### ISSUE TITLE
Third party plugins?

### ISSUE THREAD

**Issue by HiddenKn** [cockpit-project/cockpit#10017]
Hello, 

I was wondering where I can find third party plugins or packages for cockpit-project.
I've been googling for them but can't find any at all.
Is there a list of them somewhere or are they supposed to show up at the packages page?
Because the packages page is empty for me.

Kind regards,
HiddenKnowledge

p.s. Sorry I posted this as an issue, but I couldn't find a forum or anything like that.

**Comment by martinpitt** [comment]
There are a few on the Applications page in Fedora, but not on other OSes yet. There currently aren't too many third-party plugins yet, mostly [cockpit-podman](https://github.com/cockpit-project/cockpit-podman) and [Fleet Commander](https://github.com/fleet-commander/fc-admin).

**Comment by csdfgraham** [comment]
Any more plugins you are aware of?

**Comment by martinpitt** [comment]
@csdfgraham: There's a [cockpit plugin to set up a 389 directory server (part of FreeIPA)](https://pagure.io/389-ds-base) and [subscription-manager](https://github.com/candlepin/subscription-manager).

**Comment by Protektor-Desura** [comment]
Is there a list these days of all cockpit plugins available? Both official and community? It seems that Ubuntu has stopped officially supporting the docker plugin for the latest version.

**Comment by marusak** [comment]
> Is there a list these days of all cockpit plugins available? Both official and community?

No, there isn't one. Here are some notes if someone will look for the same answer:
1. Official (plugins that cockpit team directly implements) live in https://github.com/cockpit-project/
2. You can see plugins that are (correctly) packaged for your OS in `Applications` card in Cockpit
3. Anyone can do their own plugin so just looking around the internet for what you needs can yield some results.

Now as I was writing this I had and idea that we could drop some table of plugins into [README](https://github.com/cockpit-project/cockpit/blob/master/README.md) with links where these plugins are being developed. And authors of plugins could promote their product. Or we can even have it on website or so. I'll discuss this with the team on our next meeting.

> It seems that Ubuntu has stopped officially supporting the docker plugin for the latest version.

We obsoleted docker plugin and replaced it with [podman](https://github.com/cockpit-project/cockpit-podman).

**Comment by Protektor-Desura** [comment]
Will the podman plugin handle docker? I know they are suppose to be similar but just curious if the plugin will also manage docker. My understanding is podman doesn't have the support for a setup like docker compose which I use a lot, or at least not yet.

**Comment by Protektor-Desura** [comment]
On a side note a plugin for FUSE or more specifically MergerFS and SnapRAID would nice if anyone is aware of plugins to support then, I have tried searching and found nothing. They are both good for data sets that don't change a lot and are large data sets that are mostly read once created.

**Comment by marusak** [comment]
> Will the podman plugin handle docker?

No, podman diverged from docker API (mostly in adding additional functionality).

> My understanding is podman doesn't have the support for a setup like docker compose which I use a lot, or at least not yet.

https://github.com/containers/podman-compose

**Comment by garrett** [comment]
I've been collecting a list of add-ons for Cockpit on a website issue, as I'd like to highlight all of them on the website. I think it ties in nicely with this issue.

https://github.com/cockpit-project/cockpit-project.github.io/issues/348
