### ISSUE TITLE
storage: formatting a logical volume perfoms poorly design-wise

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#10014]
The current design for Logical Volume performed very poorly in the latest usability study we ran with 21 participants. A majority of the participants had issues finding the Format button under the _unrecognised data_ tab

**Comment by mtlott** [comment]
Make that a majority +1. Just flew past it three times on the UI, then googled and found this page. Went back to look for it and still was visually searching until I found it. A little color? Move it to the center for "unrecognized data".
