### ISSUE TITLE
"make dist" only ships direct node dependencies

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#10055]
The tarball made by `make dist` includes the output of webpack in `dist/` and I guess it is supposed to contain the inputs to webpack as well that end up in dist/.  However, the tarball only includes our direct dependencies that are listed in package.json under "dependencies".  It does not include indirect dependencies.

For example, dist/storaged/storage.js includes node_modules/prop-types/index.js, but node_modules/prop-types is not in the dist tarball.

Thus, the node_modules/ directory in the dist tarball is incomplete and a bit useless.  We might as well not ship any node modules.

Furthermore, the COPYING.node file is constructed from the node_modules in the dist tarball and is thus likewise incomplete and a bit misleading.

**Comment by mvollmer** [comment]
Some details: The dist tarball includes $(WEBPACK_INPUTS), which is the concatenation of all the  foo_INPUTS defined by the dist/foo/Makefile.deps files.  These Makefile fragments are generated by tools/webpack-make, which explicitly filters out any input files that do not belong to a node module listed in package.json under "dependencies".  The purpose of that filtering is seemingly to avoid putting stuff like eslint into the dist tarball, which webpack includes in its "fileDependencies", but the effect is to also filter out indirect dependencies.

**Comment by stefwalter** [comment]
It's fine to only ship direct dependencies. Webpack knowns exactly which files are to be included.

However, we definitely should enumerate the entire tree for licenses, not just the top level.

**Comment by mvollmer** [comment]
> It's fine to only ship direct dependencies. Webpack knowns exactly which files are to be included.

If we don't ship everything that's needed, we are better off shipping nothing, I'd say.

**Comment by martinpitt** [comment]
> If we don't ship everything that's needed, we are better off shipping nothing, I'd say.

I agree. We already release the cockpit-cache-XXX tarball release artifact for people who need it (that includes us for downstream patching).

I'm all for dropping node_modules/ from the release tarball and replacing it with package-lock.json. In the long run this should make cockpit-cache-XXX.tar obsolete, and in the short term it can't hurt to have it. We just need to make sure that the copyright check/generation then is also done at `make dist` time, as it won't work any more afterwards. That's the real piece of work behind this, AFAICS.

**Comment by stefwalter** [comment]
> If we don't ship everything that's needed, we are better off shipping nothing, I'd say.

Webpack knows exactly what's needed. And that's exactly what we ship.

**Comment by mvollmer** [comment]
> Webpack knows exactly what's needed to be included. And that's exactly what we ship.

No, we don't, that's the bug.  From the first comment:

> For example, dist/storaged/storage.js includes node_modules/prop-types/index.js, but node_modules/prop-types is not in the dist tarball.

**Comment by mvollmer** [comment]
> I'm all for dropping node_modules/ from the release tarball and replacing it with package-lock.json. In the long run this should make cockpit-cache-XXX.tar obsolete, and in the short term it can't hurt to have it. 

That would make us more dependent on the Internet and npm, but that's acceptable, I'd say.  We can still build the real source tarball without network.

> We just need to make sure that the copyright check/generation then is also done at make dist time, as it won't work any more afterwards. That's the real piece of work behind this, AFAICS.

For this, I think we need to find a new way to find what really is in dist/.  The foo.map.js files have that information, so it should be available from webpack somehow.

**Comment by marusak** [comment]
Fixed in https://github.com/cockpit-project/cockpit/pull/12931
