### ISSUE TITLE
storage: design issues when mounting a volume in the default location

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#10065]
In [the recent usability study](https://github.com/cockpit-project/cockpit/wiki/Usability-test-General), the default Mount behaviour was a bit confusing to many participants.
There was no indication that pressing the mount button would mount the partition at /user/run/... so I think we need to change this behaviour somehow.

**Comment by andreasn** [comment]
> "Most participants assumed clicking on ‘Mount’ button would open a dialog where they can specify the mount point and other properties. Whereas, clicking on the button automatically mount the volume on a ‘default’ path."

**Comment by andreasn** [comment]
Somewhat related:
_"Users assumed that the mounting task is done as soon as they closed the mounting dialog. However,  they still have to click ‘Mount’ button after closing the dialog to actually finish the task.
"_

**Comment by martinpitt** [comment]
I would remove the concept of a "default mount point" in Cockpit altogether IMHO. The /run/mnt/ ones are useful for desktop hotplug hardware handled by gvfs, but are not really intended for permanent configuration in /etc/fstab.

When clicking on "Mount" for a device that isn't already defined in /etc/fstab, it should just pop up the mount point dialog. If it is already defined, then "Mount" can just work (like it does now), and you can then change the mount point by clicking on the existing mount point path label. As that will then show the path that the user previously defined, it should be a lot more obvious than the "(default)" thing.

@mvollmer, WDYT?

**Comment by martinpitt** [comment]
@mvollmer, would be nice if you could have a look at my proposal above.

**Comment by mvollmer** [comment]
> I would remove the concept of a "default mount point" in Cockpit altogether IMHO.

Yes, that's what I have in mind, too.  "Mounting" with Cockpit should mean "add an entry to fstab". Also, when displaying mounts, I think Cockpit should ignore run time mounts that are not in /etc/fstab.

**Comment by andreasn** [comment]
Sounds good to me!

**Comment by mvollmer** [comment]
Fixed in #12647
