### ISSUE TITLE
domains: asking to leave when clicking an active domain is not expected behavior

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#10063]
One issue that came up in [the recent usability study](https://github.com/cockpit-project/cockpit/wiki/Usability-test-General) was that the offer to leave the domain was the first choice when clicking the domain name. Most participants expected to see more information about the domain when clicking this link. And only from there be offered to leave the domain.

**Comment by martinpitt** [comment]
I had a look at which domain properties we could/should show. I filtered out the uninteresting ones.

First, get the objects of the joined domain. It seems there's two object for a FreeIPA domain which kind of belong together:

```
$ busctl  get-property org.freedesktop.realmd /org/freedesktop/realmd  org.freedesktop.realmd.Provider Realms
ao 2 "/org/freedesktop/realmd/GenericKerberos/cockpit_lan_1" "/org/freedesktop/realmd/Sssd/cockpit_lan_2"
```

Potentially interesting GenericKerberos props (these are redundant, I think we should just show `.Name`):

```
$ busctl introspect org.freedesktop.realmd /org/freedesktop/realmd/GenericKerberos/cockpit_lan_1
org.freedesktop.realmd.Kerberos     interface -          -                                   -
.DomainName                         property  s          "cockpit.lan" 
.RealmName                          property  s          "COCKPIT.LAN"

org.freedesktop.realmd.Realm        interface -          -                                   -
.Name                               property  s          "cockpit.lan"
.SupportedInterfaces                property  as         1 "org.freedesktop.realmd.Kerberos" 
```

And the sssd one:
```
$ busctl introspect org.freedesktop.realmd /org/freedesktop/realmd/Sssd/cockpit_lan_2
org.freedesktop.realmd.Realm              interface -     
.Details                                  property  a(ss)      2 "server-software" "ipa" "client-software"  "sssd"
.LoginFormats                             property  as         1 "%U@cockpit.lan" 
```

So what we can show from that is something like

Property |  Value
------- | -------
Type | Kerberos
Domain | cockpit.lan
Login Format | %U@cockpit.lan
Server Software | ipa
Client Software | sssd

The login format isn't all that friendly, but we could replace the `%U` with the current user name, like `fred@cockpit.lan`, or replace `%U` with a generic `username` value?

So my initial reaction is that the dialog that opens when you click on a domain should get a more neutral title, show this information, and contain a [ Leave ] button (as right now) that allows you to leave the domain.  I'm less sure about the current warning text, whether it should stay in this dialog, or be shown as a second dialog when you try to leave.

**Comment by martinpitt** [comment]
Type> I don't know, I'm afraid. Apart from IPA, realmd also supports Active Directory domains, but AFAIK they should also be kerberos. But indeed let's leave this field out for now.

**Comment by andreasn** [comment]
It was more that I wondered if the label was a little bit to vague. I'm totally fine leaving it in for now.

**Comment by andreasn** [comment]
![wireframe](https://raw.githubusercontent.com/cockpit-project/cockpit-design/8d0b42fe5fd8772314ebeb01989e8f2af4d5b7d2/domains/domain-dialog.png)

**Comment by andreasn** [comment]
Indeed! I hope it's discoverable enough, but we'll find that out in user testing I think.
