### ISSUE TITLE
storage: hard to identify newly created logical volumes

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#10064]
In [the recent usability study](https://github.com/cockpit-project/cockpit/wiki/Usability-test-General) this came up as an issue.

Many participants failed to identify and edit newly created logical volumes.
The issue might be fixable with issue #10059 , but another solution might be to automatically expand newly created logical volumes

**Comment by KKoukiou** [comment]
Closing as duplicate of https://github.com/cockpit-project/cockpit/issues/10059 - let's keep one about new resources in general.
