### ISSUE TITLE
Cockpit 177 shows broken login page only when url root is '/cockpit/'

### ISSUE THREAD

**Issue by gonapps** [cockpit-project/cockpit#10073]
Only when UrlRoot is '/cockpit/'
```
$ cat /etc/cockpit/cockpit.conf
[WebService]
UrlRoot=/cockpit/
```
Some resources such as bg-plain.jpg, logo.png are not loaded in the login page.
Other UrlRoot works without problems.

**Comment by mvollmer** [comment]
Unfortunatels, using `/cockpit/` as the UrlRoot is not supported:

 https://cockpit-project.org/guide/latest/cockpit.conf.5.html

```
/cockpit/ and /cockpit+           are reserved and should not be used. For example /cockpit-new/ is ok.           /cockpit/ and /cockpit+new/ are not.
--

However, `/cockpit/` is a very natural root to use, so we should try to make this work, I'd say.

(I think the UrlRoot code can benefit from a cleanup: iirc, the root is guessed in various places from a pair of urls, and that might also be the reason why it can't be /cockpit/. It would be better to pass the root around explicitly. But I might well be wrong.)

**Comment by virtualdxs** [comment]
Any progress on this? I just discovered cockpit and hit this. I wouldn't have guessed that it was the specific url I chose were it not for this bug.

**Comment by mvollmer** [comment]
`copckpit-ws` should at least fail with a clear error message.

**Comment by mvollmer** [comment]
> Some resources such as bg-plain.jpg, logo.png are not loaded in the login page.

This is actually just a controlled re-styling of the login page, there is nothing broken here.  You should be able to login and use Cockpit just fine.  Unless there is something else that is broken by `UrlRoot=/cockpit/`, of course, but I haven't found anything yet.

What you see is the style of the login page for an embedded Cockpit.  You can directly link to, say, `https://host:9090/cockpit/@localhost/terminal` and get just the Terminal page without the navigation stuff around it.  If you need to login to that page, you get the style with the white background.

This style is selected erroneously when `UrlRoot=cockpit`.  I think #11605 fixes this.

**Comment by aldemarcalazans** [comment]
It seems the [documentation here](https://cockpit-project.org/guide/latest/cockpit.conf.5) was not updated, since Cockpit started accepting /cockpit as a valid root URL.
