### ISSUE TITLE
cockpit-ws UI  - missing separators on page logs -> problem info

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#10098]
there are missing separators on logs -> problem info page see picture
![problem info page](https://user-images.githubusercontent.com/8735467/45681592-2b159000-bb3e-11e8-8947-c005399eabb5.jpg)

**Comment by leomoty** [comment]
I filled a ticket with the same issue a while ago (#9481), albeit in my case, the spacing was broken in all tabs.
