### ISSUE TITLE
How do I switch between clusters using cockpit-kubernetes

### ISSUE THREAD

**Issue by reselbob** [cockpit-project/cockpit#10109]
I am using `cockpit-kubernetes` to visually inspect my kubernetes cluster(s). My kubernetes config supports two clusters -- one local and one external on AWS. When I added an eternal cluster, `cockpit-kubernetes` made me "troubleshoot" to declare the new cluster, which I did. I could view the added cluster, no problem. But I am at a loss about how to switch back to view my local cluster.

Thanks in advance for any help.

Here is a view of my UI: https://drive.google.com/file/d/1rYZFODLmpaFe9VdjMUDVBrOGldwLz5i-/view?usp=sharing

**Comment by martinpitt** [comment]
Go to the "Overview" page and use the wrench symbol at the top right. There you can switch between multiple clusters.
