### ISSUE TITLE
What do I do about `pkexec cockpit-bridge` authentication errors?

### ISSUE THREAD

**Issue by UntouchedWagons** [cockpit-project/cockpit#10156]
I'm trying out cockpit in a Ubuntu 18.04 virtual machine. I'm looking at the documentation and it says that if I can run `sudo cockpit-bridge` or `pkexec cockpit-bridge`without asking for a password then cockpit can do privledged stuff. But I'm prompted for a password both times and when using pkexec I get some kind of polkit authentication error:

    jordan@cockpit-test:~$ sudo cockpit-bridge
    [sudo] password for jordan: 
    cockpit-bridge: no option specified
    jordan@cockpit-test:~$ pkexec cockpit-bridge
    ==== AUTHENTICATING FOR org.freedesktop.policykit.exec ===
    Authentication is needed to run `/usr/bin/cockpit-bridge' as the super user
    Authenticating as: UntouchedWagons,,, (jordan)
    Password: 
    polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
    ==== AUTHENTICATION FAILED ===
    Error executing command as another user: Not authorized

    This incident has been reported.
    jordan@cockpit-test:~$

I've already created the wheel group, added my user to that group and logged/out and in

**Comment by UntouchedWagons** [comment]
How do I delete this issue? I realized I needed to enter the pkexec command into the web terminal. The command runs fine and doesn't ask for a password; still can't seem to do anything though

**Comment by martinpitt** [comment]
Note that users normally never run cockpit-bridge directly. This is sometimes useful for developers when debugging things. When you check the "Use my password for privileged operations" check box on the login page, the root bridge will be started automatically.
