### ISSUE TITLE
cockpit dashboard network tab cumulates network traffic (rates) from vm migration 

### ISSUE THREAD

**Issue by sandrobonazzola** [cockpit-project/cockpit#10158]
Original bug reported on oVirt bugzilla at https://bugzilla.redhat.com/show_bug.cgi?id=1632627
The above bugzilla contains full description of the issue and can be used to talk directly to the reporter.

Description of problem:
cockpit dashboard network tab cumulates network traffic (rates)
from vm migration (from) at ovirt-node and subtract it in case of migration (to).

How reproducible:
Migrate VM from and to ovirt-node (but I think it can be seen even on a plain CentOS trying to migrate a VM to another host.

**Comment by martinpitt** [comment]
This was handled upstream in ovirt, thus cockpit is the wrong upstream project.
