### ISSUE TITLE
Virtual Machines - cannot delete machines with nvram

### ISSUE THREAD

**Issue by sghosh151** [cockpit-project/cockpit#10187]
Created a UEFI vm with virt-install.
Delete VM via cockpit throws error

"error: Failed to undefine domain _< xx >_ error: Requested operation is not valid: cannot undefine domain with nvram"

**Comment by KKoukiou** [comment]
@sghosh151 thanks for reporting this. PR https://github.com/cockpit-project/cockpit/pull/10195 should fix this.
