### ISSUE TITLE
Text size is not follow the size of the browser window.

### ISSUE THREAD

**Issue by harsha-iiiv** [cockpit-project/cockpit#10213]
**Text is not responsive.**

**Comment by martinpitt** [comment]
This is rather vague -- in general, the text size is not supposed to scale with the browser size; there are certain size limits where Cockpit switches to mobile layout.

or do you have something more specific in mind?

**Comment by martinpitt** [comment]
No response in three months, and we generally *don't* want this -- text size and browser window size are independent concepts. In cockpit and on pretty well every other web site, as well as local applications.
