### ISSUE TITLE
Terminal not working for new users - II

### ISSUE THREAD

**Issue by olup** [cockpit-project/cockpit#10228]
I saw a similar issue closed from 2015 but no solutions was provided, and i think my problem is different.

Anyway, any created user cannot access the console (root can, however). The terminal display this error : 

```
couldn't change to directory: No such file or directory                             
disconnected 
```

No messages in console, in system logs or in cockpit journal.

Any ideas ??

**Comment by martinpitt** [comment]
Sounds like the user you try to login as doesn't have a valid home directory? You can check with

    getent passwd myusername | cut -f6 -d:

**Comment by KKoukiou** [comment]
I believe this is fixed with https://github.com/cockpit-project/cockpit/pull/10905
Closing the issue, please re-open if it appears again.
