### ISSUE TITLE
cockpit.spec: epoch must be unsigned integer

### ISSUE THREAD

**Issue by leomoty** [cockpit-project/cockpit#10225]
Installed Fedora 29 on my laptop. Decided to install cockpit from source. While running `sudo yum-builddep tools/cockpit.spec`, got this error:

```
warning: line 465: Possible unexpanded macro in: Provides: bundled(js-jquery) = %{npm-version:jquery}
error: line 465: Invalid version (epoch must be unsigned integer): %{npm-version:jquery}: Provides: bundled(js-jquery) = %{npm-version:jquery}
Bad spec: tools/cockpit.spec
No uninstalled build requires
```

**Comment by martinpitt** [comment]
If you do this, please use the [released spec file](https://src.fedoraproject.org/cgit/rpms/cockpit.git/tree/cockpit.spec). rpm specs are not powerful enough to support proper dynamic dependencies :(

**Comment by leomoty** [comment]
@martinpitt, thanks, will take a look after work.
