### ISSUE TITLE
Proxying cockpit cockpit container through nginx container

### ISSUE THREAD

**Issue by brennie** [cockpit-project/cockpit#10224]
Hi,

I'm attempting to reverse proxy cockpit in a container through NGINX (also through a container) and I can't seem to find any documentation about this. There is documentation about (1) running cockpit behind NGINX and (2) running it inside a container, but not the situtuation where both are in containers. If this is an impossible/unsupported configuration, the documentation should be updated to reflect that.

My NGINX configuration looks like:
```
server {
    listen 443 ssl;
    // ssl configuration

    location /cockpit-web {
        proxy_pass http://cockpit:9090;
        // proxy_set_header etc
    }
}
```

But I am getting a connection refused in the NGINX log when attempting to view `/cockpit-web`.

I am running both the containers with systemd in a Fedora atomic host environment. My service files are:

nginx.service:
```
[Unit]
Description=NGINX web server
Requires=docker.service cockpit.service
After=docker.service

[Service]
Restart=on-failure
RestartSec=10
ExecStart=/usr/bin/docker run --rm --pid host \
        -v /etc/letsencrypt/archive:/etc/letsencrypt/archive:z,ro \
        -v /etc/letsencrypt/live:/etc/letsencrypt/live:z,ro \
        -v /etc/nginx/conf.d:/etc/nginx/conf.d:Z,ro \
        -v /etc/nginx/params:/etc/nginx/params:Z,ro \
        -v /var/www:/var/www:z,ro \
        -p 80:80 \
        -p 443:443 \
        --network web \
        --name %p \
        nginx
ExecStop=-/usr/bin/docker stop -t 2 %p
ExecReload=/usr/bin/docker kill --signal=SIGHUP %p

[Install]
WantedBy=multi-user.target
```

cockpit.service:
```
[Unit]
Description=Cockpit Web Interface
Requires=docker.service
After=docker.service

[Service]
Restart=on-failure
RestartSec=10
ExecStart=/usr/bin/docker run --rm --privileged --pid host \
        -v /:/host \
        --network web \
        --name %p \
        cockpit/ws \
        /container/atomic-run --local-ssh --no-tls --address 127.0.0.1
ExecStop=-/usr/bin/docker stop -t 2 %p

[Install]
WantedBy=multi-user.target
```

However from inside the NGINX container, I cannot reach the cockpit container, even though they are on the same docker network. I attempted installing cURL and running `curl http://cockpit:9090/` inside the NGINX container but no luck.

I am *however* able to `curl http://127.0.0.1:9090` from the host. I attempted adding `--port` flags on the cockpit container to expose the port to the network manually, but then cockpit can't bind to `:9090` and crashes on start.

**Comment by martinpitt** [comment]
This is really a docker question, it has nothing to do with cockpit. Indeed it seems with `--network` they should be able to talk  to each other, but how does the nginx container resolve the `cockpit` host name? The nginx container somehow needs to learn the IP of the cockpit container, then you should be able to curl http://ip.of.cockpit.container:9090 from there.

**Comment by martinpitt** [comment]
In this case nginx does the TLS termination for you, and thus without setting `Origins` in cockpit.conf, cockpit-ws will disallow https:// origins. I'm fixing that now, but until that lands you need to explicitly allow https:// origins in cockpit.conf (see manpage).

**Comment by martinpitt** [comment]
Sorry, the previous message was for a different issue.

**Comment by martinpitt** [comment]
Closing, no reponse in a year.
