### ISSUE TITLE
Run cockpit-ws natively on iOS

### ISSUE THREAD

**Issue by subodhsri** [cockpit-project/cockpit#10242]
I was wondering if there is a chance to get cockpit to run natively on say my mac machine without any statistics or monitoring and then add different servers to monitor.

**Comment by Rohithzr** [comment]
@mvollmer exactly what I want, ill try and start building this. I can create a separate repo, but do you think it will be difficult to manage UI in two different locations?

**Comment by mvollmer** [comment]
> I can create a separate repo, but do you think it will be difficult to manage UI in two different locations?

I am not sure I understand, can you elaborate?  What two locations are you talking about?  Your repository and ours?  Or the mac that runs cockpit-ws and the Linux machine that runs cockpit-bridge?

**Comment by Rohithzr** [comment]
> > I can create a separate repo, but do you think it will be difficult to manage UI in two different locations?
> 
> I am not sure I understand, can you elaborate? What two locations are you talking about? Your repository and ours? Or the mac that runs cockpit-ws and the Linux machine that runs cockpit-bridge?

my repo and yours, seeing that your repo is a complete thing and already has the UI, I believe that another repo with just that UI might be a bit redundant.

**Comment by martinpitt** [comment]
There's some more issues to be worked out:
 - This requires glib and libssh. At first sight, building glib it on iOS should be possible, but I don't think anyone in the team has any experience with it. I don't know about libssh, but there shouldn't be fundamental barriers to building it against iOS.
 - iOS does not use glibc, so at least the cockpit-ws and cockpit-ssh code needs to be validated (and most probably fixed a bit) against iOS'es libc. In order for that to actually last, we need some free software way of putting that into CI.
 - Neither cockpit-ssh nor cockpit-ws require libsystemd, but the current build system will require it. So this needs to be split or reworked first to only build the C parts that don't use libsystemd -- i. e. not build cockpit-bridge.

These are *hard*, but if you (or anyone else) is serious about that, these need to be worked out first. IMHO it makes little sense to do some easy parts only (configure option) that nobody can actually use; these will just bitrot again.

**Comment by mvollmer** [comment]
> IMHO it makes little sense to do some easy parts only (configure option) that nobody can actually use; these will just bitrot again.

However, the options help someone with little knowledge of the cockpit sources to find the parts that actually need porting.  They represent what we can do upfront without having to do any mac os specific work.

**Comment by Rohithzr** [comment]
@martinpitt we add some stuff as "Required Pre-Requisites" 
- http://brewformulas.org/Glib
- http://brewformulas.org/libssh

also, I have not yet got a chance to go through the code, but can't it be that the UI (HTML, JS, CSS) just communicates over the ws port on server, and one can either open that ws port (using firewall, limiting IP, or via SSH tunnel)?

the UI in that way should be platform-independent.

**Comment by martinpitt** [comment]
Yes, the UI itself just talks over the websocket, so that is OS independent  -- it's just a bunch of JavaScript. That runs in the browser, and you can perfectly well use a MacOS browser like Safari to use Cockpit (that's running on some Linux box). That direction is not the problem.

But the description is about running the cockpit-webserver on MacOS. As said above, this should in principle be possible -- this only requires building cockpit-ws and cockpit-ssh. It's just a lot of work to actually do this with our build system.

**Comment by marusak** [comment]
For a year no update. @Rohithzr are you still interested in working on this?
I doubt that anyone from the team would find time to do this and external contribution would be required.

**Comment by marusak** [comment]
Seems to be abandoned. No one from the current developers will work on this. If someone will be interested in the future, it is easy to find even when closed. No need to track this actively.
