### ISSUE TITLE
Origin Registry Console Logout not working when using KeyCloak with Openshift

### ISSUE THREAD

**Issue by rhnewtron** [cockpit-project/cockpit#10253]
Having setup Openshift with OpenID Auth with Keycloak, when logging out of the Registry Console with the "Logout" link, I'm logged out of Openshift, however I am not logged out of KeyCloak. Clicking on "Login Again" and selecting the "Keycloak" Login Dialog automatically loggs me in.

The Web console of Openshift does not have this issue (If I configure the logoutUrl correctly)

**Version**

Openshift v3.9

**Steps To Reproduce**

- Deploy Openshift with Registry
- Configure Openshift with Keycloak
- Login to Openshift with Keycloak User
- Browse to Registry Console
- Logout of Registry Console
- Follow "Login Again"

**Current Result**

- You are automatically logged in using the old KeyCloak Session.

**Expected Result**

- You have to reauthenticate (Cockpit redirects to logoutUrl after logging out locally)

Also See https://github.com/openshift/origin/issues/20288

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
