### ISSUE TITLE
TestReauthorize.testBasic causes bridge crash

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#10267]
[check_reauthorize](https://fedorapeople.org/groups/cockpit/logs/pull-10252-20181009-132929-35c774e7-verify-fedora-atomic/log.html#91) sometimes fails like this:
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-reauthorize", line 53, in testBasic
    b.wait_in_text(".cockpit-internal-reauthorize span", 'result:')
testlib.Error: timeout
```
where the [screenshot](https://fedorapeople.org/groups/cockpit/logs/pull-10252-20181009-132929-35c774e7-verify-fedora-atomic/TestReauthorize-testBasic-fedora-atomic-127.0.0.2-2301-FAIL.png) shows a "disconnected". The [log](https://fedorapeople.org/groups/cockpit/logs/pull-10252-20181009-132929-35c774e7-verify-fedora-atomic/TestReauthorize-testBasic-fedora-atomic-127.0.0.2-2301-FAIL.log) shows a bridge crash.

After some umpteen retries, I was able to reproduce that locally as well. I'll now see to cramming gdb and cockpit/glib-debuginfo onto the fedora-atomic image to be able to get a full stack trace.

**Comment by martinpitt** [comment]
Unfortunately the stack trace is rather poor even with {cockpit,glib2}-debuginfo:
```
#2  0x00007f8909144d63 in g_log () from /lib64/libglib-2.0.so.0
No symbol table info available.
#3  0x0000562e3242446a in cockpit_channel_control (self=<optimized out>, command=command@entry=0x562e32442c42 "done", options=options@entry=0x0)
    at src/common/cockpitchannel.c:1041
        object = <optimized out>
        message = <optimized out>
        problem = 0x562e342df4b0 "\n"
        problem_copy = 0x0
        __func__ = "cockpit_channel_control"
#4  0x0000562e32403465 in on_files_listed (source_object=0x562e34399520, res=<optimized out>, user_data=0x562e343942e0) at src/bridge/cockpitfslist.c:118
        error = 0x0
        options = <optimized out>
        files = 0x0
        self = 0x562e343942e0
```

So this apparently fails on

    g_return_if_fail (COCKPIT_IS_CHANNEL (self));

It's "optimized out" in frame 3, but one can print it in the caller frame 4:
```
(gdb) p self
$2 = (CockpitFslist *) 0x562e343942e0
(gdb) p *self
$3 = {parent = {parent = {g_type_instance = {g_class = 0x0}, ref_count = 0, qdata = 0x0}, priv = 0x562e34394240}, path = 0x562e34372dc0 "\200\277\067\064.V", 
  monitor = 0x0, sig_changed = 0, cancellable = 0x0}
```
This looks a bit odd (ref count and g_class zero).

```c
  CockpitFslist *self = COCKPIT_FSLIST (user_data);

  if (files == NULL)
    {
      g_clear_object (&self->cancellable);
      g_object_unref (source_object);

      cockpit_channel_ready (COCKPIT_CHANNEL (self), NULL);

      if (self->monitor == NULL)
        {
          cockpit_channel_control (COCKPIT_CHANNEL (self), "done", NULL);
          cockpit_channel_close (COCKPIT_CHANNEL (self), NULL);
        }
      return;
    }
```
So apparently it still survived the `cockpit_channel_ready()`, where `self` still seems to be a valid channel, but not any more the `cockpit_channel_control()`.

This smells a bit like `on_files_listed()` is called asynchronously, and in the meantime the channel gets closed/freed?

I'm not even sure what the `fslist` channel does here -- pkg/playground/test.js's `.cockpit-internal-reauthorize` handler is just using cockpit.spawn() to run pkcheck.

**Comment by martinpitt** [comment]
@stefwalter, does this ring a bell by any chance? If not, I'll need to find some time to plaster this with debug messages and let it happen again.

**Comment by stefwalter** [comment]
Yes, this is a classic hanging pointer during async call. Will open a pull request.
