### ISSUE TITLE
Join Domain: needs polishment

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#1028]
It is better to focus Domain Address input when the dialog pops up. Join button should be disabled if domain address is empty or is not reachable.
![screenshot from 2014-08-14 10 42 20](https://cloud.githubusercontent.com/assets/3952545/3922035/ae9d508e-23c6-11e4-8bda-84f57043ac7b.png)
![screenshot from 2014-08-14 10 43 17](https://cloud.githubusercontent.com/assets/3952545/3922046/caa5de7c-23c6-11e4-91c1-ffd536178eac.png)
When click Join button twice, the details information pre element does not hide properly.
![screenshot from 2014-08-14 10 45 43](https://cloud.githubusercontent.com/assets/3952545/3922071/1164541a-23c7-11e4-8307-362e45eceeb0.png)

**Comment by martinpitt** [comment]
There was a lot of work and cleanup on the "Join Domain" dialog this year, and I believe it's quite good now.
