### ISSUE TITLE
[not an issue] [request/information] monitor custom logs

### ISSUE THREAD

**Issue by SecKarma** [cockpit-project/cockpit#10305]
Hello,

is there anyway i can monitor/show a specific log file instead of the system journal? example rails, nginx access/error logs etc...

thanks in advance
cockpit rocks

**Comment by martinpitt** [comment]
Cockpit only supports showing/filtering the journal right now. Most packaged system services should log to the journal these days, or at least can be configured to do that (i. e. log to "syslog", not to a particular file).
