### ISSUE TITLE
allow multi hash in manifest.json item paths

### ISSUE THREAD

**Issue by edospadoni** [cockpit-project/cockpit#10304]
**Description**
With this https://github.com/cockpit-project/cockpit/pull/9348 the problem with hash in item path was resolved, but it seems that is not possible handle multi path with same base path

**Example**
```json
"menu": {
    "index": {
      "label": "Menu",
      "order": 10
    },
    "/#/item-one": {
      "label": "Item One",
      "order": 100
    },
    "/#/item-two": {
      "label": "Item Two",
      "order": 200
    }
  },
```
the `item-one` and `item-two` are overwritten, it seems that wins the *last one*.

It is possible to handle also this particular case?

**Comment by edospadoni** [comment]
Does anyone have any suggestions?

**Comment by Neustradamus** [comment]
There is a problem of slash like I have informed here:
- https://github.com/cockpit-project/cockpit/issues/13171
- https://github.com/NethServer/dev/issues/5921

Have you solutions to do not have several slashs in one link?
Several examples are in specified links :)
One here: https://IP:9090/xxxx////////////#/example/blablabla

**Comment by martinpitt** [comment]
Let's not do this. Hashes should be strictly for navigating *within* a particular parge, they should not have separate  menu entries. If you want to do that, uses paths.

**Comment by Neustradamus** [comment]
@martinpitt: Have you an example?

**Comment by martinpitt** [comment]
@Neustradamus : Check the "Logs" page. When you apply a filter, this will become part of the URL, so that it becomes bookmark-able. E.g. http://localhost:9090/system/logs#/?priority=alert&tag=kernel 

Just like in classic static HTML pages, `#` are anchors within a page.
