### ISSUE TITLE
Add Disk: needs warning and button controlling

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#1031]
There might be a warning info like create volume group dialog if there are no availabe disks;
And the Add button should be disabled properly.
![screenshot from 2014-08-14 11 29 39](https://cloud.githubusercontent.com/assets/3952545/3924569/d1d5fe94-23de-11e4-9fb0-509e7a29f3a7.png)
![screenshot from 2014-08-14 13 27 01](https://cloud.githubusercontent.com/assets/3952545/3924568/d1d5fc96-23de-11e4-98da-ad0c3247ba97.png)

**Comment by mvollmer** [comment]
This is still open, and valid for both RAID and LVM.
