### ISSUE TITLE
Rename Volume Group: needs restrictions on name

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#1033]
The Rename button should be processed.
Validation of name is needed.
Make it focused automatically.
![screenshot from 2014-08-14 16 43 42](https://cloud.githubusercontent.com/assets/3952545/3926883/8ce9f2e2-23f5-11e4-81a5-7a71a525acf2.png)
![screenshot from 2014-08-14 16 42 33](https://cloud.githubusercontent.com/assets/3952545/3926884/8cedbf58-23f5-11e4-8c7c-2cc8712576e5.png)
![screenshot from 2014-08-14 16 42 45](https://cloud.githubusercontent.com/assets/3952545/3926885/8cee9d88-23f5-11e4-9e70-34f54f10f191.png)

**Comment by mvollmer** [comment]
This is fixed.
