### ISSUE TITLE
Inconsistent contents of RAID Devices

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#1037]
The contents are not consistent when we create a new RAID device and when we refresh the Storage page.
![screenshot from 2014-08-15 23 02 31](https://cloud.githubusercontent.com/assets/3952545/3940768/6fe27126-24f2-11e4-8f81-9f58a2e8a147.png)
![screenshot from 2014-08-15 23 02 47](https://cloud.githubusercontent.com/assets/3952545/3940767/6fe24cb4-24f2-11e4-9fdd-6be0acf7dcdb.png)

The same problem occurs when we navigate back to the Storage page from the RAID Device details page.

**Comment by mvollmer** [comment]
This doesn't seem to happen anymore.
