### ISSUE TITLE
Don't show RAID devices and Other Devices after removing a RAID device

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#1038]
There is no need to show the empty RAID devices content board in the Storage page after removing a RAID device. 
Other Devices board always shows up after removing a RAID device even if there is no one.
![screenshot from 2014-08-16 23 24 48](https://cloud.githubusercontent.com/assets/3952545/3943684/1c6d06a6-25be-11e4-9725-5e5effef20fd.png)
![screenshot from 2014-08-17](https://cloud.githubusercontent.com/assets/3952545/3943683/1c6a7ec2-25be-11e4-9a1d-7e6d24db75a4.png)

**Comment by mvollmer** [comment]
This has been redesigned and fixed.
