### ISSUE TITLE
Connection to remote via bastion host does not respect ProxyCommand

### ISSUE THREAD

**Issue by daankets** [cockpit-project/cockpit#10418]
I have a bastion host behind which several other hosts are reachable over SSH. On the cockpit host, I have edited /etc/ssh/ssh_config, and added a rule for `*.subdomain.domain.ext` to connect via a **ProxyCommand**. However, cockpit seems to attempts DNS resolution to the host before attempting the SSH connection. Which doesn't work for remote hosts hidden behind a bastion.

```
Cockpit could not contact the given host whatever.subdomain.domain.ext:22. Make sure it has ssh running on port 22, or specify another port in the address.
```

I think that, even though DNS resolution fails, Cockpit should still attempt to connect via SSH. Possibly, the DNS lookup shouldn't even be needed?

**Comment by martinpitt** [comment]
#10318 landed a while ago in Cockpit 186, so this should work now.

**Comment by naclander** [comment]
@martinpitt Have you verified that this works? I still seem to be getting the same error as described by @daankets

**Comment by naclander** [comment]
Seems related to #11296
