### ISSUE TITLE
Navigation mechanism does not work on the Journal page

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#1043]
When we are on the journal page, all navigation methods provided by the browser cannot navaigate us back to server main page. Is it supposed to be like this? @andreasn @stefwalter @mvollmer

**Comment by andreasn** [comment]
As far as I can tell, this still happens.
To duplicate:

* Start on the System page
* Go to the logs page
* Click on any entry
* Click on the back button in the browser (this will take you back to the logs main page)
* Click on the back button again (this will not take you back to the system page, but to the individual log entry again, and if you click back again, it loops back to the logs page...)

**Comment by marusak** [comment]
This is known issue - there are problems with navigating back in more places in cockpit. needs fixing for sure.

**Comment by marusak** [comment]
I opened #13091 to track this better, since this is happening on more places and was reported more times
