### ISSUE TITLE
Cockpit requires subscription manager

### ISSUE THREAD

**Issue by hjmallon** [cockpit-project/cockpit#10434]
Installing cockpit-system on CentOS 7.5 installs subscription manager and friends and enables them. I do not want this stuff as this is a CentOS, not RHEL, box.

Maybe this is a question for the EPEL packager rather than upstream on what to do?

**Comment by martinpitt** [comment]
Duplicate of #10132. This got fixed in version 180. I'm afraid this won't be picked up by CentOS 7.5 any more, though, you'll have to wait for 7.6.
