### ISSUE TITLE
Machines: labels are misaligned in the Add Disks dialog

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#10492]
![screenshot from 2018-11-02 12-18-20](https://user-images.githubusercontent.com/209895/47912598-86ef6a80-de99-11e8-9062-46e2ce204812.png)

**Comment by garrett** [comment]
Misalignment of labels and widgets is a problem in PatternFly*, but this looks particularly severe. My first thought assumption is that class names are not being used appropriately here. 

_* Alignment of labels and widgets should be off by a couple pixels at most — this is a lot more than that._

**Comment by martinpitt** [comment]
This got fixed by the form-layout rework.
