### ISSUE TITLE
Machines: unable to create o list machines if host is already VM (but supports nested virt)

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#10495]
although I'm able to install machines (This host has enabled nested virtualization) via ``virt-install`` and list them via ``virsh`` and ``libvirtd`` is running there

I'm not able to list this machine via cockpit web and also unable to create new one, becuase it says that this host is already VM

![image](https://user-images.githubusercontent.com/8735467/47916986-5cf17480-dea8-11e8-82f5-ed7d545be13a.png)

```
# virt-install --name ahoj --memory 1024 --import --disk=rhel-atomic-cloud-7.4.3-8.x86_64.qcow2
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.
WARNING  Unable to connect to graphical console: virt-viewer not installed. Please install the 'virt-viewer' package.
WARNING  No console to launch for the guest, defaulting to --wait -1

Starting install...
Domain installation still in progress. Waiting for installation to complete.

# virsh list
 Id    Name                           State
----------------------------------------------------
 1     ahoj                           running

# systemctl status libvirtd
● libvirtd.service - Virtualization daemon
   Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-11-02 09:00:33 EDT; 6min ago
     Docs: man:libvirtd(8)
           https://libvirt.org
 Main PID: 16071 (libvirtd)
    Tasks: 19 (limit: 32768)
   Memory: 21.8M
   CGroup: /system.slice/libvirtd.service
           ├─14654 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-sc>
           ├─14655 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-sc>
           └─16071 /usr/sbin/libvirt
# hostname
host-8-247-1...
```

**Comment by andreasn** [comment]
@martinpitt as a packaging recommendation, should cockpit-machines and cockpit-machines-ovirt be mutually exclusive? On eg. Fedora since cockpit-machines-ovirt replaces cockpit-machines in the UI?

**Comment by andreasn** [comment]
Suggestion on how we could solve the disconnected state so it communicates better what's going on.
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/e9fe3cacdab81763d8da0ae20925f03e62be4d6b/virtual-machines/ovirt-node-emptystate.png)

**Comment by andreasn** [comment]
The disabled button originates from https://github.com/cockpit-project/cockpit/issues/8767#issuecomment-371104372 (implemented in #9037) but I think I made the wrong call there.
I think we should hide the button instead, since whatever the administrator does, there is technically no way to make the button active.

**Comment by andreasn** [comment]
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/297fcdc855d450eb570e791106ea6c8f701b9df6/virtual-machines/ovirt-node-emptystate.png)

Some language adjustment based on feedback from the oVirt designers. You're connecting to an Engine not a cluster, that is a separate concept. Also changed the location of the detailed explanation text in the dialog.

**Comment by marusak** [comment]
ovirt plugin is not maintained in upstream anymore. If this  issue is still valid and you want to get it fixed, please open  downstream (bugzilla) bug.
