### ISSUE TITLE
When updating to cockpit 181-1.fc29 giving blank pages.

### ISSUE THREAD

**Issue by idcm** [cockpit-project/cockpit#10506]
It seems the new version does not support Chinese, but I use a browser the default language is Chinese. I have to set the http header Accept-Language to en to see the  normal page. The old version works very well.

**Comment by martinpitt** [comment]
Fixed in https://github.com/cockpit-project/cockpit/commit/13a7126086e7ca7e441f3d2ad71410c7de772c82 , will be in today's release 184.
