### ISSUE TITLE
machines: Inconsistent location of error notifications in modal dialogs 

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#10526]
![error-notify-add-disk](https://user-images.githubusercontent.com/14921356/48135528-7b3ae400-e29d-11e8-876e-986113dc4280.png)
--------------------------------------------------
![error-notify-create](https://user-images.githubusercontent.com/14921356/48135529-7bd37a80-e29d-11e8-9ca6-a49304a48888.png)
--------------------------------------------------
![error-notify-edit-nic](https://user-images.githubusercontent.com/14921356/48135530-7bd37a80-e29d-11e8-8ec0-02b2c8cfb907.png)

@garrett can you please tell me which error notification sign I should use in modals and in which position in the dialog it should appear because I noticed some inconsistency. Thanks :)

**Comment by garrett** [comment]
I wrote up a nice detailed reply earlier, but it got lost as gnome-session crashed and brought down all of Wayland and Firefox + GitHub didn't save the reply. Oops. I'll try again, but this time shorter:

PatternFly upstream seems to have notifications at the top of dialogs, like hehre: https://www.patternfly.org/pattern-library/forms-and-controls/errors-and-validation/

PatternFly also suggests placing errors that apply to fields next to fields to make it clear how to fix the problem.

Cockpit seems to typically place in-dialog errors below the content of the dialog, but before the dialog action buttons, as to not shift down all the forms when there's a problem.

Generally, I like the idea of not moving elements that someone would interact with. However, I think adding context to error messages by proximity of where they originate from is more important than shifting widgets.

---

All the above taken into consideration, I'd suggest the following:

1. Move error messages _below_ the forms and above the dialog action buttons.
2. Remove the close button from the warnings. (Inline errors should be checked on the fly and disappear when corrected. In these cases, when the input is not empty, the message should go away.)
3. Move the required name warnings next to the form that is required.
4. Consider marking the fields as required. (See [PatternFly: Field Labelling](https://www.patternfly.org/pattern-library/forms-and-controls/field-labeling/))
5. Change the "network settings failed" error message to be friendlier. (See below.)

---

The network settings failed error message should be more like:

> **Network settings could not be saved**
> Error message: `member name is invalid in dbus "call": GetXMLDesc-test`

(The specific message should be wrapped in `<samp>` most likely. It should be monospaced and look like pre, but wrap. The samp tag similar to `<code>` or `<kbd>`, but means "here's a sample from what the computer said". FWIW: Code is source code, kbd is what someone would type into a computer. These are all generally shown in a monospaced font and sometimes wrap `<pre>` too.)

It would be nice to also state how to fix the problem. I'm not sure what would fix it here. Trying again? or what?

**Comment by KKoukiou** [comment]
@garrett what do you think as a first enhancement step?

VCPU error old             |  VCPU error new
:-------------------------:|:-------------------------:
![vcpu-error-old](https://user-images.githubusercontent.com/14921356/48413656-aebbb980-e748-11e8-9439-00557951f5bb.png)  |  ![vcpu-fake-error-modal](https://user-images.githubusercontent.com/14921356/48413419-fdb51f00-e747-11e8-9ffd-d2f64db57b77.png)



VCPU warning old             |  VCPU warning new
:-------------------------:|:-------------------------:
![vcpu-footer-old](https://user-images.githubusercontent.com/14921356/48413563-5f758900-e748-11e8-900b-249d1b9e5833.png)  |  ![vcpu-footer-warning](https://user-images.githubusercontent.com/14921356/48413421-fe4db580-e747-11e8-810c-e3830f4bc3b9.png)


Same for other dialogs:


NIC error old             |  VCPU error new
:-------------------------:|:-------------------------:
![error-notify-edit-nic](https://user-images.githubusercontent.com/14921356/48413740-efb3ce00-e748-11e8-80c3-a023f6cc13ec.png) | ![nic-fake-error](https://user-images.githubusercontent.com/14921356/48413748-f2aebe80-e748-11e8-89fa-3c56a89f4541.png)

**Comment by garrett** [comment]
:+1: Great! I like the improvements so far!
