### ISSUE TITLE
RAID devices have the same name

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#1053]
Creating multiple RAID devices with the same name is allowed.
![screenshot from 2014-08-20 12 42 54](https://cloud.githubusercontent.com/assets/3952545/3984859/8c499e60-288b-11e4-8db6-7251d54e7f67.png)

Creating a RAID device with empty name in Cockpit will create the RAID named after the number of /dev/mdXXX.
![screenshot from 2014-08-20 12 45 22](https://cloud.githubusercontent.com/assets/3952545/3984889/cdfdab80-288b-11e4-9e7f-073972be2382.png)
Is that the default behavior of mdadm @mvollmer ?

**Comment by mvollmer** [comment]
> Is that the default behavior of mdadm @mvollmer ?

Yes, two raids with the same name seem to be allowed.
