### ISSUE TITLE
Adding additional log files

### ISSUE THREAD

**Issue by kaysond** [cockpit-project/cockpit#10538]
Is there a way to include multiple log files in the Logs section? I'm using `rsyslog` and I have a few facilities going to files; those don't show up.

**Comment by kaysond** [comment]
No. The ones that are sent to files via rsyslog.conf do in fact show up in journalctl, but I have a handful of applications that generate their own logs. Those I do not see.

**Comment by KKoukiou** [comment]
As Andreas mentioned, Logs page manipulated only with the journal logs. I don't think we want to support other sources, since it will cause issues, regarding how to group the logs regarding severity etc.

**Comment by marusak** [comment]
Yes, we show exactly what `journalctl` would show. Showing different logs would be possible to do with custom plugin through https://github.com/cockpit-project/starter-kit/
