### ISSUE TITLE
storage: no indication of loading

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#10535]
It takes about 3 seconds before the storage page loads for me (with shift+reload), and during that time, there is no indication it's loading data.
https://andreasn.portknox.net/s/Gb7KTeDjGdQx2BS

**Comment by andreasn** [comment]
Maybe it could have a spinner on the screen, like the Virtual Machines page does.

**Comment by andreasn** [comment]
Here is the profile.json-file that I recorded using the Firefox performance tool. Not sure it has any good data of what's going on, because I'm pretty bad at reading this
https://andreasn.portknox.net/s/3GNgZA44ZK7teC3

**Comment by garrett** [comment]
Mozilla just happened to post this week on how to use the JSON from Firefox (and other browsers and languages) with speedscope.app: https://hacks.mozilla.org/2018/11/cross-language-performance-profile-exploration-with-speedscope/

A bit more documentation of [speedscope.app](https://www.speedscope.app/) is at https://github.com/jlfwong/speedscope

**Comment by mvollmer** [comment]
We now have a spinner while loading, as part of the scaling tuning in #11559, but I forgot to add this issue to the commit message.
