### ISSUE TITLE
Subpages not highlighted as section

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#10545]
When I'm in the toplevel network navigation the item in the sidebar is highlighted, but not when I go to the Firewall subpage.

![screenshot from 2018-11-09 13-42-59](https://user-images.githubusercontent.com/209895/48263156-77d26480-e425-11e8-9500-404592e5606a.png)
![screenshot from 2018-11-09 13-42-52](https://user-images.githubusercontent.com/209895/48263157-77d26480-e425-11e8-9f05-e0cc32bebc54.png)

**Comment by marusak** [comment]
This is a tricky one, but definitely something we should fix. Happens also with hw info.
