### ISSUE TITLE
Don't allow removing the last disk of a RAID device

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#1054]
We should not remove the last disk of a RAID device, otherwise it will cause an error, which leaves an empty RAID device without any disk, and we cannot delete the RAID device. The device is also showed up in the Disks utitlity provided by Fedora, also cannot be deleted. Rebooting seems like the only way to get rid of thie "Zombie" device.
![screenshot from 2014-08-20 10 15 52](https://cloud.githubusercontent.com/assets/3952545/3986609/6689d094-289c-11e4-8017-5ada784aafdb.png)

When I try to delete it, it says:
![screenshot from 2014-08-20 15 02 03](https://cloud.githubusercontent.com/assets/3952545/3986620/7faafaa8-289c-11e4-89f0-59a85bd822a5.png)

**Comment by mvollmer** [comment]
This is still open.
