### ISSUE TITLE
Score tests

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#10543]
* [ ] FAIL: tests-score

**Comment by cockpituous** [comment]
tests-score in progress on thinner.
Log: http://mvo.fedorapeople.org/logs/tests-score-10543-20181109-105959/log

**Comment by cockpituous** [comment]
no learn host environment variable: $COCKPIT_LEARN_SERVICE_HOST: http://mvo.fedorapeople.org/logs/tests-score-10543-20181109-105959/log

**Comment by cockpituous** [comment]
tests-score in progress on thinner.
Log: http://mvo.fedorapeople.org/logs/tests-score-10543-20181109-110000/log
