### ISSUE TITLE
Don't show this message when add a disk to a RAID 4 device

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#1058]
I got this when I added a disk whose capacity was not greater than or equal to existing ones
![screenshot from 2014-08-21 09 57 07](https://cloud.githubusercontent.com/assets/3952545/3997290/27d5a02e-293e-11e4-9da9-a9edf09aa744.png)

**Comment by marusak** [comment]
I am no expert in storage and raid, but it seems that this error is in place, isn't it?
Or is it just broken workflow, that it shows the message earlier than it should?

**Comment by mvollmer** [comment]
What's wrong here is labelling this as "Unexpected error".  Cockpit should explicitly know about this common failure mode and guide the user better, maybe.  Or we could just say "Error".

**Comment by mvollmer** [comment]
I feel this is good enough, actually.
