### ISSUE TITLE
test: rewrite testlib.py separated classes and cleaner python module

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#10597]
## rewrite files in tests/common directory
* split ``testlib.py`` to more files 
* rewrite  python files in ``common`` directory to better python module.
  * with (imports like ``from .somemodule import something``)

similar to rewriting https://github.com/cockpit-project/cockpit/pull/10582

## Benefits
 * easier/smaller imports
 * easier to use it by external projects
 * remove duplicated parts in ``test/avocado/run-test`` for tap output and similar

**Comment by KKoukiou** [comment]
Let's close this - it's very old - and just a code refactor issue.
If you want to refactor the code just do it - let's not keep open issues for that since cockpit users don't get any benefit out of it.
