### ISSUE TITLE
Getting Ooops on safari with SecurityError

### ISSUE THREAD

**Issue by minostauros** [cockpit-project/cockpit#10618]
Using latest Safari 12.0 with MacOS Mojave 10.14, and cannot use cockpit web interface, after login, it displays Ooops! and nothing works. Chrome works perfectly.
Looking into developer console, found SecurityError below.

Server is running on Ubuntu 16.04 with latest cockpit using apt install.

`[Error] SecurityError: Attempt to use history.replaceState() more than 100 times per 30.000000 seconds
	replaceState (index.js:3639)
	jump (index.js:3639)
	u (index.js:3110)
	(anonymous function) (index.js:3261:95)
	dispatch (jquery.js:2739:93)
	trigger (jquery.js:4624)
	o (index.js:74)
	overlay (index.js:165)
	s (index.js:229)
	n (index.js:251)
	(anonymous function) (index.js:312)
	dispatch (jquery.js:2739:93)
	l (cockpit.js:55)
	o (cockpit.js:162)
	d (cockpit.js:517)
	x (cockpit.js:438)
	dispatch_data (cockpit.js:365)`

**Comment by garrett** [comment]
Is this still happening for you?

I tried Safari on macOS Mojave just now and it works perfectly fine here.

**Comment by minostauros** [comment]
I have stopped using cockpit so I cannot recheck. Closing this issue. Thanks!
