### ISSUE TITLE
Accessibility: Docker Images Buttons

### ISSUE THREAD

**Issue by leomoty** [cockpit-project/cockpit#10629]
When you open an image detail, under "Used by Containers":

It is not entirely clear what the checkmark button does and it is missing a title, "Stop Container" button is also missing a title. 

![image](https://user-images.githubusercontent.com/1463740/48801042-860c6480-ecf2-11e8-9991-82e43891b5cc.png)

I am also able to break the button sometimes, by toggling it:

```
jquery.js:6922 Uncaught TypeError: Cannot read property 'off' of null
    at jquery.js:6922
    at HTMLDivElement.a (jquery.js:6785)
    at HTMLDivElement.r (jquery.js:2595)
    at HTMLDivElement.handle (jquery.js:5837)
    at HTMLDivElement.dispatch (jquery.js:2739)
    at HTMLDivElement.v.handle (jquery.js:2626)
    at Object.trigger (jquery.js:4624)
    at HTMLDivElement.<anonymous> (jquery.js:4670)
    at Function.each (jquery.js:179)
    at x.fn.init.each (jquery.js:80)
    at x.fn.init.trigger (jquery.js:4669)
    at r (jquery.js:5825)
```

**Comment by KKoukiou** [comment]
@leomoty Thanks for the feedback. Indeed the checkmark button is not really clear what it is supposed to do. I was not able to break the buttons however.

Are you interested to post patch for this? We can ask the designers for guidelines in this case.

**Comment by KKoukiou** [comment]
@leomoty great! @garrett @andreasn any idea how we should redesign these buttons (at least the checkmark) to be more self explanatory in what it does? Shall we just add tooltips or change the icon as well?

**Comment by garrett** [comment]
Oh. Is this one of those checkmark buttons that's to toggle the selection? I think we had one of those elsewhere (in storage?), but it exposed checkboxes to perform an action on a row. Here, it seems to toggle play/stop into delete (with running images having a disabled delete).

It's a weird toggle state that's basically trying to work around a confirmation dialog, I think? 

@andreasn: Would this be clearer as a delete button next to the play/stop button, and a confirmation dialog (as it's a destructive action that has no undo)?

(BTW: I'd consider this more of a usability issue, not really an accessibility issue. Although, the interaction might become an accessibility challenge too, as the toggle state is so far away from what it toggles, and there's no clear way to get it back, so navigating around with a keyboard or with a screen reader would be extra confusing.)

**Comment by garrett** [comment]
Page screenshots, for context:

![screenshot_2019-01-07 containers - sunny](https://user-images.githubusercontent.com/10246/50782022-1dc81100-12a7-11e9-94a6-2721397307bf.png)

And the same, but with the checkbox button in the header of the list clicked:

![screenshot_2019-01-07 containers - sunny 1](https://user-images.githubusercontent.com/10246/50782046-291b3c80-12a7-11e9-835a-c92450e39c7d.png)

**Comment by KKoukiou** [comment]
@leomoty yes we need design here from @garrett :) Just docker page is not in high priority, especially with cockpit-podman trying to get more focus, so excuse us for the delays.

**Comment by leomoty** [comment]
No problem, thanks for the answer, I'll read a bit about podman.

**Comment by marusak** [comment]
We [announced](https://cockpit-project.org/blog/cockpit-215.html) deprecation of cockpit-docker. This is not something that is supported in cockpit-podman, so closing.
