### ISSUE TITLE
persistent metrics vs. Store Performance data

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#10626]
It's called one thing before it's installed, and another once it's installed.
Maybe best to call it Persistent metrics in both places, since it's the shorter label.
@garrett thoughts?

**Comment by garrett** [comment]
So the action would be:

"Enable persistent metrics" vs. "Store performance data"?

We could do a hybrid of "**Store metrics**", which is even shorter. I suppose "store" could be a noun in addition to a verb though too, so it might not be as clear? "**Keep metrics**"... as keep is _usually_ not a noun (unless you're talking about a castle's strongest part, like "Bowser's Keep", or a person "store keep").

Alternatively, part 3: "**Enable stored metrics**". A little longer, but completely clear.

**Comment by andreasn** [comment]
![screenshot from 2018-11-22 16-45-49](https://user-images.githubusercontent.com/209895/48912510-1a530480-ee76-11e8-98e9-789df598a67a.png)
![screenshot from 2018-11-22 16-32-36](https://user-images.githubusercontent.com/209895/48912512-1a530480-ee76-11e8-993c-9062ddee9b88.png)

**Comment by andreasn** [comment]
I'm not 100% sure about the wording, but I can't really come up with anything better, so I think we can go with this. Can always test it later.

**Comment by garrett** [comment]
We could have the off/on toggle be off by default, click to toggle on... and have an intermediate state while it is installing software. There should also be some indication that it is installing. I guess right now, we have a confirmation dialog, right?

It feels more correct to me than a link that changes into a toggle.

**Comment by garrett** [comment]
> We could have…

⇒ Probably a different PR for the future :wink:
