### ISSUE TITLE
Running docker containers do not show it the browser

### ISSUE THREAD

**Issue by SyCode7** [cockpit-project/cockpit#10656]
Hi, installed cockpit last week, however I do not see the running docker containers in the UI.

**Comment by martinpitt** [comment]
Can you please send a screenshot? Which operating system are you on? Do you have the cockpit-docker package installed?

**Comment by SyCode7** [comment]
@martinpitt it works after installing `cockpit-docker`. Sorry, I did not know I had to do install it separately. Thank you 👍  

Is there a list of other packages somewhere ?

**Comment by martinpitt** [comment]
You can use "yum search cockpit" or "apt search cockpit" (depending on your OS). Some extensions are also visible in the "Applications" cockpit menu (you need cockpit-packagekit for that).
