### ISSUE TITLE
Disks link doesn't work if cockpit-storaged is not installed

### ISSUE THREAD

**Issue by mykaul** [cockpit-project/cockpit#10663]
If the plugin is not installed, the disks should not be a hyper-link. It leads to a bad experience. Alternatively (my preferred one) is that it should be installed by default - by I assume it's a bit harder as it relies on udisks2 running?

**Comment by martinpitt** [comment]
Can you please send a screenshot which "Disks" link you mean? The "Storage" page shouldn't be on the menu without cockpit-storage, so I suppose there's some link in some page.

**Comment by mykaul** [comment]
Click on the 'Disk I/O' link and you'll get ''Not Found' error (link is https://localhost:9091/storage )
Before:
![screenshot from 2018-11-26 10-58-13](https://user-images.githubusercontent.com/4655593/49003260-43bbab00-f16a-11e8-8461-8b6a34a8ec9f.png)

After:
![screenshot from 2018-11-26 10-59-35](https://user-images.githubusercontent.com/4655593/49003328-5fbf4c80-f16a-11e8-84ff-32180d222a18.png)
