### ISSUE TITLE
machines: disks source list is misaligned vertically

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#10676]
As seen in #10669, disks source for each VM is misaligned to the top of the cell. At first, I thought it was a CSS issue — but it's actually because the source is an embedded table in the cell.

The issue seems to stem from [vmDiskSourceCell.jsx, around line 46 - 50](https://github.com/cockpit-project/cockpit/blob/master/pkg/machines/components/vmDiskSourceCell.jsx#L46-L50) and also the use of [InfoRecord in 30 - 32](https://github.com/cockpit-project/cockpit/blob/master/pkg/machines/components/vmDiskSourceCell.jsx#L30-L32).

This bit of code looks as though the list of sources can be > 1. If so, then can we make it a list instead?

Else, if it can only ever be one item, can we just strip it out from the `<table>`?

**Comment by garrett** [comment]
Obligatory screenshot:

![screenshot_2018-11-26 virtual machines - sunny - crop](https://user-images.githubusercontent.com/10246/49018713-6a8ad900-f18c-11e8-8f93-2b7fe7087243.png)

**Comment by garrett** [comment]
I fixed this in CSS; finalizing a patch as a part of a PR that bundles a bunch of list-related fixes & optimizations.

**Comment by KKoukiou** [comment]
JFTR source can be more than one elements, and it's quite common. So that's why <table> was used.

**Comment by garrett** [comment]
@KKoukiou: OK! Hopefully I solved it in a way where that still works as expected in #10695.
