### ISSUE TITLE
lib: cause list to overflow with a scroll past a certain height

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#10677]
The height could be an add-on class for the list, a fixed size based on font-size + padding for the list, or relative to the available height on the viewport.

(I'm thinking the latter.)

This should help solve an issue for long lists inside of list panels, as speculated on https://github.com/cockpit-project/cockpit/pull/10537#issuecomment-440743923 and mentioned at https://github.com/cockpit-project/cockpit/issues/10654#issuecomment-441655429, to make the interaction with a contextual action button, like in https://github.com/cockpit-project/cockpit/issues/10654#issuecomment-441300946, more discoverable — even on long lists.

Downside is the possibility of having multiple scrollable areas in a page, but I think not discovering the action button outweighs the problem. In most cases, it probably won't even be an issue.

**Comment by marusak** [comment]
This is rather old issue and there hasn't  been any change in this.
@garrett so you suggest that we should just enforce some certain height in the list library and make the content scrollable? Would you be interested in implementing this?

**Comment by garrett** [comment]
We're working on porting our lists to PF4, so any possible implementation of this would change completely.

**Comment by KKoukiou** [comment]
It's not clear to me which lists you are talking about. Is this issue something not relevant any more? If we don't have any concrete examples which are problematic let's close this.

**Comment by garrett** [comment]
Yeah, closing. This was about our old list implementation, so it's not really relevant anymore.

We're using PF4 now and if this would come up again, we could open a new PF4-related issue (in both Cockpit and PatternFly projects).
