### ISSUE TITLE
machines: overlapping text & layout issues in machine overview

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#10689]
The overview in machine details has two layout-related issues:

1. text is overlapping on the emulated machine
2. not enough padding at the bottom

![screenshot_2018-11-27 virtual machines - sunny](https://user-images.githubusercontent.com/10246/49103024-9f755980-f27a-11e8-84af-767736f73d20.png)

**Comment by garrett** [comment]
Perhaps we should use the same CSS grid code for forms in dialogs in PR #10703?

**Comment by martinpitt** [comment]
PR #10695 fixes issue 2. here, but 1. is still current.

**Comment by garrett** [comment]
Oh right! I made a proper fix for the other half in a commit in #10793 — specifically https://github.com/cockpit-project/cockpit/pull/10793/commits/7b9b4c051c441ba575bf8d0e8d58d63965d1e47e

It's the first non-dialog use of form-layout. :wink:
