### ISSUE TITLE
machines: disk vs. volume

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#10685]
I'm a bit confused what the correct term is here, since it seems we use both a bit interchangeably.
![screenshot from 2018-11-27 14-11-40](https://user-images.githubusercontent.com/209895/49083980-7ccd4b80-f24e-11e8-9f9a-617dde70fb33.png)
![screenshot from 2018-11-27 14-11-26](https://user-images.githubusercontent.com/209895/49083981-7ccd4b80-f24e-11e8-8536-a464af50835c.png)

**Comment by andreasn** [comment]
It seems oVirt has one section for Disks and one for Volumes, so maybe there is some subtle difference between them I'm unaware of.

**Comment by KKoukiou** [comment]
```Storage pools``` and ```Storage volumes``` is a way of libvirt to do storage management. AFAIK OVirt does **not** use libvirt ```Storage pools and volumes```.

If you want you can read here about pools and volumes, https://libvirt.org/storage.html.
Quoting from the link:
```A storage pool is a quantity of storage set aside by an administrator, for use by virtual machines. Storage pools are divided into storage volumes by the system administrator, and the volumes are assigned to VMs as block devices.```

So to make things a bit cleaner, virtual machines disks don't need necessarily the idea of pools and volumes to work. In ```cockpit-machines``` however, at least for now we don't allow the user other way to create disks, other than create a volume on a pool or use an existing volume from a pool.

**Comment by andreasn** [comment]
Cool, let's close this one then. Thanks for the clarification!
