### ISSUE TITLE
Question: ZFS

### ISSUE THREAD

**Issue by Chris230291** [cockpit-project/cockpit#10681]
Hi all. From what I gather this supports ZFS monitoring but not managing? The managing part isnt that important for me but I would like to make sure it will report any issues with my pool?

Looks great!

Thanks,
Chris

**Comment by martinpitt** [comment]
That's correct, Cockpit does not have any ZFS specific management UI such as volume management. You should be able to do the basic operations like mounting and unmounting, though (possibly with custom mount options).

**Comment by Chris230291** [comment]
Thanks
