### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#1069]
I am a little confused about the graph of memory usage, I am not sure which level of the memory it represents, and there is a big difference between Cockpit and Fedora monitor, the memory usage presented by Cockpit is greater than 10GB most of the time.
![screenshot from 2014-08-22 15 57 11](https://cloud.githubusercontent.com/assets/3952545/4016765/56895e4c-2a38-11e4-9425-e3683c7dda01.png)
@andreasn @stefwalter @mvollmer @puiterwijk

**Comment by stefwalter** [comment]
Fixed by 5ea06f9ab4244ae5cf1cc5350312e7b88bfaa239

**Comment by Ben1980** [comment]
I still have the same issue with fedora 24 server

**Comment by stefwalter** [comment]
> I still have the same issue with fedora 24 server

Which version of Cockpit? Choose 'about' in the menu in the upper right corner.

**Comment by Ben1980** [comment]
Version 0.112.
The one which is shiped with Fedora 24.
I did all updates, so maybee there is only an update of the repository necessary.
![image](https://cloud.githubusercontent.com/assets/919260/16947966/61ef819a-4db2-11e6-921e-5be5ff5bb683.png)
![image](https://cloud.githubusercontent.com/assets/919260/16947972/66deddcc-4db2-11e6-931b-4cbfbeb11f45.png)

**Comment by Ben1980** [comment]
Is there some new information? Cockpit is accumulating used and cache together:
![image](https://cloud.githubusercontent.com/assets/919260/17092695/8d20aae2-5244-11e6-83ba-8ab487af6a71.png)
![image](https://cloud.githubusercontent.com/assets/919260/17092701/9019d08e-5244-11e6-9c04-909d4eb52ec1.png)

**Comment by brlarini** [comment]
Version 141 from EPEL (el7) shows double the max memory in the memory details (not in the graph from main screen, this one is ok). My server has 16GB, but the graph goes up to 32GB.

**Comment by lodicolo** [comment]
I'm seeing the same thing as @Ben1980 on v151 from EPEL (running CentOS 7.4).

`free -tm` output:
```
              total        used        free      shared  buff/cache   available
Mem:           1839         146         689          16        1003        1468
Swap:             0           0           0
Total:         1839         146         689
```

System graph:
![image](https://user-images.githubusercontent.com/1476550/35468839-fa96c0c2-02f4-11e8-8102-3085838c4ec8.png)

Detailed graph:
![image](https://user-images.githubusercontent.com/1476550/35468833-e8830918-02f4-11e8-8eff-e72c21c943c0.png)

The graphs seem a little misleading since they're lumping multiple variables together and presenting it as "used".

**Comment by Gaboros** [comment]
Same here.

![image](https://user-images.githubusercontent.com/4209157/53001153-499ff000-342a-11e9-9924-d81985cdbedd.png)

Have 3,8 GB memory and it's says 6.52. Also the usage is under 2 GB and it's says 4 gb used.
