### ISSUE TITLE
Using cockpit on debian with a reverse proxy

### ISSUE THREAD

**Issue by DavidFW1960** [cockpit-project/cockpit#10707]
Hi @martinpitt 

I am trying to access cockpit via a reverse proxy (Caddy)

I have a duckdns domain and I have defined a subdomain for cockpit... https://cpit.domain.duckdns.org

When I try and access the web interface, it asks me to login which I do and it then displays a blank page. Pretty sure I have left something out of the setting for the sub-domain. All my other connections are to docker containers and work.

Any idea what I am missing??

This is my caddyfile..
```
domain.duckdns.org {
    header / {
    Strict-Transport-Security "max-age=31536000; includeSubdomains"
    X-XSS-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "SAMEORIGIN"
    Referrer-Policy "same-origin"
    -Server
}
cpit.domain.duckdns.org {
    proxy / localhost:19090 {
        websocket
        transparent
    }
}
```

I'm sure it's something pretty simple I am missing

**Comment by DavidFW1960** [comment]
I see there is supposed to be /etc/cockpit/cockpit.conf but that file does not exist. Do I just create one?

**Comment by martinpitt** [comment]
I'm afraid I don't know about caddy, but our wiki has some reverse proxy recipes for [nginx](https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX) and [Apache](https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-Apache-with-LetsEncrypt).

Note: Your caddyfile specifies port 19090, but did you actually change (or add) that port in `cockpit.socket`? The default is 9090. I suppose you did change that, as you can  see the login page, I'm just curious.

I suggest to open the browser's developer console (Ctrl+Shift+K in Firefox), go to the "Network" tool, and try to log into Cockpit page. There you can see more details which queries it tries to do and which file it fails on. The JS Console log may also have an error message, can you please check that as  well?

Which Cockpit version are you running? In 183 (released two days ago) we [fixed an issue](https://github.com/cockpit-project/cockpit/commit/67161f6d84267ac35e5fae03543b8ef15b5e5e99) that was previously breaking some reverse proxies. So trying with that is useful as well.

**Comment by mvollmer** [comment]
Could you check the Browser console (Ctrl-Shift-K) for error messages etc?  Try reloading the page while the console is open and look for failed HTTP requests.

A blank page after login is what happens when Cockpit can't open its WebSocket.  In that case, you should see a failed request for `/cockpit/socket` and lots of `transport closed, dropped message` lines in the log.

(Cockpit only checks whether the _Browser_ supports WebSocket, but the behavior is not very nice when the actual WebSocket request fails.  Maybe we should improve that, if only to make debugging easier.)

**Comment by DavidFW1960** [comment]
Martin - changed to 19090 because something else was using 9090.

I’ll check failed http requests tomorrow. Thanks.

**Comment by DavidFW1960** [comment]
ok so I'm a little confused now!!!
As I said before, I did not have any file here  /etc/cockpit/cockpit.conf  so I created one with the contents I posted above and still got the blank page.

Today I was going to https://local-ip-address:19090 as I always have and I'm getting the white page!! I do not understand why this is happening.

Then I tried the domain for it.. https://cpit.domain.duckdns.org and the damn thing WORKED.... What is happening here? Did the cockpit.conf file not get read and activated immediately? That actually doesn't make that much sense...

Happy it's working but wish I understood why now and why the local ip won't work now..

**Comment by DavidFW1960** [comment]
So I can't access via local ip address:19090 anymore - I get the white page. I added https://10.90.11.100:19090 to the cockpit.conf file but it won't connect - well it connects and I login but get the whitepage again. Is it possible to use both here? (the duckdns and local ip?)

**Comment by SamsonMcNulty** [comment]
I've been having similar issues but using traefik as my reverse proxy. I was able to determine that from my cell phone and from IE I am able to login without the blank white page appearing however logging in from chrome brings me to the same blank page. I have the cockpit.conf file configured the same as listed above. The chrome console outputs the following on successful auth:

`[DOM] Password field is not contained in a form: (More info: <URL>) 
cockpit.bluewillows.net/:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input class=​"form-control credential-password" autocomplete=​"off" value type=​"password">​
cockpit.bluewillows.net/:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input class=​"form-control credential-password" autocomplete=​"off" value type=​"password">​
cockpit.bluewillows.net/:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input class=​"form-control credential-old" autocomplete=​"off" value type=​"password">​
cockpit.bluewillows.net/:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input class=​"form-control credential-new" autocomplete=​"off" value type=​"password">​
cockpit.bluewillows.net/:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input class=​"form-control credential-two" autocomplete=​"off" value type=​"password">​
cockpit.js:438 transport closed, dropped message:  
{"bus":"internal","payload":"dbus-json3","command":"open","channel":"1"}
cockpit.js:438 transport closed, dropped message:  1
{"add-match":{"path":"/machines","interface":"cockpit.Machines"}}
cockpit.js:438 transport closed, dropped message:  1
{"watch":{"path":"/machines","interface":"cockpit.Machines"},"id":"2"}
cockpit.js:438 transport closed, dropped message:  1
{"type":"s","call":["/user","org.freedesktop.DBus.Properties","GetAll",["cockpit.User"]],"id":"3"}
cockpit.js:438 transport closed, dropped message:  
{"command":"authorize"}
cockpit.js:438 transport closed, dropped message:  
{"payload":"null","command":"open","channel":"2"}
index.js:3618 transport closed: no-session
(anonymous) @ index.js:3618
cockpit.js:438 transport closed, dropped message:  
{ "command": "init", "version": 1 }
cockpit.js:392 received unsupported version in init message: undefined
_ @ cockpit.js:392
cockpit.js:438 transport closed, dropped message:  
{"superuser":"try","payload":"dbus-json3","name":"org.freedesktop.PackageKit","command":"open","channel":"1"}
cockpit.js:438 transport closed, dropped message:  1
{"timeout":5000,"call":["/org/freedesktop/PackageKit","org.freedesktop.PackageKit","CreateTransaction",[]],"id":"1"}
cockpit.js:438 transport closed, dropped message:  
{"bus":"internal","payload":"dbus-json3","command":"open","channel":"2"}
cockpit.js:438 transport closed, dropped message:  2
{"type":"s","call":["/user","org.freedesktop.DBus.Properties","GetAll",["cockpit.User"]],"id":"1"}
cockpit.js:438 transport closed, dropped message:  
{"payload":"fswatch1","path":"/etc/motd","command":"open","channel":"3"}
cockpit.js:438 transport closed, dropped message:  
{"payload":"fsread1","path":"/etc/motd","command":"open","channel":"4"}
cockpit.js:438 transport closed, dropped message:  
{"bus":"system","payload":"dbus-json3","name":"org.freedesktop.timedate1","command":"open","channel":"5"}
cockpit.js:438 transport closed, dropped message:  5
{"add-match":{"path":"/org/freedesktop/timedate1","interface":"org.freedesktop.timedate1"}}
cockpit.js:438 transport closed, dropped message:  5
{"watch":{"path":"/org/freedesktop/timedate1","interface":"org.freedesktop.timedate1"},"id":"2"}
cockpit.js:438 transport closed, dropped message:  
{"superuser":"try","payload":"dbus-json3","name":"org.freedesktop.systemd1","command":"open","channel":"6"}
cockpit.js:438 transport closed, dropped message:  6
{"add-match":{"path":"/org/freedesktop/systemd1","interface":"org.freedesktop.systemd1.Manager"}}
cockpit.js:438 transport closed, dropped message:  6
{"watch":{"path":"/org/freedesktop/systemd1","interface":"org.freedesktop.systemd1.Manager"},"id":"2"}
cockpit.js:438 transport closed, dropped message:  
{"payload":"stream","spawn":["date","+%s:%:z"],"err":"message","command":"open","channel":"7"}
cockpit.js:438 transport closed, dropped message:  
{"bus":"system","payload":"dbus-json3","name":"com.redhat.SubscriptionManager","command":"open","channel":"8"}
cockpit.js:438 transport closed, dropped message:  8
{"add-match":{"path":"/EntitlementStatus","interface":"com.redhat.SubscriptionManager.EntitlementStatus","member":"entitlement_status_changed"}}
cockpit.js:438 transport closed, dropped message:  8
{"call":["/EntitlementStatus","com.redhat.SubscriptionManager.EntitlementStatus","check_status",[]],"id":"2"}
cockpit.js:438 transport closed, dropped message:  
{"payload":"fsread1","path":"/etc/machine-id","command":"open","channel":"9"}
cockpit.js:438 transport closed, dropped message:  
{"superuser":true,"payload":"dbus-json3","name":"org.projectatomic.rpmostree1","command":"open","channel":"10"}
cockpit.js:438 transport closed, dropped message:  10
{"add-match":{"path":"/org/projectatomic/rpmostree1/Sysroot","interface":"org.projectatomic.rpmostree1.Sysroot"}}
cockpit.js:438 transport closed, dropped message:  10
{"watch":{"path":"/org/projectatomic/rpmostree1/Sysroot","interface":"org.projectatomic.rpmostree1.Sysroot"},"id":"2"}
cockpit.js:438 transport closed, dropped message:  
{"superuser":"try","payload":"dbus-json3","name":"org.freedesktop.hostname1","command":"open","channel":"11"}
cockpit.js:438 transport closed, dropped message:  11
{"add-match":{"path":"/org/freedesktop/hostname1","interface":"org.freedesktop.hostname1"}}
cockpit.js:438 transport closed, dropped message:  11
{"watch":{"path":"/org/freedesktop/hostname1","interface":"org.freedesktop.hostname1"},"id":"2"}
cockpit.js:438 transport closed, dropped message:  
{"payload":"metrics1","interval":1000,"source":"pcp-archive","metrics":[{"name":"mem.util.used","units":"bytes"}],"timestamp":-300055,"limit":300,"command":"open","channel":"12"}
cockpit.js:438 transport closed, dropped message:  
{"payload":"metrics1","interval":1000,"source":"pcp-archive","metrics":[{"name":"network.interface.total.bytes","units":"bytes","derive":"rate"}],"omit-instances":["lo"],"timestamp":-300057,"limit":300,"command":"open","channel":"13"}
cockpit.js:438 transport closed, dropped message:  
{"payload":"metrics1","interval":1000,"source":"pcp-archive","metrics":[{"name":"disk.all.total_bytes","units":"bytes","derive":"rate"}],"timestamp":-300058,"limit":300,"command":"open","channel":"14"}
cockpit.js:438 transport closed, dropped message:  
{"payload":"stream","spawn":["cat","/proc/meminfo","/proc/cpuinfo"],"command":"open","channel":"15"}
cockpit.js:438 transport closed, dropped message:  
{"payload":"stream","spawn":["grep","-r","."],"directory":"/sys/class/dmi/id","err":"ignore","superuser":"try","command":"open","channel":"16"}
cockpit.js:438 transport closed, dropped message:  
{"payload":"stream","spawn":["hostname"],"err":"ignore","command":"open","channel":"17"}
cockpit.js:438 transport closed, dropped message:  
{"bus":"system","payload":"dbus-json3","name":"org.freedesktop.realmd","command":"open","channel":"18"}
cockpit.js:438 transport closed, dropped message:  18
{"watch":{"path":"/org/freedesktop/realmd"},"id":"1"}
cockpit.js:438 transport closed, dropped message:  18
{"add-match":{"interface":"org.freedesktop.realmd.Realm","path_namespace":"/"}}
cockpit.js:438 transport closed, dropped message:  18
{"watch":{"interface":"org.freedesktop.realmd.Realm","path_namespace":"/"},"id":"2"}
cockpit.js:438 transport closed, dropped message:  
{"superuser":"try","payload":"dbus-json3","name":"org.freedesktop.systemd1","command":"open","channel":"19"}
cockpit.js:438 transport closed, dropped message:  19
{"add-match":{"path":"/org/freedesktop/systemd1","interface":"org.freedesktop.systemd1.Manager"}}
cockpit.js:438 transport closed, dropped message:  19
{"watch":{"path":"/org/freedesktop/systemd1","interface":"org.freedesktop.systemd1.Manager"},"id":"2"}
cockpit.js:438 transport closed, dropped message:  
{"superuser":true,"payload":"dbus-json3","name":"com.redhat.tuned","command":"open","channel":"20"}
cockpit.js:438 transport closed, dropped message:  20
{"call":["/Tuned","com.redhat.tuned.control","is_running",[]],"id":"1"}
cockpit.js:438 transport closed, dropped message:  20
{"call":["/Tuned","com.redhat.tuned.control","active_profile",[]],"id":"2"}
cockpit.js:438 transport closed, dropped message:  20
{"call":["/Tuned","com.redhat.tuned.control","recommend_profile",[]],"id":"3"}
cockpit.js:419 received message before init:  hint
S @ cockpit.js:419
contentscript.ts:119 Connection established.
contentscript.ts:120 Portname: (...)onDisconnect: (...)onMessage: (...)sender: {id: "elnfhbjabfcepfnaeoehffgmifcfjlha"}__proto__: Object
contentscript.ts:21 sendRequest
contentscript.ts:22 Object
system.js:1670 Couldn't calculate server time offset: Server has closed the connection.
system.js:2520 Failed to query RHEL subscription status: ue
(anonymous) @ system.js:2520
system.js:1871 Error reading machine id te
(anonymous) @ system.js:1871
system.js:1805 Checking for available updates failed: Server has closed the connection.
(anonymous) @ system.js:1805
cockpit.js:438 transport closed, dropped message:  
{"payload":"metrics1","interval":1000,"source":"direct","metrics":[{"name":"mem.util.used","units":"bytes"}],"command":"open","channel":"21"}
cockpit.js:438 transport closed, dropped message:  
{"payload":"metrics1","interval":1000,"source":"direct","metrics":[{"name":"disk.all.total_bytes","units":"bytes","derive":"rate"}],"command":"open","channel":"22"}
cockpit.js:438 transport closed, dropped message:  
{"payload":"metrics1","interval":1000,"source":"direct","metrics":[{"name":"network.interface.total.bytes","units":"bytes","derive":"rate"}],"omit-instances":["lo"],"command":"open","channel":"23"}
system.js:1686 can't get NTPSynchronized property ue {problem: "disconnected", name: null, message: "Server has closed the connection.", toString: ƒ}
system.js:1686 can't get NTPSynchronized property ue {problem: "disconnected", name: null, message: "Server has closed the connection.", toString: ƒ}
system.js:1686 can't get NTPSynchronized property ue {problem: "disconnected", name: null, message: "Server has closed the connection.", toString: ƒ}
system.js:1686 can't get NTPSynchronized property ue {problem: "disconnected", name: null, message: "Server has closed the connection.", toString: ƒ}
system.js:1686 can't get NTPSynchronized property ue {problem: "disconnected", name: null, message: "Server has closed the connection.", toString: ƒ}
system.js:1686 can't get NTPSynchronized property ue {problem: "disconnected", name: null, message: "Server has closed the connection.", toString: ƒ}
system.js:1686 can't get NTPSynchronized property ue {problem: "disconnected", name: null, message: "Server has closed the connection.", toString: ƒ}
system.js:1686 can't get NTPSynchronized property ue {problem: "disconnected", name: null, message: "Server has closed the connection.", toString: ƒ}
system.js:1686 can't get NTPSynchronized property ue {problem: "disconnected", name: null, message: "Server has closed the connection.", toString: ƒ}`

**Comment by Fyb3roptik** [comment]
0.0.0.0:19090 should support all ip's

**Comment by DavidFW1960** [comment]
so potentially if I was to set:
```
Origins = https://cpit.domain.duckdns.org, ip-address-of-server
```
it would work? instead of 0.0.0.0?

**Comment by Fyb3roptik** [comment]
No, origin should be what ip the client has, not the server. So if you want to access it from everywhere, it will need to be 0.0.0.0

**Comment by SamsonMcNulty** [comment]
That was not clear by the man page but I think that's more of a fault on my part. Thanks for the clarification, That fixes everything for me lol.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
