### ISSUE TITLE
obfuscate/encode links

### ISSUE THREAD

**Issue by mqmq0** [cockpit-project/cockpit#10726]
Hello All,

Its more of a question rather then an issue. I'm trying to figure out how to "hide" my cockpit instance on my company network.
I had set up an Nginx revers proxy to access my server from outside of my network, which is working fine. Now I want to make it less obvious what I'm connecting to, from a monitored network.
How do I change https://whatever.mydomain.com/system/terminal --> https://whatever.mydomain.com/sdfCGfe3f1 or something similar.
Or, can I change the name of the Terminal app: /system/terminal --> /system/whatever?

Thanks for the help.

**Comment by martinpitt** [comment]
You can set `UrlRoot=` in [cockpit.conf](https://cockpit-project.org/guide/latest/cockpit.conf.5.html) for that.

**Comment by martinpitt** [comment]
Ah, this doesn't work, I'm afraid. The last part of the path is baked into the code of the pages.
