### ISSUE TITLE
Embed only system resource graphs

### ISSUE THREAD

**Issue by c-mart** [cockpit-project/cockpit#10720]
I want to embed these awesome resource graphs in [another application](https://gitlab.com/exosphere/exosphere/) without also bringing in the "info table". It would be awesome if we could embed each of these components separately.

![screenshot from 2018-12-01 16-54-42](https://user-images.githubusercontent.com/13605043/49334109-64309e80-f58a-11e8-8d21-48109729840e.png)

I can stick `https://my-server.net:9090/cockpit/@localhost/system/index.html` into an iframe but that brings in everything from `system/index.html`, so I need to do [terrible, fragile things](https://stackoverflow.com/a/14117980) in order to show only the graphs. It would be wonderful if we could embed something like `index.html/#graphs` to get only the graphs!

**Comment by martinpitt** [comment]
With the planned System overview page redesign in issue #13121 we actually plan to kick out the graphs into a subpage anyway. That should solve this, so this issue is still current.

**Comment by c-mart** [comment]
Hi @martinpitt. #13121 is closed but it's unclear if this is also resolved, can you please advise?

**Comment by c-mart** [comment]
@martinpitt et al., how's it going? I'd like to know if we can display just the graphs as a subpage. I don't see it in your [docs](https://cockpit-project.org/guide/latest/api-shell-html.html). Thank you!

**Comment by martinpitt** [comment]
Yes, that works with recent releases -- http://localhost:9090/cockpit/@localhost/system/graphs.html
