### ISSUE TITLE
testTopology (check_kubernetes.TestKubernetes) is flaky

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#10735]
92% on verify/fedora-29
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-080202-39912702-verify-fedora-29/log)
 - [pull-10702](http://fedorapeople.org/groups/cockpit/logs/pull-10702-20181129-141919-c2050988-verify-fedora-29/log)
 - [pull-10636](http://fedorapeople.org/groups/cockpit/logs/pull-10636-20181122-082525-a518b483-verify-fedora-29/log)
 - [pull-10582](http://fedorapeople.org/groups/cockpit/logs/pull-10582-20181116-094545-79c78c4a-verify-fedora-29/log)
 - [pull-10427](http://fedorapeople.org/groups/cockpit/logs/pull-10427-20181122-111010-0a1418cb-verify-fedora-29/log)
 - [pull-10340](http://fedorapeople.org/groups/cockpit/logs/pull-10340-20181019-083838-a295980d-verify-fedora-29/log)
 - [pull-10316](http://fedorapeople.org/groups/cockpit/logs/pull-10316-20181016-120808-38d91307-verify-fedora-29/log)

<details><summary>Source material</summary>

```json
{
  "test": [
    [
      "testTopology (check_kubernetes.TestKubernetes)",
      13
    ]
  ],
  "status": [
    [
      "failure",
      13
    ]
  ],
  "tracker": [
    [
      null,
      13
    ]
  ],
  "context": [
    [
      "verify/fedora-29",
      13
    ]
  ],
  "merged": [
    [
      true,
      12
    ],
    [
      null,
      1
    ]
  ],
  "date": [
    "2018-09-03T18:34:44Z",
    "2018-11-29T15:05:42Z"
  ]
}
```
</details>

**Comment by marusak** [comment]
kubernetes is out of master, I don't think anyone will take a look at this anymore
