### ISSUE TITLE
testBasic (check_docker_storage.TestDockerStorage) is flaky

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#10737]
80% on verify/fedora-atomic
 - [pull-10427](http://fedorapeople.org/groups/cockpit/logs/pull-10427-20181105-082121-a8b7dec3-verify-fedora-atomic/log)
 - [pull-10427](http://fedorapeople.org/groups/cockpit/logs/pull-10427-20181105-082121-a8b7dec3-verify-fedora-atomic/log)
 - [pull-10427](http://fedorapeople.org/groups/cockpit/logs/pull-10427-20181105-082121-a8b7dec3-verify-fedora-atomic/log)
 - [pull-10318](http://fedorapeople.org/groups/cockpit/logs/pull-10318-20181016-144141-607fb33f-verify-fedora-atomic/log)
 - [pull-10318](http://fedorapeople.org/groups/cockpit/logs/pull-10318-20181016-144141-607fb33f-verify-fedora-atomic/log)
 - [pull-10318](http://fedorapeople.org/groups/cockpit/logs/pull-10318-20181016-144141-607fb33f-verify-fedora-atomic/log)
 - [pull-10318](http://fedorapeople.org/groups/cockpit/logs/pull-10318-20181016-135252-4dc0dddb-verify-fedora-atomic/log)
 - [pull-10318](http://fedorapeople.org/groups/cockpit/logs/pull-10318-20181016-135252-4dc0dddb-verify-fedora-atomic/log)
 - [pull-10318](http://fedorapeople.org/groups/cockpit/logs/pull-10318-20181016-135252-4dc0dddb-verify-fedora-atomic/log)

100% on verify/rhel-atomic
 - [pull-10318](http://fedorapeople.org/groups/cockpit/logs/pull-10318-20181016-144646-607fb33f-verify-rhel-atomic/log)
 - [pull-10318](http://fedorapeople.org/groups/cockpit/logs/pull-10318-20181016-144646-607fb33f-verify-rhel-atomic/log)
 - [pull-10318](http://fedorapeople.org/groups/cockpit/logs/pull-10318-20181016-144646-607fb33f-verify-rhel-atomic/log)

<details><summary>Source material</summary>

```json
{
  "test": [
    [
      "testBasic (check_docker_storage.TestDockerStorage)",
      25
    ]
  ],
  "status": [
    [
      "failure",
      25
    ]
  ],
  "tracker": [
    [
      null,
      25
    ]
  ],
  "context": [
    [
      "verify/fedora-atomic",
      25
    ]
  ],
  "merged": [
    [
      true,
      20
    ],
    [
      false,
      5
    ]
  ],
  "date": [
    "2018-08-06T09:52:37Z",
    "2018-11-05T08:59:30Z"
  ]
}
{
  "test": [
    [
      "testBasic (check_docker_storage.TestDockerStorage)",
      11
    ]
  ],
  "status": [
    [
      "failure",
      11
    ]
  ],
  "tracker": [
    [
      null,
      11
    ]
  ],
  "context": [
    [
      "verify/rhel-atomic",
      11
    ]
  ],
  "merged": [
    [
      true,
      11
    ]
  ],
  "date": [
    "2018-09-01T21:19:57Z",
    "2018-10-16T15:28:44Z"
  ]
}
```
</details>

**Comment by KKoukiou** [comment]
These old issues for flakes are not helpful since the links are not accessible anymore.
