### ISSUE TITLE
testStoragePools (check_machines_dbus.TestMachinesDBus) is flaky

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#10732]
100% on verify/rhel-x
 - [pull-10537](http://fedorapeople.org/groups/cockpit/logs/pull-10537-20181108-160606-5feb13ce-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181111-095757-8844ddd8-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181111-095757-8844ddd8-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181111-095757-8844ddd8-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181109-145252-1ffba003-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181109-145252-1ffba003-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181109-145252-1ffba003-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181108-124747-e2a1570e-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181108-124747-e2a1570e-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181108-124747-e2a1570e-verify-rhel-x/log)

<details><summary>Source material</summary>

```json
{
  "test": [
    [
      "testStoragePools (check_machines_dbus.TestMachinesDBus)",
      13
    ]
  ],
  "status": [
    [
      "failure",
      13
    ]
  ],
  "tracker": [
    [
      null,
      13
    ]
  ],
  "context": [
    [
      "verify/rhel-x",
      13
    ]
  ],
  "merged": [
    [
      true,
      13
    ]
  ],
  "date": [
    "2018-11-08T10:08:02Z",
    "2018-11-11T10:23:26Z"
  ]
}
```
</details>

**Comment by KKoukiou** [comment]
This are is not correctly marked as flake. In boths PRs tests were failing before merging.
