### ISSUE TITLE
testNetworks (check_machines_virsh.TestMachinesVirsh) is flaky

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#10738]
91% on verify/fedora-i386
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161616-418abe4b-verify-fedora-i386/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-095959-f74d483a-verify-fedora-i386/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-073232-39912702-verify-fedora-i386/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-163333-f78fb903-verify-fedora-i386/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-075252-69a7dcae-verify-fedora-i386/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123131-12fdc93a-verify-fedora-i386/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123131-12fdc93a-verify-fedora-i386/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123131-12fdc93a-verify-fedora-i386/log)

91% on verify/fedora-28
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161717-418abe4b-verify-fedora-28/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161717-418abe4b-verify-fedora-28/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161717-418abe4b-verify-fedora-28/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-100707-f74d483a-verify-fedora-28/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-075151-39912702-verify-fedora-28/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181012-091919-ae20f6b6-verify-fedora-28/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-162121-f78fb903-verify-fedora-28/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-074646-69a7dcae-verify-fedora-28/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122525-12fdc93a-verify-fedora-28/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122525-12fdc93a-verify-fedora-28/log)

87% on verify/debian-stable
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-095858-f74d483a-verify-debian-stable/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-073434-39912702-verify-debian-stable/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-164141-f78fb903-verify-debian-stable/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-074949-69a7dcae-verify-debian-stable/log)
 - [pull-10512](http://fedorapeople.org/groups/cockpit/logs/pull-10512-20181106-133939-a755d3a5-verify-debian-stable/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122424-12fdc93a-verify-debian-stable/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122424-12fdc93a-verify-debian-stable/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122424-12fdc93a-verify-debian-stable/log)

93% on verify/debian-testing
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-095959-f74d483a-verify-debian-testing/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-095757-e86488c4-verify-debian-testing/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-074040-39912702-verify-debian-testing/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-163636-f78fb903-verify-debian-testing/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-161919-11dd8c4e-verify-debian-testing/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-074848-69a7dcae-verify-debian-testing/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122828-12fdc93a-verify-debian-testing/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122828-12fdc93a-verify-debian-testing/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122828-12fdc93a-verify-debian-testing/log)

86% on verify/ubuntu-stable
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-101818-f74d483a-verify-ubuntu-stable/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-073434-39912702-verify-ubuntu-stable/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-163131-f78fb903-verify-ubuntu-stable/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-075151-69a7dcae-verify-ubuntu-stable/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122828-12fdc93a-verify-ubuntu-stable/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122828-12fdc93a-verify-ubuntu-stable/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122828-12fdc93a-verify-ubuntu-stable/log)

90% on verify/rhel-7-5-distropkg
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-100404-f74d483a-verify-rhel-7-5-distropkg/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-075959-39912702-verify-rhel-7-5-distropkg/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-164343-f78fb903-verify-rhel-7-5-distropkg/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-074848-69a7dcae-verify-rhel-7-5-distropkg/log)

87% on verify/rhel-x
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-163030-418abe4b-verify-rhel-x/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-163030-418abe4b-verify-rhel-x/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-100707-f74d483a-verify-rhel-x/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-100101-e86488c4-verify-rhel-x/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-080101-39912702-verify-rhel-x/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-163434-f78fb903-verify-rhel-x/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-074848-69a7dcae-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123434-12fdc93a-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123434-12fdc93a-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123434-12fdc93a-verify-rhel-x/log)

91% on verify/centos-7
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161818-418abe4b-verify-centos-7/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161818-418abe4b-verify-centos-7/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-100707-f74d483a-verify-centos-7/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-075555-39912702-verify-centos-7/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181012-093030-ae20f6b6-verify-centos-7/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-162121-f78fb903-verify-centos-7/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-075454-69a7dcae-verify-centos-7/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122727-12fdc93a-verify-centos-7/log)

80% on verify/fedora-29
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-100000-f74d483a-verify-fedora-29/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-080202-39912702-verify-fedora-29/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-163535-f78fb903-verify-fedora-29/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-081111-69a7dcae-verify-fedora-29/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122424-12fdc93a-verify-fedora-29/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122424-12fdc93a-verify-fedora-29/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122424-12fdc93a-verify-fedora-29/log)

92% on verify/rhel-7-6-distropkg
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161919-418abe4b-verify-rhel-7-6-distropkg/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161919-418abe4b-verify-rhel-7-6-distropkg/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161919-418abe4b-verify-rhel-7-6-distropkg/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-095858-f74d483a-verify-rhel-7-6-distropkg/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181015-080606-39912702-verify-rhel-7-6-distropkg/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-163434-f78fb903-verify-rhel-7-6-distropkg/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181011-074949-69a7dcae-verify-rhel-7-6-distropkg/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123030-12fdc93a-verify-rhel-7-6-distropkg/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123030-12fdc93a-verify-rhel-7-6-distropkg/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123030-12fdc93a-verify-rhel-7-6-distropkg/log)

<details><summary>Source material</summary>

```json
{
  "test": [
    [
      "testNetworks (check_machines_virsh.TestMachinesVirsh)",
      23
    ]
  ],
  "status": [
    [
      "failure",
      23
    ]
  ],
  "tracker": [
    [
      null,
      23
    ]
  ],
  "context": [
    [
      "verify/fedora-i386",
      23
    ]
  ],
  "merged": [
    [
      true,
      21
    ],
    [
      false,
      2
    ]
  ],
  "date": [
    "2018-08-30T16:22:44Z",
    "2018-10-18T13:04:10Z"
  ]
}
{
  "test": [
    [
      "testNetworks (check_machines_virsh.TestMachinesVirsh)",
      23
    ]
  ],
  "status": [
    [
      "failure",
      23
    ]
  ],
  "tracker": [
    [
      null,
      23
    ]
  ],
  "context": [
    [
      "verify/fedora-28",
      23
    ]
  ],
  "merged": [
    [
      true,
      21
    ],
    [
      false,
      2
    ]
  ],
  "date": [
    "2018-08-30T16:44:41Z",
    "2018-10-18T13:08:34Z"
  ]
}
{
  "test": [
    [
      "testNetworks (check_machines_virsh.TestMachinesVirsh)",
      16
    ]
  ],
  "status": [
    [
      "failure",
      16
    ]
  ],
  "tracker": [
    [
      null,
      16
    ]
  ],
  "context": [
    [
      "verify/debian-stable",
      16
    ]
  ],
  "merged": [
    [
      true,
      14
    ],
    [
      false,
      2
    ]
  ],
  "date": [
    "2018-08-31T15:14:55Z",
    "2018-11-06T14:31:24Z"
  ]
}
{
  "test": [
    [
      "testNetworks (check_machines_virsh.TestMachinesVirsh)",
      16
    ]
  ],
  "status": [
    [
      "failure",
      16
    ]
  ],
  "tracker": [
    [
      null,
      16
    ]
  ],
  "context": [
    [
      "verify/debian-testing",
      16
    ]
  ],
  "merged": [
    [
      true,
      15
    ],
    [
      false,
      1
    ]
  ],
  "date": [
    "2018-08-31T15:22:24Z",
    "2018-10-18T12:55:28Z"
  ]
}
{
  "test": [
    [
      "testNetworks (check_machines_virsh.TestMachinesVirsh)",
      15
    ]
  ],
  "status": [
    [
      "failure",
      15
    ]
  ],
  "tracker": [
    [
      null,
      15
    ]
  ],
  "context": [
    [
      "verify/ubuntu-stable",
      15
    ]
  ],
  "merged": [
    [
      true,
      13
    ],
    [
      false,
      2
    ]
  ],
  "date": [
    "2018-08-31T15:31:47Z",
    "2018-10-22T20:46:39Z"
  ]
}
{
  "test": [
    [
      "testNetworks (check_machines_virsh.TestMachinesVirsh)",
      11
    ]
  ],
  "status": [
    [
      "failure",
      11
    ]
  ],
  "tracker": [
    [
      null,
      11
    ]
  ],
  "context": [
    [
      "verify/rhel-7-5-distropkg",
      11
    ]
  ],
  "merged": [
    [
      true,
      10
    ],
    [
      false,
      1
    ]
  ],
  "date": [
    "2018-08-31T15:35:23Z",
    "2018-10-17T17:04:33Z"
  ]
}
{
  "test": [
    [
      "testNetworks (check_machines_virsh.TestMachinesVirsh)",
      16
    ]
  ],
  "status": [
    [
      "failure",
      16
    ]
  ],
  "tracker": [
    [
      null,
      16
    ]
  ],
  "context": [
    [
      "verify/rhel-x",
      16
    ]
  ],
  "merged": [
    [
      true,
      14
    ],
    [
      false,
      2
    ]
  ],
  "date": [
    "2018-08-31T15:40:00Z",
    "2018-10-18T13:01:33Z"
  ]
}
{
  "test": [
    [
      "testNetworks (check_machines_virsh.TestMachinesVirsh)",
      12
    ]
  ],
  "status": [
    [
      "failure",
      12
    ]
  ],
  "tracker": [
    [
      null,
      12
    ]
  ],
  "context": [
    [
      "verify/centos-7",
      12
    ]
  ],
  "merged": [
    [
      true,
      11
    ],
    [
      false,
      1
    ]
  ],
  "date": [
    "2018-08-31T15:52:20Z",
    "2018-10-18T13:04:12Z"
  ]
}
{
  "test": [
    [
      "testNetworks (check_machines_virsh.TestMachinesVirsh)",
      15
    ]
  ],
  "status": [
    [
      "failure",
      15
    ]
  ],
  "tracker": [
    [
      null,
      15
    ]
  ],
  "context": [
    [
      "verify/fedora-29",
      15
    ]
  ],
  "merged": [
    [
      true,
      12
    ],
    [
      false,
      3
    ]
  ],
  "date": [
    "2018-09-17T12:27:00Z",
    "2018-10-18T13:09:45Z"
  ]
}
{
  "test": [
    [
      "testNetworks (check_machines_virsh.TestMachinesVirsh)",
      13
    ]
  ],
  "status": [
    [
      "failure",
      13
    ]
  ],
  "tracker": [
    [
      null,
      13
    ]
  ],
  "context": [
    [
      "verify/rhel-7-6-distropkg",
      13
    ]
  ],
  "merged": [
    [
      true,
      12
    ],
    [
      false,
      1
    ]
  ],
  "date": [
    "2018-09-25T05:53:52Z",
    "2018-10-18T14:13:55Z"
  ]
}
```
</details>

**Comment by KKoukiou** [comment]
This is not a flake, it never fails. The tests failing are from test runs of unmerged PRs.
