### ISSUE TITLE
testState (check_machines_virsh.TestMachinesVirsh) is flaky

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#10734]
90% on verify/fedora-i386
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161616-418abe4b-verify-fedora-i386/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161616-418abe4b-verify-fedora-i386/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161616-418abe4b-verify-fedora-i386/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123131-12fdc93a-verify-fedora-i386/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123131-12fdc93a-verify-fedora-i386/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123131-12fdc93a-verify-fedora-i386/log)

93% on verify/fedora-28
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161717-418abe4b-verify-fedora-28/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161717-418abe4b-verify-fedora-28/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161717-418abe4b-verify-fedora-28/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122525-12fdc93a-verify-fedora-28/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122525-12fdc93a-verify-fedora-28/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122525-12fdc93a-verify-fedora-28/log)

<details><summary>Source material</summary>

```json
{
  "test": [
    [
      "testState (check_machines_virsh.TestMachinesVirsh)",
      11
    ]
  ],
  "status": [
    [
      "failure",
      11
    ]
  ],
  "tracker": [
    [
      null,
      11
    ]
  ],
  "context": [
    [
      "verify/fedora-i386",
      11
    ]
  ],
  "merged": [
    [
      true,
      10
    ],
    [
      false,
      1
    ]
  ],
  "date": [
    "2018-08-30T16:22:44Z",
    "2018-10-18T13:04:10Z"
  ]
}
{
  "test": [
    [
      "testState (check_machines_virsh.TestMachinesVirsh)",
      16
    ]
  ],
  "status": [
    [
      "failure",
      16
    ]
  ],
  "tracker": [
    [
      null,
      16
    ]
  ],
  "context": [
    [
      "verify/fedora-28",
      16
    ]
  ],
  "merged": [
    [
      true,
      15
    ],
    [
      false,
      1
    ]
  ],
  "date": [
    "2018-08-30T16:44:41Z",
    "2018-10-18T13:08:34Z"
  ]
}
```
</details>

**Comment by martinpitt** [comment]
I'm looking at PR #10335. On fedorapeople we still have the logs from November 5 to 21 ([example](https://fedorapeople.org/groups/cockpit/logs/pull-10335-20181105-100707-11aa138c-verify-fedora-28/)), but no more logs from October 18.

**Comment by KKoukiou** [comment]
See comment above, this test is not flaky.
