### ISSUE TITLE
testInlineConsole (check_machines_virsh.TestMachinesVirsh) is flaky

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#10733]
92% on verify/fedora-i386
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161616-418abe4b-verify-fedora-i386/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123131-12fdc93a-verify-fedora-i386/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123131-12fdc93a-verify-fedora-i386/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123131-12fdc93a-verify-fedora-i386/log)

93% on verify/fedora-28
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161717-418abe4b-verify-fedora-28/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161717-418abe4b-verify-fedora-28/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161717-418abe4b-verify-fedora-28/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122525-12fdc93a-verify-fedora-28/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122525-12fdc93a-verify-fedora-28/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122525-12fdc93a-verify-fedora-28/log)

<details><summary>Source material</summary>

```json
{
  "test": [
    [
      "testInlineConsole (check_machines_virsh.TestMachinesVirsh)",
      13
    ]
  ],
  "status": [
    [
      "failure",
      13
    ]
  ],
  "tracker": [
    [
      null,
      13
    ]
  ],
  "context": [
    [
      "verify/fedora-i386",
      13
    ]
  ],
  "merged": [
    [
      true,
      12
    ],
    [
      false,
      1
    ]
  ],
  "date": [
    "2018-08-30T16:22:44Z",
    "2018-10-18T13:04:10Z"
  ]
}
{
  "test": [
    [
      "testInlineConsole (check_machines_virsh.TestMachinesVirsh)",
      16
    ]
  ],
  "status": [
    [
      "failure",
      16
    ]
  ],
  "tracker": [
    [
      null,
      16
    ]
  ],
  "context": [
    [
      "verify/fedora-28",
      16
    ]
  ],
  "merged": [
    [
      true,
      15
    ],
    [
      false,
      1
    ]
  ],
  "date": [
    "2018-08-30T16:44:41Z",
    "2018-10-18T13:08:34Z"
  ]
}
```
</details>

**Comment by KKoukiou** [comment]
These old issues for flakes are not helpful since the links are not accessible anymore.
