### ISSUE TITLE
storage: tooltips are empty

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#10750]
Storage page's tooltips are empty.

How to reproduce: Hover over a **+** or edit button.

![screenshot showing empty tooltip in storage page](https://user-images.githubusercontent.com/10246/49431106-ff08c300-f7ac-11e8-8b8d-523a7fdca56a.png)

Downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1655922

**Comment by martinpitt** [comment]
PR #10752 fixes the above, but there are more empty labels here:

![label](https://user-images.githubusercontent.com/200109/49452934-6db44380-f7e2-11e8-8c10-343c1731bfbd.png)

**Comment by martinpitt** [comment]
The updated  PR now fixes all of them in a general fashion. \o/
