### ISSUE TITLE
Fedora 29 cannot parse cockpit.spec

### ISSUE THREAD

**Issue by hjmallon** [cockpit-project/cockpit#10755]
I am trying to build cockpit on Fedora 29. I was hitting some issues with dnf build dep. It was not able to parse the spec file.

Testing it with
`python3 -c 'import rpm; s = rpm.spec("tools/cockpit.spec")'`

1. npm-version rpm macro not found. Is it meant to be `nodejs_version`? If so build instructions need to include `nodejs-packaging` and it needs to be changed in spec.

**Comment by martinpitt** [comment]
Right, don't use tools/cockpit.spec from git, use the one from the release tarballs. The one in git needs to be pre-processed. Or run `tools/gen-spec-dependencies tools/cockpit.spec` if you really must run it from git.

**Comment by hjmallon** [comment]
Cool. That just means that the line `sudo yum-builddep tools/cockpit.spec` in https://github.com/cockpit-project/cockpit/blob/master/HACKING.md doesn't work when using dnf tools, i.e. `dnf-tools` util `dnf builddep`.

**Comment by martinpitt** [comment]
Indeed, thanks. Reopening to adjust the docs.

**Comment by martinpitt** [comment]
Fix sent in PR #10774
