### ISSUE TITLE
Image refresh for selenium

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#10785]
Image refresh for selenium
 * [ ] FAIL: image-refresh selenium

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-1jrrv.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10785-20181208-013939/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10785-20181208-013939/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-k6ps3.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10785-20181211-134141/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10785-20181211-134141/

**Comment by martinpitt** [comment]
```
+ dnf -y remove firewalld
Error: 
 Problem: The operation would result in removing the following protected packages: kernel-core
image-create: setup failed with code 1
```
Let's disable firewalld through systemctl instead.
