### ISSUE TITLE
testLibvirt (check_machines_virsh.TestMachinesVirsh) is flaky

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#10794]
78% on verify/debian-stable
 - [pull-10512](http://fedorapeople.org/groups/cockpit/logs/pull-10512-20181106-133939-a755d3a5-verify-debian-stable/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122424-12fdc93a-verify-debian-stable/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122424-12fdc93a-verify-debian-stable/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122424-12fdc93a-verify-debian-stable/log)

82% on verify/fedora-i386
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161616-418abe4b-verify-fedora-i386/log)
 - [pull-10537](http://fedorapeople.org/groups/cockpit/logs/pull-10537-20181108-162323-5feb13ce-verify-fedora-i386/log)
 - [pull-10413](http://fedorapeople.org/groups/cockpit/logs/pull-10413-20181023-160202-d1cac879-verify-fedora-i386/log)
 - [pull-10404](http://fedorapeople.org/groups/cockpit/logs/pull-10404-20181023-110505-eb687b40-verify-fedora-i386/log)
 - [pull-10340](http://fedorapeople.org/groups/cockpit/logs/pull-10340-20181019-094545-a295980d-verify-fedora-i386/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181108-124848-e2a1570e-verify-fedora-i386/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123131-12fdc93a-verify-fedora-i386/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123131-12fdc93a-verify-fedora-i386/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123131-12fdc93a-verify-fedora-i386/log)
 - [pull-10101](http://fedorapeople.org/groups/cockpit/logs/pull-10101-20181023-153939-1695b632-verify-fedora-i386/log)

94% on verify/fedora-28
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161717-418abe4b-verify-fedora-28/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161717-418abe4b-verify-fedora-28/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161717-418abe4b-verify-fedora-28/log)
 - [pull-10537](http://fedorapeople.org/groups/cockpit/logs/pull-10537-20181108-162525-5feb13ce-verify-fedora-28/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181111-095454-8844ddd8-verify-fedora-28/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181111-095454-8844ddd8-verify-fedora-28/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181109-134141-1ffba003-verify-fedora-28/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181108-124444-e2a1570e-verify-fedora-28/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181108-102929-872e130f-verify-fedora-28/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122525-12fdc93a-verify-fedora-28/log)

81% on verify/fedora-29
 - [pull-10441](http://fedorapeople.org/groups/cockpit/logs/pull-10441-20181026-064747-cecd597d-verify-fedora-29/log)
 - [pull-10437](http://fedorapeople.org/groups/cockpit/logs/pull-10437-20181026-050707-241c2a75-verify-fedora-29/log)
 - [pull-10340](http://fedorapeople.org/groups/cockpit/logs/pull-10340-20181019-083838-a295980d-verify-fedora-29/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181111-095353-8844ddd8-verify-fedora-29/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181108-125252-e2a1570e-verify-fedora-29/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181108-104343-872e130f-verify-fedora-29/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122424-12fdc93a-verify-fedora-29/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122424-12fdc93a-verify-fedora-29/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122424-12fdc93a-verify-fedora-29/log)
 - [pull-10116](http://fedorapeople.org/groups/cockpit/logs/pull-10116-20181022-192020-5f9af006-verify-fedora-29/log)

100% on verify/centos-7
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161818-418abe4b-verify-centos-7/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161818-418abe4b-verify-centos-7/log)
 - [pull-9949](http://fedorapeople.org/groups/cockpit/logs/pull-9949-20181017-161818-418abe4b-verify-centos-7/log)
 - [pull-10557](http://fedorapeople.org/groups/cockpit/logs/pull-10557-20181112-155151-aef1507b-verify-centos-7/log)
 - [pull-10484](http://fedorapeople.org/groups/cockpit/logs/pull-10484-20181104-134646-92cc0709-verify-centos-7/log)
 - [pull-10481](http://fedorapeople.org/groups/cockpit/logs/pull-10481-20181031-021717-4cb3f2de-verify-centos-7/log)
 - [pull-10442](http://fedorapeople.org/groups/cockpit/logs/pull-10442-20181026-072626-96d7ed20-verify-centos-7/log)
 - [pull-10427](http://fedorapeople.org/groups/cockpit/logs/pull-10427-20181122-145959-82ebd83b-verify-centos-7/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181111-100000-8844ddd8-verify-centos-7/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-122727-12fdc93a-verify-centos-7/log)

92% on verify/rhel-x
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181111-095757-8844ddd8-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181111-095757-8844ddd8-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181111-095757-8844ddd8-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181108-124747-e2a1570e-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181108-093333-872e130f-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123434-12fdc93a-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123434-12fdc93a-verify-rhel-x/log)
 - [pull-10335](http://fedorapeople.org/groups/cockpit/logs/pull-10335-20181018-123434-12fdc93a-verify-rhel-x/log)

<details><summary>Source material</summary>

```json
{
  "test": [
    [
      "testLibvirt (check_machines_virsh.TestMachinesVirsh)",
      14
    ]
  ],
  "status": [
    [
      "failure",
      14
    ]
  ],
  "tracker": [
    [
      null,
      14
    ]
  ],
  "context": [
    [
      "verify/debian-stable",
      14
    ]
  ],
  "merged": [
    [
      true,
      11
    ],
    [
      false,
      3
    ]
  ],
  "date": [
    "2018-08-08T15:09:42Z",
    "2018-11-06T14:31:24Z"
  ]
}
{
  "test": [
    [
      "testLibvirt (check_machines_virsh.TestMachinesVirsh)",
      23
    ]
  ],
  "status": [
    [
      "failure",
      23
    ]
  ],
  "tracker": [
    [
      null,
      23
    ]
  ],
  "context": [
    [
      "verify/fedora-i386",
      23
    ]
  ],
  "merged": [
    [
      true,
      19
    ],
    [
      false,
      4
    ]
  ],
  "date": [
    "2018-08-30T16:22:44Z",
    "2018-11-08T16:54:16Z"
  ]
}
{
  "test": [
    [
      "testLibvirt (check_machines_virsh.TestMachinesVirsh)",
      19
    ]
  ],
  "status": [
    [
      "failure",
      19
    ]
  ],
  "tracker": [
    [
      null,
      19
    ]
  ],
  "context": [
    [
      "verify/fedora-28",
      19
    ]
  ],
  "merged": [
    [
      true,
      18
    ],
    [
      false,
      1
    ]
  ],
  "date": [
    "2018-08-30T16:44:41Z",
    "2018-11-11T10:36:20Z"
  ]
}
{
  "test": [
    [
      "testLibvirt (check_machines_virsh.TestMachinesVirsh)",
      16
    ]
  ],
  "status": [
    [
      "failure",
      16
    ]
  ],
  "tracker": [
    [
      null,
      16
    ]
  ],
  "context": [
    [
      "verify/fedora-29",
      16
    ]
  ],
  "merged": [
    [
      true,
      13
    ],
    [
      false,
      3
    ]
  ],
  "date": [
    "2018-09-24T09:23:25Z",
    "2018-11-11T10:31:12Z"
  ]
}
{
  "test": [
    [
      "testLibvirt (check_machines_virsh.TestMachinesVirsh)",
      11
    ]
  ],
  "status": [
    [
      "failure",
      11
    ]
  ],
  "tracker": [
    [
      null,
      11
    ]
  ],
  "context": [
    [
      "verify/centos-7",
      11
    ]
  ],
  "merged": [
    [
      true,
      11
    ]
  ],
  "date": [
    "2018-10-04T11:41:35Z",
    "2018-11-22T16:24:58Z"
  ]
}
{
  "test": [
    [
      "testLibvirt (check_machines_virsh.TestMachinesVirsh)",
      13
    ]
  ],
  "status": [
    [
      "failure",
      13
    ]
  ],
  "tracker": [
    [
      null,
      13
    ]
  ],
  "context": [
    [
      "verify/rhel-x",
      13
    ]
  ],
  "merged": [
    [
      true,
      12
    ],
    [
      false,
      1
    ]
  ],
  "date": [
    "2018-10-09T06:54:44Z",
    "2018-11-11T10:23:26Z"
  ]
}
```
</details>

**Comment by KKoukiou** [comment]
This started to be flaky again but the links here are completely outdated and probably it fails on different part.
