### ISSUE TITLE
cockpit-desktop: Support simple arguments

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#10809]
Support calling it with just a manifest name, like `cockpit-desktop subscriptions`, instead of the path. Need to figure out whether we can rely on `/index.html`, or need to grab this from somewhere (like the manifest).

**Comment by allisonkarlitskaya** [comment]
playground/ is an interesting example because it doesn't have an index.  I imagine we should be able to specify things like system/terminal or playground/react-patterns.

shell/base_index.js has some nice logic:

            frame.url = base + "/" + component;
            if (component.indexOf("/") === -1)
                frame.url += "/index";
            frame.url += ".html";

I feel like we could potentially duplicate this in cockpit-desktop.
