### ISSUE TITLE
Inconsistent display name on navigation bar

### ISSUE THREAD

**Issue by pesca** [cockpit-project/cockpit#10839]
~~When first connecting to a host, the real host name is used as the display name on the navigation bar.~~ Logging in on a local install uses "localhost" as the display name on the navigation bar. Switching between servers changes the display name to the host name. I expect the host name is always used, never "localhost".

**Related/Duplicate? issue:** #9909

**Comment by martinpitt** [comment]
If that was about the transient host name, that's #9909 indeed. It does seem to work fine with static and pretty host names at least with version 206 (but this hasn't changed in a long time). So I close this as a duplicate.
