### ISSUE TITLE
docker-init command fails with error checking for libzip... not found

### ISSUE THREAD

**Issue by Hughp135** [cockpit-project/cockpit#10840]
I'm getting this error from docker-init on windows 10 with node 10.11.0 and docker 2.0.0

```
checking for libzip... not found
configure: error: Please reinstall the libzip distribution
```

This was fixed by adding this line to the Dockerfile:
`  libzip-dev \`

Workaround Dockerfile command:
```
RUN apt-get update \
    && apt-get install -y \
    wget zip unzip \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    sqlite3 libsqlite3-dev \
    libssl-dev \
    libzip-dev \
    && pecl install mongodb \
    && pecl install redis \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) iconv gd pdo zip opcache pdo_sqlite \
    && a2enmod rewrite expires
```

**Comment by martinpitt** [comment]
This has nothing to do with Cockpit.

**Comment by Hughp135** [comment]
Would you do me the favour of elaborating by any chance? @martinpitt

**Comment by martinpitt** [comment]
@Hughp135 : I'm afraid I can't. *Nothing* in the description of the issue is related in any way with cockpit. Whatever docker container you are trying to build, please report it there.

**Comment by Hughp135** [comment]
Whoops, in a rush I got the wrong cockpit repository. Sorry! 😂
