### ISSUE TITLE
SSH Password-Authentication used even if public-key is available and preferred

### ISSUE THREAD

**Issue by vertuxt** [cockpit-project/cockpit#10868]
Reproduction Scenario:
- Same Username but different passwords
- Working SSH Public-Key Setup
- SSH Config to prefer Key-Login (ssh user@hostname uses pubkey)

On Hosts to be added:
- Even when selected "available authentication methods"  local-password is the only Authentication tried

On existing Hosts:
- Password is used for every authentication: "Accepted password for $user from $HOST port $$$$ ssh2

On Hosts with the same username but different password, authentication is impossible.

Software-Versions Web-UI:
Debian Buster 
Cockpit: 184 
Openssh: 1:7.9p1-4

Software-Versions Remote Hosts (bridge only):
Debian Buster + Stretch
Cockpit 184 + 180 

With Cockpit 180 and Debian Stretch on the Web-UI host everything worked fine.
I've already tried to remove the configurations and add all hosts again, but in any case, the password is being used / login is impossible for machines with an different password.

**Comment by martinpitt** [comment]
Just to make sure: Did you actually enable/unlock your SSH key in the user menu → "Authentication" dialog?

**Comment by vertuxt** [comment]
Yes, they're enabled. Also the keys are normally preferred by ssh. 
I've made several tests, and in any case the password is preferred, which fails for some remote machines. 
Machines with the same user but different PW fail as well.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
