### ISSUE TITLE
rhel-8-0: `which python` sometimes fails

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#10889]
On rhel-8-0, the `test/verify/check-apps TestApps.testL10N` test often [fails like this](https://fedorapeople.org/groups/cockpit/logs/pull-10874-20181225-094545-1fe1da6b-verify-rhel-8-0/log.html#214):
```
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 737, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 916, in check_journal_messages
    raise Error(first)
testlib.Error: which: no python in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

This is from [pkg/lib/python.js](https://github.com/cockpit-project/cockpit/blob/master/pkg/lib/python.js), which does

    exec $(which /usr/libexec/platform-python 2>/dev/null || which python3 2>/dev/null || which python)

I just can't figure out why this would sometimes fail. I added a `set -x` and printing of `$PATH`, and it looks all normal, and in some cases it just fails:

```
++ echo XXXX /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
XXXX /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ which /usr/libexec/platform-python
+ exec /usr/libexec/platform-python -
++ echo XXXX /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
XXXX /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ which /usr/libexec/platform-python
++ which python3
++ which python
which: no python in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

This makes absolutely no sense to me, I don't see why `which /usr/libexec/platform-python` would sometimes fail without an error message, and `which python3` the same. (Note that `python` is indeed not installed on the rhel-8-0 image).

Creating this issue to collect more ideas and debugging information, and for referring to it from failed test runs.

**Comment by mvollmer** [comment]
Only the `which python` part of the `||` construct doesn't redirect stderr to /dev/null, maybe that explains a bit of what's going on.

**Comment by martinpitt** [comment]
@mvollmer: The intention was that on e. g. RHEL 7 you won't always get an error message about non-existing platform-python/python3. It would just be confusing noise there. But in the above `set -x` copy&paste's, I removed stderr redirection everywhere.

**Comment by mvollmer** [comment]
This is the culprit, found by stracing `which /usr/libexec/platform-python`:
```
write(1, "/usr/libexec/platform-python\n", 29) = -1 EPIPE (Broken pipe)
```

That is, `which` succeeds as expected, but can't write the result and then the `||` expression moves on  until the last `which` prints its message.

Why the first `which` gets the SIGPIPE I can't say exactly, but it is connected with the quick reloads that `check-apps` does.  Maybe `cockpit-bridge` tears down spawned processes too brutally when a session is closed?

**Comment by martinpitt** [comment]
Thanks @mvollmer for digging this out! Reloads triggered from the tests would do it, I suppose that will invoke cleanup handlers in the bridge due to the channels from JS going away.

So now that we have an explanation, I'd actually be okay with a mere `allow_journal_message()`.
