### ISSUE TITLE
rpm based release 

### ISSUE THREAD

**Issue by sjkeerthi** [cockpit-project/cockpit#10904]
Hi All,

Today I tried to install Cockpit in centos 7.x which bring version cockpit-176-4.el7 which does not work well while adding multiserver setup.

When I try the same on Fedora it installed the latest version 182 where in this I could able to add machine with any issue in UI itself.

Requirement is:
It will be great that if you could add the rpm base release on CentOS during the Release will really help.

**Comment by martinpitt** [comment]
Right, the ordinary flow is that CentOS 7.x rebuilds what's in RHEL 7.x. I. e. there is no direct upload from upstream to CentOS.

For newer versions you are of course welcome to use the [COPR repo](https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/), which gets updated automatically with each upstream release. But we don't plan to directly upload to  CentOS (if that's even possible), as we don't have the maintainership bandwith for that. That said, if someone else wants to do that, go ahead of course :smile:
