### ISSUE TITLE
PackageKit often dumps core on current rhel-8

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#10908]
PackageKit often dumps core when installing/removing packages.

Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1663192

**Comment by KKoukiou** [comment]
verify/rhel-8-0
Ooops, it happened again<hr>
```
# testBasic (check_apps.TestApps)
*
* warning: PackageKit went away during transaction *
```
First occurrence: 2019-01-03T13:53:03.678365
Times recorded: 1
Latest occurrences:

- 2019-01-03T13:53:03.678365

**Comment by martinpitt** [comment]
Bump, let's keep this for another round and check if it's really fixed. Then we can close the downstream bug.
