### ISSUE TITLE
Network: sending and receiving uses different scales

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1090]
I'm currently doing a backup from my laptop to my server, obviously getting big numbers for Receiving traffic on the server. When I glanced at the graphs I was surprised that Sending had so much data as well, until I realized they weren't working on the same scale.
![screenshot from 2014-08-27 16 36 08](https://cloud.githubusercontent.com/assets/209895/4061442/28dc270e-2df8-11e4-9be9-a86c662633e8.png)

**Comment by martinpitt** [comment]
This is bikeshedding of course, until we invoke some actual psychology studies. Forcing both on the same scale would usually mean that one of them has a very tiny graph which isn't very useful then. 

Perhaps it woud already help to make the unit display more prominent? In your picture there is even an additional  hint as the grid lines don't match up, but apparently that wasn't enough in your case?

**Comment by andreasn** [comment]
If this comes up in any usability tests, in customer feedback or similar I think we can reopen this, but it's not critical enough to keep open I think.
