### ISSUE TITLE
ip settings: automatically suggest a gateway based on IP

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1091]
Correct me if I'm wrong, but in most situations, this is true:
If I set my static IP address to 192.168.11.5, the gateway is most likely 192.168.11.1
Filling this automatically would be a nice touch (with the ability to change the gateway of course)

**Comment by mvollmer** [comment]
Good idea.  I want this every time I use the dialog.

**Comment by gil-obradors** [comment]
I'm in!

https://github.com/cockpit-project/cockpit/blob/69a93dc68fae67e5f9b8e31693d1244f8a6d08e5/pkg/networkmanager/ip-settings.jsx#L67

Need to write a function that encapsulates setAddresses by
- Every time that address field is changed
  - Set netmask according address class
  - Set gateway with the same address ending with 1

**Comment by gil-obradors** [comment]
Could be something like this?

![Peek 2022-06-10 22-30](https://user-images.githubusercontent.com/6016929/173147264-3186961e-198e-4576-9ff5-2c4e09ec5809.gif)


https://github.com/cockpit-project/cockpit/compare/main...gil-obradors:ip-helper

**Comment by jelly** [comment]
Without taking a too detailed look this looks great! You should be able to insert an address and then later be able to change the prefix/gateway to something you prefer.

**Comment by gil-obradors** [comment]
...And tests: https://github.com/gil-obradors/cockpit/blob/3cc547b071267ff1e38beadb670cac45012ada3a/test/verify/check-networkmanager-ip-helper
