### ISSUE TITLE
Error when deleting mounted RAID devices

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#1092]
When I tried to delete a mounted RAID device, I got this:
![screenshot from 2014-08-28 10 45 59](https://cloud.githubusercontent.com/assets/3952545/4077362/61c51484-2ec2-11e4-9c5f-450865033880.png)
Do we need a warning when clicking Delete button or just hide or disable Delete button?
@mvollmer @andreasn

**Comment by mvollmer** [comment]
There is a warning now.
