### ISSUE TITLE
How to binding custom domain in caddy?

### ISSUE THREAD

**Issue by ourfor** [cockpit-project/cockpit#10920]
Hello Sir, I am the newbee of cockpit. My VPS install cockpit by default. In my opinion, this software is very good. But I can only visit  the dashboard by ipv4 address and the port 9090. I want to binding my custom domain--` control.ourfor.top `. I want to use this url ` https://control.ourfor.top ` to visit web dashboard. And I use ***Caddy*** as the http server software. I don't know how to edit this config to enable it. 

- My domain is control.ourfor.top
- I want to use ` https://control.ourfor.top ` to replace ` ipv4:9090 `
- I have set dns

**Comment by martinpitt** [comment]
You can tell [cockpit.conf](https://cockpit-project.org/guide/latest/cockpit.conf.5.html) that it runs behind a reverse proxy with setting `Origins` and `ProtocolHeader`. The wiki has a [recipe for nginx](https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX). We don't have experience with caddy, but its proxy mode looks [well documented](https://caddyserver.com/v1/docs/proxy) and easy to use.
