### ISSUE TITLE
RestError when show docker page

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#1093]
When the docker page without any docker installed shows up, I got this
![screenshot from 2014-08-28 11_55_13](https://cloud.githubusercontent.com/assets/3952545/4092413/633b70ee-2f92-11e4-86f4-55bb794d97e5.png)

**Comment by stefwalter** [comment]
I think we want to log the error.

**Comment by dperpeet** [comment]
Agreed. I believe this will be cleaned up anyway once docker moves into its own package.
