### ISSUE TITLE
RFE: Firewall integration

### ISSUE THREAD

**Issue by danofsatx** [cockpit-project/cockpit#1094]
Great work so far, folks! I logged into my F21TC3 server and was impressed by the progress y'all have made since cockpit-0.19-1. 

However, the one thing I've been waiting on still hasn't made it to cockpit - the firewall configurator/controller. It looks like you have the systemd stuff complete, and even the networking, but there is no reference to firewall settings at all, other than the opportunity to turn it off or on through the systemd services tab.

In fact, I'm looking forward to cockpit being a drop-in replacement for webmin, which means it would _awesome_ if it ever supported the configuration of servers on top of the OS (such as Apache, MariaDB, Postfix, Dovecot, and so on), but that is likely outside the scope of this project.

**Comment by nekohayo** [comment]
Some ponies on rainbows:
* Opening/closing ports, and specifying an external/internal port (ex: 8080 mapping to 80 on the machine)
 * Optionally being able to specify a source IP (or part of an IP with wildcards and whatnot) for which the rule applies?
* Same, for port "ranges"
* Port knocking (aka hadouken punch combo) and/or port triggering?
* For troubleshooting: maybe a live log that shows what access attempts are being made on which ports and are getting blocked? That would remove the temptation of most firewall GUIs to have "presets" off "typical" applications; at the end of the day we mostly just care about ports in most cases?

**Comment by stefwalter** [comment]
Trello card: https://trello.com/c/DVQIn8AC/65-firewall-support

**Comment by voxadam** [comment]
Would this be a frontend to [FirewallD](https://fedoraproject.org/wiki/FirewallD) or would it be an interface to directly manipulate iptables chains and rules?

**Comment by andreasn** [comment]
I believe firewalld has a dbus interface Cockpit can talk to, so that's probably the easier route.
