### ISSUE TITLE
Try out new machine learning with image rendering

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#10950]
This is a test of https://github.com/cockpit-project/cockpituous/pull/228

 * [x] learn-tests http://cockpit-learn.cockpit.svc.cluster.local/train/tests-train-1.jsonl.gz
 * [x] tests-data tests-train-1.jsonl.gz
 * [ ] flakes-refresh

**Comment by cockpituous** [comment]
learn-tests in progress on centosci-tasks-4w0t3.
Log: http://fedorapeople.org/groups/cockpit/logs/learn-tests-10950-20190111-111313/

**Comment by cockpituous** [comment]
tests-data in progress on centosci-tasks-4m8kt.
Log: http://fedorapeople.org/groups/cockpit/logs/tests-data-10950-20190111-150909/

**Comment by cockpituous** [comment]
flakes-refresh in progress on bos-tasks-0kvvl.
Log: http://fedorapeople.org/groups/cockpit/logs/flakes-refresh-10950-20190111-154141/

**Comment by cockpituous** [comment]
learn-tests in progress on centosci-tasks-2drqm.
Log: http://fedorapeople.org/groups/cockpit/logs/learn-tests-10950-20190111-200101/

**Comment by cockpituous** [comment]
tests-data in progress on centosci-tasks-c4cx9.
Log: http://fedorapeople.org/groups/cockpit/logs/tests-data-10950-20190111-200606/

**Comment by cockpituous** [comment]
flakes-refresh in progress on centosci-tasks-4kndd.
Log: http://fedorapeople.org/groups/cockpit/logs/flakes-refresh-10950-20190111-203838/

**Comment by cockpituous** [comment]
flakes-refresh in progress on centosci-tasks-xgql5.
Log: http://fedorapeople.org/groups/cockpit/logs/flakes-refresh-10950-20190111-203939/

**Comment by cockpituous** [comment]
flakes-refresh in progress on centosci-tasks-c4cx9.
Log: http://fedorapeople.org/groups/cockpit/logs/flakes-refresh-10950-20190111-204141/

**Comment by cockpituous** [comment]
flakes-refresh in progress on centosci-tasks-4m8kt.
Log: http://fedorapeople.org/groups/cockpit/logs/flakes-refresh-10950-20190111-204242/

**Comment by cockpituous** [comment]
flakes-refresh in progress on centosci-tasks-twvml.
Log: http://fedorapeople.org/groups/cockpit/logs/flakes-refresh-10950-20190111-204747/

**Comment by cockpituous** [comment]
flakes-refresh in progress on centosci-tasks-xgql5.
Log: http://fedorapeople.org/groups/cockpit/logs/flakes-refresh-10950-20190111-205050/

**Comment by cockpituous** [comment]
flakes-refresh in progress on centosci-tasks-xgql5.
Log: http://fedorapeople.org/groups/cockpit/logs/flakes-refresh-10950-20190111-205858/
