### ISSUE TITLE
Cockpit install on Ubuntu server 18.04 kernal 4.20

### ISSUE THREAD

**Issue by ratnose** [cockpit-project/cockpit#10958]
I have a few servers and I want to run Cockpit to monitor them.
On the servers with Kernal 4.15 there is no problem, one of them has Kernal 4.20 and there I am unable to find Cockpit via apt.

**Comment by martinpitt** [comment]
This is unrelated to the kernel version. Ubuntu 18.04 has cockpit 164 in the release, and a newer version 183 in backports, see https://launchpad.net/ubuntu/+source/cockpit . Possibly you have the "universe" repository disabled on that machine?

**Comment by damianog** [comment]
as @ratnose I have a similar issue, I cannot upgrade from 164-1 to latest (197 today), here my logs:

**cat /etc/lsb-release**

_DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"_

**sudo add-apt-repository universe**

'universe' distribution component is already enabled for all sources.

**sudo apt search cockpit**

Sorting... Done
Full Text Search... Done
cockpit/bionic,now 164-1 all [installed]
  User interface for Linux servers

cockpit-bridge/bionic,now 164-1 amd64 [installed,automatic]
  Cockpit bridge server-side component

cockpit-dashboard/bionic,now 164-1 amd64 [installed,automatic]
  Cockpit remote servers and dashboard

cockpit-doc/bionic 164-1 all
  Cockpit deployment and developer guide

cockpit-docker/bionic 164-1 all
  Cockpit user interface for Docker containers

cockpit-machines/bionic 164-1 all
  Cockpit user interface for virtual machines

cockpit-networkmanager/bionic,now 164-1 all [installed,automatic]
  Cockpit user interface for networking

cockpit-packagekit/bionic 164-1 all
  Cockpit user interface for packages

cockpit-pcp/bionic-backports 196-1~ubuntu18.04.1 amd64
  Cockpit PCP integration

cockpit-storaged/bionic,now 164-1 all [installed,automatic]
  Cockpit user interface for storage

cockpit-system/bionic,now 164-1 all [installed,automatic]
  Cockpit admin interface for a system

cockpit-tests/bionic 164-1 amd64
  Tests for Cockpit

cockpit-ws/bionic,now 164-1 amd64 [installed,automatic]
  Cockpit Web Service

any suggestions?

**Comment by martinpitt** [comment]
@damianog : Right, this is also linked from https://cockpit-project.org/running.html#ubuntu

No response from @ratnose in half a year, so I close this now.
