### ISSUE TITLE
Cockpit 183-1 TLS handshake failure Chrome

### ISSUE THREAD

**Issue by Moltenkore** [cockpit-project/cockpit#10971]
Hi, I'm trying to use my own generated CA SSL certificates in Cockpit and I keep getting ``couldn't read from connection: Error performing TLS handshake: The request is invalid.`` in the unit log when I try and visit it from Chrome. With the error in Chrome itself being ``unexpectedly closed the connection.``

Cockpit is version ~~164-1~~ 183-1 on Ubuntu 18.04.1
Chrome is version 71.0.3578.98 (Official Build) (64-bit)

The certificates were generated with XCA with a root and intermediate CA specified in a file of the same format as said here: https://cockpit-project.org/guide/149/https.html Both CA certificates are 4096 bit with the server's certificate being 2048 bit. The root CA certificate is present in Chrome's CA list as I am using the same CA in Apache for my lan.

**Comment by marusak** [comment]
Sorry for the late reply.
Is this still issue? Does this happen also with different browser?

**Comment by martinpitt** [comment]
Not reproducible, no answer in over a year.
