### ISSUE TITLE
update PPA description: it's deprecated in favor of official backports

### ISSUE THREAD

**Issue by dkebler** [cockpit-project/cockpit#10990]
The ubuntu bionic repo is really stale for arm64 (164) and three behind on amd64

I see this ppa but looks like it's not maintained and xenial is the only build
https://launchpad.net/~cockpit-project/+archive/ubuntu/cockpit

Any reason the ppa can't get the latest release compiled for various platforms (at least amd64 and arm64)?    There automations for this to make it easier on the devs.  

Would like to evaluate something  current on arm64 but don't have time to set up the compile/cross environment.

**Comment by martinpitt** [comment]
It's deliberately not maintained any more, as cockpit has been in the official Ubuntu backports for a long time. Please see https://cockpit-project.org/running.html#ubuntu and https://help.ubuntu.com/community/UbuntuBackports#Enabling_Backports .

However, we should change the description to say that it's obsolete. It might be less friendly to just delete it, as then users would get a nasty apt error about "repository not found".

**Comment by larskarlitski** [comment]
As discussed with @pitti, I've deleted the PPA instead of changing the description, so that people using it will see an error when updating. Otherwise they might run an old version for a long time.

**Comment by martinpitt** [comment]
Considering this again, while `apt update` complains about a non-existing PPA, it does not completely break apt install/upgrade etc., so we just deleted that old PPA now.
