### ISSUE TITLE
Find a more stable device name for use in fstab and crypttab when UUID is not available.

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#11]
We should select one from the symlinks, but care must be taken to only use valid ones.

(For example, if two filesystems have the same label L, they will both have /dev/disk/by-label/L among their symlinks, but the actual symlink of course only points to one device node. This should be a known problem and a bit of Googling is probably in order.)

**Comment by mvollmer** [comment]
We now let storaged choose the fsname and device entries in configuration items.
