### ISSUE TITLE
Add systemd filters

### ISSUE THREAD

**Issue by stewbond** [cockpit-project/cockpit#11006]
Cockpit's systemd support is perfect for remote monitoring and control of embedded systems.  Operators can see if the primary embedded services or targets are running, and can chose to start/stop them.

However, for non-technical operators, there is too much information.  An operator may not understand **ssh.service**, **rsync.service**, or **irqbalance.service**, or may not know whether to panic when they see **checkfs.service** is `masked / inactive (dead)`. It can be useful to hide these (when configured).  This is especially true on an embedded device we are only interested in one or two services.  So it would be nice to remove clutter to simplify the interface and help non-technical users focus on what they need to know about the system.

The feature request is:

**Add a configuration allowing a user to define filters.**

If no filters are defined, then there is no effect on the current view.  If at least one filter is defined, a dropdown allows a user to select between any of the filters or 'all'.  Selecting the filter limits the list of targets/services/sockets/timers/paths and logs from those units to those matching the pattern(s) of the filter.

In addition, add a configuration option to select the default filter.  This may be 'all' or one of the filters. If unset, it will default to `all`.

**Comment by KKoukiou** [comment]
@stewbond thanks for your interest in the project! I think adding filter in the services page might be ineed helpful.

We currently have this open issue for making services page easier to navigate. https://github.com/cockpit-project/cockpit/issues/10010
Can you please take a look and if that issue covers your requirement we can close this one so as to track this RFE at one place.

**Comment by stewbond** [comment]
Yes, this issue does cover my request.  Sorry I didn't see it before.
