### ISSUE TITLE
Dynamic UrlRoot support ?

### ISSUE THREAD

**Issue by fthiery** [cockpit-project/cockpit#11004]
Hello,

We have a bit of a special use case: consider 2 machines:
1) one is a backend server, that does server some cockpit frames over e.g. https://backend/sys-ui/cockpit/@localhost/network/index.html (this works as expected thanks to the cockpit.conf below)
2) one is an nginx frontend, with a proxy URL like https://frontend/proxy/1234/sys-ui/cockpit/@localhost/network/index.html which proxies to https://backend/ ; this url has to be dynamic (as we are using this to proxy to multiple backend machines)

As it is now, 1) works but not 2)

The problem is that the js-based URL building omits the /proxy/1234 part when opening https://frontend/proxy/sys-ui/cockpit/@localhost/network/index.html : the browser tries to open the following urls (which 404)
* https://frontend/sys-ui/cockpit/static/branding.css
* https://frontend/sys-ui/cockpit/login

```
# cat /etc/cockpit/cockpit.conf
[WebService]
UrlRoot=/sys-ui/
```

What would it take to have this work ? E.g. handling a special argument added by the frontend proxy that would allow the cockpit server to know the base url to use ?

**Comment by fthiery** [comment]
Hi

Could the UrlRoot not be determined by the current window/iframe url ?

**Comment by fthiery** [comment]
> Could the UrlRoot not be determined by the current window/iframe url ?

I meant, is there a good reason why it would not be possible ?

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
