### ISSUE TITLE
CoreOS support

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11002]
When reading the Fedora forum for Silverblue related info today, I came across this post:
"[Will CoreOS also feature Cockpit integration?](https://discussion.fedoraproject.org/t/will-coreos-also-feature-cockpit-integration/982/3)"

It's a good question. The author links to [the Atomic section on our Running page](https://cockpit-project.org/running.html#atomic) as something that might be similar, especially as Atomic is being replace with Silverblue on workstations and CoreOS on servers.

Of course, then there's the question about Fedora CoreOS vs. Red Hat CoreOS. But I imagine the support for both would be similar.

**Comment by garrett** [comment]
> What does this mean exactly?

That's why this issue exists, to figure out what it means.

> Cockpit already has support for OSTree updates. Do you mean that we need to add documentation on the website, or something else?

Documentation on the website is one thing. We also should have an official way of supporting CoreOS. Is support going to be baked in and/or will it be via a container like Atomic?

This needs to be solved at the Cockpit level, then communicated in the docs and on the website.

**Comment by mrguitar** [comment]
I just saw this and can probably help. One of the big changes we're making with RHEL/Fedora CoreOS is moving to a push model for updates, where Atomic was more of a pull. For RHCOS we're managing the nodes via kubernetes operators and really don't want admins accessing the systems via an SSH or cockpit session. 
The scope is a little different for Fedora CoreOS where we expect users to access and be more hands on with the OS. We still want to stick with the same update rollout feel as Container Linux so we'll be using a tool called Cincinnati to help with that side. I think cockpit could be a fit here w/ the cockpit-ws container, but I'm not completely sure how the updates would interact w/ the rpm-ostree plugin. We should broaden the discussion. 
The *real* reason I stumbled across this is I was looking to get this working with Silverblue, which I think absolutely makes sense. I can always package layer the bits here, but thought it might be worth asking if you guys had other thoughts around cockpit & silverblue.
Cheers,

**Comment by martinpitt** [comment]
As far as I can see, cockpit obviously makes sense on the upcoming Fedora CoreOS, which from a technical  PoV should be very close to Fedora Atomic. At least we want to continue to ship cockpit-system/bridge there plus a cockpit/ws container. However, I didn't find any alphas, betas, dailies, or any kind of download for that yet, so we can't yet start to develop and test on it.

I'm much less sure about Silverblue - that has an explicit desktop focus, and the desktop already comes with its own admin tools. We've made some steps with `cockpit-desktop(1)` to show a particular Cockpit page in a browser window without any extra authentication step, but so far this is only being used in RHEL for the subscriptions page. We may gradually extend this, but so far Cockpit isn't much of a desktop thing.

**Comment by garrett** [comment]
Using Cockpit on Silverblue does make a lot of sense. I can think of two somewhat common desktop-based cases off the top of my head that both apply to Silverblue:
1. **Admin bridge**: A bastion host on a laptop to access other machines over ssh (this not requiring exposed ports on the remote machines).
2. **Development**: Building Cockpit add-ons.

(Use 1 would be much more common, of course.)

**Comment by mrguitar** [comment]
The lastest FCOS artifacts are here: https://ci.centos.org/artifacts/fedora-coreos/prod/builds/latest/
Creating a custom build is actually pretty easy:https://github.com/coreos/coreos-assembler (even a PM can do it)

**Comment by cgwalters** [comment]
> Is support going to be baked in and/or will it be via a container like Atomic?

There's also package layering.

Bigger picture we aren't trying to carry forward much of the "system container" work from Atomic - the focus is on Kubernetes.  (Although non-Kubernetes container efforts include flatpak and toolbox, plus systemd portable services, and podman is also slowly growing integration with systemd)

**Comment by martinpitt** [comment]
@cgwalters: Thanks! Would you think it still makes sense to support/test a cockpit/ws container on FCOS, or should we rather look into a portable service or flatpak right away?

**Comment by cgwalters** [comment]
> Would you think it still makes sense to support/test a cockpit/ws container on FCOS, or should we rather look into a portable service or flatpak right away?

What I'd say is that at this time, we are not actively investigating shipping a single designated solution for this as part of the host by default.  (We also aren't shipping flatpak as part of FCOS by default as it's mostly desktop app focused)

**Comment by keithy** [comment]
"a single designated solution" would be better than no solution at all.

I like cockpit/ws, there is no other simple management interface for the more-standalone use-cases of Fedora Core OS. I think there are lots of use-cases for which FCOS is ideal for deployment of stand-alone servers too.

My use-case is for smaller installations where docker-compose marks the top level of complexity. So, I would like to be able to provision with docker-compose installed, a complse.yml file and the ability to monitor/control things via cockpit, and health check via goss. 

This would make for a pretty versatile solution in the standalone server space.

**Comment by keithy** [comment]
p.s. I am working towards a systemd Portable Services based deployment of cockpit.

**Comment by martinpitt** [comment]
I'm working on this now. Step 1 is to build a VM image for testing: https://github.com/cockpit-project/bots/pull/218

**Comment by martinpitt** [comment]
That landed, in https://github.com/cockpit-project/cockpit/issues/11002 I am now working on adjusting Cockpit's tests and the documentation for FCOS.
