### ISSUE TITLE
Using docker cant get Plex to work

### ISSUE THREAD

**Issue by Fyb3roptik** [cockpit-project/cockpit#11012]
I am using Debian 9. Fresh install. I have installed cockpit and docker.

I am using the official Plex docker image and cannot connect to plex via my browser. I am certain this is an iptables issue, but dont know if someone else has happened upon this issue.

Now my plex server is down :(

**Comment by Fyb3roptik** [comment]
Also note I did apt-get install cockpit cockpit-docker

I have seen somewhere that you guys say its deprecated and link to podman, but there is no install for podman, so I am not sure how to proceed

**Comment by Fyb3roptik** [comment]
No, it is an issue with networking. It was not forwarding the ports properly. I have stopped using Cockpit altogether because it simply does not work. Which sucks because I was really hoping to use it.

**Comment by Fyb3roptik** [comment]
I installed Debian 9. Installed cockpit and cockpit-docker. Installed the official plex container and then tried to go to http://ip_of_server:32400 and it did not work. If I install plex without docker, it works fine. So it appears cockpit is not forwarding the network connection to docker. So when I visit 32400 it does not send it to the plex container

**Comment by Fyb3roptik** [comment]
Please do not close an issue until I respond, because I AM doing that and IT IS NOT WORKING!

**Comment by KKoukiou** [comment]
@Fyb3roptik, sorry I closed the issue, I just am fairly sure that there is not an issue in cockpit-docker.

From a quick search this is what you need to run from command line for you plex container to work.
https://github.com/plexinc/pms-docker/blob/master/README.md#bridge-networking

First try it with docker-cli and it works?
Once this works for you then you can try to do the same with docker UI through cockpit.
If the cli works but UI does not then it's a cockpit-docker issue.
Please paste screenshots of your cockpit-docker page when trying to run the container, when replying here with errors.

**Comment by KKoukiou** [comment]
@Fyb3roptik when you run the container from cockpit UI, please go to terminal and execute,
$ ps aux | grep docker | grep port
root     13526  0.0  0.0 621656  3552 ?        Sl   12:15   0:00 /usr/libexec/docker/docker-proxy-current -proto tcp -host-ip 0.0.0.0 -host-port 9095 -container-ip 172.17.0.2 -container-port 9095


This is my container, where I mapped port 9095 from container to 9095 of host. You should she something similar for port 32400. This proves that port mapping is done correctly.

**Comment by KKoukiou** [comment]
@Fyb3roptik how you checked that it's not mapping the port? I am running cockpit-docker from master branch and port mapping is working.

As I mentioned above, in order to help you I need:
 - screenshot of the dialog before you run the container
 - the docker CLI command that works for you and you 're not able to make it work from cockpit UI
 - output of 'ps aux | grep docker' to see the docker runtime configuration that it's created from cockpit
- version of the cockpit-docker and docker packages

Please comment proving all of the above so that I can help you debug this.

**Comment by marusak** [comment]
@Fyb3roptik so getting back to this - is it still not working for you?
I am still not sure how cockpit fit into this problem. When you uninstall cockpit it works and when you install it back it does not work?
Or it works when you run the container from commandline but does not work when you use Cockpit UI to run it?

**Comment by marusak** [comment]
Closing, feel free to reopen - but please provide exact command you do on command line those work for you and don't work for you in Cockpit. (or any other way Cockpit breaks it for you).
