### ISSUE TITLE
There is a file manager?

### ISSUE THREAD

**Issue by CDNRocket** [cockpit-project/cockpit#11011]
Coockpit is really nice because it doesn't have too fancy things, is not based on LMAP or other prebuilds, can manage other machines, and above all because it can manage docker containers.

But I don't want to lose my visual file manager provided by webmin and other panels.

So I ask, there is a built-in file manager? will be there in the future?
If not, can y'all recommend a good file manager in support to Coockpit for RHEL?

**Comment by martinpitt** [comment]
There is no graphical file manager, and we don't plan to add one. If someone wanted to, they could create it as external Application. Links:

 - https://cockpit-project.org/blog/cockpit-starter-kit.html
 - https://cockpit-project.org/blog/making-a-cockpit-application.html
 - https://cockpit-project.org/external/wiki/Contributing.html

One thing that always works is the builtin Terminal, of course :smiley:

**Comment by martinpitt** [comment]
Check out https://github.com/45Drives/cockpit-navigator , it looks quite cool!

**Comment by CTI-Tim** [comment]
It is absolutely a dis-service to say "we dont want one"   cockpit-navigator should become one of the included by default packages as it really is well done and massively adds to the useability of the whole project.

**Comment by martinpitt** [comment]
@CTI-Tim : Yes, this appears on https://cockpit-project.org/applications.html, and the "Applications" page once packaged in distributions. I did not say "we don't want one", just "we don't plan to add one", and suggested an external application. And exactly that happened :grin:

**Comment by pavangayakwad** [comment]
Take a look at it: https://github.com/pavangayakwad/linux-drive-explorer, (https://explorer.srushtisoft.work). It has great UX and it is fast.

**Comment by tomasmatus** [comment]
Things have changed a bit in the last few years and we now have a file manager plugin, see https://github.com/cockpit-project/cockpit-files
