### ISSUE TITLE
Add role: Cockpit user

### ISSUE THREAD

**Issue by blade1989** [cockpit-project/cockpit#11020]
In the `/users#/bob` page, next to `Roles` , add a Cockpit user role option

This so that only a specified user has access to the Cockpit panel

**Comment by martinpitt** [comment]
There is no special "Cockpit user" privilege. You log in as normal Unix user, and can do exactly the same things as you can on the command line (like in ssh) or on a Desktop. Perhaps you mean administrative privileges? This already has a checkbox, and this maps to the `wheel` group on Fedora/RHEL and `admin` on Debian/Ubuntu.

**Comment by blade1989** [comment]
I know that there is no special "Cockpit user". But, I think it would be a welcomed edition to only have specific users that can login in the Cockit panel.

I don't know if it is really hard to build it in, but IMHO, I think this is a highly needed feature in Cockpit.

**Comment by martinpitt** [comment]
@blade1989 : One possible option would be to use `pam_succeed_if(8)` in /etc/pam.d/cockpit to restrict access. It does support a `user ingroup group` rule.
