### ISSUE TITLE
Security: root Login

### ISSUE THREAD

**Issue by tobias992** [cockpit-project/cockpit#11027]
Hello,
first sorry for my bad english... i am from germany.

I use Cockpit for my kvm webservers only for check the system usage.
In Changelog 183 i read "Respect SSH configuration". I have in sshd config "permitrootlogin no" but i can also login with root user. For security reason thats not nice because bad guys have 50 % from credentials.
Does the login screen have a brute force detection or i have to use fail2ban for this?

**Comment by KKoukiou** [comment]
Hi @tobias992,

your issue is a duplicate of https://github.com/cockpit-project/cockpit/issues/1790.
Check the answers there for a workaround until it's fixed please.

Regarding the Changelog in 183, it refers to ssh hosts, ex when you add different machines on the dashboard.

**Comment by KKoukiou** [comment]
Closing because is a duplicate.
