### ISSUE TITLE
Openshift/Kube-Config overflow websocket frames

### ISSUE THREAD

**Issue by bnwhorton** [cockpit-project/cockpit#11023]
I had a Openshift cluster with a very large CA-Chain. This caused the service account that cockpit-ui uses in Openshift to hand it a very large kube-config to the client. After this the client appears to use the kube-config in the websocket connections to access the ui. This large CA-Chain causes the websocket frame to overflow and crashes the connection.

**Comment by bnwhorton** [comment]
I can look at making a pull request for a fix (maybe look at the ui to splice the large frames?) If this is open to public to commit.

**Comment by martinpitt** [comment]
Of course it is, thanks! We don't currently have anyone working on the kubernetes UI, and [it's slated for removal](https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/thread/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/). So PRs greatly appreciated :)

**Comment by marusak** [comment]
@bnwhorton are you still interested to work on this?

**Comment by marusak** [comment]
Kubernetes UI is removed from master and lives only in stable branches. If this needs to be tracked a bugzilla needs to be opened.
