### ISSUE TITLE
containers: ports label gets mid align if more than one port mapped

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1103]
![screenshot from 2014-09-02 00 05 24](https://cloud.githubusercontent.com/assets/209895/4112320/2f4cdb4e-3224-11e4-9637-d3b03654e219.png)

**Comment by martinpitt** [comment]
This is fine now:

![docker-multi-ports](https://user-images.githubusercontent.com/200109/51108342-32019600-17f2-11e9-9790-abecb435368f.png)
