### ISSUE TITLE
Missing Menu items off navbar.

### ISSUE THREAD

**Issue by Tom-Development** [cockpit-project/cockpit#11055]
Cockpit version: 164.
OS: Ubuntu 18.04 LTS
Page: All

Missing menu items off navigation bar.

When I load the panel, certain menu items appear to be missing. It tells me there are updates available but I can't find the screen to update the system.

![image](https://user-images.githubusercontent.com/45858184/51777860-e787ef80-20f6-11e9-959b-02344b9b909d.png)

**Comment by martinpitt** [comment]
Presumably you don't have cockpit-packagekit installed?

**Comment by Tom-Development** [comment]
Thanks, working now.

How would I get the diagnostic reports option?

Is there a list in the docs which has all the relevant features with the packages they require?

**Comment by martinpitt** [comment]
I'm afraid the cockpit-sosreport package is not currently built in Debian. This is issue #3500.
