### ISSUE TITLE
Consider a collapsible sidebar in small screens and/or a toggle

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11059]
Initial mockups had a toggle. Should we implement one?

**Comment by marusak** [comment]
@garrett can you be please more verbose? I am not sure what this is about and also I don't know which ones are the `Initial mockups`.
Also you probably know very well - is this still issue?

**Comment by garrett** [comment]
I think this is no longer relevant?

I'm not sure, but I think it was referring to the top-level navigation, which:

1. I made it not expand/contract anyway
2. Is going away once we merge the navigation
