### ISSUE TITLE
Human readable names and groups for log details

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1108]
Spinning off #791 
Andreas: "All the other details have clear, human readable labels. The cli names are very easy to grep for, something that is quite handy in the cli, but I don't think we need that to quite the same extent, so going for easy to read instead. I didn't put the details in any particular order, so it might be that they could be arranged better."

Stef: "I agree with readable names, but should we have a way to click somewhere and get the actual journald fields? These fields are very useful for filtering."

Also consider grouping messages by their meaning as suggested in #3869

It would be helpful if the log entry fields were visually grouped by their category in the man page entry for systemd.journal-fields.

Also, if the entry fields were visually grouped it might be helpful to hide the fields in the ADDRESS FIELDS category. They are mostly internal, used for navigation by other tools. In particular, the __CURSOR field is going to convey very little info to your typical sysadmin.

Also, the MESSAGE_ID field is a very special one and maybe should get special placing, like the MESSAGE field. And, as suggested in #53, be used to display the catalog description for the entry.

**Comment by martinpitt** [comment]
This is still current, but needs a design.

**Comment by martinpitt** [comment]
No progress in 8 years, let's just give up on this. The existing labels aren't too bad, defined outside of cockpit (in systemd), and an admin who needs/wants to look at that kind of verbosity probably even wants the original field names, so that they stay translatable to the CLI and the message filter input.
