### ISSUE TITLE
No terminal for docker container when unprivileged

### ISSUE THREAD

**Issue by Chris230291** [cockpit-project/cockpit#11086]
Hi guys. Should I be seeing a Terminal windows when I select a container? I see it in screenshots but I dont have it.

Random google image to show the thing I'm talking about https://developers.redhat.com/blog/wp-content/uploads/2016/11/fireshot-capture-13-containers-192-168-121-43_-https___192-168-121-43_9090_docker.png

Ubuntu 18.04.1 LTS

Cheers,
Chris

**Comment by martinpitt** [comment]
Yes, you should. It's working fine here. What do you see instead, can you please send a screenshot?

**Comment by Chris230291** [comment]
I just have a white space hwere it should be.

https://duaw26jehqd4r.cloudfront.net/items/3t0J2Z301r3n0f1W3w2d/Screenshot_1.png

**Comment by leomoty** [comment]
I can replicate this.

I have created a new user yesterday at work to share the container logs with a coworker. The user is marked as "Container Administrator". I got these warnings on console log:

```
docker.js:18147 se {problem: "access-denied", exit_status: null, exit_signal: null, message: "Not permitted to perform this action.", toString: ƒ}
(anonymous) @ docker.js:18147
T @ cockpit.js:879
(anonymous) @ cockpit.js:891
j @ cockpit.js:808
setTimeout (async)
A @ cockpit.js:813
D @ cockpit.js:890
q @ cockpit.js:919
r @ cockpit.js:945
(anonymous) @ cockpit.js:1851
l @ cockpit.js:55
o @ cockpit.js:162
v @ cockpit.js:525
m @ cockpit.js:534
S @ cockpit.js:433
M.i.onmessage.e.dispatch_data @ cockpit.js:365
t @ cockpit.js:226
postMessage (async)
(anonymous) @ index.js:3485
M.i.onmessage.e.dispatch_data @ cockpit.js:363
cockpit.js:524 Error opening directory '/var/lib/docker': Permission denied
v @ cockpit.js:524
m @ cockpit.js:534
S @ cockpit.js:433
M.i.onmessage.e.dispatch_data @ cockpit.js:365
t @ cockpit.js:226
postMessage (async)
(anonymous) @ index.js:3485
M.i.onmessage.e.dispatch_data @ cockpit.js:363
docker.js:2713 monitor for docker directory failed: access-denied
```

**Comment by marusak** [comment]
I can reproduce this easily, I just need to uncheck `Reuse my password for privileged tasks` on the login screen. I still can create  containers and everything else, but I cannot see terminal.

```
Error opening directory '/var/lib/docker': Permission denied @ cockpit.js:785:21
monitor for docker directory failed: access-denied @ client.js:419:36
```

**Comment by marusak** [comment]
Docker is being obsoleted and now we focus on [cockpit-podman](https://github.com/cockpit-project/cockpit-podman/). Also it seems that this never really worked and there is simple solution.
