### ISSUE TITLE
RAID5 with only two disks

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1109]
Even though RAID 5 [needs at least 3 disks](http://www.vantagetech.com/faq/raid-5-recovery-faq.html), we default to this in the create raid dialog, even if you only have 2 disks available.

Ping @lhinson as we probably spoke about this before.

**Comment by mvollmer** [comment]
> Note that mdraid allows a RAID 5 with only two disks. I think the array is then in the same state as a raid5 with 3 disks of which one has failed.

That's wrong.  A RAID 5 with two disks is essentially a mirror, one disk with data, the other with parity.  There is nothing special about a RAID 5 with two disks, and it doesn't behave fundamentally differently than a RAID 5 with three or more disks.  it can still tolerate the failure of one disk.  It's just that with two disks, a RAID 5 has no advantages over RAID 4 or RAID 1.

**Comment by mvollmer** [comment]
So, conclusion: we allow creating RAID5 with two disks, simply because mdadm allows it.

**Comment by andreasn** [comment]
makes sense
