### ISSUE TITLE
Custom menu side by side with machines and dashboard

### ISSUE THREAD

**Issue by dhilst** [cockpit-project/cockpit#11093]
Page: All!?

I was wondering if is possible to get a main menu for grouping up custom plugins. It is easier to show with a image. The bellow image has 4 rows of icons, I want to add a new one, with another icon. Is that possible with a simple plugin? It would be feasible to do it?

![image](https://user-images.githubusercontent.com/392820/52095755-5e1b6600-25ab-11e9-9094-7855bb63e3d9.png)

Best regards!

**Comment by KKoukiou** [comment]
@dhilst if I understand correctly you want your custom new plugin to appear on this tab. If this is the question it's totally feasible. Check for example the manifest.json file in welder-web project. https://github.com/weldr/welder-web/blob/master/public/manifest.json
Adjust label, order and icon should make it appear where and how you want.

**Comment by dhilst** [comment]
@KKoukiou THANKS! I didn't know about welder-web
