### ISSUE TITLE
cockpit doesn't identify os for debian_version 9.7

### ISSUE THREAD

**Issue by lachlan-00** [cockpit-project/cockpit#11112]
My older stretch boxes on debian_version 9.6 identify correctly.

But my most up to date stretch box is just blank.
This box is on release 9.7
```
cat /etc/debian_version
9.7
```

![image](https://user-images.githubusercontent.com/1305249/52256320-f4f87180-2961-11e9-84f7-311cf4d46e0e.png)

**Comment by marusak** [comment]
I think this information is retrieved from `/etc/os-release`. Can you please show the content of this file?

**Comment by lachlan-00** [comment]
```
root@files:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by lachlan-00** [comment]
looks okay in v187 now
