### ISSUE TITLE
storage: unable to resize encrypted LUKS FS on log volume under 1Gb -> strange error eg. integer overflow

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#11129]
version: 184.1-1
distro: RHEL-X

I'm unable to resize partition less than 1Gb -> it seems lead to some type trouble with integer probably:

Number '-113246208' is not in range for the expected type 't'

![screenshot from 2019-02-07 13-24-07](https://user-images.githubusercontent.com/8735467/52411371-dc13cb80-2adb-11e9-8cf5-13b714e12f15.png)
![screenshot from 2019-02-07 13-23-59](https://user-images.githubusercontent.com/8735467/52411372-dcac6200-2adb-11e9-94aa-59f4a4119d90.png)
![screenshot from 2019-02-07 13-24-37](https://user-images.githubusercontent.com/8735467/52411370-dc13cb80-2adb-11e9-9f1a-cd92f2423149.png)

**Comment by jscotka** [comment]
this could be somehow connected with https://github.com/cockpit-project/cockpit/issues/11239
there are are some troubles with coversions/rounding/limits.
Should be made more robust at all

**Comment by mvollmer** [comment]
This is a bug in how Cockpit 184 handles logical volumes that are not fully used by the LUKS container in them.  Cockpit has changed a lot in that area, so please retest with the latest version in rhel-8.

Specifically, your logical volume is 1.11 GiB but the LUKS container is only 200 MiB.  Cockpit assumes that this is all normal and that the difference (800 MiBs or so) is the LUKS overhead.  So when you try to shrink the logical volume by 500 MiB, say, Cockpit will try to resize the LUKS container to -300 MiB, which will fail.

How did you arrive at this situation?  Did you use lvresize or similar command line tools?  Or just Cockpit?
