### ISSUE TITLE
Storage menu/section not present for arm-based fedora system

### ISSUE THREAD

**Issue by swvajanyatek** [cockpit-project/cockpit#11139]
Cockpit version: 2010-02-06
OS:Fedora 29
Page: Storage

On another, traditional Fedora 29 installation, cockpit  shows Storage under Logs, but on a Fedora 29 arm instance (raspberry pi 3B+), I don't see Storage at all.  Is this expected?

![image](https://user-images.githubusercontent.com/4095853/52490944-eee9d700-2b93-11e9-8354-00eaa424888a.png)

**Comment by marusak** [comment]
Storage is provided by package `cockpit-storaged`. 
Can you check you have this package installed or if it is available?

**Comment by martinpitt** [comment]
Ping?

**Comment by marusak** [comment]
@swvajanyatek

**Comment by swvajanyatek** [comment]
looks like installing the `cockpit-storaged` package did the trick.  thank you all for the help
