### ISSUE TITLE
Running 'make' has issues with 'webpack-make'

### ISSUE THREAD

**Issue by AdamKearn** [cockpit-project/cockpit#11130]
Hello,
When running `make` I am getting an error saying that "webpack-make is missing on my system"

```
root@cros-server:/home/cros-server/cockpit# make
make  all-am
make[1]: Entering directory '/home/cros-server/cockpit'
  WEBPACK  apps
webpack-make: Unexpected token {
WARNING: './tools/webpack-make' is missing on your system.
         You might have modified some files without having the proper
         tools for further handling them.  Check the 'README' file, it
         often tells you about the needed prerequisites for installing
         this package.  You may also peek at any GNU archive site, in
         case some other package contains this missing './tools/webpack-make' program.
Makefile:8851: recipe for target 'dist/apps/stamp' failed
make[1]: *** [dist/apps/stamp] Error 127
make[1]: Leaving directory '/home/cros-server/cockpit'
Makefile:2951: recipe for target 'all' failed
make: *** [all] Error 2
root@cros-server:/home/cros-server/cockpit# 
```

I was having some issues before this #11104  But it looks like they have been fixed now I have downgraded to `Ubuntu 16.04`.

What do you think is happening here?
Many thanks
-Adam

**Comment by martinpitt** [comment]
First, please don't build as  root.

What happens if you run `./tools/webpack-make --help`?  It should look something like this:
```
USAGE: node webpack-make [OPTION1] [OPTION2]... arg1 arg2...
The following options are supported:
  -d, --deps <ARG1> 	Output dependencies in Makefile format
```

This uses the `node` JavaScript interpreter. What does this say?
```
which node
node --version
```

**Comment by AdamKearn** [comment]
```
root@cros-iveshead-server:/home/cros-server/cockpit# npm --version
3.5.2
root@cros-iveshead-server:/home/cros-server/cockpit# ./tools/webpack-make --help
webpack-make: Unexpected token {
root@cros-iveshead-server:/home/cros-server/cockpit# 
```

If I don't build as root I get errors saying that it should be run as admin

**Comment by martinpitt** [comment]
So supposedly node 4.2 is way too old, and you do need a newer version, sorry.

**Comment by AdamKearn** [comment]
I'm picking this back up now

What version of nodejs are you running?
And what Ubuntu are you running as well?

**Comment by marusak** [comment]
Sorry for very late response. My versions which work:

$  npm --version
6.9.0
$ node --version
v10.16.3

This is on Fedora 30, which most of developers use now.

**Comment by marusak** [comment]
No reply for some time, closing. Please reopen if still have some questions about make.
