### ISSUE TITLE
machines: very complex message for 

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#11140]
Cockpit version: 187
OS: Fedora 29
Page: Machines

If I don't keep close track on how much memory I have on the host and accidentally creates a VM with more memory than what's available, it will kick me out of the dialog, making me loose all the data I inputted, such as name, ISO, storage etc. I'm then presented with a very long message that suggests me to restart the domain, however, if I do that, I get this message:
```
error: failed to get domain 'asdf'
error: Domain not found: no domain with matching name 'asdf'
```

Steps to reproduce

1. Create a new VM and set the Memory to more than what's available on your host
2. Hit Create

![screenshot from 2019-02-08 21-45-23](https://user-images.githubusercontent.com/209895/52505258-39e30900-2beb-11e9-9270-75c501a0a29a.png)

**Comment by andreasn** [comment]
If insufficient memory is the root cause, then I suggest we check for that already in the Create dialog, similar to what's suggested for insufficient storage #11078

**Comment by KKoukiou** [comment]
I think it makes sense to limit memory on VM creation to the total memory of the host.
However this does not guarantee that this memory be available. The host OS also need some memory, and of course if multiple VMs are running, with memory limit the hosts memory, and this memory is actually used, the performance will be bad anyway.

But I tend to agree that limiting the max VM memory during creation to the hosts total memory makes sense.

**Comment by andreasn** [comment]
Yeah, I don't think we'll be able to cover all error cases, but I think a lot of them would be caught by this.

**Comment by andreasn** [comment]
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/6b3d59bfe004aeec870d3afed7addabfa04507a1/virtual-machines/create-vm-dialog-error.png)

**Comment by KKoukiou** [comment]
This was addressed in https://github.com/cockpit-project/cockpit/pull/11491
