### ISSUE TITLE
testSnapshots (check_storage_lvm2.TestStorage) is flaky

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#11146]
100% on verify/rhel-8-0
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190123-172323-60426039-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190123-172323-60426039-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190123-172323-60426039-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190122-131111-86c5e875-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190122-131111-86c5e875-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190122-131111-86c5e875-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190122-120101-2db5c4ff-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190122-120101-2db5c4ff-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190122-120101-2db5c4ff-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190122-094343-0eb317b6-verify-rhel-8-0/log)

<details><summary>Source material</summary>

```json
{
  "test": [
    [
      "testSnapshots (check_storage_lvm2.TestStorage)",
      12
    ]
  ],
  "status": [
    [
      "failure",
      12
    ]
  ],
  "tracker": [
    [
      null,
      12
    ]
  ],
  "context": [
    [
      "verify/rhel-8-0",
      12
    ]
  ],
  "merged": [
    [
      true,
      12
    ]
  ],
  "date": [
    "2019-01-22T11:01:39Z",
    "2019-01-23T17:43:56Z"
  ]
}
```
</details>

**Comment by martinpitt** [comment]
This only ever happened on that one PR which was expected to fail.
