### ISSUE TITLE
xterm.js does not have color

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11149]
Firstly, it's great to see we're using xterm.js instead, as of https://github.com/cockpit-project/cockpit/pull/11125.

However, I'm pretty sure the old terminal had color support. Locally, I don't see color.

I've tested with both `ls --color=auto` and `htop`.

**Comment by garrett** [comment]
Screenshot of Cockpit's terminal:

![screenshot_2019-02-11 terminal - sunny](https://user-images.githubusercontent.com/10246/52554394-f9e87580-2de6-11e9-82b0-aed80dc88cd2.png)

Expected behavior (crop from a local terminal):

![screenshot from 2019-02-11 10-22-35](https://user-images.githubusercontent.com/10246/52554417-0f5d9f80-2de7-11e9-863c-ea476905be53.png)

**Comment by leomoty** [comment]
@garrett Pretty sure xterm.js does support colors, it appears just fine in VS Code (for example).

**Comment by martinpitt** [comment]
Colors work fine here, I wouldn't have merged it otherwise. See my screenshots in https://github.com/cockpit-project/cockpit/pull/11125#issuecomment-461386495

"Here" is Firefox 65 and Chromium71 on current Fedora 29.

However, I suspect that this is due to `$TERM`. What does your terminal say for `echo $TERM`? Mine is `xterm-256color`, but I'm not entirely sure where this is set.

**Comment by marusak** [comment]
Can you please specify what shell are you using? And while on it, what browser and version.

https://github.com/cockpit-project/cockpit/blob/master/pkg/systemd/terminal.jsx#L25
we create bash unless user has one specified. And we also set up `TERM=xterm-256color` (see one line lower).

**Comment by garrett** [comment]
I'm using zsh and I get `xterm-256color` from both Tilix (native desktop terminal) and Cockpit's terminal.

However, now I see color in Cockpit. But I have been switching branches and did have some build system oddities earlier.

My guess is that this was due to my system's inconsistent state this morning, due to being out sick for a few weeks and not keeping up with Cockpit's development pace. :wink:

Closing as a **`WORKSFORME`**, basically. Thanks for looking into this, BTW. Sorry for the noise.
