### ISSUE TITLE
Question: two cockpit instances on the same machine 

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [cockpit-project/cockpit#11153]
Hi, I would like to check is it possible to have two parallel cockpit instances on the same machine. One is original cockpit instance and second is customised and compiled for specific needs instance, with different port, services names, packages and certificate directories. Could this two instances run independent? Except the list above, what additional separation I need to do?

**Comment by martinpitt** [comment]
If you put them on different port, and start the other one with a different `$XDG_DATA_DIRS` so that cockpit-bridge picks up a different set of packages, it should actually be possible. I don't think anyone in the team actually tried that yet.

**Comment by marusak** [comment]
@igorSmirnovPlexi did that work for you?
