### ISSUE TITLE
cockpit denial of service

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [cockpit-project/cockpit#11160]
Cockpit version: 176
OS: mac os
Page: none
Browser: Chrome

When navigating to https://address:9090/cockpit/static/% and reload the page for several times, cause the cockpit to crash. Only restart cockpit service returns UI back. 

Steps to reproduce:
1. navigate to https://address:9090/cockpit/static/%  and getting "This page isn’t working"
2. reload page several times until getting "This site can’t be reached"
3. cockpit is crashed, could not access any page

**Comment by martinpitt** [comment]
This got fixed in PR #10662 and does not happen any more with current versions.
