### ISSUE TITLE
cockpit-machines: No way to create a VM based on a qcow2 image

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#11163]
Page: Machines

The only input that can be used to create a new VM is an ISO. This usually also means sitting through an installer, and that's less fun. It would be great if I could use a disk image as input.

**Comment by andreasn** [comment]
Initial implementation sketch:
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/0bb4e3866f1ecf209272239cc0d2f7639d485e85/virtual-machines/create-vm-cloud.png)

If we're building off an image, we need some way to sign into the VM. Since there won't be a user creation screen, like you usually get with the ISO installers, we need to to that in another way.
I think we can leverage cloud-init here and suggest copying good default values off the host into the VM, or to set custom values, in the cases where an admin is preparing an image for someone else.

**Comment by andreasn** [comment]
The way I would test that this work is to be able to successfully boot and log in to Fedora Atomic Host https://download.fedoraproject.org/pub/alt/atomic/stable/Fedora-29-updates-20190121.0/AtomicHost/x86_64/images/Fedora-AtomicHost-29-20190121.0.x86_64.qcow2

**Comment by KKoukiou** [comment]
@andreasn  where did you inspire from for the *delete vm when shuts down checkbox?

This means this VM will be transient and so far we don't support transient VMs.
docs for transient VMs here, https://wiki.libvirt.org/page/VM_lifecycle#Transient_guest_domains_vs_Persistent_guest_domains

Is it some request or some other product offering that feature?

**Comment by andreasn** [comment]
That was an idea from @larskarlitski so I think he knows the details better.
I wouldn't block on that. It can be implemented later I think.

**Comment by larskarlitski** [comment]
Love these designs. Thanks Andreas!

I think the "Set up an account" wording might be confusing. Could we use something from cloud-init's [terminology](https://cloudinit.readthedocs.io/en/latest/topics/capabilities.html)? Maybe "Provide cloud-init user data"?

Is there ever a situation where you don't want to immediately start the VM but also want it to be deleted when it shuts down? Can we combine those check boxes somehow?

> Is it some request or some other product offering that feature?

The idea is that I can quickly test a cloud image that I created in composer. Usually I wouldn't want to keep those around, but boot once and forget about it, without changing the image itself (what `qemu -snapshot` provides). We should probably write down a user story for this :)

**Comment by andreasn** [comment]
> I think the "Set up an account" wording might be confusing. Could we use something from cloud-init's [terminology](https://cloudinit.readthedocs.io/en/latest/topics/capabilities.html)? Maybe "Provide cloud-init user data"?

I wanted something that made sense also for people who are not aware of cloud-init.
What do you feel is most problematic about the current wording?

**Comment by KKoukiou** [comment]
> Love these designs. Thanks Andreas!
> 
> I think the "Set up an account" wording might be confusing. Could we use something from cloud-init's [terminology](https://cloudinit.readthedocs.io/en/latest/topics/capabilities.html)? Maybe "Provide cloud-init user data"?
> 
> Is there ever a situation where you don't want to immediately start the VM but also want it to be deleted when it shuts down? Can we combine those check boxes somehow?

The use case of immediately start VM checkbox is that you might want to configure a created VM before attempting installation. For example, you might want to add some NIC before installing the guest. This scenario is not really tight together with the concept of transient VMs, which means the VM is never defined in libvirt, and it will disappear when it shut's down.

> 
> > Is it some request or some other product offering that feature?
> 
> The idea is that I can quickly test a cloud image that I created in composer. Usually I wouldn't want to keep those around, but boot once and forget about it, without changing the image itself (what `qemu -snapshot` provides). We should probably write down a user story for this :)
