### ISSUE TITLE
Enable light and dark theme in terminal

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#11177]
Page: Terminal

It is possible to specify own [theme](https://xtermjs.org/docs/api/terminal/interfaces/itheme/) in xterm.js and change it dynamically.
This makes it possible to create any theme. It would be great to have light and dark theme.

Probably best solution (suggested by @garrett) is to have toggle switch.

Also section should be remembered in localStorage (as suggested by @martinpitt).

Also @garrett suggested using [solarized](https://ethanschoonover.com/solarized/) for selecting colors. However mapping between these colors and colors that xterm accepts needs to be investigated.

**Comment by garrett** [comment]
Here are screenshots that might give you an example about how GNOME Terminal uses Solarized:

### Solarized light
![gnome-terminal-solarized-light](https://user-images.githubusercontent.com/10246/52781924-0b7f8680-304e-11e9-9018-26519fc145aa.png)

### Solarized dark
![gnome-terminal-solarized-dark](https://user-images.githubusercontent.com/10246/52781957-2225dd80-304e-11e9-8065-74b9fb35a04b.png)

The main difference here seems to be the text color and background, at least judging from the screenshots.

**Comment by marusak** [comment]
Here are light and dark mode - picked from https://github.com/altercation/solarized/tree/master/vim-colors-solarized

Ideas? How do you like it?

![lightmode](https://user-images.githubusercontent.com/12330670/52785820-40450b00-3059-11e9-8bf0-1f92c2410d4a.png)
![darkmode](https://user-images.githubusercontent.com/12330670/52785821-40450b00-3059-11e9-96ee-cb7c18d78854.png)

**Comment by garrett** [comment]
It's looking good!

I need to make a mockup and integrate a switcher somehow. :wink:

**Comment by garrett** [comment]
Also: We need to decide on whether to have a light or dark terminal as the default.

As the other pages are a light background, perhaps we should make the terminal light too?

**Comment by marusak** [comment]
> I need to make a mockup and integrate a switcher somehow

I will do it now with simple select component and will be ready to rework it for any other switcher you come up with :)

> We need to decide on whether to have a light or dark terminal as the default.

Good point. I would go for dark as default, mainly as it would keep consistent (as now is dark theme). (the fact that I use and prefer dark theme is [almost] not affecting my decision :P )

**Comment by garrett** [comment]
What I have in mind is something similar to:

## Firefox's reader mode configuration popup

![firefox-reader-config-popup](https://user-images.githubusercontent.com/10246/52794527-4692b180-3070-11e9-8729-9dbd232184b8.png)

## Elementary's terminal config popup

![elementary-terminal-config](https://user-images.githubusercontent.com/10246/52794544-4beffc00-3070-11e9-9d91-23186950de63.png)

## Kindle app (Android)

|||
|---|---|
|![screenshot_20190214-154835](https://user-images.githubusercontent.com/10246/52795169-85753700-3071-11e9-9a17-a0da53d371ea.jpg)|![screenshot_20190214-154844](https://user-images.githubusercontent.com/10246/52795172-87d79100-3071-11e9-94f9-7b4efc8a7e3e.jpg)|

The Kindle device is similar, but the popup is a dialog instead... and it doesn't have different colors (not even inverse).

---

We should probably have font size adjustment and color theme in ours too. And perhaps have a white background theme too. (Everyone else is doing it like this.)

I like the way Firefox and Elementary have options for 3 color schemes as radio buttons basically. Firefox has bonus points for text too.

We could even have Light / Dark / Sepia / Retro (with retro being green). If we adpoted terminology like that, Sepia would be Solarized light and we'd have to have a non-Solarized theme for light. Retro would be green with scanlines as sort of a playful easter egg (and probably a chunky font if we want to go for the full retro green screen look).

...Or we could just start out with Light / Dark and stick with Solarized.
