### ISSUE TITLE
List: Mobile is missing right side border in Software Updates

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11202]
There's most likely an `overflow: hidden` truncating the right side of the mobile list.

![updates view on mobile](https://user-images.githubusercontent.com/200109/52948209-236e4780-3379-11e9-8cbd-d1711712663c.png)

As seen on #11196

**Comment by martinpitt** [comment]
Our tables now got changed to not have this box at all any more:

![update-history-mobile](https://user-images.githubusercontent.com/200109/68203318-d5ac7480-ffc5-11e9-9131-c3b35f351bd9.png)

This was probably a side effect of the PF4 changes?

So at least the mobile view looks consistent now.
