### ISSUE TITLE
PackageKit: Optimize list of packages (flow-list) using flex or grid

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11203]
The list of packages could probably be improved with alignment and sizing based on flex or grid. (Right now, it's a bunch of inline blocks with fixed widths.)

**Comment by garrett** [comment]
As mentioned in https://github.com/cockpit-project/cockpit/pull/11196#issuecomment-465115129

**Comment by martinpitt** [comment]
@garrett: Do you have something more concrete in mind here? If not, I'd say let's just close this. We have tons of "this could be improved" things that we never get to :-)

**Comment by garrett** [comment]
The idea was to have the sizing based on the content instead of having a fixed width.

Sure; let's just close this.
