### ISSUE TITLE
NTP Permission Denied

### ISSUE THREAD

**Issue by liberodark** [cockpit-project/cockpit#11218]
Cockpit version: 188
OS: Debian 9

Have juste install cockpit in fresh server but not possibility to change date.

<a href="https://i.imgur.com/lb0XJI7.png">
  <img src="https://imgur.com/lb0XJI7l.png" />
</a>

ntp is installed and running !

**Comment by liberodark** [comment]
Other Bug have see that 

<a href="https://i.imgur.com/RVM8R3V.png">
  <img src="https://imgur.com/RVM8R3Vl.png" />
</a>

cockpit-pcp not found for what ?

have try apt get install too but not found.

**Comment by martinpitt** [comment]
As for your second question, cockpit-pcp indeed only exists in unstable and testing (see https://packages.debian.org/cockpit-pcp).

I'm curious how you managed to get version 188 that early? I just uploaded it to Debian this afternoon and it's not even published to the mirrors yet. Can you please check `dpkg -l cockpit-system` for the  version?

I don't have an immediate idea about the NTP "permission denied".

**Comment by liberodark** [comment]
im use YunoHost ; https://github.com/YunoHost-Apps/cockpit_ynh

**Comment by martinpitt** [comment]
Do you still have that problem with current versions? I can't reproduce this with further information. If you get this still, please check `sudo journactl --since='10 minutes ago'` and paste it here. Thanks!

**Comment by martinpitt** [comment]
Not reproducible, reporter can't reproduce either any more.
