### ISSUE TITLE
Cant add new server

### ISSUE THREAD

**Issue by Kendokai** [cockpit-project/cockpit#11216]
I've installed and run cockpit successfully but it only on one machine and there is also no Storage option in navigation list too as image below. Should I enable this function somewhere ?
![2019-02-20 18 47 39](https://user-images.githubusercontent.com/8243358/53089763-0cc61d00-3540-11e9-979b-d9afc0f5051a.jpg)

And I can't a way to add new server. In image below there is a Dashboard button to add another server but I can't find this button in my cockpit server. Should i need to install or config to enable this functions ?
![dashboard-192 168 43 2-chromium_018](https://user-images.githubusercontent.com/8243358/53089887-63335b80-3540-11e9-9b0e-2e3e942339cc.png)

**Comment by marusak** [comment]
You miss some packages.
For storage install `cockpit-storaged` and for dashboard install `cockpit-dashboard`.

**Comment by Electronics** [comment]
I have a similar problem that I am missing the Storage tab as well as Networking and Logs sometimes, I have installed the different packages on the new server end: 
![image](https://user-images.githubusercontent.com/422393/53099845-906f1200-351e-11e9-8c19-edb2a8b0631a.png)

**Comment by choungchamnab** [comment]
I seem can't add another server to dashboard.It always return 
`Cockpit was unable to log into 192.168.33.11. You can change your authentication credentials below. `

**Comment by KKoukiou** [comment]
@choungchamnab how are you trying to authenticate to that server?

**Comment by KKoukiou** [comment]
Closing since this has been inactive for 7 months already.

**Comment by zailaib** [comment]
![image](https://github.com/user-attachments/assets/63e0384a-02f5-426a-bb0d-c3a7e93bc2f3)
this config worked for me . THK
