### ISSUE TITLE
PackageKit: Applying Updates Failed

### ISSUE THREAD

**Issue by leomoty** [cockpit-project/cockpit#11222]
I had some DNS failure while trying to update my cockpit 186 install. When it failed I got greeted by a `<pre>` that spans the entire width available and is not offsetted from the header. As shown:

![image](https://user-images.githubusercontent.com/1463740/53133378-b235bc80-3551-11e9-8073-7e23db4eaebb.png)

There is no clear way to revert back to the updates page.

**Comment by martinpitt** [comment]
Right, this is a sore point. When an update error happens, it's not actually clear what Cockpit can do to get out of this. Trying to install more updates, or trying it again (i. e. just giving a way back to the updates page) will most likely either fail again, or make things worse. In this case the admin really has to fix things manually.

(You can always reload the page, of course)

**Comment by leomoty** [comment]
Yeah, I noticed, but perhaps a button to actually reload the page? It really looks out of place, compared to everything else.
