### ISSUE TITLE
On Off Switch: Animate between normal and disabled states

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11226]
Changing between normal and disabled states should have a subtle CSS transition-based animation that adjusts at least the color, background, and outline.

This is useful for https://github.com/cockpit-project/cockpit/pull/11224, where there is an intermediate state while the toggle is being processed in the background (and the toggle should not be flipped back meanwhile).

**Comment by garrett** [comment]
Here's a codepen that builds on top of PF3 style CSS.

https://codepen.io/garrett/pen/MRZYaV

I wrote some HTML and LESS to make it resemble the PF4 switch widget, complete with navigation. It should hopefully be accessible (as it's a checkbox wrapped with a label — and the rest is presentation), but we _might_ need a little JS to toggle ARIA to help guide screen readers. (Then again, it might be fine? Needs testing.)

The colors are similar to PF4, but use PF3 instead. (It's most noticeable in the slightly different shade of blue.)

Regardless, it is already tons better than what we have (in terms of both usability and accessibility).

**Comment by garrett** [comment]
@andreasn: Please check out the codepen and let me know what you think. I could probably port this over officially once I'm done with the panels.

**Comment by garrett** [comment]
Note: Looking at it in the context of the services mockup I'm working on, I think we might want to style up the widget even a bit more, with very subtle borders, gradients to better match PF3.

**Comment by andreasn** [comment]
Codepen example looks good to me!

**Comment by andreasn** [comment]
Do you have a link to the services mockup?

**Comment by martinpitt** [comment]
That's awesome, thanks @garrett! Indeed I'd really like to get rid of cockpit-components-onoff, or at least swap out its implementation with this until we move to PatternFly 4. The most important issue here is to get rid of the "On"/"Off" translatable labels.

**Comment by garrett** [comment]
> Do you have a link to the services mockup?

Not yet; It's still a bit too rough. I hope to finish it today (or tomorrow?), but my priority at the moment is getting some PRs to land. Then I'll get back to the mockup. :+1:
