### ISSUE TITLE
"test-sshbridge" fails against libssh-0.8.6

### ISSUE THREAD

**Issue by stanislavlevin** [cockpit-project/cockpit#11223]
Cockpit version: 187
OS: ALTLinux

Actually, I'm packaging cockpit since version 180.
At that time we had libssh-0.8.4. So, due to https://bugs.libssh.org/T117 mock-sshd tests have been skipped.
Recently libssh-0.8.6 landed in my distro and these tests become runnable, but the result is always FAIL with:
```
# random seed: R02S2d22e60f9e9ed9f88595850b42c8d5b1
# GLib-DEBUG: posix_spawn avoided (workdir specified) (fd close requested) 
# GLib-DEBUG: posix_spawn avoided (workdir specified) (fd close requested) (child_setup specified) 
# cockpit-protocol-DEBUG: test-ssh: output queue empty
# cockpit-protocol-DEBUG: test-ssh: reading input 1
# cockpit-protocol-DEBUG: test-ssh: received a 73 byte payload
# cockpit-protocol-DEBUG: test-ssh: want more data
# cockpit-protocol-DEBUG: test-ssh: queued 116 byte payload
# cockpit-protocol-DEBUG: test-ssh: wrote 5 bytes
# cockpit-protocol-DEBUG: test-ssh: wrote 116 bytes
# cockpit-protocol-DEBUG: test-ssh: output queue empty
cockpit-ssh-Message: 06:56:36.945: cockpit-ssh 127.0.0.1:33523: -1 couldn't connect: Public key from server (rsa-sha2-512) doesn't match user preference (ssh-rsa,ssh-dss,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256) '127.0.0.1' '33523'
**
ERROR:src/ssh/test-sshbridge.c:515:wait_until_transport_init: assertion failed (problem == expect_problem): ("no-host" == NULL)
```
and so on.
I found out that Fedora30(?) patched libssh:
https://src.fedoraproject.org/rpms/libssh/blob/master/f/libssh-0.8.6-fix-rsa-sha2-ext.patch

These changes are only in libssh upstream/master.
Using this patch set I built libssh for the test. This helped (all tests passed).
So, I want to say that "clear" 0.8.6 is still not suitable for cockpit testing.

**Comment by martinpitt** [comment]
Right,  0.8.6 had this major regression. But there's not much that we can do about it on the cockpit side -- revert to 0.8.5 or apply the fix. I [patched it in Debian](https://salsa.debian.org/debian/libssh/commit/8922d6c8a22c115f311a985abb3f0219b4b0b00e), too.
