### ISSUE TITLE
storage: Failed to meet partition size on device

### ISSUE THREAD

**Issue by leomoty** [cockpit-project/cockpit#11239]
Cockpit version: 187
OS: Ubuntu 18.04.02 LTS, armhf
Page: Storage

Installed a new HDD. Expected to be able to create a partition with maximum size available, instead:

![image](https://user-images.githubusercontent.com/1463740/53293567-e78e1480-37b4-11e9-9c8b-924499ac9551.png)

Maybe it is because rounding? Not really, still happens with MiB.

![image](https://user-images.githubusercontent.com/1463740/53293572-eeb52280-37b4-11e9-8b99-5e8d8f13ec62.png)

One way or other, I would expect to be able to adjust the slider to the maximum available number and create a partition.

**Comment by sramsay64** [comment]
Not sure if this is relevant info but I got the same error message string in a different application (https://en.wikipedia.org/wiki/GNOME_Disks running on mint 19.2 xfce). Maybe the same dependency/library causes the issue (udisks?). I tried gparted and this solved my problem (which I think bypasses udisks).

Hope this helps the cockpit project. Sorry if this is just noise.

![2020-01-19-014603_3840x1080_scrot-cropped](https://user-images.githubusercontent.com/6789285/72666568-9c7f8e80-3a63-11ea-98da-f2f610d89c1b.png)

**Comment by martinpitt** [comment]
@sramsay64 : Correct, cockpit's Storage page uses udisks, exactly like GNOME Disks.

**Comment by KKoukiou** [comment]
I just tried to verify on Cockpit 242 and udisks2-2.9.1-2.fc33 and this is no longer reproducible. 

![Screen Shot 2021-04-16 at 14 08 48](https://user-images.githubusercontent.com/14921356/114867051-9c03ae00-9df4-11eb-96a2-9e4b23172489.png)

So basically there is no error shown in the UI any more. 

I guess some udisk/systemd update fixed the problem in the meantime.
