### ISSUE TITLE
Services: Improve mobile layout for filter bar and list

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11258]
As mentioned in https://github.com/cockpit-project/cockpit/pull/11241#pullrequestreview-207961002, the filter bar behaves oddly in narrow viewports, as does the list.

This has a few sub-tasks:
- [ ] Filter bar should collapse more optimally.
- [x] Filter bar should use `position: sticky`, not `position: fixed` (and the margin for the following container should be adjusted accordingly).
- [ ] Improve service list layout.

**Comment by garrett** [comment]
I've switched to using `position: sticky` and improved the accessibility of the list table in #11241. The other list items remain.

Improving the layout for mobile mode will be a little more tricky, as we'll want to keep it being accessible at the same time. While #11260 applies more for React list (and the Services page uses its own implementation), refer to it for details.

**Comment by marusak** [comment]
Related with #8672

**Comment by garrett** [comment]
Somewhere within a few PRs, @marusak and I fixed this.
