### ISSUE TITLE
Enhance showing units' templates

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#11269]
Page: Services
Came from #11241
In services page under `Services` or `Timers` there can be templates which are always a bit odd as do not have `Status` nor `Automatic Startup`. Also there is different behavior upon clicking on them. Also picking any startup option different than `All` hides all of them.

There are some ideas how to do this:

- Create another type next to `Paths` (But it is not really another type, it can be timer or service)
- Drop them into another table (This would be step back as #11241 removes splitting into tables)
- Introduce auto start option `Templates` - which is kinda weird to have it there and also it would not solve problem that templates look odd in the table (especially in timers table)

**Comment by andreasn** [comment]
So how does templates actually work? What's a workflow where I need to use them?

**Comment by marusak** [comment]
So I am not expert in this, but I will try to explain it as best as I can :)

Template is almost normal unit except it takes one variable - that both uniquely identifies the unit (it is in it's name/id) and also can be used inside the unit as argument. In that case you can create bunch of units that differ just a bit (where you use the variable inside unit - All `%i` in unit file are replaced by the argument you instantiate it with). And then each of those units behaves like normal unit that you can start, stop, enable, disable...

For a real user problem see for example [this](https://serverfault.com/questions/730239/start-n-processes-with-one-systemd-service-file).
Or for example you can run multiple httpd services by using templates - see https://www.mankier.com/8/httpd.service#Description-Instantiated_services

If you want to see some instantianted services search for "getty" in services page. Then hit 'ctrl+alt+f4' login and jump back and see that now you have there also `getty@tty4.service`

**Comment by marusak** [comment]
Replaced by #14549
