### ISSUE TITLE
Do we need a delete confirm dialog when deleting bonds and bridges

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#1126]
Same as the title.

**Comment by martinpitt** [comment]
IMHO it's clear enough what happens there -- select a bond/bridge, and there's a red Delete button which isn't that easy to click accidentally. There are some Delete buttons in Cockpit which ask for confirmation, such as force-deleting  a running container. But e. g. on the Services page the buttons don't ask either. This should be a result of an usability test, we've had several, and apparently it didn't come up. So closing this for now.
