### ISSUE TITLE
Add update state to dashboard

### ISSUE THREAD

**Issue by vampywiz17** [cockpit-project/cockpit#11275]
dashboard

It would be great, that if we add more than one server, we able to see the update state, on main dashboard. One of security and one of regular updates.

I make a little drawing, what my idea:

![image](https://user-images.githubusercontent.com/14281430/53648698-db84d580-3c40-11e9-8ee1-8a4f80558fdc.png)

**Comment by marusak** [comment]
cockpit-dashboard has been obsoleted. Also cockpit should not really a) connect to every machine and check its status b) be used for fleet management, but for single instance debugging and managing.
