### ISSUE TITLE
Cockpits default format type is not liked by the pools dialog

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1127]
I was really scratching my head over this one, but finally figured it out.
Whatever I did, I could never find my new disks in the Storage pools dialog.
It seems that the MBR format that we use by default in the Format dialog is disliked by the Create Volume Groups dialog.

**Comment by mvollmer** [comment]
Cockpit wont let you use a block device with a partition table on it as a new physical device (for example).  You need to either make a partition on it, or wipe the partition table.
