### ISSUE TITLE
resize logical volume dialog is error prone

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1128]
The resize logical volume dialog suffers to issues similar to issue #1116
Miscounting the number of the new size will give the error "Error resizing logical volume: lvresize exited with non-zero exit status 5: Insufficient free space: 75 extents needed, but only 50 available" but ideally we should be able to catch this error before and present that inline.

**Comment by mvollmer** [comment]
We use a slider now, just as for #1116.
