### ISSUE TITLE
user level ssh config not used

### ISSUE THREAD

**Issue by sebastianschauenburg** [cockpit-project/cockpit#11296]
Cockpit version: 179 & 187 (cosmic-backports)
OS: ubuntu 18.10 (cosmic)
Page: dashboard

The user level ssh configuration file ( ~/.ssh/config ) does not seem to be used.

When trying to add a remote server using the dashboard and filling in a custom SSH alias (which is in .ssh/config and contains HostName, User, IdentityFile and sometimes Port and/or ProxyCommand), cockpit fails with:

> Cockpit could not contact the given host shortcut.example:22. Make sure it has ssh running on port 22, or specify another port in the address.

Steps to reproduce

1. Add an SSH host name alias to your SSH config (user level) with a custom Host, User, IdentityFile and HostName. Example:

> Host shortcut.example
>     User            someusername
>     IdentityFile    ~/.ssh/id_rsa_example
>     HostName        actual.server.to.connect.to

Note: Connecting to this server using the SSH alias (here: shortcut.example) through the commandline should work. Example:

> ssh shortcut.example

2. Try to add that SSH host to your dashboard using the shorcut :

> shortcut.example

Note: I've read [the Cockpit 183 blogpost](https://cockpit-project.org/blog/cockpit-183.html), hence the upgrade to the backported Cockpit version.

**Comment by KKoukiou** [comment]
I bet @Gundersanne can answer this easier.

**Comment by sebastianschauenburg** [comment]
@Gundersanne any ideas on this matter by any chance?
@KKoukiou thanks for the referral

**Comment by Gundersanne** [comment]
Oh sorry for not seeing/replying to this earlier. 

This is indeed be possible after 183, but we only start parsing the user config file from libssh 0.8.5 because of previous bugs. And cosmic only has 0.8.1. So that's where the problem here lies.

**Comment by sebastianschauenburg** [comment]
@Gundersanne no worries and thank you for your reply.

In the meantime I've tested this on a 19.04 system (cockpit 189, libssh 0.8.6). The issue unfortunately persists.

**Comment by Gundersanne** [comment]
@sebastianschauenburg So I tried this on 19.04 and changes I make in the users ssh config does have an influence for me, but there are some bugs.

What works are the ProxyCommand, Port and HostName directives. Do you have issue with any of these?

What is definitely bugged:
- the user from the config file gets overwritten with the user from the cockpit session or the user from the url user@...; this makes this directive moot

- you need to add the ssh key into your cockpit session via the menu>authentication, and enable it. It seems to ignore the IdentityFile directive in the ssh config, yet keys added via cockpit are tried.

So needless to say these are bugs and have to be fixed.

**Comment by Gundersanne** [comment]
I'm reopening this because with locked identity files `cockpit-ssh` will still fail. I would like to at least give feedback that the identity file is locked and point to cockpit's built-in authentication menu to add the key to the ssh-agent. Ideally this would happen entirely interactively but this would require non-trivial changes to `cockpit-bridge`.

That said non-locked identity files in the user config should work, and the User directive should now take priority over anything cockpit does/assumes.

**Comment by martinpitt** [comment]
This was fixed for good with the recent SSH rework.
