### ISSUE TITLE
Non-root problem: insufficient privileges

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#1130]
File this for the non-root problems list, do we keep using "You are not allowed to perform this operation" dialog or instead of this?
![screenshot from 2014-08-28 11_46_08](https://cloud.githubusercontent.com/assets/3952545/4173993/61d72c5e-3571-11e4-9596-a39fa0bd355e.png)
![screenshot from 2014-08-28 11_46_20](https://cloud.githubusercontent.com/assets/3952545/4173994/61da29e0-3571-11e4-8bfe-469534fa2506.png)

**Comment by mvollmer** [comment]
This works now.  The buttons are disabled for non-admin users.
