### ISSUE TITLE
machines: Installation Source autocomplete is tedious to use for deep folders

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#11300]
Cockpit version: 183
OS: Fedora Server
Page: Machines

I have my ISOs buried pretty deep in subfolders of subfolders, and when typing the path for getting to a CentOS iso, it suggested to autocomplete, but I had to take my hands off the keyboard, use the mouse in the dropdown, then start typing the next subfolder, then using the mouse again etc.

Steps to reproduce

1. Put an ISO in a folder 3 or 4 levels deep, ideally with long names of the folders
2. Create a new machine and select filesystem as source

**Comment by andreasn** [comment]
Video: https://andreasn.portknox.net/s/HafrQPj6PczcyX2

**Comment by marusak** [comment]
It would be cool if it would work with tab completion. One tab press would fill up the longest possible prefix, double tab click would show list of possible paths. The problem with this approach is that tab is used for moving between dialog fields, which could be usability issue. Or possibly bind tab to autocompletion and once a valid file is present free tab for moving?

**Comment by garrett** [comment]
I didn't see this issue and opened #11322 a while back.

The gist of the other issue was to consider https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html and retool our autocomplete based on one of the example accessible ones.

I suggest [Example 3](https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html#ex3_label), which also has HTML, CSS, JS code available linked on the page, and has HTML specific to example 3 at the bottom.

@andreasn, @marusak: Please look at example 3 on that page and let me know what you think. (Of course, we'd restyle it to look more like our own.)

**Comment by andreasn** [comment]
Example 3 looks like a good approach to me!
