### ISSUE TITLE
Software Updates: Improve native select experience

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11305]
Now that native selects has been implemented (and is about to land), it has exposed some small areas where the Software Updates page could be improved.

- [x] Drop "on" from "on Mondays" — at least in English — to read "Mondays", "Tuesdays", etc.

   - This is plural, and the "on" isn't needed in English here.

   - Reasoning: When the select has focus (either in collapsed or expanded state), typing the word does a match... so you can start press "F" for Friday and it'd instantly match.

   - This little optimization might not work on other languages quite as well.

- [ ] Have a slightly higher debounced timeout threshold.

   - Right now, the change event seems to instantly fire the request, then the form's disabled state is triggered, and it breaks the flow of typing.

   - Ideally, you should be able to type "21" to select "21:00" with the focus on collapsed select. Right now, it selects "20:00" then the next item (in the first instance 21:00, but then it selects "22:00", and "23:00" oddly... depending on timing) as it's interrupted.

   - To replicate the experience, hit tab on the weekday select, then try to type the time.

   - This is also a problem with the weekday selector, but the "on" masks the issue a bit.

**Comment by garrett** [comment]
Depends on https://github.com/cockpit-project/cockpit/pull/11155 landing. Please base the PR on https://github.com/cockpit-project/cockpit/pull/11155. :wink:

**Comment by garrett** [comment]
3. It'd be nice to have the divider between different types in the weekday dropdown. That is every day, divider, weekdays.

(This one is an opinion and optional, but I think it'd be nice.)

**Comment by martinpitt** [comment]
Let's use https://github.com/niksy/throttle-debounce for 2. Sanne is already experimenting with that for the file autocompletion widget.

**Comment by martinpitt** [comment]
Let's use https://github.com/niksy/throttle-debounce for 2. Sanne is already experimenting with that for the file autocompletion widget.

**Comment by martinpitt** [comment]
Fixed the debouncing in #11345.
