### ISSUE TITLE
systemd: Uncaught RangeError: Invalid time value

### ISSUE THREAD

**Issue by jsolla** [cockpit-project/cockpit#11315]
Cockpit version: 187 / Master
OS: Linux (Angstrom) 
Page: Any 

**Please note:** Cockpit has been installed in an embedded system that uses BusyBox v1.24.1.

An exception is raised periodically in the browser when systemd pkg (host.js) tries to get the date:
```
Uncaught RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at pe.e.format (host.js:112)
    at pe.<anonymous> (host.js:270)
    at pe.dispatch (jquery.js:5183)
    at pe.elemData.handle (jquery.js:4991)
    at Object.trigger (jquery.js:8249)
    at jQuery.fn.init.triggerHandler (jquery.js:8333)
    at Function.<anonymous> (host.js:147)
    at process_queue (cockpit.js:1296)
    at cockpit.js:1309
    at later_drain (cockpit.js:1188)
```

The cause of this exception has been debugged to the following lines at host.js:
```
    Object.defineProperty(self, 'utc_fake_now', {
        enumerable: true,
        get: function get() {
            var offset = time_offset + remote_offset;
            return new Date(offset + (new Date()).valueOf());
        }
    });

```
Turns out "remote_offset" is set to NaN and as a result Date() throws the mentioned exception.

Reason for remote_offset being set to NaN is the format used to query the date/time on the following line:
`return cockpit.spawn(["date", "+%s:%:z"], { err: "message" })`

Root cause of the problem is the format string cockpit passes to the date command wich is not supported by the date tool provided by BusyBox:
```
# date "+%s:%:z"
1551822242:%:z
```
Nevertheless this other format works:
```
# date "+%s:%z" 
1551822308:+0000
```

**Comment by KKoukiou** [comment]
@jsolla thanks a lot for debugging it. Since you reached to the cause would you like to send a PR or you 're rather that someone else does it?

**Comment by martinpitt** [comment]
I'm working on fixing this right now.
