### ISSUE TITLE
Update Cockpit to latest version

### ISSUE THREAD

**Issue by bramassendorp** [cockpit-project/cockpit#11338]
Hello,

I want to run the latest Cockpit version on my Rhel environment.

I have enabled the "rhel-7-server-extras-rpms" repository but it only has the "Package - cockpit-dashboard-176-4.el7.x86_64.rpm" package.

How can I install the latest version?

Thank you.

**Comment by martinpitt** [comment]
You can install the latest version from our COPR: https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/

But please keep in mind that this won't get official RHEL support then.
