### ISSUE TITLE
testSnapshots (check_storage_lvm2.TestStorage) is flaky

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#11352]
100% on verify/rhel-8-0
 - [pull-11143](http://fedorapeople.org/groups/cockpit/logs/pull-11143-20190209-201313-8ab07fc6-verify-rhel-8-0/log)
 - [pull-11109](http://fedorapeople.org/groups/cockpit/logs/pull-11109-20190212-131515-74e5d465-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190123-172323-60426039-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190123-172323-60426039-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190123-172323-60426039-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190122-131111-86c5e875-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190122-131111-86c5e875-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190122-131111-86c5e875-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190122-120101-2db5c4ff-verify-rhel-8-0/log)
 - [pull-11030](http://fedorapeople.org/groups/cockpit/logs/pull-11030-20190122-120101-2db5c4ff-verify-rhel-8-0/log)

<details><summary>Source material</summary>

```json
{
  "test": [
    [
      "testSnapshots (check_storage_lvm2.TestStorage)",
      12
    ]
  ],
  "status": [
    [
      "failure",
      12
    ]
  ],
  "tracker": [
    [
      null,
      12
    ]
  ],
  "context": [
    [
      "verify/rhel-8-0",
      12
    ]
  ],
  "merged": [
    [
      true,
      12
    ]
  ],
  "date": [
    "2019-01-22T11:01:39Z",
    "2019-01-23T17:43:56Z"
  ]
}
```
</details>

**Comment by martinpitt** [comment]
The old logs are gone, these automatic issues need to be refreshed if they should still stay useful.
