### ISSUE TITLE
Ubuntu Server 18.04.2 LTS favicon is a Debian logo

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11371]
Here's a screenshot of Cockpit after a fresh install on Ubuntu Server LTS and a system upgrade to the latest packages:

![Screenshot from 2019-03-12 10-07-48](https://user-images.githubusercontent.com/10246/54188003-18f22a00-44af-11e9-9e6f-977da54c5347.png)

Note the favicon. It's a Debian logo. It should probably be an Ubuntu logo instead.

**Comment by martinpitt** [comment]
Fixed a few days ago in #11357
