### ISSUE TITLE
Software Updates: When PackageKit isn't installed: "Checking for available updates failed: not-found" error in console

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11370]
Cockpit attempts to check PackageKit for software updates, even when PackageKit isn't installed.

It would be better to gracefully handle this situation instead of doing a `console.log` about "not-found" with no solution.

A middle of the road approach would be to at least mention how to solve the issue in the console.

**Comment by garrett** [comment]
Screenshot from Ubuntu Server 18.04.2 LTS:

![Screenshot from 2019-03-12 10-08-36](https://user-images.githubusercontent.com/10246/54187905-d2043480-44ae-11e9-8698-013b444cb0a4.png)


(BTW: The font CSP issue, also in the logs, is @ #11366)

**Comment by martinpitt** [comment]
This was fixed with PR #12620, the system page now doesn't do its own check any more, but relies on notifications.
