### ISSUE TITLE
machines: delete image dialog text overflows

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#11374]
Cockpit version: 183
OS: Fedora Server 29
Page: Machines

The text in the delete image dialog overflows if the text strings are very long.

Steps to reproduce
1. Create a VM with a very long name
2. Delete that VM

![Screenshot from 2019-03-12 10-47-02](https://user-images.githubusercontent.com/209895/54190554-57d6ae80-44b4-11e9-958a-c3473df5b690.png)

**Comment by bertoesloco** [comment]
How?

**Comment by andreasn** [comment]
setting break-word: break-all; in the css kind of fixes it it seems

**Comment by andreasn** [comment]
Looks a little so and so when I applied it to the td though.
![Screenshot from 2019-03-12 10-58-27](https://user-images.githubusercontent.com/209895/54191238-cff1a400-44b5-11e9-96ff-03af074f9f60.png)

**Comment by KKoukiou** [comment]
Maybe we would like to replace the table with unsorted list like @garrett did here https://garrett.github.io/cockpit-mockweb/forms/grid for bond settings.

**Comment by garrett** [comment]
Yeah, putting it in a list and using break-word are probably both good things to do here.

**Comment by garrett** [comment]
@andreasn: I played around with the HTML over at https://github.com/cockpit-project/cockpit/pull/11390 to better align the items and make it work on smaller widths.

After trying a few different methods to try to get things to align and stretch, I went with a pattern with the details under the label, and aligned everything appropriately.

![Screenshot_2019-03-14 grid inherit experiment 2](https://user-images.githubusercontent.com/10246/54351130-18909500-464f-11e9-8a86-2a219a4473d8.png)

Live demo @ https://codepen.io/garrett/pen/RdxLYa

**Comment by andreasn** [comment]
Looks good to me!
Does this make the dialog narrower than now?

**Comment by garrett** [comment]
>  Does this make the dialog narrower than now?

No, the narrowness is just some constraint I set in the demo to show what happens when there's wrapping. It would be as wide or as narrow as needed (filling the size given to it in the dialog).

**Comment by andreasn** [comment]
> No, the narrowness is just some constraint I set in the demo to show what happens when there's wrapping.

Ah, cool. Awesome work, thanks!
