### ISSUE TITLE
Hacky message when trying to shrink a 

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1140]
This is what I get when I try to shrink a Logical Volume:
"Error resizing logical volume: lvresize exited with non-zero exit status 5: WARNING: Reducing active logical volume to 1.95 GiB THIS MAY DESTROY YOUR DATA (filesystem etc.) Do you really want to reduce dockern? [y/n]: n Logical volume dockern NOT reduced"

**Comment by mvollmer** [comment]
Should be fixed now.
