### ISSUE TITLE
Upgrade Cockpit on CentOs 7 (for version 189)

### ISSUE THREAD

**Issue by 851d229** [cockpit-project/cockpit#11429]
Cockpit version: 176
OS:  Centos 7 kernel 3.10.0-957.10.1.el7.x86_64
Page: 

I don't see any way to upgrade from Cockpit 176 to 189.  I've tried "yum update cockpit" but it's says that 176 is the most recent version.    Is there a way to upgrade to 189 by yum ?    Also, I have download the tar package of 189 but I don't see instructions to install it....

I would recommend to add an "update" section on the Cockpit project documentation,

thank you !

Steps to reproduce

1.
2.
3.

**Comment by martinpitt** [comment]
CentOS 7 has Cockpit 176, that's just what it is. If you want to leave the supported set there and try the latest version, you are welcome to use the COPR: https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/
