### ISSUE TITLE
Cockpit does not honor password-change policies on the system

### ISSUE THREAD

**Issue by sgallagher** [cockpit-project/cockpit#1143]
Simple reproducer:

1) Log in as root
2) Try to change root's password to a single-character password.

It succeeds. Cockpit should be honoring the pam_pwquality (or pam_cracklib, whichever is set in the system-auth stack) requirements for passwords on the system.

**Comment by stefwalter** [comment]
We now change passwords using the standard tools. This should no longer be an issue.
