### ISSUE TITLE
Build on centos 7 fails

### ISSUE THREAD

**Issue by chipmap** [cockpit-project/cockpit#11451]
Cockpit version: cockpit-190
OS: CENTOS 7
Page: NA

Getting following errors while using: ./autogen.sh --prefix=/usr --enable-debug on git clone to master OR ./configure on cockpit-190
...
checking for LIBSYSTEMD... no
checking for LIBSYSTEMD... no
configure: error: Package requirements (libsystemd-journal >= 187 libsystemd-daemon libsystemd-login) were not met:

No package 'libsystemd-journal' found
No package 'libsystemd-daemon' found
No package 'libsystemd-login' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBSYSTEMD_CFLAGS
and LIBSYSTEMD_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Steps to reproduce

1.  Follow https://github.com/cockpit-project/cockpit/blob/master/HACKING.md on CENTOS 7

**Comment by martinpitt** [comment]
You are missing the build dependencies. For that, replace "dnf builddep" with "yum builddep" on CentOS 7.
