### ISSUE TITLE
docker: doesn't show ip/mac for non-default networks

### ISSUE THREAD

**Issue by jcpunk** [cockpit-project/cockpit#11470]
Cockpit version: cockpit-docker-190-1.fc29.x86_64
OS: Fedora 29
Page: Docker

When attaching containers to custom networks, the cockpit plugin doesn't list IP address or MAC address for the container.  These are listed when using the default bridge0

Steps to reproduce

1.
```
 docker network create --driver bridge  --subnet=172.28.0.0/16 --gateway=172.28.5.254 --opt 'com.docker.network.bridge.enable_icc=true'  --opt 'com.docker.network.bridge.enable_ip_masquerade=true'  --opt 'com.docker.network.bridge.host_binding_ipv4=0.0.0.0'   --opt 'com.docker.network.bridge.mtu=1500'   --opt 'com.docker.network.bridge.name=mynet-net0' mynet
```
2. 
```
docker run --rm --name testcontainer -it fedora /bin/bash
```

3. Navigate to the container in the cockpit UI and note the empty IP and MAC address

**Comment by marusak** [comment]
With Fedora/RHEL moving to podman, cockpit-docker has been in maintenance mode for quite some time. New development goes into cockpit-podman.
In cockpit-podman we don't show any network related information yet, but it is planned. I'll attach this issue to the tracker in podman to make sure that this works in podman.
