### ISSUE TITLE
Storage: Create bare encrypted file system

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#11482]
Page: Storage

There are use cases where one wants to create an encrypted partition without a file system. But our "create file system" dialog doesn't offer that, as it combines encryption with file system types. As a minimum, we should add "Encrypted Device (no file system)" to the options.

As these are independent concepts, gnome-disks separates these:

![customformat](https://user-images.githubusercontent.com/200109/55098051-641a5880-50bd-11e9-84e7-390af17ec6a1.png)

So maybe a more thorough fix is to do the same and subsume the LUKS options into a checkbox?

**Comment by andreasn** [comment]
What are the use cases when you want to do that?

**Comment by martinpitt** [comment]
I got this forwarded via email, it said "to layer LVM or VDO on LUKS I need to create a bare encrypted device to layer correctly". So an alternative UI might also be to add an [ ] encrypt checkbox to the creation of PVs or VDO volumes (but that might also not be obvious to admins who are used to build the layers one by one?)

**Comment by garrett** [comment]
I took a few screenshots from my personal laptop running Fedora 30 Beta with GNOME 3.22 (latest GNOME, in case the UI changed at all) to elaborate here, and show it in context:

![format-simple](https://user-images.githubusercontent.com/10246/55177177-e751b200-5182-11e9-876d-789675f37d7e.png)

![format-additional](https://user-images.githubusercontent.com/10246/55177230-07817100-5183-11e9-9eac-6d9d81e9683e.png)

![format-password](https://user-images.githubusercontent.com/10246/55177236-0b14f800-5183-11e9-9d46-98abb1989f14.png)

It's basically the same UI in the second photo, but the _default_ screen most people see has it added under EXT4. However, that's the only common encryptable filesystem listed on that page. As Cockpit has more than just EXT4, I agree with having it separate.

**Comment by mvollmer** [comment]
I'll make it a dropdown as there are multiple encryption technologies.

**Comment by mvollmer** [comment]
> However, that's the only common encryptable filesystem listed on that page.

Technically, all filesystem types can be encrypted since it is done as a separate layer.
