### ISSUE TITLE
Storage: "XFS - Red Hat Enterprise Linux 7 default" is a bit confusing

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#11481]
We currently statically label these file systems:

    add_fsys("xfs", { value: "xfs", title: _("XFS - Red Hat Enterprise Linux 7 default") });
    add_fsys("ext4", { value: "ext4", title: _("ext4 - Red Hat Enterprise Linux 6 default") });

This is a bit confusing on RHEL 8 (is it the default there?), and even more so on non-RHEL operating systems. Can we generalize these a bit, maybe "Recommended default" for xfs, and find something appropriate for ext4 as well? Can we summarize their strengths, maybe in terms of data reliability or if they are appropriate for very large devices or so?

**Comment by martinpitt** [comment]
A simple proposal would be "XFS - recommended default" and keep the ext4 description as-is.

**Comment by andreasn** [comment]
_XFS - recommended default_ sounds good to me.
