### ISSUE TITLE
Notify when the system goes down for reboot

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1153]
Usecase: Me and my friend Kalev administers a bunch of servers together. If I'm in the middle of something and Kalev decides to reboot the machine for some reason, it would be good to get a notification about this. A heads up. Related to issue #1134

**Comment by martinpitt** [comment]
Still valid. We need to find something subscribable similar to the `wall` message that a scheduled shutdown sends around, maybe systemd has something.

**Comment by marusak** [comment]
I believe this is duplicate of #2468 (I know, the other way around, but I decided to close this as the othe one has more discussion and some mockups)
