### ISSUE TITLE
Performance: HTTP/2

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11543]
Switching to HTTP/2 should drastically decrease page & asset load times.

> At a high level, HTTP/2:
>
> -    is binary, instead of textual
> -    is fully multiplexed, instead of ordered and blocking
> -    can therefore use one connection for parallelism
> -    uses header compression to reduce overhead
> -    allows servers to “push” responses proactively into client caches

— From [the official HTTP/2 FAQ](https://http2.github.io/faq/).

All of [our target browsers support HTTP/2](https://caniuse.com/#feat=http2).

The only downsides:
- Implementation work
- All browsers require HTTP/2 to be served over HTTPS. While we _want_ people to use HTTPS, there are some instances where it's useful to debug things over plain HTTP locally. That said, HTTP (without the S) should never be used in production. HTTP/2 is an upgrade using ALPN, just like TLS, so it should be able to fall back to non-TLS, HTTP/1.x anyway. So it shouldn't really be an issue.

**Comment by davidmalcolm** [comment]
Presumably you'd prefer to drastically **decrease** page & asset load times, right?

**Comment by garrett** [comment]
@davidmalcolm: Hahah, yeah. I didn't have enough coffee in the morning. :wink: Fixed! Thanks!

**Comment by martinpitt** [comment]
This is still relevant of course, and only going to get more relevant in the future. However, it is a *humongous* enterprise to do this. I'd love to replace much of our cockpit-ws custom implementation with a standard web server or library (can libsoup etc. help us here?), and only implement the websocket bits ourselves. I'm afraid we'll never get to this by way of "fixing a bug", we need a good reason for this (like, funding from a major customer feature request, and getting a new developer for this for half a year or so).

As such I don't think it makes much sense to just keep this around as an issue, so I close this now.
