### ISSUE TITLE
Instant Disconnect when using AD/LDAP Auth

### ISSUE THREAD

**Issue by thehallofshields** [cockpit-project/cockpit#11561]
I've installed cockpit on several CentOS 7 servers on my network. Regardless of server, browser, cert, user or selinux I get the same behavior.

* Linux Local users can login, maintain a session, and use all features.
* Active Directory users can login, but immediately get the following message:

```
Disconnected
Server has closed the connection.
[Reconnect]
```

AD auth is setup very simple using realm. I see the cockpit-project has documentation for SSO, but I'm just looking for basic delegated auth. Is this a buggy feature? Am I misunderstanding something? Is there a change I can try in /etc/pam.d/cockpit?

**Comment by martinpitt** [comment]
Indeed we only test realmd auth with FreeIPA, as we don't have a windows AD setup. Supposedly you can log in as AD users on a VT and in ssh? Can you please copy&paste the output of

    sudo journalctl -b  -u cockpit

after such a crash here? (We might need to increase the debug level, but let's try with that first)

**Comment by thehallofshields** [comment]
Thanks Martin. I have my organization using their AD accounts to SSH to all of our CentOS 7 machines (that were added with a simple `realm join example.com` command) and have zero issues.

Here is the output you requested:

> Apr 12 10:50:12 server.example.com systemd[1]: Starting Cockpit Web Service...
> Apr 12 10:50:12 server.example.com systemd[1]: Started Cockpit Web Service.
> Apr 12 10:50:12 server.example.com cockpit-ws[30188]: Using certificate: /etc/cockpit/ws-certs.d/_.example.com.cert
> Apr 12 10:50:22 server.example.com cockpit-session[30196]: pam_sss(cockpit:auth): authentication success; logname= uid=0 euid=0 tty= r
> Apr 12 10:50:22 server.example.com cockpit-session[30196]: pam_ssh_add: Failed adding some keys
> Apr 12 10:50:22 server.example.com cockpit-ws[30188]: logged in user session
> Apr 12 10:50:24 server.example.com cockpit-ws[30188]: New connection to session from 10.11.0.6
> Apr 12 10:50:26 server.example.com cockpit-ws[30188]: WebSocket from 10.11.0.6 for session closed

**Comment by thehallofshields** [comment]
> Apr 12 10:51:14 smrtcnms002 cockpit-ws[30188]: cockpit-session: session timed out during authentication
Apr 12 10:51:14 smrtcnms002 cockpit-ws[30188]: cockpit-session: didn't receive expected "authorize" message
Apr 12 10:51:14 smrtcnms002 cockpit-ws[30188]: cockpit-session: authentication timed out
Apr 12 10:51:14 smrtcnms002 cockpit-ws[30188]: ignoring failure from session process: Authentication failed: Timeout

This output showed up a minute later. It appears to be tied to the same login attempt.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.

**Comment by liwikruk** [comment]
I recently installed cockpit and i really dont know how connect ldap with cockpit. Can somebody help me?

**Comment by SirWobbyTheFirst** [comment]
Hi @marusak, @thehallofshields and @liwikruk,

I was able to resolve this issue by editing the sssd.conf file and adding enumerate = true to the section for my domain and have documented it in my own thread: #14385
