### ISSUE TITLE
Cockpit Authentication Automatic

### ISSUE THREAD

**Issue by viniciusnascimento91** [cockpit-project/cockpit#11589]
Page: 
Hello everyone, I am a beginner in the Cockpit, I need to monitor 100 servers, initially I installed the cockpit in my Raspbary PI with Debian, perfectly working. Every time I restart my Raspbary PI I need to reconnect to all servers. How do I always restart my LOCALHOST automatically connect to the secondary servers? I'm a beginner, the more information I get. Thank you

**Comment by martinpitt** [comment]
I'm afraid what you are trying to do is outside of what cockpit is meant to do. We don't support a mode where cockpit auto-logins to a user session on startup.

For constant monitoring of 100 servers you probably want to use something like nagios, Foreman/Satellite, or similar large-scale tools.
