### ISSUE TITLE
SELinux: Odd layout in mobile

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11602]
SELinux's solution layout is very odd in mobile:

![thumb0048](https://user-images.githubusercontent.com/10246/56124191-5fd3b380-5f76-11e9-87c5-42492edddca0.jpg)

It also has problems with the actions and tabs in the panel, but that should be handled in #11600.

**Comment by marusak** [comment]
Still happening. This should not be that hard to fix - we should just use something better than `float: right` for this button and then it should behave better on smaller screens.

**Comment by garrett** [comment]
Agreed. Floating, especially floating right, is very bad CSS for layout. It's only acceptable for floating an image right within the context of an article, not for web apps. It forces content to be re-ordered, does weird floating in cases like this (because this "weirdness" is actually the intended use), and needs to be contained with hacks.

This is exactly why there are things like flex and grid for this use case.

**Comment by garrett** [comment]
I can't really fix this; it's a problem with the JS and it's why I filed the bug in the first place. :wink:
