### ISSUE TITLE
Privileged access not working in tasks within Cockpit Web Console

### ISSUE THREAD

**Issue by donwlewis** [cockpit-project/cockpit#11623]
Cockpit version: 173.1
OS: RHEL 7.6
Page: Login

When using an Active Directory account through realmd, checking the `Reuse my password for privileged tasks` does not see to work.  The user has sudo access via configuration on the server, that is granting an AD group sudo access to the server.  This is via a nested group in AD.  Sudo access with password works fine in the terminal, but it doesn't seem to translate to operations within cockpits, such as restarting the server, or viewing logs and such.

Steps to reproduce

1.  Join system to AD via realmd
2.  Provide sudo access via AD group
3.  Add group to another group in AD to provide nested access

**Comment by donwlewis** [comment]
Here is some additional logs:

```
Apr 16 17:53:44 pkexec[50146]: lewisdx5: Error executing command as another user: Not authorized [USER=root] [TTY=unknown] [CWD=/run/user/1908602105] [COMMAND=/usr/bin/cockpit-bridge --privileged]
Apr 16 17:58:44 cockpit-session: pam_unix(cockpit:session): session closed for user lewisdx5
Apr 16 18:08:03 cockpit-session: pam_sss(cockpit:auth): authentication success; logname= uid=0 euid=0 tty= ruser= rhost=172.18.128.189 user=lewisdx5
Apr 16 18:08:04 cockpit-session: pam_unix(cockpit:session): session opened for user lewisdx5 by (uid=0)
Apr 16 18:08:08 polkitd[9320]: Operator of unix-session:7136 FAILED to authenticate to gain authorization for action org.freedesktop.policykit.exec for unix-process:59178:345603402 [cockpit-bridge] (owned by unix-user:lewisdx5)
Apr 16 18:08:08 pkexec[59193]: lewisdx5: Error executing command as another user: Not authorized [USER=root] [TTY=unknown] [CWD=/run/user/1908602105] [COMMAND=/usr/bin/cockpit-bridge --privileged]
Apr 16 18:09:08 polkitd[9320]: Operator of unix-session:7136 FAILED to authenticate to gain authorization for action org.freedesktop.packagekit.system-sources-refresh for system-bus-name::1.49211 [cockpit-bridge] (owned by unix-user:lewisdx5)
```

**Comment by donwlewis** [comment]
This can get closed.  I found the issue to be having the following option turned on in our SSH config:

`Defaults      !requiretty`

**Comment by martinpitt** [comment]
Thanks for figuring this out! I haven't seen this yet as a possible reason, so something learned. :-)

**Comment by donwlewis** [comment]
Sorry edited the comment.  The `requiretty` options was on not off.
