### ISSUE TITLE
"Create VM" dialog oopses with Fedora workstation iso

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#11628]
I was trying the new OS autodetection today. In "Installation Source" I selected `/home/martin/Downloads/fedora/Fedora-Workstation-Live-x86_64-28-1.1.iso`. Once I tabbed away, I got an oops:

```
TypeError: osEntry[0] is undefined machines.js:162284:19
  onOsAutodetect http://localhost:9090/cockpit/@localhost/machines/machines.js:162284
    process_queue http://localhost:9090/cockpit/@localhost/base1/cockpit.js:1296
    schedule_process_queue http://localhost:9090/cockpit/@localhost/base1/cockpit.js:1309
    later_drain http://localhost:9090/cockpit/@localhost/base1/cockpit.js:1188
```

osinfo seems to recognize it:

```
❱❱❱ osinfo-detect ~/Downloads/fedora/Fedora-Workstation-Live-x86_64-28-1.1.iso 
Media is bootable.
Media is an installer for OS 'Fedora 28 Workstation'
Media is live media for OS 'Fedora 28 Workstation'
```

**Comment by KKoukiou** [comment]
> I was trying the new OS autodetection today. In "Installation Source" I selected `/home/martin/Downloads/fedora/Fedora-Workstation-Live-x86_64-28-1.1.iso`. Once I tabbed away, I got an oops:
> 
> ```
> TypeError: osEntry[0] is undefined machines.js:162284:19
>   onOsAutodetect http://localhost:9090/cockpit/@localhost/machines/machines.js:162284
>     process_queue http://localhost:9090/cockpit/@localhost/base1/cockpit.js:1296
>     schedule_process_queue http://localhost:9090/cockpit/@localhost/base1/cockpit.js:1309
>     later_drain http://localhost:9090/cockpit/@localhost/base1/cockpit.js:1188
> ```
> 
> osinfo seems to recognize it:
> 
> ```
> ❱❱❱ osinfo-detect ~/Downloads/fedora/Fedora-Workstation-Live-x86_64-28-1.1.iso 
> Media is bootable.
> Media is an installer for OS 'Fedora 28 Workstation'
> Media is live media for OS 'Fedora 28 Workstation'
> ```

OH, that's horrible. Thanks for catching. It's because the osinfo-detect has these Server/Worktation variants but the query does not :/ I already communicated with the libosinfo devs for this incosistency.
