### ISSUE TITLE
logs: Content streaming in causes the page to lose its place

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11663]
While trying to view log entries, new items push the current row down. With more verbose filtering rules, it's impossible to skim through the logs as everything keeps shifting down.

Reproduce:
1. Set logs to current
2. Set verbosity to debug
3. Scroll down and look at messages

To cause items to scroll down faster, interact with your system a bit to trigger even more log messages.

**Comment by garrett** [comment]
Solution would probably be a concept similar to "Scroll Anchoring", which browsers have implemented. However, it doesn't seem to effect our log page, so we'd still need to implement something ourselves.

Before the list is refreshed, do something like:

1. Find scroll offset
2. Find page height
3. Update list
4. Find new page height
5. Use scrollTop to ((document_height - document_height_old) + old_scroll)

Hopefully this would be perceived as instant (without a flicker).

**Comment by marusak** [comment]
Hopefully this would be fixed if react would be used? :crossed_fingers:
Also #11664 should be react-fixable.

**Comment by garrett** [comment]
Yeah, I hope that porting to react would just fix this.

The back/forward in #11664 might not be fixed with just a port to React though, but this issue probably would.

**Comment by marusak** [comment]
Possibly fixed in https://github.com/cockpit-project/cockpit/pull/15005 but I am not super sure how to test this
