### ISSUE TITLE
logs: Formatting of detailed content is not preserved

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11665]
When viewing details of a log entry, some of the journalctl-provided information is not formatted whatsoever, causing the information within Cockpit to be a wall of text.

## Current screenshots

![Screenshot_2019-04-24 Logs - Sunny(1)](https://user-images.githubusercontent.com/10246/56675827-54dafa80-66bd-11e9-8c26-9a897d3e6480.png)

![Screenshot_2019-04-24 Logs - Sunny(2)](https://user-images.githubusercontent.com/10246/56675838-5c020880-66bd-11e9-89e8-1852677b0527.png)

## Proposed screenshots

- `white-space: pre-wrap` applied
- Fonts haven't been set to monospace, but it would certainly help for alignment in some of the content in the table — but it's already tons better with pre-wrap

![Screenshot_2019-04-24 Logs - Sunny(6)](https://user-images.githubusercontent.com/10246/56676069-ca46cb00-66bd-11e9-9fb5-0b5d68ecf499.png)

![Screenshot_2019-04-24 Logs - Sunny(3)](https://user-images.githubusercontent.com/10246/56675989-a5525800-66bd-11e9-86a7-694ee5d35cd4.png)

![Screenshot_2019-04-24 Logs - Sunny(4)](https://user-images.githubusercontent.com/10246/56675988-a5525800-66bd-11e9-832f-47c3bfe109a9.png)

![Screenshot_2019-04-24 Logs - Sunny(5)](https://user-images.githubusercontent.com/10246/56675987-a5525800-66bd-11e9-9ea3-484f0c9af9aa.png)

**Comment by garrett** [comment]
Here's a screenshot with a monospaced font applied. Unfortunately, the table is badly coded, so I couldn't easily just select the data in Firefox, therefore labels are also monospaced (and a proper fix would only apply a monospaced font for the data — and ideally only for the data where it matters).

![Screenshot_2019-04-24 Logs - Sunny(7)](https://user-images.githubusercontent.com/10246/56676358-6670d200-66be-11e9-9b21-b3bf31309e86.png)

**Comment by marusak** [comment]
@garrett good point.
We don't format anything, we just read it from journal and drop it into table. This works in general fine, but coredumps are usually badly formatted.
So you suggest applying `pre-wrap` and monospaced font on the data in table? That should be simple fix.

**Comment by garrett** [comment]
Much of the data expects to be seen in a preformatted view, so we should duplicate that.

How accessible is it? Not at all. We'd need to interpret the data and output actual tables to make it accessible.

But adding pre-wrap for formatting would at least improve things versus what we have right now.
