### ISSUE TITLE
Login to remote servers

### ISSUE THREAD

**Issue by Nekotje** [cockpit-project/cockpit#11686]
Cockpit version: 164
OS: Main- Ubuntu. remote= Centos and Debian.

When i add a remote server and fill in the login it works fine it connects to that server. 
then i logout of the local instance and log back in.

Now i see a Red sign that it cant login to the remote server and i have to fill in again the password.
and i have the problem with remote to centos and debian.

Im using a non standard SSH port which i fill in like host/ip:port and the first time it works.

the logs says failed password.

**Comment by bbichero** [comment]
Can you try to update your cockpit version ?
The newest version on debian is 188, It's should fix the issue.

**Comment by Nekotje** [comment]
when i do the apt install cockpit it says 
cockpit is already installed at the requested version (164-1)
it seems to work now. 

What i did was i logged in with the admin account on the external server via cockpit and then sync users to it makes the user and then filled in that user. That seems to work fine.

**Comment by vapouryh** [comment]
how to you login to cockpit remotely. I've tried the external ip (https://external_ip:9090) but doesn't work

**Comment by martinpitt** [comment]
@vapouryh : Maybe you need to open the port in the firewall? Hard to say with zero data.
