### ISSUE TITLE
How to Check Historic CPU usage

### ISSUE THREAD

**Issue by jainnitesh** [cockpit-project/cockpit#11684]
Hello Team,

How we can check the historical CPU memory and Disk usage for a server as  i checked this and did not found any solution for that.

I was able to see the real-time usage only.

**Comment by marusak** [comment]
On the `/system` page there is toggle switch `Store Metrics`. If this option is turned on, then history of CPU/storage/... is being stored and cockpit can show it. 
It is possible you can see there `Enable stored metrics…` which upon clicking take you through installation of necessary packages and then you should see `Store Metrics`

**Comment by jainnitesh** [comment]
I do not see any toggle switch as you can check my attached screenshot.

![image](https://user-images.githubusercontent.com/6376405/56847779-7e826480-68fd-11e9-8dfc-41064849fac3.png)

**Comment by jainnitesh** [comment]
Can you please send me a doc which I can use to install the required package to use the matrices.

as well as is there any way I can track users login time.

**Comment by marusak** [comment]
The package you want is `cockpit-pcp` which will pull all necessary dependencies. Also to be able to see `Enable stored metrics…` you would need to have `PackageKit` (or `cockpit-packagekit` to also be able to work with packagekit from Cockpit) and then Cockpit would allow you to install `cockpit-pcp`.

**Comment by marusak** [comment]
> as well as is there any way I can track users login time.

Not yet, see opened issue https://github.com/cockpit-project/cockpit/issues/28

**Comment by jainnitesh** [comment]
I installed it and enabled the performance data but did not able to see any option to watch the historical data

**Comment by jainnitesh** [comment]
One Strange issue, I have a server running with custom SSH port and I am adding that on the cockpit but i think this is not adding the port.

Also, let me know if i can add windows server as well.

**Comment by jainnitesh** [comment]
I am getting login failed while adding a server.

![image](https://user-images.githubusercontent.com/6376405/56848713-bdb6b280-6909-11e9-8d18-3a812aa7a05d.png)


i tried with ssh key as well as password.

Also, let me know if i can add windows server as well

**Comment by jainnitesh** [comment]
let me know if i can add windows server as well

also, let me know if it will detect all virtual machine from VirtualBox

**Comment by marusak** [comment]
> I installed it and enabled the performance data but did not able to see any option to watch the historical data

In the graphs on the right, historical data should be shown. If they do not appear, there may be some issue, firstly please check that `pmlogger` service is active. Other debugging steps can be found for example [here](https://access.redhat.com/articles/2450251)

> let me know if i can add windows server as well

No. Cockpit is supported for [following linux distributions](https://cockpit-project.org/running.html)

> also, let me know if it will detect all virtual machine from VirtualBox

Yes. For this you need `cockpit-machines` package.

Much more about what is and what is not supported in Cockpit you can find in [this documentation](https://cockpit-project.org/guide/latest/)

**Comment by jainnitesh** [comment]
I installed the cockpit-machines package on the host where we are running virtual box but this is not detecting all the virtual machines.
![image](https://user-images.githubusercontent.com/6376405/56878822-97ad2180-6a73-11e9-8040-78df9913e0f9.png)


If you will see the attached screenshot virtual machine is listed there but when clicking on the virtual machine  this is saying "No VM is running or defined on this host"

**Comment by KKoukiou** [comment]
> I installed the cockpit-machines package on the host where we are running virtual box but this is not detecting all the virtual machines.
> ![image](https://user-images.githubusercontent.com/6376405/56878822-97ad2180-6a73-11e9-8040-78df9913e0f9.png)
> 
> If you will see the attached screenshot virtual machine is listed there but when clicking on the virtual machine this is saying "No VM is running or defined on this host"

@jainnitesh please open a seperate issue for the cockpit-machines (Virtual Machines page) problem you have, since it's not related with the previous and it's polluting this issue, which has totally unrelated title. I will be happy yo help you solve your problem in the separate issue you will open.

**Comment by jainnitesh** [comment]
submitted new issue

**Comment by marusak** [comment]
Back to this issue, is the history working? Maybe you can look at https://github.com/cockpit-project/cockpit/issues/9604 if it is not the same issue?
