### ISSUE TITLE
services page doesn't work on Edge

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#11708]
Cockpit version: 192
OS: Windows 10
Page: Services

The Service list works as expected, but the service pages themselves don't render at all.

**Comment by KKoukiou** [comment]
![libvirtd-service](https://user-images.githubusercontent.com/14921356/57216110-2fb88700-6fef-11e9-955b-fca836eaa8aa.png)

And the services list page:
![services-page-edge](https://user-images.githubusercontent.com/14921356/57216112-33e4a480-6fef-11e9-9cea-9838dba04f9a.png)



@andreasn  I am testing against master and I don't seem any issue. Can you paste a screenshot of the problem you see?

**Comment by andreasn** [comment]
I've tested on a couple of different systems, and trying again, one particular Fedora 29 system had issues loading the pages consistently, but it did load them most of the time. I have a hard time reproducing it, so I think we can say it works in general.
