### ISSUE TITLE
Difficult to read test failures with unexpected messages

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#11726]
When a verify test fails (particularly with -tv), you end up with a whole lot of messages on the stderr, 99% of them completely unrelated to the root cause of the failure.  A trained eye can filter out the noise, but for the rest of us, it's difficult to figure out what actually caused the problem.

For the example of unknown journal messages, for example, you get output like this:

Journal extracted to TestConnection-testTls-fedora-29-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "/home/allison/code/cockpit/test/common/testlib.py", line 777, in tearDown
    self.check_journal_messages()
  File "/home/allison/code/cockpit/test/common/testlib.py", line 959, in check_journal_messages
    raise Error(first)
testlib.Error: couldn't read from connection: Peer sent fatal TLS alert: Unknown certificate

which mentions nothing about the fact that it's from an unexpected journal message.

I think we should try to always have a very clear indication of the root cause of the error, with good explanation, at the end of the output.

**Comment by allisonkarlitskaya** [comment]
This is something along the lines of what I'm thinking about.  It's pretty extreme, but I think that's good:

testlib.Error: 
================================================
The test ran to completion, but the systemd journal on the test container
contained an unexpected message:

  couldn't read from connection: Peer sent fatal TLS alert: Unknown certificate

See the messages above for more information.
================================================

**Comment by martinpitt** [comment]
It actually does say that a little further up:
```
# ----------------------------------------------------------------------
# testUnitLifecycle (__main__.TestConnection)
#
Unexpected journal messages:
Process 2709 (cockpit-tls) of user 978 dumped core.
[...]
testlib.Error: Process 2709 (cockpit-tls) of user 978 dumped core.
```

But indeed this could be a little clearer.  A lot of our naughty patterns match on the last line, so it remains to be seen how much a change here affects these. I'll send a PR and find out.

I changed it like this:
```
Traceback (most recent call last):
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 793, in tearDown
    self.check_journal_messages()
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 970, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 5323 (cockpit-tls) of user 978 dumped core.

not ok 1 testUnitLifecycle (__main__.TestConnection) # duration: 23s
```
