### ISSUE TITLE
examples/ocserv no longer work with cockpit 191

### ISSUE THREAD

**Issue by sergiomb2** [cockpit-project/cockpit#11721]
Cockpit version: 191
OS: centos 7
Page: ocserv

I built cockpit 191 [1]  with src.rpm from fedora [2] copied example/ocserv , and the page becomes totally blank 

[1] https://copr.fedorainfracloud.org/coprs/sergiomb/builds_for_Stable_Releases/package/cockpit/
https://copr.fedorainfracloud.org/coprs/sergiomb/builds_for_Stable_Releases/package/cockpit/

[2] https://kojipkgs.fedoraproject.org//packages/cockpit/191/1.fc30/src/cockpit-191-1.fc30.src.rpm 

Steps to reproduce

1. run ocserv 
2. copy example/ocserv to main dir 
3. verify that page openconnect ocserver show some results in cockpit 
4. update cockpit to 191 with copr repo previous mention 
5. verify that page openconnect ocserver is completely blank 

Now I'm going to test  with 192

**Comment by martinpitt** [comment]
With a completely blank page there should be some error message in the JS console (Ctrl+Alt+J) and also often an error message in `journalctl -u cockpit`. Can you please check for this?

I'm afraid nobody in our team has any experience with openconnect. Is there some container/VM setup to reproduce this? I. e. some detailed reproducing steps that doesn't involve "install these 100 things on your production laptop"?

**Comment by sergiomb2** [comment]
Hi,
After install cockpit on Fedora 30 I saw that we don't have the examples directory ,  we need  clone cockpit from git  and copy example/ocserv to /usr/share/cockpit [1] and after logout and login you will see the error [2]. No need have ocserv running  , doesn't matter the error is the same 


[1]
git clone https://github.com/cockpit-project/cockpit.git 
su -
cd /usr/share/cockpit/
cp -r ~user/cockpit/examples/ocserv/ .
systemctl restart cockpit

[2] start blinking and red "oops" 

Unexpected error

Cockpit had an unexpected internal error.

You can try restarting Cockpit by pressing refresh in your browser. The javascript console contains details about this error (Ctrl-Shift-J in most browsers).

**Comment by marusak** [comment]
Indeed, It says that `require` is not defined and it means [this](https://github.com/cockpit-project/cockpit/blob/master/examples/ocserv/ocserv.html#L73).
I don't know this syntax, @martinpitt do you know how this should work?

**Comment by marusak** [comment]
Ok, I was schooled by @ondrejbudAI that this is from `requireJS` which we dropped [here](https://github.com/cockpit-project/cockpit/commit/ff5149ec5e97f825ff6e5f2704cbb3f9f1ecd3c0) and [here](https://github.com/cockpit-project/cockpit/commit/54b04ed814ddf1e11fed3d82961e90febbd8b8c2). We need to update it something different.

**Comment by marusak** [comment]
@sergiomb2 I sent https://github.com/cockpit-project/cockpit/pull/13108 which should fix it. Are you able to test if that works for you?

**Comment by sergiomb2** [comment]
yes it works thank you

**Comment by 6guysinasuite** [comment]
this is a terrific tool. thank you!!!
**question** - i was able to get the view working for me **but i was wondering if there is a way to get more information than that?**

for example, i will like to see the following information as well...

- Protocol/Tunnel type;
- duration of connection, 
- total data transfer in; 
- total data transfer out; 
- failed logins/attempts logging.

is there a way to modify the html file and see those information as well?
thank you again for your time and hard work.

**Comment by marusak** [comment]
> but i was wondering if there is a way to get more information than that?

You mean from `ocserv`? If so, then I guess. This is however just simple example and we don't work on it. It is fairly straight forward and simple to create own cockpit plugin using https://github.com/cockpit-project/starter-kit/ . Or of course you can just enhance the demo for your specific needs.

**Comment by 6guysinasuite** [comment]
Yes - for ocserv.
Thanks for responding -  I will take a look at the starter plugin and try
to create something or ask the ocserv developers if they already have
something in-house for cockpit. Thanks again for your help.
