### ISSUE TITLE
Broken default firewalld configuration on debian images

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#11748]
Cockpit version: 193
OS: debian-stable (Debian 9)

Default firewalld configuration disappears after restarting firewalld. In the permanent configuration, there's no interface attached to the default zone, resulting in the default zone config being broken after restarting the firewall.

**Comment by Gundersanne** [comment]
This also presents itself on `debian-testing` (buster/sid), after disabling and enabling the firewalld service.

Simply `systemctl disable --now firewalld && systemctl enable --now firewalld` until `firewall-cmd --get-active-zones` returns nothing.

**Comment by martinpitt** [comment]
Fixed by obsolescence, PR #12248

**Comment by martinpitt** [comment]
Actually not, the "new" debian-stable image still behaves differently, even though the debs are now exactly the same as debian-testing. I don't immediately know why that is.

With the debian-stable Debian 10 image, `firewall-cmd --get-active-zones` is empy even after the `firewall-cmd --permanent --zone=public --add-interface=eth1` dance.
