### ISSUE TITLE
High cockpit-ssh CPU use & context switches

### ISSUE THREAD

**Issue by rburchell** [cockpit-project/cockpit#11747]
Cockpit version: 192
OS: Fedora 29 & 30
Page: n/a

cockpit-ssh processes are using lots of CPU for each host while logged into the web UI.

Preconditions: have a cockpit setup with a few (in my case 5-6 different hosts, most of which are virtual machines)

* Start a process manager (e.g. htop) before login
* Note that the system is fairly quiet
* Log into the cockpit web UI
* Check the process manager again, note that cockpit-ssh processes are taking 1-2% CPU use per host (and draining battery fairly hard due to regular wakeups, which is a problem on a laptop).

I understand that it's not possible to get any functionality for _free_, but this seems a little on the heavy side, and prevents me from leaving cockpit logged in for anything more than a minute or two at a time.

Looking at:

```
sudo perf sched record -- sleep 4
sudo perf sched latency -s switch
```

Shows cockpit-ssh as having >18k switches. The next highest thing on my system right now is Xorg with 1003 switches.

**Comment by martinpitt** [comment]
I think the way how to mitigate that is to simply do less per remote host. In particular, I think the automatic CPU/memory graph collection from remote hosts was a cute demo, but it's really expensive and we shouldn't do it by default. This will probably account for most of the wakeups.

**Comment by rburchell** [comment]
That seems sensible, however -- excuse me if I'm saying stupid things, I have no idea about the implementation details -- it strikes me as a little strange that it's *that* expensive though? Or is it repeated very frequently?

As a good comparison, virt-manager does more or less the same sort of polling (albeit per virtual machine, not per host) at I think a three second interval by default, and that is more or less unnoticable even with 20-30 VMs being polled on a remote host.

**Comment by martinpitt** [comment]
This should be mitigated a lot by the Dashboard removal, plus not auto-connecting to remote machines by default any more. Beyond that, cockpit's pages just do a lot of D-Bus and file watching etc. to make sure the pages are always up to date. That's just what cockpit is all about, and we don't want to take this away. So I am closing this now.
