### ISSUE TITLE
storage: custom filesystem input is too far away from it's parent

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#11752]
Cockpit version: 192
OS: Fedora
Page: Storage

If I select _Custom (Enter filesystem type)_ in the format dialog, the input for the filesystem ends up too far away from the input that triggers it. The Name input ends up between them.

Steps to reproduce

1. Go to _Storage_
2. Select a disk
3. Press _Format_
4. Under Type, select _Custom (Enter filesystem type)_

![Screenshot from 2019-05-06 14-09-59](https://user-images.githubusercontent.com/209895/57224319-600d1f00-7009-11e9-9689-362926c059e9.png)

**Comment by KKoukiou** [comment]
That was fixed long time now with:

```bash
commit 452ed12972065d012d88cf5bdcf5a678af9957f1
Author: Marius Vollmer <mvollmer@redhat.com>
Date:   Wed May 8 17:24:03 2019 +0300

    storage: Remove "custom" filesystem type
```
