### ISSUE TITLE
Can't list LVM volumes groups on debian 9

### ISSUE THREAD

**Issue by bbichero** [cockpit-project/cockpit#11763]
Cockpit version: 193-1
OS: Debian 9.9
Page: Storage

On Centos 7.6 I was able to list volumes groups, create logicals volumes ... but not in debian stretch.
Am I missing something ? I have installed all the cockpit package available, I also have installed cockpit + cockpit storaged in experimental state (stretch backport was 188)
I have udisk2 installed along with all needed dependencies.

**Comment by KKoukiou** [comment]
@bbichero I think you need https://packages.debian.org/buster/udisks2-lvm2 for using LVM functionality and it's not available on debian stretch.
@mvollmer can you please confirm?

**Comment by bbichero** [comment]
You were right @KKoukiou, After upgrading to Debian Buster, I was able to install Udisk2-lvm2 and use it for managing volume in Cockpit.
