### ISSUE TITLE
Docker: web console (overwriting output after restart of docker)

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#1176]
Hi,
there is trouble, that web console for docker after restart have strange behaviour.
text on console after docker restart is not cleard or console pointer should be at next line.
here is copied example output from:
https://192.168.122.108:9090/#dashboard&server?machine=localhost&containers&image-details?id=88b42ffd1f7cc87c46edf70924b3e24f18da0eb69337deff4db2979d6e1032d8&container-details?id=e68dda67f7a257e933eeb539f26baacbfd571b4f0dc1887eeffa0548e0e11e86

bash-4.2# ls                                                                    
bin  etc   lib    lost+found  mnt  proc  run   srv  tmp  var                    
dev  home  lib64  media       opt  root  sbin  sys  usr                         
bash-4.2# bash-4.2# bash-4.2# bash-4.2# bash-4.2# ls                            
bin  etc   lib    lost+found  mnt  proc  run   srv  tmp  var                    
dev  home  lib64  media       opt  root  sbin  sys  usr                         
xash-4.2# disconnected                                                          
bash: x: command not found                                                      
bash-4.2#

**Comment by stefwalter** [comment]
Is this still an issue?

**Comment by jscotka** [comment]
I've didn't met this issue. It is probably somehow repaired. This issue could be closed
