### ISSUE TITLE
selenium-storage.py:StorageTestSuite.test10Storage is flaky

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#11802]
80% on selenium/firefox
 - [pull-11199](http://fedorapeople.org/groups/cockpit/logs/pull-11199-20190219-090404-10faf9b8-selenium-firefox/log)
 - [pull-11199](http://fedorapeople.org/groups/cockpit/logs/pull-11199-20190219-083535-57a865d5-selenium-firefox/log)
 - [pull-11199](http://fedorapeople.org/groups/cockpit/logs/pull-11199-20190219-070000-fb12b469-selenium-firefox/log)
 - [pull-11035](http://fedorapeople.org/groups/cockpit/logs/pull-11035-20190212-090303-ce8c64a6-selenium-firefox/log)
 - [pull-11035](http://fedorapeople.org/groups/cockpit/logs/pull-11035-20190212-082121-7e56a116-selenium-firefox/log)
 - [pull-11035](http://fedorapeople.org/groups/cockpit/logs/pull-11035-20190211-164949-63ab1a4a-selenium-firefox/log)
 - [pull-11035](http://fedorapeople.org/groups/cockpit/logs/pull-11035-20190211-140000-715ffd46-selenium-firefox/log)
 - [pull-11035](http://fedorapeople.org/groups/cockpit/logs/pull-11035-20190211-130101-d19b42c4-selenium-firefox/log)
 - [pull-11035](http://fedorapeople.org/groups/cockpit/logs/pull-11035-20190207-121414-12530444-selenium-firefox/log)
 - [pull-11035](http://fedorapeople.org/groups/cockpit/logs/pull-11035-20190206-094444-25ce0a2a-selenium-firefox/log)

65% on selenium/edge
 - [pull-11419](https://209.132.184.41:8493/logs/pull-11419-20190320-200404-be796c55-selenium-edge/log)
 - [pull-11419](https://209.132.184.41:8493/logs/pull-11419-20190320-165353-2a9585b8-selenium-edge/log)
 - [pull-11084](https://209.132.184.41:8493/logs/pull-11084-20190321-162323-8c65c6f8-selenium-edge/log)
 - [pull-11318](http://fedorapeople.org/groups/cockpit/logs/pull-11318-20190306-131313-41f9cbc7-selenium-edge/log)
 - [pull-11272](http://fedorapeople.org/groups/cockpit/logs/pull-11272-20190301-152626-d2671667-selenium-edge/log)
 - [pull-11206](http://fedorapeople.org/groups/cockpit/logs/pull-11206-20190226-135252-39df5ac2-selenium-edge/log)
 - [pull-11206](http://fedorapeople.org/groups/cockpit/logs/pull-11206-20190221-115757-c4d6e707-selenium-edge/log)
 - [pull-11200](http://fedorapeople.org/groups/cockpit/logs/pull-11200-20190218-210808-773a4a0f-selenium-edge/log)
 - [pull-11200](http://fedorapeople.org/groups/cockpit/logs/pull-11200-20190218-210202-24f5c66e-selenium-edge/log)
 - [pull-11199](http://fedorapeople.org/groups/cockpit/logs/pull-11199-20190219-090404-10faf9b8-selenium-edge/log)

87% on selenium/chrome
 - [pull-11199](http://fedorapeople.org/groups/cockpit/logs/pull-11199-20190219-090404-10faf9b8-selenium-chrome/log)
 - [pull-11199](http://fedorapeople.org/groups/cockpit/logs/pull-11199-20190219-083535-57a865d5-selenium-chrome/log)
 - [pull-11199](http://fedorapeople.org/groups/cockpit/logs/pull-11199-20190218-215252-fb12b469-selenium-chrome/log)
 - [pull-11035](http://fedorapeople.org/groups/cockpit/logs/pull-11035-20190212-083636-ce8c64a6-selenium-chrome/log)
 - [pull-11035](http://fedorapeople.org/groups/cockpit/logs/pull-11035-20190212-082222-7e56a116-selenium-chrome/log)
 - [pull-11035](http://fedorapeople.org/groups/cockpit/logs/pull-11035-20190211-165858-63ab1a4a-selenium-chrome/log)
 - [pull-11035](http://fedorapeople.org/groups/cockpit/logs/pull-11035-20190211-135656-715ffd46-selenium-chrome/log)
 - [pull-11035](http://fedorapeople.org/groups/cockpit/logs/pull-11035-20190211-125353-d19b42c4-selenium-chrome/log)
 - [pull-11035](http://fedorapeople.org/groups/cockpit/logs/pull-11035-20190207-121010-12530444-selenium-chrome/log)
 - [pull-11035](http://fedorapeople.org/groups/cockpit/logs/pull-11035-20190206-094343-25ce0a2a-selenium-chrome/log)

<details><summary>Source material</summary>

```json
{
  "test": [
    [
      "selenium-storage.py:StorageTestSuite.test10Storage",
      26
    ]
  ],
  "status": [
    [
      "failure",
      26
    ]
  ],
  "tracker": [
    [
      null,
      26
    ]
  ],
  "context": [
    [
      "selenium/firefox",
      26
    ]
  ],
  "merged": [
    [
      true,
      21
    ],
    [
      false,
      5
    ]
  ],
  "date": [
    "2018-12-03T12:28:58Z",
    "2019-02-19T09:20:09Z"
  ]
}
{
  "test": [
    [
      "selenium-storage.py:StorageTestSuite.test10Storage",
      47
    ]
  ],
  "status": [
    [
      "failure",
      47
    ]
  ],
  "tracker": [
    [
      null,
      47
    ]
  ],
  "context": [
    [
      "selenium/edge",
      47
    ]
  ],
  "merged": [
    [
      true,
      31
    ],
    [
      false,
      12
    ],
    [
      null,
      4
    ]
  ],
  "date": [
    "2018-11-30T16:18:43Z",
    "2019-03-21T17:15:57Z"
  ]
}
{
  "test": [
    [
      "selenium-storage.py:StorageTestSuite.test10Storage",
      24
    ]
  ],
  "status": [
    [
      "failure",
      24
    ]
  ],
  "tracker": [
    [
      null,
      24
    ]
  ],
  "context": [
    [
      "selenium/chrome",
      24
    ]
  ],
  "merged": [
    [
      true,
      21
    ],
    [
      false,
      3
    ]
  ],
  "date": [
    "2019-01-22T21:38:40Z",
    "2019-02-19T09:17:11Z"
  ]
}
```
</details>

**Comment by martinpitt** [comment]
The old logs are gone, these automatic issues need to be refreshed if they should still stay useful.
