### ISSUE TITLE
fails to start on corrupted certificate

### ISSUE THREAD

**Issue by eohlde** [cockpit-project/cockpit#11803]
Cockpit version: the latest from the repo (I'm not sure?)
OS: Ubuntu Server 19.04
Page: 

Steps to reproduce

1. sudo apt-get install cockpit
2. cannot navigate to localhost:9090
3. sudo service cockpit status:
![2019-05-12_14h18_10](https://user-images.githubusercontent.com/40407768/57586217-c9d17100-74c0-11e9-9cc5-ec231d776db3.png)

**Comment by martinpitt** [comment]
It seems /etc/cockpit/ws-certs.d/0-self-signed.cert is somehow mis-created. Did you replace it by any chance? Can you please do

    sudo cat /etc/cockpit/ws-certs.d/0-self-signed.cert > /tmp/0-self-signed.cert

and attach /tmp/0-self-signed.cert here? After that, please try

    sudo rm /etc/cockpit/ws-certs.d/0-self-signed.cert
    sudo remotectl certificate --ensure --user=root --group=cockpit-ws

and check if that causes any errors? Please copy&paste the entire output here.

(Explanation: The first command copies the cert+key into a file that your user can read, for  easier attaching. The second regenerates it).

**Comment by eohlde** [comment]
Hi Martin,

Thank you for the feedback. I only tried installing cockpit on my new linux headless server. It was very strange. I have it on another machine and the apt-get worked flawlessly.

the cat command failed:
![2019-05-12_21h34_39](https://user-images.githubusercontent.com/40407768/57591120-cf997780-74fd-11e9-917f-e902e23f47c2.png)

However the re-creation of the key worked just fine.

**Comment by martinpitt** [comment]
This is a strange error -- Supposedly it's not about your user being unable to write into /tmp/ (as you would hardly get anywhere then), but that /tmp/0-self-signed.cert already exists from another user. Can you please attach it, to see what got damaged in there?

**Comment by eohlde** [comment]
Attached.
[0-self-signed.zip](https://github.com/cockpit-project/cockpit/files/3174438/0-self-signed.zip)

**Comment by martinpitt** [comment]
Indeed, the 0-self-signed.cert there is full of zeros. That and the weird access error both start to smell like some hard disk corruption (or possibly memory). It may not be a bad idea to run a memory check (from the Grub boot menu) *first*, and *then* a disk check from the rescue boot entry.

At this point I don't have other ideas how to retroactively debug this, I'm afraid.

**Comment by martinpitt** [comment]
There's nothing that we can do on our side without further information, I'm afraid.
