### ISSUE TITLE
Link "Enable persistent metrics…" option not available

### ISSUE THREAD

**Issue by JeanReneRobin** [cockpit-project/cockpit#11806]
Cockpit version: 193
OS: Ubuntu 18.04
Page: System 

I want to enable persistent metrics. I read the page https://cockpit-project.org/blog/cockpit-172.html which shows  the "Enable persistent metrics…" link. This link does not appear on my UI. Is  there something that must be done before ?

**Comment by martinpitt** [comment]
Most probably you don't have the `packagekit` package installed. The "cockpit" package recommends cockpit-packagekit, which depends on packagekit. So you either removed that, or installed only a minimal  cockpit-system without the "cockpit" metapackage?

**Comment by JeanReneRobin** [comment]
I only run the `sudo apt-get install cockpit` command. The two packages are installed : 

    $ sudo apt install cockpit-packagekit packagekit
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    cockpit-packagekit is already the newest version (164-1).
    packagekit is already the newest version (1.1.9-1ubuntu2.18.04.5).
    The following package was automatically installed and is no longer required:
    grub-pc-bin
    Use 'sudo apt autoremove' to remove it.
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

But now, I see in command line that the version is 193 : 

    $ sudo apt upgrade cockpit
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    cockpit is already the newest version (193-1~ubuntu18.04.1).
    Calculating upgrade... Done
    The following package was automatically installed and is no longer required:
    grub-pc-bin
    Use 'sudo apt autoremove' to remove it.
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

... but in the UI, the 'About' section says "Version 164." It may be link to my problem.

**Comment by martinpitt** [comment]
Can you please check with `dpkg -l | grep cockpit` and give the output of `cockpit-bridge --packages`?

**Comment by JeanReneRobin** [comment]
Here is the output of the two commands :
    jean-rene@vps:~$ dpkg -l | grep cockpit
    ii  cockpit                           193-1~ubuntu18.04.1                         all          Web Console for Linux servers
    ii  cockpit-bridge                    164-1                                       amd64        Cockpit bridge server-side component
    ii  cockpit-dashboard                 164-1                                       amd64        Cockpit remote servers and dashboard
    ii  cockpit-networkmanager            164-1                                       all          Cockpit user interface for networking
    ii  cockpit-packagekit                164-1                                       all          Cockpit user interface for packages
    ii  cockpit-storaged                  164-1                                       all          Cockpit user interface for storage
    ii  cockpit-system                    164-1                                       all          Cockpit admin interface for a system
    ii  cockpit-ws                        164-1                                       amd64        Cockpit Web Service

    jean-rene@vps:~$ cockpit-bridge --packages
    apps: /usr/share/cockpit/apps
    base1: /usr/share/cockpit/base1
    dashboard: /usr/share/cockpit/dashboard
    domain: /usr/share/cockpit/realmd
    network: /usr/share/cockpit/networkmanager
    performance: /usr/share/cockpit/tuned
    shell: /usr/share/cockpit/shell
    ssh: /usr/share/cockpit/ssh
    storage: /usr/share/cockpit/storaged
    system: /usr/share/cockpit/systemd
    updates: /usr/share/cockpit/packagekit
    users: /usr/share/cockpit/users
    checksum = c397aec3ff545e19571c89c1d5d014119f34ce74

**Comment by martinpitt** [comment]
Right, that explains it. Please upgrade your system to current  cockpit packages, as this old version 164 doesn't yet have the "Enable ..." feature.

**Comment by JeanReneRobin** [comment]
Thanks ! Indeed my system could not update in 193 (i still don't know why), even if it displayed the packet when I used the command

    apt-cache policy cockpit

To whom it may help : The solution was to force all packages to update in 193 (it has to be done to 8 packets) : 

    apt install cockpit-system=193-1~ubuntu18.04.1
    apt install cockpit-bridge=193-1~ubuntu18.04.1
    ...

And then restart 

    service cockpit restart

And it works! 🎊
