### ISSUE TITLE
Not obvious how to access error when "oops" occurs

### ISSUE THREAD

**Issue by jgiardino** [cockpit-project/cockpit#11817]
During one of the labs at summit, one of the lab instructors noticed a participant had encountered an "oops", but neither the instructor or participant knew how to access the error. The instructor noted that "oops" might not be the best label for this feature, and that it wasn't obvious that you could interact with the "oops" to get more information.

**Comment by martinpitt** [comment]
We could at least add a tooltip that points out the JavaScript console (Ctrl+Alt+J in Firefox, need to check other browsers)? There's not that much more that we can do, as the page itself can't open the console, and we can't rely much on our code after a crash anyway.

Possibly we could also replace the "Oops" with some appropriate error icon.

**Comment by martinpitt** [comment]
In recent versions, when you get an Oops and click on it, you get this:

![oops](https://user-images.githubusercontent.com/200109/67189838-3d23cb00-f3ef-11e9-99f6-ea73cec45905.png)

Which should be enough to access the error.
