### ISSUE TITLE
Switch isn't clickable where expected

### ISSUE THREAD

**Issue by jgiardino** [cockpit-project/cockpit#11814]
Cockpit version: 180
OS: RHEL8
Page: System

During a RHEL8 training lab using Web Console, a participant noted that he expected to be able to click on the part of the "Store Performance Data" switch that was labeled with "OFF".

![image](https://user-images.githubusercontent.com/21063328/57633263-4b80d780-7571-11e9-8003-18502b1fc13f.png)

Steps to reproduce

1. Log in and navigate to the System page
2. If the link "Enable persistent metrics..." displays, then click that to install cockpit-pcp
3. Click the "OFF" text that displays for the "Store Performance Data" switch

Current result: nothing happens
Expected result: this action should toggle the state to "ON"

NOTE: This issue might exist in other places where the switch is used. The fix for this issue should address all similar occurrences of this.

**Comment by garrett** [comment]
@jgiardino: Thanks for reporting this issue.

It's is being addressed in https://github.com/cockpit-project/cockpit/pull/11769 (alongside many other switch issues).

**Comment by mvollmer** [comment]
Clicking on "Off" works, but you really have to click on the text.  If you click inside the borders of the button but outside of the text, the click will be ignored.
