### ISSUE TITLE
Respect ssh ConnectTimeout setting in cockpit-ssh

### ISSUE THREAD

**Issue by blaskovic** [cockpit-project/cockpit#1182]
Please add configurable timeout for adding another server.

Now if I want to add another server, timeout is too short and it looks like it failed but in a fact just the connection takes longer time.

Please make this timeout configurable or make it longer at least.

**Comment by martinpitt** [comment]
Indeed our cockpit-ssh is now supposed to respect the `ssh_config` settings via libssh. If `ConnectTimeout` is not respected, we should file an issue against libssh, and verify that we don't have a hardcoded timeout in cockpit-ssh.

**Comment by Gundersanne** [comment]
@martinpitt I just verified that ConnectTimeout is respected.

Recently (cockpit-183 or older should work) `cockpit-ssh` got a bit of a rework and should now respect ssh configs. If you still have issues after updating, don't hesitate to reopen.
