### ISSUE TITLE
Is It possible to update header and footer?

### ISSUE THREAD

**Issue by trayan16** [cockpit-project/cockpit#11866]
I want to modify the html of header, footer and login page of the cockpit. Which files should I modify in order not to break things up after new version of cockpit is released?

**Comment by martinpitt** [comment]
What precisely do you mean? There is no "footer". You can customize the header bar in /usr/share/cockpit/branding/, but that's a bit difficult to do without either rebuilding cockpit or avoiding to change package-shipped files. You could copy and adjust an existing branding and then change your /etc/os-release's `ID=` field to point to that. If you are on a Debian-based system, you can also persistently and safely change .deb-provided files with [dpkg-divert](https://debian-administration.org/article/118/Replacing_binaries_with_dpkg-divert).

**Comment by trayan16** [comment]
Thank you, @martinpitt . What about the login page? Is it configurable? I try to edit login.html, but changes are not shown on the FE side.

**Comment by martinpitt** [comment]
Cockpit ships the login page in a minified version, editing that is no joy. You are better off with customizing it in the source code and rebuilding.

**Comment by trayan16** [comment]
I think, we've tried that by editing the login.html file and then run "make" . But our changes are not taking in charge.

**Comment by marusak** [comment]
@trayan16 is this still issue? What do you do after you run `make`?

**Comment by KKoukiou** [comment]
Modifying and building from sources is the only way to fix your issue @trayan16. If you can't do that please step by from `#cockpit` channel on `freenode` on IRC and we will be happy to help you.

I will close this issue because of inactivity and also GitHub issues are not the best place to give guidance on hacking on the project.
