### ISSUE TITLE
/bin/bash: eslint: command not found

### ISSUE THREAD

**Issue by AdamKearn** [cockpit-project/cockpit#11861]
Cockpit version: TOT
OS: Ubuntu 19.04

Hello, I am getting this error when trying to compile the source.
Any idea how to fix this?

Thanks for your help.
-Adam
```
Now type 'make' to compile Cockpit.
dev@ubuntu:~/cockpit$ make
make  all-am
make[1]: Entering directory '/home/dev/cockpit'
  CHECK    dist/base1/test-dbus-common.js
/bin/bash: eslint: command not found
make[1]: *** [Makefile:9842: dist/base1/test-dbus-common.js] Error 127
make[1]: Leaving directory '/home/dev/cockpit'
make: *** [Makefile:3167: all] Error 2
dev@ubuntu:~/cockpit$ 
```

**Comment by martinpitt** [comment]
You apparently have a tree where autogen.sh failed to run; possibly due to your earlier lack of all build dependencies (like npm)?. This runs `npm install`, which includes eslint. I suggest to clean your tree (`git clean -fdx`) and start over with ./autogen.sh.

**Comment by AdamKearn** [comment]
That looks like it fixed.  Everything compiled with 0 errors.
Thanks!!!


But my edits are not showing after recompiling...
I have run the following commands.

```
sudo apt-get install cockpit
cd cockpit
make
<made edits to `/cockpit/dist/static/login.css`>
make
```
but when I went to `localhost:9090` my changes are not there???
Am I missing anything?

Thanks
-Adam

**Comment by martinpitt** [comment]
Perhaps you need to `systemctl stop cockpit` to ensure that it restarts after updating the file? It also times out after 90s of inactivity, but you may not have waited for that long?

**Comment by AdamKearn** [comment]
@martinpitt  Yep that worked! Thanks!!!
Thanks
