### ISSUE TITLE
File ownership changed when removing authorized pubkey from user

### ISSUE THREAD

**Issue by mvn23** [cockpit-project/cockpit#11876]
Cockpit version: 188, 194
OS: 188 on Debian Stretch, 194 on Arch Linux
Page: "Accounts"

When removing a key from the list of `Authorized Public SSH Keys` of a user, that user's `~/.ssh/authorized_keys` file becomes owned by `root:root`. If the file is not world-readable (or group-readable if the user is a member of group `root`), this breaks that user's ssh key login.

Steps to reproduce
1. Make sure the target user has a file `~/.ssh/authorized_keys` with more than 1 key in it.
2. Check that this file is owned by the target user and group.
3. Remove one of the keys through Cockpit>Accounts>[target user]>Authorized Public SSH Keys.
4. Check ownership of the target user's `~/.ssh/authorized_keys`.

Expected result:
File ownership remains unchanged.

Actual result:
File is now owned by `root:root`.

**Comment by marusak** [comment]
Indeed, this is issue that is still happening. Verified with current master on Fedora 31

**Comment by marusak** [comment]
Closing in favor of https://github.com/cockpit-project/cockpit/issues/18033 which is more generic and describes exactly this issue.

**Comment by martinpitt** [comment]
I un-duplicate this, as the generic fix was not approved. I'll do a targeted but ugly fix for this specific issue, and then think about improving cockpit.file() after that.
