### ISSUE TITLE
New files are being blocked.

### ISSUE THREAD

**Issue by AdamKearn** [cockpit-project/cockpit#11897]
Cockpit version: TOT
OS: Ubuntu 19

Hello, I am trying to customise the login page.
I have curated a separate `.css` file to store my modifications in. 

When I include the `CSS` in my `HTML` I get errors in the  Chrome Dev Tools Console.
HTML:
```
<link href="login.css" type="text/css" rel="stylesheet">
```
Dev Tools:
```
Refused to apply style from 'https://ubuntu:9090/login.css'
because its MIME type ('text/html') is not a supported stylesheet MIME type,
and strict MIME checking is enabled.
```

Why is it blocked and also how would I whitelist this file to allow it?

Thanks for your help!!
-Adam

**Comment by martinpitt** [comment]
So you put your file into /usr/share/cockpit/static/login.css? Not sure how the text/html gets there, but with a naïve test it seems to work:
```
$ echo "html { }" | sudo tee /usr/share/cockpit/static/login.css
$ curl -I http://localhost:9090/cockpit/static/login.css
HTTP/1.1 200 OK
Content-Type: text/css
[...]
```
Does the curl command look different for you, i. e. does it say text/html? If so, is it possible to attach your login.css here?

If you have to rebuild cockpit anyway, it seems easiest to just customize ./src/ws/login.css.

**Comment by AdamKearn** [comment]
@martinpitt sorry for the late reply.
I will try this later.

**Comment by marusak** [comment]
ping @AdamKearn
