### ISSUE TITLE
Services: link the service log to the full log

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#11901]
Page: Services

As a sysadmin, I need to easily see the full logs for a service to assert what's going wrong.

Currently we have a limited log on a services page, and we have the full logs on the Logs page.
It's now possible to filter for services on the logs page, but there is no easy way to get there from the Service page.

The url-format for filtering for a service on the Logs page is:
`https://ip-of-host:9090/system/logs#/?tag=abrtd`

**Comment by marusak** [comment]
This is being also tracked in #8271 (which is a bit more general, since these logs are also on network and storage pages).
