### ISSUE TITLE
cockpit-kubernetes cannot connect to k3s - protocol-error

### ISSUE THREAD

**Issue by benfairless** [cockpit-project/cockpit#11900]
Cockpit version: 193
OS: Fedora 29
Page: Cluster

When running Cockpit and k3s, I am unable to use the 'Cluster' page in Cockpit to connect to the Kubernetes cluster and instead I receive a message saying 'Connection Error: protocol-error'

Steps to reproduce

1. Install `cockpit` & `cockpit-kubernetes` via DNF.
2. Install [k3s](https://k3s.io/) as a master.
3. Start cockpit services via `systemctl`.
4. Start k3s.
5. Copy `/etc/rancher/k3s/k3s.yaml` to `~/.kube/config`.
6. Log in to Cockpit in web browser and select 'Cluster'.

![image](https://user-images.githubusercontent.com/5775911/58138627-fad34380-7c2e-11e9-913d-9c7bbfcf407c.png)

From what I understand having read [this](https://cockpit-project.org/guide/193/feature-kubernetes.html), it should inherit these credentials from `~/.kube/config`. It does seem to do this as changes to the config are reflected in the browser.

Contents of `~/.kube/config`
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ~~REDACTED~~
    server: https://localhost:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: ~~REDACTED~~
    username: admin
```

I am able to hit the HTTPS endpoint `https://localhost:6443/api` using Basic Auth with these credentials and get a valid, authenticated, response:
```console
$ curl https://localhost:6443/api -k -u admin:REDACTED
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "127.0.0.1:6445"
    }
  ]
}
```

I am also able to use `kubectl` with this configuration:
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"archive", BuildDate:"2019-03-05T13:36:18Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1-k3s.4", GitCommit:"52f3b42401c93c36467f1fd6d294a3aba26c7def", GitTreeState:"clean", BuildDate:"2019-04-15T22:13+00:00Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

I checked the Javascript console log for messages and found the following:
```
cockpit.js:590 grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error
p @ cockpit.js:590
m @ cockpit.js:600
v @ cockpit.js:494
a.onmessage.o.dispatch_data @ cockpit.js:424
e @ cockpit.js:280
postMessage (async)
(anonymous) @ index.js:18
a.onmessage.o.dispatch_data @ cockpit.js:422

kubernetes.js:7 Connection Error: protocol-error
(anonymous) @ kubernetes.js:7
(anonymous) @ kubernetes.js:7
(anonymous) @ kubernetes.js:7
h @ kubernetes.js:7
(anonymous) @ kubernetes.js:7
(anonymous) @ kubernetes.js:7
(anonymous) @ kubernetes.js:7
$eval @ kubernetes.js:7
$digest @ kubernetes.js:7
(anonymous) @ kubernetes.js:7
h @ kubernetes.js:7
(anonymous) @ kubernetes.js:7
setTimeout (async)
St.i.defer @ kubernetes.js:7
$evalAsync @ kubernetes.js:7
(anonymous) @ kubernetes.js:7
o @ kubernetes.js:7
$$resolve @ kubernetes.js:7
resolve @ kubernetes.js:7
(anonymous) @ kubernetes.js:7
(anonymous) @ kubernetes.js:13
se @ cockpit.js:77
e @ cockpit.js:206
p @ cockpit.js:591
m @ cockpit.js:600
v @ cockpit.js:494
a.onmessage.o.dispatch_data @ cockpit.js:424
e @ cockpit.js:280
postMessage (async)
(anonymous) @ index.js:18
a.onmessage.o.dispatch_data @ cockpit.js:422
```

I'm not sure if `cockpit-kubernetes` is even meant to work with k3s so apologies for wasting your time if this isn't something you support.

Hopefully I've provided enough information, happy to provide anything else or possibly a vagrant environment with this issue if needed.

**Comment by benfairless** [comment]
I've also tried deploying the Kubernetes dashboard as a pod following the instructions [here](https://cockpit-project.org/guide/193/feature-kubernetes.html) and the 'Cluster' page functions fine on the Kubernetes pod hosted one.

**Comment by martinpitt** [comment]
Indeed we only test cockpit-kubernetes with the "full" kubernetes and OpenShift 3.x. Also, [cockpit-kubernetes has been deprecated](https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/thread/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/) for a while now, isn't present any more in Fedora 30 (nor RHEL 8), so we won't spend much time any more on new features. Supporting an entirely new implementation is pretty much a wontfix at this point, I'm afraid. Of course we'll gladly review/accept fixes from contributors, if you want to give it a go!

**Comment by benfairless** [comment]
Thanks for replying Martin. I'll look into the issue more myself but thanks for the information.

I'll close this now.
