### ISSUE TITLE
Align colors with PF4 / RHDDS

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11913]
Cockpit uses a lot of various colors. Many are hardcoded in LESS and CSS files.

We should standardize use of colors and align to the Red Hat Digital Design System where it makes sense and fall back to PF4 colors.

To do so, we'll need to:

## Color variables

- [ ] figure out a way to override PF3 variables: PR #12001
- [ ] map PF3 colors to RHDDS with a fallback to PF4
- [ ] change PF3 color variables to match RHDDS/PF4 where applicable

## Random colors

- [x] find all the random usages of colors in Cockpit's CSS and LESS files
- [x] map the colors from random hex values to PF3, PF4, PF4→RH, RH and find the best match (working from RH to PF4→RH, to PF4, and possibly PF3 in some rare cases)
- [x] convert random colors to logically named CSS variables, where possible (`--color-link`, `--color-link-hover`, …)
- [x] convert random colors to color names, as a fallback (`--color-red`, `--color-red-light`, …)
- [ ] map as many colors as we can into PF3 variable names (and in the future, PF4)

**Comment by garrett** [comment]
I've made a "Rosetta" color reference table @ https://codepen.io/garrett/full/joZGPg which maps our one-off used colors from CSS & LESS files into various other palettes using quantization in the GIMP to find close matches from various color palettes.

We should prefer the RH palette, but fall back to one of the two PF4 conversions (either Cockpit to PF4 or Cockpit to PF4 to RH). Basically, whatever looks truest to intent. (Example: RHDDS doesn't currently have a purple, but PF4 does.)

Most of the colors in the rightmost 2 colums (the RHDDS palette conversion) are the optimal targets. A 2-times conversion (through PF4) gives us another alternate, if the straight-up conversion isn't optimal.

**Comment by garrett** [comment]
@martinpitt: Do you know how to override styles with PatternFly?

Ordinarily, we'd probably edit the `variables.less` file, but that's located in `node_modules` and not part of the git repo... so I don't know how we'd do this properly.

After poking around for a while, I think it has something to do with `src/base1/Makefile.am` ([around line 60](https://github.com/cockpit-project/cockpit/blob/master/src/base1/Makefile.am#L60-L72)) — we'd probably need to have a special `variables-overrides.less` or something like this that gets injected into PatternFly during the compilation step, perhaps?

It looks like right now, we're using a precompiled version of PatternFly from `PatternFly/dist`, but we'd need to compile PatternFly from LESS with variable changes, then copy the results into `dist/base1` instead, I think. :man_shrugging:

**Comment by martinpitt** [comment]
I don't know about it, I started looking into how this all works. Some random notes:

 * As an example I looked  at `@pficon-var-close` in node_modules/patternfly/dist/less/variables.less
 * The variables are still preserved in node_modules/patternfly/dist/less/variables.less , the file that we include in pkg/lib/variables.less. We probably don't want to replace the entire file, but override some values in e. g. pkg/lib/patternfly.less, and include it later in pkg/lib/variables.less (TODO: figure out whether this kind of "later value overrides earlier setting" works).
 * Our generated dist/base1/patternfly-additions.css has these variables resolved, e. g. 
```css
combobox-container .glyphicon-remove:before {
  content: "\e60b";
  font-family: "PatternFlyIcons-webfont";
}
```
 * That is built from is node_modules/patternfly/dist/css/patternfly-additions.css, which also alrleady has `content` resolved to the variable value. That seems to coincide with your comment about "we're using a precompiled version of PatternFly from PatternFly/dist".
  * However, the original css while that defines `.glyphicon-remove` using the variable does not exist *anywhere* in node_modules/patternfly/. So maybe there's an "npm install patternfly-source" or something, to be investigated.

**Comment by martinpitt** [comment]
It seems I'm understanding this wrong -- the "resolved" `\e60b` is even contained in the [upstream source  file](https://github.com/patternfly/patternfly/blob/master/src/less/bootstrap-combobox.less#L24), so apparently that was a bad example.

So maybe this one: The upstream PF source defines

    src/less/variables.less:@nav-pf-vertical-color:                                             @color-pf-black-300;

which is being used in 

    src/less/vertical-nav.less:      color: @nav-pf-vertical-color;

we use `.nav-pf-vertical` in our shell. This gets resolved/compiled in node_modules/patternfly/dist/css/patternfly-additions.css, so we lose it at that stage. But we still have it in node_modules/patternfly/dist/less/vertical-nav.less.

So at first sight it should be possible somehow to use (or perhaps compile) node_modules/patternfly/dist/less/patternfly-additions.less instead of using node_modules/patternfly/dist/css/patternfly-additions.css. This shouldn't require any extra source code, just the less-loader that we already  have in webpack anyway.

**Comment by martinpitt** [comment]
I sent PR #12001 for building PF from less with variable overrides.
