### ISSUE TITLE
Login fails: incorrect protocol: received invalid length prefix

### ISSUE THREAD

**Issue by shortbike** [cockpit-project/cockpit#11924]
Cockpit version: cockpit-194-1.fc30.x86_64
OS: fedora 30 (5.0.17-300.fc30.x86_64)
Page: <cockpit running on local machine>

Logging in with user account/admin-privs fails - can only login as root.
Error: Internal error in login process
SELinux is enabled
SSH keys generated
No non-default auth/pam settings

Steps to reproduce

1. Enable/Start cockpit service on local machine
2. Add firewall rules
3. Attempt to login in to cockpit running on local machine as user (w/admin privs etc.)

Login Screen Error -> https://imgur.com/a/hhh0ukU
"journalctl -b -u cockpit" output -> https://imgur.com/a/xVC2C0V

**Comment by martinpitt** [comment]
This got also reported in https://bugzilla.redhat.com/show_bug.cgi?id=1710604 . I haven't yet been able to reproduce this, nor do our tests spot it. It seems something writes on cockpit-session's stdout that breaks the protocol.

**Comment by shortbike** [comment]
Martin,
Thanks for this.
FYI - login to local host:9090 as root works without any issues. The error only appears when attempting login as a user/admin etc.
Phil

**Comment by martinpitt** [comment]
I just got an idea. I bet this broke between 191 and 192 due to https://github.com/cockpit-project/cockpit/pull/11575 . If your ~/.bashrc (or equivalent for your selected login shell) prints something, it would disturb the protocol. What's the output of

    /bin/bash -c 'echo hello'

? I. e. does that print anything else than "hello"?

**Comment by martinpitt** [comment]
No response in half a year, and this almost surely got fixed in PR #11978.
