### ISSUE TITLE
[no-test] Image refresh for rhel-7-7

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#11967]
Image refresh for rhel-7-7
 * [ ] FAIL: image-refresh rhel-7-7

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-06.
Log: https://209.132.184.41:8493/logs/image-refresh-11967-20190531-010606/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-11967-20190531-010606/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-11967-20190531-010606/

**Comment by martinpitt** [comment]
Same issue with the team subscription.
