### ISSUE TITLE
Spawn/Script processes exit on page reloads

### ISSUE THREAD

**Issue by mckenziec** [cockpit-project/cockpit#11989]
Cockpit version: 194
OS: CentOS 7

When writing a custom plugin to cockpit, the spawn and script support in cockpit.js will execute a server side process, but if the user browser refreshes, the process will exit prematurely.

To reproduce, take the pinger example (https://github.com/cockpit-project/cockpit/blob/master/examples/pinger/) and modify the pinger.js (https://github.com/cockpit-project/cockpit/blob/master/examples/pinger/pinger.js) to ping indefinitely or for a high number of ping attempts (e.g. change "4" to "4000").

Start the ping test, then drop to the server terminal and observe the ping process (e.g. ps -ef | grep ping).

Refresh the browser page, then on the terminal, check for the ping process again, it will be terminated. 

I was writing a cockpit extension to spawn a configuration process that could take a couple of minutes to complete. My script is included with the plugin in a /bin directory (e.g. /usr/share/cockpit/test/bin/test.py), and it executes fine, but if the browser is refreshed the process will terminate.

Is there a way around this? Maybe this is a enhancement request? I know the jQuery promise will no longer be hooked up if the browser refreshes, but worst case I can work out process interaction logic. e.g. process creates a PID file, self checks when called, reads output from a log file, etc...

**Comment by martinpitt** [comment]
Right, with a page reload every JS object goes away, so you can't keep state that way. For longer-running jobs it's generally better to talk to an external service (D-Bus or varlink), which is the main way how Cockpit works.

There is no generic approach to keeping that state which will work equally well for each use case. E. g. using a cookie or localstore is too strong here, as it doesn't update to the system state (if the process goes away). Here are two ideas:

 - Call your process through [systemd-run](https://www.freedesktop.org/software/systemd/man/systemd-run.html), and give it a predictable name like `cockpit-test-py`. Then have your page first check if that service exists, and get its state and "resume" it.

 - If you don't like the above for some reason, fork your process into the background (`test.py &`) and store its pid somewhere (`/run` is a good place), and check for a running pid in your page. This is fairly similar to the above, except that systemd  does the state keeping for you.

**Comment by mckenziec** [comment]
Thanks for the quick response. I'm still juggling what the best approach would be. Using systemd means registering a process as a service. In this instance I was looking at running a process that might take sometime but only run/report to the plugin view during execution. e.g. large random key material generation can take a bit of time. I was hoping for an approach where I could leverage cockpit as much as possible with as little change to the underlying system (outside of adding a cockpit plugin).

I think I might take the approach that a plugin shell/python script be called for for all operations and tracking progress/status.

**Comment by martinpitt** [comment]
Yes, the process would run "as a service", but that's exactly what you want -- it should run detached from any terminal or UI, with a way to control and inspect it. That's exactly what a systemd unit is, and with systemd run you can run a transient one on the fly without having to write config files anywhere.
