### ISSUE TITLE
[translation file] "After" word must have various contexts

### ISSUE THREAD

**Issue by Illumaria** [cockpit-project/cockpit#12019]
Hello,

I am translating Cockpit into Russian using Zanata platform at the moment, and I encountered a minor problem (which doesn't seem minor to me). As far as I could figure it out (please correct me if I'm wrong), there are two possible occurrences of the single word "After" in Cockpit:

1. First one can be found when creating a timer at the Services -> Timers menu.
2. Second one is one of a unit options/dependencies (opposite to "Before").

The point is, these two situations require different translations for the word "After", but there's only one such string in the translation file. Therefore, it would be great to split it up somehow.

**Comment by KKoukiou** [comment]
We will need to translate some longer part of the sentence instead of a single word.
As we do for example for "After system boot".
