### ISSUE TITLE
g_hmac_new() can return NULL

### ISSUE THREAD

**Issue by pwithnall** [cockpit-project/cockpit#12016]
As pointed out in [this upstream GLib bug](https://gitlab.gnome.org/GNOME/glib/merge_requests/897), `g_hmac_new()` can return `NULL` and Cockpit [doesn’t check for that](https://github.com/cockpit-project/cockpit/blob/65a755a230e4ff345787b6186a220901712f0268/src/ssh/cockpitsshknownhosts.c#L376). Hence Cockpit could crash if (for some reason) the build of GLib you’re using doesn’t support the digest type you want.

**Comment by martinpitt** [comment]
See https://bugzilla.redhat.com/show_bug.cgi?id=1718074 -- this is only an issue on RHEL/CentOS 7 and debian-stable with libssh 0.7. The code that uses GHmac isn't built at all for recent distributions.

Keeping this open for the old distributions, though (although I suspect their glib won't get such changes, it would be too intrusive).

**Comment by martinpitt** [comment]
Fixed in PR #12018
