### ISSUE TITLE
RFC: provide rhel-7 and rhel-8 test images always pointing to the latest minor release

### ISSUE THREAD

**Issue by atodorov** [cockpit-project/cockpit#12031]
From discussion in https://github.com/cockpit-project/cockpit/pull/12015 it's clear there are no `rhel-7` and `rhel-8` images. Instead they are always versioned to reflect the minor release numbers (e.g. `rhel-7-7`).

Ideally for lorax-composer we would like to have a more generic image name which always points to the latest minor version so we don't have to update the matrix of test scenarios for every minor release.

**Comment by larskarlitski** [comment]
I disagree. We should know what we're testing on and explicitly turn on a new release when we have verified that it works. Otherwise, pull requests might start breaking because the minor release changed, which is unrelated to the change itself.

**Comment by martinpitt** [comment]
Agreed. On top of that, we usually also need to run PRs on several parallel supported releases, e. g. for 7.6 z-stream and 7.7
