### ISSUE TITLE
After having changed the user's password privilege escalation doesn't work anymore

### ISSUE THREAD

**Issue by DevPre24** [cockpit-project/cockpit#12069]
Cockpit version: 196
OS: Fedora 30
Page: Terminal

After changing the password of a account via the "Accounts" page privilege escalation doesn't work anymore as intended.
Command such as "sudo -i" ask for the password to be entered even though "Reuse my password for privileged tasks" checkbox during login is checked and next to the user there's the Privileged banner.

The machine was restarted after changing the user's password.

Steps to reproduce

1. Login in
2. Change the current user password via the Accounts page
3. (Restart the machine/Cockpit) ?
4. Login in again but this time with the new password, pay attention to the  "Reuse my password for privileged tasks" checkbox to be ticked
5. Open the terminal and type a sudo command (eg. sudo -i)
Result: You'll be asked for the password to be entered

**Comment by martinpitt** [comment]
This behaviour is unrelated to changing the password. The "reuse my password for privileged tasks" checkbox only applies to admin operations in the cockpit UI. `sudo` in a terminal always asks for the password, cockpit does not change sudo's PAM stack to avoid that (by intent).

This works as intended, so I'm closing this.
