### ISSUE TITLE
Storage -> Order by mount point instead of name

### ISSUE THREAD

**Issue by lachlan-00** [cockpit-project/cockpit#12082]
In the Storage\Filesystems section it would be better to sort by path rather than label or at least allow it to be selectable.
![image](https://user-images.githubusercontent.com/1305249/59652485-37b03d00-91d1-11e9-8789-5f1214b85688.png)

**Comment by marusak** [comment]
@andreasn what is your option about this from UX point of view?

**Comment by KKoukiou** [comment]
I think we can utilize shortable PF tables here https://www.patternfly.org/v4/documentation/react/components/table/#sortable-table and have it available for both columns.
