### ISSUE TITLE
Unable to use cockpit.spawn with systemd-run for long running processes

### ISSUE THREAD

**Issue by mckenziec** [cockpit-project/cockpit#12122]
Cockpit version: 194
OS: CentOS 7

I've been trying to use cockpit.spawn() in a custom plugin to execute a long running process (not a service, just a python tool I wrote that could take up to 3 minutes to complete), and a suggestion was to leverage systemd-run to execute it.

I ended up writing a JS class library to handle execution of the process, then a watcher to check on its status. During this I figured out a bunch of nice details about how to interpret "systemctl show", but overall I'm having trouble running systemd-run with sudo through cockpit.spawn().

Basically I'm calling spawn as follows:

```
      var cmd = ["/usr/share/cockpit/unity-features/bin/unity-controller.py", procId, "enable"];
      var args = this.arrayBuilder(
            ["sudo", "systemd-run", "--remain-after-exit", "--service-type=simple", "--unit", procId],
            cmd);
    console.log("Trying: " + args.join(" "));
    var p = cockpit.spawn(args);
```
The built up command looks something like this:

sudo systemd-run --remain-after-exit --service-type=simple --unit aesir_core_classic /usr/share/cockpit/test-plugin/bin/test-controller.py core enable

This will run fine using the same user as in cockpit, but I have to enter my password when sudo'ing. 

So I added a new group and created the following /etc/sudoers.d/test file:

%test-admin ALL=(ALL:ALL) NOPASSWD:/usr/bin/systemd-run /usr/bin/systemctl

When I try executing spawn in Chrome, I get a failed callback with the message, "sudo exited with code 1"

The python script has good file permissions, and the directory/file structure is owned by my user.

Note that I have to include --remain-after-exit, otherwise when the process completes I won't be able to query its status details. --service-type is needed to detach the process from the caller foreground. 

If anyone is interested, calling "systemctl show <unit name> -p ExecMainPID,ExecMainCode,ExecMainStatus,ExecMainStartTimestamp,ExecMainExitTimestamp" will give you everything you need to determine what happened with your process (without having to parse through journalctl output). If there's a non-zero ExecMainPID, it ran. If systemd was able to execute the process ExecMainCode will be 1. If your process ran and completed, its exit code will be ExecMainStatus. Finally you can use the start/exit timestamps to kind of frame when it ran. e.g. last week or just now.

Any help is much appreciated. Thanks.

**Comment by marusak** [comment]
I think you are using spawn incorrectly. The first item in the `args` array is executable followed with its arguments. When you want to enforce superuser, use argument `superuser`.

For more info see docs: https://cockpit-project.org/guide/latest/cockpit-spawn.html

So you want to do something like this: 
```
process = cockpit.spawn([`systemd-run`, `--remain-after-exit` ... ], {superuser: "require"});
```

**Comment by martinpitt** [comment]
Only a quick en-passant comment: *never* run `sudo` as part of a command, as it will hang on a password prompt. Instead, set the `{ superuser: "require" }` option.

**Comment by mckenziec** [comment]
Huzzah! You're a life saver guys. I knew and forgot about the superuser option.
