### ISSUE TITLE
Exposing NVDIMM information 

### ISSUE THREAD

**Issue by akidua4** [cockpit-project/cockpit#12140]
Page: Hardware Info

In order to expose information about persistent memory, "ndctl" can be used to show NVDIMMs in the machine. "ndctl" will display list of clickable regions and each region will have associated namespaces and memory modules. The display is similar to what we see when we click on filesystems and drives.

**Comment by akidua4** [comment]
<img width="960" alt="Screenshot from 2019-06-19 11-13-23" src="https://user-images.githubusercontent.com/49456665/60038713-ad595480-967a-11e9-8024-a2c98a958fa5.png">
<img width="835" alt="Screenshot from 2019-06-12 12-12-52 (002)" src="https://user-images.githubusercontent.com/49456665/60038731-b5b18f80-967a-11e9-9369-291a34a0e463.png">

**Comment by KKoukiou** [comment]
@garrett @andreasn the above screenshots are mockups @akidua4 prepared by himself.
Are you satisfied with the design so that he can proceed with the implementation?

**Comment by andreasn** [comment]
So this is a hardware field I'm not very familiar with, but looks all right to me.
The first mockup has a lot of columns, so it could make it slightly harder to get a quick overview. Might be worth testing if some of the information can be shown in an expander, similar to the lower mockup. But yeah, no big concerns from me, design-wise.

**Comment by garrett** [comment]
I'm not sure about the "Name Spaces"* list being expandable. The information I see in the details area here could all be displayed in the list by default without expanding.

(* also: should it be "Namespaces" or is the space an accepted term here?)

**Comment by JeffMoyer** [comment]
On the hardware tab, I don't know why you wouldn't also list the NVDIMMs in with the normal DRAM DIMMS.

In the region page, could you also list the available space?

Is there a way to have a tree format for the regions, so you could list them all on one page, and expand each region individually?

In response to garrett, I assume that we'll eventually get access to all of the information for namespaces there.  For example, this is what's available from ndctl:

# ndctl list -n namespace1.0 -v 
[
  {
    "dev":"namespace1.0",
    "mode":"fsdax",
    "map":"dev",
    "size":583442366464,
    "uuid":"47b6d25b-bdb7-40cd-9bec-caadd33e76de",
    "raw_uuid":"64a145ec-d5de-4c49-9470-2b097c18ff33",
    "sector_size":512,
    "align":2097152,
    "blockdev":"pmem1",
    "numa_node":1,
    "supported_alignments":[
      4096,
      2097152,
      1073741824
    ],
    "badblock_count":1,
    "badblocks":[
      {
        "offset":4160,
        "length":1,
        "dimms":[
          "nmem6"
        ]
      }
    ]
  }
]

**Comment by akidua4** [comment]
@JeffMoyer There is a tree list view in patternfly but I don't see the respective components/library already built in cockpit.

![tree_list](https://user-images.githubusercontent.com/49456665/61828933-70c17a00-ae2d-11e9-9561-a7056e1a7a78.png)

**Comment by akidua4** [comment]
https://www.patternfly.org/v3/pattern-library/content-views/tree-list-view/#code

So should I proceed with this design or the design that was proposed originally?

**Comment by akidua4** [comment]
As of now I have basic ListingRow displaying some key attributes and using dmidecode and ndctl together, I am able to display DIMM IDs associated with each region.
![nspaces](https://user-images.githubusercontent.com/49456665/61829154-f2190c80-ae2d-11e9-87ca-0ee5987a2a53.png)

**Comment by akidua4** [comment]
@andreasn @garrett ??

**Comment by andreasn** [comment]
Sorry for the delay! Just got back from vacation.

> As of now I have basic ListingRow displaying some key attributes and using dmidecode and ndctl together, I am able to display DIMM IDs associated with each region.

This looks good to me! Thanks for the fixes!

**Comment by garrett** [comment]
@akidua4: The revised list (without expandables) in the bottom screenshot looks good to me. Thanks!

**Comment by marusak** [comment]
Being implemented in #12487

**Comment by JeffMoyer** [comment]
The namespaces are wrong in your screen shot.  You are listing the nmem devices instead of the namespaces.

I've rebased your code to the latest git tree and fixed the bugs I found.  I'll submit a pull request with that at some point.

The next step is to modify the storage page to allow for configuring of pmem namespaces.

**Comment by JeffMoyer** [comment]
@akidua4 are you going to update your pull request?  If you do, I can test what you have instead (in fact, that's what I'd prefer to do).  I'm just trying to move this along.

Thanks!

**Comment by martinpitt** [comment]
PR #12487 got closed due to inactivity. We have to get some information from someone while an actual NVDIMM system, as none of the core developers has access to such a system. Please re-open if you are interested in this. Thanks!
