### ISSUE TITLE
use disabled attribute instead of class

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#12155]
Cockpit version: 196
OS: Fedora 30
Page: Network

This came up in #11987
The way the network page does the disabled state is via a disabled class, rather than a [disabled html attribute](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Attribute/disabled).

**Comment by martinpitt** [comment]
We actually do that in a several other places:
```
pkg/docker/containers-view.jsx:                                <li key={index} className={ action.disabled ? 'disabled' : '' }>
pkg/lib/machine-sync-users.html:    <button class="btn btn-primary disabled" translatable="yes">Synchronize</button>
pkg/shell/indexes.js:            group.className = "list-group-item disabled";
pkg/storaged/storage-controls.jsx:                                            className={classes + (excuse ? " disabled" : "")}
pkg/storaged/storage-controls.jsx:                                        className={"link-button ct-form-relax" + (excuse ? " disabled" : "")}>
pkg/storaged/storage-controls.jsx:                                    btn_classes += " disabled";
pkg/systemd/service-details.jsx:                <DropdownKebab id="service-actions" title={ _("Additional actions") } className={this.props.disabled ? "disabled" : "" }>
pkg/systemd/service-details.jsx:                                            {rel.Units.map(unit => <li key={unit}><a href={"#/" + unit} className={this.props.isValid(unit) ? "" : "disabled"}>{unit}</a></li>)}
```

It seems the Networking page got fixed in #11987, but we should fix the others.

**Comment by leomoty** [comment]
I guess i'll take this over since #13061 is dead and I am aware how to run tests. @martinpitt can you rerun the command to see where disabled is still used?

**Comment by martinpitt** [comment]
@leomoty : That would be much appreciated! #13061 still looks like a nice start, it "just" needs to be updated to the current code. There was no magic command for that, I just ran `git grep -w disabled pkg src` and then manually fished out the relevant hits.

**Comment by martinpitt** [comment]
@deryni: Hover tooltips are fine, they just need to be attached to the parent element of the disabled one. Our code does that.
