### ISSUE TITLE
Drop `Promise.prototype.finally` polyfill

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#12151]
Related to https://github.com/cockpit-project/cockpit/pull/12134, we should also drop the last polyfill, `Promise.prototype.finally`.

TODO:
- [x] bump up our official minimum browser support from Chrome 57 to 63 on the website: https://github.com/cockpit-project/cockpit-project.github.io/pull/279
- [x] remove polyfill
- [x] bump up our official minimum browser support from Chrome 57 to 63 in build system
- [x] add a check for `Promise.prototype.finally` in our login page

As Chrome 63 was released in Dec 2017, this should be fine; nobody should be using such an old unsupported browser (due to real-world security issues). Real world browser usage from 57 to 62 is < 0.3%. In addition, hopefully our target audience, admins, are more security conscious and tech saavy than to run such an old browser. :wink:

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit-project.github.io/pull/279 and PR #13020 implement all that.

**Comment by martinpitt** [comment]
See #13020, we can't do that yet. That PR still cleans it up, but we still need the Polyfill for Edge.

**Comment by garrett** [comment]
Clarification: We need the polyfill for Edge < 18, which came out in November 2018.

1. Our tests currently run Edge 17
2. Edge 18 is the current version at the time of writing... so it would be nice to support "current - 1"

Edge 18 supports almost all of finally without the polyfill, but lacking support for the two Edge cases above :smirk: means we'll have to wait a bit — at minimum until Edge > 18 arrives (most likely the Chromium-based edge) and we upgrade our test VM.

**Comment by martinpitt** [comment]
We decided to drop our Edge CI in April, when the non-Chromium Edge will go out of support. Until then this is blocked, but still valid as such.
