### ISSUE TITLE
Account locked via password doesn't unlock consistently via Cockpit

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1216]
An account locked via passwd doesn't unlock consistently via Cockpit, sometimes requiring the action twice.

 1. login to cockpit as root and open "Account" card of existing user
 2. in command line do "passwd -l <username>" as root
 3. go back to Cockpit and unlock the user
 4. wait a few seconds

**Comment by dperpeet** [comment]
Should we warn about this, go with @mvollmer's workaround or choose to ignore it due to different tools doing different things?
