### ISSUE TITLE
Unable to get chained certificate file correct

### ISSUE THREAD

**Issue by Taomyn** [cockpit-project/cockpit#12179]
Cockpit version: 196
OS: Fedora Server 30

I'm unable to get the certificate file correct so that my Let's Encrypt (LE) certificate is trusted by the server itself.

I was having issues getting local commands/services on my Fedora box to connect to it own SSL services i.e. local Apache and Cockpit. When I use wget/curl I receive an error that the certificate cannot be trusted:

```
ERROR: The certificate of ‘mymachine’ is not trusted.
ERROR: The certificate of ‘mymachine’ doesn't have a known issuer.
```

From an external machine using a browser the same certificate is fine.

I was able to fix Apache by adding to the SSL.CONF the location of the two intermediate certificates for LE that I downloaded, and now wget/curl works with that. But I cannot get the .cert file for Cockpit to work. The service appears to accept the file as I can access it from another machine, but wget/curl continues to fail.

Roughly the format of the file I created is:

```
-----BEGIN CERTIFICATE-----
LE ROOT CA
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
LE INTERMEDIATE CA
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MYMACHINE
-----END CERTIFICATE-----
-----BEGIN RSA PRIVATE KEY-----
MYMACHINE
-----END RSA PRIVATE KEY-----

```

I tried various combinations of the order, removed the "RSA" wording but none have been successful.

Any advice? I'm a bit of a Linux noob, so go easy with me.

**Comment by martinpitt** [comment]
https://cockpit-project.org/guide/latest/https.html#https-certificates describes the format. If you put the private key first, then the certificate, and then the intermediates (i. e. exactly the opposite order as you shown before), it should work.

**Comment by Taomyn** [comment]
Thanks, that's done the trick - I'm not sure why I didn't try it in that order I just think I'd done it with the private key last elsewhere.
