### ISSUE TITLE
Packages returns no values

### ISSUE THREAD

**Issue by dyioulos** [cockpit-project/cockpit#12178]
Version:  197
System:  CentOS 7.3 Virtyalbox VM

Aside from a button labelled "Reload", which appears in the Packages values window (and does nothing when clicked, no values are returned.

**Comment by marusak** [comment]
I am pretty sure that is all it can show. It is in `playground` (see url) so it is(was) used for tests/development.
Is it supposed to do something else?

**Comment by martinpitt** [comment]
Right. Please don't install cockpit-tests, it's really not useful other than for automatic tests.
