### ISSUE TITLE
Cockpit Login - AmazonAWS Lightsail

### ISSUE THREAD

**Issue by patrickmau** [cockpit-project/cockpit#12189]
I have several AmazonAWS Lightsail instances running Ubuntu 16.04 and for testing purposes installed Cockpit on one of them, just to find that I cannot get past the login form.

I tried the AmazonAWS account details as well created an IAM user account with the relevant permissions, but to no avail.

How can I login to Cockpit when running on AWS Lightsail?
Thanks

**Comment by kevingermain** [comment]
You have to create password for your root account. 
> sudo su
> passwd
> Enter your password

After you defined it, you will be able to connect to lightsail.

**Comment by martinpitt** [comment]
What happens exactly on the login form? Do you get some error message?

Note that you don't necessarily need to login as root, and this is in fact highly discouraged on Ubuntu. In general it's better to log in as a real user who has sudo privileges.

Please log in via ssh, run  `sudo journalctl -f`, then try to log in in Cockpit, and check if there is some error message.

**Comment by patrickmau** [comment]
> You have to create password for your root account.
> 
> > sudo su
> > passwd
> > Enter your password
> 
> After you defined it, you will be able to connect to lightsail.

Thank you this actually worked.
Out of curiousity, where is this password going to be stored? Does this affect any other login on my server?

**Comment by patrickmau** [comment]
> What happens exactly on the login form? Do you get some error message?
> 
> Note that you don't necessarily need to login as root, and this is in fact highly discouraged on Ubuntu. In general it's better to log in as a real user who has sudo privileges.
> 
> Please log in via ssh, run `sudo journalctl -f`, then try to log in in Cockpit, and check if there is some error message.

After stating the journal, all I can see is a login error when trying to login with my default 'ubuntu' user account.
`pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=91.207.174.109  user=ubuntu`

I can login as root thanks to @martinpitt 's workaround, but interestingly when I login as root and check out the user accounts, I can see an account named "Ubuntu" but am unable to remove the tick in the "permanent lock" checkbox.

Not sure why, but it seems cockpit itself has a beef with my ubuntu account credentials..?

**Comment by martinpitt** [comment]
@patrickmau : That sounds like you couldn't log in as ubuntu through ssh either, at least not with a password. These instances may come preconfigured with disabling the password of the ubuntu user and only allow key-based logins?
