### ISSUE TITLE
Cockpit can't handle HTTP headers that have unicode characters

### ISSUE THREAD

**Issue by danielskowronski** [cockpit-project/cockpit#12192]
Cockpit version: 196
OS: Ubuntu 18.04.2 LTS
Page: N/A

Cockpit can't handle unicode characters in HTTP headers. This probably won't ever be hit if user connects directly to cockpit.socket or via simple reverse proxy. 

However I use caddy reverse proxy with JWT used as preauth. One of identifty providers, Github, returns full name including unicode characters in Token-Claim-Name

This causes message "received invalid HTTP request headers" in logs, when debug is enabled additional line appeared - "received invalid header" which pinpoints issue to `is_valid_line` function: https://github.com/cockpit-project/cockpit/blob/899ef8edb8b55b06e9647250842ccd0fb92f9944/src/websocket/websocket.c#L147

Cockpit config untouched. Caddy config:
```
(auth) {
  jwt {
    path /
    allow sub danielskowronski
  }
}
cockpit.example.com {
  import auth
  proxy / http://127.0.0.1:9090 {
    insecure_skip_verify
    transparent
    websocket
    header_upstream Token-Claim-Name _
  }
  log / /var/log/caddy-cockpit.log
}
```

Steps to reproduce
1. Send any header containing unicode to Cockpit (eg. from web browser console, curl)
2. It'll return 500 code

Temporal workaround

In caddy one can overwrite any header sent to backend application, so it's enoung to add `header_upstream Token-Claim-Name _` in `proxy` section of Caddy.

**Comment by martinpitt** [comment]
This can be trivially reproduced with `curl -H 'Foo: bär' http://localhost:9090`.

Indeed right now cockpit only accepts plain ASCII header values. I'm trying to gauge what could possibly break if we allow UTF-8 header values. The [HTTP spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) does not restrict the values or prescribes an encoding; even binary data is allowed as long as it's terminated with CRLF.

I checked what kind of headers cockpit looks at, with `git grep lookup.*headers`, and they all seem to be UTF-8 safe -- in particular, we either accept particular values only, such as `Connection: keep-alive`; or they are treated as opaque values, such as `X-Cockpit-Pkg-Checksum`.

A more involved case is `cockpit_web_server_parse_languages()`, which actually does some elaborate parsing. This could hiccup with UTF-8 if e. g. the second byte of a multi-byte character is `:`. So if you manipulate that header in the right way, you can trick the page into not giving you correct translations. But of course you can just do that directly.

Another interesting case is `X-Forwarded-Host`. I think non-ASCII host names won't actually end up as UTF-8 in the `Host:` header, but instead be [punycoded](https://en.wikipedia.org/wiki/Internationalized_domain_name) (xn-blah), so I don't think cockpit is currently broken with these.

So at the moment, I think it would be safe to allow UTF-8 header values.

@stefwalter, I'd appreciate your opinion/experience here.

**Comment by martinpitt** [comment]
I did an audit of headers we look at wrt. UTF-8 safety, using this command:

    git grep -E 'lookup.*headers|_web_socket_util_header_contains' | grep -v test-

Header | used for/audit
---------  | ---------
Accept-Language  | string parsing; could hiccup with UTF-8 if e. g. the second byte of a multi-byte character is `:` -- at worst, page is not translated, which is not a security issue
Host | redirection to https (safe enough with UTF-8 chars, the target host might just not exist); comparison to `localhost` constant (safe); concatenation with URL into "origin" for `cockpit_web_response_security_policy()`, where it's copied verbatim into a larger string in `string_inject_origin()`, safe
Content-Length | parsed with `g_ascii_strtoull()` with proper error handling
Transfer-Encoding | only compared to constant `chunked`
Connection | only compared to constants `keep-alive` or `upgrade`
X-Forwarded-{Proto,Host} | concatenated into `Access-Control-Allow-Origin:` header URL, safe
ProtocolHeader option in cockpit.conf | only compared to constants `http` and `https`
Upgrade | only compared to constant `websocket`
X-Cockpit-Pkg-Checksum | not interpreted, just stored verbatim
Pragma | only tested for substring "nocache", safe
If-None-Match | tested for identity to ETag, safe
X-SSH-Connect-Unknown-Hosts | only compared to constant `yes`
Authorization | calculates type prefix up to `:` or ` `; safe, may result in failed auth; type prefix is only compared to constants; auth value is either being passed on as opaque value, or dissected in `cockpit_authorize_parse_basic()` (looks safe, but not 100% sure) :warning:
X-Authorize | only tested for substring "password", safe
Sec-WebSocket-Protocol | Split by `, `, might catch multi-byte UTF-8 sequences :warning: 
Sec-WebSocket-Key | passed to `validate_rfc6455_websocket_key()` which gets base64-decoded; UTF-8 is invalid base64
Origin | used with `g_ascii_strcasecmp()`, which is not safe for arbitrary binary data, but for UTF-8

So in summary, most are safe except for `Authorization` and `Sec-WebSocket-Protocol`; I can't directly see a vulnerability with UTF-8, but just to be on the safe side, let's enforce ASCIIness for these two. I'll rework the PR.
