### ISSUE TITLE
Display Bug on Openshift Registry Console

### ISSUE THREAD

**Issue by brucejcong** [cockpit-project/cockpit#12197]
#### Description

Header of the registry console is displayed twice. It is displayed as "Red Hat Container RegistryRed Hat Container Registry". Using the inspector reveals that there is extra text in the html when the css  before selector is supposed to be adding the text. The image we are using is found [here](https://access.redhat.com/containers/#/registry.access.redhat.com/openshift3/registry-console). 

Screenshots found here: 
![Screen Shot 2019-06-20 at 10 13 47 AM](https://user-images.githubusercontent.com/39174143/59944722-1ea2c880-942b-11e9-897b-73899eaf1339.png)
![Screen Shot 2019-06-19 at 4 53 01 PM](https://user-images.githubusercontent.com/39174143/59944726-23677c80-942b-11e9-9084-875b79c13784.png)

**Comment by marusak** [comment]
This is kubernetes subpackage for which, unfortunately, upstream support has been dropped, see #12133.

If this affects you in downstream, please open bugzilla.
Sorry for any inconveniences.
