### ISSUE TITLE
Missing Plugins/Pages?

### ISSUE THREAD

**Issue by TheEagle13** [cockpit-project/cockpit#12194]
Cockpit version: 197
OS: OpenSUSE Tumbleweed
Page: ALL

Hello, I just built and installed from source. But it appears I am missing all the fancy plugins/pages? Did I miss an setup step somewhere?

I'm expecting to see something like the demo images on the project Homepage (https://cockpit-project.org/) But all I see is the following after login:

![Screenshot](https://user-images.githubusercontent.com/32144818/60407640-2c6df180-9b81-11e9-9dd7-e1a9e57c4c43.png)

I appreciate any help!

**Comment by marusak** [comment]
> I just built and installed from source.

Can you please write steps you did?

If you used `./autogen` and `make` with symlinking `dist` directory, then you are not going to see this changes as `root` but only as the user, which built it.

**Comment by TheEagle13** [comment]
I believe so. I don't remember entirely as it was late at night, and I don't recall finding build instructions.

Are they located somewhere that I can walk through and verify what I've done? This was built with root.

**Comment by TheEagle13** [comment]
So as a test, I did an install of CentOS this time since it is supported and supposedly only requires an install via yum, I only have 2 additional pages available now. So evidently I must be missing something, but since I followed the install guide on the website, I can't be that far off base?

**Comment by marusak** [comment]
> Are they located somewhere that I can walk through and verify what I've done?

https://github.com/cockpit-project/cockpit/blob/master/HACKING.md

> This was built with root.

Building as a root is almost always a bad idea.

> So evidently I must be missing something, but since I followed the install guide on the website, I can't be that far off base?

There are additional cockpit packages. They are always called `cockpit-*`. For example `cockpit-docker`,  `cockpit-storaged`,  `cockpit-networkmanager`... You can install those separately.

**Comment by TheEagle13** [comment]
I installed as root because several of the commands wouldn't run as a regular user (even with sudo). 
Is it documented somewhere that these additional packages need to be installed or even exist? The install instructions for your supported OS'es say nothing about them, where they are located, or how to install them.

How does one go about getting them to build for an unsupported system?

**Comment by marusak** [comment]
> Is it documented somewhere that these additional packages need to be installed or even exist?

I am afraid not. The list of packages is depended on your system and what is released where.

> The install instructions for your supported OS'es say nothing about them, where they are located, or how to install them.

Majority of them are directly in cockpit (https://github.com/cockpit-project/cockpit/tree/master/pkg). These you build with instructions linked above (using those build instructions builds all of them at once). Others are just on other places and they should have their own README/HACKING. For example `cockpit-podman` is [here](https://github.com/cockpit-project/cockpit-podman)

**Comment by TheEagle13** [comment]
Thank you for that, and sorry for being frustrated earlier.. I was running on a lack of sleep. Now with some much needed sleep I am running though the build again...
I am currently getting hung up on the following issue when I `./autogen.sh --prefix=/usr --enable-debug`:

```
checking for krb5-config... no
checking for working krb5-config... configure: error: no. Please install MIT kerberos devel package
```
I have krb5-config installed... It's currently at the following path:
`/usr/lib/mit/bin/krb5-config` but I can't seem to figure out what is looking for it or how to tell it the path.

**Comment by TheEagle13** [comment]
OK, I proceeded with the `--disable-pcp` option, and it installed and appears to be working. I do have one final question. How can I configure advanced options of a VM after creating (or during creation) such as choosing the network to connect to, additional passthrough devices, etc.
Thanks!

**Comment by martinpitt** [comment]
@TheEagle13 : Nice! I'm afraid these advanced VM operations -- at least passthrough devices -- are not currently possible. But the Machines page gets improvements pretty much every release, and at least network selection is on the plan already.

**Comment by John-Vacacela** [comment]
Maybe someone could help with this problem? 
![imagen_2024-05-31_213704673](https://github.com/cockpit-project/cockpit/assets/134348747/5e9ca15b-6f76-433d-8b9a-ef7cd8e43f92)

**Comment by Don-Swanson** [comment]
@John-Vacacela 
Maybe you should open a new issue that's related to your problem. I don't see anything related to this issue.

**Comment by John-Vacacela** [comment]
> @John-Vacacela Maybe you should open a new issue that's related to your problem. I don't see anything related to this issue.

At the time of doing the make, all the configuration comes out correct, what I did was change the folder, but now I get this:
![image](https://github.com/cockpit-project/cockpit/assets/134348747/c57a40b5-4cc7-46f4-aa40-3866222fce25)

**Comment by Don-Swanson** [comment]
Again, @John-Vacacela 
You need to open a new issue as your problems have nothing to do with this issue. (Plus this issue is 5 years old.)
