### ISSUE TITLE
Cockpit removes all services from firewall when adding a new service

### ISSUE THREAD

**Issue by rahbcca** [cockpit-project/cockpit#12195]
Cockpit version: 196
OS: Fedora 30 Server
Page: Network-->Firewall

All services( except newly added service ) are removed when a new service is added. This left me with only oVirt Image I/O as an allowed service. This service was not present prior to transaction nor was it selected to be activated. 

Steps to reproduce

1.Select Networking -->Firewall
2.Choose Add Services
3.Choose Service and click Add Service. When returned to Firewall page, all prior services are gone. INCLUDING SSH!! This is a headless system!! I can no longer ssh into machine. Not Good.

**Comment by Gundersanne** [comment]
Thank you for reporting. #12254 is in the works. Currently the firewall page reloads firewalld and will remove all runtime configurations, the permanent configurations however will remain.

**Comment by marusak** [comment]
@Gundersanne was this fixed in #12254 ?

**Comment by Gundersanne** [comment]
@marusak This should be fixed yes! :) Closing this.
