### ISSUE TITLE
Add help or man page cockpit

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1220]
We have man pages for various cockpit components like cockpit-ws and cockpitd, but we should also have a cockpit(8) manual page so curious people can be introduced to cockpit concepts. 

This is especially for administrators who want to understand the assumptions made by cockpit in certain areas, eg: security, privileges, sessions, etc...

**Comment by dperpeet** [comment]
@stefwalter are there easy options to compile some of the doc we have for this?
