### ISSUE TITLE
Adjust various widgets better align to PF4 (follow-up)

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#12210]
On the heels of the PF4ish PR landing (#11987), there are a few issues that should probably be resolved:

- [x] Kebab menus should be styled differently for Composer (https://github.com/weldr/cockpit-composer/pull/700#issuecomment-507708354)
- [x] Shell menu dropdown should be styled differently
- [x] Navigation styling was based on a buggy version of PF4 navigation; since then, PF4 fixed the bug and our navigation styling should be adjusted
- [x] Tabs should have a blue line at the top (this affects Dashboard & Composer)
- [x] Fix button border color
- [x] Fix primary button hover color changing (regression due to changing a little too much for the above button border color — oops!)
- [x] Host switcher arrow is missing interior arrow
- [x] Host switcher menu needs updated colors
- [x] List view icon circle isn't sized right relative to the icon (see https://github.com/weldr/cockpit-composer/pull/700#issuecomment-508108085)
- [x] Selected items in dropdowns have a blue background and black text; this affects Composer
- [ ] Mobile nav menu (three line thing on the right) should be restyled to a lighter background (same widget as the above issue, but both need to be treated differently)
- [ ] Lists could be better styled (this is _optional_; it looks a little odd to me to have 2 blue lines — should work with @andreasn on this one)

Compatibility:
- [x] Edge: Accounts cards in are broken
- [x] Chrome, Edge, WebKit: Left-highlighting expanded list items escape the list boundary (it seems WebKit doesn't support position for `tbody`?)

Anything else? Please add bugs & minor tweaks needed here.

**Comment by andreasn** [comment]
One thing I ran into was that buttons change color on hover, even though the [design docs](https://www.patternfly.org/v4/documentation/react/components/button/) specify they should only change border width.

Ours on top, PF4 on bottom.
![Screenshot from 2019-07-03 14-00-09](https://user-images.githubusercontent.com/209895/60590458-4d5e5e80-9d9c-11e9-80c4-12b5e155ef89.png)

**Comment by garrett** [comment]
@andreasn: ...but PF4 buttons change color on hover too?

However, that said, is our button hover blue the correct shade of blue?

**Comment by garrett** [comment]
The buttons don't change color on hover. They were using the wrong color for the outside border. I've fixed the color acordingly.

**Comment by garrett** [comment]
In fixing the standard buttons, I accidentally made a regression for the primary buttons. I changed the colors a little too much. Oops. :smirk_cat: 

- [ ] Fix primary button hover color changing
