### ISSUE TITLE
System: Cockpit slow permission detection in UI

### ISSUE THREAD

**Issue by andrew89898** [cockpit-project/cockpit#12242]
Cockpit version: 173.2
OS: Red Hat Enterprise Linux Version 7
Page: System (Any page on initial load)

After logging into a fresh session of cockpit as a non-wheel user, all actions/buttons requiring privileges are not disabled for up to a few seconds. This allows users to attempt the action before being denied. 

Steps to reproduce

1. Find a slow system if you want exaggerate the issue.
2. Log into cockpit as non-wheel user.
3. Try to use 'Restart' button on system page straight away.

Issue also observed on cockpit 192 fedora 30 on faster system but delay is much less.

**Comment by martinpitt** [comment]
This is still the case in current versions. On other pages, like storage, it's okay. So two things:

 - figure out why it takes so long, and
 - start with a disabled button, and enable it if permissions allow it

**Comment by mvollmer** [comment]
> This is still the case in current versions. On other pages, like storage, it's okay. So two things:
> 
>     * figure out why it takes so long, and
> 
>     * start with a disabled button, and enable it if permissions allow it

I ran into this while working on #13222.

It takes so long because it takes a long time for sudo to fail.  Sudo will ask three times for a password, and sleep a bit in between.
