### ISSUE TITLE
accounts: Tooltips are not properly dismissed

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#12262]
1. Visit the accounts page
2. Click on an account
3. Hover over something which shows a tooltip
4. Go back to the main accounts page

It doesn't _always_ happen, but it does often happen.

![Screenshot_2019-07-09 Accounts - Sunny](https://user-images.githubusercontent.com/10246/60875555-694d7e80-a23a-11e9-98c7-c0bc31b43640.png)

![Screenshot_2019-07-09 Accounts - Sunny(1)](https://user-images.githubusercontent.com/10246/60875567-6ce10580-a23a-11e9-814d-89b7cc023631.png)

**Comment by marusak** [comment]
Just worth mentioning how to reproduce this - you need to click on the field that has popup (like clicking on `Server Administrator`), just hovering did not work for me.
