### ISSUE TITLE
NFS Widget missing when connecting to remote cockpit

### ISSUE THREAD

**Issue by Ussat** [cockpit-project/cockpit#12268]
Cockpit version: Version 176.
OS: CentOS Linux release 7.6.1810 (Core)

Page:  Storage

When connecting directly to cockpit on this server, in the storage section, NFS option is available and visible. 

BUT

When I add the Centos system to a REMOTE  cockpit, looking at the same storage section, NFS is not visible or available.

Steps to reproduce

1. Build Centos7 VM
2.Enable Cockpit on this server
     A. sudo yum -y install cockpit
     B. sudo yum -y install cockpit-storaged
     C. sudo systemctl enable --now cockpit.socket
3. Goto htps://centos_server:9090
4. Goto storage section, verify NFS is available.
5. Now ad same server to remote cockpit server, goto storage and NFS is NOT available.

Attaching screenshots.

<img width="1432" alt="Storage_- on local server" src="https://user-images.githubusercontent.com/52705308/60889926-c425ac80-a21f-11e9-9d5a-42c49436cb3d.png">
<img width="1442" alt="Storage_- on remote server-2" src="https://user-images.githubusercontent.com/52705308/60889932-c6880680-a21f-11e9-8469-54fb8e7dc257.png">

**Comment by marusak** [comment]
This is very likely the same cause as in #9379

**Comment by Ussat** [comment]
I dont think so, I have it working on Ubuntu just fine, and it works on Cent/RHEL fine as long as I connect to the local cockpit, but not if I attach the system to a remote cockpit.

**Comment by marusak** [comment]
Have you also tried attaching from local centos cockpit to ubuntu?

**Comment by Ussat** [comment]
Local Centos NFS available
Local Ubuntu NFS available
Local Centos Remote Ubuntu NO NFS
Local Centos Remote Centos NO NFS
Local Ubuntu Remote Centos NO NFS
Local Ubuntu Remote Ubuntu YES NFS

**Comment by mvollmer** [comment]
I can reproduce this.  When going via SSH to another machine as non-root from CentOS, the $PATH that ends up being used during the check for `mount.nfs` ends up being `/usr/local/bin:/usr/bin` while mount.nfs is in `/usr/sbin`.
