### ISSUE TITLE
firewall: add some help for the format of source addresses in the AddZone dialog

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#12280]
Page: firewall

Some inline help or examples for the format of Allowed Addresses: Range.

**Comment by andreasn** [comment]
This also came up in the July usability tests.

Frequency: 44.44%
Severity: 3/5

**Comment by andreasn** [comment]
Some quotes from the study:

_It's weird that I can only pick the entire subnet or the range.
Pretty confusing, not sure I did that right.
Range implies that it would only accept 192.168.1.0-192.168.1.255 etc.
What if you have several subnets?_

_The (*) in IP range is confusing and needs description._

_This doesn’t specify the interface, so I’ll leave that, but I have to have it so go ahead and select virbr0_

_"Not comfortable" with entire subnet option._
