### ISSUE TITLE
No ability to edit firewall services

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#12287]
Cockpit version: 197
OS: Fedora Server 30
Page: Network > Firewall

In the usability test we ran now in July with 9 participants, 8 out of 9 participants wanted to be able to edit a Firewall service without having have to delete and creating a new one.

Frequency: 88,89%
Severity: 5/5

**Comment by garrett** [comment]
Edit should only apply to custom services, and it should only show the custom port part of the dialog when the service is being edited.

The reason why editing was wanted in the usability test was to add the service to multiple locations.

In the new design in #12288, this functionality would be provided by a context menu: "Copy to ZONE_NAME_HERE" (with a new entry for each of the other zones).

You can see the edit button for the "something-else" service and the context menu in the mockup:
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/firewall/firewall-zones-reorganization.png)

We also talked about the possibility of having "move" items as well, but it's an uncommon occurrence to move a service from one zone to another, so we decided against it. (This functionality could be achieved by copying the service and removing the original. Adding one service to multiple zones should be much more common than reassigning it.)
