### ISSUE TITLE
firewall: Adding a zone which does not include cockpit by default could break cockpit

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#12281]
Adding a zone which applies to the connection over which the user is currently using cockpit, which does not allow the cockpit service by default, results in the cockpit page becoming unreachable.

Solution would be to include it automatically? Or maybe a checkbox "Include cockpit in this zone" which would be on by default?

**Comment by garrett** [comment]
Oh, this is a tricky one.

I'd rather have an info message than a checkbox in this case... if I understand this correctly.

So... adding the zone without adding Cockpit to the zone for the current connection would break the usage of Cockpit, right? I think we need to force the addition of Cockpit in this case. Someone's using Cockpit already and don't want to stop using it. (This would be a really odd way to do so.) And as it's doing something the user did not ask for, we need to inform them before doing so (similar to your checkbox option, but without giving the user a chance to effectively break their system).

At least, that's what I'm thinking... which is basically a hybrid between your two suggestions, I think?

**Comment by Gundersanne** [comment]
So the problem as well is that we don't really know what connection is currently being used to access the machine over. So we don't know when to force adding cockpit and when it might not be desirable.

Like if someone is setting up a dmz they probably do not want to expose cockpit by default.

**Comment by garrett** [comment]
Oh. I see.

Yeah, then I guess your suggestion about the checkbox makes the most sense!

One issue: We shouldn't use the word "Cockpit", I guess. However, the firewall does use "Cockpit" as the service name already, doesn't it?

**Comment by Gundersanne** [comment]
Yup, that's the firewall service name for cockpit :/

**Comment by martinpitt** [comment]
As a random data point, on the [Software Updates](https://github.com/cockpit-project/cockpit/blob/80c858f3ce66b6335ed66c4311c8c13f35b89872/pkg/packagekit/updates.jsx#L832) page we use "This web console will be updated." when cockpit gets updated and thus there will be a disconnect on the page.

**Comment by garrett** [comment]
I wonder if we can change the service name and/or have a workaround.

Perhaps something like: "Web Console (Cockpit)" or "Cockpit Web Console" for the service name. I think, in this case, we kind of need Cockpit still, as that's the service name.

**Comment by marusak** [comment]
@Gundersanne was this implemented by https://github.com/cockpit-project/cockpit/pull/13054 ?

**Comment by martinpitt** [comment]
Indeed it was!
