### ISSUE TITLE
Firewall: The association between Services and Zones in Firewall seems to be unclear

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#12288]
Cockpit version: 197
OS: Fedora Server 30
Page: Network > Firewall

In the usability test we ran now in July with 9 participants, 6 out of 9 participants felt the association between Services and Zones in Firewall seems to be unclear.
Some participants wanted to be able to modify Zone related details where they found Services

Frequency: 66.67%
Severity: 5/5

**Comment by andreasn** [comment]
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/b1e70c812f4fed5e36cb9097143d8b15ac9ab985/firewall/firewall-zones-reorganization.png)

**Comment by andreasn** [comment]
This design puts the services as children of the zones, instead of the other way around.

**Comment by garrett** [comment]
I switched the mockup above to hotlink to the live version from our design repo, so it should always be up-to-date (in case we make further changes)

It has been modified based on what @Gundersanne, @andreasn, and I talked about at the hackfest, with @andreasn's initial sketch, and I added additional modifications on top.

This design would require us to adjust the dialogs as well — but the biggest change would probably be the removal of zones in the dialog. (However, it should probably still show the zone somewhare, like in the title: "Add service to Internal Zone".)

**Comment by andreasn** [comment]
Updated the mockup to only focus on reorganizing the relation between zones and services.
Removed any additional functionality, that we can track in separate issues once the basic groundwork is done. 

![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/f9fdfdb1cb6d8f14efa1174d434314225e3acd92/firewall/firewall-zones-reorganization.png)

**Comment by marusak** [comment]
This was implemented in #12884
