### ISSUE TITLE
selinux: Infinite spinner on system modifications

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#12284]
System modifications never shows up properly. I just get an infinite spinner.

![Screenshot_2019-07-10 SELinux - Sunny(1)](https://user-images.githubusercontent.com/10246/60963252-93717000-a310-11e9-83e9-0e71ddff57b6.png)

It _might_ be related to this weird error message at the top of the page:

![Screenshot_2019-07-10 SELinux - Sunny(2)](https://user-images.githubusercontent.com/10246/60963293-ad12b780-a310-11e9-98cf-cca9a4dd8370.png)

**Comment by marusak** [comment]
Hmm, the error could be related (although I don't know what it means).
What is your version of `policycoreutils-python-utils`? (It seems like it provides `semanage`).
What is output of `semanage export` and of  `semanage boolean --list -C --noheading`?

**Comment by garrett** [comment]
policycoreutils-python-utils-2.9-1.fc30.noarch

```
semanage export
sh: semanage: command not found...
Install package 'policycoreutils-python-utils' to provide command 'semanage'? [N/y]

 * Waiting in queue... 
 * Loading list of packages.... 
 * Downloading details about the software repositories.... 
 * Loading list of packages.... 
 * Downloading details about the software repositories.... 
 * Loading list of packages.... Failed to install packages: policycoreutils-python-utils-2.9-1.fc30.noarch is already installed
```

Uh... :astonished:

**Comment by garrett** [comment]
I reinstalled it and it still doesn't provide semanage here... on Fedora 30, BTW.

**Comment by garrett** [comment]
Aha. I don't have /usr/sbin/ in my path, apparently.

Here's the output of `sudo /usr/sbin/semanage export`:

```
boolean -D
login -D
interface -D
user -D
port -D
node -D
fcontext -D
module -D
ibendport -D
ibpkey -D
fcontext -a -f a -t cupsd_rw_etc_t -r 's0' '/etc/opt/brother/Printers/MFCL2750DW/inf(/.*)?'
fcontext -a -f a -t bin_t -r 's0' '/opt/brother/Printers/MFCL2750DW/cupswrapper(/.*)?'
fcontext -a -f a -t cupsd_rw_etc_t -r 's0' '/opt/brother/Printers/MFCL2750DW/inf(/.*)?'
fcontext -a -f a -t bin_t -r 's0' '/opt/brother/Printers/MFCL2750DW/lpd(/.*)?'
fcontext -a -f a -t chrome_sandbox_exec_t -r 's0' '/usr/lib/chrome-sandbox'
fcontext -a -f a -t bin_t -r 's0' '/usr/lib/chromium-browser'
fcontext -a -f a -t bin_t -r 's0' '/usr/lib/chromium-browser/chromium-browser.sh'
libsemanage.semanage_direct_get_module_info: Unable to read pcpupstream module lang ext file.
OSError: [Errno 0] Error
```

`sudo /usr/sbin/semanage boolean --list -C --noheading` returns nothing.

**Comment by marusak** [comment]
Eh, so it seems that something on your machine is broken. What is return code of `sudo /usr/sbin/semanage export`? Is it different from 0?

**Comment by garrett** [comment]
I mentioned in IRC yesterday that it fails (even though it exports the data). Here's output to prove it:

```
~ $ sudo /usr/sbin/semanage export && echo "SUCCESS" || echo "FAIL"
boolean -D
login -D
interface -D
user -D
port -D
node -D
fcontext -D
module -D
ibendport -D
ibpkey -D
fcontext -a -f a -t cupsd_rw_etc_t -r 's0' '/etc/opt/brother/Printers/MFCL2750DW/inf(/.*)?'
fcontext -a -f a -t bin_t -r 's0' '/opt/brother/Printers/MFCL2750DW/cupswrapper(/.*)?'
fcontext -a -f a -t cupsd_rw_etc_t -r 's0' '/opt/brother/Printers/MFCL2750DW/inf(/.*)?'
fcontext -a -f a -t bin_t -r 's0' '/opt/brother/Printers/MFCL2750DW/lpd(/.*)?'
fcontext -a -f a -t chrome_sandbox_exec_t -r 's0' '/usr/lib/chrome-sandbox'
fcontext -a -f a -t bin_t -r 's0' '/usr/lib/chromium-browser'
fcontext -a -f a -t bin_t -r 's0' '/usr/lib/chromium-browser/chromium-browser.sh'
libsemanage.semanage_direct_get_module_info: Unable to read pcpupstream module lang ext file.
OSError: [Errno 0] Error
FAIL
```

**Comment by garrett** [comment]
I tried reinstalling everything pcp with:

```sh
sudo dnf reinstall "*pcp*"
```

...but it didn't work. Same error.

**Comment by garrett** [comment]
I just uninstalled everything related to pcp. It still fails with the same error. Perhaps I should reboot to be sure.
