### ISSUE TITLE
Implement Guacamole for GUI support

### ISSUE THREAD

**Issue by superswan** [cockpit-project/cockpit#12293]
Implement Guacamole in order to start a VNC session while in the Cockpit UI.

**Comment by marusak** [comment]
Can you explain in more details what you mean?
Cockpit is not a VNC session (although it can access vnc console for virtual machines).
Cockpit is a web-based interface for (mostly) servers.

**Comment by marusak** [comment]
@superswan

**Comment by superswan** [comment]
I see that the ability to access a vnc console is available under the "Virtual Machines" tab on the sidebar. Apologies.
