### ISSUE TITLE
storage: the 'Default' mounting option in volume formatting dialog is confusing

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#12295]
Cockpit version: 197
OS: Fedora Server 30
Page: Storage

In the July usability test it became apparent that the mount option labeled Default was problematic. Almost all participant was unsure what selecting Default would result in and wished more information of what mount point it would result in. Some guessed it would be connected to the mount name, but none of them anticipated it would mount to /media/run/..

**Comment by andreasn** [comment]
Frequency: 44.44%
Severity: 4/5

**Comment by andreasn** [comment]
Can we figure out the default value here?
What about something like this in the dropdown:
`Default - /media/run/..`

@martinpitt suggested doing away with Default and defaulting to custom as the only option, as he felt the default is good for transient devices, such as a USB stick that you plug in to a laptop, but less useful for something like a hard drive that you plug in and that will remain plugged in for years.
I think that could also make sense.

**Comment by andreasn** [comment]
Here is a mockup of a new dialog with the ability to set Default or Custom removed.

![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/6b3bf668e3ab1045a21b0daa6e2c3abb2ba13c3c/storage/format-dialog.png)

**Comment by martinpitt** [comment]
This got fixed in #12647
