### ISSUE TITLE
About latest release

### ISSUE THREAD

**Issue by tp3rson** [cockpit-project/cockpit#12291]
How soon latest release come to debian?

**Comment by andreasn** [comment]
That depends on what version of Debian you're running.
Version 198 released today is in _Debian Unstable_, version 197 in in _Debian Experimental_
Check out the [Debian Tracker](https://tracker.debian.org/pkg/cockpit) for more details.

**Comment by martinpitt** [comment]
.. and once it migrates to testing, I'll backport it to buster (Debian 10). But that will still be a while, testing migration isn't on yet again due to the recent release.
