### ISSUE TITLE
storage: easy to miss the mounting step after formatting a filesystem

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#12303]
Cockpit version: 197
OS: Fedora 30 Server
Page: Storage

In the usability test we ran now in July with 9 participants, when asked to format, encrypt and mount a device, many participants missed to complete the last step for some reason.
Not sure if it had to do with the fact that you set the mount point in the dialog, and that the Format button is expected to carry that out for you. But one of the comments from a participant points in that direction.
_I expected it to automount it after formatting._

Frequency: 44.44%
Severity: 4/5

A bit of caution though, one of the participant said that _auto-mounting is not ok from a sys admin perspective_. So we can't do that as a solution.

**Comment by martinpitt** [comment]
@andreasn, @mvollmer: PR #12647 worked towards, that -- do you think it's good enough now, or can this be closed?

**Comment by KKoukiou** [comment]
This is pretty antique and everyone seemed happy with the format dialog since last time Marius improved it. I will close it and if new usability study proves otherwise we can reopen and reconsider the missing dialog feedback to the user.
