### ISSUE TITLE
firewall: a little unclear what the role of selecting interface is

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#12307]
Cockpit version: 197
OS: Fedora Server 30
Page: Network > Firewall

In the usability test we ran now in July with 9 participants, it became apparent that it's not always super clear what adding an interface to a zone means.
Only one 1 out of 9 participants ran into this, but it got marked with Severity 3, so I thought I might as well file it as an issue.

**Quote from participant 2:** _Is it exclusive to that interface in that zone?_

Frequency: 11.11%
Severity: 3/5

**Comment by andreasn** [comment]
I'm uncertain myself of the effect actually. Does not checking it means it will apply to all interfaces? Maybe we should make that a selection?
```
(o) Apply to all interfaces  ( ) Apply to selected interfaces
[x] eth0  [ ] eth1
```

**Comment by KKoukiou** [comment]
Let's add some inline documentation here.

**Comment by marusak** [comment]
see comments in #17103
