### ISSUE TITLE
Indicate encryption password as mandatory?

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#12308]
Page: Storage

In the usability test we ran now in July with 9 participants, 2 out of 9 participants wanted some indication that the password field is mandatory when creating an encrypted filesystem.

Frequency: 22.22%
Severity: 3/5

**Comment by marusak** [comment]
Now when you want to create encrypted filesystem you need to check "Encrypt data" which will then open submenu with password. I think that is clear enough that one needs to specify it. If you don't fill it up then you cannot submit the dialog (and get error saying that password cannot be empty).

This was changed in https://github.com/cockpit-project/cockpit/pull/11712 . Before that these fields were always shown and it was indeed not obvious.
