### ISSUE TITLE
The shutdown option is not visible on the mobile view

### ISSUE THREAD

**Issue by pitsi** [cockpit-project/cockpit#12309]
Cockpit version: 198
OS: Debian unstable 
Page: System

Issue description
Similar to issue #9851 I reported last year, but now only the shutdown option is not visible when you login via mobile portrait view. Actually, It is now covered by the cpu usage graph

Steps to reproduce
1. Install cockpit 198.
2. Login to it, preferably as root.
3. Tap the restart/shutdown dropdown box

Screenshot
![Screenshot_20190712-124133](https://user-images.githubusercontent.com/5880037/61119709-1e36a400-a4a4-11e9-826f-0c64c37e0684.png)

Thank you in advance

**Comment by andreasn** [comment]
Might be a z-index thing. Could also be fixed by porting to a native dropdown, as that would result in something [more like this](https://i.stack.imgur.com/dgV97.png)
Assigning to @garrett who would know what's up here.

**Comment by garrett** [comment]
@pitsi: Thanks for the bug report!

It's either `z-index` or `overflow` set to hidden or auto. I'll check it out this upcoming week. It should be super-simple to fix.  :four_leaf_clover::crossed_fingers:

**Comment by garrett** [comment]
@pitsi: Thanks again! :+1: It's been fixed.

It was due to using `overflow: hidden`. Thankfully removing the one line of CSS here was a simple fix (as we don't have to contain floated elements here anymore).
