### ISSUE TITLE
Wrong german translation for RAID devices

### ISSUE THREAD

**Issue by woraab** [cockpit-project/cockpit#12339]
Cockpit version: 195
OS: all
Page: "RAID-Geräte" (RAID-devices)

A better translation will be the following:

RAID 0 (verteilt)
RAID 1 (gespiegelt)
RAID 4 (verteilt Daten, feste Parität)
RAID 5 (verteilt Daten, verteilte Parität)
RAID 10 (verteilt und gespiegelt)

"Happengröße" is the german IT-equivalent to "Blockgröße".

If you like you can verify this on https://de.wikipedia.org/wiki/RAID

Best regards

woraab

**Comment by marusak** [comment]
Thank you for the report. We have a few native German speakers who can edit this in Zanata.
For example, @stefanleh would you be interested in fixing this?

**Comment by stefanleh** [comment]
RAID 0 (verteilt)
RAID 1 (gespiegelt)
RAID 10 (verteilt & gespiegelt)
RAID 4 (verteilte Daten & feste Parität)
RAID 5 (verteilte Daten & verteilte Parität)
RAID 6 (verteilte Daten & doppelt verteilte Parität)

**Comment by stefanleh** [comment]
Hope you are fine with my little modifications. Greetings Stefan

**Comment by woraab** [comment]
Perfekt !! :-)

**Comment by marusak** [comment]
Thank you! :)
