### ISSUE TITLE
CentOS 7.x no longer gets Cockpit-Preview builds

### ISSUE THREAD

**Issue by PeterFalken** [cockpit-project/cockpit#12334]
Cockpit version: 196+
OS: CentOS 7.6
Page: Cockpit

CentOS 7.x no longer gets Cockpit-Preview builds from Fedora COPR.
The repo is no longer available on the COPR website - it seems that support for EPEL7 has been  removed.

**Comment by marusak** [comment]
Right, CentOS7 (and RHEL7) has been dowstreamed, so it is not getting all updates from master, but only some patches are backported. Copr preview repo builds current master.
This change is intentional.
