### ISSUE TITLE
wrong SSH keys

### ISSUE THREAD

**Issue by blub4747** [cockpit-project/cockpit#12340]
Hi guys,

How can I please readd a host to cockpit which has been rebuilt?

If I do try to readd a host I do get error message telling me that the ssh keys to not match.

Thank you, blub4747

**Comment by marusak** [comment]
Can you please specify more closely what are you trying to do? What has been rebuild?  Adding another server through dashboard or connecting directly to cockpit?

**Comment by blub4747** [comment]
Let's say I have cockpit installed on fan less low power pc with the IP address 123 and also raspberry pi with the IP address 234.

Since the new version of raspbian has just been released I decided to 'rebuilt the image on the SD card.

If I than open the dashboard on the fan less pc with ip address 123 and there try to add the raspberry with IP address 234. That is when I get a error msg notifying that the SSH keys or fingerprint do not match anymore.

**Comment by Gundersanne** [comment]
If rebuilding the image results in different host keys, then indeed you'd get that error.

You can get around this by removing the host from your known_host file on the machine you're trying to connect from (so in your example the lowerpowerpc). This file is probably `~/.ssh/known_hosts`; or older versions of cockpit also use `/var/lib/cockpit/known_hosts`. There's no UI for the known_hosts files in cockpit.
