### ISSUE TITLE
Software Updates: 'not registered' on CentOS systems

### ISSUE THREAD

**Issue by shawnweeks** [cockpit-project/cockpit#12359]
Cockpit version: 176-4.el7.centos
OS:7.6.1810
Page: Software Update

It appears the CentOS 7.6.1810 does not resolve issue #9193.

`[sweeks@jb ~]$ yum list installed cockpit*
Loaded plugins: fastestmirror, langpacks, product-id, search-disabled-repos
Loading mirror speeds from cached hostfile
 * base: mirror.millry.co
 * epel: mirror.math.princeton.edu
 * extras: ftp.usf.edu
 * updates: ftp.usf.edu
Installed Packages
cockpit.x86_64                                                                                 176-4.el7.centos                                                                       @extras
cockpit-bridge.x86_64                                                                          176-4.el7.centos                                                                       @extras
cockpit-dashboard.x86_64                                                                       176-4.el7.centos                                                                       @extras
cockpit-doc.x86_64                                                                             176-4.el7.centos                                                                       @extras
cockpit-docker.x86_64                                                                          176-4.el7.centos                                                                       @extras
cockpit-machines.x86_64                                                                        176-4.el7.centos                                                                       @extras
cockpit-packagekit.x86_64                                                                      176-4.el7.centos                                                                       @extras
cockpit-pcp.x86_64                                                                             176-4.el7.centos                                                                       @extras
cockpit-storaged.noarch                                                                        176-4.el7.centos                                                                       @extras
cockpit-system.noarch                                                                          176-4.el7.centos                                                                       @extras
cockpit-ws.x86_64                                                                              176-4.el7.centos                                                                       @extras`

**Comment by shawnweeks** [comment]
<img width="760" alt="Screen Shot 2019-07-18 at 10 45 07 AM" src="https://user-images.githubusercontent.com/9768773/61472134-76a8ee00-a949-11e9-878b-ae436ca4ce7e.png">

**Comment by shawnweeks** [comment]
This may not be the exact same issue. It appears that you will get this failure if subscription-manager is even installed and there are some other packages on my system that are requiring it. Yum update works normally without complaining but Cockpit insists that it must be registered.

**Comment by martinpitt** [comment]
Indeed the fix was to not depend on subscription-manager, so if you can remove it, please do so. It's rather worthless on all  but RHEL systems anyway. On RHEL we definitively don't want to ignore subscription-manager, so this is tricky to fix. We could check /etc/os-release, but I'm not sure if we can rely on `ID="rhel"` on all RHEL derived products.

**Comment by shawnweeks** [comment]
My problem has been some other projects like ovirt force the install anyway. Could it not check to see if subscription manager is enabled by looking in /etc/yum/pluginconf.d/subscription-manager.conf?

**Comment by martinpitt** [comment]
That's a nice idea!

**Comment by martinpitt** [comment]
Sent PR #12424 to implement that.
