### ISSUE TITLE
Performance graphs never show historic data

### ISSUE THREAD

**Issue by Taomyn** [cockpit-project/cockpit#12365]
Cockpit version: 198
OS: Fedora 30 Server
Page: System, Dashboard

The performance graphs never shows me any data beyond the most recent since a reboot or the start of a Cockpit session. Sometimes nothing.

Fedora is suffering with the issue "pmlogger.service: New main PID 98612 does not belong to service, and PID file is not owned by root. Refusing." which I understand is reported to Red Hat, but someone at Red Hat did confirm my system is storing historical data:

> Hi Fernando, I examined your PCP logs (in the rar file), and you have data
> from June 30
> through to today, July 15. That's the default 2 weeks retention. So I'm not
> sure what you
> mean that PCP isn't saving more than one day (?)
> 
> Regards
> -- Mark
> 

Steps to reproduce

1. View a graph
2.  Choose anything beyond an hour
3.

![Clipboard01](https://user-images.githubusercontent.com/4365929/61518908-f77bee80-aa0a-11e9-9a00-8029fed6a591.png)
![Clipboard02](https://user-images.githubusercontent.com/4365929/61518920-fba80c00-aa0a-11e9-92f9-428a1c909a02.png)

**Comment by banana-ben** [comment]
I am having the same/similar issue on my Fedora 30 server that I haven’t yet looked into but have been meaning to report. My Cockpit install on my Ubuntu 19.04 server displays historical data properly.

**Comment by jankais3r** [comment]
Same issue on Raspbian Buster. Cockpit version 198. PCP installed and running, but dashboard is not showing any historical values. Happy to help with debugging, I'll be waiting for instructions.

**Comment by mvollmer** [comment]
The thing that is responsible of collecting the data is the `pmlogger` of pcp, together with `pmcd`. 

I have a hunch that pmlogger might have started compressing archives with XZ by default "recently" (i.e., in the last few years), and that Cockpit can't read those compressed archives.  With default settings, that would probably mean that Cockpit only shows data from the most recent archive.

I will have a closer look.

(I have tried simply uncompressing my archive files, but that just causes _all_ historic data to disappear from Cockpit... *sigh*, this is not my favorite corner of the code... :-)

In general, please check the following to debug pcp archiving:
```
systemctl status pmlogger
systemctl status pmcd
/usr/share/pcp/lib/pmlogger status
/usr/share/pcp/lib/pmcd status
cat /var/log/pcp/pmlogger/$(hostname)/pmlogger.log
cat /var/log/pcp/pmlogger/pmlogger_check.log
cat /var/log/pcp/pmlogger/pmlogger_daily-K.log
```

**Comment by Taomyn** [comment]
@mvollmer attached is what was returned for my system, hope it helps.

[pcp-debug.txt](https://github.com/cockpit-project/cockpit/files/3434746/pcp-debug.txt)

**Comment by mvollmer** [comment]
> @mvollmer attached is what was returned for my system, hope it helps.
> 
> [pcp-debug.txt](https://github.com/cockpit-project/cockpit/files/3434746/pcp-debug.txt)

Thanks, everything looks good.

Could you also show `ls -l /var/log/pcp/pmlogger/$(hostname)`?  This is to see what kind of archives you actually have.

**Comment by Taomyn** [comment]
```
[root@MAGGIE ~]# ls -l /var/log/pcp/pmlogger/$(hostname)
total 51424
-rw-r--r--. 1 pcp pcp  1088060 Jul 11 00:10 20190710.0.xz
-rw-r--r--. 1 pcp pcp    11692 Jul 11 00:10 20190710.index
-rw-r--r--. 1 pcp pcp    69432 Jul 11 00:10 20190710.meta.xz
-rw-r--r--. 1 pcp pcp  1076380 Jul 12 00:10 20190711.0.xz
-rw-r--r--. 1 pcp pcp    11852 Jul 12 00:10 20190711.index
-rw-r--r--. 1 pcp pcp    63120 Jul 12 00:10 20190711.meta.xz
-rw-r--r--. 1 pcp pcp  1098276 Jul 13 00:10 20190712.0.xz
-rw-r--r--. 1 pcp pcp    11852 Jul 13 00:10 20190712.index
-rw-r--r--. 1 pcp pcp    63932 Jul 13 00:10 20190712.meta.xz
-rw-r--r--. 1 pcp pcp  1079152 Jul 14 00:10 20190713.0.xz
-rw-r--r--. 1 pcp pcp    11852 Jul 14 00:10 20190713.index
-rw-r--r--. 1 pcp pcp    66276 Jul 14 00:10 20190713.meta.xz
-rw-r--r--. 1 pcp pcp  1082184 Jul 15 00:10 20190714.0.xz
-rw-r--r--. 1 pcp pcp    11852 Jul 15 00:10 20190714.index
-rw-r--r--. 1 pcp pcp    67484 Jul 15 00:10 20190714.meta.xz
-rw-r--r--. 1 pcp pcp  1169296 Jul 16 00:10 20190715.0.xz
-rw-r--r--. 1 pcp pcp    12572 Jul 16 00:10 20190715.index
-rw-r--r--. 1 pcp pcp    75216 Jul 16 00:10 20190715.meta.xz
-rw-r--r--. 1 pcp pcp  1107200 Jul 17 00:10 20190716.0.xz
-rw-r--r--. 1 pcp pcp    11932 Jul 17 00:10 20190716.index
-rw-r--r--. 1 pcp pcp    68080 Jul 17 00:10 20190716.meta.xz
-rw-r--r--. 1 pcp pcp  1129136 Jul 18 00:10 20190717.0.xz
-rw-r--r--. 1 pcp pcp    11852 Jul 18 00:10 20190717.index
-rw-r--r--. 1 pcp pcp    64380 Jul 18 00:10 20190717.meta.xz
-rw-r--r--. 1 pcp pcp  1229496 Jul 19 00:10 20190718.0.xz
-rw-r--r--. 1 pcp pcp    12632 Jul 19 00:10 20190718.index
-rw-r--r--. 1 pcp pcp    76772 Jul 19 00:10 20190718.meta.xz
-rw-r--r--. 1 pcp pcp  1177680 Jul 20 00:10 20190719.0.xz
-rw-r--r--. 1 pcp pcp    12212 Jul 20 00:10 20190719.index
-rw-r--r--. 1 pcp pcp    79836 Jul 20 00:10 20190719.meta.xz
-rw-r--r--. 1 pcp pcp  1096728 Jul 21 00:10 20190720.0.xz
-rw-r--r--. 1 pcp pcp    11852 Jul 21 00:10 20190720.index
-rw-r--r--. 1 pcp pcp    63128 Jul 21 00:10 20190720.meta.xz
-rw-r--r--. 1 pcp pcp  1088008 Jul 22 00:10 20190721.0.xz
-rw-r--r--. 1 pcp pcp    11852 Jul 22 00:10 20190721.index
-rw-r--r--. 1 pcp pcp    62928 Jul 22 00:10 20190721.meta.xz
-rw-r--r--. 1 pcp pcp  1104688 Jul 23 00:10 20190722.0.xz
-rw-r--r--. 1 pcp pcp    11932 Jul 23 00:10 20190722.index
-rw-r--r--. 1 pcp pcp    66380 Jul 23 00:10 20190722.meta.xz
-rw-r--r--. 1 pcp pcp  1096836 Jul 24 00:10 20190723.0.xz
-rw-r--r--. 1 pcp pcp    11932 Jul 24 00:10 20190723.index
-rw-r--r--. 1 pcp pcp    64372 Jul 24 00:10 20190723.meta.xz
-rw-r--r--. 1 pcp pcp  1148096 Jul 25 00:10 20190724.0.xz
-rw-r--r--. 1 pcp pcp    11872 Jul 25 00:10 20190724.index
-rw-r--r--. 1 pcp pcp    72872 Jul 25 00:10 20190724.meta.xz
-rw-r--r--. 1 pcp pcp  1105124 Jul 26 00:10 20190725.0.xz
-rw-r--r--. 1 pcp pcp    11852 Jul 26 00:10 20190725.index
-rw-r--r--. 1 pcp pcp    64304 Jul 26 00:10 20190725.meta.xz
-rw-r--r--. 1 pcp pcp     8484 Jul 26 00:10 20190726.00.10.0.xz
-rw-r--r--. 1 pcp pcp      252 Jul 26 00:10 20190726.00.10.index
-rw-r--r--. 1 pcp pcp    42836 Jul 26 00:10 20190726.00.10.meta.xz
-rw-r--r--. 1 pcp pcp 28398644 Jul 26 11:26 20190726.00.11.0
-rw-r--r--. 1 pcp pcp     5672 Jul 26 11:26 20190726.00.11.index
-rw-r--r--. 1 pcp pcp   915679 Jul 26 11:26 20190726.00.11.meta
-rw-r--r--. 1 pcp pcp      232 Jul 26 00:11 Latest
-rw-r--r--. 1 pcp pcp    27592 Jul 26 00:11 pmlogger.log
-rw-r--r--. 1 pcp pcp    27667 Jul 26 00:10 pmlogger.log.prior

```

**Comment by mvollmer** [comment]
Thanks, this confirms that you have compressed archives, and Cockpit is only showing the one named "20190726.00.11".

If you manually uncompress the rest, you should be able to see more historic data:

```
xz  -d /var/log/pcp/pmlogger/$(hostname)/*.xz
```

However, Cockpit is fragile when it comes to broken archives: it will not show anything if a single one is broken.  And unfortunately, a empty file (size 0) also counts as broken.  You don't seem to have any of those, so you should be fine.  Check the journal for messages from "cockpit-pcp" if you suspect that Cockpit has trouble with your archives:

```
journalctl -t cockpit-pcp
```

I have opened #12429 to increase robustness.

As to the compressed archives: Right now I would say that there is no good way to let Cockpit read them directly unless PCP itself supports that.  I'll investigate that more.

**Comment by Taomyn** [comment]
Yes, that works and I can see the extracted data now:

![image](https://user-images.githubusercontent.com/4365929/61947658-15ff5e00-afa6-11e9-8de7-bc758df1424a.png)

**Comment by mvollmer** [comment]
Nice!

You can change the compression behavior of pcp in `vi /etc/pcp/pmlogger/control`.  I now have `$PCP_COMPRESSAFTER=never` in there.

Thanks for the report, I wasn't aware of the new compressing behavior of pcp before!

**Comment by Taomyn** [comment]
Ok, so I've set mine to 14 days and cleared out the extracted ones so I can monitor it in the coming days and see how it goes.

**Comment by mvollmer** [comment]
> As to the compressed archives: Right now I would say that there is no good way to let Cockpit read them directly unless PCP itself supports that. I'll investigate that more.

PCP _does_ support reading compressed archives, Cockpit just didn't find them!  I have added a commit to #12429 to fix that.

**Comment by jankais3r** [comment]
My logs are not archived, but Cockpit still isn't displaying them.
[debug.txt](https://github.com/cockpit-project/cockpit/files/3436041/debug.txt)

**Comment by mvollmer** [comment]
> My logs are not archived, but Cockpit still isn't displaying them.

"not compressed", right?

What does `journalctl -t cockpit-pcp` say?

**Comment by jankais3r** [comment]
Sorry, yes, not compressed ;)

```
pi@raspberrypi:~ $ journalctl -t cockpit-pcp
-- Logs begin at Wed 2019-07-24 23:43:17 CEST, end at Fri 2019-07-26 15:51:29 CEST. --
-- No entries --
```

**Comment by goodwinos** [comment]
Hi Marius, yes PCP supports transparent archive decompression (since
pcp-4.x). Both the data logs (*.[0-9]*) and the meta data file (*.meta) are
compressed by the PCP log rotation scripts. The index file (*.index) is not
compressed, so your fix in #12429 to look for the index file instead of the
meta file should be good.

Regards from the PCP project

**Comment by Taomyn** [comment]
> Ok, so I've set mine to 14 days and cleared out the extracted ones so I can monitor it in the coming days and see how it goes.

Seem that setting it to 14 days has no effect as my logs continue to be archived each day

![image](https://user-images.githubusercontent.com/4365929/62025951-e33dab80-b1d9-11e9-9020-0a47a7456f2e.png)

![image](https://user-images.githubusercontent.com/4365929/62026011-0cf6d280-b1da-11e9-93db-3658408fbc8e.png)

**Comment by mvollmer** [comment]
> Seem that setting it to 14 days has no effect as my logs continue to be archived each day

I have the same experience, so maybe we are still missing something to make the config change stick.

However, the real fix is to let Cockpit read compressed archives, of course.  Can you wait for that to reach you?

**Comment by Taomyn** [comment]
> However, the real fix is to let Cockpit read compressed archives, of course. Can you wait for that to reach you?

Of course, no problem

**Comment by mvollmer** [comment]
> so your fix in #12429 to look for the index file instead of the meta file should be good.

Thanks for the confirmation!

**Comment by mvollmer** [comment]
> ```
> pi@raspberrypi:~ $ journalctl -t cockpit-pcp
> -- Logs begin at Wed 2019-07-24 23:43:17 CEST, end at Fri 2019-07-26 15:51:29 CEST. --
> -- No entries --
> ```

Hmm, let's see...

Do you see these archive controls?

![image](https://user-images.githubusercontent.com/3228183/62031009-058df400-b1ef-11e9-8c00-ec9def6adb70.png)

Is cockpit-pcp installed?

Is there a cockpit-pcp process running?

**Comment by banana-ben** [comment]
It looks they are debugging a similar issue here (pcp only keeping one day’s logs)

https://bugzilla.redhat.com/show_bug.cgi?id=1721223

No comments in 2 weeks though. Maybe they continued debugging offline?

**Comment by jankais3r** [comment]
> Do you see these archive controls?
> ![image](https://user-images.githubusercontent.com/3228183/62031009-058df400-b1ef-11e9-8c00-ec9def6adb70.png)
I do. But when I use the controls to zoom out, there's no data.

> Is cockpit-pcp installed?
```
pi@raspberrypi:~ $ apt list --installed | grep cockpit
cockpit-bridge/now 199-1 armhf [installed,local]
cockpit-dashboard/now 199-1 all [installed,local]
cockpit-networkmanager/now 199-1 all [installed,local]
cockpit-packagekit/now 199-1 all [installed,local]
cockpit-pcp/now 199-1 armhf [installed,local]
cockpit-storaged/now 199-1 all [installed,local]
cockpit-system/now 199-1 all [installed,local]
cockpit-ws/now 199-1 armhf [installed,local]
cockpit/now 199-1 all [installed,local]
```

> Is there a cockpit-pcp process running?
```
pi@raspberrypi:~ $ ps aux | grep cockpit-pcp
pi       17952  0.0  0.0   7348   564 pts/0    S+   20:41   0:00 grep --color=auto cockpit-pcp
```

**Comment by Taomyn** [comment]
What version of cockpit-pcp is this fixed in because I thought I saw an update applied this morning for Fedora 30 but I still don't see history. DNF shows I have 199-1.fc30

**Comment by mvollmer** [comment]
> What version of cockpit-pcp is this fixed in

#12429 has just been merged to master and will thus be in the next release, 200, which is due next week, I think.

**Comment by thymbahutymba** [comment]
Store metrics not working on archlinux-arm. The files seems to be there without compression: 

```
/u/l/cockpit $ ls /var/log/pcp/pmlogger/alarmpi/ -l
total 1824
-rw-r--r-- 1 pcp pcp  359452 Nov  3 18:44 20191103.18.35.0
-rw-r--r-- 1 pcp pcp     272 Nov  3 18:44 20191103.18.35.index
-rw-r--r-- 1 pcp pcp  178192 Nov  3 18:35 20191103.18.35.meta
-rw-r--r-- 1 pcp pcp 1072252 Nov  3 19:14 20191103.18.45.0
-rw-r--r-- 1 pcp pcp     392 Nov  3 19:12 20191103.18.45.index
-rw-r--r-- 1 pcp pcp  178192 Nov  3 18:45 20191103.18.45.meta
-rw-r--r-- 1 pcp pcp     217 Nov  3 18:45 Latest
-rw-r--r-- 1 pcp pcp   26311 Nov  3 18:45 pmlogger.log
-rw-r--r-- 1 pcp pcp   26311 Nov  3 18:35 pmlogger.log.prior
```

```
● pmlogger.service - Performance Metrics Archive Logger
   Loaded: loaded (/usr/lib/systemd/system/pmlogger.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2019-11-03 19:17:25 CET; 16s ago
     Docs: man:pmlogger(1)
  Process: 20458 ExecStart=/usr/share/pcp/lib/pmlogger start (code=exited, status=0/SUCCESS)
 Main PID: 25737 (pmlogger)
    Tasks: 1 (limit: 2203)
   Memory: 3.9M
   CGroup: /system.slice/pmlogger.service
           └─25737 /usr/lib/pcp/pcp/bin/pmlogger -P -r -T24h10m -c config.default -v 100mb -m pmlogger_check 20191103.19.16

Nov 03 19:16:55 alarmpi systemd[1]: Starting Performance Metrics Archive Logger...
Nov 03 19:16:55 alarmpi pmlogger[20458]: Starting pmlogger ...
Nov 03 19:16:55 alarmpi systemd[1]: pmlogger.service: Can't open PID file /run/pcp/pmlogger.pid (yet?) after start: No such file or directory
Nov 03 19:17:25 alarmpi systemd[1]: pmlogger.service: Supervising process 25737 which is not our child. We'll most likely not notice when it exits.
Nov 03 19:17:25 alarmpi systemd[1]: Started Performance Metrics Archive Logger.
```
```
/u/l/cockpit $ journalctl -t cockpit-pcp -e
Nov 03 19:12:31 alarmpi cockpit-pcp[19941]: Error Parsing ASCII PMNS: Cannot open "/var/lib/pcp/pmns/root"
Nov 03 19:12:31 alarmpi cockpit-pcp[19941]: Error Parsing ASCII PMNS: Cannot open "/var/lib/pcp/pmns/root"
Nov 03 19:12:31 alarmpi cockpit-pcp[19941]: 1:2!20: direct: no such metric: mem.physmem: PMNS not accessible
Nov 03 19:12:31 alarmpi cockpit-pcp[19941]: 1:2!21: direct: no such metric: disk.all.total_bytes: PMNS not accessible
Nov 03 19:12:31 alarmpi cockpit-pcp[19941]: Error Parsing ASCII PMNS: Cannot open "/var/lib/pcp/pmns/root"
Nov 03 19:12:31 alarmpi cockpit-pcp[19941]: 1:2!22: direct: no such metric: network.interface.total.bytes: PMNS not accessible
Nov 03 19:12:34 alarmpi cockpit-pcp[19941]: Error Parsing ASCII PMNS: Cannot open "/var/lib/pcp/pmns/root"
Nov 03 19:12:34 alarmpi cockpit-pcp[19941]: 1:2!32: direct: no such metric: kernel.all.cpu.nice: PMNS not accessible
```

**Comment by andylamp** [comment]
I can also confirm that it is broken on ubuntu 20.04 with a similar error message.

![image](https://user-images.githubusercontent.com/2177249/149818272-95bc1588-1ea5-4174-936b-f9fcf453369e.png)

**Comment by garrett** [comment]
@andylamp: Judging from the screenshot, that's an old version of Cockpit. Are you using the backports version? https://cockpit-project.org/running.html#debian

That said, I'm having some issues with pmlogger on my Fedora Silverblue development environment, but I might not have things properly set up. (I'm not depending on packages for it, this is a desktop spin of Fedora, etc.)

![Screenshot 2022-01-25 at 14-14-04 Logs - garrett Bolt](https://user-images.githubusercontent.com/10246/150983464-89965516-76c3-42f7-acf2-d42f81aa591d.png)

**Comment by andylamp** [comment]
@garrett I am using the one provided by `ubuntu` 20.04 LTS and `cockpit` is on version 215; at least that is what I get when I type:

```bash
andylamp@nas-home:~$ cockpit-bridge --version
Version: 215
Protocol: 1
Payloads: dbus-json3 http-stream1 http-stream2 stream packet fsread1 
    fsreplace1 fswatch1 fslist1 null echo websocket-stream1 
```

**Comment by martinpitt** [comment]
Yes, that's a very old version, which does not have the Metrics page even. Please [update to a backport](https://cockpit-project.org/running.html#debian)

**Comment by garrett** [comment]
> very old version

Cockpit version 215 was specifically released on Mar 18, 2020 (almost 2 years ago): https://cockpit-project.org/blog/cockpit-215.html — there have been so many bugfixes and features since then, so the version in backports is _much_ improved.

**Comment by andylamp** [comment]
@garrett, ah right - installed it through backports and the error seems to be gone. However, `cockpit-dashboard` seems to be gone; where I get aggregations over time for CPU, Storage, Network, and RAM usages. Do you know if there is any (maintained) alternative?

**Comment by martinpitt** [comment]
@andylamp : Right, we dropped c-dashboard as it was a rather bad solution (in terms of security, scalability, and utility). Instead we made it easier to integrate with Grafana. See https://cockpit-project.org/blog/pcp-grafana.html

**Comment by andylamp** [comment]
@martinpitt ah, right - that's brilliant, will look into that instead! thanks so much!
