### ISSUE TITLE
Ooops! on account page 

### ISSUE THREAD

**Issue by oleksandrborniak** [cockpit-project/cockpit#12364]
Cockpit version: cockpit-198-1.fc30
OS: Fedora Server 30
Page: Accounts -> User (https://URL:3000/users#/root)

```
cockpit.js:590 grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

p @ cockpit.js:590
m @ cockpit.js:600
v @ cockpit.js:494
a.onmessage.o.dispatch_data @ cockpit.js:424
e @ cockpit.js:280
postMessage (async)
(anonymous) @ index.js:6
a.onmessage.o.dispatch_data @ cockpit.js:422
machines.js:56 index.js: Setting LibvirtDBus as virt provider.
users.js:45 Uncaught TypeError: Cannot read property 'length' of undefined
    at $.check_username (users.js:45)
    at $.validate (users.js:45)
    at HTMLInputElement.r (jquery.js:7723)
    at HTMLInputElement.dispatch (jquery.js:3820)
    at HTMLInputElement.v.handle (jquery.js:3683)
check_username @ users.js:45
validate @ users.js:45
r @ jquery.js:7723
dispatch @ jquery.js:3820
v.handle @ jquery.js:3683
users.js:45 Uncaught TypeError: Cannot read property 'length' of undefined
    at $.check_username (users.js:45)
    at $.validate (users.js:45)
    at HTMLInputElement.r (jquery.js:7723)
    at HTMLInputElement.dispatch (jquery.js:3820)
    at HTMLInputElement.v.handle (jquery.js:3683)
check_username @ users.js:45
validate @ users.js:45
r @ jquery.js:7723
dispatch @ jquery.js:3820
v.handle @ jquery.js:3683
cockpit.js:590 Error: Could not obtain the password to be scored

p @ cockpit.js:590
m @ cockpit.js:600
v @ cockpit.js:494
a.onmessage.o.dispatch_data @ cockpit.js:424
e @ cockpit.js:280
postMessage (async)
(anonymous) @ index.js:6
a.onmessage.o.dispatch_data @ cockpit.js:422
```

Journal doesn't have any useful informations.  

Steps to reproduce: 
Select user on Accounts page. 

<img width="1011" alt="Screen Shot 2019-07-19 at 10 50 20" src="https://user-images.githubusercontent.com/49722408/61518792-18e0d880-aa13-11e9-82ef-3272bf790519.png">

**Comment by marusak** [comment]
Thank you for the report.
Can you reproduce it? If so, can you write steps you do to reproduce it?

**Comment by oleksandrborniak** [comment]
Hello Matej, 
Just needs to press on user on accounts page . I've recorded screencast for you.
https://photos.app.goo.gl/HgoHyfnAVtAMR4169
It is a test server, so I can create account for you.  Just let me know. 
@marusak  ^

**Comment by oleksandrborniak** [comment]
P.S. I am now on cockpit-203-1.fc30.x86_64 , so the issue is still there.

**Comment by marusak** [comment]
Thanks.
I cannot reproduce this at all. Is there anything interesting about this account? Does it work the same with any other account?

The most confusing part is that the trace you sent/shown comes from part of code that deals with creating of new users ('Create new user' button). So I have no idea how this code gets executed when you click on user.

Can you please try different browser just in case there is happening something weird? Thanks

**Comment by oleksandrborniak** [comment]
It works the same for any account. I've created few test users and they all were affected. 
The issue reproduces only on Chrome , Firefox and Safari browsers didn't show Oops.  
I am using latest Chrome (Version 77.0.3865.90 ) , but the same was for previous.

**Comment by marusak** [comment]
> The issue reproduces only on Chrome , Firefox and Safari browsers didn't show Oops.

Ah, great, this at least gives me some hint. I'll check with chrome and see if I can reproduce it.

**Comment by oleksandrborniak** [comment]
Thank you!

**Comment by marusak** [comment]
oh I just noticed I never replied to this. I checked chrome and it works for me. Is it possible that some plugin is interfering with it? Can you try it without any plugins?

**Comment by oleksandrborniak** [comment]
All chrome extensions ( chrome://extensions ) are turned off , but behaviour the same. 

<img width="1137" alt="Screenshot 2020-03-19 at 16 30 45" src="https://user-images.githubusercontent.com/49722408/77078638-89efea00-69ff-11ea-9242-0830fd1f0db7.png">
<img width="1150" alt="Screenshot 2020-03-19 at 16 30 52" src="https://user-images.githubusercontent.com/49722408/77078644-8b211700-69ff-11ea-9ca6-11cf84469670.png">


Chrome Version 80.0.3987.132 (Official Build) (64-bit)


Might be I can create account for you and you will re-check it in your Chrome.  (In case it is something on server side)

**Comment by marusak** [comment]
Sure, we can try that.

**Comment by oleksandrborniak** [comment]
Credentials have been sent to your email. Please let me know if you need any assistance.
Thank you!

**Comment by marusak** [comment]
Thank you! I've tested it on bunch of browsers on different versions (all linux builds):

Chrome:
Version 71.0.3578.80 (Official Build) (64-bit)
Version 80.0.3987.149 (Official Build) (64-bit)

Chromium:
Version 79.0.3945.130 (Developer Build) Fedora Project (64-bit)
Version 80.0.3987.132 (Developer Build) Fedora Project (64-bit)

Firefox:
73.0.1 (64-bit)

Firefox nightly:
76.0a1 (2020-03-19) (64-bit)

And all works as expected. I guess you use windows builds, but there should be hopefully no difference. Can you also please try [this](https://www.techsupportall.com/start-google-chrome-without-extensions/) approach to start your browser without any extensions? And also in private mode?

**Comment by oleksandrborniak** [comment]
I am working on Mac OS Catalina 10.15.3 (19D76). 
I'll ask my coworkers with Mac OS  try the same and let you know about result.
Might be, it is really something only in my browser.

**Comment by oleksandrborniak** [comment]
My coworkers also didn't see such message in Chrome under MacOS, so I guess it is some local issue with my setup. Thank you for your help. 
Have a nice day and be healthy!

**Comment by jeroenschepens** [comment]
I've just had this same problem. It was Chrome's credential management that caused this. After removing the credentials from Chrome the problem disappeared. If you save your credentials in Chrome then this is reproducible.

**Comment by oleksandrborniak** [comment]
Thank you! @Jeroen
