### ISSUE TITLE
Add cockpit.js support for testing if a file or path exists

### ISSUE THREAD

**Issue by mckenziec** [cockpit-project/cockpit#12370]
The current cockpit.js file access support is awesome, but its difficult to perform a simple file existence test. I know that reading and writing can be worked with to accomplish this, but a simple test to verify the existence of a config or log file can be used in a plugin to render differently depending. Thanks.

**Comment by martinpitt** [comment]
This is a bit tricky indeed. You could use [cockpit.file()](https://cockpit-project.org/guide/latest/cockpit-file.html) with `{ max_read_size: 1 }` options and check if on `.read()` you get a success or `too-large` error (→ file exists), or a `null` (→ file does not exist). Or use `cockpit.spawn`() with a `test` call, which will then allow you a more fine-grained determination of file type. But a `cockpit.stat()` API may be nice.

For testing a single file, the performance penalty should be negligible, though.

**Comment by martinpitt** [comment]
We finally have that! https://github.com/cockpit-project/cockpit/blob/main/doc/protocol.md#payload-fsinfo It's not yet wrapped in cockpit.js, but [cockpit-files is using it](https://github.com/cockpit-project/cockpit-files/blob/main/src/fsinfo.ts).
