### ISSUE TITLE
Proxying Cockpit over NGINX in subdir (mydomain.org/management/)

### ISSUE THREAD

**Issue by Omaha2002** [cockpit-project/cockpit#12378]
Cockpit version: latest
OS: Ubuntu / NGINX

I would like to access cockpit through  https://mydomain.org/management. https://mydomain.org is a working https (letsencrypt) Nextcloud environment.

Used: https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX as a start.

And changed:

location / {
        proxy_pass http://websocket;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        # needed for websocket
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        # change scheme of "Origin" to http
        proxy_set_header Origin http://$host;

        # Pass ETag header from cockpit to clients.
        # See: https://github.com/cockpit-project/cockpit/issues/5239
        gzip off;
    }

**to**

location **/management** {
        proxy_pass http://websocket;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        # needed for websocket
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        # change scheme of "Origin" to http
        proxy_set_header Origin http://$host;

        # Pass ETag header from cockpit to clients.
        # See: https://github.com/cockpit-project/cockpit/issues/5239
        gzip off;
    }

And /etc/cockpit/cockpit.conf to:

[WebService]
AllowUnencrypted=true
UrlRoot=/management/

Expected https://mydomain.org/management to show the cockpit login interface but it only shows blank login fields:

![image](https://user-images.githubusercontent.com/3179748/61612267-584f3500-ac5e-11e9-8e6c-61b344290198.png)

**Comment by watercrossing** [comment]
I believe you need to specify the subdir in the proxy destination too, i.e. proxy to:
```proxy_pass http://websocket/management;```

**Comment by Omaha2002** [comment]
Thanks for the suggestion but it doesnt work. Still got a empty login screen like above.

**Comment by Omaha2002** [comment]
Ended up giving cockpit it's own subdomain.
