### ISSUE TITLE
Improvements for the FileAutocompletion component

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#12409]
- Overflow of long strings escapes the text input widget
- Overflow of items in the dropdown trigger a horizontal scrollbar (perhaps these items should be forced to wrap or truncate on the left so we see the end of the string, which matters the most in this case?)
- Popup still displays in incorrect cases:
  - On focus
  - When an item is selected
  - When the text input is clicked (perhaps this is just on focus)
- Popup should only show when:
  - Down arrowhead is clicked
  - Typing occurs
  - Arrow keys are used
- There's a very small delay due to filtering and modifying the DOM on keypress; instead, this should be debounced and throttled by a very tiny amount so typing won't be delayed

**Comment by garrett** [comment]
We should consider PF4 and if it is possible to port our widget over to it.

I think this is probably the widget to consider: https://www.patternfly.org/v4/documentation/react/components/select#typeahead
