### ISSUE TITLE
Less aggressive check for package updates

### ISSUE THREAD

**Issue by jankais3r** [cockpit-project/cockpit#12413]
I am using Cockpit to monitor cluster of Raspberry Pis (different generations) and especially the older ones are having hard time with the way Cockpit checks for software updates all the time.

I'm talking about these lines in host.js:
```
 // check for updates now and on page switches, in case they get applied on /updates or terminal
$(cockpit).on("visibilitychange", check_for_updates);
check_for_updates();
```

Basically every time I refresh the page, the CPU of the raspberry in question spikes to 100% for several seconds. This is not ideal as those raspberries have their tasks that are being impacted by this behavior.

Would it be possible to make this behavior configurable? As we also have dedicated Updates tab, I don't understand why we have to check on every page load.

Thanks

**Comment by martinpitt** [comment]
Indeed this is rather aggressive right now. We must be able to catch system updates issued from the SW updates page, as well as the terminal or from outside. The check is pretty quick even in an x86_64 Fedora VM (0.3 s here), but if it's that expensive on either ARM or Debian (not sure which part contributes), we need to dial it down.

First of all, we wouldn't need to check when changing *away* from the System page. Unfortunately `document.visibilityState` always says "visible" even for that case, at least in Firefox (see [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event)). We could still check it opportunistically, perhaps it helps in some cases.

Another thing to do is to remember a global timestamp when the check happened last, and explicitly resetting it on the software updates page when applying updates. That won't immediately catch upgrades installed via some other means, but that may be an acceptable trade-off.

**Comment by jankais3r** [comment]
It's certainly not a Debian issue, as it only takes 2 seconds or so on Raspberry Pi 4, while it can take up to 20 seconds on the older Raspberries. I am not sure how common it is to run cockpit on such underpowered hardware, maybe it is not worth putting resources into.

Personally I would be fine with refreshing the value on the System page only in 2 instances - when we first switch cockpit to the given machine, and when we manually check for/install updates in the Updates tab. If you are switching between machines a lot, you would still be informed about new available updates the next time you connect to the machine, and in case you manually install updates outside of cockpit, the worst thing that can happen is that the flag will be outdated until you check for updates again from the web interface or you switch machines. It may be me, but I am not sure if the CPU cycles and constant traffic to repositories is worth having always up-to-date label.

**Comment by martinpitt** [comment]
> run cockpit on such underpowered hardware

A lot of people do that, and we actually want to support that. Cockpit fits that use case quite well (in general).

> I am not sure if the CPU cycles and constant traffic to repositories is worth having always up-to-date label.

There is no traffic to the repositories. This doesn't actually  update the repositories from remote servers, it just asks the *local* PackageKit if it already knows about pending updates. This is why it's usually not an issue on laptop/server-class hardware (the 0.3 s above), but apparently it is for embedded systems.

I have an idea how to fix this. Thanks for your report!

**Comment by martinpitt** [comment]
I sent a PR #12422 for this.
