### ISSUE TITLE
Error generated in the Storage tab after fresh install on Raspbian

### ISSUE THREAD

**Issue by jankais3r** [cockpit-project/cockpit#12412]
Cockpit version: 198
OS: Raspbian 10 Buster
Page: Storage

I just did a clean install of Cockpit on Raspbian (raspberry pi 4) and an error was thrown by `udisksd` in the Storage tab:
`Error loading modules: Error opening directory “/usr/lib/arm-linux-gnueabihf/udisks2/modules”: No such file or directory`

Steps to reproduce

1. sudo apt-get install cockpit
2. Log-in
3. Go to Storage tab
4. Find the error in the Storage Logs (The error has timestamp of the moment when you open the tab, therefore I believe it is caused by cockpit.)

**Comment by jankais3r** [comment]
Happens both with version 188 installed from Buster Stable and with version 198 installed from Bullseye Testing.

**Comment by mvollmer** [comment]
I believe this is a bug in the Debian/Raspbian packaging of UDisks2.  Installing `udisks2` alone should either create that directory, or udisksd shouldn't complain when it is missing.

Could you report that bug with Debian?

What happens when you install actual UDisks2 modules, such as `udisks2-lvm2`?

**Comment by mvollmer** [comment]
> Could you report that bug with Debian?

@martinpitt, hmm, do we actually have the official Debian/Raspbian packaging upstream as well?

**Comment by martinpitt** [comment]
@mvollmer: Yes, tools/debian/control is the official packaging of Debian/Ubuntu. In theory raspian could change it, but I doubt that they do.

**Comment by svenflender** [comment]
Is there any solution to solve this Problem?

**Comment by mvollmer** [comment]
> Is there any solution to solve this Problem?

I believe there is no actual problem.  Everything should work, despite the messages in the journal.

> When installing
> 
> udisks2-bcache
> 
> the error ist gone but i get a new one:
> 
> ![image](https://user-images.githubusercontent.com/42860703/74978720-83387c00-542d-11ea-883c-3f0be0affa0b.png)
> 
> same when i install lvm2

I get these messages as well all the time, and I have learned to ignore them. *shrug*

**Comment by svenflender** [comment]
Solved  

<code>
sudo mkdir /usr/lib/arm-linux-gnueabihf/udisks2/modules
</code>  
did the Trick. The Message is gone.
