### ISSUE TITLE
Dont install, file not found!!!

### ISSUE THREAD

**Issue by alperdos** [cockpit-project/cockpit#12420]
Cockpit version: 198
OS: Centos 7

failure: repodata/repomd.xml from ntop: [Errno 256] No more mirrors to try.
http://www.nmon.net/centos-stable/7/x86_64/repodata/repomd.xml: [Errno -1] Error importing repomd.xml for ntop: Damaged repomd.xml file

Repo file not found on nmon.
Centos 7 "sudo yum install cockpit" not working.
Pls Check
www.nmon.net/centos-stable/7/x86_64/repodata/repomd.xml

**Comment by marusak** [comment]
This is not cockpit bug. This affects anything you want to install from that repository.
You need to contact maintainer of that mirror. Also you can try different mirror in the meantime.
Here is list of official mirrors: https://www.centos.org/download/mirrors/
