### ISSUE TITLE
Customizing branding.css produces Error

### ISSUE THREAD

**Issue by trayan16** [cockpit-project/cockpit#12439]
Cockpit version: xxx
OS: Fedora
Page: Login

Hello,

I am trying to edit the branding css, but I encounter some issue there. I've followed the steps from : https://cockpit-project.org/external/source/HACKING

However, when I execute **sudo mount -o bind src/branding/ /usr/share/cockpit/branding/**
Then stop the service with **systemctl stop cockpit.service**

I reload the cockpit login page, but It shows me the following error :

**Refused to apply style from 'https://192.168.232.130:9090/cockpit/static/branding.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.**

When I follow that link, the branding.css file is not found. So maybe, I should tell Cockpit to use my local static folder. Then I execute : **sudo mount -o bind dist/static/ /usr/share/cockpit/static/**
But I get Internal Server error after restarting the Cockpit service.

Will be glad, If someone can help me. 
Thank you.

**Comment by trayan16** [comment]
Server log shows me this : 
![image](https://user-images.githubusercontent.com/16117267/62036123-da5cd200-b1f9-11e9-8e95-dc4f594e84db.png)

**Comment by marusak** [comment]
It seems that there is selinux denial. Have you tried with selinux disabled?
This is only for development purposes so I guess we can live just fine with having to disable selinux.

**Comment by marusak** [comment]
@trayan16 ping
