### ISSUE TITLE
Add means to respect sshd config (DenyUsers, DenyGroups)

### ISSUE THREAD

**Issue by stevekay** [cockpit-project/cockpit#12433]
Some enterprises make efforts to restrict the use of ssh, by adding `DenyUsers` or `DenyGroups` lines to sshd_config.

The introduction of cockpit offers a means for these existing restrictions to be subverted, because the Terminal tool within cockpit does not parse/respect these settings.

Propose the introduction of an enhancement to cockpit, such as a `RespectSshdRestrictions` boolean within cockpit.conf.

**Comment by martinpitt** [comment]
These options are specific to SSH. They don't apply to cockpit, VT, or any other logins. For your case it would be better to not install cockpit-ws on these servers at all, but only on a "bastion host", from where you use the "Connect to:" login page option, or the "Add host" functionality in the cockpit main menu. Both of these use ssh to connect to the remote machine, which will then respect all of SSH's configurations and restrictions.
