### ISSUE TITLE
Accessing VM from network

### ISSUE THREAD

**Issue by luixal** [cockpit-project/cockpit#12431]
DISCLAIMER!
I've opened this issue not because of a bug, but for a lack of documentation/understanding on how to use the tool.
----

I've just started using Cockpit for creating/using VMs and it's been impossible to me to make a VM accessible from my physical network.

I got this info in VM's entry, which seems good:

![image](https://user-images.githubusercontent.com/615268/61994891-5253bc80-b081-11e9-9ca7-f71f82dd7e87.png)

but when trying to do _something_ (not really experienced on this, bridge? vlan?) in the network section, I can't find any reference to that mac address.

How do I bind the virtual card in the VM to a physical one? (or any other method to have access to this VM from my physical network?

Some screenshots showing what I see on the network section (hope they can help):

![image](https://user-images.githubusercontent.com/615268/61994939-2be25100-b082-11e9-8c3f-6dd7f6c8804e.png)

![image](https://user-images.githubusercontent.com/615268/61994941-313f9b80-b082-11e9-9ae0-beeb87bcebfd.png)

**Comment by KKoukiou** [comment]
Your NIC is using the default network. Can you please paste the XML of that (just to see if you have changed it) 
`sudo virsh net-dumpxml default`

**Comment by luixal** [comment]
Hi @KKoukiou , the output of that command is this:

```
<network>
  <name>default</name>
  <uuid>88b696d5-ca09-49cc-8745-dfc77abe206f</uuid>
  <forward mode='nat'/>
  <bridge name='virbr0' stp='on' delay='0'/>
  <mac address='52:54:00:92:7c:c1'/>
  <ip address='192.168.122.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.122.2' end='192.168.122.254'/>
    </dhcp>
  </ip>
</network>
```

Thanks!

**Comment by Gundersanne** [comment]
Are you trying to expose the VM?

The VM should be accessible on virbr0, on whatever IP the VM received (subnet 192.168.122.1\24). You can see this inside the VM itself. On newer versions of cockpit this is also shown in the UI.

Now if you want to expose this VM on your local network, you'll need to set up some sort of forwarding from the host interface to the VM's interface.

**Comment by skobyda** [comment]
So your problem here is that Network Interface of your VM is of type "network" source "default", which basically means that for connection it will use virtual network with name "default".
As I can see from XML which you have posted, your "default" virtual network has forward mode NAT.
Because of the way NAT translation works, you can connect from your VM to the outside world. However it's impossible to connect to virtual machine which is hidden behind NAT IP translation.
So if you want to in order to connect to your virtual machine, easiet solution I would say is to change type of your VM's network interface to direct (macvtap) and as a source device choose whichever physical card you want.
Or you can setup port forwarding for your virtual network. This however cannot be done through out UI yet.

**Comment by luixal** [comment]
Yes, I want to expose my VM so it's accesible from my local network. I was trying to use only Cockpit UI (which seemed to be the point), and tried several things:

* Creating a bridge and selecting `enp3s0f1`  and `virb0`: doesn't seem to work, it stucks on "Configuring IP" (I don't like this solution either as I could only access as many VMs as physical network devices).
* Creating a VLAN: I thought this one the good solution as I won't be limited to physical network devices (is that right?), but although, didn't work for me.

Anyway, going to test right now, but when starting the VM I got this error (all of a sudden, this worked a couple days ago):

![image](https://user-images.githubusercontent.com/615268/62139953-70702580-b2ea-11e9-96dd-60499aa2693d.png)

I'm running Cockpit on Ubuntu Server 18.04.2 LTS and had to do a little tweaking for Cockpit to manage network interfaces through NetworkManager. No clue what's happening now :(

**Comment by luixal** [comment]
Nevermind, I think Cockpit is not running quite well on Ubuntu Server due to NetworkManager issues. Virsh default interface is set as inactive when some time passes and it's being a headache.

I'm closing this issue now, thanks!

**Comment by jerry3k** [comment]
```sh
#Jeremy Murray
#This will create bridge for VMs in CentOS7 
#First turn Ethernet off

# add bridge "bridge0"
nmcli c add type bridge autoconnect yes con-name bridge0 ifname bridge0
nmcli c modify bridge0 ipv4.address 192.168.0.69/24 ipv4.method manual
nmcli c modify bridge0 ipv4.gateway 192.168.0.1
nmcli c modify bridge0 ipv4.dns 192.168.0.1
#remove current network card settings
nmcli c delete eno888888
nmcli c add type bridge-slave autoconnect yes con-name eno888888 ifname eno888888 master bridge0
reboot
#most probably the network manager will not work as expected
#Go into the VM settings and see the bridge should appear along with the the host ethernet card name
```
