### ISSUE TITLE
logs: hard to identify the severity by the icon

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#12443]
Cockpit version: 199
OS: Fedora 30
Page: Logs

![Screenshot from 2019-07-29 15-52-02](https://user-images.githubusercontent.com/209895/62057141-54538200-b21f-11e9-9e33-ff01af045080.png)

There is no explanation of what the little /!\ or (x) icons actually mean, and how they relate to the Severity filter above (because they do right? Is it a 1:1 match?)

**Comment by andreasn** [comment]
Probably need to give them a tooltip at a minimum, because now you're pretty screwed if you use a screen reader also.
I suggested a Severity column on IRC, but @garrett felt that approach wouldn't work as well.

**Comment by marusak** [comment]
> because they do right? Is it a 1:1 match?)

the /!\ icon is shown if the severity is less than 4 ("Only emergency" to "Error and above")
the (x) icon is shown if the log is ABRT reported problem

**Comment by garrett** [comment]
A tooltip alone doesn't work. They'd probably need ARIA labelling for the text too.

With the widget as currently implemented, a severity column would _not_ work, as the text string would be arbitrary in length and the column needs to be fixed width. This stems from the fact that the "table" isn't actually a table so the widths are not dynamic nor relative to their siblings.

I suggest we consider porting the journal/logs to PF4 as one of the earlier porting efforts.

**Comment by garrett** [comment]
But if not PF4... then at least consider actual tables for this tabular data. :wink:

**Comment by andreasn** [comment]
Ah, ok, so just to clarify, we could do a Severity column, but only if the whole thing is turned into a table?

**Comment by marusak** [comment]
> ... we could do a Severity column ...

What would be in the severity column?

**Comment by andreasn** [comment]
> What would be in the severity column?

The same info as the icon communicates, just in text. So it would spell out _Emergency_, _Warning_ etc. so to make it easier to tell what you're filtering on.

**Comment by marusak** [comment]
> The same info as the icon communicates, just in text.

Hmm, I am not sure what information this brings to users. I got it that you want to provide feedback to filtering, but this seems rather invasive as it takes a lot of space and does not provide much useful information (as user I don't care that much in general what priority it has - the priority is great for filtering to reduce the amount of results)

**Comment by marusak** [comment]
Closing this issue as:
- One required step was to migrate to PF4 (tracked in https://github.com/cockpit-project/cockpit/issues/15170)
- The column does not seem to be useful anyway (and takes too much space)
- Maybe tooltip would work, but still not sure how "Priority is error" would help user
- I think those icons are there just to catch user attention when looking on the page
- They don't (have to) directly identify severity (as for example with abrt reports)
