### ISSUE TITLE
No error message when the web socket connection fails

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#12491]
Cockpit version: 199
OS: Fedora Server 30

Even when WebSocket support is present, actually creating a WebSocket connection might fail.  For example, iOS has trouble with self signed certificates, or a reverse proxy might be misconfigured.

Currently, Cockpit shows a blank page when the connection fails.  We should at least show a "this didn*t work" error.

**Comment by leomoty** [comment]
Just in case, related: https://github.com/cockpit-project/cockpit/issues/11844 https://github.com/cockpit-project/cockpit/issues/10146

**Comment by mvollmer** [comment]
Upps, duplicate of #11844.  Thanks @leomoty!
