### ISSUE TITLE
Allowing changing hostname in a realm-joined machine can break everything

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#125]
Right now it's fairly simple to change the hostname of a system. Especially in the case of having the system part of a Domain, the one thing you must not change is the hostname, because that will break everything.

I suggest we remove the ability to change the hostname, and move this to a initial-setup stage.

**Comment by dperpeet** [comment]
@andreasn should we warn the user when changing the hostname while part of a domain?

**Comment by martinpitt** [comment]
How about we just disable changing the hostname when the machine is part of a domain, and point that out in a tooltip?

**Comment by stefwalter** [comment]
> How about we just disable changing the hostname when the machine is part of a domain, and point that out in a tooltip?

Works for me.

**Comment by andreasn** [comment]
Sure!
