### ISSUE TITLE
sudo make install ==> cockpit-session: can't exec /bin/bash: Permission denied

### ISSUE THREAD

**Issue by zombinary** [cockpit-project/cockpit#12512]
Cockpit version: 194.x & 199
OS: fedora 30
Page: login page

The cockpit login page could not load the  packages.
After an login in the cockpit landing page, i get the error message 'The cockpit package is not installed'

In the jounralctl is logged that '/bin/bash' could not be executed by spawing.
But I can't change the permissions with
`'chmod 755 /bin'`

This is the journalctl with debuglog enabled:
```
Aug 07 14:10:40 localhost.localdomain cockpit-ws[20103]: web service closing
Aug 07 14:10:40 localhost.localdomain cockpit-ws[20103]: couldn't read from connection: Peer sent fatal TLS alert: Unknown certificate
Aug 07 14:10:45 localhost.localdomain cockpit-ws[20103]: [34B blob data]
Aug 07 14:10:45 localhost.localdomain cockpit-ws[20103]: received unknown/invalid credential cookie
Aug 07 14:10:45 localhost.localdomain cockpit-ws[20103]: spawning /usr/local/libexec/cockpit-session
Aug 07 14:10:45 localhost.localdomain cockpit-ws[20103]: received authorize challenge
**Aug 07 14:10:45 localhost.localdomain cockpit-ws[20103]: cockpit-session: can't exec /bin/bash: Permission denied** 
Aug 07 14:10:45 localhost.localdomain cockpit-ws[20103]: cockpit-session: authentication process exited: 32512; problem no-cockpit
Aug 07 14:10:45 localhost.localdomain cockpit-ws[20103]: web service closing
Aug 07 14:12:10 localhost.localdomain cockpit-ws[20103]: auth is idle
Aug 07 14:12:10 localhost.localdomain systemd[1]: cockpit.service: Succeeded.

```
Steps to reproduce

1.  $ git clone ...
2.  $ sudo make
3.  $ sudo make install 
4.  $ sudo systemctl daemon-reload
5.  $ sudo systemctl restart cockpit

**Comment by marusak** [comment]
Can you please try it the same way the official doc advices to? (like not running `make` as root, copying the pam configuration).
https://github.com/cockpit-project/cockpit/blob/master/HACKING.md#installation-from-upstream-sources

**Comment by zombinary** [comment]
i had checked this again and log in with my user name, run a `make clean` and delete the dist folder.
After an make install i had the same effect.

 `$ make clean`
` $  rm -rf dist/`
 `$  make`
 `$  sudo make install`
` $  sudo cp src/bridge/cockpit.pam.insecure /etc/pam.d/cockpit`
 `$  sudo systemctl daemon-reload`
` $  sudo systemctl restart cockpit`

**Comment by zombinary** [comment]
**[solved]**

I could run and debug my own cockpit source.
The solution was not to be used the `make install` command.
I run the `./cokpit-ws` from project folder

```
$ make distclean
$ ./autogen
$ make.sh
$ sudo systemctl stop cockpit
$ sudo systemctl start cokpit.socket
$ export G_DEBUG=fatal-criticals
$ export G_MESSAGES_DEBUG=cockpit-ws,cockpit-wrapper,cockpit-bridge
$ ./cockpit-ws --port 10000 --no-tls

```
After this steps cockpit is running in the browser **http://{ip}:1000**.
If you had a problem with the log in on cockpit landing page, get sure u had delete the cookies in your browser for this webpage.

https://github.com/cockpit-project/cockpit/blob/master/HACKING.md#running-cockpit-processes-under-a-debugger
For your interest here is my launch.json to debug with VS-Code:

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(gdb) Launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "./cockpit-ws",
      "args": ["--port", "10000", "--no-tls"],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [{"name":"G_DEBUG", "value":"fatal-criticals"},{"name":"G_MESSAGES_DEBUG","value":"cockpit-ws,cockpit-wrapper,cockpit-bridge"}],
      "externalConsole": false,
      "MIMode": "gdb",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ]
    }
  ]
}

```

**Comment by deajan** [comment]
Just for whoever might have the same problem I had:
When installing a compiled version of Cockpit on CentOS 8 I got `The cockpit package is not installed` when logging in.

Looking at journal, I had:
```
Oct 05 12:09:42 hypervisor.test.local cockpit-tls[12041]: cockpit-tls: reading from client fd 12 TLS connection failed: The TLS connection was non-properly terminated.
Oct 05 12:09:42 hypervisor.test.local cockpit-session[12308]: pam_ssh_add: Failed to start ssh-agent
Oct 05 12:09:42 hypervisor.test.local cockpit-session[12308]: pam_unix(cockpit:session): session opened for user root by (uid=0)
Oct 05 12:09:42 hypervisor.test.local cockpit-tls[12041]: cockpit-session: can't exec /bin/bash: Permission denied
Oct 05 12:09:42 hypervisor.test.local cockpit-session[12308]: pam_unix(cockpit:session): session closed for user root
Oct 05 12:10:00 hypervisor.test.local cockpit-session[12452]: pam_ssh_add: Failed to start ssh-agent
Oct 05 12:10:00 hypervisor.test.local cockpit-session[12452]: pam_unix(cockpit:session): session opened for user root by (uid=0)
Oct 05 12:10:00 hypervisor.test.local cockpit-tls[12041]: cockpit-session: can't exec /bin/bash: Permission denied
```

This is indeed SELinux related, to be sure I disable selinux with `setenforce 0` and logged in again in Cockpit, which worked.
I then reactivated selinux with `setenforce 1` and created a module for cockpit with
```
ausearch -c "cockpit-session" --just-one |audit2allow -a -M cockpit-session_rule
semodule -i cockpit-session_rule.pp
```
