### ISSUE TITLE
Branding manual selection within some config file

### ISSUE THREAD

**Issue by inspirit1986** [cockpit-project/cockpit#12524]
Hi, I want to define branding(theme selection) also within config files like
theme: sometheme1

theme placed in $prefix/share/cockpit/branding/sometheme1
Can you introduce this feature?

Auto theme selection from /etc/os-release is not applicable for me.
Thank in advance

**Comment by KKoukiou** [comment]
@inspirit1986 why /etc/os-release is not applicable for you?

**Comment by inspirit1986** [comment]
Hi @KKoukiou, at this time, our team working on our security product and we want to use cockpit as fronted with some our enhancements. One of it is manual setting of the theme in config file that belongs to out rpm package(/etc/os-release belongs to centos-release.rpm package). But setup theme in /etc/os-release is not good for us because all OS for our customers installations will be centos 7(8)(and we don't want to change $ID and $VARIAND-ID in fresh system as described at https://github.com/cockpit-project/cockpit/blob/master/doc/branding.md because this file in belong to package(centos-release) and this file used by many services in the system, such as systemd). May be cockpit team can introduce more flexible theme selection mechanism?

**Comment by larskarlitski** [comment]
Hi! We don't think it makes sense to basing the theme on something other than `/etc/os-release`. Lots of tools take cues from this file, and we'd like to be consistent.

If your product is sufficiently different from centos, I would change `/etc/os-release` to contain a different `ID` or `VARIANT`. Cockpit [looks for](https://github.com/cockpit-project/cockpit/blob/master/doc/branding.md) `$ID-$VARIANT_ID` and `$ID` in the branding directory.

Alternatively, you can rebuild Cockpit itself if you're making changes to it already anyway.

(Note that we don't consider `/usr/share/cockpit/branding` as a drop-in directory for other packages. If you do put some directory there, it might conflict with something from the cockpit package in the future.)

**Comment by atb00ker** [comment]
For people who just want to change the wallpaper and land here, this works: https://github.com/mcodato/cockpit-branding-example
