### ISSUE TITLE
Disconnects on reboot of remote device.

### ISSUE THREAD

**Issue by kylejericson** [cockpit-project/cockpit#12538]
Sorry if this is a dumb question.

If I add in a system either by ip or hostname and then do a reboot they never connect back to my Cockpit server. Is there something I'm missing. I install cockpit on the server and then on the other device I want to connect to I install cockpit. I have tried the systemctl enable and start commands on the remote server.

**Comment by marusak** [comment]
Hey, sorry for the late reply.
Can you please better describe what are you doing on which machine?

**Comment by martinpitt** [comment]
Too vague, no reply in a year.
