### ISSUE TITLE
File Editor?

### ISSUE THREAD

**Issue by Fenny** [cockpit-project/cockpit#12581]
Is cockpit working on some kind of file editor / manager?

I loved adjenti to just edit some server files from the browser.

**Comment by marusak** [comment]
No, there is currently no work on anything like this (at least to my knowladge).
It could be a separate plugin based on [start-kit](https://github.com/cockpit-project/starter-kit)

Also related https://github.com/cockpit-project/cockpit/issues/12338

**Comment by marusak** [comment]
Closing this in favor of separate project.

**Comment by martinpitt** [comment]
Check out https://github.com/45Drives/cockpit-navigator , it looks quite cool!
