### ISSUE TITLE
Checkbox has undesired behavior

### ISSUE THREAD

**Issue by pdonlon** [cockpit-project/cockpit#1258]
![](http://i.imgur.com/R47whTi.png)

After clicking into a network, if the network is unavailable and the user clicks the connect automatically checkbox it will uncheck itself in about a second.

![](http://i.imgur.com/h7MpaQs.png)

**Comment by stefwalter** [comment]
Typically we shouldn't just have checkboxes randomly sitting on pages. They're a usability problem.

**Comment by pdonlon** [comment]
Would a switch be a better option?

![](http://i.imgur.com/RuyZIxH.png)

**Comment by stefwalter** [comment]
@andreasn A switch typically turns something on and off right away, and doesn't only toggle a setting. Maybe @mvollmer knows if there are other connection global settings that could be placed in a dialog.

**Comment by pdonlon** [comment]
True, but this is not always the case, iOS uses toggles instead of checkboxes in all cases even when not making changes right away. In cockpit's case there is no actual save button on the screen so it is happening on the next connection in the same way iOS uses their toggle for next ring.

This also seems like the right spot for it to could go (above the configure button and on the same line as "connect automatically").

![](http://i.imgur.com/dF6GX3o.png)

**Comment by mvollmer** [comment]
The specific bug is fixed: the "connect automatically" setting is not offered for interfaces that don't have any settings yet, such as unavailable ones.
