### ISSUE TITLE
update ubuntu backports to cockpit 200

### ISSUE THREAD

**Issue by luixal** [cockpit-project/cockpit#12590]
Not sure how do you handle this, but I've seen build 200 is already in ubuntu's enoan repos but bionic backports are still in build 199.

Is the 200 being published to bionic backports?

**Comment by martinpitt** [comment]
I will publish 202 next Wednesday, once it lands in eoan. Sorry for missing the last two releases, holidays got in between :-)

**Comment by ejjoman** [comment]
Any news on this? I would like to try the new features, too :)

**Comment by martinpitt** [comment]
I finally backported the current 202.1 to 19.04 and 18.04 LTS: https://launchpad.net/ubuntu/+source/cockpit

Will still need ~ 2 hours to build and publish.
