### ISSUE TITLE
unavailable network behavior

### ISSUE THREAD

**Issue by pdonlon** [cockpit-project/cockpit#1259]
Is there anything in this screen that the user can do with an unavailable network?

![screenshot from 2014-09-27 13 49 10](https://cloud.githubusercontent.com/assets/2906828/4431596/ad58332c-466e-11e4-9249-ca5c27373a66.png)

What if we restricted access to unavailable networks on this page?

![screenshot from 2014-09-27 13 48 56](https://cloud.githubusercontent.com/assets/2906828/4431598/c775cdb4-466e-11e4-87de-7b51faeb1ea2.png)

We could restrict access in two ways. One we could let the user click the unavailable network but disallow them to go further and producing a popup saying that the network is unavailable. The other option we could do is just to not allow unavailable networks to be clicked all together.

**Comment by mvollmer** [comment]
> What is it that makes it not available? Is it broken or missing?

I don't know exactly.  I normal wired interface without a cable seems to be "unavailable".

**Comment by mvollmer** [comment]
Let's not offer any configuration for unavailable devices, and let's also disable the On/Off button.
