### ISSUE TITLE
machines: Dialog to import a VM reads "Create new VM"

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#12614]
Cockpit version: 201
Page: Machines

Dialog to import a VM reads "Create new VM".

![image](https://user-images.githubusercontent.com/11140201/63428538-114c8f00-c418-11e9-9e4c-2d4cd65003ab.png)

**Comment by KKoukiou** [comment]
I am not sure we should change the working here - we do create a new VM but we use a disk that we import instead of creating a new one.

**Comment by Gundersanne** [comment]
I'm not exactly sure anymore who mentioned this but I opened the issue to see what you'd think. Honestly if create is truer to what it's doing then don't change it.

**Comment by MetalDent** [comment]
Hi, anyone working on this issue?

**Comment by KKoukiou** [comment]
@MetalDent no, do you want to post a fix?

**Comment by MetalDent** [comment]
I think it should be `Import A Virtual Machine` and  `Create` can be changed to `Import`

**Comment by KKoukiou** [comment]
> I think it should be `Import A Virtual Machine` and `Create` can be changed to `Import`

Sure, I am ok with this change, feel free to post a fix.
