### ISSUE TITLE
Consistent delete buttons

### ISSUE THREAD

**Issue by pdonlon** [cockpit-project/cockpit#1261]
In networking we use a red delete button but in containers we just use default colored ones.

Networking:

![screenshot from 2014-09-27 14 12 50](https://cloud.githubusercontent.com/assets/2906828/4431671/840c8992-4672-11e4-9fb6-87d6a73697a5.png)

Containers:

![screenshot from 2014-09-27 14 15 15](https://cloud.githubusercontent.com/assets/2906828/4431672/8d58d6d6-4672-11e4-8460-5126cf80a8f3.png)

![screenshot from 2014-09-27 14 15 29](https://cloud.githubusercontent.com/assets/2906828/4431673/93a0b6a8-4672-11e4-80e6-911cb334a4b6.png)

We should either make all the delete buttons red or the default color.

**Comment by stefwalter** [comment]
Fixed in #1732 #1741
