### ISSUE TITLE
Determining IP address of machine that entered cockpit

### ISSUE THREAD

**Issue by dgomes5** [cockpit-project/cockpit#12625]
I’ve been making my own packages within cockpit using its API. 

One package I want to create involves opening/display my server’s applications (disk tools, file manager, etc) on a separate machine.
 
My main problem is coming up with a way on determining whether cockpit opened from the server’s web browser or another machines’, as I also want to have this functionality from the server machine.

Is there a way to get the IP address of the machine that entered cockpit and give it to cockpit.spawn()?

Here’s how I intend on using cockpit.spawn:

cockpit.spawn([“bin/sh”, “-c”, “DISPLAY=ipaddress:7.0 gnome-disks”]);

Also, this other machine does not have cockpit installed. It is only logging into cockpit through the web browser. 

I hope my question is clear enough...

**Comment by marusak** [comment]
I am not sure if I follow, but lets try:
If you want to just know what user typed into browser to get to the login page, `window.location.hostname` should suffice. Even when you switch to different host, this still stays the same.

If you mean to get IP address of machine on which you opened browser, then not. (Only if browser would expose that).

**Comment by asilberschneider** [comment]
@dgomes5 If you have pursued your original approach, have you been able to find a way to determine the IP address of the client machine? (as browsers do not expose that to the code that they run)
