### ISSUE TITLE
cockpit-tls split regression with multiple listen ports

### ISSUE THREAD

**Issue by jciesla** [cockpit-project/cockpit#12627]
Cockpit version: 200

With the cockpit-tls introduction, it is no longer possible to set more than one listen port (in my case, 80 and 443).

As explained in https://cockpit-project.org/guide/149/listen.html, it is possible to set multiple listen ports in cockpit.socket file. When file is modified to listen on ports 80 and 443, cockpit-tls failed on start and indicate that it could not start with 2 listen ports.

**Comment by oleksandrborniak** [comment]
cockpit-201 is also affected.

**Comment by martinpitt** [comment]
Fixed in PR #12719
