### ISSUE TITLE
Use SSH friendly name stored in .ssh/config

### ISSUE THREAD

**Issue by rdiez** [cockpit-project/cockpit#12648]
I have carefully configured my servers in ~/.ssh/config like this:

Host MyFriendlyName
    HostName 192.168.1.123
    Port 1234
    User someuser
    IdentityFile /home/rdiez/.ssh/id_rsa_some_file
    CheckHostIP no

I would like to add that remote host to the Dashboard by just typing the user-friendly name "MyFriendlyName". At the moment, I have to manually enable the appropriate SSH key file, enter the remote host IP address and SSH port number, and the remote user login. Every time I change something in ~/.ssh/config, I have to remember to modify the remote server in Cockpit's Dashboard too.

Other tools allow just typing MyFriendlyName as the remote SSH server name, and they automatically pick up all SSH connection settings.

**Comment by Gundersanne** [comment]
Hai,

Cockpit uses libssh as the ssh client, and on platforms with cockpit>=183 and libssh>=0.8.5 user level configs should be supported (to some extent).

There are a few quirks atm, the User is always taken from the cockpit session. We're reconsidering if that was a good choice.

And the key pointed to by IdentityFile needs to be added to cockpit via the authentication menu. As cockpit feeds libssh the keys it knows one by one to try and authenticate.

Specifying a human-friendlier Host should work without a hitch though. I am not sure if libssh supports/respects the `CheckHostIP` directive. Alternatively the `StrictHostKeyChecking no` should be supportede.

**Comment by rdiez** [comment]
First of all, thanks for the information.

I am using Ubuntu 18.04, which comes with Cockpit 164. I guess it is too old then.
libssh is version 0.8.0, which would also be too old.

I think that the user name should not be taken from the cockpit session. The user name for each remote host tends to be different. The user name should be taken form the SSH configuration file for the corresponding remote host.

I do not understand why you need to manually add or unlock the key on every session. That is what the SSH configuration file is for: you enter the friendly hostname, and SSH automatically knows what key to use. This is a serious usability issue. I have many remote hosts to monitor, and I cannot add each key manually every time. Just for this reason I am looking for an alternative to Cockpit. By the way, if the key is not password-protected, Cockpit should "unlock" it automatically.

**Comment by martinpitt** [comment]
> I am using Ubuntu 18.04, which comes with Cockpit 164

Note: bionic-backports has a current version (202.1): https://launchpad.net/ubuntu/+source/cockpit

**Comment by Gundersanne** [comment]
@rdiez right, the user thing should be fixed in https://github.com/cockpit-project/cockpit/pull/12900

The key thing is somthing that I'm trying to address asap.

User-level config files is a relatively recent thing for cockpit, and still ironing out the quirks.

> > I am using Ubuntu 18.04, which comes with Cockpit 164
> 
> Note: bionic-backports has a current version (202.1): https://launchpad.net/ubuntu/+source/cockpit

Though you'd still need libssh>0.8.5

**Comment by martinpitt** [comment]
> The user name should be taken form the SSH configuration file for the corresponding remote host.

Correct, that's exactly what Sanne is fixing now.

**Comment by Gundersanne** [comment]
The configuration file should work once you have a libssh > 0.8.5 version. 

And @mvollmer 's current SSH work will also remove using the cockpit user as SSH user by default in the UI.

So marking this as solved.
