### ISSUE TITLE
Impossible to use a Let's Encrypt certificate with Cockpit

### ISSUE THREAD

**Issue by j75** [cockpit-project/cockpit#12664]
Cockpit version: 188-1
OS: Linux (Debian buster)

I am trying to combine Let's Encrypt certificate and private key as a cockpit certificate.
However, `remotectl certificate` claims that

> No PEM-encoded private key found

My private key actually uses elliptic curve, thus the PEM file is something like

> ----BEGIN EC PARAMETERS-----
> ...
> -----END EC PARAMETERS-----
> -----BEGIN EC PRIVATE KEY-----
> ...
> -----END EC PRIVATE KEY-----

Could this be the cause?

**Comment by Mrcoolfuyu** [comment]
Well....
I believe that cockpit does not support ECC cert yet
you can use a RSA one instead for now.

**Comment by j75** [comment]
It's a pity, as I wanted to reuse my Let's Encrypt certificate... :-(

**Comment by martinpitt** [comment]
Fixed in PR #13074
