### ISSUE TITLE
Unknown error when using FreeIPA based authentication

### ISSUE THREAD

**Issue by pveronneau** [cockpit-project/cockpit#1266]
After configuring central authentication using FreeIPA, I get a constant error:

 cockpit-ws: cockpit-session: gssapi auth failed: An unsupported mechanism was requested (Unknown error)

This leaves cockpit in an unusable state.

**Comment by tj13** [comment]
any update for this?

**Comment by stefwalter** [comment]
@tj13 Have you tried this: http://cockpit-project.org/guide/latest/sso.html

@tj13 What happens in your case? Is it identical to the above description?

**Comment by tj13** [comment]
@stefwalter thanks for your info.  
i want to add hosts in cockpit dashboard via account on FreeIPA. it works with following guide
http://cockpit-project.org/guide/latest/authentication.html#public-key

**Comment by martinpitt** [comment]
No response from original reporter, it works for tj13 as per the last comment, and we test IPA integration on all our supported OSes. If this happens with current OSes/Cockpit versions, please reopen.
