### ISSUE TITLE
cockpit/bionic-backports not work

### ISSUE THREAD

**Issue by HuJK** [cockpit-project/cockpit#12668]
I am using Ubuntu 18.04, and I want to copy and paste in terminal in cockpit. How do I upgrade to new version of cockpit? 
I tried apt install cockpit/bionic-backports ,and reboot. but it still not works:

![image](https://user-images.githubusercontent.com/15907444/64033072-4b3b3500-cb7e-11e9-8c83-6d3cfc165901.png)

**Comment by martinpitt** [comment]
For a new install you should use `apt-get install -t bionic-backports cockpit`, otherwise you will *just* install the metapackage itself, not any of `cockpit-machines`.

For upgrading all cockpit related packages on your existing installl, use something like this:

    apt install -t bionic-backports $(dpkg-query -W | awk '/cockpit/ {print $1}')

or just `apt upgrade -t bionic-backports` to upgrade *all* your packages to backports, but double-check what it's going to do there.

**Comment by dkebler** [comment]
This comment is worthy of putting in the install/upgrade docs
```
apt install -t bionic-backports $(dpkg-query -W | awk '/cockpit/ {print $1}')
```

**Comment by FredericLatour** [comment]
@martinpitt Yes, I believe that it's quite important to update the install documentation. It will prevent many frustrations and useless support over people asking about firewall missing and all that jazz ...

**Comment by jperquin** [comment]
> This comment is worthy of putting in the install/upgrade docs
> 
> ```
> apt install -t bionic-backports $(dpkg-query -W | awk '/cockpit/ {print $1}')
> ```

I am getting the following error after running this command:

```
Reading package lists... Done
E: The value 'bionic-backports' is invalid for APT::Default-Release as such a release is not available in the sources
```

**Comment by martinpitt** [comment]
@jperquin : Seems you disabled the backports repos in /etc/apt/sources.list or sources.list.d/? See https://help.ubuntu.com/community/UbuntuBackports how to enable them.
