### ISSUE TITLE
Terminal Graphical Errors

### ISSUE THREAD

**Issue by retr0gr4d3** [cockpit-project/cockpit#12667]
Cockpit version: 189
OS: Ubuntu Server 19.04
Page: Terminal

Description: when scrolling up in nano, the text overlaps and becomes illegible.

Steps to reproduce:
1. Open a file in nano that is quite long in length.
2. Scroll to the bottom of the file.
3. Scroll back up.

![image](https://user-images.githubusercontent.com/22956832/64024990-8c5a2780-cb33-11e9-8087-d3407104260b.png)

**Comment by marusak** [comment]
I think this is already with `xterm.js`. Can you please check if you can change color of the terminal (do you have `Appearance` above terminal) ? 

Anyway, you still use a bit older version of Cockpit, would it be possible for you to update, there has been some significant changes on `xterm.js` which is underlying library we use.

I tried this and it worked for me.

> Open a file in nano that is quite long in length.

What does quiet long mean?

**Comment by marusak** [comment]
@retr0gr4d3 ping

**Comment by retr0gr4d3** [comment]
Hey, sorry I haven't responded.

I do have Appearance above terminal, but this issue isn't very important.
