### ISSUE TITLE
fedora 31 docker support

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#12670]
This issue tracks cgroupsv2 support in docker.

Fedora 31 switched to cgroupsv2, and docker doesn't support that (yet).

**Comment by martinpitt** [comment]
Status on latest fedora-31 image: "docker" command and docker.service are provided by moby-engine, but cockpit.service [fails to start up immediately](https://bugzilla.redhat.com/show_bug.cgi?id=1746355) . `dnf install docker` just brings back moby-engine. moby-engine is a dependency of kubernetes, so it's already on the current images.

We could run check-docker and check-kubernetes with explicitly switching to cgroupsv1 for these tests. The bugzilla says that this is still a supported configuration option.

**Comment by martinpitt** [comment]
This is how to do it:

    grub2-editenv - set "$(grub2-editenv list | grep kernelopts) systemd.unified_cgroup_hierarchy=0"
    reboot

**Comment by martinpitt** [comment]
Obsolete now, we stopped shipping cockpit-docker in Fedora ≥ 31.
