### ISSUE TITLE
centos extra repo release

### ISSUE THREAD

**Issue by Schnuecks** [cockpit-project/cockpit#12710]
when will the latest version 201 arrive at the centos extra repo?
or should i use source tarball for the latest version?

best regards
schnuecks

**Comment by marusak** [comment]
We don't support CentOS-7 from cockpit master anymore and therefore we don't release the newest things in there either.

**Comment by Schnuecks** [comment]
Is it only CentOS 7 or is it CentOS in general.
Then please remove it from the list supported os. Thanks

**Comment by marusak** [comment]
> Is it only CentOS 7 or is it CentOS in general.

It is just CentOS 7, once CentOS 8 is available, we will support newest releases on it.
