### ISSUE TITLE
compile error about gnutls

### ISSUE THREAD

**Issue by cine0831** [cockpit-project/cockpit#12713]
Cockpit version: 202
OS: CentOS 7
Page: 

Steps to reproduce

1. make error 

make  all-am
make[1]: Entering directory `/root/src/cockpit-202'
  CC       src/tls/cockpit_tls-server.o
src/tls/server.c: In function ‘verify_peer_certificate’:
src/tls/server.c:338:18: error: ‘GNUTLS_E_CERTIFICATE_VERIFICATION_ERROR’ undeclared (first use in this function)
           return GNUTLS_E_CERTIFICATE_VERIFICATION_ERROR;
                  ^
src/tls/server.c:338:18: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [src/tls/cockpit_tls-server.o] error 1
make[1]: Leaving directory `/root/src/cockpit-202'
make: *** [all] error 2

2. gnutls version information
[root@centos7 tls]# rpm -qa |grep gnutls
gnutls-3.3.29-9.el7_6.x86_64
gnutls-c++-3.3.29-9.el7_6.x86_64
gnutls-dane-3.3.29-9.el7_6.x86_64
gnutls-utils-3.3.29-9.el7_6.x86_64
gnutls-devel-3.3.29-9.el7_6.x86_64

**Comment by martinpitt** [comment]
Indeed we dropped support for RHEL/CentOS-7 from cockpit master and thus recent releases. E. g. you already need to `--disable-ssh` to be able to build. But indeed the failure should be a bit cleaner, I'll bump the gnutls requirement in configure.ac.

**Comment by martinpitt** [comment]
... or, if it's easy enough to build against that old GnuTLS, do that. But still be warned that new releases could break any time again on CentOS-7.

**Comment by martinpitt** [comment]
Fixed in PR #12718
