### ISSUE TITLE
Centos 7 - System Updates link unavailable

### ISSUE THREAD

**Issue by hypertoast** [cockpit-project/cockpit#12746]
Cockpit version: 176
OS: CentOS Linux release 7.6.1810 (Core)
Page: System

"Bug Fix Updates Available". There is no hyperlink to the system updates page to see and apply updates

Steps to reproduce

1. Fresh Install of Cockpit
2. yum install PackageKit  pcp-system-tools pcp-doc
3. [calvin@mango ~]# pkcon get-updates
Getting updates               [=========================]
Starting                      [=========================]
Getting information           [=========================]
Finished                      [=========================]
Normal          bind-libs-lite-32:9.9.4-74.el7_6.2.x86_64 (updates)             Libraries for working with the DNS protocol
Normal          bind-license-32:9.9.4-74.el7_6.2.noarch (updates)               License of the BIND DNS suite
Normal          curl-7.29.0-51.el7_6.3.x86_64 (updates)                         A utility for getting files from remote servers (FTP, HTTP, and others)
Normal          device-mapper-7:1.02.149-10.el7_6.8.x86_64 (updates)            Device mapper utility
Normal          device-mapper-event-7:1.02.149-10.el7_6.8.x86_64 (updates)      Device-mapper event daemon
Normal          device-mapper-event-libs-7:1.02.149-10.el7_6.8.x86_64 (updates) Device-mapper event daemon shared library
Normal          device-mapper-libs-7:1.02.149-10.el7_6.8.x86_64 (updates)       Device-mapper shared library
Normal          glib2-2.56.1-4.el7_6.x86_64 (updates)                           A library of handy utility functions
Normal          glibc-2.17-260.el7_6.6.x86_64 (updates)                         The GNU libc libraries
Normal          glibc-common-2.17-260.el7_6.6.x86_64 (updates)                  Common binaries and locale data for glibc
Normal          kernel-3.10.0-957.27.2.el7.x86_64 (updates)                     The Linux kernel
Normal          kernel-tools-3.10.0-957.27.2.el7.x86_64 (updates)               Assortment of tools for the Linux kernel
Normal          kernel-tools-libs-3.10.0-957.27.2.el7.x86_64 (updates)          Libraries for the kernels-tools
Normal          kexec-tools-2.0.15-21.el7_6.4.x86_64 (updates)                  The kexec/kdump userspace component.
Normal          libcurl-7.29.0-51.el7_6.3.x86_64 (updates)                      A library for getting files from web servers
Normal          libssh2-1.4.3-12.el7_6.3.x86_64 (updates)                       A library implementing the SSH2 protocol
Normal          libteam-1.27-6.el7_6.1.x86_64 (updates)                         Library for controlling team network device
Normal          lvm2-7:2.02.180-10.el7_6.8.x86_64 (updates)                     Userland logical volume management tools
Normal          lvm2-libs-7:2.02.180-10.el7_6.8.x86_64 (updates)                Shared libraries for lvm2
Normal          microcode_ctl-2:2.1-47.5.el7_6.x86_64 (updates)                 Tool to transform and deploy CPU microcode update for x86.
Normal          python-2.7.5-80.el7_6.x86_64 (updates)                          An interpreted, interactive, object-oriented programming language
Normal          python-libs-2.7.5-80.el7_6.x86_64 (updates)                     Runtime libraries for Python
Normal          python-perf-3.10.0-957.27.2.el7.x86_64 (updates)                Python bindings for apps which will manipulate perf events
Normal          selinux-policy-3.13.1-229.el7_6.15.noarch (updates)             SELinux policy configuration
Normal          selinux-policy-targeted-3.13.1-229.el7_6.15.noarch (updates)    SELinux targeted base policy
Normal          systemd-219-62.el7_6.9.x86_64 (updates)                         A System and Service Manager
Normal          systemd-libs-219-62.el7_6.9.x86_64 (updates)                    systemd libraries
Normal          systemd-sysv-219-62.el7_6.9.x86_64 (updates)                    SysV tools for systemd
Normal          teamd-1.27-6.el7_6.1.x86_64 (updates)                           Team network device control daemon
Normal          tuned-2.10.0-6.el7_6.4.noarch (updates)                         A dynamic adaptive system tuning daemon
Normal          tzdata-2019b-1.el7.noarch (updates)                             Timezone data
Normal          vim-minimal-2:7.4.160-6.el7_6.x86_64 (updates)                  A minimal version of the VIM editor

**Comment by marusak** [comment]
This is because you are missing `cockpit-packagekit` package.

It would possibly make sense to advice installing this package when not available (as we do with pcp or so)

**Comment by hypertoast** [comment]
Terrific. Is it possible to see a list of all cockpit related packages available to install? Maybe I missed it somewhere in the documentation. I usually start building my systems with a minimal ISO.
Thanks @marusak

**Comment by marusak** [comment]
> Is it possible to see a list of all cockpit related packages available to install

Yes, there is this item in left side menu `Applications` but it is provided by the same package (`cockpit-packagekit`)

**Comment by marusak** [comment]
> Apart from the above listed packages, are there any other packages which are available but I do not have it installed?

sure, for example `cockpit-podman`, `cockpit-docker`, `cockpit-machines`, `cockpit-session-recording`, or some more specific like `cockpit-composer` or `cockpit-ostree`(this does not make sense on your system).

Also there can be third party plugins or it should be fairly simple to create your own with https://github.com/cockpit-project/starter-kit

**Comment by marusak** [comment]
Closing as it seems it was resolved
