### ISSUE TITLE
Can't launch due to missing tls directory

### ISSUE THREAD

**Issue by llamafilm** [cockpit-project/cockpit#12750]
Cockpit version: 202.1
OS: RHEL 7.7

After installing release 202.1 I was unable to connect.  Attempting to connect in a web browser crashed cockpit with error:

    cockpit-tls: failed to bind cockpit-ws socket /run/cockpit/tls/ws.8.sock: No such file or directory

If I create that directory with `mkdir /run/cockpit/tls` then I am able launch like this and it works:

    RUNTIME_DIRECTORY=/run/cockpit/tls /usr/local/libexec/cockpit-tls

However, it still does not work when run as a service.  I do `systemctl start cockpit.socket`
Then I can see the login page.  When I attempt to login I see "The cockpit package is not installed"

```
systemctl status cockpit.service
● cockpit.service - Cockpit Web Service
   Loaded: loaded (/usr/lib/systemd/system/cockpit.service; static; vendor preset: disabled)
   Active: active (running) since Mon 2019-09-09 14:25:35 PDT; 1min 54s ago
     Docs: man:cockpit-ws(8)
  Process: 14516 ExecStartPre=/usr/local/sbin/remotectl certificate --ensure --user=root --group= --selinux-type= (code=exited, status=0/SUCCESS)
 Main PID: 14524 (cockpit-tls)
   CGroup: /system.slice/cockpit.service
           └─14524 /usr/local/libexec/cockpit-tls

Sep 09 14:25:35 elliott_zfs systemd[1]: Starting Cockpit Web Service...
Sep 09 14:25:35 elliott_zfs systemd[1]: Started Cockpit Web Service.
Sep 09 14:25:36 elliott_zfs cockpit-tls[14524]: cockpit-tls: TLS handshake failed: A TLS fatal alert has been received.
Sep 09 14:25:36 elliott_zfs cockpit-tls[14524]: cockpit-tls: TLS handshake failed: A TLS fatal alert has been received.
Sep 09 14:25:36 elliott_zfs cockpit-tls[14524]: cockpit-tls: TLS handshake failed: A TLS fatal alert has been received.
Sep 09 14:25:36 elliott_zfs cockpit-tls[14524]: cockpit-tls: TLS handshake failed: A TLS fatal alert has been received.
Sep 09 14:25:41 elliott_zfs cockpit-session[14540]: pam_ssh_add: Failed to start ssh-agent
Sep 09 14:25:41 elliott_zfs cockpit-tls[14524]: cockpit-session: can't exec /bin/bash: Permission denied
```

**Comment by martinpitt** [comment]
This is normally created by `RuntimeDirectory=cockpit/tls` in cockpit.service. Apparently RHEL 7's systemd is too old to support that. You could add the mkdir  as an `ExecStartPre=` there. However, we don't support RHEL 7 any more from our master branch and current releases. As you apparently build these yourself, please use the rhel-7.7  or rhel-7.8 upstream branch for this.

**Comment by llamafilm** [comment]
I was trying to build from master previously, but today I installed the 202.1 release.  Are you saying I shouldn't use the release tarball on RHEL since it's made from master?

**Comment by martinpitt** [comment]
Yes, please use the rhel-7.8 branch for RHEL/CentOS 7.

**Comment by martinpitt** [comment]
Or rather, the releases done from it, like [195.3]](https://github.com/cockpit-project/cockpit/releases/tag/195.3).

**Comment by llamafilm** [comment]
Sorry for being obtuse, but how can one tell which releases are from a particular branch?  I only see one list of releases.

Also, the description for 202.1 says "Fix building on RHEL/CentOS 7"

**Comment by martinpitt** [comment]
Indeed, that "fix building" was some attempt to do that, but it's really half-hearted, and we just can't support it. I reopen this because we should fix our systemd dependencies to require the version that supports `RuntimeDirectory=`, which the RHEL 7 one apparently doesn't.
