### ISSUE TITLE
Modal in Kdump, Timer pages are not centered

### ISSUE THREAD

**Issue by leomoty** [cockpit-project/cockpit#12771]
Cockpit version: 202.1
OS: Fedora
Page: Services

This modal behaves different from the others thanks to a forced width, as in, it is not always centered: 

![image](https://user-images.githubusercontent.com/1463740/64723107-3cba1b00-d4a6-11e9-995f-289c89f14cb0.png)

And I guess "After" should be on the same line.

Nonetheless, pt_BR translation also breaks the <select> boundaries:

![image](https://user-images.githubusercontent.com/1463740/64723284-9e7a8500-d4a6-11e9-9e90-54bb803473a4.png)

**Comment by leomoty** [comment]
Had some issues uploading the 2nd image on the same comment, so here it goes:

![image](https://user-images.githubusercontent.com/1463740/64723345-bf42da80-d4a6-11e9-95d9-0e59bbe04559.png)

**Comment by marusak** [comment]
Also happens on kdump:
![weirdlyinttehcorrner](https://user-images.githubusercontent.com/12330670/75040216-8fb6e600-54ba-11ea-8156-9edbd3f2c8bc.png)

**Comment by KKoukiou** [comment]
Create Timer is fixed already - fixing the Kdump dialog in  #13649  
![Screen Shot 2020-03-04 at 11 23 10](https://user-images.githubusercontent.com/14921356/75869994-a76f6200-5e0a-11ea-9898-6eb8be27d914.png)

**Comment by leomoty** [comment]
@KKoukiou Was the dropdown wrapping fixed elsewhere? It looks good tho

**Comment by KKoukiou** [comment]
> @KKoukiou Was the dropdown wrapping fixed elsewhere? It looks good tho

Yes it was solved here https://github.com/cockpit-project/bots/commit/a6f960d18afb9f626b909c7edc5ba09ad0223129
