### ISSUE TITLE
Package update on remote cockpit instance does not finish

### ISSUE THREAD

**Issue by freaky-m0** [cockpit-project/cockpit#12779]
Cockpit version: 201 / 164
OS: Fedora 30 / Ubuntu 18.04.3
Page: 

I installed a Fedora 30 server and a Ubuntu 18.04.3 server (+ installed cockpit). Then i added the Ubuntu server to the cockpit instance on the Fedora 30 server. Sometimes when i update packages on the Ubuntu server with cockpit it just hangs. The wheel is spinning infinitely. Just a reboot of the ubuntu machine helps. After the reboot everything is "up to date". It doesn't depend on the updated package. Got it with kernel, systemd or cloud-init as I can remember now.

Is it because of the older cockpit version in Ubuntu?

Steps to reproduce

1. Install Fedora 30
2. Install Ubuntu 18.04.3 with cockpit
3. Add Ubuntu to the cockpit in Fedora 30 and update packages

<a href="https://ibb.co/wJz8cqV"><img src="https://i.ibb.co/pWLNhTc/grafik.png" alt="grafik" border="0"></a>

**Comment by martinpitt** [comment]
Sorry that we did not catch this on time. This report is far too old to still be actionable now.

This was in all likelyhood some issue with PackageKit, that it never finished the transaction for some reason. Knowing more would need some log inspection, but after 1½ years these are long gone.
