### ISSUE TITLE
`image-prepare` should use a tmpfile and rename it when done

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#12781]
Right now, `image-prepare fedora-30` will create `test/images/fedora-30.qcow2` straight away and link it into place.  That means that if the process is interrupted, you end up with a `fedora-30` link in the `test/images` directory, and the tests will try to run against that.

We should use a tempfile instead and rename it into place only when everything has run to the end successfully.

Alternatively: we could put `fedora-30.qcow2` in place, but not symlink it until the end.

**Comment by nguyeabcd55544** [comment]
`https://github.com/cockpit-project/cockpit/labels/good-first-issue
