### ISSUE TITLE
Setup authorized_keys for various user accounts via Cockpit

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1279]
It would be a nice feature (suggested by jscotka) to have a field in the user account manager for assigning authorized_keys for the admin, to be able to then log in (outside of Cockpit) via SSH easily. This is a common task admins do.

**Comment by stefwalter** [comment]
@jscotka This is done by the pull request that @petervo worked on. Part of this feature:

https://github.com/cockpit-project/cockpit/wiki/Feature:-Key-based-authentication

Thanks for the suggestion.

**Comment by jscotka** [comment]
Thanks for that. It is perfect feature.
