### ISSUE TITLE
Install cockpit without webservice for remote management

### ISSUE THREAD

**Issue by Aydan** [cockpit-project/cockpit#12801]
I'd like to install cockpit without the web service for remotely managing machines.
I tried to do that by installing cockpit-bridge.
I can add the remote machine, but then I get a not found page. What other packages do I need and would it make sense to have cockpit-bridge depend on them?

**Comment by martinpitt** [comment]
You need at least cockpit-system for the basic stuff(that will also pull in -bridge). And in addition the extra cockpit modules that you want to use, like -networkmanager, -machines, etc.

**Comment by Aydan** [comment]
Since the "cockpit" package pulls in all needed packets to work I'd think it would make sense to have "cockpit-bridge" do the same or have a metapackage "cockpit-remote" that does, to ease installation with and without the webservice.
