### ISSUE TITLE
Cockpit with Nginx as reverse proxy fails after update

### ISSUE THREAD

**Issue by Omaha2002** [cockpit-project/cockpit#12802]
Cockpit version: 202.1
OS: Ubuntu 18.04

just updated Cockpit from 199 to 202.1 

Relevant parts of the system log are also useful:

Steps to reproduce

1. update cockpit 199 -> 202.1
2. access webpage for cockpit
3. eror: ERR_TOO_MANY_REDIRECTS

tried all possible guides to use NGINX as reverse proxy, no solution.

**Comment by Omaha2002** [comment]
Fixed it by following this guide:
https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX

After following guide I still got the redirect error, changed:

proxy_pass http://127.0.0.1:9090;       to       proxy_pass http**s**://127.0.0.1:9090;

and it worked.

**Comment by egormkn** [comment]
I had the same problem. Maybe this issue should be reopened as it seems that the latest version of Cockpit uses the scheme from proxy_pass directive instead of X-Forwarded-Proto header to determine whether the connection is encrypted.

**Comment by andreymal** [comment]
Same problem.

A workaround is [to use AllowUnencrypted=true](https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX#insecure-connections), but Cockpit should read X-Forwarded-Proto.

**Comment by aso930** [comment]
I have a problem where proxying with tls enabled on cockpit does not work.

`journalctl -u cockpit` shows the following error:
```
cockpit-tls: gnutls_set_default_priority failed: The request is invalid.
```

I have configure both cockpit and the nginx server block as described in the wiki:

Note: I've changed the domain name to a generic one.

`/etc/cockpit/cockpit.conf`
```
[WebService]
Origins = https://cockpit.example.com wss://cockpit.example.com
ProtocolHeader = X-Forwarded-Proto
```

`/etc/nginx/conf.d/cockpit.conf`
```
server {

    listen      80;
    listen      443;
    server_name cockpit.example.com;
    ssl on;
    ssl_certificate /etc/letsencrypt/live/cockpit.example.com/cert.pem;
    ssl_certificate_key /etc/letsencrypt/live/cockpit.example.com/privkey.pem;
    access_log /var/log/nginx/cockpit-access.log main;
    error_log /var/log/nginx/cockpit-error.log;
    location / {
        # Required to proxy the connection to Cockpit
        proxy_pass https://127.0.0.1:9090;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Required for web sockets to function
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Pass ETag header from Cockpit to clients.
        # See: https://github.com/cockpit-project/cockpit/issues/5239
        gzip off;
    }
}
```

OS:
```
#cat /etc/fedora-release 
Fedora release 30 (Thirty)
```

Cockpit version:
```
cockpit-dashboard-213-1.fc30.noarch
cockpit-ws-213-1.fc30.x86_64
cockpit-bridge-213-1.fc30.x86_64
cockpit-system-213-1.fc30.noarch
cockpit-storaged-213-1.fc30.noarch
cockpit-packagekit-213-1.fc30.noarch
cockpit-networkmanager-213-1.fc30.noarch
cockpit-213-1.fc30.x86_64
cockpit-docker-213-1.fc30.x86_64
```
