### ISSUE TITLE
Suggestion: Start/stop button on main services page

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1280]
Suggested from test day: Similar to docker containers page, may want a start/stop button the main services page. This is a common action.

**Comment by martinpitt** [comment]
I would really not do that. Without any details (state, logs, description, relations), you often don't know whether it even makes sense and is desirable to stop/restart a service. We don't want users to click around willy-nilly on random services. I tentatively close this, but please do feel free to slap my hand and reopen if you disagree. @andreasn, WDYT?

**Comment by andreasn** [comment]
I think it makes sense to keep the actions only on the service page, so I'm in favor of closing this.
