### ISSUE TITLE
Angular vulnerabilities 

### ISSUE THREAD

**Issue by larrycameron80** [cockpit-project/cockpit#12815]
Arbitrary Code Execution
Vulnerable module: angular
Introduced through: angular@1.3.20
Detailed paths
Introduced through: CockpitDevelopmentDependencies@clearos/cockpit#77b6a9e5dc9649104f1f40a054dbec82b14a40dd › angular@1.3.20
Remediation: Upgrade to angular@1.5.0.
Overview
angular is a package that lets you write client-side web applications as if you had a smarter browser. It also lets you use HTML as your template language and lets you extend HTML’s syntax to express your application’s components clearly and succinctly.

Affected versions of this package are vulnerable to Arbitrary Code Execution via unsafe svg animation tags.

**Comment by marusak** [comment]
Thanks for the report. Where does this come from? It seems like some scan was run (somewhere on clearos).
Master does not have anything with angular anymore. So there is not much was can do about it.
What version of cockpit do you use?
But this needs to be reported to clearos maintainers (or how does it work - does it pick what is currently in RHEL/CentOS?) Possibly bugzilla should be opened against rhel7 and rhel8 to upgrade angular version.
I keep this one open to find solution for this, but I am closing all others. I list them here to keep track of them and also to have some reference in them.
#12816 #12817 #12818 #12819 #12820 #12821 #12822

**Comment by larrycameron80** [comment]
The scan output came from Snyk.

**Comment by marusak** [comment]
> The scan output came from Snyk.

On what version of Cockpit?

**Comment by marusak** [comment]
This does not affect master anymore
