### ISSUE TITLE
Activating bond devices after creating

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1282]
vbenes: do not activate bond device immediatelly after creating. I've created bond with same network interfaces and it was unpredictable what happen. I think that there is is possoble to have another config for same physical device. Then you have to deactivate devices in old bond and activate them in new one. Or second possibility is to allow to create bond only for device what are not attached to another bond. (it is part what should be consulted with NM  (vbenes)

**Comment by mvollmer** [comment]
Let's just go with whatever NM does.
