### ISSUE TITLE
Docker service doesn't start automatically on reboot

### ISSUE THREAD

**Issue by Shurov** [cockpit-project/cockpit#12834]
All docker containers don't start after server reboot (made from inside Cockpit). So, I believe, the whole docker-service doesn't start automatically.
Only after I open `Docker Containers` tab, the message "Connecting to Docker" is shown and after that containers are available.

**Comment by marusak** [comment]
This means that docker service is not enabled. You need to enable this service in order to start automatically. You can do this on `Services` page.
