### ISSUE TITLE
machines: buttons are glued together

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#12833]
Cockpit version: 202
OS: Fedora 30
Page: Machines

The dropdown button for `Send key` and the button for `Disconnect` are glued together.
Not a biggie really, but thought I might as well report.

![Screenshot from 2019-09-17 15-42-12](https://user-images.githubusercontent.com/209895/65046962-daf42800-d961-11e9-8fc5-a0905d1d920a.png)

**Comment by jatinAroraGit** [comment]
Hey there, 
I will like to work on this.

**Comment by marusak** [comment]
Hey @jatinAroraGit 
Like to hear you are interested.

First thing I would like to mention is that these buttons are from [patternfly](https://github.com/patternfly/patternfly-react/tree/master/packages/patternfly-3/react-console).
So ideally firstly you would figure out, if it is broken in their component - and if so, then would send fix to them. In case we just overwrite some css rules which break those, then we just need to make those rules better on our side.

Do you need any help to start working on this?

**Comment by KKoukiou** [comment]
I reported it in the correct component.
@andreasn do you want this open here as well?

**Comment by andreasn** [comment]
Nah, if the issue is in Patternfly, I don't think there is any reason for having it mirrored here.
