### ISSUE TITLE
Group all pages related to Cockpit development into one navigation entry

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#12847]
Cockpit keeps growing main navigation on the side for new developer-only features.

Instead of having a navigation item for every entry, there should be one called something like "Developer" or "Developer Playground".

All the pages that come from pkg/playground/ should be listed there.

Benefits:
1. We can have Cockpit feel closer to what we ship
2. Any developer-related videos or screenshot will be closer to what people will see, instead of having a bunch of debug entries

**Comment by garrett** [comment]
I mentioned this in the face to face and talked with @mvollmer on IRC about it, who said he can probably find some time to address this soon (possibly even in this sprint).

**Comment by mvollmer** [comment]
As  @martinpitt mentioned, one option is to simply not have navigation entries for playground pages at all.  Developers can still access them by typing in the URL.

But some navigation would be nice, as it is hard to remember all the funny spellings of the pages.

So I'll combine both ideas: We make a "Development" page that lists all existing playground pages as subpages, and we don't make a navigation entry for the top-page in the shell.  It's easy to remember a single URL "..../playground" and then we can click from there to the specific page we want.

**Comment by garrett** [comment]
@mvollmer There should be links to all the page from the top-level page, however. (But they can just be simple links for those additional pages that are currently unlisted.)

Also, we could do the alt-click on the user menu trick and hide the page in the menu, like we do for the tasklist.

**Comment by mvollmer** [comment]
#12850 has the first part: Grouping the pages behind a single navigation entry. 

What about also removing the "Development" entry from the shell navigation?  Is that worth it?  I'd now say: No, let's leave it in.

**Comment by marusak** [comment]
> What about also removing the "Development" entry from the shell navigation? Is that worth it? I'd now say: No, let's leave it in.

Agree, lets leave it in, it is one item and makes it so much better discoverable for new developers and also makes it practical for current developers :)

**Comment by garrett** [comment]
Yep, agreed. Leave it in. If we want to change that in the future, then we can in another PR.

:+1:

**Comment by martinpitt** [comment]
I'm in favor of a single "Development" menu entry that lists all the available subpages. Then we also expose e. g. the speed test better. Thanks!

**Comment by mvollmer** [comment]
> I'm in favor of a single "Development" menu entry that lists all the available subpages.

We also need it for the page status tests: They want to put an icon on some menu entry.
