### ISSUE TITLE
update plugin wrongly labelling rpms as bug fixes when there's no supporting information.

### ISSUE THREAD

**Issue by csdfgraham** [cockpit-project/cockpit#12876]
Cockpit version: 195.1
OS: Fedora & RHEL7x
Page: updates

Updates are being marked as bug fixes even when the rpm contains no information relating to bug fixes. It should default to "unknown" in this situation.

Steps to reproduce:

1.  install an older version of an rpm that does not contain a changelog or any bug fix information at all. A good example is "ethtool".  Might be easier to reproduce using an older version of RHEL7 and look for "ethtool" in the updates page.
3. Load the updates page in cockpit.
4. Clicking on the ethtool package will open the details panel for the package, it will not show any bug fix or change log info, but will be labelled as a bug fix.

**Comment by marusak** [comment]
Does it show some number next to the bug icon? See the picture. The first item does not have any bug fixes (thus no number next to it) and the second one has one bug fix. Does it show "1" for you but when you open the item it does not list any bugs?

![somebugswsnobugs](https://user-images.githubusercontent.com/12330670/65574942-003ef280-df6f-11e9-979a-3e89282ac4fb.png)

Saying that, I find it confusing there is bug icon with no number next to it. It should be enhancement in such case (ideally using https://fontawesome.com/icons/bolt icon to be the same as bodhi does it)

**Comment by csdfgraham** [comment]
No number is displayed for me for ethtool and other rpms that probably lack a changelog.  Like you say in the case when there is no bug/errata info it should default to "enhancement" rather than "bug".

**Comment by marusak** [comment]
I was looking into it a bit and here are some notes:

1. Maintainer can release new update as bugfix, but not specify any bug (which need to be bugzilla, so when they fix bug reported in github for example, or just fix bugs that they discovered by themselves they still mark it as bugfix). Random [example](https://bodhi.fedoraproject.org/updates/FEDORA-2019-7a2b75cc2f)
2. There is `Update type` and `Update severity` in bodhi. Severity is from `low` to `urgent` and type is from `newpackage` to `security` (see https://bodhi.fedoraproject.org/updates/new). But we show column `severity` in which we show either `security`, `bugfix` or `enhancement`. This is mostly causing the confusion.
3. When severity is not specified (which is default option when doing bodhi update) then it has value which we represent as bug fix.
4. Packagekit (which we use as backend) does not provide type of update

**Comment by martinpitt** [comment]
This is a rather philosophical argument -- we need to default to some severity, and without any information from errata or the changelog one guess is as good/bad as the next one. I think "bug fix" is a nice middle-ground that doesn't under-estimate the importance too much.

**Comment by csdfgraham** [comment]
The displayed information is much improved when using a subscribed system, which enables the use of the errata database.  It would nice if there was an alternative so you could get as good information on a non-RH system.

**Comment by liberodark** [comment]
Add link of this problem is not cockpit / packagekit is change on centos 8
https://github.com/liberodark/nrpe-installer/issues/10

**Comment by martinpitt** [comment]
Closing this now. This is the API provided by bodhi/dnf/packagekit, and at that level we can't really divine new information.
