### ISSUE TITLE
communication to node-dbus

### ISSUE THREAD

**Issue by zombinary** [cockpit-project/cockpit#12885]
Cockpit version: 178
OS:
ubuntu 16.04 LTS

I have some trouble to send dbus messages with cockpit.dbus().call() to the npm package 
**'node-dbus'/'node-dbus-as-promised'**.
With 'dbus-send' the nodejs application return a message. And also you can find the dbus server in dbus **ListNames**. But with cockpit.dbus() i recived an error message '**"not-found"**' Independently if the nodejs dbus server running or not.

have i forgotten to register the service correctly?
do I have to support certain methods or signals in the nodejs application?

Steps to reproduce

1.` $ git clone https://github.com/Shouqun/node-dbus.git`
2. `$ cd node-dbus` 
3. `$ npm install`
4. `$ node example/service.js`
5. the nodejs dbus server running correctly:
```
$ dbus-send --dest=nodejs.dbus.ExampleService --type=method_call --print-reply /nodejs/dbus/ExampleService nodejs.dbus.ExampleService.Interface1.GetNameList
> method return time=1569520377.587239 sender=:1.1076 -> destination=:1.1077 serial=101 
> reply_serial=2
>    array [
>       variant          string "Fred"
>       variant          string "Stacy"
>       variant          string "Charles"
>       variant          string "Rance"
>       variant          string "Wesley"
>       variant          string "Frankie"
>    ]
```

6. Add this code lines in cockpit
```
        const sphere_dbus = cockpit.dbus('nodejs.dbus.ExampleService', { bus: "session" });
        sphere_dbus.call('/nodejs/dbus/ExampleService', 'nodejs.dbus.ExampleService.Interface1', 'GetNameList')
                .then((reply) => {
                    console.log('reply: ', reply);
                })
                .catch((e) => {
                    console.log('error: ', e);
                    reject(e);
                });
```

7. The cockpit dbus call return with an error 
`error:  ue {problem: "not-found", name: null, message: "not-found", toString: ƒ}`

**Comment by martinpitt** [comment]
I haven't tried this in detail, but my first hunch would be that you run `node example/server.js` in a session outside of cockpit. Thus that session and the cockpit session (check the Terminal page) both have a *different* session D-Bus. Does that work if you run server.js inside Cockpit's terminal?

**Comment by zombinary** [comment]
I'm in trouble to run the `example/service.js`  (this is the correct example file) in the cockpit terminal.
In the cockpit terminal the dbus return an error and i does not find the correct configuration.
```
.../node_modules/dbus/lib/bus.js:24
                self.connection = _dbus.getBus(1);
                                        ^

Error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
    at new module.exports (/home/zombinary/workspace/cockpit-sphere/dbus-aurora/node_modules/dbus/lib/bus.js:24:27)
    at Function.DBus.getBus (/home/zombinary/workspace/cockpit-sphere/dbus-aurora/node_modules/dbus/lib/dbus.js:39:9)
    at Function.DBus.registerService (/home/zombinary/workspace/cockpit-sphere/dbus-aurora/node_modules/dbus/lib/dbus.js:78:17)
    at Object.<anonymous> (/home/zombinary/workspace/cockpit-sphere/dbus-aurora/node_modules/dbus/examples/service.js:4:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
```

**Comment by martinpitt** [comment]
If you run anything on a custom D-Bus (not the system or session one), then you need to supply the address to cockpit.dbus(address).

This report is very old and stale. I close it now to clean up our bug tracker, right now it is not actionable.
