### ISSUE TITLE
Cockpit not allowing spaces in Virtual Machine Names

### ISSUE THREAD

**Issue by spectrumcomputing** [cockpit-project/cockpit#12893]
Cockpit version: cockpit-203-1.fc30.x86_64  
OS: Fedora 30
Page: Machines

Creating a new Virtual Machine with a space in the name causes an error

1. Create a new virtual machine and add a space in the name. For example 'Ubuntu Server 18.04'
2. Complete the other boxes, then click create VM

![Screenshot from 2019-09-29 19-41-25](https://user-images.githubusercontent.com/38283339/65837647-e9432c00-e2f1-11e9-9436-9b73b03f66ef.png)
![Screenshot from 2019-09-29 19-43-53](https://user-images.githubusercontent.com/38283339/65837651-f06a3a00-e2f1-11e9-97b3-89b9b79c57ea.png)

If this is not possible to fix, then is it possible for the 'error' to be caught when you click away from the 'Name' field, rather than getting an error when you click OK? An other option might be to have a 'Tool Tip'?

Thanks very much.  I'm loving testing Cockpit!

**Comment by iokaravas** [comment]
I'm seeing that Cockpit relies on QEMU/Libvirt, so the name is actually the Domain name of the virtual machine / configuration [as described here.](https://libvirt.org/docs/libvirt-appdev-guide-python/en-US/html/libvirt_application_development_guide_using_python-Guest_Domains.html#libvirt_application_development_guide_using_python-Guest_Domains-Domain_Overview) Unfortunately as the documentation states, it should be a short name and use only characters a-Z,0-9,-,_. 

In a personal note, I think it makes it easier to access the configuration from CLI as well as making it portable. I wouldn't say no to having a nice name *and* a domain name for it but it might be considered more of a new feature and not a fix.

I'm also loving Cockpit! :)

**Comment by spectrumcomputing** [comment]
Thanks for the comments.  I know that GNOME boxes is a different product, but that allows me to add spaces, and I believe (although I'm certainly not an expert) it uses the same technology.

![Screenshot from 2019-09-30 18-47-15](https://user-images.githubusercontent.com/38283339/65902714-eceab780-e3b2-11e9-9566-60e1f15d189e.png)

**Comment by marusak** [comment]
When you notice the error message, it states that `Storage object name` cannot contains spaces.
There is this "feature" that we autogenerate disk names from VM's name.
There also is currently PR with [this](https://github.com/cockpit-project/cockpit/pull/12716/commits/b0f100311f6ba2450ea7825d3c6105857d4f042b) commit, which would not allow spaces in VM names to prevent this problem. But I think we should just edit the name (by removing spaces) and use that as disk name.

WDYT @KKoukiou

**Comment by spectrumcomputing** [comment]
Thank you @marusak 

That sounds perfect.

**Comment by KKoukiou** [comment]
> When you notice the error message, it states that `Storage object name` cannot contains spaces.
> There is this "feature" that we autogenerate disk names from VM's name.
> There also is currently PR with [this](https://github.com/cockpit-project/cockpit/pull/12716/commits/b0f100311f6ba2450ea7825d3c6105857d4f042b) commit, which would not allow spaces in VM names to prevent this problem. But I think we should just edit the name (by removing spaces) and use that as disk name.
> 
> WDYT @KKoukiou

This is exactly the reason. Thanks @marusak! We will be replacing from now on spaces with underscores when creating new VMs, I hope that will work for you.
See https://github.com/KKoukiou/cockpit/commit/2c95d336f515904dffcb97678811156d4ac75f1c
