### ISSUE TITLE
Add "Manufacturer" field to Drive details tab

### ISSUE THREAD

**Issue by schopenhauer** [cockpit-project/cockpit#12915]
Page: Storage
File: cockpit/pkg/storaged/drive-details.jsx 

It would be nice to add the manufacturer of a HDD/SDD to the Drive details tab in the Storage section.

**Comment by andreasn** [comment]
Is there an easy way to get this value from an API?

**Comment by leomoty** [comment]
The udisks2 dbus call returns the vendor field alongside others, but for all my drives the vendor is empty.

http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Drive.html#gdbus-property-org-freedesktop-UDisks2-Drive.Vendor

**Comment by sghosh151** [comment]
![Screenshot from 2020-03-29 15-27-15](https://user-images.githubusercontent.com/6975708/77858529-2b322980-71d2-11ea-85e3-423561ae30a2.png)

Still needed?

**Comment by marusak** [comment]
Model contains the name in majority of cases and vendor from udisks is not set. So not much we can do there.
