### ISSUE TITLE
getting error "Storage can not be managed on this system."

### ISSUE THREAD

**Issue by grexe** [cockpit-project/cockpit#12911]
Cockpit version: 204
OS: Archi/Manjaro Linux x64
Page: Storage

I have a recent system (EFI, AMD Zen, Asus mobo with Samsung EVO 860 SSD (NVM.e) and an 8TB SATA hard drive), but the storage module just gives me the error in the title.
No further information is available.
I have tried installing `smartmontools` but that didn't help.

**Comment by grexe** [comment]
seems the module needs the "storaged" package to be installed, which I couldn't find for Arch.
Is this only for volume management?
Is there a module for checking drive health a la smartmontools?

**Comment by schopenhauer** [comment]
Cockpit version: 204
OS: Fedora 31 Server Edition
Page: Storage

I have occassionally seen the same error message (_Storage can not be managed on this system_), but a simple refresh helped to get to a functioning "Storage" page.

**Comment by mvollmer** [comment]
> seems the module needs the "storaged" package to be installed, which I couldn't find for Arch.

These days it needs "udisk2".  UDisks2 is needed for everything and the page indeed shows the "Storage can not be managed" error when it is missing.

Could you confirm wether you have "udisks2" installed?  If not, could you try to figure out how that has happened?  There should be enough dependencies in our packages to prevent that from happening.

**Comment by mvollmer** [comment]
> I have occassionally seen the same error message (_Storage can not be managed on this system_), but a simple refresh helped to get to a functioning "Storage" page.

Interesting, this might be a separate issue.  Did this also happen with earlier versions of Cockpit than 204?

Could you try to figure out more details about when this happens exactly?  For example, is the udisks2 daemon running before you load the page, or not?  (`systemctl status udisks2`)

**Comment by schopenhauer** [comment]
It seems like the service `udisks2` is not started yet, before opening the "Storage" tab, but is only activated once the "Storage" page is requested. Maybe a delay in loading `udisks2` leads to the above error message?

If it helps, please see below the "Storage Logs" shown in Cockpit.

```
7:46 PM g_object_notify: object class 'UDisksLinuxBlockObject' has no property named 'block-lvm2'
7:46 PM g_object_notify: object class 'UDisksLinuxBlockObject' has no property named 'physical-volume'
7:46 PM g_object_notify: object class 'UDisksLinuxBlockObject' has no property named 'block-lvm2'
7:46 PM g_object_notify: object class 'UDisksLinuxLogicalVolumeObject' has no property named 'logical-volume'
7:46 PM g_object_notify: object class 'UDisksLinuxVolumeGroupObject' has no property named 'volume-group'
7:46 PM g_object_notify: object class 'UDisksObjectSkeleton' has no property named 'manager-lvm2'
7:46 PM g_object_notify: object class 'UDisksObjectSkeleton' has no property named 'manager-iscsi-initiator'
7:46 PM Loading module libudisks2_lvm2.so...
7:46 PM Loading module libudisks2_iscsi.so...
```

**Comment by grexe** [comment]
@mvollmer thanks for the help, installing udisk2 solved the issue for me.
Now I only have to find out why the Network page does not work, but that's another issue...

**Comment by KKoukiou** [comment]
Let's discuss on seperate issue possible problems regarding the Network page. 
Closing this one since your issue seems to have been solved by installing udisks2.
