### ISSUE TITLE
Machines: CSS is duplicated; most (if not all) rules seem to be included twice?

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#12910]
On the Machines page, there are lots of duplicate CSS rules.

It makes debugging difficult and could be masking some bugs. In addition, it causes the browser and network connection to do a lot of extra work that's simply not needed (meaning: it bloats page load times).

Please find the source of the double imports and fix it (or them).

These duplicates all end up in machines.css, but I don't see an obvious reason why in machines.less. Is it webpack-related? Or are one of the imports importing some of the same files (like page.css)? (I looked at the files it imports and don't see imports in those...)

**Comment by marusak** [comment]
Wasn't this fixed by https://github.com/cockpit-project/cockpit/pull/13050 ? Or it was only a part of this problem? @garrett @KKoukiou

**Comment by garrett** [comment]
Nope; that was different. There's still duplication in machines.css for other reasons.

**Comment by garrett** [comment]
I looked again with Firefox Nightly, with original sources on (source mapping), and I see something is pulling in `react-core-base.css` twice. Also, `machines.less` _compiles in_ `page.css` twice too (instead of simply linking to it once — it's static CSS, after all).

**Comment by marusak** [comment]
I was debugging some other things and noticed that we include some css rules 4 times in one file and ship it like that. This seems like a bug, as it means users need to load files that are unnecessary bigger.

How to check this out:
1. On local build:
- `make` and then open for example `dist/kdump/kdump.css`
- look for `Bootstrap scss compilation will complain if these are not set` - it is 4 times there, with all of those `:root` overwrites. Also for example `.pf-m-redhat-font { ` rule is there 4 times, 

2. Check with installed package:
Checked on installed package `cockpit-kdump` from fedora repository and file `/usr/share/cockpit/kdump/kdump.css.gz` also contains it 4 times.

Theory what is the problem:
In `kdump` we include `lib/cockpit-components-onoff.scss`, `lib/page.scss`, `lib/form-layout.scss` and `base1/cockpit.css` and all of these bring these global rules, thus we include them 4 times.

**Comment by garrett** [comment]
We might want to consider switching to `@use` and `@forward` instead of using `@include`.

1. `@include` is deprecated and has some issues
   - > The Sass team discourages the continued use of the @import rule. Sass will gradually phase it out over the next few years, and eventually remove it from the language entirely. Prefer the @use rule instead.
     — https://sass-lang.com/documentation/at-rules/import
2. `@use` allows for namespacing, so we can keep better track of what file is being used where
3. I _think_ `@use` and `@forward` don't include the files multiple times? (Not sure; we'll need to test.)

There's a migration tool available to make this relatively easy:
https://sass-lang.com/documentation/cli/migrator

**Comment by KKoukiou** [comment]
We might want to consider switching to `@use` and `@forward` instead of using `@include`.
> 
>     1. `@include` is deprecated and has some issues
>        
>        * > The Sass team discourages the continued use of the @import rule. Sass will gradually phase it out over the next few years, and eventually remove it from the language entirely. Prefer the @use rule instead.
>          > — https://sass-lang.com/documentation/at-rules/import
> 
>     2. `@use` allows for namespacing, so we can keep better track of what file is being used where
> 
>     3. I _think_ `@use` and `@forward` don't include the files multiple times? (Not sure; we'll need to test.)
> 
> 
> There's a migration tool available to make this relatively easy:
> https://sass-lang.com/documentation/cli/migrator

We use @include in out scss code in only two places, 
```
$ git grep '@include'
pkg/lib/form-layout.scss:    @include widget-rules;
pkg/lib/form-layout.scss:    @include bump-up;
```
or I am missing something?

**Comment by garrett** [comment]
`@import`, not `@include`. Sorry. it's in the comment I quoted. I wrote the wrong thing.

**Comment by garrett** [comment]
I've looked into this a bit (by _attempting_ to port to `@use`/`@forward`), and realized it doesn't make sense to port from `@import` until we get source maps fixed (#13816).

The fix in #13804 goes a long way to solving the duplication issue. The `@import` switching probably can't do too much more for duplication (assuming it helps compilation only include a file once instead of multiple times).

**Comment by KKoukiou** [comment]
@garrett I think this is not still any issue. Can you confirm?

**Comment by garrett** [comment]
We still may be including duplicate CSS somewhere, but I haven't been running into it as an annoyance for some time now; I think it's fixed.
