### ISSUE TITLE
Centos 8 - Cockpit Preview get the RHEL Subscription Manager installed

### ISSUE THREAD

**Issue by PeterFalken** [cockpit-project/cockpit#12912]
Cockpit version: x204
OS: Centos 8
Page: Software

Centos 8 - Cockpit Preview get the RHEL Subscription Manager installed, this blocks the Software page based on PackageKit from showing available updates.

Steps to reproduce
1. Install a machine with Centos 8 ( Minimal or Server with GUI will do)
2. Enable the COPR cockpit-preview with "sudo $ dnf copr enable @cockpit/cockpit-preview"
3. Answer yes
4. Install or upgrade the cockpit package: "sudo dnf install -y cockpit"
5. This installs the RHEL subscription manager
6. Add a few useful cockpit add-ons: "sudo dnf install -y cockpit-packagekit cockpit-storaged"
7. Software page now complains that the system isn't registered so it can't check or show available updates.

![SubscriptionManager_Centos8_A](https://user-images.githubusercontent.com/2557898/66096472-55bf6480-e558-11e9-8fbd-2c3245d0218a.png)
![SubscriptionManager_Centos8_B](https://user-images.githubusercontent.com/2557898/66096473-55bf6480-e558-11e9-8e1b-0be32be870f0.png)
![SubscriptionManager_Centos8_C](https://user-images.githubusercontent.com/2557898/66096474-55bf6480-e558-11e9-93aa-47c6610f903a.png)

**Comment by martinpitt** [comment]
I was hoping PR #12359 would fix that, but apparently not in this case. Apparently subscription-manager gets enabled in dnf then? Do you have a /etc/yum/pluginconf.d/subscription-manager.conf, and does it have `enabled = 1`?

This apparently requires a more subtle heuristics -- perhaps we can check /etc/os-release for RHEL only, which would fix it in this case, but that would still leave "using non-RHEL repos on RHEL" failing (which we got through bugzilla).

Also, we ideally don't want subscription-manager{,-cockpit} installed on CentOS in the first place -- but the COPR package actually gets built on RHEL 8 Beta, so the dependency is there. But I wonder why you use the COPR package in the first place? CentOS 8 ought to have cockpit on board already?

**Comment by PeterFalken** [comment]
Martin,
CentOS 8 comes with cockpit version 185 - this is a bit old.
Before on CentOS 7.6, with the COPR cockpit-preview we could go up to version 196.
Since the repo has been removed for CentOS 7.x - there is no way to install a recent version of Cockpit through the yum/dnf commands.

Now that Centos 8 and RHEL 8 are out of beta - would there be a COPR repository for CentOS 8? Or would the RHEL repo be used for both CentOS & RHEL?

Regarding the file: _/etc/yum/pluginconf.d/subscription-manager.conf_ it is actually a link to: _/etc/dnf/pluginconf.d/subscription-manager.conf_ . It's there after installing cockpit through the CORP repo, and yes it does have enabled=1 on it. This file is not present on the default CEntOS 8 minimal install and cockpit is'nt installed on the minimal install either.

**Comment by PeterFalken** [comment]
Before enabling the COPR cockpit-preview repository on CentOS 8, this is what you get:

![Screen Shot 2019-10-03 at 2 36 41 PM](https://user-images.githubusercontent.com/2557898/66163737-3b37ca80-e5ee-11e9-9043-e41746187a27.png)

**Comment by santxus** [comment]
Hi

I really want to have a newer version of cockpit installed on centos 8, because I need manage firewalld from there.

Did you find any solution?

**Comment by PeterFalken** [comment]
@santxus 
you can use the following command:
`sudo dnf -y remove subscription-manager*`

Or as @martinpitt mentioned above, set _enabled = 0_  on the file: /etc/yum/pluginconf.d/subscription-manager.conf

The first option removes all subscription manager packages from your installation, the second option disables the subscription manager on the system.

**Comment by santxus** [comment]
Thank you so much

**Comment by PeterFalken** [comment]
Closing this issue since the latest build (207 on 2019.11.13) for EPEL 8 doesn't present this issue any more. Tested it through the Cockpit-Preview builds from COPR repository.
