### ISSUE TITLE
Synchronize users says Login Failed with correct credentials

### ISSUE THREAD

**Issue by dnoliver** [cockpit-project/cockpit#12932]
Cockpit version: cockpit-204-1.fc31.x86_64
OS: Fedora 31.20191003.0 (IoT Edition)
Page: Synchronize users

Synchronize users reports "Login Failed" with valid root credentials

`journalctl -u` cockpit reports nothing
I will need to cleanup some of the `journalctl --since -10m` output to paste it first. Will do if necessary :) 

Steps to reproduce

1. In a Fedora Workstation, install cockpit. Use a non-root user to log in into cockpit
2. In a Fedora IoT 31 host, install cockpit. Add this host to the Workstation cockpit with Dashboard -> Add Server
3. Try to synchronize your non root user into Fedora IoT 31 by providing the correct root credentials for IoT. A "Login Failed" message appears, event when using the correct credentials

Using the same root credentials to log in into the IoT host works. 

![Screenshot from 2019-10-07 13-06-41](https://user-images.githubusercontent.com/7730267/66346229-90355280-e906-11e9-8966-cf5a607ef42f.png)

I have another machine with Fedora Server + Cockpit, where account sync works fine. 
Maybe this is relevant: the non-root user has a weak password. If I manually try to create it using the Accounts page, it refuses to do it. But, it worked in the other machine the first time.

**Comment by marusak** [comment]
User synchronization has been dropped altogether.
