### ISSUE TITLE
Login, Dashboard, Virtual Machines - UX / features suggestions

### ISSUE THREAD

**Issue by iokaravas** [cockpit-project/cockpit#12937]
These are some notes I kept while I was using the dashboard, lets have a nice discussion about them! 👍 

Page: Login
~~- **Auto-focus on Verification Code field when using two-factor authentication (Google Authenticator)**
In my case I keep logging in and out my system and I find this frustrating mostly because it disrupts the flow of typing, you have to click the field to type, then login.~~
Found bug, [should be fixed by this PR. ](https://github.com/cockpit-project/cockpit/pull/12962)

- **An easy way to change the background shown in the page?**
Using a high resolution monitor the current branding (Debian on my system) looks strange. Centered with space left/right. It would be nice to have an easy way to customize that. Perhaps a settings pages for it?

Page: Dashboard

- **Not show the information popup every time I login?**
I'm still not sure if this is an actual issue, regardless how many times I click X, this popup will keep coming up every time I login. (the one saying `The programs included with the....`)

- **Disregard OEM default texts**
This I think there's an issue for. On my system I'm getting `Hardware
To Be Filled By O.E.M. To Be Filled By O.E.M.`

Page: Virtual Machines

- **Consoles: There is no graphical way to change VNC or SPICE settings (what port it listens to, etc)**

- **Consoles: When using `Graphics Console in Desktop Viewer`  (SPICE) the IP address is statically read from the XML and it is also defaults to 127.0.0.1**
This is strange because 127.0.0.1 is unusable when you're accessing the system from Network (isn't this a typical case?). Additionally if you set 0.0.0.0 which is a valid value for the domain, it will download a file with IP address 0.0.0.0 and not the domain's bound address(es).

- **Main screen: Allow an option to merge the Overview,Usage,Disks,Network Interfaces screens into one?**
It's feels awkward that you can't see an overview of a specific machine.

**Comment by andreasn** [comment]
Thanks for filing this!
It seems there is a couple of different bugs listed in this issue. Some of them easy to fix, others will take a bit of work, so little chance of fixing them all in one PR.
Would you be able to file them as separate issues?
That way they become a bit easier to track and we can close them one by one.
Thanks!

**Comment by iokaravas** [comment]
I'm picking each subject and creating issues until then I'm keeping this alive, I hope it's ok with you! If not, just close this :)

**Comment by marusak** [comment]
> An easy way to change the background shown in the page?

We are not going to support changeable background. The problem you mentioned is fixed and now the background image fills the screen.

> Not show the information popup every time I login?

I think you mean motd message? If so, then it is feature - it is the same as it shows up every time you ssh to a machine.

> Disregard OEM default texts

This seems to be case when you assamble your own PC (buying HW separatelly). We could just ignore it and use some general string. This should be separate issue (or ideally PR, it is simple enough :) )

> Consoles: There is no graphical way to change VNC or SPICE settings

@KKoukiou would know better, but I think separate issue would be ideal to discuss this.

> Consoles: When using Graphics Console in Desktop Viewer (SPICE) the IP address is statically read from the XML and it is also defaults to 127.0.0.1

@KKoukiou would know better, but I think separate issue would be ideal to discuss this.

> Main screen: Allow an option to merge the Overview,Usage,Disks,Network Interfaces screens into one?

I don't see how this would be any better. In general you don't want to see everything at once because it just makes the page too full and it is very hard to find anything useful. It makes much more sense to divide it into different tabs and to inspect what you are interested in. If you want to manage network you select network tab, if you want to manage disks you select disks tab...

**Comment by mvollmer** [comment]
>     * **Not show the information popup every time I login?**
>       I'm still not sure if this is an actual issue, regardless how many times I click X, this popup will keep coming up every time I login. (the one saying `The programs included with the....`)

This is a bug, the "x" should make the text go away until it changes.

**Comment by marusak** [comment]
> This is a bug, the "x" should make the text go away until it changes.

Had no idea, thanks! I believed it is designed like this.

**Comment by iokaravas** [comment]
Ok! Is there an issue for this bug? If there is I think we can also close this enhancement ;)

**Comment by q2dg** [comment]
Maybe this could be also taken into account: https://github.com/cockpit-project/cockpit/issues/8392#issuecomment-566170769

**Comment by martinpitt** [comment]
Login page parts are done, dashboard is gone, main screen changed completely in the meantime, and the VM Spice option is tracked in #14602.

If you still find anything else, please file new issues, and a separate issue for each concern. Thank you!
