### ISSUE TITLE
storage: unable to format if device is mounted

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1295]
Flow:
1. Filesystem is mounted
2. Select format in the menu
3. Press format in the dialog that pops up.
4. Get a error message along the lines of "Error opening device /dev/dm-3: Device or resource busy"

Perhaps the Format button should be grayed out if the filesystem is currently mounted.
Or the file system could be unmounted as part of the format action.
Option one is a little bit safer, option two is more efficient.

**Comment by mvollmer** [comment]
There now is a warning in the format dialog that the filesystem is mounted.  Does that suffice?
