### ISSUE TITLE
Do not state confusing number of rules in firewall

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#12952]
On networking page (`/network`) the description on firewall panel states `10 Active Rules`, however when I open the firewall page (`/network/firewall`) I see that I have two zones, first has 8 rules and the second one has 3 rules, so 10 rules seems very confusing (although it is correct, because one rule is shared between these two zones). Maybe we could show `11 rules in 2 zones` or `10 unique rules in 2 zones` or something similar.

**Comment by martinpitt** [comment]
Honestly, is the number of rules really that important and insightful on the /network overview page? It could just drop that sentence, or maybe say "2 active zones" or so?

**Comment by marusak** [comment]
> Honestly, is the number of rules really that important and insightful on the /network overview page? 

I don't have any option about it, I just wanted to point out that the number does not correspond to anything in the firewall page - which may be confusing.
@andreasn WDYT?

**Comment by andreasn** [comment]
I don't have a strong opinion either way.
@garrett designed it, so I'll defer to him.

**Comment by garrett** [comment]
The idea was to provide a summary that _something_ is happening. As long as we show something's up, then that's fine.

We _could_ have multiple rows in that list, one for each zone, with a high-level summary. (Of course, clicking would take you to the firewall page.)
