### ISSUE TITLE
test flake in check-storage-luks: Unknown device "/dev/sda1": No such file or directory

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#12957]
[This log](https://209.132.184.41:8493/logs/pull-12902-20191010-094444-3c0c80ff-cockpit-project-cockpit--fedora-31/log.html#200-2) has an interesting test failure:
```
# testLuks (check_storage_luks.TestStorage)
#
[...]
Unexpected journal messages:
Unknown device "/dev/sda1": No such file or directory
```

The [journal](https://209.132.184.41:8493/logs/pull-12902-20191010-094444-3c0c80ff-cockpit-project-cockpit--fedora-31/TestStorage-testLuks-fedora-31-127.0.0.2-2601-FAIL.log) shows that this happened late in the test, presumably around shutting down the VM. That udevadm info is from [luksmeta-monitor-hack](https://github.com/cockpit-project/cockpit/blob/master/pkg/storaged/luksmeta-monitor-hack.py), and it just failed:
```
Oct 10 06:06:38 localhost.localdomain cockpit-bridge[4561]: Unknown device "/dev/sda1": No such file or directory
Oct 10 06:06:38 localhost.localdomain python3[8317]: detected unhandled Python exception in 'interactive mode (python - ...)'
Oct 10 06:06:38 localhost.localdomain cockpit-bridge[4561]: Traceback (most recent call last):
Oct 10 06:06:38 localhost.localdomain cockpit-bridge[4561]:   File "<stdin>", line 121, in <module>
Oct 10 06:06:38 localhost.localdomain cockpit-bridge[4561]:   File "<stdin>", line 105, in monitor
Oct 10 06:06:38 localhost.localdomain cockpit-bridge[4561]:   File "/usr/lib64/python3.7/subprocess.py", line 395, in check_output
Oct 10 06:06:38 localhost.localdomain cockpit-bridge[4561]:     **kwargs).stdout
Oct 10 06:06:38 localhost.localdomain cockpit-bridge[4561]:   File "/usr/lib64/python3.7/subprocess.py", line 487, in run
Oct 10 06:06:38 localhost.localdomain cockpit-bridge[4561]:     output=stdout, stderr=stderr)
Oct 10 06:06:38 localhost.localdomain cockpit-bridge[4561]: subprocess.CalledProcessError: Command '['udevadm', 'info', '-q', 'path', '/dev/sda1']' returned non-zero exit status 1.
```
But I wonder why -- the operation before was to merely LUKS-lock /dev/sda1, and nowhere in that test it calls `.rem_disk()` to remove the disk -- it should stay around even during VM shutdown.

*if* the test removes sda1 somewhere, then it's enough to just add this as an expected message (preferably centrally in `add_disk()` or `rem_disk()`), but if that disk really doesn't get removed anywhere, then something more funny is going on. Let's see if that happens again.

@mvollmer, does that ring a bell by chance?

**Comment by mvollmer** [comment]
>  does that ring a bell by chance?

Yes.  Udevd causes the kernel to re-read partition tables from time to time, and when that happens, all partitions disappear very briefly.

I try to figure out what exactly is triggering the re-read.

**Comment by mvollmer** [comment]
So one thing we can do is to simply not use a partition in the test, but the full block device.

**Comment by martinpitt** [comment]
ah, that's a plausible explanation indeed! Then I guess it's also fine to simply allow the message. The LUKS tests should fail "properly" if the mechanism doesn't work, after all.

**Comment by mvollmer** [comment]
Actually, the test deletes the partition at the end, and that races `luksmeta-monitor-hack` startup.  That is a much more likely explanation.  There is nothing in the test that would trigger a re-reading of the partition table.

**Comment by mvollmer** [comment]
> Then I guess it's also fine to simply allow the message.

Yes, I agree.
