### ISSUE TITLE
Compatible with direct admin

### ISSUE THREAD

**Issue by spacecabbie** [cockpit-project/cockpit#12967]
Page: 

Quick question will it run together with directadmin ? (user request)

**Comment by martinpitt** [comment]
I don't know [direct admin](https://www.directadmin.com/), it's a proprietary tool. But there is no reason why they should interfere -- cockpit just manages your server, it does not impose anything cockpit specific on top of it, like cockpit-specific configuration files or APIs. See https://cockpit-project.org/ideals.html
