### ISSUE TITLE
HTTP/1.0 is broken

### ISSUE THREAD

**Issue by Shulyaka** [cockpit-project/cockpit#12969]
Cockpit version: 202.1
OS: Fedora 30
Page: N/A

I'd like to use cockpit behind lighttpd reverse proxy. Lighttpd uses HTTP/1.0 to communicate to the backend server (except websockets).

However cockpit responds to HTTP/1.0 requests with HTTP/1.1 responses (verified with tcpdump), and also adds the "Transfer-Encoding: chunked" header, which lighttpd exeptionally dislikes. I suspect that this is wrong.

Cockpit config
```
[WebService]
Origins = https://shulyaka.org.ru
ProtocolHeader = X-Forwarded-Proto
UrlRoot = /cockpit-ananas/
AllowUnencrypted = true
```

Lighttpd config
```
$HTTP["url"] =~ "^/cockpit-ananas/" {
        proxy.server = ( "" => ( ( "host" => "ananas", "port" => "9090" ) ) )
        proxy.header = ( "upgrade" => "enable" )
        server.stream-request-body  = 2
        server.stream-response-body = 2
}
```

Lighttpd error log
```
2019-10-13 16:26:56: (http-header-glue.c.1032) proxy backend sent invalid response header (Transfer-Encoding) to HTTP/1.0 request
2019-10-13 16:26:56: (gw_backend.c.2125) response not received, request sent: 590 on socket: tcp:192.168.1.229:9090 for /cockpit-ananas/?, closing connection
```

Steps to reproduce
```
[denis@ananas ~]$ (echo -e -n "GET /cockpit-ananas/ HTTP/1.0\nHost: 127.0.0.1\n\n"; sleep 1) | nc localhost 9090 | head
HTTP/1.1 200 OK
Content-Type: text/html
Content-Security-Policy: connect-src 'self' http://127.0.0.1 ws://127.0.0.1; form-action 'self' http://127.0.0.1; base-uri 'self' http://127.0.0.1; object-src 'none'; font-src 'self' http://127.0.0.1 data:; img-src 'self' http://127.0.0.1 data:; block-all-mixed-content; default-src 'self' http://127.0.0.1 'unsafe-inline'
Set-Cookie: cockpit=deleted; PATH=/; HttpOnly
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store
X-DNS-Prefetch-Control: off
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff

```

**Comment by wjrobe** [comment]
I can confirm the issue.  I have also tried setting up cockpit through a reverse proxy server and it will not work.

(my server is actually the name)

```
...
$HTTP["host"] == "cockpit.NAME.net" {
    proxy.server  = ( "" => ( (
            "host" => "127.0.0.1",
            "port" => 9090
    ) ) )
}
...
```
Here is my /etc/cockpit/cockpit.conf 
```
[WebService]
Origins = https://NAME.net https://NAME.net:9090 wss://cockpit.NAME.net
ProtocolHeader = X-Forwarded-Proto
AllowUnencrypted=true
```

Going to the website results in an error 502.

**Comment by gr01d** [comment]
I am having problem with setting up lighttpd reverse proxy with the latest debian buster cockpit package. The result is also 502 Bad Gateway, I am using lighttpd 1.4.53

**Comment by haydenjames** [comment]
same issue

**Comment by xer0-1ne** [comment]
As of version 228-2, lighttpd reverse proxy is still unusable with Cockpit and this issue is still valid.

**Comment by gstrauss** [comment]
lighttpd 1.4.56 and later send HTTP/1.1 requests to proxied backends.
buster-backports has lighttpd 1.4.58, so please try that.
Latest version of lighttpd is lighttpd 1.4.59 and will hopefully make it into buster-backports in a month or so.

`Transfer-Encoding: chunked` is part of the HTTP/1.1 specification.  `Transfer-Encoding: chunked` is not part of the HTTP/1.0 specification, so it is categorically wrong for Cockpit to send `Transfer-Encoding: chunked` in response to an HTTP/1.0 request.

**Comment by martinpitt** [comment]
I'm afraid this is a wontfix, and I close this now as we will not do anything about it. As @gstrauss already mentioned, cockpit is relying on HTTP/1.1 features. I'm not even sure if websocket is supported in 1.0.

**Comment by liamharper2453** [comment]
Hello. For interest of anyone else trying to use a reverse proxy with lighttpd who like me couldn't find anything documented out there...

lighttpd.conf

$HTTP["url"] =~ "^/yourLocation" {
	url.redirect = ("^/yourLocation$" => "/yourLocation/")
        proxy.server = ( "" => ( ( "host" => "127.0.0.1", "port" => "9090" ) ) )
        proxy.header = ( "upgrade" => "enable" )
	setenv.add-request-header   = ( "Connection" => "Upgrade")
}

cockpit.conf

[WebService]
UrlRoot = /yourLocation/
Origins = https://yourOrigin.net
AllowUnencrypted = true
ProtocolHeader = X-Forwarded-Proto

**Comment by gstrauss** [comment]
> Hello. For interest of anyone else trying to use a reverse proxy with lighttpd who like me couldn't find anything documented out there...

@liamharper2453 thanks for posting, but the real issue is if you are on a system on which you are for some reason unable to upgrade to lighttpd 1.4.56 or later, then you are on a system that is not well-maintained.  I suggest looking at different OS distros and upgrading your system.  lighttpd 1.4.56 was released over 2 1/2 years ago.  The latest lighttpd release is lighttpd 1.4.71.

WRONG: manually setting `setenv.add-request-header = ( "Connection" => "Upgrade")` is almost always wrong, as this is a hop-by-hop HTTP header and requires the presence of an `Upgrade` request header, and also requires HTTP/1.1.  Also, as @martinpitt noted, websockets requires HTTP/1.1 or later.

This lighttpd.conf snippet with a modern lighttpd installation should be something simple like:
```
$HTTP["url"] =~ "^/yourLocation/" {
    proxy.server = ( "" => ( ( "host" => "127.0.0.1", "port" => "9090" ) ) )
    proxy.header = ( "upgrade" => "enable" )
}
```

**Comment by liamharper2453** [comment]
> > Hello. For interest of anyone else trying to use a reverse proxy with lighttpd who like me couldn't find anything documented out there...
> 
> @liamharper2453 thanks for posting, but the real issue is if you are on a system on which you are for some reason unable to upgrade to lighttpd 1.4.56 or later, then you are on a system that is not well-maintained. I suggest looking at different OS distros and upgrading your system. lighttpd 1.4.56 was released over 2 1/2 years ago. The latest lighttpd release is lighttpd 1.4.71.
> 
> WRONG: manually setting `setenv.add-request-header = ( "Connection" => "Upgrade")` is almost always wrong, as this is a hop-by-hop HTTP header and requires the presence of an `Upgrade` request header, and also requires HTTP/1.1. Also, as @martinpitt noted, websockets requires HTTP/1.1 or later.
> 
> This lighttpd.conf snippet with a modern lighttpd installation should be something simple like:
> 
> ```
> $HTTP["url"] =~ "^/yourLocation/" {
>     proxy.server = ( "" => ( ( "host" => "127.0.0.1", "port" => "9090" ) ) )
>     proxy.header = ( "upgrade" => "enable" )
> }
> ```

Thanks your suggestion works great for me. You are correct the other parts are not needed.
