### ISSUE TITLE
Request: Crontab management

### ISSUE THREAD

**Issue by Justinzobel** [cockpit-project/cockpit#1297]
Ability to manage cron tasks, add/remove, set time/date/intervals

**Comment by andreasn** [comment]
http://www.freedesktop.org/software/systemd/man/systemd.timer.html

**Comment by andreasn** [comment]
With examples https://wiki.archlinux.org/index.php/Systemd/Timers

**Comment by andreasn** [comment]
http://www.freedesktop.org/software/systemd/man/systemd.time.html

**Comment by andreasn** [comment]
First iteration. Made the overview page closer resemble the systemctl list-timers CLI command.
Spent most of the time on the dialog, so the overview might still be a bit rough. Also currently missing Unit Activation/Deactivation currently.

![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/services/timers.png)

**Comment by stefwalter** [comment]
@rhamilto I see bootstrap-datepicker as a bower component dependency in the latest the patternfly source code. I guess that should be our go to for date selection.

**Comment by rhamilto** [comment]
@stefwalter, I'm guessing you're mistaking

    "bootstrap-combobox": "~1.1.6",
    "bootstrap-select": "~1.5.4",
    "bootstrap-treeview": "~1.0.1",

to include `bootstrap-datepicker` as https://github.com/patternfly/patternfly/blob/master/bower.json doesn't (yet) include bootstrap-datepicker.  :)

regardless, bootstrap-datepicker seems like a good choice and is probably the one i'll include should we determine a need for one.

**Comment by Aayush-Kasurde** [comment]
Can we consider bootstrap-datetimepicker https://github.com/Eonasdan/bootstrap-datetimepicker as it provides additional functionality of choosing time as well?

**Comment by stefwalter** [comment]
@Aayush-Kasurde makes a good point. 

@rhamilto I did see the string 'bootstrap-datepicker' when i grepped the patternfly repo, hence my suspicions that you were leaning that way :)

```
[stef@falcon patternfly]$ git grep bootstrap-datepicker
components/bootstrap-treeview/Gruntfile.js:          { expand: true, cwd: 'public/bower_components/bootstrap-datepicker/js', src: 'bootstrap-datepicker.js', dest: 'tests/lib/' },
```

**Comment by andreasn** [comment]
If possible, I would like to keep the Date and Time pickers separate. The reason for that is that the time picker is also present in the repeat hourly/weekly/monthly entrys. This then stays consistent if you switch to repeat yearly.

**Comment by Justinzobel** [comment]
How did this end up going @andreasn

**Comment by andreasn** [comment]
> How did this end up going @andreasn

The designs are in good shape I think, but it needs somebody to develop the feature.
Are you interested in taking it on?

**Comment by Justinzobel** [comment]
@andreasn sadly I have no code experience or time to learn otherwise I'd
certainly be interested.

**Comment by stefwalter** [comment]
This has been implemented with the 'Timers' support.
