### ISSUE TITLE
virsh net-list and list

### ISSUE THREAD

**Issue by alessandrobelli** [cockpit-project/cockpit#12975]
Hello!
So, I'm encountering some weird issues.
I created a Debian 9 VM in Cockpit, then if I go into the Cockpit terminal I get no network from 
`virsh net-list`
and I get the virtual machine when I try
`virsh list`

If I ssh into the host machine, and I try the same commands 
`virsh net-list`
has a default network
`virsh list`
is empty.

And I'm using the same user.
Is this wanted?

**Comment by KKoukiou** [comment]
> Hello!
> So, I'm encountering some weird issues.
> I created a Debian 9 VM in Cockpit, then if I go into the Cockpit terminal I get no network from
> `virsh net-list`
> and I get the virtual machine when I try
> `virsh list`
> 
> If I ssh into the host machine, and I try the same commands
> `virsh net-list`
> has a default network
> `virsh list`
> is empty.
> 
> And I'm using the same user.
> Is this wanted?

Definitely not.

Please paste the ouput of ``` virsh uri ``` ran in both terminals;

**Comment by alessandrobelli** [comment]
on cockpit terminal:
`qemu:///session`
and on the ssh:
`qemu:///system`

**Comment by KKoukiou** [comment]
Right, so this is the reason you see the difference. So your questions gets now down to why 'virsh uri' gives different output in cockpit terminal compared to the terminal of the ssh session.

Do you by any chance have your default virsh URI changed in the ssh session?
You might have done it by running `export LIBVIRT_DEFAULT_URI="qemu:///system"` for example.

**Comment by KKoukiou** [comment]
> on cockpit terminal:
> `qemu:///session`
> and on the ssh:
> `qemu:///system`

In addition pls make sure that you run these command really with the same user (I guess non root since I see session URI in the cockpit terminal).
And maybe it would be beneficial if you could provide some information about the user under which you are running the commands.

```
$ id $(whoami)
```

**Comment by alessandrobelli** [comment]
I'm 100% that I was using the same user, and as far as the
`export LIBVIRT_DEFAULT_URI="qemu:///system"`
I'm sure I didn't do it, but I will ask the team. Can it be something wrong with Cockpit?

**Comment by KKoukiou** [comment]
I don't see how the cockpit shell will cause this inconsistency.

In fact for non root users by default you get the ```qemu:///session``` connection like what cockpit gave you and not the system one. So I am more interested how the ssh session gave you the system if you didn't change your system's default configuration.

The ways to get ```qemu:///system``` is to either
* run as root
* set the env var I asked you about
* set in the configuration file (```/etc/libvirt/libvirt.conf```)

And only the second can be set for one terminal session.

So if you can get access once again to that system and you can reproduce again double verify if the env var is set.

**Comment by KKoukiou** [comment]
This issue is being inactive for a while; I will close this since it's not something not can probably help other users.
The fact that you had different default connection for virsh between cockpit terminal and the ssh session can depend on many things as I said above, but I don't see how it can be a bug on our side yet.
If you need help debugging this - please reopen or let's discuss it on #cockpit channel on Freenode.
