### ISSUE TITLE
Cockpit Network page do not display stats on GSM connection

### ISSUE THREAD

**Issue by dnoliver** [cockpit-project/cockpit#12980]
Cockpit version: cockpit-204-1.fc31.x86_64
OS: Fedora 31.20191014.0 (IoT Edition)
Page: Networking

Networking page does not show activity on an active GSM type connection

Steps to reproduce

1. Use a device like the [Compulab Fitlet2 with GSM module}(https://fit-iot.com/web/products/fitlet2/fitlet2-specifications/).
2. Install Fedora IoT, and Cockpit
3. Install a valid GSM card, validate that you get a valid IP address.
4. Then browse to the Networking page in cockpit, and inspect the GMS connection. Send some trafic (like ping www.google.com)
5. Nothing is shown in the Sending/Receiving graphs

`cdc-wdm0` is the GSM connection
![image](https://user-images.githubusercontent.com/7730267/66787686-71503680-ee99-11e9-8cdf-00662e824a40.png)

Sending Receiving shows no traffic, and connection driver is `Unknown "modem"
`
![image](https://user-images.githubusercontent.com/7730267/66787698-7f05bc00-ee99-11e9-931b-7ef5ba4e31e9.png)

`nmcli` output
```text
cdc-wdm0: connected to cdc-wdm0
        "cdc-wdm0"
        gsm (option1, qmi_wwan), hw, iface wwp0s21f0u8u2i5, mtu 1500
        ip4 default
        inet4 29.137.78.143/27
        route4 0.0.0.0/0
        route4 29.137.78.128/27

eno1: connected to eno1
        "Intel I211"
        ethernet (igb), 00:01:C0:21:30:8F, hw, mtu 1500
        inet4 192.168.88.246/24
        route4 192.168.88.0/24
        inet6 fe80::c296:8925:b048:99f1/64
        route6 fe80::/64
        route6 ff00::/8
```

`nmcli device show cdc-wdm0` output
```text
GENERAL.DEVICE:                         cdc-wdm0
GENERAL.TYPE:                           gsm
GENERAL.HWADDR:                         (unknown)
GENERAL.MTU:                            1500
GENERAL.STATE:                          100 (connected)
GENERAL.CONNECTION:                     cdc-wdm0
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/ActiveConnection/4
IP4.ADDRESS[1]:                         29.137.78.143/27
IP4.GATEWAY:                            29.137.78.129
IP4.ROUTE[1]:                           dst = 0.0.0.0/0, nh = 29.137.78.129, mt = 700
IP4.ROUTE[2]:                           dst = 29.137.78.128/27, nh = 0.0.0.0, mt = 700
IP4.DNS[1]:                             10.177.0.34
IP4.DNS[2]:                             10.177.0.210
IP6.GATEWAY:                            --
```

**Comment by martinpitt** [comment]
The sending/receiving stats are read from /proc/net/dev. It seems the kernel does not export that (i.e. the driver does not put it there). If this is still an issue, please file a bug against the kernel. Thank you!

**Comment by dnoliver** [comment]
Reported in Fedora's bugzilla here https://bugzilla.redhat.com/show_bug.cgi?id=1937542
