### ISSUE TITLE
Support two-factor authentication for cockpit-ssh

### ISSUE THREAD

**Issue by daniejstriata** [cockpit-project/cockpit#12982]
Login Enhancement:

I can only login to a secondary Cockpit if it does not use MFA for SSH login. When I require MFA the login fails. When I disable the MFA requirement login is successful. If it my understanding that MFA is supported but seemingly not for the secondary logins.

If this is the case can MFA support be added for the secondary logins too?

**Comment by martinpitt** [comment]
This has actually worked for quite some time, since [cockpit 228](https://cockpit-project.org/blog/cockpit-228.html). Now connecting to a remote host will ask in the dialog whatever ssh wants to know. I specifically tested this again with google-authenticator style TOTP tokens as 2FA.
