### ISSUE TITLE
Login Page customization (Walppaper, etc)

### ISSUE THREAD

**Issue by iokaravas** [cockpit-project/cockpit#12984]
Page: Login

A suggestion to have an easy way to change the background shown in the login page and position / styling?

Using a high resolution monitor the current branding (Debian on my system) looks strange. Centered with space left/right. It would be nice to have an easy way to customize that. Perhaps a settings page for it?

**Comment by marusak** [comment]
Can you please post screenshot and your current resolution?
I don't think we will support changing background - but if the background image (or branding, not sure from the issue) does not correctly spans, we should fix that.

**Comment by iokaravas** [comment]
Full size 2560x1440 (hopefully cropped 1:1)
![image](https://user-images.githubusercontent.com/1234491/66837756-2fdc8b80-ef6c-11e9-950b-6f1a5cbb7a01.png)

Windowed (?) It looks like it sticks to the left side of the screen.
![image](https://user-images.githubusercontent.com/1234491/66837804-47b40f80-ef6c-11e9-85b6-b687bd4890cd.png)

I hope this suffices!

**Comment by marusak** [comment]
I opened #12985, can you verify it fixes your problem?
