### ISSUE TITLE
cockpit-tls misbehaves with https connections

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#12994]
Cockpit version: 205
OS: fedora-31

After using Cockpit a while (few seconds to a minute), Firefox freezes and starts consuming CPU and memory.

Chrome does behave normally, but almost none of the Cockpit pages actually work.  It looks like the HTML/CSS etc assets are loaded, but there is no WebSocket traffic.

**Comment by mvollmer** [comment]
Chrome also starts consuming 100% CPU immediately after login.

**Comment by martinpitt** [comment]
PR #12993 reverts this. Let's bring this back with proper unit tests, and figure out why the integration tests with chromium https didn't catch this.

**Comment by michalhainc** [comment]
I'm currently having this issue on my system 
![image](https://user-images.githubusercontent.com/3962233/177544522-7e1cebd8-61f0-4b45-9893-53d3dddd3a71.png)

**uname -a:**
Linux 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**apt show cockpit -1:**
Package: cockpit
Version: 264-1~bpo20.04.1
Priority: optional
Section: universe/admin
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 69.6 kB
Depends: cockpit-bridge (>= 264-1~bpo20.04.1), cockpit-ws (>= 264-1~bpo20.04.1), cockpit-system (>= 264-1~bpo20.04.1)
Recommends: cockpit-storaged (>= 264-1~bpo20.04.1), cockpit-networkmanager (>= 264-1~bpo20.04.1), cockpit-packagekit (>= 264-1~bpo20.04.1)
Suggests: cockpit-doc (>= 264-1~bpo20.04.1), cockpit-pcp (>= 264-1~bpo20.04.1), cockpit-sosreport (>= 264-1~bpo20.04.1), xdg-utils
Homepage: https://cockpit-project.org/
Download-Size: 18.9 kB
APT-Sources: http://asi-fs-n.contabo.net/ubuntu focal-backports/universe amd64 Packages
Description: Web Console for Linux servers
 The Cockpit Web Console enables users to administer GNU/Linux servers using a
 web browser.
 .
 It offers network configuration, log inspection, diagnostic reports, SELinux
 troubleshooting, interactive command-line sessions, and more.

Package: cockpit
Version: 215-1
Priority: optional
Section: universe/admin
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 63.5 kB
Depends: cockpit-bridge (>= 215-1), cockpit-ws (>= 215-1), cockpit-system (>= 215-1)
Recommends: cockpit-storaged (>= 215-1), cockpit-networkmanager (>= 215-1), cockpit-dashboard (>= 215-1), cockpit-packagekit (>= 215-1)
Suggests: cockpit-doc (>= 215-1), cockpit-pcp (>= 215-1), cockpit-machines (>= 215-1), xdg-utils
Homepage: https://cockpit-project.org/
Download-Size: 18.0 kB
APT-Manual-Installed: yes
APT-Sources: http://asi-fs-n.contabo.net/ubuntu focal/universe amd64 Packages
Description: Web Console for Linux servers
 The Cockpit Web Console enables users to administer GNU/Linux servers using a
 web browser.
 .
 It offers network configuration, log inspection, diagnostic reports, SELinux
 troubleshooting, interactive command-line sessions, and more.
