### ISSUE TITLE
SSH key with pass phrase will not allow login via web

### ISSUE THREAD

**Issue by puskyer** [cockpit-project/cockpit#12992]
Cockpit version: 195.1-1.el7.centos.0.1
OS: NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"

Page: main cockpit login page

when my ssh key has a pass phrase on it I can not login in (I get "Authentication failed: Timeout" )

Steps to reproduce

1. add pass phrase to ssh key, can not login
2.remove pass phrase from ssh key, can login

**Comment by martinpitt** [comment]
You need to unlock the key first, using the "Authentication" dialog in the top right user menu. In cockpit 209 this also became easier now, see PR #13199.
