### ISSUE TITLE
firewall: delete confirmation

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#12999]
Delete confirmation:

![image](https://user-images.githubusercontent.com/11140201/67007798-72c36e00-f0e8-11e9-8c30-65e5c8fa6b45.png)

Plus extra warning when the zone or service to be removed contains/is cockpit.

**Comment by andreasn** [comment]
I think we have two different issues here:
1. Removing a whole zone where you've curated a lot of zone+s is a big hammer.
2. If you remove a zone with cockpit in it might be the tree branch you're sitting on, so it's pretty plausible that you will lock yourself out from the system.

**2** needs a warning dialog (or some other guard rails) for sure, but a little on the fence about **1** still.

**Comment by martinpitt** [comment]
For the individual services I'd rather we move the delete button into the expander. We do this on other pages already. That avoids deletion with an accidental single click.

This doesn't quite work for a whole zone, so a confirmation dialog seems ok there.

**Comment by Gundersanne** [comment]
> For the individual services I'd rather we move the delete button into the expander. We do this on other pages already. That avoids deletion with an accidental single click.
> 
> This doesn't quite work for a whole zone, so a confirmation dialog seems ok there.

In case of the cockpit service I would still have a confirmation dialog with a warning no?
