### ISSUE TITLE
investigate glusterfs support

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#13]
glusterfs is a distributed filesystem, which can be used in nas. Supporting this could be done either by adding support for it to udisks, or by directly using the glusterfs api. Adding it in udisks would have the advantage that we get desktop support for free (not sure how relevant that is).

**Comment by maci0** [comment]
+1

**Comment by vanloswang** [comment]
+1

**Comment by martinpitt** [comment]
Agreed.
