### ISSUE TITLE
packagekit: Debian 10 Buster without NetworkManager: Cannot refresh cache whilst offline

### ISSUE THREAD

**Issue by mfkrause** [cockpit-project/cockpit#13002]
Cockpit version: 188
OS: Debian GNU/Linux 10 (buster)
Page: Software Updates

I've installed Cockpit on two Debian 10 systems. While everything works fine, I cannot seem to get the software updates page running. It reports that the system is offline (even though it's obviously not).
#8477 referred to this earlier, however on an Ubuntu 16.04 installation. @martinpitt said this issue got fixed in later Ubuntu / NetworkManager versions.
Any idea regarding Debian 10? I've already tried completely disabling NetworkManager (since I don't use it anyways), still no luck.

**Comment by EdwinGraves** [comment]
This is still an issue on Ubuntu 19. Disabling NetworkManager doesn't help.

**Comment by RQinoz** [comment]
I am running Debian 10 and had this issue.  I resolved it by disabling the NetworkManager.service and re-booting.  After this action, I was able to update my installation.

**Comment by martinpitt** [comment]
Our [tests](https://github.com/cockpit-project/cockpit/blob/master/test/verify/packagelib.py#L46) have some hacks to work on ubuntu 18.04 and 19.10, which disables NetworkManager. But this is mostly becuase our test VMs are offline. We don't have nor need such a hack on Debian, so I'm afraid I don't know a good workaround either. This is a packagekit bug (you will see the same issue with `pkcon get-updates`), I'm afraid we can't really "fix" this in cockpit.

**Comment by lukestuts** [comment]
I have tested this on Ubuntu 19.10 and I still get the "Cannot refresh cache whilst offline" when NetworkManager is disabled.

pkcon get-updates works without issues:

```
stuts@test:~$ sudo pkcon get-updates
Getting updates               [=========================]
Loading cache                 [=========================]
Finished                      [=========================]
Bug fix         linux-generic-5.3.0.24.28.amd64 (ubuntu-eoan-updates-main)      Complete Generic Linux kernel and headers
Bug fix         linux-headers-generic-5.3.0.24.28.amd64 (ubuntu-eoan-updates-main)      Generic Linux kernel headers
Bug fix         linux-image-generic-5.3.0.24.28.amd64 (ubuntu-eoan-updates-main)        Generic Linux kernel image
```

**Comment by lukestuts** [comment]
I tell a lie, it fails here:
```
root@test:/home/stuts# pkcon update
Getting updates               [=========================]
Finished                      [=========================]
Loading cache                 [=========================]
Testing changes               [=========================]
Finished                      [                         ] (0%)
The following packages have to be installed:
 linux-headers-5.3.0-24-5.3.0-24.26.all Header files related to Linux kernel version 5.3.0
 linux-headers-5.3.0-24-generic-5.3.0-24.26.amd64       Linux kernel headers for version 5.3.0 on 64 bit x86 SMP
 linux-image-5.3.0-24-generic-5.3.0-24.26.amd64 Signed kernel image generic
 linux-modules-5.3.0-24-generic-5.3.0-24.26.amd64       Linux kernel extra modules for version 5.3.0 on 64 bit x86 SMP
 linux-modules-extra-5.3.0-24-generic-5.3.0-24.26.amd64 Linux kernel extra modules for version 5.3.0 on 64 bit x86 SMP
The following packages have to be updated:
 linux-generic-5.3.0.24.28.amd64        Complete Generic Linux kernel and headers
 linux-headers-generic-5.3.0.24.28.amd64        Generic Linux kernel headers
 linux-image-generic-5.3.0.24.28.amd64  Generic Linux kernel image
Proceed with changes? [N/y] y

                              [=========================]
Updating packages             [=========================]
Loading cache                 [=========================]
Finished                      [=========================]
Fatal error: Cannot download packages whilst offline
```

**Comment by lukestuts** [comment]
@martinpitt I have found a workaround for Ubuntu 19.10 and others:

Edit /etc/PackageKit/PackageKit.conf and add this to the [Daemon] section:

`UseNetworkManager = false`

I needed to reboot but now everything works perfectly with no extra network interfaces needed.

**Comment by martinpitt** [comment]
@lukestuts: Note that `get-updates` only uses the cache. What will fail is `pkcon refresh force`.

Really nice trick with PackageKit.conf! I'll adjust our tests to use that, this is cleaner indeed.

**Comment by martinpitt** [comment]
@lukestuts : Do you use some kind of modified packagekit? The [official git repo](https://github.com/hughsie/PackageKit) does not know about the `UseNetworkManager` option, and neither does the Ubuntu 19.10 package:

    dpkg -L packagekit | xargs strings | grep -i UseNetwo

The error is generated in the [aptcc backend](https://github.com/hughsie/PackageKit/blob/master/backends/aptcc/pk-backend-aptcc.cpp#L554), using [pk_backend_is_online()](https://github.com/hughsie/PackageKit/blob/master/src/pk-backend.c#L854), which in turn calls [g_network_monitor_get_network_available ()](https://developer.gnome.org/gio/stable/GNetworkMonitor.html#g-network-monitor-get-network-available). This really tests for a default route.

**Comment by lukestuts** [comment]
@martinpitt Yes, my mistake. Disabling the network-manager service completely is what actually it work on my server. I just created another server and the PackageKit.conf line did nothing. Sorry!

**Comment by PoLoMoTo** [comment]
I had this exact issue on both of my Ubuntu 19.10 servers and although disabling NetworkManager and rebooting resolved the error, the Networking page on Cockpit is just a blank page, is there any way to get that back?
