### ISSUE TITLE
machines: please add iso managent (including hotplug)

### ISSUE THREAD

**Issue by Fantu** [cockpit-project/cockpit#13003]
Hi, thanks to anyone contributing in cockpit development.
Can someone add iso managent (add/remove) to machines please? with also hotplug support it would be perfect.

Thanks for any reply and sorry for my bad english.

**Comment by andreasn** [comment]
In what situations are you adding and removing iso's to VMs?
Is it for boot devices? OS install media? Something else?

**Comment by Fantu** [comment]
@andreasn thanks for reply.
There are some cases where we add iso hotplug for install software, other cases are s.o. install, restart with cd boot for s.o. boot recovery, distrolive linux for fix/workaround important issue, near all iso usage is on windows vm.

For now we have a static ide cdrom for all vm as hdb:
```
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <target dev='hdb' bus='ide'/>
      <readonly/>
      <boot order='30'/>
      <address type='drive' controller='0' bus='0' target='0' unit='1'/>
    </disk>
```
In future with q35 cipset will be for example sdb.
And we use a very minimal custom webconsole with few features (using libvirt-go api) including iso add/remove (including hotplug) that we want remove and from some tests cockpit can be a possible replacement.

**Comment by duckinator** [comment]
Just had to pull out virt-manager because of this. An OS install failed on the first attempt and the CD was automatically unmounted after shutting it down, and Cockpit offers no way to mount it again afaict.

**Comment by skobyda** [comment]
This problem could be solved in a similar manner as virt-manager solves it. Virt-manager allows to add a volume do storage pool, where you create add a "custom path" to file with volume (in this case path to iso file).
Then you have to attach this volume as a disk to VM.

So in cockpit we could also allow specifying a custom path for volume creation.
And/Or in our "Add Disk" dialog we could also have some field for specifying custom path, although @andreasn I cannot precisely imagine where should it go.
- Should it go into Create New or Use Existing option? Or have separate option?
-- If you look at these 2 option from a perspective of libvirt's storage volumes, then it user in this case would be creating a new volume which uses existing iso file, so it should be in Create New.
-- If we however look from a perspective of creating new files or using existing files, then we are already using existing iso file, so it should be in Use Existing.

What do you think?

**Comment by KKoukiou** [comment]
This was implemented and going to be released in 238.

![Screen Shot 2021-02-12 at 22 52 51](https://user-images.githubusercontent.com/14921356/107826795-cb128a80-6d85-11eb-8ce4-f4c9bee70b3b.png)

**Comment by pricerc** [comment]
For anyone who, like me, finds this thread while trying to figure out how to attach ISO files to their VMs using Cockpit.

It seems that there is actually a limitation in libvirt around hotplugging 'optical' drives (and floppies).

https://bugzilla.redhat.com/show_bug.cgi?id=1446666

https://marc.info/?l=libvir-list&m=164121642128273

I've just started working with libvirt and KVM, coming from VMware where you can attach and detach ISO files at any time, whether the VM is running or not. It is a seamless, trivial exercise.

It is crazy that you have to shutdown a VM to add or change an ISO file. That "cdrom/floppy" hotplug isn't supported, even using "USB" for the bus.

While it is true that in 2023 optical drives are mostly used when first insalling an OS, if you're working with Microsoft server platforms (as I do for my work), it is common to download ISO versions of products such as SQL Server to install and upgrade the software onto multiple virtual machines. I.e. for people like me, it's not as niche as the libvirt developers seem to think it is.
