### ISSUE TITLE
machines: Missing Snapshots support

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#13010]
Page: Machines

Originally came in via the Red Hat bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1673158

**Problem:**
Sysadmins who handle VMs needs a way to snapshot the current state of a VM, do some potentially damaging operations, and have the ability to roll back to a previously well working state of the machine.

**Initial scope:**
- [x] Create a new snapshot with name, description and timestamp: to make them easier to recognize to yourself and coworkers.
- [x] Ability to roll back state of a VM to a snapshot: to restore to a previously state that is known to work well.
- [x] Delete snapshot: to save up space or to clear up the list of objects to keep track of.
- [x] These should be internal libvirt ones for now, external snapshots are still being worked on by libvirt team.
- [ ] Hide the snapshot section for VMs that are not in qcow2-format.
- [ ] Nice-to-have: Description of parent-child for snapshots of snapshots of snapshots (edgier case)
- [ ] Nice-to-have: Differ between VMs with RAM snapshots (running state) and those without.

**Comment by andreasn** [comment]
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/98d14548db2e81b7f69e80e5fb72ee473efc21d1/virtual-machines/snapshots.png)

**Comment by andreasn** [comment]
Some quick explanation for the mockup:
* the little lightning icon is the current snapshot
* No dialog for creating snapshot. It will just get an autogenerated name. An admin can rename it or edit the description later if they want to identify them more easily in the future. But making a snapshot needs to be a breeze.

**Comment by Fantu** [comment]
Some years ago I tested also snapshot on vm with raw disks and was possible:
with "virsh snapshot-create-as" it created additional qcow disks file with base file the raw ones; if critical operation "fails" stop the vm delete the qcow file and change the vm xml to repoint to the base raw file (virsh snapshot-revert to external snapshot was not supported, I didn't retest recently); if was ok use "virsh blockcommit" for consolidate qcow in the base file raw.
If I'll have time and needed I'll retest it and I'll post the exact procedure with exact command parameters.

**Comment by skobyda** [comment]
Looks great!
Just some small comments:
"Create Snapshot" button should have default (white) design instead of primary (blue) since we use default design for all "Create something" buttons (apart from disks).
Is there any specific reason to have "Rename" and "Edit description" functionalities separate instead of single "Edit"?

**Comment by andreasn** [comment]
@skobyda good calls! I've made the button default and merged the _Rename_ and _Edit description_ menu items.
Also discussed the design with @Ranelim and he pointed out it would be weird to single out the current snapshot, since the snapshot doesn't reflect the current state of the system, since a rollback could possibly have happened years ago.

![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/840024fa9a042da1990ab8c52ee297635771fa5a/virtual-machines/snapshots.png)

**Comment by andreasn** [comment]
Implementation happening in https://github.com/cockpit-project/cockpit/pull/13100

**Comment by gorshunovr** [comment]
I'm interested in this feature. Thank you for your work.

**Comment by irvinhomem** [comment]
Will be really pleased when this feature is available :-)

**Comment by jbravo94** [comment]
+1

**Comment by KKoukiou** [comment]
This is done.
