### ISSUE TITLE
Allow to upload a docker-compose file and past it to docker-compose

### ISSUE THREAD

**Issue by williamjmorenor** [cockpit-project/cockpit#13016]
Can be great to be able to upload a docker-compose file via cockpit web interface and pass it to docker-compose cli to make easy to run multiple containers septups.

Also should be great to allow the user to upload a new version of a previusly created docker-compose file.

Note that all images should be available in a registry since the user should upload only the docker-compose file and not all the sources.

**Comment by KKoukiou** [comment]
cockpit-docker package is not developed any further, thus I will have to close this issue.
If you are interested in podman, you can open this RFE in the [cockpit-podman repository](https://github.com/cockpit-project/cockpit-podman/), where we can discuss implementing something like that using [podman-compose](https://github.com/containers/podman-compose).
