### ISSUE TITLE
How to safely setup a regular setInterval() function in a Plugin?

### ISSUE THREAD

**Issue by mckenziec** [cockpit-project/cockpit#13034]
Cockpit version: 194
OS: Atomic Centos 7.1905.9

In a cockpit plugin (written in React, but that's doesn't matter so much), because the plugin view is loaded in an iframe, if I start a setInterval() to run a periodic call for something like a status check, the interval will run within the scope of the browser loaded URL. Meaning the interval will never stop after the time I visit my plugin while the tab/page is loaded. If the function being called is kind of heavy, you don't want it to run in the "background" while you're doing something else if the result is to update a plugin view you're not even looking at.

Here's a basic ES6/React bit on mount that illustrates my point:
```
  componentDidMount() {
    const interval = setInterval(() => {
        console.log("I'm still alive!")
    }, 5 * 1000)
  }
```
When the plugin is viewed, the interval will start and every 5 seconds the console will log the message. If you navigate away from the plugin view to another plugin, the interval will keep running.

I can cancel the interval, then start it again if I knew that the user was focused on my plugin. Do any of the existing plugins update the UI this way? Do they have the same issue?

Any tips would be great. Thanks.

**Comment by mckenziec** [comment]
Ah I just spotted a couple of code instances where cockpit.onvisibilitychange is used. I now see the cockpit.js doc on the topic. Closing.

https://github.com/cockpit-project/cockpit/blob/c5868236fb6f1c4da151827651812b7cd0f46aeb/pkg/docker/atomic.js

**Comment by martinpitt** [comment]
Correct, I was just about to reply with a pointer to https://cockpit-project.org/guide/latest/cockpit-location. The example that you found is a typical one. :)

**Comment by mckenziec** [comment]
Actually, maybe you could help with a tip on using it with React. I don't see an example plugin that uses React with the visibility callback.

I expected to be able to access the React state from my visibilityChanged() function, and its there when 1st fired when the plugin is viewed, but when I navigate away, this.state is null, and when I navigate back it's also null.

Basically "this" is undefined in React when cockpit.onvisibilitychange fires. Any ideas? Thanks!

**Comment by mckenziec** [comment]
Nope, figured it out. You have to bind this to the function assigned to cockpit.onvisibilitychange. My mistake.

```
cockpit.onvisibilitychange = this.visibilityChanged.bind(this)
```
