### ISSUE TITLE
Storage: "Format Disk" is not discoverable.

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#1304]
The "Format" for the whole device (that allows people to create partition tables) is in the menu at the top of the page.  For RAIDs, it is quite hidden even and only visible when people explicitly open the action menu.

https://bugzilla.redhat.com/show_bug.cgi?id=1142251

One idea is to move it down into the header of the "Content" panel.

**Comment by dperpeet** [comment]
@mvollmer should this be closed?

**Comment by mvollmer** [comment]
> should this be closed?

No, I think the problem is still there.

**Comment by dperpeet** [comment]
There are now 2 format buttons... one remaining in the action button, the other in the content section.
The problem: The opened dialogs look different. Do they do different things?
From action (raid):
![screenshot from 2015-03-19 11 52 27](https://cloud.githubusercontent.com/assets/8711649/6728975/8ddfdb4c-ce2e-11e4-8090-8ae5524560aa.png)

From content:
![screenshot from 2015-03-19 11 52 31](https://cloud.githubusercontent.com/assets/8711649/6728979/918ee83c-ce2e-11e4-9696-658787c8e76e.png)

**Comment by mvollmer** [comment]
> There are now 2 format buttons... one remaining in the action button, the other in the content section.
> The problem: The opened dialogs look different. Do they do different things?

Yes.  The first creates the partition table, the other creates partitions and filesystems.
