### ISSUE TITLE
Storage feature not shown

### ISSUE THREAD

**Issue by jtlarson** [cockpit-project/cockpit#13040]
Cockpit version: Version 195.1
OS: CentOS 7.7.1908
Page: Storage

The Storage feature is not visible on a fresh install of cockpit from CentOS repository on a virtual test machine. 
![image](https://user-images.githubusercontent.com/26283282/67579820-12d95280-f6fa-11e9-90f4-6e4eaf91ea19.png)

Things I have tried/verified:

1. I am logged into Cockpit as a full admin
2. udisks2 is installed and the service is running.
3. restarted cockpit service after installing udisks2
4. No relevant errors found in 'journalctl -u cockpit'

**Comment by jtlarson** [comment]
Didn't realize that Storage was provided as separate package which was not installed as dependency...

Fixed with `sudo yum install cockpit-storaged` command.

**Comment by NicoHag** [comment]
Thank you for that, I just found this, and it was the solution for me :)
