### ISSUE TITLE
Custom mount options

### ISSUE THREAD

**Issue by WonderingDane** [cockpit-project/cockpit#13062]
Cockpit version: 164
OS: Ubuntu 18.04
Page: Storage

How does the "Custom mount options" work? No matter what I try, I cannot get it to mount a drive with a specific user as the owner.

**Comment by mvollmer** [comment]
I am not sure I understand what you are trying to do.  Can you say what you did exactly, and what happened?  (Error messages, etc.)

Can you mount the drive on the command line?  If so, how do you do that exactly?  With that information, we should be able to say whether Cockpit can do it, too, and what might be missing.

**Comment by marusak** [comment]
We never got any reply, closing for not enough info.
