### ISSUE TITLE
The drop-down box disappeared where you can click and choose an item(e.g.:Installation Type,Storage on "Create VM")

### ISSUE THREAD

**Issue by cxhlunar** [cockpit-project/cockpit#13088]
Cockpit version: cockpit-machines-205.1-1.fc30.noarch
OS:Fedora30
Page: Create VM,Disk...

The drop-down box disappeared where you can click and choose an item(e.g.:Installation Type,Storage on "Create VM")
The function is still ok but may not so obvious to inform people that it's an drop-down box and user can choose items there.

Steps to reproduce
1. Click "Create VM", Disk page... etc.

**Comment by marusak** [comment]
Can you be please more specific? I don't understand exactly what is missing.
Ideally if you would post screenshot.
(I have slight idea that you might mean that caret on right does not show up? In that case can you also please check if there are some errors in browser's console?)

**Comment by cxhlunar** [comment]
Sorry that I didn't describe it clearly, pls check by comparing the following 2 pictures.

![screenshot-10 66 92 212_9090-2019 11 05-14_50_32](https://user-images.githubusercontent.com/12710195/68185167-de0faa00-ffdb-11e9-97d3-e7ad6adf86b5.png)

![screenshot-10 66 92 234_9090-2019 11 05-14_55_29](https://user-images.githubusercontent.com/12710195/68185365-56766b00-ffdc-11e9-8393-f18b5cb15671.png)

**Comment by cxhlunar** [comment]
![screenshot-10 66 92 212_9090-2019 11 05-14_50_32](https://user-images.githubusercontent.com/12710195/68185471-8cb3ea80-ffdc-11e9-91eb-1522e641ea1f.png)

**Comment by marusak** [comment]
Ah, I see! Thanks for the report, this is definitely broken.
Are you using just standard fedora 30 cockpit build? Does web browser's console say something (it may have problem with loading of some css files).

**Comment by cxhlunar** [comment]
Yes I'm using standard fedora 30 cockpit build. 
I didn't notice any error on web browser's console.
Browser:
Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by skobyda** [comment]
@cxhlunar You also mentioned Disk Add and Storage. Does this problem also happens there? Or does it also happens outside of machines page? Let's say in Kernel Dump page -> Crash dump location -> Location dropdown. Does it also happens there?

**Comment by cxhlunar** [comment]
Yes, it also happens on Disk add and storage,network ... pages in "Virtual Machines" tab, I only tried on some pages in virtual machines, all have the same problem. You can refer to the following pictures. 
I should specify that it's "cockpit-machines" related, not sure about other parts you mentioned above.
![screenshot-10 66 92 212_9090-2019 11 07-09_57_18](https://user-images.githubusercontent.com/12710195/68354245-d6204900-0146-11ea-9daa-4ae33776cad7.png)
![screenshot-10 66 92 212_9090-2019 11 07-09_57_06](https://user-images.githubusercontent.com/12710195/68354246-d6204900-0146-11ea-9683-87e1e63a8cf2.png)
![screenshot-10 66 92 212_9090-2019 11 07-09_54_53](https://user-images.githubusercontent.com/12710195/68354248-d6b8df80-0146-11ea-8e75-4d335527e3fa.png)
![screenshot-10 66 92 212_9090-2019 11 07-09_54_37](https://user-images.githubusercontent.com/12710195/68354250-d7517600-0146-11ea-865b-36d455d20f7a.png)

**Comment by skobyda** [comment]
> I should specify that it's "cockpit-machines" related

Thanks for response. If that also happens outside of machines page (like in kerneldump page), then it's probably a problem in our general dropdown component, thus no need to specify cockpit-machines.

**Comment by KKoukiou** [comment]
@cxhlunar what version of cockpit are you using? You said cockpit-machines is 205 but from the screenshots it looks like you're using a pretty old cockpit Base packages, definitely not 205 there.

**Comment by KKoukiou** [comment]
That is broken on distropkg images which are running
cockpit-bridge-196.3-1.el8.x86_64
cockpit-ws-196.3-1.el8.x86_64

**Comment by cxhlunar** [comment]
Yes, the cockpit-machines is 205 but others are 196. After update all the package to the newest version ,it's ok now.

**Comment by martinpitt** [comment]
Ack, thanks for confirming!

**Comment by martinpitt** [comment]
Reopening, as Katerina just sent a PR for this to work against old versions.
