### ISSUE TITLE
Network: WiFi, unmanaged, etc devices are ignored or not handled nicely.

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#1308]
We should list all devices and show their traffic even if we don't want to touch their configuration.

**Comment by stefwalter** [comment]
Moved this to the ideas page:

https://github.com/cockpit-project/cockpit/wiki/Ideas

**Comment by mvollmer** [comment]
I'll work on this since we need this for a good networking experience on Debian, where it is common that ethernet devices are explicitly unmanaged by NM.
