### ISSUE TITLE
The changes should not be remembered if click cancel when edit on Network interfaces

### ISSUE THREAD

**Issue by cxhlunar** [cockpit-project/cockpit#13115]
Cockpit version: cockpit-machines-205.1-1.fc30.noarch
OS: Fedora30
Page: Network Interfaces
Browser: Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)

The changes should not be remembered if click cancel when edit on Network interfaces

Steps to reproduce
1. Prepare a vm
2. Enter Network Interfaces tab
3. Click "Edit" to edit existing network
4. Change Interface Type to "Direct attachment", then click "Cancel"
5. Click "Edit" again. 

Actual Result:
In step 5, the  Interface Type is "Direct attachment" which was set in step 4
Expected Result:
In step 5, the last change of Interface Type should not take effect since we clicked cancel in step 4.

**Comment by marusak** [comment]
Indeed, thanks for the report.
@skobyda can you please take a look where is this remembered and why it is not set up whenever the dialog is opened. Thanks :)
