### ISSUE TITLE
rework system overview page

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#13121]
Redesign and rework the system overview page, with the following goals in mind:

1. **First impression**: It's the first thing people see when they load Cockpit, therefore it should look nice and work well.
2. **Understanding**: The main purpose of the page is to understand what's going on with a system.
3. **Guidance**: When there are issues, guide people toward solutions.
4. **Organization**: Group similar objects together.
5. **Standardization**: Right now, it's not obvious what each link does. Some go to a location, some pop up dialogs.
6. **Modernization**: It's grown bit by bit and has needed a rewrite for a while.

**Comment by garrett** [comment]
Here's a mockup made in Inkscape:

![system overview mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/system/system-overview.png)

I have a WIP at porting this to PF4 (using HTML, not React, for the mockup purposes) mixed into my new navigation mockups @ https://garrett.github.io/cockpit-mockweb/navigation2/

**Comment by garrett** [comment]
Andreas has mocked up how the system health card could look like with respect to Insights integration:

![system overview: health](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/system/system-overview-health.png)

Note: System health is more than Insights. It's cross-platform and is where our current notifications would be moved to.

**Comment by andreasn** [comment]
Moved Insights back into the health card on the overall system design.
https://raw.githubusercontent.com/cockpit-project/cockpit-design/8ffcf03d6e976c977d629ec7eefe7604f37ae960/system/system-overview.png

**Comment by martinpitt** [comment]
This looks great! Thanks so much for working on this! This categorization makes much more sense than the organically grown lump of info that we have now. The general layout also makes sense, and is also clear, pleasant to look at, and makes sub-pages much more discoverable (*cough* hardware info *cough*).

Some initial thoughts:

 - I guess you thought about this, but one thing I find a bit odd is that the "Metrics storage enabled" switch is not in the "Usage" card. There's of course some tension because enabling/disabling pcp is "configuration", but it determines whether or not "History" is even available.

 - Usage: We don't have "History" yet, do we? Would that be some more advanced PCP UI?

 - Domain: this could possibly merge into "Configuration", but as long as we are not cramped on space, this seems okay. Perhaps the explanatory text could say "Identity Management domain", as "domain" by itself is a little vague?

 - The "Edit Hostname" button seems a bit too prominent to me. This isn't something that one does all the time. It could perhaps move into the "Configuration" card?

**Comment by martinpitt** [comment]
Should "System information" become Title Cased? Does PF4 have something to say about header format?

**Comment by andreasn** [comment]
PF3 had various things that used headline case, but PF4 only uses headline case for _Product names and proper nouns_, everything else uses sentence case.

**Comment by garrett** [comment]
I have been intentionally moving to sentence case for everything (except Proper Names, which includes Product Names) in the mockups as that's what PF4 says to do.

We need to eventually move Cockpit over to this (at least for English, where it's a thing).

**Comment by garrett** [comment]
> I guess you thought about this, but one thing I find a bit odd is that the "Metrics storage enabled" 

Yep. Andreas and I talked about it. It influences history (which doesn't exist yet), the graphs (which would be on another page), and health (for displaying when there was an error in the past day or since last logged in or whatever). Usage is real-time-ish (average over the past 10 seconds or something... except on page load, except when PCP is enabled).

> Usage: We don't have "History" yet, do we? Would that be some more advanced PCP UI?

No, we don't have that yet. I'm thinking it would look _something_ like this (except hour-by-hour by default instead of day-by-day): https://garrett.github.io/cockpit-mockweb/overview/history

> Domain: this could possibly merge into "Configuration"

Yep, Andreas and I talked about this. I thought it impacts a lot of things and would have more information (as I don't have a way to test this currently), but it doesn't. So it'll probably be downgraded to being just an item on configuration.

---

You found all the stuff that's a bit more hand-wavy and undecided. This is all stuff I'm thinking about and playing around with at the moment. The rest is mostly solid, however.

What is pretty solid at this point:

1. Health area: "How is my machine?", with info from:
   - system-provided information (from systemd-provided info & pcp, if installed)
   - un-registered status (if applicable)
   - insights (if registered and enabled)
2. Usage area: "What is my machine doing?"
   - at-a-glance interpretation of what the machine is doing (at a very high-level)
   - history, eventually
   - links to the real-time-ish charts (which would be moved onto one page)
3. Info area: "What is my machine?" read-only information
4. Config area: Tuneables that don't fit anywhere else (usually because they impact things at a basic level)
   - These are modifyable, so the interations are internally consistent

Everything but the tunable block should be read-only information with links for more information (and to possibly do stuff).

---

BTW: Moving the charts serves multiple purposes:
1. Reduces system load while fetching information
   - the usage area also needs polling, but we can lengthen the pulling time and, for example: have disk size update every 30 seconds, CPU every 10, memory every 10... instead of updating everything every second with a re-draw
2. Reduces visual complexity (which would need to be interpreted anyway)
3. Provides an accessible way (in all senses of the word) to understand the system load
4. Encourages someone who wants a dashboard to install Grafana or some other dashboard from our Applications page and use it from the integrated navigation (this needs work done)
   - Grafana would need to be easy to install from Cockpit (separate task, but this is encouraged)
   - We need the unified navigation too (pending; there's a design for that #12784)

**Comment by garrett** [comment]
Rough experimental sketch about the visualization of Insights hits:

![insights-hits](https://user-images.githubusercontent.com/10246/68596392-6d650380-049b-11ea-96c1-b5fc30481c4a.png)

We could consolodate the hits into 1 line like this.

The "icon" could be made by having:
- each hit be a pixel wide
- each group of hits be separated by a pixel
- drawing a box around them
- have a max-width of icon×2 (so 32px)
- doing this all with flex (with flex-basis and forcing the widths to scale down if they're too wide)

The icon could be accessible, or we could just ignore it and rely on the string (if the string is informative enough). I opted for a long string here with all the details to have it wrap. Ideally, this would be the last item due to possibly-different-sized icon.

**Comment by garrett** [comment]
Alternative, locked in size, with most important hits at top and least at the bottom, sized inside to scale. The label has been shortened to show # of hits and states the highest severity level found:

![insights-hits](https://user-images.githubusercontent.com/10246/68597634-9a1a1a80-049d-11ea-89dd-34eac5e4726a.png)

**Comment by andreasn** [comment]
I think the second works better. It's a new element not seen anywhere else where we show Insight results (Satellite and cloud.redhat.com), but it probably works.

**Comment by garrett** [comment]
Same as above, but with a 1-pixel gap between severities:

![insights-hits](https://user-images.githubusercontent.com/10246/68597912-114fae80-049e-11ea-8ae1-70cf2371f5fa.png)

**Comment by garrett** [comment]
For the sake of seeing how it'd look, here's the card concept with charts ported over (just as sparkline-like charts):

![system-overview-charts](https://user-images.githubusercontent.com/10246/68601936-a7d39e00-04a5-11ea-86ec-2d69c60320dd.png)

I merged domains and hostname editing back into settings and dropped the usage block (as it's mostly redundant with the charts that more-or-less have that info at the top).

**Comment by garrett** [comment]
Here's a mod that makes usage 1 card again, but uses simple graphs inside (that would usually be 4-up with a minimum constraint that would cause them to stack in small width screens):

![system-overview-charts](https://user-images.githubusercontent.com/10246/68603995-c176e480-04a9-11ea-9968-7b15cbffb347.png)

I inflated the memory to show how it could be an indicator of an issue. This sadly doesn't work well for others like disk, as we're showing IO instead of used/available space.

**Comment by andreasn** [comment]
Visually I think the combined card looks a little bit better.

**Comment by andreasn** [comment]
If there is a notion that current, but not historical utilization would be helpful, there is also [doughnut charts](https://www.patternfly.org/v4/documentation/react/charts/chartdonututilization#donut-utilization-examples). If we use those we could get away with polling for data more seldomly.
I guess it's pretty much the same as the first mockup with Usage, but using slightly more real-estate :)

**Comment by garrett** [comment]
> the combined card looks a little bit better

Yep, the split cards were bugging me, and then there's no place for links... hence the combined cards. It's good to see you think the same.

I'm still not sure about keeping graphs on the main page. That is, I still think we shouldn't, as it's an often-unneeded drain on resources.

> If there is a notion that current, but not historical utilization would be helpful

Basically, yes. That was my thought — polling data much less frequently as to not swamp the machine, especially when people don't usually need that info constantly refreshed.

Doughnut charts are flashy, but they're not as scannable as a list of data and bars.

**Comment by garrett** [comment]
I've updated the SVG & PNG with the latest talked-about changes. The topmost mockup is linked inline, so it should always update when it changes in the design repo. (It _might_ need a shift-reload to bust cache.)

1. The store metrics toggle is now hidden behind a dialog (that would explain what benefits you'd have for enabling the feature and provide a better place to show installation)
   - It's perfectly fine to keep the toggle as-is in the first pass, so this is an optional change.
2. Insights changed to a shorter string
3. Insights "icon" is the dynamic one I proposed earlier.
   - I should make some example HTML+CSS that generates this as discussed. :wink:
4. Hostname + a link for editing is in Configuration.
   - Just like the other "links" in editing, it is a button that's styled like a link. PatternFly has a special link button class under the button widgets for this.
   - Accessibility label (aria-label) should be set to "edit hostname", to provide better context.
5. I dropped "History", as we're not going to implement it in this round. (It would be nice to do this later, at some point.)

Notes:
- All "links" under configuration are actually buttons styled as links.
  - Widget: https://www.patternfly.org/v4/documentation/react/components/button#variations
  - Design guideline: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/buttons-and-links#page-sidebar "Use a text button for secondary or tertiary actions on a page or modal. For example, you might _use text buttons to indicate actions a user might take on items in a data list or table_ to reduce visual clutter and save space." (Emphasis mine.)
- Links everywhere other than Configuration are actually links. :wink:
- The Insights link will probably open in a new window/tab. (hence the trailing icon)
- Insights shows the "most severe" label in the hits.
- Insights "icon" is dynamically generated to basically show a stacked graph of hits, but in an icon format.
- SVG is the design reference to use (in general). The live HTML mockup is a playground to test native PF4 widgets as a framework for this. The PF4 tables have lines, which is fine in the implementation. (The SVG currently lacks the divider lines in tables.)
- The HTML implementation is using PF4 tables for everything, not ct-form.
- All configuration actions pop up dialogs.
  - Dialogs exist for every action except for store metrics.
  - As stated above, it's fine to keep using a toggle for the metrics toggle in the first pass.

**Comment by andreasn** [comment]
Looks good to me!

**Comment by andreasn** [comment]
What's under the kebab on the top-right, next to `Restart` btw?

**Comment by marusak** [comment]
> What's under the kebab on the top-right, next to `Restart` btw?

I don't know, but I was wondering where is `Shutdown` button, so I guess it is there?

**Comment by garrett** [comment]
> What's under the kebab on the top-right, next to `Restart` btw?

It's basically shut down, like we have now:

![Screenshot_2019-11-14 System - Rain](https://user-images.githubusercontent.com/10246/68862495-d6dc5080-06ed-11ea-9c91-015314be7bf1.png)

...except with a kebab instead of a combo button.

(It probably doesn't need "Restart" to be repeated, though.)

I guess we _could_ also have suspend if the computer supports it — but that's not a typical use case for servers, so probably not. :man_shrugging:
