### ISSUE TITLE
Storage: Not using PF4 style headers

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#13126]
Followup to https://github.com/cockpit-project/cockpit/pull/13099

Cockpit version: 205
OS: Fedora 31
Page: Storage

#13099 re-implemented the table in PF4, but the table header ended up looking a bit off.

![image](https://user-images.githubusercontent.com/209895/68599704-56c1ab00-04a1-11ea-9d35-a18439e7ca95.png)

To fix this, I made a quick design of a more free-floating header that relies on it's font size rather than a gray container to explain it's hierarchy.
![storage-pf4](https://user-images.githubusercontent.com/209895/68600910-9d180980-04a3-11ea-8e8e-c26b5aeefe90.png)

**Comment by andreasn** [comment]
But a little bit on the fence if this is better or worse.

**Comment by garrett** [comment]
I think it's more consistent with PF4, so it makes sense.

We probably need to rework the page overall at some point (so the layout makes more sense order-wise) and I think this is (probably) a good incremental improvement.

**Comment by garrett** [comment]
(Note: The page is supposed to already have a grey background. Some sort of regression happened and it reverted back to white. I haven't fixed it yet, but switching to your mockup would be a good time to adjust it. Other pages also lost the grey backgrounds too.)
