### ISSUE TITLE
machines: Bridge To LAN

### ISSUE THREAD

**Issue by prociomem** [cockpit-project/cockpit#13141]
Cockpit version: 206-1 (Current Debian version)
OS: Debian
Page: Virtual Machines (Editing VM Network Config)

After the standard install on debian installing cockpit and cockpit machines, i created a simple lubuntu VM. Now i wanted to change the Network Type to Bridged (on the Virtual Machines Page> 'VM-Name'>Networks> Edit).

The Virtual Network Interface Settings dialog has a setting Network Type that says "Virtual Network", there is an option for "Bridge to LAN" in the drop-down, but it is grayed out. How do i get this "Bridged to LAN" option to be selectable?

**Comment by andreasn** [comment]
@KKoukiou or @skobyda do you know what's up here?
I see there is https://github.com/cockpit-project/cockpit/pull/12780 so does this mean _Bridge to LAN_ is not implemented yet?

If so, I think we should either try to land #12780 as soon as possible, or remove the option from the dropdown all together for now.

**Comment by KKoukiou** [comment]
It's not implemented yet. Greying out options indeed is not good way to show that something is currently not implemented.
@skobyda can you continue working on #12780 :) ?

**Comment by skobyda** [comment]
> @skobyda can you continue working on #12780 :) ?

Sure
