### ISSUE TITLE
Idea about tutorials

### ISSUE THREAD

**Issue by PrzemekSkw** [cockpit-project/cockpit#13154]
Hi, I cannot find any tutorial how to install nextcloud or owncloud in cockpit. I install docker and owncloud on my server by cockpit but don't know what to do next. That will be great if someone will make a tutorial how to install docker apps with cockpit.

**Comment by marusak** [comment]
> I cannot find any tutorial how to install nextcloud or owncloud in cockpit

"in" Cockpit? What do you mean?

> ... but don't know what to do next.

I am afraid I do not follow at all. Can you please be more specific? What do you want to accomplish?

> ...tutorial how to install docker apps with cockpit.

"docker app"? You mean https://docs.docker.com/app/working-with-app/ ?

**Comment by KKoukiou** [comment]
I am closing this since it's inactive for a month already and also it's not clear what is requested. Feel free to reopen if you think the question is relevant still, but make sure to provide answer to the questions above.
