### ISSUE TITLE
Possibility to run cockpit session constantly in the background

### ISSUE THREAD

**Issue by loboda4450** [cockpit-project/cockpit#13178]
Hello,

I'm a new user of Cockpit and I need a constant control of what my server is doing. Apparently Cockpit does not give such a option, does it? Is there any possibility to start a session and gain access to it by logging in on my-server-ip:9090 (by default)?

**Comment by martinpitt** [comment]
What do you mean with "constant control"? It is *possible* to let the cockpit web server run all the time, but unless someone actually logs into it, that has zero value -- it just uses resources for no purpose. Perhaps you mean that you want a constant monitoring/logging of performance data? PCP does exactly that, you can enable it in cockpit and then PCP will run all the time.

**Comment by loboda4450** [comment]
Thanks, it took me a while to add it to my cockpit, but finally it works!
