### ISSUE TITLE
test: Create simpler ABRT workflow

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#13176]
In ABRT tests we test full fedoraCCpp workflow which does way too many things which do not propagate into Cockpit in any way. Thus we could just create simpler custom workflow for testing, which would only do things we really test. It would mean the test would be faster and more resistant to future hiccups.

@ernestask could you please take a look?
It can be based on [FedoraCCpp](https://github.com/abrt/libreport/blob/master/src/workflows/workflow_FedoraCCpp.xml.in) but it should be enough to just use `report_uReport` and `report_Bugzilla` with possibly touching some files which may be required by the latter one.

**Comment by ernestask** [comment]
Created https://github.com/cockpit-project/cockpit/pull/13184 for this.
