### ISSUE TITLE
debug totp for login?

### ISSUE THREAD

**Issue by lachlan-00** [cockpit-project/cockpit#13195]
Page: Login

Currently we use http auth for login to cockpit but is it possible to allow 2fa auth through a OTP instead?

**Comment by martinpitt** [comment]
Yes, that has worked just fine for years, see e. g. [this demo](https://www.youtube.com/watch?v=gXsOt6zgBs4.) You can set up google-authenticator or similar, and add it to /etc/pam.d/cockpit. I just tested that again a week or two ago.

Did you already try and it doesn't work, or was this just an initial question?

**Comment by lachlan-00** [comment]
Sorry, I didn't realise it used pam auth.
I was looking for an application or a package for it specifically

**Comment by lachlan-00** [comment]
Is there a way to debug the login attempts? Adding the map module to my cockpi file doesn't allow using the codes and fails auth.

```
#%PAM-1.0
auth       required     pam_sepermit.so
auth       substack     common-auth
auth       optional     pam_ssh_add.so
# google authenticator for two-factor
#auth required pam_google_authenticator.so debug
account    required     pam_nologin.so
account    required     pam_shells.so
account    include      common-account
password   include      common-password
# pam_selinux.so close should be the first session rule
session    required     pam_selinux.so close
session    required     pam_loginuid.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required     pam_selinux.so open env_params
session    optional     pam_keyinit.so force revoke
session    optional     pam_ssh_add.so
session    include      common-session

# Read environment variables from /etc/environment and
# /etc/security/pam_env.conf.
session    required     pam_env.so # [1]
# In Debian 4.0 (etch), locale-related environment variables were moved to
# /etc/default/locale, so read that as well.
session    required     pam_env.so user_readenv=1 envfile=/etc/default/locale
```

**Comment by lachlan-00** [comment]
in coclpit itself it logs that it doesn't send an autorize message 

```

ignoring failure from session process: Authentication failed: Timeout cockpit-ws
cockpit-session: didn't receive expected "authorize" message
```

**Comment by lachlan-00** [comment]
Needed extra config lines in the pan conf for totp

**Comment by vleeuwenmenno** [comment]
@lachlan-00 could you share which lines? I'm trying to enable it for my instance of cockpit.

**Comment by lachlan-00** [comment]
> @lachlan-00 could you share which lines? I'm trying to enable it for my instance of cockpit.

i'll try to dig that up, check my config and edit this comment. it's been running for a few years now without issue
