### ISSUE TITLE
Trying to nail down a login "Not Found" situation 

### ISSUE THREAD

**Issue by mckenziec** [cockpit-project/cockpit#13194]
Cockpit version: 195.1
OS: Centos7

Everything has been trucking along fine for months of developing plugins, but I diverted my attention for a couple of weeks and when I turn back, Yes I _may_ have rebooted the vm. I can't login to my cockpit-ws docker container anymore. I get the dreaded "Not Found" message. I'm running cockpit-ws in a docker container, and both cockpit-bridge and cockpit-system are install on my local VM. 

First, no firewall in my dev environment. It's off.

Second, se linux is disabled.

Third, sshd is running and fine enough. I can ssh on board. I had multi-server cockpit machines ssh'ing into each other for a while. 

When I attempt to login (with privileges or without), journald shows ssh accepts my connection, there's some mention of registering authentication for cockpit-bridge, then 15 seconds later I see the ssh disconnect. The only thing I did in Chrome was login and stare at the "Not Found" page.

```
Nov 26 16:35:14 getter1.acme.com sshd[23723]: Accepted password for chris from 127.0.0.1 port 50812 ssh2
Nov 26 16:35:14 getter1.acme.com systemd[1]: Started Session 36 of user chris.
Nov 26 16:35:14 getter1.acme.com systemd-logind[9367]: New session 36 of user chris.
Nov 26 16:35:14 getter1.acme.com sshd[23723]: pam_unix(sshd:session): session opened for user chris by (uid=0)
Nov 26 16:35:14 getter1.acme.com polkitd[9285]: Registered Authentication Agent for unix-session:36 (system bus name :1.352 [cockpit-bridge], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Nov 26 16:35:14 getter1.acme.com org.gtk.vfs.Daemon[23754]: fusermount: failed to access mountpoint /run/user/1000/gvfs: Permission denied
Nov 26 16:35:30 getter1.acme.com polkitd[9285]: Unregistered Authentication Agent for unix-session:36 (system bus name :1.352, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Nov 26 16:35:30 getter1.acme.com org.gtk.vfs.Daemon[23754]: A connection to the bus can't be made
Nov 26 16:35:30 getter1.acme.com sshd[23725]: Received disconnect from 127.0.0.1 port 50812:11: Bye Bye
Nov 26 16:35:30 getter1.acme.com sshd[23725]: Disconnected from 127.0.0.1 port 50812
Nov 26 16:35:30 getter1.acme.com sshd[23723]: pam_unix(sshd:session): session closed for user chris
Nov 26 16:35:30 getter1.acme.com systemd-logind[9367]: Removed session 36.
```

The cockpit-ws container doesn't provide any clues. Chrome doesn't note anything in developer tools. I tried it with Firefox just in case, same story.

Can someone provide a clue? There have been other issues posted about the "Not Found" login page, but its never conclusive what the issue is.

Any more expressive logging? Somewhere else I can look for a clue? Thanks and keep up the excellent project. Cockpit it needed!

**Comment by martinpitt** [comment]
Sorry that this slipped through the cracks. This is really stale, so closing.
