### ISSUE TITLE
Fix Cockpit's usage of the `hidden` attribute

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#13207]
Let's fix where `hidden` is used as an attribute, so we can use the hidden CSS override method, as talked about in https://meowni.ca/hidden.is.a.lie.html & https://css-tricks.com/the-hidden-attribute-is-visibly-weak/

A PR addressing this needs to do two main things:
1. Fix HTML & JS where hidden is used, so it's to spec:
   - `hidden` in the HTML spec: https://www.w3.org/TR/html51/editing.html#the-hidden-attribute
   - `hidden` is a boolean, we need to make sure it's implemented properly in Cockpit: https://www.w3.org/TR/html51/infrastructure.html#boolean-attribute
      > Note: The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether. 
2. Add an approrpaite CSS override to global CSS that's included in every page of Cockpit:
   ```css
   [hidden] { display: none !important; }
   ```

**Comment by leomoty** [comment]
#13200 is related, just checked and they use `hidden` attribute.

**Comment by garrett** [comment]
@leomoty: Wow, that particular bug is a very good reason why this should be fixed sooner rather than later. Thanks for opening the issue and pointing it out here!

**Comment by leomoty** [comment]
Hey @garrett, is this the direction you wanna go?

https://github.com/leomoty/cockpit/commits/hidden-usage

Hidden attribute is, at least for network page, everywhere, so instead of toggling `show/hide` from jQuery (which will add `display: none;` to the element), is it clearer to toggle the prop? Keep in mind that `prop('hidden', false)` will omit the tag altogether and not keep `hidden=false|true` in DOM.

**Comment by leomoty** [comment]
@garrett ping.

**Comment by garrett** [comment]
@leomoty: Looks good to me, but I'd like it to be a PR and have someone in charge of the JS to look it over too.

I'll try to remember to bring it up at today's stand-up. If not, then I'm adding it to the meeting minutes for Wednesday's call, just in case.

**Comment by leomoty** [comment]
@garrett sure, I can open a draft PR, I just meant to understand if that were the direction you wanted to go.
