### ISSUE TITLE
API for custom dash

### ISSUE THREAD

**Issue by matyhaty** [cockpit-project/cockpit#13201]
Hi All

Im new to cockpit, so this might be a noob question, but i have trawled the docs and not found this, so apologies if ive missed it

Im looking to make a custom dashboard of a number of machines which will be cockpit-ted up and running.

Is there a way I can poll the 'master' install and get various metrics (cpu, ram, space etc) and use this on my own custom dashboard?

Thanks for any help

**Comment by martinpitt** [comment]
That's more or less what the "official" dashboard does: https://github.com/cockpit-project/cockpit/blob/master/pkg/dashboard/list.js#L56

You can copy that code into your's, and adjust it to what you need. There's no way to directly import individual UI elements into your page (you can use the entire dashboard frame, but I suppose that's not what you want).
