### ISSUE TITLE
first login on a machine, has no superuser permission

### ISSUE THREAD

**Issue by zombinary** [cockpit-project/cockpit#13215]
Cockpit version: **194**
OS: **Fedora release 30 (Thirty)Fedora release 30 (Thirty)**
Page: **login page**

After first user login on a new machine, the user is not permitted to do superuser actions.

Steps to reproduce

1. open the console on your machine
2. create a new user
     $ adduser test
3. add user to superuser group
     $ sudo usermod -aG wheel test
4. add password
     $ passwd test
5. remove last login date
     $ sudo chage -d 0 test
6. login in cockpit wih old password
7. create new password

Now it is not possible to do superuser actions.
U must logout and login again to have the correct permission.

Is it possible to check the permissions after a login and thus avoid a manual logout?

**Comment by martinpitt** [comment]
It's supposed to work that way already, i. e. the first login shouldn't be special. Do you see anything in the journal (`sudo journalctl -f`) the first time it happens? I'm afraid I cannot reproduce this here.

**Comment by marusak** [comment]
We would need more info + there has been some major changes about gaining superuser permissions since.
