### ISSUE TITLE
machine: Show that guest OS is unresponsive when detaching devices

### ISSUE THREAD

**Issue by skobyda** [cockpit-project/cockpit#13213]
Page: machines

When detaching a device (disk, network interface, ...) a signal is sent to VM's OS to detach that device.
However if VM's OS is frozen, unresponsive or if guest doesn't have any kernel at all... then detaching of that device will not happen.
This may also be a problem when an VM is overloaded, then detaching a device might take a long time.
However we will not get any error, as we don't know if VM is just overloaded or frozen/unresponsive.... And user will still see the device which they just tried to detach.
The only way for us to know something might have gone wrong is that we won't get any `device-removed` signal.

So in case that we send a request for detaching a device, we can show some spinner next to the device Detach button. And if we do not get device-removed signal after X seconds, we can show an warning with something like: "Detaching device is taking too long. VM might be unresponsive/frozen/overloaded...."

**Comment by KKoukiou** [comment]
I agree - let's not close the dialog until we get device-removed signal.
