### ISSUE TITLE
CentOS 8 - Cockpit Preview 208: Multiple Matches of cockpit

### ISSUE THREAD

**Issue by PeterFalken** [cockpit-project/cockpit#13216]
Cockpit version: 208
OS: CentOS 8
Page: Software Update

Description:
There appears to be multiple entries for cockpit version 208 on the COPR repository.
This blocks the Software Update page from upgrading the cockpit packages

Steps to reproduce:
1. On a CentOS 8 machine with cockpit preview 207 or earlier
2. Try to upgrade to version 208 of cockpit through the PakageKit based Software Updates page.

Attaching screenshots.
![MultMatchCockpit_A](https://user-images.githubusercontent.com/2557898/69835481-9e696600-1207-11ea-81e1-c4da87c4f82c.png)
![MultMatchCockpit_B](https://user-images.githubusercontent.com/2557898/69835486-a2958380-1207-11ea-9dba-68f0f5dcb281.png)

**Comment by marusak** [comment]
Indeed, 208 is built twice in copr. I think there was hiccup during release and it needed to be re-ran.
I would remove one of the build, but I don't have access there. @martinpitt could you please take a look?
(side note - I requested access to this repo so I can do this kind of maintenance)

**Comment by martinpitt** [comment]
I deleted one of the two identical builds, and also added @marusak as a copr admin. Sorry for the hiccup!

**Comment by PeterFalken** [comment]
Thanks Martin.
