### ISSUE TITLE
User cockpit-ws not cleaned-up after uninstallation.

### ISSUE THREAD

**Issue by robertdebock** [cockpit-project/cockpit#13239]
Cockpit version: 
OS: RHEL 8

After uninstalling `cockpit-ws`, the user (and group) `cockpit-ws` still exist. This issue was addressed earier in #11049, but the fix just changes the homedirectory.

Steps to reproduce

1. Install cockpit-ws: `dnf install cockpit-ws`
2. Remove cockpit-ws: `dnf erase cockpit-ws`
3. Verify that the user and group still exist: `grep cockpit-ws /etc/passwd /etc/group`

I think the [tools/cockpit.spec](https://github.com/cockpit-project/cockpit/blob/master/tools/cockpit.spec#L463) should clean up on uninstallation.

**Comment by martinpitt** [comment]
See the comments in https://github.com/cockpit-project/cockpit/pull/13240 why we don't do this.
