### ISSUE TITLE
The "Privileged" indicator in the shell is misleading

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#13232]
Cockpit version: 207
Page: Shell

The "Privileged" indicator in the shell seems to indicate whether or not the logged in user has "superuser" privileges.  It's tooltip says "Login has escalated admin privileges".

However, the visibility of the indicator only corresponds to whether Cockpit will reuse the login password "for privileged tasks and to connect to remote machines". This is not the same as actually having "superuser" privileges.

Cases where this matters:

- A user account that is not in "wheel".  Even if the password is reused for sudo, the session will not have "superuser" privileges.

- The root account.  Even if the password is not reused for sudo, the session will have "superuser" privileges.

**Comment by martinpitt** [comment]
This was fixed in @mvollmer's authentication rework a few months ago.
