### ISSUE TITLE
Firewall: No zones and unclear firewall status if unprivileged

### ISSUE THREAD

**Issue by leomoty** [cockpit-project/cockpit#13247]
Cockpit version: 207
OS: Fedora Server 31
Page: Network

If you login to cockpit with privileged access, you are greeted with: 

![image](https://user-images.githubusercontent.com/1463740/70255084-f56dbe80-1764-11ea-9ffc-7c5fe258c793.png)

And then clicking zones, you'll get to see them:

![image](https://user-images.githubusercontent.com/1463740/70255132-0a4a5200-1765-11ea-9f29-9b70af947b42.png)

However, if you are not in a privileged session:

![image](https://user-images.githubusercontent.com/1463740/70255258-3c5bb400-1765-11ea-94db-9fe500a79331.png)

See that it says "0" zones instead of "1" and that firewall toggle is active.

If you click the zones again, you'll find this:

![image](https://user-images.githubusercontent.com/1463740/70255386-7331ca00-1765-11ea-870e-ea7f04224bee.png)

And a warning message in console:

```
{…}
​
message: "org.fedoraproject.slip.dbus.service.PolKit.NotAuthorizedException.org.fedoraproject.FirewallD1.config.info"
​
name: "org.fedoraproject.slip.dbus.service.PolKit.NotAuthorizedException.org.fedoraproject.FirewallD1.config.info"
​
problem: null
```

I would expect to:

- Tell me that I am not authorized to see the firewall/zone status;
- Keep consistent enabled/disabled firewall enablement across pages

**Comment by Gundersanne** [comment]
Thanks for reporting! I can indeed reproduce this easily. I'll get on it :)
