### ISSUE TITLE
Performance Co-Pilot

### ISSUE THREAD

**Issue by BinaryBrother** [cockpit-project/cockpit#13254]
It appears that stable packages for **Performance Co-Pilot** now exist for Debian.

I'm just the janitor, so don't shoot me for any potential ignorance, here.

Add Repo:
`echo "deb https://dl.bintray.com/pcp/stretch stretch main" | sudo tee -a /etc/apt/sources.list`

Apt Install:
`apt-get update`
`apt-get install pcp`

Maybe your old _cockpit-pcp_ deb-package will install correctly, now. If not, maybe it'll be possible to rebuild it, now that the dependency appears to be fulfilled. I should have done more research before posting this, but it's the end of a long run getting a new server online for my employer and I'm fresh out of angel du... Uhh... Motivation...

**Comment by KKoukiou** [comment]
Thanks for reporting this @BinaryBrother 
Actually we do have [explicit check for stretch](https://github.com/cockpit-project/cockpit/blob/master/tools/debian/adjust-for-release#L23), which still seems to not have PCP package, see https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=pcp.

I am not sure why the mirror you pointed to contains that package but it's not officially in stretch.

In any case, the new stable release (buster) contains PCP and we build cockpit-pcp there.

**Comment by martinpitt** [comment]
Correct. [pcp](https://tracker.debian.org/pkg/pcp) exists in stable (buster), but not oldstable (stretch).
