### ISSUE TITLE
No ability to add remote server.  No dashboard page present

### ISSUE THREAD

**Issue by QuestionDevelopment** [cockpit-project/cockpit#13253]
Cockpit version: 185 (provided via dnf install)
OS: Centos 8

All the guides/documentation I can find to add say to go to my dashboard where I will have the ability to add a server.  My system does not have a dashboard (see screenshot) and I can not find the page/functionality referenced anywhere.
![screenshot](https://user-images.githubusercontent.com/394869/70377741-13aef800-18e6-11ea-9835-829b911ae993.jpg)

**Comment by marusak** [comment]
Install cockpit-dashboard. If it is not available in base centos repo, it definitelly is in https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/
