### ISSUE TITLE
machines: ERROR unsupported configuration: CPU mode 'custom' for x86_64 kvm domain on x86_64 host is not supported by hypervisor Domain installation does not appear to have been successful. If it was, you can restart your domain by running: virsh --connect qemu:///session start Ubuntu-Server otherwise, please restart your installation.

### ISSUE THREAD

**Issue by MauriceNorden** [cockpit-project/cockpit#13256]
Cockpit version: 164
OS: Ubuntu 18.04.3 LTS (Server)
Page: Virtual Machines 

Hello Everyone,
I was trying to make a windows 10 vm in cockpit 164.
After pressing ''Create" and "Install" i got the following error:

"
ERROR unsupported configuration: CPU mode 'custom' for x86_64 kvm domain on x86_64 host is not supported by hypervisor Domain installation does not appear to have been successful. If it was, you can restart your domain by running: virsh --connect qemu:///session start Ubuntu-Server otherwise, please restart your installation.
"

This is my server log after pressing install:
"
Dec 08 15:17:01 mn-devs CRON[11913]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 08 15:17:01 mn-devs CRON[11914]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Dec 08 15:17:01 mn-devs CRON[11913]: pam_unix(cron:session): session closed for user root
"

There is no direct way to reproduce this error.

Edit:
I allso tryed to reboot my server but that didn't helped

**Comment by KKoukiou** [comment]
Do you have Virtualization technology enabled in your BIOS? 
```grep -E '(vmx|svm)' /proc/cpuinfo``` should give some output.

Secondly is your user part of the KVM and libvirtd groups? If not ```sudo adduser `id -un` kvm```

Generally try to make sure you have set up correctly your envoronment for using libvirt like here https://help.ubuntu.com/community/KVM/Installation 

If this does not work please paste the output of `virsh dumpxml your-windows-vm-name` and the output for `cat /proc/cpuinfo` here.

**Comment by polhaghverdian** [comment]
> Secondly is your user part of the KVM and libvirtd groups? If not `` sudo adduser `id -un` kvm ``

This solved the problem for me, thanks! I think this should be automated, or atleast having this in the documentation?

**Comment by KKoukiou** [comment]
> > Secondly is your user part of the KVM and libvirtd groups? If not `` sudo adduser `id -un` kvm ``
> 
> @KKoukiou
> This solved the problem for me, thanks! I think this should be automated, or atleast having this in the documentation?

This is something that you can discuss with the developers of kvm or libvirt but really I don't see how could be automated. When you install libvirt (which will install kvm dependency) you can't just add kvm group to all users on the system, that's extremely invasive. So since that's not cockpit specific, since virsh CLI will have the same behavior and the libvirt documentation has the steps needed to use non-root users without password, I will close it. Feel free to go on ofct IRC #virt channel and ask the developers there about their opinion.
