### ISSUE TITLE
Cron Jobs

### ISSUE THREAD

**Issue by catborise** [cockpit-project/cockpit#13257]
Page: 
It could be nice if you manage cron jobs with cockpit. 
Adding, editing and remove operations could be done easily.

date - command - actions(delete, edit) would be enough.

thanks

**Comment by michaelsogos** [comment]
Hi @cockpituous 

I agree, also could be good to visualize CRON logs :)

**Comment by martinpitt** [comment]
The Services page can create and edit systemd timers. We don't plan to do visual crontab editing any time soon. Of course anyone is welcome to implement  this on their own cockpit-cron page/project.
