### ISSUE TITLE
Check `aria-label` across Cockpit; make sure there isn't something better (like a role attribute) or labelled-by; else make sure it's translated

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#13271]
In https://github.com/cockpit-project/cockpit/pull/13199#discussion_r356050927, @Gundersanne and I talked about some code that's used across Cockpit in multiple places that uses `aria-label='inline danger alert'`.

This specific example (and similar code) should _probably_ use `role="alert"` instead.

We should check Cockpit for `aria-label`s and change them to one or more of the following (in preferred order, depending on the context of the snippet):
1. A semantic element that has inherent meanings
2. Use `role=` (and the role) instead
3. Use `aria-labelledby` instead of `aria-label`
4. Make sure the `aria-label` is translated

**Comment by garrett** [comment]
We should do this in January. Ideally, we can ask @jgiardino — perhaps we can even discuss this at the face-to-face meeting.

**Comment by garrett** [comment]
By-the-way, this is a relevant link: https://adrianroselli.com/2019/10/stop-giving-control-hints-to-screen-readers.html

**Comment by martinpitt** [comment]
We are getting more and more aria-labels on our pages, mostly triggered via PatternFly's warnings. In such generality, this issue is too big to be actionable effectively.
