### ISSUE TITLE
system: graphs: Remove workaround for min width and height in order for the graphs to show up

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#13283]
When I changed the graphs code I introduced this ugly WA here https://github.com/KKoukiou/cockpit/blob/overview-redesign/pkg/systemd/graphs.less#L130in order to make the graphs appear. Because if the graphs container has no width and height set to be different than 0 [this code here](https://github.com/KKoukiou/cockpit/blob/overview-redesign/pkg/lib/plot.js#L494) makes sure that the graphs are not shown.

Can we somehow find a better fix for this?

**Comment by garrett** [comment]
I think the proper link is https://github.com/cockpit-project/cockpit/blob/master/pkg/systemd/graphs.less#L130 ?

(The URLs to KKoukiou/cockpit no longer work.)

**Comment by garrett** [comment]
Possibly related issues: 
- Usage graphs labels crop outside the card https://github.com/cockpit-project/cockpit/issues/13283
- CPU usage chart doesn't show https://github.com/cockpit-project/cockpit/issues/13290

All of these charts issues are related to the sizing of the charts.

A guess: Perhaps they're all related to the chart rendering possibly being called too early, before the page is sized properly? (Resizing seems to fix things, at least for some of them.)

**Comment by KKoukiou** [comment]
These graphs are obsolete.
