### ISSUE TITLE
system: Usage graphs labels crop outside the card

### ISSUE THREAD

**Issue by leomoty** [cockpit-project/cockpit#13287]
Cockpit version: 209
OS: Fedora Server 31
Page: System Page > Usage Graphs

If the browser screen is small the axis labels from the chart can crop outside the card content portion.

![image](https://user-images.githubusercontent.com/1463740/70798194-0df16080-1d85-11ea-9f17-8e834533295e.png)

**Comment by garrett** [comment]
Yep, I talked with @KKoukiou about this and there's nothing I can do. The HTML is correct, the CSS is correct — it's a problem with the JavaScript that draws the canvas.

A workaround is to resize the browser and the graphs are sized correctly. 

My guess is that the graphs are trying to draw too early, before the page layout is fully resolved.

I guess we could defer the rendering or re-trigger a layout?

**Comment by garrett** [comment]
Note: We would like to move away from Flot and to PatternFly 4's charts. Doing so would probably fix the issue.

**Comment by garrett** [comment]
I've been trying to fix this for a while today, and have had it kind of working... but then it doesn't work quite right on another page load. I think it's really rahter random and needs to be fixed in the JavaScript. Sigh.

**Comment by garrett** [comment]
We dropped the graphs from the overview a while back; they've been replaced with a current usage indicator. Detailed charts are in the performance page and are using completely different elements.

Therefore, I'm considering this addressed.
