### ISSUE TITLE
system: strange allignment of [x] in change systime modal dialog

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#13284]
@stefwalter reported it the other day on IRC, seems like a real issue.
![stange-x-allignment](https://user-images.githubusercontent.com/14921356/70757655-b16c5200-1d40-11ea-94b6-8019c1d29d9b.png)

**Comment by stefwalter** [comment]
Thanks. Sorry I Haven't been able to follow up.
