### ISSUE TITLE
Warning about disk not being mounted on reboot

### ISSUE THREAD

**Issue by mnlipp** [cockpit-project/cockpit#13293]
Cockpit version: 208
OS: Fedora 30
Page: Storage
"Suddenly" (I assume the package has been updated) I have warnings on the storage page for my / and /boot file systems: "The filesystem is currently mounted on / but will not be mounted after the next boot." and "The filesystem has no permanent mount point."

This is strange, because I didn't change anything related to storage on the machine's configuration. Nevertheless, I checked /etc/fstab and the required lines are there and everything is perfectly okay.
There's no reason to assume that the file systems won't be mounted on the next reboot.

I love cockpit. But unjustified warnings make it less useful.

**Comment by marusak** [comment]
@mvollmer could you please take a look? There has been some changes lately in storage which maybe could affect this?

**Comment by mvollmer** [comment]
> "Suddenly" (I assume the package has been updated) I have warnings on the storage page for my / and /boot file systems: "The filesystem is currently mounted on / but will not be mounted after the next boot." and "The filesystem has no permanent mount point."

Yes, this happens since #12647, released in 208.

> Nevertheless, I checked /etc/fstab and the required lines are there and everything is perfectly okay. There's no reason to assume that the file systems won't be mounted on the next reboot.

Could you show the relevant lines from `/etc/fstab`?  It seems that UDisks2 is not picking them up correctly for some reason.

> But unjustified warnings make it less useful.

Absolutely.  If we can't make this reliable, we will remove the warnings.

**Comment by mnlipp** [comment]
Here they are:
```
UUID="5d862194-7cd2-1234-a0f8-d7b8b61e7822"	/       ext4    defaults        1 1
UUID="abd15f2d-8a56-41b2-9365-7c9a4a8b2c46"     /boot   ext4    defaults        
```

**Comment by mvollmer** [comment]
> Here they are:

Thanks!  I think UDisks2 chokes on the `"` characters in `UUID="..."`. Can you say where they come from?  I don't think I have ever seen them.

(The systemd fstab generator handles quotes around UUID values and effectively removes them, and thus your boot will work as expected.)

**Comment by mnlipp** [comment]
I don't know where the quotes initially came from. The machine has a long history.

Anyway, removing the quotes removes the warning.

Thanks!
