### ISSUE TITLE
Can't select memory size when creating VM

### ISSUE THREAD

**Issue by mzamot** [cockpit-project/cockpit#13294]
Cockpit version: 208 and 209
OS: Fedora 31
Page: Machines

When creating a new virtual machine on an HPE ProLiant DL325 Gen10 with 140 Gi of RAM, memory slider is 0 out of 0. Can't select any amount of memory.

Steps to reproduce

1. Try to create a virtual machine.
2. Can't select any memory.

![image](https://user-images.githubusercontent.com/7987869/70852183-3ac87500-1e64-11ea-9351-5c42b6d7f284.png)

This doesn't happen on other machines like my laptop or other smaller servers. Not sure if there's an error doing the conversion for the memory units.

**Comment by mzamot** [comment]
In another server, a Supermicro X9DRi-LN4+ with 128 GB of RAM I only get half of the memory on the system:

![image](https://user-images.githubusercontent.com/7987869/70852536-03f45e00-1e68-11ea-91c2-a0f757eff4d7.png)

**Comment by KKoukiou** [comment]
> In another server, a Supermicro X9DRi-LN4+ with 128 GB of RAM I only get half of the memory on the system:
> 
> ![image](https://user-images.githubusercontent.com/7987869/70852538-1373a700-1e68-11ea-8cc0-59b353f20030.png)

Thanks for reporting this. The two above seem seperate issues, but let's debug the both here.
@mzamot Can you please run the following ocmmand and give me the output?
```$ sudo virsh nodememstats```

**Comment by KKoukiou** [comment]
> Cockpit version: 208 and 209
> OS: Fedora 31
> Page: Machines
> 
> When creating a new virtual machine on an HPE ProLiant DL325 Gen10 with 140 Gi of RAM, memory slider is 0 out of 0. Can't select any amount of memory.
> 
> Steps to reproduce
> 
>     1. Try to create a virtual machine.
> 
>     2. Can't select any memory.
> 
> 
> ![image](https://user-images.githubusercontent.com/7987869/70852183-3ac87500-1e64-11ea-9351-5c42b6d7f284.png)
> 
> This doesn't happen on other machines like my laptop or other smaller servers. Not sure if there's an error doing the conversion for the memory units.

Interesting. Can you post here as well the output of `$ sudo virsh nodememstats` command? Thanks!

**Comment by mzamot** [comment]
For the node reporting 0 out of 0:

```
[mzamot@deimos ~]$ sudo virsh nodememstats
total  :            148432668 KiB
free   :            146555212 KiB
buffers:                 2764 KiB
cached :               814240 KiB
```

For the node reporting half the memory:
```
[root@fat ~]# virsh nodememstats
total  :            131991564 KiB
free   :            130877700 KiB
buffers:                 3292 KiB
cached :               428140 KiB
```

**Comment by KKoukiou** [comment]
Looks like libvirt has the correct values. I bet libvirt-dbus API that we use also returns the correct values, but can you try it just to make sure?

$ gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU  --method org.libvirt.Connect.NodeGetMemoryStats 0 0

@mzamot If the DBus API returns the correct numbers,  would you be interested to build cockpit from sources or I can provide you with an RPM to install so that we can add some patch with console logs to debug this?
I am quite confused though that the unit is set to MiB by default when opening the dialog for you according to the second picture. Or did you change it?

**Comment by mzamot** [comment]
I changed it to MiB. Either MiB or GiB it's the same.
The output from gdbus is wrong :-(

```
[root@deimos ~]# gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU --method org.libvirt.Connect.NodeGetMemoryStats 0 0
({'total': uint64 0, 'free': 0},)
```

```
[root@fat ~]# gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU --method org.libvirt.Connect.NodeGetMemoryStats 0 0
({'total': uint64 65933240, 'free': 65311520},)
```

I can build from sources. Do you want me to add anything in particular to the build?

**Comment by mzamot** [comment]
The interesting thing is this:

The node showing 0 in Cockpit:

```
[mzamot@deimos ~]$ gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU --method org.libvirt.Connect.NodeGetMemoryStats 0 0 
({'total': uint64 0, 'free': 0},)
[mzamot@deimos ~]$ gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU --method org.libvirt.Connect.NodeGetMemoryStats 1 0 
({'total': uint64 16329996, 'free': 15121940},)
[mzamot@deimos ~]$ gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU --method org.libvirt.Connect.NodeGetMemoryStats 2 0 
({'total': uint64 66059052, 'free': 65584836},)
[mzamot@deimos ~]$ gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU --method org.libvirt.Connect.NodeGetMemoryStats 3 0 
({'total': uint64 66043620, 'free': 65772900},)
```

The node showing half of the memory:

```
[root@fat ~]# gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU --method org.libvirt.Connect.NodeGetMemoryStats 0 0
({'total': uint64 65933240, 'free': 65327316},)
[root@fat ~]# gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU --method org.libvirt.Connect.NodeGetMemoryStats 1 0
({'total': uint64 66058324, 'free': 65541476},)
```

Seems the memory is grouped among different cells.

**Comment by KKoukiou** [comment]
We need to change the first paramer here, https://github.com/cockpit-project/cockpit/blob/master/pkg/machines/libvirt-dbus.js#L647 to -1, see why [here](https://libvirt.org/html/libvirt-libvirt-host.html#virNodeGetMemoryStatsAllCells)

**Comment by mzamot** [comment]
@KKoukiou I created PR #13300 to fix this issue. Thank you!

**Comment by KKoukiou** [comment]
Fixed by https://github.com/cockpit-project/cockpit/pull/13300/
