### ISSUE TITLE
Cockpit: data:application doesn't work on Firefox

### ISSUE THREAD

**Issue by federicoballarini** [cockpit-project/cockpit#13291]
I'm trying to implement download file on Firefox with data:application link. I have two cases:
- it works on an application installed on NethServer Cockpit (https://github.com/NethServer/nethserver-vpn-ui/pull/18)
- it doesn't work on NethServer Cockpit main module (https://github.com/NethServer/nethserver-cockpit/pull/192)

How can I solve it?

**Comment by martinpitt** [comment]
Sorry for the really late reply! This slipped through the cracks over the holiday season.

This is really vague -- if Firefox does not accept data:application/ downloads, then cockpit can't do much about it. However, we use that (`data:application/x-virt-viewer`) on the Machines page for the external spice/VNC viewer, and it works well with Firefox.

https://github.com/NethServer/nethserver-vpn-ui/pull/18 is merged, and says that it all works now, so I'm closing this. Please yell if it is still an issue!
