### ISSUE TITLE
system: different warning icons for failed service and warning icon

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#13304]
Cockpit version: master
OS: Fedora 31
Page: System Overview

Seems we're using two different warning icons on the Overview page.

![Screenshot from 2019-12-17 11-05-12](https://user-images.githubusercontent.com/209895/70985959-511d3d80-20bd-11ea-8279-1127b247823d.png)

**Comment by andreasn** [comment]
It seems the _Services has failed_ one is the same that's being used in Alerts, but the _Not Registered_ one is what's on the [PF4 icon page](https://www.patternfly.org/v4/design-guidelines/styles/icons)

**Comment by andreasn** [comment]
@jgiardino do you know what's the correct one here?

**Comment by jgiardino** [comment]
I assume that the icons shown for [Alerts](https://www.patternfly.org/v4/documentation/core/components/alert) (i.e. `fa-exclamation-triangle`) are the same icons we should use in similar use cases, like status messages.
