### ISSUE TITLE
SSL certs, Chrome, & iOS13/OSX 10.5.

### ISSUE THREAD

**Issue by CastawayEGR** [cockpit-project/cockpit#13324]
Cockpit version: 195-1.el7
Cockpit OS: RHVH 4.3 
OS: Mac OSX Catalina v10.15.2
Page: Web Interface

It appears due to Apple updating requirements for trusted certs that my cockpit no longer works in Google Chrome (v79.0.3945.88). I get an error stating the the cert was revoked but this is not the case. Safari complains about the SSL cert as well but I am able to load the page by allowing the browser to view the insecure page. 

It looks like the OSX 10.5/iOS 13 update added some stricter requirements of the SSL cert such as a mandatory SAN field, as well as ExtendedKeyUsage requirement, and only accepting ssl certs with validity periods of 825 days or less.
 
[Related Apple Support KB](https://support.apple.com/en-us/HT210176)

Steps to reproduce

1. Install latest version of cockpit available on RHVH.
2. Browse to https://IP:9090 in Google Chrome.
3. Get error message seen below in the screenshot.

![Screen Shot 2019-12-19 at 4 44 13 PM](https://user-images.githubusercontent.com/36353334/71212197-d6038500-227e-11ea-9e03-7860ff7630ef.png)

**Comment by CastawayEGR** [comment]
I guess this is more a Chrome issue, switched to Firefox.

**Comment by cwawak** [comment]
This is still an issue. Switching to firefox is not a fix for everyone.
