### ISSUE TITLE
Controls are disabled inconsistently on the Overview

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#13320]
Cockpit version: 209OS:
Page: Overview

When not being root, the controls on the Overview are correctly disabled, but they look inconsistent:

![image](https://user-images.githubusercontent.com/3228183/71165494-970f0880-2259-11ea-81ee-d44f82206e05.png)

All the blue things should be gray, no?

**Comment by martinpitt** [comment]
Confirmed, these currently use a `disabled` class, but should use the `disabled` attribute. Same direction as PR #13061, but that doesn't change overview. I'll send a PR.

**Comment by martinpitt** [comment]
BTW, ssh "show fingerprints" should stay, that's fine as non-root.

**Comment by martinpitt** [comment]
Ah, we already have a hack for the "edit hostname" button to additionally set the attribute. But the real fix is to adjust `update_privileged()` to set the attribute, not the class, and going through all usages of it to make sure that it still looks right. Possibly we may need some CSS to get  along with the attribute.

**Comment by martinpitt** [comment]
Update: It's not just that -- jQuery really isn't compatible with React. I added some console.logs(), and the ConfigurationCard gets rendered *after* `update_privileged()` gets called, so it overrides the dynamic `disabled` change. Let's just phase out `update_privileged()` and implement that properly with React.

**Comment by martinpitt** [comment]
This also affects the Restart button and kebap.

**Comment by martinpitt** [comment]
I'm fixing this in PR #13328
