### ISSUE TITLE
Overview cards can broke with longer strings on small screens

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#13326]
On not wide enough screens `Configuration` card can break a little. It is much better reproducible in foreign languages, like Czech. It is due to long strings which do not wrap.

![Screen Shot 2019-12-20 at 10 31 50](https://user-images.githubusercontent.com/12330670/71245048-27aa1f00-2314-11ea-8e58-ac77b3695471.png)

**Comment by garrett** [comment]
I think the content is too narrow and we should adjust the size things reflow. (At this width, it should probably be 1 wide instead of 2 wide.)

Currently, language switching isn't working properly for me, so I'll try to get that figured out. While it wouldn't be a blocker, it would be nice to see it in Czech and German.

**Comment by garrett** [comment]
So the size is all wrong, regardless of language. This should be 2 wide at this size, not 3:

![Screenshot_2020-01-07 Overview - Rain](https://user-images.githubusercontent.com/10246/71903835-3cd0db80-3165-11ea-903e-d80a6d59a042.png)

And it's showing the table escaping the boundaries.

It wasn't like this when I left; a change since then is breaking it.

**Comment by garrett** [comment]
The commit which broke things was 2941938dfff4b9231142efdf2fbccee3052d28b6. "Very narrow screens" here is referring to an iPhone SE and similar sized phones, not desktops.

**Comment by marusak** [comment]
> The commit which broke things was 2941938

No, it wasn't. When I revert that commit, it is still broken the same way:
![withoutmyfix](https://user-images.githubusercontent.com/12330670/71909525-81ae3f80-3170-11ea-939f-c69d87bca73c.png)

**Comment by garrett** [comment]
1. The commit is still wrong
2. Optimizing the layout specifically for 1024x768 was an oversight, as nobody typically uses that resolution anymore... _except in VMs, as pointed out_... so I'll work on making it better specifically for the VM use case.

**Comment by marusak** [comment]
> The commit is still wrong

No doubt about that. It was just something, what was working and we needed quick fix.

**Comment by AdamWill** [comment]
@garrett you can't only think about 'resolutions', though. You have to consider window sizes. Not everyone uses a full size browser window. Indeed, the bigger your monitor (and the higher your resolution), the less likely it is that your browser window is full screen.

**Comment by garrett** [comment]
@AdamWill: I understand that. I wasn't talking about window sizes here. Cockpit is designed to work regardless of size. The layout adjusts. The screenshots you see are a bug and I'll fix it.

I was referring to 1024×768 as a resolution that's used in VMs, according to a bugzilla ticket.

Firefox's UI takes up 74 vertical pixels when maximized. GNOME takes up 27 pixels. So we're actually talking about a browser space that's 1024×694 or 1024×667 (depending on whether it's fullscreen with UI or maximized in GNOME). It's even smaller vertically if someone is using GNOME in "Classic" mode with a taskbar, like someone might be doing in a desktop RHEL VM, for example.

The goal isn't to make to just work in that resolution (it _should_, aside from this bug), but to optimize for it as a target.

One of the issues we're hitting here is having the sidebar switcher, which should be merged into the menu (this is planned, but requires some non-obvious semi-tricky changes in Cockpit's codebase). We also have the sidebar fixed to a minimum width (which I plan on changing for smaller desktop sizes now). And I can probably adjust other things regarding the layout to make it all work in a much better way for a typical VM size of 1024×768.

Anyway, I'm back from vacation and plan on trying to fix this ASAP. :wink:

**Comment by garrett** [comment]
Here's a preview of the new Cockpit overview optimized specifically for a 1024×768 desktop display, for VMs (FWIW: it accommodates slightly smaller sizes too, in case there's a GNOME header bar, task list, _and_ browser chrome, hence the image being 694 pixels tall):

![Screen Shot 2020-01-09 at 18 01 20](https://user-images.githubusercontent.com/10246/72088309-30d24e80-330a-11ea-8599-65ad721339a1.png)

The next step is to pull as much of this as I can out to other responsive breakpoints, to consider some of these rules for mobile and narrow desktop browsers too. I wanted to start with the most challenging layout first, then move it around to apply as much of this as we can in other breakpoints instead.

**Comment by AdamWill** [comment]
That looks good to me, thanks.
