### ISSUE TITLE
Reverse Proxy - Forwarded IP

### ISSUE THREAD

**Issue by ApertureDevelopment** [cockpit-project/cockpit#13323]
Cockpit version: 188-1
OS: Debian 10 Buster

Hello,

I am using Cockpit over a apache reverse proxy on our server. To increase security, I wanted to add Fail2Ban to cockpit, but that doesnt work because the IP that cockpit gives pam is .. well:
```
Dec 19 17:44:21 deb10-gs-fsn cockpit-session: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=127.0.0.1  user=<REMOVED>
```

rhost gets set to 127.0.0.1 by cockpit because of the apache reverse proxy, but there are ways to still get the public IP or a user trough the reverse proxy using ``RemoteIPHeader X-Forwarded-For``
So for security I am suggesting to implement the RemoteIpHeader in cockpit. I think this is a security issue that can become really bad real fast, because securing our SSH login is useless when they can bruteforce trough cockpit.

Steps to reproduce

1. Install cockpit
2. Setup a Apache reverse Proxy ( with this: https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-Apache-with-LetsEncrypt )
3. Look at the auth.log on your system

**Comment by leomoty** [comment]
Related: https://github.com/cockpit-project/cockpit/pull/13250

**Comment by ApertureDevelopment** [comment]
What I understand from that is that you will remove the rhost feature entirely, that prevents me from securing cockpit at all. Cockpit can be used as a huge security leak, as you can bruteforce trough it without any prevention against. It doesnt matter when authentication method you used as setting in your ssh server ( publickey as example ) if people can continue to enter username and password via cockpit. Shouldn't there be any security improovments implemented? Allowing the RemoteIPHeader to be used as rhost would already allow people to at least implement Fail2Ban

**Comment by ApertureDevelopment** [comment]
Well, I found a way to implement Fail2Ban
```
[cockpit-apache-auth]
enabled = true
port     = http,https
logpath  = <access_logfile>
```
and ``cockpit-apache-auth.conf``
```
# Fail2Ban Cockpit Apache Reverse Proxy
# Finds unauthorized login attempts and bans the user from using the website

[INCLUDES]

before = apache-common.conf

[Definition]

failregex = ^<HOST> .+\" 401 \d+ .*$

ignoreregex =

[Init]

# Author: Aperture Development
```

Already tested and works, so I dont need rhost anymore, thanks

**Comment by leomoty** [comment]
@ApertureDevelopment I am not actually a cockpit developer, just got you some context. Glad that it worked out for you :)

**Comment by git-Hmmm** [comment]
I am using Cloudflare Tunnels and having the same issue.

**Comment by git-Hmmm** [comment]
@leomoty Can you give me detailed steps please? :sweat_smile:
Do i need to install nginx web server to fix this issue?

**Comment by martinpitt** [comment]
Commit ad7b2def408bbe4a00fd82ec5399db79b446c91e (Cockpit >= 231) reintroduced a working `PAM_RHOST`, so this should work now.
