### ISSUE TITLE
Cockpit unable to connect to libvirtd

### ISSUE THREAD

**Issue by alexanderturner** [cockpit-project/cockpit#13339]
Cockpit version: 189
OS: Ubuntu 19.04

I installed Cockpit and `cockpit-machines` along with libvirt and I can create and view storage pools with virsh however Cockpit errors with:

<img width="545" alt="Screen Shot 2019-12-28 at 1 56 49 pm" src="https://user-images.githubusercontent.com/2374344/71538120-fbc51400-2979-11ea-923c-b6a014d31a81.png">

From virsh:

```
server@server:~$ virsh -c 'qemu:///system' pool-info kvm
Name:           kvm
UUID:           f9bdfc8d-c051-4b66-8832-ee9ee2c17987
State:          running
Persistent:     yes
Autostart:      yes
Capacity:       2.15 TiB
Allocation:     30.76 GiB
Available:      2.12 TiB

server@server:~$ virsh -c 'qemu:///system' pool-list --all
 Name      State    Autostart
-------------------------------
 default   active   yes
 kvm       active   yes
```

I'm logged into Cockpit as root with `Reuse my password for privileged tasks` set.
```
root@server:/etc/libvirt# ls -l /var/run/libvirt/libvirt-sock
srwxrwx--- 1 root libvirt 0 Dec 28 02:45 /var/run/libvirt/libvirt-sock
root@server:/etc/libvirt#
```

**Comment by alexanderturner** [comment]
As per:

https://www.reddit.com/r/linuxquestions/comments/c7hcfe/whack_issues_with_cockpit_and_ubuntu_server_1904/

```
I ended up editing /etc/libvirt/libvirtd.conf

Changed

unix_sock_rw_perms = "0770"

TO

unix_sock_rw_perms = "0777"

Then: systemctl restart libvirtd
```

**Comment by martinpitt** [comment]
This has been known for a long time: https://bugs.launchpad.net/ubuntu/+source/libvirt-dbus/+bug/1802005
