### ISSUE TITLE
testCreateTimer (check_services.TestServices) started to always fail

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#13346]
```
Traceback (most recent call last):
  File "test/verify/check-services", line 411, in testCreateTimer
    wait_systemctl_timer("Wed 2020-01-01 16:00")
  File "test/verify/check-services", line 349, in wait_systemctl_timer
    m.execute("cmd='systemctl list-timers'; until $cmd | grep -m 1 '%s'; do sleep 1; done" % time)
  File "/build/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 315, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timeout while waiting for systemctl list-timers
```

Happens on most of OSes, examples: (probably happens on other OSes as well)
[debian testing](https://209.132.184.41:8493/logs/pull-13345-20200102-110404-3d731b66-cockpit-project-cockpit--debian-testing/log.html#198-2)
[fedora-coreos](https://209.132.184.41:8493/logs/pull-13345-20200102-110404-3d731b66-cockpit-project-cockpit--fedora-coreos/log.html#198-2)
[ubuntu-stable](https://209.132.184.41:8493/logs/pull-13345-20200102-110404-3d731b66-cockpit-project-cockpit--ubuntu-stable/log.html)
[fedora-31](https://209.132.184.41:8493/logs/pull-13344-20200102-073232-f6e5bc4e-cockpit-project-cockpit--fedora-31/log.html#198-2)

**Comment by martinpitt** [comment]
It's not a flake, it fails persistently. Most probably because that date has just passed, so it won't ever happen any more as "next" timer. :-)
