### ISSUE TITLE
WebSocket connection times out behind load balancer

### ISSUE THREAD

**Issue by dmesser** [cockpit-project/cockpit#13355]
Cockpit version: 185.1
OS: CentOS 8

A CentOS 8 instance on GCP Compute Engine runs Cockpit. It sits behind a HTTPS Load Balancer with a managed SSL certificate. GCP Load Balancers have [support for WebSocket connections](https://cloud.google.com/load-balancing/docs/https/#websocket_proxy_support) but following a successful login on Cockpit my session disconnects after approx. 30 seconds. This seems in line with the default timeout on the load balancer side to send/receive HTTP `Upgrade` commands.

![cockpit](https://user-images.githubusercontent.com/12664117/71770651-5ee11880-2f2f-11ea-9308-0bb4aa3bb2c7.png)

`journalctl -u cockpit`

```
Jan 04 18:56:03 meter systemd[1]: Starting Cockpit Web Service...
Jan 04 18:56:03 meter systemd[1]: Started Cockpit Web Service.
Jan 04 18:56:03 meter cockpit-ws[22273]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Jan 04 18:56:28 meter cockpit-session[22280]: pam_ssh_add: Failed adding some keys
Jan 04 18:56:28 meter cockpit-session[22280]: pam_unix(cockpit:session): session opened for user dmesser by (uid=0)
Jan 04 18:56:28 meter cockpit-ws[22273]: logged in user session
Jan 04 18:56:29 meter cockpit-ws[22273]: New connection to session from <redacted>
Jan 04 18:56:59 meter cockpit-ws[22273]: WebSocket from <redacted> for session closed
Jan 04 18:57:14 meter cockpit-ws[22273]: session timed out
```

`cockpit.conf`

```
[WebService]
Origins = https://cockpit.<redacted>.com
ProtocolHeader = X-Forwarded-Proto
```

Steps to reproduce

1. Install Cockpit on CentOS behind a GCP HTTPS Load Baalancer
2. Create managed SSL certificate (DV) with correct domain
3. Log in to Cockpit
4. Wait approx. 30 secs
5. Get disconnected

**Comment by martinpitt** [comment]
Sorry, this is very stale, as it's not easy to reproduce. Do you still have that problem with current versions, or are you even interested in it still?

**Comment by DominikBasnerSotec** [comment]
Have you tried this? https://ladysign.medium.com/gke-websockets-timeouts-in-a-chat-voice-web-server-running-in-production-105c0c9e25b1
