### ISSUE TITLE
Performance is very slow 

### ISSUE THREAD

**Issue by soufiane-bouchaara** [cockpit-project/cockpit#13356]
Cockpit version: 188
OS: Debian GNU/Linux 10 (buster)
```
uname -a
Linux cockpit-master 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
```

Using ansible we are deploying cockpit in +250 instances, and we have a cockpit master instance that control all the instances,

We tried first with 5 instances, it worked very well, but when we deployed all the 250 instances the performance went very very bad, I wasn't able to close the tab  (blank screen and it crashes).

Note that all 250 instances are well setup and the master key was authorized and the instances were added to known_hosts and there's no timeout in ssh connections.

Is there any possibility to tweak the performance ?

Here's a screenshot of memory usage at that time :
![image](https://user-images.githubusercontent.com/2540416/71779895-a1106580-2fd4-11ea-96d3-4e39d01ae4a2.png)

Screenshot during the crash
![image](https://user-images.githubusercontent.com/2540416/71780031-d8801180-2fd6-11ea-8176-e94cceccf7f8.png)

**Comment by martinpitt** [comment]
> Using ansible we are deploying cockpit in +250 instances, and we have a cockpit master instance that control all the instances

Right, this is absolutely not supported. Cockpit's Dashboard has a limit of 20 machines. That will already be sluggish, usually we recommend only a handful. Of course with a direct remote connection from the login page there is no limit, as there will always just be one ssh connection at a time.

If you need to manage so many machines, please use an appropriate tool for that, like Foreman/Satellite. Latest Foreman now even has a "Web Console" button where you can drill down into an individual server's Cockpit on demand.

How did you even manage to connect to that many machines in parallel? Did you write the machines.d json files manually?
