### ISSUE TITLE
Maximum amount of servers

### ISSUE THREAD

**Issue by Ekultek** [cockpit-project/cockpit#13361]
This isn’t really an issue but a question, is there a maximum amount of servers that cockpit can connect to? For example say I have 200+ Linux servers would that cause any latency issues or unforeseen problems?

**Comment by martinpitt** [comment]
Cockpit's Dashboard has a limit of 20 machines. That will already be sluggish, usually we recommend only a handful. Of course with a direct remote connection from the login page there is no limit, as there will always just be one ssh connection at a time.

If you need to manage so many machines, please use an appropriate tool for that, like Foreman/Satellite. Latest Foreman now even has a "Web Console" button where you can drill down into an individual server's Cockpit on deman.
