### ISSUE TITLE
Feature Request: DHCP Server Configuration

### ISSUE THREAD

**Issue by necouchman** [cockpit-project/cockpit#13363]
Page: Network

There are so few good GUI-based DHCP server configuration tools out there, that having this functionality in Cockpit would be quite useful.  I'm thinking primarily ISC DHCP and ISC KEA.

**Comment by martinpitt** [comment]
I don't think we'll ever do this in cockpit project itself. This would be an excellent candidate for a [separate project](https://cockpit-project.org/blog/cockpit-starter-kit.html)

**Comment by martinpitt** [comment]
See previous comment.
