### ISSUE TITLE
Invalid File Permission Error When Enabling SSH Key In Authentication Page

### ISSUE THREAD

**Issue by elindydotcom** [cockpit-project/cockpit#13360]
Cockpit version: 164
OS: Ubuntu 18.04.3 LTS
Page: Authentication

When attempting to enable a key on the Authentication page an invalid file permissions error is shown and the key is not enabled.
<!---Please help us out by explaining how to reproduce it.
1. I added a key pair to the root/.ssh folder. The private key does NOT have a password.
2. Cockpit recognized the presence of the keys and it shows up under the Authentication screen.
3. However, enabling it results in the Invalid File Permissions Error.

Link to journalctl output: https://www.screencast.com/t/qyVLzkPyR

The filenames for the keypair are "myname" and "myname.pub" if that makes a difference.

**Comment by elindydotcom** [comment]
ummm...so I wrote a bunch of stuff describing the issue and it all disappeared when it was posted.  I'll try again...

Steps to reproduce:
1. I added a keypair to the /root/.ssh folder.
2. Cockpit recognized it and it showed up under the Authentication screen.
3. Attempting to enable it resulted in a "Invalid File Permission" error in red.

The filenames I used were "myname" and "myname.pub".  

Consistent in Chrome, Firefox and Edge.

Permissions on the keypair files are 644 (owner 0, group 0).

Here is the journal output:  https://www.screencast.com/t/zqtRvbOx9

**Comment by Gundersanne** [comment]
Private keys are supposed to be 600. 644 makes the private key readable to other users. The public key is allowed to be 644 however.

So `chmod 600 /root/.ssh/myname` should fix it :)

Closing this, feel free to reopen if the issue persists.
