### ISSUE TITLE
Feature Request: DRBD Plugin

### ISSUE THREAD

**Issue by necouchman** [cockpit-project/cockpit#13362]
Page: Storage

Add a plugin that supports configuration of the DRBD framework.  May be more involved than just DRBD configuration, as a lot of times this goes along with clvmd, which then brings in Pacemaker, etc.

**Comment by martinpitt** [comment]
This is definitively something that we won't do in the cockpit project itself -- it should be developed [as a separate project](https://cockpit-project.org/blog/cockpit-starter-kit.html), by someone with the necessary domain knowledge. Thus closing this for the cockpit project. Thanks!
