### ISSUE TITLE
Test testOverview (check_metrics.TestMetrics) is flaky

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#13370]
It is rather a new test, that is not always passing. It needs to be robustify.

```
Traceback (most recent call last):
  File "test/verify/check-metrics", line 228, in testOverview
    self.assertLessEqual(last_usage, initial_usage)
AssertionError: 40 not less than or equal to 30
```

Example on ubuntu-1804: https://logs-https-cockpit.apps.ci.centos.org/logs/pull-13368-20200108-090909-6bfb5ed2-cockpit-project-cockpit--ubuntu-1804/log.html#77-2

**Comment by martinpitt** [comment]
I sent #13385 to fix this.
