### ISSUE TITLE
Host overview displaying Health card since 209 even when no packagekit support is available

### ISSUE THREAD

**Issue by tgurr** [cockpit-project/cockpit#13393]
Cockpit version: 209/210
OS: Exherbo Linux
Page: system (Host overview)

Since our package manager on Exherbo Linux is not supported by PackageKit we do not install / remove the packagekit and apps features via:

```
edo rm -rf "${IMAGE}"/usr/share/cockpit/apps
edo rm -rf "${IMAGE}"/usr/share/cockpit/packagekit
```
This worked well for a really long time but now since cockpit 209 with the new overview/system screen it shows a new `Health` card with a running `Checking for package updates...` in it which doesn't make sense for us so it would be nice to have this card disabled as well when packagekit support is not available.

![cockpit_dashboard_updates](https://user-images.githubusercontent.com/414984/72337033-1e696380-36c2-11ea-9fa0-ee049c39176e.png)

**Comment by KKoukiou** [comment]
This was fixed with 968ffde2c6519c201fa4a4996c14198a3a14dbd9 which will be included in 211.
