### ISSUE TITLE
storage: more clear hirearchy for RAID devices

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1340]
All items in a RAID device are currently stacked on top of each other with little distinction of Disks and Content.

Current layout of RAID:
![screenshot from 2014-10-14 12 34 06](https://cloud.githubusercontent.com/assets/209895/4627685/a2677f78-538d-11e4-8ab0-c0d02e3a0759.png)

It would be good to relayout this a bit to make it clearer.

**Comment by mvollmer** [comment]
I think this has been all done.
