### ISSUE TITLE
Add AppStream data to cockpit-docker

### ISSUE THREAD

**Issue by j-eissler** [cockpit-project/cockpit#13416]
Cockpit version: 202.1
OS: Ubuntu 19.10
Page: Applications

When installing the plugin 'cockpit-docker' the plugin doesn't show up under the 'Applications' tab in the webinterface. Even after clicking the refresh button the plugin does NOT appear in the list.
However the plugin DOES show up 'Docker Containers' in the upper list.

Steps to reproduce:
1. apt install cockpit-docker docker-compose
2. Go to Webinterface 'Applications'
3. Refresh the listed applications

I hope this is the right place to post this issue. If not please tell me, I am new to GitHub.

**Comment by martinpitt** [comment]
Indeed cockpit-docker doesn't currently ship AppStream data.
