### ISSUE TITLE
storage: More clear hirearchy for Volume Groups

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1341]
Similar to issue #1340 

All items in a Volume Groups are currently stacked on top of each other with little distinction of the different parts of the hierarchy.

Screenshot:
![screenshot from 2014-10-14 12 43 09](https://cloud.githubusercontent.com/assets/209895/4627782/e5ac7bc0-538e-11e4-8e70-7cbcd1f46642.png)

**Comment by mulkieran** [comment]
I think this is better, but what about:

1. Putting a [+] in the "Logical Volumes" header (for adding a new logical volume). That fits the pattern on the overview screen better, and makes more sense now that the new logical volume logic is unified. It's also easier to see. Or maybe just an "Add" like for physical volumes. Semantically, I don't feel like there's a real distinction between "Add" and "+", so maybe everything should be '+'s.
2. For each physical volume, put a bar like for filesystems on overview page showing used and free (for a better visual).
3. Put summary physical volume info and summary logical volume information in overview panel. Summary physical is total used and free...of which half is already there. Summary logical might not be anything.

?

**Comment by mvollmer** [comment]
The layout changes have been done.
