### ISSUE TITLE
Fresh Installation - Unable to login 

### ISSUE THREAD

**Issue by AnonyBart** [cockpit-project/cockpit#13413]
Cockpit version: 202.1-1
OS: Ubuntu 19.10
Page: Log-in

Fresh installation of cockpit using "apt install cockpit", navigate to MYIP:9090, logging with user root and password, "Connection Failed"

journalctl -u cockpit
https://pastebin.com/Mb3UEYrt

journalctl --since -5m
https://pastebin.com/Nrigbch1

Steps to reproduce

1. Ubuntu 19.10
2. apt install cockpit
3. Log-In with user root

https://ibb.co/DfC61Kw

**Comment by AnonyBart** [comment]
Up

**Comment by martinpitt** [comment]
The only useful error message in the logs is that the TLS connection was interrupted. Your screenshot and description suggest that you still see the login page itself, so at first sight it's not related to cockpit-tls.

 - Which browser do you use?
 - Does logging in a normal user work?
 - Can you please try without TLS, i. e. http://localhost:9090 ? Does that work?

**Comment by AnonyBart** [comment]
> The only useful error message in the logs is that the TLS connection was interrupted. Your screenshot and description suggest that you still see the login page itself, so at first sight it's not related to cockpit-tls.
> 
> * Which browser do you use?
> * Does logging in a normal user work?
> * Can you please try without TLS, i. e. http://localhost:9090 ? Does that work?

- Chrome Versione 79.0.3945.130 
- No it doesnt, i just tried creating a test user and it doesnt log in; same error.
- I cant try without TLS because it keeps redirecting to HTTPS.

**Comment by AnonyBart** [comment]
I think the error is related to "**pam_ssh_add: Failed adding some keys**"

```
gen 17 11:00:27 ubuntu remotectl[12362]: Generating temporary certificate using: openssl req -x509 -days 36500 -newkey rsa:2048 -k
gen 17 11:00:28 ubuntu systemd[1]: Started Cockpit Web Service.
gen 17 11:00:28 ubuntu cockpit-tls[12377]: cockpit-tls: TLS handshake failed: The TLS connection was non-properly terminated.
gen 17 11:00:28 ubuntu cockpit-tls[12377]: cockpit-tls: reading from client fd 9 TLS connection failed: The TLS connection was non
gen 17 11:00:28 ubuntu cockpit-tls[12377]: cockpit-tls: reading from client fd 9 TLS connection failed: The TLS connection was non
gen 17 11:00:28 ubuntu cockpit-tls[12377]: cockpit-tls: reading from client fd 11 TLS connection failed: The TLS connection was no
gen 17 11:00:32 ubuntu cockpit-tls[12377]: cockpit-tls: reading from client fd 10 TLS connection failed: The TLS connection was no
gen 17 11:00:32 ubuntu cockpit-tls[12377]: cockpit-tls: reading from client fd 9 TLS connection failed: The TLS connection was non
gen 17 11:00:32 ubuntu cockpit-tls[12377]: cockpit-tls: reading from client fd 13 TLS connection failed: The TLS connection was no
gen 17 11:00:32 ubuntu cockpit-tls[12377]: cockpit-tls: reading from client fd 11 TLS connection failed: The TLS connection was no
gen 17 11:00:32 ubuntu cockpit-tls[12377]: cockpit-tls: reading from client fd 14 TLS connection failed: The TLS connection was no
gen 17 11:00:32 ubuntu cockpit-tls[12377]: cockpit-tls: reading from client fd 16 TLS connection failed: The TLS connection was no
gen 17 11:00:43 ubuntu cockpit-session[12390]: pam_ssh_add: Failed adding some keys
gen 17 11:00:43 ubuntu cockpit-session[12390]: pam_unix(cockpit:session): session opened for user root by (uid=0)
gen 17 11:00:43 ubuntu cockpit-ws[12381]: logged in user session
gen 17 11:00:43 ubuntu cockpit-tls[12377]: cockpit-tls: reading from client fd 12 TLS connection failed: The TLS connection was no
gen 17 11:00:43 ubuntu cockpit-tls[12377]: cockpit-tls: reading from client fd 7 TLS connection failed: The TLS connection was non
gen 17 11:00:43 ubuntu cockpit-tls[12377]: cockpit-tls: reading from client fd 15 TLS connection failed: The TLS connection was no
gen 17 11:00:44 ubuntu cockpit-tls[12377]: cockpit-tls: reading from client fd 17 TLS connection failed: The TLS connection was no
```

**Comment by martinpitt** [comment]
> pam_ssh_add: Failed adding some keys

That's unrelated, and expected if you don't have any SSH keys that get unlocked with your login password (which is the case for almost all users).

> I cant try without TLS because it keeps redirecting to HTTPS.

HSTS perhaps.. Try in a private mode window? It won't redirect by default for "localhost".

**Comment by AnonyBart** [comment]
> > pam_ssh_add: Failed adding some keys
> 
> That's unrelated, and expected if you don't have any SSH keys that get unlocked with your login password (which is the case for almost all users).
> 
> > I cant try without TLS because it keeps redirecting to HTTPS.
> 
> HSTS perhaps.. Try in a private mode window? It won't redirect by default for "localhost".

It's not in localhost, i am using the VPS IP to connect.
Tried also in private mode without results, still redirecting to https.

**Comment by AnonyBart** [comment]
up if possible help me

**Comment by JoshuaMulliken** [comment]
I am having the same issue on ubuntu 20.04.1 LTS

**Comment by marktoddgea** [comment]
I am having the same issue

**Comment by JoshuaMulliken** [comment]
It turned out to be a Safari issue for me... Chrome works

**Comment by j-norwood-young** [comment]
Just a note (since searching for "cockpit connection failed" brought me here): If you're accessing Cockpit through a reverse proxy and get this error, see https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-nginx

**Comment by machsix** [comment]
Same issue here. I’m running cockpit on Archlinux. The connection failure happens on an iphone with safari.

**Comment by VhaTer** [comment]
hello , 
same here , 
brave Version 1.18.70 Chromium: 87.0.4280.101 (Build officiel) (x86_64)
work on prive windows not on normal one, 

chrome Version 87.0.4280.88 (Build officiel) (x86_64) same as brave Work on Private Window not on normal one .
Version 
![image](https://user-images.githubusercontent.com/25908066/102831649-9d940b00-43ec-11eb-9c0c-68bfdb696b69.png)

safari look working on https (Version 14.0 (15610.1.28.1.9, 15610) )
![image](https://user-images.githubusercontent.com/25908066/102831836-07141980-43ed-11eb-94d4-0141a6af0718.png)

**Comment by francescocambi** [comment]
Same issue here on Ubuntu 20.10

**Comment by TracingChange** [comment]
I’m assuming this is still an issue for the above users. Installed fresh on Ubuntu 20.04 yesterday. Tried Safari and Chrome on iPhone and Safari, Chrome and Edge on Mac, all with both private mode and normal mode. Nothing works. It always forwards to https and I can’t try localhost as there is no GUI on the server it’s installed on.

**Comment by 88nightrider** [comment]
Same issue.
Fresh install of Ubuntu Server 20.04.2 LTS today.
Fresh install of Cockpit today.

Have tried both Chrome and Edge, with or without "privacy mode" enabled.

![Putty login window](https://user-images.githubusercontent.com/81973510/113583614-25afc080-962a-11eb-9217-9a96b814bcd2.png)
![Cockpit login](https://user-images.githubusercontent.com/81973510/113583527-09ac1f00-962a-11eb-8e7f-78d9a7ba24fb.png)
![Connection failed](https://user-images.githubusercontent.com/81973510/113583575-1597e100-962a-11eb-9b3b-b3e2bb7f3800.png)
![Cockpit log](https://user-images.githubusercontent.com/81973510/113583596-1df01c00-962a-11eb-95db-6bb337b4e0e1.png)

**Comment by pretsell** [comment]
Having the same struggles tonight.
In stock HTTPS redirect mode no joy via desktop/incognito Chrome or Edge. But did work on Chrome on phone, which was interesting.
I am now in on desktop Chrome once AllowUnencrypted=true added to cockpit.conf.
Don't want to leave it like that, but just cba to setup reverse proxy >.<

**Comment by nhstar** [comment]
As ridiculous as it sounds in 2021, I removed my cookies and all was back to working as normal.

If you're able to login in a different browser and/or in private/incognito mode, try clearing the cookies for your cockpit server.  It worked for me.

**Comment by katerkoff** [comment]
Same issue here.

**Comment by martinpitt** [comment]
There were a lot of "me too"s here, but I'm afraid these are not actionable. So far everything shown here is either due to stale browser cookies (clear data/cache or try in a private window); or using Safari, which has a long-known bug, see https://cockpit-project.org/running/safari.html how to work around it.

If you still cant' log in after that, please file new (and separate) issues. Thanks!

**Comment by jir777** [comment]
Solved the issue with a new self-signed cert.

**Comment by colorwebdesigner** [comment]
I have the same problem. After installing `FreedomBox` on a fresh VDS with `Debian 11` , I was unable to login `Cockpit` via the web interface and the system recommended me to watch the error log. I saw the same things there: 

- `cockpit-session: pam_ssh_add: Failed adding some keys`
- `cockpit-ws: received request from bad Origin: https://xx.xx.xx.xx`
- `cockpit-ws: Received invalid handshake request from the client`

So you can broke your mind trying to find out what is going wrong with handshakes, certificates and so on. BUT If you log in to your `FreedomBox`, go to `system` -> `cockpit` settings and look at the bootom of the page you will see message:

> Cockpit will only work when accessed using the following URLs:
> - `https://server_name.local`
> - `https://long_string_for_tor_domain.onion`
> - `https://vds.provider.net` <-- THIS IS WRONG

So сockpit **will not work** if you are trying to access using IP address. Check the URL you are trying to acces to Cockpit. 
In my case the problem was with VDS static url. Cockpit identified and recorded my address everywhere in configs as: `vds.myprovider.net`, but the real address was `static.xx.xx.xx.xx.ip.myprovider.net`.

When I tried to enter the `cockpit` using the real address, everything worked.

**Comment by BANG88** [comment]
> Well, if you are using Debian (maybe not only there) and have a freshly installed system with no users other than root, take a look at `/etc/cockpit/disallowed-users`. By default, `root` is listed there and is therefore not allowed to log in. If you change this, you should think carefully about who can access your machine, because the default setting is there for a reason.

This should list in the docs after installation.

**Comment by mvandemar** [comment]
> > Well, if you are using Debian (maybe not only there) and have a freshly installed system with no users other than root, take a look at `/etc/cockpit/disallowed-users`. By default, `root` is listed there and is therefore not allowed to log in. If you change this, you should think carefully about who can access your machine, because the default setting is there for a reason.
> 
> This should list in the docs after installation.

This **absolutely** should be listed in the docs after installation. The only place this is mentioned is under "openSUSE Tumbleweed and Leap", #4:

Optionally allow root access (disabled by default)
$EDITOR /etc/cockpit/disallowed-users

None of the other os's say anything about that.
