### ISSUE TITLE
Hotspot feature

### ISSUE THREAD

**Issue by shemgp** [cockpit-project/cockpit#13418]
Page: Network 

I want to use Cockpit as a web UI for my router. Mainly for enabling the machine to be a hotspot for 1 or more wireless interfaces. Meaning, setting an AP mode with ESSID with a wpa2 password. (I didn't want to use OpenWrt luci since I want a full blown Linux, eg. Ubuntu, as the router so I can use more apps).

I was thinking, since NetworkManager is being used in Cockpit, and in GNOME NetworkManager has a hotspot feature, it would be nice if Cockpit use nm to have that feature too.

Right now, if I try to enable an inactive wireless interface, Cockpit, says: 
```
Unexpected Error

A 'wireless' setting is required if no AP path was given.
```

I guess it would need some design then implementation.  I might be able to help with the implementation if it's not that difficult.

Thank you for considering this feature.

**Comment by cyberorg** [comment]
Here is a very rough module https://github.com/cyberorg/apsetup-cockpit

**Comment by marusak** [comment]
> Here is a very rough module https://github.com/cyberorg/apsetup-cockpit

Love it!

We are always very happy when we see that people create own plugins. That was the main idea and goal of cockpit - to provide platform and tooling so users can come and create their own plugins. This plugin is proof of that.
While one day this might be integrated directly into networking page, it is not priority and we won't drive it any time soon. There were some experiments with having wifi setting on this page, but it always crumbled. So I'll close this as there is no need to track this actively. Of course, external contributions are welcomed and even more welcomed are external plugins :)
