### ISSUE TITLE
Networking page shows networkmanager is not running

### ISSUE THREAD

**Issue by PedroJG** [cockpit-project/cockpit#13415]
I'm using cockpit on an embedded system, which probably gives not the best performance in the world.
Right after booting up and accessing Cockpit's web interface from an external computer, in the networking tab I get an error saying that networkmanager is not running for the first 10-15~ seconds of the page open.
It just goes away on its own after around 15s, but I'm absolutely sure that it's running when I access the page. In fact, in services it shows Networkmanager up and running.
Could this be a timeout issue regarding performance of my system?

I'm using Cockpit 210. Could you point me in the direction to solve this? Thank you beforehand

**Comment by martinpitt** [comment]
One of the page's first actions is to query NetworkManager, with the moral equivalent of

    busctl introspect org.freedesktop.NetworkManager /org/freedesktop/NetworkManager

How long does that take on your system? You can run it like this:

    time busctl introspect org.freedesktop.NetworkManager /org/freedesktop/NetworkManager |cat

but I'm not actually interested in a precise measurement, but whether it takes a split second or ~ 10s.

Is the page still slow when you reload it, or does maybe the *first* loading of the page trigger NM to start up?

**Comment by PedroJG** [comment]
It takes 0.4s, so it's pretty much instant.
When I reload the error is still showing, and the graphs do not start plotting until the error goes away. This is what I'm getting:
![image](https://user-images.githubusercontent.com/50325076/72814522-76294100-3c65-11ea-93b6-f0cd895dc2b7.png)

As I said, it goes away after like 15s, but it's pretty annoying to have it happen every time I force reload the page or reboot the system.
Thank you for your time!

**Comment by KKoukiou** [comment]
The NetworkManager page was heavily refactored in release 237. If you manage to get this issue with this release as well, then please reopen, and we can help you to debug this further.
