### ISSUE TITLE
cockpit.socket: Failed to listen on sockets: Input/output error

### ISSUE THREAD

**Issue by gerroon** [cockpit-project/cockpit#13419]
Cockpit version: xxx
OS:
Debian Testing

Cockpit refuses to start. I changed the default port, reloaded systemd and the web page is still notn accessible. I am not sure if it is respecting the port setting or not, in either case I Cokpit is not accessible.

Please help us out by explaining how to reproduce it.
I am not sure how to reproduce this. I did a clean install.

Relevant parts of the system log are also useful:
```
an 19 19:46:27 PC systemd[1]: Failed to listen on Cockpit Web Service Socket.
Jan 19 19:46:41 PC systemd[1]: cockpit.socket: Failed to receive listening socket ([::]:9090): Input/output error
Jan 19 19:46:41 PC systemd[1]: cockpit.socket: Failed to listen on sockets: Input/output error
Jan 19 19:46:41 PC systemd[1]: Starting Cockpit Web Service Socket.
Jan 19 19:46:41 PC systemd[1]: cockpit.socket: Failed with result 'resources'.
Jan 19 19:46:41 PC systemd[1]: Failed to listen on Cockpit Web Service Socket.
Jan 19 19:46:44 PC systemd[1]: cockpit.socket: Failed to receive listening socket ([::]:9090): Input/output error
Jan 19 19:46:44 PC systemd[1]: cockpit.socket: Failed to listen on sockets: Input/output error
Jan 19 19:46:45 PC systemd[1]: Starting Cockpit Web Service Socket.
Jan 19 19:46:45 PC systemd[1]: cockpit.socket: Failed with result 'resources'.
Jan 19 19:46:45 PC systemd[1]: Failed to listen on Cockpit Web Service Socket.
Jan 19 19:48:04 PC systemd[1]: Starting Cockpit Web Service Socket.
Jan 19 19:48:04 PC systemd[1]: Listening on Cockpit Web Service Socket.
Jan 19 19:48:17 PC systemd[1]: cockpit.socket: Failed to queue service startup job (Maybe the service file is missing or not a non-template unit?): Unit -.mount is >
Jan 19 19:48:17 PC systemd[1]: cockpit.socket: Failed with result 'resources'.
Jan 19 19:51:42 PC systemd[1]: Starting Cockpit Web Service Socket.
Jan 19 19:51:42 PC systemd[1]: Listening on Cockpit Web Service Socket.

```

`cat ./systemd/system/cockpit.socket.d/listen.conf`
                                                                                       
```
[Socket]
ListenStream=
ListenStream=9797
```

**Comment by martinpitt** [comment]
That's a failure already on the systemd side, aside from the actual .socket unit, cockpit code isn't even involved at that time yet. Needless to say, this doesn't affect debian testing in general, it's some bug that is specific to your system. Do you happen to have some non-default security system in place? AppArmor, SELinux, some firewall, non-standard kernel, seccomp, EBPF filters and such?

**Comment by gerroon** [comment]
Hi

That is interesting. I am using Debian Bullseye (5.4.0-2-amd64 #1 SMP Debian 5.4.8-1)

I do not have an active firewall, and iptables is pretty much empty.

**Comment by hafezieh** [comment]
i had a conflict with prometheus port and cockpit port (both 9090) , 
so i changed my cockpit default port from 9090 
" where the settings placed in /usr/lib/systemd/system/cockpit.socket and /usr/share/cockpit/motd/update-motd " to 9876 
after that by running `systemctl start cockpit`  i had another issue that i fixed that  by : 
`setsebool -P nis_enabled 1` 
and thats worked for me !

**Comment by martinpitt** [comment]
No answer from original reporter in half a year, and indeed this is most likely a port conflict. Please see https://cockpit-project.org/guide/latest/listen.html for how to change cockpit's port.
