### ISSUE TITLE
Cockpit.conf: How to bypass the login screen + How to define the default language

### ISSUE THREAD

**Issue by echo-five** [cockpit-project/cockpit#13445]
Hi,

I use Cockpit in the scope of a Vagrant local environment (for local dev. in a laptop usage only).
So the installation of Cockpit is fully scripted and the security is not important because the tool is not used in staging or production servers.

There is an option to bypass the login screen ?
Like in PHPMyAdmin, you can provide the credential in a config file.
I want to get access immediately... It's boring to fill root/root ...

There is an option to set the default language ?
My Debian 10 and my Firefox browser are in english but I see the login screen in french...
How can I define the default language ?

Thank you in advance.

M.

**Comment by KKoukiou** [comment]
@echo-five Cockpit will use the most recently set language, so if you set French in your previous session you will get French. If you switch to English it should persist to the next session. I don't see the reason to have this option in the configuration file to be honest, the current behavior seems quite flexible to me.

Regarding the passwordless login, there is not an option right now, but I am sceptical about that as well. If you think having a password for your root user doesn't make sense you can always remove it ( sudo passwd -d root) and then you will be able to login without typing the password field.

But I would be against a feature where one could define in the configuration file a default user to use as cockpit user. (and setting the password there) So I think the login prompt should stay always there.

@marusak do you want to give your feedback as well, I don't want to close the issue as 'won't do' just from my judgement.

**Comment by marusak** [comment]
> There is an option to bypass the login screen ?

As @KKoukiou said, there is no configuration file for this and one of cockpit design promises is that we don't do our configurations, but we use what is available on the system. You can use alternative logins, like [single-sign-on](https://cockpit-project.org/guide/latest/sso). You can read about other options [here](https://cockpit-project.org/guide/latest/authentication).

> There is an option to set the default language ?

It is per-browser setting (stored in cookie). Cockpit will use your default system language, but you can select one in cockpit UI (right top corner).

> My Debian 10 and my Firefox browser are in english but I see the login screen in french...

It seems you used cockpit with that browser before and changed the language to french? You can switch it back to english.

**Comment by mvollmer** [comment]
> There is an option to bypass the login screen ?

Greasemonkey?

**Comment by JaneX8** [comment]
I would also very much like to set a default language in `cockpit.conf` instead of defaulting to the users browser language.

**Comment by JaneX8** [comment]
Is there any way to workaround this as long as it is not supported? Server-side. Not in browser. By deleting the other language files or something? I simply want only English available and enabled and the rest disabled and not available.

**Comment by martinpitt** [comment]
@JaneX8 yes, in principle you can delete `/usr/share/cockpit/*/po.*.js.*`. This is package manager territory, but depending on your distro there are ways to do that. For Debian-based distros, you can create a /etc/dpkg/dpkg.cfg.d/cockpit-locales with an appropriate `path-exclude=` option, see `man dpkg` and `man dpkg.cfg`. Not sure about rpm.
