### ISSUE TITLE
noVNC and spice-html5 freezes

### ISSUE THREAD

**Issue by stanislavlevin** [cockpit-project/cockpit#13447]
Cockpit version: 210
Host OS: Fedora 31 Server
Guest OS: Fedora 31

My checked web browsers:
Firefox 68.3.0esr (64-bit)
Chromium  61.0.3163.100 (64-bit)
Google Chrome 66.0.3359.181 (64-bit)

Page: "Virtual Machines"

Steps to reproduce:

1. Install Fedora31 as a VM guest
2. Choose in Cockpit UI: Virtual Machines->Example domain name->Consoles->Graphics Console(VNC)

VNC window:
3. Launch Firefox
4. Follow, for example, https://www.google.com/doodles
5. Wait for ~30sec

VNC window will not be updated (symptom: animation stopped) until reconnect.

However, all work with the help of `virt-viewer` (direct method).

Exactly the same issue I faced with FleetCommander (one of the Cockpit's plugins) which utilizes the web browser's client of spice (`spice-html5`).
And again, all work with the help of `virt-viewer` (direct method).
I think, this issue is critical for FC as there is no other way to manage admin changes.

There are no related errors in the host/guest syslog.

**Comment by stanislavlevin** [comment]
Any thoughts here?

**Comment by KKoukiou** [comment]
@stanislavlevin hey sorry, your issue seemed to have been lost in our endless pile of open issues. 

Your issues must have been fixed by https://github.com/cockpit-project/cockpit/pull/15032
