### ISSUE TITLE
Cockpit can't reconnect to remote host - wrong authentication

### ISSUE THREAD

**Issue by radokristof** [cockpit-project/cockpit#13444]
Cockpit version: 188-1
OS: Raspbian/Debian 10 (Buster)
Page: Dashboard

I have a remote server which sometimes loses connection. It will be unavailable that time even in 
Cockpit - that's what I expect.

However after it becomes online again, the host Cockpit can't reconnect to that remote server.
Firstly it was unclear why. When I press 'Troubleshoot' it automatically offers to enter a new username and password. However the username/pass which is entered default there is for another server not that one... If I edit and enter the correct credentials it can connect easily... 
So it seems like it loses the stored user/pass and somehow it wants to use another user/pass combination (which is for another completely different server).

Steps to reproduce

1. Use Cockpit on one server and add a connection to another one.
2. Disconnect the remote server.
3. The host server won't reconnect to the remote server until you re-enter the credentials again...

**Comment by kallibr44** [comment]
did you solve this ?
