### ISSUE TITLE
creating logical volue - no check for names

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#1345]
Hi,
I've tried to create logical volume, and there is no check for name, it may not contain whitespaces, so there should be some check like [a-zA-Z0-9_]+ or something similar. I think that creation of volume group have this check, but in case of logical volue there it isn't:

Error creating logical volume: lvcreate exited with non-zero exit status 3: Logical volume name "ab cd" is invalid Run `lvcreate --help' for more information. 

But it is good that there is message that LVM name is invalid.
      Thanks&Regards
     Honza

**Comment by mvollmer** [comment]
This has been fixed.
