### ISSUE TITLE
Store Metrics doesn't work on RPI 4 with raspbian buster

### ISSUE THREAD

**Issue by LizhangX** [cockpit-project/cockpit#13455]
Cockpit version: 188-1 (on OMV 5)
OS: Raspbian GNU/Linux 10 (buster)
Page: System

Issue:
I like this tool since I can keep track of the system info and metrics.
However, if I understand correctly, the Store Metrics function should maintain the metrics so that I can come back like a week later and see how my system performed.
But it looks like to me that it wasn't functioning properly.
If anyone could take a look or know the fix, it is very much appreciated.
Thank you.

Steps to reproduce:
1.Install Cockpit through the OMV-Extras plugin in OMV 5.
2. Go to the GUI.
3. Let 5 mins view run for sometime
4. Switch to 1hr view or refresh the page
5. No metrics seems to be stored.
6. Also I don't see any journalctl logs generated while I switch the view.

Store Metrics is ON
![image](https://user-images.githubusercontent.com/15118114/73239636-519c0000-4162-11ea-8b0c-910fdee7611e.png)
5 mins view
![image](https://user-images.githubusercontent.com/15118114/73238763-b013af00-415f-11ea-8c6f-40d3c711e237.png)
then I switch to 1hr view (you can compare the timestamps with the 5 mins view)
![image](https://user-images.githubusercontent.com/15118114/73238782-c588d900-415f-11ea-8909-3cdd05550846.png)

**Comment by marusak** [comment]
188 is very old version (now we are at 211). There has been a bunch of fixes with storing and showing metrics since this version. Does this problem persists on some reasonably new version?

**Comment by LizhangX** [comment]
@marusak Thanks a lot for your reply. Understood.
I am going to raise an issue to the OMV-Extra side and see if they could provide/support newer versions. Closing this one for now.

**Comment by LizhangX** [comment]
Reopen:
Updated to version `208-1~bpo10+1` using Debian Buster backports.
Still seeing the same issue.
Took me few times to successfully login to the GUI with the same credential, and the system tab seem much slower than 188.
Also seeing this log on both versions, not sure if this could be related.
`Jan 28 23:02:39 raspberrypi cockpit-tls[2481]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.`

**Comment by jplegat** [comment]
Same issue here, installed cockpit 211 from Bullseye backports on Raspbian Buster.
pmlogger seems to be running fine (screenshot below).

<img width="1117" alt="Screen Shot 2020-02-01 at 8 07 06 PM" src="https://user-images.githubusercontent.com/10551112/73602820-7a3f4380-452e-11ea-9ea2-caf21f7b88e8.png">

**Comment by mi-hol** [comment]
@jplegat the latest version 212 seems available in raspbian repository at http://archive.raspbian.org/raspbian/pool/main/c/cockpit/
When I tried to upgrade my pi it was  reporting that 188 is the latest version (perhaps a mirror I use misses it yet).
Have you had a chance to try?

**Comment by LizhangX** [comment]
@mi-hol  Newer version doesn't come with Debian out of the box. You would need to update the source list using bullseye to have the newest 212 version. And buster-backports to have 208. [Reference](https://backports.debian.org/buster-backports/overview/)

I was trying with 208 but will try with 212 and get back here.

**Comment by mi-hol** [comment]
@LizhangX did 212 work for you?

**Comment by LizhangX** [comment]
@mi-hol Hi, I didn't have time to check yet. 
You can try the bullseye source list and do apt-get update/upgrade once.

**Comment by basilean** [comment]
Hello guys,
I just upgraded and I'm still having same issue with a Debian bullseye/sid on a cubieboard.
pcp (5.0.3-1) 
cockpit-pcp (213-1)

pmlogger active and running.
No cockpit-pcp logs at all.

I also confirmed that logs exists and contain data using:
# pmiostat -a 20200228.0
# pmstat -a 20200228.0

"Store Metrics" is ticked but it looks like only shows "realtime" collection, once I refresh page, data get lost and starts over.

I will be happy to provide any details that could help to debug it.
Andres.-

**Comment by marusak** [comment]
We don't have 'store metrics' button anymore.
There are still a few issues with loading metrics though - for example it might be related to changing of hostname: https://github.com/cockpit-project/cockpit/issues/15039

**Comment by Omoeba** [comment]
I have the same issue with pcp 5.3.0 and cockpit 237-1~bpo10+1

**Comment by Omoeba** [comment]
The hostname was not modified in any way.
