### ISSUE TITLE
Testsuite failure on openSUSE: assertion failed (cockpit_conf_string ("Section2", "value1") == "string")

### ISSUE THREAD

**Issue by glaubitz** [cockpit-project/cockpit#13452]
Currently trying to update ```cockpit``` on openSUSE/SLE:

> https://build.opensuse.org/package/show/home:glaubitz:branches:systemsmanagement:cockpit/cockpit

The build fails with:

```
[  124s] SKIP: test-config Bail out! cockpit-protocol:ERROR:src/common/test-config.c:140:test_load_dir: assertion failed (cockpit_conf_string ("Section2", "value1") == "string"): (NULL == "string")
[  124s] **
[  124s] cockpit-protocol:ERROR:src/common/test-config.c:140:test_load_dir: assertion failed (cockpit_conf_string ("Section2", "value1") == "string"): (NULL == "string")
[  124s] ERROR: test-config process failed: -6
```

Haven't checked yet what the problem could be. Might provide more information later.

**Comment by martinpitt** [comment]
Interesting.. I suppose it's not the parser code itself that is failing, as that's checked in the previous test cases (test_load_dir is the last test in test-config). So my first guess is that there's something wrong with the file loading. As there is no warning either, it's `ENOENT`; from here:

```c
static bool
load_key_file (const char *file_path)
{
[...]
  f = fopen (file_path, "r");
  if (!f)
    {
      if (errno != ENOENT)
        warnx ("couldn't load configuration file: %s: %m\n", file_path);
      return false;
    }

```

The file that it is trying to load is src/ws/mock-config/cockpit/cockpit.conf, which is shipped in the cockpit release tarball. I don't have an idea why it would be missing, but at that point it needs debugging -- i. e. is the test trying to load the wrong path, or is the file somehow missing from the build env, etc. Some initial questions:

 - Does this reproduce at all, or was it a weird flake?
 - If it reproduces, is there some way to replicate the build env? In a container or so?
 - It would be most helpful to run `strace -fvvs1024 ./test-config -p /conf/load_dir` to see what this is doing.

(Note that we run this unit test in CI on multiple versions of Fedora, Debian, Ubuntu, RHEL, and CentOS)

**Comment by marusak** [comment]
@glaubitz ping

**Comment by glaubitz** [comment]
Seems to build fine these days:

> https://build.opensuse.org/package/show/systemsmanagement:cockpit/cockpit
> https://build.opensuse.org/package/show/openSUSE:Factory:PowerPC/cockpit
> https://build.opensuse.org/package/show/openSUSE:Factory:ARM/cockpit

**Comment by marusak** [comment]
Thanks for the reply, closing then.
