### ISSUE TITLE
about Prometheus support instead of cockpit-pcp 

### ISSUE THREAD

**Issue by doyoungim999** [cockpit-project/cockpit#13468]
Page: 
Persistence metrics - 
yum install cockpit-pcp  

I am a OpenShift architect and wondering why cockpit does not support prometheus for metrics storage. 
If it is,  cockpit can store metrics of all servers and container metrics which can be stored using s3 protocol in Object Storage simply as a storage. 
Is there any plan to support prometheus ? Or not considered ?

**Comment by slrtbtfs** [comment]
Hi, Prometheus contributor here.

As far as I know, there are no such plans, but I obviously can't speak for the cockpit developers.

Can you be a bit more specific about your request? It is not really clear to me how these two projects should integrate.

Depending on what you need, the OpenShift console might be useful for you, instead.

**Comment by doyoungim999** [comment]
I am trying to use  Cockpit for KVM and OpenShift is using Proemtheus as a default option to monitor Container environment. 
I found Cockpit is using PCP. 
As a system administrator,  PCP and prometheus should be managed for monitoring. 
So i am asking prometheus support to design and make the system administration simple with prometheus technology. 

Because administrator should  manage normal baremetal server , KVM environment as well as  containers by OpenShift.  
I am asking for System administration who requires to maintain baremetal server, KVM and containers.

**Comment by Jean-Baptiste-Lasselle** [comment]
Hi, I here add a message to support @doyoungim999 's request : 
* I was today playing with podman, and came across https://github.com/cockpit-project/cockpit-podman
*And I immediately wanted to see how to integrate the metrics collected by cockpit, into a consistantly auditable monitoring system. Looked up google, and found this issue.
* Immediately thought of Prometheus (and ELK Grafana), and currently working on the same thing as @doyoungim999 , so as to propose production recommendations, including monitoring, for an open-source product about to kickoff.

**Comment by slrtbtfs** [comment]
@Jean-Baptiste-Lasselle It sounds the feature your asking for is metrics exported by cockpit. That seems to be something completely different than what @doyoungim999 is asking for.

**Comment by parametriq** [comment]
Persistent metrics storage in Prometheus would be possible if metrics were directly and constantly being exported via API. You just can take a look at how this is implemented in NetData. One just specifies NetData API endpoint that offers exported metrics data in Prometheus settings and voila! That would satisfy both previous requests and mine just as well. But, AFAIK there's no such API in Cockpit currently

**Comment by slrtbtfs** [comment]
@Jean-Baptiste-Lasselle @parametriq What you seem to be asking for is instrumenting cockpit and adding a `/metrics` endpoint.

That's something completely different to replacing cockpit-pcp (which is what this issue seemed to be about), so it might be better to open a separate issue.

**Comment by martinpitt** [comment]
Sorry, we don't plan anything like this. Cockpit shows local /sys and PCP metrics on the "Metrics history" page, but it's not cockpit's place to either *generate*/send metrics from a machine (that should be done by prometheus itself), nor view them (that's Grafana).
