### ISSUE TITLE
Cannot add server via JSON with different user name

### ISSUE THREAD

**Issue by kbknapp** [cockpit-project/cockpit#13466]
Cockpit version: 
```
$ cockpit-bridge --version
Version: 211
Protocol: 1
Payloads: dbus-json3 http-stream1 http-stream2 stream packet fsread1
    fsreplace1 fswatch1 fslist1 null echo websocket-stream1
Authorization: crypt1
```
OS: Ubuntu 18.04.3
Page: Dashboard

The network is as follows

* A:
  * has `cockpit-ws` et. al.
  * Accessible remotely
  * Can access machines B and C on LAN
  * User Account: `usr`
    * pub_usr can SSH to as the `admin` on machines B and C (i.e. `ssh admin@B`)
* B:
  * has `cockpit-bridge`
  * only accessible on LAN (private IP: 192.168.1.10)
  * User Account: `admin`
* C:
  * has `cockpit-bridge`
  * only accessible on LAN (private IP: 192.168.1.11)
  * User Acount: `admin`

Intended workflow is we log in to the cockpit webpage on machine A as `usr` and then click on the servers B or C to manage those servers.

Setup on machine A:

```
# /etc/cockpit/machines.d/10-int.json
{
  "B" : {
    "visible" : true,
    "color" : "red",
    "address" : "192.168.1.10",
    "user": "admin"
  },
  "C" : {
    "visible" : true,
    "color" : "green",
    "address" : "192.168.1.11",
    "user": "admin"
  }
}
```

Loading the webpage displays the servers as expected. However, upon clicking on server we receive either, "Not Found" or "Couldn't Connect" errors 100% of the time.

When watching `/var/log/syslog` on either B or C, the following output is observed 100% of the time when clicking on the servers on the webpage:

```
Jan 29 16:47:06 B cockpit-bridge[20071]: couldn't create polkit session subject: No session for pid 20071
Jan 29 16:47:07 B dbus-daemon[964]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.185' (uid=999 pid=20071 comm="" label="unconfined")
Jan 29 16:47:07 B systemd[1]: Starting Hostname Service...
Jan 29 16:47:07 B dbus-daemon[964]: [system] Successfully activated service 'org.freedesktop.hostname1'
Jan 29 16:47:07 B systemd[1]: Started Hostname Service.
```

The relevant line appears to be the `polkit` error? Which the [source says is just a race condition](https://github.com/cockpit-project/cockpit/blob/d7587c210496d047a9d377212ae9308b5505272d/src/bridge/cockpitpolkitagent.c#L444), however this condition happens 100% of the time.

--- 

If I log in to the cockpit webpage as `admin` on A *and* add the servers manually via the web page, this problem does not seem to happen.

**Comment by martinpitt** [comment]
So it looks like cockpit actually *was* able to log into machine B at least, as you are getting messages from the running cockpit-bridge. So it's not obvious to me what actually is "not found" there. Also, the dashboard went away in favor of the host switcher in current versions. Is that still an issue with recent cockpit?

**Comment by martinpitt** [comment]
No reply in a year, closing.
