### ISSUE TITLE
How to install cockpit on the remote without Webdashboard

### ISSUE THREAD

**Issue by jensamberg** [cockpit-project/cockpit#13477]
Page: 

Hello,

how to install cockpit on the remote without Webdashboard.
I will only have the possibility to connect to ta remot machine without exposing the port 9090
Webdashboard to the internet?

**Comment by martinpitt** [comment]
Not sure what you mean exactly, but what you can do:

 * Install cockpit-ws on one host, that runs the web server and has port 9090 open (or a different port if you want to [change it](https://cockpit-project.org/guide/latest/listen.html)). On that, use the login screen's "Connect to:" option to connect to a remote host through SSH.

 * Install cockpit-system, and any other extensions like cockpit-networkmanager, cockpit-storage, etc. on that remote host, but *not* cockpit-ws. On that host you only need SSH running.

Is that what you are looking for?

**Comment by jensamberg** [comment]
> Not sure what you mean exactly, but what you can do:
> 
> * Install cockpit-ws on one host, that runs the web server and has port 9090 open (or a different port if you want to [change it](https://cockpit-project.org/guide/latest/listen.html)). On that, use the login screen's "Connect to:" option to connect to a remote host through SSH.
> * Install cockpit-system, and any other extensions like cockpit-networkmanager, cockpit-storage, etc. on that remote host, but _not_ cockpit-ws. On that host you only need SSH running.
> 
> Is that what you are looking for?

Thanks. This is the question what do I need Minimum for packages e.g. Ubuntu Server 18 on the Remote Host ?

**Comment by martinpitt** [comment]
The minimum is cockpit-system, which pulls in cockpit-bridge.
