### ISSUE TITLE
tracker: Selenium tests covered by verify tests

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#13481]
This is tracker for replacing selenium tests with nondestructive verify tests.
Second column contains name of a test, that covers all steps that selenium test does. Third column is set to :heavy_check_mark: once this test is marked with `@nondestructive` decorator.

Name | Cover by test | Covering test is nondestructive
--- | --- | ---
selenium-base.py:BasicTestSuite.test10Base | check-multi-machine | doesn't need replacement, sanity only
selenium-base.py:BasicTestSuite.test15BaseSSHKeyAdded |  - | internal selenium test suite sanity check only
selenium-base.py:BasicTestSuite.test20Login | TestLogin.testBasic |  :heavy_check_mark: https://github.com/cockpit-project/cockpit/pull/13584
selenium-base.py:BasicTestSuite.test30ChangeTabServices | TestServices.testBasic | :heavy_check_mark: #13758
selenium-base.py:BasicTestSuite.test50ChangeTabLogs | TestJournal.testBasic | :heavy_check_mark: #14241
selenium-base.py:BasicTestSuite.test70ChangeTabNetworking | check-networking-basic | :heavy_check_mark:  #13792
selenium-base.py:BasicTestSuite.test80Accounts | TestAccounts.testBasic | :heavy_check_mark:  https://github.com/cockpit-project/cockpit/pull/13623
selenium-base.py:BasicTestSuite.test90Terminal |check-terminal TestTerminal.testBasic | :heavy_check_mark:  (#13583)
selenium-dashboard.py:TestDashboard.testDashboard | TestBasicDashboard.testBasic | :heavy_check_mark:  #14103
selenium-firewalld.py:FirewalldBasePage.testEnabling | TestFirewall.testNetworkingPage | :heavy_check_mark: #13705
selenium-firewalld.py:FirewalldBasePage.testEnablingByCommand | TestFirewall.testNetworkingPage | :heavy_check_mark:  #13705 
selenium-firewalld.py:FirewalldPage.testCockpitService | TestFirewall.testFirewallPage | :heavy_check_mark: #13705
selenium-firewalld.py:FirewalldPage.testAddService | TestFirewall.testAddServices | :heavy_check_mark: #13705
selenium-firewalld.py:FirewalldPage.testRemoveService | TestFirewall.testAddServices | :heavy_check_mark: #13705
selenium-firewalld-zones.py:FirewalldZones.testDefaultZoneListing | TestFirewall.testFirewallPage | :heavy_check_mark: #13075
selenium-firewalld-zones.py:FirewalldZones.testAddRemoveCustomZone | TestFirewall.testMultipleZones | :heavy_check_mark: #13705
selenium-firewalld-zones.py:FirewalldZones.testAddServiceToCustomZone | TestFirewall.testMultipleZones | :heavy_check_mark: #13705
selenium-hwinfo.py:TestHWinfo.testCPUinfo | TestSystemInfo.testHardwareInfo | :heavy_check_mark:  #13883
selenium-hwinfo.py:TestHWinfo.testSMT | TestSystemInfo.testCPUSecurityMitigations | :heavy_check_mark: #14050
selenium-kdump.py:TestKdump.testKdumpBasePage | TestKdump.testBasic |
selenium-kdump.py:TestKdump.testNFS | TestKdump.testBasic |
selenium-login-special.py:TextInBashRC.test | TestLogin.testBasic | :heavy_check_mark:  https://github.com/cockpit-project/cockpit/pull/13584
selenium-login-special.py:SessionLoggingShell.testShell | TestLogin.testConversation  | :heavy_check_mark: https://github.com/cockpit-project/cockpit/pull/13584
selenium-login-special.py:SessionLoggingShell.testRecordingShell | TestLogin.testSessionRecording | :heavy_check_mark: https://github.com/cockpit-project/cockpit/pull/13584
selenium-machines-basic.py:MachinesBasicTestSuite.testNoVm | machineslib.py TestMachinesDBus.[testLibvirt, testCreate]| :heavy_check_mark:  (#13607) 
selenium-machines-basic.py:MachinesBasicTestSuite.testOverviewInfo |machineslib.py  TestMachinesDBus.[testCreate, testVCPU], check-machines-dbus TestMachinesDBus.[testMemorySettings, testBootOrder...]| :heavy_check_mark:  (#13607)
selenium-machines-basic.py:MachinesBasicTestSuite.testRunVm | machineslib.py TestMachinesDBus.testBasic| :heavy_check_mark:  (#13607)
selenium-machines-basic.py:MachinesBasicTestSuite.testRestartVm | |  :heavy_check_mark: #14041
selenium-machines-basic.py:MachinesBasicTestSuite.testForceRestartVm | |  :heavy_check_mark: #14041
selenium-machines-basic.py:MachinesBasicTestSuite.testShutdownVm | |  :heavy_check_mark: #14041
selenium-machines-basic.py:MachinesBasicTestSuite.testForceShutdownVm | machineslib.py TestMachinesDBus.testBasic  | :heavy_check_mark:  (#13607)
selenium-machines-basic.py:MachinesBasicTestSuite.testSendNMI | machineslib.py TestMachinesDBus.testBasic | :heavy_check_mark:  (#13607)
selenium-machines-basic.py:MachinesBasicTestSuite.testDelete | machineslib.py TestMachinesDBus.testDelete  | :heavy_check_mark:  (#13607)
selenium-machines-basic.py:MachinesBasicTestSuite.testVmStatus | machineslib.py TestMachinesDBus.testBasic  | :heavy_check_mark:  (#13607)
selenium-machines-basic.py:MachinesBasicTestSuite.testCreateVMWithISO | machineslib.py TestMachinesDBus.testCreate |:heavy_check_mark:  (#13699)
selenium-machines-basic.py:MachinesBasicTestSuite.testCreateVMWithUrl | machineslib.py TestMachinesDBus.testCreate |:heavy_check_mark:  (#13699)
selenium-machines-consoles.py:MachinesConsolesTestSuite.testInlineConsole | machineslib.py TestMachinesDBus.testInlineConsole | :heavy_check_mark:  (#13607)
selenium-machines-consoles.py:MachinesConsolesTestSuite.testExternalConsole | machineslib.py TestMachinesDBus.testExternalConsole | :heavy_check_mark:  (#13607)
selenium-machines-consoles.py:MachinesConsolesTestSuite.testSerialConsole | machineslib.py TestMachinesDBus.testSerialConsole | :heavy_check_mark:  (#13607)
selenium-machines-disks.py:MachinesDisksTestSuite.testDiskInfo | machineslib.py TestMachinesDBus.testAddDisk | :heavy_check_mark:  (#13701)
selenium-machines-disks.py:MachinesDisksTestSuite.testAddDiskWithVmOff | | :heavy_check_mark: #14041 
selenium-machines-disks.py:MachinesDisksTestSuite.testAddDiskWithVmOn | machineslib.py TestMachinesDBus.testAddDisk |  :heavy_check_mark:  (#13701)
selenium-machines-disks.py:MachinesDisksTestSuite.testDetachDiskVmOn | check-machines-dbus TestMachinesDBus.testDetachDisk | :heavy_check_mark:  (#13635)
selenium-machines-disks.py:MachinesDisksTestSuite.testDetachDiskVmOff | check-machines-dbus TestMachinesDBus.testDetachDisk | :heavy_check_mark:  (#13635)
selenium-machines-networks.py:MachinesNetworksTestSuite.testNetworkInfo |machineslib.py TestMachinesDBus.testVmNICs | :heavy_check_mark:  (#13635)
selenium-machines-networks.py:MachinesNetworksTestSuite.testNetworkPlug | check-machines-dbus TestMachinesDBus.testNICAdd | :heavy_check_mark:  (#13635)
selenium-machines-networks.py:MachinesNetworksTestSuite.testNetworkEditWithRunning | check-machines-dbus TestMachinesDBus.testNetworkSettings | :heavy_check_mark:  (#13635)
selenium-machines-networks.py:MachinesNetworksTestSuite.testNetworkEditWithOff | check-machines-dbus TestMachinesDBus.testNetworkSettings | :heavy_check_mark:  (#13635)
selenium-machines-network-page.py:MachinesNetworkPageTestSuite.testNetworkPageInfo | check-machines-dbus TestMachinesDBus.testNetworks | :heavy_check_mark:  (#13783)
selenium-machines-non-root.py:MachinesNonrootTestSuite.testNonRootOperationWithVm | | :heavy_check_mark: #14041
selenium-machines-non-root.py:MachinesNonrootTestSuite.testLibvirtUserOperationWithVm | | :heavy_check_mark: #14041
selenium-machines-non-root.py:MachinesNonrootTestSuite.testWheelUserOperationWithVm | | :heavy_check_mark: #14041
selenium-machines-storage-pool.py:MachinesStoragePoolTestSuite.testCheckStoragePool | check-machines-dbus TestMachinesDBus.testStoragePools | :heavy_check_mark:  (#13635)
selenium-machines-storage-pool.py:MachinesStoragePoolTestSuite.testCreateDirStoragePool | check-machines-dbus TestMachinesDBus.testStoragePoolsCreate | :heavy_check_mark:  (#13699)
selenium-machines-storage-pool.py:MachinesStoragePoolTestSuite.testCreateNFSStoragePool | check-machines-dbus TestMachinesDBus.testStoragePoolsCreate | :heavy_check_mark:  (#13699)
selenium-machines-storage-pool.py:MachinesStoragePoolTestSuite.testAddAllPhysicalDiskDevice | check-machines-dbus TestMachinesDBus.testStoragePoolsCreate | :heavy_check_mark:  (#13699)
selenium-machines-storage-pool.py:MachinesStoragePoolTestSuite.testAddISCSIStoragePool | check-machines-dbus TestMachinesDBus.testStoragePoolsCreate | :heavy_check_mark:  (#13699)
selenium-machines-storage-pool.py:MachinesStoragePoolTestSuite.testCheckStateOfStoragePool | check-machines-dbus TestMachinesDBus.testStoragePools | :heavy_check_mark:  (#13635)
selenium-machines-storage-pool.py:MachinesStoragePoolTestSuite.testDeleteStoragePool | check-machines-dbus TestMachinesDBus.testStoragePools | :heavy_check_mark:  (#13635)
selenium-machines-usage.py:MachinesUsageTestSuite.testUsage | machineslib.py TestMachinesDBus.testBasic | :heavy_check_mark:  (#13607)
selenium-machines-vcpu.py:MachinesOverviewTestSuite.testVcpuConfig0 | machineslib.py TestMachinesDBus.testVCPU | :heavy_check_mark:  (#13607)
selenium-machines-vcpu.py:MachinesOverviewTestSuite.testVcpuConfig1 |machineslib.py TestMachinesDBus.testVCPU | :heavy_check_mark:  (#13607)
selenium-navigate.py:NavigateTestSuite.testNavigateNoReload | TestPages.testBasic | :heavy_check_mark: #14064
selenium-network.py:NeworkTestSuite.testBasePage | check-networking-basic TestNetworking.testBasic | :heavy_check_mark: #13792
selenium-network.py:NeworkTestSuite.testGraphs | check-networking-basic TestNetworking.testBasic | :heavy_check_mark: #13792
selenium-network.py:NeworkTestSuite.testSanityVlans | check-networking-vlan | :heavy_check_mark:  #13879 
selenium-network.py:NeworkTestSuite.testSanityBridge | check-networking-bridge | :heavy_check_mark: #13915
selenium-network.py:NeworkTestSuite.testSanityBond | check-networking-bond | :heavy_check_mark: #13879
selenium-network.py:Bonding.testSlaveRemove | check-networking-bond testAmbiguousSlave | :heavy_check_mark: #13879
selenium-sosreport.py:SosReportingTab.test10SosReport | TestSOS.testBasic | :heavy_check_mark:  https://github.com/cockpit-project/cockpit/pull/13586
selenium-storage.py:StorageTestSuite.test10Storage | check-storage-lvm2 TestStorage.testLvm | :heavy_check_mark: #13659
selenium-tuned.py:TunedProfiles.testPerformaceProfiles | check-tuned | :heavy_check_mark: (#13731)

**Comment by martinpitt** [comment]
I went through all the non-libvirt tests and marked their equivalent verify tests. I indeed found 3 minor and one bigger gap (tlog). @KKoukiou , could you please have a look at the 7 Machines tests, if they have verify equivalents?

**Comment by martinpitt** [comment]
I sent PR #13523 about the three missing verify tests as above (all but Machines)
