### ISSUE TITLE
Network: Wrong description in the "Create a network section" can lead into strange network issues

### ISSUE THREAD

**Issue by valonmamudi** [cockpit-project/cockpit#13506]
**Basic information**

Name         : cockpit
Version      : 210
OS/Release      : 1.fc30
Architecture : x86_64
Size         : 53 k
Quelle       : cockpit-210-1.fc30.src.rpm
Page: Host --> Virtual Machines --> Networks --> Create Virtual Network

**Description**

While creating a new virtual network, it automatically fills the "IPv4 Network" field with 192.168.100.**0**, which is ok but after creating the network, it takes the address 192.168.100.0 as a gateway address in the virtual machines connected to the network and IP for the virtualization host.

In my case the basic connectivity was given but I had very strange network issues between docker container and other VM's connecting to it until I changed it manually with virsh net-edit to 192.168.100.1. 

IMO it would be better to change the field to gateway and use the first available IP in the given range. 

**Steps to reproduce**

1. Go to Host --> Virtual Machines --> Networks --> Create Virtual Network
2. Add the network with the Address autmatically filled

![cockpit-network](https://user-images.githubusercontent.com/55285918/73983951-dd1e4980-4937-11ea-8adf-13dca2267505.png)

![ipnewnet](https://user-images.githubusercontent.com/55285918/73984252-911fd480-4938-11ea-9b68-dd7a552aaffc.png)

**Comment by KKoukiou** [comment]
@valonmamudi I fixed your issue in #13527 the same way that virt-manager deals with this. Let me know if that works for you - or even if you have a better fix for this;
Since you mentioned above to use gateway, which I am not certain how it translates to a Net XML.

**Comment by KKoukiou** [comment]
That was fixed within https://github.com/cockpit-project/cockpit/pull/14564
