### ISSUE TITLE
Per core utilization

### ISSUE THREAD

**Issue by jhfry** [cockpit-project/cockpit#13536]
An overall utilization value can mask underlying performance issues on servers with many cores making the overall CPU utilization less valuable.  

Perhaps clicking the CPU graph would toggle between overall and individual core graphs?  Or perhaps clicking the graph would just display a popup box with the individual core's current utilization in text or graph form?  Not sure what the optimal display would be.

**Comment by marusak** [comment]
Implemented in https://github.com/cockpit-project/cockpit/pull/15298
