### ISSUE TITLE
Microalign PF3 overrides to PF4

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#13547]
Some of the widgets have changed again in PF4. The changes are quite subtle. Most notable is the removal of the slight border-radius. There may be other little changes too.

I noticed this in a screenshot that has PF3, Cockpit-specific, and PF4 widgets all next to each other.

Screenshot attached:

![Screenshot_2020-02-13 Virtual Machines - Rain](https://user-images.githubusercontent.com/10246/74449509-f0bc3980-4e7c-11ea-820a-b728c4b1762f.png)

Ignore the error in this context. Please look at the dropdowns above the VM's VNC window.

Also, related: Our (custom? or PF3?) split buttons don't look like PF4's.

**Comment by KKoukiou** [comment]
Today we merged the PR for the consoles specifically. Generally, I think we don't plan to work more on improving the PF3 overrides, rather we are very close to completely remove it.
 I am closing this issue, since the single specific reference it has was fixed today.
