### ISSUE TITLE
List current connected users with details

### ISSUE THREAD

**Issue by sprietNathanael** [cockpit-project/cockpit#13542]
Page: I don't really know, maybe a new section

It would be interesting to add informations about the users currently connected to the server. Something like the result of the `w` command, with the user's login, its IP, date of login, last command...

**Comment by marusak** [comment]
Related to https://github.com/cockpit-project/cockpit/issues/28
And we also have [design](https://raw.githubusercontent.com/cockpit-project/cockpit-design/9a65b44ffa9cf60a6eaf02044e797d0046b77d6b/users/login-warning.png) that mostly addresses that (second to last).

**Comment by sprietNathanael** [comment]
Oh sorry, didn't see this one!
