### ISSUE TITLE
Display uptime

### ISSUE THREAD

**Issue by sprietNathanael** [cockpit-project/cockpit#13541]
Page: Overview (I think)

As discussed in #49 It would be very interesting to include somewhere the uptime information.
Or at least, the last boot date.

**Comment by martinpitt** [comment]
This could go into the "Usage" or "System information" card, or possibly "Health", I'm not sure about which one would be best. @garrett, do you have an opinion about this?

**Comment by Wibbbs** [comment]
I just want to add a +1 to this. Seems strange to have so much information and not the uptime. I think it would fit right in on the system page.

**Comment by garrett** [comment]
I think I had uptime in one of my earlier mockups. We scaled back to what was already in Cockpit, so if I did have it there, I took it out.

Health is reserved for things that go wrong on the system, basically. Uptime isn't something going wrong, unless there are security issues that haven't been applied (and need a reboot). But we already have something in Health about that.

System Information or Usage are indeed the places that make the most sense. I was also considering having the uptime next to the reboot button at one point in time, but it's way too prominent.

I think **System Information** probably makes the most sense, as it's just (almost) static information that is at-most updated every minute.

**Uptime** should be days, hours, and minutes, not seconds. It **should only show what's needed**. In other words, we would have strings like this:

- 32 minutes
- 5 hours 12 minutes
- 24 days 9 hours 6 minutes
- 32 days 1 hour 57 minutes
- 404 days 12 hours 1 minute

However, once we hit a certain bit of time, it really makes sense to **drop the smaller values**. Hours and minutes don't matter at 404 days, and they probably don't even matter at 24 days. (Just like seconds never really matter for uptime.) I'm not sure what threshold that would be, however. Perhaps **only have <= 2 units of time**? (so: 24 days 9 hours, 32 days — more than month is implied, so drop the hours?) So, it'd look like this:

- 32 minutes
  - never show seconds; it doesn't matter and makes the UI update needlessly (and even jump, as our current font does not support tabular numbers)
- 5 hours 12 minutes
  - keep not showing the seconds, but keep the minutes for now
- 1 day 6 hours
  - minutes has been dropped, as we're counting days
- 24 days
  - \>= 7 days; week is implied, so drop hours, minutes
- 32 days
  - \>= 7 days; week is implied, so drop hours, minutes
- 404 days
  - \>= 7 days; week is implied, so drop hours, minutes

We _could_ also use the rounding method mentioned above and provide more details on hover (for those who _really_ want to know).

**Comment by marusak** [comment]
Implemented in https://github.com/cockpit-project/cockpit/pull/13885
