### ISSUE TITLE
Adopt PF4's new left-aligned button order

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#13546]
PatternFly has switched the button order to be left-aligned instead of right-aligned. Cockpit should adapt.

1. We should move the buttons in the HTML/JS to preserve document order.
2. All dialogs should be updated at one time. Consistency matters!
3. Switching to PF4 for dialogs wherever possible would probably help.
4. Legacy buttons should switch order at the same time too.

It's currently undetermined what to do with the right-aligned buttons for everything other than dialogs. @andreasn and I should probably revisit some designs too.

As this is a Cockpit-wide endeavor, we'll need to make sure everyone's ready for it. Since it involves PF4 to some extent (porting dialogs, possibly), perhaps @KKoukiou and I would be best suited for this? We'll probably need @martinpitt's help too.

And anyone else who wants to help out would be really welcomed as well, as this is probably going to be a large task.

**Comment by andreasn** [comment]
What version of Patternfly did this land in? Is there other things we need from that version urgently? Just trying to get a feel for how soon we need to switch this over.

**Comment by andreasn** [comment]
After some more research, it seems it's an opt-in feature for now.
The [design documentation](https://www.patternfly.org/v4/documentation/react/components/modal) says:
_In a future breaking-change release, the modal footer buttons will default to be left aligned. You can opt into this now by setting the Modal isFooterLeftAligned prop to true._

So less urgent than I first feared, but good to start preparing for it.

**Comment by andreasn** [comment]
The **isFooterLeftAligned prop** was added in [Patternfly 2019.07](https://www.patternfly.org/v4/documentation/react/overview/release-notes#201907-release-notes-2019-09-10)

**Comment by garrett** [comment]
> good to start preparing for it

Exactly why I opened this issue.

It'll be a good bit of work for Cockpit to switch, so we need to start the process sooner rather than later, but we do still have some time. It's not urgent.
