### ISSUE TITLE
Cockpit on Fedora 31 cannot perform software update

### ISSUE THREAD

**Issue by lexiconzero** [cockpit-project/cockpit#13553]
Cockpit version: Server:210 Host:212
OS: Fedora 31
Page: Software updates

On my fresh Fedora 31 minimal install on ESXi, navigating to the software updates page produces the following error:

"Failed to check for authentication: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable"

Feb 15 14:39:05 containers.localdomain sudo[1469]: pam_unix(sudo:session): session closed for user root
Feb 15 14:39:05 containers.localdomain audit[1469]: USER_END pid=1469 uid=0 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
Feb 15 14:39:05 containers.localdomain audit[1469]: CRED_DISP pid=1469 uid=0 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_env,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
Feb 15 14:39:16 containers.localdomain PackageKit[1312]: uid 0 is trying to obtain org.freedesktop.packagekit.system-sources-refresh auth (only_trusted:0)
Feb 15 14:39:18 containers.localdomain audit[1475]: USER_ACCT pid=1475 uid=1000 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:accounting grantors=pam_unix acct="user" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
Feb 15 14:39:18 containers.localdomain audit[1475]: USER_CMD pid=1475 uid=1000 auid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='cwd="/home/user" cmd=6A6F75726E616C63746C202D2D73696E6365202D31306D202D786E exe="/usr/bin/sudo" terminal=pts/1 res=success'`

Steps to reproduce

1. Install cockpit on Fedora 31
2. Navigate to software updates as a privileged user on the host
3. Observe issue

**Comment by martinpitt** [comment]
This is https://bugzilla.redhat.com/show_bug.cgi?id=1800468 . Please run `dnf install polkit` to fix that. Thanks!
