### ISSUE TITLE
Root account is locked

### ISSUE THREAD

**Issue by unik-web** [cockpit-project/cockpit#13579]
Cockpit version: 195.1
OS: Centos 7
Page: 

I have problems with to allow root user. By mistake I was able to lock root account and my wheel account is block to change the root account. How to re-enable to allow my root account to access in cockpit.

![Screenshot from 2020-02-20 11-32-31](https://user-images.githubusercontent.com/38878075/74926052-94559e80-53d5-11ea-88c0-bb29fd9dc18b.png)

**Comment by marusak** [comment]
`sudo usermod root --unlock`?

**Comment by marusak** [comment]
That being said, you should be able to change this for root, if you are wheel user.
Have you logged in with `Reuse my password for privileged tasks`? (Do you see `Privileged` on the top right of the page)

**Comment by unik-web** [comment]
Hi,
Thanks it works just typed sudo usermod root --unlock and I was able to login with root priviled.
