### ISSUE TITLE
Provide  JSDoc or Typescript definitions for cockpit.js

### ISSUE THREAD

**Issue by jose-pr** [cockpit-project/cockpit#13597]
Add  JSDoc or Typescript definitions to the cockpit.js apis for easier development and to take advantage of autocomplete / type checking provided by tools liks VS Code.

**Comment by martinpitt** [comment]
There's some ongoing work in PR #13214

**Comment by martinpitt** [comment]
Closing this issue, tracking it in the PR is enough.
