### ISSUE TITLE
Ubuntu 16.04 package update

### ISSUE THREAD

**Issue by alex3594** [cockpit-project/cockpit#13593]
Hello!
Is there any chance to update the Cockpit packages for Ubuntu 16.04?
Or maybe any PPA is available?
Thanks!

**Comment by martinpitt** [comment]
Sorry, we don't actively test/support that any more. You are welcome to try and build the package yourself (i. e. do a source package backport), but there will be some broken functionality e. g. on the Machines page and possibly in other places.
