### ISSUE TITLE
Modal on kdump page is not in the middle

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#13591]
Cockpit version: 213
OS: Fedora 30
Page: Kernel Dump

Modal for changing dump location floats to the left and is not in the centre as all other dialogs.

![weirdlyinttehcorrner](https://user-images.githubusercontent.com/12330670/75031982-c33c4500-54a7-11ea-9776-7c34edc39891.png)

**Comment by leomoty** [comment]
This is the same as #12771, unsure if the same fix could get both correct

**Comment by marusak** [comment]
> This is the same as #12771, unsure if the same fix could get both correct

Great point, thanks!
