### ISSUE TITLE
Cockpit displays a blank page after login via web console on CentOS 8

### ISSUE THREAD

**Issue by gayhub-dev** [cockpit-project/cockpit#13595]
Cockpit version: 
cockpit-bridge-196.3-1.el8.x86_64
cockpit-196.3-1.el8.x86_64
cockpit-system-196.3-1.el8.noarch
cockpit-packagekit-197.3-1.el8.noarch
cockpit-ws-196.3-1.el8.x86_64
OS:
CentOS 8 4.18.0-147.3.1.el8_1.x86_64

log:
Feb 23 10:23:19 lon1-01 remotectl[26623]: /usr/bin/chcon: can't apply partial context to unlabeled file '/etc/cockpit/ws-certs.d/0-self-signed.cert'
Feb 23 10:23:19 lon1-01 remotectl[26623]: remotectl: couldn't change SELinux type context 'etc_t' for certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert: Child process exited with code 1
Feb 23 10:23:19 lon1-01 cockpit-ws[26625]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Feb 23 10:23:48 lon1-01 cockpit-ws[26625]: couldn't read from connection: Peer failed to perform TLS handshake
Feb 23 10:24:34 lon1-01 cockpit-session[26637]: pam_ssh_add: Failed adding some keys
Feb 23 10:24:34 lon1-01 cockpit-session[26637]: pam_unix(cockpit:session): session opened for user root by (uid=0)
Feb 23 10:24:34 lon1-01 cockpit-ws[26625]: logged in user session
Feb 23 10:24:39 lon1-01 cockpit-ws[26625]: couldn't read from connection: Peer failed to perform TLS handshake
Feb 23 10:24:49 lon1-01 cockpit-ws[26625]: session timed out
Feb 23 10:24:49 lon1-01 cockpit-session[26637]: pam_unix(cockpit:session): session closed for user root

I don't think I have done something ...en...strange before this happens,I just want to try web console after a fresh CentOS 8 install and I just active it using 'systemctl enable --now cockpit.socket
' after I login via ssh

**Comment by KKoukiou** [comment]
@gayhub-dev Looks like you have disabled SELinux, so the file we are trying to chcon is unlabaled, and thus the partial context can't be set.
@gayhub-dev you mentioned it's a fresh install - did you change the default SELinux mode? If so did you reboot afterwards so that the filesystem can get relabelled?

**Comment by KKoukiou** [comment]
@martinpitt would it make sense to set the full instead of the partial context when doing the chcon here? https://github.com/cockpit-project/cockpit/blob/master/src/ws/remotectl-certificate.c#L129

**Comment by martinpitt** [comment]
@KKoukiou : What does "full context" mean? Specifying `--user` and `--role` as well? The manpage doesn't really mention partial/full context, or when one would be better than the other. I'm not sure if we can always assume `system_u` and `object_r`, though -- couldn't that in principle be customized by an admin?

**Comment by martinpitt** [comment]
I just ran into exactly this error in a totally unrelated context. The cause was that the root file system was full. `chcon` should have said something like "No space left on device". Could that have been the case for you as well? (check `df -h`)

**Comment by martinpitt** [comment]
No response in a year, and insufficient information, see previous comments.
