### ISSUE TITLE
Cockpit service restarts every 2 minutes

### ISSUE THREAD

**Issue by greenpau** [cockpit-project/cockpit#13637]
Cockpit version: `196.3`
OS: RHEL8

```
$ rpm -qa | grep cockpit
cockpit-bridge-196.3-1.el8.x86_64
cockpit-system-196.3-1.el8.noarch
cockpit-ws-196.3-1.el8.x86_64
cockpit-packagekit-197.3-1.el8.noarch
subscription-manager-cockpit-1.25.17-1.el8.noarch
cockpit-196.3-1.el8.x86_64
cockpit-storaged-197.3-1.el8.noarch
```

Cockpit restarts every 2 minutes:

```
Feb 28 12:10:28 nysrv5 cockpit-ws[20801]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Feb 28 12:10:28 nysrv5 systemd[1]: Started Cockpit Web Service.
Feb 28 12:10:28 nysrv5 systemd[1]: Starting Cockpit Web Service...
Feb 28 12:08:28 nysrv5 cockpit-ws[20254]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Feb 28 12:08:28 nysrv5 systemd[1]: Started Cockpit Web Service.
Feb 28 12:08:28 nysrv5 systemd[1]: Starting Cockpit Web Service...
Feb 28 12:06:28 nysrv5 cockpit-ws[19702]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Feb 28 12:06:28 nysrv5 systemd[1]: Started Cockpit Web Service.
Feb 28 12:06:28 nysrv5 systemd[1]: Starting Cockpit Web Service...
Feb 28 12:04:28 nysrv5 cockpit-ws[18406]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Feb 28 12:04:28 nysrv5 systemd[1]: Started Cockpit Web Service.
Feb 28 12:04:28 nysrv5 systemd[1]: Starting Cockpit Web Service...
Feb 28 12:02:28 nysrv5 cockpit-ws[17919]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Feb 28 12:02:28 nysrv5 systemd[1]: Started Cockpit Web Service.
Feb 28 12:02:28 nysrv5 systemd[1]: Starting Cockpit Web Service...
Feb 28 12:00:28 nysrv5 cockpit-ws[17348]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Feb 28 12:00:28 nysrv5 systemd[1]: Started Cockpit Web Service.
Feb 28 12:00:28 nysrv5 systemd[1]: Starting Cockpit Web Service...
```

`systemd` unit file:

```
$ cat /usr/lib/systemd/system/cockpit.service
[Unit]
Description=Cockpit Web Service
Documentation=man:cockpit-ws(8)
Requires=cockpit.socket

[Service]
ExecStartPre=/usr/sbin/remotectl certificate --ensure --user=root --group=cockpit-ws --selinux-type=etc_t
ExecStart=/usr/libexec/cockpit-ws
PermissionsStartOnly=true
User=cockpit-ws
Group=cockpit-ws
```

**Comment by martinpitt** [comment]
Does this still happen with the current version? What exactly where you doing at that time? Were you using the browser at all?

**Comment by greenpau** [comment]
> Does this still happen with the current version?

@martinpitt , idk. No longer have access to these systems.

> Were you using the browser at all?

No browser.

> What exactly where you doing at that time?

There was a periodic Prometheus scrape happening. Now thinking about it, does cockpit accept protobuf scraping? How does it handle protobuf? etc. Prometheus can either scrape protobuf or plain text. What would happen if I would request ` `application/x-protobuf` from cockpit.

**Comment by martinpitt** [comment]
No, cockpit knows nothing about protobuf or exporting machine readable metrics. But Prometheus pinging the URL every two minutes sounds like a very plausible explanation what happened there. Great that you still remember the solution to that mystery :grin:

**Comment by greenpau** [comment]
@martinpitt , I meant that perhaps the cockpit web server by default IS responding to requests with `application/x-protobuf` and it crashes. If that is true, then there is a reason to be concerned.

**Comment by greenpau** [comment]
@martinpitt , specifically handlers like the one here: https://github.com/cockpit-project/cockpit/blob/9581452c3524b174fdc6e44c04e6f56bab0804ae/src/ws/cockpitwebservice.c#L396-L460

**Comment by martinpitt** [comment]
@greenpau : The log shows no crash. Just cockpit-ws stops itself after a minute if there are no open connections, to save resources.
