### ISSUE TITLE
Ubuntu Focal Fossa (development branch)  cannot use cockpit for software update. Page tips: Cannot download packages whilst offline

### ISSUE THREAD

**Issue by xgxdmx** [cockpit-project/cockpit#13630]
Ubuntu Focal Fossa (development branch)  cannot use cockpit for software update. Page tips: Cannot download packages whilst offline.
How can i solve this problem？
Thank you very much.

**Comment by martinpitt** [comment]
This is the same issue as #13002, please see that for details. Unfortunately this is between PackageKit and NetworkManager, cockpit can't influence this. If you have NM running, but it doesn't manage your primary interface, PackageKit will think it's offline.
