### ISSUE TITLE
Buttons on 'Software Updates' screen not properly themed in Cockpit 214

### ISSUE THREAD

**Issue by AdamWill** [cockpit-project/cockpit#13653]
Cockpit version: 214
OS: Fedora
Page: "Software Updates"

The [openQA tests for Cockpit 214 updates](https://openqa.fedoraproject.org/tests/overview?distri=fedora&version=31&build=Update-FEDORA-2020-22b3a559ff&groupid=2) show a failure in the `server_cockpit_updates` test. This is because the 'Check for Updates' and 'Install All Updates' buttons don't look how the test expects. This looks like a bug, not an intentional change. In 213, the buttons were nicely styled:
![cockpit213](https://user-images.githubusercontent.com/916551/75908357-d4b61300-5dfe-11ea-8945-b0084796823b.png)
In the 214 update test, they just look funny and unstyled:
![cockpit214](https://user-images.githubusercontent.com/916551/75908391-e697b600-5dfe-11ea-97e2-18b8112044f5.png)

Steps to reproduce

1. Install Cockpit
2. Run it
3. Go to 'Software Updates' page

That's all the test does, really. It *does* start from a very minimal base so may not have things that Cockpit kinda expects to be installed but which are not explicit dependencies of Cockpit or Firefox (like expected fonts, for instance) installed, but I don't think that's the cause here.

**Comment by AdamWill** [comment]
Obvious suspect here is f422c3e858a9b2327d4d6d83e9099d068929cf76 , tagging @KKoukiou ...

**Comment by KKoukiou** [comment]
Fixed by #13657
