### ISSUE TITLE
cockpit/kubernetes image not on docker hub any more

### ISSUE THREAD

**Issue by ZrytyADHD** [cockpit-project/cockpit#13654]
Hi Itry to day install okd openshift 3.11 and got error deploying registry console.
i got error:
`Failed to pull image "docker.io/cockpit/kubernetes:latest": rpc error: code = Unknown desc = repository docker.io/cockpit/kubernetes not found: does not exist or no pull access`

so i check this repo and can't find it because i got error 404 page not found.
Can anyone explain what happend. This repo i essential to run openshift properly.

**Comment by timbrd** [comment]
This is the related issue which is being discussed in the openshift project: https://github.com/openshift/openshift-ansible/issues/12115

The most recent source of the docker image, which @ZrytyADHD is refering to, can be found here: https://github.com/cockpit-project/cockpit/tree/195.6/containers/kubernetes

**Comment by ZrytyADHD** [comment]
Ok but can you re upload this image to dockerhub ?
I'm asking because openshift generate error during install cheking image avalability and also we cant install registry console properly without it.

**Comment by timbrd** [comment]
> Ok but can you re upload this image to dockerhub ?
> I'm asking because openshift generate error during install cheking image avalability and also we cant install registry console properly without it.

I'm not part of the cockpit team, so I don't have access to their [namespace on dockerhub](https://hub.docker.com/u/cockpit/).
Please follow my instructions in the other issue on using my image as a workaround.

**Comment by martinpitt** [comment]
Hello @ZrytyADHD ! Indeed I cleaned up some ancient unmaintained images on our dockerhub yesterday. The cockpit-kubernetes package [got deprecated](https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/) a year ago, and that included the cockpit/kubernetes image. It didn't get updated in over a year, and we shouldn't leave dead images around on the hub. It's also not really buildable right now, due to changes in Fedora (and Fedora 29 is EOL).

I can hammer on it for a bit to get it to build again, and put it back from the stable branch, so that it at least picks up current packages. However, this will only be a temporary solution.

The bigger question is, how did you get to use that image from dockerhub in the first place? I. e. which documentation refers to it? If you are running RHEL 7, you should use [the official registry-console RHEL container image](https://access.redhat.com/containers/#/registry.access.redhat.com/openshift3/registry-console).  You can [even do this on CentOS 7 without a subscription](https://access.redhat.com/containers/?tab=images&get-method=unauthenticated#/registry.access.redhat.com/openshift3/registry-console).

**Comment by ZrytyADHD** [comment]
Hi,
I;m not using Redhat Openshift. I install OKD Openshift which is free community edition of Openshift .
When it installing is using images from dockerhub. I can skip docker image availability of course during install or specify any other in my inventory file.

**Comment by aroute** [comment]
My OKD 3.11's registry-console pod is broken as well. How do I fix an already-installed cluster?

**Comment by aroute** [comment]
@martinpitt it seems OKD 3.11 is using the image. @timbrd's identified solution works but it would help if the original image reference is restored.

**Comment by dbiegunski** [comment]
Yes please restore the original image. 
Your cleanup should be based on how many times it was pulled within the last year and not if it was updated since last year. There's a lot of traffic coming in for that specific image I'm pretty sure.
Restore shouldn't be that hard ? I believe you guys run full backups ? I hope ?

**Comment by timbrd** [comment]
Restoring a backup should not be necessary. Just build and upload the most recent image.
The source code can be found here: https://github.com/cockpit-project/cockpit/tree/195.6/containers/kubernetes

**Comment by martinpitt** [comment]
I put it back with an appropriate deprecation warning: https://hub.docker.com/r/cockpit/kubernetes

**Comment by martinpitt** [comment]
> This repo i essential to run openshift properly.

It's not at all in principle. You don't need the cockpit container registry UI to run a workload, everything is available on the command line as well. It may be part of the OKD deployment installation scripts, of course.

**Comment by robbrucks** [comment]
```
# docker pull cockpit/kubernetes:latest
Trying to pull repository docker.io/cockpit/kubernetes ...
manifest for docker.io/cockpit/kubernetes:latest not found
```

**Comment by martinpitt** [comment]
@robbrucks : Hm, I don't know what to say. I tried it on RHEL 7 with Docker and Fedora with podman, and pulling that image works fine...

**Comment by dry4ng** [comment]
Same issue here:
```Trying to pull repository ce-docker-virtual.artifactory.osc.utdlab.com/cockpit/kubernetes ...
Pulling repository ce-docker-virtual.artifactory.osc.utdlab.com/cockpit/kubernetes
Trying to pull repository docker.io/cockpit/kubernetes ...
manifest for docker.io/cockpit/kubernetes:latest not found```

**Comment by dry4ng** [comment]
Same issue here:
```
docker pull docker.io/cockpit/kubernetes:latest
Trying to pull repository docker.io/cockpit/kubernetes ...
manifest for docker.io/cockpit/kubernetes:latest not found```

**Comment by robbrucks** [comment]
The latest supported version of Openshift OKD that is available is 3.11, which locks docker to version 1.13.1.

The 1.13.1 version of docker has problems with the tag manifest on the image and gives us the error.  Newer versions of docker don't appear to have a problem with the tag.

Essentially anyone wanting to use the cockpit image of docker hub with the supported version of openshift OKD is out of luck.

**Comment by timbrd** [comment]
> The latest supported version of Openshift OKD that is available is 3.11, which locks docker to version 1.13.1.
> 
> The 1.13.1 version of docker has problems with the tag manifest on the image and gives us the error. Newer versions of docker don't appear to have a problem with the tag.
> 
> Essentially anyone wanting to use the cockpit image of docker hub with the supported version of openshift OKD is out of luck.

Maybe it's not neccessary to use the deprecated image for much longer. Someone just opened a PR on the openshift-ansible repo which replaces the image with the supported one: https://github.com/openshift/openshift-ansible/pull/12122

**Comment by miroslawzachar** [comment]
**Solution for CentOS 7** 

_1) Remove Docker 1.13.1_ 
```
systemctl stop docker
yum remove docker 
yum remove docker-common
```

_2) Install Docker CE_
```
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker-ce
```

```
cat > /etc/docker/daemon.json <<EOF
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
EOF
```
`systemctl start docker`
 
:)

**Comment by tinu73** [comment]
> If you are running RHEL 7, you should use [the official registry-console RHEL container image](https://access.redhat.com/containers/#/registry.access.redhat.com/openshift3/registry-console). You can even do this on CentOS 7 without a subscription.

With "CentOS Linux release 7.7.1908 (Core)", i had to follow the instructions proposed by user "pepijnschildkamp" [here](https://github.com/minishift/minishift-centos-iso/issues/251#issuecomment-402999273).

> My work around is by creating an empty redhat-uep.pem file.
> ```
> cd /etc/rhsm/ca/
> touch redhat-uep.pem
> ```
```
# oc describe pod registry-console-1-mrmvp
Containers:
  registry-console:
    Image:          registry.access.redhat.com/openshift3/registry-console:v3.9
```
I installed OpenShift Origin v3.9, therefore in your ansible inventory file you have to use the "old" way to reference the image:
```
openshift_cockpit_deployer_prefix='registry.access.redhat.com/openshift3/'
openshift_cockpit_deployer_basename='registry-console'
openshift_cockpit_deployer_version='3.9'
```

**Comment by revolutionsystem** [comment]
1. Insert in /etc/ansible/hosts
openshift_disable_check=disk_availability,docker_storage,memory_availability,package_availability,package_version,docker_image_availability,package_availability

2. After install okd @miroslawzachar 
1) Remove Docker 1.13.1

systemctl stop docker
yum autoremove docker*

2) Install Docker CE

yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker-ce
cat > /etc/docker/daemon.json <<EOF
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
},
"insecure-registries" : ["docker-registry.default.svc:5000"]
EOF
systemctl start docker
