### ISSUE TITLE
Typo for password part when choosing "Workstation" as profile for Unattended virtual machine installation

### ISSUE THREAD

**Issue by cxhlunar** [cockpit-project/cockpit#13667]
Cockpit version: cockpit-machines-213-1.fc31.noarch
OS:Fedora31
Page: Overview

Typo for password part when choosing "Workstation" as profile for Unattended virtual machine installation

Steps to reproduce

1.Open the Create VM dialogue, configure as following:
Name:Fedora30
Installation Type:URL
Installation Source: https://mirrors.tuna.tsinghua.edu.cn/fedora/releases/30/Server/x86_64/os/ Operating System:Fedora 30
Check "Run unattended installation",
Profile:Workstation

The two lines under it show:
Root Password
Password for root
I think the second line should be for user account.

**Comment by cxhlunar** [comment]
![password](https://user-images.githubusercontent.com/12710195/76065248-396f9a00-5fc6-11ea-8871-8178aa0e6983.png)

**Comment by KKoukiou** [comment]
@cxhlunar  good catch, we are basically showing the currently connected user's name and allowing to create a same user inside the VM. I forgot to add a check that if the connected user is 'root', the dialog should not show the password field for root twice.
