### ISSUE TITLE
[Debian] fresh install of cockpit, gnutls_handshake failed, prevents loading dashboard

### ISSUE THREAD

**Issue by t3chn0m4g3** [cockpit-project/cockpit#13668]
Cockpit version: 214
OS: Debian (SID), x64
Page: Dashboard

Trying to login into cockpit succeeds, however the dasboard page does not load and after the while an error appears telling to check `journalctl -u cockpit`. A refresh of the page then leads to the authentication page again.

Reproduction is possible, however sometimes it does work. Please give it a couple of tries.

Relevant parts of the system log are also useful:
`journalctl -u cockpit -b`:
```
Mar 06 09:21:03 electricalsculpture systemd[1]: Starting Cockpit Web Service...
Mar 06 09:21:03 electricalsculpture systemd[1]: Started Cockpit Web Service.
Mar 06 09:21:03 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:21:04 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:21:29 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:21:29 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:21:29 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:21:29 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:22:00 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:22:01 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:22:01 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:22:13 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:22:42 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:22:42 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:22:42 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:22:42 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:22:42 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:23:12 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:23:12 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:23:12 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:23:43 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:25:36 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:25:37 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:25:37 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:25:49 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:25:49 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:25:49 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:25:49 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:25:49 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:25:50 electricalsculpture cockpit-tls[5599]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:29:32 electricalsculpture systemd[1]: Stopping Cockpit Web Service...
Mar 06 09:29:32 electricalsculpture systemd[1]: cockpit.service: Succeeded.
Mar 06 09:29:32 electricalsculpture systemd[1]: Stopped Cockpit Web Service.
Mar 06 09:29:32 electricalsculpture systemd[1]: Starting Cockpit Web Service...
Mar 06 09:29:32 electricalsculpture systemd[1]: Started Cockpit Web Service.
Mar 06 09:29:33 electricalsculpture cockpit-tls[30891]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:31:40 electricalsculpture systemd[1]: cockpit.service: Succeeded.
Mar 06 09:41:39 electricalsculpture systemd[1]: Starting Cockpit Web Service...
Mar 06 09:41:39 electricalsculpture systemd[1]: Started Cockpit Web Service.
Mar 06 09:41:39 electricalsculpture cockpit-tls[42073]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:41:40 electricalsculpture cockpit-tls[42073]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:41:40 electricalsculpture cockpit-tls[42073]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:42:03 electricalsculpture cockpit-tls[42073]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:42:03 electricalsculpture cockpit-tls[42073]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:42:03 electricalsculpture cockpit-tls[42073]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:42:03 electricalsculpture cockpit-tls[42073]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:42:03 electricalsculpture cockpit-tls[42073]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 06 09:42:33 electricalsculpture cockpit-tls[42073]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.

```

`cockpit-ws` complains about a missing certificate, which is odd, expectation is the default certificate should be generated upon installation of the cockpit package:
```
Mar 06 09:21:04 electricalsculpture systemd[1]: Started Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
Mar 06 09:21:04 electricalsculpture cockpit-ws[5604]: cockpit-ws: Failed to open certificate file /run/cockpit/tls/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: No such file or directory
Mar 06 09:21:08 electricalsculpture cockpit-ws[5604]: cockpit-ws: Failed to open certificate file /run/cockpit/tls/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: No such file or directory
Mar 06 09:21:28 electricalsculpture cockpit-ws[5604]: cockpit-ws: Failed to open certificate file /run/cockpit/tls/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: No such file or directory
```

**Comment by wolffstarr** [comment]
Also getting this on Debian Buster with v217 of Cockpit from buster-backports. Effectively the same logs and behavior as @t3chn0m4g3 reported.

**Comment by thiagolinhares** [comment]
Same here.
Centos 8
Error happens after login-attempt
cockpit-ws[398557]: cockpit-ws: Failed to open certificate file /run/cockpit/tls/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: No such file or directory
cockpit-session[398916]: pam_ssh_add: Failed adding some keys

**Comment by Diak** [comment]
Same problem here : 

# cat /etc/redhat-release
CentOS Linux release 8.2.2004 (Core)

# dnf info cockpit
Last metadata expiration check: 2:41:59 ago on Sat 29 Aug 2020 08:16:04 PM CEST.
Installed Packages
Name         : cockpit
Version      : 211.3
Release      : 1.el8
Architecture : x86_64
Size         : 53 k
Source       : cockpit-211.3-1.el8.src.rpm
Repository   : @System
From repo    : BaseOS
Summary      : Web Console for Linux servers
URL          : https://cockpit-project.org/
License      : LGPLv2+
Description  : The Cockpit Web Console enables users to administer GNU/Linux servers using a
             : web browser.
             :
             : It offers network configuration, log inspection, diagnostic reports, SELinux
             : troubleshooting, interactive command-line sessions, and more.

**Comment by digitalformula** [comment]
Same issue here after installing `cockpit-226`.  Worked fine with `cockpit-211`.

I'm on CentOS 8.2.2004, cockpit-226 built from source.  Issue is present on CentOS 8.2.2004, doesn't happen on Ubuntu 20.04.

**Comment by XenoBIT78** [comment]
New Install of ubuntuserver 20.04.1 and cockpit version 215-1

cockpit-tls[2718]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.

**Comment by tophee** [comment]
I am also getting the behaviour reported in the OP on OpenMediaVault 5 (Debian 10.6)

**Comment by XenoBIT78** [comment]
make your own certificates from lets encrypt using acme.sh or certbot or other...   and use certs with cockpit..

**Comment by snakehead007** [comment]
Im also getting the same error logs on ubuntu 20.04

**Comment by Alion548** [comment]
Im also getting the same error logs on Fedora 33

**Comment by AlexH0661** [comment]
Also getting this error on RHEL8.2

**Comment by eringuet** [comment]
I'm trying to figure out where that string is coming from since it's the same for all of us:
/run/cockpit/tls/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
I would expect cockpit-tls to use /run/cockpit/tls and nothing else. 

Documentation says:

> The cockpit-tls program expects the RUNTIME_DIRECTORY environment variable to be set to an empty directory (preferably in /run/) that is only accessible by the system user under which it is running. This contains the Unix sockets for communicating with the cockpit-ws instances, and in the future, state information about client certificates. This variable is normally set by the cockpit.service systemd unit.

cockpit.service on ubuntu:
```
[Service]
RuntimeDirectory=cockpit/tls
# systemd ≥ 241 sets this automatically
Environment=RUNTIME_DIRECTORY=/run/cockpit/tls
ExecStartPre=/usr/sbin/remotectl certificate --ensure --user=root --group=cockpit-ws --selinux-type=
ExecStart=/usr/lib/cockpit/cockpit-tls
PermissionsStartOnly=true
User=cockpit-ws
Group=cockpit-ws
```
looks like the service wants to run as cockpit-ws but the folder is owned by root. 

chown -R cockpit-ws:cockpit-ws /run/cockpit allows me to login and the service seems to work.

**Comment by snakehead007** [comment]
> looks like the service wants to run as cockpit-ws but the folder is owned by root.
> 
> chown -R cockpit-ws:cockpit-ws /run/cockpit allows me to login and the service seems to work.
> 
> Not sure what that means bug-wise but that's all I can contribute with my skill level.

I will try that out! huge help, if it will work. thanks!

**Comment by gstlouisgit** [comment]
the above from @snakehead007 did not work for me.  IF I refresh several times after login I can see the UI but when clicking anywhere nothing shows up.
journalctl still says :
Dec 02 15:54:14 mainoffice systemd[1]: Starting Cockpit motd updater service...
Dec 02 15:54:14 mainoffice systemd[1]: Starting Cockpit Web Service...
Dec 02 15:54:14 mainoffice systemd[1]: Started Cockpit Web Service.
Dec 02 15:54:14 mainoffice systemd[1]: Started Cockpit motd updater service.
Dec 02 15:54:19 mainoffice cockpit-tls[4555]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Dec 02 15:54:21 mainoffice cockpit-ws[4535]: cockpit-ws: Failed to open certificate file /run/cockpit/tls/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: No such file or directory
Dec 02 15:54:21 mainoffice cockpit-tls[4555]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.

on centos 8 4.18.0-193.28.1.el8_2.x86_64

**Comment by sharkyP** [comment]
i'm also having the same issue on a new install

**Comment by LordSimal** [comment]
I got it working with an NGINX Reverse proxy.
Basically follow https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-nginx

The only MAIN difference I changed is, that I added 
```
AllowUnencrypted = true
```
to the `/etc/cockpit/cockpit.conf` and added a HTTPS Redirect via NGINX 
Seems like the HTTPS Redirect from Cockpit doesnt seem to work internally when there is no valid certificate present in `/etc/cockpit/ws-certs.d`

**Comment by rcproam** [comment]
Same issue here. New install of cockpit from backports on Debian 10.

Attempting to login using Firefox hangs with a spinning circle for like 10 seconds then just displays a page that reads:
"! disconnected"

Journal output below was generated after modifying ownership for the /run/cockpit as @eringuet  suggested (which unfortunately did not resolve the issue).

# uname -a
Linux svr-lf-nas1 5.10.0-0.bpo.3-amd64 #1 SMP Debian 5.10.13-1~bpo10+1 (2021-02-11) x86_64 GNU/Linux
# dpkg -l | grep cockpit
ii  cockpit                              237-1~bpo10+1                       all          Web Console for Linux servers
ii  cockpit-bridge                       237-1~bpo10+1                       amd64        Cockpit bridge server-side component
ii  cockpit-networkmanager               237-1~bpo10+1                       all          Cockpit user interface for networking
ii  cockpit-packagekit                   237-1~bpo10+1                       all          Cockpit user interface for packages
ii  cockpit-storaged                     237-1~bpo10+1                       all          Cockpit user interface for storage
ii  cockpit-system                       237-1~bpo10+1                       all          Cockpit admin interface for a system
ii  cockpit-ws                           237-1~bpo10+1                       amd64        Cockpit Web Service

# journalctl -u cockpit
-- Journal begins at Mon 2020-12-14 09:46:57 CST, ends at Fri 2021-03-26 23:33:33 CDT. --
Mar 26 22:46:06 svr-lf-nas1 systemd[1]: Starting Cockpit Web Service...
Mar 26 22:46:06 svr-lf-nas1 systemd[1]: Started Cockpit Web Service.
Mar 26 22:46:06 svr-lf-nas1 cockpit-tls[39745]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Mar 26 22:49:14 svr-lf-nas1 systemd[1]: cockpit.service: Succeeded.
Mar 26 22:49:37 svr-lf-nas1 systemd[1]: Starting Cockpit Web Service...
Mar 26 22:49:37 svr-lf-nas1 systemd[1]: Started Cockpit Web Service.
Mar 26 22:50:31 svr-lf-nas1 systemd[1]: Stopping Cockpit Web Service...
Mar 26 22:50:31 svr-lf-nas1 systemd[1]: cockpit.service: Succeeded.
Mar 26 22:50:31 svr-lf-nas1 systemd[1]: Stopped Cockpit Web Service.
Mar 26 22:50:31 svr-lf-nas1 systemd[1]: Starting Cockpit Web Service...
Mar 26 22:50:31 svr-lf-nas1 systemd[1]: Started Cockpit Web Service.
Mar 26 22:52:58 svr-lf-nas1 systemd[1]: cockpit.service: Succeeded.
Mar 26 22:53:11 svr-lf-nas1 systemd[1]: Starting Cockpit Web Service...
Mar 26 22:53:11 svr-lf-nas1 systemd[1]: Started Cockpit Web Service.
Mar 26 22:55:38 svr-lf-nas1 systemd[1]: cockpit.service: Succeeded.
Mar 26 22:56:55 svr-lf-nas1 systemd[1]: Starting Cockpit Web Service...
Mar 26 22:56:55 svr-lf-nas1 systemd[1]: Started Cockpit Web Service.
Mar 26 23:06:40 svr-lf-nas1 systemd[1]: cockpit.service: Succeeded.
Mar 26 23:15:31 svr-lf-nas1 systemd[1]: Starting Cockpit Web Service...
Mar 26 23:15:31 svr-lf-nas1 systemd[1]: Started Cockpit Web Service.
Mar 26 23:18:06 svr-lf-nas1 systemd[1]: cockpit.service: Succeeded.
Mar 26 23:25:59 svr-lf-nas1 systemd[1]: Starting Cockpit Web Service...
Mar 26 23:25:59 svr-lf-nas1 systemd[1]: Started Cockpit Web Service.
Mar 26 23:30:28 svr-lf-nas1 systemd[1]: cockpit.service: Succeeded.
Mar 26 23:30:52 svr-lf-nas1 systemd[1]: Starting Cockpit Web Service...
Mar 26 23:30:52 svr-lf-nas1 systemd[1]: Started Cockpit Web Service.
Mar 26 23:33:33 svr-lf-nas1 systemd[1]: cockpit.service: Succeeded.

**Comment by martinpitt** [comment]
I'm afraid this bug report is not useful. The "gnutls_handshake failed" just means that the browser aborted the connection as it didn't like the certificate, presumably because it is a self-signed one and you need to accept it first. This is tracked in issue #14896.

The "Failed to open certificate file" was a bogus message that got fixed recently in commit 3c8823d99169 (cockpit 240).

Finally, from the original report, the Dashboard page is gone since [cockpit 234](https://cockpit-project.org/blog/cockpit-234.html).

So there is nothing left to examine here.

**Comment by MurzNN** [comment]
Yeah, this awesome trick do the thing:
```
chown -R cockpit-ws:cockpit-ws /run/cockpit
```
Thanks!

**Comment by 0x30c4** [comment]
```
chown -R cockpit-ws:cockpit-ws /run/cockpit 
```
Isn't working for me. :/

**Comment by beatquantum** [comment]
SOLVED: For my limited usage (one primary server), the following solution works without using Nginx as frontend.

Step1: Obtain Letsencrypt certificate for your domain of choice (say example.com), I use certbot.

Step2: Create symbolic links to the Letsencrypt certificate as follows (as root)
PS: You will note that I have changed the extensions .pem to .crt and .key as needed by Cockpit.

ln -s /etc/letsencrypt/live/example.com/cert.pem /etc/cockpit/ws-certs.d/example.com.crt 
ln -s /etc/letsencrypt/live/soc247.cloud/privkey.pem /etc/cockpit/ws-certs.d/example.com.key  

Step 3: Get rid of the self signed certificates which start with 0.
PS: I just keep such stuff in a dedicated folder (rubbish bin) called /movedfiles

mkdir /movedfiles
mv /etc/cockpit/ws-certs.d/0* /movedfiles

Step 4: Restart cockpit and check its status

service cockpit restart && service cockpit status

PS: The most important line shows success as follows:

Process: 5775 ExecStartPre=/usr/lib/cockpit/cockpit-certificate-ensure --for-cockpit-tls (code=exited, status=0/SUCCESS)

Step 5: You can access Cockpit using https and the example.com domain name on your chosen port (e.g. 9090).
PS: Please do not use IP address here as (normally) the TLS certificate is for the domain name and not the IP address.

https://example.com:9090

PS: I do not know if this will work for secondary servers, as I have installed Cockpit only on one server.

Conclusion: The use of a proper TLS certificate will avoid the above TLS error.

**Comment by lonelyor** [comment]
>
这解决了我的问题

**Comment by lonelyor** [comment]
> SOLVED: For my limited usage (one primary server), the following solution works without using Nginx as frontend.
> 
> Step1: Obtain Letsencrypt certificate for your domain of choice (say example.com), I use certbot.
> 
> Step2: Create symbolic links to the Letsencrypt certificate as follows (as root) PS: You will note that I have changed the extensions .pem to .crt and .key as needed by Cockpit.
> 
> ln -s /etc/letsencrypt/live/example.com/cert.pem /etc/cockpit/ws-certs.d/example.com.crt ln -s /etc/letsencrypt/live/soc247.cloud/privkey.pem /etc/cockpit/ws-certs.d/example.com.key
> 
> Step 3: Get rid of the self signed certificates which start with 0. PS: I just keep such stuff in a dedicated folder (rubbish bin) called /movedfiles
> 
> mkdir /movedfiles mv /etc/cockpit/ws-certs.d/0* /movedfiles
> 
> Step 4: Restart cockpit and check its status
> 
> service cockpit restart && service cockpit status
> 
> PS: The most important line shows success as follows:
> 
> Process: 5775 ExecStartPre=/usr/lib/cockpit/cockpit-certificate-ensure --for-cockpit-tls (code=exited, status=0/SUCCESS)
> 
> Step 5: You can access Cockpit using https and the example.com domain name on your chosen port (e.g. 9090). PS: Please do not use IP address here as (normally) the TLS certificate is for the domain name and not the IP address.
> 
> https://example.com:9090
> 
> PS: I do not know if this will work for secondary servers, as I have installed Cockpit only on one server.
> 
> Conclusion: The use of a proper TLS certificate will avoid the above TLS error.

这解决了我的问题。感谢

**Comment by 0x30c4** [comment]
@lonelyor 欢迎
