### ISSUE TITLE
Collections can't start with number

### ISSUE THREAD

**Issue by OneAndOnlyOdin** [cockpit-project/cockpit#13676]
Cockpit version: 0.10.0
OS: Ubuntu 18.04 with official docker image
Page: Collections

Collections apparently not working with a number at the start.

Steps to reproduce

1. Create a new collection starting with a number instead of a string character such as "360Scene"
2. Open the collection
3. A colorful spinner is shown and two new errors are logged in the browser console

![Bildschirmfoto 2020-03-07 um 22 35 20](https://user-images.githubusercontent.com/50045535/76152834-92255c80-60c4-11ea-9236-1f7de13386f1.png)

Proposed solutions:
- Block the user from using a collection name starting with a number
- Fix the broken database query

**Comment by leomoty** [comment]
I think you openend this issue against the wrong project. This one is related to: https://cockpit-project.org/

From basic googling, this should be the right project: https://github.com/agentejo/cockpit

**Comment by OneAndOnlyOdin** [comment]
Yep you're right sorry.
