### ISSUE TITLE
cockpit-bridge mutilple processes memory consumptions over 1Gb

### ISSUE THREAD

**Issue by nodje** [cockpit-project/cockpit#13689]
Cockpit version: 212
OS: Debian/Fedora

cockpit-bridge processes very frequently add up to a very high RAM consumption of over 1Gb.

In any case, i regularly get 3 cockpit-bridge processes on different monitored machine, and it takes the best of their available RAM. I have to just `killall cockpit-bridge` regularly to reclaim it.

They must grow over time, and it feels like a memory leak really, as when I killall them and restart a connection from the cockpit-ws host the RAM consumption is very low.

FYI cockpit-pcp is enabled on the monitored machine.

HTH

**Comment by aeastw** [comment]
Cockpit version: 212
OS: Debian

I also see this issue, as described above, cockpit-bridge memory usage seems to grow over time. Requires kill and restart connection to free.

**Comment by martinpitt** [comment]
This does sound serious indeed, but I'm afraid we need some more information for this to become actionable and reproducible. Please describe your setup more specifically, i. e. how many machines are involved (local or ssh login over dashboard?), which pages you have open on each of them, how fast you see the memory growing ("over time" == minutes, hours, days?), do you get regular journal messages from cockpit, etc.

**Comment by nodje** [comment]
ok, my setup is pretty basic and straightforward I believe, so hopefully it'll help identifying what is 
happening.

I have cockpit-ws setup on one machine, fedora, and it monitors 4 other machines (all debian).
They are all part of a realm, provided by a freeipa instance (not monitored).

I connect to the FE provided by the fedora cockpit-ws from 2 machines,
and basically use it to check resource consumption, sometimes to apply security updates.
So cockpit-pcp is enabled on all 4 debians.

Now the memory leaks seem to happen within ~12hours. Hard to be more precise than this atm.

I did `killall cockpit-bridge` on a postgres machine yesterday when I created this issue, and it's now using up ~1Gb of RAM again.
I did only one unique login to cockpit-ws and accessed this postgres machine to disaply its resource consumption.

Here's the screenshot of an htop showing the culprit.
These belong to the ssh user used to connect from cockpit-ws to "monitored"

![Screenshot 2020-03-10 at 11 18 15](https://user-images.githubusercontent.com/75604/76303148-8ce13100-62c1-11ea-8999-5ee836f265ec.png)

Note that the `cockpit-bridge --privileged` is owned by root and doesn't consume as much memory.
`cockpit-pcp` processes also are quite reasonable in ram consumption, never had to restart them.

This happens on different machines at different time. Not systematic.

**Comment by nodje** [comment]
Also, as an aside, it happens that multiple cockpit-bridge parent processes are created:
![Screenshot 2020-03-10 at 14 24 11](https://user-images.githubusercontent.com/75604/76316976-b0b17080-62db-11ea-8c60-608ca727a754.png)
`killall` in this case is also the simplest way to clean up

**Comment by nodje** [comment]
Same thing again today, using even more memory.
<img width="577" alt="Screenshot 2020-03-11 at 09 58 37" src="https://user-images.githubusercontent.com/75604/76399514-01c67080-637f-11ea-9ebd-dea192a591c0.png">

So def. happening within a few hours. I'd be hard-pressed to find a better way to monitor this. Any idea welcome.

**Comment by martinpitt** [comment]
Does this still happen with the current version? Can you please disable PCP or uninstall cockpit-pcp (whichever is less intrusive), and check if it happens without that as well?

**Comment by martinpitt** [comment]
If this still happens, would it be possible to get ssh access (freshly created user is enough, doesn't need sudo) on your system to debug this?

**Comment by marusak** [comment]
No reply in ~2 years, closing
