### ISSUE TITLE
Add a timeout setting on the frontend

### ISSUE THREAD

**Issue by nodje** [cockpit-project/cockpit#13691]
Would be really handy to be able to keep the dashboard open, maybe even to be able to disable automatic logout.

**Comment by marusak** [comment]
> Would be really handy to be able to keep the dashboard open, maybe even to be able to disable automatic logout.

Are you referring to the fact that you get logged out after 15minutes of inactivity? If so, then this is easy to disable: 
<hr>

You can configure the timeout, in minutes, in /etc/cockpit/cockpit.conf. For example, this will disable automatic logouts completely:
```
[Session]
IdleTimeout=0
```

**Comment by nodje** [comment]
Thank You! 
I'm able to find it in the doc now that you pointed it to me. For some reason I wasn't able to before.
