### ISSUE TITLE
Cannot access Web UI after fresh install

### ISSUE THREAD

**Issue by jarodwsams** [cockpit-project/cockpit#13709]
Cockpit version: stable 1.003
OS: Rasbpian Buster (Feb 2020 Update)

I just installed Cockpit about 12 hours ago. I was able to access the login screen at first, but now am not able to. In my browser I get a message about an unusable security cert (not an invalid one that can be excepted, but an unusable one, see screenshot). When I check `sudo systemctl status cockpit` I see an error message about a fatal TLS alert (2nd screenshot). I have tried rebooting the host system _and_ uninstalling/reinstalling.

Error message in Browser (MS Edge Chromium, but also get the same in Chrome)
![image](https://user-images.githubusercontent.com/22972834/76582408-2cf6b000-64a4-11ea-8fdb-826e3822f154.png)

systemctl status messages
![image](https://user-images.githubusercontent.com/22972834/76582467-4f88c900-64a4-11ea-8e10-eed2b8567947.png)

<-- Relevant parts of the system log -->
![image](https://user-images.githubusercontent.com/22972834/76582630-d9d12d00-64a4-11ea-8cfc-5d5b087e595f.png)

**Comment by darkworks** [comment]
by default no SSL certificates are installed you can just click  visit any way button on the page to visit it

**Comment by jarodwsams** [comment]
As you can see from the screenshot from the browser, there is no "visit anyway" link to click. That's the first thing I looked for.

**Comment by darkworks** [comment]
> As you can see from the screenshot from the browser, there is no "visit anyway" link to click. That's the first thing I looked for.

try in chrome or firefox , i have not used edge ,

**Comment by gamersalpha** [comment]
Hello same problem here, i have to use edge to open cockopit

how to get a certificat working please

**Comment by c0dehunter** [comment]
Same problem. This seems like a really basic thing in 2020, but I am unable to find a straightforward way to make this work. I use LetsEncrypt for https.

**Comment by martinpitt** [comment]
The screenshots show that you should have a certificate /etc/cockpit/ws-certs.d/0-self-signed.cert. Do you get a reasonable output with

    sudo openssl x509 -in /etc/cockpit/ws-certs.d/0-self-signed.cert -text

Maybe something went wrong with certificate generation, or just your newer version of Edge complains about something in the certificate. We may need to generate it differently. Unfortunately the [windows-10 image that we use](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) unfortunately only has a really old (version 16) and unpgradable Edge, I don't have access to a newer one. If you have an official domain name, you can of course plug in a LetsEncrypt or other certificate, see the [documentation](https://cockpit-project.org/guide/latest/https.html#https-certificates) for details.

**Comment by teunzwart** [comment]
If you are on a trusted network, you can type `thisisunsafe` in Chrome to bypass the warning.

**Comment by martinpitt** [comment]
No reply in 8 months, and not sufficient information.

**Comment by z900collector** [comment]
Surprisingly this is still an issue on "Brave" web browser...

[]# openssl x509 -in /etc/cockpit/ws-certs.d/0-self-signed.cert -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 5706414667059121122 (0x4f3141e7e3234be2)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=f0b16e90a8fc4be1a6d8a2267bb8fd08, OU=ca-5566042429254433039, CN=X-SID-TEST
        Validity
            Not Before: Dec 10 01:09:10 2025 GMT
            Not After : Jan  9 01:09:10 2027 GMT
        Subject: C=US, O=f0b16e90a8fc4be1a6d8a2267bb8fd08, CN=X-SID-TEST
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
......
AnC7NPAdaDIxEgzjnRBQkTJc27fGPW9DZJru5cJpt2Ld1oMZ8FUOQJPHutElIVse
/ExA8Rvcuf67CAMj
-----END CERTIFICATE-----
](url)
