### ISSUE TITLE
desktop: Support sandbox with webkit_web_context_set_sandbox_enabled()

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#13700]
Our Python-based WebKit desktop browser should probably opt-in to the WebKit sandbox.

The call looks like:

```
webkit_web_context_set_sandbox_enabled()
```

API doc: https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebContext.html#webkit-web-context-set-sandbox-enabled

I'm assuming it's probably supported in Python too. Right?

Mentioned at the bottom of https://blogs.gnome.org/mcatanzaro/2020/03/11/epiphany-3-36-and-webkitgtk-2-28/

**Comment by martinpitt** [comment]
Indeed this API can be accessed through Python. I don't think it will actually buy us much, as we already run the browser inside a new namespace, and thus it's rather well isolated. But it can't hurt, so I sent PR #15728 for that. Thanks for pointing out!
