### ISSUE TITLE
cockpit VNC support 

### ISSUE THREAD

**Issue by darkworks** [cockpit-project/cockpit#13718]
Am wondering can we have VNC  feature in cockpit , i think it will be good to have VNC feature because from VNC we can operate virtualization software like proxmox to deploy child servers

Implementation : i think it can be easily implemented we just need to add tight vnc or other vnc app 
to cockpit installer so that's its installed on system during cockpit installation , we can make it even optional like provide option during installation to have vnc feature enable or not . 

https://novnc.com/info.html

thanks

**Comment by najcardboyz** [comment]
i like that to :D

**Comment by martinpitt** [comment]
Cockpit's Machines page does have support for VNC, for inline viewing of libvirt VMs. If you meant anything else, that's outside of what we want to provide in the cockpit project itself -- of course anyone should feel free to [build their own page](https://cockpit-project.org/blog/cockpit-starter-kit.html) with what they want.
