### ISSUE TITLE
Debian/Ubuntu: Tighten version dependencies of cockpit metapackage

### ISSUE THREAD

**Issue by CSnipper** [cockpit-project/cockpit#13716]
Cockpit version: 188-1
OS: Debian
Page: ZFS (cockpit-zfs-manager)

How can I download newer version than 188-1 in Debian?

**Comment by martinpitt** [comment]
Version 213 is in stable-backports (see [package overview](https://tracker.debian.org/pkg/cockpit)). See https://backports.debian.org/Instructions/ for instructions how to use them.

**Comment by CSnipper** [comment]
Installed and running, still the same :(

`cockpit is already the newest version (213-1~bpo10+1).`

**Comment by martinpitt** [comment]
@CSnipper : Possibly you only upgraded the "cockpit" metapackage, but not the "real" ones like cockpit-system, cockpit-bridge, cockpit-ws? Check `dpkg -l | grep cockpit`.

**Comment by martinpitt** [comment]
This is something that happens fairly often. I suppose we could tighten the dependencies of the metapackage, this works for Debian/Ubuntu (it doesn't work for RHEL due to technical reasons).
