### ISSUE TITLE
Active Directory user's login failed with 'Permission denied'

### ISSUE THREAD

**Issue by Peter-A-Tech** [cockpit-project/cockpit#13726]
Cockpit version: 196.3
OS: CentOS Linux release 8.1.1911

The cockpit is successfully joined to the AD domain. The AD user now in the group wheel (and for the experiment in the group cockpit-ws) The user can log in via ssh and run sudo, but when tries to log in via cockpit web the 'Wrong user name or password' message is shown. I run the 'semanage permissive -a cockpit_session_t' command but it didn't change. I switched on the debug mode, Here is the relevant section from the journalctl:

cockpit-ws[30041]: [34B blob data]
cockpit-ws[30041]: received unknown/invalid credential cookie
cockpit-ws[30041]: spawning /usr/libexec/cockpit-session 
cockpit-ws[30041]: received authorize challenge
cockpit-session[30217]: pam_sepermit(cockpit:auth): Parsing config file: /etc/security/sepermit.conf
cockpit-session[30217]: pam_sepermit(cockpit:auth): Enforcing mode, access will be allowed on match 
cockpit-session[30217]: pam_sepermit(cockpit:auth): sepermit_match returned: -1
cockpit-session[30217]: pam_sss(cockpit:auth): authentication success; logname= uid=0 euid=0 tty= ruser= rhost=ip_address user=ad_user
cockpit-session[30217]: pam_selinux(cockpit:session): Open Session
cockpit-session[30217]: pam_selinux(cockpit:session): Open Session
cockpit-session[30217]: pam_selinux(cockpit:session): Username= ad_user SELinux User= unconfined_u Level= s0-s0:c0.c1023
cockpit-session[30217]: pam_selinux(cockpit:session): Selected Security Context unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
cockpit-session[30217]: pam_selinux(cockpit:session): Checking if unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 mls range valid for  unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
cockpit-session[30217]: pam_selinux(cockpit:session): Set executable context: [] -> [unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023]
cockpit-session[30217]: pam_selinux(cockpit:session): Set key creation context to unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
cockpit-session[30217]: pam_ssh_add: Identity added: /home/ad_user/.ssh/id_rsa (ad_user@cockpit-server)
cockpit-session[30217]: pam_unix(cockpit:session): session opened for user ad_user by (uid=0)
cockpit-ws[30041]: 3: **Permission denied.**
cockpit-session[30217]: pam_selinux(cockpit:session): Close Session
cockpit-session[30217]: pam_selinux(cockpit:session): Restore executable context: [unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023] -> []
cockpit-session[30217]: pam_selinux(cockpit:session): Close Session
cockpit-session[30217]: pam_unix(cockpit:session): session closed for user ad_user
cockpit-ws[30041]: **cockpit-session: authentication process exited: 256; problem access-denied**
cockpit-ws[30041]: web service closing
cockpit-ws[30041]: auth is idle

It seems that the authentication succeeded, but the opening session fails with 'Permission denied.' and at the end of the process can be seen the 'cockpit-session: authentication process exited: 256; problem access-denied'.
What permission (SElinux, file, group membership) should I set in order the AD user can log in via cockpit web?

**Comment by Peter-A-Tech** [comment]
Here is the solution of the issue:
In the  /etc/sssd/sssd.conf file must write the following:

default_shell = /bin/bash
override_shell = /bin/bash

and recommended:
override_homedir = /home/%u
fallback_homedir = /home/%u

Cockpit works only with /bin/bash. Users with other shells cannot log in.

**Comment by martinpitt** [comment]
@Peter-A-Tech : That's not true in general, e. g. zsh or trec work as well. Which particular shell were these users using before?

**Comment by Peter-A-Tech** [comment]
> 
> 
> @Peter-A-Tech : That's not true in general, e. g. zsh or trec work as well. Which particular shell were these users using before?

The shell is: tcsh The value of the attribute loginShell in the AD is: /bin/tcsh (for the sake of the old members of the staff :-) ). I checked: the /bin/tcsh exists and works in CentOS 8, but when I tried to login to cockpit I got the error message described in this post. After having set the default_shell and override_shell in the file  /etc/sssd/sssd.conf (as it written in the second post) I was able to login successfully. I didn't try whether with other shell I can login.

**Comment by martinpitt** [comment]
@Peter-A-Tech : FTR, tcsh failure is issue #14060, and we are currently working on fixing that.

**Comment by jonathanbrunath-tc** [comment]
> Here is the solution of the issue: In the /etc/sssd/sssd.conf file must write the following:
> 
> default_shell = /bin/bash override_shell = /bin/bash
> 
> and recommended: override_homedir = /home/%u fallback_homedir = /home/%u
> 
> Cockpit works only with /bin/bash. Users with other shells cannot log in.

This worked like a treat for me, thanks for the tip! I could not for the life of me figure out why cockpit was giving a permission denied error when my account was definitely working everywhere else on the host in question, and it was working right before I did an update. be default my user account was set to use /bin/sh for the shell, which was something I meant to fix anyways but didnt think would affect cockpit logins

**Comment by martinpitt** [comment]
@jonathanbrunath-tc : What is /bin/sh for you? It normally is a symlink to bash, so it should not make a difference.

**Comment by jonathanbrunath-tc** [comment]
> @jonathanbrunath-tc : What is /bin/sh for you? It normally is a symlink to bash, so it should not make a difference.

That does seem to be the case on my IPA server setup, but setting the default_shell to /bin/bash in sssd.conf did fix the cockpit login issue for AD users for me. Interestingly if I switch to 'sh' it does give a different prompt than with bash, not sure why this is though

**Comment by martinpitt** [comment]
That's normal -- If bash gets invoked as sh, it behaves more like POSIX shell, reads different config files, and has different prompt defaults.
