### ISSUE TITLE
cent8 cockpit webpage couldn't open on chrome ver:80 on mac os 

### ISSUE THREAD

**Issue by bighunter513** [cockpit-project/cockpit#13743]
Page: 

centos 8 with cockpit enabled, 
when opened on mac os chrome 80, it says :
  Your connection isn't private connection 
   NET::ERR_CERT_INVALID

**Comment by victor-ponamariov** [comment]
Same here

**Comment by martinpitt** [comment]
This is expected -- you have to accept the self-signed certificate first, or [install your own](https://cockpit-project.org/guide/latest/https.html#https-certificates) (from LetsEncrypt, for example).
