### ISSUE TITLE
Use USB as disks for RAID

### ISSUE THREAD

**Issue by dassader** [cockpit-project/cockpit#13760]
Please add the possibility to use USB as Disk for raid
Yes, I know that it's not safe
But I don't have sata ports in my device and I wanna just create the raid 0 for speed :)
Cockpit can find raid but not add new disks when I use the mdadm in console

**Comment by marusak** [comment]
(I assume you are talking about usb stick)
You can surely use usb stick to create raid on. You just need to have there free space that is not part of other fs.
![myraid](https://user-images.githubusercontent.com/12330670/77141922-d0385e00-6a7e-11ea-9aa1-39ec00844564.png)

Or I missed the point here?

**Comment by dassader** [comment]
Sorry, it's my bad 
I tested with virtualbox and have the wrong result
I just tested in my real device and it's working
