### ISSUE TITLE
FW: Mosh

### ISSUE THREAD

**Issue by jtagcat** [cockpit-project/cockpit#13767]
Page:  Network/Firewall

By default, mosh uses a UDP ports between 60000 and 61000.
One port allows one connected user, so allowing say 10 (60000-60010), you could have 11 users connected.
I would suggest 60000-60002 UDP, allowing 3 concurrent users.

It would also be nice, if this rule was automagically enabled when mosh package is detected.

**Comment by marusak** [comment]
> I would suggest 60000-60002 UDP, allowing 3 concurrent users.

I cannot see how this is RFE in Cockpit. Cockpit firewall page shows firewalls setting from the host. It also enables users to open new services/ports - the same way you can do it on commandline.

> It would also be nice, if this rule was automagically enabled when mosh package is detected.

This is not something, that Cockpit would go along with. We really don't want to introduce this kind of behaviour.
