### ISSUE TITLE
rework the journal layout

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1378]
@LHinson have been working on a reworked Journal layout.

![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/journal/Journal_withNotes.png)

**Comment by dperpeet** [comment]
After some consideration, I like that warnings/errors don't use colors.
What if we work with shade/opacity? The exclamation icon could be lighter for warnings, darker for errors. I have no idea if this looks good or if it's enough to filter. Or use a different icon for errors?

**Comment by andreasn** [comment]
Updated the mockup above to differentiate between warnings and errors. Did the error as a red icon to make it stand out even more than the warning and allows to differentiate them with both shape and color .

**Comment by KKoukiou** [comment]
This has being obsoleted by the recent refactoring of the logs page.
