### ISSUE TITLE
failed to update connection: settings plugin does not support modifying connections

### ISSUE THREAD

**Issue by lachlan-00** [cockpit-project/cockpit#13780]
Cockpit version: Version 214.1. 
OS: debian
Page: "Network"

I am unable to set the interface on a new server. When trying to update my settings i get this error message.

I've never seen this inside cockpit but i'm assuming it's a config issue with my server not allowing the interface to change?

![image](https://user-images.githubusercontent.com/1305249/77396691-e97b3a80-6def-11ea-9564-d3486702aa59.png)

**Comment by lachlan-00** [comment]
it's network manager no cockpit

**Comment by cornop** [comment]
Out of curiosity, how did  you end up fixing this issue?

**Comment by lachlan-00** [comment]
> Out of curiosity, how did you end up fixing this issue?

it was a while ago but i think this was on a system that didn't have managed=true to allow configuring the interfaces
![image](https://user-images.githubusercontent.com/1305249/158129011-2a534413-2b77-4fc1-8332-306133b5b091.png)
