### ISSUE TITLE
link from journal detail to service page?

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1379]
So I was having issues with mt-daapd today. It spit out a number of errors to the journal.
When looking at one of the journal entrys, I was wondering about the _current_ state of the service, like "is it actually running right now?"

In this case it would be handy with a link to the service in question.

**Comment by andreasn** [comment]
![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/journal/journal-links.png)

**Comment by andreasn** [comment]
The link would go to the accompanying service page. The kernel doesn't have a service page, so nothing for that.

**Comment by martinpitt** [comment]
Duplicate of #53
