### ISSUE TITLE
Networking: Bridged virtual traffic excluded from summary page

### ISSUE THREAD

**Issue by brandonkirsch** [cockpit-project/cockpit#13805]
Cockpit version: 215
OS: CentOS Linux release 8.1.1911 (Core)
Page: Network

Issue:
At the summary "Networking" page, my "Open" KVM bridge virbr0 does not contribute to the the network graph and virbr0 is listed as 0 bps in & out.

But when I click on virbr0 under the "Interfaces" heading, the detailed page ("Networking > virbr0") shows a graph with a high volume of traffic (200-800 mbps) and shows 2 ports (eno2 ethernet) and vnet0 (KVM activity) with a high level of Sending / Receiving traffic (in the 100s of mbps).

Reproduce:
1. Install Centos 8.1 and cockpit-preview (version 215) and KVM.
2. Use cockpit to add network bridge virbr0.
3. Use cockpit to attach secondary ethernet port eno2 to virbr0.
4. Boot guest OS in KVM attached to virbr0 and run a bunch of traffic through it.

Observe:
1.  Look at Networking header, and see 0 traffic.
2.  Click into virbr0, see lots of traffic.

![image](https://user-images.githubusercontent.com/449783/77817584-574e8d00-70a2-11ea-82f2-393365ff4aeb.png)

![image](https://user-images.githubusercontent.com/449783/77817594-6cc3b700-70a2-11ea-9413-1fed8d76857b.png)

Expected:
Traffic from eno2 and virbr0 should be included in Networking summary page.

**Comment by KKoukiou** [comment]
I am unsure which commit fixed this, but just tested it  with cockpit 238 and it works as expected.
