### ISSUE TITLE
Does not recognise ssl private key in separate file, and does not recognize .crt files

### ISSUE THREAD

**Issue by smac89** [cockpit-project/cockpit#13809]
Cockpit version: xxx
OS: Ubuntu 19.04
Page: https://cockpit-project.org/guide/latest/https.html

I have an existing PEM cert/key files which I obtained from letsencrypt. I decided to symlink those keys to the cockpit certificates directory (`/etc/cockpit/ws-certs.d`).

```
╭─root@vmi264 ~  
╰─➤  ll /etc/cockpit/ws-certs.d/                               
total 8.0K
-rw-r----- 1 root cockpit-ws 2.9K Mar 28 00:38 0-self-signed.cert
lrwxrwxrwx 1 root root         58 Mar 28 14:00 1-letsencrypt-signed.crt -> /etc/letsencrypt/live/vmi264/cert.pem
lrwxrwxrwx 1 root root         61 Mar 28 14:00 1-letsencrypt-signed.key -> /etc/letsencrypt/live/vmi264/privkey.pem
```

However when I run `remotectl certificate`, I get the error:
```
remotectl: /etc/cockpit/ws-certs.d/1-letsencrypt-signed.cert: No PEM-encoded private key found
```

Now I thought it had to do with the fact that the keys were symlinked, so I decided to create the actual files in the same folder; yet once again, I get the same error.

Then I decided to concatenate the cert and key using `cat 1-letsencrypt-signed.key >> 1-letsencrypt-signed.cert`, and this time it worked.

```
╭─root@vmi264 /etc/cockpit/ws-certs.d  
╰─➤  remotectl certificate                                    
certificate: /etc/cockpit/ws-certs.d/1-letsencrypt-signed.cert
```

Logs

```
-- Logs begin at Thu 2019-05-09 08:58:52 CST. --
Mar 28 14:02:03 vmi264 systemd[1]: cockpit.service: Failed with result 'exit-code'.
Mar 28 14:02:03 vmi264 systemd[1]: Failed to start Cockpit Web Service.
Mar 28 14:02:03 vmi264 systemd[1]: cockpit.service: Start request repeated too quickly.
Mar 28 14:02:03 vmi264 systemd[1]: cockpit.service: Failed with result 'exit-code'.
Mar 28 14:02:03 vmi264 systemd[1]: Failed to start Cockpit Web Service.
Mar 28 14:22:15 vmi264 systemd[1]: Starting Cockpit Web Service...
Mar 28 14:22:15 vmi264 remotectl[5992]: remotectl: /etc/cockpit/ws-certs.d/1-letsencrypt-signed.cert: No PEM-encoded private key found
Mar 28 14:22:15 vmi264 systemd[1]: cockpit.service: Control process exited, code=exited, status=1/FAILURE
Mar 28 14:22:15 vmi264 systemd[1]: cockpit.service: Failed with result 'exit-code'.
Mar 28 14:22:15 vmi264 systemd[1]: Failed to start Cockpit Web Service.
```

Steps to reproduce

1. Generate a standalone key with certbot and link it like I did above
2. `remotectl certificate`

**Comment by martinpitt** [comment]
Ubuntu 19.04 has been EOL for quite a while. But I'm fairly sure that your "xxx" version is less than 211, which [introduced standalone key files](https://cockpit-project.org/blog/cockpit-211.html). So please update to 20.04 LTS, then this will work.
