### ISSUE TITLE
CSS source maps aren't working in browsers

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#13816]
I'm not able to see source maps in browsers — at least for CSS. (Unsure about JS.)

I think the maps stopped working around the LESS to SCSS port?

**Comment by garrett** [comment]
(It's rather hard to debug _some_ CSS without source maps.)

**Comment by garrett** [comment]
It would be great to have this fixed for debugging issues and additionally, I've seen people refer to the source maps in a few bugs (aside from the one mentioned here).

In case someone is reading this issue and wondering what sourcemaps are about: Broken source maps will not impact your Cockpit experience whatsoever — unless you're a developer working on JavaScript and CSS. Sourcemaps are exclusively used for development tools to map compiled JS & CSS back to their original sources (for example: JSX & SCSS).

In fact, sourcemaps and references to sourcemaps shouldn't even be shipped with compiled versions of Cockpit. (I guess that's another related bug?)

**Comment by garrett** [comment]
This looks like a good reference:
https://survivejs.com/webpack/building/source-maps/

On a quick skim, it seems like we want to:
- have source maps completely off for production (including the references)
- have inline source maps (so the original source is in the actual files) for debug mode, as performance should be better than having separate files
- use cheap-source-map (or something like it)

**Comment by garrett** [comment]
We decided to defer fixing CSS source maps in a follow-up PR.

**Comment by martinpitt** [comment]
Is this still an issue? Local builds do produce CSS source maps, is that something that needs to be supported in browsers? I'm not sure if we can build them any different. How would I see if source maps are working?

**Comment by garrett** [comment]
> Local builds do produce CSS source maps

They have been built for a very long while. Just because the source maps exist doesn't mean they are correct or are used. (They're not.)

They're _still_ broken. It's _still_ difficult to see where the CSS is coming from as a result.

**Comment by KKoukiou** [comment]
For me on firefox the source maps on developement are working correct.
![Uploading Screenshot from 2022-12-20 20-38-56.png…]()
