### ISSUE TITLE
cockpit with php system

### ISSUE THREAD

**Issue by asklinux** [cockpit-project/cockpit#13811]
Page: 

i have build project rimauwaf as open source project for waf UI/UX . I like using cockpit for new version . how can i make this run as plugin from cockpit ui with my old project using php . thanks

**Comment by marusak** [comment]
I think you are at a wrong project? https://github.com/agentejo/cockpit
Or I am not sure what exactly you are asking.

**Comment by asklinux** [comment]
yes this project . i want rebuild my project panel for apache and mod_sec from php to become cockpit plugin/module .

**Comment by asklinux** [comment]
this is my git project now .

https://github.com/asklinux/rimau-waf

**Comment by marusak** [comment]
ok, so if you want to create a new plaugin for cockpit the best start is https://github.com/cockpit-project/starter-kit/ . You can read README.md there how to deploy the plugin. The application is in `src/` and should be intuitive how to do it when you are at least a bit familiar with js a react.
To learn how to use API that cockpit provides, please refer to https://cockpit-project.org/guide/latest/development.html

**Comment by asklinux** [comment]
ok thanks , i have new in react but familiar with jquery . its cockpit API work in jquery or i need use react ?

**Comment by asklinux** [comment]
i have start the basic menu for start this project . nead study how API is working first . 

https://github.com/asklinux/cockpit-rimauwaf

**Comment by marusak** [comment]
you can surely use jquery. Some parts of cockpit itself are written using jquery.

**Comment by asklinux** [comment]
the node.js  for cockpit support sqlite ?

**Comment by marusak** [comment]
> the node.js for cockpit support sqlite ?

no. Cockpit provides API for working with unix utilities, such as processes, dbus, files etc.

**Comment by marusak** [comment]
If you have further questions please reach to us on #cockpit on IRC freenode.
