### ISSUE TITLE
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' 

### ISSUE THREAD

**Issue by enira** [cockpit-project/cockpit#13810]
Cockpit version: 215
OS: Ubuntu 19.10

I am working on a plugin however after version 202 this does not seem to work anymore.
Files:
- index.html
- manifest.json 
- smb.js

However my user interface is not loading anymore. I get:
`index.js:15 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' https://192.168.1.160:9090". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.`

My manifest file:
```
{
    "version": "12",
    "main": "index.html",
    "requires": {
        "cockpit": "186"
    },
    "menu": {
        "index": {
            "label": "Samba Shares",
            "order": 65
        }
    },
    "content-security-policy": "img-src * data: 'unsafe-inline'; default-src 'self' 'unsafe-inline' 'unsafe-eval'"
}
```

**Comment by marusak** [comment]
> after version 202 this does not seem to work anymore.

Is something actually breaking, or you just see this error?

Can you see full traceback where this comes from? (using developer build and chrome/ium, firefox does not show full traceback for these).

I am asking, as patternfly introduced such issue. It actually does not break anything for us, it just shows this message. We reported it in https://github.com/patternfly/patternfly-react/issues/2919

**Comment by enira** [comment]
I did some further troubleshooting, did the layout change somewhere between 202 and 215? As this is likely the issue. I've changed the code to reflect the layout of 215 and added bits in and it seems to be working now. Thanks, indeed the error seems to be leading to no issue.

**Comment by marusak** [comment]
> I did some further troubleshooting, did the layout change somewhere between 202 and 215?

yeah, pretty sure there has been some major redesignes in between those 13 versions. We migrated a lot to patterfly4, had some global style overrides...

> I've changed the code to reflect the layout of 215 and added bits in and it seems to be working now.

Happy to hear and sorry for any inconveniences.

> indeed the error seems to be leading to no issue.

ack, closing then.
