### ISSUE TITLE
Storage: Mobile sizes need improvements

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#13820]
As seen on https://github.com/cockpit-project/cockpit/pull/13807#issuecomment-605419633, the storage page needs adjustments to fix:

- [ ] Padding around the lists
- [ ] Dropdown menus getting trapped (and truncated) in an overflow

There are perhaps a few other mobile-related adjustments that might need to be done specifically for this page as well.

**Comment by KKoukiou** [comment]
It's behaving nicely in mobile now:
![Screen Shot 2020-09-04 at 14 18 44](https://user-images.githubusercontent.com/14921356/92238458-9a1a5980-eeb9-11ea-8480-4beca041a239.png)


![Screen Shot 2020-09-04 at 14 18 52](https://user-images.githubusercontent.com/14921356/92238439-91c21e80-eeb9-11ea-87f6-8ffac2de7987.png)
