### ISSUE TITLE
Typo in Dutch translation of the web-interface

### ISSUE THREAD

**Issue by dennis1248** [cockpit-project/cockpit#13850]
https://github.com/cockpit-project/cockpit/blob/aa86066b8ee4c6b18b0da73a6d6b624d60f0c1b6/po/nl.po#L8062

It should be "Gebruik" not "Gebruil".

I am not sure what the proper way is to report something like this so I am making an issue here and suggesting a corrected translation on translate.fedoraproject.

**Comment by marusak** [comment]
Thanks, but indeed it needs to be changed in [weblate](https://translate.fedoraproject.org/translate/cockpit/master/nl/?q=Gebruil&checksum=&offset=#history)
You can suggest or directly edit it if you are sure it is the correct word in the scenario in which it is used.
