### ISSUE TITLE
Improve handling of cores in tests

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#13854]
Analysis from 7.11 2020 from 125 cores:

Majority was in 3 OSes:
55 debian-testing
53 centos-8-stream
16 fedora-33

Tests that have coredumps the most often (others have two or less, but still most of them were TestMachines):
25 TestMachines testAddDiskPool                                                 
19 TestMachines testAddDiskSCSI                                                 
16 TestMachines testLibvirt                                                     
9 TestLogin testTally                                                           
9 TestMachines testAddDiskNFS                                                   
7 TestMachines testInlineConsoleWithUrlRoot                                     
4 TestMachines testNICAdd                                                       
4 TestMachines testDiskEdit                                                     
3 TestMachines testStoragePoolsCreate                                           
3 TestMachines testVCPU 

Programs that coredump:
122 libvirtd
3 cockpit-bridge

**Comment by martinpitt** [comment]
PR #13855 landed with the most important fixes. After that, we should re-do the statistics, it's probably going to look a lot better.

**Comment by marusak** [comment]
@martinpitt I updated the statistics. It is obvious that we really need to stop saving cores from abrt sleep crashes. Also libvirt and all 3 versions of iptables needs to be looked at. And cockpit-bridge possibly as it is our component?

**Comment by marusak** [comment]
@KKoukiou would you be interested to take a look at this? I opened this back in the day when we had many many programs coredumping and it was getting over our heads. Now we are down to pretty much just libvirtd on two OSes.

**Comment by marusak** [comment]
We don't store them anymore by default
