### ISSUE TITLE
Add mention to 'FreeBind=true' to cockpit.socket.d/listen.conf documentation

### ISSUE THREAD

**Issue by doug-letough** [cockpit-project/cockpit#13869]
When cockpit socket is defined via /etc/systemd/system/cockpit.socket.d/listen.conf and configured to listen on a specific IP address it may be needed to add the`FreeBind=true` option to allow systemd to create the socket even if no network interface has already get the configured iP address.

In my case the DHCP server is extremely slow and does not provide IP address fastly enough so cockpit socket fails with:

```
systemd[1]: Starting Cockpit Web Service Socket.
systemd[1]: cockpit.socket: Failed with result 'resources'.
systemd[1]: Failed to listen on Cockpit Web Service Socket.
```

Mentioning the `FreeBind=true` parameter in documentation would suffice to prevent numerous people to be puzzled, ask for a solution or fill a bug report.

**Comment by martinpitt** [comment]
That is an excellent idea! I'll send a PR.
