### ISSUE TITLE
login: RHEL missing background image

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#13872]
After building the RHEL-8-2 image, and going to log in, I noticed the background image is missing:

![Screenshot_2020-04-08 m1 cockpit lan](https://user-images.githubusercontent.com/10246/78780357-bf547b80-799e-11ea-80ec-706347bbf126.png)

**Comment by andreasn** [comment]
What background image should we need to use here?

This is how 8.1 looks for reference:
![Screenshot from 2020-04-09 12-38-15](https://user-images.githubusercontent.com/209895/78886822-20438880-7a5f-11ea-9200-808e74facb0b.png)

**Comment by andreasn** [comment]
So it doesn't use bg-login.jpg for you?
Looks like it to me.

**Comment by garrett** [comment]
Isn't it supposed to look like PF4's?

https://www.patternfly.org/v4/documentation/react/components/loginpage/basic

**Comment by garrett** [comment]
(Meanwhile, I guess PF4 dropped the left side darkening strip... I guess we should update that too.)

**Comment by jgiardino** [comment]
For additional details, here's a link to design documentation that provides more details about the background image. https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/login
