### ISSUE TITLE
Debian: buster-backports package is down

### ISSUE THREAD

**Issue by xupefei** [cockpit-project/cockpit#13887]
Cockpit version: 188
OS: Debian 10
Page: 

Most "cockpit-*" package in the Debian Buster Backports repo is unavailable.

Steps to reproduce

1. Enable the backports according to https://backports.debian.org/Instructions/, then run `apt update`.
2. Run `apt -t buster-backports search cockpit` and read the output as follows:
<details>

```
Sorting... Done
Full Text Search... Done
389-ds/stable 1.4.0.21-1 all
  389 Directory Server suite - metapackage

cockpit/stable 188-1 all
  Web Console for Linux servers

cockpit-389-ds/stable 1.4.0.21-1 all
  Cockpit user interface for 389 Directory Server

cockpit-bridge/buster-backports 215-1~bpo10+1 amd64
  Cockpit bridge server-side component

cockpit-dashboard/stable 188-1 all
  Cockpit remote servers and dashboard

cockpit-doc/stable 188-1 all
  Cockpit deployment and developer guide

cockpit-docker/stable 188-1 all
  Cockpit user interface for Docker containers

cockpit-machines/stable 188-1 all
  Cockpit user interface for virtual machines

cockpit-networkmanager/stable 188-1 all
  Cockpit user interface for networking

cockpit-packagekit/stable 188-1 all
  Cockpit user interface for packages

cockpit-pcp/buster-backports 215-1~bpo10+1 amd64
  Cockpit PCP integration

cockpit-storaged/stable 188-1 all
  Cockpit user interface for storage

cockpit-system/stable 188-1 all
  Cockpit admin interface for a system

cockpit-tests/buster-backports 215-1~bpo10+1 amd64
  Tests for Cockpit

cockpit-ws/buster-backports 215-1~bpo10+1 amd64
  Cockpit Web Service

fonts-b612/stable 1.003+git20180121-1 all
  legible font designed to be used on aircraft cockpit screens

jets3t/stable 0.8.1+dfsg-4 all
  graphical and command-line tools for Amazon S3 and CloudFront

kraptor/stable 0.0.20040403+ds-2 amd64
  Classic shoot 'em up scroller game
```

</details>

You can see that no `cockpit/buster-backports` nor `cockpit-dashboard/buster-backports` available.

3. Run `apt install cockpit/buster-backports` returns an error: `E: Release 'buster-backports' for 'cockpit' was not found`

4. Furthermore, if you open this link: https://tracker.debian.org/pkg/cockpit, and click on the `215-1~bpo10+1` link in the `versions` tab, the server will report a 500 Error. Links of other versions, such as for stable, testing, or unstable, do not return an error.

**Comment by martinpitt** [comment]
Right, see the thread at https://lists.debian.org/debian-backports/2020/04/msg00000.html . I'll do another upload now which should fix this.

**Comment by martinpitt** [comment]
I  uploaded 217-1 to Debian sid now with [adjusting the cockpit-docker rule](https://salsa.debian.org/utopia-team/cockpit/-/commit/b55516fa1c0dfa60b3ec77aa9312852f5dbc97a5). Once that goes into testing and I upload the backport (ideally in 3 days), I'll apply this change to upstream as well.

**Comment by martinpitt** [comment]
Sorry, the latest backport [still failed](https://buildd.debian.org/status/package.php?p=cockpit&suite=buster-backports). Not sure what's wrong and why cockpit-docker is still being built, this needs more debugging.

**Comment by xupefei** [comment]
Hi! I confirm that this issue has been fixed, regardless of https://packages.debian.org/source/stable-backports/cockpit stills shows a 500 exception:
```
cockpit/buster-backports,now 217-2~bpo10+1 all [installed]
cockpit-389-ds/stable 1.4.0.21-1 all
cockpit-bridge/buster-backports,now 217-2~bpo10+1 amd64 [installed,automatic]
cockpit-dashboard/buster-backports,now 217-2~bpo10+1 all [installed,automatic]
cockpit-doc/buster-backports 217-2~bpo10+1 all
cockpit-docker/stable,now 188-1 all [installed]
cockpit-machines/buster-backports,now 217-2~bpo10+1 all [installed]
cockpit-networkmanager/buster-backports,now 217-2~bpo10+1 all [installed,automatic]
cockpit-packagekit/buster-backports,now 217-2~bpo10+1 all [installed,automatic]
cockpit-pcp/buster-backports 217-2~bpo10+1 amd64
cockpit-storaged/buster-backports,now 217-2~bpo10+1 all [installed,automatic]
cockpit-system/buster-backports,now 217-2~bpo10+1 all [installed,automatic]
cockpit-tests/buster-backports 217-2~bpo10+1 amd64
cockpit-ws/buster-backports,now 217-2~bpo10+1 amd64 [installed,automatic]
```

Thanks for your hard work!

**Comment by martinpitt** [comment]
Indeed it [built and uploaded fine now](https://buildd.debian.org/status/package.php?p=cockpit&suite=buster-backports)!
