### ISSUE TITLE
Type to confirm before doing dangerous operations

### ISSUE THREAD

**Issue by simon-on-gh** [cockpit-project/cockpit#13886]
Would be great if the UI would require the user to type something to confirm before doing dangerous operations, like removing a partition, or formatting a disk.

**Comment by KKoukiou** [comment]
@simon-on-gh both of the above are dialogs which have danger alerts.
![Screen Shot 2020-04-27 at 20 43 32](https://user-images.githubusercontent.com/14921356/80408644-d7e1f280-88c7-11ea-9f83-58d96ec8f190.png)
![Screen Shot 2020-04-27 at 20 43 20](https://user-images.githubusercontent.com/14921356/80408655-dadce300-88c7-11ea-8909-71e30486f209.png)

So it's already 2 step, first you click the original button then you click the button within the dialog.
I think asking for more would end up being annoying for a user that wants to actually perform that operation.
