### ISSUE TITLE
the jquery $("#id").click can't function

### ISSUE THREAD

**Issue by asklinux** [cockpit-project/cockpit#13894]
helo , i'm in proses to develope cockpit plugin , but the .click function  is not work on my plugin page . any issue using this jquery function on cockpit ?

thanks

**Comment by marusak** [comment]
No, we use jquery just fine.
You would need to share your current state, but this is most likely not related to Cockpit at all.

**Comment by asklinux** [comment]
helo this is my git for this project

https://github.com/asklinux/cockpit-rimauwaf

maybe somone can help me why my jquery click function not function on the code , thanks .

**Comment by asklinux** [comment]
this is my jquery code .

`$(function() {

	
check_httpd();
check_modsec();

});

          
function check_httpd() {

	var semak = cockpit.spawn(["systemctl", "status", "httpd"]);
	semak.catch(masalah);
	semak.then(papar);

}
function check_modsec(){
	var checkmodsec = cockpit.spawn(["cli-rimau-checkms","-s"]);
	checkmodsec.catch(masalah_modsec);
	checkmodsec.then(paparmodsec);
}
function papar(data){

	dp = '<div class="alert alert-success h-30"><strong>Apache Server Runing</strong><button class="btn btn-sm btn-warning float-right">Restart</button></div>';
	$("#display").html(dp);

}
function masalah(data){

	if (data == 'systemctl exited with code 3'){
		dp = '<div class="alert alert-info"> Apache Server Is Stop </div>';
	}
	else if (data ='systemctl exited with code 4'){
		dp = '<div class="alert alert-danger"> Apache Web Server Not Install</div>';
	}
	else{
		dp = '<div class="alert alert-danger"> '+data+'</div>';
	}
	
	$("#display").html(dp);
}
function paparmodsec(data){

	cstat = $.trim(data);

	if(cstat == 'SecRuleEngine On'){
		psec = '<img src="onwaf.jpg"/>';
	}else{
		psec = '<img src="offwaf.jpg"/>';	
	}
	
	$("#modsecstat").html(psec);
	//$("#modsec").text(cstat);

	
}
function masalah_modsec(data){
	$("#modsec").text(data);
}


$("input[name]='tukar'").click(function(){
	$("#modsecstat").text("test onclock");
});`

**Comment by marusak** [comment]
```
$("input[name]='tukar'").click(function(){
$("#modsecstat").text("test onclock");
});
```

so nowhere in your example you actually show how you create `input[name]='tukar'`.
But here are a few notes. (Nothing related to Cockpit, this is just how to use jquery)
1. `onClick` for input is weird.  Not sure what kind of input is this, but usually you want to listen `onChange` on inputs.
2. If you create this input dynamically, you need to write this method a bit differently. See [here](https://stackoverflow.com/questions/8431073/jquery-on-function-for-future-elements)
3. `#modsecstat` is `<img>`. This tag cannot have any children ([see doc](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img)), thus using `.text()` on it cannot produce anything reasonable.
4. If you want to test that the event was handled, just `console.log("FOO")` and then check your browser console.
