### ISSUE TITLE
cockpit.conf missing

### ISSUE THREAD

**Issue by daveonkels** [cockpit-project/cockpit#13904]
Cockpit version: 164
OS: Ubuntu 18.0.4

I installed a fresh copy of Cockpit on my Ubuntu server and don't see a cockpit.conf file in /etc/cockpit. Is there a way to generate this file or can someone point me to a template?

**Comment by marusak** [comment]
We don't ship this file.
The possible content is documented [here](https://cockpit-project.org/guide/latest/cockpit.conf.5.html) or you can just do `man cockpit.conf` in your terminal.
