### ISSUE TITLE
Disable Text Wrapping in Docker Contain Output

### ISSUE THREAD

**Issue by PoLoMoTo** [cockpit-project/cockpit#13922]
Page: Docker

Disable or add an option to disable text wrapping for the view of a Docker container's output.  It comes up often for me where the Docker container encounters an error and the text wrapping of the output in Cockpit can make it very hard to read.

Here is an example of the issue:
![2020-04-17_20-56](https://user-images.githubusercontent.com/5509894/79624170-07397800-80ee-11ea-9521-6586cbfec739.png)

Another solution could be making that text box resizable but that seems less ideal.  However, it might be good to have both resizability as well being able to resize the text box.

Also I am unsure if this is the correct repo for this issue though I could not find a repo specifically for cockpit-docker.

**Comment by marusak** [comment]
Thanks for the report.
This is indeed the correct repo, but unfortunately cockpit-docker is [being deprecated](https://cockpit-project.org/blog/cockpit-215.html) and we plan to abandon it soon-ish. We now have [cockpit-podman](https://github.com/cockpit-project/cockpit-podman/) as a replacement. So I am afraid that unless someone is willing to send patch, we won't fix it anymore.

**Comment by PoLoMoTo** [comment]
Oh ok thanks!  I am unfamiliar with podman, it seems that it is somewhat a replacement for docker so will cockpit-podman support managing docker containers as well or only podman containers?

**Comment by marusak** [comment]
> will cockpit-podman support managing docker containers as well or only podman containers

Only podman ones. But on commandline you should be able to use "podman" instead of "docker" and things should just work.
