### ISSUE TITLE
Stop using obsolete `com.redhat.SubscriptionManager` API

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#13935]
We use this API in `pkg/lib/packagekit.js` which is not supported anymore and was dropped from recent versions, see https://github.com/candlepin/subscription-manager/commit/2e2cfd4a0c2bf3e40f7057216952184bbf833ccd

We should be able to use [the new API](https://www.candlepinproject.org/docs/subscription-manager/dbus_objects.html). We probably need [GetStatus()](https://www.candlepinproject.org/docs/subscription-manager/dbus_objects.html#entitlement)

**Comment by martinpitt** [comment]
Thanks for digging this out! Indeed I saw the same thing in a RHEL 8.3 downstream dist-git test failure.  @mvollmer, if you want to work on this, please do of course -- I'm happy to assist, as I wrote these bits back then.
