### ISSUE TITLE
Cockpit Application Page Refresh Button

### ISSUE THREAD

**Issue by scout213** [cockpit-project/cockpit#13940]
Cockpit version: 216
OS: Fedora 31
Page: Applications

Issue: When moving the cursor near the Application refresh button in Safari (MacOS Catalina 10.15.4), the button and Applications page text jumps down the page each time the cursor moves close to the button.  This issue does not occur in Chrome, so I'm not sure if this is a bug in Safari or Cockpit.  This problem however does not occur in older versions of Cockpit with the same release of Safari (i.e. Cockpit 196 on CentOS 8 is fine).  

![Screenshot 1](https://user-images.githubusercontent.com/22671045/79933944-5ef21f00-841f-11ea-9b4f-053294db8d88.png)
![Screenshot 2](https://user-images.githubusercontent.com/22671045/79933945-5f8ab580-841f-11ea-967a-cb1147305dde.png)
![Screenshot 3](https://user-images.githubusercontent.com/22671045/79933946-5f8ab580-841f-11ea-84aa-2a41b35f785a.png)

**Comment by marusak** [comment]
Thank you for the report!
This is due to weird behaviour on webkit based browsers.
We fixed similar issue (or the same one) a while ago but I cannot remember now if it was on different page or on the same one and this is a current regression. I'll take a look.

**Comment by marusak** [comment]
It was https://github.com/cockpit-project/cockpit/pull/12552 and on machines page.

From comments there:
> The only issue that remains now is the Applications page as it does not use ct-listing, but does use `<caption>`. However, that's only cosmetic on load, so it's not critical — but it would be nice to fix as well.

which backfired now :)

**Comment by marusak** [comment]
@KKoukiou as you were the one who fixed this on all other places, would you be interested to finish also this remaining one?

**Comment by garrett** [comment]
> but it would be nice to fix as well

That was me asking for some help with a fix, but not wanting to delay the PR further, but address it with a follow-up PR. :wink:
