### ISSUE TITLE
logs: explain columns

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#13957]
Page: Logs

Feel like I'm filing like a million different bugs about logs now, but mostly because I'm staring at it a little bit too much, due to reviewing #13905 and I don't want to tack on too much onto that PR.

So we never actually explain anywhere that the priority column is the priority column, or that the identifier column is the identifier column. Hints like these would help a little with the filtering I think.

**Comment by martinpitt** [comment]
Hmm, this never came up in UX test studies, it does seem fairly self-explanatory? Closing for now.
