### ISSUE TITLE
logs: controls keep jumping a lot

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#13955]
Cockpit version: 214.1.
OS: Fedora
Page: Logs

The controls can grow out of control and they keep jumping a lot.
This became extra evident with the #13905 PR, because the text filter keep moving over, but it's there in master as well.

**Comment by andreasn** [comment]
Did an initial stab at cleaning this up a bit. Mostly to get my head around flex.
https://md8jw.csb.app/

Next step is to implement it using Patternfly widgets instead of raw html.

**Comment by garrett** [comment]
> Did an initial stab at cleaning this up a bit. Mostly to get my head around flex.

You'd want to also use `flex-wrap: wrap` (or `flex-flow: wrap`, which is a shorthand property for setting both `flex-direction` and `flex-wrap`) and consider the `justify-content` from `space-between` to something else, as full justification of text — and widgets in this case — creates ["pools" and "rivers" of whitespace](https://en.wikipedia.org/wiki/Typographic_alignment#Problems_with_justification) through the widgets.

> Next step is to implement it using Patternfly widgets instead of raw html.

You might know this already, but I'll point it out here at least for a reference link: [PF4 flex widget](https://www.patternfly.org/v4/documentation/react/layouts/flex#component-title) uses CSS flex. 

Various flex CSS attributes are exposed in the PF4 react widget (and its modifier classes) too. The example code you see after clicking on the "JSX" button on each demo is also pretty clean React in most cases.

(For example, spacing defaults exist and wrap is turned on by default, so usually you just need `<Flex><FlexItem>Content</FlexItem><FlexItem>Content 2</FlexItem></Flex>`, or some level of nested `<Flex>` and `<FlexIems>` and most stuff happens as you'd expect by default.)

**Comment by garrett** [comment]
BTW: Wrapping is important for "mobile"... which in our case, _almost all_ of "mobile" support really means:

- mobile devices
- lower resolution screens (sometimes used in data centers, often used in VMs, can be when parts of Cockpit are embedded in iframes in other apps, etc.)
- browsers that aren't maximized
- browsers that take up only half or so of the display for multitasking administrators (and most administrators multi-task _a lot_)
- browsers with sidebars (including bookmarks, history, various extensions like tabs on the side, ...)
- excessive content pushing the limits, causing things to break down (in a good way, hopefully)

When I talk about "mobile" support in Cockpit, I'm really using it as shorthand for all of the above cases. :wink:

**Comment by andreasn** [comment]
So I got this far using the patternfly flex classes.

I feel a little dirty about this part though:
```
select {
  min-width: 10em;
  max-width: 10em;
}
```
I thought there would be some good way to solve that with just flex itself.
But maybe just setting `width` as @marusak did in f9dcbf4 is good enough.

**Comment by marusak** [comment]
> I thought there would be some good way to solve that with just flex itself.
But maybe just setting width as @marusak did in f9dcbf4 is good enough.

The top navigation panel that I have now is already flex. The problem is that the list is read dynamically so it may (and often does) resize when other things are already shown. I think that having fixed width is the only solution when we don't want to see any jumping. (Other solution would be to have it as the last item, so when it spans, it does not shift other items, however that is not really a viable solution in this case).
