### ISSUE TITLE
apps: Progressbars go backwards

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#13953]
As spotted in #13945, progress bars in the Applications page sometimes goes backwards.

The code for the Applications page should ensure that progress bars only move forward. 

If there's jitter, perhaps it should adapt the number updates a bit. Otherwise, it should at least check previous with current value and only update the presented percentage with a higher value, not a lower one.

[![xkcd comic 612](https://imgs.xkcd.com/comics/estimation.png)](https://xkcd.com/612/)

If the jumps are a bit too quick, we probably should make sure the width is adjusted with CSS using transition to smoothly display the visual growth (so it quickly animates instead of immediately jumping). The progress bar may already have this baked in. (It was too quick to check.)

One possible naïve approach, assuming the spikes are only returned once in a while per sequential call (so this might not work), may be to always show the lower of the last two progress percentages and only advance when it is higher. Something simple like this may work if it goes from 4% to 50% to 10% to 35% etc. Then the 50% would be dropped as noise and the progress bar would show more accurate, always forward moving behavior. Tied with CSS transition smoothing (which _might_ be baked-in or might not — but it's just 1 line to add) would make the progress bar _feel_ much more accurate too (so you wouldn't really notice the skip in that iteration of the loop).

I was testing the the `debian-stable` VM, in case that matters.

**Comment by garrett** [comment]
I happened to mention this to @larskarlitski today and he suggested perhaps having a sorted set of current and previous numbers (up to 5 or so) and always dropping the highest one each time. It's similar to what I suggested, but with an increasing set. It would probably be more resilient to spikes, even if spikes last over two iterations.

It's difficult to search for existing methods, as most people are talking about smoothing the UI, not the data set. (For the web, it's easy with something like `transition: width 300ms ease;` on the sized progress bar.)

We probably, ideally, would want to use [a smoothing algorithm](https://en.wikipedia.org/wiki/Smoothing#Algorithms). But it could be overkill. The minimum effort is to simply never move backwords and hope for the best. (But the spikes are worrisome and would make the progress jump immediately to the end and sit there.)

It would be nice if PatternFly React might have some sort of optional filter for the progress bar (at a minimum... always increasing)... but as the data could be wildly different, it really might just need to be up to us to implement what's best before feeding it to the widget.

**Comment by garrett** [comment]
We may need to split solutions into two PRs:

1. Never go backwards (which _could_ even be at a Cockpit-wide solution or a PF4 opt-in feature)
2. Fix up or filter the incoming data Applications percentage data, to prevent spikes

It could be possible that filtering or improving the data may also fix it from going backwards too. Having an only-go-forwards feature would still be nice for others, however.

**Comment by garrett** [comment]
I've opened an issue @ https://github.com/patternfly/patternfly-react/issues/4120 to see if it makes sense to have an only-ever-move-forward option in the PF4 React progressbar component.

We would still need to improve the data we feed the progressbar regardless of the option, however.

**Comment by marusak** [comment]
Still happening, just clicking `Install` on some plugin and in the `Installing` step it goes up and down all the time.

**Comment by garrett** [comment]
It's been nearly a year. We have this issue in the Applications page and in the Software updates page (especially on Debian). PatternFly agrees it's a good idea, but haven't implemented the flag yet.

Meanwhile, we should do checks in places that use progress bars as progress bars (not usage bars) to ensure the progress is only ever >= previous value.

However, jumping progress bars are a symptom of problematic (and possibly noisy) data, so we might want to do some sort of smoothing or filtering of the data in addition.
