### ISSUE TITLE
logs: load more makes the statement in the time dropdown untrue 

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#13954]
Spinning off #13905

Cockpit version: 214.1. 
OS: Fedora
Page: Logs

Steps to reproduce

1. Select _current boot_ in the dropdown
2. Press the load more button
3. More than _just_ the current boot will show, but the dropdown will still say _current boot_

**Comment by marusak** [comment]
I think this is on purpose. The logic from the code is as follows:

> If boot or time frame is specified then we don't read the journal until the end (becase we limit it with these parameters) thus we offer 'Load earlier entries` to read more from the journal.

> but the dropdown will still say current boot

if this is the problem, then this will go away with #14104

**Comment by marusak** [comment]
This does not apply anymore, the dropdown was changed.
