### ISSUE TITLE
No obvious way to enable bearer authentication

### ISSUE THREAD

**Issue by mikehearn** [cockpit-project/cockpit#13959]
I'm trying to set up Cockpit with an OAuth provider. I got as far as an error saying "Internal error in the login process", and checking the logs says "cockpit-session: unrecognized authentication method: bearer".

The docs for cockpit.conf say you have to enable bearer auth but not how to do it. I am at a loss. I even searched this repository and the only mention of the word "bearer" is in the docs for the config and a single line of JS that sets the header. I can't see anywhere that bearer auth is actually processed.

How does one set up OAuth login successfully? The docs should be enhanced to make this much clearer.

**Comment by martinpitt** [comment]
In current Cockpit versions there is indeed no support for "Bearer". Earlier versions had a component "cockpit-kubernetes" which provided a Kubernetes component, and that used OAuth2 to authenticate against Kubernetes. But for a "regular" cockpit session there would have to be an OAuth2 PAM module to start a Linux session, and at least in Debian and Fedora there is no such thing.
