### ISSUE TITLE
Cockpit 215, not 217, available in main or backports Ubuntu 20.04 LTS or 18.04 LTS

### ISSUE THREAD

**Issue by dantheman213** [cockpit-project/cockpit#13960]
I can't get the latest version of Cockpit on Ubuntu or Debian nor is there documentation that covers how to install the latest version. The code seems to assume you already know how to deploy the project.

Can there be a method, script, documentation, or readme that allows the latest version of Cockpit to be installed on the target machine?

**Comment by martinpitt** [comment]
That's correct, there is currently newer version available in backports, due to the Ubuntu 20.04 freeze right before its release. It was released yesterday, so as soon as the g-release opens and new packages can be uploaded, I'll start the backporting process again.

**Comment by dantheman213** [comment]
Is it possible to get some documentation in the project so that as soon as a release comes out there is a clear cut official way of building it from the project and installing onto the system bypassing the OS package management?

**Comment by martinpitt** [comment]
Your issue 13970 covers that, and I quickly replied there how to do that. Note that I wouldn't recommend installing straight from upstream on production systems.

**Comment by durzo** [comment]
any progress on this?

I'm looking for a way to install cockpit-docker / cockpit-podman on ubuntu 20.04 LTS

I'm still a bit confused as to which one. the blog says docker has been deprecated but the podman github says it hasn't reached feature parity yet ?

**Comment by martinpitt** [comment]
I backported [version 218](https://launchpad.net/ubuntu/+source/cockpit/218-1~ubuntu20.04.1) to Ubuntu 20.04 LTS now. This doesn't include cockpit-docker though, see issue #13981.
