### ISSUE TITLE
Allow Cockpit to run in a Docker container

### ISSUE THREAD

**Issue by dantheman213** [cockpit-project/cockpit#13968]
Cockpit would be very useful if there was an official way to run it within a Docker image but able to control the host machine's resources. This would make installing and uninstalling the software a breeze and in paradigm with how many modern apps are deployed today.

**Comment by martinpitt** [comment]
You can run the web server part in docker: https://hub.docker.com/r/cockpit/ws/

But conceptually, at least cockpit-system (and -bridge) need to be installed on the target machine that you want to control. Just controlling the docker container itself with cockpit wouldn't be very interesting.
