### ISSUE TITLE
logs: Pause/resume button is jumpy (journal_filtering branch)

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#13965]
Posting this as a followup to #13905 before I forget about it. #13905 works totally fine without this fix, and it's a very minor thing that totally gives such a high value by itself, that it's not worth blocking on this fix.

Cockpit version: 214.1.
OS: Fedora
Page: Logs

When the label changes from Pause the Resume, the button resizes slightly. This in effect shrinks the filter input text field slightly.

Steps to reproduce

1. Go to the logs page
2. Press Pause
3. Press Resume

![pause-resume](https://user-images.githubusercontent.com/209895/80211124-6559e400-8635-11ea-9b39-66f2136a7763.gif)

**Comment by andreasn** [comment]
Screenshots of how OpenShift console does this:

![Screen Shot 2020-04-17 at 9 26 47 AM](https://user-images.githubusercontent.com/209895/80382375-82dfb580-88a2-11ea-8987-61b622d993c7.png)

![Screen Shot 2020-04-17 at 9 26 17 AM](https://user-images.githubusercontent.com/209895/80382333-75c2c680-88a2-11ea-897c-e01afde6a1b6.png)

**Comment by andreasn** [comment]
So a flexbox container set to a certain min-width, and then something like this for the button might do the trick:
```
<button class="pf-c-button pf-m-link" type="button">
  <span class="pf-c-button__text">Link</span>
</button>
```

**Comment by marusak** [comment]
`min-width` would work only for English, for other languages  it still may be jumpy.

I think this is so tiny issue that has too complicated solution that it is not worth the hassle. Also this pause button is not very likely to be used too much.
The only solution would be to rethink the design - which I don't think we want to do now.
