### ISSUE TITLE
Test cleanup not called when test is killed due to timeout

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#13971]
Reproducer:
```
--- test/verify/machineslib.py
+++ test/verify/machineslib.py
@@ -1357,7 +1357,7 @@ class TestMachines(MachineCase, StorageHelpers, NetworkHelpers):
                                     ".*Connection reset by peer")
         self.allow_browser_errors("Disconnection timed out.")
 
-    @timeout(1200)
+    @timeout(90)
     def testCreate(self):
         """
         this test will print many expected error messages
@@ -1511,6 +1511,7 @@ class TestMachines(MachineCase, StorageHelpers, NetworkHelpers):
 
         self.browser.switch_to_top()
         self.browser.wait_not_visible("#navbar-oops")
+        time.sleep(120)
```
and then run:
```
./test/verify/run-tests TestMachinesDBus.testCreate
```

The first run is killed with timeout but none cleanup is called. That makes both subsequent retries fail (or would all subsequent machine tests) like in [this](https://logs.cockpit-project.org/logs/pull-13952-20200424-190419-dee0e225-fedora-31/log) example.

We must make sure that cleanups are called even when the tests is killed due to running for too long.

**Comment by martinpitt** [comment]
Indeed, nice find! This can be reproduced more quickly with

```diff
--- test/verify/check-example
+++ test/verify/check-example
@@ -52,8 +52,12 @@ class TestExample(MachineCase):
 @nondestructive
 class TestNondestructiveExample(MachineCase):
 
+    @timeout(15)
     def testOne(self):
         self.assertEqual(self.machine.execute("whoami").strip(), "root")
+        self.machine.execute("touch /pwned")
+        self.addCleanup(self.machine.execute, "rm /pwned")
+        time.sleep(20)
 
     def testTwo(self):
         self.assertIn("usr", self.machine.execute("ls -l /").strip())

```

and

    test/verify/run-tests -tv TestNondestructiveExample.testOne

**Comment by martinpitt** [comment]
The reason is that the timeout is applied by run-tests via the timeout(1) wrapper around check-*. Back then I didn't have much luck with applying the timeout *inside* of MachineCase. With that we would have more control over test cleanup. With the current approach, the only thing that we can do is to spin up a fresh testbed, similar to what it already does on "test_harness" failures (boot or ssh failure).
