### ISSUE TITLE
Document how to build rpms or debs

### ISSUE THREAD

**Issue by dantheman213** [cockpit-project/cockpit#13970]
There should be clear cut documentation and a script to generate the needed binaries, configs, etc and install them into place. Or to generate a *.deb or *.rpm package from latest copy of master.

**Comment by martinpitt** [comment]
The [HACKING](https://github.com/cockpit-project/cockpit/blob/master/HACKING.md#installation-from-upstream-sources) file describes "Installation from upstream sources".

However, I recommend building distro packages (deb or rpm), as these are safer and easier to upgrade or remove again. For Debian, just `cp -r tools/debian .` to get a source tree, from which you can do `dpkg-buildpackage -S` or build binaries, etc. For Fedora, you can use tools/make-srpm or tools/make-rpm. Indeed we should add that to HACKING.

**Comment by dantheman213** [comment]
> However, I recommend building distro packages (deb or rpm), as these are safer and easier to upgrade or remove again. For Debian, just cp -r tools/debian .

Can you provide explicit instructions in the README or HACKING *.md files? I'm very interested in the latest changes coming into Cockpit as your VM interface has improved considerably in recent versions and I want to ensure I have the very latest changes with a clear official method for deployment. Documentation isn't quite clear would be much appreciated if it could be refactored to elaborate on some of these concepts.

**Comment by martinpitt** [comment]
Sent PR #14370 for this at last.
