### ISSUE TITLE
List of virtual machines is different from time to time

### ISSUE THREAD

**Issue by vryabokon1705** [cockpit-project/cockpit#14001]
Cockpit version: 217
OS: Fedora Workstation 31
Page: "Machines"

I have libvirt machines created with virt-manager. I wont to use cockpit to use them.
But: 
List of machines is different from time to time after page reloaded, or empty. It can list 1, 2,3 machines. But never shows all the machines. I have error messages in browser console: 
Uncaught TypeError: Cannot read property 'getAttribute' of undefined
    at machines.js:135
    at Or (machines.js:135)
    at Function.<anonymous> (machines.js:135)
    at s (cockpit.js:979)
    at cockpit.js:991
    at n (cockpit.js:897)

I can list machines with virsh: 
sudo virsh list --all
Id   Name          State
------------------------------
 -    debian8       shut off
 -    debian8-arm   shut off
 -    macosY        shut off
 -    NAU_Linux     shut off
 -    w10           shut off
 -    win7          shut off

I can list machines with dbus:
 gdbus call --system --dest org.libvirt --object-path /org/libvirt/QEMU     --method org.libvirt.Connect.ListDomains 0
([objectpath '/org/libvirt/QEMU/domain/_0f8e9191_b291_4ad1_b322_2122ccd930b4', '/org/libvirt/QEMU/domain/_9307fab4_fe39_4b8a_b805_28eec56dc0b1', '/org/libvirt/QEMU/domain/_327bd0ba_2597_4a32_a99f_d35588cf0e75', '/org/libvirt/QEMU/domain/_27764941_a729_43ba_adbe_0d2966116627', '/org/libvirt/QEMU/domain/_cdc3c2e0_a1fe_4bf7_bb38_170d2fc5fc95', '/org/libvirt/QEMU/domain/_b3d1e319_9c8a_4994_9273_96e1a8d1a06c'],)

**Comment by KKoukiou** [comment]
Hi @vryabokon1705, some of your VMs have a configuration that we can't parse and this results in the behavior you see.
We call the 'getAttribute' in a lot of places, so I can't figure out just from the js console what property exactly causes this, but if you give me the XML of all your machines, that would give me a 100% reproducer and I will be able to solve you issue. 

The following command will get you yoru system VMs.
```
mkdir -p ./my-vms; for vm in $(sudo virsh list --all --name); do sudo virsh dumpxml $vm > ./my-vms/$vm.xml; done
```
Thanks in advance for the help!

**Comment by tonymartino** [comment]
Hello Katerina,

I'm seeing something similar:
`Uncaught TypeError: Cannot read property 'getAttribute' of undefined
    at machines.js:53
    at zp (machines.js:53)
    at Function.<anonymous> (machines.js:53)
    at s (cockpit.js:962)
    at cockpit.js:974
    at n (cockpit.js:880)
(anonymous) @ machines.js:53
zp @ machines.js:53
(anonymous) @ machines.js:53
s @ cockpit.js:962
(anonymous) @ cockpit.js:974
n @ cockpit.js:880
setTimeout (async)
L @ cockpit.js:885
f @ cockpit.js:973
l @ cockpit.js:997
e.values @ cockpit.js:986
s @ cockpit.js:962
(anonymous) @ cockpit.js:974
n @ cockpit.js:880
setTimeout (async)
L @ cockpit.js:885
f @ cockpit.js:973
l @ cockpit.js:997
e @ cockpit.js:1024
(anonymous) @ machines.js:53
s @ cockpit.js:962
(anonymous) @ cockpit.js:974
n @ cockpit.js:880
setTimeout (async)
L @ cockpit.js:885
f @ cockpit.js:973
l @ cockpit.js:997
e @ cockpit.js:1024
(anonymous) @ cockpit.js:2067
se @ cockpit.js:76
e @ cockpit.js:205
p @ cockpit.js:590
m @ cockpit.js:599
v @ cockpit.js:493
a.onmessage.o.dispatch_data @ cockpit.js:423
e @ cockpit.js:279
postMessage (async)
(anonymous) @ index.js:72
a.onmessage.o.dispatch_data @ cockpit.js:439`

I've attached the XML for one of my domains (the rest of similar).

Thank you!
-Tony
[funguss.xml.txt](https://github.com/cockpit-project/cockpit/files/4672499/funguss.xml.txt)
