### ISSUE TITLE
Provide a way to skip /snap in storage module

### ISSUE THREAD

**Issue by wscott** [cockpit-project/cockpit#14008]
Page: 
Storage

On my Ubuntu 20.04 machine, the storage module is dominated by snaps that are mounted at /snap/*. These are generally useless and get in the way of looking at actual filesystem information.

It would be useful to skip these by default or have a way to hide them.

**Comment by jilted82** [comment]
I managed to solve this problem by creating a udev-rule.

Go to /etc/udev/rules.d/ and create a new file, e.g. 10-hide-snap-mounts.rules or something else to your liking and add the following to hide loop a device from udisk2 (and also cockpit)

```
KERNEL=="loop1", ENV{UDISKS_IGNORE}="1"
KERNEL=="loop2", ENV{UDISKS_IGNORE}="1"
```

You can also use range expression if you dont want to add each device one by one.

```
KERNEL=="loop[1-8]", ENV{UDISKS_IGNORE}="1"
```
Save and run udevadm trigger and refresh cockpit :)

**Comment by KKoukiou** [comment]
@jilted82 thanks for posting a workaround.

There is an upstream report for that on snapcraft about it, https://bugs.launchpad.net/ubuntu/+source/snapcraft/+bug/1714941

We could filter them in cockpit of course, but I would rather keep this logic outside of cockpit.
