### ISSUE TITLE
Something weird happens when interacting with Ubuntu's 20.04 "org.gtk.Notifications D-Bus service

### ISSUE THREAD

**Issue by q2dg** [cockpit-project/cockpit#14007]
Cockpit version: 215-1 (the stock version which comes by default in Ubuntu 20.04)
OS: Ubuntu 20.04

Hello.
I want a page with a button to remotely activate the screensaver of a Ubuntu Desktop 20.04 (where the Cockpit server is running) besides a message showing if it is already activated or not.
Starting from "ping" example, I have this HTML page...

![b](https://user-images.githubusercontent.com/7274874/80910841-9f606f80-8d32-11ea-89ae-ecc1688eb5c4.png)

...and this Javascript page:

![a](https://user-images.githubusercontent.com/7274874/80910844-a7201400-8d32-11ea-8ed9-3c84295303be.png)

But when I click the button, Firefox's console show this error: "TypeError: interf.SetActive is not a function" So I infer something is going wrong when creating the "interf" object, which represents the interface needed to run SetActive() method, asi it can be seen in this D-Feet screenshot

![Captura de pantalla de 2020-05-03 11-35-14](https://user-images.githubusercontent.com/7274874/80910860-b901b700-8d32-11ea-9e11-232de527ddf2.png)

I've tried wrting _{"bus":"user"}, {"bus":"session"}, {bus:"user"} and {bus:"session"}_ as possible values of second argument in cockpit.dbus() method but all of them raise the same error message.

If I do the DBus call inside a local terminal (like this, _busctl --user call org.gtk.Notifications /org/gnome/ScreenSaver org.gnome.ScreenSaver SetActive b true_) it works. So it seems it isn't a wrong Ubuntu's D-Bus implementation 

Thanks all of you

**Comment by q2dg** [comment]
Sorry, I was using a different user to login inside Cockpit than the user which had the desktop session opened. My fault.
Sorry a lot.

**Comment by martinpitt** [comment]
Glad you figured it out :)
