### ISSUE TITLE
trying to format lv group "nasuser" with XFS

### ISSUE THREAD

**Issue by rick-aarch64** [cockpit-project/cockpit#1402]
While using cockpit to format lvgroup names "nasuser" I got following error:
Command-line `mkfs.xfs -f -L "filesystem for nfs user" "/dev/dm-4"' exited with non-zero exit status 1: Illegal value filesystem for nfs user for -L option Usage: mkfs.xfs /\* blocksize _/ [-b log=n|size=num] /_ metadata _/  [-m crc=0|1,finobt=0|1] /_ data subvol _/   [-d agcount=n,agsize=n,file,name=xxx,size=num, (sunit=value,swidth=value|su=num,sw=num|noalign), sectlog=n|sectsize=num /_ force overwrite _/   [-f] /_ inode size _/   [-i log=n|perblock=n|size=num,maxpct=n,attr=0|1|2, projid32bit=0|1] /_ no discard _/    [-K] /_ log subvol _/   [-l agnum=n,internal,size=num,logdev=xxx,version=n sunit=value|su=num,sectlog=n|sectsize=num, lazy-count=0|1] /_ label _/   [-L label (maximum 12 characters)] /_ naming _/ [-n log=n|size=num,version=2|ci,ftype=0|1] /_ no-op info only _/    [-N] /_ prototype file _/   [-p fname] /_ quiet _/  [-q] /_ realtime subvol _/  [-r extsize=num,size=num,rtdev=xxx] /_ sectorsize _/    [-s log=n|size=num] /_ version */   [-V] devicename <devicename> is required unless -d name=xxx is given. <num> is xxx (bytes), xxxs (sectors), xxxb (fs blocks), xxxk (xxx KiB), xxxm (xxx MiB), xxxg (xxx GiB), xxxt (xxx TiB) or xxxp (xxx PiB). <value> is xxx (512 byte blocks).

[root@nas ~]# rpm -qR cockpit.aarch64
/bin/sh
/bin/sh
/bin/sh
/bin/sh
cockpit-assets
config(cockpit) = 0.25-1.fc21
dbus
glib-networking
ld-linux-aarch64.so.1()(64bit)
ld-linux-aarch64.so.1(GLIBC_2.17)(64bit)
libaccountsservice.so.0()(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.17)(64bit)
libcom_err.so.2()(64bit)
libcrypt.so.1()(64bit)
libcrypt.so.1(GLIBC_2.17)(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libgcc_s.so.1(GCC_3.3.1)(64bit)
libgio-2.0.so.0()(64bit)
libglib-2.0.so.0()(64bit)
libgobject-2.0.so.0()(64bit)
libgssapi_krb5.so.2()(64bit)
libgssapi_krb5.so.2(gssapi_krb5_2_MIT)(64bit)
libgudev-1.0.so.0()(64bit)
libjson-glib-1.0.so.0()(64bit)
libk5crypto.so.3()(64bit)
libkeyutils.so.1()(64bit)
libkeyutils.so.1(KEYUTILS_0.3)(64bit)
libkrb5.so.3()(64bit)
libkrb5.so.3(krb5_3_MIT)(64bit)
libm.so.6()(64bit)
libpam.so.0()(64bit)
libpam.so.0(LIBPAM_1.0)(64bit)
libpolkit-agent-1.so.0()(64bit)
libpolkit-gobject-1.so.0()(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.17)(64bit)
libssh.so.4()(64bit)
libsystemd.so.0()(64bit)
libsystemd.so.0(LIBSYSTEMD_209)(64bit)
libudisks2.so.0()(64bit)
libutil.so.1()(64bit)
libutil.so.1(GLIBC_2.17)(64bit)
lvm2
mdadm
realmd
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
rtld(GNU_HASH)
storaged
systemd
systemd
systemd
udisks2 >= 2.1.0

seems like lv name is split into "nas" and "user" and not handled as "nasuser"

Rick

**Comment by mvollmer** [comment]
xfs labels can not be more than 12 characters, and the error message is the way mkfs.xfs tries to tell you that... :-/

We should improve this.

**Comment by mvollmer** [comment]
https://trello.com/c/XomIlHjB/461-storage-check-filesystem-labels
