### ISSUE TITLE
Networking tab shows nothing when NM is not running

### ISSUE THREAD

**Issue by wolfy01** [cockpit-project/cockpit#14023]
![image](https://user-images.githubusercontent.com/45273698/81040592-a940ba80-8e79-11ea-84b3-880f449dc069.png)

**Comment by wolfy01** [comment]
The `Network Manager` service was not running.

**Comment by wolfy01** [comment]
When networkmanager is running i always get this error `Cannot refresh cache whilst offline` but everything works fine after disabling `NetworkManager`, but then the networking tab no longer shows anything.

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit/issues/8477

**Comment by mvollmer** [comment]
> The Network Manager service was not running.

The page should show something useful when that is the case, so we still have a bug here somehwere.

**Comment by Libitum** [comment]
Just give the solution here: https://github.com/cockpit-project/cockpit/issues/8477#issuecomment-630124971

**Comment by wolfy01** [comment]
This fixed my issue: [#8477 (comment)](https://github.com/cockpit-project/cockpit/issues/8477#issuecomment-630124971)
