### ISSUE TITLE
Crosscompile cockpit for ARM

### ISSUE THREAD

**Issue by gmalmeida** [cockpit-project/cockpit#14030]
Hi there, 

I am trying to crosscompile cockpit for ARM core. Below the steps I am taking on a host ubuntu machine:

`
sudo apt-get -y install libglib2.0-dev libsystemd-daemon-dev libsystemd-journal-dev libsystemd-login-dev  libjson-glib-dev libpolkit-agent-1-dev libkrb5-dev libssh-dev libpam0g-dev systemd intltool xsltproc xmlto

export PATH=$PATH:~/buildroot-2018.02/output/host/usr/bin

./configure CXX=aarch64-linux-g++ --disable-pcp

make

file test-hex

test-hex: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=bcf84895efceea7a2ce1db9adff0422b987307d9, not stripped
`

**Comment by davidmalcolm** [comment]
Does your cross-compiler actually use `/usr/include`?  Aren't those the include files for native compilers, rather than cross-compilers?  Passing `-v` to gcc will emit the default include paths it tries (amongst other data).

**Comment by martinpitt** [comment]
Stale, no reply in a year. If you still run into this, please test with a current version
