### ISSUE TITLE
Unable to manage 389 Directory Server on Arch Linux

### ISSUE THREAD

**Issue by ImNtReal** [cockpit-project/cockpit#14034]
Cockpit version: 218
OS: Arch Linux
Page: /389-console

I am unable to manage my 389 Directory Server from Cockpit installed on Arch Linux.

Additional info:
* 389-ds-base 1.4.3.4-2
* cockpit 217-1
~ sudo pkcon search 389-ds-base 5.9s  Thu 23 Apr 2020 01:44:03 PM EDT
Searching by details [=========================]
Finished [=========================]
Installed 389-ds-base-1.4.3.4-2.x86_64 (installed) 389 Directory Server (base)

Steps to reproduce:

Despite PackageKit showing 389-ds-base being installed, when I log in to Cockpit, and click the 389 Directory Server tab, I get a message that says:
There is no 389-ds-base package installed on this system. Sorry there is nothing to manage...

If I attempt to install 389-ds-base via Cockpit, I get a message stating:
Error installed/389-ds-base: could not find database

I have even removed the package via pacman, and re-installed it from the Cockpit interface. It appears to have installed the package, but still shows the Install button for it, and I still can't manage it.

I'm not sure if this is a problem with the 389-ds-base package, the cockpit package, or something with my config. I'm definitely willing to help collect more information, and debug. Please, let me know steps to troubleshoot this issue.

Also, see:
https://pagure.io/389-ds-base/issue/51066
https://bugs.archlinux.org/task/66551
https://bugs.archlinux.org/task/66363

**Comment by ImNtReal** [comment]
![image](https://user-images.githubusercontent.com/2048112/81095856-965ad400-8ed3-11ea-9b24-3e6b42ed1853.png)

**Comment by ImNtReal** [comment]
I managed to convince the Applications tab that 389-ds-base was installed by copying the metadata xml file from /usr/share/metainfo/389-console/org.port389.cockpit_console.metainfo.xml to /usr/share/metainfo/org.port389.cockpit_console.metainfo.xml, but this page still shows it as not installed.

**Comment by martinpitt** [comment]
Can you please file this here: https://pagure.io/389-ds-base/issues

This is a piece of code that does not come from the cockpit project itself. Thanks!
