### ISSUE TITLE
Deleting user can cause oops

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#14038]
Sometimes tests when click on `#account-delete` they cause oops with:
```
TypeError: Cannot read property 'name' of null
```

Example [log](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-14027-20200505-122603-5e2a73ba-debian-testing/log.html#1-2)

**Comment by KKoukiou** [comment]
This link is not available any more, and also I can't see any related test failure in https://images-cockpit.apps.ci.centos.org/failure-stats.html

Since this is not of any help I will close it and maybe if we see it happening again we can reopen with a more recent logs.
