### ISSUE TITLE
Connect workstation to cokpit server behind NAT

### ISSUE THREAD

**Issue by BedoM** [cockpit-project/cockpit#14049]
Page: 
For administrate WORKSTATION

Hello,
Is it possible to initiate the connection to a cockpit server from a machine behind NAT to be able to control it from this server
Or connection is only possible from the cockpit server

The server is a datacenter server with a public IP.

thank you

**Comment by martinpitt** [comment]
Cockpit provides a normal TCP socket, so of course you can access that from a client that is behind NAT, just like any other website. What happens exactly if you try to access https://your.sever.name:9090 ?

**Comment by marusak** [comment]
No reply, closing due to lack of information
