### ISSUE TITLE
polkit detection is automagic

### ISSUE THREAD

**Issue by tgurr** [cockpit-project/cockpit#14052]
Cockpit version: 218
OS: Linux

https://github.com/cockpit-project/cockpit/pull/13963 states that it implements a `--disable-polkit` configure switch, in 218 however the polkit detection is automagic, there's no such configure switch to disable polkit integration.

`configure: WARNING: unrecognized options:  --disable-polkit`
`./configure --help | grep polkit`

Please add such a configure switch so distributions are able to properly package a cockpit version without polkit integration.

**Comment by martinpitt** [comment]
The original PR indeed did, but the final commit 12afa36b40f8dd70c9a008420bf1a2fd88998854 didn't mention this any more. We can certainly add a `--disable-polkit`, but I don't understand why this would block you -- it's only necessary if you *have* libpolkit, but don't want to use it. If you don't have libpolkit, then such an option isn't necessary.

**Comment by tgurr** [comment]
Automagic is always a thing to avoid when making things optional to build. This is especially a requirement for source-based distributions (I'm packaging cockpit for exherbo). There are many use cases where there can indeed be package xy around but you don't want your final build to include support/depend on package xy, e.g. build hosts and so on. So adding a proper configure option to enable/disable polkit usage would be very welcome.

**Comment by hoinmic** [comment]
@tgurr You're right. Automatic detection can cause problems. Yocto has only had this under control since version 2.3. Previous versions have problems with adding and removing components later (probably OpenWRT has problems with this too).

@martinpitt I would extend the code as follows:
First priority) Option to explicitly enable or disable Polkit
Second priority) autodetection Polkit (as in version 218)

**Comment by martinpitt** [comment]
> @martinpitt I would extend the code as follows:
> First priority) Option to explicitly enable or disable Polkit
> Second priority) autodetection Polkit (as in version 218)

Sounds good -- that's just how standard autoconf `--enable` options behave. Do you want to work on this?

**Comment by hoinmic** [comment]
@martinpitt Sounds like a perfect weekend task :-) I will try to do it.

**Comment by tgurr** [comment]
Thanks for your work, I've just tried cockpit 221.1 and while it doesn't link to polkit anymore with the new `--disable-polkit` configure option there's still a little confusion.

configure seems to check for polkit even if `--disable-polkit` is passed, resulting in
`checking for POLKIT... yes`
but afterwards
`checking whether to build with polkit... no`
might be better to only check for polkit if --enable-polkit or nothing is passed to configure.

Also the polkit policy file
`/usr/share/polkit-1/actions/org.cockpit-project.cockpit-bridge.policy`
gets installed even if building without polkit support.

**Comment by martinpitt** [comment]
Fixed in PR #15576
