### ISSUE TITLE
Login fails if user login shell is tcsh instead of bash

### ISSUE THREAD

**Issue by crowston** [cockpit-project/cockpit#14060]
Cockpit version: Version 215
OS: Ubuntu 20.04 LTS
Page: localhost:9090/system

Logging into cockpit fails with the error "Wrong user name or password" when the user login shell is tcsh but succeeds when it's bash. 

tcsh is listed in /etc/shells. ~/.tcshrc is world readable. 

Steps to reproduce: 

1. change login shell to /bin/tcsh
2. log in to cockpit

Here are the system and authentication logs: 

May 09 08:13:51 emohawk systemd[1]: Started Cockpit Web Service https instance factory (PID 33844/UID 129).
May 09 08:13:51 emohawk systemd[1]: Starting Socket for Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
May 09 08:13:51 emohawk systemd[1]: Listening on Socket for Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
May 09 08:13:51 emohawk systemd[1]: Started Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
May 09 08:13:51 emohawk systemd[1]: cockpit-wsinstance-https-factory@4-33844-129.service: Succeeded.
May 09 08:13:51 emohawk cockpit-ws[34298]: cockpit-ws: Failed to open certificate file /run/cockpit/tls/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: No such file >
May 09 08:13:51 emohawk cockpit-session[34301]: pam_ssh_add: Failed adding some keys
May 09 08:13:51 emohawk cockpit-session[34301]: pam_unix(cockpit:session): session opened for user crowston by (uid=0)
May 09 08:13:51 emohawk systemd-logind[804]: New session 95 of user crowston.
May 09 08:13:51 emohawk systemd[1]: Started Session 95 of user crowston.
May 09 08:13:51 emohawk cockpit-ws[34311]: 3: Permission denied.
May 09 08:13:51 emohawk cockpit-session[34301]: pam_unix(cockpit:session): session closed for user crowston
May 09 08:13:51 emohawk systemd[1]: session-95.scope: Succeeded.
May 09 08:13:51 emohawk systemd-logind[804]: Session 95 logged out. Waiting for processes to exit.
May 09 08:13:51 emohawk systemd-logind[804]: Removed session 95.

**Comment by omenos** [comment]
Also running into this issue. A bit of a damper on adopting cockpit as (due to legacy reasons) tcsh is the login shell across our environment with no expected change on the horizon. Support for csh/tcsh environments would be 👌

**Comment by martinpitt** [comment]
What happens is that cockpit-session tries to do this

    tcsh -c "exec cockpit-bridge >&3"

and that syntax does not work in tcsh. "exec >&3" just tries to create a literal file "3".

tcsh does not  support input redirection to other file descriptors, so we need to special-case that. If your ~/.cshrc and friends print anything on stdoutput, then you lose, but there's nothing that we can do about that..

**Comment by cedx** [comment]
Same issue here... with PowerShell !

At my work, we are big fans of PowerShell Core, so we've started to use it on some servers (running on CentOS 7 and CentOS 8).
Setting it as a login shell works fine (`/usr/bin/pwsh` is listed in `/etc/shells`): no issue encountered so far.

But Cockpit auth does not like it :cry: (same error : "Wrong user name or password"). The connection seems OK, but is closed immediately:

```
Aug 19 16:28:29 sd-100506 cockpit-session[209307]: pam_unix(cockpit:session): session opened for user cedric by (uid=0)
Aug 19 16:28:31 sd-100506 cockpit-session[209307]: pam_unix(cockpit:session): session closed for user cedric
```

**Comment by martinpitt** [comment]
This was fixed in PR #14375 and thus in Cockpit 226.

**Comment by digitalformula** [comment]
I know the original issue here tagged Ubuntu and tcsh, but is there a possibility something similar is happening on CentOS 8?  I'm also getting the wrong username and password error on 226 and 227.  211 doesn't do this.  Is anything other than 211 even an option on CentOS 8?

@martinpitt Sorry for commenting on a closed issue.  Not sure how to diagnose this beyond issue 14553 that I logged yesterday.

**Comment by martinpitt** [comment]
@digitalformula : tcsh is not in RHEL/CentOS, so unless you got it from somewhere else, and the user you are logging in as actually is using tch, it's not the same issue. Also, the failure looked different than #14553.

**Comment by omenos** [comment]
> tcsh is not in RHEL/CentOS

`tcsh` is included in RHEL 8 in the AppStream repository. It is presently shipping 6.20 from Red Hat.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/package_manifest/appstream-repository
https://access.redhat.com/downloads/content/rhel---8/x86_64/7441/tcsh/6.20.00-12.el8/x86_64/fd431d51/package
http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/

**Comment by martinpitt** [comment]
@omenos : Oops, thanks for the correction! That evaded me somehow.
