### ISSUE TITLE
Ubuntu nodes vs Cockpit permission problem?

### ISSUE THREAD

**Issue by PiperMp3** [cockpit-project/cockpit#14077]
Hi,

Found cockpit as the number 1 software for managing multiple servers at the same time, so thought I'd give it a go.
So as I have a few, I'll call them Node1 Node2 ect, and each of them has a corresponding username, I will use a number per, as in Node1 got User1 etc.

In terms of security, these are VMs inside 1 Server, locked inside a subnet, so it cannot reach the world wide web, nor can the world wide web reach them, these are internal to internal.

Ok so, each of these has a different SSH Port, different Username, but same login PW.
Root login is not permitted, so I always have to SSH in with username + pw, then "su"  to go into root.

Now. Node 1, Node2 and node 3 has cockpit so far. These are Ubuntu all of them.
Node 1 is the "main one" (although I cannot find any checkboxes anywhere to make it master), and I've added node 2 to the dashboard.
I logged into the webui via Node 1 and i've tried both root + pw and user1 + pw, both allow me to login.
I added Node2 using User2 + pw, this only worked if I logged into the webui on Node 1 as root + pw?
User1,2,3 are all added as root users on the corresponding nodes.

I am not allowed to change any of node2's services (stop/start) - why is that? "Permission denied"
This happens regardless of logging into to webui for node1 as root or username1.
I can also not add further nodes if I am logged in to webui for node1 as username1 - why is that?
Username1 is a root user on Node1.
This is tried both with "Reuse my credentials..." which is rather unfitting as each node has a different username, and I cannot allow root login on all 8 VMs so 1 fits them all.

Why is Cockpit not managing the different nodes username and PW exclusively when interacting with said node? Ie, if I go to Node2 and find a service to stop, I would expect Cockpit to use User2 and its PW to make it happen, not Node1's pw as it seems to be (regardless of tickbox on login screen)

As an example - Node2 got apache2 on it.
Logging into node2 ssh with user2 + pw - "service apache2 stop" - prompted for PW - accepted, all done
Using Cockpit UI, logged in on Node1 as user1 - added Node2 with user2 + pw - goes to node2, service, apache2 - "stop" -> "Permission denied".

I'm struggling to understand why this happens? If Node2 is going to use Node1's user1 and pw, then why is Cockpit asking for a username and pw when adding it to the dashboard? Seems a bit redundant. 
If rootlogin is required, in a "1 pw fits them all"  Cockpit cannot be used in this environment due to the security implications.

Potentially I've gone about this wrong?

My dashboard is also missing several icons that your pages are displaying;
https://cockpit-project.org/images/site/screenshot-dashboard.png - far left.
I only have the top 2, whilst the bottom 2 are missing?
Setup steps followed;
https://cockpit-project.org/running.html

1 command, accessed UI - thats it, same goes for node2 and 3.

**Comment by PiperMp3** [comment]
Located it.
Basically you have to login "As root" to the other nodes.

sshd_config needs to allow rootlogin (Yes) and restart ssh. Cockpit can consume control at that stage.

**Comment by martinpitt** [comment]
@PiperMp3 : This has been a loooooong-standing problem indeed. As it happens, the authentication was redesigned and the next upstream release 219 (tomorrow) will fix it properly.
