### ISSUE TITLE
remotectl fails in FIPS mode: Could not parse PEM certificate: The request is invalid

### ISSUE THREAD

**Issue by vasintalana** [cockpit-project/cockpit#14074]
Cockpit version: 217
OS: Fedora 32
Page: Main page

```bash
# journalctl -u cockpit.service
systemd[1]: Starting Cockpit Web Service...
remotectl[10272]: remotectl: /etc/cockpit/ws-certs.d/0-self-signed.cert: Could not parse PEM certificate: The request is invalid.
systemd[1]: cockpit.service: Control process exited, code=exited, status=1/FAILURE
systemd[1]: cockpit.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Cockpit Web Service.
```

Steps to reproduce

1. ```# fips-mode-setup --enable```
2. ```# systemctl reboot```
3. ```# dnf -y install cockpit```
4. ```# systemctl --now enable cockpit.socket```
5. ```# firewall-cmd --permanent --add-service=cockpit```
6. ```# firewall-cmd --reload```
6. Open the cockpit page

**Comment by martinpitt** [comment]
This looks like your 0-self-signed.cert may have been generated with an algorithm which is disabled under FIPS? Can you please try

    sudo rm /etc/cockpit/ws-certs.d/0-self-signed.cert
    sudo systemctl  restart cockpit

this will regenerate the self-signed certificate, and then hopefully work?

**Comment by martinpitt** [comment]
We now see this in our image refreshes, so I can investigate this myself now.

**Comment by vasintalana** [comment]
Forgot to update this.
I've done it before, using `rm -f /etc/cockpit/ws-certs.d/*` then restarting the cockpit.
Not really, the result is still the same.
Now, Cockpit installed is version 220.

```bash
systemd[1]: Starting Cockpit Web Service...
remotectl[3260]: Generating temporary certificate using: sscg --quiet --lifetime 3650 --key-strength 2048 --cert-key-file /etc/cockpit/ws-certs.d/0-self-signed.cert --cert-file /etc/cockpit/ws-certs.d/0-self-signed.cert --ca-file /etc/cockpit/ws-certs.d/0-self-signed-ca.pem --hostname localhost.localdomain --organization 89787d7f2eb04815bd444999a92f5dc8 --subject-alt-name localhost --subject-alt-name IP:127.0.0.1/255.255.255.255
remotectl[3260]: remotectl: /etc/cockpit/ws-certs.d/0-self-signed.cert: Could not parse PEM certificate: The request is invalid.
systemd[1]: cockpit.service: Control process exited, code=exited, status=1/FAILURE
systemd[1]: cockpit.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Cockpit Web Service.
```

**Comment by martinpitt** [comment]
This was introduced with [GnuTLS 3.6.14](https://bodhi.fedoraproject.org/updates/FEDORA-2020-0cce3578e2). I reported the regression in https://bugzilla.redhat.com/show_bug.cgi?id=1845806 . There's nothing that we can do on the Cockpit side I'm afraid, GnuTLS is broken. As a workaround, you can run `dnf downgrade gnutls` to go back to 3.6.13.
