### ISSUE TITLE
Browser issue: F20 epiphany - Server has closed the connection.

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#1407]
I've tried to use other web browser, and it failed to login, better to say,
It is logged  in https://192.168.122.168:9090/#/local/dashboard, but popup windows with text:
Disconnected
Server has closed the connection.
It seems that after login, aomething close connection. I have to say, that cockpit server is still running, no error in cocpit log.
    Thanks&Regards
     Honza

**Comment by stefwalter** [comment]
Not a Cockpit bug.
