### ISSUE TITLE
DBus method GetActive() from org.freedesktop.Notifications -> /org/gnome/ScreenSaver -> org.gnome.ScreenSaver interface doesn't return the expected value

### ISSUE THREAD

**Issue by q2dg** [cockpit-project/cockpit#14085]
Cockpit version: 213-1
OS: Fedora 30

Hello.
I have a custom page (built from "pinger" example" with two buttons that remotely activate and desactivate respectively the screensaver of a Fedora Workstation 30 (where the Cockpit server is running) besides a message showing if it is already activated or not. The activation/desactivation works fine...but the desired message doesn't. 

As you can see in screenshot below (where implemented Javascript code is shown too), it seems GetActive() method (from "org.gnome.ScreenSaver" interface from "/org/gnome/ScreenSaver" object from "org.freedesktop.Notification DBus service) doesn't return the expected value ("true" or "false") but some strange Javascript function definition. 

![Captura de pantalla de 2020-05-14 02-19-17](https://user-images.githubusercontent.com/7274874/81879437-172c6680-958b-11ea-8a43-78a3463d3bb6.png)

If I do the DBus call inside a local terminal (like this, _busctl --user call org.gtk.Notifications /org/gnome/ScreenSaver org.gnome.ScreenSaver GetActive_ ) it works because I obtain the expected value "b false". So it seems there's something wrong with this specific method and Cockpiit (or I've done a mistake, which is the most probable). Anyway, it's a bit strange because the other method used, SetActive(), works perfectly.

Thanks a lot!

P.S: For completeness, I show you the prototype of GetActive() method in next screenshot

![Captura de pantalla de 2020-05-14 02-20-46](https://user-images.githubusercontent.com/7274874/81879509-4d69e600-958b-11ea-9fe7-5380bb7f913c.png)

**Comment by marusak** [comment]
Have you tried using `proxy.call()`?
https://cockpit-project.org/guide/latest/cockpit-dbus.html

**Comment by martinpitt** [comment]
Hello Osqui,

Osqui LittleRiver [2020-05-13 17:35 -0700]:
> As you can see in screenshot below (where implemented Javascript code is shown too), it seems GetActive() method (from "org.gnome.ScreenSaver" interface from "/org/gnome/ScreenSaver" object from "org.freedesktop.Notification DBus service) doesn't return the expected value ("true" or "false") but some strange Javascript function definition. 

That's a promise -- like pretty much anything in JS, a D-Bus call isn't
synchronous, but you need to wait until the promise succeeds or fails.
Something like

interf.GetActive()
       .then(result => { span_status.innerHTML = result.toString() })
       .catch(ex => console.warn("GetActive failed:", ex.toString()));

But moreover, you don't need to call that method in the first place -- the
ActiveChanged signal already delivers you the boolean answer, so you can just
directly use that.

Martin

**Comment by q2dg** [comment]
Ooooh, yes, it works with the code you provided, @martinpitt 
Thanks a lot!!! A LOT!!!
Now I csn see the logic very clearly, thanks!

In fact, knowing this I've tried to find this in documentation (https://cockpit-project.org/guide/latest/cockpit-dbus) and yes, it's already explained in this sentence: 
"All DBus methods on the interface that start with an upper case letter (as is convention) will be automatically defined on this proxy. These methods are called with arguments as normal javascript arguments. A Promise that will complete successfully when the method returns, or fail if an error occurs. The return values from the DBus method will be passed to the then handler function directly."

But I have to confess that I've read this doc many times but it is a little difficult to follow for me without a factual example. Maybe this life-saver post (https://cockpit-project.org/blog/using-dbus-from-javascript-in-cockpit.html) should be updated accordingly.

Thanks!!!!!
