### ISSUE TITLE
Add Machine then logout and log back in again and machine can't connect

### ISSUE THREAD

**Issue by WebCoderUk** [cockpit-project/cockpit#14084]
Cockpit version: 215.
OS: Ubuntu 18.04.4 LTS 
Steps to reproduce

1. Add server
2. Logout
3. Log back in

selinux is not installed on the server.

**Comment by martinpitt** [comment]
What exactly happens at step 3? Please provide screenshots, descriptions, etc. This does generally work (we have automatic tests for this).

**Comment by marusak** [comment]
No reply, closing.
