### ISSUE TITLE
webpack-watch: Confusing behavior when two copies are running

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#14087]
I already had a webpack-watch process runing in a terminal somewhere but I forgot about that and I have started a second one for the same component. The second one would do the initial build and then exit without any extra message.

I can't reproduce this anymore. Now the second process does the initial build and then keeps running but does nothing. The first process correctly does the incremental builds, and the second one is not triggered. That's arguably correct, but confusing.

If the second process is for a different page than the first, I see the same behavior: the first keeps running correctly, the second does nothing. Because the first process is for a different page, the page of the second process does not get rebuilt.

So if we can detect that webpack-watch is already running, the second process could give a clear error, or maybe kill the first process.

**Comment by martinpitt** [comment]
Unfortunately node.js doesn't have an API for flock() -- but we could wrap it around the node.js invocation somehow? Maybe even right in the shebang?

**Comment by martinpitt** [comment]
> If the second process is for a different page than the first, I see the same behavior:

I cannot reproduce this. I regularly do this, e.g. having one watch for `base1` and another one for `systemd`. Whichever package I touch, the correct webpack-watch runs and updates dist/.

I also get a different behaviour when two webpack-watches are running for the *same* webpack -- then both rebuild the page, and whichever one finishes last wins. That's not completely wrong, but confusing indeed.

> Maybe even right in the shebang?

That's too much for the shebang.

I.e. there's no good place to add an flock to, we'd have to wrap the whole webpack-make into a shell scripts. I honestly don't feel motivated enough to actually do this, as it's ugly. @mvollmer, do you still care about this? I'm inclined to just close it.

**Comment by mvollmer** [comment]
> do you still care about this? I'm inclined to just close it.

No, I think I am more careful now, or there is indeed no issue anymore.
