### ISSUE TITLE
Raid device shows in Storage panel as "0"

### ISSUE THREAD

**Issue by jhford** [cockpit-project/cockpit#14094]
Cockpit version: 217-1
OS: Fedora 32 Server
Page: `/storage`

In the storage panel, my raid volume (`/dev/md0`) shows up in the list of devices as just "0".  This seems like a bug of some sort, as "0" isn't a very descriptive name.  The volume groups which show up there have a much more descriptive name like "vg_fedora" and "vg_storage". I am not aware of any way to name raid volumes.  I looked at `pkg/storaged/mdraid-details.jsx` a bit but couldn't find the place where the name is set exactly.

This is the dom node:
#devices > table > tbody > tr:nth-child(1) > td > div > div.sidepanel-row-name 

<img width="279" alt="Screenshot 2020-05-15 at 12 46 36" src="https://user-images.githubusercontent.com/607353/82042484-efff9300-9677-11ea-9072-81fbb5d29c1f.png">

**Comment by marusak** [comment]
That just seems like its name. When you create RAID in cockpit you can pick name.
![name](https://user-images.githubusercontent.com/12330670/114010771-c5f12980-9864-11eb-935a-0a0d61a428d2.png)

Normally default values (to my knowledge) are 127, then 126... so I am not surprised it is just a number. Also `/dev/md/0` confirms my suspicion. When I create raid and name it `foo` it will use `/dev/md/foo`.
