### ISSUE TITLE
Possible to install on Amazon Linux 2?

### ISSUE THREAD

**Issue by jabza** [cockpit-project/cockpit#14117]
Hi,

I'd be interested in using Cockpit, but so far have been unable to find a way to install on my Amazon Linux 2 box. I might try installing from source if all else fails, but it would be nice if it was supported.

Thanks!

**Comment by KKoukiou** [comment]
Since Amazon Linux 2 is RHEL-7 based, you can try fetching the RPM from the centos-7 repositories.
Seems people successfully use EPEL packages from on Amazon Linux - might worth to give it a try.

**Comment by mfsiat** [comment]
Hello, 
I was also trying to install cockpit on my was ec2. But unfortunately searching from both epel and amazon-linux-extras i couldn't find the cockpit application. Could anyone help me with this?

**Comment by martinpitt** [comment]
@mfsiat : Was that an instance with Amazon Linux? (You can have pretty much any operating system on your instances). Our [COPR](https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/) is the last-ditch fallback for RPM based distros which don't otherwise ship cockpit, you can use that.

**Comment by mfsiat** [comment]
Thank you for the comment @martinpitt , from your link i'm using the epel centos 8 version. But unfortunately after adding it on the repo list and installing it, it gives me some dependency problems. is there any other easy way i could install it? I have configured cockpit on redhat i got no issues on that but as i have existing running servers i need to monitor i can not switch the os now. 
If there are any easy solutions please give me a heads up. 
Thank you

**Comment by martinpitt** [comment]
@mfsiat : Without some information what OS is running in your instance, and what the precise error message is, I'm afraid we can't help you.

**Comment by mfsiat** [comment]
Hello,
@martinpitt my os information is given below
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

And below is the hostnamectl 
```
Operating System: Amazon Linux 2
CPE OS Name: cpe:2.3:o:amazon:amazon_linux:2 
Kernel: Linux 4.14.225-169.362.amzn2.x86_64
Architecture: x86-64
```

**Comment by martinpitt** [comment]
Thanks @mfsiat : Seems this is loosely CentOS based, but neither on 7 nor 8 properly then. What are the "dependency problems"?

**Comment by mfsiat** [comment]
Hello 
the problems that i'm facing is given below 
```
Error: Package: cockpit-ws-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:grou
p_cockpit:cockpit-preview)
           Requires: libsystemd.so.0(LIBSYSTEMD_237)(64bit)
Error: Package: cockpit-bridge-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:
group_cockpit:cockpit-preview)
           Requires: libc.so.6(GLIBC_2.27)(64bit)
Error: Package: cockpit-bridge-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:
group_cockpit:cockpit-preview)
           Requires: libssh.so.4(LIBSSH_4_7_0)(64bit)
Error: Package: cockpit-ws-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:grou
p_cockpit:cockpit-preview)
           Requires: libsystemd.so.0(LIBSYSTEMD_227)(64bit)
Error: Package: cockpit-ws-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:grou
p_cockpit:cockpit-preview)
           Requires: libgnutls.so.30()(64bit)
Error: Package: cockpit-system-245-1.el8.noarch (copr:copr.fedorainfracloud.org:
group_cockpit:cockpit-preview)
           Requires: sos
Error: Package: cockpit-ws-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:grou
p_cockpit:cockpit-preview)
           Requires: libc.so.6(GLIBC_2.27)(64bit)
Error: Package: cockpit-ws-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:grou
p_cockpit:cockpit-preview)
           Requires: libgnutls.so.30(GNUTLS_3_4)(64bit)
Error: Package: cockpit-bridge-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:
group_cockpit:cockpit-preview)
           Requires: libssh.so.4(LIBSSH_4_5_0)(64bit)
Error: Package: cockpit-ws-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:grou
p_cockpit:cockpit-preview)
           Requires: libcrypt.so.1(XCRYPT_2.0)(64bit)
Error: Package: cockpit-ws-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:grou
p_cockpit:cockpit-preview)
           Requires: libsystemd.so.0(LIBSYSTEMD_221)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by mfsiat** [comment]
> Hello
> the problems that i'm facing is given below
> 
> ```
> Error: Package: cockpit-ws-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:grou
> p_cockpit:cockpit-preview)
>            Requires: libsystemd.so.0(LIBSYSTEMD_237)(64bit)
> Error: Package: cockpit-bridge-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:
> group_cockpit:cockpit-preview)
>            Requires: libc.so.6(GLIBC_2.27)(64bit)
> Error: Package: cockpit-bridge-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:
> group_cockpit:cockpit-preview)
>            Requires: libssh.so.4(LIBSSH_4_7_0)(64bit)
> Error: Package: cockpit-ws-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:grou
> p_cockpit:cockpit-preview)
>            Requires: libsystemd.so.0(LIBSYSTEMD_227)(64bit)
> Error: Package: cockpit-ws-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:grou
> p_cockpit:cockpit-preview)
>            Requires: libgnutls.so.30()(64bit)
> Error: Package: cockpit-system-245-1.el8.noarch (copr:copr.fedorainfracloud.org:
> group_cockpit:cockpit-preview)
>            Requires: sos
> Error: Package: cockpit-ws-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:grou
> p_cockpit:cockpit-preview)
>            Requires: libc.so.6(GLIBC_2.27)(64bit)
> Error: Package: cockpit-ws-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:grou
> p_cockpit:cockpit-preview)
>            Requires: libgnutls.so.30(GNUTLS_3_4)(64bit)
> Error: Package: cockpit-bridge-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:
> group_cockpit:cockpit-preview)
>            Requires: libssh.so.4(LIBSSH_4_5_0)(64bit)
> Error: Package: cockpit-ws-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:grou
> p_cockpit:cockpit-preview)
>            Requires: libcrypt.so.1(XCRYPT_2.0)(64bit)
> Error: Package: cockpit-ws-245-1.el8.x86_64 (copr:copr.fedorainfracloud.org:grou
> p_cockpit:cockpit-preview)
>            Requires: libsystemd.so.0(LIBSYSTEMD_221)(64bit)
>  You could try using --skip-broken to work around the problem
>  You could try running: rpm -Va --nofiles --nodigest
> ```

@martinpitt could you please give me some hints on this!!!!

**Comment by martinpitt** [comment]
@mfsiat : That means that this Amazon Linux is older than CentOS/RHEL 8, and thus not compatible with the builds in the COPR. We don't have a (and I'm not aware of) a cockpit build for Amazon Linux.

**Comment by mfsiat** [comment]
Thank you for the reply

**Comment by FrankFioretti** [comment]
Is this still the case? I realize this is a very old thread but I am running into the same issue with AMZL2 and cockpit.

**Comment by FrankFioretti** [comment]
I spent a day on this. No idea if newer/different versions work, but this does:

yum install http://mirror.centos.org/centos/7/os/x86_64/Packages/cockpit-bridge-195.10-1.el7.centos.x86_64.rpm

yum install http://mirror.centos.org/centos/7/os/x86_64/Packages/cockpit-system-195.10-1.el7.centos.noarch.rpm

yum install http://mirror.centos.org/centos/7/os/x86_64/Packages/cockpit-ws-195.10-1.el7.centos.x86_64.rpm

yum install http://mirror.centos.org/centos/7/os/x86_64/Packages/cockpit-195.10-1.el7.centos.x86_64.rpm

systemctl enable cockpit.socket

systemctl start cockpit.socket

Your mileage may vary, but this works for me on Amazon Linux 2.

**Comment by garrett** [comment]
Note: Cockpit 195 is _ancient_. It was released in 2019-05-29 — exactly 3 years ago, later this week — and even predates the switch to PatternFly 4. So much has changed since then.

(I'm not saying "don't do this", I'm just letting you know that what you're installing is extremely old at this point in time.)

Relatedly: It's probably noteworthy to mention that the next version of Amazon Linux, Amazon Linux 2022, is based on Fedora. It would have much more recent packages of everything. However, it's still in a preview state at this time. (It was first announced toward the end of 2021, so it's surprising it's been in preview for so long. Hopefully it'll be officially released soon.)

https://aws.amazon.com/linux/amazon-linux-2022/
https://aws.amazon.com/linux/amazon-linux-2022/faqs/

**Comment by FrankFioretti** [comment]
Yeah, I did attempt newer versions (24x-26x) but they all sent me down a dependency/conflict death spiral. 

I’m amazed that there hasn’t been any progress on an officially supported release for Amazon Linux since this thread was created, but after so much trial and error I was equally amazed that I got it to work at all.

I will take a look at AMZ2-2022 and see where that leads me.

**Comment by garrett** [comment]
> Fedora 34

Wow, that's unfortunate timing. As Fedora 36 was just released, [34 is soon to be EOL (2022-06-07)](https://fedorapeople.org/groups/schedule/f-34/f-34-key-tasks.html) and won't get any updates at that time. Hopefully Amazon's "preview" that is "subject to change" updates to 36 before it's marked as not a preview... else they'll have to do a lot of backporting.

But [241](https://cockpit-project.org/blog/cockpit-241.html) is _much_ more recent than [195](https://cockpit-project.org/blog/cockpit-195.html) ("only" a couple months over 1 year old versus 3 years old), so that's definitely an improvement.
