### ISSUE TITLE
Reduce expiration time of self-signed cert, and auto-renew it

### ISSUE THREAD

**Issue by paulhargreaves** [cockpit-project/cockpit#14121]
Cockpit version: 219
OS: Arch
Page: Login

I'm having trouble TLS with various browsers, especially safari on iOS. For example, I just can't log in at all on iOS and get messages in journalctl like this:

`cockpit-tls[3455082]: cockpit-tls: gnutls_handshake failed: The TLS connection was non-properly terminated.`

One thing I notice is that the certificate being generated doesn't appear to be valid:

From the journalctl:
`remotectl[3328058]: Generating temporary certificate using: openssl req -x509 -days 36500 -newkey rsa:2048 -keyout /etc/cockpit/ws-certs.d/0-self-signed...{snip}`

--days 36500 is the question. Where does 36500 come from, and why?
A few years ago it looks like the max limit was fixed at 2 years:  [https://www.globalsign.com/en/blog/ssl-certificate-validity-capped-at-maximum-two-years](https://www.globalsign.com/en/blog/ssl-certificate-validity-capped-at-maximum-two-years)

What is the correct way of altering the length of time? I don't see anything [https://cockpit-project.org/guide/latest/remotectl.8](https://cockpit-project.org/guide/latest/remotectl.8)

**Comment by martinpitt** [comment]
Indeed remotectl [creates the cert](https://github.com/cockpit-project/cockpit/blob/master/src/ws/cockpitcertificate.c#L156) with a 100 year lifetime. I suppose we should follow suit, and remotectl should check and automatically renew the self-signed certificate if it is past, or near, expiration.

In the meantime, feel free to [install your own certificate](https://cockpit-project.org/guide/latest/https.html#https-certificates).

**Comment by jrlepage** [comment]
I am having the same issue with TLS error: "cockpit-tls: gnutls_handshake failed: The TLS connection was non-properly terminated." Any suggestions for troubleshooting this? Running cockpit on Ubuntu Server 20.04 LTS and accessing Cockpit on iOS device (same error with Safari and Chrome on iOS).

**Comment by martinpitt** [comment]
@jrelepage: Safari is known to not like Cockpit's default certificates, see e. g. issue #10146, issue #13174 , etc. This may be related to Safari rejecting certificates with a long life span, or something else. You can try a different browser, or creating and [installing your own certificate](https://cockpit-project.org/guide/latest/https.html#https-certificates).

**Comment by jrlepage** [comment]
Thanks, but strangely it’s happening with both Safari, Chrome, and Firefox on iOS. I’m able to access it on the localhost with Firefox, but elsewhere I get the GnuTLS handshake error. I will try to install my own certificate.
