### ISSUE TITLE
Alternative for networkmanager

### ISSUE THREAD

**Issue by paulhargreaves** [cockpit-project/cockpit#14124]
Page: Network

Network is blank.
This is because, on arch, I'm using systemd networking.

There are other issues where the solution appears to be 'run networkmanager and switch your networking over to networkmanager' but that isn't really a great answer.

So, this request is for some basic networking info to be available even if networking manager isn't available.

**Comment by andreasn** [comment]
The expectation right now is that the Networking page uses networkmanager, hence why the source directory is named as such (see https://github.com/cockpit-project/cockpit/tree/master/pkg/networkmanager), and most distributions tend to call the package that include those bits cockpit-networkmanager.
It should be possible to create an alternative systemd networkd implementation using starter-kit as a start and ship it outside the main repository, as an alternative.
https://github.com/cockpit-project/starter-kit

**Comment by martinpitt** [comment]
We won't do this inside of the Cockpit project itself, at least anytime soon, sorry. Of course an external project that provides a page for networkd or similar would be nice, and we are happy to provide some guidance -- but we don't have the resources to do that ourselves.
