### ISSUE TITLE
Vagrantfile uses wrong Fedora version

### ISSUE THREAD

**Issue by yarons** [cockpit-project/cockpit#14128]
The Vagrantfile point to Fedora version 29 while it's no longer available (404), I changed it manually to 32 just to see if it works and the error message disappeared but I'm not sure it's working yet.

**Comment by yarons** [comment]
Nope, sorry 32 is no good either:

```
    default: Error: Unable to find a match: atomic
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by marusak** [comment]
Vagrantfile was dropped in https://github.com/cockpit-project/cockpit/commit/97a0e1c9f526a27967b5163a079f2e37da6ec3ad
