### ISSUE TITLE
Raspbian - Not authorized to perform operation

### ISSUE THREAD

**Issue by littlemax28** [cockpit-project/cockpit#14136]
Cockpit version: 188-1
OS: Raspbian GNU/Linux 10 (buster), armv61, Raspberry Pi B
Page: Permissions
On any actions I get "Not authorized to perform operation" message

I read that it is looks for wheel group. I has no wheel group. I added it and added pi-user to that group but it still shows that error.
Via ssh I can do operations with sudo. 

`journalctl --since -10m` if the issue happened in the last 10 minutes

> -- Logs begin at Fri 2020-05-22 21:17:03 BST, end at Fri 2020-05-22 22:17:27 BST. --
May 22 22:11:15 raspberrypi cockpit-bridge[1292]: cannot reauthorize identity(s): unix-user:root
May 22 22:11:15 raspberrypi polkitd(authority=local)[315]: Operator of unix-session:c4 FAILED to authenticate to gain authori
May 22 22:11:25 raspberrypi cockpit-bridge[1292]: cannot reauthorize identity(s): unix-user:root
May 22 22:11:25 raspberrypi polkitd(authority=local)[315]: Operator of unix-session:c4 FAILED to authenticate to gain authori
May 22 22:11:28 raspberrypi cockpit-ws[859]: Logging out session from 192.168.1.107
May 22 22:11:28 raspberrypi cockpit-ws[859]: WebSocket from 192.168.1.107 for session closed
May 22 22:11:29 raspberrypi polkitd(authority=local)[315]: Unregistered Authentication Agent for unix-session:c4 (system bus
May 22 22:11:29 raspberrypi cockpit-session[1281]: pam_unix(cockpit:session): session closed for user pi
May 22 22:11:29 raspberrypi systemd-logind[277]: Session c4 logged out. Waiting for processes to exit.
May 22 22:11:29 raspberrypi sudo[1313]: pam_unix(sudo:session): session closed for user root
May 22 22:11:29 raspberrypi systemd[1]: session-c4.scope: Succeeded.
May 22 22:11:29 raspberrypi systemd-logind[277]: Removed session c4.
May 22 22:11:41 raspberrypi cockpit-session[1438]: pam_ssh_add: Failed adding some keys
May 22 22:11:41 raspberrypi cockpit-session[1438]: pam_unix(cockpit:session): session opened for user pi by (uid=0)
May 22 22:11:41 raspberrypi systemd-logind[277]: New session c5 of user pi.
May 22 22:11:41 raspberrypi systemd[1]: Started Session c5 of user pi.
May 22 22:11:42 raspberrypi polkitd(authority=local)[315]: Registered Authentication Agent for unix-session:c5 (system bus na
May 22 22:11:42 raspberrypi cockpit-ws[859]: logged in user session
May 22 22:11:42 raspberrypi cockpit-bridge[1449]: invalid or unusable locale: en_US.UTF-8
May 22 22:11:44 raspberrypi cockpit-ws[859]: New connection to session from 192.168.1.107
May 22 22:11:45 raspberrypi dbus-daemon[235]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit=
May 22 22:11:45 raspberrypi systemd[1]: Starting Hostname Service...
May 22 22:11:46 raspberrypi dbus-daemon[235]: [system] Successfully activated service 'org.freedesktop.hostname1'
May 22 22:11:46 raspberrypi systemd[1]: Started Hostname Service.
May 22 22:11:48 raspberrypi cockpit-bridge[1449]: cannot reauthorize identity(s): unix-user:root
May 22 22:11:48 raspberrypi polkitd(authority=local)[315]: Operator of unix-session:c5 FAILED to authenticate to gain authori
May 22 22:11:48 raspberrypi pkexec[1461]: pi: Error executing command as another user: Not authorized [USER=root] [TTY=unknow
May 22 22:11:48 raspberrypi cockpit-bridge[1449]: Error executing command as another user: Not authorized
May 22 22:11:48 raspberrypi cockpit-bridge[1449]: This incident has been reported.
May 22 22:11:49 raspberrypi sudo[1467]:       pi : TTY=unknown ; PWD=/run/user/1000 ; USER=root ; COMMAND=/usr/bin/cockpit-br
May 22 22:11:49 raspberrypi sudo[1467]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
May 22 22:11:50 raspberrypi dbus-daemon[235]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit
May 22 22:11:50 raspberrypi systemd[1]: Starting PackageKit Daemon...
May 22 22:11:51 raspberrypi PackageKit[1477]: daemon start
May 22 22:11:52 raspberrypi dbus-daemon[235]: [system] Successfully activated service 'org.freedesktop.PackageKit'
May 22 22:11:52 raspberrypi systemd[1]: Started PackageKit Daemon.
May 22 22:12:12 raspberrypi PackageKit[1477]: get-updates transaction /32_cebbcecd from uid 0 finished with success after 174
May 22 22:12:18 raspberrypi cockpit-bridge[1449]: cannot reauthorize identity(s): unix-user:root
May 22 22:12:18 raspberrypi polkitd(authority=local)[315]: Operator of unix-session:c5 FAILED to authenticate to gain authori
May 22 22:12:23 raspberrypi PackageKit[1477]: get-updates transaction /33_daeecbca from uid 0 finished with success after 101
May 22 22:12:23 raspberrypi systemd[1]: systemd-hostnamed.service: Succeeded.
May 22 22:14:03 raspberrypi cockpit-bridge[1449]: cannot reauthorize identity(s): unix-user:root
May 22 22:14:03 raspberrypi polkitd(authority=local)[315]: Operator of unix-session:c5 FAILED to authenticate to gain authori
May 22 22:15:46 raspberrypi udisksd[256]: Error performing housekeeping for drive /org/freedesktop/UDisks2/drives/WDC_WD1600B
May 22 22:17:01 raspberrypi CRON[1519]: pam_unix(cron:session): session opened for user root by (uid=0)
May 22 22:17:01 raspberrypi CRON[1523]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May 22 22:17:01 raspberrypi CRON[1519]: pam_unix(cron:session): session closed for user root
May 22 22:17:27 raspberrypi PackageKit[1477]: daemon quit
May 22 22:17:27 raspberrypi systemd[1]: packagekit.service: Main process exited, code=killed, status=15/TERM
May 22 22:17:27 raspberrypi systemd[1]: packagekit.service: Succeeded.

pi@raspberrypi:~ $ ps aux | grep cockpit-bridge

> pi        1449  3.2  1.8  49184  8216 ?        Sl   22:11   0:20 cockpit-bridge
> root      1467  0.0  0.7   9932  3256 ?        S    22:11   0:00 /usr/bin/sudo -A cockpit-bridge --privileged
> root      1472  1.0  1.8  46972  8172 ?        Sl   22:11   0:06 cockpit-bridge --privileged
> pi        1547  0.0  0.4   7464  2052 pts/0    S+   22:22   0:00 grep --color=auto cockpit-bridge

**Comment by martinpitt** [comment]
Don't worry about the `wheel` group -- that's for Fedora/RHEL. On Debian/Ubuntu/Raspbian, the standard group for administrators is `sudo`, and the `pi` user is in it by default. It seems that you *do* get a root cockpit-bridge, and thus the UI should be able to run privileged operations -- can you confirm? I. e. is your bug report about the UI not working, or just about these journal messages from polkit?

**Comment by littlemax28** [comment]
The problem that I cannot run privileged operations. For example, I'm trying to mount partition and getting the same error - check the screenshot.
![изображение](https://user-images.githubusercontent.com/44037530/82733272-686eef80-9d1b-11ea-8d46-940b3d4dd0fa.png)

**Comment by martinpitt** [comment]
Ah, this is still version 188 -- this was fixed in commit 168f819ebd0. This happens if you can run `sudo` through sudoers, but *not* through polkit. So this is fixed in version 215, which you can find in buster-backports.
