### ISSUE TITLE
Terminal is reseting at session lose

### ISSUE THREAD

**Issue by Vildnex** [cockpit-project/cockpit#14137]
Cockpit version: 219
OS: Ubuntu 20.04 Server
Page: Terminal

Whenever I'm doing something in terminal like a long process of downloading something for example which has some output that will be displayed on the terminal to show the process is going to disappear (the terminal is going to be clean up) whenever I'm going to reconnect to the server (every time when I'm losing the session).
In other words my terminal will be empty even though my server is going to download my files without showing me any output.
Is there any way to keep something like a global state of the terminal per user? 

Thanks.

**Comment by martinpitt** [comment]
No, there isn't in Cockpit; that's similar to ssh, VTs, or regular GNOME terminals. If you need that, use tools like screen, tmux, or byobu. They should work just fine in Cockipt's terminal as well.
