### ISSUE TITLE
Allow expanding truncated service log entrys

### ISSUE THREAD

**Issue by TheTrueColonel** [cockpit-project/cockpit#14134]
Page: Services

In a service's logs, when the entry is truncated allow a quick way to view the entire log entry (e.g. Popup, dropdown, etc.)

**Comment by marusak** [comment]
In the newest release we enable to click on each entry and go to the full log details.
I am not really sure if clobbering the UI with such elements is a good idea.

**Comment by KKoukiou** [comment]
I agree jumping to the logs page is the right think to do in this case, services page it's just to give some hint of the most recent logs.
