### ISSUE TITLE
Memory graphs

### ISSUE THREAD

**Issue by manugd14** [cockpit-project/cockpit#14131]
Cockpit version: 164
OS: Ubuntu 16.0.4
Page: 

The graph about RAM memory on system overview (which is correct according to the free-m output) does not correlate with the graph you get when you click on "memory" (this one seems to be accounting for the cached memmory twice). 

Steps to reproduce

1. free -m
2. system overview
3. memmory detailed overview
![pc2](https://user-images.githubusercontent.com/54359435/82662214-c0c7c380-9c2d-11ea-89b9-0f8d3b3d9a94.png)
![pc3](https://user-images.githubusercontent.com/54359435/82662216-c1605a00-9c2d-11ea-856d-a77467994c0c.png)
![pc1](https://user-images.githubusercontent.com/54359435/82662217-c1605a00-9c2d-11ea-8281-45bbbc035a61.png)

**Comment by manugd14** [comment]
Seems to be discussed in #14131 but no conclusions reached.

**Comment by tbabej** [comment]
Issue #1069 was originally fixed here by my PR https://github.com/cockpit-project/cockpit/pull/1775, which addressed the double-counting: 5ea06f9ab4244ae5cf1cc5350312e7b88bfaa239

@stefwalter I think this is a regression that happened when the original MemoryMonitor legacy code was dropped in favor of using metrics channels, see: 04ed4822eab614e9d435afda837ab236e6b61296

**Comment by tbabej** [comment]
It seems to me that fixing this could just require simple modification to the bridge: https://github.com/cockpit-project/cockpit/blob/38104037fd2267e056827c9dd5d70e99ab664de4/src/bridge/cockpitmemorysamples.c#L75-L79

Where
```
cockpit_samples_sample (samples, "memory.used", NULL, (total_kb - available_kb) * 1024); 
```

needs to be modified to 

```
cockpit_samples_sample (samples, "memory.used", NULL, (total_kb - available_kb - buffer_kb - cached_kb) * 1024); 
```

**Comment by KKoukiou** [comment]
Dashboard has been deprecated and now memory usage information can be obtained from the metrics page which has different graphs, than the ones that were presented here.
Therefore I am closing this issue.
