### ISSUE TITLE
shell: Can't remove current host

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#14150]
When a host is current, it can't be removed from the host switcher:

![image](https://user-images.githubusercontent.com/3228183/82797681-1bf0f480-9e80-11ea-9931-8750a301be32.png)

I have to explicitly navigate away before I am able to remove it:

![image](https://user-images.githubusercontent.com/3228183/82797765-3dea7700-9e80-11ea-91f7-52ad952a4e54.png)

I find that annoying and it feels like the machine makes me do work for no good reason.

**Comment by marusak** [comment]
It is so you cannot remove host under yourself.
What behaviour would you expect when you remove host that you are currently on?

**Comment by mvollmer** [comment]
> What behaviour would you expect when you remove host that you are currently on?

I expect to automatically be switched to some other host, most probably the primary one.
