### ISSUE TITLE
inline help in logs goes away when I try to click it

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#14163]
Cockpit version: 218
OS: Fedora
Page: Logs

Been playing around with the new inline help in Logs. Works great in general, but when I try to copy the journald syntax by selecting it, the help bubble goes away.
This is not how the help bubble in Network bonding works. That one only activates/deactivates when you click the icon. I think that's a better behaviour.

**Comment by marusak** [comment]
Hmm, interesting. I made sure it does not disappear when one copies the command, but I guess it it not ideal still.
I'll take a look, thanks for the testing!

**Comment by KKoukiou** [comment]
Looks wrong to use dropdown here, we should use https://www.patternfly.org/v4/documentation/core/components/popover probably.

**Comment by andreasn** [comment]
This issue also came up in one of our usability testing sessions recently.
