### ISSUE TITLE
known host file with @cert-authority not working

### ISSUE THREAD

**Issue by reawakn** [cockpit-project/cockpit#14175]
Cockpit version: 211.3
OS: ol 8.2

/etc/ssh/ssh_known_hosts
@cert-authority xxxxxx

journal-log:
error: cockpit-ssh machine: ecdsa-sha2-nistp256 host key for server is not known:

with openssh client is the handshake no problem

**Comment by martinpitt** [comment]
Cockpit uses libssh to do all SSH operations. Can you please file this at https://bugs.libssh.org/ instead? Thanks!
