### ISSUE TITLE
Add method to prevent retrieving contents with File.watch

### ISSUE THREAD

**Issue by malbrec2** [cockpit-project/cockpit#14188]
Currently File.watch() automatically retrieves the content of a file when it changes and passes that to the callback.  In some cases (ie: watching an sqlite database or tracking the size of a file) the content of the file may be unimportant or unreadable, but a change in the file should trigger an action.  This is especially important when calling watch() on large files, where a too-large error may be thrown.

A flag could be added to the File options object or watch() function call to control the behavior.
Alternately, the signature of the callback passed to watch() could be inspected to determine if it has enough arguments for the contents and/or tag, and ignore the read() if there aren't enough arguments.

**Comment by martinpitt** [comment]
I'm not a big fan of signature inspection, as (1) that's too magic, and (2) functions could use `arguments` instead. But adding a flag sounds fine. It would look a bit odd, as it needs to be a negative -- the default needs to be kept for backwards compatibility. 

This only applies to the cockpit.js `cockpit.watch()` function, though. If you use an [fswatch1 channel](https://github.com/cockpit-project/cockpit/blob/master/doc/protocol.md#payload-fswatch1) directly, with [cockpit.channel()](https://cockpit-project.org/guide/latest/cockpit-channels.html), then this skips the extra `read()` and just gives you the change notifications.

**Comment by martinpitt** [comment]
@malbrec2 : I sent PR #15689 to implement this. You can now do `cockpit.file(...).watch(callback, { read: false })`. Does that work for you?
