### ISSUE TITLE
Terminal font letter spacing is huge on Linux (not on Windows)

### ISSUE THREAD

**Issue by mattfbacon** [cockpit-project/cockpit#14183]
I've only tested this on Windows 10 and Arch Linux, but I've only had the problem on Arch, in Chrome, Konqueror, Vivaldi, and GNOME Web.
Essentially, the each character in the terminal is its normal width, but the space around it is doubled, so each character takes up the space of two. [Here's some images from Chrome](https://imgur.com/a/tkVrLFL).
And as I said, on Windows it's not an issue.
If it's important, the server is on Fedora Server 32.

**Comment by mattfbacon** [comment]
This may be an issue with xterm.js.

**Comment by marusak** [comment]
I see you opened https://github.com/xtermjs/xterm.js/issues/2963 and you have the same issue on xterm.js demo as well (so unrelated to cockpit).
I am closing this. If the resolution is going to be we need some additional options, please reopen and I'll fix it.

**Comment by Winson-Huang** [comment]
hi, there is a [solution](https://github.com/xtermjs/xterm.js/issues/2963#issuecomment-812031516) in xtermjs/xterm.js#2963 now, could you please add this to cockpit? Thank you very much! @marusak
