### ISSUE TITLE
"systemctl enable cockpit" do not work as expected

### ISSUE THREAD

**Issue by cypa** [cockpit-project/cockpit#14204]
Cockpit version: any
OS: CentOS
Page: 

why "PermissionsStartOnly=true" is in systemd cockpit.service file?

Steps to reproduce

1. # yum install cockpit
2. # systemctl enable cockpit
3. check if cockpit service is enabled - it is not: 
# systemctl status cockpit 
● cockpit.service - Cockpit Web Service
   Loaded: loaded (/usr/lib/systemd/system/cockpit.service; static; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:cockpit-ws(8)

from IRC chat:
<cypa> PermissionsStartOnly=true prevents cockpit to be enabled in systemd, e.g. to start on bootup
<cypa> with PermissionsStartOnly=true cockpit.service can only be started manually
<cypa> I guess I should remove it
<cypa> I wonder why is it in the repo?

**Comment by cypa** [comment]
oops! looks like there's no [Install] section in the cockpit.service file

**Comment by martinpitt** [comment]
`systemctl enable cockpit` is wrong -- the correct command is

    systemctl enable --now cockpit.socket

See https://cockpit-project.org/running.html#centos

`PermissionsStartOnly=true` is because the `remotectl` command in `ExecStartPre=` needs to run as root, but the main process `cockpit-tls` should run as unprivileged system user.

**Comment by martinpitt** [comment]
I sent PR #14207 to replace the deprecated `PermissionsStartOnly=`, but that does not make a functional difference.
