### ISSUE TITLE
cockpit:machines Ooops! error when gluster storage pool is defined

### ISSUE THREAD

**Issue by packetloss69** [cockpit-project/cockpit#14239]
Cockpit version: cockpit-machines-211.3-1.el8.noarch
OS: CentOS Linux release 8.2.2004 (Core)
Page: Machines

Oops when creating new VM.

Steps to reproduce

Import gluster based storage domain: 
`virsh pool-define backup1_pool.xml `
``` xml
<pool type="gluster">
  <name>gluster-backup1</name>
  <source>
    <name>backupvol1</name>
    <host name='cl4-storage'/>
    <dir path='/'/>
  </source>
</pool>
```
**Pool does not have to be started for this to occur.**
(FYI: Pool is able to start successfully when `pool-start gluster-backup1`)

Click on "Create VM"  
![image](https://user-images.githubusercontent.com/2039149/84782259-1783ab80-afe8-11ea-9136-95221481a2ec.png)

![image](https://user-images.githubusercontent.com/2039149/84782539-6e898080-afe8-11ea-9d94-61a0a25a8788.png)

No errors in journalctl --since -10m 

Fix: cockpit:machines to work again with creation of new machine: 
`pool-undefine gluster-backup1`
VM can now be created again.

**Comment by KKoukiou** [comment]
@packetloss69 thanks for the report. I sent a fix for this in #14258 - this will be though included in release 222.
