### ISSUE TITLE
Repository channel management plugin

### ISSUE THREAD

**Issue by barnscott** [cockpit-project/cockpit#14246]
Request: A plugin that adds functionality for cockpit to centrally manage multiple custom repository channels. 

With my limited knowledge, I am thinking it would be great if there was a cockpit plugin to configure and manage custom repo channels that other boxes could subscribe to. Note: I do not expect the plugin would subscribe the boxes, i would do that in ansible. The plugin would instead configure and host the repo channels.

This is request would be to fill in the void that Spacewalk has left. Spacewalk conveniently managed all my repo channels, and I expect I will go back to configuring them manually via command line. But a Cockpit plugin would be very helpful.

If there is a better alternative already available, i am all ears.

**Comment by martinpitt** [comment]
What exactly does that mean? Essentially a UI to discover repositories that are available with your subscription, and inspect/enable/disable them? Your "that other boxes could subscribe to" sounds more like the opposite, like you want a tool to *create* and publish repositories?

In general, if your use case fits into "work that a human would do manually" (as opposed to repetitive/mass-scale deployment à la Ansible/chef/puppet) and "the UI can be reasonably represented in a web UI", then a cockpit plugin is a good fit. You get the convenience of web UI development with the power and flexibility of all Linux APIs.

We don't get a lot of demand for either of this (it hasn't come up as a business request so far).

As our team doesn't have much domain knowledge here, this would be a standalone project developed by domain experts, based on [starter-kit](https://cockpit-project.org/blog/cockpit-starter-kit.html). Of course our team will happily assist with getting set up, help with web devel best practices, set up CI/automated releases and so on.

**Comment by barnscott** [comment]
Sorry, I see i wasn't clear at all! Spacewalk has a feature to create "channels", which is a way to centrally manage and organize various repositories.

**User story:**
I want to subscribe my boxes to these two repos, but I see some potential issues:
- Centos repos include geoip-2.10 package.
- OSSEC security monitor repos includes geoip-1.9 package.

Having a linux box subscribe to these two repos can create app compatibility problems. Need a solution to group these two repos into a single "channel". In the channel, I can create filters per repo to ensure I only get geoip package from my preferred source that I have tested with my app. 
Now that I have a tested and approved software update channel, I can subscribe/update my boxes with my new channel _via ansible_.
Outcome: I have greater control over which packages my boxes are getting and it is easier to test and release updates.

**High level scope would include:**
- Repos section: collect remote repos from around web
  - manage any certs needed to connect
  - this section simply indexes my repos, it does not download packages
- Channels: section to aggregate/group any repo's mentioned above into "channels"
  - channels are used to group any repo defined in previous section. optionally, channels can include other channels
  - channels will download packages from associated repos
  - manage optional gpg
  - ability to create regex filters to limit packages that are included from previous repo sections
  - ability to "refresh", or re-download, packages from appropriate repos
  - integrate with cronjob or unitd.timer to "refresh" (pull package updates from repos)
- Package search: section to search for packages across channels/repos to find versions/conflict

In my use case, the "subscription" process for my boxes would be delegated to ansible, so the scope is limited to managing "channels".

Hope that clarifies context. 

With all that said, does this use case fit the general context of a useful cockpit plugin? Or does this request feel out of place for a cockpit plugin? Typically, cockpit plugins provide a UI to manage the single box, but this use case would be managing a small repository management application.

**Comment by martinpitt** [comment]
This isn't (and hasn't so far) bubbled up to our priority list (no customer demand so far). This would be excellent as a standalone extension based on [starter-kit](https://github.com/cockpit-project/starter-kit/), and we'll gladly help anyone who is interested to set this up.

**Comment by marusak** [comment]
As Martin mentioned couple of months ago, this would be an excellent standalone project. The Cockpit core team does not have time and it is very unlikely that we will have time in any foreseeable future for this.
As mentioned above any developer should be able to use starter-kit to create separate plugin and the team is happy to offer help and give guidance.

But since it is nothing actionable for our team I am closing this.
