### ISSUE TITLE
Unable to configure Multiple Machines via SSH

### ISSUE THREAD

**Issue by ehernandez-xk** [cockpit-project/cockpit#14251]
Cockpit version in primary and secondary hosts: 195.6
OS: CentOS 7

I'm unable to configure multiples machines using different users, one to log in and another to connect the hosts.

This is my configuration:

machineA: is the primary server the (web UI)
machineB: is the secondary server

userA: user to login in the web UI, no root access
userB: user to configure the secondary hosts, 

SSH configuration
I'm able to SSH into machineB from MachineA with the userB, without providing the password

I Manually created the file in machineA
/etc/cockpit/machines.d/05-hosts.json

```json
{
    "myhost": {
        "address": "myhost.mycompany.com",
        "visible": true,
        "user": "userB",
        "color": "blue"
    }
}
```
Overall Configuration
I installed cockpit-dashboard in the primary machine,
I can see the secondary host in the webUI but I only see
**Couldn't connect to the machine**
**Cannot connect to an unknown machine**

Any help on what I'm missing, how to troubleshoot?

**Comment by tscswcn** [comment]
how to use this,  if is there a guild  to guils to using cockpit session

**Comment by marusak** [comment]
> I'm able to SSH into machineB from MachineA with the userB, without providing the password

I assume you use ssh key. Do you have that same key assigned in Cockpit? (Top right corner/SSH keys)

**Comment by marusak** [comment]
@ehernandez-xk bump?

**Comment by marusak** [comment]
No reply, closing.
