### ISSUE TITLE
[Question] Does webui expose any REST endpoints?

### ISSUE THREAD

**Issue by leelavg** [cockpit-project/cockpit#14250]
Hi,  

I have gone through documentation and some of the issues in github but not able to find relevant information regarding availability of any REST api which can be consumed by other languages. 

Use case: Add a cluster to management node and query various system stats via a REST endpoint from python (requests/urllib3)

Thanks in advance.

**Comment by martinpitt** [comment]
Cockpit doesn't have a REST API, no. It has a [JSON based WebSocket API](https://github.com/cockpit-project/cockpit/tree/master/doc/protocol.md).
