### ISSUE TITLE
Allow to select which packages to update

### ISSUE THREAD

**Issue by Niondir** [cockpit-project/cockpit#14256]
Page: Updates

Currently it seems to be only possible to update all packages at once. It would be nice if I can select which packages to updates.

**Comment by martinpitt** [comment]
We will not do that. Packages have dependencies, sometimes not spelled out completely correctly, and this kind of "mix and match" is usually not supported by distros (in particular not by Debian/Ubuntu/Fedora). If you want to install packages individually, please use the command line directly (e. g. via the Terminal page or ssh).
