### ISSUE TITLE
Connection is read-only

### ISSUE THREAD

**Issue by devrvk** [cockpit-project/cockpit#14263]
Hello! If i want to change ip address for eth0 , i receive error "Connection is read-only".

**Comment by martinpitt** [comment]
Can you please post a screenshot? Can you do other administrative actions in Cockpit? Does the title bar say "Administrative access" or "Limited access"? Which OS and cockpit package version are you using?

**Comment by marusak** [comment]
Closing due to lack of information, if you can still reproduce please reopen and provide us with more information. Thanks!
