### ISSUE TITLE
gentoo ebuild

### ISSUE THREAD

**Issue by necrose99** [cockpit-project/cockpit#14266]
https://github.com/geaaru/geaaru_overlay/tree/master/app-admin/cockpit
to do update manifest hashes...  via pull request. 
can add to install docs if you like. 

`emerge -av app- app-eselect/eselect-repository <yes/no> `

```
eselect repository add geaaru git https://github.com/geaaru/geaaru_overlay.git 
emerge --sync geaaru
```

`emerge -av app-admin/cockpit`

older layman 
Geaaru Gentoo Overlay:
Installation
```
copy geaaru_overlay.xml file in /etc/layman/overlays directory;
enable option 'overlay_defs' on layman.cfg file
```

**Comment by necrose99** [comment]
https://packages.gentoo.org/packages/app-admin/openrc-settingsd  can fake systemd... 

https://github.com/goose121/initify  (sytemd units > openrc/initd ) can backport units to openrc/etc. 

while i have few qualms with sytemd , persay , if used on a webhost with diskspace contraint$  least used by packages more i an server bin-packages w/o $$ , and host is kvm/quemu image so upgrading kernel... or the like tends to break it.

**Comment by martinpitt** [comment]
@necrose99 : I'm not sure what this report is about; can you please be more specific?

If it's about install instructions on https://cockpit-project.org/running.html: We want to document only packages that are an official part of the corresponding distribution, so that they get a reasonable level of support.

I'm not sure what the "fake systemd" parts mean here -- Cockpit needs systemd, for buliding, for its web server, and most of its pages. With enough hackery you can certainly get *something* to work, but we don't want to advertise that on our upstream docs.

Thanks!

**Comment by necrose99** [comment]
geaaru adding his overlay gives cockpit,  If emerged 
Systemd is required,  and if you have systemd,  should work out of box..  as mentioned  layman older method in adding overlay,  or newr eselect repository 
Just adds to eselect-resposity.conf overlays , and emege sysnc , takes care of tree syncs.. 

Layman has a Portage-sync use flag newer users maynot use, older method works , however breaks at times.. though rarely,  the eselect repository is more encouraged by gentoo devs/support of late. 

Sabayon linux,  calculate,  Google's Chromium os, etc.. are gentoo derivatives.. , 

Openrc-settingsd , a tool for OPENRC,  to run systemd units , or running legacy  units , on systemd  after conversion,  in gentoo main tree.  However id not go 100% on it. 
Simple units perhaps,  but more complex... not too shure. 
Beats nothing.... but for a production server vs my home server....  70/40 90/10? 95/10? , as a compatiblty layer its a plus, however,  id say for absolute certainty on a production server,  ie vps or provider hosting,  systemd conversion and reboot.. perhaps NOT.  Kernels are oftentimes as minimal as possible to run in KVM./qemu. 

Or for embedded devices,  systemd is possible,  but last time i swiched init... kerblewy...  however  the rpi4/rpi3 Gentoo image supposedly now offers systemd support...as options on conversion. 


However the Infinity perl/shell script will do systemd to systemv/OPENRC int conversion , however a manual procedure at present. 

For those whom dont quite trust systemd.. 

One could thus , pick systemd default,  or OPENRC/older int , etc.  If cockpit team decided to have openrc service scripts  for non systemd users.  
BSD users etc.. wala.. https://github.com/goose121/initify

**Comment by marusak** [comment]
Still feels like this is about documentation (which does not live in this repo). But we document only things we officially support (and test for that reason). I believe that this is gonna be discoverable for people looking for `gentoo` and `cockpit` even when closed.
If I misunderstood this, please reopen.

**Comment by necrose99** [comment]
Yup gearru has a coockpit in his repo. 
For the wiki , first mention is how to add and build. 

I tried the openrc shim , however coockpit is uber hardcoded to .. , and any openrc will fail , and will need a bastion host as mentioned in prior openrc.. issue.. 
Unit hack to openrc was worth a shot..
