### ISSUE TITLE
Docker Images table headers do not line up with columns

### ISSUE THREAD

**Issue by slokhorst** [cockpit-project/cockpit#14278]
Cockpit version: 222.1
OS: Arch Linux
Browser: Chromium 83
Page: Docker Containers

The column headers and columns in the "Images" table do not line up:
![image](https://user-images.githubusercontent.com/8083666/85917957-f2503200-b85e-11ea-8ea9-3f027269fcb0.png)

It seems that there is a superfluous column in the header that isn't in the table itself:
![image](https://user-images.githubusercontent.com/8083666/85917979-1dd31c80-b85f-11ea-818d-b9d88ce2112c.png)

**Comment by martinpitt** [comment]
Fixed in #14302
