### ISSUE TITLE
CentOS 8 - bonding sets to round robin

### ISSUE THREAD

**Issue by biohazd** [cockpit-project/cockpit#14280]
Cockpit version: cockpit-211.3-1.el8.x86_64
OS: CentOS 8.2.2004 (Core)
Page: 

If you edit Network in Cockpit and setup a bond. leaving bond settings as "active backup" in the bond creation actually defaults to round robin.

Steps to reproduce

1. Load Cockpit
2. Create Bond
leaving bond settings as "active backup" in the bond creation actually defaults to round robin
3.

**Comment by mvollmer** [comment]
I believe this is the same bug as in https://bugzilla.redhat.com/show_bug.cgi?id=1817948, and fixed in Cockpit 217.

**Comment by mvollmer** [comment]
In case you are looking for a work around, from Bugzilla: "As a workaround, you can explicitly switch to "Round Robin" (or any other choice) and then back to "Active Backup".  Then the UI logic will correctly create a bond with mode Active Backup."
