### ISSUE TITLE
Switch from "Title Case" to "Sentence case"

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#14285]
Cockpit uses "Title Case" in several strings. It should be using "Sentence case", as per [PF4 guidelines](https://www.patternfly.org/v4/design-guidelines/content/capitalization).

After talking with @martinpitt, we have determined that the best way to approach this is to use our translations.

1. Update translations: `make po/cockpit.pot`
2. Grep for strings: `msggrep --msgid -e '\b[A-Z][a-z]\+\b \+\b[A-Z][a-z]' po/cockpit.pot`
3. Edit (copies of) strings to provide fixes
4. Use a script to change from Title Case to Sentence case.

Suggested timeline for global change: Around the end of August.

Note: This will likely clash with most open PRs.

**Comment by marusak** [comment]
> Suggested timeline for global change: Around the end of August

And we missed it :) @garrett or @martinpitt you still up for it?

> Note: This will likely clash with most open PRs.

I don't think so. We don't change strings that much. It will likely cause conflicts in some bigger PRs, but those conflicts will be easy to fix.

**Comment by garrett** [comment]
>> Suggested timeline for global change: Around the end of August
> And we missed it

No, that meant we start it around the end of August. It's around the end of August now (in the beginning of September). I was saying that we need to wait until the end of August (and either start then or right after). Minor quibble though. :wink:

**Comment by marusak** [comment]
> No, that meant we start it around the end of August. ...

That was just a joke :)

> @garrett or @martinpitt you still up for it?

This was the question I was looking for and answer for. As it seems like a fun little exercise, I can give it a go.  With writing some simple script to do it for us also with verifying we don't break translations, then syncing translations into weblate and possibly keeping the script as check that we still use sentence case as a separate test.

**Comment by garrett** [comment]
Note: Capitalization rules are a little more tricky than simply "Title Case" and "Sentence case": https://www.patternfly.org/v4/design-guidelines/content/capitalization#capitalization-across-products — but this will probably get most of the items.

@marusak: This looks like a good plan!

**Comment by marusak** [comment]
Just sent #14574 for review. Unfortunately we need to go manually through changed strings and find there problems. Then I'll adjust the script to fix those finds.

**Comment by marusak** [comment]
>  Capitalization rules are a little more tricky than simply

"Write menu/navigation items and their corresponding page titles in title case. " - this is gonna be tricky

**Comment by garrett** [comment]
> "Write menu/navigation items and their corresponding page titles in title case. " - this is gonna be tricky

Yeah, I'm not sure if I agree with that one. The most important thing is that we're self-consistent.

**Comment by garrett** [comment]
> Unfortunately we need to go manually through changed strings and find there problems. Then I'll adjust the script to fix those finds.

I went though it, and it _looks good!_ It seems like you've already covered all the one-offs, at least from what I saw when going through the diff. I haven't had the chance to see it in Cockpit yet though; some things might be incorrect in context.
