### ISSUE TITLE
cockpit-ws ECC certificate does not work with openssl -param_enc=explicit

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#14294]
Cockpit version: master
OS: irrelevant

Steps to reproduce
when testing https://github.com/cockpit-project/cockpit/pull/13074
I've used these steps for key generation (found on internet and little bit changed):
```
openssl ecparam -name secp521r1 -genkey -param_enc explicit -out private-key.pem
openssl req -new -x509 -key private-key.pem -out server.pem -days 730 -subj '/C=US/ST=Test/L=Test/O=Test/CN=localhost'
openssl ecparam -in private-key.pem -text -noout
openssl x509 -in server.pem -text -noout
cat private-key.pem server.pem > /etc/cockpit/ws-certs.d/cockpit.cert
restorecon -r /etc/cockpit/ws-certs.d/
```

this leads to error:
```
 remotectl: /etc/cockpit/ws-certs.d/cockpit.cert: Could not parse PEM private key: ASN1 parser: Error in DER parsing.
```

with @martinpitt we've found that this error is caused by `` -param_enc explicit`` parameter. Probably it should work, or be documented how the keys should be generated when used ECC.

**Comment by martinpitt** [comment]
This is a limitation in GnuTLS. I reported it as https://bugzilla.redhat.com/show_bug.cgi?id=1852841 . Do you mind following up there where you found that recipe? Thanks!

**Comment by jscotka** [comment]
@martinpitt  Sure, we'll see what's happen. I hope it will be fixed at least by some better error message, to be less cryptic what's happen there.
