### ISSUE TITLE
When switching from Manual to DHCP the manual adress entry isn't removed 

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/cockpit#14315]
Cockpit version: 215 
OS: ubuntu 18.04 on hyper-v running in windows 10
Page: Networking 

if you have a static ip address entry and you wish to change it back to DHCP, the static ip entry remains.
if you miss it, you end up giving your machine 2 addresses to the same network card. 
while i'm aware this is a valid configuration, i doubt this is what the user had in mind, 

Steps to reproduce:

1. in networking click on ipv4 link 
2. choose manual and enter a manual ip 
3. click apply
4. in networking click on ipv4 link 
5. choose DHCP automatic 

the previous static ip address remains ..
i would expect that static ip would get removed ..
if you still want to enable the user to keep the static ip, you could have a dialog box asking the user to confirm it's removal 
or you could have the a dhcp checkbox next to each entry. 

![image](https://user-images.githubusercontent.com/13434544/86530929-bc95f380-bec5-11ea-8ebf-cc08a76f7253.png)

**Comment by martinpitt** [comment]
@mvollmer: I remember that there was some discussion with NM a few years ago whether this was a bug or a feature. But by now that behaviour has been around for so long that it presumably became the "standard" behaviour? I.e. this is a wontfix?

**Comment by martinpitt** [comment]
What @KKoukiou said above -- this is not obvious one way or the other, and by now it's established behaviour. It should also be obvious enough, and the UI allows you to remove it manually.
