### ISSUE TITLE
logs: Selecting text to copy from the log viewer is difficult

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#14327]
Page: Logs

I haven't seen the corresponding video, but I have seen it in the notes that copying from the logs is difficult. In testing it myself, I found that Cockpit wants to eagerly visit the details page on a mouse up. 

When selecting text on the logs page, a mouseUp activates the link and takes someone to the details page for that log entry.

A possible workaround to make clicking on a line work as intended and still allow for someone to select the text to copy and paste might be something like the following pseudocode:

- mouseDown
   - start a timer
   - measure mouse position 
- mouseUp
   - check position
   - check timer
- if ((distanceOfMouseMovement > somePixels) || clickTimer > someTime)
   - // allow selection and let someone copy the text
   - stayOnPage
- else
   - // this is what we normally do
   - navigate to details page

I'm not sure what distance or time we should use that would feel comfortable for most people and still be accessible for those with tremor or other coordination-related accessibility issues.

_Alternatively_, we could [check for a selection](https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection) on mouseUp. This may have the drawback of having selected text elsewhere preventing the navigation effort. To be certain, we might want to check if the selection as a substring against the log line.

(This second approach is probably better of the two, as we wouldn't have to use arbitrary values based on time or distance.)

**Comment by marusak** [comment]
Still happening but I think we can make this simpler by just having onClick on the text itself and not on the whole panel. I'll take a look

**Comment by marusak** [comment]
Actually lets do this as part of https://github.com/cockpit-project/cockpit/issues/15170
