### ISSUE TITLE
can cockpit ui run gwt pages?

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/cockpit#14326]
i need to create a small page that is able update some properties in a file via web services, perhaps stop/start a service, i'm a java developer so a learning curve for angular/react might too steep for a short time, we have something similar with gwt ,so i was wondering it that's possible

**Comment by garrett** [comment]
Yes, it should be possible.

Details for setting up your own page are on the website @ https://cockpit-project.org/blog/cockpit-starter-kit.html

Noteworthy excerpt at the bottom of the page:

> ### Using different technologies
>
> starter-kit makes opinionated choices like using React, webpack, and Cockpit’s testing framework. These are the technologies that we use for developing Cockpit itself, so if you use them you have the best chance that the Cockpit team can help you with problems. Of course you are free to replace any of these, especially if you have already existing code/tests or a build system.

If you run into any problems, please file another issue here. Thanks!

**Comment by emaayan** [comment]
well i do, when i launch the application form my IDE, it looks ok, however
when it's under cockpit page, the layout is all wrong (my page uses it's
one css) , fields and labels are all over each other.

i develop in windows, how can make my host  page emulate the environment in
cockpit?

**Comment by garrett** [comment]
Do you have a screenshot of what it looks like?

Some guesses:
- Some necessary CSS isn't getting included
- Competing class names from the Cockpit CSS you're importing and your project

**Comment by garrett** [comment]
>i develop in windows, how can make my host  page emulate the environment in
cockpit?

Are you able to run a Linux VM (virtual machine)?

- [Hyper-V](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/) is probably the best bet for Windows. But you'll need Windows 10 Pro for it.
- There's also [VirtualBox](https://www.virtualbox.org/), which is open source at the core and by itself free to use, but you'll definitely want to [avoid installing the "extension pack"](https://www.reddit.com/r/sysadmin/comments/d1ttzp/oracle_is_going_after_companies_using_virtualbox/) if you're using it for anything other than "personal" use.
- It would be possible to run a machine "in the cloud" on AWS or Azure too, but I'm unsure at what cost. (It would vary.)
- If you can get your hands on an old machine to run Linux, it might be a good alternative to a VM as well. (Even a Raspberry Pi could work, but it would be _slow_, especially on the first compile, when it's not cached.)

(Note: WSL2 doesn't support systemd by default, but there are several hacky solutions to get it "working". Cockpit relies on systemd to work, but making WSL2 support systemd won't necessarily get Cockpit working. Therefore, your best bet is still a VM or a remote machine.)

We have some instructions on how to build Cockpit on Linux @ https://cockpit-project.org/external/source/HACKING — I'm not aware of anyone using Windows when developing Cockpit pages. It's definitely possible in VMs, as then you're actually running Linux (in Windows).

If you happen to be using VS Code as your editor, it has great support for "[remote editing](https://code.visualstudio.com/docs/remote/remote-overview)" for editing code on other machines or in VMs. It could help. (Not sure about other editors, except vim and emacs, which also can edit code remotely, or be run remotely on other machines.) If you're using another editor, you might want to see if it has support for remoting as well.

**Comment by emaayan** [comment]
here's a side by side comparison
[image: image.png]

**Comment by garrett** [comment]
@emaayan: Oh, it seems the screenshot didn't show up on GitHub. Can you try reposting it by using the attach dialog (or dragging and dropping on the text entry) on https://github.com/cockpit-project/cockpit/issues/14326 please?

**Comment by emaayan** [comment]
> @emaayan: Oh, it seems the screenshot didn't show up on GitHub. Can you try reposting it by using the attach dialog (or dragging and dropping on the text entry) on #14326 please?

![web_diff](https://user-images.githubusercontent.com/13434544/87408229-d7561f80-c5cb-11ea-9b29-30059766b169.png)

**Comment by garrett** [comment]
Why are all of the elements `<div>`s with pixel placement? :exploding_head: 

From the screenshots, I do see some CSS is loaded, but our CSP (Content Security Policy) settings do not like inline CSS (on purpose, as it's bad practice and also [opens up a page to be attacked via XSS](https://css-tricks.com/css-security-vulnerabilities/)). It's probably that.

- The correct fixes are to:
   1. _not_ position things with pixels (doing so breaks a lot of things, especially most kinds of accessibility)
   2. use elements other than `<div>`s wherever appropriate (A `<div>`, just like a `<span>`, is meaningless. Other HTML tags exist with meaning. This is often called "[semantic HTML](https://developer.mozilla.org/en-US/docs/Glossary/semantics#Semantics_in_HTML)". Having mainly `<div>`s is bad for [accessibility](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML) and breaks general expected usage of how a browser works for _everyone_.)
   3. make sure all CSS is included separately, not inline

- A quick fix to get what you have working within Cockpit:
   - relax the CSP for your page to allow for inline CSS

@martinpitt knows more about adjusting the CSP, and might have a suggestion on how to allow inline CSS for your page.

**Comment by martinpitt** [comment]
You can open up the Content-Security-Policy in your [manifest](https://cockpit-project.org/guide/latest/packages.html#package-manifest). You can look at our [gtk-broadway example](https://github.com/cockpit-project/cockpit/blob/master/examples/gtk-broadway/manifest.json) how to allow e. g. "unsafe-inline" CSS.

**Comment by emaayan** [comment]
> Why are all of the elements `<div>`s with pixel placement? 🤯
> 
> From the screenshots, I do see some CSS is loaded, but our CSP (Content Security Policy) settings do not like inline CSS (on purpose, as it's bad practice and also [opens up a page to be attacked via XSS](https://css-tricks.com/css-security-vulnerabilities/)). It's probably that.
> 
> * The correct fixes are to:
>   
>   1. _not_ position things with pixels (doing so breaks a lot of things, especially most kinds of accessibility)
>   2. use elements other than `<div>`s wherever appropriate (A `<div>`, just like a `<span>`, is meaningless. Other HTML tags exist with meaning. This is often called "[semantic HTML](https://developer.mozilla.org/en-US/docs/Glossary/semantics#Semantics_in_HTML)". Having mainly `<div>`s is bad for [accessibility](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML) and breaks general expected usage of how a browser works for _everyone_.)
>   3. make sure all CSS is included separately, not inline
> * A quick fix to get what you have working within Cockpit:
>   
>   * relax the CSP for your page to allow for inline CSS
> 
> @martinpitt knows more about adjusting the CSP, and might have a suggestion on how to allow inline CSS for your page.

as far as i know, my gwt code doesn't use DIV, maybe GWT converts it to DIV.

one of the things that droves me insane with web development is the placement of fields and form, made me want to tear my head off figuring all the css styles involved, with flows and tables and so on. i didn't know what else ot use. 

can i call in my gwt page rest api to other servers (in the same machine but different ports) or do i have ot use cockpit js api for it?

**Comment by garrett** [comment]
I think GWT is doing a lot of the div sizing behind the scenes. I'm guessing you're probably using pixel values in code and GWT uses those as inline CSS with divs. 

The frustration you're feeling with forms is probably due to fighting GWT and what it tries to do behind the scenes. GWT was built during a different era of web development — back when IE was still a big browser and building things to work cross-platform was a nightmare. GWT was released (2006) before HTML5 (2008). I guess all the divs and pixel sizing are the result of that?

I did a quick search on dev.to, which is like a Reddit clone specifically for developers and saw  https://dev.to/ibaca/modern-gwt-first-steps-509k which seems to have some suggestions on how to use GWT in a more modern way. You'd probably find a lot of it redundant, I'm sure, but some of the links might be useful. And the suggestion of having separate HTML+CSS files versus having GWT manage it all is probably a more modern approach too.

---

For right now, I'd suggest going the route of least effort and adjusting CSP in your manifest. That should get what you currently have working when embedded in Cockpit.

**Comment by emaayan** [comment]
thanks, i did that and now it seems better, i'm thinking about using
intelij that would sync remote files via ssh.
btw there's seems to be gwt patternfly
https://github.com/patternfly-java/patternfly-java

I thought about trying to use react or angular, but the amount of languages
and frameworks for CI, unitest, code style, integration, is instance, to
get a hello world you need to know 5-6 languages. something's wrong here.

gwt allows me to make direct calls to rest api's , the question is do i
need any of cockpit's javascript api to make those calls through them to
another server on the machine?

**Comment by garrett** [comment]
@emaayan: Oh, Elemento looks like it'd help you out with a more modern way to build forms (and other parts of pages) https://github.com/hal/elemento — it's what the patternfly-java repo is based on.

> I thought about trying to use react or angular, but the amount of languages
and frameworks for CI, unitest, code style, integration, is instance, to
get a hello world you need to know 5-6 languages.

Yep. That often seems be the case in web development these days.

> something's wrong here.

Yep. Agreed. :wink: 

You do need to know _at least_ some basic level of HTML, CSS, and JavaScript no matter the project, however. (And how that comes together in the browser in the DOM, which is a mix of the three.) Add 2 - 3 languages, and you're _quickly_ at the 5 - 6 languages.

> gwt allows me to make direct calls to rest api's , the question is do i
need any of cockpit's javascript api to make those calls through them to
another server on the machine?

I think that's answered somewhere in here? https://cockpit-project.org/guide/latest/development.html

For example, for cockpit.http(), it can connect to other addresses: https://cockpit-project.org/guide/latest/cockpit-http.html

And cockpit.dbus() supports different hosts as well: https://cockpit-project.org/guide/latest/cockpit-dbus.html

(Of course, the calls would need proper authorization.)

**Comment by emaayan** [comment]
thanks, btw i'm assuming i can use gwt to upload a debian packet and use
cockpit.spawn to install it?
(would be nice if cockpit had a page to install local packages)

**Comment by garrett** [comment]
@emaayan Cockpit does have a page to install packages, the "Applications" page. However, it's a preselected set of packages and it uses appstream for the information.

However, there is a pattern of installing packages needed for dependencies within Cockpit: `install_dialog` in `cockpit-components-install-dialog.jsx`. But it's React. And I don't know if/how 3rd party pages could call it (especially if they're not React).

For non-React code, PackageKit is available over the DBus API too (and this is probably what you'd want to use):
- https://cockpit-project.org/guide/latest/feature-packagekit
- https://www.freedesktop.org/software/PackageKit/gtk-doc/PackageKit.html

There's also a There's also a `packagekit.js`. (I think this wraps the PackageKit API in Cockpit and makes it easier to use. But I'm not sure how to import it and use it. There's an example of it in being used in `pkg/storaged/client.js`.)

**Comment by emaayan** [comment]
all i'm seeing in the applications is the Storage application, which is
kind of confusing as it's already in the main page.

to provide you with more background, this is meant to be created as an OVA
for customers, so we control the OS, and we create the debian package as
well.
so if appstream is just xml metadata i can include in my debian package,
would that make it easier?

**Comment by martinpitt** [comment]
@emaayan : We have a [packagekit.js library](https://github.com/cockpit-project/cockpit/blob/master/pkg/lib/packagekit.js) for the PackageKit API, and a React component [install_dialog](https://github.com/cockpit-project/cockpit/blob/master/pkg/lib/cockpit-components-install-dialog.jsx) (plus corresponding .css file!) for installing a single package (and its dependencies) on demand. You can just copy these into your project.

It's used e. g. [here](https://github.com/cockpit-project/cockpit/blob/master/pkg/systemd/overview-cards/realmd-operation.js#L650) or [here](https://github.com/cockpit-project/cockpit/blob/master/pkg/systemd/overview-cards/configurationCard.jsx#L324).

**Comment by martinpitt** [comment]
@emaayan : Right, the Applications page shows packages with appropriate [AppStream metadata](https://www.freedesktop.org/wiki/Distributions/AppStream/), in particular `<extends>org.cockpit_project.cockpit</extends>` with a proper `<launchable>`. The Storage page one is a good example.

**Comment by emaayan** [comment]
thanks!, now here's the killer question, can.. it. support EULA screens?
(as in needing to sign them before installing).

**Comment by martinpitt** [comment]
[PackageKit](https://www.freedesktop.org/software/PackageKit/gtk-doc/Transaction.html#Transaction.AcceptEula) has some API for it, but I've never seen/used it. Our cockpit library does not support that, so you need to extend it for that.

**Comment by marusak** [comment]
All questions answered. If you have some additional problems, please open another issue. And good luck :)
