### ISSUE TITLE
Highlight a part of a page (:target based on a fragment)

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#14320]
Cockpit should have the ability to highlight a part of a page, based on a target.

Suggested in (and split out from) #14319

**Comment by garrett** [comment]
The implementation is when a fragment part of a URL matches an ID, the element should have a highlight. (It would probably fade away after a short timer.)

Goal: Make a part of a page more obvious when it's linked from elsewhere in Cockpit.

**Comment by martinpitt** [comment]
In this generality it's prohibitively intrusive -- basically, every single React component would have to add a conditional class and CSS for highlighting. This has just sat around for over two years, and I'm not aware of a concrete use case, so let's close this. We can revisit once we stumble over a reason to have it (such as highlighting table changes, what was done recently)

**Comment by garrett** [comment]
> prohibitively intrusive

Really? It's literally just `#fragment` in HTML and `:target` in CSS. Native web stuff; no need for React at all.

The use case is to link from one page to another, to highlight the section. Granted, we do also need to link between pages (and subpages) even more in Cockpit (like between services and firewall), but we already do some of this now.

**Comment by martinpitt** [comment]
Hmm, don't we need corresponding anchors in the target HTML page for this to work? Maybe my understaanding of HTML is outdated then. But to refer to a specific part of the page, that part *somehow* needs to be marked and addressed, and that's react components.

**Comment by garrett** [comment]
Well, the "anchors" are IDs. As long as something has an ID somewhere on the page, we can refer to it with a hash.

**Comment by martinpitt** [comment]
Right. I'm saying that I don't want us to go around and sprinkle IDs everywhere. It should be done on an as-needed basis, but this issue is too generic IMHO -- there's no definition of "done".
