### ISSUE TITLE
can you disable certain features in cockpit?

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/cockpit#14332]
currently  i'm downloading bionic backports cockpit 215 for ubuntu 18, but i'm not sure i'd want users to be able to join a domain or format the drive, can certain features be disabled by configuration?

**Comment by martinpitt** [comment]
A cockpit session is a regular Linux user session just like GNOME, ssh, or a VT, with exactly the same privileges. There is no cockpit specific authentication/privilege. Thus you can certainly [set up polkit rules](https://cockpit-project.org/guide/latest/privileges.html#privileges-polkit) to only allow some actions for a user. You can also choose to not display some pages by creating [manifest overrides](https://cockpit-project.org/guide/latest/packages.html#package-manifest).

Other customizations are not supported.
