### ISSUE TITLE
administrative access impossible since cockpit 219 (migration from pkexec to sudo)

### ISSUE THREAD

**Issue by jciesla** [cockpit-project/cockpit#14347]
Refactoring administrative access on cockpit 219 included changes in witch sudo is used in replacement of pkexec. To test if user has access to sudo, a function spawn command "sudo -v -n".

In some O.S., calling this command return an exit code 1 with message "sudo: a password is required", even the user is in sudoers. This is caused by the sudo timestamp feature requiring the user to confirm his own password on 5 mins of sudo inactivity.

https://www.sudo.ws/man/1.8.24/sudoers_timestamp.man.html

This regression causes the user cannot longer get administrative access.

Tested on linux custom distribution based on Yocto Dunfell, (sudo v1.8.31).

Issue is present sin 219... tested until 223.

**Comment by martinpitt** [comment]
> In some O.S., calling this command return an exit code 1 with message "sudo: a password is required"

That should be the case in every OS (that we test). Our `can_do_sudo()` only checks for "Sorry, user ... may not run sudo on ..." error, and *only* then decides that the user is not a sudoer. What precisely happens now when you click on "Limited access" and try to raise it?

**Comment by mvollmer** [comment]
> In some O.S., calling this command return an exit code 1 with message "sudo: a password is required", even the user is in sudoers.

This is the case on all supported OSes, actually.  The code does not expect sudo to exit successfully, but rather checks the stderr output of sudo:

```
export function can_do_sudo(host) {
    return cockpit.spawn(["sudo", "-v", "-n"], { err: "out", environ: ["LC_ALL=C"], host: host })
            .then(() => true,
                  (err, out) => !(err.exit_status == 1 && out.match("Sorry, user .+ may not run sudo on .+\\.")));
}
```

Only if the output matches `"Sorry, user .+ may not run sudo on .+\\."` does Cockpit hide the "Turn on administrative access" button.

**Comment by mvollmer** [comment]
(Oh, @martinpitt said the same...)

**Comment by jciesla** [comment]
Hello @martinpitt, I attached a screenshot of the error.
![capture](https://user-images.githubusercontent.com/11711472/87314261-f8960d80-c4f0-11ea-88f8-ba13477ae60b.png)

**Comment by martinpitt** [comment]
@jciesla : Do you have anything in `journalctl -f` while you are trying to gain privileges? What happens if you run `sudo cockpit-bridge --packages` in Cockpit's Terminal?

**Comment by mvollmer** [comment]
In the case of "spawn failed", there are unfortunately no further journal messages. This error happens when the `execve` call in cockpit-bridge for sudo fails.

I suspect that the sudo bridge is misconfigured in `/usr/share/cockpit/shell/manifest.json`.  @jciesla, can you show the content of that file, and also the output of `which sudo`?

**Comment by jciesla** [comment]
Hello @martinpitt , when I execute the command `sudo cockpit-bridge --packages` the output is:

```
admin@localhost:~$ sudo cockpit-bridge --packages
Password:
apps                 Applications                             /usr/share/cockpit/apps
base1                                                         /usr/share/cockpit/base1
dashboard                                                     /usr/share/cockpit/dashboard
dictionary           Dictionary                               /usr/share/cockpit/dictionary
network              Networking                               /usr/share/cockpit/networkmanager
playground           Development                              /usr/share/cockpit/playground
shell                                                         /usr/share/cockpit/shell
ssh                                                           /usr/share/cockpit/ssh
system               Overview, Logs, Services, Terminal       /usr/share/cockpit/systemd
updates              Software Updates                         /usr/share/cockpit/packagekit
users                Accounts                                 /usr/share/cockpit/users
checksum = 8842b000db066ccfb5a0e6181a1ded9bb228edb676760bc6d3b4a5b6d5bd7aaa
admin@localhost:~$
```
And when I follow the journal when I click on the `Turn on administrative access`, I get this message

`Jul 15 00:44:24 localhost sudo[1314]:    admin : a password is required ; TTY=unknown ; PWD=/run/user/1000 ; USER=root ; COMMAND=validate
`

And for @mvollmer , this is the content of the shell package manifest:

```
admin@localhost:/usr/share/cockpit/shell$ cat manifest.json
{
    "version": "223",
    "requires": {
        "cockpit": "134.x"
    },
    "locales": {
        "ca-es": "català",
        "cs-cz": "čeština",
        "de-de": "Deutsch",
        "en-us": "English",
        "es-es": "español",
        "fr-fr": "français",
        "he-il": "עברית",
        "it-it": "italiano",
        "ja-jp": "日本語",
        "ko-kr": "한국어",
        "nl-nl": "Nederlands",
        "pl-pl": "polski",
        "pt-br": "português (Brasil)",
        "ru-ru": "русский",
        "sv-se": "svenska",
        "uk-ua": "Українська",
        "zh-cn": "中文（中国）",
        "zh-tw": "中文（台灣）"
    },
    "bridges": [
        {
            "privileged": true,
            "environ": [
                "SUDO_ASKPASS=/usr/libexec/cockpit-askpass"
            ],
            "spawn": [
                "/home/gitlab-runner/builds/_Lqu8sNM/0/dainsy/dainsy/build/tmp/hosttools/sudo",
                "-A",
                "cockpit-bridge",
                "--privileged"
            ]
        },
        {
            "privileged": true,
            "only-explicitly": true,
            "spawn": [
                "/usr/bin/pkexec",
                "--disable-internal-agent",
                "cockpit-bridge",
                "--privileged"
            ]
        }
    ]
}

```

And for the `chich sudo` I have

```
admin@localhost:/usr/share/cockpit/shell$ which sudo
/usr/bin/sudo
admin@localhost:/usr/share/cockpit/shell$

```

**Comment by jciesla** [comment]
Hello @martinpitt  and @mvollmer , I just realized the origin of the issue with your help, thank you very much. Like @mvollmer said, there is a misconfigured manifest  `/usr/share/cockpit/shell/manifest.json`. Sudo path is configured with my cross-compile environment. I tried to change the manifest manually on the final machine and it is working correctly.

For additional traces, few lines of the configure process:

```
checking for pkexec... /usr/bin/pkexec
checking for sudo... /home/gitlab-runner/builds/_Lqu8sNM/0/dainsy/dainsy/build/tmp/hosttools/sudo
checking for ssh-add... /usr/bin/ssh-add
checking for ssh-agent... /usr/bin/ssh-agent
checking for chcon... /usr/bin/chcon
```
I'm not sure why sudo get my building host path... weird. In the meantime, I will produce a patch to set sudo path in the manifest.json.in file, but it should be a better way to fix. Have a nice day!

**Comment by martinpitt** [comment]
@jciesla : Hah, makes sense, great that it works now! We currently do this:

    AC_PATH_PROG([SUDO], [sudo], [/usr/bin/sudo], [$PATH:/usr/local/sbin:/usr/sbin:/sbin])

I see how that would conflict with adding cross-build paths during package build.

One option would be to entirely drop static PATH detection for sudo, pkexec, chcon, chpasswd, ssh-add, and so on, and rely on a proper runtime $PATH. But I haven't yet thought hard about possible regressions there. @mvollmer, do you happen to remember why we call these with full path at runtime?
