### ISSUE TITLE
Formatting of itm.ifText and itm.thenText in list-group-item selinux-details could be improved

### ISSUE THREAD

**Issue by HunterGerlach** [cockpit-project/cockpit#14357]
Cockpit version: 222.1
OS: Fedora 32 (Server Edition)
Page: selinux/setroubleshoot

In the `list-group-item selinux-details` div (as defined in `cockpit/pkg/selinux/setroubleshoot-view.jsx`), the formatting of the `itm.ifText` and `itm.thenText` is not cohesive for all instances and can be improved.

Example...
For the following error: SELinux is preventing firewalld from using the sys_nice capability.

Itm.IfText = `If you believe that firewalld should have the sys_nice capability by default.`
Itm.ThenText = `You should report this as a bug. You can generate a local policy module to allow this access.`

Preferred conjunction: `If you believe that firewalld should have the sys_nice capability by default, you should report this as a bug. You can generate a local policy module to allow this access.`
_Note the removed period and improved readability._

Steps to reproduce

1. Open the /selinux/setroubleshoot page
2. Identify an error and open it's Solutions tab
3. View the message listed above the "solutions details" button for the relevant text

![Screenshot from 2020-07-14 10-47-54](https://user-images.githubusercontent.com/5001050/87440116-948e4a80-c5bf-11ea-87a7-129c7de88bd1.png)

**Comment by marusak** [comment]
Thank you for the report.
While it seems like improvement, it may backfire if we try to connect strings like this. I don't think it is given that such conjunction would always make sense.

**Comment by HunterGerlach** [comment]
Agreed.
Is this data coming directly from SELinux, unmodified? If so, I would like to take a look at their generic formatting to see how/if they've overcome this issue.

**Comment by marusak** [comment]
> Is this data coming directly from SELinux, unmodified?

Indeed, it comes directly through API.

**Comment by marusak** [comment]
I guess this is then more on the side of selinux, than on the side of cockpit. Closing then.
