### ISSUE TITLE
[Question] How to use public key to login the Web UI instead of password?

### ISSUE THREAD

**Issue by GF-Huang** [cockpit-project/cockpit#14378]
![image](https://user-images.githubusercontent.com/4510984/88008061-f449a000-cb41-11ea-9aa8-f6d3874dda58.png)

**Comment by martinpitt** [comment]
You can't - web browsers simply don't speak SSH. You can use username/password, certificate/smart card, and Kerberos authentication (see https://cockpit-project.org/guide/latest/authentication.html), and once you have a primary Cockpit session you can then use ssh with key auth to connect to *additional* machines.
