### ISSUE TITLE
Get Cockpit building in EPEL6

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1438]
I know we're a long way from running on non-systemd systems, but I'd like to see what it takes to get Cockpit running on EL6 via EPEL6.

**Comment by martinpitt** [comment]
This would be an immense amout of work; not only the build, but also lots of pages assume systemd. So far this has never come up as so desirable that we are ready to basically found a RHEL 6 Cockpit development team, so I'm closing this now. If it comes up again, then not because of this issue.
