### ISSUE TITLE
Network configuration parsing issue

### ISSUE THREAD

**Issue by jciesla** [cockpit-project/cockpit#14386]
Cockpit version: 223
OS: Custom Linux

When creating a bond with two network interfaces and use "Link monitoring" to **ARP**, the bond is correctly created and correctly displayed on the networking general page and the detailed view of bond0 (.../network#/bond0).
The issue appears when you re-edit the bond0. The dialog is displayed, and the "Link monitoring" is always shown as "MII (Recommended)". Maybe a parsing issue.
<!---

**Comment by marusak** [comment]
Indeed, I can reproduce it. The fix is simple and I'll post fix soon. Need to write tests now as well.

**Comment by marusak** [comment]
Sent fix in #14555
