### ISSUE TITLE
NFS mount not showing up

### ISSUE THREAD

**Issue by guizmoau** [cockpit-project/cockpit#14406]
Cockpit version: 188
OS: debian 10
Page: Storage

My server has an NFS mount and it doesn't shows in the Storage sections of cockit.
That NFS folder is mounted in fstab with nfs4 version and default options.

I am not sure what to do in order to see the NFS mount appear in cockpit interface...

Anyone can advise or help ?

**Comment by KKoukiou** [comment]
Hi @guizmoau can you share you /etc/fstab?
If you edit the file and add another entry does it appear or the same happens for all nfs mounts from fstab?

**Comment by guizmoau** [comment]
this way to install cockpit backport on debian buster ?

sudo apt install -t buster-backports cockpit

**Comment by guizmoau** [comment]
no change after installing cockpit backport with the command above and rebooting...still no NFS mount showing 

this is the extract of my fstab for mounting that nfs 

`192.168.1.5:/home/share /home/user/localshare nfs4 defaults
`

**Comment by guizmoau** [comment]
ok I got it
I was using cockpit interface with multiple servers so I updated to backport the main server hosting cockpit interface together with the others servers monitored and it is all brand new design and it does show the NFS mount now

great !
thanks
