### ISSUE TITLE
Store Metrics button

### ISSUE THREAD

**Issue by RoyKas** [cockpit-project/cockpit#14411]
Cockpit version: 188-1
OS: Debian Buster
Page: System

Store Metrics button does not show as intended (see picture below).

![Store Metrics button](https://user-images.githubusercontent.com/26328039/88477844-9bb04380-cf43-11ea-9f1e-20a89601ff7e.png)

**Comment by marusak** [comment]
> Store Metrics button does not show as intended (see picture below).

What do you mean, you expect it to be 'on'?

You also are on a very old version of Cockpit, I suggest updating as there has been a bunch of fixes regarding storing of metrics.

**Comment by RoyKas** [comment]
I've now install the backport of Debian Buster, which is currently version 223-1. Button works!
