### ISSUE TITLE
Mount Management through UI

### ISSUE THREAD

**Issue by greghacke** [cockpit-project/cockpit#14419]
While I see references to managing SAMBA Servers (and a functional enhancement with https://github.com/enira/cockpit-smb-plugin , these discussions are solely on the "server" side of the equation.

Is there any intent to add external mounts into the server environment through Cockpit? As in a managed function for the **mount** command?

**Comment by martinpitt** [comment]
The storage page is about managing local storage, i.e. what is covered by udisks. We don't plan to add a generic UI for fstab management, this is too full of corner cases and not very amenable for interactive UIs. Specific UIs for e.g. NFS or so are possible (and NFS in particular is already supported).
