### ISSUE TITLE
On the Storage page, filter out /dev/loop*

### ISSUE THREAD

**Issue by joeinwap** [cockpit-project/cockpit#14424]
Page:  "Storage"

Add a way to filter out /dev/loop* mounts.  These are not additional storage; they are already counted against /var/lib/snapd/snaps/*.snap and their presence takes up valuable real estate on  the Filesystems section.

Filtering them out would also remove them from the Other Devices section and eliminate the bogus warnings; "Inconsistent filesystem mount"
"The filesystem is currently mounted on /snap/canonical-livepatch/95 but will not be mounted after the next boot."

**Comment by KKoukiou** [comment]
There is an upstream report for that on snapcraft, https://bugs.launchpad.net/ubuntu/+source/snapcraft/+bug/1714941

We could filter them in cockpit of course, but I would rather keep this logic outside of cockpit.

I
