### ISSUE TITLE
cloud we give correct reponse messages  to the command ?

### ISSUE THREAD

**Issue by tscswcn** [cockpit-project/cockpit#14425]
Page: 
cloud we give correct reponse messages  to the command ?
such as 
[root@node-host pcp]# /usr/libexec/cockpit-ssh 10.10.204.168
74

{"command":"authorize","challenge":"*","cookie":"session293751596006669"}
cockpit-ssh-Message: 09:11:12.900: couldn't read control message: Bad message
83

{"command":"authorize","challenge":"x-host-key","cookie":"session293751596006672"}
cockpit-ssh-Message: 09:11:26.830: couldn't read control message: Bad message
cockpit-ssh-Message: 09:11:26.830: cockpit-ssh 10.10.204.168: refusing to connect to unknown host: 10.10.204.168:22
92

{"command":"init","problem":"unknown-host","error":"unknown-host","auth-method-results":{}}[root@node-10-41-91-100 pcp]#
[root@hostname  pcp]#

**Comment by marusak** [comment]
Could you please be more specific what output you would expect? Also what is your usecase to run `cockpit-ssh` manually?

You can read more about protocol [here](https://github.com/cockpit-project/cockpit/blob/master/doc/protocol.md) and about authentication [here](https://github.com/cockpit-project/cockpit/blob/master/doc/authentication.md).

**Comment by tscswcn** [comment]
For from webpage to add host, it is annoying， if possibe， we can use command， or for batch，

**Comment by marusak** [comment]
> For from webpage to add host, it is annoying， if possibe， we can use command， or for batch，

You mean to add remote hosts you would use `cockpit-ssh` instead of clicking 'Add new host' in the UI and then filling up the dialog? If so, then you should use `/etc/cockpit/machines.d/99-webui.json` to do this. See https://cockpit-project.org/guide/latest/feature-machines.html for documentation

**Comment by tscswcn** [comment]
thx  a lot!
