### ISSUE TITLE
Redirecting to Login Page After Successful Login

### ISSUE THREAD

**Issue by Saroufim** [cockpit-project/cockpit#14435]
Cockpit version: 188-1
OS: Debian on RPi3

Cockpit has worked flawlessly for a very long time on my RPi server. For some reason it began redirecting me to the login page in an endless loop recently. I simply log in and then I'm redirected to the login page.  The only relevant error from web inspector is "401 unathorized". I have not done anything related to user configs recently and I can't figure out what triggered this error. 

Possibly relevant information:
- 2fa is enabled for SSH
- Apache is used as the web server but the error also persists while using the ip address + port 9090
- I noticed this started occuring possibly after I tried installing Heimdall through docker which tried to use the same ports as cockpit. Heimdall's container did not start due to the ports having already been in use by cockpit. Perhaps this is relevant?

Thanks in advance.

**Comment by Saroufim** [comment]
Update: I completely uninstalled and purged cockpit then reinstalled it and the problem persists.

**Comment by marusak** [comment]
Sorry for this slipping through.

> I noticed this started occuring possibly after I tried installing Heimdall through docker which tried to use the same ports as cockpit. Heimdall's container did not start due to the ports having already been in use by cockpit. Perhaps this is relevant?

Could you try reverting that and checking if the issue persists?

Also is there anything in journal?

**Comment by Saroufim** [comment]
Hello. I migrated that system to Fedora IoT and the problem hasn't occurred yet, thus I'm unable to reproduce it.

**Comment by marusak** [comment]
Thank you for the reply, closing then.
