### ISSUE TITLE
Container  blocked, and after exit there is no disconnect text in terminal

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#1443]
Adter many of starting & exitiing container instance. I felt to state, that after exit command in terminal. There isn't disconnected text and it is unable to start container again.
It seems that there is broken something in docker?

![konqueror1-container](https://cloud.githubusercontent.com/assets/8735467/4919128/94856764-64f7-11e4-84db-69b09719f260.png)
![konqueror2-container-error](https://cloud.githubusercontent.com/assets/8735467/4919129/948a7718-64f7-11e4-8d8b-597607b17a02.png)

**Comment by stefwalter** [comment]
Exiting the process in the container stops the container. That's expected. What's not expected is the exception. @jscotka Does the exception still happen with the new Docker terminal code (in recent releases or git master)?

**Comment by dperpeet** [comment]
@jscotka does this still happen?

**Comment by jscotka** [comment]
I've tested it some time ago and I din't met it again, so we can close it
