### ISSUE TITLE
2FA or MFA (Multi Factor Authentication)

### ISSUE THREAD

**Issue by Ainz** [cockpit-project/cockpit#14456]
I am using Cockpit on a new Fedora Server 32, installed on a Proliant server in a SOHO.

Have been running this question up and down a couple of places. I am not sure who should provide the solution. 

Fedora - which is the OS -?
Docker - which is running on my Fedora - ?
Cockpit - which is the interface I use to log in to Fedora - ?

Looking for an implementation of TOTP 2FA based on device authenticators, much like Googles or Microsofts, yeah, probably like those. I stumbled over an article describing this with SSH: https://www.tecmint.com/two-factor-authentication-for-ssh-on-fedora/ but since I am not using the Fedora UI to logon, I guess it should be a function of Cockpit.

I don't use SSH, I recently signed up with [DUO ](https://duo.com/)to enable this for my Windows Server, which should work fine once implemented.  I find that secure enough for my needs and wish someone would consider implementing it here.

**Comment by Ainz** [comment]
This is a proposed solution I was suggested, that do not work. It looked fine, the input was there, but it did not accept generated codes.  https://vincentverhagen.nl/2017/11/fedora-cockpit-two-factor-authentication-2fa/

**Comment by martinpitt** [comment]
That blog post is actually good. Cockpit uses PAM, so anything that works on the VT  or SSH also works for Cockpit's login screen. I have a similar recipe for Fedora:
```
sudo dnf install -y google-authenticator
# generate key, just keep defaults
google-authenticator
sudo vi /etc/pam.d/system-auth
# change pam_unix "auth sufficient" to "required"
sudo vi /etc/pam.d/sudo
# add: auth required pam_google_authenticator.so user=root
```

If you use identity management with FreeIPA, you can also [centrally enable 2FA there](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/linux_domain_identity_authentication_and_policy_guide/otp). We officially support that solution and test it in CI.

**Comment by Ainz** [comment]
I also learned that RedHat - and thus Fedora - is having some issues related to underlying systems ( https://bugzilla.redhat.com/show_bug.cgi?id=1767606 ) but FreeIPA seems a good tip. I'll check it.

If this is officially supported by Cockpit, why is there no mention of it on your site? https://cockpit-project.org/guide/latest/authentication
