### ISSUE TITLE
Multiple login failures to cockpit GUIcockpit-tls: gnutls_handshake failed

### ISSUE THREAD

**Issue by ServerGeek82** [cockpit-project/cockpit#14466]
Currently running into multiple errors when logging into the interface with above error in logs. Successful login is intermittent, and able to duplicate same errors on my laptop as well. Also using the cockpit-machines plugin as I like the ability to mange my VMs.
Hardware: HP Proliant G8
Ubuntu 20.04.1 LTS

`<user>@<hostname>:/etc/cockpit$ sudo apt show cockpit
Package: cockpit
Version: 215-1
Priority: optional
Section: universe/admin
`
`<user>@<hostname>:/etc/cockpit$ sudo systemctl status cockpit
● cockpit.service - Cockpit Web Service
     Loaded: loaded (/lib/systemd/system/cockpit.service; static; vendor preset: enabled)
     Active: active (running) since Mon 2020-08-10 07:27:13 MST; 1min 17s ago
TriggeredBy: ● cockpit.socket
       Docs: man:cockpit-ws(8)
    Process: 126251 ExecStartPre=/usr/sbin/remotectl certificate --ensure --user=<user>--group=cockpit-ws --selinux-type= (code=exited, status=0/SUCCESS)
   Main PID: 126252 (cockpit-tls)
      Tasks: 7 (limit: 309383)
     Memory: 3.0M
     CGroup: /system.slice/cockpit.service
             └─126252 /usr/lib/cockpit/cockpit-tls

Aug 10 07:27:13 <hostname> cockpit-tls[126252]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Aug 10 07:27:13 <hostname> cockpit-tls[126252]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Aug 10 07:27:44 <hostname> cockpit-tls[126252]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Aug 10 07:28:26 <hostname> cockpit-tls[126252]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Aug 10 07:28:26 <hostname> cockpit-tls[126252]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
`
`<user>@<hostname>:/etc/cockpit$ remotectl certificate
certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
<user>@<hostname>:/etc/cockpit$
`

**Comment by creepinson** [comment]
Same issue, I have checked systemd and it says a tls fatal alert has been received in Ubuntu 20.*

**Comment by lijingchun0** [comment]
I have the same issue in centos 8

**Comment by martinpitt** [comment]
These messages are more or less expected, it happens when you open the cockpit login page and the browser complains about the self-signed certificate. That aborts the initial connection.
