### ISSUE TITLE
Unnecessary notification - Warning alert:Inconsistent filesystem mount

### ISSUE THREAD

**Issue by RoyKas** [cockpit-project/cockpit#14467]
Cockpit version: 225
OS: Debian 10 (Buster)
Page: Storage

I'm running a headless server with encrypted partitions. The root file system is not encrypted.
I don't like to have the passwords for the encrypted file systems stored on the server itself, so after a reboot, I manually unlock the encrypted file systems and mount them (both via Cockpit).
In order to prevent the server from booting into emergency mode, I have to give the custom mount option 'noauto' (I have to type this every time I mount the file system, which is annoying as well).
This approach results in the "Warning alert:Inconsistent filesystem mount".

I think this is a valid use case of the system, and therefore the warning should be considered unnecessary.

If I am incorrectly using the system and there is another way to organize the encrypted partitions without storing the password on the server itself, I would be glad to rearrange my system accordingly.

**Comment by mvollmer** [comment]
> so after a reboot, I manually unlock the encrypted file systems and mount them (both via Cockpit).

How do you do this exactly? Via SSH and running mount on the commandline, or via Cockpit?

But this is indeed a scenario that is not addressed well by Cockpit... Let me try to come up with something...

**Comment by mvollmer** [comment]
> But this is indeed a scenario that is not addressed well by Cockpit... Let me try to come up with something...

Ok, what about this:

We have a long-running enhancement PR that will unify encryption and filesystem management in the UI: https://github.com/cockpit-project/cockpit/pull/13192. I'll make sure that as part of that, Cockpit properly supports your use case.

For the short term, we make a special case for filesystems that are in a "noauto" luks container. For such a filesystem, "Mount" will default to "noauto" as well (if there isn't any fstab entry yet), and we wont show the "Inconsistent filesystem" warning.

I think that should cover your case. You wont see the warning, and the Mount dialog will not overwrite your "noauto" option.
Let me know if I have overlooked something.

(Indeed we might add another warning if people forget the "noauto" for the filesystem: This filesystem will be automatically mounted on the next boot, but its encryption container will not be unlocked at that time. But #13192 is already supposed to take care of that but making it impossible, so maybe we wont bother with the warning, hmm.)

**Comment by RoyKas** [comment]
> For such a filesystem, "Mount" will default to "noauto" as well (if there isn't any fstab entry yet)

Please note, that the fstab entry is there after the first time I mount, including the noauto option, but Cockpit does not take this option automatically into the 'custom options' and I now have to type this every time.

Thanks for quickly addressing this issue  :-)

**Comment by mvollmer** [comment]
This was released with Cockpit 226.

**Comment by RoyKas** [comment]
Thanks, how quick will this be included in Debian (testing) ?

**Comment by mvollmer** [comment]
> Thanks, how quick will this be included in Debian (testing) ?

@martinpitt can answer this best.

**Comment by martinpitt** [comment]
I just uploaded cockpit 226 to Debian unstable, so it should hit testing by Friday.
