### ISSUE TITLE
Can no longer see or manage virtual machine from cockpit

### ISSUE THREAD

**Issue by g3blv** [cockpit-project/cockpit#14476]
Cockpit version: 215
OS: Ubuntu Server 20.04.1 
Page: Machines

I did an update for the server through Cockpit and now I can't manage virtual machines from Cockpit.

First there was an error message about user not having access to the `kvm` group so I added the user the `kvm` group.

Now I see the following message in the log

`'/sys/kernel/security/apparmor/profiles': Permission denied`

I can still manage the virtual machines through Virtual Machine Manger over SSH.

Seems like a lot of permission where changed with the update.

![image](https://user-images.githubusercontent.com/45568043/90155788-035fee80-dd8c-11ea-9d15-8da8bd628540.png)

**Comment by marusak** [comment]
Can you please provide version on `libvirt0`?
This seems too similar to https://github.com/cockpit-project/bots/pull/1137
Can you please read through this PR and see if the problem is the same? (there is also workaround).

**Comment by g3blv** [comment]
Thx. Suggested solution solved the issue.

**Comment by marusak** [comment]
Would you mind commenting on https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1891311 to get some attention there? :)

**Comment by g3blv** [comment]
Sure. Done.

**Comment by polhaghverdian** [comment]
@g3blv @marusak what was the temporary solution? I have the same issue.

![bild](https://user-images.githubusercontent.com/50968806/91646077-a6cb2780-ea4b-11ea-9093-bedd9a68675e.png)

**Comment by marusak** [comment]
It has been reported as https://bugs.launchpad.net/ubuntu/+source/libvirt-dbus/+bug/1892757 and better workaround until ubuntu fixes its packaging is to do `usermod -a -G libvirt libvirtdbus`

**Comment by polhaghverdian** [comment]
@marusak It did not work. `usermod -a -G libvirt libvirtdbus` i also reboot the computer. 

![bild](https://user-images.githubusercontent.com/50968806/91656123-6e146800-eab6-11ea-95e4-9d94ea13209e.png)

**Comment by marusak** [comment]
What does `groups libvirtdbus` say?

**Comment by polhaghverdian** [comment]
@marusak result of `groups libvirtdbus`

**libvirtdbus : libvirtdbus libvirt**

**Comment by maxabaumgarten** [comment]
Tried same fix as @polhaghverdian and still having same issue:

`root@server:# ls -l /var/run/libvirt/libvirt-sock
srw-rw---- 1 root libvirt 0 Sep  2 12:46 /var/run/libvirt/libvirt-sock
root@server:# usermod -a -G libvirt libvirtdbus
root@server:# groups libvirtdbus
libvirtdbus : libvirtdbus libvirt

**Comment by polhaghverdian** [comment]
@maxabaumgarten Did it work for you now?

**Comment by maxabaumgarten** [comment]
@polhaghverdian it worked for me.  I did a full reboot and i can now fully manage by KVM running on Ubuntu 20.04 using Cockpit.

**Comment by polhaghverdian** [comment]
@maxabaumgarten I dont think it was the same issue. I have always been able to manage my vms in Cockpit. The problem is the error messages i get in the logs which i would like to be solved.

**Comment by polhaghverdian** [comment]
@marusak I still get these error messages. I can manage my vms so it not really a problem. But i would like to have those errors fixed.
