### ISSUE TITLE
Allow weak passwords on user creation

### ISSUE THREAD

**Issue by snoopy72** [cockpit-project/cockpit#14478]
**Problem**

cockpit is blocking the usage of weak passwords. The system (Debian 10) is allowing this usage (checked with running "adduser" and the same weak password). Please add an option to disable your password verification

cockpit version 188
linux version: Debian GNU/Linux 10 (buster)

**Reproduce**

1. in the cockpit UI open "...:9090/users" and click "Add Account" (or whatever the original text is)
2. enter the username and a weak password (f.eg. "ma99" - of course twice)
3. click "create"

**Result**

You'll get the response "Password quality check failed: The password is shorter than 8 characters". 
Wrong: I never decided to have a minimal length for passwords.
For a locally driven (not connected) server it is rediculous to have long and complex passwords.

**System behaviour**

Using the bash on the system directly, there is no problem to create the user with the same password:

1. type "adduser testname"
2. type the weak password twice
3. confirm all other questions simply by pressing the "return" key
4. voila ! the user has been created without problems.

**Expected result**

The user should not be blocked when specifying a weak password. Please remove the password verification altogether ... or add an option in your software to avoid this behaviour.

**Please note**

.. the 1st ticket at https://github.com/osbuild/cockpit-composer/issues/1079 with same description but some comments.

(also requested in ticket https://github.com/osbuild/cockpit-composer/issues/985 in cockpit-composer by jgiardino but closed without a real solution)

**Comment by snoopy72** [comment]
Same problem in version 225.

**Comment by marusak** [comment]
Cockpit uses `pwscore` to check for password quality. 
```
$ /usr/bin/pwscore 
ma99
Password quality check failed:
 The password is shorter than 8 characters
```

This is configurable in `/etc/security/pwquality.conf`. (In this case `minlen=4` I guess?)

This however still leaves the question opened as if we should or should not enforce strong passwords if `useradd` does not enforce it either (I thought it does do that). Maybe a good approach would be to do something like anaconda does, that you need to click twice on `OK` if the password is weak to make sure you are aware you are using weak one.

**Comment by mvollmer** [comment]
> Maybe a good approach would be to do something like anaconda does, that you need to click twice on `OK` if the password is weak to make sure you are aware you are using weak one.

I like this one best. Cockpit should push people toward best practices but since root can get around any additional policy that Cockpit might implement, there is no point of Cockpit actually enforcing it. That's just an annoyance.

**Comment by marusak** [comment]
Implemented in https://github.com/cockpit-project/cockpit/pull/14557
