### ISSUE TITLE
NFS mount discovery - why doesn't cockpit see nfs mounts that have been set up my system?

### ISSUE THREAD

**Issue by apennisi23** [cockpit-project/cockpit#14472]
Page: 

Storage display doesn't show NFS mounts that exist on my system if they are not added through cockpit.
Is there something missing from my setup?

**Comment by marusak** [comment]
Can you please provide more info? Like output of `mount -l` and screenshot of what is actually displayed in cockpit. Or any other information about these mounts that are not displayed.
Also can you please share OS and cockpit version you are using?

**Comment by JKuhns5739** [comment]
On our system we have an NFS mount which is seen with the showmount command.

[root@r640-f23-43 ~]# showmount -e
Export list for r640-f23-43:
/var/snapshot/venus-02.00.17-RHEL-08.01.01.02/rearMateBackup 172.27.218.220

This mount is not shown in the Storage panel unless manually added.
![Cockpit-Storage-NFS](https://user-images.githubusercontent.com/69595121/90039969-5dca5380-dc95-11ea-9809-41a41736e60b.PNG)

The mount -l output:

[root@r640-f23-43 ~]# mount -l
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime,seclabel)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,seclabel,size=131635424k,nr_inodes=32908856,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,seclabel)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,seclabel,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime,seclabel)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,pids)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,cpuset)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,cpu,cpuacct)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,perf_event)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,net_cls,net_prio)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,freezer)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,hugetlb)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,rdma)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,memory)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,blkio)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/mapper/vg00-root on / type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=44,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=1294)
mqueue on /dev/mqueue type mqueue (rw,relatime,seclabel)
debugfs on /sys/kernel/debug type debugfs (rw,relatime,seclabel)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,seclabel,pagesize=2M)
/dev/sda2 on /boot type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/vg00-opt on /opt type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/vg00-home on /home type xfs (rw,nodev,relatime,seclabel,attr2,inode64,noquota)
/dev/sda1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=winnt,errors=remount-ro)
/dev/mapper/vg00-var on /var type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/vg00-tmp on /tmp type xfs (rw,nosuid,nodev,noexec,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/vg00-var_log on /var/log type xfs (rw,nosuid,nodev,noexec,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/vg00-var_tmp on /var/tmp type xfs (rw,nosuid,nodev,noexec,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/vg00-var_log_audit on /var/log/audit type xfs (rw,nosuid,nodev,noexec,relatime,seclabel,attr2,inode64,noquota)
sunrpc on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
/dev/mapper/vg00-backups on /backups type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/vg00-upgrades on /upgrades type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/vg00-var_lib_libvirt_images on /var/lib/libvirt/images type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
nfsd on /proc/fs/nfsd type nfsd (rw,relatime)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,relatime,seclabel)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=26337264k,mode=700)

**Comment by marusak** [comment]
And which one do you expect to see in cockpit?
This one?
`nfsd on /proc/fs/nfsd type nfsd (rw,relatime)`

It is of type `nfsd` and not `nfs` and (if my [understanding](https://linux.die.net/man/7/nfsd) is correct) this is not a real mount.

**Comment by JKuhns5739** [comment]
I was expecting to see the nfsd mount. I did not understand that nfsd mounts are not considered "real" nfs mounts.

Thanks for the reply.
