### ISSUE TITLE
Unable to find name and tag when installing on Fedora IoT

### ISSUE THREAD

**Issue by jtligon** [cockpit-project/cockpit#14481]
Cockpit version: `cockpit-system-225-1.fc32.noarch`
OS: Fedora IoT `Version: 32.20200811.0 (2020-08-11T15:29:17Z)` 
Page: Installation

Step 1 and 2 of install instructions for Fedora CoreOS worked fine

```
ostree://fedora-iot:fedora/stable/x86_64/iot
                   Version: 32.20200811.0 (2020-08-11T15:29:17Z)
                BaseCommit: cc735b093f41c7c414b27a35f5fd818da7307404e25bc10c8a61719d2261a5a6
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
           LayeredPackages: cockpit-kdump cockpit-networkmanager cockpit-ostree cockpit-podman cockpit-system git toolbox
```

Steps to reproduce

1. Install Fedora IoT
2. Install cockpit using Fedora CoreOS instructions
3. `sudo podman container runlabel --name cockpit-ws RUN cockpit/ws` fails with `Error: unable to find a name and tag match for cockpit/ws in repotags: no such image`

**Comment by marusak** [comment]
You mean it is documented like this in https://cockpit-project.org/running.html#coreos?

The behaviour seems a bit odd from podman side:
```
$ sudo podman images
REPOSITORY               TAG     IMAGE ID      CREATED       SIZE
docker.io/library/mongo  latest  dee5b549543c  3 weeks ago   392 MB
k8s.gcr.io/pause         3.2     80d28bedfe5d  6 months ago  688 kB

$  sudo podman container runlabel --name cockpit-ws RUN cockpit/ws
Error: unable to find a name and tag match for cockpit/ws in repotags: no such image

$ sudo podman container runlabel --name cockpit-ws RUN docker.io/cockpit/ws
Error: unable to find 'docker.io/cockpit/ws' in local storage: no such image

$ sudo podman pull docker.io/cockpit/ws
Trying to pull docker.io/cockpit/ws...
Getting image source signatures
Copying blob a0826bee8350 done  
Copying blob 8b949f6ba22b done  
Copying blob 7b9b10cec7bd done  
Copying blob 854946d575a4 done  
Copying config b16fdeb89a done  
Writing manifest to image destination
Storing signatures
b16fdeb89aa23997b75015cfab23ce5b9e45ab9762e9bfa79ee41e5fa6e5bb86

$ sudo podman container runlabel --name cockpit-ws RUN docker.io/cockpit/ws
af2249ccd6aad7942cc65e919efb13ac347e9b324229ae5222fdab767c3beb3e
```

So podman does not try to pull this image which is a bit unexpected. So I guess we need to document this better.

**Comment by marusak** [comment]
Sent https://github.com/cockpit-project/cockpit-project.github.io/pull/339

@jtligon can you please verify that it fixes your problem? Thanks!

**Comment by jtligon** [comment]
pull then RUN works like a charm, tyvm!

**Comment by jtligon** [comment]
whoops, spoke too soon. no ports exposed so I can't connect to the container. it is up and running correctly, but a -p 9090 should be added somewhere.
