### ISSUE TITLE
Clicking on modal backdrops dismiss some modals

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#14488]
1. Open a modal in the Machines or Cockpit-Podman pages. 
2. Click outside of the modal, in the greyed-out area. 
3. The modal disappears. 

This may affect other pages too, but I've only seen this happen (so far) in Machines and Cockpit-Podman.

This isn't indented behavior. It should capture clicks, not dismiss the dialog. The whole point of the screened backdrop is to prevent interaction (especially with the content below it). This does not seem to be a PF3 vs. PF4 issue either, and this is not what the example PF4 dialogs do, nor what our dialogs (PF3 and PF4) do on other pages.

It's especially bad as closing the dialog will cause all information in the dialog to be lost. Bringing up the dialog again will reset it to defaults.

_Anyone_ can easily fire a misclick, but this _especially_ affects people with mobility issues.

(My guess? I think there's probably an event bound somewhere in the tree and an even bubbles up to it to dismiss the dialog. But I could be wrong.)

**Comment by KKoukiou** [comment]
Patternfly 3 modals behaved like that apparently, https://www.patternfly.org/v3/pattern-library/forms-and-controls/modal-overlay/index.html#code

We still use Patternfly 3 Modals in all pages which are written with react.

I suggest this to be fixed with the porting of PF3 modals o PF4.

**Comment by garrett** [comment]
Yep, we need to port to PF4 anyway. This is a very good reason why (in addition to having more modern and maintainable code).

**Comment by skobyda** [comment]
We no longer use any PF3 Modals, so closing this issue.
