### ISSUE TITLE
How to re-add host after a rebuild?

### ISSUE THREAD

**Issue by FlexibleToast** [cockpit-project/cockpit#14482]
I connected a few different hosts through the dashboard of a CentOS Cockpit. I had to rebuild one of the servers and it won't let me re-add it because the key doesn't match. I tried searching and I found that an older version of Cockpit used `/var/lib/cockpit/known_hosts` and newer versions use `~/.ssh/known_hosts`. However, I can't find a known_hosts file anywhere on the server. Even running `find / -name "known_hosts"` doesn't return any results.

**Comment by marusak** [comment]
Maybe in `/etc/ssh/ssh_known_hosts`?

**Comment by marusak** [comment]
@FlexibleToast have `/etc/ssh/ssh_known_hosts` worked?

**Comment by FlexibleToast** [comment]
Yes, that appears to be where they are. Documentation should probably reflect that.
