### ISSUE TITLE
udisks2/modules does not exist  - move to UDisks2.Manager.EnableModule()

### ISSUE THREAD

**Issue by RoyKas** [cockpit-project/cockpit#14497]
Cockpit version: 225
OS: Debian 10 (Buster)
Page: Storage

When selecting the Storage page, I get the following error in the syslog:
Error loading modules: Error opening directory “/usr/lib/x86_64-linux-gnu/udisks2/modules”: No such file or directory
The page seems however working.

It seems that Cockpit is expecting udisks2/modules to exist, but it doesn't until any udisks module is installed. On my system there are no udisks modules installed.

I have one BTRFS file system mounted. Does Cockpit expect/need udisks2-btrfs module?

For description of my situation see also issue [#14467](14467).

**Comment by mvollmer** [comment]
> It seems that Cockpit is expecting udisks2/modules to exist, but it doesn't until any udisks module is installed. On my system there are no udisks modules installed.

This would be a issue with UDisks2, I'd say. https://github.com/storaged-project/udisks

**Comment by mvollmer** [comment]
> I have one BTRFS file system mounted. Does Cockpit expect/need udisks2-btrfs module?

No, Cockpit doesn't have any explicit support for btrfs yet.  But once it does, I would expect it to need udisks2-btrfs.

**Comment by RoyKas** [comment]
> > It seems that Cockpit is expecting udisks2/modules to exist, but it doesn't until any udisks module is installed. On my system there are no udisks modules installed.
> 
> This would be a issue with UDisks2, I'd say. https://github.com/storaged-project/udisks

Thanks, I will try to reproduce this issue using udiskctl and submit at their project.

**Comment by tbzatek** [comment]
gah, this was three years old issue :-/

**Comment by abrahamdsl** [comment]
three years, three months, 15 days running :'(

**Comment by martinpitt** [comment]
Reopening with retitling. This is harmless, and `EnableModules()` is nice as there is no way to enumerate available modules, so enabling them one by one is a bit tedious. But we can look into doing that.

**Comment by jelly** [comment]
> Reopening with retitling. This is harmless, and `EnableModules()` is nice as there is no way to enumerate available modules, so enabling them one by one is a bit tedious. But we can look into doing that.

On the other hand? How many modules do we need to enable. lvm2, iscsi, btrfs? It would make our code more explicit and explicit in what we support.

**Comment by tbzatek** [comment]
> On the other hand? How many modules do we need to enable. lvm2, iscsi? It would make our code more explicit and explicit in what we support.

Exactly that was the intention. Clients should only request modules they actually need as they need to make use of the additional API/interfaces.

Besides, if you get something like ENOFILE error, you may try to install the missing module (e.g. via PackageKit) and just try again.

**Comment by jelly** [comment]
```
[jelle@t14s][~/projects/cockpit/main]%git grep EnableModule
pkg/storaged/client.js:            await client.manager.EnableModule("btrfs", true);
pkg/storaged/client.js:            await client.manager.EnableModule("iscsi", true);
pkg/storaged/client.js:            await client.manager.EnableModule("lvm2", true);
```

Cockpit uses `EnableModule` now as `EnableModules` was deprecated by udisks, so I think that's the final nail the coffin for this issue?

**Comment by jelly** [comment]
If you don't have udisks2-btrfs, udisks2-lvm installed you will get these "errors" and will miss out from the btrfs improvements we made.

These aren't really errors but more optional dependencies, so if you want to take advantage of lvm, btrfs and iscsi support install the equivalent udisks dependency.

**Comment by gen-angry** [comment]
That did it, thank you! Even fixed the weird mirrored volume display.

For others that stumble upon it, install `udisks2-lvm2` and `udisks2-btrfs` from apt.

**Comment by jelly** [comment]
Note that this isn't an error, it's a warning. Not enabling iscsi support does not affect the storage page it only means you won't have iscsi support.

**Comment by jawz101** [comment]
So... if this isn't an error, can it go away?  I guess I don't like logs that make me troubleshoot non-existent problems. 100,000 people are going to find this exact closed issue is what I'm saying.

"Error initializing module ..." means something is wrong

**Comment by tbzatek** [comment]
> "Error initializing module ..." means something is wrong

Hmmm, right, looking at it now I think this is rather clumsy as the `org.freedesktop.UDisks2.Manager.EnableModule()` method call is supposed to be called even with a gracefully handled error path. So I guess we should silence printing the ENOENT errors while keeping others. No change for the D-Bus method call of course.

**Comment by jawz101** [comment]
> > "Error initializing module ..." means something is wrong
> 
> Hmmm, right, looking at it now I think this is rather clumsy as the `org.freedesktop.UDisks2.Manager.EnableModule()` method call is supposed to be called even with a gracefully handled error path. So I guess we should silence printing the ENOENT errors while keeping others. No change for the D-Bus method call of course.

Thanks.  I do the same thing (a lot) where I reconsider a proposal
