### ISSUE TITLE
AllowUnencrypted not working

### ISSUE THREAD

**Issue by neilthomson** [cockpit-project/cockpit#14496]
Cockpit version: 215
OS: Ubuntu 20.04

On a fresh ubuntu install cockpit is unreachable in chrome because the certificate comes up as invalid and chrome seems to have changed and you can no longer "proceed anyway" (I could in Safari so at least that way I could have a play but this isn't a long term solution). I can see there's a few issues on certificates (which I know next to nothing about) and updating the docs, but I don't have any proxy's, I'm just on the LAN, so is it not possible to get a certificate that works in this scenario?

From the logs:
```
Aug 21 20:35:52 testingnuc systemd[1]: Starting Cockpit Web Service...
Aug 21 20:35:52 testingnuc remotectl[1251141]: Generating temporary certificate using: sscg --quiet --lifetime 3650 --key-strength 2048 --cert-key-file /etc/cockpit/ws-certs.d/0-self-signed.cert --cert-file /etc/cockpit/ws-certs.d/0-self-signed.cert --ca-file /etc/cockpit/ws-certs.d/0-self-signed-ca.pem --hostname testingnuc --organization 3b2e5e370e9d4ecd8bb11ab4cdc6e7d1 --subject-alt-name localhost --subject-alt-name IP:127.0.0.1/255.255.255.255
Aug 21 20:35:52 testingnuc remotectl[1251141]: Error generating temporary dummy cert using sscg, falling back to openssl
Aug 21 20:35:52 testingnuc remotectl[1251141]: Generating temporary certificate using: openssl req -x509 -days 36500 -newkey rsa:2048 -keyout /etc/cockpit/ws-certs.d/0-self-signed.Y11RP0.tmp -keyform PEM -nodes -out /etc/cockpit/ws-certs.d/0-self-signed.141RP0.tmp -outform PEM -subj /O=3b2e5e370e9d4ecd8bb11ab4cdc6e7d1/CN=testingnuc -config /tmp/ssl.conf.161RP0 -extensions v3_req
Aug 21 20:35:52 testingnuc systemd[1]: Started Cockpit Web Service.
Aug 21 20:35:52 testingnuc cockpit-tls[1251145]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
```

But to get to the title of this bug report, I tired to get around https access with AllowUnencrypted = true in cockpit.conf but either it's not working or the conf file isn't being picked up for some reason (it's in /etc/cockpit) - the site was unreachable when trying to use http://. It's not something I need long term, though I will be accessing cockpit over a VPN in the future, but it would maybe be useful for testing / trying out in light of certificate issues.

**Comment by brettpatram** [comment]
It appears to be an issue with the group ownership of /etc/cockpit.conf file 
Changing group ownership to cockpit-ws  and restarting the service resolves the issue and conf file can be read and the key/values then get set as expected

`chgrp cockpit-ws cockpit.conf`

**Comment by marusak** [comment]
> It appears to be an issue with the group ownership of /etc/cockpit.conf file

(I assume you meant `/etc/cockpit/cockpit.conf`)
We don't ship `/etc/cockpit/cockpit.conf` by default so it just had to be created wrongly on your system. There is not much we can do about it. What are the current permissions on this file, or do you remember what they were before?
```
$ ls -l /etc/cockpit/cockpit.conf
-rw-r--r--. 1 root root 24 Sep  2 09:36 /etc/cockpit/cockpit.conf
```
which are the usual permissions for any config in `/etc` and it works just fine.

**Comment by brettpatram** [comment]
Yes, sorry - /etc/cockput/cockpit.conf

The permissions originally were root root on the file

`-rw-r--r--  1 root root          5 Sep  2 06:59 cockpit.conf`

I went down this path because when I looked at the service file that was installed it appears to execute under cockpit-ws for user and group.  On a hunch I changed the group permission of cockpit.conf to  cockpit-ws to get the config file to be read.

This is on a Debian "Buster" 10.5 distro

```
[Unit]
Description=Cockpit Web Service
Documentation=man:cockpit-ws(8)
Requires=cockpit.socket

[Service]
ExecStartPre=/usr/sbin/remotectl certificate --ensure --user=root --group=cockpit-ws --selinux-type=
ExecStart=/usr/lib/cockpit/cockpit-ws
PermissionsStartOnly=true
User=cockpit-ws
Group=cockpit-ws
```

**Comment by neilthomson** [comment]
Can confirm changing the user of cockpit.conf to cockpit-ws works.

**Comment by martinpitt** [comment]
root:root with being world readable should totally work. If it didn't, then there is something wrong elsewhere. (We do test that scenario dozens of times every day). But perhaps the /etc/cockpit/ directory itself was not readable for the cockpit-ws group? It should also be world-readable, i.e. usual 0755 root:root permissions.

Can you still reproduce this?

**Comment by joe-p** [comment]
I'm seeing the same behavior on Ubuntu 20.04.02 LTS

```
/etc/cockpit$ ls -la
total 20
drwxr-xr-x   4 root root 4096 Mar  3 15:45 .
drwxr-xr-x 116 root root 4096 Mar  3 15:19 ..
-rw-r--r--   1 root root   37 Mar  3 15:45 cockpit.conf
drwxr-xr-x   2 root root 4096 Mar 23  2020 machines.d
drwxr-xr-x   2 root root 4096 Mar  3 15:20 ws-certs.d

/etc/cockpit$ cat cockpit.conf 
[WebService]
AllowUnencrypted = true
```

Still seeing `Mar 03 15:50:30 homeserver cockpit-tls[188367]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.`

The weird thing is that remotectl seems to be able to read the config file. If I put the key-value pair without the group, remotectl recognizes the syntax error: `Mar 03 15:51:40 homeserver remotectl[188676]: remotectl: /etc/cockpit/cockpit.conf: key=val line not in any section: AllowUnencrypt>`. Thus , changing the group does not solve the problem for me.

**Comment by martinpitt** [comment]
Is there anything left in this issue? It seemed to be insuffficient file permissions on cockpit.conf or its containing directory, but I don't see any new information here. Please yell if you still have trouble with this, then I'm happy to reopen.

**Comment by imthenachoman** [comment]
I am also having this issue on Debian stable. Changing the file owner didn't help. 

```
$ ls -la /etc | grep -i cockpit
drwxr-xr-x   4 root root     4096 May 19 22:33 cockpit

$ ls -la /etc/cockpit/cockpit.conf 
-rw-r--r-- 1 cockpit-ws cockpit-ws 38 May 19 22:33 /etc/cockpit/cockpit.conf

$ cat /etc/cockpit/cockpit.conf 
[WebService]
AllowUnencrypted = false
```

**Comment by francoism90** [comment]
I'm also having the same issue on CentOS 9.

Anyone found a workaround? I want to run Cockpit with traefic.

**Comment by ptahchiev** [comment]
I have the same issue.. And I don't even have `cockpit-ws` role.
````
root@cockpit:~# ls -la /etc/cockpit
total 24
drwxr-xr-x  4 root root 4096 Dec  6 20:15 .
drwxr-xr-x 81 root root 4096 Dec  6 20:15 ..
-rw-r--r--  1 root root   37 Dec  6 20:15 cockpit.conf
-rw-r--r--  1 root root   59 Dec  6 19:57 disallowed-users
drwxr-xr-x  2 root root 4096 Nov 29 10:20 machines.d
drwxr-xr-x  2 root root 4096 Dec  6 20:00 ws-certs.d
````
