### ISSUE TITLE
Cannot create VM, operating system field greyed out

### ISSUE THREAD

**Issue by ogghi** [cockpit-project/cockpit#14501]
Cockpit version: 225-1~bpo10+1
OS: Debian (OMV)
Page: Virtual machines

As the title says, the field is greyed out, cannot create the VM.

![image](https://user-images.githubusercontent.com/21173094/91033183-4418fc80-e603-11ea-944f-641297ce90ce.png)

**Comment by KKoukiou** [comment]
Thanks for reporting this @ogghi. When you insert the ISO we try to auto detect the OS form the ISO file, using a script I will paste bellow. The only reason the that field is greyed out is that the OS auto detection is in progress. Of course auto detection of the OS from the ISO should not take more than some fractions of a seconds, thus I would like to check how that script behaves on your system.
If you can run it against you ISO file and report if it's getting stuck, that would help me debugging your issue.

```
#!/usr/bin/python3

import gi
gi.require_version('Libosinfo', '1.0')
from gi.repository import Libosinfo
import sys
import json


loader = Libosinfo.Loader()
loader.process_default_path()
db = loader.get_db()

url_type_media = sys.argv[1].endswith(".iso")

os = None
res = {}
if url_type_media:
    media = Libosinfo.Media().create_from_location(sys.argv[1])
    db.identify_media(media)
    os = media.get_os()
    if os:
        res = { 'os': os.get_id(), 'media': media.get_id() };
else:
    tree = Libosinfo.Tree().create_from_location(sys.argv[1])
    os, _ = db.guess_os_from_tree(tree)
    if os:
        res = { 'os': os.get_id() };

print(json.dumps(res))

```

Take the above script and run it with 1 single parameter, your ISO file path.

So something like this: 
```
autoDetectOS.py ~/Downloads/Fedora-Server-netinst-x86_64-31-1.9.iso
```

Normally you should immediately get an output, like this:
```
{"os": "http://fedoraproject.org/fedora/31", "media": "http://fedoraproject.org/fedora/31:2"}
```

**Comment by JeongHyeon-Kim** [comment]
Can it also be used for installation via URL?

**Comment by KKoukiou** [comment]
> Can it also be used for installation via URL?

Yes

**Comment by ogghi** [comment]
Hi, if I do:
python3 detectOS.py proxmox-backup-server_BETA-1.iso 

All I get is: {}

**Comment by KKoukiou** [comment]
> Hi, if I do:
> python3 detectOS.py proxmox-backup-server_BETA-1.iso
> 
> All I get is: {}

Ok, the Operating system is not autodetected, but in that case we should allow you to autofill manually. I will fix your issue today, thanks for the help.

**Comment by ogghi** [comment]
Well, many thanks for having a look and getting onto that so quickly!

**Comment by ogghi** [comment]
Hi @martinpitt 
Thanks for pushing this fix quickly! How can I get this into my homelab prod environment?
I just would like to create a VM :P

**Comment by KKoukiou** [comment]
@ogghi This fix will be part of cockpit-machines 22,  which we made today,. I guess @martinpitt will update the package in testing in the following days. Try to update once 227~1 it's available in https://packages.debian.org/testing/cockpit-machines

**Comment by ogghi** [comment]
Wow, thanks! 
I will see tomorrow late CET if I find time

**Comment by ogghi** [comment]
Thanks a lot, this worked :+1:
