### ISSUE TITLE
machines: confusing combination of units in usage tab if VM is under 1 GiB

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#14503]
Cockpit version: 222
OS: Fedora
Page: Machines

If you create a VM with less than 1 GiB RAM, it makes the usage tab kind of hard to read. The used memory is displayed in GiB, but the total amount of memory is displayed in MiB. Forcing you to do maths in your head.
_"Uh, let's see, 1 GiB is 1024 MiB, so 0.06 GiB is..."_

**Steps to reproduce**
1. Create a VM and set the memory maximum allocation to something below 1 GiB
2. Go to the Usage tab

![Screenshot from 2020-08-24 19-06-57](https://user-images.githubusercontent.com/209895/91074998-ac84cf80-e63d-11ea-9cae-f6ed93b83c85.png)

![Screenshot from 2020-08-24 19-06-49](https://user-images.githubusercontent.com/209895/91075009-aee72980-e63d-11ea-9550-ca4a26dde0a9.png)

**Comment by marusak** [comment]
@skobyda can you please take a look? Should be straight forward - just pick one appropriate unit for both values and not two separate ones.
