### ISSUE TITLE
Auto-login with URL parameters

### ISSUE THREAD

**Issue by ahmedmgh67** [cockpit-project/cockpit#14519]
Page: Login

Make the login inputs auto-fill from the URL parameters
We're building a product where we install Cockpit for our users on their servers and we want to make a button that launches Cockpit in a new page 
Currently, we show them the password they should enter but it would be much nicer if we can auto-login them 
For example http://IP_ADDRESS:9090/login?username=USERNAME&password=PASSWORD 
And the form will capture the credentials from the URL and login automatically

**Comment by martinpitt** [comment]
Putting cleartext passwords into the URL is a really bad idea. It'll land in the browser history, is shown in the URL bar, and such. Sorry, we won't add that. However, cockpit URLs *do* accept the usual `Authorization: Basic ...` header, so if you want you can call /cockpit/login programmatically, grab the authorization cookie, and set it in the browser. Or maybe you don't want password authentication, but something else like ssh or kerberos?

This really depends on what precisely you are trying to achieve.

**Comment by ahmedmgh67** [comment]
@martinpitt 
We're using a file manager that gets the password from the URL but in base64 encryption
Maybe that'll be a good idea?

**Comment by ahmedmgh67** [comment]
@martinpitt What do you think of putting the password in base64 encoding

**Comment by marusak** [comment]
> What do you think of putting the password in base64 encoding

base64 is indeed encoding and not encryption. It has exactly the same problems as having it in a clear text form. I am sure that we won't support passing password in any form in the URL, that is just a very bad practice. There are other ways how one can authorize.
If you can show us exactly what you do and what you need we will surely be happy to guide you but closing as request for password in URL.

**Comment by ahmedmgh67** [comment]
Essentially, I want to generate auto-login links 
Something like [this](https://www.monstaftp.com/guides/how-to-auto-generate-log-in-links), is this possible?

**Comment by martinpitt** [comment]
Perhaps go a completely different route with ssh, and try something like

    /usr/libexec/cockpit-desktop you@remote.server /

See man cockpit-desktop for details.
