### ISSUE TITLE
Don't offer busy devices for RAID creation (such as `/dev/zram0`)

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#14516]
Even though it fails with expected error `Error opening device /dev/zram0 while creating mdraid: Device or resource busy` would it be possible not to offer such devices?
@mvollmer WDYT?

(Note: This issue is referenced in tests, grab for it if it is being act upon)

**Comment by KKoukiou** [comment]
@marusak you fixed this as part of https://github.com/cockpit-project/cockpit/commit/80580e189b7d3eff62d93632e2c189c5dc572a18, right?

**Comment by marusak** [comment]
No no, that is unrelated. That was about name, this is about devices.
