### ISSUE TITLE
firewall page regression

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#14511]
Cockpit version: master
OS: Fedora
Page: Network

I think commit fb793b3e1fea7ba4755040e41818449c952c3e32 introduced a small color regression on the Firewall page.
It is now a white background instead of a gray background.

**Comment by andreasn** [comment]
Before:
![Screenshot from 2020-08-26 19-00-25](https://user-images.githubusercontent.com/209895/91333854-6e6ae580-e7ce-11ea-9bd5-5730aa680f6b.png)

After:
![Screenshot from 2020-08-26 19-00-49](https://user-images.githubusercontent.com/209895/91333886-7cb90180-e7ce-11ea-959d-11a1efbc8317.png)

**Comment by martinpitt** [comment]
How odd - in performance-graphs I got it the other way round: Today I introduced `<Page>` which turned my white background into a gray one.
