### ISSUE TITLE
Containers: volumes

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1451]
This has been on my made a bit of late, since I've been doing this quite a bit via the CLI on my home server, so I thought I might as well file an issue about it.
A very basic Docker functionality is to mount volumes. Either from the host, or from a so called Data Container (basically, another container).
Some documentation here: https://docs.docker.com/userguide/dockervolumes/

Somewhat related to https://github.com/cockpit-project/cockpit/wiki/Atomic:-Docker-Storage

**Comment by andreasn** [comment]
Needs support for both mounting a directory on the host and using a volume from another

**Comment by andreasn** [comment]
http://docs.docker.com/userguide/dockervolumes/

**Comment by andreasn** [comment]
First stab at this. The concept of volumes from a volume container is still a bit fuzzy to me. Don't you need to specify path in the container you want to use it in for that?

![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/containers/docker-volumes.png)

**Comment by andreasn** [comment]
Ah, apparently not http://stackoverflow.com/questions/23137544/how-to-map-volume-paths-using-dockers-volumes-from

**Comment by andreasn** [comment]
so all data volumes that I've seen has at least one or two things under VOLUME and that corresponds to the directory that get mounted on the container that uses --volumes-from
so for example, maxexcloo/data [1] in it's dockerfile has:
    VOLUME /data
running that, and then running:
    docker run -d -P --volumes-from tutum/wordpress
will then mount the directory /data in / of the wordpress container.

The dialog therefore needs to indicate where those directories will be mounted.

**Comment by andreasn** [comment]
Updated the mockup above to use an uneditable field in the case of a container volume.
Gave them boxes around to keep the rows together.

**Comment by williamjmorenor** [comment]
Think a made a duplicate issue :(

https://github.com/cockpit-project/cockpit/issues/1666

**Comment by andreasn** [comment]
@williamjmorenor no worries. I would rather have one duplicate too much, than one report too little.
I've now closed the duplicate.

**Comment by andreasn** [comment]
as discussed on IRC, lets do the file path freeform. Also added a little dropdown to choose between read only and not.
@petervo are you also doing container volumes as part of this, or should it be a separate issue? I have less experience with container volumes, so the UI suggestions above might not be 100% excellent.

**Comment by chrrrles** [comment]
It would be nice to set values for both`volumes` and `env`; even if that is a manual process.

**Comment by mysqlboy** [comment]
Just finding this too. Seems to be an integral part of starting containers missed here.

**Comment by crestone** [comment]
+++ I was looking for information about control a volumes in Docker via Cockpit and found this issue.

**Comment by QUASARFREAK** [comment]
++++

**Comment by stefwalter** [comment]
This was implemented by @vanloswang. Yay! #4726
