### ISSUE TITLE
Allow users in a certain group to view logs without giving them all privileges.

### ISSUE THREAD

**Issue by GlenBleidd** [cockpit-project/cockpit#14515]
Hi, just a question, is it possible to allow a group, for example; called **operators** to access the logs without making them administrators? Thanks

**Comment by marusak** [comment]
Cockpit is using `journalctl` and normal users privileges. So logs that user can see when doing `journalctl` are the same logs the same user can see in the UI.

**Comment by GlenBleidd** [comment]
Oh I see, running the journalctl on the terminal shows me more logs than the UI, why is that? Sorry, kinda new to this.

**Comment by marusak** [comment]
> Oh I see, running the journalctl on the terminal shows me more logs than the UI, why is that? Sorry, kinda new to this.

No worries :) Do you just call `journalctl`, right? It shows all logs, in Cockpit we, by default, show only for priorities `Error and above`. If you want to see the same output change to `Debug and above`.

**Comment by GlenBleidd** [comment]
I can't see some specific service logs (nginx, rsyslog) with normal users so I just added these users to the group systemd-journal and now I can see those logs. Not sure if this is safe though?

**Comment by GlenBleidd** [comment]
Found a way to allow [groups to view journalctl](https://unix.stackexchange.com/questions/510358/how-to-let-a-specific-group-have-read-access-to-systemds-journal).  This answers my question. Thanks!

**Comment by marusak** [comment]
> Found a way to allow groups to view journalctl. This answers my question. 

Does it then also work in cockpit?
