### ISSUE TITLE
Cockpit reporting very high amount of used RAM when server is IDLE.

### ISSUE THREAD

**Issue by philipperemy** [cockpit-project/cockpit#14520]
We should probably map the RAM memory in "green" (Used memory ) and not in "yellow" (Cache).

https://serverfault.com/questions/180711/what-exactly-do-the-colors-in-htop-status-bars-mean

Otherwise it might be misleading for the average user.

![image](https://user-images.githubusercontent.com/4516927/91518015-2e207a00-e92a-11ea-8b8c-8884306c6eef.png)

![image](https://user-images.githubusercontent.com/4516927/91518032-3678b500-e92a-11ea-978f-04a09a54e5b0.png)

**Comment by KKoukiou** [comment]
@philipperemy since you reported this issue we deprecated this graph in favor of the graphs in the metrics page.
See:
![Screen Shot 2021-02-12 at 22 40 33](https://user-images.githubusercontent.com/14921356/107829971-24c98380-6d8b-11eb-8d05-123a66e9a0ad.png)

**Comment by philipperemy** [comment]
@KKoukiou thanks!
