### ISSUE TITLE
Idea : Add a server title and description

### ISSUE THREAD

**Issue by dx44** [cockpit-project/cockpit#14542]
Page: Dashboard 

Hello,
a server name is not always meaningful. It is often based on a template like srvxxx. Each administrator doesn't know which machine is doing what.
It will be usefull to append a title or/and a short description to display in the dashboard machine list (and in other part).
This attributes could be in the `cockpit.conf` like :
```
title = my server
description = primary server
```

Regards.

**Comment by marusak** [comment]
Why just not giving the server some meaningful name? Cockpit allows users to change name of the server, which is then shown in the dashboard (obsoleted now by the integrated host switcher).
And `cockpit.conf` is not the expected place, it should be in `/etc/cockpit/machines.d` but honestly I am not a huge fan of this.

**Comment by martinpitt** [comment]
cockpit.conf is no good indeed -- that does not apply to remote ssh machines. There really should not be a cockpit specific machine description -- cockpit *is* your server, it's not some management layer/configuration on top of it. You can use pretty host names (a systemd hostnamed concept) or assign meaningful hostnames, etc., but we won't invent a cockpit specific labeling system.

**Comment by dx44** [comment]
You're right, systemd-hostnamed does the job with cockpit ! Thanks.
