### ISSUE TITLE
consider ct-form-info for ct-form when there's no form involved

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#14548]
There's a variant of `ct-form` called `ct-form-info` that some pages are already using, when forms are not involved. It's similar to `ct-form-compact`, but with additional style adjustments.

We should look at the instances of `ct-form` across Cockpit and adjust where appropriate.

Additionally, in some of these places, `<form>` and `<label>` should not be used. They're for actual forms with widgets, not for various bits of data.

**Comment by KKoukiou** [comment]
PF4 already offers  component for displaying data like this.
https://www.patternfly.org/v4/documentation/react/components/descriptionlist 

At some point we should start replacing our ct-form, ct-form-info occurances where these are not a form with the PF provided one.

**Comment by garrett** [comment]
Ah, cool. That's new.

**Comment by garrett** [comment]
Closing, as we should use PF4's description list instead (as @KKoukiou pointed out).
