### ISSUE TITLE
services: Drop details page for Template "instantiation"

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#14549]
Some of the service details pages are really odd:

![details page](https://user-images.githubusercontent.com/12330670/91961727-dc9e3380-ed0b-11ea-98d1-3c7f4115b90b.png)

1. What is this? 
2. What is it supposed to be doing?
3. There's a random <hr> for no reason
4. some space below the button
5. no heading
6. no guidance at all what someone is supposed to do here
7. I think the input is unstyled

The error should either be inside like the first item (which feels weird to me) or outside the card (treating it as a complete unit) and not be styled like an inline alert, but as a default one — or have a shadow at least, like on the overview page. (`box-shadow: var(--pf-global--BoxShadow--sm);`).

Discussed in https://github.com/cockpit-project/cockpit/pull/14547#discussion_r481915348

**Comment by martinpitt** [comment]
Honestly, let's just kill that page. In most cases where templates are involved, users would not start random instances by hand. It's not really what they are meant to do. 

So far I encountered one such case with `syncthing@<username>.service`. But what you really want to do there is to `systemctl enable --now` them, not just `start` them.

**Comment by marusak** [comment]
> Honestly, let's just kill that page. 

I mean, sure why not :) Two points:
1. It does not do much harm to have it there, but if we are concern that users don't know what it means and what it does, we can obsolete it. Worst case scenario is that customer complains it disappered and we will revert the commit :)
2. Show we then not list templates as well?

**Comment by garrett** [comment]
>    It does not do much harm to have it there, but if we are concern that users don't know what it means and what it does, we can obsolete it. 

Or we could explain what it does. (But yeah, removing it is fine, if @martinpitt thinks we should.)


>    Show we then not list templates as well?

Perhaps?

Can you come up with a story how templates are useful? And how they would be useful in Cockpit, not just at the command line?

**Comment by marusak** [comment]
Heh, just found out that I opened same issue one and half years ago :) 
https://github.com/cockpit-project/cockpit/issues/11269

So I guess lets drop it since we don't know what to do with it...
