### ISSUE TITLE
machines: randomly switches away from the Snapshots tab under my feet

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#14552]
Cockpit version: 226
OS: Debian
Page: Virtual Machines

If I have the Snapshots tab open for a little while and don't interact with it, it will sometimes suddenly switch over to the Overview tab, out of the blue. This can also happen right after I create a new snapshot. I'm afraid I don't have more info than that.

**Comment by marusak** [comment]
Seems like the same issue as reported in https://bugzilla.redhat.com/show_bug.cgi?id=1862406
