### ISSUE TITLE
Issues after building Cockpit 226 from source and running CentOS 8.2.2004

### ISSUE THREAD

**Issue by digitalformula** [cockpit-project/cockpit#14553]
Cockpit version: 226
OS: CentOS 8.2.2004
Page: Login

Can start `cockpit.socket` and open the home page, but can't login.

This doesn't seem to be an issue with `cockpit-211` from the CentOS repos but that version is so far behind that I'd like to run the latest and haven't found an effective way of doing that via `yum` or `dnf`.

I guess I should ask first, before anyone reads any further - is Cockpit expected to run without issues on CentOS 8.2.2004?

Steps to reproduce/what I did.

- Downloaded cockpit-226.tar.xz from repo
- Installed dependencies for ./configure
- Ran `./configure --disable-pcp`
- Ran `make`
- Ran `make install`
- Ran `systemctl start cockpit.socket`
- [Installed my certificates](https://cockpit-project.org/guide/149/cockpit-ws.8.html) to `/usr/local/etc/cockpit/ws-certs.d` and verified they're being used with `remotectl certificate`
- Browsed to port 9090 on my host (works fine)
- Tried to login but get **Wrong user name or password** no matter which account I use

Note: The problem is the same whether I use my certs or the system-generated self-signed certs.

`sudo tail /var/log/messages` shows:

    Sep  2 22:26:39 centos-nas systemd[1]: Starting Socket for Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
    Sep  2 22:26:39 centos-nas systemd[1]: Listening on Socket for Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
    Sep  2 22:26:39 centos-nas systemd[1]: Started Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
    Sep  2 22:26:40 centos-nas cockpit-ws[4031]: cockpit-ws: Failed to open certificate file /run/cockpit/tls/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: No such file or directory
    Sep  2 22:26:44 centos-nas cockpit-ws[4031]: cockpit-ws: Failed to open certificate file /run/cockpit/tls/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: No such file or directory

Additional info:

- Have disabled `firewalld` (problem persists)
- Have disabled SELinux by setting it to both `permissive` and `disabled` then rebooting (problem persists)
- The installation steps above work perfectly on Ubuntu 20.04 (minus the cert install)

In [issue 11521](https://github.com/cockpit-project/cockpit/issues/11531) I found this command:

    env -u DISPLAY sudo G_MESSAGES_DEBUG=all /usr/local/sbin/remotectl certificate --ensure --user=root --group=cockpit-ws --selinux-type=etc_t

Output:

    [root@centos-nas ~]# env -u DISPLAY sudo G_MESSAGES_DEBUG=all /usr/local/sbin/remotectl certificate --ensure --user=root --group=cockpit-ws --selinux-type=etc_t
    ** (remotectl:4318): DEBUG: 22:30:49.015: loaded separate cert /usr/local/etc/cockpit/ws-certs.d/custom.net.cert and key /usr/local/etc/cockpit/ws-certs.d/custom.net.key
    ** (remotectl:4318): DEBUG: 22:30:49.015: loaded 1 certificates from /usr/local/etc/cockpit/ws-certs.d/custom.net.cert
    [root@centos-nas ~]#

Logs:

    [root@centos-nas ~]# journalctl -u cockpit -b
    -- Logs begin at Wed 2020-09-02 22:26:01 AEST, end at Thu 2020-09-03 11:40:49 AEST. --
    <snip>
    Sep 03 11:34:52 centos-nas.network.net systemd[1]: Starting Cockpit Web Service...
    Sep 03 11:34:52 centos-nas.network.net systemd[1]: Started Cockpit Web Service.
    Sep 03 11:34:56 centos-nas.network.net systemd[1]: Stopping Cockpit Web Service...
    Sep 03 11:34:56 centos-nas.network.net systemd[1]: Stopped Cockpit Web Service.
    Sep 03 11:34:56 centos-nas.network.net systemd[1]: Starting Cockpit Web Service...
    Sep 03 11:34:56 centos-nas.network.net systemd[1]: Started Cockpit Web Service.

Screenshots:

(Yes, I know I'm using `root` here but the issue persists no matter which account I use).

![Screenshot from 2020-09-02 21-00-40](https://user-images.githubusercontent.com/423229/91973318-64f9f400-ed5f-11ea-85ec-82fb6918003f.png)

Chrome dev tools showing HTTP 401:

![_Screenshot from 2020-09-02 22-35-18](https://user-images.githubusercontent.com/423229/91982044-089dd100-ed6d-11ea-9898-31a879afe110.png)

**Comment by digitalformula** [comment]
For what it's worth, the same issue occurs with Cockpit 226 on CentOS 8 Stream, where only 211 is available via `dnf`.

**Comment by martinpitt** [comment]
@digitalformula : did you install an appropriate /etc/pam.d/cockpit ? [This](https://github.com/cockpit-project/cockpit/blob/master/tools/cockpit.pam) is the one that the RPM installs for Fedora/RHEL. I also urgently recommend to not do `sudo make install`, but build RPMs and install these.

Our [COPR](https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/) has CentOS 8 packages, these are by far the easiest and safest way to get current Cockpit versions on CentOS 8.

**Comment by digitalformula** [comment]
> @digitalformula : did you install an appropriate /etc/pam.d/cockpit ? [This](https://github.com/cockpit-project/cockpit/blob/master/tools/cockpit.pam) is the one that the RPM installs for Fedora/RHEL. I also urgently recommend to not do `sudo make install`, but build RPMs and install these.
> 
> Our [COPR](https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/) has CentOS 8 packages, these are by far the easiest and safest way to get current Cockpit versions on CentOS 8.

Thanks so much @martinpitt - the advice is much appreciated.  Apologies for the n00b behaviour - your direction to use the COPR packages has worked perfectly.  Thanks again for this and for your work on Cockpit - it really is great.
