### ISSUE TITLE
¡Thank you for creating cockpit!

### ISSUE THREAD

**Issue by psociety** [cockpit-project/cockpit#14556]
When i installed it i didn't think i was really going to use it but, in just a few days it has already helped me alot!
I needed to format some drives and internet was throwing more and more commands, which i wasn't sure how to properly set.
Turns out cockpit has a format feature and with 3 clicks i had a format already going on.
I was also copying files between disks and having a graph/data telling me if it was still doing it's job has proven really useful too!

Now everytime i want to do something, i check if cockpit does it already :)

(Sorry, opening an issue was the faster way to reach cockpit devs for me)

**Comment by martinpitt** [comment]
What a pleasure to see such an issue for a change! Glad you like it! :heart_eyes:

**Comment by tetreum** [comment]
Oh!, and i forgot:
I was also having trouble mounting drives with fstab because, i didn't exactly know which was the correct "drive id"/uuid, breaking /not letting the server boot in the process.
Again, cockpit had a "mount" feature that did the proper setup for me :o

**Comment by psociety** [comment]
Oh!, and i forgot:
I was also having trouble mounting drives with fstab because, i didn't exactly know which was the correct "drive id"/uuid, breaking /not letting the server boot in the process.
Again, cockpit had a "mount" feature that did the proper setup for me :o

**Comment by marusak** [comment]
I hate to close this issue, but it is our current issue cleanup :)
