### ISSUE TITLE
openrc 

### ISSUE THREAD

**Issue by necrose99** [cockpit-project/cockpit#14565]
https://github.com/goose121/initify 

https://gitweb.gentoo.org/proj/openrc-settingsd.git   
lets systemd run openrc scripts 
**lets openrc RUN  sytemd's UNITS...** 

[openr-units.zip](https://github.com/cockpit-project/cockpit/files/5171197/openr-units.zip)

socket not converted. :-( however if settings yaml... 

```
#!/sbin/openrc-run

command=/usr/bin/mottainai-agent
command_args="agent --config /etc/mottainai/mottainai-agent.yaml"
pidfile=

name="mottainai-agent"
description="Mottainai Agent"
```
for more hardened servers , openrc is often picked.

**Comment by necrose99** [comment]
```
#!/sbin/openrc-run

command=/usr/lib/cockpit/cockpit-ws
command_args="/usr/sbin/remotectl certificate --ensure --user=root --group=cockpit-ws --selinux-type="
pidfile=

name="cockpit"
description="Cockpit Web Service"
```

```
#!/sbin/openrc-run

command=-/usr/share/cockpit/motd/update-motd
command_args=""
pidfile=

name="cockpit-motd"
description="Cockpit Web Service"
```

**Comment by martinpitt** [comment]
A lot of cockpit assumes systemd -- these days, cockpit.socket/service rely on socket activation not only for the primary cockpit-tls, but also for the secondary cockpit-ws@ instances. At some point, cockpit-ws will drop doing TLS by itself, we only keep that for backwards compatibility now. Also, a lot of the pages talk to systemd APIs for service management.

So, of course you can get some functionality without systemd (like starting cockpit-ws directly that way), but this is not what we want to officially support.

A better route for such scenarios is to let cockpit-ws run on a separate server ("bastion host"), and connect to critical machines through ssh only (adding them as additional hosts, or straight from the "Connect to:" on the login page). That way, you don't even need to open an additional port on these server targets. That will at least take care of the webserver bits -- of course page functionality will still be broken when they try and talk to systemd, but some bits should work.

**Comment by necrose99** [comment]
I however didn't feel like having to rig a lxc or docker bastion bridge.. 
Esp for just a few nodes on lan ,classics like webmin still can work, just the Security holes they had leaves some wariness.. 

Perhaps later when my VMware arsinal becomes more than a few linux machines.. 

A few systemd emulation shims like the dbus settingsd etc.. 

Sabayon fork of gentoo works, obviously as systemd is defacto.. gentoo openrc however I'd befoced to chroot into , setup a separate developer box etc.. just to do admin on a trivial developer box.. were systemd and will not run these secops testing pkgs. 

So much for easy button,  or adding back some classic shims for OPENRC etc.. 
Only elogind is split of of systemd  in OPENRC profiles..

**Comment by stormalf** [comment]
Hello, yes it's possible to use cockpit on wsl2 after some configuration. The service doesn't start automatically, but you can start cockpit after doing : 

- /usr/lib/cockpit/cockpit-certificate-ensure --for-cockpit-tls
- ./cockpit-ws

 uname -a
Linux great-server 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
greatuser@great-server:/lib/systemd/system# netstat -lpnt | grep 9090
tcp6       0      0 :::9090                 :::*                    LISTEN      1060/cockpit-ws
