### ISSUE TITLE
Updates are installed from backports

### ISSUE THREAD

**Issue by RoyKas** [cockpit-project/cockpit#14573]
Cockpit version: 225
OS: Debian 10 (Buster)
Page: Software Updates

I have noticed that resent updated packages are ~bpo10 version. These updates have been performed from within Cockpit.

I have the impression that the Cockpit Plug-in "Software Updates" installs updated from the backports repository, and not from the main Buster repository.

In apt.conf I have included:
`APT::Default-Release "buster";`

Am I missing something, or is it actually a bug?

How can I help and reproduce this assumption? I can update from within Cockpit, but I don't know how to correct the packages (reverting from backport to main repository).

**Comment by KKoukiou** [comment]
What is your `/etc/apt/sources.list`?

**Comment by RoyKas** [comment]
sources.list:
```
deb http://deb.debian.org/debian/ buster main non-free
deb-src http://deb.debian.org/debian/ buster main non-free
deb http://security.debian.org/debian-security buster/updates main non-free
deb-src http://security.debian.org/debian-security buster/updates main non-free
deb http://deb.debian.org/debian/ buster-updates main non-free
deb-src http://deb.debian.org/debian/ buster-updates main non-free
deb https://packages.grafana.com/oss/deb stable main
```

sources.list.d/backports.list
`deb http://deb.debian.org/debian buster-backports main`

sources.list.d/influxdb.list
`deb https://repos.influxdata.com/debian buster stable`

**Comment by martinpitt** [comment]
@RoyKas: Supposedly the same happens with `pkcon update`. This sounds like a bug in the apt backend of packagekit, in that it does not properly respect package priorities.

**Comment by marusak** [comment]
Cockpit uses packagekit directly. We do not do any repository selection or anything like that, thus this is issue in packagekit or somewhere in your configuration. If it still happens to you I suggest opening issue for packagekit.
