### ISSUE TITLE
Feature Request: Update manager on dashboard

### ISSUE THREAD

**Issue by shortNviolent** [cockpit-project/cockpit#14570]
Hey Guys,

First wanted to say thanks for creating cockpit it is so great. 

Second request is for a update tab on the dashboard that shows all the servers and there updated state with the ability to select all/some/one of the servers and kick off updating. If you want to go crazy maybe some way of selecting certain packages and just updating them alone but you know small wins first and all :D

Thanks

**Comment by marusak** [comment]
Cockpit is not for managing a fleet of servers. Cockpit is focused more on managing/debuging a single server.
There are other great tools which can update all/some/one of the servers in your fleet, also likely supporting advanced options like updating a specific package.

Note: There is a request to show if server needs updates in https://github.com/cockpit-project/cockpit/issues/11275
