### ISSUE TITLE
No dashboard visible in version 227-1~ubuntu20.04.1

### ISSUE THREAD

**Issue by joeinwap** [cockpit-project/cockpit#14587]
Cockpit version: 227-1~ubuntu20.04.1
OS: Ubuntu 20.04 LTS
Page: Dashboard

No dashboard is visible on the latest version distributed by Ubuntu.

root@zathras:/var/log# apt install cockpit
cockpit is already the newest version (227-1~ubuntu20.04.1).
root@zathras:/var/log# apt install cockpit-dashboard
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 cockpit-dashboard : Depends: cockpit-ws (< 215-1.1~) but 227-1~ubuntu20.04.1 is to be installed

Steps to reproduce

1.  Log in to a system that is running 215-1~ubuntu18.04.1 - Dashboard show up.
2.  Log in to a system that is running 227-1~ubuntu20.04.1 - no Dashboard is visible.
3.  Try installing cockpit-dashboard - it is the wrong version.

**Comment by martinpitt** [comment]
Try 

  apt install -t bionic-backports cockpit-dashboard

You installed the other cockpit packages from backports, so you need to consistently enable it for all of them.

**Comment by joeinwap** [comment]
The command **apt install -t focal-backports cockpit-dashboard** did the trick.  Thanks.

**Comment by martinpitt** [comment]
@joeinwap : Ah, focal of course, not bionic. Glad that it works!
