### ISSUE TITLE
F31 and OVH VPS : selinux cause cockpit service fail to start

### ISSUE THREAD

**Issue by lynerlok** [cockpit-project/cockpit#14586]
Cockpit version: 226
OS: Fedora 31 5.3.7-301.fc31.x86_64 #1 SMP Mon Oct 21 19:18:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux on OVH VPS
Page: Machines

Hi, I have a strange error when I try to install cockpit on a new OVH VPS with fedora 31 : cockpit.service fail because permission problem on remotectl and cockpit unit tls.
There isn't firewall on this configuration so the issue is not related to it.

I haven't this error since I use cockpit and journals aren't very verbose...

Results  by `journalctl -u cockpit`

```Sep 08 14:59:31 vps-XXX.vps.ovh.net systemd[1]: Starting Cockpit Web Service...
Sep 08 14:59:31 vps-XXX.vps.ovh.net systemd[12506]: cockpit.service: Failed to set up mount namespacing: /run/systemd/unit-root/run/cockpit/tls: Permission denied
Sep 08 14:59:31 vps-XXX.vps.ovh.net systemd[12506]: cockpit.service: Failed at step NAMESPACE spawning /usr/sbin/remotectl: Permission denied
Sep 08 14:59:31 vps-XXX.vps.ovh.net systemd[1]: cockpit.service: Control process exited, code=exited, status=226/NAMESPACE
Sep 08 14:59:31 vps-XXX.vps.ovh.net systemd[1]: cockpit.service: Failed with result 'exit-code'.
Sep 08 14:59:31 vps-XXX.vps.ovh.net systemd[1]: Failed to start Cockpit Web Service.
```
Results by `ausearch -m AVC,USER_AVC -ts today`

```time->Wed Sep  9 08:35:41 2020
type=AVC msg=audit(1599640541.733:128): avc:  denied  { mounton } for  pid=761 comm="(emotectl)" path="/run/systemd/unit-root/run/cockpit/tls" dev="tmpfs" ino=22179 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:cockpit_var_run_t:s0 tclass=dir permissive=0
```

Steps to reproduce

1. Install my fedora version and cockpit packages as `dnf install cockpit cockpit-selinux`
2. Check selinux is in enforcing mode ( `getenforce` )
3. Now start the service which failed ( and enable it )...
4. Switch selinux into permissive mode
5. Reboot
6. Now it's ok cockpit start

Web browser return unable to connect if service fail or connect normaly if service start.

**Comment by martinpitt** [comment]
@lynerlok : This is an SELinux bug, tracked here: https://bugzilla.redhat.com/show_bug.cgi?id=1874836
