### ISSUE TITLE
Support public-key auth when connecting via SSH

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1461]
We can use an ssh key with a specific name ```cockpit.pub``` in the user's home directory when connecting out via SSH.

This will allow us to manage servers where password based auth is disabled. Note that the user will still be the same as the user name that authenticated against cockpit.

**Comment by yuergen** [comment]
Hello @stefwalter, I just stumbled here. I just tried out cockpit while I set up a few test systems and when I disabled password authentication for ssh cockpit broke. This is seems to be perfectly alright because there is no way to use a ssh key with cockpit.
I understand you plan to add this functionality by making it possible for the user to supply keys to cockpit. I would be perfectly fine with that - as long as at least the login password is used to unlock these.
Thanks to the cockpit team for some promising looking tool! :)

**Comment by stefwalter** [comment]
>  I understand you plan to add this functionality by making it possible for the user to supply keys to cockpit. I would be perfectly fine with that - as long as at least the login password is used to unlock these.

Exactly. I was talking with @gladiac about libssh and how we can accomplish that using an ssh agent, so we don't have to hand keys around. But either way we can make this work.

**Comment by yuergen** [comment]
Thank you for another quick answer. I am keen to finally ditch password authentication. :)

**Comment by ibotty** [comment]
I started playing with atomic just now, so I stumbled into it just now.

One can mitigate the risk of allowing password authentication by only allowing password auth from specific hosts. E.g. the following snippet from `/etc/ssh/sshd_config` will allow Password authentication only from localhost. One might want to only allow the IP where cockpit is running.

```
PasswordAuthentication no
Match Address 127.0.0.1,::1
    PasswordAuthentication yes
```

**Comment by stefwalter** [comment]
I think @petervo is doing some interesting work on this issue.

**Comment by gladiac** [comment]
Why do you want/need password authentication?

**Comment by ibotty** [comment]
Because that ticket is not yet closed!? Doesn't cockpit need password auth right now?

**Comment by ibotty** [comment]
@petervo, @stefwalter where is the work he is doing? i did not see any branch/commits in his cockpit repo.

**Comment by petervo** [comment]
#2958 was the last piece of this. Key based authentication should now work for secondary servers.

**Comment by yuergen** [comment]
That sounds awesome! Thank you for your efforts!

Now we want something like automatic key deployment ... ;-)

**Comment by stefwalter** [comment]
> That sounds awesome! Thank you for your efforts!

Thanks!

> Now we want something like automatic key deployment ... ;-)

I think FreeIPA does this for you.

**Comment by yuergen** [comment]
@stefwalter I will look into FreeIPA. Thanks again!
