### ISSUE TITLE
string fixes for host connector error message

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#14619]
Cockpit version: 227
OS: RHEL
Page: Host connector

Currently the text is:
```
Not connected to host
Login failed
```
It gives very sparse information about what happened, why it failed, and how it can be avoided in the future.

@ShwetaNaresh recommended these strings instead
```
Login failed.
The Web Console is unable to log in to <hostname>.
The SSH key for auto-login is either not available or is unauthorized, or requires a password.
To manually log in to the host, click Log In to manually log in to the host. 
```
She also recommends that we move the error text away from the login dialog and onto the page.

**Comment by andreasn** [comment]
She also provided an alternate, shorter recommendation.

```
Login failed.
The Web Console is unable to log in to <hostname>.
The SSH key for auto-login is either not available, is unauthorized, or is password protected.
To manually log in to the host, click Log In. 
```
I think I like this version better.

**Comment by martinpitt** [comment]
This was covered by the recent SSH login rework, and the description is now much more helpful.
