### ISSUE TITLE
Misdirected D-Bus calls from cockpit-bridge

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#14622]
I can find this in my journal:

```
Sep 15 10:52:26 dev dbus-broker[769]: A security policy denied :1.31 to send method call /org/freedesktop/UDisks2:org.freedesktop.DBus.ObjectManager.GetManagedObjects to org.freedesktop.PackageKit.
```

When I was looking, the `:1.31` name didn't exist on the bus anymore, but I guess it was cockpit-bridge.

I didn't see any problems in the UI, and all of Cockpit worked as expected.

**Comment by mvollmer** [comment]
My journal has many, many of these, but only two variants:

```
Sep 09 14:13:06 dev dbus-broker[776]: A security policy denied :1.96 to send method call /org/storage/stratis2:org.freedesktop.DBus.ObjectManager.GetManagedObjects to org.freedesktop.PackageKit.
```
```
Sep 09 14:19:42 dev dbus-broker[776]: A security policy denied :1.110 to send method call /org/freedesktop/UDisks2:org.freedesktop.DBus.ObjectManager.GetManagedObjects to org.freedesktop.PackageKit.
```

so it must have something to do with the Storage page... I haven't a way to reproduce this reliably.

**Comment by martinpitt** [comment]
My laptops' journal dates back to December 25 right now, and `journalctl  | grep security.*policy.*GetManagedObjects` does not have a single result. `journalctl  | grep security.*policy` gives me several hits of

    dbus-broker[738]: A security policy denied :1.128 to send method call /org/freedesktop/login1:org.freedesktop.login1.Manager.CreateSession to org.freedesktop.login1.

But that's got nothing to do with cockpit.

@mvollmer, do you still get these messages, and do  they actually break anything? Right now this is not very actionable.

**Comment by mvollmer** [comment]
Yes, I still get these, as recent as a week ago:

```
Feb 23 11:38:11 dev dbus-broker[858]: A security policy denied :1.51 to send method call /org/freedesktop/UDisks2:org.freedesktop.DBus.ObjectManager.GetManagedObjects to org.freedesktop.PackageKit.
Feb 23 11:47:35 dev dbus-broker[858]: A security policy denied :1.64 to send method call /org/freedesktop/UDisks2:org.freedesktop.DBus.ObjectManager.GetManagedObjects to org.freedesktop.PackageKit.
Feb 23 11:47:53 dev dbus-broker[858]: A security policy denied :1.64 to send method call /org/storage/stratis2:org.freedesktop.DBus.ObjectManager.GetManagedObjects to org.freedesktop.PackageKit.
```

**Comment by martinpitt** [comment]
Not sure if that's still an issue, but keeping open for now. This might just have fixed itself with the Python bridge, though?

**Comment by mvollmer** [comment]
I think this was fixed by https://github.com/cockpit-project/cockpit/pull/15617

**Comment by martinpitt** [comment]
Oh nice! So we can close this then, and if you run into it again, we reopen?
