### ISSUE TITLE
Can't install cockpid-docker under Arch

### ISSUE THREAD

**Issue by qupfer** [cockpit-project/cockpit#14639]
Hi, 
i tried today cokpit but can't install the docker module. 

First I intalled it via pacman (pikaur)

>  pikaur -Ss cockpit
Suche... [###]
community/cockpit 228-1 [installiert] 
    A systemd web based user interface for Linux servers    
community/cockpit-dashboard 228-1 [installiert] 
    Cockpit support for connecting to remote servers (through ssh), bastion hosts, and a basic dashboard.    
community/cockpit-docker 228-1 [installiert] 
    Cockpit components for interacting with Docker and user interface.    
community/cockpit-machines 228-1 [installiert] 
    Cockpit components for managing virtual machines.    
community/cockpit-pcp 228-1 
    Cockpit support for reading PCP metrics and loading PCP archives    
community/cockpit-podman 22-1 [installiert] 

I can login an see my podman container(s).

But no (docker) container.
![grafik](https://user-images.githubusercontent.com/2614431/93689385-5e44de00-face-11ea-93a8-87efda641379.png)

So I go to "Applications" and click install, but this also failed:
![grafik](https://user-images.githubusercontent.com/2614431/93689397-77e62580-face-11ea-8006-b1617273d86a.png)

Maybe because I moved the docker volumes from /usr/lib to somewhere else? 
via 

>  cat /etc/docker/daemon.json 
{
"graph":"/media/SSD/docker",
"dns" : ["172.17.0.1"]
}

Any ideas? Thanks ;-)

**Comment by marusak** [comment]
So you have `cockpit-docker` installed on your system but it does not show up in the menu?
As a first step I would remove this one package and install it back up.

> Maybe because I moved the docker volumes from /usr/lib to somewhere else?

It still should show up in the menu no matter what one does to docker itself.

**Comment by martinpitt** [comment]
Please also show the contents of the "cockpit-docker" package (I don't know what the command is for pacman, sorry), and the output of `cockpit-bridge --packages`.

**Comment by hartmark** [comment]
I installed cockpit today and saw that there was a page to manage docker containers but I was unable to see that alternative and when searching for cockpit-docker I found that it seems the cockpit-docker pagage is removed

https://www.archlinux.org/packages/community-testing/x86_64/cockpit-docker/

![image](https://user-images.githubusercontent.com/12826053/95692970-f9daf180-0c29-11eb-8287-cd014a86fbd3.png)

**Comment by marusak** [comment]
`cockpit-docker` has been obsoleted and dropped. We have `cockpit-podman` alternative, please use that.

**Comment by Ferryistaken** [comment]
Does this mean that cockpit dropped support for docker? Is this because cockpit is sponsored by RedHat?

**Comment by martinpitt** [comment]
@Ferryistaken : In practice yes, so our development team has no interest/motivation to still maintain cockpit-docker. That of course shouldn't stop anyone from picking it up and maintaining it as a separate project, but the cockpit team itself won't do that any more. (Of course we are happy to help you with the setup and questions.)

**Comment by Ferryistaken** [comment]
Thanks for the clarification
