### ISSUE TITLE
why Machines page don't have Snapshot in version 228

### ISSUE THREAD

**Issue by lijingchun0** [cockpit-project/cockpit#14634]
Cockpit version: 228
OS: Centos 8
Page: Machines

I did not find the snapshot function

Steps to reproduce
![image](https://user-images.githubusercontent.com/26979634/93413801-a0a1cb80-f8d2-11ea-8337-75cd1d4dca7c.png)
![image](https://user-images.githubusercontent.com/26979634/93413839-b57e5f00-f8d2-11ea-83b1-e3fb38522f27.png)

**Comment by martinpitt** [comment]
CentOS 8 does not yet have a new enough libvirt-dbus. You need at least version 1.4.0.
