### ISSUE TITLE
machines: unattended installation password does not work with spaces

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#14632]
Cockpit version: all
OS: any
Page: Machines

Unattended installation's kickstart interprets a password with spaces as a space-delineated list.

Steps to reproduce

1. Create a new virtual machine.
2. Choose "run unattended installation".
3. Add a root password. Make sure to include spaces.

I set my password to "this is a test" and had this as the result:

![Screenshot from 2020-09-16 17-14-34](https://user-images.githubusercontent.com/10246/93357082-380a0e80-f840-11ea-9d1d-bca288902fb8.png)

**Comment by KKoukiou** [comment]
Bug submitted upstream to virt-install, no need to keep this here anymore.
https://bugzilla.redhat.com/show_bug.cgi?id=1902183
