### ISSUE TITLE
machines: should show the listed button completed after click the extend button at the end of each vm

### ISSUE THREAD

**Issue by cxhlunar** [cockpit-project/cockpit#14653]
Cockpit version: all
OS:any
Page: Machines

Steps to reproduce

1. Prepare a running vm 
2. Click the extend button at the end of the vm line
You can see not all items can be shown, you need to drop down the bar on right side to see the all the items, can we make them visible by default? Please check the screenshot.
![screenshot-10 66 93 123_9090-2020 09 23-13_45_35](https://user-images.githubusercontent.com/12710195/93971837-a7818000-fda3-11ea-96c3-8c9772b1fb39.png)

**Comment by skobyda** [comment]
This is fixed as part of https://github.com/cockpit-project/cockpit/pull/14667 in a commit https://github.com/cockpit-project/cockpit/pull/14667/commits/b56ab82a2f72f165046ed9702152e70e15ade208

**Comment by KKoukiou** [comment]
This is fixed already in fact.
