### ISSUE TITLE
machines: Add state of "paused" for Virtual machine list filtering 

### ISSUE THREAD

**Issue by cxhlunar** [cockpit-project/cockpit#14654]
Page: Machines

Now we have vm list filtering function, but can only choose state of : running & shutoff
It's better to have "paused" state since it's one of the state for vm.
![screenshot-10 66 93 123_9090-2020 09 23-14_09_42](https://user-images.githubusercontent.com/12710195/93973260-7a829c80-fda6-11ea-9491-d539462dc59a.png)

**Comment by marusak** [comment]
Right, we hardcode these 3 states. This seems like unlucky way to do this. I think much better approach would be to show there those states, that are currently present. So if we have only running VMs it would show only `Running` (or just hide it in that case?) and if you have some that are running and some that are paused you would have `All`, `Running`, `Paused` and so on.

@skobyda WDYT?

**Comment by skobyda** [comment]
Yup, according to libvirt doc there are multiple VM states https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainState . We could filter by them.  #14667
