### ISSUE TITLE
Cockpit promises return multiple variables in catch blocks 

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/cockpit#14682]
Cockpit version: 215
OS:

**when using Cockpit.spawn api, the catch seems to be returning 2 parameters** 
for example:**
```js
cockpit.spawn(["/opt/aeroscout/engine/run/aeroscout-engine-wd","status"])
.then(data=>console.log("data " + data))
.catch((ex,data) => {    
    console.log(ex);   
 })
```
the problem,  this doesn't seem to be standard in JS promises. 
i'm trying gwt and elemental2 with JsInterop which can only accept one parameter 

i have a script which writes back to standard output even though it returns error code 1 
the problem is i can't get back the standard out message no matter what i do.

**Comment by martinpitt** [comment]
There is no information at all in this report. Please provide some details.

**Comment by emaayan** [comment]
i was in the middle of it, i started writing on my phone, but something made it suddenly post it , so i switched to desktop..

**Comment by emaayan** [comment]
> There is no information at all in this report. Please provide some details.

done.

**Comment by martinpitt** [comment]
Right, this is unfortunately a historical wart. You can access the second `data` argument by using the jQuery promise API:

```js
cockpit.spawn(["/opt/aeroscout/engine/run/aeroscout-engine-wd","status"])
.done(data=>console.log("data " + data))
.fail((ex,data) => {    
    console.log(ex);   
 })
```

This is indeed wrong in our [documentation](https://cockpit-project.org/guide/latest/cockpit-spawn.html) -- we shouldn't have converted that bit to then/catch.

Alternatively, if you expect the command to fail, you can also do something like `cockpit.script('blabla status || true')`, and handle errors yourself.

**Comment by martinpitt** [comment]
With the old jQuery API:
```js
cockpit.script("echo hello; echo err >&2; exit 0", {err: "message"})
  .done((data, message) => console.log("SUCCESS", JSON.stringify(data), "msg", JSON.stringify(message)))
  .fail((exc, data) => console.log("FAIL", JSON.stringify(exc), "data", JSON.stringify(data)))
```
With `exit 0` you get

    SUCCESS "hello\n" msg "err\n"

and with `exit 1` you get

    FAIL {"problem":null,"exit_status":1,"exit_signal":null,"message":"err"} data "hello\n"

With the standard Promise API:
```js
cockpit.script("echo hello; echo err >&2; exit 0", {err: "message"})
  .then((data, message) => console.log("SUCCESS", JSON.stringify(data), "msg", JSON.stringify(message)))
  .catch((exc, data) => console.log("FAIL", JSON.stringify(exc), "data", JSON.stringify(data)))
```

You get the same SUCCESS and FAIL messages, including the "data" argument.

So the documentation and API seem right after all, I marked my previous reply as hidden.

 If you somehow need to pass these results to third-party APIs which can only handle one result, and can't handle non-zero exit statuses, then use the `cockpit.script("failing --program || true")` workaround to ignore the exit code (or some more fine-grained shell script wrapper).
