### ISSUE TITLE
Locked encrypted filesystems are not included in the list of filesystems

### ISSUE THREAD

**Issue by RoyKas** [cockpit-project/cockpit#14697]
Cockpit version: 229
OS: Debian 10 (Buster)
Page: Storage

Encrypted filesystems are not listed when locked. Only after unlocking they are listed, as shown in below snapshots. To me this seems incorrect as the filesystems exist and the system is aware of them. There is also no other listing where locked encrypted filesystems, other then by browsing all attached disks/partitions to see if there is an encrypted locked file system.

Before unlocking:
![Cockpit - Storage - before unlocking](https://user-images.githubusercontent.com/26328039/95015559-dc1bf400-064d-11eb-98d8-ca7b978d6591.png)

After unlocking:
![Cockpit - Storage - after unlocking](https://user-images.githubusercontent.com/26328039/95015563-dfaf7b00-064d-11eb-8b3b-073ae615c714.png)

After mounting:
![Cockpit - Storage - after mounting](https://user-images.githubusercontent.com/26328039/95015567-e2aa6b80-064d-11eb-808e-2c211816dd99.png)

**Comment by mvollmer** [comment]
Good point. Technically, encryption and filesystem are two quite separate things. We want to combine them in the UI eventually (see #13192), and then a locked filesystem would be included in the "Filesystems" list on the overview page. But even without that, Cockpit should really list whatever is listed in /etc/crypttab but still locked.
