### ISSUE TITLE
running cockpit in wsl 2 

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/cockpit#14699]
hi.. is it possible to run cockpit under ubuntu running under wsl2? 
one restriction that i know of is that curretnly wsl2 doesn't support systemd which makes it a problem for cockpit

**Comment by marusak** [comment]
> curretnly wsl2 doesn't support systemd

that is no go then. See for example https://github.com/cockpit-project/cockpit/issues/14565#issuecomment-686903781 this comment.

**Comment by stormalf** [comment]
It's possible now to use cockpit under wsl2 with distrod : see for more information https://github.com/nullpo-head/wsl-distrod

**Comment by garrett** [comment]
systemd is now officially supported in WSL2: https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/

(Not sure if that means Cockpit will "just work" when systemd is enabled in this way, however. It'd be nice to know.)

**Comment by stormalf** [comment]
Hi @garrett, wow thanks! I'll try it soon!

**Comment by garrett** [comment]
@stormalf: Best of luck! Please let us know if you're successful (or not).

**Comment by stormalf** [comment]
Hi @garret, I tested the preview version of wsl2 with systemd and it's working fine now with cockpit, the network information is available! all are fine!
![image](https://user-images.githubusercontent.com/74871156/193195415-a6c774cd-d1fe-4e50-9eae-e77b411153ef.png)

 wsl --version
Version WSL : 0.68.2.0
Version du noyau : 5.15.62.1
Version WSLg : 1.0.44
Version MSRDC : 1.2.3401
Version direct3D : 1.606.4
Version de DXCore : 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
version Windows : 10.0.22622.601

**Comment by martinpitt** [comment]
This is positively surprising, great to hear!

**Comment by emaayan** [comment]
through this i learned that wsl2 has added systemd support, but it's only for windows 11 (for now) 
however does this mean you will now officially support cockpit on wsl?

**Comment by garrett** [comment]
Wow, awesome to see!

To _officially_ support it, I think we'd need to have it tested, have a suggested distribution (or distributions) to use, and instructions for installing.

I'm not sure if anyone on the team has a machine that can run Windows 11, and running it in a VM is a bit tricky. FWIW: https://github.com/quickemu-project/quickemu does have support for Windows 11, but it isn't integrated in our testing.

**Comment by emaayan** [comment]
> 

for my reason i would want to easily develop pages for it.

**Comment by garrett** [comment]
> i would want to easily develop pages for it

That's definitely a great reason! :+1:

**Comment by emaayan** [comment]
btw it's possible i might be wrong about the win 11 thing 
https://www.reddit.com/r/bashonubuntuonwindows/comments/xkalm3/wsl_now_has_built_in_systemd_support/ 
it would appear you could to it on windows 10 22h2  build which is due to be out soonish.

https://www.windowslatest.com/2022/09/26/microsoft-confirms-windows-10-october-2022-update-22h2/

yes a getting started that would definitely help, especially if it would include the configuration that allows editing your development pages  in windows, so you could use your favorite IDE out of the box. 

interllij already has launchers for wsl
