### ISSUE TITLE
Storage ListingTable onRowClick reacts to "mousedown", not "click"

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#14701]
When clicking on a row in the Filesystems table in the Storage page, navigation happens already on the mousedown event, not on a click event.

**Comment by KKoukiou** [comment]
These tables are PF4 tables and from the PF4 table component documentation indeed the event listener for selctable rows is the onMouseDown. https://www.patternfly.org/v4/components/table#row-click-handler

I will make sure to confirm this is the desired behavior and keep this open till then.

**Comment by redallen** [comment]
Looks like this was a hack added in #1227 for inline editing. @suomiy said [here](https://github.com/patternfly/patternfly-react/pull/1227/files#r262077139):

> inline edit needs input events. I can send back computedData which are a bit easier to consume and leave the decision logic on consumer. IMO this is the best what can be done. Does somebody have a better idea?

If inline-edit-extension works with changing the event we can convert it to `onClick`.

**Comment by KKoukiou** [comment]
Reported it upstream, do you want to track it here as well? https://github.com/patternfly/patternfly-react/issues/5085

**Comment by marusak** [comment]
PF issue being tracked in patternfly/patternfly-react#5085
