### ISSUE TITLE
Cannot access via domain name after upgrading to Fedora 33

### ISSUE THREAD

**Issue by Alion548** [cockpit-project/cockpit#14705]
Cockpit version: 229
OS:Linux fedora_33 5.8.13-300.fc33.x86_64

![image](https://user-images.githubusercontent.com/8340545/95284676-56888600-0891-11eb-83f5-b9f90607ce90.png)
The same configuration is normal in Fedora 32.

**Comment by osiu97** [comment]
I managed to get it working on Fedora 33. To be honest at least in my case it was my mistake in nginx config. It looked same as yours so maybe it will help. For me it was trailing slash in proxy_pass directive which isn't supposed to be there. Plain config taken from wiki seems to work perfect now.

**Comment by Alion548** [comment]
> 我设法得到它在 Fedora 33 上的工作。说实话， 至少就我而言， 这是我的错误， 在 nginx 配置。它看起来和你的一样， 所以也许会有所帮助。对我来说， 这是尾随斜proxy_pass指令， 这是不应该在那里。从维基取来的纯配置现在似乎很完美。
> 
> 编辑：我刚刚检查，这是我的问题之一。当 nginx 中的同一端口上运行多台服务器时，它实际上似乎不起作用。（也许与斯尼有关？我不认为这是 Fedora 33 相关的东西 （虽然我没有手段测试它别的东西）， 因为它工作正常时， 只有驾驶舱反向代理服务器运行在 nginx 上。您可以使用这样的配置来测试它
> 
> ```
> worker_processes 2;
> error_log /var/log/nginx/error.log;
> pid /run/nginx.pid;
> 
> # Load dynamic modules. See /usr/share/nginx/README.dynamic.
> include /usr/share/nginx/modules/*.conf;
> 
> events {
>     worker_connections 768;
> }
> 
> http {
>     log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
>                       '$status $body_bytes_sent "$http_referer" '
>                       '"$http_user_agent" "$http_x_forwarded_for"';
> 
>     access_log  /var/log/nginx/access.log  main;
> 
>     sendfile            on;
>     tcp_nopush          on;
>     tcp_nodelay         on;
>     keepalive_timeout   65;
>     types_hash_max_size 2048;
> 
>     include             /etc/nginx/mime.types;
>     default_type        application/octet-stream;
> 
>     # Load modular configuration files from the /etc/nginx/conf.d directory.
>     # See http://nginx.org/en/docs/ngx_core_module.html#include
>     # for more information.
> 
> server {
>     listen         80;
>     listen         443 ssl;
>     server_name    cockpit.domain.top;
>     ssl_certificate /etc/letsencrypt/live/cockpit.domain.top/fullchain.pem; # managed by Certbot
>     ssl_certificate_key /etc/letsencrypt/live/cockpit.domain.top/privkey.pem; # managed by Certbot
> 
>     location / {
>         # Required to proxy the connection to Cockpit
>         proxy_pass https://192.168.1.100:9090;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-Proto $scheme;
> 
>         # Required for web sockets to function
>         proxy_http_version 1.1;
>         proxy_buffering off;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
> 
>         # Pass ETag header from Cockpit to clients.
>         # See: https://github.com/cockpit-project/cockpit/issues/5239
>         gzip off;
>     }
> }
> }
> ```
> 
> 并运行它`nginx -g "daemon off;" -c /tmp/cockpit.conf`

Use your nginx configuration and get the same error.

**Comment by osiu97** [comment]
If you didn't have anything else running on nginx, then you should post your logs here `journalctl -f` for me it looked like this
```
cockpit-bridge[27435]: received invalid HTTP request headers
cockpit-bridge[27435]: 0:1: http://packages/shell/index.html: received truncated HTTP response
cockpit-ws[27362]: /shell/index.html: external channel failed: protocol-error
```
Also make sure you have your origins configured in /etc/cockpit/cockpit.conf.
Is your nginx running on the same server you're trying to proxy to?

**Comment by Alion548** [comment]
nginx and cockpit are on the same host
Have checked /etc/cockpit/cockpit.conf.

**Comment by mehmooda** [comment]
Not sure if related; But my connections which go through my nginx ingress normalises the headers to lowercase

    GET /control HTTP/1.1\r\n
    Host: [redacted]\r\n
    X-Request-ID: baffc0232f142f36142d06547a413f89\r\n
    X-Real-IP: [redacted]\r\n
    X-Forwarded-For: [redacted]\r\n
    X-Forwarded-Host: [redacted]\r\n
    X-Forwarded-Port: 443\r\n
    X-Forwarded-Proto: https\r\n
    X-Scheme: https\r\n
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0\r\n
    accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\r\n
    accept-language: en-US,en;q=0.5\r\n
    accept-encoding: gzip, deflate, br\r\n
    upgrade-insecure-requests: 1\r\n
    pragma: no-cache\r\n
    cache-control: no-cache\r\n
    cookie: cockpit=dj0yO2s9NGNhMDU4OGU1MDFkZDgzMWI5Yjc5ZDU1M2FkODlmN2M2OWE5ZmY3Y2UxZDZhYTIxNjU0ZTcwM2RjYjA1NTI1OQ==\r\n
    \r\n

And results in protocol-error; the direct connection uses Title-Case for all the headers.

**Comment by Alion548** [comment]
> If you didn't have anything else running on nginx, then you should post your logs here `journalctl -f` for me it looked like this
> 
> ```
> cockpit-bridge[27435]: received invalid HTTP request headers
> cockpit-bridge[27435]: 0:1: http://packages/shell/index.html: received truncated HTTP response
> cockpit-ws[27362]: /shell/index.html: external channel failed: protocol-error
> ```
> 
> Also make sure you have your origins configured in /etc/cockpit/cockpit.conf.
> Is your nginx running on the same server you're trying to proxy to?
> For me it is working now, but for some reason I had to give it access to exclusive port and disable HTTP/2 in nginx.

```shell
journalctl -f
10月 25 18:46:25 localhost cockpit-ws[11330]: cockpit-ws: Failed to open certificate file /run/cockpit/tls/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: No such file or directory
10月 25 18:46:25 localhost audit[14226]: USER_AUTH pid=14226 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:authentication grantors=pam_unix acct="root" exe="/usr/libexec/cockpit-session" hostname=? addr=? terminal=? res=success'
10月 25 18:46:25 localhost audit[14226]: USER_ACCT pid=14226 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:accounting grantors=pam_unix,pam_localuser acct="root" exe="/usr/libexec/cockpit-session" hostname=? addr=? terminal=? res=success'
10月 25 18:46:25 localhost audit[14226]: CRED_ACQ pid=14226 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_unix acct="root" exe="/usr/libexec/cockpit-session" hostname=? addr=? terminal=? res=success'
10月 25 18:46:25 localhost cockpit-session[14226]: pam_ssh_add: Identity added: /root/.ssh/id_rsa (root@localhost.localdomain)
10月 25 18:46:25 localhost systemd-logind[850]: [🡕] New session 21 of user root.
10月 25 18:46:25 localhost systemd[1]: Started Session 21 of user root.
10月 25 18:46:25 localhost cockpit-session[14226]: pam_unix(cockpit:session): session opened for user root(uid=0) by (uid=0)
10月 25 18:46:25 localhost audit[14226]: USER_START pid=14226 uid=0 auid=0 ses=21 msg='op=PAM:session_open grantors=pam_selinux,pam_loginuid,pam_selinux,pam_keyinit,pam_ssh_add,pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_umask,pam_lastlog acct="root" exe="/usr/libexec/cockpit-session" hostname=? addr=? terminal=? res=success'
10月 25 18:46:25 localhost audit[14226]: CRED_REFR pid=14226 uid=0 auid=0 ses=21 msg='op=PAM:setcred grantors=pam_unix acct="root" exe="/usr/libexec/cockpit-session" hostname=? addr=? terminal=? res=success'
10月 25 18:46:25 localhost cockpit-bridge[14231]: received invalid HTTP request headers
10月 25 18:46:25 localhost cockpit-bridge[14231]: 0:1: http://packages/shell/index.html: received truncated HTTP response
10月 25 18:46:25 localhost cockpit-ws[11330]: /shell/index.html: external channel failed: protocol-error
```
```shell
server {
	listen 443 ssl http2;

    # SSL
	ssl_certificate     /usr/etc/cert/fullchain.cer;
	ssl_certificate_key /usr/etc/cert/website.key;
    

	location / {
        # Required to proxy the connection to Cockpit
        proxy_pass https://127.0.0.1:9090/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Required for web sockets to function
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Pass ETag header from Cockpit to clients.
        # See: https://github.com/cockpit-project/cockpit/issues/5239
        gzip off;
    }
}
```

**Comment by nos1609** [comment]
Same her on ArchLinux right after update

**Comment by sriio** [comment]
Same problem also with version 230.

Temporary downgrade to version 228 to regain acces to my server.

**Comment by Alion548** [comment]
Suspect it's a problem with the 229 version of the shell functionality.
https://cockpit-project.org/blog/cockpit-229.html

**Comment by saivert** [comment]
The bad commit is: 462eda51dec9de4661d07ea275fd14f62372ff59
(ws: If injecting a <base> element, ensure non-gzipped content)

**Comment by Yoshi2889** [comment]
I doubt this is _the_ solution, but @saivert 's research got me thinking.

After adding the following line to my Nginx proxy config:
```
proxy_set_header Accept-Encoding identity;
```

The interface loads up fine again on my subdomain. `proxy_pass_header` doesn't seem to work.

**Comment by saivert** [comment]
What I find interesting is if I instead of commenting out that line change it to lowercase like so:
`json_object_set_string_member (heads, "accept-encoding", "identity");`

It also works.

Since https2 mandates all lowercase header names this must be investigated further. Either there is an issue with how nginx handles this or cockpit isn't understanding lowercase headers.

**Comment by runfalk** [comment]
I (also Fedora 33 Server, cockpit 234) have the same problem with the config on the wiki (https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-nginx) even without explicitly enabling `http2`.

Like others I used the `proxy_set_header Accept-Encoding identity;` fix. This is my final config in case anyone else has issues:

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name cockpit.domain.tld;

    include /etc/nginx/snippets/ssl-settings.conf;

    access_log /var/log/nginx/cockpit_access.log;
    error_log /var/log/nginx/cockpit_error.log;

    location / {
        # Required to proxy the connection to Cockpit
        proxy_pass https://127.0.0.1:9090;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Required because of a bug in Cockpit 229+
        # https://github.com/cockpit-project/cockpit/issues/14705
        proxy_set_header Accept-Encoding identity;

        # Required for web sockets to function
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Pass ETag header from Cockpit to clients.
        # See: https://github.com/cockpit-project/cockpit/issues/5239
        gzip off;
    }
}
```

**Comment by mehmooda** [comment]
Might be worth rechecking with cockpit 237. I wrote https://github.com/cockpit-project/cockpit/pull/15225 because I was getting protocol-error. It should be in stable in 7 days or run the following if you cant wait.

```
dnf install bodhi-client
mkdir cockpit-update
cd cockpit-update
bodhi updates download --updateid FEDORA-2021-0ad93a9b1e
dnf update *.rpm
```
