### ISSUE TITLE
warning: cockpit-ws: Failed to open certificate file /run/cockpit/tls/...: No such file or directory

### ISSUE THREAD

**Issue by RoyKas** [cockpit-project/cockpit#14704]
Cockpit version: 229
OS: Debian 10 (Buster)
Page: Any

This issue seems related to #13668. However, Cockpit is working fine. HTTPS is secured with a valid certificate.

But my syslog is filling-up with many of the below two lines:

>  cockpit-tls[8307]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
cockpit-ws[31121]: cockpit-ws: Failed to open certificate file /run/cockpit/tls/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: No such file or directory

Folder /run/cockpit/tls is empty.

I've also found the following lines, which may be related to the issue:

> systemd[1]: cockpit-wsinstance-https@e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.service: Main process exited, code=killed, status=15/TERM
cockpit-session: pam_ssh_add: Failed adding some keys

Cockpit sessions typically end in:

>  cockpit-bridge[31193]: g_log_remove_handler: assertion 'handler_id > 0' failed

Either, my Cockpit installation is not working as intended, or unnecessary warnings are generated.

**Comment by martinpitt** [comment]
>    cockpit-ws: Failed to open certificate file /run/cockpit/tls/...

Did you enable client certificate authentication on your system? I.e. anything in /etc/cockpit/cockpit.conf? I just did that, and I still cannot get that warning, though. I just checked the code, and it would only happen if your browser sends a client certificate for the cockpit page.

**Comment by RoyKas** [comment]
There is no /etc/cockpit/cockpit.conf

Only configuration change I've made to the Debian Backport version (currently 237-1~bpo10+1) was to put a valid certificate in /etc/cockpit/ws-certs.d

**Comment by martinpitt** [comment]
Nevermind, I'll fix that.

**Comment by avnav88** [comment]
curious if this has been figured out...i'm having a similar issue:

```
cockpit-ws[989808]: cockpit-ws: Failed to open certificate file /run/cockpit/tls/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

**Comment by martinpitt** [comment]
@avnav88 : What's your OS and cockpit version? This got fixed in Cockpit 240. If you have a newer version, please open a new issue. Thanks!

**Comment by Firetalker** [comment]
Hello, i know it's an old issue. Nonetheless i wanted to share my solution for the exact same problem. Edit the `cockpit.conf` under the path `/etc/cockpit` and enter your local host like that:


`[WebService]
AllowUnencrypted=true
Origins = https://cockpit.MY.Domain https://10.0.0.1:9090
ProtocolHeader = X-Forwarded-Proto
[Session]
IdleTimeout=10`

Save the config and restart with `sudo systemctl restart cockpit.service` and then you should be able to connect via localhost from within your LAN. The "Origins = https://cockpit.MY.Domain" is only needed if you want to access this service from the outside.

FYI: I am using Ubuntu 24.04.1 LTS
