### ISSUE TITLE
machines: Making tuning of VM properties more obvious (inline edit)

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#14729]
Currently, changing settings for VMs is "hidden" behind a link. We may want to consider changing the values to be adjusted behind an inline edit pattern.

https://www.patternfly.org/v4/components/inline-edit/design-guidelines — specifically "full page edit" style, but applied to a card level.

**Comment by skobyda** [comment]
You mean allowing ability to change values presented in "Overview" card of the machine?

**Comment by KKoukiou** [comment]
yes, that's what they mean. @andreasn or @garrett can we get a mockup or design advice on that? Should we use some edit icon, like this? 
![Screen Shot 2020-11-25 at 10 57 37](https://user-images.githubusercontent.com/14921356/100211949-0e8af480-2f0d-11eb-9370-3568b8d2c976.png)

**Comment by KKoukiou** [comment]
Ok - I think I would solve this like this (how we do in the overview page) if that's fine:

![Screen Shot 2020-11-25 at 16 02 41](https://user-images.githubusercontent.com/14921356/100244872-b87f7680-2f37-11eb-8fe3-53b4052322e9.png)

**Comment by garrett** [comment]
I was previously thinking about having the inline edit icon for the autoupdate in the Software Page, but went with an edit button and a modal after talking with Andreas and/or Simon (I don't remember; just remember talking about it).

We probably want to make everything in the card editable at once, and we don't want to shift the UI around (which is what would happen when doing widget replacement). I think these were the reasons we went with an edit everything → modal → save model versus inline → edit a thing → save,  repeat for each item model.

However, I think in the comment, I was originally talking about making it more discoverable. And since the editing currently happens in separate modals, perhaps we just nee to add little edit links.

If we can make editing inline not feel cumbersome and not shift the page layout, then I could be for inline editing. But if we can't, then the minimum would be to at least make things more obvious to edit.

Another alternative is to always use editable widgets. However, if they're not in a dialog, then the problem would be how to save them. Without a save or apply button, it would look like auto-safe, and we currently don't really use that pattern in Cockpit.

Sorry that this is currently a non-answer. :wink: 

---

Options:

1. Perhaps we want to re-think having all of the items in separate dialogs and have a combined dialog for editing machine hardware information.
2. Or just have edit buttons with ![edit icon](https://user-images.githubusercontent.com/10246/100263285-9c86cf80-2f4d-11eb-9f79-eeef5f29ee8b.png) after. (Simpler; we can do this in the interim, even if we do want to go the route of choice 1.)

**Comment by garrett** [comment]
Oh, I just saw your post, @KKoukiou. GitHub had a caching issue and I didn't see it until after I just posted mine. :shrug:

**Comment by garrett** [comment]
> I think I would solve this like this (how we do in the overview page) if that's fine

That works for me too! Thanks!
