### ISSUE TITLE
Documentation: coreos missing sshd re-config

### ISSUE THREAD

**Issue by daniel-wtd** [cockpit-project/cockpit#14732]
Cockpit version: 229
OS: fedora coreos
Page: https://cockpit-project.org/running#coreos

The documentation is not including the fact, that coreos defaults to "disabled ssh passwords", which must be enabled to use the webinterface.

Steps to reproduce

1. Follow the guide at https://cockpit-project.org/running#coreos
2. Try to login with any user
3. Login will not work: ` The server refused to authenticate '<user>' using password authentication, and no other supported authentication methods are available. `
4. The point 4 of the documentation also does not work and does not generate a systemd unit file

Editing the sshd config + restat of sshd is needed to allow cockpit logins.

**Comment by martinpitt** [comment]
The current [install instructions](https://cockpit-project.org/running#coreos) do include the password ssh step; I updated them a few months ago.
