### ISSUE TITLE
Accounts: Little or no hints what makes an acceptable password

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#14737]
Cockpit version: 229
OS: Fedora
Page: Accounts

We recently ran a bunch of usability tests (RHEL Top Tasks: Baseline Usability Testing of Cockpit - round 1) and one common issue we observed was that it was hard for many participants to create a user account with acceptable password.
There are usually some rules around what makes an acceptable password, but knowing these upfront is tricky. Does it need to be a certain length? Can it be a dictionary word? Etc, etc.
The only hint now is the little bar, but that apparently doesn't give enough feedback, and it's usually down to trial and error.

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit/issues/14730 one is dupe on another - I let you decide which one you will close ;)
