### ISSUE TITLE
software: Redesign software updates page

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#14749]
The Software Updates has been around for a while and has grown organically over time. Now, we're hitting some growing pains as we try to shoehorn in more features, but they're just not fitting cleanly.

Meanwhile, other parts of Cockpit have evolved their design language.

It's time for the Software Updates page to be redesigned.

**Comment by garrett** [comment]
### Goals

- Align with the more recently redesigned parts of Cockpit
- Make the current status clear
- Provide a place for actions that need taking
- Show a summary of automatic updates and make it clear how to update it
- Separate the sections

**Comment by garrett** [comment]
### Up to date

![software-updates-overview-updated](https://user-images.githubusercontent.com/10246/96012460-6af5f100-0e44-11eb-9898-1a505b4a127a.png)

### Updates are available

![software-updates-overview](https://user-images.githubusercontent.com/10246/96012465-6b8e8780-0e44-11eb-9cbc-e86c7fd55860.png)

**Comment by andreasn** [comment]
Where does the "tracer" messaging go on this page? In the status section? Somewhere else?

**Comment by garrett** [comment]
I didn't get around to adding it yet. I ran out of time and got sick. Sorry.

Tracer's messaging is _by default_ in the complete area of the screen in a normal update flow.

It only shows up in the status card when: 
1. it's deferred from the update flow (with an action like "ignore for now" or "skip")
2. run outside of an update process
