### ISSUE TITLE
motd / active.motd not updated after systemctl enable

### ISSUE THREAD

**Issue by daniel-wtd** [cockpit-project/cockpit#14757]
Cockpit version: 229
OS: Fedora 33 (pre-release)
Page: 

After enabling cockpit via `systemctl enable --now cockpit.socket` the motd is not properly updated.

Steps to reproduce

1. `dnf install -y cockpit`
2. `systemctl enable --now cockpit.socket`
3. `reboot`
4. motd states "Activate the web console with: systemctl enable --now cockpit.socket"

What I can see so far:

```
$ ls -la /etc/motd.d/cockpit
/etc/motd.d/cockpit -> /run/cockpit/motd

$ ls -la /etc/issue.d/cockpit.issue
/etc/issue.d/cockpit.issue -> /run/cockpit/motd

$ ls -la /run/cockpit/motd
/run/cockpit/motd -> /usr/share/cockpit/motd/inactive.motd
```

The problem is, that cockpit-motd.service updates /run/cockpit/active.motd, but it seems nothing is changing the symlink for /etc/issue.d/ || /etc/motd.d/ OR the script for cockpit-motd.service is updating the wrong file.

**Comment by KKoukiou** [comment]
Hmm interesting - it works here as expected:

```
[kkoukiou@sequioa cockpit]$ ls -la /run/cockpit/motd 
lrwxrwxrwx. 1 root root 11 Oct 19 14:09 /run/cockpit/motd -> active.motd
[kkoukiou@sequioa cockpit]$ systemctl stop cockpit.socket
[kkoukiou@sequioa cockpit]$ ls -la /run/cockpit/motd 
lrwxrwxrwx. 1 root root 37 Oct 19 15:23 /run/cockpit/motd -> /usr/share/cockpit/motd/inactive.motd
[kkoukiou@sequioa cockpit]$ systemctl enable --now cockpit.socket
Created symlink /etc/systemd/system/sockets.target.wants/cockpit.socket → /usr/lib/systemd/system/cockpit.socket.
[kkoukiou@sequioa cockpit]$ ls -la /run/cockpit/motd 
lrwxrwxrwx. 1 root root 11 Oct 19 15:24 /run/cockpit/motd -> active.motd
[kkoukiou@sequioa cockpit]$ ls -la /etc/issue.d/cockpit.issue
lrwxrwxrwx. 1 root root 17 Jul 22 15:43 /etc/issue.d/cockpit.issue -> /run/cockpit/motd
```

I guess you can verify that the ExecStartPost && ExecStopPost are really linking to the active.motd/inactive.motd accordingly. You can see it in `systemctl show cockpit.socket` output.

**Comment by daniel-wtd** [comment]
Hi,

this seems a bit more interesting. I have a couple of machines and sometimes it's working, sometimes not. It can even change after one/a couple of reboots. I will have a look and see, if I can find something related these days.

**Comment by daniel-wtd** [comment]
for the machines, which were not working I had to stop the socket and enable it. :+1: 

At least for now, I cannot reproduce it. Maybe it is/was related to something else/another/older version.

If this re-occurs and I can reproduce it, I will have a look and re-open the issue.

Thanks for your support! :+1:
