### ISSUE TITLE
machines: dropdown menu obscured, unusable

### ISSUE THREAD

**Issue by slokhorst** [cockpit-project/cockpit#14759]
Cockpit version: 230
OS: Arch Linux
Page: Machines
Browser: Chromium 86.0.4240.75

When clicking the 3 dots to the right of a virtual machine, the dropdown menu is obscured and not usable.

![image](https://user-images.githubusercontent.com/8083666/96220210-997ce480-0f88-11eb-8dc5-94819657e13c.png)

![image](https://user-images.githubusercontent.com/8083666/96220246-a8639700-0f88-11eb-8dd1-a70118b30a94.png)

**Comment by marusak** [comment]
Thanks for the report!
Very similar issue is being fixed in https://github.com/cockpit-project/cockpit/pull/14667 so I'll check there if they fix also this behavior with it.

**Comment by KKoukiou** [comment]
This is already fixed on master with https://github.com/cockpit-project/cockpit/blob/master/pkg/machines/components/vm/vmExpandedContent.scss#L3

**Comment by marusak** [comment]
Great, so it will be fixed in cockpit 231 in two weeks. Thanks @KKoukiou for the reference :)
