### ISSUE TITLE
socket listening on ipv6 by default?

### ISSUE THREAD

**Issue by eisengrau** [cockpit-project/cockpit#14755]
Hello,

I just installed cockpit on an ubuntu 20.04 host (minimal install, no ufw, firewall, etc.), and it seems like it is listening on port 9090 only on tcp6 and nowhere else according to netstat:

> root@brownbear:/etc/systemd/system/cockpit.socket.d# netstat -tulnp | grep 9090
> tcp6       0      0 :::9090                 :::*                    LISTEN      1/init
> root@brownbear:/etc/systemd/system/cockpit.socket.d#

I did edit the file /etc/systemd/system/cockpit.socket.d/listen.conf and configured a different port, but it still listens on ipv6. Is it possible to enable ipv4 as well?

**Comment by zdzichu** [comment]
IPv6 sockets handle legacy IPv4 connections, too.

**Comment by marusak** [comment]
> IPv6 sockets handle legacy IPv4 connections, too.

yeah. I also have only tcp6 in `netstat -tulnp | grep 9090` but always used cockpit with ipv4 and never had any issue. Isn't ipv4 working for you @eisengrau ?

**Comment by eisengrau** [comment]
I'm so sorry. I had a temporary brain fart moment, or a n00b moment. iptables rules blocked any access from inside, even though ufw and firewalls were inactive on this host. Working now, thank you!
