### ISSUE TITLE
Ubuntu 20.04 netplan feature means network devices can't be changed

### ISSUE THREAD

**Issue by Dweller** [cockpit-project/cockpit#14766]
Page: Enhancement request for netplan support in networking control and editing

It would appear that in ubuntu 20.04 the netplan feature effectively disables the networkmanger operations within the cockpit networking menu.    It would be preferred that netplan was supported by cockpit.

**Comment by martinpitt** [comment]
I agree that would be "nice", but that would require a lot of work to parse, understand, and write the netplan syntax. I think that should rather be a separate "cockpit-netplan" project that goes in parallel with cockpit-networkmanager. Our team does not have the capacity (nor strategic interest) to do that. To work around this, you can switch netplan to use NM for all devices.
