### ISSUE TITLE
Is Ubuntu supported?

### ISSUE THREAD

**Issue by ElRoberto538** [cockpit-project/cockpit#14762]
Cockpit version: 215 (latest on ubuntu)
OS: Ubutunu 20.04

Should I be trying to use cockpit on Ubuntu? It is listed as supported, tested, and included but it doesn't work;

On a fresh install it will only login randomly and once it does login it is very slow with frequent errors causing logout (self signed cert issue?). 
Software updates (and a few other features) don't work due to Ubuntu changing to systemd-networkd (with the fix being to change back to the old network-manager.service). 
Containers don't work as the docker package is gone without a replacement.

**Comment by systemmonkey42** [comment]
Cockpit on Ubuntu is available in the "universe" repository.  Its a little behind the current release (currenty 227 compared to the website suggesting 230 is the latest)

Unfortunately, it has so many dependencies, it literally creates work for itself to manage...

> # apt-get install cockpit
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> The following package was automatically installed and is no longer required:
>   amd64-microcode
> Use 'apt autoremove' to remove it.
> The following additional packages will be installed:
>   cockpit-bridge cockpit-dashboard cockpit-networkmanager cockpit-packagekit cockpit-storaged cockpit-system
>   cockpit-ws cracklib-runtime eject finalrd gdisk libatasmart4 libblockdev-crypto2 libblockdev-fs2
>   libblockdev-loop2 libblockdev-mdraid2 libblockdev-part-err2 libblockdev-part2 libblockdev-swap2
>   libblockdev-utils2 libblockdev2 libbluetooth3 libbytesize1 libcrack2 libgudev-1.0-0 libjson-glib-1.0-0
>   libjson-glib-1.0-common libmbim-glib4 libmbim-proxy libmm-glib0 libnm0 libnspr4 libnss3 libntfs-3g883
>   libparted-fs-resize0 libpcsclite1 libpwquality-common libpwquality-tools libpwquality1 libqmi-glib5
>   libqmi-proxy libteamdctl0 libudisks2-0 libusb-1.0-0 libvolume-key1 mdadm modemmanager network-manager
>   network-manager-pptp ntfs-3g ppp pptp-linux udisks2 usb-modeswitch usb-modeswitch-data wamerican
>   wpasupplicant
> Suggested packages:
>   cockpit-doc cockpit-pcp cockpit-machines xdg-utils sssd-dbus cdtool setcd libparted-dev pcscd default-mta
>   | mail-transport-agent dracut-core avahi-autoipd libteam-utils exfat-utils f2fs-tools nilfs-tools
>   reiserfsprogs xfsprogs udftools udisks2-bcache udisks2-btrfs udisks2-lvm2 udisks2-vdo udisks2-zram comgt
>   wvdial wpagui libengine-pkcs11-openssl
> The following NEW packages will be installed:
>   cockpit cockpit-bridge cockpit-dashboard cockpit-networkmanager cockpit-packagekit cockpit-storaged
>   cockpit-system cockpit-ws cracklib-runtime eject finalrd gdisk libatasmart4 libblockdev-crypto2
>   libblockdev-fs2 libblockdev-loop2 libblockdev-mdraid2 libblockdev-part-err2 libblockdev-part2
>   libblockdev-swap2 libblockdev-utils2 libblockdev2 libbluetooth3 libbytesize1 libcrack2 libgudev-1.0-0
>   libjson-glib-1.0-0 libjson-glib-1.0-common libmbim-glib4 libmbim-proxy libmm-glib0 libnm0 libnspr4 libnss3
>   libntfs-3g883 libparted-fs-resize0 libpcsclite1 libpwquality-common libpwquality-tools libpwquality1
>   libqmi-glib5 libqmi-proxy libteamdctl0 libudisks2-0 libusb-1.0-0 libvolume-key1 mdadm modemmanager
>   network-manager network-manager-pptp ntfs-3g ppp pptp-linux udisks2 usb-modeswitch usb-modeswitch-data
>   wamerican wpasupplicant
> 0 upgraded, 58 newly installed, 0 to remove and 16 not upgraded.
> Need to get 14.6 MB of archives.
> After this operation, 44.0 MB of additional disk space will be used.


I am currently avoiding the package solution, looking for a way to install a thinner Cockpit instance which only manages what I have already installed..

Any ideas?

**Comment by marusak** [comment]
> On a fresh install it will only login randomly and once it does login it is very slow with frequent errors causing logout (self signed cert issue?).

For this we need more info unfortunately. Do you see something related in journalctl?

> Software updates (and a few other features) don't work due to Ubuntu changing to systemd-networkd (with the fix being to change back to the old network-manager.service).

https://github.com/cockpit-project/cockpit/issues/7987

> Containers don't work as the docker package is gone without a replacement.

https://github.com/cockpit-project/cockpit-podman/issues/481#issuecomment-720337505

> I especially take offence to the whole network manager dependency ... looking for a way to install a thinner Cockpit instance

Just `cockpit-networkmanager` depend on this. There is bunch of cockpit packages. `cockpit` is meta package which suggests and recommends other sub packages, but you can avoid those and just install packages, that you actually want.

**Comment by ElRoberto538** [comment]
Hi @marusak, thanks for the reply, unfortunately I kind of gave up as I couldn't get anything running, as described, so I deleted the VM it was on. Your links seem to solve my docker issue, which was the real showstopper for me once I got it logging in consistently, so I think it's OK to close this issue. I'll keep an eye on #7987 for my networking issue.
