### ISSUE TITLE
Question; why am i getting Failed to get properties: Unit name cockpit-wsinstance-https@.socket is neither a valid invocation ID nor unit name

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/cockpit#14773]
Cockpit version: 215
OS: ubuntu 18.04.1 LTS

when starting or stopping a DIFFERENT initd service (for example, service <name> stop) i get the following error:
Failed to get properties: Unit name cockpit-wsinstance-https@.socket is neither a valid invocation ID nor unit nam

<!---
Please help us out by explaining how to reproduce it.

Relevant parts of the system log are also useful:

`journalctl -u cockpit -u <unit>` if you know which unit it concerns
Jul 02 17:20:47 aeroscout-Virtual-Machine systemd[1]: Starting Cockpit Web Service...
Jul 02 17:20:47 aeroscout-Virtual-Machine remotectl[15140]: Generating temporary certificate using: sscg --quiet --li
Jul 02 17:20:47 aeroscout-Virtual-Machine remotectl[15140]: Error generating temporary dummy cert using sscg, falling
Jul 02 17:20:47 aeroscout-Virtual-Machine remotectl[15140]: Generating temporary certificate using: openssl req -x509
Jul 02 17:20:47 aeroscout-Virtual-Machine systemd[1]: Started Cockpit Web Service.
Jul 02 17:20:47 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert
Jul 02 17:20:47 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert
Jul 02 17:20:47 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert
Jul 02 17:20:50 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert
Jul 02 17:20:50 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert
Jul 02 17:20:50 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert
Jul 02 17:20:50 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert
Jul 02 17:20:50 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert
Jul 02 17:20:55 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert
Jul 02 17:20:55 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert
Jul 02 17:20:55 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert
Jul 02 17:20:55 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert
Jul 02 17:20:55 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert
Jul 02 17:20:55 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert
Jul 02 17:20:55 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert
Jul 02 17:20:55 aeroscout-Virtual-Machine cockpit-tls[15143]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert

cockpit seems to be running fine

**Comment by marusak** [comment]
Can you please post exact commands you do and exact errors?

**Comment by emaayan** [comment]
the exact errors are Failed to get properties: Unit name cockpit-wsinstance-https@.socket is neither a valid invocation ID nor unit nam
those happen when doing for example sudo service rsync stop, but it could happen for any service...

**Comment by MextroNL** [comment]
Have the same problem with every service I try start/stop
`Failed to get properties: Unit name cockpit-wsinstance-https@.socket is neither a valid invocation ID nor unit name.`

**Comment by KKoukiou** [comment]
Because you ;re using the template name in your command. See https://fedoramagazine.org/systemd-template-unit-files/ 

So there is no socket called, cockpit-wsinstance-https@.socket

After the @ there should be an index, a number.

**Comment by valtandor** [comment]
Hi @KKoukiou,

Apologies for bumping an old thread, but perhaps you could clarify what you mean.

If I run the following command(s):

```
$ sudo service dnsmasq stop && sudo service dnsmasq start
```
I get the same result @MextroNL complained of, viz.:

```
Failed to get properties: Unit name cockpit-wsinstance-https@.socket is neither a valid invocation ID nor unit name.
Failed to get properties: Unit name cockpit-wsinstance-https@.socket is neither a valid invocation ID nor unit name.
```

I don't see in what sense I'm using the template name in my command. I have tried grepping the files in `/lib/systemd/system` and they don't say that `cockpit-wsinstance-https@.socket` is being called anywhere.

I am trying to run a grep on every file in the system, as time-consuming as that is, and the only file I've found that matches so far is the binary file `/proc/kcore`, which I'm sure is not the source of the problem.

I also renamed the file `/lib/systemd/system/cockpit-wsinstance-https@.socket` to `/lib/systemd/system/cockpit-wsinstance-https.socket` on the understanding that socket units aren't supposed to have individual instances and observing that no other socket unit in `/lib/systemd/system` has the `@` decoration.

Further, having done the rename, I rebooted, ran `sudo systemctl daemon-reload` in case the call to `cockpit-wsinstance-https@.socket` was cached somewhere, and rebooted again. None of these things have helped dispel the message quoted above.

**Comment by KKoukiou** [comment]
I obviously misread the issue, reopening for further checking.

**Comment by martinpitt** [comment]
That's right -- This systemd unit is a template, it has to be instantiated with a particular name. Also, these are internally managed by cockpit.service, a user is not meant to start them directly (I mean, you can, but that doesn't do anything useful). SysV tools have no concept of template units, and cockpit doesn't work without systemd, so trying to run these with `service` is not going to work.

**Comment by valtandor** [comment]
@martinpitt Right, that makes sense.

I will therefore post this here in case it helps someone else:

Instead of running

```
sudo service foo stop
```

or 

```
sudo service foo start
```

One should run, respectively:

```
sudo systemctl stop foo.service
```

```
sudo systemctl start foo.service
```

This will make the problem go away as the service is being invoked correctly (for `systemd`).

Please feel free to correct me if I have misunderstood, but when I tried this it worked for me and didn't give me the annoying error. (Ubuntu 18.04 LTS)

**Comment by martinpitt** [comment]
@valtandor : Not quite -- `service cockpit stop` should actually work, and that's a unit (`cockpit.service`) which is at least "visible" to a user (the top-level unit is `cockpit.socket`, which dynamically activates `cockpit.service` on the first request).

What does not work is to try and stop/start `cockpit-wsinstance-https@`, regardless of whether you use `service` or `systemctl`.

**Comment by valtandor** [comment]
@martinpitt Sure, however I and (I assume) others such as @emaayan and @MextroNL were trying to stop and start arbitrary services (not sockets, mind you), with at least in my case no clear connection between the services I was issuing commands to and either `cockpit[...].service` or `cockpit[...].socket`. For instance I got the message when trying to stop and start `dnsmasq` and `lightdm` using `service`.

I don't know why a command such as `sudo service dnsmasq stop` would attempt to manage `cockpit-wsinstance-https@.socket`, but if replacing `sudo service ARGS` with `sudo systemctl ARGS` dispels the message, I'm content.

**Comment by emaayan** [comment]
what i originally meant is that when i tried for example to stop and start my own application which uses init.d but not related to cockpit i get this error. 
(i mean it does have it's own web part that's also in cockpit panel, but i've seen other services cause that too)

**Comment by martinpitt** [comment]
@emaayan : Oh! You meant that doing `service dnsmasq stop` you get that complaint about cockpit-wsinstance-https@, I see. Sorry that I misunderstood that first! That is clearly a bug in the `service` script, it shouldn't even attempt to look at units other than the specified one.
