### ISSUE TITLE
search images dialog improvement suggestions

### ISSUE THREAD

**Issue by abonas** [cockpit-project/cockpit#1477]
search images dialog improvement suggestions:
1. Its title is "search image" - is this proper English? Shouldn't it be "search for image"? 
2. there's a lot of "dead space" in the dialog - all the white space under "search image".
3. it's not clear where is this search searching for images - some repo? local? remote?
4. tag field seems disabled - what can user do with it?

![searchimage](https://cloud.githubusercontent.com/assets/6277245/5013031/5dcea950-6a93-11e4-9e06-12f2e8b0b7fc.png)

**Comment by stefwalter** [comment]
Very good observations. Splitting out the typo fix, as a starter task for someone.

**Comment by bee2502** [comment]
I am working on a fix for this issue.

**Comment by bee2502** [comment]
This issue is still open and unfixed for anyone willing to take it up.

**Comment by a2batic** [comment]
@abonas @andreasn @stefwalter @dperpeet , I would like to work on this issue

**Comment by andreasn** [comment]
@a2batic sounds good!
You can post a mockup that addresses abonas concerns here in the issue.

**Comment by martinpitt** [comment]
Supposedly this is about docker images. Our docker UI is on maintenance mode, and improvements should go to cockpit-podman.
