### ISSUE TITLE
Once you switch the locale to Chinese (simplified), there's no going back for dashboards connected to main server

### ISSUE THREAD

**Issue by eh8** [cockpit-project/cockpit#14788]
Cockpit version: 230
OS: Arch Linux
Page:  everywhere

Steps to reproduce

1. Upper right hand account picture -> 'Display language' -> '中文 （中国）'
2. Upper right hand account picture -> 'Display language' -> 'English'
3. The non-main server dashboards remain in Chinese

Note: this is active as of Firefox 82. I used the most recent builds of Chrome and Opera and found the same results. I cleared my cache and cookies; didn't solve. If I access each server directly (not via my host) then the locale switching is fine.

I even tried to reinstall all instances of `cockpit` on my machines, being sure to purge `/etc/` from any remnants of configuration files. Still the issue persists.

I would love if there was some kind of workaround available to force a locale change for now. Happy to provide any documentation necessary to exterminate this very annoying bug (my family is asking me why I switched my dashboards to Chinese)

![Demo](https://user-images.githubusercontent.com/22990581/96964576-b6f60500-14d8-11eb-80f6-edf43ebe1cb3.gif)

**Comment by marusak** [comment]
Interesting. I've played with this around and cannot reproduce.
Is your computer language set to Chinese?
Can you try to change to some other language (some random, no English or Chinese). Does it change the language on both machines? Can you change it then back to Chinese? Or Can you then change it to English?

Also can you please check for me your browser  storage? It is where we store this info. You can also right-click delete it (that is workaround).
![storage](https://user-images.githubusercontent.com/12330670/96968568-6fd83600-1511-11eb-92f9-0105ce95fa5a.png)

**Comment by eh8** [comment]
No, the only locale on my computer is English (US).

![image](https://user-images.githubusercontent.com/22990581/96969340-5965b680-14e0-11eb-9b64-928718ec1992.png)

![image](https://user-images.githubusercontent.com/22990581/96969422-80bc8380-14e0-11eb-82d1-0d8aec9beb3f.png)

Issue remains after deleting the cookie you depicted. I can use a completely separate browser that has never accessed or cached this content before i.e. `epiphany` and it unfortunately persists.

**Comment by eh8** [comment]
Switching to another language is non-functional (tried with German, Polish, Dutch) no matter if toggling from host-side or not.

**Comment by marusak** [comment]
hmm, this is weird. The shell (menu on the top and the left) is being updated correctly it seems, just the content is not.  Was the remote host ever in English or it was always in Chinese?
Can you also please check versions of all cockpit packages on both hosts?
And could you please tests one more thing for me? Can you go to 'Terminal' page, change color to something different and check how that behaves on local and remote host? (It stores the information about your preference the same way that language is stored).

**Comment by eh8** [comment]
Everything was originally in English until a few days ago when I began fiddling with the Chinese translations.

All hosts are running version 230-1.

**English host**

![image](https://user-images.githubusercontent.com/22990581/96975620-af3e5c80-14e8-11eb-87f2-89adea2df506.png)

**'Chinese' host**

![image](https://user-images.githubusercontent.com/22990581/96975715-d5fc9300-14e8-11eb-92d6-f603b6aba0fe.png)

Looks like the cookies propagate as intended.

**Comment by eh8** [comment]
As I write to this bug report, I'm also working on some PAM stuff for cockpit and keep restarting the socket.

Suddenly, everything is back in English when I logged back in to take the terminal screenshots. Nice!

But I still cannot verify the behavior has been completely removed yet (I still can't switch any host to another language, now it looks like it's stuck to English. But I'm far happier with that than the alternative :))

**Comment by martinpitt** [comment]
I also just tried that with cockpit 238 and firefox 85, and I am unable to reproduce. BTW, to avoid side effects from stale cookies etc, it often helps to try to do this in a private browser window.

**Comment by WhymustIhaveaname** [comment]
I also suffer from this bug. I am using Ubuntu 20 with Cockpit version 215. My only system language is English,
```
username@hostname:~$ echo $LANG
en_US.UTF-8
```
I do not know how Cockpit knows I am Chinese. It shows in Chinese since I installed it. However, the language showed in the setting is English in the mean while. Changing the language into Chinese/Deutsch forth and back takes no effect.

BTW, the Chinese translation of Cockpit is full of mistakes. One cannot rely on auto-translation for a language as complex as Chinese so far.

![Screenshot from 2021-04-29 09-21-02](https://user-images.githubusercontent.com/38423345/116491411-5eab2000-a8cc-11eb-8d31-32dc37b2c9c6.png)

**Comment by martinpitt** [comment]
@WhymustIhaveaname :
> I do not know how Cockpit knows I am Chinese. 

Either you specified something in Cockpit's language dialog -- this is stored in a cookie, and you might clean up the cookie/site data for cockpit to reset it, or open it in a private browser window. If that does not exist, it looks at the preferred languages that the browser sends. So probably you have Chinese in there somewhere?

I tried both Cockpit 215 (the version from Ubuntu 20.04 LTS at release time) as well as the latest available backport 252 (`apt install -t focal-backports cockpit`). Using current Firefox 93 just works. Chromium 93 is still affected by the ages-old language change issue #8160, but it also works after a forced page reload (Ctrl+Shift+F).

**Comment by WhymustIhaveaname** [comment]
Thank you for your explanation!

I have not used cockpit for quite a while. And when today I opened it, it is now English!

BTW, do you know where can I give advice on cockpit's translation?

**Comment by marusak** [comment]
> BTW, do you know where can I give advice on cockpit's translation?

What kind of advice? If something is wrongly translated or not translated, then [weblate](https://translate.fedoraproject.org/projects/cockpit/main/) would be the right place. You can directly fix it there or suggest fix (I advice not to suggest as I have no idea if there is someone checking these for any given language).
If it is something else, then opening issue here would do. Thanks!
