### ISSUE TITLE
Missing UI translation strings (for Turkish)

### ISSUE THREAD

**Issue by BouRock** [cockpit-project/cockpit#14780]
I noticed there are one or two strings which are missing. And one string is still in English.

- In "Add new host" dialog, "Specify the host and the login user account for the host that you want to add.
For the host, either specify the hostname, IP address, an alias name or a unique resource identifier for the SSH destination." strings are missing to translate in Weblate.

- "Software Updates" is in English in navigation pane although the translation exists in Weblate

![addnewhost](https://user-images.githubusercontent.com/11577799/96577726-babd3800-12dc-11eb-9a7d-632365481f00.png)

![softupd](https://user-images.githubusercontent.com/11577799/96577688-a5480e00-12dc-11eb-83bf-3676e90af330.png)

**Comment by BouRock** [comment]
Well, congrat :) you have understand screenshots are Turkish but this issue is not only for Turkish. It is same in all languages.

**Comment by marusak** [comment]
> In "Add new host" dialog, "Specify the host and ...

Fixed, it is now there. Weblate did not rebase, not sure why. I'll keep an eye on.

> "Software Updates" is in English in navigation pane although the translation exists in Weblate

It has been translated 9th of October so it is only in cockpit 230. Are you using this version?
![trabslkated](https://user-images.githubusercontent.com/12330670/96714763-ec98d200-13a2-11eb-85a9-863064163dcf.png)

**Comment by BouRock** [comment]
Interesting. Yes, it was translated 3 weeks ago. But your screenshot is OK. Mine is also 230. Here it is:


![cockpitmain](https://user-images.githubusercontent.com/11577799/96721726-38547700-13b5-11eb-8969-c2a30a987f2b.png)

**Comment by marusak** [comment]
Can you list all cockpit packages that you have? on rpm-based distros it would be `rpm -qa | grep cockpit`.

**Comment by BouRock** [comment]
I want to. But I am not sure how can I do, I have not much information on command line.

**Comment by BouRock** [comment]
Also these are still in English

![cockpitserv](https://user-images.githubusercontent.com/11577799/96725728-dcd8b800-13b9-11eb-933d-58847d5ffdac.png)

**Comment by marusak** [comment]
> I want to. But I am not sure how can I do, I have not much information on command line.

What OS are you using?

**Comment by BouRock** [comment]
This is Freedombox image. Debian GNU/Linux bullseye/sid. Debian 10

Operating System: Debian GNU/Linux bullseye/sid
Kernel: Linux 5.8.0-3-amd64
Architecture: x86-64

**Comment by marusak** [comment]
`apt list --installed | grep cockpit`

**Comment by BouRock** [comment]
cockpit-bridge/testing,now 230-1 amd64 [installed,automatic]
cockpit-networkmanager/testing,now 230-1 all [installed,automatic]
cockpit-packagekit/testing,now 230-1 all [installed,automatic]
cockpit-pcp/testing,now 230-1 amd64 [installed]
cockpit-storaged/testing,now 230-1 all [installed,automatic]
cockpit-system/testing,now 230-1 all [installed,automatic]
cockpit-ws/testing,now 230-1 amd64 [installed,automatic]
cockpit/testing,now 230-1 all [installed]

**Comment by BouRock** [comment]
In Network->Firewall->Add zone, trust levels and its descriptions are missing for translation

![addzone](https://user-images.githubusercontent.com/11577799/97361892-47559080-18b1-11eb-910b-6139cd9eb959.png)

**Comment by marusak** [comment]
So today I stopped convincing myself it was just bad timing and looked into this and it is indeed broken.
Will send fix in a bit.
![tr2](https://user-images.githubusercontent.com/12330670/98356983-c6229a00-2024-11eb-863d-5bc49884b247.png)
![tr1](https://user-images.githubusercontent.com/12330670/98356989-c6bb3080-2024-11eb-8303-e9278ddcbdb7.png)
![tr3](https://user-images.githubusercontent.com/12330670/98357571-b22b6800-2025-11eb-89c1-c52e2a8221b3.png)

Thank you for reporting those!

> In Network->Firewall->Add zone, trust levels and its descriptions are missing for translation

When I stare into our code, it seems that these names come from API. However, we define their IDs manually, so I find it a bit weird that we then ask API for names. @Gundersanne Can you enlighten us about this?

**Comment by Gundersanne** [comment]
So the IDs of the zones are hardcoded because you can't really query them via the DBus api, but they are stable, see: https://firewalld.org/documentation/man-pages/firewalld.zones.html under "Which zones are available?".

The descriptions however do come from the DBus api, as do the colloquial names. Sadly I don't see an easy way to translate those :/
