### ISSUE TITLE
Requesting OTP/2FA only when connecting outside of local network

### ISSUE THREAD

**Issue by eh8** [cockpit-project/cockpit#14791]
Page:  login

Given that `cockpit` relies upon PAM for authentication, it would nice if users can employ the current method of enforcing 2-factor authentication based on whether or not they are on a local, secure network.

**`/etc/pam.d/cockpit`**

```
#%PAM-1.0
#auth     required  pam_securetty.so     #disable remote root
auth [success=1 default=ignore] pam_access.so accessfile=/etc/security/access-local.conf
auth      required  pam_google_authenticator.so
auth      include   system-remote-login
account   include   system-remote-login
password  include   system-remote-login
session   include   system-remote-login
```

**`/etc/security/access-local.conf`**
```
# only allow from local IP range
+ : ALL : 192.168.0.0/24
+ : ALL : LOCAL
# denies other incoming requests from skipping 2fa
- : ALL : ALL
```

Currently, using `auth [success=1 default=ignore] pam_access.so accessfile=/etc/security/access-local.conf` is obsolete as `cockpit` directly admits users if they are able to provide a correct user/password.

**Comment by martinpitt** [comment]
Sorry for the very late response, this fell through the cracks. I don't understand the request -- of course you are free to configure the PAM file as you like. What isn't working with that setup above?

I don't understand the "obsolete" part -- did you mean cockpit still asks for a password despite your pam_access rule already allowing access? Perhaps you meant "sufficient" insted of "required"?

**Comment by eh8** [comment]
To clarify, the above `/etc/security/access-local.conf` configuration didn't work, and during testing I was able to log in once I provided my username and password, bypassing 2FA.

**Comment by martinpitt** [comment]
"bypassing 2FA" means that you did *not* get asked for 2FA? Isn't that exactly what you asked for with `success=1`?

**Comment by eh8** [comment]
`success=1` should skip the 2fa module if the connecting client has a IP address within the specified subnet in `/etc/security/access-local.conf`

If I recall correctly, I was using this [StackExchange thread ](https://unix.stackexchange.com/questions/388384/ssh-only-require-google-authenticator-from-outside-local-network) two years ago when I was researching this topic

**Comment by martinpitt** [comment]
Since commit ad7b2def408bbe4a00fd82ec5399db79b446c91e in Cockpit version 231 we set `PAM_RHOST` again. This was fixed three days after your report (what a coincidence). What is your current cockpit version? Does that still happen? If so, please add `debug` to your `pam_access` entry and check that it actually gets the right IP, and what it does exactly there.

**Comment by martinpitt** [comment]
Stale and most likely fixed. If not, please yell and we'll reopen and continue to debug (see previous comment for necessary information).
