### ISSUE TITLE
Menu on networking page is hidden

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#14793]
On networking details page when clicking on the + icon to add ports I cannot see the menu. (see down in ports, there is open menu)

![networking-ports](https://user-images.githubusercontent.com/12330670/97114314-1ed26880-16f0-11eb-8ac9-b02bb6801858.png)

@KKoukiou can you please take a look? (I think you know what is the problem as I think you were fixing something similar not so long ago on VMs page)

**Comment by ashishpatel1992** [comment]
@marusak it looks perfectly fine to me in Google Chrome 86.0.4240.75 
Please mention your browser name and version. The issue could be browser-specific.
![Screenshot from 2020-10-26 00-59-15](https://user-images.githubusercontent.com/652311/97116934-b5ba1780-1726-11eb-95f0-0866bc9ee074.png)

**Comment by marusak** [comment]
> It looks perfectly fine to me

What version of cockpit are you using? I am on the current master branch.

> Please mention your browser name and version.

firefox nightly 83.0a1 (2020-10-13) and chromium  85.0.4183.121 are both affected.

>  The issue could be browser-specific.

I think it is just a very recent change. There are a lot of moving parts around these things recently.
