### ISSUE TITLE
Provide link to logs page on events

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#14808]
If event happened let's say at 2:32, we could provide line to logs page where we would show logs from 2:31 to 2:37 or so with the priority 'Debug and above'. We have `since` quantifier and we have PR for `until` one in #14468 so we should be able to do this.

Copied from https://github.com/martinpitt/performance-graphs/issues/80

**Comment by martinpitt** [comment]
Tracked with design in #15303 now.
