### ISSUE TITLE
Better treat long mount points in Disks card

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#14805]
dd if=/dev/zero of=/tmp/img bs=1M count=50 && mkfs -t ext3 /tmp/img && mkdir -p /mnt/this/is/some/reeeeeally/loooooong/mount/path && mount -o loop /tmp/img /mnt/this/is/some/reeeeeally/loooooong/mount/path && rm -f /tmp/img

This doesn't actually look too bad right now:

![image](https://user-images.githubusercontent.com/200109/93311305-21df5c80-f806-11ea-88e8-b697a4d00d7a.png)

Not sure if we desperately want to clip it or so. We should surely shorten the free/total string, though.

Copied from https://github.com/martinpitt/performance-graphs/issues/42

**Comment by KKoukiou** [comment]
This is fine as is, I tried to truncate the title, using PF4's isTitleTruncated property. That truncates the string from the right, which is not desirable in this element. We can make it left truncated with custom CSS, but let's not overcomplicate it, it's just fine as is.
