### ISSUE TITLE
Consider show user session scopes in top-5 consumers

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#14806]
When you start a CPU/memory intense task in an interactive session, that process runs in a cgroup like `user.slice/user-1000.slice/session-2.scope`, not as part of any service. We should show the leaf scopes, but not their parents.

Copied from https://github.com/martinpitt/performance-graphs/issues/53

**Comment by martinpitt** [comment]
Current cockpit does that:

![image](https://user-images.githubusercontent.com/200109/176999286-af68d702-1953-4283-b9de-712af3eae9e8.png)
