### ISSUE TITLE
Option to turn off PCP

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#14803]
This page replaced the "enable pcp" button on Overview. The empty state provides the "on", but there is no "off" button.

Perhaps we could have a settings section like this? Where it's shoved under the shortest card on the right.

![metrics-config](https://user-images.githubusercontent.com/10246/92609170-90786380-f2b6-11ea-99f7-579c9dd1311b.png)

Since the toggle is probably too visible and too easy to turn off, we could have something like the CPU mitigations @ https://localhost:9090/system/hwinfo — where there's a settings link that brings up a dialog with a toggle and a confirmation button. (This would only be for disabling, as it would presumably disable the service _and_ remove packages.)

Copied from https://github.com/martinpitt/performance-graphs/issues/18

**Comment by martinpitt** [comment]
I don't quite like to squeeze it into the Network card:

 - This card row are the *current* metrics, and this switch refers to PCP (metrics history).
 - The network card does not have a fixed height, there can (and often are) many network interfaces.
 - There will be more PCP config for Grafana integration (PR #15810)

My current thought is to replace the "Install cockpit-pcp" and "Enable PCP metrics collector" buttons in the empty states:

![metrics-no-pcp-master](https://user-images.githubusercontent.com/200109/117935078-a5087200-b303-11eb-84ad-983db1154caa.png)

... with a new "PCP config" card:

![image](https://user-images.githubusercontent.com/200109/117934774-4cd17000-b303-11eb-9780-578f7e4bd144.png)

(This obviously has a lot of font/spacing/etc. issues, it's just a draft). This also simplifies the workflow: Enabling the switch would install cockpit-pcp (if necessary), and enable/start the service, there is no need any more to click *two* buttons.

Then the only case for an empty state would be if pmlogger.service failed (with the "Troubleshoot.." link), or runs but somehow does not collect data.

@garrett,  @marusak , WDYT?

**Comment by marusak** [comment]
I like how the separate card looks like, but it feels to prominent for actions that you probably want to do once.

> we could certainly also place the card below the graph

You mean under history graphs? I think none would ever find it there.

An idea that comes to my mind would be to have kebab menu somewhere and it would open pop-up containing this settings. Surely not super discoverable, but as I said, this is very much a corner case for someone who will be looking for it. We don't have ideal place for this menu as we don't have any heading (as for example on firewall page) but maybe on the right in the breadcrumb panel?
Or just introduce such heading and have there button like 'Configuration' which would open modal with these two options?

**Comment by martinpitt** [comment]
Some other ideas:
 - Make the card [expandable](https://www.patternfly.org/v4/components/card#expandable), and collapse it by default iff there are history metrics. This would IMHO give us the best of both worlds -- offer the options if PCP is off (as then we don't need the space for anything else), and get mostly out of the way and act as a heading if it's on.
 - Replace the card with a kebab menu inside the bar with  "[Today v]" and the graph headings if there is pcp data.

**Comment by garrett** [comment]
I like the empty state:

![metrics-no-pcp-master](https://user-images.githubusercontent.com/200109/117935078-a5087200-b303-11eb-84ad-983db1154caa.png)

But I don't like the card.

Can we have something in title area where the breadcrums are, but at the right of that area? We could have a configuration thing there on the right and it brings up a dialog that looks somewhat similar to the card's contents.

From https://www.patternfly.org/v4/guidelines/icons/#all-icons:
![Screenshot_2021-05-12 PatternFly 4 • Icons](https://user-images.githubusercontent.com/10246/117949744-bad16380-b312-11eb-8f66-cce6497afe4f.png)

The icon should be fa-cog / CogIcon and be called "Settings".

The icon alone (with a tooltip obviously) in that context would probably not be enough. We probably want to have it paired with the text. PF suggests "Settings" here, so perhaps we want to provide context and call it "Metrics settings", "Metric collection settings" or something similar. (Using "PCP" in the UI is a bad idea in most places, as it's also [a common drug name](https://www.drugs.com/illicit/pcp.html).)

**Comment by martinpitt** [comment]
@garrett : Note that the empty state with the button is the status quo (just to avoid confusion).

We could keep the empty state for enabling and the cog wheel for disabling (as that's not too common).

My main concern is then how to make pmproxy discoverable, i.e. exposing your metrics to other machines in the network (for Grafana). If the only way is through the cog, then it'll be hard to find. I'm certainly happy to start that way though, then we at least have the functionality and can iterate over how to expose it.

**Comment by garrett** [comment]
OK, let's step back a bit:

So the two checkboxes are odd.

When you have PCP disabled and share it, then... What happens? One depends on the other, right?

And there are really two tasks here that someone wants to do, correct?

1. Disable / uninstall or otherwise stop using PCP (for whatever reason)
2. Share the metrics from one host to another (somehow, regardless of implementation, whether it's push/pull, where it is, etc.)

For task # 1, it's really more of an action and probably really presentable in a toggle state, unless we're keeping PCP installed and just turning it off (and this is really not much different from going to services and disabling the pmlogger service).

For task # 2, it requires setting it up on the collection end. Just exposing the port isn't enough, and there's no guidance here whatsoever. (I guess what's represented here at the moment is similar to adding the service to the firewall?)

**Comment by martinpitt** [comment]
> When you have PCP disabled and share it, then... What happens? One depends on the other, right?

Yes, that makes no sense, this was just because I added this as a dummy draft.

The pmproxy stuff is PR #15812, and indeed there is a whole lot of stuff that needs to happen for that. I merely added this to the mockup to show that there eventually will be more than one option in the PCP settings. Perhaps even more in the future for the other components (e.g. pmcd or pmie).

**Comment by martinpitt** [comment]
I tried to add a cog wheel (or anything really) to the [Page](https://www.patternfly.org/v4/components/page) into the breadcumbs bar, and that doesn't seem to be that easy..
```diff
--- pkg/metrics/metrics.jsx
+++ pkg/metrics/metrics.jsx
@@ -1252,6 +1252,8 @@ class MetricsHistory extends React.Component {
 export const Application = () => (
     <Page groupProps={{ sticky: 'top' }}
           isBreadcrumbGrouped
+          isBreadcrumbWidthLimited
+          additionalGroupedContent={ <span>Hello</span> }
           breadcrumb={
               <Breadcrumb>
                   <BreadcrumbItem onClick={() => cockpit.jump("/system")} to="#">{_("Overview")}</BreadcrumbItem>
```
The additional group always goes to the next line, not to the right:

![image](https://user-images.githubusercontent.com/200109/117959296-27049500-b31c-11eb-9a26-9fb2f2337118.png)

I suppose we could do something like the kdump page and build that header ourselves with a `PageSection`. The bar is a little higher, but if we care that should not be too hard to tweak (or we just accept it and use the same bar as on kdump):

![image](https://user-images.githubusercontent.com/200109/117969468-ba8f9300-b327-11eb-8f39-aac5f1911bcd.png)

Code:
```diff
--- pkg/metrics/metrics.jsx
+++ pkg/metrics/metrics.jsx
@@ -27,7 +27,7 @@ import {
     Card, CardTitle, CardHeader, CardBody, Gallery,
     DescriptionList, DescriptionListGroup, DescriptionListTerm, DescriptionListDescription,
     Flex, FlexItem,
-    Page, PageSection,
+    Page, PageSection, PageSectionVariants,
     Progress, ProgressVariant,
     Select, SelectOption,
     Switch,
@@ -1250,14 +1250,20 @@ class MetricsHistory extends React.Component {
 }
 
 export const Application = () => (
-    <Page groupProps={{ sticky: 'top' }}
-          isBreadcrumbGrouped
-          breadcrumb={
-              <Breadcrumb>
-                  <BreadcrumbItem onClick={() => cockpit.jump("/system")} to="#">{_("Overview")}</BreadcrumbItem>
-                  <BreadcrumbItem isActive>{_("Performance Metrics")}</BreadcrumbItem>
-              </Breadcrumb>
-          }>
+    <Page>
+        <PageSection variant={PageSectionVariants.light}>
+            <Flex>
+                <FlexItem>
+                    <Breadcrumb>
+                        <BreadcrumbItem onClick={() => cockpit.jump("/system")} to="#">{_("Overview")}</BreadcrumbItem>
+                        <BreadcrumbItem isActive>{_("Performance Metrics")}</BreadcrumbItem>
+                    </Breadcrumb>
+                </FlexItem>
+                <FlexItem align={{ default: 'alignRight' }}>
+                    <Button>Hello</Button>
+                </FlexItem>
+            </Flex>
+        </PageSection>
         <PageSection>
             <CurrentMetrics />
         </PageSection>
```

**Comment by martinpitt** [comment]
PR #15810 implements this now.
