### ISSUE TITLE
Causing the Failure of Getting IPv6 Address

### ISSUE THREAD

**Issue by KernelErr** [cockpit-project/cockpit#14811]
Cockpit version: 215-1
OS: Ubuntu Server 20.10 64Bit

When I tried to install Cockpit on my Raspberry Pi, it seems will replace the default network manager. And this replacement causes the failure of getting an IPv6 address. No matter how I change the configuration of the Netplan, it doesn't work.

Before I install the Cockpit, the system could get an IPv6 address successfully.

Steps to reproduce

1. sudo apt install cockpit
2. sudo reboot
3. ifconfig

**Comment by martinpitt** [comment]
If you don't want cockpit-networkmanager and NetworkManager, you can uninstall these:

    sudo apt-get purge cockpit-networkmanager network-manager

As for why mereley *installing* network-manager causes some  IPv6 failure: I suggest filing that against network-manager in Ubuntu.
