### ISSUE TITLE
SELinux Policy Disabled CentOS

### ISSUE THREAD

**Issue by wired420** [cockpit-project/cockpit#14822]
When the SELinux Policy on CentOS has been disabled, cockpit fails to restart.

```
Oct 27 22:07:23 server remotectl[55463]: /usr/bin/chcon: can't apply partial context to unlabeled file '/etc/cockpit/ws-certs.d/certificate.cert'
Oct 27 22:07:23 server remotectl[55463]: remotectl: couldn't change SELinux type context 'etc_t' for certificate: /etc/cockpit/ws-certs.d/certificate.cert: Child process exited with code 1
```

There some reason this is not a bug? I'd be satisfied if it were some kind of security feature but a lot of people disable SELinux. This was on a customers server who had no clue how to deal with selinux.

**Comment by martinpitt** [comment]
How exactly you disabled SELinux? `setenforce 0` works. I also tried to disable SELinux entirely:
```
grub2-editenv - set 'kernelopts=root=UUID=c1e714cb-7a1d-462b-84e3-3e0892f35c78 console=tty0 console=ttyS0,115200n8 no_timer_check net.ifnames=0 crashkernel=auto selinux=0'
```
With that, cockpit.service also starts fine. I also tried to let it re-generate the certificate:
```
systemctl stop cockpit
rm /etc/cockpit/ws-certs.d/0-self-signed*
systemctl start cockpit
```
which also works. So what exactly did you do? Can you please run

    strace -fvvs1024 /usr/sbin/remotectl certificate --ensure --user=root --group=cockpit-ws --selinux-type=etc_t

and copy&paste the output here?

**Comment by martinpitt** [comment]
Also, what exact CentOS and cockpit version (`rpm -q cockpit-ws`) are you using?

**Comment by martinpitt** [comment]
No answer in a long time, and this is not a bug, just an informational message.
