### ISSUE TITLE
how can i disable tls 1.0 in cockpit ?

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/cockpit#14833]
Cockpit version: 215
OS: ubuntu 18.04.05

hi.. our nessus scan indicate the cockpit allows the use of TLS version 1.0
i tried creating  ssl.conf in /etc/systemd/system/cockpit.service.d
using various options
#Environment=G_TLS_GNUTLS_PRIORITY=SECURE192:-VERS-ALL:+VERS-TLS1.3:+VERS-TLS1.2
#Environment=G_TLS_GNUTLS_PRIORITY=NORMAL:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1
Environment=G_TLS_GNUTLS_PRIORITY=-VERS-ALL:+VERS-TLS1.2
(and doing sudo systemctl daemon-resload, and restart off course) 
but nothing seems to have changed

**Comment by allisonkarlitskaya** [comment]
hi,

The TLS termination of cockpit is now performed by a process (`cockpit-tls`) which uses gnutls directly, and (specifically) doesn't use GLib or glib-networking.  The above environment variables would therefore have no effect.

**Comment by allisonkarlitskaya** [comment]
Maybe take a look at https://gnutls.org/manual/html_node/System_002dwide-configuration-of-the-library.html

**Comment by martinpitt** [comment]
See above, closing.

**Comment by codeme-py** [comment]
I'm having this issue where it says.

`cockpit-tls: $RUNTIME_DIRECTORY environment variable must be set to a private directory`

I checked their documentation and it said.

` cockpit-tls program expects the RUNTIME_DIRECTORY environment variable to be set to an empty directory (preferably in /run/)`

Cockpit is there in the /run/ directory. Yet it shows the same error.

**Comment by martinpitt** [comment]
@codeme-py : You are apparently trying to run the cockpit-tls directly,without the `cockpit.service` systemd unit. If you actually want to run cockpit, please just use the systemd service.

**Comment by codeme-py** [comment]
```
Aug 01 13:05:29 myserver systemd[1]: Starting Cockpit Web Service...
Aug 01 13:05:29 myserver systemd[1]: Started Cockpit Web Service.
```

Still shows the same error after using systemd

Sorry, I'm a noob in this kind of stuff. Please bear with me if I did something incorrect

**Comment by martinpitt** [comment]
Which error do you mean? "Started" means it succeeded? Please file a new issue if you use the distro package, it's not at all related to the original (and closed) issue here.

**Comment by codeme-py** [comment]
I mean the error I showed first :
`cockpit-tls: $RUNTIME_DIRECTORY environment variable must be set to a private directory`

Please file a new issue if you use the distro package, it's not at all related to the original (and closed) issue here.
Okay, i will do that

**Comment by emaayan** [comment]
hi.. i just got back to it cause i never managed to find a solution 
according to this  https://blog.surgut.co.uk/

in order to configure gnutls i need to :
Create config directory
sudo mkdir -p /etc/gnutls/
Create /etc/gnutls/default-priorities with
SYSTEM=SECURE192:-VERS-ALL:+VERS-TLS1.3:+VERS-TLS1.2 

but when i use sslscan i still see cockpit supporting 1.1 and 1.0

**Comment by ZiTAL** [comment]
I'm using caddy and disable it like this:
```
cockpit.domain.com http://cockpit.localhost {
    reverse_proxy cockpit.localhost:9090 {
        transport http {
            tls_insecure_skip_verify
        }
        header_up Host {host}
        header_up X-Forwarded-Proto https
        header_up X-Forwarded-For {remote_host}
    }
}
```

**/etc/hosts**
```
127.0.1.1       cockpit.localhost
```
