### ISSUE TITLE
how to config oauth

### ISSUE THREAD

**Issue by zhangyangyang3** [cockpit-project/cockpit#14832]
Hi:
 I try to intergate cockpit throw oauth ,I have configed the cockpit.conf in /etc/cockpit/ with the content below：

```
[OAuth]
URL = http://172.24.0.64:8029/#/oauth
ErrorParam = error
TokenParam = access_token

[bearer]
command = 
timeout = 300

```

but I do not know what should I put on 'commantd', I thougth it should be a executable  program and return a json like 
```
{
    "command": "authorize",
    "cookie": "cookie",
    "response": "Basic dXNlcjpwYXNzd29yZAo=",
}
```
in stdout .

but it seems that not works .
what should I do ?

hope your reply.thanks

**Comment by zhangyangyang3** [comment]
I saw the python demo,but how to run it ?just config the python file path to bearer's command?

**Comment by mvollmer** [comment]
This is the best documentation that I am aware of: https://github.com/mvollmer/seamless-cockpit  Make sure to watch the video, https://youtu.be/FSSiL_oHWi0

The max-pane and cockpit-auth-max-pane need Python 2 to run.  I have just updated the repo accordingly.  (Maybe I'll port the code to Python 3. Tell me if that would help you.)

**Comment by zhangyangyang3** [comment]
> This is the best documentation that I am aware of: https://github.com/mvollmer/seamless-cockpit Make sure to watch the video, https://youtu.be/FSSiL_oHWi0
> 
> The max-pane and cockpit-auth-max-pane need Python 2 to run. I have just updated the repo accordingly. (Maybe I'll port the code to Python 3. Tell me if that would help you.)

thank you,I will try .
