### ISSUE TITLE
Possible improvement in Wiki Let'sEncrypt guide

### ISSUE THREAD

**Issue by Tymek** [cockpit-project/cockpit#14843]
Page: https://github.com/cockpit-project/cockpit/wiki/Cockpit-with-LetsEncrypt

I think it's possible to add script copying certificate as `post` hook in certbot. It's simpler than adding cron task.
```/etc/letsencrypt/renewal-hooks/post/cockpit.sh```

Certbot docs: https://certbot.eff.org/lets-encrypt/debianbuster-other (end of the page)

I'm not sure if this will work. I will try on my server.

**Comment by martinpitt** [comment]
@Tymek : Did you ever get around to trying that? 

[This revision](https://github.com/cockpit-project/cockpit/wiki/Cockpit-with-LetsEncrypt/_compare/26f892fe0dd1e60e281221db70d840937cb36ba4...29366b7ea2cf78598345f0cc32edb210d7b3080c) moved from cronjob to a deploy script. The current wiki page version is very clean.
