### ISSUE TITLE
Versioning - update info

### ISSUE THREAD

**Issue by Ainz** [cockpit-project/cockpit#14845]
Very simple question really that should not be necessary...

When you in your blog announce the availablility of **Cockipt 231** ( https://cockpit-project.org/blog/cockpit-231.html ) I get in to terminal and find my version being **cockpit-211.3-1.el8.x86_64** . Now that does not look like the same version from my experience of Software Versioning.

Reading your blog it seems I am not running the latest, yet there are zero updates available, I checked manually.
Als tried running install and refresh but it says nothing to do...

Am I running the latest release and if not what do I need to do to update it on CentOS 8.2 Core

**Comment by marusak** [comment]
From your version I assume you are on rhel-8 (or centos-8).
There is a release process in the game. When we announce we have released a new version, it means it goes into supported systems, which are not in freeze of any kind. Also it takes longer after we do release until it is really available in your basic updates repository. There are a lot of moving parts  (like gating, testing, updating repos, mirrors...) - each OS and even different versions of OS have different flow and different speeds.

If you really want it right away your best bet is to use something very fast moving and on edge like fedora-rawhide (still mind that most likely you will use some mirrors of repositories so it may take a while until you software management software sees it). The more you go into stable and stable releases the slower the change is propagated. RHEL in general is very stable thing that goes through thorough process of testing to be sure that what is available is of the highest quality. Therefore changes take much longer to appear. Currently (or maybe in a very few days it will be available) there is RHEL 8.3 and in half a year there will be 8.4. 8.3 is frozen and we don't expect any more updates of cockpit in there. All the changes will be available in 8.4.

Of course, here I talk about the usual `dnf update cockpit` path. You can always go different path. You can for example use [copr](https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/) where we have the newest things. Copr is a very fast way how to get updates - it is there almost right after we do the release, normally before we post the article. Also there is no mirror in the way (I think). But of course it comes with the price that it is not tested (we test A LOT in Cockpit with the newest images, but I mean no gating or QA in the formal way). In the copr there are build for epel, so you should be able to use that.

**Comment by Ainz** [comment]
Thank you very much for the in depth clarification. I was aware of the move process and availability delay so that is no surprise although I might have expected it to be mentioned in a sentence like "released for distrubution, check your local channel"... :)
