### ISSUE TITLE
software: Automatic update restart-services or reboot (tracer) integration

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#14855]
While looking at #14723, I realized we might not have tracer integration planned for this yet.

Having the machine update and restart services or reboot when necessary would be fantastic.

**Comment by garrett** [comment]
Additionally, it would actually get rid of the need for all of the UI for tracer, so perhaps we could even split [the PR](https://github.com/cockpit-project/cockpit/pull/14581) into two parts:

1. basic tracer integration and automatic updates support
2. tracer UI (which the PR is working on integrating)

This would allow us to integrate tracer earlier without all the UI polish.

What do you think about this, @skobyda?

**Comment by KKoukiou** [comment]
Automatic service restart is not a good idea in my opinion. And that because restarting of services is often a disruptive operation, which can cause downtime of needed processes, so I would let that to the user to decide.

**Comment by martinpitt** [comment]
I agree that would be great. Right now we always auto-reboot the entire machine after every automatic update, so just auto-restarting services would be a big help. @KKoukiou that's indeed a compromise that admins have to trade -- *if* the machine can get along with some regular unavailability/reboots, *then* you have the option to enable automatic updates, and not have to worry about applying them manually yourself.

**Comment by garrett** [comment]
> Automatic service restart is not a good idea in my opinion. And that because restarting of services is often a disruptive operation, which can cause downtime of needed processes, so I would let that to the user to decide.

This is proposed as an alternative to complete rebooting after a system update. Restarting services is already much less disruptive than a complete reboot. In some cases, there would also not be a restart of any services or a reboot. 

And, like auto-updates (with rebooting), it's already an opt-in.

So, this is a suggestion to use tracer to be able to have a _less disruptive_ flow (when possible) than what we currently have.

**Comment by martinpitt** [comment]
SW updates page has used tracer for a while now.
