### ISSUE TITLE
"OAuth failure" doesn't look designed

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#14885]
![image](https://user-images.githubusercontent.com/3228183/98521916-bac9ab80-227c-11eb-821b-e833ff0e2dcc.png)

This has probably regressed over time, since very very few people ever see it, I guess.

**Comment by garrett** [comment]
I agree with you. I thought it might be a regression or a bug or something.

What should this look like? I doubt failing with OAuth should look like a successful log out.

Wild guess, something like:

> ### Authentication failure
> Invalid OAuth token recieved. Or whatever other error that applies.
>
> [Try again] Cancel

I'm assuming "login again" really means "try again" with the same credentials (or whatever) — that Cockpit would try to contact the OAuth provider to get a success. Is that right?

And cancel would put you back at the inital Cockpit login screen?

**Comment by mvollmer** [comment]
> I'm assuming "login again" really means "try again" with the same credentials (or whatever) — that Cockpit would try to contact the OAuth provider to get a success. Is that right?

Yes, it would start the whole process over.  If the "OAuth" provider still authorizes it, a new Cockpit session will start automatically.  If not, what happens depends on the provider.  You might end up on the login page of that provider, and after logging in there, you will then be taken automatically to Cockpit.  Or the provider might return an error which Cockpit would then show.
 
> And cancel would put you back at the inital Cockpit login screen?

No, there is no login screen to go back to.  The best thing "cancel" could do is probably close the browser. :-) I would not have a "Cancel" button here.
