### ISSUE TITLE
upgrade cockpit centos 8

### ISSUE THREAD

**Issue by ali-95** [cockpit-project/cockpit#14883]
Centos 8 cockpit 211
how to upgrade cockpit 211 to cockpit 231
dnf update does not update

**Comment by KKoukiou** [comment]
@ali-95 it does not update because centos 8 repositories contain 211 right now.
You can try CentOS Stream to get some newer versions, but even that does not contain the latest releases.

**Comment by marusak** [comment]
Or you can also try https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/ as a preview what will come to centos later on
