### ISSUE TITLE
Creation of VM server failed

### ISSUE THREAD

**Issue by badbyt3** [cockpit-project/cockpit#14894]
Cockpit version: 230
OS: manjaro (archlinux derivative)
Page: 

When trying to create a vm in Virtual machines I get the message:

> Creation of VM test failed show less
> error: failed to get emulator capabilities error: internal error: no capabilities available for /usr/libexec/qemu-kvm ERROR Host does not support any virtualization options
![chrome_Zo2TeTeL7O](https://user-images.githubusercontent.com/1003490/98799444-6c004b00-240f-11eb-9e6e-5db7cf4cbf9d.png)

journalctl -u cockpit -u machines:

> Nov 11 11:20:26 cerebro systemd[1]: Starting Cockpit Web Service...
> Nov 11 11:20:27 cerebro systemd[1]: Started Cockpit Web Service.
> Nov 11 11:20:27 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:20:27 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:20:27 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:20:28 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:20:28 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:20:28 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:20:28 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:20:28 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:20:33 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:20:33 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:20:33 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:20:33 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:20:33 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:20:33 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:20:33 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:24:03 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:24:03 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:33:22 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:39:42 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:39:42 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:56:29 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:56:29 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:56:29 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:56:29 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:56:29 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:56:29 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:56:29 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:56:29 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:56:29 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:56:29 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:56:29 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:57:51 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:57:51 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
> Nov 11 11:58:01 cerebro cockpit-tls[55754]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.

Steps to reproduce

1.
2.
3.

**Comment by marusak** [comment]
Does not seem related to Cockpit at all. But I'll let @KKoukiou to rule this one out or see if there is something we should/could do about this in Cockpit.

**Comment by badbyt3** [comment]
before posting the issue, I first stated my issue in the irc chat. there a user named daniel-wtd said said the following: starting the containers via command  line  works  find, you may open an issue for the cockpit folks, so they can have a look.

**Comment by KKoukiou** [comment]
Indeed that's not cockpit related. I bet you will see the exact same error when you try to use virt-install directly. Did you try?

Then for debugging this further: what's the output of `egrep -m 1 "svm|vmx" /proc/cpuinfo`? this will show you if your host has virtualization support.
And then check `lsmod | grep kvm` to see if the kvm module is loaded.
Maybe paste these two and we can't help you figure this out.

**Comment by badbyt3** [comment]
egrep -m1 "svm|vmx" /proc/cpuinfo gave me:

> flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d

and lsmod |grep kvm:

> kvm_intel             319488  0
> kvm                   851968  21 kvm_intel
> irqbypass              16384  1 kvm

**Comment by KKoukiou** [comment]
@badbyt3 these look good. 
You can probably get some more hints, by running. `virt-host-validate` and checking that all PASS.
You could also try re-installing libvirt* which will re-install all the dependencies in case you have some weird state of missing some packages.

All in all, I think you will need to ask the libvirt/qemu/kvm community for solving your issue (#virt channel or IRC on oftc server). Because cockpit-machines is just a wrapper around these technologies, and the error you see is coming from libvirt itself.

**Comment by badbyt3** [comment]
virt-host-validate
 

>  QEMU: Checking for hardware virtualization                                 : PASS
>   QEMU: Checking if device /dev/kvm exists                                   : PASS
>   QEMU: Checking if device /dev/kvm is accessible                            : PASS
>   QEMU: Checking if device /dev/vhost-net exists                             : PASS
>   QEMU: Checking if device /dev/net/tun exists                               : PASS
>   QEMU: Checking for cgroup 'cpu' controller support                         : PASS
>   QEMU: Checking for cgroup 'cpuacct' controller support                     : PASS
>   QEMU: Checking for cgroup 'cpuset' controller support                      : PASS
>   QEMU: Checking for cgroup 'memory' controller support                      : PASS
>   QEMU: Checking for cgroup 'devices' controller support                     : PASS
>   QEMU: Checking for cgroup 'blkio' controller support                       : PASS
>   QEMU: Checking for device assignment IOMMU support                         : PASS
>   QEMU: Checking if IOMMU is enabled by kernel                               : WARN (IOMMU appears to be disabled in kernel. Add intel_iommu=on to kernel cmdline arguments)
>   QEMU: Checking for secure guest support                                    : WARN (Unknown if this platform has Secure Guest support)
>    LXC: Checking for Linux >= 2.6.26                                         : PASS
>    LXC: Checking for namespace ipc                                           : PASS
>    LXC: Checking for namespace mnt                                           : PASS
>    LXC: Checking for namespace pid                                           : PASS
>    LXC: Checking for namespace uts                                           : PASS
>    LXC: Checking for namespace net                                           : PASS
>    LXC: Checking for namespace user                                          : PASS
>    LXC: Checking for cgroup 'cpu' controller support                         : PASS
>    LXC: Checking for cgroup 'cpuacct' controller support                     : PASS
>    LXC: Checking for cgroup 'cpuset' controller support                      : PASS
>    LXC: Checking for cgroup 'memory' controller support                      : PASS
>    LXC: Checking for cgroup 'devices' controller support                     : PASS
>    LXC: Checking for cgroup 'freezer' controller support                     : PASS
>    LXC: Checking for cgroup 'blkio' controller support                       : PASS
>    LXC: Checking if device /sys/fs/fuse/connections exists                   : FAIL (Load the 'fuse' module to enable /proc/ overrides)

**Comment by KKoukiou** [comment]
It looks good as well, in this case I run out of ideas, if you tried to remove and reinstall libvirt* packages I ran out of ideas.

**Comment by badbyt3** [comment]
I did a libvirt search in the repository and I got this:

> community/libvirt 1:6.5.0-3 [installed]
>     API for controlling virtualization engines (openvz,kvm,qemu,virtualbox,xen,etc)
> community/libvirt-dbus 1.4.0-1 [installed]
>     Wrapper around libvirt API to provide a high-level object-oriented API better suited for dbus-based applications
> community/libvirt-glib 3.0.0-2 [installed]
>     GLib bindings for libvirt
> community/libvirt-python 1:6.4.0-1 [installed]
>     libvirt python binding
> community/libvirt-storage-gluster 1:6.5.0-3
>     Libvirt Gluster storage backend
> community/libvirt-storage-iscsi-direct 1:6.5.0-3
>     Libvirt iSCSI-direct storage backend
> community/libvirt-storage-rbd 1:6.5.0-3
>     Libvirt RBD storage backend
> community/perl-sys-virt 6.3.0-2
>     Represent and manage a libvirt hypervisor connection
> community/virt-install 3.1.0-1 [installed]
>     Command line tool for creating new KVM , Xen, or Linux container guests using the libvirt hypervisor

Let me know if there is any additional packages that  I need to install.

**Comment by KKoukiou** [comment]
@badbyt3 I can't help you more with this. As I said, for more help with debugging this you will need to ask the libvirt/qemu/kvm community (#virt channel or IRC on oftc server). I am closing this issue, because it's not cockpit machines that causes this issue, but it's something wrong with one of virt-install/libvirt/qemu-kvm/kvm. So I redirect you to the devs of these packages.

**Comment by badbyt3** [comment]
ok no problem.
