### ISSUE TITLE
unable to view send and receive in networking

### ISSUE THREAD

**Issue by mytvpro** [cockpit-project/cockpit#14921]
![image](https://user-images.githubusercontent.com/47206457/99543014-ad00de00-2980-11eb-8c7b-31ea376db218.png)

**Comment by mytvpro** [comment]
![image](https://user-images.githubusercontent.com/47206457/99543312-0bc65780-2981-11eb-8f13-ff1905fe4303.png)
actually even on local host

**Comment by mytvpro** [comment]
i really just have no data under networking. is there something i can do?

**Comment by mytvpro** [comment]
Bump?

**Comment by marusak** [comment]
Can you please provide more info:
- What browser and in what version are you using?
- What host are you using cockpit on?
- What version of cockpit and cockpit-networking are you using?

**Comment by mytvpro** [comment]
I'm using the latest version of chrome 87. The cockpit host is Ubuntu 18.04 lts server. I'll check the version of cockpit asap. It's whatever Installs after running apt update and apt Install cockpit

**Comment by mvollmer** [comment]
Note that there aren't any interfaces listed in the "Interfaces" panel below the plots. That is probably the fundamental issue.

Can you show the output of running `nmcli` in the Terminal?

> oddly everything else seems to be working fine

Does "everything" include anything on the "Networking" page?

**Comment by marusak** [comment]
@mytvpro bump

**Comment by KKoukiou** [comment]
Closing as there is not response from the issuer.
