### ISSUE TITLE
Core dump by SPICE viewer

### ISSUE THREAD

**Issue by mpdavis73** [cockpit-project/cockpit#14922]
Cockpit version: 232-1
OS: ArchLinux
Page: Virtual Machines (not directly, though)

[info.txt](https://github.com/cockpit-project/cockpit/files/5563607/info.txt)
[Journal_cockpit_remmina.txt](https://github.com/cockpit-project/cockpit/files/5563608/Journal_cockpit_remmina.txt)
[Journal_virt-manager.txt](https://github.com/cockpit-project/cockpit/files/5563609/Journal_virt-manager.txt)
[Journal_virt-manager_nouveau.txt](https://github.com/cockpit-project/cockpit/files/5563610/Journal_virt-manager_nouveau.txt)
[lshw.txt](https://github.com/cockpit-project/cockpit/files/5563612/lshw.txt)

[core.remmina.1000.3210fb612c544a479626d81e65e3b5d4.14574.1605631955000000.zip](https://github.com/cockpit-project/cockpit/files/5563619/core.remmina.1000.3210fb612c544a479626d81e65e3b5d4.14574.1605631955000000.zip)
[core.virt-manager.1000.8491b9e6ed82467a8cc5dbf4d66c9ecf.62082.1605736050000000.zip](https://github.com/cockpit-project/cockpit/files/5563620/core.virt-manager.1000.8491b9e6ed82467a8cc5dbf4d66c9ecf.62082.1605736050000000.zip)
Crash randomly occurs during input operation
Normal day:
  Start and open Win10 VM via virt-manager or cockpit (using Display Spice->Spice Server for VM)
  Set for full screen
  Check for new Windows security updates
  Open MSIE and login to work website for work
  Randomly during even operation (keypress or mouse click), the display window will crash (journal output included)

I have had the same results using the built-in VM viewer with virt-manager and with remmina, so I am fairly sure if the problem is with cockpit, it is somewhere in the spice server. I have included journal logs from virt-manager and remmina crashes while using the nvidia driver, as well as one from virt-manager using the nouveau driver, and core dumps from remmina with nvidia, and virt-manager with nouveau. So far, this has only occurred on plasma - I used xfce for a week and a half with no crashes. Willing to work to find whatever details may be needed. Please note that this is not a bad issue, as the VM itself is fine, and only requires re-launching the viewer (virt-manager or remmina - willing to try others if it would help). If this is against the wrong project, please let me know. Possibly an issue for spice directly.

**Comment by marusak** [comment]
Pretty sure this goes out of Cockpit scope and think it needs to be reported in virtmanager/spice or something like that. I am not sure if you use the viewer in browser or are completely outside Cockpit when this happens (there are two ways how you can connect to the viewer). @KKoukiou you know what I mean, right? :) Can you please decide if this needs some input from Cockpit (how we open the viewer) or not really related and help advise where this should go? Thanks!

**Comment by mpdavis73** [comment]
Ok, did some more testing, and I am thinking this should best go to ArchLinux, maybe under spice or spice-gtk. I tested by running a VM on my laptop on Ubuntu 20.04, which has Intel graphics, though I already determined it wasn't driver related - not sure how it could be GPU related and not driver related. It lasted one day with no issues at all. Please feel free to close this if it isn't useful. Thanks!

**Comment by KKoukiou** [comment]
Hey @mpdavis73 indeed you need to report it to spice on your distribution. We only create the file you download which contains the spice address and so on.
