### ISSUE TITLE
mdadm: no arrays found in config file or automatically

### ISSUE THREAD

**Issue by Viksie** [cockpit-project/cockpit#14924]
Cockpit version: 229
OS: Debian 10 - 4.19.152-1 via Buster backport - /etc/apt/sources.list.d/backports.list

On reboots, "mdadm: no arrays found in config file or automatically" messages considerably delay the boot time.

Server has no software based RAID array config, neither is there any intention of creating a software based (mdadm) RAID array.

Deleting /etc/mdadm/mdadm.conf and executing "update-initramfs -u" does not resolve the issue.

Cockpit reflects mdadm services:

mdadm-shutdown		Prepare mdadm shutdown initramfs	Not running	Disabled
mdadm-waitidle		mdadm-waitidle.service			Not running	masked
mdadm			mdadm.service				Not running	masked
mdcheck_continue	MD array scrubbing - continuation	Not running	Static
mdcheck_start		MD array scrubbing			Not running 	Static
mdmonitor-oneshot	Reminder for degraded MD arrays		Not running	Static
mdmonitor		MD array monitor			Not running	Static

Installation was executed via:

apt install -t buster-backports cockpit cockpit-docker cockpit-machines cockpit-packagekit cockpit-storaged cockpit-networkmanager

**Comment by mvollmer** [comment]
> On reboots, "mdadm: no arrays found in config file or automatically" messages considerably delay the boot time.

Hmm, wouldn't that be a bug with mdadm in Debian?

It should be possible to install it without actually using it.  This is my experience so far with all distributions.

I just checked our `debian-stable` CI image and installed the backports into it with your command. There is no sign of a slow boot nor any message from mdadm.

I am afraid your problem must be somewhere else.
