### ISSUE TITLE
cockpit-dashboard??

### ISSUE THREAD

**Issue by mytvpro** [cockpit-project/cockpit#14920]
it took me quite a bit of googling to find out cockpit doesnt install with the dashboard. could there be some way to let users know about additional plugins needed?

**Comment by martinpitt** [comment]
Out of interest, for what do you need the dashboard plugin? It's not really a "needed" plugin, in fact it's mostly obsoleted by the builtin host switcher now.

**Comment by mytvpro** [comment]
when i installed on ubuntu 20 there was no outter menu where it says dashboard and host until i installed cockpit-dashboard then it showed up.

**Comment by mytvpro** [comment]
also i am looking to add remote hosts and the botton do that is under dashboard

**Comment by mytvpro** [comment]
actually i added one of the remote host but im not seeing the network data which is really why i want this

![image](https://user-images.githubusercontent.com/47206457/99537636-eaae3880-2979-11eb-8b8a-71186377218d.png)

**Comment by mytvpro** [comment]
and on the host with ubuntu 20 there is no networking tab in the menu

**Comment by mytvpro** [comment]
oddly traffic shows here but really would like the breakdown of send and receive guess i need to add the interfaces to the dash?
![image](https://user-images.githubusercontent.com/47206457/99537909-3eb91d00-297a-11eb-9c03-bee036630bea.png)

**Comment by mytvpro** [comment]
> actually i added one of the remote host but im not seeing the network data which is really why i want this
> 
> ![image](https://user-images.githubusercontent.com/47206457/99537636-eaae3880-2979-11eb-8b8a-71186377218d.png)

just says OOPS at the top when i clicked `add bond`

**Comment by mytvpro** [comment]
im going to try ubuntu 18

**Comment by mytvpro** [comment]
it installed a lot more packages and looks completely different in ubuntu 18

**Comment by mvollmer** [comment]
This seems to be about the same stuff as #14921 now, right?  I think the original dashboard issue has been cleared up.
