### ISSUE TITLE
Command-character inserts "character" in the Cockpit Terminal window when it shouldn't.

### ISSUE THREAD

**Issue by tslivnik** [cockpit-project/cockpit#14944]
Cockpit version: 232
OS: Linux linux 5.6.6-300.fc32.x86_64 #1 SMP Tue Apr 21 13:44:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Page: Terminal

I have Firefox configured so that Command-c acts as Copy and Command-v acts as Paste. When I use these keys to copy from, or paste into, a Cockpit Terminal window, the paste is preceded by a "v" character and a copy inserts a "c" character into the Terminal window.

There is no relevant information provided by journalctl.

Steps to reproduce

1. Set up Firefox so that Command-c is Copy and Command-v is paste.
2. Start Cockpit.
3. Start a Terminal in Cockpit.
4. Copy some text in another program.
5. Switch to Cockpit Terminal window and press Command-v.
6. Instead of just the copied text being pasted, "v" plus the copied text are pasted.

**Comment by mvollmer** [comment]
>     1. Set up Firefox so that Command-c is Copy and Command-v is paste.

How did you do this exactly?  Are you on a Mac?

Without any special setup, I can use Control-V with the Cockpit terminal and it works as expected.  Control-C sends SIGINT, of course.

**Comment by tslivnik** [comment]
I'm on Linux. In the file ~/.mozilla/firefox/${PROFILE}/prefs.js, there is a variable called ui.key.accelKey which determines whether you must use Ctrl, Alt or Command with your letter keys to effect the desired commands. The default on Linux is Ctrl, but I prefer Command, as I grew up with the NeXT (and now Mac OS X) way of doing things. Also, the Ctrl key is already supposed to generate ASCII codes between 0 and 31, so you really need another key to control the GUI and the Ctrl key is a bit of a clunky choice and I don't understand why it's the default on Linux (just imagine Ctrl-M, Ctrl-J, Ctrl-H etc. - and Ctrl-C of course as well) - but that's another conversation. It just seems to me that Cockpit not working correctly with this (supported) setup is a bug. I wonder what happens on a Mac?

**Comment by martinpitt** [comment]
@tslivnik Do you still have that problem with current versions of Cockpit? xterm got a lot of fixes since then. Thanks!
