### ISSUE TITLE
Logging in cockpit on Mageia 7

### ISSUE THREAD

**Issue by hviaene** [cockpit-project/cockpit#14940]
Cockpit version: 232
OS: Mageia 7
Page:x86-64 AMD processor

Mageia does not have cockpit in its repos, so I downloaded the latest fedora version form rpmfind.net: cockpit, cockpit-motd, cockpit-wsinstance-httpd and cockpit-wsinstance-httpd-redirect.
Got the services running , and the login screen appears at localhost:9090
But when I enter user and its password (root or normal user) I get: Authentication failed: internal-error: Module is unknown.
Googling I did not find which module might be missing. It is certainly not ssh, I have the sshd daemon running.

from journalctl I get
/usr/libexec/cockpit-ws: /lib64/libjson-glib-1.0.so.0: no version information available (required by /usr/libexec/cockpit-ws)
but checking /usr/lib64 I find
# ls -als /lib64/libjson-glib-1.0.so.0
0 lrwxrwxrwx 1 root root 27 apr 17  2019 /lib64/libjson-glib-1.0.so.0 -> libjson-glib-1.0.so.0.400.4*
and further in the journal
PAM unable to dlopen(/usr/lib64/security/pam_sepermit.so)
But here I am at lost: there are a load of pam packages in the repos, but none of them match for this file name

**Comment by marusak** [comment]
Seems that someone is supporting it: https://mageia.pkgs.org/cauldron/mageia-core-release-x86_64/cockpit-227-1.mga8.x86_64.rpm.html (although not on m-7, but that is due to EOL in a month...)
Maybe you could reach out to the maintainer that ships it into Mageia.

Anyway, quick google search answers this error rather nicely: https://stackoverflow.com/questions/137773/what-does-the-no-version-information-available-error-from-linux-dynamic-linker

**Comment by hviaene** [comment]
Right, the pam version  in Mageia 7 is 1.3.1. Mageia 8 isn't there yet  as an official release, but it is not that I urgently need cockpit. so I'll wait a while.

**Comment by mvollmer** [comment]
> PAM unable to dlopen(/usr/lib64/security/pam_sepermit.so)

It should be fine to just remove this line from /etc/pam.d/cockpit.

**Comment by marusak** [comment]
@hviaene any progress? Have you tried removing just that line from `/etc/pam.d/cockpit`?

**Comment by hviaene** [comment]
Yes, I did. And that gets rid of this problem. I get the login screen via http://localhost:9090. But when I enter my usual username and password on that machine, or the root, I get permission denied.
The cockpit file reads now
#%PAM-1.0
# this MUST be first in the "auth" stack as it sets PAM_USER
# user_unknown is definitive, so die instead of ignore to avoid subsequent modules mess up the error code
-auth      [success=done new_authtok_reqd=done user_unknown=die default=ignore]   pam_cockpit_cert.so
# auth       required     pam_sepermit.so
auth       substack     password-auth
auth       include      postlogin
auth       optional     pam_ssh_add.so
account    required     pam_nologin.so
account    include      password-auth
password   include      password-auth
# pam_selinux.so close should be the first session rule
session    required     pam_selinux.so close
session    required     pam_loginuid.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required     pam_selinux.so open env_params
session    optional     pam_keyinit.so force revoke
session    optional     pam_ssh_add.so
session    include      password-auth
session    include      postlogin

**Comment by hviaene** [comment]
Searching found a refeernce to user have to belong to cockpit-ws group. Assigned that to my usual user, rebooted the system, but still "Permission denied".

**Comment by martinpitt** [comment]
Please don't add users to the cockpit-ws group. This is actively wrong and dangerous.

This requires debugging the PAM stack for Mageia, which is a downstream thing. Given that this issue is over two years old and nobody jumped at fixing it, I'm closing this now to clean up our issue tracker. Sorry, and thanks for understanding.
