### ISSUE TITLE
TestFirewall.testMultipleZones fails to read interfaces

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#14958]
Either `'Get', ['org.freedesktop.NetworkManager.Device', 'Interface'])` or `'Get', ['org.freedesktop.NetworkManager.Device', 'Capabilities'])` fails with `{"problem":"not-found","name":null,"message":"not-found"}` and then in the UI no interfaces are listed as seen for example [here](https://logs.cockpit-project.org/logs/pull-14957-20201124-182056-a7d4d1c9-ubuntu-stable/TestFirewall-testMultipleZones-ubuntu-stable-127.0.0.2-2301-FAIL.png).

Example failure [log](https://logs.cockpit-project.org/logs/pull-14957-20201124-182056-a7d4d1c9-ubuntu-stable/log.html#167-2)

According to our [stats](https://images-frontdoor.apps.ocp.ci.centos.org/failure-stats.html) it happens only on ubuntu-stable, but rather often.

**Comment by marusak** [comment]
For the same reason fails also `TestFirewall.testNetworkingPage `

https://logs.cockpit-project.org/logs/pull-14965-20201126-082347-3cb06739-ubuntu-stable/log.html#168-2

**Comment by KKoukiou** [comment]
This does not appear in our new stats. It does not mean it stopped, but without active links this is not very useful anymore. Let's close it and address it if it shows up again in the stats.
