### ISSUE TITLE
cockpit-storaged on CentOS 8 is broken after update to release 233

### ISSUE THREAD

**Issue by PeterFalken** [cockpit-project/cockpit#14974]
Cockpit version: 233
OS: CentOS
Page: Storage

Page fails to display with Ooops! message on top right.
Web Console shows: missing /base1/jquery.js - which was one of the changes of this release (233)

Steps to reproduce

1. Install COPR Cockpit-Preview repository on CentOS 8
2. Install latest version:
`sudo vi /etc/yum.repos.d/cockpit-preview.repo
sudo dnf makecache
sudo dnf -y install cockpit cockpit-packagekit cockpit-pcp cockpit-storaged`
3. Try to navigate to the Storage page.

![StorageDPage](https://user-images.githubusercontent.com/2557898/100402679-7f700080-3022-11eb-8cb5-055e1c45a249.png)

cockpit-storaged package for CentOS8 is still on version 228 on the COPR builds for CentOS

**Comment by marusak** [comment]
https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/build/1794437/

There is cockpit-storaged version 233. What I am more worried is that this is regression on our side that we don't require newer versions if we break it with a new version.

**Comment by martinpitt** [comment]
It's indeed not there: https://download.copr.fedorainfracloud.org/results/@cockpit/cockpit-preview/epel-8-x86_64/01794437-cockpit/

That's because on RHEL/CentOS 8 the cockpit.srpm now only builds the basic packages by default. We need to think about how we handle this -- upload a cockpit-appstream.srpm to copr, or adjust the spec again to build everything in COPR, but not in the real distro (not sure yet how to do that).

But I'll send a PR to fix the dependencies, thanks for pointing out!

**Comment by martinpitt** [comment]
I sent PR #14976 to adjust the package dependencies to prevent this from happening. The second half is of course still to adjust our spec to build all packages in COPR.

**Comment by martinpitt** [comment]
@PeterFalken : I did a manual COPR upload now which [provides all packages](https://download.copr.fedorainfracloud.org/results/@cockpit/cockpit-preview/epel-8-x86_64/01796907-cockpit/), so if you upgrade again, it should work now. Sorry for the hiccup!

I sent PR #14977 to fix this for the automatic releases.

**Comment by martinpitt** [comment]
Reopening for the second half, fixing our COPR. My first PR was not successful yet.

**Comment by PeterFalken** [comment]
@martinpitt Thanks for quick fix.
After the update cockpit-storaged is working correctly and as good side effect all versions of cockpit packages from COPR are at their latest versions.
![COPR_Versions](https://user-images.githubusercontent.com/2557898/100456877-a6601e00-3086-11eb-950d-008e1d7a921e.png)

**Comment by martinpitt** [comment]
@PeterFalken : Ugh, you managed to catch cockpit-ostree 999 -- that was an accident, that's of course not a real version number. I just deleted it from COPR, maybe you can install the real version 184-1? `sudo dnf distro-sync` ought to do that.

**Comment by PeterFalken** [comment]
@martinpitt I figured that cockpit-ostree 999 was a test, but I'm not aware of CentOS having an Atomic/Silverblue version yet - I might be mistaken. So wasn't able to ever test the ostree build. Hahahaha. In Fedora it works as intended. :). No harm done here.
