### ISSUE TITLE
track package-lock.json in git

### ISSUE THREAD

**Issue by lnussel** [cockpit-project/cockpit#14978]
AFAICT so far releases are done by tagging a commit in git. Then a ci job takes that, modifies the spec file to include the tag as version, runs npm etc to produce the minified files in dist/ as well as `package-lock.json`.

Would it be possible to commit back the spec file and the `package-lock.json` to git? Could be a separate release-XXX tag for example. That would allow to recreate the dist content and build a package in a separate build system such as OBS just by fetching sources from upstream git.

**Comment by KKoukiou** [comment]
@martinpitt with make_dist @lnussel can do exactly what he needs right?

**Comment by martinpitt** [comment]
We have been talking about tracking package-lock.json in git in general, to avoid some pitfalls when some random npm modules update and regress. That would solve your issue as well.

@KKoukiou : make_dist is unrelated -- our release tarballs have included package-lock.json for a long while alreay, so if your build system is ok with downloading anything, then it's better to download the official release tarball rather than some git tag.

But if it helps in the meantime, we can publish the package-lock.json as a separate release artifact on GitHub, so that you only have to download that instead of the 8 MB full tarball.

**Comment by martinpitt** [comment]
We actually have that now: Our node_modules is [tracked in git](https://github.com/cockpit-project/node-cache/). So if you are building from cockpit.git, `tools/node_modules checkout` will fetch the correct tag from the node cache. This includes package-lock.json, but also all the actual modules right away. Is that suitable for you @lnussel , or is there still a step missing?

**Comment by KKoukiou** [comment]
Closing as there is not reply from the reporter and in my opinion the reported issue is already addressed.

**Comment by lnussel** [comment]
ah sorry, I missed the question. No it's not really what I had mind. Also doesn't include the spec file modifications :-)

**Comment by martinpitt** [comment]
> No it's not really what I had mind.

What is missing then?

**Comment by lnussel** [comment]
something like this https://github.com/cockpit-project/cockpit/compare/251...lnussel:251-dist?expand=1

You don't have to. No is a valid answer :-)

**Comment by martinpitt** [comment]
@lnussel : You can get package-lock.json from several places: Our node-cache has both the full `node_modules/` as git tree, as well as https://github.com/cockpit-project/node-cache/blob/252/.package-lock.json. It's also contained in the release tarballs.

Indeed we don't put the generated .spec file into git, as that's specifically an artifact from releases. Again, it is part of the release tarballs (tools/cockpit.spec), and if you wanted to you could also get it from https://src.fedoraproject.org/rpms/cockpit/blob/rawhide/f/cockpit.spec (but that would feel rather weird, and Fedora dist-gits are also not tagged).

The idea is that a release tarball plus the autogenerated tag tarballs from node-cache give you a full set of files to be able to build everything locally, without internet connection. Or alternatively, build everything from the actual upstream git (if you check out a tag).

**Comment by KKoukiou** [comment]
Closing as per comment above.
