### ISSUE TITLE
Cockpit 215 & 231 does not work on chrome & edge

### ISSUE THREAD

**Issue by Tuliku** [cockpit-project/cockpit#14998]
Cockpit version: 231 & 215
Client OS: Win10
- MS Edge Version 87.0.664.52 (Official build) (64-bit)
- Chrome Version 87.0.4280.66 (Official Build) (64-bit)
- Firefox 83.0 (64-bit)
Server OS: 20.04.1 LTS fresh install

These are the steps I did:
`sudo apt update`
`sudo apt upgrade`
`sudo apt install cockpit`
`sudo systemctl start cockpit`
`sudo systemctl status cockpit`
-all good
`ss -tunlp | grep 9090`
-all good
`sudo ufw allow 9090/tcp`
-all good
The version of Cockpit installed is now **215** !

When going to _https://<Server-IP>:9090_ in Edge and Chrome gives me this error:
_**Connection failed**
There was an unexpected error while connecting to the machine.
Messages related to the failure might be found in the journal:
journalctl -u cockpit_
Only in Firefox it works.

Trying to update Cockpit from 215 to the latest version
Adding in `/etc/apt/sources.list` this line:
`deb http://ports.ubuntu.com/ubuntu-ports focal-backports main restricted universe multiverse`
I ran
`apt-get install -t focal-backports cockpit`
`sudo systemctl start cockpit`
`sudo systemctl status cockpit`
-all good

Now I'm running Cockpit **231**, but not the 233 version that is released according to https://cockpit-project.org/blog/cockpit-233.html
After this update to 231, the issue's are the same in Chrome and Edge.
Only Firefox works.

- How to make it work in Chrome ?
- How to update to version 233 ?

**Comment by mvollmer** [comment]
> journalctl -u cockpit

Could you run this command and show the output?

Could you also open the Browser console of Chrome while logging in and show its content?

The error message you see means that Cockpit was loaded successfully into the browser, but it could not open the websocket back to the managed machine. This might be because of certificate issues, or some other issues like misconfigured proxies.

I have tried Chrome "Version 87.0.4280.66 (Official Build) (64-bit)" (same as yours) on Fedora 33, and it works fine.

**Comment by Tuliku** [comment]
Thanks !
I did a reboot, and then your command:
- -- Reboot --
- Dec 02 09:36:36 onsdum systemd[1]: Starting Cockpit Web Service...
- Dec 02 09:36:36 onsdum systemd[1]: Started Cockpit Web Service.
- Dec 02 09:37:54 onsdum cockpit-tls[1315]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
- Dec 02 09:38:31 onsdum cockpit-tls[1315]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.

At 09:36 I started Firefox and logged in successfully
At 09:37 I started Edge and after username/password I got the error again.
At 09:38 I started Chrome and after username/password I got the error again.

And here is the console screenshot
![cockpit](https://user-images.githubusercontent.com/75329507/100856814-2ffb5b80-348c-11eb-882d-265961f06be8.jpg)

**Comment by lameducks** [comment]
I had the same problem, but due to the SSL protocol filter (ESET SSL Filter) on the client side.
I solved it by adding the Cockpit address to ESET's whitelist and clear Chrome SSL cache.

Note: #13668 may have a similar cause.

**Comment by Tuliku** [comment]
Hello Lameducks, I've tried this but in chrome I can not find anywhere the SSL cache to be cleared.
According to google it should be done like this:
-  To clear the SSL state in Chrome, follow these steps:
-  Click the (Settings) icon, and then click Settings.
-  Click Show advanced settings.
-  Under Network, click Change proxy settings. The Internet Properties dialog box appears.
-  Click the Content tab.
-  Click Clear SSL state, and then click OK.
But there is no network tab in chrome, and no SSL cache of any kind.

In Eset I added it to the white list though, but still no succes.
It's weird though, that in Firefox it does work without problems.
![cockpit issue](https://user-images.githubusercontent.com/75329507/102776508-22503c00-438f-11eb-950a-56423b62bf27.jpg)

**Comment by marusak** [comment]
So since firefox works and chrome does not this is very likely some plugin in your chrome browser. It might be eset as mentioned above, but there are planty of plugins which can block cockpit. Can you try to run chrome in recovery mode (all plugins disabled) and try then?

Note: We test chrome and firefox every day so it works in general.

**Comment by martinpitt** [comment]
No response in half a year, closing.
