### ISSUE TITLE
[Feature Request] Add support for libStorageMgmt

### ISSUE THREAD

**Issue by kirantpatil** [cockpit-project/cockpit#150]
Hello,

Libstoragemanagement (http://sourceforge.net/projects/libstoragemgmt/) - A library for storage management is  a Redhat project and  does not contain a gui interface.

Allowing to manage storage using libstoragemgmt will help to manage heterogeneous storage devices from cockpit.

Project wiki: http://sourceforge.net/p/libstoragemgmt/wiki/Home/

**Comment by stefwalter** [comment]
libstoragemgmt support is going into storaged. And various features based on that functionality could go into Cockpit. As these get added they should be targetting actual features not just "libstoragemgmt". Closing.
