### ISSUE TITLE
Is there any notification features like e-mails?

### ISSUE THREAD

**Issue by myJamong** [cockpit-project/cockpit#15003]
Page: 

Hi, I installed cockpit 195 itegrated in foreman on CentOS 7.
I was trying to find any notification features but could not find any.
I wonder if there is a feature for notification with e-mail or SMS when there is any critical problems in the hosts monitoring.

If not I think it's critical for a monitoring tool not having notification features.
I feel that cockpit is great with foreman and I really need this type of functionality!

Please reply.

**Comment by marusak** [comment]
There is nothing like that. Some kind of monitoring and notifications have been also suggested in https://github.com/cockpit-project/cockpit/issues/14083 and https://github.com/cockpit-project/cockpit/issues/11437 .

I don't think that Cockpit should be responsible for sending emails (sms, how would one do that?) as once you log out of Cockpit it does not leave anything running on the system. Of course, Cockpit can be used to setup some utility, that would do such monitoring. And that in my view is the main goal of Cockpit - to provide easy access to utilities that already exist and make it easy to use from comfort of GUI in your browser.

There are many utilities that can monitor storage usage for you and send you emails. There could be cockpit plugin for these apps to make them easier to user and to set up. Such plugin can be created by anyone. Cockpit team provides [starter-kit](https://github.com/cockpit-project/starter-kit) which makes it very easy to create a new cockpit plugin.

Also there are some full solutions with nice GUIs and such. One of them is for example https://www.nagios.org/
