### ISSUE TITLE
How to fix 404?

### ISSUE THREAD

**Issue by vhood** [cockpit-project/cockpit#15004]
CentOS 8, no domain, no SSL sertificate.  
I want to serve cockpit from a custom port and a subdirectory,  
for example:  `http://192.168.0.123:2020/example/` (I don't use /cockpit+ path)

<details>
<summary>cockpit.conf</summary>
<summary>

```
[WebService]
Origins = http://192.168.0.123:2020 wss://192.168.0.123:2020
UrlRoot = /example
AllowUnencrypted = true

[Session]
IdleTimeout = 120
```
</summary>
</details>
<details>
<summary>nginx.conf server</summary>
<summary>

```
server {
    listen 2020;

    error_page 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 421 422 423 424 425 426 428 429 431 451 500 501 502 503 504 505 506 507 508 510 511 /;
    location / {
        root /srv/noindex; #redirect to google.com
    }

    # Cockpit
    location ^~ /example/ {
        # Required to proxy the connection to Cockpit
        proxy_pass https://127.0.0.1:9090/example/;
        proxy_set_header Host $host:2020;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Required for web sockets to function
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Pass ETag header from Cockpit to clients.
        # See: https://github.com/cockpit-project/cockpit/issues/5239
        gzip off;
    }
```
</summary>
</details>

My configs don't work
![404](https://user-images.githubusercontent.com/55533574/101051118-2cec9200-3596-11eb-8885-44db7fdc0664.png)
![fonts404](https://user-images.githubusercontent.com/55533574/101051121-2d852880-3596-11eb-981f-532b02caf928.png)

cockpit and cocpit.socket services are `active (running)`. If remove the cockpit.conf, cockpit works at the default address `192.168.0.123:9090`

How can I fix this 404?

**Comment by KKoukiou** [comment]
You can see how to change the default TCP port here https://cockpit-project.org/guide/latest/listen.html#listen-systemd
For the subdirectory customization I am not aware of a solution.

**Comment by vhood** [comment]
@KKoukiou I proxying my custom port to the default cockpit port, isn't that supposed to work?

However, I have other apps on this port in their directories, so if i change the default cockpit port i guess conflicts may occur.  
I already configured this before, but then there was a domain with an SSL certificate and nginx was configured with ssl. Unfortunately, I no longer have access to that project to see the confings.

**Comment by martinpitt** [comment]
Stale, and nothing actionable here.
