### ISSUE TITLE
Motd does not work well with socket-activated cockpit.service

### ISSUE THREAD

**Issue by keszybz** [cockpit-project/cockpit#15025]
I only use cockpit occasionally, so I'd like to have the socket enabled, but not the service.
This works just fine, when I connect to the socket, the service is automatically started as expected.
But the motd is misleading:
```
Activate the web console with: systemctl enable --now cockpit.socket
```
In fact that is a noop, the .socket unit is already enabled and active.

Thus, I'd propose two things:
1. adjust motd generation to only look at the state of the socket unit (since this is what matters to be able to reach the service).
2. only enable the socket in default installation, not the service (to save resources on machines where cockpit isn't used all the time, i.e. probably the great majority).

This is with cockpit-232-1.fc34.x86_64.

**Comment by allisonkarlitskaya** [comment]
hello,

The behaviour you describe is the current intended behaviour.  You'll notice in the message, in fact, that the suggested method to enable cockpit is to enable the socket unit, not the service.

Once the socket is activated you should stop seeing that message and it should be replaced by a different one (telling you the URL to go to to access the service).  If not, we have a bug.

Can you please share the output of `ls -l /run/cockpit` with me, both with the socket activated and deactivated?  Thank you!

**Comment by keszybz** [comment]
```console
$ ls -l /run/cockpit/
total 4
-rw-r--r--. 1 root root  76 Dec  1 08:33 active.motd
lrwxrwxrwx. 1 root root  37 Dec  1 08:34 motd -> /usr/share/cockpit/motd/inactive.motd
drwxr-xr-x. 2 root root 120 Dec  9 10:03 wsinstance
```

And when I do `sudo systemctl stop cockpit.socket && sudo systemctl start cockpit.socket`, I get:
```console
$ ls -l /run/cockpit/
total 4
-rw-r--r--. 1 root root  76 Dec  9 14:41 active.motd
lrwxrwxrwx. 1 root root  11 Dec  9 14:41 motd -> active.motd
drwxr-xr-x. 2 root root 120 Dec  9 10:03 wsinstance
```

Hmm, and after reboot, `active.motd` is active. Strange. Let's assume I messed something up.
