### ISSUE TITLE
How to secure cockpit installation? SSH Key?

### ISSUE THREAD

**Issue by xelayz** [cockpit-project/cockpit#15035]
Hello. I enabled the option thats I can just login with a ssh key to my server, no pass auth allowed.
Now I can login via cockpit with root und password and can do commands via shell. This is a big security risc..

How can I secure my installation?

Thanks.

**Comment by marusak** [comment]
Sorry, I don't understand what is the problem. You mean you disabled password auth to your server but you can use cockpit with password to log into your server? If so, then you can [disable it](https://github.com/cockpit-project/cockpit/blob/master/doc/authentication.md#actions).

**Comment by xelayz** [comment]
> 
> 
> Sorry, I don't understand what is the problem. You mean you disabled password auth to your server but you can use cockpit with password to log into your server? If so, then you can [disable it](https://github.com/cockpit-project/cockpit/blob/master/doc/authentication.md#actions).

Thank you for your answer. No I disabled the remote Login. So now it is only possible to access the webinterface via localhost. So I need to setup a VPN connection to access the webinterface again, correct?

**Comment by martinpitt** [comment]
> No I disabled the remote Login. 

Did you mean "Now I disabled.."?

If you configured your server that way, I suggest to *not* install cockpit-ws on that server, but instead install it somewhere else (like your laptop) and use the login page's "Connect to:" option to access the cockpit UI on your server. That will then use SSH, and thus works with SSH keys and is just as secure as using SSH with a terminal. (We call this "bastion host" mode).

See [the docs](https://cockpit-project.org/guide/latest/authentication.html#secondary-auth) for some details.

**Comment by xelayz** [comment]
> 
> 
> > No I disabled the remote Login.
> 
> Did you mean "Now I disabled.."?
> 
> If you configured your server that way, I suggest to _not_ install cockpit-ws on that server, but instead install it somewhere else (like your laptop) and use the login page's "Connect to:" option to access the cockpit UI on your server. That will then use SSH, and thus works with SSH keys and is just as secure as using SSH with a terminal. (We call this "bastion host" mode).
> 
> See [the docs](https://cockpit-project.org/guide/latest/authentication.html#secondary-auth) for some details.

Oh, great! Thank you very much for your help. I will try this.

**Comment by discapes** [comment]
Could you post the whole command and output?

**Comment by martinpitt** [comment]
There is no need to use port 22 -- but if you use a different one, you need to specify it in the "Connect to:" input line or the "Add host" dialog in cockpit.

I just double-checked this with current Cockpit 250. On the shell, I get a host key prompt:
```
❱❱❱ ssh -p 2201 root@127.0.0.2
The authenticity of host '[127.0.0.2]:2201 ([127.0.0.2]:2201)' can't be established.
ED25519 key fingerprint is SHA256:lLamodB8dm7YvcWXZtMp6a6fGueEbSABa2LZpDAjkMo.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? n
```

In cockpit's login:

![image](https://user-images.githubusercontent.com/200109/128603597-e4b018fe-1ad6-4fb7-9420-6416e51931dc.png)

When I click on Login ("Anmelden", sorry, that is in German), I get this screen:

![image](https://user-images.githubusercontent.com/200109/128603553-70c7aa01-2e9d-4c45-ac63-df390ff45c77.png)


This means "Accept key and continue". This works, and I get a cockpit session.

This was fixed in [cockpit 235](https://cockpit-project.org/blog/cockpit-235.html).

**Comment by xelayz** [comment]
@martinpitt Could you please delete this issue permanently? Would be very grateful.

**Comment by martinpitt** [comment]
@xelayz OK, will do.
