### ISSUE TITLE
Some of the Menus Don't Appear

### ISSUE THREAD

**Issue by serdarwork** [cockpit-project/cockpit#15040]
Cockpit version: 215
OS: Ubuntu 20.04 x64 (Hetzner Cloud)

Hi,

Today, I installed Cockpit by running the "sudo apt install cockpit" command on my minimal server which is LEMP stack. Everything seems working properly but the thing is that, menus like "**Storage**", "**Networking**", "**Software Updates**" don't appear.

I've read the documentations on the cockpit-project.com and installed udisks2 package for the Storage, NetworkManager for the Networking features. However, it didn't help at all. Also, the "Health" field on the homepage looks blank.

[![Screen-Shot-2020-12-13-at-01.21.45a9e6d86175dac4a0.png](https://s3.imgbu.com/file/imgbucom-s/2020/12/13/Screen-Shot-2020-12-13-at-01.21.45a9e6d86175dac4a0.png)](https://imgbu.com/i/Rn9Dv)

According to the screenshot, below guide shows the same installation method.
https://computingforgeeks.com/manage-ubuntu-linux-with-cockpit-web-console/

Please kindly help me, what should I do to make my cockpit fully working?

Kind regards,
Serdar

**EDIT:** Storage has been installed with `sudo apt install cockpit-storaged` command. Still no idea about the others.

**Comment by marusak** [comment]
> Storage has been installed with sudo apt install cockpit-storaged command. Still no idea about the others.

`cockpit-networkmanager` and `cockpit-packagekit`.
Once you have `cockpit-packagekit` it actually helps with discovering new packages.
Also your package manager should be able to help you look for possible packages. I don't use `apt` but `dnf` can use tab-completion `sudo dnf install cockpit-<tab><tab>` and it lists all available cockpit plugins. Or just `sudo dnf search cockpit`.
