### ISSUE TITLE
Question about using latest releases (e.g. COPR etc)

### ISSUE THREAD

**Issue by digitalformula** [cockpit-project/cockpit#15051]
Page: N/A

Sorry for logging on the main repo but I'm not sure where else to do this.

I run CentOS 8 and Cockpit via COPR - that all works well.

With CentOS migrating everything into the stream branches, I'm pretty sure I'll be moving off CentOS shortly, probably to Ubuntu.  The Cockpit docs for installation just say to use `apt-get` which is fine and I understand that, but the latest versions of Cockpit are never in the main repos.

Is there a COPR equivalent for Ubuntu-based distros?  I see 234 just came out and the announcement post links to the "for your Linux system" page, but that just says to use `apt-get`.  That only installs up to 215, which is pretty old now.

Thanks

**Comment by digitalformula** [comment]
Actually I just found Cockpit later versions can be installed via backports:

`sudo apt install cockpit/focal-backports`

Is that an acceptable method?

**Comment by marusak** [comment]
> Is that an acceptable method?

Using backports is the correct way how to get new versions in ubuntu. That is something like `updates` repository in rhel/fedora/centos world.

> Asking as running that on Ubuntu 20.04 just throws a ton of 404s.

How do you mean? Cockpit from backports is not working?

**Comment by digitalformula** [comment]
> > Is that an acceptable method?
> 
> Using backports is the correct way how to get new versions in ubuntu. That is something like `updates` repository in rhel/fedora/centos world.

Ok, great.  Thanks for the clarifying.

> 
> > Asking as running that on Ubuntu 20.04 just throws a ton of 404s.
> 
> How do you mean? Cockpit from backports is not working?

When I run `sudo apt install cockpit/focal-backports` APT looks for version 231 for whatever reason.  However, if I look on [the server it is trying to download from](http://au.archive.ubuntu.com/ubuntu/pool/universe/c/cockpit/), none of the files APT tries to get are there.  Cockpit 233 is there and I've managed to download the .deb files to get Cockpit working, but using APT doesn't work due to those 404s.  Apologies for not explaining that very well before.

**Comment by marusak** [comment]
> but using APT doesn't work due to those 404s. 

Sorry, but cannot help you with `apt` issues. Please reach out to ubuntu channels, hopefully they will be able to help you.

**Comment by digitalformula** [comment]
> > but using APT doesn't work due to those 404s.
> 
> Sorry, but cannot help you with `apt` issues. Please reach out to ubuntu channels, hopefully they will be able to help you.

No that's OK - I wasn't asking for help with those.  Was just wondering if using backports is the "supported" method.  Errors on the mirrors aren't anyone's responsibility except mirror owners.  :+1:
