### ISSUE TITLE
Use PF4's new time picker

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15055]
We're using a time selector in a few places in Cockpit. I suggest we consider PatternFly's new basic time picker:

https://github.com/patternfly/patternfly-org/blob/master/release-highlights/release-highlights-2020.16/release-highlights.md#basic-time-picker

1. The most obvious place I can think of is in the Software Updates automatic updates scheduling. 
2. Additionally, I think we have a scheduled time to reboot too (not the X minutes from now, but at a certain specific time).
3. This might be useful for the journal as well.
4. Performance page may also be a candidate for this widget.

Am I forgetting anything else where you need to select a specific time?

**Comment by marusak** [comment]
It is documented here: https://www.patternfly.org/v4/components/time-picker

There are actually 3 places where this applies:
1. Shutdown/Restart: `pkg/lib/cockpit-components-shutdown.jsx`
2. Automatic updates: pkg/packagekit/autoupdates.jsx
3. Create timers: pkg/systemd/services/timer-dialog.jsx
