### ISSUE TITLE
Ubuntu 20.04 - MIME type issue

### ISSUE THREAD

**Issue by serdarwork** [cockpit-project/cockpit#15050]
OS: **Ubuntu 20.04**
Cockpit version: **233** (Proxied by **Nginx**)

1-) I was using Cockpit 215 on my Ubuntu server. Then I upgraded it to 233 by binding below command:
`apt install -t focal-backports $(dpkg-query -W | awk '/cockpit/ {print $1}')`

Although everything works properly after the upgrade, below console error occurred:
`Refused to apply style from 'https://cockpit.example.com/cockpit/$59432219106b97ede0c09c9ef015d8e2ea8739d8393a7486cec46ab0baeeb144/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

--------------

2-) **(SOLVED, see edit)** I've installed networking by running this command:
`apt install cockpit-networkmanager/focal-backports`

When I go to the Services menu, it shows duplicated Network Managers. Please see below:
[![Screen-Shot-2020-12-16-at-03.31.46423492f3c250b02f.png](https://s3.imgbu.com/file/imgbucom-s/2020/12/16/Screen-Shot-2020-12-16-at-03.31.46423492f3c250b02f.png)](https://imgbu.com/i/RGwvC)

If I disable one of them, the other one will automatically be disabled. The same log information appears on both services. That's why I call them as duplicated.

**EDIT:** I should have made more research regarding the second issue. NetworkManager and network-manager are the same processes. Credit: https://askubuntu.com/questions/919609/whats-the-difference-between-network-manager-service-and-networkmanager-service

--------------

To fix the issues, I did;
- Remove/Purge cockpit-networkmanager completely and reinstall it again.
- Server restart

Thank you for all of your helps and of course this brilliant software!

Kind regards,
Serdar

**Comment by marusak** [comment]
>  Although everything works properly after the upgrade, below console error occurred:

That is unrelated. We have reports about this and we know about this but it does not affect the functionality in any way.

> it shows duplicated Network Managers

As you figured out, these are symlinked. We show them purposefully. See commit 696585556
