### ISSUE TITLE
After selecting an automatic update type, card flips back to "No updates"

### ISSUE THREAD

**Issue by AdamWill** [cockpit-project/cockpit#15060]
Cockpit version: 234
OS: Fedora
Page: Software Updates

In Cockpit 234 with the rewrite of the updates page - d99128c70f01f2fbdc6d9e633c789c5dacabd5a5 - the openQA test of automatic updates has started failing quite often. What seems to happen is that when it sees the "Automatic updates" screen and clicks "All updates", the card *very* briefly shows correctly with "All updates" selected and the "This host will reboot after updates are installed" note, but then flips back to showing "No updates". This doesn't happen every time - sometimes it works OK - but it's happening quite often. Most likely some kind of race in the javascript?

You can see this in [this video](https://www.happyassassin.net/temp/cockpit234autoupdates.ogv) around the 0:29 mark if you carefully scroll the video - the correct state appears only for a very brief time. I don't know exactly how much *real* time the correct state was visible for because openQA videos are stitched together from screenshots, they aren't real time, but it wasn't more than a second according to the timestamps in the openQA system.

Steps to reproduce

1. Click Software Updates
2. Click "Edit"
3. Agree to install dnf-automatic
4. Click All updates

Since openQA is automated it may be doing something faster than a human typically would or could and that may be significant. Not sure. I haven't tried reproducing this manually yet.

**Comment by AdamWill** [comment]
(hum, my web host isn't serving the right MIME type for the video, apparently. You can just wget it and play it, it should be fine.)

**Comment by AdamWill** [comment]
to be specific on the timing front, the test will click the radio button quite soon after it appears on screen, maybe within a second or less.

**Comment by martinpitt** [comment]
The last three runs all seem successful: https://openqa.fedoraproject.org/tests/1646298 https://openqa.fedoraproject.org/tests/1623202 https://openqa.fedoraproject.org/tests/1689236 

@AdamWill , do you have a hack for that somewhere, or did that magically fix itself?

**Comment by AdamWill** [comment]
Best as I can tell it must have got magically fixed along the way. I can't find any workaround we ever committed for this or anything like that.

**Comment by martinpitt** [comment]
Cool, thanks for confirming! Possibly fixed by commit dfa14b9b1e or 403f4353324ea99 -- let's not waste more time on it then.
