### ISSUE TITLE
Administrative access to remote servers when using SSH keys to login

### ISSUE THREAD

**Issue by 0ranki** [cockpit-project/cockpit#15067]
Cockpit version: 233.1
OS: Fedora 33 ( and Ubuntu 20.04.1 with Cockpit 215-1 )
Page: any that require administrative privileges

When adding remote hosts and using SSH keys to authenticate, there seems to be no way to gain administrative privileges to reboot or do anything to the remote host. Even editing the user that is used as login in cockpit cannot be edited.

Cockpit tries to start `cockpit-bridge --privileged` first with `pkexec` and then with `sudo`, but since no password is provided the elevation attempt fails and outputs errors to journal.

This is even though the passwords are the same on both hosts (from Fedora 33 to Ubuntu 20.04.1, also from F33 to Centos 8.2)
and the user is in the wheel group (Fedora/CentOS) or sudo group (Ubuntu)

I found a previous closed issue ( #10500 ) that states the 3 incorrect password attempt issue is fixed in version 219, but how does the acquiring of admin privileges work when there's no password involved?

Journal after logging in: [pastebin](https://pastebin.com/g6epNVw8)

I'll be happy to provide more information/logs if necessary.

Steps to reproduce

1. Log in to localhost Cockpit Web Console
2. Add a remote host that you login to using SSH keys.
3. Try to do anything that requires privileges (reboot, add user etc)

**Comment by martinpitt** [comment]
I assume that the remote host you are logging into via ssh is the one on Ubuntu 20.04 with Cockpit 215? This use case was indeed [fixed in version 219](https://cockpit-project.org/blog/cockpit-219.html), see the description and video for how this works now. Hence I recommend to upgrade Cockpit to the `focal-backports` version. We fully support and test this. See https://help.ubuntu.com/community/UbuntuBackports for details, but the gist of it should be `sudo apt install -t focal-backports cockpit`.

**Comment by 0ranki** [comment]
Thank you for a quick response! I did not understand the Ubuntu backports system at all before, sorry about that.

So, to be clear, I have a laptop running Fedora 33, which I would like to use to control a couple of servers via Cockpit. At the moment there are Ubuntu 20.04.1 and CentOS 8.2 hosts.

I installed the latest versions of Cockpit to the remote hosts after your reply. Ubuntu host is now running version 233 from `focal-backports` and CentOS has 234 from `@cockpit/cockpit-preview` COPR repo. Before installing the newer versions I removed the older versions along with their config files.

Updating solved the issue of not being able to get administrative access at all, but the problem with 3 incorrect `sudo` password attempts  persists.

What I did:
1. Added remote hosts to Cockpit, using `Host` aliases defined in `~/.ssh/config` and SSH keys. (Password logins are disabled in `sshd` configs)
2. Turned off administrative privileges on remote hosts
3. Logged out of Cockpit
4. Logged back in, no administrative privileges enabled on any hosts (but this time it is possible, though!)

While logging back in, journals are as follows:
[Ubuntu, Cockpit 233](https://pastebin.com/qdDcBw4v)
[CentOS, Cockpit 234](https://pastebin.com/g1TXUMYa)

I'm assuming I probably missed something on my setup, maybe I'm supposed to add the user to `sudoers` with the `NOPASSWD` line for `cockpit-bridge`?

**Comment by martinpitt** [comment]
The three failed sudo attempts are only a cosmetical failure now. I thought that this was fixed already, but @mvollmer, can you please have a look? @0ranki , please don't expect an answer before January though, everyone is on vacation.

> I'm supposed to add the user to sudoers with the NOPASSWD line for cockpit-bridge?

No, no, don't do anything like that! First, there is no `cockpit-bridge` user or anything cockpit specific on the remote machine. It's really just an ssh  session for *your* user that happens to run the cockpit-bridge binary instead of bash.

**Comment by 0ranki** [comment]
> please don't expect an answer before January though, everyone is on vacation.
Of course, I'm really grateful of you taking the time to look at this!

If there's anything I can do to help, I'm happy to do it.

**Comment by mvollmer** [comment]
>  I thought that this was fixed already, but @mvollmer, can you please have a look?

Yeah, this shouldn't happen but I can reproduce it.  I'll investigate more.

When Cockpit connects to a remote machine over ssh, it tells the remote machine whether or not to open a privileged session via sudo.  By default, it will say "yes".  But if sudo fails, Cockpit should say "no" the next time.

Note that we can't make the assumption that if Cockpit doesn't have a password to try (because SSH login is done with keys), it shouldn't try sudo.  Sudo might succeed without password.

**Comment by mvollmer** [comment]
> But if sudo fails, Cockpit should say "no" the next time.

And the bug is that this change doesn't seem to happen.  Cockpit always says "yes".

**Comment by 0ranki** [comment]
> And the bug is that this change doesn't seem to happen. Cockpit always says "yes".

I can add to the issue that Cockpit tries to escalate privileges every time you enter a page that requires admin privileges, like software updates.

So when logging in, I get the `sudo: a password is required` and 3 incorrect attemts, and after that if I move to the software updates page, I get the 3 incorrect attempts again multiple times.

I don't have logs at the moment, but that is also reproducable accross several reboots of systems on both ends.

**Comment by mvollmer** [comment]
> > But if sudo fails, Cockpit should say "no" the next time.
> 
> And the bug is that this change doesn't seem to happen. Cockpit always says "yes".

Here is a fix for that: https://github.com/cockpit-project/cockpit/pull/15131

However, sudo is still run more often than we might like... For example, if you connect to a remote machine without password (via SSH keys), and then gain admin privs  in the remote session by typing you password, Cockpit will remember that you want to be admin on that machine.  On the next login, Cockpit will again try to run sudo, and fail noisily.

Maybe Cockpit could learn somehow on which machines sudo works non-interactively...

**Comment by mvollmer** [comment]
> I can add to the issue that Cockpit tries to escalate privileges every time you enter a page that requires admin privileges, like software updates.

Hmm, I can not reproduce this.  Here Cockpit only tries to escalate once, immediately after logging into the remote host.  Also, there is only one run of `sudo -v -n`.

**Comment by martinpitt** [comment]
@0ranki , is there still anything left here? We test gaining sudo privileges on remote SSH hosts on all operating systems, including Ubuntu 20.04, and it works in general.

**Comment by 0ranki** [comment]
@martinpitt sorry for taking so long to reply, I haven't had much time to test lately and I haven't had the need to use Cockpit as much as before.

At least the privilege escalation attempt every time when entering a page requiring privileges doesn't happen anymore (remote connection from a Fedora 34 host running Cockpit 249 -> RHEL8 host with Cockpit 238.2). The three failed sudo attempts on login still happen though. Using key authentication.

The original issue was about not being able to gain administrative privileges, and that works now so I think this issue can be closed.
