### ISSUE TITLE
how do you login to cockpit remotely. I've tried the external ip (https://external_ip:9090) but doesn't work

### ISSUE THREAD

**Issue by vapouryh** [cockpit-project/cockpit#15086]
Cockpit version: latest (215-1)
OS:
Page: 

how do you login to cockpit remotely. I've tried the external ip (https://external_ip:9090) but doesn't work

Steps to reproduce

1.
2.
3.

**Comment by martinpitt** [comment]
Maybe you need to open the port in the firewall? Hard to say with zero data. Does cockpit work on the same host? (localhost:9090) Can you SSH to the external_ip host? Does it run a firewall? What does the journal say on a connection attempt? What does "doesn't work" mean exactly, what is the error message?

**Comment by vapouryh** [comment]
> Maybe you need to open the port in the firewall? Hard to say with zero data. Does cockpit work on the same host? (localhost:9090) Can you SSH to the external_ip host? Does it run a firewall? What does the journal say on a connection attempt? What does "doesn't work" mean exactly, what is the error message?

I've fixed it, but thank you. I needed to port forward on my router.
