### ISSUE TITLE
Cockpit for Ubuntu is Old

### ISSUE THREAD

**Issue by jvaccaro** [cockpit-project/cockpit#15081]
Cockpit version: 164
OS: Ubuntu 20.04 LTS
Page: 

Why is the version of Cockpit in the Ubuntu repository (v164) 70 releases behind what the blog says the current release is (v234)

Steps to reproduce

1. Install Cockpit on a Ubuntu 20.04 LTS server
2. use _sudo apt-get install cockpit_

![ksnip_20201231-221750](https://user-images.githubusercontent.com/153742/103433027-f6fff500-4bb7-11eb-8f4a-1b9790076b1d.png)

**Comment by martinpitt** [comment]
> OS: Ubuntu 20.04 LTS

You got that wrong, this is for 18.04 LTS. 20.04 LTS has cockpit 227 in the release.

If you want a newer version, please install it from [backports](https://help.ubuntu.com/community/UbuntuBackports). See the [available releases](https://launchpad.net/ubuntu/+source/cockpit) for which cockpit version is contained in which ubuntu release/suite.

**Comment by mikehearn** [comment]
FWIW:

```
root@hq /etc/apt/sources.list.d # cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
root@hq /etc/apt/sources.list.d # dpkg -s cockpit|grep Version
Version: 215-1
```

215, not 227. Backports doesn't help, it appears there are no Cockpit backports for Ubuntu.

**Comment by mikehearn** [comment]
I am wrong! The behaviour of Ubuntu changed at some point and like the schoolboy noob that I am, I didn't know that. The magic incantation for Ubuntu LTS in 2021 is (as root):

```
echo "deb http://archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse" >/etc/apt/sources.list.d/backports.list
apt update
apt install cockpit/focal-updates
```

Replace "focal" with the codename of your release of course if it's not LTS. *Note the apt install command is different to normal*. If you do things in the normal way it'll just tell you you're up to date, even though you're not.

It would be nice if the Cockpit docs told you how to do this, because the whole reason people want to use Cockpit in the first place is so they can _avoid_ this exact kind of UNIX CLI usability problem.

**Comment by martinpitt** [comment]
`cockpit/focal-backports` is *not* the way to do it, you want `apt install -t focal-backports cockpit` (or "update") to also get  dependencies from backports.

**Comment by mikehearn** [comment]
OK, thanks. Can you update the Cockpit web page to tell users this? The installation page gives incorrect instructions:

https://cockpit-project.org/running.html#ubuntu

I followed them and didn't get the latest version available to me. Then I tried to figure out the right command and found one that appears to work, but you're saying, actually doesn't fully install it? How is that possible? If the backported Cockpit package depends on a newer version than available in main surely that would result in resolution failure? The Ubuntu page gives both commands as "two options" without saying which is better, so I picked the first.

**Comment by martinpitt** [comment]
Yes, that's what I'm wondering about.. as documented ("will resolve dependencies from main") `apt install cockpit/focal-backports` should not work, as the cockpit version XXX package depends on e. g. cockpit-system >= XXX. So *that* should have failed, or maybe backports are actually enabled anyway for that case.
