### ISSUE TITLE
Correct PPA for Ubuntu 20.04 and Ilk

### ISSUE THREAD

**Issue by jvaccaro** [cockpit-project/cockpit#15080]
Cockpit version: 164
OS: Ubuntu 20.04 LTS
Page: 

The Ubuntu PPA url is broken:
sudo add-apt-repository ppa:cockpit-project/cockpit
Outputs:
_Cannot add PPA: 'ppa:~cockpit-project/ubuntu/cockpit'.
The user named '~cockpit-project' has no PPA named 'ubuntu/cockpit'_

Steps to reproduce

1. Run the command **sudo add-apt-repository ppa:cockpit-project/cockpit**
2.
3.

**Comment by martinpitt** [comment]
The PPA got obsoleted long ago, in favor of uploading current cockpit versions straight to the official [backports](https://help.ubuntu.com/community/UbuntuBackports).

**Comment by dlong500** [comment]
@martinpitt How often do the current versions get uploaded to backports?  Ubuntu Jammy (22.04 LTS) doesn't appear to have any cockpit versions available in jammy-backports.  The non-backports version (264) is not super old but still nearly 4 months out of date.

**Comment by martinpitt** [comment]
@dlong500 : Thanks for the reminder. These were blocked for a while, and then I forgot to do them. I updated 22.04 and 21.10 backport now.

**Comment by dlong500** [comment]
@martinpitt Thanks for the quick response.  I see the update in backports for the Ubuntu versions you mentioned (22.04 and 21.10), but what about earlier Ubuntu versions?  Is there a typical schedule for updating the backports releases and does it differ for older versions of Ubuntu?  Sorry to pester; just trying to figure out what to expect as the 22.04 release ages over the years.

**Comment by martinpitt** [comment]
These are the only supported Ubuntu releases by us for now. We normally only support the latest LTS and latest regular release. As both are the same right now, we still test the previous one (21.10) ATM, but as that will be EOL soon, we'll soon stop that. Normally I do the backports shortly after they landed in the development series, roughly every two weeks. Sometimes I forget, though.
