### ISSUE TITLE
cannot connect to remote cockpit

### ISSUE THREAD

**Issue by carlfost** [cockpit-project/cockpit#15083]
A new installation of cockpit starts and stopped immediately on ubuntu 20.4. 
Cockpit version: 233-1~ubuntu20.04
OS: Linux ubuntu20.04
Page: 

I tried port 9090 and 9091, but no change.
root@server2:/etc/systemd/system/cockpit.socket.d# **service cockpit restart**
root@server2:/etc/systemd/system/cockpit.socket.d# **service cockpit status**
● cockpit.service - Cockpit Web Service
     Loaded: loaded (/lib/systemd/system/cockpit.service; static; vendor preset: enabled)
     **Active: active (running)** since Fri 2021-01-01 17:07:32 UTC; 4s ago
TriggeredBy: ● cockpit.socket
       Docs: man:cockpit-ws(8)
    Process: 4312 ExecStartPre=/usr/sbin/remotectl certificate --ensure --user=root --group=cockpit-ws --selinux-type= (code=exited, status=0/SUCCESS)
   Main PID: 4313 (cockpit-tls)
      Tasks: 1 (limit: 1166)
     Memory: 776.0K
     CGroup: /system.slice/cockpit.service
             └─4313 /usr/lib/cockpit/cockpit-tls

Jan 01 17:07:32 server2 systemd[1]: Starting Cockpit Web Service...
Jan 01 17:07:32 server2 systemd[1]: Started Cockpit Web Service.

root@server2:/etc/systemd/system/cockpit.socket.d# **service cockpit status**
● cockpit.service - Cockpit Web Service
     Loaded: loaded (/lib/systemd/system/cockpit.service; static; vendor preset: enabled)
     **Active: inactive (dead)** since Fri 2021-01-01 17:09:02 UTC; 1min 0s ago
TriggeredBy: ● cockpit.socket
       Docs: man:cockpit-ws(8)
    Process: 4312 ExecStartPre=/usr/sbin/remotectl certificate --ensure --user=root --group=cockpit-ws --selinux-type= (code=exited, status=0/SUCCESS)
    Process: 4313 ExecStart=/usr/lib/cockpit/cockpit-tls (code=exited, status=0/SUCCESS)
   Main PID: 4313 (code=exited, status=0/SUCCESS)

Jan 01 17:07:32 server2 systemd[1]: Starting Cockpit Web Service...
Jan 01 17:07:32 server2 systemd[1]: Started Cockpit Web Service.
Jan 01 17:09:02 server2 systemd[1]: cockpit.service: Succeeded.

FROM SYSLOG
Jan  1 17:09:02 server2 systemd[1]: cockpit.service: Succeeded.
Jan  1 17:09:02 server2 systemd[1]: cockpit-wsinstance-http-redirect.socket: Succeeded.
Jan  1 17:09:02 server2 systemd[1]: Closed Socket for Cockpit Web Service http-redirect instance.
Jan  1 17:09:02 server2 systemd[1]: cockpit-wsinstance-http.socket: Succeeded.
Jan  1 17:09:02 server2 systemd[1]: Closed Socket for Cockpit Web Service http instance.
Jan  1 17:09:02 server2 systemd[1]: cockpit-wsinstance-https-factory.socket: Succeeded.
Jan  1 17:09:02 server2 systemd[1]: Closed Socket for Cockpit Web Service https instance factory.

Steps to reproduce

1. Install the package: apt install cockpit
2. open the firewall port (9090 or 9091 for testing)
3. Launch the Chrome Browser http://35.232.27.61:9090/

Response: This site can’t be reached35.232.27.61 took too long to respond

**Comment by martinpitt** [comment]
cockpit.service is supposed to stop itself again after a minute or two of being idle. It is socket activated, so the only thing that should keep running is `systemctl status cockpit.socket`. So there is nothing wrong in all of the system logs.

If you ssh to that system and try `curl http://localhost:9090`, do you get some HTML stuff? (the login page). If that fails also, there is indeed something wrong with the service, and capturing `journalctl -f` during the curl command would be very useful.

If that works, then it's more likely that the port gets blocked by something in between, like a firewall?

**Comment by carlfost** [comment]
I am using port 9091 and when I send curl http://localhost:9091 from the ssh terminal, I got back some html codes, but when I tested it from outside of the server network using the external IP address, it failed to connect.

Since it is a new server, I turned off firewall, and test it, but it still failed.  So I am pointing to something between my external network and the server network that is blocking 9090 or 9091.

**Comment by carlfost** [comment]
It seems like some external firewall is blocking port 9090 and 9091

**Comment by Nisargshah18** [comment]
How did you fix it?

**Comment by shubhamkumar13** [comment]
@Nisargshah18 on ubuntu ufw blocks it often `sudo ufw allow <port number>` might help

**Comment by jon-dearaujo** [comment]
> [@Nisargshah18](https://github.com/Nisargshah18) on ubuntu ufw blocks it often `sudo ufw allow <port number>` might help

Managed to get back my access to Cockpit after updating the firewall. Been messing with it early this week for another service, so I might have blocked everything else. Funny thing is that I don't recall enabling it (:9090) ever before. 
Thanks, @shubhamkumar13
