### ISSUE TITLE
Support for modules with custom menu

### ISSUE THREAD

**Issue by flo-mic** [cockpit-project/cockpit#15082]
It would be great if I could use nested menu entries in the navigation.

As example, I have a buch of custom packages. All these packages have are related to web servers so i would like to create a menu entry "Web servers" and when someone click on this it shows the nested items inside the menu.

I tried serval things in the mainfest.json but for me it is not working. Is this feature already there? If not can this be implemented?

**Comment by martinpitt** [comment]
That feature does not exist indeed, you did not miss anything. There is only the `menu` vs. `tools` vs. `dashboard` (Apps) distinction, see https://cockpit-project.org/guide/latest/packages.html#package-manifest . But no subgrouping. The alternative for your case is to have just a single top-level menu entry, and then do the further points inside your own page's menu.

**Comment by marusak** [comment]
As Martin mentioned, this was not yet implemented. When we were doing the big menu redesign we had this in mind. There exists still an interactive demo where this is styled out: https://garrett.github.io/cockpit-mockweb/navigation2/index.html (see 'Demo with menu').

It is not that difficult to write, mostly needs some thinking how we want to support this. For now it is possible to just have submenu in your own module.

**Comment by flo-mic** [comment]
Thanks for your answers i solved it by using modal popups. This makes the page even more responsive so i'm happy with that. 

I will close the issue but it would be cool to have this on the next ui redesign available.
