### ISSUE TITLE
Cannot Login - cockpit-session: bridge program failed: Child process exited with code 1

### ISSUE THREAD

**Issue by gregvis** [cockpit-project/cockpit#15099]
Cockpit version: 188-1
OS: Debian 10 Buster

Cannot login to cockpit - Webpage just shows "Internal error in login process". I don't even see the login prompt. 

journalctl:

Jan 05 21:29:46 nas systemd[1]: Starting Cockpit Web Service...
Jan 05 21:29:46 nas systemd[1]: Started Cockpit Web Service.
Jan 05 21:29:46 nas cockpit-ws[15718]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Jan 05 21:29:46 nas cockpit-ws[15718]: couldn't read from connection: Peer sent fatal TLS alert: Unknown certificate
Jan 05 21:29:47 nas cockpit-ws[15718]: couldn't read from connection: Peer sent fatal TLS alert: Unknown certificate
Jan 05 21:29:47 nas cockpit-ws[15718]: couldn't read from connection: Peer sent fatal TLS alert: Unknown certificate
Jan 05 21:29:47 nas cockpit-ws[15718]: /usr/lib/cockpit/cockpit-session: bridge program failed: Child process exited with code 1
Jan 05 21:29:47 nas cockpit-ws[15718]: couldn't read from connection: Peer sent fatal TLS alert: Unknown certificate
Jan 05 21:29:47 nas cockpit-ws[15718]: couldn't read from connection: Peer sent fatal TLS alert: Unknown certificate

**Comment by martinpitt** [comment]
Seems you may have only cockpit-ws installed, but not cockpit-system and cockpit-bridge?  Is this a local or a remote login?

**Comment by gregvis** [comment]
cockpit-system and cockpit-bridge seem to be installed. 

apt list --installed | grep cockpit

cockpit-bridge/stable,now 188-1 amd64 [installed]
cockpit-dashboard/stable,now 188-1 all [installed,automatic]
cockpit-networkmanager/stable,now 188-1 all [installed,automatic]
cockpit-packagekit/stable,now 188-1 all [installed,automatic]
cockpit-storaged/stable,now 188-1 all [installed,automatic]
cockpit-system/stable,now 188-1 all [installed,automatic]
cockpit-ws/stable,now 188-1 amd64 [installed,automatic]
cockpit/stable,now 188-1 all [installed]

this is a remote login to a headless server. 

I've tried removing and reinstalling cockpit, and still have this issue. It was working for a long time on this system...I'm not sure what changed to break it. 

Is there any way to get more verbose debug messages?

**Comment by martinpitt** [comment]
> this is a remote login to a headless server.

That may not have been entirely clear, sorry. You can talk to the remote cockpit *web server* (like https://your.machine:9090) and then log into that machine -- or you can set a "Connect to:" on the login page to use ssh to log into some other machine. That other machine still needs cockpit-bridge and -system installed.

It's probably best if you attach a screenshot of the error, and `sudo journalctl --since '10 minutes ago'` or so, so that we can see the precise error.

**Comment by gregvis** [comment]
![image](https://user-images.githubusercontent.com/8760745/103790238-ef54ac00-500e-11eb-9ef6-9f943e398d48.png)

I'm trying to talk (from a Windows PC) to the remote cockpit web server (Debian 10 headless) to login. I'm not using the "Connect to" option. 

Here is the journalctl...I still filtered it on cockpit since there is a lot of non cockpit related messages. 

sudo journalctl --since '30 minutes ago' | grep -i cockpit
Jan 06 10:46:11 nas systemd[1]: Starting Cockpit Web Service Socket.
Jan 06 10:46:11 nas systemd[1]: Listening on Cockpit Web Service Socket.
Jan 06 10:46:12 nas systemd[1]: Starting Cockpit motd updater service...
Jan 06 10:46:12 nas systemd[1]: cockpit-motd.service: Succeeded.
Jan 06 10:46:12 nas systemd[1]: Started Cockpit motd updater service.
Jan 06 10:48:29 nas systemd[1]: Starting Cockpit Web Service...
Jan 06 10:48:29 nas systemd[1]: Started Cockpit Web Service.
Jan 06 10:48:29 nas cockpit-ws[6594]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Jan 06 10:48:29 nas cockpit-ws[6594]: couldn't read from connection: Peer sent fatal TLS alert: Unknown certificate
Jan 06 10:48:29 nas cockpit-ws[6594]: couldn't read from connection: Peer sent fatal TLS alert: Unknown certificate
Jan 06 10:48:29 nas cockpit-ws[6594]: couldn't read from connection: Peer sent fatal TLS alert: Unknown certificate
Jan 06 10:48:29 nas cockpit-ws[6594]: couldn't read from connection: Peer sent fatal TLS alert: Unknown certificate
Jan 06 10:48:29 nas cockpit-ws[6594]: /usr/lib/cockpit/cockpit-session: bridge program failed: Child process exited with code 1
Jan 06 10:48:29 nas cockpit-ws[6594]: couldn't read from connection: Peer sent fatal TLS alert: Unknown certificate
Jan 06 10:48:29 nas cockpit-ws[6594]: couldn't read from connection: Peer sent fatal TLS alert: Unknown certificate
Jan 06 10:49:59 nas systemd[1]: cockpit.service: Succeeded.

**Comment by martinpitt** [comment]
Thanks, that clarifies it. Can you please log in as the same user with SSH, and copy&paste the output of `cockpit-bridge --packages`?

**Comment by martinpitt** [comment]
Also, that is a rather old version which did not have commit 2044cde58896 yet. Before that, there could be a number of things going wrong, e.g. if your user used tcsh. It may be worth trying to update to version 229 in [buster-backports](https://backports.debian.org/Instructions/).

**Comment by gregvis** [comment]
Installing 229 fixed it. I can now login. Thank you. 

Here is the cockpit-bridge output from version 188. 

cockpit-bridge --packages
apps: /usr/share/cockpit/apps
base1: /usr/share/cockpit/base1
dashboard: /usr/share/cockpit/dashboard
domain: /usr/share/cockpit/realmd
network: /usr/share/cockpit/networkmanager
performance: /usr/share/cockpit/tuned
shell: /usr/share/cockpit/shell
ssh: /usr/share/cockpit/ssh
storage: /usr/share/cockpit/storaged
system: /usr/share/cockpit/systemd
updates: /usr/share/cockpit/packagekit
users: /usr/share/cockpit/users
checksum = 9e8462c592b2b70162877e2be47835b1c36c166435eb009b6ffc97d9d62aef3a

**Comment by martinpitt** [comment]
Nice, thanks! So let's blame it on commit 2044cde :grin:

**Comment by Evonder** [comment]
I just ran into this issue tonight, been out of town, and am back up and running using buster-backports.

The one issue I am having though is that cockpit-docker is not in [buster-backports](https://packages.debian.org/source/buster-backports/cockpit)

Is there a reason for that, or am I missing something?

**Comment by marusak** [comment]
> cockpit-docker is not in buster-backports

cockpit-docker has been obsoleted. cockpit-podman is replacement.
