### ISSUE TITLE
Creating LUKS encrypted drive fails if /etc/crypttab does not exist

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#15100]
Cockpit version: 234
OS: Fedora 33, RHEL 8.4 (all)
Page:Storage

Until now, all our test VM images have an empty `/etc/crypttab` in the pre-install. However, this is not the case on Fedora/RHEL cloud images, see https://github.com/cockpit-project/bots/pull/1518. If that file does not exist, then creating a new LUKS fs fails.

Steps to reproduce

1. `modprobe scsi_debug dev_size_mb=200`
2. Go to Storage page, select the scsi_debug drive, "Format" button
3. Select "Encrypt data", enter name and mount point

![image](https://user-images.githubusercontent.com/200109/103752004-6ab35f00-5009-11eb-8c0e-5fd9ade5cb3e.png)

`sudo touch /etc/crypttab` avoids this.

I had a quick look at the source, and did not immediately find where cockpit parses crypttab, so the bug may actually be in udisks.

**Comment by mvollmer** [comment]
The error message does indeed come from UDisks2.  I would argue that a missing /etc/crypttab is a bug by itself, if only because of tradition, but it wouldn't hurt to be robust against it.

**Comment by mvollmer** [comment]
Google found me this from 2012: https://bugzilla.redhat.com/show_bug.cgi?id=845826

**Comment by mvollmer** [comment]
Alright, reading some bug reports and especially this

    https://cgit.freedesktop.org/udisks/commit/?id=1f196a9f2f0f9e1d9e4c037f73a3db7fc2958057

I'd now say that UDisks2 is supposed to handle a missing /etc/crypttab.  It needs to create it when writing into it. I have a closer look and file an issue/pr for UDisks2.

**Comment by mvollmer** [comment]
https://github.com/storaged-project/udisks/pull/835

**Comment by martinpitt** [comment]
Thanks @mvollmer!
