### ISSUE TITLE
Avoid running "sudo -v -n" gratuitiously

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#15114]
Cockpit runs "sudo -v -n" to figure out whether a user can gain admin privs via sudo, and adjusts the UI to suit.

However, running sudo like this is treated by sudo itself as a failed attempt, which will at least be logged and might even trigger an email.

I think we should avoid running "sudo -v -n" for this reason. Instead, Cockpit can always assume that the user can get admin privs and let sudo itself explain the details via its error messages.

Unfortunately, we don't capture stderr of the peer bridges. This would need to be fixed first.

**Comment by mvollmer** [comment]
A compromise would be to only run "sudo -v -n" when the "Administrative access" dialog is opened, and not also to determine whether to show a button on the Overview page.

**Comment by martinpitt** [comment]
This got finally fixed in #15293.
