### ISSUE TITLE
Login to cockpit is not possible

### ISSUE THREAD

**Issue by ViacheslavUKR** [cockpit-project/cockpit#15117]
Dear developers, I try to start you system in two different computers, but unfortunately failed. Even after reading your documentation during a hour, even after try to setup different config. Is you try so start your system in any clear OpenSuse or Ubuntu or not? Why login to local computer is so difficult? What minimal config to start in local computer?

![Screenshot from 2021-01-10 05 48 461](https://user-images.githubusercontent.com/20413407/104114003-101b4b00-5308-11eb-8727-f8349190fb32.png)

**Comment by martinpitt** [comment]
I'm afraid we need some more information here:
 * How exactly did you install cockpit? The official OpenSUSE and Ubuntu packages certainly work. Is this a custom install from source perhaps? (Then it's almost surely because you did not install an appropriate PAM config).
 * Do you actually have a user named "admin" on your system? Can you log in to that machine using the same user/password?
 * Please run `sudo journalctl -f` in a terminal, then try to log into Cockpit, and copy&paste the output.

Thanks!

**Comment by ViacheslavUKR** [comment]
Hi, @martinpitt , I have installed from your instruction, from there - https://cockpit-project.org/running.html
Screenshot below contains most of answer for you. Except of course, my account. Account Admin - this is excactly my account to this computer, whoami respond me "admin". Config file after installation has been missing, I add it manually, because I don't understand how you receive name localhost.localdomain of my local computer, why not simple "localhost"? But after I have edit /etc/hosts strange name " localhost.localdomain" has been resolved to my computer. 
What additional info I need to provide? I'm Linux programmer, not user, and can provide you any information.
My initial big goal was be connected my local computer with a lot of servers, but I was failed even in local computer.

![Screenshot from 2021-01-10 21 40 07](https://user-images.githubusercontent.com/20413407/104133525-cd4f8680-538c-11eb-9cdd-3dd44cf0ee1a.png)

**Comment by ViacheslavUKR** [comment]
@martinpitt 
![Screenshot from 2021-01-10 21 57 38](https://user-images.githubusercontent.com/20413407/104133882-02f56f00-538f-11eb-9287-982976395c4c.png)

**Comment by martinpitt** [comment]
Your /etc/cockpit/cockpit.conf is broken, that's what's generating these "couldn't load config file" error messages. You can just delete it, there is nothing useful in there.

However, that's not what is breaking the logins. I just created a cockpit.conf like yours, and I get the above error messages, but I can still log in. Can you please give me the *full* journal from a login attempt? Just filtering for "cockpit" does not suffice, as this is about `unix_chpkwd`, `pam`, etc.

If you don't like the name "localhost" for your machine, you can change it with `hostnamectl` (or on the Cockpit UI once you get there :grin: )

**Comment by marusak** [comment]
@ViacheslavUKR ping

**Comment by martinpitt** [comment]
No response in half a year, closing.
