### ISSUE TITLE
Cannot install cockpit-docker after upgrade on debian buster backports broken dependencies

### ISSUE THREAD

**Issue by Ddataa** [cockpit-project/cockpit#15129]
Cockpit version: xxx
OS: debian buster backports
Page: docker container

after updating my system I noticed that the tab container disappeared
when trying to install I have this error

$ sudo apt install -t buster-backports cockpit-docker
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cockpit-docker : Depends: cockpit-bridge (>= 138) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by marusak** [comment]
cockpit-docker has been obsoleted for a while and in cockpit-228 it has been dropped altogether.
See https://cockpit-project.org/blog/cockpit-228.html

**Comment by Ddataa** [comment]
is cockpit-podman available in buster backports ?

**Comment by martinpitt** [comment]
@Ddataa : No, because https://tracker.debian.org/pkg/libpod is not available in buster-backports. If you want podman on buster, you need to install them from https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman . This is also what GitHub workflows etc. use, they are fairly reliable.
