### ISSUE TITLE
Icon offset override should only apply to icons, not all SVGs

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15132]
We need to class this override:
https://github.com/cockpit-project/cockpit/blob/8ea9d250d99be240c5a27ea77ae9091a57857de6/pkg/lib/patternfly/patternfly-4-overrides.scss#L28-L33

...As we're now using SVGs that are not icons, such as in the performance page, the SVG graphs, etc.

**Comment by garrett** [comment]
Ah, PF4 icons are unclassed SVGs, but have the following attributes:

```
                          height="1em"
                          role="img"
                          width="1em" 
```

Perhaps we should use `svg[height=1em][width=1em][role=img] { vertical-align: -0.125em; }` until we get the proper fix from upstream?

**Comment by KKoukiou** [comment]
There is already a PR upstream for your interest. https://github.com/patternfly/patternfly-react/pull/5275

**Comment by garrett** [comment]
@KKoukiou: Thanks for linking it here!

It isn't ready in a release we can use yet, so I think we still need a fixed workaround until then. Hopefully it won't have to last so long in our codebase.

**Comment by garrett** [comment]
It does apply to all SVGs, but only actually applies to inline SVGs or ones in a table cell. So, basically: it would only affect icons with the incorrect offset anyway. Block SVGs and those inside of a flex or grid (with other specific alignment) actually ignore the vertical-align and are aligned in the flow or as specified (for flex/grid).
