### ISSUE TITLE
Ubuntu 20.04 LTS VMs get stuck at boot (/dev/vda5: clean)

### ISSUE THREAD

**Issue by aptsurfer** [cockpit-project/cockpit#15147]
Cockpit version: 215
OS: Ubuntu 20.04 LTS
Page: Virtual Machines

Installing an Ubuntu 20.04 LTS VM works, but after installation, it gets stuck during boot with this message:
```/dev/vda5: clean, 63320/466944 files, 543263/1866240 blocks```

I tried making several Ubuntu 20.04 LTS VMs, and this issue occurred on all of them. In contrast, a Ubuntu 18.04 LTS VM works after install automatically and boots to completion.

Steps to reproduce (exactly what I did):

1. Create a virtual machine and select Ubuntu 20.04 LTS (Focal Fossa). Select "Run unattended installation" and choose a root password. I have "Immediately Start VM" checked.
2. Wait for Ubuntu to install inside the VM.
3. When the installation is complete, the machine should be shut off. You can start it up again, but it will get stuck during boot with a blinking cursor.

![ubuntu2004_fail_blinking_cursor](https://user-images.githubusercontent.com/69405481/104628787-8f09de00-5690-11eb-8c40-78b7ef28eeb6.png)

**Comment by aptsurfer** [comment]
You can get to a login prompt by sending Ctrl+Alt+F1 to switch to tty1, as Ubuntu 20.04 LTS boots into a different tty by default.

Source: https://askubuntu.com/questions/761031/ubuntu-server-16-04-installs-on-sdc-but-fails-to-boot

Not actually sure how to send Ctrl+Alt+F1 to the VNC viewer yet though, hence the new issue below.

**Comment by fft7ope** [comment]
I am facing similar Issue, not resolve it. can anyone suggest the solution.
![Screenshot 2024-09-25 122513](https://github.com/user-attachments/assets/c1efcaae-b324-42d4-b47a-8bb480ac0fe5)
