### ISSUE TITLE
LetsEncrypt documentation no longer working & some doc improvment suggestions

### ISSUE THREAD

**Issue by tigerblue77** [cockpit-project/cockpit#15140]
Hi there,

thanks for all the good job done to build cockpit !

Today I proxied Cockpit over Apache, I firstly found [this doc](https://github.com/cockpit-project/cockpit/wiki/Cockpit-with-LetsEncrypt) which is very incomplete and seems to use a file that I didn't find on my installation :
> /etc/systemd/system/cockpit.socket.d/listen.conf

But that doesn't matter because secondly, I found [this doc](https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-Apache-with-LetsEncrypt) which is very complete even though it is older. You could just improve it by precising :
- that you can easily generate a let's encrypt certificate using [Cerbot](https://certbot.eff.org/) and following prompted instructions
- that you can extend an existing certificate (for your-domain.com for example) to certify your cockpit subdomain (cockpit.your-domain.com let's say)
- that /etc/cockpit/cockpit.conf file have to be created if it doesn't exists (instead of "Make sure you changed /etc/cockpit/cockpit.conf" because I lossed time searching for it...)
- and replace those commands :
```bash
cat /etc/letsencrypt/live/cockpit.your-domain.com/fullchain.pem >> /etc/cockpit/ws-certs.d/1-my-cert.cert
cat /etc/letsencrypt/live/cockpit.your-domain.com/privkey.pem >> /etc/cockpit/ws-certs.d/1-my-cert.cert
```
by those :
```bash
cat /etc/letsencrypt/live/cockpit.your-domain.com/fullchain.pem > /etc/cockpit/ws-certs.d/1-my-cert.cert
cat /etc/letsencrypt/live/cockpit.your-domain.com/privkey.pem >> /etc/cockpit/ws-certs.d/1-my-cert.cert
```
So that it'll replace previous content.

So could you please delete the first one and edit/improve the second one with my feedback ? Thanks :)

Finally, 2 questions :
- it could be great to find a way to automatically copy the new cert each time it is renewed (and not with a basic daily cron task...), do you know if it's possible ?
- Is it normal that I can still access to cockpit using 9090 port ?

Thanks by advance for your consideration & anwser

**Comment by tigerblue77** [comment]
Ok, got an answer for this question :

> it could be great to find a way to automatically copy the new cert each time it is renewed (and not with a basic daily cron task...) Do you know if it's possible ?

Yes it's possible in accordance with [the certbot documentation](https://certbot.eff.org/docs/using.html#automated-renewals) using "deploy hook" (source : [https://community.letsencrypt.org/t/run-script-after-each-automatic-renewal/118054](https://community.letsencrypt.org/t/run-script-after-each-automatic-renewal/118054))
So here is what I've done as root :
`mkdir /etc/letsencrypt/deploy
nano /etc/letsencrypt/deploy/update_cockpit_certificate.sh`
Add the following lines :
`#!/bin/bash
cat /etc/letsencrypt/live/tigerblue77.fr.nf/fullchain.pem > /etc/cockpit/ws-certs.d/1-my-cert.cert
cat /etc/letsencrypt/live/tigerblue77.fr.nf/privkey.pem >> /etc/cockpit/ws-certs.d/1-my-cert.cert
service cockpit restart`
then make the script executable :
`chmod u+x /etc/letsencrypt/deploy/update_cockpit_certificate.sh`

**Comment by martinpitt** [comment]
Thanks and sorry for the delay! I reworked https://github.com/cockpit-project/cockpit/wiki/Cockpit-with-LetsEncrypt and cleaned up a lot of other wrong things as well.

**Comment by tigerblue77** [comment]
Good ! Thanks for applying changes and using my script (and nice improvment !)
Did you tested it works ? My "fix" is operational since january and still works but it would be nice to test it a second time on your side.

**Comment by martinpitt** [comment]
@tigerblue77 : I tested the individual steps with the cert installation, but I can't test the actual `certbot` call, as I don't currently have DNS control over a non-production domain name.

**Comment by tigerblue77** [comment]
@martinpitt Ok should be good thanks 👍
