### ISSUE TITLE
No apps installed or available on Ubuntu

### ISSUE THREAD

**Issue by EricFROL** [cockpit-project/cockpit#15157]
Cockpit version: 215
OS: Ubuntu (Lubuntu)
Hey guys, i just installed cockpit in my lubuntu, just for manage it remotely, and when i try to install apps such as "NFS file Sharing", returns me "No apps installed or available".
What should i know do now?, i already installed  cockpit-packagekit package.

PD: Image is in spanish.
![1](https://user-images.githubusercontent.com/42719382/104747591-0141f780-5751-11eb-81ff-3b573d2996b7.PNG)

Ty in advanced ^^

**Comment by martinpitt** [comment]
There is no "NFS file sharing" cockpit extension, at least not known to us. However, it seems a bit unexpected that not even cockpit's own extensions (like cockpit-storage) are shown. We need to look into how Ubuntu publishes the AppStream metadata.
