### ISSUE TITLE
Unable to create VM without root password (UI issue?)

### ISSUE THREAD

**Issue by aptsurfer** [cockpit-project/cockpit#15161]
Cockpit version: 235
OS: Ubuntu 20.04 LTS
Page: Virtual Machines -> Create Virtual Machine

When creating a VM with the "Workstation" profile, a question mark popup says "Leave the password blank if you do not wish to have a root account created". However, the UI prohibits users from proceeding if the password field is blank.

Steps to reproduce

1. Click "Create VM" button in Virtual Machines tab.
2. Fill out everything (I used Ubuntu 20.04 LTS as my VM) **except the root password** and select Workstation as the profile. Notice that clicking on the question mark reveals a popup that says you do not need to enter a root password if you don't want a root account.
3. Click the Create button. The UI will not let you continue without entering a root password.

**Comment by KKoukiou** [comment]
@aptsurfer indeed I can confirm the issue, i will address it.
