### ISSUE TITLE
[machines] ubuntu20.04 requires the user-password to be set.

### ISSUE THREAD

**Issue by guerby** [cockpit-project/cockpit#15178]
cockpit 235-1 on debian 11 bullseye (from apt-get install cockpit cockpit-machines)
osinfo-db is at version 0.20201218-1

When creating a VM with "download an os" choosing ubuntu 20.04, run unattended, profile workstation, entering a non empty root password the creation fails with:

ERROR ubuntu20.04 requires the user-password to be set. Domain installation does not appear to have been successful. If it was, you can restart your domain by running: virsh --connect qemu:///system start vmtestpolluxubuntudesktop otherwise, please restart your installation.

Note: same error with ubuntu 18.04 workstation.

**Comment by KKoukiou** [comment]
Thanks for the report @guerby, I will take a look.
