### ISSUE TITLE
Addons folder not found

### ISSUE THREAD

**Issue by altkhashi** [cockpit-project/cockpit#15172]
Hi, I am trying to install an addon for cockpit and the instructions say that i need to put it in a folder: path/to/cockpit/addons
i tried to use find to locate the "addons" folder in any directory related to cockpit with no results...
```
root08:54 AMmydeploy:~# find / -name addons
/snap/core18/1880/var/lib/vim/addons
/snap/core18/1944/var/lib/vim/addons
/var/lib/vim/addons
/usr/share/vim/addons
```

I also tried creating the "addons" folder with the addon placed inside it, in each of the following locations again with no results:
```
root09:23 AMmydeploy:~# find / -name cockpit
/etc/cockpit
/var/lib/cockpit
/usr/share/doc/cockpit
/usr/share/cockpit
/usr/lib/cockpit
/run/cockpit
```
Could you please advise me on where exactly the addons should be put? I have tried both on ubuntu 20.04 and centos 7, same outcome.
would appreciate your help.

**Comment by martinpitt** [comment]
There is no cockpit documentation about wher to place "addons". Any external cockpit package needs to ship their bits in /usr/share/cockpit/, and developers can also use ~/.local/share/cockpit/. What kind of "addon" are you trying to install?

**Comment by altkhashi** [comment]
Hi there,
Thank you for your fast response!
The addon is: https://github.com/serjoscha87/cockpit_GROUPS
I have tried putting the Groups folder in:
1. /usr/share/cockpit/  and then performed a systemctl restart cockpit
2. ~/.local/share/cockpit/ and then refresh the browser with and without restarting cockpit's service
none worked...
not sure if i have to do any extra steps...

**Comment by martinpitt** [comment]
Ah, heh -- that is for a [different cockpit](https://getcockpit.com/), I'm afraid :grin:

**Comment by altkhashi** [comment]
oh my god ... thanks for letting me know, otherwise i'd search for another couple days ... :D
