### ISSUE TITLE
Should be able to multi-select containers/images for deletion

### ISSUE THREAD

**Issue by sgallagher** [cockpit-project/cockpit#1517]
When testing with docker containers, it's not uncommon to build up a large number of unused containers. It would be very handy to be able to select a multitude of them and delete them all (or start or stop them all, etc.)

**Comment by andreasn** [comment]
I feel there are two different issues here.
One is that deleting a number of container is very labour intensive work. Dive into each container, delete it and then confirm that deletion in the box that pops up.
The second is to be able to perform the same action across several containers in one go.
I tried to sketch up some solutions for the second issue, but the solutions I could quickly come up with was just as much work as currently, or was trying to hit things with a hammer too big (stop or start All containers).

For the first issue there is no delete function in the list right now to avoid accidental deletion. If we could either have a delete button for every container and have the dialog pop up for every deletion (about the same amount of work as now, but less jumping back and forth) or have some kind of safety lock function as we have on the overview for deleting machines (and then skip the dialog for that case) that might solve it.

**Comment by andreasn** [comment]
![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/containers/docker-container-deletion.png)

**Comment by andreasn** [comment]
@dperpeet had some concerns about the discoverability of the delete action, so I made this alternative mockup: 
![Image of Yaktocat](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/containers/docker-container-deletion-alt.png)

**Comment by andreasn** [comment]
https://github.com/cockpit-project/cockpit/pull/1724

**Comment by stefwalter** [comment]
Where is the discussion and points from @dperpeet. I think the second mockup is too cluttered. It's already easy to delete containers by clicking on them, and then clicking 'Delete'. That's the most discoverable manner.

The alternate delete buttons are strictly an optimized path. I think it is acceptable that it isn't pushed in the user's face.

**Comment by andreasn** [comment]
@stefwalter we were discussing it over IRC on Friday.

After thinking some more about this over the weekend and playing around a bit with the pull request I think we should go for the first design where the delete buttons are only visible if the check is checked.
The low discoverability is a potential issue, but I agree with stef that it's not blocking the action, there is still the "old" way to delete it via the container page, and this keeps things consistent with the dashboard pattern.
