### ISSUE TITLE
missing files in release tarball

### ISSUE THREAD

**Issue by lnussel** [cockpit-project/cockpit#15209]
Cockpit version: 236
OS: openSUSE Tumbleweed

The release tarball misses at least the following files preventing rebuild of the dist/ content:
```
  pkg/lib/cockpit-po-plugin.js
  pkg/lib/_global-variables.scss
```

**Comment by marusak** [comment]
Reproducer:
```
$ wget https://github.com/cockpit-project/cockpit/releases/download/236/cockpit-236.tar.xz
$ tar -xvf cockpit-236.tar.xz
$ cd cockpit-236/
$ rm -rf dist/
$ ./configure
$ npm install
$ make
...
Error: Cannot find module './pkg/lib/cockpit-po-plugin'
```

**Comment by marusak** [comment]
Other missing files: (I'll update this comment as I iteratively try to build it)
```
./pkg/lib/variables.scss
./pkg/lib/patternfly/patternfly-overrides-variables.scss
```

**Comment by marusak** [comment]
Hmm, `npm install` does not install it all?
```
Error: File to import not found or unreadable: patternfly/dist/sass/patternfly.
        on line 5:1 of pkg/lib/patternfly/patternfly-cockpit.scss
>> @import "patternfly/dist/sass/patternfly";
```
and indeed:

In tarball:
```
$ ls node_modules/patternfly/dist/
fonts  js
```

In git checkout:
```
$ ls node_modules/patternfly/dist/
css  fonts  img  js  less  sass
```

**Comment by marusak** [comment]
Oh, the tar contains node_modules :O And it is not complete, like `sass` dir is missing for paternfly.

**Comment by martinpitt** [comment]
@marusak: Traditionally we have only shipped the runtime dependencies in the release tarballs (mostly for license reasons, I guess?), and the devel ones in cockpit-cache.tar.gz. So it is fully expected that you have to either run npm install or download/unpack cockpit-cache.
