### ISSUE TITLE
Host switcher design issues

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1521]
The host switcher at present has several design issues:

 * It is useless when there is only one server (the default case)
 * It does not remember whether it was hidden/visible when you:
   * Log into cockpit again
   * Refresh Cockpit
 * To go to the dashboard you have to show the host switcher, and if you didn't want it shown that is  irritating to come back from the dashboard and still have it there.

**Comment by andreasn** [comment]
Closing, since this was fixed in the new layout
