### ISSUE TITLE
tests: some machines verify tests break when tested against small screen sizes

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#15213]
As reported by xchen `when running verify test, my Notepad can only set 1920*1080 resolution,and when the browser is not Maximum , the "No VM is running or defined on this host" will disappear when there is no VM defined, causing lots of cases to fail.`

**Comment by marusak** [comment]
If you checkout the test code, I have had dealt with this before:
```
                # On smaller resolutions empty message is hidden. Firefox opens up in smaller window then chrome.
                if b.cdp.browser == "firefox":      
```

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit/commit/6f5f9ecbeefa234b15ce3a1843a30625797e9834

**Comment by KKoukiou** [comment]
@marusak this is not the desired behavior, so we should fix it propertly in the react code and remove the WA. I will leave it open for this reason.
