### ISSUE TITLE
Incorrect case-sensitive match of HTTP Headers

### ISSUE THREAD

**Issue by mehmooda** [cockpit-project/cockpit#15212]
in cockpit_web_server_parse_cookie
src/common/cockpitwebserver.c:511

the cookie is looked up using the title case "Cookie". 

Cockpit uses a hand rolled http header parser in web_socket_util_parse_headers
src/websocket/websocket.c:367

The headers are inserted into a hashmap without any normalisation.

HTTP header names are case-insensitive.

The nginx-ingress in kubernetes is set to be enabled for http2 by default. As part of this it normalised the cookie header into lowercase "cookie". I suspect this is a reason http2 doesn't work.

**Comment by martinpitt** [comment]
@mehmooda : Why did you close this? Cockpit may not do the header normalization, that seems rather easy to fix. What we *definitively* don't have is HTTP 2.0 support in cockpit-ws, and there is currently no simple way to add that. In other words, even with header normalization this may not be sufficient.

**Comment by mehmooda** [comment]
Sorry I closed this because I found that g_hash_table_new_full is created with a case insensitive string lookup function.

I'm still looking into why cockpit over a HTTP2 reverse proxy returns protocol-error. So far I'm seeing cockpit-bridge returning -1 from web_socket_util_parse_headers. Possibly due to g_utf8_validate?
