### ISSUE TITLE
Storage: incorrect report of LVM partitions size

### ISSUE THREAD

**Issue by jthing** [cockpit-project/cockpit#15220]
I use lvm to manage storage on a hard drive. All was well until I resized two logical partitions. The old values for size are still listed and this persists even after I rebooted.

**Comment by KKoukiou** [comment]
@jthing thanks for reporting this issue. Can you give the precise steps:

* How did you resize the partitions? Through cockpit UI or CLI?
* Did you verify from CLI that the size shown does not match the cockpit UI?

**Comment by jthing** [comment]
Sorry for the delay. The problem was with lvm reporting a different value from the shell value. Not a cockpit problem.
