### ISSUE TITLE
Breadcrumb bar needs to be in fixed frame

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1523]
The breadcrumb bar at the top of various pages needs to be in a fixed frame, so it doesn't scroll when you scroll the page. Having basic navigation scroll out of view is broken.

**Comment by martinpitt** [comment]
Supposedly not literally in a frame, but using CSS these days, but other than that this is still a valid concern.

**Comment by KKoukiou** [comment]
I think this can be done with:
  position: sticky;
CSS rule.
Trying it out now.
