### ISSUE TITLE
Docker Containers/Containers Tab

### ISSUE THREAD

**Issue by wmr-evo** [cockpit-project/cockpit#15240]
Cockpit version: 235
OS: Fedora 33 (Server Edition)
Page: <Docker Containers->

Are Docker Containers still an available tabbed option in Cockpit for Fedora?

Just installed Fedora Server 33 and when reviewing the cockpit-project.org page I noticed the option for a containers tab was shown as a tab on several of the pictures on the homepage.  I'm guessing it is for Docker, is this tab still available?  I've tried installing and searching but I have been unsuccessful.

**Comment by marusak** [comment]
cockpit-docker has been obsoleted for a while and in cockpit-228 it has been dropped altogether.
See https://cockpit-project.org/blog/cockpit-228.html
cockpit-podman is replacement.
We need to adjust screenshots though.
