### ISSUE TITLE
Runtime Directory environment variable must be set to a private directory

### ISSUE THREAD

**Issue by CaseyK9** [cockpit-project/cockpit#15248]
Cockpit version: 
OS: Latest
Page: N/A

I get the following errors upon cockpit startup:
cockpit-tls: $RUNTIME_DIRECTORY environment variable must be set to a private directory.
cockpit.service: Main process exited, code=exited, status=1/FAILURE
cockpit.service: Failed with result 'exit-code'.

I have no clue how to reproduce this, I am just looking for a way to fix this.

**Comment by martinpitt** [comment]
How do you start cockpit? This variable is set by /usr/lib/systemd/system/cockpit.service normally:

```
# systemd ≥ 241 sets this automatically
Environment=RUNTIME_DIRECTORY=/run/cockpit/tls
```
Please copy&paste the output of `systemctl cat cockpit`.

**Comment by martinpitt** [comment]
Also, what operating system do you use? (There is a reason why the bug template asks that..)

**Comment by CaseyK9** [comment]
I'm using Ubuntu 20.04 LTS

**Comment by CaseyK9** [comment]
# /lib/systemd/system/cockpit.service
[Unit]
Description=Cockpit Web Service
Documentation=man:cockpit-ws(8)
Requires=cockpit.socket
Requires=cockpit-wsinstance-http.socket cockpit-wsinstance-http-redirect.socket cockpit-wsinstance-https-factory.socket
After=cockpit-wsinstance-http.socket cockpit-wsinstance-http-redirect.socket cockpit-wsinstance-https-factory.socket

[Service]
# systemd ≥ 241 sets this automatically
ExecStartPre=/usr/sbin/remotectl certificate --ensure --user=root --group=cockpit-ws --selinux-type=
ExecStart=/usr/lib/cockpit/cockpit-ws
PermissionsStartOnly=true
User=cockpit-ws
Group=cockpit-ws

**Comment by CaseyK9** [comment]
I also get a permission issue stating that Cockpit's files are executable and have permission issues on startup, however, these error messages are too fast for me to read.

**Comment by martinpitt** [comment]
@CaseyK9 : Your /lib/systemd/system/cockpit.service is broken -- its `[Unit]` is correct, but its `[Service]` is indeed missing the `Environment=RUNTIME_DIRECTORY=/run/cockpit/tls` line, and moreover its `ExecStart=` is wrong also. Still, *something*  in your system is trying to start cockpit-tls, but it's not cockpit.service. Most likely you manually edited/installed/updated some files in /usr. I suggest to completely purge all cockpit related packages and reinstall them from scratch:

    sudo apt purge `cockpit*`
