### ISSUE TITLE
network: show a  proper empty state when NM is not installed

### ISSUE THREAD

**Issue by RazielleS** [cockpit-project/cockpit#15245]
Cockpit version: 236-1
OS: Arch Linux
Page: Network

Loading the network page, it remains completely empty.
This is a completely fresh installation of Arch. So it is entirely possible that just a package is missing.
But in contrast to other pages, I do not really get an error message I can understand.
![image](https://user-images.githubusercontent.com/8451816/106259722-e1660580-621f-11eb-8652-6631a377e582.png)

## Journal:
```
-- Journal begins at Thu 2021-01-28 23:03:39 UTC, ends at Fri 2021-01-29 09:54:48 UTC. --
Jan 29 09:54:47 sec cockpit-tls[722]: cockpit-tls: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Jan 29 09:54:47 sec cockpit-tls[722]: gnutls_handshake failed: A TLS fatal alert has been received.
Jan 29 09:54:47 sec cockpit-tls[722]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Jan 29 09:54:47 sec cockpit-tls[722]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Jan 29 09:54:47 sec cockpit-tls[722]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Jan 29 09:54:47 sec cockpit-tls[722]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Jan 29 09:54:47 sec dbus-daemon[611]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.37' (uid=0 pid=747 comm="cockpit-bridge ")
Jan 29 09:54:47 sec audit: BPF prog-id=31 op=LOAD
Jan 29 09:54:47 sec audit: BPF prog-id=32 op=LOAD
Jan 29 09:54:47 sec kernel: audit: type=1334 audit(1611914087.451:153): prog-id=31 op=LOAD
Jan 29 09:54:47 sec kernel: audit: type=1334 audit(1611914087.451:154): prog-id=32 op=LOAD
Jan 29 09:54:47 sec systemd[1]: Starting Hostname Service...
Jan 29 09:54:47 sec dbus-daemon[611]: [system] Successfully activated service 'org.freedesktop.hostname1'
Jan 29 09:54:47 sec systemd[1]: Started Hostname Service.
Jan 29 09:54:47 sec audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 29 09:54:47 sec kernel: audit: type=1130 audit(1611914087.495:155): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 29 09:54:48 sec audit[1052]: USER_ACCT pid=1052 uid=0 auid=0 ses=1 msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=? res=success'
Jan 29 09:54:48 sec kernel: audit: type=1101 audit(1611914088.228:156): pid=1052 uid=0 auid=0 ses=1 msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=? res=success'
Jan 29 09:54:48 sec PackageKit[774]: get-updates transaction /14_bcabdeba from uid 0 finished with success after 105ms
```

## Steps to reproduce
It happens on every reload. Since it is likely a missing package, I can't tell how to reproduce it.

**Comment by RazielleS** [comment]
I just figured it out:
This page only works if NetworkManager is installed. Otherwise I just get a blank page.

This is resolved for me. Would be nice to see what is missing though.

**Comment by marusak** [comment]
> This page only works if NetworkManager is installed.

Normally distribution should make sure that you cannot install cockpit-networking unless you also install networkmanager.
In Fedora for example we do exactly that:
`Requires: NetworkManager >= 1.6 `

Have you installed this from official arch repos or have you build it yourself?

**Comment by RazielleS** [comment]
I have installed it from the official repos.
I now just doublechecked: network manager is [listed as an optional dependency](https://archlinux.org/packages/community/x86_64/cockpit/). 

In this case it might make sens to display a warning instead of just nothing...or is it intended to not have cockpit-networking in the base installation of cockpit?

**Comment by KKoukiou** [comment]
It makes sense to display a warning that NM is not installed, on current master it does not, it displays a spinner forever which is also problamatic behavior.
