### ISSUE TITLE
Error on Realtime Graphs.

### ISSUE THREAD

**Issue by n00r-muhammad** [cockpit-project/cockpit#15259]
Cockpit version: 224.2.
OS: CentOS 8
Page: 

Steps to reproduce

1. update cockpit to new version 224.2.
2. restart cockpit or restart OS
3. showing graphs for 5 mins or less then graphs hang or not showing on refreshing browser
3. inspect graphs
4. tested on both chrome and edge browsers

![image](https://user-images.githubusercontent.com/78408870/106571833-79822880-6559-11eb-984b-7281309df787.png)

**Comment by marusak** [comment]
This is on dashboard component, which we obsoleted and dropped already. One of the reasons was that it was getting too difficult to maintain and not providing anything interesting anymore.
This report is proof of that. The logs on the screen don't show anything that can be reason of this problem.
In general I would advise not to use this component anymore. For some more info about the deprecation see https://cockpit-project.org/blog/cockpit-234.html
I am closing this issue as it does not apply to upstream anymore, but if you believe it is serious and should be fixed, then it needs to be reported in downstream trackers. (Mind you, in rhel-8 we already have cockpit-236 ready, which does not have this component anymore).

**Comment by n00r-muhammad** [comment]
> This is on dashboard component, which we obsoleted and dropped already. One of the reasons was that it was getting too difficult to maintain and not providing anything interesting anymore.
> This report is proof of that. The logs on the screen don't show anything that can be reason of this problem.
> In general I would advise not to use this component anymore. For some more info about the deprecation see https://cockpit-project.org/blog/cockpit-234.html
> I am closing this issue as it does not apply to upstream anymore, but if you believe it is serious and should be fixed, then it needs to be reported in downstream trackers. (Mind you, in rhel-8 we already have cockpit-236 ready, which does not have this component anymore).

For me as i am using clustered environment with multiple nodes, these graphs were very useful to monitory the resource utilizations in real time. it was working best in previous release. i think cockpit-234 is not yet available and pre-matured to implement on production env. if possible please fix the issue otherwise please guide me how can i rollback to previous version 195.6.
To be very honest and as end user of this app cockpit 195.6. is far more better than the latest 224.2. and the one you are mentioning is not yet in game.
thanks for considering.
