### ISSUE TITLE
Layout bug on login page re RequireHost

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#15255]
Cockpit version: 236
Page: Login

When `RequireHost` is true and there is no remote host in the URL yet, the login page looks like this:

![image](https://user-images.githubusercontent.com/3228183/106459342-62303600-649a-11eb-85ed-a728b82d7f51.png)

**Comment by mvollmer** [comment]
I.e., the login page tries to hide the "> Options" header, and we were not aware of this possibility when doing the recent rework.

But, I actually found the current behavior confusing: When RequireHost is enabled., the "> Options" header is sometimes shown and sometimes not, and I couldn't really see the logic.  Turns out if the header will be shown when there already is a `/=HOST` element in the URL, and otherwise not.

So a fix would be to always show the "> Options" header.  This makes the whole thing simpler and I don't think anybody will notice or care.

**Comment by garrett** [comment]
Oh, there's no margin under the error message!
