### ISSUE TITLE
Cockpit Dashboard not available on Buster Backports

### ISSUE THREAD

**Issue by crouchingtigerhiddenadam** [cockpit-project/cockpit#15292]
I'm trying to install cockpit dashboard for cockpit 235-1~bpo10+1. This is no longer showing available on Buster Backports for ARM64 (aarch64).

**Comment by martinpitt** [comment]
Indeed, the dashboard got removed in favor of a shell-integrated host switcher. See https://cockpit-project.org/blog/cockpit-234.html

**Comment by crouchingtigerhiddenadam** [comment]
Thanks Martin, I hadn't seen this. I found the dashboard very useful in a server farm environment where jobs could go astray and use excessive CPU and for checking load balancing was working correctly. There are better tools, but being able to have a quick overview in cockpit was really useful to me. Most of the time a warning icon next to any computer with failed services and combined graphs was all the information I needed.
