### ISSUE TITLE
Removing local host on first page -> unable to add it back

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#1529]
Hi,
I've used [-] button to remove localhost from cockpit, but then I'm unable to add it back via button [+] 
![hribecek - mozilla firefox on boletus brq redhat com _002](https://cloud.githubusercontent.com/assets/8735467/5202691/75e65022-7580-11e4-9122-8258357ae024.png)
![cockpit - mozilla firefox on boletus brq redhat com _003](https://cloud.githubusercontent.com/assets/8735467/5202693/7a66265e-7580-11e4-94be-091a86520faf.png)

**Comment by sub-mod** [comment]
I couldn't locate /opt/cockpit4/var/lib/cockpit/machines
So i searched for "machines" file
>find / -name machines
/var/lib/cockpit/machines

deleted it and restarted cockpit
>systemctl restart cockpit.service

local machine is now back

**Comment by jscotka** [comment]
Hi,
I have recompiled cockpit to --prefix= /opt/cockpit4, thats why I have longer prefix than compilation directly to /usr dir.
