### ISSUE TITLE
metrics: journal integration

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15303]
Wireframe:

![metrics-journal-2021-02-08-1454(3)](https://user-images.githubusercontent.com/10246/107394236-ee2a0980-6afb-11eb-99a9-f874dc79bb27.png)

Mockup:

![Metrics Journal](https://user-images.githubusercontent.com/10246/107394295-03069d00-6afc-11eb-948e-a9d5a821fccb.png)

Features:

- tooltip information integrated at the top of the expansion
- journal log lines
- prominent errors and warnings

Not pictured:
- Hour headers could have an "expand hour entries" action that would expand the entries of the hour

Originally, I was going the route of having popovers, but decided that it would not be easy to compare entries during the current time with other time slices.

The wireframe was made using Excalidraw and can be opened up and edited there (as it embeds all the editable vector data inside the PNG. The mockup was made in Penpot; it doesn't do a good job at exporting SVG yet and lacks import/export features (except by path or artboard, and only to PNG and wonky SVG).

**Comment by garrett** [comment]
I was thinking of making it similar to PatternFly's table element, except that we only draw the lines of expanded elements (otherwise it would get pretty noisy, I think).

The tooltip's content was intentionally placed at the top with a different style and background. Expanding multiple times should make the metadata easier to compare.

**Comment by garrett** [comment]
When expanding the time, it would stretch that section of the graph. The journal entries probably won't line up with the graph, but it'll at least help zoom to the problem a bit (and keep the graph contiguous).

**Comment by martinpitt** [comment]
Splendid, thanks @garrett! I really like this, let's see how it will look in practice. I hope the expanders don't get too crammed so that the log messages get too hard to read. We may need to make this scrollable also, first because there could be a lot of log spewage for one minute (possibly hundreds of lines) and we probably also want to show the previous minute so that one can see which system events led to that spike.

**Comment by garrett** [comment]
> We may need to make this scrollable also, first because there could be a lot of log spewage for one minute (possibly hundreds of lines) and we probably also want to show the previous minute so that one can see which system events led to that spike.

I think we would want to avoid the double scrollbars if we can. I was thinking that we might want to filter the messages with a default (such as warnings and higher) and allow someone to change that.

But I think we might need to see it in action before making a decision on what to do.

**Comment by garrett** [comment]
I was thinking of either tabs or a dropdown for the granularity, above the list. Although it might be annoying to change that every minute.

Also, an expander link at the bottom that says something like "Show 12 additional filtered journal entries" which would include the filtered ones.

But too much of that would be annoying when comparing minutes. Perhaps granularity should be a dropdown in the hour's header (perhaps with the expander link in the minutes still, when it applies)?

**Comment by marusak** [comment]
I like this! However I cannot help myself thinking that we cannot fit everything into this super confined space. So I would suggest showing just limited time with limited priority and also limit it to 10 or so messages with "See all logs" link to logs page where user can change range, severity, services and just dig deeper.

**Comment by martinpitt** [comment]
> filter the messages with a default (such as warnings and higher)

But that would then remove all the interesting bits -- like starting a service or logging what programs do. In most cases, it's exactly the non-error "normal" operations that cause resource utilization.

I like the idea with limiting the messages and a "see all" link.
