### ISSUE TITLE
Running make does not recompile some changed files, such as pkg/lib/patternfly/patternfly-overrides.scss

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15300]
1. Compile everything
2. Change `pkg/lib/patternfly/patternfly-overrides.scss`
3. Compile again
4. Note how the overrides file is not recompiled

This may (and probably does) affect other files too.

**Comment by martinpitt** [comment]
@allisonkarlitskaya is currently reworking the whole webpack-make stuff. Let's re-test this after she's done (my gut feeling is that the rework will just fix bugs like this in general)

**Comment by martinpitt** [comment]
This works again:
```
$ make
# does nothing
$ touch pkg/lib/patternfly/patternfly-overrides.scss
$ make
# rebuilds everything
```
