### ISSUE TITLE
Please resume the dashboard graphs

### ISSUE THREAD

**Issue by n00r-muhammad** [cockpit-project/cockpit#15308]
For me as i am using clustered environment with multiple nodes, these graphs were very useful to monitory the resource utilizations in real time. it was working best in previous release.
i think cockpit-234 is not yet available and pre-matured to implement on production env. if possible please fix the issue otherwise please guide me how can i rollback to previous version 195.6.
To be very honest and as end user of this app cockpit 195.6. is far more better than the latest 224.2. and the one Cockpit 234 you are mentioning is not yet in a game.
thanks for considering.

**Comment by marusak** [comment]
> if possible please fix the issue otherwise please guide me how can i rollback to previous version 195.6.

Before we removed this plugin we discussed it thoroughly considering all aspects. The old plugin is not coming back. Of course, if there is anyone who wants to implement it as a third party plugin, they are welcomed to do so (there is [starter-kit](https://github.com/cockpit-project/starter-kit/) to make this easy) but mind you, it the meantime we don't autoconnect to machines, so the plugin would have to do it manually. We are currently in the process of looking into grafana and how we can help users with setting it up.

What includes rolling to older version, this depends on your system, but the same way you have updated there is always option to downgrade (like `dnf downgrade cockpit` or so).

**Comment by n00r-muhammad** [comment]
> > if possible please fix the issue otherwise please guide me how can i rollback to previous version 195.6.
> 
> Before we removed this plugin we discussed it thoroughly considering all aspects. The old plugin is not coming back. Of course, if there is anyone who wants to implement it as a third party plugin, they are welcomed to do so (there is [starter-kit](https://github.com/cockpit-project/starter-kit/) to make this easy) but mind you, it the meantime we don't autoconnect to machines, so the plugin would have to do it manually. We are currently in the process of looking into grafana and how we can help users with setting it up.
> 
> What includes rolling to older version, this depends on your system, but the same way you have updated there is always option to downgrade (like `dnf downgrade cockpit` or so).

# sudo yum downgrade cockpit
Last metadata expiration check: -945 days, 9:16:17 ago on Mon 01 Feb 2021 08:28:05 AM PKT.
Package cockpit of lowest version already installed, cannot downgrade it.
Dependencies resolved.
Nothing to do.
Complete!
