### ISSUE TITLE
New config setting for autoinstall feature

### ISSUE THREAD

**Issue by psztoch** [cockpit-project/cockpit#15310]
Please, add new configuration parametr (in example in cockpit.conf) for blocking autoinstall feature.

If this parameter will be enabled, then:
a) /metrics: "Package cockpit-pcp is missing for metrics history [Install cockpit-pcp]" should be hided
b) /system: "install software" popups for realmd, tuned or cockpit-pcp should be disabled.

Exemplary justification:
In low performance/budget micro-machines with SD card as storage, users install "cockpit-pcp", and storage gets broken, becauseit is not suitable for continuous writes.
Some "administrative" users have an irresistible urge to enable whatever their interface allows. And sometimes you have to protect against them.

**Comment by martinpitt** [comment]
Note, as a stopgap measure you can uninstall PackageKit. Then none of these "install on demand" features will be available.

This can't really be in cockpit.conf, that's not what it is for. If this is going to be conditionalized, it needs to live someplace else.

**Comment by marusak** [comment]
There are many open source projects out there, that have config option for pretty much anything. Half of them don't work, or work only if some other options are not specifed... It always gets messy. I always liked about cockpit that it did not get on this slippery slope of having config options for everything.

This proposed option seems rather wild as it is not something we can enforce in general, but every page and every (third party) plugin would have to implement it directly.

As Martin said, if you remove PackageKit, you won't see this options.
Also you should not be able to install any of these if the logged in user does not have root access. So I would think that user that has been given root access would be knowledgeable enough to know what to install and what not.

**Comment by marusak** [comment]
Sorry, but I don't see this actionable.
