### ISSUE TITLE
Login page is not a proper HTML form

### ISSUE THREAD

**Issue by septatrix** [cockpit-project/cockpit#15335]
Cockpit version: 215
OS: Ubuntu 20.04
Page: -

The login form is not a html `<form>` element.
This leads to bad accessibility but also a degraded experience in general. For example my browser does not prompt to save the password.

Steps to reproduce

1. Open the cockpit website (without being logged in) in - you should see the login page
2. Inspect the DOM - there is no `<form>` element but only a `<div role="form">`
3. Login with your username/password - in Chrome at least you will not be prompted to save the password

I assume the autofill issue is also due to not using a proper form element. By looking at the code it seems that the login process is for some reason implemented mostly client side in JS for some reason unknown to me. However HTML5 also allows form elements with no action attribute which could be used instead of the current div.

**Comment by marusak** [comment]
> For example my browser does not prompt to save the password.

Duplicate, please see https://github.com/cockpit-project/cockpit/issues/6399#issuecomment-689424516

> This leads to bad accessibility

Does it? Isn't `role="form"` enough for accessiblity?

It you read through #6399 you will see that we tried to move it to `form` and the browser behavior did not change. It can save login, see the linked comment. I have saved my password and autofilling works just fine.

**Comment by septatrix** [comment]
Okay I will try it again with the newest version.

> Does it? Isn't role="form" enough for accessiblity?

Sadly not all tools like extensions support these roles. But yes  for general screen readers it is mostly sufficient (although I see no reason why a normal form was not used).
