### ISSUE TITLE
cockpit-machine: missing firmware options

### ISSUE THREAD

**Issue by ishioni** [cockpit-project/cockpit#15332]
Cockpit version: 237
OS: Debian Buster
Page: Machines

In older versions of cockpit-machine i was able to switch a VM between BIOS and UEFI. After the UI redesign some versions ago, this is gone for me, but in the screenshots i see it's supposed to be there. The ovmf package is present in the system

Steps to reproduce

1. Install cockpit from debian backports
2. Create a debian buster VM
3. No firmware selection is present
<img width="890" alt="Screenshot 2021-02-15 at 00 20 45" src="https://user-images.githubusercontent.com/50323052/107892165-a81ddd00-6f23-11eb-9d7f-feba587bf018.png">

**Comment by KKoukiou** [comment]
`<os firmware=[bios/efi]'` settings is available only for libvirt version >= 5.2

I see debian buster is with libvirt-daemon 5.0.0, which is not sufficient version to show this option.

I don't see how the redesign would affect the visibility of this attribute really.

**Comment by ishioni** [comment]
Thanks for the info. I see from libvirt changelog that it was possible to change that manually in the xml but from 5.2 onwards libvirt handles this internally, so I'm guessing that at some point cockpit took advantage of that.

**Comment by KKoukiou** [comment]
@ishioni actually this libvirt version check exists since this feature exists; basically there are two conditions that enable in the UI that firmware line in the VM overview;

* libvirt version > 5.2.0 - there is actually libvirt version check directly in the code from the first commit this issue was implemented  
* virsh domcapabilities should have info for `os loader`

For the latter I mean: 
```
$ virsh domcapabilities 
<domainCapabilities>
...
  <os supported='yes'>
    <enum name='firmware'>
      <value>efi</value>
    </enum>
    <loader supported='yes'>
      <value>/usr/share/edk2/ovmf/OVMF_CODE.fd</value>
      <enum name='type'>
        <value>rom</value>
        <value>pflash</value>
      </enum>
      <enum name='readonly'>
        <value>yes</value>
        <value>no</value>
      </enum>
      <enum name='secure'>
        <value>no</value>
      </enum>
    </loader>
  </os>
``` 
So one of the two, or both are not satisfied on your system.

**Comment by KKoukiou** [comment]
@ishioni since it's clear that these options are not expected to appear on your system because of the insufficient libvirt version I will close this issue. (I am not sure how you were able to see it at some point)

**Comment by ishioni** [comment]
Yes this is fine, i didn't know there was a requirement on libvirt version 5.2 for this
