### ISSUE TITLE
Offline installation package

### ISSUE THREAD

**Issue by yanghui-git** [cockpit-project/cockpit#15387]
Page: 

In many necessary occasions， We cannot install online，So how can i  get an  Offline installation package

thanks very much

**Comment by marusak** [comment]
Is this about how to install cockpit itself? Or using the updates page?

If about cockpit itself, you just need to get the necessary packages and install them. This depend on your distro. I'll give you example for Fedora, but the same applies for other distros, you just need to look around.
You will need `cockpit-bridge`, `cockpit-ws` and for example `cockpit-system`. You can get these either from repos or from build system. For Fedora 33 mirror list is https://mirrors.fedoraproject.org/metalink?repo=fedora-33&arch=x86_64 (grabbed from `/etc/yum.repos.d/fedora.repo`). There is also updates repo.
Or you can just get packages directly from build system - https://koji.fedoraproject.org/koji/

Of course, you will need to make sure you have also all dependable packages. This can be transitive chain, so it may become a bit wild to do this manually package by package.

I would say that your best option is to use dnf (still talking about fedora) and just let it download all packages into folder.
Something like this will download these packages with all required deps into `/var/tmp/cockpit-repo`:
```
dnf --downloaddir /var/tmp/cockpit-repo download --alldeps --resolve cockpit-ws cockpit-bridge cockpit-system
```
Then you can copy this folder and just use `dnf` or `rpm` and install those packcages. Of course you can specify updates repository if you want to get the newest version etc.

You can take it step further and call `createrepo` utility on this folder and create from it a full blown repository. Then you can create another entry in `/etc/yum.repo.d/` with pointer to this folder (with `file://` prefix) and then you can treat this folder as full and valid repository and just do `dnf install cockpit` and it will  use your local repository. (Make sure to enable it and disable all others).
With the same approach even the updates page would work.

Btw. there is even `reposync` command for dnf which will take the whole repository and will download it. That will be in GBs of course, but you can literally take the whole repository to offline machine and update it as if it is connected to the internet.

So as you can see, this topic is rather broad - I just skimmed over the most obvious points, but there is much more to it. This whole comment was about how to do it on Fedora, but I believe (hope) that other distros enable doing the same.

To learn more, you can just google something like `<packcage_manager> offline installation` and you will get some nice results. For example https://unix.stackexchange.com/questions/259640/how-to-use-yum-to-get-all-rpms-required-for-offline-use

**Comment by yanghui-git** [comment]
Thanks for reply
My issue is how to install cockpit on offline environment;
I try to use the method like your idea  that  google something like <packcage_manager> offline installation;
First , i get all cockpit rpm packages  including  cockpit dependent services,
Second  I put these rpm packages on my offline environment 

But there is a problems  that these rpm packages are too many ,your can see these in my pictures;
So I do not know how to install these rpm packages

the issue is cockpit and cockpit's related service rpm packages are too many 

This is my advice ; For example If we get phone app like WeChat in Android , We just need an APK (Android application package) ,then I just need  install this APK ;  If We use java ,We Just need  a JDK package ;   If We use Google Chrome in windows ，We just need Google Chrome installation package; 
So ,If We use cockpit ,We just need a rpm package named cockpit.version8.2.rpm

<img width="894" alt="截屏2021-02-21 下午2 37 02" src="https://user-images.githubusercontent.com/69784471/108617552-4a711f80-7452-11eb-8cc0-b5d59313f28d.png">

<img width="672" alt="截屏2021-02-21 下午2 22 59" src="https://user-images.githubusercontent.com/69784471/108617335-8905da80-7450-11eb-9cbf-d682597bbd50.png">

**Comment by marusak** [comment]
> But there is a problems that these rpm packages are too many ,your can see these in my pictures;
So I do not know how to install these rpm packages

If you have them in folder `foo` just do `yum install foo/*` and it will install all of them. (`yum` as it seems you are on centos-7)
Or as I wrote above, create repo from this folder and just use that. The link I provided describes exactly that. (The part from `createrepo`)

**Comment by yanghui-git** [comment]
this method  may success ,but it takes much time ,especially for someone who do not know yum, rpm,.repo,yum.conf, and how to make mirror ；it is very unfriendly

So i advice enhancement that We Just need  simple rpm package
For example If we get phone app like WeChat in Android , We just need an APK (Android application package) ,then I just need install this APK ; If We use java ,We Just need a JDK package ; If We use Google Chrome in windows ，We just need Google Chrome installation package
