### ISSUE TITLE
cockpit-ws: DH KEX missing

### ISSUE THREAD

**Issue by nabilragab** [cockpit-project/cockpit#15403]
This is a server management tool that potentially gives full access to the Linux server system, hence top SSL security measures must be implemented to ensure server security.

Currently, I must address the following low priority issues:

- Strict Transport Security HTTP Header Not Set
(Header set Strict-Transport-Security "max-age=7776000" Header append Strict-Transport-Security includeSubDomains)

- Implementing Diffie–Hellman key exchange
(can be optionally defined to find it in /etc/cockpit/ws-certs.d/dfh.key )

**Comment by martinpitt** [comment]
We can't/won't do Strict-Transport-Security, see discussion in https://bugzilla.redhat.com/show_bug.cgi?id=1877851.

What do you mean with "Diffie–Hellman key exchange"? This is all between the browser, the certificate you give to cockpit-ws, and GnuTLS. Can you please expand on what you want to do, and what should happen? Thanks!

**Comment by martinpitt** [comment]
Stale, no response.
