### ISSUE TITLE
Grow logical volume - Unexpected type 'double' in argument

### ISSUE THREAD

**Issue by oskarb** [cockpit-project/cockpit#15409]
Cockpit version: 237
OS: Fedora 32
Page: Storage/Volume group

Grow logical volume opens as:
![image](https://user-images.githubusercontent.com/482095/108875042-11c17980-75fd-11eb-813c-959908ebfc96.png)

I change the "8" to "9" and click "Grow":
![image](https://user-images.githubusercontent.com/482095/108875163-2b62c100-75fd-11eb-9f4b-3e59fbd76508.png)

Expected behaviour is that either decimals should be accepted, or it should populate the input field with an integer value to begin with (and have a more explanatory input validation error message instead of something that looks like a bug).

If it must be integer, probably TB is too big unit, it would feel too imprecise, and the dialog should instead select GB as unit when it's opened.

**Comment by KKoukiou** [comment]
Interesting, with cockpit-239 I am not even able to insert in the field some floating point number.
![Screen Shot 2021-03-04 at 19 28 08](https://user-images.githubusercontent.com/14921356/110011520-d5d69480-7d1f-11eb-93f9-c6e63f8a776d.png)

This needs a closer look from my side.

**Comment by mvollmer** [comment]
@oskarb, please check out #15534.

**Comment by oskarb** [comment]
@mvollmer I don't feel I have the ability to test it, with reasonable level of effort (unless there happens to an already up-and-running demo environment somewhere). I did have a look through the code and it sounds promising. As I understand it, in `validate`, the text value is converted to Number and multiplied by the unit size, and the rounding happens after that. So I guess this means I can type/select 9.15 TB and in the end the size will be a value at, or close to, 9.15*1024*1024*1024*1024 bytes?

That sounds good to me! :)
