### ISSUE TITLE
storage: Enhance side panel lists with a top border and make sure that all list items appear clickable (also main list)

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15418]
Cards with lists do not have lines on the topmost element:

![Screenshot_2021-02-24 Storage - garrett Rain](https://user-images.githubusercontent.com/10246/108986308-47647200-7692-11eb-8926-680b5ac7435b.png)

However, it is acceptable to omit the lines from the heading of the list:

![Screenshot_2021-02-24 Storage - garrett Rain(1)](https://user-images.githubusercontent.com/10246/108986425-64994080-7692-11eb-96dc-ea03c6ac66e8.png)

Screenshots are from Storage, but this applies elsewhere too.

**Comment by garrett** [comment]
At first, I thought the drives were handled by a [table widget](https://www.patternfly.org/v4/components/table), but all the examples all have a header. There's an option for header=no, but I think it's for something else.

Then, I thought it must be a [data list](https://www.patternfly.org/v4/components/data-list/). All of these have top lines.

It turns out we're using a "SidePanel" widget that's our own thing. It also doesn't have a clicky looking mouse cursor (with a pointing hand), which is another bug.

Are we able to use a data list instead?

**Comment by garrett** [comment]
On second thought, I looked at it further and it doesn't really align with what we're trying to do here. I've looked through all of PatternFly's widgets to consider what we could use instead and nothing really fits. (In a way, it's even kind of like [a menu object](https://www.patternfly.org/v4/components/menu#with-favorites), except it's always expanded. 😆)

I guess I'll adjust the tiles to look clickable and add the top border.

Meanwhile, we should consider working with PatternFly to get an official widget for this kind of object, as they're not quite a data list, table widget, or even the new "tile" widget (which is more for forms, not lists).

**Comment by KKoukiou** [comment]
@garrett there is this issue as well, https://github.com/cockpit-project/cockpit/issues/15586 which also notes that hovering on items on storage page is inconsistent and wrong.

Therefore I will close the other one, and keep this one with the following goal:

* Make sure that storage list/side panel items are all showing up us clickable and use appropriate widgets for this.

**Comment by garrett** [comment]
@KKoukiou: Great, thanks! :+1:

**Comment by KKoukiou** [comment]
Checked on main and all lists are showing clickable and navigable in a consistent way. Closing this as resolved.
