### ISSUE TITLE
storage: Devices & iSCSI cards need to improve empty state style

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15419]
![Screenshot_2021-02-24 Storage - garrett Rain(2)](https://user-images.githubusercontent.com/10246/108986613-9f02dd80-7692-11eb-9893-a101b87dddd8.png)

It should match the empty state of https://github.com/cockpit-project/cockpit/issues/15417. (That is: Both need to be adjusted and both should look similar to the PF empty state for cards.)

Reference for the PF Card empty state:

https://marvelapp.com/prototype/7c5cdhd/screen/72928590

Excerpt: 

![Screenshot_2021-02-23 x-small empty state(1)](https://user-images.githubusercontent.com/10246/108869037-1edb6a00-75f7-11eb-8620-ea18b61b0e85.png)

Since the card already has a heading, we should probably remove the second heading and just use the secondary text, which would resemble something like this modification I did on the above crop of the PF mockup:

![Screenshot_2021-02-23 x-small empty state(1)-mod](https://user-images.githubusercontent.com/10246/108988057-4e8c7f80-7694-11eb-8ea6-3a4008a94b78.png)

**Comment by garrett** [comment]
This is the same for iSCSI too:

![Screenshot_2021-02-24 Storage - admin localhost localdomain](https://user-images.githubusercontent.com/10246/109004070-89001780-76a8-11eb-9623-8225fd62a5cd.png)

**Comment by KKoukiou** [comment]
@garrett how do you expect the link in the empty state action to be? The button for creating new devices is a dropdown, because of different device types. I am unsure how we can integrate that in the empty state described above.

**Comment by KKoukiou** [comment]
@garrett so I just looked into this, the padding in the empty state cards and the ones with list should be the same. Therefore I don't really believe this is wrong as it is. However I made sure that the original emptystate component is used here, with all padding adjusted to match the cards that are not empty.

**Comment by garrett** [comment]
It should look roughly like this (not pixel perfect) to be more balanced:

![empty-state-card](https://user-images.githubusercontent.com/10246/112322005-d3c57d00-8cb0-11eb-92b5-6bbb62e7457b.png)

I think the size would probably be around 1.5rem, which is equivalent 24px and `var(--pf-global--spacer--lg)`. The empty state itself hopefully sets something like this, perhaps more or less.

**Comment by KKoukiou** [comment]
@garrett Hmm I actually disagree about the bottom padding.
I believe we should have the same bottom padding in all cards on the side panel, regardless if they are empty or contain lists and this is exactly what I am doing in this PR.

**Comment by garrett** [comment]
1. Yes, same padding.
2. It needs inner padding between the text and the bottom of the card. The lists themselves have the padding inside the list. The empty state should also have padding (which it does on PF's examples).

The problem is that the cards do not have same or even similar padding. There needs to be some space between the text and the bottom, and it's not currently there (in the screenshots, and in master, at least).

**Comment by KKoukiou** [comment]
>     1. Yes, same padding.

That's what I am doing in https://github.com/cockpit-project/cockpit/pull/15583, can we move the discussion there? 
> 
>     2. It needs inner padding between the text and the bottom of the card. The lists themselves have the padding inside the list. The empty state should also have padding (which it does on PF's examples).
> 
> 
> The problem is that the cards do not have same or even similar padding. There needs to be some space between the text and the bottom, and it's not currently there (in the screenshots, and in master, at least).
