### ISSUE TITLE
metrics: Don't show read-only mounts for Ubuntu snaps

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#15434]
Cockpit version: 238
OS: Ubuntu 20.04
Page: Metrics

This is useless and unnecessarily alarming:

![image](https://user-images.githubusercontent.com/200109/109180935-b245a400-778b-11eb-9642-2a81fc8558a4.png)

Let's filter out /snap in particular, or possibly even all read-only mounts.

This can be seen in /livetest machines.

**Comment by martinpitt** [comment]
These are loop devices apparently -- filtering these out is more generic.

**Comment by mvollmer** [comment]
We should filter out all devices with UDISKS_IGNORE set, and that snap should set UDISKS_IGNORE on its devices.
See https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1714941

**Comment by mvollmer** [comment]
Ah, seems we can look at the x-gdu.hide mount option.

**Comment by martinpitt** [comment]
@mvollmer: That would be for issue #2454 then. The metrics page doesn't use udisks. But I'll check how these snap mounts look like in #15439.
