### ISSUE TITLE
Storage disk bars look like they have the same size

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1543]
In the bars on the storage page all of the disks look like they have the same size. Their light gray bars are all identically large.

https://cloud.githubusercontent.com/assets/795070/5228697/1ee3c158-770e-11e4-8726-1ee0d469f5b8.png

**Comment by dperpeet** [comment]
What's worse in that screenshot is that the actual size is elided in order to show more empty progress bar. The graphics are nice, but I can understand the progress even if it's narrower and I need to see the actual numbers.

**Comment by andreasn** [comment]
> What's worse in that screenshot is that the actual size is elided in order to show more empty progress bar.

That part of the bug has been fixed since.

**Comment by andreasn** [comment]
Dumping some prior art here:
Windows 8.1: http://media.askvg.com/articles/images5/Windows_8_1_Explorer_Single_Section.png
Zyksel NAS: http://static.trustedreviews.com/94/27e7c1/7e43/4346-zyxel2.gif
FreeNAS: https://images.duckduckgo.com/iu/?u=http%3A%2F%2Ffarm3.staticflickr.com%2F2153%2F2048111210_09f947bc16.jpg&f=1
Windows Server 2012: https://erpcoder.files.wordpress.com/2013/04/image_thumb.png?w=1012&h=375

**Comment by dperpeet** [comment]
maybe patternfly or other current software does this better now?

**Comment by a2batic** [comment]
@dperpeet, @stefwalter, @andreasn I would like to work on this issue.

**Comment by a2batic** [comment]
I have come up with following mockups:-
![1543_01](https://cloud.githubusercontent.com/assets/12200504/19415953/336f4bf6-939f-11e6-822f-5802c231b2e7.png)
![1543_02](https://cloud.githubusercontent.com/assets/12200504/19415954/34c7c528-939f-11e6-9294-a9575ac5d185.png)

**Comment by dperpeet** [comment]
That looks nice. I think the question is: what is the most important information? It's a lot easier this eay to see how full a volume is. Do we purposely not use different colors to indicate how full a volume is? How important is it to read the end of the storage volume, i.e. how is text elided (the last part might be very important, but maybe also the beginning). Maybe text shouldn't be elided, only wrapped... Is the mount point not as important? It's grey in that current mockup.

**Comment by a2batic** [comment]
Thanks @dperpeet !!
Yes, we can add different colors and all the information ie the end point of volume and mount point are important. Therefore, I have improved upon the design, and done some experiment for the graphs as well.
![1543_03](https://cloud.githubusercontent.com/assets/12200504/19417008/a6c960c2-93be-11e6-894b-d12caf883a04.png)
![1543_04](https://cloud.githubusercontent.com/assets/12200504/19417009/a9c16acc-93be-11e6-8eac-d1a886bf546a.png)

(I have numbered it 1,2 ,3,4,5, so that, it is easy to point out )

**Comment by andreasn** [comment]
What do the different colors represent in the latest mockup? (1)

**Comment by a2batic** [comment]
@andreasn, I tried different colors:-
1. To show which color looks better
2. To show if colorful looks better

The colors shows the ```filled``` storage space.

**Comment by KKoukiou** [comment]
I think the current state is quite optimal; 
![Screen Shot 2020-03-25 at 21 22 14](https://user-images.githubusercontent.com/14921356/77582199-473a8000-6edf-11ea-83cc-7716d1cd4686.png)
The progress bars are  used from PF and there is always the unit indicator.

The above mockup using different colors for different units is intuitive and also using charts for the filesystem sizes is a bit of an overhead I think.
