### ISSUE TITLE
SELinux follow-ups

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15458]
The SELinux restyling looks great overall!

I noticed there are a few small things, all of which can be seen in this screenshot:

![Screenshot_2021-03-03 SELinux - garrett Rain](https://user-images.githubusercontent.com/10246/109806276-cfafbd80-7c24-11eb-8ee3-557b3b0c9eca.png)

* [x] Too much space between toggle and its label (this may be a PF4 regression: https://github.com/patternfly/patternfly/issues/3880)
  kkoukiou: Indeed it's that bug, let's not track it here. It will be fixed automatically when we update.
* [x] Action to view automation script is not vertically aligned... it should be either vertically centered or baseline (and it's neither)
* [x] Action to view automation script should probably be a button; it should not look like a link, as it doesn't go somewhere, but shows a dialog
* [x] Responsive mode of the tables do not save any space here, but look ugly... as we can adjust the spacing, I'd suggest we don't collapse in this case (this probably applies even moreso to the bottom card's non-list "list")
* [x]  Empty state for the bottom card should not be in the list
* [ ]  Empty state in the bottom card should have an action to resolve, to install the package directly (although this may just be a consequence of looking at it on an rpm-ostree system, where that's not possible)

**Comment by KKoukiou** [comment]
I fixed all items apart from the first ( should be fixed upstream) and the last. 
setroubleshoot-server is a dependency of cockpit-selinux for fedora/centos/rhel. In ubuntu it does not even exist. Therefore I would not even bothering about creating a dialog, since that should be installed by default when the distro provides it.

**Comment by martinpitt** [comment]
Agreed about the empty state -- on Fedora I have to use `rpm -e --nodeps` to uninstall setroubleshoot-server, as it's a dependency of cockpit-selinux. On Ubuntu etc. you wouldn't have cockpit-selinux. So most of the time this would probably show an error like "could not contact setroubleshoot server" when that crashed (which is hopefully not that often either :grin: )
