### ISSUE TITLE
Question: how to append lines to a file?

### ISSUE THREAD

**Issue by RamonGiovane** [cockpit-project/cockpit#15485]
I want to append new lines to a file.
Does the API provides something more efficient than open a file with `read()`, store the old content, then append the new line to the content, like `replace(content + newLine)`?
I've checked the documentation, but could not understand very well the possibilities.

The use of operators such as ` | `or` >>` seems to be blocked by `cockpit.spawn`, which prevents me from using any command like `tee`, `echo`, or `sed`, for example:

`cockpit.spawn(["echo", "'abc'", ">>", "/usr/test.txt"]) `

or

`cockpit.spawn(["echo", "'abc'", "I", "tee", "-a", "/usr/test.txt"]) `

did not work. Any tips?

**Comment by martinpitt** [comment]
Indeed the cockpit.file() API does not support appending.

That cockpit.spawn() syntax more or less uses `execve()` directly. But `>>` is not part of a program/command, but it is shell syntax.

But you can use [cockpit.script()](https://cockpit-project.org/guide/latest/cockpit-spawn.html#cockpit-spawn-script) to run shell snippets. That's syntactic sugar for running `["sh", "-ec", "your shell.. commands"]` through cockpit.spawn(), but looks a little easier. So you can do

    cockpit.script("echo abc >> /tmp/test.txt")

or run any other shell command like pipelines.
