### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by powerriegel** [cockpit-project/cockpit#15481]
Page: 
Some german translations are broken. Where can I fix them?

For example: Storage-Logical volumes -select volume group
Volume tab is translated as loudness. It should either be not translated or you should translate the term "Logical Volume". 

Other wrong translations see screenshot 
![cockpit](https://user-images.githubusercontent.com/11870663/110237711-af8e4000-7f3d-11eb-95b8-4e8f75bab50f.PNG)

**Comment by marusak** [comment]
We translate German here: https://translate.fedoraproject.org/projects/cockpit/master/de/ so ideally if you would register there and translate it directly. Thank you!

Mind you, you seem to be using old version of Cockpit and these strings have been already fixed. But there is still a lot to translate/improve in German translations.
