### ISSUE TITLE
Cockpit is stuck loading "applications" indefinitely

### ISSUE THREAD

**Issue by Etile0** [cockpit-project/cockpit#15482]
Cockpit version: 215
OS: Ubuntu 20.04.2 LTS focal x86_64
Page: Applications

When I go to the "Applications" page there's a spinning loading bar which never finishes loading. 

I don't see anything in the logs that would suggest why this is happening.

Here is a screenshot of what I see:
![image](https://user-images.githubusercontent.com/58475290/110248489-880d9680-7f82-11eb-8331-64c5a76951af.png)

Please tell me how to fix this. Other than this issue this is a fantastic program which does exactly what I wanted it to!

**Comment by KKoukiou** [comment]
@Etile0 do you see some errors in the browser console?

**Comment by Etile0** [comment]
@KKoukiou no

**Comment by Etile0** [comment]
nevermind, I upgraded my ubuntu and when I looked at cockpit again it was fixed. Maybe it was fixed in a later version because now my version is 227.
