### ISSUE TITLE
Hangs on Create Partition

### ISSUE THREAD

**Issue by 0byt3** [cockpit-project/cockpit#15519]
Cockpit version: 224.2
OS: ovirt-node 4.4.4 (CentOS 8)
Page: Storage

When I create a partition the page hangs on creating the partition

Steps to reproduce

1. Go to storage
2. Click create partition
3. Fill in details
4. Click create partition

**Comment by KKoukiou** [comment]
Closing this issue as its very old ,using a old cockpit version and it's also not reproduceable on centos-8 with latest avaiable cockpit.

@0byt3 if you still use cockpit-storage and you encounter this, please comment with journal logs, and we will reopen it.
