### ISSUE TITLE
kdump: the label of the switch is misaligned

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#15511]
Spotted on: cockpit-239

![misaligned-kdump](https://user-images.githubusercontent.com/14921356/110915229-a7584b00-8317-11eb-97d8-0f1a545dab68.png)

This happends because we use link as the switch label. This is not expected usage of the Switch component, and maybe we want to reapproach the design of this line.

**Comment by garrett** [comment]
The kdump page itself is odd. It would make sense to port it to a more modern layout (and fix this in the process) anyway.

The parent of the switch is a `<div role="group">`, and it'd need something like the following:

```
.pf-c-description-list__group > div[role=group] {
 display: flex;
 align-items: center;
}
```

But, again, I think this page really needs a proper port to PF4 (and issues like these should hopefully just be solved by default).

**Comment by KKoukiou** [comment]
> ```css
> .pf-c-description-list__group > div[role=group] {
> ```

What does it mean a proper port to PF4? This is actually a pure PF4 page. The only issue I see here is that we use a link inside a switch label, which is not the expected way to use that component.

**Comment by KKoukiou** [comment]
> The kdump page itself is odd. It would make sense to port it to a more modern layout (and fix this in the process) anyway. It should look more like the SELinux or Firewall pages.
> 
> The parent of the switch is a `<div role="group">`, and it'd need something like the following:
> 
> ```css
> .pf-c-description-list__group > div[role=group] {
>  display: flex;
>  align-items: center;
> }
> ```
> 
> But, again, I think this page really needs a proper port to PF4 (and issues like these should hopefully just be solved by default).


What does it mean a proper port to PF4? This is actually a pure PF4 page. The only issue I see here is that we use a link inside a switch label, which is not the expected way to use that component.

**Comment by KKoukiou** [comment]
Update: i see now what you mean here @garrett. The page is pF4 but the Switch is not used in the expected way, resulting on the alignment issue, I will post a fix.

**Comment by garrett** [comment]
Right, that's some of it.

The page itself doesn't have a typical layout either. It sticks out like a sore thumb compared to the rest of Cockpit. It should be changed to resemble other pages.

Both the SELinux and Firewall pages have headings with toggles; I mentioned them due to that. And the rest should be a typical form layout like we have elsewhere in Cockpit.

**Comment by KKoukiou** [comment]
@garrett so I tried to make the link and the icon part of the label.

```
diff --git pkg/kdump/kdump-view.jsx pkg/kdump/kdump-view.jsx
index ef7c51bdc..100b4ecc8 100644
--- pkg/kdump/kdump-view.jsx
+++ pkg/kdump/kdump-view.jsx
@@ -499,14 +499,13 @@ export class KdumpPage extends React.Component {
                             <DescriptionListGroup>
                                 <DescriptionListTerm>{_("kdump status")}</DescriptionListTerm>
                                 <DescriptionListDescription>
-                                    <div role="group">
-                                        <Switch isChecked={!!serviceRunning}
-                                                onChange={this.props.onSetServiceState}
-                                                aria-label={_("kdump status")}
-                                                isDisabled={this.props.stateChanging} />
-                                        {serviceWaiting}
-                                        {kdumpServiceDetails}
-                                    </div>
+                                    <Switch isChecked={!!serviceRunning}
+                                            onChange={this.props.onSetServiceState}
+                                            label={<>
+                                                {serviceWaiting}
+                                                {kdumpServiceDetails}
+                                            </>}
+                                            isDisabled={this.props.stateChanging} />
                                 </DescriptionListDescription>
                             </DescriptionListGroup>
```

This is resulting in incorrect behavior. In specific when clicking on the switch'es label the switch should the focus. Now it just gets redirected to the services page.

**Comment by garrett** [comment]
I just think we shouldn't have this workaround CSS, but should use pure PF4 for some additional layout, in other words. I think fixing the alignment is a tiny little patch for a page with more serious visual issues (caused by unique HTML usage).

**Comment by garrett** [comment]
> This is resulting in incorrect behavior. In specific when clicking on the switch'es label the switch should the focus. Now it just gets redirected to the services page.

OK, that's weird.
