### ISSUE TITLE
Sudo error dialogs should look like error dialogs

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15536]
The modal dialog that shows up with sudo errors currently looks like:

![image](https://user-images.githubusercontent.com/3228183/107507477-4c142b00-6ba8-11eb-91ce-246614b737ac.png)

It has these issues:

1. Heading should indicate that there's an error; something more like "Problem becoming administrator"
2. Error icon is missing from the heading
3. Inline error is styled incorrectly... the whole dialog is the notification (the docs linked below show how it should look)
4. It has two content bodies... it should only have one
5. The close button should be styled like a button

For reference, here's what error dialogs should look like: https://www.patternfly.org/v4/components/modal/design-guidelines/#error-dialogs

The button should be either primary or secondary. Link styled buttons should never be used, except for a cancel action (and when there's an action dialog).

In this case, if there's no action to accomplish something (like "retry"), then "close" itself is the default action (as it is here), and should be a button that looks like a button.

**Comment by garrett** [comment]
Mockup:

![Screenshot_2021-03-16 PatternFly 4 • Modal](https://user-images.githubusercontent.com/10246/111334236-ab67ce00-8673-11eb-927b-2482c3b99834.png)

React code I used on the PF site:

```jsx
        <Modal
          variant={ModalVariant.small}
          title="Problem becoming administrator"
          position="top"
          isOpen={isModalOpen}
          onClose={this.handleModalToggle}
          titleIconVariant="warning"
          actions={[
            <Button key="close" variant="primary" onClick={this.handleModalToggle}>
              Close
            </Button>
          ]}
        >
          junior is not in the sudoers file. This incident will be reported.
        </Modal>
```

I'm sure it's not 1:1 correct, but it's probably a start.

If you have better suggestions for the title of the modal, I'd love to hear it. The requirements: Should state that there is an issue of some sort and it should be clear.

**Comment by garrett** [comment]
It's debatable if it should be a warning of error. I only went with error because that's what the default example went with.

Change `warning` to `danger` and it becomes this:

![Screenshot_2021-03-16 PatternFly 4 • Modal(1)](https://user-images.githubusercontent.com/10246/111335261-89228000-8674-11eb-94a2-9e48cefce4a7.png)

On one hand, nothing broke and nothing happened that can't be undone. So it's not dangerous. On the other, it's a critical step to doing anything else, so it's an important error instead of a warning.

So keeping it at the "danger" level is probably more appropriate than just a warning.

**Comment by garrett** [comment]
Also, I went with a secondary action here as you're not actually performing an action. You're acknowledging that the dialog exists and dismissing it... but not doing anything in particular otherwise. Still, looking like a button for the singular action is important, which is why it has more emphasis than a borderless link-styled "cancel" button, even if it's more-or-less functionally equivalent.

**Comment by mvollmer** [comment]
I have started to fix this as part of #15293, since it produces a lot more pure error dialogs than master does right now.

Here is the current state:

#### When clicking on "Administrative access" to drop privileges:

![image](https://user-images.githubusercontent.com/3228183/112277312-4ec76d00-8c8a-11eb-90e8-6f39727f5bd1.png)

(Note that the title says "Switch to limited access" and not "Limited access".)

#### When clicking on "Limited access" to gain privileges

![image](https://user-images.githubusercontent.com/3228183/112277559-8fbf8180-8c8a-11eb-88d5-450d55296ad4.png)

Note that it doesn't say "Switch to administrative access".  The "[sudo] password for junior:" string comes straight from the sudo executable.

#### After pressing "Authenticate"

![image](https://user-images.githubusercontent.com/3228183/112278129-2f7d0f80-8c8b-11eb-8fed-7792e5b4a96e.png)

#### When mistyping the password

![image](https://user-images.githubusercontent.com/3228183/112277780-c2697a00-8c8a-11eb-85bd-af3366ba5a63.png)

The "Sorry, try again" text comes straight from sudo.

#### When mistyping the password three times

![image](https://user-images.githubusercontent.com/3228183/112277887-e6c55680-8c8a-11eb-8900-cab1699cca0c.png)

The "sudo: 3 incorrect password attempts" comes from sudo.

#### When your account can't get admin privs

![image](https://user-images.githubusercontent.com/3228183/112278547-a1edef80-8c8b-11eb-9b3a-ba39f0f2772d.png)

#### When sudo gives you admin access without needing a password

![image](https://user-images.githubusercontent.com/3228183/112278976-10cb4880-8c8c-11eb-91fe-40dca9be1f8b.png)

#### When sudo asks a non-standard question

![image](https://user-images.githubusercontent.com/3228183/112286297-d665a980-8c93-11eb-9897-f7c91ece8ab6.png)

#### When sudo lectures first time users

![image](https://user-images.githubusercontent.com/3228183/112285662-3b6ccf80-8c93-11eb-8007-153a841bc25d.png)

**Comment by mvollmer** [comment]
So we need to at least make these changes:

- Use "Switch to administrative access" instead of "Administrative access" as the dialog title when there is a text input.
- Move the error alert to the top.

**Comment by garrett** [comment]
1. It's weird that there's [sudo] in the prompts.
2. "We trust... with great power comes great responsibility" is just weird firstly, and secondly, is not an error.
3. I'm glad you're moving the alerts at the top.
4. "Sorry, try again." is not a valid error message. It needs to cover three points. See: https://www.patternfly.org/v4/ux-writing/error-messages
   1. Description: What happened? (Example: The user's login failed.)
      - Sorry doesn't explain what happens. It should be something like _"Authentication failed"_.
   2. Reason: Why did it happen? (Example: SSH key isn't allowing auto-login.)
      - _"Password does not match"_ (if sudo even gives the reason like this)
   3. Resolution: How can it be resolved? (Example: Manually log in to the host.)
      - "Try again" works here, as long as there's a way to try again... which there is in this dialog, thankfully.
   - All together, it would be _"Authentication failed: Password does not match. Try again."_
   - If sudo doesn't give the reason, then it could be: _"Authentication failed. Try again."_
   - "_Please"_ is intentionally left out, as recommended @ https://www.patternfly.org/v4/components/empty-state/design-guidelines/#title-and-body
      > There is also no need to be overly mannerly, so avoid using please, unless the user is being inconvenienced.
5. Incident will be reported is always odd...

   [![He sees you when you're sleeping, he knows when you're awake, he's copied on /var/spool/mail/root, so be good for goodness' sake](https://imgs.xkcd.com/comics/incident.png)](https://xkcd.com/838/)

Overall, it's already a lot better, and it'll be mostly solved when you move alerts above and address a few points above.

**Comment by mvollmer** [comment]
>     1. It's weird [...]

Yes, this is sudo...

We can translate a couple of specific sudo phrases into something more proper:

"[sudo] password for ...:" -> "Password for ..."

"... is not in the sudoers file. This incident will be reported" -> "... is not allowed to gain administrative access"

"We trust you have received ..." -> <blank>

What do you think?

**Comment by garrett** [comment]
> We can translate a couple of specific sudo phrases into something more proper

How would that work for translations though?

Sudo should output to another language, and we'd have to catch that. This is screen scraping, basically, right? Additionally, it's fragile because sudo could change the strings at any time (and on any version on any supported OS, including patches). The liklihood of sudo changing the strings is slim, but still possible.

I guess we could tell `sudo` to run in `LANG=C` or something silly too? :laughing: 

Anyway, even if we handled that, we'd still have to also handle the cases where it doesn't fix up the strings and then it'd show unformatted sudo strings (possibly even in the wrong language) in the UI. :shrug:

**Comment by martinpitt** [comment]
In some cases we actually *want* that -- e.g. if sudo PAM is configured to ask for a second factor, or to swipe a fingerprint or similar. So this can only ever be an opportunistic translation.

Also, if sudo is *not* in English, then it's not too bad to just show the string directly, as it's already translated?

We can only paper over sudo so far, but in the end that's what everyone uses on the command line -- so in Linux you kind of have to be familiar to it anyway.

**Comment by mvollmer** [comment]
> > We can translate a couple of specific sudo phrases into something more proper
> 
> How would that work for translations though?

The "something more proper" would be localized, something like 

```
msg.replace(/[sudo] password for (.+):/, _("Password for $1"))
```

The replacement would "Password $1" would be subject to our own l10n machinery.

Whether or not to put sudo into LANG=C, good question. Whatever we do, it will be imperfect. But I think it is less likely that non-standard messages from custom PAM stacks will be properly localized by their authors, so I propose LANG=C.

**Comment by garrett** [comment]
But my point about languages still stands. If we scrape and replace (or modify), that would only work in English, not other languages.

**Comment by martinpitt** [comment]
`msgunfmt /usr/share/locale/de/LC_MESSAGES/sudo.mo` indeed does not show much interesting stuff that users should see at runtime -- most of it is translated help and usage errors. The main messages we are interested in come from PAM anyway, plus the 

So running sudo under `LC_MESSAGES=C.UTF-8` seems ok to me (let's not restrict to ANSI with `C` and let's not destroy e.g.  time localization).

**Comment by mvollmer** [comment]
There is also /usr/share/locale/de/LC_MESSAGES/sudoers.mo which seems to have the interesting stuff, like the password prompt and the lecture.

**Comment by mvollmer** [comment]
So we could add patterns for all localized variants of the messages we want to match, such as `[sudo] password for %p:` and also `sudo] Passwort für %p: `. It would still be screen scraping, but it would be more international.

**Comment by martinpitt** [comment]
@mvollmer: Perhaps it'd make more sense to just drop the `[sudo]` prefix from these messages, and otherwise use them as-is? Translating all of these translations and strings again sounds like a lot of effort and wasted translator time, for a marginaly better result only IMHO.

**Comment by martinpitt** [comment]
In other words.. This is Linux, it uses sudo, let's not try to hide that too much :grin:

**Comment by garrett** [comment]
> msg.replace(/[sudo] password for (.+):/, _("Password for $1"))

If we do want to ensure the sentence is capitalized, but don't want to rewrite all the strings, we could do something like:

```css
.sudo-output::first-letter { text-transform: capitalize; }
```

Assuming the sudo output has a class of `sudo-output` (but it could be anything; I just used that as an example here).

**Comment by mvollmer** [comment]
> @mvollmer: Perhaps it'd make more sense to just drop the `[sudo]` prefix from these messages, and otherwise use them as-is?

Yes, that makes sense to me as well.

**Comment by mvollmer** [comment]
Current state:

#### When clicking on "Limited access" to gain privileges

![image](https://user-images.githubusercontent.com/3228183/114690751-ae5fe800-9d1f-11eb-8fb2-a7d541bfa02b.png)

The "Password for junior:" string is a polished version of "[sudo] password for junior:" which comes straight from the sudo executable. "[sudo] " is dropped, "password" is capitalized.

#### After pressing "Authenticate"

![image](https://user-images.githubusercontent.com/3228183/114691159-0bf43480-9d20-11eb-8d69-e7b3271e55f7.png)

#### When mistyping the password

![image](https://user-images.githubusercontent.com/3228183/114691227-1dd5d780-9d20-11eb-88ac-479c38b70cdd.png)

The "Sorry, try again" text comes straight from sudo.

#### When mistyping the password three times

![image](https://user-images.githubusercontent.com/3228183/114691329-3a720f80-9d20-11eb-8fa7-4bc964d4412f.png)

The "sudo: 3 incorrect password attempts" comes from sudo.

#### When your account can't get admin privs

![image](https://user-images.githubusercontent.com/3228183/114691530-7311e900-9d20-11eb-848d-14d6ba955da1.png)

#### When sudo gives you admin access without needing a password

![image](https://user-images.githubusercontent.com/3228183/114691896-cedc7200-9d20-11eb-9b67-47b76ec7097b.png)

#### When sudo asks a non-standard question

![image](https://user-images.githubusercontent.com/3228183/114692119-ff241080-9d20-11eb-90cd-bff165ee406f.png)

#### When sudo lectures first time users

![image](https://user-images.githubusercontent.com/3228183/114692394-414d5200-9d21-11eb-9d39-d124ddcae09d.png)

**Comment by mvollmer** [comment]
Ok, now everything that sudo outputs before the first prompt is just a warning:

![image](https://user-images.githubusercontent.com/3228183/114694234-00563d00-9d23-11eb-9f50-c992e75741ac.png)

**Comment by mvollmer** [comment]
A couple dialogs in "Deutsch":

![image](https://user-images.githubusercontent.com/3228183/114695041-d3eef080-9d23-11eb-8dca-b8ef09c7bc1e.png)

![image](https://user-images.githubusercontent.com/3228183/114695137-ef59fb80-9d23-11eb-9a90-682e73957477.png)

![image](https://user-images.githubusercontent.com/3228183/114695185-026ccb80-9d24-11eb-9d27-e4427c85ca27.png)

![image](https://user-images.githubusercontent.com/3228183/114695347-30eaa680-9d24-11eb-8a52-28a467a78a10.png)

![image](https://user-images.githubusercontent.com/3228183/114695403-4069ef80-9d24-11eb-9710-da6cd4846233.png)

**Comment by martinpitt** [comment]
@mvollmer : Amazing! IMHO this strikes exactly the right balance: Keeping sudo messages and translations as close as possible to sudo, with making it reasonably tasteful without too much effort and long-term maintenance. Cheers! :clap:

**Comment by garrett** [comment]
Agreed. This works for me.

The strings are not ideal, but we tried hashing it out other ways, and this is the best compromise for all the reasons @martinpitt states. :+1: 

BTW: I have a pending fix for the alert sizes, so they won't be so in-your-face big when that lands.
