### ISSUE TITLE
TestLogin.testConversation sometimes invokes sudo

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#15544]
Recently I saw several instances of [this test failure](https://logs.cockpit-project.org/logs/pull-15543-20210317-032630-7a4e80e4-debian-testing/log.html#197):
```
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
sudo: 3 incorrect password attempts
```
The [journal](https://logs.cockpit-project.org/logs/pull-15543-20210317-032630-7a4e80e4-debian-testing/TestLogin-testConversation-debian-testing-127.0.0.2-2301-FAIL.log.gz) confirms this:
```
Mar 17 03:52:05 debian root[31264]: COCKPITTEST: start TestLogin.testConversation
Mar 17 03:52:05 debian sudo[31188]:    admin : 3 incorrect password attempts ; PWD=/run/user/1002 ; USER=root ; COMMAND=/usr/bin/cockpit-bridge --privileged
Mar 17 03:52:05 debian cockpit-ws[31188]: sudo: 3 incorrect password attempts
Mar 17 03:52:05 debian sudo[31199]:    admin : a password is required ; PWD=/run/user/1002 ; USER=root ; COMMAND=validate
Mar 17 03:52:05 debian systemd[1]: systemd-timedated.service: Succeeded.
Mar 17 03:52:05 debian systemd[1]: session-132.scope: Succeeded.
Mar 17 03:52:05 debian systemd[1]: Stopped Session 132 of user admin.
```
This also happened on CentOS 8 and other OSes, it's not OS specific. 

This is a bit hard to reproduce locally. But I don't understand it conceptually -- this test is not *meant* to attempt sudo authentication. It just checks the initial login page.

*If* this test legitimately does superuser escalation, then fixing it is trivial (`self.allow_failed_sudo_journal_messages()`), but I don't see a good justification for it.

@mvollmer, do you have any idea about this?

**Comment by martinpitt** [comment]
[still happens](https://logs.cockpit-project.org/logs/pull-15668-20210408-142703-164c3689-debian-testing/log.html#149)

**Comment by mvollmer** [comment]
> But I don't understand it conceptually -- this test is not _meant_ to attempt sudo authentication. It just checks the initial login page.

The test does a full login.  The `Browser.try_login` method will by default request to run sudo. But that should always succeed. So the question is why sudo sometimes fail.

**Comment by martinpitt** [comment]
@mvollmer: Thanks! I keep mixing up that our login process now does not involve sudo by default any more, but our test API does..

**Comment by mvollmer** [comment]
Both failures run testExpired before testConversation in the same machine.  testExpired changes the password of admin and it might not get restored.  But why does the login succeed at all... I'll dig into this.

**Comment by martinpitt** [comment]
@mvollmer: nonDestructiveSetup() restores all of passwd, group, shadow, and /home/* for each nondestructive test.

**Comment by mvollmer** [comment]
I had it fail once locally, and I keep trying to figure something out.  If that takes too much effort, I think we can use `superuser=False` with try_login, since this test isn't really about sudo.

**Comment by mvollmer** [comment]
Alright, I think the offending journal messages are produces by testExpires but are treated as part of testConversation.

```
Apr 12 08:52:21 debian root[2545]: COCKPITTEST: start TestLogin.testConversation
Apr 12 08:52:22 debian systemd[1]: Reloading.
Apr 12 08:52:22 debian sudo[2464]:    admin : 3 incorrect password attempts ; PWD=/run/user/1002 ; USER=root ; COMMAND=/usr/bin/cockpit-bridge --privileged
Apr 12 08:52:22 debian cockpit-ws[2464]: sudo: 3 incorrect password attempts
Apr 12 08:52:22 debian sudo[2485]:    admin : a password is required ; PWD=/run/user/1002 ; USER=root ; COMMAND=validate
Apr 12 08:52:22 debian systemd[1]: Starting Cockpit motd updater service...
Apr 12 08:52:22 debian systemd[1]: cockpit-motd.service: Succeeded.
Apr 12 08:52:22 debian systemd[1]: Finished Cockpit motd updater service.
Apr 12 08:52:22 debian systemd[1]: Starting Socket for Cockpit Web Service http-redirect instance.
Apr 12 08:52:22 debian systemd[1]: Starting Socket for Cockpit Web Service http instance.
Apr 12 08:52:22 debian systemd[1]: Starting Socket for Cockpit Web Service https instance factory.
Apr 12 08:52:22 debian systemd[1]: Listening on Socket for Cockpit Web Service http-redirect instance.
```

The sudo error appears after the `COCKPITTEST: start TestLogin.testConversation` message but before cockpit.service is started for this test. 

This makes sense since sudo delays asking for input by a few seconds and thus takes a few seconds to actually fail and produce it's output.

**Comment by mvollmer** [comment]
So we would need to wait after a test until all cockpit sessions are closed, I guess.  Hopefully sudo isn't able to escape this.
