### ISSUE TITLE
Weblate: set propagation for rhel-7 component

### ISSUE THREAD

**Issue by rffontenelle** [cockpit-project/cockpit#15550]
When translating cockpit's strings on [Fedora Weblate](https://translate.fedoraproject.org/projects/cockpit/), translation of strings can be set to propagated across the components of the same project, so that multiple components receive the exact same translation. This is perfect to assure consistency for the same strings across components. Cockpit project on Weblate has 3 components: master, rhel8 and rhel-7.

Currently, cockpit has propagation between the [master](https://translate.fedoraproject.org/projects/cockpit/master/) e [rhel8](https://translate.fedoraproject.org/projects/cockpit/rhel8/) components, but not to [rhel-7](https://translate.fedoraproject.org/projects/cockpit/rhel-7/) component. This means that translations sent to master are synced with rhel8, but not with rhel-7.

Please consider setting propagation in rhel-7 component too, so that all 3 components receive the same string.

Steps to reproduce

1. Go to a translation string from master component (e.g. string ["$0 Network"](https://translate.fedoraproject.org/translate/cockpit/master/pt_BR/?checksum=8756371e136ae0da&sort_by=-priority,position))
2. Access the "Other occurrences" tab right below the source string and target textarea elements.
3. See more than one component mentioned in there, (i.e. the current one, master, and other one, rhel8)
4. Now, check the same string now from rhel-7 component (again, ["$0 Network"](https://translate.fedoraproject.org/translate/cockpit/rhel-7/pt_BR/?checksum=6a897de69710dfdb&sort_by=-priority,position))
5. Notice how there is no "Other occurrences" tab, meaning there is no other occurrence of the same string or, in this case, propagation is not set with other components of the same project.

Screenshot of the master component, "Other occurrences" tab visible:

![Captura de tela de 2021-03-17 10-55-51](https://user-images.githubusercontent.com/1571783/111479297-98a2d700-870f-11eb-9593-359167256820.png)

Screenshot of the rhel-7 component, without a "Other occurrences" tab:

![Captura de tela de 2021-03-17 10-57-19](https://user-images.githubusercontent.com/1571783/111479312-9ccef480-870f-11eb-83d1-43bd70d0e1a4.png)

**Comment by marusak** [comment]
Rhel-7 is frozen. We won't take updates from this branch anymore so there is no need to translate it there.
Last time I've locked component in weblate it kicked me out and produced warning I could not deal with. Thus I want to avoid doing that again, but I've added warning that this component is locked.

**Comment by rffontenelle** [comment]
@marusak Would it be possible to removed this component from Weblate then?
