### ISSUE TITLE
_netdev option for storage auto mount

### ISSUE THREAD

**Issue by aaronprisk** [cockpit-project/cockpit#15556]
Cockpit version: 238.1
OS: Debian 10
Page: Storage

After adding a new Filesystem to an ISCSI-based storage device, Cockpit will prompt the user to enable the filesystem mounting at boot. Using the defaults boot option in fstab, the machine will sometimes try to mount the filesystem prior to the networked device being ready which causes the machine to hang or sometimes fail to properly boot.

Replacing **defaults** with **_netdev** in the new /etc/fstab entry resolves the issue.

Is it possible for cockpit to recognize the filesystem is living on a networked storage medium and add the _netdev option automatically?

**Comment by mvollmer** [comment]
Part of this works already: Cockpit detects iSCSI devices and adds _netdev automatically when formatting a new Filesystem on it. 

However, Cockpit does not detect existing filesystems on iSCSI devices that are missing the "_netdev" option.  Is that what you are after?

Cockpit might also fail to detect your iSCSI devices.

**Comment by martinpitt** [comment]
No response in almost a year, and apparently already fixed.
