### ISSUE TITLE
Authentication failed: timeout

### ISSUE THREAD

**Issue by q2dg** [cockpit-project/cockpit#15572]
Cockpit version: 239
OS: Fedora 33 (Workstation Edition)

I've just installed Cockpit package from official Fedora repository and started Cockpit's socket (_sudo systemctl start cockpit.socket_). Nothing else. When I want to go to https://my.IP:9090 and I want to insert my local username and its password, I get stuck some seconds and then I get this error: "Authentication failed: timeout" (as it can be seen in shown screenshot).

![Captura de pantalla de 2021-03-22 15-06-29](https://user-images.githubusercontent.com/7274874/112002470-350a1680-8b20-11eb-96eb-9784dc5b0b6a.png)

For the record: my username is fine: I can start a session with gdm, with su, etc without problem. In fact, what it's "interesting" is that if I write a wrong user or password, then I get the correct error message ("Wrong user name or password")...I mean that in this circumstance there's no any timeout.

Output of _journalctl _COMM=cockpit-session _COMM=cockpit-ws _COMM=polkitd  -e --no-pager_ command doesn't give me any clue, nor the output of _journalctl -u cockpit -e --no-pager_ command. Both outputs are shown below (note I have SELinux disabled).

![Captura de pantalla de 2021-03-22 15-18-45](https://user-images.githubusercontent.com/7274874/112004472-1f95ec00-8b22-11eb-9301-5209f631eb17.png)

![Captura de pantalla de 2021-03-22 15-21-02](https://user-images.githubusercontent.com/7274874/112004900-887d6400-8b22-11eb-820f-07fd25725814.png)

Thanks a lot!

**Comment by martinpitt** [comment]
Could you please check `journalctl -f` while you are trying to log in? Apparently the session does start, but quickly gets stopped again after 30 seconds. I am hoping that the journal will show some relevant things outside of cockpit-ws, such as SELinux violations or D-Bus service messages. In particular, I'm a bit suspicious about the polkit agent registration taking that long.

Do you use any non-default PAM/authentication setup? Fingerprint readers, IPA, kerberos, sssd, etc.?

If you run `pkexec whoami` in a Terminal on your desktop, does that work? You should be asked for your password and then get an output "root".

**Comment by q2dg** [comment]
Hello. Thanks for your interest! I've collected in the attached file the output of journalctl -f while trying to log in... I hope it helps.

I don't use any non-default PAM/authentication setup: nor fingerprint neither IPA/Kerberos/sssd...just plain /etc/passwd file

I've also run _pkexec whoami_ as you suggest and it works as expected.

The only "strange" thing my system has is SELinux disabled.

Thanks a lot again.

[cockpit.log](https://github.com/cockpit-project/cockpit/files/6196551/cockpit.log)

**Comment by andy47** [comment]
Hi, I'm getting exactly the same problem on a fresh installation on Ubuntu 20.04. I get the same behaviour if I try and log in locally or remotely.  I ran `journalctl -f` in a terminal whilst I tried to logon and pasted the output into the attached file. Any pointers to help fix this are very welcome.

[cockpit.log](https://github.com/cockpit-project/cockpit/files/6438054/cockpit.log)

**Comment by rlad78** [comment]
Hi all. I had the same exact issue and couldn't figure out for the life of me what the hell was happening. I thought maybe Cockpit was not allowing me to log in as root for some reason.

Not sure if this'll work for everyone else's case, but I resolved my issue by changing the password of the user I was logging in with. I went from a 33 character long password to a 16 char long one, and it works now!

**Comment by q2dg** [comment]
Well, that's not my case. There must be something wrong with my regular desktop login user and Cockpit because I've created a brand new user (_sudo useradd -m pepito && sudo passwd pepito_) and I've given him sudo privileges (_sudo usermod -a -G wheel pepito_) and it enters well inside Cockpit. So I don't know which is the problem. 

As a workaround, I'll use this "secondary" user to enter exclusively in Cockpit besides my regular desktop user, then.
I'll keep this issue open, anyway.
Thanks

**Comment by martinpitt** [comment]
This is stale and there is no actionable information here, I'm afraid. If you still get this issue with current versions, please report back here, and I'll reopen.

**Comment by cprecioso** [comment]
Hi @martinpitt, I am getting this error message as well.

<img width="871" height="354" alt="Image" src="https://github.com/user-attachments/assets/baa6af4f-69d8-4604-b9fc-66064faaa943" />

I am on `Fedora CoreOS 43.20260202.3.1` with `Cockpit 356`.

`journalctl -f`:
```
Feb 23 10:15:31 tuareg systemd[1]: Started cockpit-session@5-4100-6791_6792-63714.service - Cockpit session 5/4100/6791_6792/63714 (PID 6791/UID 63714).
Feb 23 10:15:31 tuareg audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=cockpit-session@5-4100-6791_6792-63714 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 23 10:15:31 tuareg cockpit-session[6814]: pam_unix(cockpit:auth): user [carlos] has blank password; authenticated without it
Feb 23 10:15:31 tuareg audit[6814]: AUDIT1100 pid=6814 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='op=PAM:authentication grantors=pam_unix acct="carlos" exe="/usr/libexec/cockpit-session" hostname=::ffff:100.73.89.87 addr=::ffff:100.73.89.87 terminal=? res=success'
Feb 23 10:15:31 tuareg audit[6814]: AUDIT1101 pid=6814 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='op=PAM:accounting grantors=pam_listfile,pam_unix acct="carlos" exe="/usr/libexec/cockpit-session" hostname=::ffff:100.73.89.87 addr=::ffff:100.73.89.87 terminal=? res=success'
Feb 23 10:15:31 tuareg audit[6814]: AUDIT1103 pid=6814 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='op=PAM:setcred grantors=pam_unix acct="carlos" exe="/usr/libexec/cockpit-session" hostname=::ffff:100.73.89.87 addr=::ffff:100.73.89.87 terminal=? res=success'                                                          
Feb 23 10:15:31 tuareg cockpit-session[6814]: pam_ssh_add: Failed adding some keys
Feb 23 10:15:31 tuareg systemd-logind[1020]: New session '8' of user 'carlos' with class 'user' and type 'web'.                                                    
Feb 23 10:16:01 tuareg cockpit-ws[6791]: session: session timed out during authentication                                                                          
Feb 23 10:16:01 tuareg cockpit-ws[6791]: session: authentication timed out                                                                                         
```

If useful, this is the bootc image of the OS: https://github.com/cprecioso/homelab/pkgs/container/homelab-system/700361454?tag=latest
Made from this Dockerfile: https://github.com/cprecioso/homelab/blob/main/system/Dockerfile
