### ISSUE TITLE
storage: List hovering is inconsistent and does not look clickable

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15586]
1. Cursor does not change
2. Color is wrong (should be a PF color based on the link color, but lighter)
3. Text does not change (you're visiting the disk, not its size or the location on the filesystem)

![storage-list-sidebar](https://user-images.githubusercontent.com/10246/112346795-953abd00-8cc6-11eb-96c9-2aec05bf13d0.png)

4. There's no affordance other than changing color (underline and/or background color)

![storage-filesystem-hover](https://user-images.githubusercontent.com/10246/112346809-9835ad80-8cc6-11eb-8f1d-abd072f6e663.png)

**Comment by KKoukiou** [comment]
https://github.com/cockpit-project/cockpit/issues/15418#issuecomment-824599765
