### ISSUE TITLE
software: Hide automatic updates card on Debian

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15595]
On Debian, it doesn't seem possible to set up automatic updates. The card shows up and just says it's not set up, with no guidance or any way to change it.

Screenshot:
![Screenshot_2021-03-25 Software Updates - admin debian(1)](https://user-images.githubusercontent.com/10246/112483963-cd4f0800-8d79-11eb-9879-ad7e4c2e49e0.png)

**Comment by marusak** [comment]
I am doing restyling of this in https://github.com/cockpit-project/cockpit/pull/15569 (splitting it into status and settings) so I'll take a look. I was actually thinking about this before.

**Comment by martinpitt** [comment]
Implementing the feature is issue #15269 . But indeed on Debian we shouldn't show this box at all until that happens.
