### ISSUE TITLE
Progress bars jump when percentages are the label

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15594]
On at least the software page, possibly on other places, the progressbar width shifts as the numbers increment.

The _proper_ solution would be to use tabular numbers, but our font does not support that (yet). Related: https://github.com/cockpit-project/cockpit/issues/15090 & https://github.com/RedHatOfficial/RedHatFont/issues/27

Therefore, a work-around that we could do right now is to set `min-width: 3ch` on the label. As this would affect anything with a progress bar, we should probably have this as an override.

**Comment by jelly** [comment]
For the "Software Updates" case I reproduced the issue using the `testUpdates.testBasic` test case and extending it with:

```python
+        for i in range(1, 35):
+            pkgname = "test{}".format(i)
+            self.createPackage(pkgname, "1.0", "1", install=True)
+            self.createPackage(pkgname, "1.0", "2", postinst="sleep 1;")
         # create two updates; force installing chocolate before vanilla
```

This makes the issue visible for me.

I also noticed the issue with the CPU/Memory graphs on the `Overview`
