### ISSUE TITLE
cockpit-docker and cockpit-dashboard are not available for Debian-testing

### ISSUE THREAD

**Issue by metzger100** [cockpit-project/cockpit#15603]
I sadly can't install Cockpit-Dashboard on my debian-testing-(bullseye)-Server.
They are not available as package and not as backport for bullseye.
Would be nice if you could add both modules to bullseye. Wanted to install it by downloading the package. But it says that the dependency of cokpit-ws is missing. 
```
needs cockpit-ws (<< 233-1.1~);
Version 239-1 installed
```
greetings Metzger, Germany

**Comment by marusak** [comment]
cockpit-dashboard has been obsoleted
cockpit-docker has been replaced by cockpit-podman
