### ISSUE TITLE
volume size and usage reported incorrectly

### ISSUE THREAD

**Issue by cmurf** [cockpit-project/cockpit#1561]
Cockpit seems confused about Btrfs volume size. It reports the volume as 0.7/1.5 GB (see screenshot):

$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda4        54G  4.8G   48G   9% /
/dev/sda4        54G  4.8G   48G   9% /var
/dev/sda4        54G  4.8G   48G   9% /home

$ stat -f /home
  File: "/home"
    ID: dbcfcb8f2858a147 Namelen: 255     Type: btrfs
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 13998336   Free: 12762956   Available: 12565436
Inodes: Total: 0          Free: 0

The ext4 /boot volumes reports used and total values correctly.
![screen shot 2014-12-05 at 12 27 39 pm](https://cloud.githubusercontent.com/assets/10091077/5321792/bb4c2586-7c7b-11e4-833f-ecd4d1c77b0b.png)

**Comment by cmurf** [comment]
This is still a bug with cockpit-0.41-1.fc22 for both Btrfs and XFS file systems. For example a 16GB USB stick is inserted, it has a single partition that's 14.9 GiB in size, which is XFS formatted, there is one file on the filesystem: 11MiB PDF.

Cockpit Storage > Filesystems UI shows this as:
/dev/sdd1          14.9 GB

If I click this line I'm taken to a new page Storage >> Kingston DT R500, and under Content I click the Mount button. I go to the top part of the page and click on Storage to return to the previous Storage overview page, and under Filesystems I see

/dev/sdd1           0.1 / 2.9 GB

df -h reports this as
Size  Used Avail Use% 
15G   44M   15G   1%

$ stat -f /run/media/chris/054f3320-8599-4c3a-849e-92ad0bd2ba66
  File: "/run/media/chris/054f3320-8599-4c3a-849e-92ad0bd2ba66"
    ID: 83100000000 Namelen: 255     Type: xfs
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 3906811    Free: 3895770    Available: 3895770
Inodes: Total: 15637440   Free: 15637435

So definitely on mounted filesystems cockpit isn't showing even ballpark correct values. I'm not sure where it's getting them from.

**Comment by cmurf** [comment]
So this problem also happens when the USB stick is MBR partitioned, and ext4. At the moment I haven't found the mounted volume sizes in the UI to be even in the ballpark of correct. I'm not sure what's going on.

**Comment by cmurf** [comment]
This is still a bug in cockpit-0.67-1.fc23 where it shows a volume as "-2.8 / 1 GB" which has several problems...

What does cockpit use to get volume size information?

**Comment by mvollmer** [comment]
> This is based on cockpit-0.27-2.fc21.i686

The bogus numbers only show up on 32 bit architectures for the filesystem sizes, right?  Then #3427 will hopefully fix this.

(Sorry for letting this sit for so long, I thought it is much harder to track down.)
