### ISSUE TITLE
Integration tests produce PCP warnings that should be explained

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#15625]
We see these warnings from `cockpit-pcp` in our integration tests. We only discovered them when we cast a wider net for journal messages (in #15599), so it is unknown when they have started.  It would be excellent if we could figure out why they happen.

        pcp-archive: no such metric: blah

This might be harmless and expected since an archive might be from a time when pmlogger didn't log that particular metric that we try to find in it.  Cockpit has its own pmlogconf snippet in /var/lib/pcp/config/pmlogconf/tools/cockpit (which we probably have neglected), so the pmlogger configuration might change when cockpit is installed.

        pcp-archive: instance name lookup failed: blah

This doesn't look so harmless.  This message appears when cockpit-pcp has read a sample from an archive, and that sample contains a list of instance indices, but then pcp can't convert the index into a name. This looks like a corrupted archive.

**Comment by mvollmer** [comment]
There have also been messages about the `direct` source:

```
direct: instance name lookup failed: network.interface.in.bytes.14: Unknown or illegal instance identifier
```

**Comment by martinpitt** [comment]
In #16216 I got a first set of results. These two tests are primarily affected, they fail everywhere:

 -  `test/verify/check-metrics TestGrafanaClient.testBasic`
 - `test/verify/check-metrics TestHistoryMetrics.testNoDataEnable`

And they consistently fail with exactly this one message:
```
pcp-archive: no such metric: kernel.all.cpu.nice: Unknown metric name
```

But this also spuriously happens to networking and storage tests (as these pages also have graphs), e.g. [here](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-16216-20210808-071940-40b7959a-ubuntu-stable/log.html#84) or [here](https://logs.cockpit-project.org/logs/pull-16216-20210808-071940-40b7959a-debian-stable/log.html#207). These fail with:

```
pcp-archive: no such metric: disk.all.read_bytes: Unknown metric name
pcp-archive: no such metric: network.interface.in.bytes: Unknown metric name
```

**Comment by martinpitt** [comment]
> This might be harmless and expected since an archive might be from a time when pmlogger didn't log that particular metric that we try to find in it. 

We can exclude that possibility at least in check-metrics, as the tests all start with a completely clean /var/log/pcp.

The message in `testNoDataEnable` makes perfect sense: It stops pmlogger, the page tries to load the metric, doesn't find any, and the metrics channel shows that message. It seems legit to ignore it there. TestGrafanaClient is in exactly the same situation: It disables pmlogger.service (several times even) and opens the page.

The page has no other chance of probing the metric than trying to read the PCP channel. We should IMHO *not* check whether `pmlogger.service` is running, as historical metrics don't depend on this. I'll update #16216 accordingly.

**Comment by martinpitt** [comment]
> This doesn't look so harmless. This message appears when cockpit-pcp has read a sample from an archive, and that sample contains a list of instance indices, but then pcp can't convert the index into a name. This looks like a corrupted archive.

Could that not just be that no samples from that particular interfaces were collected yet?

**Comment by martinpitt** [comment]
> Could that not just be that no samples from that particular interfaces were collected yet?

Ah no -- at least two of the offending tests ran on nondestructive VMs, and thus pcp should have had plenty of time to collect data.

**Comment by martinpitt** [comment]
Not important enough, closing.
