### ISSUE TITLE
Alerts in cockpit use bigger font-size compared to the Alerts in PF4 docs

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#15639]
These are some alerts from our overview page:
![Screen Shot 2021-04-01 at 14 06 22](https://user-images.githubusercontent.com/14921356/113300668-7196f880-92fe-11eb-8521-904e48659abb.png)

And these are from the PF4 documentation:
![Screen Shot 2021-04-01 at 15 25 50](https://user-images.githubusercontent.com/14921356/113300823-a014d380-92fe-11eb-816f-18c36b1fa4ba.png)

This is some fallout from the PF4-PF3 mix.

**Comment by garrett** [comment]
Whoops! Sorry for reporting it as a duplicate.

Fix is to add this to overrides:

```css
.pf-c-alert__title {
    font-size: inherit;
}
```

And report upstream. (It's not directly related to PF4, but when PF4 is used with anything else whatsoever, it can introduce this problem. Therefore, it should be fixed upstream, as nearly every project uses PF4 and something else from time to time.)

I'll submit a PR and make sure a bug is submitted upstream too.
