### ISSUE TITLE
"cockpit-389-ds" package is missing in the Debian Buster Backports repo

### ISSUE THREAD

**Issue by cermep-pierre** [cockpit-project/cockpit#15635]
Cockpit version: 237
OS: Debian 10
Page: 

"cockpit-389-ds" package in the Debian Buster Backports repo is unavailable.

Steps to reproduce

1. Enable the backports according to https://backports.debian.org/Instructions/, then run apt update.
2. Run apt -t buster-backports search cockpit-389-ds. Only the stable version (188) is found.
3. Run apt install cockpit-389-ds/buster-backports returns an error: E: Release 'buster-backports' for 'cockpit-389-ds' was not found

Screenshot from : https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=cockpit
![cockpit-389-ds_missing](https://user-images.githubusercontent.com/8792513/113271282-a2fdcd00-92da-11eb-968d-fa18da01a228.png)

**Comment by marusak** [comment]
This is external plugin that is not maintained by us.
It lives [here](https://github.com/389ds/389-ds-base/tree/master/src/cockpit/389-console) so please ask in https://github.com/389ds/389-ds-base . Thanks
