### ISSUE TITLE
1 package needs a system reboot

### ISSUE THREAD

**Issue by briandconnolly** [cockpit-project/cockpit#15649]
Cockpit version: cockpit-240-1.fc33.x86_64
OS: Fedora 33
![cockpit](https://user-images.githubusercontent.com/31881084/113482233-4a0d7080-9463-11eb-81a2-9730d3d4ce07.png)

ISSUE: Status in Software Updates indicates, "1 package needs a system reboot." A reboot does not change the status.

**Comment by marusak** [comment]
Can you please provide output of command `tracer`? If this utility states that system needs restart, you restart the system and it still insists on restart it is bug in tracer itself.

**Comment by briandconnolly** [comment]
Indeed, tracer is telling me that I should restart the kernel... and doing that does not change the condition.

Thank you kindly.

**Comment by marusak** [comment]
I see you found https://github.com/FrostyX/tracer/issues/132 so closing
