### ISSUE TITLE
cockpit machines: no settings nor VMs displayed on ubuntu budgie 21.04

### ISSUE THREAD

**Issue by ilvipero** [cockpit-project/cockpit#15641]
Cockpit version: 238
OS: Ubuntu Budgie 21.04
Page: Machines

Opening cockpit on Virtual Machines, none of my configurations shows up. This host as libvirtd already configured with VMs, storage pool, virtual network. It all shows fine on virt-manager and virsh, but cockpit-machines cannot display any of the details. If I try to manually add a pool, I get an error: "Error message: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied". disabling apparmor or changing it to complain mode does not seem to help. 

Same thing seems to be working fine on Ubuntu Budgie 20.10. Same setup, same conditions, same version of Cockpit 238, all works fine out of the box. I can see my VMs, pools, virtual networks.

Please help us out by explaining how to reproduce it.
Install cockpit and cockpit-machines on a Ubuntu Budgie 21.04 that has already libvirtd and virt-manager up and running.

Relevant parts of the system log are also useful:

Apr 02 09:38:10 MGDT-ROG dbus-daemon[1185]: [system] Activating service name='org.libvirt' requested by ':1.133' (uid=0 pid=16624 comm="cockpit-bridge --privileged " label=>
Apr 02 09:38:10 MGDT-ROG dbus-daemon[7289]: [session uid=1000 pid=7289] Activating service name='org.libvirt' requested by ':1.145' (uid=1000 pid=16617 comm="cockpit-bridge>
Apr 02 09:38:10 MGDT-ROG dbus-daemon[1185]: [system] Successfully activated service 'org.libvirt'
Apr 02 09:38:10 MGDT-ROG dbus-daemon[7289]: [session uid=1000 pid=7289] Successfully activated service 'org.libvirt'
Apr 02 09:38:10 MGDT-ROG libvirtd[16698]: libvirt version: 7.0.0, package: 2ubuntu1 (Christian Ehrhardt <christian.ehrhardt@canonical.com> Tue, 23 Feb 2021 12:16:08 +0100)
Apr 02 09:38:10 MGDT-ROG libvirtd[16698]: hostname: MGDT-ROG
Apr 02 09:38:10 MGDT-ROG libvirtd[16698]: Failed to open file '/sys/kernel/security/apparmor/profiles': Permission denied
Apr 02 09:38:10 MGDT-ROG libvirtd[16698]: Failed to read AppArmor profiles list '/sys/kernel/security/apparmor/profiles': Permission denied
Apr 02 09:38:10 MGDT-ROG libvirtd[16698]: Failed to open file '/sys/kernel/security/apparmor/profiles': Permission denied
Apr 02 09:38:10 MGDT-ROG libvirtd[16698]: Failed to read AppArmor profiles list '/sys/kernel/security/apparmor/profiles': Permission denied
Apr 02 09:38:10 MGDT-ROG dbus-daemon[7289]: apparmor="ALLOWED" operation="dbus_method_call"  bus="session" path="/org/freedesktop/DBus" interface="org.freedesktop.DBus" mem>
Apr 02 09:38:17 MGDT-ROG dbus-daemon[1185]: [system] Failed to activate service 'org.freedesktop.Avahi': timed out (service_start_timeout=25000ms)
Apr 02 09:38:17 MGDT-ROG audit[15177]: AVC apparmor="DENIED" operation="capable" profile="/usr/sbin/cups-browsed" pid=15177 comm="cups-browsed" capability=23  capn

Steps to reproduce

1. Upgrade Ubuntu Budgie to 21.04
2. Configure virtualization via virt-manager: storage pool, virtual network, virtual machines
3. Install cockpit and cockpit-machines. Attempt to manage virtual machines.

![cockpit-machines-01](https://user-images.githubusercontent.com/6520987/113371989-2cc09f80-939a-11eb-9ff0-ae5b4f581635.jpg)
![cockpit-machines-02](https://user-images.githubusercontent.com/6520987/113371992-2f22f980-939a-11eb-9026-ba8e91736c84.jpg)

**Comment by martinpitt** [comment]
This smells a lot like https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1802005 -- please try to run `usermod -a -G libvirt libvirtdbus` and see if that helps.

**Comment by ilvipero** [comment]
> This smells a lot like https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1802005 -- please try to run `usermod -a -G libvirt libvirtdbus` and see if that helps.

yes, it did help indeed! After adding the group, rebooting, I can now see all configurations from cockpit-machines. 
I am really sure I have not done that on 20.10 and it worked out of the box. If you need more testing on other 21.04 based ubuntus, please let me know and I will do my best to help out. By the way this 21.04 was a fresh install, not an upgrade.

**Comment by martinpitt** [comment]
Thanks for confirming! Please track this on Launchpad then, for libvirt.
