### ISSUE TITLE
Need to Login all server everytime

### ISSUE THREAD

**Issue by SinaXhpm** [cockpit-project/cockpit#15642]
i added  my all servers but after some hours when i checkout cockpit all of them got a danger icon and when i click on them it show 
```
Couldn't connect to the machine
Login failed
```
and reconnecting buttton dosent work and i have to click on troubleshoot and enter passwords again .....
its normal or something else .... ?!
its too bad to login all of them one by one and everytime whats the solution ?!
![2021-04-02_141401](https://user-images.githubusercontent.com/13718594/113404879-1fb5a780-93be-11eb-8290-1c4267dcd936.jpg)

**Comment by marusak** [comment]
> and reconnecting buttton dosent work

Which button is that?

> and enter passwords again

If you don't use ssh keys, then I would expect that you have to type password every time you get disconnected.

But here is proper answer:
This is from `Dashboard`. That is not a thing anymore - one of big reasons we dropped it was that users confused Cockpit with fleet management tools. Cockpit is not designed to be used with many servers at once. Now you can list your servers in host switcher - but cockpit won't auto-login you to these servers. It is mostly just like ssh config file so you can get to them easily. So the solution is not to connect to all of your machines - it is a bad practice if nothing else.
