### ISSUE TITLE
storage: Long disk names do not wrap when needed

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15669]
On the side panels, when there's a disk with a long name, it looks like this:

![Screenshot_2021-04-08 Storage - admin m1 cockpit lan](https://user-images.githubusercontent.com/10246/114050102-46775080-988c-11eb-830c-5867e03cc6ad.png)

(I'm not sure why that disk has that name; it looks like an encoding issue? That's beside the point for this issue though. Any long name without spaces will break this panel.)

When adding `overflow-wrap: anywhere;` to `.sidepanel-row-name` in `storage.scss`, it fixes the issue and looks like this:

![Screenshot_2021-04-08 Storage - admin m1 cockpit lan(1)](https://user-images.githubusercontent.com/10246/114050468-9524ea80-988c-11eb-8ba9-422d3d0142dc.png)

**Comment by garrett** [comment]
Just to highlight this, the fix is above:

Add `overflow-wrap: anywhere;` to `.sidepanel-row-name` in `storage.scss`

**Comment by KKoukiou** [comment]
I don't say we should not add the overflow-wrap, but these disk names are not really realistic. They are just because of a systemd bug in udev.

**Comment by garrett** [comment]
> these disk names are not really realistic

It's what I'm getting right now.

 > just because of a systemd bug in udev

Is there a fix for it somewhere? Or are our users going to see this?

**Comment by KKoukiou** [comment]
@garrett the bug report is here https://bugzilla.redhat.com/show_bug.cgi?id=1935062 

It's affecting f-34 so some users are going to see it.

**Comment by marusak** [comment]
> It's affecting f-34 so some users are going to see it.

Already fixed and I don't see it anymore on F34.

**Comment by KKoukiou** [comment]
> > It's affecting f-34 so some users are going to see it.
> 
> Already fixed and I don't see it anymore on F34.

Ph good, then I guess we don't need the fix for the wrapping disk names either.

**Comment by garrett** [comment]
I guess we could still add the fix, but on the other hand, I can confirm the issue is fixed in F34.
