### ISSUE TITLE
Cannot refresh cache whilst offline

### ISSUE THREAD

**Issue by ne20002** [cockpit-project/cockpit#15694]
Cockpit version: 239
OS: Debian Bullseye 
Page: Network, General 

I have a problem using Cockpit and/or Debian Bullseye with OpenvSwitch. One of the problems ('Cannot refresh cache whilst offline' during package refresh) seems to be related to not having NetworkManager controlling the main interface?

I started setting up a small NAS with Debian Buster and Cockpit which I wanted to use to host a small number of virtual servers at home (it has just become a few too much Raspberry Pis').
I started trying with a standard Linux bridge but ran into problems when needing to support VLANs for the virtual servers. I then found OpenvSwitch which made setting up KVM with the virtual servers an easy and quick thing.

The only drawback found is, that when using OpenvSwitch, _the network connections are not handled by NetworkManager._

I tried but didn't find a solution to have NetworkManager handle my internal interface on the OVS bridge (the one my host uses). Setting it up in /etc/network/interfaces gave my IPv4 and IPv6 connection, eventhough resolv.conf and some of the router advertisements are not working properly.
I found that I can live with that until I have a solution but then the problem with the not working any more package updates popped up. And that is annoying.

Ain't there a way to

- fix the package update problem somehow (I wonder what configuration made package updates depending on NetworkManager)
- or even better get NetworkManager to take controll over the OVS bridge interface?

Any help welcome.

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit/issues/8477

^ there is explenations why it does not work and a few solutions and workarounds. Hope that helps. Does any of those work for you?

**Comment by ne20002** [comment]
It indeed explains (https://github.com/cockpit-project/cockpit/issues/8477#issuecomment-496096071) why this happens. This matches my case:
Having network on the NIC with the OpenvSwitch lists all connections in nmcli as unmanaged or unavailable and I get a 'Cannot ..'.
Using the second NIC let NM handle the connection and all is fine.
So I probabaly can live with one NIC for access to the host and on NIC exclusive for the OVS and the KVM machines.

Even though: It should be possible with a single interface .. but it seems as if there are dependencies not matched, as
- NM can't handle openvswitch connections on Debian as the NetworkManager-ovs package is not existing and therefor the Network-Manager OVS plugin is missing.
- I can't get NM forced to use/manage the br0 interface of the OVS switch. So I'm stuck with /etc/network/interfaces dhcp stanza for this interface (which also does not get all configuration as it ignores a few router advertised settings)

Thank you very much.

(where ist the correct place to file a ticket for the missig NetworkManager-ovs package in Debian or missing OVS support in NetworkManager?)

**Comment by marusak** [comment]
> where ist the correct place to file a ticket for the missig NetworkManager-ovs package in Debian

In would ask in debian bug tracker: https://www.debian.org/Bugs/ or maintainers of NetworkManager package in debian. 

> missing OVS support in NetworkManager

Depends. If it exists in upstream then still in debian bug tracker. If it does not exist in upstream either, then first ask upstream developers for it.
