### ISSUE TITLE
make install fails with --disable-doc: No rule to make target 'dist/guide/html/index.html', needed by 'install-data-local'

### ISSUE THREAD

**Issue by InfRandomness** [cockpit-project/cockpit#15710]
Cockpit version: xxx
OS: openSUSE Leap 15.3

Hi, I am trying to build cockpit for oS Leap 15.3 (because it is not in the repos).
It appears that makes cannot install that 'dist/guide/html/index.html' file for some reason;
I have tried multiple different --prefix but the same issue occur

Steps to reproduce

1. Install openSUSE leap 15.3
2. Install the toolchain / tools needed to build cockpit
3. Configure it, compile it and try to install it to any directory prefix

![image](https://user-images.githubusercontent.com/43730933/115094011-580bc880-9f1c-11eb-80cf-f286f73f507f.png)
![image](https://user-images.githubusercontent.com/43730933/115094035-6eb21f80-9f1c-11eb-916a-6d99f2489dd8.png)

**Comment by martinpitt** [comment]
Do you have a link to the full build log? Sounds like you either built with `--disable-doc` or the `xsltproc` program is missing? (it should be a build dependency). The spec has `BuildRequires: libxslt-devel`.

**Comment by InfRandomness** [comment]
Yeah, I used --disable-pcp and --disable-doc

**Comment by martinpitt** [comment]
Confirmed that `--disabled-doc` breaks `make install`. Thanks for your report!

**Comment by martinpitt** [comment]
Fixed in PR #15729
