### ISSUE TITLE
Message in web UI - Automatic updates are not set up

### ISSUE THREAD

**Issue by infestdead** [cockpit-project/cockpit#15712]
Cockpit version: cockpit-242-1.fc33.x86_64
OS: Fedora 33
Page: Updates

Fresh install of Fedora 33 Server, enabled automatic updates, set to reboot every day, after one reboot - the page shows just a message 

Automatic updates
Automatic updates are not set up

And there is no button to set it up.

Steps to reproduce

1. Install Fedora 33 server
2. Set up automatic updates via cockpit web UI
3. After a reboot/update that part doesn't work any more

![image](https://user-images.githubusercontent.com/2643517/115152294-38d67d80-a079-11eb-8417-0948c5c12ac7.png)

**Comment by marusak** [comment]
Do you have `dnf-automatic` installed?
DO you see anything in browser console?

@KKoukiou this might be the exact same issue you are having.

**Comment by infestdead** [comment]
dnf-automatic is installed
```
rpm -qi dnf-automatic
Name        : dnf-automatic
Version     : 4.6.1
Release     : 1.fc33
```
There are some errors in the debug console of the browser, I'm not sure if they are related. I'm testing with latest firefox, all extensions disabled, also incognito mode, also integrated protection is disabled for the site.

![image](https://user-images.githubusercontent.com/2643517/115190079-29dee200-a0f0-11eb-896b-6d4d97256314.png)

Another somewhat strange error there is this:
```
ke @ index.js:25
Be @ index.js:25
append @ index.js:25
S @ index.js:64
(anonymous) @ index.js:64
n @ index.js:1
(anonymous) @ index.js:34
n @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
cockpit.js:1 grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

p @ cockpit.js:1
v @ cockpit.js:1
(anonymous) @ cockpit.js:1
C.n.onmessage.e.dispatch_data @ cockpit.js:1
(anonymous) @ cockpit.js:1
postMessage (async)
(anonymous) @ index.js:69
C.n.onmessage.e.dispatch_data @ cockpit.js:1
```

**Comment by KKoukiou** [comment]
> Do you have `dnf-automatic` installed?
> DO you see anything in browser console?
> 
> @KKoukiou this might be the exact same issue you are having.

Yes I just thought the same. It's still the same on my system so I guess I can just debug it here today.

**Comment by KKoukiou** [comment]
I found what the issue was on my side, maybe it's the same for you @infestdead.
The current implementation hides the UI, if there is already onCalendar timer property, but it's not a full hour.

So on my system it was:
```
$ cat /usr/lib/systemd/system/dnf-automatic-install.timer | grep OnCalendar
OnCalendar=*-*-* 6:42
```

The 42 part was the problematic. Switchin it to 6:00 will show the autoupdates card in the UI. 

So I will send a fix, but you can also easily make the card available by choosing full hours for your updates.

**Comment by infestdead** [comment]
```
cat /usr/lib/systemd/system/dnf-automatic-install.timer
[Unit]
Description=dnf-automatic-install timer
# See comment in dnf-makecache.service
ConditionPathExists=!/run/ostree-booted
Wants=network-online.target

[Timer]
OnCalendar=*-*-* 6:00
RandomizedDelaySec=60m
Persistent=true

[Install]
WantedBy=timers.target
```

That's what I have now in that timer, tried changing it, removing it, adding it back. No change in the web UI.

**Comment by KKoukiou** [comment]
No this is fine, how about the overrides file? 
```
/etc/systemd/system/dnf-automatic-install.timer.d/override.conf
```

**Comment by KKoukiou** [comment]
Check also the dnf-automatic.timer. So both:

```
 sudo systemctl cat dnf-automatic.timer
 sudo systemctl cat dnf-automatic-install.timer
```

**Comment by infestdead** [comment]
Yeap, that was it.
```/etc/systemd/system/dnf-automatic-install.timer.d/time.conf```
had 
```
OnCalendar= 10:30
```

Changed that to 10:00 and the EDIT button showed up right away.

**Comment by infestdead** [comment]
Also noticed another bug, but maybe that's for a separate issue. 
If you remove dnf-automatic from the command line, then go to cockpit, automatic updates - you get the Edit button, but when clicked you get this error:
![image](https://user-images.githubusercontent.com/2643517/115260553-89aeaa80-a13b-11eb-8492-cfb93eb84b88.png)
and the install button is grayed out, maybe something gets cached at packagekit side or something, I don't know :)

**Comment by KKoukiou** [comment]
Yes, you need to refresh the page cockpit to get the dnf-automatic is not installed, if you removed it form the CLI after the page was loaded. But it's indeed another issue (IMO not really important one)

**Comment by marusak** [comment]
This is not and issue (at least on our side). Packagekit uses cache that is not yet updated since your last transaction that you have done using dnf and not packagekit. You need to refresh that. Easiest way is clicking on that 'Refresh' icon in 'Updates'.

**Comment by infestdead** [comment]
Yes, refresh and then Edit on the automatic updates installs the dnf-automatic package just fine. 
Thanks!
