### ISSUE TITLE
openSUSE Tumbleweed zfs not showing disk

### ISSUE THREAD

**Issue by cchalifo999** [cockpit-project/cockpit#15726]
Cockpit version: Version 238.1
OS: openSUSE Tumbleweed
Page: 

cockpit-zfs-manager is not showing any disk 
The zfs version i have is zfs-2.0.4-1
zfs-kmod-2.0.4-

Steps to reproduce

1. fresh install openSUSE Tumbleweed
2. Cloned the repo cockpit-zfs-manager copy the modulers to usr/share/cockpit and enable cockpit and started cockpit ran the wizerad when i clicked on the zfs tab
3.

**Comment by marusak** [comment]
Please report this into https://github.com/optimans/cockpit-zfs-manager
