### ISSUE TITLE
firewall: When adding custom ports to a zone and ID is supposed to be optional but it's not

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#15723]
![Screen Shot 2021-04-21 at 16 08 49](https://user-images.githubusercontent.com/14921356/115410298-cd182000-a1f2-11eb-8a95-a1babee965c0.png)

**Comment by KKoukiou** [comment]
OK I just got it, it's optional in matters that it's autogenerated, I thought you can just leave it blank.
That is utterly confusing.

**Comment by garrett** [comment]
> OK I just got it, it's optional in matters that it's autogenerated, I thought you can just leave it blank.

It should be optional, but this looks broken. It is _supposed to_ autogenerate an ID.

> That is utterly confusing.

Yep, agreed. It's a bug. It should complete successfully with an autogenerated ID.

**Comment by KKoukiou** [comment]
@garrett the id actually get's autogenerated. So what i did:

* I wanted to open some random port range 5550-5560
* Click Add Service, custom Ports, and then filled in the port range
* The ID was autgenerated to custom-* something

I already had noticed it's optional, so I was like, what's that even, I don't want an ID, let's erase it.
 
Then of course clicking the add button with an empty ID string causes this error. 

So the actual issue here is that I did not expect a service to be created for some random port range named after that autogenerated Id. Does this make sense?

**Comment by garrett** [comment]
Ah, right; the ports are handled as generated services in the background.

At least as-is: When the entry is blank, it should still use the autogenerated ID.
