### ISSUE TITLE
cockpit to config vxlan for kernel & coriolis 

### ISSUE THREAD

**Issue by summer-father** [cockpit-project/cockpit#15730]
It is hoped that Cockpit can increase the functional configuration of VXLAN in the management kernel and add DPDK for Intel, which is similar to the effect of Huawei Cloud L2CG large layer network. In this way, the basic cost of VXLAN must be dependent on physical devices can be greatly reduced.  To make the OS kernel network SDN performance and graphical configuration further, to achieve a two-layer network across multiple data centers such as OpenStack, to achieve single-host granularity migration.  
HUAWEI Automatic Discovery Migration Tool: http://www.huaweicloud-rda.com/ HUAWEICCLOUD-L2CG:  https://support.huaweicloud.com/intl/en-us/usermanual-vpc/vpc_l2cg_0001.html  
Huawei SMS service: https://www.huaweicloud.com/en-us/product/sms.html  
Cockpit by integrating coriolis (link: https://github.com/cloudbase/coriolis) and vxlan (link:  https://www.kernel.org/doc/html/latest/networking/vxlan.html) configuration, to achieve the same effect.

**Comment by marusak** [comment]
> Cockpit by integrating coriolis (link: https://github.com/cloudbase/coriolis)

That would be definitely a separate project based on https://github.com/cockpit-project/starter-kit (ideally done by coriolis developers)

> vxlan (link: https://www.kernel.org/doc/html/latest/networking/vxlan.html) configuration

Netowrking page shows vxlan devices already. What exactly is missing there?

**Comment by marusak** [comment]
@summer-father ping

**Comment by martinpitt** [comment]
No response in three months, and there was an answer above. I'm happy to reopen if you have further information. Thanks!

**Comment by summer-father** [comment]
The Linux kernel has vxlan configuration commands that are turned off first, but it is not suitable for novices to configure and inconvenient, and they hope to be able to integrate with the kernel to configure vxlan commands

**Comment by summer-father** [comment]
To configure VXLAN in the Linux kernel, you need to follow these steps:

Ensure Kernel Version Support: VXLAN requires a Linux kernel version of at least 3.7 or higher, with 3.9 or newer versions recommended.
Add VXLAN Interface: Create a VXLAN-type network interface, such as vxlan0, which will serve as a VTEP (VXLAN Tunnel Endpoint).
Configure VXLAN Interface Address: Assign an IP address to the VXLAN interface and activate it to make it available.
Check Routing and FDB Entries: Review the routing table and FDB (Forwarding Database) entries to ensure proper forwarding and encapsulation within the VXLAN network.
Use iproute2 Tools: The configuration and management of VXLAN typically involve using the iproute2 suite of tools, which has been merged into the kernel along with VXLAN. The commonly used ip command is a client tool for iproute2.
Perform Network Testing: After configuration, conduct network connectivity and performance tests to ensure the VXLAN network is functioning correctly.
Please note that these steps provide a basic guide, and the specific operations may vary depending on your Linux distribution and network environment. During the configuration process, you may need to adjust parameters based on your actual situation, such as the VXLAN network ID, VNI (VXLAN Network Identifier), etc. Additionally, to ensure the stability and security of the VXLAN network, you might also need to configure corresponding security policies and Access Control Lists (ACLs). @marusak
