### ISSUE TITLE
Do CA and CRL checks during certificate authentication

### ISSUE THREAD

**Issue by SteveSimpson** [cockpit-project/cockpit#15736]
# Summary
Add a PAM module to allow a local client certificate verification. Current solution required Domain Infrastructure. The solution I would like to see uses a ca-bundle.pem file for CA verification (might want to add that to the domain version) & a little SQLite database for storing the user mappings.

# Status
I think I'm really close to having this working, but there is something that I'm missing. I would love someone who is more familiar with the code base to take a look. Happy to pass on my work and make this a community feature in the future.

I am using CentOS Stream 8 as my platform.

[pam_cockpit_local_cert.c.txt](https://github.com/cockpit-project/cockpit/files/6359591/pam_cockpit_local_cert.c.txt)

# Background
I am using cockpit for a console to virtual machines. I don't want the overhead / reliability issues of tying this with my AD Domain (which is hosted on VMs). Creating a separate IPA or Samba Domain is very heavy weight solution for the small number of admins.

**Comment by martinpitt** [comment]
Hello @SteveSimpson  -- Indeed I looked into this as well a while ago. We even have an integration test that demonstrates how to do that with just sssd and a local certificate → user mapping: https://github.com/cockpit-project/cockpit/blob/master/test/verify/check-static-login#L694

But this requires some help from sssd, I filed https://github.com/SSSD/sssd/issues/5224 about this. It should not actually be that hard to do, just nobody got around to it so far.

Honestly I'd much rather re-use the existing infrastructure from sssd for this than creating a new cockpit specific PAM module.

**Comment by SteveSimpson** [comment]
@martinpitt -- Thanks for looking at this & responding quickly. 

I need to get something working pretty quickly - I can revisit the solution later. Couple of hopefully quick questions that would really help me:

1.) Is anything else needed beside the certificate to username mapping / is anything getting pulled from SSSD elsewhere? (does my concept work or is it missing something)

2.) Any idea why I would be getting the following error when using my module:

`cockpit-ws[84987]: double free or corruption (out)`

Tracing it out it id coming from 
   main.c:300  g_printerr ("cockpit-ws: %s\n", error->message);
and getting set from one of the following:
   main.c:182  cert_path = cockpit_certificate_locate_gerror (&error);  
   main.c:184  certificate = cockpit_certificate_load (cert_path, &error);
   main.c:212   server = cockpit_web_server_new(... &error); 

line 212 seems the most obvious, but the server is getting setting started because, the error is not prefaced with "Error starting web server: " (line 220)
  
## Other comments

I thought about using SSSD as the avenue & didn't realize that you had already done work in that direction. Personally, I would love to keep SSSD out of the mix, but that is just an opinion. 

The OpenSSL code for certificate validation (with certificates in a single file) was not hard to add. You could certainly add that as a if file exists then validate CAs check. 

I haven't done CRL checking yet because I don't need it, as I'm planning on generating a file from a certificate database where they are already checked, but I would be happy to look at adding it anyway.

Assuming that I'm not missing a major concept (see question 1), I think my code could be merged with your existing module, maybe with a simple check of if a system is a domain member or if the sqlite db exists.

**Comment by martinpitt** [comment]
This is certainly great as a tech demo! I was looking at sssd, as that's already a well-established component, available in all supported distributions, and it has an existing API and config structure. It also makes it easy to integrate with identity management. If at all possible, we avoid introducing cockpit specific config files, and re-use what ssh, sudo, sssd, and Linux in general already have. This local certificate bundle and the SQLite database would be such a cockpit specific solution, and there is neither documentation nor tooling to maintain these.

There could certainly be some middle ground here -- sssd's user maps are fine, the only missing part is the validation that it's signed by a trusted CA. So in theory, such a custom module would be fine with just looking at a cockpit specific CA bundle, and then calling out to sssd for doing the actual mapping. (NB that we still don't want to merge that, as we'd have to support it for all eternity; also, we use GnuTLS, not OpenSSL, but that's just a minor detail). But it would make your demo much closer to what the eventual solution would look like.

Wrt. the `error` crash, I don't have an immediate idea. I agree that the most likely path is through a cockpit_web_server_new() failure, as in all likelyhood loading the server certificate works. But then again, not sure why creating a CockpitWebServer instance would fail.. this is a wholly new process, so it couldn't be memory corruption from the PAM module even. I need to do some experiments with error injection there.

**Comment by SteveSimpson** [comment]
@martinpitt - With your pointer to the SSSD code, I was able to get that working. I also added a validation to a certificate file (/etc/cockpit/ca-bundle.pem), looking at the OpenSSL libs, CRL checking should not be difficult either, just some logic to fine and add the CRLs. Anyway, I would love to get that part added to the main code base, at least until there is another way to do it. 

I have forked the repo and will be pushing my code to that so you to take a look at it. My current thinking is to make this an optional configuration. Having used PKI for my entire career, I can tell you, maintaining a single certificate for a service actually makes a lot of sense. Most configurations are only going to have a handful of CA's that they would want to authorize a connection to cockpit.

I can look at adding a Wiki page at getting all this working. Cockpit is great & this would really help it gain traction in the enterprise space (where smart card authentication is the standard). Our enterprise uses backend Kerberos (with custom 2FA) for ssh, I don't believe we have anything for SSSD. I am only looking at cockpit for admin, so I don't want users accessing it anyway.

Separate question - I see that cockpit is using sudo auth PAM module, does it check for something like sudo-cockpit 1st then fall back to just sudo? --> My problem is that we are using a custom 2FA solution that give the user a URL to authenticate to for sudo, but this prompt isn't passed in cockpit. The other way to approach this would be for me to look at what it would take for cockpit to read that prompt (with the URL). Other than the URL prompt, the current authentication works fine.

**Comment by SteveSimpson** [comment]
I have committed code with a changes to check CA & CRLs. This is all backwards compatible and will work without the files in place. There would be a log entry each time someone logs in if CA or CRL validation is not done.

**Comment by martinpitt** [comment]
I'd like to fix that properly in Cockpit, both for IPA and local mappings. But we really need some sssd API for this (https://github.com/SSSD/sssd/issues/5224), so setting blocked.

**Comment by martinpitt** [comment]
This was implemented in PR #16703 in [cockpit 260](https://cockpit-project.org/blog/cockpit-260.html). With a reasonably recent sssd this now validates against the CA configured in sssd. That's about as far as we are going to implement this. Thanks!
