### ISSUE TITLE
admin account panel borders are black

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1574]
This looks out of place with the rest of Cockpit.
![screenshot from 2014-12-10 12 15 42](https://cloud.githubusercontent.com/assets/209895/5375059/51108d80-8066-11e4-9d01-2f3df69e4768.png)

**Comment by stefwalter** [comment]
@andreasn Is this ready for a pull request?

**Comment by martinpitt** [comment]
The borders are light-gray now, which does look in-line with the rest of Cockpit.
