### ISSUE TITLE
renderer : networkd -> Loading available updates failed

### ISSUE THREAD

**Issue by marcoczen** [cockpit-project/cockpit#15746]
Cockpit version: 238
OS: Ubuntu Server LTS 20.x
Page: updates

Error Msg : 
Loading available updates failed
Cannot refresh cache whilst offline

Hi .. With reference to https://github.com/cockpit-project/cockpit/issues/13002
and https://github.com/cockpit-project/cockpit/issues/15742

I am wondering why cockpit software updates doesnt seem to work with 
 renderer : networkd

I had to set it to  renderer : NetworkManager to get it to work.

Any insight ?  What is the fix ?

Thanks.

**Comment by KKoukiou** [comment]
Hey @marcoczen, thanks for the issue.
Some other users have showed interest in the past in this, here is an answer copied from another issue.

https://github.com/cockpit-project/cockpit/issues/7987#issuecomment-787413478

Closing this so that we can keep our bug tracker clean.

**Comment by KKoukiou** [comment]
OH, sorry for closing, I misread the issue initially as that it's an RFE for supporting networkd backend for network page.

**Comment by KKoukiou** [comment]
@marcoczen did you try https://github.com/cockpit-project/cockpit/issues/8477#issuecomment-622253139 ?

**Comment by marcoczen** [comment]
Hi @KKoukiou  - as mentioned in the issue https://github.com/cockpit-project/cockpit/issues/8477#issuecomment-622253139 , Stopping and disabling NetworkManager will make the Networking page NOT work anymore. This was also indicated in https://github.com/cockpit-project/cockpit/issues/15742

**Comment by KKoukiou** [comment]
The only solution is what you did and mention in the issue description, namely setting the renderer to NetworkManager, ifor both pages to work. However this is not a cockpit bug, and there is nothing we can do from our side for this to get fixed unfortunately.

See: https://github.com/cockpit-project/cockpit/issues/8477#issuecomment-640062964

**Comment by marcoczen** [comment]
Thanks. Much appreciated.
Great piece of software.

Closed.
