### ISSUE TITLE
Monitor all resources from all servers on one screen

### ISSUE THREAD

**Issue by zigazajc007** [cockpit-project/cockpit#15757]
It is possible to show all resource usage on all servers from one screen so I can hook that up with monitors on server rooms, my house... So I will be able to monitor resources 24/7. Also if it's possible to make a check box or something so that session would never expire.

I can't find the perfect program that can monitor all servers from one screen. That's why I wanted to make my own program to do that, but then I found out about cockpit and it's really close to be perfect for server monitoring. Only thing that is needed is all resources monitor on one screen and session that would never expire for 24/7 monitoring.

Here is the quick preview:
![suggestion](https://user-images.githubusercontent.com/44822563/116388644-5398b700-a81c-11eb-92e0-8a840ba787d0.png)

**Comment by marusak** [comment]
We talked about this a lot lately in team and we all agree that for this you want to use https://grafana.com/
We plan to make setting up of Grafana easier in near future.
