### ISSUE TITLE
Login credentials stopped working

### ISSUE THREAD

**Issue by dpk89** [cockpit-project/cockpit#15759]
Hlo, I am new into cockpit
I was trying to do some changes on the login page, but it was not getting reflected, so I ran these commands
$ sudo mount -o bind dist/static/ /usr/share/cockpit/static/
$ sudo mount -o bind src/branding/ /usr/share/cockpit/branding/
$ sudo mount -o bind cockpit-ws /usr/libexec/cockpit-ws

UI changes got reflected, but login with previous credentials stopped working.

**Comment by marusak** [comment]
You haven't provided enough info I am afraid. What kind of changes have you done?
Also if it was just login page then there is no need to bind mount `cockpit-ws` which might be the reason why cockpit stopped working.
Have you done `systemctl stop cockpit.service`?
Is there anything in journal?
Do you have selinux enabled?

**Comment by dpk89** [comment]
Restarting the system, solved my issue.
Thanks
