### ISSUE TITLE
No error for invalid new password

### ISSUE THREAD

**Issue by marwenbk** [cockpit-project/cockpit#15775]
Cockpit version: 243
OS: ubuntu 20.4.2
Page: set password

I set my password to a 3363 char length password with multi-lines,
no error showed 
I'm logged out and I can't log in,

Steps to reproduce

1. open the profile page 
2. copy multiline 3363 char string 
3. paste the string 
4. setting the password

**Comment by marusak** [comment]
When I try to set such password I get error `chpasswd: failed to crypt password with salt '$6$qDmAULpz.c//': Numerical result out of range`

Can you by any chance post here example of such password? Surely you generated it.

**Comment by marwenbk** [comment]
MIIJKAIBAAKCAgEApaequSosjdWiJdMn7ZoGuKM2N+u3EE3XJCmPk1QuAS5LXjSq
vFSKqIpFXD/q395IqeJ/h5Mo0+Wn7WMpoxSuhPtpWve+WUB3rHkyk341vWTUmSaS
LP0wfPpgg4+QqQw94sV0ys2aRIf4A9wEPIfGXK2uz4Kak3C3fFp7A1Qqq9juSSEK
NMWEUYklttGoQT6OH/qI7eYvX6xNOzCXSv+IUKqkGhDJSDz7qR4zjp6EICtqlq/G
ajx0evUGd41SwKKBaDWKsfue/qUpInPxhvnonmJGzxUjrNGFNYW1/8ZzluWn4gTx
MvTHLW8IMx69gYeDTCfCx/KhC29mg3axWwZPHlMhhOjiXbTKsIGxPexoDHCR/GQc
zVR1MM6fzpqQI718ISvv5b6YSDHePt1sIKAyaumztkihIFDhxcRqVlltAkBWGkU5
2wu4q2LcAzVtFW180/VBXLIEUsZkNt38LxjyS+LzFDG+9bGUmHkWwqSHsud3WEYQ
jENatqDWoIVqj+vuNdqjLyWbcon0m5M+bBFF35KK3i4iS3yC6RAyx3+LK48KGV3+
8D/s6cYgMRz49MwYnyZG/S0rbuUk6JEvyMwb/IcULvgLo1p3db8MKeXBxSY9S23j
slRHwTff6w0P6kWoFFZGR3+vnaMApM7GINKJ0PWyqpKWWmdRMVcj2fB17VUCAwEA
AQKCAgABWjALmOuKMN9E/cdKqkI5yaNMq5DwAiKqeehhJIPHoLAe0cE/DlWfcJmG
WkM5lp/zOxUdbzcbG7nWN0QEv8t47HB8vJ8CLYOMleSyzYn0xNjzcxwoX9zAeG7H
RCnDJ4Vtz3zXlvwWaSG+LlKeh+E3qndN3FwUrgvhaP+uFEbQ5lFzqWBi8+XToJH9
PxLnjXItkqcBgiqK1mY/AHOLujBLsEjsqYxrGYxYYhW7qVGczZ3uIvs0rM+qnUtz
OGUfi3QQ/LboIwy2OXTvghDLsEiU2mqHkD2dUIyM1k2ZC+6voapQLwglCViC53Ai
srKLVybcPUraxQFJjZxBoHtsKc4FhvN5cedfUhCCrp1qLCvIoBdvuSQRJ/r+tSk/
rdke9OMbtYk47180zbGWpMST8go3TsyzjXXHPy2CLuK21FjZE6Gjbp2xYYxkFv+9
j/eQjpoEMPvzaBtfc1dKtbBmKKW+MSwJYlthzVdFOZ1IK0XJbldGsWl2FW2GYd/b
eUVeDevwwLFgjJBiqTxtSoh7gVG+//tVXc6XOZDIxY6Gw6AbXYHLwsScFQ5nRmMQ
17FVfIq4H9ESwjLDKdsday0Wm/IRtyfuixdepyg26WGc2KMK6XwTm6wtznsDeB7l
tSc8fSfzeZyu9aIxbR3752tt/coYg88hKtqMNkpp5wr3Sc+nFQKCAQEA78635FQN
/Wscf7TMX5wHDoJfP2WQlphq9gZ2e/eElohjZPGXRipCbDecobFDJyd9XqAulxax
QkePTODRFJQaNSwVdHJH9HL+PbRSEFuac5RadrocGGKaDUFREqjZLyb+rueDR1Gb
LUkW8QLen84Cqd6uckkYSRq6ngvyp+cNFtHCUpBaOqaTQu/tqbbKzZ/dEkjX4qcv
AHThztwgXhf+LwIm0P+eeY/hdJcqeNClv7r94bbRuCFPsR7M4spYWAMbH6/54RWs
dWeMgcFXfd5U25Z9sc0/OxMECOtqtdc5Wv9PSshTAJtqDHeZ2SzT0MCMLjPtP36R
boVPcRRZWHkd4wKCAQEAsNcoOzFfxsQvdjdmvhqX3XxSsu6aBwBU2CQv4Pb7BWz/
BjBS+Jn2B388JC1dapw6GLWTGbJKO7LsHDEiMG0KRD4V64QbWWo3PxNTf3HjNezh
VFoV/E8m6ouqeAN/hVruBYVRkJSDzP4yJ6faLtrY2jUeQM3qOKSPrYDSphVMn4Vm
TxHCSMZZei0ZmErXbh17sWJlczegeiLr0TnJ/SUveVCNUQHImpZLaNGmGU6A30mx
R9FzGlpWafYvo6Bl6QGYkDutqWzBh1ayZ6DYB0iedElzatgDxRNEiTeS+msa9PnQ
QnG4DZms+tMzcGo17xU0jj6hlE5NmFFK84WI1b4tZwKCAQBX7bYjtGZEy2dxs/tT
+0PjIA6IklcHwO9HMmtzXPhysaOwOZ08Dva381QtPW/gBWzEq3spzxpDsTVr/Ors
3rkVUgqz3ctgaGGsglesw8nII1dgPTFcB5twzMhLTToFPgkYXK8YEWYSnsAYsvKq
KcF0Q8A3C3IqK/DNTpg01FVKTrMvztomszk/y/Wayvlll/5ZW/g8lQx44GKDlNcR
aT68Qc+1xmR3Mjh6pYrfLbH4sTmx73TKTPyJdz+s0IDAFLN3VPEMhQPtMICmexv3
fPQkZ/PCo/1RTdGm65r+/eF76i1KwFUe3d1uoNP6e6NW4aMEtemB5Iiyu5K7Zbi0
5gP9AoIBAQCEgGIrn/4kf4EUccRw8poRoYKRgYg1cMEhxlN9m3FQim+3YmP409tt
mJ8meDtDk1VQiFR074sBmjmhkgsM/9audVqVQkH/yD8m6sMofdwB3sCjJHDOwTvm
h8mt7OkSsaQgzNjlnPH4mgpYfkNT0jSjoyNM6TzzPhJNrXWobdMgv6J94k+RmdUX
X02LN6CdaEfzDEf5gZejjCDnfwZiwAcHPhz0soJtmelc26E52wFizOOhbUVyXHfd
I1Jkpt1VLhXzFFQ120BSuNoqHXFgW8AmX5a0WrDQbHRw4AwnyDLFlZy+/FgtEJV0
xuUG+P36awgbAMCuz9ECLP8c4lQ52ypHAoIBAEso2d9MAOgw47VqqKONhWIjZDqN
T/iw/5QWsOeRSrW+xiUwtkPP7h2UtD6pZuF2Bi79GwTlSegiLyamuaxa57zxEz1m
tHpsN6yQtGj1KfJb3hXrLXPWZ/a0VCLMwMwnqzeuHOZIyJ8RFyAp3OnYJkED0bUx
jd6+d/sL8gblDf6Hbe/K2k9SU4kKEARv9CL3D5huvRU/vFCsRG2aS8jvi0qG+qUC
dpScdECP2YSGH7mbPzYsyBFlQb/zl146vqZ/CU2A0YuOLFRIzQQbx0dQ/U7gIj0m
2oOPBhtk6oy7WQaZ2t8UCR2lEKEChdvU6H2DvwTR030zkPf2++d18skzm1A=

**Comment by marwenbk** [comment]
I tested again on another machine till my server is 600 km away and no one has access to it
the bug still exist

**Comment by marusak** [comment]
So on Fedora this password is not accepted due to the error I posted above.
On ubuntu 20.04 it is accepted and then I can log in with given password.

How I tested:
1. Took Ubuntu 20.04 and logged into Cockpit as user `admin`
2. Went to `Accounts` page
3. Click `Create new account
4. Created user "Foo Bar" (`foobar`) with password `foobar123`
5. Click on this new account
6. Click on `Set password`
7. Pass in https://github.com/cockpit-project/cockpit/issues/15775#issuecomment-831981063
8. Click on `Set password`
9. Log out of Cockpit
10. Log in as `foobar` with https://github.com/cockpit-project/cockpit/issues/15775#issuecomment-831981063
11. Now I am logged in as `foobar`

So I cannot reproduce. Is this consistently happening for you? Could it be that in the original case you mis-copied the password?

**Comment by marwenbk** [comment]
no im not miss copying, i double checked this on other machine and same problem,
it ubuntu server os
and i change the current user password ,

**Comment by marwenbk** [comment]
for the third time, i tried this on my local machine and the error exist

**Comment by marwenbk** [comment]
update:
I changed the root password to a different password after change the user password,
logged to the cockpit with root 
change the user password again
the /etc/shadow changed from 
marwenbk:$6$4LuaVCRASE7rcitd$8Fg/qZj4xrhuqkA5WKe04lHtu8knVNehBEbZizO..ffdZq/wThS.PjXSIiUSg9RHQvlpAXWS7cM8UHxtmXQpI0:18752:0:99999:7:::
to ->
marwenbk:$1$dK8uHv8i$umppG8QOX0dLKK74aeiz8/:18752:0:99999:7:::
and now i can log in in the long key,,, hence changing the password only work from another account ( here root)

**Comment by marusak** [comment]
> and now I can log in in the long key, hence changing the password only works from another account ( here root)

So you mean this error happens if you change password for yourself but does not happen if you change it for someone else?

> if I try to set password again the old password (the long key ) is not accepted !!

For yourself or again changing as root?

**Comment by marusak** [comment]
perfect, I can now reproduce this. The reproducer is:
1. Change password for yourself
2. Be in limited access mode

**Comment by marusak** [comment]
Right, so it accepts only 511 characters from the long password, this your password is:
```
MIIJKAIBAAKCAgEApaequSosjdWiJdMn7ZoGuKM2N+u3EE3XJCmPk1QuAS5LXjSq
vFSKqIpFXD/q395IqeJ/h5Mo0+Wn7WMpoxSuhPtpWve+WUB3rHkyk341vWTUmSaS
LP0wfPpgg4+QqQw94sV0ys2aRIf4A9wEPIfGXK2uz4Kak3C3fFp7A1Qqq9juSSEK
NMWEUYklttGoQT6OH/qI7eYvX6xNOzCXSv+IUKqkGhDJSDz7qR4zjp6EICtqlq/G
ajx0evUGd41SwKKBaDWKsfue/qUpInPxhvnonmJGzxUjrNGFNYW1/8ZzluWn4gTx
MvTHLW8IMx69gYeDTCfCx/KhC29mg3axWwZPHlMhhOjiXbTKsIGxPexoDHCR/GQc
zVR1MM6fzpqQI718ISvv5b6YSDHePt1sIKAyaumztkihIFDhxcRqVlltAkBWGkU5
2wu4q2LcAzVtFW180/VBXLIEUsZkNt38LxjyS+LzFDG+9bGUmHkWwqSH
```

I am looking now if `passwd` cuts it or cockpit input. And then will check what can be done to tell user the password is too long.

**Comment by marusak** [comment]
Ok, so `passwd` only reads 511 characters from the input and ignores the rest. It does not tall us about this in any way. I think we just need to limit the lenght in the UI.

**Comment by marusak** [comment]
cmd line reproducer:
1. `passwd`
2. Enter current password
3. Enter `MIIJKAIBAAKCAgEApaequSosjdWiJdMn7ZoGuKM2N+u3EE3XJCmPk1QuAS5LXjSqvFSKqIpFXD/q395IqeJ/h5Mo0+Wn7WMpoxSuhPtpWve+WUB3rHkyk341vWTUmSaSLP0wfPpgg4+QqQw94sV0ys2aRIf4A9wEPIfGXK2uz4Kak3C3fFp7A1Qqq9juSSEKNMWEUYklttGoQT6OH/qI7eYvX6xNOzCXSv+IUKqkGhDJSDz7qR4zjp6EICtqlq/Gajx0evUGd41SwKKBaDWKsfue/qUpInPxhvnonmJGzxUjrNGFNYW1/8ZzluWn4gTxMvTHLW8IMx69gYeDTCfCx/KhC29mg3axWwZPHlMhhOjiXbTKsIGxPexoDHCR/GQczVR1MM6fzpqQI718ISvv5b6YSDHePt1sIKAyaumztkihIFDhxcRqVlltAkBWGkU52wu4q2LcAzVtFW180/VBXLIEUsZkNt38LxjyS+LzFDG+9bGUmHkWwqSHsud3WEYQ` as a new password that is 512 characters long
4. repeat
5. Try to log in with the new password - does not work
6. Try to log in with the new password without the last `Q` - works

**Comment by martinpitt** [comment]
Limiting the password to 512 (or even 100) characters seems ok to me. If someone accidentally puts an SSL certificate into a password, this is  an oversight anyway, so in exactly which way it fails isn't *that* important I guess :grin:

**Comment by marwenbk** [comment]
for our company the use of cockpit in production without brute-force protection was a risk, how long can be your password? , we switched back to ssh, key pair is more efficient and secure

**Comment by marusak** [comment]
Such long password is a naive approach for protection against brute force attacks. There is really no good reason to have such long password. To protect against brute force attacks you want to limit amount of tries that one can do in a given time frame. [some ideas](https://unix.stackexchange.com/questions/2126/why-is-there-a-big-delay-after-entering-a-wrong-password).
If for example you limit one password try every two seconds, only 10 characters long password (that is not in dictionary) would take thousands of years to crack.

So I'll go with limiting the length of the new password. If one still has to use some longer password other utilities (for example `chpasswd`) still can be used from terminal to set such password.

**Comment by martinpitt** [comment]
Moreover, setting an X.509 certificate keypair as password is just not useful. At least that still has a private key in it -- but if you e.g. tried to set the password to a *public* key, then the length doesn't help you at all :grin:
