### ISSUE TITLE
Remove 'which no gear in ((null))' message

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1577]
Note that this could just be my system, but felt best to file just in case.

![screenshot from 2014-12-10 15 08 09](https://cloud.githubusercontent.com/assets/209895/5377762/4955ea1c-8085-11e4-96b9-7d78ed2f0803.png)

**Comment by stefwalter** [comment]
The output of ```which``` just needs to be directed to null.

**Comment by mvollmer** [comment]
> The output of which just needs to be directed to null.

But note that it gets a useless $PATH.  We might want to investigate where $PATH gets killed.

**Comment by stefwalter** [comment]
Sounds good. Separate bug?

**Comment by mvollmer** [comment]
Yup, #1624.
