### ISSUE TITLE
Cockpit not publicy accessible

### ISSUE THREAD

**Issue by wiryonolau** [cockpit-project/cockpit#15776]
Cockpit version: builtin package from apt, yum, and dnf
OS: Ubuntu 20.04, Centos 7, Centos 8
Page: initial page

Steps to reproduce

1. New vps test in Digital Ocean and Upcloud
2. run update : yum update -y
3. install cockpit : yum install -y cockpit 
4. add firewall : firewalld-cmd --add-service=cockpit --permanent
5. enable service : systemtctl enable --now cockpit.socket

ss -tulpn return 

```
Netid     State      Recv-Q     Send-Q         Local Address:Port           Peer Address:Port
udp       UNCONN     0          0                    0.0.0.0:5355                0.0.0.0:*         users:(("systemd-resolve",pid=862,fd=12))
udp       UNCONN     0          0              127.0.0.53%lo:53                  0.0.0.0:*         users:(("systemd-resolve",pid=862,fd=18))
udp       UNCONN     0          0                       [::]:5355                   [::]:*         users:(("systemd-resolve",pid=862,fd=14))
tcp       LISTEN     0          128                  0.0.0.0:5355                0.0.0.0:*         users:(("systemd-resolve",pid=862,fd=13))
tcp       LISTEN     0          128                  0.0.0.0:22                  0.0.0.0:*         users:(("sshd",pid=723,fd=5))
tcp       LISTEN     0          128                        *:9090                      *:*         users:(("systemd",pid=1,fd=42))
tcp       LISTEN     0          128                     [::]:5355                   [::]:*         users:(("systemd-resolve",pid=862,fd=15))
tcp       LISTEN     0          128                     [::]:22                     [::]:*         users:(("sshd",pid=723,fd=7))
```

curl -k https://ip-address:9090 or curl -k https://localhost:9090 return result it's mean it's works.
curl -k https://ip-address:9090 from remote pc ( different isp ) always got connection time out

Does the built in systemd config block public access ?

**Comment by martinpitt** [comment]
> firewalld-cmd --add-service=cockpit --permanent

This only enables it for the on-disk configuration, not for the running firewalld instance. After that you either need to allow it for the running one with `firewalld-cmd --add-service=cockpit` or restart the entire firewall with `firewall-cmd --reload`. Does it work then?

**Comment by wiryonolau** [comment]
it's not working. I even restart the whole vm.

When in digitalocean by default their ubuntu centos doesn't have any firewall installed ( all input is allowed )

I don't use any of their cloud firewall.

**Comment by martinpitt** [comment]
I'm afraid I don't know then -- the port is open on all interfaces, there must be some additional firewall/networking policy in your cloud provider.

**Comment by wiryonolau** [comment]
Is there a way to run cockpit without cockpit.socket. 
Just let it up without waiting for socket connection like nginx / apache

**Comment by martinpitt** [comment]
You already confirmed with local curl and `ss` that the socket is fine. Sure, *for testing only* you can try this:
```
systemctl stop cockpit cockpit.socket
su -s /bin/sh -c '/usr/lib/cockpit/cockpit-ws --no-tls' cockpit-wsinstance
```

Then http://localhost:9090 should work (TLS is not available in this mode, hence it is  for  testing only).

**Comment by wiryonolau** [comment]
As I mention accessing with tls from localhost or LAN works, but not WAN. I'm checking with the cloud provider. Thanks for the help.

**Comment by martinpitt** [comment]
@wiryonolau : You can also test this very easily with stopping cockpit and just having a simple netcat like `nc -l 9090` in case there is any doubt about whether it's the server side. Often in cloud providers you need to set additional security policies to open ports.

Alternatively, you can run the cockpit web server locally and connect to your instance over SSH. Either directly on the login page, or with adding this additional host in the host selector in the top left menu.

**Comment by wiryonolau** [comment]
LOL sorry for the trouble, apparently my ISP block it.
