### ISSUE TITLE
cockpit 243 in centos7

### ISSUE THREAD

**Issue by mvala** [cockpit-project/cockpit#15785]
Cockpit version: 243
OS: Centos7
I don't see any rpms produced for centos7. Is it discontinued? Or is it going to be supported. I need at least some version with patternfly 4. 
Thanks for support

https://pkgs.org/download/cockpit-packagekit

**Comment by marusak** [comment]
Indeed, centos-7 is not supported anymore.
We don't test it anymore thus don't ship either.
One could try to do builds but it will likely won't just work.
Are you interested to try to produce builds and want our help with it?

**Comment by KKoukiou** [comment]
Centos 7 traditionally had followed the updates of RHEL-7, which is already a few years out of the full support phase.
Centos-8 stream has newer version of cockpit-* packages available. http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/

**Comment by mvala** [comment]
> Indeed, centos-7 is not supported anymore.
> We don't test it anymore thus don't ship either.
> One could try to do builds but it will likely won't just work.
> Are you interested to try to produce builds and want our help with it?

I already tried. And it had problems with rpm and `Recommends` tags. Thanks for your hard work. I will continue on centos8
