### ISSUE TITLE
Activate the web console login message does not disappear

### ISSUE THREAD

**Issue by lzap** [cockpit-project/cockpit#15789]
Cockpit version: cockpit-242-1.fc34.x86_64
OS: Fedora 34 Server

Hello,

this might be just Fedora packaging issue but since I know many of you guys are Fedora members I am reporting it here.

I have cockpit activated from the day one of my Fedora 33 (now upgraded to F34) installation and I noticed the MOTD message which is there for each login. I'd assume it would disappear at some point:

```
Activate the web console with: systemctl enable --now cockpit.socket

Last login: Tue May  4 19:00:18 2021 from 192.168.1.5
[lzap@nuc ~]$ sudo systemctl status cockpit.socket
● cockpit.socket - Cockpit Web Service Socket
     Loaded: loaded (/usr/lib/systemd/system/cockpit.socket; enabled; vendor preset: enabled)
     Active: active (listening) since Wed 2021-04-28 09:38:14 CEST; 1 weeks 0 days ago
   Triggers: ● cockpit.service
       Docs: man:cockpit-ws(8)
     Listen: [::]:9090 (Stream)
      Tasks: 0 (limit: 38385)
     Memory: 928.0K
        CPU: 14ms
     CGroup: /system.slice/cockpit.socket

dub 28 09:38:14 nuc.home.lan systemd[1]: Starting Cockpit Web Service Socket.
dub 28 09:38:14 nuc.home.lan systemd[1]: Listening on Cockpit Web Service Socket.
```

This is just a tiny nitpick, cheers! :-)

**Comment by marusak** [comment]
Somewhere back in my head I have that this message should not be shown  when cockpit.socket is active. But cannot now really remember if that is the case.
In any case, there have been lately a few discussions about this motd message and right now we have https://github.com/cockpit-project/cockpit/pull/15784 pending which lets you to remove it. You can also symlink it to /dev/null as discussed in https://bugzilla.redhat.com/show_bug.cgi?id=1663812

@martinpitt should this message not be shown when the socket is enabled and active?

**Comment by martinpitt** [comment]
The message should certainly be different if cockpit.socket is already running. So let's debug that.

First of all, can you please copy&paste the output of `systemctl status cockpit-motd.service`?

Also, please run `sh -x /usr/share/cockpit/motd/update-motd` as *user*. It will fail in the last step trying to write to /run/cockpit/active.motd with a "Permission denied", but that's fine -- I'm interested in the output before that.

Thank you!

**Comment by lzap** [comment]
Sure, this should be easily reproducable, it is just Fedora 33 Server (upgraded to 34). Here you are:

```
$ systemctl status cockpit-motd.service
○ cockpit-motd.service - Cockpit motd updater service
     Loaded: loaded (/usr/lib/systemd/system/cockpit-motd.service; static)
     Active: inactive (dead) since Wed 2021-04-28 09:38:19 CEST; 1 weeks 1 days ago
       Docs: man:cockpit-ws(8)
   Main PID: 972 (code=exited, status=0/SUCCESS)
        CPU: 19ms

dub 28 09:38:19 nuc.home.lan systemd[1]: Starting Cockpit motd updater service...
dub 28 09:38:19 nuc.home.lan systemd[1]: cockpit-motd.service: Deactivated successfully.
dub 28 09:38:19 nuc.home.lan systemd[1]: Finished Cockpit motd updater service.

[lzap@nuc ~]$ sh -x /usr/share/cockpit/motd/update-motd
++ systemctl show --property Listen cockpit.socket
++ sed -E '$!d;$s/.*[^0-9]([0-9]+).*/\1/;'
+ port=9090
+ port=9090
++ hostname -f
+ hostname=nuc.home.lan
++ ip -o route get 255.0
++ sed -e 's/.*src \([^ ]*\) .*/\1/'
+ ip=192.168.1.X
+ protocol=https
+ hostname_url=https://nuc.home.lan:9090/
+ ip_url=' or https://192.168.1.X:9090/'
+ printf 'Web console: %s%s\n\n' https://nuc.home.lan:9090/ ' or https://192.168.1.X:9090/'
/usr/share/cockpit/motd/update-motd: řádek 24: /run/cockpit/active.motd: Operace zamítnuta

[lzap@nuc ~]$ systemctl show --property Listen cockpit.socket
Listen=[::]:9090 (Stream)

[lzap@nuc ~]$ systemctl show --property Listen cockpit.socket | sed -E '$!d;$s/.*[^0-9]([0-9]+).*/\1/;'
9090
```

I have ton of github notification, if you want to speed up my response ping me on freenode: lzap.

**Comment by martinpitt** [comment]
> this should be easily reproducable

It's not, I'm afraid. We actually test this feature in CI, on a dozen of OSes including F33/34. So your call of /usr/share/cockpit/motd/update-motd looks fine, it detects the running service and wants to say "Web console: url", not the "Activate.." if it's not running.  Also, cockpit-motd.service has `After=cockpit.socket`, so at the time when it runs the socket should be up.

Can you please try this:

    sudo systemctl edit cockpit-motd

with these lines:
```
[Service]
ExecStart=-/bin/sh -ex /usr/share/cockpit/motd/update-motd
```
then reboot, do

    sudo journalctl -b > /tmp/journal.txt

and attach /tmp/journal.txt here?

After that, clean up with

    sudo rm /etc/systemd/system/cockpit-motd.service.d/override.conf
    sudo rmdir /etc/systemd/system/cockpit-motd.service.d

Thanks!

**Comment by lzap** [comment]
I thought it would be good idea to do `dnf update` prior rebooting, for the record I am getting:

```
Balíčky můžete z mezipaměti odstranit spuštěním 'dnf clean packages'.
Chyba: Transaction test error:
  soubor /usr/share/man/man8/cockpit_session_selinux.8.gz způsobuje konflikt mezi instalovaným selinux-policy-doc-34.4-1.fc34.noarch a cockpit-ws-243-1.fc34.x86_64
  soubor /usr/share/man/man8/cockpit_ws_selinux.8.gz způsobuje konflikt mezi instalovaným selinux-policy-doc-34.4-1.fc34.noarch a cockpit-ws-243-1.fc34.x86_64
```

It is probably not related, sorry this is in Czech, it is a conflict obviously. Do you want a BZ for this one?

**Comment by marusak** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1955526
Already reported and also fixed. New package should be already available.

**Comment by lzap** [comment]
Thanks, rebooting, will comment in a bit.

**Comment by lzap** [comment]
Done, attaching.

[journal.txt](https://github.com/cockpit-project/cockpit/files/6433871/journal.txt)

**Comment by lzap** [comment]
The relevant bit is:

```
kvě 06 12:38:12 nuc.home.lan sh[476790]: ++ sed -E '$!d;$s/.*[^0-9]([0-9]+).*/\1/;'
kvě 06 12:38:12 nuc.home.lan sh[476789]: ++ systemctl show --property Listen cockpit.socket
kvě 06 12:38:12 nuc.home.lan sh[476787]: + port=9090
kvě 06 12:38:12 nuc.home.lan sh[476787]: + port=9090
kvě 06 12:38:12 nuc.home.lan sh[476797]: ++ hostname -f
kvě 06 12:38:12 nuc.home.lan sh[476787]: + hostname=nuc.home.lan
kvě 06 12:38:12 nuc.home.lan sh[476803]: ++ ip -o route get 255.0
kvě 06 12:38:12 nuc.home.lan sh[476804]: ++ sed -e 's/.*src \([^ ]*\) .*/\1/'
kvě 06 12:38:12 nuc.home.lan sh[476787]: + ip=192.168.1.2
kvě 06 12:38:12 nuc.home.lan sh[476787]: + protocol=https
kvě 06 12:38:12 nuc.home.lan sh[476787]: + hostname_url=https://nuc.home.lan:9090/
kvě 06 12:38:12 nuc.home.lan sh[476787]: + ip_url=' or https://192.168.1.2:9090/'
kvě 06 12:38:12 nuc.home.lan sh[476787]: + printf 'Web console: %s%s\n\n' https://nuc.home.lan:9090/ ' or https://192.168.1.2:9090/'
kvě 06 12:38:12 nuc.home.lan systemd[1]: cockpit-motd.service: Deactivated successfully.
kvě 06 12:38:12 nuc.home.lan systemd[1]: Finished Cockpit motd updater service.
```

**Comment by lzap** [comment]
Btw I now see the correct motd:

```
Web console: https://nuc.home.lan:9090/ or https://192.168.1.2:9090/

Last login: Thu May  6 12:53:07 2021 from 192.168.1.5
[lzap@nuc ~]$
```

**Comment by martinpitt** [comment]
@lzap : Right.. so did that bug disappear just because of adding `set -x`? (hello Heisenbug) Does it at least come back if you remove the unit overrides?

**Comment by lzap** [comment]
Well I did `dnf update` and it pulled newer version of cockpit, that might be the difference.

Anyway, I just rebooted and it works. Feel free to close the issue, apologies if this was not helpful.

**Comment by martinpitt** [comment]
Please don't apologize -- I really appreciate your report and your help with trying to debug it! It just feels like all the evidence is gone now :cry: We did not fix anything in that area in the recent weeks, maybe you had a very old version?

Please shout if this ever comes back,then I can think about how to debug this without a  reboot. Thanks!

**Comment by lzap** [comment]
> maybe you had a very old version

For the record, this was pretty much standard Fedora 33 Server to 34 upgrade, I did everything as required (full update prior upgrade). I was digging in the codebase and everything looks okay, really, I do not understand this.

Anyway, thanks!
