### ISSUE TITLE
When there is motd the login message takes just half screen size on big screens

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#15786]
Cockpit version: 243
Page: Overview

![Screen Shot 2021-05-05 at 13 03 00](https://user-images.githubusercontent.com/14921356/116994834-8b4ea580-acd9-11eb-9437-27e657bef7bc.png)

It would make sense that modt and login messages would just be splitting one line for small screens.

**Comment by KKoukiou** [comment]
If it's not a bug just close, I was not sure.

**Comment by garrett** [comment]
This is definitely a bug. This shouldn't happen.

**Comment by marusak** [comment]
So there are 4 possible situations:
- Neither motd nor the last login are present (right now last login is always present, but one can close it or with https://github.com/cockpit-project/cockpit/issues/13882 it could happen)
- Only motd is present
- Only last-login is present
- Neither is present

When neither or both are present, then I think we want to span it across the whole screen.
If both are present then we want to split the screen in half? Or just have two 1/3 cards to match cards below?

@garrett WDYT?

**Comment by KKoukiou** [comment]
So currently motd and login messages are both alerts; so according to @garrett these should span fully grid-column: 1/-1

However I clearly remember many discussions that login messages should not be an alert, but part of the system card.


Here is how it looks fully spanned. I feel it's too much wasted space.

![Screen Shot 2021-06-11 at 09 02 44](https://user-images.githubusercontent.com/14921356/121479982-dfc8fd00-c9ca-11eb-9960-f64853e9da2d.png)

@garrett do you think this worths a bit of a design guidance? In that case let's block it on some mockup.

**Comment by marusak** [comment]
> However I clearly remember many discussions that login messages should not be an alert, but part of the system card.

It should be part of the card, when it is just info (just last login, no failed logins). When there are failed logins, we want to highlight it, thus it is fine to take a lot of space.

https://github.com/cockpit-project/cockpit/issues/13882

**Comment by garrett** [comment]
> However I clearly remember many discussions that login messages should not be an alert, but part of the system card.
> Here is how it looks fully spanned. I feel it's too much wasted space.

Yep, agreed on all parts.

It should not be an alert. However, alerts should still span across. So until it's fixed to not be an alert (unless there's an actual problem), it should span across. But it should still be properly fixed to not alert for something that's perfectly normal.

> When there are failed logins, we want to highlight it

Correct: Failed logins are alerts. Successful logins are not alerts.
