### ISSUE TITLE
There is no proper documentation to setup SSO

### ISSUE THREAD

**Issue by dpk89** [cockpit-project/cockpit#15791]
I want to implement SSO in Cockpit but there is no proper documentation or example for how we can do the same using Kerberos or OKTA. I don't have much hands on experience with Python.
Please guide me over the same.

Thanks in advance.

**Comment by martinpitt** [comment]
Hellp @dpk89 ! So starting from https://cockpit-project.org/guide/latest/authentication.html and https://cockpit-project.org/guide/latest/sso.html , where did you get stuck? I.e. what exactly do you want to set up? We support Kerberos authentication against FreeIPA or Active Directory. I haven't heard OKTA yet (supposedly we don't support that, unless it's just a variant of Kerberos).

**Comment by marusak** [comment]
@dpk89 ping

**Comment by marusak** [comment]
Closing due to lack of information
