### ISSUE TITLE
New applications are not getting listed

### ISSUE THREAD

**Issue by dpk89** [cockpit-project/cockpit#15800]
Running Cockpit using 238.1 tag
OS: Ubuntu 21.04
Page: Applications

Steps:
1. Installed Apache NiFi on my system.
2. In source code, created a directory named nifi  under pkg.
3. Added two files under this directory. 
One is the normal **index.html** and another with the name **org.cockpit-project.cockpit-nifi.metainfo.xml**  with the content as shown in attached image.

 **org.cockpit-project.cockpit-nifi.metainfo.xml**
![image](https://user-images.githubusercontent.com/39826327/117310069-9bfd4800-aea0-11eb-8f9d-e0a121eff86a.png)

4. Added link to above xml file in Makefile.am
**Makefile.am**
![image](https://user-images.githubusercontent.com/39826327/117309912-81c36a00-aea0-11eb-9a11-35ebcb67c72a.png)

**Comment by marusak** [comment]
So if I understand correctly you are trying to create your own plugin. The approach you picked is suboptimal. While you could surely make it to work I suggest you take different path. It is easy to create custom plugin using https://github.com/cockpit-project/starter-kit/

It is documented there how to install it. And once you create it you will have a stand alone module not just some files in cockpit source code.

(back to what you posted - you are missing manifest at least. Also not sure how you are building cockpit and how you install it so it is tricky to guess).

**Comment by dpk89** [comment]
@marusak 
I have installed cockpit using the cockpit -project repo and tag 238.1
**https://github.com/cockpit-project/cockpit/releases/tag/238.1**

Have also added manifest file now, but still same.
Only Storage is getting listed.

**manifest.json.in**
![image](https://user-images.githubusercontent.com/39826327/117410525-280a8080-af30-11eb-847c-a74e9f65ebd4.png)

**Comment by marusak** [comment]
can you please show me output of `ls dist/nifi` and `ls ~/.local/share/cockpit`?

**Comment by dpk89** [comment]
@marusak 
nifi directory is not getting created in dist
**Output of ls dist and ls ~/.local/share/cockpit** :
![image](https://user-images.githubusercontent.com/39826327/117430222-8726c000-af45-11eb-8c65-23b9a4d7b74e.png)

**Comment by marusak** [comment]
> nifi directory is not getting created in dist

That means it does not build. I really suggest just using starter kit, should be much easier to develop then fitting it into cockpit source directly. Any reason why you don't want to use that?

**Comment by marusak** [comment]
To make it build you need to also add `nifi` into `Makefile.am` `WEBPACK_PACKAGES` as well as into `webpack.config.js` at two places (check for example `metrics` in this file). This all done just works in starter kit.

**Comment by dpk89** [comment]
As per your guidance have added nifi into all places. It got listed in sidebar but in Applications listing.
Now the out of ls dist/nifi is
![image](https://user-images.githubusercontent.com/39826327/117443676-1e940f00-af56-11eb-8fb1-55d177d4b521.png)

Also I want to list NiFi in sidebar only when its installed.

> I really suggest just using starter kit
Is any video demo available for this?

**Comment by martinpitt** [comment]
@dpk89 : See https://cockpit-project.org/blog/cockpit-starter-kit.html for an introduction to starter-kit.

**Comment by dpk89** [comment]
@marusak 

> There are tricks how you can tell it about it (like creating local repository) or releasing your application into your OS.

Where is it mentioned?

> Can you elaborate what is your goal? You seem to be only concern about app being listed in Applications page - while not having app in a first place.

I have Apache NiFi installed on my system, anyhow I just want to list it in applications listing to run or stop the same.
It should be displayed in sidebar only when it is in running state.

> It is just three commands or so all mentioned in README.md

Sorry, it contains only the steps to clone and build

**Comment by dpk89** [comment]
@marusak 
Okay, but now I have uninstalled NiFi, but it's still there in sidebar menu.
Now decide to display it in menu now, only if it is installed.

**Comment by marusak** [comment]
> Now decide to display it in menu now, only if it is installed.

Right, if you symlinked it (as developers do) then you just need to unlink it.
If you are looking how users would deal with such situation, then the answer is "packaging".
I am not sure how nifi is delivered, but hopefully it is a package. Then you can add into your cockpit-nifi package `Requires: nifi` (or something similar based on OS, how nifi is delivered...) and then when someone would remove `nifi` it would remove also `cockpit-nifi`. It also deals with situation that if someone would install `cockpit-nifi` it would also install `nifi`.

**Comment by marusak** [comment]
Closing as everything works as expected from our side
