### ISSUE TITLE
 ssl port redirection fail (  segfault at 60 ip  error 4 in libglib-2.0.so.0.3600.3)

### ISSUE THREAD

**Issue by subhashc** [cockpit-project/cockpit#1581]
I have successfully installed cockpit server in 
OS: Redhat Enterprise  Linux release 7.0.1406 (Core)
Kernel: 3.10.0-123.el7.x86_64
when i try to browse http://10.10.10.6:9090 it  redirect to (SSL)  https://10.10.10.6:9090 page is not opening.

http://10.10.10.6:9090   URL is working in  local  machine but if i open in remote this  URL  https://10.10.8.6:9090 page is not loading and through below errors

[root@docker-host3 build]# systemctl status cockpit.socket
cockpit.socket - Cockpit Web Server Socket
   Loaded: loaded (/usr/lib/systemd/system/cockpit.socket; disabled)
   Active: active (listening) since Wed 2014-12-10 23:21:22 IST; 6min ago
     Docs: man:cockpit-ws(8)
   Listen: [::]:9090 (Stream)

Dec 10 23:21:22 docker-host3 systemd[1]: Starting Cockpit Web Server Socket.
Dec 10 23:21:22 docker-host3 systemd[1]: Listening on Cockpit Web Server Socket.
[root@docker-host3 build]#
# var - log

Dec 10 23:25:54 docker-host3 systemd: Starting Cockpit Web Server...
Dec 10 23:25:54 docker-host3 systemd: Started Cockpit Web Server.
Dec 10 23:25:54 docker-host3 cockpit-ws: Using certificate: /usr/etc/cockpit/ws-certs.d/~self-signed.cert
Dec 10 23:25:54 docker-host3 cockpit-ws: HTTP Server listening on port 9090
Dec 10 23:25:55 docker-host3 kernel: cockpit-ws[18479]: segfault at 60 ip 00007f934f0e7621 sp 00007fffe958a6d0 error 4 in libglib-2.0.so.0.3600.3[7f934f0a2000+127000]
Dec 10 23:25:55 docker-host3 abrt-hook-ccpp: Saved core dump of pid 18479 (/usr/libexec/cockpit-ws) to /var/tmp/abrt/ccpp-2014-12-10-23:25:55-18479 (10547200 bytes)
Dec 10 23:25:55 docker-host3 systemd: cockpit.service: main process exited, code=dumped, status=11/SEGV
Dec 10 23:25:55 docker-host3 systemd: Unit cockpit.service entered failed state.
Dec 10 23:25:55 docker-host3 abrt-server: Executable '/usr/libexec/cockpit-ws' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Dec 10 23:25:55 docker-host3 abrt-server: 'post-create' on '/var/tmp/abrt/ccpp-2014-12-10-23:25:55-18479' exited with 1
Dec 10 23:25:55 docker-host3 abrt-server: Deleting problem directory '/var/tmp/abrt/ccpp-2014-12-10-23:25:55-18479'

I have installed and uninstalled multiple times but no luck. 

Can any one suggest how to fix?

**Comment by e-minguez** [comment]
In my tests, the no-tls.conf needs to "clear" execstart first:
```
cat /etc/systemd/system/cockpit.service.d/no-tls.conf
[Service]
ExecStart=
ExecStart=/usr/libexec/cockpit-ws –no-tls
```
(because ExecStart doesn’t allow overwrite the /usr/lib/… default without first “clear” it)

**Comment by Ralnoc** [comment]
The SSL port issue is most likely a result of the fact that CentOS 7 is running on glibc 2.17 and glib2 2.36.3 and Fedora is running on glibc 2.20 and glib2 2.42.1. 

Running with the --no-tls option will likely be required until there is an update to that package available for CentOS 7.

**Comment by kbsingh** [comment]
cockpit on CentOS-7 is done against glib2 2.36.3  ref:  https://github.com/cockpit-project/cockpit/issues/1581#issuecomment-77206094

given that we've already moved forward from whats in the baseline distro, to satisfy the cockpit requirement - is there any reason why we cant move to a newer ver ? 

the flip side might be - why is cockpit moving to only working with very new versions of deps

**Comment by stefwalter** [comment]
> Why is cockpit moving to only working with very new versions of deps

That's not what we do. Cockpit requires the minimum dependency that allows it to function. That is glib-2.37.4. Earlier upstream versions of glib crash due to the glib bug mentioned above. If you've back ported the relevant patches to earlier versions, then you should patch your cockpit.spec to account for that.

I posted this on cockpit-devel many months ago, with specifically CentOS in mind:

https://lists.fedorahosted.org/pipermail/cockpit-devel/2014-December/000212.html

**Comment by kbsingh** [comment]
adding @lsm5 

we have fozen on cockpit 0.27 since dec due to the Atomic folks asking for it to not move beyond, is this something we need to consider for 0.27 as well ? 

Lokesh thoughts ?

**Comment by stefwalter** [comment]
> we have fozen on cockpit 0.27 since dec due to the Atomic folks asking for it to not move beyond, is this something we need to consider for 0.27 as well ? 

Yes, that continues to be our last stable release. We're moving toward stabilizing another release in the next month or so.

And yes, the glib bug (and versions in which it is patched) above applies to cockpit-0.27 just as much as it does to the latest development release.

**Comment by Ralnoc** [comment]
Does anyone know if there is there a glibc patched RPM for CentOS 7 out there? Otherwise I'll look into building one for it.

**Comment by lsm5** [comment]
ok, so these 2 patches were added in the glib2 that cockpit uses: http://fpaste.org/193998/58535414/ and http://fpaste.org/193997/42558532/ .

@stefwalter could you dumb this down for me please: `you can use the mechanism provided by pkg-config to
override the check in question.` Is it a matter of `BuildRequires: pkgconfig(glib2)` ? Also, I don't see any failure output on running `configure`. This is probably the missing piece causing trouble on c7.

Sorry about that.

Btw, the NVRs I have:

    $ rpm -q cockpit glib2
    cockpit-0.27-1.el7.centos.x86_64
    glib2-2.36.3-6.el7.centos.x86_64

**Comment by lsm5** [comment]
@Ralnoc feel free to take this up if you prefer.

**Comment by stefwalter** [comment]
@lsm5 The cockpit build failures happened here #1586 and commit 7f0a31e44b6f590728c02689784a031f14e07e85
