### ISSUE TITLE
Can manifest.json file "doc"  open a file on the server?

### ISSUE THREAD

**Issue by rrandecker** [cockpit-project/cockpit#15811]
I am creating an addon package for cockpit, and want to include a help document, but don't have an external server to use for URL. 
Is there a way to have the doc in the manifest.json file bring up a file on the server, instead of putting in a static URL? 

Thanks

**Comment by marusak** [comment]
Unfortunately not.

**Comment by rrandecker** [comment]
Thank you for the clarification.  I know I could add my own help button.  Wanted to avoid having multiple help buttons if I could use the one already there.
