### ISSUE TITLE
services: Services View across machines

### ISSUE THREAD

**Issue by mayankasthana** [cockpit-project/cockpit#15822]
Page: Services

It would be great if we could manage a systemd service across machines.

My usecase is to start, stop and see the status of a systemd service running on multiple machines at the same time.

**Comment by marusak** [comment]
I am sorry to be a bearer of bad news but this is not the direction in which Cockpit wants to go. Cockpit is meant to be a tool to dive deep into one machine. It is not meant to be automation tool nor group management tool. For such tasks you can for example use Ansible (to stop/start service on all of your machines) or some other products like [Foreman](https://www.theforeman.org/) for example.

**Comment by mayankasthana** [comment]
Thanks, I'll look into other projects for my usecase.
