### ISSUE TITLE
Cockpit 244 on centos7

### ISSUE THREAD

**Issue by NovaDecker** [cockpit-project/cockpit#15829]
Cockpit version: 244
OS: centos 7
Page: 
Installation

I can not install Cockpit 244 on CentOS 7, since I gets an error saying:

fatal: Not a git repository (or any of the parent directories): .git

And 
error: unknown option `reference-if-able'
usage: git clone [options] [--] <repo> [<dir>]

If I try to run ./configure manually, it says:
Requested 'libsystemd >= 235' but version of systemd is 219

It is not possible to find libsystemd>235 to CentOS 7...

Could you explain me how you are thinking this should be solved?

**Comment by marusak** [comment]
> fatal: Not a git repository (or any of the parent directories): .git

What exact command are you executing?

> error: unknown option `reference-if-able'

Right, our current master expects a newer version of `git` that what you have installed/what is available for centos-7

> It is not possible to find libsystemd>235 to CentOS 7...

Might be, we don't support centos-7 from master branch anymore.

To sum up - we don't support centos-7 anymore so it will take some non-trivial effort to even build it and very likely a lot of stuff won't work as expected. We support centos-8 and one can get pre-releases from https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/

[rhel-7.9](https://github.com/cockpit-project/cockpit/tree/rhel-7.9) branch should be buildable for centos-7 but it is far behind master.

**Comment by NovaDecker** [comment]
What command i am executing: I do not know, it happens in the autogen.sh

I think it is a bit strange that you does not support centos 7 now, because EOL of centos 8 are coming soon.. What should I do? If I use centos 8, then virtio-fs does not work, because the kernel version is too old. CentOS 7 does have a newer kernel version that makes it possible.

**Comment by marusak** [comment]
> because EOL of centos 8 are coming soon

right, we support centos-8-stream, sorry for confusion. Surely that has newer kernel than centos-7

**Comment by NovaDecker** [comment]
Be right bak, i am installing centos 8....

**Comment by NovaDecker** [comment]
Ok, there we go. Now I have installed cockpit-224 on the CentOS 8, from the YUM repository.
Now I am wondering how I can upgrade to cockpit-244? Could you tell me that?

**Comment by marusak** [comment]
You can use pre-releases from https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/ (see right column how to install this repo).
