### ISSUE TITLE
Cockpit should build and run without systemd

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1583]
Cockpit should build and run without systemd, for example on RHEL 6. This means a few things:

 * Optional use of libsystemd and journal code in cockpit-ws and cockpit-bridge
 * An alternate package which provides the 'server' component that does not use systemd functionality.
 * A simple sysv startup script

**Comment by subhashc** [comment]
Hi Stef,
Can you provide me cockpit installation guide for RHEL 6.

**Comment by stefwalter** [comment]
Cockpit does not build or run on RHEL 6 at this time. Hopefully we can get to that point in the future.

**Comment by msx** [comment]
Hi all,
I too am interested in running Cockpit on my RHEL / CentOS servers at work, please let me know if can help with the testing / bugs-squashing..
Regards!

**Comment by stefwalter** [comment]
@msx That's great, but we're not at that point yet. The basic work to build on RHEL6 isn't there yet. Here's a related trello card:

https://trello.com/c/3h8dyPl6/70-build-cockpit-bridge-rhel6

**Comment by stefwalter** [comment]
I'm moving this to the Ideas page since it's not clear who would contribute this work and when or if it would happen. https://github.com/cockpit-project/cockpit/wiki/Ideas
