### ISSUE TITLE
Document Safari workaround on Cockpit's "blank" certificate error page

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15831]
When there's a problem on signing in that's likely the result of Safari WSS brokenness, suggest a workaround.

It should probably have simple, plain text instructions and should refer to the Cockpit website's install page for details on the workaround (https://github.com/cockpit-project/cockpit-project.github.io/issues/410).

**Comment by martinpitt** [comment]
It's [now in our FAQ](https://cockpit-project.org/faq.html#blank-page-using-safari), and our "blank" page is not really blank any more, but even has a dedicated Safari help paragraph.
