### ISSUE TITLE
repeated ( looping ) webpage warnings from storage.js:349 

### ISSUE THREAD

**Issue by jacksnodgrass** [cockpit-project/cockpit#15858]
Cockpit version: cockpit-244.1-1.fc34.x86_64
OS: Fedora 34
Page: Storage 

on the webpage screen for Storage in the Devices box, there is a spinning activity indicator.  
The developer console on Chrome has repeating warnings... 

One of aria-label or aria-labelledby properties should be passed when using the progress component without a title. 
 - storage.js:349

I've been sitting on the Storage page for a bit and there have been over 3000 warnings of this message produced.   It's up to 3500 now... One of the devices in the devices box keeps spinning and the warning keep going. 

I don't know what that aria-label waning means... but I think it's self explanatory.

I get the same waning issue on Firefox too.  I have the latest Firefox and Google-Chrome-Unstable that Fedora 34 has put out. 

you can see a partial animation... a few pixels of the spinner over the /dev/md2 line in the Devices pic that has been attached to this. That's where the full spinner animation is occuring. 

Steps to reproduce

1. setup a mdadm raid mirror on two drives... call it /dev/md1 - I used the command line to create this device. 
2. setup a 2nd mdadm raid mirror on two drives... call it /dev/md2 - I used the command line to create this device. 
3. create a lvm volume group with the two mdadm devices. I used cockpit to assemble the lvm group. 

![capture_20210524-080733](https://user-images.githubusercontent.com/3471734/119353591-affac500-bc68-11eb-8538-b5bfe61819ce.jpg)

**Comment by marusak** [comment]
Thanks for the report. I just sent #15873 that fixes it
