### ISSUE TITLE
Layout: Disks with long serial id mess up the page layout

### ISSUE THREAD

**Issue by ne20002** [cockpit-project/cockpit#15886]
Simply a screenshot:

![grafik](https://user-images.githubusercontent.com/39007279/120669758-07323e00-c490-11eb-82f4-5c6f0e011626.png)

Would it be an option to limit width of serial id?

**Comment by marusak** [comment]
I think we want to just limit it with css.
When I try it out, the whole panel gets out of screen:
![Screenshot from 2021-06-04 14-36-52outofscreen](https://user-images.githubusercontent.com/12330670/120802219-78cac480-c542-11eb-9c47-15fc30802e5d.png)

**Comment by ne20002** [comment]
Yes, and with the panel getting out of the screen on the right side, the warning icon as seen in my screenshot also gets out of sight.
Limitting the field displaying the serial with css should be enough. The other information in the boxes is more relevant than the serial and should not be moved outside the screen.
