### ISSUE TITLE
'install' (sub)command missing from dnf command

### ISSUE THREAD

**Issue by smwltr** [cockpit-project/cockpit#15889]
Cockpit version: master branch
OS: Fedora 34

HACKER.md has an invalid command:
$ sudo dnf chromium-headless dbus-daemon

PR #15888 fixes this.

**Comment by marusak** [comment]
In general, there is no need to open an issue once there is pending PR.
Now the commit in #15888 should have `Fixes #15889` so once we merge it, it closes this issue.

Do you want to re-push with amended commit message?
