### ISSUE TITLE
Create timer modal improvements (SPUR)

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#15927]
- [x] `After specific boot` needs validation (try putting there "`-x` seconds")
- [x] `Repeat hourly` should be better explained (MM did not get it takes minutes, maybe specify somewhere that minutes are needed)
- [x] `Repeat hourly` wraps +- buttons to different line when it does not validate [1]
- [x] In `Repeat yearly` height of date picker is taller than of hour picker - they don’t align [2] (not for all, for MM they alight, for KK they don't, check development builds on different browsers) (kk: can't reproduce any more)
- [x] +- button don’t fit onto one line on iphone SE [4] 
- [x] +- button do not align with selectors [3] (#16618)
- [ ] On small screens the ends of date and hour dropdowns are partly hidden behind shell [5] (Reported upstream, I don't see how we can fix it locally https://github.com/patternfly/patternfly-react/issues/6616)

Questions:
- [x] `Repeat monthly` and pick `31` - would that work for months with 30 days? (or is that just out of our scope?) 
- [ ] Icons in +- buttons are not perfectly centered? (we were not exactly sure, lets check it out - if it is an issue move to the list above) (kk: can't see the problem here)

[1]
![Screenshot from 2021-06-10 15-22-5670](https://user-images.githubusercontent.com/12330670/121532570-c2faec80-c9ff-11eb-9aae-86798e71b494.png)

[2] 
![Screen Shot 2021-06-11 at 14 24 27](https://user-images.githubusercontent.com/12330670/121533647-c478e480-ca00-11eb-8714-72228395ae71.png)

[3]
![Screenshot from 2021-06-10 15-29-02](https://user-images.githubusercontent.com/12330670/121533826-f12cfc00-ca00-11eb-898a-d2057f5322d8.png)

[4]
![Screen Shot 2021-06-11 at 15 33 35](https://user-images.githubusercontent.com/12330670/121534165-42d58680-ca01-11eb-9996-91d2bf86a9e7.png)

[5]
![Screen Shot 2021-06-11 at 15 33 44](https://user-images.githubusercontent.com/12330670/121534380-74e6e880-ca01-11eb-85a0-914fc748c6ee.png)

**Comment by KKoukiou** [comment]
Regarding the last point:
> Icons in +- buttons are not perfectly centered? (we were not exactly sure, lets check it out - if it is an issue move to the list above)

it's because all element apart from the buttons have pf-c-form-control class which changes the height. i think I will need to communicate with PF css people for that.

**Comment by KKoukiou** [comment]
>     * [ ]  `After specific boot` needs validation (try putting there "`-x` seconds")
> 
>     * [ ]  `Repeat hourly` should be better explained (MM did not get it takes minutes, maybe specify somewhere that minutes are needed)
> 
>     * [ ]  `Repeat hourly` wraps +- buttons to different line when it does not validate [1]
> 
>     * [ ]  In `Repeat yearly` height of date picker is taller than of hour picker - they don’t align [2] (not for all, for MM they alight, for KK they don't, check development builds on different browsers)
> 
>     * [ ]  +- button don’t fit onto one line on iphone SE [4]
> 
>     * [ ]  +- button do not align with selectors [3]
> 
>     * [ ]  On small screens the ends of date and hour dropdowns are partly hidden behind shell [5]
> 
> 
> Questions:
> 
>     * [x ]  `Repeat monthly` and pick `31` - would that work for months with 30 days? (or is that just out of our scope?)

That will generate:
```
[Unit]
Description=test0
[Timer]
OnCalendar=*-*-31 00:00:00
[Install]
WantedBy=timers.target
```

Which will just not run on months without 31st.

> 
>     * [ ]  Icons in +- buttons are not perfectly centered? (we were not exactly sure, lets check it out - if it is an issue move to the list above)

Their height is different than other widgets.
This is because all element apart from the buttons have pf-c-form-control class which changes the height. i think I will need to communicate with PF css people for that.

**Comment by garrett** [comment]
> Which will just not run on months without 31st.

I guess we need to add a little warning when days > 28 are selected. :frowning_face: 

>> On small screens the ends of date and hour dropdowns are partly hidden behind shell
>
> Not sure we can do much here

Yeah. I think this would have to be handled in PF JS. Dropdowns shouldn't go out of the document bounds (iframe being a document, of course), which is what's happening here. I don't think any amount of CSS (z-index or otherwise) would fix it, as this is placed and sized with JavaScript.

We'll just have to let it be and rest assured that people can select _most_ items and also enter the time/date manually. (And in the date case, people probably shouldn't select a day higher than 28 anyway, unless they want a not-February and – in some cases – an every-other-month tick-tock approach.)
