### ISSUE TITLE
Long description in Timers tab breaks (self and also UI) (SPUR) 

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#15928]
Create failing timer (for example select `After system boot` and input `-x`). Then on overview you will see:
![Screenshot from 2021-06-10 15-40-56one](https://user-images.githubusercontent.com/12330670/121535256-49b0c900-ca02-11eb-9a52-087f510d7c5c.png)

It should not break the string.
It is even worse on small phone screens (iphone SE)
![Screen Shot 2021-06-11 at 15 41 05](https://user-images.githubusercontent.com/12330670/121535326-59c8a880-ca02-11eb-9cae-0180b1b0704f.png)

**Comment by KKoukiou** [comment]
@garrett this is the last issue remaining from last SPUR, and when it's ready we can arrange the next SPUR. However I was not able to fix this, no matter how much I put all my CSS knowledge on the keyboard.

When you have time please pick this up!
