### ISSUE TITLE
shell: Show versions of cockpit-* packages

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15962]
In the about modal, we should list not just the main Cockpit version, but various additional Cockpit-related packages that are also installed, like cockpit-machines, cockpit-podman, cockpit-ostree, etc.

**Comment by martinpitt** [comment]
Similar to issue #5092 to show the versions o the Applications page.

**Comment by marusak** [comment]
I would say it is the same as #5092 - it is not that much about just the applications page, but showing it for the whole installation.
