### ISSUE TITLE
dist/ caching does the wrong thing in non-rebased PRs

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#15960]
Any time someone proposes a non-rebased PR, GitHub generates a merge commit vs. the master branch and starts running the `build-dist` workflow out of that.  We end up a `dist/` corresponding to the PR head branch, as if it had been rebased onto the current target branch.  That's what we want: testing changes as they would look if they landed on the master branch now.

The problem starts, however, when the `publish-dist` workflow starts running and names the result of that build according to the sha of the PR head commit.  We do that for two main reasons:
 - this is the easier thing to check from the `workflow_run` event that triggers that workflow
 - we want to get the cache result for non-rebased checkouts of the PR head branch (for example, for testing locally, or also for packit builds)

The problem is made complete by running `tools/webpack-jumpstart` in that PR branch.  You are working with a non-rebased `src/`, `pkg/`, `node_modules`, `package-lock.json`, and everything else, but your `dist/` was built from a rebased version of the tree.  This is most readily apparent when there have been changes to the `node_modules/` on the master branch, because now your `package-lock.json` will be out of sync.

The current situation also prevents the dist cache from being useful from our integration test runs (which rebase the branch, ending up with a different commit ID) and will also be a problem in the future when packit also does a merge (and surely ends up with another distinct result).

This problem has been making my skin crawl for quite some time, because we basically have a cache that introduces corrupt results into the tree: the `dist/` that you get might very well be different than the `dist/` you would get if you ran the build yourself locally.

I'm also afraid that there are not any good solutions here.

 - we could disable `build-dist` for PRs and use it only on `push`.  This is the case where it's the most useful, anyway.
 - we could query the PR from the workflow_run (this is harder than it sounds) and tag using the merge commit ID, and then figure out a way to get the merge commit onto our own machines, packit, etc. in order to make sure everything associated with a PR is testing from the exact same set of files
 - we could abandon naming by SHA for the PR merge case and, for example, name the branch according to the PR number or something like that
 - we could try to figure out a way to tie the cache to the PR itself (as it was when we had artifacts), but it needs to be done in a way that packit can access it
 - ???

**Comment by martinpitt** [comment]
I think PR #16158 sufficiently addressed this. Please yell at me and reopen if you disagree. Thanks!
