### ISSUE TITLE
Visual bug on checking for new application

### ISSUE THREAD

**Issue by costaht** [cockpit-project/cockpit#15964]
Hi guys, thanks for this great tool! 
Just want to report this visual bug where you forgot to add a space after the word "applications"

![Screenshot from 2021-06-16 15-56-30](https://user-images.githubusercontent.com/50637431/122284523-abb67600-cebb-11eb-8639-1e59d386b563.png)

**Comment by KKoukiou** [comment]
Hey @costaht - thanks for reporting this! I fixed the issue you found plus multiple other visual issues on the Apps page with https://github.com/cockpit-project/cockpit/pull/15966
