### ISSUE TITLE
Storage: potential crash without slots

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#15988]
Cockpit version: 247
Page: Storage

Coverity detected a new issue in the latest version:
```
 3. cockpit-247/pkg/storaged/crypto-keyslots.jsx:482: null_check: Comparing "slots" to a null-like value implies that "slots" might be null-like.
8. cockpit-247/pkg/storaged/crypto-keyslots.jsx:509: property_access: Accessing a property of null-like value "slots".
#   507|           }
#   508|   
#   509|->         var keys = slots.map(decode_clevis_slot).filter(k => !!k);
#   510|   
#   511|           var rows;
```
This comes from PR #15924 and looks legit -- there is nothing in the code that intercepts `slots == null`. There is only the more specific
```js
        if ((slots == null && slot_error == null) || slot_error == "not-found")
            return null;
```

the component does error handling as well, so I think that condition by itself makes sense. So how about

    var keys = slots ? slots.map(decode_clevis_slot).filter(k => !!k) : [];

**Comment by mvollmer** [comment]
Makes sense to me.
