### ISSUE TITLE
Make error 

### ISSUE THREAD

**Issue by softuvo** [cockpit-project/cockpit#15989]
Cockpit version: Latest clone from github
OS: Ubuntu 20.04.2 LTS

Hi while running make command I am getting this error 
make[1]: *** No rule to make target 'pkg/apps/manifest.json.in', needed by 'dist/apps/manifest.json'.  Stop.
make[1]: Leaving directory '/cockpit'
make: *** [Makefile:3217: all] Error 2

Please check screenshot
https://snipboard.io/MiUO5G.jpg

**Comment by martinpitt** [comment]
pkg/apps/manifest.json.in has not existed any more since March 1 (commit eaa6c494e060920c), so this is not a "latest clone", at least not fully. Can you please show the precise steps that you tried, including the `git clone`? (starting from scratch)

**Comment by softuvo** [comment]
Hi thanks for reply actually what I did was I checkout in this tag "cockpit_238.1" because I was facing js issue in latest clone . The issue was coming in cockpit that is "Please enable javascript in your browser" but I could not found the solution for that in latest clone. Can u suggest me regarding javascript issue in latest clone . Login screen was not coming but cockpit was working I followed HACKING.md steps.

**Comment by softuvo** [comment]
Hi please mark this issue solved I ran cockpit with 242 checkout i mean I did "git checkout 242" Now javascript issue has solved.
