### ISSUE TITLE
Authentication failed: internal-error: Module is unknown

### ISSUE THREAD

**Issue by forwardpointer** [cockpit-project/cockpit#15981]
Cockpit version: compiled from the main branch pulled on June 14, 2021.
OS: [Mariner](https://github.com/microsoft/CBL-Mariner)
Page: Login page

I try to login as any user, including root, but cockpit complains "Authentication failed: internal-error: Module is unknown"

Steps to reproduce:
1. I compiled from the main branch, following the instructions in HACKING.md
2. make install
3. sudo cp src/bridge/cockpit.pam.insecure /etc/pam.d/cockpit
4. systemctl start cockpit
5. On my other device, visit https://\<ip-address\>:9090, log in
6. See the error

In the logs I only see the following messages. This is after I followed the instructions in HACKING.md to enable more debug log output from cockpit-bridge, cockpit-protocol, and cockpit-ws.
```
Jun 22 15:10:29 scz3 cockpit-session[2666]: pam_unix(cockpit:session): session opened for user root by (uid=0)
Jun 22 15:10:29 scz3 cockpit-ws[2653]: cockpit-session: couldn't open session: root: Module is unknown
```

Could anyone direct me to how further debug this? My next step is to look into the code from cockpit-session to see what's going on, but any extra help would be appreciated :)

**Comment by martinpitt** [comment]
Ugh, we should not document to install src/bridge/cockpit.pam.insecure. Supposedly your system does not have `pam_selinux`, but this is also circumventing the whole system PAM policy.

Can you please try this with tools/cockpit.pam (for Fedora/RHEL/CentOS) or tools/cockpit.debian.pam (for Debian/Ubuntu and derivatives) instead?

I'll send a PR to fix HACKING.

**Comment by martinpitt** [comment]
Sent an update in PR #15987

**Comment by forwardpointer** [comment]
Thank you very much for your response! I was able to get cockpit working (I think) by replacing the contents of /etc/pam.d/cockpit with the following 

```
#%PAM-1.0
# this MUST be first in the "auth" stack as it sets PAM_USER
# user_unknown is definitive, so die instead of ignore to avoid subsequent modules mess up the error code
-auth      [success=done new_authtok_reqd=done user_unknown=die default=ignore]   pam_cockpit_cert.so
auth       substack     system-auth
auth       optional     pam_ssh_add.so
account    required     pam_nologin.so
account    include      system-account
password   include      system-password
session    required     pam_loginuid.so
session    optional     pam_keyinit.so force revoke
session    optional     pam_ssh_add.so
session    include      system-session
```

My OS didn't have /etc/pam.d/common-*, nor did it have pam_selinux.so and pam_sepermit.so which is why I removed those lines.

**Comment by martinpitt** [comment]
Great to hear! Out of interest, which OS was that? Would it make sense to include your PAM file into tools/ so that others can use it?

**Comment by forwardpointer** [comment]
My OS is CBL-Mariner. https://github.com/microsoft/CBL-Mariner

I would be glad to include my PAM file into tools/ once I verify that the PAM file I wrote is indeed correct, haha. For instance, I am unable to login to cockpit as any user other than root. When I try, I get the following message:

```
Jun 28 20:30:21 scz3 cockpit-session[2606]: pam_ssh_add: Failed adding some keys
Jun 28 20:30:21 scz3 cockpit-session[2606]: pam_unix(cockpit:session): session opened for user shane by (uid=0)
Jun 28 20:30:21 scz3 cockpit-bridge[2623]: couldn't list directory: /usr/share/cockpit: Error opening directory “/usr/share/cockpit”: Permission denied
Jun 28 20:30:21 scz3 polkitd[2133]: Registered Authentication Agent for unix-session:16 (system bus name :1.66 [cockpit-bridge], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale C.UTF-8)
Jun 28 20:30:22 scz3 cockpit-ws[2590]: cockpit-bridge: couldn't load configuration file: /usr/etc/cockpit/cockpit.conf: Permission denied
Jun 28 20:30:37 scz3 cockpit-session[2606]: pam_unix(cockpit:session): session closed for user shane
```

I'll open an issue for this.

**Comment by martinpitt** [comment]
@forwardpointer : Sounds like you need to ./configure with `--sysconfdir /etc` at least. But the broken permissions on /usr/share/cockpit are more interesting -- that should be the normal root:root 0755, so that it's world readable. Seems it's not for you?

**Comment by RobotsAreCrazy** [comment]
Martin, i got 264.1 working stopped socket, copied over the cockpit.pam from arch folder in tools on the git and enabled, start the socket....now logged in with root account
