### ISSUE TITLE
After logging in the page is blank

### ISSUE THREAD

**Issue by fuomag9** [cockpit-project/cockpit#15985]
Cockpit version: cockpit-238.2-1.el8.x86_64
OS: RHEL 8.4
Page: login

After logging in the page is blank and then it errors out. I've tried uninstalling with `sudo dnf remove cockpit` and reinstalling but nothing changed. I've also tried restarting the cockpit socket via `sudo systemctl restart --now cockpit.socket` but nothing changed. I've tried rebooting multiple times and changing things but nothing changed. This issue started appearing randomly and nothing particular was changed in the system before it started happening. Journalctl yields no logs to this issue. I'm connecting directly to the webserver itself and there is no firewall enabled between the hosts. 

I've tried connecting from a virtual machine and it works fine. I'm using firefox 89.0.1 on the host that has the issue and 89.0.2 on the virtual machine. I've tried clearing data or using a private session but the issue seems to persist.

Below are screenshots/logs:

![blank](https://user-images.githubusercontent.com/1580624/123123543-3280cb00-d447-11eb-85aa-efa78e5edbf7.png)
![error](https://user-images.githubusercontent.com/1580624/123123544-33196180-d447-11eb-8764-1f99959b67b7.png)

```
sudo journalctl -u cockput
-- Logs begin at Wed 2021-06-23 16:43:04 CEST, end at Wed 2021-06-23 16:57:25 CEST. --
-- No entries --
```

Steps to reproduce

1. Login to the webpage

**Comment by martinpitt** [comment]
It seems there is no actual error on the target machine (192.168.1.105), but that the browser fails to talk to the websocket. Do you perhaps have some extensions which may block this? Could you try this with a fresh profile? The least intrusive way is to close firefox, and run `HOME=/tmp/f firefox`.

**Comment by fuomag9** [comment]
> It seems there is no actual error on the target machine (192.168.1.105), but that the browser fails to talk to the websocket. Do you perhaps have some extensions which may block this? Could you try this with a fresh profile? The least intrusive way is to close firefox, and run `HOME=/tmp/f firefox`.

That test did indeed work, thanks. Today it started working again in my main firefox profile (nothing was changed) but I have no clue on how it fixed itself.
