### ISSUE TITLE
No scrollbar in applications page

### ISSUE THREAD

**Issue by burner986** [cockpit-project/cockpit#15996]
Cockpit version: 239, 244, 245
OS: Fedora, Debian
Page: Application

I noticed that there is no scrollbar in the applications-page.

![image](https://user-images.githubusercontent.com/14252277/123392491-afd74780-d5cf-11eb-80ac-c01140c08127.png)

**Comment by KKoukiou** [comment]
This was fixed by:
```
commit 98c9f628b026493997c5685c238955151facc709
Author: Katerina Koukiou <kkoukiou@redhat.com>
Date:   Thu Jun 17 10:01:54 2021 +0200

    apps: Use PF4 components for the page layout
```

And will be contains in release 247. It's already available on fedora https://bodhi.fedoraproject.org/updates/FEDORA-2021-b61fc3e33d
