### ISSUE TITLE
How do I build and install cockpit-storaged?

### ISSUE THREAD

**Issue by forwardpointer** [cockpit-project/cockpit#16012]
Cockpit version: compiled from the main branch pulled on June 14, 2021.
OS: [Mariner](https://github.com/microsoft/CBL-Mariner)
Page: Storage

When I visit the Storage page it says "Storage can not be managed on this system". After a little googling, I learned that I need the cockpit-storaged package. However, I am unable to find where to get the source code and build cockpit-storaged. Any help would be appreciated!

**Comment by martinpitt** [comment]
You already have the cockpit-storaged package -- it's part of the main cockpit.git, and you are looking at the "Storage" page. What's missing is the "udisks" package/service. Normally that is pulled in through rpm/deb dependencies, but as you used a local build/install, these don't apply.

**Comment by forwardpointer** [comment]
Thanks! Now I have to figure out how to get udisks on Mariner :)

**Comment by martinpitt** [comment]
@forwardpointer : I'm afraid I haven't followed the progress of WSL, but udev/udisks are certainly *really* big challenges (unless this is all running in an actual VM, not on the Windows host through the WSL API). Good luck!
