### ISSUE TITLE
`make install` with tight umask creates inaccessible directories

### ISSUE THREAD

**Issue by forwardpointer** [cockpit-project/cockpit#16011]
Cockpit version: compiled from the main branch pulled on June 14, 2021.
OS: [Mariner](https://github.com/microsoft/CBL-Mariner)
Page: Login page

I try to login as any user other than root but cockpit gives me a 404 response. I am able to login as the root, however.

Steps to reproduce:

I compiled from the main branch, following the instructions in HACKING.md
1. make install
2. replace the pam file /etc/pam.d/cockpit to the one reported in [this issue](https://github.com/cockpit-project/cockpit/issues/15981)
3. sudo systemctl enable cockpit.socket --now
4. On my other device, visit https://\<ip-address\>:9090, log in as a user other than root
5. See the 404 response

Here are the logs:
```
Jun 28 20:30:21 scz3 cockpit-session[2606]: pam_ssh_add: Failed adding some keys
Jun 28 20:30:21 scz3 cockpit-session[2606]: pam_unix(cockpit:session): session opened for user shane by (uid=0)
Jun 28 20:30:21 scz3 cockpit-bridge[2623]: couldn't list directory: /usr/share/cockpit: Error opening directory “/usr/share/cockpit”: Permission denied
Jun 28 20:30:21 scz3 polkitd[2133]: Registered Authentication Agent for unix-session:16 (system bus name :1.66 [cockpit-bridge], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale C.UTF-8)
Jun 28 20:30:22 scz3 cockpit-ws[2590]: cockpit-bridge: couldn't load configuration file: /usr/etc/cockpit/cockpit.conf: Permission denied
Jun 28 20:30:37 scz3 cockpit-session[2606]: pam_unix(cockpit:session): session closed for user shane
```

I presume that this is caused by pam_ssh_add failing? Or do I have to change the permissions for /usr/share/cockpit to allow sudoers instead of just root? Thanks a lot for your help!

**Comment by martinpitt** [comment]
@forwardpointer : Sounds like you need to ./configure with --sysconfdir /etc at least. But the broken permissions on /usr/share/cockpit are more interesting -- that should be the normal root:root 0755, so that it's world readable. Seems it's not for you?

`pam_ssh_add: Failed adding some keys` is "known" noise, you can ignore that.

**Comment by martinpitt** [comment]
That said, of course /usr/etc works as well in general, it's just *very* unusual -- /usr should be treated as read-only, and Linux has configuration in /etc/.

**Comment by martinpitt** [comment]
One possible cause could be that your `make install` ran with a tight umask like `077`? What does `umask` show?

**Comment by forwardpointer** [comment]
Thanks for your response!

The permissions for /usr/share/cockpit and /usr/etc are root:root 0750.

umask reports 0027.

Let me ask the maintainers of Mariner to confirm that the permissions on /usr/etc should be root:root 0750 because it looks like that is not the standard Linux permissions for /usr/etc/.

So for the ./configure with --sysconfdir comand, do I run it like this?
```
./configure --sysconfdir /etc
sudo make
sudo make install
```

Thanks again!

**Comment by martinpitt** [comment]
Please don't run `sudo make`, the build can (and should) be done as normal user. Otherwise you'll get a lot of root-owned files in your build tree, and compilers, unit tests etc. really shouldn't run as root.

Otherwise, this looks by and large as intended. The bug may be that `sudo make install` doesn't work properly with a tight umask. so you may rather try something like

```
./configure --sysconfdir=/etc
make
sudo make install
sudo -s
```
and in the root shell
```
umask 022
make install
```
to work around this.

**Comment by forwardpointer** [comment]
I think this problem arose when I cloned the cockpit repo under /root, so I was already the root user when I run the configure and make commands. I'll try cloning the cockpig repo under the home dir of a normal user and then follow your instruction above.

**Comment by forwardpointer** [comment]
I finished building cockpit as a normal user, but when I log in as said user into the cockpit I get the same 404.
Here is the specific commands I issued as the normal user
```
./autogen.sh --sysconfdir=/etc --prefix=/usr --enable-debug --disable-pcp --disable-doc
make
sudo make install
sudo su
```
in the root shell
```
umask 022
make install
```
Here are the logs when I tried to log in again with the new build (nothing changed):
```
Jun 29 18:17:34 scz3 cockpit-session[4316]: pam_ssh_add: Failed adding some keys
Jun 29 18:17:34 scz3 cockpit-session[4316]: pam_unix(cockpit:session): session opened for user shane by (uid=0)
Jun 29 18:17:35 scz3 cockpit-bridge[4331]: couldn't list directory: /usr/share/cockpit: Error opening directory “/usr/share/cockpit”: Permission denied
Jun 29 18:17:35 scz3 polkitd[4293]: Registered Authentication Agent for unix-session:12 (system bus name :1.38 [cockpit-bridge], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale C.UTF-8)
Jun 29 18:17:35 scz3 cockpit-ws[4208]: cockpit-bridge: couldn't load configuration file: /etc/cockpit/cockpit.conf: Permission denied
Jun 29 18:17:51 scz3 cockpit-session[4316]: pam_unix(cockpit:session): session closed for user shane
```

It looks like /usr/share/cockpit is still root:root 0750 permissions

**Comment by martinpitt** [comment]
At this point I'm afraid I don't know where the 0750 permissions for /usr/share/cockpit come from -- umask 022 is certainly correct then. Can you try `sudo chmod go+rX /usr/share/cockpit` and see if that helps?

**Comment by forwardpointer** [comment]
Thanks for your help so far. When I tried ``` sudo chmod go+rX /usr/share/cockpit ``` it told me that it couldn't find the manifest files because they were root access only:
```
Jul 06 14:34:25 scz3 cockpit-session[15968]: pam_unix(cockpit:session): session opened for user shane by (uid=0)
Jul 06 14:34:25 scz3 cockpit-bridge[15983]: apps: couldn't read manifest.json: Failed to open file “/usr/share/cockpit/apps/manifest.json”: open() failed: Permission denied
Jul 06 14:34:25 scz3 cockpit-bridge[15983]: base1: couldn't read manifest.json: Failed to open file “/usr/share/cockpit/base1/manifest.json”: open() failed: Permission denied
Jul 06 14:34:25 scz3 cockpit-bridge[15983]: branding: couldn't read manifest.json: Failed to open file “/usr/share/cockpit/branding/manifest.json”: open() failed: Permission denied
Jul 06 14:34:25 scz3 cockpit-bridge[15983]: kdump: couldn't read manifest.json: Failed to open file “/usr/share/cockpit/kdump/manifest.json”: open() failed: Permission denied
Jul 06 14:34:25 scz3 cockpit-bridge[15983]: metrics: couldn't read manifest.json: Failed to open file “/usr/share/cockpit/metrics/manifest.json”: open() failed: Permission denied
Jul 06 14:34:25 scz3 cockpit-bridge[15983]: motd: couldn't read manifest.json: Failed to open file “/usr/share/cockpit/motd/manifest.json”: open() failed: Permission denied
Jul 06 14:34:25 scz3 cockpit-bridge[15983]: networkmanager: couldn't read manifest.json: Failed to open file “/usr/share/cockpit/networkmanager/manifest.json”: open() failed: Permission denied
Jul 06 14:34:25 scz3 cockpit-bridge[15983]: packagekit: couldn't read manifest.json: Failed to open file “/usr/share/cockpit/packagekit/manifest.json”: open() failed: Permission denied
Jul 06 14:34:25 scz3 cockpit-bridge[15983]: pcp: couldn't read manifest.json: Failed to open file “/usr/share/cockpit/pcp/manifest.json”: open() failed: Permission denied
Jul 06 14:34:25 scz3 cockpit-bridge[15983]: playground: couldn't read manifest.json: Failed to open file “/usr/share/cockpit/playground/manifest.json”: open() failed: Permission denied
Jul 06 14:34:25 scz3 cockpit-bridge[15983]: selinux: couldn't read manifest.json: Failed to open file “/usr/share/cockpit/selinux/manifest.json”: open() failed: Permission denied
Jul 06 14:34:25 scz3 cockpit-bridge[15983]: shell: couldn't read manifest.json: Failed to open file “/usr/share/cockpit/shell/manifest.json”: open() failed: Permission denied
Jul 06 14:34:25 scz3 cockpit-bridge[15983]: sosreport: couldn't read manifest.json: Failed to open file “/usr/share/cockpit/sosreport/manifest.json”: open() failed: Permission denied
Jul 06 14:34:25 scz3 cockpit-bridge[15983]: ssh: couldn't read manifest.json: Failed to open file “/usr/share/cockpit/ssh/manifest.json”: open() failed: Permission denied
Jul 06 14:34:25 scz3 cockpit-bridge[15983]: static: couldn't read manifest.json: Failed to open file “/usr/share/cockpi
/static/manifest.json”: open() failed: Permission denied
```

So I tried the recursive chmod command, because I thought that maybe everything in the /usr/share/cockpit directory needs to have rx permissions globally: ``` sudo chmod -R go+rX /usr/share/cockpit ```

This seems to work. I'll report back if I run into any issues from this. Thanks again!

**Comment by forwardpointer** [comment]
Here are some additional files I had to change permissions:
```
chmod o+rw /etc/cockpit/cockpit.conf
chmod o+rx /etc/cockpit/
```
