### ISSUE TITLE
metrics: Layout issues with metrics labels

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16016]
On the metrics page, there are various issues in different languages.

In German, for example, the text overlaps poorly:

![Screenshot from 2021-06-29 13-59-59](https://user-images.githubusercontent.com/10246/123793925-8fb2cb80-d8e2-11eb-806d-5ecf3fa17b97.png)

Same for Turkish...
![Screenshot from 2021-06-29 14-06-21](https://user-images.githubusercontent.com/10246/123794554-40b96600-d8e3-11eb-8f71-5e570c41ac62.png)

And Russian...
![Screenshot from 2021-06-29 14-04-10](https://user-images.githubusercontent.com/10246/123794557-4151fc80-d8e3-11eb-9849-1b501b3e5b26.png)

And so on...

---

In English, the I/O wraps:

![Screenshot from 2021-06-29 14-03-06](https://user-images.githubusercontent.com/10246/123794096-c25cc400-d8e2-11eb-8dec-948f8e648990.png)

**Comment by martinpitt** [comment]
Indeed the widest parts of these graphs are the labels :sob: As a relatively simple measure, we could increase the minimum width of the graphs and make the top-level headings smaller?

Side issue: I'm not sure why your screenshot shows "Auslastung" for both sides of CPU in German -- that should be "Usage" and "Load", and "Load" is [translated as](https://translate.fedoraproject.org/translate/cockpit/main/de/?checksum=7ae8cf5ef2de87cd&q=Last&sort_by=-priority%2Cposition) "Last". In a narrow window I see

![image](https://user-images.githubusercontent.com/200109/124224837-ae91a780-db06-11eb-9810-95fa4fb085fc.png)

i.e. it has the correct "Last" label. (This is version 246)

**Comment by martinpitt** [comment]
I sent PR #16110 with half a fix (medium and wide ranges). Mobile mode still to do, discussion in the PR.

**Comment by KKoukiou** [comment]
This was fixed with the redesign.
