### ISSUE TITLE
White Screen after login in on iOS devices (iPhone & iPad)  cockpit on raspberrypi4B

### ISSUE THREAD

**Issue by HappyQuQu** [cockpit-project/cockpit#16023]
Cockpit version: 188
OS: Debian GNU/Linux 10 (buster)arm64
Device:raspberrypi4B

 ### Issue description
**Follow the instructions at https://cockpit-project.org/running/safari.html to be Enabled
"NSURLSession WebSocket",
Deployed on
Cockpit on Debian GNU/Linux 10 (buster) arm64 I use ipad pro (ios14.6) to log in and a white screen appears
However, it is no problem when deployed on ubuntu server amd64**

###  system log :
Jun 30 19:09:00 raspberrypi cockpit-session[15170]: pam_ssh_add: Identity added: /home/pi/.ssh/id_rsa (xxx@outlook.com)
Jun 30 19:09:00 raspberrypi cockpit-session[15170]: pam_unix(cockpit:session): session opened for user pi by (uid=0)
Jun 30 19:09:00 raspberrypi cockpit-ws[15076]: logged in user session
Jun 30 19:09:15 raspberrypi cockpit-ws[15076]: session timed out

### screenshots
![6E6ACBF4B466D09E1F3074D491B7D8AA](https://user-images.githubusercontent.com/4098823/123953228-93754980-d9d9-11eb-8d7f-f940ce58d535.png)

**Comment by ragnaroks** [comment]
same as #12745 ,it's device uncorrelated,use privacy mode

**Comment by HappyQuQu** [comment]
> same as #12745 ,it's device uncorrelated,use privacy mode

it's not work

**Comment by garrett** [comment]
I have an old Raspberry Pi 1 I use for local DNS (including tracker blocking via pihole) running Raspbian (Raspberry Pi OS) with Cockpit 188 (which is _ancient_, but so is Buster) and can sign into it just fine with my iPhone running iOS 14.6, using the workaround. I can also sign into Cockpit 247 on Fedora 34 IoT (aarch64) on a Raspberry Pi 4.

The difference between your Debian and Ubuntu server versions is most likely not x86 versus ARM, but the version of Cockpit. However, I've signed into both Cockpit 188 specifically on armv7 and Cockpit 247 on aarch64 with default self-signed certificates on both servers here and it works from my test iPhone.

I know that we did rework the certificate handling a long time ago in-between these versions. (As it happened in the PatternFly 4 era and 188 is still 100% PatternFly 3.) So I'd suggest upgrading Cockpit to a newer version.

As Cockpit 188 was released round 2.5 years ago, I think you and I should probably enable Debian backports. We have instructions outlined at https://cockpit-project.org/running.html#debian.

(Although my Raspberry Pi is running Raspbian, so I should really switch it over to plain Debian and enable backports at some point... but you said you're using Debian, so you should be able to upgrade with the instructions at the link.)


---

**Summary**: Use backports with the instructions at https://cockpit-project.org/running.html#debian to get a recent version of Cockpit on Debian. Hopefully this will solve your issue.

**Comment by garrett** [comment]
Alternatively, Debian 11 will be released next month on August 14. It should also have a newer version of Cockpit (although one that's probably not as recent as backports).

**Comment by garrett** [comment]
I believe this has been fixed.

If you're still getting a white page under the same conditions with a newer version of Cockpit, please re-open to let us know to see if there's anything we can do to help.

Thanks! :sparkles:
