### ISSUE TITLE
Set config variables and access into html file

### ISSUE THREAD

**Issue by dpk89** [cockpit-project/cockpit#16044]
Hi,

I want to create set dynamic URL in configure file and want to access into package .html.

How we can do this?

I have tried by defining in configure file at root folder , but its not accessing in html file.

Thanks.

**Comment by martinpitt** [comment]
I'm afraid I don't understand what you want to do. If you want to serve cockpit on a different URL path prefix, you can set `UrlRoot=` in cockpit.conf, see [the documentation](https://cockpit-project.org/guide/latest/cockpit.conf.5.html).
