### ISSUE TITLE
Can't get failed service resolved

### ISSUE THREAD

**Issue by ne20002** [cockpit-project/cockpit#16048]
Cockpit version: 239
OS: debian bullseye
Page: Services

I get, once a week, the following problem:

![grafik](https://user-images.githubusercontent.com/39007279/124487531-23870a80-ddaf-11eb-979a-3c0a506fbe4e.png)

This is due to fstrim returning an error. On the prompt I get:

`xx@u-nas0:~$ sudo fstrim -av

[sudo] password for pi: 

/boot/efi: 482.6 MiB (506073088 bytes) trimmed on /dev/nvme0n1p1

fstrim: /mnt/data1: FITRIM ioctl failed: Invalid argument

/boot: 0 B (0 bytes) trimmed on /dev/mapper/vg_system-lv_boot

/mnt/data0: 909.2 MiB (953413632 bytes) trimmed on /dev/mapper/vg_data0-lv_data0

/: 858.5 MiB (900210688 bytes) trimmed on /dev/mapper/vg_system-lv_root

xx@u-nas0:~$ 
`

Restarting the service is not working, it just 'fails' again. To get rid of the red status I need to reboot the machine.

The fstrim error is due to TRIM not supported on lvm cached volume and also not for the underlying hard disks.

Not sure what the solution would be .. but kind of an 'accept' button / status may be an idea.

**Comment by martinpitt** [comment]
You can click on the unit to get the details, then in the action menu you find the Clear "failed to start" entry. This is the equivalent of "systemctl reset-failed" *unitname* on the command line.

![image](https://user-images.githubusercontent.com/200109/124493404-e40fec80-ddb5-11eb-8c95-d4db11e81344.png)

I'm not sure if that exists already in version 239, but it does in the current upstream version.

**Comment by ne20002** [comment]
Thank you
Not sure if it is availabe in 239. It's not shown but I may need to wait until the service fails again (which is weekly at the moment).
:(

Debian is stucked to Cockpit version 239 ... I hope to get newer version once Bullseye backports are available.
