### ISSUE TITLE
Adding servers to cockpit (  ssh:notty ) 

### ISSUE THREAD

**Issue by subhashc** [cockpit-project/cockpit#1605]
HI,

Cockpit running under RHEL 7.0 

when i am trying to add remote servers in cockpit portal, i am getting below errors

[root@docker-host3 ~]# journalctl -b | grep cockpit
--------------------------------------------------------------
Dec 12 23:06:49 docker-host3 cockpit-session[19150]: pam_unix(cockpit:session): session closed for user root
Dec 15 21:56:43 docker-host3 cockpit-ws[28703]: HTTP Server listening on port 9090
Dec 15 21:56:56 docker-host3 cockpit-session[28705]: pam_unix(cockpit:session): session opened for user root by (uid=0)
Dec 15 21:56:56 docker-host3 cockpit-ws[28703]: cockpit-session: pam: Last failed login: Fri Dec 12 22:51:50 IST 2014 from 10.10.10.109 on ssh:notty

[root@docker-host3 ~]# cat  /etc/pam.d/cockpit
-----------------------------------------------------------
#%PAM-1.0
auth            required     pam_sepermit.so
auth            substack     password-auth
auth            include      postlogin
auth            optional     pam_reauthorize.so prepare
account         required     pam_nologin.so
account         include      password-auth
password        include      password-auth
# pam_selinux.so close should be the first session rule
session         required     pam_selinux.so close
session         required     pam_loginuid.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session         required     pam_selinux.so open env_params
session         optional     pam_keyinit.so force revoke
session         optional     pam_reauthorize.so prepare
session         include      password-auth
session         include      postlogin

Could you please suggest.

**Comment by stefwalter** [comment]
This code has been reworked. I believe it should work now. If the problem persists feel free to comment, and we can reopen the bug.
