### ISSUE TITLE
overview: Add server name to the graphs page

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16063]
When someone's using Cockpit on multiple machines and are watching the graphs tick by, it would make sense to ensure that the current computer's name is visible.

Discussed in https://github.com/cockpit-project/cockpit/discussions/16037

(However, the current machine is in the shell at the top-right, so it's debatable if we want to make it clear in this page too.)

**Comment by KKoukiou** [comment]
Graphs page was dropped a few months ago in favor of metrics, so the discussion above is kinda obsolete. Also as you mention, the info about the hostname is in the shell and overview page, so closing this as wontfix.
