### ISSUE TITLE
Initial process in cockpit

### ISSUE THREAD

**Issue by dpk89** [cockpit-project/cockpit#16074]
Cockpit version: xxx
OS:Ubuntu 20
Page: 

Global call - I need the process which is running while I access cockpit .
From where I can validate the user info.

I want to add some middleware

**Comment by martinpitt** [comment]
Sorry, you need to be a bit more specific. Which process? If you need the user info, that's the [cockpit.user() API](https://cockpit-project.org/guide/latest/cockpit-login.html). Please have a look at the whole [API documentation](https://cockpit-project.org/guide/latest/api-base1.html) and existing examples/code.
