### ISSUE TITLE
Ubuntu 21.04 - service fails to start (namespace)

### ISSUE THREAD

**Issue by Wanni48** [cockpit-project/cockpit#16085]
Cockpit version: 238
OS: Ubuntu 21.04
Page: 

After some packages updated on Ubuntu 21.04 cockpit.service failed to start. Installation via standard package manager (apt install cockpit). Removed package and installed few times. Did not help, abways aborts with below message.

systemd[810347]: cockpit.service: Failed to set up mount namespacing: /run/systemd/unit-root/: Stale file handle
systemd[810347]: cockpit.service: Failed at step NAMESPACE spawning /usr/lib/cockpit/cockpit-tls: Stale file handle
cockpit.service: Main process exited, code=exited, status=226/NAMESPACE

Steps to reproduce

1. Install cockpit (via "apt install")  
2. 
3.

**Comment by martinpitt** [comment]
That's a systemd/kernel issue. We do test Cockpit (every commit and release) on Ubuntu 21.04, and it's not a general bug that affects everyone. Can you please report this to https://bugs.launchpad.net/ubuntu/+source/systemd ?

Does a complete reboot help? The package updates may have updated some library or component which is stale now.

**Comment by Wanni48** [comment]
Shame on me. Looks like a package update messed it up. A complete reboot helped.
Thanks for the hint!
