### ISSUE TITLE
save data for configuration 

### ISSUE THREAD

**Issue by dpk89** [cockpit-project/cockpit#16115]
OS:Ubuntu
Page: Custom package
NEED TO SAVE DATA - while user will done license add flow I need to save the license key for that 
What will be the best method?

**Comment by marusak** [comment]
Can this be stored per browser? If so, then you can use cookie. For example look for `theme_cookie` in the source code to see how it is being used. There are other browser storages available that you can use. They all differ for how long the settings are saved. What they have in common though is that they all are only for you current browser and if you connect to the same machine from somewhere else or with a different browser, you will lose these settings.

If not, then you have to designing your own storage. The same way how you would create some config for your command line tool, you can create such config for your cockpit extension. Regarding the location I would probably use ~/.config/myapp or ~/.local/share/myapp.

**Comment by dpk89** [comment]
I would like to make code setup once with this license key.
Can we configure some DB library ?

**Comment by dpk89** [comment]
Hi,

I need to execute system commands, its working for AWS CLI commands like 

cockpit.spawn(["aws", "license-manager" ,"get-license-usage" ,"--license-arn", awslicensemanagerkeyval.value])
        .stream(ping_output_val)
        .then(ping_success_val)
        .catch(ping_output_val);

**But following is not working , I want to execute terminal commands**

 cockpit.spawn(["echo", "$grafan"])
        .stream(ping_output_val)
        .then(ping_success_val)
        .catch(ping_output_val);

Thanks

**Comment by martinpitt** [comment]
@dpk89 : You don't need a DB, you can just write the license key into ~/.config/*myapp* as Matej suggested.

`"$grafan"` is a shell variable, it will not be expanded by cockpit.spawn(). This is similar to [execve()](https://www.man7.org/linux/man-pages/man2/execve.2.html). If you need shell expansion, use cockpit.script(). But really avoid that at all cost, as it introduces a whole set of security vulnerabilities.

**Comment by dpk89** [comment]
Hi,

Without execve() , how to write data to 
~/.local/share/myapp.
