### ISSUE TITLE
applications: Clicking the refresh button causes an "Oops"

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16129]
On Fedora 34, with Cockpit build from the main branch, after loading the applications page apps are loaded. However, when I clicked on the refresh button (which is unneeded in this case), it caused an "Oops".

After page load, I saw these page-specific errors in the console:

![Screenshot from 2021-07-22 09-58-16](https://user-images.githubusercontent.com/10246/126606867-2344f141-7659-4a8c-9fff-a825b21c8183.png)

And after clicking the button, I saw this:

![Screenshot from 2021-07-22 09-59-01](https://user-images.githubusercontent.com/10246/126606900-6035fc8f-2573-4cb7-990a-3e14032cff90.png)

The button is working otherwise, as evidenced by #16127 (discussion / #16128 (issue). 

It looks like this might be React reporting invalid HTML construction as an error instead of a warning? (It's still an HTML error, but browsers usually are ultra-forgiving about those. They should still be fixed, however. :wink: This is especially true as to avoid the "Oops" bug, but even if it didn't show a visible error, invalid HTML should still be corrected.)

**Comment by martinpitt** [comment]
I have some trouble reproducing this. I did a debug build as well, on Fedora 34. The first "div in p" in OsUpdates is on the "software updates" page, not on Applications. But searching the inspector for "p div" did not find anything, on either or the two pages. However, your stacktrace goes through an EmptyPanel, I don't have one right now. Do you still remember what it said for you? Any chance to make a DOM dump?

I also clicked the "refresh" button on Applications several times. It did install appstream-data.rpm, but it does not actually show me any installable application. But I also don't get these react warnings.

**Comment by garrett** [comment]
Here's Firefox's version of the DOM, using the output from copying outerHtml on the HTML element within the iframe (the page) after clicking refresh and getting the error:

[dom-dump.txt](https://github.com/cockpit-project/cockpit/files/7127751/dom-dump.txt)

You might have warnings and errors turned off in the console. Look at the bottom right of this screenshot crop:

![Screenshot from 2021-09-08 11-42-11](https://user-images.githubusercontent.com/10246/132486194-aa5bac7d-c4f9-42ac-b4b7-9d79f3f08ca7.png)

I have errors through debug toggled on and CSS, XHR, and Requests toggled off.

**Comment by KKoukiou** [comment]
Can't reproduce. @garrett if you can still reproduce with latest release please reopen, and add console logs from developer build.
