### ISSUE TITLE
accounts: Don't let someone lock their currently used account

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16152]
_Originally posted by @Verhoeckx in https://github.com/cockpit-project/cockpit/discussions/16133#discussioncomment-1037900:_

> I wonder however if it's possible to lock all accounts (so you won't be able to log in anymore in Cockpit)?
> Because I still have the option to also lock my own user account :fearful: !

It's basically a "break my system" feature that we shouldn't expose.

**Comment by marusak** [comment]
I've sent #16159
