### ISSUE TITLE
Memory utilization is not accurate in cockpit portal

### ISSUE THREAD

**Issue by subhashc** [cockpit-project/cockpit#1616]
My system having  128GB RAM but where as in cockpit dashboard  graph shows 168 GB RAM utilized

I have cross verified using command line syntax and pcp

Server command line check 
![image](https://cloud.githubusercontent.com/assets/7770603/5500350/c95e0b7e-8768-11e4-8c54-69a3797c2bd9.png)

Cockpit dashboard memory utilization snapshot

![image](https://cloud.githubusercontent.com/assets/7770603/5500491/50b4106c-876b-11e4-8f6f-13b27b8ac886.png)

**Comment by mvollmer** [comment]
I hope this is better now...
