### ISSUE TITLE
cockpit graphs(CPU/Memory) are gray color

### ISSUE THREAD

**Issue by subhashc** [cockpit-project/cockpit#1617]
![image](https://cloud.githubusercontent.com/assets/7770603/5500791/aa39259e-8772-11e4-871d-ed4c34d2b89d.png)

![image](https://cloud.githubusercontent.com/assets/7770603/5500795/c70f61ba-8772-11e4-8bae-e8da8170477e.png)

**Comment by andreasn** [comment]
As @mvollmer mentioned, the longer term fix is to move the graphs to the services page, but for a quicker fix, we can use the colors:
#7fcbff, #2daaff, #0071c4, #004b7f instead of the grays.
