### ISSUE TITLE
/router/superuser/none and /remotectl-certificate/create-no-permission tests fail

### ISSUE THREAD

**Issue by forwardpointer** [cockpit-project/cockpit#16189]
Cockpit version: 248
OS: Mariner

Hello, I am doing a custom build of cockpit and wanted to verify my build using make check. When I run the command, all the tests pass or skip, except for 2 tests that ERROR out. 

Below are the logs from the tests:
```
ERROR:src/ws/test-remotectlcertificate.c:147:setup: Got unexpected message: Generating temporary certificate using: openssl req -x509 -days 365 -newkey rsa:2048 -keyout /usr/src/mariner/BUILD/cockpit-248/test-configdir/cockpit/ws-certs.d/0-self-signed.Q3N960.tmp -keyform PEM -nodes -out /usr/src/mariner/BUILD/cockpit-248/test-configdir/cockpit/ws-certs.d/0-self-signed.A3N960.tmp -outform PEM -subj /CN=shane-ThinkPad-X1-Extreme -config /tmp/ssl.conf.EUN960 -extensions v3_req instead of (null)-Message: Couldn't create temporary file*Permission denied"

"cockpit-bridge:ERROR:src/bridge/test-router.c:774:test_superuser_none: {\"command\":\"close\",\"channel\":\"a\",\"problem\":\"not-supported\"} != {'command':'close','channel':'a', 'problem':'access-denied'}"
```

I tried running sudo make check but that made no difference. I'm a bit lost as to what these "permission denied" errors mean.
Any help would be greatly appreciated here!

**Comment by martinpitt** [comment]
That sounds like you are running the tests as root -- these are really meant to run as user, otherwise e.g. /remotectl-certificate/create-no-permission can't work as root can read files without any file permissions (through `CAP_DAC_OVERRIDE`).

**Comment by forwardpointer** [comment]
Thanks for the insight! Switching to a non-root user did the trick!
