### ISSUE TITLE
Terminal needs reset

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#1618]
Once a terminal becomes unusable (logout, invalid character sequences) user needs to log out of cockpit and log back in to recover.
![image](https://cloud.githubusercontent.com/assets/8711649/5611323/a1494cd8-94c5-11e4-8d3d-0b1f17a04878.png)

How about a reset button to get a terminal with the initial state (same as on login)?

**Comment by stefwalter** [comment]
@andreasn What do you think?

From a UI perspective should we log in again when you come back to the page?

**Comment by stefwalter** [comment]
@dperpeet could you propose a location for the button. If it's easier to do a wireframe, or just to hack the html a bit and post a screenshot for @andreasn?
