### ISSUE TITLE
Warn that changing groups for a user is effective only in new sessions

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#1619]
In Cockpit, user needs to relog for any change to the setting "Container Administrator" to take effect.

Cockpit should either display a notice that changes to the current user's role require a relog or apply them immediately.

A warning would be the easiest. For immediate effect to work, all plugins need to ensure consistency when user privileges change mid-session.

**Comment by stefwalter** [comment]
So to fix the symptom I think we should prompt the user to re-login after changing their group settings.

But secondarily, @mvollmer Do you think we should move away from using the 'docker' group? It's completely insecure, and bypasses the usual security mechanisms of Linux. It's would be a shame, because it's the only non-wheel group we've had listed in 'User Accounts' so far.

**Comment by stefwalter** [comment]
I don't think there's a way to add effective groups to a running process without that process having root privileges. So I don't think we're going to get away from logout/login.

**Comment by martinpitt** [comment]
Indeed there is no way to do this within a running session.

The "Container Administrator" (docker) group UI option is still part of our code,  but (fortunately, as it is really a bad idea), doesn't seem to be created by default any more at least in Fedora.

The only group that we show by default in the UI is "Server Administrator", and that doesn't have this problem - if you aren't already logged in as an admin, you can't change this setting.

There's also the `weldr` group. But in general, these don't affect the *current Cockpit session*, but just any possible sessions that the target user may have running. These need to be restarted for the setting to take effect. The accounts page knows whether a user has a running session, so  we can conditionalize the warning on that.  The warning should be worded accordingly.

**Comment by marusak** [comment]
It is implemented:
![mustlogoutandbackin](https://user-images.githubusercontent.com/12330670/73830292-b57a9480-4804-11ea-8548-3407cc2d0540.png)
However it shows this message even if the user is not logged in, which is a bit redundant. I will send simple fix for that.
