### ISSUE TITLE
dbus session bus needs a $DISPLAY variable

### ISSUE THREAD

**Issue by jamesjzitoiv** [cockpit-project/cockpit#16228]
While using the cockpit.dbus api (https://cockpit-project.org/guide/latest/cockpit-dbus.html), I'm getting the message: ”Unable to autolaunch a dbus-daemon without a $DISPLAY for X11” when I try to connect to the session bus. I'm able to connect to the session bus service via bash or python, but not using the cockpit.dbus api because of this error. How can I give cockpit the DISPLAY variable so it will be satisfied and connect to the session bus?

**Comment by marusak** [comment]
Can you please post exact command how you use it in shell as well as how you use `cockpit.dbus`?

**Comment by martinpitt** [comment]
No response in over a year, closing.
