### ISSUE TITLE
Decoupling of dashboard and main server (client-server architecture)

### ISSUE THREAD

**Issue by gaui** [cockpit-project/cockpit#16231]
Wouldn't it be better to decouple the dashboard from the main controller host (client-server architecture)? This way you could set up the dashboard/client in a lightweight Docker container and then add a main controller host (server), finally add secondary hosts. It wouldn't need the server running the dashboard to be the main controller host, thus making it hard to run it in a Docker container.

Just an idea.

**Comment by marusak** [comment]
Dashboard has been removed, see https://cockpit-project.org/blog/cockpit-234.html

> This way you could set up the dashboard/client in a lightweight Docker container and then add a main controller host (server), finally add secondary hosts. It wouldn't need the server running the dashboard to be the main controller host, thus making it hard to run it in a Docker container.

This is pretty much what you can do with Grafana for example - export your metrics and use some other tool to display it for you.
