### ISSUE TITLE
"Not Found" error - My Notebooks - Jupyter

### ISSUE THREAD

**Issue by stedeschi** [cockpit-project/cockpit#16230]
Hello all,

I’m at my wits end with this.

Trying to use the “My Notebooks” section. :9090/cockpit_jupyter

Whenever I try to open a notebook, it redirects to a new tab and loads for a moment before displaying the following error

“Not Found”
![image](https://user-images.githubusercontent.com/71405781/129208353-8db36ebd-b4d5-4041-ab07-73258fbc6b99.png)

Here are the two web addresses it will redirect to upon clicking “Open” on any notebook under “My Notebooks”

-http://172.22.44.100:442/?token=f432ec8e4c0dac322d666424cad8252c432c3835e50ec09a which then redirects to
-https://172.22.44.100/cockpit/@localhost/cockpit_jupyter/undefined

I was able to find two log entries in two areas around the same time as our clicks on “open”.

-one error is found in a log dump pulled up in console using “sudo journalctl -n 100 -u cockpit”

dl cockpit-tls[1322897]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.

-error in cockpit logs page not sure if related

2:38 PM unable to read: /sys/class/net/veth3ebd7a7(randomized)/operstate: No such file or directory libvirtd
2:38 PM Failed to open file ‘/sys/class/net/veth3ebd7a7(randomized)/operstate’: No such file or directory

Our system is running Ubuntu 20.04 LTS
The hostname of the system is “dl”
Cockpits file locations are: 

> (base) bizon@dl:~$ cockpit-bridge --packages
apps                 Applications                             /usr/share/cockpit/apps
base1                                                         /usr/share/cockpit/base1
cockpit_containers   Docker Images                            /home/bizon/.local/share/cockpit/cockpit_containers
cockpit_jupyter      My Notebooks                             /home/bizon/.local/share/cockpit/cockpit_jupyter
cockpit_support      Bizon Knowledge Base                     /home/bizon/.local/share/cockpit/cockpit_support
dashboard                                                     /usr/share/cockpit/dashboard
machines             Virtual Machines                         /usr/share/cockpit/machines
network              Networking                               /usr/share/cockpit/networkmanager
performance                                                   /usr/share/cockpit/tuned
playground           Development                              /usr/share/cockpit/playground
shell                                                         /usr/share/cockpit/shell
ssh                                                           /usr/share/cockpit/ssh
storage              Storage                                  /usr/share/cockpit/storaged
system               Overview, Logs, Services, Terminal       /usr/share/cockpit/systemd
updates              Software Updates                         /usr/share/cockpit/packagekit
users                Accounts                                 /usr/share/cockpit/users

This happens remotely or locally directly on the machine running cockpit.

I cannot find anyone with a similar issue after multiple hours of googling, searching cockpits github, etc.

I tried locating the notebook files manually and could not find a location after searching for related files and identifiers. I also tried manually combing all directories related to jupyter and cockpit as well as cockpit bridge.

I also tried renaming system from dl back to localhost.

I believed ports 441-3 were being blocked but that is not the case as it will not work locally, i also checked and currently ufw is disabled, so nothing locally either.

Any help would be greatly appreciated!

**Comment by marusak** [comment]
> Trying to use the “My Notebooks” section. :9090/cockpit_jupyter

What is `My Notebooks`? Is that some plugin you created?

**Comment by martinpitt** [comment]
"cockpit_jupyter" is not a part of *this* GitHub project. It is apparently some third-party project or a locally installed/generated one:  /home/bizon/.local/share/cockpit/cockpit_jupyter

Maybe you just installed this in an incomplete way? It seems to have a manifest.json, but no index.html? (or whatever file the manifest specifies)
