### ISSUE TITLE
Issue adding a host via IPv6 and custom port

### ISSUE THREAD

**Issue by MartinX3** [cockpit-project/cockpit#16240]
Cockpit version: 250
OS: arch linux
Page: Network

I can't add a host via IPv6 and custom port.
IPv4 works fine.
SSH works fine as well.
The target server can't get reached, cockpit doesn't even try to make a connection or corrupts the used IPv6 port combination

Steps to reproduce

1. Use an custom IPv6+port combination using `[2001:41d0:a:3829::1]:34123`

```
cockpit-ssh[17515]: cockpit-ssh customserver@[2001:4260:a:1234::1]:41231: refusing to connect to unknown 

cockpit-ssh[17517]: cockpit-ssh customserver@[2001:4260:a:1234::1]:41231: -1 couldn't connect: Timeout connecting to 2001:4260:a:1234::1 '2001:4260:a:1234::1' '41231'
```
PS:
I changed username, ipv6 and port for privacy reasons.

**Comment by martinpitt** [comment]
I just tested logging into my server at [2a03:4000:6:4019::2]:659 , which works just fine. So apparently this got fixed in the  meantime? If it still happens for you, please shout here and we can debug it. thanks!
