### ISSUE TITLE
Filter level on Logs page no longer changes when hitting 'enter' after typing

### ISSUE THREAD

**Issue by AdamWill** [cockpit-project/cockpit#16243]
Cockpit version: 251
OS: Fedora Linux
Page: Logs

In Cockpit 251, where the page was ported to React/PF4, if you change the text in the "Filter" box on the Logs page and hit enter, the change is not applied. I expect hitting the new "right-arrow button" element would cause the change to be applied, but I wouldn't expect that to be necessary; for convenience and a11y, it should be possible to change the filter just by typing and hitting enter. This is how it used to work.

Steps to reproduce

1. Start Cockpit
2. Go to the Logs page
3. Change the filter text from default "priority:err" to something else, e.g. "priority:info" and hit enter
4. On 250 and earlier, the change is applied and the visible messages change. On 251, the change is not applied, you continue to see messages matching the old filter.

**Comment by marusak** [comment]
Thanks for the report. We knew about this when we were implementing it (for example [here](https://github.com/cockpit-project/cockpit/pull/16091#issuecomment-894953421)). We also submitted fix into patternfly in https://github.com/patternfly/patternfly-react/commit/6757b8e46f14987f3680a2d6c3614bab938e2065

It was released in `@patternfly/react-core@4.149.0` but it is still only a prerelease, see [here](https://www.npmjs.com/package/@patternfly/react-core). Hopefully in couple of days it should be stable and we can update this npm module as well.
