### ISSUE TITLE
Missing BTRFS filesystem type in Format type dropdown

### ISSUE THREAD

**Issue by MurzNN** [cockpit-project/cockpit#16245]
Cockpit version: 248-1~ubuntu20.04.1
OS: Ubuntu 20.04
Page: Storage

Linux system has support for btrfs filesystem in mkfs, but in Cockpit "Format" dialog this option is absent.

**Comment by marusak** [comment]
Duplicate of https://github.com/cockpit-project/cockpit/issues/4796
