### ISSUE TITLE
$PATH is sometimes "(null)". 

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#1624]
This code in cockpit-services.js

```
cockpit.spawn([ "which", "gear" ], { host: me.address })
```

produces this message in the journal

```
which: no gear in ((null))
```

This means that $PATH was lost somewhere.

**Comment by stefwalter** [comment]
Note for whoever picks this up. Adding debug statements at or around the relevent code in ```src/common/cockpitpipe.c``` is a good place to start debugging this.
