### ISSUE TITLE
Add support for Server Roles

### ISSUE THREAD

**Issue by sgallagher** [cockpit-project/cockpit#1625]
The [rolekit](https://fedorahosted.org/rolekit) project provides a mechanism for deploying complete server software solutions to a particular machine. Cockpit should provide a user interface for performing these deployments to ease system management setup tasks.

**Comment by andreasn** [comment]
![Image of Yaktocat](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/roles/roles.png)

**Comment by stefwalter** [comment]
@andreasn the server summary page is already quite noisy, and doesn't wrap that well. Minor suggestion: put the list of roles at the end of the page (float clear both sides) at least for now.

**Comment by stefwalter** [comment]
Trello card: https://trello.com/c/7CZqL9AQ/54-rolekit-integration-for-domain-controller

**Comment by martinpitt** [comment]
[He's dead, Jim](https://github.com/libre-server/rolekit)
