### ISSUE TITLE
Add support for the Domain Controller Server Role

### ISSUE THREAD

**Issue by sgallagher** [cockpit-project/cockpit#1626]
The [rolekit](https://fedorahosted.org/rolekit) project provides support for a Domain Controller server role. This role installs and configures the FreeIPA Linux domain controller and is a useful feature for any new network of systems. Cockpit should provide UI to set it up.

**Comment by andreasn** [comment]
some specific details for IPA in https://github.com/cockpit-project/cockpit/issues/1625#issuecomment-69193958

**Comment by stefwalter** [comment]
Trello card: https://trello.com/c/7CZqL9AQ/54-rolekit-integration-for-domain-controller

**Comment by akilawickey** [comment]
According to https://trello.com/c/7CZqL9AQ/54-rolekit-integration-for-domain-controller their is six steps to the user for create FreeIPA Linux domain controller.  Can we make it so simple?. i mean without opening many windows boxes can we reduce the windows opening in the process.

**Comment by stefwalter** [comment]
I think they're all drawings of the same window. The modal dialog changes state as the action occur.

But I agree the design may need revisiting. @andreasn the actual process takes about 10 minutes, are we sure it should have it in a modal?

**Comment by andreasn** [comment]
Yeah, it might be possible to do it inline on a page and give a toast notification when it's done.
https://www.patternfly.org/patterns/toast-notifications/

**Comment by akilawickey** [comment]
when domain-creation process takes a few minutes to run and there's no notification through the D-BUS API of where it is in the process. So to show user that progress is still happening we have to show  the progress graphically to the user... i mean for a normal user not a programmer

**Comment by martinpitt** [comment]
The [FreeIPA installer](http://localhost:9090/apps#/org.cockpit-project.app-freeipa) has been available as a Cockpit Application for a while, which solves this more elegantly and generically than a built-in Cockpit feature.

**Comment by sgallagher** [comment]
@martinpitt Are you sure about the FreeIPA Installer? It certainly doesn't seem to be appearing on my F29 system. How would I get that?

**Comment by martinpitt** [comment]
It's in the "Applications" menu:

![apps](https://user-images.githubusercontent.com/200109/51115990-12766780-180a-11e9-8793-ba946aef091a.png)

If you don't have that, maybe you are missing cockpit-packagekit?

**Comment by sgallagher** [comment]
No, I have the Applications page, but I have different ones available: 

![cockpit-apps](https://user-images.githubusercontent.com/739555/51116180-610b0e00-17d8-11e9-810a-6a2fd04a9e91.png)

I'm using Cockpit 184 on Fedora 29 x86_64

**Comment by sgallagher** [comment]
I tried hitting the refresh button, which I only noticed after your reply. It's pretty subtle. However, it did not show me any new Applications.

Is there some other package that should be installed?
