### ISSUE TITLE
Enable different privilege escalation methods 

### ISSUE THREAD

**Issue by madleit** [cockpit-project/cockpit#16336]
Page:  Security

Hello, I am planning to use cockpit to monitor my server however we use pbrun as privilege escalation method. It would be great if I would be able to choose or setup pbrun to work along with cockpit.

**Comment by martinpitt** [comment]
This was implemented in [version 275](https://cockpit-project.org/blog/cockpit-275.html). A [manifest](https://cockpit-project.org/guide/latest/packages.html#package-bridges) can declare a "privileged" bridge like https://github.com/cockpit-project/cockpit/blob/main/pkg/shell/manifest.json 

See tests in https://github.com/cockpit-project/cockpit/blob/main/test/verify/check-superuser#L238 for more examples.
