### ISSUE TITLE
Reduce excess padding around cards in space-constrained layouts to optimize for content

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16353]
Goal: remove excess padding that only gets in the way of actual content on space constrained layouts, for all pages.

---

The Overview page has a one-off that reduces card padding in mobile mode. I am pretty sure we handled this across pages at one point. Perhaps pages have been rewritten since and this feature fell away? (Overview was the first page using PF4, IIRC, so that's probably why it's local, and why I seem to remember other (pre-PF4) pages having this feature too.)

Here's what I'm talking about... it only takes effect in super-small sizes, to shave off a little excess padding... compare:

![Screen Shot 2021-09-15 at 10 48 12](https://user-images.githubusercontent.com/10246/133402023-08e72257-d8b8-443f-b0cc-65564a9fde2e.png)
![Screen Shot 2021-09-15 at 10 49 19](https://user-images.githubusercontent.com/10246/133402109-661be782-6e4a-40eb-8739-bd153c9d58c7.png)

- This could be done in a more global, generic manner.
- It could drop the extra padding for all mobile, not just extreme sizes. (To be determined, but I think it might help.)
- We could consider it either as an opt-in for Cockpit or as a PF4 override. :shrug: 

Dropping the padding and stretching cards to the width for overview is @ https://github.com/cockpit-project/cockpit/blob/main/pkg/systemd/overview.scss#L196-L218

**Comment by KKoukiou** [comment]
This should be done the PF4 way. https://github.com/cockpit-project/cockpit/pull/16355

**Comment by garrett** [comment]
@KKoukiou and I hashed it out in #16355 and I suggested some opt-in CSS to go into `page.scss` in https://github.com/cockpit-project/cockpit/pull/16355/files#r710164707, and then we just add the class to the various pages where we want to drop the edges.

I can do this pretty easily, so I'll assign it to myself (and eventually get to it).
