### ISSUE TITLE
bridge: CockpitDBusCache might react on foreign signals

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#16387]
See #16381 for many details.

A CockpitDBusCache should only react to PropertiesChanged, InterfacesAdded, and InterfacesRemoved signals from the name that it is watching. However, when the name is a well-known one (like "org.freedesktop.Udisks2") and not a unique name (like ":1.26"), glib will not filter out signals from foreign sources.

CockpitDBusCache needs to track the owner of the name that it is watching, and filter signals accordingly.

This happens in a hackish way for the default name of a CockpitDBusJson instance, but not for caches for non-default names.

Thus, we should move the name tracking into CockpitDBusCache, so that each cache does its own tracking and can implement its own signal filtering.

Caches for non-default names are super rare, I think, and this only matters if a page connects to multiple D-Bus services and even then the worst that can happen is a entry in the journal. So this is not as bad as it sounds, and mostly interesting to reduce flakiness of tests.

**Comment by martinpitt** [comment]
@mvollmer Do you still think it's worth pursuing that? What does the pybridge do here, it dropped a bunch of overhead/concepts of the C bridge?

**Comment by mvollmer** [comment]
The pybridge doesn't handle non-default names, and we might never implement it. I think we can close this issue.
