### ISSUE TITLE
Cockpit doesn't work with Cloudflare Argo Tunneling

### ISSUE THREAD

**Issue by CharlesGodwin** [cockpit-project/cockpit#16392]
I don't know if this is a bug on enhancement request.

I'm trying to put Cockpit behind a Cloudflare Tunnel. It sort of works as the login page appears, but then, after I enter my credentials, I get an empty page.

I have set config.yml of cloudflared I use 
<pre>
- hostname: dashboard.mydomain.com
  service: http://localhost:9090</pre>

and then I invoke it using `https://dashboard.mydomain.com`

This technique is working on other non-standard port tools such as grafana.

Can this be done? what am I doing wrong?

Thanks

**Comment by martinpitt** [comment]
What is your OS and cockpit version? (Please use the template to file bugs) We recently (version 251) fixed a bug with similar symptoms in commit 16c3c16d37a6ed.

**Comment by CharlesGodwin** [comment]
I'll open this as a bug report.
