### ISSUE TITLE
Kernel update being stuck

### ISSUE THREAD

**Issue by TwilyHoney** [cockpit-project/cockpit#16405]
Cockpit version: 252
OS: Ubuntu 20.04.3 LTS
Page: Software Updates

Attempting to update kernel from 86 to 88, the progress stuck at 98%. Upon checking on SSH, login wall says there's 9 updates, and the usual _system restart required_ message.

Login and go to software updates page, check for updates, and try to update the kernel

For logs, unfortunately there's nothing useful, but i found this line:
`packagekitd[2915563]: no statusfd changes/content updates in terminal for 120 seconds`

Steps to reproduce

1. Login to cockpit
2. Check for updates, make sure kernel is included
3. Try install the updates

Screenshot:
![hello](https://user-images.githubusercontent.com/75704411/134990606-64c528d6-c6b0-47c6-b503-4e692a5bc6e5.png)

Then I'm disconnected. Upon reloading, i got this in browser console:
`Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """" updates.js:2:1160151`
 
Further checking, the upgrade is successful, but again, cockpit for some reason didn't tell about it.

**Comment by martinpitt** [comment]
The tracer error message is unrelated and harmless. We should quiece it, but it has nothing to do with the PackageKit update. So as packagekitd found out by itself, something between packagekit and apt got stuck. That's a bit hard to diagnose after the fact, but could you please save and attach the journal from around that time? Something like

    sudo journalctl --since '7 hours ago' --until '6 hours ago'

**Comment by jelly** [comment]
Closing this issue as there was no response, if this issue still persists please comment and we'll re-open the issue.
