### ISSUE TITLE
Cockpit unable to start

### ISSUE THREAD

**Issue by carbon-cell** [cockpit-project/cockpit#16433]
Cockpit version: 215-1
OS: Ubuntu Ubuntu 20.04.3 LTS
Page: 

Unable to start cockpit. It seems that when I download cockpit it's on an old version. Not sure why. It's on version 215-1 instead of 252.

Steps to reproduce

1. sudo apt-get install cockpit
2. systemctl enable cockpit
3. systemctl start cockpit
4. systemctl status cockpit
● cockpit.service - Cockpit Web Service
     Loaded: loaded (/lib/systemd/system/cockpit.service; static; vendor preset>
     Active: failed (Result: exit-code) since Wed 2021-10-06 05:33:14 EDT; 7s a>
TriggeredBy: ● cockpit.socket
       Docs: man:cockpit-ws(8)
    Process: 8074 ExecStartPre=/usr/sbin/remotectl certificate --ensure --user=>
    Process: 8075 ExecStart=/usr/lib/cockpit/cockpit-tls (code=exited, status=2>
   Main PID: 8075 (code=exited, status=203/EXEC)
 
Oct 06 05:33:14 unsung systemd[1]: Starting Cockpit Web Service...
Oct 06 05:33:14 unsung systemd[1]: Started Cockpit Web Service.
Oct 06 05:33:14 unsung systemd[8075]: cockpit.service: Failed to execute comman>
Oct 06 05:33:14 unsung systemd[8075]: cockpit.service: Failed at step EXEC spaw>
Oct 06 05:33:14 unsung systemd[1]: cockpit.service: Main process exited, code=e>
Oct 06 05:33:14 unsung systemd[1]: cockpit.service: Failed with result 'exit-co>
lines 1-15/15 (END)...skipping...
● cockpit.service - Cockpit Web Service
     Loaded: loaded (/lib/systemd/system/cockpit.service; static; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-10-06 05:33:14 EDT; 7s ago
TriggeredBy: ● cockpit.socket
       Docs: man:cockpit-ws(8)
    Process: 8074 ExecStartPre=/usr/sbin/remotectl certificate --ensure --user=root --group=cockpit-ws --selinux-type= (code=exited, status=0/SUCCESS)
    Process: 8075 ExecStart=/usr/lib/cockpit/cockpit-tls (code=exited, status=203/EXEC)
   Main PID: 8075 (code=exited, status=203/EXEC)

**Comment by carbon-cell** [comment]
I'll give it a try once I get the chance.

**Comment by marusak** [comment]
@carbon-cell any update on this?
