### ISSUE TITLE
metrics: Optimize for lower resolution laptop/desktop screens

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16435]
Two big issues:

1. The cards start to overflow horizontally
2. Historical metrics cannot be seen without scrolling

![Screenshot from 2021-10-06 17-13-20](https://user-images.githubusercontent.com/10246/136236998-39680a1a-245a-4164-b30b-ad93f5e4b18c.png)
(I've blanked out anything that might possibly be personally identifying.)

As this was via screen sharing, I don't know the actual screen resolution. But it looks like it might be around 73% of this image, which would be 1280 x 720.

Here's the same screenshot scaled 1:1 (click to view at size):

![1280x720](https://user-images.githubusercontent.com/10246/136239877-25b645a3-1877-4fc3-9c7e-1492991a1df6.png)

Usable document real estate is:

- 1280x578 for all of Cockpit, after removing the browser UI (tabs, nav, bookmarks) and the Windows task bar.
- 1026x514 for the usable page area, after removing the above, Chrome's scrollbars on Windows, Cockpit's header, Cockpit's navigation 

And I guess we need to make sure to test the following resolutions:

- 1366×768 (second most common resolution in 2021, according to some random website that was the first search hit)
- 1280x720 (seventh most common resolution from the same list)

Corporate environments would hopefully have higher resolution screens, but we can't just wave our hands at that, as a lot of people are still working from home in the pandemic and a lot will be working from home after the pandemic too.

**Comment by martinpitt** [comment]
@garrett: What we can do easily is to do an one-off run with those resolutions, and we'll get failed pixel tests (with new images) for these two resolutions. We can't easily do "all of cockpit", as one needs to define at which point they need to happen.

**Comment by garrett** [comment]
@martinpitt: That would be a good start. I guess combining that with manual testing and asking everyone to check these sizes (as we go forward) and file issues would be helpful.

**Comment by garrett** [comment]
You can add the tiny laptop resolution of 1280 x 578 (to simulate the reduction of Chrome UI, bookmarks, and Windows taskbar) in Firefox's mobile mode and add it as a preset:

![Screenshot from 2021-10-12 14-56-38](https://user-images.githubusercontent.com/10246/136960434-ec7363f2-b458-4c4a-8ea1-62e357488336.png)

Here's what the metrics page looks like:

![Screenshot from 2021-10-12 14-54-47](https://user-images.githubusercontent.com/10246/136960135-7e8cbd29-2a62-4319-881e-c2e1edb8ed24.png)

Firefox mobile mode is control-shift-m; adding a custom size is an option on the dropdown at the top left (right before resolutions) and it'll use whatever you're currently using as a base, so you can set the size and then save it.

**Comment by martinpitt** [comment]
We got a lot of fixes in that area already, so this is stale. Also, the scope of this ticket is now way too wide, it's too hard to define "done". Let's rather file small issues for concrete pages/situations.
