### ISSUE TITLE
metrics: When current historical metrics do not load, _all_ older metrics load and overwhelm the browser

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16462]
When I load the metrics page on my work laptop, it fails to load the historical metrics and then auto-loads all the historical metrics it can find.

This makes the browser (Firefox specifically) unresponsive and makes debugging in the developer tools difficult to impossible.

The metrics page should always limit the number of data points by default, even if it goes into a fallback mode.

**Comment by garrett** [comment]
This is basically blocking me from working on https://github.com/cockpit-project/cockpit/issues/16435 at the moment. (I've tried. It's super frustrating and extremely hard to do anything while I wait.)

**Comment by marusak** [comment]
> it fails to load the historical metrics and then auto-loads all the historical metrics it can find

How does it fail? And what triggers it to load all data?

> The metrics page should always limit the number of data points by default

We load only 12h of data. https://github.com/cockpit-project/cockpit/blob/main/pkg/metrics/metrics.jsx#L62 When I was hacking on this page I changed this to 2h to make the page even smaller.

> even if it goes into a fallback mode.

I don't even know there is a fallback mode :open_mouth: Let me check the code for that.

> This is basically blocking me from working on #16435 at the moment

Please just use testing VM, we have there pre-recorded archives.

**Comment by garrett** [comment]
> Aha! This gives it away :) I assume you saw first

Yes! That's what I saw whenever I had the issue. And then it'd load everything. Thanks for finding and fixing the bug!

> Is your collector running the whole time? Or is this machine running the whole time? Possibly haven't you changed hostname during the day?

It's on my laptop, so it's not running all the time, just when my laptop is. But I'm not sure why it seems to have gaps even when it's running. Cockpit will not show data even when the command line tools do (but it's the streaming data, not saved).

I haven't changed the hostname in quite some time.
