### ISSUE TITLE
Missing 'class=active' for Journal Page

### ISSUE THREAD

**Issue by Aayush-Kasurde** [cockpit-project/cockpit#1646]
There is missing highlighting for Journal page as shown in figure

![journal](https://cloud.githubusercontent.com/assets/7703416/5724324/cc240f04-9b70-11e4-89c9-4aee44bb8c04.png)

I am using latest Cockpit version with Fedora 20

**Comment by stefwalter** [comment]
Can confirm. Same thing happens here.
