### ISSUE TITLE
Help with websocket

### ISSUE THREAD

**Issue by mvala** [cockpit-project/cockpit#16489]
Cockpit version: 251
OS: Centos
Page: Own page

I would like to make websocket connection via cockpit.channel. I would like to do following
```
var WebSocketClient = require('websocket').client;
var client = new WebSocketClient();
client.on('connect', function(connection) {
    console.log('WebSocket Client Connected');
    connection.on('error', function(error) {
        console.log("Connection Error: " + error.toString());
    });
    connection.on('close', function() {
        console.log('Connection Closed');
    });
    connection.on('message', function(message) {
        console.log(message);
    });
});
client.connect('ws://localhost:8442/','');
```
Can you give me hint or example for this? Thanks

**Comment by martinpitt** [comment]
As a first step you'd need to allow this in the Content-Security-Policy in your manifest.json. Add something like

    "content-security-policy": "default-src 'self'; img-src 'self' ws://localhost:8442"

I don't know if that's already sufficient, but that at least takes care of the C-S-P blocking?
