### ISSUE TITLE
command to install additional Applications??

### ISSUE THREAD

**Issue by grand-lotus-iroh** [cockpit-project/cockpit#16484]
Cockpit version: 215
OS: Ubuntu 20.04 x64

When I goto the /apps page I only see Storage but I would very much like to check out Software Updates (PackageKit) and Network. May you please advise me on command I need to type?

How do I install application? I can't for the love of god find any documentation. I have a brand new fresh installation of Ubuntu on a VPS and I connected VIA PuTTY and typed in `sudo apt-get install cockpit` and access the browser no problem.

* https://cockpit-project.org/guide/latest/ (nothing when I CTRL + F)

**Comment by martinpitt** [comment]
> I would very much like to check out Software Updates (PackageKit) and Network

You already have Software Updates, as the /apps page is shipped by the same Ubuntu package (cockpit-packagekit) as Software Updates.

Network does not have an "Applications" entry, you need to install this manually: `sudo apt install cockpit-networkmanager`.
