### ISSUE TITLE
storage: Graphs aren't visible under (unknown) certain conditions

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16493]
From the UX study on the metrics page

Pariticpant 5 @ 30 minutes (and elsewhere) visited the Storage page and the graphs were not visible:

![Screenshot from 2021-10-19 14-08-22_ L3](https://user-images.githubusercontent.com/10246/137906501-d27f8139-1e95-49da-84d7-cc1526c2485c.png)

Screen resolution (not sure if relevant): 1280x720.

I'm not sure why the graphs were not showing. I don't have more details. Sorry. Other participants also encountered this issue.

**Comment by garrett** [comment]
I think we need to know more about this, probably from @martinpitt, as he set up the VMs that were used from the test. We could try to see if it happens again if a VM currently exists or if he could set up a test VM for the UX study but for us instead.

We could also re-watch the videos for any hints, but @martinpitt and the VM setup would be our best bet.

Otherwise, I don't know how why this is happening.

Of possibly somewhat related note: The software updates page also did not work due to some packagekit issue. Therefore, the VMs were probably broken in at least a few ways. It might be a way which our users could hit, or it could be something else.

I'm going to assign this to @martinpitt right now, as we need more information.

**Comment by martinpitt** [comment]
I spun up a new EC2 instance, and this reproduces just fine:

![image](https://user-images.githubusercontent.com/200109/145778582-0f3f3b22-6d1d-4d89-9420-2e436bc99503.png)

i.e. /dev/xvda is indeed part of "other devices".

I confirmed it with current main. The [storage overview](https://github.com/cockpit-project/cockpit/blob/main/pkg/storaged/overview.jsx#L46) unconditionally renders `<StoragePlots>`, and [StoragePlots](https://github.com/cockpit-project/cockpit/blob/main/pkg/storaged/plot.jsx#L77) unconditionally renders the two `<SvgPlot>`s, but that one returns null if `(!chart_data || chart_data.length == 0)`.

On my laptop, I see in `this.plot_state` that plots.read.data.0 has `name: "nvme0n1"` and lots of data:. But on the EC2 instance, there is no `name:` at all, and data: is an empty array. This is still the case after removing pcp and cockpit-pcp on the EC2 instance (as my laptop does not have them either).

On the laptop, in `update_plot_state()` I get
```
path /org/freedesktop/UDisks2/drives/WDC_PC_SN730_SDBQNTY_256G_1001_194305806501
block 
Object { Device: Getter & Setter, PreferredDevice: Getter & Setter, Symlinks: Getter & Setter, DeviceNumber: Getter & Setter, Id: Getter & Setter, Size: Getter & Setter, ReadOnly: Getter & Setter, Drive: Getter & Setter, MDRaid: Getter & Setter, MDRaidMember: Getter & Setter, … }
 dev nvme0n1
```

while on EC2, `client.drives` is empty.

Locally, I have
```
/org/freedesktop/UDisks2/block_devices/nvme0n1:
  org.freedesktop.UDisks2.Block:
    Configuration:              []
    CryptoBackingDevice:        '/'
    Device:                     /dev/nvme0n1
    DeviceNumber:               66304
    Drive:                      '/org/freedesktop/UDisks2/drives/WDC_PC_SN730_SDBQNTY_256G_1001_194305806501'

/org/freedesktop/UDisks2/drives/WDC_PC_SN730_SDBQNTY_256G_1001_194305806501:
  org.freedesktop.UDisks2.Drive:
```

while on EC2 there is not a single `.Drive`  object, and the root partition is part of the '/' drive:
```
/org/freedesktop/UDisks2/block_devices/xvda:
  org.freedesktop.UDisks2.Block:
    Configuration:              []
    CryptoBackingDevice:        '/'
    Device:                     /dev/xvda
    DeviceNumber:               51712
    Drive:                      '/'
```

This can be fixed easily:
```
--- pkg/storaged/plot.jsx
+++ pkg/storaged/plot.jsx
@@ -58,8 +58,8 @@ const instances_write_metric = {
 
 export function update_plot_state(ps, client) {
     const devs = [];
-    for (const p in client.drives) {
-        const block = client.drives_block[p];
+    for (const b in client.blocks) {
+        const block = client.blocks[b];
         const dev = block && decode_filename(block.Device).replace(/^\/dev\//, "");
         if (dev)
             devs.push(dev);
```

![image](https://user-images.githubusercontent.com/200109/145785613-beaf4fa9-cf0a-43ca-9e52-5598792951da.png)

**Comment by garrett** [comment]
> This can be fixed easily

:partying_face:

**Comment by mvollmer** [comment]
> This can be fixed easily:
> 
> ```diff
> --- pkg/storaged/plot.jsx
> +++ pkg/storaged/plot.jsx
> @@ -58,8 +58,8 @@ const instances_write_metric = {
>  
>  export function update_plot_state(ps, client) {
>      const devs = [];
> -    for (const p in client.drives) {
> -        const block = client.drives_block[p];
> +    for (const b in client.blocks) {
> +        const block = client.blocks[b];

Wouldn't that put absolutely all block devices into the plot?  Partitions, LUKS containers, logical volumes, the lot?  I would agree that we should include "Drives" and "Other devices", but not all block devices.
