### ISSUE TITLE
services: Filter bar collapses down to an icon too early and does not look clickable

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16494]
When the desktop/laptop screen is a lower resolution (such as 1280x720, which is extremely common, even in 2021) the services page hides the filter bar and replaces it with a non-obvious filter icon.

![Screenshot from 2021-10-19 14-13-38](https://user-images.githubusercontent.com/10246/137907176-5314cbb9-ef5c-472e-833d-4363decf2366.png)

(As found on the UX study of the Metrics page, as several participants were using low-res screens at 1280x720.) 

We should:

1. Change the collapse to be mobile-device only.
2. Add a label to the filter icon.
3. Make the filter icon + label look clickable. (Blue and/or secondary button styled)

**Comment by marusak** [comment]
> Add a label to the filter icon.

https://github.com/patternfly/patternfly-react/issues/6140

We have workaround for this on logs page. (`git grep toggleIcon`)
