### ISSUE TITLE
metrics: History view: Embedded logs aren't aligned with the time

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16492]
As seen in the historical view in the UX Study: Metrics can say spike events happened at 5:35, 5:36, and 5:37, but when the logs are expanded, they say 5:06.

This prevented people from completing the last task successfully in an easier manner.

From the screen of participant 5 around 30 minutes in, where it was specifically called out:

![Screenshot from 2021-10-19 14-03-33_ L3](https://user-images.githubusercontent.com/10246/137905824-1b45fb4d-4308-462a-b885-c071cab24f02.png)

**Comment by KKoukiou** [comment]
I can not see this on my system, I have sometimes 1 minutes divergence. Can someone else reproduce it deterministically?

**Comment by garrett** [comment]
We may need @martinpitt's help to recreate this. Perhaps it shows up as an issue on the testing VM?

Wild speculation: I do see that this is off by half an hour. Perhaps the person being tested was in a timezone that offsets by a half hour instead of a whole hour?

Here are the locations which don't use whole hours for timezone offsets:

![special-tz-map6](https://user-images.githubusercontent.com/10246/140284389-2f8118e3-d8e5-489e-88ee-e8545ee95842.png)

https://www.timeanddate.com/time/time-zones-interesting.html

The list includes:

- All of India and Sri Lanka (same timezone, IST)
- Some of Australia
- Islands of New Zealand
- A small part of Canada
- Afghanistan
- Iran
- Myanmar
- Nepal
- French Polynesia
- Venezuela used to (which is why it's on the map?)
- North Korea also used to (but it's not a highlight on the map...)

Most of these are off by half an hour, but a few are off by 45 minutes.

**Comment by martinpitt** [comment]
Initially I thought this was becauee the journal logs use the server's own time zone/time, while the header uses the browser's time zone/formatting. But that's not the case, they both use browser time.

I booted a rhel 8.6 VM, did `timedatectl set-timezone Asia/Tehran` and rebooted:
```
# date
Wed Feb  2 10:38:43 +0330 2022
```

This corresponds to my local time (Europe/Berlin) of 08:08. I then triggered a CPU event:

![image](https://user-images.githubusercontent.com/200109/152109709-f0b9eb07-ad1b-44fc-9f19-9e7eefcb4fa4.png)

So this is not obvious to reproduce, and needs some more prodding :cry:

**Comment by garrett** [comment]
@martinpitt: Have you tried to see what happens when your browser's system is set to the Indian timezone (IST) with your server set in something else?

I can't check because logs still don't work on my development machine (or on my server, which is using Fedora packages...). I see something like this still:

![Screenshot from 2022-02-02 09-51-20](https://user-images.githubusercontent.com/10246/152122276-1a6d9d15-5ea6-4ca0-b3ea-207942452221.png)

**Comment by marusak** [comment]
Cool, I can reproduce this.

![Screenshot from 2022-02-07 15-36-18](https://user-images.githubusercontent.com/12330670/152767628-684d41cc-e03f-4c31-8b96-454939b5d138.png)

I set my computer time zone to India (see time on top of the screen, I took it around 11:06 of my local time) and then inspected my other computer. I am taking a look at this.
