### ISSUE TITLE
"Internal error" when trying to add a new Host

### ISSUE THREAD

**Issue by 63427083** [cockpit-project/cockpit#16504]
Cockpit version: 238.2
OS: Centos8
Page: Any

journalctl -u cockpit
  Oct 21 05:42:23 dienste systemd[1]: Starting Cockpit Web Service...
  Oct 21 05:42:23 dienste systemd[1]: Started Cockpit Web Service.

journalctl -u cockpit-bridge
-- Logs begin at Thu 2021-10-21 04:16:42 CEST, end at Thu 2021-10-21 05:53:44 CEST. --
-- No entries --
journalctl -u cockpit-ws
-- Logs begin at Thu 2021-10-21 04:16:42 CEST, end at Thu 2021-10-21 05:53:52 CEST. --
-- No entries --
journalctl -u cockpit-system
-- Logs begin at Thu 2021-10-21 04:16:42 CEST, end at Thu 2021-10-21 05:54:19 CEST. --
-- No entries --

Steps to reproduce

1. Cick "Add new Host" button in the host menu.
2. Enter Hostname, User and select color.
3. Press "Add"

After the above steps i just get a red warning "Internal Error". The web console does the same and spouts out 
"Internal error    index.js:64:61448"
The journalctls i copied above, seem kinda unhelpful on this one as well.
I can otherwise ssh freely to the target machine.

As i'm kinda lost here, i'd appreciate any hint on where to actually look. Feel free to ask for more logs if necessary.

**Comment by martinpitt** [comment]
I'm afraid you'll need a full `journalctl`, as the interesting things about the session aren't happening inside cockpit.service, but in PAM and the user session.

There's nothing actionable here, I'm afraid, and this is quite stale. I'm closing this now. But if it still happens wit current versions, please respond here and I'm happy to reopen. Thanks!
