### ISSUE TITLE
Question / Support - Moving to a Domain from IP:PORT

### ISSUE THREAD

**Issue by EpsilonCommunity** [cockpit-project/cockpit#16529]
Hi,

Looked on the wiki and the documentation with no clear path to enable change from local IP to domain.

Any help would be greatly appreciated or linking to an overlooked page.

**Comment by martinpitt** [comment]
What do you mean with this exactly? IP/Domain is a function of your DNS, not cockpit. Can you please clarify your question? Thanks!
