### ISSUE TITLE
Add mdadm logs

### ISSUE THREAD

**Issue by ne20002** [cockpit-project/cockpit#16569]
Page: storage

Today is the first sunday of November and mdadm started checking the raids ... but no logs appeared. Looking on the storage tab logs and on the all logs tab the filter ist set to
priority:debug _SYSTEMD_UNIT=storaged.service,udisks2.service,dm-event.service,smartd.service,multipathd.service 

I suggest to add mdadm to the storage logs.

**Comment by jelly** [comment]
With mdadm, do you mean the mdmonitor service? In Debian mdadm.service is a symlink to /dev/null, and Fedora does not provide a mdadm.service but mdmonitor.service instead.

**Comment by ne20002** [comment]
Maybe it's mdmonitor. As far as I see there is no logs of raid monitoring ... on the first sunday every month there is a check of the raid.. but there is nothing in the log (or I haven' tfound it).

**Comment by martinpitt** [comment]
Sorry for the late reply.. Can you please give us the full (`journalctl -o verbose`) output of the RAID check?
