### ISSUE TITLE
tuned: Performance profile list should be scrollable, not the modal itself

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16562]
It looks like this now:

![image](https://user-images.githubusercontent.com/10246/140325262-98590cf2-228a-449f-944e-04d246f68c9a.png)

But the list itself should be scrollable, not the modal, similar to how we had it before #16516 landed:

![image](https://user-images.githubusercontent.com/10246/140325394-716aedd8-0226-492b-9ea0-6f52849bc0b9.png)

**Comment by KKoukiou** [comment]
Fixed with:
``` bash
commit 7d4383201e4f8f28ef399ee4715788ba277f2abe
Author: Garrett LeSage <garrett@redhat.com>
Date:   Thu Mar 24 17:43:51 2022 +0100

    overview: Stretch menu selector to modal bod
```
