### ISSUE TITLE
applications: Progress bar goes backwards

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16564]
When checking for applications, progress bars bounce around. They should only move forwards.

![tempsnip](https://user-images.githubusercontent.com/2385260/138095674-df27891e-4559-4c9a-a6d0-2023bf4a0004.png)

_Originally posted by @csjjpm in https://github.com/cockpit-project/cockpit/issues/16484#issuecomment-947632500_

**Comment by garrett** [comment]
PatternFly has recently added a new demo on how to force progress bars to only have increasing progress:

https://www.patternfly.org/v4/components/progress/react-demos#with-only-increasing-progress

Code:

```jsx
import React from 'react';
import { Progress, Button, Stack, StackItem } from '@patternfly/react-core';

ProgressStepperDemo = () => {
  const [currentValue, setCurrentValue] = React.useState(0);

  const onProgressUpdate = nextValue => {
    if (nextValue > currentValue) {
      setCurrentValue(nextValue);
    }
  };

  return (
    <Stack>
      <StackItem>
        <Button onClick={() => onProgressUpdate(currentValue - 10)} isDisabled={currentValue === 0}>
          Decrease value
        </Button>{' '}
        <Button onClick={() => onProgressUpdate(currentValue + 10)} isDisabled={currentValue === 100}>
          Increase value
        </Button>
        <br />
        <br />
      </StackItem>
      <StackItem>
        <div className="pf-screen-reader" aria-live="polite">
          {`Progress value is ${currentValue}%.`}
        </div>
        <Progress value={currentValue} title="Title" />
      </StackItem>
    </Stack>
  );
};
```

Depending on the bouncing, we might need to filter the percentages to smooth it out, instead of just forcing it forward.

I'm totally guessing here and am probably wrong: If the results we're getting back are for multiple sources, then they should each be considered in a complete total. If there are separate locations that are being checked at one time in the backend, it could be that the results are thrown together in a not-thread-safe manner in our progress representation.

**Comment by KKoukiou** [comment]
This bug has been fixed upstream a long time now, with:
```
commit 2064a4f78ac2191d5e9fa8f9705b27535979a99e
Author: Katerina Koukiou <kkoukiou@redhat.com>
Date:   Wed Mar 24 14:20:47 2021 +0100

    lib: packagekit: update progress bars by using the PK backend provided value
```

The reporter which has this issue in the link above has a really old version of cockpit (215), which does not contain this fix (available first in 241)

**Comment by garrett** [comment]
@KKoukiou: That commit is for PackageKit, not for the Applications page.

**Comment by garrett** [comment]
The reporter did have a very old version of Cockpit, but upgraded, and still has this issue: https://github.com/cockpit-project/cockpit/issues/16484#issuecomment-949221307

**Comment by garrett** [comment]
I've reproduced this on Ubuntu 20.04.3 LTS with the Cockpit backport, meaning Cockpit 252. It's probably the same on other systems that use apt (all supported versions of Debian, Ubuntu, and their variants).
