### ISSUE TITLE
applications: Modal has a close button that isn't styled like a button

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16579]
I built a Debian Stable VM, but haven't updated the images in quite some time. When trying to refresh the applications, it triggered an error.

_This issue isn't about the error._

This issue is about the link-styled button. The close should be a secondary action button, not styled like a link.

Here's a screenshot with the context:

![Screenshot 2021-11-09 at 11-57-40 Applications - admin debian](https://user-images.githubusercontent.com/10246/140912215-4c306817-d21e-49a1-8484-accb3a6f5b45.png)

I would fix this myself, but on a quick debugging run, I found the ID isn't useful to find in the codebase, nor was there anything really specific to search for. So it's not obvious where this code lives, so I can't quickly make a patch and send it up.

This fix should be easy though; it's just a matter of changing the style of the button from a link-styled one to a secondary.

(The actual error is one our users should hopefully never hit. But error dialogs like this might still be encountered via other reasons.)

This dialog is possibly not Applications-page related, but somewhere in our PackageKit handling. Meanwhile, I'm not sure of that, and it happens on Applications, so I'm adding the applications page label.

**Comment by KKoukiou** [comment]
This is the same in network page, storage page and users page for error modals. Let's fix it in all of these within this PR.
