### ISSUE TITLE
Document service.js library

### ISSUE THREAD

**Issue by gbraad** [cockpit-project/cockpit#16577]
It would be nice if a `systemd` interaction library exists, instead of having to spawn calls to `systemctl`.

**Comment by martinpitt** [comment]
What exactly do you want to do?

We have a [service.js](https://github.com/cockpit-project/cockpit/blob/main/pkg/lib/service.js) library, which wraps a unit, has methods for enable/disable/start/stop, and gives you events for state changes.

For rarer actions it's usually also quite straightforward to just do a [D-Bus call](https://www.freedesktop.org/wiki/Software/systemd/dbus/).

**Comment by gbraad** [comment]
Enabling a unit for socket activation as that is what a plugin would rely on. 
Didn't find this in the documentation. Might this be missing?

**Comment by martinpitt** [comment]
Right, you want to use service.js then, which provides exactly that. Its documentation is in the header comment. We use it in plenty of places in cockpit, so there are many examples.

**Comment by gbraad** [comment]
OK. If I have some insights and time I might consider adding some documentation around this. Diving into code to find what works is not ideal for a newcomer to the project.

**Comment by garrett** [comment]
> If I have some insights and time I might consider adding some documentation around this.

Awesome!

> Diving into code to find what works is not ideal for a newcomer to the project.

Agreed.

**Comment by martinpitt** [comment]
This is stale, I assume @gbraad is not interested in this any more, and https://github.com/cockpit-project/cockpit/blob/main/pkg/lib/service.js actually has quite an extensive documentation at the top.

**Comment by gbraad** [comment]
Haven't had time to look into this, but you are right; documentation exists for developers.
