### ISSUE TITLE
intl: Starting day of week is not country specific

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16588]
The first day of the week is different in various places.

![first day of the week](https://user-images.githubusercontent.com/10246/140730729-0563345b-b0bf-452d-bde7-3274505a0fa0.png)
https://en.wikipedia.org/wiki/Week#/media/File:First_Day_of_Week_World_Map.svg

And either we're assuming English means US and have German incorrect, or we (or PF) hardcode the first day of the week as Sunday:

![Screenshot 2021-11-08 at 11-47-02 Overview - garrett Bolt](https://user-images.githubusercontent.com/10246/140730890-28df47e0-1566-4652-ae2a-a0641044e01a.png)

![Screenshot 2021-11-08 at 11-47-46 Überblick - garrett Bolt](https://user-images.githubusercontent.com/10246/140730884-45308589-be7a-4653-9b52-cdaa338f64bb.png)

PatternFly has a `weekStart` option. I guess we're not handling that with locales and/or not passing it to the PF widget:

Name | Type | Default | Description
-- | -- | -- | --
weekStart | 0 \| 1 \| 2 \| 3 \| 4 \| 5 \| 6 \| Weekday |   | Day of week that starts the week. 0 is Sunday, 6 is Saturday.

_Originally posted by @garrett in https://github.com/cockpit-project/cockpit/issues/13489#issuecomment-963073680_

**Comment by garrett** [comment]
#16587 is a partial fix for this. It makes the start day Monday in some cases, but doesn't fix:

- Friday as a start day
- Saturday as a start day
- English in Europe being Monday
- Spanish in the Americas being Sunday (in most cases)

**Comment by martinpitt** [comment]
Right, so far this is an "as good as possible" approximation with just having a language. For being more precise, we need the browser to tell us the country/region, but we don't expose this at the moment.

**Comment by martinpitt** [comment]
#16587 landed, which is the above "guess by language" approximation. Retitling this for the completely correct solution, which unfortunately is a huge pile of owork.

**Comment by garrett** [comment]
There's [Intl.Locale.prototype.weekInfo](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/weekInfo), but it isn't used anywhere and currently only seems to [exist as a proposal](https://tc39.es/proposal-intl-locale-info/#sec-week-info-of-locale).

There's `<input type="week">` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/week, which is supposed to show the week as intended, but only works in Chrome at the moment, but still shows me Sundays as the first day, even though my system is set to en_US w/ Ireland (English) for formats (so I get all the typical EU formats instead of US ones, except with a decimal point instead of a comma). This includes Monday as the first day, which works in my calendars... but Chrome doesn't respect it. The thought was: "What if we use this input, but hidden, set it to a date, and get the resulting week?" However, as the browser support isn't everywhere and it doesn't work quite as intended, it's not useful for us anyway.

Meanwhile, we could use a modified version of what I suggested in the PR, by running `Intl.DateTimeFormat().resolvedOptions().timeZone` (which returns "Europe/Berlin" here) and matching the first item (split by "/") to set the day. That would work for all of Europe, except for Portugal.

ISO 8601 defines Monday as the first day of the week, so everything else is kind of an exception.

Setting the first day is more a regional thing than a language thing. For example: I know a bunch of native Germans who use their computer in English, as German translations are sometimes bad, because they're programmers who use an EN-US-Intl keyboard (as it has more convenient keys), etc. And I'm sure there are others across the world too, especially those who use computers every day (admins and devs).

**Comment by martinpitt** [comment]
[Locale.weekinfo](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/weekInfo) is still not a thing, and #16587 fixed this sufficiently well.
