### ISSUE TITLE
Can not add SSH Key with passphrase

### ISSUE THREAD

**Issue by OSXGroupFL** [cockpit-project/cockpit#16585]
Cockpit version: 256
OS: Ubuntu 20.04
Page: Session > SSH Keys

SSH key is not saved when selected

<details>
<summary>Original incomplete log meta-data</summary>
Log Info:

PRIORITY | 4
-- | --
SYSLOG_FACILITY | 1
SYSLOG_IDENTIFIER | cockpit-session
SYSLOG_TIMESTAMP | Nov  9 11:49:13
_AUDIT_LOGINUID | 1000
_AUDIT_SESSION | 1776
_BOOT_ID | 59a07588a8c443f7978bb07cb7cfe2ee
_CAP_EFFECTIVE | 3fffffffff
_CMDLINE | /usr/lib/cockpit/cockpit-session localhost
_COMM | cockpit-session
_EXE | /usr/lib/cockpit/cockpit-session
_GID | 0
_HOSTNAME | atlanta
_MACHINE_ID | 96f6abc22a1646cea6036647f827d2a9
_PID | 3286177
_SELINUX_CONTEXT | unconfined
_SOURCE_REALTIME_TIMESTAMP | 1636476553570773
_SYSTEMD_CGROUP | /system.slice/system-cockpithttps.slice/cockpit-wsinstance-https@e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.service
_SYSTEMD_INVOCATION_ID | b2ce6201888246778d4834371aab3afa
_SYSTEMD_SLICE | system-cockpithttps.slice
_SYSTEMD_UNIT | cockpit-wsinstance-https@e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.service
_TRANSPORT | syslog
_UID | 0
__CURSOR | s=71346a33925a4850a70370e09b71c9db;i=b3f7f9;b=59a07588a8c443f7978bb07cb7cfe2ee;m=4d96a1f8c9d;t=5d05de3a8aa11;x=b292589e7232c4a3
__MONOTONIC_TIMESTAMP | 5331834866845
__REALTIME_TIMESTAMP | 1636476553570833
</details>

Steps to reproduce

1. Session > SSH keys
2.  path to key: /home/usr/.ssh/key_rsa
3. Click Add Key
4. box disappears and key is not added

![Screen Shot 2021-11-09 at 11 13 44 AM](https://user-images.githubusercontent.com/44268753/140962408-3ac00521-f8c1-4663-9109-3a784f3d4bb9.png)
![Screen Shot 2021-11-09 at 11 13 57 AM](https://user-images.githubusercontent.com/44268753/140962447-09cff44b-133c-4cd7-b407-02335d859d42.png)

**Comment by martinpitt** [comment]
Unfortunately your (meticulously formatted) log info contains all the (relatively uninteresting) meta-data, but not the message itself.  Can you please copy it here, with the normal format?

Maybe the key has some non-standard format which the SSH agent somehow does not recognize. Normally it auto-detects private keys in ~/.ssh/ automatically already, they don't need to be added manually. However, there ought to be a visible error message of course, like you get when the permissions are wrong.

 - Do you still know how you generated it?
 - Can you try to create a default format key with `ssh-keygen -f ~/.ssh/key_test` and see if it appears in the dialog? (That should happen automatically even while the dialog is open). Does it appear there, and can you unlock it?
 - Can you please show me the first lines of the file with the meta-data, up to and including to the `------ BEGIN ..` line? (I.e. *don't* copy anything which looks like gibberish and is the key material).

Thanks!

**Comment by OSXGroupFL** [comment]
Key Created on OS X using: ssh-keygen -t rsa

Just opened the dialog to check the test key and now the key I was trying to add is there with a blue check mark. 

Not sure what caused the delay in it being accepted and activated. I'm not seeing any further detail in the logs regarding when I tried to add the key yesterday and it had the error message I posted above.

**Comment by marusak** [comment]
Actually this does not work for me.
I do `ssh-keygen -f ~/key_test` and then try to add this location through UI and it does nothing. When I check browser console it shows:
```
Enter passphrase for /home/mmarusak/key_test: 

Bad passphrase, try again for /home/mmarusak/key_test: 
```

Checking the code I see that we don't pass any passphrase, so it tries to unlock it with password being `undefined`. This seems like broken UI or we only accepts keys without passphrases?

**Comment by marusak** [comment]
When I generate key without passphrase it works just fine. I think we should support also passphrased keys

**Comment by marusak** [comment]
If the key is not in `~/.ssh/` then the key does not have name at the UI breaks somewhat. This needs a bit more work. I have some fixes locally already.
