### ISSUE TITLE
Allow Cockpit to be installable as a web application

### ISSUE THREAD

**Issue by gbraad** [cockpit-project/cockpit#16601]
The cockpit can be made installable as an application when described with a `manifest.json`. More details here: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs

This allows the website to be hosted from Chrome (Chromium, Vivaldi, Firefox) but launched in a dedicated window from a desktop launcher.

Like on Windows
![image](https://user-images.githubusercontent.com/1894/141459062-c8c65655-f384-43b8-8ae2-e7998bb71c32.png)

Launching any of these applications allows the website to work in a dedicated Window.

![](https://pbs.twimg.com/media/FDwhxWsXMAomPy9?format=jpg&name=large)

**Comment by gbraad** [comment]
I'll create a PR for this later

**Comment by garrett** [comment]
We'll want to make sure there's a higher quality icon being used for the launcher. And we might want to change the title to highlight the machine first (in case people add more than one mahcine at a time, so launching and switching between them is more obvious), and say "Web Console" — at least for RHEL.

**Comment by gbraad** [comment]
The icon is currently set by cockpit based in the host os.
A fixed cockpit icon might be a possibility, though this hides the info about the host.
Launcher name is suggested by the page title, but free-form. So page titles are very important

**Comment by garrett** [comment]
> The icon is currently set by cockpit based in the host os.

The icon is unacceptable. Surely the various OSes we use have higher-res icons as well? We have higher-res ones on the login page. What would happen if we just reuse those as larger ones? We could use the size-optimized ones for 16x16 still.

(Also, that's not the current Fedora logo... is this from F34 or F35?)

**Comment by gbraad** [comment]
> The icon is unacceptable. 

:+1 agree, (no doubt about that!) I think this happens because cockpit references the favicon, as the same happens for a regular link or adding cockpit to your favorites/speed dial

>  is this from F34 or F35

F33, test system/workstation

**Comment by gbraad** [comment]
@garrett The manifest allows you to set a static image. Using a cockpit logo like you discussed here: https://github.com/cockpit-project/cockpit/pull/16596#issuecomment-969115010 It would hide 'some information' but the target, but sin the flatpak would also, perhaps better to be consistent? A more complex approach is to allow the backend to generate an image that overlay the target OS/favicon over the cockpit logo... though I see this as an improvement and also, not much on return for the effort put into it.

**Comment by garrett** [comment]
We generally don't use the word "Cockpit" within Cockpit itself, nor do we use the logo. We want Cockpit just to be a UI for the system — and for RHEL, we call it "Web Console".

The exception is the about dialog and the package names.

So it would be better to use the OS icon when available. We could still use a better app icon for Cockpit specifically when those are not available for whatever reason, of course.

I do see a higher res OS logo @
https://localhost:9090/cockpit/static/logo.png

For Fedora 35, it's this:

![image](https://user-images.githubusercontent.com/10246/141956086-393ea9ce-c631-4313-8999-69e793b9ff61.png)

It should be the same URL for all the distros and for Fedora < 35, it would be the old logo.

**Comment by gbraad** [comment]
I think it is best to create a new issue for this, as the current favorite icon comes from the fallback at https://localhost:9090/favicon.ico

The interface should ideally also reference:

```
    <link rel="shortcut icon" href="/cockpit/static/logo.png">
```

**Comment by gbraad** [comment]
Updated the system to F35, and this is the `favicon.ico` that gets added to shortcuts
![image](https://user-images.githubusercontent.com/1894/141994531-47f10a8c-edcb-4307-816a-45ebeee61aba.png)

**Comment by gbraad** [comment]
Have been testing this with another application I have, and found out: 64x64 and 144x144 are mandatory sizes for the icon. Without them, the manifest will not be installable. Also a theme color and a background color needs to be specified. The theme will be used to color the chrome of the browser window, while the background color is an override for when the body does not specify a color by stylesheet. It will also be used when opening the shortcut as an initial color while the page loads.

**Comment by gbraad** [comment]
> for RHEL, we call it "Web Console".

The `index.html` only calls the page itself by the `hostname` of the system. This might preferably be `Web Console (hostname)` instead in that case?

**Comment by garrett** [comment]
For the icons, I wonder if we can generate different sizes during compilations. It's not as ideal as a hand-crafted or SVG-based icons, but it would let us specify those exact sizes. I don't know if we have any tooling in use where we can rescale images (such as graphicsmagick / imagemagick or something similar).

@martinpitt could answe the app icon size issue and resizing... basically if we currently can resize or add some tooling to build different sizes in our build process.

**Comment by garrett** [comment]
Worst case, we could perhaps ship the icons for all our supported distros. But it would be best if we could just use what the OS already provides (if possible).

**Comment by garrett** [comment]
> The index.html only calls the page itself by `<title>hostname</title>` of the system. This might preferably be `<title>Web Console (hostname)</title>` instead in that case?

It's probably better to do something like Hostname: Web Console, as OSes can ellipsise the titles, and that's usually at the end of the string. If we put "Web Console" first, then all of them would be "Web Conso..." (or something to this effect). Starting with unique strings would help someone quickly and easily differentiate between their app icons, regardless of ellipsis.

**Comment by gbraad** [comment]
@garrett also notice that the favicon for F35 is transparent; the `f` isn't colored white as expected

**Comment by garrett** [comment]
@gbraad: Yeah, that can be a problem. We might need to ship some of the distro icons ourselves in some (or all?) cases.

**Comment by gbraad** [comment]
Doesn't sound like a maintenable scenario. I am curious where this favicon.ico is added, and therefore who made it.

**Comment by garrett** [comment]
We currently have to maintain the logos for the distros for the website @ https://cockpit-project.org/running.html#installation--setup. Maintaining icons isn't tough. Distros (and browsers, which we also have on the same page above) don't change branding that often.

Again, it's better if the OS itself provides this, but it doesn't always.

**Comment by martinpitt** [comment]
Stale, we don't have the capacity to work on this, and I'm quite sure that @gbraad isn't interested in this any more.

**Comment by gbraad** [comment]
I am interested but have the same time problem.
