### ISSUE TITLE
Login shows "Internal error in login process" when using howdy with camera disabled

### ISSUE THREAD

**Issue by LandryNorris** [cockpit-project/cockpit#16606]
Cockpit version: Latest on Arch Linux (package version is 257-1)
OS: Arch Linux
uname -a: Linux landry-hp-spectre 5.14.16-arch1-1 #1 SMP PREEMPT Tue, 02 Nov 2021 22:22:59 +0000 x86_64 GNU/Linux
Page: Login

I use Howdy for facial recognition (using the instructions Howdy gives). My laptop has a hardware camera kill switch, so I often use that when I don't need facial recognition. Most other programs that use PAM will react to the error Howdy gives when the kill switch turns the camera off by skipping it and asking for my password. Cockpit tells me that there is an internal error in the login process and won't log me in unless I turn my camera back on (despite already asking me for my password).

Steps to reproduce
1. Install Howdy
2. Add "auth 	  sufficient	pam_python.so	/lib/security/howdy/pam.py" to the start of /etc/pam.d/cockpit
3. Disable camera via hardware
4. Attempt to log in using password.

**Comment by martinpitt** [comment]
Sorry for the silence here, but I'm afraid this is really a case of "you or another contributor need to debug that themselves". This isn't testable in a VM, and howdy isn't packaged in either Fedora or Debian, so this is  hard to reproduce for everyone in our team.

There is nothing wrong in principle with that "auth sufficient" line. If howdy fails, it should get skipped and go on with the next PAM line. As next step, I suggest to append "debug" to the lines, make sure that you inserted howdy to the *correct* place in /etc/pam.d/cockpit (it would really help if you pasted the whole file here, or a diff), and then watch `journalctl -f` during a login attempt.

**Comment by martinpitt** [comment]
Stale, and not supportable by us.
