### ISSUE TITLE
Need a good and easy way to tell the size and space avaiable to /var/lib/docker

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1662]
Spinning off issue #1541

We need a good way to tell the total size available to /var/lib/docker to support the use cases of the personas Peter and David here:
https://github.com/cockpit-project/cockpit/wiki/Atomic:-Docker-Storage

**Comment by andreasn** [comment]
His name is Robert goddamit

**Comment by andreasn** [comment]
A bit plain, but functional. Clicking the panel jumps to the disk/volume group in Storage.

![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/containers/docker-storage.png)

**Comment by stefwalter** [comment]
Nice.
