### ISSUE TITLE
cockpit-client / login: Recent hosts

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16672]
We should save and present recent hosts that were successfully connected to, possibly as a list or a grid of recent hosts.

(I guess these should be stored in the browser's local storage?)

I'm mainly thinking of Cockpit Client for this, but it would be useful from the browser as well.

**Comment by garrett** [comment]
We probably want to let someone remove hosts too. It'd be annoying to have temporary hosts or those purposefully taken out of commission to still show up.

**Comment by garrett** [comment]
Here's a rough mockup of one idea:

![cockpit-client-hosts](https://user-images.githubusercontent.com/10246/144267793-df10afa3-e16a-45e2-8961-598097b6a8f4.png)

It's not a great use of space, but it's more or less inspired by the PF4 login and I added the hosts as a list. 

The style could still be up in the air, of course; this is just a wireframe.

Source:

https://excalidraw.com/#json=LBhvBwJN11kJEDMLueoEB,TZhzHJO7RxfHzRlYabScXg

[🡳 **cockpit-client-hosts.excalidraw.zip**](https://github.com/cockpit-project/cockpit/files/7635333/cockpit-client-hosts.excalidraw.zip)

**Comment by garrett** [comment]
Alternate, deviating from the PF4 login pattern, but improving the layout a bit:

## By default, without hosts:

![cockpit-client-hosts-alt](https://user-images.githubusercontent.com/10246/144269279-7fec302c-20c2-47c8-82a0-a737d10189e7.png)

## And two possibilities for the hosts:

### At the side

![cockpit-client-hosts-alt-1](https://user-images.githubusercontent.com/10246/144269333-6e9ae76e-6b0f-4775-9da3-7f23d55a9b16.png)

### Under, in an attached grey box, like PF4 login page

![cockpit-client-hosts-alt-2](https://user-images.githubusercontent.com/10246/144269328-0926df6e-134b-4270-8b97-244edd5b6521.png)

[🡳 **cockpit-client-hosts-alt.excalidraw.zip**](https://github.com/cockpit-project/cockpit/files/7635418/cockpit-client-hosts-alt.excalidraw.zip)
https://excalidraw.com/#json=0w2nTfxh8Xtr4HCu7L6-A,u5YCUgRJRMeBNC_Yd24xgw

**Comment by garrett** [comment]
@allisonkarlitskaya: Oh! I forgot to add your star/unstar icon in the top of the titlebar. Sorry (starry)!

These mockups assume saving each host by default and removing any unwanted ones. We could do that or we could do the bookmark-like toggle with stars. (If we do have the star in the header for adding, then we need to be able to remove hosts too. That could either be done in the "page" area like here, or we'll have to grow a management UI, like a settings page. We should try to avoid that as long as possible.)

**Comment by marusak** [comment]
When I saw this, the first thing that sprung to my mind was that we use [`<datalist>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) in `Add new host` modal inside host switcher. It does something very similar (not exactly, as it gets hosts from `/etc/cockpit/machines.d/`). So just worth mentioning and maybe we can use similar approach in both places?

**Comment by garrett** [comment]
@marusak: Datalist is more for an autocomplete, which this is not. The host tiles are always there by default and it's not filterable. It's like a browser's top sites. When I say the hosts aren't there, I mean this is the default mode when there are no previously connected hosts. As it's a wireframe, I know it doesn't communicate as much as a more high-fidelity mockup, so it's easy to mistake one widget for another.

While it _could_ be an autocomplete, the goal is to prevent having to type at all. Someone may already be using their mouse (such as after clicking the icon) and would want to click once to start connecting to a host.

(Also: Datalist is not properly supported in all browsers. There are still some issues with Firefox, so it has to be used properly. For example, it needs to be only paired with `<input type"text">`, not other types. And has a bug with initial display: https://bugzilla.mozilla.org/show_bug.cgi?id=1474137. These can be worked-around, of course.)
