### ISSUE TITLE
Search image dialog typo

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1667]
The dialog title is "search image" - is this proper English? Shouldn't it be "search for image"?

**Comment by stefwalter** [comment]
Split out from #1477 

![searchimage](https://cloud.githubusercontent.com/assets/6277245/5013031/5dcea950-6a93-11e4-9e06-12f2e8b0b7fc.png)

**Comment by jeffvance** [comment]
I like "Image Search" more. Making change now.
