### ISSUE TITLE
shell: Adjust style of the admin switcher

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16694]
Follow-up to:
- https://github.com/cockpit-project/cockpit/pull/16614

The above-referenced PR changed the shell to use PF4 widgets. As such, the style of the help and session menus have changed. This means we should reconsider the style of the admin switcher. We might determine it shouldn't change, but we should at least think about it and if it needs to be more consistent.

Note: The current implementation with the bold underline when hovering was done as the result of a UX study, so we need to be careful with this.

**Comment by KKoukiou** [comment]
@garrett is this something you want to work on? AFAIK there was no complains whatsoever about this element. Please close this issue if not relevant anymore.

**Comment by garrett** [comment]
I think I opened this issue before making it more button-like, with an icon in color, when you're signed out.

It looks like this now (and has for some time):

![image](https://user-images.githubusercontent.com/10246/212876121-b7e66b9c-9113-44fe-93d3-3880fa6007a9.png)

I purposefully kept being an admin mainly unstyled, as problems (like things not appearing or others not being useful enough) only arise when you're not signed in as an admin, not when you are an admin.
