### ISSUE TITLE
Time Format Change (AM/PM to 24-hour)

### ISSUE THREAD

**Issue by tijanicm** [cockpit-project/cockpit#16713]
Hi,

Is there a possibility to change the time format from AM/PM to 24-hour?

Kind regards.

**Comment by marusak** [comment]
It is based on the locale you are using. If the locale uses 12-hour format, then cockpit will use that, otherwise it will use 24-hour format.

**Comment by tijanicm** [comment]
@marusak Thank you for the answer.

Would there be any possibility of adding the English – UK to the display languages?
In that way we would have English language and 24-hour time format, if I am correct.

**Comment by marusak** [comment]
> Would there be any possibility of adding the English – UK to the display languages?

Once https://translate.fedoraproject.org/projects/cockpit/main/en_GB/ would get translated, it would be included.
I am not sure, if anyone is interested in doing this, as it would be mostly the same as original. I don't think that there would be too many differences between original and British English in Cockpit strings. But we could theoretically either just add untranslated British .po file (as untranslated strings default to original anyway) or threat en-gb as special case as we do en-us. Both should be easy to do.

**Comment by marusak** [comment]
Actually, we already track https://github.com/cockpit-project/cockpit/issues/16588 which is about using local settings. Using that would fix this issue nicely I believe.
