### ISSUE TITLE
Integration testing: quick start missing important notes

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#1671]
Possible errors when following quick start in [test/README](https://github.com/cockpit-project/cockpit/blob/d88b2311ee4d6c5f491974be4514b36fcb834e6e/test/README):
* phantomjs only installed in local cockpit dir, but needed globally for testing
* ``mock`` may issue a warning when user is not in group ``mock``, which leads ``vm-install`` to fail during ``testsuite-prepare``

**Comment by stefwalter** [comment]
Fixed by #1672
