### ISSUE TITLE
client: Remember cookies

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16712]
When you're using Cockpit Client in a flatpak, it doesn't remember:
- admin status
- language setting (you always get the default)

I guess it's not saving cookies and/or localstorage from once you're logged into Cockpit?

**Comment by marusak** [comment]
> admin status

This should be fixed by https://github.com/cockpit-project/cockpit/pull/16700

> language setting 

Even with #16700 it does not remember cookies. We need to fix that
