### ISSUE TITLE
iSCSI and LVM option don't show in Ubuntu 20.04

### ISSUE THREAD

**Issue by xsmart** [cockpit-project/cockpit#16740]
Cockpit version: 257
OS: Ubuntu 20.04 

Steps to reproduce
when run in Rocky linux 8, there has LVM and iSCSI, but ubuntu 20.04 don't have that, do i need install some package?
![1639706145(1)](https://user-images.githubusercontent.com/4601085/146475976-eeb62461-9d15-4daf-a008-dcdbc8a67e8b.png)

**Comment by marusak** [comment]
You will need `udisks2-lvm2` and `udisks2-iscsi`

**Comment by martinpitt** [comment]
udisks2-lvm2 yes. Debian/Ubuntu does not package udisks iscsi support, so this functionality is just unavailable there.
