### ISSUE TITLE
scheduling a shutdown at a specific time does not work

### ISSUE THREAD

**Issue by basilrabi** [cockpit-project/cockpit#16753]
Cockpit version: 259-1
OS: Fedora 35
Page: Overview (Shutdown)

When scheduling a shutdown at a specific time, the page turns white and an _Ooops!_ is shown.

Steps to reproduce

1. Go to overview
2. Choose shutdown in reboot drop down
3. Choose _Specific time_  in delay dropdown

![screen](https://user-images.githubusercontent.com/29010952/147010820-c13bf1c0-a6e3-4715-8b65-9c39889e8f3f.gif)

**Comment by jelly** [comment]
Thanks for reporting the issue, I managed to reproduce it locally the issue being caused by `this.state.error` being set to an object instead of a string. This is for me is caused by:

```
cockpit.js:1 date: invalid date ‘22/12/2021 12:16’
```

So this needs some further investigation.
