### ISSUE TITLE
Disconnected after login

### ISSUE THREAD

**Issue by hamdyaea** [cockpit-project/cockpit#16764]
Cockpit version: cockpit-251.1-1.el8.x86_64
OS: Rocky Linux 8.5

I connect to my cockpit with the right pasword and user then I get disconnected after a few seconds.

Relevant parts of the system log are also useful:
`journalctl -f`

```
Dec 27 21:02:44 Daylight systemd[1]: Starting Socket for Cockpit Web Service http-redirect instance.
Dec 27 21:02:44 Daylight systemd[1]: Starting Socket for Cockpit Web Service https instance factory.
Dec 27 21:02:44 Daylight systemd[1]: Starting Socket for Cockpit Web Service http instance.
Dec 27 21:02:44 Daylight systemd[1]: Listening on Socket for Cockpit Web Service http-redirect instance.
Dec 27 21:02:44 Daylight systemd[1]: Listening on Socket for Cockpit Web Service https instance factory.
Dec 27 21:02:44 Daylight systemd[1]: Listening on Socket for Cockpit Web Service http instance.
Dec 27 21:02:44 Daylight systemd[1]: Starting Cockpit Web Service...
Dec 27 21:02:45 Daylight systemd[1]: Started Cockpit Web Service.
Dec 27 21:02:45 Daylight systemd[1]: Started Cockpit Web Service https instance factory (PID 49513/UID 994).
Dec 27 21:02:45 Daylight systemd[1]: Starting Socket for Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
Dec 27 21:02:45 Daylight systemd[1]: Listening on Socket for Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
Dec 27 21:02:45 Daylight systemd[1]: Started Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
Dec 27 21:02:45 Daylight systemd[1]: cockpit-wsinstance-https-factory@12-49513-994.service: Succeeded.
Dec 27 21:02:45 Daylight cockpit-ws[49517]: json_object_get_string_member: assertion 'node != NULL' failed
Dec 27 21:03:01 Daylight systemd[1]: Started Session 3217 of user root.
Dec 27 21:03:24 Daylight systemd[1]: session-3206.scope: Succeeded.
Dec 27 21:03:27 Daylight systemd[1]: session-3215.scope: Succeeded.
**Dec 27 21:03:45 Daylight cockpit-ws[49517]: json_object_get_string_member: assertion 'node != NULL' failed
Dec 27 21:03:45 Daylight cockpit-session[49542]: pam_ssh_add: Identity added: /root/.ssh/id_rsa (root@Daylight)**
Dec 27 21:03:45 Daylight systemd[1]: Started Session 3218 of user root.
Dec 27 21:03:45 Daylight systemd-logind[793]: New session 3218 of user root.
**Dec 27 21:03:45 Daylight cockpit-session[49542]: pam_unix(cockpit:session): session opened for user root by (uid=0)
Dec 27 21:04:00 Daylight cockpit-session[49542]: pam_unix(cockpit:session): session closed for user root**
```

**Comment by martinpitt** [comment]
The `json_object_get_string_member()` message is a red herring -- it always happens if you log in without a client certificate, and we should quiesce this error message. But it's not what closes your session. The logs and timestamps show that the login page came up at 21:02:45, then you took a few seconds to type login/password, at 21:03:01 the session authentication succeeded and the session starte, and at 21:03:24 the session closed. There are *no* useful log messages here.

Please describe more precisely what you see during these 20 seconds, and also try and open the browser console (Ctrl+Shift+J) before logging in to see if the web browser disconnects by itself for some reason.

**Comment by hamdyaea** [comment]
So here's the answer of the disconnected page from the web console 👍🏽 

GEThttps://astrometry.ch:9090/
[HTTP/1.1 502 disconnected 15185ms]

	
GET
	https://astrometry.ch:9090/
État
502
disconnected
VersionHTTP/1.1
Transfert3,58 Ko (taille 3,35 Ko)

    	
    HTTP/1.1 502 disconnected

    Content-Type: text/html; charset=utf8

    Transfer-Encoding: chunked

    X-DNS-Prefetch-Control: off

    Referrer-Policy: no-referrer

    X-Content-Type-Options: nosniff

    Cross-Origin-Resource-Policy: same-origin
    	
    GET / HTTP/1.1

    Host: astrometry.ch:9090

    User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0

    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8

    Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3

    Accept-Encoding: gzip, deflate, br

    Connection: keep-alive

    Cookie: cockpit=dj0yO2s9NDI3Y2YzZWFkMjU5OTIzZTc3YTBlNGUxNTNjOGQ2MWFjOWJhMzJlYjQ3NWE4YWJmZGJjNmM5NjI5NDlmYmRhYQ==

    Upgrade-Insecure-Requests: 1

    Sec-Fetch-Dest: document

    Sec-Fetch-Mode: navigate

    Sec-Fetch-Site: none

    Sec-Fetch-User: ?1

    Sec-GPC: 1

    Pragma: no-cache

    Cache-Control: no-cache
    
    GET / HTTP/1.1
Host: astrometry.ch:9090
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: cockpit=dj0yO2s9NDI3Y2YzZWFkMjU5OTIzZTc3YTBlNGUxNTNjOGQ2MWFjOWJhMzJlYjQ3NWE4YWJmZGJjNmM5NjI5NDlmYmRhYQ==
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Sec-GPC: 1
Pragma: no-cache
Cache-Control: no-cache

**Comment by hamdyaea** [comment]
Here's the log from /var/log/audit/audit.log with or without selinux : 

t"
type=USER_END msg=audit(1640725823.700:34392): pid=72199 uid=0 auid=0 ses=4785 subj=system_u:system_r:crond_t:s0-s0:c0.c1023 msg='op=PAM:session_close grantors=pam_loginuid,pam_keyinit,pam_limits,pam_systemd acct="root" exe="/usr/sbin/crond" hostname=? addr=? terminal=cron res=success'UID="root" AUID="root

**Comment by martinpitt** [comment]
Still no conclusive error message, I'm afraid. Which browser are you using? Please first try a private window, to ensure that it's not an old cookie or so. Please also try another browser if you can -- often, installed extensions break websockets.

**Comment by hamdyaea** [comment]
I have the same issue on all browsers.

Here's the log or /var/log/messages 

Dec 30 19:41:26 Daylight systemd-logind[793]: New session 7630 of user root.
Dec 30 19:41:51 Daylight systemd[1]: Starting Socket for Cockpit Web Service http-redirect instance.
Dec 30 19:41:51 Daylight systemd[1]: Starting Socket for Cockpit Web Service https instance factory.
Dec 30 19:41:51 Daylight systemd[1]: Starting Socket for Cockpit Web Service http instance.
Dec 30 19:41:51 Daylight systemd[1]: Listening on Socket for Cockpit Web Service http-redirect instance.
Dec 30 19:41:51 Daylight systemd[1]: Listening on Socket for Cockpit Web Service http instance.
Dec 30 19:41:51 Daylight systemd[1]: Listening on Socket for Cockpit Web Service https instance factory.
Dec 30 19:41:51 Daylight systemd[1]: Starting Cockpit Web Service...
Dec 30 19:41:51 Daylight systemd[1]: Started Cockpit Web Service.
Dec 30 19:41:51 Daylight systemd[1]: Started Cockpit Web Service https instance factory (PID 114922/UID 994).
Dec 30 19:41:51 Daylight systemd[1]: Starting Socket for Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
Dec 30 19:41:51 Daylight systemd[1]: Listening on Socket for Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
Dec 30 19:41:51 Daylight systemd[1]: Started Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
Dec 30 19:41:51 Daylight systemd[1]: cockpit-wsinstance-https-factory@24-114922-994.service: Succeeded.
Dec 30 19:41:51 Daylight cockpit-tls[114922]: cockpit-tls: gnutls_handshake failed: The TLS connection was non-properly terminated.
Dec 30 19:41:51 Daylight journal[114927]: json_object_get_string_member: assertion 'node != NULL' failed
Dec 30 19:41:56 Daylight journal[114927]: json_object_get_string_member: assertion 'node != NULL' failed
Dec 30 19:41:56 Daylight cockpit-session[114938]: pam_ssh_add: Identity added: /root/.ssh/id_rsa (root@Daylight)
Dec 30 19:41:56 Daylight systemd[1]: Started Session 7631 of user root.
Dec 30 19:41:56 Daylight systemd-logind[793]: New session 7631 of user root.
Dec 30 19:42:01 Daylight systemd[1]: Started Session 7632 of user root.
Dec 30 19:42:12 Daylight systemd[1]: session-7631.scope: Succeeded.
Dec 30 19:42:12 Daylight systemd-logind[793]: Session 7631 logged out. Waiting for processes to exit.
Dec 30 19:42:12 Daylight systemd-logind[793]: Removed session 7631.

**Comment by martinpitt** [comment]
What is your login shell? Anything else than bash?

**Comment by hamdyaea** [comment]
I am using ZSH with root and bash with the normal user. I have the same problem with both. I have httpd (apache) running. I think that's the problem.

**Comment by martinpitt** [comment]
There's still nothing conclusive here, I'm afraid. The closest hint is this one:

> cockpit-tls: gnutls_handshake failed: The TLS connection was non-properly terminated.

which usually suggests that the browser aborted the handshake.  Please open the browser console (Ctrl+Shift+J usually) and check if you get any messages during a login attempt. Thanks!

**Comment by martinpitt** [comment]
Stale and not actionable I'm afraid.
