### ISSUE TITLE
Track and manage TCP traffic

### ISSUE THREAD

**Issue by Link0Darck** [cockpit-project/cockpit#16761]
Hello,
I'm coming to you because I have some ideas that would be nice with your interface.
It would be three to be more precise:

- The first would be to add the ability to set permissions to certain users, for example, I have a user I don't want to access the terminal and many other things.

- The second would be to add a way to access directories and transfer files like web ftp to upload the file or even edit it.

- The third would be to add a security category like an IP log to see all incoming and outgoing connections like tcptracker except that it only does TCP protocol to monitor what is happening on our server with a way to ban or cut the connection of a person who is connected to the server etc...

I've been using it for a while now, but I'm not sure how to use it.

**Comment by marusak** [comment]
> add the ability to set permissions to certain users, for example, I have a user I don't want to access the terminal and many other things.

See https://github.com/cockpit-project/cockpit/issues/14332
But please mind, even if you decide to hide terminal from the UI, any user can open browser console and use `cockpit.spawn` to execute any arbitrary command (which the given user can do).

> add a way to access directories and transfer files like web ftp to upload the file or even edit it.

See https://github.com/cockpit-project/cockpit/issues/12338 and https://github.com/45Drives/cockpit-navigator

> add a security category like an IP log to see all incoming and outgoing connections like tcptracker except that it only does TCP protocol to monitor what is happening on our server with a way to ban or cut the connection of a person who is connected to the server etc...

If I understand correctly, this would be for a full separate plugin. If that is the case, I am afraid it is not something that the core Cockpit team would have time for. Of course, we encourage anyone to do their own plugins using [starter-kit](https://github.com/cockpit-project/starter-kit/). You can see list of such plugins on our website: https://cockpit-project.org/applications.html

**Comment by marusak** [comment]
No answer and as explain in the above comment there does not seem to be anything from our side (or it is already tracked elsewhere)
