### ISSUE TITLE
Allow automatic security updates and all updates to work on separate schedules

### ISSUE THREAD

**Issue by darakian** [cockpit-project/cockpit#16762]
Page: /updates

At the moment cockpit can do automatic updates, but the user has the choice of one schedule on which to run with the choice of either updating security updates or all updates.
<img width="674" alt="image" src="https://user-images.githubusercontent.com/3607524/147417789-79c6529e-7fd8-4080-8bf4-a349c19f1a3d.png">

Can you add a feature where I could run security updates daily and all updates on another, longer schedule? Something like Monthly. I get that the webUI is meant to keep things simple and I'm not asking for fine granularity or anything.

<details>
<summary>Cockpit Package version</summary>

```
[root@fedora etc]# dnf info cockpit
Last metadata expiration check: 1:42:24 ago on Sun 26 Dec 2021 12:32:37 PM EST.
Installed Packages
Name         : cockpit
Version      : 259
Release      : 1.fc35
Architecture : aarch64
Size         : 57 k
Source       : cockpit-259-1.fc35.src.rpm
Repository   : @System
From repo    : updates
Summary      : Web Console for Linux servers
URL          : https://cockpit-project.org/
License      : LGPLv2+
Description  : The Cockpit Web Console enables users to administer GNU/Linux servers using a
             : web browser.
             :
             : It offers network configuration, log inspection, diagnostic reports, SELinux
             : troubleshooting, interactive command-line sessions, and more.
```
</details>

Also, love your work 👍

**Comment by martinpitt** [comment]
This is a UI for [dnf-automatic](https://dnf.readthedocs.io/en/latest/automatic.html). This does not support separate schedules for security and all updates, so I'm afraid we can't do this right now.

For the record, apt's counterpart is the same, but the automatic updates UI is currently not implemented at all for apt.

**Comment by darakian** [comment]
Gotcha. I'll go ping dnf-automatic :)
