### ISSUE TITLE
scanning for certificates fails with "Value too large for defined data type" on armhf-qemu guest on amd64 host

### ISSUE THREAD

**Issue by jo-bitsch** [cockpit-project/cockpit#16778]
Today I ran into an interesting little bug:
I wanted to run cockpit inside a armhf-qemu guest on an amd64 host, but ran into the following error message:

`cockpit-tls: Could not locate server certificate: Error loading certificates from /etc/cockpit/ws-certs.d: Value too large for defined data type`

After investigating a bit, I tracked it down to the following line:
https://github.com/cockpit-project/cockpit/blob/ef9002e32e85e88cccd99f1e49996e7891018218/src/common/cockpitwebcertificate.c#L55

Would it be possible to replace the call with
`n = scandir64 (dir_name, &certs, filter_cert, alphasort64);`
and adjust https://github.com/cockpit-project/cockpit/blob/ef9002e32e85e88cccd99f1e49996e7891018218/src/common/cockpitwebcertificate.c#L38 to use `dirent64`.

Thanks a lot for providing the world with this excellent piece of software!

**Comment by martinpitt** [comment]
Thanks for your report! If possible, I'd rather avoid literally writing `scandir64()` in the code -- that's not even officially documented in the manpage. dirent.h automatically enables/redirects these if `__USE_LARGEFILE64` is defined, and it seems /usr/include/features.h enables that with `#define _GNU_SOURCE`. We do the latter in several source files already, but not in cockpitwebcertificate.c. Are you in a position to test this?

```diff
--- src/common/cockpitwebcertificate.c
+++ src/common/cockpitwebcertificate.c
@@ -17,6 +17,8 @@
  * along with Cockpit; If not, see <http://www.gnu.org/licenses/>.
  */
 
+#define _GNU_SOURCE
+
 #include "config.h"
 
 #include <assert.h>
```

**Comment by martinpitt** [comment]
I sent PR #16779 which should fix this in a more robust manner, but the test patch above is less intrusive. If it helps, I can provide an arm rpm (or .deb?) for testing.

**Comment by martinpitt** [comment]
Nevermind -- the file already includes config.h, which defines _GNU_SOURCE. So this apparently doesn't help.

**Comment by allisonkarlitskaya** [comment]
`AC_SYS_LARGEFILE`?

**Comment by martinpitt** [comment]
I updated PR #16779 to enable largefile support, and made a [Fedora 35 scratch build](https://koji.fedoraproject.org/koji/taskinfo?taskID=80859545), which includes a [32 bit ARM build](https://koji.fedoraproject.org/koji/taskinfo?taskID=80859613).

@jo-bitsch , please let me know if you need another Fedora/CentOS release, or an Ubuntu .deb (then I can put this into a PPA).

**Comment by jo-bitsch** [comment]
I will test it later today. My target system is debian though (but I have everything in place to compile it myself) Thanks so much for the quick help!
