### ISSUE TITLE
Login history IP Address formatting issue

### ISSUE THREAD

**Issue by leomoty** [cockpit-project/cockpit#16774]
Cockpit version: 259
OS: Fedora Server 35
Page: Overview / Accounts

Updated cockpit from 247 to 259, and IP Address formatting looks weird, looks like a mix of IPv4 and IPv6. Mixed results happen in both "last successful login" and "login history". The upgrade is pretty clear after it went from 247 to 259.... Also .173 and .174 are just two machines I was connecting to it, not meaningful.

Steps to reproduce

1. Login to server
2. Check last successful location IP address

![image](https://user-images.githubusercontent.com/1463740/148005186-9a1fd5cf-3e18-4359-9198-a43546c99230.png)

3. Press "View login history"

![image](https://user-images.githubusercontent.com/1463740/148005168-c128bc93-86e5-4938-b2ed-48c4803275c4.png)

**Comment by marusak** [comment]
![Screenshot from 2022-01-04 07-50-30](https://user-images.githubusercontent.com/12330670/148020386-e96608fa-39fe-4efb-ad47-87b7aa9e9b91.png)

Notice the last section talking about "dual format".
The fact it has changed is not related to updating Cockpit but some other utility/library on your system. We only parse output of `last` (run with `-n 25` to see only last 25 logins).

**Comment by martinpitt** [comment]
This was closed wrongly back then. But it is a duplicate of #21383 which just got fixed in PR #21418.
