### ISSUE TITLE
Allow for favoriting services

### ISSUE THREAD

**Issue by queengooborg** [cockpit-project/cockpit#16780]
First off, I must say: great job, Cockpit project team!  I really love how straightforward and easy to use the UI is -- quite a refreshing experience after struggling with the complexity of Zabbix!  Keep up the great work, everyone!  💜 

I had a feature suggestion that I was hoping you guys would be interested in.  I'd love to have the ability to favorite or pin services to the top of the list, so I can quickly see them all without having to scroll through the system-defined services.  I grabbed Cockpit as a way to quickly manage the various gaming servers I am hosting (which has been great, now that I've tied them all into `systemctl` controlled services), but I typically keep two or three on at a time.  Having them at the top of the list, or easily filterable, would be great for quick access and monitoring of them!

**Comment by queengooborg** [comment]
Thanks for the quick response!  For my use case, I am commonly starting and stopping these particular services manually, and so I'd love to have quick access to trigger them at the top of the page.  I think that it makes sense to place the "pin" action in the menu on the service's page -- users are already expecting to control their services from there!

**Comment by martinpitt** [comment]
Honestly this sounds more like a per-user preference, and should go into localstore -- like language selection or the list of recent hosts. There isn't anything "systemic" about these which would justify to create lots of little drop-in files.
