### ISSUE TITLE
List of servers to connect to in desktop app

### ISSUE THREAD

**Issue by Yajo** [cockpit-project/cockpit#16781]
Page: login 

I've been testing Cockpit desktop client. I always used an SSH connection manager, and this one can be used as one of those, but with way more features, as long as the required depedencies are in the server. Neat!

However I still need to type that ugly `user@server` every time I want to connect to a server.

It'd be great if the desktop app could have a locally-stored list of servers where to connect to. One example of an app that does that is https://github.com/muriloventuroso/easyssh, in case it helps to draw some inspiration.

**Comment by martinpitt** [comment]
PR #16700 does exactly that :grin:  It will be released today with Cockpit 260.
