### ISSUE TITLE
Ability to edit arbitrary configuration files on the web interface

### ISSUE THREAD

**Issue by rdiez** [cockpit-project/cockpit#16790]
Hi all:

I am a (very) part-time Linux sysadmin in a small team of Windows users.

For some basic and repetitive tasks, like adding an account to our OpenVPN server configuration, I could write a user guide stating which config file to edit and which systemd service to restart afterwards. The trouble is, Windows users have problems editing files with sudo on a remote Linux machine.

Cockpit is relatively easy to use, and even has a built-in shell console, but I am missing something in between. I haven't got the time or the skills to write custom Cockpit Applications for my scenario. But if Cockpit allowed editing arbitrary configuration (text) files on the web interface, that would be enough. Such an built-in text editor would be the right compromise between flexibility and easy of use.

It does not have to be truly arbitrary configuration files. I could enter in some Cockpit configuration file the list of text files that the user should be able to edit on the web interface (with root access).

Thanks in advance,
&nbsp;&nbsp;  rdiez

**Comment by marusak** [comment]
Have you tried this plugin? https://github.com/45Drives/cockpit-navigator
It should allow users to find and edit files.

**Comment by rdiez** [comment]
Not yet, thanks for the hint.

In the mean time, I found that a Webmin module can do such a thing:

"Custom Commands"

"Create buttons to execute commonly used commands or edit files on your system."

"Another feature of the module is the ability to define file editors, so that frequently changed files can
 be edited through Webmin's web interface. You can also define commands to be run before and after the file
 is edited, so that it can be validated, copied or backed up before editing."

It would be nice to have such a feature built into Cockpit too, or at least automatically packaged in Ubuntu. Otherwise, with random plug-ins from random sources, you tend to hit this kind of snag:

https://github.com/45Drives/cockpit-navigator/issues/30

**Comment by martinpitt** [comment]
@rdiez: We are not going to implement the umpteenth crappy editor, sorry. Opening Cockpit's Terminal and using the editor of your choice works just fine, and that's what we recommend/support. Thanks!
