### ISSUE TITLE
Wifi goes dead after install to raspbian

### ISSUE THREAD

**Issue by JustinBenedick** [cockpit-project/cockpit#16797]
Cockpit version: Latest as of 1/8
OS: Rasbian Buster
Device : Raspberry pi 4
Page: 

Wifi is compeltely disabled and in-operable after installing cockpit on rasbian-buster. This is even after the device was already working with wifi and a static IP
<!---
Please help us out by explaining how to reproduce it.

Steps to reproduce

1. sudo apt update 
2.sudo pat install cockpit-y
3.reboot

I did try to install the backports version and rasbian did not cooperate when I tried to add the repo. After the reboot the wifi does not have any IP address. 

I am currently trying to use this on a RPI4 that is running docker with a octorpint to manage and use a 3d printer. I don't have the option to have a network cable plugged in.

**Comment by marusak** [comment]
I believe this can be related: https://github.com/cockpit-project/cockpit/issues/15972
Can you please read through that thread (mainly 3rd comment) and let me know if that helped?

**Comment by JustinBenedick** [comment]
This actually making a lot of sense.  I am going to have to try the partial install.

**Comment by JustinBenedick** [comment]
The install command without networking and machines (Not planning on using it) Worked
sudo apt install cockpit-ws cockpit-system cockpit-packagekit cockpit-storaged cockpit-pcp

Also I will note that under the networking section it only shows information on the docker interface and not on the wifi or ethernet.
