### ISSUE TITLE
Allow specifying custom ssh port for the cockpit-rsync-plugin

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#16817]
Maybe add new ENV variable, RSYNC_PORT.

For reasoning see https://github.com/M4rtinK/anaconda/pull/21#discussion_r782226515

**Comment by KKoukiou** [comment]
@martinpitt this was not meant to be used by CI, rather from developers.
@jkonecny12  was not fond of the idea of making the `~/.ssh/config` changes obligatory for using this rsync mode. 

I know in cockpit we also add the ssh/config host entry for the test VM, in order to use the RSYNC option, as the ssh port is not the default. 

@jkonecny12 would you then mind to keep this strategy for developing in anaconda as well? (There is always the option to rsync manually instead of using the automatic rsync plugin)

**Comment by jkonecny12** [comment]
It seems that I don't understand the logic enough. What I was thinking of is the development on the remote VMs or multiple VMs in parallel. In that case the `~/.ssh/config` doesn't really scale nice.

**Comment by martinpitt** [comment]
Ah, I see what you mean -- sorry, I misinterpreted the original request. So you *do* have a `Host c` entry, but multiple parallel VMs on different ports for rsyncing. Yes, that makes sense then.

**Comment by KKoukiou** [comment]
Irrelevant at this point.
