### ISSUE TITLE
Cockpit doesn't recognize UUID storage mounting

### ISSUE THREAD

**Issue by michaelkrieger** [cockpit-project/cockpit#16856]
Cockpit version: 260-1~bpo11+1
OS: Debian 11
Page: Storage

Filesystem shows the yellow exclamation and notes an `Inconsistent filesystem mount: The filesystem is currently mounted on /mnt/datadisk1 but will not be mounted after the next boot.` Meanwhile, /etc/fstab has
`UUID="86b319d7-1faa-1234-a123-8731211cc4a0" /mnt/datadisk1              ext4    defaults,nofail   0 2` in it and is correctly mounted by Debian 11 on each and every reboot without fail.

While there was discussion on automount in https://github.com/cockpit-project/cockpit/issues/15902 , this is not via automount but a hardcoded mount in /etc/fstab.

Steps to reproduce

1. Have a UUID mount formatted as above in /etc/fstab with the UUID obtained from `lsblk -f`
2. Mount the partition `mount /mnt/datadisk1`
3. View the error under storage

![2022-01-19](https://user-images.githubusercontent.com/7321259/150192023-70277e12-4149-404c-940a-102e0294346c.png)

**Comment by martinpitt** [comment]
Right, the lookup should happen for labels, UUID, and also direct dev name. @mvollmer , is that something for you?

**Comment by mvollmer** [comment]
> UUID="86b319d7-1faa-1234-a123-8731211cc4a0"

I bet it's the quotes.  UDisks2 doesn't expect them and fails to associate this fstab entry with the right filesystem.

**Comment by mvollmer** [comment]
> I bet it's the quotes. UDisks2 doesn't expect them and fails to associate this fstab entry with the right filesystem.

Hmm, that might have been a bit terse. :-)

Please remove the quotes from your entry in /etc/fstab:

```
UUID=86b319d7-1faa-1234-a123-8731211cc4a0 /mnt/datadisk1 ext4 defaults,nofail 0 2 
```

We should probably change UDisks to allow and ignore quotes, but note that quoting in a field does probably not allow it to contain spaces anyway.  Those need to be escaped as `\040`.  But I should check how other programs actually parse /etc/fstab.

**Comment by mvollmer** [comment]
Actually, UDisks2 should do the right thing since https://github.com/storaged-project/udisks/pull/888, but that doesn't seem to have been released yet.

**Comment by michaelkrieger** [comment]
> Please remove the quotes from your entry in /etc/fstab:
> We should probably change UDisks to allow and ignore quotes, but note that quoting in a field does probably not allow it to contain spaces anyway. Those need to be escaped as `\040`. But I should check how other programs actually parse /etc/fstab.

Removing the quotes did fix the issue.  The more I look into it, the more I see the quotes are not only unnecessary, but possibly even contrary to in the documentation for the fstab itself.  So I will call that solved since what I had seemed to not be in line with what I should have been doing in fstab.

That said, I'll leave it to you if handling it more gracefully in cockpit is something that should be done, as from web reading, I'm certainly not the only one to do it.

**Comment by mvollmer** [comment]
> That said, I'll leave it to you if handling it more gracefully in cockpit is something that should be done, as from web reading, I'm certainly not the only one to do it.

Yes, I am convinced now that UDisks2 needs to ignore quotes in things like `UUID="..."` or `LABEL="..."`.    systemd-fstab-generator ignores them, and the fstab man page contains this:

```
Note that mount(8) uses UUIDs as strings. The string representation of
the UUID should be based on lower case characters. But when specifying
the volume ID of FAT or NTFS file systems upper case characters are
used (e.g UUID="A40D-85E7" or UUID="61DB7756DB7779B3").
```

We just need to wait for a UDisks2 release with #888 in it.
