### ISSUE TITLE
Docker: bind container port to host port doesn't work

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#1685]
Binding ports from container to host doesn't work via cockpit, works when starting via CLI.
* Run dialog:
![docker_run](https://cloud.githubusercontent.com/assets/8711649/5815098/bdcf8862-a092-11e4-9c06-4601604aeb9f.jpg)
* Running container:
![docker_running](https://cloud.githubusercontent.com/assets/8711649/5815101/c29d23cc-a092-11e4-847f-a9954f43fb68.jpg)
* This is what we should get (started via cli):
![docker_running_cli](https://cloud.githubusercontent.com/assets/8711649/5815107/ca9f311e-a092-11e4-9e89-f76c932c13a7.jpg)

**Comment by dperpeet** [comment]
[start function](https://github.com/cockpit-project/cockpit/blob/fecb363bf1a3514c740b4d28fa60b40061d233be/pkg/shell/cockpit-docker.js#L1746-L1759) doesn't take options parameter that is filled with the exposed ports.

**Comment by dperpeet** [comment]
I will fix this together with #1587

**Comment by stefwalter** [comment]
A separate commit would be appreciated. This fix could get in much faster.

**Comment by dperpeet** [comment]
fixed by #1696
