### ISSUE TITLE
Oops! Unexpected Error Opening Virtual Machines after cockpit update

### ISSUE THREAD

**Issue by ajhollenbach** [cockpit-project/cockpit#16865]
Cockpit version:  Upgrade from 215'sh TO 260
OS: Ubuntu 20.04.3 LTS
cockpit 260-1~bpo20.04.1
cockpit-bridge 260-1~bpo20.04.1
cockpit-machines 215-1
cockpit-networkmanager 260-1~bpo20.04.1
cockpit-packagekit 260-1~bpo20.04.1
cockpit-pcp 215-1
cockpit-storaged 260-1~bpo20.04.1
cockpit-system 260-1~bpo20.04.1
cockpit-ws 260-1~bpo20.04.1

Page: 
Virtual Machines

After upgrading from 215 -> 260 my virtual machines menu inside of the web console no longer loads, receiving the "Oops!" message at the top.  This happens on two different user accounts.  This happens in both Chrome and Firefox. 

<!---
Please help us out by explaining how to reproduce it.
Login to web interface.  Select Virtual Machines on Left side.  Nothing loads in center, Oops! message in top right.

webBrowser JS errors:

index.js:2 Modal: Specify at least one of: title, aria-label, aria-labelledby.
componentDidMount @ index.js:2
jquery.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
machines.js:103 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' https://192.168.50.64:9090". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

h @ machines.js:103
machines.js:48 Uncaught ReferenceError: jQuery is not defined
    at Object.<anonymous> (machines.js:48:519593)
    at n (machines.js:1:110)
    at Module.<anonymous> (machines.js:135:782598)
    at n (machines.js:1:110)
    at Object.<anonymous> (machines.js:103:205205)
    at n (machines.js:1:110)
    at machines.js:1:902
    at machines.js:1:913
overview.js:2 Modal: Specify at least one of: title, aria-label, aria-labelledby.
componentDidMount @ overview.js:2
cockpit.js:1 grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

h @ cockpit.js:1
cockpit.js:1 Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

h @ cockpit.js:1
updates.js:2 Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
(anonymous) @ updates.js:2
index.js:2 Modal: Specify at least one of: title, aria-label, aria-labelledby.
componentDidMount @ index.js:2
DevTools failed to load source map: Could not load content for https://192.168.50.64:9090/cockpit/$5e65c2075bffc428706f07ca64b8340d0eabf84d77f7b894caa485a468958412/machines/machines.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://192.168.50.64:9090/cockpit/$5e65c2075bffc428706f07ca64b8340d0eabf84d77f7b894caa485a468958412/machines/machines.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

I also uninstalled and re-installed the cockpit-machines packages with 0 change.
I'm fairly new to Linux in general, but the JS errors make me think I just need to update some sort of packages on the linux server.

**Comment by jelly** [comment]
It sounds like you installed cockpit from focal-backports but not cockpit-machines which is also available:

```
focal-backports (admin): Cockpit user interface for virtual machines [universe]
259-1~bpo20.04.1: all
```

So I would recommend installing cockpit-machines from backports as well.

**Comment by martinpitt** [comment]
Right, that old cockpit-machines version does not work with the newer cockpit any more, sorry about that. Upgrading should fix it.
