### ISSUE TITLE
OpenSLP needs a conntrack helper

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#169]
SLP sends unicast replies to multicast queries.  This is not currently supported by the netfilter connection tracking facility.  Fixing this might help with two issues:

- The unicast replies are dropped by the usual firewall rules because they are not part of
  any established or related connection.

- In the presence of NAT, the multicast queries arrive at their destination with a rewritten
  source address, but replies to that address are dropped.

The same issue exists for other protocols that use unicast replies to multicast queries, such as SNMP. 

The conntrack helper should probably work with "nfct helper add", see the conntrack-tools RPM package.

References:

http://www.cs.helsinki.fi/linux/linux-kernel/2001-12/0789.htm
https://lkml.org/lkml/2013/5/7/614
https://lkml.org/lkml/2013/5/7/830

**Comment by stefwalter** [comment]
Closing this. I don't think we're going to use OpenSLP.
