### ISSUE TITLE
Authentication with SSH Keys

### ISSUE THREAD

**Issue by SpawnZ1337** [cockpit-project/cockpit#16913]
Hi Im having issues loading the ssh keys.

I have created a .pub file in the users ./ssh folder

and then created another file called *****.pk

once i add both i can then access my machines until i log out.

When I log out of the cockpit my keys vanish and then i get this error in the developer's console.

.pub is not a public key file.

Public key format is - SSH2 PUBLIC KEY

Any advice and help would be appreciated.

**Comment by martinpitt** [comment]
Hello @SpawnZ1337 , I have some questions:

 - Did you literally call the file `.pub`? That's very unusual, normally you should have a proper name such as `id_blabla.pub`.
 - What is the `.pk` file? Is that a completely separate key, or somehow related to the `.pub` one? I.e. is that key file related to the error message that you are seeing?
 - Are you sure that this `.pub` file actually does you any good? Or is it perhaps the `.pk` file that is being used to actually access the remote machines?
 - ".pub is not a public key file." is an error message from SSH itself -- it can't recognize the key file. To verify, run `ssh-keygen  -l -f ~/.ssh/.pub` (put in the actual file name, of course)
 - Can you please send a screenshot of the key dialog after trying to unlock the `.pub` file? I can't believe that SSH does not recognize the format, and then is able to unlock it.

Thanks!

**Comment by martinpitt** [comment]
No response in 8 months, closing.
