### ISSUE TITLE
Text misalign in account overview menu

### ISSUE THREAD

**Issue by tomasmatus** [cockpit-project/cockpit#16917]
Cockpit version: 260
OS: Fedora 35
Page: Account overview

The `Never expire account` and edit button are slightly shifted down compared to the text to it's left.

![account_menu_misalign](https://user-images.githubusercontent.com/74668142/152381956-1bad86e6-dba7-4780-928b-c3c3fc22e024.png)

**Comment by garrett** [comment]
**Firstly**: Thanks for noticing that this page is off!

**Secondly**: That's not how things are supposed to be aligned. For text, it's important to align to the baseline, not bounding boxes. (However, in this case, showing the bounding box with guides extending for two similarly set text elements does show that this is off. It's not the proper way to check... it but it's so clearly wrong here that it works. Things like line height can get in the way.)

The [baseline](https://en.wikipedia.org/wiki/Baseline_(typography)) of text, put simply, is the imaginary line where letters and numbers line up at the bottom when you ignore any descenders (the parts that go under, like in `ygp` and sometimes, in some fonts, additional curvy letters may slightly go under the baseline). It's best to look at bottom of traditionally flat-bottomed letters, like `mn`.

Here's a screenshot crop where I drew underlines on all the baselines. There should only be one baseline per label + widget pair, not two. (Only "Full name" and "Password" get things right.)
![Screenshot from 2022-02-08 09-32-00](https://user-images.githubusercontent.com/10246/152948434-674e0fc9-c2e2-4e0c-a87e-c7ad42490764.png)

Here's how it would look if the widgets were all properly aligned to the baseline:

![Screenshot from 2022-02-08 09-37-17](https://user-images.githubusercontent.com/10246/152949228-423fa21b-03c8-454e-a537-5690e317a221.png)
(I've ignored vertical rhythm and just nudged pixels around for the widgets to make them align properly.)

And here's the resulting adjusted screenshot at 1:1, without the guides:

![baseline-aligned](https://user-images.githubusercontent.com/10246/152951495-32b2bbbd-8499-40fd-9f6f-5670cbd8a448.png)

(There are still some horizontal issues with this layout, especially with "Never expire password", but we'll ignore those for now.)

**Thirdly**: This is a very old page and needs to be redesigned. 

Meanwhile, I was going to suggest porting it over from a table layout to PF4, but looking at the DOM, it actually looks like it's PF4. I know PatternFly had some issues with some minor label alignment in the past (off by 2 pixels here and there), but that was supposed have been resolved. There is the issue that checkbox lists do need a special attribute set for proper alignment (some of our modal dialogs do this correctly), but that doesn't explain everything wrong here.

**Comment by shaunak-09** [comment]
Hey, can you pls assign me this task?

**Comment by marusak** [comment]
Hey @shaunak-09
Please feel free to work on this task! Please report back when you have some interesting progress or when stuck. Looking forward :)

**Comment by Akshay9704** [comment]
Hey, I am new to this project. I want to ask how to run this project? as npm start is not working.

**Comment by KKoukiou** [comment]
@Akshay9704 you can read this https://github.com/cockpit-project/cockpit/blob/main/HACKING.md

You can always find somebody in the IRC (#cockpit on libera.chat), which is the right place to ask/answer such questions.

**Comment by DoonSlayer42** [comment]
Hey, can I work on this issue?

**Comment by shaunak-09** [comment]
Should I just align the lines of this page or redesign the entire page?
Also can you please guide me where to find this page's code since I cloned the repo and searched but could not find this page

**Comment by KKoukiou** [comment]
@shaunak-09 you don't have to fix the whole dialog alignment at once. Any independent alignment fix is welcome seperately. The pages code is here. https://github.com/cockpit-project/cockpit/blob/main/pkg/users/account-details.js

**Comment by Keshav-0907** [comment]
Hi, Can I work on this issue?

**Comment by garrett** [comment]
Note: While the Accounts page has been changed, this is still a problem to some degree. It's not as bad as before, as the groups has been changed (and that was the worst part), but as you can see in this screenshot, there are multiple baselines, often a pixel or two off:

![image](https://user-images.githubusercontent.com/10246/222111494-e1c75cf3-5c1e-4347-bd7c-bc754507c242.png)

This _might_ be a side effect of not using the correct widgets for the form layouts.

Additionally, the (?) icon and its text "Never expire account" are not aligned properly, as seen here:

![image](https://user-images.githubusercontent.com/10246/222112003-d40d001b-bec3-4be6-9cab-c0b3cd7a9d26.png)

**Comment by garrett** [comment]
Part of the problem is that the layout is not correct. It's a very, very old layout made even before PatternFly 3, then ported to PatternFly 3 and then ported to PatternFly 4.

According to the recent redesign, it was supposed to be more like this, with a view mode and edit for everything in create new user modal (top group area) and then editing the expiry:

![image](https://user-images.githubusercontent.com/10246/222115709-e0604e5a-91a2-4360-9f48-c1e8164c304a.png)

And the menu was supposed to look like this:

![image](https://user-images.githubusercontent.com/10246/222116434-5c704592-ce2e-4734-a436-38b3aa8ad7df.png)

But then we got into a discussion about viewing in details versus directly editing, and I made a hybrid which has direct editing like we currently have:

![image](https://user-images.githubusercontent.com/10246/222115526-3c7774e5-eab8-474c-82b1-dfa179f0ec07.png)

(Set password and force password change are actions in the menu instead of inline buttons.)

It might be better to update to the new UI than to adjust this very old one.

**Comment by KIET7UKE** [comment]
I'm working on this, lets's see if I can fix this.

**Comment by abhishekkhanna2710** [comment]
I want to work on this issue. Can anyone assign me the task if not working?

**Comment by KKoukiou** [comment]
Someone is already on it https://github.com/cockpit-project/cockpit/issues/16917#issuecomment-1471456719

**Comment by Avi-J0506** [comment]
I want to work on this issue. Please assign me to this issue

**Comment by adibmannan** [comment]
Did anyone solve this issue? I wanted to solve it.

**Comment by garrett** [comment]
I think @dCO2 fixed it last month @ https://github.com/cockpit-project/cockpit/pull/18517
