### ISSUE TITLE
After clicking on "View login history" from the "system overview" back button does not go back to "system overview"

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#16941]
### Explain what happens

1. Browser to system overview 
2. Click on "View login history"
3. Press the back button

Instead of going back to the system overview, you go back to the account overview page, most likely due to the hash used in the url?

### Version of Cockpit

257

### Where is the problem in Cockpit?

Accounts

**Comment by garrett** [comment]
Hopefully the history PR fixes this?

- https://github.com/cockpit-project/cockpit/pull/16938

**Comment by jelly** [comment]
Yes, we should verify it does.

**Comment by marusak** [comment]
Indeed, works with the current version
