### ISSUE TITLE
metrics: CPU and Memory services show user services but link to system services (which do not exist if it's just a user service)

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16945]
### Explain what happens

1. Visit the metrics page.
2. Have a user service running. On Fedora, that can be `user@1000`, `org.gnome.Shell@wayland.service`, `pipewire-pulse`, etc.
3. Click on the user service.
4. See a "Unit not found" page when the services page tries to load the system version of the unit (which in most cases won't exist... but even if it does also exist, it would be unrelated).

This is probably an issue with the way links are constructed on the metrics page.

What I get:
https://localhost:9090/system/services#/pipewire-pulse.service

What it should be:
https://localhost:9090/system/services#/pipewire-pulse.service?owner=user

(The `owner=user` is weird; it really should be `/username/pipewire-pulse.service`. But that's another issue.)

### Version of Cockpit

main

### Where is the problem in Cockpit?

Metrics

### Server operating system

Fedora

### Server operating system version

35

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
That sounds very close to what @tomasmatus fixed the other day in PR #16889, except that was for timers. @tomasmatus , would that be something for you  as a finger exercise?

**Comment by tomasmatus** [comment]
> That sounds very close to what @tomasmatus fixed the other day in PR #16889, except that was for timers. @tomasmatus , would that be something for you as a finger exercise?

Yes, I can have a look!
