### ISSUE TITLE
Real IP behind reverse proxy

### ISSUE THREAD

**Issue by GarryLai** [cockpit-project/cockpit#16949]
Page:  Network

I use Cockpit with Nginx reverse proxy.
But it always detect my login IP address as 127.0.0.1.
How can I fix it to true client IP?

**Comment by allisonkarlitskaya** [comment]
hi.

We've been thinking about implementing this for a little while now.  I hope to find the time to look into it soon.

**Comment by jelly** [comment]
This looks similar to https://github.com/cockpit-project/cockpit/issues/16927

**Comment by allisonkarlitskaya** [comment]
#16927 came first, so let's discuss there.
