### ISSUE TITLE
Skip PCP tests when mock-pmda cannot be initialized

### ISSUE THREAD

**Issue by jeffvance** [cockpit-project/cockpit#1695]
- git clone master branch
- follow instructions here: https://github.com/subhashc/kb/wiki/cockpit-rhel7 (starting at Step 2)
- cockpit running w/ initial kubernetes screen
- make check fails with 1 error (inline below).
There could certainly be a problem with my laptop environment -- host os is f21.

Output from make check:
......
PASS: test-fs 20 /fsdir/simple
PASS: test-fs 21 /fsdir/early-close
PASS: test-fs 22 /fsdir/watch
(<type 'exceptions.IOError'>, IOError(25, 'Inappropriate ioctl for device'), <tr
aceback object at 0x7f8a0f5ee200>)
sh: /usr/libexec/pcp/bin/pmcpp: No such file or directory
Error Parsing ASCII PMNS: pmcpp returned non-zero exit status
**
cockpit-bridge:ERROR:../src/bridge/test-metrics.c:42:init_mock_pmda: assertion f
ailed: (pmLoadNameSpace (SRCDIR "/src/bridge/mock-pmns") >= 0)
tap-gtester: listing GTest tests failed: -6
ERROR: test-metrics process failed: 250
(<type 'exceptions.IOError'>, IOError(25, 'Inappropriate ioctl for device'), <tr
aceback object at 0x7f6905ea7200>)
PASS: test-hex 1 /hex/decode-success
PASS: test-hex 2 /hex/decode-no-length
......
============================================================================
Testsuite summary for Cockpit 0.36
============================================================================
# TOTAL: 430
# PASS:  402
# SKIP:  25
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 1
============================================================================
See ./test-suite.log
Please report to devel@lists.cockpit-project.org
============================================================================
Makefile:5664: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/home/jvance/Development/cockpit/build'
Makefile:5770: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2

test-suite.log:
====================================
   Cockpit 0.36: ./test-suite.log
====================================
# TOTAL: 430
# PASS:  402
# SKIP:  25
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 1
.. contents:: :depth: 2
SKIP: pkg/base/test-base64
......
# random seed: R02Sbddac2454fdf956018f9f9dc843a797d
ok 22 /fsdir/watch

ERROR: test-metrics
===================

# ../tools/tap-driver --test-name test-metrics --log-file test-metrics.log --trs-file test-metrics.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ../tools/tap-gtester ./test-metrics
sh: /usr/libexec/pcp/bin/pmcpp: No such file or directory
Error Parsing ASCII PMNS: pmcpp returned non-zero exit status
**
cockpit-bridge:ERROR:../src/bridge/test-metrics.c:42:init_mock_pmda: assertion failed: (pmLoadNameSpace (SRCDIR "/src/bridge/mock-pmns") >= 0)
tap-gtester: listing GTest tests failed: -6

PASS: test-hex
==============
...

**Comment by stefwalter** [comment]
For now you need the 'pcp' package installed in order for the tests to pass. This code was merged last week and I've been trying to deal with the fallout @mvollmer

**Comment by mvollmer** [comment]
Let's skip the tests when the mock pmda can not be initialized.

**Comment by mvollmer** [comment]
Fixed by #1697
