### ISSUE TITLE
cockpit Software Updates doesn't seem to honour dnf (priorities)?

### ISSUE THREAD

**Issue by xpseudonym** [cockpit-project/cockpit#16971]
### Explain what happens

1. Check updates in Cockpit - see screenshot - updates reported as available:
![Screenshot from 2022-02-10 08-52-18](https://user-images.githubusercontent.com/5032475/153373834-a2a5ec4c-99f0-4f43-8fed-e4d77f67b4b2.png)
2. Check updates in dnf:
```
$ sudo dnf upgrade
[sudo] password for admin: 
Last metadata expiration check: 2:31:37 ago on Thu 10 Feb 2022 06:22:24 GMT.
Dependencies resolved.
Nothing to do.
Complete!
```
3. dnf is correct and honours priorities set in yum.repos.d; cockpit is wrong and does not honour priorities set in yum.repos.d.  See attached listing of yum.repos.d files contents - which is complex.
[yum-repos-d.txt](https://github.com/cockpit-project/cockpit/files/8039667/yum-repos-d.txt)

### Version of Cockpit

Version 251.3

### Where is the problem in Cockpit?

Software updates

### Server operating system version

Rocky Linux 8.5 (Green Obsidian)

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
That means that the priorities are evaluated by the `dnf` CLI tool, not libdnf. Cockpit doesn't (and really can't) use the `dnf` command line tool, but uses the packagekit service (which uses libdnf). So at the moment I'm afraid we can't fix this.

However, dnf 5 is working on its own dnfdaemon D-Bus service, then this has a much higher chance of getting fixed.

**Comment by xpseudonym** [comment]
I figured this would probably be an up-steam thing, no surprise packagekit squeezes in there - should it be filed against packagekit, dnf or libdnf then - or would that be just repeating what's already known?  Thx

**Comment by marusak** [comment]
As discussed above, there is nothing from our side that we can do about this. Underlying tools need to support this.
