### ISSUE TITLE
How to expose a virtual machine to the internet?

### ISSUE THREAD

**Issue by Bazimek** [cockpit-project/cockpit#16997]
### Explain what happens

I have tried everything and it does not work.

It is because of some bug in Ubuntu Server 20.04 ?

### Version of Cockpit

261-1~bpo20.04.1

### Where is the problem in Cockpit?

Networking

### Server operating system

Ubuntu

### Server operating system version

Ubuntu Server 20.04

### What browsers are you using?

Edge

**Comment by KKoukiou** [comment]
Closing in favor of https://github.com/cockpit-project/cockpit-machines/issues/569
