### ISSUE TITLE
error trying to install cockpit-pcp

### ISSUE THREAD

**Issue by x0rld** [cockpit-project/cockpit#16998]
### Explain what happens

1. I tried to install cockpit-pcp with the GUI
2. ![image](https://user-images.githubusercontent.com/45242856/153921803-25854c88-27cc-463b-b33e-70e578e0099f.png)
3. the repository contains a newer version for pcp-selinux

Is it possible to change the repo ? 
even after I installed pcp-selinux in cli with dnf it still wants to download the version who doesn't exist

### Where is the problem in Cockpit?

Software updates

### Server operating system

Fedora

### Server operating system version

35

### What browsers are you using?

Chrome

**Comment by martinpitt** [comment]
The [current pcp version](https://bodhi.fedoraproject.org/updates/?packages=pcp) is 5.3.6 from 3 weeks ago. It looks like your system had an out of date package index cache? Does it work after `pkcon refresh force`?
