### ISSUE TITLE
Historical graph controls

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1700]
* Needs zooming and panning/scrolling for the graphs
* Need to be able to turn historical data on and off

**Comment by andreasn** [comment]
Needs more specific use cases.

**Comment by andreasn** [comment]
and time indicators

**Comment by andreasn** [comment]
https://github.com/cockpit-project/cockpit/wiki/historical-performance-data contains two use cases now.

**Comment by andreasn** [comment]
http://www.highcharts.com/demo/line-time-series

**Comment by andreasn** [comment]
So this ended up to be a slight more complex interaction than I first imagined (I started with back/forward and zoom in/out, but that ended up being too flimsy and imprecise).
I tried to solve all the issues for the personas Robert and Sarah. I hope it's possible to do with what PCP and our graph libraries provides, if not, we'll have to scale back a bit.
![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/historical-data/historical-data.png)

**Comment by stefwalter** [comment]
Just saynig "Performance Data" seems a bit terse? We may need to say 'Archive performance data' or 'Store performance data'.

**Comment by dperpeet** [comment]
@stefwalter but it also shows current performance data, right? So "store" or "archive" might be misleading.

An example of the "time picker" from [NewRelic](http://newrelic.com/):
![NewRelic time picker](https://cdn.tutsplus.com/net/uploads/2014/01/03_change_time_window.png)

Here is [logic behind it](https://docs.newrelic.com/docs/apm/new-relic-apm/ui-functions/time-picker-setting-time-periods-view-data)

In my experience it is important to differentiate between a sliding window relative to now (will keep updating) or relative to a fixed position. Each has their use cases where different behavior might be annoying.

**Comment by andreasn** [comment]
The actual storing of that data goes either straight out to space or is being kept, so I'm leaning towards "Store performance data" being the more correct label.

**Comment by andreasn** [comment]
@dperpeet The NewRelic approach to this seems interesting. I certainly agree there are issues with simultaneity monitor realtime data and archive data due to the ongoing updating of data (like when you're hovering a datapoint, and Swoosh, it moved to the left!).
One issue with the popover approach used by NewRelic is that it covers the data point you're looking for. In both Sarah's and Roberts cases they are looking for the time when things went south.
I wonder if it would help to either update in chunks, so that it fills one minute at a time rather than every second (the truly realtime data you have with the %/MB/Bs/Mbps label anyway) or freeze the whole updating upon hover or interaction.

**Comment by andreasn** [comment]
This update speed isn't too jarring for example http://code.shutterstock.com/rickshaw/examples/extensions.html

**Comment by andreasn** [comment]
While this one totally is: http://canvasjs.com/html5-javascript-dynamic-chart/
Especially since it's jumping to a new datapoint even though you're not moving the cursor.

**Comment by dperpeet** [comment]
@andreasn You're right about the issues regarding the "popover" approach by NewRelic. I agree that we don't want controls to cover anything. I like the slider to easily select common ranges and the basic choice between "relative to now" and "relative to a fixed time".
The update speed in [your first link](http://code.shutterstock.com/rickshaw/examples/extensions.html) doesn't appear too jarring, until you realize the y axis keeps changing. This is very counter-intuitive while analyzing data (I think).
The thing is, which speed is acceptable will vary from user to user... that's why I like the idea of choosing the reference point.

**Comment by andreasn** [comment]
Good points! I'll keep iterating on this next week.

**Comment by andreasn** [comment]
So I've done a bunch of more iterations on paper, and one of the approaches I did was a dropdown with ending-now/running, but that's pretty much a pause button. This is very mode-ish though, and I've think we can achieve pretty much a pause, but without changing modes.
So, what if:
* Clicking (instead of hovering) an individual point brings up the details for that.
* Once clicked, the graph doesn't stop scrolling, but what it stops is pushing data to the left, instead it starts pushing data to the right so to say.
* The little [>] turns from disabled to active, indicating that there is newer data on the right. If you press this until it reaches the end, the graph starts pushing data to the left again. This could also be activated by pressing the X% label on the top.

**Comment by mvollmer** [comment]
We'll first implement this on the multi-host dashboard, no?

**Comment by stefwalter** [comment]
> We'll first implement this on the multi-host dashboard, no?

I'm working on multiple dashboard support. The Machines dashboard becomes one of them. So this doesn't block on that work.

**Comment by andreasn** [comment]
I think this one is done. Closing.
