### ISSUE TITLE
Bottom of font on Terminal page cut off when viewed on Firefox

### ISSUE THREAD

**Issue by tjakubo** [cockpit-project/cockpit#17025]
### Explain what happens

1. Open Cockpit Terminal under Firefox 97.0.1 (most recent stable at time of posting), under fresh install or Safe Mode
2. Type in characters extending down, e.g. "yellow_jello"
3. Line appears like that
![image](https://user-images.githubusercontent.com/12734857/154686453-7df8ae96-c716-4289-bb9b-26f73ac9a3c8.png)

Bottom of bracket, @ sign and y/j letters are visibly cut off. Even worse, underscore is completely invisible.
Changing font size using buttons above the terminal resizes correctly, but same problem still persists.

I tried some primitive CSS fiddling in the Inspector, but no luck.

Same thing viewed under Chrome 98.0.4758.102 seems to be OK
![image](https://user-images.githubusercontent.com/12734857/154686887-2de8677e-6cec-4eda-8fe1-5de5f2acfdd1.png)
as it appears to render a very similiar, but notably shorter on vertical axis, font

I would be very grateful if someone tried to reproduce it, or maybe has some bandaids to address this issue. Invisible underscores suck :/
It definitely wasn't happening in *some* earlier version of Firefox, but can't test that because I upgraded Cockpit to see if it will help and now it says "This web browser is too old to run the Web Console (missing replaceAll)" on my laptop with older FF installed.

Viewing system (running Firefox) info in case it is relevant:
OS: Windows 10 21H1
Display language: English (United Kingdom)

### Version of Cockpit

Version 251.3.

### Where is the problem in Cockpit?

Terminal

### Server operating system

other

### Server operating system version

Rocky Linux 8.5 (Green Obsidian), recently migrated from CentOS 8

### What browsers are you using?

Firefox

**Comment by marusak** [comment]
We did some fixes regarding spacing of terminal in version 256 (https://github.com/cockpit-project/cockpit/commit/481513e2757203f924de5e7eacc8d90d98e0c590)
Would you be able to update and check if it still happens with current versions?

I am no sure what versions rocky linux provides, but I think it might be based on centos-8 and we build preview: https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/

**Comment by garrett** [comment]
@tjakubo2: Additionally: If you're still having issues on Cockpit 256 or higher, if you could take a screenshot (without personal information) and share it, that would be great as well. Knowing what resolution your screen is and how much space Cockpit has to draw could help us recreate issues.

**Comment by marusak** [comment]
No reply, closing. Please reopen if you can provide the information requested above.
