### ISSUE TITLE
Update usage of fonts

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#17115]
We're loading multiple copies of RedHatText and RedHatDisplay.

We should, instead, only load:
- RedHatText, the variable version (so it has weights & italics in the same file too)
- RedHatMono for monospaced text
- RedHatDisplay (Although I thought it was deprecated for use in PatternFly, it seems that might not be the case? Perhaps I'm remembering a talking point about _possibly_ switching away from it in a community call.)

Additionally, when updating the fonts, we should use the new(ish) tabular number support in RedHatText, which is this somewhat-related issue:

- https://github.com/cockpit-project/cockpit/issues/15090

---

More details @ https://www.patternfly.org/v4/developer-resources/red-hat-font/

**Comment by KKoukiou** [comment]
Variable PF4 fonts are broken on firefox. See more on https://patternfly.slack.com/archives/C293LQ36J/p1670285179546349

**Comment by KKoukiou** [comment]
Tabular and updated font are now used. Variabel fonts are broken, but we don't really need these as it's just for developers confort.
