### ISSUE TITLE
users: make known groups customizable

### ISSUE THREAD

**Issue by hbrekke** [cockpit-project/cockpit#17131]
### Explain what happens

I was trying to figure out how to add another role to the user section, but I can't seem to find the documentation that states where cockpits "Roles" translates to unix groups. 

Example: Server Administrator -> sudo

### Version of Cockpit

Version 215

### Where is the problem in Cockpit?

Accounts

### Server operating system

Ubuntu

### Server operating system version

Ubuntu 20.04.4 LTS

### What browsers are you using?

Safari macOS

**Comment by marusak** [comment]
> Example: Server Administrator -> sudo

It actually translates to wheel group. There is popover that shows it. I though that your version might not have it but when I dug into history it is surely there in 215. Don't you see it or it is not clear from the content of the popup?

![Screenshot from 2022-03-14 08-43-22](https://user-images.githubusercontent.com/12330670/158130681-f951e814-b688-4601-9fc6-61eebecd98d1.png)

**Comment by marusak** [comment]
> I was trying to figure out how to add another role to the user section

What do you mean? You mean as a new feature as in https://github.com/cockpit-project/cockpit/issues/14746 ?

**Comment by hbrekke** [comment]
Perhaps, what i dosen't seem to understand is when you install some packages it altso creates a role like "image builder" or "docker manager".
What i am looking for is perhaps a json file somewhere where it's possble to add another role and link that role up to a unix group. Or perhaps some other way of achving the same thing.

I find it strange that it's not a feature but does happen.

**Comment by marusak** [comment]
I see what you mean - there is no mapping between "roles" and "groups" per se. In Cockpit we have just a few groups mapped like this - https://github.com/cockpit-project/cockpit/blob/main/pkg/users/account-roles.js#L56
If you can think of another one that would make sense, ideas are welcomed.

Adding into any group is tracked in #14746 but that will be without any "roles" it will just enable to add anyone into any group.

**Comment by hbrekke** [comment]
The way I see it cockpit isn't for users that have hundres of groups that they are defining roles to, if this is the case move to ldap or AD. And therefore there is really not a reason to implement a search for group in cockpit. Instead cockpit should check a json file for how to display roles. 
On the design of it I belive that it should not go lower than six rows with checkboxes. For the seventh it will start to add then to a secondary column on the right of the first. 
If there is more than twelve roles the thirteen and upwards will not get displayed and would be ignored by the module.

```
{   "accounts": {
        "roles": [
            {
            "rolename":"Server administrator",
            "order":"1",
            "unix-group":"wheel",
            "standard":false
            },
            {
            "rolename":"Container administrator",
            "order":"2",
            "unix-group":"docker",
            "standard":false
            
            },
            {
            "rolename":"Image builder",
            "order":"3",
            "unix-group":"weldr",
            "standard":false
            },
            {
            "rolename":"File Access",
            "order":"4",
            "unix-group":"myFileAccessGroup",
            "standard":true
            }
        ]
    }
    
}
```
Wrote the json as if the file is going to define some other options under the accounts tab. 
What is your thoughts on this as a concept?

**Comment by martinpitt** [comment]
Indeed we need to show the group name in the UI, it's just too confusing. Especially as "container" is much more generic than just "Docker" these days -- there's "nspawn" and "podman" and half a dozen other things (they don't have their own groups, though).

I like the idea of pulling this mapping out of the code, so that admins can customize it. We should still have a builtin default which doesn't require reading a file on the target system (i.e. JSON file baked into the webpack), but we should support an override.

**Comment by martinpitt** [comment]
Err, nevermind, we already have the popover for the group name, so using this issue for the customization.

**Comment by KKoukiou** [comment]
This issue is now obsolete as we removed the 'Roles' checkboxes in favor of the new 'Group' typeahead select.
