### ISSUE TITLE
Manifest overwrite: one file to rule them all

### ISSUE THREAD

**Issue by hbrekke** [cockpit-project/cockpit#17153]
There should be only one overwrite file placed in `/etc/cockpit` or `~/.config/cockpit`. This new file will start by defining the unix-group, if a user with that group log in they get that set of overwrite rules - if any. If you want to keep the overwrite rule for all users you can use the `*` as a representation of all groups.

Example:
```
{
    "groups":[
       {
          "unix-group":"wheel",
          "group-priorety":"100",
          "overwrites":{
             "menu":{
                "services":{
                   "order":-1
                }
             },
             "systemd":{
                "version":"215",
                "name":"system"
             }
          }
       },
       {
          "unix-group":"*",
          "group-priorety":"50",
          "overwrites":{
             "menu":{
                "logs":null,
                "storage":null,
                "networking":null,
                "accounts":null,
                "applications":null,
                "software-updates":null
             }
          }
       }
    ]
 }
```

This will mainly enable the possibility to set certain rules for certain groups, thoughts on this as a concept?

**Comment by martinpitt** [comment]
https://cockpit-project.org/blog/cockpit-265.html introduced /etc/cockpit/*package*.override.json and ~/.config/cockpit/*package*.override.json, which made overrides a lot more useful.

But we are not going to implement the "groups" thing, this is deviating too much from the usual Linux config schema and too complex/error prone to implement.
