### ISSUE TITLE
Can a Administrative Access be enabled by default?

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/cockpit#17162]
i see that each time a user logs into cockpit they have to enable administrative access, is there a way to configure that so it would be on by default?

**Comment by marusak** [comment]
It should be remembered in a local storage. And it surely is working for me - that when I log in I already have administrative access.

Can you please provide more information, like what version of cockpit are you using, on what OS, what browser. Are you using by any chance cockpit client (the flat pack application?)

**Comment by emaayan** [comment]
i have no idea what's cockpit client (or flat pack application) i'm using cockpit 2.65 on ubuntu 20.04.04

**Comment by marusak** [comment]
Any information about browser? Are you using private browsing for any chance or have any plugin which would block local browser storage?

Would you be able to inspect local storage in your browser and see if there is any entry for your user:
![Screenshot from 2022-03-22 07-41-11](https://user-images.githubusercontent.com/12330670/159422854-de8ebd99-42e4-48c9-b5c4-a2fb168e95a3.png)

**Comment by emaayan** [comment]
i see now that administrative access is preserved, thanks (sorry, i was using packer to create an OVA containing cockpit by default, and got turned around,
