### ISSUE TITLE
Installing cockpit-pcp (from web) removes the per service metrics on memory and cpu tabs 

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/cockpit#17171]
### Explain what happens

1.  go to performance metrics 
2.  verify the percentages for each service are displayed in real time 
3.  click on install cockpit-pcp 
4.  logout 
5. log in
6. go to performance metrics
![after-pcp](https://user-images.githubusercontent.com/13434544/159690036-b7574be9-a491-406b-bc84-c08e51d2feab.png)
![before-pcp](https://user-images.githubusercontent.com/13434544/159690060-5b81e32a-3c82-4520-96fa-a6c4574a2919.png)

while investigating this, i believe i know the cause, i've installed cockpit from focal-backports. 
but the web-console installs cockpit-pcp from the default repo which is version 2.15 
thus you have different versions of components being installed.. 

### Version of Cockpit

264-1~bpo20.04.1

### Where is the problem in Cockpit?

Metrics

### Server operating system

Ubuntu

### Server operating system version

20.04.04

### What browsers are you using?

Chrome

**Comment by martinpitt** [comment]
Does this work properly if you install cockpit-pcp from backports as well? That's not clear from the above description.

If so, let's just make the dependencies tighter.

**Comment by marusak** [comment]
This seems like mixing very old cockpit-pcp with new cockpit metrics page. Not much actionable items here. Please install newer version and if the issues persist please reopen.
