### ISSUE TITLE
services: Changed rows show up with a "new" animation (but shouldn't)

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#17189]
In the Services page, when rows change state, they show up with a new animation.

The new animation should be reserved for new items. As the services exist on disk and are not new, they shouldn't animate as though they are.

This can also be triggered by doing a search, including clearing a search.

**Comment by KKoukiou** [comment]
Fixed with https://github.com/cockpit-project/cockpit/commit/788fd124facb4f33291af0b573c5a095cae6bdd1
