### ISSUE TITLE
Time axis not lining up with real cpu activity on Raspberry Pi 4 with Buster

### ISSUE THREAD

**Issue by waterwin** [cockpit-project/cockpit#17212]
### Explain what happens

1. Start using cockpit on RPi4
2. Look at the activity screen (5 minutes interval) 
3. Load the cpu with a process running at least 100% for a few seconds
4. See the x-axis legend (time) become out of line for the 4 items. The main cpu activity starts at exactly the even minutes 0-2-4 etc
![cockpit-x-axisl](https://user-images.githubusercontent.com/21102829/161420072-d14893f2-7306-40ff-b628-07a9d2c8f367.png)

### Version of Cockpit

v. 188

### Where is the problem in Cockpit?

Overview

### Server operating system

other

### Server operating system version

Raspbian Buster

### What browsers are you using?

Chrome

**Comment by marusak** [comment]
Thank you for the report!
However version 188 is very very old - released 20 Feb 2019. We are currently on version 266. The overview does not look anything like this anymore but mainly those graphs are not there anymore. We won't be able therefore to do anything about this.

You might try to update to newer version from backports - https://cockpit-project.org/running.html#debian

**Comment by waterwin** [comment]
It looks as if that does not work:sudo apt install -t ${VERSION_CODENAME}-backports cockpit
Reading package lists... Done
E: The value 'buster-backports' is invalid for APT::Default-Release as such a release is not available in the sources
So the Raspbian Buster software still has a very old cockpit that appears not to be maintained by the Raspbian team.

    On Monday, April 4, 2022, 08:35:19 AM GMT+2, Matej Marusak ***@***.***> wrote:  
 
 


Thank you for the report!
However version 188 is very very old - released 20 Feb 2019. We are currently on version 266. The overview does not look anything like this anymore but mainly those graphs are not there anymore. We won't be able therefore to do anything about this.

You might try to update to newer version from backports - https://cockpit-project.org/running.html#debian

**Comment by martinpitt** [comment]
@waterwin Did you actually do step 1 to define the buster-backports repo?

```
. /etc/os-release
echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-backports main" > \
    /etc/apt/sources.list.d/backports.list
apt update
```

**Comment by waterwin** [comment]
Yes; using that repo runs into difficulties generating the keychain as no keyserver is available which is another Raspbian related issue. So the quest for a working solution continues.

    On Monday, April 4, 2022, 10:47:28 AM GMT+2, Martin Pitt ***@***.***> wrote:  
 
 


@waterwin Did you actually do step 1 to define the buster-backports repo?
. /etc/os-release
echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-backports main" > \
    /etc/apt/sources.list.d/backports.list
apt update

**Comment by waterwin** [comment]
The value 'buster-backports::main' is invalid for APT::Default-Release as such a release is not available in the sources

    On Monday, April 4, 2022, 10:47:28 AM GMT+2, Martin Pitt ***@***.***> wrote:  
 
 


@waterwin Did you actually do step 1 to define the buster-backports repo?
. /etc/os-release
echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-backports main" > \
    /etc/apt/sources.list.d/backports.list
apt update

**Comment by waterwin** [comment]
Installed version on Raspbian Buster now 239 ... detailed metrics page stays empty

On my Imac running Ubuntu : Cockpit 252-1 is installed ... detailed metrics page has detailed graphs running actively
Does this mean the buster-backport can only install a (too old) version as well?


    On Monday, April 4, 2022, 10:47:28 AM GMT+2, Martin Pitt ***@***.***> wrote:  
 
 


@waterwin Did you actually do step 1 to define the buster-backports repo?
. /etc/os-release
echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-backports main" > \
    /etc/apt/sources.list.d/backports.list
apt update

**Comment by garrett** [comment]
Raspbian Buster came out in the middle of 2019 (almost 3 years ago). You might want to consider upgrading your version to Raspberry Pi OS (the new name of Raspbian) Bullseye, the latest version.

https://www.raspberrypi.com/software/operating-systems/

It woud have a newer version of Cockpit, although it still wouldn't be the latest one.

Using backports with Raspbian / Raspberry Pi OS doesn't work very well. (I've tried it with Buster several months ago.) It's different enough from Debian that it has some issues.

You'd want to run Debian, Ubuntu, Fedora, or some other OS on your Pi other than Raspberry Pi OS to get the best Cockpit experience.

Meanwhile, consider Raspbian to Raspberry Pi OS (and set your expectations to running an older version of everything, including Cockpit) if you don't want to switch to a different OS.

**Comment by garrett** [comment]
> Moving away from Buster at the moment is no good as some other software for primary use of the Raspberry Pi is not available on Bullseye yet. We are just finalizing an alpha release on Buster before porting this to Bullseye.

You could consider Debian Buster instead of Raspbian Buster and then use backports (including Cockpit) properly. Raspbian's changes from Debian are mainly desktop-specific, and as you're running Cockpit, I'm assuming this is for a server.

https://raspi.debian.net/

This would allow you to have a much more recent Cockpit on your Raspberry Pi and keep using Buster with the other software that needs it.

If you go the route of changing the base OS, I suggest doing so on another SD card and keeping this one around, unmodified, so you have something to go back to. Ideally, you'd do installation on a secondary Pi, but not everyone has one of those, especially since the prices are sky high at the moment — they're around 3 times the price here as what they should be!

(Alternatively: Podman containers with the software that needs Buster in a container, letting you run newer software on the host. But that requires a lot more work and is extremely outside the scope of this discussion.)

**Comment by waterwin** [comment]
The tested releases for Debian on Raspi are Bookworm and Bullseye. Which are both past Buster. That would mean no difference from getting our sw working on Raspbian Bullseye.
Thanks for all the suggestions and support.

    On Monday, April 4, 2022, 02:56:16 PM GMT+2, Garrett LeSage ***@***.***> wrote:  
 
 



Moving away from Buster at the moment is no good as some other software for primary use of the Raspberry Pi is not available on Bullseye yet. We are just finalizing an alpha release on Buster before porting this to Bullseye.


You could consider Debian Buster instead of Raspbian Buster and then use backports (including Cockpit) properly. Raspbian's changes from Debian are mainly desktop-specific, and as you're running Cockpit, I'm assuming this is for a server.

https://raspi.debian.net/

This would allow you to have a much more recent Cockpit on your Raspberry Pi and keep using Buster with the other software that needs it.

If you go the route of changing the base OS, I suggest doing so on another SD card and keeping this one around, unmodified, so you have something to go back to. Ideally, you'd do installation on a secondary Pi, but not everyone has one of those, especially since the prices are sky high at the moment — they're around 3 times the price here as what they should be!

(Alternatively: Podman containers with the software that needs Buster in a container, letting you run newer software on the host. But that requires a lot more work and is extremely outside the scope of this discussion.)

**Comment by waterwin** [comment]
Had to do the steps from the below first:
How to add buster-backports to a Raspberry Pi | Jack Stromberg

| 
| 
|  | 
How to add buster-backports to a Raspberry Pi | Jack Stromberg


 |

 |

 |


Especially the command sudo bash helped me here; followed by adding the keys.





    On Monday, April 4, 2022, 10:47:28 AM GMT+2, Martin Pitt ***@***.***> wrote:  
 
 


@waterwin Did you actually do step 1 to define the buster-backports repo?
. /etc/os-release
echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-backports main" > \
    /etc/apt/sources.list.d/backports.list
apt update
