### ISSUE TITLE
Cockpit Client will not open Fedora 35

### ISSUE THREAD

**Issue by limedawg99** [cockpit-project/cockpit#17211]
### Explain what happens

1. When installed via flat hub client will not launch if launched directly from applications menu
2. If lunched from GNOME software (I am running version 41.5) where I installed it from it works
3. no errors display just does not work
4. Fedora 35: 5.16.18-200.fc35.x86_64 is my current build.

### Version of Cockpit

266

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Fedora

### Server operating system version

35

### What browsers are you using?

Cockpit Client / Cockpit Desktop

### System log

```shell
app-flatpak-org.cockpit_project.CockpitClient-27429.scope: Consumed 26min 9.157s CPU time.
nome-shell[2353]: JS ERROR: Error: Expected an object of type ClutterActor for argument 'sibling' but got type undefined
                  _syncStacking@resource:///org/gnome/shell/ui/workspaceAnimation.js:80:18
nome-shell[2353]: JS ERROR: TypeError: record is undefined
                  _syncStacking@resource:///org/gnome/shell/ui/workspaceAnimation.js:80:13
nome-shell[2353]: JS ERROR: Error: Expected an object of type ClutterActor for argument 'sibling' but got type undefined
                  _syncStacking@resource:///org/gnome/shell/ui/workspaceAnimation.js:80:18
nome-shell[2353]: JS ERROR: TypeError: record is undefined
                  _syncStacking@resource:///org/gnome/shell/ui/workspaceAnimation.js:80:13
```

**Comment by martinpitt** [comment]
Can you please open a Terminal, and start it from there?

    flatpak run org.cockpit_project.CockpitClient

If it fails as well, please copy&paste error messages. I'm afraid the messages that you sent are not that useful -- they are errors from GNOME shell, and the Cockpit client has already exited.

**Comment by limedawg99** [comment]
Sorry about that the output is below. Interestingly the client does appear to function if the script you gave me is run directly. But not if launched from the applications menu.

Gtk-Message: 09:14:52.605: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:14:52.605: Failed to load module "pk-gtk-module"
Gtk-Message: 09:14:53.197: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:14:53.197: Failed to load module "pk-gtk-module"
Gtk-Message: 09:14:53.199: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:14:53.199: Failed to load module "pk-gtk-module"

**Comment by limedawg99** [comment]
Fedora pushed an OS update that added the missing gtk dependency. Cockpit client now functions as expected.
