### ISSUE TITLE
Cockpit Doesn't Recognize Root FS Mounted Via Kernel Command Line Only

### ISSUE THREAD

**Issue by BrainwreckedTech** [cockpit-project/cockpit#17231]
### Explain what happens

1. Make sure the `root*` kernel command line parameters are used to mount the rootfs.
2. Remove rootfs mount in `/etc/fstab` if present.
3. Reboot if changes were made.

The kernel command line in use on my Pi from `/proc/cmdline`:
```
root=PARTUUID=642e064b-02 rootfstype=btrfs rootflags=noatime,compress-force=zstd rootwait rw loglevel=4 cosnoleblank=0 net.ifnames=0 ipv6.disable=1 smsc95xx.macaddr=[redacted]
```

This results in the :warning: symbol showing up for the storage device.  Drilling down shows the issue Cockpit thinks is at play:

![Screenshot_20220408_155633-1](https://user-images.githubusercontent.com/3752022/162519632-3147c260-b290-4c24-8523-527e4641ed38.png)

IIRC systemd recommends using kernel command line parameters to mount the rootfs and not to do so in `/etc/fstab` since doing both results in the root filesystem being mounted twice.

Side note:  Offering to unmount root is probably A Bad Idea:tm: and should probably be avoided.

### Version of Cockpit

266-1

### Where is the problem in Cockpit?

Storage

### Server operating system

Arch Linux

### Server operating system version

rolling

### What browsers are you using?

Chrome

**Comment by mvollmer** [comment]
@BrainwreckedTech, is there a systemd mount unit for "/"?  What does `systemctl cat -- -.mount` say?

**Comment by mvollmer** [comment]
> Offering to unmount root is probably A Bad Ideatm and should probably be avoided.

Unmounting will never succeed, so Cockpit offering it is not really dangerous. Unmounting any filesystem might be  Bad Idea, so I am reluctant to make "/" a special case.

**Comment by mvollmer** [comment]
> IIRC systemd recommends using kernel command line parameters to mount the rootfs and not to do so in `/etc/fstab` since doing both results in the root filesystem being mounted twice.

Makes sense to me.  I'll change Cockpit not to issue any warnings about the rootfs, on the assumption that Cockpit doesn't have enough information to do a good job of it.

**Comment by BrainwreckedTech** [comment]
> @BrainwreckedTech, is there a systemd mount unit for "/"? What does `systemctl cat -- -.mount` say?

```
$ systemctl list-units --type=mount
  UNIT                          LOAD   ACTIVE SUB     DESCRIPTION                     
  -.mount                       loaded active mounted Root Mount
  boot.mount                    loaded active mounted /boot
  dev-hugepages.mount           loaded active mounted Huge Pages File System
  dev-mqueue.mount              loaded active mounted POSIX Message Queue File System
...
```

**Comment by mvollmer** [comment]
> > @BrainwreckedTech, is there a systemd mount unit for "/"? What does `systemctl cat -- -.mount` say?
> 
> ```
> $ systemctl list-units --type=mount
>   UNIT                          LOAD   ACTIVE SUB     DESCRIPTION                     
>   -.mount                       loaded active mounted Root Mount

Thanks! Could you also show `systemctl status -- -.mount`? I am interested in whether systemd can tell us where the mount point is defined.

**Comment by BrainwreckedTech** [comment]
> Thanks! Could you also show `systemctl status -- -.mount`? I am interested in whether systemd can tell us where the mount point is defined.

Very late on my part, but

```
# systemctl status -- -.mount
● -.mount - Root Mount
     Loaded: loaded
     Active: active (mounted) since Fri 2022-06-03 08:59:25 EDT; 1 week 4 days ago
      Until: Fri 2022-06-03 08:59:25 EDT; 1 week 4 days ago
      Where: /
       What: /dev/mmcblk0p2

Notice: journal has been rotated since unit was started, output may be incomplete.
```
