### ISSUE TITLE
NFS dialog sometimes does not show error message (TestStorageNfs.testNfsClient)

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#17259]
[Example failure on f35/firefox](https://logs.cockpit-project.org/logs/pull-17255-20220415-174440-8c102764-fedora-35-firefox/log.html), [example failure on PackIt](https://bodhi.fedoraproject.org/updates/FEDORA-2022-70c1d3d182)

In #17258 it also failed on our own CI in [c8s](https://logs.cockpit-project.org/logs/pull-17258-20220419-033103-417fbe13-centos-8-stream/log.html#206) and [r90](https://logs.cockpit-project.org/logs/pull-17258-20220419-033103-417fbe13-rhel-9-0/log.html#206), so it's not specific to Firefox either. I can't reproduce locally.

The dialog action seems to happen, as the journal says

    rpc.mountd[10213]: refused mount request from 127.0.0.1 for /usr/share (/): not exported

and the test log says

    > warning: mount.nfs: mounting 127.0.0.1:/usr/share failed, reason given by server: No such file or directory

So this is an actual bug in that dialog, it does not always pick up the error message.

As this is in main, and breaks everything, I land this with red (with a heavy heart). I'll split this out into a new issue.

_Originally posted by @martinpitt in https://github.com/cockpit-project/cockpit/issues/17255#issuecomment-1102055671_

**Comment by mvollmer** [comment]
The `dlg.set_options` call resets all errors in a dialog.  Thus there is likely a race between updating the combobox and runing the actual action of the dialog. I'll make sure.
