### ISSUE TITLE
Uninstalling cockpit-session-recorder uninstalls required library

### ISSUE THREAD

**Issue by millerthegorilla** [cockpit-project/cockpit#17274]
### Explain what happens

1. Install cockpit and all the fedora available extensions.
2. Uninstall cockpit-session-recorder
3. Error occurs with service failing to start   ```pmlogger_daily failed - see /var/log/pcp/pmlogger/pmlogger_daily-K.log```

The service fails because the tlog package gets removed when uninstalling session-recorder.
Installing the package tlog allows the service to function correctly.

### Version of Cockpit

266

### Where is the problem in Cockpit?

Services

### Server operating system

other

### Server operating system version

coreos

### What browsers are you using?

Firefox

### System log

```shell
this is the service fail log from cockpit.  With session-recorder installed the service runs fine, and when I uninstall session-recorder it removes tlog, which is necessary for this service to function.  Installing tlog, solves the issue.

pcp
pmlogger_daily failed - see /var/log/pcp/pmlogger/pmlogger_daily-K.log

PRIORITY
    3
SYSLOG_FACILITY
    3
SYSLOG_IDENTIFIER
    pcp
SYSLOG_TIMESTAMP
    Apr 21 16:25:01 
_BOOT_ID
    d1c1fece5e3f41a39f6ba9aa28943b86
_GID
    977
_HOSTNAME
    ceramicisles.local
_MACHINE_ID
    7f89001753614e2a83b08503d9c5bda1
_PID
    2519824
_SELINUX_CONTEXT
    system_u:system_r:unconfined_service_t:s0
_SOURCE_REALTIME_TIMESTAMP
    1650558301449386
_TRANSPORT
    syslog
_UID
    977
__CURSOR
    s=e635eab771784a7eb34cdab997820d87;i=9006;b=d1c1fece5e3f41a39f6ba9aa28943b86;m=1435bb6851;t=5dd2c8d3d2cd0;x=657991e67c94f57c
__MONOTONIC_TIMESTAMP
    86800820305
__REALTIME_TIMESTAMP
    1650558301449424
```

**Comment by martinpitt** [comment]
Hello @millerthegorilla! Please file this against the Fedora pcp package on https://bugzilla.redhat.com/ . This is between the pcp and tlog packages (and I don't know what's going on, this needs the pcp logs).

**Comment by marusak** [comment]
Thanks for the report, but this is surely not cockpit issue, let me put down a few thoughts.
- If pmlogger really needs tlog to function, then it needs to depend on it. If it would depend on it, then removing cockpit-s-r would not remove tlog as there would be another depending package installed. If that is the case, then it needs to be reported to pcp
- You haven't provided content of `/var/log/pcp/pmlogger/pmlogger_daily-K.log` what is really happening, but I __think__ that just restarting `pmlogger_daily.service` would do the trick. Have you tried restarting it or could you then provide content of this file?
- If it is real issue with cockpit-s-r (which I am not yet convinced it is, as it does nothing wrong, just has defined dependency) then it should be reported in https://github.com/Scribery/cockpit-session-recording

**Comment by millerthegorilla** [comment]
I tried restarting the service but to no avail, and yes I think you are correct
This is an issue with PCP, as it should declare tlog as a dependency if that is actually the case.
Should I report this elsewhere then?
