### ISSUE TITLE
client: Support light & dark mode

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#17283]
It'd be great if Cockpit Client has support for desktop light and dark mode settings, corresponding to Cockpit's own light/dark mode settings (#10189).

**Comment by garrett** [comment]
### Web docs

- https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

### App docs

- https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Settings
- https://docs.gtk.org/gtk3/property.Settings.gtk-application-prefer-dark-theme.html
- https://docs.gtk.org/gtk4/property.Settings.gtk-application-prefer-dark-theme.html

### WebKit

- https://webkit.org/blog/8840/dark-mode-support-in-webkit/
- https://blogs.gnome.org/mcatanzaro/2020/03/
- https://trac.webkit.org/changeset/255342/webkit
- https://bugs.webkit.org/show_bug.cgi?id=197947

### Testing

- GNOME Shell extension, Night Theme Switcher: https://extensions.gnome.org/extension/2236/night-theme-switcher/
- GNOME Web extension, Dark Mode: https://github.com/GNOME-Web-Extensions/Dark-Mode
- Color Scheme Simulator: https://gitlab.gnome.org/exalm/color-scheme-simulator

**Comment by garrett** [comment]
It probably makes sense to move to "libadwaita" (the new GNOME style) at the same time. However, it does depend on GTK4, so it's probably not quite as simple, and might need to be handled in a different PR.

But libadwaita does handle light/dark modes and even lets you specify a color, which means we could even use the host color per machine.

Cockpit Client would look something like this:

![image](https://user-images.githubusercontent.com/10246/165319983-3354e324-4402-45f6-bc70-719829171533.png)

And in dark mode:

![image](https://user-images.githubusercontent.com/10246/165320066-1b15082a-f7d8-4333-8c95-f1b09d3ba0ff.png)

Since there are different host colors, we might even want to pull some of that into the titlebar:

![image](https://user-images.githubusercontent.com/10246/165320232-101c180a-0fa6-4388-9da0-3efdcff8d852.png)

Similar to what a lot of new GNOME apps that use libadwaita are doing, such as GNOME Builder, Text Editor, GNOME Console, Amberol, and NoteJot are all doing.

Here's Text Editor in light and dark modes, with the Solarized theme selected:

![image](https://user-images.githubusercontent.com/10246/165320853-85812c43-a93f-4023-91d9-01cea327815e.png)

![image](https://user-images.githubusercontent.com/10246/165320804-d39baaa7-5322-4768-8f00-2a542b6df69d.png)

It works for other schemes too, like Cobalt (here it is in the light mode):

![image](https://user-images.githubusercontent.com/10246/165321204-b9571e58-9afb-445f-b34a-0bc0563785b3.png)

**Comment by allisonkarlitskaya** [comment]
PR'd in #17321.

**Comment by jelly** [comment]
Dark mode is now merged!
