### ISSUE TITLE
Duplicate interface names present while creating Firewall Zones through Cockpit GUI

### ISSUE THREAD

**Issue by aburmash** [cockpit-project/cockpit#17280]
### Explain what happens

1. Try creating firewalls zones through cockpit UI while having multiple interfaces on the system
2.  notice that some of them are listed twice
3. that does not seem to be correct
Note: issues is reproducible only if there is an interface with capabilities per dbus reports >= 7

I had a quick look at cockpit code and i think this piece might be a problem.
https://github.com/cockpit-project/cockpit/blob/main/pkg/networkmanager/firewall.jsx#L727
Here is a sample interface list:
On that exact machine for example :
Last digit is capabilites as it is reported by dbus:
```

/org/freedesktop/NetworkManager/Devices/2 eno1 /sys/devices/pci0000:00/0000:00:1c.4/0000:02:00.0/net/eno1 00:10:E0:D8:27:14 100 1 1 3
/org/freedesktop/NetworkManager/Devices/5 enp59s0f0 /sys/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.0/net/enp59s0f0 3C:FD:FE:57:9D:C0 20 1 1 11
/org/freedesktop/NetworkManager/Devices/6 enp59s0f1 /sys/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.1/net/enp59s0f1 3C:FD:FE:57:9D:C1 20 1 1 11
/org/freedesktop/NetworkManager/Devices/7 enp59s0f2 /sys/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.2/net/enp59s0f2 3C:FD:FE:57:9D:C2 20 1 1 11
/org/freedesktop/NetworkManager/Devices/8 enp59s0f3 /sys/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.3/net/enp59s0f3 3C:FD:FE:57:9D:C3 20 1 1 11

```

All devices with capabilities 11 will be displayed twice. 
basically 11 matches `i => i.capabilities >= 7` for Virtual Devices
and at the same time it matches` i.capabilities < 5 || i.capabilities > 7`
So same exact device gets into both virtual device and physical device and is listed twice here - https://github.com/cockpit-project/cockpit/blob/main/pkg/networkmanager/firewall.jsx#L786

Being honest i was not able to find any relevant comments concerning what virtual and physical devices should represent there, but i SUPPOSE that according to https://developer-old.gnome.org/NetworkManager/stable/nm-dbus-types.html#NMDeviceCapabilities
virtual should be actually 5 & 7, so  `i.capabilities >=5 &&  i.capabilities <=7` ( fine with 6 being there as well )

### Version of Cockpit

264

### Where is the problem in Cockpit?

Firewall

### Server operating system

other

### Server operating system version

Oracle Linux 8.5

### What browsers are you using?

Chrome

**Comment by jelly** [comment]
Thanks for reporting the issue, the issue is indeed that we are not filtering virtual/physical devices correctly. The opened PR should resolve your issue.
