### ISSUE TITLE
tools/tap-driver can hang on unclean test exit

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#17307]
### Explain what happens

The main loop for polling and reading from stout/stderr in the tap driver doesn't consider the exit of the test process.  That means that if either of stderr or stdout have been leaked to another process, and that process is still running, then the tests can hang indefinitely.

In practice, this can be observed with the `test-tls-server` test by listening on port 9123 and running `make check`:

```
$ socat - TCP-LISTEN:9123&
$ make check
```

which will hang, with the `timeout` invocation as a zombie and `tap-driver` stuck waiting on reading log output from the forked-off `socket-activation-helper` which will never exit.

There are a few possibilities for a workaround here.

 - we might be able to figure out a way to get timeout to take down the entire session when the parent exits
 - we could ensure that we clean up the socket activation helper, even if the testcase exits uncleanly.  `PR_SET_PDEATHSIG` could help.
 - we could modify `tools/tap-driver` to be more robust: on exit of the primary testing process, we could drain the stdout/stderr and exit immediately.

Doing a one-off fix of the launching of the socket activation helper would be the easiest way to fix this, but this is just one possible instance of what is a sufficiently general problem.  In my opinion, once the primary test process has exited, the test is definitively finished, and the tap driver shouldn't hang around much longer...

**Comment by allisonkarlitskaya** [comment]
More concretely, fixing the problem from the tap driver could take a few different approaches:
 - switch to a polling-based design and check for the child process having exited
 - try to capture SIGCHLD somehow
 - use a pidfd or something
 - maybe see if `subprocess.communicate()` does the right thing here (at the cost of realtime log output)

**Comment by allisonkarlitskaya** [comment]
My current line of thinking is moving closer to "delete the whole thing".  The reasons are:
 - the default automake (non-TAP) driver produces far less verbose output.  One line per executable.  I consider that ideal for the passing case: our logs are very verbose, and difficult to find failures in.
 - the results for the failing cases are neatly deposited in the `test-suite.log` file, which we can display after-the-fact in case of failure.  Wiring this into `make check` turns out to be almost impossible, but we could define our own target, or just make sure the relevant workflows show the log in case it's required.  In any case: seeing only the logs of the failing tests, neatly at the end, would make it far easier to find what you're looking for
 - GLib doesn't really support TAP properly anyway: we define that we're going to run 20 tests (or whatever) in this executable, but then when we hit an assertion in the first one, we bomb out immediately.  The exit code is what's really important here (plus the logs) and this is well supported by the default driver
 - as per this issue, our TAP driver contains difficult-to-fix bugs, and is a non-trivial piece of code.  It's always nice to remove complexity.

Thoughts?

**Comment by martinpitt** [comment]
For the record: I don't care about the unit test TAP output at all. Nothing uses/parses that. We only need it for the integration tests.
