### ISSUE TITLE
Broken layout on network interface details

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#17318]
### Explain what happens

1. Visit network interface
2. Add member if there is none
3. Resize the window size so member details starts to wrap. Notice how the minus button become too big and is not spaced with regards to the switch

![Screenshot from 2022-05-05 15-38-07](https://user-images.githubusercontent.com/12330670/166936232-91740fdd-4bc6-4aee-818f-e1be01bdac44.png)

### Version of Cockpit

main

### Where is the problem in Cockpit?

Networking

**Comment by garrett** [comment]
Ah, this is yet another issue with the mobile layout in PF where it stretches the content to fit.

The solution is to not have it set to stretch for that item _or_ to add a level, such as a form element group of some sort, even if it's one item. (We added a "label" group before for the "labels" that are really badges by other names (not HTML form labels).)

However, it's kind of odd to have the remove button be where it is here in mobile too.
