### ISSUE TITLE
lint css via webpack

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#17329]
We should probably add in some sort of linting for our CSS.

This would warn people when they try to use bad CSS practices, which would solve some headaches and me manually pointing out some of the issues. :wink: 

This post has details on the concept and suggests stylelint (it should be pointed out that it's a little biased, as it's from the author of stylelint):
https://css-tricks.com/stylelint/

But stylelint _does_ look good and it does have webpack integration and does also support SASS (SCSS):

- https://stylelint.io/
- https://webpack.js.org/plugins/stylelint-webpack-plugin/
- https://www.npmjs.com/package/stylelint-webpack-plugin

We'll probably have to introduce it with some relaxed rules at first and then tighten it up over time as we make fixes across the codebases.

**Comment by garrett** [comment]
@martinpitt: As this is both webpack and CSS related, it's probably a matter of you and me working on this together, most likely?

(And to anyone else who might be reading this who wants to take it on instead: You're more than welcome to do so!)

**Comment by martinpitt** [comment]
PR #17471 laid the foundation for this (just landed). Now we can resurrect PR #17408 and land this piece by piece.

**Comment by jelly** [comment]
Auto fixing rules to appy in future pull requests:

- [ ] 
- [ ] I found all the autofixing rules according to the documentation, made a template file that disabled all the rules (after importing the base ones) and wrote a 1-liner loop for fish shell (the shell I use) that iterated through the listing of the commands, excluded the line from the template file, ran stylelint with the custom config with --fix, and did a git commit with a basic summary.
- [ ] 
- [ ] Fish loop:
- [ ] 
- [ ] for i in (cat autorules); echo $i; grep -v \"$i\" stylelint-template.json > rules.json; npx stylelint --config rules.json --fix "pkg/**/*.*css"; git commit -a -m "stylelint: $i"; end
- [ ] Template to turn off things:
- [ ] 
- [ ] {
- [ ]   "extends": "stylelint-config-standard-scss",
- [ ]   "rules": {
- [ ] 	"alpha-value-notation": null,
- [ ] 	"at-rule-empty-line-before": null,
- [ ] 	"at-rule-name-case": null,
- [ ] 	"at-rule-name-space-after": null,
- [ ] 	"at-rule-no-vendor-prefix": null,
- [ ] 	"at-rule-semicolon-newline-after": null,
- [ ] 	"block-closing-brace-empty-line-before": null,
- [ ] 	"block-closing-brace-newline-after": null,
- [ ] 	"block-closing-brace-newline-before": null,
- [ ] 	"block-closing-brace-space-before": null,
- [ ] 	"block-opening-brace-newline-after": null,
- [ ] 	"block-opening-brace-newline-before": null,
- [ ] 	"block-opening-brace-space-after": null,
- [ ] 	"block-opening-brace-space-before": null,
- [ ] 	"color-function-notation": null,
- [ ] 	"color-hex-case": null,
- [ ] 	"color-hex-length": null,
- [ ] 	"comment-empty-line-before": null,
- [ ] 	"comment-whitespace-inside": null,
- [ ] 	"custom-property-empty-line-before": null,
- [ ] 	"declaration-bang-space-after": null,
- [ ] 	"declaration-bang-space-before": null,
- [ ] 	"declaration-block-semicolon-newline-after": null,
- [ ] 	"declaration-block-semicolon-space-after": null,
- [ ] 	"declaration-block-semicolon-space-before": null,
- [ ] 	"declaration-block-trailing-semicolon": null,
- [ ] 	"declaration-colon-newline-after": null,
- [ ] 	"declaration-colon-space-after": null,
- [ ] 	"declaration-colon-space-before": null,
- [ ] 	"declaration-empty-line-before": null,
- [ ] 	"font-family-name-quotes": null,
- [ ] 	"function-comma-newline-after": null,
- [ ] 	"function-comma-newline-before": null,
- [ ] 	"function-comma-space-after": null,
- [ ] 	"function-comma-space-before": null,
- [ ] 	"function-max-empty-lines": null,
- [ ] 	"function-name-case": null,
- [ ] 	"function-parentheses-newline-inside": null,
- [ ] 	"function-parentheses-space-inside": null,
- [ ] 	"function-whitespace-after": null,
- [ ] 	"hue-degree-notation": null,
- [ ] 	"indentation": null,
- [ ] 	"length-zero-no-unit": null,
- [ ] 	"linebreaks": null,
- [ ] 	"max-empty-lines": null,
- [ ] 	"media-feature-colon-space-after": null,
- [ ] 	"media-feature-colon-space-before": null,
- [ ] 	"media-feature-name-case": null,
- [ ] 	"media-feature-name-no-vendor-prefix": null,
- [ ] 	"media-feature-parentheses-space-inside": null,
- [ ] 	"media-feature-range-operator-space-after": null,
- [ ] 	"media-feature-range-operator-space-before": null,
- [ ] 	"media-query-list-comma-newline-after": null,
- [ ] 	"media-query-list-comma-space-after": null,
- [ ] 	"media-query-list-comma-space-before": null,
- [ ] 	"no-empty-first-line": null,
- [ ] 	"no-eol-whitespace": null,
- [ ] 	"no-extra-semicolons": null,
- [ ] 	"no-missing-end-of-source-newline": null,
- [ ] 	"number-leading-zero": null,
- [ ] 	"number-no-trailing-zeros": null,
- [ ] 	"property-case": null,
- [ ] 	"property-no-vendor-prefix": null,
- [ ] 	"rule-empty-line-before": null,
- [ ] 	"selector-attribute-brackets-space-inside": null,
- [ ] 	"selector-attribute-operator-space-after": null,
- [ ] 	"selector-attribute-operator-space-before": null,
- [ ] 	"selector-combinator-space-after": null,
- [ ] 	"selector-combinator-space-before": null,
- [ ] 	"selector-descendant-combinator-no-non-space": null,
- [ ] 	"selector-list-comma-newline-after": null,
- [ ] 	"selector-list-comma-newline-before": null,
- [ ] 	"selector-list-comma-space-after": null,
- [ ] 	"selector-list-comma-space-before": null,
- [ ] 	"selector-max-empty-lines": null,
- [ ] 	"selector-no-vendor-prefix": null,
- [ ] 	"selector-not-notation": null,
- [ ] 	"selector-pseudo-class-case": null,
- [ ] 	"selector-pseudo-class-parentheses-space-inside": null,
- [ ] 	"selector-pseudo-element-case": null,
- [ ] 	"selector-pseudo-element-colon-notation": null,
- [ ] 	"selector-type-case": null,
- [ ] 	"shorthand-property-no-redundant-values": null,
- [ ] 	"string-quotes": null,
- [ ] 	"unit-case": null,
- [ ] 	"value-keyword-case": null,
- [ ] 	"value-list-comma-newline-after": null,
- [ ] 	"value-list-comma-space-after": null,
- [ ] 	"value-list-comma-space-before": null,
- [ ] 	"value-list-max-empty-lines": null,
- [ ] 	"value-no-vendor-prefix": null
- [ ]   }
- [ ] }
- [ ] All the autofixing rules:
- [ ] 
- [ ] alpha-value-notation
- [ ] at-rule-empty-line-before
- [ ] at-rule-name-case
- [ ] at-rule-name-space-after
- [ ] at-rule-no-vendor-prefix
- [ ] at-rule-semicolon-newline-after
- [ ] block-closing-brace-empty-line-before
- [ ] block-closing-brace-newline-after
- [ ] block-closing-brace-newline-before
- [ ] block-closing-brace-space-before
- [ ] block-opening-brace-newline-after
- [ ] block-opening-brace-newline-before
- [ ] block-opening-brace-space-after
- [ ] block-opening-brace-space-before
- [ ] color-function-notation
- [ ] color-hex-case
- [ ] color-hex-length
- [ ] comment-empty-line-before
- [ ] comment-whitespace-inside
- [ ] custom-property-empty-line-before
- [ ] declaration-bang-space-after
- [ ] declaration-bang-space-before
- [ ] declaration-block-semicolon-newline-after
- [ ] declaration-block-semicolon-space-after
- [ ] declaration-block-semicolon-space-before
- [ ] declaration-block-trailing-semicolon
- [ ] declaration-colon-newline-after
- [ ] declaration-colon-space-after
- [ ] declaration-colon-space-before
- [ ] declaration-empty-line-before
- [ ] font-family-name-quotes
- [ ] function-comma-newline-after
- [ ] function-comma-newline-before
- [ ] function-comma-space-after
- [ ] function-comma-space-before
- [ ] function-max-empty-lines
- [ ] function-name-case
- [ ] function-parentheses-newline-inside
- [ ] function-parentheses-space-inside
- [ ] function-whitespace-after
- [ ] hue-degree-notation
- [ ] indentation
- [ ] length-zero-no-unit
- [ ] linebreaks
- [ ] max-empty-lines
- [ ] media-feature-colon-space-after
- [ ] media-feature-colon-space-before
- [ ] media-feature-name-case
- [ ] media-feature-name-no-vendor-prefix
- [ ] media-feature-parentheses-space-inside
- [ ] media-feature-range-operator-space-after
- [ ] media-feature-range-operator-space-before
- [ ] media-query-list-comma-newline-after
- [ ] media-query-list-comma-space-after
- [ ] media-query-list-comma-space-before
- [ ] no-empty-first-line
- [ ] no-eol-whitespace
- [ ] no-extra-semicolons
- [ ] no-missing-end-of-source-newline
- [ ] number-leading-zero
- [ ] number-no-trailing-zeros
- [ ] property-case
- [ ] property-no-vendor-prefix
- [ ] rule-empty-line-before
- [ ] selector-attribute-brackets-space-inside
- [ ] selector-attribute-operator-space-after
- [ ] selector-attribute-operator-space-before
- [ ] selector-combinator-space-after
- [ ] selector-combinator-space-before
- [ ] selector-descendant-combinator-no-non-space
- [ ] selector-list-comma-newline-after
- [ ] selector-list-comma-newline-before
- [ ] selector-list-comma-space-after
- [ ] selector-list-comma-space-before
- [ ] selector-max-empty-lines
- [ ] selector-no-vendor-prefix
- [ ] selector-not-notation
- [ ] selector-pseudo-class-case
- [ ] selector-pseudo-class-parentheses-space-inside
- [ ] selector-pseudo-element-case
- [ ] selector-pseudo-element-colon-notation
- [ ] selector-type-case
- [ ] shorthand-property-no-redundant-values
- [ ] string-quotes
- [ ] unit-case
- [ ] value-keyword-case
- [ ] value-list-comma-newline-after
- [ ] value-list-comma-space-after
- [ ] value-list-comma-space-before
- [ ] value-list-max-empty-lines
- [ ] value-no-vendor-prefix

**Comment by jelly** [comment]
@garrett I think we have applied all the stylelint rules we wanted so I'm closing this issue.
