### ISSUE TITLE
Add ability to disable "Other Options > Connect to"

### ISSUE THREAD

**Issue by sparticvs** [cockpit-project/cockpit#17340]
Page: Login

This now displays "Other options > Connect to", which while I can see the value, is not something I want on my Cockpit instance - it makes it so that someone could bypass my 2FA setup, which I don't like. I'd like to be able to disable this option, even if it was just part of the config file.

**Comment by martinpitt** [comment]
Basically the same as in https://bugzilla.redhat.com/show_bug.cgi?id=2018741 . My proposed solution was to change the `RequireHost` option into a three-state: `RemoteHost=require|allow|no`.

**Comment by sparticvs** [comment]
@martinpitt thanks for the comment, I honestly didn't even look at BZ. I like your suggestion. My question is would it prohibit just on the login page or would it be across the platform entirely (meaning after logging in, would it prevent you from connecting to other hosts in VMs that are on the private networks?) [If you'd prefer, I can also move the conversation over there].

**Comment by sparticvs** [comment]
Perfect, that aligns with what I am hoping for.
