### ISSUE TITLE
Use delete icon for deleting

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#1735]
Removing servers (dashboard) and containers (docker) currently use the close icon instead.

**Comment by stefwalter** [comment]
@andreasn could you note the new icon that should be used, and the size?

**Comment by andreasn** [comment]
Icon is pficon-delete and text-size is 14px
Should be fixed in the pull request above.

**Comment by stefwalter** [comment]
The pull request #1739 only fixes half of the issue here, it doesn't change the dashboard.

**Comment by andreasn** [comment]
True. I wanted to do that as a separate pull request.
