### ISSUE TITLE
Escape the Kubernetes REST URIs correctly 

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1737]
In KubernetesClient we need to escape the Kubernetes REST API variable components correctly with ```escapeURIComponent```

**Comment by stefwalter** [comment]
All the lines that look like this: https://github.com/cockpit-project/cockpit/blob/master/pkg/kubernetes/kubernetes.js#L132

Need to have escapeURIComponent(xxxx) added around the variable part of the path.

**Comment by jeffvance** [comment]
Should it be encodeURIComponent()? Some google searching indicates that escapeURIComponent is (or will be) depracated.

**Comment by stefwalter** [comment]
@jeffvance Yes. encodeURIComponent() Indeed: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
