### ISSUE TITLE
Cannot check for updates - Content Security Policy problem

### ISSUE THREAD

**Issue by divStar** [cockpit-project/cockpit#17377]
Hello,

I've been using Cockpit for a couple of days and at first it opened up without a problem - even on my android phone. But today it stopped.

In neither of the browsers I tested (Firefox on Android 100.x, Firefox for Windows 100.0.2, Chrome on Android, Edge on Windows) was it possible to check for updated packages and package lists, let alone update my system.

The "checking for package updates..." line keeps spinning (screenshot is taken in Firefox for Windows; Dark Reader Addon made the background - well - dark):
![grafik](https://user-images.githubusercontent.com/138585/169924104-6e68e50c-5329-4d86-a365-ce96cfa821f3.png)

In Firefox, sometimes that call completes and turns in `Bug fix updates available`, but it will not let me install it, saying (and no further console output):
![grafik](https://user-images.githubusercontent.com/138585/169924458-1335fd92-9b41-4035-bf95-251cc0bdb1a4.png)

Most of the other stuff seems to work, though.

I get the following errors in **Edge**:
```ts
Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
(anonym) @ updates.js:2
(anonym) @ cockpit.js:1
(anonym) @ cockpit.js:1
L @ cockpit.js:1
setTimeout (asynchron)
A @ cockpit.js:1
M @ cockpit.js:1
U @ cockpit.js:1
P.e.reject @ cockpit.js:1
(anonym) @ cockpit.js:1
(anonym) @ cockpit.js:1
L @ cockpit.js:1
setTimeout (asynchron)
A @ cockpit.js:1
M @ cockpit.js:1
U @ cockpit.js:1
P.e.reject @ cockpit.js:1
(anonym) @ cockpit.js:1
s @ cockpit.js:1
value @ cockpit.js:1
h @ cockpit.js:1
g @ cockpit.js:1
(anonym) @ cockpit.js:1
A.n.onmessage.e.dispatch_data @ cockpit.js:1
(anonym) @ cockpit.js:1
postMessage (asynchron)
(anonym) @ index.js:2
A.n.onmessage.e.dispatch_data @ cockpit.js:1
```
and
```ts
Uncaught TypeError: Cannot set properties of undefined (setting 'vendor_urls')
    at Object.UpdateDetail (updates.js:2:1102472)
    at ae.<anonymous> (updates.js:2:402375)
    at cockpit.js:1:31321
    at L (cockpit.js:1:12242)
UpdateDetail @ updates.js:2
(anonym) @ updates.js:2
(anonym) @ cockpit.js:1
L @ cockpit.js:1
setTimeout (asynchron)
A @ cockpit.js:1
m @ cockpit.js:1
s @ cockpit.js:1
value @ cockpit.js:1
f @ cockpit.js:1
(anonym) @ cockpit.js:1
A.n.onmessage.e.dispatch_data @ cockpit.js:1
(anonym) @ cockpit.js:1
postMessage (asynchron)
(anonym) @ index.js:2
A.n.onmessage.e.dispatch_data @ cockpit.js:1
```

In Firefox for Windows I am getting the exceptions above as well as:
```ts
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("default-src").
```
(should translate somewhat to: [Content Security Policy: The page's settings blocked the loading of a resource: xyz](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/CSPViolation))

The issue started after I installed `cockpit-navigator`, but now I already removed it (as you can see in the menu on the left), yet the issue persists.

I've also been desperately trying to use the `0-self-signed.cert` and `0-self-signed.key` files (on all systems and browsers mentioned above) to render the connection trustworthy, which did not go well so far. Perhaps it has something to do with this, too.

Do you know if it's possible to fix the issue (perhaps it's on my end after all) or work around it?

I am on Ubuntu 22.04, Cockpit 264 and PackageKit 1.2.5.

**Comment by garrett** [comment]
Thanks for your report!

It looks like your system is trying to run `tracer` on Ubuntu... but I'm pretty sure `tracer` is supposed to be for Fedora & RHEL only and not on Ubuntu? I wonder why.

@skobyda would know more about that.

I think the CSP (content security policy) errors are unrelated. They may have to do with browser extensions.

**Comment by divStar** [comment]
Thank you very much for auch a quick response!

Just to clarify: by "offline issue" you are referring to the inability to apply updates? So it was just pure luck, that it worked for me a few days ago? I will definitely look at the Ubuntu issue you linked. Thanks!

I will also retry with all add-ons disabled in Firefox and see if the CSP-error related messages disappear.

**Comment by divStar** [comment]
So uhm... From my point of view the issue is resolved since I just stopped NetworkManager while keeping systemd-networkd enabled. Now the issue does not occur anymore.
