### ISSUE TITLE
Websocket refusing connection

### ISSUE THREAD

**Issue by deprale** [cockpit-project/cockpit#17393]
### Explain what happens

![image](https://user-images.githubusercontent.com/33827235/170454789-8849c4cc-d2ec-4651-a5eb-c29389bd31ca.png)
![image](https://i.imgur.com/JoFk7Wp.png)

ufw status numbered
```

Status: active

     To                         Action      From
[ 1] 61094                      ALLOW IN    Anywhere
[ 2] 443                        ALLOW IN    Anywhere
[ 3] 80/tcp                     ALLOW IN    Anywhere
[ 4] 25565/tcp                  ALLOW IN    Anywhere
[ 5] 25565/udp                  ALLOW IN    Anywhere
[ 6] 27015/tcp                  ALLOW IN    Anywhere
[ 7] 27015/udp                  ALLOW IN    Anywhere
[ 8] 9090                       ALLOW IN    Anywhere
```

 /etc/cockpit/cockpit.conf
```
[WebService]
Origins = https://trinity-zone.net wss://trinity-zone.net
ProtocolHeader = X-Forwarded-Proto
UrlRoot = /dockers/
AllowUnencrypted = true
```

/etc/nginx/nginx.conf

```
user http;
worker_processes  1;

error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    server_tokens off;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;
    types_hash_max_size 4096;

    gzip  on;
    # HTTPS server
    #
    server {
		listen 80;
        listen 443 ssl;
		listen [::]:443 ssl;
        ssl_certificate      /etc/ssl/private/ssl.crt;
        ssl_certificate_key  /etc/ssl/private/ssl.key;
        server_name trinityzone www.trinity-zone.net;

		error_page 403 /403.html; 
		error_page 404 /404.html; 

		location /dockers/ {
			proxy_pass https://127.0.0.1:9090/dockers/;
			proxy_set_header Host $host;
			proxy_set_header X-Forwarded-Proto $scheme;

			proxy_http_version 1.1;
			proxy_buffering off;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection $http_upgrade;

			gzip off;
		}
		
		location / {
	    	root /var/www/trinityzone;
	    	#try_files $uri $uri/ =404;

       }

   }


}
```

### Version of Cockpit

(don't know where to check since i cant login) pacman -S cockpit

### Where is the problem in Cockpit?

Networking

### Server operating system

Arch Linux

### Server operating system version

Latest Arch Linux 64 bit

### System log

```shell
Journalctl is spotless for both nginx and cockpit. No errors whatsoever.
```

I'm also using cloudflare origin CA.

**Comment by philippe-ancsin** [comment]
I got the same bug.

**Comment by deprale** [comment]
> I got the same bug.

Let's hope we get some insight from someone more knowledgeable :)

**Comment by martinpitt** [comment]
> proxy_pass https://127.0.0.1:9090/dockers/;

I don't think you want https here. It's both unnecessary (this is localhost, after all) and unnecessarily complicated, as you need to provide some certificate for cockpit-ws then (which is precisely what you want to avoid by using a reverse proxy). We don't test https-to-https proxying anywhere and don't have much experience with it.

https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX has our tested standard recipe. As first step, can you test with plain "http://" proxy_pass?

Also, would you mind expanding the "WebSocket connection .. failed" message? (the little triangle on the left)

**Comment by deprale** [comment]
> Also, would you mind expanding the "WebSocket connection .. failed" message? (the little triangle on the left)

I've given up really, wasted too much time but I'm looking to get it started again since using docker in the terminal is a pain on a VPS.

I can't access it locally, unless I do some funny openvpn stuff which would be too complicated and unnecessary, would leaving it on HTTP be actually beneficial? If so, should I just limit access to my ip and that's it? (which is gonna be another hassle because mine is dynamic zzzzzzzzz)

I'm not too familiar with networking and I'm unsure how "unsafe" http is to be left accessible by the public.

**Comment by martinpitt** [comment]
> I'm not too familiar with networking and I'm unsure how "unsafe" http is to be left accessible by the public.

It's not -- cockpit/ws only listens on localhost, you can't access it from outside. That's the point of using a reverse proxy, which "wraps" that private network service into a publicly accessible one, with https, a certificate, and a proper domain name.

**Comment by FlorianLeChat** [comment]
I have had the exact same one for several days/weeks (since at least the beginning of June) now. Cockpit (version 272) is installed on my VPS running Debian 11 and using Nginx as a reverse proxy. When I installed Cockpit several months ago following this tutorial: https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX everything was working fine until recently when I noticed I was unable to connect with any user account.

![image](https://user-images.githubusercontent.com/26360935/179372579-bb025e78-1e54-4ba5-b5eb-9378165116a0.png)
(Well sorry it's in French but the errors are exactly the same as those from the author of this issue).

Here is the configuration file I use, Cockpit is used in a subdomain of Nginx and the whole server configuration is in two separate files. Also, I want to point out that I use Cloudflare on my domain.

`/etc/nginx/sites-available/monitor.florian-dev.fr`
```
server
{
    server_name monitor.florian-dev.fr;

    root /var/www/monitor.florian-dev.fr;

    include /etc/nginx/include.d/all_common;
    include /etc/nginx/include.d/ssl_common;

    location /
    {
        proxy_pass https://127.0.0.1:9090;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```
`/etc/cockpit/cockpit.conf`
```
[WebService]
Origins = https://monitor.florian-dev.fr wss://monitor.florian-dev.fr
ProtocolHeader = X-Forwarded-Proto
```

Partial logs of `journalctl -u cockpit`:
```
juil. 16 23:20:35 vps761196 systemd[1]: cockpit.service: Deactivated successfully.
juil. 16 23:23:41 vps761196 systemd[1]: Starting Cockpit Web Service...
juil. 16 23:23:41 vps761196 systemd[1]: Started Cockpit Web Service.
juil. 16 23:25:14 vps761196 systemd[1]: cockpit.service: Deactivated successfully.
juil. 16 23:25:16 vps761196 systemd[1]: Starting Cockpit Web Service...
juil. 16 23:25:16 vps761196 systemd[1]: Started Cockpit Web Service.
juil. 16 23:26:54 vps761196 systemd[1]: cockpit.service: Deactivated successfully.
juil. 16 23:28:05 vps761196 systemd[1]: Starting Cockpit Web Service...
juil. 16 23:28:05 vps761196 systemd[1]: Started Cockpit Web Service.
juil. 16 23:29:35 vps761196 systemd[1]: cockpit.service: Deactivated successfully.
juil. 16 23:32:23 vps761196 systemd[1]: Starting Cockpit Web Service...
juil. 16 23:32:23 vps761196 systemd[1]: Started Cockpit Web Service.
juil. 16 23:33:55 vps761196 systemd[1]: cockpit.service: Deactivated successfully.
juil. 16 23:35:55 vps761196 systemd[1]: Starting Cockpit Web Service...
juil. 16 23:35:55 vps761196 systemd[1]: Started Cockpit Web Service.
juil. 16 23:37:56 vps761196 systemd[1]: cockpit.service: Deactivated successfully.
```
Partial logs of `journalctl -f` when attempting to connect
```
juil. 16 23:44:21 vps761196 systemd[1]: Starting Socket for Cockpit Web Service http instance...
juil. 16 23:44:21 vps761196 systemd[1]: Starting Socket for Cockpit Web Service https instance factory...
juil. 16 23:44:21 vps761196 systemd[1]: Listening on Socket for Cockpit Web Service http instance.
juil. 16 23:44:21 vps761196 systemd[1]: Listening on Socket for Cockpit Web Service https instance factory.
juil. 16 23:44:21 vps761196 systemd[1]: Starting Cockpit Web Service...
juil. 16 23:44:21 vps761196 systemd[1]: Started Cockpit Web Service.
juil. 16 23:44:22 vps761196 systemd[1]: Started Cockpit Web Service http instance.
juil. 16 23:44:24 vps761196 cockpit-session[1594334]: pam_ssh_add: Failed adding some keys
juil. 16 23:44:24 vps761196 cockpit-session[1594334]: pam_unix(cockpit:session): session opened for user root(uid=0) by (uid=0)
juil. 16 23:44:24 vps761196 systemd-logind[4054237]: New session 343817 of user root.
juil. 16 23:44:24 vps761196 systemd[1]: Started Session 343817 of User root.
juil. 16 23:44:39 vps761196 cockpit-session[1594334]: pam_unix(cockpit:session): session closed for user root
juil. 16 23:44:39 vps761196 systemd[1]: session-343817.scope: Deactivated successfully.
juil. 16 23:44:39 vps761196 systemd-logind[4054237]: Session 343817 logged out. Waiting for processes to exit.
juil. 16 23:44:39 vps761196 systemd-logind[4054237]: Removed session 343817.
```

I tried to do several things, including disabling Cloudflare temporarily on my domain, removing a large part of the configuration I had applied to Nginx (like CSP headers, etc...). Also, I thought it was because I disabled password authentication for SSH access which was causing that but even re-enabling it, the issue is still there. I'm really out of ideas and yet I've spent several hours on this without success, if anyone can help me, that would be very nice!

> https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX has our tested standard recipe. As first step, can you test with plain "http://" proxy_pass?

I always get the same error when making this change.

> Also, would you mind expanding the "WebSocket connection .. failed" message? (the little triangle on the left)

![image](https://user-images.githubusercontent.com/26360935/179373167-8ce6140f-72ff-4886-931e-1ba6c2576588.png)
![image](https://user-images.githubusercontent.com/26360935/179373172-2de0d92e-a0f5-4da0-88c1-a79c2473e1a3.png)
![image](https://user-images.githubusercontent.com/26360935/179373182-0e10b72f-2545-494b-b21e-a16f04d1533a.png)

**Comment by martinpitt** [comment]
See my [response above](https://github.com/cockpit-project/cockpit/issues/17393#issuecomment-1146057859). There was no further information in half a year, so I am closing this now. Please respond here if you have further info, then I'm happy to reopen. Thanks!

**Comment by funkemunky** [comment]
I figured out the fix for this issue. You need to configure your cockpit.conf with the appropriate settings to allow it to access the websocket via a reverse proxy (I.E. nginx or cloudflare tunnels).

In my case, I proxy mine through Cloudflare Tunnels.

You need to do the following:
`sudo nano /etc/cockpit/cockpit.conf`

and enter the following configuration:
```yaml
[WebService]
Origins = https://cockpit.yourdomain.com
ProtocolHeader = X-Forwarded-Proto
AllowUnencrypted = true
```

Hope this helps!

**Comment by w00dwind** [comment]
Have the same issue. Can access to cockpit only from same subnet with server. When try to access through another subnets - login page loads, but can't login. 
I have server behind reverse proxy (nginx) runing on KeeneticOS (its my wifi router). 

my cockpit.conf have necessary options:
```
[WebService]
#Origins = https://somedomain1.com https://somedomain2.com:9090 https://*.somedomain3.com
Origins = https://cpt.sub.mydomain.pro/ wss://cpt.cpt.sub.mydomain.pro http://192.168.3.30:9090
ProtocolHeader = X-Forwarded-Proto
ForwardedForHeader = X-Forwarded-For
AllowUnencrypted = true
```

i tried solution founded on keenetic forum to change nginx options, but it didn't work for me:

```
ip http proxy subdomain
    upstream https mac_address 9090
    domain ndns
    ssl no redirect
    security-level public
    x-real-ip
    preserve-host
    preserve-referer
    preserve-origin
```

Here is my nginx.conf
```
server {
    resolver 127.0.0.1;
    listen 192.168.3.1:80;
    listen unix:/var/nginx/ndns.plain.socket proxy_protocol;
    listen unix:/var/nginx/ndmp.plain.socket proxy_protocol;
    listen 127.0.0.1:80;
    server_name cpt.sub.mydomain.pro/ ;
    location / {
      auth_basic off;
      auth_digest off;
      zstd off;
      gzip off;
      set $ndm_proxy_upstream_9 "192.168.3.30:9090";
      proxy_pass http://$ndm_proxy_upstream_9;
      proxy_http_version 1.1;
      proxy_buffering off;
      proxy_buffers 8 32k;
      proxy_buffer_size 64k;
      proxy_busy_buffers_size 64k;
      proxy_max_temp_file_size 0;
      proxy_redirect http://$proxy_host/ /;
      proxy_request_buffering off;
      proxy_set_header Connection $http_connection;
      proxy_set_header Upgrade $http_upgrade;
      proxy_read_timeout 60s;
      proxy_send_timeout 60s;
      send_timeout 60s;
      proxy_set_header Origin $http_origin;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Port $ndm_server_port;
    }
```

When i try to login through cpt.sub.mydomain.pro/ - i have nothing in **journalctl -u cockpit** only see error in web console like first post. 

When try to login through 192.168.3.30:9090:
```
Feb 23 23:59:13 pve cockpit-tls[3227916]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Feb 23 23:59:14 pve cockpit-tls[3227916]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Feb 23 23:59:14 pve cockpit-tls[3227916]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
```

But both methods cant login.
