### ISSUE TITLE
SW updates page oopses to set up `vendor_urls`

### ISSUE THREAD

**Issue by tgwaste** [cockpit-project/cockpit#17405]
Im not really even sure what to title this but here is what chrome is telling me:
<img width="552" alt="Screen Shot 2022-05-30 at 16 38 51" src="https://user-images.githubusercontent.com/690918/171068443-d673c270-ac4b-4db9-89e3-61b52409ab66.png">

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
```

**Comment by martinpitt** [comment]
@marusak : IIRC you had a half-done patch for this? Or was this a dead end?

**Comment by marusak** [comment]
@martinpitt It was just quick fix for the oops, to just check if `v` is set up. Happy to send it as PR of course, but it would be more interesting to figure out whyit can happen.

**Comment by tgwaste** [comment]
Hi, just wondering if there were any plans to fix this?  It seems to make cockpit unusable with 22.04, unless I'm missing something?

**Comment by marusak** [comment]
I have sent https://github.com/cockpit-project/cockpit/pull/17464

I am still not sure though how this could happen, possibly some weird package or change in packagekit api but I would have hoped that our CI would see it.

I am not sure if we should land this. I would love to see output from the `console.warn` I put there. Would you be interested @tgwaste to try this patch before we merge it?

**Comment by tgwaste** [comment]
Yes, of course. Glad to help.

**Comment by tgwaste** [comment]
So, I've noticed this isn't happening anymore but I have not seen any cockpit updates.  I have seen Chrome updates though.  Any thoughts or am I missing something?

**Comment by marusak** [comment]
any packagekit updates?
But in general I think this was related to specific update that was pending. Once you have applied this update (or even there was newer version of the package) it might start behaving normally again.

**Comment by matthewpritchett** [comment]
Curious if this has been pushed as an update to Ubuntu 22.04 as I’m seeing a similar Oops on a freshly setup system. Thanks!

**Comment by martinpitt** [comment]
@matthewpritchett : You can install version 275-1~bpo22.04.1 from backports. This was not released as a fix into -updates.

**Comment by matthewpritchett** [comment]
@martinpitt thank you! Do you happen to know if it’ll ever make it into -updates? I try not to dive into backports too often. Thanks again!

**Comment by martinpitt** [comment]
@matthewpritchett : Nothing happens just by itself :grin: I'm not opposed to fixing this in 22.04 proper, but given how https://launchpad.net/bugs/1990623 and the entire SRU process has been stalled for a long time doesn't exactly motivate me to do it now. Once that is in, and the processs works again, I'm okay with sending another update, but that currently pending one is much more important.

**Comment by matthewpritchett** [comment]
@martinpitt Thanks for that info! Didn’t realize how involved the SRU process was. I’ll keep an eye out on that other bug and see how it goes.
