### ISSUE TITLE
As of today COPR no longer works as it is missing an EPEL8 build. @martinpitt

### ISSUE THREAD

**Issue by fmsy** [cockpit-project/cockpit#17413]
As of today COPR no longer works as it is missing an EPEL8 build. @martinpitt 

It was present until at least 22/04/05 @ https://download.copr.fedorainfracloud.org/results/@cockpit/cockpit-preview/epel-8-x86_64/

![image](https://user-images.githubusercontent.com/3216591/171323969-ce2ebbec-893c-4852-a836-a813e0dd9b6c.png)

Are there any plans on providing EPEL8 builds again ?

Using the centos8stream builds is not an options as they depend on non-existent versions of policy-targeted

![image](https://user-images.githubusercontent.com/3216591/171324610-e53c204c-ad5b-4129-9e28-31a843cc2a37.png)

_Originally posted by @fmsy in https://github.com/cockpit-project/cockpit/discussions/17061#discussioncomment-2860716_

**Comment by fmsy** [comment]
from what is visible to me i can see `cockpit-185` @ el 8.0, then `cockpit-251` @ el 8.5 and el 8.10 to be released in 2024 (from RHEL 8 Planning Guide)

wouldn't it be reasonable then to follow a non-stream el8 by having an epel8 build and testing it?

**Comment by hfoy** [comment]
I second the request to re-implement epel-8 as build target for COPR.

**Comment by martinpitt** [comment]
This finally got unblocked by a packit improvement -- I just sent a bunch of PRs like #17783 to drop the hardcoded target list from our packit.yml. After all of these land, we gain back the flexibility of adding more COPR targets such as EPEL.

**Comment by martinpitt** [comment]
Sorry for letting this slip -- I finally enabled epel 8/9 for x86_64 and aarch64 on our COPR.
