### ISSUE TITLE
Cockpit ignores TLS priority settings 

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/cockpit#17416]
### Explain what happens

1. i have tried everything to configure cockpit 215 not to ALLOW TLS 1.0/1.1
 i'm using GNUTLS 3.5.18-1 and i'm trying to use /etc/gnutls/default-priorities file with various strings 
#SYSTEM=NONE:!VERS-SSL3.0:!VERS-TLS1.0:+VERS-TLS1.2:+AES-128-CBC:+RSA:+SHA1:+COMP-NULL
SECURE128=NONE
NORMAL=NONE
#SYSTEM=NONE

and not matter what i tried and service restarts it still allows tls 1/1.1

is there any way to configure cockpit not to allow those protocols? 

### Version of Cockpit

215

### Where is the problem in Cockpit?

Networking

### Server operating system version

Ubuntu 18.04.06

### What browsers are you using?

Chrome

**Comment by martinpitt** [comment]
Can you please re-test this with a current version? cockpit-tls uses GNUTLS in a pretty straightforward way, it does not make any custom choices about TLS versions. How exactly did you test this, so that we can reproduce this?

**Comment by emaayan** [comment]
that's the problem it's too strighforward the GNUTLS library (in ubuntu 18) doesn't provide you with the ability to disable tls 
cockpit in ubuntu 20 does have it's tls 1.1 disabled.

**Comment by martinpitt** [comment]
GnuTLS config internals, not actionable, stale.

**Comment by bendergm** [comment]
I had the same issue and found that reconfiguring a GNUTLS config file was a lot easier.

To minimally disable TLS1.0 and TLS1.1, you can state just that.  GNUTLS documentation here, [Disabling-algorithms-and-protocols](https://www.gnutls.org/manual/html_node/Disabling-algorithms-and-protocols.html)
```
$ sudo cat /etc/gnutls/config
[overrides]
disabled-version = tls1.0
disabled-version = tls1.1
```
I am experimenting with the [Priority String](https://www.gnutls.org/manual/html_node/Priority-Strings.html) option, which you may have also stumbled on in other people's tials.  Using this statement seems to give you a lot of the options you'd want for higher security all in one line.
```
$ sudo cat /etc/gnutls/config
[overrides]
default-priority-string = SECURE128:%LATEST_RECORD_VERSION:%SERVER_PRECEDENCE:%SAFE_RENEGOTIATION:-AES-128-CBC:-AES-256-CBC:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1
```
After configuring this, nmap does not quite scan correctly.  Use the [ssl-enum-ciphers](https://nmap.org/nsedoc/scripts/ssl-enum-ciphers.html) script if you want to test/validate it also,
```
nmap -sV -p 9090 --script ssl-enum-ciphers cockpit.local
```  
I snagged that Priority String line from the [Tenable documentation for securing Cockpit](https://community.tenable.com/s/article/How-to-configure-restrict-SSL-ciphers-for-Tenable-Core-cockpit?language=en_US).  Using their method did not quite work for me.

**Comment by emaayan** [comment]
Yea, i think the problem i've encountered was that in ubuntu 20 you could
not have override this no matter what you did.
Ubuntu 22 disables this by default
