### ISSUE TITLE
Libvirtd errors, each time opening virtual machines page

### ISSUE THREAD

**Issue by polhaghverdian** [cockpit-project/cockpit#17439]
### Explain what happens

Every time I open the Virtual machines page, I get a handful of libvirtd errors. I'm pretty sure it's caused by Cockpit. I run Ubuntu 22.04 together with Cockpit version 264-1. Its worth mentioning that the VM's work fine. I just want to get rid of the errors.

![image](https://user-images.githubusercontent.com/50968806/172475393-8bc51616-7080-4085-a3b3-6f91d4cd59d4.png)

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Ubuntu

### Server operating system version

22.04

### What browsers are you using?

Firefox

**Comment by KKoukiou** [comment]
Please report this to libvit or apparmor package or your distros bugtracker. This is not related to cockpit. Thanks for using cockpit-machines though :)
