### ISSUE TITLE
iscsi widget missing

### ISSUE THREAD

**Issue by aandre81** [cockpit-project/cockpit#17455]
### Explain what happens

The iscsi Widget in Storage is missing!
No matter which version I install, it's missing.
I've tried Ubuntu 20.04.4, 22.04, 22.10, none of them work. I've tried it on virtual machines, on real computers, different browsers, always the same.
It always looks like this:
![ccc](https://user-images.githubusercontent.com/107535784/173761985-361147fe-cea5-42ff-93c9-068b4073d552.jpg)

### Version of Cockpit

271

### Where is the problem in Cockpit?

Storage

### Server operating system

Ubuntu

### Server operating system version

22.10

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
The [debian udisks2 package](https://tracker.debian.org/pkg/udisks2) does not enable iscsi; Ubuntu inherits that.

That is the API that cockpit talks to.

**Comment by aandre81** [comment]
Is there a possibility to fix it?
