### ISSUE TITLE
Unable to connect to web service when samba share is mounted

### ISSUE THREAD

**Issue by zz0rk** [cockpit-project/cockpit#17515]
### Explain what happens

1. Mount samba share
2. Open browser > localhost:9090
3. Page cannot be reached

systemd error log:

Jun 29 20:20:23 debian11 systemd[1]: Starting Cockpit Web Service...
Jun 29 20:20:23 debian11 systemd[1]: Started Cockpit Web Service.
Jun 29 20:20:33 debian11 systemd[183037]: cockpit.service: Failed to set up mount namespacing: /run/systemd/unit-root/: Host is down
Jun 29 20:20:33 debian11 systemd[183037]: cockpit.service: Failed at step NAMESPACE spawning /usr/lib/cockpit/cockpit-tls: Host is down
Jun 29 20:20:33 debian11 systemd[1]: cockpit.service: Main process exited, code=exited, status=226/NAMESPACE
Jun 29 20:20:33 debian11 systemd[1]: cockpit.service: Failed with result 'exit-code'.
Jun 29 20:20:33 debian11 systemd[1]: Starting Cockpit Web Service...
Jun 29 20:20:33 debian11 systemd[1]: Started Cockpit Web Service.

4. unmount samba share/s
5. Open browser > localhost:9090 > sign into cockpit

error is browser agnostic

### Version of Cockpit

Package: cockpit Version: 239-1

### Where is the problem in Cockpit?

Services

### Server operating system

Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

### Server operating system version

Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

### What browsers are you using?

Edge, Firefox, Chrome

### System log

```shell
Jun 29 20:20:23 debian11 systemd[1]: Starting Cockpit Web Service...
Jun 29 20:20:23 debian11 systemd[1]: Started Cockpit Web Service.
Jun 29 20:20:33 debian11 systemd[183037]: cockpit.service: Failed to set up mount namespacing: /run/systemd/unit-root/: Host is down
Jun 29 20:20:33 debian11 systemd[183037]: cockpit.service: Failed at step NAMESPACE spawning /usr/lib/cockpit/cockpit-tls: Host is down
Jun 29 20:20:33 debian11 systemd[1]: cockpit.service: Main process exited, code=exited, status=226/NAMESPACE
Jun 29 20:20:33 debian11 systemd[1]: cockpit.service: Failed with result 'exit-code'.
Jun 29 20:20:33 debian11 systemd[1]: Starting Cockpit Web Service...
Jun 29 20:20:33 debian11 systemd[1]: Started Cockpit Web Service.
```

**Comment by martinpitt** [comment]
cockpit.service: Failed to set up mount namespacing: /run/systemd/unit-root/: Host is down

This bug is between samba breaking systemd, systemd getting confused by the samba mount, the Linux kernel, or possibly a local misconfiguration.

Where exactly do you mount the samba shares? Not possibly onto `/run/`? Can you show the output of `mount`?

**Comment by zz0rk** [comment]
//muzak/muzak on /media/username/muzak type cifs (rw,nosuid,nodev,relatime,vers=3.1.1,cache=strict,=username,uid=1000,forceuid,gid=1000,forcegid,addr=[IP address],file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1,user=username)

The other shares are mounted in exactly the same manner.
The issue seemed to occur primarily after the share had been mounted and the laptop had been suspended some time afterwards. After I unmount I can sign in. It took me some time to realize it was related to the samba shares, until I came across this article.

https://bugzilla.redhat.com/show_bug.cgi?id=1869028
