### ISSUE TITLE
software updates: Services button should be secondary, not primary

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#17514]
### Explain what happens

You're not supposed to have two primary buttons for the same related section

![image](https://user-images.githubusercontent.com/10246/176643928-fb08d4b1-e7e2-4464-b24c-a88d437d5f91.png)

The services button should be secondary.

(Reboot being primary is correct; the ignore being a link styled button is also correct.)

**Comment by martinpitt** [comment]
This dialog already tries to DTRT:
```
                        { restart.length > 0 && <Button id="choose-service" variant={reboot.length > 0 ? "secondary" : "primary"} onClick={openServiceRestartDialog}>{_("Restart services...")}</Button> }
```
but it's missing the corner case that the reboot button is only shown for "restarted manually". I'll fix it.
