### ISSUE TITLE
Loading available updates failed (when using /etc/yum/vars or /etc/dnf/vars)

### ISSUE THREAD

**Issue by jamjon3** [cockpit-project/cockpit#17533]
Hosts that have a var defined that is used in /etc/yum.repos.d/ conf files are causing Cockpit to be unable to handle updates (even though the host works just fine from dnf/yum)

Clicking on Software Updates shows this

![image](https://user-images.githubusercontent.com/907953/177862641-82ca8d3c-7d1b-4a42-8abb-04f6ebf04e36.png)

**Comment by jamjon3** [comment]
This affects RHEL7, RHEL8 and RHEL9 with cockpit

**Comment by garrett** [comment]
> Hosts that have a var defined that is used in /etc/yum.repos.d/ conf files

Do you mind sharing the var in your `/etc/yum.repos.d/`? Either what you have in your conf file or an example that's similar? It'd be best if you can share the configuration for `nexus-podsit` specifically.

The error message in your screenshot, "Cannot download repomd.xml: Empty mirrorlist and no basepath specified!", makes it look like the URLs don't exist, as least from PackageKit's point of view. It's odd if dnf/yum see it and PackageKit doesn't.

> (even though the host works just fine from dnf/yum)

Just a clarification: Cockpit uses [PackageKit](https://en.wikipedia.org/wiki/PackageKit), not dnf/yum, so it's probable the issue may exist at that level.

In a terminal, what does `pkcon get-updates` ([PackageKit command](https://manpages.org/pkcon) to show available updates) and `pkcon update` (PackageKit's command line way to update your system) show?

**Comment by KKoukiou** [comment]
@jamjon3 thanks for reporting this.
This was a libdnf known bug https://bugzilla.redhat.com/show_bug.cgi?id=1756382 which seems to been fixed in latest RHEL 8 and RHEL 9. If you can verify otherwise please use bugzilla to report this against the libdnf component.
