### ISSUE TITLE
"New NFS Mount" dialog is impossible to use

### ISSUE THREAD

**Issue by AshleighTheCutie** [cockpit-project/cockpit#17539]
### Explain what happens

1. Type in server IP
2. Attempt to supply a server path
3. Watch as it deletes your text because it thinks the path doesn't exist, and cannot take direct input

### Version of Cockpit

239

### Where is the problem in Cockpit?

Storage

### Server operating system

Debian

### Server operating system version

11

### What browsers are you using?

Firefox

**Comment by AshleighTheCutie** [comment]
Apparently Debian does not use backports packages over the mainline packages.

**Comment by garrett** [comment]
Yeah, with Debian, you need to specify backports specifically

https://cockpit-project.org/running.html#debian:

> 1. To get the latest version, we recommend to enable the [backports repository](https://backports.debian.org) (as root):
>    ```
>    . /etc/os-release
>    echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-backports main" > \
>        /etc/apt/sources.list.d/backports.list
>    apt update
>    ```
> 2. Install or update the package:
> ```
> apt install -t ${VERSION_CODENAME}-backports cockpit
> ```
> 
> _When updating Cockpit-related packages and any dependencies, make sure to use `-t ...-backports` as above, so backports are included._

(So after Cockpit is already installed, `apt upgrade -t ${VERSION_CODENAME}-backports cockpit`, after the usual `apt update` to fetch the latest info.)

The NFS mount dialog should've still worked for you in Cockpit 239, however.
