### ISSUE TITLE
Splash Screen Displays Wrong OS Version

### ISSUE THREAD

**Issue by tgwaste** [cockpit-project/cockpit#17534]
### Explain what happens

![Screen Shot 2022-07-07 at 4 22 03 PM](https://user-images.githubusercontent.com/690918/177887380-d771e3e2-6769-49eb-a992-e1ed9ae2f96f.png)

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
```

### Version of Cockpit

264-1 (machines is 265-1)

### Server operating system

Ubuntu

### Server operating system version

Ubuntu 22.04 LTS

### What browsers are you using?

Chrome

**Comment by marusak** [comment]
Is this on login page? (full screenshot would be appropriated). If so, how/where do you run cockpit-ws? Is this standard cockpit installation and socket activation or are you for example using flatpak?

Also can you please provide content of `/etc/os-release`?

**Comment by tgwaste** [comment]
Yes, login page.
![Screen Shot 2022-07-08 at 5 10 08 AM](https://user-images.githubusercontent.com/690918/177990124-80f13dd3-efa7-429b-ad10-0abc44f8586f.png)

```
# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
i just do apt-get cockpit-ws

**Comment by garrett** [comment]
Did you upgrade from 20.04 to 22.04? (Not a problem; just wondering if that's what's needed to recreate this issue, to try to track it down.)

Possibly silly suggestion: Can you try shift-reloading the page in Chrome? Perhaps it's being aggressively cached for some reason.

(Shift-reloading is basically holding down shift while reloading. It tells the browser to re-fetch the page, regardless of cache. You can press `shift-F5` or `shift-control-r` or even hold down shift key while clicking the reload button.)

**Comment by tgwaste** [comment]
force reload fixed it, thanks :)
