### ISSUE TITLE
Installation of cockpit/ws does not work as advertised

### ISSUE THREAD

**Issue by keithy** [cockpit-project/cockpit#17568]
This does work (testing on FCOS 20200108.2.0)

```
sudo podman container runlabel INSTALL cockpit/ws cockpit/ws
```
I suspect that the dockerfile needs to be amended like so
```
LABEL INSTALL="/usr/bin/docker run --rm --privileged -v /:/host IMAGE /container/atomic-install IMAGE"
```

**Comment by martinpitt** [comment]
There is nothing actionable here. The original reporter @keithy never reported back, this works for @wdouglascampbell , and I don't see anything wrong with our current container images. If anyone still has a problem with this, please file a new issue with *exact* information about what commands you ran, on which operating system, with which podman version. Thanks!
