### ISSUE TITLE
Proper patternfly alerts for failures

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1757]
We have a lot of dialogs popping up for failures. This does not fit in with patternfly or good design in general. There's an alert pattern, where a bar is displayed instead.

**Comment by stefwalter** [comment]
In many cases, such as a dialog performing an action, when there is an error, I think that this alert whould show up in the dialog or context of the action being performed.

**Comment by stefwalter** [comment]
Patternfly alerts: https://www.patternfly.org/widgets/#alerts

**Comment by stefwalter** [comment]
Current situation:

![screenshot from 2015-01-30 15 46 53](https://cloud.githubusercontent.com/assets/795070/5977334/3e00ea6a-a897-11e4-8a69-ecaec149e0fc.png)

What patternfly recommends:

![screenshot from 2015-01-30 15 45 23](https://cloud.githubusercontent.com/assets/795070/5977337/4cec017c-a897-11e4-83a3-70789daf57c2.png)

**Comment by andreasn** [comment]
I like this idea. Lets try and hunt these down and list them here.
How did you manage to trigger the docker delete one. I thought delete was always insensitive when running.

**Comment by stefwalter** [comment]
> I like this idea. Lets try and hunt these down and list them here.

Look for show_unexpected_error in the code:

```
$ git grep show_unexpected_error
```

>  How did you manage to trigger the docker delete one. I thought delete was always insensitive when running.

I stopped it while we had the 'Do you want to delete' prompt open. :D

**Comment by andreasn** [comment]
Hehe, nice (but totally possible) edge case

**Comment by stefwalter** [comment]
This is present in the dialog pattern we now use.https://github.com/cockpit-project/cockpit/wiki/HIG:-Dialogs
