### ISSUE TITLE
Arch package is missing Python dependency

### ISSUE THREAD

**Issue by plut0n1umX239p** [cockpit-project/cockpit#17587]
### Explain what happens

hi. today i install cookpit on fresh install arch. i was able to login to web interface but application tab was stuck at loading. checked browser console and see which error says: python not found!
connect to server wia ssh, install python with pacman and its working...

i think python must be dependency for cookpit pacman!

### Version of Cockpit

last

### Where is the problem in Cockpit?

Applications

### Server operating system

Arch Linux

### Server operating system version

last

### What browsers are you using?

Chrome

**Comment by martinpitt** [comment]
In the RPM packaging, cockpit-storaged and cockpit-packagekit both depend on Python. The Debian packaging is missing it on c-packagekit, I'll send a PR.

But we don't control the Arch packaging upstream. Can you please report this against the Arch package?

**Comment by jelly** [comment]
Reported upstream https://bugs.archlinux.org/task/75495

**Comment by jelly** [comment]
Python issue fixed on Arch, but now the packages are split too. So I wonder if this breaks one of our tests.
