### ISSUE TITLE
No CPU temp shown in metrics for AMD AM2/3 CPUs

### ISSUE THREAD

**Issue by g6avk** [cockpit-project/cockpit#17580]
### Explain what happens

Go to overview > Metrics and History and no CPU temp is shown.

![Screenshot_20220720_230339](https://user-images.githubusercontent.com/4700941/180090611-43ae5616-1ea3-4595-9f93-7e18cd119abf.jpeg)

### Version of Cockpit

273

### Where is the problem in Cockpit?

Metrics

### Server operating system

Fedora

### Server operating system version

36

### What browsers are you using?

Brave

**Comment by martinpitt** [comment]
On that machine, can you please copy&paste the output of these commands?

    grep -r . /sys/class/hwmon/hwmon*/name
    grep -r . /sys/class/hwmon/hwmon*/temp*

**Comment by g6avk** [comment]
$ grep -r . /sys/class/hwmon/hwmon*/name

/sys/class/hwmon/hwmon0/name:atk0110
/sys/class/hwmon/hwmon1/name:k10temp
/sys/class/hwmon/hwmon2/name:hidpp_battery_0
/sys/class/hwmon/hwmon3/name:hidpp_battery_1

 grep -r . /sys/class/hwmon/hwmon*/temp*

/sys/class/hwmon/hwmon0/temp1_crit:95000
/sys/class/hwmon/hwmon0/temp1_input:42000
/sys/class/hwmon/hwmon0/temp1_label:CPU Temperature
/sys/class/hwmon/hwmon0/temp1_max:60000
/sys/class/hwmon/hwmon0/temp2_crit:75000
/sys/class/hwmon/hwmon0/temp2_input:37000
/sys/class/hwmon/hwmon0/temp2_label:MB Temperature
/sys/class/hwmon/hwmon0/temp2_max:45000
/sys/class/hwmon/hwmon1/temp1_crit:99500
/sys/class/hwmon/hwmon1/temp1_crit_hyst:97500
/sys/class/hwmon/hwmon1/temp1_input:0
/sys/class/hwmon/hwmon1/temp1_max:70000

**Comment by tomasmatus** [comment]
> /sys/class/hwmon/hwmon1/temp1_input:0

Well this is weird. The `k10temp` driver seems to export 0C.
What CPU model is this? Are other programs such as `lm-sensors` able to read CPU Temp?

**Comment by g6avk** [comment]
The CPU is  AMD Phenom II X4 965

lm-sensors can read the temp but it is not using the k10temp driver but the atk0110, snipped output below:

$ sensors
k10temp-pci-00c3
Adapter: PCI adapter
temp1:         +0.0°C  (high = +70.0°C)
                                 (crit = +99.5°C, hyst = +97.5°C)

atk0110-acpi-0
Adapter: ACPI interface

CPU Temperature:    +45.0°C  (high = +60.0°C, crit = +95.0°C)
MB Temperature:     +34.0°C  (high = +45.0°C, crit = +75.0°C)

I guess the age of the motherboard maybe the issue?

**Comment by garrett** [comment]
I did see this comment, when I thought was interesting (but I didn't see it mentioned elsewhere, so I don't know how accurate it might be):

https://bbs.archlinux.org/viewtopic.php?pid=1600653#p1600653:

> AMD put the thermal sensor on the die so far away from the 'real' heat that we who have AMD cpu's usually get really low readings. It doesn't really become accurate until the cpu gets somewhere between 20-30C. Don't start freaking out or making config adjustments, that'll just throw off your readings when the cpu does actually get warm.

**Comment by garrett** [comment]
@g6avk: Do you have a Socket AM2+? It looks like your CPU can work in AM2+ or AM3, if I understand it correctly. If it is using AM2+ in your system, that could be why it's reporting an incorrect value.

The Linux kernel source code for k10temp.c says "Erratum 319: The thermal sensor of Socket F/AM2+ processors may be unreliable." @ https://github.com/torvalds/linux/blob/master/drivers/hwmon/k10temp.c#L308-L311

Which makes me think that the comment on the Arch Linux forum about AMD putting the thermal sensor far away from the heat is likely accurate and may be what we're seeing. Perhaps lm-sensors has a workaround that compensates for this? (And it might not be so accurate still, until it gets to higher temperatures.)

**Comment by martinpitt** [comment]
The above may all be true, but our intention is to show the highest valid/available temperature. And there is that one:
```
/sys/class/hwmon/hwmon0/temp1_input:42000
/sys/class/hwmon/hwmon0/temp1_label:CPU Temperature
```

So it seems we have a bug in bridge's iteration through /sysfs, and it may abort the detection loop too early?

**Comment by garrett** [comment]
> show the highest valid/available temperature

(For the CPU, yes. :+1:)

> /sys/class/hwmon/hwmon0/temp1_input:42000
> /sys/class/hwmon/hwmon0/temp1_label:CPU Temperature

Whoops, I guess I missed that!

Thanks! It's best to avoid lm-sensors and another codepath. I'm happy the temperature is exposed somewhere.

**Comment by g6avk** [comment]
> @g6avk: Do you have a Socket AM2+? It looks like your CPU can work in AM2+ or AM3, if I understand it correctly. If it is using AM2+ in your system, that could be why it's reporting an incorrect value.

It's AM3, it's an old motherboard (legacy Bios!) but it just works so well and reliable.
It's interesting to read others have had this issue and appreciate the links which I will have a look later.

**Comment by g6avk** [comment]
I have just updated to 274 and the k10temp is working for me now.. 
Thank You.

**Comment by martinpitt** [comment]
Thanks for confirming!

**Comment by Yangff** [comment]
On AMD epyc, the file numbers in the /sys/class/hwmon/hwmon1/ directory are not consecutive, for example 
```
/sys/class/hwmon/hwmon1/:
device  name  power  subsystem  temp1_input  temp1_label  temp5_input  temp5_label  temp7_input  temp7_label  uevent
```
where `temp1_label` is `Tcal` and get ignored, `temp5_label` is `Tccd3` and `temp7_label` is `Tccd7`
