### ISSUE TITLE
LVM - no other disks to join

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1758]
Running on a VM with only one disk in it.
Under Physical volumes I pressed Add.
Got presented with an empty dialog. Either the Add button needs to be disabled or there should be some kind of helper message in the dialog.

**Comment by andreasn** [comment]
![screenshot from 2015-01-30 16 22 36](https://cloud.githubusercontent.com/assets/209895/5977992/a2a757a6-a89c-11e4-8b43-b8f8535f2a5d.png)

**Comment by stefwalter** [comment]
This needs a patternfly alert
