### ISSUE TITLE
podman add-on - unable to access docker container

### ISSUE THREAD

**Issue by jade2020** [cockpit-project/cockpit#17609]
Hi,

I am running the podman add-on for Cockpit under Manjaro. I have pulled down a docker image ok and it is running but I can't access it. I have tried docker ps, docker exec -it...., ssh.... I don't see it running and I can't access the container. I can't even access it from the console from cockpit ui. 

I can see it reported as running though in the cockpit ui. Am I missing something here

**Comment by martinpitt** [comment]
Well yes.. podman and docker are two entirely parallel and independent container runtimes. cockpit-podman is not meant to see docker containers and vice versa.
