### ISSUE TITLE
firewall: Add services dialog's visuals are odd

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#17615]
![image](https://user-images.githubusercontent.com/10246/182181885-f27a7e2b-bbf8-4e1b-9469-4f093a8c52e6.png)

The search entry is not obvious; it's almost hidden in this layout.

The scrollable services area isn't obviously a scroll box. It looks like there are just 4 services available.

**Comment by garrett** [comment]
Oh, this is a regression, due to #17612. Here's what it looked like before:

![image](https://user-images.githubusercontent.com/10246/182182673-7f7049bd-bf90-4863-9bae-b7fc03172a00.png)

I guess also this means there's no pixel test for this dialog.

At least the filter issue would be fixed by this. I wonder if there's a better way to address this than doing a revert. Meanwhile, I'm going to make this a release-blocker as the fix should be relatively simple... or we should revert the #17612 before the release.

**Comment by garrett** [comment]
We could probably improve the overflow area by adding a border on the edges too, to indicate that it's scrollable. Overflow, even set to scroll, doesn't show a scrollbar except on hover on browsers that have transient scrollbars.

Adding the border would be something like this:

```scss
#add-services-dialog .service-list {
  border: 1px solid var(--pf-c-data-list--BorderTopColor);
}
```

(The component does not have any border color except for top. We could otherwise use the global PF border color, which `--pf-c-data-list--BorderTopColor` is aliased to.)

**Comment by martinpitt** [comment]
@garrett: PR #17614 failed due to exactly this issue -- see e.g. [this pixel diff/failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17614-20220801-150332-5d05b4ce-fedora-36/pixeldiff.html#TestFirewall-testAddServices-firewall-add-services-to-zone-modal), which is (1) exactly this dialog (i.e. we *do* have a pixel test), and (2) hopefully we didn't regress that in main, but it's only in that PR?

**Comment by martinpitt** [comment]
Very odd -- it also failed that way in a totally unrelated [centos-7 image refresh](https://github.com/cockpit-project/bots/pull/3685). Is that perhaps sometimes looking like this and like that?

**Comment by garrett** [comment]
It looks as expected in Chrome (Version 103.0.5060.134 (Official Build) unknown (64-bit)):

![Screenshot from 2022-08-02 15-16-51](https://user-images.githubusercontent.com/10246/182384091-9c14b833-87a4-4e1a-a4e3-a3895c6060b7.png)
