### ISSUE TITLE
Duplicate timestamps on dashboard graph?

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1762]
duplicates of 17:56, 17:57 etc.
![screenshot from 2015-01-30 17 59 20](https://cloud.githubusercontent.com/assets/209895/5979651/d21ac24a-a8a9-11e4-941e-1cc5cd0b8250.png)

Is this actually 17:56:00 and 17:56:30?

**Comment by mvollmer** [comment]
Yep, good catch.
