### ISSUE TITLE
React code splitting

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#17643]
To improve our time-to-load experience (performance), we should consider code splitting. React + WebPack can do this.

React docs on code splitting: https://reactjs.org/docs/code-splitting.html

Using "Suspense" on web.dev: https://web.dev/code-splitting-suspense/

We might want to pick a slower-loading page to start and see what it's like. Or we could pick one of the simpler pages to experiment.

**Comment by KKoukiou** [comment]
Tried this out https://github.com/KKoukiou/cockpit/commit/0156fa00844c4f927e823ac30508e57dcc06ef9c 

There is not much of a improvement compared to the code complexity added. In addition I hit some issues that I was not able to solve.

I don't see the reason of keeping this issue open further.
