### ISSUE TITLE
hang when repeat same hostname or same ip when adding a remote host

### ISSUE THREAD

**Issue by jeffvance** [cockpit-project/cockpit#1766]
Cockpit Version 0.38.
Attempting to add a remote host to cockpit using hostname and same credentials, but receive error:
   "Cockpit is not installed on the host."  # still debugging as to why, but that's not this issue...

If I retry using the same hostname, instead of the above error it just hangs.
If I retry using the IP of the remote host I see the same "Cockpit is not installed on the host" error.
If I repeat using the same IP, instead of that error  msg it hangs again.
Re-logging-in to the Cockpit GUI clears the problem and I can reuse the hostname and/or ip.

**Comment by jeffvance** [comment]
This problem may be related to different cockpit versions: 0.38 on my laptop but 0.27 on the VMs.

**Comment by stefwalter** [comment]
Seems to have been fixed.
