### ISSUE TITLE
Realm join just spins forever(? at least ~5 minutes) if realmd/packagekitd crash underneath it

### ISSUE THREAD

**Issue by AdamWill** [cockpit-project/cockpit#17675]
### Explain what happens

Looking through Fedora openQA test failures, I caught one where the FreeIPA realm join test failed because it just span forever after hitting the Join button: see [video](https://openqa.stg.fedoraproject.org/tests/1999742/video?filename=video.ogv) (will be garbage collected in a couple of weeks). It seems like what happened is that packagekitd crashed underneath realmd, but this didn't percolate back up to an error in Cockpit. I'm not sure if realmd noticed that packagekitd had crashed - it may be that this is a bug in realmd, in which case we can redirect it.

Here's the log messages indicating packagekitd crashed:

    Aug 25 07:09:15 client002.test.openqa.fedoraproject.org realmd[1566]:  * Installing necessary packages: freeipa-client oddjob oddjob-mkhomedir
    Aug 25 07:09:15 client002.test.openqa.fedoraproject.org realmd[1566]: packages: CreateTransaction call
    Aug 25 07:09:15 client002.test.openqa.fedoraproject.org realmd[1566]: packages: freeing transtaction
    Aug 25 07:09:15 client002.test.openqa.fedoraproject.org realmd[1566]: packages: SetHints call
    Aug 25 07:09:15 client002.test.openqa.fedoraproject.org realmd[1566]: packages: call InstallPackages (1, ['freeipa-client;4.10.0-3.fc37;x86_64;fedora', 'oddjob;0.34.7-6.fc37;x86_64;fedora', 'oddjob-mkhomedir;0.34.7-6.fc37;x86_64;fedora'])
    Aug 25 07:09:15 client002.test.openqa.fedoraproject.org PackageKit[1578]: uid 0 is trying to obtain org.freedesktop.packagekit.package-install-untrusted auth (only_trusted:0)
    Aug 25 07:09:15 client002.test.openqa.fedoraproject.org realmd[1566]: packages: call InstallPackages completed
    Aug 25 07:09:15 client002.test.openqa.fedoraproject.org PackageKit[1578]: new install-packages transaction /9_cdabeeaa scheduled from uid 0
    Aug 25 07:09:15 client002.test.openqa.fedoraproject.org PackageKit[1578]: uid 0 obtained auth for org.freedesktop.packagekit.package-install-untrusted
    Aug 25 07:09:16 client002.test.openqa.fedoraproject.org packagekitd[1578]: corrupted double-linked list
    Aug 25 07:09:16 client002.test.openqa.fedoraproject.org audit[1578]: ANOM_ABEND auid=4294967295 uid=0 gid=0 ses=4294967295 subj=system_u:system_r:rpm_t:s0 pid=1578 comm="PK-Backend" exe="/usr/libexec/packagekitd" sig=6 res=1
    Aug 25 07:09:16 client002.test.openqa.fedoraproject.org systemd[1]: Created slice system-systemd\x2dcoredump.slice - Slice /system/systemd-coredump.
    Aug 25 07:09:16 client002.test.openqa.fedoraproject.org audit: BPF prog-id=116 op=LOAD
    Aug 25 07:09:16 client002.test.openqa.fedoraproject.org audit: BPF prog-id=117 op=LOAD
    Aug 25 07:09:16 client002.test.openqa.fedoraproject.org audit: BPF prog-id=118 op=LOAD
    Aug 25 07:09:16 client002.test.openqa.fedoraproject.org systemd[1]: Started systemd-coredump@0-1734-0.service - Process Core Dump (PID 1734/UID 0).
    Aug 25 07:09:16 client002.test.openqa.fedoraproject.org audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@0-1734-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
    Aug 25 07:09:19 client002.test.openqa.fedoraproject.org [1736]: [164B blob data]
    Aug 25 07:09:19 client002.test.openqa.fedoraproject.org systemd-coredump[1735]: [🡕] Process 1578 (packagekitd) of user 0 dumped core.

But there's nothing after that from realmd or cockpit. Nothing else except unrelated messages is logged until five minutes later, when the test gives up waiting and logs into a console to dump logs:

    Aug 25 07:14:20 client002.test.openqa.fedoraproject.org systemd[1]: Started getty@tty6.service - Getty on tty6.

So I guess it's possible cockpit would've eventually timed out - if it's a five minute timeout or longer, the test may not have waited long enough to hit it. But it seems like "the package install failed because packagekitd crashed" ought to be caught *immediately*, really.

I've filed the packagekit crash [separately](https://bugzilla.redhat.com/show_bug.cgi?id=2121498), for the record.

### Version of Cockpit

274.1

### Where is the problem in Cockpit?

Overview

### Server operating system

Fedora

### Server operating system version

37

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
I tried to reproduce this on current Fedora 37 on the CLI:
```
# watch what's going on
journalctl -f -u realmd
```
another terminal:
```
rpm -e freeipa-client
realm join COCKPIT.LAN
```
and while the above is running, `pkill -e -SEGV packagekitd`. This indeed makes `realm join` hang indefinitely, nothing happens after this:

```
realmd[2262]:  * Resolving required packages
realmd[2262]: packages: CreateTransaction call
realmd[2262]: packages: SetHints call
realmd[2262]: packages: call Resolve (327680, ['freeipa-client', 'oddjob', 'oddjob-mkhomedir', 'sssd'])
realmd[2262]: packages: call Resolve completed
```

This isn't something which we can fix on the cockpit side, so I filed https://bugzilla.redhat.com/show_bug.cgi?id=2157849 to report it against realmd. Thanks!
