### ISSUE TITLE
"Metrics settings" allow to trigger package installation when it shouldn't

### ISSUE THREAD

**Issue by ancorgs** [cockpit-project/cockpit#17693]
### Explain what happens

Let's start with the part that works correctly. :wink:

There is logic in the UI to decide whether the button "Install cockpit-pcp" should be displayed. That logic relies quite directly on `packagekit.detect()` which checks for two circumstances:

- PackageKit is available
- `/usr` is not mounted as "ro" (ie. we are not in a transactional system like CoreOS, Silverblue or openSUSE Micro).

That looks quite correct... although I have a question about it. See [1].

Now the not-so-working part. You can also trigger the same software installation via "Metrics settings" -> "Collect metrics". And that doesn't see to be protected (see [2]). So it's relatively easy to get the software installation of packages started in a system in which it cannot succeed. The exact error depends on the system:

In a "regular" Fedora without PackageKit:

![fedora](https://user-images.githubusercontent.com/3638289/187717126-c9bd994f-8805-418e-b847-bf365337322c.png)

In Fedora CoreOS (read-only file-system), no matter where PackageKit is available or not:

![coreos](https://user-images.githubusercontent.com/3638289/187718151-6beba34f-5ca1-43e7-9c97-ceab9e528483.png)

In an early prototype of openSUSE ALP (kind of equivalent at this point in time to MicroOS):

![alp](https://user-images.githubusercontent.com/3638289/187718402-0801d943-2c68-4532-a3da-da888ddc210c.png)

So I guess that "collect metrics" (or maybe the whole "metrics settings" button) should also check for `packagekit.detect()`. Isn't it?

[1] Is there any plan to better support transactional systems in the future? Something like offering to install the packages and then reboot (installing via rpm-ostree or maybe adding some capabilities to PackageKit so it can handle transactional systems)?

[2] There is [some logic](https://github.com/cockpit-project/cockpit/blob/ff02d58b2523f23d8ab501e411d5576e9d0b54f4/pkg/metrics/metrics.jsx#L1301) to disable the "Metric settings" button, but reading the code I don't quite get what's the intention. I was able to get the button disabled once (not sure doing what), but in general is always on.

PS.- I would say that at some point I was able to trigger a different error in which simply nothing happened when clicking on "save" in the "metrics settings" pop-up. No error or feedback at all. I cannot reproduce it any longer, but maybe it rings a bell to someone.

### Version of Cockpit

271

### Where is the problem in Cockpit?

Metrics

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
> "collect metrics" (or maybe the whole "metrics settings" button) should also check for packagekit.detect().

Very much so, thanks for reporting! I'll look into that.

> support transactional systems in the future?

From our side there is https://github.com/cockpit-project/cockpit-ostree/ , which provides a "Software Updates" page for rpm-ostree. We do not intend to transparently do overlay installs on ostree -- while many of them work, that's not how you are supposed to use coreos. So cockpit should just not offer on-demand installation there.

> [some logic](https://github.com/cockpit-project/cockpit/blob/ff02d58b2523f23d8ab501e411d5576e9d0b54f4/pkg/metrics/metrics.jsx#L1301) to disable the "Metric settings" button

This code is just for disabling the button while the page is loading or the status is being changed, to avoid race conditions. It's not related to on-demand install. On OSTree systems it may still make sense to show that config dialog, just on-demand install should not happen.

**Comment by martinpitt** [comment]
Fixed in PR #17713
