### ISSUE TITLE
Multiple terminal tabs

### ISSUE THREAD

**Issue by eugrus** [cockpit-project/cockpit#17725]
Page: Terminal

Couldn't introducing multiple terminal tabs (like in Windows Terminal) be a good idea?

**Comment by garrett** [comment]
As a workaround for now, you can middle click (or hold down control and click, or right click and select "open link in new tab") the "Terminal" item in the side navigation to have multiple terminal tabs in your browser.

I know it's not the same as tabs in the page; however, Cockpit's terminal is supposed to be something you use all the time. There are limitations in browsers that makes pressing certain key combinations problematic (except in [Cockpit Client](https://flathub.org/apps/details/org.cockpit_project.CockpitClient), the Linux desktop UI for Cockpit).

We do have an open issue about having a minimal UI version of the terminal @ https://github.com/cockpit-project/cockpit/issues/16584 which would make a multi-window (or multi-browser-tab in most browsers) work in a better way. It's somewhat related.

**Comment by alanmilinovic** [comment]
> As a workaround for now, you can middle click (or hold down control and click, or right click and select "open link in new tab") the "Terminal" item in the side navigation to have multiple terminal tabs in your browser.
> 
> I know it's not the same as tabs in the page; however, Cockpit's terminal is supposed to be something you use all the time. There are limitations in browsers that makes pressing certain key combinations problematic (except in [Cockpit Client](https://flathub.org/apps/details/org.cockpit_project.CockpitClient), the Linux desktop UI for Cockpit).
> 
> We do have an open issue about having a minimal UI version of the terminal @ #16584 which would make a multi-window (or multi-browser-tab in most browsers) work in a better way. It's somewhat related.

Middle click is not working, like stated here  #13396
