### ISSUE TITLE
applications not listed on ubuntu

### ISSUE THREAD

**Issue by kinghat** [cockpit-project/cockpit#17737]
### Explain what happens

1. on a fresh install of ubuntu 22.04 and a 20.04 install all of the official packages are not listed. hitting the refresh button doesnt help.

# 22.04.1 shows:

![image](https://user-images.githubusercontent.com/16073360/190308430-f01fe377-20f2-41a2-bb87-585fb0ac3b2b.png)

## installed version(upgraded to backports):

> $ apt list -a --installed cockpit*
> Listing... Done
> cockpit-bridge/jammy-backports,now 276.1-1~bpo22.04.1 amd64 [installed,automatic]
> cockpit-bridge/jammy 264-1 amd64
> 
> cockpit-networkmanager/jammy-backports,now 276.1-1~bpo22.04.1 all [installed,automatic]
> cockpit-networkmanager/jammy 264-1 all
> 
> cockpit-packagekit/jammy-backports,now 276.1-1~bpo22.04.1 all [installed,automatic]
> cockpit-packagekit/jammy 264-1 all
> 
> cockpit-pcp/jammy-backports 276.1-1~bpo22.04.1 amd64
> cockpit-pcp/jammy,now 264-1 amd64 [installed]
> 
> cockpit-storaged/jammy-backports,now 276.1-1~bpo22.04.1 all [installed,automatic]
> cockpit-storaged/jammy 264-1 all
> 
> cockpit-system/jammy-backports,now 276.1-1~bpo22.04.1 all [installed,automatic]
> cockpit-system/jammy 264-1 all
> 
> cockpit-ws/jammy-backports,now 276.1-1~bpo22.04.1 amd64 [installed,automatic]
> cockpit-ws/jammy 264-1 amd64
> 
> cockpit/jammy-backports,now 276.1-1~bpo22.04.1 all [installed]
> cockpit/jammy 264-1 all

# 20.04.5 shows:

![image](https://user-images.githubusercontent.com/16073360/190308898-262dc708-a7ea-4ed2-bfff-db8cdb4110bd.png)

## installed version:

> $ apt list --installed cockpit*
> Listing... Done
> cockpit-bridge/focal-backports,now 264-1~bpo20.04.1 amd64 [installed,automatic]
> cockpit-machines/focal-backports,now 263-1~bpo20.04.1 all [installed]
> cockpit-navigator/focal,now 0.5.9-1focal all [installed]
> cockpit-networkmanager/focal-backports,now 264-1~bpo20.04.1 all [installed,automatic]
> cockpit-packagekit/focal-backports,now 264-1~bpo20.04.1 all [installed,automatic]
> cockpit-storaged/focal-backports,now 264-1~bpo20.04.1 all [installed,automatic]
> cockpit-system/focal-backports,now 264-1~bpo20.04.1 all [installed,automatic]
> cockpit-ws/focal-backports,now 264-1~bpo20.04.1 amd64 [installed,automatic]
> cockpit-zfs-manager/focal,now 1.3.0-3focal all [installed]
> cockpit/focal-backports,now 264-1~bpo20.04.1 all [installed]

i am accessing both of those cockpits via cockpit web on fedora:

> cockpit 275
> cockpit-bridge 275
> cockpit-machines 273
> cockpit-networkmanager 275
> cockpit-packagekit 275
> cockpit-pcp 275
> cockpit-storaged 275
> cockpit-system 275
> cockpit-ws 275

### Version of Cockpit

275/3

### Where is the problem in Cockpit?

Applications

### Server operating system

Ubuntu

### Server operating system version

20.04.5 and 22.04.1

### What browsers are you using?

Firefox

### System log

```shell
// 22.04 install after running application refresh

Sep 15 03:35:08 marla-server PackageKit[2464]: resolve transaction /128_baedaeaa from uid 0 finished with success after 251ms
Sep 15 03:35:08 marla-server PackageKit[2464]: search-file transaction /129_ecdccded from uid 0 finished with success after 327ms
Sep 15 03:35:08 marla-server PackageKit[2464]: uid 0 is trying to obtain org.freedesktop.packagekit.system-sources-refresh auth (only_trusted:0)
Sep 15 03:35:08 marla-server PackageKit[2464]: uid 0 obtained auth for org.freedesktop.packagekit.system-sources-refresh
Sep 15 03:35:10 marla-server PackageKit[2464]: refresh-cache transaction /130_eedbcaae from uid 0 finished with success after 1271ms
Sep 15 03:35:11 marla-server tailscaled[897]: Accept: TCP{100.84.132.67:22 > 100.73.179.118:39300} 360 ok out
Sep 15 03:35:11 marla-server PackageKit[2464]: get-updates transaction /131_bbebdbea from uid 0 finished with success after 1144ms
```

**Comment by tiborbokor** [comment]
Same..
Running Ubuntu 22.04.1 LTS

**Comment by alanmilinovic** [comment]
Same on Debian 11 (bullseye).

**Comment by jelly** [comment]
On our own test images:

Fedora 36

![image](https://user-images.githubusercontent.com/67428/202234903-57d755ac-1e92-41f8-874d-060b2917f2e7.png)

Debian 11

![image](https://user-images.githubusercontent.com/67428/202234984-3f83f492-9d0a-4072-bb72-1dfaf2baf650.png)

**Comment by alanmilinovic** [comment]
I can confirm the same.

**Comment by jelly** [comment]
This looks like it makes sense as we have appstream xml files for, these pages.

```
pkg/kdump/org.cockpit-project.cockpit-kdump.metainfo.xml.in
pkg/selinux/org.cockpit-project.cockpit-selinux.metainfo.xml.in
pkg/sosreport/org.cockpit-project.cockpit-sosreport.metainfo.xml.in
pkg/storaged/org.cockpit-project.cockpit-storaged.metainfo.xml.in
```

From the original issue comment, it only makes sense to add everything which is not cockpit-ws/cockpit-system. So

```
ii  cockpit-networkmanager                           277.36.gce52c4ee1.dirty-1      all          Cockpit user interface for networking
ii  cockpit-packagekit                               277.36.gce52c4ee1.dirty-1      all          Cockpit user interface for packages
ii  cockpit-pcp                                      277.36.gce52c4ee1.dirty-1      amd64        Cockpit PCP integration
ii  cockpit-sosreport                                277.36.gce52c4ee1.dirty-1      all          Cockpit user interface for diagnostic reports
```

@marusak @martinpitt thoughts?

**Comment by KKoukiou** [comment]
@jelly we don't want to show cockpit-NM as it's not working for ubuntu by default  - see https://github.com/cockpit-project/cockpit/issues/17040

The other too should be exposed from my understanding.

**Comment by crawforc3** [comment]
Is there a way to install applications even if they aren't shown in the applications page?

**Comment by jelly** [comment]
> Is there a way to install applications even if they aren't shown in the applications page?

I'm not sure what you mean? The applications page shows the installed applications, you usually install applications with your distributions package manager.

**Comment by martinpitt** [comment]
Indeed the appstream file is mysteriously missing in [cockpit-pcp](https://packages.ubuntu.com/kinetic/amd64/cockpit-pcp/filelist). It's fine in [cockpit-storaged](https://packages.ubuntu.com/kinetic/amd64/cockpit-storaged/filelist) and other packages. I'll have a look.

**Comment by BrunoDSL** [comment]
I'm running the latest backports version of cockpit on the latest Ubuntu Server (22.04.3 LTS) and I still have this issue. While it did give me the option to install the file the first time I entered the page, nothing happens after that. It only displays the applications which are already installed. No amount of clicking refresh, reloading the browser or rebooting the machine does anything.

**Comment by mihkel-ra** [comment]
I have the same issue, also on 22.04.3 and cockpit from backports (306). 
Installed cockpit packages:
`cockpit-bridge/jammy-backports,now 306-1~bpo22.04.1 amd64 [installed,automatic]
cockpit-networkmanager/jammy-backports,now 306-1~bpo22.04.1 all [installed,automatic]
cockpit-packagekit/jammy-backports,now 306-1~bpo22.04.1 all [installed,automatic]
cockpit-storaged/jammy-backports,now 306-1~bpo22.04.1 all [installed,automatic]
cockpit-system/jammy-backports,now 306-1~bpo22.04.1 all [installed,automatic]
cockpit-ws/jammy-backports,now 306-1~bpo22.04.1 amd64 [installed,automatic]
cockpit/jammy-backports,now 306-1~bpo22.04.1 all [installed]
`
Applications page only shows networking and storage (installed), refreshing does not reveal any available packages.

**Comment by tbukfrc** [comment]
Same issue here, running cockpit 310 from the jammy backports (Ubuntu 22.04.04), and my "applications" tab is only Networking and Storage.

**Comment by dr-msr** [comment]
no update on the issue?

**Comment by n0xy1** [comment]
+1 on the same problem here

**Comment by colonelmatrix** [comment]
same for me too

**Comment by DrDirtyDevil** [comment]
i have got the same problem on debian 12

**Comment by yodaphone** [comment]
new to cockpit .. installed it and I'm having the same issue with Ubuntu 22.04

**Comment by damoye** [comment]
same for me in debian

**Comment by HVR88** [comment]
>i have got the same problem on debian 12

Here as well, but it hasn't yet been two years, so let's give it some time.

**Comment by maximt** [comment]
same for debian 11
here is error

`
ModuleNotFoundError: No module named 'tracer'
`

after installing  tracer by _pip install tracer_ here is new error

`
ModuleNotFoundError: No module named 'tracer.query'; 'tracer' is not a package
`
```
$ python --version
Python 3.9.2
```
looks like tracer pkg is broken in debian/ubuntu

**Comment by martinpitt** [comment]
@maximt Yes, tracer isn't a thing on Debian/Ubuntu, it's "needrestart" there. This message is harmless and unrelated.

**Comment by dezerving** [comment]
Still same issue. Did anyone manage to find a fix?

**Comment by Talref** [comment]
> Still same issue. Did anyone manage to find a fix?

Webmin

**Comment by thatkid662** [comment]
same issue. what do you mean by webmin?

**Comment by creeperwater** [comment]
Same problem in 2025.

**Comment by ciaoly** [comment]
Still same problem on Debian 12 bookworm.

**Comment by mmosquera91** [comment]
Same issue on Ubuntu 24.04 LTS

**Comment by machitza** [comment]
is this project dead? i tried on a proxmox 9 with debian12, ubuntu 20,22,24.... still nothing

**Comment by fieldwrk** [comment]
I think I figured out why it's happening, posted a comment with all the details here: https://github.com/cockpit-project/cockpit/issues/20354#issuecomment-3743575437
There are a bunch of issues on github related to this, not sure which one would be the primary one
