### ISSUE TITLE
Cockpit just fails completely (yes, I mean it) after fresh install of RHEL 8.6

### ISSUE THREAD

**Issue by argonaut-network** [cockpit-project/cockpit#17732]
### Explain what happens

1. Install RHEL 8 using latest ISO direct from Red Hat, do absolutely zero config OOTB. I mean none at all!
2. `systemctl enable --now cockpit.socket`
3. `sudo dnf install cockpit-pcp`
4. Log in using administrator account
5. Fail. Almost everything just never loads or is a blank page. The frames will load, for example Terminal, but it just says "Loading..." forever. Same with Subscriptions, Software Update, Storage, Logs, Services, Overview, everything. Trying to upgrade from Limited Mode does nothing and doesn't bring up the expected popup.

- Yes, I cleared my cache and tried in Private (Firefox)
- I upgraded all packages using DNF over ssh and restarted both the entire system and the cockpit service before posting
- I can't even view the version of Cockpit from the About page, it just sits and loads forever

I'd really like to not have to reinstall my system, that would be asinine; this server is colocated in a data center and it would be awfully expensive and difficult to try to reinstall.
Potentially helpful info:
- `/var` and `/var/log` are located on separate LVs from root due to having issues with those directories filling up and causing system crashes in the past.
![Screenshot from 2022-09-12 18-38-00](https://user-images.githubusercontent.com/86501673/189770824-d44a00f0-75ab-4525-b8d8-a101a451996a.png)
![Screenshot from 2022-09-12 18-37-27](https://user-images.githubusercontent.com/86501673/189770826-6c8abc53-0597-4973-9563-edc8f56992d4.png)
![Screenshot from 2022-09-12 18-37-17](https://user-images.githubusercontent.com/86501673/189770827-8f6d33c7-97d0-4a15-a97e-06860a3503dd.png)

### Version of Cockpit

cockpit-264.1-1.el8.x86_64

### Where is the problem in Cockpit?

Overview

### Server operating system

Red Hat Enterprise Linux

### Server operating system version

8.6

### What browsers are you using?

Firefox

### System log

```shell
Sep 12 18:47:14 argonet-us-nyc1-1 cockpit-ws[9569]: connection unexpectedly closed by peer
Sep 12 18:48:49 argonet-us-nyc1-1 dbus-daemon[1452]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.240' (uid=1000 pid=9623 comm="cockpit-bridge " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Sep 12 18:49:09 argonet-us-nyc1-1 cockpit-ws[9569]: connection unexpectedly closed by peer
Sep 12 18:49:20 argonet-us-nyc1-1 cockpit-ws[9569]: connection unexpectedly closed by peer
Sep 12 18:49:34 argonet-us-nyc1-1 cockpit-ws[9569]: received invalid HTTP request line
Sep 12 18:49:35 argonet-us-nyc1-1 cockpit-session[9615]: pam_unix(cockpit:session): session closed for user asdf
Sep 12 18:50:50 argonet-us-nyc1-1 systemd[1]: cockpit-wsinstance-https@e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.service: Succeeded.
Sep 12 18:50:50 argonet-us-nyc1-1 systemd[1]: cockpit-wsinstance-https@e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.socket: Succeeded.
Sep 12 18:50:54 argonet-us-nyc1-1 systemd[1]: cockpit-wsinstance-https-factory@2-9562-993.service: Succeeded.
Sep 12 18:50:54 argonet-us-nyc1-1 cockpit-session[10097]: pam_ssh_add: Failed adding some keys
Sep 12 18:50:54 argonet-us-nyc1-1 cockpit-session[10097]: pam_unix(cockpit:session): session opened for user asdf by (uid=0)
Sep 12 18:50:54 argonet-us-nyc1-1 polkitd[1454]: Registered Authentication Agent for unix-session:8 (system bus name :1.261 [cockpit-bridge], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale C.UTF-8)
Sep 12 18:50:55 argonet-us-nyc1-1 dbus-daemon[1452]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.262' (uid=1000 pid=10105 comm="cockpit-bridge " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
```

**Comment by martinpitt** [comment]
Sorry to hear about your trouble! The syslog does not say much indeed. It might be helpful to look at the browser log (Ctrl+Shift+J) while you log into Cockpit and try to do something. If there are any warnings/errors, can you copy&paste them here?

Also, what happens on the server you log into during a session? Does some process use 100% CPU or memory or something such, which would make the communication slow?

It looks like you installed cockpit-ws directly on your server in your data center -- you did not add add it as a remote host in a local cockpit installation, right? That might be worth a try to compare whether the problem is in the web server or the bridge part. If you don't want to install cockpit locally you could also try https://flathub.org/apps/details/org.cockpit_project.CockpitClient on your local machine.

Thanks!

**Comment by argonaut-network** [comment]
Ultimately was a networking issue that didn't rear its ugly head until I decided to finally move on from troubleshooting cockpit. CHECK YOUR MTU FOLKS!

**Comment by martinpitt** [comment]
Hah, thanks for the feedback -- ugly indeed, and very much not obvious..

**Comment by RoepLuke** [comment]
> Ultimately was a networking issue that didn't rear its ugly head until I decided to finally move on from troubleshooting cockpit. CHECK YOUR MTU FOLKS!

**For anyone using WireGuard:**
- https://keremerkan.net/posts/wireguard-mtu-fixes/ 
- https://schroederdennis.de/vpn/wireguard-mtu-size-1420-1412-best-practices-ipv4-ipv6-mtu-berechnen/

The default MTU for WireGuard interfaces is 1420 bytes, which may be too big for IPv6-Connections in some Countries or with some ISPs / transport media. Try 1412 bytes or even 1280 bytes (lower limit for IPv6) as the MTU in your WireGuard config. I had the same behavior as described above, the Browser Console said nothing and the problem seemed to appear and disappear randomly.

@argonaut-network thank you for the hint at the MTU
