### ISSUE TITLE
iscsi section not showing inside of storage tab

### ISSUE THREAD

**Issue by K34nu** [cockpit-project/cockpit#17743]
### Explain what happens

1. Installed open-iscsi, tgt and lvm2
2. Open up cockpit in the web browser
3. doesn't show anything to do with iscsi inside of there.

### Version of Cockpit

debian 11 

### Where is the problem in Cockpit?

Storage

### Server operating system

Debian

### Server operating system version

11

### What browsers are you using?

Edge

**Comment by marusak** [comment]
You need to install `udisks2-iscsi`. This should be suggested while installing cockpit-networkmanger

**Comment by martinpitt** [comment]
Debian's and Ubuntu's udisks2 package does not support/build the iscsi driver, so this functionality is not available on these distributions.
