### ISSUE TITLE
Bypass login with a broken browser?

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#17756]
If a browser fails the feature check, @allisonkarlitskaya says we should allow them to run Cockpit anyway.

The problem is that when they're signed in, then Cockpit _will absolutely_ be messed up.

Therefore, _if_ we had a bypass mechanism, then we also must have a GIANT IN YOUR FACE message when they're signed in to Cockpit that they're using an unsupported browser version and things will be messed up, and they might even lose data or completely corrupt their system. (These are extreme examples. In most cases, someone wouldn't see things correctly or at all or a feature will just not work.)

If someone forces their broken, old, insecure browser to access Cockpit, then there will be problems and we don't want issues reported about things that are not a problem on an updated, good browser.

**Comment by allisonkarlitskaya** [comment]
To be clear, I made this suggestion in light of #17726.

"This is not gonna work, but if you want to proceed then you get to keep both pieces" is a lot more in keeping with the "foss mentality" than "access denied", even if we're right....  The fact that we got it completely wrong in this case only makes it worse.

**Comment by garrett** [comment]
>  The fact that we got it completely wrong in this case only makes it worse.

But we didn't get it completely wrong. It changed in browsers when they implemented level 2.

**Comment by garrett** [comment]
> ...until the next time they change the specs out from under us ;)

That's not going to happen. They didn't change the spec. They implemented it halfway, then the rest. They're not "changing" anything.

**Comment by garrett** [comment]
We'd either have to duplicate the checks in Cockpit or pass the reason over when signing in.

And some things are absolutely no-go, where others might mess up the layout to some degree. (If you don't support flex and grid, things will be really bad, for example. For the :is() and :where(), some things will not show up. For CSS custom properties (variables), Cockpit won't work. For WebSocket, Cockpit also won't work.)

Regardless of checks, if the browser engine is old, it's insecure and people really shouldn't use it with Cockpit.

There are a lot of things to consider, and my point is that it's not as easy as adding a button saying "let me in anyway". We absolutely need to handle it once logged in as well.

But I'm not entirely opposed to it, as long as Cockpit has a big warning at the top with the reason why the check failed and why that matters.

**Comment by garrett** [comment]
I think this was closed with https://github.com/cockpit-project/cockpit/pull/17774. The expander serves as a warning enough already.
