### ISSUE TITLE
Highlight legend in big graphs

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1776]
In the server memory graphs highlight the legend for the series that the mouse is hovering over. That'll help with identifying what it actually is.

**Comment by garrett** [comment]
Legends for memory and CPU were split out to the side of the graphs, recolored for usability & accessibility (tested for all forms of colorblindness and use of contrasting colors is useful even for those of us who can see all colors), and reordered to appear in the same order as the graph in #10282.

We don't have the mouse hovering, but I think the above changes make it a lot clearer.
