### ISSUE TITLE
Login Screen After password change

### ISSUE THREAD

**Issue by Razriel3** [cockpit-project/cockpit#17760]
### Explain what happens

1. logged  in to root account using.
2. under accout tab force 
3. under account route force change I reset the password
4. logout from the system.
5. login to the system

![Capture](https://user-images.githubusercontent.com/106509819/191777677-e705b623-2992-4a94-a81c-a841826cfe1a.JPG)

### Version of Cockpit

tag 220

### Where is the problem in Cockpit?

Accounts

### Server operating system

other

### Server operating system version

YOCTO Framework

### What browsers are you using?

Chrome

### System log

```shell
I guess problem is related to pam configuration.
following the code I have seen in session-utils.c the following remark
/* Certain PAM implementations return PAM_AUTHTOK_ERR if the users input does not
 * match criteria. Let the conversation happen three times in that case.
 */



Jouranlctl:

Sep 22 14:20:04 imx8mn-ddr4-evk cockpit-ws[2096]: cockpit-ws: Failed to open certificate file /run/cockpit/tls/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: No such file or directory
Sep 22 14:20:04 imx8mn-ddr4-evk cockpit-ws[3076]: cockpit-session: pam: You are required to change your password immediately (administrator enforced).
Sep 22 14:20:04 imx8mn-ddr4-evk cockpit-ws[3076]: cockpit-session: pam: You are required to change your password immediately (administrator enforced).
Sep 22 14:20:04 imx8mn-ddr4-evk cockpit-ws[3076]: cockpit-session: user account or password has expired: root: Authentication token is no longer valid; new one required
Sep 22 14:20:04 imx8mn-ddr4-evk cockpit-ws[3076]: cockpit-session: unable to change expired account or password: root: Authentication token manipulation error
Sep 22 14:20:04 imx8mn-ddr4-evk cockpit-ws[3076]: cockpit-session: unable to change expired account or password: root: Authentication token manipulation error
Sep 22 14:20:04 imx8mn-ddr4-evk cockpit-ws[3076]: cockpit-session: unable to change expired account or password: root: Authentication token manipulation error


/var/log/messages:

Sep 22 14:19:45 imx8mn-ddr4-evk daemon.info dbus-daemon[372]: [system] Successfully activated service 'org.freedesktop.hostname1'
Sep 22 14:19:48 imx8mn-ddr4-evk authpriv.info cockpit-session: pam_unix(cockpit:session): session closed for user root
Sep 22 14:19:53 imx8mn-ddr4-evk authpriv.info cockpit-session: pam_unix(cockpit:session): session opened for user root(uid=0) by (uid=0)
Sep 22 14:19:56 imx8mn-ddr4-evk authpriv.info passwd[3070]: password for 'root' changed by 'root'
Sep 22 14:19:59 imx8mn-ddr4-evk authpriv.info cockpit-session: pam_unix(cockpit:session): session closed for user root
Sep 22 14:20:04 imx8mn-ddr4-evk authpriv.notice cockpit-session: pam_unix(cockpit:account): expired password for user root (root enforced)
Sep 22 14:20:04 imx8mn-ddr4-evk authpriv.notice cockpit-session: pam_unix(cockpit:account): expired password for user root (root enforced)
Sep 22 14:20:04 imx8mn-ddr4-evk authpriv.notice cockpit-session: pam_warn(cockpit:chauthtok): function=[pam_sm_chauthtok] flags=0x4020 service=[cockpit] terminal=[<unknown>] user=[root] ruser=[<unknown>] rhost=[<unknown>]
Sep 22 14:20:04 imx8mn-ddr4-evk authpriv.notice cockpit-session: pam_warn(cockpit:chauthtok): function=[pam_sm_chauthtok] flags=0x4020 service=[cockpit] terminal=[<unknown>] user=[root] ruser=[<unknown>] rhost=[<unknown>]
Sep 22 14:20:04 imx8mn-ddr4-evk authpriv.notice cockpit-session: pam_warn(cockpit:chauthtok): function=[pam_sm_chauthtok] flags=0x4020 service=[cockpit] terminal=[<unknown>] user=[root] ruser=[<unknown>] rhost=[<unknown>]
```

**Comment by marusak** [comment]
if you would do `su <user_name>` where `<user_name>` is the account of which you enforced password change what does it output?
For me it is:
```
$ su jiriku
Password: 
You are required to change your password immediately (administrator enforced).
Current password: 
Current Password:
```

Does it ask for `Current password`? That is the pattern that we recognize in our code base.

**Comment by Razriel3** [comment]
I have two terminals to the device one is base on uart and the other based on openssh.
on both I am logged in as root.
doing su root from root after reset gives the following message:
root@imx8mn-ddr4-evk:~# su root
You are required to change your password immediately (administrator enforced).
su: Authentication token is no longer valid; new one required
(Ignored)

but after exiting the openssh terminal ( after resseting from password from cockpit) I get similar message:
root@192.168.8.120's password: 
You are required to change your password immediately (administrator enforced).
Permission denied, please try again.

so I undertand I am also not able to enter ssh terminal anymore.
maybe the  problem is not related to cockpit but to the ssh configuration. can you direct me what can be the reason ?

**Comment by martinpitt** [comment]
In general, changing the password on the login page does work. We have an 
[integration test](https://github.com/cockpit-project/cockpit/blob/69dc4b1eaf6bc2d9c4ef164cbd4b6f8183fd6dc4/test/verify/check-static-login#L262) that checks this at least for a non-root user, on the OSes that we [support](https://cockpit-project.org/running.html#installation-setup). However, we don't test on yocto -- the PAM configuration is annoyingly different between operating systems, and it could very well be that something in the conversation isn't recognized. 

But indeed, if it doesn't work with PAM's own tools on the CLI either, then the login page will just reflect the same error message. So this isn't cockpit specific, but some issue in the PAM config on that machine.
