### ISSUE TITLE
Cockpit doesn't open in Firefox Developer Edition 106.0b3

### ISSUE THREAD

**Issue by doughsay** [cockpit-project/cockpit#17767]
### Explain what happens

1. Open Cockpit in latest Firefox Developer Edition
2. Get the following error message:

```
This web browser is too old to run the Web Console (missing selector(:is():where()))
```

### Version of Cockpit

cockpit/jammy-backports 276.1-1~bpo22.04.1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Ubuntu

### Server operating system version

22.04.1

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
> cockpit/jammy-backports 276.1-1~bpo22.04.1

This is precisely the bug that got *fixed* in that version. Did you perhaps try this right after upgrading? Perhaps the browser used a cached page or so? Please try this with a force-reload (Ctrl+Shift+R), or in a private window. Please also make sure that the running service is up to date, with `sudo systemctl stop cockpit` (the socket unit will auto-restart it).

Please also see https://launchpad.net/bugs/1990623

**Comment by doughsay** [comment]
Hey, sorry for adding noise, it does seem like it was some very aggressive caching.  A force refresh in firefox cleared it up, thanks!

**Comment by martinpitt** [comment]
*phew*, thanks for confirming!

**Comment by gorsing** [comment]
Use Google Chrome browser

**Comment by garrett** [comment]
@gorsing: Many of us (myself included) use Firefox as our primary browser. We develop Cockpit using Firefox, and we test Cockpit in Firefox too.

(There are a few on the team who also use Chrome as their primary browser as well, but I think most of us mainly use Firefox. Regardless, we all test Cockpit in both of these browsers — as well as WebKit too, which is used in GNOME Web, Safari, and our own Cockpit Client app.)
