### ISSUE TITLE
Rendering of update description is 'weird'

### ISSUE THREAD

**Issue by supakeen** [cockpit-project/cockpit#17789]
### Explain what happens

1. Open an update with a description. 
2. This is rendered as 'markdown'
3. This doesn't look that good:

![Screenshot_2022-10-04_11-41-34](https://user-images.githubusercontent.com/39536295/193787831-fca4889c-f234-43db-8798-787afcfbf4ab.png)

(sidenote: where is this markdown coming from?)
(sidenote: it seems like the first line of this markdown is also used in the table view, making some things *clickable* without a visually-clickable style).

### Version of Cockpit

main

### Where is the problem in Cockpit?

Software updates

### Server operating system

Fedora

### Server operating system version

Fedora 37

### What browsers are you using?

Chrome

**Comment by jelly** [comment]
I can see the same on Fedora 37

![image](https://user-images.githubusercontent.com/67428/193794569-5f7b1e6e-2c38-4e79-ba30-104ac4a027f4.png)

There should be some separation between "Bugs" or "Errata" or whatever the DescriptionList is and the actual description

**Comment by garrett** [comment]
Can we use some form of layout in the details? Perhaps have packages and bugs on the left and changelog on the right? It could be a flex which would change to being stacked vertically when space doesn't allow for layout. Or it could be a grid with a breakpoint.

And, of course, changelog markdown should be properly formatted, with correct links, etc.

**Comment by supakeen** [comment]
I would suggest to put the description inside a 'container' so it's clear what's part of cockpit and what's part of the upstream release notes. Personally I feel like markdown shouldn't be rendered at all here and it could be shown in a code block unrendered but that's just me :)
