### ISSUE TITLE
Update page links do not work

### ISSUE THREAD

**Issue by supakeen** [cockpit-project/cockpit#17788]
### Explain what happens

1. Open update page.
2. Find an update that has a link in its description.
3. Click this link.
4. "This content is blocked. Contact the site owner to fix the issue."

Likely due to not allowed to frame the external website.

### Version of Cockpit

main

### Where is the problem in Cockpit?

Software updates

### Server operating system

Fedora

### Server operating system version

Fedora 37

### What browsers are you using?

Chrome

**Comment by jelly** [comment]
PackageKit gives us an `update_text` which is marked as markdown and parsed using `remarkable` (nodejs module) and unlike our bug/cve links these do not get a `target="_blank"` or `noopener` attribute set.

**Comment by garrett** [comment]
@jelly: Oh, we _absolutely **need**_ a target and noopener on those links. :frowning_face:
