### ISSUE TITLE
Path to docker is wrong for (open)SUSE

### ISSUE THREAD

**Issue by kkaempf** [cockpit-project/cockpit#1779]
For (open)SUSE, it's `/usr/bin/docker` instead of `/var/lib/docker`

**Comment by stefwalter** [comment]
I only see ```/var/lib/docker``` in pkg/shell/cockpit-docker.js where we are monitoring the directory for changes, in order to update the containers page display. I think ```/usr/bin/docker``` refers to the binary docker command. So they are not the same thing. Where does docker store its images/containers by default on openSUSE?

**Comment by petervo** [comment]
The docker api endpoint info returns the location it's running in, might be worth using that in cockpit-docker.js

**Comment by kkaempf** [comment]
Argh, no, this was entirely my fault. Cockpit and Docker are doing fine on SUSE without this path.

**Comment by stefwalter** [comment]
@petervo does make a good point though. @petervo could you break that out into a separate issue?
