### ISSUE TITLE
Tunelled cockpit sessions don't ask for password when session is established anymore

### ISSUE THREAD

**Issue by adamruzicka** [cockpit-project/cockpit#17793]
### Explain what happens

We have an integration in Foreman which tunnels cockpit from Foreman to a remote host through ssh (more details here https://github.com/theforeman/foreman_remote_execution/pull/680#issuecomment-1057961602).

Part of the integration which we were about to add is the PR mentioned above. Foreman may already know a sudo password for the remote host and in case the ssh connection is established as an unprivileged user we wanted to inject the password into the flow of cockpit's messages. It might be a hacky hack, but it seemed to work.

On EL7 (cockpit-195.12), this worked, the remote end would send a message like `{"command":"authorize","challenge":"plain1:726578:","cookie":"askpass173401664972727"}`, on Foreman's side, we would catch it inside cockpit-session script and craft a fake response, containing the password.

On EL8 (cockpit-264.1), this does not work anymore as the `authorize` command message never comes. The UI ends up in the limited access mode, I can turn on administrative access and provide the password manually, but I have not found a way how I could hook into the process and provide the password without having the user type it in.

I recall it used to work on EL8 around the time the PR above was opened, no idea what cockpit version it had back then. Gut feeling tells me it might be caused by fixing issue https://github.com/cockpit-project/cockpit/issues/17169 , but I might be wrong about that. In case it is caused by that, is there a way to bring the old behavior back through configuration?

CC @mvollmer iirc you wrote the first version of foreman-cockpit integration, any ideas?

### Version of Cockpit

264.1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Red Hat Enterprise Linux

### Server operating system version

8.6

### What browsers are you using?

Firefox

**Comment by mvollmer** [comment]
> is there a way to bring the old behavior back through configuration?

You are on the right track.  The cockpit-bridge needs to be told during startup to start "sudo". I'll have to dig into the code a bit to figure out how that can be done in your case.

(I wasn't aware that you got sudo working, nice! This is certainly something we want to support also, and it's not a hack in my view.)

**Comment by mvollmer** [comment]
> Gut feeling tells me it might be caused by fixing issue #17169

Hmm, I don't think so.  This was fixed by #17196, which only changed what cockpit-bridge does when it starts another cockpit-bridge via SSH on another host.  This is not what is happening with Foreman, I think.

**Comment by adamruzicka** [comment]
> Hmm, I don't think so.

It wouldn't be the first time I was wrong about something :)

> You intercept the 'init' message from cockpit-ws to the bridge and modify it by including superuser: { id: "any" } in it. It will probably include superuser: { id: "none" } right now.

This did the trick, thank you. The message originally had `superuser: false` in it.

**Comment by adamruzicka** [comment]
Actually, both your suggestions work

**Comment by mvollmer** [comment]
> Actually, both your suggestions work

Yes, and thanks for confirming!  I like the environment variable better.  While supporting automatic sudo for Foreman is a great feature, I am not so sure intercepting messages is the most reliable approach. We should document all this officially, and telling people to intercept and modify messages doesn't feel awesome. :-)

There is some mechanism in cockpit-ws that allows the session helper to tell it a password that it will then use to reply to "authorize" requests. Maybe that can be used instead of intercepting "authorize" messages.

I'll bring this up with the team and think about it some more.
