### ISSUE TITLE
CPU temp disappeared after installing cockpit-pcp on Raspberry Pi 4 Model B Rev 1.4

### ISSUE THREAD

**Issue by maxdelia** [cockpit-project/cockpit#17797]
### Explain what happens

In a fresh install via backports the CPU temp is correctly visible inside the CPU card under metrics, but after installing `cockpit-pcp` for enabling metrics history the temp disappears!

In the console of my browser I can see the following error:
```
CPU temperature metric closed: Object {
  "command": "close",
  "channel": "2:7!262",
  "problem": "not-supported"
}
```

The system seems to be able to detect the CPU temp:

`grep -r . /sys/class/hwmon/hwmon*/name` returns
```
/sys/class/hwmon/hwmon0/name:cpu_thermal
/sys/class/hwmon/hwmon1/name:rpi_volt
```
`grep -r . /sys/class/hwmon/hwmon*/temp*` returns
```
38946
```

### Version of Cockpit

276.1-1~bpo11+1

### Where is the problem in Cockpit?

Metrics

### Server operating system

Debian

### Server operating system version

Debian GNU/Linux 11 (bullseye)

### What browsers are you using?

Chrome

### System log

```shell
Oct 09 10:56:23 pi40 cockpit-pcp[15725]: unknown internal metric cpu.temperature
Oct 09 10:59:21 pi40 cockpit-pcp[15725]: unknown internal metric cpu.temperature
Oct 09 10:59:23 pi40 cockpit-pcp[15725]: unknown internal metric cpu.temperature
```

**Comment by tomasmatus** [comment]
Interesting bug, I wasn't able to reproduce this on fedora. Could you please send which version of `cockpit-pcp` you have installed?

**Comment by maxdelia** [comment]
> Interesting bug, I wasn't able to reproduce this on fedora. Could you please send which version of `cockpit-pcp` you have installed?

Sure, thanks for taking a look!

I ran `apt-get -V -s install cockpit-pcp` and this was the output:
```
...
cockpit-pcp is already the newest version (239-1).
```

**Comment by marusak** [comment]
239 is super old. How come it has shown temperature before? You need to enable backports to get a new version.

**Comment by maxdelia** [comment]
> 239 is super old. How come it has shown temperature before? You need to enable backports to get a new version.

It worked, thanks! I've used `sudo apt -t bullseye-backports install`.
