### ISSUE TITLE
Stratis feature for cockpit GUI to increase stratis pool

### ISSUE THREAD

**Issue by sirweazel** [cockpit-project/cockpit#17804]
Page: Storage

Stratis is working on implementing the growth of pools as underlying storage increases.
[https://github.com/stratis-storage/stratisd/pull/3035](url)

I tried searching, but i didn't know if any gui changes were being made in tandem with the addition of this function of stratisd.  So I figured if not, I'll at least bring attention and maybe it can be an enhancement to the current storage functions?

Example use case:
Stratis pool is built upon raid device that increases in size from additional drives or replacement with larger drives.

**Comment by mvollmer** [comment]
Nothing is in the works yet, but this sounds like something that Cockpit should support.

**Comment by sirweazel** [comment]
Thank You.
