### ISSUE TITLE
Account expiration datepicker popover is unusable

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#17814]
### Explain what happens

1) Go to the accounts page
2) Click on `edit` after `Never expire account`
3) Click on the calendar icon

![image](https://user-images.githubusercontent.com/67428/195593729-a8e1c169-29f7-481d-8c96-77b95c3108a0.png)

### Version of Cockpit

277

### Where is the problem in Cockpit?

Accounts

**Comment by garrett** [comment]
This is similar to https://github.com/cockpit-project/cockpit/issues/17772, but on a different page. Same solution though... and I think we might want to:

1. Find all instances and change them all.
2. Report the issue with using this by default. (It should possibly append to body by default?)
