### ISSUE TITLE
Debian: No motd for cockpit when upgrading from 239

### ISSUE THREAD

**Issue by pitsi** [cockpit-project/cockpit#17828]
### Explain what happens

I had cockpit 239 installed on a debian 11 system (arm64 on rpi3b+). This is the version that the debian repo provides for stable. Then I noticed that it also provides 276.1 from backports, so I installed that one because it's newer.

And a couple of days later I noticed that cockpit's info message, e.g. 
`Web console: https://rpi3b:9090/ or https://192.168.1.100:9090/`
which was there in 239, was missing from both the issue (the message above the login prompt) and from motd (the message after the login).
For the above behavior in 239, there was a cockpit-related file under both `/etc/issue.d` and /etc/motd.d/, which was actually a symlnk to `/run/cockpit/motd`.
Then I installed 277 on my main system which runs debian unstable x64 and I noticed that the file is missing there as well.

The file in /run is still there, but the symlinks are missing. So, I would like to ask if this is a change from upstream or something is broken on the packages themselves.

### Version of Cockpit

277 and 276.1

### Server operating system

Debian

### Server operating system version

Stable (11) and Unstable

### What browsers are you using?

Other

### System log

```shell
(not applicable)
```

**Comment by KKoukiou** [comment]
The only relevant thing that I can think of is the pam package. If you re using pam < 1.5.0 as a non-root user you will not see the motd messages in cockpit.

Maybe add in the issue here, the pam-modules version and if you 're logging in as root or not. 

From my side I can't reproduce it, I tried in the latest debian unstable image and motd is displayed as expected.

**Comment by pitsi** [comment]
First of all, the issue is still present on cockpit v279 that reached unstable on Nov 8th and stable backports on Nov 11th. Unstable went from v278 to v279 while stable backports went from v276.1 straight to v279. V280 will reach unstable tomorrow probably.

On unstable, pam is on v1.5.2 at the moment and on stable it is (stuck) on 1.4.0. However, regardless of their respective pam versions, both branches had a working motd a while ago.
If possible, please post which pam packages are installed on your end. On my end, they are
```
$ dpkg -l | grep pam
ii  libpam-modules:i386           1.5.2-5                           i386         Pluggable Authentication Modules for PAM
ii  libpam-modules-bin            1.5.2-5                           i386         Pluggable Authentication Modules for PAM - helper binaries
ii  libpam-runtime                1.5.2-5                           all          Runtime support for the PAM library
ii  libpam-systemd:i386           252.1-1                           i386         system and service manager - PAM module
ii  libpam0g:i386                 1.5.2-5                           i386         Pluggable Authentication Modules library
```
for unstable and these
```
$ dpkg -l | grep pam
ii  libpam-modules:arm64           1.4.0-9+deb11u1                          arm64        Pluggable Authentication Modules for PAM
ii  libpam-modules-bin             1.4.0-9+deb11u1                          arm64        Pluggable Authentication Modules for PAM - helper binaries
ii  libpam-runtime                 1.4.0-9+deb11u1                          all          Runtime support for the PAM library
ii  libpam-systemd:arm64           247.3-7+deb11u1                          arm64        system and service manager - PAM module
ii  libpam0g:arm64                 1.4.0-9+deb11u1                          arm64        Pluggable Authentication Modules library
```
for stable.

Also, please note that I am talking about the motd which is displayed on the tty, right above the login prompt, so it should work regardless of which user is logged in or not, because it is made by the file under /etc/issue.d/
The motd that shows up after the log in is made is by the file under /etc/motd.d/.

**Comment by garrett** [comment]
> Also, please note that I am talking about the motd which is displayed on the tty, right above the login prompt

So, to clarify, for everyone here, visually:

**This** is the MOTD message being talked about: (where it says `Web console: https://...` right above `Last login...`) 

![image](https://user-images.githubusercontent.com/10246/203613283-d1b08161-71d2-437f-9829-826e144e2356.png)

_Not_ this message (`The programs included with the Debian GNU/Linux system are free software; ...`):

![Screenshot 2022-11-23 at 18-35-42 Overview - admin@debian](https://user-images.githubusercontent.com/10246/203612656-82f6da85-5504-4bf3-9122-445f3b09a2b7.png)

**Comment by pitsi** [comment]
Although the first one is the one that comes from /etc/motd.d/, yes that is the one I mean, because the motd on the second screenshot just... the contents of /etc/motd.

The one that comes from /etc/issue.d/ can not be seen before any login, unless you are willing to take an actual photo of a screen showing the login prompt. I would, but without cockpit's motd there, it is pointless.

Btw, what is cockpit's version on that system?

**Comment by garrett** [comment]
This is Cockpit in a VM of Debian Stable, built from code that's currently in Cockpit's main branch. It's Cockpit 280 and some commits (most likely completely unrelated) above that. There's likely no code difference that would affect this between Cockpit 279 and Cockpit 280 (and likely 276.1 as well).

**Comment by pitsi** [comment]
Thank you.

So, back to what I said above. Assuming that a related to pam is missing and I do not see cockpit's motd, what am I missing?

**Comment by pitsi** [comment]
One month later, I finally got the same version on unstable and stable-backports. Unstable got 282 10 days ago, but stable-backports jumped from 279 straight to 282.
And nothing has changed on the above. Thanks to the symlinked files above, the system running stable still has cockpit's motd displayed both before and after the login prompt, while the one running unstable has it only on the screen before login.

Is there a compilation parameter that controls this behavior? If not, I have to complain to my distro's maintainers because the needed file(s) are missing from the newer versions of cockpit as seen below
https://packages.debian.org/bullseye/amd64/cockpit-ws/filelist
https://packages.debian.org/bullseye-backports/amd64/cockpit-ws/filelist

**Comment by KKoukiou** [comment]
@pitsi I guess it's then this; https://github.com/cockpit-project/cockpit/commit/5705709d416954c169e9af442ea3460ad48b6e9c

@martinpitt you 're handling the debian packaging still?

**Comment by KKoukiou** [comment]
@pitsi according to the comments on that commit the current behavior is as follows:

+# set up dynamic motd/issue symlinks on first-time install; don't bring them back on upgrades if admin removed them

**Comment by martinpitt** [comment]
At first sight I think I screwed up this check:
```
# set up dynamic motd/issue symlinks on first-time install; don't bring them back on upgrades if admin removed them
if [ "$1" = "configure" ] && [ -z "$2" ]; then
```

This needs to additionally check for "upgraded from < 244", as upgrading the package will also make /etc/motd.d/cockpit  go away (as they stopped getting shipped in the .deb). I'll properly reproduce/fix/validate that soon, thanks for reporting!

**Comment by martinpitt** [comment]
Trivially reproducible on our debian-stable image:
```
# dpkg -l cockpit-ws
ii  cockpit-ws     239-1        amd64        Cockpit Web Service

# ls -l /etc/issue.d/cockpit.issue /etc/motd.d/cockpit
lrwxrwxrwx 1 root root 17 Mar  4  2021 /etc/issue.d/cockpit.issue -> /run/cockpit/motd
lrwxrwxrwx 1 root root 17 Mar  4  2021 /etc/motd.d/cockpit -> /run/cockpit/motd

# apt install -t bullseye-backports cockpit-ws

# ls -l /etc/issue.d/cockpit.issue /etc/motd.d/cockpit
ls: cannot access '/etc/issue.d/cockpit.issue': No such file or directory
ls: cannot access '/etc/motd.d/cockpit': No such file or directory
```

This doesn't affect our `image-prepare debian-testing` images because we purge the packages first, so that installing our locally built .debs are a fresh install. This can be turned into an upgrade with:

```diff
--- test/image-prepare
+++ test/image-prepare
@@ -80,7 +80,7 @@ def build_install_package(dist_tar, image):
     # our images have distro cockpit packages pre-installed, remove them
     args = ["--run-command"]
     if 'debian' in image or 'ubuntu' in image:
-        args.append("dpkg --purge cockpit cockpit-ws cockpit-bridge cockpit-system")
+        args.append("echo dpkg --purge cockpit cockpit-ws cockpit-bridge cockpit-system")
     else:
         # subscription-manager-cockpit needs these, thus --nodeps
         args.append("if rpm -q cockpit-ws >/dev/null 2>&1; then rpm --erase --nodeps --verbose cockpit cockpit-ws cockpit-bridge cockpit-system; fi")
```
This reproduces the bug, and validates the fix -- afterwards, the issue/motd symlinks should still be present.

**Comment by martinpitt** [comment]
While looking at this, I also noticed this:
```
dpkg-source: warning: ignoring deletion of directory autom4te.cache
dpkg-source: warning: ignoring deletion of file autom4te.cache/traces.2, use --include-removal to override
```

i.e. our tarballs contain autom4te.cache/. Let's clean this up while at it.

**Comment by martinpitt** [comment]
Fixed both in PR #18137

**Comment by pitsi** [comment]
Please excuse my ignorance... The above mean that
a) both motds were removed at 244 because they were symlinks and were packaged as such instead of being created after installation or by the user
b) on debian, this was causing some issue with the updates, so it was just addressed with the forementioned pr.
Am I right on those? Both answers are good for me and the issue can be closed if everyone is ok with it.

**Comment by martinpitt** [comment]
@pitsi:
a) right, they previously were shipped in the .deb, and version 244 moved to create them dynamically in the postinst. This was necessary to be able to respect admins removing these links.
b) correct, this wrongly handled the upgrade scenario. The PR fixes that, so that an upgrade from stable keeps the links.

**Comment by pitsi** [comment]
Ok then, time to close this one :)

**Comment by martinpitt** [comment]
It would be auto-closed when landing the PR (which didn't land yet), but no worries :-)
