### ISSUE TITLE
Colon in Full Name on account screen has an obscure message.

### ISSUE THREAD

**Issue by AsocPro** [cockpit-project/cockpit#17822]
### Explain what happens

1. On the accounts extension press the create new account button.
2. Fill out the form and include a colon in the Full name field
3. Press create and see the error message: useradd: invalid comment 'UserName:'

![Screen Shot 2022-10-17 at 10 54 00 AM](https://user-images.githubusercontent.com/3435186/196238140-5babfd1c-fa62-4539-abe9-b301c0d50961.png)

This is minor for people who would realize this probably means that the useradd application does not like the colon but the error message could be more clear. It should be pretty simple to check for a colon in the full name field and throw a specific error if a colon is included.

### Version of Cockpit

276.1

### Where is the problem in Cockpit?

Accounts

### Server operating system

CentOS

### Server operating system version

CentOS 8

### What browsers are you using?

Firefox

**Comment by marusak** [comment]
Interesting, man pages for `useradd` define:
```
       -c, --comment COMMENT
           Any text string. It is generally a short description of the account, and is currently used as the field for the user's full name.
```

From `any text string` I would not guess there is limit for characters that one can use. Does anyone know if there are more restrictions? I assume colon is restricted so it does not break `/etc/passwd`.

**Comment by jelly** [comment]
The [useradd](https://man.archlinux.org/man/useradd.8#CAVEATS) man page explains what a valid username is and the regex to verify. So sounds like something we can easily validate.

**Comment by marusak** [comment]
This is not the user name, this is the full name or for the matter of fact any description for the account

**Comment by jelly** [comment]
Aah, woops. Interestingly I can't find anything about "Full name" restrictions, reading the shadow-utils code gives me:

https://github.com/shadow-maint/shadow/blob/master/src/useradd.c#L1258
https://github.com/shadow-maint/shadow/blob/master/src/useradd.c#L93

so yeah a colon is not allowed.

**Comment by AsocPro** [comment]
Yeah I couldn't find anything specifically either on restrictions. I did try a bunch of different special characters and none of them had issues besides colon. which makes sense based on /etc/passwd being comma delimited and the code you linked to.

**Comment by ianbrown78** [comment]
Hi All, I don't appear to have permission to assign this to me, but I have created a PR above with changes to validate the username anyway.
