### ISSUE TITLE
Latest firefox wont load cockpit

### ISSUE THREAD

**Issue by Code-Slave** [cockpit-project/cockpit#17832]
Firefox just updated and all i get now is

This web browser is too old to run the Web Console (missing selector(:is():where()))

**Comment by Code-Slave** [comment]
dupe

**Comment by garrett** [comment]
Apologies for the problem!

Most distributions have had a fix for a few weeks. Some have fixes still pending. I've written a blog post about the issue, complete with an explanation and workarounds: https://cockpit-project.org/blog/login-issues.html

**Comment by Code-Slave** [comment]
fixed it with sed till update is avail. thanks for that
