### ISSUE TITLE
Any Fix for this 

### ISSUE THREAD

**Issue by csj90** [cockpit-project/cockpit#17831]
### Explain what happens

This web browser is too old to run the Web Console (missing selector(:is():where()))
A modern browser is required for security, reliability, and performance.
Download a new browser for free

    [Mozilla Firefox](https://firefox.com/) / Linux, Windows, macOS
    [Google Chrome](https://www.google.com/chrome/) / Linux, Windows, macOS

Or use a bundled browser

    [Microsoft Edge](https://www.microsoft.com/) / Windows
    [Apple Safari](https://www.apple.com/safari/) / macOS

### Version of Cockpit

264-1

### Where is the problem in Cockpit?

Navigation & Shell

### Server operating system

Ubuntu

### Server operating system version

22.04.1 LTS

### What browsers are you using?

Firefox

**Comment by marusak** [comment]
Duplicate of https://github.com/cockpit-project/cockpit/issues/17773

**Comment by garrett** [comment]
Apologies for the problem!

Most distributions have had a fix for a few weeks. Some have fixes still pending. I've written a blog post about the issue, complete with an explanation and workarounds: https://cockpit-project.org/blog/login-issues.html
