### ISSUE TITLE
I can't login into cockpit because my user doesn't have password

### ISSUE THREAD

**Issue by ISukONiA** [cockpit-project/cockpit#17843]
### Explain what happens

I can't login into the interface because I use a private key to login into cockpit.
I prefer not to create another account just for logging in. 

### Version of Cockpit

latest

### Where is the problem in Cockpit?

Accounts

### Server operating system

Ubuntu

### Server operating system version

Ubuntu 22.04.1 LTS

### What browsers are you using?

Edge

**Comment by garrett** [comment]
If you're using a Linux desktop, [Cockpit Client](https://flathub.org/apps/details/org.cockpit_project.CockpitClient) is a desktop app that's able to use ssh key authentication.

General browsers (for good reasons) do not provide access to your ssh configuration directory.

**Comment by KKoukiou** [comment]
See reply in previous comment.

**Comment by carrete** [comment]
> If you're using a Linux desktop, [Cockpit Client](https://flathub.org/apps/details/org.cockpit_project.CockpitClient) is a desktop app that's able to use ssh key authentication.

We're in the same boat. This is an acceptable solution for us. I wish it was easier to find though. Thanks
