### ISSUE TITLE
No Services listed under Memory

### ISSUE THREAD

**Issue by fruchttiger87** [cockpit-project/cockpit#17853]
### Explain what happens

Hi everybody,
I use cockpit for 2 days and I am very impressed how good it is!! The developers made a fantastic job!!!

Explain what happens
I installed the latest version of cockpit from the debian backports on my Raspberry Pi 3B+ with the latest version of Raspbian. I get the services listed that use the most cpu but not the services that use the most ram. Can anyone help and say how to fix that? Is it necessary to configure something in a conf file? I have a screenshot attached.

Version of Cockpit
latest

Where is the problem in Cockpit?
Overview -> Metrics and history -> Memory

Server operating system
Raspbian

Server operating system version
Raspbian Bullseye

System log
No response

![image](https://user-images.githubusercontent.com/63422494/198531607-a0693ba5-1143-47d9-8f20-55aae53127a0.png)

By the way, my debian server on a thinkpad t520 shows everything like expected.

Best regards
fruchttiger

**Comment by jelly** [comment]
What Raspbian is this exactly? Can you provide the content of `/etc/os-release` and output of `systemctl --version`.

The metrics memory feature depends on systemd's cgroups memory accounting feature. This should be enabled out of the box on normal installations.

```
/etc/systemd/system.conf:#DefaultMemoryAccounting=yes
```

So maybe it isn't yet on Raspbian?

**Comment by fruchttiger87** [comment]
I could fix my problems!
The hint with memory accounting was crucial. After searching a little bit I found this thread:
[https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/124](https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/124)
Somebody there had a similar issue and it was fixed by adding

`cgroup_memory=1 cgroup_enable=memory` to the cmdline.txt.

Now everything works as expected. Of course, this is no bug in cockpit.
