### ISSUE TITLE
Unable to communicate with OSTree

### ISSUE THREAD

**Issue by humantex** [cockpit-project/cockpit#17858]
### Explain what happens

1. Logged into Cockpit today
2. installed all updates - including latest Cockpit
3. reconnected and logged back in
4. update page has an error...

_**Unable to communicate with OSTree
OSTree is not available on this system**_

I've been using Cockpit and keeping it and the OS/Kernel/Software updated regularly, and this is the first time I've been presented with any component failures in Cockpit itself. I can still login to the machine itself to do standard upgrades if/when needed, so this isn't a major issue overall.

I did check to see if both Cockpit & Fedora's ostree were installed via dnf, and they showed to be installed with latest versions.

Sorry for the overly long log file... it took me some time between the update and entering this bug report, so there's 'since -120m' worth of data, and hopefully all the relevant details are included. 

: [Log file for download](https://drive.google.com/file/d/1j2Oe-oVKojoKTjVn9Wj07-boU5AqY_dc/view?usp=sharing) :

Relevant cockpit component versions:
cockpit
278
cockpit-bridge
278
cockpit-composer
41
cockpit-file-sharing
2.4.5
cockpit-machines
276
cockpit-navigator
0.5.9
cockpit-networkmanager
278
cockpit-ostree
190.1
cockpit-packagekit
278
cockpit-pcp
278
cockpit-podman
55
cockpit-selinux
278
cockpit-storaged
278
cockpit-system
278
cockpit-ws
278

### Version of Cockpit

278

### Where is the problem in Cockpit?

Software updates

### Server operating system

Fedora

### Server operating system version

Workstation - 36

### What browsers are you using?

Firefox, Chrome

**Comment by tomasmatus** [comment]
Hey! Since you are on Fedora Workstation uninstalling `cockpit-ostree` should fix it for you.
Fedora Workstation doesn't use ostree for its versioning. For that you'd need to use Fedora CoreOS or Silverblue.

**Comment by humantex** [comment]
After removal and a reboot, software updates were again visible and working fine. Perfect solution.
