### ISSUE TITLE
Logs: Unable to insert datetime with space in the "filters"

### ISSUE THREAD

**Issue by huangyxi** [cockpit-project/cockpit#17875]
### Explain what happens

1. Login to cockpit via Chrome
2. Enter "Logs" panel
3. Click "Reset" button in the drop-down menu of "Filters" for reproducibility
4. Type a datetime string with a space (U+0020) (e.g. "2022-11-04 12:34:56" as the format of "YYYY-MM-DD hh:mm:ss" prompted by the (?) button) in the input box of "Since" or "Until"

Then I can't insert space (U+0020) through my keyboard.

Attempt 2:
If I paste the whole string "2022-11-04 12:34:56" (w or w/o quotes) directly into the input box, the rest of the string after space goes to the "--grep" argument as shown in the non-editable command line.
The query results are surely not expected.
<img width="613" alt="cockpit-screenshot" src="https://user-images.githubusercontent.com/32028289/199926113-dcbc67d7-10e4-48ac-a0d5-3afc6a821394.png">

Attempt 3:
If I paste the datetime strings "2022-11-0412:34:56" and "2022-11-0422:34:56" without space or quotes directly into the input boxes of "Since" and "Until" respectively, only one of the two input boxes will be applied to the query argument, and the pasted string will not be echoed in the input box (maybe too long).

Attempt 4:
The only temporary alternative solution I tried is to edit the search bar directly (e.g. "priority:debug since:2022-11-0412:34:56 until:2022-11-0422:34:56"). Obviously this is not an elegant approach.

### Version of Cockpit

276.1-1~bpo22.04.1

### Where is the problem in Cockpit?

Logs

### Server operating system

Ubuntu

### Server operating system version

Ubuntu 22.04.1 LTS (5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022)

### What browsers are you using?

Chrome

**Comment by garrett** [comment]
Definitely a bug. Thanks for reporting this!

I'd also suggest that when improving this, we look at adding a datetime picker, so entering a date + time by clicking around works in addition to typing/pasting a datetime.

https://www.patternfly.org/v4/demos/date-and-time-picker/

(But adding the datetime picker should be secondary to fixing this bug with space handling.)

**Comment by KKoukiou** [comment]
The problem comes from the upstream SearchInput Patternfly React component, which filters out spaces when typing in the form fields. 

Opened an issue there, https://github.com/patternfly/patternfly-react/issues/8369

**Comment by KKoukiou** [comment]
Fixed with https://github.com/cockpit-project/cockpit/pull/18019
