### ISSUE TITLE
limited access

### ISSUE THREAD

**Issue by Razriel3** [cockpit-project/cockpit#17872]
### Explain what happens

I am using cockpit in a YOCTO enviorment.
currently I am able to login with root permission and have all capabilies.
I have created another user in my system and gave him permissons to the following gruops:

groups user
root adm cdrom sudo dip plugdev user

also added the username to the sudowers file

still when I login with this user I see on top message "limited access"
what do I need to do to have full capability for a user which is not root ?

see below print from log message:

Nov  3 07:43:24 imx8mn-ddr4-evk-target1 authpriv.alert sudo: tigogateway : a password is required ; PWD=/run/user/1200 ; USER=root ; COMMAND=validate
Nov  3 07:43:24 imx8mn-ddr4-evk-target1 daemon.info dbus-daemon[211]: [system] Successfully activated service 'org.freedesktop.hostname1'
Nov  3 07:44:03 imx8mn-ddr4-evk-target1 authpriv.alert sudo: tigogateway : a password is required ; PWD=/run/user/1200 ; USER=root ; COMMAND=validate

the last message arrived when trying to click "Turn on administrative access" button

### Version of Cockpit

tag 220

### Server operating system

other

### Server operating system version

YOCTO

### What browsers are you using?

Chrome

### System log

```shell
Nov 03 07:43:24 imx8mn-ddr4-evk-target1 cockpit-tls[114659]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 03 07:43:24 imx8mn-ddr4-evk-target1 cockpit-tls[114659]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 03 07:43:24 imx8mn-ddr4-evk-target1 cockpit-tls[114659]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Nov 03 07:43:24 imx8mn-ddr4-evk-target1 cockpit-tls[114659]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.


getting same messages also when I enter with root
```

**Comment by jelly** [comment]
Are you building cockpit 220? That's a really old release from more then two years ago. I'd advice to try the latest release, but that might not fix your issue.

**Comment by KKoukiou** [comment]
@Razriel3 this is a known limitation in cockpit. We hide parts of the UI if the logged in users is not logged in with the superuser mode. 
See this is already reported in a similar way here: https://github.com/cockpit-project/cockpit/issues/17346
