### ISSUE TITLE
dark mode: Follow-up to fix a few issues

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#17886]
This is a follow-up to #17319, https://github.com/cockpit-project/cockpit-machines/pull/842: 

1. Check popovers to see if the border is the intent (I think it is?) but fix it if it's not.
2. Fix the  lack of spacing under the banner in machines (which affects dark mode). (kkooukiou: This is fixed upstream)

![image](https://user-images.githubusercontent.com/10246/200313783-a597f72a-a576-4fd9-a589-5a372f63780b.png)
![image](https://user-images.githubusercontent.com/10246/200313794-1d58bafc-216c-448d-a98d-32b5e8c39c76.png)

3. Make disabled entries look disabled (similar to what I did with buttons):

![image](https://user-images.githubusercontent.com/10246/200314028-f96bdf88-cc0c-477e-a20f-627bd8fe0577.png)
![image](https://user-images.githubusercontent.com/10246/200314046-871aa034-fac6-481e-88d1-2f5987c4b732.png)

Thanks for [spotting these issues](https://github.com/cockpit-project/cockpit-machines/pull/842#issuecomment-1303703577), @skobyda!

**Comment by septatrix** [comment]
By the looks of it the darkmode only works when javascript is enabled. Is this an upstream limitation?

**Comment by jelly** [comment]
> By the looks of it the darkmode only works when javascript is enabled. Is this an upstream limitation?

Yes the switching is implemented using JavaScript, but Cockpit itself only works with JavaScript so I'm not sure what you are mean exactly?

**Comment by septatrix** [comment]
> Yes the switching is implemented using JavaScript, but Cockpit itself only works with JavaScript so I'm not sure what you are mean exactly?

I was mainly asking for two reasons:

1. The first being that this is the first project I really see using PF4 dark theme and I wasn't sure if it respects the media query without js. Sadly it still seems to be in a limbo state where the theme seems to exists but is neither documented nor advertised on the PF homepage so instructions how to use it do not really exist. And for PF itself a js-less switch is rather important.
2. Additionally, having to implement the switch manually in JS obviously incurs some maintenance and if PF can do this without JS it would most likely be better. Especially if e.g. there may be further `prefers-color-scheme` values or PF implements similar mechanisms like `forced-colors`

**Comment by jelly** [comment]
> > Yes the switching is implemented using JavaScript, but Cockpit itself only works with JavaScript so I'm not sure what you are mean exactly?
> 
> I was mainly asking for two reasons:
> 
> 1. The first being that this is the first project I really see using PF4 dark theme and I wasn't sure if it respects the media query without js. Sadly it still seems to be in a limbo state where the theme seems to exists but is neither documented nor advertised on the PF homepage so instructions how to use it do not really exist. And for PF itself a js-less switch is rather important.

Yes, as far as I know PF switches to dark theme based on `pf-theme-dark` only, this is also what we expect as we want to have the flexibility to override the system settings.

> 2. Additionally, having to implement the switch manually in JS obviously incurs some maintenance and if PF can do this without JS it would most likely be better. Especially if e.g. there may be further `prefers-color-scheme` values or PF implements similar mechanisms like `forced-colors`

That would break what we try to implement (the feature explained above) and honestly the amount of required JavaScript is tiny. Furthermore this is something for the Patternfly project to answer.

**Comment by garrett** [comment]
Related (specific bug about tables in modals in dark mode): https://github.com/cockpit-project/cockpit/issues/17976

**Comment by KKoukiou** [comment]
So this issue is about:
* [x] tooltips which are covered by patternfly issue https://github.com/patternfly/patternfly/issues/5158
* [x] tables in modals which was solved by https://github.com/cockpit-project/cockpit/commit/13c39cabc44555418bccc3e999ea6fad3dec5aa1
* [ ] disabled form elements. ? For these there should have been patternfly issues but I can't find any

**Comment by KKoukiou** [comment]
The disabled form elements are also handled in patternfly in dark mode. The background color changes slightly. The example in the  screenshot above is not disabled form element, it's readonly.
I opened an issue to patternfly to handle this https://github.com/patternfly/patternfly/issues/5302
