### ISSUE TITLE
Allow reauthentication for embedded plugins

### ISSUE THREAD

**Issue by pvoborni** [cockpit-project/cockpit#1788]
With GSS API, embedded plugins in 3rd party apps automatically authenticates (e.g. when user has valid krb ticket) and cockpit creates a session for the user+browser. This session is kept even when user principal changes. So far it's a correct behavior. But when 3rd party app destroy its session and reauthenticates as the new principal, cockpit session will still hold the old principal and therefore will act as incorrect user. Cockpit could not know that the principal is different unless it periodically checks it with re-negotiate which is undesired.

Cockpit should allow the 3rd party app to tell it that principal changed.

For instance it could be plain logout (destroying of session) or a more sophisticated way like "check user's principal on next occasion and act accordingly". 

Note: this method won't handle the case when 3rd party's app session would expire after cockpit's session.

**Comment by stefwalter** [comment]
/me wonders if adding a query string arg to the end of the component url. The query string arg drives the cookie that is used. That means you can use various cookies at will, and essentially accomplish multiple distinct and concurrent logins to cockpit at the same time in the same browser.

**Comment by pvoborni** [comment]
I guess it could work. The query string could be also used for other settings of the embedded plugin.

**Comment by stefwalter** [comment]
Unfortunately the query string approach won't work as the query string won't be transferred to other resources.

Likely this will require a different base url. That is, cockpit uses ```/cockpit/``` as a prefix for loading resources, but we may need to allow something like ```/cockpit+embedder/``` or something like that. Then the two wouldn't share the cookies or browser cache.

**Comment by stefwalter** [comment]
Depends on #1873
