### ISSUE TITLE
dark mode: Switch between auto, light, and dark

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#17900]
Some people may want to use Cockpit in dark or light modes regardless of their system settings.

Aside from aesthetic preferences, Chromium browsers (for quite some time) are flaky when it comes to detecting dark mode. This would provide a way to override whatever the browser thinks is correct (even if it's wrong).

We could either have a modal dialog to switch things, activated from the top-right menu...

![dark-mode-modal](https://user-images.githubusercontent.com/10246/201161296-2787bfd2-8e7d-4c8b-af09-23bc71c2e8a7.png)

Or have the switch directly embedded in the menu, like so many desktop apps are doing:

![dark-mode](https://user-images.githubusercontent.com/10246/201161148-416b8c37-3729-4703-86a3-c58c0dd50c88.png)

Zoomed in:

![dark-menu](https://user-images.githubusercontent.com/10246/201160928-e0a4386c-3926-450f-8836-c92ea4d43f7b.png)

Both mockups use something like the toggle group (https://www.patternfly.org/v4/components/toggle-group), with custom icons I made.

The modal could alternatively use a tile (https://www.patternfly.org/v4/components/tile) or radio buttons.

**Comment by garrett** [comment]
The icons, at least in light mode (we'd need to recolor these for dark mode, of course):

![dark-auto](https://user-images.githubusercontent.com/10246/201162405-3fbfa960-f82a-4832-b4fe-75fd1bbb8e42.svg)

![dark-light](https://user-images.githubusercontent.com/10246/201162398-5702b566-c288-458f-9fa4-f603b66282d7.svg)

![dark-dark](https://user-images.githubusercontent.com/10246/201162404-6433f1a0-c06b-4c68-93b0-900f25c07c49.svg)

I haven't sized these to a standard 16x16, but probably should.

**Comment by septatrix** [comment]
I would prefer the less obtrusive version embedded in the dropdown

**Comment by garrett** [comment]
> I would prefer the less obtrusive version embedded in the dropdown

Cool! Thanks for sharing your opinion; it helps confirm that it's probably the direction we should go. It is what I think we should go for too and I'll push for that design when we implement it. :+1:
