### ISSUE TITLE
Plugins not on official page

### ISSUE THREAD

**Issue by alanmilinovic** [cockpit-project/cockpit#17904]
Anyone knows any user made plugins/applications that ara not on official page? Or if someone made it and would like to share.

**Comment by garrett** [comment]
If you find any apps or plugins not listed @ https://cockpit-project.org/applications.html, please open an issue with information about it on our website repo @ https://github.com/cockpit-project/cockpit-project.github.io/issues/new and/or send a pull request on the https://github.com/cockpit-project/cockpit-project.github.io repo.

(Here's a link to edit the app data directly: https://github.com/cockpit-project/cockpit-project.github.io/edit/main/_data/applications.yml, which will let you save and suggest it as a PR.)
