### ISSUE TITLE
overview: Customize sections

### ISSUE THREAD

**Issue by alanmilinovic** [cockpit-project/cockpit#17901]
Is it possible to modify or extend component html pages without touching the source?

On the Overview page, we have Health, Usage, System information and Configuration. It would be nice for example to be able to add some additional sections, at the moment there is a huge empty space under current sections (at lest on desktop browser).

Overview page is showing most of the information that I need, but what if beside what is already there I want to add some additional information? For example under System information I would like to add Distribution, what is in my case "Debian GNU/Linux 11 (bullseye)". Also for the Usage part, I would like to have CPU temperature displayed or it can be placed under Health as well. Now I need to press on "View metrics and history" to see the temperature.

Same can be applied for sections, if I want to introduce entire new section beside Health, Usage, System information and Configuration.

I know this can all be done by building a new package, but then I would have information split cross two pages  or I would have to build entire new plugin based on existing one.

Some kind of overriding mechanism for component pages would be awesome.

**Comment by alanmilinovic** [comment]
Ok, so I did some digging into code and there is so much logic for example in systemd plugin. I can copy entire source folder from github into my /usr/share/systmd-override and modify it to my needs but I don't want to do that.

That is why creating at least new cards that I can incorporate in existing plugin pages would be nice. Some level of flexibility to customize things is needed in my opinion.

Probably it is a lot of work, any thoughts?

**Comment by garrett** [comment]
Having a UI for customization is probably a bit much. However, it would be pretty neat if we had everything modular in a definition file, or could extend things with a similar file on a system somewhere, so you could do some kind of label + value to show on the page.

We could also reconsider parts that we show on the page as well. 

I know that you've opened https://github.com/cockpit-project/cockpit/issues/17903 (kind of related, but about showing various values by default). I don't think this and that are a duplicate, because I think you're asking for some way to configure the page to show some custom fields... without modifying the source as a one-off.

**Comment by alanmilinovic** [comment]
Exactly, you got the point. I have checked the code and concept you have in place and indeed it is too heavy having UI customized. If we can make it modular without touching the source code, it would be awesome.

Thank you for following up on my cases.

**Comment by garrett** [comment]
> Exactly, you got the point.

(Yep, I wanted to make it clear for whomever may be implementing it. And to restate it with some details to see if I understood what you were asking.)

**Comment by KKoukiou** [comment]
I don't see a clean way of making this part of the UI modular. We generally don't expose page layout/info modification options in cockpit and I believe this is not a direction the team would upvote.
 
I suggest that any missing info on these cards can be discussed in seperete issues and can be added for all users. 


@marusak can you please share you opinion and keep open / close this issue?

**Comment by alanmilinovic** [comment]
Thank you for the update, in the meantime I moved away from Cockpit mainly because of a lack of flexibility in the UI.

Wish you a very happy New Year!

**Comment by marusak** [comment]
I agree with @KKoukiou that making everything extensible, modular and generic would very quickly led down a rabbit hole. We don't want to do that.

Also agree that if you want to add some generic information you deem important we are happy to discuss that.

And I also think that the overview page is already nicely modular, if I want to add my new card that I named `FooCard` to the overview page I only need to copy the overview page and do these changes:
```diff
diff --git pkg/systemd/overview.jsx pkg/systemd/overview.jsx
index 4e26c3882..2c6b16089 100644
--- pkg/systemd/overview.jsx
+++ pkg/systemd/overview.jsx
@@ -33,6 +33,7 @@ import {
 import { superuser } from "superuser";
 
 import { SystemInfomationCard } from './overview-cards/systemInformationCard.jsx';
+import { FooCard } from './overview-cards/fooCard.jsx';
 import { ConfigurationCard } from './overview-cards/configurationCard.jsx';
 import { HealthCard } from './overview-cards/healthCard.jsx';
 import { MotdCard } from './overview-cards/motdCard.jsx';
@@ -170,6 +171,7 @@ class OverviewPage extends React.Component {
                         <HealthCard />
                         <UsageCard />
                         <SystemInfomationCard />
+                        <FooCard />
                         <ConfigurationCard hostname={this.hostname_text()} />
                     </Gallery>
                 </PageSection>
```

Trying to make it modular would make it just more complicated as you would need to well define it and would be brittle. By changing two lines you have all the control you want. Also they are very easy to resolve if a conflict would appear so should be very low maintenance.
