### ISSUE TITLE
Systemctl Always Reports with XML error

### ISSUE THREAD

**Issue by jyxjjj** [cockpit-project/cockpit#17928]
### Explain what happens

1. `systemctl status libvirtd`
2. `XML error: Invalid value for attribute 'value' in element 'allowReboot': 'default'.`
3. It just prints that error and starts normally.
4. I cannot find this attr in all XMLs that created by cockpit.
5. Fedora team leads me here.

### Version of Cockpit

279-1.fc37.x86_64

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Fedora

### Server operating system version

35 to 37

### What browsers are you using?

Chrome

**Comment by jelly** [comment]
Is this with a virtual machine created by cockpit-machines? Can you provide more detailed logs from libvirt from `journalctl -u libvirtd` with more context of the error.

**Comment by jyxjjj** [comment]
Yes, it created by cockpit-machines.
Logs will submitted later, because i cannot connect to my server within several hours.

**Comment by jyxjjj** [comment]
```
Nov 17 16:07:58 fedora systemd[1]: Starting libvirtd.service - Virtualization daemon...
Nov 17 16:07:58 fedora systemd[1]: Started libvirtd.service - Virtualization daemon.
Nov 17 16:07:58 fedora libvirtd[286650]: libvirt version: 8.1.0, package: 2.fc36 (Fedora Project, 2022-03-13-01:12:58, )
Nov 17 16:07:58 fedora libvirtd[286650]: hostname: fedora
Nov 17 16:07:58 fedora libvirtd[286650]: XML error: Invalid value for attribute 'value' in element 'allowReboot': 'default'.
Nov 17 16:26:49 fedora systemd[1]: Stopping libvirtd.service - Virtualization daemon...
Nov 17 16:26:49 fedora systemd[1]: libvirtd.service: Deactivated successfully.
Nov 17 16:26:49 fedora systemd[1]: Stopped libvirtd.service - Virtualization daemon.

```

I think it is not helpful

**Comment by zatricky** [comment]
I'm seeing exactly the same issue, though I suspect it has nothing to do with cockpit as I don't have it installed.

I found a reference to the config item [here](https://www.mail-archive.com/libvir-list@redhat.com/msg227647.html). I'm also unable to find any reference to the configuration within any XML files on my host.

**Comment by zatricky** [comment]
Also note I haven't figured out why libvirtd is stopping aside from that it may be because of this XML error.

**Comment by jyxjjj** [comment]
> I'm seeing exactly the same issue, though I suspect it has nothing to do with cockpit as I don't have cockpit installed.

Ya, so that may means cockpit called a program that same as you manually called, then what is that process, and how it occurred, where to report and how to fix

**Comment by KKoukiou** [comment]
Please reopen for further help if using the new suggested daemons and updating the libvirt/qemu won't solve the issue.

**Comment by zatricky** [comment]
Thank you @KKoukiou. Note that @jyxjjj and I seem to be using the same lib versions for Fedora 36 (not 37). The links you gave look like the right documentation to follow. I will post an update here when I've had an opportunity to try it out. Thanks again. :-)

**Comment by zatricky** [comment]
Can confirm after having gone through the documented process that it is resolved for me. I did end up rebooting the host and restarting virt-manager before some broken functionality worked. Hopefully OP can confirm if the issue is resolved for them as well.

Thanks :-)

**Comment by jyxjjj** [comment]
Okay It seems that i am using virtqemud but i am not sure.
I just found out it and my VMs are running normally, no other errors.
Btw @zatricky do yours running normally too?
Anyway, I read you two's words and i cannot understand what is [this](https://www.mail-archive.com/libvir-list@redhat.com/msg227647.html), due to i am a user not a C developer, but if there is no problem, i can leave it there.
