### ISSUE TITLE
Can not connect to host using a ed25519 host key

### ISSUE THREAD

**Issue by yuergen** [cockpit-project/cockpit#1792]
Cockpit is not able to connect to a target host, when the target host's sshd_config is set up like this:
```
# HostKey for protocol version 1
#HostKey /etc/ssh/ssh_host_key
# HostKeys for protocol version 2
#HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_dsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
```
--> Everything except for ed25519 is disabled.

The entry in the journal is:
`cockpit-ws[28101]: 192.168.1.1: couldn't connect: kex error : no match for method server host key algo: server [ssh-ed25519], client [ecdsa-sha2-nistp256]`

Did I set up something wrong? Can I supply more information?
Thank you for reading!

**Comment by yuergen** [comment]
This issue seems to have something to do with an old entry in /var/lib/cockpit/know_hosts.

If I remove the old ecdsa public key from this file I get another error message as follows:
cockpit-ws[6119]: 192.168.1.1: couldn't connect: kex error : no match for method server host key algo: server [ssh-ed25519], client [ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss]

**Comment by stefwalter** [comment]
I suspect this is libssh: http://www.libssh.org/

I think that 'ed25519' isn't in a release yet. @gladiac can confirm.

I'll close this bug. But if you do find that this is a Cockpit bug, then please let me know and I can reopen it.

**Comment by gladiac** [comment]
We will support ed25519 keys with the next release. I'm just not sure if I release now or wait for chacha20-poly1305 encryption being finished.

**Comment by yuergen** [comment]
Thank you for your quick answer. I have no idea about the schedule of chcha20-poly1305, yet I am looking forward to be able to use ed25519 host keys. :)

**Comment by cgwalters** [comment]
I switched to ED25519 by default and hit this too.  Looking forward to the new libssh!

**Comment by gladiac** [comment]
Well, get it now! :)

https://www.libssh.org/2015/05/11/libssh-0-7-0/

**Comment by cgwalters** [comment]
FWIW I have been following https://stribika.github.io/2015/01/04/secure-secure-shell.html
