### ISSUE TITLE
Cockpit update is ignoring excludes in yum/dnf configurations

### ISSUE THREAD

**Issue by Zlopez** [cockpit-project/cockpit#17955]
### Explain what happens

After excluding package in `/etc/yum.conf` or `/etc/dnf/dnf.conf` the package updates are still shown in cockpit web UI.
Running `dnf check-update` shows no new update.

Content of `/etc/yum.conf`:
```
[main]
gpgcheck=1
installonly_limit=3
clean_requirements_on_remove=True
best=True
skip_if_unavailable=False
excludepkgs=kernel*
```

How to reproduce:
1. Add `excludepkgs=<package_name>` to `/etc/yum.conf` or `/etc/dnf/dnf.conf`
2. Check the updates in cockpit

### Version of Cockpit

279-1

### Where is the problem in Cockpit?

Software updates

### Server operating system

CentOS

### Server operating system version

CentOS 8 Stream

### What browsers are you using?

Firefox

**Comment by KKoukiou** [comment]
This is a long standing [packagekit bug](https://bugzilla.redhat.com/show_bug.cgi?id=1147928) and a workaround from cockpit side it's not possible. 
I found a [suggestion](https://bugzilla.redhat.com/show_bug.cgi?id=1237014#c6) on how to address this as a user, but I can admit is suboptimal.

Closing as there is nothing we can do in cockpit about it.

**Comment by Zlopez** [comment]
Thanks for answer, I added to CC on the bugzilla.
