### ISSUE TITLE
In 281, Services page has black background, other pages are white

### ISSUE THREAD

**Issue by AdamWill** [cockpit-project/cockpit#17978]
### Explain what happens

1. Run the Fedora openQA Cockpit tests on a cockpit-281 build
2. Note that the Services page appears to be using 'dark mode' (i.e. the background is black), but every other page (overview, Logs, Software updates...) is still 'light mode'

Overview: ![overview screenshot](https://user-images.githubusercontent.com/916551/205171226-f0d1e0a3-4b3e-45cf-9105-bda6cf94882f.png)
Logs: ![logs](https://user-images.githubusercontent.com/916551/205171269-ea90c69e-8d00-4c69-b9ca-5850adcf3d7c.png)
But, Services: ![services](https://user-images.githubusercontent.com/916551/205171290-582f9f3a-4819-4eb0-b0ed-8aca410e3fa7.png)

Maybe this is intentional? But it looks pretty odd. Reporting it before I just adjust the test to expect it.

### Version of Cockpit

281

### Where is the problem in Cockpit?

Services

### Server operating system

Fedora

### Server operating system version

any

### What browsers are you using?

Firefox

**Comment by jelly** [comment]
This isn't intentional, this is a bug. If you want light mode it shouldn't be a mix.

**Comment by KKoukiou** [comment]
@jelly this is 100% reproducible if you switch from admin to limited or vice versa while on services page. I guess this is a nasty regression and feel will should karma down the release from friday. @martinpitt @marusak what do you think?

**Comment by marusak** [comment]
Agree with karma -1, doing so now

**Comment by KKoukiou** [comment]
> Random though - maybe it is related to preloading of pages? We preload services page and this one seems to be affected

Tt happens also to the storage page which is not preloaded, so my assumption is that its the pages which get reloaded when superuser privileged change.
