### ISSUE TITLE
dark mode: lists in modals have different backgrounds

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#17976]
Lists in modals, specifically used in the storage page, have a white background on white background in light mode. 

![image](https://user-images.githubusercontent.com/10246/205097095-8ecc62b4-eafc-4d09-ab00-a5ddbf52b7b7.png)

But in dark mode, the list background and the modal backgrounds both switch to different shades of grey.

![image](https://user-images.githubusercontent.com/10246/205096850-67210331-8788-4952-86b9-8694f17eec15.png)

The solution would be to either make the background transparent for the tables or align it to the same color.

This might actually come from PF. (I'm not sure if they intend on tables to be used like this in modals or not.)

**Comment by KKoukiou** [comment]
See https://github.com/patternfly/patternfly/issues/5278
