### ISSUE TITLE
Creating a partition loads indefinitely and fails to mount

### ISSUE THREAD

**Issue by optimanetworks** [cockpit-project/cockpit#17982]
### What has been tested
- Reproduced on multiple different machines with exactly the same results.
- Tried with both new and used hard disk drives.

### Reproducing the issue
1. Go to **Storage** and select either a new or used storage device.
2. Create a partition table.
3. Create a partition with EXT4 filesystem.
- Naming the partition or leaving the field empty doesn't appear to matter.
- It doesn't appear that the mountpoint existing already or not has an impact.
- Using custom mount options or not doesn't affect the issue either.

4. The page will now keep loading.
5. Reloading the page will show that the partition was created but that mounting has not happened.

### What it looks like
Indefinite loading screen when creating partition:
![image](https://user-images.githubusercontent.com/102368162/205269696-4dc46e93-abbd-41d2-8cf5-866043e14c2b.png)

Reloading the page shows that filesystem is not mounted:
![image](https://user-images.githubusercontent.com/102368162/205270386-832a0521-6d02-4dc6-a72a-2e4d0a75b127.png)

### Version of Cockpit

215

### Where is the problem in Cockpit?

Storage

### Server operating system

Ubuntu

### Server operating system version

20.04.4 LTS

### What browsers are you using?

Firefox, Chrome

### System log

```shell
Dec 02 11:01:45 ubuntu cockpit-tls[32966]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Dec 02 11:02:41 ubuntu cockpit-tls[32966]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Dec 02 11:02:50 ubuntu cockpit-tls[32966]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Dec 02 11:02:50 ubuntu cockpit-tls[32966]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Dec 02 11:03:02 ubuntu cockpit-tls[32966]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Dec 02 11:03:03 ubuntu cockpit-tls[32966]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Dec 02 11:03:04 ubuntu cockpit-tls[32966]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Dec 02 11:08:55 ubuntu cockpit-tls[32966]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Dec 02 11:08:56 ubuntu cockpit-tls[32966]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Dec 02 11:08:56 ubuntu cockpit-tls[32966]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
```

**Comment by KKoukiou** [comment]
This seems to be solved in 226, https://github.com/cockpit-project/cockpit/issues/14467

Try updating the cockpit-storage package using backports and please report if it got fixed.

**Comment by optimanetworks** [comment]
@KKoukiou - Thank you for your swift and helpful response!

Problem does seem to be alleviated by updating to 264 via backports, which is great and my issue is solved.

Just for the record (if anyone else runs into this issue) only updating the `cockpit-storaged` package results in the dashboard being blank. Updating the entire `cockpit` package worked perfectly though.
