### ISSUE TITLE
cockpit error - 389-ds module

### ISSUE THREAD

**Issue by baffledmystic** [cockpit-project/cockpit#17997]
Cockpit is unable to display replication agreement details for rhds directory server (389-ds)
# rpm -qa | grep cockpit-389
cockpit-389-ds-1.4.3.31-6.module+el8dsrv+16980+c4b9cd33.noarch

Console logs show error in syntax for dsconf command:
```
bootstrap:1 CMD: loadReplSuffix: Load the replication info ==> dsconf -j ldapi://%2fvar%2frun%2fdsinsance.socket replication get-changelog --suffix o=archive
cockpit/$7f50cb6409a<E2><80><A6>sole/index.html#/:1 
       Uncaught SyntaxError: Unexpected token 'u', "usage: dsc"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Function.<anonymous> (bootstrap:1:1)
    at cockpit.js:1:12867
    at cockpit.js:1:12978
    at L (cockpit.js:1:12383)
```

**Comment by jelly** [comment]
This plugin is not maintained by the Cockpit team, but it's part of the 389-ds repository, please fill an issue there https://github.com/389ds/389-ds-base/tree/main/src/cockpit/389-console

**Comment by baffledmystic** [comment]
Thanks for the response!
I'll open a new issue there.
