### ISSUE TITLE
Choose better SSL cipher and version settings

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1801]
We need to choose better SSL cipher and SSL cert settings. The ones we currently use have at least the following problems:

 - client side cipher ordering
 - server supports RC4 ciphers
 - server has SSLv3 enabled

**Comment by stefwalter** [comment]
@danwinship How do I tweak the above settings when using glib-networking and GTlsServerConnection?

**Comment by danwinship** [comment]
There's currently no way to do it other than setting the G_TLS_GNUTLS_PRIORITY environment variable to an appropriate gnutls "priority string". (With the accompanying warnings about not calling setenv after any threads have been started.) This is what epiphany is currently doing to disable SSLv3 to prevent POODLE.

https://git.gnome.org/browse/glib-networking/tree/tls/gnutls/gtlsconnection-gnutls.c?id=2.43.1#n200
https://bugzilla.gnome.org/show_bug.cgi?id=738633

I've been looking at adding APIs to query the negotiated version/ciphersuite; there could be APIs for setting available ones as well (although to stay compatible with http://fedoraproject.org/wiki/Changes/CryptoPolicy, FIPS, etc, we'd probably want to only allow *disabling* versions/suites).

**Comment by stefwalter** [comment]
> There's currently no way to do it other than setting the G_TLS_GNUTLS_PRIORITY environment variable to an appropriate gnutls "priority string". (With the accompanying warnings about not calling setenv after any threads have been started.) This is what epiphany is currently doing to disable SSLv3 to prevent POODLE.

I think that should work.

@tomato42 What is a good SSL command that I can check the above TLS settings with. I'd like to add a cross check of this to our test suite.

**Comment by tomato42** [comment]
@stefwalter depends on how thorough you want to be. If you want just to check if the SSLv3 is disabled then a simple `openssl s_client -connect localhost:4433 -ssl3` and then parsing the output, scanning for ssl alerts will be enough, similarly RC4 can be checked with `openssl s_client -connect localhost:4433 -cipher RC4`
If you want to do more checks or have easier time parsing the output then cipherscan ( https://github.com/jvehent/cipherscan ) has a JSON output with a lot of info

though if you are using the CryptoPolicy, then we probably should file bugs against it, as the issues I mentioned are generic, not specific to the use case - though the presence of RC4 doesn't look like you are (or is CryptoPolicy not enabled by default?)

**Comment by stefwalter** [comment]
@tomato42 #1835 should fix this issue. If you would like, please review. 

> though if you are using the CryptoPolicy, then we probably should file bugs against it, as the issues I mentioned are generic, not specific to the use case - though the presence of RC4 doesn't look like you are (or is CryptoPolicy not enabled by default?)

We are using glib-networking and gnutls. If standard policy is to be enforced, it should be done in those components.
