### ISSUE TITLE
Cockpit terminal stuck

### ISSUE THREAD

**Issue by 7054company** [cockpit-project/cockpit#18024]
### Explain what happens

It take time to load and stuck
No respose 

### Version of Cockpit

lastest

### Where is the problem in Cockpit?

Terminal

### Server operating system

CentOS

### Server operating system version

7

### What browsers are you using?

Chrome, Chrome on Android

**Comment by jelly** [comment]
Which version is latest, is that 281? Are there any errors in the developer console?
