### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by yarons** [cockpit-project/cockpit#18023]
https://github.com/cockpit-project/cockpit/blob/c49fc4b1d544c10375f9040fb63813d0784d61ea/pkg/systemd/logs.jsx#L413

It's either just me with my plain old silly keyboard that doesn't remember anything or it's rather clipboard which makes more sense in that context :)

**Comment by jelly** [comment]
This indeed seems like a bug!
```
pkg/storaged/crypto-keyslots.jsx:                                   clickTip={_("Successfully copied to clipboard!")}
pkg/systemd/logs.jsx:                         <ClipboardCopy clickTip={_("Successfully copied to keyboard")}
```
