### ISSUE TITLE
Allow zooming in/out metrics

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#18027]
Use case: I want to see a slow resource creep over multiple days.

The most logical approach is to change our current blocks into a day view and then allow a user to expand into hourly slots.

Some further thoughts we discussed:

Divide into 24 hour slots, count the spikes and visualise the biggest peaks (relative to the other spikes). We don't want to overload the user with spikes, but figure out the most interesting spikes.

Related to not overloading on spikes, we might want to add an option to filter "spike types" such as network/disk/cpu/memory. Maybe I am not interested in network spikes as my server servers as a package mirror.

As this issue is about slow resource creep, a common example would be memory leaks. So do we currently detect those well and do we show OOM related logs if the `oomd` is invoked?

For memory usage it would be nice to show the memory used per process, if we can get this information from PCP.

**Comment by garrett** [comment]
Additional details:

- try to summarize the hits with the number, type, and a relative icon (on the left) which shows the performance impact
- (probably label the hour segments somewhere, subtly)
- hours would be expandable for more details
- default to all types of resources, but allow someone to choose which to see (it could be any combo)
- in addition to OOM, we probably want to show other stressors like: hitting swap, when a CPU was being throttled, IO-related issues, etc.

This will require both design and implementation work. But a lot of this can be done in parallel or even with the implementation first, as we already talked about this and made some design-related decisions.

PF has resource usage icons which we can use for this:

![image](https://user-images.githubusercontent.com/10246/207921196-4096556d-bf59-4980-8d76-8ab0a2b256c5.png)

From https://www.patternfly.org/v4/guidelines/icons/#all-icons; search for "pf-icon-resources"
