### ISSUE TITLE
cockpit.file().replace() doesn't preserve owner/group/mode

### ISSUE THREAD

**Issue by champtar** [cockpit-project/cockpit#18033]
### Explain what happens

https://github.com/cockpit-project/cockpit/blob/27cb665b5c135481f900dafac0c1b754ab91b5a0/src/bridge/cockpitfsreplace.c#L270
replace create a new world readable file, this is a problem when using replace() to write any kind of sensitive data.
Developer can call chmod just after but this leave a small insecure window.
Developer could also miss the fact that replace just changed the permissions and leave everything open.
Idealy it would preserve:
- owner
- group
- mode
- selinux (bonus)

This already cases issues, see https://github.com/cockpit-project/cockpit/issues/11876 where cockpit changes owner on `~/.ssh/authorized_keys`. This component uses `file.modify()` which calls `file.replace()`. Or issue #19905 where editing motd makes it inaccessible.

**Comment by marusak** [comment]
@allisonkarlitskaya @martinpitt This is something which would be superb if we could fix in python bridge. And we can easily test it as well on the accounts page.

**Comment by martinpitt** [comment]
fsreplace1 creates a new temp file and renames it to the original file (both in Python and in C). If the file exists already, we could stat() it and then set owner/group/mode of the new file after writing and before renaming. This is a bit racy (TOCTOU), but I don't think it matters -- if someone manages to remove the file in between the stat() and creating the new one, this does not really change the result, as this would happen anyway as part of rename().

I'm happy to work on this, if @allisonkarlitskaya is fine with that approach.

**Comment by allisonkarlitskaya** [comment]
And ACL?  And SELinux label?  and other xattrs?  and what if it's a symlink?

:(  can't say I'm a huge fan of this.  It's sort of a difference in approach between our "make a new file and move it into place" and the `O_TRUNC` paradigm.

**Comment by martinpitt** [comment]
Right, it mostly comes down to "more or less wrong", it can't be "perfect".

**Comment by martinpitt** [comment]
We can reconsider this when we dropped the C bridge on most OSes, and use https://docs.python.org/3/library/shutil.html#shutil.copystat instead of a home-brewn solution

**Comment by martinpitt** [comment]
I tried `os.copystat()` in #20002, but it's not sufficient. It doesn't copy owner and group.

**Comment by martinpitt** [comment]
Copying and updating this comment from https://github.com/cockpit-project/cockpit/pull/18585#issuecomment-1494591662 as that's an abandoned/closed PR and thus hard to find.

I did an audit, to check where we actually use this API, and which other places could be affected (or broken): 

We use `cockpit.file().replace()` in these places: 
 1. in serverTime.js for writing timesyncd/chrony drop-ins (largely unaffected as cockpit itself creates the files, and tight permissions are not a problem)
 2. updating motd (broken, see #19905)
 3. writing /run/systemd/shutdown/scheduled (tight  permissions are not a problem)
 4. editing timers (medium, systemd doesn't care about permissions but users can't read the files)
 5. cockpit-ostree: writing a config for adding a remote (created by cockpit itself, should be fine)

We use `cockpit.file().modify()` in these places:
 1. update kdump config (read by root, tight permissions are not a problem)
 2. delete key from `authorized_keys` (hacked around with `sed -i` in a3694802b7b2)

c-{podman,machines,certificates,composer,sub-man} don't use these APIs at all.
