### ISSUE TITLE
Double tooltip for docker storage warning and typo.

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#1804]
![double-tip](https://cloud.githubusercontent.com/assets/3228183/6144484/f09e4c6a-b1e0-11e4-9929-d89c1f4ea872.png)

Also, "allocated".

**Comment by stefwalter** [comment]
Which browser is this happening in?

**Comment by mvollmer** [comment]
> Which browser is this happening in?

Sorry, Firefox 35.0.1.
