### ISSUE TITLE
Cockpit 282 with Firefox intermittent issue with sorting "Groups" by "# of users"

### ISSUE THREAD

**Issue by briansmith0** [cockpit-project/cockpit#18054]
### Explain what happens

1. Upgrade to Cockpit 282 (cockpit-282-1.fc36.x86_64) on Fedora 36
2. Using Firefox, go to the "Accounts" page
3. Expand the drop down for "Groups"
4. Click on "# of users" to sort in descending order
5. Intermittently, the table of users will start rapidly changing at this point (appears that the order of the users shown is rapidly changing) 
6. If issue doesn't occur, reload the page, and try again.  Seems to be about ~20% of the time this issue occurs

Not sure if this is related to: https://github.com/cockpit-project/cockpit/issues/18053

Using Firefox 108.0 on Fedora

### Version of Cockpit

cockpit-282-1.fc36.x86_64

### Where is the problem in Cockpit?

Accounts

### Server operating system

Fedora

### Server operating system version

36 (also occurs on 37)

### What browsers are you using?

Firefox

**Comment by jelly** [comment]
@KKoukiou @tomasmatus as you both worked on the groups feature, do you have an idea what might be causing this?
