### ISSUE TITLE
Crypto for NIST 800-171

### ISSUE THREAD

**Issue by Cyril-Roy** [cockpit-project/cockpit#18062]
### Explain what happens

According to the OSCAP NIST 800-171 security profile, FIPS mode must be enabled and crypto policy configured as FIPS:OSPP
That is to say:
- sudo fips-mode-setup --enable: http://static.open-scap.org/ssg-guides/ssg-rhel8-guide-cui.html#xccdf_org.ssgproject.content_rule_enable_dracut_fips_module
- sudo update-crypto-policies --set FIPS:OSPP http://static.open-scap.org/ssg-guides/ssg-rhel8-guide-cui.html#xccdf_org.ssgproject.content_rule_configure_crypto_policy

However, when it is configured like this, Cockpit shows "Fips:ospp" inconsistent.
The view is therefore not correct.

### Version of Cockpit

276.1

### Where is the problem in Cockpit?

Overview

### Server operating system

Red Hat Enterprise Linux

### Server operating system version

RHEL 8.7

### What browsers are you using?

Chrome

**Comment by jelly** [comment]
We have some code to detect if a user applied a FIPS inconsistently FIPS policy applied but the user didn't yet reboot. This should show `FIPS is not properly enabled` but as the code does not know about `FIPS:OSPP` this is not shown.

**Comment by Cyril-Roy** [comment]
When the remidation is applied through Cockpit, it disable FIPS mode and keeps FIPS:OSPP crypto policy.
according to the NIST 800-171, it must be:
- FIPS enabled
- FIPS:OSPP crypto policy

Is it possible to adapt the code to take FIPS:OSPP crypto policy into account as it is part of the NIST 800-171 security guide described by OSCAP?
Ref: http://static.open-scap.org/ssg-guides/ssg-rhel8-guide-cui.html#xccdf_org.ssgproject.content_rule_configure_crypto_policy
