### ISSUE TITLE
Network Visualization

### ISSUE THREAD

**Issue by whitel** [cockpit-project/cockpit#1807]
As a user, I would like to be able to visualize the various networks on the machine being managed. Keeping track of the networks (multiple vlans for VMs and containers), their interconnections, and their exposure outside the host can be quite confusing.

**Comment by stefwalter** [comment]
Related: https://trello.com/c/eauhQW54/138-use-plotnetcfg-to-draw-a-network-plot

**Comment by larskarlitski** [comment]
This issue is quite old and not very detailed. We didn't yet and probably won't have plans to add something like this in the medium term.
