### ISSUE TITLE
Port settings in config where removed after system upgrade

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [cockpit-project/cockpit#18079]
### Explain what happens

1.  I updated my system with sudo do-release-upgrade
2.  Cockpit changed ports from 7777 to 9090 and my reverse proxy broke, no biggie just changed the config file
3.  Reuse credentials checkbox is gone from login page and I have to enable administrative access on each login

![image](https://user-images.githubusercontent.com/51783206/209336430-82a6c0ca-46d4-4765-b658-60046b6680dd.png)

### Version of Cockpit

264-1ubuntu0.22.04.1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Ubuntu

### Server operating system version

22.04.1 lts

### What browsers are you using?

Firefox

**Comment by KKoukiou** [comment]
Hi @HEPOSHEIKKI thanks for reporting this. In fact the 'Reuse password..' checkbox was intentionally removed. Read more about it here; https://cockpit-project.org/blog/cockpit-228.html -> 'Changes to remote host logins' section

The fact that your port was overwritten can be indeed a packaging bug, so I will leave this issue here open to take a look into this one.

**Comment by KKoukiou** [comment]
Oh got the other issue as well. It was some change on how we produce the config file on release 260.

``` git
commit 1ca495779d746bd2df772453a9fd367669b3b55c
Author: Allison Karlitskaya <allison.karlitskaya@redhat.com>
Date:   Mon Jan 10 10:56:47 2022 +0100

    src/systemd: new directory
    
    Our increasingly large web of systemd integration mostly lives in
    src/ws/, for mostly historical reasons.  These days, cockpit-tls has
    at least as much integration with systemd as does cockpit-ws, and
    cockpit-session is about to gain some.
    
    Move everything to a new src/systemd/ directory.
```
