### ISSUE TITLE
Can't change or reset Samba AD DC user password

### ISSUE THREAD

**Issue by bwrgitprotect** [cockpit-project/cockpit#18084]
### Explain what happens

When I create or choose to change or reset the password of one of my Samba 4 AD DC, it just returns me the message: An Error Occurred

Running Samba 4.13.17 on Ubuntu 20.04 server on AWS EC2 Instance.

How do I fix it?

Thanks

### Version of Cockpit

264

### Where is the problem in Cockpit?

Accounts

### Server operating system

Ubuntu

### Server operating system version

20.04

### What browsers are you using?

Chrome, Edge, Safari macOS

**Comment by KKoukiou** [comment]
@bwrgitprotect which plugin are you reporting this for? Maybe Samba plugin? In that case please close this as this plugin is not maintained by cockpit core team within this repo. I suspect it's https://github.com/45Drives/cockpit-file-sharing

**Comment by bwrgitprotect** [comment]
> https://github.com/45Drives/cockpit-file-sharing

I refer to the Cockpit Samba AD DC plugin that installed by default when installing using the tutorial here: https://wiki.samba.org/index.php/GSOC_cockpit_samba_ad_dc

**Comment by garrett** [comment]
Apologies, but we also do not make that plugin either.

The Samba AD DC plugin is located @ https://gitlab.com/HezekiahM/samba-ad-dc

Issues for the Samba AD DC plugin are located at https://gitlab.com/HezekiahM/samba-ad-dc/-/issues

Please file an issue on their issue tracker. I hope they can fix your issue soon!
