### ISSUE TITLE
CUPS web-service integration (OpenPrinting CUPS)

### ISSUE THREAD

**Issue by erdincay** [cockpit-project/cockpit#18092]
**Page: Applications**

We have a huge printing facility which has one central Linux server, and we would like to see Cockpit providing the CUPS web-user interface integrated in Cockpit.

Links:
- https://openprinting.github.io/cups/
- reachable through: http://localhost:631/

**Comment by marusak** [comment]
This is not something that the Cockpit team would work on any time soon. We are however supporting [starter kit](https://github.com/cockpit-project/starter-kit) with which it is very simple for any developer to create their own plugin. We are also happy to help and give some guidance when it comes to plugin development but we don't have resources to implement this plugin.

If you would go though and do the implementation let us know so we can put it on our page with list of all other cool apps people have created: https://cockpit-project.org/applications.html
