### ISSUE TITLE
No CPU temp shown in metrics  (new motherboard/CPU)

### ISSUE THREAD

**Issue by g6avk** [cockpit-project/cockpit#18098]
### Explain what happens

1.  This may not be a  bug.. 
2. A recent rebuild of my PC, Asus board/Ryzen 5600 CPU. To get the sensors to work I had to build the module from another project https://github.com/frankcrawford/it87 The relevant one seen in sensors is it8655-isa-0290 but the CPU temp is not seen in Cockpit.

3. The info below was requested in a previous report (that was fixed, thank you) so maybe of use :

4. grep -r . /sys/class/hwmon/hwmon*/name
/sys/class/hwmon/hwmon0/name:it8655
/sys/class/hwmon/hwmon1/name:amdgpu
/sys/class/hwmon/hwmon2/name:hidpp_battery_0
/sys/class/hwmon/hwmon3/name:k10temp
/sys/class/hwmon/hwmon4/name:hidpp_battery_1

5. grep -r . /sys/class/hwmon/hwmon*/temp*
/sys/class/hwmon/hwmon0/temp1_alarm:0
/sys/class/hwmon/hwmon0/temp1_beep:0
/sys/class/hwmon/hwmon0/temp1_input:24000
/sys/class/hwmon/hwmon0/temp1_max:92000
/sys/class/hwmon/hwmon0/temp1_min:63000
/sys/class/hwmon/hwmon0/temp1_offset:0
/sys/class/hwmon/hwmon0/temp2_alarm:1
/sys/class/hwmon/hwmon0/temp2_beep:0
/sys/class/hwmon/hwmon0/temp2_input:27000
/sys/class/hwmon/hwmon0/temp2_max:-101000
/sys/class/hwmon/hwmon0/temp2_min:96000
/sys/class/hwmon/hwmon0/temp2_offset:0
/sys/class/hwmon/hwmon0/temp2_type:4
/sys/class/hwmon/hwmon0/temp3_alarm:0
/sys/class/hwmon/hwmon0/temp3_beep:0
/sys/class/hwmon/hwmon0/temp3_input:22000
/sys/class/hwmon/hwmon0/temp3_max:111000
/sys/class/hwmon/hwmon0/temp3_min:-80000
/sys/class/hwmon/hwmon0/temp3_offset:0
/sys/class/hwmon/hwmon0/temp3_type:4

Above snipped this as it is rather long..

6. sensors
it8655-isa-0290
Adapter: ISA adapter
in0:         698.00 mV (min =  +1.08 V, max =  +1.83 V)  ALARM
in1:           2.50 V  (min =  +2.55 V, max =  +1.29 V)  ALARM
in2:           2.03 V  (min =  +2.62 V, max =  +2.39 V)  ALARM
in3:           2.00 V  (min =  +0.57 V, max =  +0.58 V)  ALARM
in4:           1.98 V  (min =  +1.07 V, max =  +1.12 V)  ALARM
in5:           1.95 V  (min =  +1.82 V, max =  +2.15 V)
in6:           1.98 V  (min =  +1.19 V, max =  +0.53 V)  ALARM
3VSB:          3.31 V  (min =  +1.50 V, max =  +3.07 V)  ALARM
Vbat:          3.16 V  
+3.3V:         3.33 V  
fan1:        1308 RPM  (min =   11 RPM)
fan2:         415 RPM  (min =   16 RPM)
fan3:         234 RPM  (min =   18 RPM)
temp1:        +23.0°C  (low  = +63.0°C, high = +92.0°C)
temp2:        +27.0°C  (low  = +96.0°C, high = -101.0°C)  ALARM  sensor = thermistor
temp3:        +22.0°C  (low  = -80.0°C, high = +111.0°C)  sensor = thermistor
temp4:        +22.0°C  (low  = -62.0°C, high = -106.0°C)  ALARM  sensor = thermistor
temp5:        +22.0°C  (low  = +42.0°C, high = +83.0°C)  sensor = thermistor
temp6:        +22.0°C  (low  = -101.0°C, high = -99.0°C)  ALARM  sensor = thermistor
intrusion0:  ALARM

k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +23.8°C  

amdgpu-pci-0800
Adapter: PCI adapter
vddgfx:      724.00 mV 
vddnb:         1.10 V  
edge:         +22.0°C  

### Version of Cockpit

282

### Where is the problem in Cockpit?

Metrics

### Server operating system

Fedora

### What browsers are you using?

Brave

**Comment by KKoukiou** [comment]
@tomasmatus since you implemented this feature, can you please take a look?

**Comment by tomasmatus** [comment]
Thank you for the report. Yes, I'll look into this.

**Comment by jelly** [comment]
Cockpit should check `k10temp` and checks for you `/sys/class/hwmon/hwmon3/name:k10temp`

hwmon devices might change after a reboot ( I don't think the order is guarranteed), so it would be nice if you could provide:

`/sys/class/hwmon/hwmon3/temp*_input` and `/sys/class/hwmon/hwmon3/temp*_label`. (If hwmon3 is k10temp)

**Comment by g6avk** [comment]
Sure:

grep -r . /sys/class/hwmon/hwmon3/temp*_input
25500
grep -r . /sys/class/hwmon/hwmon3/temp*_label
Tctl

**Comment by jelly** [comment]
> Sure:
> 
> grep -r . /sys/class/hwmon/hwmon3/temp*_input 25500 grep -r . /sys/class/hwmon/hwmon3/temp*_label Tctl

Reading our code, we ignore `Tctl` label with this PR https://github.com/cockpit-project/cockpit/pull/17601/files#diff-cdfd1fecd247e75674897918942454a99669afd2512c0f61547b979959456946R183

Not sure what the exact reasoning is, I can check my AMD desktop later today and see if I have a similar issue.

**Comment by jelly** [comment]
Can reproduce this with my desktop's ` AMD Ryzen 7 5700X 8-Core Processor`.

**Comment by jelly** [comment]
Ok the bug is quite obvious, if a path does not exists we skip it, as `temp2_input` does not exists we skip it, so we never reach `temp3_label`.

**Comment by g6avk** [comment]
I'm curious if this fix make it into 284, because after updating  the CPU temp is not showing in metrics.

**Comment by jelly** [comment]
Which distro are you on? 284 should fix the issue, I did locally have some weird caching issues but after a while it started working.

**Comment by g6avk** [comment]
I'm on Fedora 37

**Comment by CreatingNull** [comment]
Seems as though the #18127 PR doesn't work for all AM4 CPUs.

The problem seems to be the assumption that `tccd1` or `tdie` sensors are reported for all AMD devices on this platform. On some devices (such as my 5600g at least in current kernels) only the `tctl` is reported, I think because these lower end devices don't use an internal offset S.T tdie=tctl anyway.

This means the `predicate = (lambda label: label != 'Tctl')` just filters out all the valid temperature readings on all devices falling into this category, causing the CPU temperature feature to not work. Perhaps the logic should be to fallback on the `tctl` if no other sensors are reported? For Ryzen, `tctl` is probably a more accurate reading to expose for most supervisory purposes anyway (As it's a better representation of the temperature at the IHS).

**Comment by aenertia** [comment]
Confirming lack of temps with the f40 packages on steamdeck,
