### ISSUE TITLE
Session Timeout Support

### ISSUE THREAD

**Issue by MingcongBai** [cockpit-project/cockpit#18097]
Cockpit should consider implementing a session timeout support for its Web interface. Leaving the webpage open equates access to key system administrative functions and, without a session timeout, it seems unsafe to allow leaving a session open indefinitely.

**Comment by KKoukiou** [comment]
Since release 209 Cockpit will automatically log you out of your current session after 15 minutes of inactivity.

See the release notes from the version https://cockpit-project.org/blog/cockpit-209.html

**Comment by MingcongBai** [comment]
Well, if this is the case, it's probably not working properly? I left the "Overview" page on my browser and left my computer there for the afternoon, Cockpit did not logout.

I see that in the release note, there is a switch to toggle this behaviour - is this enabled by default?

**Comment by marusak** [comment]
Can you please show you cockpit.conf file? Have you also restarted cockpit.socket and logged back in?

> I see that in the release note, there is a switch to toggle this behaviour - is this enabled by default?

Not sure which picture you mean - there is no switch. You need to edit the config file for it to work

**Comment by Cyanoxygen** [comment]
Hi all,
Cockpit's config file is not generated during the build, so as we are introducing Cockpit to our distro, there's no config file being pre-shipped. According to manual `cockpit.conf(5)`, this config file is optional and no session timeout is the default behavior.

So to enable session timeout, distro maintainers should create `/etc/cockpit/cockpit.conf` manually, and add corresponding config keys to it.

**Comment by marusak** [comment]
> So to enable session timeout, distro maintainers should create /etc/cockpit/cockpit.conf manually, and add corresponding config keys to it.

Correct

**Comment by Cyanoxygen** [comment]
After creating cockpit.conf and specifying the session timeout, this functionality now works. Thanks for pointing it out.
