### ISSUE TITLE
Unable to Save Files with Nano in Terminal

### ISSUE THREAD

**Issue by MingcongBai** [cockpit-project/cockpit#18095]
### Explain what happens

1. Open Cockpit web console.
2. Attempt to edit a file with Nano and saving using one of the two combination keys (Ctrl-S, save in place; Ctrl-O, save as).
3. Web browser opens "save webpage" or "open file" dialog, user unable to save files with Nano.

### Version of Cockpit

282

### Where is the problem in Cockpit?

Terminal

### Server operating system

other

### Server operating system version

AOSC OS 10.0.0

### What browsers are you using?

Firefox

**Comment by KKoukiou** [comment]
Thanks for reporting. This has been already reported, https://github.com/cockpit-project/cockpit/issues/14545
