### ISSUE TITLE
Cockpit crashing when adding WebService Origin domain to cockpit.conf

### ISSUE THREAD

**Issue by C4rmine** [cockpit-project/cockpit#18100]
### Explain what happens

1. Create a cockpit.conf in /etc/cockpit/
2. Put this: 

[WebService]
Origins = http://192.168.1.11:8989
ProtocolHeader = X-Forwarded-Proto
AllowUnencrypted = true

3. Restar cockpit service
4. Login to the portal

![image](https://user-images.githubusercontent.com/114113033/210051180-52d4ea7f-6ce2-4c6d-a13a-76bd68b3d2a7.png)

How can i do cockpit accept any origin?

### Version of Cockpit

215

### Where is the problem in Cockpit?

None

### Server operating system

Ubuntu

### What browsers are you using?

Chrome

**Comment by KKoukiou** [comment]
Can you please send also the journalctl output, as suggested in the failure page?
