### ISSUE TITLE
Can't login with zsh as login shell

### ISSUE THREAD

**Issue by rys** [cockpit-project/cockpit#18129]
### Explain what happens

Trying to login to cockpit with a user that has `zsh` set as their login shell causes cockpit login to fail and return "Wrong user name or password" as the error.

I think the core issue is a duplicate of #14060: zsh, at least on my system, doesn't support redirecting the `cockpit-bridge` output into that numbered fd. If I change the login shell to bash then cockpit logins succeed.

The error message returned is quite unhelpful and sent me off on a number of wild goose chases. Is there a chance any fix could also surface something more useful? Sadly the cockpit logs were not helpful in diagnosing the issue, at least on my Arch system.

### Version of Cockpit

282.1-1

### Where is the problem in Cockpit?

Accounts

### Server operating system

Arch Linux

### Server operating system version

rolling

### What browsers are you using?

Firefox

**Comment by jelly** [comment]
That sounds strange, my default shell is zsh and I can login fine:

```
[jelle@t14s][~/projects/cockpit/timers-create-validation]%grep jelle /etc/passwd
jelle:x:1000:1000::/home/jelle:/bin/zsh
```

Do you have some logs which might be interesting or error message?

**Comment by jelly** [comment]
No response.
