### ISSUE TITLE
Regular user has full access through web console

### ISSUE THREAD

**Issue by Sekenenz** [cockpit-project/cockpit#18128]
While testing I've noticed that any regular user (even without any permissions) can login to web console and navigate (Navigator) through the whole system with full permissions.

How do I block it?

--- 
cockpit 282-1~bpo11+1
Debian 11
Chrome 108.0.5359.71

**Comment by KKoukiou** [comment]
@Sekenenz do you maybe indend to report this against [this plugin](https://github.com/45Drives/cockpit-navigator)?

This is not maintained by the core cockpit team.

**Comment by Sekenenz** [comment]
I will, thanks.

**Comment by jelly** [comment]
Closing as this is about the `navigator` plugin.
