### ISSUE TITLE
ISCSI Initiator and Target GUI Sections Not Present in Arch Linux

### ISSUE THREAD

**Issue by Ai-Elias** [cockpit-project/cockpit#18139]
### Explain what happens

The ISCSI Initiaor and Target sections of the storage tab (cockpit-storaged) appear to be missing on Arch Linux. Unless, I'm missing packages, (if so apologies couldn't find anything I appeared to be missing in my day of research) are there any plans to implement these sections for Arch in the future?

![image](https://user-images.githubusercontent.com/87244515/211184818-972051da-931e-45bb-9dd3-ddabe925f25e.png)

### Version of Cockpit

282.1-1

### Where is the problem in Cockpit?

Storage

### Server operating system

Arch Linux

### Server operating system version

Latest

### What browsers are you using?

Firefox

**Comment by KKoukiou** [comment]
Hi @Ai-Elias unfortunately this is expected what you see. Udisks does not have support for ISCSI in arch.

https://github.com/storaged-project/udisks/issues/388
https://bugs.archlinux.org/task/55260

There is nothing we can do from cockpit side, so closing this issue here.
