### ISSUE TITLE
Rhost in pam log report localhost address

### ISSUE THREAD

**Issue by Ludo-code** [cockpit-project/cockpit#18167]
### Explain what happens

When trying to configure fail2ban with help on issue #722 i have seen in my pam file, localhost ip address for cockpit login...

here is the proof 

```log
Jan 13 07:05:10 vps-e95807bf cockpit-session: pam_unix(cockpit:auth): check pass; user unknown
Jan 13 07:05:10 vps-e95807bf cockpit-session: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=::ffff:127.0.0.1
```

So it is a bug or a normal thing ?

### Version of Cockpit

282-1~bpo22.04.1

### Where is the problem in Cockpit?

Logs

### Server operating system

Ubuntu

### Server operating system version

VERSION="22.04.1 LTS (Jammy Jellyfish)"

### What browsers are you using?

Firefox, Firefox Mobile on Android, Chrome, Chrome on Android, Edge, Safari on iPhone, GNOME Web, Other

**Comment by jelly** [comment]
Do you reverse proxy Cockpit?

**Comment by Ludo-code** [comment]
Yes with apache2

**Comment by jelly** [comment]
Then my hunch is that you have to set `ForwardedForHeader = X-Forwarded-For` in `cockpit.conf` and make Apache2 use it with `RemoteIPHeader X-Forwarded-For` (I think). I don't use Apache2 that often.

**Comment by Ludo-code** [comment]
It's working thanks you
