### ISSUE TITLE
There were "xxxx" failed login attempts since the last successful login.

### ISSUE THREAD

**Issue by xfisbest** [cockpit-project/cockpit#18176]
### Explain what happens

I installed cockpit on custom port last night and in morning when i log in back i saw "There were 1515 failed login attempts since the last successful login." 
"Last failed login: Jan 16, 2023 11:10:41 AM from 114.34.103.156 on ssh:notty"

### Version of Cockpit

cockpit/stable,now 239-1 all [installed]

### Where is the problem in Cockpit?

Overview

### Server operating system

Debian

### Server operating system version

11.6

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
... so can you please check recent `journalctl` to see where these come from? If that's a publicly accessible server, that's not at all uncommon (new IPs are getting script kiddie attack after *seconds* these days). Most often these are from SSH.

**Comment by xfisbest** [comment]
> ... so can you please check recent `journalctl` to see where these come from? If that's a publicly accessible server, that's not at all uncommon (new IPs are getting script kiddie attack after _seconds_ these days). Most often these are from SSH.

they are almost all like:
```
 Jan 16 01:40:13 xf sshd[6216]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=61.216.105.99
Jan 16 01:40:15 xf sshd[6216]: Failed password for invalid user admin from 61.216.105.99 port 56020 ssh2
```

**Comment by martinpitt** [comment]
Yes, I suggest to set up fail2ban to fend off these script kiddie attacks. I use that on my server, and it works really well. See e.g. issue #722 , other users produced fail2ban configs for cockpit as well. But the better solution is to not expose cockpit on a public server in the first place, but instead use [Cockpit Client](https://flathub.org/apps/details/org.cockpit_project.CockpitClient) or a bastion host (i.e. connect from a local cockpit via SSH).
