### ISSUE TITLE
Changing server certificates for 389 Directory Server throws an Unexpected Error in web gui

### ISSUE THREAD

**Issue by rheaalleen** [cockpit-project/cockpit#18178]
### Explain what happens

1. Installing 389-ds-base per CLI on Fedora 37
2. Using Cockpit add a server/CA certificate in the 389 Directory Server Application
3. Trying to enable TLS/SSL Cockpit refuses to select the item from drop-down menu and throws an error. The Server-Cert is preinstalled and works, selecting your own certificate from the drop down throws the error every time, making it impossible to use your own certificate through the web gui

![image](https://user-images.githubusercontent.com/52893816/212675807-e8cc87c0-b4a6-4975-b22c-cfa87f17fe13.png)

![image](https://user-images.githubusercontent.com/52893816/212675865-7c6b20ac-5709-48be-8282-c36da92839be.png)

![image](https://user-images.githubusercontent.com/52893816/212675936-68a7f825-9c62-43be-87ee-2551c2cb7f84.png)

![image](https://user-images.githubusercontent.com/52893816/212676020-5b3d60c9-d887-46e3-b0f8-144344ba3e9f.png)

Wasn´t sure if this is a Cockpit or 389-ds problem, so please inform me if this issue should be moved to the 389-ds repo

**Comment by martinpitt** [comment]
Please re-report this to https://github.com/389ds/389-ds-base/issues, that code lives there. Thank you!
