### ISSUE TITLE
setroubleshootd.service fails to start if `cockpit-selinux` is installed on Fedora CoreOS

### ISSUE THREAD

**Issue by marvinruder** [cockpit-project/cockpit#18170]
### Explain what happens

1. Install cockpit and some more of its applications using `sudo rpm-ostree install cockpit-system cockpit-ostree cockpit-pcp cockpit-storaged cockpit-networkmanager cockpit-kdump` on Fedora CoreOS and reboot.
2. Everything is fine.
3. Install cockpit-selinux using `sudo rpm-ostree install cockpit-selinux` and reboot.
4. Observe that `setroubleshootd.service` fails with the log output provided below. 

On a machine with a very similar configuration, this issue does not occur. One difference I noticed between both machines is that the working one has the package `python3-six-1.16.0-8.fc37.noarch` installed (by coindidence, as dependency of the unrelated `borgmatic`). 

Perhaps some required dependencies are not declared in the `cockpit-selinux` RPM?

### Version of Cockpit

282

### Where is the problem in Cockpit?

SELinux

### Server operating system

Fedora

### Server operating system version

Fedora CoreOS 37.20221225.3.0

### System log

```shell
× setroubleshootd.service - SETroubleshoot daemon for processing new SELinux denial logs
     Loaded: loaded (/usr/lib/systemd/system/setroubleshootd.service; static)
     Active: failed (Result: exit-code) since Fri 2023-01-13 08:11:17 UTC; 21s ago
    Process: 1968 ExecStart=/usr/sbin/setroubleshootd -f (code=exited, status=1/FAILURE)
   Main PID: 1968 (code=exited, status=1/FAILURE)
        CPU: 117ms

Jan 13 08:11:16 [hostname] systemd[1]: Starting setroubleshootd.service - SETroubleshoot daemon for processing new SELinux denial logs...
Jan 13 08:11:17 [hostname] setroubleshootd[1968]: Traceback (most recent call last):
Jan 13 08:11:17 [hostname] setroubleshootd[1968]:   File "/usr/sbin/setroubleshootd", line 31, in <module>
Jan 13 08:11:17 [hostname] setroubleshootd[1968]:     from setroubleshoot.util import log_debug
Jan 13 08:11:17 [hostname] setroubleshootd[1968]:   File "/usr/lib/python3.11/site-packages/setroubleshoot/util.py", line 2, in <module>
Jan 13 08:11:17 [hostname] setroubleshootd[1968]:     from six.moves import range
Jan 13 08:11:17 [hostname] setroubleshootd[1968]: ModuleNotFoundError: No module named 'six'
Jan 13 08:11:17 [hostname] systemd[1]: setroubleshootd.service: Main process exited, code=exited, status=1/FAILURE
Jan 13 08:11:17 [hostname] systemd[1]: setroubleshootd.service: Failed with result 'exit-code'.
Jan 13 08:11:17 [hostname] systemd[1]: Failed to start setroubleshootd.service - SETroubleshoot daemon for processing new SELinux denial logs.
```

**Comment by marvinruder** [comment]
Since the issue is also present when installing `setroubleshoot` directly, I reported it [here](https://gitlab.com/setroubleshoot/setroubleshoot/-/issues/5) as well. But since that repository does not look too active, I will leave this issue open.

**Comment by martinpitt** [comment]
Thanks! This is a crash/bug in setroubleshoot itself, and there's already a fix for it.
