### ISSUE TITLE
Javascript cockpit.transport.host property for default host name

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1817]
We should be able to tell which host cockpit.js is going to talk to by default.

This is useful for features like the firewall, which want to show a warning if an action will disconnect you from Cockpit. To implement this the code needs to know whether the browser is connected directly to cockpit-ws, or via SSH.

**Comment by jscotka** [comment]
Hi,
it is connected with issue:
https://github.com/cockpit-project/cockpit/issues/1529
It would be nice also to add localhost back and be able to use localhost as normal remote machine (without localhost hack)
usecase is that it would help for testing (test localhost hack, and also normal remote behaviour on localhost)
