### ISSUE TITLE
SELinux recommendation "fully relabel" automatic solution wrongly escaped

### ISSUE THREAD

**Issue by merlinscholz** [cockpit-project/cockpit#18174]
### Explain what happens

1. Have SELinux issues which prompt for the file system to be relabled
2. Click "Apply this solution" next to cockpit-selinux suggestion:
![image](https://user-images.githubusercontent.com/21988035/212446741-a24b5e6d-8c19-4e16-acb6-e5affe0e1de9.png)
3. Check / directory: A file named `.autorelabel;` appears, and the machine is *not* being rebooted
![image](https://user-images.githubusercontent.com/21988035/212446782-307ca6dc-4dd8-4fbc-8847-5351ab0b46f2.png)

### Version of Cockpit

276.1

### Where is the problem in Cockpit?

SELinux

### Server operating system

Red Hat Enterprise Linux

### Server operating system version

AlmaLinux 9.1

### What browsers are you using?

Firefox, Chrome, Brave, Other

**Comment by KKoukiou** [comment]
Verified, it's because of how cockpit.script works.

**Comment by martinpitt** [comment]
I can reproduce this easily:
```
cp /bin/ls /root/
chcon -t unlabeled_t /root/ls
runcon -u system_u -r system_r -t httpd_t -- /root/ls ~admin
```

But cockpit *doesn't* run the solution through `cockpit.spawn()`, it uses the `org.fedoraproject.SetroubleshootFixit.run_fix()` D-Bus API. It's even worse: Trying to apply it claims "applied successfully", but:
```
audit[2603]: AVC avc:  denied  { dac_override } for  pid=2603 comm="touch" capability=1  scontext=system_u:system_r:setroubleshoot_fixit_t:s0 tcontext=system_u:system_r:setroubleshoot_fixit_t:s0 tclass=capability permissive=0
SetroubleshootFixit.py[2603]: touch: cannot touch '/.autorelabel;': Permission denied
audit[2603]: AVC avc:  denied  { dac_override } for  pid=2603 comm="touch" capability=1  scontext=system_u:system_r:setroubleshoot_fixit_t:s0 tcontext=system_u:system_r:setroubleshoot_fixit_t:s0 tclass=capability permissive=0
SetroubleshootFixit.py[2603]: touch: cannot touch 'reboot': Permission denied
```

So it's running the wrong commands *and* with the wrong permissions. :exploding_head: I'll create a standalone reproducer and file a bugzilla.

**Comment by martinpitt** [comment]
Reported here: https://bugzilla.redhat.com/show_bug.cgi?id=2251907

This is a bug in SETroubleshoot, not cockpit.
