### ISSUE TITLE
Create an option for tmux to not clear screen on login

### ISSUE THREAD

**Issue by davidpaige** [cockpit-project/cockpit#18196]
Page: 
To reproduce:
1. Log into a host with tmux starting automatically in /etc/profile (e.g., by DISA STIG)
2. The system displays messages like "Your password expires in 7 days"
3. Tmux clears the screen, wiping the messages before they can be read
4. User (me) gets bitten, because the password expires

It's not a bug necessarily, because there is nothing "wrong."  

Request an enhancement that allows the user to see the system messages.  
Not to constrain the developers, but perhaps one of:

1. Not clearing the screen by default
2. Not clearing the screen by command switch
3. Not clearing the screen by config file parameter
4. Capturing and reprinting the system messages

**Comment by martinpitt** [comment]
Please file this against [tmux](https://github.com/tmux/tmux). Thanks!
