### ISSUE TITLE
Can I override the https redirect to force using the FQDN?

### ISSUE THREAD

**Issue by BinaryCortex** [cockpit-project/cockpit#18197]
If I navigate to http://servername:9090 cockpit currently redirects to https://servername:9090. Is there a way to force it to redirect to https://servername.domain.com:9090?

**Comment by martinpitt** [comment]
[No, there is not. For such operations you need to use a real webserver such as Apache or nginx, and reverse-proxy cockpit: https://cockpit-project.org/faq.html#how-do-i-use-cockpit-with-a-reverse-proxy
