### ISSUE TITLE
Storage: graphs lost colours

### ISSUE THREAD

**Issue by ne20002** [cockpit-project/cockpit#18200]
### Explain what happens

1. In the storage view the graphs lost the colours and alos the tooltips

![grafik](https://user-images.githubusercontent.com/39007279/213155547-b36e2e16-41ef-4f1f-98f7-6a702b151149.png)

This is graphics of five disks. No colours anymore.

### Version of Cockpit

282

### Where is the problem in Cockpit?

Storage

### Server operating system

Debian

### Server operating system version

Debian 11 (Bullseye)

### What browsers are you using?

Firefox

**Comment by garrett** [comment]
Do you have more than one filesystem that's being written to?

Here's a screenshot where I have 2 filesystems in Cockpit and one is being written to more than the other. It happens to be green (the other one is blue and doesn't have much IO). After hovering the mouse over the filesystem in the graph, it shows a tooltip.

![image](https://user-images.githubusercontent.com/10246/213178387-926f0184-db0b-4f15-942e-26579e0a5aec.png)

This is Fedora 37, with Cockpit compiled from a branch close to what's in main (so around Cockpit 283).

**Comment by ne20002** [comment]
I checked my system. I appears that on all virtual machines the colouring and the tooltip is working correctly. On the host it is not (and it has until some time ago). 
The host is using multiple disks, raid and lvm. A reboot did not help neither emtying cache in the browser (Firefox Linux).

**Comment by ne20002** [comment]
I found it. From the last backup a lvm volume snapshot was not been removed. After removing it the display is coloured again and all disks are shown.
My fault, sorry.
