### ISSUE TITLE
python: `en` treated incorrectly in `Accept-Language` list

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#18216]
### Explain what happens

If we get an `Accept-Language` list like `en, de?q=0.8` the Python bridge will try to find `po.en.js` (which will fail) and then end up serving `po.de.js`.  The correct behaviour in this case would be to show the untranslated page.

Introduced by de8cb44547226b7fc25e015ec060f9c8ae838a71.

### Where is the problem in Cockpit?

None

### Server operating system

None

**Comment by martinpitt** [comment]
@jelly: Is that still actually the case? I thought you reworked this?

**Comment by allisonkarlitskaya** [comment]
This got fixed in https://github.com/cockpit-project/cockpit/pull/18223/commits/cc000f425df74535c0f4f484225bf7272294079e
