### ISSUE TITLE
Performance Metrics "No Data Available"

### ISSUE THREAD

**Issue by PeterDragonTM** [cockpit-project/cockpit#18229]
### Explain what happens

**Fresh install of RasberryPi OS Bullseye, and Cockpit Version: 239-1**
1. sudo apt update
2. sudo apt upgrade
3. sudo apt install cockpit
4. Log into https://localhost:9090
5. Under Overview, click on "[View details and history]"
6. Under "CPU, Memory, Disks , Network" The error "No data available"

**Troubleshooting Performed So far:** 
Rebooted the OS
sudo apt remove, and purge
Verified all services were enabled (Example: Network Manager, daemons, etc..)

**Checked to see if proper packages were install:** 
sudo apt list --installed | grep cockpit

cockpit-bridge/stable,now 239-1 armhf [installed,automatic]
cockpit-networkmanager/stable,now 239-1 all [installed,automatic]
cockpit-packagekit/stable,now 239-1 all [installed,automatic]
cockpit-pcp/stable,now 239-1 armhf [installed]
cockpit-storaged/stable,now 239-1 all [installed,automatic]
cockpit-system/stable,now 239-1 all [installed,automatic]
cockpit-ws/stable,now 239-1 armhf [installed,automatic]
cockpit/stable,now 239-1 all [installed]

At the moment I am unable to view real time metrics overtime. On the page I see the bars giving me at the moment stats, but the over time graphs that you can filter by day are empty. 

Thoughts?

### Version of Cockpit

Version: 239-1

### Where is the problem in Cockpit?

Metrics

### Server operating system

Debian

### Server operating system version

NAME="Raspbian GNU/Linux", VERSION="11 (bullseye)"

### What browsers are you using?

Chrome

**Comment by garrett** [comment]
Raspberry Pi OS (and Raspbian, in older versions, as it used to be called) is not Debian. It's a fork of Debian and is actually different in many ways.

It is an OS intended for a simple desktop, for educational purposes. (This is why there are additional distros ported to the Pi, to fill general purpose computing needs.)

As such, as far as I know, the Raspberry Pi folks do not actively maintain packages outside of what you see on the desktop (and the necessary ones below, like the kernel) and merely pull many of them in from Debian.

---

I've looked to see if this is a problem with Debian or Rapsbery Pi OS by doing the following:

Installed two VMs:

- the x86_64 version of Raspberry Pi OS, bullseye
- Debian 11, also bullseye

Inside of each VM, I then:

1. updated all packages
2. installed `cockpit` and `cockpit-pcp`
3. rebooted
4. let each sit several minutes

Cockpit 239 on Debian shows events, as expected:

![image](https://user-images.githubusercontent.com/10246/214838147-e9193832-79e0-457e-a79c-b69652948508.png)

Cockpit 239 in Raspberry Pi OS does not (this is what you're seeing):

![image](https://user-images.githubusercontent.com/10246/214848325-f3e6703e-11aa-4ffe-aa77-805a1f0df968.png)

This confirms that it's a problem specific to Raspberry Pi OS. You'll need to contact them.

We package for Debian (among several other distributions) and actively test our Debian builds with automated and manual testing. (Our list of supported distributions is at https://cockpit-project.org/running.html#installation--setup — "Available" means there's a version in the repository. "Tested" means we specifically test it in our automated testing framework. The distribution might or might not do additional testing. In the cases of the distributions listed on that page, they also each do some form of testing. Other distributions, such as Raspberry Pi OS, might not.)

Raspberry Pi bugs page is @ https://www.raspbian.org/RaspbianBugs

I _think_ you need to file it against the distro at their tracker @ https://github.com/RPi-Distro/repo/issues

Additionally, this is also _probably_ a problem with PCP, not Cockpit itself.

---

Meanwhile, you might want to consider switching to Debian proper (as it's the most similar distribution to Raspberry Pi OS), for better software support overall.

- https://wiki.debian.org/RaspberryPi
- https://raspi.debian.net/
