### ISSUE TITLE
Implement shell l10n in the python bridge

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#18224]
We're going to abandon the `*/po.js` globbing approach for collecting and serving the translations of all of the packages to the shell for several reasons:

 - globbing doesn't work well in the presence of gzipped data and requires the data to be decompressed by the bridge before it can be concatenated with non-compressed data.  gzip streams can be concatenated, but for simplicity, the C bridge decompresses even if all of the files are gzipped.  We want to avoid gzip decompression in the Python bridge

 - the globbing mechanism itself is a bit too big of a hammer for being implemented as a general purpose feature, when it's used for exactly one path `*/po.js` and from exactly one place (the shell)

 - the amount of data sent is very large: the shell doesn't need the full translation of every page — only the strings that appear in the manifest.

There are many possible solutions to this problem:
 - have the bridge parse the `po.js` files and extract the strings relevant to translating the manifest
   - can be done because the bridge reads the manifests and can build a list of those strings
   - could also be done using msgctxt to hint which strings are from manifests
   - could also be added to the `po.js` file in some other way by `cockpit-po-plugin` based on the file references informaiton (ie: is `manifest.json` mentioned?)
     - possibly per-string, in the unused `[0]` field of the destination of the translation
     - possibly by grouping the manifest-relevant and manifest-irrelevant strings onto separate lines in the `po.js` file — the bridge would only read the first line in order to get strings for the manifest.  This would greatly simplify the "parsing"
 - all translations could be merged into the built `manifest.json` file by webpack
   - this file is currently copied directly over from `pkg/` to `dist/` during the build.  Adding the translations might require creating a new webpack plugin.
   - it would also require changes on the client side unless the bridge converted the data in the manifest into `cockpit.locale()` calls
    - it would result in too much data being sent in another way: instead of the entire translation for all pages in the current language, we'd get only the manifest-relevant strings, but we'd get them in every language, which is a different kind of wastefulness
  - modify `cockpit-po-plugin` to write the manifest-relevant translations to separate files like `apps/po.manifest.de.js`/`.json`/`.gz` for each package and each language
    - this would double the number of translation files on the disk
    - if the standard says that all of these files need to be compressed, then we can compress them all and serve the concatenated compressed stream
    - if this is uncompressed JSON data, we can merge it into the `/manifests.js` that we already serve.  this would require client-side changes, or a bit of code added to the served manifests blob.
    - if this is uncompressed JS data we can simply concatenate it to the `/manifests.js` that we already serve

After a quick IRC conversation, we seem to be consolidating around the option to have `cockpit-po-plugin` split out the manifest-related translations into separate per-language files (ie: the last option).  It's not clear if those will be in JSON or JS form, but either way, they'll probably be stored uncompressed, minimally processed by the bridge (either merging of JSON dictionaries, as we already do for the `manifest.json` files, or straight-up file concatenation), and served as part of `/manifests.js`.

**Comment by martinpitt** [comment]
> if the standard says that all of these files need to be compressed, then we can compress them all and serve the concatenated compressed stream

There's no "standard" around that, simply a convention/our choice in webpack.config.js to compress stuff in general. We already opted out of it for the login page and for HTML pages, and it's reasonable to not compress the manifest.po.LL.json files either.

Thanks @allisonkarlitskaya for the summary! My current gut feeling is that your third approach (apps/manifest.po.de.json) together with cockpit-bridge's /manifests.js path inlining the correct translations at runtime is the best in terms of efficiency, simplicity, elegance, and not changing the [manifests.js API](https://cockpit-project.org/guide/latest/cockpit-manifest.html) unnecessarily.

**Comment by jelly** [comment]
> There are many possible solutions to this problem:
> 
> * have the bridge parse the `po.js` files and extract the strings relevant to translating the manifest
>   
>   * can be done because the bridge reads the manifests and can build a list of those strings
>   * could also be done using msgctxt to hint which strings are from manifests
>   * could also be added to the `po.js` file in some other way by `cockpit-po-plugin` based on the file references informaiton (ie: is `manifest.json` mentioned?)
>     
>     * possibly per-string, in the unused `[0]` field of the destination of the translation
>     * possibly by grouping the manifest-relevant and manifest-irrelevant strings onto separate lines in the `po.js` file — the bridge would only read the first line in order to get strings for the manifest.  This would greatly simplify the "parsing"

I find this rather ugly and this is requires changes in all plugins no? The whole idea of `po.js` is to execute itself now we are again modifying things in flight and as translation files could be gzipped this sounds like the problem we are trying to fix.

> * all translations could be merged into the built `manifest.json` file by webpack
>   
>   * this file is currently copied directly over from `pkg/` to `dist/` during the build.  Adding the translations might require creating a new webpack plugin.
>   * it would also require changes on the client side unless the bridge converted the data in the manifest into `cockpit.locale()` calls
>   * it would result in too much data being sent in another way: instead of the entire translation for all pages in the current language, we'd get only the manifest-relevant strings, but we'd get them in every language, which is a different kind of wastefulness

Is it really wasteful? I can't imagine a `manifest.json` having more then 10-20 translations? The real question is how we support this, we currently load a single translation js file which is directly executed. I guess the Javascript code could look at `cockpit.language` to determine what JavaScript translation should be used?

> * modify `cockpit-po-plugin` to write the manifest-relevant translations to separate files like `apps/po.manifest.de.js`/`.json`/`.gz` for each package and each language
>   
>   * this would double the number of translation files on the disk
>   * if the standard says that all of these files need to be compressed, then we can compress them all and serve the concatenated compressed stream
>   * if this is uncompressed JSON data, we can merge it into the `/manifests.js` that we already serve.  this would require client-side changes, or a bit of code added to the served manifests blob.
>   * if this is uncompressed JS data we can simply concatenate it to the `/manifests.js` that we already serve
> 
> After a quick IRC conversation, we seem to be consolidating around the option to have `cockpit-po-plugin` split out the manifest-related translations into separate per-language files (ie: the last option). It's not clear if those will be in JSON or JS form, but either way, they'll probably be stored uncompressed, minimally processed by the bridge (either merging of JSON dictionaries, as we already do for the `manifest.json` files, or straight-up file concatenation), and served as part of `/manifests.js`.

AH :)

My only question with the change of globbing is, we'll have to update all our plugins to support this new workflow right?  So we need:

1. Make `cockpit-po-plugin` split out manifest related translations
2. Update `cockpit-po-plugin` in all our projects
3. ????
4. Load via `manifest.js`

**Comment by martinpitt** [comment]
@jelly : Ideally there would not be a "3. ???", once the po plugin is updated and the files get shipped (which should be automatic), then the rest is inside the shell.
