### ISSUE TITLE
Recommendation: server cluster monitoring design

### ISSUE THREAD

**Issue by kksay2010** [cockpit-project/cockpit#18238]
Page: 
I need a clear and simple monitoring scheme
      1. Simple deployment (satisfied)
       2. Clear interface (unsatisfactory)
I hope I can clearly see the information of all servers (cpu, memory, disk occupancy, disk write, disk read, broadband upload and download, number of connections, number of tcp connections)
The current mainstream solution is Node_ Exporter+Prometheus+grafana, but the deployment is cumbersome.
I hope you can refer to this design
![image](https://user-images.githubusercontent.com/29589474/214501928-97c36b71-1caf-4deb-8c5f-66772cd6e527.png)

source：
   https://grafana.com/grafana/dashboards/11074-node-exporter-for-prometheus-dashboard-en-v20201010/

**Comment by garrett** [comment]
Cockpit is mainly intended for single servers.

There are minimal multi-user integration points in the interface, such as switching between various hosts running Cockpit, and being able to run multiple virtual machines (cockpit-machines) or containers (cockpit-podman) on one host. And there's Cockpit's PCP+Grafana integration (https://cockpit-project.org/blog/pcp-grafana.html) for bringing metrics from individual machines together into Grafana.

For running server clusters, the intended tool would be [OpenShift](https://www.redhat.com/en/technologies/cloud-computing/openshift) or its upstream community project [OKD](https://www.okd.io/).

This all said, if you want to develop a server cluster monitor app that runs in Cockpit, then check out the https://cockpit-project.org/blog/cockpit-starter-kit.html and developer docs on the bottom of the "contributing" page @ https://cockpit-project.org/external/wiki/Contributing.html

But we're not going to develop a server cluster monitoring tool within Cockpit itself. It's wildly out of scope of Cockpit's goals and intent.

Right now, if you want to have a view of metrics across multiple servers, you're probably best off looking into the aforementioned [PCP+Grafana integration that Cockpit provides](https://cockpit-project.org/blog/pcp-grafana.html).

Hopefully this info helps!
