### ISSUE TITLE
Metrics not loading (problem with pmlogger)

### ISSUE THREAD

**Issue by fredlarochelle** [cockpit-project/cockpit#18277]
### Explain what happens

 
![image](https://user-images.githubusercontent.com/21048605/215898904-d95b91d8-35be-4a34-a781-4453e347f3ab.png)

As you can see, I get that pmlogger.service is not running. Then, when I try to restart pmlogger I get the following error: 

![image](https://user-images.githubusercontent.com/21048605/215899313-24648894-98a8-40c2-ab51-71614fcb1864.png)

It doesn't work either when I try to restart the service using `sudo systemctl restart pmlogger`. I get
```Job for pmlogger.service failed because the service did not take the steps required by its unit configuration. See "systemctl status pmlogger.service" and "journalctl -xeu pmlogger.service" for details.```

Then trying `systemctl status pmlogger.service`, I get 
![image](https://user-images.githubusercontent.com/21048605/215900276-dbf46d0b-703a-40af-822d-c94a0cf43cd0.png)

If it is of any help, it was working a couple weeks ago (can't remember when exactly) and apart from updates, only the Intel oneAPI HPC Toolkit was added to the system. Should not be the source of the problem tho...

Any ideas what could the problem be? Thanks!

### Version of Cockpit

283

### Where is the problem in Cockpit?

Metrics

### Server operating system

Fedora

### Server operating system version

Fedora 37

### What browsers are you using?

Chrome

### System log

```shell
Here is the log with `journalctl --since -5m`:
Jan 31 17:40:07 dev1 systemd[1]: pmlogger.service: Failed with result 'protocol'.
Jan 31 17:40:07 dev1 systemd[1]: Failed to start pmlogger.service - Performance Metrics Archive Logger.
Jan 31 17:40:07 dev1 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=pmlogger comm="systemd" exe="/usr/lib/systemd/system>
Jan 31 17:40:07 dev1 systemd[1]: Starting pmlogger_farm.service - pmlogger farm service...
Jan 31 17:40:07 dev1 systemd[1]: Started pmlogger_farm.service - pmlogger farm service.
Jan 31 17:40:07 dev1 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=pmlogger_farm comm="systemd" exe="/usr/lib/systemd/s>
Jan 31 17:40:08 dev1 systemd[1]: pmlogger.service: Scheduled restart job, restart counter is at 18.
Jan 31 17:40:08 dev1 systemd[1]: Stopping pmlogger_farm.service - pmlogger farm service...
Jan 31 17:40:08 dev1 systemd[1]: pmlogger_farm.service: Deactivated successfully.
Jan 31 17:40:08 dev1 systemd[1]: Stopped pmlogger_farm.service - pmlogger farm service.
Jan 31 17:40:08 dev1 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=pmlogger_farm comm="systemd" exe="/usr/lib/systemd/sy>
Jan 31 17:40:08 dev1 systemd[1]: Stopped pmlogger.service - Performance Metrics Archive Logger.
Jan 31 17:40:08 dev1 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=pmlogger comm="systemd" exe="/usr/lib/systemd/system>
Jan 31 17:40:08 dev1 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=pmlogger comm="systemd" exe="/usr/lib/systemd/systemd>
Jan 31 17:40:15 dev1 tailscaled[1119]: Accept: TCP{[IP_redacted] > [IP_redacted]} 89 ok out
Jan 31 17:40:25 dev1 tailscaled[1119]: Accept: TCP{[IP_redacted] > [IP_redacted]} 89 ok out
Jan 31 17:40:35 dev1 tailscaled[1119]: Accept: TCP{[IP_redacted] > [IP_redacted]} 52 tcp non-syn
Jan 31 17:40:45 dev1 tailscaled[1119]: Accept: TCP{[IP_redacted] > [IP_redacted]} 52 tcp non-syn
Jan 31 17:40:55 dev1 tailscaled[1119]: Accept: TCP{[IP_redacted] > [IP_redacted]} 52 tcp non-syn
Jan 31 17:41:02 dev1 root[15188]: pmcd_wait failed in /usr/libexec/pcp/lib/pmcd: exit status: 2
Jan 31 17:41:02 dev1 systemd[1]: pmcd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 31 17:41:02 dev1 systemd[1]: pmcd.service: Failed with result 'exit-code'.
Jan 31 17:41:02 dev1 systemd[1]: Failed to start pmcd.service - Performance Metrics Collector Daemon.
Jan 31 17:41:02 dev1 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=pmcd comm="systemd" exe="/usr/lib/systemd/systemd" h>
Jan 31 17:41:02 dev1 systemd[1]: Starting pmlogger.service - Performance Metrics Archive Logger...
Jan 31 17:41:02 dev1 systemd[1]: pmcd.service: Scheduled restart job, restart counter is at 19.
Jan 31 17:41:02 dev1 systemd[1]: Stopped pmcd.service - Performance Metrics Collector Daemon.
Jan 31 17:41:02 dev1 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=pmcd comm="systemd" exe="/usr/lib/systemd/systemd" h>
Jan 31 17:41:02 dev1 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=pmcd comm="systemd" exe="/usr/lib/systemd/systemd" ho>
Jan 31 17:41:02 dev1 systemd[1]: Starting pmcd.service - Performance Metrics Collector Daemon...
Jan 31 17:41:05 dev1 tailscaled[1119]: Accept: TCP{[IP_redacted] > [IP_redacted]} 52 tcp non-syn
Jan 31 17:41:08 dev1 systemd[1]: pmlogger.service: Failed with result 'protocol'.
Jan 31 17:41:08 dev1 systemd[1]: Failed to start pmlogger.service - Performance Metrics Archive Logger.
Jan 31 17:41:08 dev1 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=pmlogger comm="systemd" exe="/usr/lib/systemd/system>
Jan 31 17:41:08 dev1 systemd[1]: Starting pmlogger_farm.service - pmlogger farm service...
Jan 31 17:41:08 dev1 systemd[1]: Started pmlogger_farm.service - pmlogger farm service.
```

**Comment by marusak** [comment]
I believe this is due to https://bugzilla.redhat.com/show_bug.cgi?id=2013937

Can you check your version of pcp and try to update it?

**Comment by fredlarochelle** [comment]
Running 'dnf info pcp', I get that I am running pcp 6.0.1 which, from their [Github repo](https://github.com/performancecopilot/pcp) seems to be the latest release.

![image](https://user-images.githubusercontent.com/21048605/216104325-81cb723f-a99b-4b8d-8cd9-6e889a9407c5.png)


Also, running `dnf info cockpit-pcp`, I get the following (Cockpit was also updated to version 284 since yesterday and the problem is still present).

![image](https://user-images.githubusercontent.com/21048605/216103724-3c091660-11b6-4d3a-b6e5-baa32d86a891.png)

Should I file a new bug report with Red Hat, since this one dates back to October 2021 and was closed in May 2022?

**Comment by bitbull06** [comment]
Any chance this could be updated or a solution provided? Still having this issue here, on RHEL 8.7 with pcp 5.3.7 and cockpit-pcp 276 ...

**Comment by bitbull06** [comment]
Yes, but reinstalling os entirely in an enterprise environment is not really an option (for everybody) I guess. Still hoping for a less drastic outcome.


________________________________

**Comment by martinpitt** [comment]
@bitbull06 Well, it was fixed with a PCP update in RHEL 9 as well, almost a year ago? https://access.redhat.com/errata/RHBA-2022:2370

**Comment by bitbull06** [comment]
Great for RHEL9, but still using 8(.7) here ...


________________________________

**Comment by martinpitt** [comment]
Yeah, sorry.. that must be fixed in PCP. Perhaps if you report it against RHEL 8 in bugzilla?

**Comment by UbuntuRunner** [comment]
chown -R cockpit-wsinstance /var/log/pcp/pmlogger/

(So exactly the opposite way compared to the suggestion at https://forums.fedoraforum.org/showthread.php?331674-pmlogger-not-starting-after-Fedora-IoT-upgrade-to-39&p=1877886)

**Comment by FeelTheLemon** [comment]
Faced the same problem with PCP 6.3.1 after system upgrade 
pmlogger is running under pcp user and files in /var/log/pcp/pmlogger already owned by pcp

Removed everything there and restarted pmlogger and it finally started to show metrics

**Comment by taras-bors** [comment]
> Faced the same problem with PCP 6.3.1 after system upgrade pmlogger is running under pcp user and files in /var/log/pcp/pmlogger already owned by pcp
> 
> Removed everything there and restarted pmlogger and it finally started to show metrics

Thanks, that worked for me on Fedora 41.

**Comment by GegeApl** [comment]
Check rights 
I noticed insufficient rights drwxr-x--- 
I fixed with sudo chmod 775 /var/log/pcp/pmlogger/MyHost/
then restarted pmlogger
