### ISSUE TITLE
docker: problem while starting/stopping container

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#1831]
During tests for #1772, hubbot encountered the following error:

![check-docker-testbasic-fail](https://cloud.githubusercontent.com/assets/8711649/6246220/d31b0170-b766-11e4-8388-a231f7be6850.png)

If this errors comes up again, we should look into whether containers are properly stopped. I found references to this error, along with a [possible fix](https://github.com/docker/docker/issues/7015#issuecomment-52522196).

For now, I don't have a way to reliably reproduce the error.

**Comment by stefwalter** [comment]
Made a note in the bug upstream that we're affected by this.

**Comment by stefwalter** [comment]
Work around posted upstream: 

```
sudo systemctl stop docker-<container_hash>.scope
```
