### ISSUE TITLE
Unable to install applications

### ISSUE THREAD

**Issue by TeoConan** [cockpit-project/cockpit#18329]
### Explain what happens

1. Install cockpit
2. Run and setup cockpit
3. Install another app (like cockpit-certificates for example)
4. And then nothing appear in the application panel
![image](https://user-images.githubusercontent.com/22664730/218286846-59160a45-9c01-42d3-8f40-aa20701b3640.png)

I'm on a raspberry pi 2 debian, I don't know how I can setup some vhost on cockpit
I tried to install backport repository, but it failed, I don't know why

### Version of Cockpit

239

### Where is the problem in Cockpit?

Applications

### Server operating system

Debian

### Server operating system version

22.10

### What browsers are you using?

Chrome

**Comment by KKoukiou** [comment]
How did you install cockpit-certificates? It's not available on ubuntu variants afaik.

For using backports follow the instructions from https://cockpit-project.org/running. Search for backports. Please update the issue 

Please update your cockpit-* packages and let us know if the issue persists, as this is a very old cockpit version and pretty hard to get to understand any issues.
