### ISSUE TITLE
Overview/Metrics reports CPU Critical Temperature instead of Current

### ISSUE THREAD

**Issue by jwhaugustine** [cockpit-project/cockpit#18335]
### Explain what happens

Having updated cockpit from version 284 to 285, all of my physical machines running cockpit web interface are now reporting the CPU's critical temperature on the metrics page instead of their actual temperature.

These are all older PowerEdge systems, R210II R420 R620 on Ubuntu Jammy 22.04 server.

Running ```sensors``` confirms a display issue:
```
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +46.0°C  (high = +87.0°C, crit = +97.0°C)
Core 0:        +44.0°C  (high = +87.0°C, crit = +97.0°C)
Core 1:        +45.0°C  (high = +87.0°C, crit = +97.0°C)
Core 2:        +46.0°C  (high = +87.0°C, crit = +97.0°C)
Core 3:        +43.0°C  (high = +87.0°C, crit = +97.0°C)
Core 4:        +45.0°C  (high = +87.0°C, crit = +97.0°C)
Core 5:        +40.0°C  (high = +87.0°C, crit = +97.0°C)

coretemp-isa-0001
Adapter: ISA adapter
Package id 1:  +43.0°C  (high = +87.0°C, crit = +97.0°C)
Core 0:        +42.0°C  (high = +87.0°C, crit = +97.0°C)
Core 1:        +40.0°C  (high = +87.0°C, crit = +97.0°C)
Core 2:        +43.0°C  (high = +87.0°C, crit = +97.0°C)
Core 3:        +40.0°C  (high = +87.0°C, crit = +97.0°C)
Core 4:        +41.0°C  (high = +87.0°C, crit = +97.0°C)
Core 5:        +38.0°C  (high = +87.0°C, crit = +97.0°C)
```

### Version of Cockpit

285

### Where is the problem in Cockpit?

Metrics

### Server operating system

Ubuntu

### Server operating system version

22.04.1

### What browsers are you using?

Chrome

**Comment by tomasmatus** [comment]
Thank you for your report, I hope we didn't cause you any inconveniences by alarming that your servers are on fire.

@martinpitt looks like the sensor check was broken in abb9ed4 and `sscanf()` is satisfied with anything that begins with `temp%d` when it should only take `temp%d_input` as a valid temperature sensor.

**Comment by sch-dmtr** [comment]
Same bug, Dell PowerEdge T130
![Screenshot_20230217-105559_Chrome](https://user-images.githubusercontent.com/98957088/219589897-18158e22-2a5b-4d12-ad2d-b1f6d2b98c4f.jpg)
![Screenshot_20230217-110551_Termius](https://user-images.githubusercontent.com/98957088/219589905-3a02f937-37fb-4fe9-80d8-4ff91bab1e2a.jpg)
![Screenshot_20230217-111132_Chrome](https://user-images.githubusercontent.com/98957088/219590306-3a9a938a-addf-438c-ba9d-a52d07f39d51.jpg)
