### ISSUE TITLE
Smiley at success of syncing accounts too silly?

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1836]
![screenshot from 2015-02-19 11 25 12](https://cloud.githubusercontent.com/assets/209895/6265058/0b2c37a0-b82a-11e4-979b-34003131fb56.png)

Perhaps better to use pficon-ok [1] in this case.
I wanted to use pficon-ok for successful process in the subscriptions UI, so might as well make the two consistent.

1. https://www.patternfly.org/visual-styles/icons-glyphs/

**Comment by stefwalter** [comment]
fixed.
