### ISSUE TITLE
Accounts: -1 more

### ISSUE THREAD

**Issue by supakeen** [cockpit-project/cockpit#18371]
### Explain what happens

1. Visit the /users endpoint.
2. Groups shows -1 more users.

![Screenshot_2023-02-20_09-33-55](https://user-images.githubusercontent.com/39536295/220053952-c4613212-2f71-4170-9273-d79d0380f396.png)
![Screenshot_2023-02-20_09-34-10](https://user-images.githubusercontent.com/39536295/220053965-0cfdb054-6e1a-4fdd-a9e8-a1a94fbb4b13.png)

### Version of Cockpit

284

### Where is the problem in Cockpit?

Accounts

### Server operating system

Fedora

### Server operating system version

Fedora IoT 37

**Comment by KKoukiou** [comment]
Thanks for taking the time to report this. This has been already fixed in 285 with:

```
commit 3cee85cc05b6b8f6769524acec51d7b9ec278dee
Author: Katerina Koukiou <kkoukiou@redhat.com>
Date:   Tue Jan 10 11:01:01 2023 +0100

    users: Add filter for the groups table
```
