### ISSUE TITLE
historical graphs time controls a bit too promintent

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1837]
I recall talking briefly to either @stefwalter or @mvollmer about a week ago, so noting this down before I forget.

While buttons rows are more discoverable in the sense that you get a quick overview of the different options right away, they also eat a lot of space and takes attention away from other elements on the screen. Using a dropdown of the different time options might therefore be a better idea.

**Comment by stefwalter** [comment]
The buttons should also not be treated as modal. They are shortcuts to scrolling operations. In other words they make more sense as menu items in a drop down.

**Comment by andreasn** [comment]
And it that vein it would be possible to show the timescale you're currently looking at. "2 days", "30 minutes" if there is a good way to figure that out.

**Comment by andreasn** [comment]
Fixed in #1834, so closing.
