### ISSUE TITLE
`ESC[0m` won't reset colors if followed by new line

### ISSUE THREAD

**Issue by CarterLi** [cockpit-project/cockpit#18378]
### Explain what happens

`echo -e '\033[41;31m!\033[0m\n'`

# Expected: (iTerm2)

<img width="364" alt="image" src="https://user-images.githubusercontent.com/6134068/220274152-505554a1-5255-4b47-bdc0-02e8fc841c67.png">

# Actual: (Cockpit)

<img width="471" alt="image" src="https://user-images.githubusercontent.com/6134068/220274046-9f09fed1-85d1-4956-b781-5c64ac343bfc.png">

### Version of Cockpit

285

### Where is the problem in Cockpit?

Terminal

### Server operating system

Fedora

### Server operating system version

Linux eoitek.net 6.2.0-0.rc8.20230217gitec35307e18ba.60.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Feb 17 16:19:48 UTC 2023 x86_64 GNU/Linux

### What browsers are you using?

Chrome, Edge

**Comment by CarterLi** [comment]
Ref: https://github.com/LinusDierheimer/fastfetch/issues/418

**Comment by garrett** [comment]
This is not a Cockpit bug, but a terminal emulation bug.

We use xterm.js to render the console, specifically version `5.1.0` at the moment (this is the latest release), with the canvas addon that is version `0.3.0`.

That said, VS Code also uses xterm.js — and I tested it in VS Codium and got this:

![image](https://user-images.githubusercontent.com/10246/220293252-3ed2f504-585a-4b26-b2b1-c7c868b21bb7.png)

So at least one implementation is correct... but they're using a different renderer by default (at least on my system). 

As VS Code uses Electron, I also tried Cockpit in Chrome (as they'd effectively use the same browser engine). The this bug still shows up in Cockpit's terminal:

![image](https://user-images.githubusercontent.com/10246/220295607-a35037ec-bbc7-4658-b1b9-121c68a4707f.png)

But in VS Codium have "auto" as my renderer:

![image](https://user-images.githubusercontent.com/10246/220297341-eefca5d8-7197-4487-adf3-fcfbc4094afa.png)

When I switch the renderer to "canvas", I see the bug in VS Codium too:

![image](https://user-images.githubusercontent.com/10246/220297964-4bfb064f-fcf0-4900-a9cc-20a70450d315.png)

Here's the upstream issue @ xterm.js:

- https://github.com/xtermjs/xterm.js/issues/4120

We'll have to wait for upstream to fix this and we'll update the dependency when they do.

**Comment by CarterLi** [comment]
Let's wait for xterm.js change then

**Comment by CarterLi** [comment]
The new version of xterm has been released for several weeks. Does the problem still exist?

**Comment by martinpitt** [comment]
We can't update to xterm 5.2, as that breaks the accessibility tree: https://github.com/xtermjs/xterm.js/issues/4571 .

**Comment by garrett** [comment]
xterm.js fixed the accessibility tree in the PR @ https://github.com/xtermjs/xterm.js/pull/4637 — we should consider updating.

**Comment by jelly** [comment]
It's fixed in 5.3.0
