### ISSUE TITLE
Cockpit shows my cpu temperature at 100℃ 

### ISSUE THREAD

**Issue by akronblim** [cockpit-project/cockpit#18397]
### Explain what happens

1. I opened my cockpit 
2. Click the 'View metrics and history'
3. And it shows my server cpu temperature at 100℃, it never drop

When I type `cat /sys/devices/virtual/thermal/thermal_zone0/temp` in terminal, it shows 43000, all other cores are at the same temperature or around. 
Besides my server is my old laptop, and I can touch it, it's pretty cool

Here is screenshot
![QQ图片20230224001718](https://user-images.githubusercontent.com/22946763/220966616-6dda62ce-ba08-4d63-971c-e242d57417e5.png)

### Version of Cockpit

285

### Where is the problem in Cockpit?

Metrics

### Server operating system

CentOS

### Server operating system version

CentOS Stream release 9

### What browsers are you using?

Chrome

**Comment by jelly** [comment]
286 has a fix for this issue, please upgrade and re-open if it's still an issue.

https://github.com/cockpit-project/cockpit/commit/452e8007cd21f6af185ec3e24c50829de1dd2309
