### ISSUE TITLE
Overview CPU temperature value display error

### ISSUE THREAD

**Issue by kekylin** [cockpit-project/cockpit#18394]
### Explain what happens

1. Log in to Ubuntu with an administrator account
2. Open Overview - Indicators and History
3. View CPU temperature values
4. I used lm-sensors to check and the actual CPU temperature is only 53°C.
5. In cockpit version 284, the temperature display here is correct
![20230223152207](https://user-images.githubusercontent.com/65521882/220843409-964951c1-c9a2-42ad-96df-eaa9d89a2a65.png)

### Version of Cockpit

cockpit v285

### Where is the problem in Cockpit?

Overview

### Server operating system

Ubuntu

### Server operating system version

ubuntu server 22.04

### What browsers are you using?

Chrome

**Comment by martinpitt** [comment]
This got fixed in version 286. I'll update the backport for Ubuntu 22.04 as soon as that version [lands](https://launchpad.net/ubuntu/+source/cockpit) in lunar.
