### ISSUE TITLE
user: Create new account modal has password-related UI issues

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#18391]
Follow-up to https://github.com/cockpit-project/cockpit/pull/18234#pullrequestreview-1309520648.

Screenshot of the create new user modal:

![image](https://user-images.githubusercontent.com/10246/220672692-3ee66dbc-43db-43f1-8a77-481e4bfdb560.png)

Issues:

1. "Confirm" should be "Confirm password".
2. Password strength meter is too far away from the entry, and there's no text to explain what's going on (unless you have an "Excellent" password.
3. Confirmation doesn't show if it matches or not. (In this screenshot, it clearly does not match and the focus is in another form.)
4. Authentication is about using a password, so it should be before the password entries.
5. Home and shell should probably come before authentication and password, especially since home changes when username does.

**Comment by garrett** [comment]
What we have now also deviates from the mockups @ https://github.com/cockpit-project/cockpit/discussions/17604, which has these high-fidelity mockups:

![image](https://user-images.githubusercontent.com/10246/220679208-ef86a06b-52a0-49a1-bca1-59ad729d2909.png)

![image](https://user-images.githubusercontent.com/10246/220679229-7e6ba4f6-a691-4f39-a518-9d4b48ec6fb4.png)

---

I found some ideas I was sketching out on the road to the mockups above, which all have the idea of having some way to have basic information and additional information:

![users-create excalidraw](https://user-images.githubusercontent.com/10246/220679881-528052c8-70b4-4a17-a91a-6d5bdeaeb76b.png)

And I found this old-ish mockup:

![account-create-disallow-password excalidraw](https://user-images.githubusercontent.com/10246/220677295-9c6fe2ac-0237-452c-8bd0-f5b6b7bcc75d.png)

What we have now is lacking a lot of things in all of the mockups.

---

I'm happy to work with you on what it should be like; we can iterate further. But we shouldn't stray so far from the mockups, unless there are good reasons when developing it. I can create new mockups that fit updated considerations if these don't work for whatever reasons.

**Comment by garrett** [comment]
To be clear: This should land in the next release as a follow-up. It should be treated as high priority.

We don't have to have expanding. But we do need to have everything else mentioned in the list above, including the renaming, reordering, and so on.

Adding groups would be good, but that can come later. Let's work with what we have to fix the layout first.

**Comment by 17rawat** [comment]
Hey Garrett, could you assign this issue to me?  I have a 1-year of experience in web.

**Comment by garrett** [comment]
Sorry, this is supposed to be a follow-up to some of the longstanding PRs. https://github.com/cockpit-project/cockpit/pull/18234

I mistakenly thought that landed already; side effect of trying to track everything everywhere all at once.  Apologies to @skobyda.
