### ISSUE TITLE
storage: Filesystem delete entry in dropdown's should shown as dangerous

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#18415]
### Explain what happens

For example the stratis filesystem delete dropdown or a normal disk's delete dropdown entry is not shown as dangerous as required per [Patternfly guidelines](https://www.patternfly.org/v4/guidelines/colors/#status-and-state-colors).

![image](https://user-images.githubusercontent.com/67428/221591485-5d8c2991-a57a-4810-b866-cec7f4a7864f.png)

They should be shown as the image below, with red text.

![image](https://user-images.githubusercontent.com/67428/221592750-d441cc5a-0d29-4d32-9562-6da3475be97c.png)

## Reproduce

```
./test/image-prepare fedora-37
./bots/vm-run -s cockpit.socket fedora-37
```

* Open a browser http://localhost:9090 login and open the storage page.
* Click on the `/dev/vda2` filesystem 
* Click on the kebab menu (three dots on the right)
* This should open a dropdown menu with a Delete entry which doesn't have a red text.

### Version of Cockpit

main

### Where is the problem in Cockpit?

None

### Server operating system

None

**Comment by KKoukiou** [comment]
@sharmas07 if you feel like solving it, please just start working on it without worrying  about the assignment.

**Comment by Prince2319** [comment]
Can i do this issue?

**Comment by Keshav-0907** [comment]
Hi, Can I Work on this issue?

**Comment by KKoukiou** [comment]
@sharmas07 @Prince2319 @Keshav-0907 you all asked to work on this issue. I guess it's easy and therefore popular :)

Genrally, you don't need to ask, we 're more than welcoming external contributors. Just go ahead and send a PR. But before this:

* make sure you can build cockpit from sources
* make a tiny change like this and check that you see you changes

At this point just let the people know that you 're working on this issue, so as to avoid duplicate work. But don't ask for pre-assigning without knowing if you know how to implement the fix.

if you cant find something on GitHub issues that matches your level, you can also write in the team's IRC channel and we can find something small for you to work on.
