### ISSUE TITLE
Can't set a custom UDP port in firewall

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#18412]
Trying to open a UDP port 22222 but it won't let me. Gives me an error, "Port number and type do not match". 
![Screenshot from 2023-02-10 17-08-10](https://user-images.githubusercontent.com/108582693/218221617-e55d5636-099a-497d-8dc7-89a5f0a217c5.png)

See https://github.com/cockpit-project/cockpit/discussions/18326 for description of the problem and what is needed to change

**Comment by rrsingh11** [comment]
Hey, @marusak,

I saw the description for this problem. He did mention that he might work on this issue. 

![image](https://user-images.githubusercontent.com/86000208/221553087-fc407910-6329-4414-924d-030a33563b50.png)

If he's not, shall I work on this issue ? 

Also, I need help finding an Installation guide for Windows. I know Cockpit is an excellent plugin for Linux OS, but I also saw an Windows implementation on the website.
![image](https://user-images.githubusercontent.com/86000208/221562487-d1830cf2-2371-4a2f-adb2-2f8624c8d8fe.png)

Please provide me with any available resource.

Thanks

**Comment by KKoukiou** [comment]
@rrsingh11 you need to have a linux development environment if you wish you work on cockpit. cockpit is only meant for administering linux servers. You can access the web interface through a windows machine by specifying the remote IP/url to the the administered server, which is always a linux one.

**Comment by rrsingh11** [comment]
Oh, I think I have to install WSL. I hope that will help. Or shall I go with setting up dual boot on my system ?

**Comment by garrett** [comment]
@rrsingh11: Either dual boot or a VM would be better than running in WSL, but I've seen some mention of someone running Cockpit inside of WSL2, which is on Windows 11 or Windows 10 after 22H2 (October 2022 update).

I'm not sure what someone must do to install Cockpit on WSL2... but I'm sure it involves running systemd, which was previously impossible on WSL. Although, something changed (in the past... year or so?) that enabled systemd on WSL2, which let Cockpit run on it.

I remember seeing more info @ https://github.com/cockpit-project/cockpit/issues/14699

But none of us on the team have tried running Cockpit in WSL. We do run Cockpit in VMs (on Linux, but the principle is the same) all the time, however. And we're all running Linux on "bare metal" (that is: directly on the machine, not in a VM) as well. So dual boot or in a VM would be the best choices, not WSL. But you can _probably_ make WSL work too — but we can't help you make it work, as we don't have any experience with it. (However, if you do decide to try it and get it working, it would be interesting to know.)

**Comment by garrett** [comment]
@rrsingh11: Also, if you're considering dual booting:

- **Be sure to back up important data first**, as installation could theoretically go wrong (either by selecting the wrong thing in the installer or some possible bug — although with millions installing, it's probably not likely things will go wrong with the software)
- Most of us run [Fedora](https://getfedora.org/en/workstation/download/) as our main OS, so it would be a good choice of a distribution (so we could help you out)... but some of us are also quite familiar with Debian and Ubuntu too

**Comment by garrett** [comment]
Oh, additionally, that screenshot is about connecting to Cockpit on a remote system. (That's Windows connecting to Cockpit that is running in a Debian VM, showing that you can manage a Linux server from Windows. In other words, you don't need to use Linux as a desktop OS to manage a Linux server. But to run and develop for Cockpit, you do need to run Linux somewhere.)

**Comment by rrsingh11** [comment]
Thanks, @garrett

At first, I'll try to figure out using WSl because it sounds like "the path less traveled." And it will help me understand Linux better and maybe will help me familiarize with your code base. Like till yesterday, I was searching for why we write GNU/Linux instead of just Linux. I hope to make some progress by learning new stuff. 

If it becomes a total disaster, I'll surely get back to you after installing Fedora for any further help. 
And will share the experience.

**Comment by rrsingh11** [comment]
![image](https://user-images.githubusercontent.com/86000208/221854855-4dc96eb6-b9c2-4916-a4a3-d8d910ac41d9.png)

I tried figuring it out with WSL, and it is working fine. Please let me know if there is anything else, like any error with this page.

If this looks fine, I can start working on fixing the 🐛

**Comment by garrett** [comment]
@rrsingh11: Oh, nice! Glad to see Cockpit's working in WSL so easily for you! I hope development also works well too. (Main dev page @ https://cockpit-project.org/external/wiki/Contributing.html but the "HACKING" document is the one about setting up a development environment @ https://cockpit-project.org/external/source/HACKING.html)

(BTW: We probably should have this conversation elsewhere, perhaps in the forums @ https://github.com/cockpit-project/cockpit/discussions , and keep this issue about keeping a custom UDP port in the firewall.)

**Comment by garrett** [comment]
@rrsingh11: The GSoC guidelines @ https://github.com/cockpit-project/cockpit/wiki/GSoC-2023-topics#extra-requirements-for-applicants state:

> A Linux development environment is a must for GSoC candidate students

So you need to use a real Linux development environment, not WSL. While it looks like WSL works from your screenshot (that's really cool!), we cannot be sure that you won't run into problems and don't want you or us to be frustrated trying to debug any issues specific to Windows + WSL.

Additionally, most of the team uses Fedora, so that would be your best bet to get help from the team. (Several of us also know other distros too, but most of us know Fedora the best, and all parts of Cockpit work on Fedora, whereas a few parts aren't available with the same feature parity on other platforms.)

And please hang out in IRC with us, so we can help you out realtime.

**Comment by Sukriti-m** [comment]
Hey @garrett 
I'd like to work on this issue. I am using Ubuntu 22.04.2 LTS version on my desktop. 
Can it be assigned to me?

**Comment by 17rawat** [comment]
Hey, Garrett
I'd like to work on this project. I am using Mac. can I  setup this up on my machine?

**Comment by garrett** [comment]
@Sukriti-m & @17rawat: @KKoukiou is heading up GSoC. Chat with us on IRC: `irc.libera.chat` on channel `#cockpit`. 

The website has more info @ https://libera.chat/ — or if you don't have an IRC client, you can even use https://web.libera.chat/#cockpit and enter your "nick" (short for nickname — be sure to change this to yours) and click "Start".

**Comment by garrett** [comment]
@17rawat: If you're using a Mac, you cannot use macOS itself to work on Cockpit. You will need to use Linux.

There are two main ways to use Linux on a Mac computer: You must either run Linux inside of a **VM** (virtual machine) or **dual boot** (where you install side by side and reboot into a different operating system). Only Intel Macs support dual booting at this time. (Work is being done to support ARM-based "Apple Silicon", but it's not ready for most people yet.)

If you're on an Intel Mac and want to run Linux in a VM, there's [VirtualBox](https://www.virtualbox.org/wiki/Downloads), [Parallels](https://www.parallels.com/), and [VMware Fusion](https://www.vmware.com/products/fusion/fusion-evaluation.html). The first of these (VirtualBox) is free (except for the "extension pack" — _don't install that_) and the last two cost money.

If you're on an M1 or M2 "Apple Silicon" ARM-based Mac, you can run an Intel-based Linux distribution inside of a VM app known as **UTM**: https://mac.getutm.app/

As for which distribution, I strongly suggest **Fedora**, as you will be able to work on all of Cockpit. Other distributions cannot work on some parts of Cockpit, as they would require a VM and you don't want to get into a VM in a VM situation (as that can be quite slow, if it even would work on your computer) to be able to edit pages.

Regardless of the virtual machine you use, they all work similarly on macOS. They're an app that makes a software-based fake computer inside your computer. In this VM, you can then install a normal Linux installation, as if it were another computer.
