### ISSUE TITLE
Services: Wrong timer "next run" with machine suspends

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#18418]
I have a custom backup timer, which runs every hour. The "Last trigger" is right, but the "next run" is is utter nonsense, and even in the past:

![image](https://user-images.githubusercontent.com/200109/221684215-bf990606-48ff-4e73-9835-8247ae0e717d.png)

The real value:
```
❱❱❱ systemctl --user list-timers|cat
NEXT                        LEFT       LAST                        PASSED     UNIT                    ACTIVATES
Mon 2023-02-27 22:30:53 CET 31min left Mon 2023-02-27 21:30:53 CET 28min ago  backup.timer            backup.service
```

This is probably some mistake with the Realtime calculation, during the time when my laptop is suspended? I didn't investigate that yet, will do after my other umpteen bugs that I am currently looking at on the Services page :grin:

**Comment by marusak** [comment]
Pretty sure it is the same thing as https://github.com/cockpit-project/cockpit/issues/11252
I hoped it just got magically fixed :D

**Comment by martinpitt** [comment]
The problem is that the [NextElapseUSecMonotonic property](https://www.freedesktop.org/wiki/Software/systemd/dbus/) is relative to CLOCK_MONOTONIC, while the Services page reads the value from `/proc/uptime`, whose first value is CLOCK_BOOTTIME:
```
>>> time.clock_gettime_ns(time.CLOCK_BOOTTIME)//1000
344408992402
>>> time.clock_gettime_ns(time.CLOCK_MONOTONIC)//1000
143735908722

❱❱❱ cat /proc/uptime 
344504.66 154416.43

❱❱❱ sudo grep now /proc/timer_list
now at 144194728442454 nsecs
```

When I add the timer property to CLOCK_MONOTONIC, I get a sensible result. So we need a way to read CLOCK_MONOTONIC. Unfortunately there is no shell API for that, and /proc/timer_list can only be read by root. `systemctl list-timers` is not (easily) machine readable either. So it seems we are left only with bad options :cry:

**Comment by martinpitt** [comment]
There's one more way: we don't *really* need CLOCK_MONOTONIC, we only need the wallclock time of the last boot. This is actually fairly accurate as the ctime or mtime of `/proc` or `/proc/1` :speak_no_evil: Given that we only show minute precision anyway, this is probably even good enough?

**Comment by martinpitt** [comment]
It's actually amazingly accurate, up to milliseconds:
```
❱❱❱ python3 -c 'import time; print((time.clock_gettime_ns(time.CLOCK_REALTIME) - time.clock_gettime_ns(time.CLOCK_BOOTTIME))//1000000)'
1677911147687

❱❱❱ python3 -c 'import os; print(os.stat("/proc").st_ctime)'
1677911147.679
```
But I only just now realized that this doesn't actually help us -- the timer must be added to CLOCK_MONOTONIC, so we can't just add it to the boot time. Our whole approach here is wrong :cry:

**Comment by martinpitt** [comment]
I think the correct way to fix this is:

 * compute the duration until the timer runs next: delta = `NextElapseUSecMonotonic` - `CLOCK_MONOTONIC`
 * wallclock time of that, if we actually want to keep showing it as absolute time: `CLOCK_REALTIME` (aka `date +%s`) + `delta` = (`CLOCK_REALTIME` - `CLOCK_MONOTONIC`) + `NextElapseUSecMonotonic`
 * (`CLOCK_REALTIME` - `CLOCK_MONOTONIC`) is a constant mostly, so we don't need to re-compute this all the time, just when time zone etc. changes (which we do by listening to timedated events; it is *not* any meaningful value (such as "wallclock time of current boot"), just something like `monotonic_timer_base`.


So we either need to call python to compute this value, or teach this to the bridge. My current gut feeling is to try python, and if that fails, fall back to reading CLOCK_BOOTTIME as approximation.
