### ISSUE TITLE
testlib: add MachineCase.reboot and MachineCase.wait_reboot functions which allows restart messages

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#18424]
Tests which call `m.reboot` or `m.wait_reboot` should automatically call `self.allow_restart_journal_mesages` so we don't have to add this for every test which uses these functions.

To implement this we will need to extend the `MachineCase` class and add two new functions `reboot` and `wait_reboot` which calls `self.allow_restart_journal_messages` and either `self.machine.reboot()` or `self.machine.wait_reboot()` taking the `timeout_sec` parameter into account.

**Comment by gauravmishra2123** [comment]
Hey there! I would like to work on this issue

**Comment by jelly** [comment]
Sure, there are no pre-assigned issues so please try to setup a Cockpit development environment and ask any questions if they come up.

**Comment by gauravmishra2123** [comment]
> Sure, there are no pre-assigned issues so please try to setup a Cockpit development environment and ask any questions if they come up.

so I clone the project locally but I'm unable to understand how to implement changes please help me in this

**Comment by gauravmishra2123** [comment]
> Sure, there are no pre-assigned issues so please try to setup a Cockpit development environment and ask any questions if they come up.

what exactly I have to do is extend the **MachineCase** class and add two functions **reboot** which calls self.machine.reboot().  and **wait_reboot** which calls self.machine.wait_reboot() 
the thing in which I'm confused is **timeout_sec** parameter please help me out in this

**Comment by jelly** [comment]
> > Sure, there are no pre-assigned issues so please try to setup a Cockpit development environment and ask any questions if they come up.
> 
> what exactly I have to do is extend the **MachineCase** class and add two functions **reboot** which calls self.machine.reboot(). and **wait_reboot** which calls self.machine.wait_reboot() the thing in which I'm confused is **timeout_sec** parameter please help me out in this

The new function should accept a `timeout_sec` parameter and pass it through.

**Comment by mrdetective** [comment]
Is it necessary to create a new subclass that inherits from the "MachineChase" class in order to make changes, or can modifications be made directly to the "MachineChase" class?

**Comment by Deeppjp116** [comment]
Hello,

I'm Deep. I'm interested in working on this issue. Could you please explain the problem and guide me on setting up the repository on my computer? I'm eager to contribute and give my best effort to resolve this. This will be my first valuable contribution. Thank you for giving me this opportunity.

**Comment by martinpitt** [comment]
Hello @Deeppjp116 thanks for your interest! Please see https://github.com/cockpit-project/cockpit/blob/main/HACKING.md for how to set yourself up for Cockpit development.

**Comment by Deeppjp116** [comment]
ok thanks

**Comment by Deeppjp116** [comment]
I am currently using a Windows operating system. Is there anything specific you would like assistance with regarding Windows setup?

**Comment by martinpitt** [comment]
@Deeppjp116 I'm afraid I can't. We've heard reports that it is possible to build and run Cockpit on WSL, but nobody in the team has personal experience with it. I recommend to install a Linux distribution into WSL (Ubuntu 22.04 is a popular choice,  and Fedora hopefully also works), and then just follow HACKING.md.

**Comment by Deeppjp116** [comment]
Thanks for the suggestion. I'll give it a try by installing a Linux distribution into WSL and following the instructions in HACKING.md.

**Comment by Harshalvk** [comment]
Hello @martinpitt ,

I hope this message finds you well. My name is Harshal, and  I've recently come across issue #18644 , titled "testlib: add MachineCase.reboot and MachineCase.wait_reboot functions which allows restart messages," and I'm eager to take on the challenge and contribute to its resolution. This will be my first valuable contribution. Thank you for giving me this opportunity.

**Comment by subhoghoshX** [comment]
Hey @Harshalvk, thanks for the interest. There's already a draft PR #18897 working on the issue. Please, choose another one from the [good first issues](https://github.com/cockpit-project/cockpit/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-issue).

You may also want to set up a local development environment first, please follow https://github.com/cockpit-project/cockpit/blob/main/HACKING.md. Feel free to ask in [Matrix](https://matrix.to/#/#cockpit:fedoraproject.org) if you get stuck.

**Comment by subhoghoshX** [comment]
Hey @Harshalvk, thanks for the interest. There's already a draft PR #18897 working on the issue. Please, choose another one from the [good first issues](https://github.com/cockpit-project/cockpit/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-issue).

You may also want to set up a local development environment first, please follow https://github.com/cockpit-project/cockpit/blob/main/HACKING.md. Feel free to ask in [Matrix](https://matrix.to/#/#cockpit:fedoraproject.org) if you get stuck.

**Comment by mantosh-mariner** [comment]
Hi, I would like to work on this issue. Could you assign it to me?

**Comment by martinpitt** [comment]
@mantosh-mariner I just sent #18897 to fix this, so too late for this one. But if you want to help out, that's still greatly appreciated! We have lots of other good-first-issue things to work on. Thanks!

**Comment by mantosh-mariner** [comment]
> @mantosh-mariner I just sent #18897 to fix this, so too late for this one. But if you want to help out, that's still greatly appreciated! We have lots of other good-first-issue things to work on. Thanks!

yeah! sure you can assign , i am ready to solve other good-first-issue
