### ISSUE TITLE
Up to date backports for bionic and xenial ?

### ISSUE THREAD

**Issue by ardabeyazoglu** [cockpit-project/cockpit#18421]
Currently, ubuntu 18.04 bionic backport is 215 which is too old and for 20.04 it is 264, still quite old. Is there any plan to update them anytime soon ? Most ubuntu servers are still on 18.04 and 20.04 lts if not even older.

**Comment by martinpitt** [comment]
No, we don't support these old Ubuntu releases in current cockpit versions any more, it's too much work for too little benefit. People who run such old releases usually *don't* want things to change unnecessarily.
