### ISSUE TITLE
Cockpit on Debian 11 doesn't list available Applications

### ISSUE THREAD

**Issue by briansmith0** [cockpit-project/cockpit#18439]
### Explain what happens

1.  Install Debian 11
2.  Install and enable Cockpit (apt-get install cockpit) (this also occurs with Cockpit from backports)
3.  Go to the "Applications" page in Cockpit
4.  Only currently installed applications are listed on the Applications page
5.  Currently uninstalled applications, such as cockpit-podman, cockpit-machines, etc. are not listed as installable

### Version of Cockpit

239 and 285 (backports)

### Where is the problem in Cockpit?

Applications

### Server operating system

Debian

### Server operating system version

11

**Comment by marusak** [comment]
Duplicate of https://github.com/cockpit-project/cockpit/issues/17737 ?

**Comment by briansmith0** [comment]
Yes, this is a duplicate of that.
