### ISSUE TITLE
hacking: Improve Debian/Ubuntu development docs

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#18459]
In the HACKING document, Debian and Ubuntu are mentioned for installing nodejs. However, the rest of the document is Fedora-specific.

We probably want to fix this.

I've seen that at least a few GSOC participants have been running into problems.

**Comment by Alcadeus0** [comment]
Can i take up this issue :)

**Comment by jelly** [comment]
Feel free!

**Comment by garrett** [comment]
Note: The HACKING file is in the main repo, but it's regularly mirrored into the website. So edit the original file in the repo; don't worry about the version on the website.

https://github.com/cockpit-project/cockpit/blob/main/HACKING.md

**Comment by martinpitt** [comment]
The current [HACKING](https://github.com/cockpit-project/cockpit/blob/main/HACKING.md) recommends using the cockpit/tasks container in toolbox, instead of installing development dependencies directly on your machine. This works on all distributions, is easier, cleaner, and more reliable.
