### ISSUE TITLE
Installation progress looks strange in the apps page

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#18463]
### Explain what happens

The percentage should be next to the number (61) and maybe the progress bar should be bigger?

![image](https://user-images.githubusercontent.com/67428/223475014-7fe3bb96-03d0-48fd-b113-30826fb46456.png)

@garrett just for verification, how should it exactly look like?

Update: 
Discussion led to https://github.com/cockpit-project/cockpit/issues/18463#issuecomment-1459789817
The progress bar text should be put on the left of the bar, the bar should have inline style and limited width.

**Comment by garrett** [comment]
Is it ever cancellable? If not, then we shouldn't show that action. And it should be a secondary button, not a link, if you can cancel it at some point (and a disabled button if it is supposed to be possible at some human-clickable point in time). So a disabled button should still look like a button.

I don't think it's realistically cancelable though. I suppose when it's downloading before installing... but that's such a small window of time, especially on a server. We're talking about downloading several megabytes at most. Which, in these days, on a server, is really absurdly quick. Meaning that it would be possible to cancel the download for maybe quarter of a second? Nobody's that fast to click the button, unless they're Superman or they had their mouse cursor over the area. As that's where the install button would've been, I think, then that brings up another problem of someone accidentally clicking the same area twice. (It's an accessibility problem, especially for some people. But everyone can accidentally double click.) So I think canceling is useless and could even be a misfeature here. It's probably better to remove it and rely on the remove button?

Otherwise, it's basically supposed to be a progress bar. And the percentage should be a fixed width with tabular numbers, else it'll make the bar bounce around.

So, kinda like this:

![progress](https://user-images.githubusercontent.com/10246/223480367-25c77e5b-a42f-4e49-9c7a-d4d843a7243a.png)

**Comment by jelly** [comment]
Oh, for me the install process takes quite a while on a VM. I haven't tested cancellation, will have to see if that's broken or not.

**Comment by jelly** [comment]
This also looks.. not 100% aligned:

![Screenshot from 2023-03-07 17-59-34](https://user-images.githubusercontent.com/67428/223494266-05567fa4-dcf6-4630-8917-271716db7063.png)

**Comment by jelly** [comment]
Re-trying today and it all seems to work...

![image](https://user-images.githubusercontent.com/67428/223662122-fda44794-3e5b-49ad-b048-13a60f0548de.png)

**Comment by garrett** [comment]
The original mockups from 2017 (in PF3 style... they're old) made by Andreas have progress bars mocked up:

https://github.com/cockpit-project/cockpit-design/blob/main/server-apps/server-apps.png

Although I think the progress bars are quite long there too. They'd be better to be constrained and right aligned next to the action. But even still, they're OK.

![image](https://user-images.githubusercontent.com/10246/223665815-5269c27a-78b7-47eb-8cb6-0b0df13402b8.png)

![image](https://user-images.githubusercontent.com/10246/223666106-3eb30778-489d-4d31-9418-0d60b65660d6.png)

(This second one, on the details page, has a bar that is shorter than full width. I think it should probably be even a bit shorter though. But if the text needs to go away, I can understand the hesitance on making it too short and filling the area. There's probably a happy medium.)

Here's a mod that shows it smaller:

![image](https://user-images.githubusercontent.com/10246/223667126-5104ad23-d86d-4034-ba79-e1849503819c.png)

The "issue" is that there's a bunch of blank area where the description was.

A more correct approach would probably be to truncate the text and show the installation like this (excuse the wrong fonts and sloppiness — this is an quick mod on an old design which uses old fonts and old style):

![image](https://user-images.githubusercontent.com/10246/223668550-d288f9f0-9434-4777-80af-7bcbea99a1c4.png)

**Comment by garrett** [comment]
Left aligning is another approach to a smaller bar. The question is if the installation action and the cancel are too far apart:

![image](https://user-images.githubusercontent.com/10246/223668887-25df5458-ad4c-44cf-8370-be1915c911bc.png)

I guess this could work. It's probably OK. It gets around the blank feeling of the right aligned without text, at least. The divider lines and horizontal are probably fine enough to connect the installing and cancel?

It's all a balance.

**Comment by garrett** [comment]
So, looking at it all, I guess the constrained left aligned one is probably best. The stretched one does work too, but it's just absurdly long. But it does also connect the action to the progress, which is good.

Regardless, the alignment should be correct (it's actually off a little in the mockups — these ones were never pixel perfect, and now they're visually dated) and the height should be the inline variant.

**Comment by AdarshRawat1** [comment]
Can I work on this bug?

**Comment by KKoukiou** [comment]
> Can I work on this bug?

Sure if you think you can, just try, no need to ask.

**Comment by ahmedr2001** [comment]
I was trying to reproduce this issue, but there is a problem: The application page only displays a Storage application which when I click on says `Cockpit version 265 required`. When setting up cockpit I was told to install using backports, which I did, but I got version 264. Is there a way to upgrade it or do I have to redo the process?

**Comment by jelly** [comment]
Try to also install cockpit-packagekit from backports

**Comment by Suraj-Dhankad2025** [comment]
Is anyone working on this issue ?
As i have understood it I want to contribute to this issue

**Comment by AdarshRawat1** [comment]
@Suraj-Dhankad2025 I'm trying to, but you can work on it. 
I think @ahmedr2001 is also working on it.

**Comment by Suraj-Dhankad2025** [comment]
Can i install it on macOS

**Comment by neeraj542** [comment]
Hello there,

I've been following this issue and would love to contribute to the Cockpit project by helping to resolve it.

After reading through the discussion, I believe that the best approach to fixing this issue would be to add a new option in the cockpit-ws service configuration file that allows users to specify a custom port range. This would give users more flexibility and control over which port ranges are used by Cockpit.

I have experience working with systemd and have contributed to several open-source projects in the past, including [insert project name here]. I would be happy to take on this issue and work towards a solution.

Please let me know if there is anything else I can do to help or if you have any suggestions on how to approach this problem.

Thank you for your time and consideration.

Best regards,
Neeraj Meena

**Comment by KKoukiou** [comment]
> Hello there,
> 
> I've been following this issue and would love to contribute to the Cockpit project by helping to resolve it.
> 
> After reading through the discussion, I believe that the best approach to fixing this issue would be to add a new option in the cockpit-ws service configuration file that allows users to specify a custom port range. This would give users more flexibility and control over which port ranges are used by Cockpit.
> 
> I have experience working with systemd and have contributed to several open-source projects in the past, including [insert project name here]. I would be happy to take on this issue and work towards a solution.
> 
> Please let me know if there is anything else I can do to help or if you have any suggestions on how to approach this problem.
> 
> Thank you for your time and consideration.
> 
> Best regards, Neeraj Meena

Hi @neeraj542 please this comment and especially the suggestion on how to fix this  are quite out of place. There are also many people already active on this so maybe you want to pick something else.

**Comment by KKoukiou** [comment]
> Can i install it on macOS

No, also https://github.com/cockpit-project/cockpit/wiki/GSoC-2023-topics#extra-requirements-for-applicants

**Comment by neeraj542** [comment]
> > Hello there,
> > I've been following this issue and would love to contribute to the Cockpit project by helping to resolve it.
> > After reading through the discussion, I believe that the best approach to fixing this issue would be to add a new option in the cockpit-ws service configuration file that allows users to specify a custom port range. This would give users more flexibility and control over which port ranges are used by Cockpit.
> > I have experience working with systemd and have contributed to several open-source projects in the past, including [insert project name here]. I would be happy to take on this issue and work towards a solution.
> > Please let me know if there is anything else I can do to help or if you have any suggestions on how to approach this problem.
> > Thank you for your time and consideration.
> > Best regards, Neeraj Meena
> 
> Hi @neeraj542 please this comment and especially the suggestion on how to fix this are quite out of place. There are also many people already active on this so maybe you want to pick something else.

Thank you for bringing this to my attention and for your valuable input. I appreciate your insights and would be grateful if you could suggest any other areas that may require attention. Your guidance would be much appreciated. Thank you

**Comment by KKoukiou** [comment]
@neeraj542 please contact me through IRC, https://github.com/cockpit-project/cockpit/wiki/GSoC-2023-topics#contact as this is not the right place for this conversation.

**Comment by neeraj542** [comment]
> @neeraj542 please contact me through IRC, https://github.com/cockpit-project/cockpit/wiki/GSoC-2023-topics#contact as this is not the right place for this conversation.

Hello @KKoukiou ,

Thank you for your message. I understand that this may not be the right platform for our conversation. I'm interested in discussing the GSoC'23 project and would like to contact you through IRC as you have suggested. I've visited the link you provided (https://github.com/cockpit-project/cockpit/wiki/GSoC-2023-topics#contact) and will follow the instructions to reach out to you.

Thank you for your time and consideration. I look forward to connecting with you on IRC.

Best regards,
Neeraj

**Comment by neeraj542** [comment]
Hi @KKoukiou, On this chat page I am not able to connect with you, would you like to help me

**Comment by ahmedr2001** [comment]
> The code is in `pkg/apps`, to be specific `pkg/apps/application-list.jsx`.

I'm working with ./build.js -w to watch my changes to the source files, but I want to watch my changes on certain components in the node_modules folder (Progress and ProgressContainer specifically). How do I do that?

**Comment by martinpitt** [comment]
@ahmedr2001 : Please don't ever edit files in node_modules/. If you do for experimentation, watch mode does not cover this, so you'll have to rebuild completely. But be aware that as soon as package.json or package-lock.json changes, build.js will checkout node_modules/ from git again, which will overwrite your changes.

**Comment by KKoukiou** [comment]
@siddhant99m there is already an open PR for this.
