### ISSUE TITLE
Services: Clean up URL/filter state handling

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#18465]
[TestPages.testBasic](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18422-20230307-120556-7e7cb6b6-centos-8-stream-pybridge/log.html#302-2) failure is pretty much the last Services page related flake. Once again this is filter/URL options state handling confusing/race condition. This is unrelated to #18422 (where this isssue is broken out from), but now we have a debug log.

We start at the Services page detail:

> debug: XXX ServicesPageBody render path ["test.service"] rendering service details for test.service
> log: XXX cockpit.location.get; window.location.hash "#/test.service" unchanged last_loc

Then the test switches to the /network page:

> -> ph_go("/network")
> <- {'type': 'undefined'}
> log: XXX cockpit.location.get; window.location.hash "#/test.service" unchanged last_loc
> log: XXX cockpit.location.get; window.location.hash "" creating new last_loc
> <- {'type': 'undefined'}

Then switches back to Services:

> -> ph_go("/system/services")
> log: XXX cockpit.location.get; window.location.hash "" unchanged last_loc
> log: XXX cockpit.location.get; window.location.hash "#/" creating new last_loc
> <- {'type': 'undefined'}

... and at that point forgot its previous location. Apparently we expect pages to remember their state/URL options internally, as opposed to treating the URL (aka cockpit.location) as *the* single source of truth. @mvollmer so I suppose that is the reason why we have this duplication of state and URL change listeners?

_Originally posted by @martinpitt in https://github.com/cockpit-project/cockpit/issues/18422#issuecomment-1458223393_

**Comment by mvollmer** [comment]
> Apparently we expect pages to remember their state/URL options internally, as opposed to treating the URL (aka cockpit.location) as *_the_ single source of truth.

No, I don't think this is true.  The URL that a page sees comes from an iframe attribute ("src"?), and that shouldn't change when the shell switches between iframes (which only changes their visibility).  The shell has code to change the main browser URL during navigation to reflect the current iframe, and that code is a bit on the complex side, so I wouldn't be surprised if something goes wrong there.

**Comment by martinpitt** [comment]
@mvollmer : Indeed, you are right. In fact I think it's even the opposite -- the TestPages test logs in again, which I believe should destroy and restart the pages and their state -- to the state *is* kept in the URL.

**Comment by martinpitt** [comment]
[This](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18501-20230314-174040-08af671e-rhel-8-8/log.html#343) is a very common flake these days (probably the #1 Services page flake now), which seems related.

**Comment by martinpitt** [comment]
Probably same root cause: https://cockpit-logs.us-east-1.linodeobjects.com/pull-4659-20230417-054534-ff6394ed-rhel4edge-cockpit-project-cockpit/log.html#125-2
