### ISSUE TITLE
Move away from accountsservice

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1853]
We should be able to manage local accounts without accountsservice:

 * It doesn't let us manage the root account
 * It doesn't do password strength correctly
 * It doesn't let us manage groups
 * We currently use cockpitd legacy wrapper code, and we should get away from this.

Instead we really can use shadow-utils directly.

 * Read and watch ```/etc/passwd``` using cockpit.file() API
 * Read and watch ```/etc/group``` using the cockpit.file() API
 * Use ```passwd``` to set user passwords
 * Use ```useradd``` to add new users
 * Use ```usermod``` to modify groups (Roles)
 * Use ```usermod --coment``` to modify full name
 * Use ```usermod --lock``` to lock an account
 * Use ```usermod --unlock``` to unlock an account
 * Use ```newusers``` to sync users when adding a server to the dashboard

**Comment by stefwalter** [comment]
No accountsservice in Atomic. #1679

**Comment by stefwalter** [comment]
Although it's not a DBus API, I think the shadow-utils and the two file formats involved are stable and solid enough to build a UI on top of.

In addition, local user account management is not a core feature of Cockpit. In real deployments, peolpe will use IPA or another domain to manage users. So that makes me more confident in implementing this with shadow-utils.

**Comment by stefwalter** [comment]
Note that we never modify the file formats, we rely on tools to do this. We consume the format directly though. It's stable and well documented.

**Comment by stefwalter** [comment]
The feature that we do lose is user avatars. However these are not typically used on servers, and not used anywhere in cockpit either. @andreasn are you okay with dropping the local user avatar feature?

**Comment by stefwalter** [comment]
Did this research last week on the train.

**Comment by fridex** [comment]
Just to be sure... It is planned to move from cockpitd (drop accountsservice calls) and directly spawn shadow-util binary using cockpit.spawn(), isn't it?

**Comment by jscotka** [comment]
Is possible to use command:
 $ getent passwd
It works with all aviable locally configured user databases.

**Comment by stefwalter** [comment]
This cockpit feature is *only* about local users. So that's why ```getent``` is not relevant or necessary here.

**Comment by stefwalter** [comment]
> Just to be sure... It is planned to move from cockpitd (drop accountsservice calls) and directly spawn shadow-util binary using cockpit.spawn(), isn't it?

Yes, that's right. In addition use cockpit.file() to watch and read the relevant files.

One exception, the 'newuser' stuff noted above would go into the Cockpit ```remotectl``` command, and not be invoked directly from javascript.

**Comment by fridex** [comment]
> * Use passwd to set user passwords

This is a little bit tricky on some systems - passwd does not read from stdin by default (e.g. Fedora). It accepts --stdin option but only for root, thus it would be not possible to change password by non-root user. Is this restriction OK?

**Comment by stefwalter** [comment]
> This is a little bit tricky on some systems - passwd does not read from stdin by default (e.g. Fedora). It accepts --stdin option but only for root, thus it would be not possible to change password by non-root user. Is this restriction OK?

Hmmm, good catch. No this is not ok that only root can change passwords, it would be a regression. We need users to be able to change their own passwords.

Should we depend on 'expect' and use it to drive the passwd command? I imagine having such a tool as a dependency would be useful elsewhere in Cockpit too. Here's an example of using expect with passwd:

http://code.seanodonnell.com/?id=21

Obviously we would need to:

 * Execute passwd in ```LC_ALL=C``` so that locale matches
 * Include the password in the expect script itself (and not on the command line)
 * And pass the expect script to expect via stdin.

It's worth noting that handling pam_cracklib password strength checking during the passwd PAM conversation phase is a really lousy user experience for a UI to have. We really want to drive cracklib while the user is typing the password and provide immediate feedback in the dialog. But that's a separate issue.

**Comment by stefwalter** [comment]
Some more notes. Only the following users are listed:

 * root, ie: uid=0
 * Users above 1000 with a valid shell

The way to tell locked user accounts is as follows.

 * ```cockpit.spawn(["sed", "-n", "s/\([^:]\+\):!.*/\1/p", "/etc/shadow"], { superuser: true }) ...```
 * Only someone with superuser privileges (usually anyone in wheel) can get the list of locked/unlocked users. Anyone else will not see that information. This is acceptable, IMO.
 * Note that, even though we could retrieve the entire contents of ```/etc/shadow``` we make sure not to.

**Comment by andreasn** [comment]
> The feature that we do lose is user avatars. However these are not typically used on servers, and not used anywhere in cockpit either. @andreasn are you okay with dropping the local user avatar feature?

Sure, if that's the only thing we lose.

**Comment by andreasn** [comment]
Will stuff still be "realtime"? Like if I do useradd from the CLI, will it be reflected instantly in Cockpit?

**Comment by stefwalter** [comment]
> Will stuff still be "realtime"? Like if I do useradd from the CLI, will it be reflected instantly in Cockpit?

Yes.

**Comment by stefwalter** [comment]
This should fix: https://bugzilla.redhat.com/show_bug.cgi?id=1174984

**Comment by stefwalter** [comment]
Should also fix: https://bugzilla.redhat.com/show_bug.cgi?id=1161750

**Comment by stefwalter** [comment]
Should also fix: https://bugzilla.redhat.com/show_bug.cgi?id=1142234
