### ISSUE TITLE
cockpit: LoginTo=false does not prevent connections to remote hosts

### ISSUE THREAD

**Issue by thoger** [cockpit-project/cockpit#18540]
### Explain what happens

In issue #17340, the [WebService > LoginTo](https://cockpit-project.org/guide/latest/cockpit.conf.5.html) option was pointed out as a way to disable the "Other Options > Connect to" option on the Cockpit login screen.  In the man page, that option is documented as:

> When set to true the Connect to option on the login screen is visible and allows logging into another server. If this option is not specified then it will be automatically detected based on whether the cockpit-ssh process is available or not.

That documentation is not explicit what is the expected behaviour in case of LoginTo=false - whether it's only supposed to hide the option, or actually also prevent logging to remote hosts.  The latter is likely to be assumed.  However, the option only hides the input field on the login screen without preventing remote logins.

To test, set the following in the cockpit.conf:

```
[WebService]
LoginTo=false
```

Restart the service and visit the login page.  See that the "Connect to" option is not shown.  Change the URL of the page to append `/=other.host.or.ip`.  I.e the URL as:

https://cockpit.example.com:9090/

is changed to:

https://cockpit.example.com:9090/=otherhost.example.com/

or

https://cockpit.example.com:9090/=10.0.0.10/

See that after loading such changed URL, the login page now indicates the remote host as the "Server".  Providing correct authentication credentials for the remote hosts opens a session on that remote host.

### Version of Cockpit

Tested with RHEL packaged Cockpit 276.1

### Where is the problem in Cockpit?

None

### Server operating system

None

**Comment by martinpitt** [comment]
Thanks for the report! I'll look at this.

**Comment by JaneX8** [comment]
Is this fixed? Because it seems like a serious security bypass. `LoginTo = false` should disable the entire feature, not just hide the input box.

**Comment by jelly** [comment]
> Is this fixed? Because it seems like a serious security bypass. `LoginTo = false` should disable the entire feature, not just hide the input box.

See https://github.com/cockpit-project/cockpit/commit/29500b32c66dff16ec4aabf119a5772f007a007e this also disallows direct logins:

> If cockpit-ws is exposed to the public internet, and also has access to a private internal network, it is recommended to explicitly set LoginTo=false. This prevents unauthenticated remote attackers from scanning the internal network for existing machines and open ports.
