### ISSUE TITLE
Debian bullseye missing all tools except terminal

### ISSUE THREAD

**Issue by campbellhennessy** [cockpit-project/cockpit#18547]
### Explain what happens
Sorry if this is a simple user error, I searched around a fair amount and couldn't seem to find any examples where tools like Applications did not appear by default.

1.  I installed cockpit on debian bullseye using the instructions linked in the Readme
2. Current version of cockpit running on my server is 286-1~bpoll+1
3. The tools section of cockpit only shows the Terminal tool, there is no Applications option.  Please see screenshot:
![image](https://user-images.githubusercontent.com/4094269/226940298-8c74ebc3-f6d6-4baa-b066-a14a73896623.png)

### Version of Cockpit

286-1~bpo11+1

### Where is the problem in Cockpit?

Applications

### Server operating system

Debian

### Server operating system version

11 bullseye

### What browsers are you using?

Chrome

### System log

```shell
Mar 22 14:39:06  systemd[1]: Starting Cockpit Web Service...
Mar 22 14:39:06  systemd[1]: Started Cockpit Web Service.
Mar 22 14:40:37  systemd[1]: cockpit.service: Succeeded.
```

**Comment by KKoukiou** [comment]
Applications page is part of this package https://packages.debian.org/bullseye/cockpit-packagekit

**Comment by campbellhennessy** [comment]
Thank you that was what I was missing
