### ISSUE TITLE
Software updates: Output when failing to load updates come in a single line

### ISSUE THREAD

**Issue by tripathics** [cockpit-project/cockpit#18581]
## Steps to reproduce
1. Disconnect the system from the internet (I used mobile hotspot with mobile data turned off)
2. Open cockpit web console on your linux machine and login to your local computer
3. Go to software updates to see that each line of the output joined or concatenated in a single line.

## Screenshots

![Screenshot from 2023-03-29 20-38-48](https://user-images.githubusercontent.com/68462214/228627189-60de8bdd-a1ad-4eb0-8604-a83368c5970f.png)

![image](https://user-images.githubusercontent.com/68462214/228626125-819613d1-6398-457b-8b27-a416e40821a5.png)

## Implementation

- [X] I am interested in solving this issue

### Version of Cockpit

287-1~bpo22.10.1

### Where is the problem in Cockpit?

Software updates

### Server operating system

Ubuntu

### Server operating system version

22.10

### What browsers are you using?

Chrome, Edge

**Comment by martinpitt** [comment]
Thanks for reporting! Indeed it makes sense to show these error messages in a `<CodeBlockCode>`. We already do this for kdump, realmd, and sosreport error messages. That's indeed a nice good-first-issue, labelling.

**Comment by usyntest** [comment]
I was trying to solve this issue and used `<CodeBlockCode>` instead of `<span>`, which was used before. Do you think this should look like this?
![image](https://user-images.githubusercontent.com/68940203/229052758-cce35b21-f178-48af-a278-5e195a1ad60b.png)

**Comment by martinpitt** [comment]
This is already an improvement. I think it would look even better left-aligned instead of centered, but I figure that's a bonus. :grin:

**Comment by tripathics** [comment]
@martinpitt I have followed the design of `<ApplyUpdates/>` component to include an `Expandable` for showing the logs. I have also moved the "Please reload the page..." paragraph before the logs. Is is fine?

![image](https://user-images.githubusercontent.com/68462214/229252063-0386cd7d-c10a-45d5-ac0a-004f08453520.png)

**Comment by tripathics** [comment]
Kindly review my PR
