### ISSUE TITLE
Software Updates: integrate new "reboot" configuration option from dnf-automatic

### ISSUE THREAD

**Issue by ishimko** [cockpit-project/cockpit#18593]
Page: Software Updates

Currently automatic reboot after installing updates is achieved by a custom script, which **does** check whether something was installed or not via searching for a `===========` sequence:

https://github.com/cockpit-project/cockpit/blob/07e5edf1470251e48d8d15d231e1386a3a71f4c2/pkg/packagekit/autoupdates.jsx#L183-L190

[The bug](https://bugzilla.redhat.com/show_bug.cgi?id=1491190) mentioned in a code comment mentions that a new option `reboot` was added to `automatic.conf`: https://github.com/rpm-software-management/dnf/pull/1879, which can be used instead (`when-changed` flag gives this behavior).

**Comment by ishimko** [comment]
Hi @omarY23, apologize for my mistake, you're right. I was almost sure I experienced reboot without any updates being installed, but now I am checking logs and see that there were updates, so this `=======` magic line was used like a marker.

However I still believe it could be beneficial to switch to the new documented option, even though current solution seems to provide the same behavior. For instance there could be a UI dropdown list which allows selecting from `when-changed`/`when-needed`/`never` as per new option in dnf-automatic.

I am good closing this issue as it is not accurate with it's current wording.

**Comment by jelly** [comment]
> Hi @omarY23, apologize for my mistake, you're right. I was almost sure I experienced reboot without any updates being installed, but now I am checking logs and see that there were updates, so this `=======` magic line was used like a marker.
> 
> However I still believe it could be beneficial to switch to the new documented option, even though current solution seems to provide the same behavior. For instance there could be a UI dropdown list which allows selecting from `when-changed`/`when-needed`/`never` as per new option in dnf-automatic.

Using the standard provided mechanism is much preferred, as this feature is relatively new we'd need to handle old and new dnf.

**Comment by martinpitt** [comment]
This was done in PR #19648
