### ISSUE TITLE
Define components in manifest.json files

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1859]
Instead of just tools, we need a way to define components in a flexible manner:

 * Main menu components
 * Tools
 * Dashboards

**Comment by stefwalter** [comment]
Some ideas discussed with @mvollmer 

```

{
	"version": 0,

	"menu": [
		{
			"path": "server/host"
			"label": "System"
			"order": 0,
			"group": "symbolic-name",
		},
		{
			...
			"order": 1,
			"group": "symbolic-name",
		},
	]
}

{
	"version": 0,

	"tools": [
		{
			"path": "users/local"
			"label": "Administrator Accounts"
		}
	]
}


{
	"version": 0,

	"dashboard": [
		{
			"path": "kubernetes/dashboard"
			"label": "Cluster"
		}
	]
}
```

**Comment by stefwalter** [comment]
@mvollmer Is it okay if I leave out the ```symbolic-name``` grouping stuff for now, until we have a solid use case?

**Comment by mvollmer** [comment]
> Is it okay if I leave out the group grouping stuff (above) for now, until we have a solid use case?

Of course, that was just a brainstorm.
