### ISSUE TITLE
Kubernetes: trouble with "localhost" vs "127.0.0.1"

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#1860]
By default, the kube-apiserver seems to listen on 127.0.0.1, and cockpit-bridge connects to "localhost".  For some reason, cockpit-bridge seems to prefer to resolve "localhost" to ::1 instead of 127.0.0.1 and the connection fails.

If I remove the `::1 localhost ...` line from `/etc/hosts`, everything starts to work as expected.

**Comment by mvollmer** [comment]
(I have not verified that cockpit-bridge really connects to ::1, that's just an assumption.)

**Comment by stefwalter** [comment]
Hmmm, this is also an issue with travis. I wonder if we should see how we can connect to both.

**Comment by stefwalter** [comment]
@sub-mod FYI

**Comment by stefwalter** [comment]
This really needs to be fixed in a better way, by using 'kubectl exec':

https://trello.com/c/VCLg2DWK/153-kubernetes-use-kubectl-exec-to-connect-to-containers

**Comment by stefwalter** [comment]
fixed.
