### ISSUE TITLE
Software updates still failing after switching my renderer from networkd to networkmanager

### ISSUE THREAD

**Issue by Toniassaker** [cockpit-project/cockpit#18620]
### Explain what happens

[](url)It all started when my website gave me this error: this website is facing a critical error,
So I started searching in my website Ubuntu cockpit, and found that I had tons of updates undone,
While wanting to do them, I got the notice: loading available updates failed and that cannot refresh cash whilst offline,
So I searched for it online and learned how to switch from networked to NetworkManager,
After doing that, and this is my proof down here

![tempsnip](https://user-images.githubusercontent.com/130477211/231195129-1241ff1e-b6db-4ecb-ba06-7358177c63e4.png)

So I went to try and update them,
And the issue persisted
![image](https://user-images.githubusercontent.com/130477211/231195786-48d1dcd8-457b-4ad7-a0ce-4ec9dd20cb32.png)

And even I have a network that no matter what I do, it won't start
![image](https://user-images.githubusercontent.com/130477211/231196691-1cd0727c-e251-4e34-bd79-b46d21876476.png)

So plz if anyone has any close idea of what must be done, plz tell me,
cause its been 2 weeks that my website is facing these issues and I am having more than enough,
thanks in advance

### Version of Cockpit

215

### Where is the problem in Cockpit?

Software updates

### Server operating system

Ubuntu

### What browsers are you using?

Edge

**Comment by KKoukiou** [comment]
A workaround for this is described here https://cockpit-project.org/faq.html#error-message-about-being-offline

A lengthy discussion exists on https://github.com/cockpit-project/cockpit/issues/8477

Closing as a known issue, which is not on cockpit side to solve.
