### ISSUE TITLE
Terminal context menu isn't dark themed

### ISSUE THREAD

**Issue by LunarTwilight** [cockpit-project/cockpit#18621]
### Explain what happens

1. Open cockpit
2. Go to the terminal
3. Right click
![chrome_zfhEFLEFgi](https://user-images.githubusercontent.com/13520392/231246996-3762bdbe-ea4f-4c45-926c-deb6cc864221.png)

### Version of Cockpit

287-1~bpo22.04.1

### Where is the problem in Cockpit?

Terminal

### Server operating system

Ubuntu

### Server operating system version

22.04.2 LTS

### What browsers are you using?

Chrome

**Comment by LunarTwilight** [comment]
can also reproduce on cockpit `286-1~bpo11+1` running on "Debian GNU/Linux 11 (bullseye)"

**Comment by MahmoudHamdy02** [comment]
Looks like adding a `color: black` to `contextMenuOption` in `context-menu.css` fixes this problem. I'm not sure if this is as simple as it looks though. @garrett what do you think?
