### ISSUE TITLE
storage: Formatting "No filesystem" shows "Format and mount" button

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#18623]
Like this:

![image](https://user-images.githubusercontent.com/3228183/231397619-d2f8d0d7-4b4c-4470-8318-d6c921e716d4.png)

"Mounting" makes no sense when just wiping a device.

(Clicking either button works and correctly wipes the device without attempting to mount it. It's just confusing to have them both.)

**Comment by MahmoudHamdy02** [comment]
So it should only be 1 primary button that says "Format", correct?

**Comment by KKoukiou** [comment]
> So it should only be 1 primary button that says "Format", correct?

Correct just for the case where 'NO filesystem' is selected.
