### ISSUE TITLE
Dark theme will not apply in firefox for login page

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#18652]
### Explain what happens

If you check dist/login.css you can notice that it contains nested CSS rules, which actually firefox can parse.
Normally the bundler should transpile the css into something firefox could read, and it actually does it for other pages.

Pixel tests actually verify this problem.

### Version of Cockpit

289

### Where is the problem in Cockpit?

None

### Server operating system

None

**Comment by Ragavendaran** [comment]
Can confirm the Tagged Version 287 of cockpit can produce dark login screen (with the `shell:style` set to 'auto' or 'dark')

I was trying to test Main branch cockpit with Firefox and got always light theme regardless of the theme setting

**Comment by Ragavendaran** [comment]
It seems like the nested CSS is not flattened after moving the front end build tool from webpack to esbuild https://github.com/cockpit-project/cockpit/commit/fe89f2eff580970bac4a142dceeb4f8e6d16a19e

This was the comparison between the dist/login.css between that commit https://github.com/cockpit-project/cockpit/commit/fe89f2eff580970bac4a142dceeb4f8e6d16a19e and its previous commit https://github.com/cockpit-project/cockpit/commit/a06d1e8ae6df57a1403b9467582b4079e688a171
![image](https://user-images.githubusercontent.com/39620234/233201408-ebaa3545-08f5-4f02-b8c2-c1ca1279f0c6.png)

Flattening it in the source login.css seems to be a hacky fix, opening a draft PR
