### ISSUE TITLE
No "languages found" text is shown when languages are not found in the language modal

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#18680]
### Explain what happens

We should probably show an EmptyState with an EmptyText which explains that no languages are found.

![image](https://user-images.githubusercontent.com/67428/233420151-75515fed-e7da-41de-afc2-da8bca174004.png)

### Where is the problem in Cockpit?

None

### Server operating system

None

**Comment by abhishekkhanna2710** [comment]
I want to work on this isssue. Please assign me this?

**Comment by jelly** [comment]
> I want to work on this isssue. Please assign me this?

We don't assign issues, please try to work on it and make a PR if possible.
