### ISSUE TITLE
Slide up tools menu

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1868]
In the new navigation design, tools should be in a slide up tools menu. Tools are components you don't use very often, and shouldn't be always visible in the sidebar.

**Comment by stefwalter** [comment]
We could use some elements of the sliders seen here: https://www.patternfly.org/wp-content/uploads/patternfly/tests/form.html

**Comment by dperpeet** [comment]
depends on #788 to avoid redundant work
