### ISSUE TITLE
288.1  Software Updates Status always reports reboot required

### ISSUE THREAD

**Issue by KeithSBB** [cockpit-project/cockpit#18693]
### Explain what happens

1. Cockpit software updates Status refresh
2. Reports; 1 package needs a system reboot
3. Terminal; dnf needs-restarting -r
4. Reports: No core libraries or services have been updated since boot-up.
                    Reboot should not be necessary.

### Version of Cockpit

288.1

### Where is the problem in Cockpit?

Software updates

### Server operating system

Fedora

### Server operating system version

38

### What browsers are you using?

Brave

**Comment by KeithSBB** [comment]
After upgrading to Fedora 38 server trace was reporting that the kernel required a reboot.  This was resolved by using grubby to set the default kernel to the latest kernel image.

**Comment by UbuntuRunner** [comment]
We have now narrowed down the cause of the problem when restoring a server. 

The problem does not occur if you restart the server after the first update of the server via the cockpit update plugin. 

If you start the server via the cockpit start page or the terminal, you will encounter the problem of a constant message in cockpit telling you to restart, even though this has been done several times.

Maybe this will help with troubleshooting.
