### ISSUE TITLE
Just installed cockpit on Fedora 37 and no login possible at all

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [cockpit-project/cockpit#18700]
### Explain what happens

went to http://localhost:9090 and https://localhost:9090 and https://myserver.ltd:9090 and login does not work at all for root (yes I removed root on disable-users) or a user with id > 1000.  in the log nothing special but TLS failure and  cockpit-session: authentication timed out. FYI I check the whole internet and this repo about this issue and it seems to be redundant.

### Version of Cockpit

last

**Comment by martinpitt** [comment]
"Timed out" sounds like the authentication actually did succeed, but the cockpit session didn't start properly. Adding a journal and the output of the browser console (Ctrl+Shift+J) would help, as well as a precise description what happens exactly. Please also try this with a private browser window, this helps sometimes to not have any old cookies or site data.

Did this work before for you? Do you have any browser extensions installed which might break this? (Please try another browser, or without extensions)

**Comment by ROBERT-MCDOWELL** [comment]
@martinpitt 
Did this work before for you? 
no, never, I installed it from Fedora Package, followed your install process and stuck since...
I just tried with a private browser (Midori on Linux) and it works!!! how is it possible since there was no cookie the first time I connected to the page with a normal browser?

**Comment by martinpitt** [comment]
I don't know.. As I said, I really need some details. *Something* is special on your system, and we need to find out what.

**Comment by ROBERT-MCDOWELL** [comment]
@martinpitt 
the problem is I have no choice to use Midori which does not have any apparent debug console and I connect to my server from VNC.

**Comment by martinpitt** [comment]
I thought you said it works with Midori. I suppose you originally tried it with Firefox or Chromium? These do have a debug console, and we need the logs from a failing case.

**Comment by ROBERT-MCDOWELL** [comment]
Sorry @martinpitt on my server I cannot install firefox nor chrome, until now I used Midori. I have also Edge for Linux but apparently the last update broke it.
