### ISSUE TITLE
pybridge: ssh/ferny does not recognize changed hostkey

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#18713]
When a remote host key changes, ferny does not recognize that error message, but treats it as "You are connecting to hostname for the first time". Given SSH's usual "trust on first use" security model, this is misleading and potentially dangerous, so I consider this a blocker for rolling out the python bridge.

This breaks TestMultiMachine.testTroubleshooting.

The tests currently expect to pick up the situation of a *changed* host key (as opposed to an unknown one), and offer this:

![image](https://github.com/cockpit-project/cockpit/assets/200109/1a2ee96b-ce8d-431e-a230-7cabf1d6f49b)

 - [x] https://github.co[m/allisonkarlitskaya/ferny/pull/15
 - [x] https://github.com/allisonkarlitskaya/ferny/pull/16

**Comment by martinpitt** [comment]
@croissanne : You also worked on this quite a bit a few years ago -- do you still happen to remember the history? (Please see the previous comment only, the older ones are unrelated for you)

**Comment by martinpitt** [comment]
I laid some groundwork for this in https://github.com/allisonkarlitskaya/ferny/pull/15 .

**Comment by martinpitt** [comment]
I test this fix in https://github.com/cockpit-project/cockpit/pull/18856 to fix invalid-hostkey handling in Cockpit.

**Comment by stefwalter** [comment]
> I am trying to understand the reason behind that `private` special-casing. At first sight this feels quite unrelated to host key checking -- that needs to happen for opening a shared connection as well. Of course we also need to actually fix ferny here -- it needs to ask for a host key when it's needed only.

private channels are fundamentally unrelated to unknown hosts (and the related key handling). Private channels are a general capability in the cockpit routing for a transport to be used by just that one private cockpit channel. 

An example of this is when a specific "user" is specified on a channel for a specific host. It should not then be automatically used by other channels for that host. Thus it should often be private. We used to use this for syncing users between hosts, and other cross host setup.

It appears that the only remaining use of private channels in the cockpit code *is* related to loading and verifying host keys. It thus sets the {{{COCKPIT_SSH_CONNECT_TO_UNKNOWN_HOSTS=true}}} environment variable for a new cockpit-ssh process allowing it to connect to a host that was never connected to before. Normally cockpit-ssh will only (TCP) connect to known hosts to prevent bounce or mirroring DDOS attacks.

Hope that helps.

**Comment by martinpitt** [comment]
Thanks @stefwalter ! I relayed that to https://github.com/cockpit-project/cockpit/issues/18847#issuecomment-1570127978 as it's independent from this PR after all.
