### ISSUE TITLE
RTL Support in Cockpit

### ISSUE THREAD

**Issue by ahmedr2001** [cockpit-project/cockpit#18710]
Page: All pages

A list of some misalignments in cockpit UI when using RTL display languages.

Nav bar search icon and sections
![Screenshot from 2023-04-26 02-35-32](https://user-images.githubusercontent.com/77215230/234440011-d251a95b-fe9a-4cc3-92d7-2b6227d52a98.png)

![Screenshot from 2023-04-26 02-35-45](https://user-images.githubusercontent.com/77215230/234440247-98fee30a-d96a-4837-bed0-8866c87818ec.png)

Display language dialog
![Screenshot from 2023-04-26 02-36-09](https://user-images.githubusercontent.com/77215230/234440356-cb856a03-af11-4a7a-925b-68770a7f4c02.png)

Hosts
![Screenshot from 2023-04-26 02-36-45](https://user-images.githubusercontent.com/77215230/234440377-ab52f964-aa33-4c27-b40c-713d292207a8.png)

Accounts list (Notice the blue "Your account" badge)
![Screenshot from 2023-04-26 02-55-08](https://user-images.githubusercontent.com/77215230/234440642-586d8c31-1e94-4f96-b723-37f6f9517775.png)

Accounts list action table
![Screenshot from 2023-04-26 02-55-27](https://user-images.githubusercontent.com/77215230/234440762-a172a222-f9cd-4fe7-8336-035101e01bbe.png)

Accounts list search bar
![Screenshot from 2023-04-26 02-56-50](https://user-images.githubusercontent.com/77215230/234440812-69d5a65b-3598-4fa4-810f-ee1eac6f7c88.png)

Bond settings modal
![Screenshot from 2023-04-26 02-57-38](https://user-images.githubusercontent.com/77215230/234440952-b53b0bc3-9b74-4e2b-a926-9ac299109cb0.png)

Networking page
![Screenshot from 2023-04-26 02-57-49](https://user-images.githubusercontent.com/77215230/234441190-597878e7-d81a-4f19-b679-84fde0897135.png)

![Screenshot from 2023-04-26 03-04-36](https://user-images.githubusercontent.com/77215230/234441497-36408cf3-385d-4ae0-809e-67ed9656c96a.png)

Networking page: Interfaces
![Screenshot from 2023-04-26 02-58-37](https://user-images.githubusercontent.com/77215230/234441267-f3d3c93a-3420-4c01-bf07-08a8c7c4bd13.png)

Networking page: logs
![Screenshot from 2023-04-26 02-59-22](https://user-images.githubusercontent.com/77215230/234441304-519bb4c1-9659-4d17-9cf3-31fb08237e7c.png)

VM page
![Screenshot from 2023-04-26 03-00-03](https://user-images.githubusercontent.com/77215230/234441357-504a9085-8008-4d32-8930-caf2d51289ab.png)

Switch to Limited access
![Screenshot from 2023-04-26 03-04-07](https://user-images.githubusercontent.com/77215230/234441452-2225fc8e-bbd5-4852-99fe-4a92d65b2d0e.png)

Help
![Screenshot from 2023-04-26 03-05-10](https://user-images.githubusercontent.com/77215230/234441525-2eb685ba-5b04-4e44-833c-facfb57404bd.png)

**Comment by KKoukiou** [comment]
Closing in favor of https://github.com/cockpit-project/cockpit/issues/14058
