### ISSUE TITLE
pybridge: superuser privs not set with old dashboard/webserver

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#18712]
This breaks TestSuperuserOldDashboard, TestSuperuserOldWebserver, and TestSuperuserDashboardOldMachine.

These are edge cases mostly to rescue the old "greedy authentication" behaviour. Users can just authenticate again directly, so I don't consider this a pybridge-blocker.

**Comment by mvollmer** [comment]
TestSuperuserOldDashboard, TestSuperuserOldWebserver should be fixed by #18984 . TestSuperuserDashboardOldMachine is something else.

**Comment by mvollmer** [comment]
TestSuperuserDashboardOldMachine  is fixed by #18712.
