### ISSUE TITLE
Simpler reauthorization using second login

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1874]
I'd like to implement a simpler reauthorization mechanism, where we just log in again. The presence of a second login allows the first to escalate privileges. Will put more information here. Discussion on this topic occurred at DevConf ... but wasn't yet documented.

**Comment by martinpitt** [comment]
This is very stale, does not have a lot of information, and at least at first sight this seems dangerous -- if we log into Cockpit in two different browser tabs, they should *not* be able to talk to each other directly and exchange credentials, no? Also, right now you can't really (or at least easily) have a "second login", as once you are logged in, the browser always sends the existing session cookie to a new cockpit tab/page.
