### ISSUE TITLE
Correctly write names of crypto policies

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#18790]
Right now it looks like this:
![Screenshot from 2023-05-11 11-17-36](https://github.com/cockpit-project/cockpit/assets/12330670/59e5d2e1-69af-414a-afc2-41304205b06b)

We should always write FIPS and not Fips, also SHA1 not sha1, OSPP instead of ospp and AD-support rather than ad-support. Also we name the policy Default but in description we use DEFAULT. We should be consistent about this.

**Comment by Pushkarm029** [comment]
Can you assign me this issue?

**Comment by Pushkarm029** [comment]
@marusak I'm new to open source, and I've already cloned this project locally; could you please assign me this issue?

**Comment by martinpitt** [comment]
@Pushkarm029 We don't generally do that. If you want to work on Cockpit, that's much appreciated of course!  Please work through https://github.com/cockpit-project/cockpit/blob/main/HACKING.md if you didn't already, and then feel free to ask [in the chat](https://matrix.to/#/#cockpit:fedoraproject.org) if you run into trouble.

If you want to fix this issue, please say so here and send a pull request. Thanks!

**Comment by PavanButke** [comment]
hi , I'm also new to this project.
May I know if issue is closed? or Open?

**Comment by martinpitt** [comment]
@PavanButke : @Pushkarm029 has started working on it in #18804

**Comment by PavanButke** [comment]
np ! @martinpitt I'm new to this project. I choosen this project as I have seen java used.
Is there any way I can contribute to this project?

**Comment by Akshat2Jain** [comment]
@marusak can you close this issue now?

**Comment by martinpitt** [comment]
Ah, we forgot to refer to it in the PR. Thanks!
