### ISSUE TITLE
Storage: mmc card incorrectly detected as multipathed drive

### ISSUE THREAD

**Issue by zegab1** [cockpit-project/cockpit#18805]
### Explain what happens

1. My system uses an eMMC card as boot device. MMC cards can have two boot partions, which are separate protected areas from the main data partitions. These are not defined by a partition table, but a [feature](https://www.kernel.org/doc/Documentation/mmc/mmc-dev-parts.txt) of the hardware itself.

```
# dmesg | grep mmc
[    1.729330] mmc0: CQHCI version 5.10
[    1.729508] mmc0: SDHCI controller on PCI [0000:00:1a.0] using ADMA 64-bit
[    1.832728] mmc0: Command Queue Engine enabled
[    1.835127] mmc0: new HS400 Enhanced strobe MMC card at address 0001
[    1.842286] mmcblk0: mmc0:0001 AJTD4R 14.6 GiB 
[    1.846842]  mmcblk0: p1 p2 p3
[    1.849605] mmcblk0boot0: mmc0:0001 AJTD4R 4.00 MiB 
[    1.852290] mmcblk0boot1: mmc0:0001 AJTD4R 4.00 MiB 
[    1.855146] mmcblk0rpmb: mmc0:0001 AJTD4R 4.00 MiB, chardev (238:0)

# lsblk
NAME                  MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda                     8:0    0 931.5G  0 disk 
├─sda1                  8:1    0   200M  0 part 
├─sda2                  8:2    0 465.7G  0 part 
└─sda3                  8:3    0 465.5G  0 part 
mmcblk0               179:0    0  14.6G  0 disk 
├─mmcblk0p1           179:1    0   512M  0 part /boot/efi
├─mmcblk0p2           179:2    0     1G  0 part /boot
└─mmcblk0p3           179:3    0  13.1G  0 part 
  ├─vg_system-lv_root 253:0    0     8G  0 lvm  /
  └─vg_system-lv_var  253:1    0     4G  0 lvm  /var
mmcblk0boot0          179:8    0     4M  1 disk 
mmcblk0boot1          179:16   0     4M  1 disk 
nvme0n1               259:0    0   1.8T  0 disk 
├─nvme0n1p1           259:1    0   1.8T  0 part 
└─nvme0n1p9           259:2    0     8M  0 part
``` 
2. The block devices "/dev/mmcblk0", "/dev/mmcblk0boot0" and "/dev/mmcblk0boot1" are backed by the same drive ID, reported similarly in sysfs and by storaged
3. This specific setup will set "client.broken_multipath_present = true" [here](https://github.com/cockpit-project/cockpit/blob/0181f0e4c4f21bec53a0b4eb0bc773c8afc6f6a2/pkg/storaged/client.js#L238). 
4. As a consequence, I'll get the [alert](https://github.com/cockpit-project/cockpit/blob/cfde666c56a18bb4d0bceeb2421efb574e015beb/pkg/storaged/multipath.jsx#L65) "Danger alert:There are devices with multiple paths on the system, but the multipath service is not running." on the UI, and I'm not able to use this feature unless I have multipathd running on the system.

Multipathd's default [blacklist](https://github.com/opensvc/multipath-tools/blob/master/libmultipath/blacklist.c#L201) prevents mmc devices to be considered for multipathing:
```
# multipath -c -v 3 /dev/mmcblk0
5012.625461 | set open fds limit to 1073741816/1073741816
5012.625491 | loading /lib64/multipath/libchecktur.so checker
5012.625618 | checker tur: message table size = 3
5012.625628 | loading /lib64/multipath/libprioconst.so prioritizer
5012.625726 | _init_foreign: foreign library "nvme" is not enabled
5012.625914 | mmcblk0: device node name blacklisted
DM_MULTIPATH_DEVICE_PATH="0"
5012.625979 | unloading tur checker
5012.626013 | unloading const prioritizer
```

Now I have to run multipathd as a workaround even if it my system is not having multipathed drives in reality.

[udiskctl_dump.txt](https://github.com/cockpit-project/cockpit/files/11472738/udiskctl_dump.txt)

### Version of Cockpit

276.1 (bundled with OS)

### Where is the problem in Cockpit?

Storage

### Server operating system

other

### Server operating system version

Rocky Linux 9.1

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
@mvollmer can you please have a look here?

**Comment by jelly** [comment]
This should be fixed in https://github.com/cockpit-project/cockpit/pull/20329 and included in 316
