### ISSUE TITLE
Cockpit image builder : Filesystem tile has title Firewall

### ISSUE THREAD

**Issue by bdherouville** [cockpit-project/cockpit#18838]
### Explain what happens

1. Open ablueprint
2. Click on the Filesystem customization
3. The tile has title "Firewall"

![image](https://github.com/cockpit-project/cockpit/assets/13697064/40629125-f98a-4e6b-aaa0-f201875a655b)

### Version of Cockpit

286.1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Red Hat Enterprise Linux

### Server operating system version

9.2

### What browsers are you using?

Chrome

**Comment by martinpitt** [comment]
This applies to the https://github.com/osbuild/cockpit-composer/ project, can you please file that there? Unfortunately GitHub does not allow issues to get transfered across organizations. Thanks!
