### ISSUE TITLE
icons lost in zfs tab for cockpit-zfs-manager

### ISSUE THREAD

**Issue by zer0to1ne** [cockpit-project/cockpit#18841]
### Explain what happens

I'm running Cockpit 287-1~bpo11+1 on Proxmox 7.4-3 from Debian's backports repo. After installing the 45Drives' cockpit-zfs-manager addon, I found some minor icons are lost on the zfs tab. Any idea how to tweak this little bug?

![Snipaste_2023-05-24_16-34-08](https://github.com/cockpit-project/cockpit/assets/81726521/96735802-6741-48f3-8c85-4a33bcaa1d46)

### Version of Cockpit

287-1~bpo11+1

### Where is the problem in Cockpit?

Applications

### Server operating system

Debian

### Server operating system version

Proxmox 7.4-3

### What browsers are you using?

Firefox

**Comment by jelly** [comment]
We don't maintain the ZFS plugin, so I would suggest to open a bug there but you already commented on https://github.com/45Drives/cockpit-zfs-manager/issues/15 

The project needs to ship fontawesome fonts themself as Cockpit no longer does, meanwhile a workaround was posted here https://github.com/45Drives/cockpit-zfs-manager/issues/15#issuecomment-1407443216
