### ISSUE TITLE
Unable to scroll terminal using scrollbar

### ISSUE THREAD

**Issue by LunarTwilight** [cockpit-project/cockpit#18859]
### Explain what happens

1. Go to terminal
2. Use terminal enough that you get a scrollbar
3. Unable to use scrollbar

Poking around in inspect element, it seems that
```css
.xterm .xterm-screen {
    position: relative;
}
```
is what is causing it, if I uncheck that rule, the scrollbar works again.

### Version of Cockpit

292-1~bpo22.04.1

### Where is the problem in Cockpit?

Terminal

### Server operating system

Ubuntu

### Server operating system version

22.04.2 LTS

### What browsers are you using?

Chrome

**Comment by jelly** [comment]
Scrolling works, but trying to scroll by clicking the scrollbar indeed does not work. The mouse pointer should also change when hovering over the scrollbar.

[Screencast from 2023-05-30 14-31-57.webm](https://github.com/cockpit-project/cockpit/assets/67428/556a2c5e-1889-4847-80d7-9202e1b4b8d1)

**Comment by LunarTwilight** [comment]
> Scrolling works, but trying to scroll by clicking the scrollbar indeed does not work. The mouse pointer should also change when hovering over the scrollbar.

Yeah same for me, it works if I scroll another way, but it doesn't work if I use the scrollbar.

**Comment by subhoghoshX** [comment]
Apart from the issue mentioned above, the terminal is also not taking full height (there's a little gap at the bottom).

![image](https://github.com/cockpit-project/cockpit/assets/108616679/1782099b-dee9-4640-bc14-863eee2ffde0)

I found bringing back some of the CSS removed in this [commit](https://github.com/cockpit-project/cockpit/commit/65471fd9fcbc09343fa66246889bb2c48032cf8a#diff-56769b147d9240af6baba616f66a2ac27cf67a40be3b8f7992400ffb48a0fc8a) seem to fix it all.
