### ISSUE TITLE
Virtual Machine (VM) config issues.

### ISSUE THREAD

**Issue by FoxIDK** [cockpit-project/cockpit#18914]
### Explain what happens

1. Installed Cockpit using backports.
2. It's been running fine _beside_ the fact whenever I try to change the CPU from "custom (qemu64)" I get an error of:
```
CPU configuration could not be saved
Traceback (most recent call last): File "/usr/bin/virt-xml", line 6, in <module> from virtinst import virtxml File "/usr/share/virt-manager/virtinst/__init__.py", line 8, in <module> import gi File "/usr/lib/python3/dist-packages/gi/__init__.py", line 40, in <module> from . import _gi ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
```
3. It was working until I recently did an upgrade and update of my Ubuntu 20.04 LTS installation.
4. I've attempted to reinstall, and purge reinstall cockpit and it's associated packages _(such as cockpit-machines)_ 

I've done:
```
sudo apt purge python3-gi
sudo apt install python3-gi
sudo apt purge cockpit
sudo apt install cockpit
sudo apt purge cockpit-machines
sudo apt install cockpit-machines
sudo apt install gir1.2-glib-2.0 gir1.2-dbusmenu-glib-0.4
sudo apt install virtinst
sudo apt update && sudo apt upgrade
```
followed by rebooting too to no success. I've come to find a friend of mine, also running Ubuntu 20.04 LTS is having a similar issue with virtinst not being present and when they've installed it manually they've been met with the same error.

For the versions installed it's:
```
cockpit/jammy-backports,now 292-1~bpo22.04.1 all [installed]
cockpit-machines/jammy-backports,now 283-1~bpo22.04.1 all [installed]
```

![image](https://github.com/cockpit-project/cockpit/assets/120978468/127c711d-4122-4436-b982-65cbbeb6a8ab)
![image](https://github.com/cockpit-project/cockpit/assets/120978468/f798c566-ebc0-41be-9469-6d4358047567)

It also came to my attention _and may be worth noting_ that when I do try to set up a VM I can't choose any operating system, as non are listed either:

![image](https://github.com/cockpit-project/cockpit/assets/120978468/b56da260-5d91-4f4a-8341-d4797f78a205)

**Any insight or information would be greatly appreciated. Thank you**.

### Version of Cockpit

cockpit/jammy-backports,now 292-1~bpo22.04.1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Ubuntu

### Server operating system version

20.04 LTS

### What browsers are you using?

Firefox, Edge, Brave

**Comment by FoxIDK** [comment]
Through trial and error, I've found it's an issue if you're using Python 3.11.x

I've resolved this issue by doing the following:
`sudo unlink python`
`sudo unlink python3`
`sudo ln -s /usr/bin/python3.10 python`
`sudo ln -s /usr/bin/python3.10 python3`

This is assuming you've got Python installed in the `/usr/bin/*` directory.
_I was able to reproduce this Python 3.11.x related bug on a fresh Ubuntu machine, as well as Debian. It is consistent with using Python 3.11.x by-default._

**Comment by janfickler** [comment]
Hi,
is for python3.11 a bugfix in the making ?
