### ISSUE TITLE
Please add "systemctl reset-failed" button to service module

### ISSUE THREAD

**Issue by lnykryn** [cockpit-project/cockpit#18919]
Page: Services

Could you please add a button that would run systemctl reset-failed?

One use, case is that I've run something bad with systemd-run (systemd-run /bin/false), for example, and now I have a failed unit. But I really want to make the error disappear. From terminal this is simple, I just type the mentioned systemctl reset-failed, but I don't see a way how to do it directly from the cockpit.

**Comment by martinpitt** [comment]
This already exists. It's called "Clear 'Failed to start'" in the three-dot menu on the service details page:

![image](https://github.com/cockpit-project/cockpit/assets/200109/30b0dd4b-7e4c-4546-8257-d272c4738141)

**Comment by lnykryn** [comment]
Yeah, but in my case I had like twenty failed services and wanted to clean all at once.

**Comment by martinpitt** [comment]
That's not something that we want to make "too easy". In most cases, services fail independently from each other, and should be investigated separately.
