### ISSUE TITLE
network-manager, udisks, kdump, sosreport, podman, machines: Hide pages with missing dependencies

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#18935]
### Explain what happens

1. Connect to a Debian/Ubuntu/Raspbian system that is a basic install that does not have Cockpit
2. You can't really do much; many pages have errors

Without some basic dependencies, Cockpit isn't as useful as it should be.

We need a way to install the dependencies without having to install a Cockpit package (which pulls in the dependencies).

### Version of Cockpit

293 beta

### Where is the problem in Cockpit?

None

### Server operating system

other

### Server operating system version

Raspbian 10

### What browsers are you using?

Cockpit Client / Cockpit Desktop

**Comment by martinpitt** [comment]
> We need a way to install the dependencies without having to install a Cockpit package (which pulls in the dependencies).

FTR, I veto that, see https://issues.redhat.com/browse/COCKPIT-943  . But of course what we should at least do here is to add conditions to these pages to not show up. Thanks for the report!

**Comment by garrett** [comment]
I think it's 3 steps:

1. Disable pages that do not have support (instead of showing broken pages)
2. Show some message somewhere that pages aren't enabled because things are lacking
3. Provide a way to optionally fix it in Cockpit

Not installing the packages should not be an error. Also: Installing deps shouldn't be automatic.

**Comment by martinpitt** [comment]
PR #18939 fixes the first four pages in this list.

**Comment by martinpitt** [comment]
machines fixed in https://github.com/cockpit-project/cockpit-machines/pull/1105

SELinux fixed in https://github.com/cockpit-project/cockpit/pull/18941

Apps/Playground fixed in https://github.com/cockpit-project/cockpit/pull/18940

The remaining one is podman, being fixed in https://github.com/cockpit-project/cockpit-podman/pull/1305

**Comment by martinpitt** [comment]
Closing, all pages on the cockpit side got addressed. The podman PR is already on our radar independently.
