### ISSUE TITLE
Ctrl-Shift-J doesn't work in Cockpit Client; we may want to change the string in Cockpit itself

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#18936]
### Explain what happens

When getting an "Ooops!", we have a message to use Ctrl-Shift-J. But it doesn't work in Cockpit Client, and we might want to change it for other browswers in general, as it doesn't always show all the logs anyway.

![image](https://github.com/cockpit-project/cockpit/assets/10246/7ebb05be-2937-4675-8682-1f37f80e2d8e)

### Where is the problem in Cockpit?

None

### Server operating system

other

### What browsers are you using?

Cockpit Client / Cockpit Desktop

**Comment by allisonkarlitskaya** [comment]
I checked ephy and Ctrl+Shift+J doesn't do anything there, either, but (as in Cockpit Client) Ctrl+Shift+I works.

**Comment by allisonkarlitskaya** [comment]
> I've seen that ctrl-shift-j shows different things from the devtools, at least in Firefox, at least in the past. They're not 1:1. Not sure which would be better for Cockpit messages for debugging, however.

Your call :)

Should we do it per-browser?
