### ISSUE TITLE
Unable to connect to secondary host using hostname

### ISSUE THREAD

**Issue by marvinruder** [cockpit-project/cockpit#18931]
### Explain what happens

I am trying to connect to another host after logging in to my primary server as described [here](https://cockpit-project.org/guide/latest/authentication.html#secondary-auth). This works fine when using the secondary server’s IP adress, but fails with `no-host` when using its hostname (Using the IP address in the background but setting a nice readable ID in the `machines.d` config also does not work because of https://github.com/cockpit-project/cockpit/issues/13094 – has anyone looked into that lately?).

Some possibly relevant details:

- I am running the web interface on the primary server from the `cockpit-ws` container in Docker
- `sshd` runs on a custom port on all servers
- Both `ip.address:port` and `[hostname]:port` entries exist in the user’s `known_hosts` file
- The hostname is configured in `/etc/hosts` of the primary server and can be resolved by a `dnsmasq` DNS server running on the primary server. This works fine also with Docker’s networking, `ssh hostname -p port` works fine both within the `cockpit-ws` container and directly on the primary server. Mounting `/etc/hosts` into the `cockpit-ws` container has no effect.

### Version of Cockpit

293

### Where is the problem in Cockpit?

Navigation & Shell

### Server operating system

Fedora

### Server operating system version

Fedora CoreOS 38.20230514.3.0

### What browsers are you using?

Safari macOS, Safari on iPhone

### System log

```shell
My system's journal does not show any cockpit-related information -- can I perhaps obtain these from the `cockpit-ws` container? Its stdout only shows `Agent pid 12`
```

**Comment by martinpitt** [comment]
Could it be that you fell into the issue #18653 trap? I.e. pressing the "Enter" key when entering the password? That has surely tripped me up a lot of times.

**Comment by marvinruder** [comment]
Seems unlikely, I am using an SSH key with no password to connect to other hosts from the primary, so there is no password prompt involved. Must have been something else in my infrastructure.
