### ISSUE TITLE
"Web Console" link is hardcoded in js

### ISSUE THREAD

**Issue by champtar** [cockpit-project/cockpit#18958]
### Explain what happens

It would be nice if "Web Console" link could be disabled / be part of the branding
https://github.com/cockpit-project/cockpit/blob/5a497e86c771ef13763f7a114924b1f38ac9bda9/pkg/shell/topnav.jsx#L151

I'm building an Appliance using Cockpit as the WebUI, I have no problem having a About web console talking about cockpit, but it's a bit confusing to send customer to RedHat docs.
(I can obviouly patch the js but I prefer config/branding over patch)

### Version of Cockpit

main

### Where is the problem in Cockpit?

Navigation & Shell

**Comment by martinpitt** [comment]
Our branding is currently CSS only. That does inject some text using `:before`, and in principle you could do some nasty tricks with hiding the "Web Console" menu entry with CSS, it feels hackish. But moreover, many pages also add their page specific help URLs, e.g. the [Accounts page's](https://github.com/cockpit-project/cockpit/blob/06130aed574c2472605ac21dd8c1b03cb104c26c/pkg/users/manifest.json#L6). These are easier to change with [manifest overrides](https://cockpit-project.org/guide/latest/packages.html#package-manifest-override), though.

We currently show these in all OSes (also Debian, Fedora, Ubuntu, etc.) as the RH docs are not really RH specific, they apply to all other OSes as well. That said, I don't mind making this more configurable. One obvious change would be to move the "Web Console" link into `shell.manifest`, where it can be overridden. Would that work for you?

That said, there are still a few more RH doc links in the code which are specific to a particular dialog, as opposed to the whole page:
```
pkg/networkmanager/bond.jsx:                                          href="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_systems_using_the_rhel_8_web_console/configuring-network-bonds-using-the-web-console_system-management-using-the-rhel-8-web-console">
pkg/systemd/hwinfo.jsx:                                            <a href="https://access.redhat.com/security/vulnerabilities/L1TF" target="_blank" rel="noopener noreferrer">
pkg/systemd/overview-cards/cryptoPolicies.jsx:                    href="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/assembly_installing-a-rhel-8-system-with-fips-mode-enabled_security-hardening">
pkg/systemd/overview-cards/cryptoPolicies.jsx:                        href="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening">
pkg/systemd/overview-cards/tuned-dialog.jsx:                        href="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/managing_systems_using_the_rhel_8_web_console/index#optimizing-the-system-performance-using-the-web-console_system-management-using-the-RHEL-8-web-console">
```

We could try to move these into the manifest as well, but that's becoming a bit unwieldy. Do you actually mind these, though?

**Comment by champtar** [comment]
I don't mind the other links, it's really the "Web Console" one that is kind of "how to use your server", but when you are building an Appliance using Cockpit there is a lot of irrelevant content, because pages have been removed/added/...
Page specific docs are still relevant even when you are using custom cockpit.

**Comment by martinpitt** [comment]
Ack, thanks. Let's move that particular link into the manifest then.

**Comment by martinpitt** [comment]
I sent PR #19126 to do that.
