### ISSUE TITLE
Login constantly spins

### ISSUE THREAD

**Issue by tgwaste** [cockpit-project/cockpit#18986]
update today makes the login button have a constant spinner. not a big issue just thought I would mention it
```
ii  cockpit-bridge                        294.1-1~bpo22.04.1
ii  cockpit-machines                      292-1~bpo22.04.1
ii  cockpit-networkmanager                294.1-1~bpo22.04.1
ii  cockpit-packagekit                    294.1-1~bpo22.04.1
ii  cockpit-pcp                           294.1-1~bpo22.04.1
ii  cockpit-storaged                      294.1-1~bpo22.04.1
ii  cockpit-system                        294.1-1~bpo22.04.1
ii  cockpit-ws                            294.1-1~bpo22.04.1
```
<img width="470" alt="Screenshot 2023-06-21 at 1 07 34 PM" src="https://github.com/cockpit-project/cockpit/assets/690918/694cb17f-be25-456b-ba33-b90dbc7331de">

**Comment by martinpitt** [comment]
I started a clean 22.04 cloud image and installed the official 294.1-1~bpo22.04.1 , same as you have. I cannot confirm this. The login button has no spinner initially, and when I enter user/password, it shows *only* a spinner (no "Log in") for about half a second, and then the session starts. This is with Firefox 113.

Can you please be more specific what exactly happens, and when? Is that the initial state? What happens after entering user/password? Does the login actually work? (I suppose so, as you said "no big issue"). What browser version do you use? Any extensions?

Thanks!

**Comment by tgwaste** [comment]
I logged out and logged and the problem is no longer happening.  False alarm I guess!
