### ISSUE TITLE
Metrics page should provide links to network interfaces

### ISSUE THREAD

**Issue by briansmith0** [cockpit-project/cockpit#18998]
Page: Overview / "View metrics and history"

On the metrics page, we have links to the top services taking CPU, memory, and disk resources, and we have links to filesystems.    All of these links provide users the ability to get more details.  

However, under the Network section, there are no links for the network interfaces.  It would be helpful to be able to click a link for the network interface and be taken to that section of Cockpit (i.e. <host>/network#/<interface>) so that I can see additional information about this interface, as well as performance graphs specific to this interface.  

See screenshot:

![Screenshot from 2023-06-22 14-53-01](https://github.com/cockpit-project/cockpit/assets/60192516/72f0bf4c-f07b-4f91-965b-93dfd4bca993)

**Comment by martinpitt** [comment]
Thanks @briansmith0 , well spotted!

For implementers: There may not always be an 1-1 correspondence between those, as NetworkManager does not manage all interfaces in all cases. But we can at least do some approximation and ask NM about its known/managed interfaces when the page starts. Or perhaps there is even some minimal r/o information even if the interface is managed by e.g. networkd or cloud-init. So this is something to watch out for.

**Comment by iampaandey** [comment]
is this issue still open ?

**Comment by martinpitt** [comment]
@iampaandey Yes, it is.

**Comment by jainamshah102** [comment]
I am interested to work on this issue. Can you provide some guidance and assistance in resolving this.

**Comment by martinpitt** [comment]
@jainamshah102 : Thanks for your interest! To set yourself up for Cockpit development, please follow the first two sections of https://github.com/cockpit-project/cockpit/blob/main/HACKING.md , and make sure you can make a trivial change (like changing some string), and see it in your browser.
