### ISSUE TITLE
Pixel failures due to noise with Chromium 114

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#19001]
We have a lot of [failed test](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18992-20230622-141833-5770d0e3-fedora-38-pybridge-networkingm/log.html#31) with [pixel noise](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18992-20230622-141833-5770d0e3-fedora-38-pybridge-networking/pixeldiff.html#TestTeam-testBasic-networking-team-settings-dialog-mobile) since we moved to Chromium 114 yesterday. If you zoom in closely, there's a handful of red  pixels around the dialog's "X" close button. 

More examples:
 - https://cockpit-logs.us-east-1.linodeobjects.com/pull-18994-20230622-153534-d4e9e05f-fedora-38-pybridge-networking/log.html
 - https://cockpit-logs.us-east-1.linodeobjects.com/pull-18994-20230622-172333-d4e9e05f-fedora-38-pybridge-networking/log.html
 - https://cockpit-logs.us-east-1.linodeobjects.com/pull-18996-20230623-040635-2fcb486f-fedora-38-storage/pixeldiff.html#TestStorageLuks-testLuks-format - this is not the close button, but noise in the "reveal eye" icon of the password field

@mvollmer , I believe you looked at similar cases before.  What do we do in these cases? Increase the allowed fuzz?

_Originally posted by @martinpitt in https://github.com/cockpit-project/cockpit/issues/18992#issuecomment-1602778394_

**Comment by martinpitt** [comment]
The metrics page renders SVG for expanded hours, and we have a [pixel test](https://github.com/cockpit-project/pixel-test-reference/blob/bbdb50f7f706905b3c751666fb666ca16f08ad18/TestHistoryMetrics-testEvents-metrics-history-expanded-hour-medium-pixels.png) for it. But perhaps we can somehow restrict this to ignore PF icons?

**Comment by mvollmer** [comment]
> The metrics page renders SVG for expanded hours, and we have a [pixel test](https://github.com/cockpit-project/pixel-test-reference/blob/bbdb50f7f706905b3c751666fb666ca16f08ad18/TestHistoryMetrics-testEvents-metrics-history-expanded-hour-medium-pixels.png) for it. But perhaps we can somehow restrict this to ignore PF icons?

oh, and it uses mock data to get reliably rendered graphs! nice!
