### ISSUE TITLE
Full Screen VNC Console Pop Out Window

### ISSUE THREAD

**Issue by tgwaste** [cockpit-project/cockpit#19007]
Please, for the love of god make this!  I mean.. now the freaking side window is even smaller and the expanded window got bigger which is bad when its confined to its space.

Please just give us a full screen pop-out window for this that scales properly to our screen sizes..  It would be so very useful.

**Comment by jelly** [comment]
I assume this is about cockpit-machines, we have a separate issue tracker for it [here](https://github.com/cockpit-project/cockpit-machines/issues) and there is already an issue open about a similar feature request https://github.com/cockpit-project/cockpit-machines/issues/680
