### ISSUE TITLE
No spacing between spinner and text

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#19059]
### Explain what happens

When clicking `Report to Fedora` the spinner has no spacing between itself and the text. Also when an error occurs and you re-click report the error is not cleared (as can be seen in `Report to ABRT Analysis`)

Easiest to reproduce by putting a `testlib.sit()` in `test/verify/check-system-journal` and run

```
TEST_SHOW_BROWSER=1 ./test/verify/check-system-journal -vst TestJournal.testAbrtSegv
```

![image](https://github.com/cockpit-project/cockpit/assets/67428/46b0157d-4ac4-4076-884d-ecad46e61faf)

### Where is the problem in Cockpit?

None

### Server operating system

None

**Comment by omarY23** [comment]
Should I create separate PRs for each of them?

**Comment by jelly** [comment]
> Should I create separate PRs for each of them?

Fixing all the spacing issues with the spinner at once is fine. The modal design needs some more work/ux.

**Comment by garrett** [comment]
Something like this?

![API key dialog](https://github.com/cockpit-project/cockpit/assets/10246/6fb8d638-2a0e-4ef3-b8bb-81958f2d7459)

- Explains what's needed
- Has a link to actually get the key
- Uses standard PF conventions

---

I played around with the layouts, but thought the one above would be best.

![image](https://github.com/cockpit-project/cockpit/assets/10246/49fd6129-f2c5-475f-a69e-dd700e21a0da)

**Comment by vishalsingh2972** [comment]
@jelly could you assign this to me I would like to give it a try!

**Comment by martinpitt** [comment]
@vishalsingh2972 Please go ahead, thank you!

**Comment by ishsarin** [comment]
Hi, if this is open can I contribute?

**Comment by martinpitt** [comment]
@ishsarin Please do, much appreciated! Please go through https://github.com/cockpit-project/cockpit/blob/main/HACKING.md first, to make sure that you are set up for development.

**Comment by dushyantpant5** [comment]
Are there some issues which are still open? Can I contribute?

**Comment by garrett** [comment]
If you'd like to send up a PR for this, please make sure this issue number is referenced; then it will show up here in the issue. There's no need to ask if you can work on it; you can just work on it and send a PR.

As far as I'm aware, nobody has handled this yet (as it doesn't have a link to a PR here yet).

**Comment by yashpandey06** [comment]
I want to work on this issue, please assign this issue to me if no is working on it

**Comment by ashutosh7i** [comment]
Hello i was browsing for some good first issues as i am new contributor,
i think this issue has been already merged, can you close this issue?
or am i wrong ?
actually i was interested

**Comment by martinpitt** [comment]
Hm, I don't see any commit/PR which would have addressed that. I may have missed it, of course. But there are more issues here, I'm fairly sure that not all of them are addressed.

**Comment by tahamukhtar20** [comment]
kindly assign this task to me, I've opened a pull request, that could potentially fix this issue, I'd like to link that PR to this issue thanks.

**Comment by subhoghoshX** [comment]
> kindly assign this task to me, I've opened a pull request, that could potentially fix this issue, I'd like to link that PR to this issue thanks.

You can link a PR to an issue with #issue-number in your PR description (you may also do that in you commit message as well).

I assume the PR you mentioned is #19729. I've added it in your PR description. Thanks :)

**Comment by subhoghoshX** [comment]
> kindly assign this task to me, I've opened a pull request, that could potentially fix this issue, I'd like to link that PR to this issue thanks.

You can link a PR to an issue with #issue-number in your PR description (you may also do that in you commit message as well).

I assume the PR you mentioned is #19729. I've added it in your PR description. Thanks :)

**Comment by subhoghoshX** [comment]
> kindly assign this task to me, I've opened a pull request, that could potentially fix this issue, I'd like to link that PR to this issue thanks.

You can link a PR to an issue with #issue-number in your PR description (you may also do that in you commit message as well).

I assume the PR you mentioned is #19729. I've added it in your PR description. Thanks :)

**Comment by tahamukhtar20** [comment]
yes, thanks alot.
