### ISSUE TITLE
AMD CPU temperature monitoring

### ISSUE THREAD

**Issue by tomasmatus** [cockpit-project/cockpit#19055]
As mentioned in #18098 it looks like there's been some misunderstanding on my end how the k10temp driver reports temperature.
The assumption that `tccd` or `tdie` are reported on all CPU models appears to be incorrect. The driver [documentation](https://docs.kernel.org/hwmon/k10temp.html) mentions that these additional sensors **may** report values.

In #18098 there is a report that 5600g only reports `Tctl` value and `tccd` or `tdie` are not present. 

Perhaps `Tctl` sensor value should be used as a fallback when no other  k10temp sensor is available or it shouldn't be ignored at all.

**Comment by tomasmatus** [comment]
Now that I have small arsenal of two recent AMD CPUs at home and I can easily check on real hardware:

My 5700g only reports a single value:

-`temp1_label` with label `Tctl`

Whereas my 7800X3D reports two values 

- `temp1_label` with label `Tctl`
- `temp3_label` with label `Tccd1`

@jelly WDYT? Should we use `Tctl` as a fallback when nothing else is available or no longer ignore it and always use its value?

**Comment by jelly** [comment]
Sounds good!

**Comment by zeroZshadow** [comment]
What version was this fix rolled out on?
I'm on 299, using an AMD 5600g and `sensors` showing the `Tctl` sensor from k10temp.
But the temperature is not displayed in either the overview nor the metrics.

I am however seeing a `CPU temperature metric closed` error in the browser console.

**Comment by martinpitt** [comment]
It was released in 296. @tomasmatus, what information do you need from @zeroZshadow to debug this?
