### ISSUE TITLE
Switching selinux automation script tabs still shows text is copied (but it goes away after a while)

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#19057]
### Explain what happens

Copy the ansible script and then switch to the shell script version, notice that the clipboard still shows as copied.

[Uploading Screencast from 2023-07-04 09-32-17.webm…]()

**Comment by jelly** [comment]
[Screencast from 2023-07-04 09-32-17.webm](https://github.com/cockpit-project/cockpit/assets/67428/3c783b85-c5ce-478a-8ce9-72b8e5d1998e)

**Comment by omarY23** [comment]
Hey @jelly . There are two ways of which I can think. First one is maybe to reduce the setTimeout  for state copied: 

```
                    .then(() => {
                        this.setState({ copied: true });
                        setTimeout(() => {
                            this.setState({ copied: false });
                        }, 3000);
                    })
```

The second one is that as soon as tab is clicked I set the copied state again to false.

```
    handleSelect(event, active_tab) {
        this.setState({ active_tab });
        this.setState({copied: false})       // making change here
    } 
```
Which one should be better?

**Comment by jelly** [comment]
> Hey @jelly . There are two ways of which I can think. First one is maybe to reduce the setTimeout for state copied:
> 
> ```
>                     .then(() => {
>                         this.setState({ copied: true });
>                         setTimeout(() => {
>                             this.setState({ copied: false });
>                         }, 3000);           // **decreasing this time**
>                     })

We don't want to decrease the timeout, but we can clear the timeout using `clearTimeout` this requires us to save the output of `setTimeout` which can be used to clear the timeout when switching in `handleSelect`.

See https://developer.mozilla.org/en-US/docs/Web/API/clearTimeout

**Comment by omarY23** [comment]
So should I go ahead with clearing the timeout in the handleSelect function in which tabs are clicked?

**Comment by jelly** [comment]
> So should I go ahead with clearing the timeout in the handleSelect function in which tabs are clicked?

That would be my suggestion yes
