### ISSUE TITLE
Progressbar looks strange in apps page

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#19062]
### Explain what happens

![image](https://github.com/cockpit-project/cockpit/assets/67428/580c1d4b-a911-4a7a-ac5f-f24dd9ef5894)

### Where is the problem in Cockpit?

None

### Server operating system

None

**Comment by ianbrown78** [comment]
I am running v286 on RHEL9.2 and the progress bar looks fine.
![Screenshot from 2023-08-22 20-35-02](https://github.com/cockpit-project/cockpit/assets/1063820/93ba44ed-0442-4264-a2dd-9efe061c64e8)

**Comment by jelly** [comment]
The latest release is 298 and this issue is related to the overall progress bar.

**Comment by leomoty** [comment]
@jelly is the goal something like this?

![image](https://github.com/cockpit-project/cockpit/assets/1463740/1770ec6c-61ba-48a5-8931-8680edbc6b2c)

I tried to check on my raspberry how it looked, but the progressbar itself changed somewhat significantly
