### ISSUE TITLE
Stop using deprecated onKeyPress

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#19061]
### Explain what happens

It turns out that [onKeyPress](https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event) is deprecated, which we still [use](https://github.com/search?q=org%3Acockpit-project%20onKeyPress&type=code) and can be fixed by using [different event listeners](https://www.delftstack.com/howto/react/onkeypress-react/).

**Comment by themukeshmahiya** [comment]
hi, currently I'm learning react and can try to replace these event listeners and test the changes

**Comment by vishalsingh2972** [comment]
@jelly I see a PR has already been merged for this issue, but issue still open?

**Comment by martinpitt** [comment]
@vishalsingh2972 The merged one was for cockpit-podman, but this issue is for cockpit.

**Comment by martinpitt** [comment]
This was fixed in PR #19083
