### ISSUE TITLE
Can cockpit be instgalled on any other kind of distros besides fedora centos and rehls?

### ISSUE THREAD

**Issue by topstarnetwork** [cockpit-project/cockpit#1906]
Can cockpit be instgalled on any other kind of distros besides fedora centos and rehls?

**Comment by andreasn** [comment]
Yes it can be built on various distros, provided that it has all the dependencies filled.
It's listed as [http://cockpit-project.org/running.html](available on Arch on the website), and Jared Sutton created a [PPA for Ubuntu](https://launchpad.net/~jpsutton/+archive/ubuntu/cockpit).
