### ISSUE TITLE
project: cockpit-beiboot ws container

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#19072]
Top-level goal: it should be possible to install a container onto a vanilla Fedora IoT system (no overlays) such that:

 - the container exports a webserver on a port
 - users can connect their web browser to that port to login to the host system

with the only additional requirement being that `sshd` is enabled on the host.

# Notes

This will work by way of something very similar to the existing `src/client/cockpit-beiboot` mechanism.

The beiboot code will need to be generalized and probably moved into `src/cockpit/` if we want to use it from places other than `cockpit-client`.  We probably need to do this anyway, if we want to support beibooting for `Add Host`.

This generalization of the beiboot code might well depend on the packages rework discussed in #19071.

Important: Similar to the way the flatpak operates, we'll be shipping packages (including cockpit-machines, ostree, podman) as part of the container image.  We can do this without worrying too much about forward compatibility of those pages because we can assume that, as with Flatpaks, people keep their containers more or less up-to-date (vs distro packages which can be very old, if you're on an old distro).  This means that we don't have to worry too much about getting stuck in a bad situation when dealing with unknown future API breaks in podman or libvirt.

**Comment by martinpitt** [comment]
This is also tracked in https://issues.redhat.com/browse/COCKPIT-849

**Comment by martinpitt** [comment]
It's done! https://cockpit-project.org/blog/cockpit-326.html
