### ISSUE TITLE
Newly added hosts do not persist

### ISSUE THREAD

**Issue by ethicnology** [cockpit-project/cockpit#19087]
### Explain what happens

1. Add a new host from the primary instance using web UI
2. Reboot the primary instance
3. The newly added host disappeared

I tried with and without passphrase SSH

Is there any file that can list all the hosts configurations for the primary instance ?

### Version of Cockpit

287-1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Debian

### Server operating system version

12

### What browsers are you using?

Firefox

**Comment by jelly** [comment]
Hosts are saved in `/etc/cockpit/machines.d`, there should be a json file there with the address/hostname of the host you added. Is it there?

**Comment by ethicnology** [comment]
Closing/Re-opening the browser web session make new hosts disappears

**Comment by ethicnology** [comment]
@jelly thank you for the path
