### ISSUE TITLE
Cockpit podman container -- document underlying runlabel command

### ISSUE THREAD

**Issue by Nitrousoxide** [cockpit-project/cockpit#19094]
Currently the cockpit podman install instructions for some OS's like CoreOS have you run the cockpit podman container.  This is fine of course, but the instruction have you using the runlabel built into the container to deploy it.  While this simplifies the setup some, it doesn't permit the user to tweak the conditions at all.   An obvious addition an admin might want to the deployment is the appropriate auto-update label so podman can properly update the container with a "podman auto-update" command, or if they would like to define other volume mounts to the container for ssh fingerprints.

It is possible to sdout the podman run command that makes up the runlabel and then do a manual podman run of a tweaked version, however it would probably be better to document what the recommended run command is in the how-to page so someone can tweak it as needed rather than **only** referencing the runlabel in the instructions.

**Comment by martinpitt** [comment]
I don't actually want to duplicate the exact command in the README, it's prone to get out of date. But I'm happy to add something like

> Use `podman container runlabel --display RUN quay.io/cockpit/ws` to show the `RUN` label command if you want to run the container with different arguments.

WDYT?

**Comment by Nitrousoxide** [comment]
That's probably fine.  That's what I did so I could add a self-updating systemd service to a coreOS ignition file.
