### ISSUE TITLE
Cockpit behind apache2 reverse proxy logging router ip

### ISSUE THREAD

**Issue by freaker2112** [cockpit-project/cockpit#19110]
### Explain what happens

when logging into my cockpit instance though an apache2 reverse proxy, the access log just shows my router ip as the client ip.
![image](https://github.com/cockpit-project/cockpit/assets/50562261/5d1f08e1-a2d7-4d6b-b9df-5ea875b741ef)

### Version of Cockpit

264-1ubuntu0.22.04.1

### Where is the problem in Cockpit?

Logs

### Server operating system

Ubuntu

### Server operating system version

22.04

### What browsers are you using?

Chrome

**Comment by martinpitt** [comment]
Did you add `ForwardedForHeader` to [cockpit.conf](https://cockpit-project.org/guide/latest/cockpit.conf.5.html), and the corresponding setting in your proxy? Otherwise cockpit has no chance of knowing the real origin.

This was added in commit 3a2f903155f7e79631c25b82d490943bc2a01 which is in version 264 (so just barely the version you are using).

**Comment by freaker2112** [comment]
Yes, here's my cockpit conf:

[WebService]                                                                                         
Origins = [REDACTED]
https://[REDACTED]
ProtocolHeader = X-Forwarded-Proto                                                                   
AllowUnencrypted = true    
ForwardedForHeader = X-Forwarded-For

and my apache2 conf file:
<IfModule mod_ssl.c>
<VirtualHost *:443>
 ServerName cockpit.[REDACTED].gov
 SSLCertificateFile /etc/letsencrypt/live/cockpit.[REDACTED].gov/fullchain.pem
 SSLCertificateKeyFile /etc/letsencrypt/live/cockpit.[REDACTED].gov/privkey.pem
 Include /etc/letsencrypt/options-ssl-apache.conf
 ProxyPreserveHost On
 ProxyRequests Off

 # allow for upgrading to websockets
 RewriteEngine On
 RewriteCond %{HTTP:Upgrade} =websocket [NC]
 RewriteRule /(.*)           ws://127.0.0.1:9090/$1 [P,L]
 RewriteCond %{HTTP:Upgrade} !=websocket [NC]
 RewriteRule /(.*)           http://127.0.0.1:9090/$1 [P,L]

 # Proxy to your local cockpit instance
 ProxyPass / http://127.0.0.1:9090/
 ProxyPassReverse / http://127.0.0.1:9090/
</VirtualHost>
</IfModule>

**Comment by martinpitt** [comment]
So how exactly does the network layout look like? Where's your browser, internet gateway, router, reverse proxy? I. e. which address would you *expect* to be shown? If Apache thinks the address is "192.168.86.1" and sets that in `X-Forwarded-For`, then nothing behind it can divine anything else.

**Comment by freaker2112** [comment]
the issue seems to have resolved itself upon system reboot.
