### ISSUE TITLE
TLS CBC Incorrect Padding Abuse Vulnerability

### ISSUE THREAD

**Issue by molusegit** [cockpit-project/cockpit#19141]
### Explain what happens

1. 
2. 
3. 

### Where is the problem in Cockpit?

None

### Server operating system

None

**Comment by martinpitt** [comment]
Do you have some details about that? Cockpit does not implement any crypto by itself, it uses GnuTLS.

**Comment by molusegit** [comment]
I’m actually trying to remediate a vulnerability on my linux server which was identified using a Qualys scanner.The tool identified a vuln TLS CBC Incorrect Padding Abuse Vulnerability on port 9090 which happens to be running cockpit.How do I fix this.On 27 Jul 2023, at 12:23 PM, Martin Pitt ***@***.***> wrote:﻿
Do you have some details about that? Cockpit does not implement any crypto by itself, it uses GnuTLS.

**Comment by martinpitt** [comment]
I don't know, I'm afraid.. this is pretty vague.

**Comment by martinpitt** [comment]
No further info in half a year, and not actionable.
