### ISSUE TITLE
Drop `pkg/lib` from the coverage total for subprojects

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#19157]
See martin's comment here https://github.com/cockpit-project/cockpit-ostree/pull/397#issuecomment-1655131295

@mvollmer what is your opinion of keeping `pkg/lib` in the report itself?

**Comment by martinpitt** [comment]
*By design* we aren't going to use all shared components in a subproject., What's worse: whenever we add a new one, the coverage would appear to go down. This would then block us from ever starting to use coverage delta as a gating measure.

**Comment by jelly** [comment]
Another issue is that the `lcov` dir is somehow counted as coverage diff
https://cockpit-logs.us-east-1.linodeobjects.com/pull-19156-20230801-065114-15e72e1d-fedora-38-devel/Coverage/lcov/index.html
