### ISSUE TITLE
"Not Found" upon opening web panel.

### ISSUE THREAD

**Issue by LunarN0v4** [cockpit-project/cockpit#19165]
### Explain what happens

Honestly, I just installed the FreedomBox software by accident and after uninstalling the firewalls and reinstalling Cockpit and purging a few times, it says "Not Found" when I open the panel on port 9090, same as #14897.

### Version of Cockpit

287-1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Debian

### Server operating system version

12 / Bookworm

### What browsers are you using?

Firefox

### System log

```shell
No logs at all.
However I can provide installed versions of Cockpit.
root@vps:~# dpkg -l | grep cockpi
ii cockpit 287-1 all Web Console for Linux servers
ii cockpit-bridge 287-1 amd64 Cockpit bridge server-side component
ii cockpit-doc 287-1 all Cockpit deployment and developer guide
ii cockpit-networkmanager 287-1 all Cockpit user interface for networking
ii cockpit-packagekit 287-1 all Cockpit user interface for packages
ii cockpit-pcp 287-1 amd64 Cockpit PCP integration
ii cockpit-sosreport 287-1 all Cockpit user interface for diagnostic reports
ii cockpit-storaged 287-1 all Cockpit user interface for storage
ii cockpit-system 287-1 all Cockpit admin interface for a system
ii cockpit-ws 287-1 amd64 Cockpit Web Service
```

**Comment by LunarN0v4** [comment]
Broken UrlRoot in config

**Comment by duncan-dommerdich-beebryte** [comment]
Hi,
My company is also using cockpit on its edge component and we are facing a similar issue
here is a screen shot of the report view after executing the command
  
![Image](https://github.com/user-attachments/assets/2f07ed41-baa9-4176-8ec1-33f0e22520c7)

the report was indeed created in the folder /var/tmp/sosreport-name-of-the-device but it doesn't show off
