### ISSUE TITLE
Easy way to install firmware

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1922]
Way down on the priority list probably, but filing here so I don't forget.
https://github.com/hughsie/fwupd/blob/master/README.md

**Comment by stefwalter** [comment]
> By default, any users are able to install firmware to removable hardware. The logic here is that if the hardware can be removed, it can easily be moved to a device that the user already has root access on, and asking for authentication would just be security theatre.

This doesn't work for servers, where physical access is restricted.

**Comment by stefwalter** [comment]
fwupd has the same dependency issues as PackageKit itself, bringing in all of GTK+, X dependencies etc.

**Comment by hughsie** [comment]
Well, the GTK dep will be brought in from appstream-glib, which we've still not found a solution for. I assume the real issue here is the gtk3 dep, rather than the gdk-pixbuf dep, right?

**Comment by stefwalter** [comment]
@hughsie gdk-pixbuf depends on libX11 ... so yes it is problematic as well.

In addition having libjpeg, libtiff, libjasper, libpng on servers is a bit odd. But not as problematic as X and GTK

**Comment by hughsie** [comment]
I've been sorting this out in rawhide. In f23 the only dep we pull by default is libpng which I think is a lot more palatable than what we have now.

**Comment by stefwalter** [comment]
I'll be moving this to the ideas page. @andreasn Are you okay with that? Or do you have a plan to work on this?

**Comment by stefwalter** [comment]
https://github.com/cockpit-project/cockpit/wiki/Ideas

**Comment by andreasn** [comment]
> Are you okay with that? Or do you have a plan to work on this?

No, not anytime soon. I think the roadmap has enough things on it as it is. I think it's fine on the Ideas page for now.
