### ISSUE TITLE
text channels drop frames with split UTF-8 multi-byte characters

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#19235]
Our tests occasionally fail with unexpected messages

    invalid non-UTF8 @data passed as text to web_socket_connection_send()

Today it happened [here](https://artifacts.dev.testing-farm.io/bef4337d-49f1-4670-8c28-1487b8f7aaad/) in `TestJournal.testAbrtReport`.  There is no other information about that, so we need to collect some instances to identify some patterns.

It may also help to actually show the data, so that we get a clue what happens.

 - [testAbrtReport rawhide on TF](https://artifacts.dev.testing-farm.io/bd093e0d-c09a-40ae-ad55-027006963065/)
 - [testAbrtReportCancel f38 on our CI](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19152-20230825-130641-f8cd4822-fedora-38-other/log.html#122)
 - [testAbrtSegv f38 on our CI](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19246-20230828-054020-5d786ab8-fedora-38-devel/log.html#288)
 - [testAbrtSegv f39 on our CI](https://cockpit-logs.us-east-1.linodeobjects.com/pull-5171-20230829-063656-e518ac35-fedora-39-other-cockpit-project-cockpit/log.html#123)
 - [testHiddenRaid on f39](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19254-20230829-091131-245b0fad-fedora-38-devel/log.html#188)

:arrow_up: By today (June 2024) the above logs are all gone, but https://github.com/cockpit-project/cockpit-podman/issues/1733 is a recent case with recent logs which is very easy to reproduce -- but it won't be any more in a few days. See below, @martinpitt  captured this bug in a unit test.

**Comment by martinpitt** [comment]
I ran

    for i in `seq 30`; do test/verify/check-system-journal TestJournal.testAbrtReport TestJournal.testAbrtDelete TestJournal.testAbrtReportCancel $RUNC || break; done

several times, and while I did find some other flakes, I never hit this issue.

**Comment by mvollmer** [comment]
I just got this on Arch:

```
/updates/updates.js: couldn't parse http-stream1 header payload: JSON data must be UTF-8 encoded
cockpit_web_response_queue: assertion 'self->complete == FALSE' failed
cockpit_web_response_queue: assertion 'self->complete == FALSE' failed
```

Maybe related?

https://cockpit-logs.us-east-1.linodeobjects.com/pull-5144-20230824-094601-66eef2ca-arch-other-cockpit-project-cockpit/log.html#141

**Comment by martinpitt** [comment]
I think it's unrelated, but don't take my word for it.

**Comment by mvollmer** [comment]
And again:

```
/system/services.css: couldn't parse http-stream1 header payload: JSON data must be UTF-8 encoded
cockpit_web_response_queue: assertion 'self->complete == FALSE' failed
cockpit_web_response_queue: assertion 'self->complete == FALSE' failed
```

https://cockpit-logs.us-east-1.linodeobjects.com/pull-19079-20230824-105223-f05215f3-arch-storage-bots-5147/log.html

This is with a new Arch image, so it might indeed be caused by that.

**Comment by martinpitt** [comment]
Interesting, I have an instance in [testHiddenRaid](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19254-20230829-091131-245b0fad-fedora-38-devel/log.html#188), so far all the others were in the ABRT tests. This happens often enough that I'll send a PR to ignore that message. We have enough instances now, no need to constantly break our CI with this.

**Comment by martinpitt** [comment]
Interestingly this very issue came back and currently hits us hard here: https://github.com/cockpit-project/cockpit-podman/issues/1733

It happens if some data source sends UTF-8, and the frame gets split in the middle of a multi-byte character. I have a unit test for this now in my [utf8-split branch](https://github.com/martinpitt/cockpit/tree/utf8-split). As pushed, it fails with
```
(test-server:231201): WebSocket-CRITICAL **: 07:39:15.715: invalid non-UTF8 @data passed as text to web_socket_connection_send()
cleaning up pid 231203
Trace/breakpoint trap (core dumped)
```
and the unit test just aborts as the web server goes away. When toning this down with
```diff
--- src/websocket/websocketconnection.c
+++ src/websocket/websocketconnection.c
@@ -1740,7 +1740,7 @@ web_socket_connection_send (WebSocketConnection *self,
       if (!g_utf8_validate (pref, prefix_len, NULL) ||
           !g_utf8_validate (payload, payload_len, NULL))
         {
-          g_critical ("invalid non-UTF8 @data passed as text to web_socket_connection_send()");
+          g_message ("invalid non-UTF8 @data passed as text to web_socket_connection_send()");
           return;
         }
       break;
```

then `pytest -k http` fails with

```
# test: split UTF8 frames {}
not ok 1 - correct response, expected: "initialfirst half é second halffinal", got: "initialfinal", test: split UTF8 frames, module: , source: at Function.<anonymous> (http://localhost:46513/qunit/base1/test-http.js:9517:85)
```
which is exactly the problem that we see in https://github.com/cockpit-project/cockpit-podman/issues/1733.

I'm not entirely sure what do do here -- it's tempting to just ditch `WEB_SOCKET_DATA_TEXT` and send everything as bytes, and don't care about UTF-8 in data streams, bridge, and webserver, until the very end in cockpit.js. But I suppose there were reasons to do it that way, so we need to fix the bridge to do some buffering and partial decoding of such frames.

@allisonkarlitskaya you seemed to have some idea/opinion about this?

**Comment by martinpitt** [comment]
I sent PR# 20628 to try and address this.
