### ISSUE TITLE
With "Limited access" the user can edit network interfaces' MAC addresses and can switch interfaces on/off

### ISSUE THREAD

**Issue by g-pape** [cockpit-project/cockpit#19242]
### Explain what happens

Since with "Limited access", i.e. not activating "Administrative access", the user cannot edit network interfaces' IPv4, IPv6, and MTU configuration, it feels natural that she also cannot edit MAC addresses and cannot switch interfaces on/off.

I suggest this change:

```
diff --git a/pkg/networkmanager/network-interface.jsx b/pkg/networkmanager/network-interface.jsx
index 2fbf2befa..94ff0b75b 100644
--- a/pkg/networkmanager/network-interface.jsx
+++ b/pkg/networkmanager/network-interface.jsx
@@ -215,7 +215,7 @@ export const NetworkInterfacePage = ({
             mac = iface.MainConnection.Settings.ethernet.assigned_mac_address;
         }

-        const can_edit_mac = (iface && iface.MainConnection &&
+        const can_edit_mac = (privileged && iface && iface.MainConnection &&
                               (connection_settings(iface.MainConnection).type == "802-3-ethernet" ||
                                connection_settings(iface.MainConnection).type == "bond"));

@@ -669,7 +669,7 @@ export const NetworkInterfacePage = ({
     */

     let onoff;
-    if (isManaged) {
+    if (privileged && isManaged) {
         onoff = (
             <Switch isChecked={!!(dev && dev.ActiveConnection)}
                     isDisabled={!iface || (dev && dev.State == 20)}
```

### Version of Cockpit

264

### Where is the problem in Cockpit?

None

### Server operating system

None

**Comment by martinpitt** [comment]
Indeed, at the moment this just results in an unsightly error:

![image](https://github.com/cockpit-project/cockpit/assets/200109/266bb5aa-feae-43ee-8f02-2a12c4e75ea8)

I'm fine with this patch -- polkit checks would be nicer, but that's a huge task -- and at least then we have all the places clearly marked with `if privileged`. Thanks, I'll create a PR and a test!

**Comment by martinpitt** [comment]
See PR #19741. Thanks!
