### ISSUE TITLE
Nightly tests did not succeed - bogus, bots error

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19269]
Tests failed on 4dadc7f45d31f7128d5f407353723256cc72be20

**Comment by martinpitt** [comment]
This looks like fallout from https://github.com/cockpit-project/bots/pull/5149. The `if not opts.pull_number` was apparently true (even though that should be part of https://github.com/cockpit-project/cockpit/pull/19268) and filed an issue for the failing test there.

**Comment by martinpitt** [comment]
> Command:       /bin/sh -c 'PRIORITY=0005 ./make-checkout --verbose --repo=cockpit-project/cockpit --rebase=main 4dadc7f45d31f7128d5f407353723256cc72be20 && cd make-checkout-workdir && TEST_OS=fedora-38 BASE_BRANCH=main COCKPIT_BOTS_REF=main TEST_SCENARIO=networking ../tests-invoke --revision 4dadc7f45d31f7128d5f407353723256cc72be20 --repo cockpit-project/cockpit'

This was a manually triggered test by @mvollmer. Calling bots/tests-trigger on the developer machine may not actually add a `--pull-number` argument or so?

**Comment by jelly** [comment]
I don't see how we can end up without `pull-number` seeing that the pull number is 0, `pull-0-20230901-074940` it seems we run into `elif sha` and not `else` ?! https://github.com/cockpit-project/bots/blob/main/tests-scan#L294 

So if that's true, which I think it is we need a *better* condition there.

```
Test name:     pull-0-20230901-074940
Command:       /bin/sh -c 'PRIORITY=0005 ./make-checkout --verbose --repo=cockpit-project/cockpit --rebase=main 4dadc7f45d31f7128d5f407353723256cc72be20 && cd make-checkout-workdir && TEST_OS=fedora-38 BASE_BRANCH=main COCKPIT_BOTS_REF=main TEST_SCENARIO=networking ../tests-invoke --revision 4dadc7f45d31f7128d5f407353723256cc72be20 --repo cockpit-project/cockpit'
```

**Comment by jelly** [comment]
https://github.com/cockpit-project/bots/commit/09c8fe48b74ee310209d15e0eeb8f0028586bf9e
