### ISSUE TITLE
Cockpit creating systemd timers with wrong execution times

### ISSUE THREAD

**Issue by watn3y** [cockpit-project/cockpit#19278]
### 1. Create a systemd timer 

<details>
<summary>Screenshot</summary>

![image](https://github.com/cockpit-project/cockpit/assets/64812615/fa9d6c2c-775a-4e22-8b0d-6904fd870d78)

</details>

### 2. The timer gets created with the wrong execution time 
<details>
<summary>Screenshot</summary>

![image](https://github.com/cockpit-project/cockpit/assets/64812615/a6feab48-7bf8-4a24-be1d-8a65ed42b23b)

</details>

**Content of /etc/systemd/system/test.timer**
```
[Unit]
Description=test
[Timer]
OnCalendar=*-*-* 00:00:00
[Install]
WantedBy=timers.target
```

### Version of Cockpit

299-1~bpo12+1 from bookworm-backports

### Where is the problem in Cockpit?

Services

### Server operating system

Debian

### Server operating system version

Debian 12 / Bookworm

### What browsers are you using?

Chrome

**Comment by jelly** [comment]
Thanks for the bug repot, I cannot reproduce this under Fedora-38

```[root@fedora-38-127-0-0-2-2201 ~]# systemctl cat bar.timer
# /etc/systemd/system/bar.timer
[Unit]
Description=bar
[Timer]
OnCalendar=*-*-* 05:30:00
[Install]
WantedBy=timers.target
[root@fedora-38-127-0-0-2-2201 ~]# cockpit -v
-bash: cockpit: command not found
[root@fedora-38-127-0-0-2-2201 ~]# cockpit-bridge -V
usage: cockpit-bridge [-h] [--privileged] [--packages] [--bridges] [--debug] [--version]
cockpit-bridge: error: unrecognized arguments: -V
[root@fedora-38-127-0-0-2-2201 ~]# cockpit-bridge --version
Version: 299.dev52+g84a57a82a.dirty
Protocol: 1
```

**Comment by jelly** [comment]
In what timezone are you located and what timezone does your server have? Just checking, but it might be related.

**Comment by autrera** [comment]
I'm having the same issue on an ubuntu server 22.04 and on an Manjaro machine. 

This only happens when creating a repeating timer. It doesn't matter what time I choose, the timer has the time at 00:00:00

I'm guessing that this is an issue in the frontend because the file is generated there and then sent through the socket.

![image](https://github.com/cockpit-project/cockpit/assets/36897576/c1acd3a4-d2fb-4076-946c-f761b747774c)

**Comment by martinpitt** [comment]
Ooh, this is subtle -- I tried this two times, one timer was correct, the other wrong. When I *type* the time, the created timer is correct (`OnCalendar=mon *-*-* 05:30:00`). When I open the dropdown, select the time, and then click on "Save", the time is wrong (`mon *-*-* 00:00:00`). It even stays wrong when I click on (i.e. focus) another element in between. So this is some bug in the PF date selector. I guess @watn3y and @autrera used the dropdown to select the time, and @jelly you typed it?
