### ISSUE TITLE
"Switch to administrative access" dialog bugs

### ISSUE THREAD

**Issue by subhoghoshX** [cockpit-project/cockpit#19288]
### Explain what happens

1. When dialog is canceled using `X` button there's no way to bring it back (without logging out and back in).

[Screencast from 2023-09-06 14-36-34.webm](https://github.com/cockpit-project/cockpit/assets/108616679/ae29d4bb-3f1c-449d-8f8f-1ea3c4c12f72)

### Version of Cockpit

main (299-61)

### Where is the problem in Cockpit?

None

### Server operating system

Fedora

### Server operating system version

Fedora-38

### What browsers are you using?

Brave

**Comment by subhoghoshX** [comment]
2. On `ubuntu-stable` (Ubuntu 23.04) the "Administrative access" becomes "Limited access" after a browser reload.

[Screencast from 2023-09-06 15-30-22.webm](https://github.com/cockpit-project/cockpit/assets/108616679/53a24e69-6b8a-4060-a5ff-d839d4a82836)

**Comment by ShivangRawat30** [comment]
I'll work on this issue

**Comment by jelly** [comment]
We initialize the superuser proxy which hides the switch button, normally this is cancelled by calling `cancel` but that does not happen in this scenario. (That's issue #1)

**Comment by subhoghoshX** [comment]
> 2. On `ubuntu-stable` (Ubuntu 23.04) the "Administrative access" becomes "Limited access" after a browser reload.
> 
>  Screencast.from.2023-09-06.15-30-22.webm

With today's cockpit update I see this issue on fedora-38 too now. Latest versions:
![image](https://github.com/cockpit-project/cockpit/assets/108616679/670eb216-d1d4-4163-9ea2-f2683a7b4d0d)
