### ISSUE TITLE
Network pixel flakes around the help icon

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19311]
Tests failed on 96ab01128de8f934723de5988da688d03f7242f5

**Comment by martinpitt** [comment]
See https://cockpit-logs.us-east-1.linodeobjects.com/pull-19310-20230911-101057-96ab0112-fedora-38-networking/log.html#6 . This has happened very often recently. @mvollmer can you please have a look?

**Comment by martinpitt** [comment]
Happened twice again, I'll send a PR.

**Comment by martinpitt** [comment]
https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20230912-012305-6283d5ca-fedora-38-updates-testing/log.html and https://cockpit-logs.us-east-1.linodeobjects.com/pull-19310-20230911-101057-96ab0112-fedora-38-networking/log.html#6
