### ISSUE TITLE
TestSystemInfo-testBasic-overview pixel flake on high CPU usage

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19322]
Tests failed on be26a9beea42e9cce8daee2c7296d559b669eec9

**Comment by martinpitt** [comment]
[pixel failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20230913-012453-be26a9be-fedora-38-updates-testing/pixeldiff.html#TestSystemInfo-testBasic-overview), unexpectedly high CPU usage made the progress bar wider than in the reference.

We could fix that by waiting until CPU usage drops below 20% or so. Keeping this open and retitling.

**Comment by martinpitt** [comment]
#19614 is a newer one for the same issue, let's keep that one.
