### ISSUE TITLE
Nightly tests did not succeed on fedora-38/updates-testing - breaks kdump

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19331]
Tests failed on c35ea0fa74b1080ccc95cc8748c04481f275c5d0

**Comment by martinpitt** [comment]
[The failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20230915-012456-c35ea0fa-fedora-38-updates-testing/log.html#45-2) feels real -- new kernel breaking kdump? /me invokes the pilot @jelly

**Comment by jelly** [comment]
```
[root@fedora-38-127-0-0-2-2201 ~]# ls -lh /srv/kdump/var/crash/
total 0
```

No crashdumps where made at all.

**Comment by jelly** [comment]
This will probably not fixed soon so let's add a naughty: https://github.com/cockpit-project/bots/issues/5263
