### ISSUE TITLE
Can Log In To Cockpit

### ISSUE THREAD

**Issue by JEMcats** [cockpit-project/cockpit#19342]
### Explain what happens

1. I get on to the website
2. Enter my credentials
3. Error failed to connect

### Version of Cockpit

I can't get into the web portal

### Where is the problem in Cockpit?

Accounts

### Server operating system

Ubuntu

### Server operating system version

Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-83-generic x86_64)

### What browsers are you using?

Safari macOS

### System log

```shell
cockpit-tls: gnutls_handshake failed: The TLS connection was non-properly terminated.
```

**Comment by martinpitt** [comment]
Please see https://cockpit-project.org/faq.html#blank-page-using-safari .
