### ISSUE TITLE
I like to report security issue please give me the contact to do so.

### ISSUE THREAD

**Issue by whitedevil1710** [cockpit-project/cockpit#19346]

**Comment by jelly** [comment]
(As the original text in the issue can still be seen, I'll reply here)

Cockpit uses PAM for authenticating users, and uses the standard distribution configuration for it. PAM can be configured to lock users after too many failed login attempts using faillock; some distributions have this configured by default.

Alternatively Cockpit offers [smart card](https://cockpit-project.org/guide/latest/cert-authentication) and [other kinds of authentication](https://cockpit-project.org/guide/latest/authentication.html).

We don’t see this as a Cockpit issue, as it depends on the distribution’s PAM configuration.
