### ISSUE TITLE
Nightly tests did not succeed on debian-stable/other

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19347]
Tests failed on 682c8725fa9db186113da1ddd4cb0ee7d8614a7a

**Comment by martinpitt** [comment]
Interesting, so this was for a PR, not from main? How come that this failed `if not api.has_open_prs(opts.revision) `, i. e. how exactly did you trigger this?

**Comment by jelly** [comment]
This is quite old and has not happened in a while, let's close it.
