### ISSUE TITLE
cockpit-po-plugin doesn't add `po/LINGUAS` to depends

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#19369]
Since the changes in 4bdbbbe058052e626dccc404536f39e50fc90caf, the `cockpit-po-plugin` doesn't add `po/LINGUAS` to the list of dependency files, even though it reads it.

This bug is extremely theoretical — nothing uses that list.  We no longer output the dependencies for use from our `Makefile` and even our built-in `./build.js --watch` mode just does a blanket recursive watch on `pkg/*` — even updating `.po` files themselves won't trigger a rebuild (despite them being on the list).

So maybe this is a way to start a discussion: do we care about tracking file dependencies at all?  If not, then we could remove some other code which does this.  If so, then we should probably fix this bug.

**Comment by martinpitt** [comment]
I don't care about LINGUAS -- it's always prone to be out of date. We don't use it in starter-kit and friends either, instead their Makefile does:
```
LINGUAS=$(basename $(notdir $(wildcard po/*.po)))
```

(and it then does some outdated creation of a temporary po/LINGUAS, but that's still from the time when our PO plugin couldn't do globbing).

Rebuilding on po file changes does seem worth fixing, though.

**Comment by allisonkarlitskaya** [comment]
The issue is (or at least, with `webpack-make`, was) that you need some file to act as a timestamp for noticing if translations get added/removed.  Simply dropping a new .po file in the directory wouldn't get picked up, otherwise.

That could happen if you do a `git pull` for example and a new translation got added, but nothing in `pkg/` changed.

**Comment by martinpitt** [comment]
TBH I don't mind watch mode etc. not working correctly when translations update. This happens so rarely in practice (as nobody edits .po files, they come via weblate) that I'd rather simplify our code than wasting complexity on such corner cases.

Personally I wouldn't mind dropping dependency tracking almost completely -- the only requirement that we have is that running `make` in a release tarball must not rebuild dist/ (to not break distro builds). Developers should run `./build.js` for iterating, not `make`. But I'm not sure if everyone in the team actually does that now, that may be a good Wednesday meeting topic? I'll add it to the agenda

**Comment by allisonkarlitskaya** [comment]
> But I'm not sure if everyone in the team actually does that now, that may be a good Wednesday meeting topic? I'll add it to the agenda

Right.  I wanted to start a conversation about if this is still appropriate for us at all.  Sounds good!

**Comment by allisonkarlitskaya** [comment]
So after the team meeting we decided:
 - the dependency list isn't so interesting
 - `./build.js -w` is really about hacking on `pkg/`
 - `make` should absolutely always produce an up-to-date result, regardless of what changed

That means that the thing that needs to be fixed here (in addition to perhaps removing some dependency tracking) is to add some extra inputs to the `PKG_INPUTS` variable in the makefile — at least for `po/*.po` and possibly for other things we haven't thought about yet...
