### ISSUE TITLE
client: Update to GNOME 45

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#19365]
Now that GNOME 45 has been released, GNOME 43 is no longer supported (as of today). Cockpit Client is currently using GNOME 43, so we need to update.

**Comment by garrett** [comment]
GNOME Software shows Cockpit like this now:

![image](https://github.com/cockpit-project/cockpit/assets/10246/9852e279-a34c-4fef-8787-ac942dab83ad)

![image](https://github.com/cockpit-project/cockpit/assets/10246/c58ca08c-5a48-45fa-918d-07d8df399c30)

So it'd be nice to handle this soon. :wink:

**Comment by allisonkarlitskaya** [comment]
We might also port to Gtk 4 while we're at it...
