### ISSUE TITLE
rpm: file conflicts on dist-info/RECORD and dist-info/direct_url.json

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#19373]
This breaks [rpmdeplint](https://artifacts.dev.testing-farm.io/ce5742b6-1319-4ccb-9d83-845f49cce304/) for cockpit:

> Undeclared file conflicts:
> cockpit-bridge-301-1.fc40.i686 provides /usr/lib/python3.12/site-packages/cockpit-301.dist-info/RECORD which is also provided by cockpit-bridge-301-1.fc40.x86_64
> cockpit-bridge-301-1.fc40.i686 provides /usr/lib/python3.12/site-packages/cockpit-301.dist-info/direct_url.json which is also provided by cockpit-bridge-301-1.fc40.x86_64
> cockpit-bridge-301-1.fc40.x86_64 provides /usr/lib/python3.12/site-packages/cockpit-301.dist-info/RECORD which is also provided by cockpit-bridge-301-1.fc40.i686
> cockpit-bridge-301-1.fc40.x86_64 provides /usr/lib/python3.12/site-packages/cockpit-301.dist-info/direct_url.json which is also provided by cockpit-bridge-301-1.fc40.i686

These contain the absolute build path and some noisy hashes, which breaks reproducible builds. That already broke Debian's reproducibility tests, and I just removed the whole dir in commit 60ba2ee263310.

@allisonkarlitskaya AFAIR you mentioned that some files there are important? As a middle-ground, could we either drop or clean up (seddery) at least these two problematic files, both in Fedora and in Debian?

**Comment by martinpitt** [comment]
Downloading from [koji](https://koji.fedoraproject.org/koji/buildinfo?buildID=2292843):
```
mkdir i386 64
curl -o- https://kojipkgs.fedoraproject.org//packages/cockpit/301/1.fc40/i686/cockpit-bridge-301-1.fc40.i686.rpm | rpm2cpio | cpio -idD i386
curl -o- https://kojipkgs.fedoraproject.org//packages/cockpit/301/1.fc40/x86_64/cockpit-bridge-301-1.fc40.x86_64.rpm | rpm2cpio | cpio -idD 64
```

direct_url.json is apparently about Python's "make wheel" being not reproducible, perhaps timestamps?

```diff
--- i386/usr/lib/python3.12/site-packages/cockpit-301.dist-info/direct_url.json	2023-09-22 09:20:41.811263526 +0200
+++ 64/usr/lib/python3.12/site-packages/cockpit-301.dist-info/direct_url.json	2023-09-22 09:22:10.706743577 +0200
@@ -1 +1 @@
-{"archive_info": {"hash": "sha256=96afecf740a917797efbed3c96370714bd9be1ffc7b246cdb408ccbb808dfba0", "hashes": {"sha256": "96afecf740a917797efbed3c96370714bd9be1ffc7b246cdb408ccbb808dfba0"}}, "url": "file:///builddir/build/BUILD/cockpit-301/tmp/wheel/cockpit-301-py3-none-any.whl"}
\ No newline at end of file
+{"archive_info": {"hash": "sha256=c432eab9aa512f0f8e16af731f0e5a676e6bb1e70de1295c047f6e9629ed18e5", "hashes": {"sha256": "c432eab9aa512f0f8e16af731f0e5a676e6bb1e70de1295c047f6e9629ed18e5"}}, "url": "file:///builddir/build/BUILD/cockpit-301/tmp/wheel/cockpit-301-py3-none-any.whl"}
\ No newline at end of file
```

RECORD is just transitive fallout from direct-url.json being different:
```diff
--- i386/usr/lib/python3.12/site-packages/cockpit-301.dist-info/RECORD	2023-09-22 09:20:41.811263526 +0200
+++ 64/usr/lib/python3.12/site-packages/cockpit-301.dist-info/RECORD	2023-09-22 09:22:10.706743577 +0200
@@ -6,7 +6,7 @@
 cockpit-301.dist-info/RECORD,,
 cockpit-301.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
 cockpit-301.dist-info/WHEEL,sha256=gT5nO6Xt8FXSldXJkcmc82um7kNcQnlMv-QhEedlzRg,92
-cockpit-301.dist-info/direct_url.json,sha256=FkUOQm2LX80lzgfFB9p_OU3YdKC8MZC127tdNd6SKOY,281
+cockpit-301.dist-info/direct_url.json,sha256=a5mYVfiiSll8-4ojpdm028p5T_QcMtykYFg3PjTMhco,281
 cockpit-301.dist-info/entry_points.txt,sha256=ONfzyD03bBkU0zNVeUdx62qTGK3bVdOsmzWRhp0_a_E,158
 cockpit/__init__.py,sha256=26Wdg9R3_Dwde7RuyBsrXvQLRuWLAveenLvYyWaIoq4,48
 cockpit/__pycache__/__init__.cpython-312.pyc,,
```

**Comment by allisonkarlitskaya** [comment]
Okay so this is really just about the `direct_url.json` file — the `RECORD` is a side-effect...

**Comment by allisonkarlitskaya** [comment]
This means that our wheel build is non-reproducable.  I guess that comes down to timestamps in the `.zip` file.  We should definitely fix that.
