### ISSUE TITLE
networking: TypeError on missing allowed-ips with manually imported WireGuard files

### ISSUE THREAD

**Issue by ne20002** [cockpit-project/cockpit#19384]
### Explain what happens

1. Updated to Cockpit 301
2. Try to load Network page -> endless spinner
3. A Wireguard configuration has been in place

### Version of Cockpit

301

### Where is the problem in Cockpit?

Networking

### Server operating system

Debian

### What browsers are you using?

Firefox

**Comment by ne20002** [comment]
![grafik](https://github.com/cockpit-project/cockpit/assets/39007279/e8abdbad-6fcf-4d5b-96c1-364a780cbd40)

**Comment by subhoghoshX** [comment]
I interpolated your wireguard config, with some fake data, like:
```
[Interface]
Address = 192.168.34.71/32, fd42:0:0:34::71/64
ListenPort = 1196
PrivateKey = +OIE0p31TCgYM7BIGyrxQXV6U9Uu/Y4ZWHZtXl6V/VI=

[Peer]
PublicKey = ajjiIGgER9BbZFSBEQsNeAT9QoqCzzRdkan7eruq4lQ=
PresharedKey = mGmuQJRKxQgL9JE7kElwAwF7eO7qmROv7QzJ575aDGQ=
AllowedIPs = 192.168.0.0/16, fd42::/48
Endpoint = 192.168.12.24:5433
```
and imported with in NetworkManager (`nmcli con import type wireguard file wg.conf`), I can't seem to reproduce the issue.

**Comment by ne20002** [comment]
Hmm
I never checked with NetworkManager. Just added the wireguard interface manually. That my be the issue. ;)
I test

**Comment by ne20002** [comment]
@subhoghoshX 
got it
I needed to set up/import  the connection with/into NetworkManager, disable my wg-quick@wg1 service and needed to fix the firewalld rules as (new) wg1 has been assigned to wrong zone.
Now the ui is working.

So: having a wireguard connection not defined by NetworkManager breaks the UI. Is this an issue?

**Comment by subhoghoshX** [comment]
@ne20002 yes, from the console error screen shot above it seems the the `allowed-ips` field was not set properly when configuring *externally*. NetworkManager (at least its dbus api) doesn't even allow creating a connection if some fields are wrong. For example, you might get an error of the form `wireguard.peers: failed to set property: peer #1 has invalid allowed-ips setting` when creating a connection.

But the issue remains, it shouldn't break the /network home page in Cockpit and I can reproduce it. At worst it should break only when editing the connection (or maybe it shouldn't even allow editing if it's managed *externally*).

I'll investigate it further. Thanks for reporting it @ne20002.

**Comment by martinpitt** [comment]
So what is the wireguard config that reproduces this? Like in @subhoghoshX 's https://github.com/cockpit-project/cockpit/issues/19384#issuecomment-1733205796 but with dropping the `AllowedIPs=` line?

**Comment by ne20002** [comment]
> So what is the wireguard config that reproduces this? Like in @subhoghoshX 's [#19384 (comment)](https://github.com/cockpit-project/cockpit/issues/19384#issuecomment-1733205796) but with dropping the `AllowedIPs=` line?

Just a wireguard connection defined manually and **not** with NetworkManager.
