### ISSUE TITLE
testOverMounting fails with: Error synchronizing after initial wipe: Timed out waiting for object

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19445]
Tests failed on 4edda8d87519afeb1530110ec75af99e196cd087

**Comment by martinpitt** [comment]
[testOverMounting](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231006-012520-4edda8d8-fedora-38-daily/log.html#210-2) failed three times in a row, with "Error synchronizing after initial wipe: Timed out waiting for object". @mvollmer, any idea?

**Comment by martinpitt** [comment]
[failed again last night](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231008-012748-170f0621-fedora-38-daily/log.html#210-2). Maybe this is actually a regression in updates-proposed?

**Comment by martinpitt** [comment]
Last night's failure: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231011-012449-9a18e43a-fedora-38-daily/log.html

**Comment by martinpitt** [comment]
We also see this failure [on main](https://artifacts.dev.testing-farm.io/f2fccf11-f2da-4886-b88d-bd63ca990b4d/), from https://github.com/cockpit-project/cockpit/pull/19281 . So this is *not* introduced in the daily COPRs.

**Comment by martinpitt** [comment]
This reproduces locally fairly well. Debugging tomorrow.

**Comment by martinpitt** [comment]
[debug run](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19476-20231013-092440-1cfdf967-fedora-38-daily-storage/log.html#70) shows one interesting thing in the journal:
```
Locked device /dev/sda1 (was unlocked as /dev/dm-0)
udisksd[5901]: Error re-reading partition table (BLKRRPART ioctl) on /dev/sda: Device or resource busy
udisksd[5901]: Error synchronizing after initial wipe: Timed out waiting for object
```
and the corresponding client D-Bus debug log:
```
> debug: dbus: {"call":["/org/freedesktop/UDisks2/block_devices/sda","org.freedesktop.UDisks2.Block","Format",["gpt",{"tear-down":{"t":"b","v":true}}]],"id":"133"}
> debug: dbus: {                                 
  "error": [                
    "org.freedesktop.UDisks2.Error.Failed",
    [    
      "Error synchronizing after initial wipe: Timed out waiting for object"
    ]
  ],
  "id": "133"
}
    
```

**Comment by martinpitt** [comment]
[settling udev](https://github.com/cockpit-project/cockpit/commit/45a9d81f8923f727c143bf08e43efb046b3ada87) [didn't help at all](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19476-20231013-121655-45a9d81f-fedora-38-daily-storage/log.html#78). Too bad, it was a really nice theory..

**Comment by martinpitt** [comment]
I finally have a CLI reproducer, reported at https://github.com/storaged-project/udisks/issues/1204 .

I'll send a naughty now.
