### ISSUE TITLE
Slow ... 

### ISSUE THREAD

**Issue by benjiro29** [cockpit-project/cockpit#19517]
### Explain what happens

OS: Debian bookworm, Intel n100, clean server install with only docker installed.

Login (Limited Access Account!).

Open the start page is extreme sloooooow. 20~30 second wait times. Try other pages, same, sometimes they are instantly as if cached, other times its slooooooow. Like 95% of the time, slow. 

htop shows 70% IO (Red) with 30% CPU being hit per core, with 1 to multiple cores at 100%. Depending on how many pages you click.

Logs show:

Tracing back to the first errors we find:

``` 
lib/cockpit/cockpit-certificate-helper: line 25: sscg: command not found
```

Installed sscg manually.
restarted cockpit with systemctl restart cockpit
Same issue ...

```
cockpit-tls[40611]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received
cockpit-tls[40611]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received
cockpit-tls[40611]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received
cockpit-tls[40611]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
systemd[1]: cockpit.service: Deactivated successfully.
systemd[1]: cockpit.service: Consumed 30.542s CPU time.
```

Sometimes when opening a page we get (translated because for some reason its in Dutch, when its a US keyboard + German location... Is Germany Dutch? Lucky i understand Dutch):

```
Er is een onverwachte fout opgetreden tijdens het verbinden met de machine.
Berichten met betrekking tot de fout zijn mogelijk te vinden in het journaal:

Translated:

An unexpected error occurred while connecting to the machine.
Messages related to the error may be found in the journal:
```

If you suffer a few times, new loads become a bit faster but in most cases it will still hit one or two cores with 100% utilization and 70 to 80% IO. 

Switch to Administrative access (using same user, sudo), Pages are fast. But that is a fakeout, what your seeing is just past pages already cached. Refreshing that data from cache and your back to IO hell...

That is all the info i can provide as there are no other errors etc. It feels like a DB issue more, like unoptimized tables with no proper index going. 

Note: This is on a 4TB NVME and system has over 11.5 / 12GB free memory .

### Version of Cockpit

301-1~bpo12+1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Debian

### Server operating system version

12

### What browsers are you using?

Edge

**Comment by allisonkarlitskaya** [comment]
It would be useful to see which processes are pinning the CPU/IO.

**Comment by jelly** [comment]
There are multiple issues in this issue so I'll just comment on the translation issues.

Cockpit does not determine the language based on the keyboard layout but on what your browser advertises via the [Accept Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) header. So based on your system's language / whatever you have configured in Edge.

The other option is that someone set the language on the browser before you as it's stored in localStorage:
```
window.localStorage.getItem('cockpit.lang') 
```

Can you successfully change your language using Cockpit's session menu or do you still get Dutch when you have German selected?

**Comment by benjiro29** [comment]
> Cockpit does not determine the language based on the keyboard layout but on what your browser advertises via the [Accept Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) header. So based on your system's language / whatever you have configured in Edge.

Seem Cockpit can not tell language priority from Edge because i checked my languages and they are English(US), English, German, Dutch (in that order, for page translations). I get the feeling that the language is selected alphabetically with Dutch being first in alphanumeric sorted.

**Comment by benjiro29** [comment]
> It would be useful to see which processes are pinning the CPU/IO.

Every time its /usr/lib/cockpit/cockpit-tls

That shows 100% CPU activity  with one or two process, owned by cockpit-ws

**Comment by benjiro29** [comment]
Update: The problem is related to using a ip to access cockpit

> https://192.168.178.20:9090

TLS problems, slow, 100% CPU usage, .... not usable.

> https://hostname:9090

Fast, no issues with this. In other words, the bug or issue is related how the TLS services is dealing with IP address vs (local)hostname.

**Comment by allisonkarlitskaya** [comment]
This is very strange.  `cockpit-tls` ought to be completely unaware of which name you're using to talk to it, so assuming the hostname resolves to the same IP address, there should be no difference here.

I'd love to see what cockpit-tls is doing.  Could you attach `strace` to it, or so?

**Comment by allisonkarlitskaya** [comment]
> Seem Cockpit can not tell language priority from Edge because i checked my languages and they are English(US), English, German, Dutch (in that order, for page translations). I get the feeling that the language is selected alphabetically with Dutch being first in alphanumeric sorted.

No such sorting happens inside of Cockpit, but it might be the case that your browser sorts the list and sends priorities that we're failing to interpret properly.  Can you find the exact content of the `Accept-Language` header that your browser is sending (from the network section in the inspector)?

Another possibility is that your language list contains "German (Germany)" (ie: `de-de`) but a generic "Dutch" (ie: `nl`).  The way we handle fallbacks might then find `nl` before `de-de`, because we don't have a specific `de-de` translation, but only a `de` one.

The fact that English wasn't considered first is probably our bug.  That might have been introduced in f4be9066c9d3f5dbad0316231b5ad98c117394cf when we dropped explicitly considering 'en' as being an empty translation.  I suspect the current code will look for the 'en' translation, fail to find it, and then move on to German.  I'll look into fixing that part today.

**Comment by allisonkarlitskaya** [comment]
Let's track the locale related parts of this issue in #19526, since they're well understood by now.

**Comment by allisonkarlitskaya** [comment]
@benjiro29 are you able to provide more information about the CPU usage part of this issue?  Do you need help with collecting the debugging information?
