### ISSUE TITLE
kpatch test failed on "packagekit crashed" browser error

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19519]
Tests failed on 54a27a6f11695f51fb26c6e637f02bfeb5d8d506, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231024-012507-54a27a6f-fedora-38-daily//log.html)

**Comment by martinpitt** [comment]
Interesting, that's fallout from our recent error message cleanup. On to the pile of OS bugs to look at...

**Comment by martinpitt** [comment]
I picked this up in my current "flakes" branch, but I'll try to mop up a few others at the same time.
