### ISSUE TITLE
missing patternfly

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#1951]
Recent commits to master seem to have resulted in missing patternfly.css on pages that don't use legacy css. Certainly affected: terminal, subscriptions

![screenshot from 2015-03-19 10 19 05](https://cloud.githubusercontent.com/assets/8711649/6727353/8e795e32-ce21-11e4-8835-b8cfedaaf261.png)
![screenshot from 2015-03-19 10 19 16](https://cloud.githubusercontent.com/assets/8711649/6727354/90e4382c-ce21-11e4-9350-9f247216e79b.png)

**Comment by dperpeet** [comment]
@stefwalter 

This might be due to https://github.com/cockpit-project/cockpit/commit/11ca545a0ba4b4848dc0744d32e7ff366f910a35#diff-0168dfe58de9654ebc171f3b804c18b5L11

Which patternfly are we supposed to include?

**Comment by stefwalter** [comment]
How did you install cockpit?

**Comment by dperpeet** [comment]
make install, I cleaned /usr/share/cockpit beforehand
