### ISSUE TITLE
direct: instance name lookup failed: disk.dev.write_bytes.3: Unknown or illegal instance identifier

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19568]
Tests failed on f959a07c6238e9ee55cf0abe642a86e53f8b91ff, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231106-012704-f959a07c-fedora-39-daily//log.html)

**Comment by martinpitt** [comment]
I've seen this several times in the last days. It feels like it always happened in `TestStorageLvm2.testDegradation`, but I don't have the previous logs any more.

> direct: instance name lookup failed: disk.dev.write_bytes.3: Unknown or illegal instance identifier

This message is from PCP, i.e. from generating the usage graphs. Most likely we should just ignore it, but I'll try to get some more information from it first.

**Comment by martinpitt** [comment]
I can't reproduce it locally even with 3 loops of tests, but it's actually fairly clear what happens. I'll send a PR.
