### ISSUE TITLE
Failed to start Security Auditing Service

### ISSUE THREAD

**Issue by Niaw** [cockpit-project/cockpit#19565]
### Explain what happens

Hi,

I have installed Cockpit in a Proxmox LXC (Linux container), the LXC is a clean Rocky Linux 9 from Proxmox official templates and the Cockpit web server is running well after installation, no error. Unprivileged container, nesting on.

After the first reboot, I had a problem with the auditd service:
Security Auditing Service -> /usr/lib/systemd/system/auditd.service

![auditd](https://github.com/cockpit-project/cockpit/assets/9696932/954d6be4-ae22-403a-91c4-a899e57c022e)

I suppose the problem comes from the container.

I tried to modify the /etc/audit/auditd.conf:
local_events = yes -> no
But same error after reboot.

Of course, the error doesn't show up if I disable the auditd service, but I don't know if Cockpit needs it.

So, if Cockpit doesn't need auditd.service, I will stick with the LXC, otherwise, I will install it in a VM.
In any case, if it is not a problem on my side, it may be a good idea to write this information in the documentation.

Thanks!

### Version of Cockpit

286.2

### Where is the problem in Cockpit?

Services

### Server operating system

CentOS

### Server operating system version

Rocky Linux 9.2

### What browsers are you using?

Firefox

### System log

```shell
Nov 04 22:43:11 cockpit systemd[1]: auditd.service: Scheduled restart job, restart counter is at 3.
Nov 04 22:43:11 cockpit systemd[1]: Stopped Security Auditing Service.
Nov 04 22:43:11 cockpit systemd[1]: Starting Security Auditing Service...
Nov 04 22:43:11 cockpit auditd[183]: Cannot change priority (Operation not permitted)
Nov 04 22:43:11 cockpit auditd[183]: The audit daemon is exiting.
Nov 04 22:43:11 cockpit systemd[1]: auditd.service: Control process exited, code=exited, status=1/FAILURE
Nov 04 22:43:11 cockpit systemd[1]: auditd.service: Failed with result 'exit-code'.
Nov 04 22:43:11 cockpit systemd[1]: Failed to start Security Auditing Service.
Nov 04 22:43:11 cockpit systemd[1]: auditd.service: Scheduled restart job, restart counter is at 4.
Nov 04 22:43:11 cockpit systemd[1]: Stopped Security Auditing Service.
Nov 04 22:43:11 cockpit systemd[1]: Starting Security Auditing Service...
Nov 04 22:43:11 cockpit auditd[184]: Cannot change priority (Operation not permitted)
Nov 04 22:43:11 cockpit auditd[184]: The audit daemon is exiting.
Nov 04 22:43:11 cockpit systemd[1]: auditd.service: Control process exited, code=exited, status=1/FAILURE
Nov 04 22:43:11 cockpit systemd[1]: auditd.service: Failed with result 'exit-code'.
Nov 04 22:43:11 cockpit systemd[1]: Failed to start Security Auditing Service.
Nov 04 22:43:12 cockpit systemd[1]: auditd.service: Scheduled restart job, restart counter is at 5.
Nov 04 22:43:12 cockpit systemd[1]: Stopped Security Auditing Service.
Nov 04 22:43:12 cockpit systemd[1]: auditd.service: Start request repeated too quickly.
Nov 04 22:43:12 cockpit systemd[1]: auditd.service: Failed with result 'exit-code'.
Nov 04 22:43:12 cockpit systemd[1]: Failed to start Security Auditing Service.
```

**Comment by martinpitt** [comment]
auditd can't work in a container, that subsystem isn't namespace aware. So this is a bug in the auditd package, the systemd service should have `ConditionVirtualization=!container` or so.

This isn't a cockpit bug, though -- cockpit doesn't care about auditd, but of course the Logs page will show the service status and journal.

**Comment by Niaw** [comment]
Hi Martin,
Thank you for this clarification.
Ok, great if Cockpit doesn't need it. I will investigate if this service was installed by default in Rocky Linux, or with a specified package.
I will simply disable it.

**Comment by Niaw** [comment]
I confirm "audit" is a dependancy of "cockpit".

![audit-dnf](https://github.com/cockpit-project/cockpit/assets/9696932/9306739d-7dd6-4f58-a8f7-11f7fd17c2da)

**Comment by martinpitt** [comment]
> I confirm "audit" is a dependancy of "cockpit".

Not quite -- `cockpit` recommends `setroubleshoot-server` (for the "SELinux" page) which requires audit. Disabling `auditd.service` is the correct fix for a container.

**Comment by Niaw** [comment]
Ok, I understand. Thank you Martin.
