### ISSUE TITLE
Error in storage after fresh install in proxmox and Cockpit

### ISSUE THREAD

**Issue by wojciechczyz** [cockpit-project/cockpit#19571]
### Explain what happens

This seems to be the same error as previously investigated yet not really solved by finding root cause:
https://github.com/cockpit-project/cockpit/issues/12412

1. Installed Proxmox
2. Installed Cockpit
3. when opening Storage tab getting error:
Error loading modules: Error opening directory “/usr/lib/x86_64-linux-gnu/udisks2/modules”: No such file or directory
CODE_FILE
udisksmodulemanager.c:226
_EXE
/usr/libexec/udisks2/udisksd

### Version of Cockpit

303-1~bpo12+1

### Where is the problem in Cockpit?

Storage

### Server operating system

other

### Server operating system version

Proxmox 8.0.4

### What browsers are you using?

Chrome

### System log

```shell
Error loading modules: Error opening directory “/usr/lib/x86_64-linux-gnu/udisks2/modules”: No such file or directory
CODE_FILE
udisksmodulemanager.c:226
CODE_FUNC
get_modules_list
GLIB_DOMAIN
udisks
```

**Comment by jelly** [comment]
We try to enable all udisks modules on startup so likely that causes this "error". But is anything broken or do you just get a log in your journal?

As far as Cockpit concerns there doesn't seem to be anything to act on.

**Comment by TCS-UK** [comment]
Same erro also happens with deb12 lxc containers

**Comment by jelly** [comment]
This just seems to be https://github.com/storaged-project/udisks/issues/1157 Tested on Ubuntu:

```

2:33 PM
Error loading modules: Error opening directory “/usr/lib/x86_64-linux-gnu/udisks2/modules”: No such file or directory
udisksd
2:32 PM
Error initializing module 'lvm2': /usr/lib/x86_64-linux-gnu/udisks2/modules/libudisks2_lvm2.so: cannot open shared object file: No such file or directory
udisksd
```

It's harmless
