### ISSUE TITLE
Services: misleading breadcrumbs navigation

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#1959]
In Services we have different categories to look at (Targets, System Services et al.).

When we click on an entry from any category, we go to a page with details. At the top of the page we have breadcrumbs to navigate back, but this will always lead do System Services again (as will the browser "back" key). This is misleading.

![screenshot from 2015-03-19 17 04 04](https://cloud.githubusercontent.com/assets/8711649/6734847/bc491508-ce5a-11e4-963c-f262e32bffc6.png)

I propose we fix these breadcrumbs until we have reworked the way we deal with services (#698, #82, #51)

**Comment by martinpitt** [comment]
This got fixed; going back on the breadcrumb now keeps the filter.
