### ISSUE TITLE
when generating SOS report plugin looks in /var/tmp/ while sos report creates it in /tmp 

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/cockpit#19617]
### Explain what happens

1. click on run report on the diagnostic report panel 
2. no report label  
3. clicked on run report on run new report dialog 

after the report has run i see no reports in the report list 

looked in the source code, the plugin looks for the sos reports in /var/tmp
while sos report itself creates them in /tmp (according /etc/sos/sos.conf)

from my pov, the plugin shoudl just override the sos report creation using --tmp-dir

### Version of Cockpit

303-1~bpo22.04.1

### Where is the problem in Cockpit?

Diagnostic Reports

### Server operating system

Ubuntu

### Server operating system version

22.04.03

### What browsers are you using?

Chrome

**Comment by jelly** [comment]
Replicated:
```
Your sosreport has been generated and saved in:
        /tmp/sosreport-ubuntu-2023-11-16-zlmbaly.tar.xz

 Size   223.95KiB
 Owner  root
 sha256 5a2e878498e1029d79bbb6edde7f8c2a228fba1af9dbaf1c087015ecde24e55c

Please send this file to your support representative.
```

In our tests we write our own `sos.conf` file which interestingly resets it to `/var/tmp` on Ubuntu. So we should read the configured dump path and show the correct one and also fix the test to not override the defaults from the OS.

**Comment by emaayan** [comment]
would 

> Replicated:
> 
> ```
> Your sosreport has been generated and saved in:
>         /tmp/sosreport-ubuntu-2023-11-16-zlmbaly.tar.xz
> 
>  Size   223.95KiB
>  Owner  root
>  sha256 5a2e878498e1029d79bbb6edde7f8c2a228fba1af9dbaf1c087015ecde24e55c
> 
> Please send this file to your support representative.
> ```
> 
> In our tests we write our own `sos.conf` file which interestingly resets it to `/var/tmp` on Ubuntu. So we should read the configured dump path and show the correct one and also fix the test to not override the defaults from the OS.

thanks, would this be backported to cockpits on 22.04 and 20.04 by any chance?

**Comment by jelly** [comment]
> would
> 
> > Replicated:
> > ```
> > Your sosreport has been generated and saved in:
> >         /tmp/sosreport-ubuntu-2023-11-16-zlmbaly.tar.xz
> > 
> >  Size   223.95KiB
> >  Owner  root
> >  sha256 5a2e878498e1029d79bbb6edde7f8c2a228fba1af9dbaf1c087015ecde24e55c
> > 
> > Please send this file to your support representative.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In our tests we write our own `sos.conf` file which interestingly resets it to `/var/tmp` on Ubuntu. So we should read the configured dump path and show the correct one and also fix the test to not override the defaults from the OS.
> 
> thanks, would this be backported to cockpits on 22.04 and 20.04 by any chance?

We do put Cockpit in backports, but this first needs a fix.

**Comment by martinpitt** [comment]
Indeed the default /etc/sos/sos.conf on Debian/Ubuntu has `tmp-dir = /tmp`. We should totally respect that in the tests and not stomp over it. That's also quite feasible to parse at runtime. I'll have a look at that.

**Comment by martinpitt** [comment]
Fedora's default /etc/sos/sos.conf does not set `tmp-dir`. I checked the [Debian packaging git](https://salsa.debian.org/sosreport-team/sosreport/-/tree/master) and nowhere does it set/patch/configure `tmp-dir`. But then I realized that this packaging git is *ancient* (4 years), apparently the recent uploads were all done without pushing git.

`apt-get source sosreport` gives it away:

```
❱❱❱ cat debian/patches/0001-debian-change-tmp-dir-location.patch 
Description: Change default location to /tmp
--- sos-4.0.orig/sos.conf
+++ sos-4.0/sos.conf
@@ -7,6 +7,7 @@
 #verify = yes
 #batch = yes
 #log-size = 15
+tmp-dir = /tmp
 
 [report]
 # Options that will apply to any `sos report` run should be listed here.
```
