### ISSUE TITLE
terminal problem

### ISSUE THREAD

**Issue by eafudd** [cockpit-project/cockpit#19626]
### Explain what happens

1. conect to host(local or others)
2. enter admin pw
3. openterminal wala everything is redacted (imput and output
4. 

### Version of Cockpit

current and four or five previous (fedoraOS

### Where is the problem in Cockpit?

Terminal

### Server operating system

Fedora

### Server operating system version

38&39

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
What do you mean with "everything is redacted"? Can you please post a screenshot?

Please also confirm this in a private window and try to disable extensions, to find out if one of them breaks it.

**Comment by martinpitt** [comment]
Any more info here?
