### ISSUE TITLE
bashism without shebang in /etc/profile.d

### ISSUE THREAD

**Issue by AeliusSaionji** [cockpit-project/cockpit#19628]
### Explain what happens

The following picture shows how the PackageKit.sh is sourced on every login, but through the wrong interpreter.

![image](https://github.com/cockpit-project/cockpit/assets/4342746/5d19cac8-ff39-49f9-9e0c-b18da7d699fb)

I'm not sure where this file comes from, I tried to look at my distro's package maintainer source files and these source files. Sorry if the problem originates elsewhere. At the very least, he name in the script comments does appear in this codebase.

```sh
$ pacman -Qo /etc/profile.d/PackageKit.sh
/etc/profile.d/PackageKit.sh is owned by packagekit 1.2.8-1
```

Running archlinux

### Version of Cockpit

305-1

### Where is the problem in Cockpit?

Terminal

### Server operating system

Arch Linux

### Server operating system version

x86_64 6.6.1-arch1-1

**Comment by martinpitt** [comment]
Please file that as bug report against packagekit in arch.
