### ISSUE TITLE
Installation on latest CoreOs during cosa builds

### ISSUE THREAD

**Issue by nicolaiunrein** [cockpit-project/cockpit#19642]
As far as I can tell cockpit is incompatible with the latest stable Fedora CoreOs (based on Fedora 39) since python is explicitly disabled in CoreOs. What is the recommended workaround for this? Also I think the install documentation should be updated since it is no longer working.

**Comment by martinpitt** [comment]
well, it's not "disabled", it's just not installed by default. You can easily do `rpm-ostree install --apply-live python3`. Which install instructions don't work? As far as I can see, both https://quay.io/repository/cockpit/ws and https://cockpit-project.org/running.html#coreos should still work. We run CI on current FCOS "testing" channel, which have been F39 based for a fair while.

**Comment by nicolaiunrein** [comment]
Oh, thats great new 👍. However what I was trying to do is build a custom CoreOs image with cockpit installed from the start. This worked until yesterday but is no longer working now because of this line: https://github.com/coreos/fedora-coreos-config/blob/4408116c16b993a9fb65adb2aae3d9d59b0c8ea8/manifests/fedora-coreos.yaml#L183
and the fact that cockpit now requires python. 
I wasn‘t aware that this only prevents installation during coreos-assembler builds. I will rename this issue. Any advice on how to include cockpit pre ignition would still be appreciated. The reason I chose to go this route is because I want clients to be able to install on bare metal without access to the internet. And I also want to make sure cockpit is always available. I am new to CoreOs/rpm-ostree/fedora so please apologise my ignorance 😂

**Comment by nicolaiunrein** [comment]
When you say you run CI on FCOS which workflow are you referring to? I would like to have a look but could not find it.

**Comment by martinpitt** [comment]
That python3 exclusion isn't new, it's been there for over 3 years. If you build a custom image, you somehow have to "unignore" python3 indeed. You may also be able to build from fedora-iot instead, which does have python3 even in the default install. This isn't something which we have influence on in the upstream cockpit project, I'm afraid.

**Comment by martinpitt** [comment]
> When you say you run CI on FCOS which workflow are you referring to? I would like to have a look but could not find it.

That's https://github.com/cockpit-project/bots/blob/main/images/scripts/ostree.setup#L27 . But it just uses `rpm-ostree install`. That really doesn't belong onto a custom image though, this is more of a hack than a proper solution.

**Comment by nicolaiunrein** [comment]
Thank you!
