### ISSUE TITLE
Browser too old check on Oracle Linux 8.8

### ISSUE THREAD

**Issue by schleicherdeha** [cockpit-project/cockpit#19646]
### Explain what happens

On Oracle Linux 8.8 the browser too old check message appears.
cockpit-300.1-1.0.1.el8_9.x86_64

### Where is the problem in Cockpit?

None

### Server operating system

other

### Server operating system version

Oracle Linux 8.8

### What browsers are you using?

Safari macOS

**Comment by jelly** [comment]
What browser do you use and what version?

**Comment by schleicherdeha** [comment]
It neither works with
Safari Version 17.1 (18616.2.9.11.9, 18616)
Chrome Version 119.0.6045.159 (Offizieller Build) (x86_64)
by the time of writing the latest Versions for my OS.

Message is: "fehlende selector(:is():where()))"

**Comment by jelly** [comment]
This comes from https://github.com/cockpit-project/cockpit/blob/main/pkg/static/login.js#L273 and is there since https://github.com/cockpit-project/cockpit/commit/29f6ecd58d33dc3caf25f73d54c06bda5b82604a so Cockpit 279.

So this all makes me wonder, if the shown Cockpit is actually 300? It also seems strange to have an el9 package on Oracle Linux 8.8? Then again I don't know much about Oracle Linux.

**Comment by schleicherdeha** [comment]
cockpit-300.1-1.0.1.el8_9.x86_64 is a package for Oracle 8.9 which actually runs on the system. I removed cockpit with
dnf remove cockpit
rebooted and installed it again with
dnf install cockpit
at least it works with chrome now.

**Comment by martinpitt** [comment]
Can you please check the version of `rpm -q cockpit-ws`? There's something very wrong here version 300.1 most definitively doesn't have `:is():where()`.

**Comment by schleicherdeha** [comment]
[root@lis3application ~]# rpm -q cockpit-ws
cockpit-ws-300.1-1.0.1.el8_9.x86_64

**Comment by martinpitt** [comment]
Thanks -- then I officially don't know what's up. This Cannot Happen™.

**Comment by schleicherdeha** [comment]
As it's working at least with chrome now, perhaps it's a weird caching problem at client side? I will close this.
