### ISSUE TITLE
System: datepicker doesn't always close

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#1964]
When manually setting system date/time

In Firefox: If I open the datepicker, resize the browser window (while datepicker is open) and then hit Escape, the dialog is closed but the datepicker remains open until I click somewhere inside the window.
This doesn't happen in Chrome.

**Comment by harishanand95** [comment]
@dperpeet was this fixed? I didn't get this issue when I tried it.

**Comment by martinpitt** [comment]
I can't replicate this on current versions either, and it seems it was already fixed in 2016 as per the last comment.
