### ISSUE TITLE
Nightly tests did not succeed on fedora-39/daily: iscsid SIGABRT on shutdown

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19661]
Tests failed on 564717f61abf1725188308c331359b38c70c9a10, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231128-012803-564717f6-fedora-39-daily//log.html)

**Comment by martinpitt** [comment]
The [journal](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231128-012803-564717f6-fedora-39-daily/TestStorageISCSI-testISCSI-fedora-39-127.0.0.2-2501-FAIL.log.gz) shows that iscsid timed out during shutdown, so systemd killed it, which caused that abort() message. Uninteresting, and doesn't seem to happen often enough. Closing for now, but retitling to make it possible to find and compare in the future if it happens more often. This is better tracked in the weather report.
