### ISSUE TITLE
Nightly tests did not succeed on fedora-39/updates-testing: TestStorageBasic.testBasic flaky pixels due to column widths

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19679]
Tests failed on f0b096151519c1764335f25569a9c4120b0facf3, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231202-012546-f0b09615-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment]
@mvollmer that pixel test failure is similar than the one from yesterday, although here the progress bars are visible. Could you please have a look? Sorry, pilot task list overflow, need a copilot.

**Comment by martinpitt** [comment]
[same failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231203-012917-f0b09615-fedora-39-updates-testing/log.html) last night.

**Comment by martinpitt** [comment]
Again [similar failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231204-012804-f0b09615-fedora-39-updates-testing/log.html) last night.

**Comment by mvollmer** [comment]
Yes, it was very naive to expect the whole overview to be stable, pixel-wise. I'll mock the sizes.
