### ISSUE TITLE
failed to parse public key for /var/cache/PackageKit/9.2/metadata on AlmaLinux 9.3

### ISSUE THREAD

**Issue by jamminjames** [cockpit-project/cockpit#19695]
### Explain what happens

1. When logged into the cockpit web console, some things don't work, eg, Software updates
2. The browser developer tools console shows that a file can't be found: `/cockpit/@localhost/*/po.js net::ERR_ABORTED 404`
3. Also getting: Refused to execute script from '/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
4. Also getting "FormSelect requires either an id or aria-label to be specified" for terminal.js
5. Also getting "Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'"."
6. After a long time, Software updates shows this: "failed to parse public key for /var/cache/PackageKit/9.2/metadata/nodesource-nsolid-9-x86_64.tmp/NODESOURCE-NSOLID-GPG-SIGNING-KEY-EL"

Looking in` /var/cache/PackageKit/9.2/metadata`, there is no "nodesource-nsolid..." listed. What should I do about this? I tried `dnf clean all` and `dnf check-update`, but no change.

I have nodejs installed, via `dnf module install nodejs`, so is `nodesource` redundant? Can I/should I uninstall it, and how?

Regarding the po.js MIME type, shouldn't it have a 'application/javascript' MIME type? JS files are listed that way in our nginx mime.types file, so why do I get this error? 

Why am I getting the CSP error for the inline style? Does cockpit have a CSP set somewhere? I didn't set one for the subdomain we're using for cockpit.

How should I address these errors? Thanks for any help.

### Version of Cockpit

300.1

### Where is the problem in Cockpit?

Software updates

### Server operating system

Red Hat Enterprise Linux

### Server operating system version

AlmaLinux 9.3

### What browsers are you using?

Chrome

### System log

```shell
Dec 05 01:16:01 localhost systemd[1]: Created slice User Slice of UID 0.
Dec 05 01:16:01 localhost systemd[1]: Starting User Runtime Directory /run/user/0...
Dec 05 01:16:01 localhost systemd[1]: Finished User Runtime Directory /run/user/0.
Dec 05 01:16:01 localhost systemd[1]: Starting User Manager for UID 0...
Dec 05 01:16:01 localhost systemd[3530357]: pam_unix(systemd-user:session): session opened for user root(uid=0) by (uid=0)
Dec 05 01:16:01 localhost systemd[3530357]: Queued start job for default target Main User Target.
Dec 05 01:16:01 localhost systemd[3530357]: Created slice User Application Slice.
Dec 05 01:16:01 localhost systemd[3530357]: Mark boot as successful after the user session has run 2 minutes was skipped b>
Dec 05 01:16:01 localhost systemd[3530357]: Started Daily Cleanup of User's Temporary Directories.
Dec 05 01:16:01 localhost systemd[3530357]: Reached target Paths.
Dec 05 01:16:01 localhost systemd[3530357]: Reached target Timers.
Dec 05 01:16:01 localhost systemd[3530357]: Starting D-Bus User Message Bus Socket...
Dec 05 01:16:01 localhost systemd[3530357]: PipeWire PulseAudio was skipped because of an unmet condition check (Condition>
Dec 05 01:16:01 localhost systemd[3530357]: Listening on PipeWire Multimedia System Socket.
Dec 05 01:16:01 localhost systemd[3530357]: Starting Create User's Volatile Files and Directories...
Dec 05 01:16:01 localhost systemd[3530357]: Listening on D-Bus User Message Bus Socket.
Dec 05 01:16:01 localhost systemd[3530357]: Finished Create User's Volatile Files and Directories.
Dec 05 01:16:01 localhost systemd[3530357]: Reached target Sockets.
Dec 05 01:16:01 localhost systemd[3530357]: Reached target Basic System.
Dec 05 01:16:01 localhost systemd[3530357]: Reached target Main User Target.
Dec 05 01:16:01 localhost systemd[3530357]: Startup finished in 212ms.
Dec 05 01:16:01 localhost systemd[1]: Started User Manager for UID 0.
Dec 05 01:16:01 localhost systemd[1]: Started Session 54383 of User root.
Dec 05 01:16:01 localhost CROND[3530373]: (root) CMD (cd /var/www/subs.humortimes && vendor/bin/crunz schedule:run >/dev/n>
Dec 05 01:16:01 localhost CROND[3530354]: (root) CMDEND (cd /var/www/subs.humortimes && vendor/bin/crunz schedule:run >/de>
Dec 05 01:16:01 localhost systemd[1]: session-54383.scope: Deactivated successfully.
Dec 05 01:16:11 localhost systemd[1]: Stopping User Manager for UID 0...
Dec 05 01:16:11 localhost systemd[3530357]: Activating special unit Exit the Session...
Dec 05 01:16:11 localhost systemd[3530357]: Stopped target Main User Target.
Dec 05 01:16:11 localhost systemd[3530357]: Stopped target Basic System.
Dec 05 01:16:11 localhost systemd[3530357]: Stopped target Paths.
Dec 05 01:16:11 localhost systemd[3530357]: Stopped target Sockets.
Dec 05 01:16:11 localhost systemd[3530357]: Stopped target Timers.
Dec 05 01:16:11 localhost systemd[3530357]: Stopped Daily Cleanup of User's Temporary Directories.
Dec 05 01:16:11 localhost systemd[3530357]: Closed D-Bus User Message Bus Socket.
Dec 05 01:16:11 localhost systemd[3530357]: Closed PipeWire Multimedia System Socket.
Dec 05 01:16:11 localhost systemd[3530357]: Stopped Create User's Volatile Files and Directories.
Dec 05 01:16:11 localhost systemd[3530357]: Removed slice User Application Slice.
Dec 05 01:16:11 localhost systemd[3530357]: Reached target Shutdown.
Dec 05 01:16:11 localhost systemd[3530357]: Finished Exit the Session.
```

**Comment by jamminjames** [comment]
Turns out some of this was being caused by our Content Security Policy (CSP). I added those scripts to it, and now they are loading okay. However, I am still getting the MIME issue for po.js.

I'm also getting `Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"` for the updates.js file.

Also getting `failed to poll tuned be {problem: 'disconnected', name: null, message: 'Server has closed the connection.', toString: ƒ}` for overview.js.

**Comment by martinpitt** [comment]
Hello @jamminjames,

your points 1. to 5. as well as the tracer/tuned messages are indeed known, but harmless noise. They happen everywhere, and some of them are fixed in newer versions.

The real issue is number 6, but that's somewhere between PackageKit, dnf, and your or Alma's /etc/yum.repos.d/ configs. You should see similar errors with `pkcon refresh` and `pkcon get-updates`, can you please check?

**Comment by martinpitt** [comment]
>  Where does cockpit add its own CSP?

That happens in the manifests, see https://cockpit-project.org/guide/latest/packages.html#package-manifest . We want to be very strict, as the JS code running on these pages has a lot of privileges.

**Comment by jamminjames** [comment]
re: My issue #6, it's been a while now, sorry I forgot to come back here and post my solution. I think I just had to delete that package source. It's fine now.
