### ISSUE TITLE
Allow configurable port for cockpit on CoreOS (installed as a container using runlabel)

### ISSUE THREAD

**Issue by soubinan** [cockpit-project/cockpit#19701]
Page: https://cockpit-project.org/running.html#coreos

Context:
---

Currently we can only use the 9090 default port on coreos

Neither `podman runlabel RUN` nor `podman runlabel INSTALL` allows to do so
If we want to configure the port we have to run into unpriviledged mode and redo many things manually (not what we want)

PS: Using the listen.conf file don't work (ref here: https://cockpit-project.org/guide/latest/listen)

Feature request:
---

There are many options:

1. Use the listen.conf file to configure the port (will be mapped automatically)
2. Provide a volume mount we could use to add our configurations

I hope I missed something and this issue have already a solution, if so please let me know

**Comment by martinpitt** [comment]
`listen.conf` is not a thing for the container -- that's a systemd socket unit configuration, and that's not involved at all in the container. But what you can do easily is to tell cockpit-ws in the container via a CLI option. Both `podman container runlabel` and the containers `label-run` script plumb through additional args:
```sh
podman container runlabel --name cockpit-ws RUN quay.io/cockpit/ws -- -p 9999
```

But this isn't obvious indeed -- I'll update the documentation accordingly.

**Comment by soubinan** [comment]
Thank's, I did something similar but wihtout the run_label
Actually I didn't know -p was usable there
Thanks very much for your update
