### ISSUE TITLE
One thing: Would be good to update doc/guide/packages.xml but that could be a follow-up.

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#19720]
> One thing: Would be good to update doc/guide/packages.xml but that could be a follow-up.

_Originally posted by @martinpitt in https://github.com/cockpit-project/cockpit/issues/19716#issuecomment-1847322962_

**Comment by martinpitt** [comment]
Grabbing, as I am about to send a doc update PR anyway. I'll let you review.
