### ISSUE TITLE
storage: Missing margin when no overview row has an icon

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#19736]
Only the OVerview table shows icons, but when there are none, the left side of the table is missing its margin.

![image](https://github.com/cockpit-project/cockpit/assets/3228183/f1283763-3091-4d42-81aa-0acfa02effa7)

The table should be aligned with the card header:

![image](https://github.com/cockpit-project/cockpit/assets/3228183/f4515bea-6e01-46fe-ac4c-f86c52a57695)

**Comment by garrett** [comment]
1. Should loop have an icon?
2. Are there any other types that don't have an icon?
3. Should there be a generic icon?

**Comment by garrett** [comment]
Are we using drive-removable-media-symbolic yet? Would that work as a generic enough icon in this case?
![drive-removable-media-symbolic](https://github.com/cockpit-project/cockpit/assets/10246/ab0232b5-5724-4e94-a734-0d11216dcc07)

Alternatively, if we want to get more specific: technically, loopback is a file that's mounted, so it could be:

text-x-generic-symbolic
![text-x-generic-symbolic](https://github.com/cockpit-project/cockpit/assets/10246/055e6ee6-1264-4a38-a115-3d8347b44f1a)

emblem-documents-symbolic
![emblem-documents-symbolic](https://github.com/cockpit-project/cockpit/assets/10246/2ae71299-b6c5-49ba-9537-2d197a99951e)

**Comment by mvollmer** [comment]
> 1. Should loop have an icon?
> 2. Are there any other types that don't have an icon?
> 3. Should there be a generic icon?

Good questions. We could give each top-level thing an icon, which would fix this issue here. Non-toplevel entries don't have icons to keep them visually distinct, but there will of course always be at leat one top-level entry.

So the current top-level types and their icons:

 - iscsi session, network-wired-symbolic
 - hdd or unknown, drive-harddisk-symbolic
 - ssd, drive-harddisk-solidstate-symbolic
 - media, drive-removable-media-symbolic
 - lvm2 volume groups, drive-multidisk-symbolic
 - mdraids, drive-multidisk-symbolic
 - stratis pools, drive-multidisk-symbolic
 - nfs mounts, network-wired-symbolic
 - generic "block device", used for everything else, no icon

So only the generic case doesn't have an icon currently. Cockpit doesn't currently know about loopbacks specifically, but it might in the future.

Since we already fall back to drive-harddisk-symbolic for "generic" drives, what about using it also for generic block devices?

**Comment by garrett** [comment]
> Since we already fall back to drive-harddisk-symbolic for "generic" drives, what about using it also for generic block devices?

`drive-harddisk-symbolic` should _not_ be used for generic disks. It specifically has cylindars and a head for reading. (It's abstract, but there.)

**Comment by garrett** [comment]
I modified the icon to make it just the rectangle, removing the platters:

![drive-harddisk-symbolic-generic](https://github.com/cockpit-project/cockpit/assets/10246/22663fad-2a52-4f63-8500-e0f88f32e99e)

WDYT?

**Comment by mvollmer** [comment]
> WDYT?

Yes, looks good to me. Thanks!
