### ISSUE TITLE
Disabled real name editing

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#1974]
When you don't have permission to edit a users real name we disable the field.

When it's your own name you get a tooltip telling you can't edit if you type anyways you get an error. When it is someone else's account, you get no tooltip just a cancel icon on hover and you are unable to type in the field.

We can't have the tooltip and the completely disabled field at the same time. But i think they should both be the same. Which way do we think is preferable.

**Comment by stefwalter** [comment]
I think we figured out how to have a disabled field and a tooltip, rigth?

**Comment by userimack** [comment]
Hii I would like to work on this?

**Comment by dperpeet** [comment]
> Hii I would like to work on this?

That would be great! How do you think the ui should behave in the different use cases? You can discuss this here and/or open a pull request with code that shows your implementation.

**Comment by userimack** [comment]
ok I will make a pull request @dperpeet

**Comment by Sagar-AArya** [comment]
@dperpeet Is this still open?

**Comment by larskarlitski** [comment]
> I think we figured out how to have a disabled field and a tooltip, rigth?

We have and this works in current versions of Cockpit. Feel free to reopen if anyone's still seeing this issue.
