### ISSUE TITLE
cockpit behind nginx on subpath redirects to login after logging in

### ISSUE THREAD

**Issue by marcusfey** [cockpit-project/cockpit#19753]
### Explain what happens

1. configure nginx (docker) and cockpit for cockpit to be accessible on `http://epsilon/cockpit` (or any server)
2. open configured URL in browser -> login form opens
3. enter wrong credentials -> redirect to login page with message "bad username or password" - GREAT
4. enter correct credentials -> "instant" redirect to login page without message

nginx.conf:
```
   location /cockpit/ {
        proxy_pass         https://<servers-main-ipv4-addr>:9090/cockpit/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Required for web sockets to function
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Pass ETag header from Cockpit to clients.
        # See: https://github.com/cockpit-project/cockpit/issues/5239
        gzip off;
    }
```

cockpit.conf:
```
[WebService]
Origins = https://epsilon:9090 wss://epsilon:9090 https://epsilon.fritz.box:9090 wss://epsilon.fritz.box:9090
ProtocolHeader = X-Forwarded-Proto
ForwardedFor   = X-Forwarded-For
UrlRoot=/cockpit
```

Browser network log:
![grafik](https://github.com/cockpit-project/cockpit/assets/6460821/f392627f-c0e7-48e2-ad5e-e4fb6ebf91d2)

`journalctl -u cockpit` contains nothing.

`journalctl -f` looks good, I can see my successful login, also I see
```
Dec 16 12:56:18 epsilon polkitd[1039]: Registered Authentication Agent for unix-session:235 (system bus name :1.588 [cockpit-bridge], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
...
Dec 16 12:56:33 epsilon polkitd[1039]: Unregistered Authentication Agent for unix-session:235 (system bus name :1.588, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
```
the gap from :18 to :33 is only related to a single login attempt.

I can log-in using `https://epsilon:9090/cockpit`

### Version of Cockpit

287-1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Debian

### Server operating system version

Debian GNU/Linux 12 (bookworm)

### What browsers are you using?

Firefox, Chrome

**Comment by goatfanboi23** [comment]
According to [https://cockpit-project.org/guide/latest/cockpit.conf.5.html](url) in the `UrlRoot` section, "/cockpit/ and /cockpit+ are reserved and should not be used". I would first try changing the `location` block and `UrlRoot` variable in your `cockpit.conf` and see if your issue persists

**Comment by marcusfey** [comment]
Thanks! I didn't know that. It works now.
