### ISSUE TITLE
Layout problem with new storage view

### ISSUE THREAD

**Issue by ne20002** [cockpit-project/cockpit#19767]
### Explain what happens

![grafik](https://github.com/cockpit-project/cockpit/assets/39007279/77f3d977-3648-484c-876c-d0f1f395bffb)

### Version of Cockpit

307

### Where is the problem in Cockpit?

Storage

### Server operating system

Debian

### Server operating system version

12.3

### What browsers are you using?

Firefox

**Comment by salmanansari14** [comment]
Hello!
I want to fix this bug!

**Comment by MadhavKrishanGoswami** [comment]
Can you give more info where is this issue exactly ?

**Comment by ne20002** [comment]
This is a part of the new storage page. It shows a row with a device with a long Id, breaking the layout.

**Comment by MohdMohsin97** [comment]
The layout breaks because of the long ID, but it works with small words. Should I break the ID in half or remove it? What do you suggest? ![Screenshot from 2024-01-08 15-16-52](https://github.com/cockpit-project/cockpit/assets/136162998/7ec23f16-e0e6-4c46-9818-b61f56a49439)

**Comment by MohdMohsin97** [comment]
Implemented the turncate on the line. Want to change anything like number of visible letters at the end?
![Screenshot from 2024-01-09 14-33-22](https://github.com/cockpit-project/cockpit/assets/136162998/b8c98ec2-f89b-465f-b0d0-b48bf9eec61c)
[Screencast from 09-01-24 02:28:24 PM IST.webm](https://github.com/cockpit-project/cockpit/assets/136162998/7e616dfd-9f6c-474b-a969-d42bb3c31a14)

**Comment by garrett** [comment]
Yeah, we'd either want to truncate it or make it force wrap. 

Do people need to see the full ID and possibly copy it? If so, then we should go with force wrap. Truncation and tooltip only makes sense when people can read and understand something when the item is hovered or focused.

**Comment by ne20002** [comment]
In the old version the id has been wrapped. But truncate is ok, it is not very impoirtant information as long as one can identify the device with the first part of the id.

**Comment by MohdMohsin97** [comment]
Can you assign this issue to me?
