### ISSUE TITLE
Nightly tests did not succeed on fedora-39/updates-testing: IPv6 regression in libssh 0.10.6

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19772]
Tests failed on 5a872683db3d00a27064d24ab7e1011b7fd46baa, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231222-012624-5a872683-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment]
Hmm, [IPv6 regression](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231222-012624-5a872683-fedora-39-updates-testing/log.html#182-2) or flake? I don't remember this being flaky. Retrying.

**Comment by martinpitt** [comment]
Triggered on commit d90a4645f0c13ea268de270946f9139db46172ea

**Comment by Jakuje** [comment]
This is a bug in libssh. We are looking into that ...

**Comment by Jakuje** [comment]
I think it should be fixed with https://gitlab.com/libssh/libssh-mirror/-/merge_requests/431 Do you have a simple way to verify the fix? I will likely update fedora later today.

**Comment by martinpitt** [comment]
Thanks @Jakuje ! I wasn't even aware that you monitored the nightly builds, thanks for picking this up! I responded in the libssh MR.

packit supports GitLab  these days, so in theory it should be possible to run the unit and some of cockpit's integration tests (which can run on the Testing Farm) there. But that's something to be discussed in January, after PTO season.

**Comment by martinpitt** [comment]
Fix got uploaded: https://bodhi.fedoraproject.org/updates/FEDORA-2023-733d984cc3 It'll need some time to land in updates, but from tomorrow on at least the /updates-testing nightly run ought to succeed again.

**Comment by martinpitt** [comment]
Last night's /updates-testing run is happy again.
