### ISSUE TITLE
TestAccounts.testBasic shows "Disallow interactive password" with minus-ed checkbox

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19787]
Tests failed on e70b470c1ef028b91484f90e762aa108735621f4, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231227-012539-e70b470c-fedora-39-daily/log.html)

**Comment by martinpitt** [comment]
Wow, what a weird regression -- I didn't even know that our checkboxes could do that!

**Comment by martinpitt** [comment]
This hasn't come back, let's sweep it under the rug; PTO season, too rare and obscure, and not reproducible.

**Comment by martinpitt** [comment]
It happened again in #19797, [log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240102-012702-5060e25b-fedora-39-daily/log.html)

**Comment by subhoghoshX** [comment]
I haven't looked into it, but the most probable reason is that the default state is `null` i.e. `const [checked, setChecked] = useState(null)`. As there is only one checkbox having the default value to `false` or just empty (or `undefined`) is probably better.

In PF checkbox:
no selected -> `false`
selected -> `true`
intermediate -> `null`

**Comment by martinpitt** [comment]
Also happened in a PR: [log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19804-20240103-092556-77bd8309-fedora-39-other/pixeldiff.html#TestAccounts-testBasic-user-detail-page)

**Comment by martinpitt** [comment]
I think it's more or less legit to use `null` there as an explicit "uninitialized/don't know" value. Fixed in #19805
