### ISSUE TITLE
TestAccounts.testBasic pixel flake with checkbox

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19822]
Tests failed on 254969f6cfefb6df33f0c2ad2d8e4224663e208e, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240108-012830-254969f6-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment]
Wah wah [what](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240108-012830-254969f6-fedora-39-updates-testing/pixeldiff.html#TestAccounts-testBasic-user-detail-page-medium)? This was supposed to be fixed with #19805

**Comment by martinpitt** [comment]
[Failed again last night](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240115-012940-d742ae04-fedora-39-daily/log.html)

**Comment by jelly** [comment]
Debug attempt: https://github.com/cockpit-project/cockpit/pull/19971

**Comment by jelly** [comment]
A development build reload of the page actually reproduces this issue:

![image](https://github.com/cockpit-project/cockpit/assets/67428/cdbfc8fa-f121-447e-9ecc-43f1d97e36fc)

**Comment by jelly** [comment]
Hit it again with rhel4edge in testExpire:



![Image](https://github.com/cockpit-project/cockpit/assets/67428/4af8697e-b295-4190-923f-19299ad0122b)
