### ISSUE TITLE
[cockpit-storaged] shows blank page

### ISSUE THREAD

**Issue by ykevinnow** [cockpit-project/cockpit#19848]
### Explain what happens

1. env: Fedora Server 39, the Web admin console
2. all works well but the "storage" sub-page, it shows blank(nothing)
3. 
![cockpit-storaged](https://github.com/cockpit-project/cockpit/assets/7316163/51ba7fd4-5727-4505-a689-cc0b5561fd83)

[Updated]
1. Version info
### Version of Cockpit

cockpit-storaged-307-1.fc39.noarch

### Where is the problem in Cockpit?

Storage

### Server operating system

Fedora

### Server operating system version

Fedora Server 39

### What browsers are you using?

Chrome

**Comment by jelly** [comment]
307 is the latest version in Fedora, do you mind trying that? As the storage page got a big overhaul.

**Comment by ykevinnow** [comment]
My apologies: the version should be "cockpit-storaged-307-1.fc39.noarch", so it seems to be the latest version. And that issue is still open.
Need your help.

**Comment by ykevinnow** [comment]
F.Y.I, and 304 works fine.

**Comment by thezedt** [comment]
Hi,

I'm seeing the same on a CentOS Stream 8:
![image](https://github.com/cockpit-project/cockpit/assets/96701648/80bed9c2-3cd3-47e5-a263-1c7b923a298c)

The issue appeared after the latest packages update which seems to have installed the (same) 307-1
```
Installed Packages
Name         : cockpit-storaged
Version      : 307
Release      : 1.el8
Architecture : noarch
Size         : 890 k
Source       : cockpit-appstream-307-1.el8.src.rpm
```
Browser: Firefox

Reverting to ```306-1.el8``` was sufficient for me to get the Storage section working again.

**Comment by jelly** [comment]
> Hi,
> 
> I'm seeing the same on a CentOS Stream 8: ![image](https://private-user-images.githubusercontent.com/96701648/297912068-80bed9c2-3cd3-47e5-a263-1c7b923a298c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NDEyNTcsIm5iZiI6MTcwNTk0MDk1NywicGF0aCI6Ii85NjcwMTY0OC8yOTc5MTIwNjgtODBiZWQ5YzItM2NkMy00N2U1LWEyNjMtMWM3YjkyM2EyOThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDE2MjkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3N2NjZTc4ZDFkZjdjNGQxMjM3ZWYwOTk1MGQ4Y2IxOWIzYzBhODQ4NTI2OTJkYjRhMDNjYTljNmY2MGNjYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yjYJxPHIsz0h0nNpHCR94swhG5VfDhsnWeDzGGP0ieo)
> 
> The issue appeared after the latest packages update which seems to have installed the (same) 307-1
> 
> ```
> Installed Packages
> Name         : cockpit-storaged
> Version      : 307
> Release      : 1.el8
> Architecture : noarch
> Size         : 890 k
> Source       : cockpit-appstream-307-1.el8.src.rpm
> ```
> 
> Browser: Firefox
> 
> Reverting to `306-1.el8` was sufficient for me to get the Storage section working again.

Do you have any interesting disk or filesystem setup? That would help us a lot to figure out the issue.

**Comment by thezedt** [comment]
> 
> Do you have any interesting disk or filesystem setup? That would help us a lot to figure out the issue.
> 

Just some mdraid devices, nothing too interesting (screenshot with 306-1):
![image](https://github.com/cockpit-project/cockpit/assets/96701648/4bac9fbc-bdb4-4b10-ba66-6d1faed66be8)


> Looking at the code there is one `toSorted`:
> 
> ```
> pkg/storaged/pages.jsx:        return things.toSorted((a, b) => page_compare(accessor(a), accessor(b)));
> ```
> 
> So likely `things` is not an Array which can be from either `crossrefs` or `pages` which makes it very hard to figure out.
> 
> @thezedt if you are willing to install a debug build of cockpit-storaged, I can make one and we can likely figure out what is wrong (and fix it in the next release).

Yes, I can do that if a more detailed debug log will help out.

**Comment by jelly** [comment]
@thezedt thanks for being willing to test, I've build packages with some debug logging here: https://copr.fedorainfracloud.org/coprs/packit/cockpit-project-cockpit-19878/build/6943386/

**Comment by ykevinnow** [comment]
Sorry, the issue is still open in cockpit-309-1.fc39.x86_64.

**Comment by jelly** [comment]
> Sorry, the issue is still open in cockpit-309-1.fc39.x86_64.

Hi, we would love to fix it but we are unable to reproduce it our self.  Can you describe more about your test setup or try the build with debug logs:

> @thezedt thanks for being willing to test, I've build packages with some debug logging here: https://copr.fedorainfracloud.org/coprs/packit/cockpit-project-cockpit-19878/build/6943386/

**Comment by thezedt** [comment]
> @thezedt thanks for being willing to test, I've build packages with some debug logging here: https://copr.fedorainfracloud.org/coprs/packit/cockpit-project-cockpit-19878/build/6943386/

Sorry about the delay, things piled up...

I installed the debug 309 build (for the `cockpit-storaged` package only) and I can see a lot of debug data in the browser's console now. However, I'm not sure how to retrieve and upload that information here (copy/paste or save as file only saves the top level messages, not the objects structure).
Trying to enable debug logging [according to the documentation](https://github.com/cockpit-project/cockpit/blob/main/HACKING.md#debug-logging-of-cockpit-processes) doesn't appear to generate any results either - there's nothing extra showing up in the system log.  

Interestingly enough, while looking for ways to save from the console I found that the storage module works fine in Chrome and Edge, it's only on my **older version** of Firefox that it fails. Testing with the latest 122 Firefox showed that the storage module works fine there too. 

![image](https://github.com/cockpit-project/cockpit/assets/96701648/6dbf545f-5144-4b71-a611-c221cbc1117c)

This should teach me to remember to test with the latest before reporting issues :flushed:
It would be interesting to see if the others reporting this issue are also running an older Firefox. 

If you consider there's still a reason to look into this further and you could tell me a way of retrieving  and passing the debug data along I can still do it.

**Comment by martinpitt** [comment]
@thezedt That is actually interesting for us! We do want to keep Cockpit compatible with Firefox ESR at least. A 3 year old browser is certainly tool old, but it really depends on what you mean by "older" -- which version was that? We may be able to reproduce the failure if you tell us the version. Thanks!

**Comment by thezedt** [comment]
I see the same behaviour on both 110.0b6 and 111.0b2 (they're the Developer Edition). Not quite 3 years old... yet, but older than the current ESR. 

Works fine with 122.0b9, also Developer Edition.

**Comment by ykevinnow** [comment]
Works fine.
