### ISSUE TITLE
Can't login to Cockpit after Installing cPanel

### ISSUE THREAD

**Issue by Emmasimeon** [cockpit-project/cockpit#19865]
### Explain what happens

1.  Cockpit works fine after installation, till after Installing cPanel on both servers
2. Once cPanel is installed, the Cockpit login page displays, but you keep getting the error "Wrong user name or password" when trying to log in.
3. Had to remove cockpit after cPanel installation and install afresh, but still same issue.

### Version of Cockpit

cockpit-300.3-1.el9_3.x86_64

### Where is the problem in Cockpit?

Networking

### Server operating system

Red Hat Enterprise Linux

### Server operating system version

Alma Linux 9

### What browsers are you using?

Firefox, Chrome, Safari macOS

### System log

```shell
Jan 21 16:32:28 dns1.servername.com systemd[1]: Starting Cockpit Web Service...
Jan 21 16:32:28 dns1.servername.com systemd[1]: Started Cockpit Web Service.
Jan 21 16:32:28 dns1.servername.com cockpit-tls[3818]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Jan 21 16:32:28 dns1.servername.com cockpit-tls[3818]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Jan 21 16:32:30 dns1.servername.com cockpit-tls[3818]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Jan 21 16:32:32 dns1.servername.com cockpit-tls[3818]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
Jan 21 16:35:42 dns1.servername.com systemd[1]: cockpit.service: Deactivated successfully.
```

**Comment by martinpitt** [comment]
That smells like cpanel modifies /etc/pam.d/ somehow? Can you please try a fresh installation where it works, back up /etc with `sudo cp -a /etc /etc.bak`, then install cpanel, run
```sh
diff -Nur /etc.bak /etc
```
and check/paste the diff? Please give it a check for passwords or other secrets first, the most interesting changes are probably in /etc/pam.d or /etc/nsswitch.conf.

Thanks!

**Comment by dontaskdonttellme** [comment]
I am in this same situation.  Fresh Cloudlinux 9.4 Shared pro install.  Enabled Cockpit, logged into cockpit with ROOT user.  Fully updated Cockpit and all system updates via Web GUI.
Activated Cloudlinux
Installed cPanel

Cockpit GUI comes up, but I can no longer sign into it.

"wrong username or password"

No entries in the disallowed users file.

Seeking to be able to log back into Cockpit for routine server health checks.

**Comment by jelly** [comment]
Do you have any logs of with relevant pam failures? Does cPanel disable root login? It would also be helpful if you could answer the questions here https://github.com/cockpit-project/cockpit/issues/19865#issuecomment-1903318549

**Comment by jelly** [comment]
Closing due to lack of response, please re-open with more information
