### ISSUE TITLE
Support passing Content-Length to `external` headers on `fsread1`

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#19861]
In Cockpit navigator we want to offer the option to download a file, this isn't too hard with an external channel:

```
    const query = window.btoa(JSON.stringify({
        payload: "fsread1",
        binary: "raw",
        path: `${currentPath}/${selected.name}`,
        superuser: "try",
        external: {
            "content-disposition": `attachment; filename="${selected.name}"`,
            "content-type": "application/octet-stream",
            "content-length": Number(selected.size),
        }
    }));
```

However cockpit-ws does not `cockpit_web_service_parse_external` ignores content-length and without the content-length a big download won't show the remaining time until it's downloaded. I think the easiest solution is to just allow setting this header, teaching cockpit-ws how to get the filesize seems a little bit daunting.

Background info: https://github.com/cockpit-project/cockpit-navigator/pull/175#discussion_r1459167369

**Comment by jelly** [comment]
@martinpitt @allisonkarlitskaya would love your input here :)

**Comment by Faizan-Alam-1** [comment]
Hey , can I take this task?

**Comment by jelly** [comment]
> @jelly Hey , can I take this task?

There is nothing decided yet, this is purely a research issue.

**Comment by jelly** [comment]
Idea from @allisonkarlitskaya make the ready message in `fsread1` return the content-length and let cockpit-ws send that back to the client.
