### ISSUE TITLE
Rebooted beelink and now cockpit not accessible from webgui.  Running cockpit on ubuntu

### ISSUE THREAD

**Issue by palominovet** [cockpit-project/cockpit#19864]
Have two bee links; other one is working fine after restart.  This one is not.  I originally followed the standard install instructions on the cockpit-project website for Ubuntu (am using gui version of Ubuntu but I installed via CLI as instructed). It had worked ever since install about 9 days ago but following a reboot today where I was adding some other disks, it has completely stopped.  When I check the status, it shows it running but not active.  When I try to access the same link I used prior (beelinkip:port) nothing happens. When I check port 9090, it shows systemd is listening.  This also shows when I have the other beelink turned off so I don’t think it’s interference from the other bee.  I have uninstalled and reinstalled and just can’t sort it out.

**Comment by martinpitt** [comment]
Sorry, there is not enough information in here. "running but not active" is contradictory, and which service did you check? What does "nothing happen" mean? Please check that `cockpit.socket` is active, and check `sudo journalctl -f` while you try to access cockpit, and paste it here if you aren't sure what happens.
