### ISSUE TITLE
Storage: stdbuf is not dependency of cockpit-storaged but it's used for monitoring LUKS

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#19892]
### Explain what happens

When in a system without stdbuf package, the LUKS device monitoring gives an error in the UI.
![Screen Shot 2024-01-26 at 13 04 06](https://github.com/cockpit-project/cockpit/assets/14921356/583f6087-0bc2-417a-a58b-8b3dc8d0623e)

Please add it as a dependency.

### Version of Cockpit

309

### Where is the problem in Cockpit?

Storage

### Server operating system

None

**Comment by jelly** [comment]
```
core/coreutils 9.4-2 [installed]
    usr/bin/stdbuf
[jelle@t14s][~/projects/libblockdev]%j main
[jelle@t14s][~/projects/cockpit/main]%git grep stdbuf
pkg/storaged/crypto/luksmeta-monitor-hack.py:    mon = subprocess.Popen(["stdbuf", "-o", "L", "udevadm", "monitor", "-u", "-s", "block"],
```

And same on Fedora where it's part of `coreutils`

**Comment by martinpitt** [comment]
Wow, how did you manage to not have coreutils? It's an essential package in Debian, and apparently also something like that in Fedora:
```
❱❱❱ podman run -it --rm registry.fedoraproject.org/fedora dnf remove --skip-broken -y coreutils
Error: 
 Problem: The operation would result in removing the following protected packages: sudo

╭─ 1 martin@cockpit-toolbox:~ ────────────────────╮
❱❱❱ podman run -it --rm registry.fedoraproject.org/fedora dnf remove --skip-broken -y coreutils sudo
Error: 
 Problem: The operation would result in removing the following protected packages: dnf
```

So... we could add it to the .spec, but please not to the Debian packaging. Not sure about arch. But seriously, not having *coreutils*? That's `true`, `false`, `echo`, `cat`, etc. -- I daresay that not a lot of cockpit will work without these.

Or is that some weird bug with `$PATH` or whatnot in the installer env?

**Comment by KKoukiou** [comment]
@martinpitt did not realize that comes from coreutils. The lorax templated remove part of the files packages provide, if they think these are not used (for size reduction purposes)

I will check the template clean ups.

**Comment by KKoukiou** [comment]
Here is what I meant ;) https://github.com/weldr/lorax/pull/1369

Sorry for the noise.

**Comment by martinpitt** [comment]
hah, thanks @KKoukiou ! That makes a lot more sense now.
