### ISSUE TITLE
Current performance percentage

### ISSUE THREAD

**Issue by mega-bots** [cockpit-project/cockpit#19891]
Would it be nice if there was an approximate percentage indicator indicating the current performance of the server compared to the time it was initially purchased?

So we would be able to know the status directly at a glance and see the PCP metrics or logs, which may be for further analysis.

**Comment by jelly** [comment]
I don't see how this can be implemented, how would PCP metrics know if performance "degraded" and why would performance degrade of a server over time?

**Comment by jelly** [comment]
> My thought (correct me if i am wrong, i am a beginner)
> 
> I am unaware of the implementation, but as time goes on, I think servers will degrade.

Not really, software changes the hardware stays the same. Sure cooling might get less optimal and thermal paste might have be replaced but that is nothing we can measure.
 
> Our PC, which we bought, doesn't perform the same way after what may be 4 years,so the performance drop, If somehow it could be made to value, that would be nice. I know this won't be easy, as many factors are involved, and giving an approximate value on which one should rely is difficult. But just in case, if we carefully do it somehow, we might get a nice feature, is what I thought.

There are too many moving parts to make a conclusive decision on if a server is degrade. Until something concrete is suggested to implement I'm closing this issue.
