### ISSUE TITLE
misuse of Red Hat Shadowman logo

### ISSUE THREAD

**Issue by lathan** [cockpit-project/cockpit#1990]
In the [try it out](http://cockpit-project.org/running.html) page, the Shadowman logo is used incorrectly. There are two issues:

1. Shadowman is used without the "Red Hat" wordmark. From [brand.redhat.com](http://brand.redhat.com/logos/shadowman/):

> Our corporate logo is Shadowman and the accompanying “Red Hat” wordmark.
> We never say never, but Red Hat very seldom approves the use of the Shadowman icon alone, without the wordmark. When we do, there is always a very good reason, considered and sanctioned at the highest levels.

2. Shadowman is used to represent RHEL Atomic Host, a product of Red Hat. This is also incorrect. Again, details here: [brand.redhat.com](http://brand.redhat.com/logos/productlogos/):

**Comment by stefwalter** [comment]
@lathan This is actually where the source code of http://cockpit-project.org comes from: https://github.com/cockpit-project/cockpit-project.github.io

**Comment by lathan** [comment]
thanks @stefwalter . I opened an issue [there](https://github.com/cockpit-project/cockpit-project.github.io/issues/22).
