### ISSUE TITLE
Thanks! Mostly looks good. If you want to land this quickly, please do, but I'd appreciate a follow-up (no-test) to put back the comment.

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#19916]
That comment is still current, other than the "we don't have .index" bit. But it's useful to explain the magic number 10 below, as well as splitting reads in between a number.

_Originally posted by @martinpitt in https://github.com/cockpit-project/cockpit/pull/19270#pullrequestreview-1852915257_

**Comment by allisonkarlitskaya** [comment]
@martinpitt I actually just read this comment and it's definitely no longer relevant.  We no longer slice anything, specifically because the part about not having `memoryview.index()` is no longer relevant.  That means the performance concerns are also not relevant...

**Comment by martinpitt** [comment]
OK, thanks for checking!
