### ISSUE TITLE
libsystemd-journal libsystemd-daemon deprecated

### ISSUE THREAD

**Issue by shawnl** [cockpit-project/cockpit#1991]
```
commit bc5ec08dfa2a082aa511e68e9e6df721bde99b50
Author: Shawn Landden <shawn@churchofgit.com>
Date:   Mon Mar 23 19:31:39 2015 +0000

    libsystemd-journal libsystemd-daemon deprecated

diff --git a/configure.ac b/configure.ac
index 9adbf1a..9650537 100644
--- a/configure.ac
+++ b/configure.ac
@@ -57,7 +57,7 @@ GLIB_VERSION="2.34"
 LIBSSH_VERSION="0.6.0"
 
 GIO_REQUIREMENT="gio-unix-2.0 >= $GLIB_VERSION"
-SYSTEMD_REQUIREMENT="libsystemd-journal >= 187 libsystemd-daemon"
+SYSTEMD_REQUIREMENT="libsystemd >= 209"
 JSON_GLIB_REQUIREMENT="json-glib-1.0 >= 0.14.0"
 UDISKS_REQUIREMENT="udisks2 >= 2.0.91"
 ACCOUNTS_REQUIREMENT="accountsservice >= 0.6.35"
```

**Comment by stefwalter** [comment]
Which version of systemd did this happen in? We probably would need to bump the required version.

**Comment by shawnl** [comment]
209

**Comment by stefwalter** [comment]
@mvollmer @kkaempf @kbsingh @jpsutton 

Are we ready to have Cockpit drop support for systemd 208 and earlier?

This would mean dropping support for Fedora 20 ... which is probably broken anyway. How does this affect OpenSUSE, CentOS or Ubuntu Vivid?

**Comment by kkaempf** [comment]
Should be fine for openSUSE.
It will drop openSUSE 13.1 (released Nov 2013) which had systemd 208.
All later releases (SUSE Linux Enterprise Server 12, openSUSE 13.2) have systemd 210.

**Comment by jzb** [comment]
As I understand it this would impact CentOS 7 including the next release. While Fedora > 20 may be well ahead of 208, CentOS 7x will be on 208 for some time, no?

**Comment by jpsutton** [comment]
Ubuntu Vivid is on systemd 219.

**Comment by stefwalter** [comment]
It turns out that in addition RHEL 7.0 is on systemd 208.

Once systemd actually removes these libsystemd-*.pc pkg-config files, we'll need to add the customary NN lines of autofoo gunk to our configure.ac in order to support both pre-209 and later releases.

But for now lets leave it as is.

**Comment by kbsingh** [comment]
note that the systemd 208 isnt stock 208, there is a patchset that comes with it on CentOS and RHEL - do we have the feature you need ? Can we request backports for specific bits as needed ?

**Comment by stefwalter** [comment]
@kbsingh @jzb We'll stick with a 208 minimum for now. 

There are bothersome "wontfix" bugs (including mutually-exclusize bugs) in both <= 208 and > 208 .... so it's sorta pick your poison. None of them are blockers though.
