### ISSUE TITLE
Cockpit storage reports the wrong temperature for a Kingston SSD

### ISSUE THREAD

**Issue by poVoq** [cockpit-project/cockpit#19931]
### Explain what happens

1. Install Kingston SSD
2. See temperature in Cockpit-storage
3. Compare with actual SMART reading

Strangely this doesn't happen with a Samsung SSD or other HDDs.

![grafik](https://github.com/cockpit-project/cockpit/assets/940360/902259b7-c7e2-48f6-a865-49d9d96c6e1f)

Actual SMART of same drive:
![grafik](https://github.com/cockpit-project/cockpit/assets/940360/23932d79-64d1-4a17-b66f-c2b4f672501b)

### Version of Cockpit

304

### Where is the problem in Cockpit?

Storage

### Server operating system

Fedora

### Server operating system version

38

### What browsers are you using?

Firefox

**Comment by jelly** [comment]
We retrieve the temperature data from [udisks](http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Drive.Ata.html#gdbus-property-org-freedesktop-UDisks2-Drive-Ata.SmartTemperature) which seems to have an issue supporting [Kingston drives](https://github.com/storaged-project/udisks/issues/568).

**Comment by CodeWithCJ** [comment]
I am also facing similar issue on PNY 2.5 SSD. Anyway to fix this?

**Comment by jelly** [comment]
Likely fixed with libblockdev 3.2.0.

**Comment by CodeWithCJ** [comment]
> Likely fixed with libblockdev 3.2.0.

Could you propvide commands to upgrade? I tried apt update/upgrade and said I am on latest version of libblockdev

**Comment by jelly** [comment]
@CodeWithCJ that depends on your distribution what do you run?
