### ISSUE TITLE
🔴 Nightly tests did not succeed on fedora-39/updates-testing: pixel test failures with new tasks container

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19944]
Tests failed on fb27a62a9f7559ab0d0e2eb7c9ad2274f0fe3471, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240206-012355-fb27a62a-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment]
@allisonkarlitskaya @mvollmer This looks like fallout from yesterday's tasks container refresh? I see the same failures in #19942 and #19943 so it looks like we should just push these new pixels to main?

(Sorry, can't do it today, just passing by)
