### ISSUE TITLE
Request RPMs for OpenSuse Leap 15.5

### ISSUE THREAD

**Issue by marcoczen** [cockpit-project/cockpit#19991]
Guys,

I have Cockpit running on OpenSuse 15.4 ( packaged by a good samaritan ) but i cant seem to get RPMS for OpenSuse Leap 15.5. ( he doesnt have time ).

I see that you have rpms for SUSE Linux Enterprise Micro. So i hope you could kindly consider packging rpms for OpenSuse Leap 15.5 ?

```
# cat /etc/*release

NAME="openSUSE Leap"
VERSION="15.5"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.5"
PRETTY_NAME="openSUSE Leap 15.5"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.5"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"

```

**Comment by martinpitt** [comment]
I'm afraid that's not under our control. Please file a bug in the OpenSUSE bug tracker. Thanks!
