### ISSUE TITLE
Fresh install of debian 12.5.0 AMD64, cannot install cockpit

### ISSUE THREAD

**Issue by smurfster** [cockpit-project/cockpit#20013]
### Explain what happens

Follow the https://cockpit-project.org/running.html#debian instructions

The result is as follows 

> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  cockpit-bridge : Depends: libglib2.0-0 (>= 2.67.1) but it is not installable
>                   Depends: libjson-glib-1.0-0 (>= 1.5.2) but it is not installable
>                   Depends: libssh-4 (>= 0.10.4) but it is not installable
>                   Depends: glib-networking but it is not installable
>  cockpit-system : Depends: libpwquality-tools but it is not installable
>                   Recommends: sudo but it is not installable or
>                               pkexec but it is not installable or
>                               policykit-1 but it is not installable
>  cockpit-ws : Depends: libglib2.0-0 (>= 2.67.1) but it is not installable
>               Depends: libjson-glib-1.0-0 (>= 1.5.2) but it is not installable
>               Depends: glib-networking but it is not installable
> E: Unable to correct problems, you have held broken packages.

### Where is the problem in Cockpit?

Software updates

### Server operating system

Debian

### Server operating system version

12.5.0

**Comment by martinpitt** [comment]
Looks like the packages on your system are broken somehow. What does `apt-cache policy libglib2.0-0` show? And what does `apt update` say?

**Comment by smurfster** [comment]
> Looks like the packages on your system are broken somehow. What does `apt-cache policy libglib2.0-0` show? And what does `apt update` say?

You sir are correct and I'm an idiot. Im not sure how this happened as its a complete fresh install.

Thank you

Just in case this happens to anyone else
I used this to get the repos list
https://wiki.debian.org/SourcesList#Example_sources.list

and pasted them in here /etc/apt/sources.list

**Comment by martinpitt** [comment]
@smurfster :rofl: no worries, happens to all of us! :wink:
