### ISSUE TITLE
allow to resize the terminal widget

### ISSUE THREAD

**Issue by kdudka** [cockpit-project/cockpit#2001]
The default size of the terminal widget is too small for me to be useful.  There is currently no way to enlarge it.  It would be nice to make the size customizable.

**Comment by andreasn** [comment]
In it's very simplest form, I would suggest adding a maximize button. This would simply fill the frame from left to right, top to bottom.

![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/terminal/terminal-maximize.png)

**Comment by kdudka** [comment]
Yes, that sounds useful to me.

**Comment by stefwalter** [comment]
@andreasn, maybe arrows-alt? http://fortawesome.github.io/Font-Awesome/icon/arrows-alt/

**Comment by fridex** [comment]
I started to work on this. Unfortunately, the terminal implementation is behaving weird. The size of terminal is 80x24 by default and this is the only working resolution. Other sizes do not respect number of columns/rows and act like 80x24 when displaying a content. The implementation is pretty confusing in some cases. Is this issue known?

![image](https://cloud.githubusercontent.com/assets/880687/7307285/0f6abc74-ea0c-11e4-920b-a4bc5cdb7c73.png)

**Comment by stefwalter** [comment]
I think a particular unix signal that needs to be sent to the process when the window size changes. Maybe this isn't so simple after all.

**Comment by mvollmer** [comment]
> Maybe this isn't so simple after all.

But it would be very cool. :-)

**Comment by fridex** [comment]
> I think a particular unix signal that needs to be sent to the process when the window size changes. Maybe this isn't so simple after all.

It looks like handling rows/columns is incorrectly implemented. Sending ^L or instantiating terminal with different size than 80x24 does not effect bogus behavior.

**Comment by stefwalter** [comment]
> It looks like handling rows/columns is incorrectly implemented. Sending ^L or instantiating terminal with different size than 80x24 does not effect bogus behavior.

If you've identified a bug, then the upstream for the terminal code is *term.js* here: https://github.com/chjj/term.js

**Comment by stefwalter** [comment]
This is not a starter issue. It involves ```ioctl()```.

**Comment by Pazns** [comment]
According to : https://github.com/chjj/term.js/issues/117 ,term.js seems to be quite dead, or becoming so, and people are talking about [xterm.js](https://github.com/sourcelair/xterm.js) as a technical replacement.

**Comment by stefwalter** [comment]
@Pazns Interesting. If you're interested in porting to xterm.js I'd be happy to help review code and help with setup and testing.

**Comment by larsu** [comment]
Why don't we just have the terminal be full size all the time? I can't think of a good reason why anyone would want a small terminal rather than one that fills the entire space.

Wouldn't need an extra button then, either.

**Comment by stefwalter** [comment]
@larsu I'd be fine with that as long as it doesn't break common terminal based apps. Although it's worth noting that typically terminals start with 80x25 and then are resizeable. @andreasn What do you think?

But either way, @larsu if you're interested in working on this, the cockpit stream channel needs a new control message that is sent from frontend -> bridge and does a ```ioctl(fd, TIOCGWINSZ, &ws)``` or equivalent.

**Comment by larsu** [comment]
> But either way, @larsu if you're interested in working on this, the cockpit stream channel needs a new control message that is sent from frontend -> bridge and does a ioctl(fd, TIOCGWINSZ, &ws) or equivalent.

Would love to. Assigning to myself.

**Comment by Pazns** [comment]
@larsu Without the correct Terminal Resize event handling, what will happen if the terminal is created when the window is large at first, and then shrinked ?

**Comment by larsu** [comment]
> @larsu Without the correct Terminal Resize event handling, what will happen if the terminal is created when the window is large at first, and then shrinked ?

Without correct resizing, resizing won't work ;) I'll have to fix this correctly either way.

**Comment by andreasn** [comment]
> @larsu I'd be fine with that as long as it doesn't break common terminal based apps. Although it's worth noting that typically terminals start with 80x25 and then are resizeable. @andreasn What do you think?

Yeah, apps breaking is what would worry me as well.

For things like embedded terminals for things like the docker page is another case where they need to stay the same size as now.

I would also worry about a terminal being bigger than the window, and the actual promt being hidden below the fold.

If those are taken care of, I think I'm fine with a bigger terminal.

**Comment by larsu** [comment]
I've put up a branch at #4633 which makes the terminal fullscreen.

I'd appreciate some testing and design input for that.

**Comment by loadshare** [comment]
lets find the people/person who decided on the 80x24 resolution and kick them hard ..... 
then afterwards realise that the kicking hasn't delivered a change in code ... or any improvement whatsoever - then get back to work and actually try and resolve the matter at hand ....

**Comment by larskarlitski** [comment]
@loadshare please refrain from assaulting cockpit contributors.

**Comment by loadshare** [comment]
@larskarlitski  - just a little humour - no harm intended ;)

**Comment by nitingupta910** [comment]
Any updates on merging @larskarlitski 's changes. The small terminal size is almost unusable.

**Comment by larskarlitski** [comment]
> Any updates on merging @larskarlitski 's changes? The small terminal size is almost unusable.

I've just updated the pull request.

**Comment by PeterFalken** [comment]
Nice - Thanks you Lars.

**Comment by lp177** [comment]
Why do no do the same thing on the terminals of Docker containers ?

**Comment by marusak** [comment]
> Why do no do the same thing on the terminals of Docker containers ?

None just did it. But also now docker plugin is being replaced by podman plugin where terminal resizes.
