### ISSUE TITLE
TestStorageLvm2-testLvm-pool-page pixel flake due to missing used size

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20053]
Tests failed on 1a151ef292939e23701db1be189035a76f71b7b1, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240217-012330-1a151ef2-fedora-39-daily/log.html)

**Comment by martinpitt** [comment]
The [pixel diff](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240217-012330-1a151ef2-fedora-39-daily/pixeldiff.html#TestStorageLvm2-testLvm-pool-page) shows that the page does not (yet, I hope) show the used size. The pixel test needs to wait for that. We can just `wait_in_text()`, as the pixel test asserts the precise "0.047" anyway.

**Comment by martinpitt** [comment]
Happened also [here](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20052-20240217-054538-f322ee41-fedora-39-storage/log.html)

**Comment by martinpitt** [comment]
and in #20056
