### ISSUE TITLE
Change system time - SELinux policy denies access

### ISSUE THREAD

**Issue by blaskovic** [cockpit-project/cockpit#2007]
System -> System time -> Set time automaticaly using NTP.

    type=USER_AVC msg=audit(1427202207.975:435): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='avc:  denied  { start } for auid=n/a uid=0 gid=0 path="/usr/lib/systemd/system/systemd-timesyncd.service" cmdline="/usr/lib/systemd/systemd-timedated" scontext=system_u:system_r:systemd_timedated_t:s0 tcontext=system_u:object_r:systemd_unit_file_t:s0 tclass=service  exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'

![Selinux bug](http://www.blaskovic.sk/data/screenshot-20250-1427202358.png)

**Comment by stefwalter** [comment]
Thanks for reporting this. But this is not a bug in Cockpit. It's a common bug in Fedora that has unfortunately been around for a year and a half

https://bugzilla.redhat.com/show_bug.cgi?id=1014315
