### ISSUE TITLE
Nightly tests did not succeed on arch/other

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20084]
Tests failed on 3d1110a4436d8c920ba37cfdcaa06f2a00948e8d, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20081-20240222-134057-3d1110a4-arch-other/log.html)

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/bots/issues/5958
