### ISSUE TITLE
Copy and paste to terminal could improve usability

### ISSUE THREAD

**Issue by schidlo** [cockpit-project/cockpit#2009]
From time to time I use copy and paste in terminal. It's not necessary but it could improve usability.

**Comment by balugrace** [comment]
is anyone working on this issue? if so, what is the status?

**Comment by stefwalter** [comment]
> is anyone working on this issue? if so, what is the status?

I don't know of anyone working on this issue. Likely the first step is migrating our use of term.js to xterm.js instead, since the latter is maintained going forward.

**Comment by dagnelies** [comment]
Indeed, this would be very welcome. Great stuff by the way.

**Comment by simonk83** [comment]
I'd love this too

**Comment by tomasxiv** [comment]
Is it the task (copy and paste in terminal) in progress or wont it to be supported?

**Comment by larskarlitski** [comment]
What exactly did you mean by "could improve usability"? It was broken for a long time, but #7983 should at least allow copy and pasting with the right click menu.

Did you imagine something in addition to that? In #7956, @garrett suggested that `Ctrl+Shit+C` could be used, similar to how gnome terminal does it.

**Comment by die7** [comment]
Windows 10, IE 11, Chrome Version 63.0.3239.132 copy & paste not working

**Comment by garrett** [comment]
Firefox 58.0.2 on Linux (Fedora 27, Cockpit built from master):
- Copy works after selecting an item and right clicking on the terminal titlebar. Right-clicking in the terminal itself (where I'd expect to right-click) does not work.
- Paste does not work at all.

**Comment by vikranttkamble** [comment]
Will this feature consider for next release? This is a must feature for us to start using cockpit.

**Comment by vikranttkamble** [comment]
Okay, so paste is working on linux machines chrome and chromium and not working in firefox.
We can work with this. Thanks!

**Comment by tj22157** [comment]
Heya,

I see thing is working on chorme. However I can not paste into the terminal. I'm on version 172, Google Chrome om Windows and I do not get an option to paste. 

Am I missing a step here?

**Comment by MinkiDev** [comment]
Win10 64bit, Chrome68.0.3440.75 (official), x64
copy function working but paste into terminal not working.

**Comment by Tezzlicious** [comment]
Copy / Paste would be appreciated.

**Comment by Jarli01** [comment]
I too would love to have this functionality.

**Comment by waclaw66** [comment]
Very missing features indeed. At least Paste.

**Comment by garrett** [comment]
Note: I had additional suggestions in a different bug @ https://github.com/cockpit-project/cockpit/issues/7956#issuecomment-339296754 & https://github.com/cockpit-project/cockpit/issues/7956#issuecomment-339365141 (including sticky keys and such). Both were written a long time ago, but probably still apply.

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit/commit/8eb0e5e6 provides copy and paste through context menu. Also it makes shortcuts discoverable (ctrl+Insert and shift+insert).

Others combinations can be added, but as discussed, crtl+c and ctrl+v generally are not great choice, ctrl+shift+c/v can be implemented, but for example ctrl+shift+c is already reserved in firefox.

Closing, if anyone thinks there is something missing please reopen.
