### ISSUE TITLE
clicking on networking in the applications tag leads to not found page 

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/cockpit#20127]
### Explain what happens

1.  log in to cockpit 
2.  go to applications tab 
3.  click networking 
get not found error
the browser is let to https://<ip>:9090/networkmanager
while the actuall applicaiton is in:
https://<ip>:9090/network#

### Version of Cockpit

310.1-1~bpo22.04.1

### Where is the problem in Cockpit?

None

### Server operating system

Ubuntu

### Server operating system version

22.04.0.4

### What browsers are you using?

Chrome

**Comment by martinpitt** [comment]
Can you please do a screenshot where exactly you click? There's no link to `/networkmananger` in Cockpit's own source code anywhere. Thanks!

**Comment by emaayan** [comment]
additianlly i'm not sure what this message means (after i click instal it does something and it goes away) 

![image](https://github.com/cockpit-project/cockpit/assets/13434544/0d958f96-4c11-4ca6-9d11-9e1ff31bd117)

**Comment by martinpitt** [comment]
Ah, thanks! src/appstream/org.cockpit-project.cockpit-networkmanager.metainfo.xml.in is indeed wrong:
```xml
<launchable type="cockpit-manifest">networkmanager</launchable>
```

That needs to be `network`.
