### ISSUE TITLE
TestStorageMdRaid.testRaid pixel flake due to not waiting for progress bar

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20129]
Tests failed on 770eddc7fcb56c06e4a514755f04156bf41335e9, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240301-012736-770eddc7-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment]
[This pixel failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240301-012736-770eddc7-fedora-39-updates-testing/pixeldiff.html#TestStorageMdRaid-testRaid-page) looks like a legit flake -- it should wait for the progress bar to appear. @mvollmer something for you?
