### ISSUE TITLE
disabling a service removes status info and buttons

### ISSUE THREAD

**Issue by todoleza** [cockpit-project/cockpit#2012]
after cockpit start (reproducible by stopping it) I logged in and went to services, opened a failed service lm_sensors and pushed Disable. All buttons for the service disappeared  and the field was replaced with text "unknown" as captured on picture bellow. Repeating the steps on already running instance works as it should.
![pic](https://cloud.githubusercontent.com/assets/4707985/6803797/509d1f32-d23a-11e4-8838-eae2e3099f64.png)
cockpit-0.44-3.fc22.x86_64

**Comment by mvollmer** [comment]
This works for me now.
