### ISSUE TITLE
Provide better description in About dialog

### ISSUE THREAD

**Issue by todoleza** [cockpit-project/cockpit#2014]
Currently, "About Cockpit" menu item from top right shows window with very vague description of Cockpit: `Cockpit is an advanced application with many options.`
following lines are also present:
`Version 0.44.`
`Built on Sat Mar 21 11:49:16 UTC 2015.`

imho a web link to project or github page would be good to put there

**Comment by andreasn** [comment]
On the website it says "Cockpit makes it easy to administer your GNU/Linux servers from the browser", and since you're already in the browser, cutting "...from the browser" should be ok.
Probably best to link to http://cockpit-project.org/ since it has all the pointers to the issue tracker, mailing list etc.

**Comment by stefwalter** [comment]
Sounds good.

**Comment by andreasn** [comment]
@todoleza do you want to do a pull request with the above fixed?

**Comment by todoleza** [comment]
Hello,
I can create PR for this, but I am not acquaint with po files generation. please look at index.html diff. Originally I wanted to put the website under the two generated lines but it didn't look well and would generate one more translation string. It's merged as to be seen in the diff.
Also, if I got you correctly, "from the browser" was cut away.
https://gist.github.com/todoleza/0f111e0eafe9ad279f29

**Comment by camarox53** [comment]
Hello everyone, 
While I was looking at the index.html file located at /pkg/shell/index.html. It would appear that this issue has already been resolved. Can this issue be closed? or does something else need finished? 

Link to the index.html for ease of access: 
https://github.com/cockpit-project/cockpit/blob/master/pkg/shell/index.html

- Cheers

**Comment by martinpitt** [comment]
It currently says "Cockpit is an interactive Linux server admin interface." with a link to the project homepage, which seems appropriate to me.
