### ISSUE TITLE
plot useLayoutSize() crashes on infinite recursion

### ISSUE THREAD

**Issue by joshqou** [cockpit-project/cockpit#20171]
### Explain what happens

1. Click the "Storage" or "Networking" tab
2. Load to a blank screen with the "Oops!" error hint at the top right

This issue does not manifest in Firefox. Ungoogled Chromium (flatpak 122.0.6261.111)

#### Storage error:
```
storaged.js:8 Uncaught Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at oi (storaged.js:8:33845)
    at OQ (storaged.js:6:24880)
    at storaged.js:655:511
    at $h (storaged.js:8:24270)
    at tB (storaged.js:8:31626)
    at YT (storaged.js:8:31478)
    at VQ (storaged.js:8:31016)
    at YQ (storaged.js:8:40923)
    at Rc (storaged.js:8:40281)
    at aB (storaged.js:8:36889)
```

#### Networking error
```
networkmanager.js:8 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at bn (networkmanager.js:8:33829)
    at hD (networkmanager.js:6:24854)
    at networkmanager.js:17:509
    at kv (networkmanager.js:8:24259)
    at pI (networkmanager.js:8:31611)
    at o2 (networkmanager.js:8:31463)
    at OD (networkmanager.js:8:31001)
    at AD (networkmanager.js:8:40897)
    at hi (networkmanager.js:8:40257)
    at dI (networkmanager.js:8:36867)
```

### Version of Cockpit

311

### Where is the problem in Cockpit?

Storage, Networking

### Server operating system

Fedora

### Server operating system version

39

### What browsers are you using?

Other

**Comment by martinpitt** [comment]
That error [means](https://react.dev/errors/185) :+1: 

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

>    at oi (storaged.js:8:33845)
 >  at OQ (storaged.js:6:24880)

These are deep inside minified React code.

>   at storaged.js:655:511

This is the plot creation code, in particular [useLayoutSize()](https://github.com/cockpit-project/cockpit/blob/cb02ac0e902e5c28fc9810538d00a6b9b8ad6164/pkg/lib/cockpit-components-plot.jsx#L291). It recurses in the `setSize()` call. Yet another one of my pet peeve "effects with setState are evil" :smirk: 

>   at networkmanager.js:17:509

That's exactly the same place.

However, this code was introduced in commit 9c60b70ec2b59b66cd77ab over 3 years ago, so something changed in recent chromium? It doesn't happen with the Fedora-packaged chromium version 122.0.6261.128 (that runs in our CI). Your version is a tad behind, but only in the last two digits. `flatpak install ungoogled-chromium` gives me the same version .128. However, the networking/storage pages don't crash for me (that's cockpit 313, but as mentioned the plot code hasn't changed in > 3 years anyway). I tried resizing, moving the window, (un)maximizing, anything I could think of to change the size of the plots, but no crash.

So there must be something "special" on your setup, perhaps a browser  extension, perhaps some desktop environment which makes the browser behave differently with resize requests.

So this is unreproducible for now, but at least we have a fairly good idea about where the crash happens. @mvollmer do you happen to have an idea how to prevent recursion there?

**Comment by joshqou** [comment]
@martinpitt The profile I was using doesn't have any extensions installed. I do have some chrome flags set though
```
extension-mime-request-handling = "Download as regular file"
disable-search-engine-collection = "enabled"
disable-qr-generator = "Enabled"
disable-sharing-hub = "enabled"
hide-sidepanel-button = "enabled"
fingerprinting-client-rects-noise = "enabled"
fingerprinting-canvas-measuretext-noise = "enabled"
fingerprinting-canvas-image-data-noise = "enabled"
no-pings = "enabled"
overlay-scrollbars = "Enabled"
ozone-platform-hint = "X11"
tab-groups-save = "Disabled"
scrollable-tabstrip = "Disabled"
enable-accessibility-live-caption = "Disabled"
chrome-labs = "Disabled"
chrome-refresh-2023 = "Disabled"
side-search = "Disabled"
```
GNOME Wayland 45.5
Fedora Workstation 39

**Comment by mvollmer** [comment]
> So this is unreproducible for now, but at least we have a fairly good idea about where the crash happens. @mvollmer do you happen to have an idea how to prevent recursion there?

Yeah, the code is questionable. It assumes that the sizes of things interact in simple ways. I'll see if we can remove that assumption without causing too much flicker. I think it might be enough to only run the layout effect once initially, and then once after each window resize event.

**Comment by mvollmer** [comment]
> ozone-platform-hint = "X11"

Is this in a X11 session (and not Wayland)?

**Comment by mvollmer** [comment]
> > ozone-platform-hint = "X11"
> 
> Is this in a X11 session (and not Wayland)?

Ouch, you also said "GNOME Wayland 45.5"... sorry.

**Comment by joshqou** [comment]
@martinpitt Figured out the cause. It's a result of `fingerprinting-client-rects-noise`

![Screenshot from 2024-03-26 21-22-44](https://github.com/cockpit-project/cockpit/assets/97894002/69a8d377-45c3-47e5-a02a-f0c0dcb4e875)

Reproduced in a fresh Fedora Workstation 39 virtual machine.

```sh
flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install -y --user com.github.Eloston.UngoogledChromium
sudo dnf install cockpit -y && systemctl enable --now cockpit
```

Enabling the `rects-noise` flag will break and subsequently restore functionality of the storage and networking pages.

**Comment by mvollmer** [comment]
> Enabling the `rects-noise` flag will break and subsequently restore functionality of the storage and networking pages.

Thanks! Excellent! I'll update #20225 accordingly.

**Comment by joshqou** [comment]
Reported the issue upstream to Ungoogled Chromium as well as this seems like this may have been caused by a bug/regression. The `rects-noise` flag is supposed to generate a random offset to use for each document, rather than randomly generating an offset each call

**Comment by mvollmer** [comment]
> The `rects-noise` flag is supposed to generate a random offset to use for each document, rather than randomly generating an offset each call

Yes, I was wondering about that as well. But since this is part of a never ending war of escalation, I dont think we can expect one side to strictly stick to a specification.
