### ISSUE TITLE
Root login is now by default disabled by `/etc/cockpit/disallowed-users`, so if you want to allow root login you will need to remove the `root` entry from that file.

### ISSUE THREAD

**Issue by govwin** [cockpit-project/cockpit#20181]
Root login is now by default disabled by `/etc/cockpit/disallowed-users`, so if you want to allow root login you will need to remove the `root` entry from that file.

_Originally posted by @jelly in https://github.com/cockpit-project/cockpit/issues/18427#issuecomment-1448831430_
            

This is an unnecessary interference.
Why not let it default to how the user has kept it. That is, if root is enabled in the system, let the root login on cockpit as well.

**Comment by jelly** [comment]
From our perspective allowing root login possibly public on the internet is a no-go, and if a user wants too they can by either removing the file or editing `disallowed-users` file. Note that on upgrading we respected the users existing configuration and didn't disable root logins.

**Comment by tristan-k** [comment]
I just discovered that it's possible to login with a non-root user (eg. `user1`) even though the non-root user is in the `/etc/cockpit/disallowed-users` file. This is only possible if enter `localhost` in `Other Options` and connect. Why is that?

**Comment by jelly** [comment]
> I just discovered that it's possible to login with a non-root user (eg. `user1`) even though the non-root user is in the `/etc/cockpit/disallowed-users` file. This is only possible if enter `localhost` in `Other Options` and connect. Why is that?

That's because that uses ssh auth and the normal login uses our PAM rules.
