### ISSUE TITLE
clevis-luks not installable in updates-testing F39

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20184]
The job `fedora-39/updates-testing` failed on commit 6be5f27fa863d7599d8721ae4043e3a485c7bdc4.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-6be5f27f-20240316-012249-fedora-39-updates-testing/log.html

**Comment by martinpitt** [comment]
Same as the night before in issue #20179:
```
Problem: conflicting requests
  - nothing provides clevis-luks(x86-64) = 19-4.fc39 needed by clevis-systemd-19-4.fc39.x86_64 from updates
```

So Fedora is kaputt

**Comment by martinpitt** [comment]
Ah! This happens because we have a static "clevis-systemd" rpm in /var/lib/package-sets/clevis/, which isn't compatible with the system installed version. This needs to be fixed in bots first.
