### ISSUE TITLE
nightly failure: TestStorageStratisReboot.testEncrypted timed out on reboot

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20245]
The job `fedora-39/updates-testing` failed on commit f2cc9e1a360e69dc55b8f9f26f367eb4c17ecb5b.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-f2cc9e1a-20240401-012844-fedora-39-updates-testing/log.html

**Comment by martinpitt** [comment]
This happened three nights in a row, this is real.

**Comment by martinpitt** [comment]
This got sorted out via naughty in https://github.com/cockpit-project/bots/pull/6166
