### ISSUE TITLE
Join domain only by sssd

### ISSUE THREAD

**Issue by atol71** [cockpit-project/cockpit#20240]
### Explain what happens

1. The title in Cockpit Join Domain only says client: sssd
2. Changed realmd default client to winbind
3. in /etc/realmd.conf
4. in /usr/lib/realmd/realmd-defaults.conf
5. rebooted machine
6. still sssd not winbind

### Version of Cockpit

300.1-1

### Where is the problem in Cockpit?

Overview

### Server operating system

Ubuntu

### Server operating system version

23.10

### What browsers are you using?

Firefox

**Comment by atol71** [comment]
To add a note, if one do not have sssd at all installed the Cockpit UI says winbind like expected.

**Comment by martinpitt** [comment]
This is more of a realmd bug report, not a cockpit one, but I suppose there may be some confusion here? When you say "winbind" you most certainly mean that you have an Active Directory setup. The Linux client side interface of talking to that to set up users etc. **is** sssd, winbind is merely the protocol.
