### ISSUE TITLE
Cannot control mmc device

### ISSUE THREAD

**Issue by onlineapps-cloud** [cockpit-project/cockpit#20250]
### Explain what happens

hi, i have radxa x2l SBC with EMMC on board, but i cannot format, delete partitions or make another things using cockpit
![image](https://github.com/cockpit-project/cockpit/assets/69077240/2ae7c959-6c30-463d-a0d0-672131f6a0e6)
when i click on this device i get this:
![image](https://github.com/cockpit-project/cockpit/assets/69077240/49da80bb-aaaa-4964-8f06-159716d1f7a2)
control buttons not available, please help me to debug and fix this problem, thanks, bet regards.
cockpit version:
![image](https://github.com/cockpit-project/cockpit/assets/69077240/6876a6b7-856d-490c-8928-f41756c3895f)

### Version of Cockpit

287-1

### Where is the problem in Cockpit?

Storage

### Server operating system

Debian

### Server operating system version

12

### What browsers are you using?

Firefox

**Comment by mvollmer** [comment]
> control buttons not available

Do you have "Administrative access"?  If you see "Limited access" at the top of Cockpit, click that to get admin access. Then the buttons should appear that let you format your device.

**Comment by onlineapps-cloud** [comment]
> > control buttons not available
> 
> Do you have "Administrative access"? If you see "Limited access" at the top of Cockpit, click that to get admin access. Then the buttons should appear that let you format your device.

yes,  i have Administrative access, i can manage another drives , but this emmc drive i cannot manage

**Comment by mvollmer** [comment]
Ah, I see now.

The emmc card is treated as if it were a multipathed device, but the main device for it is missing.

What are /dev/mmcblk0boot0 and /dev/mmcblk0boot1? They kinda look like partitions of /dev/mmcblk0, but not really. (Partitions would be called /dev/mmcblk0p0, I think.)

Could you share the output of the following command?

```
udevadm info /dev/mmcblk*
```

**Comment by mvollmer** [comment]
> What are /dev/mmcblk0boot0 and /dev/mmcblk0boot1?

I found this, which explains it clearly: https://www.kernel.org/doc/Documentation/mmc/mmc-dev-parts.txt

So my guess right now is that UDisks2 or udev need to be changed to correctly recognize these block devices as distinct from mmcblk0. I don't think we need to do anything sophisticated about them, like linking them back to mmcblk0 as a new kind of partition.

**Comment by mvollmer** [comment]
(The output of udevadm info is still very interesting. I don't think I have access to a real emmc here.)

**Comment by onlineapps-cloud** [comment]
hi, thanks for help, here is `udevadm info /dev/mmcblk*` log:

```
P: /devices/pci0000:00/0000:00:1c.0/mmc_host/mmc0/mmc0:0001/block/mmcblk0
M: mmcblk0
R: 0
U: block
T: disk
D: b 179:0
N: mmcblk0
L: 0
S: disk/by-diskseq/10
S: disk/by-id/mmc-BJTD4R_0x78dc46c8
Q: 10
E: DEVPATH=/devices/pci0000:00/0000:00:1c.0/mmc_host/mmc0/mmc0:0001/block/mmcblk0
E: DEVNAME=/dev/mmcblk0
E: DEVTYPE=disk
E: DISKSEQ=10
E: MAJOR=179
E: MINOR=0
E: SUBSYSTEM=block
E: USEC_INITIALIZED=2017473
E: ID_SERIAL=0x78dc46c8
E: ID_NAME=BJTD4R
E: ID_PART_TABLE_UUID=e55fc5b4-cbeb-4296-bf45-d38a585dc587
E: ID_PART_TABLE_TYPE=gpt
E: MMC_TYPE=MMC
E: ID_DRIVE_FLASH_MMC=1
E: ID_DRIVE_MEDIA_FLASH_MMC=1
E: DEVLINKS=/dev/disk/by-diskseq/10 /dev/disk/by-id/mmc-BJTD4R_0x78dc46c8
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1c.0/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot0
M: mmcblk0boot0
R: 0
U: block
T: disk
D: b 179:8
N: mmcblk0boot0
L: 0
S: disk/by-diskseq/11
Q: 11
E: DEVPATH=/devices/pci0000:00/0000:00:1c.0/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot0
E: DEVNAME=/dev/mmcblk0boot0
E: DEVTYPE=disk
E: DISKSEQ=11
E: MAJOR=179
E: MINOR=8
E: SUBSYSTEM=block
E: USEC_INITIALIZED=2021743
E: MMC_TYPE=MMC
E: ID_DRIVE_FLASH_MMC=1
E: ID_DRIVE_MEDIA_FLASH_MMC=1
E: ID_SERIAL=0x78dc46c8
E: ID_NAME=BJTD4R
E: ID_PART_TABLE_UUID=e55fc5b4-cbeb-4296-bf45-d38a585dc587
E: ID_PART_TABLE_TYPE=gpt
E: DEVLINKS=/dev/disk/by-diskseq/11
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1c.0/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot1
M: mmcblk0boot1
R: 1
U: block
T: disk
D: b 179:16
N: mmcblk0boot1
L: 0
S: disk/by-diskseq/12
Q: 12
E: DEVPATH=/devices/pci0000:00/0000:00:1c.0/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0boot1
E: DEVNAME=/dev/mmcblk0boot1
E: DEVTYPE=disk
E: DISKSEQ=12
E: MAJOR=179
E: MINOR=16
E: SUBSYSTEM=block
E: USEC_INITIALIZED=2021741
E: MMC_TYPE=MMC
E: ID_DRIVE_FLASH_MMC=1
E: ID_DRIVE_MEDIA_FLASH_MMC=1
E: ID_SERIAL=0x78dc46c8
E: ID_NAME=BJTD4R
E: ID_PART_TABLE_UUID=e55fc5b4-cbeb-4296-bf45-d38a585dc587
E: ID_PART_TABLE_TYPE=gpt
E: DEVLINKS=/dev/disk/by-diskseq/12
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1c.0/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0p1
M: mmcblk0p1
R: 1
U: block
T: partition
D: b 179:1
N: mmcblk0p1
L: 0
S: disk/by-id/mmc-BJTD4R_0x78dc46c8-part1
S: disk/by-uuid/29027a86-7544-49fe-b649-cc7f68a608ac
S: disk/by-partuuid/245e31d1-080b-c44e-9383-aa794fecc336
Q: 10
E: DEVPATH=/devices/pci0000:00/0000:00:1c.0/mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0p1
E: DEVNAME=/dev/mmcblk0p1
E: DEVTYPE=partition
E: DISKSEQ=10
E: PARTN=1
E: MAJOR=179
E: MINOR=1
E: SUBSYSTEM=block
E: USEC_INITIALIZED=2426217243
E: ID_SERIAL=0x78dc46c8
E: ID_NAME=BJTD4R
E: ID_PART_TABLE_UUID=e55fc5b4-cbeb-4296-bf45-d38a585dc587
E: ID_PART_TABLE_TYPE=gpt
E: ID_DRIVE_FLASH_MMC=1
E: ID_DRIVE_MEDIA_FLASH_MMC=1
E: ID_FS_UUID=29027a86-7544-49fe-b649-cc7f68a608ac
E: ID_FS_UUID_ENC=29027a86-7544-49fe-b649-cc7f68a608ac
E: ID_FS_VERSION=1.0
E: ID_FS_TYPE=ext4
E: ID_FS_USAGE=filesystem
E: ID_PART_ENTRY_SCHEME=gpt
E: ID_PART_ENTRY_UUID=245e31d1-080b-c44e-9383-aa794fecc336
E: ID_PART_ENTRY_TYPE=0fc63daf-8483-4772-8e79-3d69d8477de4
E: ID_PART_ENTRY_NUMBER=1
E: ID_PART_ENTRY_OFFSET=2048
E: ID_PART_ENTRY_SIZE=61067264
E: ID_PART_ENTRY_DISK=179:0
E: DEVLINKS=/dev/disk/by-id/mmc-BJTD4R_0x78dc46c8-part1 /dev/disk/by-uuid/29027a86-7544-49fe-b649-cc7f68a608ac /dev/disk/by-partuuid/245e31d1-080b-c44e-9383-aa794fecc336
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

P: /devices/pci0000:00/0000:00:1c.0/mmc_host/mmc0/mmc0:0001/mmcblk0rpmb
M: mmcblk0rpmb
U: mmc_rpmb
D: c 239:0
N: mmcblk0rpmb
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.0/mmc_host/mmc0/mmc0:0001/mmcblk0rpmb
E: DEVNAME=/dev/mmcblk0rpmb
E: MAJOR=239
E: MINOR=0
E: SUBSYSTEM=mmc_rpmb
```

**Comment by mvollmer** [comment]
Thanks! The only idea I have is to put a special case into Cockpit for devices called "mmcblk*boot*" and exclude them from multipath considerations. This is what UDisk2 does as well, essentially (recognizing them by name).

**Comment by mvollmer** [comment]
@onlineapps-cloud, can you test the fix in #20329 somehow? Let me know how I can help.

I think we can easily provide RPMs with the fix, but not Debian packages. Also, it's kind of a jump from 287 to the current 315 release of Cockpit.

**Comment by onlineapps-cloud** [comment]
hi, i can test tomorrow, but i have installed cockpit in debian 12, i unable to install another system on radxa at the momment, please give instruction, what i need to do to apply your fix on current installed system, thanks.

**Comment by martinpitt** [comment]
@mvollmer My proposal is to build the branch locally, attach a tarball of dist/storaged/ here, and then @onlineapps-cloud can unpack this in /usr/local/share/cockpit or ~/.local/share/cockpit for easy and safe testing.

**Comment by onlineapps-cloud** [comment]
hi, i saw that you closed my issue as fixed, how i can to test it? i just need to made apt update && apt upgrade of my system and cockpit will updated to latest version?

**Comment by jelly** [comment]
> hi, i saw that you closed my issue as fixed, how i can to test it? i just need to made apt update && apt upgrade of my system and cockpit will updated to latest version?

We release today, so it depends on when the backports are updated and what Ubuntu/Debian you run. But hopefully soon yes :)
