### ISSUE TITLE
dnf5 compatibility tracking issue

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#20260]
There is a Fedora 41 proposal to switch to dnf5 this impacts PackageKit and dnf-automatic. See [this proposal](https://lists.fedoraproject.org/archives/list/devel-announce@lists.fedoraproject.org/thread/VPEQZXEVN4TDGY6C3R5X7FQYQ7L656KG/).

Impact:

* [dnf-automatic becomes a plugin](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/OFF32IRC633C6ML4ZROQ3IJIZZYQIWSN/)
* [cli changes](https://dnf5.readthedocs.io/en/latest/changes.html#changes-on-the-command-line)

 - [x] confirm with dnf team how to configure the plugin: https://bugzilla.redhat.com/show_bug.cgi?id=2279258

**Comment by martinpitt** [comment]
I did an initial manual test for this. On our rawhide image:
```
dnf remove -y dnf-automatic
dnf5 install -y dnf5-plugin-automatic
```

This became structurally easier, there is now just one `dnf5-automatic.timer` (plus dnf-automatic.timer alias), no -*install variant any more. However, now I'm a bit lost -- https://dnf5.readthedocs.io/en/latest/changes.html says "Different configuration file locations and some changes in format", but the [manpage](https://dnf5.readthedocs.io/en/latest/dnf5_plugins/automatic.8.html#automatic-plugin-ref-label) still talks about `/etc/dnf/automatic.conf`. However, dnf5-plugin-automatic does not ship *any* config file, nor does any other package (`find /etc/dnf/ -name '*auto*'`), and the `dnf-automatic-notifyonly.timer` reference and "Some other timer units are provided" are clearly obsolete.

When I simulate a timer event with `systemctl start dnf5-automatic`, it merely download available updates (according to the journal). When I create a config according to the manpage:

```
# cat /etc/dnf/automatic.conf
[commands]
apply_updates = True
```
it still only uploads, so it doesn't really look at that file.
```
$ strace -e trace=file /usr/bin/dnf5 automatic
[...]
newfstatat(AT_FDCWD, "/etc/dnf/dnf5-plugins/automatic.conf", 0x7ffee3c912d0, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/share/dnf5/dnf5-plugins/automatic.conf", 0x7ffee3c912d0, 0) = -1 ENOENT (No such file or directory)
```
Aha! I moved the file to that place. When I run `dnf5 automatic` now, it installs packages.

I also tried to add "reboot = when-needed". My currently available updates include the kernel, and it correctly schedules a reboot after updates.

I filed https://bugzilla.redhat.com/show_bug.cgi?id=2279257 about the outdated manpage, and https://bugzilla.redhat.com/show_bug.cgi?id=2279258 about the missing config file. In the latter I also asked how exactly Cockpit is supposed to enable auto-upgrades with dnf5. I'll let the dnf team respond to that first before changing our code.

**Comment by jelly** [comment]
It seems dnf5 now is the default in rawhide and there no longer is an alias to dnf-automatic-install.timer. I've adjusted our tests in a PR so rawhide tests no longer fail.
