### ISSUE TITLE
Installation failure on latest release of FCOS 39

### ISSUE THREAD

**Issue by PeaceRebel** [cockpit-project/cockpit#20288]
### Explain what happens

Install cockpit-system and some related packages via systemd service that runs post first boot. After the installation and a reboot, I was enabling cockpit.socket via another systemd service. 

This is the output of `rpm-ostree status`
![image](https://github.com/cockpit-project/cockpit/assets/22352237/3058c3bc-b6dc-4152-8b46-93fd6818e061)

systemctl throws an error while trying to enable cockpit.socket as it's not present.

### Version of Cockpit

Latest version available in official fedora repo

### Where is the problem in Cockpit?

None

### Server operating system

Fedora

**Comment by PeaceRebel** [comment]
It fails the same way on manual installation on a running coreos instance. There are no logs that I could see.
![image](https://github.com/cockpit-project/cockpit/assets/22352237/e5c3ab5a-9c70-44e2-abbb-83089e4cfdfb)

**Comment by martinpitt** [comment]
> systemctl throws an error while trying to enable cockpit.socket as it's not preset.

Do you mean "present"? (May be a typo, but "preset" is a systemd thing, too) You have to install `cockpit-ws` (or the whole `cockpit` metapackage) to get that.

If you didn't mean "present", what is the particular error message?

**Comment by PeaceRebel** [comment]
> > systemctl throws an error while trying to enable cockpit.socket as it's not preset.
> 
> Do you mean "present"? (May be a typo, but "preset" is a systemd thing, too) You have to install `cockpit-ws` (or the whole `cockpit` metapackage) to get that.
> 
> If you didn't mean "present", what is the particular error message?

Typo, I meant 'present'.

There are not error messages during installation. Post install, when I try to enable `cockpit.socket` systemctl throws  `Unit cockpit.socket could not be found.`

Additionally, I had another instance of FCOS  with cockpit already up and running. I installed cockpit-pcp and cockpit-podman via cockpit terminal and rebooted. This had the same affect. Cockpit didn't come back up on reboot and the socket and service can't be found.

**Comment by PeaceRebel** [comment]
> You have to install cockpit-ws (or the whole cockpit metapackage) to get that.

Do you mean the socket is part of another package now? What about `cockpit.service`?

**Comment by martinpitt** [comment]
It has *always* been in the cockpit-ws package. cockpit.{socket,service} are both in there.

**Comment by martinpitt** [comment]
> Additionally, I had another instance of FCOS with cockpit already up and running

Did that actually have cockpit-ws.rpm installed? The more common approach on CoreOS is to run the [cockpit/ws container](https://quay.io/repository/cockpit/ws), that may just not be set up to automatically start on boot?

**Comment by PeaceRebel** [comment]
IIRC, I have never installed `cockpit-ws`. Never used the container either. Only installed cockpit-system and other extensions for ostree, network manager, etc. The socket and service are installed along with it.

**Comment by PeaceRebel** [comment]
My mistake.

**Comment by martinpitt** [comment]
That works if you connect to that machine through SSH, i.e. from a remote cockpit host. That's actually how we recommend it, don't install cockpit-ws onto production hosts.

**Comment by PeaceRebel** [comment]
Found out that the `cockpit-benchmark` extension from 45Drives has a dependency on cockpit metapackage. That was the magic.
