### ISSUE TITLE
consider adding `cockpit.assert()`

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#20298]
Now that we're using typescript, we're going to get into unfortunate situations where we'll have to do type narrowing.

One of the best tools for that is assertions, but since `console.assert()` doesn't actually abort the current control flow, typescript doesn't treat it as a guard.

Node's `assert()` function is different.  It raises an error if the predicate fails, interrupting the calling function.  Typescript has a syntax to support such functions:

```typescript
function assert(predicate: any): asserts predicate {
 ...
}
```

See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions

See https://github.com/cockpit-project/cockpit-files/pull/365 for a recent example of how this was handled:

```typescript
        if (typeof itemId === "string") {
            ....
        } else {
            console.error("unexpected itemId type", itemId);
        }
```

That doesn't feel great, and I'd prefer not to see it proliferate.  It's also going to cause issues with coverage reporting...

I'd prefer if we could add `cockpit.assert()` as a "hard assert" function, and annotate it accordingly.

**Comment by jelly** [comment]
I say this is a bad example, clearly PatternFly is wrongly typed here and should be fixed.

**Comment by allisonkarlitskaya** [comment]
> I say this is a bad example, clearly PatternFly is wrongly typed here and should be fixed.

I half-agree.  The `undefined` part of this is pretty bogus, but the `string | number` thing, but we know it's `string` is pretty legit, and we're going to run into issues like that a lot.  It's actually the worse case (since you can use `!` to deal with the `undefined` thing).

I know from our existing use of `mypy` that sometimes it's just unavoidable...

**Comment by martinpitt** [comment]
I wanted something like this several times already, and so far always resorted to the explicit `console.error()`.  Adding a helper for that and annotating it with `// not-covered: assertion` sounds nice!

**Comment by allisonkarlitskaya** [comment]
That's the nice thing, though: we wouldn't need the comment, because the assertion *would* run.

**Comment by martinpitt** [comment]
@allisonkarlitskaya I mean *inside* the definition of `cockpit.assert()` -- the console.error() would (hopefully) not be covered :grin:
