### ISSUE TITLE
TestHistoryMetrics.testEvents is flaky

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20302]
The job `fedora-39/updates-testing` failed on commit 48514705b6acf325a11ac1c1908941d1b98bc07d.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-48514705-20240412-012544-fedora-39-updates-testing/log.html

**Comment by martinpitt** [comment]
This initially looked like it may be systemd change, but  there's no systemd update here. Also, that test fails for me locally on a standard fedora-39 image without updates, so I think it's "just" a flake. The [weather report](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?days=7&repo=cockpit-project%2Fcockpit&test=test%2Fverify%2Fcheck-metrics+TestHistoryMetrics.testEvents) also has it at 25% failure rate.

**Comment by martinpitt** [comment]
Found it -- https://github.com/systemd/systemd/issues/28746 . This "worked" because in most cases the test is skipped as naughty match. Let's stop that, this is silly by now.
