### ISSUE TITLE
TestGrafanaClient.testBasic fails with pcp 6.2.1-1.fc3

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20327]
The job `fedora-39/updates-testing` failed on commit 18ec3fa7f02f38eab4644d7319d6e2ddf5acf66f.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-18ec3fa7-20240417-012533-fedora-39-updates-testing/log.html

**Comment by martinpitt** [comment]
Uh, that smells like a pcp regression, I'll investigate. Let's stop it in bodhi.

**Comment by martinpitt** [comment]
Argh, that was https://bodhi.fedoraproject.org/updates/FEDORA-2024-4c09d22f7e but it already went into stable, too fast.

I reported https://bugzilla.redhat.com/show_bug.cgi?id=2275408 . But also, we could robustify our test to be a little less demanding, I'll send a PR.
