### ISSUE TITLE
Manage Groups and Their Members

### ISSUE THREAD

**Issue by fridex** [cockpit-project/cockpit#2032]
Based on https://github.com/cockpit-project/cockpit/issues/644

Manage groups:
 * add a new group
 * delete a group
 * administer members of a group

**Comment by fridex** [comment]
Displaying a list of all groups for every user looks confusing according to https://github.com/cockpit-project/cockpit/pull/1877#issuecomment-76895671.

**Comment by stefwalter** [comment]
I don't yet understand what this is going to be used for. That said, there could be a use case here that I don't understand.

In Cockpit we do "Design Driven Development". Which means that for every significant feature we build a feature page, and document the workflow, tasks that should be accomplished etc. And then andreasn does wireframes.

Could you build a new feature page for this feature? Here's the template:

https://github.com/cockpit-project/cockpit/wiki/New-Features

If you look on the wiki you can see several other features listed as well.

While thinking about this feature: Remember that we would like to push people towards using IPA for group management across multiple servers. The local account management is really a stop gap to help people setup administrator accounts, change local passwords, very basic stuff.

**Comment by stefwalter** [comment]
No response in 9  months to the questions above. Closing for now. Can reopen if someone wants to pick this up.
