### ISSUE TITLE
Cockpit session recordings are not playing on web UI

### ISSUE THREAD

**Issue by dsputnikk** [cockpit-project/cockpit#20382]
### Explain what happens

1. Alma 9, install cockpit
2. Enable Session Recording (journal)
3. Start Terminal session in Web UI (see msg about record warning). Session Entry appears, user's input appears below "black" player but no video is shown.

Have tried Chromium and Firefox, on the server itself. I've tried localhost:9090 and m.y.i.p:9090

I'm on Alma 9. 
Cockpit 300.4 
cockpit-session-recording 13

Switching to file or syslog doesn't help. In fact, the session no longer appears as an entry, whether file or syslog. However in file mode, I do get a file in my /tmp directory which I can successfully playback with `tlog-play -i thefilename`.

I can find no hard errors from sssd or cockpit or selinux.

I see browser warnings for po.js not loading, but other github comments tell me to ignore it.

### Version of Cockpit

300.4

### Where is the problem in Cockpit?

Terminal

### Server operating system

other

### Server operating system version

Alma 9, up-to-date as of writing

### What browsers are you using?

Firefox, Chrome

**Comment by martinpitt** [comment]
Already reported to https://github.com/Scribery/cockpit-session-recording/issues/174
