### ISSUE TITLE
SELinux test flake

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#20396]
`TestSelinux.testTroubleshootAlerts` started to flake over the weekend with:

https://cockpit-logs.us-east-1.linodeobjects.com/pull-20380-a577af7a-20240429-073335-rhel-9-4-other/log.html#43-2

This seems pretty obvious when you reproduce it:

ansible machine
```
[root@fedora-40-127-0-0-2-2201 ~]# semanage export
boolean -D
login -D
interface -D
user -D
port -D
node -D
fcontext -D
module -D
ibendport -D
ibpkey -D
permissive -D
boolean -m -1 httpd_enable_homedirs
boolean -m -1 selinuxuser_execmod
boolean -m -1 virt_sandbox_use_all_caps
boolean -m -1 virt_use_nfs
boolean -m -1 zebra_write_config
fcontext -a -f a -t samba_share_t -r 's0' '/var/tmp/'
permissive -a rhcd_t
```

Test machine
```
[root@rhel-9-5-127-0-0-2-2201 ~]# semanage export
boolean -D
login -D
interface -D
user -D
port -D
node -D
fcontext -D
module -D
ibendport -D
ibpkey -D
permissive -D
boolean -m -1 httpd_enable_homedirs
boolean -m -1 virt_sandbox_use_all_caps
boolean -m -1 virt_use_nfs
boolean -m -1 zebra_write_config
fcontext -a -f a -t samba_share_t -r 's0' '/var/tmp/'
permissive -a rhcd_t
```

The ansible machine has a new `boolean -m -1 selinuxuser_execmod`. This happens on all machines where we tested SELinux

**Comment by martinpitt** [comment]
I just fixed that on the rhel-8 branch: https://github.com/cockpit-project/cockpit/commit/3a6136db126c5b7aaf0cf5980ff783ed83bb5994

But how did that get past https://github.com/cockpit-project/bots/pull/6281 .. :thinking:

**Comment by martinpitt** [comment]
Ah! https://github.com/cockpit-project/bots/pull/6281didn't run against rhel-9-4, only Fedora
