### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by ChandlerAx** [cockpit-project/cockpit#20406]
Page: 

When creating a user in Cockpit on version 164 of Ubuntu 18, the user is granted administrator privileges by default, allowing them to view all settings and resources within Cockpit. However, this behavior occurs even when the "Administrator" checkbox is not selected during user creation, indicating a discrepancy between the intended user privileges and the actual permissions granted.

Also add better user management so we can, for example, create a user and assign a VM to that user

**Comment by jelly** [comment]
The current version of Cockpit is 316, (164 was 6 years ago). The users page has been drastically changed, please re-check this functionality with a recent Cockpit.

The current create user dialog has no way to give admin privileges:

![image](https://github.com/cockpit-project/cockpit/assets/67428/59c43610-68f1-4999-9c74-24f193951a8b)
