### ISSUE TITLE
Duplicate name error for containers is not inline

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2041]
If I try naming a new container with a name of an already running container, I get a dialog poping up saying:

"Conflict. The name "wordpress-site-1" is already in use by container 4c195f39e10f. You have to delete (or rename) that container to be able to reuse that name. "

This would be nice to have inline. Obviously needs shorter error text in that case.

**Comment by andreasn** [comment]
Mockup:
![screenshot from 2015-04-08 11 59 07](https://cloud.githubusercontent.com/assets/209895/7043042/b2239760-dde6-11e4-9be5-9d2c8115b7eb.png)

**Comment by stefwalter** [comment]
Accidentally closed this bug instead of #3041

**Comment by martinpitt** [comment]
I just checked current master, and it seems alright now:

![Uploading conflicting-name.png…]()

Closing. @andreasn , please reopen if you still think this is wrong.
