### ISSUE TITLE
Enrolling with a tang keyserver for NBDE fails on atomic hosts

### ISSUE THREAD

**Issue by sgallagher** [cockpit-project/cockpit#20419]
### Explain what happens

# Steps to reproduce
1. Install a Fedora Atomic Desktop system (Silverblue, Kinoite, etc.)
2. During installation, configure full-disk encryption with a passphrase
3. After installation, install cockpit and clevis via rpm-ostree and reboot.
`rpm-ostree install cockpit cockpit-storaged clevis clevis-dracut clevis-udisks2`
4. Log into Cockpit with an administrative user
5. In the storage interface, add a key. Select "Tang keyserver" and enter the appropriate address and the keyphrase set during OS installation.
6. When the tang server returns the key for validation, click "Trust Key"

## Expected result
The system is enrolled with the tang server and is properly unlocked when booting if the tang server is reachable.

## Actual result
A red banner showing `(!) not-found` is shown at the top of the "Verify key" page.

Enabling `window.debugging = 'spawn'` in the javascript console results in the following message:
```
process spawn: ["grubby","--update-kernel=ALL","--args=rd.neednet=1"] cockpit.js:6:968
process closed: {"problem":"not-found","command":"close","channel":"2:5!6093"}
```

Grubby is not usable on ostree systems because initramfs regeneration is complicated. However, since Cockpit is only trying to add a kernel argument, it would probably be best to have it just use the `rpm-ostree kargs --append-if-missing rd.neednet=1` command on ostree systems.

### Version of Cockpit

cockpit-316-1.fc40.x86_64

### Where is the problem in Cockpit?

Storage

### Server operating system

Fedora

### Server operating system version

Fedora Kinoite 40

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
Thanks! Indeed pkg/storaged/crypto/keyslots.jsx only calls grubby. We already have a [kernelopt.sh script](https://github.com/cockpit-project/cockpit/blob/main/pkg/systemd/kernelopt.sh) which does it correctly, we just need to use it for NBDE as well.

**Comment by sgallagher** [comment]
Sorry, I didn't get a chance to test this until 317 was released, but it's still not working (though it breaks in a new place).
![nbde-fail](https://github.com/cockpit-project/cockpit/assets/739555/bdc51074-ec0b-4f35-8b4e-2ceea4cb65f5)

```
$ rpm-ostree status
State: idle
Deployments:
  fedora:fedora/40/x86_64/kinoite
                  Version: 40.20240606.0 (2024-06-06T00:43:46Z)
               BaseCommit: 7a8e9ef139f942aeef07fe3a0ce28d3e9d47aa914f094632c8ac98450e3c5db0
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
          LayeredPackages: /usr/bin/virsh clevis clevis-dracut clevis-udisks2 cockpit cockpit-machines cockpit-selinux ksshaskpass libvirt postgresql powerline-fonts powerline-go python3-gssapi python3-pip
                           virt-manager zsh
            LocalPackages: redhat-internal-cert-install-0.1-30.el7.csb.noarch redhat-internal-NetworkManager-openvpn-profiles-0.1-54.el7.csb.noarch
                           redhat-internal-NetworkManager-openvpn-profiles-non-gnome-0.1-54.el7.csb.noarch redhat-internal-openvpn-profiles-0.1-54.el7.csb.noarch

● fedora:fedora/40/x86_64/kinoite
                  Version: 40.20240606.0 (2024-06-06T00:43:46Z)
               BaseCommit: 7a8e9ef139f942aeef07fe3a0ce28d3e9d47aa914f094632c8ac98450e3c5db0
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
          LayeredPackages: /usr/bin/virsh clevis clevis-dracut clevis-udisks2 cockpit cockpit-machines cockpit-selinux ksshaskpass libvirt postgresql powerline-fonts powerline-go python3-gssapi python3-pip
                           virt-manager zsh
            LocalPackages: redhat-internal-cert-install-0.1-30.el7.csb.noarch redhat-internal-NetworkManager-openvpn-profiles-0.1-54.el7.csb.noarch
                           redhat-internal-NetworkManager-openvpn-profiles-non-gnome-0.1-54.el7.csb.noarch redhat-internal-openvpn-profiles-0.1-54.el7.csb.noarch

  fedora:fedora/40/x86_64/kinoite
                  Version: 40.20240605.0 (2024-06-05T00:45:00Z)
               BaseCommit: 28c52fa53e435b6b197ec3af71743ae235308f32d4dfa4a931698d90bdf2d4ad
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
          LayeredPackages: /usr/bin/virsh clevis clevis-dracut clevis-udisks2 cockpit cockpit-machines cockpit-selinux ksshaskpass libvirt postgresql powerline-fonts powerline-go python3-gssapi python3-pip
                           virt-manager zsh
            LocalPackages: redhat-internal-cert-install-0.1-30.el7.csb.noarch redhat-internal-NetworkManager-openvpn-profiles-0.1-54.el7.csb.noarch
                           redhat-internal-NetworkManager-openvpn-profiles-non-gnome-0.1-54.el7.csb.noarch redhat-internal-openvpn-profiles-0.1-54.el7.csb.noarch
```

I already have `clevis-dracut` installed as an overlay package, so it shouldn't be trying to install it.

**Comment by martinpitt** [comment]
@sgallagher That has a different root cause. I split this out into #20602.
