### ISSUE TITLE
Storage page device table started producing accesibility warning

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#20457]
Page: 

warning: Th: Table headers must have an accessible name. If the Th is intended to be visually empty, pass in screenReaderText. If the Th contains only non-text, interactive content such as a checkbox or expand toggle, pass in an aria-label.

**Comment by martinpitt** [comment]
Funny you should ask *now* :grin: @mvollmer is just fixing that in #20358.

**Comment by mvollmer** [comment]
> Funny you should ask _now_ 😁 @mvollmer is just fixing that in #20358.

Actually, the Storage page uses `Table` directly, so #20358 is not going to fix this. But as soon as we have decided what to do in #20358, I'll do the same wherever we get this warning, such as in pkg/storaged and c-machines.

**Comment by mvollmer** [comment]
good-first-issue, haha... :-)
