### ISSUE TITLE
nightly tests failed: sosreport times out

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20488]
The job `fedora-40/updates-testing` failed on commit f0d0c718208205a8ff6d8803f561cb31e80441f4.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-f0d0c718-20240520-012823-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment]
It's not sosreport itself which updated -- the last bodhi update was 3 weeks ago. Apparently some of the other updates make it take very/too long. It failed last night as well.

**Comment by martinpitt** [comment]
The [journal attachment](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-f0d0c718-20240520-012823-fedora-40-updates-testing/TestSOS-testVerbose-fedora-40-127.0.0.2-2201-FAIL-1.log.gz) has a "nice" kernel crash.

But I can't reproduce this locally at all. I ran `TEST_OS=fedora-40 TEST_SCENARIO=updates-testing test/run` and confirmed that the image has packages from updates-testing. Running just the single test finishes in 27s, 5 times in a row. So perhaps some garbage from previous tests?

```
test/verify/check-examples TestXHRProxy.testBasic $RUNC
test/verify/check-packagekit TestUpdates.testBasic $RUNC
test/verify/check-superuser TestSuperuser.testWrongPasswd $RUNC
test/verify/check-superuser TestSuperuser.testRemoveBridgeConfig $RUNC
test/verify/check-superuser TestSuperuser.testBrokenBridgeConfig $RUNC
test/verify/check-storage-used TestStorageUsed.testUsed $RUNC
test/verify/check-storage-nfs TestStorageNfs.testNfsListExports $RUNC
test/verify/check-storage-mounting TestStorageMountingLUKS.testDuplicateMountPoints $RUNC
test/verify/check-storage-lvm2 TestStorageLvm2.testUnpartitionedSpace $RUNC
test/verify/check-storage-lvm2 TestStorageLvm2.testMaxLayoutGrowth $RUNC
test/verify/check-storage-ignored TestStorageIgnored.testIgnored $RUNC
test/verify/check-storage-hidden TestStorageHidden.testHiddenRaid $RUNC
test/verify/check-storage-format TestStorageFormat.testAtBoot $RUNC
test/verify/check-storage-anaconda TestStorageAnaconda.testBasic $RUNC
test/verify/check-system-services TestServices.testBasicSession $RUNC
test/verify/check-sosreport TestSOS.testVerbose $RUNC
```

But that also works fine, and the other sos report test crashed the same way on a different VM, so unrelated tests.

**Comment by martinpitt** [comment]
Oh! My VM is still running kernel-core-6.8.9-300.fc40.x86_64 and dnf doesn't "see" 6.8.10 from https://bodhi.fedoraproject.org/updates/FEDORA-2024-92664ae6fe . How can that be, it moved to stable 3 days ago.. Some Germany mirror being severely out of date?

```
dnf install -y https://kojipkgs.fedoraproject.org//packages/kernel/6.8.10/300.fc40/x86_64/kernel-core-6.8.10-300.fc40.x86_64.rpm https://kojipkgs.fedoraproject.org//packages/kernel/6.8.10/300.fc40/x86_64/kernel-modules-core-6.8.10-300.fc40.x86_64.rpm && reboot
```

And now it reproduces fine, after starting the NFS server:
```
test/verify/check-storage-nfs TestStorageNfs.testNfsListExports $RUNC
test/verify/check-sosreport TestSOS.testVerbose $RUNC -stv
```

And without cockpit:
```
systemctl start nfs-server
sos report --batch
```

causes the kernel crash and hangs at
```
  Starting 50/101 multipath       [Running: dnf logs memory multipath]
  Starting 51/101 networking      [Running: dnf logs multipath networking]
  Starting 52/101 networkmanager  [Running: dnf logs networking networkmanager]
```

Reported to https://bugzilla.redhat.com/show_bug.cgi?id=2282287 , created https://github.com/cockpit-project/bots/issues/6411 and a naughty PR: https://github.com/cockpit-project/bots/pull/6412
