### ISSUE TITLE
cockpit-machines not updating on Alma Linux?

### ISSUE THREAD

**Issue by mtopolinski** [cockpit-project/cockpit#20503]
### Explain what happens

Sorry I'm very new to Cockpit and am trying to assist another team with some issues, is this correct?

cockpit
    311.1
cockpit-bridge
    311.1
cockpit-machines
    308
cockpit-packagekit
    311.1
cockpit-system
    311.1
cockpit-ws
    311.1
    
    Should cockpit-machines be a different version than the other cockpit utilities? I tried running yum update cockpit-machines but it reports it's at the latest version. 

### Version of Cockpit

311.1

### Where is the problem in Cockpit?

Software updates

### Server operating system

other

### Server operating system version

AlmaLinux 9.4 (Seafoam Ocelot)

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
> Should cockpit-machines be a different version than the other cockpit utilities? I tried running yum update cockpit-machines but it reports it's at the latest version. 

Yes, c-machines is an [indepentent project](https://github.com/cockpit-project/cockpit-machines) with different version numbers. 311.1 is indeed the RHEL 9.4 version.
