### ISSUE TITLE
make isn't finding some tools in Debian Jessie

### ISSUE THREAD

**Issue by hashworks** [cockpit-project/cockpit#2051]
After running autoconf.sh (which worked fine) make tells me that it isn't finding some tools:
```
[...]
WARNING: '../tools/r.js' is missing on your system.
[...]
Makefile:7038: recipe for target 'pkg/base1/cockpit.min.css' failed
make[2]: *** [pkg/base1/cockpit.min.css] Error 127
[...]
```

Repeadingly running make results in more tools missing, f.e. jshint and uglifyjs. However all of them exist in the tools folder.

What I did:
```bash
apt-get install nodejs npm intltool xsltproc libsystemd-journal-dev libjson-glib-dev libpolkit-agent-1-dev libudisks2-dev libaccountsservice-dev libssh-dev libdbus-1-dev libkeyutils-dev libpcp3-dev libpcp-import1-dev xmlto
cd /usr/local/src
git clone https://github.com/cockpit-project/cockpit
cd cockpit
mkdir build
cd build
../autogen.sh --prefix=/usr --enable-maintainer-mode --enable-debug > ~/autogen.log 2>&1
make > ~/make.log 2>&1
``` 

full autogen.log: http://pastebin.com/ftm2SVyj
full make.log: http://pastebin.com/k10YeJ6p

`ls /usr/local/src/cockpit/tools`
```
cockpit-container-run  depcomp                glib.supp      jsbundle           make-srpm     pcp.supp         r.js           travis.supp
cockpit-preview.repo   Dockerfile             htmlmin.conf   jshint             missing       po2json          simple-tap.js  uglifycss
cockpit.spec           frob-catmsgs           html-minifier  jshint.conf        node_modules  pthread.supp     tap-driver     uglifyjs
compile                gcrypt.supp            install-sh     Makefile-tools.am  package.json  qunit-config.js  tap-gtester    unknown.supp
cssbundle              gdbus-unbreak-codegen  intltool.m4    make-rpms          parsejson     reporter.js      tap-phantom    zlib.supp
```

**Comment by stefwalter** [comment]
The ```npm install``` didn't seem to do anything. We use it to install a local copies of various nodejs development dependencies. Note that these dependencies should not be needed to build from the tarball, only when building from git.

It could be that it behaves differently on Jesse. Can you run the following commands, and post the output?

```
$ cd tools
$ npm install
```

**Comment by hashworks** [comment]
I guess I've run autoconf twice by accident, so the log is empty. npm install definitly installed something on the first run, now it just returns nothing (as you did expect).

**Comment by stefwalter** [comment]
requirejs is definitely in package.json. If you see this problem again, post here and we can reopen this issue.
