### ISSUE TITLE
rawhide started to fail storage tests

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#20520]
[example 1](https://artifacts.dev.testing-farm.io/245e67af-7142-427f-abb7-73f37d257fa5/), [example 2](https://artifacts.dev.testing-farm.io/1db96d05-a232-48e6-a27b-a124847bda58/)

----

Many tests fail with "warning: Error wiping newly created partition /dev/sda1: Failed to open the device '/dev/sda1': Device or resource busy"

This happens inside UDisks2 where it creates a partition and proceeds to modify and wipe it.  No idea what other thing keeps it busy. UDisks2 does take a lock on the partition table block device to stop udev from doing it BLKRRPART ioctl at the wrong time. wipefs does a regular open(2) so EBUSY means that the block device is "in use by the system".

I can't reproduce this outside of TF, unfortunately. I'll check what kind of things are happening during the test...

**Comment by martinpitt** [comment]
This also started to break selinux-policy tests in e.g. https://github.com/fedora-selinux/selinux-policy/pull/2136 or https://github.com/fedora-selinux/selinux-policy/pull/2137 , e.g. [this failure](https://artifacts.dev.testing-farm.io/9bc34465-eed9-4b72-99e1-0f4df5ef22f3/). Escalating to "urgent".

**Comment by mvollmer** [comment]
My best shot: https://github.com/cockpit-project/cockpit/pull/20527

I can't explain why, but scsi_debug starting to show problems with partitions fits the pattern of recent kernel releases.

**Comment by martinpitt** [comment]
I tried to reproduce this locally with `tmt`. @mvollmer you mentioned some troubles -- the trick is to run tmt from a *clean tree*, as it copies the whole tree into the test VM (even twice). I. e. if it has `node_modules/` and possibly even test/images/ in it, that's going to be very big. I disabled most tests, as on production the very fist storage test (TestStorageswap.testEncrypted) already fails, and then it seems very consistent. In my test reorg PR #20524 it is even the [very first test which fails already](https://artifacts.dev.testing-farm.io/c74855e8-33c5-4fc5-adf2-002bad0aa54e/).

But locally it passes. `dnf update` also has nothing to do. Both local qemu and production TF run kernel 6.9.0-64.

So I tried with [tmt CLI](https://docs.testing-farm.io/Testing%20Farm/0.1/cli.html)  and `TESTING_FARM_API_TOKEN=secret testing-farm reserve --duration 720`, and got a [reservation](https://artifacts.dev.testing-farm.io/9a14cd38-3d82-45e0-9964-65fcf67802e6/). Then I ran

    tmt run --until report provision --how connect --user root --guest 52.15.254.166

so that it would install all the packages and do its other provisioning setup. I'm following along in ssh with `journalctl -f`. This reproduces it, so now I have an SSH session which exhibits the problem. I'll let the test finish (the retries take very long), and then see if I can get a sequence of CLI commands that reproduce the problem.

**Comment by martinpitt** [comment]
Test finished. In that VM, *without* scsi_debug loaded, there is already a /dev/sda1:
```
lrwxrwxrwx. 1 root root 7 May 29 03:52 /dev/sda1 -> nvme0n1
lrwxrwxrwx. 1 root root 9 May 29 03:52 /dev/sda11 -> nvme0n1p1
lrwxrwxrwx. 1 root root 9 May 29 03:52 /dev/sda12 -> nvme0n1p2
lrwxrwxrwx. 1 root root 9 May 29 03:52 /dev/sda13 -> nvme0n1p3
lrwxrwxrwx. 1 root root 9 May 29 03:52 /dev/sda14 -> nvme0n1p4
```
But `modprobe scsi_debug dev_size_mb=100` claims
[ 1558.119779] sd 0:0:0:0: Attached scsi generic sg0 type 0
[ 1558.121976] sd 0:0:0:0: [sda] 204800 512-byte logical blocks: (105 MB/100 MiB)
[ 1558.129760] sd 0:0:0:0: [sda] Write Protect is off
```
So indeed there's now a /dev/sda, but that's bogus -- the minute we'd try to create a partition on it, it'll fail as sda1 is already a thing for an entirely different device (the primary partition). Trying to run the two partitioning commands
```
parted -s /dev/sda mktable msdos
parted -s /dev/sda mkpart primary ext2 1M 25
```
then doesn't actually create any new /dev/sda*

This also explains why we only get this on TF machines -- local VMs wouldn't have that NVME link.

udev db says:
```
P: /devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1
M: nvme0n1
R: 1
U: block
T: disk
D: b 259:0
N: nvme0n1
L: 0
S: disk/by-id/nvme-Amazon_Elastic_Block_Store_vol07cc26dbe569d6c3e-ns-1
S: disk/by-id/nvme-uuid.9d1960b3-f466-5633-94c1-19fa4575cf54
S: disk/by-path/pci-0000:00:04.0-nvme-1
S: disk/by-id/nvme-Amazon_Elastic_Block_Store_vol07cc26dbe569d6c3e_1
S: disk/by-diskseq/1
S: disk/by-id/nvme-Amazon_Elastic_Block_Store_vol07cc26dbe569d6c3e
S: sda1

P: /devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/nvme0n1p1
M: nvme0n1p1
R: 1
U: block
T: partition
D: b 259:1
N: nvme0n1p1
L: 0
S: disk/by-diskseq/1-part1
S: sda11
```
so it's rather insistent on claiming the "sda1" name.

So there's some udev rule which does that. My eyes are on /usr/lib/udev/rules.d/70-ec2-nvme-devices.rules  (amazon-ec2-utils-2.2.0-2.fc41.noarch) or /usr/lib/udev/rules.d/62-multipath.rules.

I can simulate the failure in a local `test/image-prepare -q fedora-rawhide` with `TEST_OS=fedora-rawhide test/verify/check-storage-used TestStorageUsed.testUsed $RUNC` if I run `ln -s vda1 /dev/sda1` after vm-run. But of course that's uninteresting now -- we know what causes it, we now need to debug why we get these bogus symlinks on the TF machine.

**Comment by martinpitt** [comment]
`udevadm test /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1` doesn't show the symlink:
```
Device node symlinks: (priority=0)
  /dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol07cc26dbe569d6c3e-ns-1
  /dev/disk/by-path/pci-0000:00:04.0-nvme-1
  /dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol07cc26dbe569d6c3e_1
  /dev/disk/by-diskseq/1
  /dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol07cc26dbe569d6c3e
  /dev/disk/by-id/nvme-uuid.9d1960b3-f466-5633-94c1-19fa4575cf54
```

But that directory looks "interesting" :eyes: 
```
# ls -l /dev/disk/by-diskseq/
total 0
lrwxrwxrwx. 1 root root 13 May 29 03:52 1 -> ../../nvme0n1
lrwxrwxrwx. 1 root root 11 May 29 04:07 10 -> ../../loop0
lrwxrwxrwx. 1 root root 10 May 29 04:07 12-part1 -> ../../sda1
lrwxrwxrwx. 1 root root 10 May 29 04:07 13-part1 -> ../../sda1
lrwxrwxrwx. 1 root root 10 May 29 04:07 14-part1 -> ../../sda1
lrwxrwxrwx. 1 root root 10 May 29 04:30 18-part1 -> ../../sda1
lrwxrwxrwx. 1 root root 15 May 29 03:52 1-part1 -> ../../nvme0n1p1
lrwxrwxrwx. 1 root root 15 May 29 03:52 1-part2 -> ../../nvme0n1p2
lrwxrwxrwx. 1 root root 15 May 29 03:52 1-part3 -> ../../nvme0n1p3
lrwxrwxrwx. 1 root root 15 May 29 03:52 1-part4 -> ../../nvme0n1p4
lrwxrwxrwx. 1 root root 10 May 29 04:04 5-part1 -> ../../sda1
lrwxrwxrwx. 1 root root 10 May 29 04:05 6-part1 -> ../../sda1
lrwxrwxrwx. 1 root root 10 May 29 04:06 7-part1 -> ../../sda1
```

Also, after rebooting the VM the symlinks are gone. Unfortunately the advertised `tmt-reboot` doesn't work:
```
/usr/local/bin/tmt-reboot-core: line 23: : No such file or directory
/usr/local/bin/tmt-reboot-core: line 24: kill: `': not a pid or valid job spec
```
and after `reboot` I only get a shell for a few seconds after it shuts down automatically -- my reservation is now gone. But I can easily get a new one.

**Comment by martinpitt** [comment]
I pushed a hack attempt to #20524 . I'll try to get another hour of sleep :yawning_face: and then check the result.

**Comment by martinpitt** [comment]
Freshly reserved machine:
 - /dev/sda* symlinks exist right after booting, before any test
 - `rm -f /dev/sda1; udevadm trigger /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1` brings back the symlink.
 - after `mv /usr/lib/udev/rules.d/70-ec2-nvme-devices.rules{,.disabled}` the symlink doesn't come back any more. Sanity check: Moving it back and re-triggering brings back the symlink
 - That rule has
```
KERNEL=="nvme[0-9]*n[0-9]*",        ENV{DEVTYPE}=="disk",      ATTRS{model}=="Amazon Elastic Block Store", PROGRAM="/usr/sbin/ebsnvme-id -u /dev/%k", SYMLINK+="%c"
KERNEL=="nvme[0-9]*n[0-9]*p[0-9]*", ENV{DEVTYPE}=="partition", ATTRS{model}=="Amazon Elastic Block Store", PROGRAM="/usr/sbin/ebsnvme-id -u /dev/%k", SYMLINK+="%c%n"
```
and
```
# /usr/sbin/ebsnvme-id -u /dev/nvme0n1
sda1
```
- Upstream link: https://github.com/amazonlinux/amazon-ec2-utils/blob/main/70-ec2-nvme-devices.rules
- However, the last commit there was in 2022. But the [Fedora package](https://src.fedoraproject.org/rpms/amazon-ec2-utils/commits/rawhide) has only existed for 20 days, see [bodhi history](https://bodhi.fedoraproject.org/updates/?packages=amazon-ec2-utils).
