### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by John-Vacacela** [cockpit-project/cockpit#20534]
![image](https://github.com/cockpit-project/cockpit/assets/134348747/851c2356-c80d-4467-ad19-a997675a9cb8)

I need help with this problem, I'm trying to install cockpit with the source code.

**Comment by jelly** [comment]
What version of nodejs is this, it sounds like it's very old and likely not supported by us. We likely need nodejs 18 or higher

**Comment by jelly** [comment]
No response.
