### ISSUE TITLE
TestAD.testUnqualifiedUsers triggered page oops (minified react errror)

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20547]
The job `fedora-40/daily` failed on commit b3f3cd070f11903e30917ab23a6193a1adc7e3b7.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-b3f3cd07-20240605-012920-fedora-40-daily/log.html

**Comment by martinpitt** [comment]
This isn't specific to updates-testing -- our [weather report](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?test=test%2Fverify%2Fcheck-system-realms+TestAD.testUnqualifiedUsers) has this as a common flake, 47% on centos-10, and still 21% on fedora 40. 

The decoded error is

> Objects are not valid as a React child (found: object with keys {problem, exit_status, exit_signal, message, toString}). If you meant to render a collection of children, use an array instead.

I.e. something is trying to render an error object directly on the page.

I tried to run this locally in a loop, doesn't reproduce.

Fortunately this also happens in  [/devel](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20551-e32d4bc5-20240605-120752-fedora-40-devel/log.html#329) with a better error message.

**Comment by martinpitt** [comment]
This reproduces [reliably](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20556-962fc79c-20240606-075211-fedora-40-network-devel-2/log.html#388) in #20556. So I trust that amplification to confirm a fix.

This happens late in the game, after clicking "Reboot" -- after that, it's game over for the session anyway, and we expect the "disconnected" curtain anyway. But apparently sometimes it still manages to get an error.

```
-> ph_mouse("#shutdown-dialog button:contains(Reboot):not([disabled]):not([aria-disabled=true])","click",0,0,0,false,false,false,false)
<- {'type': 'undefined'}
-> switch to frame None
-> wait: ph_is_present(".curtains-ct h1")
Connection to 127.0.0.2 closed by remote host.
> warning: [BrokenPipeError] [Errno 32] Broken pipe
> warning: [BrokenPipeError] [Errno 32] Broken pipe
> warning: [BrokenPipeError] [Errno 32] Broken pipe
> warning: [BrokenPipeError] [Errno 32] Broken pipe
> warning: [BrokenPipeError] [Errno 32] Broken pipe
> warning: [BrokenPipeError] [Errno 32] Broken pipe
> warning: [BrokenPipeError] [Errno 32] Broken pipe
overview.js:5653:41)","overflow":false,"properties":[{"name":"stack","type":"string","value":"Error: Objects are not valid as a React child (fou…91/cockpit/@localhost/system/overview.js:5653:41)"},{"name":"message","type":"string","value":"Objects are not valid as a React child (found: obj…r a collection of children, use an array instead."}]}},"executionContextId":6}
```
