### ISSUE TITLE
Tests failed on new random unrelated SELinux messages

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20542]
The job `fedora-40/updates-testing` failed on commit 3b9c57223cf484cde049cd6151151c831db28131.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-3b9c5722-20240604-012922-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment]
Gazillions of SELinux messages, like
```
type=AVC msg=audit(04/10/2036 04:10:00.915:1044) : avc:  denied  { getattr } for  pid=3244 comm=systemd-fstab-g path=/boot/efi dev="vda2" ino=1 scontext=system_u:system_r:systemd_fstab_generator_t:s0 tcontext=system_u:object_r:dosfs_t:s0 tclass=dir permissive=0

type=AVC msg=audit(04/10/2036 04:10:00.934:1045) : avc:  denied  { search } for  pid=3253 comm=systemd-rc-loca name=journal dev="tmpfs" ino=49 scontext=system_u:system_r:systemd_rc_local_generator_t:s0 tcontext=system_u:object_r:syslogd_var_run_t:s0 tclass=dir permissive=0
```
They don't break our tests, but are either a regression of systemd 255.7-1.fc40 or selinux-policy 40.21-1.fc40.

**Comment by martinpitt** [comment]
Ah, this was https://bodhi.fedoraproject.org/updates/FEDORA-2024-35b6a83b02 and it was already unpushed. So ignoring this, but also let this be a chance to dial down which kind of messages break our tests?

**Comment by martinpitt** [comment]
The two recent duplicates above are *different* failures, but still completely unrelated to cockpit.

**Comment by martinpitt** [comment]
Reopening.. This happens on F40 updates-testing as well.
