### ISSUE TITLE
TestServices.testBasic pixel fail due to appearing service unit memory

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20571]
The job `fedora-40/daily` failed on commit f6a38027bd4116d55c4728fc75aed9557330480b.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-f6a38027-20240610-013007-fedora-40-daily/log.html

**Comment by martinpitt** [comment]
[Interesting!](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-f6a38027-20240610-013007-fedora-40-daily/pixeldiff.html#TestServices-testBasic-details-test-fail) Memory controller now on by default? Or is that a race? Let's see tomorrow.
