### ISSUE TITLE
Administrator accounts alignment off

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2060]
![screenshot from 2015-03-30 15 08 11](https://cloud.githubusercontent.com/assets/209895/6896720/b51a523c-d6ee-11e4-86b1-284df184753b.png)

**Comment by andreasn** [comment]
Hups, this was on a branch. Ignore.

**Comment by andreasn** [comment]
Realized it actually happens on master too.
It happens in the cases the "Real Name" field is blank.

**Comment by dperpeet** [comment]
I saw this before, but I'm not sure what the proper way would be to fix this.
Possible workaround (I tested this in the browser) is to have whitespace in the "Real Name" field, e.g. `&nbsp;`. I didn't do a pr with this because it doesn't seem like a clean solution...

**Comment by andreasn** [comment]
That was pretty much what I could come up with for fixing it as well.
Another way is to do
.cockpit-account > .cockpit-account-real-name {
display: block;
min-height: 30px;
}

**Comment by dperpeet** [comment]
I think fixing the style is better. Otherwise we change content and add invisible whitespace to prevent the ui from breaking...
