### ISSUE TITLE
uploads not working in WebKit

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#20615]
I thought it might be fun to test uploading from localhost to localhost.  I was surprised to get a file chooser dialog, and access to my entire home directory!  Yay for xdg portal, I guess...

This was less exciting, though:

![image](https://github.com/cockpit-project/cockpit/assets/36541154/0e81bc20-0d6b-45ef-bc34-cf2b60d309f3)

_Originally posted by @allisonkarlitskaya in https://github.com/cockpit-project/cockpit/issues/20614#issuecomment-2175523464_

**Comment by allisonkarlitskaya** [comment]
Near as I can tell, this is some very confusing way of saying that the Blob implementation for a selected file in webkit implements the ReadableStream interface, but not in BYOB mode.

So the solution here would be to use non-BYOB mode, but that's gonna suck: if memory serves, in testing on Chromium, I was getting handed 2MB chunks, which is enough to fill the entire window in one shot.  If we were to "just switch" then we'd have to fill the entire window, wait for it to completely arrive on the other end, then repeat, leaving gaps in the transmission (and dramatically reduced throughput, depending on the connection latency).

It also means that our progress bar will only update once every 2MB.

Two approaches to solving this:
 - fiddle with the window sizes.  We were thinking about increasing those anyway, since they were decided a decade or two ago...
 - if we can't BYOB then take the buffer we get and split it into our preferred block size before transmitting it, effectively emulating the old behaviour, but more complicated.

**Comment by garrett** [comment]
I get this on GNOME Web on Linux, and also on macOS Safari. Here's a screenshot from macOS Safari:

![image](https://github.com/cockpit-project/cockpit/assets/10246/8bd66d7f-4fe3-471a-a679-8cba50e5e166)

(Nothing exciting; it looks just the same.)

**Comment by allisonkarlitskaya** [comment]
I tried dropping the byob and this happened:

```
WebSocket-Message: 11:28:58.532: server is trying to frame of size 524294 or greater, but max supported size is 128KiB
WebSocket-Message: 11:28:58.532: Received extremely large WebSocket data from the server
```

which is promising, but rules out option 1 ("fiddle with the window").  The browser is handing us a large chunk (probably ~2MB) and we absolutely need to send smaller chunks.  We're gonna have to segment them.  Oh well.

Kinda glad we went with byte-based flow control in the end :sweat_smile:

**Comment by garrett** [comment]
As mentioned in Matrix, CanIUse says WebKit doesn't support it: https://caniuse.com/mdn-api_readablestreambyobreader_readablestreambyobreader

Same for MDN: https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamBYOBReader/ReadableStreamBYOBReader

Here's the specific issue to implement it in Safari (nothing to see here, just a stub that shows it's on their TODO) https://bugs.webkit.org/show_bug.cgi?id=264731

There is a polyfill, although if we could avoid it, that'd be nice: https://github.com/MattiasBuelens/web-streams-polyfill
