### ISSUE TITLE
Incorrect MIME type

### ISSUE THREAD

**Issue by goatfanboi23** [cockpit-project/cockpit#20623]
### Explain what happens

1. Install cockpit
2. Go to login page
3.  login with credentials
4. Receive Connection failed page.
The Firefox and Chrome dev tools both show that “https://${DOMAIN}/admin/cockpit/@localhost/*/po.js”  is returning the wrong type. `was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)`. This is also shown with executing `curl -I 'https://${DOMAIN}/admin/cockpit/@localhost/*/po.manifest.js`
```
HTTP/1.1 401 Not Authorized
Server: nginx/1.24.0 (Ubuntu)
Date: Wed, 19 Jun 2024 14:00:25 GMT
Content-Type: text/html; charset=utf8
Connection: keep-alive
X-DNS-Prefetch-Control: off
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
Cross-Origin-Resource-Policy: same-origin
X-Frame-Options: sameorigin
```
Notice the `Content-Type: text/html`.
In the `journalctl` logs, there are no abnormal messages (only starting and stopping service messages)
I am using Nginx reverse proxy and a `UrlRoot=/admin` in my cockpit config. However, I run into the same problem when accessing cockpit directory using the port `9090` in the url.
Platform Ubuntu: 24.04 LTS

### Version of Cockpit

316-1~bpo24.04.1

### Where is the problem in Cockpit?

Networking

### Server operating system

Ubuntu

### Server operating system version

24.04

### What browsers are you using?

Firefox, Chrome

**Comment by goatfanboi23** [comment]
My preliminary code search led me to [https://github.com/cockpit-project/cockpit/blob/7c795bb70eb232525b9f2f29603c863d366c8294/src/ws/cockpithandlers.c#L444](url) where the request for the JavaScript files might happen along with an explicit X-Content-Type header.

**Comment by jelly** [comment]
Is anything not working? `/*/po.js` is something we no longer really do with the python bridge. Are translations not working?

**Comment by goatfanboi23** [comment]
Great to hear that the Incorrect Mime Type was not the problem. I ended up fixing my problem by adding `https://${DOMAIN}:9090` to my cockpit.conf config, instead of just the `https://${DOMAIN}' and `wss://${DOMAIN}` entries. This was probably a quirk of how my reverse proxy as setup, and also prevented me from logging in directly over port 9090.
Thank you for your clarification.
