### ISSUE TITLE
Inconsistent translation of 'passphrase' in German .po files

### ISSUE THREAD

**Issue by jfaltenbacher** [cockpit-project/cockpit#20638]
### Explain what happens

While reading through the German translation of https://github.com/cockpit-project/cockpit/blob/main/po/de.po, I noticed that the term 'passphrase' has been translated differently. For example: in line 843 it has been translated as 'Passphrase'
in line 1605 as 'Passwort', and in line 6155 as 'Passwort-Satz'. For consistency reasons, I propose to stick to one translation only. For me, as a German native speaker, using 'Passwort' for all occurrences would be most appropriate.

### Version of Cockpit

current main branch

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

openSUSE

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
Thanks for pointing out! I went through all German translations including "passphrase" in https://translate.fedoraproject.org/projects/cockpit/main/de/#repository and consistently used "Passwort" there.
