### ISSUE TITLE
Options of which users to sync, when adding to dashboard

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2066]
Cockpit requires that the same user is used for all servers on the dashboard, and thusly we offer to sync the user to other machines (eg: if not joined to a domain). 

We currently sync all users. But we should make this optional, with just the current user as a prerequisite.

**Comment by petervo** [comment]
Current user may be ambiguous, is that the user that i'm logged into cockipt with on the machine that is serving the dashboard ei: has the machines file. Or the user that was used to log into the remote machine as part of the add host process.

**Comment by stefwalter** [comment]
The one logged into Cockpit.

I agree this is a UI nightmare with the two users involved (one temporary). It needs some thought to be presented correctly.

**Comment by stefwalter** [comment]
This is done.
