### ISSUE TITLE
 newusers error logs

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#2067]
Errors from newusers commands don't seem to be making their way into the journal.

**Comment by stefwalter** [comment]
Which errors did you see that went to the wrong place? I took a look at the newusers source code, and everything goes to stderr, which should go to the journal.

**Comment by petervo** [comment]
This was with shadow-utils 4.1.5.1. My shadow file and /etc/groups were inconsistent on the vm i was testing with, so adding a user was failing. Nothing in the journal but running the same command on the command line showed me the error.

**Comment by stefwalter** [comment]
Yes. What was the error? So we can track it down.

**Comment by petervo** [comment]
The error looks like: 

newusers: group x is a shadow group, but does not exist in /etc/group
newusers: line 1: can't create group

**Comment by stefwalter** [comment]
Hmmm, that error goes to stderr in src/newusers.c

**Comment by petervo** [comment]
Haven't been able to reproduce since.
