### ISSUE TITLE
kdumpctl missing on /daily scenario

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20694]
The job `fedora-40/daily` failed on commit ffe62648fdf6e7ef09da9b8192616cf067d757ed.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-ffe62648-20240703-013022-fedora-40-daily/log.html

**Comment by martinpitt** [comment]
This triggers a very strong déjà-vu:
```
error: Failed dependencies:
	/usr/bin/kdumpctl is needed by cockpit-kdump-319.dev47+gffe62648f-1.fc40.noarch
```

And indeed I tried to fix this in #20661. But the log has no trace of `dnf -y install kdump-utils`, it continues right away with downloading package sets. What the.. ??

I have no clue what's going on here. The [tested commit](https://github.com/cockpit-project/cockpit/blob/ffe62648fdf6e7ef09da9b8192616cf067d757ed/test/vm.updates-testing) very clearly still has that command.

**Comment by martinpitt** [comment]
Anyway.. the bodhi update was finally pushed to stable, so we can refresh our fedora-40 image tomorrow-ish and drop this hack.

**Comment by martinpitt** [comment]
Triggered https://github.com/cockpit-project/bots/issues/6577 let's see if that helps.
