### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by riccardovalentinieusphere** [cockpit-project/cockpit#20702]
### Explain what happens

If we go into /users and look for root user, we will find that the translation for "Last activity" is "Nessuno uutenticato" instead of "Nessuno autenticato"

### Version of Cockpit

314-1

### Where is the problem in Cockpit?

Accounts

### Server operating system

Ubuntu

### Server operating system version

24.04LTS

### What browsers are you using?

Chrome

**Comment by martinpitt** [comment]
Thanks! I fixed that in weblate: https://translate.fedoraproject.org/translate/cockpit/main/it/?checksum=58b75d09cc1b293d

It'll be picked up by the next translation refresh.
