### ISSUE TITLE
Cockpit 320 on Debian not showing network stats

### ISSUE THREAD

**Issue by Unclezz** [cockpit-project/cockpit#20739]
### Explain what happens

I am running Cockpit on a Debian Bookworm (12) using the repository from backports.

The network stats are not shown. I was previously using the older cockpit version (287) coming from official debian stable reports and stats were there.

Did anyone else noticed the same?

### Version of Cockpit

320

### Where is the problem in Cockpit?

Networking

### Server operating system

Debian

### Server operating system version

12

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
Do you have `cockpit-pcp` installed? which version?

**Comment by Unclezz** [comment]
Thanks @martinpitt !

I did not remember I installed it before. Now have the 311 version (again from backports) and it started working.
Sorry for overlooking this and asking question here.

**Comment by martinpitt** [comment]
No worries, I'm glad it's working!
