### ISSUE TITLE
User-specific package manifest overrides (systemd.override.json) ignored or not working

### ISSUE THREAD

**Issue by tfrancois** [cockpit-project/cockpit#20750]
### Explain what happens

Following the documentation that states it is possible to hide menu options in Cockpit for certain users simply by placing a systemd.override.json file in the ~/.config/cockpit folder (or users /home folder) is ignored or not working.

Perhaps I'm simply not calling the package names properly - not sure.  And I can't find the correct name for the default packages ANYWHERE in the documentation.  The only ones I can confirm that work in the list below is `logs `and `services`.

My user's `~/.config/cockpit/systemd.override.json` file looks like this:
```

{
  "menu": {
    "logs": null,
    "storage": null,
    "network": null,
    "users": null,
    "services": null,
    "updates": null,
    "apps": null,	
    "selinux": null,
    "metrics": null,
    "sosreport": null,
    "kdump": null
  }
}
```
 The desired outcome is for ONLY the Overview and Terminal menu items to be present for the user.  Any help would be appreciated.

### Version of Cockpit

310.4

### Where is the problem in Cockpit?

Front-end user interface/console

### Server operating system

CentOS

### Server operating system version

Centos Stream 8

### What browsers are you using?

Firefox, Chrome

**Comment by martinpitt** [comment]
The "systemd" page provides the "index" (overview), logs, services, and terminal pages, and you said that these work. All the others come from other pages, e.g. /usr/share/cockpit/storaged/manifest.json. But if you don't want these, perhaps just uninstall the `cockpit-packagekit` and `cockpit-storaged` packages? The rest you can override similar to the system ones.

See `cockpit-bridge --packages` for an overview what module ships which pages.

**Comment by tfrancois** [comment]
Respectfully @martinpitt - the issue still exists.  Before I re-open a new issue on this same topic (I am not able to re-open this one and don't want to create duplicate unnecessarily), the menu options I wish to override are:

- Accounts
- Networking
- Diagnostic reports
- Kernel dump
- SELinux

With the file I have set for a non-sudo user in question, they all appear despite the following override file:
`{
  "menu": {
    "logs": null,
    "storage": null,
    "network": null,
    "users": null,
    "services": null,
    "updates": null,
    "apps": null,
    "selinux": null,
    "metrics": null,
    "sosreport": null,
    "kdump": null
  }
}`

Thanks.

**Comment by martinpitt** [comment]
You can't override *all* of these menu entries with a `systemd.override.json`. -- as I said, you have to e.g. disable Accounts in `users.override.json`, or Networking in `networkmanager.override.json`, and so on. See `cockpit-bridge --packages` for the mapping.

**Comment by ThomasGehPunkt** [comment]
Hi everyone,

I had the same question and came across this page several times, so I wanted to share my solution and suggest adding it to the documentation.

For additional packages, the .override.json should be structured as follows: { "tools": { "index": null } }

Additionally, please note that the systemd override can have multiple values for the menu key.

Hope this helps
