### ISSUE TITLE
OS and version visible from login window, not safe

### ISSUE THREAD

**Issue by pascald0210** [cockpit-project/cockpit#20759]
### Explain what happens

1. Launch debug utility from your internet explorer on cockpit login window
2. It gives some crucial informations about OS and version server

![cockpit login](https://github.com/user-attachments/assets/ae85e55f-ff83-46b0-8bb5-89493ddfaeb9)

### Where is the problem in Cockpit?

None

### Server operating system

Ubuntu

### Server operating system version

20.04

### What browsers are you using?

Edge

**Comment by jelly** [comment]
Duplicated of https://github.com/cockpit-project/cockpit/issues/19852
