### ISSUE TITLE
TestStorageLvm2.testLvm pixel flake

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20764]
The job `fedora-40/daily` failed on commit 294fd5305c9eefc41cff4d59a06f78a0040c6843.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-294fd530-20240716-013023-fedora-40-daily/log.html

**Comment by martinpitt** [comment]
I've seen [this pixel flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-294fd530-20240716-013023-fedora-40-daily/pixeldiff.html#TestStorageLvm2-testLvm-pool-page) several times now. The test sets `mock={".usage-text": "1 / 100 MB"}`, but this sometimes either doesn't seem to apply in time, or it may get overwritten again by some storage event, and thus flips back to the real values?

**Comment by martinpitt** [comment]
@mvollmer that may be something for you?

**Comment by mvollmer** [comment]
> and thus flips back to the real values?

Yes, quite possible.
