### ISSUE TITLE
The trace option for tests is broken -v during boot

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2077]
The trace option for tests (showing the bootup) is broken. Previously specifying -v to a VM would show all boot messages and allow you to diagnose startup issues.

**Comment by dperpeet** [comment]
does `-t` (trace) work for you? that traces the actual test, but doesn't show the bootup. Should it?
Which option (`v` or `t`) should show the bootup process?

**Comment by stefwalter** [comment]
-v would show the bootup process before, as well as any other verbose messages (such as command lines executed, and so on). If you would like to change the options around that's fine with me, but we should still have a way of seeing the boot up somewhere.
