### ISSUE TITLE
Jammy-backports is missing updated dependencies for ARM

### ISSUE THREAD

**Issue by evoke0** [cockpit-project/cockpit#20785]
### Explain what happens

CPU Architecture: aarch64
CPU: ARM Neoverse-N1

Uppon trying to install cockpit from the backports, the main package can't be installed due to the following dependencies not being at version 321:

cockpit-bridge (version 316)
cockpit-ws (version 316)

### Version of Cockpit

321

### Where is the problem in Cockpit?

Software updates

### Server operating system

Ubuntu

### Server operating system version

22.04.4 LTS

**Comment by martinpitt** [comment]
Indeed that version still hasn't built on ARM: https://launchpad.net/ubuntu/+source/cockpit/321-1~bpo22.04.1

This is a problem with Ubuntu's package builders, I'm afraid we can't do anything about this on our side.
