### ISSUE TITLE
updates-testing failed in TestKdumpNFSAnsible.testBasic

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20797]
The job `fedora-40/daily` failed on commit 3cd180202d09c34b11b4dbe4d67a048530de5bfd.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-3cd18020-20240724-013023-fedora-40-daily/log.html

**Comment by martinpitt** [comment]
Continuation of #20779 but now the log has more useful debug information. The kdump kernel boot is broken:
```
[    2.102250] Run /init as init process
/init: line 17: modprobe: command not found
/init: line 18: modprobe: command not found
/init: line 19: modprobe: command not found
mount: /squash/root: failed to setup loop device for /squash-root.img.
mount: /newroot: unknown filesystem type 'overlay'.
       dmesg(1) may have more information after failed mount system call.
mount: /newroot/squash: mount point does not exist.
       dmesg(1) may have more information after failed mount system call.
/init: line 34: exec: switch_root: not found
[    2.157896] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00
```

**Comment by martinpitt** [comment]
This hit fedora-40 proper now, see https://github.com/cockpit-project/bots/pull/6659 Let's track it there.

**Comment by licliu** [comment]
Hi @martinpitt , I noticed this issue from "A week in the life of a Cockpit team pilot" you sent to the redhat devel mailling list.
Please feel free to contact me or file an issue to [kdump-utils](https://github.com/rhkdump/kdump-utils) if there is any issue about kdump . We are willing to help.

**Comment by martinpitt** [comment]
@licliu By now, Fedora 40 has gone back to being *differently* broken, it already fails the kdump NFS test much earlier in the test run. This has been known as https://bugzilla.redhat.com/show_bug.cgi?id=2270423 and already regressed in March. That has a cockpit-independent reproducer. Thanks!

**Comment by licliu** [comment]
@martinpitt Thanks to let me know, we haven't given btrfs a high priority in the past, I will work on improving it.
