### ISSUE TITLE
Amazon Linux 2023 arm64 install cockpit cannot be found.      

### ISSUE THREAD

**Issue by xiaoming728** [cockpit-project/cockpit#20799]
### Explain what happens

run  yum install -y cockpit cockpit-docker cockpit-machines cockpit-dashboard cockpit-storaged cockpit-packagekit
error 
created by dnf config-manager from https://download.fedoraproject.org/pub/ep  19  B/s |  19  B     00:00    
Errors during downloading metadata for repository 'download.fedoraproject.org_pub_epel_7_x86_64_epel-release-7-14.noarch.rpm':
  - Status code: 404 for https://download.fedoraproject.org/pub/epel/7/x86_64/epel-release-7-14.noarch.rpm/repodata/repomd.xml (IP: 140.211.169.196)
Error: Failed to download metadata for repo 'download.fedoraproject.org_pub_epel_7_x86_64_epel-release-7-14.noarch.rpm': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: download.fedoraproject.org_pub_epel_7_x86_64_epel-release-7-14.noarch.rpm
Last metadata expiration check: 0:18:39 ago on Wed Jul 24 18:32:49 2024.
No match for argument: cockpit
Error: Unable to find a match: cockpit
[root@ip-172-31-22-19 ~]# systemctl enable --now cockpit
Failed to enable unit: Unit file cockpit.service does not exist.

Whether or not to support Amazon Linux 2023 arm64

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

other

### What browsers are you using?

Chrome

**Comment by martinpitt** [comment]
RHEL 7 and hence EPEL 7 are out of life.
