### ISSUE TITLE
Missing requirements style

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#2083]
We have a few pages were we have messages letting users know that a component needed for that page isn't installed. ei: docker or storage. We should probably have a standardized look for those types of messages.

**Comment by andreasn** [comment]
What about something like this?

![screenshot from 2015-04-22 15-44-53](https://cloud.githubusercontent.com/assets/209895/7275866/8f500504-e906-11e4-9be7-f91660ecfd16.png)

**Comment by andreasn** [comment]
for Storage it would be "Storaged is not installed or activated on the system"

**Comment by stefwalter** [comment]
Interesting. I think it's a good pattern.

We also need something similar when people access an unknown page or unknown component (instead of our ugly 404 page). Maybe with an (x) icon?

Is the above implementable *without* yet another image?

**Comment by dperpeet** [comment]
I don't think we should add another pattern here, https://www.patternfly.org/widgets/#alerts seems to do the trick. I recommend we use non-dismissable alerts for standalone alerts on an otherwise empty page.

An advantage of using these alerts is also that they can be generated when needed - they aren't part of the dom initially and just hidden...

Use could be like @andreasn proposed: use the different levels depending on the situation, e.g. information if a component isn't installed (and we expect that).

**Comment by andreasn** [comment]
> Is the above implementable without yet another image?

It actually is! :)
it's pficon pficon-info from https://www.patternfly.org/visual-styles/icons-glyphs/

**Comment by andreasn** [comment]
More like this?

![screenshot from 2015-04-23 11-36-48](https://cloud.githubusercontent.com/assets/209895/7294391/169bded8-e9ad-11e4-8d69-5a30e092f12e.png)

**Comment by jeffvance** [comment]
For the case above (Docker is not installed or activated on the system), if the user clicks "Start Docker", and docker was in fact not installed, will cockpit install docker and then if successful start docker?

**Comment by jeffvance** [comment]
This curtain pattern could also apply to the "Cluster" view when kubernetes is not installed or activated. However, I was also wondering if it would also be nice to grey out the "Cluster" label but keep the link active -- to give the user a visual hint that there's nothing to see there...

**Comment by stefwalter** [comment]
> This curtain pattern could also apply to the "Cluster" view when kubernetes is not installed or activated. However, I was also wondering if it would also be nice to grey out the "Cluster" label but keep the link active -- to give the user a visual hint that there's nothing to see there...

That would be nice. But due to the way that Cockpit is componentized I haven't figured out a good way to accomplish that. However, in general we try to have a model where people only install the cockpit-kubernetes package when kubernetes is installed.

**Comment by jeffvance** [comment]
Good point re. installing pkg/kubernetes as a good indication that they're using kube!

**Comment by stefwalter** [comment]
The style is done. More info here: https://trello.com/c/r05Yyvu5/241-lazy-installation-of-cockpit-modules
