### ISSUE TITLE
Multiple hosts tab missing

### ISSUE THREAD

**Issue by Fuzzypyro** [cockpit-project/cockpit#20859]
### Explain what happens

Machine tab is missing from the top left hand side. 

Tried logging out then logging in.
Tried restarting cockpit.
Tried authorizing ssh session key.
Tried on a different system running the same distribution. 

No option to switch to any known hosts at all.

### Version of Cockpit

322-1

### Where is the problem in Cockpit?

Overview

### Server operating system

Arch Linux

### Server operating system version

Latest 6.10.3-arch1-2

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
This is by design. We are still fine-tuning the release announcement in https://github.com/cockpit-project/cockpit-project.github.io/pull/751 , but please see the preview for now: https://mvollmer.github.io/cockpit-project.github.io/blog/cockpit-322.html

**Comment by martinpitt** [comment]
The announcement has been published: https://cockpit-project.org/blog/cockpit-322.html
