### ISSUE TITLE
Deref of null while using g_hash_table_lookup (in dead C bridge code)

### ISSUE THREAD

**Issue by sminux** [cockpit-project/cockpit#20857]
### Explain what happens

Static [analyzer](https://www.ispras.ru/en/technologies/svace/) got me thinking of:
Return value of a function 'g_hash_table_lookup' is dereferenced at cockpitdbusjson.c:2856 without checking for NULL, but it is usually checked for this function (73 times) like this
https://github.com/cockpit-project/cockpit/blob/4cb9238994ba997eb9a8315ac6b6ba4d67e6f3b6/src/bridge/cockpitdbusjson.c#L2679-L2681

but here are some code without checking fot null:
https://github.com/cockpit-project/cockpit/blob/4cb9238994ba997eb9a8315ac6b6ba4d67e6f3b6/src/bridge/cockpitdbusjson.c#L2855
https://github.com/cockpit-project/cockpit/blob/4cb9238994ba997eb9a8315ac6b6ba4d67e6f3b6/src/bridge/cockpitpackages.c#L1510

### Version of Cockpit

main

### Where is the problem in Cockpit?

None

### Server operating system

None

**Comment by martinpitt** [comment]
Thanks -- Like #20856, this is dead code. cockpitdbusjson isn't being used by the PCP bridge, nor cockpitpackages. This will all go away with #20000.

**Comment by martinpitt** [comment]
Closing, this isn't actionable and we track the removal of that code in #20000.
