### ISSUE TITLE
Storage: should allowed to fold or hide btrfs subvolumes 

### ISSUE THREAD

**Issue by 8ar10der** [cockpit-project/cockpit#20912]
Page: Storage

I am using podman with btrfs backend driver. There are lots of subvolumes created by the podman for containers. This is "good" that all be showed in the cockpit, but bad I can not fast track to the volumes I need to check. I have to scroll down lots of time to find the other disks.

If they are foldable, that would be great.

![image](https://github.com/user-attachments/assets/44540ba9-4db5-41bd-81f6-d0ab91c8dc9b)

**Comment by jelly** [comment]
These are all btrfs subvolumes from podman, @mvollmer suggested we hide these by default.

**Comment by 8ar10der** [comment]
Arch Linux already released the latest version `extra/cockpit-storaged:324-1` including the change. Glad to see the quick response. Thanks!
