### ISSUE TITLE
Login page show Debian badge instead of Ubuntu on Ubuntu 24.04 

### ISSUE THREAD

**Issue by pureexe** [cockpit-project/cockpit#20929]
### Explain what happens

I'm using Ubuntu 24.04 LTS on NanoPi NEO 3. 
The Cockpit was installed using following command.
```
. /etc/os-release
sudo apt install -t ${VERSION_CODENAME}-backports cockpit
```

1.  Here is the login screen that has wrong badge. It should be ubuntu 
![image](https://github.com/user-attachments/assets/960f5580-2605-46b7-bcc0-1c201e80580e)

2. Page show the screenfetch
![image](https://github.com/user-attachments/assets/f3b1cac2-e9e1-49c7-91c0-cd6547ae8978)

### Version of Cockpit

321-1~bpo24.04.1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Ubuntu

### Server operating system version

24.04

### What browsers are you using?

Chrome

**Comment by jelly** [comment]
I don't see a Debian badge anywhere? Can you point out where it shows it?

**Comment by martinpitt** [comment]
@jelly The swirl to the right of the login field.

Can you please check the output of

    ls -l /usr/share/cockpit/branding/ubuntu/logo.png

? It should be a symlink to ../../../plymouth/ubuntu-logo.png. Can you please check /usr/share/plymouth/ubuntu-logo.png ? That shuold be an Ubuntu logo.

**Comment by pureexe** [comment]
> @jelly The swirl to the right of the login field.
> 
> Can you please check the output of
> 
> ```
> ls -l /usr/share/cockpit/branding/ubuntu/logo.png
> ```
> 
> ? It should be a symlink to ../../../plymouth/ubuntu-logo.png. Can you please check /usr/share/plymouth/ubuntu-logo.png ? That shuold be an Ubuntu logo.

Yes, it does symlink to the Ubuntu logo as shown below. But I still got the Debian logo on the login page.

![image](https://github.com/user-attachments/assets/a654318b-7d2a-4cd1-8061-5425d6f2ef02)

**Comment by pureexe** [comment]
Update: It seems like "/usr/share/Plymouth" does not exist in NanoPi.

This is a headless single-board computer that doesn't have monitor output. This may be the reason why the Ubuntu logo is not shown.

**Comment by martinpitt** [comment]
Right, if there's no Ubuntu logo installed, then it falls back to the Debian logo. This is pretty much a wontfix, I'm afraid.
