### ISSUE TITLE
putdated gitignore

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2092]
after building, I have a lot of untracked files:

	cockpit-pcp
	cockpitd
	doc/man/cockpit-bridge.1
	doc/man/cockpit-ws.8
	doc/man/cockpit.conf.5
	doc/man/cockpitd.8
	doc/version
	guide/
	org.freedesktop.UDisks2.c
	org.freedesktop.UDisks2.h
	pkg/base/
	pkg/base1/bundle.min.js
	pkg/base1/bundle.min.js.gz
	pkg/base1/cockpit.min.css.gz
	pkg/base1/cockpit.min.js
	pkg/base1/cockpit.min.js.gz
	pkg/base1/fonts/fontawesome.woff.gz
	pkg/base1/fonts/glyphicons.woff.gz
	pkg/base1/fonts/patternfly.woff.gz
	pkg/base1/jquery.min.js.gz
	pkg/base1/mustache.min.js.gz
	pkg/base1/po.js.gz
	pkg/base1/require.min.js.gz
	pkg/base1/term.min.js
	pkg/base1/term.min.js.gz
	pkg/docker/console.min.html.gz
	pkg/docker/docker.min.js.gz
	pkg/kubernetes/angular.min.js.gz
	pkg/kubernetes/app.min.css.gz
	pkg/kubernetes/app.min.js
	pkg/kubernetes/client.min.js
	pkg/kubernetes/client.min.js.gz
	pkg/kubernetes/cluster.min.html.gz
	pkg/kubernetes/dashboard.min.js
	pkg/kubernetes/kubernetes.min.js
	pkg/kubernetes/kubernetes.min.js.gz
	pkg/kubernetes/tool.min.html.gz
	pkg/legacy/cockpit.min.css.gz
	pkg/realmd/bundle.min.js
	pkg/realmd/bundle.min.js.gz
	pkg/realmd/operation.min.js
	pkg/shell/bundle.min.js
	pkg/shell/bundle.min.js.gz
	pkg/shell/canvas.min.js
	pkg/shell/cockpit-accounts.min.js
	pkg/shell/cockpit-cpu-status.min.js
	pkg/shell/cockpit-dashboard.min.js
	pkg/shell/cockpit-docker.min.js
	pkg/shell/cockpit-main.min.js
	pkg/shell/cockpit-memory-status.min.js
	pkg/shell/cockpit-networking.min.js
	pkg/shell/cockpit-plot.min.js
	pkg/shell/cockpit-server.min.js
	pkg/shell/cockpit-services.min.js
	pkg/shell/cockpit-setup.min.js
	pkg/shell/cockpit-storage.min.js
	pkg/shell/cockpit-util.min.js
	pkg/shell/controls.min.js
	pkg/shell/dbus.min.js
	pkg/shell/index.min.js
	pkg/shell/index.min.js.gz
	pkg/shell/machines.min.js
	pkg/shell/plot.min.js
	pkg/shell/shell.min.css.gz
	pkg/shell/shell.min.html.gz
	pkg/shell/shell.min.js
	pkg/shell/shell.min.js.gz
	pkg/subscriptions/subscriptions.min.css
	pkg/subscriptions/subscriptions.min.css.gz
	pkg/subscriptions/subscriptions.min.html.gz
	pkg/subscriptions/subscriptions.min.js
	pkg/subscriptions/subscriptions.min.js.gz
	pkg/systemd/bundle.min.js
	pkg/systemd/bundle.min.js.gz
	pkg/systemd/log.min.html.gz
	pkg/systemd/log.min.js
	pkg/systemd/server.min.js
	pkg/systemd/terminal.min.html.gz
	pkg/systemd/terminal.min.js
	po/po.da.js
	po/po.da.js.gz
	po/po.de.js
	po/po.de.js.gz
	po/po.pl.js
	po/po.pl.js.gz
	shell.min.js.gz

**Comment by stefwalter** [comment]
Ideally you should use a separate build directory. See HACKING.md. However if you want to use the same build directory as your source directory, you are welcome to submit a pull request for curating the .gitignore.

**Comment by andreasn** [comment]
working on that now

**Comment by andreasn** [comment]
https://github.com/cockpit-project/cockpit/pull/2093
