### ISSUE TITLE
updates-testing: TestNetworkingMAC.testBondMac timeout

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20932]
The job `fedora-40/updates-testing` failed on commit e8cf93050356f3cecdc229f170e5c4a72825ef80.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-e8cf9305-20240822-013036-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment]
That MAC change timeout looks a little too specific to be a coincidence.

**Comment by martinpitt** [comment]
Didn't repeat, so smells like "slow bot cloud instance"

**Comment by martinpitt** [comment]
It did repeat in #20938, let's have a look.

**Comment by martinpitt** [comment]
Timeout, and doesn't seem to have happened recently
