### ISSUE TITLE
index-brand is not used, maybe remove from branding css?

### ISSUE THREAD

**Issue by hjmallon** [cockpit-project/cockpit#20936]
### Explain what happens

1. Looks like index-brand was removed in v220 (https://github.com/cockpit-project/cockpit/pull/13663)
2. Should it be removed from the branding css?

### Version of Cockpit

323

### Where is the problem in Cockpit?

Navigation & Shell

### Server operating system

None

**Comment by martinpitt** [comment]
Thanks for spotting @hjmallon ! Dropped in #20972.
