### ISSUE TITLE
Hide efivars mount point in metrics

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#20969]
### Explain what happens

![image](https://github.com/user-attachments/assets/b475266e-354f-4988-968f-4fcabc61fbf1)

efivars is platform specific data and not something for a user to usually read/write into. Showing it has no value.

### Where is the problem in Cockpit?

None

### Server operating system

None

**Comment by jelly** [comment]
I would opt for filtering this in the bridge so src/cockpit/metrics.py (MountSampler), so we don't send unneeded data over the wire.

**Comment by tomasmatus** [comment]
This was fixed in #21062
