### ISSUE TITLE
TestStorageAnaconda.testMDRaid failed on fedora-40 updates/testing

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20977]
The job `fedora-40/daily` failed on commit c062fd73b3a7746446510012cfda5911694e31fd.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-c062fd73-20240905-013122-fedora-40-daily/log.html

**Comment by jelly** [comment]
This is possibly a flake? At least once the test fails we don't properly cleanup the loopback device


```
losetup: /var/tmp/loop.EDvC: failed to set up loop device: Device or resource busy
```

**Comment by jelly** [comment]
https://github.com/cockpit-project/cockpit/pull/20983

**Comment by jelly** [comment]
The PR was merged, lets take a deeper look when this happens again.
