### ISSUE TITLE
Terminal: screen -r into Minecraft server - cant type

### ISSUE THREAD

**Issue by ashwalk33r** [cockpit-project/cockpit#20980]
### Explain what happens

Using Terminal (https://subdomain.example.com/system/terminal) and running `screen` https://linux.die.net/man/1/screen (`screen -S minecraft`) and running in it the Minecraft server process https://fabricmc.net/use/server/ (using Java 21 https://docs.papermc.io/misc/java-install) when I go to the screen `screen -r minecraft` I can not type anything. 

When in the screen I can press `CTRL + A + D` and it successfully takes me back out of the screen, so there is some interaction there...

I've also tried with no success to do `tmux` and inside of it go to `screen -r` but still could not type.

Checked both Chrome and Firefox. Windows OS.

### Version of Cockpit

ubunut as of 2024-09-05 of https://cockpit-project.org/running.html#debian

### Where is the problem in Cockpit?

Terminal

### Server operating system

Ubuntu

### Server operating system version

24

### What browsers are you using?

Chrome

**Comment by jelly** [comment]
screen/tmux works fine for me in the terminal page in Firefox on Linux. I assume you also tried just running `tmux` and then invoking a command there?

**Comment by ashwalk33r** [comment]
I've restarted everything and it works fine now - the screen froze. Sorry for bothering you.
