### ISSUE TITLE
stream mapping internal name should be editable

### ISSUE THREAD

**Issue by eldinmiller** [cockpit-project/cockpit#20999]
Settings / Video / Stream Mapping

Internal name should be editable, or at least an option to match external name.

Use case example: multiple camera vehicle, a user would want to name the cameras "front", "back", "left", "right".  And have those show whenever the stream names are exposed.

**Comment by rafaellehmkuhl** [comment]
Totally agree.
We designed the system so it can be editable, but didn't implement it yet.
It will be done.

**Comment by eldinmiller** [comment]
wrong repo
