### ISSUE TITLE
shell: Doesn't show "network" docs when on "network/firewall" page

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#21040]
When on the "network/firewall" page, the "Help" menu does not include the networking docs:

![image](https://github.com/user-attachments/assets/6c90f68f-624b-4ed3-a509-51d32464b746)

**Comment by mvollmer** [comment]
The "network" page itself has all the docs, including for the firewall. SO I guess the "network/firewall" page should show them as well.

![image](https://github.com/user-attachments/assets/9aa3c75e-3e1d-4ba1-93b5-c0385f132bc8)

**Comment by jelly** [comment]
I think it makes sense to only show the firewall documentation on network/firewall and not on network. That makes me wonder, isn't the fix to fix the manifest to have a separate firewall entry like systemd/manifest.json?
