### ISSUE TITLE
TestStorageNBDE.testRootReboot regression in updates-testing

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21048]
The job `fedora-40/updates-testing` failed on commit f540cfaef30ae50f4f9fc2e2e1aa7b35623804a0.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-f540cfae-20240928-013100-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment]
The screenshot shows a "please enter passphrase for disk...:" prompt, so clevis/tang doesn't work. It also shows a series of "Detected no PKCS#11 device, retry PKCS#11 detection?" question prompts, not sure yet if they are a regression.

On the current image without updates-testing, the "enter passphrase" prompt appears as well (apparently that always happens, it just gets canceled when clevis finishes). But I don't see the PKCS#11 bit.

I'll start to bisect the package updates, we may still be able to stop that in bodhi.

**Comment by sarroutbi** [comment]
Hello @martinpitt . Thanks for your discovery. :-1: makes sense. I have to investigate it, as this question should be performed only for cases where bound device is configured to PKCS11 pin

**Comment by martinpitt** [comment]
This should get fixed by https://github.com/latchset/clevis/pull/481

**Comment by martinpitt** [comment]
Fixed in https://bodhi.fedoraproject.org/updates/FEDORA-2024-70b079f92f
