### ISSUE TITLE
TestPages.TestUploadMultiple flake

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#21065]
### Explain what happens

This happens a lot now since https://github.com/cockpit-project/cockpit/commit/03fcd561ac30f716cca945d844bd93ad6b33363a

https://cockpit-logs.us-east-1.linodeobjects.com/pull-20697-6d9c3dd4-20241001-161112-rhel-9-6-expensive/log.html
https://cockpit-logs.us-east-1.linodeobjects.com/pull-20997-755963db-20241001-150804-rhel-9-6-expensive/log.html

**Comment by mvollmer** [comment]
We need to revert https://github.com/cockpit-project/cockpit/commit/03fcd561ac30f716cca945d844bd93ad6b33363a anyway since we still test c-machines and c-podman on rhel-8-10, and fsinfo doesn't work there (because rhel-8-10 still has the C bridge): #21087

**Comment by martinpitt** [comment]
> cannot open a channel 1:6!4 with the same id as another channel

That was #21219, so whenever we reapply commit 03fcd561ac30f716cca945d this will not be an issue any more.
