### ISSUE TITLE
updates-testing: TestNetworkingSettings.testOtherSettings VM crash

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21091]
The job `fedora-40/daily` failed on commit 2ba803af0119b100dfa625e143cba8d5b57a949c.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-2ba803af-20241008-013314-fedora-40-daily/log.html

**Comment by jelly** [comment]
Doesn't seem like a flake, new issue?

**Comment by martinpitt** [comment]
Could also be overcommitted bot, we occasionally get such VM crashes. Let's see next night?

**Comment by martinpitt** [comment]
Didn't repeat last night, so flake.
