### ISSUE TITLE
TestStorageStratisNBDE.testBasic fails in updates-testing

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21108]
The job `fedora-40/updates-testing` failed on commit a30106a40b4fdc752194447b663e5d32c8638ff5.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-a30106a4-20241012-013105-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment]
warn: Either thumbprints for all Tang servers or a directive to trust all Tang servers is required

This shouldn't regress in stable -- maybe that's new API, but that should be compatible. There's both a [stratis](https://bodhi.fedoraproject.org/updates/FEDORA-2024-51b35142d0) and a [clevis update](https://bodhi.fedoraproject.org/updates/FEDORA-2024-ce137b7a5b), so that needs some checking whom to yell at.

**Comment by mvollmer** [comment]
On it.

**Comment by mvollmer** [comment]
> There's both a [stratis](https://bodhi.fedoraproject.org/updates/FEDORA-2024-51b35142d0) and a [clevis update](https://bodhi.fedoraproject.org/updates/FEDORA-2024-ce137b7a5b), so that needs some checking whom to yell at.

Given that the other clevis tests are still green, I suspect Stratis.

**Comment by mvollmer** [comment]
> Also, don't we do revdeps with Stratis? Why wasn't this caught? Maybe my theory above is wrong.

This is the PR that introduced the extra checks: https://github.com/stratis-storage/stratisd/pull/3613

It was merged in May, and I don't know why it only now shows up in a release.

We did run revdeps on it, but the crucial test, TestStorageStratisNBDE, is a destructive test that doesn't run in TMT. So we missed this regression at the time.

**Comment by mvollmer** [comment]
Fixed in https://github.com/stratis-storage/stratisd/pull/3701

**Comment by martinpitt** [comment]
The fix is now on bodhi: https://bodhi.fedoraproject.org/updates/FEDORA-2024-09cee483a4

**Comment by martinpitt** [comment]
[Last night's run](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-c7fddca2-20241018-013123-fedora-40-daily/log.html) was ok, as it had stratis 3.6.8 again. That feels like a bug, but if/when the updates repo acutally works again, then it should have 3.7.2. For now we can take this off the pilot board.
