### ISSUE TITLE
Why does the Copilot documentation not describe what it is for (an overview)???

### ISSUE THREAD

**Issue by mjvande** [cockpit-project/cockpit#21116]

**Comment by martinpitt** [comment]
https://cockpit-project.org/ does explain what the project is. https://github.com/cockpit-project/cockpit README has a pointer to it and also a summary.

Why did you say "Copilot"? Was that a typo, or were you speaking of GitHub Copilot (or some similar AI thing), and picked the wrong project for this issue?

**Comment by mjvande** [comment]
I'm using Windows 10. Copilot showed up on my taskbar, but I have no idea what it's for, and the documentation doesn't say. Documentation is supposed to be thorough, and contain more than jargon! Is that too much to ask? I'm not asking about Github, although that might be helpful.

**Comment by mjvande** [comment]
By interacting with Copilot, you agree to the Terms of Use and confirm you’ve reviewed the Privacy Statement.
You
wHERE IS THE COPILOT DOCUMENTATION?
Copilot

It seems like you're looking for the Cockpit documentation. You can find it on the Cockpit Project website1. This guide provides comprehensive information on how to use Cockpit, including developer guides, package details, and more1.


| 
| 
|  | 
Cockpit Guide


 |

 |

 |






Is there something specific you're trying to achieve with Cockpit? Maybe I can help!
1cockpit-project.org

--

Machine-Free Trails Association

I am working on creating wildlife habitat that is off-limits to humans ("pure habitat"). Want to help? (I spent the previous 8 years fighting auto dependence and road construction.)

Wildlife must be given top priority, because they can't protect themselves from us.

An abortion is a MEDICAL PROCEDURE! Interfering with abortions is practicing medicine without a license!

Please don't put a cell phone next to any part of your body that you are fond of!

Stop obeying dictators and incompetent leaders from this time forward! Please share this message as widely as possible!

Are you still driving? Why?????

Have you noticed how motor vehicle use has decreased, since global warming was discovered? Me, neither!

https://mjvande.info

To not receive email from me, just reply and ask to be removed. 

    On Monday, October 14, 2024 at 08:11:33 AM PDT, Martin Pitt ***@***.***> wrote:  
 
 


I'm sorry, but this project has absolutely nothing to do with Windows Copilot.
