### ISSUE TITLE
Manifest override.json not being read or ignored

### ISSUE THREAD

**Issue by SirH2Os** [cockpit-project/cockpit#21118]
### Explain what happens

Hey :wave: 
I've tried multiple times to replicate an override.json like in the [tutorial](https://cockpit-project.org/guide/latest/packages.html#package-manifest-override) both for the whole system and for specific users and in both I can't even get the tutorial to work :thinking:.

![path](https://github.com/user-attachments/assets/f0368d3c-d284-4fdb-b157-cea50f360999)
![content](https://github.com/user-attachments/assets/39ccca5c-f3d1-44b5-b3b7-055edbb10c62)

I've also read [this thread](https://github.com/cockpit-project/cockpit/issues/20750) but to no avail on what I am missing.

I've also tried to check for mistakes on the cockpit service boot and it is very clean no errors.
The only thing new to my cockpit installation is a plugin I've developed that only sends requests to endpoints.

Many thanks in advance :smiley: 

### Version of Cockpit

188

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Ubuntu

### What browsers are you using?

Firefox, Chrome, Brave

**Comment by jelly** [comment]
We are happy to help you with your problem but strongly recommend trying to upgrade Cockpit first as version 188 is quite old and the currently supported Ubuntu versions have a more modern Cockpit available.

See also our instructions on installing Cockpit from [backports](https://cockpit-project.org/running#ubuntu).

**Comment by SirH2Os** [comment]
Sorry, when I wrote the thread I forgot I changed from Ubuntu to Raspbian to start to test for the final device...

I am indeed running 188-1 Cockpit on a Raspbian 10, those are the correct specs.

Are there any blockers related to the override functionality because of this?
