### ISSUE TITLE
TestServices.testFilter pixel change 

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21137]
The job `fedora-40/updates-testing` failed on commit c7fddca2bc64be51ee01e40307519e4fc3156b05.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-c7fddca2-20241019-013057-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment]
Uninteresting

**Comment by martinpitt** [comment]
Meh, this is [just the scrolling](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-c7fddca2-20241019-013057-fedora-40-updates-testing/pixeldiff.html#TestServices-testFilter-text-filter-test-mobile), and I can't think of what could influence this in updates-testing. But it repeats.

**Comment by jelly** [comment]
This issue rings a bell, I recall this was introduced in a PF update and we have a workaround for it but it seems the workaround doesn't work well enough?

**Comment by martinpitt** [comment]
I also see this in "normal" PRs, like in https://cockpit-logs.us-east-1.linodeobjects.com/pull-21121-a74fe387-20241021-073359-fedora-40-other/log.html

**Comment by martinpitt** [comment]
@jelly I assume you mean PR #20962 ? Not sure if it's really the reload, it's "just" some different scroll position?

**Comment by martinpitt** [comment]
This reproduces locally when I revert commit f2f381ac2b21988fadf4bee375f45877495846ed. But neither with nor without that hack, the actual nav_scroll_btn loop never runs.

I can interactively reproduce it with Firefox: Switch "Galaxy S10/S10+ Android 11", or just resize the window. I can reload as often as I want, and there are no scroll buttons.

With interactive Chromium I see the buttons after a reload, but *sometimes* I can reproduce the failure with `TEST_SHOW_BROWSER=pixels` or default chromium-headless.

**Comment by jelly** [comment]
Ok, so my F5 doesn't help anymore or accidentally helped. Then we should rework this, keep in mind that I think this was a PF bug?

**Comment by martinpitt** [comment]
This is https://www.patternfly.org/components/navigation#tertiary-deprecated . The example in the docs is way too wide to fit on a single screen, so the bug can't easily be reproduced there. But with it being deprecated, I suppose it doesn't make much sense to file a bug. We could try porting to https://www.patternfly.org/components/navigation#horizontal-subnav

**Comment by jelly** [comment]
I created https://github.com/patternfly/patternfly-react/issues/10897 back then and this has been fixed apparently.

**Comment by martinpitt** [comment]
Ooh, thanks for that pointer! https://github.com/patternfly/patternfly-react/pull/11099 is included in 5.4.2, so let's try an update.
