### ISSUE TITLE
cockpit-ws bastion/unprivilleged forced ssh-agent

### ISSUE THREAD

**Issue by engelant** [cockpit-project/cockpit#21170]
https://github.com/cockpit-project/cockpit/blob/f985ad053f4933884bef9713a2091decbf1c76b9/containers/ws/label-run#L45
My issue being, that ssh-agent is started unconditionally.

Can anybody spot any harm in wrapping this in a start if unset condition like so:
```sh
if [ -z "$SSH_AUTH_SOCK" ]; then
    eval "$(ssh-agent)"
fi
```

This would enable me to provide my own SSH_AUTH_SOCK without breaking behavior.

**Comment by engelant** [comment]
By harm I really just ment for other users in terms of compatability.
Right now for testing i just used a Containerfile to sed out the line, and it works as intended.
Especially under linux I am against hiding potentially dangerous settings, but only if "we don't break userspace".

Therefor my main concern is wether this could break any potentiall existion application.
As it only affects the container label-run and an admin would have to explicitly have set SSH_AUTH_SOCK for an unprivileged environment for the behaviour to change.

**Comment by martinpitt** [comment]
No, I can't imagine breaking any existing realistic setup. Setting $SSH_AUTH_SOCKET in the container never worked and was never documented.
