### ISSUE TITLE
Possible bad copy past in session-utils.c

### ISSUE THREAD

**Issue by Bbulatov** [cockpit-project/cockpit#21177]
### Explain what happens

Hello!
During the static analysis was found possible mistake:
In src/session/session-utils.c:562 in function spawn_and_wait() value 'gid' might be 'uid', besause 'gid' used in src/session/session-utils.c:558-559.
 ```
 if (setresgid (gid, gid, gid) != 0)
       abort_with_message ("setresgid: couldn't set gid to %u: %m\n", (int) gid);

if (setresuid (uid, uid, uid) != 0)
       abort_with_message ("setresgid: couldn't set uid to %u: %m\n", (int) gid);
 ```

### Version of Cockpit

main

### Where is the problem in Cockpit?

Logs

### Server operating system

Debian

**Comment by martinpitt** [comment]
Thank you @Bbulatov for spotting this! PR #21178 fixes this.
