### ISSUE TITLE
Possible deference of null pointer

### ISSUE THREAD

**Issue by Bbulatov** [cockpit-project/cockpit#21180]
### Explain what happens

Hello!
During the static analysis was found possible mistake in 325 version:
In src/bridge/cockpitdbusjson.c return value of a function g_hash_table_lookup() is dereferenced at cockpitdbusjson.c:2856 without checking for NULL, but it is usually checked for this function:
```
subscribers = g_hash_table_lookup (pending_group_connections, key);
for (guint i = 0; i < subscribers->len; i++)
```
Please clarify whether inspection is required in this location?

### Version of Cockpit

325

### Where is the problem in Cockpit?

None

### Server operating system

Debian

**Comment by martinpitt** [comment]
Hello @Bbulatov ! This file doesn't exist any more, since PR #20000. It has already been dead since Cockpit 294 in Debian testing/unstable.
