### ISSUE TITLE
TestStorageLvm2.testRaid pixel failure

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21196]
The job `fedora-40/updates-testing` failed on commit 6d478ad51585d9d7f8c4567c155bd641635f284f.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-6d478ad5-20241031-013118-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment]
The actual pixels contain the "87% synchronized" which isn't in the reference. Needs waiting and stubbing out the number with a mock value.

**Comment by jelly** [comment]
A this happened again.
