### ISSUE TITLE
shell crash: TypeError: _ is null , b.target.contentWindow is  null

### ISSUE THREAD

**Issue by jangotek** [cockpit-project/cockpit#21207]
### Explain what happens

![error1](https://github.com/user-attachments/assets/8b0e0f86-7984-4f18-b3b6-159a2cbf8284)

this error only happen on firefox browser, no error on chromium browser, affected also latest cockpit 327

### Version of Cockpit

325-1~bpo12+1

### Where is the problem in Cockpit?

Overview

### Server operating system

Debian

### Server operating system version

Linux debian 6.1.0-26-amd64

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
The C-S-P warnings are mostly noise, although the script-src-elem ones are unusual. The deadly ones are the `TypeError`s. But what is `lockdown-install.js`? Do you have a browser extension which restricts JavaScript somehow? Could you try this in a private window without the extension, or a separate browser profile or so?

**Comment by jangotek** [comment]
> The C-S-P warnings are mostly noise, although the script-src-elem ones are unusual. The deadly ones are the `TypeError`s. But what is `lockdown-install.js`? Do you have a browser extension which restricts JavaScript somehow? Could you try this in a private window without the extension, or a separate browser profile or so?

thanks for reply i found out the extension is the source of the error i disabled Popup Blocker (strict) the error is gone

**Comment by not-pyroman** [comment]
I have also observed the script-src-elem warnings due to Dark Reader not detecting that Cockpit is already in a dark theme
