### ISSUE TITLE
[Nvidia][Flatpak] Cannot launch Cockpit Client

### ISSUE THREAD

**Issue by TaylorMichaelHall** [cockpit-project/cockpit#21218]
### Explain what happens

- OS: Bazzite 41 (Fedora 41 Silverblue-based)
- GPU: NVIDIA RTX 4070 SUPER
- Drivers: NVIDIA proprietary drivers 565.57.01
- Desktop: GNOME 47.1
- Flatpak version: Flatpak 1.15.10
- Cockpit Client version: 326

I'm not able to run the flatpak Cockpit Client on my Nvidia system. It does work on my AMD system under the same operating system.

Launching normally with `flatpak run org.cockpit_project.CockpitClient`:
> `Gdk-Message: 06:42:36.688: Error 71 (Protocol error) dispatching to Wayland display.`

This results in no window appearing and the application closing.

`flatpak run --nosocket=wayland org.cockpit_project.CockpitClient`
> `Gtk-Message: 06:43:11.168: Failed to load module "canberra-gtk-module"`
>`Gtk-Message: 06:43:11.773: Failed to load module "canberra-gtk-module"`
> `Gtk-Message: 06:43:11.774: Failed to load module "canberra-gtk-module"`
> `Failed to create GBM buffer of size 1280x800: Invalid argument`

This results in a blank login window
![image](https://github.com/user-attachments/assets/8b20222f-6ec8-4845-9382-aaca9b2af6fa)

Also reported [here](https://github.com/cockpit-project/cockpit/issues/21032#issuecomment-2368069022) but that report was conflated with an unrelated locale issue.

### Version of Cockpit

flatpak app/org.cockpit_project.CockpitClient/x86_64/stable version 326

### Where is the problem in Cockpit?

Navigation & Shell

### Server operating system

Fedora

### Server operating system version

41

### What browsers are you using?

Cockpit Client / Cockpit Desktop

**Comment by martinpitt** [comment]
> Failed to create GBM buffer of size 1280x800: Invalid argument

This smells like somewhere between webkit, GTK, and the kernel driver -- this is way below the stuff cockpit client has access to. So this needs to be reported somewhere else.

Could you try a minimal webkit demo and see how that works? Download [webkittest.py.txt](https://github.com/user-attachments/files/18195068/webkittest.py.txt), rename it to `.py`, inspect it that I don't try to 0wn you :wink:, and run `python3 webkittest.py`? That should bring up a simple browser window for https://redhat.com.

If that works, please change the `win.set_default_size()` call to "1280, 800". Does that make any difference?

Thanks!

**Comment by TaylorMichaelHall** [comment]
Thank you for your guidance!

I’ve tested the webkit test script as suggested and was able to reproduce the same error (Error 71 (Protocol error) dispatching to Wayland display) outside of Flatpak. This suggests that the issue lies deeper in the stack, likely involving the NVIDIA proprietary drivers or their interaction with Wayland and WebKitGTK.

```
$ python webkittest.py # 1280, 800
Gdk-Message: 20:45:39.698: Error 71 (Protocol error) dispatching to Wayland display.
$ python orig_webkittest.py  # original win.set_default_size()
Gdk-Message: 20:45:44.767: Error 71 (Protocol error) dispatching to Wayland display
```

I also ran with some extra debugging

```
$ G_MESSAGES_DEBUG=all /usr/bin/python3 webkittest.py
# last line of output
(webkittest.py:8734): Gdk-DEBUG: 20:47:59.017: wp_linux_drm_syncobj_surface_v1#49: error 4: explicit sync is used, but no acquire point is set
```

This appears to point to an explicit sync issue (wp_linux_drm_syncobj), which aligns with the error seen when running the Cockpit Client Flatpak. This seems specific to NVIDIA hardware and the proprietary drivers andunlikely that this issue is related to Cockpit itself.

**Comment by martinpitt** [comment]
Nice, thanks @TaylorMichaelHall ! As this is tracked in https://bugs.webkit.org/show_bug.cgi?id=280210 already, closing here.
