### ISSUE TITLE
Cockpit sends non-empty body (due to chunked transport encoding) on a `HEAD` request

### ISSUE THREAD

**Issue by zwimer** [cockpit-project/cockpit#21216]
### Explain what happens

# Fundamental Issue

Cockpit responds to a `HEAD` request with non-zero body; or more specifically I believe (I will link the quote below where it has context):
> The "0\r\n" they're sending is part of the chunked transport encoding of the message body. It should not be present in a HEAD response.

Check via netcat; I believe that final `0\r\n\r\n` should not be present as it is body, not header.
```
$ nc localhost 9090
HEAD / HTTP/1.1
Host: localhost:9090
User-Agent: curl/8.6.0
Accept: */*

HTTP/1.1 200 OK
Content-Type: text/html
Content-Security-Policy: connect-src 'self' http://localhost:9090 ws://localhost:9090; form-action 'self' http://localhost:9090; base-uri 'self' http://localhost:9090; object-src 'none'; font-src 'self' http://localhost:9090 data:; img-src 'self' http://localhost:9090 data:; block-all-mixed-content; default-src 'self' http://localhost:9090 'unsafe-inline'
Set-Cookie: cockpit=deleted; PATH=/; SameSite=strict; HttpOnly
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store
X-DNS-Prefetch-Control: off
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
Cross-Origin-Resource-Policy: same-origin
X-Frame-Options: sameorigin

0

```

# Why I think this is a bug

An http `HEAD` request to cockpit behind my caddy reverse proxy yields a correct response, but also yields:
```
{"level":"info","ts":1730779270.247465,"msg":"Unsolicited response received on idle HTTP channel starting with \"0\\r\\n\\r\\n\"; err=<nil>"}
```
I believe it is sending extra data, which I am guessing based off of these comments on similar errors:
> The "0\r\n" they're sending is part of the chunked transport encoding of the message body. It should not be present in a HEAD response.

https://github.com/caddyserver/caddy/issues/4445#issuecomment-979301132
https://github.com/ipfs/go-ds-s3/issues/201#issuecomment-1057000832
https://github.com/golang/go/issues/19895#issuecomment-292729277

---

I run cockpit behind a reverse proxy, with `/etc/cockpit/cockpit.conf` set to:
```
[WebService]
Origins = https://cockpit.cryo.zwimer.com wss://cockpit.cryo.zwimer.com https://Cryo:9090 wss://Cryo:9090
ProtocolHeader = X-Forwarded-Proto
```

1. I have `caddy` configured to reverse proxy `localhost:9090` to `https://cockpit.cryo.zwimer.com` with TLS
2. This happens no matter how I make the head request; for example: `curl -vvv --insecure -I https://cockpit.cryo.zwimer.com`
3. The request returns validly with a 200 code, but in the caddy logs I see `{"level":"info","ts":1730779670.398779,"msg":"Unsolicited response received on idle HTTP channel starting with \"0\\r\\n\\r\\n\"; err=<nil>"}`

### Version of Cockpit

326

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Fedora

### Server operating system version

Fedora Workstation 40 & Fedora Cloud 41

### What browsers are you using?

Other

**Comment by zwimer** [comment]
I imagine they come from: https://github.com/cockpit-project/cockpit/blob/78108b91cec3ccdfa553ae8cd560caa4d5fa81fb/src/common/cockpitwebresponse.c#L620

**Comment by martinpitt** [comment]
Test on the CLI:
```
make ./test-server  && ./test-server
printf 'HEAD /mock/headonly HTTP/1.1\nHost: localhost:9090\nInputData: some\n\n' | nc localhost 8765
```

On current main it shows:

```
HTTP/1.1 200 OK
[... more headers ...]
X-Frame-Options: sameorigin

0

```

With the fix, the output terminates at `X-Frame-Options:`.
