### ISSUE TITLE
Change default landing page

### ISSUE THREAD

**Issue by SirH2Os** [cockpit-project/cockpit#21231]
Page: Landing page

Hello :wave: , is there a way to change the default landing page?

I've developed a package and I want it to be the default landing page after login, is there a way to do this?

I can't seem to find any documentation explaining this.

Thanks! :smile:

**Comment by SirH2Os** [comment]
I've found that using Shell = /packe_location/package_index.html in the cockpit.conf file makes the page load by default.

But I am still struggling to get the my package + cockpit's navigation menu to load together since redirecting the page with Shell does not load the navigation menu.

**Comment by martinpitt** [comment]
The default page is the one with the lowest `"order"` in the [package manifest](https://cockpit-project.org/guide/latest/packages.html). By default that's "Overview" with order 10, but you can create an [override](https://cockpit-project.org/guide/latest/packages.html#package-manifest-override) to change a page to a smaller positive number, or if it's your own page, set its manifest order accordingly.

**Comment by martinpitt** [comment]
... except that it is buggy: https://github.com/cockpit-project/cockpit/blob/main/pkg/shell/state.jsx#L547 (`else:` missing)

So that'll need a fix :sweat_smile: 

Thanks to @mvollmer for pointing out!

**Comment by jelly** [comment]
Should be fixed in https://github.com/cockpit-project/cockpit/pull/21271

**Comment by SirH2Os** [comment]
Hi again, I am new to this and understand that this bug will be fixed in the next release.

But since I am using  version 188-1 Cockpit on a Raspbian 10 (newest version available through apt) will I receive the update too?

If not, what can I do so I can make use of this fixed issue?

**Comment by martinpitt** [comment]
@SirH2Os You won't get a new Cockpit version, sorry. Version 188 was from Debian oldoldstable aka Debian 10, aka buster. This has long gone out of support. You'd have to upgrade to Debian 12 to get current versions (via backports).

That said, the code completely changed, and in 188 adding an override or changing the "order" in /usr/share/cockpit/systemd/manifest.json may just work.
