### ISSUE TITLE
TestHistoryMetrics.testEvents graph changes structure in updates-testing

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21237]
The job `fedora-40/updates-testing` failed on commit f474f0da1c6f723b9f55b4b599b5468047fc8a59.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-f474f0da-20241109-013334-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment]
Confirmed in #21241 this seems to be real.

**Comment by mvollmer** [comment]
What about not doing pixel tests for updates-testing? We don't have a mechanism to cope with pixel alternatives and any failure in updates-testing will just be pain.

If we write code like

```
self.assert_pixels("dialog" if not updates_testing else "dialog-testing", ...)
```

then the machinery will yet at us that one of "dialog" or "dialog-testing" is unused... but we could invent something if we want to.

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/bots/pull/7126 refreshes the image, but that fails on a handful of other issues. We'll update the pixel tests as part of that.
