### ISSUE TITLE
Can not switch to other servers after upgrading to Fedora 41

### ISSUE THREAD

**Issue by poVoq** [cockpit-project/cockpit#21236]
### Explain what happens

1. Upgrade to Fedora 41 and log into Cockpit as usual
2. Try to switch to another server via the usual drop-down menu
3. The drop-down menu is missing (no triangle and clicking the area has no effect):

![image](https://github.com/user-attachments/assets/450c883c-6eba-4d03-b146-84e333d06538)

Am I just missing some config option during the upgrade, or was this vital function removed?

### Version of Cockpit

327 (Fedora 41 server editon)

### Where is the problem in Cockpit?

Overview

### Server operating system

Fedora

### Server operating system version

41

### What browsers are you using?

Firefox

**Comment by poVoq** [comment]
Ah, looks like the default for `AllowMultiHost` was changed to false?

After setting it to true in cockpit.conf and restarting cockpit it works again.

**Comment by martinpitt** [comment]
Right, please see https://cockpit-project.org/blog/cockpit-322.html for details. Thanks!
