### ISSUE TITLE
Why not show BTRFS filesystem in list while create/format partition?

### ISSUE THREAD

**Issue by vihatsoft** [cockpit-project/cockpit#21274]
### Explain what happens

why BTRFS filesystem not show dropdown list when create or format partition?
already install btrfs and successfully format partition using command `sudo mkfs.btrfs /dev/sdX` however not show in dropdown list. 
cockpit version : 327-1~bpo12+1 
OS: RPI 64 bit Bookworm.
![image](https://github.com/user-attachments/assets/f0497b66-373a-4b2d-a1be-ff2b276005a0)

Thank you,

### Version of Cockpit

327-1~bpo12+1

### Where is the problem in Cockpit?

Storage

### Server operating system

Debian

### Server operating system version

12 (Bookworm)

**Comment by vihatsoft** [comment]
Solved with bellow commands :
```sudo apt install udisk2-lvm2
sudo apt install udisks2-btrfs
sudo apt install udisk2-iscsi```

**Comment by jelly** [comment]
The btrfs support depends on this, its not super clear from the UI so maybe we should put some effort into that.
