### ISSUE TITLE
follow-up: systemd: open path in terminal improvements

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#21281]
I noticed a few issue from the screenshots that should be handled in a follow-up:

![image](https://github.com/user-attachments/assets/63bc6994-f2a4-44fa-8c02-4ed25ead45ff)

- Have the error in the title instead of "error": "Directory does not exist"

![image](https://github.com/user-attachments/assets/e97b2e8c-6e4d-4a80-9a44-62a445da2397)

- Text needs to be reworked. Title: "Running process prevents directory change", Body: "Changing the directory will forcefully stop the currently running process." We might want to add a hint that this could be interactive by tacking on an extra sentence, with something like: "The process can also be stopped manually in the terminal before continuing."
- Action buttons should say what they will do. "Continue" isn't the action that's being performed; it's "Change directory".
- If this is a dangerous action, as the alert state indicates, then the button should reflect that; it shouldn't be a secondary button, but a danger button.

_Originally posted by @garrett in https://github.com/cockpit-project/cockpit/issues/21162#issuecomment-2482397469_

**Comment by ashley-cui** [comment]
@garrett For the directory does not exist warning, should the title include "Unable to open directory" or something like that, since the error itself is the inability to open the directory, and the reason is that it doesn't exist, or should the title be "Directory does not exist" If so, what should the description be? It seems like having a title of "Directory does not exist" and then "/asdf does not exist" would also be repetitive

**Comment by garrett** [comment]
@ashley-cui: Sure! You're right. That sounds good.

"Unable to open directory"
"/asdf does not exist."

Works for me! :+1: 

I'm guessing permissions would be an even more likely issue than a directory not being able to be opened, as (at least for now) Cockpit Files would already have to see that the directory exists to be able to request the Terminal to open it. I could imagine that the directory does not have +x permission for access, but can still be seen from Cockpit Files.

So, something like this could work in that case:

"Permission denied"
"Cannot open /asdf.  Permissions block access to this directory."
