### ISSUE TITLE
rpc.statd crash regression in Fedora 40

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21312]
The job `fedora-40/updates-testing` failed on commit c7d327f89f01ae54bd127020e7665dccea00aff3.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-c7d327f8-20241124-013228-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment]
This is a disaster.. The metrics failures are #21301 and #21237, but the nfs/rpc.statd crash is new. Moreover, bodhi is currently down, I can't see https://bodhi.fedoraproject.org/updates/?packages=nfs-utils . We need to stop this faulty update.

**Comment by martinpitt** [comment]
I blocked https://bodhi.fedoraproject.org/updates/FEDORA-2024-e27e34f8dc

**Comment by martinpitt** [comment]
The corresponding F41 update is https://bodhi.fedoraproject.org/updates/FEDORA-2024-39db8155bf . Let's test this as well and -1 if necessary. Our currently pending F41 refresh in https://github.com/cockpit-project/bots/pull/7123 still caught rc1 instead of rc2, and that one seemed to work.
