### ISSUE TITLE
can i use debianbackports to specify cockpit backports?

### ISSUE THREAD

**Issue by emaayan** [cockpit-project/cockpit#21351]
i'm trying to consolidate all installations in cloud-init but i couldn't find anything i can force the installation of a backport other than runcmd so i was wondering if i could create this backport file just for cockpit 

Package: cockpit-* 
Pin: release a=noble-backports
Pin-Priority: 900

**Comment by emaayan** [comment]
actually i would be concerned about using cockpit* because i could
potentially include other packages which starts with the word cockpit
won't this be better?

Package: cockpit-*
Pin: release a=${os_distro_name}-backports
Pin-Priority: 900
Package: cockpit
Pin: release a=${os_distro_name}-backports
Pin-Priority: 900

**Comment by martinpitt** [comment]
@emaayan Sure! :wink:

**Comment by BobDotCom** [comment]
Wouldn't it be simpler to use `src:cockpit` instead of the wildcards? That way all of the binaries are included automatically?

On my system (debian bookworm) it'd be
```
Package: src:cockpit
Pin: release n=bookworm-backports
Pin-Priority: 900
```

**Comment by martinpitt** [comment]
@BobDotCom But that wouldn't cover https://tracker.debian.org/pkg/cockpit-podman and https://tracker.debian.org/pkg/cockpit-machines (and cockpit-files, if it ever gets through the NEW queue). So it depends on your use case. TBH I think `cockpit*` is a good default unless you *know* you have more specific requirements.

**Comment by BobDotCom** [comment]
That makes sense, I didn't think of that. Thanks for the quick reply :)
