### ISSUE TITLE
Storage: Stop public automatic btrfs mounts

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#21355]
The recent [TestStorageBtrfs.testDeleteSubvolume](https://artifacts.dev.testing-farm.io/5fb0024f-2538-47dd-bdc3-75a20a30847d/) flakes point out some major issue on the Storage page that was introduced in PR #20893. @mvollmer TBH this feels like a giant hack to me -- mounting unmounted file systems without the user explicitly asking for it feels like asking for trouble:

 * It may (and does) trigger udev rules, may trigger backup software that backs up /var, or other system services that do something with files, and that may lead to unintentional modifications of the file system.
 * Silently ignoring unmount failures is a *grave bug* which could lead to data loss or information leakage. We know that the OS is "greedy" and triggers udev rules, systemd units, etc. for new mounts, and we have to (1) ensure that this eventually succeeds, and (2) failures have much less impact.
 * It is mounted read-write, which leads to potential data loss.

My gut feeling about this:
 * Never *ever* auto-mount a file system r/w, but always r/o. Storage could temporarily mount it read-only, in a separate mount namespace with private mount propagation (so that the OS, file browsers, backup software, etc. doesn't see it).
 * Unprivileged users must not be able to see and read files on these mounts even if the file permissions would ordinarily allow them to. There is a reason that the admin did not mount that file system, we don't know it.
 * Disable the features that rely on the writable temp mount (label change?). If Linux doesn't support that, neither should Cockpit.
 * Retry unmounting until successful, do a final lazy unmount.

To get rid of the worst security issues here, perhaps we can restrict this feature to Anaconda mode for now, and then rebuild it carefully for "normal" Cockpit mode?

https://issues.redhat.com/browse/COCKPIT-1210

[another instance in TestStorageBtrfs.testCreateSubvolume](https://artifacts.dev.testing-farm.io/b7add70a-1c47-4bfb-98ac-ed469b97cf15/)

**Comment by martinpitt** [comment]
Impact: This was introduced into Cockpit 326, so fortunately it doesn't affect RHEL 9.5/10 beta. Fedora is affected, but that's easy enough to update. Ubuntu 24.04 LTS and 24.10 releases are not affected, only backports. This is mitigated by the fact that RHEL doesn't support btrfs *phew*. But we should still not leave this open for long, as this is a potential data loss issue.

**Comment by mvollmer** [comment]
What about adding text to teh relevant dialogs to the effect of "The top-level subvolume will be temporarily mounted to carry out this operation."?

**Comment by mvollmer** [comment]
> * Silently ignoring unmount failures is a _grave bug_

Do you mean `remove_tmp_mount` in btrfs-tool.py?  That could be made more robust, indeed.
