### ISSUE TITLE
updates-testing failed: python3 core dumps

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21354]
The job `fedora-40/updates-testing` failed on commit ab76818721182151b95a6dd721414cea625a67cf.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-ab768187-20241129-013147-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment]
Smells related to the tracer crash: https://github.com/cockpit-project/bots/issues/7139, but needs a closer look as there are lots of test failures. It's very suspicious that all of them happened in the same machine (ND@3)

**Comment by martinpitt** [comment]
Hm, this doesn't willingly reproduce. I ran the same test prep and tests on the VM as in CI:
```
bots/image-customize --fresh -v --script test/vm.updates-testing fedora-40
test/image-prepare -q --overlay fedora-40
bots/vm-run fedora-40
```

```
test/verify/check-packagekit TestUpdates.testNoPackageKit $RUNC
test/verify/check-system-tuned TestTuned.testBasic $RUNC
# first test that crashed in CI
test/verify/check-system-info TestSystemInfo.testHardwareInfo $RUNC
# that one didn't crash
test/verify/check-superuser TestSuperuser.testNoPasswd $RUNC
# that one did again
test/verify/check-storage-swap TestStorageswap.testBasic $RUNC -stv
```
