### ISSUE TITLE
[Bug] Timesync conf permissions need a+r

### ISSUE THREAD

**Issue by OdinVex** [cockpit-project/cockpit#21364]
### Explain what happens

1. Specify NTP server via web interface.
2. Notice timesyncd doesn't use server but continues to fallback to distro defaults.
3. Checked status of systemd-timesyncd, failed to read `/etc/systemd/timesyncd.conf.d/50-cockpit.conf` until a+r just like `/etc/systemd/timesyncd.conf`.

This might be an Ubuntu-only thing but the configuration is created with permissions slightly too restrictive.

### Version of Cockpit

314-1

### Where is the problem in Cockpit?

Overview

### Server operating system

None

### Server operating system version

Ubuntu (latest as of 30/11/24)

### What browsers are you using?

Other

### System log

```shell
● systemd-timesyncd.service - Network Time Synchronization
     Loaded: loaded (/usr/lib/systemd/system/systemd-timesyncd.service; enabled; preset: enabled)
     Active: active (running) since Sat 2024-11-30 13:06:08 EST; 2s ago
       Docs: man:systemd-timesyncd.service(8)
   Main PID: 3349365 (systemd-timesyn)
     Status: "Connecting to time server [2620:2d:4000:1::3f]:123 (ntp.ubuntu.com)."
      Tasks: 2 (limit: 77027)
     Memory: 1.3M (peak: 2.0M)
        CPU: 178ms
     CGroup: /system.slice/systemd-timesyncd.service
             └─3349365 /usr/lib/systemd/systemd-timesyncd

Nov 30 13:06:08 <REMOVED> systemd[1]: Starting systemd-timesyncd.service - Network Time Synchronization...
Nov 30 13:06:08 <REMOVED> systemd-timesyncd[3349365]: Failed to parse configuration file: Permission denied
Nov 30 13:06:08 <REMOVED> systemd[1]: Started systemd-timesyncd.service - Network Time Synchronization.
```
```

**Comment by martinpitt** [comment]
Hello @OdinVex !

I tested this on current Ubuntu 24.04.1 in a default install, and it works fine:

```
# ls -l /etc/systemd/timesyncd.conf.d/50-cockpit.conf 
-rw-r--r-- 1 root root 70 Dec  4 08:06 /etc/systemd/timesyncd.conf.d/50-cockpit.conf
```

However, this happens if you change the default umask from 022 (or 002) to 077 or similar. What does `umask` and `sudo sh -c 'umask'` show you?

> Ubuntu (latest as of 30/11/24)

That doesn't tell me much, I'm afraid. Hopefully everyone keeps their OS up to date :grin: Please check /etc/issue or /etc/os-release for the Ubuntu release.

**Comment by martinpitt** [comment]
@OdinVex Excatly, the umask seddery you looked at was integration tests to reproduce the failure with tight umask. Not a runtime change.
