### ISSUE TITLE
updates-testing fails on F41: Unknown argument "--enable" for command "config-manager".

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21361]
The job `fedora-41/updates-testing` failed on commit 3c421eb3cb0c16d12a827bb0f5919ba1c906b756.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-3c421eb3-20241130-013128-fedora-41-updates-testing/log.html

**Comment by martinpitt** [comment]
This is the first run against F41. Whoops!
```
+ dnf config-manager --enable updates-testing
Unknown argument "--enable" for command "config-manager".
```
