### ISSUE TITLE
[Bug] Login history truncates IPv6 addresses

### ISSUE THREAD

**Issue by OdinVex** [cockpit-project/cockpit#21383]
### Explain what happens

1. Login via an IPv6 address.
2. View Accounts->account that logged in via IPv6 address
3. Notice login history truncation.

### Version of Cockpit

329-1

### Where is the problem in Cockpit?

None

### Server operating system

None

### System log

The actual `td` information is truncated. I checked the browser console log and noticed some JavaScript mixed with Python and Shell script in `/cockpit/@localhost/users/users.js`? Why would anything like that ever be in JavaScript for this? No matter what client-side interaction is doing this is weird.

**Comment by leomoty** [comment]
You can take a look at https://github.com/cockpit-project/cockpit/issues/16774#issuecomment-1004567527, which I believe already answers your question on truncated.

Other than that, the underlying code can be found here: https://github.com/cockpit-project/cockpit/blob/1ada2a5cc05f8f67d590ec79f2e12b741c505c59/pkg/users/account-logs-panel.jsx#L34

it spawns a shell and runs `last -n 25`.

**Comment by martinpitt** [comment]
Thanks @OdinVex ! I'll send a fix.
