### ISSUE TITLE
Testsuite fails on alpha due to incorrect filename for libc.so.6.1

### ISSUE THREAD

**Issue by glaubitz** [cockpit-project/cockpit#21396]
### Explain what happens

The testsuite fails on alpha as it assumes that the name of the shared C library is always `libc.so.6`:

```
=========================== short test summary info ============================
ERROR test/pytest/test_beiboot.py - OSError: libc.so.6: cannot open shared object file: No such file or directory
ERROR test/pytest/test_bridge.py - OSError: libc.so.6: cannot open shared object file: No such file or directory
ERROR test/pytest/test_pcp.py - OSError: libc.so.6: cannot open shared object file: No such file or directory
ERROR test/pytest/test_peer.py - OSError: libc.so.6: cannot open shared object file: No such file or directory
ERROR test/pytest/test_transport.py - OSError: libc.so.6: cannot open shared object file: No such file or directory
!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!
================== 1 deselected, 1 warning, 5 errors in 3.96s ==================
```

However, on alpha and ia64, it's actually `libc.so.6.1`.

Full build log at: https://buildd.debian.org/status/fetch.php?pkg=cockpit&arch=alpha&ver=330-1&stamp=1733378756&raw=0

### Version of Cockpit

330

### Where is the problem in Cockpit?

None

### Server operating system

Debian

**Comment by martinpitt** [comment]
Dang, there are [no porter boxes](https://db.debian.org/machines.cgi) for alpha, so I suppose I need to fix this blindly.

This first needs to be fixed in ferny, then synced over, and then do the same fallback in

```
src/client/cockpit-client:libc6 = ctypes.cdll.LoadLibrary('libc.so.6')
src/cockpit/transports.py:libc6 = ctypes.cdll.LoadLibrary('libc.so.6')
```
