### ISSUE TITLE
Client does not show dropdown due to FQDN length

### ISSUE THREAD

**Issue by towo** [cockpit-project/cockpit#21406]
### Explain what happens

1. Connect to a host with domain name/FQDN set.
2. Try to connect to another host.
3. Do not see dropdown to change hosts.
![Screenshot from 2024-12-08 22-19-04](https://github.com/user-attachments/assets/534894d9-7e26-46bb-9a00-8fd602b37759)

### Version of Cockpit

330-1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Arch Linux

### What browsers are you using?

Cockpit Client / Cockpit Desktop

**Comment by towo** [comment]
I'd suggest either truncating the host name (could still lead to problems with longer hostnames), making the divider adjustable (feels annoying to make the user accomodate the UI), or just drawing the dropdown indepedently of the field below it, on a higher CSS Z-level, in relation to the parent container.

**Comment by martinpitt** [comment]
@towo This is actually misleading -- the host switcher isn't *supposed* to work in the client. You need to log out and connect to a different host. Please see https://cockpit-project.org/blog/cockpit-322.html for more details. Sorry for the confusion!
