### ISSUE TITLE
IPA regression in updates-testing

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21424]
The job `fedora-41/updates-testing` failed on commit 35090b743b6b4536fc9c09cd9644c1c3b53c1cb2.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-35090b74-20241212-013206-fedora-41-updates-testing/log.html

**Comment by martinpitt** [comment]
Ugh, that could be an actual regression. Urgent pilot thing, we can possibly stop it in bodhi.

**Comment by martinpitt** [comment]
Note that [yesterday's run](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-2d6af150-20241211-013210-fedora-41-updates-testing/log.html) was still fine (wrt. IPA). freeipa was already the same version, but this run updated sssd.

**Comment by jelly** [comment]
And caught in bodhi already by Adam https://bodhi.fedoraproject.org/updates/FEDORA-2024-5afdb12065

**Comment by jelly** [comment]
https://issues.redhat.com/browse/RHEL-71134

**Comment by martinpitt** [comment]
That update got unpushed, and didn't break last night's run any more.
