### ISSUE TITLE
Can Debian10 Buster install Cockpit (329-1~bpo12+1)

### ISSUE THREAD

**Issue by lcy-1024** [cockpit-project/cockpit#21459]
Page: 

Debian10 Buster can only install Cockpit (188-1) version. How can I install updated versions, such as Cockpit (329-1~bpo12+1)

**Comment by martinpitt** [comment]
Sorry, you can't. We don't support Debian 10 (buster) any more on current releases. If you can't update to Debian 12, your other choice is to install the [Client flatpak](https://github.com/flathub/org.cockpit_project.CockpitClient) or the [ws container](https://quay.io/repository/cockpit/ws) somewhere else, and then connect to that Debian 10 machine remotely. However, here be dragons -- as said we don't support/test Debian 10 any more, so expect some broken functionality.
