### ISSUE TITLE
fuzzy spinner in Subscriptions

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2147]
When looking if there is a subscription, the spinner that shows up looks a bit fuzzy compared to the sharp ones on https://www.patternfly.org/widgets/#spinner

Not sure why this is.

**Comment by dperpeet** [comment]
Firefox 31.6:
![spinner_patternfly](https://cloud.githubusercontent.com/assets/8711649/7260283/39009954-e869-11e4-8870-a7c6d76ebc3c.png)
![spinner_cockpit](https://cloud.githubusercontent.com/assets/8711649/7260281/37ab9360-e869-11e4-819c-56fb61159fd4.png)

Looks ok to me. Did you check after https://github.com/cockpit-project/cockpit/commit/454027604fa26ce715b5699921cb1d08ea222931 today? I centered the spinner like the other status messages...

**Comment by andreasn** [comment]
Might be something that was temporary iffy with my system. Closing
