### ISSUE TITLE
Link to the Subscription registration

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2148]
In the *Register System* dialog we say:

"To create a login, please visit https://www.redhat.com/wapps/ugc/register.html"

Shouldn't we just have a link, with a target of a new tab/window?

**Comment by andreasn** [comment]
Sounds sane.

**Comment by dperpeet** [comment]
Technically we don't say that, it's just the message that comes from the subscription server (whichever was used). We could convert all http / https links to actual links.
Would that make sense @andreasn ?

**Comment by stefwalter** [comment]
> We could convert all http / https links to actual links. 

Makes sense to me. I would suggest leaving both the href and the clickable text as the full URL.

**Comment by andreasn** [comment]
> We could convert all http / https links to actual links.

Yeah, that sounds like a good approach.
