### ISSUE TITLE
Dashboard misalignments after Patternfly update

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2157]
Various misalignments on the dashboard. Seems to be after the patternfly update:

![screenshot from 2015-04-16 10-49-52](https://cloud.githubusercontent.com/assets/795070/7177374/67ce0ab0-e426-11e4-99c3-7f3784683358.png)

 * No space between graph and Servers listing.
 * Click on the [ ] check icon, and the [edit] and [delete] icons are too low.
 * "My Name" the machine name is too high, and doesn't line up with the "Dashboard" and "Cluster"

**Comment by andreasn** [comment]
This looks like it was fixed in:
https://github.com/cockpit-project/cockpit/commit/4de6e772e497d3d364b70d80f0ef6e23e5e39ccb
https://github.com/cockpit-project/cockpit/commit/9612275613eb935512f1ad27cf6296a2caca8846

Closing
