### ISSUE TITLE
Cockpit asking for password twice (httpd-like popup)

### ISSUE THREAD

**Issue by ghost** [cockpit-project/cockpit#2164]
Hi,
I got cockpit running on a fresh un-modified Fedora 21 Server and one thing I've noticed is that when I access https://server:9090/ it shows a apache-like popup asking for a user/password. Both root and my sudo user don't work, but if I click cancel it show the normal cockpit login page and it all works from there.
How can I remove this popup, or it is really a bug?

[user@server ~]$ rpm -qa | grep cockpit
cockpit-assets-0.27-4.fc21.noarch
cockpit-0.27-4.fc21.x86_64
[user@server ~]$ cat /etc/redhat-release
Fedora release 21 (Twenty One)

Thanks.

**Comment by stefwalter** [comment]
Could you post a screenshot?

**Comment by hezitemaj** [comment]
Sure!

Guess it's normal because of the self-signed certificate.
![cert](https://cloud.githubusercontent.com/assets/9095120/7208635/2f4cddb4-e53a-11e4-864d-52a6b4233891.jpg)

The autentication I'm refering to:
![auth](https://cloud.githubusercontent.com/assets/9095120/7208638/34e57c4a-e53a-11e4-88ce-63502410f9a0.jpg)

After hitting cancel:
![after cancel](https://cloud.githubusercontent.com/assets/9095120/7208640/39c6f2b6-e53a-11e4-8425-c86ed7ec5e9e.jpg)

**Comment by stefwalter** [comment]
Interesting. What is your browser and the operating system that your browser is running on?

**Comment by hezitemaj** [comment]
I'm using Windows 8.1 Pro (x64), and I've tried with Google Chrome 42.0.2311.90 m and Internet Explorer 11.0.9600.17728.

**Comment by stefwalter** [comment]
Since windows browsers seem to prompt for Kerberos auth (instead of using using SSO) ... it looks like we need some server side logic to detect whether GSSAPI auth is configured or not. We can't opportunistically use it.

This isn't as easy as it seems as GSSAPI can be configured via gss-proxy ... needs some thought.

**Comment by hezitemaj** [comment]
I've tried to access from a Linux machine (Fedora 21 Workstation) and the issue was not present, it's working as it should. So yeah, seems like it happens only in Windows browsers.

**Comment by jfarcher** [comment]
Interestingly I was also seeing this issue using Chrome on Windows, using Firefox on Windows however doesn't present the httpd style login window.

**Comment by jds2001** [comment]
Firefox probably doesn't support the Kerberos GSSAPI that Chrome does. I'll add that I'm seeing this as well, in both F23 and rawhide, both of which appear to have the same version of cockpit ATM (0.83). Same observation of Firefox vs. Chrome as well. IE11 also has the prompt.

**Comment by stefwalter** [comment]
I've been meaning to fix this. Essentially during startup we need to detect if a keytab is available, and if it is not, don't offer GSSAPI auth.

**Comment by bortek** [comment]
Yeah I have the same issue and it is really annoying. I am on Windows 7 and use Chrome.

**Comment by stefwalter** [comment]
@bortek Could you test the above pull request #3278 

You would need to do something like the following on your target system:

```
$ git clone https://github.com/cockpit-project/cockpit
$ cd cockpit
$ tools/make-rpms
$ yum install *.rpm
```

**Comment by Neustradamus** [comment]
@atodorov, @chris1984, @dperpeet, @evan-goode, @Gundersanne, @jniederm, @martinpitt, @marusak, @mvollmer, @QiWang19, @sgallagher
@stefwalter, @jfarcher, @bortek, @jds2001
@sebabordon, @NULUSIOS, @H20-17:

Can you reopen this ticket ?

It is not solved after more 5 years!

One day a security solution?

**Comment by marusak** [comment]
> Can you reopen this ticket ?

There is https://github.com/cockpit-project/cockpit/issues/13202 which is the same issue, isn't it?

**Comment by NULUSIOS** [comment]
Issue still happens.

**Comment by Neustradamus** [comment]
To all, there is a fix in https://github.com/cockpit-project/cockpit/pull/13982 for:
- https://github.com/cockpit-project/cockpit/issues/2164
- https://github.com/cockpit-project/cockpit/issues/13036
- https://github.com/cockpit-project/cockpit/issues/13202
