### ISSUE TITLE
Resizing login screen width, makes 'Login In' button jump

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2171]
Resizing login screen width, makes 'Login In' button jump around. Seen on Firefox. As I resize it smaller, the 'Log In' button jumps from left to right and back.

**Comment by andreasn** [comment]
I see this when resizing to between 769px and 879px.

**Comment by andreasn** [comment]
The log in button box and the spinner box fights for the space in a weird way and the spinner box ends up overlapping with the log in box.

**Comment by andreasn** [comment]
Not the nicest fix in the world, but it seems to do the trick.

**Comment by stefwalter** [comment]
Seems fine to me. Will you be making a pull request?

**Comment by andreasn** [comment]
Hups. I hadn't done that already?
Done now.
