### ISSUE TITLE
nginx redirect bug

### ISSUE THREAD

**Issue by ramantalkin** [cockpit-project/cockpit#2185]
i don't know if this is really a bug or config mis-match, here it goes.
i installed cockpit 0.52 on an arch host with custom ssl certificate running on default port 9090 connected via domain name like domain.com:9090, and it worked well and good. then i created a dns based nginx redirect like cockpit.domain.com it also worked good until i login, as i login it says 'Server has closed the connection' with options 'Try to reconnect' and 'login again'

server {
       listen         80;
       server_name    cockpit.domain.com www.cockpit.domain.com;
       return         301 https://$server_name$request_uri;
}

server {
    listen 443;
    server_name www.cockpit.domain.com cockpit.domain.com;

        ssl on;
        ssl_certificate /home/ssl/ohl.crt;
        ssl_certificate_key /home/ssl/ohl.key;

    location / {
        proxy_pass http://127.0.0.1:9090;
        include /etc/nginx/proxy_params;
    }
}

firstly i thought it could be due to ssl, so i modified systemctl service file with '--no tls' option but the problem remains, altogether cockpit does not uses ssl when connecting from localhost.

I don't know if it is really a bug or i just need config documentation.

**Comment by stefwalter** [comment]
Cockpit uses web sockets, and if you want to proxy it, you'll need to proxy that too:

https://lists.fedorahosted.org/pipermail/cockpit-devel/2015-April/000285.html

If you would like to make documentation on how to use nginx with Cockpit on the github wiki, that would be great. Somewhere like this:

https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit

**Comment by ramantalkin** [comment]
after crawling web for 2 hours, i am still confused with the issue.

**Comment by ramantalkin** [comment]
after crawling the web for 2 hours, i am still confused. here is my nginx virtual host file

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

upstream websocket {
    server 127.0.0.1:9090;
}

server {
       listen         80;
       server_name    cockpit.domain.com www.cockpit.domain.com;
       return         301 https://$server_name$request_uri;
}

server {
    listen 443;
    server_name www.cockpit.domain.com cockpit.domain.com;

        ssl on;
        ssl_certificate /home/ssl/ohl.crt;
        ssl_certificate_key /home/ssl/ohl.key;

    location / {
        proxy_http_version 1.1;

        # needed for websocket
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://127.0.0.1:9090;
        include /etc/nginx/proxy_params;
    }
}

i even changed web socket from port 9090 to 80 and 443, as it describes address on which client listens, a config file without map and upstream parameters gives error. (logs: nginx fails to recognize connection upgrade)
also tried to change "Origin" Http-Header from https to http as was in https://lists.fedorahosted.org/pipermail/cockpit-devel/2015-April/000285.html (the link you provided), in that case nginx fails to restart
here is the source from where i configured this config
http://nginx.org/en/docs/http/websocket.html
http://files.cockpit-project.org/guide/cockpit.conf.5.html
now earlier i used to connect via IP:9090 so i created /etc/cockpit/cockpit.conf and added.
[Webservice]
Origins = https://cockpit.orionholdings.org https://www.orionholdings.org:9090

still it gives the same exact error.

**Comment by stefwalter** [comment]
The cockpit mailing list is a good place to ask for support, and exchange ideas around proxying. 

https://lists.fedorahosted.org/mailman/listinfo/cockpit-devel

None of the core Cockpit developers proxy or have done any work on proxying cockpit. Until very recently (with nginx WebSocket proxying support) it was impossible.

This is not a bug.

**Comment by ramantalkin** [comment]
ahh!! now it is working, i upgraded my nginx to 1.6.3, earlier i had 1.4, i guess web socked update was with version 1.3... anyways it works now, i would definately take time and write a mini wiki for nginx proxy.
Thanks
