### ISSUE TITLE
Clicking on 'On' in OnOff turns Off

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2188]
When an OnOff is 'On', and i click on 'On' it turns 'Off'. It should stay On. 

Otherwise the UI is unpredictable and confusing even knowing what state the button is in.

**Comment by andreasn** [comment]
This is how the GNOME on/off buttons work. I think it's similar in other UIs, but I'll do some more research. I'm probably OK with modifying the behaviour.

**Comment by stefwalter** [comment]
This is an active area of controversy in web design, but I believe there are some best practices around. Worth talking with @rhamilto about it too.

**Comment by stefwalter** [comment]
This should be fixed now.
