### ISSUE TITLE
Brand name based on /etc/os-release

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2198]
Right now the brand name is controlled by some png's in brand/os-name
Stephen Gallager brought up that this is a bit weird for systems where two products share the same package, such as Fedora Workstation and Fedora Server. This request also came up in other discussions for RHEL and Atomic.

The suggestion on IRC was $NAME $VARIANT (variant is being added to Fedora 22  and to "the spec", NAME is pretty standard). The system would fall back on $NAME only if $VARIANT is missing.

**Comment by andreasn** [comment]
This also happens on Fedora Atomic, where it's incorrectly called "Fedora Server"

**Comment by stefwalter** [comment]
@rhamilto We would like to use text instead of an image for branding:

 * On the login screen above the login area
 * Above the navbar

**Comment by andreasn** [comment]
We'll probably be best off if we use Overpass http://www.fontsquirrel.com/fonts/overpass at 24px for the login screen and 14px for the top-bar.

**Comment by stefwalter** [comment]
So do we distribute the Overpass font?

**Comment by andreasn** [comment]
Not currently, but we would have to. It's under a SIL license.

**Comment by rhamilto** [comment]
I suggest limiting the use of Overpass to only the downstream projects since Overpass is a key component of Red Hat branding.  PatternFly uses Open Sans to avoid this conflict.

**Comment by andreasn** [comment]
All right, might need to add a little class that we can override in the RHEL branding in the end.
So:
```
font-family: open sans;
letter-spacing: 2px;
font-size: 24px;
```

**Comment by stefwalter** [comment]
We have branding specific CSS, so I don't think that's a problem.

**Comment by andreasn** [comment]
could also add text-transform: uppercase;

**Comment by andreasn** [comment]
This one is done. Closing.
