### ISSUE TITLE
Patternfly box styling is broken

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2203]
The combo box styling is broken. You can see this in the work on #1989 

![screenshot from 2015-04-23 17-29-46](https://cloud.githubusercontent.com/assets/795070/7300753/5bb1ff8a-e9de-11e4-809a-9b903809e4e2.png)

 * The blue highlight (if present at all) should be around the entire control, not just the input area.
 * The width of the drop down should match the width of the control.
 * The [v] button does not change state when clicked. It also doesn't hover like other buttons in Patternfly.

CC @rhamilto

**Comment by rhamilto** [comment]
> * The blue highlight (if present at all) should be around the entire control, not just the input area.

Given a combobox is a combination of a text input *and* a dropdown, I believe the behavior is correct as is.  The focus should be solely on the text input so users know that they can input text there.  This behavior is consistent with the way the "Data Live Search" functionality of Boostrap-selects works.  See https://www.patternfly.org/wp-content/uploads/patternfly/tests/bootstrap-select.html 

> * The width of the drop down should match the width of the control.

Agreed.  This is fixed.  https://github.com/patternfly/patternfly/issues/60

> * The [v] button does not change state when clicked. It also doesn't hover like other buttons in Patternfly.

Agreed.  I've added a bug for this to the backlog. https://trello.com/c/szp3ElND/65-bootstrap-combobox-v-buttons-lack-the-hover-active-and-focus-behavior-of-regular-boostrap-buttons

**Comment by rhamilto** [comment]
> Agreed. I've added a bug for this to the backlog. https://trello.com/c/szp3ElND/65-bootstrap-combobox-v-buttons-lack-the-hover-active-and-focus-behavior-of-regular-boostrap-buttons

This is done. https://github.com/patternfly/patternfly/commit/ccd3c221a7d2c4cfb0fb1cd4de502cfa057f0524

**Comment by stefwalter** [comment]
Should be fixed now.
