### ISSUE TITLE
branding doesn't affect title

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2207]
The branding covers almost all of Cockpit, but on my F22 Server, it still says "Cockpit" and not Fedora Server. On one of my F21 boxes I get the title set to the hostname of the box.
If we can get the hostname back, that would be awesome, and ideally we should also fall back to the brand (from /etc/os-release perhaps)

**Comment by stefwalter** [comment]
Looks like we need to have textual branding for both the login screen and the navbar.

Lets just ping @rhamilto so he's aware in case this is something Patternfly also wants to solve.

**Comment by rhamilto** [comment]
@stefwalter, @andreasn:  I've added a card to backlog for this.  https://trello.com/c/9wjA1Jz6/66-add-html-text-alternates-for-product-name-in-navbar-and-login-page  I will need to discuss this with the PatternFly team before we proceed.

**Comment by rhamilto** [comment]
@stefwalter After discussing this with the team, we've decided we don't want to support an HTML-text alternate, but you guys are more than welcome to create whatever solution is appropriate for Cockpit.  I will delete the aformentioned Trello card.  cc: @kybaker

**Comment by andreasn** [comment]
All right, we'll go ahead with a Cockpit specific solution then. Thanks!

**Comment by stefwalter** [comment]
Discussion of how the os VARIANT is represented in ```/etc/os-release```

http://lists.freedesktop.org/archives/systemd-devel/2015-April/031336.html

**Comment by petervo** [comment]
@andreasn Could you explain exactly what you would like the title to be? The title is currently Section - Hostname.

If there is no hostname, then it defaults to Cockpit.

Or were you talking about something other than the <title> of the page.

**Comment by stefwalter** [comment]
When no host name, instead of defaulting to "Cockpit" it should default to "Fedora Server" or whatever.
