### ISSUE TITLE
Improve About dialog

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#2213]
Hi,
I've opened About dialog, and I've found that there is:

About Cockpit
Cockpit is an advanced application with many options.
Version 0.53.
Built on Fri Apr 24 07:45:43 EDT 2015.

I've expected that there could be info for example like mentioned on: 
https://github.com/cockpit-project/cockpit/blob/master/README.md#about

and also link to upstream or upsream doc could be good.
      Regards
      Honza

**Comment by stefwalter** [comment]
Are you interested in providing a patch to fix the about dialog?

**Comment by jscotka** [comment]
No, It is more less cosmetic, and I'll see what are your ideas how text could be there  and probably I'll provide next feedback.
Is it okay?

**Comment by stefwalter** [comment]
I guess @andreasn might be able to provide feedback on how it should look.

**Comment by andreasn** [comment]
I would suggest replacing:
"Cockpit is an advanced application with many options." with "Cockpit is an interactive Linux server admin interface." and link to www.cockpit-project.org saying "Project website"

**Comment by jscotka** [comment]
It sounds good. Probably there coul be also cockpit logo.

**Comment by mvollmer** [comment]
Should we mention that it is free software and the license?

**Comment by jscotka** [comment]
Probably string "Built on Fri Apr 24 07:45:43 EDT 2015." could be removed, version is important, but that string is not so important to be in about dialog from my POV.

**Comment by andreasn** [comment]
@mvollmer yeah, I think that's a good idea.
@jscotka Agreed.
