### ISSUE TITLE
errors/warnings in journal related to cockpit

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#2214]
Hi,
I've tested  Version 0.53. (Built on Fri Apr 24 07:45:43 EDT 2015)  and when I was randomly clicking via web interface (over slow network) there appeared more cockpit journal logs:

journal errors:
cockpit-bridge: (src/bridge/cockpithttpstream.c:876):cockpit_http_stream_close: code should not be reached14:47
udisksd: Error probing device: Error sending ATA command IDENTIFY DEVICE to /dev/sda: ATA command failed: error=0x01 count=0x00 status=0x50 (g-io-error-quark, 0)14:14
cockpit-ws: couldn't read from connection: Error reading data from TLS socket: A TLS fatal alert has been received.

journal warnings:
cockpit-bridge: (src/bridge/cockpithttpstream.c:876):cockpit_http_stream_close: code should not be reached14:47
cockpit-bridge: org.freedesktop.NetworkManager: couldn't get all properties of org.freedesktop.NetworkManager.AgentManager at /org/freedesktop/NetworkManager/AgentManager: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "GetAll" with signature "s" on interface "org.freedesktop.DBus.Properties" doesn't exist 214:46
cockpit-bridge: org.freedesktop.NetworkManager: couldn't get all properties of com.redhat.ifcfgrh1 at /com/redhat/ifcfgrh1: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "GetAll" with signature "s" on interface "org.freedesktop.DBus.Properties" doesn't exist 214:46
cockpit-bridge: org.freedesktop.NetworkManager: couldn't get all properties of org.freedesktop.DBus.Properties at /org/freedesktop/NetworkManager: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "GetAll" with signature "s" on interface "org.freedesktop.DBus.Properties" doesn't exist 14:46
cockpit-bridge: cockpit-pcp: failed to execute bridge: not found1314:45
cockpit-bridge: org.freedesktop.NetworkManager: couldn't get all properties of org.freedesktop.NetworkManager.AgentManager at /org/freedesktop/NetworkManager/AgentManager: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "GetAll" with signature "s" on interface "org.freedesktop.DBus.Properties" doesn't exist 214:42
cockpit-bridge: org.freedesktop.NetworkManager: couldn't get all properties of com.redhat.ifcfgrh1 at /com/redhat/ifcfgrh1: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "GetAll" with signature "s" on interface "org.freedesktop.DBus.Properties" doesn't exist 214:42
cockpit-bridge: org.freedesktop.NetworkManager: couldn't get all properties of org.freedesktop.DBus.Properties at /org/freedesktop/NetworkManager: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "GetAll" with signature "s" on interface "org.freedesktop.DBus.Properties" doesn't exist

**Comment by stefwalter** [comment]
These warnings are now suppressed.
