### ISSUE TITLE
Oooops: TypeError: self.client is null shell.js:5933:20

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#2229]
Hi,
it seems that line 
                var manager = self.client.lookup("/com/redhat/Cockpit/Storage/Manager", "com.redhat.Cockpit.Storage.Manager");
is not reliable, somethines happen red Oooops: TypeError: self.client is null shell.js:5933:20
Machine was on slow network,  version of cockpit 0.53.
I'm unable to debug that more.
@mvollmer met same issue on that machine.
     Honza

**Comment by stefwalter** [comment]
This has now been fixed. The code here has been rewritten.
