### ISSUE TITLE
Login: sane error message if password authentication is disabled

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#2230]
Currently we get this screen when we try to log in as a user that doesn't have password authentication enabled:
![check-login-testbasic-fail](https://cloud.githubusercontent.com/assets/8711649/7412511/ebd4678c-ef43-11e4-83f9-14d15a48d85f.png)

The message should make sense and show some contextual info.

**Comment by stefwalter** [comment]
This has now been fixed.
