### ISSUE TITLE
Change date: error when closing datepicker

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#2241]
Steps to reproduce:
- login
- navigate to system
- click on time to open "Change System Time" dialog
- click on date to open datepicker
- click outside of the picker to close ("cancel")
- see error:

![datepicker_error](https://cloud.githubusercontent.com/assets/8711649/7460147/4a80dad0-f2a1-11e4-9653-42440ea2a020.png)

Once a date has been picked, subsequent "cancel" clicks don't lead to this error.

**Comment by andreasn** [comment]
Confirmed. It should go back to the number it started with in this case.

**Comment by stefwalter** [comment]
Sholud now be fixed.
