### ISSUE TITLE
Network: Add bridge control alignment

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#2242]
In the "add bridge" dialog (networking) the checkbox for Spanning Tree Protocol (STP) isn't aligned with the other checkboxes in the same column.

![error_alignment](https://cloud.githubusercontent.com/assets/8711649/7460395/fb06416e-f2a2-11e4-8916-265b4ec88fe1.png)

**Comment by andreasn** [comment]
Having the checkbox on the right of the label is part of the problem.
Since it's a network traffic routing kind of thing, would it be correct to have something like?
Routing: [x] Use Spanning Tree Protocol

**Comment by andreasn** [comment]
The above commit takes care of the issue, but creates the issue that all labels jump when STP gets checked, since the "STP Maximum message age" is a really long label.

**Comment by andreasn** [comment]
And the Ports goes away :(

**Comment by andreasn** [comment]
This is what I wanted the end result to look like.
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/network/network-dialogs.png)

**Comment by marusak** [comment]
Now the ports are in separate box and things are alligned correctly.
Also we should use `<fieldset>` not `<ul>` for ports, but that is for some other time :)
![addbridge](https://user-images.githubusercontent.com/12330670/68197621-d986c980-ffba-11e9-8592-02828d1bfe3b.png)
