### ISSUE TITLE
kubernetes watches may be overly aggressive

### ISSUE THREAD

**Issue by jeffvance** [cockpit-project/cockpit#2246]
On a host with no kubernetes, etcd, docker installed, when I go to the "Clusters" main view and look at the console I see the following:
...
client.js:213 watching kubernetes services failed: Internal error
client.js:213 watching kubernetes pods failed: Internal error
client.js:213 watching kubernetes namespaces failed: Internal error
client.js:213 watching kubernetes replicationcontrollers failed: Internal error
client.js:213 watching kubernetes nodes failed: Internal error
client.js:213 watching kubernetes services failed: Internal error
client.js:213 watching kubernetes pods failed: Internal error
client.js:213 watching kubernetes namespaces failed: Internal error
client.js:213 watching kubernetes replicationcontrollers failed: Internal error
client.js:213 watching kubernetes nodes failed: Internal error
client.js:213 watching kubernetes services failed: Internal error
client.js:213 watching kubernetes pods failed: Internal error
client.js:213 watching kubernetes namespaces failed: Internal error
client.js:213 watching kubernetes replicationcontrollers failed: Internal error
client.js:213 watching kubernetes nodes failed: Internal error
client.js:213 watching kubernetes services failed: Internal error
client.js:213 watching kubernetes pods failed: Internal error
client.js:213 watching kubernetes namespaces failed: Internal error
client.js:213 watching kubernetes replicationcontrollers failed: Internal error
client.js:213 watching kubernetes nodes failed: Internal error
...

This seems to be potentially inconsistent with the lighweight, low resource consumption goals for cockpit. Is it possible (or desireable) to reduce the polling interval when kubernetes is not installed? I assume we need some polling to handle the case of the customer freshly installing kubernetes.

**Comment by stefwalter** [comment]
Kubernetes requires keeping open about 5 or 6 watches in order to get object state. @fsimonce has some ideas on how to remedy this.

 When the watches fail, we start them again after 5 seconds (in git master). Is this what you mean by 'polling'?

**Comment by jeffvance** [comment]
Yes Stef. I should have written restart watches, not polling.

**Comment by stefwalter** [comment]
By the way, I think you need kubernetes 0.15.0 if you're using git master. I'll do a pull request to update the README.md. Things are changing rapidly with kubernetes.

**Comment by stefwalter** [comment]
Yes, we do need a curtain screen on that dashboard that covers the case where Kubernetes is not installed. In addition we need to detect Openshift and handle that accordingly, as well as 'access denied' type failures.

**Comment by jeffvance** [comment]
kubectl version
Client Version: version.Info{Major:"0", Minor:"15+", GitVersion:"v0.15.0-824-g99fc906f78cd2b", GitCommit:"99fc906f78cd2bcb08536c262867fa6803f816d5", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"15+", GitVersion:"v0.15.0-824-g99fc906f78cd2b", GitCommit:"99fc906f78cd2bcb08536c262867fa6803f816d5", GitTreeState:"clean"}

Does this look current enough?

**Comment by stefwalter** [comment]
Yup.

**Comment by jeffvance** [comment]
# top on host machine shows cockpit-ws consistently at 5% cpu when not in use.

**Comment by stefwalter** [comment]
cockpit-ws should exit after 10 minutes, if not in use. Is it staying around?

**Comment by jeffvance** [comment]
Stef, yes cockpit-ws is staying around. I haven't used cockpit 9090 on my laptop since 8+ hours ago and I still see cockpit-ws using 5.+ % cpu.

**Comment by stefwalter** [comment]
There is no way to track kubernetes without many many watches. This is a known issue upstream. When it is resolved there, we will use less watches.
