### ISSUE TITLE
Should the color of the graph line for remote servers match each server's color?

### ISSUE THREAD

**Issue by jeffvance** [cockpit-project/cockpit#2247]
On the host's dashboard screen each remote server (shown at the bottom) has a unique color to the left of the server name. Each server's color is also used in the graph seen at the top of the screen.
However, when I select a remote server, even though that server's color is displayed just left of the server name, the system graph line is still rendered in blue.
Should the graph line in the System view for a remote server be the same color as assigned to that server?

**Comment by andreasn** [comment]
The colors on the dashboard are used first and foremost to tell the servers apart from each other. On the server page this problem doesn't exist, so it's can use a more standard that always have good contrast (some of the yellows have some issues with this against white).
For identifying the exact server you're on, the color is indicated in the top left, next to the name. I think that's enough.
