### ISSUE TITLE
Cockpit shows the wrong disk usage

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2256]
I've observed this on a couple of my ARMv7 systems, so it might be specific to that architecture somehow.

![screenshot from 2015-05-07 11-15-48](https://cloud.githubusercontent.com/assets/209895/7512065/70289646-f4aa-11e4-9c32-e05a556111f4.png)

**Comment by cmurf** [comment]
Looks related to issue 1561.
