### ISSUE TITLE
Cockpit installed from CentOS Extras repo shows RHEL branding

### ISSUE THREAD

**Issue by danofsatx** [cockpit-project/cockpit#2282]
I just installed cockpit-0.53-3 from the CentOS 7 Extras repo, and the login page says "Red Hat Enterprise Linux 7" with the Red Hat "Shadowman" logo in the top right corner and as the favicon.

I don't know if this is handled by cockpit or CentOS, but it is filed also at:
 http://bugs.centos.org/view.php?id=8659

**Comment by stefwalter** [comment]
Centos can provide branding upstream if they want (in our ```branding```) directory, or they can patch it into their build.

**Comment by andreasn** [comment]
Fixed here: https://github.com/cockpit-project/cockpit/commit/ba59f250a0fd4fa4e3f3173ef0c819a9c8420da8
