### ISSUE TITLE
when downloading a container, _all_ tags are downloaded

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2309]
![screenshot from 2015-05-19 13-38-43](https://cloud.githubusercontent.com/assets/209895/7701945/638d1b4c-fe2c-11e4-8d6e-6d4f234458bf.png)

**Comment by stefwalter** [comment]
Which operating system and docker version is this?

**Comment by andreasn** [comment]
Fedora 21
Docker 1.6.0

**Comment by martinpitt** [comment]
I tried to download the "nginx" image, first the default "latest" tag, then delete it again, and download the "mainline" tag. In both cases just that one tag got downloaded:
```
❱❱❱ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
docker.io/nginx     mainline            7042885a156a        2 weeks ago         109 MB
```
As this is quite old and does not have further information, I close this now. Please reopen if it still happens for you. Thanks!
