### ISSUE TITLE
replication controllers without a service are 'unfindable'

### ISSUE THREAD

**Issue by eparis** [cockpit-project/cockpit#2366]
If you have created a replication controller in your cluster, but have not defined a service which selects the pods in the replications controller, you have no way to know the rc is running in the overview pane.

**Comment by stefwalter** [comment]
The overview shows "wellformed" services not random kube objects.

But the point of this issue is valid. There should be other views where these are findable.

**Comment by eparis** [comment]
Is this conflated 'services' the right front page display then? (you know I've never much cared for it)  Even random pods are at least discover-able on the 'pods' tab.

Imagine pods doing some distributed calculation, some sort of map/reduce type thing. They would have an rc, but no service. I don't think that doing so is in any way not 'wellformed'...

**Comment by petervo** [comment]
These are now visible in the details view.
