### ISSUE TITLE
annotations incorrect on topology details

### ISSUE THREAD

**Issue by eparis** [cockpit-project/cockpit#2367]
Given a pod with annotations `"kubernetes.io/created-by": "{\"kind\":\"ReplicationController\",\"namespace\":\"default\",\"name\":\"database\",\"uid\":\"124f9735-ed13-11e4-bb09-b8ca3a5fb15c\",\"apiVersion\":\"v1beta3\",\"resourceVersion\":\"1277168\"}"`

The details pain on the right shows:

`kubernetes.io/...   {{value}} {{value.substring(0, 120)}}...`

**Comment by eparis** [comment]
(which also happens to be a backpointer from the pod to the replication controller which created it)

**Comment by stefwalter** [comment]
This should be fixed by: https://github.com/kubernetes-ui/object-describer/pull/21

**Comment by mvollmer** [comment]
Tracked elsewhere.
