### ISSUE TITLE
atomic: correct permission denied message for users

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#2402]
When logging in as a user without admin role, permission should be denied. Instead, there is a different message: "connect or authenticate: terminated"
We currently have a workaround in the tests, but the underlying issue should be fixed:
https://github.com/cockpit-project/cockpit/pull/2231#discussion-diff-31327545R66

**Comment by petervo** [comment]
sshd doesn't always tell us why a server disconnects. So we can't really have the same message as cockpit-session logins. If you try on the command line all you see is: "Connection closed by xxx"

We probably can make the message better though. We do know if we were at least prompted for credentials so we can differentiate between no connection and when our connection was closed mid-auth, for whatever reason.

So my suggested is to show "Authentication Failed: Server closed the connection" as the error and show the username/password prompt again.

@andreasn WDYT?

**Comment by andreasn** [comment]
"Authentication Failed: Server closed the connection" sounds good to me.

**Comment by petervo** [comment]
Fixed in #3797
