### ISSUE TITLE
Double brand

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2420]
It seems it does both the textual and the image based branding.

![screenshot from 2015-06-11 13-25-24](https://cloud.githubusercontent.com/assets/209895/8105915/2c0908ac-100b-11e5-9955-cd3926173774.png)

**Comment by andreasn** [comment]
I can't understand were it's coming from though, since the div is empty in index.html
https://github.com/cockpit-project/cockpit/blob/7829ef2dfddea8c26e54b133d1853361814f59d2/pkg/shell/index.html#L24

**Comment by andreasn** [comment]
Is it that $NAME falls back on Cockpit?

**Comment by stefwalter** [comment]
You need to set the string "none" as content in the css I think. Like this:

```
content: "none";
```

**Comment by andreasn** [comment]
Now it says "none" over the title on Firefox instead.
![screenshot from 2015-06-15 12-01-44](https://cloud.githubusercontent.com/assets/209895/8159330/912bd770-1333-11e5-8c0b-aa9d19abe31c.png)

**Comment by andreasn** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/content indicates that Firefox likes:
''' content: none; '''
better

**Comment by andreasn** [comment]
http://www.w3.org/wiki/CSS/Properties/content also documents it as without the quotes. Is this browser-specific? :/

**Comment by andreasn** [comment]
After a bit of testing, it seems none, without the quotes is the one that bites on both Chrome and Firefox. http://pastebin.com/VWZzAaGf
