### ISSUE TITLE
Ability to enable and disable repositories for Subscriptions

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2421]
I was asked for this by a colleague at the Stockholm office.
Seems like a fairly common use case.

**Comment by stefwalter** [comment]
I think we said we'd wait for a DBus API from subscription manager before implementing any further features there. It's hard enough as it is to be screenscaping the commandline for the few things that we do.

**Comment by johnsimcall** [comment]
ping:

Any progress on this issue?  I see from [1] that some basic DBus objects are available, but apparently nothing as it relates to repository management.  :cry: 

[1] - https://www.candlepinproject.org/docs/subscription-manager/dbus_objects.html

**Comment by martinpitt** [comment]
These days, the Cockpit subscription manager page is being maintained by the [Candlepin](https://github.com/candlepin/subscription-manager) project, so I'm closing this.
