### ISSUE TITLE
DBus "owner" support is not backwards compatible

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2424]
The DBus "owner" support breaks connecting from older versions to newer versions. When it sees an ```owner``` message, cockpit.js aborts the connection with a ```protocol-error```.

Perhaps this is unavoidable. But at a minimum we should fix ```cockpit.js``` DBus code to avoid this in the future and only ignore unknown messages? Or should we warn?

**Comment by stefwalter** [comment]
It seems like we would need to reneg on our compatibility promise and say you can connect from a newer version of cockpit to an older, but not the other way around. At least for now.

**Comment by petervo** [comment]
I'll open a pull PR to make this not error. We also broke compatibility though with superuser try.

**Comment by petervo** [comment]
Superuser try, breaks in the opposite way. Newer to older is broken older to newer works. So we really are broken both ways ATM.

**Comment by petervo** [comment]
Removed my comments that were wrong, my testing setup was just non standard. The PR still fixes these types of issues going forward but not sure what we can do about current versions.

**Comment by petervo** [comment]
This was fixed by #2425. Users who run into this will need to upgrade
