### ISSUE TITLE
Add .cockpitrc command file

### ISSUE THREAD

**Issue by adriansev** [cockpit-project/cockpit#2426]
Hi! so this is based on working with cockpit-0.27-4.fc21.x86_64 and it would be great if these features
could be added: 
1. Is it possible that for management of machines to add custom ports for connections (like in a gateway forwarded port to the managed machine)? (i tried with host:port but it did not worked out)
2. is it possible to add for host connection a number of pre-commands (like a fwknop + ssh tunnel)
3. would be great if for a host definition the connection type could be ssh (to create the tunnel auto-magically) and with an attribute/field for sudo (connection to a custom user with sudo rights for systemd and/or root - just to not ave a direct connection to root)
Would these make sense? (for anyone else other than me :) )
Thank you!
Adrian

**Comment by cclements** [comment]
Being able to simply select a non-standard ssh port would help me.

**Comment by michaelwemoto** [comment]
+1
custom SSH ports would be very helpful.

**Comment by stefwalter** [comment]
>  1. Is it possible that for management of machines to add custom ports for connections (like in a gateway forwarded port to the managed machine)? (i tried with host:port but it did not worked out)

I think if implemented properly (the UI would be typing host:port in the server dialog) ... this could work well. Are you interested in implementing this? The port would become part of the machine address and part of the "host" parameter used throughout Cockpit.

> 2. is it possible to add for host connection a number of pre-commands (like a fwknop + ssh tunnel)

This would be a bit more tricky. But if done right, I don't think we'd be against such a contribution. Keep in mind that the ssh tunnel is not created via the 'ssh' command on the client side. We use libssh.

>  3. would be great if for a host definition the connection type could be ssh (to create the tunnel auto-magically) and with an attribute/field for sudo (connection to a custom user with sudo rights for systemd and/or root - just to not ave a direct connection to root)

This one already exists, we automatically sudo to root for privileged operations if possible.

**Comment by stefwalter** [comment]
Ports have been added.

We really do need a .cockpitrc file in the home directory that we execute when logging in. That could perform such command actions.

**Comment by adriansev** [comment]
great! and thanks! i think that the customization of connection (+ commands) could be done if
.ssh/config is used .. unfortunately i did not have time to look on this so far but i found that with libssh 
it is possible with 
int ssh_options_parse_config ( ssh_session session, const char * filename )
http://api.libssh.org/master/group__libssh__session.html#ga82371e723260c7572ea061edecc2e9f1

Thank you!
Adrian

**Comment by martinpitt** [comment]
> is it possible to add for host connection a number of pre-commands (like a fwknop + ssh tunnel)

I agree, this should parse/use ~/.ssh/config. I wouldn't be very happy about a ~/.cockpitrc (or ~/.config/cockpit/ in modern parlor), that's not in the spirit of the project.

Either way, this isn't really a starter task and requires comparatively much discussion and design, so dropping that label.

**Comment by martinpitt** [comment]
cockpit-ssh now does parse the ssh config, which is a much better place to configure custom ports than some cockpit specific config file.
