### ISSUE TITLE
time on the System page doesn't reflect timedatectl commands (right away)

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2433]
If I change the hostname with hostnamectl from the CLI, it's immediately reflected in Cockpit in the System page.
However, if change the time with timedatectl from the CLI, it doesn't bite on Cockpit until I log out and log in again.
@fridex any idea what could be wrong here?

**Comment by stefwalter** [comment]
timedated doesn't send out events when the time changes. In order to do this, we would need to listen with ```timerfd()``` ... in a new channel type. See http://www.freedesktop.org/wiki/Software/systemd/timedated/

**Comment by martinpitt** [comment]
This is still a current issue. Unfortunately there is no `PropertiesChanged` signal when this happens.

**Comment by KKoukiou** [comment]
Does this make sense to solve or can we close it? I guess people don't configure their server time manually usually anyway.
@marusak what do you think?

**Comment by marusak** [comment]
I think without this we go against Cockpit being integrated. That if something happens on system that it does not happen in Cockpit. I would like it to get fixed if possible.

**Comment by martinpitt** [comment]
No progress on this in 7 years, it's really difficult to fix, and a corner case. Let's just give up on this, we have enough more important bugs to work on.
