### ISSUE TITLE
Machine switching does not always work

### ISSUE THREAD

**Issue by maweki** [cockpit-project/cockpit#2439]
I am on a Fedora 22 machine and I have a remote Fedora 22 machine and a Raspberry Pi with Pidora 20 all running Cockpit (the former two the repo-version and the latter the latest tagged version from github).

From my main machine I have added all those machines. If I go to "system" I can switch between any of those machines. If I now switch to the pi or the remote machine and go to "Network" or "Storage" I see the Network/Storage of my main machine (even though the menu and the url is the correct remote machine). I can't switch to the corresponding menu on the remote machine without reloading the page.

Edit: I can make a video, if this is neccessary.

**Comment by petervo** [comment]
Machine navigation was changed fairly recently, can you using the latest tagged version in github on your main machine, the one that the other machines are added to and let us know if you are still seeing the same issue.

**Comment by stefwalter** [comment]
Haven't heard back in 5 months, so closing this issue.
