### ISSUE TITLE
Dashboard: Avatars cannot be changed

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2441]
I had an avatar for a server that I had set via another client. I wanted to change the color of the server, but when doing so, it lost the avatar. Since I'm not on that client right now, I can change it back, so that makes it slightly more irritating :)

**Comment by stefwalter** [comment]
Does this still happen?

**Comment by martinpitt** [comment]
Actually avatars cannot be changed at all right now. Click on a host's pencil button, then click on the avatar icon, select some icon (I tried /usr/share/pixmaps/system-logo-white.png and /usr/share/calibre/images/swap.png), and it's just ignored; the dialog doesn't update, nor does the icon in the dashboard.

This was also reported downstream at https://bugzilla.redhat.com/show_bug.cgi?id=1534963

**Comment by riker09** [comment]
I had the same issue. I cannot add or change the default avatar of any servers. This is the error the browser debug tool console gives me:

```
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf data:image/jpeg;base64,/9j/4AAQSkZJRgABA… blockiert ("default-src").
```

**Comment by marusak** [comment]
Indeed, this is due to `Content-Security-Policy`. I just wonder if this feature is needed or it was just `nice to have`. Seems it was not working for more than 4 years now.
Could we just show one default icon for all?

**Comment by martinpitt** [comment]
Agreed, let's just drop the Avatar feature. I'd rather not weaken our CSP just for that.

**Comment by martinpitt** [comment]
Actually, no -- our machines.d json doesn't refer to an external file, it just uses a `data:image/png` image. That actually seems fine to support?

**Comment by martinpitt** [comment]
I just tried that with Firefox, and a custom avatar of my external server works. I tried to log out, restart cockpit.service, and it's still there. @marusak, what precise C-S-P error do you see?

**Comment by marusak** [comment]
Ha, nice!
I remember I tested this a few months ago and it was failing (pretty much as described by @martinpitt and @riker09 ) but I haven't tested it today because I don't recall we did any changes which could affect this. But it seems we did (or possibly new browser?) but it works for me as well today. Nice :)
