### ISSUE TITLE
Administrator Accounts: last login doesn't match server page time

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2443]
On the server page I see "2015-06-24 16:20"
On the individual user page under Administrator Accounts I see "6/24/2015, 3:48:02 PM"

These should probably match up.

**Comment by mvollmer** [comment]
Confirmed, the Accounts page always shows UTC.

**Comment by marusak** [comment]
They show the same time for me, only difference is the format.
On system overview `2019-10-21 10:43`
On accounts page `10/21/2019, 10:43:40 AM`
This is tracked on https://github.com/cockpit-project/cockpit/issues/8583

@mvollmer said:
> Confirmed, the Accounts page always shows UTC.

I am not UTC. Can you still reproduce it?
