### ISSUE TITLE
Cockpit fails if run in Container

### ISSUE THREAD

**Issue by autarchprinceps** [cockpit-project/cockpit#2447]
If I run Cockpit in a container, it fails with a modal dialog.
![image](https://cloud.githubusercontent.com/assets/239063/8354725/730c40a8-1b4a-11e5-941f-2226f6b2eb35.png)

I believe, after looking throught the logs, that this error message belongs to my problem: cockpit-bridge[30733]: g_hash_table_unref: assertion 'hash_table != NULL' failed

I know not all of Cockpits features can be used in a container, but it would be nice to be able to use those that can be used. As context information: I am trying to run cockpit in a Vserver which turns out to be a container (Virtuozzo I think).

**Comment by autarchprinceps** [comment]
I'm running cockpit 0.58.2.el7 on CentOS 7.1.1503

**Comment by stefwalter** [comment]
Could you describe where you got the container from? What command did you use to run the container?

**Comment by autarchprinceps** [comment]
It's a Strato Vserver, so I didn't run the container myself. It's definitively a OpenVZ container. Most hosters use Virtuozzo, I'm reasonably certain that's the case here as well.

**Comment by stefwalter** [comment]
Is there further information in the logs, besides the hash table unref problem (above)?

**Comment by autarchprinceps** [comment]
The only other things in the log are not problematic. Just successful login and standard "using certificate ..." lines, but they are mostly from cockpit-ws and not cockpit-bridge anyway.

**Comment by stefwalter** [comment]
Is systemd running inside the container? Nobody has done work yet on making cockpit work without systemd. The basic architecture shouldn't care much (probably a few patches necessary here), but lots of the UI code uses systemd APIs (so lots of alternate components necessary).

**Comment by autarchprinceps** [comment]
Systemd is used, since it's CentOS 7

**Comment by stefwalter** [comment]
I believe this issue has since been fixed.
