### ISSUE TITLE
cockpit-session has no effect on "w", but cockpit-accounts uses "w".

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#2451]
Sessions established by cockpit-session don't show up in the "w" output but cockpit-accounts uses "w" to check whether someone is logged in or not.  Thus, we miss our own sessions.

**Comment by mvollmer** [comment]
cockpit-accounts should probably talk to logind via D-Bus for session stuff.

**Comment by dperpeet** [comment]
Since the displayed info isn't correct, I'd consider this to be a bug.

**Comment by stefwalter** [comment]
In addition, I wonder if we should hook things up so we do actually have a tty on which we receive system messages broadcast to all users.

**Comment by martinpitt** [comment]
This has been fixed long ago:
```
❱❱ w
 09:17:31 up  1:58,  1 user,  load average: 0,25, 0,39, 0,48
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
martin   web cons  09:17    0.00s  0.00s  0.03s /usr/libexec/cockpit-session localhost
```
