### ISSUE TITLE
"Permission denied" when running instructions from README.md

### ISSUE THREAD

**Issue by yevmel** [cockpit-project/cockpit#2457]
the section "Debug logging of Cockpit processes" of the README.md suggests tu run following command: 

    sudo printf "[Service]\nEnvironment=G_MESSAGES_DEBUG=cockpit-ws,cockpit-wrapper,cockpit-bridge\nUser=root\nGroup=\n" > /etc/systemd/system/cockpit.service.d/debug.conf

it results in `Permission denied` because `sudo` only affects the left-hand side of the instruction.

**Comment by yevmel** [comment]
Oops, i ment HACKING.md

**Comment by stefwalter** [comment]
Thanks for the patch. Merged into git master.
