### ISSUE TITLE
Show TTY broadcast messages

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2468]
When you're at a terminal and someone does `shutdown` you see a message in the other terminals. What do you think about making that show up in the Patternfly messages area (that we currently don't use).

@andreasn CC

**Comment by stefwalter** [comment]
@dperpeet This would fix #2451 as a side effect.

**Comment by dperpeet** [comment]
I think that would be valuable information to have! Did you mean the [Patternfly Info Tip](https://www.patternfly.org/widgets/#info-tip)?

**Comment by stefwalter** [comment]
> I think that would be valuable information to have! Did you mean the Patternfly Info Tip?

Yup.

**Comment by andreasn** [comment]
Yeah, that would be great.
Info tips sounds good. Doesn't get in the way. I'll whip up a quick mockup.

**Comment by andreasn** [comment]
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/notifications/notification-poweroff.png)

**Comment by stefwalter** [comment]
How should this be modeled? Perhaps a channel which drains a buffer?

**Comment by marusak** [comment]
Also see https://github.com/cockpit-project/cockpit/issues/1153

**Comment by martinpitt** [comment]
PR #16885 introduced showing scheduled shutdowns on the Overview page, which is by far the most common case of this. Implementing a generic TTY console listener is a lot more overhead, for a technology that's hardly being used any more, so not worth it IMHO.
