### ISSUE TITLE
units displayed over values in graph

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#2491]
It seems that in my default resolution, at the first page it caused, that units Mbps are not well formatted, see attached image (browser is firefox browser, F21). 

![cockpit-units](https://cloud.githubusercontent.com/assets/8735467/8697579/6d0512d2-2af6-11e5-93e7-47c48e0259d4.png)

**Comment by andreasn** [comment]
The fonts look a bit big, so I wonder if there is a weird overflow when Mbps realizes it actually doesn't have space and has to clip, due to the bigger font-size. Some kind of text-overflow rule needs to happen here I think.

**Comment by mvollmer** [comment]
Fixed.
