### ISSUE TITLE
newusers: unrecognized option

### ISSUE THREAD

**Issue by Vosky** [cockpit-project/cockpit#2495]
Hi,

I have an error in journalctl when I try to add a new server :
cockpit-ws[21118]: /usr/sbin/newusers: unrecognized option '--crypt-method=NONE'
cockpit-ws[21118]: Usage: newusers [options]
cockpit-ws[21118]: Options:
cockpit-ws[21118]: -h, --help                    display this help message and exit
cockpit-ws[21118]: -r, --system                  create system accounts
cockpit-ws[21118]: -R, --root CHROOT_DIR         directory to chroot into

OS : Arch Linux
Cockpit version : 0.65

Vosky

**Comment by dperpeet** [comment]
@petervo did you come across this when working on authentication?

**Comment by petervo** [comment]
@dperpeet no, this is part of cockpitdbussetup not what i'm working on, that part of the code hasn't been touched in a long time. i don't have an arch system to test.

**Comment by Vosky** [comment]
Is there a way to add server manually ?
Like create user on the new server and generate SSH key.

**Comment by mvollmer** [comment]
This also happens on Debian.

**Comment by mvollmer** [comment]
Should be fixed by https://github.com/cockpit-project/cockpit/commit/e0b3a846081734e2d7efe757254a4f7d4a20da9b
