### ISSUE TITLE
Enhancement : Add a option to autostart container in boot time.

### ISSUE THREAD

**Issue by williamjmorenor** [cockpit-project/cockpit#2496]
Looking at the docker container interface there is not option to mark a docker container to autostart, it could be a nice feature to add this option to cockpit, for example will nice if after to shutdown a server, physical or virtual, or even a Atomic Host, cockpir start the containers at boot time without need to log into cockpit to start the services by hand.

**Comment by andreasn** [comment]
Does this more technically mean creating a systemd service and enabling that?

**Comment by petervo** [comment]
Kubernetes is probably the preferred way of ensuring containers are running on restart. But without it a systemd service is probably the best option.

**Comment by stefwalter** [comment]
Docker has a native always restart option. We should support it. It's a simple change to make.

**Comment by petervo** [comment]
I think the catch is that if the container is manually stopped then it will not be restarted on boot. Maybe that's what we'd want though.

**Comment by williamjmorenor** [comment]
From a user point of view it will be hard to remember which containers will start on boot and which not if the restart feature if defined by if the container was running or not before to shutdown the server, it will be nice to have a option to mark the container to autostart so the user can choose which container autostart and which not, these way user will have control about what services will be served by default. Any to know than services than were running before shutdown will restart again in boot is always a great feature.

**Comment by williamjmorenor** [comment]
Desing if not my best, sorry

![rect3444](https://cloud.githubusercontent.com/assets/3522386/8730144/66561d12-2bac-11e5-8d5c-a119a6f0c075.png)

**Comment by dperpeet** [comment]
I think we can place this in the run dialog. [Docker documentation](https://docs.docker.com/reference/api/docker_remote_api_v1.14/) calls it `RestartPolicy`. We have the options:
* disabled (default)
* `always`
* `on-failure` (with `MaximumRetryCount`)

@andreasn I don't think we need a mockup / wiki page for this. It seems pretty straightforward. It aligns well with the current run dialog with its checkboxes to enable a configuration subset.

**Comment by williamjmorenor** [comment]
This sound good if a want to create a container with a database server than I want to link with other containers, so will be nice if the container restart always on boot and serve the database to others.

But will be nice to have the opción to set a existing container to autostart, the user case can be:

I create a container to test a update before to go to production, I restore a backup with my data, run test and if always look fine I want to set this container to autostart but I did mark this option when a I run the container the first time, Will I nedd to create a new container and make all the job again?

**Comment by dperpeet** [comment]
As far as I can tell from looking at the [docker remote api v1.19](https://docs.docker.com/reference/api/docker_remote_api_v1.19/), `RestartPolicy` can only be set during container creation. When using the CLI, I'm sure it also only works with `docker run`, not once the container is already up and running.

@williamjmorenor While the use case is interesting, are you aware of a way to change the setting after the container was created? If not, you might be well served to file an issue with docker.

**Comment by stefwalter** [comment]
Implemented now that #4172 is merged.

**Comment by williamjmorenor** [comment]
Thanks !
