### ISSUE TITLE
unable to log in to domain if password renewal is needed

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2501]
1. Create a user 'rupert' in FreeIPA
2. Give 'rupert' a password
3. Take a machine and join the FreeIPA domain
4. Try to log in with 'rupert' on the machine you joined to the domain
5. It fails, because you need to update the password.

Logging in with the same user in the terminal works, or via GDM works, since it will ask for a new password there.

**Comment by andreasn** [comment]
Would probably look very similar to
https://github.com/cockpit-project/cockpit/pull/2062#issuecomment-115703181

**Comment by martinpitt** [comment]
This got fixed in PR #2062, I just validated this on current master.
