### ISSUE TITLE
domain dialog text too close to text

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2504]
![screenshot from 2015-07-21 15-10-44](https://cloud.githubusercontent.com/assets/209895/8801419/c12480aa-2fba-11e5-8bdd-f343493ac024.png)

**Comment by andreasn** [comment]
to spinner

**Comment by stefwalter** [comment]
This should use the standard dialog pattern code in patterns.js, which would solve this issue.

**Comment by andreasn** [comment]
![screenshot from 2015-11-27 14-26-34](https://cloud.githubusercontent.com/assets/209895/11442165/528e3be0-9513-11e5-8eb3-4b0655a2bea6.png)

Dialog after the fix.

**Comment by andreasn** [comment]
> This should use the standard dialog pattern code in patterns.js, which would solve this issue.

Does this mean the whole dialog have to be rebuilt?
