### ISSUE TITLE
Network Configuration: IP range

### ISSUE THREAD

**Issue by qooob** [cockpit-project/cockpit#2509]
It used to be possible on CentOS to setup IP ranges, where you could put in `/etc/sysconfig/network-scripts/ifcfg-eth0-range0` file to set up IP range.

Is this still possible in Fedora and can Cockpit manage it?

**Comment by andreasn** [comment]
I'm not too familiar with this feature, is it the same that's described here?
http://www.ducea.com/2006/07/15/linux-tips-how-to-quickly-bind-a-range-of-ips-on-redhat-based-systems/

**Comment by qooob** [comment]
Yes. All I could do to work around the problem (only half way), is to add IP one by one in separate file, like: `ifcfg-eth0:1, ifcfg-eth0:2, ifcfg-eth0:3, ifcfg-eth0:4, ifcfg-eth0:5, ifcfg-eth0:6 ...`. Cockpit can see and read the configuration exampled above BUT when you click SAVE button Cockpit DELETES all of those `ifcfg-eth0:X` files and leaves only one `ifcfg-eth0` with IP's listed like:

```
IPADDR1=1.2.3.4
PREFIX1=29
IPADDR2=1.2.3.5
PREFIX2=29
IPADDR3=1.2.3.6
PREFIX3=29
```

This is *highly undesirable*. Cockpit should try to keep the patterns set by user or at least make an option for doing so. If Cockpit will read `-range0, -range1, -range2` files even better.

Now, all I could do to prevent accidental undesirable change happen is to immune network scripts conf files.

https://github.com/webmin/webmin/issues/238#issuecomment-125088017

**Comment by petervo** [comment]
Cockpit uses network manager to manage network configuration. Cockpit doesn't delete configuration files directly. If that's happening I'd recommend filing a bug with them.

**Comment by qooob** [comment]
I think it would worth more if you do it on behalf of Cockpit. You can check/confirm your-self of what I'm talking about.

**Comment by andreasn** [comment]
Ah, so Cockpit (or more likely Network Manager) doesn't respect the old configuration?
What happens if you edit the connection with nmcli or nmtui instead? Does the same problem still occur?

**Comment by qooob** [comment]
Yeah, guys, you better not mess with the person with such avatar!! :+1:

**Comment by stefwalter** [comment]
Cockpit doesn't support network-scripts. Nobody has built a UI to support them. We simply support NetworkManager. NetworkManager's interaction with network-scripts should be discussed with the NetworkManager project.
