### ISSUE TITLE
The /fswatch/simple test fails

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2540]
This happens when running the check in brew. It's the only test that fails. It hangs forever unless we add the 025f85f6d6ae817bf43211e68bada1813df644ea timeout fix to the test.

```
FAIL: test-fs 17 /fswatch/simple
```

**Comment by stefwalter** [comment]
@mvollmer I wonder what kind of guarantee we have that the event will arrive after we've opened the channel? What if GFileMonitor delays opening internally?

**Comment by stefwalter** [comment]
This only fails on F23 during testing. This is the GFileMonitor regression bug.

**Comment by stefwalter** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1225957

**Comment by mvollmer** [comment]
> This only fails on F23 during testing. This is the GFileMonitor regression bug.

Ahh, make sense, of course.

**Comment by stefwalter** [comment]
Patch landed upstream.
