### ISSUE TITLE
kubernetes: Add a vertical scrollbar that appears when too much info

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2542]
We should add a vertical scrollbar to the details pane when too much information is present.

![screenshot from 2015-08-05 16-32-08](https://cloud.githubusercontent.com/assets/795070/9088284/85e4661e-3b8f-11e5-9709-5fb4a23aa375.png)

CC @sub-mod

**Comment by marusak** [comment]
cockpit-kubernetes is in maintenance mode. Also this was not implemented in almost 4 years, probably won't happen now.
