### ISSUE TITLE
"multipathed devices" displayed as if they are seperate devices

### ISSUE THREAD

**Issue by trgill** [cockpit-project/cockpit#2554]
When there are multiple paths to the same "multipathed device" - they are displayed as if they are different devices.

I think the "create volume" and "create RAID" windows should use the unique ID of a device to determine if they are the same device. It should only list the device once with an indicator that there are multiple paths to the same device.  (provide a list of the paths?)

multipath is very common in enterprise environments.

![raid_device_multipath](https://cloud.githubusercontent.com/assets/13203542/9183506/6d4ef492-3f7d-11e5-8992-06a4823acfd1.png)
![volume_group_multipath](https://cloud.githubusercontent.com/assets/13203542/9183509/71d7ac5c-3f7d-11e5-8c1c-fe3b90329f74.png)

**Comment by stefwalter** [comment]
@phatina FYI

**Comment by mvollmer** [comment]
Yes, I know that there is a thing called multipath, but I don't understand it well enough.  I'll catch up.

**Comment by mvollmer** [comment]
> I think the "create volume" and "create RAID" windows should use the unique ID of a device to determine if they are the same device. It should only list the device once with an indicator that there are multiple paths to the same device. (provide a list of the paths?)

What are the `/dev/mapper/...` entries in the list?

Isn't it so that with multipath, you get a new block device that will 'bond' a number of existing block devices together, and you are then supposed to use that new block device instead of the old ones?

E.g, in your example, we would need to hide all the `/dev/sd*` entries and somehow figure out that /dev/mapper/<id> refers to one of the NETAPP drives.  Correct?

**Comment by trgill** [comment]
Yes, the  /dev/mapper/... entries are like containers for the underlying paths.  In this case there are two paths, but there can be many.  When multipath is enabled an application doing IO to the /dev/mapper/xxx  device gets fault tolerance and load balancing across the paths.

I think Cockpit has the data to figure out when there are multiple paths.  The attached display knows that /dev/sde and /dev/sdc point to the same device. 

Could you group the /dev/sd* entries together when they have the same WWN or Serial number?  I think that would be better. 

Grouping them under the correct /dev/mapper/xxx device would be ideal, but I'm not sure how you'd get that data to make the connection.

![netapp_lun](https://cloud.githubusercontent.com/assets/13203542/9204425/402f0764-402b-11e5-86cf-42e2f14b567a.png)

**Comment by mvollmer** [comment]
> Grouping them under the correct /dev/mapper/xxx device would be ideal, but I'm not sure how you'd get that data to make the connection.

Let's say we group /dev/sdf and /dev/sdi, and the user selects that entry as a physical volume for a new volume group, how should we create the volume group?  Which of the block devices should we pass to `vgvreate`?  Isn't the only proper way to find the right /dev/mapper/ entry and pass that to `vgcreate`?


In general, I have to admit that I have ignored the possibility of multi path when writing the Cockpit code until now.  Storaged/UDisks2 have some understanding of it, but Cockpit will likely show odd behavior with multipath devices.  I'll plan to get multipath right soonish, starting within a weeks time or so.

**Comment by trgill** [comment]
> Let's say we group /dev/sdf and /dev/sdi, and the user selects that entry as a physical volume for a new volume group, how should we create the volume group? Which of the block devices should we pass to vgvreate? Isn't the only proper way to find the right /dev/mapper/ entry and pass that to vgcreate?

Yes, you are right.  We will need to figure out a way to get the mappings to you.

Looks like we should also add a filter to the lvm.conf file so that the /dev/sdx devices don't get scanned by the LVM.

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/DM_Multipath/multipath_logical_volumes.html

**Comment by trgill** [comment]
I think you'll know how to do this better, but something along the lines of this would be good.  The serial number/WWN from the /dev/mapper/xxx will match the /dev/sdxx values to group then together.

You are right - we should send all commands down /dev/mapper/xxx.

![proposed_multipath](https://cloud.githubusercontent.com/assets/13203542/9280487/9ed47a0c-428c-11e5-8dbd-d0a4b257a23c.png)

**Comment by mvollmer** [comment]
I have some code now in #2596, please check it out.
