### ISSUE TITLE
ssh tunnel blank page

### ISSUE THREAD

**Issue by TonyBostonTB** [cockpit-project/cockpit#2556]
when connecting to cockpit via ssh tunnel, I can login but after logging in, I get a blank page.

'GET https://localhost:4444/socket [HTTP/1.1 101 Switching Protocols 367ms]'

![bildschirmfoto 2015-08-11 um 09 32 15](https://cloud.githubusercontent.com/assets/8842338/9192495/e6ec27b4-400b-11e5-91a6-3de01b6005f5.png)

**Comment by stefwalter** [comment]
Could you file a full reproducer? Or alternatively provide a patch to fix the issue?

**Comment by AndreasMuellerDD** [comment]
more screenshots for a better understanding

![bildschirmfoto 2015-08-11 um 10 04 18](https://cloud.githubusercontent.com/assets/8842338/9193013/6d3ef8ba-4010-11e5-85a9-f963c7794753.png)

after logging in

![bildschirmfoto 2015-08-11 um 10 05 33](https://cloud.githubusercontent.com/assets/8842338/9193032/8d32027a-4010-11e5-89d1-dea9546980d6.png)

**Comment by stefwalter** [comment]
How did you set up your tunnel? Can you reproduce this on a single machine, and provide instructions for doing so?

**Comment by AndreasMuellerDD** [comment]
connection via ssh tunnel as follows:

ssh -p 55533 -fCN user@host.ddns.net -L 4444:192.168.222.100:9090

I'll try that at home when I get there later

**Comment by stefwalter** [comment]
This example works fine for me:

```
ssh -fCN localhost -L:9999:localhost:9090
```

I can access Cockpit on port 9999 fine. If you do discover the source of the issues you were encountering, we'd be happy to include any fixes to both the code or documentation that you have to contribute.
