### ISSUE TITLE
nothing displayed in Drives-Info-List on Storage-Tab 

### ISSUE THREAD

**Issue by TonyBostonTB** [cockpit-project/cockpit#2560]
I added an LVM Volume Group with two Drives.
Now the Drives-Info shows two extra Drives with no info in it. See screenshot below
![bildschirmfoto 2015-08-10 um 15 45 46](https://cloud.githubusercontent.com/assets/8842338/9196391/4cbf7c34-402b-11e5-9dc6-0212da23699e.png)

**Comment by mvollmer** [comment]
I can't unfortunately reproduce this...
