### ISSUE TITLE
journalctl: terminates despite -f flag when there are no matching entries

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2571]
We see this in our test output:

```
Unexpected journal message '-- No entries --'
```

**Comment by stefwalter** [comment]
May be coming from here?

https://github.com/systemd/systemd/blob/master/src/shared/logs-show.c#L45

**Comment by stefwalter** [comment]
From @mvollmer: 

journalctl --follow will exit immediately if there are initially no matching entries.  Instead, it should block until a matching entry is appended to the journal.

Example: If you have a new service unit that has never been started, the following will not give the expected result:

**Comment by dperpeet** [comment]
> Example: If you have a new service unit that has never been started, the following will not give the expected result.
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=1253649

this is a separate issue

**Comment by stefwalter** [comment]
@mvollmer @dperpeet So Cockpit is still broken until upstream https://bugzilla.redhat.com/show_bug.cgi?id=1253649 is fixed

**Comment by stefwalter** [comment]
Posted patch to systemd upstream: https://github.com/systemd/systemd/pull/958

**Comment by stefwalter** [comment]
Patch merged up stream

**Comment by stefwalter** [comment]
Fixed in Fedora 23
