### ISSUE TITLE
tarball distribution on github for (pre-)releases

### ISSUE THREAD

**Issue by tgurr** [cockpit-project/cockpit#2597]
Not a bug in the software itself, but the constant hopping between tar.gz and tar.bz2 for (pre-)releases is a minor annoyance for packagers. It would be nice if there could be a consensus between the involved people doing the releases.

**Comment by petervo** [comment]
Sorry about that, github stopped accepting tar.bz2 briefly and that's why there are a few gz's. Hopefully from here on we should be able to stick to tar.bz2.

**Comment by stefwalter** [comment]
@tgurr I uploaded the bz2 tarballs where they were missing.
