### ISSUE TITLE
Unify partitions, logical volumes, and raid re filesystem creation, maybe.

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#26]
Partitions are created and formatted with one operation, while logical volumes are created in a separate step from formatting them.

Formatting needs many parameters, but partition creation only needs the size, so it made sense to put them into one dialog. (I think I copied that from GNOME Disks.)

Logical volume creation might be complex in terms of UI, just like raid creation, so it is probably better off as a seperate step from formatting, which is also complex.

To unify this, we might separate partition creation from formatting; or we might combine lv/raid creation and formatting and just pay attention that we have a manageable UI for this complex task (similar to Anaconda, maybe).

**Comment by mvollmer** [comment]
This is too vague.
