### ISSUE TITLE
Display VM address in vm-run

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2667]
The vm-run now makes you guess at the address and when the machine is ready. This is a regression from when we stopped producing console output from the VMs.

**Comment by dperpeet** [comment]
Instead of waiting for the machine to get an ip, vm-run is now interactive (via `virsh console`) right from the bootloader. In my opinion, this is an improvement. Do we need a non-interactive mode that doesn't display anything and just waits for an ip address?

**Comment by dperpeet** [comment]
Unless there's actual need for another mode, we can just keep this the way it currently is.
