### ISSUE TITLE
Support for Debian/Ubuntu?

### ISSUE THREAD

**Issue by karibuTW** [cockpit-project/cockpit#2671]
Hi there,

That's a great project out there! 
Nice web interface, well integrated, with great tools.

However to install on Debian or Ubuntu is quite tedious.

I've managed to do it on my Virtual Machine and I wrote an article as usual.
You can find it here:
http://freedif.org/cockpit-administer-your-server-via-a-web-browser/

But there are still many features not working such as:
- Shutdown/Restart do not work (Error: Not found)
- Storage (Not the storaged API)
- Networking tab is empty
- Subscriptions not available

May be those are easy to fix.

And also it tooks me quite some time to do it haha.
Any plan to improve the support for Debian/Ubuntu in the near future?

Thank you guys!

**Comment by andreasn** [comment]
With regards to Subscriptions, as far as I'm aware, that's a concept that isn't available on neither Ubuntu or Debian. Do you get an error or something else?

**Comment by andreasn** [comment]
For the Shutdown/Restart. Does your system use systemd?

**Comment by karibuTW** [comment]
I'm using Debian 8, so systemd should be the default init but I need to double check if it is well configured tho

**Comment by stefwalter** [comment]
> Shutdown/Restart do not work (Error: Not found)

If you have systemd installed, then this is probably a bug. Worth filing a bug separately and digging into this.

> Storage (Not the storaged API)

Solution here is to package storaged.

> Networking tab is empty

The networking tab uses NetworkManager. The solution here is to either use NetworkManager on the server, or for interested contributors to contribute a non NetworkManager networking UI tab. The components are pluggable exactly for this reason, that different implementations can be used on different operating systems, where necessary.

> Subscriptions not available

This should likely not be installed on Debian, if it doesn't make sense there.

>  Any plan to improve the support for Debian/Ubuntu in the near future?

I think that's a great goal. But it would only happen with contributions and interested people getting involved. So far none of the core contributors use Debian day to day, but that could change :)

**Comment by stefwalter** [comment]
@karibuTW By the way, if you build from a tarball, you won't need to have nodejs, npm or phantomjs as a build dependency:

https://github.com/cockpit-project/cockpit/releases

**Comment by stefwalter** [comment]
@karibuTW Is it okay if I close this issue? Could you file bug reports for the separate issues that you find running on Ubuntu? It'd be much easier to track them individually. Some of them are easy to fix, some are bugs, others would require significant contribution to the project.

**Comment by karibuTW** [comment]
Thanks Stefwalter,

I'll dig into it and file bug reports if I cannot  go around as you suggested.

Thanks
