### ISSUE TITLE
Get list of supported filesystem types from lower level.

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#27]
Right now, the list is hard coded. It should be configurable.

In the extreme, we might offer support for discovering packages that would add more filesystem types, pretty much like totem can go looking for video codec packages.

**Comment by mvollmer** [comment]
Needed API issue: https://github.com/storaged-project/storaged/issues/38

**Comment by mvollmer** [comment]
Fixed by #4851
