### ISSUE TITLE
Page titles should reflect the page we're on

### ISSUE THREAD

**Issue by nekohayo** [cockpit-project/cockpit#2715]
Most pages only list the hostname in the title ("kusanagi"), instead of doing something like "kusanagi — Networking", which means it's currently not terribly helpful for page history/navigation:

![cockpit redundant title](https://cloud.githubusercontent.com/assets/479401/9725437/57ba16b0-55b3-11e5-8a6a-eb7ee14ab7b6.png)

**Comment by stefwalter** [comment]
Yes good point. @andreasn Should we add something like this to the design guidelines?

**Comment by stefwalter** [comment]
This is now fixed. The titles say the section name in front of the host name.
