### ISSUE TITLE
Autogenerated self-signed HTTPS certificate is only for localhost

### ISSUE THREAD

**Issue by nekohayo** [cockpit-project/cockpit#2716]
It seems Cockpit autogenerates a certificate for the machine it's running on, but only for "localhost" as the address. So accessing https://localhost:9090 works fine but trying https://thehostname.local:9090 or the machine's publicly accessible name on the net (let's say foobar.dyndns.org) is not possible because you get huge warnings in every browser about the certificate not matching the domain, being only or "localhost".

Wondering if, for those who are not big orgs getting official certs signed by CAs, it would be possible to specify in cockpit's prefs a list of addresses it is expected to be accessed from. I suppose the person viewing it would still get a warning because it would be self-signed, but at least it wouldn't say "it's only for 'localhost' "?

**Comment by stefwalter** [comment]
Yes, we should add the current hostname to the self-signed certificate as a subjectAltName. Good point.

**Comment by stefwalter** [comment]
The certificate now uses the host name as the CN when it generates a new self-signed certificate. I believe this should fix the issue.
