### ISSUE TITLE
different graphs for same machine connected via more adresses (dashboard)

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#2729]
Hi,
I've connected one machine (localhost) via more adresses:
first is localhost, second one is ::1 and third one is 127.0.0.2
It is possible to connect it, it is okay and nice feature.
But I have troubles with graph, 
IPv4 adresses has same graph. but IPv6 adress, has little bit different graph.
It is strange, all three graphs should be same.
What do you think?
      Regards
      Honza
![screenshot from 2015-09-09 17 27 38](https://cloud.githubusercontent.com/assets/8735467/9766366/c5d99934-5718-11e5-9ae1-74e31596ad21.png)

**Comment by stefwalter** [comment]
When you connect twice to the same system (with different addresses) you start two sessions. Each session starts at a different time. 

The specific metric values depend on the exact timing of the measurement. This is true of PCP or any other measurement system. A spike will be flattened if it happens between measurements. Therefore you will see different measurements for the same system when both sessions measure the system at slightly different times.

So this is not a bug.
