### ISSUE TITLE
Update/delete  object  impact on angular view 

### ISSUE THREAD

**Issue by sub-mod** [cockpit-project/cockpit#2737]
seen with https://github.com/cockpit-project/cockpit/pull/2712

@stefwalter 
What should be the behaviour in the topology view when
1)delete button is pressed in the sidepanel. should the side panel close ?

Also,
 adjust button for RC will update the replica count but the updated count is not shown in the sidepanel.

**Comment by stefwalter** [comment]
>  What should be the behaviour in the topology view when
1)delete button is pressed in the sidepanel. should the side panel close ?

I think we should return to the 'no object selected' case. Very good point, that does change my assumptions about the second question:

> Also, adjust button for RC will update the replica count but the updated count is not shown in the sidepanel.

Exactly. We need to figure out whether we want to update items, or just have the controller track them better. In the deletion case it seems like we need to do the latter. Lets think about this, and see what @petervo has to say when he comes online.

**Comment by stefwalter** [comment]
As we discussed, we should:
 * In TopologyCtrl an 'updated' handler to the ```all``` Kubelist
   * Check if last item matches the selected item in scope, and replace if so.
 * Add a ```deleted``` handler
   * Set selected item in scope to null, if handler gets passed same item

**Comment by stefwalter** [comment]
Setting ```$scope.selected = null``` will go back to the legend view.
