### ISSUE TITLE
Pass in kubeconfig file correctly to atomicapp

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2738]
Disable or fail Nulecule in situations where it cannot work:

 * Cockpit is not running on the same host as Kubernetes API server.
 * Running Openshift instead of kubernetes

**Comment by stefwalter** [comment]
@goern Am I understanding this right?

 * If we're accessing kubernetes remotely, then using 'atomic install my/atomicapp' on the local machine cannot work?
 * If kubernetes requires authentication then atomicapp cannot work?

Or does atomicapp somehow respect the local ```~/.kube/config``` and access the right kubernetes server?

**Comment by vpavlin** [comment]
We have this for OpenShift config file. I don't think we use kube config anyhow, but it seems to be an issue we should fix!

**Comment by stefwalter** [comment]
By the way, I see this:

```
cmd failed: /host/usr/bin/kubectl create -f /atomicapp/.workdir/helloapache-app/artifacts/k8s/hello-apache-pod.json --namespace=testo
```

@vpavlin So how do we use the Openshift config file? We currently use a nice ```~/.kube/config``` file to access Openshift. So how do we pass openshift's kubeconfig file to atomicapp ... so that it accesses the right machine, authentication, user, etc...?

**Comment by vpavlin** [comment]
https://github.com/projectatomic/atomicapp/blob/master/docs/providers.md#openshift3

You add `openshiftconfig=/path/to/config` to `answers.conf`

**Comment by stefwalter** [comment]
Awesome. @sub-mod we need to implement this. 

@vpavlin And what about situations where we're using kubernetes and not openshift? The kubeconfig file format is the same ... is there a similar setting that can be added to ```answers.conf```?

**Comment by stefwalter** [comment]
https://trello.com/c/OpExzbDU/198-nulecule-with-openshift

**Comment by vpavlin** [comment]
Nope, not yet, though, as I stated in my first comment - it's a valid issue which should be filed against Atomic App (and kubes provider). I think the logic could be basically copied from openshift provider

https://github.com/projectatomic/atomicapp/blob/master/atomicapp/providers/openshift.py#L58

**Comment by stefwalter** [comment]
Filed: https://github.com/projectatomic/atomicapp/issues/266

**Comment by vpavlin** [comment]
Thanks!

**Comment by stefwalter** [comment]
A user's kubeconfig file is not a single location. kubectl reads from multiple location and combines the data.

@sub-mod: To implement
 1. Expose the combined data we've loaded in KubernetesClient
 2. Write it out to the answers directorty before referring to it from answers.conf

**Comment by sub-mod** [comment]
fixed in https://github.com/cockpit-project/cockpit/pull/2921 and projectatomic/atomicapp#266
