### ISSUE TITLE
Services list could indicate the status with colored dots near the name?

### ISSUE THREAD

**Issue by nekohayo** [cockpit-project/cockpit#2747]
A quick idea for synesthetes: on the left of each service name, there could be a simple unicode bullet • with various colors to indicate at a glance whether a service is active or inactive? Or would that be visually overloading?

**Comment by stefwalter** [comment]
Good Idea. @andreasn and I were talking about how we might refresh that page, and this might be part of it.

**Comment by marusak** [comment]
New design suggested in https://github.com/cockpit-project/cockpit/issues/11846
