### ISSUE TITLE
Some pages don't work with Epiphany Web browser when using subservers

### ISSUE THREAD

**Issue by nekohayo** [cockpit-project/cockpit#2749]
Interesting little issue (maybe because of self-signed certs and Epiphany being quite enforcing in that case?): my test setup is a fresh Centos 7 server with Cockpit, with a Fedora 22 workstation running Cockpit. Fedora's cockpit has been configured to add the Centos server to its dashboard.

If you look at it in Firefox, no problems at all. If you visit the pages in Epiphany however, you will see that all pages except "Services", "Journal" and "Tools > Terminal" will show the global dashboard instead of showing the expected page contents, as the attached screenshot illustrates (Firefox on the left, Epiphany on the right):

![foo](https://cloud.githubusercontent.com/assets/479401/9827003/59b69528-58ac-11e5-876b-cb81d0a30e35.png)

"Jeff, finding corner-case bugs in your apps since '04" ™ ;)

**Comment by stefwalter** [comment]
Could you look for javascript failures in the javascript console? Note that Epiphany is not on our list of browsers ... but I don't think we're against people contributing fixes to change that:

http://cockpit-project.org/running.html

**Comment by petervo** [comment]
This may be related to this test failure in #2690

**Comment by nekohayo** [comment]
@stefwalter there are no cockpit errors, and Epiphany 3.16's inspector doesn't show errors in the console, only a few CSS warnings.

**Comment by stefwalter** [comment]
@nekohayo. Epiphany isn't one of the browsers we've been aiming to support. However if you wish to contribute fixes to make Cockpit work on Epiphany, that would be great.

**Comment by larskarlitski** [comment]
This is quite an old issue and I can't reproduce this with Epiphany on Fedora 30. Cockpit works quite nicely in it. Feel free to reopen if this is still an issue for you.
