### ISSUE TITLE
Cockpit's memory usage graphs includes the cache but makes no distinction

### ISSUE THREAD

**Issue by nekohayo** [cockpit-project/cockpit#2751]
I'm mostly interested in something close to gnome-system-monitor or htop's representation. Currently, Cockpit makes me believe that my server's RAM is full, but in practice half of it seems to be caching:

![foo](https://cloud.githubusercontent.com/assets/479401/9835322/aaeb9b8e-59b3-11e5-827b-f14efb2e9f0c.png)

**Comment by dperpeet** [comment]
We have something like that in the details (click on `Memory`). The question is whether we should show that level of detail in the dashboard or not.
Or we could ignore cached memory in the dashboard overview, to keep it simple.
![2015_sep_memory_use](https://cloud.githubusercontent.com/assets/8711649/9872555/5e9f828e-5b9a-11e5-8ca0-d20d8a2b1900.png)

This needs some design @andreasn.
@mvollmer is currently working on changing the graphs.

**Comment by garrett** [comment]
PRs #10101 and #10282 reworked the memory and its display.

Calculations have been redone, cached RAM has been de-emphesized on the details page and omitted from the overview, and swap has been split out into its own area on the top on both.

(Our design doc is @ https://github.com/cockpit-project/cockpit/wiki/Feature:-Memory-graphs)

As of today, Cockpit's memory reporting now looks like this in overview:

![screenshot of memory in overview](https://user-images.githubusercontent.com/10246/47802404-77084700-dd30-11e8-9a22-67917be68cfe.png)

And like this in details:

![screenshot of memory details](https://user-images.githubusercontent.com/10246/47802394-7374c000-dd30-11e8-96fd-f3434daf09a8.png)

Oh, and we did happen to base the new calculations on https://linuxatemyram.com/ :wink:
