### ISSUE TITLE
Cockpit's measurement of bandwidth in the global "System" page disagrees with the Network page (and every other tool)

### ISSUE THREAD

**Issue by nekohayo** [cockpit-project/cockpit#2753]
As can be seen here:

![foo](https://cloud.githubusercontent.com/assets/479401/9837332/2c29bd8e-5a09-11e5-9980-0b25bd3d182d.png)

**Comment by dperpeet** [comment]
@mvollmer does https://github.com/cockpit-project/cockpit/commit/2efc1b01a8a436e420fe6bdcf20c781885005a80 affect this?

**Comment by mvollmer** [comment]
Recorded as part of https://trello.com/c/Wr090pj5/463-epic-monitoring-love, closing here for house keeping.
