### ISSUE TITLE
Kubernetes dashboard flickers when filtering

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2760]
The kubernetes dashboard flickers twice when filtering. The screen is redrawing itself too many times. @petervo Any ideas?

**Comment by stefwalter** [comment]
Although this no longer happens when filtering, it happens when refreshing the dashboard. Open the Overview page. press F5 ... the dashboard refreshes ... and then refreshes again.

**Comment by stefwalter** [comment]
> Although this no longer happens when filtering, it happens when refreshing the dashboard. Open the Overview page. press F5 ... the dashboard refreshes ... and then refreshes again.

Nope, this happens on all pages here.

**Comment by petervo** [comment]
What browser? Seems like it's always been like this, but what I see is the dashboard start out as empty with the rocket, and then fill in the pods. Once the services are in, i don't see a second render. Or is that initial filling in of the data what you are talking about

**Comment by stefwalter** [comment]
It seems like all the pages are doing this on my machine, when I had a second unreachable machine added to the dashboard. Was due to lousy machines.js code. I've reworked this in machine-loader branch and the flicker has gone.
