### ISSUE TITLE
Hiding default kubernetes service

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#2764]
Right now the code that we have to hide the default kubernetes service doesn't really work and leads to the service reappearing depending on what is tracking "Service" when the data is loaded/reloaded. 

Is the goal to hide that service everywhere? If so we probably need to filter it out in the client. Otherwise something in the dashboard is probably appropriate.

**Comment by stefwalter** [comment]
@sub-mod Did you also file a bug for this? Yes, we've seen this for a while, but nobody has fixed it yet.

I think the goal is just to hide it only on the 'Overview' dashboard.

**Comment by petervo** [comment]
opened PR #2765
