### ISSUE TITLE
Connecting to older cockpit fails to show certain components

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2772]
The docker, storage, network, and init, server have been moved out of shell. We still need to use those old locations and paths when connecting to old cockpit systems.

**Comment by petervo** [comment]
I merged #2773, but we still have the reverse issue. Where if an old version is the primary and a new version the secondary the moved sections on the secondary are broken.

**Comment by petervo** [comment]
Fixed in #2793
