### ISSUE TITLE
Graphs are now uglier than in 0.6x and early 0.7x

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2775]
The various small graphs are quite ugly compared to where they were in early 0.6x releases and 0.7x  releases. Can we tweak them back to the way they were? We know the previous settings, right?

FYI @andreasn

**Comment by andreasn** [comment]
All of them are now using PCP, so that adds some noise (and functionality).
What if we pick up patternfly-styled graphs https://www.patternfly.org/wp-content/uploads/2015/07/dashboard_callout.png

**Comment by andreasn** [comment]
Mockup:
![screenshot from 2015-09-30 12-51-26](https://cloud.githubusercontent.com/assets/209895/10191224/5e047936-6772-11e5-9476-a26955493e07.png)

**Comment by andreasn** [comment]
This would mean that we would need to decide on what unit to display, instead of being flexible like now.
The number on the top right of the graph would be the current load and the unit we determine.

**Comment by andreasn** [comment]
Slightly zoomed out view to show how the elements align with others on the page.
![screenshot from 2015-09-30 12-59-09](https://cloud.githubusercontent.com/assets/209895/10191324/1cd428b6-6773-11e5-80ef-1e8671e6f2b6.png)

**Comment by mvollmer** [comment]
We don't have the "current value" element anymore.  What about this:

![prettier-plots](https://cloud.githubusercontent.com/assets/3228183/10425429/40acabac-70e0-11e5-8d7f-3c35fd86bab5.png)

**Comment by andreasn** [comment]
Looks good. I think it would benefit from some spacing, and to have the left side of the graph line up with the title
![graph-mockup](https://cloud.githubusercontent.com/assets/209895/10427549/e0e72f02-70ea-11e5-9981-53bb99306728.png)

**Comment by andreasn** [comment]
The timestamps feels a bit too glued to the  graph above them. Would need 2-3 more pixels I think

**Comment by andreasn** [comment]
I think it looks slightly better if the line under the controls is 1px high instead of 2px

**Comment by mvollmer** [comment]
> The timestamps feels a bit too glued to the graph above them. Would need 2 pixels more above I think

I have used 3px.

**Comment by mvollmer** [comment]
> I think it would benefit from some spacing, and to have the left side of the graph line up with the title

Alignment is fixed, and I added 2px to the margin between the y-axis label and the grid.

**Comment by mvollmer** [comment]
![prettier-plots-2](https://cloud.githubusercontent.com/assets/3228183/10448383/2e1d23f8-7195-11e5-939c-2318b1409a1a.png)

**Comment by mvollmer** [comment]
Instead of the titles, what about moving the controls closer to the plots?
![prettier-plots-3](https://cloud.githubusercontent.com/assets/3228183/10449507/b7f33ab6-719c-11e5-87cd-64f786f519be.png)

**Comment by andreasn** [comment]
Yeah, probably makes sense. Commented on the pull request.
