### ISSUE TITLE
kubernetes: Fix spacing for adjust replication controller

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2780]
Two issues with the adjust dialog and button.
1. In the topology view, please add space as indicated in the design: https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/kubernetes/alter.png 
2. The buttons in the adjust replication controller dialog wrap while the action is taking place. They should remain in their positions.

**Comment by stefwalter** [comment]
Both these issues are visible here: 

https://www.youtube.com/watch?v=tiv9tIs4qkw

**Comment by martinpitt** [comment]
The RC adjustment dialog is much wider now, even with very narrow screen sizes.  There is no wrapping any more. So item 2 is fixed.

I'm not sure what item 1 means, i. e. which exact spacing it applies to. But this seems minor, and with the k8s UI being in maintenance mode, I suggest to not bother any more.
