### ISSUE TITLE
Test: no docker in newly built fedora 22 images

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#2792]
This just happened on master and a pull request. @mvollmer has this happened to you?

version `docker.x86_64 1.8.1-3.git32b8b25.fc22`

From hubbot:
```
Failed to start docker.service: Access denied
+ docker pull busybox:latest
Post http:///var/run/docker.sock/v1.20/images/create?fromImage=busybox%3Alatest: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?```

**Comment by dperpeet** [comment]
might be related to https://bugzilla.redhat.com/show_bug.cgi?id=1224211
I will investigate further.

**Comment by stefwalter** [comment]
> Post http:///var/run/docker.sock/v1.20/images/create?fromImage=busybox%3Alatest: dial unix /var/run/docker.sock: no such file or directory.

This means docker is not running.

**Comment by dperpeet** [comment]
> This means docker is not running.

yes, but `Failed to start docker.service: Access denied` when trying to start it via systemctl is something else.

**Comment by dperpeet** [comment]
As noted in the bug, `systemctl daemon-reexec` and a reboot seem to work for now

**Comment by dperpeet** [comment]
This has been fixed upstream, closing this.
