### ISSUE TITLE
Show all user sessions and history

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#28]
Not just whether someone is currently logged or when the last time was.

**Comment by martinpitt** [comment]
This would fit well on the Accounts page. A single account already has a "Terminate Session" button, so the overview could at least show all running sessions, or perhaps better, change the card appearance to indicate if that user is logged in or not.

**Comment by marusak** [comment]
Related [design](https://raw.githubusercontent.com/cockpit-project/cockpit-design/9a65b44ffa9cf60a6eaf02044e797d0046b77d6b/users/login-warning.png). (Last two screen).

**Comment by marusak** [comment]
`last --time-format iso mmarusak` can provide this list.
