### ISSUE TITLE
Specify maximum file size for cockpit.file().read()

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2818]
I think we should have a maximum file size specified on creating cockpit.file() and fsread1 channels, along with a healthy default. That way we won't accidentally load megabytes of data into the browser.

**Comment by stefwalter** [comment]
@mvollmer WDYT?

**Comment by mvollmer** [comment]
Yes, that's a good idea.

**Comment by mvollmer** [comment]
Although, as with timeouts, the limit will be hit somewhere in the field and might just cause annoying breakage.  Hmm.
