### ISSUE TITLE
Prevent assigning already taken ports to containers

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#283]
Right now it's fairly easy to by mistake assign a port already used by another container to a new container. This results in the container just shutting down immediately.
We should check what ports are already in use and give a inline warning that the port is already used, but perhaps make it possible to go ahead anyway?

**Comment by a2batic** [comment]
@andreasn @mvollmer  @stefwalter @dperpeet. I would like to work upon the design. Can you elaborate on what all mockups are required here ?

**Comment by dperpeet** [comment]
> @andreasn @mvollmer @stefwalter @dperpeet. I would like to work upon the design. Can you elaborate on what all mockups are required here ?

This is an interesting one. I think before we need mockups here, we need some prior design steps: Some workflows / scoping. Should we detect just ports that docker is already using? All ports? Should the user be able to go ahead anyway? Maybe you need to try what happens right now when you try to use a port twice in the Cockpit/docker ui. Once those questions (and others?) are answered, we can think about where such a warning would be displayed in the ui. The run dialog is also currently being worked on, so mockups should probably wait until https://github.com/cockpit-project/cockpit/pull/4405 has been merged or it's ui is "stable".

**Comment by a2batic** [comment]
@dperpeet, till #4405 is being worked on, I will try to set up the issue on system.

**Comment by KKoukiou** [comment]
See reasoning for closing here https://github.com/cockpit-project/cockpit/pull/4405#issuecomment-418184515
