### ISSUE TITLE
broken image in domain dialog

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2830]
![screenshot from 2015-09-25 13-57-52](https://cloud.githubusercontent.com/assets/209895/10099814/85ae130e-638d-11e5-8cb8-1f99d6d960df.png)

**Comment by stefwalter** [comment]
@andreasn Can we avoid using an image here and use a font icon instead?

**Comment by andreasn** [comment]
I wonder if we need an image at all.
The pattern with the red outline and error text underneath that we use in the Create Account dialog would work a lot better here.
![screenshot from 2015-09-29 17-02-14](https://cloud.githubusercontent.com/assets/209895/10168183/f604b1ee-66cb-11e5-89f9-9f7695b06728.png)

**Comment by andreasn** [comment]
![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/misc/join-domain.png)

**Comment by andreasn** [comment]
I must admit I have no idea how to alter the code to achieve the result above. :/

**Comment by stefwalter** [comment]
Opened issue https://github.com/cockpit-project/cockpit/issues/3415 to deal with the dialog in general.
