### ISSUE TITLE
network graph controls lack padding

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2831]
![screenshot from 2015-09-25 14-02-09](https://cloud.githubusercontent.com/assets/209895/10099878/1763af3e-638e-11e5-8a71-7ea0b7e74b67.png)

**Comment by stefwalter** [comment]
@andreasn, Is this something you're going to fix?

**Comment by andreasn** [comment]
Yep!

**Comment by andreasn** [comment]
Closing this issue, since the fix is merged.
