### ISSUE TITLE
Honor /etc/os.release.d/*

### ISSUE THREAD

**Issue by fabiand** [cockpit-project/cockpit#2861]
Fedora lately started to use /etc/os.release.d/* to provide snippets to override /etc/os-release:
http://pkgs.fedoraproject.org/cgit/fedora-release.git/tree/fedora-release.spec#n88

Cockpit should honor this override mechanism.

**Comment by stefwalter** [comment]
@fabiand Are you interested in patching the code to handle this? If so, the code in question is here: https://github.com/cockpit-project/cockpit/blob/master/src/common/cockpitsystem.c

**Comment by Akasurde** [comment]
@stefwalter on Fedora 23, I see, `/usr/lib/os-release` is symlink to `/etc/os.release.d/os-release-fedora` and internally `/etc/os-release` is symlink to `/usr/lib/os-release`

IMO, this is handled. Let me know if you have different views? I am OK to work on this.

**Comment by fabiand** [comment]
@Akasurde AFAIK some spins (i.e. the Atomic image) is using /etc/os.release.d/ to add/override some vars in /etc/os-release.
And this is currently not handled in the code.

I looked at it initially, but I did not yet get to it :-/

**Comment by Akasurde** [comment]
@fabiand I will try to find what is behavior in in Atomic Image and update.

**Comment by fabiand** [comment]
See i.e. http://pkgs.fedoraproject.org/cgit/fedora-release.git/tree/fedora-release.spec#n117

**Comment by fabiand** [comment]
Also [Rename /etc/os.release.d to /etc/os-release.d](https://bugzilla.redhat.com/show_bug.cgi?id=1282430)

**Comment by fabiand** [comment]
It seems that os.release.d is just holding alternaitve versions for the os-release file.

It is not used to provide partial snippets for overriding some parts of os-release, this means this issue can be closed.
