### ISSUE TITLE
Logs vs Journals

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2872]
Since recently, the entry in the sidebar is Logs, while things like the Storage page still calls it "Storage Journal"

**Comment by stefwalter** [comment]
Yes good catch. What do you think the name should be?

**Comment by andreasn** [comment]
I'm not quite sure, but I'm probably happy as long as the name is consistent. :)
The journal documentation mentions logs several times, and I think that's the name that is most familiar to most sysadmins, both those familiar with Linux and those with a Windows background [1]
"systemd-journald is a system service that collects and stores logging data." [2]

I'll create a pull request to make it all called "Logs".

1. https://technet.microsoft.com/en-us/library/cc722404.aspx
2. http://www.freedesktop.org/software/systemd/man/systemd-journald.service.html
