### ISSUE TITLE
check-multi-machine-key fails on Fedora 23

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#2876]
```
ERROR: testBasic (__main__.TestMultiMachineKeyAuth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-multi-machine-key", line 144, in testBasic
    "2048 SHA256:gwSyNJuAvsZXlsv+zQNten2XaCe4cw6Gbqw2tmFTBRA /home/admin/.ssh/identity (RSA)",
  File "./check-multi-machine-key", line 85, in test_keys
    b.wait_js_func("(function (expected) { return window.test_result == expected; })", "\n".join(keys) + "\n")
  File "/home/mvo/work/cockpit/test/testlib.py", line 208, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))), timeout=self.phantom_wait_timeout)
  File "/home/mvo/work/cockpit/test/testlib.py", line 656, in wait
    return self.run({'cmd': 'wait', 'cond': cond, 'timeout': timeout*1000})
  File "/home/mvo/work/cockpit/test/testlib.py", line 619, in run
    raise Error("timeout")
Error: timeout
```

From the journal:

```
syys 30 14:40:04 m10 cockpit-session[1283]: pam_ssh_add: Identity added: /home/admin/.ssh/id_rsa (/home/admin/.ssh/id_rsa)
syys 30 14:40:04 m10 cockpit-session[1283]: pam_ssh_add: Identity added: /home/admin/.ssh/id_ed25519 (/home/admin/.ssh/id_ed25519)
syys 30 14:40:04 m10 cockpit-session[1283]: pam_ssh_add: Failed adding some keys
```

The `/home/admin/.ssh/identity` key is not loaded into the agent, apparently.

**Comment by petervo** [comment]
Looks like in june openssh changed their default build options from with-ssh1 to without-ssh1. That means that on fedora 23 .ssh/identity won't be picked up automatically but ssh-add. It still works if you pass the key directly but it doesn't help us here.

@stefwalter you were talking the other day about droping ssh1 support in cockpit. If we are good to do that I can add another key format that is supported by default on f23.

**Comment by stefwalter** [comment]
I think dropping SSH1 support is a good plan. Although I managed to deal with them in the SSH private key UI, I don't think it's productive to work with those old kinds of keys. People can obviously use them if they want, just not in a seamless fashion with Cockpit.
