### ISSUE TITLE
TLS handshake errors with latest Chrome/OSX

### ISSUE THREAD

**Issue by edrex** [cockpit-project/cockpit#2897]
I just installed Cockpit on Arch using the AUR package and I am seeing errors like this when trying to log in as root from Chrome/Chromium 45 under OSX 10.10.3.

```
cockpit-ws[#]: couldn't read from connection: Error performing TLS handshake: A connection with inappropriate fallback was attempted.
cockpit-ws[#]: couldn't read from connection: Error performing TLS handshake: An unknown public key algorithm was encountered.
cockpit-ws[#]: couldn't read from connection: Peer failed to perform TLS handshake
```

Logging in with Firefox works fine.

**Comment by linux-modder** [comment]
chrome version?   also do you have  ANY  chrome://flags enabled or thrown?

**Comment by edrex** [comment]
Chromium Version 45.0.2454.101 (64-bit), no flags

Also Chrome Version 45.0.2454.101 (64-bit) (some flags, but see above)

**Comment by andreasn** [comment]
I can reproduce this, but only on Chrome 46, not Chrome 45

**Comment by andreasn** [comment]
(on a fedora system)

**Comment by andreasn** [comment]
Do you get just a blank screen after the login screen, or something else?

**Comment by stefwalter** [comment]
This is a bug in Gnutls 3.4.5 and similar. We've ascertained that this is not a bug in Cockpit:

https://bugzilla.redhat.com/show_bug.cgi?id=1273102
