### ISSUE TITLE
cockpit.js: failed to retrieve resource: no-host

### ISSUE THREAD

**Issue by subhashc** [cockpit-project/cockpit#2900]
Hi Stef,
Hope you are doing well!!

Recently i have installed below version in RHEL 7.1 and facing below error. Could you please advise on this issue.

Installed version
-----------------------
[root@docker-host1 subhashc]# rpm -qa | grep cockpit -i
cockpit-ws-0.71-1.el7.x86_64
cockpit-storaged-0.71-1.el7.x86_64
cockpit-bridge-0.71-1.el7.x86_64
cockpit-0.71-1.el7.x86_64
cockpit-shell-0.71-1.el7.noarch
cockpit-docker-0.71-1.el7.x86_64
[root@docker-host1 subhashc]#

Error log 
=========
[root@docker-host1 subhashc]# systemctl status  cockpit.service
cockpit.service - Cockpit Web Server
   Loaded: loaded (/usr/lib/systemd/system/cockpit.service; static)
   Active: active (running) since Mon 2015-10-05 14:29:12 IST; 8min ago
     Docs: man:cockpit-ws(8)
  Process: 7485 ExecStartPre=/usr/sbin/remotectl certificate --ensure --user=root --group=cockpit-ws (code=exited, status=0/SUCCESS)
 Main PID: 7489 (cockpit-ws)
   CGroup: /system.slice/cockpit.service
           ââ7489 /usr/libexec/cockpit-ws

Oct 05 14:37:08 docker-host1 cockpit-ws[7489]: /mustache.js: failed to retrieve resource: no-host
Oct 05 14:37:09 docker-host1 cockpit-ws[7489]: @latest@@: couldn't connect: Failed to resolve hostname lat...own)
Oct 05 14:37:09 docker-host1 cockpit-ws[7489]: /cockpit.js: failed to retrieve resource: no-host
Oct 05 14:37:09 docker-host1 cockpit-ws[7489]: @shell@@: couldn't connect: Failed to resolve hostname shel...own)
Oct 05 14:37:09 docker-host1 cockpit-ws[7489]: /shell.js: failed to retrieve resource: no-host
Oct 05 14:37:09 docker-host1 cockpit-ws[7489]: @shell@@: couldn't connect: Failed to resolve hostname shel...own)
Oct 05 14:37:09 docker-host1 cockpit-ws[7489]: /attrchange.js: failed to retrieve resource: no-host
Oct 05 14:37:09 docker-host1 cockpit-ws[7489]: /images/switcher.png: failed to retrieve resource: no-host
Oct 05 14:37:09 docker-host1 cockpit-ws[7489]: @shell@@: couldn't connect: Failed to resolve hostname shel...own)
Oct 05 14:37:09 docker-host1 cockpit-ws[7489]: /images/dialog-error.png: failed to retrieve resource: no-host
Hint: Some lines were ellipsized, use -l to show in full.
[root@docker-host1 subhashc]#

![cockpit](https://cloud.githubusercontent.com/assets/7770603/10276944/3a0bcb5e-6b70-11e5-9d01-11793b753c71.JPG)

**Comment by stefwalter** [comment]
It seems like you have mismatched cockpit resources from installing Cockpit manually. Please clear out ```/usr/local/share/cockpit``` ```/usr/share/cockpit``` and ```~/.local/share/cockpit``` and reinstall cockpit from official RHEL packages.
