### ISSUE TITLE
error when scaling pods via rc adjust option in the topology view

### ISSUE THREAD

**Issue by v1k0d3n** [cockpit-project/cockpit#2935]
i noticed an error with scaling pods via rc "adjust" option on the topology page.

Steps to reproduce are pretty easy (using kubernetes methods on CLI and Cockpit to scale out):

1. Start an environment consisting of an RC (pod numbers don't matter), and a Service.
2. Go to topology and click the "adjust" pencil icon. Double the number of replicated pods.
3. That will work just find. This is where things get strange. Remove the cluster via the CLI (just as it was created.
4. Bring up the same cluster, same amount of pods via the RC manifest.
5. Go to topology and clock the "adjust" pencil icon to double the number of replicated pods again.
6. Now you'll notice that the number has actually tripled rather than doubled. It's...strange. More pods than expected.
7. If you try to scale back to the desired state, than you get an error that say "! Conflict" with no other details.

This is Cockpit Version 0.78, that's included in Fedora 23 Beta.

**Comment by stefwalter** [comment]
Do you have an example RC definition that makes this happen?

**Comment by v1k0d3n** [comment]
https://github.com/v1k0d3n/kubelab/tree/master/jinkit-demo/kube/demo/guestbook

**Comment by v1k0d3n** [comment]
the really quick version is:

STEP 1: Create the Redis Master RC
kubectl create -f redis-master-controller.yaml

OPTIONAL:
kubectl get rc
kubectl get pods
kubectl describe pods/redis-master-XXXXX
kubectl logs redis-master-XXXXX

STEP 2: Create the Redis Master Service
kubectl create -f redis-master-service.yaml

OPTIONAL:
kubectl get services
kubectl describe services redis-master


STEP 3: Create Redis Slave RC
kubectl create -f redis-slave-controller.yaml

OPTIONAL:
kubectl get pods

STEP 4: Create the Redis Slave Service
kubectl create -f redis-slave-service.yaml

STEP 5: Create the Front-End RC
kubectl create -f frontend-controller.yaml

OPTIONAL:
kubectl get rc
kubectl get pods

STEP 6: Create the Front-End Service
kubectl create -f frontend-service-np.yaml


Tear Down Lab:
kubectl stop rc -l "name in (redis-master, redis-slave, frontend)"
kubectl delete service -l "name in (redis-master, redis-slave, frontend)"

**Comment by sub-mod** [comment]
I saw this issue and I have fixed it in https://github.com/cockpit-project/cockpit/pull/2899

**Comment by stefwalter** [comment]
So I guess this issue can be closed?
