### ISSUE TITLE
previous servers looks like an accordion

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2955]
![screenshot from 2015-10-13 15-05-30](https://cloud.githubusercontent.com/assets/209895/10455496/ed5a08d2-71bb-11e5-9c96-d8d493085f4e.png)

**Comment by andreasn** [comment]
maybe it would be better to do it like the firefox/chrome address bar

**Comment by stefwalter** [comment]
Discussed this more, and without some sort of discovery, there aren't very many compelling arguments for having auto-complete here.

**Comment by petervo** [comment]
#3018 changed previous servers to a autocomplete bar.
