### ISSUE TITLE
RFE: print port on start/status 

### ISSUE THREAD

**Issue by whitel** [cockpit-project/cockpit#2962]
As cockpit launches on a non-standard port, it might be nice if "systemctl status cockpit" reported the port it was running on.

**Comment by stefwalter** [comment]
The port isn't really non-standard (9090 is the 'web system manager' port) but I agree, it would be nice to use the sd_notify API to push out a status with the port.

**Comment by whitel** [comment]
Well TIL :)

**Comment by martinpitt** [comment]
`systemctl status cockpit.socket` does show the port by default. `cockpit.service` has no way to know that, as it just receives an FD of the already opened socket from systemd.
