### ISSUE TITLE
Easy to miss to make user administrator

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#2975]
Spinned off https://bugzilla.redhat.com/show_bug.cgi?id=1258169

It seems it's easy to miss to make a user an administrator, leading to confusion around why things like shutdown doesn't work.
It was suggested that there could be an option to make a user administrator already in the create dialog.

**Comment by andreasn** [comment]
GNOME Account creation dialog:
![screenshot from 2015-10-19 13-58-05](https://cloud.githubusercontent.com/assets/209895/10577232/ac8c6fb8-7669-11e5-942b-6d16720705f5.png)

**Comment by andreasn** [comment]
![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/users/user-creation.png)

**Comment by andreasn** [comment]
Was torn between this and a dropdown. The dropdown means you'll never see the word "Administrator", while the checkbox wording is super-clear. Having the checkbox at the bottom might mean that it's easy to miss, since all the necessary boxes that the dialog forces you to fill is done by the time you reach that box. Might just be obsessing too much though.

**Comment by stefwalter** [comment]
Are we giving up on other possible roles in the design?

**Comment by andreasn** [comment]
The control for an existing user is only a checkbox for admin now (since it was the only one left, and it felt wrong to hide that only entry in it's own dialog), but I'm open to at least long term bring back the roles. Maybe we could do that as a SELinux-thing, or using something else http://www.ibm.com/developerworks/library/l-rbac-selinux/index.html

Making it a (multiselect? again, depends on selinux/something-else functionality) dropdown to prepare for when it become more options than just a simple admin on/off-thing would certainly weight in favor of the dropdown in that case.

**Comment by andreasn** [comment]
Maybe not the best example url above. This one might be slightly better http://selinux-mac.blogspot.se/2009/06/selinux-lockdown-part-five-selinux-rbac.html giving examples of roles such as User, Admin, Staff, Web Admin, Log Admin

**Comment by petervo** [comment]
> The control for an existing user is only a checkbox for admin now (since
> it was the only one left, and it felt wrong to hide that only entry in
> it's own dialog), but I'm open to at least long term bring back the
> roles. Maybe we could do that as a SELinux-thing, or using something
> else http://www.ibm.com/developerworks/library/l-rbac-selinux/index.html

We still display a checkbox for "docker" as "Container Administrator" if 
that groups exists.

**Comment by andreasn** [comment]
![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/users/user-creation-accounttype.png)

Are the Container Administrator and Administrator exclusive to each other, or can you be both a Administrator _and_ a Container Administrator?

**Comment by petervo** [comment]
They are not exclusive.

**Comment by andreasn** [comment]
I think this needs to become some variant of https://www.patternfly.org/widgets/#bootstrap-select but not sure yet

**Comment by andreasn** [comment]
![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/users/user-creation.png)

**Comment by andreasn** [comment]
Might need to shift-reload your browsers to get the latest image above.

**Comment by stefwalter** [comment]
Looks good. Maybe this is worth adding to Trello?

**Comment by andigi89** [comment]
Hi,
is anybody working currently on this issue?

Regards

Andi

**Comment by andreasn** [comment]
Not that I'm aware of. Feel free to make a PR!

**Comment by KKoukiou** [comment]
@andreasn do we want this implemented?
You can make a user admin after creating them - I don't see why we would like to put this in the creation dialog.

**Comment by andreasn** [comment]
Because apparently it's not obvious enough how it it now. At least that's what Chris said in the bug https://bugzilla.redhat.com/show_bug.cgi?id=1258169

**Comment by KKoukiou** [comment]
So I would like to close this issue as WONTFIX, as part of our February2021 issue cleanup. Creating a new user and then adding them to the wheel group is a normal workflow when creating users from the terminal as well.

I would not like to add more options to the main dialog, it has enough fields already.
