### ISSUE TITLE
Specify Certificate Chain File

### ISSUE THREAD

**Issue by dcrdev** [cockpit-project/cockpit#2980]
When generating self signed certificates it becomes difficult to add an exception in some browsers because of the lack of certificate chain. One way around this is to sign certificates with a self signed CA, but given self signed CAs are not trusted they need to be sent as part of the request.

I would love to be able to specify a certificate chain file somewhere within the cockpit web server configuration, as far as I can tell there is nowhere to do this.

**Comment by stefwalter** [comment]
See 'man cockpit-ws' or the guide: http://files.cockpit-project.org/guide/latest/https.html

**Comment by stefwalter** [comment]
I've taken this opportunity to add some further clarifications to the guide and man page. I hope they clear up any remaining questions.

**Comment by dcrdev** [comment]
Thanks I had already worked out how to create a certificate - the .cert format cockpit uses is essentially just a concatenation of the private key and certificate. However my above query was in reference to supplying a certificate chain or intermediate certificate within the request - perhaps I'm not making sense; in essence this would be equivalent to Apache's SSLCertificateChainFile directive; see http://httpd.apache.org/docs/2.2/mod/mod_ssl.html#sslcertificatechainfile .

**Comment by stefwalter** [comment]
That does make sense. Good point. I believe that one puts multiple certificates in the .cert file in this case. We need to add a test to make sure this works, and update the documentation.

**Comment by stefwalter** [comment]
The support for loading certificate chains from a PEM file was added to GLib in 2.44

For earlier GLib versions we may need to retrofit this support.

**Comment by stefwalter** [comment]
For certificate chain loading to work you'll need either of the following:

 * Cockpit 0.81 (not yet released)
 * Glib 2.44 (very recent, eg: in Fedora 23)

Thanks for highlighting this as an issue. I've updated documentation, added tests for this case, and backported the Glib 2.44 feature in pull request #2981

**Comment by dcrdev** [comment]
Brilliant thanks - I'll give it a test when I can.
