### ISSUE TITLE
Missing UTC timezone

### ISSUE THREAD

**Issue by isius** [cockpit-project/cockpit#3029]
System > System Time > Change System Time > Timezone
Set Time: "Set time automatically using NTP"

Time Zone: Displays "Africa/Abidjan" when server is actually set to UTC. UTC timezone not available in dropdown to select.

**Comment by stefwalter** [comment]
What does the following command output on your server?

```
$ timedatectl list-timezones
```

**Comment by isius** [comment]
Hmm, it's quite long at 416 zones (I'll post them all if you wish). UTC isn't among them.
However, `$ timedatectl` reports timezone as "UTC (UTC, +0000)".

**Comment by stefwalter** [comment]
This is what I see here:

```
$ timedatectl list-timezones | grep UTC
UTC
```

What operating system are you using? This is probably an operating system or a bug in its version of systemd.

**Comment by isius** [comment]
Indeed, that's the command I used as well. No UTC.

**Comment by isius** [comment]
Asking around [ServerFault](http://serverfault.com/questions/731760/why-doesnt-timedatectl-list-timezones-list-all-timezones) has been helpful to get an idea of what's going on. But I'm not sure where that leaves this issue. I *could* "fix" it at the system level (manually). Or wait for a CentOs patch or update? But I'm wondering if this may be something that should be handled by Cockpit.

For what it's worth, it's true that the timezone isn't in the list of available timezones, but, presumably, the timezone is currently set to a *valid* timezone, which should be reported as such, yes?
Although that would leave the condition where it's possible that one could change from UTC (for instance) to any other timezone in the list, then be unable to change back to UTC since it would no longer be an available option.

**Comment by stefwalter** [comment]
> For what it's worth, it's true that the timezone isn't in the list of available timezones, but, presumably, the timezone is currently set to a valid timezone, which should be reported as such, yes?

Yes, that's a good point. It should be displayed in any case, even when not in the list of timezones.

Are you interested in making a pull request to fix this? The code is here: https://github.com/cockpit-project/cockpit/blob/master/pkg/systemd/host.js#L823

**Comment by Akasurde** [comment]
@stefwalter I am able to see UTC in given workflow. Is this fixed ?

Fedora 24, Cockpit 0.103

**Comment by stefwalter** [comment]
I can't reproduce this in Fedora. I don't think it's fixed though, because UTC is listed in the ```timedatectl list-timezones``` output no matter what I do.
