### ISSUE TITLE
0.71 Not Understanding LVM Layout on CentOS 7.1

### ISSUE THREAD

**Issue by dcrdev** [cockpit-project/cockpit#3038]
I'm currently testing out cockpit on CentOS 7.1 having come from using cockpit on Fedora. I've set up a simple LVM layout in a virtual machine, which looks like this:

LVM Group 1
/ root
/ swap

LVM Group 2
/home

However cockpit doesn't seem to recognise this layout - it shows the LVM groups in the "other devices" section of the storage tab. I cannot add volume groups, resize disks etc.. in the same way that I could in fedora.

See the screenshot below:
![Cockpit 0.71 CentOS](http://i.imgur.com/vie0Wjt.png?1)

Also getting this in the journal:
(null): unknown internal metric block.device.write

**Comment by dcrdev** [comment]
So I've done some digging and it turns out that the CentOS cockpit package doesn't pull down storaged-lvm2.

**Comment by stefwalter** [comment]
The commit 63de904106c6983c48127cfd87f2073a2ce52400 started to require pulling in storaged-lvm2 by default. That commit is included in Cockpit 0.78 and later.

**Comment by sudhaker** [comment]
Following message continue to flood the /var/log/messages even after installing 'storaged-lvm2'
(null): unknown internal metric block.device.write

Seems the correct metric is block.device.written; some typo somewhere on UI side.

**Comment by stefwalter** [comment]
@sudhacker That's indeed a bug. It was fixed in 486e37d11383d2b90de15021086506859c88e961

**Comment by sudhaker** [comment]
On CentOS 7.2 | cockpit-storaged-0.77-3.1.el7.noarch

Not sure when distribution will include this patch so I patched it myself.

yum install storaged-lvm2 -y

gunzip /usr/share/cockpit/storage/bundle.min.js.gz
manually patch --> search for "block.device.write" and fix
gzip /usr/share/cockpit/storage/bundle.min.js

Thanks Stef :-)
