### ISSUE TITLE
The error message "Cannot forward login credentials" is not helpful

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#3075]
I get this when I try to access a machine via ssh that needs one of my ssh keys, but that key is not currently "On".  "Login failed" would have been more helpful.

**Comment by petervo** [comment]
#3018 changed machine connection errors messages. This text, "Cannot forward login credentials" is still used in some places, but there is a lot more context now. I guess the question is, is this still confusing?

**Comment by petervo** [comment]
This message has been removed in #3375
