### ISSUE TITLE
When adding a machine, "access-denied" case could be improved.

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#3076]
This happens when the login succeeds but cockpit can't become superuser on the other machine.  The message might give the impression that the password was wrong, or something was wrong with the ssh keys.

One option would be to continue without any setup tasks.

**Comment by stefwalter** [comment]
@petervo I think this is the case in the work you're doing right?

**Comment by petervo** [comment]
The flow changed so you won't get the impression that the password was wrong. In #3018 if you don't have superuser permissions the machine will add but you'll be prompted for a user / pass when syncing users. If already authenticated with a superuser account those inputs won't be present.
