### ISSUE TITLE
 added second machine, log out and log in back and it is unable to connect added machine again

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#3117]
Hi,
I've found some troubles with multiple machines
I've added second machine with cockpit-0.71
to dashboard on cockpit-0.77
* I've changed pretty host names.
-- It works as expected, host added, able to change and discover then machine
* I've logged out
* I've logget in back
-> unable to connect second machine, try to connect but fails with:

Couldn't connect to the machine
Internal error

# systemctl -l status cockpit
● cockpit.service - Cockpit Web Server
   Loaded: loaded (/usr/lib/systemd/system/cockpit.service; static; vendor preset: disabled)
   Active: active (running) since Wed 2015-11-04 06:00:31 EST; 24min ago
     Docs: man:cockpit-ws(8)
 Main PID: 1987 (cockpit-ws)
   Memory: 2.3M
   CGroup: /system.slice/cockpit.service
           ├─1987 /usr/libexec/cockpit-ws
           └─2923 /usr/bin/ssh-agent

Nov 04 06:23:51 ahoj2.machine.com cockpit-ws[1987]: Couldn't make temporary name for knownhosts line: Permission denied
Nov 04 06:23:51 ahoj2.machine.com cockpit-ws[1987]: /manifests.json: failed to retrieve resource: internal-error
Nov 04 06:23:52 ahoj2.machine.com cockpit-ws[1987]: Couldn't make temporary name for knownhosts line: Permission denied
Nov 04 06:23:52 ahoj2.machine.com cockpit-ws[1987]: /manifests.json: failed to retrieve resource: internal-error
Nov 04 06:23:52 ahoj2.machine.com cockpit-ws[1987]: Couldn't make temporary name for knownhosts line: Permission denied
Nov 04 06:23:52 ahoj2.machine.com cockpit-ws[1987]: /manifests.json: failed to retrieve resource: internal-error
Nov 04 06:23:52 ahoj2.machine.com cockpit-ws[1987]: Couldn't make temporary name for knownhosts line: Permission denied
Nov 04 06:23:52 ahoj2.machine.com cockpit-ws[1987]: /manifests.json: failed to retrieve resource: internal-error
Nov 04 06:23:53 ahoj2.machine.com cockpit-ws[1987]: Couldn't make temporary name for knownhosts line: Permission denied
Nov 04 06:23:53 ahoj2.machine.com cockpit-ws[1987]: /manifests.json: failed to retrieve resource: internal-error
![screenshot from 2015-11-04 12 43 43](https://cloud.githubusercontent.com/assets/8735467/10937395/d6f0d4ac-82f2-11e5-8da6-bad2403a2948.png)
![screenshot from 2015-11-04 12 43 56](https://cloud.githubusercontent.com/assets/8735467/10937396/d6f658d2-82f2-11e5-8589-b3f74760ea79.png)

**Comment by jscotka** [comment]
Hi,
I was not able to reproduce same issue for second time. Seems that I've also done step what I don't remember now, or there were some external issue, what somehow breaks that.

**Comment by petervo** [comment]
This is caused by selinux blocking cockpit-ws from writing to the /tmp dir to create the tmp known hosts file.

type=AVC msg=audit(1446822429.928:1027): avc:  denied  { write } for  pid=9224 comm="ssh-transport-c" name="/" dev="tmpfs" ino=37147 scontext=system_u:system_r:cockpit_ws_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=dir

**Comment by stefwalter** [comment]
@jscotka What operating system is this on?
