### ISSUE TITLE
switch from  system/#memory -> /@qeos-40 causes Ooops!

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#3118]
Hi,
it is connected with issue:
https://github.com/cockpit-project/cockpit/issues/3117

I test then to o to page: /system#/memory
and then I've tried to switch to /@qeos-40 from menu at the top of page 
causes Ooops!

there is lots of js errors after playing with that: (some of them are only warnings these are acceptable)

TypeError: elem.css(...) is undefined jquery.js:11845:751
"transport closed, dropped message: " "
{"command":"kill","group":"cockpit1:localhost/dashboard"}" cockpit.js:539:13
"transport closed, dropped message: " "
{"command":"kill","group":"cockpit1:localhost/system"}" cockpit.js:539:13
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. cockpit.css:52:10
Error in parsing value for 'vertical-align'.  Declaration dropped. cockpit.css:113:20
Unknown property '-moz-border-radius'.  Declaration dropped. cockpit.css:217:22
Unknown pseudo-class or pseudo-element '-webkit-inner-spin-button'.  Ruleset ignored due to bad selector. patternfly.css:180:22
Unknown pseudo-class or pseudo-element '-webkit-search-cancel-button'.  Ruleset ignored due to bad selector. patternfly.css:188:22
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. patternfly.css:299:25
Expected color but found 'auto'.  Expected color but found '-webkit-focus-ring-color'.  Expected end of value but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. patternfly.css:1129:15
Expected end of value but found '\9 '.  Error in parsing value for 'margin-top'.  Declaration dropped. patternfly.css:2540:18
Expected color but found 'auto'.  Expected color but found '-webkit-focus-ring-color'.  Expected end of value but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. patternfly.css:2558:15
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. patternfly.css:2596:14
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. patternfly.css:2599:15
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. patternfly.css:2610:14
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. patternfly.css:2614:15
Expected media feature name but found '-webkit-min-device-pixel-ratio'. patternfly.css:2634:19
Expected end of value but found '\9 '.  Error in parsing value for 'margin-top'.  Declaration dropped. patternfly.css:2686:18
Unknown property 'touch-action'.  Declaration dropped. patternfly.css:3040:14
Unknown property 'user-select'.  Declaration dropped. patternfly.css:3052:13
Expected color but found 'auto'.  Expected color but found '-webkit-focus-ring-color'.  Expected end of value but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. patternfly.css:3061:15
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:3082:10
Expected color but found '\9 '.  Expected end of value but found '\9 '.  Error in parsing value for 'border-top'.  Declaration dropped. patternfly.css:3591:22
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:3666:10
Expected color but found '\9 '.  Expected end of value but found '\9 '.  Error in parsing value for 'border-bottom'.  Declaration dropped. patternfly.css:3707:25
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:5218:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:5219:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:5221:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:5235:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:5236:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:5238:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:5245:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:5246:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:5248:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:5255:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:5256:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:5258:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:5265:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:5266:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:5268:20
Unknown property 'zoom'.  Declaration dropped. patternfly.css:5279:6
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:5924:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:5932:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:6003:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:6007:10
Unknown property 'line-break'.  Declaration dropped. patternfly.css:6073:12
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:6086:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:6090:10
Unknown property 'line-break'.  Declaration dropped. patternfly.css:6191:12
Expected media feature name but found 'transform-3d'. patternfly.css:6329:16
Expected media feature name but found '-webkit-transform-3d'. patternfly.css:6329:32
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:6399:10
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:6406:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:6407:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:6410:10
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:6415:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:6416:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:6419:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:6427:10
Expected end of value but found '\9 '.  Error in parsing value for 'background-color'.  Declaration dropped. patternfly.css:6482:25
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. patternfly.css:6844:25
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:6933:10
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:6939:10
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:6945:10
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:6951:10
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:6957:10
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:8704:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:8705:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:8708:10
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:8759:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:8760:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:8763:10
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:8819:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:8820:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:8823:10
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:8910:10
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:8916:10
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:8923:10
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:9070:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:9071:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:9074:10
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:9205:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:9206:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:9209:10
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:9315:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:9316:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:9319:10
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:9330:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:9331:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:9334:10
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:9375:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:9376:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:9379:10
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:9558:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly.css:9559:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly.css:9562:10
Unknown property 'user-select'.  Declaration dropped. patternfly-additions.css:124:13
Expected end of value but found '�'.  Error in parsing value for 'width'.  Declaration dropped. patternfly-additions.css:1145:15
Expected color but found 'auto'.  Expected color but found '-webkit-focus-ring-color'.  Expected end of value but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. patternfly-additions.css:1164:15
Unknown property 'user-select'.  Declaration dropped. patternfly-additions.css:1401:13
Unknown property '-moz-box-shadow'.  Declaration dropped. patternfly-additions.css:1498:17
Unknown pseudo-class or pseudo-element '-ms-clear'.  Ruleset ignored due to bad selector. patternfly-additions.css:1590:31
Error in parsing value for 'background-image'.  Declaration dropped. patternfly-additions.css:1608:20
Error in parsing value for 'background-image'.  Declaration dropped. patternfly-additions.css:1609:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly-additions.css:1612:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. patternfly-additions.css:2060:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. patternfly-additions.css:2084:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. patternfly-additions.css:2094:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. patternfly-additions.css:2099:10
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly-additions.css:2206:10
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly-additions.css:2215:10
Expected declaration but found '*'.  Skipped to next declaration. patternfly-additions.css:2269:2
Unknown property 'speak'.  Declaration dropped. patternfly-additions.css:2338:7
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. patternfly-additions.css:2342:25
Error in parsing value for 'background-image'.  Declaration dropped. patternfly-additions.css:3023:22
Error in parsing value for 'background-image'.  Declaration dropped. patternfly-additions.css:3024:22
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly-additions.css:3027:12
Error in parsing value for 'background-image'.  Declaration dropped. patternfly-additions.css:3148:22
Error in parsing value for 'background-image'.  Declaration dropped. patternfly-additions.css:3149:22
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly-additions.css:3152:12
Error in parsing value for 'background-image'.  Declaration dropped. patternfly-additions.css:3166:22
Error in parsing value for 'background-image'.  Declaration dropped. patternfly-additions.css:3167:22
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly-additions.css:3170:12
Error in parsing value for 'background-image'.  Declaration dropped. patternfly-additions.css:3186:22
Error in parsing value for 'background-image'.  Declaration dropped. patternfly-additions.css:3187:22
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly-additions.css:3190:12
Error in parsing value for 'background-image'.  Declaration dropped. patternfly-additions.css:3198:22
Error in parsing value for 'background-image'.  Declaration dropped. patternfly-additions.css:3199:22
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly-additions.css:3202:12
Error in parsing value for 'background-image'.  Declaration dropped. patternfly-additions.css:3209:22
Error in parsing value for 'background-image'.  Declaration dropped. patternfly-additions.css:3210:22
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. patternfly-additions.css:3213:12
Unknown pseudo-class or pseudo-element '-ms-clear'.  Ruleset ignored due to bad selector. patternfly-additions.css:3574:37
Unknown property 'user-select'.  Declaration dropped. shell.css:310:15
Expected identifier for pseudo-class or pseudo-element but found ' '.  Ruleset ignored due to bad selector. shell.css:601:19
Use of getUserData() or setUserData() is deprecated.  Use WeakMap or element.dataset instead. BackgroundFramework.js:499:0
Use of getUserData() or setUserData() is deprecated.  Use WeakMap or element.dataset instead. cacheobj.js:877:0
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. BackgroundFramework.js line 465 > eval:4:0
"failed to load manifests from qeos-40: [object Object]" machines.js:398:25
"failed to load manifests from qeos-40: [object Object]" machines.js:398:25
"failed to load manifests from qeos-40: [object Object]" machines.js:398:25
"failed to load manifests from qeos-40: [object Object]" machines.js:398:25
"failed to load manifests from qeos-40: [object Object]" machines.js:398:25
"failed to load manifests from qeos-40: [object Object]" machines.js:398:25
"failed to load manifests from qeos-40: [object Object]" machines.js:398:25
"failed to load manifests from qeos-40: [object Object]" machines.js:398:25
"failed to load manifests from qeos-40: [object Object]" machines.js:398:25
TypeError: elem.css(...) is undefined jquery.js:11845:751
"failed to load manifests from qeos-40: [object Object]" machines.js:398:25
"failed to load manifests from qeos-40: [object Object]" machines.js:398:25
TypeError: elem.css(...) is undefined jquery.js:11845:751
"failed to load manifests from qeos-40: [object Object]" machines.js:398:25
"failed to load manifests from qeos-40: [object Object]" machines.js:398:25
TypeError: elem.css(...) is undefined jquery.js:11845:751

**Comment by jscotka** [comment]
Hi,
I've found that it is not connected with changing to another machine.
It is enought to be on one machine and go to:
https://10.8.49.27:9090/system#/cpu
or 
https://10.8.49.27:9090/system#/memory

and then switch to another tab like services:
https://10.8.49.27:9090/system/services
-> cause Ooops!

**Comment by stefwalter** [comment]
@mvollmer Just navigating to this on my machine directly (paste it into the title bar) causes a failure:

http://localhost:9090/system#/cpu

```
Error: Invalid dimensions for plot, width = 0, height = 360
```

**Comment by jscotka** [comment]
Hi, this trouble is still here in version 0.93-2  (moved to memory subpage and then for example to services tab)
![screenshot from 2016-02-10 09-04-52](https://cloud.githubusercontent.com/assets/8735467/12941771/cf791ed4-cfd5-11e5-987f-60faf423f549.png)

**Comment by martinpitt** [comment]
#3117 got fixed years ago, and going directly to http://localhost:9090/system#/cpu works now. So I think this got fixed by now. Please reopen if you still see it somewhere. Thanks!
