### ISSUE TITLE
Chunk Size must be zero, but there isnt 0 value in dropdown

### ISSUE THREAD

**Issue by filipeguarino** [cockpit-project/cockpit#3123]
Hello guys 
This error happens always that i try to create raid 1 in cockpit using Fedora 23.
![cockpit-chunk_size_must_be_zero](https://cloud.githubusercontent.com/assets/8042066/10969167/b9e9b660-83ad-11e5-816e-26e2a6d1a914.png)
![cockpit-not_exist_0_value_in_chunk_size](https://cloud.githubusercontent.com/assets/8042066/10969166/b9e51286-83ad-11e5-9c24-d0ad397b4831.png)

**Comment by dperpeet** [comment]
Good catch! This also affects Fedora 22.

**Comment by dperpeet** [comment]
Fixed in https://github.com/cockpit-project/cockpit/commit/897919b06c5384e277e4b645a179e641ca4ba009
