### ISSUE TITLE
cockpit memory graph (http://localhost:9090/system#/memory) does not show "MemAvailable"

### ISSUE THREAD

**Issue by shatadru** [cockpit-project/cockpit#3126]
- The graph shows Swap Used, cached, used, free.
- However it should also show the MemAvailable.
- It gives a better estimation how much memory is actually available for new processes.
- This is more realistic, than calculating free `mem available = free + cache + buffer`
- Just free does not makes sense, if you drop cache, it will show you you have more memory,
  But thats not the fact, available memory remains almost same, even `free + cache + buffer` remains same, as you have more free less cache, but this is not reflected in graph

```
From man free :
Estimation of how much memory is available for starting new applications, without swapping. Unlike the data provided by the cache or  free  fields,  this
              field  takes  into  account  page  cache  and  also  that  not  all reclaimable memory slabs will be reclaimed due to items being in use (MemAvailable in
              /proc/meminfo, available on kernels 3.14, emulated on kernels 2.6.27+, otherwise the same as free
```

See the below example : 
- After some I/O performed I have 4.8 GiB of cache but available mem is 6.6 GiB

```
# cat /proc/meminfo |grep kB |awk '{print $0,"~ " $2/2^20" GiB"}' | egrep "MemTotal|MemFree|Buffers|Cached|Slab|MemAvail" |grep -iv "swap" 
MemTotal:       16116380 kB ~ 15.3698 GiB
MemFree:         2808884 kB ~ 2.67876 GiB
MemAvailable:    6996084 kB ~ 6.67199 GiB
Buffers:           19092 kB ~ 0.0182076 GiB
Cached:          5072776 kB ~ 4.83778 GiB
Slab:             285944 kB ~ 0.272697 GiB

# cat /proc/meminfo |grep kB |awk '{print $0,"~ " $2/2^20" GiB"}' | egrep "MemTotal|MemFree|Buffers|Cached|Slab|MemAvail" |grep -iv "swap" 
MemTotal:       16116380 kB ~ 15.3698 GiB
MemFree:         6163716 kB ~ 5.87818 GiB
MemAvailable:    7005956 kB ~ 6.6814 GiB
Buffers:           19160 kB ~ 0.0182724 GiB
Cached:          1805864 kB ~ 1.72221 GiB
```
- After kernel reclaims the cache, its dropped to 1.72 GiB but still the mem available is 6.68 GiB

My point is MemAvailable actual gives how much memory is free, so it would be great for sysadmins if 
its included in cockpit

**Comment by shatadru** [comment]
![memgraph](https://cloud.githubusercontent.com/assets/15201458/10995761/2d5633e2-84a5-11e5-9062-ea0cebf0aa15.png)

**Comment by mvollmer** [comment]
Recorded as part of https://trello.com/c/Wr090pj5/463-epic-monitoring-love, closing here for house keeping.
