### ISSUE TITLE
Memory usage ticker reporting incorrectly

### ISSUE THREAD

**Issue by cj0nes** [cockpit-project/cockpit#3146]
On the main page of the server i'm monitoring, the memory usage says it's maxed.  When I click on the memory usage ticker, the memory usage page shows the actual usage (about half of what's shown on the main page).

**Comment by mvollmer** [comment]
I can't easily reproduce this.  Can you show some screenshots?  Also, could you tell whether you are using cockpit-pcp or not?

The detailed memory graph with swap/cached/used/free might be a bit bogus, actually, since 'cached' is probably already included in 'used'

**Comment by stefwalter** [comment]
No reply to the question. Closing this issue.
