### ISSUE TITLE
Cockpit - Publishing a container port or otherwise configuring a Docker Container is confusing.

### ISSUE THREAD

**Issue by rseward** [cockpit-project/cockpit#3151]
I expected to be able to click on an existing docker container and manage its settings for publishing a port to a localhost ip address. However I found I could not. 

I did not realize that I needed to create a new container from my mongo image in order to set this in the "Run Screen."

I suggest the cockpit team add a button next to "Start", "Stop", "Restart", etc. buttons.

I think the new button should read "Configure New Instance" or similar.

The button should take the user to the Run Image screen where you can configure exposed ports etc. for a new instance of the image.

Thank you,
Rob

**Comment by stefwalter** [comment]
It's a bit odd, but in docker such parameters happen when you create/run a container, and cannot be changed afterwards. 

@andreasn Is there anything we can do here to make it simpler?

**Comment by KKoukiou** [comment]
Closing this issue because the Docker plugin is not being actively developed any longer.
Replacement should be https://github.com/cockpit-project/cockpit-podman/ so any RFEs should be opened on that repository.
