### ISSUE TITLE
User "nobody" is shown in Accounts panel under Debian

### ISSUE THREAD

**Issue by mbiebl** [cockpit-project/cockpit#3166]
Under Debian, the user "nobody" is shown in the Accounts panel.

Fedora:
```
# getent passwd nobody
nobody:x:99:99:Nobody:/:/sbin/nologin
```
Debian
```
# getent passwd nobody
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
```

**Comment by mbiebl** [comment]
![cockpit-accounts](https://cloud.githubusercontent.com/assets/3609611/11160119/4ecfb504-8a66-11e5-926f-d388c7e4f48e.png)

**Comment by stefwalter** [comment]
Do you have a fix in mind? Is 'nobody' distinguishable from a real user on Debian?

**Comment by mbiebl** [comment]
Could we filter out accounts which have /bin/false or (/usr)/sbin/nologin as shell?

**Comment by mbiebl** [comment]
http://anonscm.debian.org/cgit/users/cjwatson/base-passwd.git/tree/passwd.master
those are the system users which are created statically on each system.

Then there are system users created dynamically via adduser. The UID range is defined in /etc/adduser.conf 
```
# FIRST_SYSTEM_[GU]ID to LAST_SYSTEM_[GU]ID inclusive is the range for UIDs
# for dynamically allocated administrative and system accounts/groups.
# Please note that system software, such as the users allocated by the base-passwd
# package, may assume that UIDs less than 100 are unallocated.
FIRST_SYSTEM_UID=100
LAST_SYSTEM_UID=999
```

**Comment by mbiebl** [comment]
I just looked what other software does, like AccountService. It's not pretty:
http://cgit.freedesktop.org/accountsservice/tree/src/user-classify.c

**Comment by stefwalter** [comment]
Yup. Mixing of system users with real users is a really broken part of Linux systems. There have been efforts to fix this, such as 'sysusers' but they have not (yet?) been widely adopted.

http://man7.org/linux/man-pages/man5/sysusers.d.5.html

> Could we filter out accounts which have /bin/false or (/usr)/sbin/nologin as shell?

Yes. That might work. Looks like that's part of accountsservice's heuristics. Are you interested in making the patch? Looks like an appropriate place is in ```pkg/users/local.js``` ... search for ```/sbin/nologin```.

**Comment by nenonano** [comment]
hi there..

related to this issue, an user with a password but with /sbin/nologin shell can log in cockpit (and his account is listed)
obviously he can't almost do anything, but it should avoided..
is the suggested package (pkg/users/local.js) the right place to check?

**Comment by pehden** [comment]
same issue, but in archlinux.
