### ISSUE TITLE
Reorder resource graphs

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#3168]
(From Marko Myllynen.)

cpu/mem/disk/net graphs look nice but I'd group them in that order
(ie, not cpu/mem/net/disk), it feels more logical and is what the rest
of the world (e.g. virt-manager etc) are following

**Comment by andreasn** [comment]
Seems to be the same order for [vSphere] (https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fi1-win.softpedia-static.com%2Fscreenshots%2FvSphere_1.png&f=1) and [Windows Server 2012](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.winserverhelp.com%2Fwp-content%2Fuploads%2F2011%2F01%2FScreenHunter_03-Jan.-19-21.04.gif&f=1) so sure, it makes sense to switch Network and Storage graphs around.
As a bonus, Storage is above Networking in the sidebar, so the will be the same order.
