### ISSUE TITLE
user is not recognized as admin user

### ISSUE THREAD

**Issue by mbiebl** [cockpit-project/cockpit#3176]
Under Debian, being part of the "sudo" group means having root-like provileges.
The default /etc/sudoers config file ships a rule like
```
%sudo   ALL=(ALL:ALL) ALL
```
Even though my user is part of group sudo, the webfrontend doesn't list it as admin user.

Is there some special configuration necessary to make this work?
http://cockpit-project.org/guide/latest/privileges.html doesn't really go into detail here.

**Comment by stefwalter** [comment]
This needs work. At a minimum we need to recognize (and set) the sudo group on admin accounts.

We should auto-detect the presence of 'sudo' or 'wheel' group and treat either (when reading admin state) or both (when setting admin state).

**Comment by stefwalter** [comment]
This is exactly the sort of thing that would be caught by getting the integration tests running on Debian. Thankfully there is progress being made in #3138

**Comment by stefwalter** [comment]
@mbiebl What does polkit respect on Debian? Many things on linux use polkit (like systemd) and we only use sudo as a fallback to escalate privileges when nothing else is available. In addition the only time we can escalate privileges with sudo is when sudo is configured NOPASSWD (such as in the cloud).

Does Debian have a single concept of a group that makes a user an admin for both polkit and sudo? Or do we have to place users in both "wheel" (for polkit) and "sudo" (for sudo).

**Comment by mbiebl** [comment]
yes, that's what the sudo group is for. We set up a sudo config (as posted above) and in addition a
/etc/polkit-1/localauthority.conf.d/51-debian-sudo.conf with
```
[Configuration]
AdminIdentities=unix-group:sudo
```

**Comment by mbiebl** [comment]
One current Ubuntu this is
```
[Configuration]
AdminIdentities=unix-group:sudo;unix-group:admin
```
and
```
# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL
```

The "admin" group is the one traditionally used by Ubuntu to make users admins, the sudo group was added to sync with Debian.

**Comment by mbiebl** [comment]
@stefwalter is the wheel group currently hard-coded? Or how does cockpit decide when to grant a user admin privs?

**Comment by stefwalter** [comment]
> @stefwalter is the wheel group currently hard-coded? Or how does cockpit decide when to grant a user admin privs?

Cockpit does not decide to grant the user admin privileges (it uses polkit or in some cases sudo) for that. Remember that Cockpit doesn't (and shouldn't) run with root or elevated privileges. It runs with the privileges of the logged in user.

However Cockpit does currently use the "wheel" group to display whether a user has admin privileges or not. And that logic will need to change.
