### ISSUE TITLE
docker: distinguish between not installed and not running

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#3182]
Right now we only check if docker is running and offer to start it if it's not.

We should detect if it's installed and have the ui reflect that: maybe hide it?

**Comment by petervo** [comment]
Right now this isn't really an issue as the cockpit-docker package requires docker. https://github.com/cockpit-project/cockpit/blob/master/tools/cockpit.spec#L372 

No one should really have the docker package without docker  being installed. unless they specifically added it manually. We could of course change that an add this.

**Comment by stefwalter** [comment]
This is not currently a bug. Since cockpit-docker subpackage should depend on docker as @petervo says. However further work in this area is tracked here: https://trello.com/c/r05Yyvu5/241-lazy-installation-of-cockpit-modules
