### ISSUE TITLE
Kubernetes URL /api/v1beta3/watch generates 404

### ISSUE THREAD

**Issue by tedstirm** [cockpit-project/cockpit#3204]
I am running Kubernetes using the ([Vagrant Installation](http://kubernetes.io/v1.1/docs/getting-started-guides/vagrant.html)) and the Fedora Cockpit(file topology.min.js around line 829) is trying to access /api/v1beta3/watch which doesn't exist, so this results in constant 404 errors. I have tried the ([Vagrant Installation](http://kubernetes.io/v1.1/docs/getting-started-guides/vagrant.html)) on Release 1.1.2 and 1.2.0-alpha-3. The Fedora Cockpit in Release 1.2.0-alpha-3 was working for me last week, so I am not sure what has changed.

**Comment by stefwalter** [comment]
Which version of cockpit are you using?

**Comment by tedstirm** [comment]
I tried to find a way to get the version from the UI, but couldn't seem to find it. Is there a way to tell from the UI? When Kubenetes is installing it seems to be getting it from the following repo: https://copr.fedoraproject.org/coprs/sgallagh/cockpit-preview/repo/fedora-21/sgallagh-cockpit-preview-fedora-21.repo. In particular it is doing:
```
# Enable Fedora Cockpit on host to support Kubernetes administration
# Access it by going to <master-ip>:9090 and login as vagrant/vagrant
if ! which /usr/libexec/cockpit-ws &>/dev/null; then
  
  pushd /etc/yum.repos.d
    wget https://copr.fedoraproject.org/coprs/sgallagh/cockpit-preview/repo/fedora-21/sgallagh-cockpit-preview-fedora-21.repo
    yum install -y cockpit cockpit-kubernetes  
  popd

  systemctl enable cockpit.socket
  systemctl start cockpit.socket
fi
```
This is taken from kubernetes/cluster/vagrant/provision-master.sh

**Comment by stefwalter** [comment]
The latest version of Cockpit 0.84 versions behind the latest one. We stopped using v1beta3 in version 0.69.

Fedora 21 is no longer supported upstream now that Fedora 23 is out. The Cockpit project is no longer building Cockpit for Fedora 21 either in the COPR. You could build it from source, or from an source rpm. Alternatively, you could use Fedora 22 where the latest version of Cockpit is still being built in the COPR.
