### ISSUE TITLE
Can't access to terminal with new account

### ISSUE THREAD

**Issue by shannara** [cockpit-project/cockpit#3207]
In fresh CentOS 7 x64 install with cockpit after.
I create account in cockpit, when i connect with, terminal access doesn't work.
In journal i have this line:
    23:29 cockpit_pipe_write: assertion '!self->priv->closed' failed cockpit-bridge
    23:29 stdio: couldn't read: Bad file descriptor cockpit-bridge
    23:29 /bin/bash: couldn't read: Bad file descriptor cockpit-bridge
    23:25 value "-1" of type 'gint' is invalid or out of range for property 'pid' of type 'gint' cockpit-bridge

Output log from JS console:
http://pastebin.centos.org/36386/

But with root account, access on terminal work property.

Seem important note that:
I install CentOS 7 in virtual machine, and work property both with root and my new user (created from cockpit).

Why difference usage between virtual machine and physical ?

**Comment by stefwalter** [comment]
Which version of Cockpit is this? Is the version of Cockpit identical in the VM and on the physical machine?

**Comment by shannara** [comment]
Hi,

Yes it's same CentOS 7.1 x64 Cockpit 0.71.
CentOS's it's up to date.

**Comment by stefwalter** [comment]
From the log messages it looks like forkpty() is failing. I'll create a patch that will produce clearer messages for this failure case.

**Comment by shannara** [comment]
Ok, If need i can try cockpit with patch.
It's strange that VM work property and real machine not work.

**Comment by stefwalter** [comment]
@shannara Could you try the fix at #3212 and see what error message it produces after that? It should say: 

```
forkpty failed: something interesting here
```

**Comment by shannara** [comment]
I use cockpit packaged from rpm.
i need to use git version, how use it ?

**Comment by stefwalter** [comment]
There are many ways to build packages. But I'm working on a simple way for you to build them in #3214

**Comment by shannara** [comment]
I run this command

yum-builddep tools/cockpit.spec
yum install mock
./tools/make-rpms

Now rum mock command.

**Comment by shannara** [comment]
I have various rpm for fc22.
I remove cockpit packages and try install them.
Failed with required libsystemd.so.0.

**Comment by shannara** [comment]
I decide to compile Cockpit.

Result of test when try to launch terminal :  internal-error

In Logs from interface
forkpty failed: Operation not permitted

**Comment by stefwalter** [comment]
> I have various rpm for fc22. I remove cockpit packages and try install them. Failed with required libsystemd.so.0.

Yes, that's what I was trying to work on with #3214: An easy way for you to build the packages for system (and not for f22).

> I decide to compile Cockpit.

Great. Glad that worked.

> Result of test when try to launch terminal : internal-error
> 
> In Logs from interface
> forkpty failed: Operation not permitted

Okay good to know. Now we have the real error message. We need to figure out why this is happening. Could you try disabling SELinux temporarily? That'll give us a clue if it's an SELinux issue.

**Comment by shannara** [comment]
I switch to Permissive mode, normally SELINUX allow all but log rules needed.

Same error, but i show new errors with PAM

SYSLOG_IDENTIFIER cockpit-session
PAM adding faulty module: /usr/lib64/security/pam_reauthorize.so
PAM unable to dlopen(/usr/lib64/security/pam_reauthorize.so): /usr/lib64/security/pam_reauthorize.so: cannot open shared object file: No such file or directory

I disabled SELINUX and reboot, sames errors.

**Comment by stefwalter** [comment]
> I switch to Permissive mode, normally SELINUX allow all but log rules needed. Same error, but i show new errors with PAM

Okay. So the issue is not SELinux.

> SYSLOG_IDENTIFIER cockpit-session PAM adding faulty module: /usr/lib64/security/pam_reauthorize.so PAM unable to dlopen(/usr/lib64/security/pam_reauthorize.so): /usr/lib64/security/pam_reauthorize.so: cannot open shared object file: No such file or directory

This is not related.

What kind of VM is this that you're running cockpit in, where this error is occuring? How was the VM created?

**Comment by shannara** [comment]
Errors is present in real hardware server.
When work it's run in qemu VM.

**Comment by stefwalter** [comment]
I wish it was the other way around, then we could ship the VM over here and I could debug it.

I'm not aware of any reason that forkpty() should be failing on a stock CentOS 7.1 server.

**Comment by shannara** [comment]
Note: I also try sunday with fedora 23 Server, same error.
If i reinstall server with this release and compile cockpit, help you ?

**Comment by stefwalter** [comment]
This is very wierd. Thanks for helping debug the issue.

Would you be able to place a file like this at ```/usr/local/bin/cockpit-bridge``` and make it executable?

```
#!/bin/sh
strace -e fork,open,ioctl -o /tmp/strace-bridge.log /usr/bin/cockpit-bridge "$@"
```

A file called ```/tmp/strace-bridge.log``` should be created. So you would make the problem happen again, and we should see some relevant output in that file.

**Comment by stefwalter** [comment]
You will need strace installed for above to work

**Comment by shannara** [comment]
Nothing, it's normal :)
Log file is attached, i rename to txt because dot log denied.
[strace-bridge.txt](https://github.com/cockpit-project/cockpit/files/42719/strace-bridge.txt)

**Comment by shannara** [comment]
Hi,
In attachment find strace-bridge from VM when account work.
I use VirtualBox and CentOS 7.1 Minimal and Cockpit build from git to have same environment that my server.
[strace-bridge_vm.txt](https://github.com/cockpit-project/cockpit/files/45738/strace-bridge_vm.txt)

**Comment by wolfbill** [comment]
@shannara how's your problem going ?

**Comment by larskarlitski** [comment]
This looks like a stale issue. I cannot reproduce it and the original author hasn't responded to the last question. I'll close it, but feel free to reopen if you're still seeing this issue. Thanks!
