### ISSUE TITLE
Docker network support

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#3217]
According to this blog, Docker network is the new thing and container links is the old thing.
http://rethinkdb.com/blog/docker-networking/

I don't think links are deprecated per se (yet) though.
Network seems pretty straight forward and nice in general. No idea what a UI for it would look like yet.

**Comment by KKoukiou** [comment]
Closing this issue because the Docker plugin is being actively developed any longer.
Replacement should be https://github.com/cockpit-project/cockpit-podman/ so any RFEs should be opened on that repository.
