### ISSUE TITLE
do I trust a system once I've added it?

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#3219]
This came out mostly out of a desire to have a clean system for a demo, but stef said I should file it regardless.
If I add a system to my dashboard, then remove it and add it again, I don't get the "Do you really trust this system" part of the dialog. Is that a good behaviour?

**Comment by stefwalter** [comment]
Yes, once you've trusted a key for a given machine, removing it won't remove the key. That's how ssh behaves. But for demo purposes you can ```rm /var/lib/cockpit/known_hosts``` in order to reset trust.

**Comment by stefwalter** [comment]
I misunderstood this issue on IRC ... by the way.
