### ISSUE TITLE
domain: broken layout in join domain dialog

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#3222]
When attempting to join a domain, but it fails due to missing dependencies on the client, it informs you of the missing packages. Hitting the More-button breaks the layout of the dialog.
![screenshot from 2015-11-24 14-37-42](https://cloud.githubusercontent.com/assets/209895/11368273/2be70334-92b9-11e5-933b-0e3abb755976.png)

**Comment by stefwalter** [comment]
FWIW, if you install PackageKit it'll install the packages for you. This UI bug should still be fixed, however.

**Comment by andreasn** [comment]
oh, that's handy

**Comment by andreasn** [comment]
Sorry about the new pull request, I was unaware that I had to do a force push.
