### ISSUE TITLE
domain: incorrect password error should be styled differently

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#3223]
Should look similar to other incorrect passwords fields, such in the user dialogs.

![screenshot from 2015-11-24 14-40-40](https://cloud.githubusercontent.com/assets/209895/11368308/65df0a78-92b9-11e5-939c-b066195d8539.png)

**Comment by jogenderkota** [comment]
@dperpeet  I found this issue on the easyfix page. I know python and am new to open-source. I wish to work on this bug. Can you please give a few pointers here ! thanks :)

**Comment by dperpeet** [comment]
@jogenderkota this is a good place to start, let me know if you need help with this

You will probably have the best response rates on irc in #cockpit

**Comment by stefwalter** [comment]
See for info on how to bring up a local domain in order to develop this: https://github.com/cockpit-project/cockpit/blob/master/pkg/realmd/README.md

For info on what an error should look like, load the playground component and click on "Design Patterns" in the side bar, Click on 'Show Dialog' and then 'Error'

**Comment by stefwalter** [comment]
More info on how dialogs should look: https://github.com/cockpit-project/cockpit/wiki/HIG:-Dialogs

**Comment by andreasn** [comment]
For reference for what classes to use, check out either the "Create New Account"-dialog on the Accounts page in Cockpit (just set the Password and Confirm to different phrases) or the Patternfly documentation
http://www.patternfly.org/pattern-library/widgets/#forms

**Comment by thomasmckay** [comment]
![system cockpit example com](https://user-images.githubusercontent.com/338096/27433429-afdfed16-5722-11e7-8699-ddabaace2ee2.png)

@andreasn - The error is not always related to password so highlighting a field seems incorrect. I could reformat the message ("Failed to join the domain" is the message now) to be shown as above, though.

Thoughts?

**Comment by andreasn** [comment]
Oh, good call.
Do we have the logic to figure out why it failed to join the domain? What is the output under "More" there?
If it's a problem with the Domain Address that message should go under the Domain Address field I think.

**Comment by thomasmckay** [comment]
TBH, I think there may be a couple additional issues on the page:
1. When entering the domain address, a spinner is presented at some point (stopped typing?). If the address is incorrect there is no error/warning indication. If it does resolve then the "Authentication" choice box is presented. I'd suggest adding an explicit "Resolve" button or such before presenting any of the other fields, if that's an important first step.
2. Entering info into the "Administrator Password" fields, then switching to another auth choice and entering details there, then clicking join uses the admin password fields. This is confusing and incorrect.
3. Clicking the "More" displays the details but hides the text so one cannot choose a "Less" option. Not critical but just feels a bit odd when using.

As for the "More" details, the message indicates "couldn't authenticate" which is generic for either an incorrect username or password. Personally I'd leave things as they are except perhaps coloring the failed red.

**Comment by andreasn** [comment]
So let's go with an inline error notification for now, highlighting that there was an error somewhere on the input. As we discussed, parsing the realmd output is a bit too unreliable and fiddly to be able to match up the correct fields with the error messages.

**Comment by andreasn** [comment]
For the additional issues you ran into, I agree that they are working a bit wonky. Let's do those as separate issues.
