### ISSUE TITLE
Restarting Docker containers doesn't specify timeout, resulting in quick SIGKILL

### ISSUE THREAD

**Issue by AHelper** [cockpit-project/cockpit#3230]
Been dealing with data lost/corruption from containers not being allowed to cleanly shut down when being restarted. 

From `docker restart` documentation, the default timeout if not specified is 10 seconds (same with `docker stop`).  Stopping a container defaults to 10 seconds [in cockpit](https://github.com/cockpit-project/cockpit/blob/master/pkg/docker/client.js#L422), but restart [doesn't specify a timeout](https://github.com/cockpit-project/cockpit/blob/master/pkg/docker/client.js#L439), which causes docker to nearly instantly force a restart with SIGKILL:
```
Nov 24 17:34:58 host1 docker[1422]: time="2015-11-24T17:34:58.706261844-06:00" level=info msg="POST /v1.12/containers/417d490561a5b6d336d29c3df6061813a83084c6cf32ebbd9984979495f44e10/restart"
Nov 24 17:34:58 host1 docker[1422]: time="2015-11-24T17:34:58.706651337-06:00" level=info msg="Container 417d490561a5b6d336d29c3df6061813a83084c6cf32ebbd9984979495f44e10 failed to exit within 0 seconds of SIGTERM - using the force"
```

**Comment by stefwalter** [comment]
Nice catch. Are you interested in providing a patch for this? If so you probably would make the restart call more like the create call in the next function.

**Comment by AHelper** [comment]
I am, I was planning on building from source and making a patch the next day.  Should I go ahead and have restart accept a timeout, using default if not provided, like with stop? (I didn't see stop being invoked with a timeout, but hey, that functionality could be added in the future)

**Comment by stefwalter** [comment]
Yes, that would be great. Agree that it would be good to invoke both stop and restart with a timeout.The docker manual page seems to say 10 seconds is a good default, right?

**Comment by AHelper** [comment]
Correct, 10 seconds seem to work.
