### ISSUE TITLE
RAID 1 Creation Error

### ISSUE THREAD

**Issue by darksaboteur** [cockpit-project/cockpit#3231]
When attempting to create a raid1 array the following error is received 
"Chunk must be zero for level 'raid1'"
 but there is no option available to select zero.

There is also a typo in the RAID level selection drop down for "AID 10 (Stripe Of Mirrors)"

I am running Fedora 23 with Cockpit 0.83-1.fc23 on 64Bit

**Comment by petervo** [comment]
This was fixed in #3124 and is available with version 0.84.
