### ISSUE TITLE
deleting a user that is used by another process silently fails

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#3234]
I was trying to delete a user from my system.
I went to the users page and pressed the Delete button.
It popped up the dialog asking me if I wanted to also delete the users files.
I pressed Delete in the dialog
Nothing happened.

This is the error I got from the journal:
userdel: user andreasn is currently used by process 4838

**Comment by andreasn** [comment]
(I was logged in as another user, and not andreasn btw)

**Comment by stefwalter** [comment]
Could you describe what should happen instead?

**Comment by andreasn** [comment]
I'm not quite sure, but one alternative would be to show a message about this in the dialog where we confirm to delete the files of the user (since we show that dialog anyway).
"This user is currently logged in and is running processes. Are you sure you want to delete the user?"
(If the above is a correct description of the situation)

**Comment by FireDrunk** [comment]
I've looked into the issue, and after 2 hours i stopped. The cockpit.spawn() works fine, and even goes into the .fail() as expected. The paramters passed down to the method are also properly filled with the exitcode ( 8 ).

The weird thing is, that i cannot the the .fail() to spawn the dialog. And i can't figure out why.
Mayby it has something to do that this is all being setup in the :apply of the .prototype of PageAccountConfirmDelete class.

But i don't know enough of the data structure to further look into it.
One thing i can confirm is that the script fails correctly, it's just a visual javascript bug.

**Comment by stefan-wolfsheimer** [comment]
When adding the error popup to /user/index.html  a popup is shown when userdel fails.
However, the error message is not very helpful:
"/usr/sbin/userdel exited with code 8"
It should display something like: "userdel: user hello is currently used by process 6331".
Is this a separate issue?
