### ISSUE TITLE
test: vm-prep insufficient in some cases

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#3235]
One of vm-prep's jobs is to adjust qemu's bridge.conf.

Without the correct entry, starting a vm will fail with
```
libvirt: QEMU Driver error : failed to retrieve file descriptor for interface: Transport endpoint is not connected
```

On a Red Hat Enterprise Linux system I needed to add `allow cockpit1` to `/etc/qemu-kvm/bridge.conf`, while the script vm-prep only added it to `/etc/qemu/bridge.conf`

**Comment by stefwalter** [comment]
There's a check in vm-prep for that other file, but it only adds it to the first one it finds.

**Comment by dperpeet** [comment]
replaced by a real world case in #3753
