### ISSUE TITLE
test: vm creation will fail if host doesn't have enough memory

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#3236]
We could add a sanity check to vm-prep or testsuite-prepare to see if the host has enough memory. In the case of vm-build, we could reduce the memory if necessary at the cost of runtime performance.

Relevant error:
```
libvirt.libvirtError: internal error: process exited while connecting to monitor: Cannot set up guest memory 'pc.ram': Cannot allocate memory
```

**Comment by stefwalter** [comment]
How much is not enough memory?

**Comment by dperpeet** [comment]
One good pointer is host memory < guest memory. Maybe we can also catch that error in a smarter fashion and display a sane error message.

**Comment by stefwalter** [comment]
Does the error above get displayed? Because it's pretty clear. I don't think our tests need the polish of Cockpit itself. Obviously if the above message is hidden in the journal somewhere, then we should work to surface it.

**Comment by stefwalter** [comment]
I don't think this is a bug if the error above gets displayed. It's informative enough.
