### ISSUE TITLE
dns entry text box is too short

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#3253]
![screenshot from 2015-11-27 16-00-23](https://cloud.githubusercontent.com/assets/209895/11443768/04b98afc-9520-11e5-9b82-92beb0e0c528.png)

**Comment by andreasn** [comment]
This could be fixed either by giving the td surrounding it width: 100%;
Or to set the width of the input form-control to width: 524px;
For that there need to be some class or id to attach it to though (unless we want to go for some nth-child thing, but that would break easily)

**Comment by FireDrunk** [comment]
I've tried either of those options but they both break the "Routes" UI.
It seems that the [Remove] Button messes it all up. The size of the encapsulating td is larger than it should be (105px vs 26px)

![cockpit_dns_bug](https://cloud.githubusercontent.com/assets/6359704/11913878/e27f14c0-a672-11e5-84a5-86202e7a41e2.PNG)

**Comment by FireDrunk** [comment]
Screenshot of breaking:

![screenshot from 2015-12-19 17-00-58](https://cloud.githubusercontent.com/assets/6359704/11913886/3ad4aa72-a673-11e5-95eb-8a6dfb57f903.png)

**Comment by stefwalter** [comment]
@andreasn would be able to help with the CSS here

**Comment by shameempk** [comment]
I tried with `:last-child` selector for the `td` containing the button. Assigned button width +1 px.
Screenshot:
![selection_001](https://cloud.githubusercontent.com/assets/8086146/13982642/3b635d38-f111-11e5-94dc-eae992d1a744.png)

**Comment by shameempk** [comment]
@andreasn will above fix mess with anything else?

**Comment by stefwalter** [comment]
@shameempk Don't be shy about opening a github pull request with your change. That'll make it easier for @andreasn to examine and try out.
