### ISSUE TITLE
Remove no-forwarding error

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#3269]
We now have more details about what auth methods are tried and their results. And it doesn't make a lot of sense when public-key auth is involved. Unless anyone has any objections, removing this error code will also help clean things up.

**Comment by stefwalter** [comment]
Makes sense to me. What about the case where GSSAPI is present but cannot be forwarded? Is there a good error code for that?

**Comment by petervo** [comment]
What about putting that as the value for gssapi-mic on auth-method-results? Assuming I'm able to find a way to properly detect it.

**Comment by stefwalter** [comment]
> What about putting that as the value for gssapi-mic on auth-method-results? Assuming I'm able to find a way to properly detect it.

Sounds good.

**Comment by mvollmer** [comment]
What about also removing `authentication-not-supported`?

**Comment by mvollmer** [comment]
> What about also removing authentication-not-supported?

Or maybe change its meaning to "Cockpit can never login to this server no matter which keys, passwords, or tickets you give to it.  You must change the server configuration somehow to be able to login."
