### ISSUE TITLE
No CPU, Memory Graphs on Kubernetes

### ISSUE THREAD

**Issue by brockoffdev** [cockpit-project/cockpit#3270]
Hi all-

I'm on CentOS 7, and have deployed version 0.85 to my system.  Everything is working very well, save for one thing: the Kubernetes cluster graphs (CPU, Memory, Network, etc.) are not displaying correctly (note that all other graphs thus far do).  The actual Graph panels do display, but no graphs are generated.  The actual Kubernetes API communication does appear to be working properly, as I can deploy manifests, see info on the cluster, etc. At first I had thought this may have been an SELinux issue, however after disabling SELinux I still am seeing the same issue.  I also ensured to install cockpit and cockpit-kubernetes on all kube minions, but did not have any luck.  The Debug logs do not show any errors, so sorry I can't be of much assistance in that.  

Any thoughts on the problem?  

...also, just as an aside, we should work on allowing YAML manifest submission via the Kubernetes plugin, rather than just JSON, which Google seems to be pushing moving forward.

**Comment by dperpeet** [comment]
Did you get pre-built packages (if so, do you have a link) or did you build from git (if so, which commit - 0.85 tag)?

**Comment by brockoffdev** [comment]
I actually got it via a pre-built package just for testing, however I also compiled the app myself via the 0.85 tag. This also manifested in 0.84, so I'm not sure if anyone else has successfully seen this working.  Here is a link to the pre-built package:

https://copr-be.cloud.fedoraproject.org/results/@cockpit/cockpit-preview/epel-7-x86_64/

**Comment by stefwalter** [comment]
I wonder if perhaps the cAdvisor stuff is disabled in the kubernetes you're running. I've seen several lately where that's the case. I'll try to do some more research here.

**Comment by brockoffdev** [comment]
So I can verify that I have cadvisor running on my nodes at port 4194...I can definitely reach each one and retrieve api information, so not sure if that helps limit the issue.

**Comment by jkaurredhat** [comment]
I am seeing a similar issue when integrating Openshift with cockpit.   In the "Cluster" (kubernetes) part, when we select a project (or when "all projects" is selected by default), then an empty graph is displayed . It looks like it should display CPU, Memory and  Network data, but nothing is displayed.  

rpm -qa | grep cockpit
cockpit-kubernetes-0.93-3.el7.x86_64
cockpit-storaged-0.93-3.el7.noarch
cockpit-ws-0.93-3.el7.x86_64
cockpit-shell-0.93-3.el7.noarch
cockpit-0.93-3.el7.x86_64
cockpit-bridge-0.93-3.el7.x86_64
cockpit-docker-0.93-3.el7.x86_64

while the graphs are correctly seen under machines -> containers.

**Comment by stefwalter** [comment]
Openshift has removed the cadvisor stuff, and doesn't run it. To fix this we should remove those graphs when cadvisor is not available. Or replace it with other info.

**Comment by jkaurredhat** [comment]
Thanks..Understood.. is it similar to data we see in the graphs that are seen under machines -> containers.

How can we view the resources used for containers deployed in Openshift

**Comment by psteyn** [comment]
Any update on this?

**Comment by petervo** [comment]
The graph panels are not displayed on openshift. They have not been replaced with anything else yet. Metrics are available for the nodes on the node pages, but nothing on the container level.

**Comment by psteyn** [comment]
Tnx.  FYI, I worked around this by installing cadvisor on the actual nodes via yum.  This caused the graph panel to populate.  Not sure if this is desired behavior, but it left me happy.

**Comment by larskarlitski** [comment]
cockpit-kubernetes hasn't seen much development in quite some time. Looks like people have moved on to other tools. Closing this old bug. Sorry.
