### ISSUE TITLE
Containers: no proper image titles in Container list

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#3273]
I no longer get any proper image names under Image under the container listing on the Containers page. Instead they get these random strings, like 05a4abb906277a83238d6b6be1f1be613be76c13f49f55f4715e512134d07393 and e3224345b21be0882d4cc85794809a2b613f6a1044279fa21d67bdedcf92e454

This is a screenshot from today:
![screenshot from 2015-12-03 12-54-17](https://cloud.githubusercontent.com/assets/209895/11559952/1bcc4382-99bd-11e5-8910-825ae7f60607.png)

Compare with the screenshot on the project website:
![image](http://cockpit-project.org/images/screenshot-docker.png)

**Comment by dperpeet** [comment]
Is this on F23? I can confirm this to be the case with current master on F23 as well.

**Comment by dperpeet** [comment]
Maybe we need to update the version of the docker API we use.

**Comment by andreasn** [comment]
Yep, F23 here
