### ISSUE TITLE
Connect an other server with SSH port different than 22

### ISSUE THREAD

**Issue by Sutat** [cockpit-project/cockpit#3280]
Hello,

I installed cockpit on one of my servers (first).
I installed cockpit on an other one (**second**).

I tried to add the **second** server to the first cockpit UI.
I had the error "no-host", I think the problem is my **second** server SSH listen to the *443* port, and not the default SSH's one (port 22).

Do you know how I can connect my **second** server on my first one ?
I tried to add : 
* \<ip\>
* \<ip\>:*443*
* \<ip\>/*443*

Is it something we can do ?

**Comment by stefwalter** [comment]
Yes this is possible. Cockpit 0.85 or later supports this feature. You can see:

http://stef.thewalter.net/cockpit-0.85.html

**Comment by gitthangbaby** [comment]
None of the current methods (hosntame, IP, alias, ssh://) work for me, probably because alias name = hostname. In that case i recommend adding dot or domain name:
`hostname.:port`
