### ISSUE TITLE
cockpit installs debug data for things in /usr/share

### ISSUE THREAD

**Issue by tgurr** [cockpit-project/cockpit#3288]
[cockpit_installed_files.txt](https://github.com/cockpit-project/cockpit/files/53836/cockpit_installed_files.txt)

Please see the attached list of installed files for cockpit 0.86 (css/js/html/less/mustache/sh files) installed to /usr/x86_64-pc-linux-gnu/src/debug/usr/share/cockpit/*.

**Comment by stefwalter** [comment]
Are you packaging Cockpit? When packaging these files should be moved to an appropriate debuginfo package.

**Comment by tgurr** [comment]
Yes, I've been packaging cockpit on Exherbo Linux for quite a while now: https://git.exherbo.org/net.git/log/?qt=grep&q=cockpit

I didn't care/notice about the files, but someone spotted it in our Jenkins/Gerrit CI. Since we're a source-based distribution we don't have separate packages for debug stuff but have it handled by our package manager (preserve/strip/split/compress).

It's working as intended for the lib and bin stuff, I wondered if it makes sense for stuff in /usr/share at all and thought it's a bug to even create debug stuff for these(?). For sure I can just delete these files after the build so they don't get installed.

**Comment by stefwalter** [comment]
> It's working as intended for the lib and bin stuff, I wondered if it makes sense for stuff in /usr/share at all and thought it's a bug to even create debug stuff for these(?). 

We had to manually teach our packaging system (RPMS) how to deal with the debug files for javascript, since it had no idea what to do with them.

> For sure I can just delete these files after the build so they don't get installed.

If you're not going to use/package them, then yes, that's what I would suggest. I'll post something to cockpit-devel explaining this for reference.
