### ISSUE TITLE
Trying to join a existing but not-supported domain gives bad error message

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#3291]
For example, setting `[providers] sssd = no` in the realmd config leads to this:

![testrealms-testnotsupported-xxx](https://cloud.githubusercontent.com/assets/3228183/11650804/d488ec42-9d94-11e5-8ec9-26bc45d38895.png)

Also, we should probably show a error indicator next to the address, similar to the one for domains that are not found at all.

**Comment by mvollmer** [comment]
See #3292 for a test case.

**Comment by stefwalter** [comment]
If the KerberosMembership interface is not present, we should have an intelligent error message.
