### ISSUE TITLE
Patching bower_components is not straightforward

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#3297]
Packagers might want to patch the files we acquire via bower, such a jquery, bootstrap, angular, patternfly, and others.

**Comment by stefwalter** [comment]
Ideally they wouldn't patch the files directly. They need to setup a local bower repo with their desired versions, and then 'bower update' them into place.

However as a prerequisite, we need to stop patching the files ourselves, or at least do it during a build step.

**Comment by stefwalter** [comment]
How to use a private bower dependency: http://www.frontendjunkie.com/2014/01/using-bower-as-package-management-tool.html

**Comment by stefwalter** [comment]
This is now fixed, we just use simple bower components, and any patches necessary are done while bundling into our installable files.
