### ISSUE TITLE
Improve time specification for shutdown / restart

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#33]
Right now, when specifying a exact point in time when to do a shutdown or restart (as opposed to specifying a delay), the UI mimics the venerable /usr/bin/shutdown" interface.

We should have a nice date / time picker there, with calendar and everything.

**Comment by Aayush-Kasurde** [comment]
Do we need to include a third-party plugin for datepicker like jquery-ui datepicker or custom datepicker for this functionality ?

**Comment by andreasn** [comment]
If that's the easiest way to do it and the license is right, it would be great to be able to reuse that.

**Comment by stefwalter** [comment]
It would be good to ask the Patternfly guys what they have in mind WRT date pickers ... so we don't diverge further than we already have.

‘#patternfly’ on chat.freenode.net.

**Comment by Aayush-Kasurde** [comment]
Ok, Let us discuss this with #patternfly, I don't see any datepicker in patternfly source.

**Comment by andreasn** [comment]
Sent a mail to patternfly-list about it:
https://www.redhat.com/archives/patternfly/2015-January/msg00006.html
