### ISSUE TITLE
vm-prep does not work on Debian

### ISSUE THREAD

**Issue by fsateler** [cockpit-project/cockpit#3319]
vm-prep assumes it is running on a fedora system apparently. On debian
- There is no `/etc/sysconfig/network-scripts/`. I think the proper solution should be to edit NM configuration (unmanaged-devices in [keyfile]).
- Selinux is not enabled by default, so making the policy is not necessary. I suggest checking with `getenforce`, if non existing or status is Disabled, then it should not install the policy.

**Comment by martinpitt** [comment]
This is obsolete, vm-prep is gone.
