### ISSUE TITLE
Large disks on 32bit system

### ISSUE THREAD

**Issue by ilventu** [cockpit-project/cockpit#3325]
Running Cockpit on Linux raspberry 4.1.13-1-ARCH based on ARMv7 Processor rev 5 (v7l) I get this strange behavior:
![screenshot - 12122015 - 21 26 34](https://cloud.githubusercontent.com/assets/16270846/11763758/115b0fbc-a117-11e5-9b11-18863c1afa99.png)
/mnt/usb1 is "TOSHIBA DT01ACA300" and /mnt/usb2 "TOSHIBA External USB 3.0". It seems an overflow problem.

Ciao
Andrea

**Comment by andreasn** [comment]
I've seen this one too

**Comment by mvollmer** [comment]
I belive this was fixed with 73820b6, released in cockpit 0.91.

**Comment by ilventu** [comment]
It works! (tested on 0.93)
