### ISSUE TITLE
Extend cockpit.permissions to work with polkit actions

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#3341]
So that we can use it for pkg/networkmanager and maybe others.

**Comment by petervo** [comment]
@mvollmer, we did try this before but ran into a couple issues, see previous discussion here: https://github.com/cockpit-project/cockpit/pull/1645#issuecomment-71052644. I still have that old code around somewhere if we do pick this up again.

**Comment by martinpitt** [comment]
This was done in a more generic way in commit 168f819ebd09ddc220097915aecd3cc829c4a8bc
