### ISSUE TITLE
known issues could be more specific

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#3347]
By
- match against the journal and the JS console output.
- being limited to a given image

We could have `test/naughty-fedora-23` and `test/naughty-debian` in addition to `test/naughty`.

**Comment by stefwalter** [comment]
The latter part has been implemented.

**Comment by stefwalter** [comment]
Added journal support in #3520

**Comment by stefwalter** [comment]
This is solved. We have:

 * Limited to images
 * Javascript console output.
 * Journal output.
