### ISSUE TITLE
journal: regression in systemd breaks --follow again

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#3361]
something like `journalctl --follow -- _SYSTEMD_UNIT=something.service` will fail again in systemd-222-10.fc23.x86_64 - it worked in systemd-222-8.fc23.x86_64

New images are affected by this (fedora-23, fedora-testing, fedora-atomic)

**Comment by dperpeet** [comment]
bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1292805

**Comment by stefwalter** [comment]
Is this fixed upstream now?

**Comment by stefwalter** [comment]
No reply from reporter. Closing.
