### ISSUE TITLE
Predictable URL for OS Updates

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#3363]
Operating system updates should have a predictable URL that shows a system applicable UI depending on the system we connect to. Currently the ostree stuff shows at /ostree, which wouldn't apply to package based systems.

**Comment by petervo** [comment]
What would you like? software?

**Comment by stefwalter** [comment]
@andreasn @mvollmer What do you think? I would say 'updates' or 'software/updates' what do you guys think?
