### ISSUE TITLE
Vagrant box is using a very small root partition

### ISSUE THREAD

**Issue by FireDrunk** [cockpit-project/cockpit#3377]
The current mentioned base box "arguello/fedora-22" is using a 3GB root partition.
The base box is 550MB which is fine.
But the default provisioning script installs so many components that the root partition fills up to 60%.
If someone were to do a dnf update inside, it's over.

I've looked into finding another base box for Fedora 22, but couldn't find one that supports the Libvirt provider.

There are numerous Fedora 22 boxes which run on Virtualbox, so we could switch to those, but it's up to you guys.

EDIT: After doing a complete vagrant destroy -> vagrant up -> dnf update cycle, my VM has 1.1GB free. So this probably is less of an issue than i first thought...

**Comment by stefwalter** [comment]
Hmmm, if it's 1G free it seems like that's fine no? The vagrant VM should only be used for running cockpit. But maybe we can also ask dnf to clear it's cache to make more room? WDYT?

**Comment by FireDrunk** [comment]
I dunno, i think 5GB's is not that much these days, even on SSD's, maybe we can ask Arguello nicely to edit the box to gives us a little more headroom. Doesn't hurt anybody...

I've built a Vagrantfile for VirtualBox:
https://github.com/FireDrunk/cockpit/blob/vagrant-virtualbox/Vagrantfile

I can do a pull request if you want.

**Comment by dperpeet** [comment]
We changed the Vagrant base image to [fedora-23-cloud-base](https://github.com/cockpit-project/cockpit/blob/e251c04bfeb0c2e27c260adf686dcfce7f92c2cb/Vagrantfile#L8), is this better?

**Comment by stefwalter** [comment]
@FireDrunk Do you have a moment to try again as per @deperpeet's suggestion?

**Comment by stefwalter** [comment]
Haven't received a response back from reporter. Closing the bug.
