### ISSUE TITLE
Confusing 'user' behavior when adding machine

### ISSUE THREAD

**Issue by hrumph** [cockpit-project/cockpit#3379]
Hi,
I'm not sure if anything I am complaining about will be considered to be a bug or not, but nevertheless here goes:

Let's suppose you are user jsmith on the master machine and you've got another jsmith account on another machine albeit with a different password, and suppose that you want to make the other machine a slave machine. It won't connect at first because it will will try to use your password from the master machine which won't work. So a dialog comes up saying "Couldn't connect to the machine: Login Failed" Next let's suppose we log in now, and suppose we enter in our user name in the "User Name" field and log in (this is probably a mistake in most cases but suppose we do it anyway). At this point the name we entered becomes hard-set in the machines.json file on the master machine.

Now suppose we log off and log back in. Now it won't connect again because it doesn't even bother to try your password _even though_ the user name set in the machines.json file is the same as the one we logged in cockpit with, so this may be a point of confusion for some users. Now suppose we hit troubleshoot again, and perhaps we decide that perhaps the solution is to synchronise users (after all why is it inviting us to do this if it's not going to help?).

At the bottom of the SYnchronize users dialog is a User Name/Password field pair. Telling us we must provide authorisation. Although it makes sense that it has to be the slave machine we need to authorise on, it's not telling us that anywhere. So let's suppose we check on the jsmith user, jsmith and the slave machine password for jsmith, then jsmith on the slave machine will end up with the master machine's password. However we still end up with a "Couldn't Connect to the Machine" dialog. This is once again because the the user name is still set in machines.json and it won't bother attempting to try the jsmith password in this case.

I realise that I have failed to specificy any definite bugs, but maybe two or three things could be done. 

1) if a user name find its way into machines.json and if the user name matches the one you logged into cockpit with, then maybe it should attempt to connect with the password you logged in with.

2) Even though there is an info popup explaining things next to the User Name field, it would be clearer (even though it would be visually less appealing I suppose), if there was a check box and a text field. By checking the checkbox you would be enabling the field, otherwise the field would be blank. This will stop users from just unthinkingly entering a user name.

3)In the synchronize users dialog it would be nice if it stated that we were authorising on the slave machine.

**Comment by stefwalter** [comment]
I think all three points are valid. Very good. @petervo What do you think? You have a better understanding of the details here.

**Comment by petervo** [comment]
I'll do 1 and 3. 2 I'll need some design help with.

**Comment by mvollmer** [comment]
If I understand things right, with 1 fixed, entering a user name does not lead to confusing behavior anymore.
