### ISSUE TITLE
Run cockpit with vagrant on Mac OS

### ISSUE THREAD

**Issue by smirnovigor** [cockpit-project/cockpit#3405]
I've gave up to run cockpit with vagrant on Mac os. The main problem was to install vagrant libvirt provider.
I also tried to run it within fedora box with no result. 
Is there other way to run cockpit?

**Comment by stefwalter** [comment]
Do you have suggested changes to the Vagrantfile that you could make into a pull request? I don't have a Mac, but someone who does needs to help make the necessary changes to the Vagrantfile

**Comment by smirnovigor** [comment]
I'm new to vagrant, but it seems that ``rarguello/fedora-22`` should be changed to different one, that runs with a ``virtualbox`` provider and has a nfs configuration

**Comment by stefwalter** [comment]
I found some Fedora 23 images, that I posted in #3416. I'm  trying them out now. I don't have virtualbox or libvirt, so I'll need your help tying off any loose ends.

**Comment by smirnovigor** [comment]
thank you Stef
