### ISSUE TITLE
No service install for cockpit-ws

### ISSUE THREAD

**Issue by sudhaker** [cockpit-project/cockpit#3413]
My fresh CentOS 7.2 installation doesn't have the "Install" section in "/usr/lib/systemd/system/cockpit.service"

[Install]
WantedBy=multi-user.target

https://github.com/cockpit-project/cockpit/blob/master/src/ws/cockpit.service.in

Did we miss this on purpose? If not, please add this so that "systemctl enable" can work.

**Comment by stefwalter** [comment]
Cockpit is socket activated, and the service doesn't need to be running on boot. To enable cockpit on boot use:

```
$ sudo systemctl enable cockpit.socket
```

I've added some documentation on this to the guide in #3414
