### ISSUE TITLE
docker: unable to change resource limits

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#3439]
Hi,
When testing container I've found that via cockpit web iface I'm unable to change resource limits for docker instance.
I've clicked on button change resource limits, then I've changed CPU shares or memory, and these changes are not set after click to button "change" still same values.
my machine is F-23 (cockpit WIP instance builded from master)

**Comment by stefwalter** [comment]
We should remove the UI to change resource limits for a running container. Docker doesn't support this.
