### ISSUE TITLE
Image Registry: Non-graceful behavior if connection to the registry is lost

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#3449]
E.g. if the openshift instance closes, all the views just become empty.
The API issues a lot of messages on the console. I would expect the curtain page and a note that Cockpit is trying to connect to the registry.
![screenshot from 2016-01-12 12 50 10](https://cloud.githubusercontent.com/assets/8711649/12262890/434220f2-b92b-11e5-9704-eea50c37170c.png)

**Comment by martinpitt** [comment]
This hasn't come up as a major complaint elsewhere, and our kubernetes UI is on maintenance mode.
