### ISSUE TITLE
add ssh key dialog needs a bit of helper text

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#3454]
To answer the question of "what should I do with this text entry"
![screenshot from 2016-01-13 13-20-21](https://cloud.githubusercontent.com/assets/209895/12294170/863d3e6e-b9f8-11e5-8fe4-ddbb253e7a15.png)

**Comment by andreasn** [comment]
How about the label: "Paste the contents of your public ssh key file here"

**Comment by abhishekgupta5** [comment]
Hi andreasn, I would like to work on it. I don't know which file to alter though ?

**Comment by stefwalter** [comment]
```
$ git grep 'Add public key'
pkg/users/index.html:          <h4 class="modal-title" translatable="yes">Add public key</h4>
```

**Comment by stefwalter** [comment]
@abhishekgupta5 Thanks!

**Comment by abhishekgupta5** [comment]
@stefwalter Update me if I missed something. Waiting for that PR to be merged
