### ISSUE TITLE
cockpit-kubernetes Security Issue when changing Services from Overview Page

### ISSUE THREAD

**Issue by ahuffman** [cockpit-project/cockpit#3462]
I've run chmod 700 /bin/kubectl to prevent non-privileged users from interacting with the kubernetes cluster via cockpit-kubernetes.
 
Regardless of the user logged into cockpit, the user can still modify services from the Overview page of the cockpit-kubernetes plug-in even though there is no access for the given user to the kubectl binary on the system.

This creates a major access control and security issue with the kubernetes cluster environment, as a user with no access to the binary should not be able to interact with the cluster through cockpit.

From the containers page, the user is unable to get to the individual container's shell when the binary's permissions have been changed, which is appropriate.  The user in this case gets a 'couldn't execute: kubectl: Permission denieddisconnected' message.  This should be the behavior from the Overview page when attempting to change the number of container instances (adjust.)

**Comment by petervo** [comment]
Cockpit mainly communicates with kubernetes via it's REST API not by using kubectl. Just chmoding kubectl won't stop users from changing things via the REST API directly and cockpit reflects this. To properly project the kube API see http://kubernetes.io/v1.1/docs/admin/authorization.html. 

Cockpit only uses kubectl to get the users credentials when initialing connecting to the api. Right now log and shell do as well, until #2911 gets merged.

**Comment by ahuffman** [comment]
I have already implemented ABAC on my cluster, and furthermore how would cockpit-kubernetes determine what user I'm accessing the apiserver when I've logged into cockpit on the master server that is running the kube-apiserver.  This is a serious security concern.  I'm logged into cockpit as a user that has no account on the apiserver, and no access to the kubectl binary.  I can scale all of my services, which is very bad, as I mentioned previously.

**Comment by petervo** [comment]
Cockpit doesn't have/store any special credentials for talking to kubernetes. First it runs kubectl as the logged in user, if the user has a .kube/config file then that returns their credentials. If that fails then it tries the following ports on localhost, 8080, 8443, 6443 without any credentials. 

Try issuing a curl request to your api server from localhost as the same user logged into cockpit. One of those ports must be open and accessible.

**Comment by ahuffman** [comment]
Yes, 8080 is the default insecure port.  The kubelets are configured with --master=http://<IP>:8080.  So on the master I can curl http://localhost:8080.  So it sounds like I want to shut down the insecure port altogether and reconfigure the nodes.

I've been following the kubernetes documentation, and since it leaves a lot of room for clarity, I have not seen an example of how to configure my nodes to use the secure port only, and furthermore, how would I configure the master so that someone logging in with cockpit would not have access to scaling services on the cluster?  I do have ABAC setup and have all the keys in place already for my master/apiserver.

This is very confusing, so sorry if I'm off base in this issue.  I am using the kubernetes packages shipped with RHEL7 which are listed as version 1.0.3-0.1.gitb9a88a7.el7.

**Comment by petervo** [comment]
Yeah, this is a bit of a known problem, you can set it to 0 but that can cause other issues, see https://github.com/kubernetes/kubernetes/issues/13598.

The easiest work around for now would be to not expose cockpit from your master but use cockpit on a different server, where the accounts that should be allowed to talk to the api server have a valid .kube/config file in their home directory. If you want to use cockpit to administer other aspects of the master server, you can add it as a secondary server via the dashboard, and no kubernetes endpoints will be exposed via the UI.

@stefwalter do you have a better suggestion? Or do you think we need to change anything in our connecting code to deal with this rather than waiting for kubernetes to solve it?

**Comment by petervo** [comment]
Actually, even easier work around, change --insecure-port to something other than 8080, then cockpit won't connect to kubernetes for users without a .kube/config. Of course users can still ssh in and issue http calls on their own, but at least cockpit won't be exposing it.

**Comment by stefwalter** [comment]
Cockpit has identical access to users who log into the system. It does not and cannot confer more privileges. Anything users can do through Cockpit, can be done by those users logging in any other way, such as in an SSH terminal.

If Cockpit can scale services, or perform X with kubernetes, it means that the logged in user can. 

kubectl is only one possible way to interact with the kubernetes REST API. Most other tools interact with that REST API directly, and do not involve kubectl.

This is not a Cockpit security issue.

I'm going to close this bug report. But feel free to continue to look for a solution here in the discussion area, or join us on IRC at #cockpit on FreeNode if you would like more help on solving this for your use case.

**Comment by ahuffman** [comment]
I think @petervo that using the .kube/config for every user is a bit unwieldy since in an enterprise environment you typically make use of NIS which we are in this case, to allow many users access which would/could change at any time.  I think if the cockpit-kubernetes plug-in made direct use of kubectl instead of the REST API you'd at least be able to limit cluster access to users by doing what I attempted and limit access to the binary, instead of attempting to configure each user's api access.  

In some cases we only want users to be able to get into the cockpit-kubernetes UI to be able to look at the cluster health and check on the topology, and not necessarily be able to change anything in the cluster.  

Like I mentioned in my previous post, limiting kubectl's ACL to the root group prohibits the cockpit user from accessing the container's shell, which is perfect.  I still feel this is a design flaw since kubernetes' authentication and authorization plug-ins are still very much works in progress.  By making use of the REST API you've introduced a hard to configure and hard to lock down scenario.

**Comment by petervo** [comment]
Relying on solely on kubectl is not an option. Cockpit needs to be able to access kubernetes in environments where kubectl is not available. Work is underway to make the current log and shell behavior work with websockets instead.

I understand your concerns but if the API is open users will be able to access whether that is through cockpit or not.

**Comment by ahuffman** [comment]
Why not add a 2nd layer of authentication on the "Cluster" tab, that takes the kubernetes apiserver's username, token, and cert or a drop-down that the user could choose the auth method such as simple http auth etc and then make the REST API connections based upon that log-in info?  That seems more sane than just reaching out and making a connection to the API by trying several methods until cockpit gets a valid hit.

**Comment by stefwalter** [comment]
@Users can simply access the REST API with curl from the command line, and access it on port 8080 directly. Shutting down kubectl or cockpit has no real effect unless you shutdown kubernetes (or don't let users log into your kubernetes master).

For example, this deletes a pod, just substitute the name at the end of the URL:

     $ curl -k -v -XDELETE http://localhost:8080/api/v1/namespaces/default/pods/my-test-pod

**Comment by stefwalter** [comment]
@ahuffman There is some planned work on providing a way to update the user's login config and thus providing the login screen you're talking about:

https://trello.com/c/2qwR9Kvj/202-atomic-login-to-kubernetes-origin

However ... unless you lock down access to kubernetes REST API itself ... logged in users can trivially bypass any imagined security restriction whether it's by deleting or chmoding kubectl or any other thing you may try in Cockpit.

Cockpit is not granting access of any sort, Cockpit is using the logged in uid's current privileges and abilities to display a UI.
