### ISSUE TITLE
select dropdown on demo page is missing

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#3473]
![screenshot from 2016-01-14 15-22-08](https://cloud.githubusercontent.com/assets/209895/12326693/a362150c-bad2-11e5-906e-65310d1a5328.png)

**Comment by stefwalter** [comment]
I really just want to drop bootstrap-select. See how we do dropdown and dropdown-toggle in the registry component for an idea.

**Comment by andreasn** [comment]
Sure.
