### ISSUE TITLE
containers and header button is out of alignment

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#3489]
![screenshot from 2016-01-15 18-05-42](https://cloud.githubusercontent.com/assets/209895/12359439/aa254e5a-bbb2-11e5-89b5-b9093db2244d.png)

**Comment by abhishekgupta5** [comment]
@andreasn , @stefwalter   > I can work on it. I need to know which file to alter though and what do you expect ?

**Comment by andreasn** [comment]
Great to hear!
I think it's the button margin of those buttons in the list that needs a bit more margin or padding.
The css lives in either this [1] (global css) or this [2] (docker specific css)
1. https://github.com/cockpit-project/cockpit/blob/master/pkg/base1/cockpit.css
2. https://github.com/cockpit-project/cockpit/blob/master/pkg/docker/docker.css

I would recommend figuring out exactly what the widget class is using the browser inspector.

**Comment by abhishekgupta5** [comment]
@andreasn : Sorry for late report on the issue. Actually I am facing some problem with my fedora distro. I'll get back on this bug as soon as possible. A couple of days maybe

**Comment by abhishekgupta5** [comment]
@andreasn : I think it's the 'docker.css' file that needs change. But to know the exact amount of padding which needs to be improved, I need to do hit and trial on my machine.
The problem which I am facing is I am editing the code on my local cockpit repo(the docker.css file) but it's not getting reflected on https://ip-of-my-machine:9090 Can you guide me what I am missing here ?

**Comment by abhishekgupta5** [comment]
@andreasn > How can I add a container in my system ? Then I'll be able to see how much padding is required. I don't have anything in the containers field
