### ISSUE TITLE
test: Use unique names for test directories

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#3515]
The os can be reused now (e.g. avocado/fedora-23, verify/fedora-23).

This currently means that the dir is used multiple times for a single commit, whereas they should be unique for the commit.

One solution would be to include the prefix in the dir name. Due to the testing impact, I'm filing this as a bug.

**Comment by stefwalter** [comment]
What test directory are you refering to here?

**Comment by dperpeet** [comment]
I meant the log directory, which you apparently noticed as well.
Fixed in https://github.com/cockpit-project/cockpit/commit/1bebc6ff31fa99849892c5f38f1215a9646ff952
