### ISSUE TITLE
Feature Request: Samba support

### ISSUE THREAD

**Issue by FireDrunk** [cockpit-project/cockpit#3534]
Is there any support for management of (or at least information about) Samba shares planned?

**Comment by andreasn** [comment]
Samba client or samba server?

**Comment by andreasn** [comment]
We have NFS client support on the roadmap, and I imagine SMB support would work fairly similar UX-wise. https://trello.com/c/PZPciouD/146-nfs-client-configuration

**Comment by FireDrunk** [comment]
I was thinking about Samba Server in this case (so creating shares using Cockpit).

**Comment by muhahacz** [comment]
@FireDrunk +1

**Comment by andreasn** [comment]
A UI for controlling samba shares of the servers is not something we have on the [roadmap](https://trello.com/c/ieN2nnXd/176-milestone-feature-roadmap) right now, but if it's something you want to work on, I'm happy to help with designs.

**Comment by dcrdev** [comment]
@FireDrunk +1

**Comment by andreasn** [comment]
Who of you is up for hacking on it?

**Comment by dcrdev** [comment]
So I'm thinking about taking this on - are there any existing examples where you've had to implement a configuration file parser? I note most of what's going on in cockpit is interacting via dbus - but samba has no dbus interface and is configured through a single ascii file.

**Comment by petervo** [comment]
```cockpit.file``` (http://cockpit-project.org/guide/latest/cockpit-file.html) is the api to use for reading and writing files. Here's some code that does some config file parsing. https://github.com/cockpit-project/cockpit/blob/master/pkg/ostree/remotes.js#L102 Though depending on the format there may be better options.

**Comment by lukasmrtvy** [comment]
Any progress on this ?

**Comment by martinpitt** [comment]
Obviously we don't have the capacity in the Cockpit team to create that UI ourselves. But we have worked a lot on making external Cockpit extensions ("Applications") much easier, and will support you if you want to work on this.

Links:
 - https://cockpit-project.org/blog/cockpit-starter-kit.html
 - https://cockpit-project.org/blog/making-a-cockpit-application.html
 - https://cockpit-project.org/external/wiki/Contributing.html

**Comment by t-dan** [comment]
There is https://github.com/enira/cockpit-smb-plugin
Could it be a good starting point?

**Comment by andreasn** [comment]
@t-dan that sounds like a good solution in itself. No particular need for samba client support to live in the main cockpit tree itself, so as long as it's possible to install easily, it would solve this issue.

**Comment by Protektor-Desura** [comment]
Except it isn't a fully managed solution. It does not have the UI ease to for setting up Samba AD server. The plugin that mentions AD hasn't been updated in 3 years. So it isn't keeping up with Samba.

**Comment by lukasmrtvy** [comment]
@Protektor-Desura try this https://github.com/45Drives/cockpit-samba-manager

**Comment by iandk** [comment]
Are there any plans for an official solution?

**Comment by Protektor-Desura** [comment]
Also not sure about other distros but if you want the Samba server to show up in the Windows 10 network neighbor shares folder you are going to need Web Service Discovery daemon running on the server, or you will have to type in the name or IP of the server to access shares.

https://github.com/christgau/wsdd

So any Samba add on module should install this or make sure it is running or whatever or people will be pulling their hair out as to why they can't see the server on the network automatically.

**Comment by iandk** [comment]
yea that's right, therefore I'd appreciate a official solution which would provide a simple and clean solution to add and manage shared/ users.

**Comment by Protektor-Desura** [comment]
I don't know if many of you saw this but Ubuntu desktop is now going to have major integrations with Active Directory. It is part of their push to bring Ubuntu to the enterprise desktop. So it would seem to me that a plugin for Samba and Active Directory would only make sense.

https://ubuntu.com/blog/ubuntu-21-04-is-here
