### ISSUE TITLE
/tmp/libvirt/qemu/log/ grows slowly over time

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#3609]
This will kill some of our verify containers after some weeks, which might only have 64M in /tmp.

The directory contains a small file for each libvirt domain we create, and since we don't reuse names, it will fill up.

As @dperpeet suggested, we can just clean out this directory before/after a test run.

**Comment by stefwalter** [comment]
This needs to go into cockpituous repository in the verify/ directory.
