### ISSUE TITLE
Cockpit on Centos7 minimal - Docker not enough free space error

### ISSUE THREAD

**Issue by brianread108** [cockpit-project/cockpit#3641]
Clicking "Image" in the docker page gives the following errors in the logs:

Docker-storage-setup.service failed. systemd
22:59
Unit docker-storage-setup.service entered failed state. systemd
22:59
Failed to start Docker Storage Setup. systemd
22:59
docker-storage-setup.service: main process exited, code=exited, status=1/FAILURE systemd
22:59
There is not enough free space in volume group centos to create data volume of size MIN_DATA_SIZE=2G. docker-storage-setup
22:59
Metadata volume docker-poolmeta already exists. Not creating a new one. docker-storage-setup
22:59
Starting Docker Storage Setup... systemd

Am running in Virtual Box v5, hard drive is 20g (dynamic).

**Comment by stefwalter** [comment]
This seems like a CentOS bug. Could you request help from them. I'm sorry that this issue tracker can't solve all the Linux issues encountered.

**Comment by brianread108** [comment]
Tricky to know if it is Centos, Docker or VIrtual Box!
