### ISSUE TITLE
unable to install on Lubuntu: 'unable to locate package cockpit'

### ISSUE THREAD

**Issue by Gys** [cockpit-project/cockpit#3642]
I tried to install this on a Lubuntu 15.0x machine.
According to http://cockpit-project.org/running.html these are the commands:

    sudo add-apt-repository ppa:jpsutton/cockpit
    sudo apt-get install cockpit
    sudo systemctl start cockpit

However, after the second command I get an error:    

    Lubuntu15 $ sudo add-apt-repository ppa:jpsutton/cockpit
    Packages for the Cockpit project ( https://github.com/cockpit-project )
    More info: https://launchpad.net/~jpsutton/+archive/ubuntu/cockpit
    Press [ENTER] to continue or ctrl-c to cancel adding it
    
    gpg: keyring `/tmp/tmpcw3v96_4/secring.gpg' created
    gpg: keyring `/tmp/tmpcw3v96_4/pubring.gpg' created
    gpg: requesting key 3E4F2C0C from hkp server keyserver.ubuntu.com
    gpg: /tmp/tmpcw3v96_4/trustdb.gpg: trustdb created
    gpg: key 3E4F2C0C: public key "Launchpad PPA for Jared Sutton" imported
    gpg: Total number processed: 1
    gpg:               imported: 1  (RSA: 1)
    OK
    Lubuntu15 $ sudo apt-get install cockpit
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    E: Unable to locate package cockpit

**Comment by stefwalter** [comment]
@andreasn Should we take Ubuntu off the list at running.html? It doesn't seem to be updated, nor does the Cockpit Project have access to update it? What do you think @jpsutton?

**Comment by jpsutton** [comment]
I have updated the PPA with an updated cockpit as of a week or two ago.  However, it is currently building correctly only on 15.10, not 15.04.  Updating the running.html page with more specific version info should be good enough I think.

**Comment by stefwalter** [comment]
Thanks @jpsutton. Could you check the command that the OP is reporting above? Do we need to have a different command at our running.html page to install Cockpit from the PPA?

**Comment by jpsutton** [comment]
No adjustment to the installation commands should be necessary.  If we could just get a note on there that Ubuntu 15.10 is currently the only supported release, that would be great.

For reference, I posted the build error that I'm seeing over on the devel list: https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/thread/QWO3ZE3OF6FHTFRWMWZDHBKZTU6A3ZXB/

**Comment by stefwalter** [comment]
Updated the running.html to say Ubuntu 15.10 or later.

**Comment by smirnovigor** [comment]
I'm running `sudo apt-get install cockpit` on Ubuntu 15.10 and fall in the same issue
