### ISSUE TITLE
Couldn't connect to Kubernetes server

### ISSUE THREAD

**Issue by smirnovigor** [cockpit-project/cockpit#3643]
After installing a fresh version of cockpit, on the Cluster page I get 

```
Couldn't connect to Kubernetes server
Couldn't find running kube-apiserver
```

On the VM running command `kubectl get nodes` return result: 

```
error: couldn't read version from server: Get http://localhost:8080/api: dial tcp [::1]:8080: getsockopt: connection refused
```

Any help?

**Comment by stefwalter** [comment]
How did you install Cockpit? ```kubectl get nodes``` should work before Cockpit will work, which typically means that you need to have a valid ```~/.kube/config``` file in place. In the future we probably need to make this be simpler.

**Comment by smirnovigor** [comment]
I'm installing with a ``vagrant up`` command and there is no ``~/.kube`` folder for admin and root users.

**Comment by stefwalter** [comment]
I think we should make a script for bringing up cockpit inside the Vagrant node. Bringing it up by default would penalize users not interested.

**Comment by smirnovigor** [comment]
It seems that starting kubernetes services in Vagrantfile is missing. 

I have added this script to Vagrantfile and it starts kubernetes, but it doesn't work from cockpit.

```
    mkdir /var/run/kubernetes
	chown kube:kube /var/run/kubernetes
	chmod 750 /var/run/kubernetes

	for SERVICES in etcd kube-apiserver kube-controller-manager kube-scheduler; do
	    systemctl restart $SERVICES
	    systemctl enable $SERVICES
	    systemctl status $SERVICES
	done
```

**Comment by martinpitt** [comment]
This is an issue about configuring kubernetes in a VM, not an issue in cockpit itself. This is quite old, but if it's still an issue,  would you mind asking this in the  kubernetes project? Thank you!
