### ISSUE TITLE
check-embed should not rely on network access.

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#3661]
The check-embed test uses a sophisticated frame around Cockpit that loads Patternfly, Bootstrap, jQuery, etc from the Internet.

It should load what it needs from the unpacked Cockpit source tree.

Also, it probably needs a lot less than it currently loads.

**Comment by martinpitt** [comment]
I fixed that a while ago in commit f2024dd80d729e0f3dd530e285d4bed2b897e5de
