### ISSUE TITLE
124 tests failed

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#3666]
The tests are complaining about things like '124 tests failed' on IRC. I think this is a regression for the recent sink or github-task changes.

```
<cockpitbot> 124 tests failed - http://fedorapeople.org/groups/cockpit/logs/master-dc3c5bb2-verify-fedora-22/log.html
```

**Comment by mvollmer** [comment]
124 is the exit code when we hit the global timeout.
