### ISSUE TITLE
Auth failing in 2-step setup

### ISSUE THREAD

**Issue by ebalsumgo** [cockpit-project/cockpit#3678]
I recently setup OpenShift Enterprise 3.1.1 which includes support for Cockpit. However, authentication to the local machine is done as 2-step process. Password (kerberos) + security token (Duo in our case), which in Cockpit produces **Feb  3 16:24:03 osmaster0s cockpit-session: Aborted Duo login for 'boris' from 172.22.44.16: Error gathering user response**

As far as I can tell the only way to get logged in is to write a pam config for cockpit specifically, but that will be frowned upon by our security office and will not pass muster in production.

Suggestions? @sgallagher and myself talked about this in #openshift-dev

**Comment by petervo** [comment]
@ebalsumgo  I'm not sure exactly how you have things configured but, cockpit does have it's own pam configuration already see: https://github.com/cockpit-project/cockpit/blob/master/tools/cockpit.pam.

If modifying that isn't an option, cockpit also supports logging in over ssh by passing the --local-ssh option to cockpit-ws when it starts. Then as long as the same user is able to ssh into the machine cockpit should work as well.

**Comment by ebalsumgo** [comment]
As far as configuration. As I said Cockpit has been included in Red Hat Openshift and thats about all the visibility I have into it as the documentation for their setup is not there yet at the moment :/

As far as PAM thats what I was going to work on trying to setup today and see how that went over. --local-ssh would not work as 2-step is still part of the login process.

**Comment by sgallagher** [comment]
@stefwalter I think the problem here is that Cockpit's login mechanism doesn't support conversations: we can't get prompted for the second factor and thus login fails.

**Comment by petervo** [comment]
@sgallagher yes conversations are not supported for either local or ssh logins.

**Comment by stefwalter** [comment]
We do need to support the ability to reset the login password, if it has expired. Does that mean we should generalize to supporting conversations?

**Comment by sgallagher** [comment]
That would seem like the most future-proof solution.

**Comment by petervo** [comment]
Conversations are now supported. Should be in the next release. Please reopen if this doesn't solve the problem.
