### ISSUE TITLE
server: tuned error doesn't look errory enough

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#3701]
![screenshot from 2016-02-07 14-21-23](https://cloud.githubusercontent.com/assets/209895/12872551/584355f4-cda6-11e5-8ad0-26349d4f0e81.png)

Maybe we should use a /!\ icon instead of (i) in the cases it's an error.

**Comment by andreasn** [comment]
The error in this case is "tuned is not avaiable

**Comment by dperpeet** [comment]
But if tuned isn't available, why should that be an error? An error in my opinion is if something failed that was expected to succeed - e.g. we detect tuned but communication fails. If it's just not present, then that's informative and not an error.

**Comment by andreasn** [comment]
This came up when I spoke to one of the virt guys, so I thought I might as well fail it.
It's a fair argument, so closing.
