### ISSUE TITLE
RFE: "blame" functionality for dashboards

### ISSUE THREAD

**Issue by davidmalcolm** [cockpit-project/cockpit#3726]
I leave a window with cockpit's "System" view open on my workstation, and I sometimes see spikes of activity on the different graphs: CPU, memory, network, disk IO, and find myself wondering "what's doing that?".

It would be nice to:
- be able to click on one of the graphs in the "System" view and go to a more detailed version of that view (maybe this is already implemented? I'm running a relatively old version of Cockpit, 0.67)
- from the more detailed view, have some kind of "biggest consumers" view e.g.
  - for the CPU, a sorted list of all processes consuming more than some x% of CPU over last second
  - for memory: a sorted list of all processes by "memory consumption" (whatever _that_ means; in the presence of shared libraries etc, it's nontrivial to say what we mean here)
  - for network: what processes are transmitting/accepting the data, and what IP addresses they're talking to (and maybe convert these back to hostnames)
  - disk IO: not sure about this

Hope this is constructive.

**Comment by stefwalter** [comment]
Interesting idea. Worth taking into account when redoing the dashboards or server summary. @andreasn did you put any thought into this area?

**Comment by andreasn** [comment]
I like this idea a lot, and I've seen other software do it. I'll try to fold it into the dashboard work design that is underway.

**Comment by davidmalcolm** [comment]
Some more brainstorming: maybe show sparklines showing:
- CPU: per-process CPU activity
- Memory: per-process memory consumption
- Network: per-pair-of-IP-addresses/port tx/rx (so you can see e.g. that machines A, B, C (web frontends) are sending/receiving to many external hosts on port 443, and that they're talking a lot to machine D's postgres port, and similar kinds of thing  (maybe show this as a graph in the kubernetes view e.g. thickness of the connection?).  (does cockpit have a network topology view?)  Could have port/service-specific plugins, so e.g. if we see postgres activity, can click on it and see a summary of queries e.g. slow queries, etc, (perhaps via systemtap's user-space static probepoints???).  Or at least be able to see service-specific journal entries?

(Not sure if all these ideas are sane/useful, am just brainstorming)

**Comment by davidmalcolm** [comment]
(actually, it's not so much "network topology" I was thinking, but perhaps more like Wireshark's "conversations" idea: pairs of endpoints)

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
