### ISSUE TITLE
Plugin absent in second tab

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3730]
I'm using cockpit 0.77 on RHEL 7.2. I installed the ping plugin and started cockpit in my web browser and the plugin was there and working. Then, I opened a second tab to the same address as the same user and the plugin did not show up in the menu.

**Comment by mulkieran** [comment]
Seems to occur with HEAD from master, too. Running web portion on Firefox v42.0, Fedora 22.

**Comment by stefwalter** [comment]
If you log out and log back in on the second tab, does the plugin show up as expected?

**Comment by mulkieran** [comment]
I'm afraid I wasn't able to check that specifically before the whole machine had to be rebooted...the problem did not survive the reboot, and I definitely did log out as a result of that reboot :) , so feel free to close.
