### ISSUE TITLE
Version information not displayed in "About Cockpit" pop-up.

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3733]
Just an empty string with a period after it, like so:

```
About Cockpit
Cockpit is an interactive Linux server admin interface.
Project website
Version .
Licensed under the GNU LGPL version 2.1
```

On RHEL 7.2.

Definitely occured in version 0.77. Also occurring in HEAD branch of master, AFAICT (it's a little hard to be certain given the lack of version information, but I believe that I have succesfully removed 0.77 and succesfully installed from source).

**Comment by andreasn** [comment]
I see the version number in 0.91 on master here (compiled earlier today). On Fedora however. Will test if it's any different for me on a RHEL7 system.

**Comment by mulkieran** [comment]
I am now seeing the version string.

```

Cockpit is an interactive Linux server admin interface.
Project website
Version 0.95.x.
Licensed under the GNU LGPL version 2.1
```

**Comment by andreasn** [comment]
Good to hear!
Closing this. Please reopen if you run into it again.

**Comment by mulkieran** [comment]
I'm afraid that it is back.
