### ISSUE TITLE
Breadcrumbs wrong when inspecting multipathed storage devices

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3734]
```
Storage >> sdc     <-- BAD BREADCRUMB

Drive
Model   WDC WD10EFRX-68PJCN0
Firmware Version    82.00A82
Serial Number   WD-WCC4JKAT9Y7F
World Wide Name     0xb2590ae94ee25001
Capacity    931.5 GB (1000204886016 bytes)
Assessment  Disk is OK (25.0° C / 77.0° F)
Device File     -
Multipath Devices   /dev/sdc /dev/sds 
```

The breadcrumb should refer to its device, not to one of the two multipathed devices. I believe that this is a problem in the current version, because the fields seem to reflect the current source.

It probably goes all the way back to the choice of dev in:
https://github.com/cockpit-project/cockpit/blob/master/pkg/storaged/index.html#L183.

**Comment by andreasn** [comment]
I get "Strorage > dm-3" here.
@mvollmer do you see the same as @mulkieran above?

**Comment by mulkieran** [comment]
This no longer seems to be occurring in current version.

**Comment by mulkieran** [comment]
But, I think it would be better to use the /dev/mapper name than the /dev one, because of this one line in the RHEL 7 multipath manual:
```
Any devices of the form /dev/dm-n are for internal use only should never be used by the administrator directly.
```

**Comment by mulkieran** [comment]
Actually, I think even better would be to use the appropriate name for the physical disk, given that you can always end up in the situation where there are two device files and no multipath device. The only unique and reliable identifier is something to do with the disk itself.

**Comment by mvollmer** [comment]
> Actually, I think even better would be to use the appropriate name for the physical disk [...]

Makes sense.
