### ISSUE TITLE
tests: use of cockpit.lan is not rfc compliant

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#3735]
@goern suggested the following changes to fix this (change to example.com)
https://github.com/cockpit-project/cockpit/compare/master...goern:feature/use-rfc2606

The problem is that this involves changing the network and will invalidate all current testing setups.

**Comment by martinpitt** [comment]
This should not have any impact on any infrastructure any more, so this can be done now.

**Comment by marusak** [comment]
Is this just replacing `cockpit.lan` with `cockpit.example.com`?

**Comment by goern** [comment]
Ja ;)

**Comment by martinpitt** [comment]
Note that this is totally busywork: our tests have a private network and the VMs are offline otherwise, nothing leaks to the host or even the internet. So if someone wants to change it, it's fine, but it's quite a lot of work (rebuilding images and changing tests in sync)

**Comment by goern** [comment]
thats fair

**Comment by marusak** [comment]
Since it seems there is little to no actual effect this would have except to "being correct" and it is a noisy work, lets not track this actively as we most likely not going to change this.
