### ISSUE TITLE
Information for whacky multipath device incorrect

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3736]
The screen shown below is for a mutlipath device with the unusual property of possessing only one member. The reason....unknown, but likely a hardware failure at the point where the two paths are multiplexed to the actual disk.

At some point, there were two multipathed paths, /dev/sdb and _unknown_, now there is only /dev/sdb.

However, that one device is still multipathed, so the display should use the display appropriate for a multipath device.

```
Storage >> mapper/350014ee5aaab876c 

Block Device
Device File     /dev/mapper/350014ee5aaab876c
Capacity    3.6 TB (4000787030016 bytes)
Content

Unrecognized Data
/dev/mapper/350014ee5aaab876c      —  
```

Also, probably it should be listed among "Drives" on the main storage screen, but it gets tossed in among 'Other Devices" instead.

**Comment by mulkieran** [comment]
Also, if I try to create a RAID array, /dev/sdb is a candidate device...the candidate devcie  should be its multipath holder.

**Comment by mvollmer** [comment]
Recorded in our secret planning tool.
