### ISSUE TITLE
Drive names get cut off in Drives panel on storage screen

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3737]
Here's a table entry in the drives panel.

```
WDC WD10EFRX-68PJCN0 (WD-WCC4J5VFRF29)
931.5 GB Hard Disk
R: 0 B/s W: 0 B/s   
```

There is nothing wrong with it in the above copied and pasted example.
But, in the actual GUI, the name  gets sheared off in the middle of the very last 9 (and looks a tiny bit funny).

I'm not sure how the Name value is actually calculated. I'm using multipath's unfriendly names because they are more informative. Friendly names look more like "mpath1", and are generally a bit shorter.

**Comment by mulkieran** [comment]
Actually, the funny long names are due to https://bugzilla.redhat.com/show_bug.cgi?id=1273306.
Multipath detects that the WWN on the drive is the wrong format, so synthesizes a name from some sort of manufacturer, serial  number info and that number is abnormally long.

**Comment by andreasn** [comment]
Does it get cut straight off, or do you get "..." at the end?
I think we used to get proper ellipses for long names in the past, but it might have regressed.

**Comment by mulkieran** [comment]
![screenshot from 2016-02-12 13-56-23](https://cloud.githubusercontent.com/assets/1218366/13017089/7f5ace5e-d190-11e5-8427-7dfaad4bbedc.png)

I just updated, and I'm definitely running from master. The look has changed a bit, but the end of the Name string is still cut off, observe the missing close paren. I think the Name stringi is getting more room, though, so there are fewer cut off strings. In fact, when I copy and paste the string, it is clear that the only thing missing is the close paren.

```
WDC WD10EFRX-68PJCN0 (WD-WCC4JEDAXESZ)
```

**Comment by mvollmer** [comment]
We get ellipses now, I think since the rewrite to React.
