### ISSUE TITLE
Descriptions for disks in "Create RAID Device" dialog are redundant

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3739]
![screenshot from 2016-02-12 15-28-05](https://cloud.githubusercontent.com/assets/1218366/13019536/0fb46070-d19e-11e5-985b-1a0a504770c4.png)

It seems like in almost every entry, a name is repeated twice, sometimes the name is quite long, which makes the whole display cluttered.

**Comment by mvollmer** [comment]
This still happens, for example with /dev/loop0.
