### ISSUE TITLE
Implement pull cancellation in overview and details page

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#374]
Cancellation of an image pull in the overview and details page. Currently for stuff in progress we show a waiting throbber.

Need design from @andreasn on how to combine waiting throbber with a cancel button for cancellable tasks.

**Comment by KKoukiou** [comment]
Closing this issue because the Docker plugin is not being actively developed any longer.
Replacement should be https://github.com/cockpit-project/cockpit-podman/ so any RFEs should be opened on that repository.
