### ISSUE TITLE
Fedora Powerline arrows encoding in Terminal

### ISSUE THREAD

**Issue by wstarcev** [cockpit-project/cockpit#3740]
Using [Powerline](https://fedoramagazine.org/add-power-terminal-powerline/) in web terminal the arrows shown as rectangles. Probably wrong encoding or font.

**Comment by stefwalter** [comment]
Do you know how Powerline renders? In particular why does it require a daemon? It's likely it doesn't consider non X11 uses of its prompt.

Are you interested in contributing towards making this work?

**Comment by stefwalter** [comment]
Haven't received a response back from reporter. Closing the bug.
