### ISSUE TITLE
 libvirt issues when trying to run the tests as root

### ISSUE THREAD

**Issue by arilivigni** [cockpit-project/cockpit#3753]
I set everything up as the root user and ran testsuite-prepare

After downloading the images I get the following:

[root@cockpit-ci-slave-3airmv test]# ./testsuite-prepare 
https://fedorapeople.org/groups/cockpit/images/fedora-23-83c415de2896d696e99e13d6dd7626366241050a.qcow2.xz
######################################################################## 100.0%
https://fedorapeople.org/groups/cockpit/images/ipa-b5c4494f86d104aa83507ff1b5897e6d81552bf5.qcow2.xz
######################################################################## 100.0%
https://fedorapeople.org/groups/cockpit/images/openshift-15183b1034936c914760f556feb478226c342955.qcow2.xz
######################################################################## 100.0%
https://fedorapeople.org/groups/cockpit/images/stock-fedora-22-x86_64-2.qcow2.xz
######################################################################## 100.0%
libvirt: Capabilities Utils error : invalid argument: could not find capabilities for arch=x86_64 domaintype=kvm 
Traceback (most recent call last):
  File "./vm-install", line 97, in <module>
    build_and_maybe_install(build_image, do_install=True, skip=skip)
  File "./vm-install", line 66, in build_and_maybe_install
    machine.start(maintain=do_install, memory_mb=4096, cpus=4)
  File "/root/cockpit/test/testvm.py", line 897, in start
    self._start_qemu(maintain=maintain, macaddr=macaddr, wait_for_ip=wait_for_ip, memory_mb=memory_mb, cpus=cpus)
  File "/root/cockpit/test/testvm.py", line 847, in _start_qemu
    dom = self.virt_connection.createXML(test_domain_desc, libvirt.VIR_DOMAIN_START_AUTODESTROY)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 3611, in createXML
    if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
libvirt.libvirtError: invalid argument: could not find capabilities for arch=x86_64 domaintype=kvm

**Comment by stefwalter** [comment]
Did you install the stuff near the top of ```test/README```?

**Comment by arilivigni** [comment]
yep:

yum install npm python-libguestfs qemu qemu-kvm python \
>          libvirt-client openssl libguestfs-tools \
>          krb5-workstation expect rsync libvirt-python curl xz
Package npm-1.3.6-5.el7.noarch already installed and latest version
Package 1:python-libguestfs-1.28.1-1.55.el7.x86_64 already installed and latest version
Package 2:qemu-2.0.0-1.el7.6.x86_64 already installed and latest version
Package 10:qemu-kvm-1.5.3-105.el7.x86_64 is obsoleted by 10:qemu-kvm-rhev-2.3.0-31.el7_2.7.x86_64 which is already installed
Package python-2.7.5-34.el7.x86_64 already installed and latest version
Package libvirt-client-1.2.17-13.el7.x86_64 already installed and latest version
Package 1:openssl-1.0.1e-42.el7_1.9.x86_64 already installed and latest version
Package 1:libguestfs-tools-1.28.1-1.55.el7.noarch already installed and latest version
Package krb5-workstation-1.13.2-10.el7.x86_64 already installed and latest version
Package expect-5.45-14.el7_1.x86_64 already installed and latest version
Package rsync-3.0.9-17.el7.x86_64 already installed and latest version
Package libvirt-python-1.2.17-2.el7.x86_64 already installed and latest version
Package curl-7.29.0-25.el7.x86_64 already installed and latest version
Package xz-5.1.2-12alpha.el7.x86_64 already installed and latest version
Nothing to do
[root@cockpit-ci-slave-zh6xf test]#

**Comment by arilivigni** [comment]
virsh capabilities | grep x86
      <arch>x86_64</arch>
    <arch name='x86_64'>
      <emulator>/usr/bin/qemu-system-x86_64</emulator>

**Comment by arilivigni** [comment]
filename:       /lib/modules/3.10.0-229.el7.x86_64/kernel/arch/x86/kvm/kvm-intel.ko
license:        GPL
author:         Qumranet
rhelversion:    7.1
srcversion:     563B39A25B297BBD92206E4
alias:          x86cpu:vendor:*:family:*:model:*:feature:*0085*
depends:        kvm
intree:         Y
vermagic:       3.10.0-229.el7.x86_64 SMP mod_unload modversions 
signer:         Red Hat Enterprise Linux kernel signing key
sig_key:        A3:CB:8C:C3:19:50:4A:B5:2C:FB:76:BA:F8:D8:A2:A7:39:68:9C:56
sig_hashalgo:   sha256
parm:           vpid:bool
parm:           flexpriority:bool
parm:           ept:bool
parm:           unrestricted_guest:bool
parm:           eptad:bool
parm:           emulate_invalid_guest_state:bool
parm:           vmm_exclusive:bool
parm:           fasteoi:bool
parm:           enable_apicv:bool
parm:           enable_shadow_vmcs:bool
parm:           nested:bool
parm:           ple_gap:int
parm:           ple_window:int
parm:           ple_window_grow:int
parm:           ple_window_shrink:int
parm:           ple_window_max:int

**Comment by arilivigni** [comment]
QEMU: Checking for hardware virtualization                                 : PASS
  QEMU: Checking for device /dev/kvm                                         : PASS
  QEMU: Checking for device /dev/vhost-net                                   : PASS
  QEMU: Checking for device /dev/net/tun                                     : PASS
   LXC: Checking for Linux >= 2.6.26                                         : PASS

**Comment by dperpeet** [comment]
Since you're using root, my hunch is a conflict of qemu:///session vs qemu:///system
I'll take a look at the code to see where it could fail.

**Comment by arilivigni** [comment]
I will try creating another user and running things that way to see if that works.
I emailed you that system info as well to take a look.

**Comment by arilivigni** [comment]
I received the same issue as another user:

[jenkins@cockpit-ci-slave-zh6xf test]$ ./testsuite-prepare 
https://fedorapeople.org/groups/cockpit/images/fedora-23-83c415de2896d696e99e13d6dd7626366241050a.qcow2.xz
######################################################################## 100.0%
https://fedorapeople.org/groups/cockpit/images/ipa-b5c4494f86d104aa83507ff1b5897e6d81552bf5.qcow2.xz
######################################################################## 100.0%
https://fedorapeople.org/groups/cockpit/images/openshift-15183b1034936c914760f556feb478226c342955.qcow2.xz
######################################################################## 100.0%
https://fedorapeople.org/groups/cockpit/images/stock-fedora-22-x86_64-2.qcow2.xz
######################################################################## 100.0%
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
Traceback (most recent call last):
  File "./vm-install", line 97, in <module>
    build_and_maybe_install(build_image, do_install=True, skip=skip)
  File "./vm-install", line 64, in build_and_maybe_install
    machine = testvm.VirtMachine(verbose=args.verbose, image=image, label="install")
  File "/home/jenkins/cockpit/test/testvm.py", line 681, in __init__
    self.virt_connection = self._libvirt_connection(hypervisor = "qemu:///session")
  File "/home/jenkins/cockpit/test/testvm.py", line 714, in _libvirt_connection
    connection = open_function(hypervisor)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 255, in open
    if ret is None:raise libvirtError('virConnectOpen() failed')
libvirt.libvirtError: Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
[jenkins@cockpit-ci-slave-zh6xf test]$ sudo ./testsuite-prepare 
libvirt: Storage Driver error : Cannot access storage file '/home/jenkins/cockpit/test/tmp/run/fedora-23.qcow2' (as uid:107, gid:107): Permission denied
Traceback (most recent call last):
  File "./vm-install", line 97, in <module>
    build_and_maybe_install(build_image, do_install=True, skip=skip)
  File "./vm-install", line 66, in build_and_maybe_install
    machine.start(maintain=do_install, memory_mb=4096, cpus=4)
  File "/home/jenkins/cockpit/test/testvm.py", line 897, in start
    self._start_qemu(maintain=maintain, macaddr=macaddr, wait_for_ip=wait_for_ip, memory_mb=memory_mb, cpus=cpus)
  File "/home/jenkins/cockpit/test/testvm.py", line 847, in _start_qemu
    dom = self.virt_connection.createXML(test_domain_desc, libvirt.VIR_DOMAIN_START_AUTODESTROY)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 3611, in createXML
    if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
libvirt.libvirtError: Cannot access storage file '/home/jenkins/cockpit/test/tmp/run/fedora-23.qcow2' (as uid:107, gid:107): Permission denied

**Comment by dperpeet** [comment]
something's broken in vm-prep:

/etc/qemu-kvm/bridge.conf needed `allow cockpit1`
There's also an /etc/qemu/bridge.conf and that one had the line.

**Comment by arilivigni** [comment]
I am still hitting this issue after the merged code.

[jenkins@cockpit-slave ~]$ cd cockpit/test/
[jenkins@cockpit-slave test]$ ./testsuite-prepare 
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
Traceback (most recent call last):
  File "./vm-install", line 97, in <module>
    build_and_maybe_install(build_image, do_install=True, skip=skip)
  File "./vm-install", line 64, in build_and_maybe_install
    machine = testvm.VirtMachine(verbose=args.verbose, image=image, label="install")
  File "/home/jenkins/cockpit/test/testvm.py", line 681, in __init__
    self.virt_connection = self._libvirt_connection(hypervisor = "qemu:///session")
  File "/home/jenkins/cockpit/test/testvm.py", line 714, in _libvirt_connection
    connection = open_function(hypervisor)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 255, in open
    if ret is None:raise libvirtError('virConnectOpen() failed')
libvirt.libvirtError: Cannot create user runtime directory '/run/user/0/libvirt': Permission denied

**Comment by stefwalter** [comment]
Did this work out or are you still stuck here?

**Comment by arilivigni** [comment]
This  can be closed it would be good if we could run these as root or a
user without having to set the home env.  Dominik and I worked through it.
