### ISSUE TITLE
Usebility: Graph out of bounds

### ISSUE THREAD

**Issue by xrow** [cockpit-project/cockpit#3762]
Hi Folks,

as you can see from by screenshot the visual tools has problems displaying many nodes and pods. There should be a posiblity to scroll.

This is just a minor issue, but that makes the too a bit unuseable.

<img width="678" alt="urknall2" src="https://cloud.githubusercontent.com/assets/295491/13076083/23c9994e-d4b0-11e5-8b13-fd68a97fcd64.PNG">

**Comment by stefwalter** [comment]
We need better ability to filter for starters, and not default to displaying everything when there's too much data.

**Comment by martinpitt** [comment]
This would require a major amount of work, and our kubernetes UI is on low maintenance mode.

https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/thread/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
