### ISSUE TITLE
test-kerberos leaves behind a cockpit-session process at 100%

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#3763]
After each run of
```
./test-kerberos
```
I have one more `cockpit-session` process running at full tilt.  I haven't yet checked what it is doing.

**Comment by mvollmer** [comment]
@petervo, any ideas?

**Comment by mvollmer** [comment]
test-kerberos seems to have trouble with shutting down the cockpit-session process in general: https://github.com/cockpit-project/cockpit/pull/3761#issuecomment-184681618

**Comment by mvollmer** [comment]
Also, test-kerberos ends up (trying to) execute `cockpit-bridge` from $PATH, no? Is that harmless?

**Comment by petervo** [comment]
This doesn't happen for me, what OS do you see this on? Does it only happen when it fails or on success too?

**Comment by mvollmer** [comment]
> This doesn't happen for me, what OS do you see this on? Does it only happen when it fails or on success too?

I can't reproduce this anymore... weird.

**Comment by mvollmer** [comment]
>> This doesn't happen for me, what OS do you see this on? Does it only happen when it fails or on success too?

> I can't reproduce this anymore... weird.

Now I can.

cockpit-session gets into a loop sending itself SIGTERM over and over.  The reason is that `pass_to_child` is called while `child` is zero.
