### ISSUE TITLE
libvirt issues when running the tests as a user

### ISSUE THREAD

**Issue by arilivigni** [cockpit-project/cockpit#3765]
I am still hitting this issue after the merged code.

[jenkins@cockpit-slave ~]$ cd cockpit/test/
[jenkins@cockpit-slave test]$ ./testsuite-prepare 
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
libvirt: XML-RPC error : Cannot create user runtime directory '/run/user/0/libvirt': Permission denied
Traceback (most recent call last):
File "./vm-install", line 97, in 
build_and_maybe_install(build_image, do_install=True, skip=skip)
File "./vm-install", line 64, in build_and_maybe_install
machine = testvm.VirtMachine(verbose=args.verbose, image=image, label="install")
File "/home/jenkins/cockpit/test/testvm.py", line 681, in init
self.virt_connection = self._libvirt_connection(hypervisor = "qemu:///session")
File "/home/jenkins/cockpit/test/testvm.py", line 714, in _libvirt_connection
connection = open_function(hypervisor)
File "/usr/lib64/python2.7/site-packages/libvirt.py", line 255, in open
if ret is None:raise libvirtError('virConnectOpen() failed')
libvirt.libvirtError: Cannot create user runtime directory '/run/user/0/libvirt': Permission denied

**Comment by dperpeet** [comment]
The shell might mess this up, try "su - [user]"

**Comment by arilivigni** [comment]
This fixed the issue thanks!
