### ISSUE TITLE
storage: LVM raid needs to be implemented or taken out

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#3770]
I think we need to either get it working, or take this menu entry out.

![screenshot from 2016-02-17 12-48-12](https://cloud.githubusercontent.com/assets/209895/13108657/ca6581d6-d574-11e5-9402-5636923fdb6d.png)

**Comment by andreasn** [comment]
![screenshot from 2016-02-17 12-50-41](https://cloud.githubusercontent.com/assets/209895/13108704/13ff660e-d575-11e5-99b7-4821fe11462c.png)

**Comment by mvollmer** [comment]
It has been taken out.
