### ISSUE TITLE
storage: try and prevent error with removing last disk in a LVM volume

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#3772]
Trying to remove the last disk in a LVM volume will always give this error:
"Error remove /dev/vdh from volume group: Command-line `vgreduce "dunder" "/dev/vdh"' exited with non-zero exit status 5: /dev/sdc: read failed after 0 of 4096 at 0: Input/output error /dev/sdc: read failed after 0 of 4096 at 104857534464: Input/output error /dev/sdc: read failed after 0 of 4096 at 104857591808: Input/output error /dev/sdc: read failed after 0 of 4096 at 4096: Input/output error Can't remove final physical volume "/dev/vdh" from volume group "dunder""

Emptying the last disk will also throw an error (Error emptying /dev/vdh: Command-line `pvmove "/dev/vdh"' exited with non-zero exit status 5: No extents available for allocation).

If we gray out the button for the last disk in the list, we can avoid these errors. Possibly with a little popup explaining that the last disk can't be removed because that's how life is.

**Comment by KKoukiou** [comment]
![last-disk-removal-pv](https://user-images.githubusercontent.com/14921356/51991911-617bf800-24ac-11e9-9657-2ad20c89e1fa.png)
Looks like this was fixed some time ago.
