### ISSUE TITLE
Version information not displayed in "About Cockpit" pop-up.

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3781]
Reopening #3733.

**Comment by mulkieran** [comment]
This seems to have something to do with how I stop cockpit after I've done a rebuild and a reinstall.

I started with:
```
systemctl stop cockpit.socket
systemclt start cockpit.socket
```
which left me with missing version.

```
systemctl stop cockpit
systemclt start cockpit.socket
```

leads to me seeing the version again.

So this may not be worth pursuing any further.

**Comment by stefwalter** [comment]
Yup, after a rebuild and reinstall the version numbers may be off. The version numbers in the about dialog are predictable after an install from packages.
