### ISSUE TITLE
"Create RAID devices" dialogue odd in appearance

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3782]
![screenshot from 2016-02-18 11-24-40](https://cloud.githubusercontent.com/assets/1218366/13150144/8a3c86b8-d632-11e5-9f60-6b0b014c9e2b.png)

**Comment by stefwalter** [comment]
What version is this in? @andreasn Do you think this is a result of the recent changes to the disk list layout?

**Comment by andreasn** [comment]
Yes, I saw this behavior when I created the pull request, but added a css property to avoid it.
Let me see if I can duplicate it. Might be a Firefox vs. Chrome thing.

**Comment by andreasn** [comment]
Nope, this is totally happening in Firefox too. Fix coming up!
