### ISSUE TITLE
Centos 7 cockpit-kubernetes 0.93 upgrade issue

### ISSUE THREAD

**Issue by michaelschefczyk** [cockpit-project/cockpit#3790]
Dear All,

February 18, 2016, the Centos 7 extras repo upgraded cockipt from 0.77-3.1.el7 to 0.93-3.el7. After this upgrade, I find an issue with cockipt-kubernetes. Used in conjunction with up to date Centos Atomic Hosts, cockit yields an internal error (shown by a red "Ooops!" in the upper right part of the screen just left of the user indicator) when using two previously working functions:
Cluster -> Containers -> Logs
Cluster -> Containers -> Shell

If this is due to a bug, it would be nice if the two functions could be made to work again so that one may easily use the shell and inspect the logs. If this is just a configuration error I should be able to address, I would very much welcome if someone could point me to the right direction.

Regards,

Michael Schefczyk

**Comment by stefwalter** [comment]
Once the Ooops happens. Could you press Ctrl-Shift-J and click on 'Console'? There should be a more descriptive error message there. Once it's open, could you attach a screenshot or paste the text from the Console, if you'd rather not include a screenshot here.

**Comment by michaelschefczyk** [comment]
Dear Stef,

Thank you very much for your fast respone. The screenshot is enclosed. The missing line at the bottom of the scroll down field is just "t()".

Regards,

Michael

![screenshot](https://cloud.githubusercontent.com/assets/5464672/13217553/9cfa3604-d963-11e5-844f-10e2395c3404.png)

**Comment by stefwalter** [comment]
Thanks for the details #3832 has fixed this issue.

**Comment by stefwalter** [comment]
By the way this is due to a combination of upgrading Cockpit and using something like Firefox 44.x which added support for the initMessageEvent() function.

**Comment by michaelschefczyk** [comment]
Indeed, Firefox 38.6.1 does not produce the same problem! IE 11, however, does behave as the current Firefox version. Thank you very much for explaining and solving this!
