### ISSUE TITLE
Fedora 23 - Unable to install due to docker

### ISSUE THREAD

**Issue by brhahlen** [cockpit-project/cockpit#3799]
I am using the official Docker repo in Fedora 23, and when I try to install cockpit, the following error is produced:
``Error: package cockpit-docker-0.79-1.fc23.x86_64 requires docker >= 1.3.0, but none of the providers can be installed``
Currently installed:
``docker-engine-1.10.2-1.fc23.x86_64``

**Comment by stefwalter** [comment]
What is "docker-engine"?

I see this on Fedora 23:

```
No package docker-engine available.
```

**Comment by brhahlen** [comment]
docker-engine is the "official" name for docker from the docker-repo:
https://docs.docker.com/engine/installation/linux/fedora/

**Comment by stefwalter** [comment]
The Cockpit Fedora packages are meant to be used with other Fedora packages. That's how they are tested and delivered.

If you're using non Fedora packages ... then I guess you'll need to find other solutions to making things work. Like one of these:

 * Use rpm to install cockpit-docker with the --nodeps
 * Build and install Cockpit from source.

**Comment by brhahlen** [comment]
Okay, just did the first option and at least it installs.
But now it is stuck on "Connecting to docker"
Oh well...

**Comment by stefwalter** [comment]
>  But now it is stuck on "Connecting to docker"

Is there any other output on the screen? Perhaps a red "Ooops" in the upper right corner?

**Comment by brhahlen** [comment]
Nope, nothing.
It just keeps spinning. I am logged in as my own user, which is added to the docker group.
As the root user the same thing happens.

**Comment by stefwalter** [comment]
> Nope, nothing. It just keeps spinning. I am logged in as my own user, which is added to the docker group. As the root user the same thing happens.

Strange. I guess 'docker-engine' must be different enough to break things. 

If you do find the issue, I'd be happy to include a patch to fix it. Here's how to get started working on Cockpit: https://github.com/cockpit-project/cockpit/blob/master/HACKING.md#making-changes-in-the-ui-code

Alternatively if you have a publicly accessible machine where this failure is happening, I'd be happy to log in and take a look.

**Comment by brhahlen** [comment]
I will have a look, I'm not that much of a programmer, so it might take some time if I can figure out what's happening.

However: when running with the Fedora-provided docker package, I get the error "Not authorized to access Docker on this system"
journalctl -f output:
```
Feb 23 12:18:40 hostname cockpit-bridge[20415]: cannot reauthorize identity(s): unix-user:root 
Feb 23 12:18:40 hostname polkitd[1122]: Operator of unix-session:15 FAILED to authenticate to gain authorization for action org.freedesktop.policykit.exec for unix-process:20415:1687383 [cockpit-bridge] (owned by unix-user:ben2404)
Feb 23 12:18:40 hostname pkexec[20597]: ben2404: Error executing command as another user: Not authorized [USER=root] [TTY=unknown] [CWD=/run/user/1000] [COMMAND=/usr/bin/cockpit-bridge --privileged]
Feb 23 12:18:40 hostname cockpit-bridge[20415]: Error executing command as another user: Not authorized
Feb 23 12:18:40 hostname cockpit-bridge[20415]: This incident has been reported.
Feb 23 12:18:41 hostname audit[20612]: USER_CMD pid=20612 uid=1000 auid=1000 ses=15 msg='cwd="/run/user/1000" cmd=636F636B7069742D627269646765202D2D70726976696C65676564 terminal=? res=failed'
Feb 23 12:18:41 hostname sudo[20612]:  ben2404 : a password is required ; TTY=unknown ; PWD=/run/user/1000 ; USER=root ; COMMAND=/bin/cockpit-bridge --privileged
Feb 23 12:18:41 hostname cockpit-bridge[20415]: sudo: a password is required
Feb 23 12:18:41 hostname cockpit-bridge[20415]: http:///var/run/docker.sock/v1.12/events: couldn't connect: Permission denied
Feb 23 12:18:41 hostname cockpit-bridge[20415]: http:///var/run/docker.sock/v1.12/info: couldn't connect: Permission denied
Feb 23 12:18:41 hostname cockpit-bridge[20415]: http:///var/run/docker.sock/v1.12/info: couldn't connect: Permission denied
Feb 23 12:18:41 hostname cockpit-bridge[20415]: http:///var/run/docker.sock/v1.12/containers/json?all=1: couldn't connect: Permission denied
Feb 23 12:18:41 hostname cockpit-bridge[20415]: http:///var/run/docker.sock/v1.12/images/json: couldn't connect: Permission denied
Feb 23 12:18:41 hostname cockpit-bridge[20415]: http:///var/run/docker.sock/v1.12/info: couldn't connect: Permission denied
Feb 23 12:18:42 hostname cockpit-bridge[20415]: http:///var/run/docker.sock/v1.12/events: couldn't connect: Permission denied
```

Logging in with the root user shows that "Docker is not installed or activated on the system".
journalctl -f output:
```
Feb 23 12:17:26 hostname cockpit-bridge[19407]: http:///var/run/docker.sock/v1.12/events: couldn't connect: Connection refused
Feb 23 12:17:26 hostname cockpit-bridge[19407]: http:///var/run/docker.sock/v1.12/info: couldn't connect: Connection refused
Feb 23 12:17:26 hostname cockpit-bridge[19407]: http:///var/run/docker.sock/v1.12/info: couldn't connect: Connection refused
Feb 23 12:17:27 hostname cockpit-bridge[19407]: http:///var/run/docker.sock/v1.12/containers/json?all=1: couldn't connect: Connection refused
Feb 23 12:17:27 hostname cockpit-bridge[19407]: http:///var/run/docker.sock/v1.12/images/json: couldn't connect: Connection refused
Feb 23 12:17:27 hostname cockpit-bridge[19407]: http:///var/run/docker.sock/v1.12/info: couldn't connect: Connection refused
Feb 23 12:17:27 hostname cockpit-bridge[19407]: http:///var/run/docker.sock/v1.12/events: couldn't connect: Connection refused
Feb 23 12:17:30 hostname systemd[1]: Starting Docker Storage Setup...
Feb 23 12:17:30 hostname docker-storage-setup[20142]: INFO: Volume group backing root filesystem could not be determined
Feb 23 12:17:30 hostname docker-storage-setup[20142]: No valid volume group found. Exiting.
Feb 23 12:17:30 hostname systemd[1]: docker-storage-setup.service: Main process exited, code=exited, status=1/FAILURE
Feb 23 12:17:30 hostname systemd[1]: Failed to start Docker Storage Setup.
Feb 23 12:17:30 hostname systemd[1]: docker-storage-setup.service: Unit entered failed state.
Feb 23 12:17:30 hostname audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=docker-storage-setup comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Feb 23 12:17:30 hostname systemd[1]: docker-storage-setup.service: Failed with result 'exit-code'.
Feb 23 12:17:30 hostname systemd[1]: Started Docker Application Container Engine.
Feb 23 12:17:30 hostname cockpit-bridge[19407]: http:///var/run/docker.sock/v1.12/events: couldn't connect: Connection refused
Feb 23 12:17:30 hostname cockpit-bridge[19407]: http:///var/run/docker.sock/v1.12/info: couldn't connect: Connection refused
Feb 23 12:17:30 hostname cockpit-bridge[19407]: http:///var/run/docker.sock/v1.12/containers/json?all=1: couldn't connect: Connection refused
Feb 23 12:17:30 hostname cockpit-bridge[19407]: http:///var/run/docker.sock/v1.12/images/json: couldn't connect: Connection refused
Feb 23 12:17:36 hostname cockpit-bridge[19407]: http:///var/run/docker.sock/v1.12/info: couldn't connect: Connection refused
```

**Comment by stefwalter** [comment]
Lets first get it running as root. Does ```/var/run/docker.sock``` exist?

**Comment by brhahlen** [comment]
Yes:
```
# ll /var/run/docker.sock
srw-rw---- 1 root root 0 Feb 23 12:14 /var/run/docker.sock
```

**Comment by brhahlen** [comment]
I just realized: I am running docker in a secure setup. Could that be the problem?

**Comment by stefwalter** [comment]
And what does ```netstat -an | grep docker.sock``` say?

I'm trying to figure out why we're seeing ```Feb 23 12:17:26 hostname cockpit-bridge[19407]: http:///var/run/docker.sock/v1.12/events: couldn't connect: Connection refused``` when running as root.

**Comment by stefwalter** [comment]
Not sure what a 'secure setup' is.

**Comment by brhahlen** [comment]
Securing docker: https://docs.docker.com/engine/security/https/

Basically it needs to connect over https. I just disabled the docker.service.d/secure.conf and restarted docker, and now it works in cockpit.
The contents of the secure.conf are:
```
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon --tlsverify --tlscacert=/home/.docker/server/ca.pem --tlscert=/home/.docker/server/server-cert.pem --tlskey=/home/.docker/server/server-key.pem -H=hostname:2376
```

**Comment by brhahlen** [comment]
My .bashrc uses ```export DOCKER_HOST=tcp://XebTop:2376 DOCKER_TLS_VERIFY=1``` and I have a .docker directory in /home/user which has the certificates (see above).

**Comment by stefwalter** [comment]
Ok, that makes sense. Very likely /var/run/docker.sock was not even accessible. In addition, if TLS would have been required on that unix socket, it would have similarly failed.

It's as shame docker doesn't have a sane client config file for setting up this tls based mode. If it did, then we could add code to Cockpit to use it. As it stands, a variety of files and environment variables are required.

**Comment by brhahlen** [comment]
Yeah, that kind of sucks, was pretty hard to get working as well...
Then again, I am not sure whether I actually still need it, so might just disable it.
Thanks for the help!
