### ISSUE TITLE
Cannot reconnect to a machine - credentials are not offered

### ISSUE THREAD

**Issue by mykaul** [cockpit-project/cockpit#3800]
Seems that Cockpit does not store credentials to remote machines between runs.
I've updated to 0.95 and now it doesn't offer to type in the credentials again - just update the SSHd port.

**Comment by stefwalter** [comment]
What kind of credentials are you trying to store?

**Comment by mykaul** [comment]
I'm not sure if it stores them or not - SSH password. In any case, it should prompt for something (it did in 0.93!).

**Comment by stefwalter** [comment]
SSH passwords are not stored, just like SSH passwords on the command line are not stored. But yes, prompting again is important.

@mykaul Could you attach a screenshot of where you're seeing the problem? That'll make it easier to understand the behavioral change you're talking about.

@petervo Does this behavior change between 0.93 and 0.95 ring a bell?

**Comment by mykaul** [comment]
Strange - restarting cockpit solved it... That makes little sense to me - but now I did get the credentials popup correctly (and not the SSHd one).

**Comment by petervo** [comment]
Nothing in the ssh transport or machine-dialogs changed between those 2 versions. Though I'm unclear on what exactly the issue was. I'm closing this for now but if it reappears please reopen.
