### ISSUE TITLE
Performance tune = error - when logging to a remote machine with non-root user

### ISSUE THREAD

**Issue by mykaul** [cockpit-project/cockpit#3805]
if the user has no privs (I assume), an error is shown for the tuned profile for the remote machine. If I login as root, all is well and I see the correct tuned profile.

Cockpit 0.95 (though I've seen it in earlier versions too).

**Comment by whyoh** [comment]
i get this in my log file:

Apr 05 23:59:41 xxxxxx sudo[nnnnnn]:    yyyyy : **a password is required** ; TTY=unknown ; PWD=/run/user/mmmm ; USER=root ; COMMAND=/bin/cockpit-bridge --privileged

it might be affecting the "store performance data" button too.

**Comment by mvollmer** [comment]
This is fixed.
