### ISSUE TITLE
storage: browser back arrow is infinite loop when inspecting RAID devices

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3809]
New cockpit build from today.

Firefox 42.0.
1. In RAID devices panel, select a RAID device.
2. When on RAID device screen, select a disk from the Disks panel.
3. When on the disk device screen, press browser back button, return to RAID devices screen.
4. Press browser back button again, return to disk device screen.
5. Press browser back button again, return to RAID devices screen.
6. etc.

Breadcrumbs get me back to where I want to go just fine.

**Comment by mvollmer** [comment]
This happens anywhere, for example also with the Service overview and a single Service, or with the Accounts overview and a single Account.

**Comment by mvollmer** [comment]
This is still valid.

**Comment by marusak** [comment]
I opened #13091 to track this better, since this is happening on more places in cockpit and is not raid-devices specific.
