### ISSUE TITLE
storage: SSDs should be listed among "Drives" instead of among "Other Devices"

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3810]
Today's build.

On my system, I have two SSDs forming a RAID array. They show up ok under the Disks panel on the array information screen, but on the main screen they are listed under the "Other Devices" panel instead of the "Drives" panel. I _think_ they should properly belong in the "Drives" panel.

**Comment by mvollmer** [comment]
>  I think they should properly belong in the "Drives" panel.

They should indeed.

Could you attach the output of `storagectl dump` and `udevadm info /dev/NNN/` for the two devices?

**Comment by mulkieran** [comment]
Here it is:
[udevadm.info.txt](https://github.com/cockpit-project/cockpit/files/146763/udevadm.info.txt)
[storagedctl.dump.txt](https://github.com/cockpit-project/cockpit/files/146762/storagedctl.dump.txt)

I atttached the udevadm info for the parents of the two RAID member devices in question, too.

**Comment by mvollmer** [comment]
Please reopen if this still happens.
