### ISSUE TITLE
journal: problem with handling detail screen for log entry with no message

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3817]
It is possible to insert an entry with no message into the journal.

And Cockpit does the correct thing, and allocates a line for such an entry, just like every other entry.
But, if you select that entry, and go to the log entry detail screen, there is no message for that entry, and the message you see is the message from the previous selected entry.

**Comment by mulkieran** [comment]
If you go to the Journal and immediatley select a en entry with no message, there is no previously selected entry, and no message is shown in the message detail screen.

**Comment by mulkieran** [comment]
![screenshot from 2016-02-24 09-53-27](https://cloud.githubusercontent.com/assets/1218366/13289082/b6618064-dadc-11e5-999c-7dcef09e7df8.png)

This screenshot shows a journal entry. The entry actually has no MESSAGE field associated with it, but the value of the MESSAGE field from the previously selected entry is displayed, i.e., the comma separated list of numbers at the top.

**Comment by mvollmer** [comment]
I included a fix in #3833
