### ISSUE TITLE
journal: really large fields do not get terminated nicely in log entry detail screen

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3818]
They just keep going until they hit the right side scroll bar and disappear.

**Comment by andreasn** [comment]
Do you have a screenshot of that?

**Comment by mulkieran** [comment]
Here you go!

![screenshot from 2016-02-24 09-53-27](https://cloud.githubusercontent.com/assets/1218366/13289026/7d94cc32-dadc-11e5-87a5-7e6b816dd715.png)

**Comment by andreasn** [comment]
I think this is a white-space css property issue that we apply to all tables. I think I have a working solution for this.
