### ISSUE TITLE
Cant login after update

### ISSUE THREAD

**Issue by uacode** [cockpit-project/cockpit#3820]
```
[root@asterisk-2 ~]# dnf info installed cockpit
Last metadata expiration check performed 2:10:31 ago on Wed Feb 24 10:11:38 2016.
Installed Packages
Name        : cockpit
Arch        : x86_64
Epoch       : 0
Version     : 0.95
Release     : 1.fc23
Size        : 36 k
Repo        : @System
From repo   : updates
Summary     : A user interface for Linux servers
URL         : http://cockpit-project.org/
License     : LGPLv2+
Description : Cockpit runs in a browser and can manage your network of GNU/Linux
            : machines.

```

```
[root@asterisk-2 ~]# service cockpit status -l
Redirecting to /bin/systemctl status  -l cockpit.service
● cockpit.service - Cockpit Web Service
   Loaded: loaded (/usr/lib/systemd/system/cockpit.service; static; vendor preset: disabled)
   Active: active (running) since Wed 2016-02-24 12:10:35 EET; 3s ago
     Docs: man:cockpit-ws(8)
  Process: 3153 ExecStartPre=/usr/sbin/remotectl certificate --ensure --user=root --group=cockpit-ws --selinux-type=etc_t (code=exited, status=0/SUCCESS)
 Main PID: 3156 (cockpit-ws)
   CGroup: /system.slice/cockpit.service
           ├─3156 /usr/libexec/cockpit-ws
           └─3165 /usr/bin/ssh-agent

Feb 24 12:10:35 asterisk-2.lan systemd[1]: Starting Cockpit Web Service...
Feb 24 12:10:35 asterisk-2.lan systemd[1]: Started Cockpit Web Service.
Feb 24 12:10:35 asterisk-2.lan cockpit-ws[3156]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Feb 24 12:10:35 asterisk-2.lan cockpit-session[3160]: pam_ssh_add: Failed adding some keys
Feb 24 12:10:35 asterisk-2.lan cockpit-session[3160]: pam_limits(cockpit:session): Could not set limit for 'nofile': Operation not permitted
Feb 24 12:10:35 asterisk-2.lan cockpit-ws[3156]: cockpit-session: couldn't open session: root: Permission denied
```

Hello, after update I can't login :(
How to fix?

**Comment by stefwalter** [comment]
Can you log in via SSH using password based authentication? The failure seems to be in pam_limits.so which on Fedora is present in ```password-auth```.

Do you have any uncommented settings in ```/etc/security/limits.conf``` or in ```/etc/security/limits.d``` ... these files seem to affect ```pam_limits.so```

**Comment by stefwalter** [comment]
Is this related to: https://bugzilla.redhat.com/show_bug.cgi?id=485955

**Comment by uacode** [comment]
Thank you. I comment strings in /etc/security/limits.conf
root            soft    nofile          9000
root            hard    nofile          65000

And cockpit work again

**Comment by rjhowe** [comment]
This is still an issue. If nofile is set in /etc/security/limits.conf selinux blocks cockpit from making syscall setrlimit.   Was able to reproduce this in both RHEL 7 and Fedora 23

~% sudo  ausearch -i -m avc -ts recent
----
type=AVC msg=audit(12/07/2016 11:34:34.871:367) : avc:  denied  { sys_resource } for  pid=3483 comm=cockpit-session capability=sys_resource  scontext=system_u:system_r:cockpit_session_t:s0 tcontext=system_u:system_r:cockpit_session_t:s0 tclass=capability permissive=0 

Created bug on this for RHEL 7 
https://bugzilla.redhat.com/show_bug.cgi?id=1402495

**Comment by stefwalter** [comment]
@rjhowe Could you submit your exact contents of limits.conf that makes this bug happen. Then in the Cockpit project we can create a test that tracks this as a known issue. That said ... the issue is clearly with the SELinux policy, and not with Cockpit.
