### ISSUE TITLE
journal: not correct to assume values of all fields are text

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3825]
It is possible, although not really encouraged, to put binary data into the journal.

journalctl represents the inserted binary data thus:

```
JUNK=[39B blob data]
```

but Cockpit does:

![screenshot from 2016-02-24 11-02-11](https://cloud.githubusercontent.com/assets/1218366/13291521/13ab7cee-dae6-11e5-9310-cbb662c92661.png)

I think journalctl is doing a bit better by specifying that it the value is possibly unprintable binary data.

I think this issue is minor. The binary data must be terminated with a null character to avoid corrupting the journal, and how do you know that your binary data does not contain the null character within it, thus terminating prematurely? So, I can't see that binary data will be inserted in the journal that often, and so long as Cockpit does not suffer failure in displaying the data, there is probably no serious concern.

**Comment by mvollmer** [comment]
> The binary data must be terminated with a null character to avoid corrupting the journal

I think this is not true, but you would need to use sd_journal_sendv to add them to the journal.  Note that your example data contains a couple of internal zeros.

**Comment by mvollmer** [comment]
> I think journalctl is doing a bit better by specifying that it the value is possibly unprintable binary data.

Yes, we should definitely do the same.  Thanks for pointing this out!

**Comment by mvollmer** [comment]
Please try #3833.

**Comment by mulkieran** [comment]
You are right!

I have been recently corrupting my journal by writing large chunks of binary data to it
using the python-systemd API. I don't know what causes the corruption, but I do know it
is happening.

And I thought I'ld read about this null-termination issue, which made the
whole binary data option seem pretty useless anyway, even nonsensical.

Thanks for pointing out that I was mistaken.

I guess it's back to the debugging of my original corruption problem.

- mulhern


----- Original Message -----
