### ISSUE TITLE
Can't connect to Docker 400 400 Bad Request: malformed Host header

### ISSUE THREAD

**Issue by sjenning** [cockpit-project/cockpit#3828]
On the latest rawhide build, I see this error when going to the "Containers" tab.

Can't connect to Docker
400 400 Bad Request: malformed Host header

Could be related to Docker 1.10?

I've tried logged in a fedora user (in group docker) and as root.  I can reproduce on fedora cloud base with the  and atomic images using ```atomic run cockpit/ws```.

Docker is running:
```
[fedora@kube-master ~]$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

I am running 0.95:
```
$ dnf list installed cockpit*
Last metadata expiration check performed 0:03:12 ago on Wed Feb 24 18:17:41 2016.
Installed Packages
cockpit.x86_64                      0.95-1.fc24        @rawhide
cockpit-bridge.x86_64               0.95-1.fc24        @rawhide
cockpit-doc.x86_64                  0.95-1.fc24        @rawhide
cockpit-docker.x86_64               0.95-1.fc24        @rawhide
cockpit-kubernetes.x86_64           0.95-1.fc24        @rawhide
cockpit-networkmanager.noarch       0.95-1.fc24        @rawhide
cockpit-ostree.x86_64               0.95-1.fc24        @rawhide
cockpit-pcp.x86_64                  0.95-1.fc24        @rawhide
cockpit-shell.noarch                0.95-1.fc24        @rawhide
cockpit-sosreport.noarch            0.95-1.fc24        @rawhide
cockpit-storaged.noarch             0.95-1.fc24        @rawhide
cockpit-subscriptions.noarch        0.95-1.fc24        @rawhide
cockpit-ws.x86_64                   0.95-1.fc24        @rawhide
```

Docker version:
```
$ dnf list installed docker
Last metadata expiration check performed 0:03:26 ago on Wed Feb 24 18:17:41 2016.
Installed Packages
docker.x86_64        1:1.10.2-5.git0f5ac89.fc24        @rawhide
```

**Comment by stefwalter** [comment]
@mvollmer Is this related to the fixes you're doing for docker in fedora-testing?

**Comment by sjenning** [comment]
For good measure:
![Cockpit Docker 400 Error](https://www.variantweb.net/pub/cockpit-docker-400.png)

**Comment by jhdulaney** [comment]
I also am seeing this; there was an issue with docker on rawhide with missaligned assembly in go, but that has been resolved.

**Comment by mvollmer** [comment]
> @mvollmer Is this related to the fixes you're doing for docker in fedora-testing?

I don't recognize the exact error message, but it might well be.  We do have problems with Docker 1.10 in general.

**Comment by stefwalter** [comment]
This is about a change in golang

https://groups.google.com/forum/#!topic/golang-codereviews/CPeFXzMJRzI
