### ISSUE TITLE
Attaching via kubectl broken 

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#3835]
https://bugzilla.redhat.com/show_bug.cgi?id=1311861
https://github.com/fsouza/go-dockerclient/issues/455

**Comment by stefwalter** [comment]
CC @ingvagabund This causes Cockpit to fail with fedora-testing (and fedora-rawhide?)

**Comment by ingvagabund** [comment]
New build for f23,f24,rawhide on its way.

**Comment by stefwalter** [comment]
@ingvagabund Thanks!

**Comment by ingvagabund** [comment]
@stefwalter can you test the latest build for f23 [1]? I can not start kube-controller-manager. It fails with
```
F0225 14:19:49.455598    9568 controllermanager.go:249] Failed to get supported resources from server: the server could not find the requested resource
```

I believe it is kubeconfig related only. With the correct configuration it will work.

[1] http://koji.fedoraproject.org/koji/buildinfo?buildID=738830

**Comment by cockpituous** [comment]
Ooops, it happened again
```
Traceback (most recent call last):
  File "kubelib.py", line 199, in testDashboard
    self.check_shell(b)
  File "kubelib.py", line 82, in check_shell
    b.wait_in_text(".listing-panel .terminal div:nth-child(1)", "#")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 651, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 674, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by ingvagabund** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2016-8bc7ba5f6b
At the same time, all commands (up to kube-apiserver) are hardlinks to hyperkube binary.
