### ISSUE TITLE
accounts: tooltip over "Create New Account" button slides under the main menu bar

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3851]
Generally I log into Cockpit not as root user.

Therefore, if I go to the Accounts tool, I don't have privileges to create a new account. For this reason, the "Create New Account" button is inactive, which is good. But, if I hover over the button, a grey tooltip appears above it (probably telling me that user so-and-so is not permitted to create new accounts). However, I can only see the bottom edge of this tooltip, the rest disappears under the main menu bar, specifically it is obscured by the Dashboard and Cluster button in the menu bar.

**Comment by stefwalter** [comment]
@mulkieran Could you attach a screenshot?

**Comment by mulkieran** [comment]
I'm afraid not, can't get around gnome-screenshot bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1237128.

**Comment by stefwalter** [comment]
Unfortunately haven't heard back from the reporter. Closing this issue.
