### ISSUE TITLE
Drop down menu in right hand corner of "RAID device" panel is skittish

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3853]
![screenshot from 2016-02-26 15-51-40](https://cloud.githubusercontent.com/assets/1218366/13365065/da3a9208-dca0-11e5-878f-99c8f6bcb5c7.png)

Click on the little down arrow and the list of options will appear, but actually selecting them is really hard because the list will disappear while you're trying to select one of the options. it took me about 15 tries to select the option I wanted, 'Delete", from the list of 5 options. I think it's the hardest, because it is the bottom one.

**Comment by andreasn** [comment]
I haven't seen the behavior with disappearing entrys.
Would you be able to do a quick screencast?

**Comment by mulkieran** [comment]
'pologies, it looks like this was just a problem with Firefox instance running on my machine.

**Comment by andreasn** [comment]
No worries, good to have it tracked down.
