### ISSUE TITLE
Blank a plot of memory in menu containers and some error in JS console

### ISSUE THREAD

**Issue by crestone** [cockpit-project/cockpit#3862]
I see some trouble with a memory plot in **Cockpit UI** -> **Docker containers menu**
you can see on the picture:

![screenshot from 2016-02-29 16-26-02](https://cloud.githubusercontent.com/assets/13472712/13397780/1cf8fc1e-df04-11e5-83e9-9e3ab9c03b84.png)

I mean blank a plot of memory named as "Combined memory usage" and some errors in JS console.
output of Chromium console:

![screenshot from 2016-02-29 16-28-37](https://cloud.githubusercontent.com/assets/13472712/13397806/37c2fa36-df04-11e5-96b8-8e8e3770ed6a.png)

I see this bug only for this server, RAM on board is 32GB

Client:
Chromium 47.0.2526.106
Cockpit 0.95-1.fc23

Server:
CentOS Linux release 7.2.1511 (Core)
cockpit-docker 0.93-3.el7.centos.0.1 (from CentOS 7 Extras Repo)

And what I tried:
- updating Cockpit - cockpit-0.93-1.fc23.x86_64 -> cockpit-0.95-1.fc23.x86_64 (before on 0.93 I saw this error too and then was updated to 0.95);
- refreshing page (F5), clearing chache;
- restarting Cockpit service;
- removing this server setting from UI and adding then.

**Comment by crestone** [comment]
And what I tried:
- updating Cockpit - cockpit-0.93-1.fc23.x86_64 -> cockpit-0.95-1.fc23.x86_64 (before on 0.93 I saw this error too and then was updated to 0.95);
- refreshing page (F5), clearing chache;
- restarting Cockpit service;
- removing this server setting from UI and adding then.

**Comment by mvollmer** [comment]
Does this till happen?  Please reopen if it does.
