### ISSUE TITLE
storage: general idea of "not in normal state"

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3865]
It would be nice if main storage screen showed an alert for particular devices in more situations than it actually does.

For example, if I go to the detail screen for md-ssd RAID device, it very clearly shows that the device is degraded and is resyncing, but on the main storage screen there is no indication of that. These SSDs only take about 1/2 hour to resync, but arrays on standard disks can take a day or two (and rising), and while they are resyncing they are especially vulnerable.

There is no indication on the main screen when the array is degraded but not resyncing, either.

I don't think details of the problem on the main screen make any sense, but just a warning symbol indicating that the the device could use some inspection.

Generally speaking, I think the idea of not-normal state could be extended to a lot of devices and maybe file systems as well, and could possibly make sense divided into categories, like: vulnerable but recovering, needs help, dead, very busy.

**Comment by andreasn** [comment]
I did some mockups that incorporated the idea of this for the Troubleshooting feature
https://github.com/cockpit-project/cockpit/wiki/Feature:-Troubleshooting

https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/troubleshooting/troubleshooting.png

**Comment by andreasn** [comment]
In this mockup, the devices that needs attention has an error icon instead of the device icon, and the mount that is close to running out of space has a red color.

**Comment by mulkieran** [comment]
Looks good! Do you accept PRs for the wiki?

**Comment by andreasn** [comment]
Yeah, sure.
If you want to leave feedback on the page directly without a PR, I think I can add you to contributors directly.

**Comment by andreasn** [comment]
I invited you to "Contributors". Did that work?

**Comment by mulkieran** [comment]
Yes, thanks.

- mulhern

----- Original Message -----

**Comment by mvollmer** [comment]
This is tracked in the Wiki already.
