### ISSUE TITLE
journal: display of log entries comment

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3869]
It would be helpful if the log entry fields were visually grouped by their category in the man page entry for systemd.journal-fields. I think they are already sorted by these categories and then sorted alphabetically. But this is not really obvious at first.

Also, if the entry fields were visually grouped it might be helpful to hide the fields in the ADDRESS FIELDS category. They are mostly internal, used for navigation by other tools. In particular, the __CURSOR field is going to convey very little info to your typical sysadmin.

Also, the MESSAGE_ID field is a very special one and maybe should get special placing, like the MESSAGE field. And, as suggested in #53, be used to display the catalog description for the entry.

**Comment by marusak** [comment]
This is something we would most likely do together with #1108 s I'll close this in favour of the other issue and comment there.
