### ISSUE TITLE
Cache headers

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#3877]
I think we need the following changes to our cache headers.

1) login.html should always explicitly set Cache-Control: no-cache.
2) Whenever we serve the shell html, we should: Vary: Cookie.
3) Whenever we don't explicitly set cache headers, we should Vary: Cookie.

@stefwalter if you agree i can make these changes.

**Comment by stefwalter** [comment]
These make sense. But I'm interested in the "Why"? Or what went wrong?

**Comment by petervo** [comment]
If the cookie is cleared or changed, Vary: Cookie is enough. But if we can't rely on that for embedded we might need to.

**Comment by stefwalter** [comment]
That makes sense.
