### ISSUE TITLE
storage: another funky multipath situation

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3882]
In this one, the disk is multipathed correctly, but the multipath device shows up in "Other Devices" and the drive is shown as a multipathed drive, but without its multipath 'Device File' entry.

![screenshot from 2016-03-01 17-07-45](https://cloud.githubusercontent.com/assets/1218366/13443681/263d429a-dfd0-11e5-9cad-5494cfea945f.png)
![screenshot from 2016-03-01 17-07-05](https://cloud.githubusercontent.com/assets/1218366/13443682/264a6fce-dfd0-11e5-8b5a-2a56b68c1684.png)

This drive was unmultipathed for a while, but is now correctly multipathed.

Output of multipath -ll:

```
350014ee5aaab876c dm-8 WD      ,WD4001FYYG-01SL3
size=3.6T features='0' hwhandler='0' wp=rw
|-+- policy='service-time 0' prio=1 status=active
| `- 0:0:35:0 sdai 66:32  active ready running
`-+- policy='service-time 0' prio=1 status=enabled
  `- 0:0:40:0 sdam 66:96  active ready running
```

and of my plugin:

![screenshot from 2016-03-01 17-12-00](https://cloud.githubusercontent.com/assets/1218366/13443789/bfdcef36-dfd0-11e5-985f-4333ae110a5c.png)

This problem survived me logging out and logging in again, but went away when I stopped cockpit and restarted it.

**Comment by andreasn** [comment]
@mvollmer any idea what's up here?

**Comment by mvollmer** [comment]
> @mvollmer, any idea about this?

No, unfortunately not.  We would need a reproducer to start working on this.

**Comment by marusak** [comment]
Way too old, and also no reproducer.
