### ISSUE TITLE
storage: desirable to group drives by physical attributes and/or perfomance behavior

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3883]
It is desirable to group drives, which are themselves physical, by the physical attributes that affect them.

It is also the case that appropriate physical attributes can vary among drives.

I've written a simple plugin that sorts drives by enclosure. Here's a very ugly screenshot (thanks for the help w/ the plugin).

![screenshot from 2016-03-01 16-49-19](https://cloud.githubusercontent.com/assets/1218366/13443113/96807048-dfcd-11e5-8c5e-765ffb145ce2.png)

Note some unfortunate things, like that an enclosure has no definite name. I'm showing the names of the two sysfs devices that represent the distinct paths to the enclosure in the top bar.

Note also that not all drives are organized by enclosure, so this sorting approach would be inadequate in a different setup. Sorting by enclosure would be a good first step, however, and one could gradually begin to sort by other things as well.

One important reason to motivate sorting in this physical fashion is the organization of .e.g., RAID devices. In creating a RAID device, a conscientious storage administrator would probably prefer to distribute the members to different physical locations. The strategy for distributing the members would vary with the RAID level, but the result would be that if power is lost to one enclosure, the data would not be lost. This principle could be extended to distributing components of networked storage across geographical locations.

I also think that this consideration should be taken into account when considering the UI for, e.g., RAID device creation.

**Comment by mulkieran** [comment]
It would also be nice to be able to sort or group devices by their performance characters, like topio.

**Comment by mvollmer** [comment]
I have copied this into our secret planning tool to track it better.  Closing here.
