### ISSUE TITLE
storage: another multipath possibility

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3895]
What I did was create a RAID 5 array, with one drive in one enclosure and the rest in another, for a test. 
Each of the members of the array was a partition of a multipath device.
Then I turned one enclosure off, the one with a single drive.
Cockpit updated its lists of drives nicel and the missing drives no longer appear. mdadm did not detect any problems with the array, partly because multipath didn't detect that its device paths had gone missing, and Cockpit doesn't detect anything wrong with the array either.

If I select the RAID member (a partition device) that no longer has a drive, I see the following screen:

![screenshot from 2016-03-02 16-49-11](https://cloud.githubusercontent.com/assets/1218366/13476627/b9ed9ae6-e096-11e5-8653-e3537d37a3b4.png)

This is a multipath device which has lost its paths, but it is still a multipath device. Therefore, there should still be a line for Multipathed Devices, but no values for that line.

My guess is that something, maybe storaged, is setting the Multipath attribute to false, so the display takes the path for non-multipathed devices. Here's what the RAID array screen looks like:
![screenshot from 2016-03-02 16-53-46](https://cloud.githubusercontent.com/assets/1218366/13476787/6f1aa24c-e097-11e5-8e5b-e63dbc430b54.png)

Here's the udevadm info for the multipath device:

```
P: /devices/virtual/block/dm-12
N: dm-12
L: 10
S: disk/by-id/dm-name-WDC_WD10EFRX-68PJCN0_WD-WCC4JLHVDELY
S: disk/by-id/dm-uuid-mpath-WDC_WD10EFRX-68PJCN0_WD-WCC4JLHVDELY
S: mapper/WDC_WD10EFRX-68PJCN0_WD-WCC4JLHVDELY
E: DEVLINKS=/dev/disk/by-id/dm-name-WDC_WD10EFRX-68PJCN0_WD-WCC4JLHVDELY /dev/disk/by-id/dm-uuid-mpath-WDC_WD10EFRX-68PJCN0_WD-WCC4JLHVDELY /dev/mapper/WDC_WD10EFRX-68PJCN0_WD-WCC4JLHVDELY
E: DEVNAME=/dev/dm-12
E: DEVPATH=/devices/virtual/block/dm-12
E: DEVTYPE=disk
E: DM_ACTIVATION=0
E: DM_MULTIPATH_TIMESTAMP=1456929727
E: DM_NAME=WDC_WD10EFRX-68PJCN0_WD-WCC4JLHVDELY
E: DM_SUBSYSTEM_UDEV_FLAG0=1
E: DM_SUSPENDED=0
E: DM_UDEV_DISABLE_LIBRARY_FALLBACK_FLAG=1
E: DM_UDEV_PRIMARY_SOURCE_FLAG=1
E: DM_UDEV_RULES_VSN=2
E: DM_UUID=mpath-WDC_WD10EFRX-68PJCN0_WD-WCC4JLHVDELY
E: ID_PART_TABLE_TYPE=gpt
E: MAJOR=253
E: MINOR=12
E: MPATH_SBIN_PATH=/sbin
E: SUBSYSTEM=block
E: TAGS=:systemd:
E: USEC_INITIALIZED=32939
```

**Comment by mulkieran** [comment]
When I brought storage backup the devices got appropriately filled in, but there was still some information, like WWN, missing.
![screenshot from 2016-03-03 10-51-31](https://cloud.githubusercontent.com/assets/1218366/13499871/03eb89f4-e12e-11e5-9d33-24891b98d20a.png)

Output of storagedctl dump
```
/org/storaged/Storaged/block_devices/dm_2d12:
  org.storaged.Storaged.Block:
    Configuration:              []
    CryptoBackingDevice:        '/'
    Device:                     /dev/dm-12
    DeviceNumber:               64780
    Drive:                      '/org/storaged/Storaged/drives/WDC_WD10EFRX_68PJCN0_WD_WCC4JLHVDELY'
    HintAuto:                   false
    HintIconName:               
    HintIgnore:                 false
    HintName:                   
    HintPartitionable:          false
    HintSymbolicIconName:       
    HintSystem:                 true
    Id:                         by-id-dm-name-WDC_WD10EFRX-68PJCN0_WD-WCC4JLHVDELY
    IdLabel:                    
    IdType:                     
    IdUUID:                     
    IdUsage:                    
    IdVersion:                  
    MDRaid:                     '/'
    MDRaidMember:               '/'
    PreferredDevice:            /dev/mapper/WDC_WD10EFRX-68PJCN0_WD-WCC4JLHVDELY
    ReadOnly:                   false
    Size:                       1000204886016
    Symlinks:                   /dev/disk/by-id/dm-name-WDC_WD10EFRX-68PJCN0_WD-WCC4JLHVDELY
                                /dev/disk/by-id/dm-uuid-mpath-WDC_WD10EFRX-68PJCN0_WD-WCC4JLHVDELY
                                /dev/mapper/WDC_WD10EFRX-68PJCN0_WD-WCC4JLHVDELY
  org.storaged.Storaged.PartitionTable:
    Type:               gpt
```

Logging out and logging in again makes no difference, nor stoppimg and starting Cockpit via ```systemclt stop cockpit```, ```systemctl start cockpit```.

**Comment by mvollmer** [comment]
This would be a part of a general "make multipath work robustly" effort.  I'll collect this and similar issues into our secret planning tool.
