### ISSUE TITLE
general: improve truncated labels

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#3904]
There are 2 related parts:
1. Truncation should be smarter, so that important details (especially end of string) is not cut.
2. Tooltips should appear when labels are truncated (but not when the full label is displayed).

I have written some example code that does the above in pure HTML+CSS and does not rely on JavaScript for truncation.

**Demo**: http://codepen.io/garrett/pen/VaLGzw
## 

This code, while simple, would need to be adapted slightly to Cockpit so that it:
- Uses Patternfly-friendly classes
- Takes advantage of Patternfly-styled tooltips (instead of relying on browser-based title tooltips)
- Adheres to Cockpit CSS & JS standards
## 

_Note: Plain text strings would be required to be parsed and split to indicate the important parts. For example, in the Containers section, the container image names and image tag names would need to be split apart by `/`, and rejoined with wrapping everything but the end in the "truncatable" class. (It's optional to have something like an "important" class on the last part. I've included that in the demo just to highlight that the two pieces are split apart.)_

**Comment by andreasn** [comment]
Does the tooltips have any certain location?
Can we put them on top of the objects with a little arrow, such as the tooltips here on github?

**Comment by andreasn** [comment]
Is the container page a good first candidate for this? Or should we do it with a broader brush?

**Comment by andreasn** [comment]
The storage page (on non-atomic system) have some issues with this as well.
Both in the dialogs and in the device list in the sidebar

**Comment by garrett** [comment]
I do not suggest using the browser-based tooltips. I just didn't want to include extra stuff in the demo. The code can easily be adapted for any tooltip library (or any framework that provides tooltips, like Bootstrap/Patternfly/etc.)

The container page is why I brought this up, but I think it should be implemented with a broader brush, hence "general:" in the issue title.

This technique should be generic and flexible enough to implement it everywhere. The smart priority truncation requires splitting strings into two and wrapping them, but the tooltip detection method (if a tooltip of additional data is needed) is really simple and should be enabled everywhere (via delegation, naturally).

So, yes, there are two parts, but they're possibly intertwined. They might be two separate pull requests, or they could possibly be in one. It's at your discretion.

**Comment by garrett** [comment]
Implementing this across Cockpit also would help fix things like log entries, journal pages (linked from log entries), the overview info on the Dashboard page, and so on…

**Comment by larskarlitski** [comment]
@garrett, does it still make sense to keep this bug open? It will be hard to mark it as "done", as it will probably always apply to some parts of cockpit.

**Comment by garrett** [comment]
Wow! This is an old bug.

It's probably valuable to implement this.

I've forked my codepen and altered it to be flex-based, which makes it less CSS and implemented a little more cleanly: https://codepen.io/garrett/pen/vPxVMP

**Comment by garrett** [comment]
@larskarlitski: I think it's more about making a React widget that can be used so that Cockpit can implement this in places where it really would benefit from.

That is: Any place where we want to be able to truncate strings and have parts not be truncated. Primary usages would be: a full path with the filename not truncated or a URL that shows the last part untruncated.

It's probably worth re-doing this using flex instead of floats. And it's possibly worth considering it as a PF4 component.

**Comment by KKoukiou** [comment]
So PF4 on some component automatically truncates the text. We rarely handle that manually and it's the way it should be. I suggest if we notice some incorrect overflow we can address it but I don't see the reason to keep this issue open.
