### ISSUE TITLE
containers: incorrect alignment of container size labels

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#3905]
Container sizes are aligned in a wonky way.

This picture illustrates the issue (look at the entire size column):
![container-size-problematic-alignment](https://cloud.githubusercontent.com/assets/10246/13494042/25d13302-e142-11e5-81ed-80bd657fe7a4.png)

--

Note: In proportional fonts, as both numbers and units vary in width, sizes are best aligned with the numbers aligned to the right and the units aligned to the left, so the spacing between each is consistant and the list is easily scannable.

Somewhat ironically, I'll use monospaced fonts to illustrate the alignment:
```
101 megabytes
 24 kilobytes
  1 byte
```

In CSS, one technique is to align to the right and fix the min-size of the units, and set a style in the class of the units to use a consistent min-width.

Another approach is to align to the left and set the min-width property of the value instead. However, as the value is much more variable than the unit (especially with unit abbreviations), the first technique is often preferred.

In both approaches, min-width is preferred to just using plain width, to prioritize displaying of information with wonky alignment over cutting off the information. Also, min-width should be set to use the `ex` size, as it referrs to character width (based on a standard `x` character in the same font). Therefore, you can have a pretty good estimation of the width based on whatever the element's font size is — without having to guess with pixels, points, or relative ems.

**Comment by andreasn** [comment]
I'm unable to reproduce this on my system.

**Comment by andreasn** [comment]
I was able to kind of reproduce it by:
* Stopping a container
* Logging out
* Logging in again

**Comment by dperpeet** [comment]
I'm not sure we have to left align the units so the right aligned numbers look better. Aligning the numbers allows easier comparison, right? But what use is that if the magnitude is different (different unit)?
I think making the right side look ragged would detract from the overall look.
@garrett maybe you could make a mockup for this?
