### ISSUE TITLE
storage: multipathed devices offline not shown (assessment info too optimistic)

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3913]
If I take devices belonging to a multipath group offline, this is not well detected.
In the shot below, sdk and sdaa are both offline, but this is not shown in the detail.

![screenshot from 2016-03-03 17-12-11](https://cloud.githubusercontent.com/assets/1218366/13511374/1724aef8-e163-11e5-8435-7934afeb8866.png)

There is a sense in which storaged has noticed the problem, as it logs a few journal entries indicating failure to properly read the status of the backing storage device.

![screenshot from 2016-03-03 17-16-00](https://cloud.githubusercontent.com/assets/1218366/13511481/b2c07f36-e163-11e5-8854-43ba65d3c602.png)
![screenshot from 2016-03-03 17-14-54](https://cloud.githubusercontent.com/assets/1218366/13511482/b2c29d20-e163-11e5-8784-a8b91e5b7526.png)

I think that if it can't read the SMART data, it should change the Assessment value to something less positive than OK (assuming that the assessment is derived from the SMART data).

**Comment by mvollmer** [comment]
What does it mean for a block device to be off-line? If you disconnect a drive, shouldn't the block device disappear completely?
