### ISSUE TITLE
print to stdout: Resource temporarily unavailable

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#3915]
Hi,
@stefwalter found that https://github.com/cockpit-project/cockpit/pull/3909 found issue in Machine class in execute command what causes IOError and EAGAIN should be handled inside machine.execute

```
Traceback (most recent call last):
  File "./avocado/run-tests", line 256, in <module>
    sys.exit(main())
  File "./avocado/run-tests", line 250, in main
    if run_avocado(opts.tests, opts.verbosity, opts.browser, opts.download_logs):
  File "./avocado/run-tests", line 187, in run_avocado
    success = run_avocado_tests(machine, avocado_tests, env=env)
  File "./avocado/run-tests", line 122, in run_avocado_tests
    tap_output(machine)
  File "./avocado/run-tests", line 70, in tap_output
    print machine.execute(command="cat " + test_log, quiet=True)
IOError: [Errno 11] Resource temporarily unavailable
```

**Comment by stefwalter** [comment]
This is a strange bug, but it's not happening during the execute function. Otherwise the stack trace would be deeper. It's happening during the "print" statement.

**Comment by jscotka** [comment]
With some workaround in run-test file, it provides better output in case of traceback
https://fedorapeople.org/groups/cockpit/logs/pull-3909-5deb5a54-selenium-chrome/log.html
It seems that domain was destroyed when output (full log has 455kB)
```
...
05:32:53 INFO | {u'timestamp': 1457087472635, u'message': u'org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Done: [is displayed: 6 [[ChromeDriver: chrome on LINUX (3b96ae4d830497c70cf3c0c76ef77f92)] -> id: journal]]', u'level': u'INFO'} 05:32:53 INFO | {u'timestamp': 1457087472639, u'mess[1457087602.87] EVENT: Domain 'fedora-23-ka5u' (ID -1) Stopped Destroyed [1457087603.07] EVENT: Domain 'selenium-74c8' (ID -1) Stopped Destroyed ERROR: Unable to fetch testlog from remote machine: /root/avocado_results/job-2016-03-04T05.30-32d659e/test-results/tmp/avocado_tests/selenium-login.py:BasicTestSuite.test80ChangeTabTools/debug.log [Errno 11] Resource temporarily unavailable # TEST LOG END ------- not ok 8 /tmp/avocado_tests/selenium-login.py:BasicTestSuite.test80ChangeTabTools (time 80 secs) 
```

**Comment by jscotka** [comment]
reproducer could be:
[debug.log.zip](https://github.com/cockpit-project/cockpit/files/158627/debug.log.zip)
```
machine.upload(attached_file)
print machine.execute(command="cat " + uploaded_file, quiet=True)
```

**Comment by jscotka** [comment]
There will be also some other issue, I'te tested on F23:
machine = testvm.VirtMachine(verbose=True, label="avocado")
machine.start()
machine.upload(["debug.log"],"/tmp/")
print machine.execute("cat /tmp/debug.log", quiet=True)

and it works as expected. (Doesn selenium tests run on F-23 orit uses rhel-7 images)
So it is stranger than I can debug.

**Comment by jscotka** [comment]
It reminds me, that this function is called on host, not on guest, so that if host is for example some older fedora than mine, or rhel7. This could be reason, why I was unable to reproduce this issue locally
