### ISSUE TITLE
storage: UI prevents me from making a 1 KiB sized partition

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3920]
![screenshot from 2016-03-04 10-03-34](https://cloud.githubusercontent.com/assets/1218366/13530638/66732362-e1f0-11e5-92c0-9bca25e9721b.png)
![screenshot from 2016-03-04 10-01-55](https://cloud.githubusercontent.com/assets/1218366/13530649/716d0a8a-e1f0-11e5-9c8c-87703d030bf7.png)

**Comment by mulkieran** [comment]
But it is too accepting of a negative sized partition.

![screenshot from 2016-03-04 15-31-06](https://cloud.githubusercontent.com/assets/1218366/13539411/36a31c5e-e21e-11e5-82b3-40d0b6c08eee.png)

Clearly the first problem is a consequence of the fact that all values are truncated using parseInt(). My feeling is that it is sometimes necessary to work in fractions of a MiB, but that entry of address ranges in GUI is generally speaking a hard problem. Between parseInt() and parseFloat(), parseInt() is definitely the better choice.

I've put together a PR for the negative size, it is a trivial problem.

**Comment by mvollmer** [comment]
@mulkieran, please check #3876, it replaces the naive text inputs with sliders.

**Comment by mvollmer** [comment]
#3876 improves this a lot, although one still can't make a partition of size 1kiB.  The smallest size Cockpit supports is 1MiB.
