### ISSUE TITLE
Ubuntu 15.10

### ISSUE THREAD

**Issue by twizod** [cockpit-project/cockpit#3927]
Process: 934 ExecStartPre=/usr/sbin/remotectl certificate --ensure --user=root --group= --selinux-type= (code=exited, status=1/FAILURE)
Mar 05 05:19:39 ubuntu4 systemd[1]: Failed to start Cockpit Web Service.

Edited:
vi /lib/systemd/system/cockpit.service
Commented out selinux
Reran: 
 sudo systemctl start cockpit
It executed without complaining but it never started.

I followed the three simple steps to install it on ubuntu 15.10 Wily and this was my result.
I do not have selinux running.

**Comment by twizod** [comment]
Mar 05 05:36:16 ubuntu4 systemd[1]: Stopped Cockpit Web Service.
Mar 05 05:36:16 ubuntu4 systemd[1]: Started Cockpit Web Service.
Mar 05 05:36:16 ubuntu4 cockpit-ws[1026]: cockpit-ws: /etc/cockpit/ws-certs.d/0-self-signed.cert: TLS support is not available
Mar 05 05:36:16 ubuntu4 systemd[1]: cockpit.service: Main process exited, code=exited, status=1/FAILURE
Mar 05 05:36:16 ubuntu4 systemd[1]: cockpit.service: Unit entered failed state.
Mar 05 05:36:16 ubuntu4 systemd[1]: cockpit.service: Failed with result 'exit-code'.

**Comment by twizod** [comment]
Nevermind close case.
I had to install glib-networking
Why was this not part of the installation process?

**Comment by stefwalter** [comment]
What version are you using on Ubuntu?

**Comment by twizod** [comment]
I did the full install from ISO for Ubuntu 15.10 and it doesn't look like glib-networking comes with it from what I am seeing.  Does that help?

**Comment by twizod** [comment]
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily

**Comment by larsu** [comment]
I think Stef meant which version of Cockpit you're running.

Are you running it from Jared Sutton's PPA [1]? That seems to be based on the debian packaging we have upstream, which is indeed missing glib-networking as a dependency of cockpit-ws. Thanks for the catch!

[1] https://launchpad.net/~jpsutton/+archive/ubuntu/cockpit
