### ISSUE TITLE
RFE: storage tab - reorder the boxes on the left - drives, volume groups, RAID

### ISSUE THREAD

**Issue by mykaul** [cockpit-project/cockpit#3934]
The usability dictates that first of all you'll show the drives, then the VGs, and lastly the RAID devices - how many are going to use the RAID '+' vs. , for example, looking at the drives performance or the VGs?

**Comment by cmurf** [comment]
Depends on whether this is mdadm or LVM managed RAID. Typically it's drives>mdadm>PV>VG>LV. If it uses LVM managed RAID, then this is a function of the LV itself. I haven't looked at the code so I'm not sure which md front end is being used.

**Comment by mvollmer** [comment]
> Depends on whether this is mdadm or LVM managed RAID.

mdadm.  LVM managed raid should come 'soon'.

**Comment by mvollmer** [comment]
I think we will have to collapse all the panels into a single one so that people only see what they have, in  some sensible order.  Maybe alphabetical by name?

**Comment by KKoukiou** [comment]
The storage page had been redigned and currently looks like this - which in my opinion resolves this issue.
![Screen Shot 2020-03-25 at 21 08 28](https://user-images.githubusercontent.com/14921356/77580800-e7db7080-6edc-11ea-8fcf-d74ad109c221.png)
