### ISSUE TITLE
RFE: Add 'fstrim' option to mount points

### ISSUE THREAD

**Issue by mykaul** [cockpit-project/cockpit#3935]
It'd be great if one could run 'fstrim' on a mount point. Currently, it is not available.

**Comment by mvollmer** [comment]
What is fstrim, the new defrag? :-)

The best thing would be that users don't need to run fstrim, of course. Can we detect when it might be necessary/beneficial to run fstrim?

What would a good menu entry be for this?  "Optimize Disk"?

We already have a similar "i don't know what it does but it sounds good" entry for RAIDs: "Start scrubbing".  I think we could do a better job there as well.

And let's not forget that expert users can use the Terminal so this is more about helping people discover that fstrim exists can do something good for them, than it is to make something possible that is only rarely needed by experts.

**Comment by mykaul** [comment]
fstrim runs weekly via systemd's scheduler. I think the idea is to run it on demand.
It does not optimize the disk, it trims (sends UNMAP) commands to the underlying storage, thus freeing space. Mainly useful for thin-provisioned disks (in the past, for SSDs as well).

Experts of course can use the terminal, but then again, they could do everything via the terminal.

**Comment by mvollmer** [comment]
> fstrim runs weekly via systemd's scheduler. I think the idea is to run it on demand.

How do people know that it would be a good idea to run fstrim now?  Can we help them?

**Comment by mykaul** [comment]
On Mon, Mar 7, 2016 at 2:37 PM, Marius Vollmer <notifications@github.com>
wrote:

> fstrim runs weekly via systemd's scheduler. I think the idea is to run it
> on demand.
>
> How do people know that it would be a good idea to run fstrim now? Can we
> help them?
>

I'm not aware of a good way. I doubt there's any counter.
Y.

**Comment by cmurf** [comment]
I'm unconvinced this needs any UI prominence at all. I see no good use case for running it on demand. If the workload dictates running it daily, then change the timer to run it daily?

Eventually everything will properly support queued-trim (SATA rev 3.1) and 'discard' mount option is the way to go. So I can already foresee the obsolescence of this feature. Once a week is fine. The open question is whether it's safe now to enable fstrim.timer by default, and whether that's an upstream systemd question or a distro question.

**Comment by mvollmer** [comment]
Another idea is to prompt people to enable fstrim.timer on a system where it might have benefits, similar to how we prompt people to enable the multipath daemon on systems with multipath devices.

What would the criteria be for enabling fstrim.timer?  At least one SSD present?

**Comment by mykaul** [comment]
Yes, essentially I'd look at /sys/block/<disk>/queue/rotational and if it's equal 0 - run it. (It can be an iSCSI or FC target, so I would not look for a different property to identify it as a SSD).
Or perhaps just look if the device supports discard via /sys/block/<disk>/queue/discard_granularity != 0

**Comment by mvollmer** [comment]
Okay, what about this:

- We assume that fstrim.timer is enabled by default.  There is no down-side to enabling it that I can see.

- We put a "Trim Filesystem" command into the menu for block devices with /sys/block//queue/discard_granularity != 0 and a filesystem.  It is enabled when the filesystem is mounted.  It will run "fstrim <mountpoint>" in the background as a "job".

This should be quite straightforward via a couple of Storaged additions.

**Comment by cmurf** [comment]
Also useful if it applies to LVM thinp logical volumes. Even if HDD is used, fstrim causes unused logical extents in the LV to be returned to the volume group for use by any other thinp LV.

**Comment by mvollmer** [comment]
> Also useful if it applies to LVM thinp logical volumes. Even if HDD is used, fstrim causes unused logical extents in the LV to be returned to the volume group for use by any other thinp LV.

Does the block of the logical volume have queue/discard_granularity != 0?

**Comment by cmurf** [comment]
[root@f24s ~]# cat /sys/block/dm-5/queue/rotational 
1
[root@f24s ~]# cat /sys/block/dm-5/queue/discard_granularity 
65536

**Comment by mvollmer** [comment]
> [root@f24s ~]# cat /sys/block/dm-5/queue/discard_granularity
> 65536

Cool, thanks.

**Comment by martinpitt** [comment]
Indeed this should be handled by the OS itself, through `fstrim.timer`.

Or a cron job solution, as proposed to Debian](https://bugs.debian.org/732054).
