### ISSUE TITLE
storage: all mutlipath devices in other devices, multipath devices not shown in disk detail

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3939]
![screenshot from 2016-03-07 17-38-25](https://cloud.githubusercontent.com/assets/1218366/13585721/6e036504-e48b-11e5-8f34-c4c2f0d39b8b.png)
![screenshot from 2016-03-07 17-37-32](https://cloud.githubusercontent.com/assets/1218366/13585725/74157f54-e48b-11e5-9484-3817a48d99d2.png)

I think this is caused by me starting cockpit service before mulltipath was up after a reboot. But, I can't fix it by stopping and starting cockpit again (or by logging out). It's eerily permanent. I've attached the storagedctl dump output and also a selection from the journal of storaged and multipath actions.
`journalctl --reverse _COMM=multipathd --output=verbose _COMM=storaged --boot > journal.txt`

[storagedctl.dump.txt](https://github.com/cockpit-project/cockpit/files/162229/storagedctl.dump.txt)
[journal.txt](https://github.com/cockpit-project/cockpit/files/162242/journal.txt)

**Comment by mulkieran** [comment]
Updated to 0.96-1.x and both problems still remain. Haven't rebooted since this problem showed up, that might change things.

**Comment by mulkieran** [comment]
This problem is entirely persistent after multiple reboots and updates.

**Comment by mvollmer** [comment]
I can't reproduce this... Please reopen if this still happens.
