### ISSUE TITLE
storage: Weird order and double entry of volumes

### ISSUE THREAD

**Issue by FireDrunk** [cockpit-project/cockpit#3946]
![screenshot from 2016-03-08 12-39-43](https://cloud.githubusercontent.com/assets/6359704/13600721/1b276150-e52b-11e5-9f61-cc8dd15a2db3.png)

I don't know why, but i don't think this is the correct way to show these volumes.

The volumes are ZFS pools & filesystems, that might have something to do with it :)

Cockpit version: 0.96-1 on Fedora 23 with Kernel 4.4.2-301, ZFS 0.6.5.4-1.el7

**Comment by mvollmer** [comment]
The code is all different now... Please reopen if this still happens.
