### ISSUE TITLE
dashboard: add host should mention ssh

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#3959]
Adding a host requires a direct connection from the "gateway" system to the target system/address via ssh. If no port is given, standard 22 is assumed.

Maybe something like "Cockpit will attempt to connect to this host via ssh"? Optionally, "this host" could be replaced by the actual contents of the edit box with port 22 amended if no port is given. That way, the user sees that the port can be edited.

**Comment by andreasn** [comment]
At the very minimum, we could suggest this in the error message.

**Comment by TonyBostonTB** [comment]
I'd also say that it would be good to have that in the error message. Assuming that most users have ssh on the standard port and giving the address would just work.

**Comment by andreasn** [comment]
"Cockpit could not contact the given host.
Make sure ssh is running on port 22, or specify another port in the address"

And then in the input box the address shows up something like this:
192.168.1.45:22
