### ISSUE TITLE
storage: ReadRate for drives in overview is sometimes negative (example -0.4 B)

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3963]
This happens when the ReadRate for other disks is in the MiBs.

I can't get a screen shot, because the numbers move around to fast.

Attached is a shot of what the overview screen looks like when reads are highish from a lot of disks, for fun. I assume that the individual lines represent the contributions from individual disks.

![screenshot from 2016-03-09 14-31-51](https://cloud.githubusercontent.com/assets/1218366/13647903/374ae706-e604-11e5-8d8a-22f6989ba797.png)

**Comment by mvollmer** [comment]
Let's just clip the numbers to be non-negative.

**Comment by marusak** [comment]
I believe this was for individual drives - we dropped this metric in the meantime, so closing.
