### ISSUE TITLE
Containers view should default to "running"

### ISSUE THREAD

**Issue by jberkus** [cockpit-project/cockpit#3965]
The way it is now:

Containers view defaults to "All", showing all containers on stored on the machine.  If there are a lot of dead containers, this is quite cluttered.

The way it should be:

The default view should be "running" containers.

**Comment by stefwalter** [comment]
Makes sense. @larsu Do you think this is a good first step towards getting involved in the docker code?

**Comment by larsu** [comment]
Yeah, perfect. Thanks!
