### ISSUE TITLE
Forced to log in for each service after timeout

### ISSUE THREAD

**Issue by jberkus** [cockpit-project/cockpit#3966]
This *seems* to be the sequence of events which causes this issue:

1. Log into a machine running cockpit/ws (Atomic Host)
2. use it off and on, maybe long enough for there to be a timeout.
3. In the server view, switch services (say, from "logs" to "containers")
4. You will be forced to log in for that specific service.
5. Hereafter, each time you click on a service or server you will be made to log in again.

... however, since it is timeout-related, I'm not 100% sure that's the cause of the login for each service.

**Comment by stefwalter** [comment]
Very strange. Screenshots and journal logs would be interesting. The output of this:

```
$ sudo journalctl -b | grep cockpit
```

**Comment by jberkus** [comment]
OK, will grab those after Kubecon.

**Comment by dperpeet** [comment]
I haven't been able to reproduce this issue. @jberkus Any news?

**Comment by jberkus** [comment]
Nope, haven't been able to repro the issue under controlled circumstances.

Closing.
