### ISSUE TITLE
Registry: display labels summary, description, url

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#3971]
The [Container Application Generic Labels](https://github.com/projectatomic/ContainerApplicationGenericLabels/) repository specifies standards for some useful human-readable metadata. If present, values for these labels should be prominently displayed for images in the registry:

* summary
* description
* url

**Comment by aweiteka** [comment]
@stefwalter

**Comment by stefwalter** [comment]
@aweiteka What are some containers to use for testing this? Do you have any examples?

**Comment by aweiteka** [comment]
https://hub.docker.com/r/aweiteka/atomic-registry-quickstart/
