### ISSUE TITLE
RFE: Support for filesystem quotas

### ISSUE THREAD

**Issue by cmurf** [cockpit-project/cockpit#3992]
Specifically XFS project quotas. Kernel 4.5 brings project quota support for ext4 also. Btrfs has/will have (3rd revision in progress!) subvolume quotas that will be something like a project/uberdirectory quota. The project quota is most reasonable for initial support because it effectively enables a directory quota, rather than per user or group, although those quotas could be supported also. I'd suggest it in a different location in the UI (with users and groups rather than storage).

Use case: Instead of having to partition up a drive with separate /var, /opt, /srv, to keep a runaway process from soaking up space (e.g. logs), use something more appropriate for this task that's much easier to change, and also let's us get a warning rather than just abruptly getting ENOSPC. But at least XFS project quotas are rather esoteric to configure, so eliminating that headache makes quota a winning strategy.

Plus for Cockpit: I don't think GUI exists anywhere for managing quotas, so it helps Cockpit be unique. It's a more modern approach to allocating/limiting file system space. It's also rather low risk, you could mess it up by having wrong min/max values, but doesn't involve slicing and dicing up a drive or VGs.

**Comment by mvollmer** [comment]
Still a good idea! :-)

**Comment by martinpitt** [comment]
Still a good idea, but in the cockpit team itself we just  don't ever find the time/capacity for these. Contributions welcome!
