### ISSUE TITLE
storage: observations regarding organization and options on overview

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3994]
Some general observations:

* If you hover your mouse over a particular graph portion in the Read or the Write graph the corresponding drive will be highlighted. This is quite nice, but ineffective if you have enough drives that they don't all appear on the screen. This is somewhat related to #3934, because if the drives were ordered upward, it might be more likely to see the ones being selected. But, with a few more drives the problem comes back.
This is just an observation, everything works fine, it just doesn't always have the effect intended.

* I feel that it is not all that useful to work on the + buttons and their dialogs, as opposed to doing work to show the static and dynamic state of storage. This is also slightly related to #3934. One of the posters in that issue points out that you just don't make RAID arrays and VGs all that much, you're going to spend a lot more time monitoring and troubleshooting the storage setup you have than doing creation (unless you're a professional tester). If I were a storage admin, I would be likely to use the command-line for creation, because there are a _lot_ of options that might matter to me, and because Cockpit hides details, like what kind of RAID array is being made (lvm or mdadm) behind a GUI. I may have strong preferences which one I want, but I have to read the code to find out what I'm getting anyway. What I'ld like from Cockpit is to have a very good idea of what I've ended up with once I've run the commands. _That_ would be added value that the individual tools don't offer but that Cockpit might be able to do something about. Then, if I realize I've got it wrong, I'ld like Cockpit's help to reconfigure my RAID array or VG. Finally, in all but the simplest cases, the + dialogs do not present the available devices in a way that makes it at all easy for a storage admin to select the members that should participate, and it is likely that the work to make it really useful for more complex cases is _considerable_.

* It would be nice to be able to sort and group the drives by significant features, like I/O and physical location. I'm not sure how they're sorted at this time, and that makes searching for the correct one harder.

* Some of the "Drives" may not be real drives at all, but a bunch of drives hidden behind firmware and forming, e.g., a RAID array (like LSI MegaRAID). Note: this is even variable according to configuration, in JBOD configuration the disks are visible, AFAIU. It would be nice to distinguish these more strongly from a standard drive. (libstoragemgmt could go some way to helping out with that, it is something I am looking into.)

**Comment by stefwalter** [comment]
@mulkieran Thanks for all your feedback, but please file separate github issues for separate issues. These should be 4 different issues. Otherwise the discussion and fixes will just be confusing and it's easy to talk past each other.

**Comment by mulkieran** [comment]
Sure, I can separate them, but they'll all just link to each other in the end.

**Comment by mulkieran** [comment]
Split out to #3883, #4006, #4007, #4009.
