### ISSUE TITLE
test: Automatically update machines / verify instances

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#3996]
As [noted by @stefw](https://github.com/cockpit-project/cockpit/pull/3978#issuecomment-195426832), the following is needed on each verify machine in order to update them:

```
sudo docker pull cockpit/infra-verify
sudo systemctl restart cockpit-verify
```

This will kill any running tests.

In order to scale properly, we need to automate the update without interrupting running tests.

**Comment by dperpeet** [comment]
One way would be to commit to github the version of cockpit that test runners should run. After each test, they can switch to this if it doesn't match what they're on. As an added bonus, this also allows reverting the entire fleet to a last known good setting.

I'm not sure how much of this we could do for a pull request to be tested or if that is even necessary.

**Comment by dperpeet** [comment]
@stefwalter what do you think?

**Comment by stefwalter** [comment]
> One way would be to commit to github the version of cockpit that test runners should run. 

Do you mean the container version? Because this stuff isn't part of cockpit itself. Are the verify machines running a container in the new ansible based scheme?

**Comment by mvollmer** [comment]
We run in OpenShift clusters now, which should take care of that, no?

**Comment by martinpitt** [comment]
@mvollmer: It still interrupts running tests if we want to forcefully apply a new container. But this is then by intent ("I want the new things running *now*"). If we don't kill them, they will just restart with the latest container  version after 60 actions, which provides the "smooth update" functionality.

So I agree, all is well.
