### ISSUE TITLE
storage: highlighted drive not apparent when it is not on screen

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#4006]
If you hover your mouse over a particular graph portion in the Read or the Write graph the corresponding drive will be highlighted. This is quite nice, but ineffective if you have enough drives that they don't all appear on the screen. This is somewhat related to #3934, because if the drives were ordered above the RAID devices and VGs, it might be more likely to see the ones being selected. But, with a few more drives the problem comes back.

This is just an observation, everything works as intended, it just doesn't always have the effect intended, i.e., to identify the drive of interest.

I do not know what would be best to unambiguously identify the drive that shows the behavior. The highlighting has the advantage that it skips the problem of names. One could imagine a tooltip with the name of the drive that would appear when the cursor hovered over the particular graph segment, but all this might cause ugly display issues and if it is a WWN or serial number combination still be kind of hard for the user to cope with.

**Comment by marusak** [comment]
Nice, I did not ever notice that this feature exists.
I understand the problem but as OP mentions, there is no ideal solution.
Maybe @andreasn can think of something? Or since this this was abandon 3 years we can just close it?

**Comment by KKoukiou** [comment]
This feature also exists for the graphs on the network page and it's indeed not noticeable at all. When we fix it we need to fix both!
