### ISSUE TITLE
storage: in overview screen better to focus on what will be used more often by admin

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#4007]
I feel that it is not all that useful to work on the + buttons and their dialogs, as opposed to doing work to show the static and dynamic state of storage. This is also slightly related to #3934. One of the posters in that issue points out that you just don't make RAID arrays and VGs all that much, you're going to spend a lot more time monitoring and troubleshooting the storage setup you have than doing creation (unless you're a professional tester). If I were a storage admin, I would be likely to use the command-line for creation, because there are a lot of options that might matter to me, and because Cockpit hides details, like what kind of RAID array is being made (lvm or mdadm) behind a GUI. I may have strong preferences which one I want, but I have to read the code to find out what I'm getting anyway. What I'ld like from Cockpit is to have a very good idea of what I've ended up with once I've run the commands. That would be added value that the individual tools don't offer but that Cockpit might be able to do something about. Then, if I realize I've got it wrong, I'ld like Cockpit's help to reconfigure my RAID array or VG. Finally, in all but the simplest cases, the + dialogs do not present the available devices in a way that makes it at all easy for a storage admin to select the members that should participate, and it is likely that the work to make it really useful for more complex cases is considerable.

Note: My colleague pointed out that in some cases the simple presentation of drives in the + dialogs might be quite adequate. The scenario is that most of your disks are tied up in your storage organization already. Then you buy a few new disks and stick them in an enclosure. You press the + button and only those drives are presented to you in the dialog. You're sure those are the ones you want, because those are the only ones available. But, if that's really a likely scenario, and it may be, the dialog should probably have a "Select All" option.

**Comment by mvollmer** [comment]
Thanks for the feedback!  But let's close this issue since there is nothing really actionable in here.
