### ISSUE TITLE
storage: firmware RAID in a somewhat paradoxical position on Cockpit

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#4009]
I've been experimenting a bit with an LSI MegaRAID setup on my machine and it strikes me that Cockpit is in an odd position wrt. it. Here's what happens and what I think ought to happen in a more perfect world.
- Until the card is configured, it does not appear at all on the Cockpit overview screen.
  I think it would be better if the card were apparent, but I'm not sure it should appear under Drives or any of the other current designations that I know about. AFAIU, it can not function as a device until configured. Ideally, it should be possible to select the card, see the disks that belong to it, and configure it on its detail screen.
- Once the card is configured it appears among the Drives on the overview screen, but the detail screen gives no information about its RAID configuration or about the disks that back it.
  I'm not sure whether it is right or wrong to show it as a Drive. One good argument for this arrangement is that the MegaRAID device has a single device file associated with it. An argument against, is that this hides the drives that belong to the RAID array, and they may have distinct performance or other characteristics.
  But in any case, the detail screen should give more help.

Below are two screen shots...one shows the MegaRAID showing up among the drives once I've configured it as a RAID 5, the other shows the detail screen for that device.

![screenshot from 2016-03-14 16-04-52](https://cloud.githubusercontent.com/assets/1218366/13779374/027d3f10-ea91-11e5-9518-0450494bcc0b.png)
![screenshot from 2016-03-14 16-02-22](https://cloud.githubusercontent.com/assets/1218366/13779381/064b35ac-ea91-11e5-946c-d583a257c3e0.png)

**Comment by mulkieran** [comment]
Note that the MegaRAID can be run in JBOD mode and in that case, there should be multiple device files corresponding to each of its disks, AFAIU.

**Comment by mulkieran** [comment]
Libstoragemgmt (LSM) is definitely the library to consult to make these things happen. However, I have gathered that there are difficulties involved. Rather significantly, LSM does not do discovery. It requires an intelligent decision maker to decide that there is an hpsa or a megaraid card out there and to make the connection to the appropriate daemon. There has been talk about doing discovery, but the obstacles, especially for distributed storage, are real and technical. So, it is desirable to detect the MegaRAID card, but not easy. A user could instruct Cockpit to look for, e.g, MegaRAID cards, but that seems extremely clunky. Other alternatives are less obvious.

**Comment by mvollmer** [comment]
LSM support would be great indeed but needs much more than a GitHub issue to track.
