### ISSUE TITLE
Mem and CPU graphs for containers breaks with Docker 1.10

### ISSUE THREAD

**Issue by Subsack** [cockpit-project/cockpit#4010]
Hi,

all graphs for containers break with docker 1.10.x, @stefwalter helped me confirm it. I've tried all version of cockpit from 0.93 to 0.97 on centos and fedora server.

**Comment by stefwalter** [comment]
CGroup names in docker 1.10 are different:

```
/sys/fs/cgroup/memory/docker/612540d76d685e209f322b9a50375f229c00457f2dbc51493fb48ba1bc4a1454
```

Compared to what we expect in pkg/docker/client.js

**Comment by Subsack** [comment]
Thanks @stefwalter, I was able to get it working by changing:
`return "system.slice/docker-" + id + ".scope";` to `return "docker\/” + id + ""` 

And:
`var regex_docker_cgroup = /docker-([A-Fa-f0-9]{64})\.scope/;` to `var regex_docker_cgroup = /docker\/([A-Fa-f0-9]{64})/`

**Comment by t3chn0m4g3** [comment]
Can confirm for Ubuntu 16.04.x, will there be a fix in the near future?

**Comment by arputcu** [comment]
any update on this?

**Comment by petervo** [comment]
@arputcu what version ok cockpit are you trying with? I believe this was fixed on the docker page.

**Comment by arputcu** [comment]
@petervo  Version 138. on ubuntu 
Docker version 1.12.6, build 78d1802

**Comment by arpu** [comment]
tested again with cockpit 140-0 on ubuntu 
i think this bugreport could be closed
