### ISSUE TITLE
TestNetworking testBridge fails waiting for tbridge

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#4056]
The TestNetworking.testBridge test fails waiting for "tbridge"

```
Traceback (most recent call last):
  File "./verify/check-networking", line 259, in testBridge
    b.wait_not_in_text("#networking-interfaces", "tbridge")
```

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-networking", line 259, in testBridge
    b.wait_not_in_text("#networking-interfaces", "tbridge")
  File "testlib.py", line 242, in wait_not_in_text
    return self.wait_js_func('!ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 659, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 682, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-03-22T05:51:28.070742 | revision 1f24ca44b2191ad32cf64ee269c537b99eca436b, [logs](http://files.cockpit-project.org/logs/pull-4060-1f24ca44-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-03-22T05:51:28.070742 | revision 1f24ca44b2191ad32cf64ee269c537b99eca436b, [logs](http://files.cockpit-project.org/logs/pull-4060-1f24ca44-verify-fedora-24/log.html)
