### ISSUE TITLE
ssh-transport-c denied access to /proc/net/unix

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#4062]
We don't know what's actually doing this, but an SELinux audit message shows up every once in a while denying access to the cockpit-ws process.

```
Error: audit: type=1400 audit(1458639170.404:268): avc: denied { read } for pid=1301 comm="ssh-transport-c" name="unix" dev="proc" ino=4026532021 scontext=system_u:system_r:cockpit_ws_t:s0 tcontext=system_u:object_r:proc_net_t:s0 tclass=file permissive=0
```

**Comment by stefwalter** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1242656

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 504, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 625, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1458644336.962:268): avc:  denied  { read } for  pid=1299 comm="ssh-transport-c" name="unix" dev="proc" ino=4026532021 scontext=system_u:system_r:cockpit_ws_t:s0 tcontext=system_u:object_r:proc_net_t:s0 tclass=file permissive=0
```
First occurrence: 2016-03-22T10:59:10.250533 | revision 3f9ea569c27b6331398be3d2ddc71bbb033e2f2e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4063-3f9ea569-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-03-22T10:59:10.250533 | revision 3f9ea569c27b6331398be3d2ddc71bbb033e2f2e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4063-3f9ea569-verify-fedora-24/log.html)
