### ISSUE TITLE
kube: long node names makes panel overflow

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#4067]
I ran the new openshift node from e71c9318311a040718fe2b9be0fb38ac33344613
![screenshot from 2016-03-22 16-05-54](https://cloud.githubusercontent.com/assets/209895/13956205/1366fd18-f048-11e5-9e2a-819c1b6372e2.png)

**Comment by shameempk** [comment]
Is there any possibility to reproduce this issue, without having Kubernetes installed ?

**Comment by stefwalter** [comment]
@shameempk It's easy to bring up a couple of kube machines from the cockpit directory like this:

```
$ test/vm-run openshift
```

Wait until that's booted. Log into Cockpit, look at the "Cluster". At this point only one machine will be listed. Now click the [+] above the "Nodes" list and add a node with a very long name, like above.

**Comment by shameempk** [comment]
Will check this out.

**Comment by andreasn** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
