### ISSUE TITLE
cluster: inconsistent icon representation of cluster node

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#4068]
I was in the middle of adding a cluster node icon to a mockup for the Cluster Dashboard when I noticed that the icon representation for a cluster node is inconsistent between different panes.

The Details page uses this icon (pficon-cluster):
![screenshot from 2016-03-22 16-29-03](https://cloud.githubusercontent.com/assets/209895/13957053/502997b2-f04b-11e5-85c3-2d8d612e79d6.png)

While the Topology page uses this icon (pficon-container-node)
![screenshot from 2016-03-22 16-29-13](https://cloud.githubusercontent.com/assets/209895/13957140/aa86f2fe-f04b-11e5-9f91-230fdbf562cc.png)

Feel free to close this in case I'm just confused and these are actually two distinct and different things.

**Comment by petervo** [comment]
This was fixed
