### ISSUE TITLE
Allow easy addition of new SSH keys

### ISSUE THREAD

**Issue by bexelbie** [cockpit-project/cockpit#4070]
I  do a lot of work with vagrant managed boxes.  While they are ephemeral, some do stick around for a while.  It would be nice to use cockpit with some of them.  The bridge and other pieces are deployed in them.

I'd like an easy way to accomplish one or both of the following:
1) Log in directly a a web client on the vagrant box using just the SSH private key in the .vagrant directory.  I am happy to navigate to that file.
2) Add the vagrant box to a cockpit dashboard on the host machine.  Again, the SSH private key is all I have and it is in the .vagrant directory.

I got number 2 working by doing the following:
1. Copy private key from .vagrant/... to ~/.ssh
2. Log into vagrant box and get the public key
3. Create a .pub file in ~/.ssh with the public key
4. Go into cockpit and enable the key in the authentication list with no password
5. Add the box
6. cockpit magic!

**Comment by vmindru** [comment]
+1 we need an easy way to add ssh private key to the server.

**Comment by mvollmer** [comment]
There is a "Add key" button in the "Authenticate" dialog:
![image](https://user-images.githubusercontent.com/3228183/52114844-cbfc7780-2615-11e9-9537-5cd5972ec0c3.png)

Does that do what you need?  Please reopen if I misunderstood.
