### ISSUE TITLE
Allow for each deletion of the cached copy of known_hosts - Incorrect Host Key Error

### ISSUE THREAD

**Issue by bexelbie** [cockpit-project/cockpit#4071]
If a machine changes and the IP is reused, there is no easy way to delete the cached known_host entry in Cockpit.  I deleted the file in ~/.ssh and it had no effect.  The error message gives no guidance.  Restarting the cockpit service didn't clear it either.  Changing browsers had no effect.

**Comment by petervo** [comment]
If you click on trouble shoot, it should show you the command to use to clear that host from the known hosts. Are you not seeing that?

**Comment by bexelbie** [comment]
@petervo there is no troubleshoot button or link, just a close button.  This is on Fedora 23 Workstation fully updated.  

```
Version     : 0.96
Release     : 1.fc23
```

**Comment by petervo** [comment]
Could you attach a screen shot. Or walk me through the steps so i know exactly how you are getting to the error.

**Comment by bexelbie** [comment]
Reproduction steps:

1. Start a machine, I am using a vagrant box
2. In the cockpit web ui of a different machine, I am using my vagrant host, add the machine in the dashboard
3. Delete the machine
4. Replace the machine.  I am doing `vagrant destroy; vagrant up`
5. Try to readd the machine
6. Get Error: 
![error](https://cloud.githubusercontent.com/assets/7413661/13963342/47a7e854-f065-11e5-8410-4d4d7861b6fe.png)

**Comment by petervo** [comment]
Thanks, there should be a line below giving you a command to run to clear it. https://github.com/cockpit-project/cockpit/blob/master/pkg/shell/templates/invalid-hostkey.html#L11

I will look into why that isn't showing.

**Comment by bexelbie** [comment]
@petervo thanks for looking into this.  In the iterim I found and took a machete to `/var/lib/cockpit/known_hosts`  I have probably done bad things :p

**Comment by stefwalter** [comment]
Thanks @bexelbie fixed in #4072

**Comment by t3chn0m4g3** [comment]
I have the exact same problem on Cockpit 188 running on Debian Sid:
![image](https://user-images.githubusercontent.com/4318452/55874591-1872af00-5b93-11e9-9ce1-446b00d7d886.png)

- deleted known_hosts => no effect
- looked for another known_hosts file i.e. in `/var/lib/cockpit`, but no luck.

Can anyone guide me to what file I have to delete?

**Comment by t3chn0m4g3** [comment]
As described in #6025 it is now `/etc/ssh/ssh_known_hosts`

**Comment by cconstab** [comment]
Thanks..... I could not find it either after a rebuild of one of my hosts.. Saved me an hour :-)
