### ISSUE TITLE
Ability to view the SSH host key

### ISSUE THREAD

**Issue by fabiand** [cockpit-project/cockpit#4077]
To give a user the ability to ensure that he is really connecting to the right host using ssh, it would be nice to have a button somewhere in the UI to display the ssh host key(s).

**Comment by dperpeet** [comment]
@fabiand can you make a mockup of a good place for this?

**Comment by fabiand** [comment]
@dperpeet Yep, let me find a place for it.

**Comment by stefwalter** [comment]
@andreasn Probably makes sense on the server summary page no? It's a unique way of identifying the server. In addition what about the machine-id, I believe that was also requested.

**Comment by andreasn** [comment]
is this a duplicate of issue #4310 ?

**Comment by fabiand** [comment]
Yes, this is a dupe of #4310.
