### ISSUE TITLE
Registry: Import Image

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#4081]
The "New Image Stream" action might be better labeled "Import Image" since it references another registry and sync's down the metadata.

Also, I would suggest an optional checkbox to pull all tags. Otherwise the user may enter a list of tags in a text field. :latest is default if unspecified.

This maps well to `oc import-image --from` command.

```
oc import-image -h
Import tag and image information from an external Docker image repository

Only image streams that have a value set for spec.dockerImageRepository and/or
spec.Tags may have tag and image information imported.

Usage:
  oc import-image IMAGESTREAM[:TAG] [options]

Examples:
  $ oc import-image mystream

Options:
      --all=false: If true, import all tags from the provided source on creation or if --from is specified
      --confirm=false: If true, allow the image stream import location to be set or changed
      --from='': A Docker image repository to import images from
      --insecure=false: If true, allow importing from registries that have invalid HTTPS certificates or are hosted via HTTP

Use "oc options" for a list of global command-line options (applies to all commands).
```

**Comment by stefwalter** [comment]
> The "New Image Stream" action might be better labeled "Import Image" since it references another registry and sync's down the metadata.

I'm not sure about this. Since it actually does create a new image repository ^H^H^H i mean **stream** (groan). Automatically pulling images into it is an optional choice.

> Also, I would suggest an optional checkbox to pull all tags. Otherwise the user may enter a list of tags in a text field. :latest is default if unspecified.

I tried to implement this and  failed. Openshift just pulled all the metadata regardless. The designs do have it however. We just need to figure out how to actually make it work. Have you tried it via JSON on the command line?

![](https://github.com/cockpit-project/cockpit-design/raw/master/kubernetes/images.png)

**Comment by aweiteka** [comment]
> Have you tried it via JSON on the command line?

It appears defining an image stream via JSON is basically the same behavior as `oc import-image`. I'm trying to sort out the use case for creating an empty image stream. It feels to me like "import image" or "sync remote image" is the behavior a user would expect. I'm okay as it is today as long as the CLI args are basically covered. We can get feedback from users now.

**Comment by aweiteka** [comment]
@thomasmckay I think this is what you're seeing.

**Comment by thomasmckay** [comment]
Yes, allowing the equivalent to --all --insecure via cockpit would be very useful.

**Comment by thomasmckay** [comment]
still would be useful

**Comment by martinpitt** [comment]
Tag import (all or specified ones)  got fixed a while ago. Changing labels etc. won't happen any more, as our kubernetes UI is on maintenance mode. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
