### ISSUE TITLE
suppress display of, and disallow creation of thin volumes from thin pools with transaction id 1

### ISSUE THREAD

**Issue by cmurf** [cockpit-project/cockpit#4082]
docker-storage-setup creates a dmthin pool "docker-pool" with a transaction id of 1, which LVM tools cannot use. Cockpit presents this pool to the user rather prominently, and makes it easy to create a thin volume from this pool which then fails (see screen shot). The failure is expected, this pool is really "owned" by docker and probably shouldn't be exposed to the user at all.
![screenshot from 2016-03-23 17-08-19](https://cloud.githubusercontent.com/assets/10091077/14004088/4b1c2a28-f11d-11e5-9556-fb98b39b58fc.png)

**Comment by cmurf** [comment]
Actually, the pool needs to be there, so it can be resized. But maybe suppress the action to create thin volumes from such a pool? The error isn't really the problem, it's the error message that LVM is handing to cockpit (I'm guessing) that's not very intuitive or plain language. It's using terminology most people, even a sysadmin, is unlikely to understand that there are dm thin pools that LVM won't manage, and it's this type of thin pool that docker is using.

**Comment by andreasn** [comment]
Is docker-storage-setup only available on Fedora Atomic, or also on regular, rpm-based Fedora?

**Comment by stefwalter** [comment]
Available on Fedora as well.

**Comment by mvollmer** [comment]
@cmurf, looking at the transaction id doesn't feels like a hack.  Is that really how to identify pools that are not available for logical volumes?

**Comment by cmurf** [comment]
It's been a few years so I don't remember who I asked about it, so I'd have to defer the question to an LVM developer.

**Comment by mvollmer** [comment]
Afaik, this kind of docker storage setup has been on its way out for some time.  Closing..
