### ISSUE TITLE
Display nodePort in the service details

### ISSUE THREAD

**Issue by Smana** [cockpit-project/cockpit#4101]
Hi guys,

I think it would be useful if we could get the nodePort from the service details. (kubernetes).

Regards,
Smana

**Comment by stefwalter** [comment]
Makes sense. Are you interested in contributing that change? I could help point out where the changes would go.

**Comment by Smana** [comment]
Yes, please guide me, i'll do the PR :)

**Comment by stefwalter** [comment]
I think the changes would go here: 

https://github.com/cockpit-project/cockpit/blob/master/pkg/kubernetes/views/service-panel.html#L26

There would probably be some ng-if attributes added to cover the various cases as well.

**Comment by Smana** [comment]
Done : https://github.com/cockpit-project/cockpit/pull/4110
