### ISSUE TITLE
zram disk content is not recognized

### ISSUE THREAD

**Issue by mykaul** [cockpit-project/cockpit#4120]
While in mount it's very visible:
/dev/zram0 on /home/zram type xfs (rw,relatime,attr2,nobarrier,inode64,noquota)

In the Cockpit UI, I'm seeing:
Unrecognized Data
/dev/zram0

And it offers to format it.

It's also unseen in the Filesystems list.

v0.96, Fedora 23.

**Comment by mvollmer** [comment]
Does this still happen?  Please reopen if so.
