### ISSUE TITLE
Docker logger have a bug 。docker logger will display all the systemlog and waste to much time

### ISSUE THREAD

**Issue by jake2009** [cockpit-project/cockpit#4127]
my log is to many and docker logger will dispay all the log including one week ago that the first day log。
it spend to much time 。 I lost my patient ...

may be only "tail -2000f server.log"  is fine. only display the last 2000 row.

**Comment by stefwalter** [comment]
Could you post a screenshot of the issue and the URL (you can remove your host name) at which you found the issue?

**Comment by skelbley** [comment]
I have noticed this as well; it happens when viewing a running container (clicking on the container under  the "Containers" tab). When viewing a container that has been running for a while with a program that writes a modest amount to stdout, loading the page results in the container console on the right scrolling through what looks like every line of output since the container was started.

**Comment by stefwalter** [comment]
Thanks for confirming the issue.

The first thing to check when fixing this checking whether the docker API has a way to tail a specific number of logs lines and follow from there. The docker command line certainly does with ```docker log --tail=N```

**Comment by skelbley** [comment]
It looks like the API call results can be limited either [tail or by a timestamp](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.15/#get-container-logs).

And I'm not familiar with the code in Cockpit, but I think the change would be on [this call](https://github.com/cockpit-project/cockpit/blob/8256580c76c54a20faf673c54a79bacada152c18/pkg/docker/docker.js#L363). Not in a position to test it out currently, unfortunately.

**Comment by stefwalter** [comment]
@skelbley Thanks for that research. Looks correct. The next thing to figure out is which version of the API this feature was added, and we can bump the docker requirement along with this change.

**Comment by skelbley** [comment]
@stefwalter: Glad to help, thanks for your guys work on cockpit. Looks like the tail parameter exists back as far as API [version 1.14](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.14/#get-container-logs) (Docker version 1.2.x), specfile currently lists >=1.3.0 for docker.

**Comment by stefwalter** [comment]
Hmmm, I tried to do this and it looks like only ```/logs``` can use the tail limiter. The ```/attach``` stuff (ie: showing a TTY) cannot limit the number of lines. But I've done this for when we're showing logs rather than attaching to a TTY.

Closes #4160
