### ISSUE TITLE
alers are squashed

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#4130]
As a followup to #4115 
The alerts are squashed and lacks padding.
We seem to do some custom css on top. Will try and figure out why.

![screenshot from 2016-04-01 12-15-23](https://cloud.githubusercontent.com/assets/209895/14204287/7f5e24f2-f803-11e5-928a-7af20dfe219d.png)

**Comment by andreasn** [comment]
Comes from https://github.com/cockpit-project/cockpit/blame/af7a6ca8396858b253ae6b9fbc8b8aa326ee9606/pkg/base1/cockpit.css#L352

**Comment by stefwalter** [comment]
The cockpit.css change goes back to the way Patternfly used to render them. 

The default display is very big for modals ... so as long as we take that into account i'm fine with further changes.

**Comment by andreasn** [comment]
I can special-case the css for alerts in modals, and then this one should go away.

**Comment by mvollmer** [comment]
Looks like this now:
![image](https://user-images.githubusercontent.com/3228183/52115122-82f8f300-2616-11e9-99eb-6d2426f68e00.png)

This is okay, no?
