### ISSUE TITLE
Cockpit Kubernetes Docker Image "root" password

### ISSUE THREAD

**Issue by subodhp** [cockpit-project/cockpit#4134]
Hi, 

I have onboarded the following container using Kubernetes. I can the Web GUI on the port 9090.

docker.io/cockpit/kubernetes                                  latest              7a0d423879b6        2 days ago          236 MB

The problem is when I try to login to Web GUI, it says Authentication Fail.

Then I checked on the running container, the root password is not present. 

The Fedora 23 Container Image doesn't have passwd utility to set "root" password. 

I am not able to login. Any comments?

**Comment by petervo** [comment]
The kubernetes container needs to login using kubernetes credentials. This is documented here http://cockpit-project.org/guide/latest/feature-kubernetes.html (see the "Used as a Kubernetes Pod" section) and here https://github.com/cockpit-project/cockpit/blob/master/containers/kubernetes/README.md.

Are you running it as a pod? Or a standalone docker container?

**Comment by subodhp** [comment]
I am running as a pod, I tried using standalone too.

The links you have mentioned seem to point to Cockpit communicating to Kubernetes for management.

My question is not related to Kubernetes Authentication.

I am stuck at the Web GUI Login. Cockpit uses System Login for Web UI login. Since the system is Docker Container, it is using container user root.

**Comment by petervo** [comment]
That's my point, the kubernetes container, only uses kubernetes authentication and only shows the kubernetes UI.

If you want the full cockpit and to authenticate using system users you must install cockpit another way. There are quite a few options depending on your OS, but the container cockpit/kubernetes is not one of them.

**Comment by subodhp** [comment]
Ok. So can you suggest me a quick option to do following.

Objective - Install Cockpit to manage Kubernetes Cluster. 

How do I do that, I don't strictly intend to use Cockpit as a Container. I can install that on base OS too.

**Comment by petervo** [comment]
Generally speaking you need the cockpit-kubernetes package. Instructions are different depending on what operating system you are using.

**Comment by subodhp** [comment]
So right now, I have installed cockpit on the RHEL7 Base Node. Works perfectly. 
Now I cannot find any package named cockpit-kubernetes on RHEL7. It is present for CENTOS7 though.

**Comment by petervo** [comment]
I guess it isn't in extra's on RHEL, there might be a different way to get it you should ask your rep about that.

In the mean time there are ways to link additional packages in. Cockpit looks at /usr/share/cockpit and ~/.local/share/cockpit for the packages to load. These packages are all just html/js so they can just be copied/linked in from a distribution tar (https://github.com/cockpit-project/cockpit/releases).

**Comment by subodhp** [comment]
Now, I have gone ahead and installed Cockpit 0.99 from source successfully on RHEL7 Base OS. The Web GUI page appears, but the root account is not working. When I enter credentials, the page refreshes. No login.

**Comment by subodhp** [comment]
It is saying wrong user/pass, even though the root credentials are correct.

**Comment by subodhp** [comment]
I tried with creating different username too. Source Build of 0.99, the login doesn't happen.

**Comment by petervo** [comment]
0.99 from source is known to work on RHEL, there are lots of reasons why you could be running into this. You'll want to check that you aren't accidentally still running the container and that you built with --prefix=/usr and see if there is anything helpful in the logs.

This really isn't a good forum for this sort of support. Why don't you join us on #cockpit on freenode irc and we can try to further debug the issue you are seeing that way.

**Comment by subodhp** [comment]
Well, I have stopped all of the containers and rebuilt from source multiple times. Still facing the issue. 
Ok Sure.

**Comment by petervo** [comment]
Did you build with prefix=/usr? If not you'll need to clear out anything cockpit related in /usr/local before building again. My irc nic matches my github name if you want to talk directly.

**Comment by subodhp** [comment]
Hi Peter,

I took a fresh RHEL7.2 VM & installed cockpit 0.99. Satisfied all dependencies. Configured with parameters "--disable-doc --disable-pcp". Still I am facing the same error. Correct root password is reported as "Incorrect Username and Password" on the Cockpit UI.

I was looking into "journactl -xe", I found following interesting messages. 

At the time of User login on Cockpit Web UI.

-------------------------
polkitd[1394]: Unregistered Authentication Agent for unix-process:1721:48376139 (system bus name :1.4163, object path /org/freedesktop/Po
cockpit-ws[1731]: Using certificate: /usr/local/etc/cockpit/ws-certs.d/0-self-signed.cert
kernel: SELinux: initialized (dev tmpfs, type tmpfs), uses transition SIDs
-------------------------

After 2-3 minutes, the service goes into inactive state & goes into running state if I access WebGUI, this is expected. "systemctl status cockpit -l" output below. Please check the service parameters.

-------------------------
[root@bash cockpit-0.99]# systemctl status cockpit -l
● cockpit.service - Cockpit Web Service
   Loaded: loaded (/usr/lib/systemd/system/cockpit.service; static; vendor preset: disabled)
   Active: inactive (dead) since Thu 2016-04-07 01:55:30 EDT; 12min ago
     Docs: man:cockpit-ws(8)
  Process: 1731 ExecStart=/usr/local/libexec/cockpit-ws (code=exited, status=0/SUCCESS)
  Process: 1727 ExecStartPre=/usr/local/sbin/remotectl certificate --ensure --user=root --group= --selinux-type= (code=exited, status=0/SUCCESS)
 Main PID: 1731 (code=exited, status=0/SUCCESS)

systemd[1]: Starting Cockpit Web Service...
remotectl[1727]: Generating temporary certificate using: openssl req -x509 -days 36500 -newkey rsa:2048 -keyout /usr/local/etc/cockpit/ws-certs.d/0-self-signed.VPRQFY.tmp -keyform PEM -nodes -out /usr/local/etc/cockpit/ws-certs.d/0-self-signed.JJRQFY.tmp -outform PEM -subj /O=6e0fcbcac1784da79b4366c14ec19a3e/CN=test1
systemd[1]: Started Cockpit Web Service.
cockpit-ws[1731]: Using certificate: /usr/local/etc/cockpit/ws-certs.d/0-self-signed.cert
------------------------

I have selinux enabled in the "enforcing" mode.

Any comments?

Thanks,
Subodh
thesubodh.com

**Comment by petervo** [comment]
I don't see anything here that would cause a problem. Though I would still recommend you configure with --prefix=/usr

Since cockpit is socket activated, going inactive after a little while is expected.

Is /etc/pam.d/cockpit present? and match what is here: https://github.com/cockpit-project/cockpit/blob/master/tools/cockpit.pam

Have you tried with a non-root user?
