### ISSUE TITLE
storage: unable to add available device to existing mirror

### ISSUE THREAD

**Issue by mrguitar** [cockpit-project/cockpit#4148]
I'm running cockpit 0.96.1 on f23. I had a drive die in my mirror. I was able to remove the dead drive via cockpit, but after physically installing the new drive I'm unable to add the disk via cockpit. Here's a screenshot: 
![screenshot from 2016-04-04 20-34-16](https://cloud.githubusercontent.com/assets/1071620/14268883/1d311b64-faa5-11e5-861b-d260ec95f60a.png)

At first there wasn't a partition table on the disk: unable to select it in the UI.
The drive is the same physical size as the other one, so I thought maybe the partition table needs to match. Running sfdisk -d /dev/sdg | sfdisk /dev/sdh had no effect on the problem. For some reason I'm still unable to "see" this device as valid to add to the mirror. 

running this added the device perfectly and cockpit does show the status of the resync. mdadm /dev/md124 --add /dev/sdh3

**Comment by mvollmer** [comment]
Thanks for the report!  This is a known weakness in Cockpit: It tries to only offer block devices for adding that are not already in use for something else.  It really should show them all, and indicate which ones are in use.

Also, what counts as "in use" and what the user needs to do to free a device is not clear at all.  You should have been able to format the drive without any partition table, and then it should have shown up in the "Add Disks" dialog.

**Comment by mrguitar** [comment]
Thanks for the info. I'm probably one of three people who actually uses mdraid. :) .....I love that you guys support it. 
Thanks,

**Comment by mvollmer** [comment]
Please see #4169 and #4180.  You might be running into the same bug.

**Comment by mvollmer** [comment]
Let's close this.
