### ISSUE TITLE
Display "Details" tab with REGISTRY_ONLY mode

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#4158]
Atomic registry cluster admins should be able to (at least) view the architecture of the deployed registry. This also may be "low hanging fruit" to help registry admins to understand the architecture of the registry components.

**Comment by stefwalter** [comment]
I'm not sure about this. Couldn't such admins be deploy the ```cockpit/kubernetes``` pod, as described in: http://cockpit-project.org/guide/latest/feature-kubernetes.html

**Comment by aweiteka** [comment]
> Couldn't such admins be deploy the cockpit/kubernetes pod

Yes, that could work. It's an additional step and the same image, potentially adding to confusion.

If the UI is not designed this way then maybe that's best for now.
