### ISSUE TITLE
Debian packaging is blocked on a few issues

### ISSUE THREAD

**Issue by larskarlitski** [cockpit-project/cockpit#4159]
Andreas Henriksson was kind enough to put some more work into the debian package at http://anonscm.debian.org/cgit/collab-maint/cockpit.git and gave some feedback in a private mail. Pasting his thoughts here so that we can better track the issues. I don't think it makes sense to split out all of those into separate issues, but feel free to do so if anything needs deeper discussion.

I'm going to quote the lintian checker tool output below and comment inline:

> Setting up lintian (2.5.42.1) ...
> W: --force-yes is deprecated, use one of the options starting with --allow instead.

We should probably add a lintian override for po/po.*.js files as they are generated
from po(?) which is the source, but we also needs to make sure the generator
sourcecode is available (in unminified/unobfuscated format).

> E: cockpit source: source-is-missing po/po.ca.js line length is 32650 characters (>512)
> N: 
> N:    The source of the following file is missing. Lintian checked a few
> N:    possible paths to find the source, and do not find it.
> N:    
> N:    Please repack your package to include the source or add it to
> N:    "debian/missing-sources" directory.
> N:    
> N:    If this is a false-positive, please report a bug against Lintian.
> N:    
> N:    Severity: serious, Certainty: possible
> N:    
> N:    Check: cruft, Type: source
> N: 
> E: cockpit source: issing po/po.da.js line length is 25429 characters (>512)
> E: cockpit source: source-is-missing po/po.de.js line length is 32650 characters (>512)
> E: cockpit source: source-is-missing po/po.pl.js line length is 32650 characters (>512)
> E: cockpit source: source-is-missing po/po.pt_BR.js line length is 32650 characters (>512)
> E: cockpit source: source-is-missing po/po.tr.js line length is 32653 characters (>512)
> E: cockpit source: source-is-missing po/po.uk.js line length is 32576 characters (>512)

I guess the following comes from the autogen.sh usage of npm install which then
gets shipped in the tarball. We need to ship all sources (preferable form of
modification) in Debian, so maybe it's possible to get the sources for these
node modules bundled within the tarball as well? Even better ofcourse would be
if npm install wasn't used at all in autogen.sh somehow, so we can build debian
packages straight from git snapshots (since Debian buildds do not generally have
network access, as Debian policy mandates packages should be buildable without
network access).

> E: cockpit source: source-is-missing node_modules/esprima/esprima.js line length is 6439 characters (>512)
> E: cockpit source: source-is-missing node_modules/jed/jed.js line length is 2360 characters (>512)
> E: cockpit source: source-is-missing pkg/base1/angular-bootstrap.js line length is 514 characters (>512)
> E: cockpit source: source-is-missing pkg/docker/run.js line length is 541 characters (>512)
> E: cockpit source: source-is-missing pkg/kubernetes/kubernetes-templates.js line length is 834 characters (>512)
> E: cockpit source: source-is-missing pkg/kubernetes/registry-templates.js line length is 834 characters (>512)
> E: cockpit source: source-is-missing bower_components/less/dist/less.js line length is 844 characters (>512)
> E: cockpit source: source-is-missing node_modules/jshint/data/non-ascii-identifier-part-only.js line length is 8026 characters (>512)
> E: cockpit source: source-is-missing node_modules/jshint/data/non-ascii-identifier-start.js line length is 32768 characters (>512)
> E: cockpit source: source-is-missing node_modules/jshint/dist/jshint-rhino.js line length is 8026 characters (>512)

This one is a big showstopper for us. "Good, not evil license" is not considered
DFSG-free. Please see the linked wiki page for alternatives that could possibly
substitute. I guess this comes from some node dependency though so maybe it's
not very easy for you to pick an alternative.

> E: cockpit source: license-problem-json-evil node_modules/jshint/dist/jshint-rhino.js
> N: 
> N:    The given source file is copyrighted under the non-free license of json
> N:    and the infamous clause: The Software shall be used for Good, not Evil.
> N:    
> N:    Refer to https://wiki.debian.org/qa.debian.org/jsonevil for details.
> N:    
> N:    Severity: serious, Certainty: possible
> N:    
> N:    Check: cruft, Type: source
> N: 
> E: cockpit source: license-problem-json-evil node_modules/jshint/dist/jshint.js
> E: cockpit source: license-problem-json-evil node_modules/jshint/src/jshint.js
> E: cockpit source: source-is-missing node_modules/less/dist/less.js line length is 844 characters (>512)
> E: cockpit source: source-is-missing node_modules/uglify-js/lib/parse.js line length is 4985 characters (>512)
> E: cockpit source: source-is-missing node_modules/html-minifier/node_modules/cli/cli.js line length is 587 characters (>512)
> E: cockpit source: source-is-missing node_modules/jshint/node_modules/cli/cli.js line length is 587 characters (>512)
> E: cockpit source: source-is-missing node_modules/jshint/node_modules/minimatch/browser.js line length is 849 characters (>512)
> E: cockpit source: source-is-missing node_modules/html-minifier/node_modules/uglify-js/lib/parse.js line length is 4985 characters (>512)
> E: cockpit source: source-is-missing node_modules/html-minifier/node_modules/change-case/node_modules/sentence-case/vendor/camel-case-regexp.js line length is 8562 characters (>512)
> E: cockpit source: source-is-missing node_modules/html-minifier/node_modules/change-case/node_modules/sentence-case/vendor/non-word-regexp.js line length is 5036 characters (>512)
> E: cockpit source: source-is-missing node_modules/html-minifier/node_modules/change-case/node_modules/sentence-case/vendor/trailing-digit-regexp.js line length is 1635 characters (>512)
> E: cockpit source: source-is-missing node_modules/less/node_modules/request/node_modules/hawk/lib/browser.js line length is 3835 characters (>512)
> E: cockpit source: source-is-missing node_modules/less/node_modules/request/node_modules/qs/dist/qs.js line length is 842 characters (>512)
> E: cockpit source: source-is-missing node_modules/less/node_modules/request/node_modules/tough-cookie/lib/pubsuffix.js line length is 29445 characters (>512)
> E: cockpit source: source-is-missing node_modules/less/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/formats.js line length is 1099 characters (>512)
> E: cockpit source: source-is-missing node_modules/po2json/node_modules/gettext-parser/node_modules/encoding/node_modules/iconv-lite/encodings/sbcs-data-generated.js line length is 633 characters (>512)
> E: cockpit source: source-is-missing node_modules/less/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property/is-property.js line length is 10942 characters (>512)

This one is a packaging bug. Shame on me. ;)

> W: cockpit source: restriction-formula-with-debhelper-without-debhelper-version
> N: 
> N:    If a restriction formula appears in the build dependencies or if the
> N:    Build-Profiles field is used in a binary package stanza and the package
> N:    uses debhelper, then the source package has to depend on at least
> N:    debhelper 9.20141010.
> N:    
> N:    Severity: normal, Certainty: certain
> N:    
> N:    Check: fields, Type: binary, udeb, source
> N: 

Another packaging issue (we should probably file an "Intent to package" bug
report for tracking purposes where discussions like this one can be archived).

> W: cockpit-networkmanager: wrong-bug-number-in-closes l3:#XXXXXX
> N: 
> N:    Bug numbers can only contain digits.
> N:    
> N:    Refer to Debian Policy Manual section 4.4 (Debian changelog:
> N:    debian/changelog) for details.
> N:    
> N:    Severity: normal, Certainty: certain
> N:    
> N:    Check: changelog-file, Type: binary
> N: 
> W: cockpit-networkmanager: new-package-should-close-itp-bug
> N: 
> N:    This package appears to be the first packaging of a new upstream
> N:    software package (there is only one changelog entry and the Debian
> N:    revision is 1), but it does not close any bugs. The initial upload of a
> N:    new package should close the corresponding ITP bug for that package.
> N:    
> N:    This warning can be ignored if the package is not intended for Debian or
> N:    if it is a split of an existing Debian package.
> N:    
> N:    Refer to Debian Developer's Reference section 5.1 (New packages) for
> N:    details.
> N:    
> N:    Severity: normal, Certainty: certain
> N:    
> N:    Check: changelog-file, Type: binary
> N: 
> W: cockpit-shell: wrong-bug-number-in-closes l3:#XXXXXX
> W: cockpit-shell: new-package-should-close-itp-bug

Some more work for us here... While Fedora also seems to have a "don't bundle"
policy, in Debian it seems to be taken to a whole other level. If there's anything
you can do as upstream to make it easier for us to replace the bundled javascript
with dependencies on packaged equivalents that would be welcome.

> W: cockpit-shell: embedded-javascript-library usr/share/cockpit/base1/jquery.min.js.gz please use libjs-jquery
> N: 
> N:    This package contains an embedded copy of JavaScript libraries that are
> N:    now available in their own packages (for example, JQuery, Prototype,
> N:    Mochikit or "Cropper"). Please depend on the appropriate package and
> N:    symlink the library into the appropriate location.
> N:    
> N:    Refer to Debian Policy Manual section 4.13 (Convenience copies of code)
> N:    for details.
> N:    
> N:    Severity: normal, Certainty: possible
> N:    
> N:    Check: files, Type: binary, udeb
> N: 

(again, same old warning once for each binary package.)

> W: cockpit-ws: wrong-bug-number-in-closes l3:#XXXXXX
> W: cockpit-ws: new-package-should-close-itp-bug
> W: cockpit: wrong-bug-number-in-closes l3:#XXXXXX
> W: cockpit: new-package-should-close-itp-bug
> W: cockpit-docker: wrong-bug-number-in-closes l3:#XXXXXX
> W: cockpit-docker: new-package-should-close-itp-bug
> W: cockpit-bridge: wrong-bug-number-in-closes l3:#XXXXXX
> W: cockpit-bridge: new-package-should-close-itp-bug
> W: cockpit-pcp: wrong-bug-number-in-closes l3:#XXXXXX
> W: cockpit-pcp: new-package-should-close-itp-bug
> W: cockpit-storaged: wrong-bug-number-in-closes l3:#XXXXXX
> W: cockpit-storaged: new-package-should-close-itp-bug
> W: cockpit-doc: wrong-bug-number-in-closes l3:#XXXXXX
> W: cockpit-doc: new-package-should-close-itp-bug

This is probably something for me to look into, possible packaging bug:

> W: cockpit-doc: zero-byte-file-in-doc-directory usr/share/doc/cockpit/guide/cockpit-guide.proc
> N: 
> N:    The documentation directory for this package contains an empty file.
> N:    This is often due to installing an upstream NEWS or README file without
> N:    realizing it's empty and hence not useful.
> N:    
> N:    Files in the examples subdirectory are excluded from this check, but
> N:    there are some cases where empty files are legitimate parts of the
> N:    documentation without being examples. In those cases, please add an
> N:    override.
> N:    
> N:    Severity: normal, Certainty: possible
> N:    
> N:    Check: files, Type: binary, udeb
> N: 
> N: 1 tag overridden (1 warning)
> I: user script /var/cache/pbuilder/build/14619/tmp/hooks/B92lintian finished

I'm also including a list of files which we currently don't ship at all
in the package (but are built by the upstream build system). If you could
confirm my suspicions/assumptions about these that would be very welcome.

> I: user script /var/cache/pbuilder/build/14619/tmp/hooks/B93list-missing starting
> I: checking for missing files.
> dh list-missing --with=systemd
> dh: Unknown sequence list-missing (choose from: binary binary-arch binary-indep build build-arch build-indep clean install install-arch install-indep)
> debian/rules:6: recipe for target 'list-missing' failed
> make: *** [list-missing] Error 255
> 
> [... a whole lot of files in /usr/src/debug/* stripped from the log ...]
> 

The "playground" module seems to be some testing files which we have not packaged
in Debian. Hopefully not needed/missed.

> dh_install: usr/share/cockpit/playground/po.en.js exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/po.de.js exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/hammer.gif exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/manifest.json exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/plot.min.html exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/plot.html exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/service.js exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/service.min.html exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/service.html exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/patterns.min.html exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/patterns.js exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/patterns.html exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/metrics.min.html exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/metrics.html exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/speed.min.html exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/speed.html exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/test.js exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/test.min.html exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/playground/test.html exists in debian/tmp but is not installed to anywhere

The "subscriptions" module is something RHEL-specific I guess.
Maybe upstream could carry a --disable-foo flag we can use (or even better autodetect
if it's useful to build this module at all if possible) so that real missing files
doesn't get a chance to hide inbetween all these false positives.

> dh_install: usr/share/cockpit/subscriptions/manifest.json exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/subscriptions/subscriptions.min.js.gz exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/subscriptions/subscriptions.min.css.gz exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/subscriptions/index.min.html.gz exists in debian/tmp but is not installed to anywhere

Also "sosreport" is redhat/fedora specific?

> dh_install: usr/share/cockpit/sosreport/run-sosreport.sh exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/sosreport/sosreport.png exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/sosreport/manifest.json exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/sosreport/index.min.js.gz exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/sosreport/sosreport.min.css.gz exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/sosreport/index.min.html.gz exists in debian/tmp but is not installed to anywhere

Unsure if the "ostree" module would work here, so left it out for now....

> dh_install: usr/share/cockpit/ostree/manifest.json exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/ostree/ostree.min.js.gz exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/ostree/index.min.html.gz exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/ostree/ostree.min.css.gz exists in debian/tmp but is not installed to anywhere

Same for "kubernetes". I don't think we carry the core kubernetes bits in Debian yet
so likely won't work here.

> dh_install: usr/share/cockpit/kubernetes/registry.min.css.gz exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/kubernetes/registry.min.js.gz exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/kubernetes/registry.min.html.gz exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/kubernetes/kubernetes.min.js.gz exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/kubernetes/index.min.html.gz exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/kubernetes/kubernetes.min.css.gz exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/kubernetes/override.json exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/kubernetes/manifest.json exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/kubernetes/donut-placeholder.png exists in debian/tmp but is not installed to anywhere
> dh_install: usr/share/cockpit/kubernetes/sparkle-placeholder.png exists in debian/tmp but is not installed to anywhere
> I: user script /var/cache/pbuilder/build/14619/tmp/hooks/B93list-missing finished

**Comment by mvollmer** [comment]
> Even better ofcourse would be
if npm install wasn't used at all in autogen.sh somehow, so we can build debian
packages straight from git snapshots (since Debian buildds do not generally have
network access, as Debian policy mandates packages should be buildable without
network access).

We don't want to include the files generated by the various tools so that it is easy for Debian to patch all the sources. As far as I can remember, this was specifically asked for during initial packaging of Cockpit.  (And personally I am in favor of running autoreconf, etc during build to make it easy to patch configure and fix bugs in autoconf itself.)

But, yeah, including the node modules in the tarball isn't good either.  Would we need to package the missing ones for Debian and then Build-Depend on them?

**Comment by mvollmer** [comment]
> While Fedora also seems to have a "don't bundle"
policy, in Debian it seems to be taken to a whole other level. If there's anything
you can do as upstream to make it easier for us to replace the bundled javascript
with dependencies on packaged equivalents that would be welcome.

When discussing this with Fedora, our position has been: Build-depending on a externally packaged jQuery should be fine, but keeping jQuery out of the binary packages doesn't seem to be worhtwhile.
I am not sure if that position is acceptable, but the issue doesn't seem to be terribly important for Fedora.

**Comment by mvollmer** [comment]
> This one is a big showstopper for us. "Good, not evil license" is not considered
DFSG-free.

Ouch.  jshint should be optional during build, we might be able to just remove it from the sources.

**Comment by mvollmer** [comment]
> The "playground" module seems to be some testing files which we have not packaged
in Debian. Hopefully not needed/missed.

Correct.

**Comment by mvollmer** [comment]
> Also "sosreport" is redhat/fedora specific?

`sosreport` is actually available in Debian, but we haven't yet tried it out.

**Comment by mvollmer** [comment]
> Unsure if the "ostree" module would work here, so left it out for now....

> Same for "kubernetes". I don't think we carry the core kubernetes bits in Debian yet
so likely won't work here.

Makes sense.

**Comment by stefwalter** [comment]
> While Fedora also seems to have a "don't bundle" policy, in Debian it seems to be taken to a whole other level. If there's anything you can do as upstream to make it easier for us to replace the bundled javascript with dependencies on packaged equivalents that would be welcome.

Is this during build or during deployment? If the latter, then does Debian have a compressed compatible identical version of jQuery 2.1.4?

**Comment by stefwalter** [comment]
> I guess the following comes from the autogen.sh usage of npm install which then
gets shipped in the tarball. We need to ship all sources (preferable form of
modification) in Debian, so maybe it's possible to get the sources for these
node modules bundled within the tarball as well? Even better ofcourse would be
if npm install wasn't used at all in autogen.sh somehow, so we can build debian
packages straight from git snapshots (since Debian buildds do not generally have
network access, as Debian policy mandates packages should be buildable without
network access).

The git snapshots (and autogen.sh) are for development. A lot of distribution happens during the creation of the real dist tarball, including pulling together licenses. Lets not use the git snapshots for actual packaged releases. The real dist tarball doesn't include autogen.sh FWIW.

**Comment by stefwalter** [comment]
Stop distributing jshint in the tarballs: #4165

Again, please use the release real tarballs for building packages.

**Comment by andhe** [comment]
Hello!

> We don't want to include the files generated by the various tools so that it is easy for Debian to patch all the sources. 

I'm not sure what you're trying to tell me here, but Debian doesn't really want generated files in the tarballs either. It is preferred to generate things during the build step. What is needed is for preferable form of modification (source) to be available (even if unused because of pre-generated files) for the ftp-masters to let things into the archive (as a general rule) in my experience. As I understand it the Debian archive is supposed to be self-contained as internet access is not a requirement for the  freedoms the Social Contract promises you. Thus "go fish on the internet" is not a valid answer for "where are the sources?".

> As far as I can remember, this was specifically asked for during initial packaging of Cockpit. (And personally I am in favor of running autoreconf, etc during build to make it easy to patch configure and fix bugs in autoconf itself.)

We generally don't want to patch these files, rather the reason for autoreconf during build is that (pre-)generated files will not cut it when you introduce a new architecture for example. You'll need to regenerate based on new sources and just patching the source and rebuilding is much easier then having to patch every single package in the archive.

> 
> But, yeah, including the node modules in the tarball isn't good either. Would we need to package the missing ones for Debian and then Build-Depend on them?

Doing that would earn you a gold star, but not strictly required. The goal is to avoid duplication of sources, so if noone else uses them it's ok to bundle them in your source tarball. But sooner or later someone else will and then the question of packaging them separately will likely come up.

**Comment by stefwalter** [comment]
> I'm not sure what you're trying to tell me here, but Debian doesn't really want generated files in the tarballs either. It is preferred to generate things during the build step. What is needed is for preferable form of modification (source) to be available (even if unused because of pre-generated files) for the ftp-masters to let things into the archive (as a general rule) in my experience. As I understand it the Debian archive is supposed to be self-contained as internet access is not a requirement for the freedoms the Social Contract promises you. Thus "go fish on the internet" is not a valid answer for "where are the sources?".

The sources are all in the tarball. 'make clean' and 'make distclean' will remove anything that's pregenerated from the tarball. As you're aware, all autotools tarballs contain generated sources, in addition to the original sources.

If this is not the case for one of the sources, then that's a bug, and we'll jump on fixing it.

> We generally don't want to patch these files, rather the reason for autoreconf during build is that (pre-)generated files will not cut it when you introduce a new architecture for example. You'll need to regenerate based on new sources and just patching the source and rebuilding is much easier then having to patch every single package in the archive.

Makes sense. Just don't run autogen.sh (which isn't in the tarball anyway) as that's for developers not packagers.

> Doing that would earn you a gold star, but not strictly required. The goal is to avoid duplication of sources, so if noone else uses them it's ok to bundle them in your source tarball. But sooner or later someone else will and then the question of packaging them separately will likely come up.

Roger. Totally agree. Shipping the node_modules in the tarball is like shipping m4 files. Packagers can replace them as energy and requirements permit.

**Comment by stefwalter** [comment]
> Roger. Totally agree. Shipping the node_modules in the tarball is like shipping m4 files. Packagers can replace them as energy and requirements permit.

As explained in node_modules/README, the stuff in node_modules are build-time dependencies, not runtime dependencies. Just figured that would help explain my analogy to m4 files for anyone following along.

**Comment by andhe** [comment]
Hi again @mvollmer 

> When discussing this with Fedora, our position has been: Build-depending on a externally packaged jQuery should be fine, but keeping jQuery out of the binary packages doesn't seem to be worhtwhile.
> I am not sure if that position is acceptable, but the issue doesn't seem to be terribly important for Fedora.

Debian there's a (still relatively new) package field called Built-Using: which should be inserted in the binary package containing the package and version which was used to pull in parts from.

See for example:
http://sources.debian.net/src/libselinux/2.4-3/debian/rules/#L15
http://sources.debian.net/src/libselinux/2.4-3/debian/rules/#L83
http://sources.debian.net/src/libselinux/2.4-3/debian/control/#L105

Apparently python-selinux binary package contains things copied/generated from it's build-dependency libsepol1-dev.

**Comment by andhe** [comment]
> sosreport is actually available in Debian, but we haven't yet tried it out.

Oh, right. Thanks for pointing it out. Will keep this in mind next time I touch the debian collab-maint cockpit git repo and look into shipping the sosreport bits. Ping @mbiebl FYI.

**Comment by andhe** [comment]
Hello @stefwalter 

> The sources are all in the tarball. 'make clean' and 'make distclean' will remove anything that's pregenerated from the tarball. As you're aware, all autotools tarballs contain generated sources, in addition to the original sources.

Thanks for your insight. Personally I haven't really looked at this more then a couple of minutes, the issues reported here are all by the auto checking tool lintian. When uploading for NEW processing in Debian this will be the first thing ftp-masters look at for their review and if any issues are reported they expect a really good answer to be available right in front of them. Usually easiest way to have a smooth ride through NEW is simply to fix things up so even lintian can find them. Might be that whoever uploads this to the Debian archive will just need to invest a bit more time and point out where the sources are located which lintian didn't find.

**Comment by andhe** [comment]
FYI I've filed bug reports in the official places to hopefully locate someone interested in taking on the role as official Debian maintainer:

storaged: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820099
cockpit: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820107

**Comment by andhe** [comment]
The fix for issue #3436 should resolve one of the main blockers in this issue for Debian archive uploads. Not sure if there's anything useful left to fix in this issue or if it should be closed?

**Comment by larskarlitski** [comment]
I agree. Also, let's create smaller, more focused issues if we find new ones.
