### ISSUE TITLE
storage: Selection of devices for Add button for RAID array and for Create button for RAID array different

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#4169]
The list for Create shows one more device...the particular multipathed partition device that I want to add to my RAID array. The list for the Add button does not show that device.

**Comment by mulkieran** [comment]
I think the reason for this is that the device, which formerly belonged to the array, mdadm considers not large enough to be added to the array. So, this feels like an mdadm issue, and correct behavior on Cockpit's part.

**Comment by mulkieran** [comment]
This problem is confirmed...I briefly thought there was an mdadm reason for the partition device being missing, but I had my arrays confused.

**Comment by mvollmer** [comment]
> I briefly thought there was an mdadm reason for the partition device being missing, but I had my arrays confused.

Cockpit doesn't go that deep when constructing the list of devices to offer: It will omit devices that are "in use".  I think we need to improve this and at least explain why some devices are omitted, and maybe allow people to add them anyway, with proper warning.

**Comment by mvollmer** [comment]
> It will omit devices that are "in use". 

And this doesn't explain the difference you have observed, so there is indeed a bug.  Can you help with reproducing this, or adding debugging code in your copy of Cockpit?

Please have a look at `utils.get_free_blockdevs` here: https://github.com/cockpit-project/cockpit/blob/master/pkg/storaged/utils.js#L235

**Comment by mulkieran** [comment]
Like you say, it's probably the extra filter function at https://github.com/cockpit-project/cockpit/blob/master/pkg/storaged/details.js#L512 that is going wrong. In my case, every one of the members of the RAID is a partition on a separate multipath device. So each raid member is not, strictly speaking, a partition device, instead it is a device mapper device, controlled by kpartx, which maps to the actual partition on the drive.
The link between these kpartx device mapper devices and their actual partitions is a bit tenuous.

I _think_ that the code in the filter function is trying to filter out partition devices if the device that they partition is already a member of the RAID device to be added to. That seems right.

Here's a possibility. The device _is_ among the ```blocks_part```  array, because it has a partitiony like quality. OTOH, the lookup in client.blocks fails because it's not really a partition device. So b is null, and the device gets filtered out.

Another possibility is that ```client.blocks[b.path].MDRaid == path``` (because the device just got removed from the array and I'm trying to re-add it). That seems just as likely as the first idea.

I could take a look and see whether either of these hypotheses is true. This would be my first attempt every to actually debug Javascript code. Do you have any basic pointers?

**Comment by mulkieran** [comment]
Firebug is OK.

And it's the first option, b is ```undefined``` after the ```if``` block is executed.

**Comment by mulkieran** [comment]
And it's undefined because ```client.blocks_part[b.path].PartitionTable``` is undefined.

**Comment by mulkieran** [comment]
here's a selection from the debugger + screen showing the missing device:

![screenshot from 2016-04-08 15-03-30](https://cloud.githubusercontent.com/assets/1218366/14394628/2f121cd6-fd9b-11e5-822b-99824e2a5d01.png)

and also storagedctl dump output:

[storagedctl.dump.txt](https://github.com/cockpit-project/cockpit/files/210720/storagedctl.dump.txt)

**Comment by mulkieran** [comment]
Ok, this all seems to be the result of a simple typo, see #4180.

**Comment by mvollmer** [comment]
> Ok, this all seems to be the result of a simple typo, see #4180.

Damn.  "Code is either tested or buggy."  Thanks a lot!

**Comment by mvollmer** [comment]
> I think that the code in the filter function is trying to filter out partition devices if the device that they partition is already a member of the RAID device to be added to. That seems right.

The intention is to filter out block devices that are the mdraid device itself, or parts of it.  For example, if the mdraid is /dev/md127, then we want to filter out /dev/md127, /dev/md127p1, /dev/md127p2, etc.

This is incomplete: If you use /dev/md127 as a physical volume for a LVM2 volume group and make a logical volume in that volume group, this lvol wouldn't get filtered out.  I have no idea what happens if you try to add it as a physical volume to the mdraid...

**Comment by mvollmer** [comment]
This is fixed.
