### ISSUE TITLE
storage: ghost among the drives

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#4170]
![screenshot from 2016-04-07 17-20-46](https://cloud.githubusercontent.com/assets/1218366/14367297/27c7ab6e-fce5-11e5-9900-019649bca379.png)

I got here by pulling the plug on an enclosure. The enclosure contained four drives, all of which were multipathed, two of the multipath devices belonged to a RAID device.

I'm not sure whether this device was already there before I did I/O to the RAID device or only afterward.

It doesn't respond to clicks, the link is just "".

**Comment by mulkieran** [comment]
When I turned the enclosure back on, the ghost stayed, and the four restored drives showed up immediately below it.

**Comment by mvollmer** [comment]
The ghost probably exists in the UDisks2 API and Cockpit just shows it mindlessly. I guess it doesn't have an associated block device, and we could just ignore those.

**Comment by martinpitt** [comment]
This is an ancient bug report, not reproducible. Can you still reproduce this? If you ever run into this again, can you please copy&paste the output of `udisksctl dump` here? I'll reopen the report then. Thanks!
