### ISSUE TITLE
storage: would be nice to have some sort of "patch this thing back up" button for RAID devices

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#4171]
In situation like below:

![screenshot from 2016-04-07 17-37-56](https://cloud.githubusercontent.com/assets/1218366/14367764/e22f8dbc-fce7-11e5-99ef-9ec9e197c933.png)

it would be nice to be able to press one button that did the necessary to restore the device, assuming that the member devices were all fixed up.

**Comment by martinpitt** [comment]
I just tested this with current Cockpit 238, by unbinding and re-binding one RAID member. After that, I can stop and restart the array, which gets it re-synced. @mvollmer, can this be done without stop/start even, i.e. starting a sync in a running degraded raid?

**Comment by mvollmer** [comment]
> I just tested this with current Cockpit 238, by unbinding and re-binding one RAID member. After that, I can stop and restart the array, which gets it re-synced. @mvollmer, can this be done without stop/start even, i.e. starting a sync in a running degraded raid?

As far as I know, a MDRAID will automatically sync as soon as a spare becomes available, see TestStorageMdRaid.testRaid integration test.

Cockpit used to have a "Scrub" button, but we have removed it: #8860

I don't actually know how this is all supposed to work.  With concrete enough input, we can certainly improve Cockpit here, but it would need to be very concrete, with exact details of what the equivalent mdadm invocation would be etc.

**Comment by martinpitt** [comment]
Stale, underspecified, nothing actionable. Closing.
