### ISSUE TITLE
Install cockpit deb package fails on Debian testing with docker.io already installed

### ISSUE THREAD

**Issue by jeremiah** [cockpit-project/cockpit#4179]
`$ apt install cockpit `

**Produces the following error;**

Setting up docker.io (1.8.3~ds1-2) ...
addgroup: The group `docker' already exists as a system group. Exiting.
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
dpkg: error processing package docker.io (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of cockpit-docker:
 cockpit-docker depends on docker.io (>= 1.3.0); however:
  Package docker.io is not configured yet.

dpkg: error processing package cockpit-docker (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 docker.io
 cockpit-docker
E: Sub-process /usr/bin/dpkg returned an error code (1)

**And systemctl restart docker.service says;**

● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2016-04-08 15:26:15 CEST; 4s ago
     Docs: https://docs.docker.com
  Process: 12796 ExecStart=/usr/bin/docker daemon -H fd:// $DOCKER_OPTS (code=exited, status=1/FAILURE)
 Main PID: 12796 (code=exited, status=1/FAILURE)

Apr 08 15:26:15 jefo-debian systemd[1]: Starting Docker Application Container Engine...
Apr 08 15:26:15 jefo-debian docker[12796]: time="2016-04-08T15:26:15.565610943+02:00" level=error msg="[graphdriver] prior storage driver \"aufs\" failed: driver not supported"
Apr 08 15:26:15 jefo-debian docker[12796]: time="2016-04-08T15:26:15.565684077+02:00" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported"
Apr 08 15:26:15 jefo-debian systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Apr 08 15:26:15 jefo-debian systemd[1]: Failed to start Docker Application Container Engine.
Apr 08 15:26:15 jefo-debian systemd[1]: docker.service: Unit entered failed state.
Apr 08 15:26:15 jefo-debian systemd[1]: docker.service: Failed with result 'exit-code'.

**Comment by mvollmer** [comment]
Isn't that a docker issue?  Or is `docker.io` the wrong package to depend on?

**Comment by jeremiah** [comment]
I think you're right -- this is a docker issue. I think docker.io is the right dependency.

**Comment by janza** [comment]
Instructions on [docker docs](https://docs.docker.com/engine/installation/linux/debian/) state that correct package name is `docker-engine`
