### ISSUE TITLE
Registry: image view should be "Collapsed" by default

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#4189]
With version 0.101 the Image page has the tags "expanded", which is a bit daunting when a large number of images are displayed. A [+] element for each image would help convey there's more info.

Note: expand/collapse control doesn't appear to be working with version 0.1.01.

**Comment by stefwalter** [comment]
Could you include a screenshot?

**Comment by aweiteka** [comment]
![screen shot 2016-04-12 at 8 23 16 am](https://cloud.githubusercontent.com/assets/1764461/14459929/d9e1f1a0-0088-11e6-9e1c-bcff46b8d221.png)

**Comment by stefwalter** [comment]
@aweiteka Suggested we should be able to hide the tags here, or have them hidden by default.

**Comment by aweiteka** [comment]
@stefwalter suggested maybe collapsing when displaying "All projects", expanding when a specific project is selected.

**Comment by andreasn** [comment]
I've added this to my todo

**Comment by martinpitt** [comment]
Tabs are now shown in a horizontal list, without individual details in the overview.
