### ISSUE TITLE
ws : Chromium empty response

### ISSUE THREAD

**Issue by marmeladema** [cockpit-project/cockpit#4201]
I have a problem with a letsencrypt certificate using chromium on debian 8

> ERR_EMPTY_RESPONSE

[http://www.zimagez.com/full/e9c38030921035be817defaa1cf6b75442002534960af7d49fbcd8c2d59f653e59a39294d88429b3bb3b48a06e0425da81e42557cc468aea.php](http://www.zimagez.com/full/e9c38030921035be817defaa1cf6b75442002534960af7d49fbcd8c2d59f653e59a39294d88429b3bb3b48a06e0425da81e42557cc468aea.php)

But it works with firefox and I'm using the same certificate for other services on the same host with nginx and it works fine with every browers i've tested. It seems to be a problem related to cockpit, not to the certificate.

The certificate incluses my cert, letsencrypt intermediate ca cert and my private key, in this order. I tried to shuffle things around but then, it never works on any browser.

On the ws side, i have this message

> cockpit-protocol-Message: request timed out, closing

With --no-tls, it works fine with every browser.

**Comment by larskarlitski** [comment]
I'm closing this because it's an old bug and there was no further indication that this is a cockpit-specific problem. Feel free to reopen when you're still seeing this issue.
