### ISSUE TITLE
javascript oops on storage tab

### ISSUE THREAD

**Issue by zdzichu** [cockpit-project/cockpit#4209]
Hi,

 I'm using Cockpit as packaged for Fedora 24 and Rawhide:
cockpit-ws-0.101-1.fc24.x86_64
storaged-2.5.0-5.fc25.x86_64
storaged-iscsi-2.5.0-5.fc25.x86_64

When I open storage tab, there's a red Ooops! displayed in upper-righthand corner. Javascript console contains sparse information about target_name (screenshot attached).

Please guide me: how can I provide more useful logs to debug this issue?
![cockpit-storage-oops](https://cloud.githubusercontent.com/assets/496236/14519005/49333318-021c-11e6-80f4-8761d6d458bc.png)

**Comment by mvollmer** [comment]
I believe this is fixed.  The code now uses `a.data["target_name"]`.
