### ISSUE TITLE
Registry: "New project" policy fixes

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#4218]
Version 0.102

New project policy selection isn't providing the correct permissions. Below is the tested behavior we want. Note, I added "project" to the pull-down menu text to make it clearer.

*Allow only project members to pull images* should remove registry-viewer permission (this is necessary since the default project template may add this by default).

```
oc policy remove-role-from-group registry-viewer system:authenticated -n <project>
```

*Allow project non-members to pull images* should add registry-viewer permission
```
oc policy add-role-to-group registry-viewer system:authenticated -n <project>
```

**Future**
We want to support unauthenticated docker pull. See backlog item https://trello.com/c/Ev8y3pC4
In this case we would want to add an "unauthenticated users" drop-down

*Allow anyone to pull images* should add registry-viewer permission to unauth'd
```
oc policy add-role-to-group registry-viewer system:unauthenticated -n <project>
```

**Comment by aweiteka** [comment]
cc @sub-mod

**Comment by aweiteka** [comment]
@sub-mod if this isn't in your current work in progress I can take this.

**Comment by sub-mod** [comment]
@aweiteka please take it
