### ISSUE TITLE
Kubernetes topology sidebar: If too much text, parts are elided

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#4226]
![screenshot from 2016-04-18 12-23-18](https://cloud.githubusercontent.com/assets/209895/14601089/636aa86e-0560-11e6-8dc8-43c9fffcf11f.png)

**Comment by dperpeet** [comment]
This is still current.
![screenshot from 2016-06-14 15-36-11](https://cloud.githubusercontent.com/assets/8711649/16044828/47c8fed6-3246-11e6-8f45-c73936d1a90b.png)

**Comment by andreasn** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
