### ISSUE TITLE
at centos 7,I cannot make the project . It stop at "GEN    pkg/base1/angular.min.js"

### ISSUE THREAD

**Issue by jake2009** [cockpit-project/cockpit#4239]
in centos 7, I cannot make the project .
 It stop at "GEN    pkg/base1/angular.min.js" .
I want a rpm packet to install cockpit .

**Comment by stefwalter** [comment]
@jake2009 What is the build output?

**Comment by jake2009** [comment]
@stefwalter  output nothing  just stop at "GEN pkg/base1/angular.min.js"
I cannot upload my images .
....
  CC       src/remotectl/remotectl-certificate.o
  CC       src/remotectl/remotectl-remotectl.o
  CCLD     remotectl
  GEN      mock-auth-command
chmod +x mock-auth-command
  GEN      doc/man/cockpit-bridge.1
  GEN      doc/man/cockpit.1
  GEN      doc/man/cockpit-ws.8
  GEN      doc/man/cockpit.conf.5
  GEN      doc/man/pam_ssh_add.8
  GEN      doc/man/remotectl.8
  ITMRG  src/ws/cockpit.appdata.xml
  GEN      po/po.ca.js
  GEN      po/po.de.js
  GEN      po/po.da.js
  GEN      po/po.pl.js
  GEN      po/po.pt_BR.js
  GEN      po/po.tr.js
  GEN      po/po.uk.js
  ITMRG  src/ws/cockpit.desktop
  GEN      pkg/base1/angular.min.js

just stop there . I wait for one day...

**Comment by stefwalter** [comment]
This should now be fixed with the move to webpack for building cockpit's javascript components.
