### ISSUE TITLE
service action drop down menu has too many options

### ISSUE THREAD

**Issue by abonas** [cockpit-project/cockpit#424]
When selecting a specific service in a host (host->services->service)
there's a dropdown list starting with "stop".
Inside, there are a lot of options, some of them repeating itself with different variations.
For example: Restart, Reload, Reload or Restart.
It will be more clear to have less options and have them better defined.
(It's not clear why there's a need for 
![serviceoptionscockpit](https://cloud.githubusercontent.com/assets/6277245/2630235/a8c8797c-be45-11e3-9246-7a3719eb548a.png)
: "option1", "option2", "option1 or option2")

**Comment by mvollmer** [comment]
(I finally try to catch up with old issues.)

Yeah, I just dumped all the systemctl commands in there.  The try-this-or-that variants are only rally useful for use in scripts where you don't want to cobble together the logic yourself.  In an interactive UI, we can reduce the list to the basics and expect people to try "restart" when they see that "reload" didn't work.
