### ISSUE TITLE
Universal Docker container?

### ISSUE THREAD

**Issue by cdrage** [cockpit-project/cockpit#4250]
So after a bit of Google'ing and looking through some of the documentation I wasn't able to find a *universal* containerized version of Cockpit (other than the one used for Atomic Hosts).

I'd *love* to use a universal Docker container that would effectively work on Debian, CoreOS, CentOS, anything you wish.

May of been a stupid question as there may have already been one out there!

**Comment by petervo** [comment]
Cockpit is would need to manager the underlying host not what is in the container. Having a universal container is not super straight forward as there can be pretty major differences between the system APIs on different distros and releases. There is a feature page with some ideas of how this might work here: https://github.com/cockpit-project/cockpit/wiki/Feature:-Cockpit-Container. If you have specific ideas of how this should be done feel free to edit or comment there

**Comment by cdrage** [comment]
I meant managing the underlying host (by passing --net=host, -v /:/host, etc.) to the docker container :)

But yes, i will look at the page! Thank you :)

**Comment by mdecou** [comment]
@cdrage I am curious... were you able to find a way to pass --net=host to a container from within Cockpit?

**Comment by cdrage** [comment]
@mdecou nope, sorry!

**Comment by stefwalter** [comment]
@mdecou @cdrage This would be an interesting thing to add to the run dialog. Are you up for contributing such a change?

**Comment by mdecou** [comment]
haha... I do not have the skills to contribute  (I wish I did).
