### ISSUE TITLE
Update PPA for Ubuntu

### ISSUE THREAD

**Issue by bjackson** [cockpit-project/cockpit#4263]
The latest build for the Ubuntu PPA is 0.92. This does not include changes for recent versions of Docker and the containers section of Cockpit is broken for post 1.10 releases of Docker.

Could a new build be made for the most recent release and pushed to the PPA?

**Comment by stefwalter** [comment]
Which PPA are you using? We just pushed 0.103 to the one listed here yesterday: http://cockpit-project.org/running.html

**Comment by bjackson** [comment]
Oops, I was using this one:
https://launchpad.net/~jpsutton/+archive/ubuntu/cockpit

**Comment by stefwalter** [comment]
> Oops, I was using this one: https://launchpad.net/~jpsutton/+archive/ubuntu/cockpit

No worries, the one that gets automatic pushes is a new one.

@jpsutton By the way there's a new PPA  for Cockpit that gets automatically pushed to every week. See http://cockpit-project.org/running.html

**Comment by bjackson** [comment]
Yeah, I switched over to that one and everything's running smooth. Didn't notice that the PPA had changed. Thanks!
