### ISSUE TITLE
Fedora: SELinux breaks kubernetes mounting of certificate

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#4270]
kubernetes tests failing on fedora-24
Filed on [bugzilla #1324456](https://bugzilla.redhat.com/show_bug.cgi?id=1324456) against docker.

@stefwalter Has removed some of the many comments here.

Errors look like [this](http://files.cockpit-project.org/logs/pull-4269-b5d13cca-verify-fedora-24/log.html#27):

```
Unexpected journal message 'audit: type=1401 audit(1461305082.057:276): op=security_compute_av reason=bounds scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=siginh'
Journal extracted to TestConnection-testConnect-10.111.119.4-FAIL.log
Wrote TestConnection-testConnect-FAIL.png
Journal extracted to TestConnection-testConnect-10.111.119.4-FAIL.log
not ok 29 testConnect (check_kubernetes.TestConnection)
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 504, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 625, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1461305082.057:276): op=security_compute_av reason=bounds scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=siginh


```

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 504, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 625, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1461925292.392:293): op=security_compute_av reason=bounds scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=siginh
```
First occurrence: 2016-04-29T10:21:54.617739 | revision fe53557e956b7e7224483207718106e3288b90e9, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4326-fe53557e-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-04-29T10:21:54.617739 | revision fe53557e956b7e7224483207718106e3288b90e9, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4326-fe53557e-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 505, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 626, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1465824707.834:311): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c650,c683 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-06-13T13:32:14.401171 | revision 9c60841d9938babc77394574e08b02f2ddbb8837, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4565-9c60841d-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-06-13T13:32:14.401171 | revision 9c60841d9938babc77394574e08b02f2ddbb8837, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4565-9c60841d-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 506, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 631, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1468337419.161:222): op=security_compute_av reason=bounds scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=siginh
```
First occurrence: 2016-07-12T15:31:02.698253 | revision 131511dbb07918aab01c9a16f58b8bba784130bc, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4717-131511db-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2016-07-12T15:31:02.698253 | revision 131511dbb07918aab01c9a16f58b8bba784130bc, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4717-131511db-verify-fedora-testing/log.html)

**Comment by stefwalter** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 652, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1470646428.446:277): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c96,c107 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-08-08T10:53:59.064121
Times recorded: 1
Latest occurrences:

- 2016-08-08T10:53:59.064121

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 652, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1470762224.898:258): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c529,c1014 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-08-09T17:04:09.261292 | revision e69523a8c12bc8e0bd478fa495eecf76b1ae31b5, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4807-e69523a8-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-08-09T17:04:09.261292 | revision e69523a8c12bc8e0bd478fa495eecf76b1ae31b5, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4807-e69523a8-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 652, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1470848052.460:219): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c362,c559 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-08-10T16:55:22.769992 | revision 2b0aaecdbd9357a32dd2a5db5ceb0d42cce17406, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4848-2b0aaecd-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-08-10T16:55:22.769992 | revision 2b0aaecdbd9357a32dd2a5db5ceb0d42cce17406, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4848-2b0aaecd-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 652, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1470883668.447:254): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c758,c856 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-08-11T02:47:56.726951 | revision a2d9c3c0d11f77b0f81793187514fc50cc128222, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4849-a2d9c3c0-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-08-11T02:47:56.726951 | revision a2d9c3c0d11f77b0f81793187514fc50cc128222, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4849-a2d9c3c0-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 650, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1470940463.673:224): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c0,c967 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-08-11T18:34:33.952029 | revision b9d111c45310e3b75f64b0ce7c37b9c9d1cd17b9, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4708-b9d111c4-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-08-11T18:34:33.952029 | revision b9d111c45310e3b75f64b0ce7c37b9c9d1cd17b9, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4708-b9d111c4-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 650, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1471060708.380:258): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c75,c345 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-08-13T03:58:47.019854 | revision 6a280c0afb56f47a11d175078f413f61cd875608, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4869-6a280c0a-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-08-13T03:58:47.019854 | revision 6a280c0afb56f47a11d175078f413f61cd875608, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4869-6a280c0a-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 650, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1471283576.916:221): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c13,c649 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-08-15T17:53:37.918274 | revision e7a4a1565a52eacfd6148a04cee6251d6f522c3b, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4878-e7a4a156-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-08-15T17:53:37.918274 | revision e7a4a1565a52eacfd6148a04cee6251d6f522c3b, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4878-e7a4a156-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 650, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1471384226.908:245): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c112,c401 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-08-16T21:50:21.371285 | revision 2b2a4563a7bae1741d8ba6dab5581af2fa27e839, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4840-2b2a4563-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-08-16T21:50:21.371285 | revision 2b2a4563a7bae1741d8ba6dab5581af2fa27e839, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4840-2b2a4563-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 650, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1471500525.029:256): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c794,c883 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-08-18T06:08:56.849838 | revision e1ee7d91dd4edea7d308bbbad4c76e8f95c717e3, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4894-e1ee7d91-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-08-18T06:08:56.849838 | revision e1ee7d91dd4edea7d308bbbad4c76e8f95c717e3, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4894-e1ee7d91-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 651, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1471537343.139:259): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c553,c952 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-08-18T16:22:23.684901 | revision 29b9603c010cbc360545424a685bb8fbbde70a13, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4827-29b9603c-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-08-18T16:22:23.684901 | revision 29b9603c010cbc360545424a685bb8fbbde70a13, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4827-29b9603c-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 651, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1471675019.264:223): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c198,c832 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-08-20T06:37:28.669263 | revision ac7d9af5c928543b7dad0560cc760d00f39a6cb3, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4827-ac7d9af5-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-08-20T06:37:28.669263 | revision ac7d9af5c928543b7dad0560cc760d00f39a6cb3, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4827-ac7d9af5-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 651, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1471885062.980:260): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c635,c955 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-08-22T16:57:55.915977 | revision acb89f9d449a7b28b68490bb21ed86c45b257cf0, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4923-acb89f9d-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-08-22T16:57:55.915977 | revision acb89f9d449a7b28b68490bb21ed86c45b257cf0, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4923-acb89f9d-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 648, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1472188868.423:256): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c224,c741 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-08-26T05:21:12.221724 | revision f6dfd6f1a92e53f485d50465ec3f61b4b0d30f81, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4932-f6dfd6f1-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-08-26T05:21:12.221724 | revision f6dfd6f1a92e53f485d50465ec3f61b4b0d30f81, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4932-f6dfd6f1-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 648, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1472692304.250:206): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c304,c481 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-09-01T01:12:23.247088 | revision 9fd1afd60627d8a73b2dda1185b97e054bac57d5, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4951-9fd1afd6-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-01T01:12:23.247088 | revision 9fd1afd60627d8a73b2dda1185b97e054bac57d5, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4951-9fd1afd6-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 648, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1473006601.048:204): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c118,c201 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-09-04T16:30:42.073757 | revision ce8731ac033937354f0e6e21204190e6b59e78dc, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4565-ce8731ac-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-04T16:30:42.073757 | revision ce8731ac033937354f0e6e21204190e6b59e78dc, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4565-ce8731ac-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 648, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1473130041.664:204): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c571,c833 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-09-06T02:47:39.130066 | revision b87e0cbaca3d1a3d8c3f67e7fad739653327df82, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4965-b87e0cba-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-06T02:47:39.130066 | revision b87e0cbaca3d1a3d8c3f67e7fad739653327df82, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4965-b87e0cba-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 648, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1473175693.514:224): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c174,c852 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-09-06T15:28:28.117937 | revision 657ad9e77bf68cb46013bf66e63bf82121dbbd09, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4904-657ad9e7-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-06T15:28:28.117937 | revision 657ad9e77bf68cb46013bf66e63bf82121dbbd09, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4904-657ad9e7-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 648, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1473201133.070:262): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c591,c954 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-09-06T22:32:35.734522 | revision bb5133a7a1a592bda05d2cd247b78d476fe6abcf, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4974-bb5133a7-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-06T22:32:35.734522 | revision bb5133a7a1a592bda05d2cd247b78d476fe6abcf, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4974-bb5133a7-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 648, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1473336554.578:263): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c524,c915 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-09-08T12:09:33.991695 | revision 493f77ba67de5e11722a27e6267f7375a9cbada8, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4991-493f77ba-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-08T12:09:33.991695 | revision 493f77ba67de5e11722a27e6267f7375a9cbada8, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4991-493f77ba-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 648, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1473376144.845:224): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c235,c687 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-09-08T23:09:16.873886 | revision 9c485fec7098ac0d7deeb225752303bb2587fa62, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4881-9c485fec-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-08T23:09:16.873886 | revision 9c485fec7098ac0d7deeb225752303bb2587fa62, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4881-9c485fec-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 648, in check_journal_messages
    raise Error(first)
Error: audit: type=1401 audit(1473426078.144:224): op=security_compute_av reason=bounds scontext=system_u:system_r:svirt_lxc_net_t:s0:c50,c886 tcontext=system_u:system_r:docker_t:s0 tclass=process perms=getattr
```
First occurrence: 2016-09-09T13:01:36.286241 | revision f40801f50bc5e6d578fdd02d27a46ab4834241c0, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4878-f40801f5-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-09T13:01:36.286241 | revision f40801f50bc5e6d578fdd02d27a46ab4834241c0, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4878-f40801f5-verify-fedora-24/log.html)

**Comment by rhatdan** [comment]
What version of docker-selinux do you have?

**Comment by rhatdan** [comment]
What version of docker-selinux do you have?

**Comment by stefwalter** [comment]
@rhatdan We track the latest Fedora 24 version in the fedora-24 image. At present: 

```
# rpm -qa docker-selinux
docker-selinux-1.10.3-26.git1ecb834.fc24.x86_64
# yum update docker-selinux
...
Dependencies resolved.
Nothing to do.
Complete!
```

**Comment by rhatdan** [comment]
What version of docker-selinux do you have?

**Comment by rhatdan** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2016-adecb6c677
Says that docker-1.10.3-50 version is available in f24.  Although I want to get it to 53 to match what is going into RHEL7.3

**Comment by marusak** [comment]
This naughty is not tracked anymore.
