### ISSUE TITLE
setroubleshoot: Issues not fixable via sealert

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#4281]
There is a fedora-24 problem right now relating to the way setroubleshoot-server works internally. Neither Cockpit nor the cli seem to get proper selinux issue information or can list possible solutions / apply a solution.

https://bugzilla.redhat.com/show_bug.cgi?id=1329550

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-setroubleshoot", line 121, in testTroubleshootAlerts
    b.wait_in_text(row_selector, "you must fix the labels")
  File "testlib.py", line 239, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 659, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 682, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-04-25T10:42:07.605767 | revision dbddce03ecc2e56587703c6d76ece3f06f56d017, [logs](http://files.cockpit-project.org/logs/pull-4269-dbddce03-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-04-25T10:42:07.605767 | revision dbddce03ecc2e56587703c6d76ece3f06f56d017, [logs](http://files.cockpit-project.org/logs/pull-4269-dbddce03-verify-fedora-24/log.html)
