### ISSUE TITLE
Registry: Needs a better empty state

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#4290]
The image page falls apart visually. The "Create new Image Stream" floats midair.

![screenshot from 2016-04-26 14-09-05](https://cloud.githubusercontent.com/assets/209895/14817618/a7bff9ac-0bb8-11e6-8852-1ee0221bd519.png)

The Cluster pages has a line above the table headers that helps things to hold together a bit better.
![screenshot from 2016-04-26 14-10-56](https://cloud.githubusercontent.com/assets/209895/14817663/e441121c-0bb8-11e6-865f-726cff7a04a1.png)

**Comment by andreasn** [comment]
This seems to be due to a inline style for `table.images-listing thead th` that sets `border-top: none;`

**Comment by stefwalter** [comment]
I think the entire header row should disappear when no images are present. This should be a standard thing in the listing view. The empty/failure message should replace the entire thing.

**Comment by andreasn** [comment]
I agree about that.
However, the issue remains when there are several images there as well I think.

**Comment by andreasn** [comment]
Eh, nevermind, I checked now. You're right. I'll rename this to be about the empty state.

**Comment by dperpeet** [comment]
In react I'll use something similar to https://github.com/cockpit-project/cockpit/blob/6165d634921bbc2a31bdca7d54a1dfa5ecfda0cc/pkg/selinux/setroubleshoot-view.jsx#L324

**Comment by stefwalter** [comment]
I don't think we should use "curtains" in this case. That's when the entire page can't be displayed due to a missing API, connection issue, or so on. The listing view has a class "listing-empty" that is built for this purpose. Do you think it works in this case?

**Comment by andreasn** [comment]
Closing, since we're deprecating Registry, so no longer applies.
