### ISSUE TITLE
Allow robust RAID cleanup

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#43]
It is possible to do 'stupid' things with RAIDs in Cockpit that can't be undone with it.

When starting a RAID fails, this might leave inactive raids behind that udisks2 doesn't seem to handle well. Those arrays can keep disks busy, but udisks2 will not allow inactive arrays to be stopped. (It either ingnores them or pretends they are not running.)

See ​https://bugs.freedesktop.org/show_bug.cgi?id=60359

Also, udisks2 sometimes gets out of sync and shows RAIDs that don't exist anymore at all, and will disappear from udisk2 after a restart of it.

Maybe there are other things...

**Comment by mvollmer** [comment]
This is too vague, and there have been improvements.
