### ISSUE TITLE
'Domain is not supported' warning is unnecessarily scary

### ISSUE THREAD

**Issue by AdamWill** [cockpit-project/cockpit#4301]
If you try to enrol in a FreeIPA domain without the necessary packages installed, Cockpit shows a pretty scary red icon and a 'Domain is not supported' warning (or similar, I forget the exact text). When in fact if you hit 'Join', it goes ahead and downloads the packages and joins the domain just fine (pace https://bugzilla.redhat.com/show_bug.cgi?id=1330766 ).

Couldn't this be a much less scary 'domain requires extra packages for enrolment, don't worry, we'll do it for you!' or something message?

**Comment by stefwalter** [comment]
Well there are domains that are actually not supported. So there must be a bug here. Could you run ```realm discover --verbose <domain>``` against the same domain?

**Comment by stefwalter** [comment]
Haven't received a response back from reporter. Closing the bug.

**Comment by AdamWill** [comment]
sorry, never got enough round tuits. i'll re-open if i remember.
