### ISSUE TITLE
User API is confusing

### ISSUE THREAD

**Issue by larsu** [cockpit-project/cockpit#4306]
There's a changed signal which conflates availability of user information and changes in properties of the user. It's hard to differentiate between the two in client code and quite a few call sites only care about the user object being there, not about further changes. Could we split those two use cases up? I imagine something like:

```js
cockpit.getUser(function (user) {});
```

This will alleviate that awkward `cockpit.user.user` check before connecting to `changed` (thanks @dperpeet for making me aware of this) and makes it harder for client code to do the wrong thing.

Also, it's not clear which properties can change. Surely `id` and `user` never change. Can `home` and `shell` change while logged in?

I also would like to suggest changing `user.user`. Maybe `name` and `displayName`?

Sorry if this stomps over any API guarantees we have.

**Comment by stefwalter** [comment]
> Sorry if this stomps over any API guarantees we have.

None yet. I agree this is worth changing if we can get it right. Do you have an idea of how to have code track this in a more reliable way?

**Comment by larsu** [comment]
> None yet. I agree this is worth changing if we can get it right. Do you have an idea of how to have code track this in a more reliable way?

Sorry, do you mean test API stability or track the user object?

**Comment by stefwalter** [comment]
API stability is not completely frozen. So we can make changes as long as they have real wins. Tracking the user object is a problem, and I agree it doesn't change. We're basically waiting for it to load. Would using a promise here be more helpful?
