### ISSUE TITLE
SElinux troubleshoot: error state suggests faulty install

### ISSUE THREAD

**Issue by larsu** [cockpit-project/cockpit#4324]
When `setroubleshoot` is not installed, the troubleshoot page displays error message "Couldn't connect to SETroubleshoot daemon" with an exclamation mark icon. This makes the default install of cockpit look faulty or incomplete.

It is also not very helpful for people who don't the name of the `setroubleshoot` package.

I can imagine a couple of possible solutions:

1. make cockpit depend on `setroubleshoot`
2.  remove the page entirely when the name is not on D-Bus
3. display a more meaningful message, like "SELinux troubleshooting is disabled. You can enable it by `$POSSIBLE_SOLUTION`"

**Comment by stefwalter** [comment]
This can use a standard class="curtains blank-state-pf" as we see elsewhere in Cockpit. @lars Do you think it's worth bringing that out into a pattern?

**Comment by larsu** [comment]
> @lars Do you think it's worth bringing that out into a pattern?

Yes, of course.

**Comment by dperpeet** [comment]
Note: it needs `setroubleshoot-server`, not all the gui stuff

This is a general problem. I don't think we should force the user to install all the stuff that Cockpit supports. But if the subpackage depends on `setroubleshoot-server`, then we shouldn't install the subpackage by default. And if we don't have that, Cockpit isn't discoverable anymore...

I agree that the message could be more helpful, that would be an interim measure. In the long run, we want to integrate this with an install mechanism.

**Comment by dperpeet** [comment]
> This can use a standard class="curtains blank-state-pf" as we see elsewhere in Cockpit. @lars Do you think it's worth bringing that out into a pattern?

It uses the EmptyState pattern already, similar to the docker page one.

**Comment by dperpeet** [comment]
As @stefw rightly pointed out, the subpackage already has the correct dependencies: https://github.com/cockpit-project/cockpit/blob/b1027fc7e1711c98dd45bd348b4c5849734cc8bf/tools/cockpit.spec#L433
If you install it properly, it'll work. You only see the issue because you compiled from source without installing dependencies.

**Comment by larsu** [comment]
Ha, so it was a faulty install. Sorry for the noise.

I've updated the Vagrantfile to install all cockpit packages in #4328.

Leaving this open for @dperpeet to make the message a bit clearer.
