### ISSUE TITLE
Can't install Cockpit on Ubuntu Trusty

### ISSUE THREAD

**Issue by gloterman** [cockpit-project/cockpit#4329]
Hi,

I can't install Cockpit by the ppa repo indicatd on the website.
` sudo add-apt-repository ppa:cockpit-project/cockpit
`
`
 sudo apt-get update
`
`
 sudo apt-get install cockpit
` 

Durant the apt-get update I'm faced to this error :

`100% [Working]W: Failed to fetch http://ppa.launchpad.net/cockpit-project/cockpit/ubuntu/dists/trusty/main/binary-amd64/Packages: 404  Not Found`

My OS version :
VERSION="14.04.3 LTS, Trusty Tahr"

Is appear cockpit is not compatible with older Ubuntu LTS than the latest Xenial.
It is expected that Cockpit become compatible with Trusty?

**Comment by stefwalter** [comment]
Cockpit doesn't currently work without systemd and the APIs that it provides to configure the system. It's theoretically possible to make it work with significant effort. That's noted here:

https://github.com/cockpit-project/cockpit/wiki/Ideas

And some of the possible work is tracked here:

https://trello.com/c/3h8dyPl6/70-build-cockpit-bridge-rhel6

But it's not clear when or who will work on this. Nobody is doing the work right now. So I hope it's okay to close this bug. Unless there is someone who is willing to contribute (in which case I'd be happy to reopen it).
