### ISSUE TITLE
Network: support for team

### ISSUE THREAD

**Issue by hadess** [cockpit-project/cockpit#4330]
To replace the enterprise networking support in GNOME's Network Settings, cockpit is still missing support for "team" networking, as implemented in:
https://git.gnome.org/browse/gnome-control-center/tree/panels/network/net-device-team.c

Bonding support was added in #458
Bridging support was added in #459
VLAN support was added in #1007

**Comment by dperpeet** [comment]
Can you describe where you would think this would be added in cockpit?

@mvollmer Do you know if this is exposed in networkmanager?

**Comment by hadess** [comment]
It is exposed in NetworkManager, and I personally don't care where it's exposed, just not in GNOME's Network Settings panel :)

**Comment by dperpeet** [comment]
@hadess do you have a user story / example case of this?
Then we'll have a better understanding of where to put this. If you want to hack on this, I can help you to get started! Otherwise a mockup or description of where it would go in the current network section of cockpit would help.

**Comment by hadess** [comment]
@dperpeet No. Please talk to @mvollmer or @stefwalter, this has already been discussed internally.

**Comment by vbenes** [comment]
actually, to remove GNOME's Network Settings enterprise features we need far far more to be implemented in Cockpit. We need team (into the same section as bond) but team and bond both need 802.1x, WOL, and DCB functionality for slaves.

**Comment by vbenes** [comment]
I've reported tickets for that: #4389, #4390, #4391

**Comment by hadess** [comment]
FWIW, there's no WOL support in the GNOME Network settings.

**Comment by vbenes** [comment]
There is. At least for bond/team/bridge slaves. Go to CC and create new bond and while adding a slave you can set WOL. C-C is probably just calling a code from nm-connection-editor but you can definitely set it via GUI tools.

**Comment by mvollmer** [comment]
The idea right now, roughly put, is to keep the existing bond UI and just use the "team" driver to implement it.  Plus some legacy support for bonds that use the "bond" driver.

**Comment by mvollmer** [comment]
Done.
