### ISSUE TITLE
SSH Key changed

### ISSUE THREAD

**Issue by somabc** [cockpit-project/cockpit#4333]
I reinstalled one of my hosts. I removed the host and readded it but it warns SSH Key has been changed and will not accept the new host. Where is the SSH Key I need to change?

**Comment by stefwalter** [comment]
Newer versions of cockpit give the command to use. @petervo Do you know when this was fixed?

**Comment by somabc** [comment]
This is Cockpit for CentOS 7.1

**Comment by stefwalter** [comment]
Could you look at the version of Cockpit in the About dialog (menu in the upper right corner). Or run

```
$ rpm -q cockpit
```

**Comment by dperpeet** [comment]
I believe it was fixed in https://github.com/cockpit-project/cockpit/releases/tag/0.100
`Show SSH info when we fail to connect to another machine`
@somabc can you see if you're running a current version?

**Comment by somabc** [comment]
➜  ~ rpm -q cockpit    
cockpit-0.96-2.el7.centos.x86_64

**Comment by dperpeet** [comment]
cockpit will recommend to use `ssh-keygen -R host -f path-to-known-hosts` (e.g. `~/.ssh/known_hosts`)

**Comment by petervo** [comment]
That's not quite right, it's ```/var/lib/cockpit/known_hosts``` if you've installed from packages.

**Comment by petervo** [comment]
This was actually added in 0.85 so you should see the message. What version of cockpit-ws are you running?

**Comment by somabc** [comment]
➜  ~ yum info cockpit
Loaded plugins: etckeeper, fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.hyve.com
 * extras: centos.hyve.com
 * updates: mirrors.vooservers.com
Installed Packages
Name        : cockpit
Arch        : x86_64
Version     : 0.96
Release     : 2.el7.centos
Size        : 36 k
Repo        : installed
From repo   : extras
Summary     : A user interface for Linux servers
URL         : http://cockpit-project.org/
Licence     : LGPLv2+
Description : Cockpit runs in a browser and can manage your network of GNU/Linux
            : machines.

**Comment by petervo** [comment]
Turns out there was a bug that was fixed in 0.99. So you need to update to a newer version. 

In the mean time you can edit the file ```/var/lib/cockpit/known_hosts``` either manually or using ssh-keygen -R
