### ISSUE TITLE
unit test: failing pkg/base1/test-dbus-address.html

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#4363]
This seems to be happening fairly regularly lately.
Example: https://travis-ci.org/cockpit-project/cockpit/jobs/127729480

```
FAIL: pkg/base1/test-dbus-address.html 67 - correct data, expected: {
```

**Comment by stefwalter** [comment]
I don't see that line at that link.

**Comment by theseaofstars** [comment]
I meet the same fail, keep watching.
not ok 70 - correct data, expected: {
#   "FinallyNormalName": "There aint no place like home",
#   "ReadonlyProperty": "blah",
#   "aay": [],
#   "ag": [],
#   "ao": [],
#   "as": [],
#   "ay": "QUJDYWJjAA==",
#   "b": false,
#   "d": 43,
#   "g": "",
#   "i": 0,
#   "n": 0,
#   "o": "/",
#   "q": 0,
#   "s": "",
#   "t": 0,
#   "u": 0,
#   "x": 0,
#   "y": 42
# }, got: {}, test: watch barrier, source: http://localhost:34820/pkg/base1/test-dbus-common.js:566:26
# process_queue@http://localhost:34820/pkg/base1/cockpit.js:1136:42
# http://localhost:34820/pkg/base1/cockpit.js:1150:26
