### ISSUE TITLE
System: clicking "Performance Profile" button often does nothing, and sometimes too much

### ISSUE THREAD

**Issue by larsu** [cockpit-project/cockpit#4364]
Clicking that button restarts the `tuned` unit and cockpit seems to miss the service coming up sometimes. `tuned` probably shouldn't restart on Start(), but that's another bug.

Clicking often can make the dialog appear multiple times.

**Comment by stefwalter** [comment]
> tuned probably shouldn't restart on Start(),

That doesn't happen with ```systemctl start tuned```. Is this a bug in our code?

**Comment by larsu** [comment]
> That doesn't happen with systemctl start tuned. Is this a bug in our code?

Indeed, I confused systemd's `Starting` message with tuned actually restarting. Thanks.

**Comment by larsu** [comment]
The problem is that cockpit.dbus breaks message ordering: subscriptions to signals are called directly when the dbus message arrives, while replies to method calls are scheduled for the next main loop iteration (via a promise). The tuned code listens to systemd's `JobRemoved` signal to figure out when `tuned` has started, but gets the reply from the `StartUnit` call after the `JobRemoved` signal.

Possible fixes:

1. Put signals on the same queue as method replies. Would be a bit weird, because `DBusClient` would need access to the queue of the cockpit.deferred

2. Invoke callbacks directly in Promise.resolve. I don't understand why we're not doing that anyway. The standard JavaScript promises seem to do that, no?   

3. Quick workaround for this case in tuned: remember JobRemoved signals for a while (I really don't like to do this, but if the other stuff needs more discussion, it might be worth to have that button work in the next release). 

Marking as priority because this bug is quite visible.

**Comment by dperpeet** [comment]
fixed in #4368: 5b16b107e79ee73b459a5682ae425d8cddb7dbaf
