### ISSUE TITLE
Apostrophe on the docker page makes github flip out

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#4367]
![screenshot from 2016-05-04 15-49-32](https://cloud.githubusercontent.com/assets/209895/15016115/dbb8da64-120f-11e6-9a26-326b2615cae5.png)

**Comment by stefwalter** [comment]
This is a github bug?

**Comment by andreasn** [comment]
Either that, or we're using the wrong kind of apostrophe.
I can create a pull-request to rename it to "cannot" for now.

Does github have a issue tracker?

**Comment by stefwalter** [comment]
>  I can create a pull-request to rename it to "cannot" for now.

But this doesn't affect Cockpit. If you do want to change this you can use ```&squot;``` instead.

**Comment by andreasn** [comment]
Oh, that's true. I'll do that.
