### ISSUE TITLE
Selinux with confined users

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#4369]
grift on IRC brought up some issues with cockpit-bridge when running with confined users. Specifically he was concerned that when cockpit opens the terminal, the shell should transition to the shell domain rather than continue in whatever domain was setup for cockpit-bridge. 

I haven't actually run cockpit with a confined user yet, obviously running it like this requires some work to setup a custom policy but I'm opening this ticket to see if there is anything we can or should do different to better support systems where user are confined and the admin has gone through the trouble of setting up a custom policy for cockpit-bridge.

**Comment by doverride** [comment]
I was the person mentioning this on irc. My users have restricted shells. I do not want them to be able to escalate their shell permissions via the cockpit terminal. The cockpit terminal has the permissions that are associated with cockpit-bridge. These include permissions to dbus chat with various system services, tcp connect to ephemeral ports and other things that these users would'nt be able to do directly from a shell.

SELinux can be used to transition from one set of permissions to another transparently but then the terminal would have to be "executed" by cockpit-bridge. Instead it seems that cockpit bridge interprets some java script so there is no way for me to tell selinux: when a process associated with the joe_cockpitbridge_t type runs a file with the shell_exec_t type then process type transition from the joe_cockpitbridge_t type to the joe_shell_t type.

This is only an issue if you want to be able to associate different sets of permissions with cockpit bridge and the terminal is presents in the web front-end.

**Comment by doverride** [comment]
I was wrong, please close this. I can (most likely) make this happen after all as-is
I will try that out and will keep you posted.

cockpit bridge actually does run /bin/bash so i can make it transition back to the login shell domain there. I can do the same for ssh-agent.

So then the shell and ssh-agent run with exactly the same properties as if they were run by a normal shell

**Comment by stefwalter** [comment]
Good to hear. Closing.
