### ISSUE TITLE
add DCB functionality for ethernet devices and team/bond slaves

### ISSUE THREAD

**Issue by vbenes** [cockpit-project/cockpit#4389]
for full team/bond support we need to implement DCB functionality to allow traffic shaping on slaves (and basically all ethernet devices). This is already implemented in NM and can be seen in nm-connection-editor (or GNOME's control-center). 
We need FCoE, iSCSI, FIP Flow Controls and Priority Groups settings.

**Comment by vbenes** [comment]
bridge slaves should have been included too

**Comment by marusak** [comment]
This issue is closed due to inactivity.

We are sorry, but we won't be able to address this in any time soon.
If you are interested in helping us with the implementation, please comment here.
