### ISSUE TITLE
add 802.1x security

### ISSUE THREAD

**Issue by vbenes** [cockpit-project/cockpit#4391]
we need to implement 802.1x security for ethernet and bond/team/bridge slaves. This is pretty crucial..

in nm-connection-editor we support MD5, TLS, TTLS (with ton of inner auth protocols), PEAP (at least GTC, MSCHAP2, and MD5 based authentication), FAST and password based (w/o md5) login.

**Comment by voxadam** [comment]
This is absolutely needed but I'm also wondering how closely this should be integrated with FreeIPA.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

We are sorry, but we won't be able to address this in any time soon.
If you are interested in helping us with the implementation, please comment here.
