### ISSUE TITLE
error in vm-create from source package

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#4398]
@larsu We talked about this: a [commit](https://github.com/cockpit-project/cockpit/commit/b3b6fe838937251175f0cdebe84e44c4baf0eca4#diff-fcc3d5821f233d4abde0ece1822faa4bR43) introduced behavior that seems to break using vm-create from a source tarball.

When @jscotka tried to use `vm-create`, `tools/make-source` failed with

```
make: *** No rule to make target `dist-gzip'.  Stop.
```

**Comment by jscotka** [comment]
In that case there were some strange Makefile (in testing env) when I've done it on clean env:
    $ TEST_OS=rhel-7 BOOTSTRAP_VOLUME_SIZE=15G ./vm-create -v 2>&1 | egrep -v '[0-9]+\.[0-9]%$'
    + '[' 3 -lt 3 ']'
    + subscription_args=
    + '[' 3 -gt 3 ']'
    ++ dirname /home/test/cockpit/test/images/scripts/virt-builder-fedora
    + BASE=/home/test/cockpit/test/images/scripts
    + out=/home/test/cockpit/test/tmp/run/rhel-7.qcow2
    + os=rhel-7.2
    + arch=x86_64
    + test -z 15G
    + '[' '' == yes ']'
    + virt-builder rhel-7.2 --output /home/test/cockpit/test/tmp/run/rhel-7.qcow2 --size 15G --format qcow2     --arch x86_64 --root-password password:foobar --mkdir /root/.ssh --chmod 0700:/root/.ssh --upload     /home/test/cockpit/test/images/scripts/../../common/identity.pub:/root/.ssh/authorized_keys --chmod 0600:/root/.ssh/authorized_keys --run-command 'chown root:root /root/.ssh/authorized_keys' --upload /home/test/cockpit/test/images/scripts/host_key:/etc/ssh/ssh_host_rsa_key --chmod 0600:/etc/ssh/ssh_host_rsa_key --upload /home/test/cockpit/test/images/scripts/host_key.pub:/etc/ssh/ssh_host_rsa_key.pub --upload /home/test/cockpit/test/images/scripts/fedora-network-ifcfg:/etc/sysconfig/network-scripts/ifcfg-eth0 --delete /etc/systemd/system/multi-user.target.wants/sshd.service --mkdir /etc/systemd/system/sockets.target.wants --link /usr/lib/systemd/system/sshd.socket:/etc/systemd/system    /sockets.target.wants --selinux-relabel
    gpg: Signature made Thu 21 Apr 2016 08:41:27 AM EDT using RSA key ID E1B768A0
    gpg: Good signature from "Richard W.M. Jones <rjones@redhat.com>"
    gpg:                 aka "Richard W.M. Jones <rich@annexia.org>"
    gpg: WARNING: This key is not certified with a trusted signature!
    gpg:          There is no indication that the signature belongs to the owner.
    Primary key fingerprint: F777 4FB1 AD07 4A7E 8C87  67EA 9173 8F73 E1B7 68A0
    [   3.0] Downloading: http://ibm-x3650-04.ovirt.rhts.eng.bos.redhat.com/rhel-7.2.xz
    [   6.0] Planning how to build this image
    [   6.0] Uncompressing
    [  77.0] Resizing (using virt-resize) to expand the disk to 15.0G
    [ 169.0] Opening the new disk
    [ 175.0] Setting a random seed
    [ 175.0] Making directory: /root/.ssh
    [ 175.0] Changing permissions of /root/.ssh to 0700
    [ 175.0] Uploading: /home/test/cockpit/test/images/scripts/../../common/identity.pub to /root/.ssh    /authorized_keys
    [ 175.0] Changing permissions of /root/.ssh/authorized_keys to 0600
    [ 175.0] Running: chown root:root /root/.ssh/authorized_keys
    [ 175.0] Uploading: /home/test/cockpit/test/images/scripts/host_key to /etc/ssh/ssh_host_rsa_key
    [ 175.0] Changing permissions of /etc/ssh/ssh_host_rsa_key to 0600
    [ 175.0] Uploading: /home/test/cockpit/test/images/scripts/host_key.pub to /etc/ssh    /ssh_host_rsa_key.pub
    [ 175.0] Uploading: /home/test/cockpit/test/images/scripts/fedora-network-ifcfg to /etc/sysconfig/network-scripts/ifcfg-eth0
    [ 175.0] Deleting: /etc/systemd/system/multi-user.target.wants/sshd.service
    [ 175.0] Making directory: /etc/systemd/system/sockets.target.wants
    [ 175.0] Linking: /etc/systemd/system/sockets.target.wants -> /usr/lib/systemd/system/sshd.socket
    [ 175.0] Setting passwords
    [ 177.0] SELinux relabelling
    [ 177.0] Finishing off
                       Output file: /home/test/cockpit/test/tmp/run/rhel-7.qcow2
                       Output size: 15.0G
                     Output format: qcow2
                Total usable space: 12.6G
                        Free space: 11.6G (92%)
    ../tools/make-source: line 36: ../autogen.sh: No such file or directory
    Running setup script /home/test/cockpit/test/images/scripts/rhel-7.setup
    Traceback (most recent call last):
      File "./vm-create", line 184, in <module>
        builder.build()
      File "./vm-create", line 126, in build
        source = subprocess.check_output([ "../tools/make-source" ]).strip()
      File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
        subprocess.CalledProcessError: Command '['../tools/make-source']' returned non-zero exit status 1

**Comment by jscotka** [comment]
It calls line:       (cd tmp-dist && NOREDIRECTMAKEFILE=t ../autogen.sh) 1>&2
and autogen.sh is not packed in rpm

**Comment by jscotka** [comment]
after I called ./configure then makefile was created, but there happen another issue:
Running setup script /home/test/cockpit/test/images/scripts/rhel-7.setup
/home/test/cockpit/tools/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
on rhel7.2 there is: 
automake-1.13.4-3.el7.noarch
autoconf-2.69-11.el7.noarch
