### ISSUE TITLE
Registry: display user who created project

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#4408]
Sometimes it's nice to be able to see who created a project so we know who the "owner" is. Use cases:
1. As a registry admin I have a question for the project owner. This may be due to high usage or some other concern.
2. As a registry user I want to be able to contact a project owner to request edit or admin access.

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
