### ISSUE TITLE
unable to modify the ui

### ISSUE THREAD

**Issue by theseaofstars** [cockpit-project/cockpit#4411]
I modify the /docker/run.js and /docker/index.html to add some interesting function on the create_container_dialog. After using "ln -s $(pwd)/pkg/\* ~/.local/share/cockpit", I could see the changes i made appears, while after removing ~/.local/share/cockpit/\* and using "
$ make
$ sudo make install
$ sudo systemctl restart cockpit" .
The changes i made seems to be disappeared. and i can not find file run.min.js.gz which contains the changes i made
I need your help, thanks

**Comment by dperpeet** [comment]
Hi! Thanks for contributing.

Two questions:
- Did you build from a git checkout? The steps are here: https://github.com/cockpit-project/cockpit/blob/master/HACKING.md#building-and-installing-from-source
- Second, can you post changes in a pull request? I'm currently reworking the docker run dialog in https://github.com/cockpit-project/cockpit/pull/4405

**Comment by stefwalter** [comment]
Haven't received a response back from reporter. Closing the bug.
