### ISSUE TITLE
Shell CSP Errors

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#4421]
Got a report on IRC of the shell not loading due to CSP errors. Restoring the old manifest with 

```
"content-security-policy": "default-src 'self' 'unsafe-inline' 'unsafe-eval'"
```

made it work again.

**Comment by petervo** [comment]
This was with firefox: 46.0.1.

**Comment by mulkieran** [comment]
Running Cockpit master, last commit: b6d2dca23b82b6bd1559f5dd745a2c8b5bb6ea35.

**Comment by mulkieran** [comment]
Also on firefox: 38.4.0 (RHEL7 CSB).

**Comment by stefwalter** [comment]
@mulkieran Which manifest file did you restore?

**Comment by petervo** [comment]
It was the shell. pkg/shell/manifest.json

**Comment by stefwalter** [comment]
@dperpeet Can you replicate this with CSB?

**Comment by stefwalter** [comment]
Never mind. I can duplicate it here. it's the legend graphs.

**Comment by petervo** [comment]
@mulkieran, we fixed the flot issue on the graphs, but feel free to reopen if this hasn't resolved the issue.
