### ISSUE TITLE
update-lib fails

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#4442]
For me, update-lib fails due to missing patternfly css:
```
sed -f ../cockpit/tools/patternfly.sed \
	../cockpit/bower_components/patternfly/dist/css/patternfly.css > ../cockpit/pkg/base1/patternfly.css
sed: can't read ../cockpit/bower_components/patternfly/dist/css/patternfly.css: No such file or directory
Makefile:9469: recipe for target 'update-lib' failed
```
In my `bower_components/patternfly/dist` directory there is only one child entry: `fonts` (no `css`).

**Comment by petervo** [comment]
are you seeing messages like 

```
patternfly was not installed because there is already a non-bower directory with that name in the components directory (bower_components/patternfly). You can force installation with --force.
```

If you you can just erase the patternfly dir and run again, not sure why it thinks it's not a bower directory

**Comment by dperpeet** [comment]
I didn't see that message, but cleaning out the bower_components dir helped. Thanks!
