### ISSUE TITLE
Mouse cursor should indicate clickable area when standing on host icon

### ISSUE THREAD

**Issue by abonas** [cockpit-project/cockpit#445]
In "Manage" UI there's a nice option to change a server's icon.
However it is very unclear that the icon can be changed, because it's revealed only when clicking the current icon. 
Since the mouse cursor doesn't turn into a hand palm, and there's no tooltip either,
there is no indication of the fact that it's clickable, so probably most of the users will be unaware of the feature.

![icon](https://cloud.githubusercontent.com/assets/6277245/2644865/b2bf8636-bf2c-11e3-87e4-95bf274fd8a1.png)

**Comment by stefwalter** [comment]
This avatar is no longer displayed there. Closing.
