### ISSUE TITLE
Confusing state of ON/OFF widget

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#4462]
As we were working on a SELinux detail that included a ON/OFF widget, @dperpeet pointed out it was a bit hard to tell what state the widget was currently in.
![screenshot from 2016-05-23 17-05-47](https://cloud.githubusercontent.com/assets/209895/15475197/2eb9d760-2109-11e6-9e8e-7101fc03699b.png)

The bootstrap switch used by patternfly shows only the current state, and it's ON state look very active in difference with it's off state, that has a more disabled look to it.
The ON/OFF switches in GNOME works in a similar fashion.

https://www.patternfly.org/widgets/#bootstrap-switch

**Comment by stefwalter** [comment]
Good point, but need to do better than just using bootstrap-switch. Using the standard btngroup plus additional styling CSS allows us to use it in jQuery, React, or Angular. so I would suggest changing the styling of the existing component, and using CSS animation.
