### ISSUE TITLE
docker: volume support and enviroment variables when starting containers

### ISSUE THREAD

**Issue by vanloswang** [cockpit-project/cockpit#4506]
There are no -v to mount volume and no -e to claim an enviroment value in cockpit-docker UI? I cannot run docker container in cockpit-docker UI like mariadb with following cmdline:

# docker run --name some-mariadb -v /my/custom:/etc/mysql/conf.d -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mariadb:latest

So how to handle this? maybe we can add some object like Ports to complete this ?

**Comment by FireDrunk** [comment]
I would also very much appreciate this! Good example is the Gogs (Go Git Service) Docker image file, which requires a -v to be able to get the GIT data repositories outside of the container.

**Comment by hyperbart** [comment]
+1

**Comment by dperpeet** [comment]
It would be nice to have both of these, I agree.

Docker volume support is on the roadmap (no associated timeline, though) https://trello.com/c/4juwxCaE/94-docker-volume-support and in #1451.

Environment variables are a different matter, I couldn't find any plans or research in Cockpit on that topic.
@vanloswang @hyperbart Would you like to contribute? Aside from pull requests, I think this is enough to warrant some scoping, maybe a mock-up and/or checking out the Docker REST API to see what we can glean from there. For example: Can images tell us about environment variables they expect?

**Comment by dperpeet** [comment]
@larsu Would this greatly conflict with your work in progress on overhauling the docker page? Did you start something in this direction already?

**Comment by larsu** [comment]
> @larsu Would this greatly conflict with your work in progress on overhauling the docker page? Did you start something in this direction already?

I think so, yes. I haven't made much progress, but the design of the docker page changed quite substantially.

**Comment by vanloswang** [comment]
@dperpeet @larsu  What is the matter for this direction recently?  Now I have some time to contribute to it.

**Comment by vanloswang** [comment]
![image](https://cloud.githubusercontent.com/assets/1133578/16722735/339e4372-477b-11e6-8f83-e3a429e1014a.png)

**Comment by stefwalter** [comment]
@vanloswang The UI design looks good.

**Comment by vanloswang** [comment]
close here and go to https://github.com/cockpit-project/cockpit/pull/4726
