### ISSUE TITLE
SELinux: "enforced security mode" might be hard for newcomers to understand

### ISSUE THREAD

**Issue by larskarlitski** [cockpit-project/cockpit#4509]
The current [design](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/selinux-troubleshooting/selinux-v5.png) uses a switch with the label "Enforced security mode" to change SELinux mode. I think that's quite vague and hard to understand for people new to SELinux.

How about something more elaborate, like:

Enforce SELinux policy
If disabled, actions that would be denied will only be logged to $WHEREVER".

**Comment by doverride** [comment]
Maybe:
```
In enforcing mode events are prevented based on SELinux security policy. Otherwise events are detected.
```

**Comment by stefwalter** [comment]
Agree. This looks very confusing as designed right now.

**Comment by andreasn** [comment]
This is what the documentation says:
_Enforcing: SELinux policy is enforced. SELinux denies access based on SELinux policy rules. 
Permissive: SELinux policy is not enforced. SELinux does not deny access, but denials are logged for actions that would have been denied if running in enforcing mode._ 

So what if we have text in the popup:
_If turned ON: SELinux denies access is based on SELinux policy rules.

If turned OFF: SELinux does not deny access, but denials are logged for actions that would have been denied if running in enforcing mode._

OR

_If turned ON: Access is denied based on SELinux policy rules.

If turned OFF: Access is not denied, but denials are logged for actions that would have been denied if running in enforcing mode._

The latter makes it less about SELinux the component, and more about the system doing it, with SELinux as the tool.

**Comment by davidmalcolm** [comment]
The use of "On" or "Off" to mean "Enforcing" or "Permissive" could be confusing.

As I understand it, internally, SELinux is a tri-state:

1.  On and Enforcing  (labels are written and read, and access granted accordingly); normally called "enforcing".
2.  On and Permissive (labels are written and read, problems are merely logged); normally called "permissive".
3.  Off (labels aren't written or read); normally called "off".

Turning SELinux to state 3 means disabling labelling; turning it back from state 3 to states 1 or 2 means a time-consuming relabelling, so it's generally a bad idea to turn SELinux to state 3, better to turn it from state 1 to state 2.

The proposed UI seems to transitions between states 1 and 2 (which is good), but using the terms "on" and "off" for states 1 and 2 is likely to be confusing when using non-cockpit UI and docs.

**Comment by andreasn** [comment]
The logic I used was from the setenforce command, that can be either 1 or 0.
https://fedoraproject.org/wiki/SELinux/setenforce
There is currently no way to disable SELinux from Cockpit, so we don't have the third state.
Another reason for choosing the On/Off widget is that it can express the ideal state (Enforcing/On). Kind of like "I will lower my shields temporarily to get this thing working, then I will raise them again."

We could include some text about the Enforcing/Permissive in the help popup like this:
> If turned ON: Enforced. Access is denied based on SELinux policy rules.
> If turned OFF: Permissive. Access is not denied, but denials are logged for actions that would have been denied if running in enforcing mode.

**Comment by marusak** [comment]
Currently we have on-off switch, but we show 'Enforcing' and 'Permissive' next to it:
![currentselinux](https://user-images.githubusercontent.com/12330670/73827969-c45f4800-4800-11ea-9354-c04b33a43b64.png)
I think this is clear and uses the same terminology as selinux (so no 'on' to represent 'enforcing...)
