### ISSUE TITLE
Terminal does not display command prompt or command line input for fish shell

### ISSUE THREAD

**Issue by terrycloth** [cockpit-project/cockpit#4523]
When I log in to the Cockpit web interface, it does not show the command prompt or command line input when using fish as my shell. This means I have to type commands blind and hope for the best. The following screenshot shows me running `dnf info cockpit`, but you cannot see the actual command line.

![screenshot from 2016-05-31 22-18-50](https://cloud.githubusercontent.com/assets/3881885/15698050/b932e10a-277d-11e6-9158-092269a8c19e.png)

I'm running Cockpit 0.108 on Fedora 24 Beta Server Edition in a virtual machine. My desktop is running Fedora 23 Workstation (64-bit). bash and zsh seem to work as they should, but I like fish. Let me know if you need any other information.

**Comment by larsu** [comment]
Indeed.

There seems to be something different in the environment which causes fish to not emit the prompt. Alas, I can't see anything obvious when running fish in debug mode.

**Comment by mvollmer** [comment]
I am looking at this a bit.

**Comment by mvollmer** [comment]
This is a quick fix: https://github.com/mvollmer/cockpit/commit/e39343c3117ad73262eef32d6fc97a34cbe46a70

I am not sure whether we should release that quick fix or go the whole distance and make the terminal actually resizable...

**Comment by stefwalter** [comment]
Awesome research @mvollmer ... I would suggest getting this fix in first, and we can follow up by fixing #2001

**Comment by mvollmer** [comment]
> make the terminal actually resizable...

I mean, let the terminal fill the browser window and resize it with the browser window, not put a resize handle on it or something like that.

**Comment by mvollmer** [comment]
> I would suggest getting this fix in first

Yep, #4537
