### ISSUE TITLE
Increase portability

### ISSUE THREAD

**Issue by lrusak** [cockpit-project/cockpit#4542]
Currently as it sits cockpit requires various build time dependencies that aren't needed during run time.

`kubernets (krb5)` and `PAM` are are the big ones here. PAM can be mitigated at runtime by launching `cockpit-ws` with the `--local-ssh` option.

It would be nice to be able to disable these build time dependencies.

I'm asking because I have started a cockpit add-on for LibreELEC (because we have a docker add-on also). All the dependencies are built statically but it would be nice to not have to build them at all.

see, https://github.com/lrusak/LibreELEC.tv/commits/cockpit
and specifically https://github.com/lrusak/LibreELEC.tv/blob/cockpit/packages/addons/service/cockpit/package.mk

**Comment by dperpeet** [comment]
Great that you find Cockpit useful for this!

PAM and kerberos dev-packages are definitely needed for the build right now. An example of where the PAM code is actually used: https://github.com/cockpit-project/cockpit/blob/8256580c76c54a20faf673c54a79bacada152c18/src/ws/session.c

Any contributions to reducing build requirements are welcome. Would you be willing to give this a go? I'd be happy to look at pull requests.

**Comment by dperpeet** [comment]
Note that kerberos authentication and PAM are linked into Cockpit in several places, so this might not be a trivial change.

**Comment by stefwalter** [comment]
Haven't received a response back from reporter. Closing the bug.
