### ISSUE TITLE
Storage sometimes doesn't show correct filesystem usage during test

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#4574]
```
# testMounting (check_storage_mounting.TestStorage)
#
Wrote TestStorage-testMounting-FAIL.png
Journal extracted to TestStorage-testMounting-10.111.122.151-FAIL.log
not ok 92 testMounting (check_storage_mounting.TestStorage)
Traceback (most recent call last):
  File "./verify/check-storage-mounting", line 97, in testMounting
    wait_ratio_in_range(bar_selector, 0.5, 1.0)
  File "./verify/check-storage-mounting", line 90, in wait_ratio_in_range
    })""", sel, low, high)
  File "/build/cockpit/test/common/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 660, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 683, in _invoke
    raise Error(res['error'])
Error: timeout
```

I couldn't reproduce this locally, not even with lots of load on the machine. I have retriggered the test, and now this one has passed.

One theory is that the m.execute("dd ...") takes a really long time and that this somehow causes the browser to lose contact with the bridge. The bridge keeps running during m.execute, but the browser is stopped and doesn't read from the websocket, for example.

**Comment by stefwalter** [comment]
> One theory is that the m.execute("dd ...") takes a really long time and that this somehow causes the browser to lose contact with the bridge. The bridge keeps running during m.execute, but the browser is stopped and doesn't read from the websocket, for example. 

Should we check for ping responses in the CockpitWebService code? We currently do it in the frontend, but not in the web service. That would help us narrow this down.

**Comment by mvollmer** [comment]
Another theory is that something goes wrong with the metric interpolation.  Maybe the bridge itself isn't running "real-timey" enough.

**Comment by stefwalter** [comment]
What value is actually being shown in the UI at the point of failure?

If this theory is correct, couldn't we just increase the wait timeouts for this test? And/or perhaps run the dd in the background with ```m.spawn()```

**Comment by dperpeet** [comment]
Using `spawn` didn't seem to help. There has to be a different issue.

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-mounting", line 97, in testMounting
    wait_ratio_in_range(bar_selector, 0.5, 1.0)
  File "check-storage-mounting", line 90, in wait_ratio_in_range
    })""", sel, low, high)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 664, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 687, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-06-27T11:00:15.310117 | revision e25fbaefefe34569d1c2de534709843566b021ea, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4568-e25fbaef-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-06-27T11:00:15.310117 | revision e25fbaefefe34569d1c2de534709843566b021ea, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4568-e25fbaef-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/debian-unstable
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-mounting", line 97, in testMounting
    wait_ratio_in_range(bar_selector, 0.5, 1.0)
  File "check-storage-mounting", line 90, in wait_ratio_in_range
    })""", sel, low, high)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 664, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 687, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-06-29T07:57:36.908825 | revision e25fbaefefe34569d1c2de534709843566b021ea, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4568-e25fbaef-verify-debian-unstable/log.html)
Times recorded: 1
Latest occurrences:

- 2016-06-29T07:57:36.908825 | revision e25fbaefefe34569d1c2de534709843566b021ea, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4568-e25fbaef-verify-debian-unstable/log.html)

**Comment by stefwalter** [comment]
@mvollmer So is this a known issue without an upstream bug?

**Comment by mvollmer** [comment]
> So is this a known issue without an upstream bug?

Yes.  It's very likely a bug in Cockpit.

**Comment by stefwalter** [comment]
@mvollmer This hasn't happened in months. Is it fixed?

**Comment by mvollmer** [comment]
> Is it fixed?

Not consciously...
