### ISSUE TITLE
Formatting a small partition fails without message

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#4576]
When formatting a small partition, no message is shown, but the format doesn't succeed. The failure message should be displayed clearly. Either in the format dialog, or in the drive's screen as an alert.

**Comment by stefwalter** [comment]
{{{
# dd if=/dev/zero of=/fs2 bs=1024 count=10240
# losetup /dev/loop1 /fs2
}}}

Now click on the /dev/loop1 in the UI.

**Comment by mvollmer** [comment]
I added this to the "Storage Polish" card, https://trello.com/c/hqj8oZdu/273-storage-polish

The current plan is to make asynchronous errors appear at least in the journal.

Additionally, I think we should prevent people from formatting a disk when we know that this is going to fail.
