### ISSUE TITLE
Add configurable docs link to upper-right menu

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#4587]
In registry mode I would like to have configurable link to documentation appear in the menu, either as a separate link or in the about screen. Link configuration should have a sane default, overridden by environment variable.

**Comment by aweiteka** [comment]
@stefwalter do we have any hooks to customize the about menu? If so, any pointers to contrib docs and I can take a look.

**Comment by stefwalter** [comment]
@petervo Do you have ideas for how to bring a pluggable docs link into the upper right menu?

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
