### ISSUE TITLE
Display kubernetes cluster version in About menu

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#4588]
It is very useful to have the cockpit version displayed in the upper-right About menu. As a remote user when connected to a kubernetes cluster this may be my only interface to the cluster, without knowledge or access to CLI tools. I would like the kubernetes version displayed.

**Comment by aweiteka** [comment]
@stefwalter @petervo is this possible? Do we already have hooks in cockpit kube for this type of thing?

**Comment by stefwalter** [comment]
Similar question to #4587

**Comment by aweiteka** [comment]
#4587 is static content. This is a request for a dynamic call. I haven't found an API call to discover this. :(

**Comment by stefwalter** [comment]
Yup, this is a good point. I wonder if this should go into branding.

**Comment by aweiteka** [comment]
> I wonder if this should go into branding.

Yes, I wasn't clear how this was wired in but that sounds right. I can imagine some deployments require a custom link so ideally it's an env var.

**Comment by aweiteka** [comment]
With #4865 I'm satisfied this is discoverable.
