### ISSUE TITLE
The form-inline style collapses in most modals

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#4593]
If you have a screen that's zoomed in, and either the Docker run or NTP modal is displayed, you'll see a mess in the NTP Servers, Link, or Expose sections of these dialogs:

![screenshot from 2016-06-18 17-55-07](https://cloud.githubusercontent.com/assets/795070/16171990/54cc9526-357e-11e6-8b72-70ebbad8fbb6.png)

This is because `.form-inline` doesn't display as expected if the view is less than 768px wide. As documented in bootstrap. We either need to override this or use a different style.

@andreasn What do you think we should do?

**Comment by andreasn** [comment]
I'll take a look

**Comment by martinpitt** [comment]
This should work much better now with ct-form-layout, which has been designed and tested on narrow mobile views, too.
