### ISSUE TITLE
Integration tests for Docker

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#461]

**Comment by stefwalter** [comment]
We now have one or two tests for docker, but certainly not proper coverage.

**Comment by stefwalter** [comment]
Here's how to run the tests:

https://github.com/cockpit-project/cockpit/blob/master/test/README

The test being modified would be check-docker

https://github.com/cockpit-project/cockpit/blob/master/test/check-docker

We need to have an integration test the for at least the following features:

 * Commit a container to an image
 * Search/pull
 * Restart a container.

**Comment by martinpitt** [comment]
Our check-docker is actually quite comprehensive now, so let's close this.
