### ISSUE TITLE
"bower_components" folder is being stored in repository

### ISSUE THREAD

**Issue by ecarlisle** [cockpit-project/cockpit#4620]
Hi!
I'm uncertain why the bower_components" folder is being stored in source control. There is a bower.json in the project root with the respective dependencies listed. Shouldn't the user download these packages upon downloading the project?

I see there is an [npm_modules](https://github.com/cockpit-project/cockpit/tree/master/node_modules) folder also, but for documentation purposes (which is great!). Should the [bower_components](https://github.com/cockpit-project/cockpit/tree/master/bower_components) folder also be empty except for a readme similar to the one in the node_modules folder?

Thanks!

**Comment by stefwalter** [comment]
The intent was that people could hack on Cockpit components especially for quick fixes without needing to use bower or similar nodejs tooling. You'll note there are symlinks pointing into the bower_components directory from other places in Cockpit.

However that situation is changing and @larsu is reworking the build system. Some of the Cockpit packages have transitioned away from this. You've caught us with our pants down ... while changing the pants. The refactoring of the build stuff is taking a while. Once it's done, we can probably remove the stuff in the bower_components directory and have it populated when the user clones the repo.

**Comment by ecarlisle** [comment]
Cool, that makes a lot of sense, especially with saving time to make small tweaks. What kind of build build approach is @larsu taking? I see some front-end asset management happening in [Makefile.am](https://github.com/cockpit-project/cockpit/blob/master/Makefile.am). I'm curious if the Cockpit team is considering solutions like Gulp, Grunt, or NPM scripts for asset assembly, optimization, and/or watchers.

Thanks!

**Comment by stefwalter** [comment]
Starting with webpack. I believe it has a watcher. For most components that should be simple enough, and obviously with the option to have a more involved build step for a given component.

**Comment by ecarlisle** [comment]
Sounds great! Thanks, I really appreciate the info!
