### ISSUE TITLE
Unable to login to cloud hosted instances

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [cockpit-project/cockpit#4643]
I'm running machine on AWS, which doesn't have any user, all connection made with ssh file key. How can I login to the cockpit web application without creating new user?

**Comment by ykorman** [comment]
It might not sound serious but this makes cockpit unusable in most cloud environments...

**Comment by stefwalter** [comment]
Sorry missed this the first time it came around. You log in like this: http://cockpit-project.org/guide/latest/authentication.html

Here's one of several videos describing this: https://www.youtube.com/watch?v=RZ_N2iCPm_U

**Comment by ykorman** [comment]
Hmm... that's not what we mean, we mean that if we don't have a password (only an SSH key) for our primary server, we can't login to cockpit UI.
Even if I customize the PAM configuration, it will still require a password...

Personally my use case is simple - show a customer the cockpit UI:
Tell a customer to spin up an instance in <insert-cloud-provider-here>, connect, install cockpit and login to the UI.
But I can't, I need to also add a step of manually adding a local user+password for this setup.

**Comment by stefwalter** [comment]
>  But I can't, I need to also add a step of manually adding a local user+password for this setup.

Web browsers cannot do SSH key authentication. So as outlined above, you have several options here:

 a) Add a user/password to the cloud instance.
 b) Proxy all access to the cloud instance through another hosted machine. As described in the video above.

Or do you have another idea of how you might choose to solve this?

**Comment by ykorman** [comment]
Sorry for taking a while to reply, had to think about this a bit.
Thanks for providing options, but for security reasons, they're not always possible.

I had an idea of how we might solve this:

Implement a two-step authentication of sorts - cockpit generates a temporary token to identify the current login attempt and then the user uses SSH to authorize the token on the server.

For example, imagine that the cockpit login screen has a button called 'token-based login', clicking on the button gives you  a token string `<token>`.
Then the user executes from the shell:
`ssh -i <ssh_key_file.pem> username@server cockpit-bridge --token-login <token>`
The command returns immediately and the browser automatically logins (similar to how webapps lately use smartphones to authenticate users).
It's a bit cumbersome but doesn't reduce the level of security the user receives.

**Comment by stefwalter** [comment]
@ykorman I'm not against that, but any such implementation would need to be done at the PAM level. It would be useful to Cockpit, but not Cockpit specific. 

Summarized: 
 1. User logs into a system.
 2. Generates a token
 3. That token can be used to log in again, while the initial login session that generated the token is still active.

I'm not against work on this. But don't have time personally to implement it. Would help review patches though ...

**Comment by ykorman** [comment]
I not exactly what I had in mind, but I think it will work just as well.
Also, your suggestion requires writing a PAM module, which might be easier for me to do than delve into Cockpit (it's a much bigger project than I initially thought).
I'll give it a try.

Thanks for the suggestion!
(and the review offer :-))
