### ISSUE TITLE
Change cockpit port on Centos

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [cockpit-project/cockpit#4644]
I'm trying, without any effect, to change cockpit default port as so:
- in ``/lib/systemd/system/cockpit.service`` file adding port option ``ExecStart=/usr/libexec/cockpit-ws --port 443``
- running ``systemctl daemon-reload`` command
- running ``systemctl restart cockpit`` command

Am I doing something wrong?

**Comment by igorSmirnovPlexi** [comment]
Ok, I've changed the cockpit port :)

- add port option ``ExecStart=/usr/libexec/cockpit-ws --port 443`` to the ``/lib/systemd/system/cockpit.service`` file
- change socket port in ``/lib/systemd/system/cockpit.socket`` to 443
- run ``systemctl daemon-reload`` command
- run ``systemctl restart cockpit`` command

**Comment by stefwalter** [comment]
Here's the documentation about that for future reference: http://cockpit-project.org/guide/latest/listen.html
