### ISSUE TITLE
setroubleshootd gets no alerts

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#4678]
https://bugzilla.redhat.com/show_bug.cgi?id=1352611

This needs fixes in both audisp and setroubleshootd.

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-setroubleshoot", line 79, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 664, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 687, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-07-06T12:43:35.362592 | revision 1a798842f46a49e3ab1f30332377ffd1032eb633, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4679-1a798842-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-07-06T12:43:35.362592 | revision 1a798842f46a49e3ab1f30332377ffd1032eb633, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4679-1a798842-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-setroubleshoot", line 80, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "testlib.py", line 217, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 665, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 688, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-07-12T15:46:48.006464 | revision 131511dbb07918aab01c9a16f58b8bba784130bc, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4717-131511db-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2016-07-12T15:46:48.006464 | revision 131511dbb07918aab01c9a16f58b8bba784130bc, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4717-131511db-verify-fedora-testing/log.html)

**Comment by cockpituous** [comment]
verify/fedora-23
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-setroubleshoot", line 80, in testTroubleshootAlerts
    b.wait_present(row_selector)
  File "testlib.py", line 217, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 686, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 709, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-07-26T21:56:34.880144 | revision f574a93ae661c02e5ca17dfe87cb5287bace3845, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4788-f574a93a-verify-fedora-23/log.html)
Times recorded: 1
Latest occurrences:

- 2016-07-26T21:56:34.880144 | revision f574a93ae661c02e5ca17dfe87cb5287bace3845, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4788-f574a93a-verify-fedora-23/log.html)
