### ISSUE TITLE
server page: make more use of title

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#4682]
A lot of the string can end up being eclipsed due to their length.
Pull #4310 puts the full version in a title tag, so you can see it on hover.
It would be nice to do this for the other entrys as well.

**Comment by sgedward** [comment]
Hi,
I try to fix this bug, do you know which file should I look into? Thank you!

**Comment by andreasn** [comment]
@stefwalter asked for clarification on IRC what this issue was about, so here is a screenshot of how the hover for machine works in action.
The label ellipsis, and there is a tooltip with the full data on hover.
This behaviour does not work on the hostname right now.

![screenshot from 2016-11-07 11-46-37](https://cloud.githubusercontent.com/assets/209895/20055095/eb2ee23c-a4df-11e6-9b84-91e8091643d4.png)

**Comment by andreasn** [comment]
No idea what file to look in actually.
pkg/systemd/index.html maybe?

Your browser inspector will be able to find certain elements with certain classes, id's etc. You can then do a global search across the source code for those, here on github for example.
