### ISSUE TITLE
No Containers tab

### ISSUE THREAD

**Issue by cracker0dks** [cockpit-project/cockpit#4686]
Hey,
I have no "containers" tab after a clean installation of Fedora 24. So I checked and no docker was installed. I installed Docker and rebooted but still no tab. 

![image](https://cloud.githubusercontent.com/assets/1816621/16654717/4ed8e93e-4457-11e6-9f3f-9e7f26ce602d.png)

How can I enable the containers tab?

Thanks :)

**Comment by mvollmer** [comment]
Install `cockpit-docker` and then logout and login again to Cockpit.

**Comment by cracker0dks** [comment]
thanks! worked!

**Comment by stefwalter** [comment]
By the way, Fedora 24 Server chose to remove docker from the default install. Cockpit aims to respect what's installed on the system by breaking out parts into subpackages.
