### ISSUE TITLE
No po data load and no other locale can show except en in release 0.113

### ISSUE THREAD

**Issue by vanloswang** [cockpit-project/cockpit#4707]
After read the code, I found out that the po data is not loaded. when I choose a language in 'Display Language' dialog, it take no sense for me. The display language is en always. So how to make the locales to works?
Additionaly, my source code is from http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/source/tree/Packages/c/cockpit-0.113-1.fc25.src.rpm.

@stefwalter CC this issue, Thx.

**Comment by stefwalter** [comment]
Where did you see that the po data is not loaded? In which part of the code? It could be that for one of the documents a <script> tag is missing, so identifying this specifically would be helpful.

**Comment by vanloswang** [comment]
![image](https://cloud.githubusercontent.com/assets/1133578/16752537/b7c204b0-4814-11e6-923a-21170e1e17b3.png)

![image](https://cloud.githubusercontent.com/assets/1133578/16752527/a3472592-4814-11e6-92e7-79184843e6e4.png)

@stefwalter  The code is in ./src/base1/cockpit.js, just search 'Localization' then you will see it.

**Comment by vanloswang** [comment]
@larsu CC this issue

**Comment by stefwalter** [comment]
@vanloswang I think I tracked the issue down.

**Comment by stefwalter** [comment]
@vanloswang The pull request #4728 and specifically this commit 7a5b09b2b4ad7e4e85c13933d3bc5e30f1ef486d should fix this problem.

**Comment by vanloswang** [comment]
@stefwalter Is the po file in the output .gz file? or somewhere need to put it to?

**Comment by stefwalter** [comment]
Yes, the po data is in the .gz file. But as I said, https://github.com/cockpit-project/cockpit/pull/4728 needs to be merged before this actually works.
