### ISSUE TITLE
Subscriptions: should we use Empty State with missing subscription-manager dep?

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#4712]
http://www.patternfly.org/pattern-library/communication/empty-state/#_

**Comment by stefwalter** [comment]
Not sure, is it expected that it's missing? Don't the Cockpit packages that include the subscription functionality depend on subscription-manager being installed in order to themselves install?

**Comment by andreasn** [comment]
This was built from source, so probably less of a problem in production.

**Comment by dperpeet** [comment]
the react rewrite will probably use EmptyState #4715

**Comment by dperpeet** [comment]
similar to what we do for SELinux troubleshooting

**Comment by martinpitt** [comment]
The Subscriptions page is maintained in the [subscription-manager project](https://github.com/candlepin/subscription-manager) now.
