### ISSUE TITLE
Unable to View Network Device Information

### ISSUE THREAD

**Issue by canit00** [cockpit-project/cockpit#4731]
We are testing Cockpit v 0.108 and when wanting to drill down to the network device we receive a blank page.

The steps to reproduce are:

Under Networking --> Clicking the device under --> Name

Same error under Windows server FireFOx 4.7.0 and Mac OS X using Version Chrome 51.0.2704.103 (64-bit)

**Comment by canit00** [comment]
![screen shot 2016-07-13 at 1 20 05 pm](https://cloud.githubusercontent.com/assets/17949679/16815052/02f043f4-48fe-11e6-8367-be65b8d3a9e7.png)

**Comment by andreasn** [comment]
Is this using the packages from the RHEL 7 testing repo?

**Comment by canit00** [comment]
cockpit.x86_64                   0.108-1.el7          @rhel-7-server-extras-rpms
cockpit-bridge.x86_64            0.108-1.el7          @rhel-7-server-extras-rpms
cockpit-shell.noarch             0.108-1.el7          @rhel-7-server-extras-rpms
cockpit-storaged.noarch          0.108-1.el7          @rhel-7-server-extras-rpms
cockpit-ws.x86_64                0.108-1.el7          @rhel-7-server-extras-rpms

**Comment by stefwalter** [comment]
Oh hmmm, and a similar problem was fixed in https://github.com/cockpit-project/cockpit/pull/4619 That fix was included in Cockpit versions 0.112 and later. That fix should make it into the next version of Cockpit targeted for RHEL.

**Comment by stefwalter** [comment]
I'll mark this as closed by both #4681 and #4619
