### ISSUE TITLE
broken view with untrusted certificate

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [cockpit-project/cockpit#4735]
![screen shot 2016-07-14 at 10 19 49 am](https://cloud.githubusercontent.com/assets/19838682/16831255/a2b4dbbc-49ac-11e6-89b9-c01acbed8f6d.png)

After accepting untrusted certificate, the application works fine. But once the acceptance has timeout, on navigate to the new page you get broken view with error on console `Failed to load resource: net::ERR_INSECURE_RESPONSE`. The iframe which serve the resource unavailable to load it. After page reload and accepting untrusted certificate, the page is loading as expected.

I think, some user friendly message in this case will be very helpful. Let say, on menu entry click, before activate an iframe, check if a page is available, if not, show the message. 

![screen shot 2016-07-14 at 10 34 57 am](https://cloud.githubusercontent.com/assets/19838682/16831638/d1511812-49ae-11e6-80c2-7eca6cbd91f8.png)

To reproduce this bug, you should stop using an invalid certificate and then navigate to the new page.

**Comment by stefwalter** [comment]
Browsers have been making it harder and harder to use "invalid" certificates. We should move towards making it easier to install/use a valid certificate, rather than trying to work around browsers.

**Comment by martinpitt** [comment]
This is still by and large the same, but shouldn't come as a surprise to a user when explicitly clicking on "stop trusting this certificate" .. at that point we can't send any new page any more, and we really don't want to watch for this condition everywhere all the time (is this even possible with JavaScript? I doubt it)

I agree that we shouldn't "fix" this -- it works as advertised.
