### ISSUE TITLE
Use bower to get patternfly.

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#475]
Updating Patternfly is a pretty manual process right now, and I can't say that I knew how web stuff is supposed to be distributed and installed when I imported the first version of Patternfly.  So let's look at this again.

https://www.redhat.com/archives/patternfly/2014-April/msg00027.html

**Comment by dperpeet** [comment]
This is what we do. The only exception is for the static landing page, but I don't think this is what the issue is about.
