### ISSUE TITLE
Will it work on fedora 10

### ISSUE THREAD

**Issue by carson20** [cockpit-project/cockpit#4761]
Just wanted to know if it could work on old fedora 10 as maybe i missed out to look at minimum requirement.

**Comment by andreasn** [comment]
Among other things, Cockpit relies heavily on systemd for a lot of it's functionality.
If I recall correctly, systemd was only introduced in Fedora 15.

**Comment by andreasn** [comment]
So unfortunately, no.
I would recommend upgrading to at minimum Fedora 21 Server, where Cockpit is installed by default.
