### ISSUE TITLE
Why do we read template from k8s or origin and list them in cockpit-k8s?

### ISSUE THREAD

**Issue by vanloswang** [cockpit-project/cockpit#4769]
Now we can manage k8s and origin, but we do not read and show any templates from k8s or origin. The benefit of this point is that we can reuse these templates on the servers to create multi app with the same template. It is an alternative way to create apps fast. To upload template frequently is troublesome. Add a new menu item named 'Template', show and manage templates there will be more convenience. Does someone appreciate this idea?

**Comment by stefwalter** [comment]
Seems to make sense, although the Openshift Web Console is more developer oriented. In the Cockpit admin console for origin/k8s I would think we would want to target the "deploy an application" case. Where that application was defined elsewhere. Sometimes templates do fit that use case.

Is there a central repository somewhere for templates, that we could populate a list from? Like the way we can search the docker hub?
