### ISSUE TITLE
Cache and Translated assets

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#4784]
#4728 Fixed a regression with loading po files and added ETags that take language into account. However because browsers are not guaranteed to re-request all assets within an iframe after a window.location.reload(true). Etags might now be enough in some cases.

So we may need to vary on cookie at least for urls that are translatable. Or alternatively we could work out a scheme to have each language load from a different url by using different prefix or a base url or a query argument, instead of relying on the cookie.

**Comment by stefwalter** [comment]
@petervo Agree that changing the URL would be the cleanest. Do you have ideas for how that would work? Something, something ... CockpitChannelInject?
