### ISSUE TITLE
after deleting user, there is still info about user

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#4793]
Hi,
I've tested manually create and remove user with cockpit 0.114 and it caused that after click on delete user button, user is deleted, but user info window is still there, I've met it when testing cockpit in atomic, but probably same issue will be also in normal cockpit
![screenshot from 2016-07-28 12-35-20](https://cloud.githubusercontent.com/assets/8735467/17210571/03bf8f52-54c4-11e6-9a9a-c302972fbd46.png)

after page reload it is fixed

**Comment by jscotka** [comment]
after page reload it is fixed

**Comment by jscotka** [comment]
I've met that issue, becaue upstream avocado selenium tests for tools tab failed. 
It is also strange, because I'm deleting there user testxx, also backgroug shows that there is open testxx user, but tries to delete test user (what is logged used, so it is not able to delete)
It happens with atomic, with normal release I've didn't met that.
# rpm -qa cockpit\*
cockpit-docker-0.114-2.el7.x86_64
cockpit-shell-0.114-2.el7.noarch
cockpit-bridge-0.114-2.el7.x86_64
cockpit-ostree-0.114-2.el7.x86_64

![screenshottest80changetabtools](https://cloud.githubusercontent.com/assets/8735467/17210990/d6b1da6c-54c6-11e6-9056-8f4521d40dff.png)

**Comment by jscotka** [comment]
I've tested it with normal cockpit, and it happened only with atomic container, not with normal cockpit 
# rpm -qa cockpit\*
cockpit-0.114-2.el7.x86_64
cockpit-bridge-0.114-2.el7.x86_64
cockpit-docker-0.114-2.el7.x86_64
cockpit-debuginfo-0.114-2.el7.x86_64
cockpit-ws-0.114-2.el7.x86_64
cockpit-storaged-0.114-2.el7.noarch
cockpit-doc-0.114-2.el7.x86_64
cockpit-pcp-0.114-2.el7.x86_64
cockpit-shell-0.114-2.el7.noarch

**Comment by dperpeet** [comment]
so maybe there's an underlying issue unrelated to cockpit

**Comment by jscotka** [comment]
yep, it could be, but I have no idea, what causes these issue, it seems cockpit related, but who knows. It could be caused by that, maybe it could be caused by some missing cokcpit package, what are installed normally but not installed inside atomic host?
Or in cockpit-ws atomic container there are little bit different .js scripts than in cockpit-ws package?

**Comment by dperpeet** [comment]
it might be permissions related when trying to read ssh keys

**Comment by deryni** [comment]
I just ran into this issue on a self-built (but unmodified) cockpit-150 on a CentOS 7 VM (with some custom packages/hardening/etc.).

It looks like nothing hides the `#account` element once the delete happens. So you get the normal `#accounts` element listing the accounts and then the `#account` element for the (now deleted) account under it.

**Comment by mvollmer** [comment]
Should be (finally) fixed by #8479.
