### ISSUE TITLE
i18n for simplified Chinese should be support 

### ISSUE THREAD

**Issue by vanloswang** [cockpit-project/cockpit#4814]
I have completed most translation for simplified Chinese on https://fedora.zanata.org. The tranlated rate is reach 85%. But with latest Cockpit, the display language of Chinese is not supported. We need to fix it to support it. And then I will find the remaining untranslted strings and go on the translate job. Also need someone to review the translations.

@petervo @stefwalter @cockpit-bot CC this issue and talk about later works.

**Comment by petervo** [comment]
@vanloswang bringing in your changes here #4815.

**Comment by vanloswang** [comment]
already support in 0.117, so closed this issue.
