### ISSUE TITLE
Add a new host via command line or rest or ansible

### ISSUE THREAD

**Issue by glennswest** [cockpit-project/cockpit#4818]
Looking for being able to add host in a automated way. 
Api - command line - database injection

**Comment by petervo** [comment]
Hosts are stored in json at /var/lib/cockpit/ in a file named machines.json. We hope to have a better way to add machines automatically in the future, but for now editing that file is your best bet. When it gets reworked in the future care will be taken to ensure backwards compatibility with the current json format.
