### ISSUE TITLE
When adding additional host, get a issue with cockpit-bridge not being authorised in RHEL 7.2

### ISSUE THREAD

**Issue by glennswest** [cockpit-project/cockpit#4819]
Aug  4 03:35:21 localhost polkitd[997]: Registered Authentication Agent for unix-session:9 (system bus name :1.69 [cockpit-bridge], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Aug  4 03:35:23 localhost polkitd[997]: Operator of unix-session:9 FAILED to authenticate to gain authorization for action org.freedesktop.policykit.exec for unix-process:4912:286104 [cockpit-bridge](owned by unix-user:gwest)
Aug  4 03:35:23 localhost pkexec[4923]: gwest: Error executing command as another user: Not authorized [USER=root] [TTY=unknown] [CWD=/run/user/1000] [COMMAND=/usr/bin/cockpit-bridge --privileged]
Aug  4 03:40:08 localhost sudo:   gwest : TTY=pts/0 ; PWD=/home/gwest/.ssh ; USER=root ; COMMAND=/bin/bash
Aug  4 03:48:16 localhost polkitd[997]: Registered Authentication Agent for unix-process:32580:363660 (system bus name :1.76 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Aug  4 03:48:16 localhost sshd[2708]: Received signal 15; terminating.

**Comment by glennswest** [comment]
[gwest@master1 ~]$ pkexec cockpit-bridge
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ===
Authentication is needed to run `/usr/bin/cockpit-bridge' as the super user
Authenticating as: gwest
Password:

**Comment by petervo** [comment]
Cockpit is trying to use pkexec to check if you have permission to run commands as a superuser. If you don't cockpit should continue to work with the parts that require superuser privileges disabled.

What behavior are you expecting? Are you logging into these machines using password authentication or kerberos or key based auth.

**Comment by glennswest** [comment]
using key based authentication.

I can connect to all the machines via ssh via gwest

Im adding the host to the dashboard, which fails.

It looks like I need to add  /etc/polkit-1/rules.d/49-nopasswd_global.rules and make them a part of wheel group.

/* Allow members of the wheel group to execute any actions
 * without password authentication, similar to "sudo NOPASSWD:"
 */
polkit.addRule(function(action, subject) {
    if (subject.isInGroup("wheel")) {
        return polkit.Result.YES;
    }
});

**Comment by glennswest** [comment]
Aug  4 04:42:35 localhost cockpit-session: pam_succeed_if(cockpit:auth): requirement "uid >= 1000" not met by user "root"
Aug  4 04:42:45 localhost cockpit-session: pam_unix(cockpit:session): session opened for user gwest by (uid=0)
Aug  4 04:42:45 localhost polkitd[997]: Registered Authentication Agent for unix-session:18 (system bus name :1.93 [cockpit-bridge], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Aug  4 04:42:47 localhost polkitd[997]: Operator of unix-session:18 FAILED to authenticate to gain authorization for action org.freedesktop.policykit.exec for unix-process:32794:690563 [cockpit-bridge] (owned by unix-user:gwest)
Aug  4 04:42:47 localhost pkexec[32806]: gwest: Error executing command as another user: Not authorized [USER=root] [TTY=unknown] [CWD=/run/user/1000] [COMMAND=/usr/bin/cockpit-bridge --privileged]
Aug  4 05:07:14 localhost sudo:   gwest : TTY=pts/0 ; PWD=/var/log ; USER=root ; COMMAND=/bin/bash
Aug  4 05:15:43 localhost sudo:   gwest : TTY=pts/0 ; PWD=/var/log ; USER=root ; COMMAND=/bin/bash

**Comment by glennswest** [comment]
Given username "X" I want to 
Be able to login into cockpit
Add N normal of hosts via add host dialog on dashboard
and have full privileges on all the hosts

The host all have user X enabled, and ssh is enabled and work to all hosts

I've installed the cockpit as well.

**Comment by petervo** [comment]
When  you try to add a machine via the dashboard what error message does it give you? Screenshot or javascript console output would be helpful.

When using key based auth for secondary machines, cockpit does not have a password to use to escalate privileges on those secondary machines. So the user will only have full privileges if they have NOPASSWD turned on either with polkit or sudo. For the primary machine the password you used to log into cockpit is used if polkit or sudo prompts for a password. See http://cockpit-project.org/guide/latest/authentication.html for more details.

**Comment by glennswest** [comment]
/var/log/secure
Aug  4 07:58:28 localhost sshd[33591]: pam_unix(sshd:session): session opened for user gwest by (uid=0)
Aug  4 07:58:28 localhost sshd[33589]: Received disconnect from 180.96.63.100: 11: Bye Bye [preauth]
Aug  4 07:58:31 localhost sshd[33634]: Received disconnect from 180.96.63.100: 11: Bye Bye [preauth]
Aug  4 07:58:32 localhost sshd[33636]: Received disconnect from 180.96.63.100: 11: Bye Bye [preauth]
Aug  4 07:58:33 localhost sshd[33638]: Received disconnect from 180.96.63.100: 11: Bye Bye [preauth]
Aug  4 07:58:34 localhost sshd[33640]: Received disconnect from 180.96.63.100: 11: Bye Bye [preauth]
Aug  4 07:58:36 localhost sshd[33643]: Received disconnect from 180.96.63.100: 11: Bye Bye [preauth]
Aug  4 07:58:37 localhost sudo:   gwest : TTY=pts/0 ; PWD=/var/log ; USER=root ; COMMAND=/bin/bash
Aug  4 07:58:37 localhost sshd[33645]: Received disconnect from 180.96.63.100: 11: Bye Bye [preauth]
Aug  4 07:58:39 localhost sshd[33673]: Received disconnect from 180.96.63.100: 11: Bye Bye [preauth]


<img width="1286" alt="screen shot 2016-08-04 at 2 59 24 pm" src="https://cloud.githubusercontent.com/assets/31789/17394578/27ff8ecc-5a54-11e6-89cd-d0e966bf6573.png">
<img width="846" alt="screen shot 2016-08-03 at 4 50 53 pm" src="https://cloud.githubusercontent.com/assets/31789/17394586/2caf5600-5a54-11e6-8bbf-acee6a2149b2.png">

**Comment by glennswest** [comment]
<img width="1248" alt="screen shot 2016-08-04 at 2 59 56 pm" src="https://cloud.githubusercontent.com/assets/31789/17394695/bcefeb12-5a54-11e6-8927-39969f0c2a39.png">

**Comment by glennswest** [comment]
Currently this is where I'm at, I added the known_hosts file, Just gives me not permited

Aug  4 08:32:03 localhost systemd: Starting Hostname Service...
Aug  4 08:32:03 localhost systemd: Starting Time & Date Service...
Aug  4 08:32:03 localhost dbus[663]: [system] Successfully activated service 'org.freedesktop.timedate1'
Aug  4 08:32:03 localhost dbus-daemon: dbus[663]: [system] Successfully activated service 'org.freedesktop.timedate1'
Aug  4 08:32:03 localhost systemd: Started Time & Date Service.
Aug  4 08:32:03 localhost dbus-daemon: dbus[663]: [system] Successfully activated service 'org.freedesktop.hostname1'
Aug  4 08:32:03 localhost dbus[663]: [system] Successfully activated service 'org.freedesktop.hostname1'
Aug  4 08:32:03 localhost systemd: Started Hostname Service.
Aug  4 08:32:03 localhost cockpit-bridge: cannot reauthorize identity(s): unix-user:root 
Aug  4 08:32:03 localhost cockpit-bridge: Error executing command as another user: Not authorized
Aug  4 08:32:03 localhost cockpit-bridge: This incident has been reported.
Aug  4 08:32:03 localhost cockpit-bridge: sudo: sorry, you must have a tty to run sudo
Aug  4 08:32:38 localhost cockpit-ws: master1: ssh-ed25519 host key for server is not known: 30:35:24:ea:80:80:be:2c:52:e6:e9:84:0a:78:59:c2
Aug  4 08:36:45 localhost cockpit-bridge: No journal files were found.
Aug  4 08:36:45 localhost cockpit-bridge: Failed to get realtime timestamp: Cannot assign requested address
Aug  4 08:36:45 localhost cockpit-bridge: No journal files were found.
Aug  4 08:36:45 localhost cockpit-bridge: Failed to get realtime timestamp: Cannot assign requested address
Aug  4 08:36:48 localhost systemd: Configuration file /usr/lib/systemd/system/wpa_supplicant.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Aug  4 08:36:48 localhost systemd: Configuration file /usr/lib/systemd/system/ebtables.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Aug  4 08:36:54 localhost cockpit-bridge: No journal files were found.
Aug  4 08:36:54 localhost cockpit-bridge: Failed to get realtime timestamp: Cannot assign requested address
Aug  4 08:40:01 localhost systemd: Created slice user-0.slice.
Aug  4 08:40:01 localhost systemd: Starting user-0.slice.
Aug  4 08:40:01 localhost systemd: Started Session 49 of user root.
Aug  4 08:40:01 localhost systemd: Starting Session 49 of user root.
Aug  4 08:40:01 localhost systemd: Removed slice user-0.slice.
Aug  4 08:40:01 localhost systemd: Stopping user-0.slice.

**Comment by petervo** [comment]
Ok, so it seems that on the primary server you aren't able to get superuser privileges, but you are still seeing the 'add server' button. If that's the case that's a bug we'll need to fix.

As to why that isn't working, did you log in the primary server with a password or SSO. If a password is it the same password that pkexec expects when used from the command line?

**Comment by glennswest** [comment]
I logged into the server with a password. 
I actually ran pkexec, and it seem to run on the target system just fine.
I can ssh across using the same keys just fine as well and user.
maybe I need to add in sudoer rule for the user? (On the master server?)

**Comment by Yoshi2889** [comment]
Sorry for necrobumping this, I'm having this exact issue with a similar setup using Fedora 28. Two servers use a different password and I want to use one to monitor the other. 

Adding the nopasswd rule for policykit fixes the issue of not being able to authenticate but this is considered bad practice. Perhaps a better solution would be fore cockpit to show (an) authentication dialog(s) when entering privileged areas?

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
