### ISSUE TITLE
intergrate with ansible tower or provide a way to execute ansible playbooks

### ISSUE THREAD

**Issue by vanloswang** [cockpit-project/cockpit#4821]
We know that Cockpit is aimed at managing servers, but with a huge deployment task, there is not convenient to handle in the terminal on Cockpit. So run an ansible or ansible tower container with Cockpit, and intergrate with it, and provide a way to execute ansible playbooks is more powerful to deploy huge tasks.  What do you think about this issue?

**Comment by mvollmer** [comment]
Yes, good idea.  Cockpit would be a good place for a Ansible UI, I think.

**Comment by stefwalter** [comment]
@vanloswang Cockpit is Interactive, and not about managing huge amounts of servers. Tower is already a general Ansible UI. So although I'm not against having Ansible stuff in Cockpit, it needs to be focused on the story people actually use this for.

Perhaps interactive aspects of Ansible, running playbooks, looking at effects, and so on?

**Comment by vanloswang** [comment]
@stefwalter Finally, I found out that run a jenkins container and install ansible plugin for jenkins will meet the requirements. not need ansible tower.

**Comment by vanloswang** [comment]
https://github.com/cockpit-project/cockpit/issues/5507
