### ISSUE TITLE
Ready/HealthCheck page for Cockpit GUI

### ISSUE THREAD

**Issue by VinayKumarbrsoft** [cockpit-project/cockpit#4828]
When I try to setup a probe for healthcheck of Cockpit-kubernetes gui I always get HTTP 401 response using the following URL.  I think it is trying to auto-logon using the credentials stored in cookie. 

Is there a healthcheck url for cockpit-gui that I can use to setup my probe which does not try to auto-logon? 

`VM43 kubernetes:186 GET https://k8svinay1a.localdomain:30601/cockpit/login 401 (Authentication failed)
standard_auto_login @ VM43 kubernetes:186
boot @ VM43 kubernetes:164`

**Comment by petervo** [comment]
You could try hitting one of the assets in static, ei static/branding.css, those are served without any authentication required.

**Comment by stefwalter** [comment]
@VinayKumarbrsoft This is how you would do that:

http://cockpit-project.org/guide/latest/embedding.html#embedding-cors

**Comment by VinayKumarbrsoft** [comment]
Thanks @stefwalter .  Exactly what I was looking for.  Cheers!!

**Comment by stefwalter** [comment]
@VinayKumarbrsoft Glad it worked :)
