### ISSUE TITLE
cockpit on korora 24

### ISSUE THREAD

**Issue by rxrftx** [cockpit-project/cockpit#4832]
Just upgraded to korora 24 (fedora remix) and cockpit only gives me system, services, logs and tools as options. it appears to be missing containers, storage, and networking. I didnt have any issues using cockpit with korora 23. I attached an image showing the cockpit interface.

Thanks for your help!

![cockpit1](https://cloud.githubusercontent.com/assets/19593967/17447285/33ceacfa-5b13-11e6-8833-81114fe8a4b3.png)

**Comment by petervo** [comment]
Those are separate packages: cockpit-docker, cockpit-networking, cockpit-storaged
