### ISSUE TITLE
make fewer categories in a server's left menu

### ISSUE THREAD

**Issue by abonas** [cockpit-project/cockpit#485]
Please see attached screenshot.
Some categories  in the left menu seem to have very few options, and hold basic and general info about the system (for example - "system information" and "shutdown and reboot"). 
Perhaps they can be merged into fewer categories, or/and be visible in the main view without the need to explicitly navigate to?  Currently this view contains 4 graphs and has plenty of free space anyway.
![serverview](https://cloud.githubusercontent.com/assets/6277245/2742684/df7016cc-c707-11e3-89f3-d8e11f65202a.png)

**Comment by stefwalter** [comment]
The new navigation has reworked this considerably. In particular components (the right hand side of the screen) are now embeddable independently, without the Cockpit navigation.

http://files.cockpit-project.org/guide/latest/embedding.html#embedding-full
