### ISSUE TITLE
Wrong plural rule for Polish translation

### ISSUE THREAD

**Issue by piotrdrag** [cockpit-project/cockpit#4855]
The change from #4586 got reverted and now po/pl.po has the wrong plural rule again. It should be:

`"Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"`

**Comment by petervo** [comment]
Sorry about that, opened a PR to fix. Need to figure out how to make sure that get preserved with the next update.

**Comment by petervo** [comment]
Fixed in zanata as well, so this shouldn't happen again.

**Comment by piotrdrag** [comment]
Thank you!
