### ISSUE TITLE
Docker storage setup screen doesn't filter out removable media

### ISSUE THREAD

**Issue by sgallagher** [cockpit-project/cockpit#4864]
![cockpit-docker-storage-setup](https://cloud.githubusercontent.com/assets/739555/17590829/5377fbfc-5fa9-11e6-8c0a-62442d2af175.png)

On my system, my (empty) DVD-RAM drive is listed as an available source for increasing docker storage. This will absolutely not work.

**Comment by mvollmer** [comment]
We don't work on Docker in Cockpit anymore, the story continues at https://github.com/cockpit-project/cockpit-podman
