### ISSUE TITLE
Registry: 'admin' doesn't appear in membership, only 'registry-admin'

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#4868]
If a user creates a project via OpenShift (CLI or console), they are project "admin" role. Projects created using the cockpit console get "registry-admin" role. "Admin" does not appear in project membership views in the cockpit console. Both are valid admin roles, we just need to account for both cases.

**Comment by aweiteka** [comment]
I looked at this but couldn't find an obvious solution. One approach may be to add an "admin" role with a null displayRole and handle that case when displaying.

            var registryRoles = [{ ocRole: "registry-admin", displayRole :"Admin"},
                { ocRole: "admin", displayRole :null },
                { ocRole:"registry-editor", displayRole :"Push" },
                { ocRole:"registry-viewer", displayRole :"Pull" }];

**Comment by aweiteka** [comment]
IRC conversation with @petervo we decided it's not good for Admin to be valid for both *registry-admin* and *admin*. So something like this would work with some explanatory text.

            var registryRoles = [{ ocRole: "registry-admin", displayRole :"Registry Admin"},
                { ocRole:"registry-editor", displayRole :"Push" },
                { ocRole:"registry-viewer", displayRole :"Pull" },
                { ocRole: "admin", displayRole : "Project Admin" }];

**Comment by stefwalter** [comment]
So the question is whether we start to have a potentially unbounded list of roles here, and move towards making this part of the UI more generally reusable. @aweiteka Is that along the lines you're thinking?

**Comment by aweiteka** [comment]
> potentially unbounded list of roles here

This is a risk. Honestly I don't like any option at this point. It's a choice between misleading (admin != admin) and confusing (What is the difference between admin and registry-admin and why should I care?).

**Comment by stefwalter** [comment]
> This is a risk. Honestly I don't like any option at this point. It's a choice between misleading (admin != admin) and confusing (What is the difference between admin and registry-admin and why should I care?).

Should we just set both admin and registry-admin when the user selects admin in the registry UI?

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode: https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/

However, this actually looks like a reasonably serious issue. Apparently we've got by in the past years with it, but I'll keep it open for now, just in case  someone who knows OpenShift well wants to address this (we don't have anyone in the cockpit team any more).

**Comment by marusak** [comment]
Almost another year passed and no update. Also kubernetes UI is not supported from master anymore. If this should be fixed in some downstream release, it should be reported to appropriate bug tracker.
