### ISSUE TITLE
Registry: Display quota limits

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#4879]
As a user I want to view any quota restrictions that has been place on my account or project. Interesting information is storage and project quotas. Reference: https://docs.openshift.org/latest/admin_guide/limits.html#image-limits

**Comment by stefwalter** [comment]
Is this strictly per-project information?

**Comment by aweiteka** [comment]
> Is this strictly per-project information?

Good question. I think the most common use case is per project. There are cluster-scoped quotas but I don't see these as being very relevant to the registry. See https://docs.openshift.org/latest/admin_guide/multiproject_quota.html

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
