### ISSUE TITLE
Registry: prune images button for admins

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#4880]
OpenShift provides a garbage collection service for pruning non-referenced image blobs from the registry. A cluster-admin should have the capability to prune the registry from the web console. See https://docs.openshift.org/latest/admin_guide/pruning_resources.html#pruning-images

**Comment by stefwalter** [comment]
@aweiteka Some questions to get us started:

 * Does this apply to the entire registry or per image stream?
 * Does this make sense on Openshift for cluster admins (ie: non-registry UI).
 * Are there other registry wide operations to build a page around?

**Comment by aweiteka** [comment]
> Does this apply to the entire registry or per image stream?

I think this is the entire registry. It may be possible to limit to a specific project (the oadm cmd supports this) but I would think the most common use cases is registry-wide.

> Does this make sense on Openshift for cluster admins (ie: non-registry UI).

Yes, a cluster admin can prune several other resources: builds, deployments and groups (as of openshift v1.3.0-alpha).

> Are there other registry wide operations to build a page around?

I can't think of any. This does seem a bit "one-off". The Project view does have some administrative focused controls, like managing users and groups.

**Comment by stefwalter** [comment]
Why should the user have to run this from the web console? Why wouldn't it be something that is either (or both):

 * Scheduled, and scheduled by default
 * Run from the command line in outlier cases

**Comment by aweiteka** [comment]
> Scheduled, and scheduled by default
> Run from the command line in outlier cases

Good point. These are more likely scenarios.
