### ISSUE TITLE
Put system information to the Dashboard

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#49]
It would be nice to get a quick overview of the characteristics of the machine already on the Dashboard. This would include the most crucial parts of information of the machine.

Some quick ideas on what this would be:
- Host name
- Operating System
- Domain
- Uptime

It would also be nice to put the identifying picture here.

**Comment by kanersps** [comment]
> Uptime seems a bit over the line as it would have to be constantly updated.

Couldn't it just be updated every minute or so? Currently I just added uptime to my own plugin but I'd much rather prefer it to be added to the system page.
