### ISSUE TITLE
The strings with _() is not translated

### ISSUE THREAD

**Issue by vanloswang** [cockpit-project/cockpit#4913]
In cockpit, only tanslate the strings marked with 'translatable = "yes"'.

In the Makefile.am,:
update-pofiles:
    cd $(srcdir) && \
    echo "# Generated by make update-potfiles" > po/POTFILES.in && \
    cat po/POTFILES.in.in >> po/POTFILES.in && \
    find pkg/ -name "_.js" | xargs grep -l "gettext" >> po/POTFILES.in && \
    find lib/ -name "_.js" | xargs grep -l "gettext" >> po/POTFILES.in && \
    find src/base1/ -name "_.js" | xargs grep -l "gettext" >> po/POTFILES.in && \
    find pkg/ -name "_.html" | xargs grep -l "translatable" | sed -e "s#(._)#[type: gettext/glade] \1#g" >> po/POTFILES.in && \
    find lib/ -name "_.html" | xargs grep -l "translatable" | sed -e "s#(.*)#[type: gettext/glade] \1#g" >> po/POTFILES.in

In ./src/base1/cockpit.js:
    cockpit.translate = function translate(el) {
        var list = (el || document).querySelectorAll("[translatable=\"yes\"]");
        var e, translated, i, len;
        if (list) {
            for (i = 0, len = list.length; i < len; i++) {
                e = list[i];
                translated = cockpit.gettext(e.getAttribute("context"), e.textContent);
                e.removeAttribute("translatable");
                e.textContent = translated;
            }
        }
    };

**Comment by vanloswang** [comment]
@stefwalter @petervo CC this issue, Shall we change '_()' to 'translatable = "yes"'?

**Comment by petervo** [comment]
While cockpit.translate doesn't touch _() values, if done correctly those string should still be translated by the cockpit.gettext call. Can you give an example of a string that should be translated but isn't?

**Comment by vanloswang** [comment]
@petervo 
 in pkg/docker/storage.jsx:
153                     case "sdd": return _("Solid-State Disk");
154                     case "hdd": return _("Hard Disk");
155                     default:    return _("Drive");

185                         <h4>{_("Local Disks")}</h4>

191                 drive_list = <span>{_("No additional local storage found.")}</span>;

There are to many strings need to changed. Just type the following cmd in the cockpit source code:
```bash
grep '_(\"' -r .
```
You will see most of them.

**Comment by petervo** [comment]
Well there are lots of _() strings that are translated correctly. For example _("$0 Block Device") in pkg/storaged/overview.js. So I don't think it's accurate to say all instances of _() are wrong.

Are all the strings you are seeing missing in .jsx files? It's possible that we aren't processing those correctly.

**Comment by vanloswang** [comment]
@petervo I only fount out the strings with _() is not translated in .jsx files.

**Comment by vanloswang** [comment]
@petervo I found out that some string in js file is not translated too.
./pkg/realmd/operation.js:                text = _("Join Domain");

**Comment by petervo** [comment]
@vanloswang thanks for the report. So there is in fact a race condition between that button loading and the translations file loading. If the translations aren't yet loaded when the link picks it's text we get the default text showing through.

As a separate issue, translations in react and angular based packages are not working or only partially working.

**Comment by vanloswang** [comment]
@petervo is there some new roadmap for this issue or i18n?

**Comment by petervo** [comment]
@vanloswang, sorry for the long delay in replying @stefwalter did a bunch of work that should fix the gathering of translations and the translations of react and angular based packages. An updated pot has been uploaded to zanata.

I'm not sure that the race condition is in fact solved. But i guess the next step would be to get one of the translations up to date and see where we are at from there.

**Comment by stefwalter** [comment]
The extraction infrastructure has been updated. Remaining bulk changes to marking up translatable will be fixed by #5442. In particular various fixes have been made to extract strings from jsx and es6 files. In addition it's worth noting that ```_('String')``` with single quotes was never, and still is not extracted. All those instances have been replaced wit double quotes in #5442.

**Comment by petervo** [comment]
This issue isn't fully solved, would like to leave open until @vanloswang has had a chance to take a look.

**Comment by vanloswang** [comment]
@petervo most of the strings is translated ok, but some string in storage UI, bridge UI and docker storage related UI is not translated, I have updated the chinese translation on zatana, the po file need to be updated.

**Comment by vanloswang** [comment]
@petervo @stefwalter The login UI are not translated too.

**Comment by stefwalter** [comment]
> @petervo @stefwalter The login UI are not translated too.

Indeed. Good point. But that's not related to this issue. This is about strings wrapped in ```_("")``` not being translated.

**Comment by stefwalter** [comment]
> @petervo most of the strings are translated ok, but some string in storage UI, bridge UI and docker storage related UI are not translated, I have updated the chinese translation on zatana, the po file need to be updated.

Could you file a new bug about those specific strings, in the storage, bridge, and docker UI pages? And paste the strings into the bug which you see are not being translated?
