### ISSUE TITLE
Support multi-step authentication for secondary machines.

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#4921]
Right now multi-step authentication only works with the primary machine. We probably should support it for secondary machines as well. This means adding dialogs to the shell and figuring out how to detect both shell and cockpit-ws support for this feature.

**Comment by mvollmer** [comment]
What is multi-step authentication?

**Comment by marusak** [comment]
This issue is closed due to inactivity.

We are sorry, but we won't be able to address this in any time soon.
If you are interested in helping us with the implementation, please comment here.
