### ISSUE TITLE
"Permission Denied" while logging in

### ISSUE THREAD

**Issue by FireDrunk** [cockpit-project/cockpit#4943]
When my server is still booting, and cockpit has already been started, i get the message "Permission Denied" while logging in. This is because pam_nologin is still rejecting logins (this is also true for SSH).

While this is a valid state of the system (you cannot login while booting), the error message is not very descriptive. Perhaps this can be changed to the error SSH gives:
```System is booting up. See pam_nologin(8) 
Connection closed by xxx.xxx.xxx.xxx```

**Comment by stefwalter** [comment]
Good catch. The above pull request should fix this issue.
