### ISSUE TITLE
Registry: project filter cannot display large list

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#4944]
With a large number of projects the Project filter drop-down extends below the page. In the Images view the drop-down is pinned to the top of the viewport so scrolling the page does not reveal the rest of the projects.

Version 0.117

![screen shot 2016-08-30 at 2 19 51 pm](https://cloud.githubusercontent.com/assets/1764461/18101507/ec340a80-6ebc-11e6-8df2-196f2254b752.png)
.

**Comment by stefwalter** [comment]
I added a workaround in #4945, but I don't think it'll completely fix this issue.

 @andreasn What kind of UI element should we use here, to make such a long project list be searchable, navigable?

**Comment by andreasn** [comment]
I think we can use a variant of the dropdown with a filter if the list exceeds more than 10 items.
I used this in the Journal mockups (see Services)
https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/journal/journal-v3.png

**Comment by andreasn** [comment]
There is also the combobox [1] that lets you type straight into the text field to filter things down.
Using that could make it more apparent that there is a filtered view you're looking at, but it also feels less solid somehow. [2]

1. http://www.patternfly.org/pattern-library/widgets/#bootstrap-combobox
2. Vague, handwavey

**Comment by andreasn** [comment]
Here is a example of what I mean with the filter. See select2 here: http://angular-ui.github.io/ui-select/demo-basic.html

I spoke to skateman from the manageIQ design team on IRC, and he said they are using a similar control there.

**Comment by aweiteka** [comment]
> Here is a example of what I mean with the filter. See select2 here: http://angular-ui.github.io/ui-select/demo-basic.html

I think this would work well. We get search-like filter "for free", which is useful with large lists anyway.

**Comment by martinpitt** [comment]
Was [fixed](https://github.com/cockpit-project/cockpit/commit/897f9f9baf231096dcadb440395d81111167cae9)  a long time ago, but not closed.
