### ISSUE TITLE
Registry: display project access policy in Images view

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#4949]
As a user, I am most curious about access policy when I'm looking at an image. When a project is selected in Image view it would be helpful to display the access policy above the list somewhere. Not sure how it should render, possibly just use the existing text from Projects page, "[Project access policy](#) allows any authenticated user to pull images."

**Comment by stefwalter** [comment]
@aweiteka Could you include a screenshot of where you would imagine this to fit well?

**Comment by aweiteka** [comment]
What I'm missing is access control at this view, looking at all images in a project, which share the same access control.

<img width="1078" alt="screen shot 2016-10-17 at 1 50 11 pm" src="https://cloud.githubusercontent.com/assets/1764461/19448660/c944e0ba-9470-11e6-9e72-e4d04b8e7c91.png">

I think we want the same edit Access Control link we provide at the imagestream level:

<img width="1079" alt="screen shot 2016-10-17 at 1 52 59 pm" src="https://cloud.githubusercontent.com/assets/1764461/19448762/287e1772-9471-11e6-9de1-26167e92ef6f.png">

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
