### ISSUE TITLE
100% CPU usage when password reset on fedora-atomic

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#4962]
Here's what I'm doing, and it's resulting in cockpit-ws hanging with full CPU usage:

*For anyone else following along, workaround is to first ```test/verify/testsuite-prepare```*

 * Start fedora-atomic with ```test/vm-run fedora-atomic```
 * Start cockpit in the instance: ```/usr/bin/docker run -d --privileged --pid=host -v /:/host cockpit/ws /container/atomic-run --local-ssh --no-tls```
 * Expire the password for *admin*: ```chage -d 0 admin```
 * Enable ```ChallengeResponse``` authentication in ```/etc/ssh/sshd_config```
 * Restart sshd ```systemctl restart sshd```
 * Log into Cockpit UI

And we don't log in and get a hang. 

I cannot reproduce this on my own machine running ```cockpit-ws``` manually with ```--local-ssh```.

We absolutely need a test for this functionality even if it's expected to only work with ```--local-ssh```.

**Comment by petervo** [comment]
@stefwalter are you sure are testing with an up to date image? you have to run testsuite-prepare otherwise the image in there is old and doesn't have this feature.

**Comment by stefwalter** [comment]
OK. Verified that this works with ```./testsuite-prepare``` and added above to the instructions.

This is a real issue then, but it was fixed with https://github.com/cockpit-project/cockpit/pull/4827
