### ISSUE TITLE
RHEL: Docker + SELinux completely broken in 7.3 beta

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#4978]
No containers start due to SELinux breakage:

https://bugzilla.redhat.com/show_bug.cgi?id=1373430

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 81, in testBasic
    b.wait_popdown("containers_run_image_dialog")
  File "testlib.py", line 266, in wait_popdown
    self.wait_not_visible('#' + id)
  File "testlib.py", line 238, in wait_not_visible
    return self.wait_js_func('!ph_is_visible', selector)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 682, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 705, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-09-07T10:49:08.251617 | revision 9ac02c543d5653248d566d284ad1b0bd34a85b1a, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4975-9ac02c54-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-07T10:49:08.251617 | revision 9ac02c543d5653248d566d284ad1b0bd34a85b1a, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4975-9ac02c54-verify-rhel-7/log.html)

**Comment by stefwalter** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 88, in testBasic
    self.wait_for_message(message)
  File "check-docker", line 56, in wait_for_message
    b.wait_in_text("#container-terminal", message)
  File "testlib.py", line 241, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 685, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 708, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-09-09T20:36:58.388788 | revision 3b58e72912556718b848920e0ce56e9e2f3f8dd9, [logs](http://stefw.fedorapeople.org/logs/pull-3b58e729-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-09T20:36:58.388788 | revision 3b58e72912556718b848920e0ce56e9e2f3f8dd9, [logs](http://stefw.fedorapeople.org/logs/pull-3b58e729-verify-fedora-25/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 651, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1474374352.815:4): avc:  denied  { search } for  pid=1475 comm="systemd-machine" name="1467" dev="proc" ino=27296 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir
```
First occurrence: 2016-09-20T12:26:09.840755 | revision 9d84690b337503222407717d15914b3a90da23d2, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5070-9d84690b-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-20T12:26:09.840755 | revision 9d84690b337503222407717d15914b3a90da23d2, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5070-9d84690b-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 654, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1476888370.103:4): avc:  denied  { transition } for  pid=1616 comm="exe" path="/usr/bin/pod" dev="dm-1" ino=6385664 scontext=system_u:system_r:unconfined_service_t:s0 tcontext=system_u:system_r:svirt_lxc_net_t:s0:c104,c479 tclass=process
```
First occurrence: 2016-10-19T14:46:26.867317 | revision e419bee38b3bfc33fee5fc2344aed29ffb288873, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5182-e419bee3-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-10-19T14:46:26.867317 | revision e419bee38b3bfc33fee5fc2344aed29ffb288873, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5182-e419bee3-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 655, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1477487221.284:4): avc:  denied  { transition } for  pid=1616 comm="exe" path="/usr/bin/pod" dev="dm-1" ino=6385664 scontext=system_u:system_r:unconfined_service_t:s0 tcontext=system_u:system_r:svirt_lxc_net_t:s0:c31,c820 tclass=process
```
First occurrence: 2016-10-26T13:07:18.254893 | revision 4bd9241cff783ec86d42cad5a9033a0f2b99291d, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5238-4bd9241c-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-10-26T13:07:18.254893 | revision 4bd9241cff783ec86d42cad5a9033a0f2b99291d, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5238-4bd9241c-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "kubelib.py", line 413, in testDashboard
    b.wait_text("#service-list tr[data-name='mock']:first-of-type td.containers", "1")
  File "testlib.py", line 247, in wait_text
    return self.wait_js_func('ph_text_is', selector, text)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 695, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 718, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-11-03T11:28:11.833577 | revision 51cbf00b1fae1de6abcf03b39aa163b25ac7863e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5285-51cbf00b-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-11-03T11:28:11.833577 | revision 51cbf00b1fae1de6abcf03b39aa163b25ac7863e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5285-51cbf00b-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 238, in testExpose
    b.wait_popdown("containers_run_image_dialog")
  File "testlib.py", line 266, in wait_popdown
    self.wait_not_visible('#' + id)
  File "testlib.py", line 238, in wait_not_visible
    return self.wait_js_func('!ph_is_visible', selector)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 705, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 728, in _invoke
    raise Error(res['error'])
Error: timeout
Container command could not be invoked.
```
First occurrence: 2016-11-07T10:55:47.293230 | revision af84e3f2dcdefd10216226deb60c12a4e8e083af, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5315-af84e3f2-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-11-07T10:55:47.293230 | revision af84e3f2dcdefd10216226deb60c12a4e8e083af, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5315-af84e3f2-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 397, in testRestart
    b.wait_popdown("containers_run_image_dialog")
  File "testlib.py", line 267, in wait_popdown
    self.wait_not_visible('#' + id)
  File "testlib.py", line 239, in wait_not_visible
    return self.wait_js_func('!ph_is_visible', selector)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 712, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 735, in _invoke
    raise Error(res['error'])
Error: timeout
Container command could not be invoked.
```
First occurrence: 2016-11-09T05:43:12.210740 | revision c6bdd0a491310385bfe49763d7dfe72e4ed92e2c, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5322-c6bdd0a4-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-11-09T05:43:12.210740 | revision c6bdd0a491310385bfe49763d7dfe72e4ed92e2c, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5322-c6bdd0a4-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 530, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 668, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1478779201.926:4): avc:  denied  { transition } for  pid=1622 comm="exe" path="/usr/bin/pod" dev="dm-1" ino=6385664 scontext=system_u:system_r:unconfined_service_t:s0 tcontext=system_u:system_r:svirt_lxc_net_t:s0:c249,c510 tclass=process
```
First occurrence: 2016-11-10T12:00:19.221273 | revision 172c40348df391d3c44651509f22c7389b29acd7, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5342-172c4034-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-11-10T12:00:19.221273 | revision 172c40348df391d3c44651509f22c7389b29acd7, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5342-172c4034-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 531, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 669, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1479116716.936:4): avc:  denied  { transition } for  pid=1624 comm="exe" path="/usr/bin/pod" dev="dm-1" ino=6385664 scontext=system_u:system_r:unconfined_service_t:s0 tcontext=system_u:system_r:svirt_lxc_net_t:s0:c23,c791 tclass=process
```
First occurrence: 2016-11-14T09:45:22.446223 | revision 173a835ce075e7220cfc1ffd581af22c3754c500, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5387-173a835c-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-11-14T09:45:22.446223 | revision 173a835ce075e7220cfc1ffd581af22c3754c500, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5387-173a835c-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 81, in testBasic
    b.wait_popdown("containers_run_image_dialog")
  File "testlib.py", line 272, in wait_popdown
    self.wait_not_visible('#' + id)
  File "testlib.py", line 244, in wait_not_visible
    return self.wait_js_func('!ph_is_visible', selector)
  File "testlib.py", line 214, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 717, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 740, in _invoke
    raise Error(res['error'])
Error: timeout
Cannot start container c372539e3a92d30bc851c0c26377705c9a5d2935b10f6f7d2e2214d10f3e6a6a: [9] System error: invalid character ',' looking for beginning of value
```
First occurrence: 2016-11-16T16:51:27.389346 | revision f1c28d6018244618bcc29b7e90869556012ab222, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5409-f1c28d60-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-11-16T16:51:27.389346 | revision f1c28d6018244618bcc29b7e90869556012ab222, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5409-f1c28d60-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "kubelib.py", line 623, in testTopology
    b.wait_text("#service-list tr[data-name='mock'] td.containers", "1")
  File "testlib.py", line 253, in wait_text
    return self.wait_js_func('ph_text_is', selector, text)
  File "testlib.py", line 214, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 717, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 740, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-11-19T01:49:56.550218 | revision 739c4fa0b64fb3880f8d2a607e0d755b0313f157, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5435-739c4fa0-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-11-19T01:49:56.550218 | revision 739c4fa0b64fb3880f8d2a607e0d755b0313f157, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5435-739c4fa0-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 248, in testExpose
    b.wait_popdown("containers_run_image_dialog")
  File "testlib.py", line 270, in wait_popdown
    self.wait_not_visible('#' + id)
  File "testlib.py", line 242, in wait_not_visible
    return self.wait_js_func('!ph_is_visible', selector)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 745, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 771, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-05-15T09:42:18.013117 | revision 359122f0cc492d1416e105e532b02498de2a620a, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6554-359122f0-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2017-05-15T09:42:18.013117 | revision 359122f0cc492d1416e105e532b02498de2a620a, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6554-359122f0-verify-rhel-7/log.html)
