### ISSUE TITLE
RHEL: SELinux prevents NetworkManager from removing resolv.conf

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#4980]
https://bugzilla.redhat.com/show_bug.cgi?id=1373882

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 648, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1473248899.591:4): avc:  denied  { unlink } for  pid=463 comm="NetworkManager" name="resolv.conf" dev="vda3" ino=11215282 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=unconfined_u:object_r:etc_t:s0 tclass=file
```
First occurrence: 2016-09-07T11:48:33.119309 | revision c2b654899f1424d0186ca5e73f26e7fea65627a4, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4981-c2b65489-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-07T11:48:33.119309 | revision c2b654899f1424d0186ca5e73f26e7fea65627a4, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4981-c2b65489-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 654, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1476363973.179:4): avc:  denied  { unlink } for  pid=513 comm="NetworkManager" name="resolv.conf" dev="vda3" ino=9404865 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=unconfined_u:object_r:etc_t:s0 tclass=file
```
First occurrence: 2016-10-13T13:08:12.182608 | revision cd448628a519bff5a595c58198177d732ccfc7f7, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5097-cd448628-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-10-13T13:08:12.182608 | revision cd448628a519bff5a595c58198177d732ccfc7f7, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5097-cd448628-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 527, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 655, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1478021480.186:4): avc:  denied  { unlink } for  pid=509 comm="NetworkManager" name="resolv.conf" dev="vda3" ino=8888516 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=unconfined_u:object_r:etc_t:s0 tclass=file
```
First occurrence: 2016-11-01T17:33:01.506831 | revision 11e52440b295eddca53d94f0f4576bf98f40a828, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5097-11e52440-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-11-01T17:33:01.506831 | revision 11e52440b295eddca53d94f0f4576bf98f40a828, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5097-11e52440-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-realms", line 218, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 538, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 676, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1481533909.293:4): avc:  denied  { unlink } for  pid=518 comm="NetworkManager" name="resolv.conf" dev="vda3" ino=4463045 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=unconfined_u:object_r:etc_t:s0 tclass=file
```
First occurrence: 2016-12-12T09:12:47.967682 | revision d28cd2be11caddff4df2edea8652f531d9085e30, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5580-d28cd2be-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-12-12T09:12:47.967682 | revision d28cd2be11caddff4df2edea8652f531d9085e30, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5580-d28cd2be-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-realms", line 218, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 538, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 676, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1482129781.662:4): avc:  denied  { unlink } for  pid=516 comm="NetworkManager" name="resolv.conf" dev="vda3" ino=5160755 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=unconfined_u:object_r:etc_t:s0 tclass=file
```
First occurrence: 2016-12-19T06:44:14.872552 | revision cf743a83e89eedb11acb7d850c9c026307f3ebad, [logs](http://fedorapeople.org/groups/cockpit/logs/master-cf743a83-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-12-19T06:44:14.872552 | revision cf743a83e89eedb11acb7d850c9c026307f3ebad, [logs](http://fedorapeople.org/groups/cockpit/logs/master-cf743a83-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-realms", line 218, in tearDown
    MachineCase.tearDown(self)
  File "testlib.py", line 538, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 679, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1483598020.415:4): avc:  denied  { unlink } for  pid=518 comm="NetworkManager" name="resolv.conf" dev="vda3" ino=5082110 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=unconfined_u:object_r:etc_t:s0 tclass=file
```
First occurrence: 2017-01-05T06:34:39.707643 | revision 198598850b26482f14f79d4a234a44f72f89b179, [logs](http://fedorapeople.org/groups/cockpit/logs/master-19859885-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2017-01-05T06:34:39.707643 | revision 198598850b26482f14f79d4a234a44f72f89b179, [logs](http://fedorapeople.org/groups/cockpit/logs/master-19859885-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 533, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 674, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1484125252.256:4): avc:  denied  { unlink } for  pid=516 comm="NetworkManager" name="resolv.conf" dev="vda3" ino=4568447 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=unconfined_u:object_r:etc_t:s0 tclass=file
```
First occurrence: 2017-01-11T09:00:57.652096 | revision 0f595c8b5ce6c8b1d03ab6bf2ffce54eafd8d7fa, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5338-0f595c8b-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2017-01-11T09:00:57.652096 | revision 0f595c8b5ce6c8b1d03ab6bf2ffce54eafd8d7fa, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5338-0f595c8b-verify-rhel-7/log.html)

**Comment by stefwalter** [comment]
Test comment.

**Comment by martinpitt** [comment]
Indeed the bots haven't encountered this issue since January. But the downstream bug got no developer response, and I don't see anything in RHEL dist-git that would indicate a change there, so this could just be sheer luck. Let's keep this open for another round.

**Comment by martinpitt** [comment]
Obsolete for a long time.
