### ISSUE TITLE
storage tooltips are unpredictable

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#4984]
As a followup to #4963
In some cases, the tooltips for Physical Volumes gets the wrong style.
So instead of looking like this:
![screenshot from 2016-09-07 18-10-12](https://cloud.githubusercontent.com/assets/209895/18319529/65f5f198-7526-11e6-9ab7-9f53f61f5cf4.png)

They look like this:
![screenshot from 2016-09-07 18-09-06](https://cloud.githubusercontent.com/assets/209895/18319567/8cb333c2-7526-11e6-9e0c-ab4487adf8e5.png)

The most predictable way of triggering the wrong style is to
- Have two Volume Groups
- Dive in to the first volume group and hover a button there.
- Go up to the storage page
- Dive in to the second volume group
- Hover a button

The button in the first volume group will display a correct tooltip, the one in the second volume group will not. Also the reverse is true if you go into the second volume group first.
It does not seem to trigger the wrong tooltip on the buttons in the second volume group if the button in the first volume group is never hovered.

**Comment by mvollmer** [comment]
I plan to fix this by reactifying the physical volumes panel and using our own reactish tooltip implementation.
