### ISSUE TITLE
SELinux context of fstab changed

### ISSUE THREAD

**Issue by Derek123456** [cockpit-project/cockpit#4999]
I recently did a fresh install of Fedora Core 24 which came with Cockpit.
I logged into Cockpit and mounted a usb drive using the interface:
![1](https://cloud.githubusercontent.com/assets/22090809/18374988/5ac19d86-7684-11e6-9305-4c19b5492834.png)

When I rebooted the machine I got an SELinux permission error. 

dmesg output:

`[    5.774566] audit: type=1400 audit(1473392161.629:42): avc:  denied  { read } for  pid=571 comm="systemd-fstab-g" name="fstab" dev="dm-0" ino=16797806 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:lvm_metadata_t:s0 tclass=file permissive=0
[    5.774611] audit: type=1300 audit(1473392161.629:42): arch=c000003e syscall=2 success=no exit=-13 a0=55a2762f900e a1=80000 a2=1b6 a3=0 items=0 ppid=567 pid=571 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-fstab-g" exe="/usr/lib/systemd/system-generators/systemd-fstab-generator" subj=system_u:system_r:init_t:s0 key=(null)
[    5.774631] audit: type=1327 audit(1473392161.629:42): proctitle=2F7573722F6C69622F73797374656D642F73797374656D2D67656E657261746F72732F73797374656D642D66737461622D67656E657261746F72002F72756E2F73797374656D642F67656E657261746F72002F72756E2F73797374656D642F67656E657261746F722E6561726C79002F72756E2F73797374656D642F67656E65
[    5.774661] systemd-fstab-generator[571]: Failed to open /etc/fstab: Permission denied`

It appears that cockpit is changing the context of fstab from **system_u:system_r:init_t:s0** to **system_u:object_r:lvm_metadata_t:s0** which means that fstab can't be accessed by the system. 

This results in none of the mount points working, the main / directory gets mounted as read only and because / is read only cockpit fails to load.

`remotectl: couldn't set certificate permissions: /etc/cockpit/ws-certs.d/0-self-signed.cert: Read-only file system`

I resolved this issue by manually logging in, remount as read/write then restoring the Selinux context:

```
[root@localhost etc]# mount -o rw,remount /
[root@localhost etc]# ls -alZ /etc/fstab
-rw-r--r--. 1 root root system_u:object_r:lvm_metadata_t:s0 602 Sep  9 14:05 /etc/fstab
[root@localhost etc]# restorecon /etc/fstab
[root@localhost etc]# ls -alZ /etc/fstab
-rw-r--r--. 1 root root system_u:object_r:etc_t:s0 602 Sep  9 14:05 /etc/fstab
```

However any changes I make to the storage system using Cockpit result in the context being changed back which causes the same problem again.

**Comment by skutov** [comment]
I also have this issue, just spent the best part of 3 hours trying to find out why my laptop wasn't booting. I can provide further details of needed to diagnose the issue.

**Comment by petervo** [comment]
@skutov did you also use cockpit to mount a usb disk? Or did you get your system in this state a different way?

**Comment by mvollmer** [comment]
The culprit would be storaged, I think.

**Comment by skutov** [comment]
@petervo I had set an LVM volume to me mounted as a part of the boot process.

**Comment by AHelper** [comment]
I just had this happen to me. Same avc denial as above, fstab got relabelled as kvm_metadata_t.

Last thing I did in cockpit was create a new LVM thin partition, format, and set mount point.

**Comment by nolange** [comment]
I ran into this issue, but because I use a read-only root filesystem on purpose.
Would be great if `set_cert_attributes` only does modifications if those are necessary.

**Comment by mvollmer** [comment]
We haven't figure out how to reproduce this, unfortunately.  Please open if this still happens.
