### ISSUE TITLE
"User name" field no longer selected by default on login screen

### ISSUE THREAD

**Issue by AdamWill** [cockpit-project/cockpit#5000]
Up until cockpit 118, when you land on the cockpit login screen, the "User name" field is pre-selected and you can just start typing the user name. With cockpit 118 (in Fedora Rawhide), it is not: you have to click the field or hit tab before you can type the user name.

**Comment by AdamWill** [comment]
looks like https://github.com/cockpit-project/cockpit/pull/4991 fixed this already.

**Comment by stefwalter** [comment]
Thanks @AdamWill and congratulations on #5000 :)

I also added a regression test for this, making sure the expected behavior sticks.
