### ISSUE TITLE
Fedora, RHEL, CentOS: SELinux prevents password expiry reset from working

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#5010]
https://bugzilla.redhat.com/show_bug.cgi?id=1374262
https://bugzilla.redhat.com/show_bug.cgi?id=1374572

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-login", line 164, in testExpired
    b.wait_in_text("#conversation-prompt", "Retype")
  File "testlib.py", line 241, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 682, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 705, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-09-09T08:35:19.170204 | revision eadf162c16fd40e9a9026c5383ace48219d259ad, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4993-eadf162c-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-09T08:35:19.170204 | revision eadf162c16fd40e9a9026c5383ace48219d259ad, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4993-eadf162c-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-login", line 164, in testExpired
    b.wait_in_text("#conversation-prompt", "Retype")
  File "testlib.py", line 241, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 682, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 705, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-09-09T08:39:19.058787 | revision eadf162c16fd40e9a9026c5383ace48219d259ad, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4993-eadf162c-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-09T08:39:19.058787 | revision eadf162c16fd40e9a9026c5383ace48219d259ad, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4993-eadf162c-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/centos-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-login", line 164, in testExpired
    b.wait_in_text("#conversation-prompt", "Retype")
  File "testlib.py", line 241, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 682, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 705, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-09-09T08:46:25.911778 | revision eadf162c16fd40e9a9026c5383ace48219d259ad, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4993-eadf162c-verify-centos-7/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-09T08:46:25.911778 | revision eadf162c16fd40e9a9026c5383ace48219d259ad, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-4993-eadf162c-verify-centos-7/log.html)

**Comment by stefwalter** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-login", line 164, in testExpired
    b.wait_in_text("#conversation-prompt", "Retype")
  File "testlib.py", line 241, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 685, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 708, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-09-09T20:37:15.299627 | revision 3b58e72912556718b848920e0ce56e9e2f3f8dd9, [logs](http://stefw.fedorapeople.org/logs/pull-3b58e729-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-09T20:37:15.299627 | revision 3b58e72912556718b848920e0ce56e9e2f3f8dd9, [logs](http://stefw.fedorapeople.org/logs/pull-3b58e729-verify-fedora-25/log.html)

**Comment by cockpituous** [comment]
verify/fedora-23
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-login", line 164, in testExpired
    b.wait_in_text("#conversation-prompt", "Retype")
  File "testlib.py", line 241, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 685, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 708, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2016-10-07T12:39:33.055323 | revision 11aeb5e4340ce259bcced447e8951333283cb827, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5130-11aeb5e4-verify-fedora-23/log.html)
Times recorded: 1
Latest occurrences:

- 2016-10-07T12:39:33.055323 | revision 11aeb5e4340ce259bcced447e8951333283cb827, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5130-11aeb5e4-verify-fedora-23/log.html)
