### ISSUE TITLE
Disable power options

### ISSUE THREAD

**Issue by sebastianwebber** [cockpit-project/cockpit#5022]
Hi There,

it's possible disable the 'reboot' button on the system dashboard? How can I do that?

Thanks

**Comment by nbluis** [comment]
NIce, good point.
Maybe some way to use read-only would be perfect in my view.

**Comment by dperpeet** [comment]
Cockpit is a thin layer on top of already exposed APIs, as such it is placed in the visualization layer. If you want to disable the reboot functionality for a subset of users, then you basically need to disable that feature for them, i.e. if they were logged in via ssh, they couldn't reboot.

Beyond that, I'm not sure if we could detect in the ui whether the user is allowed to reboot a system. In some places Cockpit disables buttons if the user doesn't have the right permissions, but that isn't the case with the power options. What do you think, @andreasn @mvollmer - would that be technically possible in the case and make sense from a UX-perspective?

**Comment by mvollmer** [comment]
> What do you think, @andreasn @mvollmer - would that be technically possible in the case and make sense from a UX-perspective?

I think it makes complete sense.  We already disable a lot of buttons when the user is not root/wheel, and we can do the same here, if that reflects reality.

I don't think we do proper polkit checks for more fine grained permissions, and maybe this is the first case where it actually matters...

**Comment by andreasn** [comment]
From a UX perspective, simply disabling the button and showing a tooltip that you're not authorized to do that sounds like a good call, and consistent with what we do elsewhere in Cockpit.

**Comment by dperpeet** [comment]
> I think it makes complete sense. We already disable a lot of buttons when the user is not root/wheel, and we can do the same here, if that reflects reality.
> 
> I don't think we do proper polkit checks for more fine grained permissions, and maybe this is the first case where it actually matters...

I agree - I tried this as a regular user earlier and I had to go through all the motions to try and reboot a system, only for that to fail with `shutdown exited with code 1`.

Performance Profile also shows an error as regular user right now.

**Comment by andreasn** [comment]
> I agree - I tried this as a regular user earlier and I had to go through all the motions to try and reboot a system, only for that to fail with shutdown exited with code 1.

Yeah, that sounds wrong, and we should be able to predict that earlier, hence disabling the button.
Is there any difference in permission between rebooting and powering off a machine?
