### ISSUE TITLE
Storage graphs don't work

### ISSUE THREAD

**Issue by sebastianwebber** [cockpit-project/cockpit#5023]
Hi there!

After installing the cockpit on my new centos 7 server, the storage graphs (Reading and Writing b/s) don't show anything, see:

![image](https://cloud.githubusercontent.com/assets/2515929/18406889/2092fd0c-76da-11e6-8fe5-27a5071d68ef.png)

There is some configuration to do?

The `I/O Disk` dashboard works fine, see:

![image](https://cloud.githubusercontent.com/assets/2515929/18406896/4a510850-76da-11e6-9d83-2deeea4c2ebe.png)

**Comment by mvollmer** [comment]
> There is some configuration to do?

No, it should just work.

**Comment by mvollmer** [comment]
Confirmed, the graphs stay empty when PCP is not used.

**Comment by sebastianwebber** [comment]
> Confirmed, the graphs stay empty when PCP is not used.

It's a bug? Any workaround recommended?

**Comment by mvollmer** [comment]
> It's a bug? Any workaround recommended?

It's a bug. :-) I let you know when I know more.

**Comment by mvollmer** [comment]
Okay, there might be a bug in the way we handle the fallback from PCP to the internal samplers.

To explain: Cockpit tries to uses the Performance Co Pilot (PCP) to gather all kinds of metrics.  However, if PCP is not installed or not available for other reasons, Cockpit falls back on some simple internal metric samplers.

Cockpit only falls back to the internal samplers when PCP is clearly not there.  If the code crashes or otherwise misbehaves in unexpected ways, you will end up with empty plots, and a message in the developer console.

This is likely what is happening to you.  Can you check the Browser console for messages?  You should be able to open it with Control-Shift-K or somewhere from a menu.

You probably want to install the `cockpit-pcp` package so that Cockpit uses PCP (Log out from Cockpit and in again after that).  This will hopefully just work.  However, the fallback should still work, so it would be great if you could help debug that as well.

(When I tested this earlier, I just did `chmod a-x /usr/libexec/cockpit-pcp`, which Cockpit treats as a broken setup, and it doesn't trigger the fallback.  `rm /usr/libexec/cockpit-pcp` on the other hand works as expected.)

**Comment by sebastianwebber** [comment]
> This is likely what is happening to you. Can you check the Browser console for messages? You should be able to open it with Control-Shift-K or somewhere from a menu.

I can't see any message on the console of the browser (I tried on chrome and safari). =/

> You probably want to install the cockpit-pcp package so that Cockpit uses PCP (Log out from Cockpit and in again after that). This will hopefully just work. However, the fallback should still work, so it would be great if you could help debug that as well.

Indeed.  I installed the `cockpit-pcp` but it don't change anything. I tried to restart the `cockpit service` and nothing changes. I'm doing something wrong here?

BTW, this are all the cockpit packages installed on my server:

```
[root@server ~]# rpm -qa | grep  cockpit
cockpit-bridge-0.114-2.el7.centos.x86_64
cockpit-docker-0.114-2.el7.centos.x86_64
cockpit-ws-0.114-2.el7.centos.x86_64
cockpit-shell-0.114-2.el7.centos.noarch
cockpit-storaged-0.114-2.el7.centos.noarch
cockpit-pcp-0.114-2.el7.centos.x86_64
cockpit-0.114-2.el7.centos.x86_64
```

I could not find anything useful on the logs:

```
[root@server ~]# grep cockpit /var/log/messages
Sep 13 11:41:50 server cockpit-ws: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Sep 13 11:42:04 server cockpit-session: pam_ssh_add: Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
Sep 13 11:42:04 server cockpit-ws: logged in user: root
Sep 13 11:42:10 server cockpit-ws: New connection from ::1 for root
Sep 13 11:42:32 server cockpit-ws: WebSocket from ::1 for root closed
Sep 13 11:42:40 server cockpit-ws: New connection from ::1 for root
Sep 13 11:43:42 server yum[44444]: Installed: cockpit-pcp-0.114-2.el7.centos.x86_64
Sep 13 11:44:05 server cockpit-ws: Logging out user root from ::1
Sep 13 11:44:05 server cockpit-ws: WebSocket from ::1 for root closed
Sep 13 11:44:19 server cockpit-session: pam_ssh_add: Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
Sep 13 11:44:19 server cockpit-ws: logged in user: root
Sep 13 11:44:23 server cockpit-ws: New connection from ::1 for root
Sep 13 11:45:45 server cockpit-ws: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Sep 13 11:46:15 server cockpit-session: pam_ssh_add: Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
Sep 13 11:46:15 server cockpit-ws: logged in user: root
Sep 13 11:46:17 server cockpit-ws: New connection from ::1 for root
Sep 13 11:47:11 server cockpit-ws: WebSocket from ::1 for root closed
Sep 13 11:47:13 server cockpit-ws: New connection from ::1 for root
Sep 13 11:48:26 server cockpit-pcp: pcp-archive: no such metric: network.interface.in.bytes: Unknown metric name
Sep 13 11:48:26 server cockpit-pcp: pcp-archive: no such metric: network.interface.out.bytes: Unknown metric name
Sep 13 11:49:05 server cockpit-session: pam_ssh_add: Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
Sep 13 11:49:05 server cockpit-ws: logged in user: root
Sep 13 11:49:14 server cockpit-ws: New connection from ::1 for root
Sep 13 11:50:25 server cockpit-ws: connection unexpectedly closed by peer
Sep 13 11:50:25 server cockpit-ws: WebSocket from ::1 for root closed
Sep 13 11:50:26 server cockpit-ws: New connection from ::1 for root
Sep 13 11:50:45 server cockpit-ws: connection unexpectedly closed by peer
Sep 13 11:50:45 server cockpit-ws: WebSocket from ::1 for root closed
Sep 13 11:50:46 server cockpit-ws: New connection from ::1 for root
Sep 13 11:54:00 server cockpit-ws: Logging out user root from ::1
Sep 13 11:54:00 server cockpit-ws: WebSocket from ::1 for root closed
Sep 13 11:54:11 server cockpit-session: pam_ssh_add: Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
Sep 13 11:54:11 server cockpit-ws: logged in user: root
Sep 13 11:54:12 server cockpit-ws: New connection from ::1 for root
Sep 13 11:56:10 server cockpit-ws: 10.0.1.101: ssh-ed25519 host key for server is not known: d2:59:3f:9d:61:a6:fc:21:55:d4:34:b8:51:23:90:01
Sep 13 12:00:44 server cockpit-ws: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Sep 13 12:00:55 server cockpit-session: pam_ssh_add: Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
Sep 13 12:00:55 server cockpit-ws: logged in user: root
Sep 13 12:00:58 server cockpit-ws: New connection from ::1 for root
Sep 13 12:01:30 server cockpit-ws: Logging out user root from ::1
Sep 13 12:01:31 server cockpit-ws: WebSocket from ::1 for root closed
```

Any ideas?

**Comment by martinpitt** [comment]
This is obsolete now, as the storage graphs got removed entirely.

**Comment by mvollmer** [comment]
> This is obsolete now, as the storage graphs got removed entirely.

No, we only removed the textual I/O rates in the "Drives" panel, the plots are still there.

**Comment by mvollmer** [comment]
But, I am afraid this is obsolete now.  Sorry for dropping the ball on this.  Please reopen if this still happens.
