### ISSUE TITLE
Fedora: SELinux prevents systemd from dumping core

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#5027]
https://bugzilla.redhat.com/show_bug.cgi?id=1365435

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-connection", line 99, in testBasic
    wait(lambda: m.execute("journalctl -b | grep 'Process.*cron.*of user.*dumped core.'"))
  File "testlib.py", line 1101, in wait
    val = func()
  File "check-connection", line 99, in <lambda>
    wait(lambda: m.execute("journalctl -b | grep 'Process.*cron.*of user.*dumped core.'"))
  File "testvm.py", line 412, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'journalctl -b | grep 'Process.*cron.*of user.*dumped core.'' returned non-zero exit status 1
```
First occurrence: 2016-09-13T12:43:27.446058 | revision e6e16df8352f6458265c620af3a351efaed50023, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5018-e6e16df8-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-13T12:43:27.446058 | revision e6e16df8352f6458265c620af3a351efaed50023, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5018-e6e16df8-verify-fedora-25/log.html)

**Comment by stefwalter** [comment]
verify/fedora-atomic
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-connection", line 114, in testBasic
    self.assertNotEqual(cores, "")
AssertionError: '' == ''
```
First occurrence: 2016-12-19T16:33:57.766448
Times recorded: 1
Latest occurrences:

- 2016-12-19T16:33:57.766448

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-connection", line 112, in testBasic
    self.assertNotEqual(cores, "")
AssertionError: '' == ''
```
First occurrence: 2017-01-31T11:41:12.813242 | revision 658a9f229efc2cc7c8bc0f03c76b59a0e24ee1f2, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5822-658a9f22-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2017-01-31T11:41:12.813242 | revision 658a9f229efc2cc7c8bc0f03c76b59a0e24ee1f2, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5822-658a9f22-verify-fedora-testing/log.html)
