### ISSUE TITLE
Fedora 25: SELinux prevents storaged from working

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#5041]
The storaged daemon is completely broken on Fedora 25 due to SELinux preventing it from starting, registering on DBus, and so on.

https://bugzilla.redhat.com/show_bug.cgi?id=1375156

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-storage-iscsi", line 70, in testISCSI
    b.wait_visible('[data-action="edit-iscsi"]')
  File "testlib.py", line 226, in wait_visible
    return self.wait_js_func('ph_is_visible', selector)
  File "testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 685, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 708, in _invoke
    raise Error(res['error'])
Error: [data-action="edit-iscsi"] not found
```
First occurrence: 2016-09-13T09:36:11.536334 | revision 5a0bb029611f09c77d4e70183d956d59e6d85d47, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5018-5a0bb029-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2016-09-13T09:36:11.536334 | revision 5a0bb029611f09c77d4e70183d956d59e6d85d47, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5018-5a0bb029-verify-fedora-25/log.html)
