### ISSUE TITLE
Graphs not displayed in Cockpit Kubernetes dashboard

### ISSUE THREAD

**Issue by praoreo** [cockpit-project/cockpit#5054]
Hi,

I have 1 kubernetes master and 2 worker nodes running in my lab. Cockpit-kubernetes dashboard is running as a docker container on master.

`
docker run --env-file=test.env --net=host --rm -it cockpit/kubernetes:latest`

Dashboard is accessible and I am able to deploy services and associated pods on worker nodes. But the graphical view of CPU/Memory/Bandwidth utilization seems to be not working. We are running "stress" command within the deployed container to increase the CPU utilization. And could notice that CPU utilization under Nodes->Capacity is reflecting correctly. However the graph in Overview page is not reflecting the usage.

I am using Kubernetes version 1.3.6 and docker version 1.12.

```
root@tbserver3:/home/tbserver3# kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:06:06Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

root@controller:/home/tbserver1# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

```

cadvisor is deployed as a pod on all the worker node using dashboard. 
I am able to access it from master node as shown below.

```
root@tbserver3:/home/tbserver3# wget http://XXX.XX.XX.X:4194/api/v1.2/docker
--2016-09-15 14:18:30--  http://XXX.XX.XX.X:4194/api/v1.2/docker
Connecting to XXX.XX.XX.X:4194... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘docker.1’

    [ <=>                                                                                        ] 179,702     --.-K/s   in 0.001s

2016-09-15 14:18:30 (147 MB/s) - ‘docker.1’ saved [179702]
```

**Comment by marusak** [comment]
Long time no update and also we dropped kubernetes from master. If this happens on some specific donwstream release, please report into appropriate bug tracker.

Thank you.
