### ISSUE TITLE
add machine on dashboard without ssh port exposed

### ISSUE THREAD

**Issue by vanloswang** [cockpit-project/cockpit#5063]
I have a machine which is not exposed any ssh port, and I want to add it to another Cockpit dashboard. This machine is exposed port 9090 which Cockpit ws use.  
Is there a way to add machine without ssh started and ssh port exposed, just with Cockpit started and 9090 exposed?

**Comment by petervo** [comment]
No, ATM cockpit only supports adding secondary machines that can be connected to via ssh.

**Comment by dperpeet** [comment]
I think this issue can be closed. For changes to this fundamental decision, I propose writing up a wiki page with concrete goals, requirements and ideas how to implement.
