### ISSUE TITLE
Container memory usage

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#5065]
Docker includes cache in it's memory.usage_in_bytes numbers so our graphs can can continue to grow making it look like there is a memory leak when there isn't. Should we subtract the cache from the total numbers? Or should we add a visual representation to clarify what is cache and available to be reclaimed by the system and what is actually in use by the process.

**Comment by petervo** [comment]
Reference issues.

https://github.com/docker/docker/issues/10824
https://github.com/docker/libcontainer/pull/518

**Comment by dperpeet** [comment]
I think adding a visual representation to clarify the distinction would be good, but in any case the amount of memory used without caching is more important.
Why I don't think we should hide cache info completely: That might suggest that docker isn't using memory, even when it is.

**Comment by larskarlitski** [comment]
This might still be useful, even though it's an old bug.

@garrett, what do we do on the system page? Do we show cache separately?

**Comment by garrett** [comment]
Yes! As of https://github.com/cockpit-project/cockpit/pull/10282 (2018-10-31), Cockpit:
1. Doesn't show cache on the overview
2. Shows cache separately on the details graph, with optimized colors and placement, as to not emphasize cache

Details @ https://cockpit-project.org/blog/cockpit-181.html

I think the new(ish) visualization of RAM helps address this issue (and others), so I'm closing it.

Please reopen if you think I'm wrong. :wink:
