### ISSUE TITLE
Networkmanager requirement

### ISSUE THREAD

**Issue by xrow** [cockpit-project/cockpit#5066]
Hi,

in https://github.com/cockpit-project/cockpit/pull/1555 you had added networkmanager as a hard requirement. In https://github.com/cockpit-project/cockpit/blob/master/doc/guide/feature-networkmanager.xml you state that it is optional. What  is the right case though?

We have the feeling that networkmanager should optional. Managing Network connections of a running server sounds scary anyway. 

In any case. We wanted you just to give you this hint. Maybe there is no action required.

**Comment by mvollmer** [comment]
The current Network UI in Cockpit requires NetworkManager, but the whole UI is optional.

On Fedora at least, it is possible to just uninstall cockpit-networkmanager and the Network UI should go away.

**Comment by mvollmer** [comment]
> We have the feeling that networkmanager should optional. Managing Network connections of a running server sounds scary anyway. 

Well, don't do it, then! :-)

We are working on checkpoints to make this somewhat less dangerous: https://github.com/cockpit-project/cockpit/pull/5069
