### ISSUE TITLE
please revert https://github.com/cockpit-project/cockpit/commit/03f31d3ef17b39d23294a413b8c792bbdc4f2629

### ISSUE THREAD

**Issue by doverride** [cockpit-project/cockpit#5071]
SELinux should be transparent to cockpit.

This seems to have been caused by admin moving (mv) a certificate from a different location. mv -Z should have been used instead (or preferably cp). remotectl should not be expected to deal with this. If the file would have been owned by for example joe and had 0700 set then remotectl would (likely?) not able to deal with it either, this is no different.

Nothing else is needed, just revert this commit and then rely on a capable admin. if admin is not capable then just let it fail

**Comment by doverride** [comment]
And if you insist on remotectl being able to deal with mistakes like this by incapable admins then just use "restorecon -RvF /etc/cockpit" or preferably "selinux_lsetfilecon()".

**Comment by mvollmer** [comment]
> If the file would have been owned by for example joe and had 0700 set then remotectl would (likely?) not able to deal with it either, this is no different.

I think it is able to deal with this by fixing the permissions and owner: https://github.com/cockpit-project/cockpit/blob/03f31d3ef17b39d23294a413b8c792bbdc4f2629/src/remotectl/certificate.c#L120

Is there any specific harm to remotectl calling chcon?

@stefwalter, wdyt?

**Comment by doverride** [comment]
The preferable way would be to use selinux_lsetfilecon(), and if you do not want to link to libselinux then restorecon -RvF.

I Think though that it is not a good idea to try to do these things on behalf of sysadm in the first place.

Using chcon is a bad idea because:

To be able to "relabel to" a specific type, the process also needs to be able to "relabel from" a specific type. We cannot know the type to "relabel from" beforehand.

And so chances are that eventhough remotectl runs chcon. It is not allowed to relabel from the existing type anyway

For example, lets say currently . for whatever reason, /etc/cockpit/cert.cert is associated with type shadow_t (the type that is associated with /etc/shadow), then remotectl will, or atleast, should not be  allowed to relabel from shadow_t to for example etc_t. 

Also It is prone to error, and this implementation proves that point, In this implementation chcon is used to associate type etc_t with the cockpit certificate. This is not the appropriate type for either /etc/cockpit or for certificates.

Not to mention that type etc_t is a policy specific identifier. It might not work on all policies enforced.

**Comment by doverride** [comment]
If you assume that sysadm may be incompetent and then try to deal with that automatically then that is a potential security issue

what if a incompetent admin by mistake moves /etc/shadow to /etc/cockpit/cockpit.cert? then remotectl, in theory, would happily remove protection from it by changing its type to etc_t, causing many processes to be able to read it.

**Comment by rhwood** [comment]
Some vendors of RHEL-based appliances replace the default SELinux policies with significantly more stringent and granular policies. Using ```restorecon``` in these cases would take the correct action (applying the appliance-specific policy), while using ```chcon``` would break things (by assuming that the cockpit-defined policy is in effect).

**Comment by larskarlitski** [comment]
This patch doesn't cleanly revert anymore and we didn't hear about an issue with it since this bug was opened. If you still think we should stop calling `chcon`, feel free to reopen it.
