### ISSUE TITLE
cockpit socket responds 403 Forbidden in apache reverse proxy

### ISSUE THREAD

**Issue by bensonshaji** [cockpit-project/cockpit#5073]
I am actually trying to set up reverse proxy to access cockpit via custom URL. for ex: https://example.com
Everything works fine except that cockpit socket connection is failing. All web requests are successful except https://example.com/cockpit/socket, which responds 403 Forbidden via reverse proxy. 

I believe there is something wrong with my SSL setup (currently using LetsEncrypt) because when i access cockpit through port 9090, I am able to access dashboard (with default cockpit ssl certificates). Below is my apache conf file

```
<VirtualHost *:443>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/
        ServerName example.com
        SSLEngine on
        SSLProxyEngine on
        SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
        SSLCertificateChainFile /etc/letsencrypt/live/example.com/chain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem

        ProxyPass / http://127.0.0.1:9090/
        ProxyPassReverse / http://127.0.0.1:9090/

        <Location "/cockpit/socket">
                ProxyPass "ws://127.0.0.1:9090/cockpit/socket"
        </Location>
</VirtualHost>
```

Is there any official documentation/resource that I can refer to configure cockpit with Apache reverse proxy ?

**Comment by petervo** [comment]
You are probably missing the Origins setting in cockpit.conf. See http://cockpit-project.org/guide/latest/cockpit.conf.5.html

**Comment by bensonshaji** [comment]
@petervo Thank you so much :)
Thats exactly what I was looking for. It Works! Thanks once again. :)

**Comment by petervo** [comment]
np, glad it's working.
