### ISSUE TITLE
Question: Websocket connection to Docker container in Cockpit environment fails

### ISSUE THREAD

**Issue by pitaki** [cockpit-project/cockpit#5086]
I do have a dockerized centos that has a websocket service built it. For that socket a port 80 is declared in docker run-command. In an environment without cockpit a http-request upon that host is handled as a ws-connection and heartbeat can be heard to anybody who has access to that ip-address (docker host).

I placed this container inside a host that has cockpit on it and ... something blocks the traffic completely. I have given access to firewalld, but something else has to be completed too. Any hints of where to look is greatly appreciated.

**Comment by petervo** [comment]
Have you tried checking for selinux errors in the journal? Cockpit shouldn't really be interfering with this, it only listens on port 9090. I would suggest you disable cockpit

```
systemctl disable cockpit.socket
systemctl stop cockpit
```

and see if that makes your service work. If it does not, then cockpit is not the issue,

**Comment by pitaki** [comment]
Thanks, petervo. I tried that and still no websocket traffic out from the host (that runs Docker). I even closed down firewalld and set SELinux to permissive and still the same. Wonder if this Docker installation has changed somehow as it now comes with the Centos-minimal/cockpit -installation.

**Comment by stefwalter** [comment]
@pitaki If you disabled Cockpit and that didn't solve the problem, then this doesn't have to do with Cockpit. I hope you do figure out the issue. I'll close this now, although if you do see some concrete way that Cockpit is involved, then feel free to continue to comment and discuss here.
