### ISSUE TITLE
Hardware Fault Management

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [cockpit-project/cockpit#5090]
Does cockpit have any plans to include some kind of Hardware Fault Management, which will show hardware status, e.g. Memory, IO, Cache errors for devices? Currently you can find partial hardware information in the cockpit system or storage logs, but the full hardware status aggregated in one place is missing. In my opinion, it is very helpful feature for critical system error indications. 

P.S. I've found the [mcelog](https://github.com/andikleen/mcelog) log, which might be integrated with cockpit for collecting hardware status.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

We are sorry, but we won't be able to address this in any time soon.
If you are interested in helping us with the implementation, please comment here.
