### ISSUE TITLE
Applications: Show versions of all modules

### ISSUE THREAD

**Issue by thomasmckay** [cockpit-project/cockpit#5092]
For example, when running Atomic Registry the "About Cockpit" should indicate the relevant information about the registry. TBH, I don't know what "relevant information" is but it should be enough to allow a user to visit a changelog or other source of record and see what went into that release.

**Comment by stefwalter** [comment]
Agree ++

**Comment by stefwalter** [comment]
@andreasn Do you have any ideas for how this might look? A nice looking design would allow someone to jump in and contribute this change.

**Comment by andreasn** [comment]
I can take a look. There is also a new Patternfly About Dialog pattern in the works, that can be part of this change.

**Comment by andreasn** [comment]
https://www.patternfly.org/pattern-library/communication/about-modal/

**Comment by radhikakolathumani** [comment]
@andreasn  I would like to work on this issue, a good start for my outreachy application as well.

**Comment by dperpeet** [comment]
> @andreasn I would like to work on this issue, a good start for my outreachy application as well.

@radhikakolathumani I think this is a great issue to get started on. As far as I know @andreasn hasn't put much work into this. I don't see anything on the trello board either. The patternfly about modal looks like a good template. To try the workflow, it might be worth creating a wiki page to collect info on what should go into the dialog and gather feedback from others. Setting the scope for this new look is crucial, more features can always be added later.

**Comment by andreasn** [comment]
@radhikakolathumani @dperpeet sounds good to me!

**Comment by radhikakolathumani** [comment]
Iam setting up cockpit but since I have a Mac I am setting up through virtualbox, if I run into any issues , I will let you know.

**Comment by radhikamani88** [comment]
First version of the user story : https://github.com/cockpit-project/cockpit/wiki/About-Cockpit . Feedback and suggestion welcome.

**Comment by radhikamani88** [comment]
First version of the iteration, followed all the design guidelines from patternfly

![about_cockpit](https://cloud.githubusercontent.com/assets/14060749/19315824/3f6fddec-906d-11e6-9b7f-9f4bbb636715.png)

**Comment by radhikamani88** [comment]
![cockpit2](https://cloud.githubusercontent.com/assets/14060749/19411967/5578e71e-92d9-11e6-87f7-5662818d8978.png)

**Comment by radhikamani88** [comment]
![cockpit23](https://cloud.githubusercontent.com/assets/14060749/19412046/f31bbe5a-92da-11e6-8184-6e42ed4b4bd5.png)

**Comment by dperpeet** [comment]
Looks better. I would leave out "Configuration". Also, it's currently unclear which part of the Cockpit the version refers to, since there might be different versions (bridge, ws, ...). The vertical spacing seems a bit off regarding the grouping of information.

**Comment by radhikamani88** [comment]
Hi dominick, 
I needed to clarify this before I start on the iteration. 
Should I be showing all the versions ( like ws , bridge) as given below : 

![cockpit component versions](https://cloud.githubusercontent.com/assets/14060749/19428492/891d15aa-9418-11e6-942c-8cfaa045a313.png)

**Comment by dperpeet** [comment]
@andreasn what do you think?
We have os packages on one side, on the other side we have cockpit modules/parts:
```
[dev@devmachine src]$ cockpit-bridge --packages
base1: /usr/share/cockpit/base1
dashboard: /usr/share/cockpit/dashboard
docker: /usr/share/cockpit/docker
domain: /usr/share/cockpit/realmd
kubernetes: /usr/share/cockpit/kubernetes
machines: /usr/share/cockpit/machines
network: /usr/share/cockpit/networkmanager
performance: /usr/share/cockpit/tuned
playground: /usr/share/cockpit/playground
selinux: /usr/share/cockpit/selinux
shell: /usr/share/cockpit/shell
sosreport: /usr/share/cockpit/sosreport
storage: /usr/share/cockpit/storaged
subscriptions: /usr/share/cockpit/subscriptions
system: /usr/share/cockpit/systemd
updates: /usr/share/cockpit/ostree
users: /usr/share/cockpit/users
checksum = dcf801a38c732a4e304f7cfa50168c57be376ef7
```
Each of these has a version and an os package might install more than one cockpit module/part. Like described on the wiki, contextual info might be best. That probably requires more coding, so the question is: how much should we try to show in the about dialog?

**Comment by andreasn** [comment]
Usually the labels that describe things align to the right, so it creates a nice clear line in between.
The dialog feels a bit busy right now, and not as clean and clear as the example on the Patternfly page.
Is there anything you can do to reduce the noise?

**Comment by radhikamani88** [comment]
Agreed @andreasn  I also felt the same, the  pattern shown in the website looked small. Further even the website modal as shown below in the screenshot is small and does not cover a lot of space. My question what is about modal dimensions ? Should I concentrating on making the modal exactly given in the patternfly or should I increase the size of modal to nicely fit the information displayed.

**Comment by radhikamani88** [comment]
![screen shot 2016-10-16 at 10 14 43 pm](https://cloud.githubusercontent.com/assets/14060749/19459313/e1277718-949f-11e6-8b5f-83cfa0c97046.png)

**Comment by andreasn** [comment]
> Should I concentrating on making the modal exactly given in the patternfly or should I increase the size of modal to nicely fit the information displayed.

Following Patternfly sounds better I think.

**Comment by radhikamani88** [comment]
@andreasn @dperpeet I iterated according to the feedback. The questions I have in mind are these 1) What if the user installs more packages, how can that be shown in the modal. I have come up with these solutions : 
          a) Scroll bar inside the about modal 
          b) Infinite scroll inside the about modal
I have tried thinking about accordion inside a modal but when a user clicks it, it would open beyond the modal's dimensions. So the above two solutions seems reasonable. I wanted to ask whether I can use these patterns mentioned above in my about-modal design. For now, I have given the two designs which shows the left and right aligned versions. 
![asset 9](https://cloud.githubusercontent.com/assets/14060749/19633089/bb721286-997b-11e6-975b-7c3c30c04f38.png)
![asset 14](https://cloud.githubusercontent.com/assets/14060749/19633091/c11cae94-997b-11e6-9b09-88b05cad0e88.png)

**Comment by dperpeet** [comment]
Looks good, lots of information.
Some ideas:

- What about using the logo instead of the text "About Cockpit"? Also, I assume it is a link to the project homepage
- Top-down I would expect a different order: machine, cockpit, other modules
- `Version` and `Link` seem redundant, it's obvious - The page will probably look a lot cleaner without the extra text
- How about `Machine` or `Host` instead of `OS, Hostname`?
- If the Cockpit logo is at the top, we could have the branding logo in the bottom right corner

**Comment by radhikamani88** [comment]
Hi dominik, thanks I do have some questions before I work on the iteration, 

1) Is the information displayed adequate or is it way too much for the user to comprehend? 
2) If it is too much, I had given some recommendations in my previous message here, will following such patterns be okay?

**Comment by dperpeet** [comment]
> Hi dominik, thanks I do have some questions before I work on the iteration,
> 
> 1) Is the information displayed adequate or is it way too much for the user to comprehend?
> 2) If it is too much, I had given some recommendations in my previous message here, will following such patterns be okay?

The changes I mentioned should help reduce the content somewhat. The dialog could fall back on our regular scrolling behavior, but shouldn't need to.

**Comment by andreasn** [comment]
Patternfly pattern for reference:
![patternfly pattern](https://www.patternfly.org/assets/img/PatternFly_About_Modal.jpg)

**Comment by radhikamani88** [comment]
@andreasn @dperpeet 

Hi all,

Thanks for the feedback !

I do have some more doubts for which  clarification would be greatly appreciated.

We have discussed both options in the past -- (1) to show the machine information (2) to not show it. And there have been some differing opinions on it. (You can refer to the feedback section in the user stories page :.https://github.com/cockpit-project/cockpit/wiki/About-Cockpit where Dominik originally suggested having that information) So what should we incorporate into this modal? One way I can think of resolving this would be to test it with the users and get their feedback to see whether this is a good information to display. 


Design Questions 

1) I am new to using patternfly so I have some doubts about the hex code for the modal shown above. Is the hex code for this modal this ?: pf-black-900 #292e34 

2) I had mocked up 2 versions -- left aligned and other is right aligned. Which one do you all prefer. I will carry that version forwarded to next iteration.

3) Further, there is pattern above the branding in the right hand corner, is this pattern required for the dialog as well? I am referring to the diagonal stripes.

Thanks , any help would be appreciated :)

**Comment by andreasn** [comment]
> 1) I am new to using patternfly so I have some doubts about the hex code for the modal shown above. Is the hex code for this modal this ?: pf-black-900 #292e34 

Seems so. At least that what I got when I measured in GIMP.

> 2) I had mocked up 2 versions -- left aligned and other is right aligned. Which one do you all prefer. I will carry that version forwarded to next iteration.

Right aligned would make it consistent with all other labels in Cockpit.

> 3) Further, there is pattern above the branding in the right hand corner, is this pattern required for the dialog as well? I am referring to the diagonal stripes. ( Please refer to the image below)

The documentation in Patternfly is a bit sparse and unclear for that part, but from comparing it with [the login page](http://www.patternfly.org/pattern-library/application-framework/login-page/#_) we should be using the same background pattern we use on the login page. You can start with using just plain #292e34 for now in the mockup, or use the same pattern as we use on the Cockpit login page.


With regards to showing the OS name and host name, you're right about this being specified in the workflow, so in some sense it's a bit late in the game for me to oppose it at this stage, but my concern was with the sheer amount of information already available in the about screen. It's easy for a system administrator to access that information by looking at the server page.
I'm fine with keeping it if there is a way we can cut down on the amount of text somehow, maybe taking out some headers and restructure things a bit.

**Comment by radhikamani88** [comment]
@dperpeet @andreasn 

I completed this iteration , few things I noted down are: 

![asset 19](https://cloud.githubusercontent.com/assets/14060749/19906560/9f12c7ca-a051-11e6-97fe-76d34931dee5.png)


1) The pattern fly github design file's about modal (https://github.com/patternfly/patternfly-sass/blob/master/assets/images/patternfly/bg-modal-about-pf.png)was a bit squared as opposed to the modal given in the pattern fly website. Should I change the dimensions ? 

2) The pattern inside the about modal feels a bit busy currently as I had to overlay the text on it. Since I have not changed the modal dimensions (specially horizontally), what should I be doing in this case ?

3) The about modal image file  when stretched out makes the image more pixelated ? Is there any other image asset file in github I should be looking at ?

Thanks , any feedback and suggestions are welcome for this iteration

**Comment by andreasn** [comment]
> Should I change the dimensions?

I think it might be that the dialog design isn't made to have this much information in it.
Here is some ideas of how to fix that:
 * Remove all the headers (all the cockpit module names have cockpit- before them anyway)
 * Make the module version one line, by making the version be the link to the release notes
 * Get rid of the Version header.

**Comment by andreasn** [comment]
> The pattern inside the about modal feels a bit busy currently as I had to overlay the text on it.

This will use the same background as the login page. On Fedora this is very plain, and so it is on RHEL, so I think this should be OK in most cases.

**Comment by andreasn** [comment]
> The about modal image file when stretched out makes the image more pixelated ?

I think the implementation in Patternfly should not stretch the background image, but if it does, you'll need to file a bug against Patternfly. https://github.com/patternfly/

**Comment by radhikamani88** [comment]
@andreasn So for this iteration, I saw how the code was implemented and made the design accordingly ( basically the pattern was overlaid on a rectangle). So I believe at this time, RFE maybe is not required. I exactly the followed the about modal's dimensions and the spacing of the heading, labels and logo placement. 
![asset 24](https://cloud.githubusercontent.com/assets/14060749/19993006/c3676e64-a218-11e6-96d0-33efae019a70.png)

**Comment by andreasn** [comment]
Thanks for taking care of the headers and links. Looks much better now!

In the [patternfly pattern page]( https://www.patternfly.org/pattern-library/communication/about-modal/#/api) the name label is bold. Did you make that nonbold on purpose, or was it an oversight?

Looking at the pattern and comparing it to the [login page pattern](http://www.patternfly.org/pattern-library/application-framework/login-page/#_), I think the logo in the bottom right corner is supposed to be the Cockpit logo, and where you currently have the Cockpit logo, it should just say Cockpit in regular letters.
The background should be the same as you get on the Cockpit login page by default.

Apart from those things, this looks good!

**Comment by andreasn** [comment]
> But looking at the design, I believe this header spacing can be decreased a bit , any thoughts on this ?

This spacing looks very similar to the one on the Patternfly page. So it looks correct to me.

**Comment by radhikamani88** [comment]
Thanks for the feedback, Please find my answers inline 

In the patternfly pattern page the name label is bold. Did you make that nonbold on purpose, or was it an oversight?

Nope, the open sans font only shows me semibold n light option , I used that semibold option and when I reduced the text size the font weight appears light. Should I change type ? I don't think that will be according to standards. However I guess it will be okay to change the font weight a bit.

Looking at the pattern and comparing it to the login page pattern, I think the logo in the bottom right corner is supposed to be the Cockpit logo, and where you currently have the Cockpit logo, it should just say Cockpit in regular letters.
The background should be the same as you get on the Cockpit login page by default.

Dominik previously suggested this in the feedback above 

"If the Cockpit logo is at the top, we could have the branding logo in the bottom right corner"

**Comment by dperpeet** [comment]
> Dominik previously suggested this in the feedback above
> 
> "If the Cockpit logo is at the top, we could have the branding logo in the bottom right corner"

Right. I have to admit I didn't check too carefully against the pattern while writing that. I'll defer to Andreas' judgement here.
The idea behind what I wrote was that we want to brand the About dialog somehow, in the future. Also, we still want to place the Cockpit logo somewhere. With what I suggested, we can place both without taking up too much valuable space.

**Comment by andreasn** [comment]
Reading the Patternfly spec page again, it has the "Product title" specified as text only, but it probably works with a graphical logo as well. So in that case it makes sense to keep the logo where it is now.

**Comment by thomasmckay** [comment]
@radhikamani88 - Did this ever make it to a pull-request? Would be very useful.

**Comment by KKoukiou** [comment]
Wondering if this belongs to the applications page;

@andreasn since you were involved in this, what do you think?

**Comment by martinpitt** [comment]
The Applications page doesn't show the versions of pages that we ship ourselves, though. It would be a good start of course, as usually these are the ones that differ much more likely from the "main" cockpit version than things like cockpit-machines.

**Comment by stefwalter** [comment]
But why isn't the cockpit-machines an application that shows up on the Applications page?

**Comment by KKoukiou** [comment]
> But why isn't the cockpit-machines an application that shows up on the Applications page?

It does show actually.
![Screen Shot 2019-10-18 at 15 21 48](https://user-images.githubusercontent.com/14921356/67097752-0f564080-f1bb-11e9-9e93-b48c0e69a0e1.png)

**Comment by martinpitt** [comment]
Right, cockpit-machines was a bad example. In fact, we actually added AppStream descriptions (i. e. entries on the Machines page) even for SELinux, kdump, etc. So on second thought, showing the version on the Apps page is just fine!

**Comment by marusak** [comment]
We should use https://www.patternfly.org/v4/components/about-modal

**Comment by garrett** [comment]
I believe we happen to have this now, filed in issue #15962 and added in PR #16222.

Please reopen with a comment if I'm wrong. :wink:
