### ISSUE TITLE
latest release (118) missing from Ubuntu's PPA

### ISSUE THREAD

**Issue by ykorman** [cockpit-project/cockpit#5093]
[Cockpit's Ubuntu PPA](https://launchpad.net/~cockpit-project/+archive/ubuntu/cockpit) still contains the previous release 0.117.

**Comment by larskarlitski** [comment]
Hey! Thanks for the report. The debian package failed building for the last couple of releases. I've made a pull request for our release machinery here:

    https://github.com/cockpit-project/cockpituous/pull/39

Once this is fixed, packages for new versions should go out to launchpad again.

**Comment by larskarlitski** [comment]
Pushed 119 to the PPA.
