### ISSUE TITLE
This package requires Cockpit version 0.114 or later

### ISSUE THREAD

**Issue by Yamakaky** [cockpit-project/cockpit#5103]
I just installed https://aur.archlinux.org/packages/cockpit/, version 118-1, but I get the following message: `This package requires Cockpit version 0.114 or later`.

**Comment by fcmugen** [comment]
Likewise. I am seeing the same issue.

**Comment by stefwalter** [comment]
Could you include relevant log lines from the journal? Something like this would help you to find them:

```
journalctl -b | grep cockpit
```

**Comment by Yamakaky** [comment]
Not really relevant but https://0bin.net/paste/FZ2BY9GEPwOMf+g1#zlUt7tQ1pBphBnnz-n8dCGJqG20cuV6XYZx8X8VetTt

**Comment by stefwalter** [comment]
Thanks that output is very telling. The build seems to have a knowing its own PACKAGE_VERSION. 

 1. Instead of using github.com/cockpit-project/cockpit/archive/118.tar.gz the build should be using the official tarball that includes the package version: https://github.com/cockpit-project/cockpit/releases/download/119/cockpit-119.tar.xz

**Comment by stefwalter** [comment]
The linked pull request will enforce the behavior and prevent us from getting into this situation. 

Summarized: Cockpit needs to know its own version. When built from 118.tar.gz that information is not available, none of the contents of that file contain the version number. Either the actual .tar.xz tarball can be used to build Cockpit, or a proper git checkout.

The above pull request enforces this reality in a better way so it's easier to troubleshoot.

**Comment by Yamakaky** [comment]
Cool! Letting this issue open until the AUR package is updated.

**Comment by stefwalter** [comment]
@Yamakaky Have you reached out the AUR package maintainer with a link to this here?

**Comment by Yamakaky** [comment]
Yes

**Comment by Yamakaky** [comment]
Good!
