### ISSUE TITLE
Registry: returning to overview should not filter by project

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#5119]
When navigating to a project, then back to "Overview", some users have expressed it is unexpected the project filter is set to the project. They expect it to be "All Projects".

**Comment by stefwalter** [comment]
Good point. We could just put the project in the url bar perhaps.

**Comment by lcarva** [comment]
Also, without navigating between pages, but while in "Overview" page, selecting a specific project in “Images pushed recently” and selecting back “All Projects”, does not show images for all projects. Instead the data displayed is for the previously selected project.

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
