### ISSUE TITLE
No Containers in Cockpit on Fedora 24

### ISSUE THREAD

**Issue by m0nhawk** [cockpit-project/cockpit#5121]
I'm using Fedora 24 Server Edition with Cockpit and Docker installed from the repository.

I have my main used added to the `docker` group and have option `Container Administrator` set for this user.

But, I don't see any `Container` menu link in Cockpit.

What's wrong?

**Comment by petervo** [comment]
Do you have the cockpit-docker package installed?

**Comment by m0nhawk** [comment]
@petervo Thanks. It was missing.

I was looking into this [page](http://cockpit-project.org/guide/latest/feature-docker.html) and haven't found any reference on it.

**Comment by stefwalter** [comment]
@rhatdan Hmmm, I wonder if we can we make the 'docker' page 'Suggest:' cockpit-docker on Fedora 24 and later?
