### ISSUE TITLE
RPM conflict with Docker 1.12. Won't Install

### ISSUE THREAD

**Issue by bgulla** [cockpit-project/cockpit#5133]
I want to install cockpit but unfortunately, on my fresh centos7 aws instance, there's a version conflict with the latest RPM of docker. Any Help?

Linux ip-172-31-1-89.ec2.internal 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

CentOS Linux release 7.2.1511 (Core)

> yum install -y cockpit
...
--> Processing Conflict: docker-engine-1.12.1-1.el7.centos.x86_64 conflicts docker
--> Processing Conflict: docker-engine-1.12.1-1.el7.centos.x86_64 conflicts docker-io
--> Processing Conflict: docker-engine-selinux-1.12.1-1.el7.centos.noarch conflicts docker-selinux

> docker version
brandon@ip-172-31-1-89[~] > docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

**Comment by liger1978** [comment]
Yes, I'm seeing this issue also.  On EL7, many people will be using the official docker repos rather than the bundled docker packages (which are a bit old).  Not sure of a nice way to rewrite the dependencies so that this issue does not occur :(

**Comment by stefwalter** [comment]
Agree this looks like a packaging issue. And upstream docker seems to have merged the right fix. I'll close this issue for now.

In the meantime you should be able to avoid installing the ```cockpit-docker``` subpackage or ```sudo yum remove cockpit-docker``` as a workaround.
