### ISSUE TITLE
i386 Cockpit package not found

### ISSUE THREAD

**Issue by andyforceno** [cockpit-project/cockpit#5139]
Not sure if this is the best place to post this, but I don't know where would be appropriate. I tried installing Cockpit on my Linux server running a 32bit Ubuntu-based distro (Cub Linux), and I get a package not found error:

`W: Failed to fetch http://ppa.launchpad.net/cockpit-project/cockpit/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found`

There is an i386 package for Cockpit, correct?

**Comment by kasabov** [comment]
Cockpit doesn't work on Trusty in general: https://github.com/cockpit-project/cockpit/issues/4329

**Comment by andyforceno** [comment]
Sorry, I must have missed that. Thanks!
