### ISSUE TITLE
test: fedora 23 regression (SELinux, sssd)

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#5142]
Looks like an SELinux failure:
```
Error: audit: type=1400 audit(1476093069.806:244): avc:  denied  { getattr } for  pid=1562 comm="sssd" name="/" dev="vda3" ino=96 scontext=system_u:system_r:sssd_t:s0 tcontext=system_u:object_r:fs_t:s0 tclass=filesystem permissive=0
```

bug: https://bugzilla.redhat.com/show_bug.cgi?id=1380953

**Comment by stefwalter** [comment]
This isn't a knownissue if it's just an SELinux message that doesn't affect the user's ability. It's good that we filed it upstream and are getting it fixed. But the HACK and workaround in our tests is sufficient.

In addition the knownissue won't track when it's fixed either. So lets close this.
