### ISSUE TITLE
storaged: actions on Logical Volume affects it's snapshot, and the other way around

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#5148]
I've been playing around with lvm snapshots, as part of the review of #5097
One issue I found is that while snapshots show up as a separate Logical Volume, it doesn't act quite like one. Several actions triggered on the original Logical Volume apparently affects it's snapshot, such as Activate/Deactivate and Delete. This is also true for the other way around, where those actions triggered on the snapshot affect the original Logical Volume.

**Comment by andreasn** [comment]
Just a clarification, deleting the snapshot doesn't delete the original volume group, but the reverse is true.

**Comment by andreasn** [comment]
Here is a proposal for a layout where snapshots are treated as children of their original logical volume.

![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/storage/logical-volume-snapshot.png)

**Comment by mvollmer** [comment]
Ugh, (non-thin) snapshots are way more complicated than what Cockpit can handle.  For example, the size of a snapshot volume does not correspond to the size of the block device at all and all kind of weird things will probably happen when the user tries to resize them.

I am in favor of quickly removing trad snapshots altogether from the UI and adding them back carefully, probably in coordination with things like Boom.

**Comment by martinpitt** [comment]
Not sure what "trad" snapshots are (the opposite of "thin"?), but I'm fine with removing the feature if it's broken.

**Comment by mvollmer** [comment]
> Not sure what "trad" snapshots are (the opposite of "thin"?)

Yes, exactly.  Snapshots of non-this volumes are implemented very differently from snapshots of thin volumes.  A snapshot of a thin volume is independent of the origin after the initial creation.  It's a copy of the origin that uses CoW optimizations because the pool mechanism makes that easy.
