### ISSUE TITLE
rpm for cokcpit-pcp causes warning

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#5151]
installation of cockpit-pcp causes warning. It is not nice and should be suppressed/solved.

  Installing : cockpit-pcp-118-2.el7.x86_64                               36/38
Rebuild: Warning: -d deprecated, duplicate PMNS names allowed by default
/usr/share/pcp/lib/pmlogger: Warning: Performance Co-Pilot archive logger(s) not permanently enabled.
    To enable pmlogger, run the following as root:
    # /bin/systemctl enable pmlogger.service
Starting pmlogger ...

**Comment by mvollmer** [comment]
Fixed.
