### ISSUE TITLE
Can't Install on Ubuntu or CentOS

### ISSUE THREAD

**Issue by elJoeyJojo** [cockpit-project/cockpit#5162]
Hello Cockpit Devs

I have tried to install Cockpit on both an Ubuntu 14.04 Server and a CentOS 6.7 Server with no luck.  I followed these commands:

http://cockpit-project.org/running.html

These are the errors I get on Ubuntu:

W: Failed to fetch http://ppa.launchpad.net/cockpit-project/cockpit/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/cockpit-project/cockpit/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

These are the errors I get on CentOS:

No package cockpit available.

I'm probably missing something but not quite sure what.

Thanks

**Comment by petervo** [comment]
Cockpit requires systemd. So it only works on CentOS 7+ or ubuntu 16+.

On ubuntu you are going to need this ppa.
ppa:cockpit-project/cockpit
