### ISSUE TITLE
`vagrant up` is broken when nested vms are not enabled

### ISSUE THREAD

**Issue by larskarlitski** [cockpit-project/cockpit#5174]
As of 77d10f6, `vagrant up` doesn't work anymore if running it on a host that doesn't have nested virtualization enabled (which is the default). It fails on [line 57](https://github.com/cockpit-project/cockpit/blob/master/Vagrantfile#L57), because `/sys/module/kvm_intel/parameters/nested` doesn't exist.

Why is removing and reinserting the modules necessary at all when  `libvirt.nested = true` is passed? Even if not, can't we just pass the option on the kernel command line when booting?

I also think that 2 GB of memory for the VM is too much for the default case.

**Comment by larskarlitski** [comment]
Another question: why do we need to enable nested vms inside the vagrant VM at all? If I understand correctly, it only needs to be enabled on the hypervisor.

**Comment by mareklibra** [comment]
The libvirt.nested=true did not ensure the kvm_intel module has nested=1 parameter set.
By default, the kvm_intel is loaded with nested=0.

For that reason, there's the modprobe attempting to add kvm_[intel|amd] module with nested virt allowed.
As far as I know, there's no way how to set the nested param once the module is loaded, so the rmmod is used.

The purpose of the failing line is informative only to allow check whether the nested virtualization allowed.

To fix the issue I would either
- add "| true" at the end of the line and extended the 'cat' for the kvm_amd
- or remove the failing 'echo' line

In general, the purpose of these changes was to provide possibility to try the 'machines' package in Vagrant.
If this use case is not needed, we can remove these changes at all.

**Comment by larskarlitski** [comment]
> The libvirt.nested=true did not ensure the kvm_intel module has nested=1 parameter set.
By default, the kvm_intel is loaded with nested=0.

Right, but you need this set on the host, not inside the VM. The VM only needs to have the `vmx` cpu flag set, which is what `libvirt.nested=true` does.

Enabled nested virtualization on my machine and running `sudo virt-host-validate` inside the vagrant VM shows that hardware virtualization is enabled, even if I remove all of those lines. Can you please try if everything works for you as well with my patch at #5176.

I got this information from https://kashyapc.com/2012/01/14/nested-virtualization-with-kvm-intel/ .

**Comment by mareklibra** [comment]
Thanks, works for me.

**Comment by larskarlitski** [comment]
Thanks for pushing the fix, Stef.
