### ISSUE TITLE
Webshell characters "{" and "}" are broken

### ISSUE THREAD

**Issue by xrow** [cockpit-project/cockpit#5185]
Hi,

if you type the chars "{" or "}" into the cli of a pod. Nothing will happen. In vi the "{" will turn into "^_".  

It is usefull to be able to use "{" or "}".

I have a german keyboard. The cockpit version is 0.114.

**Comment by stefwalter** [comment]
Hi @xrow, which browser are/were you using?

**Comment by xrow** [comment]
Hi @stefwalter ,

I use chrome. Let me know, if I should test in other browsers too.

**Comment by stefwalter** [comment]
Can reproduce. I'll need to look into this further.

**Comment by martinpitt** [comment]
I tested this in Firefox and Chromium on current versions, works fine.
