### ISSUE TITLE
network: "Automatic" for MTU is not clear. 

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#5190]
People where not sure whether "Automatic" does clever path discovery and sets the MTU to the best value for the actual infrastructure, or just sets it to the default 1500.

We should at least report the actual value, and maybe change "Automatic" to "Default".

**Comment by mvollmer** [comment]
@andreasn, wdyt?

**Comment by mvollmer** [comment]
I am not sure either what it actually does exactly...

**Comment by andreasn** [comment]
Default sounds better.

We should also indicate what unit the number is in.
What about something like this:
![mockup](https://github.com/cockpit-project/cockpit-design/blob/master/network/mtu-size-dialog-v2.png)

**Comment by andreasn** [comment]
Not sure if putting bytes after the input box there will mess up translations. If so, we can skip the "bytes" label.

**Comment by dperpeet** [comment]
Good design, but what does NetworkManager actually do? Putting a number in there only makes sense if that is what will be set. Can we guarantee that?

**Comment by andreasn** [comment]
> Can we guarantee that?

It's possible in nm-connection-editor, so it seems so.

![screenshot from 2016-10-26 15-03-21](https://cloud.githubusercontent.com/assets/209895/19726903/6d6fae40-9b8d-11e6-9981-afd153a9ff56.png)

**Comment by mvollmer** [comment]
Let's close this.
