### ISSUE TITLE
Compile and Makefile: how to add another library support?

### ISSUE THREAD

**Issue by leopeng1995** [cockpit-project/cockpit#5196]
I need to use another library functionalities in Cockpit sources, so I want to know where to write directive  something like 

`gcc -Wall ``pkg-config --cflags --libs glib-2.0`` example.c -lglib -o example`

where the _-lglib_. Because I am messing up in enormous codes in `configure` and `Makefile`.

**Comment by leopeng1995** [comment]
Alright, I found it. In `configure` where `COCKPIT_WS_LIBS`, `COCKPIT_PCP_LIBS`,

**Comment by leopeng1995** [comment]
When I add `-l???` to `COCKPIT_WS_LIBS` in `configure`, there is no compile issue. However, when I restart the cockpit.service process, it displays `cannot open shared object file: No such file or directory` error.

**Comment by leopeng1995** [comment]
I executed the command `cp` copy the lib to /usr/lib and /usr/lib64, and then solved this issue.

**Comment by stefwalter** [comment]
Ok glad this worked out. I'm assuming this is a packaging issue?
