### ISSUE TITLE
Collapse instanced services

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#52]
Lennart proposed to collapse instanced services (like getty's) into one. This would help keep our list of services from getting too long.

**Comment by KKoukiou** [comment]
I think with the current design this does not make sense any more.
Its row of the table has 'per service' information like active state and so on, and also each rows is clickable and that would redirect you to the service details.

I don't think keeping more that one services (the instances ones) in this case in one row would make sense.
@marusak I would like to ask you for you opinion on this - and you agree let's close this issue.

**Comment by marusak** [comment]
yeah, I never really knew how this should work. It would make the UI even more complex and harder to understand.
The list is too long anyway, but we have filtering, so it should help users to find units.
And since no one figured anything out since 2013, I think we can close this one.

**Comment by marusak** [comment]
I am re-opening this one. Right now `setroubleshootd` fails to start on my system. Or to better put it, once I visit services page every few seconds one such item pops up. And in a few minutes it looks like this:
![setroubleshootd](https://user-images.githubusercontent.com/12330670/117149032-1baee800-adb7-11eb-98c1-0261a4cd9c44.png)

So I think we need some squashing or something as this completely breaks the list.

**Comment by marusak** [comment]
This was issue that was fixed in #15802 so I think we don't need this at the end.
