### ISSUE TITLE
Registry: auto-complete tags in create image stream

### ISSUE THREAD

**Issue by thomasmckay** [cockpit-project/cockpit#5213]
The default number of tags pulled for an imagestream set to "sync all tags" is only five. For some this will not be enough but changing this value has other implications to performance. To alleviate this having the "pull specific tags" provide autocomplete suggestions would let the user add the specific tags they desire and exceed this hardcoded limit (eg. ten specific tags could be entered).

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
