### ISSUE TITLE
Registry: editing tags in an imagestream does not refresh images shown

### ISSUE THREAD

**Issue by thomasmckay** [cockpit-project/cockpit#5214]
I synced all tags from registry.access.redhat.com/openshift3/node; this pulled down five tags (as per config setting this is expected). I then edited the imagestream and added another known tag (v3.2.1.13) but the list of tags did not update. Next I removed 'latest' tag from the list and added a tag that did not exist (v3.4). This tag did not show up in the list either.

I saw no errors or even traffic w/ journalctl.

**Comment by larskarlitski** [comment]
Closing this, because we'll be [removing cockpit-kubernetes](https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/) soon. It's unlikely that we'll fix this before then. Sorry!
