### ISSUE TITLE
Cannot access secondary servers when primary server is behind nginx

### ISSUE THREAD

**Issue by agross** [cockpit-project/cockpit#5239]
Hello,

I've set up my primary server behind nginx following the directions given in the [wiki](https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX).

Accessing the primary machine works as expected. As soon as I switch the machine to one of my secondaries the HTML displays "Not found" next to the menu on the left. Using Chrome developer tools I found that cockpit requests 3 `index.html` pages when loading the secondary,

Using unproxied cockpit (no nginx in place!) at https://172.16.0.3:9090/@foo.example.com/system:
* HTTP/200: https://172.16.0.3:9090/cockpit/$855401a16182dcef6a79cf4036cead9ad202d949/dashboard/index.html
* HTTP/200: https://172.16.0.3:9090/cockpit/$855401a16182dcef6a79cf4036cead9ad202d949/system/index.html
* HTTP/200: https://172.16.0.3:9090/cockpit/$855401a16182dcef6a79cf4036cead9ad202d949/system/index.html

Using the nginx-proxied cockpit at https://cockpit.example.local/@foo.example.com/system
* HTTP/200: https://cockpit.example.local/cockpit/$855401a16182dcef6a79cf4036cead9ad202d949/dashboard/index.html
* HTTP/200: https://cockpit.example.local/cockpit/$855401a16182dcef6a79cf4036cead9ad202d949/system/index.html
* HTTP/404: https://cockpit.example.local/cockpit/W/%22$855401a16182dcef6a79cf4036cead9ad202d949%22/system/index.html

The last request resulting in HTTP/404 looks interesing as it contains `%22` (escaped `"`) after `/W` and in front of `/system`.

After a bit of fiddling in my browser I found that https://cockpit.example.local/cockpit/$855401a16182dcef6a79cf4036cead9ad202d949/system/index.html actually works (same as above with `%22` and `/W` removed).

I added a new rewrite rule to my nginx config that redirects such requests internally and suddenly accessing secondaries work:

```diff
diff --git a/sites-available/cockpit b/sites-available/cockpit
index f050abc..e767034 100644
--- a/sites-available/cockpit
+++ b/sites-available/cockpit
@@ -1,54 +1,55 @@
 upstream cockpit {
   server localhost:9090;
 }

 map $http_upgrade $connection_upgrade_cockpit {
   default upgrade;
   '' close;
 }

 server {
   listen            80;
   listen       [::]:80;

   server_name  cockpit.example.local;

   access_log   /var/log/nginx/cockpit.access.log;
   error_log    /var/log/nginx/cockpit.error.log;

   return       301 https://$host$request_uri;
 }

 server {
   listen            443 ssl;
   listen       [::]:443 ssl;

   server_name  cockpit.example.local;

   access_log   /var/log/nginx/cockpit.access.log;
   error_log    /var/log/nginx/cockpit.error.log;

   include      h5bp/directive-only/ssl.conf;

   location / {
-    proxy_pass         http://cockpit;
+    rewrite /cockpit/W/"(.*)"(.*) /cockpit/$1$2 break; # Fix bogus URLs.
+    rewrite /cockpit/W/(.*) /cockpit/$1 break; # Fix assets like fonts.

+    proxy_pass         http://cockpit;
     proxy_set_header   Host              $host;
     proxy_set_header   X-Real-IP         $remote_addr;
     proxy_set_header   X-Forwarded-Host  $http_host;
     proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
     proxy_set_header   X-Forwarded-Proto $scheme;
     proxy_set_header   Connection        "keep-alive";
     proxy_http_version 1.1;

     proxy_store off;
     proxy_buffering off;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection $connection_upgrade_cockpit;

     # Change scheme of "Origin" to http.
     proxy_set_header Origin http://$host;
   }

   include custom/location/letsencrypt.conf;
 }
```

I'm running Fedora 24:
```
$ dnf info cockpit
Last metadata expiration check: 2:00:53 ago on Wed Oct 26 13:56:12 2016.
Available Packages
Name        : cockpit
Arch        : x86_64
Epoch       : 0
Version     : 0.117
Release     : 1.fc24
Size        : 47 k
Repo        : updates
Summary     : A user interface for Linux servers
URL         : http://cockpit-project.org/
License     : LGPLv2+
Description : Cockpit runs in a browser and can manage your network of GNU/Linux
            : machines.
```

**Comment by petervo** [comment]
Cockpit shouldn't be adding that /W but i'm not sure where that could be coming from. The fact that it only happens when behind nginx is very strange as there really isn't any code that would effect that. What is the contents of /etc/cockpit/cockpit.conf?

**Comment by agross** [comment]
@petervo Yes, I agree that nginx should not make modifications to the files. /etc/cockpit/cockpit.conf does not exist.

**Comment by agross** [comment]
Any ideas what causes the `index.html`s to be loaded in the first place? JavaScript?

**Comment by petervo** [comment]
index.html is the html for the system package. loading that page is expected.

Is there possibly any rewriting happening in h5bp/directive-only/ssl.conf or custom/location/letsencrypt.conf

**Comment by agross** [comment]
Nope, no rewriting in place:

https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/directive-only/ssl.conf

letsencrypt.conf:
```
location ^~ /.well-known {
  root /usr/share/nginx/html/letsencrypt;
}
```

**Comment by agross** [comment]
I found this in the HTML of the initial cockpit page:
![2016-10-26_16-46-40](https://cloud.githubusercontent.com/assets/16245/19730868/d95aee68-9b9b-11e6-8e23-39c37a99e6f7.png)

**Comment by petervo** [comment]
What version of cockpit is installed on the secondary machine?

**Comment by agross** [comment]
All running the same (Fedora 24 0.117)

**Comment by agross** [comment]
Seems like when populating the iframe list the checksum member of the server object is responsible:

![2016-10-26_16-50-43](https://cloud.githubusercontent.com/assets/16245/19731126/b9bd75d4-9b9c-11e6-89a7-c24c2432052d.png)

**Comment by petervo** [comment]
Can you make a request to ```/cockpit/@hostname//manifests.json``` and look at the response headers? Specifically ETag.

**Comment by agross** [comment]
My browser session storage contains this:

```json
{
    "content": {
        "blah.example.com": {
            "visible": true,
            "color": "rgb(76, 138, 0)",
            "address": "blah.example.com",
            "label": "blah.example.com",
            "user": ""
        },
    },
    "tag": "1:25362906-1477485565.731835945",
    "overlay": {
        "blah.example.com": {
            "on_disk": true,
            "state": "connected",
                "system": {
                    "version": 0,
                    "name": "system",
                    "menu": {
                        "index": {
                            "label": "System",
                            "order": 0
                        },
            ...
            },
            "checksum": "W/\"$855401a16182dcef6a79cf4036cead9ad202d949\"",
            "restarting": false,
            "os": "Fedora 24 (Server Edition)"
        }
...
```

**Comment by agross** [comment]
Yep, there it is.

```
cache-control:max-age=31556926, public
content-encoding:gzip
content-type:application/json
date:Wed, 26 Oct 2016 15:01:35 GMT
etag:W/"$855401a16182dcef6a79cf4036cead9ad202d949"
server:nginx
status:200
strict-transport-security:max-age=31536000;
vary:Accept-Encoding
```

**Comment by petervo** [comment]
So the question is, is nginx changing that header or is cockpit-ws outputing the wrong thing?

**Comment by agross** [comment]
Plain cockpit returns these:

```
Cache-Control:max-age=31556926, public
Content-Type:application/json
ETag:"$855401a16182dcef6a79cf4036cead9ad202d949"
Transfer-Encoding:chunked
```

I'm going to research ETag settings for nginx and get back to your.

**Comment by petervo** [comment]
Does setting ```etag off;``` in your location block make a difference?

**Comment by agross** [comment]
Actually that wasn't enough. nginx gzips content by default and enabling gzip seems to force an ETag calculated by nginx.

Just disabling gzip works:

```
  location / {
    ...
    # Pass ETag header from cockpit to clients.
    gzip off;
  ...
  }
```

Many thanks for your help!

**Comment by agross** [comment]
Added to the Wiki: https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX

**Comment by K3UL** [comment]
Hi @agross,
I know this is old, but I do not have your use case of a secondary server to try it out, and do not want to write nonsense in the wiki.

In my case everything works fine with gzip on and I have this in my config that is supposed to preserve ETag :

```bash
# Enable gzip but do not remove ETag headers
    gzip                          on;
    gzip_vary                     on;
    gzip_comp_level               4;
    gzip_min_length               256;
    gzip_proxied                  expired no-cache no-store private no_last_modified no_etag auth;
    gzip_types                    application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject applicat$

    location / {
        proxy_pass http://localhost:9090/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```

I can provide the full file if necessary. The gzip/Etag part is shamelessly copy/pasted from what Nextcloud recommends : https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html

If you still have Cockpit and are willing to give it a try, I think this would be an improvement over just gzip turned off.

**Comment by agross** [comment]
Hey @K3UL,

I removed the `gzip off` stanza from my config and I can still access secondary servers. I didn't have to specify anything else to get gzip compression, I guess this is because I use an [older version of h5bp](https://github.com/h5bp/server-configs-nginx/tree/1.0.0) (specifically [this](https://github.com/h5bp/server-configs-nginx/blob/1.0.0/nginx.conf#L70)).

**Comment by MartinX3** [comment]
@agross but it's still mentioned at https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX
So the wiki needs an update?
