### ISSUE TITLE
Errors on Clean Debian Install

### ISSUE THREAD

**Issue by eangulus** [cockpit-project/cockpit#5275]
Hi,

Running a XenServer VM of Debian 8.6 with only Webmin and Sudo added.

Trying to test and evaluate Cockpit for possible use.

After following instructions here: http://cockpit-project.org/running.html I came across 2 issues.
1.  Being a https source, requires installing apt-transport-https. This needs to be specified in the instructions as it is not installed by default.
2. When I try to run `sudo apt-get install cockpit`, I get the following error that I cannot seem to solve.

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cockpit : Depends: cockpit-ws but it is not going to be installed
           Recommends: cockpit-docker but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by stefwalter** [comment]
Well first of all Cockpit is not packaged for Debian Jesse yet. Just Debian unstable. I'd like to get it working for Jesse soon. There's active progress in this area, on the storage and networking sides.

But I did work to help solve the ```apt-transport-https``` problem, and made two changes to where we upload the repo to help with this:

https://github.com/cockpit-project/cockpit-project.github.io/pull/48
https://github.com/cockpit-project/cockpituous/pull/42

@dperpeet Would you be able to help review these so they're in place for the next release?

**Comment by stefwalter** [comment]
@eangulus For reference here's one of the pull requests that work toward get working well on Debian Jesse: https://github.com/cockpit-project/cockpit/pull/5264 and here's another: https://github.com/cockpit-project/cockpit/pull/4901

**Comment by eangulus** [comment]
OK thanks for the info.

I didn't see any statement that it was not ready for Jessie. I simply followed the Debian install instructions.

Currently setting up new servers and so I figured to use the latest stable Debian version.

**Comment by stefwalter** [comment]
The instructions say "debian unstable" ... But hopefully we can change that:

"Cockpit is not yet part of the official Debian repositories, but you can add a repository which contains weekly builds targeting debian unstable:"

See list of work at this milestone: https://trello.com/c/Fl2ayBli/385-milestone-debian-and-ubuntu

And also, the Cockpit meeting notes from yesterday, if you're interested: https://meetbot.fedoraproject.org/cockpit/2016-10-31/weekly_meeting.2016-10-31-14.02.log.html
