### ISSUE TITLE
Registry: Creating imagestream when host name cannot be resolved does not show error in UI.

### ISSUE THREAD

**Issue by thomasmckay** [cockpit-project/cockpit#5282]
Running this command directly indicates there is an error. I don't know how to get the error details (the container logs show nothing).
```
[root@9c3a8028aa0d origin]# oc import-image xyz -n thomasmckay --from registry.example.com:5000/default_organization-dockerhub-hammer --all --confirm --insecure
The import completed with errors.

Name:			xyz
Namespace:		thomasmckay
Created:		Less than a second ago
Labels:			<none>
Annotations:		openshift.io/image.dockerRepositoryCheck=2016-10-31T12:48:58Z
Docker Pull Spec:	172.30.230.125:5000/thomasmckay/xyz
Tags:			<none>
```

The atomic registry UI calls a command or api similar to this. In the UI, the imagestream is shown (thomasmckay/xyz) but no tags are displayed and there is no indication that an error has occurred.

**Comment by larskarlitski** [comment]
Closing this, because we'll be [removing cockpit-kubernetes](https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/) soon. It's unlikely that we'll fix this before then. Sorry!
