### ISSUE TITLE
link _SYSTEMD_UNIT journal detail to service page

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#53]
It should be possible to see all fields of a journal entry. Selected ones should get special treatment: 
- MESSAGE_ID should be looked up in the catalog
- _SYSTEMD_UNIT links to the service page
- _PID should offer to send signals to the process
- _KERNEL_DEVICE etc should link to the storage page if applicable

**Comment by martinpitt** [comment]
IMHO doing magic with `_KERNEL_DEVICE` is too heuristic, and even more so `_PID` -- for old messages it's very plausible that the pid is long gone, or got re-used by a newer process. But linking to the services page is a great and simple improvement.
