### ISSUE TITLE
show pretty hostname for primary server on dashboard servers

### ISSUE THREAD

**Issue by arpu** [cockpit-project/cockpit#5304]
for my users configuration, show the pretty hostname on dashboard servers is more interesting than the ip or domain

**Comment by stefwalter** [comment]
Just to be sure. Could you use a screenshot to indicate the location of the bug?

**Comment by arpu** [comment]
http://localhost:9090/dashboard

![bildschirmfoto von 2016-11-07 23-14-50](https://cloud.githubusercontent.com/assets/14173/20078244/067d6134-a540-11e6-8e97-2f26ac6b619d.png)

**Comment by Gundersanne** [comment]
Is this still an issue for you? I think this got fixed along the way somewhere as my dashboard shows hostname:

![image](https://user-images.githubusercontent.com/11140201/51036669-15751c00-15ae-11e9-8557-56a0cb725cfc.png)

It'll prioritize the pretty hostname, and you can also set the pretty hostname with the 'Edit Server' button.

Closing this, feel free to reopen.
