### ISSUE TITLE
Debian: Docker fails to run due to new systemd cgroup layout

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#5340]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843530

https://github.com/opencontainers/runc/issues/1175

**Comment by cockpituous** [comment]
verify/debian-unstable
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 81, in testBasic
    b.wait_popdown("containers_run_image_dialog")
  File "testlib.py", line 269, in wait_popdown
    self.wait_not_visible('#' + id)
  File "testlib.py", line 241, in wait_not_visible
    return self.wait_js_func('!ph_is_visible', selector)
  File "testlib.py", line 214, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 714, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 737, in _invoke
    raise Error(res['error'])
Error: timeout
rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: no subsystem for mount"
```
First occurrence: 2016-11-10T12:45:57.112144 | revision 204aab6a909647c2329848dcdc56789118784256, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5341-204aab6a-verify-debian-unstable/log.html)
Times recorded: 1
Latest occurrences:

- 2016-11-10T12:45:57.112144 | revision 204aab6a909647c2329848dcdc56789118784256, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5341-204aab6a-verify-debian-unstable/log.html)
