### ISSUE TITLE
Kubernetes cockpit not showing logs anymore

### ISSUE THREAD

**Issue by rmtodd618** [cockpit-project/cockpit#5347]
Upgraded kubernetes to 1.4 and cockpit no longer is showing the logs of the containers. The api is showing logs just fine so api is working for kubernetes.
https://root:changeme@localhost/api/v1/namespaces/kube-system/pods/kube-proxy-node3/log?follow=1&container=kube-proxy

**Comment by petervo** [comment]
What version of cockpit are you running?

**Comment by rmtodd618** [comment]
Im running the latest release. killed it and pulled new image today just to make sure.

**Comment by rmtodd618** [comment]
I know that cockpit works in this version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}

**Comment by petervo** [comment]
We've tested with 1.3 but not to my knowledge 1.4. Chances are something changed in the websocket functionality used to stream the logs. I'll try to take a look, but might not get to it right away. In the mean time, are there any errors in your browser console?

**Comment by stefwalter** [comment]
Thanks for reporting the issue. This should be fixed in version 124
