### ISSUE TITLE
unable to change name of bridge if there is activated slave

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#5355]
There is probably trouble caused by active device in bridgge.
1. created vlan and activate that
2. created bridge and added there this vlan
3. try to configure the bridge (change name to another one)
![screenshot from 2016-11-11 12-19-55](https://cloud.githubusercontent.com/assets/8735467/20213618/c855ac8c-a809-11e6-9de3-2766b8db33e6.png)
 
When I've tested it without any slave device, renaming worked well

**Comment by mvollmer** [comment]
> When I've tested it without any slave device, renaming worked well

Renaming works when an interface is inactive and fails when it is active.  The number of slaves don't matter, but your bridge without any slaves was probably inactive.

**Comment by mvollmer** [comment]
@jscotka, see #5570

**Comment by jscotka** [comment]
yes, this could be that case.
maybe it is not quit well known, when you cretate something new  in networking via cockpit web ui, if it is activated immediately, or it waits until explicit enable, or is this device dependent? I'm not sure now, how Network manager deals with that.
