### ISSUE TITLE
CentOS: Logind fails to kill user session

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#5357]
https://bugs.freedesktop.org/show_bug.cgi?id=89024

```
systemd-219-19.el7_2.13.x86_64
```

**Comment by al3x609** [comment]
i have the same problem 
Version: 176
centos 7
install it from standard repo.

**Comment by marusak** [comment]
This never matched. Also there is no such file in `bots/naughty` which would trigger it
