### ISSUE TITLE
unable to install at Debian...

### ISSUE THREAD

**Issue by nixmomo** [cockpit-project/cockpit#5372]
apt-get install cockpit
Reading package lists... Done
Building dependency tree... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cockpit : Depends: cockpit-ws but it is not going to be installed
           Recommends: cockpit-docker but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by nixmomo** [comment]
its a fresh debian jessie and try to install cockpit-ws too ends in next unme debendencies...

**Comment by stefwalter** [comment]
Debian Jessie is not yet supported by the packages. It will be soon though, likely for the next release: https://github.com/cockpit-project/cockpit/pull/5324

**Comment by nixmomo** [comment]
Itsthe same with Debian 7....

Von meinem iPhone gesendet

**Comment by stefwalter** [comment]
Yup. The repo currently targets "Debian unstable". This is documented here: http://cockpit-project.org/running.html

**Comment by nixmomo** [comment]
Yup but the doc isn't working. 


Von meinem iPhone gesendet
