### ISSUE TITLE
Feature request - integrate compose yml

### ISSUE THREAD

**Issue by jamesdboone** [cockpit-project/cockpit#5404]
Great work on this application guys, it's very useful!

Would it be feasible to implement a 'image run' feature to utilize docker compose yml to define the container parameters?

Likewise, if yml is used for initial container startup, have a 'clean container restart' option that performs a docker stop, docker rm, and docker run again from same yml.

yml copy/paste would be useful, but actually pulling from file would be better in my opinion.

**Comment by stefwalter** [comment]
Thanks @jamesdboone. That sounds like a decent idea. Is it something that you would would be interested in working on?

**Comment by stefwalter** [comment]
Haven't heard back from the reporter. Moved this to the ideas wiki page, and closing the issue.

https://github.com/cockpit-project/cockpit/wiki/Ideas

**Comment by flefevre** [comment]
Hey, 
it will be definitively great to be able to 
- upload a Dockercompose.yml file or to reference one located in a public git
- generate a form for each service described in the docker-compose.yml file
- download all images and start the corresponding images.

Idea: is to be able to deploy a functionnal application composed of several docker.
For instance, Wordpress with the mariadb backend.

Any news for it?
