### ISSUE TITLE
SELinux entry contains more than just troubleshooting

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#5423]
It also allows changing between Enforcing and Permissive mode now, so the label of the page is wrong from that standpoint.

**Comment by andreasn** [comment]
The label "SELinux" by itself is completely technology-focused, but maybe recognizable enough.
"SELinux Access Control", or just "Access Control" are two other options.

**Comment by andreasn** [comment]
```
From the [SELinux wikipedia page](https://en.wikipedia.org/wiki/Security-Enhanced_Linux)
_NSA Security-enhanced Linux is a set of patches to the Linux kernel and some utilities to incorporate a strong, flexible mandatory access control (MAC) architecture into the major subsystems of the kernel._
```

**Comment by dperpeet** [comment]
"Access Control" is a bit too generic, I think.
For an admin, I believe "SELinux" is enough to go on - "SELinux Access Control" is more descriptive, but feels a bit long.

**Comment by andreasn** [comment]
Access Control, or ACL is what Windows Server calls it
https://technet.microsoft.com/en-us/library/dn408189(v=ws.11).aspx
So that would be a bit more familiar to admins coming from Windows.

On the other hand, searching the RH customer portal, searching for "Access Control" gives pretty bad results, while "SELinux" gives you the right stuff, so maybe "SELinux" is more well known in the Linux context

**Comment by dperpeet** [comment]
We have to be careful here, Windows ACL (Access Control Lists) are a different thing, somewhat. I think using the keyword "SELinux" in the title is pretty important - anything with "security" is too vague in this context.

**Comment by andreasn** [comment]
Maybe it's best to just call it "SELinux" in that case then
