### ISSUE TITLE
Cockpit Documentation

### ISSUE THREAD

**Issue by k-s-dean** [cockpit-project/cockpit#5424]
http://cockpit-project.org/guide/latest/guide.html

Was Looking at the documentation yesterday. went back to reference some of the modules and the URL 404'ed

http://cockpit-project.org/guide/latest/guide.html

Kind Regards 
K

**Comment by stefwalter** [comment]
Thanks I appreciate the report. I've fixed the issue, and added a check in our continuous delivery so that the release will fail if the documentation isn't built correctly: https://github.com/cockpit-project/cockpituous/pull/56
