### ISSUE TITLE
"Not ready for use on production servers", Where am I going wrong ?

### ISSUE THREAD

**Issue by bensonshaji** [cockpit-project/cockpit#5493]
I have installed cockpit by building it from source, but I this warning message in the login page. Where am I going wrong ?

I am also getting this error in console.. 

> Content Security Policy: The page’s settings blocked the loading of a resource at self ("default-src www.mydomain.com") 

Build Version = Tag - 125

**Comment by stefwalter** [comment]
Out of interest, which operating system are you building Cockpit on?

The warning "Not ready for use on production servers" is an old leftover warning from when Cockpit was unstable. It's being displayed in the case where Cockpit doesn't recognize your operating system. But it's confusing and I'll work on removing that warning.

**Comment by bensonshaji** [comment]
I guess you are right, I am using Raspbian for my Raspberry PI 3. Since there was no official repositories for this arm based processor, I had to build it from source. Should I modify the css to get it removed for now ?
