### ISSUE TITLE
Server metric dashboards

### ISSUE THREAD

**Issue by fvzwieten** [cockpit-project/cockpit#5498]
Hi,

Love this project! What I would like to propose is that I as a user can create my own dashboards. On my custom made dashboards I can create multiple graphs and in each graph I can select multiple pcp metrics from multple servers. This way I can track what I find important from each set of servers in on view. I would like to be able to specify treshhold values for each counter where I get a visual "alarm" when that trashhold is surpassed.

Problem is that this seems to violate the project's ideal. Creating custom dashboards means keeping user state somewhere. This can be something like a json in the users home directory (~/.cockpit).

Would this be a good idea or is this too much outside the projects intended use-cases?

**Comment by stefwalter** [comment]
This would indeed be cool. And I think it can be done in a way that is inline with the project's use cases and ideals:

 * Store the meta data (such as list of PCP ids, or threshholds) in a way that other tools can use it.
 * Don't store it in ```~/.cockpit``` but put it in ```~/.config/metrics``` or something like that.
 * Build a small command line tool to make the same data available on the command line

Ideally related non GUI tooling would eventually be logging (to the journal, or alerting) when a counter surpasses an alarm ... but that's not a blocker for the pull request.

Try this out as its own dashboard first. If you need help getting started placing the files in the right place to build one, join us on IRC at ```#cockpit``` and ask for mvollmer or myself.

**Comment by larskarlitski** [comment]
We recently decided that a configurable dashboard is out of scope for Cockpit, especially now that tools like [Vector](http://getvector.io/) exist.
