### ISSUE TITLE
Documentation on Kubernetes Auth needs to be clearer

### ISSUE THREAD

**Issue by caedev** [cockpit-project/cockpit#5505]
Having deployed cockpit in a pod in my Kubernetes cluster, I can get to the login screen but can't figure out what credentials I should be using in order to access the dashboard.   It would be useful if the documentation provided the steps to get this up and running.

**Comment by petervo** [comment]
The docs do, http://cockpit-project.org/guide/latest/feature-kubernetes.html#feature-kubernetes-pod

Kubernetes needs to be configured to use to use basic auth or have authentication turned off. If you are using basic auth, log in with those credentials. Feel free to open a pull request if you have suggestions of how to explain that better.
