### ISSUE TITLE
unified menu style ?

### ISSUE THREAD

**Issue by vanloswang** [cockpit-project/cockpit#5506]
There are host domain menu, cluster menu, registry menu on navbar. Both of them have a list-group menu. But the styles of them are different. So there are three styles for them, can we unify it? The menu under host domain menu are generated by js code, there is only text but no icon style, maybe we can specify each icon in manifest.json. The style of cluster menu is much better on mobile devices, maybe we can use it for all.

**Comment by vanloswang** [comment]
@larskarlitski What do think about it?

**Comment by stefwalter** [comment]
I'm separating these into separate issues so they can be dealt with separately.

**Comment by stefwalter** [comment]
@andreasn Is the one to talk to about the menu design. I think we do need some work done in this area.
