### ISSUE TITLE
have the capability to deploy a k8s or origin cluster on cockpit UI ?

### ISSUE THREAD

**Issue by vanloswang** [cockpit-project/cockpit#5507]
As we know, we can deploy an origin cluster by openshift-ansible, but it is not intuitively, cockpit is extensible, modularization, it will be easy to add support this feature. Design the ui and intergrate with openshift-ansible, let the deployment logs on UI. Dynamic add host info and deploy vars like Docker volume or Docker environment. That will be more convenience and WYSIWYG.

Also there is a new project named kubernetes-ansible, it is aimed to deploy a k8s cluster by ansible.

**Comment by stefwalter** [comment]
Are you interested in working on this? If so I can help point you where and how get started. 

I'm not against it, but I don't know of anyone who is looking to implement this.

**Comment by vanloswang** [comment]
@stefwalter There will be a lot works to do for it,  I will keep work on it.

**Comment by vanloswang** [comment]
![image](https://cloud.githubusercontent.com/assets/1133578/21963199/1faefbba-db71-11e6-9c9b-a64dde300e9a.png)

![image](https://cloud.githubusercontent.com/assets/1133578/21963194/08161c7c-db71-11e6-91bb-a81b1a28772d.png)
