### ISSUE TITLE
delete cluster credential to access k8s or origin cluster api server

### ISSUE THREAD

**Issue by vanloswang** [cockpit-project/cockpit#5509]
There are many credentials on my machine, it is out of work after I remove cockpit pkgs and reinstall them, I just want to delete them, but there is no way to delete them on the UI. Cockpit should have the capability.

![default](https://cloud.githubusercontent.com/assets/1133578/20743941/199ac906-b714-11e6-810a-84ff7ba769dd.PNG)

**Comment by stefwalter** [comment]
@vanloswang Are you interested in implementing this? If so I can point you to where where the code is and help you get started.

**Comment by vanloswang** [comment]
@stefwalter I can add a button, and I know that 'kubectl config unset' can delete them, but I does not know to execute the cmd on backgroud now, I does now know the internal of the communications in Cockpit frontend to backend now. Could you give me some info?

**Comment by stefwalter** [comment]
@vanloswang Awesome thanks.

@andreasn Do you think there should just be a little x to the right of each option in that list?

**Comment by andreasn** [comment]
Yeah, I think that is a quick and straightforward solution.

**Comment by vanloswang** [comment]
@stefwalter @andreasn I have done some progress like what stefwalter said, I put a 'Delete' button on the right of each option in that list. Now I am making the backgroud cmd line from user, currentContext.

**Comment by vanloswang** [comment]
@stefwalter Do you meet this situation? Execute 'kubectl config unset' cmd ok, but the context or user is still in the view.
```bash
# kubectl config unset contexts.context.name.192-168-10-16:8443/vanlos/192-168-10-16:8443
property "contexts.context.name.192-168-10-16:8443/vanlos/192-168-10-16:8443" unset.
```

**Comment by vanloswang** [comment]
https://github.com/vanloswang/cockpit/commit/c391dba38659d7b16ea15094e0e2297fb0fc7a0e contain the initial code, click the delete button will execute 'kubectl config unset' cmd on backgroud, using below script to catch the cmds:
```bash
#!/bin/bash

while true
do
    RESULT=`ps aux | grep kubectl | grep -v grep`
    if [ "$RESULT" != "" ]; then
        echo $RESULT
    fi
done
```
Attentions: the code will exec the right cmd, but is still not able to delete the user credentials

**Comment by petervo** [comment]
@vanloswang is it refreshing issue, or is the data just not actually being deleted from the file?

**Comment by vanloswang** [comment]
@petervo now it works, but missing refresh the ui and notice when deleting system:admin.

**Comment by petervo** [comment]
I don't think it was initially built to refresh itself, so you may need to make some changes to how the dropdown is built to get it to update after a deletion.
