### ISSUE TITLE
Minimized css files

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#5512]
@vansloswang says: Also there are some duplicated css style for different pkgs, for example, there are four pieces of a same log panel style in ./dist/networkmanager/network.css and ./dist/storaged/storage.css and ./dist/systemd/system.css and ./pkg/lib/journal.css, which named '.cockpit-log-panel .panel-heading'.

**Comment by stefwalter** [comment]
> Also there are some duplicated css style for different pkgs

Yes this is by design. Each package has its own CSS and javascript. Only the basics with a concrete stable API are shared.

We *do* need to minimize the CSS files ... however we need to do it in such a way that they remain patchable.

**Comment by marusak** [comment]
Fixed in https://github.com/cockpit-project/cockpit/pull/13804
