### ISSUE TITLE
These strings are still need to be translated properly

### ISSUE THREAD

**Issue by vanloswang** [cockpit-project/cockpit#5513]
![image](https://cloud.githubusercontent.com/assets/1133578/20751686/01952472-b738-11e6-9f0f-ee04f24d01fa.png)
The strings in login UI is translated, even login and select language then logout.

![image](https://cloud.githubusercontent.com/assets/1133578/20751763/91d8ee60-b738-11e6-85fe-c2491cdb6a6b.png)
![image](https://cloud.githubusercontent.com/assets/1133578/20751778/b16b9ade-b738-11e6-8cd5-39eaa3d2fc24.png)
The strings related to docker storage.

![image](https://cloud.githubusercontent.com/assets/1133578/20752640/458dddfe-b73d-11e6-9fb1-6097a65cdf49.png)
Cluster--->Docker

![image](https://cloud.githubusercontent.com/assets/1133578/20751826/048bb488-b739-11e6-8232-e9c3e0ccc654.png)
![image](https://cloud.githubusercontent.com/assets/1133578/20751863/2dcb077c-b739-11e6-94f1-b869e5d3af89.png)
The strings related to storaged, the 'Cancel' button in 'Create Volume Group' and 'Create RAID Device'.

![image](https://cloud.githubusercontent.com/assets/1133578/20751955/9fbbe3d8-b739-11e6-8d30-608b0a1e7d58.png)
'Add Bond', 'Add Team' , 'Add Bridge' and 'Add VLAN' in network.  

![image](https://cloud.githubusercontent.com/assets/1133578/20752100/6ddcc3c2-b73a-11e6-966b-0abcc9db3da4.png)
'Reset' button in terminal.

![image](https://cloud.githubusercontent.com/assets/1133578/20752166/d85e748e-b73a-11e6-9d5c-b6a88fda96c4.png)
'Add machine' in dashboard.

![image](https://cloud.githubusercontent.com/assets/1133578/20752457/7aa72d02-b73c-11e6-9594-e792a3de9e2e.png)
Cluster--->topo

![image](https://cloud.githubusercontent.com/assets/1133578/20752505/a73777aa-b73c-11e6-81d3-230ef553db96.png)
Cluster--->Image Stream--->Create Image Stream

![image](https://cloud.githubusercontent.com/assets/1133578/20752559/dc1eae3e-b73c-11e6-912b-024a8114f6d9.png)
Cluster--->Project--->New Project, another dropdown

![image](https://cloud.githubusercontent.com/assets/1133578/20752610/1a67e0d4-b73d-11e6-981c-65b3e95eeae7.png)
Registry--->Image--->New Image Stream

**Comment by stefwalter** [comment]
I'll have a patch for everything but the login screen shortly.

**Comment by petervo** [comment]
Everything but the login page has been merged and uploaded to zanata. Feel free to reopen if there are problems with it.
