### ISSUE TITLE
NetworkManager resets connection settings to defaults during checkpoint rollback

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#5529]
https://bugzilla.redhat.com/show_bug.cgi?id=1400540

**Comment by mvollmer** [comment]
This is for #5472.

If we hit this issue, the test machine stays permanently disconnected.  Not sure if we can actually write a pattern for this...

**Comment by KKoukiou** [comment]
@mvollmer This was a BZ for fedora-25, which is already after EOL, so I guess we can close this?

**Comment by mvollmer** [comment]
If this is indeed fixed, we can remove this HACK: https://www.google.com/search?client=firefox-b-d&q=ipv6+addresses

I'll make a PR for that with a Fixes #5529.
