### ISSUE TITLE
Plugin for monitoring nvidia hardware

### ISSUE THREAD

**Issue by mhirsch** [cockpit-project/cockpit#5549]
I have a cluster of fedora servers with nvidia hardware. I already use cockpit, and would love to be able to monitor nvidia hardware running under the proprietary nvidia driver with a cockpit plugin -- things like temperature, fan speed, GPU utilization, GPU free memory, etc. This would be mediated by the `nvidia-settings` binary. I'm curious if there's any interest in this from other people using cockpit, or if there's already other work being done on something like this.

**Comment by petervo** [comment]
I haven't heard of anything nvidia specific like this in the works, although similar-but-not-really-the- same work is going on here. https://github.com/cockpit-project/cockpit/pull/5523.

My recommendation would be to start by building a prototype. Here are some examples of tutorials for implementing a part of the interface in Cockpit. 

    https://matrixhas.me/en/creating-cockpit-plugin/
    http://cockpit-project.org/blog/creating-plugins-for-the-cockpit-user-interface.html
    http://cockpit-project.org/blog/category/tutorial.html

Once you have a prototype working, we can discuses if bringing it into cockpit upstream makes sense or if it works better as an out of tree plugin.

**Comment by mhirsch** [comment]
Neat, thanks! I made a little text-based prototype following the "ping tool" example, which I already find useful. It looks like to stream temperature and utilization data from the gpu one should use `nvidia-smi`. I saw that the `system` package in cockpit uses the built-in `cockpit.metrics()`. Is there any example you know of that duplicates this kind of behavior with an external binary?

If I end up with something worth sharing I'll be sure to let you all know ;)

**Comment by petervo** [comment]
I don't think there is anyway to plug an external binary into the metrics payload type. 

The kubernetes graphs use some of the javascript functions in cockpit with an external data source, in this case a json based http api.

https://github.com/cockpit-project/cockpit/blob/master/pkg/kubernetes/scripts/graphs.js
https://github.com/cockpit-project/cockpit/blob/master/pkg/kubernetes/scripts/kube-client-cockpit.js#L1181

Not sure if that helps or not.

**Comment by mhirsch** [comment]
Looking at this again, I noticed that the kubernetes graph.js you linked above implements all the graphing logic in `d3`, while cockpit seems to have another internal `flot` implementation here https://github.com/cockpit-project/cockpit/blob/369185303582e0b8cf17a46137bf394dc4f2d641/pkg/lib/plot.js used in all the system graphs. I don't see a way to use either as an "external" plugin. Am I missing something? Should I just be replicating this logic however rather than reusing the code from the project? Is the right answer to be developing my plugin inside the project tree?

**Comment by stefwalter** [comment]
We would like to move away from jQuery Flot plugin over time and towards d3. So I would suggest using d3 (or c3 if necessary). You can use webpack or browserify to bundle these dependencies in an "external" plugin.

**Comment by minostauros** [comment]
This is exactly what I'm in need right now, hope you can share your work to make this upstream!

**Comment by sethgoldin** [comment]
Just found this issue and would like to bump it. Even something as simple as having a page in the cockpit UI that shows the output of `$ watch nvidia-smi` would be great. If the UI plotted the values from `$ watch nvidia-smi` over time, it would be amazing.

**Comment by sethgoldin** [comment]
Oops, I realize now that there's a terminal, so I actually _can_ run `$ watch nvidia-smi`. Still, plotting the different parameters over time would really be great.

**Comment by sprietNathanael** [comment]
I just found this issue too, and what @sethgoldin  would be really useful!

**Comment by martinpitt** [comment]
We will not do this as part of the cockpit project itself. However, we are hapy to assist you if you or someone else wants to write a third-party cockpit extension for that. 

 - https://cockpit-project.org/blog/creating-plugins-for-the-cockpit-user-interface.html
 - https://cockpit-project.org/blog/cockpit-starter-kit.html

**Comment by binbinsh** [comment]
I had made a plugin to monitor NVIDIA GPUs, try it here https://github.com/binbinsh/cockpit-gpu
