### ISSUE TITLE
add shared ports and volumes to docker container info

### ISSUE THREAD

**Issue by ikke-t** [cockpit-project/cockpit#5551]
Hi,

I just started with F25 on RasPi3. I started a container on it. One of the main use cases for container is to connect it to IP port, and to share storage from host to have persistent data. Those info are missing from details list from docker container info. It would be great to have it. One can set it in the container launch dialog.

![screen shot 2016-12-05 at 15 42 59](https://cloud.githubusercontent.com/assets/1146409/20887025/9240b4f6-bb01-11e6-8b13-3ea417bf5c3c.png)

**Comment by ikke-t** [comment]
$ rpm -qa docker*
docker-1.12.3-10.git7b5044b.fc25.armv7hl
docker-common-1.12.3-10.git7b5044b.fc25.armv7hl
$ rpm -qa cockpit*
cockpit-shell-125-1.fc25.noarch
cockpit-bridge-125-1.fc25.armv7hl
cockpit-networkmanager-125-1.fc25.noarch
cockpit-ws-125-1.fc25.armv7hl
cockpit-docker-125-1.fc25.armv7hl
cockpit-storaged-125-1.fc25.noarch

**Comment by ikke-t** [comment]
The info would be listed in here, see volumes and ports from docker inspect:

>         "Config": {
>             "Hostname": "556571da63ff",
>             "Domainname": "",
>             "User": "",
>             "AttachStdin": true,
>             "AttachStdout": true,
>             "AttachStderr": true,
>             "ExposedPorts": {
>                 "443/tcp": {},
>                 "80/tcp": {}
>             },
>             "Tty": true,
>             "OpenStdin": true,
>             "StdinOnce": true,
>             "Env": [
>                 "QEMU_EXECVE=1",
>                 "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
>             ],
>             "Cmd": null,
>             "Image": "sha256:06e60db7621b8da7749cab41961420f3baf0f0226d12472d22188cbe2a69b64e",
>             "Volumes": null,
>             "WorkingDir": "",
>             "Entrypoint": [
>                 "docker-run"
>             ],
>             "OnBuild": null,
>             "Labels": {}
>         },
>         "NetworkSettings": {
>             "Bridge": "",
>             "SandboxID": "192cc75128147c3270bcb7aee316523539386594c3364247a664c719a676fd2b",
>             "HairpinMode": false,
>             "LinkLocalIPv6Address": "",
>             "LinkLocalIPv6PrefixLen": 0,
>             "Ports": {
>                 "443/tcp": null,
>                 "80/tcp": null
>             },
>

**Comment by martinpitt** [comment]
Reopening, as this is also about shared ports.

**Comment by KKoukiou** [comment]
Closing this issue because the Docker plugin is being actively developed anymore.
Replacement should be https://github.com/cockpit-project/cockpit-podman/ so any RFEs should be opened on that repository.
