### ISSUE TITLE
docker memory shows wrong max

### ISSUE THREAD

**Issue by ikke-t** [cockpit-project/cockpit#5552]
Screenshot is from RasPi3, which has only 1G of mem. Docker page claims it has 8TB.

![screen shot 2016-12-05 at 15 42 59](https://cloud.githubusercontent.com/assets/1146409/20887177/3bf1bebe-bb02-11e6-8288-acd765a7c1c4.png)

$ rpm -qa docker*
docker-1.12.3-10.git7b5044b.fc25.armv7hl
docker-common-1.12.3-10.git7b5044b.fc25.armv7hl
$ rpm -qa cockpit*
cockpit-shell-125-1.fc25.noarch
cockpit-bridge-125-1.fc25.armv7hl
cockpit-networkmanager-125-1.fc25.noarch
cockpit-ws-125-1.fc25.armv7hl
cockpit-docker-125-1.fc25.armv7hl
cockpit-storaged-125-1.fc25.noarch

**Comment by petervo** [comment]
What does ```docker info``` and ```docker stats``` show?

**Comment by ikke-t** [comment]
Here you go:

> $ sudo docker info
> Containers: 1
>  Running: 1
>  Paused: 0
>  Stopped: 0
> Images: 1
> Server Version: 1.12.3
> Storage Driver: devicemapper
>  Pool Name: vgpi-docker--pool
>  Pool Blocksize: 524.3 kB
>  Base Device Size: 10.74 GB
>  Backing Filesystem: xfs
>  Data file: 
>  Metadata file: 
>  Data Space Used: 89.65 MB
>  Data Space Total: 3.196 GB
>  Data Space Available: 3.106 GB
>  Metadata Space Used: 69.63 kB
>  Metadata Space Total: 8.389 MB
>  Metadata Space Available: 8.319 MB
>  Thin Pool Minimum Free Space: 319.3 MB
>  Udev Sync Supported: true
>  Deferred Removal Enabled: true
>  Deferred Deletion Enabled: true
>  Deferred Deleted Device Count: 0
>  Library Version: 1.02.131 (2016-07-15)
> Logging Driver: journald
> Cgroup Driver: systemd
> Plugins:
>  Volume: local
>  Network: overlay null host bridge
> Swarm: inactive
> Runtimes: oci runc
> Default Runtime: oci
> Security Options: seccomp selinux
> Kernel Version: 4.8.10-300.fc25.armv7hl
> Operating System: Fedora 25 (Server Edition)
> OSType: linux
> Architecture: armv7l
> Number of Docker Hooks: 2
> CPUs: 4
> Total Memory: 970 MiB
> Name: raspi
> ID: CXYW:3SLK:HHRM:IIJ6:EKY3:YTBI:YUHZ:JAUM:CLXO:V4IL:2PFK:MUKJ
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Insecure Registries:
>  127.0.0.0/8
> Registries: docker.io (secure)
> 


> $ docker stats
> CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
> 556571da63ff        0.05%               6.047 MiB / 970 MiB   0.62%               648 B / 648 B       49.66 kB / 0 B      5
>

**Comment by petervo** [comment]
That looks pretty normal. I think the total is only supposed to be shown when the container has a memory limit set. But i'm guessing you didn't set one, is that right? @larskarlitski any ideas?

**Comment by ikke-t** [comment]
yeap, the memory consumption is ok in the docker, no problem there. The issue was the 8TB what the gui shows for it, which is totally wrong.

**Comment by larskarlitski** [comment]
Yeah, MemoryLimit doesn't seem to be set on the container, which makes cockpit use whatever is in `/sys/fs/cgroup/memory/memory.limit_in_bytes`. On the Raspeberry Pi 3, that is 8796093018112, or "8.0 TiB" according to `cockpit.format_bytes()`. 

I guess [this check in `cockpitcgroupsamples.c`](https://github.com/cockpit-project/cockpit/blob/master/src/bridge/cockpitcgroupsamples.c#L82) fails on that machine?

@ikke-t, can you please post the outputs of:
- `cat /sys/fs/cgroup/memory/memory.limit_in_bytes`
-  `python -c 'from gi.repository import GLib; print(GLib.MAXSIZE, GLib.MAXSSIZE)'`

Thanks!

**Comment by petervo** [comment]
@larskarlitski, I think the docker code doesn't go through the our c samples code but uses what docker report via it's api.

**Comment by ikke-t** [comment]
@larskarlitski here you are, some library missing from python to do that:

$ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
8796093018112
$ python -c 'from gi.repository import GLib; print(GLib.MAXSIZE, GLib.MAXSSIZE)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named gi.repository

**Comment by larskarlitski** [comment]
> @larskarlitski, I think the docker code doesn't go through the our c samples code but uses what docker report via it's api.

It prefers using `cgroup.memory.limit` if it is different from the MemoryLimit that docker reports (in fact it does when any of cpu usage, memory usage, or memory limit are different). I don't know why it does that. Maybe @mvollmer can shed some light on this? I'd prefer only using docker's limit and not showing the system's, especially since the values from cgroupfs are often fishy.

> $ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
8796093018112
$ python -c 'from gi.repository import GLib; print(GLib.MAXSIZE, GLib.MAXSSIZE)'
Traceback (most recent call last):
File "", line 1, in 
ImportError: No module named gi.repository

The second call failed, but I've verified on a friend's Raspberry that size_t is 32 bit indeed. This should be fixed with #5567.

**Comment by mvollmer** [comment]
> Maybe @mvollmer can shed some light on this?

Not really.  Maybe there was a time when docker didn't report any metrics and the only way to get them was from the cgroups?
