### ISSUE TITLE
cockpit doesn't show container storage graph

### ISSUE THREAD

**Issue by ikke-t** [cockpit-project/cockpit#5553]
See how the graph is missing alongside of mem/cpu

![screen shot 2016-12-05 at 15 50 16](https://cloud.githubusercontent.com/assets/1146409/20887284/a4dd18e2-bb02-11e6-8b0a-892718b36d3f.png)

$ rpm -qa docker*
docker-1.12.3-10.git7b5044b.fc25.armv7hl
docker-common-1.12.3-10.git7b5044b.fc25.armv7hl
$ rpm -qa cockpit*
cockpit-shell-125-1.fc25.noarch
cockpit-bridge-125-1.fc25.armv7hl
cockpit-networkmanager-125-1.fc25.noarch
cockpit-ws-125-1.fc25.armv7hl
cockpit-docker-125-1.fc25.armv7hl
cockpit-storaged-125-1.fc25.noarch

**Comment by petervo** [comment]
The design of the storage graph is a little different. Because so little is in use it is a little hard to see. @andreasn anything we should be doing differently here?

**Comment by andreasn** [comment]
Yeah, it looks a bit off right now.
I have some mockups for putting them in cards and make the storage card look a bit more interesting
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/containers/container-list-design.png)

**Comment by andreasn** [comment]
These are less precise with regards to time and percentage markers compared to the current UI though.

**Comment by andreasn** [comment]
Similar to this sparkline from Patternfly http://www.patternfly.org/pattern-library/data-visualization/sparkline/#/api

**Comment by marusak** [comment]
I am afraid this won't be implemented. No one found time for it in last three years and now docker is getting slowly into maintenance mode.
