### ISSUE TITLE
translation miss realmd

### ISSUE THREAD

**Issue by vanloswang** [cockpit-project/cockpit#5558]
@petervo @stefwalter 'Join domain' and 'Leave domain' UI is not translated properly.
![image](https://cloud.githubusercontent.com/assets/1133578/20919417/adc20a06-bbd6-11e6-9021-83fd625b62ae.png)

**Comment by petervo** [comment]
Thanks, should be fixed with #5559. Once that makes it in, i'll update zanata again.
