### ISSUE TITLE
Cockpit-Bridge reports no packages

### ISSUE THREAD

**Issue by sgarfinkel** [cockpit-project/cockpit#5568]
I've tried installing Cockpit on Raspbian using the tarballs. I've made sure to install all of the dependencies I'm aware of. Afterwards I installed Cockpit using the following commands:

```
./configure --disable-doc --disable-pcp --prefix=/usr
make
sudo make install
sudo cp tools/cockpit.debian.pam /etc/pamd.c/cockpit
sudo systemctl enable cockpit.socket
```

Then if I try `cockpit-bridge --packages`, it only reports a checksum:
```
checksum = da39a3ee5e6b4b0d3255bfef95601890afd80709
```

Likewise, trying to log in online, I get as far as the login page, then immediately hit a 404, presumably because I'm missing all of the packages for some reason. I know armhf isn't officially supported, but weirdly I was able to get this to work on my other Raspberry Pi. No idea why.

**Comment by petervo** [comment]
```G_MESSAGES_DEBUG=all cockpit-bridge --packages``` might give you a better idea of what is going on.

I'd suggest configuring with ```--prefix=/usr```. Packages should then be placed in /usr/share/cockpit

**Comment by sgarfinkel** [comment]
I'm not sure I understand. I used `--prefix=/usr` when I configured. And `G_MESSAGES_DEBUG=all` doesn't seem to do anything. Is that definitely a valid environment variable for cockpit-bridge?

**Comment by petervo** [comment]
Yes G_MESSAGES_DEBUG=all is a valid env var. Try configuring with --enable-debug.

Are there packages in /usr/share/cockpit?

**Comment by sgarfinkel** [comment]
Yeah. I'll try to recompile and report back.

**Comment by sgarfinkel** [comment]
Going to close this. It turns out I had an old, broken cockpit-bridge installed to `/usr/local/bin`, which was overriding the properly installed one in `/usr/bin`. Removing it fixed it.
