### ISSUE TITLE
docker: Fix icon alignment for images with vulnerabilities

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#5591]
It looks like the warning icon is a bit too high compared to the text `2 Vulnerabilities` next to it:

![screenshot from 2016-12-14 11-31-05](https://cloud.githubusercontent.com/assets/8711649/21178785/6c33ae70-c1f1-11e6-8ec7-1bab6546f307.png)

follow-up to #5259

**Comment by andreasn** [comment]
alerts.less has some css for dealing with this icon positioning problem in alerts
https://github.com/patternfly/patternfly/blob/64357c539ed7f8723f5dfe5b2c8680f869246cf6/src/less/alerts.less#L19

**Comment by andreasn** [comment]
How does this look?

![screenshot from 2016-12-14 13-11-03](https://cloud.githubusercontent.com/assets/209895/21181553/cb0b1566-c1fe-11e6-9aed-fed754afd033.png)

**Comment by larskarlitski** [comment]
> How does this look?

Perfect, thanks!
