### ISSUE TITLE
base: Unable to read non-mappable files

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#5597]
Some files can't be mapped, but we would still like to be able to read them via `cockpit.file`.

Example: Trying to read `/sys/kernel/kexec_crash_size` will result in the error
```
couldn't map: Failed to map fd: mmap() failed: No such device
```
https://github.com/cockpit-project/cockpit/blob/5196b70887fd89e0b4442ff55827fb7a71dfe14a/pkg/users/local.js#L86

We should probably provide a fallback solution here.

**Comment by stefwalter** [comment]
We really don't need to map at all in this case. No need to fall back, lets just use ```read()``` in ```on_idle_send_block()```

**Comment by stefwalter** [comment]
Actually, I think I remember why @mvollmer used mmap. And it had a good reason for a corner case. With ```read()``` need to be able to throttle loading the file if the queue gets too long, or ```cockpit-bridge``` can race the transport and run out of memory (with massive files). 

So we need to be able to have CockpitTransport note when it's send queue is too long, and have the fsread channel back down in ```on_idle_send_block()```
