### ISSUE TITLE
SSH pubkey auth not possible on Ubuntu?

### ISSUE THREAD

**Issue by gasinvein** [cockpit-project/cockpit#5623]
On Ubuntu (both primary and secondary servers) there is now option for pubkey auth, only password or kerberos are present.
Is this a bug or am I missed something?

Adding server with password auth enabled:
![screenshot_20161220_231429](https://cloud.githubusercontent.com/assets/4569691/21366567/527e3ff8-c70b-11e6-845e-b4f0fca72da7.png)
Adding server with password auth disabled:
![screenshot_20161220_231323](https://cloud.githubusercontent.com/assets/4569691/21366493/16c1453c-c70b-11e6-969c-bb7e3b7f825b.png)

User does have SSH pubkeys and they are listed and enabled in "authentication" menu.

**Comment by petervo** [comment]
The version of libssh on ubuntu is too old to support the way cockpit does public key authentication. Cockpit must be built with libssh 0.7 or greater to support it.
