### ISSUE TITLE
ssh connect error with custome port

### ISSUE THREAD

**Issue by kokspflanze** [cockpit-project/cockpit#5626]
Hi,

i have the problem that i can not connect to a other host with a custome port, like 2342, with port 22 all works fine, connect over command line between both servers works also, in logs i can also see no login try.

I have this problem on the add host page (input 127.0.0.1:2342)

![shot 12222016-12-17](https://cloud.githubusercontent.com/assets/1885435/21409940/a8ecb6bc-c7dd-11e6-94e2-9eb1c869f883.png)

and also on the troubleshoot popup, if i change later the port 22 to 2342

![shot 12222016-12-16](https://cloud.githubusercontent.com/assets/1885435/21409958/c18a7f38-c7dd-11e6-8ff0-7109d717f0bf.png)

On the Cockpit.Service Server run Fedora 25 with Cockpit 126 and on the host with the Cockpit.Bridge run Centos 7.3 with Cockpit 122

Thanks =)

**Comment by petervo** [comment]
We do test this as part of our automatic integration testing so I would expect this to work. Are there any messages in the journal?

**Comment by kokspflanze** [comment]
in message log is 

```
Dec 22 01:50:24 localhost audit: AVC avc:  denied  { name_connect } for  pid=7237 comm="cockpit-ssh" dest=2342 scontext=system_u:system_r:cockpit_ws_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=tcp_socket permissive=0
Dec 22 01:50:24 localhost cockpit-ssh: cockpit-ssh olli@127.0.0.1:2342: -1 couldn't connect: Failed to connect: Permission denied '127.0.0.1' '2342'
```

**Comment by kokspflanze** [comment]
@petervo would it be possible to add a hint for problems like this in the message?
