### ISSUE TITLE
Authentication Failed on Dashboard UI to add a new host

### ISSUE THREAD

**Issue by vanloswang** [cockpit-project/cockpit#5627]
Authentication Failed on Dashboard UI to add a new host with following error:
```bash
Cockpit was unable to log into 192.168.10.21. To use this machine with cockpit you will need to enable one of the following authentication methods in the sshd config on 192.168.10.21:

Password
Public Key
Kerberos Based SSO
```
the public key from /root/.ssh/id_rsa.pub is set on both hosts in /root/.ssh/authorized_keys. it always fails to connect to the peer host. one of the cockpit version is 122 and the other one is 125.  My sshd config is set to password auth now. 

log info from /var/log/messages:
```bash
cockpit-ssh: cockpit-ssh root@192.168.10.21:22: server offered unsupported authentication methods: unknown
```

**Comment by stefwalter** [comment]
Is this machine a VM which we could use to reproduce the issue? Perhaps by uploading the disk somewhere?

**Comment by vanloswang** [comment]
@stefwalter it is installed on bare metal server. I update it to 126, and login into the server 192.168.10.21 by    root user, but it tell me:
```bash
The server refused to authenticate 'root' using password authentication, and no other supported authentication methods are available.
```   
I have already set 'PermitRootLogin yes' in sshd config and restart sshd service.

**Comment by stefwalter** [comment]
Interesting. This used to work before right? Are there any other related failure messages in the journal, such as SELinux issues perhaps? Is this on Fedora using the prebuilt packages?

**Comment by vanloswang** [comment]
@stefwalter 
the steps to reproduce the issue are as following:
1. install two vms with CentOS-7-x86_64-Minimal-1610-01.iso 
2. compile cockpit 126 from fedora srpm
3. install cockpit-ws and cockpit-shell, and start cockpit
4. setup iptables rule to allow access cockpit
5. login to the other vm with Other Options in login ui 
Result:
login failed with 'Refusing to connect. Host is unknown'
Logs from /var/log/messages:
```bash
Dec 22 06:25:47 localhost cockpit-ws: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Dec 22 06:25:47 localhost cockpit-ssh: failed to open known hosts file /var/lib/cockpit/known_hosts
Dec 22 06:25:47 localhost cockpit-ssh: cockpit-ssh 192.168.10.17: refusing to connect to unknown host: 192.168.10.17:22
```

**Comment by vanloswang** [comment]
@stefwalter According to my memory, adding host is ok in 114 or 104, I found it failed in 125

**Comment by petervo** [comment]
@vanloswang, the unknown host error from this comment (https://github.com/cockpit-project/cockpit/issues/5627#issuecomment-268783339) is expected. To allow connecting to as of yet unknown hosts you can set the config option as described here. https://github.com/cockpit-project/cockpit/blob/master/doc/authentication.md

This error (https://github.com/cockpit-project/cockpit/issues/5627#issue-197111227) though is not expected. But I wasn't able to reproduce. Any additional log messages or hints on how to reproduce?

**Comment by vanloswang** [comment]
@petervo @stefwalter I add some code in src/ws/ssh.c, print the value of the four macros, then adding host is ok and no 'server offered unsupported authentication methods: unknown'. it is so weird. it seem like the time sequece has some problem. in my code, the if condition will not enter, because methods_to_try is not zero, so only the four g_message will realy excute.
```bash
  /* If interactive isn't supported try password instead */
  if (!(methods_server & SSH_AUTH_METHOD_INTERACTIVE) ||
      !data->auth_options->supports_conversations)
    {
      methods_to_try = methods_to_try | SSH_AUTH_METHOD_PASSWORD;
      methods_to_try = methods_to_try & ~SSH_AUTH_METHOD_INTERACTIVE;
    }

  **g_message ("methods_to_try: %d", methods_to_try);
  g_message ("SSH_AUTH_METHOD_PASSWORD: %d", SSH_AUTH_METHOD_PASSWORD);
  g_message ("SSH_AUTH_METHOD_INTERACTIVE: %d", SSH_AUTH_METHOD_INTERACTIVE);
  g_message ("SSH_AUTH_METHOD_GSSAPI_MIC: %d", SSH_AUTH_METHOD_GSSAPI_MIC);
  g_message ("SSH_AUTH_METHOD_PUBLICKEY: %d", SSH_AUTH_METHOD_PUBLICKEY);

  if (0 == methods_to_try)
    {
      methods_to_try = SSH_AUTH_METHOD_PASSWORD;
    }**

  while (methods_to_try != 0)
    {
      int (*auth_func)(CockpitSshData *data);
      const gchar *result_string;
      int method;
```
The log of the four g_message  is as following:
```bash
Dec 23 10:37:13 localhost cockpit-ssh: methods_to_try: 38
Dec 23 10:37:13 localhost cockpit-ssh: SSH_AUTH_METHOD_PASSWORD: 2
Dec 23 10:37:13 localhost cockpit-ssh: SSH_AUTH_METHOD_INTERACTIVE: 16
Dec 23 10:37:13 localhost cockpit-ssh: SSH_AUTH_METHOD_GSSAPI_MIC: 32
Dec 23 10:37:13 localhost cockpit-ssh: SSH_AUTH_METHOD_PUBLICKEY: 4
```

**Comment by petervo** [comment]
@vanloswang, were you able to figure out what the problem was?
