### ISSUE TITLE
Unable to receive json-rpc response

### ISSUE THREAD

**Issue by leopeng1995** [cockpit-project/cockpit#5638]
I know using curl in `spawn` can request the RESTful API and receive the response successfully. But when I try to add a new module to connect to json-rpc backend, it displayed nothing in the web-frontent. However, I use the same curl comamnd and parameters in the terminal, it can receive the proper json response. Is this a special case?

**Comment by petervo** [comment]
There's not really enough information here for me to be able to give concrete advise. Maybe if you added some code that shows what you are trying to do and what is not working as you expect that might help diagnose the issue.

Generally the cockpit functions return a promise that you use to see the result of the operation and do what you want with the data.

See:
http://cockpit-project.org/guide/latest/cockpit-http.html
http://cockpit-project.org/guide/latest/cockpit-spawn.html

and here's an example of the spawn command.

https://github.com/cockpit-project/cockpit/blob/master/examples/pinger/ping.html

**Comment by leopeng1995** [comment]
Thx... actually, I wrote this module refer to the official example pinger. It doesn't works. So I tried the **http client** approach you recommended and it works. But I don't know why.

**Comment by stefwalter** [comment]
Great. Glad it works. When you call ```cockpit.spawn``` it executes a process on the server. The ```cockpit.http``` connects to a local REST service on the server.
