### ISSUE TITLE
Debian builds are broken

### ISSUE THREAD

**Issue by TuningYourCode** [cockpit-project/cockpit#5640]
Hi,

i wanted to test cockpit on my debian jessie maschine.

Sadly there are some problems with dependencys:

root@majestix:~# apt-get install cockpit
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cockpit : Depends: cockpit-ws but it is not going to be installed
           Recommends: cockpit-docker but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@majestix:~# apt-get install cockpit cockpit-ws
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cockpit-ws : Depends: libgssapi-krb5-2 (>= 1.14+dfsg) but 1.12.1+dfsg-19+deb8u2 is to be installed
              Depends: libssh-4 (>= 0.7.3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@majestix:~#

Best regards

**Comment by zielot** [comment]
I just added the unstable repo to my Jesse server and only the cockpit-doc packages were found. I was just able to install unstable mediatomb using apt-get install mediatomb/unstable and assumed I could do the same with cockpit. 

I should also add that I am using the i386 architecture on Debian Jesse. (It's an old Mac Mini I am trying use as a media server).

**Comment by zielot** [comment]
This might help:

> W: Failed to fetch http://repo-cockpitproject.rhcloud.com/debian/dists/unstable/InRelease  Unable to find expected entry 'contrib/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by fey0** [comment]
That would probably be because your sources.list is wrong,

> deb http://repo-cockpitproject.rhcloud.com/debian/ unstable main

Is the correct entry, you used contrib instead of main.

**Comment by zielot** [comment]
yes, removing contrib gets rid of the error I mentioned. However the real problem is that there is nothing except cockpit-doc available in the Debian repo:
```
$ cat /var/lib/apt/lists/repo-cockpitproject.rhcloud.com_debian_dists_unstable_main_binary-i386_Packages 
Package: cockpit-doc
Source: cockpit
Version: 125-0
Architecture: all
Maintainer: Cockpit <cockpit@cockpit-project.org>
Installed-Size: 624
Homepage: http://cockpit-project.org/
Priority: optional
Section: doc
Filename: pool/main/c/cockpit/cockpit-doc_125-0_all.deb
Size: 288830
SHA256: c41d86fad3dca188a9c3940b83698bfa95ae1a584965587ac0e96e02676feb80
SHA1: 2e29af4ea027fa857665dc660a62dbfe576c52ad
MD5sum: 13e07b539c5781f524ba1dbca55359fc
Description: Cockpit deployment and developer guide
 The Cockpit Deployment and Developer Guide shows sysadmins how to deploy
 Cockpit on their machines as well as helps developers who want to embed
 or extend Cockpit.
```

**Comment by fey0** [comment]
I dont have any 32bit machines, so all I can say is that the 64bit repo has all packages.

**Comment by zielot** [comment]
I could try building the 32-bit packages if you can direct me towards a
list of steps. I've built binary Debs for myself before but it appears that
this one build on (and runs on?) Node.js.

**Comment by stefwalter** [comment]
The repo now targets both debian jessie and unstable. I hope this makes it easier for you to use Cockpit.

However the unstable builds are broken for unrelated reasons.
