### ISSUE TITLE
yakkety repository

### ISSUE THREAD

**Issue by rgarrigue** [cockpit-project/cockpit#5650]
Hi

Would it be possible to get a build for yakkety ? There's only xenial & devel [here](http://ppa.launchpad.net/cockpit-project/cockpit/ubuntu/dists/)

Regards,

**Comment by seffyroff** [comment]
This is preventing me from running Cockpit right now - Yakkety needed please.

`Err:7 http://ppa.launchpad.net/cockpit-project/cockpit/ubuntu yakkety/main amd64 Packages
  404  Not Found`

`W: The repository 'http://ppa.launchpad.net/cockpit-project/cockpit/ubuntu yakkety Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/cockpit-project/cockpit/ubuntu/dists/yakkety/main/binary-amd64/Packages  404  Not Found`

**Comment by martinpitt** [comment]
You can just add the "xenial" release for that PPA.
