### ISSUE TITLE
test preparation removes phantomjs

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#5676]
When following `test/README`, I first installed phantomjs (`npm install phantomjs-prebuilt`), then either
```
test/verify/run-tests --install
test/verify/run-tests --install
```

or an individual test with
```
test/verify/testsuite-prepare
test/verify/check-login
```

In both cases you get an error message:
```
/home/martin/upstream/cockpit/test/common/phantom-command: line 4: exec: phantomjs: not found
Restarting browser...
[...]
IOError: [Errno 32] Broken pipe
```
So in between test preparation and test execution one needs to re-run `npm install phantomjs-prebuilt` so that the test actually works.

The preparation step calls `autogen.sh` which calls
```
+ npm prune
unbuild fd-slicer@1.0.1
unbuild hasha@2.2.0
unbuild es6-promise@4.0.5
unbuild isexe@1.1.2
unbuild is-stream@1.1.0
unbuild kew@0.7.0
unbuild pend@1.2.0
unbuild progress@1.1.8
unbuild request-progress@2.0.1
unbuild throttleit@1.0.0
unbuild yauzl@2.4.1
unbuild which@1.2.12
unbuild extract-zip@1.5.0
unbuild phantomjs-prebuilt@2.1.14
```

and that seems to be what removes `node_modules/.bin/phantomjs`.

If that `npm prune` step in autogen.sh is necessary for some reason, I'm happy to submit a PR that (re-)installs phantomjs automatically, or at least adjusts the documentation accordingly. Otherwise, the prune could just be dropped from autogen.sh?

**Comment by stefwalter** [comment]
We've had problems with old dependencies sitting around in node_modules causing lots of problems on the verify machines. Does this help:

```
[stef@falcon cockpit]$ git diff
diff --git a/package.json b/package.json
index 3c858ec..41e3777 100644
--- a/package.json
+++ b/package.json
@@ -22,6 +22,7 @@
     "less": "~2.6.0",
     "less-loader": "~2.2.3",
     "ng-cache-loader": "0.0.16",
+    "phantomjs-prebuilt": "~2.1.14",
     "po2json": "~0.4.1",
     "promise": "~7.1.1",
     "raw-loader": "~0.5.1",
```

**Comment by martinpitt** [comment]
Yes, it does indeed. This makes running tests work OOTB again.

**Comment by mvollmer** [comment]
Didn't we tell people to install phantomjs globally? (npm install -g)?  Is that no longer an option?

**Comment by stefwalter** [comment]
Hmmm, maybe a long time ago. But it doesn't look like we were telling them that recently:

```
$ git grep phantomjs-prebuilt
HACKING.md:    $ npm install phantomjs-prebuilt
test/README:    $ npm install phantomjs-prebuilt
test/images/scripts/fedora-24.setup:npm -g install phantomjs-prebuilt
```
