### ISSUE TITLE
Add git hash to tools/make-srpm

### ISSUE THREAD

**Issue by sgallagher** [cockpit-project/cockpit#5679]
Right now, the output of `tools/make-srpm` is something like `cockpit-126.x-1.wip.fc25.src.rpm`. It would be helpful when tracking down issues in Coverity scans if the SRPM name (and tarball inside it) also included at least the short git hash.

**Comment by OllyNuralAND** [comment]
Can I give this a shot?

**Comment by martinpitt** [comment]
Olly Nural [2019-10-14 11:31 -0700]:
> Can I give this a shot?

Sure, go ahead! Thanks :)
