### ISSUE TITLE
creating new user fails on missing /usr/share/cracklib/pw_dict.pwd.gz

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#5684]
When installing cockpit into a minimal Fedora 25 VM, creating new users fails:
```
/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
Password quality check failed: The password fails the dictionary check - error loading dictionary
```

I only have
```
$ rpm -qa | grep cracklib
cracklib-2.9.6-4.fc25.x86_64
```
Installing `cracklib-dicts` fixes this, so this should be added to the spec file as a dependency.

**Comment by stefwalter** [comment]
Is this the case just on Fedora 25 or also on RHEL, CentOS and elsewhere. To quickly bring up such systems, just do:

```
./vm-run centos-7
```

or similar.

**Comment by martinpitt** [comment]
I filed this yesterday without much though while working on something else. On closer inspection, cockpit does not call cracklib by itself, but calls `pwscore`, which is what produces this error message:
```
$ echo foobar123 | pwscore
/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
Password quality check failed:
 The password fails the dictionary check - error loading dictionary
```

In Fedora 25 it's possible to uninstall `cracklib-dicts` without any problem, and I guess my minimal test env just never installed it in the first place. On CentOS 7 this doesn't work:
```
# rpm -e cracklib-dicts
error: Failed dependencies:
	cracklib-dicts >= 2.8 is needed by (installed) libpwquality-1.2.3-4.el7.x86_64
	cracklib-dicts >= 2.8 is needed by (installed) pam-1.1.8-18.el7.x86_64
```

IMHO the dependency should be (re-)added to `pwquality`, not cockpit, or pwscore should gracefully handle the absence of this package. I filed that here: https://bugzilla.redhat.com/show_bug.cgi?id=1410450.
