### ISSUE TITLE
Cockpit menu doesn't scroll

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#5727]
This will be a problem as we get more entries with smaller windows:
![screenshot from 2017-01-11 17-18-58](https://cloud.githubusercontent.com/assets/8711649/21856413/3a3bf200-d822-11e6-8a89-3d7c5b932dd4.png)

For devs, it's noticeable when there's a debug window open.

**Comment by garrett** [comment]
This should fix it:

```css
#sidebar { overflow-y: auto; }
```

I'm having Andreas assign it to me and I'll poke around the code and make the fix. It's a super-simple fix, but this is additional experience for getting my hands dirty with the code and pushing PRs to Cockpit. 😉
