### ISSUE TITLE
Storage error state is different from other error states

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#5728]
![screenshot from 2017-01-12 18-20-53](https://cloud.githubusercontent.com/assets/209895/21900413/006db630-d8f4-11e6-8b38-3b5713192526.png)

**Comment by andreasn** [comment]
Compare to SELinux, Software Updates and Subscriptions
![screenshot from 2017-01-12 18-20-43](https://cloud.githubusercontent.com/assets/209895/21900449/18fc341a-d8f4-11e6-925f-80bca973a1fe.png)

![screenshot from 2017-01-12 18-20-48](https://cloud.githubusercontent.com/assets/209895/21900457/1fb30b1c-d8f4-11e6-8fb1-93c3ae9dab66.png)

![screenshot from 2017-01-12 18-22-56](https://cloud.githubusercontent.com/assets/209895/21900465/2891ca52-d8f4-11e6-96de-d718b83d9b10.png)

**Comment by mvollmer** [comment]
@andreasn, how should it look?  Should it mention "please install udisks2"?

**Comment by andreasn** [comment]
Can we offer to install udisks2 there and then, using packagekit?
If so, I'll come up with a design.

**Comment by andreasn** [comment]
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/1f06cf98d328e75e6a68bb0fa71e00f882137d55/storage/error-udisks2.png)

**Comment by mvollmer** [comment]
> Can we offer to install udisks2 there and then, using packagekit?

Yeah, we have the infrastructure now for easy "on-demand" stuff.  Let's do this!

**Comment by martinpitt** [comment]
Hang on, this is wrong. The cockpit-storage package should depend on udisks2 already, so there shouldn't be a situation today where this happens.

**Comment by andreasn** [comment]
Yeah, unfortunately I can't remember how I managed to trigger the error.
Is the code for the error gone now?

**Comment by mvollmer** [comment]
One can run `systemctl mask udisks2; systemctl stop udisks2` and then reload the page.

But, yeah, it's probably not worth putting the "Install" button on the page.

**Comment by andreasn** [comment]
Makes sense, closing.
