### ISSUE TITLE
Dashboard not an obvious button

### ISSUE THREAD

**Issue by gbraad** [cockpit-project/cockpit#5741]
As part of first-time user experience, I believe the  Dashboard button does not really look like a button. This only becomes obvious after hover over. The word 'Dashboard' does not stand out on it's own as being an additional option, as the view what Cockpit shows can be interpreted as the dashboard view.

![2017-01-15](https://cloud.githubusercontent.com/assets/1894/21956655/4b933d4c-dac0-11e6-81e9-fae7beeb99c8.png)

**Comment by stefwalter** [comment]
CC @andreasn @garrett

**Comment by mcpaddy** [comment]
I ran into the same problem, when trying to add machines to cockpit. I did not realised that the dashboard was button, showing the screen to add the machines.

**Comment by gbraad** [comment]
Any ideas on how to solve this? This happened to more than one person so far... I just made it part of my demos now, but this should not be needed.

**Comment by garrett** [comment]
Andreas and I are considering this issue in the [Task Switcher design](https://github.com/cockpit-project/cockpit/wiki/Feature%3A-Task-Switcher).

**Comment by garrett** [comment]
This was addressed with the new navigation from Cockpit release 156.

http://cockpit-project.org/blog/cockpit-156.html

(Specifically PR https://github.com/cockpit-project/cockpit/pull/7482 + https://github.com/cockpit-project/cockpit/pull/8102)
