### ISSUE TITLE
Internal error in login process

### ISSUE THREAD

**Issue by asrob** [cockpit-project/cockpit#5742]
Background:
Fresh Fedora (25) Atomic Host installation, everything is up-to-date.

Steps to reproduce:

- Install and run cockpit/ws via `atomic run cockpit/ws`
- Check or uncheck "Reuse my password for privileged tasks" checkbox
- Log in

Error message: 
I can see this in the browser window:

> Internal error in login process

![screen shot 2017-01-15 at 6 35 21](https://cloud.githubusercontent.com/assets/251897/21960458/d6988c40-daec-11e6-8551-7d8ae1ed9c25.png)

- docker logs output:

> + sed -e /pam_selinux/d -e /pam_sepermit/d /etc/pam.d/cockpit
> + mkdir -p /host/etc/cockpit/ws-certs.d
> + chmod 755 /host/etc/cockpit/ws-certs.d
> + chown root:root /host/etc/cockpit/ws-certs.d
> + mkdir -p /host/var/lib/cockpit
> + chmod 775 /host/var/lib/cockpit
> + chown root:wheel /host/var/lib/cockpit
> + /bin/mount --bind /host/etc/cockpit /etc/cockpit
> + /usr/sbin/remotectl certificate --ensure
> INFO: cockpit-ws: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
> WARNING: cockpit-protocol: /usr/libexec/cockpit-ssh: couldn't recv: Connection reset by peer
> WARNING: cockpit-ws: /usr/libexec/cockpit-ssh: Auth pipe closed: internal-error
> MESSAGE: cockpit-protocol: couldn't read from connection: Error reading data from TLS socket: A TLS fatal alert has been received.
> MESSAGE: cockpit-protocol: couldn't read from connection: Error reading data from TLS socket: A TLS fatal alert has been received.
> WARNING: cockpit-protocol: /usr/libexec/cockpit-ssh: couldn't recv: Connection reset by peer
> WARNING: cockpit-ws: /usr/libexec/cockpit-ssh: Auth pipe closed: internal-error

**Comment by petervo** [comment]
Can you see if /usr/libexec/cockpit-ssh is present in the container? The lastest container is missing it. Once https://github.com/cockpit-project/cockpit-container/pull/7 is merged we a new one will be built.

**Comment by asrob** [comment]
Hi @petervo,

I think no, it's not.

>$ ls -la /usr/libexec/ | grep cockpit
> -rwsr-x---.  1 root cockpit-ws  27856 Jan 12 13:36 cockpit-session
> -rwxr-xr-x.  1 root root       322504 Jan 12 13:36 cockpit-stub
> -rwxr-xr-x.  1 root root       267488 Jan 12 13:36 cockpit-ws

**Comment by petervo** [comment]
@asrob thanks, a new container has been built. Can you try it and see if it fixes the problem?

**Comment by asrob** [comment]
@petervo yes, I updated cockpit container and looks good now. Thanks! :)
