### ISSUE TITLE
cannot install on ubuntu14.04

### ISSUE THREAD

**Issue by judypol** [cockpit-project/cockpit#5749]
1.Add the PPA for Cockpit:
sudo add-apt-repository ppa:cockpit-project/cockpit
2.Update the package information:
sudo apt-get update
3.Install cockpit:
sudo apt-get install cockpit

but I got the cannot found the cockpit package.

**Comment by stefwalter** [comment]
Currently Cockpit is built only for Ubuntu 16.04. @martinpitt is working in this area and things may change in the future. However it's unlikely that Cockpit will work well on Ubuntu 14.04, because it doesn't use systemd. Cockpit works well on systems that include systemd. Although Cockpit could work on systems without systemd ... nobody has put in the effort to make that happen (yet?).

**Comment by martinpitt** [comment]
systemd was recently backported to Ubuntu 14.04 in https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1616422 for supporting snappy, it runs as a kind of "deputy init". But to be honest, this is an utter hack, and as 14.04 has a very old systemd (204) that might not even support the things we expect in cockpit. For example, it does not yet have any polkit integration.

**Comment by stefwalter** [comment]
> But to be honest, this is an utter hack, and as 14.04 has a very old systemd (204) that might not even support the things we expect in cockpit. For example, it does not yet have any polkit integration.

Likely not insurmountable ... but requires putting in the effort to make it work with that older version. I would suggest we first focus on getting Cockpit into current versions of Ubuntu/Debian ... and then putting the effort towards backporting it.

However if someone wants to do this work, I'd help review pull requests, give pointers about possible solutions, etc.

**Comment by AGresvig** [comment]
Should it not work for 16.10, then? I see the same message..

**Comment by petervo** [comment]
I think the currently the ppa above only builds for 16.04. Though 16.10 is supported.

**Comment by martinpitt** [comment]
@AGresvig : the 16.04 builds ought to work fine on 16.10, just use "xenial" in the apt source instead of "yakkety".

**Comment by AGresvig** [comment]
ah ok, thanks!
