### ISSUE TITLE
Fedora, RHEL, Atomic: 'atomic storage reset' is broken

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#5750]
https://bugzilla.redhat.com/show_bug.cgi?id=1413862

The 'atomic storage reset' command has been broken by ```atomic-1.14.1-1.fc24```

```
# atomic storage reset
/usr/bin/atomic storage reset: too few arguments
Try '/usr/bin/atomic storage reset --help' for more information.
```

**Comment by stefwalter** [comment]
CC @rhatdan @lsm5

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker-storage", line 218, in testDevmapperVGroup
    self.testDevmapper("dockah")
  File "check-docker-storage", line 169, in testDevmapper
    b.wait_not_present(".modal-dialog:contains(Add Additional Storage)")
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 719, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 742, in _invoke
    raise Error(res['error'])
Error: timeout
[object Object]
```
First occurrence: 2017-01-17T09:54:57.961544 | revision 05ce1f9146840b50219f8a885b7e91401f31abe1, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5737-05ce1f91-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2017-01-17T09:54:57.961544 | revision 05ce1f9146840b50219f8a885b7e91401f31abe1, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5737-05ce1f91-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker-storage", line 218, in testDevmapperVGroup
    self.testDevmapper("dockah")
  File "check-docker-storage", line 169, in testDevmapper
    b.wait_not_present(".modal-dialog:contains(Add Additional Storage)")
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 719, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 742, in _invoke
    raise Error(res['error'])
Error: timeout
[object Object]
```
First occurrence: 2017-01-23T19:21:47.320311 | revision 9116a74ad896368ee31ddf1cd1cf137ca0631df9, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5587-9116a74a-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2017-01-23T19:21:47.320311 | revision 9116a74ad896368ee31ddf1cd1cf137ca0631df9, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5587-9116a74a-verify-fedora-25/log.html)

**Comment by cockpituous** [comment]
verify/fedora-atomic
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker-storage", line 169, in testDevmapper
    b.wait_not_present(".modal-dialog:contains(Add Additional Storage)")
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 719, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 742, in _invoke
    raise Error(res['error'])
Error: timeout
[object Object]
```
First occurrence: 2017-01-28T16:36:22.130488 | revision 9fa9d433525842b99bde1855b44e16ada81c5fcb, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5798-9fa9d433-verify-fedora-atomic/log.html)
Times recorded: 1
Latest occurrences:

- 2017-01-28T16:36:22.130488 | revision 9fa9d433525842b99bde1855b44e16ada81c5fcb, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5798-9fa9d433-verify-fedora-atomic/log.html)

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker-storage", line 169, in testDevmapper
    b.wait_not_present(".modal-dialog:contains(Add Additional Storage)")
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 719, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 742, in _invoke
    raise Error(res['error'])
Error: timeout
[object Object]
```
First occurrence: 2017-01-31T11:39:21.256486 | revision 658a9f229efc2cc7c8bc0f03c76b59a0e24ee1f2, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5822-658a9f22-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2017-01-31T11:39:21.256486 | revision 658a9f229efc2cc7c8bc0f03c76b59a0e24ee1f2, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5822-658a9f22-verify-fedora-testing/log.html)

**Comment by cockpituous** [comment]
verify/rhel-atomic
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker-storage", line 169, in testDevmapper
    b.wait_not_present(".modal-dialog:contains(Add Additional Storage)")
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 719, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 742, in _invoke
    raise Error(res['error'])
Error: timeout
[object Object]
```
First occurrence: 2017-02-02T12:28:31.529814 | revision def823ed75a396a04e1cbcd86e90b0f68451a762, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5815-def823ed-verify-rhel-atomic/log.html)
Times recorded: 1
Latest occurrences:

- 2017-02-02T12:28:31.529814 | revision def823ed75a396a04e1cbcd86e90b0f68451a762, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5815-def823ed-verify-rhel-atomic/log.html)

**Comment by cockpituous** [comment]
verify/continuous-atomic
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker-storage", line 169, in testDevmapper
    b.wait_not_present(".modal-dialog:contains(Add Additional Storage)")
  File "testlib.py", line 218, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 719, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 742, in _invoke
    raise Error(res['error'])
Error: timeout
[object Object]
```
First occurrence: 2017-02-02T13:38:24.535409 | revision a882380e9603ab932050946e9e6660d0f29fe7f6, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5820-a882380e-verify-continuous-atomic/log.html)
Times recorded: 1
Latest occurrences:

- 2017-02-02T13:38:24.535409 | revision a882380e9603ab932050946e9e6660d0f29fe7f6, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5820-a882380e-verify-continuous-atomic/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker-storage", line 163, in testDevmapper
    b.wait_not_present(".modal-dialog:contains(Add Additional Storage)")
  File "testlib.py", line 219, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 722, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 748, in _invoke
    raise Error(res['error'])
Error: timeout
[object Object]
```
First occurrence: 2017-03-02T16:35:37.392660 | revision 9ae1d7773445781a8fb829915eaa8e6e80f4d31d, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6014-9ae1d777-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-03-02T16:35:37.392660 | revision 9ae1d7773445781a8fb829915eaa8e6e80f4d31d, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6014-9ae1d777-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker-storage", line 169, in testDevmapper
    b.wait_not_present(".modal-dialog:contains(Add Additional Storage)")
  File "testlib.py", line 219, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 736, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 762, in _invoke
    raise Error(res['error'])
Error: timeout
[object Object]
```
First occurrence: 2017-03-14T08:16:26.657276 | revision c434ae3b88f97073ec14c7ebc1c84c6e5236a217, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6081-c434ae3b-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2017-03-14T08:16:26.657276 | revision c434ae3b88f97073ec14c7ebc1c84c6e5236a217, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6081-c434ae3b-verify-fedora-25/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker-storage", line 183, in testDevmapper
    b.wait_not_present(".modal-dialog:contains(Add Additional Storage)")
  File "testlib.py", line 221, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 741, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 767, in _invoke
    raise Error(res['error'])
Error: timeout
[object Object]
```
First occurrence: 2017-04-27T13:26:05.326854 | revision 353b18ec0eda742d61e7d309afef8ef6dbc8ecf2, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6360-353b18ec-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2017-04-27T13:26:05.326854 | revision 353b18ec0eda742d61e7d309afef8ef6dbc8ecf2, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6360-353b18ec-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker-storage", line 183, in testDevmapper
    b.wait_not_present(".modal-dialog:contains(Add Additional Storage)")
  File "testlib.py", line 221, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 745, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 771, in _invoke
    raise Error(res['error'])
Error: timeout
[object Object]
```
First occurrence: 2017-05-08T07:56:35.803604 | revision 162ecb0ae1fe2f332f08ebf2881e300c9a4c125a, [logs](http://fedorapeople.org/groups/cockpit/logs/master-162ecb0a-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2017-05-08T07:56:35.803604 | revision 162ecb0ae1fe2f332f08ebf2881e300c9a4c125a, [logs](http://fedorapeople.org/groups/cockpit/logs/master-162ecb0a-verify-fedora-25/log.html)

**Comment by cockpituous** [comment]
verify/fedora-atomic
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker-storage", line 184, in testDevmapper
    b.wait_not_present(".modal-dialog:contains(Add Additional Storage)")
  File "testlib.py", line 221, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "testlib.py", line 212, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 745, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 771, in _invoke
    raise Error(res['error'])
Error: timeout
[object Object]
```
First occurrence: 2017-05-15T21:42:29.557656 | revision dcbebc4f0677d687f3222476bbaa6a4d2d0b9e90, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6360-dcbebc4f-verify-fedora-atomic/log.html)
Times recorded: 1
Latest occurrences:

- 2017-05-15T21:42:29.557656 | revision dcbebc4f0677d687f3222476bbaa6a4d2d0b9e90, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6360-dcbebc4f-verify-fedora-atomic/log.html)
