### ISSUE TITLE
Fedora, RHEL, Atomic: atomic scan VulnerabilityInfo DBus API is broken

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#5754]
https://bugzilla.redhat.com/show_bug.cgi?id=1414010

The atomic scan VulnerabilityInfo DBus API has regressed in recent versions of ```atomic``` CLI command and DBus service. It just hangs until a timeout has been reached, if there is scan output on the system.

Likely this is a fix: https://github.com/projectatomic/atomic/pull/817

**Comment by cockpituous** [comment]
verify/fedora-24
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 574, in testBasic
    b.wait_present(row_selector + ' td span.pficon-warning-triangle-o')
  File "testlib.py", line 215, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 719, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 742, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-01-18T10:15:39.327209 | revision 04355a3747ec3fdc98c82e94e643b8620341f470, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5737-04355a37-verify-fedora-24/log.html)
Times recorded: 1
Latest occurrences:

- 2017-01-18T10:15:39.327209 | revision 04355a3747ec3fdc98c82e94e643b8620341f470, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5737-04355a37-verify-fedora-24/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 574, in testBasic
    b.wait_present(row_selector + ' td span.pficon-warning-triangle-o')
  File "testlib.py", line 215, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 719, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 742, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-01-23T15:17:08.954338 | revision 7ccd0349a53c076b89165a0bc4fe5329705d574f, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5587-7ccd0349-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2017-01-23T15:17:08.954338 | revision 7ccd0349a53c076b89165a0bc4fe5329705d574f, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5587-7ccd0349-verify-rhel-7/log.html)

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 574, in testBasic
    b.wait_present(row_selector + ' td span.pficon-warning-triangle-o')
  File "testlib.py", line 215, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 719, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 742, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-01-23T16:32:16.716175 | revision d7e6be9c656cd058165096d59338d3a65e7d2d89, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5587-d7e6be9c-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2017-01-23T16:32:16.716175 | revision d7e6be9c656cd058165096d59338d3a65e7d2d89, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5587-d7e6be9c-verify-fedora-25/log.html)

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 574, in testBasic
    b.wait_present(row_selector + ' td span.pficon-warning-triangle-o')
  File "testlib.py", line 215, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 719, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 742, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-01-31T11:39:15.566131 | revision 658a9f229efc2cc7c8bc0f03c76b59a0e24ee1f2, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5822-658a9f22-verify-fedora-testing/log.html)
Times recorded: 1
Latest occurrences:

- 2017-01-31T11:39:15.566131 | revision 658a9f229efc2cc7c8bc0f03c76b59a0e24ee1f2, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-5822-658a9f22-verify-fedora-testing/log.html)

**Comment by cockpituous** [comment]
verify/continuous-atomic
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 574, in testBasic
    b.wait_present(row_selector + ' td span.pficon-warning-triangle-o')
  File "testlib.py", line 215, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 722, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 745, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-02-07T17:41:58.991326 | revision 15ebc3127c4aacbb62e7f7d96f896b74c382c06b, [logs](http://fedorapeople.org/groups/cockpit/logs/master-15ebc312-verify-continuous-atomic/log.html)
Times recorded: 1
Latest occurrences:

- 2017-02-07T17:41:58.991326 | revision 15ebc3127c4aacbb62e7f7d96f896b74c382c06b, [logs](http://fedorapeople.org/groups/cockpit/logs/master-15ebc312-verify-continuous-atomic/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 574, in testBasic
    b.wait_present(row_selector + ' td span.pficon-warning-triangle-o')
  File "testlib.py", line 216, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 722, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 748, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-03-02T16:34:32.316366 | revision 9ae1d7773445781a8fb829915eaa8e6e80f4d31d, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6014-9ae1d777-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-03-02T16:34:32.316366 | revision 9ae1d7773445781a8fb829915eaa8e6e80f4d31d, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6014-9ae1d777-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-docker", line 600, in testBasic
    b.wait_present(row_selector + ' td span.pficon-warning-triangle-o')
  File "testlib.py", line 224, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "testlib.py", line 218, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "testlib.py", line 780, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "testlib.py", line 806, in _invoke
    raise Error(res['error'])
Error: timeout
```
First occurrence: 2017-05-05T13:38:03.306081 | revision ff3f64167e401c2c2abad93265a8da60155bb157, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6334-ff3f6416-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2017-05-05T13:38:03.306081 | revision ff3f64167e401c2c2abad93265a8da60155bb157, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-6334-ff3f6416-verify-fedora-25/log.html)
