### ISSUE TITLE
Allow cockpit working with official docker-engine

### ISSUE THREAD

**Issue by flexbrane** [cockpit-project/cockpit#5769]
Hello,

I'm on CentOS 7 and I'm using cockpit to do some monitoring. 

Since I have some troubles with the centos-docker package, I remove it and install the offcial docker-engine package.

But It seems that cockpit-docker is only compatible with the centos-docker package. 

Is there any solution / hack to install cockpit-docker along to docker-engine?

**Try to install cockpit-docker**

```sh
└─ ▶ yum install cockpit-docker --nodeps
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.quelquesmots.fr
 * epel: mirrors.ircam.fr
 * extras: centos.quelquesmots.fr
 * updates: centos.mirror.fr.planethoster.net
Resolving Dependencies
--> Running transaction check
---> Package cockpit-docker.x86_64 0:122-3.el7.centos will be installed
--> Processing Dependency: docker >= 1.3.0 for package: cockpit-docker-122-3.el7.centos.x86_64
--> Running transaction check
---> Package docker.x86_64 2:1.10.3-59.el7.centos will be installed
--> Processing Dependency: docker-common = 2:1.10.3-59.el7.centos for package: 2:docker-1.10.3-59.el7.centos.x86_64
--> Processing Dependency: container-selinux >= 2:1.10.3-59.el7.centos for package: 2:docker-1.10.3-59.el7.centos.x86_64
--> Running transaction check
---> Package container-selinux.x86_64 2:1.10.3-59.el7.centos will be installed
---> Package docker-common.x86_64 2:1.10.3-59.el7.centos will be installed
--> Processing Conflict: docker-engine-1.13.0-1.el7.centos.x86_64 conflicts docker
--> Processing Conflict: docker-engine-1.13.0-1.el7.centos.x86_64 conflicts docker-io
--> Processing Conflict: docker-engine-selinux-1.13.0-1.el7.centos.noarch conflicts docker-selinux
--> Finished Dependency Resolution
Error: docker-engine conflicts with 2:docker-1.10.3-59.el7.centos.x86_64
Error: docker-engine-selinux conflicts with 2:container-selinux-1.10.3-59.el7.centos.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Docker version**

```sh
└─ ▶ docker --version
Docker version 1.13.0, build 49bf474
```

**CentOS version**

```sh
└─ ▶ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
```

**Comment by stefwalter** [comment]
I wonder if we can depend on /usr/bin/docker instead in our spec file. What do you think Dominik? Then any RPM that provides that file can be used as the dependency.

**Comment by stefwalter** [comment]
er .. CC @dperpeet ... question above for you.

**Comment by johanwasserman** [comment]
Hi all,
any progress on this?  I have the same issue;

Error: Package: cockpit-docker-126-1.el7.centos.x86_64 (/cockpit-docker-126-1.el7.centos.x86_64)
           Requires: docker >= 1.3.0

Linux version
Red Hat Enterprise Linux Server 7.3 (Maipo)

docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by johanwasserman** [comment]
Also tried with 131;

Marking cockpit-docker-131-1.fc25.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package cockpit-docker.x86_64 0:131-1.fc25 will be installed
--> Processing Dependency: docker >= 1.3.0 for package: cockpit-docker-131-1.fc25.x86_64
--> Finished Dependency Resolution
Error: Package: cockpit-docker-131-1.fc25.x86_64 (/cockpit-docker-131-1.fc25.x86_64)
           Requires: docker >= 1.3.0

**Comment by stefwalter** [comment]
There's unsuccessful work to try and resolve this in #5943 ... could you comment there?

**Comment by johanwasserman** [comment]
will do, thanks Stef

**Comment by Wolfereign** [comment]
Is there any update to this?  The package seems to still be broken in Ubuntu.

**Comment by martinpitt** [comment]
@Wolfereign: What is the remaining problem? `cockpit-docker` only `Recommends: docker.io | docker-engine`, so if you want to use a different implementation you can remove the docker package and keep cockpit-docker.

**Comment by flexbrane** [comment]
For me the problem is solved!

```bash
$ docker --version
Docker version 17.10.0-ce, build f4ffd25
```

```bash
$ yum info docker
[...]
Nom                 : docker
Architecture        : x86_64
Date                : 2
Version             : 1.12.6
Révision            : 55.gitc4618fb.el7.centos
Taille              : 15 M
Dépôt               : extras/7/x86_64
Résumé              : Automates deployment of containerized applications
URL                 : https://github.com/docker/docker
Licence             : ASL 2.0
Description         : Docker is an open-source engine that automates the deployment of any
                    : application as a lightweight, portable, self-sufficient container that will
                    : run virtually anywhere.
                    :
                    : Docker containers can encapsulate any payload, and will run consistently on
                    : and between virtually any server. The same container that a developer builds
                    : and tests on a laptop will run at scale, in production*, on VMs, bare-metal
                    : servers, OpenStack clusters, public instances, or combinations of the above.
```

```bash
$ yum info cockpit-docker
[...]
Nom                 : cockpit-docker
Architecture        : x86_64
Version             : 148
Révision            : 1.el7.centos
Taille              : 249 k
Dépôt               : installed
Depuis le dépôt     : extras
Résumé              : Cockpit user interface for Docker containers
URL                 : http://cockpit-project.org/
Licence             : LGPLv2+
Description         : The Cockpit components for interacting with Docker and user interface.
                    : This package is not yet complete.
```
