### ISSUE TITLE
Ubuntu launchpad feed broken

### ISSUE THREAD

**Issue by nunojpg** [cockpit-project/cockpit#5799]
Err:10 http://ppa.launchpad.net/cockpit-project/cockpit/ubuntu yakkety/main amd64 Packages
  404  Not Found

**Comment by martinpitt** [comment]
The PPA only publishes for xenial (16.04 LTS) and for the current development series (zesty now), so this is intended. If you are on yakkety, using the xenial cockpit packages should work.
