### ISSUE TITLE
Containers - images not displayed when untagged

### ISSUE THREAD

**Issue by abonas** [cockpit-project/cockpit#581]
Scenario:
1. docker pull 'fedora:latest'
2. run a container with this image
3. in cockpit UI, go to Containers - Images section, select this image and press "delete".
4. The following error occurs:
"Unexpected error
Conflict, cannot delete b7de3133ff98 because the container 85c7bb280644 is using it (docker untagged the image), use -f to force"
5. The image is not deleted (which is OK because there's a container that is using it), but since it was untagged by docker, it is no longer displayed in cockpit UI.
6. When doing in command line 'docker images' it is displayed (without a tag, of course).
7. After doing in command line 'docker tag <imgId> fedora:latest', it reappears in cockpit UI.

The bug here IMHO is that after image is attempted to be deleted (and is not actually deleted, just untagged), it stops appearing in the cockpit UI which is misleading to the user who tried to delete, got an error that it wasn't actually deleted, and still it disappeared from UI.

**Comment by martinpitt** [comment]
Our docker UI is on maintenance, any work should be done on cockpit-podman.
