### ISSUE TITLE
log in screen tab order is incorrect

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#5819]
## Expected

Tabbing from one field to the other should happen in a logical order (usually top to bottom, left to right). 

This order would be:
1. username
2. password
3. reuse password
4. log in
5. connect to (with automatic expansion)

## Current implementation

1. username
2. password
3. log in
4. reuse password
5. ??? (not visible)

## Solution

I suggest dropping the `tabindex` whenever possible. (See http://webaim.org/techniques/keyboard/tabindex). If `tabindex` is actually needed (sub-optimal, but sometimes necessary), then assign & reorder numbers for `tabindex` values.

Secondly, there should be an accessible way to get to the connect to form via keyboard. (However, this probably should be handled by another bug and addressed by a different patch.)

Also, we probably need to evaluate keyboard navigation and other accessibility related features across the rest of Cockpit too.

**Comment by dperpeet** [comment]
Solved in #5821, commit https://github.com/cockpit-project/cockpit/commit/4ff65893b7ac7551f3f140519aec664472807edc
