### ISSUE TITLE
log in screen `other options` is not accessible using a keyboard

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#5823]
## Summary

Connect to form's disclosure element should be reworked to be an `<a>` and/or `<label>` tag so it can be tabbed to and activated. When activated, it should focus the connect-to form.

(This is related to #5819)

## Suggestion

This all can be done with pure HTML and would not need to rely on JavaScript.

Right now, the code looks like this:

```html
<div class="col-sm-5 col-md-5">
  <i id="option-caret" class="caret caret-down" aria-hidden="true" classname="caret caret-down">
    <svg height="16" width="16" viewBox="0 0 16 16">
      <polygon fill="#ffffff" points="4,0 4,14 12,7"></polygon>
      <polygon>
      </polygon></svg>
  </i>
  <span>Other Options</span>
</div>
```

Also, for reference, the server input is:

```html
<input class="form-control" id="server-field" type="text">
```

Perhaps something like this may make sense:

```html
<div id="option-group" style="display: block;">
  <div class="col-sm-5 col-md-5">
    <i id="option-caret" class="caret caret-right" aria-hidden="true">
      <svg height="16" width="16" viewBox="0 0 16 16">
        <polygon fill="#ffffff" points="4,0 4,14 12,7"></polygon>
        <polygon>
        </polygon></svg>
    </i>
    <span>Other Options</span>
  </div>
</div>
```

...and make #`option-group` activate on an `active` event as well as `click` event.

Using a label like this should then automatically expand and focus the element.

**Comment by martinpitt** [comment]
This was fixed a while ago.
