### ISSUE TITLE
Design patterns: Headers have unpredictable size

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#5885]
Followup to PR #5882

**On the page Design Patterns:**
![screenshot from 2017-02-13 14-58-29](https://cloud.githubusercontent.com/assets/209895/22886149/e975b7b2-f1fc-11e6-8617-6510718ddb6e.png)

The headers "Dialogs" and "On/Off Switch" are smaller than "Listing with Panels", "Expandable Listing: Panel header is row" and "Listing with Timeline" for no apparent reason.
I think they should all be the same size.

**On the page React Patterns:**
![screenshot from 2017-02-13 15-05-16](https://cloud.githubusercontent.com/assets/209895/22886384/db25c1b0-f1fd-11e6-9967-cbbcfe3f0165.png)

The headers "Tooltip", "Dialogs", "Listing Pattern" and "OnOff Switch" are smaller than "Demo Listing Pattern with expandable rows" and "Demo Empty Listing Pattern"
Here the hierarchy is broken in the sense that "Listing Pattern" a parent to "Demo Listing Pattern with expandable rows" and "Demo Empty Listing Pattern" is smaller than it's children.

**Comment by andreasn** [comment]
http://www.patternfly.org/styles/typography/#_ for reference

**Comment by andreasn** [comment]
@garrett @dperpeet what do you think?

**Comment by garrett** [comment]
I missed this in my notifications (I still had a flood of OSAS related stuff back then too — whoops!) and agree, they should be consistent.

I prefer the larger headings, such as "Listing with Panels".

**Comment by larskarlitski** [comment]
Still relevant and should be an easy fix.

**Comment by martinpitt** [comment]
This was fixed somewhere in between the PF4 rework.
