### ISSUE TITLE
[Ubuntu 16.04LTS]Cockpit doesn't show harddisk section and some questions

### ISSUE THREAD

**Issue by piperun** [cockpit-project/cockpit#5910]
This is an quite old issue for me, but essentially I can't access the hard disk section (started to happen around early autumn), since it's not existent (but was when I first installed storaged and cockpit) in the options.

And if I click on the Hardisk I/O graph, I get "Not Found".

Of course my assumption is that cockpit has broken compatibility with 2.5 version but it's the only version available for use for Ubuntu (since the maintainer at launchpad hasn't updated it to the latest 2.6 version).

Cockpit version:
`
Version: 131
Protocol: 1
Payloads: dbus-json3 http-stream1 http-stream2 stream fsread1
    fsreplace1 fswatch1 fslist1 null echo metrics1 websocket-stream1
Authorization: crypt1
`

from `dpkg -l` 
`storaged                   2.5.0-6`

**Comment by stefwalter** [comment]
@mvollmer is probably best able to help with this question/bug. I've removed the unrelated questions, since dealing with a single question per issue is much easier.

**Comment by mvollmer** [comment]
> Of course my assumption is that cockpit has broken compatibility with 2.5 version but it's the only version available for use for Ubuntu (since the maintainer at launchpad hasn't updated it to the latest 2.6 version).

We do test this combination, so things _should_ work for you.

Can you show screenshots of Cockpit in the broken state?  Also, could you show the contents of the browser console (Ctrl-Shift-K)?

**Comment by piperun** [comment]
Oh, apologize for the assumption then.
![chrome_2017-02-21_14-24-56](https://cloud.githubusercontent.com/assets/1145126/23166712/fac666ba-f841-11e6-984b-e8a73cf5d4b7.png)

the address is ip:9090/storage

Also for the other questions, should I open seperate issues for them or where can I get info about those?

**Comment by stefwalter** [comment]
I would suggest: ```apt-get install cockpit-storaged```

CC @andreasn By the way, another real world example of your idea to make it easier to install parts of Cockpit or parts of the server ^^

**Comment by andreasn** [comment]
Yeah. I was thinking of doing software package updates first, but it doesn't seem to materialize (Kalev is busy with other projects) so maybe this is a good place to start.

**Comment by piperun** [comment]
Sorry for late reply (kernel update taking forever).

This was indeed the problem, thanks for helping out so quickly!
