### ISSUE TITLE
Kubernetes Makefile.deps fail when compiling from source on rpi3

### ISSUE THREAD

**Issue by moretocome** [cockpit-project/cockpit#5919]
I am trying to compile cockpit from source on a Raspberry Pi 3 running Raspbian 8. But ```make``` fails when trying to generate the Makefile.deps for Kubernetes.

```../autogen.sh --disable-pcp --disable-doc``` completes successfully if I clone the git repository (had problems with the released tarballs) and ```cd cockpit && mkdir build && cd build```, but ```make``` fails on:

```
  GEN      dist/kubernetes/Makefile.deps

Killed

make  all-am

make[1]: Entering directory '/home/[username]/apps/cockpit/build'

  GEN      dist/kubernetes/Makefile.deps

Killed
```
and finally:
```
make[1]: *** No rule to make target 'dist/kubernetes/Makefile.deps', needed by 'all-am'.  Stop.

make[1]: Leaving directory '/home/[username]/apps/cockpit/build'

Makefile:2741: recipe for target 'all' failed

make: *** [all] Error 2
```

No other errors are thrown.

NodeJS v. 6.9.5
Go version go1.7.4 linux/arm

Help will be greatly appreciated.

**Comment by petervo** [comment]
Strange, haven't seen a ```Killed``` like that before. Could you put the full build log in a paste bin somewhere so we can take a look at it? Hoping there will be a few hints in there.

**Comment by moretocome** [comment]
I am not sure, what you mean by "full build log".
If i run ```make &> make.log```
the full contents of make.log is:
```
  GEN      dist/kubernetes/Makefile.deps

Killed

make  all-am

make[1]: Entering directory '/home/[username]/apps/cockpit/build'

  GEN      dist/kubernetes/Makefile.deps

Killed

make[1]: *** No rule to make target 'dist/kubernetes/Makefile.deps', needed by 'all-am'.  Stop.

make[1]: Leaving directory '/home/[username]/apps/cockpit/build'

Makefile:2741: recipe for target 'all' failed

make: *** [all] Error 2
```
The first time i saw a lot of output, but it seems everything else has compiled correctly, so now I only see the unsuccessful attempt to compile kubernetes.

I have posted the content of config.log [here](http://pastebin.com/ziLh2ia9).

**Comment by petervo** [comment]
```make clean``` should be able to have you start from scratch again.

What i'm trying to figure out is which command is getting killed and why. Unfortunately I don't have access to a armv7l to try it out myself.

**Comment by petervo** [comment]
Yeah there's not a whole lot there maybe ```make -d``` will show more?

**Comment by moretocome** [comment]
make -d produced a lot more output. Unfortunately the "make -d.log" file is way to big for pastebin (17MB).

The lines mentioning kubernetes are first [here](http://pastebin.com/vYR2c5E6), then [here](http://pastebin.com/2YfqPDQz), then [here](http://pastebin.com/tcUm3inW), and finally [here](http://pastebin.com/QQkkWYmB).

I have uploaded the entire log file to zippyshare [here](http://www111.zippyshare.com/v/zdU8XYsu/file.html).

**Comment by moretocome** [comment]
Can you make anything of this @petervo? Or should I try to upload the "make -d.log" to another hoster?

**Comment by petervo** [comment]
Thanks for the logs, unfortunately it still only says ```killed```. It's definitely the webpack/javascript part, not the go piece. My best guess that this point is memory exhaustion. Is there anything in the journal or system logs to indicate that might be the case?

**Comment by moretocome** [comment]
I don't know, but I will try again later and see what is says. But in the mean time, do you know if there is a relevant memory limit I could raise?
The new Raspian has a very smalle page file. I could also enlarge that temporarily. I will try and experiment at bit and report back here. Thank you for your time!

**Comment by moretocome** [comment]
I moved the swap to an external hdd and increased the size to 1024MB, and now the ´´´make´´´ process completes without errors. Thanks for the help..
