### ISSUE TITLE
get rid of SHA1

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#5940]
SHA-1 has been seriously wounded for about a decade now, but now it's completely dead: https://shattered.it/

We should review our usage of it, like in src/common/cockpitknownhosts.c `matches_hashed()`
```C
  hmac = g_hmac_new (G_CHECKSUM_SHA1, (guchar *)copied, salt_length);
```

**Comment by petervo** [comment]
The use there is because of the behavior of ssh-keygen -H. That behavior would need to change before we can change anything.

**Comment by petervo** [comment]
Also note, that we only use this code for deciding whether or a specific host is in our known hosts file before attempting to open a ssh connection to a server. This is necessary because the known hosts file can be hashed. Any actually verification is done by libssh, not this code.

**Comment by martinpitt** [comment]
Right, that part sounds fine. I took a look at the other usages:

 * The usage in websocketserver.c actually *is* security sensitive, but it's prescribed in [the protocol spec](https://tools.ietf.org/html/draft-ietf-hybi-thewebsocketprotocol-17) so we can't just change it.
 * src/ws/mock-kdc.conf.in allows sha1 hashes which should be dropped at some point; if for nothing else than to prove that our side of it doesn't depend on it.
 * checksums in cockpitpackages.c aren't security sensitive
 * checksums in test/vm-create are little more than a version number, not sensitive

**Comment by stefwalter** [comment]
Thanks for looking through everything. Some more notes:

 * The WebSocket RFC describes its use of SHA-1 as non security related. See Section 10.8 https://tools.ietf.org/html/draft-ietf-hybi-thewebsocketprotocol-17#page-57
 * The use in mock-kdc.conf.in is stock kerberos configuration. Kerberos and distro packages of MIT kerberos should drop SHA-1 here. But you can try removing this and make sure that these unit tests pass on all our target operating systems. Should be a simple pull request.
 * We can change the use in cockpitpackages.c if it helps with auditing. There is no backwards compatibility guarantee broken here by changing it.
 * Ditto for the use in our test images. All we need is a unique identifier. A simple pull request should help here. Perhaps a new test dependency?

**Comment by martinpitt** [comment]
I updated the previous comment with the current state. The websocket one is outside of our reach, and the other three have PRs or got fixed. But two more instances popped up now:

 - src/common/cockpitknownhosts.c uses SHA1. This is security sensitive (although very mildly), but we need to stay compatible to what openssh actually does. It's utterly hard to find what hash ssh currently uses (neither the manpage nor a google search answer that), so this needs a bit more research.

 - The new pkg/storaged/cockpit-clevis-tool.py uses SHA1 in `compute_thp()`. @mvollmer, do you know if that is by spec, or can be changed?

**Comment by mvollmer** [comment]
> The new pkg/storaged/cockpit-clevis-tool.py uses SHA1 in `compute_thp()`. @mvollmer, do you know if that is by spec, or can be changed?

This has to match what clevis itself does. SHA1 is used to compute the fingerprint of a key which people are then supposed to compare. So I guess this is security sensitive.

**Comment by larskarlitski** [comment]
>     * src/common/cockpitknownhosts.c uses SHA1. This is security sensitive (although very mildly), but we need to stay compatible to what openssh actually does. It's utterly hard to find what hash ssh currently uses (neither the manpage nor a google search answer that), so this needs a bit more research.

It uses it to compare to a hash generated by openssh, right? I don't see how we could be able to get rid of it. @Gundersanne what do you think?

**Comment by martinpitt** [comment]
This code now only runs with libssh 0.7, for 0.8 we use libssh's builtin API (which hopefully uses SHA256 now). So this part is done.

Which means that everything that we *can* do now, we did. Thus I close this now.
