### ISSUE TITLE
Testing README clarifications

### ISSUE THREAD

**Issue by ncoghlan** [cockpit-project/cockpit#5962]
I'm attempting to follow the directions in https://github.com/cockpit-project/cockpit/blob/master/test/README and currently receive the following output attempting to run `sudo ./test/vm-prep`:

```
$ sudo ./test/vm-prep
Network cockpit1 defined from ./test/common/network-cockpit.xml

Network cockpit1 marked as autostarted

Network cockpit1 started

rmmod: ERROR: Module kvm_amd is not currently loaded
```

All of the given test dependencies other than `expect` were already installed.

I *think* it may just be a spurious error from the setup script, as the tests seem to be running OK (I only just started the test run, so I'll update this once it finishes)

**Comment by ncoghlan** [comment]
Update after a few of the tests started to complete: they all seem to be consistently failing, complaining about `No files found for cockpit.service`. This is a typical failure message:

```
# ----------------------------------------------------------------------
# testBasic (check_reauthorize.TestReauthorize)
#
https://fedorapeople.org/groups/cockpit/images/fedora-25-72af2f835d70af73d8955823c6bf4d226ee77d55.qcow2.xz
######################################################################## 100.0%
No files found for cockpit.service.
Failed to start cockpit.socket: Unit cockpit.socket not found.
Wrote TestReauthorize-testBasic-FAIL.png
Journal extracted to TestReauthorize-testBasic-10.111.118.176-FAIL.log
Core dumps downloaded to TestReauthorize-testBasic-10.111.118.176-FAIL.core
not ok 1 testBasic (check_reauthorize.TestReauthorize) duration: 630s
Traceback (most recent call last):
  File "./test/verify/check-reauthorize", line 29, in testBasic
    self.login_and_go("/playground/test", authorized=False)
  File "/home/ncoghlan/fedoradevel/cockpit/test/common/testlib.py", line 537, in login_and_go
    self.machine.start_cockpit(host)
  File "/home/ncoghlan/fedoradevel/cockpit/test/common/testvm.py", line 608, in start_cockpit
    """)
  File "/home/ncoghlan/fedoradevel/cockpit/test/common/testvm.py", line 412, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command '<script>' returned non-zero exit status 5
```

**Comment by ncoghlan** [comment]
Notes based on further experimentation and chatting to @petervo on IRC:

- the `rmmod` error looks spurious: `vm-prep` uses the `kvm-amd` and `kvm-intel` config files to decide which kernel modules to configure and attempt to reload, but this machine has both config files (even though it's an Intel CPU).
- need to check BIOS settings to ensure nested virt is enabled (vm-prep enables it in the kernel KVM drivers, but that won't help if it's turned off in the BIOS)
- need to run `./test/verify/testsuite-prepare` before running the test suite itself
- `automake` is missing from the list of components to pre-install (needed for `aclocal`)

**Comment by ncoghlan** [comment]
The test suite is looking much happier with the above changes, so I think there are two potentially useful enhancements here:

- update test/README to cover all of these points
- add an early check to `run-tests` that looks to see if the project has actually been built first and aborts the test run if it hasn't

**Comment by martinpitt** [comment]
Confirmed that the rmmod message is just (confusing) noise. test/README actually does document that you need to run `testsuite-prepare` first. I also stumbled over the "no automake/build deps installed on the host" situation (I always build in mock, not the host), and added this to the README not too long ago:

    This either needs a configured/built tree (build in mock or a development VM)
    or cockpit's build dependencies installed.

but maybe this isn't obvious enough. TBH I would avoid enumerating all of cockpit's build dependencies in the README -- it's a rather big piece of redundancy which will quickly go out of sync with reality, and at least personally I don't like having development packages installed on my host (that's what mock/schroot/etc. are for). If you want to document this, I'd rather describe how to get the list of build deps from `cockpit.spec` or `tools/debian/control`.

Personally I use

    mock -i $(sed -n '/^BuildRequires:/ {s/^.*: //; s/>=.*$//; p}' tools/cockpit.spec)

**Comment by stefwalter** [comment]
> Personally I use:

Worth a pull request?

**Comment by mvollmer** [comment]
> and added this to the README not too long ago:

This is pretty far down in the document.  We should make sure that the quick start steps in the introduction section are complete.

**Comment by ncoghlan** [comment]
https://github.com/cockpit-project/cockpit/pull/5965 is an initial attempt at a PR for this. Between `HACKING` and `test/README.md`, I found 3 different places that described getting the build and test dependencies, and tried to consolidate them into one.
