### ISSUE TITLE
Virtual Machines module's State column related information is not displayed with qemu/KVM..

### ISSUE THREAD

**Issue by Ricky-Tigg** [cockpit-project/cockpit#5967]
Hi. Tested in root an others users’ sessions, in both Firefox and Chrome-based browsers with url https://localhost:9090, the Virtual Machines module does not display its State column related information; it does not update it automatically either manually so the tool is inoperative to inform about the qemu/KVM machines’ states. At best the State feature has randomly worked and rarely.

**Comment by martinpitt** [comment]
I ran into a very similar problem, and just discovered that this is broken if the display language (in the upper right menu) is *not* English:

![fails-de](https://cloud.githubusercontent.com/assets/200109/26831162/ac601728-4acb-11e7-966a-e8314bd7057d.png)

Once I switch it to English, it starts to work:

![works-en](https://cloud.githubusercontent.com/assets/200109/26831178/ba809a30-4acb-11e7-890a-815b21634a7f.png)

and I can also expand it to see the Run/Restart/Shutdown buttons.

Can you please check if you have the same issue?

**Comment by martinpitt** [comment]
cc  @mareklibra

**Comment by mareklibra** [comment]
@martinpitt , it's same issue. I'll provide fix shortly.
