### ISSUE TITLE
Registry: changing users causes stale overview/images pages

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#5983]
While working on [a registry bug](https://bugzilla.redhat.com/show_bug.cgi?id=1373448), my new test case for that spotted a refresh bug when changing users:

 * Run our openshift test VM (`test/vm-run openshift`) and log into Cockpit.
 * On http://localhost:9090/kubernetes, check in the "wrench" dialog box (top right) that you are logged in as `system:admin`.
 * On http://localhost:9090/kubernetes/registry (Overview, Projects, and Images tabs) you can see all images and projects.
 * Go back to "Cluster" (http://localhost:9090/kubernetes) and use the wrench to log in as "amanda" (use any password).
 * Go back to "Image registry", and see that Overview, Projects, and Images tabs still all show all projects and data, even through amanda is not supposed to see them and doesn't have permisions on those. Reloading the page (Ctrl+R) then updates it correctly.

So the image registry pages need to be invalidated when changing users.

**Comment by petervo** [comment]
The problem here is that you are mixing the kubernetes and registry packages. Changing this user in the kubernetes package doesn't affect the registry package. They are two separate packages. I'm not sure this really is a problem as they aren't normally installed side by side outside of dev environments. The kubernetes package contains all the registry package with the exception of the registry dashboard.

**Comment by martinpitt** [comment]
Oh, you are saying that I normally wouldn't see "Cluster" and "Registry" both together? I. e. when I only have the openshift package there actually is no way to change the currently logged in user as the registry itself doesn't have an UI for it, just the kubernetes package?

Thanks for the clarification!

**Comment by petervo** [comment]
Correct in that normally outside of dev mode, you wouldn't see "Cluster" and "Registry" together.

There is no openshift package. There is the kubernetes package that adapts itself to display openshift objects (such as imagestreams and projects etc..) if it is talking to an openshift server. And there is the registry package that meant to run as a standalone container. It only contains the image and project related UI bits from the kubernetes package and adds a custom dashboard that is focused on what you would expect out of a registry.

When either of these packages are used in a standalone container the user logs in using their openshift/kubernetes credentials directly. To change users, they would log out and back in as a different user, and so the wrench icon and it's dialog is disabled. It's only when used as part of a regular cockpit setup when the user logged into cockpit as real system user that ```~/.kube/config``` is read and used to authorize against openshift. In those cases the kubernetes package 

We could add the switch users dialog to the registry pretty easily. Although I'm a bit hesitant to do that as it would never show up in any actual delivered code/product.

We could add a monitor to ```~/.kube/config``` and reload the interface when the default user changes. That would allow user changes from the kubernetes package to be picked up in the registry package. But that could get pretty weird for users that typing ```oc login``` or ```kubectl``` commands makes cockpit disconnect and try (and potentially fail) to reconnect.

**Comment by martinpitt** [comment]
This was a misunderstanding of mine how these two products are shipped. And cockpit-kubernetes is on maintenance mode now, so we won't change stuff like this any more.
