### ISSUE TITLE
hostname is displayed as 'localhost'

### ISSUE THREAD

**Issue by abonas** [cockpit-project/cockpit#601]
When accessing cockpit UI from another server, the hostname inside the UI is shown as 'localhost' instead of the real host name.
SELinux: permissive

when doing 'hostname' in command line: dhcp-1-23.tlv.mycompany.com

hostnamectl output:
Static hostname: dhcp-1-23.tlv.mycompany.com
Icon name: computer-desktop
Chassis: desktop
 Machine ID: c3fd637915654afcb2ca87427c977555
Boot ID: a60c5153a35b4989a639b7a4b84cbf45
Operating System: Fedora 20 (Heisenbug)
CPE OS Name: cpe:/o:fedoraproject:fedora:20
Kernel: Linux 3.11.10-301.fc20.x86_64
Architecture: x86_64

Screenshot example:
![cockpitview](https://cloud.githubusercontent.com/assets/6277245/3051909/bd93a9c4-e192-11e3-9f10-b5b90ad894d3.png)

**Comment by stefwalter** [comment]
I believe this bug has been fixed with the new modular UI.
