### ISSUE TITLE
docker: spinner is off-center

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#6016]
When searching for containers, some kind of style-regression happened where the search spinner used to be centred, but is now off to the left side.
![screenshot from 2017-03-02 15-37-37](https://cloud.githubusercontent.com/assets/209895/23511734/778e525c-ff5e-11e6-9bdf-70f04d3ef2da.png)

**Comment by garrett** [comment]
I stumbled across this issue today, when poking around Cockpit to make sure another alignment bug is fixed (one that affects _all_ radios and checkboxes) that's actually an upstream-upstream issue (stemming from us using Cockpit using Bootstrap) that makes some wrong assumptions. (#9806)

Sending a PR in a short bit.
