### ISSUE TITLE
Request: overview of available options for developing third party plugins

### ISSUE THREAD

**Issue by ncoghlan** [cockpit-project/cockpit#6033]
Working on a custom plugin, I'm attempting to figure out the recommended approach to displaying data tables dynamically.

* looking at the existing plugins didn't help, as they all appear to have come up with their own way of doing it (up to and including a full React JS plugin)
* the PatternFly table view example seems like it *should* apply (since Cockpit uses PatternFly elsewhere), but it isn't clear whether it's failing because I've configured it incorrectly, or because Cockpit doesn't ship the necessary JQuery DataTables component

So it would be very helpful if there was a good on writing more complex plugins that covered:

* which JS & CSS files Cockpit promises to provide by default, and how to load them into your third party plugin (i.e. *not* using the Cockpit build process)
* explicit pointers to the example plugins in the 'playground' (alternatively, these could be moved out to a separate repo, so they serve as test cases for the ability to develop and maintain third party plugins)
* how it is recommended to manage other JS dependencies both during plugin development and when packaging it for deployment

**Comment by dperpeet** [comment]
Cockpit tries not to impose a specific way of doing things on plugins/packages.

In the past year, most new plugins have used React, others use mostly jquery. The list of packages that are installed by default is [here, in the bower.json file](https://github.com/cockpit-project/cockpit/blob/master/bower.json).

That said, the expression "full React JS plugin" is a bit misleading in my opinion, because there isn't much overhead necessary to use React (since the build system supports it already). You can also display parts of your page using React. You can check out the [React demo page](https://github.com/cockpit-project/cockpit/blob/master/pkg/playground/react-patterns.html) in our playground to see how a listing is used.

Thanks for your feedback on the documentation. You're right, we should link together what we have and augment the info to clarify what Cockpit can and wants to do right now.

**Comment by ncoghlan** [comment]
Ah, I hadn't even found the playground examples at all (just the VM management plugin, which is more worthy of the phrase "full React JS plugin"). 

I've retitled the issue to just request a more general overview of the available options. Stef's current blogposts are great for understanding how to get a plugin to interact with a backend CLI or Dbus service, but less so for dynamically updating the information displayed in the UI.

For my specific case, the stripped down React example looks very attractive, so I'll give that a go :)

**Comment by ncoghlan** [comment]
This actually gets more confusing, as even after the above fix, the simplified React example emits `Error: Module name "cockpit" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded`

And according to http://requirejs.org/docs/errors.html#notloaded, the way the demo is currently written simply can't work, as it is calling `require("name")` directly, without using either the `define()` helper, or a `require` callback.

**Comment by dperpeet** [comment]
This should work if you have the correct includes in the html: https://github.com/cockpit-project/cockpit/blob/master/pkg/playground/react-patterns.html#L9
`cockpit.js` brings in most of what you need and you may need to add an entry for webpack if you're writing a new package: https://github.com/cockpit-project/cockpit/blob/master/webpack.config.js

**Comment by ncoghlan** [comment]
I made some further updates to the title and description to clarify that the case I'm interested in is developing third party plugins distributed independently of Cockpit itself, rather than plugins that are integrated directly into the main Cockpit build and deployment process.

**Comment by ncoghlan** [comment]
Explaining what I'm now trying to do:

1. Symlink a plugin development directory into `~/.local/share/cockpit/` as per the instructions in the README
2. Download the following files from the `playground` directory:
    - `react-patterns.html` (rename this one)
    - `react-patterns.js`
    - `react-demo-*.jsx`
3. Add a manifest.json based on the `pinger` example, with the name updated to match the HTML file

This turns out not to work, as it runs into all sorts of problems with `require.js` complaining that modules haven't been loaded yet.

Now, it's entirely possible that I've missed a step in updating the manifest (does it need to list all the plugin files, not just the main HTML file?), or that refreshing the page isn't enough for `requires.js` to update properly so I need to log out entirely and then log back in, but that's the reason for the documentation request - I don't have a clear reference for how this is *supposed* to work for third party plugins, so it's hard to tell what's user error and what's an actual problem with using React in 3rd party plugins.

**Comment by martinpitt** [comment]
IMHO this is sufficiently addressed by the [Cockpit starter kit](https://github.com/cockpit-project/starter-kit) now. This is also linked from the ["Contributing" section of Cockpit's home page](https://cockpit-project.org/external/wiki/Contributing.html), together with a few related items.
