### ISSUE TITLE
Swapped IP in network panel

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#6041]
On irc someone reported a swapped IP address on  ppc64. Most likely a big endian issue.

This was with ```cockpit-networkmanager-130-1.fc25.noarch```

**Comment by petervo** [comment]
![a2di20u](https://cloud.githubusercontent.com/assets/10439156/23635404/7daf694a-0284-11e7-9b25-522bc3fa15c9.png)

**Comment by petervo** [comment]
@martinpitt was this fixed with the recent multi-arch work?

**Comment by martinpitt** [comment]
No, it wasn't. I'm still waiting on getting access to a big-endian machine to run tests on and reproducing this.

**Comment by martinpitt** [comment]
I have now learned how to get access to an s390x machine. Curiously *some* addresses are right, some aren't:

![s390x-ips](https://user-images.githubusercontent.com/200109/61545743-70e60200-aa48-11e9-9d43-f9d87b31ad3c.png)

**Comment by martinpitt** [comment]
The problem is that rendering the page does not block on this:
```js
    client.call("/org/freedesktop/NetworkManager",
                "org.freedesktop.DBus.Properties", "Get",
                ["org.freedesktop.NetworkManager", "State"], { flags: "" })
            .fail(complain)
            .done(function(reply, options) {
                if (options.flags) {
                    if (options.flags.indexOf(">") !== -1)
                        utils.set_byteorder("be");
                    else if (options.flags.indexOf("<") !== -1)
                        utils.set_byteorder("le");
                }
            });
```
So for the first few addresses rendered, `byteorder === undefined`. When doing some change on the page that forces it to re-render, like changing the IPv4 address settings, they start being correct.

**Comment by martinpitt** [comment]
```diff
--- a/pkg/networkmanager/utils.js
+++ b/pkg/networkmanager/utils.js
@@ -73,6 +73,7 @@ function bytes_from_nm32(num) {
             num = num >>> 8;
         }
     }
+    console.log("XXX bytes_from_nm32 byteorder", byteorder, "num", num, "bytes", JSON.stringify(bytes));
     return bytes;
 }
```

Outputs:
```
XXX bytes_from_nm32 byteorder undefined num 0 bytes [1,0,0,127] network.js:36883:11
XXX bytes_from_nm32 byteorder undefined num 0 bytes [61,69,16,10] network.js:36883:11
XXX bytes_from_nm32 byteorder undefined num 0 bytes [254,71,16,10] network.js:36883:11
XXX bytes_from_nm32 byteorder be num 0 bytes [10,16,69,61] network.js:36883:11
XXX bytes_from_nm32 byteorder be num 0 bytes [10,16,71,254] network.js:36883:11
XXX bytes_from_nm32 byteorder be num 0 bytes [10,11,5,19]
```

I can reproduce this locally, just that it's not visibly obvious as LE is the default. I'll fix this locally and then re-test it on a new beaker instance.
