### ISSUE TITLE
Image refresh for rhel-atomic

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#6043]
bot: Image refresh for rhel-atomic

**Comment by cockpituous** [comment]
Image creation for rhel-atomic in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-atomic-2017-03-07/

**Comment by cockpituous** [comment]
Image creation done.

**Comment by mvollmer** [comment]
Hmm, turning this issue into a pull request didn't work... maybe the bot can't do that for issues filed by someone else.
