### ISSUE TITLE
Allow kubernetes-cockpit container to work with service account

### ISSUE THREAD

**Issue by fabiand** [cockpit-project/cockpit#6048]
In the i.e. minikube demo it is not easily possible to change the authentication scheme, i.e. setting it to basic authentication as required by Cockpit.

It would be nice if the cockpit container could wok out of the box with service account credentials aka bearer tokens.

**Comment by fabiand** [comment]
There are several ways to achieve this.

One way might be to allow cockpit-kube-auth to connect to an `http` (not `https`) endpoint, then it could be configured (by overriding `KUBERNETES_SERVICE_HOST` and `_PORT`) to use a local `kubectl proxy` instance in a sidecar container.

**Comment by fabiand** [comment]
I.e. it should be possible to launch kubernetes-cockpit on https://github.com/kubernetes/minikube/ without modifications.

**Comment by petervo** [comment]
The reason we do not use the service credentials from inside the pod is that then there would be no authentication checks and all users would be getting exactly the same credentials. Allowing anyone who can access the service access to the api. Additionally, depending on the setup in some cases users would be restricted to the namespace the pod is running in, which would not be what people expect.

However, if others think this is useful, I wouldn't be totally opposed to adding a 
```USE_POD_CREDENTIALS_AND_OPEN_ACCESS_TO_ANYONE_AND_EVERYONE``` env var that if set to true we do this. 

@stefwalter any thoughts.

**Comment by bw2** [comment]
What is the recommended way to log in to cockpit on a vanilla minikube installation?

**Comment by fabiand** [comment]
This is still an issue.

Could the authentication be done similar to how it's done for the kubernetes dashboardß

**Comment by petervo** [comment]
> In other words: If Cockpit reliad on the pods credentials, the this is not better or worse than what a user can do with kubectl.

It is not really comparable. in order for someone to use kubectl they need to get the key and certificate somehow. If we expose it with cockpit then anyone who has connectivity to cockpit gets access. There are no credential checks. Again we can do this, you might has well just run your cluster without auth.

**Comment by martinpitt** [comment]
This is a request for enhancement, and in this case it's even a bit questionable.

Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
