### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#6049]
While designing the task killer and task switcher, I realized that there should be keyboard shortcuts in Cockpit to make getting around a bit easier.

- For the task killer, I'm currently suggesting `Alt`-`Esc` as a means to bring up the UI to kill off parts of Cockpit.
- With regards to the task switcher, it would be nice to have a way to press a hotkey to jump over to the task switching sidebar, navigate items with the keyboard (arrows), and select one of the items (enter and/or space).
- Also, for the task switcher, it would be ideal to have a keyboard shortcut to allow one to quickly switch hosts (all with just the keyboard).
- There should also be a way to focus the top header bar as well as open the menu in the top-right.

In addition, there should be a listing of keyboard shortcuts similar to recent versions of GNOME. (To see this in action, open the file manager "Nautilus" and select "Keyboard Shortcuts" from the app menu in the topbar, next to activities.) This should live in the menu in the top-right, either above or below "About Cockpit", and should also have a keyboard shortcut itself.

Also, I think it might make sense to have a standardized way to register keyboard shortcuts so that the shortcuts dialog would always be accurate.

_Relevant link: [Feature page for keyboard shortcuts](https://github.com/cockpit-project/cockpit/wiki/Feature:-Keyboard-shortcuts)_

**Comment by marusak** [comment]
What is `task killer` and `task switcher` exactly?
But we should be careful about having random shortcuts as nothing grinds my gears more on websites than unpredictable shortcuts - like when I think I am in a different window/or hit wrong key and suddenly I liked some status (that I don't even know I liked), navigate somewhere else, start replying and then I need to grab mouse and click Cancel...

So if we have some shortcut, they should be esc-reversible(click esc to undo, like close dialog...) and very much so visible that something happened. So no `ctrl+x` to kill something as that cannot be undone if you press ctrl+x by accident or shortcut that would do something in background or jumped to different page (especially if that would mean that the page would start loading bunch of data and you would need to navigate back to where you were before)
Shortcut for opening dialog/some side panel is of course fine. (when esc just closes them and returns focus where it was before).

**Comment by garrett** [comment]
You used to be able to hit alt or shift or something like this and click the user menu and select the task manager window. I don't know how to get to it now. Anyway, that's beside the point.

With keyboard shortcuts, we should also have a keyboard shortcut viewer and probably a way to toggle them on/off.

In Google Docs, for example, there are many shortcuts available, and they can be viewed with `ctrl`+`/`... additionally, they have a help page listing all the shortcuts. https://support.google.com/docs/answer/179738

I think we could have something similar:

- modal that lists the shortcuts
- a toggle for additional shortcuts (base set would always be on, secondary set is optional and would have a toggle)
- shortcut to show the dialog; probably `ctrl`+`/`
- a way to get to the dialog from the menu; select user menu in the top-right, click on "Keyboard shortcuts"

**Comment by garrett** [comment]
## Nautilus

![keyboard-screenshots-menu](https://user-images.githubusercontent.com/10246/109810289-a80f2400-7c29-11eb-8e42-a9bb799c47d4.png)

![Screenshot from 2021-03-03 14-03-25](https://user-images.githubusercontent.com/10246/109810293-a8a7ba80-7c29-11eb-88de-aedba3f569c2.png)

## Google Docs

![Screenshot from 2021-03-03 14-03-54](https://user-images.githubusercontent.com/10246/109810291-a8a7ba80-7c29-11eb-8f50-ae2360759efd.png)

**Comment by marusak** [comment]
> You used to be able to hit alt or shift or something like this and click the user menu and select the task manager window. I don't know how to get to it now. Anyway, that's beside the point.

That exists, it is `alt + <click on icon right top corner>` and then `Active pages`.
![alticon](https://user-images.githubusercontent.com/12330670/109810728-2ff52e00-7c2a-11eb-8791-1502dee94fe9.png)

But this is very much developers tool I would say.

You mentioned how to menage shortcuts, but what shortcuts should we have?

From [wiki](https://github.com/cockpit-project/cockpit/wiki/Feature:-Keyboard-shortcuts) I see:

1. Navigation
2. Host selector
3. Header bar
4. Top-left menu
5. Dashboard
6. Sign out

1., 2. and 3. are mostly about jumping to the top of the shell where we also have skiplinks so it should be reasonably easy to move between content/navigation/host selector.

4. and 5. don't exist anymore

6. Is one of those shortcuts that I would be against. User does not need to log out that often that it would become burden to navigate and click twice to log out. Also it is one of those actions where you can do more harm than it is useful when you log out by accident.

So does this boil down to `Jump to the start of the document`? If so, maybe there is some better approach of doing this (like skiplink of sort).

**Comment by garrett** [comment]
> But this is very much developers tool I would say.

It is! That's why I said to forget it. But it prompted me to think about keyboard shortcuts, and here we are.

Plus, it doesn't work here, as I have alt-click as a window modifier. It's supposed to have alt or shift as modifiers, IIRC. But it seems that it only accepts alt at the moment.

> So does this boil down to Jump to the start of the document? If so, maybe there is some better approach of doing this (like skiplink of sort).

No! These were just a start of a brainstorm. I wanted others to contribute ideas for keyboard shortcuts, but it never took off.

The general idea is that one should be able to easily jump around Cockpit using just a keyboard. And that it should be documented, as I mentioned above. That's the actual goal.

It would be useful not just for a11y reasons, but also for "power users" (which most admins, our target audience, are).

**Comment by marusak** [comment]
Here is fine example why I hate all browser apps that have keyboard shortcuts: https://github.com/cockpit-project/bots/issues/2042
I was on github issue and wanted to check whats the weather going to be like in Praque, so I wanted to type into url bar `pocasie praha`. But I did not focus the url bar and instead typed this string directly on the github page. Apparently `po` does nothing, `c` goes to the new issue page. `asie` was lost as the page was loading. Then the title was focused by default, that took the `praha` input and the enter I hit to submit my query created the issue.

**Comment by martinpitt** [comment]
This is still "valid" in the sense of "nothing changed", but honestly, if you want to drive your server with the keyboard, use ssh.. The iframe dialog/killer is specifically a developer tool that I would *not* want a keyboard shortcut for. From the nautilus shortcuts, nothing actually applies there to cockpit other than "new/close window", and browsers already have that. From the google docs shortcuts, nothing applies at all.

I have a hard time to see what you could sensibly do in Cockpit with keyboard shortcuts that you can't already do with Tab/space, or the keyboard extensions like vimium/tridactyl. I'm closing this now to clean up our issues tracker. If you disagree, please reopen. Thanks!
