### ISSUE TITLE
tabbing order is not optimal: remove tabindex to use built-in browser order

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#6057]
Similar to what we did with the log in screen several weeks ago, we should rework `tabindex` across all of Cockpit, to help improve accessibility.

`tabindex` is generally a misfeature of HTML and gets in the way of natural order of tabbing through elements. (Generally one would want to remove all `tabindex` references, unless it is necessary to hardcode the tabbing order of elements which may be activated.)

See http://webaim.org/techniques/keyboard/tabindex for proper usage of `tabindex`.

---

Note: There are 105 remaining uses of `tabindex` within the Cockpit repository. However, simply removing these might break things (each would need to be inspected in context).

**Comment by garrett** [comment]
Here's a list of files that include `tabindex`:

```
23	pkg/networkmanager/index.html
12	pkg/systemd/index.html
9	pkg/dashboard/index.html
8	pkg/storaged/index.html
6	pkg/docker/index.html
6	pkg/playground/plot.html
6	pkg/shell/index.html
5	pkg/users/index.html
4	pkg/kubernetes/views/registry-dashboard-page.html
4	pkg/shell/stub.html
3	pkg/shell/simple.html
3	pkg/systemd/services.html
2	pkg/kubernetes/views/project-modify.html
2	pkg/lib/machine-change-auth.html
1	pkg/kubernetes/scripts/tags.js
1	pkg/kubernetes/scripts/tags.min.js
1	pkg/kubernetes/views/add-member-role-dialog.html
1	pkg/lib/cockpit-components-dialog.jsx
1	pkg/lib/machine-color-picker.html
1	pkg/playground/jquery-patterns.html
1	pkg/realmd/operation.html
1	pkg/shell/indexes.js
1	pkg/sosreport/index.html
1	pkg/tuned/change-profile.jsx
1	pkg/tuned/dialog-view.js
1	pkg/tuned/link.html
```

**Comment by martinpitt** [comment]
@garrett: Yesterday you mentioned that [tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) values 0 and -1 were (at least in principle) kosher, to disable tabbing to elements which are meant to be non-interactive. We don't have any other values any more.

Do you want to keep this open still and review this, or was this meant to get  rid of positive (i. e. actually ordering) tabindexes?

**Comment by marusak** [comment]
```
$ git grep tabindex | wc -l
233
```
By quick look most of them are in our custom dropdowns, which we should replace by native selects anyway.

**Comment by KKoukiou** [comment]
```
$ git grep tabIn
pkg/lib/cockpit-components-logs-panel.jsx:            <div className="cockpit-logline" role="row" tabIndex="0" key={entry.__CURSOR}
pkg/metrics/metrics.jsx:                        tabIndex="0"
pkg/metrics/metrics.jsx:                                    tabIndex="0"
pkg/storaged/side-panel.jsx:                <tr role="button" tabIndex="0"
pkg/storaged/side-panel.jsx:                role="link" tabIndex="0"
pkg/storaged/storage-controls.jsx:    <li><a role="link" tabIndex="0" onKeyPress={checked(onClick)} onClick={checked(onClick)}>{children}</a></li>
pkg/systemd/overview-cards/insights.jsx:
```

Seems like 30min works to check the last occurances.

**Comment by KKoukiou** [comment]
PR #15326 handles metrics ans overview page.

Storage page is handled by https://github.com/cockpit-project/cockpit/pull/15261

In logs the tabIndex is correctly used.
