### ISSUE TITLE
Killing a agent session results in unpredictable errors.

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#606]
And it is also different depending on whether it's a local session started by cockpit-session or a remote session by sshd.

Killing a local session might even result in the client going to the "closed" state with error == null.

To reproduce, run ./test/check-multi-machine and observe the exact error messages.

**Comment by stefwalter** [comment]
Is this solved now?

**Comment by mvollmer** [comment]
> Is this solved now?

I think so.  In any case, we need to start over with concrete cases again.
