### ISSUE TITLE
No obvious way to get back to System page from the CPU and Memory pages

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#6060]
Proxied for Ben, who sent a mail from the airport:
"When a user clicks the memory or cpu links under the system page for the detailed performance graphs, there doesn't appear to be any type of "back" button to return to the regular system page."

**Comment by andreasn** [comment]
We could do a breadcrumb here, like we do on Storage, Logs and Networking etc.

**Comment by martinpitt** [comment]
We have breadcrumbs on the hwinfo page now.
