### ISSUE TITLE
Migrate /var/lib/cockpit/known_hosts to /etc/ssh/ssh_known_hosts

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#6068]
After we'll land PR #6025 to read/write `/etc/ssh/ssh_known_hosts` it would be nice to migrate `/var/lib/cockpit/known_hosts` to that canonical file as well, so that host fingerprints accepted in Cockpit also apply to the `ssh` command line client.

Unlike for `machines.json` there is no hurry for landing the migration of the existing `/var/lib/cockpit/known_hosts` in lockstep, as we always have to assume and get along with an already existing file in `/etc`, and also can't assume that we are able to write it (as we don't "own" it). But I was wondering where and how to actually do that - we can't do  that in cockpit-ssh itself as that doesn't have root privileges. As far as I can tell there are these options:

 1. Through a root command  from JavaScript
    * I would add this to pkg/lib/machines.js `add_key()`, as there we change `ssh_known_hosts` anyway. This must only happen if `ws` reports the new `etc-knownhosts` capability that PR #6025 introduces, although this is likely to go away -- in that case we need some equivalent check. We must not do the transition if we are running against an old `cockpit/ws` container whose `cockpit-ssh` only looks at /var.
    * This has the advantage that we have root permissions and don't need to rely on any new bridge API. But it is rather expensive (several roundtrips through JS and the bridge) and requires a new `ws`/`ssh` capability.
 2. In the (privileged) bridge, doing this migration along with `machines.json`.
    * This would be magnitudes more efficient and also doesn't require any API changes. But it appears to me that in the bridge we have no way of checking the `cockpit-ssh/ws` capabilities, so we don't know when it's safe to actually do that migration.
 3. Don't bother and look at the old path forever.
    * Checking for the old file in `cockpit-ssh` is rather cheap, so it doesn't hurt to keep this around for a while.

@petervo, do you have some guidance/opinion about this?

**Comment by stefwalter** [comment]
@martinpitt Is this possible now?

**Comment by petervo** [comment]
Sorry for not replying earlier. IIRC, we discussed this on IRC but to recap i think that since we have to keep reading from /var/lib/cockpit for compatibility reasons, we probably don't need to migrate as long as we are only writing to the new location at /etc/ssh/ then we should be ok.

If you agree then we can close this.

**Comment by martinpitt** [comment]
Yes, we only write to `/etc/ssh/`. So, option 3 it is :-)
