### ISSUE TITLE
Debian cockpit packages pulls in x11

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#6080]
Would be nice to not have a x11 dependency in cockpit, I believe it's xdg-utils is what pulls it in.

**Comment by martinpitt** [comment]
`xdg-utils` recommends `x11-common` (just a few files, harmless), `x11-utils` (not too big, but unnecessary for our purposes), and `x11-xserver-utils` (not necessary at all for us indeed). No server bits, but some unnecessary client programs. But it also pulls in a couple of fonts, cpp, libwww-perl and so on. One could install with `--no-install-recommends` to avoid all that, but this is a bit ugly indeed.

We need it for src/ws/cockpit.desktop.in only (`Exec=xdg-open http://localhost:9090`), and we don't declare the dependency in `cockpit.spec` at all. So we could lower `Depends: xdg-utils` to `Suggests:`, assuming that on servers you don't want it, and on desktops it's generally already installed.
