### ISSUE TITLE
RFE: use a library to provide HTTP and WebSocket functionality

### ISSUE THREAD

**Issue by dfj** [cockpit-project/cockpit#613]
Cockpit currently implements HTTP and WebSocket functionality itself, without relying on any external libraries. In cockpit's case, this may be less work than relying on an external library, but it means that your implementation needs to be free of all the potential security issues that are likely to have been resolved in a mature external library. There are a wide range of potential issues you could be exposing. Many security issues have already been fixed (thanks!) and further auditing is ongoing. That said, the best long-term solution may be to use an external library to provide HTTP and WebSocket functionality.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

We are sorry, but we won't be able to address this in any time soon.
If you are interested in helping us with the implementation, please comment here.
