### ISSUE TITLE
Registry: Maintainer label not used for Author

### ISSUE THREAD

**Issue by lcarva** [cockpit-project/cockpit#6133]
Dockerfile reference specifies that `MAINTAINER` instruction is deprecated and instead the `LABEL` `maintainer` should be used. However, imagestream page only populates Author information when `MAINTAINER` instruction is used.

https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

**Comment by stefwalter** [comment]
Good point. Here's where that happens:

https://github.com/openshift/registry-image-widgets/blob/master/views/image-body.html

Are you interested in making a change to that code? If so I'd be happy to review a pull request. If not, then I'll leave this note here for someone to fix and find the spot in the code to change.

**Comment by brandongray** [comment]
Is this a bigger change than just updating the Dockerfiles that contain `MAINTAINER` vs. `LABEL maintainer`?

**Comment by martinpitt** [comment]
This depends on updating the external registry-image-widgets component, so this isn't a "good-first-issue".

Our kubernetes UI is on maintenance mode, so this most likely won't happen any more (unless someone external steps up and wants to do it). See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/

**Comment by marusak** [comment]
I don't think anyone will implement this. I am closing this especially as Kubernetes is not maintained in master anymore. When it needs to be tracked, then Bugzilla would be a right place for it.
