### ISSUE TITLE
"Add Server" does not allow you to add a port forwarded server

### ISSUE THREAD

**Issue by taw00** [cockpit-project/cockpit#6146]
So, I port-forward some VPS systems... example...
ssh -L 9092:127.0.0.1:9090 username@remote_system -N"

I can browse to 127.0.0.1:9092 and view the system's cockpit just fine. But if I open up my own local cockpit at 127.0.0.1:9090 and then try to "Add Server" using that 127.0.0.1:9092 combo, it just doesn't work.

Why do I do this? Because my systems sitting out in the cloud have one less attack vector. That port is not accessible to the outside world. And SSH port forwarding works very well.

Thanks! -todd warner

**Comment by petervo** [comment]
Add server connects via ssh to the secondary server, it does not require port 9090 to be open on the remove server. It seems like you are forwarding the cockpit port. Having you tried adding your cloud server directly?

**Comment by taw00** [comment]
You can't add the cloud server directly. The port is not externally available. That's the point of the port-forwarding through SSH.

**Comment by petervo** [comment]
But it has ssh running correct? Cockpit uses ssh to talk to it's secondary servers. Not port 9090. So if ssh is available then you should be able to add the server directly. Otherwise if you need port forwarding you need to forward so you can access the port used by the remote sshd port (ei: 22) not 9090.

**Comment by taw00** [comment]
I run SSH locally. See original description. With that configuration, I can...

* browse to both https://127.0.0.1:9090 and https://127.0.0.1:9092 and interface with cockpit. The former is my localhost the latter is my remote machine.
* https://<remote_ip_address>:9090 is not available because the firewall prevents it.
* Within 127.0.0.1:9090 one would _think_ that you could add server 127.0.0.1:9092 and it would just do what you expect. It does not.

The way SSH port forwarding works is that you create a pipe and link the local port (9092 in this case) with a remote port (9090 in this case). I could use that same ssh piping to connect any two other ports as well. Cockpit leveraging SSH to talk to its own services locally and remotely is irrelevant because none of this changes the behavior of SSH.

**Comment by petervo** [comment]
@taw00, I understand your configuration and what you are trying to do but cockpit does not communicate with secondary servers that are added to the dashboard via http requests and websockets. Even if you had port 9090 open on your remove server, you could not add it as a secondary server on the cockpit dashboard. That connection will always happen via ssh, all http and websocket requests for that secondary server go through the same connection as the requests to your primary server. Maybe this diagram will help to explain, https://github.com/cockpit-project/cockpit/blob/master/doc/cockpit-transport.png.

**Comment by Gundersanne** [comment]
Closing this because answered and inactive. The way to do this is to indeed add the remote server's ssh url on the dashboard.
