### ISSUE TITLE
TestCases and wasSuccessful

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#6165]
We use ```currentResult.wasSuccessful()``` in teardown to copy journals and screenshot if needed. But that reports on test run, not the individual test that was selected. Meaning when a TestCase class has those actions will be taken for every test after the first failure even when those tests succeeded.

**Comment by larskarlitski** [comment]
The only mention of `wasSuccessful` is in `run()`, not in `tearDown()`. @martinpitt am I right?

**Comment by martinpitt** [comment]
It's still effectively tearDown in `runOne`. However, I don't understand the original bug report, and this by and large works as intended, so I agree to closing this.
