### ISSUE TITLE
Auth Pipe Closed: timeout

### ISSUE THREAD

**Issue by FloThinksPi** [cockpit-project/cockpit#6201]
When trying to add a Host to Cockpit i get following error.

![error](https://cloud.githubusercontent.com/assets/5863788/24295429/f6dea992-109a-11e7-8ba7-94e8eb3bd37f.png)

However logging in via SSH from the Terminal of the Main machine works without issues. Also the ssh port of the Target machine is 22 so there should be no issues. 

\var\log\secure on the target machine
> Mar 24 14:37:42 storageserver sshd[11779]: Accepted password for root from 10.110.109.31 port 49986 ssh2
> Mar 24 14:37:42 storageserver systemd: pam_unix(systemd-user:session): session opened for user root by (uid=0)
> Mar 24 14:37:42 storageserver sshd[11779]: pam_unix(sshd:session): session opened for user root by (uid=0)
> Mar 24 14:38:12 storageserver sshd[11779]: pam_unix(sshd:session): session closed for user root

The Host is running CentOS7 with Cockpit 135 form https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/ , the Target which i wanted to add runs Fedora 25 also with Cockpit 135. At this point i reinstalled all Cockpit Packages on both machines. But i dont find any issue in the installation. Is this a software issue ?

Regards
Flo

**Comment by petervo** [comment]
I wasn't able to reproduce. I tried the same centos7 - fedora-25 combo. A couple things to check

1) Did you check the "Reuse my password for privileged tasks" when logging in?
2) Do you have any custom pam modules in ``` /etc/pam.d/sshd``` on the target machine.
3) Are there any selinux failures in the logs

Just out of curiosity, to you get the same error trying the other way. Adding the centos machine to the dashboard on fedora?

**Comment by FloThinksPi** [comment]
Thank you for your response, so
1. I tried both, when not using the passwort for Privileged tasks, i get prompted for username and password and then the same error occurs.
2. Following Modules are in the file:
> #%PAM-1.0
> auth	   required	pam_sepermit.so
> auth       substack     password-auth
> auth       include      postlogin
> # Used with polkit to reauthorize users in remote sessions
> -auth      optional     pam_reauthorize.so prepare
> account    required     pam_nologin.so
> account    include      password-auth
> password   include      password-auth
> # pam_selinux.so close should be the first session rule
> session    required     pam_selinux.so close
> session    required     pam_loginuid.so
> # pam_selinux.so open should only be followed by sessions to be executed in the user context
> session    required     pam_selinux.so open env_params
> session    required     pam_namespace.so
> session    optional     pam_keyinit.so force revoke
> session    include      password-auth
> session    include      postlogin
> # Used with polkit to reauthorize users in remote sessions
> -session   optional     pam_reauthorize.so prepare
I did not change anything here by myself.
3. There are no selinux errors in the logs on both machines. selinux is enforcing.
And the same error occurs when trying to add the machines the other way around :/ strange.

**Comment by petervo** [comment]
That all looks pretty normal. Are you seeing the a timeout message in the dialog?

Any chance you'd be willing to turn debug logging on (https://github.com/cockpit-project/cockpit/blob/master/HACKING.md#debug-logging-of-cockpit-processes) and send us fuller logs:

**Comment by FloThinksPi** [comment]
Yes there is a timeout message in the dialog. I turned on debugging like in the instruction. Here is the output of "journalctl -f" https://gist.github.com/FloThinksPi/d52686c727d5af6f194968bfad55c3cb
I am now going to reinstall the physical server with CentOS too. I need it now working :wink:

**Comment by FloThinksPi** [comment]
So did a fresh install of the target which i wanted to add with CentOS both having the Cockpit Versions from the Copr and it works all flawless now, letting you decide if you want to keep this issue open and do further investigations or just close it

**Comment by larskarlitski** [comment]
I'll close it now. It's been a while (and we've reworked cockpit-ssh) and there haven't been similar reports. Thanks!
