### ISSUE TITLE
Add HEAD support to cockpit-ws

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#6202]
cockpit-ws should reply correctly to a HEAD request. The registry is being pinged that way.

**Comment by stefwalter** [comment]
```
 INFO: cockpit-ws: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
 MESSAGE: cockpit-protocol: received unsupported HTTP method
```

**Comment by sferich888** [comment]
This was found by running the following: 

```
curl -Ik https://registry-console-default.router.default.svc.cluster.local
HTTP/1.1 405 Method Not Allowed
Content-Type: text/html; charset=utf8
Transfer-Encoding: chunked
```

```
oc logs pod/registry-console-#-HASH -n default
INFO: cockpit-ws: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
MESSAGE: cockpit-protocol: received unsupported HTTP method
```

**Comment by stefwalter** [comment]
@martinpitt Is this something you'd be interested in fixing? It's relevant for long term freeze too. If not, let me know.

**Comment by martinpitt** [comment]
Assigning to me for now, I'm interested to learn some more details of ws and this is a good opportunity. Trivial to test with `curl -Ik https://localhost:9090`, so I'll look at this or tell you if it's too overwhelming for me to get done in time.

**Comment by martinpitt** [comment]
@stefwalter, @petervo: How fancy do we want to get with this? For the "ping" use case it's by and large enough to send back a constant `200 OK` without much further processing. As long as the sender isn't authenticated and has a running session (i. e. for use cases like this), the current ws redirects any path to the login page, i. e. something like http://localhost:9090/BogusPath will always result in `200 OK`. So unauthenticated callers cannot use this to determine if the path is valid.

So I wonder if `process_request()` should handle `HEAD` locally with a constant `200 OK` or whether the `handle-stream` signal should grow a new `gboolean head_only` and adjust all implementations for that accordingly. My gut feeling is the former and do the latter only if someone complains, but I'd appreciate your opinion on this.

**Comment by petervo** [comment]
IMO unauthenticated should return 401. If an etag is there we should return 304. Otherwise 200 ok is good.

**Comment by petervo** [comment]
Just to be clear for the above I was talking about /cockpit/xxx paths. Not the ones where the login page is served.

**Comment by martinpitt** [comment]
I have an [initial working version](https://paste.fedoraproject.org/paste/3df~sNDdmZEWkoahzLaajV5M1UNdIGYhyRLivL9gydE=/). I tested it on the login page (http://localhost:9090), a static page (http://localhost:9090/cockpit/static/login.html), and a (non-existing) channel page (http://localhost:9090/cockpit+123/channel/foo), and in all cases HEAD vs. GET seems to work fine.

I still need to write tests, and either clarify or remove the `g_assert` marked with XXX (which is to ensure that I didn't miss any signal handler with the new signature and the gboolean just gets assigned to random memory), but I'd appreciate some initial feedback. In particular:

 - Is the general approach of plumbing that new `head_only` boolean through the signal handler okay?
 - `cockpit_web_response_ignore_content()` vs. adding this as an argument to `cockpit_web_response_new()` and changing all 40 places where it's called?
 - passing `head_only` as a bool vs. the method as a string (harder to pass around and keep track of, but more flexible in case we ever need POST, PUT, DELETE, etc.)

**Comment by petervo** [comment]
Probably easier to review in a WIP PR. 

Personally I would prefer to store method as a member on CockpitRequest rather than a boolean. And use it as a const everywhere else. But I don't think we will ever do other methods. Last time this came up we decided against it. So if it's significantly easier to do the bool i'm ok with it.
