### ISSUE TITLE
Virtual machines external API

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [cockpit-project/cockpit#6219]
Is there way to use cockpit-machines JS API in other plugin? 
For example, in my home page, which is custom cockpit plugin, I want to show list of VM's, is there way to access this [function](https://github.com/cockpit-project/cockpit/blob/master/pkg/machines/actions.es6#L35) from my plugin?
@mareklibra could you help on this?

**Comment by stefwalter** [comment]
I'll leave answering this to @mareklibra .. but @igorSmirnovPlexi it's worth noting that:

The machines code is in constant flux right now. I'm not sure it's an "API" yet. How would you handle regular changes to the functions in ```actions.es6```?

**Comment by igorSmirnovPlexi** [comment]
Ok, the same question about docker plugin, which is stable. Might I use existed docker API to get list of containers or I need to find my own way how to list them?

**Comment by mareklibra** [comment]
@igorSmirnovPlexi , the external provider API in cockpit:machines is intended to provide data for cockpit:machines React components by dispatching Redux actions. 

Cockpit:machines are meant to be the frontend, not a middleware for other systems.
I would suggest to integrate on presentation layer by embedding the cockpit:machines plugin or connect to Libvirt or other provider other way.

**Comment by igorSmirnovPlexi** [comment]
Ok, thank you @mareklibra, I got it.
