### ISSUE TITLE
RFE: Add VPN support to the Networking

### ISSUE THREAD

**Issue by sgallagher** [cockpit-project/cockpit#6220]
It would be convenient to be able to activate or deactivate a VPN connection on the Networking tab the same way it can be done via the GNOME NetworkManager control panel.

Ideally, it would also support creating, configuring and importing VPN configurations.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

We are sorry, but we won't be able to address this in any time soon.
If you are interested in helping us with the implementation, please comment here.
