### ISSUE TITLE
Allow docker-ce as a dependency of cockpit-docker

### ISSUE THREAD

**Issue by agross** [cockpit-project/cockpit#6225]
Hi!

Since installing `docker-ce`, `cockpit-docker` is not available anymore and I can't figure out a way to install it:

```sh
[root@foo]# dnf install cockpit-docker
Last metadata expiration check: 0:24:01 ago on Mon Mar 27 23:30:00 2017 CEST.
Error: package cockpit-docker-120-1.fc25.x86_64 requires docker >= 1.3.0, but none of the providers can be installed
  - package docker-ce-17.03.0.ce-1.fc25.x86_64 conflicts with docker-engine provided by docker-2:1.12.2-5.git8f1975c.fc25.x86_64
  - package docker-ce-17.03.0.ce-1.fc25.x86_64 conflicts with docker-engine provided by docker-2:1.12.6-6.gitae7d637.fc25.x86_64
  - problem with installed package docker-ce-17.03.0.ce-1.fc25.x86_64
  - package docker-ce-17.03.0.ce-1.fc25.x86_64 conflicts with docker provided by docker-2:1.12.2-5.git8f1975c.fc25.x86_64
  - package docker-ce-17.03.0.ce-1.fc25.x86_64 conflicts with docker provided by docker-2:1.12.6-6.gitae7d637.fc25.x86_64
  - conflicting requests
  - package cockpit-docker-135-1.fc25.x86_64 requires docker >= 1.3.0, but none of the providers can be installed
(try to add '--allowerasing' to command line to replace conflicting packages)
```

It would be great if `docker-ce` would be considered as a valid dependency of `cockpit-docker`.

**Comment by agross** [comment]
```sh
rpm -Uvh --nodeps $(dnf download --url cockpit-docker | tail -n 1)
```

worked as a workaround.

**Comment by petervo** [comment]
This is related to #5943, closing this. If you have further info or feedback can you comment there?

**Comment by bjackson** [comment]
What would be the workaround for Ubuntu or another apt-based system?

**Comment by martinpitt** [comment]
@bjackson: Something like `apt-get -o Dpkg::Options::="--force-conflicts" install docker..`, but *only ever* do this on emphemeral throw-away systems, never a permanent/production one. You will break upgradeability with this, or the next `apt-get -f install` will just remove one of the conflicting packages again. But is that even a problem on Debian? Conversation on #5943 suggests its not, but if it is please follow up there with what you want to do precisely.
