### ISSUE TITLE
entrys in tuned profiles are very tall

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#6276]
I was looking at this one again, and I wonder if the rows are a bit tall.
Right now it only fits 3 entrys at a time, and on something like RHEL Atomic Host, it becomes a bit tricky to navigate the list, since it's so long.
I think it would be good to tight this up a bit.

![screenshot from 2017-04-04 14-40-32](https://cloud.githubusercontent.com/assets/209895/24657065/416aa09e-1945-11e7-9267-e1641a782aa9.png)

**Comment by andreasn** [comment]
I think it's because p in Patternfly has margin set to 0 0 10px.
Special-casing the last one to 0 instead would fix it.
![screenshot from 2017-04-04 14-48-32](https://cloud.githubusercontent.com/assets/209895/24657252/cecf7eaa-1945-11e7-80e9-4b30c7e583cb.png)

**Comment by larskarlitski** [comment]
Is this still valid? I think this is a good starter issue, but needs an updated design first.

**Comment by andreasn** [comment]
Optimization, but nothing that is critical really. Will file again if it feels like it's still a big problem in the future.
