### ISSUE TITLE
ostree: repo edit button is cut off

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#6277]
![screenshot from 2017-04-04 14-50-10](https://cloud.githubusercontent.com/assets/209895/24657335/2066013a-1946-11e7-8107-9dedf2b5752d.png)

@petervo any idea what's going on here? This system is not subscribed, so it might be an unexpected case.

**Comment by petervo** [comment]
I can't reproduce. Does your remote not have a name? Are there no remotes?

What's the output of ```ostree remote list```

**Comment by andreasn** [comment]
The output is empty.
I also get this:
![screenshot from 2017-04-05 11-46-17](https://cloud.githubusercontent.com/assets/209895/24699806/86e53836-19f5-11e7-9444-6ddf07ee3d8f.png)

**Comment by andreasn** [comment]
So I think this is the case where something has gone very wrong

**Comment by petervo** [comment]
Yep, somehow all your remotes are deleted. probably by rhsmcertd. I guess we should fix the layout for that case.

Are you still able to add new remotes?

**Comment by andreasn** [comment]
> Are you still able to add new remotes?

Yes.

**Comment by andreasn** [comment]
Got the system subscribed now, and now it looks like it should.
