### ISSUE TITLE
sidebar border width is very thick

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#6286]
![screenshot from 2017-04-05 16-06-45](https://cloud.githubusercontent.com/assets/209895/24709368/f4240b92-1a19-11e7-9af4-1702b0dc3849.png)

@garrett I think we discussed to make this 3px rather than 7px, but I didn't file an issue about it.

**Comment by garrett** [comment]
Ah, yeah; we did discuss it.

I'll poke around in the codebase to see if I can send a PR for this.

**Comment by garrett** [comment]
Note: This patch also should change the line thickness in the dropdown to switch hosts as well as in the dashboard machine listing. All should be consistently 3 pixels wide now (instead of 7 pixels).

**Comment by garrett** [comment]
@andreasn: Can you test the change in the PR and post a screenshot on the PR #6289 please?

**Comment by andreasn** [comment]
This was fixed.
