### ISSUE TITLE
add cockpit-machines to RHEL 7.3 repo

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [cockpit-project/cockpit#6290]
cockpit-machines is available in ubuntu and centos repositories, but not in RHEL. Could you add it?

**Comment by petervo** [comment]
The plan is to do that at some point, but i hasn't yet reached the level of stability required for rhel. You can always get it from our copr in the mean time.

https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/
