### ISSUE TITLE
Failed to add machine: Unexpected type 'int' in argument

### ISSUE THREAD

**Issue by cabusar** [cockpit-project/cockpit#6291]
Hello,

First of all, many thanks for your work.

I have a problem and no clue how to deal with.

Let's assume that i have my Ubuntu laptop (Ubuntu 16.04 / Cockpit 137-0 via ppa) and a server (Debian Jessie / cockpit 136-0 via repository).

I want to connect my Laptop to the server (like if i have a vsphere client connecting an esxi). The main goal is to have a basic management tool on my laptop for my server without exposing cockpit on the server.

I install cockpit 137-0 on my laptop, then on the server (136-0) and i try to add the server into the dashboard on the laptop.

My ssh port isn't 22 but a port above 1024. (as example i will use 1337)

First step : 
```
Adresse : my.server.com:1337 
Seem to be ok.
```

Second step : 
```
username : USER
password : PASSWORD
```

Result : 
`Failed to add machine: Unexpected type 'int' in argument.`

I try to look in /etc/cockpit.conf but the file is not present.
I don't really know were to look for clues.

I will continue to troubleshoot.

Any help will be appreciated.

Thanks in advance. :)

**Comment by petervo** [comment]
Where do you see that error? In the dialog, in the browser console, or in the journal? Any logs you can give us from the journal would be helpful in tracking this down.

Here's how to enable debug logging https://github.com/cockpit-project/cockpit/blob/master/HACKING.md#debug-logging-of-cockpit-processes

**Comment by cabusar** [comment]
I see that in the dialog box.

Here is a extract from journalctl -f, it correspond to the exact moment when i click on "log in" in the dialogue box to the moment i get the error.

```
avril 06 15:58:48 laptop cockpit-ws[4681]: 1: added channel 1:2!42 to socket
avril 06 15:58:48 laptop cockpit-bridge[4706]: /bin/sh: end of data, closing pipe
avril 06 15:58:48 laptop cockpit-ws[4681]: 1: remove channel 1:2!42 for socket
avril 06 15:58:52 laptop cockpit-bridge[4706]: org.freedesktop.timedate1: invoking org.freedesktop.DBus.Properties Get at /org/freedesktop/timedate1
avril 06 15:58:52 laptop cockpit-bridge[4706]: org.freedesktop.timedate1: reply for Get
avril 06 15:58:53 laptop cockpit-ws[4681]: 1: added channel 1:2!43 to socket
avril 06 15:58:53 laptop cockpit-bridge[4706]: /bin/sh: end of data, closing pipe
avril 06 15:58:53 laptop cockpit-ws[4681]: 1: remove channel 1:2!43 for socket
avril 06 15:58:57 laptop cockpit-bridge[4706]: org.freedesktop.timedate1: invoking org.freedesktop.DBus.Properties Get at /org/freedesktop/timedate1
avril 06 15:58:57 laptop cockpit-bridge[4706]: org.freedesktop.timedate1: reply for Get
avril 06 15:58:58 laptop cockpit-ws[4681]: 1: added channel 1:2!44 to socket
avril 06 15:58:58 laptop cockpit-bridge[4706]: /bin/sh: end of data, closing pipe
avril 06 15:58:58 laptop cockpit-ws[4681]: 1: remove channel 1:2!44 for socket
avril 06 15:58:59 laptop cockpit-ws[4681]: 1: added channel 1:2!45 to socket
avril 06 15:58:59 laptop cockpit-bridge[4706]: /usr/lib/cockpit/cockpit-ssh: handling channel "1:2!45" on peer
avril 06 15:58:59 laptop cockpit-ws[4681]: 1: remove channel 1:2!45 for socket
avril 06 15:58:59 laptop cockpit-ws[4681]: 1: added channel 1:2!46 to socket
avril 06 15:58:59 laptop cockpit-bridge[4706]: /usr/bin/pkexec: handling channel "1:2!46" on peer
avril 06 15:59:02 laptop cockpit-bridge[4706]: org.freedesktop.timedate1: invoking org.freedesktop.DBus.Properties Get at /org/freedesktop/timedate1
avril 06 15:59:02 laptop cockpit-bridge[4706]: org.freedesktop.timedate1: reply for Get

```

And here is a auth.log extract from the server : 

```
Apr  6 15:58:22 SERVER sshd[31754]: Accepted password for XXUSERXX from X.X.X.X port 60404 ssh2
Apr  6 15:58:22 SERVER sshd[31754]: pam_unix(sshd:session): session opened for user XXUSERXX by (uid=0)
Apr  6 15:58:22 SERVER systemd-logind[32718]: New session 330153 of user XXUSERXX.
Apr  6 15:58:22 SERVER systemd: pam_unix(systemd-user:session): session opened for user XXUSERXX by (uid=0)
Apr  6 15:58:22 SERVER polkitd(authority=local): Registered Authentication Agent for unix-session:330153 (system bus name :1.45 [cockpit-bridge], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Apr  6 15:59:21 SERVER sshd[31754]: pam_unix(sshd:session): session closed for user XXUSERXX
Apr  6 15:59:21 SERVER polkitd(authority=local): Unregistered Authentication Agent for unix-session:330153 (system bus name :1.45, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
```

Hope this can help.

Thanks.

**Comment by martinpitt** [comment]
I'm afraid the above logs don't contain information wrt. that failure, and I can't reproduce this. I wonder if this is somehow getting confused by existing machine definitions? Can you please give us the contents of `/var/lib/cockpit/machines.json` (if it exists) and all `/etc/cockpit/machines.d/*.json` files?

**Comment by martinpitt** [comment]
BTW, if you are concerned about keeping your defined remotes private, feel free to obfuscate them; it just needs to be clear what is for my.server.com and what not (these other entries are most likely irrelevant for this bug, but having the complete set might increase our chances of reproducing this).

**Comment by f3rno** [comment]
I'm seeing this as well; I'm running Fedora 25 and attempting to connect to an Ubuntu 16.04 server (both machines have `cockpit` installed). I've enabled logging, but nothing shows up besides:

```
Apr 18 03:46:59 kira cockpit-ws[27366]: 1: added channel 1:2!29 to socket                                                                                                                
Apr 18 03:46:59 kira cockpit-ws[27366]: 1: remove channel 1:2!29 for socket                                                                                                              
Apr 18 03:47:02 kira cockpit-ws[27366]: 1: added channel 1:2!30 to socket                                                                                                                
Apr 18 03:47:03 kira cockpit-ws[27366]: 1: remove channel 1:2!30 for socket                                                                                                              
Apr 18 03:47:03 kira cockpit-ws[27366]: 1: added channel 1:2!31 to socket                                                                                                                
Apr 18 03:47:05 kira cockpit-ws[27366]: 1: added channel 1:2!32 to socket                                                                                                                
Apr 18 03:47:05 kira cockpit-ws[27366]: 1: remove channel 1:2!32 for socket
...
```

The error shown in the login dialog box is: `Failed to add machine: Unexpected type 'int' in argument`. If it helps, I am trying to log in w/ pubkey auth (encrypted key) on a non-standard ssh port.

**Comment by petervo** [comment]
@f3rno what version of cockpit is present on fedora 25? Can you send the full log with pastebin or something like that? is there anything in the browser console?

**Comment by martinpitt** [comment]
@f3rno, please attach your `machines.d` files as asked in [the above comment](https://github.com/cockpit-project/cockpit/issues/6291#issuecomment-292855439). Thanks!

**Comment by martinpitt** [comment]
I just ran into that. In `update_saved_machine()`, the built `values_variant.port` has `t == "s"` and `v == 659` which would explain the type mismatch.
