### ISSUE TITLE
Cockpit 137 doesn't display existing volume group

### ISSUE THREAD

**Issue by sgallagher** [cockpit-project/cockpit#6298]
![screenshot from 2017-04-07 10-54-39](https://cloud.githubusercontent.com/assets/739555/24805705/b91b637a-1b80-11e7-83fb-3b5169a24cd4.png)

The Cockpit UI does not show my volume group created as part of Fedora system installation atop a LUKS encrypted partition:

```
[sgallagh@sgallagh540:~]$ sudo pvdisplay
  --- Physical volume ---
  PV Name               /dev/mapper/luks-b6e4cec3-4472-4f72-a853-375bdd3b1981
  VG Name               fedora_sgallagh540
  PV Size               237.98 GiB / not usable 3.00 MiB
  Allocatable           yes 
  PE Size               4.00 MiB
  Total PE              60923
  Free PE               1
  Allocated PE          60922
  PV UUID               MvVGOF-8NQ5-stIG-4cOt-JdNO-vOsn-eJDzXe
   
[sgallagh@sgallagh540:~]$ sudo vgdisplay
  --- Volume group ---
  VG Name               fedora_sgallagh540
  System ID             
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  4
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                3
  Open LV               3
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               237.98 GiB
  PE Size               4.00 MiB
  Total PE              60923
  Alloc PE / Size       60922 / 237.98 GiB
  Free  PE / Size       1 / 4.00 MiB
  VG UUID               9X960N-BAHS-3Ewv-xVQ7-1Lt0-t3A9-Wxoiec
   
[sgallagh@sgallagh540:~]$ sudo lvdisplay
  --- Logical volume ---
  LV Path                /dev/fedora_sgallagh540/root
  LV Name                root
  VG Name                fedora_sgallagh540
  LV UUID                honOg9-KxQE-Hb7u-7rtt-9Z4g-KVjx-p0MTb2
  LV Write Access        read/write
  LV Creation host, time sgallagh540.sgallagh.rht, 2015-02-19 15:48:39 -0500
  LV Status              available
  # open                 1
  LV Size                50.00 GiB
  Current LE             12800
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           253:1
   
  --- Logical volume ---
  LV Path                /dev/fedora_sgallagh540/home
  LV Name                home
  VG Name                fedora_sgallagh540
  LV UUID                zGchYN-A7so-DtEk-vuw7-95X7-I6vb-21dq7f
  LV Write Access        read/write
  LV Creation host, time sgallagh540.sgallagh.rht, 2015-02-19 15:48:43 -0500
  LV Status              available
  # open                 1
  LV Size                180.29 GiB
  Current LE             46154
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           253:3
   
  --- Logical volume ---
  LV Path                /dev/fedora_sgallagh540/swap
  LV Name                swap
  VG Name                fedora_sgallagh540
  LV UUID                0af1NP-lkOu-ccra-ncAG-f3T9-32YN-E58XPY
  LV Write Access        read/write
  LV Creation host, time sgallagh540.sgallagh.rht, 2015-02-19 15:48:46 -0500
  LV Status              available
  # open                 2
  LV Size                7.69 GiB
  Current LE             1968
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           253:2
```

**Comment by mvollmer** [comment]
@sgallagher, what is the storaged / udisks2 version?  Could you show `storagectl dump` or `udisksctl dump`?

**Comment by sgallagher** [comment]
@mvollmer OK, this is odd. When I launched Cockpit today, the volume group was properly displayed. I'll see if I can reproduce the issue somehow.

**Comment by mvollmer** [comment]
> When I launched Cockpit today, the volume group was properly displayed. I'll see if I can reproduce the issue somehow.

I think I have seen this issue with Fedora 25.  Restarting storaged seems to help.  If you can figure out a reproducer for this, that would be awesome.

**Comment by sgallagher** [comment]
I suspect it may be a disconnect when I upgraded Cockpit to the latest version and restarted `cockpit.service` but didn't also restart `storaged.service`. I will see if I can reproduce it when version 138 is released.

**Comment by dperpeet** [comment]
@sgallagher Were you able to reproduce the issue?

**Comment by sgallagher** [comment]
Sorry, I completely forgot about this. I'll try updating now.

**Comment by sgallagher** [comment]
Many apologies for the long return to this. I can confirm that today when I did `dnf update cockpit\* --enablerepo=updates-testing` on my F26 system to go from Cockpit 142->143, I hit this bug again.

**Comment by monreal** [comment]
Just ran into this myself, kind of. Solution was to install the udisks2-lvm2 which for some reason was not installed by default by the Fedora ARM Server 28 image...

**Comment by mvollmer** [comment]
@monreal, did you have a "Volume Group" panel in Cockpit before you installed udisks2-lvm2?

The issue here is that Cockpit shows an _empty_ Volume Group panel although there is a volume group in the system.  When not all needed components are installed for LVM2 support in Cockpit, then Cockpit should show _no_ Volume Group panel.

**Comment by monreal** [comment]
@mvollmer not sure and no way to recreate the situation ATM

**Comment by mvollmer** [comment]
Let's close this until we figure out how to reproduce this.
