### ISSUE TITLE
Storage module confused by overlay mounts

### ISSUE THREAD

**Issue by fsateler** [cockpit-project/cockpit#6303]
The storage module seems to think that my `/dev/sda5` is mounted at `/var/lib/docker/overlay` and I have nothing mounted in `/`:

![image](https://cloud.githubusercontent.com/assets/1322013/24822876/2cf6950a-1bcf-11e7-9dde-fed541889b73.png)

In reality, `/dev/sda5` is the root fs:

```
% findmnt /
TARGET SOURCE    FSTYPE OPTIONS
/      /dev/sda5 ext4   rw,relatime,errors=remount-ro,data=ordered
% findmnt /var/lib/docker/overlay
TARGET                  SOURCE                             FSTYPE OPTIONS
/var/lib/docker/overlay /dev/sda5[/var/lib/docker/overlay] ext4   rw,relatime,errors=remount-ro,data=ordered
```

I don't know what other information might me needed to diagnose this. Cockpit is the recently accepted debian package (137-3), udisks is 2.1.8.

EDIT: upgrading udisks to 2.6.4 does not solve the issue.

**Comment by fsateler** [comment]
Interestingly, in the drive view the information appears correct:

![image](https://cloud.githubusercontent.com/assets/1322013/24822995/550ca5c4-1bd0-11e7-9346-fe5f280e399e.png)

**Comment by mvollmer** [comment]
Yes, "confused" is the right word.  I think Cockpit / UDisks2 are technically correct, and correctly reflect `/proc/mounts`, but the UI is not the most helpful.  We should somehow hide 'internal' mount points that the user should better not touch.

This is not a regression and should be harmless, but we should improve the behavior.

What is your expectation?  Should Cockpit only show "/" and be completely silent about "/var/lib/docker/overlay"?

I have a TODO item to address this: https://trello.com/c/1ws6qXYt/365-storage-more-control-over-mounting

**Comment by fsateler** [comment]
> What is your expectation? Should Cockpit only show "/" and be completely silent about "/var/lib/docker/overlay"?

I would have expected that "/" is listed. Bind mounts should probably be listed separately (or marked somehow), since they are not a storage device (but they are important nonetheless).

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
