### ISSUE TITLE
Manage system time settings

### ISSUE THREAD

**Issue by nphilipp** [cockpit-project/cockpit#632]
Cockpit should offer a way to set the system time zone as well as set date/time -- either manually, or by using/configuring NTP (ntpd, chrony, or that new-fangled systemd service doing that).

**Comment by Aayush-Kasurde** [comment]
Do we have a mockup design for managing time settings ?

**Comment by stefwalter** [comment]
No not yet. I imagine this would go into a dialog on the server summary page (ie: the one that lists the BIOS, host name, and has graphs).

**Comment by andreasn** [comment]
Design for setting the time automatically via NTP server or manually with datepicker and clock.

![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/timendate/timendate.png)
