### ISSUE TITLE
Enable/start created timers by default

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#6326]
This came up while reviewing PR #6324: Currently, `test/verify/check-services  TestServices.testCreateTimer` enables the newly created timer. But this is odd -- why would the test have to do it? If the user creates a timer, then surely she'd want to actually use it? I think pkg/systemd/init.js itself should `systemctl enable --now` the newly created timer.

**Comment by mvollmer** [comment]
@andreasn, what do you think?

**Comment by andreasn** [comment]
So this means that a administrator will:
1. Go to the Timers page
2. Press the Create Timer button
3. Set timer to a specific time, and that time is five minutes later
4. The timer will run five minutes later

Yeah, I think that makes sense.
