### ISSUE TITLE
Fedora 26:  kube-apiserver.service fails to start: first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#6327]
kube-apiserver.service does not start any more in Fedora 26 (still works fine in 25, CentOS 7, etc.):

    E0411 12:36:28.827991     486 server.go:254] Failed to create clientset: parse 127.0.0.1:8080: first path segment in URL cannot contain colon

This was apparently reported as https://github.com/kubernetes/kubernetes/issues/38380 and fixed later on, but it seems the fix is still missing in Fedora 26.

I filed this as https://bugzilla.redhat.com/show_bug.cgi?id=1441218 . Filing this for tracking this as a known issue for the time being, to unblock testing on Fedora 26 (see PR #6294).

**Comment by martinpitt** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "check-kubernetes", line 35, in setUp
    self.start_kubernetes()
  File "kubelib.py", line 53, in start_kubernetes
    self.machine.execute("systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet")
  File "testvm.py", line 414, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet' returned non-zero exit status 1
```
First occurrence: 2017-04-11T23:39:20.794291
Times recorded: 1
Latest occurrences:

- 2017-04-11T23:39:20.794291

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-kubernetes", line 58, in testConnect
    self.start_kubernetes()
  File "/build/cockpit/test/verify/kubelib.py", line 65, in start_kubernetes
    self.machine.execute("systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet")
  File "/build/cockpit/test/common/testvm.py", line 437, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet' returned non-zero exit status 1
```
First occurrence: 2017-07-18T08:36:19.085794 | revision 3c077f226f2f515ffcf9e38901cc2a8a8d1950e1, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7315-20170718-081919-3c077f22-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-07-18T08:36:19.085794 | revision 3c077f226f2f515ffcf9e38901cc2a8a8d1950e1, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7315-20170718-081919-3c077f22-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-kubernetes", line 35, in setUp
    self.start_kubernetes()
  File "/build/cockpit/test/verify/kubelib.py", line 65, in start_kubernetes
    self.machine.execute("systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet")
  File "/build/cockpit/test/common/testvm.py", line 437, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet' returned non-zero exit status 1
```
First occurrence: 2017-07-18T08:36:39.086051 | revision 3c077f226f2f515ffcf9e38901cc2a8a8d1950e1, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7315-20170718-081919-3c077f22-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-07-18T08:36:39.086051 | revision 3c077f226f2f515ffcf9e38901cc2a8a8d1950e1, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7315-20170718-081919-3c077f22-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-kubernetes", line 35, in setUp
    self.start_kubernetes()
  File "/build/cockpit/test/verify/kubelib.py", line 65, in start_kubernetes
    self.machine.execute("systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet")
  File "/build/cockpit/test/common/testvm.py", line 437, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet' returned non-zero exit status 1
```
First occurrence: 2017-07-18T08:37:01.265418 | revision 3c077f226f2f515ffcf9e38901cc2a8a8d1950e1, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7315-20170718-081919-3c077f22-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-07-18T08:37:01.265418 | revision 3c077f226f2f515ffcf9e38901cc2a8a8d1950e1, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7315-20170718-081919-3c077f22-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-kubernetes", line 35, in setUp
    self.start_kubernetes()
  File "/build/cockpit/test/verify/kubelib.py", line 65, in start_kubernetes
    self.machine.execute("systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet")
  File "/build/cockpit/test/common/testvm.py", line 437, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet' returned non-zero exit status 1
```
First occurrence: 2017-07-18T13:04:45.825880 | revision 0789fcfea972c9488cb518eaeb060a775e7f8fab, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7265-20170718-124949-0789fcfe-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-07-18T13:04:45.825880 | revision 0789fcfea972c9488cb518eaeb060a775e7f8fab, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7265-20170718-124949-0789fcfe-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-kubernetes", line 35, in setUp
    self.start_kubernetes()
  File "/build/cockpit/test/verify/kubelib.py", line 65, in start_kubernetes
    self.machine.execute("systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet")
  File "/build/cockpit/test/common/testvm.py", line 437, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet' returned non-zero exit status 1
```
First occurrence: 2017-07-18T13:05:07.042870 | revision 0789fcfea972c9488cb518eaeb060a775e7f8fab, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7265-20170718-124949-0789fcfe-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-07-18T13:05:07.042870 | revision 0789fcfea972c9488cb518eaeb060a775e7f8fab, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7265-20170718-124949-0789fcfe-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-kubernetes", line 35, in setUp
    self.start_kubernetes()
  File "/build/cockpit/test/verify/kubelib.py", line 65, in start_kubernetes
    self.machine.execute("systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet")
  File "/build/cockpit/test/common/testvm.py", line 437, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet' returned non-zero exit status 1
```
First occurrence: 2017-07-18T13:05:26.387417 | revision 0789fcfea972c9488cb518eaeb060a775e7f8fab, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7265-20170718-124949-0789fcfe-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-07-18T13:05:26.387417 | revision 0789fcfea972c9488cb518eaeb060a775e7f8fab, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7265-20170718-124949-0789fcfe-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-kubernetes", line 35, in setUp
    self.start_kubernetes()
  File "/build/cockpit/test/verify/kubelib.py", line 65, in start_kubernetes
    self.machine.execute("systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet")
  File "/build/cockpit/test/common/testvm.py", line 437, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet' returned non-zero exit status 1
```
First occurrence: 2017-07-18T13:05:45.437586 | revision 0789fcfea972c9488cb518eaeb060a775e7f8fab, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7265-20170718-124949-0789fcfe-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-07-18T13:05:45.437586 | revision 0789fcfea972c9488cb518eaeb060a775e7f8fab, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7265-20170718-124949-0789fcfe-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-kubernetes", line 58, in testConnect
    self.start_kubernetes()
  File "/build/cockpit/test/verify/kubelib.py", line 65, in start_kubernetes
    self.machine.execute("systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet")
  File "/build/cockpit/test/common/testvm.py", line 437, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet' returned non-zero exit status 1
```
First occurrence: 2017-07-19T09:29:47.647621 | revision 04c7c4d5029ccc6bcef25d1fbb3a97d23032fc08, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7329-20170719-092121-04c7c4d5-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-07-19T09:29:47.647621 | revision 04c7c4d5029ccc6bcef25d1fbb3a97d23032fc08, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7329-20170719-092121-04c7c4d5-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-kubernetes", line 35, in setUp
    self.start_kubernetes()
  File "/build/cockpit/test/verify/kubelib.py", line 65, in start_kubernetes
    self.machine.execute("systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet")
  File "/build/cockpit/test/common/testvm.py", line 437, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet' returned non-zero exit status 1
```
First occurrence: 2017-07-19T09:30:08.594232 | revision 04c7c4d5029ccc6bcef25d1fbb3a97d23032fc08, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7329-20170719-092121-04c7c4d5-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-07-19T09:30:08.594232 | revision 04c7c4d5029ccc6bcef25d1fbb3a97d23032fc08, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7329-20170719-092121-04c7c4d5-verify-fedora-26/log.html)

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-kubernetes", line 35, in setUp
    self.start_kubernetes()
  File "/build/cockpit/test/verify/kubelib.py", line 65, in start_kubernetes
    self.machine.execute("systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet")
  File "/build/cockpit/test/common/testvm.py", line 437, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet' returned non-zero exit status 1
```
First occurrence: 2017-07-19T09:30:28.998045 | revision 04c7c4d5029ccc6bcef25d1fbb3a97d23032fc08, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7329-20170719-092121-04c7c4d5-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2017-07-19T09:30:28.998045 | revision 04c7c4d5029ccc6bcef25d1fbb3a97d23032fc08, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7329-20170719-092121-04c7c4d5-verify-fedora-26/log.html)
