### ISSUE TITLE
storaged: long lines for mount point creates a line break

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#6335]
It makes it's size disproportional compared to the others
![screenshot from 2017-04-13 11-46-45](https://cloud.githubusercontent.com/assets/209895/24999758/152ba04a-203f-11e7-88b6-4070931b6df4.png)

**Comment by andreasn** [comment]
@mvollmer @garrett
What's the best way to solve this?

**Comment by andreasn** [comment]
Apparently it's two different <div>s.
I think this is two different mount points.
Maybe put a comma between them is best?

**Comment by mvollmer** [comment]
We will probably end up ignoring the second mount in this particular case, but a comman can't hurt.

See https://trello.com/c/1ws6qXYt/365-storage-more-control-over-mounting

**Comment by KKoukiou** [comment]
@andreasn please let me know if adding a comma is acceptable solution here so that I can't post the fix.

**Comment by andreasn** [comment]
Yeah, let's do a comma separated list!

**Comment by marusak** [comment]
![commaseparatedlist](https://user-images.githubusercontent.com/12330670/69634395-653bc500-1052-11ea-941d-aea4942cc54e.png)
There is now comma
