### ISSUE TITLE
Unable to install cockpit in centos 7.2.

### ISSUE THREAD

**Issue by RatanShreshtha** [cockpit-project/cockpit#6337]
I am trying to install cockpit on a server running on centos 7.2 but I keep getting following error.

```
Error: docker-ce-selinux conflicts with 2:container-selinux-2.9-4.el7.noarch
Error: docker-ce conflicts with 2:docker-1.12.6-11.el7.centos.x86_64

```

Kernel version is 3.10.0-514.10.2.el7.x86_64.

**Comment by petervo** [comment]
This is related to https://github.com/cockpit-project/cockpit/pull/5943. Basically the problem is the cockpit-docker depends on docker. But there are so many other docker-x packages that are used instead that cause conflicts.
