### ISSUE TITLE
Get cgroup from container instead of guessing container from cgroup

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#634]
Right now we try to find the container id by looking at cgroup names with some regular expressions.  It would be more reliable and future-proof to get all cgroups for a container by some means.

One way would be to check /proc/PID/cgroup, where PID is from container.State.PID.

The CGroupMonitor could be changed to take a set of PIDs as parameter, with the meaning to monitor the cgroups that these PIDs are in.  This would also work for services.

**Comment by stefwalter** [comment]
This is no longer needed. In addition if we want to do this right, we should make 'docker stats' work better and have a better API.
