### ISSUE TITLE
Issue update 135.4e17 for Centos 7

### ISSUE THREAD

**Issue by pcaviede** [cockpit-project/cockpit#6365]
Hello:
I could not update Cockpit to version 135.4e17 today, the system reports a conflict with the cockpit network manager. I'd greatly appreciate your help.

Here is the log:

-----------------------
 yum update
Loaded plugins: fastestmirror, langpacks, product-id, search-disabled-repos, subscription-manager
This system is registered with Subscription Management, but is not receiving updates. You can use subscription-manager to assign subscriptions.
Loading mirror speeds from cached hostfile
 * base: mirror.orbyta.com
 * epel: mirror.us.leaseweb.net
 * extras: mirror.orbyta.com
 * remi: repo1.sea.innoscale.net
 * remi-php56: repo1.sea.innoscale.net
 * remi-safe: repo1.sea.innoscale.net
 * updates: mirror.orbyta.com
Resolving Dependencies
--> Running transaction check
---> Package cockpit.x86_64 0:131-3.el7.centos will be updated
---> Package cockpit.x86_64 0:135-4.el7.centos will be an update
---> Package cockpit-bridge.x86_64 0:131-3.el7.centos will be updated
---> Package cockpit-bridge.x86_64 0:135-4.el7.centos will be an update
---> Package cockpit-dashboard.x86_64 0:131-3.el7.centos will be updated
---> Package cockpit-dashboard.x86_64 0:135-4.el7.centos will be an update
---> Package cockpit-docker.x86_64 0:131-3.el7.centos will be updated
---> Package cockpit-docker.x86_64 0:135-4.el7.centos will be an update
---> Package cockpit-storaged.noarch 0:131-3.el7.centos will be updated
---> Package cockpit-storaged.noarch 0:135-4.el7.centos will be an update
---> Package cockpit-system.noarch 0:131-3.el7.centos will be updated
---> Package cockpit-system.noarch 0:135-4.el7.centos will be an update
---> Package cockpit-ws.x86_64 0:131-3.el7.centos will be updated
---> Package cockpit-ws.x86_64 0:135-4.el7.centos will be an update
--> Finished Dependency Resolution

Dependencies Resolved

=======================================================================================================================================================
 Package                                  Arch                          Version                                    Repository                     Size
=======================================================================================================================================================
Updating:
 cockpit                                  x86_64                        135-4.el7.centos                           extras                         41 k
 cockpit-bridge                           x86_64                        135-4.el7.centos                           extras                        447 k
 cockpit-dashboard                        x86_64                        135-4.el7.centos                           extras                        170 k
 cockpit-docker                           x86_64                        135-4.el7.centos                           extras                        246 k
 cockpit-storaged                         noarch                        135-4.el7.centos                           extras                        161 k
 cockpit-system                           noarch                        135-4.el7.centos                           extras                        831 k
 cockpit-ws                               x86_64                        135-4.el7.centos                           extras                        418 k

Transaction Summary
=======================================================================================================================================================
Upgrade  7 Packages

Total size: 2.3 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test

Transaction check error:
  file /usr/share/cockpit/networkmanager/manifest.json from install of cockpit-system-135-4.el7.centos.noarch conflicts with file from package cockpit-networkmanager-131-3.el7.centos.noarch
  file /usr/share/cockpit/networkmanager/index.html.gz from install of cockpit-system-135-4.el7.centos.noarch conflicts with file from package cockpit-networkmanager-131-3.el7.centos.noarch
  file /usr/share/cockpit/networkmanager/network.css.gz from install of cockpit-system-135-4.el7.centos.noarch conflicts with file from package cockpit-networkmanager-131-3.el7.centos.noarch
  file /usr/share/cockpit/networkmanager/network.min.js.gz from install of cockpit-system-135-4.el7.centos.noarch conflicts with file from package cockpit-networkmanager-131-3.el7.centos.noarch

Error Summary
-------------

**Comment by petervo** [comment]
@dperpeet, do we need a depreciates in our spec file? Did we used to ship cockpit-networkmanager as a separate package on centos/rhel?

@pcaviede You didn't install from a copr or something like that did you? 

In the mean time if you remove cockpit-networkmanager you should be able to complete the upgrade.

**Comment by pcaviede** [comment]
Hi. I updated from the official repos via yum. I tried  your suggestion and the upgrade was successful. Thanks!

**Comment by rexlx** [comment]
Any word on this? I'm still getting issues when I attempt to update cockpit.

Here is the error summary:

Transaction check error:
  file /usr/share/cockpit/networkmanager/index.html.gz conflicts between attempted installs of cockpit-networkmanager-131-3.el7.centos.noarch and cockpit-system-135-4.el7.centos.noarch
  file /usr/share/cockpit/networkmanager/manifest.json conflicts between attempted installs of cockpit-networkmanager-131-3.el7.centos.noarch and cockpit-system-135-4.el7.centos.noarch
  file /usr/share/cockpit/networkmanager/network.css.gz conflicts between attempted installs of cockpit-networkmanager-131-3.el7.centos.noarch and cockpit-system-135-4.el7.centos.noarch
  file /usr/share/cockpit/networkmanager/network.min.js.gz conflicts between attempted installs of cockpit-networkmanager-131-3.el7.centos.noarch and cockpit-system-135-4.el7.centos.noarch

Error Summary
-------------

**Comment by pcaviede** [comment]
I believe it's still under revision. I had the same issue, a temporary 
workaround is to unistall cockpit-networkmanager and then update 
cockpit. Worked for me

**Comment by petervo** [comment]
@dperpeet can you look into what version of cockpit-network needs to be deprecated by cockpit-system and for which os's?

**Comment by rexlx** [comment]
Whats weird is i completely removed cockpit to do an update but when I attempt to reinstall it I get the errors mentioned earlier. Here are a few commands I ran:

[root@instance-1 bin]# **rpm -qa | grep -i cockpit**
[root@instance-1 bin]# 
[root@instance-1 bin]# 
[root@instance-1 bin]# **locate cockpit | grep -i networkmanager**
_/var/cache/yum/x86_64/7/extras/packages/cockpit-networkmanager-131-3.el7.centos.noarch.rpm._

I'm not having any issues on my fedora 25 builds, which are all real hardware. But my CentOS 7 instances (openstack and google cloud) are having this issue.

**Comment by pcaviede** [comment]
Don't remove cockpit entirely, only the network manager. Then update 
cockpit. Worked for me!

**Comment by deryni** [comment]
We ran into this on CentOS 7 upgrading from cockpit-131 to cockpit-135.

The cockpit-135 package bundles the networkmanager files whereas 131 had a separate package for them.

What's weird is that I can still see the networkmanager sub-package entry in the cockpit spec file it just doesn't seem to have built that way for some reason.

**Comment by pcaviede** [comment]
Indeed. Removing networkmanager for Cockpit, and then upgrading, did the 
trick for me

**Comment by elico** [comment]
So just to understand:
is the "cockpit-networkmanager" CentOS package no longer in use and it's in the repo since it was there in the past?

**Comment by pcaviede** [comment]
From version 1.38,  networkmanager is embedded in the Cockpit package. Removing the old networkmanager, and then updating to 1.38 via yum should work.

**Comment by elico** [comment]
@pcaviede Thanks.
Now it makes more sense.
