### ISSUE TITLE
Stats of Different Servers only show data of the same single Server

### ISSUE THREAD

**Issue by FloThinksPi** [cockpit-project/cockpit#6366]
So when adding multiple servers in Cockpit , all stats in the Dashboard view are equal for each server. Somehow the stats of one server get shown for every server.

![34992088-267a-11e7-85f8-d7e3f6459ddb](https://cloud.githubusercontent.com/assets/5863788/25269454/fcb7b762-267c-11e7-90f4-db4cc09bc976.png)

The main server which runs cockpit is on centos7  with cockpit 138. The Storage Server has the same configuration. On the Raspberry pi i compiled version 0.99 on raspian(Newest version did not compile). This issue also occured when just having the 2 CentOS systems in Cockpit. 

In the detailed view you can view the simmilarity of the stats, however the maximum of each graph is correct but the values are only from one host. 

![image](https://cloud.githubusercontent.com/assets/5863788/25268927/e2c3d4fa-267a-11e7-9ef2-395887a53862.png)

![unbenannt](https://cloud.githubusercontent.com/assets/5863788/25269264/2afd0b46-267c-11e7-84dd-b98d6c7d4e30.png)

Furthermore when clicking in the detailed RAM view of any server, i get completely off stats. On every server i get this chart.

![image](https://cloud.githubusercontent.com/assets/5863788/25269285/3faee988-267c-11e7-9701-976a334442a6.png)

The Raspberry has 1Gb, StorageServer has 6GB and the Main server has 4GB so i dont really know what this graph shows now but i suspect it to be the ram statisics of the StorageServer.
Verry Odd behaviour.

**Comment by petervo** [comment]
@FloThinksPi Thanks for catching this. It is indeed a bug. I will fix.

**Comment by petervo** [comment]
Have a fix for this here #6368

**Comment by FloThinksPi** [comment]
@petervo Thanks, this should fix it then in Version 140.
