### ISSUE TITLE
Can't login in the Vagrant development mode.

### ISSUE THREAD

**Issue by CrisLi** [cockpit-project/cockpit#6375]
Follow the [document](https://github.com/cockpit-project/cockpit/blob/master/HACKING.md#working-on-cockpit-using-vagrant) to install vagrant.

The server has been started up, but can't login with 'admin'/'foobar'.

The developer web tools console log is following:

```
GET http://localhost:9090/cockpit/login 401 (Authentication failed)
standard_auto_login @ (index):428
boot @ (index):406
Navigated to http://localhost:9090/
GET http://localhost:9090/cockpit/login 401 (Authentication failed)
```

**Comment by petervo** [comment]
That user / pw works for me. It may be that the port forwarding isn't working (exisiting cockpit running on that port?)

Try accessing the VM directly using it's ip address directly and port 9090. ei http://192.168.121.140:9090

**Comment by stefwalter** [comment]
No reply from reporter closing.
