### ISSUE TITLE
Simplify storage update triggers

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#64]
We currently try to only recreate a page when something in the D-Bus tree changes that actually contributes to the page.

This is hairy and not really worthwhile. We can just recreate the page when anything at all below /com/redhat/Cockpit/Storage changes. 

At the same time, we mights not recreate the whole page when the RAID repair progress changes, as we do now.

But then again, the progress change is already throttled and will advance very slowly for real world arrays anyway.

**Comment by dperpeet** [comment]
@mvollmer I think the storage page now updates more selectively.

**Comment by mvollmer** [comment]
Yes, this has been addressed.
