### ISSUE TITLE
File not Found | 404 Error

### ISSUE THREAD

**Issue by computergott** [cockpit-project/cockpit#6406]
When I do "apt-get upgrade" I get an 404 Error

N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
**E: Fehlschlag beim Holen von http://ppa.launchpad.net/cockpit-project/cockpit/ubuntu/dists/zesty/main/binary-i386/Packages  404  Not Found**
E: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.

**Comment by petervo** [comment]
Currently only xenial packages are available with that PPA.

**Comment by martinpitt** [comment]
Note that cockpit is in Ubuntu 17.04 (zesty), so you can just install it as usual without the PPA.

**Comment by stefwalter** [comment]
@martinpitt Should we update http://cockpit-project.org/running.html to say that?

**Comment by martinpitt** [comment]
@stefwalter: Done last week in https://github.com/cockpit-project/cockpit-project.github.io/pull/65 (not merged yet)
