### ISSUE TITLE
Configure NFS server and exports

### ISSUE THREAD

**Issue by nphilipp** [cockpit-project/cockpit#641]
It would be great if Cockpit let admins configure NFS exports and related server flags.

**Comment by martinpitt** [comment]
This has just been sitting here for 5 years, this is too big a topic for a GitHub issue. The last time we discussed this we found that this would fit much better as a third-party project/extension which can be installed via the Applications page. The Cockpit team is happy to assist interested developers with setting this up and integrating with CI/CD, but we won't develop this ourselves.

See https://cockpit-project.org/blog/cockpit-starter-kit.html and the other documentation on  https://cockpit-project.org/external/wiki/Contributing.html
