### ISSUE TITLE
Building on Raspbian fails

### ISSUE THREAD

**Issue by machadotiago** [cockpit-project/cockpit#6428]
Hi !
after this commit https://github.com/cockpit-project/cockpit/commit/a92018188424628d2c80e1720f3a6384758df477 we are now having problems for generating the make files on Raspbian. Basically the problem is related to one of the dependencies added to the package.json: the phantomjs
Phantomjs is not yet available for Raspbian and this is breaking autogen.sh during the execution of "npm install"
Currently I'm manually removing this dependency (since it's just for testing).

**Comment by petervo** [comment]
@machadotiago if you put phantomjs-prebuilt in optionalDependencies instead of devDependencies in package.json does it work?

or @martinpitt, do you have a different suggestion

**Comment by machadotiago** [comment]
Yes, adding it as an optional dependency worked for me.
