### ISSUE TITLE
More options for account management

### ISSUE THREAD

**Issue by nphilipp** [cockpit-project/cockpit#644]
Cockpit lets admins manage basic high level aspects of accounts (real and user names, passwords, "roles", "mugshot", locking of an account), but should also offer to manage these (for lack of better word) "advanced" settings:
- custom UID/GID, home directory, login shell
- password- and account expiration
- force password change on next login (so an admin can reset PW to a temp value and the user sets their own one)
- manage groups and their members

**Comment by fridex** [comment]
Is there any mockup design available?

BTW, it looks like there is currently no implementation for changing UID/GID in accountsservice.

**Comment by stefwalter** [comment]
I've been looking at migrating away accountsservice for this and other reasons. See #1853

**Comment by fridex** [comment]
Will these "advanced options" be available when creating a new account or is it meant only for managing existing ones?

@andreasn Any mockup design available?

**Comment by andreasn** [comment]
@fridex not yet, but I can get on it. Do we want to mash up all these things in one issue, or would it be better to split it up perhaps?
All of them needs a bit of work and thought to them, so it sounds hard to try and solve them all in one bit. If I were to tackle one problem first, what would it be?
Out of the list above, I personally think the password strength is most critical.

**Comment by fridex** [comment]
@andreasn yes, I would prefer to solve this in separate issues.

**Comment by andreasn** [comment]
Since #2032, #2062, #2061 and #2075 was merged into master ages ago, I'll go ahead and close this.
Feel free to open a new issues about any remaining problems.
