### ISSUE TITLE
Dashboard tab is missing.

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [cockpit-project/cockpit#6486]
After cockpit (version 135) installation I've realised that dashboard tab is missing on RHEL and CENTOS.

**Comment by stefwalter** [comment]
You can install cockpit-dashboard to get that tab back. RHEL and CentOS currently don't have that part by default.

**Comment by igorSmirnovPlexi** [comment]
Thank you. What about other distributions?

**Comment by stefwalter** [comment]
On Fedora, Debian and Ubuntu, cockpit-dashboard remains a recommended dependency and thus generally installed when you install "cockpit".

**Comment by stefwalter** [comment]
The reason for this comes down to dependencies. RHEL and CentOS don't have libssh in their base channels, they are in extra add-on channels.

**Comment by igorSmirnovPlexi** [comment]
Ok, thank you!

**Comment by raleighguevarra** [comment]
May I know how to add the cockpit dashboard? also, I don't see the disks, I only have these:

- System
- Logs
- Accounts
- Services
- Terminal

**Comment by martinpitt** [comment]
@raleighguevarra : See above, install the `cockpit-dashboard` package for the Dashboard. Or `cockpit-storaged` for disks. These are in extras, not installed by default.

**Comment by sureshkachwa** [comment]
Looks like there is no "cockpit-dashboard" for  Oracle Linux Server 7.7
