### ISSUE TITLE
When menu entry text is overflowed, show tooltip on mouse hoover.

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [cockpit-project/cockpit#6550]
In some cases, when menu entry is too long, text is truncated. For better user experience I suggest to show tooltip on mouse hoover, which will show full entry name. 

(Kernel dump configuration as an example) 
![screen shot 2017-05-14 at 3 49 29 pm](https://cloud.githubusercontent.com/assets/19838682/26033908/f5eeae8e-38bc-11e7-8ea0-ae674c648efc.png)

**Comment by stefwalter** [comment]
@garrett Is this something to work into your task switcher designs?

**Comment by garrett** [comment]
The tooltip enhancement issue I opened up last year (#3904) could cover this too.

Demo: https://codepen.io/garrett/pen/VaLGzw

**Comment by stefwalter** [comment]
@garrett Is this worth fixing on its own, before your task switcher changes land? If so, then @thomasmckay may be interested in working on it.

**Comment by garrett** [comment]
@stefwalter: It's worth fixing in a across the site. There are several places (mostly under constrained width) that could benefit from a more generic fix, in addition to the navigation.

So, yes, it could be a task for @thomasmckay.

**Comment by igorSmirnovPlexi** [comment]
Hi, is there anything new in this thread?

**Comment by garrett** [comment]
The label specifically was changed in commit 68fb5265a7 (Jun 29) and the new navigation (PR #7482 + #8102) provides better space for labels in general too.

**Comment by martinpitt** [comment]
We actually had a tooltip for that, but it became moot with the navigation redesign in Cockpit 155. So I think this can be closed now.
