### ISSUE TITLE
cockpit-kubernetes can't login

### ISSUE THREAD

**Issue by hongtao12310** [cockpit-project/cockpit#6562]
I am running kubernetes v1.6.1 on centos7 and use the latest image of cockpit/kubernetes. however i can't login the cockpit dashboard and the cockpit complain that "invalid user and password"

I  am running kube-apiserver with https enabled and use the basic user name and password authentication(--basic-auth-file) and i also enabled the --insecure-bind-address and --insecure-port

any suggestions ?

# kubectl logs kubernetes-cockpit-w7f3p
DEBUG: cockpit-protocol: Loaded configuration from: /etc/cockpit/cockpit.conf
DEBUG: cockpit-ws: auth is idle
DEBUG: cockpit-ws: received unknown/invalid credential cookie
DEBUG: cockpit-ws: spawning /usr/libexec/cockpit-kube-auth
DEBUG: cockpit-protocol: /usr/libexec/cockpit-kube-auth: output queue empty
DEBUG: cockpit-protocol: /usr/libexec/cockpit-kube-auth: reading input 1
DEBUG: cockpit-protocol: /usr/libexec/cockpit-kube-auth: received a 70 byte payload
DEBUG: cockpit-ws: received authorize challenge
DEBUG: cockpit-protocol: /usr/libexec/cockpit-kube-auth: queued 89 byte payload
DEBUG: cockpit-protocol: /usr/libexec/cockpit-kube-auth: want more data
DEBUG: cockpit-protocol: /usr/libexec/cockpit-kube-auth: wrote 4 bytes
DEBUG: cockpit-protocol: /usr/libexec/cockpit-kube-auth: wrote 89 bytes
DEBUG: cockpit-protocol: /usr/libexec/cockpit-kube-auth: output queue empty
2017/05/17 05:15:18 Couldn't get api version: 200 OK
DEBUG: cockpit-protocol: /usr/libexec/cockpit-kube-auth: reading input 1
DEBUG: cockpit-protocol: /usr/libexec/cockpit-kube-auth: received a 98 byte payload
DEBUG: cockpit-ws: session initialized
DEBUG: cockpit-ws: cockpit-kube-auth: authentication-failed Couldn't get api version: 200 OK
DEBUG: cockpit-protocol: /cockpit/login: returning error: 401 Authentication failed
DEBUG: cockpit-protocol: /cockpit/login: queued 41 bytes
DEBUG: cockpit-protocol: /cockpit/login: queued 21 bytes
DEBUG: cockpit-protocol: /cockpit/login: queued 3318 bytes
DEBUG: cockpit-protocol: /cockpit/login: queued 21 bytes
DEBUG: cockpit-protocol: /cockpit/login: queued 33 bytes
DEBUG: cockpit-protocol: /cockpit/login: queueing complete
DEBUG: cockpit-protocol: /usr/libexec/cockpit-kube-auth: end of output
DEBUG: cockpit-ws: web service closing
DEBUG: cockpit-protocol: received unknown control command: init
DEBUG: cockpit-protocol: /usr/libexec/cockpit-kube-auth: want more data
DEBUG: cockpit-protocol: /usr/libexec/cockpit-kube-auth: killing child: 19
DEBUG: cockpit-protocol: /usr/libexec/cockpit-kube-auth: closing pipe: terminated
DEBUG: cockpit-protocol: /usr/libexec/cockpit-kube-auth: killing child: 19
DEBUG: cockpit-protocol: /cockpit/login: sent 105 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 4 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 41 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 2 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 4 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 21 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 2 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 5 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 3318 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 2 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 4 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 21 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 2 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 4 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 33 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 2 bytes
DEBUG: cockpit-protocol: /cockpit/login: sent 5 bytes
DEBUG: cockpit-protocol: /cockpit/login: complete flushing output
DEBUG: cockpit-protocol: /cockpit/login: flushed output

**Comment by petervo** [comment]
@hongtao12310. Generally you don't need the insecure bind and port and the basic auth file, usually you run with one or the other.

What did your command to start up the cockpit/kubernetes service look like? Could you post your full list of kube-apiserver arguments that you are running with?

**Comment by hongtao12310** [comment]
@petervo Thanks for your messages

Hi Petervo,

I am running the cockpit as a pod in kubernetes. I paste the json file below. since the RBAC is enabled on kubernetes v1.6.1 . so i am using the cockpit service account and it was bound with the cluster admin role by creating a cluster role bindings 

   "kind":"List",
   "apiVersion":"v1",
   "items":[
      {
         "kind":"ReplicationController",
         "apiVersion":"v1",
         "metadata":{
            "name":"kubernetes-cockpit",
            "labels":{
               "name":"kubernetes-cockpit"
            }
         },
         "spec":{
            "replicas":1,
            "selector":{
               "name":"kubernetes-cockpit"
            },
            "template":{
               "metadata":{
                  "labels":{
                     "name":"kubernetes-cockpit"
                  }
               },
               "spec":{
                  "containers":[{
                    "name": "kubernetes-cockpit",
                    "image": "cockpit/kubernetes:latest",
		    "imagePullPolicy": "IfNotPresent",
                    "ports":[{
                        "containerPort":9090,
                        "protocol":"TCP"
                     }],
                    "env": [
			{
                        "name": "COCKPIT_KUBE_INSECURE",
                        "value": "true"
                        },
			{
			"name": "G_MESSAGES_DEBUG",
			"value": "all"
			}
	            ]
                  }],
	        "serviceAccountName": "cockpit"
               }
            }
         }
      }


and the Kube-apiserver arguments used as below:

    - kube-apiserver
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-allowed-names=front-proxy-client
    - --experimental-bootstrap-token-auth=true
    - --storage-backend=etcd3
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --secure-port=6443
    - --requestheader-username-headers=X-Remote-User
    - --service-cluster-ip-range=10.96.0.0/12
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --insecure-port=8080
    - --insecure-bind-address=0.0.0.0
    - --basic-auth-file=/etc/kubernetes/basic_auth.csv
    - --allow-privileged=true
    - --authorization-mode=RBAC
    - --advertise-address=10.214.160.9
    - --etcd-servers=http://10.214.160.9:2379,http://10.214.160.10:2379,http://10.214.160.11:2379

**Comment by petervo** [comment]
Thanks one other thing, can you kubectl exec into the kubernetes-cockpit pod and send me the output of running ```env```.

**Comment by hongtao12310** [comment]
Hi Petervo, 

below is the output of the env command in the kubernetes-cockpit pod container

[root@ctum2a2402007 ~]# docker exec 6fee3672b002 env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=kubernetes-cockpit-z6qwj
KUBE_INSECURE=false
G_MESSAGES_DEBUG=all
KUBERNETES_COCKPIT_PORT=tcp://10.110.210.70:9090
KUBERNETES_SERVICE_PORT_HTTPS=443
MYSQL_SERVICE_PORT=tcp://10.111.234.187:3306
ECHOHEADERS_PORT_80_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_PORT=443
MYSQL_SERVICE_PORT_3306_TCP_ADDR=10.111.234.187
ECHOHEADERS_SERVICE_PORT=80
KUBERNETES_COCKPIT_SERVICE_HOST=10.110.210.70
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
ECHOHEADERS_PORT_80_TCP=tcp://10.104.54.207:80
KUBERNETES_COCKPIT_SERVICE_PORT=9090
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
MYSQL_SERVICE_SERVICE_HOST=10.111.234.187
ECHOHEADERS_PORT_80_TCP_ADDR=10.104.54.207
KUBERNETES_COCKPIT_PORT_9090_TCP=tcp://10.110.210.70:9090
MYSQL_SERVICE_PORT_3306_TCP_PROTO=tcp
KUBERNETES_COCKPIT_PORT_9090_TCP_PORT=9090
MYSQL_SERVICE_SERVICE_PORT=3306
ECHOHEADERS_SERVICE_HOST=10.104.54.207
KUBERNETES_COCKPIT_PORT_9090_TCP_ADDR=10.110.210.70
MYSQL_SERVICE_PORT_3306_TCP_PORT=3306
KUBERNETES_COCKPIT_PORT_9090_TCP_PROTO=tcp
KUBERNETES_SERVICE_HOST=10.96.0.1
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
MYSQL_SERVICE_PORT_3306_TCP=tcp://10.111.234.187:3306
ECHOHEADERS_PORT=tcp://10.104.54.207:80
ECHOHEADERS_PORT_80_TCP_PORT=80
DISTTAG=f25docker
FGC=f25
FBR=f25
HOME=/root

the other question is i even don't know what is the exactly username and password to login. i am using the kubernetes basic_auth setting up . which is admin/admin

**Comment by petervo** [comment]
Yes it should be the u/p that is in /etc/kubernetes/basic_auth.csv

does what does

```
curl -k -u admin:admin https://10.96.0.1/api/
```

return

what about 

```
curl -k https://10.96.0.1/api/
```

**Comment by hongtao12310** [comment]
[root@ctum2a2402005 ~]# curl -k -u admin:admin https://10.96.0.1/api/
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "10.214.160.9:6443"
    }
  ]
}

[root@ctum2a2402005 ~]# curl -k https://10.96.0.1/api/
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "10.214.160.9:6443"
    }
  ]
}

**Comment by hongtao12310** [comment]
I also verified the u/p use another context. under the context i skip the tls verification and use the user in the basic_auth.csv 

and everything goes well. i can look up the pods/services/rs... and other resources. since i bind the user to the cluster-admin role

[root@ctum2a2402005 ~]# kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://10.214.160.9:6443
  name: kubernetes
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.214.160.9:6443
  name: local-server
contexts:
- context:
    cluster: local-server
    user: myself
  name: default-context
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: default-context
kind: Config
preferences: {}
users:
- name: cluster-admin
  user:
    password: YWRtaW4K
    username: admin
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    password: YWRtaW4K
    username: admin
- name: myself
  user:
    password: admin
    username: admin

**Comment by petervo** [comment]
@hongtao12310, I'm trying to replicate your environment, but I'm not seeing a kubernetes 1.6 package yet on centos. How did you install kubernetes?

**Comment by hongtao12310** [comment]
@petervo  I use kubeadm to install the kubernetes v1.6.1 

basically, reference to the page below
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

**Comment by petervo** [comment]
@hongtao12310, thanks for your help debugging this. It looks like in 1.6 kubernetes turned anonymous access on by default, and we don't support that yet. I'll work on a fix for that but in the mean time you can try running with.

```--anonymous-auth=false```

and see if that works for you.

**Comment by hongtao12310** [comment]
@petervo 

I tried to add the --anonymous-auth=false to the kube-apiserver. however, it seems that the apiserver was struggled to boot up.  it has ever successfully booted up but after a second the process was killed again.

Excitedly. when booted up. i can access the cockpit use the u/p to login the system. and good to see the dashboard. very cool !

Now. i think we will suspend to wait for your verification on v1.6.1 with cockpit . 

Jun 12 17:08:52 ctum2a2402005 kubelet: E0612 17:08:52.814169   15164 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:390: Failed to list *v1.Node: Get https://10.214.160.9:6443/api/v1/nodes?fieldSelector=metadata.name%3Dctum2a2402005&resourceVersion=0: dial tcp 10.214.160.9:6443: getsockopt: connection refused

**Comment by hongtao12310** [comment]
sounds like there will be some issue when kube v1.6.1 enabled with --anonymous-auth=false , I will also look into it .

**Comment by petervo** [comment]
@hongtao12310 I've made some fixes to make this work better with 1.6 on #6921. But that won't effect the problem with the api server dying. You might want to report that upstream to kuberentes and i think that would be their bug to fix.

**Comment by hongtao12310** [comment]
@petervo excellent !!

so if i was understanding correctly. we don't need to running apiserver with --anonymous-auth=false when including your fix , right ?

could you give some details about the fix ?

supposed , we can use the latest cockpit image after you PR was merged into master branch.?

**Comment by stefwalter** [comment]
Closing this now that #6921 has been merged and will be included in this week's release.

**Comment by moon03432** [comment]
kube-apiserver cannot boot up with --anonymous-auth=false because that livenessProbe still targets secure port and is forbidden. Also need to target livenessProbe to unsecure port like version 1.5.0 do:

    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15

**Comment by petervo** [comment]
@moon03432 we do not support connecting via the insecure port.
