### ISSUE TITLE
Front end reporting identical resource usage in dashboard

### ISSUE THREAD

**Issue by rexlx** [cockpit-project/cockpit#6568]
Hey guys, 

I'm currently running Cockpit on three CentOS 7 boxes. Two are virtual, one resides in Google Cloud and the other in our OpenStack rig. The third is the hyper-visor for the instance running in OpenStack I just mentioned. When I click on "dashboard" to view resource comparisons (cpu, memory, network, disk), the line graph shows all three boxes as having identical resource utilization. I've attached an image that depicts this. Cockpit seems to be running fine on all three boxes, but i went ahead and restarted the service on all for good measure since they've been running for some time. Thanks for all your help!

![cp-error1](https://cloud.githubusercontent.com/assets/23558766/26160943/2558ccd6-3ae8-11e7-9877-e3b47a8322e1.JPG)

**Comment by petervo** [comment]
I believe this was fixed in #6368. Please reopen if you are running 140 or greater and still seeing this problem.

**Comment by rexlx** [comment]
Video link:  https://drive.google.com/open?id=0B-VE2jW-mCy7NWFUQTF3Ti1oMEU

I still seem to be having the same issue, I've provided a link to a video (it got very compressed in the cloud so dont full screen it just full screen your browser) that shows whats going on. The servers in use are:

1. my laptop running korora 25 (really just fedora)
2. two fedora 26 builds
3. a centOS 7 build in google cloud
4. a centOS 7 build in openstack

All servers are updated on a very regular basis, so they have whatever the newest cockpit package is per their repo.

Thanks for all your help!

**Comment by petervo** [comment]
What version of cockpit is running on the machine that the dashboard is on?

**Comment by rexlx** [comment]
That would be version 137 on fedora 25. Is version 140+ not going to fedora 25 repos? i see my fedora 26 builds are running 151 and my centOS 7 builds are 148
