### ISSUE TITLE
Virtual machines reboot / shutdown button UI mod

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#6633]
At the request of @mareklibra in IRC today, I was working on the reboot / shutdown buttons. He asked about a confirmation step and we talked about forced shutdowns as well.

@mareklibra, @andreasn, and I then talked about a reboot / shutdown today (although not all together at once). I've made a mockup of how this could work, so that it:

1. Wouldn't have a confirmation step (as it is hidden away until the row is expanded)
2. Could integrate the forced shutdown step when shutting down normally is taking too long. (This could be anywhere from 5 - 20 seconds, depending on what "feels" right for a normal system shutdown.)
3. Would try to avoid extra UI like dialogs (either modal or popovers).

![reboot & shutdown mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/virtual-machines/restart-shutdown.png)

I'd like further input on this design from @andrean before committing to it. (It might need tweaks before @mareklibra's implementation.)

**Comment by mareklibra** [comment]
I was further thinking about that. The discussion lead us to following separate aspects:
- avoid confirmation
- delay the "Force" action

I'm still not convinced, we should not ask the user for confirmation of actions like Shut Down or Reset.

Right, in normal setup these actions are reversible by Run action.
But the VM is inoperative in the mean while and some application data or configuration might be lost. The VM be be running some server. The button might be still clicked accidentally. 

I can imagine operation, where accidental VM shut down can lead to a disaster.

The delay for the "Force"-version makes sense.

@garrett , @andreasn , can we rethink that?

**Comment by garrett** [comment]
Closing, as the associated PR was merged.
