### ISSUE TITLE
Calling commands requiring superuser sometimes fails for no apparent reason.

### ISSUE THREAD

**Issue by JacobCZ** [cockpit-project/cockpit#6696]
When trying to call a command that requires superuser rights using ```cockpit.call()```, sometimes the command works just fine and sometimes, it fails, without any error message beyond an exit status code.

This seems to be happening completely randomly.

Any ideas?

**Comment by stefwalter** [comment]
Hmmm, there is no ```cockpit.call()``` function.

Look at the journal logs of the system. Do you have any example code? Are you handling errors properly? Also feel free to ping people on Freenode IRC in the ```#cockpit``` channel.

**Comment by JacobCZ** [comment]
@stefwalter Sorry, I'm an idiot ^^. I mean ```cockpit.spawn()```

Also, nothing in logs

**Comment by JacobCZ** [comment]
Guys? Anyone?

**Comment by petervo** [comment]
Can you give some example code? Would be helpful to see your error handling.

Can when the call fails, can you run ps -xa | grep cockpit-bridge to see what is running.

**Comment by JacobCZ** [comment]
Hi, it seems to be working now for some reason, I will reply to this thread in case the problem occurs again...

**Comment by stefwalter** [comment]
No reply here so I'll assume the issue resolved itself. Glad if that's the case :)
