### ISSUE TITLE
Cockpit may use wrong passwords when escalating privileges in 'other' machines/VMs

### ISSUE THREAD

**Issue by cmacq2** [cockpit-project/cockpit#6709]
Given the following scenario:

1. Host machine Debian Sid/unstable with Virtualbox, cockpit package & browser
2. Host user account `host` with password 'host'
3. Virtualbox VM with Debian Sid/unstable with SSH server, sudo, docker.io, policykit-1, cockpit-bridge, cockpit-system, cockpit-docker packages
4 VM user account `guest` with password 'guest'
5. VM user account configured with 'sudo' & 'docker' user groups

Then: when you log in to cockpit & ask it to reuse passwords for privileged operations cockpit will not be able to gain privileges on the VM with the `guest` account.

This means the cockpit UI is rendered largely non-functional, for example things like pulling a docker image will fail with an error message even though performing the same action manually from the terminal with `docker pull` works just fine.

Redoing the configuration, but using the same account names & passwords on both host & guest 'fixes' the problem.

It looks like cockpit passes the wrong (cached) password when attempting to elevate privileges on the guest.

**Comment by petervo** [comment]
Yes, this is a known issue for now.

The difficulty here is that we try not to store passwords beyond when there are immediately needed in code that runs inside the user's session.

One possible option for this use case might be for us to have some UI that users can use to launch the privileged bridge by typing the password directly. This would also cover use cases where there is no password such as when ssh used key based authentication. That probably needs a little more thought but could be an option.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

We are sorry, but we won't be able to address this in any time soon.
If you are interested in helping us with the implementation, please comment here.
