### ISSUE TITLE
Registry console sometimes displaying project more than once, JS error

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#6712]
Cockpit version 140
Origin version v1.5.0

After changing project access permissions the registry console threw an error, displaying the project more than once. Not clear how reproducible this is.

cc @dmsimard

![screen shot 2017-05-26 at 11 09 24 am](https://cloud.githubusercontent.com/assets/1764461/26501060/5f366be6-4206-11e7-9aec-c0210278f037.png)

**Comment by petervo** [comment]
Closing as dup of #6381, please reopen if reproducible with the still unreleased openshift 1.5.1
