### ISSUE TITLE
Adding a machine with the same address but different port not allowed

### ISSUE THREAD

**Issue by MisterRager** [cockpit-project/cockpit#6719]
When I try to add another machine with the same host but different port, I get the error `This machine has already been added.`.

**Comment by petervo** [comment]
Yep, we don't allow that right now. The hostname portion of the address without the port and user is used in the url and thus has to be unique.

Do you have a real world usecase where doing this would be useful? Or was this mainly just for testing?

**Comment by MisterRager** [comment]
I've got 2 boxes at home, and I'm accessing them through the same hostname since there's only one routable IP to share between the two.

**Comment by jmakov** [comment]
A quick workaround is to add in your `.ssh/config` a new host (alias for your machine) e.g. :
```
Host my_machine_1
    Hostname IP_mach_1
    Port port_1
Host my_machine_2
    Hostname IP_mach_1
    Port port_2
```

**Comment by marusak** [comment]
It is indeed still the case. Unfortunately it is design decision that deep in Cockpit and changing it would require some significant effort.
This hasn't been acted upon for 4 years and there is simple and straight forward way of doing it.
