### ISSUE TITLE
Running image-customize resets the VM (?)

### ISSUE THREAD

**Issue by vojtechtrefny** [cockpit-project/cockpit#6843]
We are running cockpit tests with daily builds of udisks and our test runs are now failing. We might be doing something wrong, but this worked before the recent tests/bots changes.

We run `image-customize` to install newest udisks to the machine and after running this command all tests are failing because cockpit doesn't run/start.

Simple steps to reproduce:

1. `bots/image-download fedora-26`
2. `sudo test/vm-prep`
3. `bots/image-prepare fedora-26`
4. `./test/verify/check-storage-basic` --> test passes this time
5. `bots/image-customize -r "uname -a" fedora-26`
6. `./test/verify/check-storage-basic` --> test fail

```
No files found for cockpit.service.
Failed to start cockpit.socket: Unit cockpit.socket not found.
not ok 1 testBasic (__main__.TestStorage) duration: 32s
```

Are we doing something wrong or is the `image-customize` script broken?

**Comment by stefwalter** [comment]
The image-customize script probably regressed when refactoring it.

**Comment by stefwalter** [comment]
Opening a pull request for this. I tested the commands above and they work now.

Sorry for the regression :S

**Comment by vojtechtrefny** [comment]
I've tested the fix, works good. Thank you!
