### ISSUE TITLE
Question: Running services with non admin user (regular user)

### ISSUE THREAD

**Issue by ordah** [cockpit-project/cockpit#6882]
Hi,

I'm having trouble to start services with non admin user.
I'm giving a user the following sudo permission:
my_user ALL= NOPASSWD  : /bin/systemctl start my_service

From the terminal it works well but when i'm trying to start it from cockpit services
i'm getting Error: permission denied

What am i missing here?
If i give it sudo to all or adding it to wheel group it works well but I don't want
to give him that much permissions.

Please advise,
Or

**Comment by stefwalter** [comment]
systemd uses polkit to check users. Here's an example of how to make that work:

https://wiki.archlinux.org/index.php/Polkit#Allow_management_of_individual_systemd_units_by_regular_users

**Comment by ordah** [comment]
Thanks for the response.
It looks like this is what I was looking for.

For some reason the action that i'm getting is: org.freedesktop.systemd1.manage-units
but it contains only id so I can't distinguish different services.

Do you know how can i fix it?

Thank you very much

**Comment by stefwalter** [comment]
I've tried this out and it works. Documented it here: 

https://github.com/cockpit-project/cockpit/pull/6900

You need to use code like ```action.lookup("unit")```

**Comment by ordah** [comment]
Thanks for all the help.

In case some else will have the same problem as me that the action is missing fields.
It because of the systemd version, I'm working with RedHat 7 Enterprise which have systemd V219
and the unit, verb etc... properties were added in version 226.

[https://superuser.com/questions/1064616/polkit-systemd-interaction#answer-1141284](url)
