### ISSUE TITLE
VM inline console does not work from RPM package

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#6919]
So far I only tested the inline console from the PR, i. e. from the build tree, where it worked fine. But it does not work from the 142 RPM packages, at least not on Fedora 26:

![console](https://user-images.githubusercontent.com/200109/27002330-6b7e5b72-4ddf-11e7-8b23-6d50991013ea.png)

In the JS console I see:
```
ReferenceError: Util is not defined[Learn More]  vnc.html:74:9
	<anonymous> https://localhost:9090/cockpit/$fef1ceed6ff785adc70a972fff80ba1802568815/machines/vnc.html:74:9
```
Apparently the noVNC include files are missing from the webpack?

CC @mareklibra

**Comment by martinpitt** [comment]
```
sudo ln -s ~martin/upstream/cockpit/dist/machines/include /usr/share/cockpit/machines/include
```
does the trick; but I'm not sure if these files really should be shipped verbatim, or put into machines.min.js.gz / vnc.html.gz etc.?

**Comment by martinpitt** [comment]
So first and foremost this teaches us that we must cover this with a test case. When it works (with the symlink),  the console shows some messages from noVNC:
```
channel 5901  vnc.html:215:13
 Msg: noVNC ready: native WebSockets, canvas rendering  util.js:218:43
  util.js:218:43
 Msg: Starting VNC handshake
```
whereas in the failing case we should be able to at least detect the `ReferenceError`. If phantomjs can't run noVNC, then maybe we can cover this in the selenium tests.

We should also be able to do some assertions on the HTML structure inside the noVNC iframe:
```html
<iframe src="vnc.html?host=null&amp;port=-1&amp;encrypt=true&amp;true_color=1&amp;resize=true&amp;containerId=vm-sid-lxde-novnc-frame-container" class="machines-console-frame-vnc" data-container-id="vm-sid-lxde-novnc-frame-container" frameborder="0">Your browser does not support iframes.</iframe>
```
In the failing case it is almost empty, while it has plenty of stuff in the success case, particularly a `#noVNC_status_bar` and the "Connected" message in `#noVNC_status`:
```html
<div id="noVNC_container" class="vnc-custom-container">
        <div id="noVNC_status_bar" class="noVNC_status_normal">
            <table width="100%" border="0">
                <tbody><tr>
                    <td>
                        <div id="noVNC_status" class="vnc-custom-status-bar">Connected (encrypted) to: QEMU (sid-lxde)</div>
                    </td>
                </tr>
            </tbody></table>
        </div>

        <canvas id="noVNC_canvas" width="1024" height="768" tabindex="0" style="width: 1024px; height: 768px; cursor: url(&quot;data:image/x-icon;base64,AAACAAEAQEA[...]) 4 4, default;">
           Canvas not supported.
        </canvas>
    </div>
```

**Comment by mareklibra** [comment]
@martinpitt , the noVNC's `include` dir must be distributed as it is (with some exception for keysymdef.js, which needs either preprocessing or exception in tools/check-dist). 
I checked at some development phase, the directory was properly copied-through to rpm.

Anyway, recently is not. I need to have a look. Or do you have a hint why? The `dist` directory contains it.

**Comment by mareklibra** [comment]
I can't see node_modules/noVNC in .tar.gz.
The noVNC is properly listed in `dependencies` of package.json

**Comment by stefwalter** [comment]
@martinpitt noVNC either needs webpack static linking using ```require()``` ... or needs t obe listed in files section of webpack.config.js to be distributed as independent files

**Comment by mareklibra** [comment]
@stefwalter , `info.files` in webpack.config.js already contains noVNC files (dynamically added, see line 270).

IIUC, content of node_modules in .tar.gz depends on output of tools/webpack-make . Is there a way to force-include the noVNC ?
The `require()` is an option but there's no need for it from code-perspective.

**Comment by martinpitt** [comment]
I'm really stumped now. This succeeds:
```py
            b.wait_present("iframe.machines-console-frame-vnc")
            b.switch_to_frame("vm-subVmTest1-novnc-frame-container")
            import time
            for i in range(10):
                time.sleep(1)
                b.wait_checkpoint()
            b.snapshot('checkpoint')
            print("----- b.text")
            print(b.text("html"))
            b.wait_present("#vnc-main-menu")
```
I. e. with just waiting for 10s and calling `wait_checkpoint()` in between, the `b.text()` shows me the correct noVNC frame content, and the `wait_present()` succeeds. However, if I move the printing of `b.text` *into* the polling loop, it is always the empty string and the `wait_present` fails too. It is as if calling `.text()` or `.wait_present()` or similar "poisons" something in phantomjs or creates a cache that doesn't get updated any more after the first assertion (but `.snapshot()`  gives the correct frame content in any case!). I. e. I can't currently find a suitable waiting condition.

**Comment by martinpitt** [comment]
I worked around that `wait_present()` bug and now I [have a test case](https://github.com/martinpitt/cockpit/commit/76ff9a722ef17c3607d0434a4d6930124ee05774) that fails with our current images and succeeds when I install the `/include/*` bits into the test VM.

**Comment by mareklibra** [comment]
I'm working on that. I've probably a solution in fake `require()`, but currently testing it

**Comment by martinpitt** [comment]
Indeed the dist tarball contains the include dir (also the officially released 142 one), and so does a `make install` from the build tree. But quite obviously the built rpms and [debs](https://packages.debian.org/sid/all/cockpit-machines/filelist) don't, also for a local `tools/make-rpms`. So I'm not sure how a `require()` would help - it seems this is some difference in behaviour when running `make install` from git vs. from the disted tarball?

**Comment by mareklibra** [comment]
yes, `tools/webpack-make` is involved - files under node_modules must be referenced to be included in node_modules of .tar.gz

**Comment by martinpitt** [comment]
I think I understand this a bit better now: `machinesinclude_DATA` tries to install the files from node_modules/noVNC/include, but our `EXTRA_DIST` rule moves them from there to `dist/machines/include` (via the `sed`). We need to make up our mind whether we want to dist/install them from node_modules/ or dist. I think the former would be less confusing and more consistent, what do you think?

**Comment by mareklibra** [comment]
Build is being fixed here: https://github.com/cockpit-project/cockpit/pull/6922
