### ISSUE TITLE
machines: scroll when console is activated, if VM console is partially offscreen

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#6939]
In the Virtual Machines page, when the "console" tab is activated, the display can be partially offscreen. You can see this in the video demo at http://cockpit-project.org/blog/cockpit-142.html

To make the virtual console more immediately useful, I would suggest that the page scrolls up to accommodate the entire remote screen, if possible. If the console screen is already viewable in the page's viewport, then do nothing. (Also, take into account that the VM screen might be larger than the viewport.)

It might be useful to use https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView or do a bit more calculation and use https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll (IIRC, `scrollIntoView()` might be a little buggy).

(Minor polishing related to PR #5932)

**Comment by martinpitt** [comment]
CC @mareklibra
