### ISSUE TITLE
machines: minor text alignment optimization

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#6940]
The text under "More information" looks correct in a "typical" browser width.

![image](https://user-images.githubusercontent.com/10246/27134373-a4eaba98-5115-11e7-952b-c3bbcccebee4.png)

However, in this extract from the video, you can see the browser is quite wide and the text looks odd. There should be a `max-width` constraint based on character size (`em` units) and the text block, while left-aligned, would be aligned to the center (probably with a `margin: auto;` on the left and right sides), like the rest of the elements.

![screenshot from 2017-06-14 15-19-17-or8](https://user-images.githubusercontent.com/10246/27134534-29ea8764-5116-11e7-9500-347292e73d51.png)

This isn't a critical fix, but it would be nice to ensure it looks a little better when the browser is wider.

(This is minor polishing related to PR #5932)

**Comment by mareklibra** [comment]
CC @mareklibra
