### ISSUE TITLE
Authentication Dialog does not show automatically loaded keys correctly as being loaded

### ISSUE THREAD

**Issue by vinzenz** [cockpit-project/cockpit#6997]
When logging into the Cockpit UI and navigating to the Authentication Dialog I am getting represented with this:
![Authentication Dialog](https://dl.dropboxusercontent.com/s/msslxa9ccpmqlyk/Screenshot%202017-06-19%2008.10.17.png)

Which would indicate that I would still have to unlock this key, however when going to the terminal and check what keys are loaded by running `ssh-add -L` I can see that the key is already unlocked

![ssh-agent -L](https://dl.dropboxusercontent.com/s/hfwgmsjm4kv0chc/Screenshot%202017-06-19%2008.10.27.png)

Also when clicking on the 'ON' switch in the Authentication dialog, nothing seems to happen the first time (because I actually unload the key) and when clicking again it offers me to unlock the key

From that time on it's behaving correctly however it is a very confusing user experience

**Comment by petervo** [comment]
Did you try with latest master? I think think the layout fixes make this a little clearer.

**Comment by stefwalter** [comment]
No reply from @vinzenz ... closing the issue.
