### ISSUE TITLE
content-security-policy parsing is sensitive to whitespace

### ISSUE THREAD

**Issue by deryni** [cockpit-project/cockpit#7005]
Using a value of `"content-security-policy": "img-src: 'self' data:; default-src 'self'"` in a `manifest.json` file will cause cockpit to append the default value to the CSP header and cause the browser (at least chrome) to throw a warning about a duplicated `default-src` directive.

The issue is that the prefix matching in [`src/common/cockpitwebresponse.c`](https://github.com/cockpit-project/cockpit/blob/master/src/common/cockpitwebresponse.c#L1818) doesn't take leading spaces into account.

Using a value of `"content-security-policy": "img-src: 'self' data:;default-src 'self'"`, etc. will work correctly as a workaround though.

**Comment by stefwalter** [comment]
Good catch. Are you able to post a pull request that fixes the issue?

**Comment by deryni** [comment]
That was my first thought. I just wasn't sure what the correct scope for the fix would be (I'm not sure exactly what the parsing rules for that header are or should be, etc.) and my C/glib is a bit rusty so wasn't sure what the right approach to fixing it would be.

Is the right approach to modify `strv_have_prefix` to advance the `strv[i]` pointer past any leading whitespace before passing it to `g_str_has_prefix`?

**Comment by petervo** [comment]
That seems sane to me
