### ISSUE TITLE
subscriptions: when registering to foreman or satellite-6 the environment is required when not using an activation key

### ISSUE THREAD

**Issue by thomasmckay** [cockpit-project/cockpit#7007]
The environment parameter is necessary when registering to foreman w/ katello or satellite-6 unless using an activation key. The UI should provide a field for this (defaulting to "Library").

**Comment by martinpitt** [comment]
The Subscriptions page is maintained in the [subscription-manager project](https://github.com/candlepin/subscription-manager) now.
