### ISSUE TITLE
Possibility to switch out branding

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#702]
We should make it as easy as possible to switch out the (small amounts of) Cockpit branding.
This came up when we discussed how to integrate with Fedora specifically, but probably applies to other cases as well.
This applies to:
* Favicon
* Log in screen
* Product name in the top left corner
* About in top right corner menu.

**Comment by dperpeet** [comment]
@andreasn does our recent change to cockpit cover enough of this?

**Comment by stefwalter** [comment]
Done.
