### ISSUE TITLE
Diagnostic reports - inconsistent heading capitalization the in sidebar

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#7023]
"Diagnostic reports" in the sidebar is using "Sentence case", but all the others are using "Headline Case"
http://www.patternfly.org/styles/terminology-and-wording/

![screenshot from 2017-06-20 11-10-30](https://user-images.githubusercontent.com/209895/27325645-65d0f6e0-55a9-11e7-9333-e976a3218373.png)

**Comment by martinpitt** [comment]
kdump too apparently? This looks like a nice warm-up exercise for Thomas.

**Comment by martinpitt** [comment]
Nevermind, kdump is issue #7024.
