### ISSUE TITLE
Software Updates: Confusing labels

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#7062]
The table label currently says "Available packages", which confused some participants during the usability testing. We should better call this "Available Updates" perhaps?

During applying, PackageKit has a state `PK_STATUS_ENUM_CLEANUP` which we currently show as "Cleaning up...". That's a bit confusing as it takes some time and is really about running the postinst script. Debian calls this "Configuring...", so renaming it to that or "Setting up.." might be nicer?

CC @garrett

**Comment by garrett** [comment]
I agree on the "Available Updates" label. It sounds good to me.

**Comment by martinpitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OS updates: reboot required detection](https://trello.com/c/8F1d2nOk/517-os-updates-reboot-required-detection)
