### ISSUE TITLE
Software Updates: Reboot after update

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#7065]
Until/unless we have a proper "reboot required" detection (which only really reliably works on Ubuntu), we should always recommend to reboot the server after applying updates.

This is mostly not needed on Debians as services get auto-restarted on package updates, but this demonstrably does not happen at least in Fedora (obvserved with updating ssh). There is "tracer", but it's not installed by default. So let's err on the safe side for now.

This is already designed in the [spec mockups](https://github.com/cockpit-project/cockpit/wiki/Feature:-System-Updates-for-dnf,-yum,-apt-hosts).

CC @andreasn, @garrett

**Comment by martinpitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OS updates: reboot required detection](https://trello.com/c/8F1d2nOk/517-os-updates-reboot-required-detection)

**Comment by martinpitt** [comment]
@garrett: As long as we can't tell and just always do it - what do you think about toning down the "Restart Required" message to something like "Restart Recommended" - "Upgrades may require a restart to take effect"?

**Comment by martinpitt** [comment]
Oh, and should we add a non-default "Later" button that gets you back to the index page? So that folks who only install security updates can still see the others? Otherwise you are stuck on that page in that state.

**Comment by garrett** [comment]
I've updated the mockup. Here's the image as of the latest commit:

![update mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/1e09788c506c1ac8bd8f55fcb50a6c618e31bc3e/software-updates/software-updates-packages-progress.png)

And here's a crop of the relevant area:

![image](https://user-images.githubusercontent.com/10246/27392115-1360326a-56a6-11e7-9d3c-d71585891f2c.png)

Clicking the "Ignore" button ignores the recommendation and the page returns to the standard updates view. (Of course, it would have a summary of what was upgraded as well... but that's for another mockup.) One thing to note is that it should probably _not_ say the computer is up to date — but perhaps be a weird updates-applied state — importantly without a OK checkmark?

Clicking restart will reboot the computer with a progress spinner. When it reconnects, the page will change to the computer-is-updated mode with the list of changes.

**Comment by garrett** [comment]
@martinpitt: Should we actually have a list of updated packages here, so that an informed decision can be made? (I'm thinking yes.)

**Comment by martinpitt** [comment]
Once we have that component, sure! We can show it both here and in "all up to date" state.
