### ISSUE TITLE
Topology select object view doesn't display

### ISSUE THREAD

**Issue by ajmulhollan1** [cockpit-project/cockpit#7074]
Hello,

Apologies if I've not logged the issue correctly but I've launched Cockpit inside of Kubernetes pod and a couple of months ago when I first did this, in topology view - you could click each item be it a pod, RC, Service or Node and it would display information about that item on the right.

My view is as below, is this an issue/bug or something wrong with my setup?

<img width="1438" alt="screen shot 2017-06-22 at 09 22 05" src="https://user-images.githubusercontent.com/8045504/27424276-68e8e4b2-572c-11e7-97c8-8fad4244e2ee.png">

Thanks

**Comment by amitkshirsagar13** [comment]
Same thing happening with me... were you able to fix this somehow?

**Comment by ajmulhollan1** [comment]
I'm afraid not, however I found a desktop client, which allows you to see quite a bit which works as an alternative for now.

https://kubernetic.com/

The topology view was quite handy though, as we could leave it on a touch screen throughout the day, and click on resources as and when needed. Now its almost pointless.

**Comment by petervo** [comment]
This was fixed in #7516 and should be available in the next release
