### ISSUE TITLE
Check cleanup of partial logical volumes.

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#71]
If a logical volume is inactive, it does not keep the physical volumes that it is stored on "busy". Wiping such a physical volume will probably create a partial logical volume that can not be activated but we should still be able to cleanup fstab etc when the partial logical volume is ultimately deleted. Check this.

Also check what happens when the _last_ physical volume of a volume group disappears in this way. The VG will be removed completely and we have no chance to cleanup fstab.

**Comment by mvollmer** [comment]
Cockpit now has better "in-use" checks tat should prevent this scenario.
