### ISSUE TITLE
"Disconnected" page is not centered

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#7106]
Spotted in #7101:

![reboot-disconnect](https://user-images.githubusercontent.com/200109/27474534-b4d30b56-5802-11e7-95e1-9db6683a1270.png)

It doesn't catch the eye much on wide screens, but it is noticeable there too.

**Comment by willcodes** [comment]
hi, thought I would take a stab at this as a first timer - wasn't sure where to reproduce though. Is this still an issue?

**Comment by martinpitt** [comment]
@willcodes: Yes, it is still an issue. How to reproduce:

 * Log into cockpit
 * Make your browser relatively narrow, so that you better see the effect.
 * Run `sudo systemctl stop cockpit` in a terminal.
