### ISSUE TITLE
Automatically detect "Reconnect" on "Disconnected" page

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#7111]
Cockpit can disconnect for various reasons: explicitly (triggering a reboot from systemd, packagekit, or ostree) or implicitly (network error, cockpit crash). In these cases we show this screen:

![reboot-disconnect](https://user-images.githubusercontent.com/200109/27474534-b4d30b56-5802-11e7-95e1-9db6683a1270.png)

It's unfriendly to let the user poll on the "Reconnect" button, we can determine this automatically in a polling loop (possibly with linearly or exponentially increasing intervals).

**Comment by marusak** [comment]
Bee reported again in #14724
