### ISSUE TITLE
requires glib-networking

### ISSUE THREAD

**Issue by cgwalters** [cockpit-project/cockpit#7135]
`cockpit-ws` is the last thing in current Fedora Atomic Host that requires `glib-networking`, since [NetworkManager switched to libcurl](http://pkgs.fedoraproject.org/cgit/rpms/NetworkManager.git/commit/?id=a486a68256760912d7daf5b04dbd201a2a51491d) and [so did libostree](http://pkgs.fedoraproject.org/cgit/rpms/ostree.git/commit/?id=115e0f5703f92f335ee5b5eb8265721d77adaaaf).

**Comment by stefwalter** [comment]
Good to know. I'd like to switch to use gnutls or openssl directly, and drop the glib-networking dependency.

**Comment by petervo** [comment]
Just for the record cockpit-bridge depends on glib-networking as well. That's probably the bigger issue as cockpit-ws is only delivered in a container.

**Comment by martinpitt** [comment]
We are making slow progress here. cockpit-tls has mostly taken over TLS termination from ws, and doesn't require glib{,-networking}, and at some point we want to drop TLS support from cockpit-ws.

However, as pointed out above, the bigger part here is cockpit-bridge. That is a heavy user of glib and gio, and changing glib-networking to a custom implementation that essentially just does the same thing (with more bugs) is IMHO not really helpful. So I close this for now.
