### ISSUE TITLE
Virtual Machines: State is inconsistent with other pages in Cockpit

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#7140]
This is like the tiniest little issue, but I thought I should file it regardless.
Everywhere else in Cockpit we use only the label for the state (see Containers page, Services page etc), and no icon for the states. I think it would make sense to have it look consistent across pages.

So therefore I would suggest to express the state only with a string. The icon doesn't add any additional information.

**Comment by andreasn** [comment]
@mareklibra - what do you think?

**Comment by mareklibra** [comment]
No problem from my side, I can push a patch removing the icons.

@andreasn , @garrett , What about other UI improvements like those proposed later within https://github.com/cockpit-project/cockpit/pull/6565 ?

Namely:
- VM-related error message (sort of "an action failed for the VM") - recently a message on the Overview subtab
- highlighting particular VM with such an error message - recently a warning-triangle in front of the VM name
- replacement of action buttons by icons
