### ISSUE TITLE
Hard to tell if terminal has keyboard focus

### ISSUE THREAD

**Issue by da2x** [cockpit-project/cockpit#7143]
The input cursor blinks in the terminal regardless of whether it has keyboard focus or not. You have to click in the terminal to give it focus before you can start typing.

E.g. when you switch from one machine to another using the machine drop-down selection in the top left corner, and then keyboard focus is lost from the terminal. The blinking input cursor indicates that it’s ready to accept keyboard input, and there is nothing else on screen that visibly has keyboard access.

Clicking outside the terminal (anywhere else on the page) also triggers the same problem.

Please paint a blue focus rung around the terminal or something to indicate that it has keyboard focus.

**Comment by andreasn** [comment]
This is what GNOME Terminal does when it doesn't have focus:
![screenshot from 2017-07-06 17-47-04](https://user-images.githubusercontent.com/209895/27919924-4ed6112e-6273-11e7-9465-1a1d05464863.png)

**Comment by da2x** [comment]
(The input cursor in GNOME Terminal is normally solid and blinking, but its not solid and not blinking when window doesn't have focus.)

**Comment by garrett** [comment]
Don't forget to set the window focus/blur events too, in case someone switches windows or tabs.

(It should set/remove the same class on the terminal widget, so it's styled similarly.)

**Comment by larskarlitski** [comment]
Pull request #7983 changes this to the same style as gnome terminal: solid and blinking when in focus and a static empty rectangle when out of focus. Please have a look!
