### ISSUE TITLE
cluster nodes usage stat chart not intuitive to read

### ISSUE THREAD

**Issue by thomasmckay** [cockpit-project/cockpit#7145]
![cluster cockpit example com](https://user-images.githubusercontent.com/338096/27702010-a1de6f90-5cd0-11e7-892b-dbd49e3d8504.png)

This chart, in my opinion, is difficult to understand. The square is color coded for a range of resource usage (cpu, memory, disk). The user must look at the color, then match it up to the scale below it. In the same space, three donut graphs could be displayed that are immediately and intuitively understandable.

**Comment by petervo** [comment]
It's one square per node. One pie graph per node might be a bit confusing. @andreasn thoughts?

**Comment by andreasn** [comment]
This is how the design looks:
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/kubernetes/node-view.png)

It's using the heatmap data visualization pattern from Patternfly
http://www.patternfly.org/pattern-library/data-visualization/heat-map/

The idea was that while you'll need to do some matching the first time you see it, the colors would have enough context from elsewhere (traffic lights, warning sings etc.), and they would be learn-able enough that you'll be able to read it on a glance in the future. It will also give you the information on hover.

I did a quick mockup with using pie-charts, and while it can show you more precise information when you have just a few nodes, it scales very badly unfortunately. So at least for the case where you have +20 nodes, we'll have to rely on hover for that info.
![screenshot from 2017-07-05 17-13-17](https://user-images.githubusercontent.com/209895/27871312-93726838-61a5-11e7-844f-d81ed5479f88.png)

**Comment by thomasmckay** [comment]
Oh! I didn't realize it was per node. I like the squares in the context of multiple nodes. Closing this issue.

**Comment by andreasn** [comment]
No worries, better to file than to not file issues you run into!
