### ISSUE TITLE
less dramatic error case for misspellings

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#7157]
Making this a followup to #7153 since I don't think it's worth blocking on.

> Showed it briefly to @fabianapsimoes and her feedback was that it worked great, but that the error when you mistype a path was a bit too intense, but we can solve that as a followup issue.

Here is an updated design for the error case. No icon and regular text instead of bold.
![custom-ssh-keys](https://user-images.githubusercontent.com/209895/27836232-d1256c42-60de-11e7-884d-7a68dbefea18.png)

**Comment by petervo** [comment]
Addressed in PR
