### ISSUE TITLE
Failing to serve large files

### ISSUE THREAD

**Issue by fthiery** [cockpit-project/cockpit#7162]
Hello

I am trying to serve large files (in my case, a 5 GB video file); the file is located in the user folder (~/.local/share/cockpit/publish/media); serving small files works but apparently not big ones.

When trying to get the large file, here's what the journal is saying:
```
cockpit-bridge[1054]: 0:11945: http://packages/publish/media/20170705-100856-4269/2160p.mp4: received invalid HTTP chunk data
cockpit-ws[1044]: /publish/media/20170705-100856-4269/2160p.mp4: failure while serving external channel: protocol-error
```
I understand that serving large files is probably out of scope for cockpit but
* is it planned to support file streaming ?
* is it rather advised to use a frontal web server to serve static files instead ?

Thanks

**Comment by petervo** [comment]
Have you tried running with debug on ```G_MESSAGES_DEBUG=all```? I'd be interested to see what it is tripping up on.

**Comment by fthiery** [comment]
Out of memory errors -- sounds logical !

```
cockpit-bridge[692]: http://packages/publish/media/20170705-143652-b5f6/1920p.mp4: read 1024 bytes
cockpit-bridge[692]: http://packages/publish/media/20170705-143652-b5f6/1920p.mp4: read 1024 bytes
cockpit-bridge[692]: date: couldn't run date: Le clonage a échoué (Ne peut allouer de la mémoire)
cockpit-bridge[692]: cat: couldn't run cat: Le clonage a échoué (Ne peut allouer de la mémoire)
cockpit-bridge[692]: grep: couldn't run grep: Le clonage a échoué (Ne peut allouer de la mémoire)
cockpit-bridge[692]: grep: couldn't run grep: Le clonage a échoué (Ne peut allouer de la mémoire)
cockpit-bridge[692]: hostname: couldn't run hostname: Le clonage a échoué (Ne peut allouer de la mémoire)
systemd-journald[164]: Suppressed 1528601 messages from /system.slice/cockpit.service
juil. 05 16:39:19
cockpit-ws[686]: /cockpit/@localhost/publish/media/20170705-143652-b5f6/1920p.mp4: ignoring queued block after failure
cockpit-bridge[692]: stdio: wrote 10 bytes
...
```

**Comment by fthiery** [comment]
Basically cockpit seems to read the whole 5GB file in memory -- and essentially die. I can't reproduce exactly my initial case, but in any case large file handling is not very practical; it's even dangerous, and maybe it would be better to cap it (if no optimization is provided) instead of trying to read 5GB of data at once...

**Comment by fthiery** [comment]
What are your thoughts ? Should cockpit refuse reading files larger than e.g. 100 MB or should it support streaming files (with range requests support) ?

I think that for now i will have to use nginx as frontend, but then resources are not authenticated anymore.

**Comment by petervo** [comment]
Thanks for the logs, makes sense. I'm not sure we want to go down the road of fully supporting range requests. I'd be in favor of having a cap at least for now. @stefwalter thoughts?

**Comment by stefwalter** [comment]
There's nothing in the Cockpit protocol that prevents us from just streaming the bytes. I think this should be fixed in cockpit-bridge.
