### ISSUE TITLE
Hard to visually distinguish the different security updates from each other

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#7170]
There are no lines between the different items.
It seems there are lines between the regular update items.

![screenshot from 2017-07-07 12-01-36](https://user-images.githubusercontent.com/209895/27953471-30569acc-630c-11e7-978d-cb713456afd7.png)

**Comment by andreasn** [comment]
It seems they have lines between them in the wireframes:
![wireframe](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/software-updates/software-updates-packages-merged.png)

**Comment by martinpitt** [comment]
The lines do exist (I see them on my monitor), but indeed they are very faint. I suppose we should make them a bit darker and perhaps thicker for the security updates?

**Comment by andreasn** [comment]
Oh, I see the lines now. Since they are color: #f1f1f1, the contrast between that and the red background color is too small.
In the wireframes, the security updates uses #fceded for the top and bottom lines of a security update.

**Comment by martinpitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Software Updates: upgrade log, layout, RHEL registration](https://trello.com/c/w0weB970/534-software-updates-upgrade-log-layout-rhel-registration)

**Comment by martinpitt** [comment]
#fceded is completely invisible against our #fbf0f0 background. How about #e0e0e0? That doesn't look too strong (at least on my monitor) and is still clearly distinguishable:

![security-border](https://user-images.githubusercontent.com/200109/28156521-6790c462-67b3-11e7-8ff9-a8e4eb5cb393.png)

I staged that in https://github.com/martinpitt/cockpit/commit/974df8d0fdbc43b2d49a1aafed74656f837471c1 .
