### ISSUE TITLE
Software Updates: some updates lines are very long

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#7171]
The design shows one or two lines per update, but reality is not so kind :)
The items sometimes gets very tall. This makes it harder to scan the entire list.

Due to many bugs:
![screenshot from 2017-07-07 12-09-21](https://user-images.githubusercontent.com/209895/27953717-22ffb934-630d-11e7-9cab-06d83af8ea1b.png)

Due to very big changelog:
![screenshot from 2017-07-07 12-10-49](https://user-images.githubusercontent.com/209895/27953847-a4fad0c2-630d-11e7-8947-9d20a76aebe9.png)

Due to grouping of many items:
![screenshot from 2017-07-07 12-13-38](https://user-images.githubusercontent.com/209895/27953879-c93aa1a6-630d-11e7-81b1-e3b7e0918988.png)

**Comment by martinpitt** [comment]
See: http://garrettlesage.com/cockpit-mockweb/updates/available and http://garrettlesage.com/cockpit-mockweb/updates/expand

**Comment by garrett** [comment]
I tweaked the mockups a bit more and pushed just a couple minutes ago. I had extra CSS in them that was breaking things when narrow and fixed a few other minor things. I think they should be good for reference now.

The CSS will need to be changed. (Ideally, remove all `!important` when you can... and some of the classnames should also be changed. In addition, the table stuff should probably only apply for software updates too. The JS is jQuery and would need to be ported. It's straightforward and there are comments as well.)

**Comment by martinpitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Software Updates: upgrade log, layout, RHEL registration](https://trello.com/c/w0weB970/534-software-updates-upgrade-log-layout-rhel-registration)

**Comment by martinpitt** [comment]
For reference, this is how my mock updates look like in width 1280. The entry with many binary packages totally dominates the screen width, and the entry below with lots of changes gets squeezed together.

![master-1280](https://user-images.githubusercontent.com/200109/28210494-fc0191d2-6897-11e7-829a-adc3f6bd74f0.png)

It gets a little more equalized at 640px (half of my laptop screen width), but overall it's really hard to read. I didn't bother doing a screenshot.

With @garret's CSS changes it looks a lot more balanced at 1280:

![this-1280](https://user-images.githubusercontent.com/200109/28210671-d78c2622-6898-11e7-8295-ebf7ca3ab6a4.png)

At 640px it now nicely folds into just a single column with vertically stacked information:

![this-640](https://user-images.githubusercontent.com/200109/28210689-e9902c9c-6898-11e7-83a0-705222f7b4b8.png)

Only at an "in between" width of ~ 900 px the first column is still too wide:

![this-900](https://user-images.githubusercontent.com/200109/28210714-05c061ac-6899-11e7-8a12-02b07df1837f.png)

I tried a naïve fix with
```css
@media screen and (min-width: 800px) and (max-width: 1400px) {
    .listing-ct-item th {
        min-width: 20%;
        max-width: 40%;
    }
[...]
```
but that doesn't have any effect. But still, this is already a *lot* better than what we have now.

**Comment by martinpitt** [comment]
I now also implemented the truncation. I didn't use CSS for this after all, as with React I need to keep the expanded-ness as React state anyway, so the code can just as well render the list right as it should appear. But the effect is the same. Rows are expanded by clicking anywhere in the truncated text or the link.

1280px:

![updates-expander](https://user-images.githubusercontent.com/200109/28217533-b47b1e8c-68b5-11e7-8fc6-6c44b729c758.png)

640px:

![updates-expander-narrow](https://user-images.githubusercontent.com/200109/28217534-b53fa798-68b5-11e7-89eb-a8280ad9acbc.png)

**Comment by martinpitt** [comment]
PR #7264 includes these. The screenshots from above match the PR.

**Comment by martinpitt** [comment]
Better screenshot for the release notes:

![updates-narrow](https://user-images.githubusercontent.com/200109/28453848-3785aafc-6df9-11e7-98ad-cf4f375ba8d1.png)
