### ISSUE TITLE
Support z and Z flags when mounting Docker volumes

### ISSUE THREAD

**Issue by mjmg** [cockpit-project/cockpit#7181]
Mounting docker volumes with z and Z flags have long been implemented in docker since docker 1.7
<http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/>

As cockpit is primarily developed for Red Hat based distributions with SELINUX in enforcing mode, I'm surprised the only options when mounting docker volumes under cockpit are Default, ReadWrite and ReadOnly without any z or Z flags available.

**Comment by stefwalter** [comment]
@mjmg That does sound like an oversight. Are you interested in adding this feature?

It looks like this code would need to be changed:

```
$ git grep ReadWrite pkg/docker/
pkg/docker/index.html:            <li><a translatable="yes">ReadWrite</a></li>
pkg/docker/run.js:                    case 'ReadWrite':
```

Keep in mind that Cockpit is included in Debian, Ubuntu, and other distros as well. But point taken ...

**Comment by mjmg** [comment]
@stefwalter I wish I could but I have other codings to prioritize. Let's park this request if someone is willing to pick it up.


To take care of Debian and friends, the options would have to be:

- Default

- ReadWrite

- ReadWrite,Z

- ReadWrite,z

- ReadOnly

- ReadOnly,Z

- ReadOnly,z


From <https://docs.docker.com/engine/tutorials/dockervolumes/#volume-labels>

### Volume labels

Labeling systems like SELinux require that proper labels are placed on volume content mounted into a container. Without a label, the security system might prevent the processes running inside the container from using the content. By default, Docker does not change the labels set by the OS.

To change a label in the container context, you can add either of two suffixes :z or :Z to the volume mount. These suffixes tell Docker to relabel file objects on the shared volumes. The z option tells Docker that two containers share the volume content. As a result, Docker labels the content with a shared content label. Shared volume labels allow all containers to read/write content. The Z option tells Docker to label the content with a private unshared label. Only the current container can use a private volume.

**Comment by Gundersanne** [comment]
Closing this issue because the Docker plugin is not being actively developed any longer.
Replacement should be https://github.com/cockpit-project/cockpit-podman/ so any RFEs should be opened on that repository.
