### ISSUE TITLE
Monitor/Alert for hdd

### ISSUE THREAD

**Issue by Fredrik81** [cockpit-project/cockpit#7182]
Would be great if the storage part in cockpit could have monitoring and alert functionality based on smarttools/smartd.
To be able to show if errors have occurred for a drive.
Perhaps by showing the log entries in combination to a status icon.

**Comment by stefwalter** [comment]
@Fredrik81 Yes indeed. That would be very useful. Are you interested in working on this feature?

**Comment by martinpitt** [comment]
Duplicate of #1134
