### ISSUE TITLE
Support for nvidia-docker when creating/running docker containers on hosts with NVIDIA GPU

### ISSUE THREAD

**Issue by mjmg** [cockpit-project/cockpit#7183]
nvidia-docker is a thin wrapper on top of docker and act as a drop-in replacement for the docker command line interface to enable access to the docker host NVIDIA GPU.

https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker

As I am using nvidia-docker extensively, such support within cockpit will simplify management, creation and running of docker containers with access to the underlying GPU for CUDA accelerated computing without resorting to the long command below for each docker command:

```
# Running nvidia-docker with a custom docker command
NV_DOCKER='sudo docker -D' nvidia-docker <docker-options> <docker-command> <docker-args>
```

**Comment by stefwalter** [comment]
Are you interested in working on this feature?

**Comment by mjmg** [comment]
@stefwalter my background on web programming is not that extensive so I might pass for the meantime. Parking this request for reference so someone might pick it up.

**Comment by stefwalter** [comment]
It might be worth posting to this mailing list https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/ or poking people on IRC to see if you can find someone interested in working on this.

FWIW, Cockpit doesn't use the docker command line. It uses the API: https://docs.docker.com/engine/api/  ... the same GPU and Nvidia stuff is likely available via the API, but implementing it would probably not involve ```nvidia-docker```.

**Comment by mjmg** [comment]
Closing as nvidia-docker2 was released which has a different implementation using runtimes.
