### ISSUE TITLE
Localize moment.js times

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#7197]
We are using moment.js in tons of places, but nowhere do we localize it.

The suggested way is
```
moment.locale(window.navigator.userLanguage || window.navigator.language);
```
But our "Display Language" setting doesn't affect that -- if I set that to German, `window.navigator.userLanguage` is undefined while `window.navigator.language` is `en-US`.

**Comment by stefwalter** [comment]
I think you can use  ```cockpit.language```. Last time I checked, It's not possible for webpages to affect ```window.navigator.userLanguage``` or ```window.navigator.language``` in a cross browser predictable way.

**Comment by allisonkarlitskaya** [comment]
Note that cockpit.language will contain POSIX-style strings like "pt_BR", which may not work for javascript libraries.  See also #9349.
