### ISSUE TITLE
Produce logs usable by fail2ban

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#722]
Should we choose to format our 'authentication failed' logs similar to sshd, or should we have some other useful format that is useful with tools like fail2ban.

http://www.fail2ban.org/wiki/index.php/Main_Page

**Comment by Lerenn** [comment]
It's a pretty old issue but I didn't find fail2ban/cockpit subjects on the internet...
Is it possible to make rules in fail2ban for cockpit ? (This issue being opened, I imagine that would mean 'no' but it has maybe changed).
Thanks ! :)

**Comment by FloThinksPi** [comment]
in my experience Cockpit already produces(indirectly) useable logs for fail2ban and in my case OSSEC. Cockpit tries to authenticate over sshd thus sshd is producing access denied log entrys and tools like OSSEC ban that IP completely so yea. :)

**Comment by stefwalter** [comment]
> Cockpit tries to authenticate over sshd

Good that it works. However Cockpit only authenticates over SSHD locally when using the ```atomic run cockpit/ws``` container, or when using the ```cockpit-ws --local-ssh``` option.

**Comment by Lerenn** [comment]
I don't use atomic (yet) and don't dockerize (yet) this service. However, thanks to your infos, I found what to do to make cockpit authenticate using SSH.

For those who wants to know : you have to modify the file `/usr/lib/systemd/system/cockpit.service` and add the option `--local-ssh` to the line `ExecStart=/usr/libexec/cockpit-ws` as you suggested. I ran `systemctl restart cockpit` and it works !

However, concerning fail2ban, do not forget to delete `ignore-ip = 127.0.0.1/8` to allow banishment through cockpit (cockpit connection being made locally). Therefore, if someone tries to brute force your cockpit, you won't be able to connect also...

**Comment by martinpitt** [comment]
A failed password on the cockpit login page (not using ssh) produces fairly standard logs from PAM and audit:
```
unix_chkpwd[32898]: password check failed for user (martin)
cockpit-session[32896]: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=martin
audit[32896]: USER_AUTH pid=32896 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:cockpit_session_t:s0 msg='op=PAM:authentication grantors=? acct="martin" exe="/usr/libexec/cockpit-session" hostname=? addr=? terminal=? res=failed'
```

Likewise for an unknown user:
```
cockpit-session[32905]: pam_unix(cockpit:auth): check pass; user unknown
kernel: audit: type=1100 audit(1571394598.792:207): pid=32905 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:cockpit_session_t:s0 msg='op=PAM:authentication grantors=? acct="xxx" exe="/usr/libexec/cockpit-session" hostname=? addr=? terminal=? res=failed'
audit[32905]: USER_AUTH pid=32905 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:cockpit_session_t:s0 msg='op=PAM:authentication grantors=? acct="xxx" exe="/usr/libexec/cockpit-session" hostname=? addr=? terminal=? res=failed'
```
This is good enough, we don't need to arbitrarily change any strings here.

**Comment by redochka** [comment]
@martinpitt exactly. 
For users new to fail2ban, don't forget to set `enabled = true` to the `[pam-generic]` section in your `jail.local` file

**Comment by elgholm** [comment]
Sorry for resurrecting an old topic, and perhaps I'm a bit stupid, but how am I supposed to use the auth-failed logs produced by cockpit when they do not contain any IP-address or host-name?
The only thing I see using  journalctl SYSLOG_FACILITY=10 is:
```
Mar 27 10:11:10 tor.brightly.se cockpit-session[14844]: pam_unix(cockpit:auth): check pass; user unknown --- What user? (Which is good to know for debugging)
Mar 27 10:11:10 tor.brightly.se cockpit-session[14844]: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost= --- What ip/host am I to block in fail2ban?
```
Comparing this with sshd logs:
`Mar 27 09:52:36 tor.brightly.se sshd[12061]: Failed password for elgholm from 5.178.78.215 port 14122 ssh2`
I'm on a fresh install of Oracle Linux 8, which is RHEL.

**Comment by martinpitt** [comment]
@elgholm : Indeed rhosts= is not back yet, that is tracked in https://issues.redhat.com/browse/COCKPIT-703 (internal, sorry)

**Comment by elgholm** [comment]
Ok, cool. I'll fall back to sleep then ;)
PS. ruser, whatever that is (the login-name entered I hope?), would be cool as well. Also, "rip" (remote-ip) would skip a lookup... Cheers!

**Comment by Bram-diederik** [comment]
you can enable fail2ban by creating a apache ProxyPass with an AuthType 
those rules are default in fail2ban jail 

here the apache conf settings

```
  RewriteEngine On
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule /(.*)           ws://127.0.0.1:9090/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket [NC]
  RewriteRule /(.*)           http://127.0.0.1:9090/$1 [P,L]
  <Location "/">
  ProxyPass  http://127.0.0.1:9090/
  ProxyPassReverse  http://127.0.0.1:9090/
         AuthType Basic
        AuthName "Restricted Content"
        AuthUserFile /etc/apache2/.htpasswd
        Require valid-user
  </Location>
```

**Comment by ecadagiani** [comment]
Hello, sorry to wake up this old issue. But it appears in one of the first results of google, when you search 'fail2ban with cockpit'. After trying a few times without success, i finally managed to find a solution with PAM, and i want to share it with people that might have this problem in the future.

Cockpit now share `rhost` in systemd logs. (example: `Dec 17 00:42:22 myserver cockpit-session[32634]: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=::ffff:192.168.1.17  user=eden`)

I update my `/etc/fail2ban/jail.local`, and add this:
```conf
[cockpit]

enabled  = true
banaction = %(banaction_allports)s
backend  = systemd
port     = 9090
filter   = cockpit
logpath  = /var/log/fail2ban.log
maxretry = 4
bantime = 10m
```
And create file `/etc/fail2ban/filter.d/cockpit.conf`: 
```conf
[Definition]

failregex = pam_unix\(cockpit:auth\): authentication failure; logname=.* uid=.* euid=.* tty=.* ruser=.* rhost=<HOST>
journalmatch = SYSLOG_FACILITY=10 PRIORITY=5
```

And then, restart fail2ban `systemctl restart fail2ban`

If you want to debug, you can use this commands:
```bash
journalctl -f SYSLOG_FACILITY=10 PRIORITY=5 # to see errors logs
tail -f /var/log/fail2ban.log # to see fail2ban logs
sudo systemctl status fail2ban # to see error of fail2ban server
```

**Comment by garrett** [comment]
@ecadagiani: That's neat!

I'm on PTO right now, but saw this and wanted to not forget about it, so I opened an issue to add it to our new FAQ (or a tips and tricks page), unless someone else on the team thinks it would be useful to ship an example configuration like this that would be easy to enable.

**Comment by kminek** [comment]
@ecadagiani i tested your setup and it doesnt work. i think there is an error - specifying `logpath` is not valid for `systemd` backend - according to comments in default `jail.conf`

**Comment by Ludo-code** [comment]
> @ecadagiani i tested your setup and it doesnt work. i think there is an error - specifying `logpath` is not valid for `systemd` backend - according to comments in default `jail.conf`. but i think there is even more straightforward way - just enable `pam-generic` which ships with fail2ban - in Debian its `/etc/fail2ban/jail.d/defaults-debian.conf`:
> 
> ```ini
> [sshd]
> enabled = true
> 
> [pam-generic]
> enabled = true
> ```

After  some log analyze i have see two interesting things...

The first is the solution proposed by @ecadagiani is working prooved by this : 

2023-01-13 06:52:05,765 fail2ban.filter         [15109]: INFO    [cockpit] Ignore 127.0.0.1 by ignoreself rule
2023-01-13 06:52:05,773 fail2ban.filter         [15109]: INFO    [pam-generic] Ignore 127.0.0.1 by ignoreself rule

I think the problem is more with rhost returning localhost address...

Jan 13 06:55:14 vps-e95807bf cockpit-session: pam_unix(cockpit:auth): check pass; user unknown
Jan 13 06:55:14 vps-e95807bf cockpit-session: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=::ffff:127.0.0.1

**Comment by baltazartroisville** [comment]
Please excuse me for revisiting this old topic, but there are conflicting statements here that confuse me.
Also, there is still no entry in the documentation on this topic, at least I haven't found one. 
But it is also difficult to find any information on this topic using search engines.

Some say ecadagiani's solution works well, some say it does not. Some say that adding pam-generic to the fail2ban config is enough, others say that it only works in addition to ecadagiani's solution.

I tried the following as a custom filter:

```
[Definition].
failregex = .*pam_unix\(cockpit:auth\): authentication failure.*$
```

And with the following as jail config:

```
[cockpit]
enabled = true
port = 9090
filter = cockpit
logpath = /var/log/cockpit/cockpit.log
maxretry = 3
```

But this doesn't seem to do the trick.

For almost exactly 10 years people have been trying to find a solution, maybe someone will manage to clear things up for the anniversary on June 18th 😄 

Many thanks in advance to all the people who will help here and to all those who are involved in this important project in general!

**Comment by Dark-Schneider-666** [comment]
> Hello, sorry to wake up this old issue. But it appears in one of the first results of google, when you search 'fail2ban with cockpit'. After trying a few times without success, i finally managed to find a solution with PAM, and i want to share it with people that might have this problem in the future.
> 
> Cockpit now share `rhost` in systemd logs. (example: `Dec 17 00:42:22 myserver cockpit-session[32634]: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=::ffff:192.168.1.17 user=eden`)
> 
> I update my `/etc/fail2ban/jail.local`, and add this:
> 
> ```
> [cockpit]
> 
> enabled  = true
> banaction = %(banaction_allports)s
> backend  = systemd
> port     = 9090
> filter   = cockpit
> logpath  = /var/log/fail2ban.log
> maxretry = 4
> bantime = 10m
> ```
> 
> And create file `/etc/fail2ban/filter.d/cockpit.conf`:
> 
> ```
> [Definition]
> 
> failregex = pam_unix\(cockpit:auth\): authentication failure; logname=.* uid=.* euid=.* tty=.* ruser=.* rhost=<HOST>
> journalmatch = SYSLOG_FACILITY=10 PRIORITY=5
> ```
> 
> And then, restart fail2ban `systemctl restart fail2ban`
> 
> If you want to debug, you can use this commands:
> 
> ```shell
> journalctl -f SYSLOG_FACILITY=10 PRIORITY=5 # to see errors logs
> tail -f /var/log/fail2ban.log # to see fail2ban logs
> sudo systemctl status fail2ban # to see error of fail2ban server
> ```

This is mainly the correct way for systemd systems. I'd put my config on AlmaLinux as it can be a bit tricky due to the installation of firewalld config if using the dnf installation.

**jail.local** (notice that we change the banactions to iptables if not it use firewall-cmd rich rules that doesn't work, seems not to override the open ports by the own firewalld. If you don't use firewalld to open ports, maybe it works but didn't try)
```
[DEFAULT]
banaction = iptables[type=multiport]
banaction_allports = iptables[type=allports]

[pam-generic]
enable = true
```
**jail.d/cockpit.conf**
```
[cockpit]

enabled  = true
backend  = systemd
port     = 9090
filter   = cockpit
```
**filter.d/cockpit.conf**
```
[Definition]

failregex = pam_unix\(cockpit:auth\): authentication failure; logname=.* uid=.* euid=.* tty=.* ruser=.* rhost=<HOST>
journalmatch = SYSLOG_FACILITY=10 PRIORITY=5
```
With this config is working on AlmaLinux 9.5.

**Comment by chriswayg** [comment]
> **jail.local** 
> ```
> [DEFAULT]
> banaction = iptables[type=multiport]
> banaction_allports = iptables[type=allports]
> 
> [pam-generic]
> enable = true
> ```
> 
> **jail.d/cockpit.conf**
> 
> ```
> [cockpit]
> enabled  = true
> backend  = systemd
> port     = 9090
> filter   = cockpit
> ```
> 
> **filter.d/cockpit.conf**
> ```
> [Definition]
> failregex = pam_unix\(cockpit:auth\): authentication failure; logname=.* uid=.* euid=.* tty=.* ruser=.* rhost=<HOST>
> journalmatch = SYSLOG_FACILITY=10 PRIORITY=5
> ```

I can confirm that this fail2ban config works on _Debian Bookworm_ as well with the standard Cockpit backports package and `ufw` firewall.

**Comment by BlackMoses2017** [comment]
> Hello, sorry to wake up this old issue. But it appears in one of the first results of google, when you search 'fail2ban with cockpit'. After trying a few times without success, i finally managed to find a solution with PAM, and i want to share it with people that might have this problem in the future.
> 
> Cockpit now share `rhost` in systemd logs. (example: `Dec 17 00:42:22 myserver cockpit-session[32634]: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=::ffff:192.168.1.17 user=eden`)
> 
> I update my `/etc/fail2ban/jail.local`, and add this:
> 
> ```
> [cockpit]
> 
> enabled  = true
> banaction = %(banaction_allports)s
> backend  = systemd
> port     = 9090
> filter   = cockpit
> logpath  = /var/log/fail2ban.log
> maxretry = 4
> bantime = 10m
> ```
> 
> And create file `/etc/fail2ban/filter.d/cockpit.conf`:
> 
> ```
> [Definition]
> 
> failregex = pam_unix\(cockpit:auth\): authentication failure; logname=.* uid=.* euid=.* tty=.* ruser=.* rhost=<HOST>
> journalmatch = SYSLOG_FACILITY=10 PRIORITY=5
> ```
> 
> And then, restart fail2ban `systemctl restart fail2ban`
> 
> If you want to debug, you can use this commands:
> 
> journalctl -f SYSLOG_FACILITY=10 PRIORITY=5 # to see errors logs
> tail -f /var/log/fail2ban.log # to see fail2ban logs
> sudo systemctl status fail2ban # to see error of fail2ban server

**### Thanks a looooot 
I appreciate it greatly** 🥇
