### ISSUE TITLE
Install cockpit on debian 9.0

### ISSUE THREAD

**Issue by hip3ri0n** [cockpit-project/cockpit#7259]
Hi i'm trying to install cockpit under debian 9.0 from cockpit repo but fails on configure

First time:

> configure: error: Couldn't find pcp headers (perhaps --disable-pcp)

And second time:

> configure: error: the xsltproc command was not found (perhaps --disable-doc)

So you need to pass that options to 
`./autogen.sh` --disable-pcp --disable-doc

¿That's a bug?

**Comment by stefwalter** [comment]
@martinpitt No it's not a bug, Debian doesn't have those necessary PCP requirements. You'll need to opt out in that manner.

**Comment by martinpitt** [comment]
You can leave the docs enabled, just `sudo apt install xsltproc`. You might have some more missing build dependencies, see https://github.com/cockpit-project/cockpit/blob/master/tools/debian/control .

PCP indeed isn't available in Debian 9, so `./configure --disable-pcp`.
