### ISSUE TITLE
testInternal (check_metrics.TestMetrics) is broken

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#7318]
This often times out on our internal infra:
```
# testInternal (check_metrics.TestMetrics)
#
Measured CPU 97.7805769434
Measured Memory 5565767682
not ok 113 testInternal (check_metrics.TestMetrics) duration: 126s
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-metrics", line 151, in testInternal
    self.check_host_metrics()
  File "/build/cockpit/bots/../test/verify/check-metrics", line 130, in check_host_metrics
    b.wait_js_func("ph_flot_data_plateau", "#server_network_traffic_graph", 300*1000, None, 5, "net io");
  File "/build/cockpit/test/common/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 821, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 847, in _invoke
    raise Error(res['error'])
Error: timeout
```

Needless to say that the failure isn't reproducible locally, I've ran it many dozen times in a loop.

Examples:
 - https://fedorapeople.org/groups/cockpit/logs/pull-7264-20170718-135757-fb7d0b7d-verify-rhel-atomic/log.html#113
 - https://fedorapeople.org/groups/cockpit/logs/pull-7265-20170718-134747-0789fcfe-verify-rhel-atomic/log.html#120
 - https://fedorapeople.org/groups/cockpit/logs/pull-7264-20170718-144646-fb7d0b7d-verify-rhel-atomic/log.html#14

This is failing

    b.wait_js_func("ph_flot_data_plateau", "#server_network_traffic_graph", 300*1000, None, 5, "net io");

In both cases, the screenshot shows that there is a single large network traffic spike (1.5 to 2 MBps) a while ago, and otherwise by and large calm. This is simply not enough traffic to get over the 0.3 Mbps average that it expects. So either it's not picking up traffic correctly, or the traffic-generating command

       net_pid = m.spawn("ssh -o StrictHostKeyChecking=no -i /var/tmp/{1} {0} cat /dev/zero >/dev/null".format("172.27.0.15", os.path.basename(identity)), "load-net.log")

isn't actually working.

**Comment by martinpitt** [comment]
Locally, when I `sit()` right after the `ssh cat` and log in, I get a nice 3.2 GBps traffic plateau.

**Comment by martinpitt** [comment]
I filed #7319 to get some useful debug output if the test fails.

**Comment by martinpitt** [comment]
With the debugging in #7319, locally I get numbers like this:
```
Measured CPU 98.0050770074
Measured Memory 376307712
Warning: Permanently added '172.27.0.15' (ECDSA) to the list of known hosts.
[...]
IpExt: InNoRoutes InTruncatedPkts InMcastPkts OutMcastPkts InBcastPkts OutBcastPkts InOctets OutOctets InMcastOctets OutMcastOctets InBcastOctets OutBcastOctets InCsumErrors InNoECTPkts InECT1Pkts InECT0Pkts InCEPkts
IpExt: 0 0 0 0 0 0 12403258568 12404176293 0 0 0 0 0 1183173 0 0 0
```
On the infra, the ssh traffic generation [in a failed case](https://fedorapeople.org/groups/cockpit/logs/pull-7319-20170718-152323-57a29202-verify-rhel-atomic/log.html#55) does seem to work, but it produces a really low throughput:
```
Warning: Permanently added '172.27.0.15' (ECDSA) to the list of known hosts.
IpExt: InNoRoutes InTruncatedPkts InMcastPkts OutMcastPkts InBcastPkts OutBcastPkts InOctets OutOctets InMcastOctets OutMcastOctets InBcastOctets OutBcastOctets InCsumErrors InNoECTPkts InECT1Pkts InECT0Pkts InCEPkts
IpExt: 0 0 0 0 23 0 1174493 1888992 0 0 7544 0 0 2657 0 0 0
```
Thus on my system it squeezed 12 GB through the QEMU network in the 30 (?) seconds that this test was running, while on the infra it merely manages 2 MB. The [screenshot](https://fedorapeople.org/groups/cockpit/logs/pull-7319-20170718-152323-57a29202-verify-rhel-atomic/TestMetrics-testInternal-rhel-atomic-127.0.0.2-2201-FAIL.png) does show a constant ripple on the graph, but compared to the 2.4 Mbps spike it's mostly noise.

I wonder if that's due to the different QEMU versions on the infra vs. on Fedora 26, or maybe related to the `/dev/kvm` screwup that we saw before we switched nested VMs from kvm to emulated QEMU.

**Comment by martinpitt** [comment]
Using a faster ssh cipher or [netcat instead of ssh](https://gist.github.com/martinpitt/16ce7ec1041567ffa7461f0ae87764d2) did not help at all, the speed is still modem-like.

Next step: I rebooted our three CI machines (good chance to install pending updates) and reverted the test change (just the additional debugging), to rule out the /dev/kvm problems.

**Comment by martinpitt** [comment]
The very slow download speeds also happen with image downloads, e. g. [here](https://fedorapeople.org/groups/cockpit/logs/pull-7265-20170719-060909-0789fcfe-verify-rhel-atomic/log.html#11). This is still a frequent reason for test failures.

**Comment by martinpitt** [comment]
Reboot didn't help, still painfully slow. I'm running a test manually on cockpit-10 in the cockpit/tests docker container to investigate.

**Comment by mvollmer** [comment]
While making the network fast is of course very helpful, we can also make the test more robust by measuring the actual network throughput, like we do for the CPU load.

**Comment by mvollmer** [comment]
Is this only happening to testInternal?  Shouldn't testPcp fail in the same way?

**Comment by martinpitt** [comment]
@mvollmer: I've sometimes seen testPcp fail  as well, but for some reason most  of the time it happens to testInternal(). Also, measuring actual throughput is what I'm doing, and as I said it's *absurdly* slow - modem magnitude. There is no point asserting just that, as this is insignificant noise compared to the spikes that happened on the traffic before, and it would just easily pass the test if there is no network traffic at all. We have to find the root cause of that, as it also affects the image download in check-networking*.

I am trying the following on our cockpit-{8,9,10} machines:
```
=== on host ==
docker run -ti --rm --privileged --uts=host --volume=/var/lib/cockpit-tests/secrets:/secrets:ro --volume=/var/cache/cockpit-tests:/cache:rw cockpit/tests /bin/bash -i

== in container ==
cd cockpit
git pull
test/vm-run rhel-atomic

== in test VM ==
ssh -o StrictHostKeyChecking=no 172.27.0.15 cat /dev/zero >/dev/null
## enter password, ^Z, bg
cat /proc/`pidof ssh`/net/netstat
## do that ^ several times, check IP throughput
poweroff

== back in container ==
./autogen.sh --prefix=/usr --sysconfdir=/etc --localstatedir=/var
export TEST_OS=rhel-atomic
bots/image-prepare
test/verify/check-metrics TestMetrics.testInternal
test/verify/check-networking-basic TestNetworking.testBasic
```

The first simple test (ssh in basic test machine) worked fine on cockpit-8 and -9, on -10 I had some trouble (background process got stopped, will investigate). However, right now on -8 and -9 I can reproduce the test failure with the slow networking; it might be load related, or backgrounding the ssh process somehow doesn't do what we think it does. I keep debugging.

**Comment by martinpitt** [comment]
Some more observations:
 * `/proc/pid/net/netstat` is misleading, it's not the per-process statistics (Linux doesn't keep track of that), but the global one. A better way to measure network traffic is to calculate per-time deltas of `grep ` *iface* `/proc/net/dev  | awk '{print $2 + $10}'`
 * `ssh -vv -o StrictHostKeyChecking=no -i /var/tmp/identity 172.27.0.15` is extremely slow on cockpit-8. It takes about a minute to establish the ssh connection, hanging in authentication. That explains why that command doesn't generate measurable network traffic. It does not explain yet why the `netcat` approach failed. I can't reproduce this on cockpit-9, but again it might be load related.
 * Device names on rhel-atomic use the udev names (`ens5`) (not sure if that is relevant)
 * `ssh -i /var/tmp/identity -o StrictHostKeyChecking=no 172.27.0.15 cat /dev/zero > /tmp/dump &` produces lots of output in `/tmp/dump`, but *not* in `/proc/net/dev` - the traffic is being accounted to `lo`, not to `eth0` (on Fedora-26)
 * I tried several runs of check-metrics on cockpit-8 and -9, alternating between fedora-26 and rhel-atomic. It seems on both machines rhel-atomic consistently fails and fedora-26 consistently succeeds. That suggests it's not the outside qemu, but a problem inside the test VM; possibly with the ethernet names?

**Comment by martinpitt** [comment]
I added a force failure to the test on fedora-26 (still on the infra) and got a screenshot after the `wait('ph_flot_data_plateau("#server_network_traffic_graph",300000,null,5,"net io")')` succeeded. And lo and behold, it's completely zero:

![metrics-f26](https://user-images.githubusercontent.com/200109/28359618-28c7b924-6c73-11e7-9880-e64c46b856a0.png)

This seems to coincide with the above observation that the traffic from the ssh is being accounted to lo, which `/proc/net/dev` confirms:
```
  eth0:  160004    2490    0    0    0     0          0         0  1284403    1948    0    0    0  9402       0          0
    lo: 9498928161  902695    0    0    0     0          0         0 9498928161  902695    0    0    0     0       0          0
```

You can also bump the "300" in that check to "30000" and it still succeeds:

        b.wait_js_func("ph_flot_data_plateau", "#server_network_traffic_graph", 300*1000, None, 5, "net io");

So quite obviously this check is completely broken when running on the bots - both the traffic generation (`ssh cat /dev/zero`) and its validation.

I just confirmed that the same happens locally. So all in all, the current test doesn't actually check anything, it just randomly succeeds or fails.

**Comment by martinpitt** [comment]
Amendment: When running the ssh /dev/zero command interactively, apparently our "network traffic" graph does pick that up, so it's apparently counting loopback traffic too. We should most probably ignore lo, but aside from that the flat graph in the noninteractive test might either be a strange phantomjs bug, or that the ssh traffic still isn't what we expect it to be when it's running noninteractively.

**Comment by martinpitt** [comment]
With the better debugging in #7319 this now confirms the numbers on the infra. On most OSes we get something like

    Measured 1.9s of network traffic; eth0/ens5: 5412 bytes, lo: 220691084 bytes

while on [rhel-atomic](https://fedorapeople.org/groups/cockpit/logs/pull-7319-20170719-103939-fd4f5a15-verify-rhel-atomic/log.html#53) we get

    Measured 60.0s of network traffic; eth0/ens5: 41907 bytes, lo: 71636 bytes

**Comment by martinpitt** [comment]
I went through the confusing points above, and I think I resolved them now:

 * With a netcat approach I do get a neat throughput of several Gbps on rhel-atomic too. ssh inside the rhel-atomic image indeed takes ages and does not generate much traffic. Both the authentication (GSS blocks for a lot of time) and the encryption (RNG not yet initialized while the test runs?) seem to pose problems. PR #7319 should now work, I locally tested it on rhel-atomic, rhel-7, and fedora-26.

 * The graph on a phantomjs failure PNG is flatlining, but that seems to be a bug with phantomjs. In firefox it's working fine, and the textual debugging shows proper numbers now:

       Measured 1.9s of network traffic; eth0/ens5: 5065 bytes, lo: 5335514800 bytes

 * *"You can also bump the "300" in that check to "30000" and it still succeeds:"* - this is actually correct. netcat (and ssh on other OSes) easily generate 30 MBps, so I was simply not aiming high enough to break the test. With "300000" (300 MBps) it still succeeds (it has to measure for a little longer, 3.6s), with "3000000" (3 GBps) it fails. So the test (and hence the Cockpit graph) does measure the throughput correctly.

 * netcatting to 127.0.0.1 still gets recorded; I'm not sure whether it makes sense to include the loopback device in that graph, but this is a separate issue, unrelated to the test. I filed that as issue #7338 to not forget about it.
