### ISSUE TITLE
Hide buf/cache from RAM usage graph?

### ISSUE THREAD

**Issue by lsaadeh1** [cockpit-project/cockpit#7358]
Currently cockpit is showing that all my ram is used, this is incorrect as free ram is being used for buff/cache but is still available. if this is intended maybe have a checkbox to exclude buff/cache ram

**Comment by martinpitt** [comment]
To clarify, you mean the "summary" graph on the `/system` page, not the detailled graph when you click on the "memory" label there (leading to `/system#/memory`), right? The latter already shows swap/cached/used/free.

I wouldn't call this "wrong", it's a matter of opinion and also consistency. As it is now, the summary graph reflects the shape and size of the detailled graph, and for VMs the memory usage on the hypervisor doesn't care whether the memory is being used for "real" process data or page caches.

I'm leaning towards not changing this, but I'm open to arguments from others.

**Comment by lsaadeh1** [comment]
Hi @martinpitt, thanks for taking the time to get back to me. 

Thats correct the summary graph is the one I was talking about. While you are correct this isn't 'free' memory and its isn't wrong, I do find the summary less useful as the graph is maxed out all the time and it doesn't provide me any information at a glance, I would find it more useful if I could exclude buff/cache from the summary to provide me a useful summary of current ram usage. 

As I know this isn't for everyone, adding a setting to exclude it from summary would allow everyone to be happy.

**Comment by petervo** [comment]
@martinpitt this has come up enough both here and for the various container graphs that i think we need some sort of design solution. @andreasn was going to look into it. We have this open #2751. Closing this in favor of that one. @lsaadeh1 if you have a suggestion of what you think this could look like let's continue the discussion over there.
