### ISSUE TITLE
Registry slow when having many images

### ISSUE THREAD

**Issue by chlunde** [cockpit-project/cockpit#7371]
With many images (4000) in a registry, the UI is slow, and it is difficult to locate an image.

Possible fixes:
* Don't show tags if there are too many images (require the user to click on an image to show tags)
* Add search option and limit to N images/tags

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
