### ISSUE TITLE
Add Ubuntu 16.04 cockpit-Packagekit package

### ISSUE THREAD

**Issue by petems** [cockpit-project/cockpit#7465]
Currently the building of the cockpit-packagekit package is disabled for Xenial because packagekit was not working, but enabled for zesty. Asking on IRC, this was intentional because of the broken Xenial functionality.

This is being backported to Xenial: https://bugs.launchpad.net/ubuntu/+source/packagekit/+bug/1689820/

> I found the fix and backported it to xenial. The SRU is complicated by the fact that packagekit is currently FTBFS due to recent firefox dropping NPAPI, thus the browser plugin cannot be built any more. I'll drop it.

Can the pipeline to create a package for cockpit-packagekit be enabled for 16.04 once the fix has been backported?

**Comment by martinpitt** [comment]
Yes, of course, that's the intent of the SRU above.

**Comment by martinpitt** [comment]
My SRU made it through QA into xenial-updates, so the next image rebuild should pick this up and then I can enable this.
