### ISSUE TITLE
DMI Info Fallback

### ISSUE THREAD

**Issue by dcrdev** [cockpit-project/cockpit#7476]
In instances where the mainboard manufacturer has not populated the DMI tables within the firmware, can a fallback be introduced for the "Hardware" section on the "System" tab?

As a fallback could this information be sourced from /proc/cpuinfo ?

Just built a new server and the firmware has empty DMI tables, resulting in Cockpit just displaying "To Be Filled By O.E.M." several times over.

**Comment by dcrdev** [comment]
Ok I didn't fully understand what was happening here, but now I can shed some light on the problem as I was going to submit a pr but my workaround now seems like the wrong solution.

The problem is that my board has an ipmi chip and that is being listed by dmidecode before the main board. So the second entry accurately shows information about my board, the first entry has no dmi information written.

**Comment by monreal** [comment]
Similar or same in my case. Please get the information from "Base Board Information".

> Handle 0x0001, DMI type 1, 27 bytes
> System Information
> 	Manufacturer: To Be Filled By O.E.M.
> 	Product Name: To Be Filled By O.E.M.
> 	Version: To Be Filled By O.E.M.
> 	Serial Number: To Be Filled By O.E.M.
> 	UUID: 71c28570-1177-0000-0000-000000000000
> 	Wake-up Type: Power Switch
> 	SKU Number: To Be Filled By O.E.M.
> 	Family: To Be Filled By O.E.M.
> 
> Handle 0x0002, DMI type 2, 15 bytes
> Base Board Information
> 	Manufacturer: ASRock
> 	Product Name: J4105-ITX
> 	Version:                       
> 	Serial Number: M80-B1004200114
> 	Asset Tag:                       
> 	Features:
> 		Board is a hosting board
> 		Board is replaceable
> 	Location In Chassis:                       
> 	Chassis Handle: 0x0003
> 	Type: Motherboard
> 	Contained Object Handles: 0
> 
> Handle 0x0003, DMI type 3, 22 bytes
> Chassis Information
> 	Manufacturer: To Be Filled By O.E.M.
> 	Type: Desktop
> 	Lock: Not Present
> 	Version: To Be Filled By O.E.M.
> 	Serial Number: To Be Filled By O.E.M.
> 	Asset Tag: To Be Filled By O.E.M.
> 	Boot-up State: Safe
> 	Power Supply State: Safe
> 	Thermal State: Safe
> 	Security Status: None
> 	OEM Information: 0x00000000
> 	Height: Unspecified
> 	Number Of Power Cords: 1
> 	Contained Elements: 0
> 	SKU Number: To Be Filled By O.E.M.

**Comment by garrett** [comment]
Similarly, I have an ARM server and Cockpit reports the "Hardware" and "Asset Tag" as empty.

To make it worse: As Cockpit currently links to the detailed system information from the "Hardware" string, I don't have a link on the server to see detailed hardware information. (We should have an explicit link for more information anyway. I'm working on this in a new design.)

**Comment by garrett** [comment]
We should treat an empty string and "To Be Filled By O.E.M." as one and the same.

The question is if we should skip showing the information or show a string like "Not available". I'd suggest not showing the string at all in most (and probably all) cases.

FWIW, [it seems like "To Be Filled By O.E.M." is a non-translated, commonly-used string](https://duckduckgo.com/?q="To+Be+Filled+By+O.E.M.").

**Comment by garrett** [comment]
On my Raspberry Pi 4, which seems to have this issue:

```sh
# grep -r . /sys/class/dmi/id
grep: /sys/class/dmi/id: No such file or directory

# grep -r . /sys/class/dmi/
grep: /sys/class/dmi/: No such file or directory

# grep -r . /sys/class/
grep: /sys/class/gpio/unexport: Permission denied
grep: /sys/class/gpio/export: Permission denied
/sys/class/devcoredump/disabled:0
grep: /sys/class/zram-control/hot_remove: Permission denied
/sys/class/zram-control/hot_add:1
/sys/class/drm/version:drm 1.1.0 20060810

# ls /sys/class/dmi/
ls: cannot access '/sys/class/dmi/': No such file or directory

# ls /sys/class/
ata_device	 devfreq-event	input	  powercap	  rpivid-intcmem  tpm
ata_link	 dma		iommu	  power_supply	  rpivid-vp9mem   tpmrm
ata_port	 dma_heap	leds	  ppp		  rtc		  tty
backlight	 drm		lirc	  pps		  scsi_device	  uio
bcm2708_vcio	 extcon		mdio_bus  ptp		  scsi_disk	  vc
bcm2835-gpiomem  gpio		mem	  pwm		  scsi_generic	  vchiq
bdi		 graphics	misc	  rc		  scsi_host	  vc-mem
block		 hidraw		mmc_host  regulator	  sound		  video4linux
bluetooth	 hwmon		nd	  remoteproc	  spidev	  vtconsole
bsg		 i2c-adapter	net	  rfkill	  spi_master	  watchdog
devcoredump	 i2c-dev	pci_bus   rpivid-h264mem  spi_slave	  zram-control
devfreq		 ieee80211	phy	  rpivid-hevcmem  thermal
```

**Comment by monreal** [comment]
On the system I reported on may 30, 2019 (see above):

grep -r . /sys/class/dmi/id
/sys/class/dmi/id/bios_date:08/06/2018
/sys/class/dmi/id/board_serial:M80-B1004200114
/sys/class/dmi/id/uevent:MODALIAS=dmi:bvnAmericanMegatrendsInc.:bvrP1.40:bd08/06/2018:br5.13:svnToBeFilledByO.E.M.:pnToBeFilledByO.E.M.:pvrToBeFilledByO.E.M.:rvnASRock:rnJ4105-ITX:rvr:cvnToBeFilledByO.E.M.:ct3:cvrToBeFilledByO.E.M.:
/sys/class/dmi/id/product_serial:To Be Filled By O.E.M.
/sys/class/dmi/id/product_name:To Be Filled By O.E.M.
/sys/class/dmi/id/chassis_vendor:To Be Filled By O.E.M.
/sys/class/dmi/id/chassis_asset_tag:To Be Filled By O.E.M.
/sys/class/dmi/id/sys_vendor:To Be Filled By O.E.M.
/sys/class/dmi/id/power/runtime_active_time:0
/sys/class/dmi/id/power/runtime_status:unsupported
grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error
/sys/class/dmi/id/power/runtime_suspended_time:0
/sys/class/dmi/id/power/control:auto
/sys/class/dmi/id/bios_version:P1.40
/sys/class/dmi/id/bios_release:5.13
/sys/class/dmi/id/product_version:To Be Filled By O.E.M.
/sys/class/dmi/id/board_vendor:ASRock
/sys/class/dmi/id/chassis_version:To Be Filled By O.E.M.
/sys/class/dmi/id/product_sku:To Be Filled By O.E.M.
/sys/class/dmi/id/chassis_type:3
/sys/class/dmi/id/chassis_serial:To Be Filled By O.E.M.
/sys/class/dmi/id/product_family:To Be Filled By O.E.M.
/sys/class/dmi/id/product_uuid:71c28570-1177-0000-0000-000000000000
/sys/class/dmi/id/bios_vendor:American Megatrends Inc.
/sys/class/dmi/id/modalias:dmi:bvnAmericanMegatrendsInc.:bvrP1.40:bd08/06/2018:br5.13:svnToBeFilledByO.E.M.:pnToBeFilledByO.E.M.:pvrToBeFilledByO.E.M.:rvnASRock:rnJ4105-ITX:rvr:cvnToBeFilledByO.E.M.:ct3:cvrToBeFilledByO.E.M.:
/sys/class/dmi/id/board_name:J4105-ITX

**Comment by martinpitt** [comment]
Indeed ARM has no DMI, but these two files in device tree look useful, on my RasPi 3:
```
$ grep -ar . /proc/device-tree/{model,serial-number}
/proc/device-tree/model:Raspberry Pi 3 Model B Rev 1.2
/proc/device-tree/serial-number:0000000057c81ec9
```
They are a good counterpart for the "Model" and "Asset tag" that we have on x86. The other files don't seem to be too interesting.

**Comment by martinpitt** [comment]
It is an absolute nuisance trying to fake this for the tests:
 * One can't just `mkdir /proc/device-tree` in a real procfs, as it's not enough of a file system.
 * procfs [can't be overlaid](https://unix.stackexchange.com/questions/371915/why-cant-proc-be-a-layer-of-a-overlay-file-system-overlayfs-on-linux)
 * Globally over-mounting /proc with a tmpfs completely breaks just about everything
 * I tried to over-mount it only in the cockpit-bridge process:
```python
        m.execute(r"""mount -t tmpfs none /sys/class/dmi
                      mkdir -p /tmp/fakeproc/device-tree
                      echo "CoolThingSOC Model 42" > /tmp/fakeproc/device-tree/model
                      echo 0012345 > /tmp/fakeproc/device-tree/serial-number
                      printf '#!/bin/sh\nunshare -rUm sh -ec "mount -o bind /tmp/fakeproc /proc/; exec /usr/bin/cockpit-bridge $@"\n' > /usr/local/bin/cockpit-bridge
                      chmod a+x /usr/local/bin/cockpit-bridge
                      """)
        self.addCleanup(m.execute, "umount /sys/class/dmi/id; rm /usr/local/bin/cockpit-bridge")

```
    But that does not work either, one gets an immediate crash on missing /proc/stats and such.

 * /proc/devicetree is actually just a symlink to /sys/firmware/devicetree/base. Faking that is trivial, but userspace is supposed to use /proc only, as that's stable while the latter could change.

**Comment by martinpitt** [comment]
PR #16127 implements the DeviceTree bits for RasPi & Co. Keeping this open for the "to be filled by O.E.M." aspect.

**Comment by dcrdev** [comment]
> I don't have any machine where I could see such behavior. I therefore will need some debug info from people who see this behavior. Can you please provide me with output of this following command?
> 
> ```
> grep -r . /sys/class/dmi/id
> ```
```shell
$ grep -r . /sys/class/dmi/id
/sys/class/dmi/id/product_name:To Be Filled By O.E.M.
/sys/class/dmi/id/product_uuid:00000000-0000-0000-0000-D05099C12B65
/sys/class/dmi/id/board_name:E3C236D2I
/sys/class/dmi/id/board_asset_tag:        
/sys/class/dmi/id/power/control:auto
/sys/class/dmi/id/power/async:disabled
/sys/class/dmi/id/power/runtime_enabled:disabled
/sys/class/dmi/id/power/runtime_active_kids:0
/sys/class/dmi/id/power/runtime_active_time:0
grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error
/sys/class/dmi/id/power/runtime_status:unsupported
/sys/class/dmi/id/power/runtime_usage:0
/sys/class/dmi/id/power/runtime_suspended_time:0
/sys/class/dmi/id/chassis_serial:To Be Filled By O.E.M.
/sys/class/dmi/id/product_version:To Be Filled By O.E.M.
/sys/class/dmi/id/chassis_vendor:To Be Filled By O.E.M.
/sys/class/dmi/id/modalias:dmi:bvnAmericanMegatrendsInc.:bvrL2.21:bd05/16/2017:svnToBeFilledByO.E.M.:pnToBeFilledByO.E.M.:pvrToBeFilledByO.E.M.:rvnASRockRack:rnE3C236D2I:rvr:cvnToBeFilledByO.E.M.:ct3:cvrToBeFilledByO.E.M.:
/sys/class/dmi/id/chassis_version:To Be Filled By O.E.M.
/sys/class/dmi/id/bios_date:05/16/2017
/sys/class/dmi/id/bios_version:L2.21
/sys/class/dmi/id/product_serial:To Be Filled By O.E.M.
/sys/class/dmi/id/sys_vendor:To Be Filled By O.E.M.
/sys/class/dmi/id/bios_vendor:American Megatrends Inc.
/sys/class/dmi/id/board_serial:        
/sys/class/dmi/id/uevent:MODALIAS=dmi:bvnAmericanMegatrendsInc.:bvrL2.21:bd05/16/2017:svnToBeFilledByO.E.M.:pnToBeFilledByO.E.M.:pvrToBeFilledByO.E.M.:rvnASRockRack:rnE3C236D2I:rvr:cvnToBeFilledByO.E.M.:ct3:cvrToBeFilledByO.E.M.:
/sys/class/dmi/id/chassis_asset_tag:To Be Filled By O.E.M.
/sys/class/dmi/id/chassis_type:3
/sys/class/dmi/id/board_vendor:ASRockRack
/sys/class/dmi/id/board_version:
```

**Comment by martinpitt** [comment]
I sent PR #16280 to ignore the "to be filled by OEM" values and fall back to board name/vendor. That was the second and last part of this issue.
