### ISSUE TITLE
Make cockpit-machines configurable

### ISSUE THREAD

**Issue by mareklibra** [cockpit-project/cockpit#7484]
Implement application-wide configuration for pkg/machines as already started in pkg/machines/config.es6 to allow finer tuning or different deployment scenarios in production environment.

Location: /usr/share/cockpit/machines/machines.conf

Presence of the config file is optional, cockpit-machines will be installed with defaults.

The config file is retrieved at cockpit-machines plugin start-up. If found, defaults in `config.es6` will be merged with its content.

The config file is accessed via `cockpit.file` interface.

Options to set:
- refresh interval for "usage polling", default 10 seconds
- virsh connection URIs, default is `qemu:///system` and `qemu:///session`
- logging level (debug on/off), default is off

**Comment by michalskrivanek** [comment]
may be better/easier if we use the default env variable https://libvirt.org/uri.html#URI_default

**Comment by stefwalter** [comment]
Is this meant to be changed by packagers or admins? If the former it should go into manifest.json/override.json ... if the latter it should go into /etc

**Comment by michalskrivanek** [comment]
I would say admins, but I think we should also honor the LIBVIRT_DEFAULT_URI environment variable

**Comment by mareklibra** [comment]
The `libvirt-dbus` project is expected to be released shortly and `pkg/machines` will be adopting it, if possible. 

Configuration highlighted in this issue is expected to be incompatible with the new DBus approach, so putting it on-hold for a while.

**Comment by KKoukiou** [comment]
As mentioned above cockpit-machines package is now developed only with using libvirt DBus bindings. Supporting remore URIs is not supported with this, and generally we wouldn't like to expose any configuration options through some file. So I 'll close this, since it's outdated.
