### ISSUE TITLE
Cockpit-kubernetes on Kubernetes 1.7.3 GKE Error

### ISSUE THREAD

**Issue by dt665m** [cockpit-project/cockpit#7502]
I'm getting this error on my GKE cluster:

**Authentication failed: internal-error: This version of kubernetes is not supported. Turn off anonymous auth or upgrade.**

The GKE cluster comes with a built in basic auth account.  I was able to exec bash into the container running cockpit-kubernetes and successfully issue this:
`` $ curl -k -u user:password https://$KUBERNETES_SERVICE_HOST/ --insecure``

So I'm reasonably certain cockpit-kubernetes can access the API.  I'm wondering if the latest docker image is targeting a Kubernetes Version == to a specific build?  The error code suggests the version I'm on is too old but 1.7.3 is pretty bleeding edge.  Any help troubleshooting this?  

Curiously, I'm also unable to access this cluster via an independent instance of CentOS with standard cockpit+cockpit-kubernetes installed along a working kubectl and ~/.kube/config file.

**Comment by dt665m** [comment]
just spun up a 1.6.7 Kubernetes cluster to test this and still getting the same error.  Has anyone gotten cockpit-kubernetes to work with GKE either in-cluster or through pre-configured kubectl + standard cockpit session

**Comment by petervo** [comment]
@dt665m, setting up kubectl to connect to any version of GCE via a ~/.kube/config file works for me. for me. When trying this, what version of cockpit-kubernetes were you using?

For the container version if you are using 1.6.x you need to use the OAUTH auth method. Make sure you have the latest cockpit/kubernetes container from docker hub. and setup as described in #7186. I have tested this.

I haven't yet tested 1.7.3 on GCE with basic auth. It should work, but i'll try to get access to one to verify.

**Comment by dt665m** [comment]
@petervo for the cockpit-kubernetes standalone session, I used the current rpm version for centos7, installed through yum.  It seemed like I couldn't get any Api calls even though kubectl was working correctly.  Do you recommend another version?

As for your OAuth method, I'm not entirely sure how the flow works for that in kubernetes honestly. I understand the environment variable needs to be set for the pod but I'm not sure where I need to whitelist/setup OAuth in the cluster/setup credentials.   I really appreciate you taking the time to respond!  Thanks again.

**Comment by dt665m** [comment]
@petervo quick update on this... I've temporarily given up on running cockpit in the cluster so I decided to give a separate cockpit session a go.  Here is my setup:

3 Node Google Container Engine Kubernetes 1.6.7
1 Debian(stretch) Instance, using ``./configure && make install`` on cockpit-148
kubectl configured to be able to access the cluster (~/.kube/config setup and ``kubectl cluster-info`` working)

1.) Log into cockpit
2.) Cluster Tab = "Couldn't Connect To Server - couldn't find running API"
3.) Run ``kubectl proxy`` in cockpit terminal
4.) Cluster Tab click "Troubleshoot" and input the correct proxy url and port
5.) Cluster Tab works.  (sort of)

I'm seeing a lot of proxying errors in the terminal and most of the stats related metrics aren't available in the UI.  Nodes, namespaces, topology and pods all seem to be showing up though.

New question:  Is Cockpit supposed to auto-detect ~/.kube/config and automatically try to access the cluster API through it or do I have to use kubectl proxy?  I noticed in cockpit-148, there is no drop down menu to select .kube configurations anymore.  Any idea what I might be doing wrong if ~/.kube/config should work automatically?

**Comment by petervo** [comment]
You do not need to use kubectl proxy. Cockpit looks at ~/.kube/config for where to talk to kubernetes. Make sure you are logging into cockpit with the same user you are using on the command line to type kubectl.

I also see the icon to get the menu to change so I can't help but think something isn't quite right with your setup. If you aren't sure what version you have, I recommend using the latest from copr (https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/) on a fedora or centos machine.

If you are using proxy you won't get the metrics as those aren't usually proxied correctly.

>As for your OAuth method, I'm not entirely sure how the flow works for that in kubernetes honestly. I understand the environment variable needs to be set for the pod but I'm not sure where I need to whitelist/setup OAuth in the cluster/setup credentials. I really appreciate you taking the time to respond! Thanks again.

This is a google thing, you have to set up a oauth client id with authorized redirect urls. Google has pretty good docs on this. https://console.developers.google.com/apis/credentials

**Comment by dt665m** [comment]
@petervo finally got it working.  I ended up adding the preview repo on a fresh centos7 machine.  For future reference if anyone finds their way here for GKE clusters... these are the things I had to do to get it to work:

1.) Make sure the GKE Cluster is configured with "basic authentication enabled" (this is actually on by default)
2.) setup kubectl to get the proper ~/.kube/config
3.) login to cockpit 
4.) click the Clusters Tab, click Connection Settings wrench in Overview
5.) your .kube cluster should be listed.  Go to Users and plug in your basic authentication credentials

I was under the impression cockpit will use the account/cert in the kube config file for authentication but apparently that isn't working for me.  After manually setting up basic auth, everything works.  Thanks for all the help @petervo.  If a working ~/.kube/config file is supposed to just work out of the box (and I am logged in to cockpit with the correct user account that has kubectl working), then maybe my instance has some debug info that can help.  Let me know if there's anything I can do.  I'll be tearing this instance down in a few days.

**Comment by petervo** [comment]
Yes a working ~/.kube/config should work out of the box. You should not need to use basic auth if you have a certificate setup.

**Comment by petervo** [comment]
What fields does the certificate user have in your .kube/config? Or if you want to send me your .kube/config file with the secrets stubbed out I can take a look.

**Comment by dt665m** [comment]
Sorry for the delay @petervo , here is the .kube/config used:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ****
    server: https://****
  name: gke_tsaiunion_asia-east1-a_tsaik8s
contexts:
- context:
    cluster: gke_tsaiunion_asia-east1-a_tsaik8s
    user: gke_tsaiunion_asia-east1-a_tsaik8s
  name: gke_tsaiunion_asia-east1-a_tsaik8s
current-context: gke_tsaiunion_asia-east1-a_tsaik8s
kind: Config
preferences: {}
users:
- name: gke_tsaiunion_asia-east1-a_tsaik8s
  user:
    auth-provider:
      config:
        access-token: ****
        cmd-args: config config-helper --format=json
        cmd-path: ****
        expiry: 2017-08-17T10:58:14Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

This is generated by the ```gcloud container clusters get-credentials``` helper.  I've tried with a few more clusters now and I still cannot automatically login with cockpit-148 with the ~/.kube/config without explicitly using basic auth as a new user.

**Comment by petervo** [comment]
@dt665m, interesting this is a little different from the format that we normally use. We normally expect a a token attribute on the user itself, see (https://github.com/cockpit-project/cockpit/blob/master/pkg/kubernetes/scripts/kube-client-cockpit.js#L832). I guess we need to find where the new format is documented and update our code to find tokens given in this way. You interested in having a go at adding this?

**Comment by dt665m** [comment]
@petervo I could try to take a look but honestly I'm not too familiar with the codebase.  If it's in the javascript part you linked me I'll take a look at it and see what a good way to detect this format would be given the way it's currently handled.  If there are other related parts of the codebase you want to point me to that would help out.

**Comment by petervo** [comment]
@dt665m if you are able to try out #7585, that should fix the kubeconfig issue.

**Comment by petervo** [comment]
Cockpit/kubernetes has been updated
