### ISSUE TITLE
Feature request: notes

### ISSUE THREAD

**Issue by elecprog** [cockpit-project/cockpit#7505]
It would be helpful to be able to leave notes in Cockpit when you make a temporal fix, have to do something in the future...

**Comment by martinpitt** [comment]
This is dangerously close to the old "no software is complete until it grows an email client" :wink: 

Cockpit manages the system through existing APIs, but note taking to "arbitrary system components" isn't something that Linux does. Thus this would require putting cockpit specific files in the file system, which we really want to avoid.

There are a gazillion notekeeping applications out there, and probably everyone has their favourite, so let's not reinvent yet another bad implementation.

**Comment by elecprog** [comment]
> "no software is complete until it grows an email client"
Well I mean it could be implement by using the Unix `mail` utility.

But indeed there are already many great note keeping and team communication tools that could perfectly achieve this.
