### ISSUE TITLE
Concerns related to "Drop extra priviledges"

### ISSUE THREAD

**Issue by LHinson** [cockpit-project/cockpit#751]
We may need to discuss as I'm not familiar with this feature but when I click on "Drop extra privileges" it immediately goes gray and I'm unsure as to what I just did. When I clicked this and it immediately went gray I was left thinking, "whoops, I hope that's not bad". It would be helpful if the user was presented with a dialog warning them of the action that they are about to take. Thoughts?

**Comment by andreasn** [comment]
Fixed here https://github.com/cockpit-project/cockpit/pull/9531
