### ISSUE TITLE
spec file needs reworking for https://fedoraproject.org/wiki/Changes/SubpackageAndSourceDebuginfo

### ISSUE THREAD

**Issue by cgwalters** [cockpit-project/cockpit#7510]
https://koji.fedoraproject.org/koji/taskinfo?taskID=20981011 :arrow_right:  https://kojipkgs.fedoraproject.org//work/tasks/1011/20981011/build.log
> RPM build errors:
>    Could not open %files file /builddir/build/BUILD/cockpit-146/debugsourcefiles.list: No such file or directory

I think https://fedoraproject.org/wiki/Changes/SubpackageAndSourceDebuginfo broke the manual debuginfo bits in the current spec.

**Comment by cgwalters** [comment]
It's going to block F27AH (and shipping cockpit in F27 in general I assume) - I hit this locally when testing out a modular AH build.

**Comment by contyk** [comment]
This is blocking even the non-AH build for Fedora 27. There was a request to include Cockpit in Platform and this is effectively preventing us from doing so.

**Comment by stefwalter** [comment]
I did some work on playing with this and fixing it. Will dig it out.

**Comment by stefwalter** [comment]
Changes have been merged to fix building on F27. We just need a release. @petervo What do you think about releasing today?

**Comment by contyk** [comment]
v149 fixes the problem. This can be closed. Thank you.
