### ISSUE TITLE
Development environment for cockpit-Dashboard(kubernetes)

### ISSUE THREAD

**Issue by anoopvm** [cockpit-project/cockpit#7517]
I was trying to customize cockpit-project. I need the cockpit to monitor a kubernetes cluster running on ubuntu 16.04 servers. So I prefer to run the cockpit as a pod. My development server is also running Ubuntu 16.04 LTS. While exploring development environment I found this page "https://github.com/cockpit-project/cockpit/tree/master/containers" where it is mentioned to mount the source path to the container path "/.local/share/cockpit". I am able to mount but the page is loading from a different path in the container i.e. "/usr/share/cockpit/kubernetes". Where the files seems to be in the format *.gz (for eg: index.html.gz). I am new to node.js or any similar environment. How am I supposed to keep my changes from "/.local/share/cockpit" to "/usr/share/cockpit/kubernetes" with the *.gz format? I have seen references to webpack. Not sure if I need to use that. Even if I have to use that, should I run webpack inside the container to package contents in "/.local/share/cockpit" to "/usr/share/cockpit/kubernetes"? Or it should be packaged using webpack in my Ubuntu machine and create a container based on that? Any help would be greatly appreciated as I cannot find any detailed docs regarding cockpit development environment anywhere.

**Comment by petervo** [comment]
I would not recommend trying to develop live using a container. It's a lot more difficult. If you have a working ~/.kube/config and kubectl on your desktop you can get the kubernetes interface without having to run it as a pod. That way you can develop on your desktop and build a container from your results. That said if you really want to do it, you can. You should mount the kubernetes directory from your dist directory on your desktop to /.local/share/cockpit/kubernetes. exec into the container and run

```
/usr/libexec/cockpit-stub --packages
```

It should show that the kubernetes package is loaded from  /.local/share/cockpit/kubernetes. With this setup you still run webpack on your desktop but webpacks output directory is mounted in the container so your changes are picked up when you refresh.

**Comment by anoopvm** [comment]
Thank you very much @petervo for the inputs. As you suggested, I went with desktop installation and the customization is in progress. I think, I will build a container from it.
Initially I had trouble in setting up environment in Ubuntu, as the command line for node.js is 'nodejs' while the webpack was looking for 'node'. That is when I was trying different options. After installing node.js-legacy I could make it working. 
Thanks a lot again!
