### ISSUE TITLE
Question: Add nodes to dashboard programmatically?

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [cockpit-project/cockpit#7528]
If I have a cluster node, which has a list of his nodes, how can I add them to a dashboard? Is there cockpit.js API or some other way to do so?

**Comment by petervo** [comment]
There isn't at the moment. You can write them to .json file in /etc/cockpit/machines.d/. See the file 99-webui.json file currently there for an example. The plan is to eventually provide a command that can add or remove machines programmatically. But it hasn't been done yet.

**Comment by igorSmirnovPlexi** [comment]
Thank you for the answer!
