### ISSUE TITLE
SSH - add new server: internal error

### ISSUE THREAD

**Issue by tomasxiv** [cockpit-project/cockpit#7537]
Hi,
I'm not able to add new server in cockpit 148, it cries "Internal error". In my previous version 126 it was working. 
It is built on PowerPC, Debian Jessie.
Local server logs:
```
Aug 24 11:49:07 xxxx cockpit-bridge[3803]: cockpit-ssh-Message: cockpit-ssh xx.xx.xx.xx: couldn't agent authenticate: Bad authentication reply message type: 201326592
Aug 24 11:49:07 xxxx cockpit-bridge[3803]: cockpit-ssh-Message: cockpit-ssh xx.xx.xx.xx: couldn't authenticate: Bad authentication reply message type: 201326592
```
Remote server logs:
```
Aug 24 11:49:06 yyyy sshd[3299]: Connection from xx.xx.xx.xx port 39361 on yy.yy.yy.yy port 22
Aug 24 11:49:07 yyyy sshd[3299]: Connection closed by xx.xx.xx.xx [preauth]
```
Obviously, there pam_reauthorize.so module is missing.

**Comment by petervo** [comment]
@tomasxiv, what version of libssh are you using?

**Comment by tomasxiv** [comment]
```
# dpkg -l | grep libssh
ii  libssh-4:powerpc                0.6.3-4+deb8u2            powerpc      tiny C SSH library (OpenSSL flavor)
ii  libssh2-1:powerpc               1.4.3-4.1+deb8u1          powerpc      SSH2 client-side library

```

**Comment by petervo** [comment]
What changed is that we don't explicitly stop ssh-key based authentication anymore with older libssh versions. My best guess is that seems like this is a bug in the libssh library. I don't have access to a power pc. Are you able to try with a newer version?

**Comment by tomasxiv** [comment]
ok, I'm going to try it, but those are the newest stable versions for Jessie PPC

**Comment by tomasxiv** [comment]
It is already working with new libssh version.
There is another issue (it could be connected with my modification of other things in js modules): from local server to another, it is not possible to add new server into dashboard table (without specific logs). From side of the remote server it is working correctly.

**Comment by tomasxiv** [comment]
so, now it is fully working, unfortunately with sid (unstable) libssh, but it is due to powerpc

**Comment by petervo** [comment]
For future reference, what is the working version of libssh?

**Comment by tomasxiv** [comment]
Unfortunately unstable version for debian Jessie and ppc, Package: libssh-4 (0.7.5-1) 
https://packages.debian.org/sid/libssh-4

**Comment by petervo** [comment]
Thanks, closing this issue as this seems to be best work around available for now.
