### ISSUE TITLE
cockpit-machines - wrong dependency on 'libvirt'

### ISSUE THREAD

**Issue by mykaul** [cockpit-project/cockpit#7573]
[root@lago-basic-suite-master-host0 ~]# sudo yum install cockpit-machines
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package cockpit-machines.x86_64 0:141-3.el7.centos will be installed
--> Processing Dependency: cockpit-bridge >= 122 for package: cockpit-machines-141-3.el7.centos.x86_64
--> Processing Dependency: cockpit-system >= 122 for package: cockpit-machines-141-3.el7.centos.x86_64
--> Processing Dependency: libvirt for package: cockpit-machines-141-3.el7.centos.x86_64
--> Running transaction check
---> Package cockpit-bridge.x86_64 0:141-3.el7.centos will be installed
--> Processing Dependency: libjson-glib-1.0.so.0()(64bit) for package: cockpit-bridge-141-3.el7.centos.x86_64
---> Package cockpit-machines.x86_64 0:141-3.el7.centos will be installed
--> Processing Dependency: libvirt for package: cockpit-machines-141-3.el7.centos.x86_64
---> Package cockpit-system.noarch 0:141-3.el7.centos will be installed
--> Running transaction check
---> Package cockpit-machines.x86_64 0:141-3.el7.centos will be installed
--> Processing Dependency: libvirt for package: cockpit-machines-141-3.el7.centos.x86_64
---> Package json-glib.x86_64 0:1.0.2-1.el7 will be installed
--> Finished Dependency Resolution
Error: Package: cockpit-machines-141-3.el7.centos.x86_64 (alocalsync)
           Requires: libvirt
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@lago-basic-suite-master-host0 ~]# rpm -qa |grep libvirt
libvirt-daemon-driver-network-2.0.0-10.el7_3.9.x86_64
libvirt-python-2.0.0-2.el7.x86_64
libvirt-daemon-driver-secret-2.0.0-10.el7_3.9.x86_64
libvirt-daemon-2.0.0-10.el7_3.9.x86_64
libvirt-daemon-driver-qemu-2.0.0-10.el7_3.9.x86_64
libvirt-lock-sanlock-2.0.0-10.el7_3.9.x86_64
libvirt-client-2.0.0-10.el7_3.9.x86_64
libvirt-daemon-driver-storage-2.0.0-10.el7_3.9.x86_64
libvirt-daemon-config-nwfilter-2.0.0-10.el7_3.9.x86_64
libvirt-daemon-driver-nodedev-2.0.0-10.el7_3.9.x86_64
libvirt-daemon-kvm-2.0.0-10.el7_3.9.x86_64
libvirt-daemon-driver-nwfilter-2.0.0-10.el7_3.9.x86_64
libvirt-daemon-driver-interface-2.0.0-10.el7_3.9.x86_64

(I am running VMs on that host of course!)
Y.

**Comment by mykaul** [comment]
@mareklibra , @michalskrivanek  - thoughts?

**Comment by michalskrivanek** [comment]
@mykaul you don't have the libvirt meta pkg installed. what repos do you have configured? libvirt rpm should be in common repos. 
Note we do not use "libvirt" dependency in oVirt currently.

**Comment by mykaul** [comment]
I have the usual oVirt repos, fetched via ovirt-system-tests (and thus libvirt is not needed).
(I have disabled all repos but what o-s-t provides, so that explains why it can't find the package)
Are you sure you need libvirt? Isn't libvirt-client the one you actually need?

**Comment by michalskrivanek** [comment]
there are several packages needed, and normally "libvirt" solves the dependencies. We just chose in oVirt to explicitly enumerate them (iirc because of ppc64le)

In cockpit-machines you indeed should onle need the client, but since it's on the local server you practically need others to be able to run a VM. Requiring "libvirt" sounds more maintainable in cockpit than enumerating the combinations/additional rpms based on machines' features

**Comment by petervo** [comment]
I think having this require libvirt makes sense as we don't support connecting to other servers right now people do need the full libvirt to do anything useful.
