### ISSUE TITLE
 SELinux is preventing cockpit-session from using the 'dac_read_search' capabilities

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#7575]
https://bugzilla.redhat.com/show_bug.cgi?id=1476738

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 602, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 773, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1503941806.492:177): avc:  denied  { dac_read_search } for  pid=1209 comm="unix_chkpwd" capability=2  scontext=system_u:system_r:chkpwd_t:s0-s0:c0.c1023 tcontext=system_u:system_r:chkpwd_t:s0-s0:c0.c1023 tclass=capability permissive=0
```
First occurrence: 2017-08-28T17:37:00.117498 | revision 2ba10b8918c974e62767989211914034d7d7ecce, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7558-20170828-173030-2ba10b89-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2017-08-28T17:37:00.117498 | revision 2ba10b8918c974e62767989211914034d7d7ecce, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7558-20170828-173030-2ba10b89-verify-fedora-25/log.html)

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 602, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 773, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1503941806.244:184): avc:  denied  { dac_read_search } for  pid=1181 comm="unix_chkpwd" capability=2  scontext=system_u:system_r:chkpwd_t:s0 tcontext=system_u:system_r:chkpwd_t:s0 tclass=capability permissive=0
```
First occurrence: 2017-08-28T17:37:05.906580 | revision 2ba10b8918c974e62767989211914034d7d7ecce, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7558-20170828-173030-2ba10b89-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2017-08-28T17:37:05.906580 | revision 2ba10b8918c974e62767989211914034d7d7ecce, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7558-20170828-173030-2ba10b89-verify-fedora-25/log.html)

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 602, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 773, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1503941829.429:215): avc:  denied  { dac_read_search } for  pid=1194 comm="unix_chkpwd" capability=2  scontext=system_u:system_r:chkpwd_t:s0-s0:c0.c1023 tcontext=system_u:system_r:chkpwd_t:s0-s0:c0.c1023 tclass=capability permissive=0
```
First occurrence: 2017-08-28T17:37:15.370441 | revision 2ba10b8918c974e62767989211914034d7d7ecce, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7558-20170828-173030-2ba10b89-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2017-08-28T17:37:15.370441 | revision 2ba10b8918c974e62767989211914034d7d7ecce, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7558-20170828-173030-2ba10b89-verify-fedora-25/log.html)

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 602, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 773, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1503941806.255:184): avc:  denied  { dac_read_search } for  pid=1169 comm="unix_chkpwd" capability=2  scontext=system_u:system_r:chkpwd_t:s0 tcontext=system_u:system_r:chkpwd_t:s0 tclass=capability permissive=0
```
First occurrence: 2017-08-28T17:37:24.130459 | revision 2ba10b8918c974e62767989211914034d7d7ecce, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7558-20170828-173030-2ba10b89-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2017-08-28T17:37:24.130459 | revision 2ba10b8918c974e62767989211914034d7d7ecce, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7558-20170828-173030-2ba10b89-verify-fedora-25/log.html)

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 602, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 773, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1503941856.503:184): avc:  denied  { dac_read_search } for  pid=1173 comm="unix_chkpwd" capability=2  scontext=system_u:system_r:chkpwd_t:s0 tcontext=system_u:system_r:chkpwd_t:s0 tclass=capability permissive=0
```
First occurrence: 2017-08-28T17:37:48.601643 | revision 2ba10b8918c974e62767989211914034d7d7ecce, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7558-20170828-173030-2ba10b89-verify-fedora-25/log.html)
Times recorded: 1
Latest occurrences:

- 2017-08-28T17:37:48.601643 | revision 2ba10b8918c974e62767989211914034d7d7ecce, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7558-20170828-173030-2ba10b89-verify-fedora-25/log.html)

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 602, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 773, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1504014066.556:182): avc:  denied  { dac_read_search } for  pid=1185 comm="unix_chkpwd" capability=2  scontext=system_u:system_r:chkpwd_t:s0-s0:c0.c1023 tcontext=system_u:system_r:chkpwd_t:s0-s0:c0.c1023 tclass=capability permissive=0
```
First occurrence: 2017-08-29T13:42:25.174711 | revision 096e37d1af83810a32f1fd5d2ed085d57a2665da
Times recorded: 1
Latest occurrences:

- 2017-08-29T13:42:25.174711 | revision 096e37d1af83810a32f1fd5d2ed085d57a2665da

**Comment by cockpituous** [comment]
verify/fedora-25
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 602, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 773, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1504141437.774:171): avc:  denied  { dac_read_search } for  pid=1208 comm="sm-notify" capability=2  scontext=system_u:system_r:rpcd_t:s0 tcontext=system_u:system_r:rpcd_t:s0 tclass=capability permissive=0
```
First occurrence: 2017-08-31T01:07:05.615530 | revision 72443321bb9bb2e1da3f966d76a622d831dfdfbe
Times recorded: 1
Latest occurrences:

- 2017-08-31T01:07:05.615530 | revision 72443321bb9bb2e1da3f966d76a622d831dfdfbe

**Comment by petervo** [comment]
Let's keep this open for now, was mostly happening on fedora 27 which we aren't running much yet
