### ISSUE TITLE
unrelated SELinux denial: NetworkManager cannot run arping

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#7621]
On rhel-7 and rhel-7-4 images, at least on the rhel-7.4 branch, [test/verify/check-connection TestConnection.testSocketPort](https://fedorapeople.org/groups/cockpit/logs/pull-7604-20170906-093838-33595476-verify-rhel-7/log.html#55) reliably fails due to an unrelated SELinux denial:
```
Unexpected journal message 'type=1400 audit(1504691627.225:6): avc:  denied  { execute } for  pid=530 comm="NetworkManager" name="arping" dev="vda3" ino=229246 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file'
```

It was previously reported against Fedora (https://bugzilla.redhat.com/show_bug.cgi?id=1442132), I now reported it against RHEL 7.4 too (https://bugzilla.redhat.com/show_bug.cgi?id=1488831).

**Comment by martinpitt** [comment]
verify/rhel-7-4
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 537, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 699, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1504693144.282:4): avc:  denied  { execute } for  pid=530 comm="NetworkManager" name="arping" dev="vda3" ino=229246 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```
First occurrence: 2017-09-06T12:19:06.430269
Times recorded: 1
Latest occurrences:

- 2017-09-06T12:19:06.430269

**Comment by cockpituous** [comment]
verify/rhel-7
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "testlib.py", line 537, in tearDown
    self.check_journal_messages()
  File "testlib.py", line 699, in check_journal_messages
    raise Error(first)
Error: type=1400 audit(1505751551.685:4): avc:  denied  { execute } for  pid=530 comm="NetworkManager" name="arping" dev="vda3" ino=229246 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
```
First occurrence: 2017-09-18T16:19:14.805321 | revision bb4e1eaec745b817ab8af41a42a8445408132c25, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7705-20170918-160404-bb4e1eae-verify-rhel-7/log.html)
Times recorded: 1
Latest occurrences:

- 2017-09-18T16:19:14.805321 | revision bb4e1eaec745b817ab8af41a42a8445408132c25, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7705-20170918-160404-bb4e1eae-verify-rhel-7/log.html)
