### ISSUE TITLE
kubernetes: Enhancing kubernetes plugin to support KubeVirt

### ISSUE THREAD

**Issue by jniederm** [cockpit-project/cockpit#7631]
I'd like to add support for [KubeVirt][1] project to kubernetes plugin.

KubeVirt is a libvirt virtual machine management add-on for Kubernetes. It adds new Kubernetes resource "vms" allowing to deploy VMs in a similar way to pods. VMs are actually run inside containers ([KubeVirt architecture][2]).

The enhancements should help users to manage and troubleshoot KubeVirt VMs to a similar extent current plugin does for Kubernetes.

All enhancements should be conditionally enabled only in case KubeVirt is installed on connected Kubernetes instance.

It would be nice to allow users to

* visually distinguish KubeVirt related resources, especially pods and containers and allow filtering based on that feature. KubeVirt deploys several infrastructure pods on master and regular nodes. Next to these actual virtual machine pods and regular pods are run. The UI could help user to answer questions like: Is KubeVirt infrastructure running ok? Are my VMs running ok? Are my regular pods running ok? What node is a VM running at?

* view all deployed virtual machines in KubeVirt/Kubernetes cluster in one table, perhaps in new "Virtual Machines" tab for global overview. Each row corresponding to one VM would provide basic info like "Name" (libvirt name), "Status" (libvirt status), "Node" the VM is running at, similarly to "Containers" tab. Expanded area can show logs and hyperlinks to related entities: Nodes, Pods, Containers and "machines" plugin on relevant node cockpit instance. Such table should help user to get global overview of VMs (similar to `kubectl get vms`), inspect error state in logs and easily navigate to relevant entities when troubleshooting is needed.

What do you guys think?

Cc: @fabiand @rmohr @michalskrivanek @jelkosz

[1]: http://kubevirt.io
[2]: https://github.com/kubevirt/kubevirt/blob/master/docs/architecture.md

**Comment by petervo** [comment]
How visually similar should this be compared the current kubernetes vs the machines module that currently deals with virtual machines on a single host? Are there parts of that you'd think should be reused?

**Comment by jelkosz** [comment]
@petervo It is meant as an extension of this plugins. So it would not be a different plugin, it would just add some features here and there (as explained in the comment) to teach this two plugins to understand also kubevirt vms.

**Comment by petervo** [comment]
The first step would be to make a wiki page here, you can use https://github.com/cockpit-project/cockpit/wiki/Feature-template as a starting point. We should start with user stories related to what we'd expect users to be able to do. We can discuss there initially, then once we have some solid user stories the next step would be to put together some mockups for what this should look like.

I'm going to close this issue as I don't think an issue is the best way to design and collaborate on a large feature like this. But please do open the feature wiki page and we'll get started figuring things out there.

**Comment by jniederm** [comment]
[KubeVirt support enhancements][1] feature page posted.

[1]: https://github.com/cockpit-project/cockpit/wiki/Feature:-Kubernetes:-KubeVirt-support-enhancements
