### ISSUE TITLE
add labels to elements in the topology graph

### ISSUE THREAD

**Issue by bw2** [cockpit-project/cockpit#7632]
I'd like to share the topology view in presentations, but it's not particularly useful without labels. 

It would be great if there was a way to show labels by default, or toggle them on/off.

**Comment by petervo** [comment]
Hovering over an item shows a label, clicking on a item should show details about it. We've gotten feedback that it's already pretty crowded, so I'm hesitant to add anything else to it.
There was a regression recently that make the clicking functionality not work. If you pull the latest from docker it should be fixed.

@andreasn WDYT?

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
