### ISSUE TITLE
System rendered un-bootable by storage component

### ISSUE THREAD

**Issue by jonathanunderwood** [cockpit-project/cockpit#7639]
Before I get stuck in: cockpit is a thing of beauty, thanks for the great work on this.

I have a freshly installed Fedora 26 system that I am running cockpit on. In this system I have added, since the install, 2 disks that I've set up to be a raid1 array (mdraid), with a luks encrypted volume layered on top, with an ext4 filesystem on top of that. This storage array was intentionally added after install, and is not mounted at boot, as I don't wish to store my passphrase/key on the machine.

So, although normally I happily unlock and mount this storage volume as needed, today I was exploring cockpit's storage control. Through cockpit I:

* Unlocked the volume with the passphrase
* Mounted the ext4 volume, at a custom location (/mnt/data0)

This all works fine and essentially is what I'd normally do via the command line, and I was enjoying the cockpit experience. 

But then I rebooted, and my system dropped into the recovery console. A bit freaked out, I debugged what was going on quite quickly - cockpit had added an entry to /etc/fstab such that the system now tried to mount the storage volume at boot, and of course fails.

This was really unexpected - I didn't ask for, nor expect an entry to be added to /etc/fstab. This really isn't a great user experience - I don't think cockpit should be blindly adding fstab entries. In this case, if it was REALLY going to add an fstab entry, it should also have created an /etc/crypttab entry as well.

I really think this is a bit of a misfeature - at the least, it should be up to the user to decide if you want a permanent mount entry creating. And if it does, it needs to create one that works (by also managing /etc/crypttab as well).

**Comment by jonathanunderwood** [comment]
In case it's useful, the fstab entry it created was:

UUID=ca1a7e4c-d87d-483e-a2e7-5291cff63bf5 /mnt/data0 auto defaults,x-parent=33711224-8c27-4019-9c69-1c3e64564396,x-parent=b2bcbd89:7c42d4b8:159dde4d:f7123704 0 0


(where some of the UUIDs have been changed by me for obscurity).

**Comment by petervo** [comment]
@andreasn @mvollmer anything we can do make it clear that this is what will happen, or maybe a way  to opt out of the fstab changes?

**Comment by mvollmer** [comment]
> * Mounted the ext4 volume, at a custom location (/mnt/data0)

This is what has created the fstab entry.  There is no way with the UDisks2 API to mount a filesystem in a specific location without also writing to fstab.  (It's very desktopy in this regard.)

You could have included "noauto" in the mount options, but if you weren't aware that the dialog is for creating a fstab entry, you wouldn't think of that.  (And the crypttab entry would still be missing.)

We have plans to improve this somewhat: https://trello.com/c/1ws6qXYt/365-storage-more-control-over-mounting, and I'll bump the priority of it.

> I really think this is a bit of a misfeature - at the least, it should be up to the user to decide if you want a permanent mount entry creating. And if it does, it needs to create one that works (by also managing /etc/crypttab as well).

Agreed.

I think we have these things to do:

- Write a basic crypttab entry when writing a fstab entry for a encrypted fsys.  We should probably copy the noauto option.  I think this is straighforward.

- Make mounting more serverish, with a clearer distinction between run-time vs config state.  This needs design.

**Comment by mvollmer** [comment]
Also, just having a text entry for "Mount Options" is bad, of course.  If there would have been a "[ ] Mount at boot" checkbox, you would probably understood what's going on.

**Comment by mvollmer** [comment]
> Before I get stuck in: cockpit is a thing of beauty, thanks for the great work on this.

And thanks for the kind words! *blush*

**Comment by martinpitt** [comment]
FTR, I agree about at least setting the `noauto` option by default. That mirrors other dynamic mounts that udisks does (i. e. with the default mount point), as they are not even persistent and thus not `auto`.

It would be nice to turn mount options into check boxes so that it's more obvious. These should also offer `nofail`, which is useful for "optional" mounts which should still be attempted at boot.

**Comment by jonathanunderwood** [comment]
Yes, I like @martinpitt 's notion of check boxes. I'd love to see:

[ ] Store passphrase on system
[ ] Mount automatically at boot

options, where:
* Selecting "Store passphrase on system" ensures creation of an entry in /etc/crypttab
* Selecting "Mount automatically at boot" ensures an entry in /etc/fstab
* Not selecting "Mount automatically at boot" means no /etc/fstab entry is created - I get that udisks2 will always create an entry when asked to mount, but it should be possible to remove it.
* Selecting "Mount automatically at boot" would also auto-select "Store passphrase on system".

**Comment by mvollmer** [comment]
> Yes, I like @martinpitt 's notion of check boxes.

Yes, I agree.  There are many ways to shoot yourself in the foot when configuring your storage, and the fundamental problem here was that you weren't aware that a fstab entry is going to be written.  Adding the checkboxes will hopefully make that obvious. 

> I'd love to see:
>
> [ ] Store passphrase on system
> [ ] Mount automatically at boot

We already have the "Store passphrase on system" option.  However, crypto options are separate from fsys options right now.  It's an open task to try to unify them somehow: https://trello.com/c/UerTOQM5/366-storage-maybe-merge-encryption-and-filesys-tabs

I'll start by making the "Mount automatically at boot" option explicit.

Cockpit will still let the user set them incorrectly (e.g., crypto backing device is noauto, fsys cleartext is auto).

**Comment by mvollmer** [comment]
Here is something: https://github.com/cockpit-project/cockpit/pull/7750

It makes it harder to end up with broken options during filesystem creation, but wouldn't directly help in this scenario.  However, the presence of a "[x] Mount automatically at boot" checkbox is hopefully enough to catch people's attention.

**Comment by mvollmer** [comment]
I think this can be closed, actually,
