### ISSUE TITLE
Ubuntu 16

### ISSUE THREAD

**Issue by gzcwnk** [cockpit-project/cockpit#7651]
Since I cant login as root for Ubuntu, how do I make cockpit up to root privileges?

**Comment by martinpitt** [comment]
Indeed Ubuntu disables the root account by default, but at least the user that gets created during installation has `sudo` permissions. Cockpit can use these. When logging into Cockpit, you have to make sure that the "[X] Reuse my password for privileged tasks" check box is enabled, then Cockpit will use sudo just like you would on the command line.
