### ISSUE TITLE
RHEL7 - cockpit

### ISSUE THREAD

**Issue by gzcwnk** [cockpit-project/cockpit#7652]
It seems a lot of cockpit's functionality is missing in RHEL7.  Is there a repo I can add to pick up the full set of modules?

**Comment by martinpitt** [comment]
There are some modules in Extras which you can install separately, namely the Dashboard, Storage, Containers, and "cockpit-pcp" for more detailled metrics. These don't get installed with just the metapackage (`yum install cockpit`). Which functionality in particular are you looking for?

**Comment by gzcwnk** [comment]
I think its dashboard? so I can add more servers. Its there on debian9 but missing in rhel7.

**Comment by gzcwnk** [comment]
I did a yum whatprovides cockpit* and dashboard didnt turn up, I'll check further in the morning.

**Comment by martinpitt** [comment]
You might need to enable the "Extras" repository first?

**Comment by stefwalter** [comment]
No reply from @gzcwnk ... closing this issue.
