### ISSUE TITLE
storage and networking link issues

### ISSUE THREAD

**Issue by doverride** [cockpit-project/cockpit#7654]
1. on the system screen there are links "Disk I/O" and "Network Traffic". These links only work if cockpit-storaged and cockpit-networkmanager are installed respectively

2. if you are connected to remote nodes from a local session, and in a remote host tab click the "Disk I/O" and "Network Traffic" links, then you are directed to the "Storage"  and "Networking" section of the local host instead of the "Storage"  and "Networking" section of the remote node respecitively.

**Comment by petervo** [comment]
1) This is somewhat expected. There's not really a quick fix for it as generally most apps are not really aware of what other apps are installed. But there is probably something we can do here, there are also other places in cockpit that might have similar issues.

2) I'll open a PR to fix.

**Comment by doverride** [comment]
On Tue, Sep 12, 2017 at 05:43:36PM -0700, petervo wrote:
> 1) This is somewhat expected. There's not really a quick fix for it as generally most apps are not really aware of what other apps are installed. But there is probably something we can do here, there are also other places in cockpit that might have similar issues.

Understood. Maybe instead a page with a message "component not available" instead of letting it return "page not found" is a bit nicer

> 
> 2) I'll open a PR to fix.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/cockpit-project/cockpit/issues/7654#issuecomment-329024488

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by stefwalter** [comment]
Another fix for (2) is planned here: https://trello.com/c/7WuCtGti/550-base-make-cockpitjump-jump-to-defaulthost-by-default

**Comment by KKoukiou** [comment]
Fixed by #11040
