### ISSUE TITLE
RFE: Display problems for containers

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#7655]
Opening this issue to get some feedback on this RFE:
https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/thread/RG77UQSOTBPSTJJSG7Q6X55JOM7OD6IF/

Any comments, ideas?

**Comment by petervo** [comment]
I think discussion has gotten started on the ML so closing this and let it happen there.
