### ISSUE TITLE
Channeled process not killed on closing

### ISSUE THREAD

**Issue by spbnick** [cockpit-project/cockpit#7656]
If a channel to a process is opened and then closed without an argument to the `close` function, the process stays running and is not killed.

### Reproduction
In JavaScript console:

    c1 = cockpit.channel({"payload":"stream", "spawn":["/bin/sleep", "1000"]})
    c1.close()
    c2 = cockpit.channel({"payload":"stream", "spawn":["/bin/sleep", "2000"]})
    c2.close("terminated")

On host:

    ps auxf|grep sleep

The output is:

     6135 ?        S      0:00 /bin/sleep 1000
     6146 pts/0    S+     0:00 grep --color=auto sleep

Should be:

     6146 pts/0    S+     0:00 grep --color=auto sleep

**Comment by stefwalter** [comment]
The stdin of the process is closed when you call ```.close()```. For most command line utilities this triggers an orderly shutdown of the process. Try the above example with ```cat```:

```
c3 = cockpit.channel({"payload":"stream", "spawn":["cat"]})
c3.close()
```

And on the host:

```
$ ps -xa | grep -w cat
20233 pts/2    S+     0:00 grep --color=auto -w cat

```

By using a reason error code like ```.close("terminate")```, then cockpit-bridge will send the process a ```SIGTERM```.

If you wish to terminate the process with a signal, specify

**Comment by spbnick** [comment]
Thanks, Stef! That's fine, but it's a bug unless documented ;)
