### ISSUE TITLE
ovirt: implement 'shut down' via libvirt for troubleshooting

### ISSUE THREAD

**Issue by mareklibra** [cockpit-project/cockpit#7670]
In pkg/ovirt, implement virtual machine's `shut down` action via direct Libvirt call in addition to recent oVirt's API call.

The libvirt's version for VM shut down is meant for trouble shooting, so the user can politely shut down particular VM even if connection to oVirt API is not working.

To connect to Libvirt for active action, use 

    qemu+tls://[HOSTNAME]/system

As a fall back

    qemu+tcp://[HOSTNAME]/system

might be used as well, but the first option is better since it respects permissions.
The user logged-in has to have access to Libvirt's certificate.

This rescue-URI shall be configurable in `/etc/cockpit/machines-ovirt.config` with default set as mentioned above.

We can rely on the fact that a properly configured oVirt host has `hostname -f` set correctly.

---

[  ]  Shut Down via Libvirt
[  ]  Send NMI via Libvirt

---
This is a followup for #7139

**Comment by mareklibra** [comment]
@garrett , any suggestion how to do it from UI perspective?

**More insight:**
For an oVirt-managed virtual machine, the action like `shut down` shall be normally routed to oVirt enegine instead of shutting it down just locally via Libvirt.

Anyway, in case the oVirt engine happens to be inaccessible or even a bug might happen somewhere, the user shall be able to turn it off locally, so there shall be still an option to route the action to local Libvirt instead of the oVirt engine.

In such scenario, the VM gets a chance to gracefully clean its processes before exiting its qemu process so at least the "business function" is ended properly.

We might i.e. show a confirmation dialog which happens to have a check-box denoting to perform the action just locally (unchecked by default).

Or we can add new action to the `Shut Down` dropdown box. This seems to me confusing, anyway. We have already `Shut Down`, `Force Shut Down`, `Send NMI` there.

I was considering to perform this "local" routing once the preceding oVirt call fails. This would be usually possible but is not 100% reliable, there might be still marginal cases where the action passes but the VM is still up.

What do you think?

**Comment by garrett** [comment]
When a VM is managed by oVirt, in most circumstances, you'd want to shut down VMs via oVirt, correct? And you'd only resort to shutting things down with libvirt if the oVirt method fails, right?

For oVirt VMs, would it make sense to change the "Shut Down" action to be the oVirt shutdown? And then "Force Shut Down" would remain the libvirt shutdown method?

Questions:

1. Would these two methods ("Shut Down" changed to oVirt shutdown plus the normal "Force Shut Down") handle the cases fine?
2. Is there any reason why someone would want to trigger the non-forceful libvirt shutdown method on an oVirt managed VM?

**Comment by mareklibra** [comment]
> When a VM is managed by oVirt, in most circumstances, you'd want to shut down VMs via oVirt, correct? 

Right.

> And you'd only resort to shutting things down with libvirt if the oVirt method fails, right?

Right.

> For oVirt VMs, would it make sense to change the "Shut Down" action to be the oVirt shutdown?

Yes, it's recent state already.

> And then "Force Shut Down" would remain the libvirt shutdown method?

Thanks to nature of this particular action, I think there might be no harm in calling `Force Shut Down` directly via Libvirt. 
Anyway, generally speaking - all such actions shall be routed to oVirt first, since it's cleaner. The higher-level management application (oVirt) is immediately informed about the change and not just by backward detection. This might affect auditing, error handling on cluster level, scheduling, proper logging for issue backtracking, etc.

There's rule in oVirt, the user or anything should not manipulate the VMs directly while by-passing the engine. This is exactly the reason why Libvirt access is secured on an oVirt host - to discourage anyone accessing Libvirt directly.

> Questions:
>
> 1. Would these two methods ("Shut Down" changed to oVirt shutdown plus the normal "Force Shut Down") handle the cases fine?

`Force Shut Down` via Libvirt - probably no big harm, see above. But I still think that involving oVirt is the better option.

`Shut Down` - in case of issues (as mentioned lost connection to oVirt, bug on any of the many layers, etc) there shall be still possibility to gracefully shut-down the VM no matter how difficult it might be to detect proper state for oVirt afterwards.
It's corner case, but cockpit-ovirt is meant for troubleshooting.

Due to multiple reasons, I would like to avoid client-side detection whether `Shut Down` via oVirt finished successfully to issue the libvirt call automatically. I would keep this decision/detection on user.

**Comment by mareklibra** [comment]
Send NMI action should be added same way

**Comment by mareklibra** [comment]
Send NMI #9226 is merged - adding workaround of `qemu+tls:///` connection URI.
So the other "write" action should work now as well.

Remains: add extra step for oVirt-managed VMs in calling oVirt API first. In case of failure, direct libvirt call is executed after user confirmation.

**Comment by KKoukiou** [comment]
@mareklibra @michalskrivanek checking if this one is still valid a part of generic issue cleanup. TBH I don't see the importance for it, and also this RFE is outside of the scope of the ovirt plugin functionality.

**Comment by michalskrivanek** [comment]
indeed it's not too important. It was always rather a nice to have

**Comment by KKoukiou** [comment]
I always considered the cockpit-ovirt a UI for deploying hosted engine. And I think this is out of this use case. Anyway, I can leave this open and we can discuss this in cockpit hackfest.

**Comment by marusak** [comment]
ovirt plugin is not maintained in upstream anymore. If this issue is still valid and you want to get it fixed, please open downstream (bugzilla) bug.
