### ISSUE TITLE
kubernetes: Consider renaming "Connection Error" dialog window

### ISSUE THREAD

**Issue by jniederm** [cockpit-project/cockpit#7684]
If there is no server configuration and "Troubleshoot" button is clicked, new dialog window pops up called "Connection Error". Maybe "New server connection" or "Server connections" would be more descriptive, since main purpose of the window is to allow user to enter new server details rather than give him/her details regarding connection error.

version: master, commit 6befb5a5

Steps to reproduce:
1. run cockpit form the vagrant image
2. make sure `/root/.kube/config` doesn't exist
3. log in using `root:foobar`
4. select Cluster tab
5. click Troubleshoot button

![image](https://user-images.githubusercontent.com/5278760/30462473-35aa8132-99c6-11e7-85dc-2b82a9400d27.png)

![image](https://user-images.githubusercontent.com/5278760/30462480-3fbc048e-99c6-11e7-93d8-dc432e272e26.png)

**Comment by petervo** [comment]
The dialog is used alot more than the first time someone logs on. 'Connection error' is the right thing to say a lot of times when you've already configured things or expect kube to be running and just work on localhost. So I'd stay away from anything with add. I don't mind 'Server connection' though. @andreasn WDYT?

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
