### ISSUE TITLE
cockpit created boot timers are broken on RHEL 7.4

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#7710]
See downstream bug https://bugzilla.redhat.com/show_bug.cgi?id=1478832 for details. This was fixed upstream in version 139 and is being backported to RHEL 7.4 in PR #7705. Until then, the boot timer test will [fail](https://fedorapeople.org/groups/cockpit/logs/pull-7705-20170919-063636-bb4e1eae-verify-rhel-7-4/log.html#45):
```
# testCreateTimer (check_services.TestServices)
#
Killed by signal 15.
not ok 45 testCreateTimer (check_services.TestServices) duration: 93s
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-services", line 478, in testCreateTimer
    m.execute("while [ ! -f /tmp/hello ] ; do sleep 0.5; done")
  File "/build/cockpit/test/common/testvm.py", line 385, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit/test/common/testvm.py", line 83, in handle_timeout
    raise Exception(self.error_message)
Exception: Timeout while waiting for boot timer to run
```

**Comment by martinpitt** [comment]
verify/rhel-7-4
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "test/verify/check-services", line 478, in testCreateTimer
    m.execute("while [ ! -f /tmp/hello ] ; do sleep 0.5; done")
  File "/home/martin/upstream/cockpit/test/common/testvm.py", line 439, in execute
    ret = select.select(rset, wset, [], 10)
  File "/home/martin/upstream/cockpit/test/common/testvm.py", line 80, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timeout while waiting for boot timer to run
```
First occurrence: 2017-09-19T11:34:06.569988
Times recorded: 1
Latest occurrences:

- 2017-09-19T11:34:06.569988

**Comment by cockpituous** [comment]
verify/rhel-7-4
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-services", line 478, in testCreateTimer
    m.execute("while [ ! -f /tmp/hello ] ; do sleep 0.5; done")
  File "/build/cockpit/test/common/testvm.py", line 439, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit/test/common/testvm.py", line 80, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timeout while waiting for boot timer to run
```
First occurrence: 2017-09-26T08:43:10.223929 | revision 9e2c6d807183e2fb904eda955fd90471e45c03c4, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7725-20170926-082020-9e2c6d80-verify-rhel-7-4/log.html)
Times recorded: 1
Latest occurrences:

- 2017-09-26T08:43:10.223929 | revision 9e2c6d807183e2fb904eda955fd90471e45c03c4, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7725-20170926-082020-9e2c6d80-verify-rhel-7-4/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7-4
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-services", line 478, in testCreateTimer
    m.execute("while [ ! -f /tmp/hello ] ; do sleep 0.5; done")
  File "/build/cockpit/test/common/testvm.py", line 439, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit/test/common/testvm.py", line 80, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timeout while waiting for boot timer to run
```
First occurrence: 2017-09-27T15:20:23.527139 | revision 21dd0ad211efacc31c21bf120e584dd797a5c0ca, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7482-20170927-151010-21dd0ad2-verify-rhel-7-4/log.html)
Times recorded: 1
Latest occurrences:

- 2017-09-27T15:20:23.527139 | revision 21dd0ad211efacc31c21bf120e584dd797a5c0ca, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7482-20170927-151010-21dd0ad2-verify-rhel-7-4/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7-4
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-services", line 478, in testCreateTimer
    m.execute("while [ ! -f /tmp/hello ] ; do sleep 0.5; done")
  File "/build/cockpit/test/common/testvm.py", line 439, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit/test/common/testvm.py", line 80, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timeout while waiting for boot timer to run
```
First occurrence: 2017-10-02T06:59:51.687319 | revision 456cadcc2920e025379bc978b9ed95057f433a17, [logs](http://fedorapeople.org/groups/cockpit/logs/master-20171002-064141-456cadcc-verify-rhel-7-4/log.html)
Times recorded: 1
Latest occurrences:

- 2017-10-02T06:59:51.687319 | revision 456cadcc2920e025379bc978b9ed95057f433a17, [logs](http://fedorapeople.org/groups/cockpit/logs/master-20171002-064141-456cadcc-verify-rhel-7-4/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7-4
Ooops, it happened again<hr>
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-services", line 478, in testCreateTimer
    m.execute("while [ ! -f /tmp/hello ] ; do sleep 0.5; done")
  File "/build/cockpit/test/common/testvm.py", line 439, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit/test/common/testvm.py", line 80, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timeout while waiting for boot timer to run
```
First occurrence: 2017-10-05T12:16:18.186650 | revision 1e1438a4836350cfd8191ca71651d0422c33ce9e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7482-20171005-120606-1e1438a4-verify-rhel-7-4/log.html)
Times recorded: 1
Latest occurrences:

- 2017-10-05T12:16:18.186650 | revision 1e1438a4836350cfd8191ca71651d0422c33ce9e, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7482-20171005-120606-1e1438a4-verify-rhel-7-4/log.html)

**Comment by harishanand95** [comment]
@martinpitt I wrote the code for the timers including the test cases. https://github.com/cockpit-project/cockpit/pull/4645
I would be glad to contribute fixes. But I do not know why this error is happening. :confused:

The initial plan we had for creation and modification of timers was to use systemd dbus (by creating persistent units). Since Dbus didn't have that functionality to create persistent units, we choose to write timer files directly.
I think the creation of persistent units using systemd dbus is still pending. https://github.com/systemd/systemd/issues/3234

CC: @dperpeet

**Comment by martinpitt** [comment]
@harishanand95 : Please don't worry about this particular issue. This only exists to track the (known) failure of  timers in current RHEL 7.4.1 base. It is fixed upstream and will be fixed in RHEL 7.4.2 too (see https://bugzilla.redhat.com/show_bug.cgi?id=1478832).

These "knownissues" labelled issues are just for housekeeping in our test suite and are not "real" outstanding Cockpit bugs.

**Comment by harishanand95** [comment]
ohh okay. thank you!!

**Comment by cockpituous** [comment]
verify/rhel-7-4
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateTimer (check_services.TestServices)
#
Warning: Permanently added '[127.0.0.2]:2501' (ECDSA) to the list of known hosts.
Warning: Permanently added '[127.0.0.2]:2501' (ECDSA) to the list of known hosts.
Connection to 127.0.0.2 closed by remote host.
Warning: Permanently added '[127.0.0.2]:2501' (ECDSA) to the list of known hosts.
Killed by signal 15.
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-services", line 478, in testCreateTimer
    m.execute("while [ ! -f /tmp/hello ] ; do sleep 0.5; done")
  File "/build/cockpit/test/common/testvm.py", line 439, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit/test/common/testvm.py", line 80, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timeout while waiting for boot timer to run

not ok 84 testCreateTimer (check_services.TestServices) # duration: 110s
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2501-FAIL.png
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2501-FAIL.html
```
First occurrence: 2017-10-07T19:32:27.532528 | revision 26e3c37177095425353b3e40b09e6f96f481668a, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7702-20171007-191414-26e3c371-verify-rhel-7-4/log.html)
Times recorded: 1
Latest occurrences:

- 2017-10-07T19:32:27.532528 | revision 26e3c37177095425353b3e40b09e6f96f481668a, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7702-20171007-191414-26e3c371-verify-rhel-7-4/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7-4
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateTimer (check_services.TestServices)
#
Warning: Permanently added '[127.0.0.2]:2501' (ECDSA) to the list of known hosts.
Warning: Permanently added '[127.0.0.2]:2501' (ECDSA) to the list of known hosts.
Killed by signal 15.
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-services", line 478, in testCreateTimer
    m.execute("while [ ! -f /tmp/hello ] ; do sleep 0.5; done")
  File "/build/cockpit/test/common/testvm.py", line 439, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit/test/common/testvm.py", line 80, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timeout while waiting for boot timer to run

not ok 72 testCreateTimer (check_services.TestServices) # duration: 104s
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2501-FAIL.png
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2501-FAIL.html
```
First occurrence: 2017-10-11T09:12:00.151598 | revision bfa057f228e93b21668c74e2e39a738a488f63b1, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7861-20171011-085454-bfa057f2-verify-rhel-7-4/log.html)
Times recorded: 1
Latest occurrences:

- 2017-10-11T09:12:00.151598 | revision bfa057f228e93b21668c74e2e39a738a488f63b1, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7861-20171011-085454-bfa057f2-verify-rhel-7-4/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7-4
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateTimer (check_services.TestServices)
#
Warning: Permanently added '[127.0.0.2]:2501' (ECDSA) to the list of known hosts.
Warning: Permanently added '[127.0.0.2]:2501' (ECDSA) to the list of known hosts.
Warning: Permanently added '[127.0.0.2]:2501' (ECDSA) to the list of known hosts.
Warning: Permanently added '[127.0.0.2]:2501' (ECDSA) to the list of known hosts.
Warning: Permanently added '[127.0.0.2]:2501' (ECDSA) to the list of known hosts.
Killed by signal 15.
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-services", line 478, in testCreateTimer
    m.execute("while [ ! -f /tmp/hello ] ; do sleep 0.5; done")
  File "/build/cockpit/test/common/testvm.py", line 439, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit/test/common/testvm.py", line 80, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timeout while waiting for boot timer to run

not ok 68 testCreateTimer (check_services.TestServices) # duration: 67s
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2501-FAIL.png
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2501-FAIL.html
```
First occurrence: 2017-10-13T07:51:27.787150 | revision bedf82abc06616ef931499b868f026a6f3eddc00, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7876-20171013-072727-bedf82ab-verify-rhel-7-4/log.html)
Times recorded: 1
Latest occurrences:

- 2017-10-13T07:51:27.787150 | revision bedf82abc06616ef931499b868f026a6f3eddc00, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7876-20171013-072727-bedf82ab-verify-rhel-7-4/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7-4
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateTimer (check_services.TestServices)
#
Warning: Permanently added '[127.0.0.2]:2601' (ECDSA) to the list of known hosts.
Warning: Permanently added '[127.0.0.2]:2601' (ECDSA) to the list of known hosts.
Connection closed by 127.0.0.2 port 2601
Warning: Permanently added '[127.0.0.2]:2601' (ECDSA) to the list of known hosts.
Killed by signal 15.
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-services", line 478, in testCreateTimer
    m.execute("while [ ! -f /tmp/hello ] ; do sleep 0.5; done")
  File "/build/cockpit/test/common/testvm.py", line 439, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit/test/common/testvm.py", line 80, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timeout while waiting for boot timer to run

not ok 84 testCreateTimer (check_services.TestServices) # duration: 105s
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2601-FAIL.png
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2601-FAIL.html
```
First occurrence: 2017-10-17T09:07:49.118666 | revision 4779073d81f7878a9c2a9eec742838557a6425ea, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7892-20171017-084949-4779073d-verify-rhel-7-4/log.html)
Times recorded: 1
Latest occurrences:

- 2017-10-17T09:07:49.118666 | revision 4779073d81f7878a9c2a9eec742838557a6425ea, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7892-20171017-084949-4779073d-verify-rhel-7-4/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7-4
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateTimer (check_services.TestServices)
#
Warning: Permanently added '[127.0.0.2]:2601' (ECDSA) to the list of known hosts.
Warning: Permanently added '[127.0.0.2]:2601' (ECDSA) to the list of known hosts.
Connection to 127.0.0.2 closed by remote host.
Warning: Permanently added '[127.0.0.2]:2601' (ECDSA) to the list of known hosts.
Killed by signal 15.
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-services", line 478, in testCreateTimer
    m.execute("while [ ! -f /tmp/hello ] ; do sleep 0.5; done")
  File "/build/cockpit/test/common/testvm.py", line 439, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit/test/common/testvm.py", line 80, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timeout while waiting for boot timer to run

not ok 84 testCreateTimer (check_services.TestServices) # duration: 108s
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2601-FAIL.png
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2601-FAIL.html
```
First occurrence: 2017-10-17T22:11:23.627874 | revision 4545c2dba0e5d903a3886fb529042c0b8713bb49, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7900-20171017-215252-4545c2db-verify-rhel-7-4/log.html)
Times recorded: 1
Latest occurrences:

- 2017-10-17T22:11:23.627874 | revision 4545c2dba0e5d903a3886fb529042c0b8713bb49, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7900-20171017-215252-4545c2db-verify-rhel-7-4/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7-4
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateTimer (check_services.TestServices)
#
Warning: Permanently added '[127.0.0.2]:2701' (ECDSA) to the list of known hosts.
Warning: Permanently added '[127.0.0.2]:2701' (ECDSA) to the list of known hosts.
Connection to 127.0.0.2 closed by remote host.
Warning: Permanently added '[127.0.0.2]:2701' (ECDSA) to the list of known hosts.
Killed by signal 15.
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-services", line 478, in testCreateTimer
    m.execute("while [ ! -f /tmp/hello ] ; do sleep 0.5; done")
  File "/build/cockpit/test/common/testvm.py", line 439, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit/test/common/testvm.py", line 80, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timeout while waiting for boot timer to run

not ok 84 testCreateTimer (check_services.TestServices) # duration: 100s
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2701-FAIL.png
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2701-FAIL.html
```
First occurrence: 2017-10-19T07:41:47.807109 | revision 82db13e16f832d2197183b8e2b25ee7b48069d25, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7750-20171019-072626-82db13e1-verify-rhel-7-4/log.html)
Times recorded: 1
Latest occurrences:

- 2017-10-19T07:41:47.807109 | revision 82db13e16f832d2197183b8e2b25ee7b48069d25, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7750-20171019-072626-82db13e1-verify-rhel-7-4/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7-4
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateTimer (check_services.TestServices)
#
Warning: Permanently added '[127.0.0.2]:2701' (ECDSA) to the list of known hosts.
Warning: Permanently added '[127.0.0.2]:2701' (ECDSA) to the list of known hosts.
Connection to 127.0.0.2 closed by remote host.
Warning: Permanently added '[127.0.0.2]:2701' (ECDSA) to the list of known hosts.
Killed by signal 15.
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-services", line 478, in testCreateTimer
    m.execute("while [ ! -f /tmp/hello ] ; do sleep 0.5; done")
  File "/build/cockpit/test/common/testvm.py", line 439, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit/test/common/testvm.py", line 80, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timeout while waiting for boot timer to run

not ok 83 testCreateTimer (check_services.TestServices) # duration: 105s
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2701-FAIL.png
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2701-FAIL.html
```
First occurrence: 2017-10-20T13:18:30.375725 | revision 687190c370d17051a3136e31c503490c4d967fd8, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7926-20171020-125757-687190c3-verify-rhel-7-4/log.html)
Times recorded: 1
Latest occurrences:

- 2017-10-20T13:18:30.375725 | revision 687190c370d17051a3136e31c503490c4d967fd8, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7926-20171020-125757-687190c3-verify-rhel-7-4/log.html)

**Comment by cockpituous** [comment]
verify/rhel-7-4
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateTimer (check_services.TestServices)
#
Warning: Permanently added '[127.0.0.2]:2301' (ECDSA) to the list of known hosts.
Warning: Permanently added '[127.0.0.2]:2301' (ECDSA) to the list of known hosts.
Killed by signal 15.
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-services", line 478, in testCreateTimer
    m.execute("while [ ! -f /tmp/hello ] ; do sleep 0.5; done")
  File "/build/cockpit/test/common/testvm.py", line 439, in execute
    ret = select.select(rset, wset, [], 10)
  File "/build/cockpit/test/common/testvm.py", line 80, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timeout while waiting for boot timer to run

not ok 84 testCreateTimer (check_services.TestServices) # duration: 151s
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2301-FAIL.png
Wrote TestServices-testCreateTimer-rhel-7-4-127.0.0.2-2301-FAIL.html
```
First occurrence: 2017-10-23T20:25:20.280871 | revision 1865a4fd8242b3f949c470fa62c20cd884f606f6, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7934-20171023-200303-1865a4fd-verify-rhel-7-4/log.html)
Times recorded: 1
Latest occurrences:

- 2017-10-23T20:25:20.280871 | revision 1865a4fd8242b3f949c470fa62c20cd884f606f6, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-7934-20171023-200303-1865a4fd-verify-rhel-7-4/log.html)
