### ISSUE TITLE
ovirt: Allow change of registered oVirt FQDN

### ISSUE THREAD

**Issue by mareklibra** [cockpit-project/cockpit#7724]
Within pkg/ovirt, the user shall be able to change the registered oVirt engine address.

Recently, the FQDN and PORT are stored in `/etc/cockpit/machines-ovirt.config`, effective for all cockpit-users.
Even non-root user shall be able to edit oVirt connection for him-self, so some user-specific configuration should be involved.

Storage of user-specific configuration is still for decision:
- either window.localStorage
- or in home directory

Followup for #7139

**Comment by KKoukiou** [comment]
@mareklibra @michalskrivanek we are doing an issue cleanup. Is this still valid? If yes is anyone from RHV planning to work on this? Otherwise I 'll close this issue as won't do since the plugin is not actively developed anyway.

**Comment by michalskrivanek** [comment]
@KKoukiou it can be closed, it's not anything people do often at all
