### ISSUE TITLE
Allow using separate files for certificate and key in /etc/cockpit/ws-certs.d

### ISSUE THREAD

**Issue by ibotty** [cockpit-project/cockpit#7763]
According to [the latest cockpit guide](http://cockpit-project.org/guide/latest/https.html), it's not possible to separate the used SSL key and certificate into different files.

I am deploying cockpit as registry-console on openshift, but use openshift generated service certificates (to use a reasonable reencrypt route). For now, I have to use an init container that does `cat /run/secrets/registry-console-certs/tls.crt /run/secrets/registry-console-certs/tls.key > /etc/cockpit/ws-certs.d/01-openshift-generated.cert`

It would be nice to get rid of that.

**Comment by ibotty** [comment]
Oh, and it would be great to accept the file names: `tls.crt` and `tls.key`, because these are the ones generated by openshift.

**Comment by petervo** [comment]
@ibotty we already support this.

https://github.com/cockpit-project/cockpit/blob/master/pkg/kubernetes/standalone/src/cockpit-kube-launch/main.go#L76

Make sure your paths match up with what is there. If for some reason this isn't working please reopen with the versions you are using so we can try to reproduce.

**Comment by ibotty** [comment]
I will try to find the documentation and fix it instead. Thank you!
