### ISSUE TITLE
Apps: empty page looks a bit cramped

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#7787]
Compare Applications
![screenshot from 2017-10-03 14-46-26](https://user-images.githubusercontent.com/209895/31125767-cf1cd130-a849-11e7-94e2-bdfb30644880.png)

With SELinux
![screenshot from 2017-10-03 14-46-38](https://user-images.githubusercontent.com/209895/31125798-e8e2ccb4-a849-11e7-9730-47a1a3f43213.png)

**Comment by KKoukiou** [comment]
@andreasn if this is still valid please provide with a mockup or just description how it should be and I can take over it!

**Comment by andreasn** [comment]
Thanks for taking care of this one!
I think just adding padding of 10px should be enough.

![screenshot from 2019-01-14 18-09-38](https://user-images.githubusercontent.com/209895/51128223-9f7be980-1827-11e9-8a7a-10bbc7f15516.png)

**Comment by KKoukiou** [comment]
Actually there is already padding for td 8px.
I see in the style developer tools.

.table > thead > tr > th, .table > tbody > tr > td {
    padding: 8px;
        padding-right: 8px;
        padding-left: 8px;


10px vs 8px doesn't make much of a difference tbh but if you think it's ok, I am glag to overwrite that for empty list with 10px.

**Comment by andreasn** [comment]
Hm, doesn't look like 8px in the first screenshot, and my Application page is all populated now, so I can't check for the empty state easily.

**Comment by marusak** [comment]
![padding](https://user-images.githubusercontent.com/12330670/69544894-f0ed1d00-0f90-11ea-84e9-62c0ae7aaa7f.png)

Now there is enough padding I believe.
