### ISSUE TITLE
Apps: no hover icon on row, even though it's a link

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#7788]
In the list of applications, even though I can click on it to get to the details page, is a regular pointer rather than the hand.

**Comment by andreasn** [comment]
It should work though, according to https://github.com/cockpit-project/cockpit/blob/c800bb33e6f535a328d50341a1a0864c191b8435/pkg/lib/table.css#L27

@garrett any idea what's up?

**Comment by garrett** [comment]
How do I check the applications list?

**Comment by garrett** [comment]
Here's what I see under "Applications".

![screenshot-2017-10-4 applications](https://user-images.githubusercontent.com/10246/31172525-32705b52-a904-11e7-807b-82b6b1bfb4aa.png)

When I click the refresh button, it checks for applications, but when it finishes, the screen returns to looking like this.

**Comment by garrett** [comment]
I've been trying to debug this, but it's really odd. It _should_ be applicable, and it appears to be pulled in, but I don't see it applied.

**Comment by garrett** [comment]
The `table.css` include is was not inside `application.css`. (I patterned the include based on Kubernetes as an example.)
