### ISSUE TITLE
kind of ugly "Optional" label

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#779]
![screenshot from 2014-06-24 17 11 42](https://cloud.githubusercontent.com/assets/209895/3373936/74047c62-fbb8-11e3-9f64-5f3849f2c7ae.png)

@LHinson mentioned that the standard patternfly pattern for indicating what fields are optional and what is not is to set * symbols next to the mandatory ones.

**Comment by dperpeet** [comment]
The "Options" label has been removed and the dialog simplified.
