### ISSUE TITLE
Port 9090 conflicts with Cherokee's cherokee-admin tool

### ISSUE THREAD

**Issue by nekohayo** [cockpit-project/cockpit#7815]
So a few weeks ago I tried logging into cockpit on my Fedora 26 workstation, then realized that it wasn't running for some reason, so I did `sudo systemctl enable --now cockpit.socket` (probably from some guide I found on the net), and it seemed to do the trick. So far, so good.

Except that today I wanted to administer my web server running on the same machine, Cherokee, which is done using the command "cherokee-admin" as root, and this is what I got:

> [04/10/2017 17:24:36.858] (critical) bind.c:293 - Could not bind() port=9090 (UID=0, GID=0) | Most probably there is another web server listening to the same port. You will have to shut it down before launching Cherokee. It could also be a permissions issue as well. Remember that non-root user cannot listen to ports < 1024.

So I remembered that cockpit had a pretty similar-sounding port, and did `sudo systemctl disable --now cockpit.socket`, which made cherokee's admin interface work again.

Couldn't cockpit default to a less popular port? I'd like to have my cake and eat it too :)

**Comment by petervo** [comment]
9090 is a pretty standard port for web based consoles, so I don't think we are likely to change that. You can have cockpit run on a different port by changing the ListenStream=9090 line in /usr/lib/systemd/system/cockpit.socket as described here: http://cockpit-project.org/guide/latest/listen.html

**Comment by 84ace** [comment]
> 9090 is a pretty standard port for web based consoles, so I don't think we are likely to change that. You can have cockpit run on a different port by changing the ListenStream=9090 line in /usr/lib/systemd/system/cockpit.socket as described here: http://cockpit-project.org/guide/latest/listen.html

It has just taken me an hour to change the port on my first cockpit install. I followed the docs as I was installing then ran into issues as /etc/systemd/system/cockpit.socket.d/listen.conf does not exist. It wasn't until i came across your response with the following path /usr/lib/systemd/system/cockpit.socket that I could get things working.

My point is that the docs you linked seem incorrect. Thanks for pointing us in the right direction though :)

**Comment by martinpitt** [comment]
That path is correct. Please do **not** write into /usr/lib! The docs say

> Create the file and directories in that path which not already exist. 

Would it help to add an explicit `mkdir -p /etc/systemd/system/cockpit.socket.d/`?

**Comment by 84ace** [comment]
> That path is correct. Please do **not** write into /usr/lib! The docs say
> 
> > Create the file and directories in that path which not already exist.
> 
> Would it help to add an explicit `mkdir -p /etc/systemd/system/cockpit.socket.d/`?

Hi Martin, 

You're right. My mistake. I'd make it bold or put it in its own paragraph. I just skimmed the article for commands and missed that key point as it just looks like fluff. 

Cheers!
