### ISSUE TITLE
Kubernetes Cockpit Error - Latest Version 

### ISSUE THREAD

**Issue by VinayKumarbrsoft** [cockpit-project/cockpit#7873]
Hi Guys, 

Updated cockpit version to 152 which is the latest version and the container logs showing following error.  Any leads to what is causing this error would be great!

> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header
> MESSAGE: cockpit-protocol: received HTTP request without Host header

Kubernetes Version: 1.5.6 
OS:  Linux RHEL

**Comment by petervo** [comment]
@VinayKumarbrsoft is there functionality not working as well? Or are these just messages?

**Comment by VinayKumarbrsoft** [comment]
Application does not start and GUI is not available.

**Comment by VinayKumarbrsoft** [comment]
Sorry - application started ; however the GUI is not available.

**Comment by petervo** [comment]
I'm assuming you are using the container. Can you provide the yaml or json you are using to create the objects. How are you exposing the service? Is there any information in the status part when you kubectl get the pod?

**Comment by martinpitt** [comment]
No response in 1.5 years, and there is not enough information here to reproduce or understand this issue, sorry. Thus I am closing this now. If this still happens with current versions, please reopen. Thank you!
