### ISSUE TITLE
Adjust all dialogs to use Modal component from patternfly-react

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#7880]
The standard patternfly pattern is that the dialog animate in from the top.
This is especially evident when switching between Composer and the rest of Cockpit.

**Comment by garrett** [comment]
It seems that this is related to adding the `fade` and `in` classes to the element with the `modal` class. It might be as simple as adding these two classes (fade and in) to our modals.

**Comment by KKoukiou** [comment]
There has been this effort to move all our dialogs to patternfly-react Modal component. That has the behavior you describe here. We are not fully there yet, some packages are not yet moved to patternfly-react Modal, so keeping this open as reminder to finish all.

**Comment by andreasn** [comment]
In that case we should either use this issue as a tracker issue for moving dialogs to react specifically, since the animation will be a side effect of moving them to react. So I would either rename this issue to something like "port all dialogs to react", or close the issue, since we don't have to do anything specific for adding animation.

**Comment by andreasn** [comment]
VM create dialog animates in already, as an effect of moving to react. We're moving dialogs to react over time, but no need to track it here.
