### ISSUE TITLE
prioritize machines pkg over ovirt pkg?

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#7913]
now when I build the code I get the ovitrt page instead of the machines page.
Should we switch the priority of these?

**Comment by mareklibra** [comment]
Are you using cockpit's vagrant?

On production environment, there's no difference whether to (un)install one or another. So why not.

Integration tests are already enforcing priority of either `ovirt` or `machines` depending on context, so no harm here either.

On development environment, the issue will be vice versa - how to show the oVirt Machines page?
Considering the facts that more people is involved in pkg/machines development recently and the `ovirt` environment is not part of the vagrant setup but just the test image, it makes sense to switch the priority.

**Comment by martinpitt** [comment]
Developer convenience is surely a factor here, but we need to consider the effect on the installed packages in products. If you have both cockpit-machines and -ovirt installed, which one should you see? As far as I understand, it should be ovirt then, as that's a superset of the functionality?

**Comment by mareklibra** [comment]
On production, the cockpit-ovirt would be expected in this case

**Comment by martinpitt** [comment]
Right. So either we munge the priority during `make install`, or we keep the status quo. But TBH I'd find the former quite confusing.

**Comment by andreasn** [comment]
Makes sense. Closing.

**Comment by mareklibra** [comment]
For future seekers, to prioritize `cockpit-machines` over `cockpit-ovirt` in vagrant:

- vagrant up
- set `Priority` to `100` in dist/machines/manifest.json
- vagrant rsync

Once (re)logged into cockpit, the `localhost:9090/machines` will use `dist/machines` instead of `dist/ovirt`.
