### ISSUE TITLE
Connection_refused on Ubuntu Server

### ISSUE THREAD

**Issue by phate82** [cockpit-project/cockpit#7914]
Hi everyone, 

I installed Ubuntu server on a physical machine (HP ProLiant). Then, I added the cockpit package. 
If I try to access the cockpit interface at https://server_public_ip:9090 just when the server starts, I can do that, but after few minutes I receive Connection_refused and I have to reboot the server in order to access again.

Any ideas? Thanks.

**Comment by martinpitt** [comment]
Once that "connection refused" happens, can you please log into that server and give us the output of

    systemctl status --lines=100 -l --no-pager cockpit.socket cockpit.service

Thanks!

**Comment by stefwalter** [comment]
No reply from @phate82 ... closing this issue.
