### ISSUE TITLE
RFE: move from React-lite to React 

### ISSUE THREAD

**Issue by suomiy** [cockpit-project/cockpit#7917]
I would like to propose to move from React-lite to React.

### Benefits:
- current updates (React-lite is lacking in development)
- features and fixes (PropTypes checking)
- dev tools support 

I got a pretty obscure bug (see bellow) in React-lite which doesn't happen in React:

```diff
<p className='ovirt-login-in-progress'>
-     {_("oVirt login in progress")} <span className="spinner spinner-xs spinner-inline"/>
+     {_("oVirt login in progress") + '\xa0'}
+      <span className="spinner spinner-xs spinner-inline"/>
</p>
```
The space just before the span causes the React-lite crash after specific re-render (not the initial one) and only in chrome (firefox works).

The thing that fixes that, is the new part of the diff. Non breaking space \&nbsp; crashes it as well.

### Size of index.js 
I tried to build cockpit with both React and React-lite and I think the size difference is negligible, because overall we are already sending hundreds of KiB.

|         | React-lite           | React  |
| ------------- |:-------------:| -----:|
| index.min.js     | 198K | 344K |
| index.min.js.gz     | 46K      |  77K |

### Hurdles
New version of React is divided into these packages:
```
"react": "16.0.0",
"react-dom": "16.0.0",
"create-react-class": "15.6.2",
"prop-types": "15.6.0",
```
 - so require/import fixes would be necessary.
 - there are also many warnings by React all over the project

I tried porting only machines plugin and it was ok.

@stefwalter @petervo @mareklibra 
What do you guys think?

### Bug exception
Just for the completion
```
Uncaught TypeError: Cannot read property 'vchildren' of undefined
    at diffVchildren (react-lite.js:230)
    at diffVchildren (react-lite.js:336)
    at updateVChildren (react-lite.js:100)
    at updateVnode (react-lite.js:88)
    at compareTwoVnodes (react-lite.js:587)
    at updateVstateless (react-lite.js:386)
    at applyUpdate (react-lite.js:120)
    at flatEach (react-lite.js:1881)
    at flatEach (react-lite.js:1879)
    at updateVChildren (react-lite.js:102)

	diffVchildren	@	react-lite.js:230
diffVchildren	@	react-lite.js:336
updateVChildren	@	react-lite.js:100
updateVnode	@	react-lite.js:88
compareTwoVnodes	@	react-lite.js:587
updateVstateless	@	react-lite.js:386
applyUpdate	@	react-lite.js:120
flatEach	@	react-lite.js:1881
flatEach	@	react-lite.js:1879
updateVChildren	@	react-lite.js:102
updateVnode	@	react-lite.js:88
compareTwoVnodes	@	react-lite.js:587
updateVstateless	@	react-lite.js:386
applyUpdate	@	react-lite.js:120
flatEach	@	react-lite.js:1881
flatEach	@	react-lite.js:1879
updateVChildren	@	react-lite.js:102
updateVnode	@	react-lite.js:88
compareTwoVnodes	@	react-lite.js:587
updateVstateless	@	react-lite.js:386
updateVnode	@	react-lite.js:75
compareTwoVnodes	@	react-lite.js:587
renderTreeIntoContainer	@	react-lite.js:2034
render	@	react-lite.js:2072
render	@	index.es6:30
dispatch	@	redux.js:412
(anonymous)	@	middlewares.es6:41
dispatch	@	redux.js:751
(anonymous)	@	libvirt.es6:233
(anonymous)	@	middlewares.es6:38
dispatch	@	redux.js:751
(anonymous)	@	provider.es6:90
P	@	cockpit.js:1283
(anonymous)	@	cockpit.js:1296
j	@	cockpit.js:1174
setTimeout (async)		
A	@	cockpit.js:1182
T	@	cockpit.js:1296
B	@	cockpit.js:1204
s	@	cockpit.js:1244
(anonymous)	@	provider.es6:85
(anonymous)	@	middlewares.es6:38
clicked	@	createDialog.jsx:362
action_click	@	cockpit-components-dialog.jsx:91
dispatchEvent	@	react-lite.js:1030
```

**Comment by mareklibra** [comment]
I don't know all the reasons leading to former decision about `react-lite`, but from recent perspective I vote for `react` as well. Better maintained, 3rd party components/libraries are developed usually having just the `react` on mind.

Size of .tgz or application start-up time seem to me insignificant in this context.

AFAIK, react-lite rendering is faster compared to react. I don't think there is a plugin benefiting from that, anyway.

**Comment by petervo** [comment]
IIRC, the main reason we chose it was because of size and the fact that we weren't going to use a lot of what was extra in the full version.

I'd be interested in seeing if we can find a way to allow cockpit components to chose which one they want to use without having to make any changes to existing working code. Might be possible to do if we can have different aliases for different packages.

@larskarlitski @stefwalter any opinions here.

**Comment by martinpitt** [comment]
It's also possible to do that on a per-pkg basis. welder-web will require exactly this, as it doesn't work with react-lite. I have an initial working approach here: https://github.com/cockpit-project/cockpit/pull/7870/commits/a23fddd61bbf68749cd29b944f5a25dbd34b1cb7

**Comment by stefwalter** [comment]
I would prefer a per package basis, at least for now.

**Comment by petervo** [comment]
Per component it is. @suomiy feel free to open a PR for switching machines away from react-lite. Any further discussion can happen there.
