### ISSUE TITLE
terminal: protect against Ctrl+W closing the tab

### ISSUE THREAD

**Issue by larskarlitski** [cockpit-project/cockpit#7956]
Most key combinations that you would use on a local terminal work great in cockpit's terminal. So, it's quite surprising when some of them don't. Most notably, `Ctrl+W`  (to delete the word before the cursor) closes the current tab in most browsers. This also loses all state from the terminal session.
 
I've looked into this and found out that browsers don't allow any global keyboard shortcuts to be overridden. Other examples are `Ctrl+Q` to quit the browser, `Ctrl+T` to open a new tab and `Ctrl+N` to open a new window. Actions that are local to the tab, such as `Ctrl+C`, `Ctrl+F` and `Ctrl+D` can be overridden. I think it is worth it for the terminal widget to capture those, because they are used quite often when interacting with a terminal.

A workaround for this problem is to show a hint somewhere on the terminal page to explain that these combinations cannot be used on the web. In addition, it probably makes sense to use the [beforeunload](https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload) event to warn about leaving the page when the terminal widget is in focus.

@andreasn or @garrett, do you think this makes sense?

**Comment by larskarlitski** [comment]
Just saw that OpenShift displays this above a container's terminal:

> When you navigate away from this pod, any open terminal connections will be closed. This will kill any foreground processes you started from the terminal.

**Comment by garrett** [comment]
## Prior history

Just for some background info: Years ago, in SUSE Studio, I made a console similar to Cockpit's; the feature was called "Testdrive". There was a text-based terminal as well as a graphical frontend. Both shared the code for keyboard handling, IIRC.

I implemented a few workarounds there: Flash & a Java fallback to be able to capture certain keyboard shortcuts that the browser wouldn't let us capture (it was focused and captured the keyboard shortcuts and would fall back to let JavaScript handle the rest). But times have changed and that's no longer possible, as plugins are basically now verboten in modern browsers.

Even with all that, we had a few remaining key combos that were problematic as well, such as control-alt-F1, control-alt-backspace, and so on, which were actually grabbed by X11 and killed the local display (or switched to text mode, in the case of control-alt-f#).

## Solutions & work-arounds

So I spent some time thinking about the problem and looking up _current_ possible solutions this morning.

### Plugins

Flash, Java, ActiveX, and NaCl _are_ actually solutions, but we shouldn't implement them, as all of them are deprecated and most browsers disable all of them now (and no browser supported all of them, meaning we'd have to have alternate codepaths _and_ a time machine).

It's worth mentioning, as it was a working solution years ago, but it's not a realistic one to use anymore.

### Local app

I know that if you install a webapp as a local application, it is possible to remap all keyboard shortcuts, at least in Chrome (and I think this is the same for Firefox and possibly even Edge). However, I don't think we should require people to install Cockpit as an app (although that would be interesting for other reasons — but this is an entirely different conversation).

### Fullscreen

It _might_ be possible to work around the issue by requesting fullscreen access. However, then I think that would break `ESC`, causing it to switch out of fullscreen mode.

### Shift

We could do something similar to what gnome-terminal does, where it allows you to do certain special features when holding the shift. In the case of gnome-terminal, you hit control-shift-c and control-shift-v to copy and paste, as control-c is usually used for breaking out of running software.

In our case, we'd want to capture control-shift-key and pass control-key. This would probably need to be a high-level toggle — and perhaps it should be enabled by default. (We'd want to test it to make sure it works.) 

There could be two ways it could be implemented: Have it handle just the browser-reserved keyboard shortcuts (but then that means someone would have to know and remember which are browser-specific) or pass all control-shift-key commands as control-key.

### Buttons

We could have buttons someone would need to click to perform these tasks. It would break the flow of typing, however.

One advantage of the buttons: We could have tooltips with the workaround keyboard shortcuts to make it more discoverable.

### beforeunload

Yeah, I agree with you and think this would need to be implemented. It's an ugly but necessary hack.

## Recommendations

I think we should probably use a combination of techniques:

- Shift
  - probably with a toggle, defaulting to on
  - we'd need a good, simple name for this toggle
- Buttons
  - in the terminal titlebar, with tooltips that show how to call them via the shift workaround
- beforeunload
  - to capture native keys that would ordinarily do destructive things

**Comment by larskarlitski** [comment]
> (and no browser supported all of them, meaning we'd have to have alternate codepaths and a time machine)

:smile:

> Shift

Interesting, I hadn't thought of that. Unfortunately, browsers use many of `Ctrl+Shift` key combinations as well and don't allow overriding all of them. `Ctrl+Shift+W` for example is mapped to "Close Window" on Chrome.

I'll get started with the `beforeunload` thing, because that will work around the the original problem of this bug.

There's also #7143, which has some overlap. If it were clearer that the terminal is in focus, it is less surprising that some of the normal function keys don't work.

Thanks for the detailed answer!

**Comment by garrett** [comment]
> Unfortunately, browsers use many of Ctrl+Shift key combinations as well

It would be nice to have a modern-browser list of reserved keyboard shortcuts to work-around. Everything I saw is ancient, out-of-date stuff.

I wonder how Ctrl+Alt fares? It's more cumbersome to type, but perhaps it would be better supported?

# Additional alternate methods

## Command key

ALSO: There's another method — `screen`, that GNU command to make virtual screens that can be detacted and stay running on servers even after closing SSH connections (and so on) has ctrl-a as a command command. That is, it is a command that allows you to pass commands to screen itself instead of the shell, just for a moment. 

## Sticky key

Sticky key builds upon the command key and changes the way the control key works under some circumstances (when it's pressed versus pressed with another key).

Screen's command command is similar to a one-time sticky key for commands. A compose key on Linux, when configured properly, works like this as well. And that's similar to the accessibilty concept known as "Sticky Keys", implemented on GNOME, Windows, and OS X.

https://en.wikipedia.org/wiki/Sticky_keys

We could enable sticky keys with a button and/or a keyboard shortcut.

It could be implemented like the following:

- Was control pressed?
  - Is there any other key than control pressed?
    1. If sticky state is enabled, then end it. (This makes commands always work as expected, except for browser-reserved combos.)
    2. Send the key combo.
  - Was control pressed by itself? If so, enter Sticky state, then:
    1. Wait until another key is pressed.
    2. Send control and the key that was pressed.
    3. Unset sticky state.
  - Is sticky state enabled and was control pressed by itself?
    1. End sticky state.

Sticky state would need to have an indicator that control is pressed and will accept more feedback.

**Comment by garrett** [comment]
The big gotcha with sticky key is that we'd want to make sure that our implementation doesn't conflict with the OS implementation of sticky keys. I think it wouldn't though, as the OS would queue it up and send it in one go. However, then that would make us have the reserved keyboard shortcut issue again, like we currently do.

**Comment by garrett** [comment]
The sticky key implementation would _also_ be useful for the (soon arriving) mobile mode, as most mobile keyboards do not allow for control/alt/shift modifiers.

As such, I'd recommend it is a status indicator put on the bottom of the window — at least for mobile.

(BTW: With CSS, we could have this at the top on desktop and on the bottom on mobile too. Or we could just simply always have it on the bottom.)

**Comment by larskarlitski** [comment]
#7985 implements the `beforeunload` solution.
