### ISSUE TITLE
date and time not consistent across Cockpit

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#7973]
Pull request #7972 made me realize we're not very consistent with how we show dates and times across Cockpit.

Server page:
![screenshot from 2017-10-26 12-57-44](https://user-images.githubusercontent.com/209895/32049427-48d5588e-ba4d-11e7-80f1-502cd972b99f.png)

Logs page:
![screenshot from 2017-10-26 12-58-18](https://user-images.githubusercontent.com/209895/32049457-5f006bd0-ba4d-11e7-8fba-5a51037c9832.png)

Containers page:
![screenshot from 2017-10-26 12-59-05](https://user-images.githubusercontent.com/209895/32049485-7b5d1832-ba4d-11e7-83d3-dd76215350ba.png)

Services page:
![screenshot from 2017-10-26 12-59-47](https://user-images.githubusercontent.com/209895/32049513-94af0124-ba4d-11e7-8441-13dfd48397e1.png)

There might be other places as well. Feel free to add more.

**Comment by garrett** [comment]
folding this into https://github.com/cockpit-project/cockpit/issues/8583
