### ISSUE TITLE
Terminal Reset button sets stty size to 80x24

### ISSUE THREAD

**Issue by PeterFalken** [cockpit-project/cockpit#7976]
When using the new terminal window that takes advantage of the full size of the window.
If you click on the reset button, it sets the size of the stty terminal back to 80x24, even thou the terminal window size is set to use the whole window space. This can cause some weird display issues in the terminal if you are not aware of the stty resize.

This is related to the implementation of Pull Request #4633

**Comment by larskarlitski** [comment]
Awesome catch, thanks! #7984 should fix it.

**Comment by PeterFalken** [comment]
Thanks Lars. Looking forward to testing it.
