### ISSUE TITLE
machines: improve VM error notification

### ISSUE THREAD

**Issue by mareklibra** [cockpit-project/cockpit#7978]
Related to both machines and oVirt packages: improve design of VM error notification.

Recently a failed VM action is denoted by a yellow triangle preceding VM name in the list.
Within Overview subtab, short error description is farther rendered, additional details are visible within tooltip. See screenshots.

![vmproblem](https://user-images.githubusercontent.com/17194943/32091551-fc89dc54-baf4-11e7-91df-10841df0d09f.png)
---
![vmproblemdetail](https://user-images.githubusercontent.com/17194943/32091552-fcaaccc0-baf4-11e7-97f1-5f4b6fa6335f.png)

---

I like the design used i.e. in https://github.com/cockpit-project/cockpit/pull/7963, means
- the yellow triangle is rendered close to the `state` in the list
- new subtab `Problems` (or so) would be created to provide additional error details

@garrett , @andreasn , what do you think, please?

**Comment by andreasn** [comment]
I like the idea!
In the other parts of the UI (Logs and Containers), "Problems" mean crashers, and similar things that gets caught by abrt and fed into the [central retrace server](https://retrace.fedoraproject.org/faf/summary/), while this seems to be more about issues with the VM refusing to run.
I think it needs to be called something else to avoid confusion and possible disappointment ("why wasn't these problems fed into the FAF systems like the other problems?").
What about the word "Error instead"? What is this called in oVirt?

The thing where the warning icon shifts the Name over feels a bit jarring to me. I would place it on the left of the state, like we do in #7963

**Comment by andreasn** [comment]
Stepping back a bit, this is just a temporary error that you're supposed to address urgently and resolve fairly quickly, right?
If so, I wouldn't hide it under a tab, but show a notification right there and then:
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/fd2c65bc87b5dd465ea70962d51a419c85b8ff07/virtual-machines/vm-errors.png)

**Comment by andreasn** [comment]
Depending on the exact nature of these (is it breaking or nonbreaking), you might or might not want to give it the ability for the notification to be dismissed.

http://www.patternfly.org/pattern-library/communication/inline-notifications/

**Comment by andreasn** [comment]
Sorry I keep adding on here, but are the events the same as Events in oVirt?
If so, it would be good if it mirrored the Health section in oVirt.
 * The tab should be called "Events"
 * The events should get a icon for each kind of error + a number

**Comment by mareklibra** [comment]
@andreasn , thanks for the ideas.

The "START VM" error is just an example of a failed action. And any action might fail.

The #7978 scope is meant for failed actions initiated by the user within cockpit.
In other words, it's not meant for failures occurred within other flows within oVirt's processing in the background.

> but are the events the same as Events in oVirt?

No. Not recently. It should be failing result of immediate user action.

The proposed inline-notification looks great and meets its purpose in #7978 purpose better than separate subtab.
I think, the user shall be able to dismiss it since doing that automatically might be confusing and introducing "information gaps" for the user.

Anyway, these "oVirt events" might be worth to render as well, the proposed `Events` subtab fits here. 

Recently they are used in within #8028. Since there's >1000 of event types, let's open for this task a different issue. Proper implementation will require deep analysis of event types to better "harvest" the information for rendering.

**Comment by andreasn** [comment]
Thanks for the clarification!
I agree with giving the administrator control over dismissing the notification makes sense. Modified the mockups according to that.
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/3f4c2b9d227934db4de9055b18353d07f2367398/virtual-machines/vm-errors.png)

**Comment by andreasn** [comment]
And yeah, doing something for oVirt events belongs in a separate issue.
