### ISSUE TITLE
RFE: show kernel version on the system page

### ISSUE THREAD

**Issue by larskarlitski** [cockpit-project/cockpit#7981]
Fuji San suggested that we could show the kernel version on the system page.

I'm not sure if this information belongs there, as we're already showing the operating system and showing more stuff there might clutter the overview. However, I think it's worth thinking about whether we want to make it accessible from cockpit (other than `uname -r` on the terminal).

**Comment by martinpitt** [comment]
TBH I'm a bit skeptical about this. In general, the kernel version is usually implicitly defined by the OS version, and particularly the microversion and the distro suffixes don't really tell the user much. Also, depending on what kind of "feature availability information" you are looking for, the versions of systemd, NM, udisks etc. are also interesting. But we most certainly don't want to show an entire package list here.

So my gut feeling is to consistently not show these, and suggest the terminal for any queries like that.

**Comment by fujisan43** [comment]
Every time you restart a system after a system update, it is always good to know on which kernel the remote system has rebooted on. So you don't need to 'uname -a' in a terminal.
I don't want an 'entire package list', but just the kernel version so I can jump from one system to the next and immediately see which one has not booted on the latest kernel.

**Comment by KKoukiou** [comment]
I actually agree with @martinpitt on this. I wouldn't like to see kernel version information on the system page, since I think most users don't have any special interest in knowing that.
A user interested in this detail can either check it in the installed packages list or from the terminal.

Lets poll on that - I don't want to close this issue but let's decide.
@marusak @Gundersanne some quick feedback on this so that we can solve it or close it?

**Comment by marusak** [comment]
I agree with @martinpitt and @KKoukiou that showing kernel does not usually have any special meaning for users, so showing it on the main page seems to be a bit overkill. And as was pointed out, users may be interested in some other components as well and picking the "right" set would be just close to impossible as everyone would be interested in something else.
User to whom kernel version has some meaning is definitely capable to check it in other way (like in terminal with `uname`)
