### ISSUE TITLE
[Feature request] Make cockpit compatible with systemd-networkd besides NetworkManager

### ISSUE THREAD

**Issue by q2dg** [cockpit-project/cockpit#7987]
Hello

Here (http://cockpit-project.org/guide/latest/feature-networkmanager.html) it is said Cockpit uses D-Bus API offered by NetworkManager to interact with system's network configuration.

Could it be possible that Cockpit had the same behavior but running on systemd-networkd service (that is to say: could it recognize and manage .netdev/.network/.link files?)

Thanks!

PD: I don't know if systemd-networkd offers a D-Bus API like NetworkManager does. Sorry if this issue is a silliness, then.

**Comment by raneon** [comment]
This would be nice, originally I removed NetworkManager from all my servers and I only had to add it again as of cockpit, but my network is still managed by systemd-networkd.

**Comment by q2dg** [comment]
I've put a Feature Request on Systemd GitHub: https://github.com/systemd/systemd/issues/7593

**Comment by martinpitt** [comment]
Marking as blocked, until networkd gets an API (D-Bus or varlink or similar).

**Comment by enaut** [comment]
some network functionality has been exposed to D-Bus see:
https://github.com/systemd/systemd/blob/v243-rc1/src/network/org.freedesktop.network1.policy

The implemented features are mostly dns settings:
  * org.freedesktop.network1.set-ntp-servers
  * org.freedesktop.network1.set-dns-servers
  * org.freedesktop.network1.set-domains
  * org.freedesktop.network1.set-default-route
  * org.freedesktop.network1.set-llmnr
  * org.freedesktop.network1.set-mdns
  * org.freedesktop.network1.set-dns-over-tls
  * org.freedesktop.network1.set-dnssec
  * org.freedesktop.network1.set-dnssec-negative-trust-anchors
  * org.freedesktop.network1.revert-ntp
  * org.freedesktop.network1.revert-dns

**Comment by q2dg** [comment]
Regarding to this...do you think this list of currently implemented systemd-networkd's items  is enough for using it as a viable Cockpit's backend: https://github.com/systemd/systemd/issues/7593#issuecomment-713131716 ?
Thanks a lot

**Comment by martinpitt** [comment]
The currently available network1 API is for timedated, timesyncd (both of which already have Cockpit UI), and resolved. None of that is related to actually managing network interfaces, and the upstream bug said that they will not add a configuration D-Bus API.

So this is still an option if the cockpit UI parses and handles networkd's configuration files. Either way, this is a humongous piece of work, much too big for an issue -- it is safe to say that Red Hat's core cockpit team will *never* do this without a business demand/funding.

If someone else wants to develop such a page, please have a look at https://cockpit-project.org/blog/creating-plugins-for-the-cockpit-user-interface.html and https://cockpit-project.org/blog/cockpit-starter-kit.html . We are happy to assist you with developing such a page, CI, etc., but we don't have the capacity/priority to do that ourselves.

Thus I close this issue, to clean up our bug tracker.
