### ISSUE TITLE
doesn't show any branding in Edge

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8002]
On Edge, I don't get the name/branding of the system.
Not on the login screen or once I'm logged in.

**Comment by andreasn** [comment]
Might be due to Edge following the spec more closely than Chrome and Firefox: https://stackoverflow.com/a/36290015

**Comment by petervo** [comment]
It's also likely to be https://technet.microsoft.com/itpro/windows/keep-secure/block-untrusted-fonts-in-enterprise#Turn_on_and_use_the_Blocking_untrusted_fonts_feature

**Comment by garrett** [comment]
It looks like @andreasn is right about the `content` issue.

I've played around in Edge and noticed a couple of things:

1. The masthead brand is shown only via CSS (which is odd — shouldn't it in the HTML markup itself?)
2. `content` does work `#index-brand` is changed to `#index-brand:before` in `branding.css`
3. Edge does not support HTML tags in content (so `Fedora <b>Workstation Edition</b>` is rendered with tags visible)

As content is for plain text or special characters (and _not_ HTML) and it is only supposed to be included within `:before` and `:after` according to the spec, I suggest we fix this for all browsers by moving the branding to the HTML.

(Do you know the reason why it's in the CSS and not the HTML?)

**Comment by garrett** [comment]
I'm _guessing_ that Edge only supports `getComputedStyle` with the style attributes it supports. As it doesn't support `content` except in `:before` and `:after` (which is correct, according to spec), that means it ignores `content` in `#index-brand` outright.

MDN does have a section on using `getComputedStyle` with pseudo-elements: https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle#Use_with_pseudo-elements However, the support block at the bottom of the page has a "?" Edge's support of pseudo-elements, which means we'd have to try it to know if it supports it or not. I'm assuming it would work in this case though.

What this means: We might need to change `#index-brand` in the `branding.css` files to `#index-brand:after` (or `:before` — it's more of a preference) and then update the `getComputedStyle` call to look at the psuedo-element. (There are some tests for this specifically as well, so those would have to be updated too, of course.)

As Edge is apparently adhering to spec, it is possible other browsers may change this in the future too.

**Comment by garrett** [comment]
Note: This, unsurprisingly, affects Internet Explorer as well, and it's in master; it isn't a regression in the nav branch. (The nav branch happens to make it more noticeable, but it's nothing new.)
