### ISSUE TITLE
machines: label styling is inconsistent with the rest of Cockpit

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8018]
The labels in Virtual Machines differs slightly in style from the other parts of cockpit.
The other parts use non-bold text and no colon character. Virtual Machines uses bold text and colon character.

Accounts:
![screenshot from 2017-11-02 16-42-26](https://user-images.githubusercontent.com/209895/32335352-f3e6df64-bfec-11e7-9f8d-993860d6a5b9.png)

Storage:
![screenshot from 2017-11-02 16-42-01](https://user-images.githubusercontent.com/209895/32335364-fec325aa-bfec-11e7-88ee-b4910e2771cd.png)

Networking:
![screenshot from 2017-11-02 16-42-12](https://user-images.githubusercontent.com/209895/32335383-099c25d0-bfed-11e7-8a17-931865706364.png)

Virtual Machines:
![screenshot from 2017-11-02 16-42-32](https://user-images.githubusercontent.com/209895/32335401-1806406a-bfed-11e7-96bc-5ff894547716.png)

**Comment by andreasn** [comment]
I'm actually starting to question why we override the Patternfly styling for this across Cockpit.
(default behaviour is black, bold text). It just makes it look a tiny little more out of place with other Patternfly products (Welder being one of them):
![screenshot from 2017-11-02 16-58-22](https://user-images.githubusercontent.com/209895/32336234-0f4d00c4-bfef-11e7-829f-891548eb4627.png)

@garrett @stefwalter thoughts?

**Comment by garrett** [comment]
## Initial thoughts

So my initial thoughts on this:

1. Consistency (especially within a single app) is important, so yeah, we should fix this with a unified style, at least consistent within Cockpit itself.
2. I personally prefer having the labels de-emphasized, as the content is the important part. Dark, bold labels call attention to themselves more than the data.
3. If there's adequate differentiation between the label and the data, a colon isn't really needed as a separator.

## What others are doing

Let's look at what others do with respect to label formatting:

| | Patternfly | Bootstrap | GNOME | macOS | Windows | KDE | Material (Google) |
|---:|---|---|---|---|---|---|---|
| _Placement_ | side (usually), above also | top (usually), side also | side | side | above | side | side (usually), above also |
| _Alignment_ | right | left | right | right | left | right | left |
| _Colon_ | no | no | no | yes | no | yes | no |
| _Bold_ | yes | no | no | no | no | no | no |
| _Grey_ | no | no | yes | no | no | no | yes |

References:

1. [Patternfly](http://www.patternfly.org/pattern-library/)
2. [Bootstrap](http://getbootstrap.com/docs/4.0/components/forms/)
2. [GNOME HIG](https://developer.gnome.org/hig/stable/visual-layout.html.en)
3. [macOS HIG](https://developer.apple.com/macos/human-interface-guidelines/fields-and-labels/labels/)
4. [Windows UWP Design and UI](https://docs.microsoft.com/en-us/windows/uwp/design/layout/forms) 
5. [KDE HIG](https://community.kde.org/KDE_Visual_Design_Group/HIG/Alignment)
6. [Material Design Guidelines](https://material.io/guidelines/)

However, this is just the suggestion from each vendor. I've seen examples from each that are inconsistent. A few quick examples:

- Patternfly has inconsistent usage within the HIG
- Microsoft is inconsistent all over the places, especially in Windows, especially in older UI that's mixed in randomly
- GNOME is inconsistent with its default apps, most notably in preference UIs

## Consensus

If we're looking for a consensus across the different popular HIGs, it looks like:

1. Side placement (usually)
2. Right aligned labels
3. Not bold
4. Some form of differentiation: Either grey or a colon, but not both.

## Recommendations

1. We could either go with a consensus approach and choose either going grey (as we currently mainly do) or have a colon.
2. Or we could try to implement what Patternfly does by default.

(I personally prefer option 1.)

Also, while we should definitely improve what we can, we shouldn't feel too bad: it seems _nobody_ is doing this quite right across the board. There really are exception to the rules for every HIG. :wink:

**Comment by KKoukiou** [comment]
So, machines labels don't have their own styling, forms should use ```ct-form-layout``` class, and this should be cockpit generic design.
But indeed I notice in the Overview VM tabs we use colons after labels, which is not usual in cockpit.
@andreasn shall I remove the colons?

**Comment by andreasn** [comment]
Yes, removing the colons should be enough. Thanks!
