### ISSUE TITLE
cockpit-ssh connect and disconnect on demand rather than on login

### ISSUE THREAD

**Issue by brainbug95** [cockpit-project/cockpit#8025]
Hi there,

I'm having an issue with my cockpit setup which looks like the following: 
client browser -> cockpit-bastion -> cockpit-ssh to about 300 physical/virtual machines around the globe

I found out that i in fact can have only about 30 machines in my multiple_machines.json file before the cockpit interface and the machine it is running on (my bastion-host) start to get slow up to the point where the system is in fact unusable until I logout. I think the issue here is that cockpit tries to start and maintain at least one connection per user to all configured machines simultaneously. I tried working around that be removing the dashboard completely but apparently that's not all. 

I would suggest a change in that behavior to a more on-demand style. Only connect to a host if selected and there should be a disconnect (button) as well. Maybe combined with hostgroups like described in #2791. 

Unfortunately I cannot do stuff like that as I am not much of a dev person ;-). But I most definitely can test stuff like that.

**Comment by petervo** [comment]
@brainbug95 yes, we are aware of the problem and @andreasn is working on the design implications. Once he is done we'll stop connecting to machines on login by default unless a user specifically asks us to.

**Comment by andreasn** [comment]
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/navigation/host-switcher.png)

**Comment by brainbug95** [comment]
Looks very good :+1: . Are there any plans for implementing a manual or automatic disconnect mechanism as well?

**Comment by petervo** [comment]
Yes the plug looking button disconnects. Clicking on any machine whether from the dashboard or the sidebar menu attempts to connect.

**Comment by brainbug95** [comment]
Looking forward to test it.

**Comment by brainbug95** [comment]
May I kindly ask how the status of this is progressing? I cannot seem to find any further information on that.

**Comment by stefwalter** [comment]
CC @petervo CC @martinpitt Do you know if any of this code landed or is in a branch somewhere? I know that @petervo started working on it.

**Comment by martinpitt** [comment]
Not in a public one. I asked @petervo to push his WIP work to some public place about two weeks ago, but didn't get a response yet.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

We are sorry, but we won't be able to address this in any time soon.
If you are interested in helping us with the implementation, please comment here.
