### ISSUE TITLE
Blank login screen after logging in via caddy proxy

### ISSUE THREAD

**Issue by skluthe** [cockpit-project/cockpit#8030]
I have a caddy proxy setup on me network and I want to access cockpit through it. I've got my config setup like this:
```
cockpit.domain.com {
                        gzip
                        proxy / 10.0.100.10:9090 {
                                insecure_skip_verify
                                transparent
                                websocket
                       }
}
```
I am able to login but then I get a blank screen. Chrome's console is giving me too many redirect errors:
```
GET https://cockpit.sklu3.us/cockpit/$676a25bf6baff9a78650adfca327f37bf8e8e72f/manifests.js net::ERR_TOO_MANY_REDIRECTS
cockpit.sklu3.us/:82 GET https://cockpit.sklu3.us/cockpit/$676a25bf6baff9a78650adfca327f37bf8e8e72f/shell/images/server-small.png net::ERR_TOO_MANY_REDIRECTS
VM801:161 WebSocket connection to 'wss://cockpit.sklu3.us/cockpit/socket' failed: Error during WebSocket handshake: Unexpected response code: 403
WrappedWebSocket @ VM801:161
M @ cockpit.js:293
N @ cockpit.js:482
(anonymous) @ index.js:368
(anonymous) @ index.js:375
t @ index.js:9
(anonymous) @ index.js:18
(anonymous) @ index.js:36
t @ index.js:9
(anonymous) @ index.js:14
t @ index.js:9
(anonymous) @ index.js:12
(anonymous) @ index.js:13
cockpit.js:441 transport closed, dropped message:  
{"bus":"internal","payload":"dbus-json3","command":"open","channel":"1"}
cockpit.js:441 transport closed, dropped message:  1
{"add-match":{"path":"/machines","interface":"cockpit.Machines"}}
cockpit.js:441 transport closed, dropped message:  1
{"watch":{"path":"/machines","interface":"cockpit.Machines"},"id":"2"}
cockpit.js:441 transport closed, dropped message:  1
{"type":"s","call":["/user","org.freedesktop.DBus.Properties","GetAll",["cockpit.User"]],"id":"3"}
cockpit.js:441 transport closed, dropped message:  
{"command":"authorize"}
cockpit.js:441 transport closed, dropped message:  
{"payload":"null","command":"open","channel":"2"}
index.js:3558 transport closed: disconnected
(anonymous) @ index.js:3558
dispatch @ jquery.js:2524
m.handle @ jquery.js:2414
l @ cockpit.js:57
o @ cockpit.js:164
v @ cockpit.js:524
m @ cockpit.js:533
M @ cockpit.js:381
M.i.onclose @ cockpit.js:347
index.html:504 GET https://cockpit.sklu3.us/cockpit/$676a25bf6baff9a78650adfca327f37bf8e8e72f/system/system.js net::ERR_TOO_MANY_REDIRECTS
index.html:505 GET https://cockpit.sklu3.us/cockpit/$676a25bf6baff9a78650adfca327f37bf8e8e72f/domain/domain.js net::ERR_TOO_MANY_REDIRECTS
index.html:506 GET https://cockpit.sklu3.us/cockpit/$676a25bf6baff9a78650adfca327f37bf8e8e72f/performance/performance.js net::ERR_TOO_MANY_REDIRECTS
```

**Comment by petervo** [comment]
I'm not familiar with setting up caddy services so I don't think I can give you step by step instructions. But themes for setting up a proxy server are generally the same.

* Your proxy needs to be configured to support websockets at /cockpit/socket.
* Your origin header needs to match the domain and scheme properly. You can do this by using ProtocolHeader and/or Origins in your cockpit.conf (http://cockpit-project.org/guide/latest/cockpit.conf.5.html)
* You shouldn't be adding gzip or anything else that will mess with content or etags. Let the cockpit webservice handle that.
* There is limited support for subpaths. If you want a subpath you need to use the UrlRoot setting in cockpit.conf

Without knowing more i would try turning off gzip and look at configuring origins in cockpit.conf.

**Comment by skluthe** [comment]
I was able to get it to work. The only issue now is that I don't have any options for managing the server that's running cockpit. I am able to manage the other servers it's connected to though.
![image](https://user-images.githubusercontent.com/23664304/32387158-d1d02aa4-c080-11e7-8f0b-1696cb29bb2a.png)

Here is my cockpit config: (Changing the Origins to the url is what worked)
```
[WebService]
AllowUnencrypted = true
Origins = https://cockpit.domain.com
ProtocolHeader = X-Forwarded-Proto
UrlRoot = /
```
Here is my caddy config:
```
cockpit.domain.com {
        proxy / 10.0.100.10:9090 {
                insecure_skip_verify
                transparent
                websocket
        }
}
```

**Comment by petervo** [comment]
Why don't you change your proxy to point to localhost. and then once logged into cockpit add 10.0.100.10 as a machine via the dashboard.

**Comment by skluthe** [comment]
Trying that now. Thank you for the quick assistance!

**Comment by skluthe** [comment]
Worked perfectly! Thank you for the help!

**Comment by Esux** [comment]
I've pretty much followed skluthes setup but I get-

`Disconnected
Server has closed the connection.`

After like 10 seconds or so. Clicking reconnect allows me to browse the UI but then I'm disconnected again.
