### ISSUE TITLE
search host navigation

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#8036]
The host navigation is getting pretty long, especially with more dashboards installed. It would be nice to be able to quickly search for a few different reasons:

1. **fight cognitive overload**: In the usability study we did on the software update UI, people had issues finding the software update page when various debug navigation items were enabled. This indicates that we may hit a cognitive overload issue soon — and may already have too many items for some people. (Note: Nobody had an issue when debug menu items were removed. It could be coincidental, but it's worth mentioning.)

2. **submodule findabilty**: Some parts of Cockpit reside as submodules and more may will show up in the future. (Example: Someone may want to change the firewall and not think to look under "network".)

3. **aliases for alternate phrasing**: We could also have aliases to make things easier to find for people who are more familiar with Windows and macOS terminology — and we should probably include English language strings for non-English languages too.

**Comment by liberodark** [comment]
yes would be great to add search on dashboard
