### ISSUE TITLE
Apps: Support nested lists in description

### ISSUE THREAD

**Issue by jeepingben** [cockpit-project/cockpit#8042]
Allowing list items to contain lists is supported in html, but doesn't seem to be supported in the apps description element.  Supporting one more level, or making the parsing of the metadata db recursive to allow arbitrary nesting depth would be helpful for presenting some application descriptions.

![screen shot 2017-11-07 at 11 01 31 am](https://user-images.githubusercontent.com/8668066/32503433-2cee3a66-c3ab-11e7-81ef-5dfe74fc33fa.png)
[nested.xml.gz](https://github.com/cockpit-project/cockpit/files/1450700/nested.xml.gz)

**Comment by petervo** [comment]
@mvollmer does this work with the appstream metadata spec?

**Comment by mvollmer** [comment]
The AppStream spec does not explicitly rule out nested lists, so let's leave this open.

**Comment by mvollmer** [comment]
I have opened https://github.com/ximion/appstream/pull/228 to clarify the spec (with a preference for the lazy option, of you course :-).
