### ISSUE TITLE
Firefox can’t establish a connection to the server at wss://www.example.com/cockpit-dashboard/cockpit/socket

### ISSUE THREAD

**Issue by bensonshaji** [cockpit-project/cockpit#8044]
I unable to connect to the cockpit socket while configuring reverse proxy.. below is my apache configuration in fedora 26. I am not sure where I am going wrong.. Thanks in advance

```
<VirtualHost *:443>
        ServerName www.example.com
        SSLProxyEngine On
        ProxyPreserveHost On

        ProxyPass /cockpit-dashboard/ http://127.0.0.1:9090/cockpit-dashboard/
        ProxyPassReverse /cockpit-dashboard/ http://127.0.0.1:9090/cockpit-dashboard/
        <Location "/cockpit-dashboard/cockpit/socket">
                ProxyPass "wss://127.0.0.1:9090/cockpit-dashboard/cockpit/socket"
        </Location>

        SSLEngine on
        SSLCertificateFile /cert.pem
        SSLCertificateChainFile /fullchain.pem
        SSLCertificateKeyFile /privkey.pem
</VirtualHost>
```

**Comment by petervo** [comment]
You need to make sure your cockpit.conf has the settings needed to run on a subpath and validate the origin properly.

This comment should help. https://github.com/cockpit-project/cockpit/issues/8030#issuecomment-341767554

**Comment by bensonshaji** [comment]
It almost matches to the one which you referenced, but no luck.. I still get the same error

[WebService]
AllowUnencrypted = true
Origins = http://www.example.com
ProtocolHeader = X-Forwarded-Proto
UrlRoot = /cockpit-dashboard/

**Comment by petervo** [comment]
Your origin says http but you are running https

**Comment by petervo** [comment]
Your origin says http but you are running https

**Comment by petervo** [comment]
Your origin says http but you are running https

**Comment by petervo** [comment]
Here's what i would have

```
ProxyPreserveHost on
RequestHeader unset X-Forwarded-Proto
RequestHeader set X-Forwarded-Proto 'https' env=HTTPS

<LocationMatch "^/cockpit-dashboard/cockpi(t[^/]+|t)?/socket$">
    ProxyPassMatch "ws://localhost:9090/cockpit-dashboard/cockpi$1/socket"
</LocationMatch>

ProxyPass /cockpit-dashboard/ http://localhost:9090/cockpit-dashboard/
```

Then you shouldn't need a ```Origins``` entry in your cockpit.conf.

Because you have ```AllowUnencrypted = true``` in your cockpit.conf we proxy to http: and ws: terminating ssl at apache.

This also removes proxy pass reverse, that isn't needed.

**Comment by bensonshaji** [comment]
Thank you so much.. :) I thought since I was reverse proxying it, it did not really matter. I now realize it was not apache's configuration..  Thanks a lot again. 👍

**Comment by bensonshaji** [comment]
Thank you so much.. :) I thought since I was reverse proxying it, it did not really matter. I now realize it was not apache's configuration..  Thanks a lot again. 👍

**Comment by petervo** [comment]
Since this seems to be resolved, closing

**Comment by bensonshaji** [comment]
@petervo I have a weird issue... cockpit works in Centos 7 and in Ubuntu 16.04 with same setting doesn't work. I am just trying to move from centos 7 to ubuntu. There is no cockpit.conf in either OS. 

I get 

_**Firefox can’t establish a connection to the server at wss://subdomain.domain/cockpit/socket**_

Why is it so ?

**Comment by petervo** [comment]
Are the versions of cockpit on both the same? Are you reverse proxing on either?

**Comment by bensonshaji** [comment]
In centos 7 its version 151 and in Ubuntu 16.04 156-1. Yes i am reverse proxying them for a subdomain.

**Comment by petervo** [comment]
If you are reverse proxying you are going to need to set things up in either cockpit.conf or your proxy config so that the origin header matches expectations. Use Origins in cockpit.conf or X-Forwarded-Proto
