### ISSUE TITLE
network-manager on ubuntu 16.04 pulls in X

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#8048]
We should see if there is a different package we can depend on.

**Comment by martinpitt** [comment]
There is not much we can do about it on our side, I'm afraid. On Ubuntu 16.04, the network-manager package itself has a `Recommends: network-manager-gnome | plasma-widget-networkmanagement | plasma-nm` which pulls in that stuff. A workaround is to install cockpit-networkmanager with `apt --no-install-recommends`.

This also affects newer Ubuntu releases up to 17.04. The recommends was finally dropped in 17.10 (current stable release), and also does not exist in Debian stable and testing. Dropping recommends from stable releases is rather outside of the usual policy too, so I'm afraid `--no-install-recommends` is the only way out on 16.04.

**Comment by petervo** [comment]
ok --no-install-recommends will have to be good enough.
