### ISSUE TITLE
NFS partition showing wrong used space

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#8053]
Reported by grift on IRC.

df shows 7.3T space  663G used

cockpit shows "6.6 / 7.2 TiB"

**Comment by petervo** [comment]
![screenshot](https://user-images.githubusercontent.com/10439156/32622487-db1aca04-c537-11e7-8c36-83f92b93e75e.png)

**Comment by mvollmer** [comment]
OMG! Thanks a lot for finding and reporting this.  Cockpit tries to show the "used" space, but actually uses the numbers for the "free" space.
