### ISSUE TITLE
Unclear messages for Locked/Unlocked state in UI

### ISSUE THREAD

**Issue by local-minimum** [cockpit-project/cockpit#8068]
I'm running a vanilla installation of cockpit on Ubuntu Server 16.04LTS

I was confused by the following:

* On the login-screen the checkbox for "Unlocked" has the wording "Reuse my password for privileged tasks". This does not clearly convey that this relates to login in as "Unlocked"

* If you are logged in as "Locked" but your user has admin rights, and you try to change the user settings of some other user you get an alert that says:

> Unexpected error
> 
> Not permitted to perform this action.

This does not clearly convey that it relates to the locked-state. In particular if it related to the lock state, it should by no means be an unexpected error, it should be very expected.

* After closing the above alert, the UI does not reflect the operational settings of the system (the checkbox is not reset to what is actually true on the system)

* I found it strange that I could not input my password to temporarily raise my privileges for the action that needed it.

* I found it unexpected that actions that were locked to me weren't indicated as such.

* Since I could not temporarily raise privileges for the action, I expected to be able to click on "Locked" in the top bar to unlock by supplying my password. In particular I didn't expect to need to log out and in again.

* When logging in as "Unlocked", I expected clicking on "Unlocked" to make the system "Locked" (which maybe it does), but instead of rendering the "Locked" status that you get when logging in as "Locked", the status just disappeared.

(Sorry for making a multi-issue, but they seem quite closely related)

**Comment by petervo** [comment]
Most of these issues are a result of the fact that we don't yet allow the user to interactively supply a password for privilege escalation after login. It's something we know we want but not yet implemented. Patches are welcome.

>On the login-screen the checkbox for "Unlocked" has the wording "Reuse my password for privileged tasks". This does not clearly convey that this relates to login in as "Unlocked"

Do you have alternate wording suggestions. Please open a PR and it can be discussed more there.

>    If you are logged in as "Locked" but your user has admin rights, and you try to change the user settings of some other user you get an alert that says:
> I found it unexpected that actions that were locked to me weren't indicated as such.

The message varies in different places through out the UI. We should probably be more standardized. We do try to disable things when we know that a user won't be able to perform those actions but often though discovering in advance what a user is allowed and not allowed to do can be tricky. Again PRs are welcome.

> After closing the above alert, the UI does not reflect the operational settings of the system (the checkbox is not reset to what is actually true on the system)

That sounds like a bug specific the particular action you were trying to do and not something true everywhere. More details would be needed or better yet a patch.

**Comment by andreasn** [comment]
Thanks for filing an issue about this after our private conversation on Saturday, @local-minimum, and thanks for testing out Cockpit after my recommendation!
Now that I'm back at work after the weekend, I'll try to come up with some wording to connect the string a bit more.

**Comment by Gundersanne** [comment]
#9531 removed the locked/unlocked wording in favour of privileged. And dropped the ability to interactively de-escalate privileges, as many parts of cockpit's UI didn't respond to this properly. So I'm closing this.
