### ISSUE TITLE
Authentication / Add key to user session

### ISSUE THREAD

**Issue by bkircher** [cockpit-project/cockpit#8103]
Allow a user to add an SSH key and password to the current session that is not installed on the host system.

Currently, when I go to User Name → Authentication → Add key (screen shot below) I am _only able to add a SSH key that is already on the host system_.

What I would expect is the possibility to upload a key file to the host system and use that by providing the corresponding passphrase.

Is this a reasonable feature request?

<img width="596" alt="add-key" src="https://user-images.githubusercontent.com/536464/32838577-159b98ca-ca1a-11e7-8ec1-3b6e0c0f27fb.png">

What I want here is a

```html
<input name="myKey" type="file">
```

that accepts the private key file, uploads it to the host system, adds it to a ssh-agent, using a passphrase provided by me through an additional input element.

**Comment by bkircher** [comment]
On a second thought, I am not sure if this is the right way to go.

Another way to go on about this is to keep the private key on my system and forward my local system's SSH agent to the remote hosts user session.

**Comment by petervo** [comment]
I don't think we can make forwarding an agent from your local machine to the remote host work. The only connection is through the browser and no browser that i know of supports that sort of thing.

If you are ok with leaving your key on the server, it's pretty easy to use the teminal or scp to upload a key and then unlocking it in the dialog. But I'm not opposed to adding a input box to dialog either. @andreasn WDYT? Does it work or would it make things too cluttered?

**Comment by bkircher** [comment]
Yes, you're right. I close this because I don't even know myself what the right thing would look like. I'll go back to copying SSH keys.
