### ISSUE TITLE
Cant login: authentication failure

### ISSUE THREAD

**Issue by norwat** [cockpit-project/cockpit#8104]
Hi
I made a standard install both on my local machine with Fedora 26 and a server running Centos 7.4. I just followed the steps from the tutorials online and the official ones. Yet with a fresh install im unable to log in.

```Nov 15 14:44:24 xxxxxx systemd[1]: Started Cockpit Web Service.
-- Subject: Unit cockpit.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit cockpit.service has finished starting up.
--
-- The start-up result is done.
Nov 15 14:44:24 xxxxxx cockpit-ws[16413]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
Nov 15 14:44:41 xxxxxx cockpit-ws[16413]: logged in user session
Nov 15 14:44:56 xxxxxx cockpit-ws[16413]: session timed out
Nov 15 14:45:18 xxxxxx cockpit-ws[16413]: cockpit-session: user account access failed: 7 xxxxxx: Authentication failure
Nov 15 14:45:37 xxxxxx cockpit-ws[16413]: logged in user session
Nov 15 14:45:52 xxxxxx cockpit-ws[16413]: cockpit-session: user account access failed: 7 root: Authentication failure
Nov 15 14:45:53 xxxxxx cockpit-ws[16413]: session timed out
```
On the web-ui i get a "Permission Denied" message, on both machines i have SELinux turned off, ~~i even tried with a fresh install in a VM with the same version of CentOS, just a plain install, and i get exactly the same error~~.
Im unable to find any post online with similar error, any other info you need from my setup i'll be happy to provide.

Thank you

**Comment by petervo** [comment]
Usually permission denied means there is some rule in the PAM stack denying that user permission to login. Such has having nologin set or a account required type rule that the user doesn't satisfy.

Is this a publicly available VM image availble somewhere I can try? How was your user created?

**Comment by norwat** [comment]
I just tested was a vanilla CentOS install and apparently i made some mistake last time i tested, this time it worked perfectly.
However i still have the same issue on the desktop and on the server. I didn't made any modifications to PAM.
On both systems theres only one user account and it was created using CentOS's anaconda installer.

**Comment by norwat** [comment]
I also get this on my `/var/log/secure`

```
Nov 15 17:01:49 xxxxxx polkitd[857]: Registered Authentication Agent for unix-process:5062:14087 (system bus name :1.26 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Nov 15 17:01:49 xxxxxx polkitd[857]: Unregistered Authentication Agent for unix-process:5062:14087 (system bus name :1.26, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
```

**Comment by petervo** [comment]
Is your users uid > 1000?

**Comment by norwat** [comment]
uid is 1000

**Comment by petervo** [comment]
Not sure what to say. I use it on fedora 26 workstation everyday, and have used it successfully with centos 7.4 server. Both without requiring any additional config.

If you expound on what you mean by 'standard install' with step-by-step instructions i can try to see if I can reproduce. Otherwise I'm out of ideas.

**Comment by norwat** [comment]
Well installation is pretty straight forward i followed this link, [](https://www.vultr.com/docs/how-to-install-cockpit-on-centos-7).
Even weirder, i added a new account with uid 1001 and now i get a page refresh when i try to login, no error on the page once it loads.

I get this on `/var/log/secure`
```
Nov 15 17:31:23 xxxxxx cockpit-session: pam_unix(cockpit:session): session opened for user user2 by (uid=0)
Nov 15 17:31:23 xxxxxx cockpit-session: pam_lastlog(cockpit:session): corruption detected in /var/log/btmp
Nov 15 17:31:23 xxxxxx polkitd[857]: Registered Authentication Agent for unix-session:51 (system bus name :1.63 [cockpit-bridge], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
``` 

And this on cockpit's systemd journal
```
Nov 15 17:31:23 xxxxxx cockpit-session[15238]: pam_ssh_add: Failed adding some keys
Nov 15 17:31:23 xxxxxx cockpit-ws[12663]: logged in user session
Nov 15 17:31:39 xxxxxx cockpit-ws[12663]: session timed out
```

**Comment by petervo** [comment]
@norwat I meant system setup / installation not cockpit.

> Even weirder, i added a new account with uid 1001 and now i get a page refresh when i try to login, no error on the page once it loads.

don't understand this, do you mean it's working?

**Comment by norwat** [comment]
> @norwat I meant system setup / installation not cockpit.

No, we do have a small provisioning ansible playbook but it just does setup of user accounts, ssh acess and install some tools, everything else was changed manually. This machine is used mostly to run docker and lxc containers in dev, so system changes should be very minimal. 

> don't understand this, do you mean it's working?

No, the login page just refreshes and loads up with no error, I still cant login. The user was created using `useradd` and added that user to wheel group so it would have sudo access.

**Comment by petervo** [comment]
what version of cockpit do you have install?

rpm -qa | grep cockpit

**Comment by petervo** [comment]
Btw this is probably easier to figure out in a conversation, If you want to join #cockpit on freenode that might be alot easier.

**Comment by petervo** [comment]
After debuging on IRC.

user2 not working was the result of /var/log/btmp being corrupt.

Original user works if the users shell is set to bash.

Still need to figure out why the original zsh setting didn't work.

**Comment by petervo** [comment]
problem was zsh shell path used for user shell wasn't in /etc/shells.
