### ISSUE TITLE
Multiple Machine == Authentication |  No available credentials

### ISSUE THREAD

**Issue by jodumont** [cockpit-project/cockpit#8110]
Hi Everyone;

I try to connect a second CentOS7 through Cockpit

-----
I base my observation via this diagram:
https://raw.githubusercontent.com/cockpit-project/cockpit/master/doc/cockpit-transport.png
-----

- SSH is on port 22 and only allowed key authentication  
- My ssh key is a ed25519, I mention it because sometimes projects only implicitly support RSA.  
- I pull and push everything from the primary server (backups, config, ...) so primary server talk to everyone via SSH and nobodies able to talk to him via SSH  

1. My primary server is able to connect via ssh to my second server  
It have **cockpit-ws, cockpit-bridge, cockpit-system**, cockpit-docker, cockpit-pcp, ...

2. My secondary server don't have access to my primary server via ssh
It have **cockpit-ws, cockpit-bridge, cockpit-system**, ...

So when I go in the dashboard of server1 and try to connect server2 I have : **Authentication |  No available credentials**

I wonder where I configure these Authentification because under account on both server 
my users are identical and authorize the ssh key ed25519 I use via ssh.

Could someone help me to figure what I'm missing ? :)

Also; do I necessarily need cockpit-ws and cockpit-system on the server2 or everything fine with just cockpit-bridge ?

Regards!

Jonathan

PS: It might be another important detail 
neither server1 or server2 have a  : Machine SSH Key Fingerprints : No host keys found.

**Comment by petervo** [comment]
server2 needs cockpit-system. The only package that it doesn't need is cockpit-ws.

Do you have any keys loaded in cockpit? In order to ssh from server1 to server2 server1 needs access to your keys. You can see what keys you have loaded by clicking on the "authorization" link in the top right dropdown menu.

**Comment by jodumont** [comment]
@petervo 
thanks for the hint, I did'nt see this option before ;)
