### ISSUE TITLE
chroot

### ISSUE THREAD

**Issue by ivomarino** [cockpit-project/cockpit#8124]
hi all, trying to run cockpit in a Debian stretch `chroot` and `systemd` doesn't like it very much:

```
root@chroot:~# sudo systemctl daemon-reload
Running in chroot, ignoring request.
```

so probably this is a no go for running cockpit inside a `chroot`, right? thanks for feedback.

**Comment by petervo** [comment]
Cockpit needs to be able to access the system apis, such as systemd dbus apis, files in /etc and so on. So at the very least the cockpit-bridge process that gets started post login cannot be run in a chroot but needs access to the full system.

There is a docker container version of cockpit that mounts /etc from the system into the container and runs the webservice that way (https://github.com/cockpit-project/cockpit-container). In that setup login happens via ssh to the system running the container and cockpit-bridge gets started that way. But again cockpit-bridge has access to the full system.

**Comment by ivomarino** [comment]
ok, thanks for feedback, will try that way.
