### ISSUE TITLE
Question: Reuse cockpit SSL certificate

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [cockpit-project/cockpit#8125]
I'm curious, might I reuse valid cockpit SSL certificate, provided by user, for my REST API running on same server or user should provide different/same certificate specifically for REST API?  
I'm interesting more in morale part than technical implementation.

**Comment by petervo** [comment]
Without knowing all the details of what your API does, I would say that I don't see any reason why you wouldn't want to have the two services share the same SSL certificate as long as both are using the same host name.

**Comment by igorSmirnovPlexi** [comment]
Thank you, the REST API expose data, which I use in my cockpit plugins. This data also available for authenticated third parties.

**Comment by igorSmirnovPlexi** [comment]
I'd like to use cockpit's certificate for nodejs server. To create nodejs server, the https module [requires](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener) key and certificate as parameters. 
`sudo remotectl certificate` returns certificate path which used by cockpit. The file contains one or more certificate and key PEM blocks.
What is the right way to extract the certificate and the key from this file? By openssl command or simple context substring (How to substring if there are many)?

**Comment by petervo** [comment]
The key will always be the last one. I'm not sure there an openssl command to separate them cleanly. There is a cockpit command to combine them. remotectl certificate path-to-certs path-to-key. So you might want to generate them yourself  and then just run that to combine them for cockpit.

**Comment by igorSmirnovPlexi** [comment]
I need to extract (not to combine) certificate and key from this file.

How do I know which certificate and key block to choose, if there are many?

On Nov 28, 2017 8:41 PM, "petervo" <notifications@github.com> wrote:

The key will always be the last one. I'm not sure there an openssl command
to separate them cleanly. There is a cockpit command to combine them.
remotectl certificate path-to-certs path-to-key. So you might want to
generate them yourself and then just run that to combine them for cockpit.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/cockpit-project/cockpit/issues/8125#issuecomment-347622488>,
or mute the thread

**Comment by petervo** [comment]
If there are many they will be a chain. You'll need them all. There should only ever be one key.

The reason I suggested combining is that generating certificates the way you want for your service and then combining seems easier too me than trying to parse out certificates from a file without a proper library to do so. But UTU of course.

**Comment by igorSmirnovPlexi** [comment]
Thanks a lot!
