### ISSUE TITLE
Kubernetes Topology view contains icons that are not defined

### ISSUE THREAD

**Issue by bexelbie** [cockpit-project/cockpit#8127]
See screenshot
![screenshot from 2017-11-16 12-13-53](https://user-images.githubusercontent.com/7413661/33011888-8dfe2198-cddf-11e7-96b4-713174ec9af8.png)

**Comment by petervo** [comment]
We are waiting for this to make it to npm. https://github.com/kubernetes-ui/topology-graph/pull/27

**Comment by petervo** [comment]
update was merged
