### ISSUE TITLE
Building from cockpit binaries error

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [cockpit-project/cockpit#8143]
During building cockpit on Fedora 26 as described [here](https://github.com/cockpit-project/cockpit/blob/master/HACKING.md#building-cockpit-binaries), autogen.sh command is failing with following error:

`../autogen.sh: line 46: autoreconf: command not found`

Please help

**Comment by martinpitt** [comment]
You need to install the build dependencies first: https://github.com/cockpit-project/cockpit/blob/master/HACKING.md#getting-the-development-dependencies

**Comment by igorSmirnovPlexi** [comment]
Thanks Martin, my fault.
