### ISSUE TITLE
Dashboard icon has other meanings

### ISSUE THREAD

**Issue by rhwood** [cockpit-project/cockpit#8147]
The current dashboard icon in cockpit is the Patternfly topology icon.

Shouldn't it be the tachometer icon, which is frequently and recognizably used as a Dashboard icon ([and recommended for such a purpose](https://www.patternfly.org/styles/icons/))?

**Comment by andreasn** [comment]
@garrett any thoughts on this?

**Comment by garrett** [comment]
OK, I'll switch the icon to `fa-tachometer`. Thanks for spotting this! It was just a holdover from the mockups and nobody said anything like this until now. :wink:

**Comment by garrett** [comment]
Added a PR to fix the issue.

## Screenshots

Desktop mode:

![screen shot 2017-11-27 at 17 42 35-fullpage](https://user-images.githubusercontent.com/10246/33278069-b1ea746a-d39a-11e7-85c6-edaea62da0ae.png)

Mobile mode:

![screen shot 2017-11-27 at 17 42 57-fullpage](https://user-images.githubusercontent.com/10246/33278073-b51de8ce-d39a-11e7-86e5-6e90cfc4496b.png)

---

@rhwood: Thanks for the catch!
