### ISSUE TITLE
check-journal TestJournal.testAbrtDelete does not check reality

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8153]
In commit f0ffc99e079c51453bec49db8b81874f5214285b @marusak added tests for ABRT support, particularly `testAbrtDelete()`. It generates a crash, waits for it to appear in the logs, and then does this:

```python
        sel = "#journal-box .cockpit-logline .cockpit-log-message:contains('crashed in posix_kill')"
        b.click(sel)

        b.wait_present("#journal-entry-id")
        b.wait_in_text("#journal-entry-id", "python")
        b.wait_present('.cockpit-log-panel')
        b.wait_visible('.cockpit-log-panel')
```
The first paragraph clicks on the log message in the `.cockpit-log-panel` to get the details view, the second waits for the details view (`#journal-entry-id`), and then for `.cockpit-log-panel` to *appear*. But this isn't what happens in reality:

![testjournal-testabrtdelete-fedora-27-127 0 0 2-2301-fail](https://user-images.githubusercontent.com/200109/33123132-9a309f18-cf79-11e7-9813-3882f5bb7c7e.png)

I. e. clicking on the details view makes the `.cockpit-log-panel` *disappear*, as you can also see in the inspector:

![inspector](https://user-images.githubusercontent.com/200109/33123202-d72f8c26-cf79-11e7-9ab4-e705cebf3840.png)

(Note the `display: none` in the parent `<div id="journal">` element).

So the test case and actual behaviour of this are a mismatch. Apparently some PhantomJS bug/quirk causes the tests to succeed, but when running them with chromium (PR #8069) the test fails due to this issue:
```
wait_js_cond(ph_is_visible(".cockpit-log-panel")): condition did not become true
```

If the current behaviour is as intended (and it makes sense to me to not intermingle the log and details view), the test needs to be adjusted. But if you *meant* the log view to be visible in when looking at the details (perhaps with just a reduced/filtered view?) then the code needs to be fixed and the test refined to specify the desired behaviour.

@marusak, can you please confirm what your intention was?

**Comment by martinpitt** [comment]
@marusak: The much more likely option is that the test case was simply wrong, so I filed #8154 to fix it. This works with PhantomJS, and now also with chromium. If you had some other behaviour in mind, please speak up here and I'll close #8154.

**Comment by mvollmer** [comment]
> Apparently some PhantomJS bug/quirk causes the tests to succeed

Might be just a race.  Maybe with PhantomJS the `.cockpit-log-panel` was still visible by the time the check was done.

**Comment by marusak** [comment]
@martinpitt Yeah, it seems that I made this by accident. Sorry for the troubles and thank your for fixing it!
