### ISSUE TITLE
Numeric values on the storage slider or should we keep it continious?

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8156]
Spinning this off #8139 
@maryclarke suggested adding number indicators to the storage sliders.

> For the scale, if possible, it would be good to add the two end points for reference. Those end points can update depending on what is selected from the associated dropdown.

> @mvollmer, I mean something more in-line with what PatternFly shows here: http://www.patternfly.org/pattern-library/forms-and-controls/slider/

> This page shows detents on the slider at different points, but I was suggesting that the numeric value may only needed at the low and high ends. If we feel that all users will know what the min and max numbers are, maybe this wouldn't be necessary. I was only trying to point out that it is best practice to give context to users for the slider. Nothing else about what you have would need to change.

**Comment by martinpitt** [comment]
We already show the exact numerical value right next to the slider. Do you think we should still show it again under the slider? The [PF design page](https://www.patternfly.org/pattern-library/forms-and-controls/slider/#design) seems to suggest one or the other, but not both.

**Comment by andreasn** [comment]
Nah, probably good as it is now. I have never seen this come up again. Closing.
