### ISSUE TITLE
machines: add description field to create vm dialog

### ISSUE THREAD

**Issue by suomiy** [cockpit-project/cockpit#8157]
see also #7820 for original discussion

**Comment by suomiy** [comment]
@andreasn  @garrett  

is it still reasonable to add description field to the vm?

we could add it in the dialog as text input/area under the name

![dialog](https://user-images.githubusercontent.com/3648838/36786521-f1fde0ac-1c86-11e8-94bd-3dccec885504.png)
 

and show it under the vm overview

![over](https://user-images.githubusercontent.com/3648838/36786561-19c8a298-1c87-11e8-9777-207bd340c932.png)

**Comment by suomiy** [comment]
@andreasn @garrett ping

**Comment by garrett** [comment]
The Create New Virtual Machine dialog is already packed full of widgets, so I'm hesitant to suggest we add anything else there. And a description is not necessary to create a VM.

If we're adding a description somewhere, it should be an editable area in the overview tab only.

**Comment by andreasn** [comment]
I like the idea of making it an editable field in the overview tab for those that want to add those notes about a particular machine!

**Comment by KKoukiou** [comment]
@suomiy do you plan to work on this? I am not against such a field in the overview tab but there is much more important functionality missing for the moment and we can't allocate time on this. Please let me know, if you would like to contribute to add this else I 'll close this issue as won't do for the time being.

**Comment by suomiy** [comment]
I am not planning to at this moment. You can close the issue if you want.
