### ISSUE TITLE
oVirt Machines and virtual machines menu

### ISSUE THREAD

**Issue by raneon** [cockpit-project/cockpit#8159]
Since cockpit 156 the "virtual machines" entry in the menu got replaced with "oVirt Machines." I don't use oVirt on my Arch Linux systems, so whenever I want to see my running virtual machines I need to open now "oVirt Machines" and it will show me a dialog asking to create a connection to a oVirt Engine (FQDN and Port). If I click on cancel then I see on the right top a spinning circle "oVirt login in progress". Is this the expected behavior? Should all users start to use oVirt now or will you support the use case of normal virtual machines in the future as well?

**Comment by martinpitt** [comment]
This seems to be a packaging issue in Arch. The intention is that cockpit-machines and cockpit-ovirt are in two different packages (RPMs, debs) and that usually you would have cockpit-machines installed. Indeed you only want to install -ovirt if you actually have and use oVirt.

This package split is done that way in Fedora, CentOS, Debian, and Ubuntu. We don't control the Arch packaging upstream, so can you please report this in the Arch bug tracker?

**Comment by raneon** [comment]
Thanks for the fast response! I will report this to the package maintainer in Arch Linux AUR.
