### ISSUE TITLE
language change has no effect in chromium on our test images

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8160]
While debugging failed tests for the PhantomJS → Chome transition, the `testBasic (check_pages.TestPages)` failure is actually real:

 * Prepare a fedora-27 image (haven't tested others), `test/vm-run fedora-27`, log in, `systemctl start cockpit.socket`
 * In chromium, log into that VM's cockpit at https://127.0.0.2:9091/
 * Select "Display Language" in the menu bar and switch to German
 * UI reloads, but stays in English; showing `cockpit.language` in the JS console still shows "en"

The weird thing is that it *does* work when logging into my laptop's host cockpit (https://localhost:9090), and it *also* works when doing this in Firefox. So the problem isn't unanimously in the test VM or in the browser.

**Comment by petervo** [comment]
@martinpitt this is probably a dup of #7695

**Comment by martinpitt** [comment]
@petervo: Thanks for the pointer. I see how caching could affect the loading of po files and pages, but is that related to not setting the `cockpit.language` variable too?

**Comment by petervo** [comment]
are you checking cockpit.language in the child frame (ie dashboard or system)? Or the shell frame?

**Comment by martinpitt** [comment]
Reopening, #8436 had to be reverted.

**Comment by mglantz** [comment]
If you need help testing, let me know, I'd love to help.

**Comment by Neustradamus** [comment]
@martinpitt: Have you progressed on this ticket?

**Comment by marusak** [comment]
This is also tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1666310
This is known issue. Solution is to only allow picking language on login screen, the problem of course is with stuff like OAuth when there is no login screen.

This needs some good idea how to deal with such situations. Closing this issue as it has been inactive for a long time, we track it in BZ and there is workaround (ctrl + alt + R or re-login).

**Comment by martinpitt** [comment]
@marusak: Could we trigger a force-reload from the cockpit shell itself?

**Comment by marusak** [comment]
@martinpitt good idea, `window.location.reload(true)` might work. Let me give that a try.

**Comment by Neustradamus** [comment]
The problem has been solved?
-> This ticket has been closed

It is not good to close a ticket before the solution.

**Comment by marusak** [comment]
> good idea, window.location.reload(true) might work. Let me give that a try.

ah, we do that already.

We might do `cockpit.logout(true)`. That will get one on login screen and I __think__ if one uses SSO it would login them back in directly?
Maybe even better would be that we would show just message like 'You need to relogin to use new language' and then put there button that upon clicking does `cockpit.logout(true)`.

**Comment by attisan** [comment]
using cockpit 238 on ubuntu 20.04; having the very same problem. Would want to use cockpit in English, but no matter what I select cockpit is shown in German.
* Am not using SSO
* English is my first language in chrome
* Works in Firefox _and_ did work in chrome until I added a letsencrypt certificate 😕

**Comment by martinpitt** [comment]
When I switch from French to German and watch the loading in the network inspector, I see that the apps page loads base1's `po.js` for the new language, but already from its internal cache:

> Request URL: http://127.0.0.2:9091/cockpit/$a1135db2f99cf762f2d8760afead7b6c578ba57dbfc4d29388f39fbd1f2a9c85/base1/po.js
> Status Code: 200 OK (from memory cache)
> Cache-Control: max-age=31556926, public
> ETag: "$a1135db2f99cf762f2d8760afead7b6c578ba57dbfc4d29388f39fbd1f2a9c85-de-de"

However, po for apps is also cached, and still uses the old language:

> Request URL: http://127.0.0.2:9091/cockpit/$a1135db2f99cf762f2d8760afead7b6c578ba57dbfc4d29388f39fbd1f2a9c85/apps/po.js
> Status Code: 200 OK (from memory cache)
> Cache-Control: max-age=31556926, public
> ETag: "$a1135db2f99cf762f2d8760afead7b6c578ba57dbfc4d29388f39fbd1f2a9c85-fr-fr"

The `ETag` that includes the language doesn't save us, as Chromium doesn't reload the HEAD (for checking for an updated ETag) in the first place. This is due to the `Cache-Control:` which we [set to "infinite" whenever there is an ETag](https://github.com/cockpit-project/cockpit/blob/442a1ab982d7ff957bdb2441df115c4f658b2565/src/ws/cockpitchannelresponse.c#L603) -- i.e. we make the promise "The contents of this URL will never change whenever there is an ETag". This is fine for most files, but *not* for the magic po.js.

This caching goes away when I create a ~admin/.local/share/cockpit/pinger/, as user packages disable the bridge packages checksumming and ETags. So that's at least a workaround if someone is bothered about this with existing versions, but it *will* 
slow down the page loading, of course.

Disabling the caching for just po.js does work:

```diff
--- src/ws/cockpithandlers.c
+++ src/ws/cockpithandlers.c
@@ -567,6 +567,8 @@ handle_resource (CockpitHandlerData *data,
         {
           cockpit_channel_response_serve (service, headers, response, where,
                                           cockpit_web_response_get_path (response));
+          if (g_str_has_suffix (path, "/po.js"))
+            cockpit_web_response_set_cache_type (response, COCKPIT_WEB_RESPONSE_NO_CACHE);
         }
       else if (g_str_has_suffix (path, ".html"))
         {
```

This might be an acceptable hack until we figure this out properly. But it destroys caching for the common case when the language does not change.

It would make more sense to update our package checksum with the locale, instead of appending it to the ETag (where it's too late anyway, as the Cache promise has already been made):

```diff
--- src/bridge/cockpitpackages.c
+++ src/bridge/cockpitpackages.c
@@ -658,6 +658,12 @@ maybe_add_package (GHashTable *listing,
       g_checksum_update (own_checksum, (guchar *) manifest_str, manifest_len);
       g_checksum_update (bundle_checksum, (guchar *) manifest_str, manifest_len);
 
+      const char *locale = setlocale(LC_MESSAGES, NULL);
+      if (locale) {
+        g_checksum_update (own_checksum, (guchar *) locale, strlen (locale));
+        g_checksum_update (bundle_checksum, (guchar *) locale, strlen (locale));
+      }
+
        package->own_checksum = g_strdup (g_checksum_get_string (own_checksum));
     }
```

However, that by itself does not fix it. The code does get called, but the page does not even try to reload the resources, and in particular not the bit that would try to determine and reload the new bundle.

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit/pull/16930#issuecomment-1061648445 and the next comment try to set the [Vary:](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary) header, but this also does not work.

**Comment by Neustradamus** [comment]
@allisonkarlitskaya, I do not understand your closing, have you looked for https://github.com/cockpit-project/cockpit/pull/15633?

**Comment by martinpitt** [comment]
@Neustradamus : Yes, that one (#15633) can probably be closed as welll, but it may be the first steps for a better fix. But #17092 fixed this issue (with an arguably too heavy hammer, but it's fixed)

**Comment by Neustradamus** [comment]
@martinpitt Thanks for your PR about this old bug.
I hope it is the good one!
