### ISSUE TITLE
Kubernetes topology icons missing firefox

### ISSUE THREAD

**Issue by rajula96reddy** [cockpit-project/cockpit#8169]
Hey!

I have trying to setup cockpit Kubernetes. And after the setup, I found the topology icons are all black, unlike how they should be. I am on Firefox Quantum. 
![cockpit_bug](https://user-images.githubusercontent.com/9512824/33259662-97853c02-d383-11e7-9918-1ed349c40c6d.png)

I also tested with chrome and my mobile browser. And it was all fine with it. The problem only seems to be on firefox.

**Comment by petervo** [comment]
This should be fixed with https://github.com/cockpit-project/cockpit/commit/caab5e13b3af942104c2a871c768926e0f626bca and https://github.com/kubernetes-ui/topology-graph/pull/27
