### ISSUE TITLE
[DOC] Broken links in official blog tutorial

### ISSUE THREAD

**Issue by q2dg** [cockpit-project/cockpit#8186]
Hello.
In wonderful (and very important!) basic guide http://cockpit-project.org/blog/creating-plugins-for-the-cockpit-user-interface.html the link to download example code (http://cockpit-project.org/files/pinger.tgz) is broken. Now, to download "pinger" example it is necessary to go to https://github.com/cockpit-project/cockpit/tree/master/examples/pinger
Thanks

**Comment by petervo** [comment]
@garrett any way we can restore the old link?

**Comment by garrett** [comment]
Fixed in https://github.com/cockpit-project/cockpit-project.github.io/pull/122 — the site should rebuild momentarily and the files should exist once more.

Thanks for the bug report!

(Sorry about accidentally removing those files in the website migration.)
