### ISSUE TITLE
Wrong username/password if webserver uses auth_basic

### ISSUE THREAD

**Issue by moso** [cockpit-project/cockpit#8189]
I'm trying to "hide" my Cockpit page behind a simple `auth_basic` in Nginx.
It's not the first time I've done this, so I have a process insight on how to create a `htpasswd`.

My nginx conf have this included:

```bash
...
    location / {
        ...
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/.htpasswd;
    }
```

The `auth_basic` works fine but suddenly I get a wrong username or password at the Cockpit login form.
If I remove/comment out the `auth_basic`-part, the login form works fine again.

Is there a way to hide my page, or accept something like ssh-keys as login through the browser?

**Comment by petervo** [comment]
Cockpit uses basic auth to send username / password to the server to login. And you can't have 2 sets of credentials sent at the same time. If you really wanted to do this you could configure nginx to require basic auth everywhere except /cockpit/login. Then i think things would work.

> Is there a way to hide my page

Firewalls, or requiring a client cert, might be other options to consider.

> accept something like ssh-keys as login through the browser?

I wish, unfortunately this isn't something browsers support.

**Comment by LaKing** [comment]
A similar, actually almost the same thing actually exists, that browsers support: client side certificates.

#8429

**Comment by martinpitt** [comment]
This seems by and large unfixable, so I'm closing this.
