### ISSUE TITLE
manage user .k5login and .k5user

### ISSUE THREAD

**Issue by jcpunk** [cockpit-project/cockpit#8191]
Cockpit currently provides an interface for .ssh/authorized_keys.

It would be helpful if it could also manage a user's .k5login and .k5users within the same UI.

**Comment by martinpitt** [comment]
At this point it's safe to say that this will not happen just because of an ancient enhancement request issue, sorry.  This should probably be part of a more comprehensive kerberos/identity management UI from someone who actually uses and understands this stuff in an appropriate environment.
