### ISSUE TITLE
oVirt:  The cockpit UI always displays "oVirt login in process" with a rotating Icon when the user does not connect the engine. 

### ISSUE THREAD

**Issue by kenzhaoyihui** [cockpit-project/cockpit#8198]
Description of problem:
Should display the appropriate info while the user does not connect the engine via cockpit. Currently, the cockpit UI always displays "oVirt login in process" with a rotating Icon when the user does not connect the engine. 

Version-Release number of selected component (if applicable):
RHEL 7.5
cockpit-ws-154-1.el7.x86_64
cockpit-bridge-154-1.el7.x86_64
cockpit-system-154-1.el7.noarch
cockpit-ovirt-154-1.el7.x86_64

How reproducible:
100%

Steps to Reproduce:
1. Install the pkg cockpit-ovirt on the RHEL7.5
2. Login to the cockpit and don't connect the engine

Actual results:
After step2, cockpit display "ovirt login in progress"

Expected results:
Suggest to display the suitable info while don't connect the engine. Likely, for example, show "oVirt not login in"

Additional info:
The picture:
[Cockpit ovirt](https://github.com/kenzhaoyihui/issue_picture/blob/master/cockpitovirt1.png)

**Comment by mareklibra** [comment]
Related to: https://github.com/cockpit-project/cockpit/issues/7724

**Comment by mareklibra** [comment]
The user shall be able to re-issue the login

**Comment by mareklibra** [comment]
If the connection to oVirt fails or the user dismisses the oVirt connection dialog (for FQDN and port), the `Login in progress ... ` should be replaced by an action link `Log in to oVirt` which opens the FQDN/Port dialog and reissues the login.

**Comment by kenzhaoyihui** [comment]
I just have the suggestion : 
give the user action link login or logout to the oVirt.

**Comment by mareklibra** [comment]
Fixed within #8515, resp. #9020.

To re-issue login, the user can i.e. refresh the page.
