### ISSUE TITLE
filtering on the service list

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#82]
We have a filter entry on the network device list, which has a measly 2 entries here.

But my service list has (what feels like) hundreds, I could really use some filtering there to find e.g. just the active services.

There will be a general "search" facility, and we will also do something to highlight interesting services.

**Comment by nicekiwi** [comment]
:+1:

**Comment by andreasn** [comment]
This came up during the last round of usability testing as well. I opened #10010 after that, and since that issue has a design attached to it, I'll close this one as a duplicate.
