### ISSUE TITLE
Navigation Issue when logging in/out

### ISSUE THREAD

**Issue by pdonlon** [cockpit-project/cockpit#820]
Not sure if this is desired, but logging in navigates the user to the exact page they logged out on.

**Comment by andreasn** [comment]
I don't have any super-strong opinion for either behavior, but going to / could work.
Will this affect the behavior of when you get disconnected rather than manually log out? In the case of OSTree updates, I think it's desired to get back to the same place after an update.

**Comment by stefwalter** [comment]
Yup this is only about explicit logout.

So in conclusion. Lets drop the URL hash if someone logs out, and go to '/'

**Comment by andreasn** [comment]
Sure.

**Comment by martinpitt** [comment]
Removing good-first-issue -- Matej already tried in PR #11098, and it's not that easy after all. Also, this is a tiny issue and hasn't been addressed in many years, so the effort-to-effect ratio is simply too large here.
