### ISSUE TITLE
[DOC] Only "guide" pages are shown in "Documentation" page

### ISSUE THREAD

**Issue by q2dg** [cockpit-project/cockpit#8203]
I mean...in https://github.com/cockpit-project/cockpit/tree/master/doc there some very interesting pages (for instance "branding.md", to name only one) which aren't available if you click on "Documentation" link on http://cockpit-project.org because it points to http://cockpit-project.org/guide/latest , which I understand it only represents a subfolder of all the existing documentation (this: https://github.com/cockpit-project/cockpit/tree/master/doc/guide).

Could it be possible to make all .md files hosted on github "doc" folder readily available as generalistic web documentation?

Thanks!!

**Comment by martinpitt** [comment]
Not going to happen anytime soon. The doc/ folder is easy to look at for any developer, and some doc pages now actually do link to specific documents -- like https://cockpit-project.org/guide/latest/authentication.html
