### ISSUE TITLE
[Feature Request] Add the ability of manage Systemd-nspawn and/or LXD/LXC containers

### ISSUE THREAD

**Issue by q2dg** [cockpit-project/cockpit#8215]
Hello.

With Cockpit is possible to manage Docker containers, Libvirt VMs and even oVirt's ones.
Would it be too complicated embrace other container technologies like Systemd-nspawn or LXD/LXC ?
I know this could be a never-ending race because there are many nearly-overlapping technologies out there, but I ask this only to know if there would be any future plans about this topic.

Thanks!

**Comment by petervo** [comment]
There is no reason that it couldn't be done but to my knowledge no one is actively working on this right now.

**Comment by LaKing** [comment]
Systemd-nspawn containers are in essence actually services, and services can be managed by cockpit.
The basic functionality, start, stop, restart, enable, disable works therefore out of the box.
They appear under services static if started as services.  

LXC is a bit mor complicated, there are more tools to manage containers. Nspawn also has machinectl that can do more then systemctl.

**Comment by KKoukiou** [comment]
For the time being there is effort to implement support for podman containers, talking about container runtimes.
https://github.com/cockpit-project/cockpit-podman/

There hasn't been any effort towards LXC and if there will it will require a total new implementation due to different API that we need to use for this container runtime.

So, is there any real need to implement this functionality or this issue was opened out of pure interest?

**Comment by q2dg** [comment]
Well, I'd like to be able to manage **system** containers instead of **application** containers.
Anyway, with @Laking explanation I'm satisfied relating to system-nspawn but I'd just like to give them more integration with Cockpit, like being able to provision raw images, contigure network interfaces, etc. But well, it's only a wish. On the other hand, if you consider LXC is too much effort, it's fine: with systemd-nspawn is enough. Thanks.

**Comment by martinpitt** [comment]
This has been sitting around here for too long. This is a major new feature that requires a developer who wants to create and maintain it. This is not within the plans and focus of the cockpit team, sorry. If someone wants to work on this, I recommend building on [starter-kit](https://cockpit-project.org/blog/cockpit-starter-kit.html), and we'll be glad to help you with project and CI setup.

**Comment by khimaros** [comment]
quick note for those who found this while searching for how to manage lxc containers in cockpit. cockpit is able to manage libvirt containers, and libvirt has an [lxc driver](https://libvirt.org/drvlxc.html). requires further investigation.

**Comment by Imeguras** [comment]
> quick note for those who found this while searching for how to manage lxc containers in cockpit. cockpit is able to manage libvirt containers, and libvirt has an [lxc driver](https://libvirt.org/drvlxc.html). requires further investigation.

I've begun exploring its viability, as an outsider. I'm slowly progressing through some basic stuff, will post results if I achieve anything of note. I am unsure about contributing as there was some strict notes about "wontfix". I began deriving machines as lxc driver makes it easier
