### ISSUE TITLE
Failed to delete a UEFI/OVMF Libvirt machine

### ISSUE THREAD

**Issue by q2dg** [cockpit-project/cockpit#8217]
I get the error "Requested operation is not valid: cannot delete inactive domain with nvram"
The same error occurs if I execute the command virsh undefine myMachine in a shell, so it's not a bug of Cockpit. But...looking here (https://bugzilla.redhat.com/show_bug.cgi?id=1175120) I've found the solution: command must be virsh undefine --nvram myMachine. 

So I infer "Delete" button in Cockpit UI doesn't add the "--nvram" to the underlying command. 
Could it be possible to add it?
Thanks!!

**Comment by petervo** [comment]
@q2dg PR's welcome.

@mareklibra is there a reason why we might not want to do this?

**Comment by KKoukiou** [comment]
This was already fixed in release 179 with eb4771a81c316bb1afcfb1203ff2a6321d67d2e2
