### ISSUE TITLE
storage: odd looking pcp button in storage

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8230]
It's very long here.

![screenshot from 2017-12-07 14-04-15](https://user-images.githubusercontent.com/209895/33716751-9da50c80-db57-11e7-8a16-a098fbf38553.png)

**Comment by mvollmer** [comment]
Yes, I saw this, too. This should be fixed on master now, as part of the rewrite in React.  Could you check?

**Comment by Gundersanne** [comment]
As far as I can see this is now fixed as the zoom buttons were removed, closing.
