### ISSUE TITLE
[Feature request] Make Cockpit's HTTP client able to do HTTP/S remote queries 

### ISSUE THREAD

**Issue by q2dg** [cockpit-project/cockpit#8231]
I've read in http://cockpit-project.org/guide/latest/cockpit-http.html Cockpit's HTTP client only allows access to local HTTP and REST services. Why this limitation? Why not transform this client in a "standard" HTTP/S client able to do queries to a remote HTTP/S server?
Thanks!

**Comment by petervo** [comment]
I think you've missread the docs. If you don't supply the "address" param, then it assumes localhost. If you supply it you can connect to a remote http(s)

**Comment by q2dg** [comment]
Sorry, you're true, I've noticed now. But it isn't clear that "address" (and "connection" and "superuser") are possible "options"...they are listed out of context. I mean... I miss a sentence like: "Possible options are:". 
Thanks a lot, anyway.
