### ISSUE TITLE
auth: key based primary authentication

### ISSUE THREAD

**Issue by prasannavl** [cockpit-project/cockpit#8241]
I've found a few issues that addresses key based auth, but all of them seem to care only about secondary authentication, and I couldn't find anything on the docs regarding key based primary auth.

Is there a specific reason, why there has been no effort on this? I would be surprised if I'm the only one who feels like I'm being forced to set a password on my GCP instances, just for cockpit, as all other auth is purely key based. Can the login screen not have a way to drag and drop a key file to login?

**Comment by petervo** [comment]
Browsers do not support ssh-key based auth. I wish they did but they do not. Asking users to copy/paste or upload a private key into a browser also doesn't seem very secure.

The recommended way right now to avoid having to set a password is to use a bastion host. That bastion host could be a remote server, or your local computer. You log into cockpit on that server, unlock your key on it and connect to other machines as a secondary server. This has the added benefit that you don't need to open port 9090 on the remote server anymore, it just uses ssh.

There are other options that can be explored. I've been meaning to make an example for a bastion container, that has a encrypted key mounted as a secret, you login with your username and the password for the key and host you want to connect to. If the password unlocks the key, you are connected to that server.

**Comment by prasannavl** [comment]
> Browsers do not support ssh-key based auth. I wish they did but they do not. Asking users to copy/paste or upload a private key into a browser also doesn't seem very secure.

The cheery naive side of me is tempted to just drop in a note saying drag-drop/copy-paste of the key isn't really all that different from typing a password in. But I do see your point. Thanks for the detailed explanation of the alternate options. A bastion host seems like a pretty clean workaround :) The latter route looks like a pretty clever solution, though I suppose the simple bastion should be sufficient in many cases. 

Thanks again, for the neat solutions. I'll close this until further development on this.
