### ISSUE TITLE
kubernetes: Browser history broken

### ISSUE THREAD

**Issue by jniederm** [cockpit-project/cockpit#8248]
* Going back only cycles between last two states
* When navigated back, no forward history state is added

![kubernetes-navigation](https://user-images.githubusercontent.com/5278760/33845844-0e374030-dea5-11e7-8ac6-064ca641226c.gif)

version: commit d62178ec

**Comment by larskarlitski** [comment]
Closing this, because we'll be [removing cockpit-kubernetes](https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/) soon. It's unlikely that we'll fix this before then. Sorry!
