### ISSUE TITLE
Error showing real amount of RAM 

### ISSUE THREAD

**Issue by q2dg** [cockpit-project/cockpit#8251]
Hello.
My system only has 4GB of RAM. But, as it can be seen in attached image, when I focus on memory graph shown by Cockpit main page, y-axis units are completely wrong . Exact numbers are compared by free command output, also visible on image
If you want me to do some other tests, I'm your man
Thanks!

![cockpitissue](https://user-images.githubusercontent.com/7274874/33862642-12e16d56-dee4-11e7-84b9-a39da6db4b5d.png)

**Comment by petervo** [comment]
@mvollmer can you take a look. Seems to only be on the details page.

**Comment by q2dg** [comment]
Yes, it's only on the details page, it's true. Sorry for not having mentioned it

**Comment by andreasn** [comment]
@garrett started working on this https://github.com/cockpit-project/cockpit/wiki/Feature:-Memory-graphs

**Comment by MarkRS-UK** [comment]
Similar issue here (though with 8Gb of RAM under Fedora27), but the problem also shows on the overview page, with memory displayed as almost completely full when in fact only a little over 1Gb is in use (according to "free"). The graph on the detail page also incorrectly shows about 10Gb of RAM in use.

I watched this build up on the overview graph over the course of about a minute from what appeared to be the correct figure to the incorrect one.

**Comment by garrett** [comment]
We just merged in a fix in PR #10101 today.
