### ISSUE TITLE
Running Cockpit as HTTP Service not working (HAProxy)

### ISSUE THREAD

**Issue by ExaconAT** [cockpit-project/cockpit#8255]
Hi,
I want to manage Cockpit over my HAproxy Server.

I've installed Cockpit and created **/etc/cockpit/cockpit.conf** with the following entries:

```
[Webservice]
Origins = https://dev-machine.domain.net:9090
ProtocolHeader = X-Forwarded-Proto
AllowUnencrypted = true
```

● cockpit.service - Cockpit Web Service
   Loaded: loaded (/lib/systemd/system/cockpit.service; static; vendor preset: enabled)
   Active: active (running) since Die 2017-12-12 11:41:21 CET; 1s ago
     Docs: man:cockpit-ws(8)
  Process: 5832 ExecStartPre=/usr/sbin/remotectl certificate --ensure --user=root --group=cockpit-ws --selinux-type= (code=exited, status=0/SUCCESS)
 Main PID: 5837 (cockpit-ws)
    Tasks: 2
   Memory: 892.0K
      CPU: 59ms
   CGroup: /system.slice/cockpit.service
           └─5837 /usr/lib/cockpit/cockpit-ws

Dez 12 11:41:21 dev-machine01.domain.local systemd[1]: Starting Cockpit Web Service...
Dez 12 11:41:21 dev-machine01.domain.local systemd[1]: Started Cockpit Web Service.
Dez 12 11:41:21 dev-machine01.domain.local cockpit-ws[5837]: **Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert** **## ???**

**haproxy.cfg**
`frontend www-http
        bind *:9090
        redirect scheme https if !{ ssl_fc }
.
.
use_backend dev_cluster if { ssl_fc_sni dev-machine.domain.net } 
.
.
backend dev_cluster
        http-response set-header Strict-Transport-Security "max-age=15552000; includeSubDomains; preload;"
        option forwardfor
        cookie serverid insert indirect nocache
        server dev-machine01.domain.local 10.101.203.31:9090 check weight 100 cookie dev01-cockpit
´
Firefox Error: `SSL_ERROR_RX_RECORD_TOO_LONG´

**Comment by petervo** [comment]
It looks like you set cockpit to be unencrypted but configured haproxy to use ssl to talk to cockpit.

**Comment by ExaconAT** [comment]
No im talking http internal and https external, at least with the other Webservices it works like that.

**Comment by petervo** [comment]
Well i can't see your whole haproxy config so I can't say for sure. But the error SSL_ERROR_RX_RECORD_TOO_LONG generally means that the browser expected to get an ssl message and instead got an unencrypted http reponse.

**Comment by ExaconAT** [comment]
`global
        maxconn 4096
        tune.ssl.default-dh-param 2048
        user haproxy
        group haproxy
        chroot /var/lib/haproxy
        daemon
        log 127.0.0.1 local0

        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 10s
        stats bind-process all
        ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
        ssl-default-bind-options no-sslv3
        tune.ssl.default-dh-param 2048


defaults
        maxconn 4096
        log     global
        mode    http
        option  httplog
        option  dontlognull
        retries 3
        option  redispatch
        option  http-server-close
        option  forwardfor
        timeout connect 5000
        timeout client  50000
        timeout server  50000

        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend www-http
        bind *:80

        mode http
        option forwardfor
        option http-server-close
        option http-pretend-keepalive
        reqadd X-Forwarded-Proto:\ http
        redirect scheme https if !{ ssl_fc }
        http-response set-header Strict-Transport-Security max-age=31536000;

frontend www-https
        bind 0.0.0.0:443 ssl crt /etc/haproxy/certs/

        reqadd X-Forwarded-Proto:\ https
        use_backend cockpit_cluster if { ssl_fc_sni  } # content switching based on SNI

backend nextcloud_cluster
        balance roundrobin
        server node1 10.0.0.2:9090 check

backend letsencrypt-backend
   server letsencrypt 127.0.0.1:54321`

**Comment by petervo** [comment]
What does the cockpit_cluster backend definition look like?

**Comment by ExaconAT** [comment]
Refresh Page pls

**Comment by petervo** [comment]
I'm not able to reproduce. Using haproxy-1.7.9-1.

```
frontend main
    bind *:443 ssl crt /path/to/cert.cert
    reqadd X-Forwarded-Proto:\ https
    default_backend app

backend app
    server  node 127.0.0.1:9090
```

works for me.

older versions of haproxy might need a slightly different configuration. But i'm pretty sure is is a haproxy config issue not something with cockpit.

**Comment by ExaconAT** [comment]
Ok, will try again now. Thx 👍

**Comment by ExaconAT** [comment]
Found the problem, it is not visible in this part of my haproxy config, added the server to other webservice backend for load balancing all http cockpit 9090, what a mistake!

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
