### ISSUE TITLE
Change hostname privilages

### ISSUE THREAD

**Issue by machadotiago** [cockpit-project/cockpit#8260]
It is common on raspbain that superuser powers are required for changing the Hostname.
Because of that we always have this error when trying to change the hostname

![image](https://user-images.githubusercontent.com/3775353/33902717-0ca0eeca-df5d-11e7-88c1-07c563dc96c8.png)

I added `superuser: "try"` to the dbus client https://github.com/cockpit-project/cockpit/blob/b4459b90700419bdddf4d799c6734c6822ab8334/pkg/systemd/host.js#L434 

and it's now working.
Can I open a PR with it or there are any better solution for that ?

**Comment by martinpitt** [comment]
Fixed in #8261, forgot to add the Fixes # to the commit message.
