### ISSUE TITLE
PCP Stops Logging when signing in to Cockpit

### ISSUE THREAD

**Issue by dcrdev** [cockpit-project/cockpit#8268]
I've noticed a strange issue where by pcp stops monitoring utilisation stats when signing into cockpit. Everything before a successful sign in is being logged, but there's a gap in the logging in between iniitiating sign-in and successful authentication.

This is on a CentOS 7.4 installation:
![screenshot_2017-12-13_18-46-57](https://user-images.githubusercontent.com/8715048/33956418-621e9b34-e036-11e7-9708-013f2c4738b6.png)

**Comment by petervo** [comment]
Does this only happen once? Or everytime you log in / log out?

@mvollmer any ideas?

**Comment by dcrdev** [comment]
It's every time I log in.

**Comment by mvollmer** [comment]
This can probably be explained by the different sampling frequencies of archived data and real-time data.

When you log in, Cockpit fills the plots with data from the PCP archives and then continues to add to the plots from real-time samples.  The archives contain samples once every minute, but real-time data is sampled once every second.

So the gap you see is for the time from the last archive sample (up-to one minute ago) to the first real-time sample.

TBH, I haven't paid a lot of attention to such gaps yet.  You might also get them when the archive data is incomplete, for example.  (I think this used to work a bit better before we introduced a more general sampling infrastructure, but I am not sure...)

What can we do?  I think 'real' gaps should be shown by not drawing any line, but artificial gaps could be smoothed out somehow.

**Comment by dcrdev** [comment]
That makes sense, although I would have expected the gap to be a lot smaller?

In any case, I think it disturbs the flow of the visualisation - arbitrarily smoothing out the difference seems like a good idea.

**Comment by mvollmer** [comment]
> That makes sense, although I would have expected the gap to be a lot smaller?

Do you expect the archive sampling frequency to be higher? Or do you see gaps that are significantly longer than one minute?

**Comment by marusak** [comment]
This is still problem. It is happening and is obviously due to different sampling rate. On my machine pcp logs every minute, but cockpit samples every second or so. So there may be up to minute gap one very login.

**Comment by martinpitt** [comment]
This page does not exist any more, and the new Metrics page does this in a different way. It should handle gaps appropriately now.
