### ISSUE TITLE
Not showing available Software Updates

### ISSUE THREAD

**Issue by dcrdev** [cockpit-project/cockpit#8269]
I would like to request if I may - clarification on the Applications/Software Updates module for cockpit. It's not clear to me what exactly is required to get this working. Is this functionality even supported on pre-dnf distros a la RHEL?

I'm using CentOS 7.4, have packagekit, but updates are not coming through to Cockpit nor are any applications available for install. So as an example - yum is currently showing 64 available updates, but cockpit once the checks are done is showing that my system is fully up-to-date.

**Comment by petervo** [comment]
Updates should be working if you have packagekit installed and working. What does

```pkcon get-updates```

output.

No applications available for install is expected, this are cockpit specific applications and depend on some new meta data fields that are not yet in widespread use. Overtime more applications should become available.

**Comment by dcrdev** [comment]
Sorry did an update since posting the issue -

As a test I downgraded wget and ran the above:
```[root@hell01-serv01 dominic]# yum downgrade wget 1.13
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirroring.pulsant.co.uk
 * centos-php71: rpms.remirepo.net
 * centos-php71-safe: rpms.remirepo.net
 * epel: www.mirrorservice.org
 * extras: centos.mirroring.pulsant.co.uk
 * updates: www.mirrorservice.org
No package 1.13 available.
Resolving Dependencies
--> Running transaction check
---> Package wget.x86_64 0:1.14-15.el7 will be a downgrade
---> Package wget.x86_64 0:1.14-15.el7_4.1 will be erased
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package         Arch              Version                Repository       Size
================================================================================
Downgrading:
 wget            x86_64            1.14-15.el7            base            547 k

Transaction Summary
================================================================================
Downgrade  1 Package

Total download size: 547 k
Is this ok [y/d/N]: y
Downloading packages:
wget-1.14-15.el7.x86_64.rpm                                | 547 kB   00:02     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : wget-1.14-15.el7.x86_64                                      1/2 
  Cleanup    : wget-1.14-15.el7_4.1.x86_64                                  2/2 
  Verifying  : wget-1.14-15.el7.x86_64                                      1/2 
  Verifying  : wget-1.14-15.el7_4.1.x86_64                                  2/2 

Removed:
  wget.x86_64 0:1.14-15.el7_4.1                                                 

Installed:
  wget.x86_64 0:1.14-15.el7                                                     

Complete!
[root@hell01-serv01 dominic]# pkcon get-updatesGetting updates               [=========================]         
Starting                      [=========================]         
Getting information           [=========================]         
Downloading lists of changes  [=========================]         
Finished                      [=========================]         
Normal      	wget-1.14-15.el7_4.1.x86_64 (updates)                       	A utility for retrieving files using the HTTP or FTP protocols
```
So pkcon shows the update, cockpit does not however:
![screenshot_2017-12-13_19-43-55](https://user-images.githubusercontent.com/8715048/33958982-fb001ede-e03d-11e7-9717-0da5c54e5d14.png)

**Comment by martinpitt** [comment]
If you open the JavaScript console (usually Ctrl+Alt+J) before opening the "Updates" page, do you get any errors? Also, do you get a quick spinner that says "checking for available updates"?

FWIW, this does generally work on CentOS, i. e. it's not a case of "known broken".

**Comment by dcrdev** [comment]
No there are no errors - a few warnings about style violations, but nothing relevant.

I've made some progress though - software updates appear, if I sign in as root. I'm assuming that signing in as root is not a requirement nor particularly advised?

My regular user account is part of the wheel group and I'm ticking the "Reuse my password for privileged tasks" box at sign-in.

**Comment by martinpitt** [comment]
Thanks. So the fact that "System is up to date" appears (internal state name `uptodate`) means that the `GetUpdates()` call was successful and did receive a `Finished`  signal, but it didn't pick up any `Package` signals. You already ruled out PackageKit being generally broken, or a permissions problem. At this point I'm afraid I don't see an obvious error and I cannot reproduce that on a CentOS 7 VM. Is it possible for me by any chance to log into your machine to investigate this? ([my ssh key](http://www.piware.de/sshkey)). If not, I can prepare some additional debug output in the packagekit module and tell you how to build and run it from the source tree.

**Comment by dcrdev** [comment]
I would say that would be alright, except I have some confidential data on the server.

Happy to build/run from source though.

**Comment by leezout** [comment]
Same problem here, freshly installed cockpit 158-1~ubuntu16.04.1 
And I am unable to see the system update panel on the web page. 
Anything that I should do ? Activate an option or ?

**Comment by petervo** [comment]
@leezout did you install the cockpit-packagekit package?

**Comment by leezout** [comment]
@petervo thanks for the quick reply ! I wasn't aware of that and now it works.

**Comment by fumbles** [comment]
/usr/libexec/packagekit-direct
Failed to load the backend: opening module yum failed : /usr/lib64/packagekit-backend/libpk_backend_yum.so: undefined symbol: pk_backend_spawn_is_busy

Cockpit visual log: refresh-cache transaction /6_acadaccb from uid 0 finished with failed after 301ms


I am having this issue as well. I should note-I upgraded from a Centos 7.6 installation so might have some dependencies from Centos stll hanging around. Cockpit -> software updates -> The backend exited unexpectedly. This is a serious error as the spawned backend did not complete the pending transaction


I'm going to poke around in the packagekit-direct and see about that error

**Comment by odyssey4me** [comment]
For future posterity, I had to install both ``cockpit-packagekit`` and ``cockpit-selinux`` for it to work as expected.

**Comment by imz** [comment]
> /usr/libexec/packagekit-direct
> Failed to load the backend: opening module yum failed : /usr/lib64/packagekit-backend/libpk_backend_yum.so: undefined symbol: pk_backend_spawn_is_busy

The "undefined symbol" error might be simply caused by an incorrect build of `packagekit-direct`, see:

* <https://github.com/PackageKit/PackageKit/issues/477>
* <https://github.com/PackageKit/PackageKit/pull/480>
