### ISSUE TITLE
[Really *CRAZY* feature request] Add WebDAV capabilities to cockpit-ws

### ISSUE THREAD

**Issue by q2dg** [cockpit-project/cockpit#8274]
Hello.

I'd be wonderful if Cockpit had a "Files" tool which allowed web user to "simply" create/delete/rename remote files and folders and, over all, to upload/download files from/to local machine to server, like "Files" module of Moodle does, for naming an example.

I suspect this is against spirit of this project but...wouldn't it be wonderful?
Thanks and sorry if this issue has disturb you

**Comment by martinpitt** [comment]
Let's see what others think, but IMHO that's a little over the top. There are lots of existing file managers out there, including nautilus+gvfs for GNOME, which implement this well.

**Comment by dcrdev** [comment]
My two cents -

Basic file manager - yes.
WebDAV client - no.

A WebDAV client just doesn't seem like something that fits into what Cockpit is trying to accomplish.

**Comment by q2dg** [comment]
@dcrdev Yes, yes, that's the idea!
@martinpitt If nautilus+gvfs had a D-Bus interfaces...I've asked to Gnome but I don't expect any response: https://twitter.com/q2dg/status/941454412890992641
Thanks a lot for considering it!

**Comment by martinpitt** [comment]
This is outside of the boundaries of what we want to in Cockpit itself. This would be a nice cockpit "Application" for someone interested, though. See also https://cockpit-project.org/blog/cockpit-starter-kit.html and https://cockpit-project.org/blog/making-a-cockpit-application.html .
