### ISSUE TITLE
VMs: should not be able to create a VM with higher specs than possible

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8279]
Splitting out from #7820 
It shouldn't be possible to create a VM with for example more RAM than what is available on the host, so we need a pattern to avoid that happening when you set up the VM.

**Comment by KKoukiou** [comment]
It makes sense to me but network manager doesn't have these restrictions. @Antique can you maybe provide feedback here if this would make sense to have?
Thanks

**Comment by KKoukiou** [comment]
It's already implemented in cockpit for memory and disk size
