### ISSUE TITLE
VMs: detect ISOs in URLs to ease installation process

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8295]
As a followup to #7820 

In the cases where the OS is delivered in ISO format, you currently need to first download the ISO, and then install it. It would be great if the UI would allow me to skip that step. There is currently a URL field, but that only work on certain OS trees.

**Comment by KKoukiou** [comment]
This is still current, we probably want to support passing remote ISO to the create VM dialog. Should be just some small change in the virt-install paramers.
