### ISSUE TITLE
Allow the motd to be set from the System page

### ISSUE THREAD

**Issue by jeepingben** [cockpit-project/cockpit#8296]
The system page of Cockpit displays the current contents of /etc/motd and allows the user to dismiss it until it has changed.  Allow the same widget to edit motd if the logged in user is an administrator.  This will probably involve adding some sort of edit button to the page on or near motd widget.  There will need to be a way to edit after the banner has been dismissed so it may need to be near instead of in the banner display widget.

**Comment by martinpitt** [comment]
This makes sense to me at first sight. @garrett, @andreasn , WDYT?

**Comment by jeepingben** [comment]
![screen shot 2017-12-27 at 10 50 26 am](https://user-images.githubusercontent.com/8668066/34386295-eeca6238-eaf5-11e7-974a-59846ee8bcfa.png)

What if there is a clickable item in the info table that is displayed only when the MOTD isn't being displayed?

For admins, the motd box could be clickable to bring up an edit modal
![screen shot 2017-12-27 at 11 00 57 am](https://user-images.githubusercontent.com/8668066/34386224-a5aa947e-eaf5-11e7-8478-1747503ff77a.png)

**Comment by garrett** [comment]
Yeah, I agree that it should be editable by admins.

The icon used for editing should be `pficon-edit`, and it should have the word "Edit" following behind it.

![screenshot-2018-1-25 icons patternfly](https://user-images.githubusercontent.com/10246/35399045-aadd0c50-01f3-11e8-8ded-b2afecf9c494.png)
_This is the edit icon, for reference._

- There's too much space to the side of the textarea
- Save and Cancel buttons are switched around in this mockup
- Save (which should be on the right) should be primary colored (blue), as it is the default action
- Text in the textarea should be monospaced
- There should probably be an indicator of 80 (or 72 perhaps?) character column width
  - this could probably even be done with a background gradient that has a 1px width at `72ex`
  - ...or an `:after` with content, a left-margin of `72ex`, and `pointer-events: none`

But these are all minor nitpicky details (important for the implementation); I like the concept.

**Comment by recteurlp** [comment]
Hi,

Could you enable the color for motd ? or at least delete ASCII color codes in the output ?

I got things like:

```
The system has [36m8[0m cpus.
```
Maybe some support for color in edit mode too ?

Would you like another issue for this ?

Best Regards,

**Comment by andreasn** [comment]
> Could you enable the color for motd ? or at least delete ASCII color codes in the output ?

Interesting idea. Let's do it as a followup, so it doesn't block fixing this issue. Let's keep this one simple and focused on editing the string.

**Comment by martinpitt** [comment]
@jeepingben: To clarify, are you working on such a feature and the above was a screenshot? Or was it just some mockups, and you want someone else to implement this?

**Comment by jeepingben** [comment]
That was a mockup.  I haven't done any work on this since its in design.  If someone else wants to take it, that would be great.
