### ISSUE TITLE
OpenShift registry web console does not scale well with large amount of images, tags

### ISSUE THREAD

**Issue by dmsimard** [cockpit-project/cockpit#8310]
Hi,

We're currently using OpenShift 3.7.

We don't make use of the web console very much but I thought you might be interested in potential improvement opportunities when cockpit is used for the atomic/openshift registry web console.

Our use case leads us to build 125 images over 12 times a day (rolling >5000 tags a week, we delete tags older than 7 days).
The interface does not work very well -- it feels like the asynchronous background loading is impacting the interface.

For example, when I log in to the interface, I'm shown the familiar dashboard:

![dashboard](https://i.imgur.com/8qtBAaL.png)

However, when I try to click on a tag, it doesn't seem to work until I let the interface load for a while (presumably until it finishes loading everything) and then clicking on a tag works.
When I successfully click on a tag, the browser hangs for a bit (Firefox 57 on Fedora) but then all the tag metadata appears properly.

This experience is made worse when there are new images being pushed while you are logged on to the web console. New images being pushed will be displayed automatically and asynchronously as they are pushed and it makes it near impossible to click on anything.

I'm happy to provide some data (or even access to the interface, it's a public registry) if you would like to troubleshoot this. I don't really know where to begin so let me know what you would need.

Thanks !

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
