### ISSUE TITLE
Wrong scale on system memory detail page

### ISSUE THREAD

**Issue by powerriegel** [cockpit-project/cockpit#8315]
Hello,

On my Debian Stretch,  Cockpit shows on the overview page the correct amount of RAM (4 GB). 3 GB are used. `htop` says my RAM is half free. 

Then I click on Memory. The diagramm gets colorful and my RAM amount increases magically to 6.7 GB (4.7G used). 

https://screenshots.firefox.com/3BRFcLVex4bRgJp1/192.168.170.11
https://screenshots.firefox.com/qnA2KIo79rE20k5T/192.168.170.11

Really strange...

**Comment by petervo** [comment]
Dup of #8251
