### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by golimer** [cockpit-project/cockpit#8334]
hello 
installed un ubuntu and can't login 
`Wrong user name or password`
Logs:
Jan  2 08:26:46 ip- cockpit-session: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=172.*.*.*  user=user123
Jan  2 08:26:46 ip- cockpit-session: pam_sss(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=172.*.*.* user=user123
Jan  2 08:26:46 ip cockpit-session: pam_sss(cockpit:auth): received for user user123: 10 (User not known to the underlying authentication module)

**Comment by martinpitt** [comment]
Does `getent passwd user123` succeed, i. e. does that user actually exist? Also, it seems you put a remote host into the "Connect to:" input line; does that `user123` actually exist on that host, i. e. 172...?

**Comment by golimer** [comment]
Yes user exist "user123:x:1002:1002::/home/user123:" +password

**Comment by martinpitt** [comment]
Can you confirm that `ssh user123@172..` (the host you put into "Connect to") works? It seems either the password is wrong or ssh is not configured correctly on the remote machine you are logging into.

**Comment by golimer** [comment]
Jan  2 10:34:42 ip-10-37-27-35 systemd: pam_unix(systemd-user:session): session opened for user user123 by (uid=0)
Jan  2 10:34:42 ip-10-37-27-35 systemd-logind[1330]: New session 5 of user user123.

**Comment by martinpitt** [comment]
Did you install Cockpit from official backports, or with something like `make; sudo make install` from upstream? In the latter case the PAM config will need some adjustment. Can you please copy&paste the output of `dpkg -l cockpit-ws` and `dpkg -S etc/pam.d/cockpit`?

From the logs in the initial description it appears like it is trying to log `user123` into the host that runs the cockpit web server, not the remote 172.* host.

**Comment by golimer** [comment]
/var/log/auth.log
cockpit-session: pam_sss(cockpit:account): Access denied for user user123: 10 (User not known to the underlying authentication module)

`dpkg -l cockpit-ws`
/etc/pam.d# dpkg -l cockpit-ws
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                              Version                       Architecture                  Description
+++-=================================================-=============================-=============================-=======================================================================================================
ii  cockpit-ws

`dpkg -S etc/pam.d/cockpi`
dpkg -S etc/pam.d/cockpit
cockpit-ws: /etc/pam.d/cockpit

**Comment by golimer** [comment]
any help regarding this?

**Comment by martinpitt** [comment]
I still wonder where the `pam_sss` bit comes from. Can you please attach /etc/pam.d/cockpit and all the files that are printed out by `grep -rl sss /etc/pam.d`.

By the way,  that PPA is becoming outdated quickly. Rather install cockpit from the official backports (see [install instructions](http://cockpit-project.org/running.html#ubuntu)). But this shouldn't make a difference, the PAM config didn't change recently.

**Comment by cloud-rocket** [comment]
* I am running into this issue on GCP (users are created automatically and available under `/etc/passwd`)
* Installed Ubuntu 18.04 minimal
* Installed `cockpit` with `apt install cockpit`

`/var/log/auth.log` reports:

```
Feb 25 12:17:54 cockpit cockpit-session: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=10.142.0.7  user=myuser

``` 

Any idea?

**Comment by martinpitt** [comment]
No reply in 10 months to the outstanding "needs info" request above, closing.
