### ISSUE TITLE
show disk usage with more precision

### ISSUE THREAD

**Issue by Kurairaito** [cockpit-project/cockpit#8361]
Dear,

I have a disk of 1.1TB and Cockpit report it as 0.2 / 1.1 TiB, incrementing by 0.1TB.
So disk usage is reported 10% per 10% and is not accurate at all.

how can I report thoses value in GB instead ?
if not possible how can I add more numbers after the dot? (report 0.159TB instead of rounding it to 0.2TB)

I use the version provided in ubuntu server artful repo  :

> $ cockpit-bridge --version
> Version: 151
> Protocol: 1
> Payloads: dbus-json3 http-stream1 http-stream2 stream fsread1 
>     fsreplace1 fswatch1 fslist1 null echo websocket-stream1 
> Authorization: crypt1

in the picture attached, the difference with eSM for example which is more accurate
![storagediff](https://user-images.githubusercontent.com/11020393/34580511-9aaff2be-f18d-11e7-91de-243aa6fd42f4.png)

best regards,

thanks.
Kurairaito

**Comment by petervo** [comment]
Cockpit doesn't support customization of display units. In the details pane the numbers are broken down a little more. Note the numbers are TiB not TB.

@andreasn or @mvollmer any suggestions for how we might perhaps display a little more precision without cluttering things up too much?

**Comment by martinpitt** [comment]
@Kurairaito : At least on my system the actually reported numbers are correct, i. e. they are really in GiB/TiB, not GB/TB. Compare with the output of `df -h` which also uses the base-2 units (you can use `df --si` to get base-10 units). I don't think this is system/hardware specific, so for the time being I assume the actual numbers and units are correct, and apparently the units in eSM are wrong (MB is base-10, but the number is MiB, i. e. base-2).

So retitling this about increasing the precision. I agree it makes sense to show more than just two significant digits (e. g. 0.1 TiB should better be something like 829 GiB, and 1.1 TiB should be 1.07 - three or four digits feel right).

**Comment by mvollmer** [comment]
I think we can simple use more digits when showing usage numbers.  @Kurairaito, what do you use the numbers for?

**Comment by Kurairaito** [comment]
Hi,
Yes the numbers are in TiB, it was a confusion from my side.
I also found the detail when going in the partition and then expanding it, the precision is much better because the size is written as 816GiB/1.1TiB

I use those numbers for monitoring a fast growing database, to check remaining space before taking an action.

Having more precision would be a great thing ! (the same as in detail would be great, the software can already write it in GiB)

Thanks.
