### ISSUE TITLE
CPU Graph showing usage greater than 100% (version 151)

### ISSUE THREAD

**Issue by egee-irl** [cockpit-project/cockpit#8373]
I'm running Cockpit version 151 on my server where I run a small cluster of Docker containers. The resource usage I am seeing in Cockpit does not match the usage which Docker is reporting, nor the usage that htop is reporting.

Here's a set of screenshots of what I am seeing - https://imgur.com/a/k5km6

The only way the Cockpit numbers would make sense is if 100% = 1 full core. But that is misleading at best. If that is the case, I would consider this a bug as that is a relatively uncommon way of calculating CPU usage.

Use case - I've got a 12 core CPU, so it shows the max usage at 1200%? That is just silly.

**Comment by mvollmer** [comment]
> The only way the Cockpit numbers would make sense is if 100% = 1 full core.

Yes. that's the idea.  I think it comes from the 'top' command, which defaults to this ("Solaris" mode) for %CPU of individual processes.

> But that is misleading at best. If that is the case, I would consider this a bug as that is a relatively uncommon way of calculating CPU usage.

I agree.
