### ISSUE TITLE
Provide X for the Journal Details Dialog 

### ISSUE THREAD

**Issue by LHinson** [cockpit-project/cockpit#838]
When I click on a Journal line with a number to get more details, some of these details are quite lengthy. At one point I wanted to quickly close and couldn't do so until I scrolled down to the Close button. It would be faster and easier for me to close the dialog if there was an X in the top right corner (in addition to the close button at the bottom) as seen in the PF dialogs here: https://www.patternfly.org/widgets/#modal

This would be a good first step but I will look and see if other products use a max height for dialogs. I'll report back with what I find out.

**Comment by dperpeet** [comment]
The details are on a separate page.
