### ISSUE TITLE
storage: no inline documentation for unfamiliar concepts of VDO devices

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8391]
Terry was a bit worried that we're introducing a lot of new concepts and vocabulary without really explaining it.

We'll need some inline documentation to more thoughtfully explain some of the concepts and upsides and downsides of the different options when you create a VDO device.

Video: https://youtu.be/_iOYN4Y24aY?t=45s

**Comment by andreasn** [comment]
Compression - "Saves space by compressing data"
Deduplication - "Saves space by eliminating duplicate data"

**Comment by andreasn** [comment]
New suggestions:

**Compression**
_Save space by compressing individual data blocks with a LZ4 compression_

**Deduplication**
_Save space by not writing out data blocks for when a copy of that data is already found_

**Transfer data asynchronously**
_Writes are acknowledged before being written to persistent storage. 
VDO must be set to async mode if the underlying storage does not guarantee that data is written to persistent storage when the write command completes; that is, when the storage has a volatile write back cache. 
It is critical to set the VDO write policy to match the behavior of the underlying storage._

Still struggling with the 512 byte emulation...

**Comment by andreasn** [comment]
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/storage/data-reduction-inlinehelp.png)

**Comment by andreasn** [comment]
> Save space by compressing individual blocks with LZ4

Sounds good to me.

>  deduplication: possible shortening to Save space by storing identical data blocks just once (feel free to ignore, but shortening might be relevant if it's not a tooltip)

It will be a tooltip, but shortening is better overall, so let's go for your suggestion.

> async: ok, there's no way to cram that into the dialog, this should be a tooltip :-) While this is semantically ugly (if it's so critical, then VDO itself should just pick the right setting), we have to cope with this for the time being. It still bears the question how the user would actually determine "the behaviour of the underlying storage", though.

The VDO team is working on making this setting go away, by doing the right thing out of the box, but we'll need to carry this setting a bit longer until this is resolved.

> 512 byte emulation: do you know if this affects particular hypervisors only, or all of them? We might call systemd-detect-virt to detect this and pick the right default, or even hide the option completely.

Right now it affects both VMware and RHV, according to Louis. Work is underway to get rid of this issue on the RHV hypervisor.

**Comment by martinpitt** [comment]
async option is being removed in PR #8679 as per the VDO team's request. So the one with the really long (and still not fully sufficient) documentation is going away \o/

**Comment by martinpitt** [comment]
This has had a nice design for a while, and we should really just implement this. Tagging good-first-issue, that's maybe something for @marusak soon?

**Comment by marusak** [comment]
Sounds great. Feel free to assign me to any tasks you feel are suitable - at least I will know what to work on :)
