### ISSUE TITLE
check-sosreport : Use real browser download instead of curl

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#8416]
There used to be trouble with downloading files with PhantomJS.  Maybe this is better now with CDB.

**Comment by mvollmer** [comment]
@martinpitt, @larskarlitski, any quick thoughts?

**Comment by larskarlitski** [comment]
Yeah there are a couple of places that have workarounds for phantomjs. We decided to address those in follow-ups to the switch.

Thanks for reporting this!

**Comment by martinpitt** [comment]
I adjusted the bug title accordingly. There is a [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=696481) about file downloads not working properly with headless. The "tip of tree" version of the DevTools protocol has an experimental [Page.setDownloadBehaviour()](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setDownloadBehavior) call to control this. I'm not sure if our current chromium 63 already supports this, so this is subject to experimentation. If/once it works, switching the test to do a real browser download would be much nicer indeed.

**Comment by martinpitt** [comment]
Implemented in PR #9990.
