### ISSUE TITLE
atomic-registry-cockpit is unable to set CA data

### ISSUE THREAD

**Issue by roysjosh** [cockpit-project/cockpit#8421]
Following http://docs.projectatomic.io/registry/latest/registry_quickstart/administrators/index.html#registry-quickstart-administrators-index and then attempting to use organizationally-valid certificates according to https://github.com/cockpit-project/cockpit/tree/master/containers/kubernetes#kubernetes-certificate-authority is not working.  After configuring the registry, console and master to all use org certs I get the following error during login:
Authentication failed: internal-error: Couldn%27t connect to the api: Get https:%2F%2Four.fqdn.example.com:8443%2Fapi: x509: certificate signed by unknown authority

A packet capture shows the console requesting and receiving the correct org cert and then rejecting it as unknown.  Digging more, it looks like KUBERNETES_CA_DATA doesn't seem to work properly.  In [pkg/kubernetes/standalone/src/cockpit-kube-auth/helpers/client.go](https://github.com/cockpit-project/cockpit/blob/master/pkg/kubernetes/standalone/src/cockpit-kube-auth/helpers/client.go) the CA data is read from KUBERNETES_CA_DATA and passed to [pool.AppendCertsFromPEM](https://github.com/golang/go/blob/9745eed4fd4160cfbf55e9dbbfa99aca5563b392/src/crypto/x509/cert_pool.go#L106).  That function appears to only parse [newline separated PEM certificates](https://github.com/golang/go/blob/9745eed4fd4160cfbf55e9dbbfa99aca5563b392/src/encoding/pem/pem.go#L74).  I can see no way to pass a valid certificate with embedded newlines in an env-file (docker/compose#3527).  A small test program, basically copying the code from client.go, validated these assumptions:

```Go
package main

import (
	"crypto/x509"
	"fmt"
	"io/ioutil"
	"log"
	"os"
)

const CA_PATH = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"

func main() {
	var caData []byte = nil
	var pool *x509.CertPool

	data := os.Getenv("KUBERNETES_CA_DATA")
	if data != "" {
		caData = []byte(data)
	}

	if caData == nil {
		var err error
		caData, err = ioutil.ReadFile(CA_PATH)
		if err != nil {
			log.Println(fmt.Sprintf("Couldn't load CA data: %s", err))
		}
	}

	if caData != nil {
		pool = x509.NewCertPool()
		pool.AppendCertsFromPEM(caData)
		fmt.Println("cert pool: ", pool)
	}
}
```

```
$ export KUBERNETES_CA_DATA=MIIF...
$ go run test.go
cert pool:  &{map[] map[] []}
$ read -d '' KUBERNETES_CA_DATA < /path/to/root.pem
$ go run test.go
cert pool:  &{map[???F?o??R{h??r??:[0]] map[0p1
... more cert gobbledegook ...
```

I'm not sure how to set secrets in an atomic-registry install but it looks like the CA_PATH branch of the code should work.

**Comment by petervo** [comment]
I thought you could set env vars with new lines if you set them in your json object definition file.

But if that isn't working you should be able to configure openshift/kubernetes to mount it's CA chain in /var/run/secrets/kubernetes.io/serviceaccount/ca.crt then you don't set the env var KUBERNETES_CA_DATA. Is that not working for you either?

**Comment by roysjosh** [comment]
I probably can mount a volume at that directory.  I had to mount one at /etc/cockpit/ws-certs.d to get the server cert and key in place.  I'm still figuring all of this out but it seems like if there is a way to set a secret for the console in an Atomic Registry install I should do that instead.

**Comment by petervo** [comment]
If you have ```ServiceAccount``` in your admission-control settings, openshift should setup the secrets for you automatically.

**Comment by roysjosh** [comment]
Hm, I may be up a creek without a paddle.  I'm following the [Atomic Registry install](http://docs.projectatomic.io/registry/latest/registry_quickstart/administrators/index.html#registry-quickstart-administrators-index) which according to the info block near the top of https://docs.openshift.org/latest/install_config/install/stand_alone_registry.html is a somewhat different set up than normal:

> OCR should not be confused with the upstream project Atomic Registry, which is a different implementation using a non-Kubernetes deployment method that leverages systemd and local configuration files to manage services.

**Comment by martinpitt** [comment]
Is this still an issue for you? I'm afraid we don't have anyone in the Cockpit team any more with that level of OpenShift knowledge.

**Comment by roysjosh** [comment]
We went with a full blown OpenShift install so I can't say. You can close
this out.

**Comment by martinpitt** [comment]
Ack, thanks.
