### ISSUE TITLE
Replace bots/whitelist with GitHub team member/contributor check

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8427]
Apparently it is necessary to add new contributors who want to actually be able to (re-)trigger tests to the  [Contributors team](https://github.com/orgs/cockpit-project/teams/contributors/members). This means we could cut out our explicit [whitelist](https://github.com/cockpit-project/cockpit/blob/master/bots/whitelist) and replace them with a GitHub API call.

https://api.github.com/orgs/cockpit-project/members is one such list, but only contains very few people, this needs some more comprehensive team checks as per https://developer.github.com/v3/orgs/teams/ .

**Comment by chdigvijay20** [comment]
Hi @martinpitt ,
I would like to work on this.
After going through github api I have figured out the api call to get the list of contributors, [https://api.github.com/repos/cockpit-project/cockpit/contributors](url).
I think changes will be needed in following things:
In file **bots/task/github.py**, change `def whitelist(filename=WHITELIST)`
In file **bots/task/test-github**, there will be changes in `class TestWhitelist(unittest.TestCase)`

Please tell if I can work on this.

**Comment by martinpitt** [comment]
Also to bots/issue-scan and bots/tests-scan, unless you actually keep the `github.whitelist` API - but feel free to change it of course if that's inconvenient.

> Please tell if I can work on this.

Of course, thanks for your interest!

**Comment by chdigvijay20** [comment]
Hi, thanks!
One query, [this page](https://github.com/cockpit-project/cockpit/graphs/contributors) shows list of all contributors, which are around 92. Should we whitelist all of these?

**Comment by martinpitt** [comment]
I think this is a reasonable list to start with. The main function of the whitelist is to prevent overly abusing the CI infra, but if we ever notice that it does get abused, we can dial that back. But so far we haven't had the "problem" of getting too many PRs from external contributors :-)

**Comment by chdigvijay20** [comment]
Till now I have changed following code.

def whitelist():

    api = GitHub()
    whitelist = []
    page_number = 1
    while True:
        resource = 'https://api.github.com/repos/cockpit-project/cockpit/contributors?page='+str(page_number)
        response = api.request(method='GET', resource=resource)

        user_list = json.loads(response['data'])

        if len(user_list) == 0:
            break

        whitelist += [user['login'] for user in user_list]
        page_number += 1

    return set(whitelist)

Though this will work, I am not sure about how I should handle exceptions in above code.
Also is this correct way? One more way I think is adding `contrubutors()` method in GitHub class which will return the list. What do you think?

**Comment by martinpitt** [comment]
I think for now it's fine to just directly do the `/contributors/` request in `whitelist()`; we can split it out later if we need to use it somewhere else. I think you shouldn't handle exceptions - for this purpose it's fine to just crash with an exception, this is easy and familiar enough for us developers to see in the logs.

There's some stylistic issues:

 - just use `if not user_list:`
 - rename the variable `whitelist` to e. g. `users` to not be the same as the function name, and make it a set right away
 - use `users.update([ ... ])` for the set update

Nice work so far, thanks!

**Comment by chdigvijay20** [comment]
Ok. will do the changes.

**Comment by dennisotugo** [comment]
@chdigvijay20 Any update or is this an open issue?
