### ISSUE TITLE
No containers when moving docker root dir

### ISSUE THREAD

**Issue by justyntemme** [cockpit-project/cockpit#8428]
After moving my docker root directory that hosts all my containers to a different partition I am not able to see resources on containers from cockpit.

I would be willing to help solve this issue, I'm assuming it's using the default directory rather than parsing `docker info` for the root directory variable.

**Comment by petervo** [comment]
This is where the setup happens.

https://github.com/cockpit-project/cockpit/blob/master/pkg/docker/client.js#L390

The api is assumed to be at /var/run/docker.sock but the directory comes from info using DockerRootDir

**Comment by justyntemme** [comment]
Ah I must also add I am using docker CE instead of the Fedora packaged version. I am running Fedora 27 with latest updates.

**Comment by justyntemme** [comment]
When uninstalling the fedora docker package it uninstalled cockpit-docker. After reinstalling we are working flawlessly.
