### ISSUE TITLE
machines: VM console can not be interact with sometimes

### ISSUE THREAD

**Issue by AlertBear** [cockpit-project/cockpit#8438]
## Test versions:
cockpit-159-1.el7.x86_64
cockpit-machines-159-1.el7.x86_64
firefox-57.0.1(On Fedora27)
chrome-59.0.3071.115(On Fedora27)
## Test steps:
- Senario1:
1. Open console, can input words to terminal in console
2. Click other buttons, like network or storage
3. Change back to console, then can not type words into terminal in cosole, have to refresh
- Senario2:
Create a vm via virsh, but do not start it beforehand. Open web, click follow the sequence:vm, Consoles, Run. The vnc console cannot be shown
- Senario3:
While installing OS via iso to vm from console, can not input password during installation phase, have to refresh.

**Comment by KKoukiou** [comment]
@AlertBear is that still valid? https://github.com/cockpit-project/cockpit/pull/8894 is already merged which addresses these.
