### ISSUE TITLE
Properly localize numbers

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8445]
We currently don't properly localize numbers  with thousands or decimal separators. E. g. when switching language to German, the network page shows:

![numbers-net](https://user-images.githubusercontent.com/200109/35085453-16d76034-fc29-11e7-9dbd-f9df330afc1f.png)

and the storage page shows:

![numbers-storage](https://user-images.githubusercontent.com/200109/35085454-17b565f0-fc29-11e7-922e-66c3ff381ebc.png)

Our [localization API](http://cockpit-project.org/guide/latest/cockpit-locale.html) does not have a function for formatting numbers according to the current locale, but I figure we don't really need one: Our code could just use

    >> n = 1234.56
    >> n.toLocaleString(cockpit.language)
    "1.234,56"

If we add an API to base, we need some fallback anyway as we might run against an older cockpit-bridge package (like on RHEL or with containers).

**Comment by allisonkarlitskaya** [comment]
cockpit.format_number() in already contains this comment:

        /* TODO: Make the decimal separator translatable */

        /* We show 3 digits of precison but avoid scientific notation.
         * We also show integers without digits after the comma.
         */

Would implementing this change there be considered an API break in your opinion?  If not, do we basically need to go all over the place, changing each separate location?

**Comment by martinpitt** [comment]
`format_number()` is explicitely for turning a `Number` into a humanly readable string, so respecting the locale there is IMHO not an API break. There's also precedent: In commit 0218d776ca1acab we recently changed the precision of that function.

IMHO fixing it centrally is better than wrapping all invocations of this with `toLocaleString()`. This also provides better consistency when mixing newer cockpit-* extension packages with an older cockpit-system (as happens in RHEL).
