### ISSUE TITLE
machines: xen support

### ISSUE THREAD

**Issue by Fnux** [cockpit-project/cockpit#8461]
Hello,

I would be glad to see [xen](https://www.xenproject.org/) supported in cockpit-machines. It should not be too difficult since [libvirt supports xen](https://libvirt.org/drvxen.html).

Is #7484  (in order to use the `xen:///` URI for libvirt)  the only issue on the way ?

Thanks!

**Comment by mareklibra** [comment]
The URI will be configurable to whatever (almost) working along libvirt. So in this context, xen might be supported. Please stay tuned :-), will you be able to help with testing or even implementation?

**Comment by Fnux** [comment]
I don't think I find enough time to implement it myself in the next weeks [0] (I'm rather busy with exams right now), but would be glad to help testing.

[0] later, perhaps.

**Comment by martinpitt** [comment]
This is not within the plans and focus of the Cockpit team, sorry. Xen has been a deprecated technology in Fedora, RHEL, AWS, colo hosters, etc. for many years, in favor of kvm. Supporting all/many of the features that we currently have for virtual machines (storage pools, networking config, etc.) would be a huge task for very little benefit at this point, sorry.
