### ISSUE TITLE
Graphical issues mobile interface

### ISSUE THREAD

**Issue by mbastiaan** [cockpit-project/cockpit#8464]
There are some small graphical issues when viewing Cockpit on a mobile phone with a 1280x720 screen.

- In portrait mode the login screen has overlapping name (Fedora Server Edition in my case) and Cockpit logo.
- Sometimes it's impossible to scroll a page up/down, closing browser the tab and reopening Cockpit solves the problem (not sure if this is actually a Cockpit problem, but it's the only website I have this problem with). 
- On the System page the Machine ID is so long it runs off screen. There is plenty of white space on the left so maybe change the alignment a bit to make everything fit without causing the page to be scrollable.
- On various pages in portrait mode there are too many buttons next to each other causing some of them to be placed on a next line (Network and Services for example), going outside their intended place on the interface and messing up alignments. 
- The tables on the Services page are a mess on this resolution.

**Comment by garrett** [comment]
Hi @mbastiaan; thanks for filing this! 

The mobile UI is basically an alpha preview at this point and needs more work overall. Thanks for trying it out and sharing your feedback; it helps to identify and prioritize the issues.

Firstly: Which phone and browser are you using?

1. Could you take a screenshot of the login screen on your phone and attach it here?
   * On Android, you should be able to take a screenshot by holding power and volume down.
2. Do you know which specific pages have issues with scrolling?
3. Can you attach a screenshot of the system page with the long machine ID please?
4. Yeah; the mobile effort thus far has mainly been the navigation. It was a first step. There are definitely problems with many pages (especially the more complex ones, like Network and Services).
5. Yes, tables on Services: same as # 4.

Some of these might be able to be solved quickly, once I can see the problem and reproduce it. Others will probably take additional effort (items 4 & 5).

**Comment by mbastiaan** [comment]
Hi,

I'm using a Samsung A3 (2017) with Firefox Beta.

1: 
![20180208_200436](https://user-images.githubusercontent.com/35669404/35994197-ff09a96a-0d0f-11e8-9e55-871ba2b0779c.png)
2: All pages. Right now I just went from System to Network to Storage to System and none of the pages are scrolling.
3: On the desktop version it cuts off the ID after '1bbd' and replaces the rest with ... and the full value is visible in a tooltip.
![20180208_202919](https://user-images.githubusercontent.com/35669404/35994198-ff31b036-0d0f-11e8-9b08-8d52dbaaa5a5.png)
4/5: I like the navigation so far and it certainly has potential to become a very useful tool. :)

**Comment by garrett** [comment]
I fixed the login and system page issues mentioned above and split the two remaining problems into separate issues (#8672 & #8673).
