### ISSUE TITLE
Base Cockpit installation shows odd behavior in accounts page

### ISSUE THREAD

**Issue by jhorigan** [cockpit-project/cockpit#8476]
Hello,

When the view returns to the main "Accounts" view after creating a user, the new user information will appear below the list of account names in an editor panel.  

Also, the browser returns to the "Accounts" view after deleting a user account the deleted user appears in the editing panel beneath the list of accounts even though the user no longer exists on the system. 

Steps to recreate:

Video attached

Requirements:  CentOS 7 server with Cockpit installed and configured

1)  Log in to the Cockpit web UI and navigate to the "Accounts" view.

2)  Click on any account to open the account editor page. 

3)  Move back to the main "Accounts" view.  (It does not matter whether or not changes are made in the editor.)

4)  Click the create new account button, fill out the "pop-up" form to create a new account, then click the "Create" button.

5)  When the view returns to the main "Accounts" view, the last edited user, (from step 2), will appear below the list of account names in an editor panel.  (This is unexpected behavior.)

6)  Delete the newly created user by clicking on the name and selecting the "Delete" button in the upper right hand corner of the editor.
 

OBSERVED:  When the browser returns to the "Accounts" view the "last edited user" appears in the editing panel beneath the list of accounts even though the user no longer exists on the system.

EXPECT:  The User Editor panel should only appear when actively editing a user account.

ATTACHMENT:  
[Cockpit-User-Editor-bug.mp4.gz](https://github.com/cockpit-project/cockpit/files/1656536/Cockpit-User-Editor-bug.mp4.gz)

**Comment by jhorigan** [comment]
ADDENDUM:  Test and recreation was seen on Cockpit 155-1.el7.centos.

**Comment by jhorigan** [comment]
Package information:
yum list installed |grep -i cockpit
cockpit.x86_64                       155-1.el7.centos                  @extras  
cockpit-bridge.x86_64                155-1.el7.centos                  @extras  
cockpit-dashboard.x86_64             155-1.el7.centos                  @extras  
cockpit-system.noarch                155-1.el7.centos                  @extras  
cockpit-ws.x86_64                    155-1.el7.centos                  @extras

**Comment by mvollmer** [comment]
Confirmed with Cockpit master on Fedora 27.  I'll take this.

**Comment by deryni** [comment]
I believe this mostly duplicates #4793 so that should also get closed by this fix.

**Comment by mvollmer** [comment]
> I believe this mostly duplicates #4793 so that should also get closed by this fix.

Yes, looks like it.  Thanks for mentioning this!

**Comment by deryni** [comment]
jhorigan and I found this issue together, I tried to look into it to see if I could fix it but got lost in the navigation, callback, indirection, etc. involved in how the pieces involved interacted.

@mvollmer For my own edification, and improved ability to fix things in the future, would you be able to tell me how you figured out the problem (or even just how you approached doing so) and came to this solution? (I understand if the answer is "no".) Thank you.
