### ISSUE TITLE
machines: Failed to open the remote console after click the "Launch remote viewer"

### ISSUE THREAD

**Issue by AlertBear** [cockpit-project/cockpit#8497]
Description of problem:
Failed open the remote console after click the "Launch remote viewer"

Version-Release number of selected component (if applicable):
firefox-57.0.1 (64-bit)
cockpit-machines-159-1.el7.x86_64
cockpit-bridge-159-1.el7.x86_64
cockpit-ws-159-1.el7.x86_64
cockpit-system-159-1.el7.noarch
cockpit-159-1.el7.x86_64
RHEL-7.5-20180116.0
libvirt-3.9.0-7.el7.x86_64
virt-viewer-6.0-1.fc27.x86_64

How reproducible:
100%

Steps to Reproduce:
1. Install cockpit-machines package
2. Create a vm via libvirt
3. Click the console tab, choose "Grahphics Console in Desktop viewer"
4. Launch remote-viewer button

Actual results:
1.After step#4, the vm console can not be shown

Expected results:
1. After step#4, the VM console can be shown

Additional info:
1. The virt-viewer was already installed on my system.
2. The console can be shown via CLI "remote-viewer vnc://$hostip:$port" on my system.

**Comment by qiyuann** [comment]
The vm was created by `virsh define vm.xml`, and the listen address was configured to 0.0.0.0 in vm.xml,
in this case, Launch Remoter Viewer would fail.
If configure the listen address to the host ip, then Launch Remoter Viewer could succeed.
So, this is related to ip:port configuration.

**Comment by mareklibra** [comment]
So this will be fixed within #8140.
Please reopen if you thing otherwise.
