### ISSUE TITLE
machines: The VMs can not be shown via IE11

### ISSUE THREAD

**Issue by AlertBear** [cockpit-project/cockpit#8498]
Description of problem:
The VMs can not be shown via IE11

Version-Release number of selected component (if applicable):
cockpit-machines-159-1.el7.x86_64
cockpit-bridge-159-1.el7.x86_64
cockpit-ws-159-1.el7.x86_64
cockpit-system-159-1.el7.noarch
cockpit-159-1.el7.x86_64
RHEL-7.5-20180116.0
libvirt-3.9.0-7.el7.x86_64
ie-11.0.9600.18860

How reproducible:
100%

Steps to Reproduce:
1. Install cockpit-machines package
2. Create a vm via libvirt, the vm can be shown on cockpit-machines page over chrome and firefox
3. Access the cockpit-machines page via IE11

Actual results:
1.After step#3, the vm can not be shown, "No vm is running or defined on this host"

Expected results:
1. After step#3, the vm can be shown

**Comment by stefwalter** [comment]
CC @mareklibra

**Comment by mareklibra** [comment]
IE11 does not support some JavaScript functions, like Object.assign.
I will push a fix.

**Comment by qiyuann** [comment]
@mareklibra , it seems the VM still cannot be shown on IE11. Here are the components versions:
cockpit-machines-160-3.el7.x86_64
cockpit-bridge-154-3.el7.x86_64
cockpit-system-154-3.el7.noarch
cockpit-154-3.el7.x86_64
cockpit-ws-154-3.el7.x86_64
libvirt-3.9.0-13.el7.x86_64
RHEL-7.5-20180228.1
ie-11.0.9600.18860

**Comment by kenzhaoyihui** [comment]
cockpit-machines-ovirt-162-1.el7.centos.noarch also met this issue.

**Comment by mareklibra** [comment]
@qiyuann , first version with the #8523 fix is 161.

@kenzhaoyihui , can you please send logs (press F12)? This works for me on recent master:
![ie11](https://user-images.githubusercontent.com/17194943/36974927-b86bb472-2078-11e8-86a3-13773c5a2f26.png)

**Comment by mareklibra** [comment]
There's a similar issue on the `Disks` subtab which I'm about to fix, but the main page loads fine for me.

**Comment by kenzhaoyihui** [comment]
## Version: cockpit-machines-ovirt-162-1.el7.centos.noarch

![cockpit-ie11](https://user-images.githubusercontent.com/18360375/37010638-167d2936-20b2-11e8-9f27-324b1fe2f1e6.png)

**Comment by mareklibra** [comment]
@kenzhaoyihui , I was able to reproduce this on cockpit-machines-ovirt-162 as well, but not on recent master (fixed by #8774). Can you please re-try once 163 is released? Thank you.

Btw. you are facing known IE 11 issue (see https://stackoverflow.com/questions/28301393/an-error-has-ocurredjsplugin-3005). Please install the patch in case you need to access console logs.

**Comment by kenzhaoyihui** [comment]
VMs can be shown on the cockpit  on cockpit-machines-ovirt-163-1.el7.centos.noarch from IE11.
