### ISSUE TITLE
Support filesystems that are not on a block device

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#8502]
Sometimes a proper filesystem is not on a block device, and UDisks doesn't know anything about it.  Still, it would be useful to list it in the overview and show usage statistics about it.

One example is having the rootfs on simfs in some hosting situation.

One challenge is that we don't want to show /proc etc.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

We are sorry, but we won't be able to address this in any time soon.
If you are interested in helping us with the implementation, please comment here.
