### ISSUE TITLE
After fe488aa calling only `webpack` does not build manifest.json files

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#8507]
I've used "Working on your local machine" section from HACKING.md for develoment (ln /dist and webpack).
But after fe488aa this does not seems to work. After I do all steps and log in into cockpit, it acts like there is no symlink to the dist.
When I do `git revert fe488aa` then it works again as expected.

Is there some way how to make this work again?

**Comment by martinpitt** [comment]
I do this all the time, i. e. `ln -s ~/upstream/cockpit/dist ~/.local/share/cockpit`, and it works fine. Can you please be more specific  what the error is? What's the output of `cockpit-bridge --packages`?

Did you try `git clean -fdx` and rebuild your tree? Perhaps there were still some old files somewhere?

**Comment by marusak** [comment]
And do you build your Cockpit binaries or you use released ones?

I did `git clean -dfx` and did not help (I tried it before I opened this issue). Here is output of `cockpit-bridge --packages` with current upstream after I run `webpack`.
```
base1: /usr/share/cockpit/base1
dashboard: /usr/share/cockpit/dashboard
docker: /usr/share/cockpit/docker
domain: /usr/share/cockpit/realmd
network: /usr/share/cockpit/networkmanager
performance: /usr/share/cockpit/tuned
shell: /usr/share/cockpit/shell
ssh: /usr/share/cockpit/ssh
storage: /usr/share/cockpit/storaged
system: /usr/share/cockpit/systemd
users: /usr/share/cockpit/users
checksum = 73ea4eb5bfbd76bd71d80003f93995bf54ff6a35
```
Now I `git revert fe488aa` and `webpack` and now the `cockpit-bridge --packages` looks like this:
```
cockpit-bridge-Message: apps: couldn't read manifest.json: <data>:16:38: Parse error: unexpected character `@', expected character `}'
base1: /usr/share/cockpit/base1
dashboard: /home/mmarusak/.local/share/cockpit/dashboard
docker: /home/mmarusak/.local/share/cockpit/docker
domain: /home/mmarusak/.local/share/cockpit/realmd
kdump: /home/mmarusak/.local/share/cockpit/kdump
kubernetes: /home/mmarusak/.local/share/cockpit/kubernetes
machines: /home/mmarusak/.local/share/cockpit/ovirt
network: /home/mmarusak/.local/share/cockpit/networkmanager
performance: /home/mmarusak/.local/share/cockpit/tuned
playground: /home/mmarusak/.local/share/cockpit/playground
selinux: /home/mmarusak/.local/share/cockpit/selinux
shell: /usr/share/cockpit/shell
sosreport: /home/mmarusak/.local/share/cockpit/sosreport
ssh: /usr/share/cockpit/ssh
storage: /home/mmarusak/.local/share/cockpit/storaged
subscriptions: /home/mmarusak/.local/share/cockpit/subscriptions
system: /home/mmarusak/.local/share/cockpit/systemd
updates: /home/mmarusak/.local/share/cockpit/ostree
users: /home/mmarusak/.local/share/cockpit/users
```

There are new packages and also most of them point into my local git clone. Also notice there is some bug, but I believe that it is due to my reverting.

BUT!! if now I remove the reverting commit and do again webpack, it works as in second case. Did you tried to do `git clean -dfx`? Couldn't it be, that if you used `webpack` before the mentioned commit, you have those manifest files in the `\dist` directory?

**Comment by martinpitt** [comment]
Ah, that could be it! I (nor CI) never call `webpack` directly, just `./configure` and `make`. Our Makefiles do quite a bit of extra magic (like only rebuilding the webpack for the page you changed, not the others).

**Comment by martinpitt** [comment]
In other words, right now only the makefile generate the dist/*/manifest.json files from the pkg/*/manifest.json.in files, so with just pure webpack this does indeed not work right now.

**Comment by marusak** [comment]
So, is `./configure` and `make` preferred way?

**Comment by martinpitt** [comment]
Yes, that's what most of us developers use. If there's a way to make pure `webpack` work again, that would be nice of course - but we must not put back the pre-generated manifests into dist tarballs. This could be done with reverting fe488aaba and instead blacklisting them from `make dist` of course, hence I left this issue open.

**Comment by mvollmer** [comment]
The generated `manifest.json` files depend on values determined by `configure`, so letting webpack generate them without running `configure` first would be wrong.  Also, we don't want to run `webpack` when building a source package, because `webpack` and all its inputs are not available at that time.

But it would really be nice if `webpack` could do a complete job, which includes putting the manifests into `dist/`.

We could say that the manifests should _not_ depend on output from `configure` and that `configure` is only for the C parts.  This makes sense to me, especially since we might want to move pieces out of `pkg/` into their own projects, maybe, eventually.

`cockpit-bridge` could do some of the substitution, such as a `@libexecdir@` and `@SUDO@`.  `webpack` should be able to do `@VERSION@`.  We would need to find another mechanism for hacks like `@with_networkmanager_needs_root@`.  Maybe we can find other workarounds at run-time.

**Comment by stefwalter** [comment]
> But it would really be nice if webpack could do a complete job, which includes putting the manifests into dist/.

Agree.

> We could say that the manifests should not depend on output from configure and that configure is only for the C parts. This makes sense to me, especially since we might want to move pieces out of pkg/ into their own projects, maybe, eventually.

Agree. The version number should be parseable by webpack and not only configure.

> cockpit-bridge could do some of the substitution, such as a @libexecdir@ and @SUDO@. webpack should be able to do @VERSION@. We would need to find another mechanism for hacks like @with_networkmanager_needs_root@. Maybe we can find other workarounds at run-time.

I know it's just an idea, but I disagree with this wholeheartedly. Lets not leak build system inadequacies into Cockpit itsealf.

In addition things like @with_networkmanager_needs_root@ should be discoverable at run time. They must be if/when cockpit components are used in a container. Having them in ./configure is a hack and/or workaround, and should not be a long term solution.

**Comment by mvollmer** [comment]
> I know it's just an idea, but I disagree with this wholeheartedly. Lets not leak build system inadequacies into Cockpit itsealf.

Can you elaborate?  What do you disagree with?  cockpit-bridge doing substitutions?

**Comment by stefwalter** [comment]
>  cockpit-bridge doing substitutions?

Yup. In thihs case in particular. The whole point is for cockpit-bridge to check the versions and what's the manifest requires, not interpolate values here.

But more generally, lets not leak build system brokenness into cockpit-bridge. Build systems are ugly beasts for a reason: that they have to deal with all sorts of edge cases. But they thing that they build should aim to be clean and understandable.

**Comment by mvollmer** [comment]
We can let the bridge search `$PATH` for sudo and pkexec, I guess.  Somebody needs to know where `cockpit-ssh` and `cockpit-askpass` are, though.  Or we also put them in $PATH.

**Comment by martinpitt** [comment]
FWIW, I don't think we should put helper programs like c-ssh and c-askpass into $PATH as a workaround. These are classic configure arguments, so they should also be handled by Makefile rules IMHO.

**Comment by larskarlitski** [comment]
What's the state on this? I think we decided last year that you need to call `make` at least once before being able to use `webpack`, right?

**Comment by martinpitt** [comment]
I don't see a way to build everything we do through webpack. You *have* to call make once, then calling webpack might work.

**Comment by larskarlitski** [comment]
Right, and we don't document this anymore (which was the problem for this bug in the first place). However, this bug still applies to running webpack after the initial make. It won't pick up changes to manifest.json. I guess we could move the `sed` (or an equivalent) into `webpack.config.js`...

**Comment by stefwalter** [comment]
I think the direction of having webpack continue to generate manifest.json makes sense.

Part of the idea was to use web tools for the packages of Cockpit, and autofoo for the backend parts.

**Comment by larskarlitski** [comment]
> I think the direction of having webpack continue to generate manifest.json makes sense.

Agreed, but the commit @marusak linked to does the opposite.

**Comment by marusak** [comment]
I don't find this important anymore
