### ISSUE TITLE
Provide GUI for crypto policies

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8519]
Fedora has had a CLI and config API for setting global [crypto policies](https://fedoraproject.org/wiki/Changes/CryptoPolicy) for a while. For the most part this is a setting which large institutions want to roll out globally through configuration management systems (mostly changing `/etc/crypto-policies/config`).

However, @nmav pointed out that in some cases this makes sense in "troubleshooting" mode. E. g. your server fails to connect to your mail server as your current crypto policy forbids the usage of the auth algorithm that they use. So one could try a different mode, see if it works, and then take actions to either roll out the different policy or file a bug, etc. Once you found a setting that works, the page then should show you how to apply it to other systems, e. g. the command line or that being wrapped in an Ansible playbook.

It's a global setting, so it doesn't make sense on the subsystem pages. For the global /system page it's a too specialized use case (in particular, we don't want users to mess around with that unless they really know what they are doing). Thus this would make a nice start for a standalone Cockpit App.

Notes:
 * `update-crypto-policy` command lives in a separate package; preferred over changing the config file
 * Enabling/disabling FIPS requires a reboot
 * Policies are abstract names, thus they apply to different OS versions; but might not mean the same thing on them.
 * UI page needs to describe what the policy does; this needs some help from the `crypto-policies` package, either through exporting that in machine readable format (JSON?) from which the manpages could be generated as well; or some kind of `update-crypto-policy describe`.

**Comment by martinpitt** [comment]
@nmav, could you please look through this whether I captured this correctly?

**Comment by nmav** [comment]
Your description is accurate, thank you.
