### ISSUE TITLE
Google Engine Compute

### ISSUE THREAD

**Issue by N214** [cockpit-project/cockpit#8527]
Hello, 

it's a weird question but how are we suppose to login to cockpit for the first time since with Google Engine Compute, I don't have a password? It's SSH only and i don't have the root permission beside sudo... 

Could someone enlighten me? Thanks

**Comment by stefwalter** [comment]
You can use the bastion host model: 

 * Log into Cockpit running on another Linux machine as your own account.
 * Add your GCE machine to the dashboard, which will then use your SSH key.

See: http://cockpit-project.org/guide/latest/authentication.html

or a video: https://www.youtube.com/watch?v=RZ_N2iCPm_U
