### ISSUE TITLE
Monitoring history

### ISSUE THREAD

**Issue by Ansem93** [cockpit-project/cockpit#8536]
Hi everyone.
There is some way to save the monitoring of the most important thing for 1/2 year?
I like the interface of cockpit and it's semplicity, but I need to save the cpu,ram,hdd, network utlization.
If possible I would lilke to save process cpu and ram utilization too

**Comment by Gundersanne** [comment]
Sorry for the late reply.

Cockpit itself doesn't really support this as it's a bit outside the scope of the project, cockpit just reflects the current state of the system. However several tools exist to do this, like sysstat: https://github.com/sysstat/sysstat.
