### ISSUE TITLE
machines: It seems no effect after click the restart or shutdown vm button

### ISSUE THREAD

**Issue by AlertBear** [cockpit-project/cockpit#8542]
Description of problem:
It seems no effect after click the restart or shutdown vm button

Version-Release number of selected component (if applicable):
cockpit-ws-154-3.el7.x86_64
cockpit-system-154-3.el7.noarch
cockpit-154-3.el7.x86_64
cockpit-machines-160-2.el7.x86_64
cockpit-bridge-154-3.el7.x86_64
RHEL-7.5-20180125.0
firefox-57.0.1
chrome-59.0.3071.115

How reproducible:
100%

Steps to Reproduce:
1. Install cockpit-machines package
2. Create a vm via libvirt and install os to the vm
3. Click the restart or shutdown button

Actual results:
1.After step#3, the vm is not restarted or shutdown

Expected results:
1. After step#3, the vm can be restarted or shutdown

Additional info:
1. This is regression since no such issue on last build
2. Force restart or Force shutdown can be successful

**Comment by mareklibra** [comment]
I might be related to the guest VM configuration.

Please try

     virsh shutdown [YOUR_VM_NAME]

and see output and check if the VM is down.

If not, please provide output of following:

     VM=[YOUR_VM_NAME] virsh -d 0 shutdown ${VM} ; sleep 5 ; virsh list ; virsh dumpxml ${VM}

The VM has to have `acpi` feature enabled (see the domain xml) and `acpid` running inside the guest.

**Comment by AlertBear** [comment]
Thanks, the acpi feature is indeed not enabled. After fix this, the vm can be shutdown and reboot successfully. Please close this as it is not an issue.
