### ISSUE TITLE
RFE: cockpit.format_bytes between all units

### ISSUE THREAD

**Issue by suomiy** [cockpit-project/cockpit#8572]
### Add support for:
- conversion between all units (i.e.  MiB to GiB, TiB to B, etc.)
- converting to and picking the highest unit.

#### Implementation
I already implemented this in machines pkg (for factor 1024): 
https://github.com/cockpit-project/cockpit/blob/master/pkg/machines/helpers.es6#L88

##### Methods:
``` js
convertToUnit(input, inputUnit, outputUnit)
convertToUnitVerbose(input, inputUnit, outputUnit)
convertToBestUnit(input, inputUnit)
```
##### Units
There are units to choose from, although they are not a prerequisite (string can be used instead, e.g. `"KiB"`)
``` js
const units = {}
```

### To Resolve
I am not sure how the API should look like
- should we enhance `cockpit.format_bytes` in http://cockpit-project.org/guide/latest/cockpit-util.html ?
- should we add another function or multiple functions ?

**Comment by stefwalter** [comment]
Lets only make this an API once it starts to be used across lots of Cockpit in a consistent way. Until then, would a file in ```pkg/lib/units.js``` suffice?

**Comment by suomiy** [comment]
Yes. I will move it there.

**Comment by martinpitt** [comment]
Indeed this largely overlaps with `cockpit.format_bytes()`, which already picks the "best" unit, has a selector between base-2 and base-10 units, and a flag for whether to return a single string or a pair of [number, unit]. So AFAICS, what's missing for your purposes is the ability to parse a string like "12.3 MB" or "0.4 TiB" into a bytes integer? That seems to be more flexible to me, as the code will often want to do some boundary etc. checks, and they are much more practically done on an integer than on  a string with unit. So would the needs of the Add VM dialog be addressed with a `parse_number(str)` function?

**Comment by suomiy** [comment]
> So AFAICS, what's missing for your purposes is the ability to parse a string like "12.3 MB" or "0.4 TiB" into a bytes integer?

it is not about parsing the string - it is mainly about conversion between arbitrary units

> So would the needs of the Add VM dialog be addressed with a parse_number(str) function?

These conversions are used in other places in machines as well.

**Comment by martinpitt** [comment]
> it is not about parsing the string - it is mainly about conversion between arbitrary units

This API does both, while we already have a conversion from int *to* a formatted number. So we are mostly missing the parsing part? These can then be put together to convert a unit, in places which need it.

**Comment by suomiy** [comment]
so should I remove the parsing part and just leave the conversions? which are the main focus of this API

**Comment by martinpitt** [comment]
I thought the parsing part was the main missing thing here? As said we already have the formatting of an int, what we don't currently have (in lib/) is parsing a string like "12.3 MiB" to 12897485.

**Comment by suomiy** [comment]
It is not about parsing. It is not possible to parse string "12.3 MiB" with these functions (yet?).

It is about easier conversions. Please look at the implementation and usage in pkg/machines

**Comment by martinpitt** [comment]
If you can convert between two units, you can by definition also convert them to "bytes" , i. e. a plain integer :-) I. e. essentially you are interpreting a string into a number. Except that the current API folds the "string → int" and "int → string with a different unit" into one call, which is what I'd like to avoid as the second half we already have with `format_bytes()`.

**Comment by suomiy** [comment]
> "int → string with a different unit" we already have with format_bytes()

you cannot choose the unit with format_bytes()

You are right, it can be split into two steps going through intermediate byte number. I think it is still useful to have function (or wrapper) which does both steps though.

**Comment by martinpitt** [comment]
This is quite stale, so let's close this. As said above, this isn't currently a generic API, I don't think it should be used on other pages, and `format_bytes()` is public API which we don't want to change.
