### ISSUE TITLE
Wrong encoding in Terminal when using Powerline

### ISSUE THREAD

**Issue by liquidat** [cockpit-project/cockpit#8594]
I have a [zsh](http://www.zsh.org/) running [Powerline](https://github.com/powerline/powerline) on a CentOS 7. As mentioned in #3740 (closed due to missing reporter response) the encoding does not look right when I open the Cockpit Terminal in Chromium on my Fedora:
![cockpit terminal problem](https://user-images.githubusercontent.com/1998084/36076702-1ee0b4ac-0f60-11e8-8bd2-bd9400bd0b51.png)
When I connect to the server via SSH, everything looks fine:
![remote-ssh-session](https://user-images.githubusercontent.com/1998084/36076709-2d13e076-0f60-11e8-935e-52f4cf6295c5.png)

Given the remote connection I do not think this rendering issue has anything to do with a running X session.
Given the [Powerline troubleshooting](http://powerline.readthedocs.io/en/master/troubleshooting/linux.html#i-cant-see-any-fancy-symbols-whats-wrong) I think it is a font problem:

- [ ] Make sure that you’ve configured gvim or your terminal emulator to use a patched font.

The [Powerline install on Fedora](https://fedoramagazine.org/add-power-terminal-powerline/) copies the fonts as symbol fonts afaik.

Referencing those as a custom font could fix this. Is that possible?

**Comment by martinpitt** [comment]
Unless it's a very simple fix, it's unlikely that we'll rearrange fonts in our rather old term.js component. At some point we'll move to [xterm.js](https://xtermjs.org/) (see PR #7424) at which point this should be reevaluated.

@larskarlitski , you dealt with the terminal a bit, do you have more insights here?

**Comment by larskarlitski** [comment]
Powerline apparently uses Unicode private use areas for these extra symbols. The community provides patched fonts which have the right symbols at these code points.

This makes it really hard to properly support connecting from a remote system, as you'll need to have a patched font installed on every system you might connect from.

> When I connect to the server via SSH, everything looks fine:

Hm, but only when you connect from a system that has a patched font installed, right?

> At some point we'll move to xterm.js (see PR #7424) at which point this should be reevaluated.

I don't think this will make it easier, as it is a font problem.

The only way I can think of to solve this for Cockpit would be to allow people to choose which font they want to use in the terminal. People using powerline could then choose a patched one (again, on every system they want to connect from).

This goes against Cockpit's no-configuration principle and is also a lot of work. So I'm inclined to close this bug, unless enough people feel strongly about this.

Sorry @liquidat :(  Maybe there's some way for powershell to find out which system you're on and only display its fancy private symbols when it knows the font includes them?

**Comment by martinpitt** [comment]
Agreed about this being basically "unfixable", as it is a gross layering violation: `$PS1` just simply can't make assumptions about fonts by itself. The cleanest solution would be for powerline to only show the fancy private unicode symbols if it finds a special `$TERM` value, and only set that on machines that have the modified font, under graphical environments.

**Comment by martinpitt** [comment]
FWIW, a much more elegant, robust, and simple fix would be to stop assuming private unicode glyphs and just use standard characaters - then it will just work everywhere :-)

**Comment by liquidat** [comment]
Thanks for the responses @martinpitt @larskarlitski - I am not sure powerline will move to a existing glyphs in the near future, but I understand that right now this is not really solvable for cockpit.

**Comment by averykhoo** [comment]
worked for me: check value of `$XDG_SESSION_TYPE` before enabling powerline in `.bashrc`, e.g.:
```bash
if [[ ! $XDG_SESSION_TYPE == "web" ]]; then
    <enable powerline>
fi
```

**Comment by goozbach** [comment]
Any reason the powerline fonts couldn't be embedded as a web font?

**Comment by SdotVdot** [comment]
@goozbach Did it work for you?
