### ISSUE TITLE
selinux: improper formatting in manual solutions

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#8596]
When the SELinux page cannot fix things automatically, it still often lists solutions that must be ran (as root) to fix the issue.

Currently, the formatting is all in-line and not copy/pastable. As the standard root prompt is also the character in shells to comment out lines, if someone were to copy & paste the command, it would not work properly

Here's what it currently looks like:

![Current screenshot of SELinux manual solution](https://user-images.githubusercontent.com/10246/36097848-f2f587d0-0ffc-11e8-9caf-55acde069543.png)

It should probably look similar to the following:

![Proposed SELinux manual solution](https://user-images.githubusercontent.com/10246/36097841-ebb3fe98-0ffc-11e8-8a4f-e7933778ba9c.png)

**Comment by nversluis** [comment]
Hi,

I would like to work on this issue, but I am not sure what the best way to reproduce the error log that is shown in the images. What would be the best way to generate an error that would display the content that needs to be reformatted?

Thank you for your time.

**Comment by garrett** [comment]
@nversluis: The above screenshot was from my little personal server running NextCloud, but I have a bunch of these types of issues locally on my development laptop too.

1. Go to the SELinux page
2. Look for messages like: "SELinux is preventing ... from ... access ..."
3. Expand the row
4. Click on "solution details" to see the unformatted details.

Once we have support for properly displaying the the manual solution, I would also like to suggest we drop the solution details expander and show it as part of the card body without having a second expansion — except possibly for automatic solutions (when there's an "Apply this solution" button).

**Comment by garrett** [comment]
My guess as to why it's implemented as it is now:

SELinux returns the entire string in "doText". We'd have to parse this in a language-agnostic way, like splitting on the first colon. I don't know if there are any other strings other than "Allow this access for now" (and what it's translated to in other languages), however. I also don't know if it suggests anything other than running commands as root. It _seems_ as that's the only string and then the commands are prefixed by "#", however.

I don't know if there's a better way to get the information than parsing the doText line. (Hopefully there might be?)

**Comment by garrett** [comment]
I've tracked down where the "Allow this access for now" string comes from. It's in [the `setroubleshoot` command, hosted at Pagure](https://pagure.io/setroubleshoot/tree/master). Specifically, this string is in https://pagure.io/setroubleshoot/blob/master/f/plugins/src/catchall.py — it's the catch all plugin.

Other plugins have different strings. Look for `do_text` in the files in `plugins/src/`.

From what I see, there are a few patterns:
1. Text strings.
2. First line that ends with `:`, then has additional lines for commands that begin with `#`
3. Only command lines (each line or lines beginning with `#`).
