### ISSUE TITLE
Performance Profile shows error for unprivileged

### ISSUE THREAD

**Issue by nan0tube** [cockpit-project/cockpit#8601]
Using Version 161 (from ubuntu 18.04 repo), with tuned 2.9.0 installed.

When logged in without checking "Reuse my password for privileged tasks", Performance Profile shows "error" and its status shows "Communication with tuned has failed". 

Perhaps a message suggesting "requires elevation" is more informative.

**Comment by martinpitt** [comment]
Indeed this should use `cockpit.permission()` and `.update_privileged()` like e. g. on pkg/systemd/host.js for changing the host name. This needs to happen in pkg/tuned/dialog.js.
