### ISSUE TITLE
Fedora 27, VDO device creating not work

### ISSUE THREAD

**Issue by serjponomarev** [cockpit-project/cockpit#8609]
I have Fedora 27 with full updates for now (pkgs, kernel etc).
Build and install VDO https://github.com/dm-vdo/ (VDO today updated and added support for Fedor 27)
VDO working, all perfect.
But when i creating VDO device in Cockpit interface, his creates, but not showing in VDO device in interface. His dropped to Other devices. 
See screenshot.
![create_vdo](https://user-images.githubusercontent.com/11921443/36154089-fd20032a-10d8-11e8-8b70-481b8bf31f8d.PNG)
![after_create_vdo](https://user-images.githubusercontent.com/11921443/36154088-fd0253f2-10d8-11e8-834f-cfae2a679ea4.PNG)

What wrong?

**Comment by mvollmer** [comment]
Thanks for reporting this!  I will have to try this myself.

**Comment by serjponomarev** [comment]
Marius, do you have any progress?

**Comment by mvollmer** [comment]
> Marius, do you have any progress?

I'll start now.  Is there a COPR with VDO rpms for F27?

**Comment by serjponomarev** [comment]
Yes, from default repo (Updates).
Cockpit version 161 and all deps.

**Comment by mvollmer** [comment]
Okay, the main issue is that Fedora 27 has python3 installed and thus Cockpit was using that to run the VDO Python code (because we require all our Python code to work with python3).  However, we also use the semi-private "vdomgmt" module installed with `/usr/bin/vdo`, and that one exists only for python2.

There was also a small API change in vdomgmt.

#8626 should fix this.  Can you try it out?

**Comment by serjponomarev** [comment]
I need merge master with you changes and compile from source? Right?

**Comment by mvollmer** [comment]
> I need merge master with your changes and compile Cockpit from source? Right?

The merge is optional, but you would need to compile Cockpit from sources, yes.

I have also uploaded a pre-compiled version of just the "storage" component, with instructions:

https://github.com/mvollmer/cockpit-storage-vdo-f27

Let me know how it goes!

**Comment by serjponomarev** [comment]
Perfect! Working!
When will it be in the master branch?
![image](https://user-images.githubusercontent.com/11921443/36305236-632418c0-131b-11e8-9a97-fb152719b5db.png)

**Comment by mvollmer** [comment]
> When will it be in the master branch?

In a couple of days, I'd guess.  There is no particular hurry IMO since vdo itself isn't in Fedora 27 yet.

**Comment by martinpitt** [comment]
@serjponomarev : The fix was released with Cockpit 162 yesterday and is in Fedora 27 testing now: https://bodhi.fedoraproject.org/updates/cockpit-162-1.fc27

**Comment by serjponomarev** [comment]
This problem has been reproduced again:
Centos 7.5
kernel 4.17.14-1.el7.elrepo.x86_64
KVDO and VDO from master branch
Cockpit version 169:
cockpit-system-169-1.el7.centos.noarch
cockpit-169-1.el7.centos.x86_64
cockpit-bridge-169-1.el7.centos.x86_64
cockpit-ws-169-1.el7.centos.x86_64
cockpit-networkmanager-169-1.el7.centos.noarch
cockpit-storaged-169-1.el7.centos.noarch

**how to resolve this issue on Centos 7.5 with last VDO & KVDO from Git?**

**Comment by drckeefe** [comment]
Newer version of VDO manager (6.2+) uses python 3.  Centos 7.5 uses python 2.  This might be the issue.  Can you try using the 6.1 version of VDO manager with 6.2 version of kmod-kvdo on Centos 7.5 with the 4.17 kernel?  I haven't tried it, but it might work for you.

**Comment by serjponomarev** [comment]
I already checked it.
Cockpit and VDO are working, the web console is also working.
The problem in the statistics, **vdostats --si** produces an error, `VDOStatistics version mismatch`

**Comment by mvollmer** [comment]
> Cockpit and VDO are working, the web console is also working.

I would Cockpit expect that Cockpit is broken just like in the original issue: One can create a VDO volume, but Cockpit will not recognize it as such.

The reason is exactly what @drckeefe has mentioned: Cockpit will try to load vdo.statistics with Python 2, but since VDO from Git now uses Python 3, this will fail.

Cockpit 172 fixes this.  Can you upgrade Cockpit as well?

**Comment by serjponomarev** [comment]
in the official Centos repositories, the cockpit is only version 169 at the moment. Can you tell me when will version 172? Thank you )

**Comment by serjponomarev** [comment]
@mvollmer  please,  tell me when will version 172 in repo? )
