### ISSUE TITLE
SEC_ERROR_UNKNOWN_ISSUER in Firefox

### ISSUE THREAD

**Issue by abitrolly** [cockpit-project/cockpit#8618]
Accessing Cockpit with `https://localhost:9090` gives warning that connection is insecure.

> 127.0.0.1:9090 uses an invalid security certificate.
>
> The certificate is not trusted because the issuer certificate is unknown. The server might not be sending the appropriate intermediate certificates. An additional root certificate may need to be imported.
>
> Error code: SEC_ERROR_UNKNOWN_ISSUER 

Fedora 27 // Firefox 58.0.1

Is it possible to fix this?

**Comment by martinpitt** [comment]
You can supply your own certificate if you have one and put it into /etc/cockpit/ws-certs.d/; or, if you have a trusted network, disable SSL. See `man cockpit.conf` and `man cockpit-ws`.

**Comment by stefwalter** [comment]
More detailed info can be found in the guide: http://cockpit-project.org/guide/latest/https.html

**Comment by abitrolly** [comment]
Can it generate certificate for the local machine automatically?
