### ISSUE TITLE
anchors without href but with onclick actions are untabbable in navigation

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#8627]
This stops keyboard navigation (by default) and within screen readers from working properly.

**Comment by garrett** [comment]
This is a pattern that's used a bunch in JSX, apparently. It's especially problematic when navigation is concerned.

After running `ag "<a.*onclick" --js`, I get the following 25 results:

```js
pkg/machines/components/desktopConsole.jsx
100:                <a href='#' onClick={this.onClick}>
108:                <a href='#' onClick={this.onClick}>

pkg/machines/components/dropdownButtons.jsx
40:                    <a role='menuitem' onClick={mouseClick(button.action)} id={button.id}>

pkg/apps/application.jsx
108:                progress_or_launch = <a onClick={left_click(() => launch(comp))}>{_("Go to Application")}</a>;
143:                    <li><a onClick={left_click(navigate_up)}>{_("Applications")}</a></li>

pkg/apps/application-list.jsx
57:            name = <a onClick={left_click(() => launch(comp))}>{comp.name}</a>;

pkg/ovirt/components/ClusterVms.jsx
57:        return (<a href='#' onClick={() => dispatch(goToSubpage('hostvms'))}>
63:    // just the <a href> without the onClick handler is not working
64:    return (<a href={cockpitUrl} onClick={() => {window.top.location=cockpitUrl;}}>

pkg/selinux/setroubleshoot-view.jsx
118:            var detailsLink = <a href="#" onClick={ self.handleSolutionDetailsClick.bind(self, itmIdx) }>{ _("solution details") }</a>;

pkg/lib/cockpit-components-listing.jsx
209:                        <a href="#" onClick={ self.handleTabClick.bind(self, idx) }>{itm.name}</a>

pkg/systemd/hwinfo.jsx
90:                    <li><a onClick={ () => cockpit.jump("/system", cockpit.transport.host) }>{ _("System") }</a></li>

pkg/storaged/details.jsx
136:                        <li><a onClick={go_up}>{_("Storage")}</a></li>

pkg/storaged/storage-controls.jsx
122:                                    <a onClick={checked(this.props.onClick)}
161:            <a onClick={() => { cockpit.location.go(parts.location) }}>
233:                                                          <a role="menuitem" onClick={checked(act.action)}>

pkg/storaged/pvol-tabs.jsx
46:                             <a onClick={() => cockpit.location.go([ "vg", vgroup.Name ])}>
76:                             <a onClick={() => cockpit.location.go([ "mdraid", mdraid.UUID ])}>
102:                             <a onClick={() => cockpit.location.go([ "vdo", vdo.name ])}>

pkg/playground/react-demo-listing.jsx
95:        var addLink = <a className="pull-right" onClick={handleAddClick}>Add Row</a>;

pkg/docker/containers-view.jsx
65:                                    <a data-value={index} onClick={this.handleClick}>{action.label}</a>
141:            problem_cursors.push(<a data-url={problem[i][0]} className='list-group-item' onClick={this.onItemClick}>
660:        var getNewImageAction = <a onClick={this.handleSearchImageClick} className="card-pf-link-with-icon pull-right">

pkg/kdump/kdump-view.jsx
403:            settingsLink = <a href="#" onClick={this.handleSettingsClick}>{ kdumpLocation }</a>;
457:            kdumpServiceDetails = <a href="#" onClick={this.handleServiceDetailsClick}>{serviceDescription}{serviceHint}</a>;
```

**Comment by garrett** [comment]
I'm wondering if adding `tabindex=0` is an easy way to work-around this misfeature. I'll test.

**Comment by garrett** [comment]
Yep! The tabindex="0" trick works.

For JSX, it's necessary to write it as: `tabIndex="0"`.

Adding a patch for all of these to my huge accessibility WIP PR #8612.

**Comment by martinpitt** [comment]
Confirming on current master, and confirming that `tabindex="0"` "fixes" it. Does that really need to be applied to each and every link, or can we enable this via CSS somehow?

**Comment by garrett** [comment]
It's not a CSS-level issue. This is with HTML and browser implementation.

Anchor tags are only focusable when they have an `href` or `tabindex="0"`.

The _proper_ fix is:

1. convert `<a>` restyled to look like "buttons" to one of:
   - actual `<button>` tags
   - a type of `<input>`

2. if it's supposed to be a link (visually &  conceptually) choose one:
   - add an `href`
   - add a `tabindex="0"`

---

General rule of thumb:

- Button: action
- Link: go somewhere

There are exceptions, of course. Example: Some patterns de-emphisize secondary actions as links instead of buttons. Other times, the secondary action is destyled a bit, like with color and style removal but keep buttons for both actions.

**Comment by garrett** [comment]
Note: Some of the `<a onClick>` examples above actually have `href`, but most don't.

As this issue is an older one (from a year ago), we probably have even more issues across the codebase. Everyone on the team needs to be aware of this problem, or we'll keep hitting it again and again.

**Comment by marusak** [comment]
We now enforce this in all .jsx code.
I did some quick grepping and found two places:
```
pkg/dashboard/index.html:            <a data-address="{{address}}" class="list-group-item {{state}}"
pkg/shell/index.html:        <a download>ca.cer</a>
```

The dashboard one seems to work with keyboard just fine (maybe the code is not ideal, but since we think about obsoleting dashboard slowly...)

The shell one seem weird, but we set the href from js, so when user gets to it, it has href and thus is correct.
```
$("#safari-cert-help a").attr("href", ca_cert_url);  
```
