### ISSUE TITLE
cockpit-bridge constantly generating error about missing /proc/diskstats

### ISSUE THREAD

**Issue by djstuandrews** [cockpit-project/cockpit#8630]
I have Cockpit setup on several VPS
/proc/diskstats isn't exposed

The following error is written to the log every second:
Feb 16 09:35:32 jupiter cockpit-bridge: error loading contents /proc/vmstat: Failed to open file '/proc/diskstats': No such file or directory

Can you add a way of disabling this check, or disabling the reporting of this error.

**Comment by martinpitt** [comment]
I think it would be best if `cockpit_block_samples()` and `cockpit_disk_samples()` would just remember that /proc/diskstats is not available, and then just silently return.
