### ISSUE TITLE
read only mode without login

### ISSUE THREAD

**Issue by djstuandrews** [cockpit-project/cockpit#8631]
Is there / can you add a way to view a dashboard (e.g. in read-only mode) without authenticating?

We want to display the dashboard on a digital signage screen.

**Comment by martinpitt** [comment]
I'm afraid Cockpit's architecture does not allow that. Cockpit is an actual Linux session, so it needs to log into the host. If you want to supervise a bunch of machines without logging in, I recommend something like nagios.
