### ISSUE TITLE
cannot find cockpit.conf

### ISSUE THREAD

**Issue by cedroid09** [cockpit-project/cockpit#8636]
Hello,

I've been trying to proxy cockpit using nginx but I can't find cockpit.conf in `/etc/cockpit/cockpit.conf` on ubuntu 16.04.

**Comment by thenameisflic** [comment]
It doesn't exist by default, you have to create it yourself.

**Comment by martinpitt** [comment]
Right, this is  by design. You usually don't need one, but see `man cockpit.conf` for available settings.

**Comment by shinedog** [comment]
It would be nice if there was a comment in the man page/documentation that indicated that it is by design. It definitely isn't clear currently, I spent a significant amount of time trying to find where the file gets located by install.

**Comment by GP1cdenney** [comment]
I also spent a significant amount of time trying to find where cockpit.conf might be located. Not all linux distros have the same installation configuration, so when a config file is not in its "default" location, I assume that the documentation didn't specify an exception for my distro and start looking for it elsewhere.

I would like to request that /etc/cockpit/cockpit.conf exist by default, with all default configuration settings listed and commented out. Sample configurations for common overrides would be nice as well, such as making cockpit proxy aware to an nginx reverse_proxy.

**Comment by ScarUY** [comment]
Free software is great, having to deal with the "I'd do it the way I like it" is another thing entirely, I always thought 'conf' files always existed by default, with all default configuration settings listed and commented out, but it's not a rule apparently, "let's just make the life of the people using my creation more complicated for no reason at all" seems to be a strange way to gain support from users, I mean cockpit is great, but making people waste time with this stuff it's just....

**Comment by gbraad** [comment]
^^^ @martinpitt it seems several people have issues with the non-existence of `cockpit.conf`.
it might be a good idea to create a mock configuration that contains examples or defaults as comments.
I understand this might be duplication of the manpages

**Comment by ScarUY** [comment]
> @adityakamat1 : See [`man cockpit.conf`](https://cockpit-project.org/guide/latest/cockpit.conf.5.html), in particular `Banner=` and `IdleTimeout=` in the `[Session]` section.

While that's a valid answer, I agree with @gbraad in that it'll be nice to have a commented cockpit.conf, like so many other projects, helps begginners and I believe will help make the project more popular.
