### ISSUE TITLE
software: markdown-based formatting of changelog details has issues

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#8644]
The software list looks a bit hodgepodgy with details, as seen in this screenshot:

![screenshot-2018-2-19 software updates - sunny lan 1](https://user-images.githubusercontent.com/10246/36391364-784bc5d0-15a6-11e8-8a91-572a70c972ad.png)

Suggestions for in-row item details:

1. Strip HTML
2. Use truncation
3. Use the same baseline as the other columns (using stripped plain text might automatically solve this)

Details are mainly fine when expanded. (Bumping down headers _may_ make sense when they appear, however. `gnome-photos` uses headings that are a bit too prominent.)

**Comment by garrett** [comment]
For reference, here's what `gnome-photos` currently looks like when expanded:

![screenshot-2018-2-19 software updates - sunny lan 2](https://user-images.githubusercontent.com/10246/36391590-6fb7cb02-15a7-11e8-9126-a9611277c9be.png)

**Comment by martinpitt** [comment]
gnome-photos is indeed a bit curious. There is already a `removeHeading()` function which removes `== [...] ==` headings from the first line, but apparently that doesn't help here, and it's a different heading. I thought this would come from the .spec's `%changelog`, but apparently it doesn't: https://src.fedoraproject.org/rpms/gnome-photos/blob/f27/f/gnome-photos.spec#_126
```
%changelog
* Fri Dec 15 2017 Debarshi Ray <rishi@fedoraproject.org> - 3.26.3-1
- Update to 3.26.3
```
This looks innocuous, so apparently this is coming from some place else. Do you still happen to be able to  do `sudo dnf downgrade gnome-photos`? Do you get that weird formatting again? If so, can you please copy&paste the output of `pkcon get-update-detail gnome-photos`?

In the meantime I'll work on removing enumeration and all levels of headings from the changes line displayed in the list.
