### ISSUE TITLE
selinux: have a way to show and export local modifications

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8657]
Once you make a policy change, you'll need a way to see how that change is different from the default configuration.

From the ticket in Jira:
"As a Cockpit user I want to manage local policy modifications in Cockpit so that I keep track of the current SELinux policy configuration."

**Comment by andreasn** [comment]
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/852197c04f33289776e970202ab36459f968d161/selinux-troubleshooting/selinux.png)

**Comment by martinpitt** [comment]
@andreasn: Thanks for the initial design! Some thoughts:

 * I'm not sure how "pretty" we can format the system modifications. We can at least format the booleans, though, they have human-readable descriptions (`semanage boolean --list`, although they are mostly autogenerated). But for example, after `semanage fcontext --add -t samba_share_t /var/tmp/`, `semanage export` shows

       fcontext -a -f a -t samba_share_t '/var/tmp/'

   which is much harder to translate into something humanly readable: there are lots of file types and I'm not sure we have a humanly readable explanation of the various  `*_t` SELinux types.

 * The Export button would make the output of `semanage export` available, I figure. Should this trigger a text file download, or perhaps switch the view from the humanly readable table to a `<pre>` with the result, for copy&pasting?

 * I don't think we want an "Import.." button here (or anywhere else) - as discussed,  Cockpit isn't a tool to apply a pre-defined policy onto a machine, and this  very quickly gets into Ansible/Satellite/puppet etc. territory.

**Comment by andreasn** [comment]
> I don't think we want an "Import.." button here (or anywhere else) - as discussed, Cockpit isn't a tool to apply a pre-defined policy onto a machine, and this very quickly gets into Ansible/Satellite/puppet etc. territory.

I lifted this from the mockup @garrett created a little while ago. I agree about the reasons for dropping import, so I'll do that.

**Comment by andreasn** [comment]
> fcontext -a -f a -t samba_share_t '/var/tmp/'

I have no idea what this means. It's complete jargon. What would a junior admin even do with this information? If we can't make it more readable than this, we failed and I would rather not ship this.

**Comment by andreasn** [comment]
Looking at the man page, it seems -a is for "Add a new record", -f is for File-type, -t defines a file-type. Not sure what the second a after -f does really.

**Comment by martinpitt** [comment]
Indeed it's the command line that an admin would actually use to do the equivalent action. So for the "export" and "learn the CLI from cockpit" points  of view, I think this is fine. I. e. it's exactly what the "Export" button should do (either with a downloaded file or showing a <pre> or so).

However, as for showing this in the "System Modifications", I agree. I gave that example not to say "we can't do this", but to point out that Cockpit needs to understand/parse commands beyond the SELinux booleans. And I suppose we need to fall back to showing the verbatim command for cases that we can't interpret yet (and then fix these piece by piece).

**Comment by andreasn** [comment]
Makes sense.

**Comment by andreasn** [comment]
Version 2, now without the Import button:
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/988f5a6782b72dd6383c3e342874974c1996caaf/selinux-troubleshooting/selinux.png)

**Comment by martinpitt** [comment]
We want to at least offer an Ansible playbook version of this. This could just be the thing that happens when you click "Export..", or that could lead to a further choice between "Ansible playbook" or "Shell Script". Maybe we don't even need an "Export" button, but instead have a "Format" choice between "human readable HTML", "shell script", and "Ansible playbook".

The current RHEL focus is certainly on "Ansible playbook", so maybe that should be the MVP. But it certainly can't hurt to have a design that encompasses all three of those.

**Comment by andreasn** [comment]
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/0b4e474b7d1788bf7ee4b44683c07b80fe697d8d/selinux-troubleshooting/selinux.png)

**Comment by garrett** [comment]
Should the view window also have a save button, which saves the current selected format?

**Comment by martinpitt** [comment]
BTW, I suggest to limit the human translations to SELinux booleans for now. For others, we could start with just showing the corresponding `semanage export` lines verbatim, and then iterate on translating those. But AFAICS the troubleshooter mostly advises enabling booleans anyway.

**Comment by garrett** [comment]
> auto-generate a download

We need this feature in at least these two places, and will probably elsewhere in the future too. Copy/pasting a file — especially if it gets large — is not really a great experience. Hopefully we can figure something out soon!

> Ansible supports seboolean directly

Nice!

**Comment by garrett** [comment]
BTW: For Ansible, won't we eventually need to support more than one file? Like downloading an archive of multiple files (probably in ZIP format, which is supported well everywhere, or a choice of ZIP/TGZ).

We'll need to figure out a good way to download files one way or another, I guess.

**Comment by marusak** [comment]
Hey @andreasn and @garrett 
I would like to work on this. Is the design still up to date or would you like to make some changes to it?
This also would be a nice feature for firewall page. Would the design fit the firewall page the same way?

**Comment by andreasn** [comment]
Yes, it's up to date, or rather the best I could come up with for now :)
https://github.com/cockpit-project/cockpit/issues/8657#issuecomment-392777014 is the one that's the latest.

So let's run with that, see how it works and then make modifications as we find problems in usability tests and such.
