### ISSUE TITLE
 missing test-policy for known failures

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#8666]
Hi.
I'm running tests with already  prepared  packages (for RHEL7) and I run all tests, and tests does not check for 
known fails: https://github.com/cockpit-project/cockpit/blob/master/bots/naughty/rhel-7-5/6359-glib-networking-change-cert
like test: not ok 8 testReconnectChangeCert (__main__.TestOpenshift) # duration: 186s
thanks to @martinpitt to investigate this issue

**Comment by martinpitt** [comment]
testlib.py's `filterOutput()` already calls bots/tests-policy, which should match the bots/naughty/ files against the output. This generally works:
```
❱❱❱ TEST_OS=rhel-7-5 test/verify/check-machines TestMachines.testBasic 
1..1
# ----------------------------------------------------------------------
# testBasic (__main__.TestMachines)
[...]
Traceback (most recent call last):
  File "test/verify/check-machines", line 282, in testBasic
    wait(lambda: "Linux version" in self.machine.execute("cat {0}".format(args["logfile"])), delay=3)
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 1184, in wait
    raise Error(msg or "Condition did not become true.")
Error: Condition did not become true.

ok 1 testBasic (__main__.TestMachines) # duration: 214s # SKIP Known issue #7891

❱❱❱ TEST_OS=rhel-7-5 test/verify/check-openshift TestOpenshift.testReconnectChangeCert
1..1
# ----------------------------------------------------------------------
# testReconnectChangeCert (__main__.TestOpenshift)
[...]
Traceback (most recent call last):
  File "test/verify/check-openshift", line 382, in testReconnectChangeCert
    b.wait_present("#service-list")
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 266, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 260, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 257, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 168, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
Error: timeout
wait_js_cond(ph_is_present("#service-list")): condition did not become true
cdp: {u'level': u'error', u'url': u'http://127.0.0.2:9191/cockpit/login', u'text': u'Failed to load resource: the server responded with a status of 401 (Authentication failed)', u'source': u'network', u'networkRequestId': u'6256.8', u'timestamp': 1519211074980.18}

ok 1 testReconnectChangeCert (__main__.TestOpenshift) # duration: 205s # SKIP Known issue #6359
```
(Note the errors, but the test are "ok" with a "SKIP and the # known issue).

 - What is `$TEST_OS` in your case? I think you are running this against a custom image. But this still needs `TEST_OS=rhel-7-5` so that the matching of bots/naughty/`$TEST_OS/` can work.
 - Do you have bots/naughty/rhel-7-5/ in your environment? Perhaps you only checked out a subset of bots/ in your env?

**Comment by jscotka** [comment]
I uses something like, so all subtree of bots should be there in master branch revision: 
```
VERSION=$1
WHERETOUNPACK=$2
git clone https://github.com/cockpit-project/cockpit.git $WHERETOUNPACK
cd $WHERETOUNPACK
git checkout tags/$VERSION
git checkout master -- bots/
```
so all bots should be there.
But I've found one issue, what could cause this, that I expected that varibale is set to ``TEST_OS=rhel-7-5`` but by mistake it was set to ``TEST_OS=rhel-7-4`` so probably could be caused that it is not in https://github.com/cockpit-project/cockpit/tree/master/bots/naughty/rhel-7-4 but just in rhel-7-5 known bugs.
I'll retest it with properly set ``TEST_OS=rhel-7-5`` 
I should avoid using  syntax like``TEST_OS=${TEST_OS:-rhel-7-5}`` :-)

**Comment by jscotka** [comment]
we can close this issue, unless you want to fix issues with rhel-7-4

**Comment by martinpitt** [comment]
Nice, so it works now with rhel-7-5?
