### ISSUE TITLE
mobile: improve lists & tables on Network & Services

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#8672]
Network and Services pages are particularly bad in mobile.

As reported by @mbastiaan in #8464

**Comment by marusak** [comment]
I am not sure what it meant back when this was reported.  But I checked it on my phone now and I think they work well. On network the tables fit nicely on the display and on Services the tables is wider than my screen, but it is intuitive that I need to move more to the right to see the rest of the page.
