### ISSUE TITLE
machines: Cannot use Backspace key to delete the storage size on VM creation window

### ISSUE THREAD

**Issue by qiyuann** [cockpit-project/cockpit#8678]
**Description of problem:**
Cannot use Backspace key to delete the storage size on VM creation window

**Version-Release number of selected component (if applicable):**
cockpit-machines-162-1.fc26.noarch
cockpit-bridge-151-2.fc26.x86_64
cockpit-system-151-2.fc26.noarch
libvirt-3.2.1-7.fc26.x86_64
Firefox 57.0.1

**How reproducible:**
100%

**Steps to Reproduce:**
1. Click "Create New VM" button to open the vm creation dialogue.
2. Set/select each field as below:
![screenshot from 2018-02-22 16-58-58](https://user-images.githubusercontent.com/23047456/36529061-22a664ac-17f2-11e8-84ef-4d2aace44e04.png)

3. Try to delete the storage size numbers using Backspace key.

**Actual results:**
1. The storage size numbers cannot be deleted.

**Expected results:**
1. The storage size numbers could be deleted by Backspace key.

**Comment by martinpitt** [comment]
Confirmed, this affects memory size too. I'll send a PR to fix it.
