### ISSUE TITLE
that new hardware link doesnt seem to work (lscpi/dmidecode) when you press it on a remote node tab it takes you to the hardware page of the local system

### ISSUE THREAD

**Issue by doverride** [cockpit-project/cockpit#8681]
that new hardware link doesnt seem to work (lscpi/dmidecode) when you press it on a remote node tab it takes you to the hardware page of the local system

**Comment by martinpitt** [comment]
Ah, same old bug again - one of these days we should fix `cockpit.jump()` to DTRT :-)

**Comment by martinpitt** [comment]
Fixed in PR #8685, thanks for spotting!
