### ISSUE TITLE
machines: Allow selection of UEFI vs BIOS for machine 

### ISSUE THREAD

**Issue by sghosh151** [cockpit-project/cockpit#8682]
Support UEFI instead of BIOS for VM configuration.

Fedora has included the ability to select UEFI as the VM firmware as an alternative to  BIOS (seabios). Virt-manager/virt-install includes support for this option.
ref: http://blog.wikichoon.com/2016/01/uefi-support-in-virt-install-and-virt.html

**Comment by stefwalter** [comment]
CC @mareklibra

**Comment by mareklibra** [comment]
@sghosh151 , thanks for pointing this out.
This feature makes sense and would be nice to have it in the Create VM Dialog.

**Comment by KKoukiou** [comment]
I am wondering if it should go in the create VM dialog or the the overview for later customization;
libvirt docs for this: https://libvirt.org/formatdomain.html#elementsOSBIOS

@martinpitt do you think that it makes sense to expose this option in the create VM dialog?

**Comment by martinpitt** [comment]
@KKoukiou : Technically, absolutely. From a UI POV it becomes a bit crowded. Does this need to be set on creation time? With plain QEMU you can basically choose at each boot, so maybe it could be in the same league as e. g. the vCPU settings?
