### ISSUE TITLE
console /etc/issue: print the hostname IP address 

### ISSUE THREAD

**Issue by sghosh151** [cockpit-project/cockpit#8701]
https://bugzilla.redhat.com/show_bug.cgi?id=1110763 introduced the capability to print the Cockpit URL on the VT - pretty cool, but when a system has multiple IP addresses, it seems to pick the first address seen to print on the VT via /etc/issue.

It would be better to either use the hostname or the IP address that matches the hostname. 

Use case - primary IP address matches the hostname - 4 other NICs on the system to support VM bridges - those can change over time since I don't care about the bridge IP address

**Comment by stefwalter** [comment]
Makes sense. We would need to make these changes to agetty in util-linux. @martinpitt Do you agree that making this change is necessary for "finishing" this feature?

**Comment by martinpitt** [comment]
I agree that we should rather print the hostname than an IP address. This is currently being discussed and worked on by @allisonkarlitskaya in issue #9129, so I'm closing this as a duplicate.
