### ISSUE TITLE
blank screen after login (Armbian + Apache 2.14)

### ISSUE THREAD

**Issue by TalmarGrosskotz** [cockpit-project/cockpit#8702]
Hi, I tried using cockpit on my Cubietruck-Server with the lastest Armbian. when i call the page on port 9090, I get the loginscreen. After login there is a blank page and the console says something about jqury not found and an Error 401.

Anybody know a fix for this?

**Comment by stefwalter** [comment]
Anything related in the system logs? Look for anything related to cockpit. Can you please post complete error messages?

**Comment by TalmarGrosskotz** [comment]
Glad to say that another reinstall solved the problem entirely.. don't know why but it works now.
