### ISSUE TITLE
Dashboard not showing OS if hostnamed is not available

### ISSUE THREAD

**Issue by BJ01090** [cockpit-project/cockpit#8710]
Hi,

on Dashboard some Server not sown the OS. In this case this are 3 Debian 9 server in lxc container. Other debian 9 lxc container show the os in Dashboard.

Attached an screenshot.
![unbenannt](https://user-images.githubusercontent.com/36855919/36681270-6c4001e4-1b18-11e8-9a27-9390e72acc9c.jpg)

**Comment by martinpitt** [comment]
At first sight this seems to be related to systemd-hostnamed not working in unprivileged LXC containers, which is a [known downstream bug](https://launchpad.net/bugs/1575779).

**Comment by BJ01090** [comment]
Found a solution here: https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1575779/comments/12

**Comment by martinpitt** [comment]
For the record, this is done in https://github.com/cockpit-project/cockpit/blob/master/pkg/lib/machines.js in `Machines()`. We could fall back to reading /etc/os-release if hostnamed is not available (which might happen for other reasons than just this), so I keep this open.

**Comment by martinpitt** [comment]
This got fixed in LXC a while ago, so let's close this.
