### ISSUE TITLE
 Session issue  multiple browsers

### ISSUE THREAD

**Issue by die7** [cockpit-project/cockpit#8719]
I have strange behavior with  multiple sessions/browsers faced, in my example I used IE 11 and firefox 58.02, on the both  I can login to cockpit-ws, but from dash I get no access to other systems with both just with first on.

on non working I try to troubleshoot

to instead of reconnect I have chosen troubleshot >  entering password and then I get new issue like:
Failed to create file '/etc/cockpit/machines.d/99-webui.json.DM95EZ': Permission denied ...

If I cancel then I can access it:

first attempt

JAVA CON:
cat: *.pub: No such file or directory
  cockpit.js:523
failed to list keys in home directory: cat: *.pub: No such file or directory  index.js:1981
cat: *.pub: No such file or directory
  cockpit.js:523
failed to list keys in home directory: cat: *.pub: No such file or directory  index.js:1981
cat: *.pub: No such file or directory

entering password:

JAVA CON:
failed to call cockpit.Machines.Update():  <unavailable>  index.js:89
Failed to create file '/etc/cockpit/machines.d/99-webui.json.XL06EZ': Permission denied  index.js:2201

but if I can press on the cancel I can login, but when I switch from node to node it it ask me in th eloop to update password

at end I have
Unexpected match of multiple logins.

**Comment by martinpitt** [comment]
At first sight it seems like you logged in as an admin in one  browser, and didn't tick the "Use my password for privileged tasks" on the other?

**Comment by martinpitt** [comment]
ping?

**Comment by martinpitt** [comment]
No response, closing. Please reopen if you have further information. Thank you!

**Comment by uri-iothreat** [comment]
I experienced a similar issue, I resolved it by changing the owner of the cockpit folder in my /etc folder from "root" to the user that I'm using to login and manage my local cockpit instance.

For example:
sudo chown -R <USER> /etc/cockpit/
