### ISSUE TITLE
apps installation fails with "multiple matches"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8731]
```
sudo dnf copr enable mvo/cockpit-app-freeipa
sudo dnf install appstream-data-mvo -y
```
If on Fedora 27, hack /etc/yum.repos.d/_copr_mvo-cockpit-app-freeipa.repo to replace `$releasever` with `26`, as the COPR only builds for F26.

Go to the apps page and try to install any app:

![error](https://user-images.githubusercontent.com/200109/36786897-586635d2-1c88-11e8-9f7b-22b5439b3911.png)

Presumably this is due to the "source"?
```
❱❱❱ pkcon resolve demo-app
Resolving                     [=========================]         
Loading cache                 [=========================]         
Available   	demo-app-7-0.noarch (mvo-cockpit-app-freeipa)               	Cockpit Demo Application
Available   	demo-app-7-0.src (mvo-cockpit-app-freeipa)                  	Cockpit Demo Application
```

**Comment by martinpitt** [comment]
The filter in `install()` does seem to work. When adding a console.log, I get

    Resolving demo-app to demo-app;7-0;noarch;mvo-cockpit-app-freeipa

and nothing else. This actually seems to be a packagekit regression:
```
❱❱❱ pkcon install 'demo-app;7-0;noarch;mvo-cockpit-app-freeipa'
Installing                    [=========================]         
Finished                      [=========================]         
Fatal error: Multiple matches of demo-app;7-0;noarch;mvo-cockpit-app-freeipa
```
Maybe the "multiple" is wrong, and it really wants to complain about "no match"?
```
❱❱❱ pkcon resolve 'demo-app;7-0;noarch;mvo-cockpit-app-freeipa'
Resolving                     [=========================]         
```

**Comment by martinpitt** [comment]
If I hack the `install()` function to replace `name` with `"bash-doc"`, it happily installs bash-doc. So this looks like some PackageKit bug with COPR repositories. There might be some work around with tighter flags, but I figure this should be fixed on the PK side.

**Comment by Crote** [comment]
Is there an upstream bug for this? I seem to have exactly the same issue with the COPR julekgwa/Bingwallpapers.

**Comment by martinpitt** [comment]
I never got this any more, let's close this.

**Comment by martinpitt** [comment]
Or rather, let's track it in #21035
