### ISSUE TITLE
Software Update page refers to "Cockpit"

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8737]
The Update Page refers to "cockpit"
![screenshot from 2018-03-01 11-05-00](https://user-images.githubusercontent.com/209895/36838802-75b16a90-1d40-11e8-8689-b47daaf9ac09.png)

While the console refers to it as "Admin console"
![screenshot from 2018-03-01 11-06-43](https://user-images.githubusercontent.com/209895/36838900-b88941b2-1d40-11e8-8933-3d2cee4068f8.png)

Should we call it "Admin console" on the Updates Page as well?

**Comment by martinpitt** [comment]
That would be confusing IMHO; "cockpit" does appear literally as a package name in the available updates list. Maybe it can be reworded differently somehow?  "The cockpit package will be updated. [...]"?

**Comment by andreasn** [comment]
Yeah, or something like:
"The Admin Console (cockpit package) itself will be updated"?
Not sure.

**Comment by martinpitt** [comment]
That would work for me. It makes the string even longer, but I hope it wraps properly :-)

**Comment by martinpitt** [comment]
As "Admin Console" is not very well visible yet, and not at all in e. g. Debian/Ubuntu or older RHELs, how about "This web interface itself will be updated. …"?

**Comment by andreasn** [comment]
Yeah, I think that makes sense. Let's go with that for now, at least until we figure something better out.

**Comment by martinpitt** [comment]
Ack, taking over then. Unless of course you want to file the PR (would be appreciated).
