### ISSUE TITLE
Applications: The Install button is still clickable on the details page while an install is in progress

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8738]
The install button appears, and is active on an Applications detail page, even while an application is currently being installed.
I didn't dare pressing this button:
https://andreasn.portknox.net/s/bSLFXbLQmgK42Xj

**Comment by marusak** [comment]
> I didn't dare pressing this button:

It starts another installation, but there can be only one installation at one time, therefore it shows:
`Waiting for other programs to finish using the package manager...`

Anyway, it should shows the progress bar on both places.
