### ISSUE TITLE
check-openshift TestOpenshiftPrerelease.testVolumes fails against Openshift 3.9

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8744]
One of the two regressions in #8740 which is probably an API change/regression:
```
$ test/verify/check-openshift TestOpenshiftPrerelease.testVolumes
[...]
-> wait: ph_is_present("modal-dialog")
<- {u'type': u'undefined'}
-> wait: !ph_is_present("modal-dialog input#modify-name")
<- {u'type': u'undefined'}
-> wait: ph_in_text("modal-dialog span#modify-name","pv2")
<- {u'type': u'undefined'}
-> wait: !ph_is_present("modal-dialog input#modify-capacity")
<- {u'type': u'undefined'}
-> wait: ph_in_text("modal-dialog span#modify-capacity","1Gi")
<- {u'type': u'undefined'}
-> ph_set_val("modal-dialog #modify-path","/not-tmp")
<- {u'type': u'undefined'}
-> ph_click("modal-dialog .modal-footer button.btn-primary",false)
<- {u'type': u'undefined'}
-> wait: !ph_is_present("modal-dialog")
> warning: PersistentVolume "pv2" is invalid: spec.persistentvolumesource: Forbidden: is immutable after creation
<- {u'type': u'string', u'value': u'condition did not become true'}
Traceback (most recent call last):
  File "/home/martin/upstream/c2/test/verify/kubelib.py", line 250, in testVolumes
    b.wait_not_present("modal-dialog")
  File "/home/martin/upstream/c2/test/common/testlib.py", line 273, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "/home/martin/upstream/c2/test/common/testlib.py", line 264, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/martin/upstream/c2/test/common/testlib.py", line 261, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/martin/upstream/c2/test/common/testlib.py", line 169, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
Error: timeout
wait_js_cond(!ph_is_present("modal-dialog")): condition did not become true
```
Example: https://fedorapeople.org/groups/cockpit/logs/pull-8740-20180301-133333-f8bb64f9-verify-fedora-27/log.html#139

I'm handling these as expected failures for now, so that we can land the new image and avoid other regressions.

**Comment by martinpitt** [comment]
Actually, let's not do known issues  for that, too much noise (it would need to be added to all images).

**Comment by martinpitt** [comment]
In OpenShift 3.7, I can create a host path volume "foo" on /tmp/, and change the path to /var:
```
oc patch pv foo -p '{"kind":"PersistentVolume","metadata":{"name":"foo"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"500M"},"persistentVolumeReclaimPolicy":"Retain","hostPath":{"path":"/var"}}}'
```
This is what Cockpit does, see pkg/kubernetes/scripts/volumes.js `performModify()`. After that, `oc get pv foo -o json` shows the updated path.

In 3.9 this generates the  error that's already visible in the cockpit log:

   The PersistentVolume "foo" is invalid: spec.persistentvolumesource: Forbidden: is immutable after creation

I take it that this is deliberate and we need to adjust cockpit accordingly. E. g. the name and capacity are already immutable and cannot be changed in the "edit" dialog. The trick is to conditionally allow editing or not for < and >= 3.9.

**Comment by martinpitt** [comment]
> The trick is to conditionally allow editing or not for < and >= 3.9.

This is indeed tricky.. We don't do OpenShift server version tests anywhere else, and the API itself doesn't tell us whether that field is immutable (it also isn't for )

So I see three options:
 1. Keep the field editable right now, and just live with the error message in the dialog ("immutable blah bla") if the user actually tries to change it. Not 100% pretty, but workable and keeps backwards compat. This already happens when running against current kubernetes (our test does not catch this case, it only runs the modify test on openshift).
 2. Generally disable host path editing. This would do the right thing for current Kubernetes and upcoming OpenShift 3.9, but be a small regression for 3.7 and earlier. It's a corner case feature though, so maybe that's just acceptable.
 3. Add a version comparison check to the API for this case and  restrict editing to openshift < 3.7 (taking care to correctly interpret kubernetes versions).

@stefwalter, do you have an opinion here?

**Comment by stefwalter** [comment]
If this were a host specific feature I would definitely choose option 2. The whole point of Cockpit's architecture is to iterate along with the system and its capabilities. Since this is a cluster API, and not a system API ... then I understand this is a bit of a grey area ... but that's still where I would start.

**Comment by martinpitt** [comment]
OK, let's just disable it then. I can't really see a case where someone would depend on changing the host dir of a volume; it can just as well be deleted and recreated again. Thanks!
