### ISSUE TITLE
machines-ovirt: Should disable the "Create New VM" button while the host is managed by ovirt.

### ISSUE THREAD

**Issue by kenzhaoyihui** [cockpit-project/cockpit#8767]
Description of problem:
Should disable the "Create New VM" button while the host is managed by ovirt. When the host is managed by ovirt , then the "Create New VM" didn't work.

Version-Release number of selected component (if applicable):
RHEL-7.5-20180221
cockpit-machines-ovirt-162-1.el7.centos.noarch
cockpit-ws-154-3.el7.x86_64
cockpit-bridge-154-3.el7.x86_64
cockpit-system-154-3.el7.noarch
cockpit-154-3.el7.x86_64

How reproducible:
100%

Steps to Reproduce:
1. Add the host to the engine( host is managed by ovirt)
2. Try to create new VM from the cockpit UI.

Actual results:
After step2, the "create new vm" function didn't work.

Expected results:

Additional info:

**Comment by martinpitt** [comment]
CC @mareklibra, @suomiy

**Comment by mareklibra** [comment]
Thumb up until implemented for the ovirt flow

**Comment by andreasn** [comment]
Here is a mockup with a similar behaviour to the one on the Storage Volume Group creation page.
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/56a8ca9d83aad5b33db3ca40a4ab04dccf587c04/virtual-machines/create-new-vm-ovirt.png)

Is the wording clear enough?

**Comment by mareklibra** [comment]
@andreasn , wording is clear from my POV.
When is this tooltip rendered? After click? And shall the "Create New VM" still look like a link (incl. the different mouse pointer) but in lighter blue?

**Comment by andreasn** [comment]
It's rendered on `hover`. The color is `#7dc3e8` and the pointer is `default` instead of `pointer`
If you have a system with LVM, check https://<ip-address>:9090/storage#/vg/<vg-name> for how it works on the storage page.

**Comment by andreasn** [comment]
I can't the exact code, but I think @mvollmer would know.

**Comment by mareklibra** [comment]
@andreasn , `hover` will not work on touchscreens. I think we should rather remove it whenever possible. Please correct me.

**Comment by andreasn** [comment]
@mareklibra just tested it on my phone, and it shows up on click as well.

**Comment by andreasn** [comment]
Here is the tooltip code https://github.com/cockpit-project/cockpit/blob/fabe81046672a6f1e96523f2793774950b2c41e5/pkg/lib/cockpit-components-tooltip.jsx

**Comment by kenzhaoyihui** [comment]
Tested with cockpit-machines-ovirt-165-3.el7.noarch, it also exists. And create vm Dialog for ovirt is enable.

**Comment by martinpitt** [comment]
@kenzhaoyihui : The fix will be in next Wednesday's 167.
