### ISSUE TITLE
machines-ovirt: Login to the cockpit with host fqdn(hostname) will miss some information while adding the host to engine using the host ip.

### ISSUE THREAD

**Issue by kenzhaoyihui** [cockpit-project/cockpit#8768]
Description of problem:
Add host to engine by its ip, if log in to cockpit by hostname, then some infos will miss on pages, include overview info, consoles info, ovirt info, Host to maintaince button. if log in to cockpit by host ip, there is no such problem. 
Additionally, if add  host to engine by its hostname(fqdn), then there is no such problem, no matter loging in to cockpit by host ip or hostname. 

Version-Release number of selected component (if applicable):
RHEL-7.5-20180221
cockpit-machines-ovirt-162-1.el7.centos.noarch
cockpit-ws-154-3.el7.x86_64
cockpit-bridge-154-3.el7.x86_64
cockpit-system-154-3.el7.noarch
cockpit-154-3.el7.x86_64

How reproducible:
100%

Steps to Reproduce:
1. Add the host to the engine by its ip
2. Create the vm by ovirt(engine)
3. Login the cockpit by ip or fqdn

Actual results:
The same as the Description

Expected results:
After step3, login the cockpit by ip or fqdn have the same results.

Additional info:
[login_cockpit_ip](https://github.com/kenzhaoyihui/issue_picture/blob/master/login_cockpit_ip.png)
[login_cockpit_fqdn](https://github.com/kenzhaoyihui/issue_picture/blob/master/login_cockpit_fqdn.png)

**Comment by martinpitt** [comment]
CC @mareklibra, @suomiy

**Comment by mareklibra** [comment]
Thanks for reporting that.

To fix, `selectors.es6:getHost()` must be extended
