### ISSUE TITLE
Cockpit UI does not show "Hardware" on '/system' view on ARM

### ISSUE THREAD

**Issue by goern** [cockpit-project/cockpit#8807]
Looking at the web ui on a Fedora Server on ARMv7 I dont see any hardware info on the /system view. It might be related to dmidecode missing?!

![bildschirmfoto 2018-03-10 um 20 38 39](https://user-images.githubusercontent.com/260331/37246089-160e3afe-24a3-11e8-9688-7dcb5d79c501.png)

Cockpit Version 162

**Comment by martinpitt** [comment]
Correct, right now the hardware view only supports DMI.

**Comment by buckethead41** [comment]
Request that cockpit determine if dmidecode is present and identify same to users.

**Comment by buckethead41** [comment]
Please check if DMI is present in such a way that warnings aren't written to logs. 
![untitled](https://user-images.githubusercontent.com/42307198/43997485-440c66a8-9daa-11e8-9511-0c640b5cc7a5.jpg)

**Comment by martinpitt** [comment]
All fixed in PR #11005
