### ISSUE TITLE
add host: mistyping an address is very punishing

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8818]
I wanted to add another host, but I mistyped the address, and got this error message:
![screenshot from 2018-03-13 19-03-00](https://user-images.githubusercontent.com/209895/37360711-4d29b89c-26f1-11e8-8fd0-98ef6c45ebd8.png)

The only thing I can do here is to close the dialog and start over, crossing my fingers that I type it right this time.

**Comment by andreasn** [comment]
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/ba522c8a1721ecd4168ed7fa9d5700db69d7f5b8/add-system/machine-dialogs-errors.png)

**Comment by andreasn** [comment]
Note that this also gets rid of the word "Cockpit", as it's irrelevant in this situation.

**Comment by andreasn** [comment]
Tried to simplify the text a bit:
"Couldn’t connect to the host"

**Comment by Gundersanne** [comment]
The current state of this:

![image](https://user-images.githubusercontent.com/11140201/51025325-01202780-158c-11e9-9fb0-3685f7b7ee04.png)

Is this good enough?

**Comment by martinpitt** [comment]
Let's close this for now, it has certainly improved enough IMHO.
