### ISSUE TITLE
Can't talk to DBUS?

### ISSUE THREAD

**Issue by dhilst** [cockpit-project/cockpit#8823]
I'm trying to talk to DBUS to get a filtered list of services. But I can't grasp the cockpit.dbus interface. I tried this: 

```
cockpit.dbus("org.freedesktop.systemd1", {superuser: "try"}).proxy("org.freedesktop.systemd1.Manager", "/org/freedesktop/systemd1").ListUnits().done(d => console.log("Done", d)).fail(e => console.error("Error", e));
```

But I get ListUnits is not a function. What I'm doing wrong?

**Comment by dhilst** [comment]
Okay, I got it. Here is how:

```
var systemdManager = cockpit.dbus("org.freedesktop.systemd1").proxy("org.freedesktop.systemd1.Manager", "/org/freedesktop/systemd1");
systemdManager.ListUnits().done(console.log);
```
I hit some weird problem with firefox where `console.log` wasn't printing anything. I had to restart firefox.

**Comment by mvollmer** [comment]
> But I get ListUnits is not a function.

The functions on a proxy don't appear immediately.  They are created based on "introspecting" the object, which is done asynchronously in the background.  However, there is also a cache, and thus sometimes the functions _do_ appear immediately.  This is probably the reason why your second version works.

You can wait until the proxy is ready with `proxy.wait`.

**Comment by dhilst** [comment]
Hi @mvollmer, thanks for the reply. So the second version may not work if the second line executes before introspection happens!?

Would this be safer?

``` javascript
var systemdManager = cockpit.dbus("org.freedesktop.systemd1").proxy("org.freedesktop.systemd1.Manager", "/org/freedesktop/systemd1");
systemdManager.wait().done(() => systemdManager.ListUnits().done(console.log));
```

**Comment by mvollmer** [comment]
>  So the second version may not work if the second line executes before introspection happens!?

Yes, that's what I would expect.  How do you run these commands?  From the JavaScript console, or from some script?

If you run them in the console, the introspection happens in the background while the console prompt is waiting for more input.  If you run them in a script, there is no waiting between statements, and the second line should always 'crash'.

(I am actually not sure how the cache works exactly, timing-wise, but you shouldn't rely on it anyway.)

**Comment by dhilst** [comment]
I ran them in the console. In script I wrapped it with something like

``` javascript
function systemdManager() {
  const defer = jQuery.Deferred();
  const proxy =  cockpit.dbus("org.freedesktop.systemd1").proxy("org.freedesktop.systemd1.Manager", "/org/freedesktop/systemd1");
  proxy.wait().done(() => defer.resolve(proxy)).fail(defer.reject);
  return defer.promise();
}

systemdManager().done(proxy => /* do stuff */);
```
