### ISSUE TITLE
Disabled links don't show tooltips

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#8827]
For example, the "Join domain" link on the "System" page is disabled when realmd is not installed, but it doesn't show the tooltip that explains why.

**Comment by andreasn** [comment]
I can confirm this issue.
Run "yum remove realmd" on any RHEL or Fedora system to see it.

**Comment by martinpitt** [comment]
I spent some time fixing notifications in #8829 / PR #8835 , I'll look at this as well.

**Comment by martinpitt** [comment]
Fixed in #8835
