### ISSUE TITLE
add key dialog is broken

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8828]
Some pretty wild scrolling going on there.

![screenshot from 2018-03-14 12-26-32](https://user-images.githubusercontent.com/209895/37399762-fbead9ec-2782-11e8-802b-324164b90a35.png)

**Comment by Gundersanne** [comment]
I can confirm that this is still an issue. Should the inner dropdown come on top of the rest of the dialog? Not sure how to achieve that but that would fix it.

**Comment by KKoukiou** [comment]
This was fixed with:
```
commit e3f0a617d0167304aca23a2fe3a11b52ca341d51
Author: Katerina Koukiou <kkoukiou@redhat.com>
Date:   Mon Jul 15 19:52:32 2019 +0200

    Rewrite FileAutoComplete component to fix accessibility issues
```
