### ISSUE TITLE
inconsistent tool tips

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#8829]
We currently have at least three tooltip styles. On our React pages, like kdump or React Patterns:

![tooltip-react](https://user-images.githubusercontent.com/200109/37402038-584acf88-278a-11e8-8bba-94278808123e.png)

On the system page there are "broken" ones on Hardware and Machine ID, as well as the navigation menu items on the left:

![tooltip machine id](https://user-images.githubusercontent.com/200109/37401825-b01ce404-2789-11e8-9b99-b6d38fbdc86b.png)

This is because this just sets the `title=` attribute instead of using the [jQuery .tooltip()](https://www.w3schools.com/bootstrap/bootstrap_ref_js_tooltip.asp) method. When doing that, they look like the React ones:

![tooltip-system-fixed](https://user-images.githubusercontent.com/200109/37401928-02ff36d6-278a-11e8-9482-d06141c53b44.png)

Finally, on the system page on the blue (i)s we have this style, which also needs to be *clicked*, not just hovered:

![tooltip-system-2](https://user-images.githubusercontent.com/200109/37402103-99fa7c94-278a-11e8-9bfa-7a184f0e1a6c.png)

We should pick one style and apply it consistently.

The React one has a nice contrast and looks a little more "distinguished". The latter (white) one is nicer for showing icons, as the grey one has poor contrast in this case:

![tooltip-system-updates](https://user-images.githubusercontent.com/200109/37402220-ffc92fde-278a-11e8-8fc2-30faad364439.png)

(The text color is wrong, I haven't looked into that yet - but the icon is the point here)

Hint from @garrett: try `text-shadow`

**Comment by garrett** [comment]
Accessibility concerns:
1. `title` should be used when possible; if it gets "upgraded" from the browser-based tooltip to the richer one, fine, as along as it's accessible.
2. For the "synchronized with" — would you really want a robotic voice reading off that IPv6 hostname to you? We need to be aware of problems like this (as aXe and other tools will _not_ let us know).

**Comment by andreasn** [comment]
I think those are good accessibility concerns regarding the IPv6 hostname, and thanks for bringing those up!
But let's keep this issue about the presentation of the different tooltips, and then file specific a11y bugs as separate issues.

**Comment by garrett** [comment]
## Browser tooltips

- uses the `title` attribute; browser handles this natively
- Example: second screenshot, system hardware information
- Browsers tooltips should not be used. These should be upgraded to PatternFly / jQuery rich tooltips.

## PatternFly & jQuery tooltips

- [**PatternFly's implementation of tooltips**](https://www.patternfly.org/pattern-library/widgets/#tooltip); style and functionality is also shared with jQuery's `.tooltip()`
- Example: first screenshot, kdump status
- Tooltips should be used when extra information should be handled.

## PatternFly Info Tips

- [**PatternFly's Info tips**](https://www.patternfly.org/pattern-library/widgets/#info-tip): requires clicking and can be interacted with
- Example: fourth screenshot, system time
- Info tips should be used when contextual menus are needed.

---

**Summary**: Use PatternFly / jQuery tooltips when you need tooltips. Info tips should only be used when you expect interaction.

**Comment by garrett** [comment]
(The above is based on a conversation on IRC earlier today. Please correct if wrong.)

**Comment by martinpitt** [comment]
Thanks @garrett for the summary! So I'll go with the transparent-gray notifications by default on the systems page and the menu navigation for now, and will try `text-shadow` for the icons.

**Comment by martinpitt** [comment]
The nav menu also uses browser "title" style tooltips:

![tooltip-menu-standard](https://user-images.githubusercontent.com/200109/37458458-69865d42-2845-11e8-9df4-b623dd817d4b.png)

But converting them to the jquery/PF ones looks really crappy, due to gray-on-gray:

![tooltip-menu-jquery](https://user-images.githubusercontent.com/200109/37458481-73c1503c-2845-11e8-96c1-fb8b26aa2a95.png)

So I suppose I leave these alone for now, and just clean up the /system page for now.

**Comment by garrett** [comment]
Yikes. I think titles are only needed in the navigation when the string is truncated anyway. It's visible and screen readers should pick up the items without resorting to title.

When I redid the nav, I tried to make sure even the longest of our labels fit in without truncation. Perhaps we can just remove the `title` attributes in this subnav? :man_shrugging:

**Comment by martinpitt** [comment]
> Perhaps we can just remove the title attributes in this subnav

Indeed! They are just redundant. The simplest ideas are the best :+1:
