### ISSUE TITLE
storage: individual buttons instead of dropdowns

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8834]
I spoke to @mvollmer on IRC and we were saying we should move all the actions on the storage pages into individual buttons, to make the actions more discoverable, instead of hiding all the actions under dropdowns.
This would affect these pages:
 * RAID
 * Volume group
 * VDO

**Comment by andreasn** [comment]
I think it's all individual buttons now, @mvollmer can you confirm?

**Comment by mvollmer** [comment]
> I think it's all individual buttons now, @mvollmer can you confirm?

Correct.
