### ISSUE TITLE
cockpit bridge leaks file descriptors

### ISSUE THREAD

**Issue by doverride** [cockpit-project/cockpit#8849]
https://danwalsh.livejournal.com/53603.html

**Comment by martinpitt** [comment]
Hello Dan,

can you please be more specific where you saw file descriptor leaks?

The  bridge itself indeed has tons of open fds:
```
$ ls -l /proc/`pgrep -xf cockpit-bridge`/fd/
total 0
lrwx------ 1 martin martin 64 28. Mär 09:44 0 -> socket:[286583]
lrwx------ 1 martin martin 64 28. Mär 09:44 1 -> socket:[288290]
lrwx------ 1 martin martin 64 28. Mär 09:44 10 -> socket:[288295]
lrwx------ 1 martin martin 64 28. Mär 09:44 11 -> socket:[287051]
lr-x------ 1 martin martin 64 28. Mär 09:44 12 -> anon_inode:inotify
lrwx------ 1 martin martin 64 28. Mär 09:44 13 -> socket:[289267]
lrwx------ 1 martin martin 64 28. Mär 09:44 14 -> socket:[289496]
lrwx------ 1 martin martin 64 28. Mär 09:44 17 -> socket:[289498]
lrwx------ 1 martin martin 64 28. Mär 09:44 2 -> socket:[288290]
lrwx------ 1 martin martin 64 28. Mär 09:44 3 -> socket:[288290]
lrwx------ 1 martin martin 64 28. Mär 09:44 4 -> socket:[286583]
lrwx------ 1 martin martin 64 28. Mär 09:44 5 -> anon_inode:[eventfd]
lrwx------ 1 martin martin 64 28. Mär 09:44 6 -> anon_inode:[eventfd]
lrwx------ 1 martin martin 64 28. Mär 09:44 7 -> socket:[288293]
lrwx------ 1 martin martin 64 28. Mär 09:44 8 -> socket:[288294]
lrwx------ 1 martin martin 64 28. Mär 09:44 9 -> anon_inode:[eventfd]
```

But they don't leak into spawned processes through the JS API (this is in Firefox' console):
```
>> cockpit.spawn(["ls", "-l", "/proc/self/fd"]).then(console.log)
← function Promise()
total 0
lr-x------ 1 martin martin 64 Mar 28 09:46 0 -> pipe:[314684]
l-wx------ 1 martin martin 64 Mar 28 09:46 1 -> pipe:[314685]
lrwx------ 1 martin martin 64 Mar 28 09:46 2 -> socket:[288290]
lr-x------ 1 martin martin 64 Mar 28 09:46 3 -> /proc/13336/fd
```
Cockpit does not use `exec*()` directly, but GLib's [g_spawn_*()](https://developer.gnome.org/glib/stable/glib-Spawning-Processes.html) family, which (sensibly) inverts the default behaviour:


> G_SPAWN_LEAVE_DESCRIPTORS_OPEN means that the parent's open file descriptors will be  inherited by the child; otherwise all descriptors except stdin/stdout/stderr will be closed before calling exec() in the child

and cockpit does not use this flag anywhere.

**Comment by doverride** [comment]
On Wed, Mar 28, 2018 at 07:53:26AM +0000, Martin Pitt wrote:
> Hello Dan,
> 
> can you please be more specific where you saw file descriptor leaks?

Here is one example:

----
type=PROCTITLE msg=audit(03/28/2018 10:59:00.478:508) : proctitle=/usr/lib/polkit-1/polkit-agent-helper-1 kcinimod
type=PATH msg=audit(03/28/2018 10:59:00.478:508) : item=1 name=/lib64/ld-linux-x86-64.so.2 inode=2761615 dev=fd:01 mode=file,755 ouid=root ogid=root rdev=00:00 obj=sys.id:sys.role:lib.ld_so.file:s0 nametype=NORMAL cap_fp=none cap_fi=none cap_fe=0 cap_fver=0
type=PATH msg=audit(03/28/2018 10:59:00.478:508) : item=0 name=/usr/lib/polkit-1/polkit-agent-helper-1 inode=976 dev=fd:01 mode=file,suid,755 ouid=root ogid=root rdev=00:00 obj=sys.id:sys.role:polkit.agent.cmd_file:s0 nametype=NORMAL cap_fp=none cap_fi=none cap_fe=0 cap_fver=0
type=CWD msg=audit(03/28/2018 10:59:00.478:508) : cwd=/run/user/9999
type=EXECVE msg=audit(03/28/2018 10:59:00.478:508) : argc=2 a0=/usr/lib/polkit-1/polkit-agent-helper-1 a1=kcinimod
type=SYSCALL msg=audit(03/28/2018 10:59:00.478:508) : arch=x86_64 syscall=execve success=yes exit=0 a0=0x7fa6137f8218 a1=0x7ffc0efa9e50 a2=0x5580d3950f90 a3=0x7fa6131610a0 items=2 ppid=16906 pid=16950 auid=kcinimod uid=kcinimod gid=kcinimod euid=root suid=root fsuid=root egid=kcinimod sgid=kcinimod fsgid=kcinimod tty=(none) ses=3 comm=polkit-agent-he exe=/usr/lib/polkit-1/polkit-agent-helper-1 subj=wheel.id:wheel.role:polkit.agent.subj:s0 key=(null)
type=AVC msg=audit(03/28/2018 10:59:00.478:508) : avc:  denied  { siginh } for  pid=16950 comm=polkit-agent-he scontext=wheel.id:wheel.role:cockpit.bridge.wheel.subj:s0 tcontext=wheel.id:wheel.role:polkit.agent.subj:s0 tclass=process permissive=0
type=AVC msg=audit(03/28/2018 10:59:00.478:508) : avc:  denied  { rlimitinh } for  pid=16950 comm=polkit-agent-he scontext=wheel.id:wheel.role:cockpit.bridge.wheel.subj:s0 tcontext=wheel.id:wheel.role:polkit.agent.subj:s0 tclass=process permissive=0
type=AVC msg=audit(03/28/2018 10:59:00.478:508) : avc:  denied  { read write } for  pid=16950 comm=polkit-agent-he path=socket:[1053049] dev="sockfs" ino=1053049 scontext=wheel.id:wheel.role:polkit.agent.subj:s0 tcontext=wheel.id:wheel.role:cockpit.bridge.wheel.subj:s0 tclass=unix_stream_socket permissive=0
type=AVC msg=audit(03/28/2018 10:59:00.478:508) : avc:  denied  { noatsecure } for  pid=16950 comm=cockpit-bridge scontext=wheel.id:wheel.role:cockpit.bridge.wheel.subj:s0 tcontext=wheel.id:wheel.role:polkit.agent.subj:s0 tclass=process permissive=0
----



> 
> The  bridge itself indeed has tons of open fds:
> ```
> $ ls -l /proc/`pgrep -xf cockpit-bridge`/fd/
> total 0
> lrwx------ 1 martin martin 64 28. Mär 09:44 0 -> socket:[286583]
> lrwx------ 1 martin martin 64 28. Mär 09:44 1 -> socket:[288290]
> lrwx------ 1 martin martin 64 28. Mär 09:44 10 -> socket:[288295]
> lrwx------ 1 martin martin 64 28. Mär 09:44 11 -> socket:[287051]
> lr-x------ 1 martin martin 64 28. Mär 09:44 12 -> anon_inode:inotify
> lrwx------ 1 martin martin 64 28. Mär 09:44 13 -> socket:[289267]
> lrwx------ 1 martin martin 64 28. Mär 09:44 14 -> socket:[289496]
> lrwx------ 1 martin martin 64 28. Mär 09:44 17 -> socket:[289498]
> lrwx------ 1 martin martin 64 28. Mär 09:44 2 -> socket:[288290]
> lrwx------ 1 martin martin 64 28. Mär 09:44 3 -> socket:[288290]
> lrwx------ 1 martin martin 64 28. Mär 09:44 4 -> socket:[286583]
> lrwx------ 1 martin martin 64 28. Mär 09:44 5 -> anon_inode:[eventfd]
> lrwx------ 1 martin martin 64 28. Mär 09:44 6 -> anon_inode:[eventfd]
> lrwx------ 1 martin martin 64 28. Mär 09:44 7 -> socket:[288293]
> lrwx------ 1 martin martin 64 28. Mär 09:44 8 -> socket:[288294]
> lrwx------ 1 martin martin 64 28. Mär 09:44 9 -> anon_inode:[eventfd]
> ```
> 
> But they don't leak into spawned processes through the JS API (this is in Firefox' console):
> ```
> >> cockpit.spawn(["ls", "-l", "/proc/self/fd"]).then(console.log)
> ← function Promise()
> total 0
> lr-x------ 1 martin martin 64 Mar 28 09:46 0 -> pipe:[314684]
> l-wx------ 1 martin martin 64 Mar 28 09:46 1 -> pipe:[314685]
> lrwx------ 1 martin martin 64 Mar 28 09:46 2 -> socket:[288290]
> lr-x------ 1 martin martin 64 Mar 28 09:46 3 -> /proc/13336/fd
> ```
> Cockpit does not use `exec*()` directly, but GLib's [g_spawn_*()](https://developer.gnome.org/glib/stable/glib-Spawning-Processes.html) family, which (sensibly) inverts the default behaviour:
> 
> 
> > G_SPAWN_LEAVE_DESCRIPTORS_OPEN means that the parent's open file descriptors will be  inherited by the child; otherwise all descriptors except stdin/stdout/stderr will be closed before calling exec() in the child
> 
> and cockpit does not use this flag anywhere.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/cockpit-project/cockpit/issues/8849#issuecomment-376795162

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by doverride** [comment]
So appears to me that cockpit bridge is running `/usr/lib/polkit-1/polkit-agent-helper-1 kcinimod` , and that is were a open unix domain socket seems to be leaked?

**Comment by doverride** [comment]
Is cockpit bridge executing that command "directly"? or is there some entity in between cockpit-bridge and /usr/lib/polkit-1/polkit-agent-helper-1 that might be the cause of this particular leak?

**Comment by doverride** [comment]
By the way: I am not "Dan". I was just referencing a blog post written by "Dan"

**Comment by doverride** [comment]
Might be systemctl, timedatectl or one of the other systemd "ctl" utils then ....
Thanks for looking into it. Closing

**Comment by doverride** [comment]
Seems to be `pkexec` in fact that is leaking it to polkit-agent-helper-1

So i suppose the sequence is: cockpit-bridge -> pkexec -> polkit-agent-helper-1

and pkexec is what leaks it when it executes polkit-agent-helper-1

**Comment by doverride** [comment]
nope I do not believe its pkexec either. Regardless, I will just forget about this issue and configure my access control to silently block these events....

**Comment by martinpitt** [comment]
Cockpit doesn't call polkit-agent-helper-1 directly, and I believe this is an internal helper program of polkit only. `pkexec` is called as a command line from the [shell manifest](https://github.com/cockpit-project/cockpit/blob/master/pkg/shell/manifest.json.in), so that doesn't have control over file descriptors.

Cockpit calls [polkit_agent_listener_register_with_options](https://www.freedesktop.org/software/polkit/docs/latest/PolkitAgentListener.html#polkit-agent-listener-register-with-options) and [polkit_agent_session_initiate](https://www.freedesktop.org/software/polkit/docs/latest/PolkitAgentSession.html#polkit-agent-session-initiate) in its C code; the latter spawns polkit-agent-helper-1, but also uses `g_spawn_async_with_pipes()`, so it should not leak fds.

So indeed I don't think this leak is in the cockpit code. Do you have the precise SELinux errors? They might contain a path or a pid, which could at least be mapped to cockpit-bridge vs. pkexec vs. the auth agent?

**Comment by doverride** [comment]
Take this event:

```
type=PROCTITLE msg=audit(03/29/2018 13:19:08.301:434) : proctitle=/usr/bin/w -sh kcinimod
type=PATH msg=audit(03/29/2018 13:19:08.301:434) : item=1 name=/lib64/ld-linux-x86-64.so.2 inode=2761615 dev=fd:01 mode=file,755 ouid=root ogid=root rdev=00:00 obj=sys.id:sys.role:lib.ld_so.file:s0 nametype=NORMAL cap_fp=none cap_fi=none cap_fe=0 cap_fver=0
type=PATH msg=audit(03/29/2018 13:19:08.301:434) : item=0 name=/usr/bin/w inode=2754011 dev=fd:01 mode=file,755 ouid=root ogid=root rdev=00:00 obj=sys.id:sys.role:who.cmd_file:s0 nametype=NORMAL cap_fp=none cap_fi=none cap_fe=0 cap_fver=0
type=CWD msg=audit(03/29/2018 13:19:08.301:434) : cwd=/run/user/9999
type=EXECVE msg=audit(03/29/2018 13:19:08.301:434) : argc=3 a0=/usr/bin/w a1=-sh a2=kcinimod
type=SYSCALL msg=audit(03/29/2018 13:19:08.301:434) : arch=x86_64 syscall=execve success=yes exit=0 a0=0x562f59f9d160 a1=0x562f59fabf60 a2=0x562f59f9d930 a3=0x7f4e19779b97 items=2 ppid=32607 pid=2093 auid=kcinimod uid=kcinimod gid=kcinimod euid=kcinimod suid=kcinimod fsuid=kcinimod egid=kcinimod sgid=kcinimod fsgid=kcinimod tty=(none) ses=3 comm=w exe=/usr/bin/w subj=wheel.id:wheel.role:who.subj:s0 key=(null)
type=AVC msg=audit(03/29/2018 13:19:08.301:434) : avc:  denied  { siginh } for  pid=2093 comm=w scontext=wheel.id:wheel.role:cockpit.bridge.wheel.subj:s0 tcontext=wheel.id:wheel.role:who.subj:s0 tclass=process permissive=0
type=AVC msg=audit(03/29/2018 13:19:08.301:434) : avc:  denied  { rlimitinh } for  pid=2093 comm=w scontext=wheel.id:wheel.role:cockpit.bridge.wheel.subj:s0 tcontext=wheel.id:wheel.role:who.subj:s0 tclass=process permissive=0
type=AVC msg=audit(03/29/2018 13:19:08.301:434) : avc:  denied  { read write } for  pid=2093 comm=w path=socket:[493559] dev="sockfs" ino=493559 scontext=wheel.id:wheel.role:who.subj:s0 tcontext=wheel.id:wheel.role:cockpit.bridge.wheel.subj:s0 tclass=unix_stream_socket permissive=0
type=AVC msg=audit(03/29/2018 13:19:08.301:434) : avc:  denied  { noatsecure } for  pid=2093 comm=cockpit-bridge scontext=wheel.id:wheel.role:cockpit.bridge.wheel.subj:s0 tcontext=wheel.id:wheel.role:who.subj:s0 tclass=process permissive=0
```

Here, whatever process executes `/usr/bin/w -sh kcinimod` leaks a unix daemon socket

This event happens when you `http://localhost:9090/users#/kcinimod`

**Comment by doverride** [comment]
There is a more complete audit:

```
----
type=PROCTITLE msg=audit(03/29/2018 13:29:17.921:801) : proctitle=/usr/bin/w -sh kcinimod
type=PATH msg=audit(03/29/2018 13:29:17.921:801) : item=1 name=/lib64/ld-linux-x86-64.so.2 inode=2761615 dev=fd:01 mode=fi
le,755 ouid=root ogid=root rdev=00:00 obj=sys.id:sys.role:lib.ld_so.file:s0 nametype=NORMAL cap_fp=none cap_fi=none cap_fe
=0 cap_fver=0
type=PATH msg=audit(03/29/2018 13:29:17.921:801) : item=0 name=/usr/bin/w inode=2754011 dev=fd:01 mode=file,755 ouid=root 
ogid=root rdev=00:00 obj=sys.id:sys.role:who.cmd_file:s0 nametype=NORMAL cap_fp=none cap_fi=none cap_fe=0 cap_fver=0
type=CWD msg=audit(03/29/2018 13:29:17.921:801) : cwd=/run/user/9999
type=EXECVE msg=audit(03/29/2018 13:29:17.921:801) : argc=3 a0=/usr/bin/w a1=-sh a2=kcinimod
type=SYSCALL msg=audit(03/29/2018 13:29:17.921:801) : arch=x86_64 syscall=execve success=yes exit=0 a0=0x562f59fc7e40 a1=0x562f59fc4090 a2=0x562f59fc9b50 a3=0x7f4e19779b97 items=2 ppid=32607 pid=3442 auid=kcinimod uid=kcinimod gid=kcinimod euid=kcinimod suid=kcinimod fsuid=kcinimod egid=kcinimod sgid=kcinimod fsgid=kcinimod tty=(none) ses=3 comm=w exe=/usr/bin/w subj=wheel.id:wheel.role:who.subj:s0 key=(null)
type=AVC msg=audit(03/29/2018 13:29:17.921:801) : avc:  granted  { execute } for  pid=3442 comm=w path=/usr/bin/w dev="dm-1" ino=2754011 scontext=wheel.id:wheel.role:who.subj:s0 tcontext=sys.id:sys.role:who.cmd_file:s0 tclass=file
type=AVC msg=audit(03/29/2018 13:29:17.921:801) : avc:  denied  { siginh } for  pid=3442 comm=w scontext=wheel.id:wheel.role:cockpit.bridge.wheel.subj:s0 tcontext=wheel.id:wheel.role:who.subj:s0 tclass=process permissive=0
type=AVC msg=audit(03/29/2018 13:29:17.921:801) : avc:  denied  { rlimitinh } for  pid=3442 comm=w scontext=wheel.id:wheel.role:cockpit.bridge.wheel.subj:s0 tcontext=wheel.id:wheel.role:who.subj:s0 tclass=process permissive=0
type=AVC msg=audit(03/29/2018 13:29:17.921:801) : avc:  denied  { read write } for  pid=3442 comm=w path=socket:[493559] dev="sockfs" ino=493559 scontext=wheel.id:wheel.role:who.subj:s0 tcontext=wheel.id:wheel.role:cockpit.bridge.wheel.subj:s0 tclass=unix_stream_socket permissive=0
type=AVC msg=audit(03/29/2018 13:29:17.921:801) : avc:  denied  { noatsecure } for  pid=3442 comm=cockpit-bridge scontext=wheel.id:wheel.role:cockpit.bridge.wheel.subj:s0 tcontext=wheel.id:wheel.role:who.subj:s0 tclass=process permissive=0
type=AVC msg=audit(03/29/2018 13:29:17.921:801) : avc:  granted  { execute } for  pid=3442 comm=cockpit-bridge name=w dev="dm-1" ino=2754011 scontext=wheel.id:wheel.role:cockpit.bridge.wheel.subj:s0 tcontext=sys.id:sys.role:who.cmd_file:s0 tclass=file
----
```

Above shows that `cockpit-bridge` executes `w`

**Comment by doverride** [comment]
The thing about the above is that it looks like w *also* executes itself .... So I suppose in the above event maybe w leaks when it executes it self?

(note the "type granted" message show the actual EXECVE events)
The "{ read write }" event is the actual leak event

**Comment by doverride** [comment]
O hmm, that w "execute" event is just w mmaping its executable. So yes afaict this just looks like cockpit-bridge leaks the fd when it executes w

**Comment by doverride** [comment]
`cockpit.spawn(["/usr/bin/w", "-sh", self.account_id])`

Are you sure that cockpit.spawn does not leak?
