### ISSUE TITLE
Issues with the new log filters

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#8870]
Today I've read new release note http://cockpit-project.org/blog/cockpit-164.html and I've noticed the part `Logs: Change severities` so I went straight for it and tested it.
I've found two issues with it:
1) https://github.com/cockpit-project/cockpit/blob/master/pkg/systemd/logs.js#L301 Severity `Critical and above` files only ABRT logs (which I like :) ) but it is definitely not the correct behavior. (Yes, I'm author of that, but in that time it worked differently and it was acceptable behavior) I would love to see one more severity `Only problems` with its own number (-1, 8?). What do you think?
2) Severity `Only emergency` (prio = 0) files everything as does `Debug or above` or `Everything`. I did not check the code that much, but it seems to me, that if log does not have any `PRIORITY` filed, it is picked up in the `Only emergency`? But I also found under `Only emergency` item with `Priority: 6` even though emergency should be with 0.

**Comment by marusak** [comment]
Hi folks,
I would love to fix this, mainly no.1. Can someone suggest how this should work now? I think we should enable looking only for problems, without breaking categories which are there. Any suggestions from the design point of view?
Thank you

**Comment by KKoukiou** [comment]
#2 was already fixed by https://github.com/cockpit-project/cockpit/pull/10951

**Comment by KKoukiou** [comment]
As per point 1, the log levels are the usual syslog log levels as documented in syslog(3), i.e.  "emerg" (0), "alert" (1), "crit" (2), "err" (3), "warning" (4), "notice" (5), "info" (6), "debug" (7).

I don't see the reason to add more or to remove everything. Ouput is pure journalctl -p PRIORITY_LEVEL with that being one of the above. Why do our magic here?

Let me know know if you still have something against to current implementation, else I 'll close this issue.

**Comment by marusak** [comment]
It works now correctly
