### ISSUE TITLE
2fa support for SSH login on dashboard

### ISSUE THREAD

**Issue by AdrianKoshka** [cockpit-project/cockpit#8876]
When you try to add a macine to your dashboard (in my case, a raspberry pi), you won't be able to if you have a form of 2fa setup on your SSH server (in my case, you need to enter a TOTP Code).

**Comment by inenting** [comment]
When will you be able to do this? This has been open for a long time and cockpit itself also supports 2fa

**Comment by amo13** [comment]
Looks like it is already working fine. If I try to login to my remote server with 2fa enabled on ssh, I get prompted for the second factor in the web ui.
