### ISSUE TITLE
Keep dashboard information cached

### ISSUE THREAD

**Issue by realies** [cockpit-project/cockpit#8884]
It would be great if the information presented in the dashboard gets populated with buffered history instead of starting to display statistics as soon as the page has loaded.

**Comment by martinpitt** [comment]
We won't do this. We want to show information that's real and current, or not show it at all. Showing buffered/cached graphs isn't very useful.

That said, the dashboard will probably cease to exist in the medium term, as we redesign the navigation menu and overview page.
