### ISSUE TITLE
enabling "nfsd" on server running cockpit causes SELinux alerts - Fedora 27

### ISSUE THREAD

**Issue by sghosh151** [cockpit-project/cockpit#8886]
Running cockpit with metrics (PCP) enabled on F27
Enable nfsd
series of SELinux alerts on PCP access to /proc/fs/nfsd/*

https://bugzilla.redhat.com/show_bug.cgi?id=1560307
https://bugzilla.redhat.com/show_bug.cgi?id=1560308
https://bugzilla.redhat.com/show_bug.cgi?id=1560313

**Comment by KKoukiou** [comment]
Fedora 27 is no longer maintained . Please re-open if you see these issues on release that hasn't reached EOL.
