### ISSUE TITLE
Image refresh for ubuntu-stable - fixed in #8910

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#8887]
Image refresh for ubuntu-stable
 * [ ] FAIL: image-refresh ubuntu-stable

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-hsxkd.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8887-20180325-222828/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-6ctnb.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8887-20180325-222929/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8887-20180325-222929/

**Comment by martinpitt** [comment]
Looks like Ubuntu stable now moved to persistent journal?
```
+ mkdir /var/log/journal
mkdir: cannot create directory '/var/log/journal': File exists
image-create: setup failed with code 1
```
