### ISSUE TITLE
Unlocking Cockpit (privilege escalation) using the lock button

### ISSUE THREAD

**Issue by zeroshft** [cockpit-project/cockpit#8899]
Is there some sort of limitation that hinders implementing locked to unlocked functionality? Right now, only going from unlocked to locked works as expected.

This question is in reference to the privilege escalation workflow described here: 
https://github.com/cockpit-project/cockpit/wiki/Feature:-unlocking-privileged-operations#workflows

**Comment by mattuskan** [comment]
Anyone have an update on this? Interested in having a windows/mac-os like escalation auth pop-up as shown.

**Comment by martinpitt** [comment]
This wasn't very reliable or friendly, so the lock button got removed in PR #9440.
