### ISSUE TITLE
machines: graphical console does not handle switching from text to graphics mode

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#8911]
I installed Fedora 27 Server via a netinst ISO (to test PR #8726) using this URL:
```
https://ftp.halifax.rwth-aachen.de/fedora/linux/releases/27/Server/x86_64/os/
```

When the machine graphical console was open, it was truncated vertically in the installer.

I believe this has to do with not handling the mode switching from text to graphics.

**Comment by KKoukiou** [comment]
@garrett I am not sure if this problem persist or what it was actually? Can you give me a hint?
Screenshot of the builtin vnc how it looks now. ( but it hasn't changed long time now)
![console](https://user-images.githubusercontent.com/14921356/53632976-8b911900-3c16-11e9-8288-ad23e80a270f.png)

**Comment by KKoukiou** [comment]
I don't see this issue on current master.

**Comment by garrett** [comment]
I've tested this with master and Fedora 27 @ https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/27/Server/x86_64/os/ (as to minimize the variables by testing the same exact OS) and the VNC window resized itself properly when textmode height switched and also when it switched from text to graphical mode.

So confirmed fixed here too.
