### ISSUE TITLE
machines ovirt: Should disable the network "plug/unplug"  

### ISSUE THREAD

**Issue by kenzhaoyihui** [cockpit-project/cockpit#8912]
Description of problem:
When created a vm by ovirt, it should be displayed on the cockpit(cockpit-machines-ovirt), If click the network "plug/unplug" and "SEND Non-Maskable" buttons, cockpit will raise the error "error: failed to connect to the hypervisor error: authentication failed: Failed to start SASL negotiation: -1 (SASL(-1): generic failure: All-whitespace username.)"

Version-Release number of selected component (if applicable):
cockpit-machines-ovirt-163-1.el7.centos.noarch.rpm
RHEL-7.5-20180228.1

How reproducible:
100%

Steps to Reproduce:
The same as the description.

Expected results:
Disable these buttons.

Additional info:

**Comment by mareklibra** [comment]
Since the action requires access to libvirt (is not implemented via oVirt API call), it should be disabled on oVirt host until Libvirt connection can be configured - https://github.com/cockpit-project/cockpit/issues/7484

**Comment by mareklibra** [comment]
Within #9226 , as a workaround, libvirt connection URI is set even on an oVirt host.
So removing SEND_NMI from scope of this issue - it's working.

The network (un-)plug needs to be implemented via oVirt API.
