### ISSUE TITLE
machines: start vm checkbox is too large

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#8916]
The "Immediately Start VM" checkbox is a bit too large:

![screenshot-2018-3-28 ovirt machines - sunny 2](https://user-images.githubusercontent.com/10246/38047283-4f2a31b2-32c2-11e8-80a5-0a009a4c3e9e.png)

This is due to it pulling in the classes "form-control dialog-checkbox" that set height and width oddly (for a checkbox) on the #start-vm input.

Solutions (choose one):
- Remove `form-control` and `dialog-checkbox` on the input element's `class` attribute

- If you need the classes: in `pkg/machines/machines.less`, change height and width to unset, like so:
  ```css
  .dialog-checkbox {
    width: unset;
    height: unset;
  }
  ```
  (Unset resets the CSS value to default.)

**Comment by martinpitt** [comment]
I don't see that either class is actually necessary at runtime or for tests, so I just dropped these. Fix sent in PR #9177.
