### ISSUE TITLE
ws: separate cert and key for easy LetsEncrypt integration

### ISSUE THREAD

**Issue by sashaman** [cockpit-project/cockpit#8922]
is this: 
https://github.com/cockpit-project/cockpit/blob/master/containers/kubernetes/README.md#web-certificates
always available or just with kubernetes? 
i am trying and keep failing...
CentOS 7 with cockpit and LetsEncrypt (acme.sh), 
/var/run/secrets/ws-certs.d/tls.crt and /var/run/secrets/ws-certs.d/tls.key available, 
but cockpit-ws still creating selfsigned. 

any hint please?

**Comment by martinpitt** [comment]
These are just available with the cockpit/kubernetes container, not for a "regular" cockpit installation.

Unfortunately the [glib-networking API](https://developer.gnome.org/gio/stable/GTlsCertificate.html) requires putting both into the same file. So at most, cockpit-ws could read the two individual files, cat them together in /run, and point glib-networking towards that. Keeping this open as a possible enhancement.

**Comment by mo-g** [comment]
@martinpitt :+1: from me for that. Seems less painful (if also less elegant) than proxying from nginx-etc.

**Comment by alexhora** [comment]
:ok_hand: :clap: thanks a lot

**Comment by martinpitt** [comment]
As an update, cockpit-tls supports two separate files, and in fact [cockpit_certificate_parse()](https://github.com/cockpit-project/cockpit/blob/master/src/common/cockpitwebcertificate.c#L109) has to go through some effort to pick them apart. But the [/etc/cockpit/ws-certs.d/ format](https://cockpit-project.org/guide/latest/https.html#https-certificates) is API now, so we'd need to think about how to support separate files.

As we only accept *.cert files, it would be compatible to look for a *.key file with the same name if the private key is *not* contained in the .cert file. That should never collide with existing setups.

**Comment by martinpitt** [comment]
Fixed in #13388
