### ISSUE TITLE
Image refresh for openshift-prerelease - fixed in #8947

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#8924]
Image refresh for openshift-prerelease
 * [ ] FAIL: image-refresh openshift-prerelease

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-ct0dw.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8924-20180401-011919/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-dmgl2.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8924-20180401-011919/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-zd4gx.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8924-20180401-035151/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-tn84s.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8924-20180401-035151/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8924-20180401-035151/

**Comment by martinpitt** [comment]
Same issue as in the openshift refresh in #8866 - docker.io/kubevirt/virt-migrator:v0.3.0 image does not exist.
