### ISSUE TITLE
Image refresh for debian-stable (broken, fixed in #8944)

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#8929]
Image refresh for debian-stable
 * [ ] FAIL: image-refresh debian-stable

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-p36c1.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8929-20180402-204343/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8929-20180402-204343/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-6ctnb.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8929-20180404-063939/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8929-20180404-063939/

**Comment by martinpitt** [comment]
This looks like a transient problem, but one retry after two days didn't fix it. So this needs to be looked into:
```
The following packages have unmet dependencies:
 systemd-coredump : Depends: systemd (= 232-25+deb9u2) but 232-25+deb9u3 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by martinpitt** [comment]
Indeed /etc/apt/sources.list is broken - the last line is not terminated with a newline, so the newly added line for security updates both doesn't work and also breaks the stable-updates apt source. systemd 232-25+deb9u3 is still in stable/updates, not yet in stable (until the next point release).
