### ISSUE TITLE
machines: sparse option in create vm

### ISSUE THREAD

**Issue by suomiy** [cockpit-project/cockpit#8931]
We could add `sparse` checkbox to create vm dialog (discussed in #8726).

#### Reasons

 current - non sparse:
 - Disk creation takes too long 
 - takes unnecessary space.

sparse:
 - slower performance 
 - vm can unexpectedly run out of disk space when host machine runs out of space

**Comment by suomiy** [comment]
@martinpitt I put blocked label on this. Hope it is ok?

**Comment by martinpitt** [comment]
@suomiy: I am testing this on Fedora 27. Might this be different on RHEL?

**Comment by suomiy** [comment]
not sure, I tested it on Fedora 26

**Comment by KKoukiou** [comment]
tested in fedora-29 and the VMs disks created are sparse. Thus closing the issue. If you think it is still reproducible please re-open.

**Comment by martinpitt** [comment]
Confirmed. Tested on fedora 29, and /var/lib/libvirt/images/test.qcow2 is a sparse file, and creation is fast. Nice, thanks!
