### ISSUE TITLE
SELinux doesn't allow "systemctl start tangd.socket"

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#8942]
https://bugzilla.redhat.com/show_bug.cgi?id=1563626

**Comment by cockpituous** [comment]
verify/fedora-26
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testClevis (check_storage_luks.TestStorage)
#
Failed to reset failed state of unit tangd-update.service: Unit tangd-update.service is not loaded.
Job for tangd.socket failed.
See "systemctl  status tangd.socket" and "journalctl  -xe" for details.
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-storage-luks", line 155, in testClevis
    m.execute("systemctl start tangd.socket")
  File "/build/cockpit/bots/machine/testvm.py", line 488, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'systemctl start tangd.socket' returned non-zero exit status 1

not ok 124 testClevis (check_storage_luks.TestStorage) # duration: 14s
Journal extracted to TestStorage-testClevis-fedora-26-127.0.0.2-2201-FAIL.log
```
First occurrence: 2018-04-04T11:05:40.516594 | revision 6aebaef879d538973fc11567958839443d7cc939, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8940-20180404-104949-6aebaef8-verify-fedora-26/log.html)
Times recorded: 1
Latest occurrences:

- 2018-04-04T11:05:40.516594 | revision 6aebaef879d538973fc11567958839443d7cc939, [logs](http://fedorapeople.org/groups/cockpit/logs/pull-8940-20180404-104949-6aebaef8-verify-fedora-26/log.html)

**Comment by martinpitt** [comment]
Still fails, we just haven't updated the fedora-26 image in a while (and it's obsolete, too). So *prod*.

**Comment by Gundersanne** [comment]
It seems that this has 2 duplicate issues #9218 and #9219. Fedora 26 isn't supported anymore, and the bug never got fixed there either. Closing this.
