### ISSUE TITLE
Throbber in buttons

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#898]
We have throbbers that show up in buttons, like on the 'Add Server' dialog. It changes the size of the buttons and causes flicker. Should we just disable the button and put the throbber in the empty space to the far left?

**Comment by dperpeet** [comment]
@andreasn I think we have successfully moved away from this. Can you confirm?

**Comment by martinpitt** [comment]
This hasn't been an issue in years, closing.
