### ISSUE TITLE
Add "Disk Usage" tab into Dashboard view

### ISSUE THREAD

**Issue by mclang** [cockpit-project/cockpit#8991]
For my work as server admin, I need to follow how the disk usage of the servers grow across time so that I can spot possible sudden jumps and plan for need of more space.

Currently I have to go through the storage section of all servers, which is cumbersome and time consuming affair. It would be nice to be able see the disk space usage of all servers in the dashboard view like you can now check CPU, Memory, Network and Disk I/O.

Maybe it could be one line graph per server with the different disks in different line types, or just the root filesystems of all servers in one graph like how CPU/Mem/Network/DiskIO is shown now.

**Comment by martinpitt** [comment]
Disk usage generally changes slowly, so for the most part we'd just add a new set of flat lines into the graphs. Also, showing the disk usage on every server line in the dashboard makes it visually much harder to spot actual problems, i. e. when free space is running low. So how about adding a "low disk space" warning to the table if/when that problem actually happens? This avoids showing "normal" state and thus makes problematic states more prominent.

**Comment by mclang** [comment]
Yes, disk usage usually changes slowly, but a graph would show sudden jumps or situation where disks are getting full faster than before.

But otherwise you are tight - generally an alarm would be good and graph boring flat line.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

We are sorry, but we won't be able to address this in any time soon.
If you are interested in helping us with the implementation, please comment here.
