### ISSUE TITLE
machines: Create New VM doesn't work on IE

### ISSUE THREAD

**Issue by qiyuann** [cockpit-project/cockpit#9024]
The Create New VM button doesn't work on IE, the error is:

![screenshot from 2018-04-23 14-37-30](https://user-images.githubusercontent.com/23047456/39110600-595ad050-4704-11e8-9064-42fca1fdf5a0.png)

Versions:
cockpit-machines-165-3.el7.x86_64
cockpit-system-154-3.el7.noarch
cockpit-154-3.el7.x86_64
cockpit-ws-154-3.el7.x86_64
cockpit-bridge-154-3.el7.x86_64
 IE-11.0.9600.18977

**Comment by martinpitt** [comment]
So we need a polyfill for [String.includes()](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/includes)

**Comment by qiyuann** [comment]
Create New VM function works on IE11 now.

Verify Versions:
cockpit-machines-169-1.el7.x86_64
IE-11.0.9600.19002
