### ISSUE TITLE
machines: The value of Used displayed on Disks tab is not accurate

### ISSUE THREAD

**Issue by qiyuann** [cockpit-project/cockpit#9052]
Create a VM using the Create New VM button:

![screenshot from 2018-04-23 16-42-06](https://user-images.githubusercontent.com/23047456/39298980-3fc72e18-497a-11e8-8adc-77e6f37e8086.png)

After the VM is installed, check the Disks tab:

![screenshot from 2018-04-23 17-43-16](https://user-images.githubusercontent.com/23047456/39299025-5be9f472-497a-11e8-854c-b89b1e7a8a73.png)

The disk Capacity is 10GiB, the Used is 8.2GiB. 

Run `df -Th` on guest:

![screenshot from 2018-04-23 17-43-43](https://user-images.githubusercontent.com/23047456/39299155-a4131972-497a-11e8-8b1b-0b5028cfebd4.png)

The totally Used is about 1GiB, much smaller than 8.2GiB.

The Used value displayed on Disks tab is not accurate.

**Versions under test:**
cockpit-machines-165-3.el7.x86_64
cockpit-system-154-3.el7.noarch
cockpit-154-3.el7.x86_64
cockpit-ws-154-3.el7.x86_64
cockpit-bridge-154-3.el7.x86_64

**Comment by mareklibra** [comment]
Recently the value is retrieved from `domstats` from ``block.X.allocation` value.

**Comment by nyoxi** [comment]
@qiyuann the field reflects the amount of storage consumed by the disk image. It does not (and cannot) represent the amount of free space reported by your OS. There may be blocks of zeros that occupy space in the image, but are considered "empty" by your OS. What about swap space?  Etc.

Note that showing free space as seen by your OS is not trivial. It could be to retrived by some tools (e.g. virt-df from libguestfs) but the numbers are hard to interpret without better knowledge of the guest (e.g. what if there is multi-boot and multiple OSes, what should be displayed?).

**Comment by qiyuann** [comment]
@nyoxi , I can understand your point, but my confusion is when create the vm via `virsh create vm.xml`, the Used is 1.2GiB. The detailed steps are:
1. Create disk using `qemu-img create -f qcow2 /var/lib/libvirt/images/test.qcow2 10G`
2. Create vm.xml with:
```
<disk type="file" device="cdrom">
    <source file="/var/lib/libvirt/images/CentOS-7-x86_64-Minimal-1708.iso" />
    <target dev="hda" bus="ide" />
</disk>
<disk type="file" device="disk">
    <driver name="qemu" type="qcow2" />
    <source file="/var/lib/libvirt/images/test.qcow2" />
    <target dev="vda" bus="virtio" />
 </disk>
```
3. Run `virsh create vm.xml`
4. After the guest OS is installed, check the Used:
![screenshot from 2018-04-29 12-05-17](https://user-images.githubusercontent.com/23047456/39403220-44c3e23c-4ba8-11e8-87cc-7b9e69a17674.png)

centos1 is created by `virsh create vm.xml`, vm is created by Create New VM button, they use the same iso.
As you can see, the Used of centos1 is 1.2GiB, while the Used of vm is 8.2GiB. 

Check the qemu-img info:
```

[root@hp-dl385g7-06 images]# qemu-img info test.qcow2
image: test.qcow2
file format: qcow2
virtual size: 10G (10737418240 bytes)
disk size: 1.2G
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: false
[root@hp-dl385g7-06 images]# qemu-img info vm.qcow2 
image: vm.qcow2
file format: qcow2
virtual size: 10G (10737418240 bytes)
disk size: 1.2G
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: true
```
The disk sizes of test.qcow2 and vm.qcow2 are the same, both are 1.2G. It seems the disk size in `qemu-img info` can better represent the autual used space of the guest os.

**Comment by nyoxi** [comment]
I see. Well this is strange. Could you also send the output of `ls -l vm.qcow2` and `du -B1 vm.qcow2`.

**Comment by qiyuann** [comment]
```
[root@hp-dl385pg8-07 images]# ls -lh vm.qcow2 
-rw-------. 1 qemu qemu 11G Apr 29 08:03 vm.qcow2
[root@hp-dl385pg8-07 images]# du -B1 -h vm.qcow2 
1.2G	vm.qcow2
```

**Comment by mareklibra** [comment]
Looks like `virt-df` is better source of data to show allocation from guest POV. Anyway, it's quite expensive operation, so I would not go this way unless the feature is explicitly requested by real use-case.

To fix this issue, we can use `du` if the disk type is `file`.

There's still possibility to remove the column but from user perspective it's good to have similar information, no matter it's not 100% accurate (but close to ...).

What do you think?

**Comment by KKoukiou** [comment]
@qiyuann coming back to this quite late. So as @nyoxi correctly explained we don't and can't in a straightforward  way to get disk usage info from inside the guest.
All disks created by cockpit are thinly allocated and the values of used and capacity are taken from domstats, so the values can be seen directly like this;
```
virsh # domstats my-VM
...
  block.0.allocation=3339354112
  block.0.capacity=5368709120
...
```

Let me know if you see differences between qemu-img and this command data so that we can investigate further.

**Comment by KKoukiou** [comment]
Closing since it's inactive for very long time - see last comment.

**Comment by shodanshok** [comment]
Using `block.<num>.allocation` seems wrong, and this explains some discrepancy I found on newly started machines. 

From virsh man page:
> block.\<num\>.allocation - offset of highest written sector in bytes
> block.\<num\>.physical - physical size of source file in bytes

So it seems cockpit-machines should really use `block.<num>.physical`, otherwise an incorrect number will be returned, as:
```
block.1.allocation=3222331392
block.1.capacity=214748364800
block.1.physical=121545744896
```


Note that from stopped machines, `allocation` and `physical` matches - so the issue is apparent on powered-on vm only.
