### ISSUE TITLE
firewall: look into disabling rather than deleting

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#9053]
This issue came up during the [usability testing](https://github.com/cockpit-project/cockpit/wiki/Usability-test-Firewall) of the firewall.
Half of the participants expressed a need to not delete services, but to only temporarily disable them.
This is especially important if the rules are complex, something ours aren't right now, but do we express custom rules that was created manually from the CLI in our UI?

**Comment by martinpitt** [comment]
I'm not sure what the difference would be between disabling and deleting. firewalld just has the concepts of adding and removing a service.

**Comment by martinpitt** [comment]
This has sat around for a long time, firewalld does not have a concept of "disabled", and we don't want to have cockpit specific state on the machine and hack around that. So I close this now, I don't see us changing this anytime soon.
