### ISSUE TITLE
needs a clearer loading state for pages that takes a long time to load

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#9055]
Something that becomes evident on slower connections (usually a server in a remote location) is that the feedback when loading some pages is not sufficient.

**Comment by KKoukiou** [comment]
@andreasn I think this issue as is doesn't provide much feedback and information for implementation.
I would keep it open only if we have specific pages in mind and an idea of what information we want to show whole loading.

**Comment by marusak** [comment]
Closing as is too generic. We fixed missing loading state on several pages over last year or so. If there is some specific page that is still missing this, please open a separate issue. Thanks!
