### ISSUE TITLE
kvm management

### ISSUE THREAD

**Issue by bitchecker** [cockpit-project/cockpit#9059]
like linked issue, [https://github.com/cockpit-project/cockpit/issues/9058](lxc management issue)
on cockpit-machines, it's possible to start&stop virtual machines and connect to console, there will be possible also have other functions like creations, delete, etc?

**Comment by mareklibra** [comment]
In `cockpit-machines` (libvirt-based plugin), the user is already able to create/delete a VM (initial PRs #7820, #7113) .
Is it what you are looking for?
