### ISSUE TITLE
machines-ovirt: [RFE] Add the way to remove the host from maintenance on cockpit when it was put into local maintenance.

### ISSUE THREAD

**Issue by kenzhaoyihui** [cockpit-project/cockpit#9060]
Description of problem:
There is no way to remove the host from maintenance on cockpit when it was put into local maintenance. So, suggest to add this function. Because if putting the host to maintenance, just only to activate the host from the ovirt-engine.

Version-Release number of selected component (if applicable):
RHEL-7.5-20180322.0
cockpit-machines-ovirt-165-3.el7.noarch

How reproducible:
100%

Steps to Reproduce:
The same as the description.

Expected results:
Add the way to remove the host from maintenance on cockpit when it was put into local maintenance.

Additional info:

**Comment by mareklibra** [comment]
Should be single API call.
The corresponding action should be rendered only if engine oVirt connection is established (means token and FQDN is available) and status of host reported by oVirt is `maintenance`.
