### ISSUE TITLE
firewall: The message "No open ports" is misleading

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#9065]
If I turn off the Firewall, I get the message "No open ports"
But on a standard Fedora install, if firewalld is off, all ports are open.
![screenshot from 2018-04-27 15-55-59](https://user-images.githubusercontent.com/209895/39366254-aca5f532-4a33-11e8-9235-632347a9d3be.png)

Not sure what the best fix is. Saying all ports are open could also be a lie, if I have another firewall installed.  @mvollmer suggested "Firewall is off"

**Comment by garrett** [comment]
What about simply hiding everything below the firewall switch? 

(None of it makes sense if the firewall is happens to be not managed by firewalld.)

**Comment by KKoukiou** [comment]
> What about simply hiding everything below the firewall switch?
> 
> (None of it makes sense if the firewall is happens to be not managed by firewalld.)

I think @garrett 's point makes sense. I 'll post a pr, let be know if you have any objections here.
