### ISSUE TITLE
Image refresh for ubuntu-stable - fixed in #9130

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#9094]
Image refresh for ubuntu-stable
 * [ ] FAIL: image-refresh ubuntu-stable

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-npcrk.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9094-20180503-014242/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9094-20180503-014242/

**Comment by martinpitt** [comment]
This is the first ubuntu-stable that is 18.04. It failed with
```
ERROR! docker does not use aufs
+ echo 'ERROR! docker does not use aufs'
```
but there's likely more issues. I'll have a look.

**Comment by martinpitt** [comment]
ATM I can't build any images locally due to https://bugzilla.redhat.com/show_bug.cgi?id=1575640 . Ideas how to fix/work around this appreciated!
