### ISSUE TITLE
Unable to create properly aligned swap partition on LVM2 with Cockpit

### ISSUE THREAD

**Issue by monreal** [cockpit-project/cockpit#9119]
I set up PV, VG and LV on a new SSD using Cockpit and then formatted the LV as swap manually because I did not find a way to do it in Cockpit. Problem is, I cannot get it to me alligned correctly:

```mkswap: warning: /dev/vol/swap is misaligned```

**Comment by mvollmer** [comment]
(This is "just" a warning, isn't it?)

Cockpit doesn't expose any LVM2 options or parameters to influence LV alignment.  However, the default extent size is 4MiB, so I would expect all LVs to be aligned to 4MiB.  Isn't that enough for swap?

So, right now I think that Cockpit doesn't need to do anything extra to support mkswap.  Please reopen this issue if you disagree, and please also provide the exact steps that you did.

**Comment by monreal** [comment]
For reference: I tried for days and experimented with manual alignment but never got the partitions to be aligned correctly (according to CLI tools).

**Comment by mvollmer** [comment]
>  I tried for days and experimented with manual alignment but never got the partitions to be aligned correctly (according to CLI tools).

Could you show the exact command line invocations that you did in your experiments?

It all comes down to having a non-zero value in /sys/block/XXX/align_offset.  I have haven't found any real documentation about what this value means and how to get it to be non-zero.  I will ask around.

**Comment by mvollmer** [comment]
> I haven't found any real documentation about what this value means and how to get it to be non-zero. I will ask around.

Okay, I have been pointed at this: http://people.redhat.com/msnitzer/docs/io-limits.txt

it contains this:
```
LVM provides userspace tools that are used to manage the kernel's DM
devices.  LVM will shift the start of the data area, that a given DM
device will use, to account for a non-zero 'alignment_offset' associated
with any device LVM manages.  This means LVM logical volumes will be
properly aligned (alignment_offset=0).  LVM will adjust for any
'alignment_offset' by default but this may be disabled through
lvm.conf's 'data_alignment_offset_detection'.  Disabling this is not
recommended.
```

So your /dev/vol/swap should have a zero align_offset.

Can you show the output of `lsblk --topology`?

**Comment by monreal** [comment]
$ lsblk --topology
NAME        ALIGNMENT MIN-IO OPT-IO PHY-SEC LOG-SEC ROTA SCHED RQ-SIZE  RA WSAME
sda                 0    512      0     512     512    0 cfq       128 128    0B
├─sda1              0    512      0     512     512    0 cfq       128 128    0B
├─sda2              0    512      0     512     512    0 cfq       128 128    0B
└─sda3              0    512      0     512     512    0 cfq       128 128    0B
  ├─fedora_freya-root
  │                 0    512      0     512     512    0           128 128    0B
  └─fedora_freya-swap
                    0    512      0     512     512    0           128 128    0B
