### ISSUE TITLE
Give hints at login about how to start/access cockpit

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#9129]
We'd like to provide an additional system integration point: when the login prompt is displayed at the hardware console, or when the user logs in to an interactive session (eg. over ssh) then we will display a message.  If cockpit is not started, we will instruct how to start it.  If it's already running, we will print the URL to go to.

That means displaying something as part of /etc/issue and /etc/motd.

For the /etc/issue most part, this will be driven by the recently-added /etc/issue.d support (util-linux v2.32, rc2) and a symlink to a file that cockpit is already writing into /run/cockpit/issue.

For the /etc/motd part, I've written a patch for /etc/motd.d support, and we seem to have support for the feature from the PAM maintainers: https://github.com/linux-pam/linux-pam/issues/47

Since pam_motd doesn't support the \4 and \6 style escapes that getty does, we'll need to add some more code to cockpit to make sure this is working properly.  We might as well update the issue message at this point too, since cockpit has a better idea of where it is bound, anyway.

**Comment by mvollmer** [comment]
Note that Cockpit itself displays /etc/motd... We would need to add support for /etc/motd.d as well, I guess, and probably filter out our own advertisement.  But we could advertise SSH instead! :-)

**Comment by martinpitt** [comment]
Excellent point about not showing our own motd message in Cockpit, thanks @mvollmer.

Why would we want/need *both* issue and motd? motd is shown on every PAM session, thus also on gettys, so this would be redundant (and wrong, as it would show up twice)?

**Comment by martinpitt** [comment]
We discussed how to display the address on IRC the other day. With /etc/issue we currently use `\4` and `\6`, but this is highly unfriendly. On getty this is usually not copy&pasteable, and typing IP addresses is really not human friendly; let alone an IPv6 address! There might also be multiple addresses.

We discussed various options like picking the address from the interface that has the default route, but all of these are just heuristics. We eventually agreed to just show https://`hostname`:9090 - like an IP address picked from `hostname -I`, this might also not work from a remote computer, but a name is much easier for an administrator to remember/type, and also makes it much more obvious what this URL really *means* - i. e. translating the name to an "outside accessible" one can be expected from an admin. The main point of this notification is to point out that the web console exists and how to generally access it.

**Comment by martinpitt** [comment]
@stefwalter: All of these are just heuristics. An IP address might not work either (tunelling, proxying, etc.), and we don't know *which* address of `hostname -I` is actually the one that applies to the remote place the user is currently on. So in most cases this will only work from connecting locally anyway. Also, if the local host name is not resolvable, tools like sudo also croak loudly. So I'm in favor of assuming a normal system configuration and human-readable names to fit its purpose.

We won't ever be able to give a perfect and succinct URL in this motd snippet anyway. As the best thing that we can do is a hint, let's use the one that humans can understand most, not a hodgepodge of random numbers.

**Comment by stefwalter** [comment]
> All of these are just heuristics. An IP address might not work either (tunelling, proxying, etc.), and we don't know which address of hostname -I is actually the one that applies to the remote place the user is currently on. 

There are several heuristics here we can use to make this work for 95% of the cases:

 * The ```SSH_CLIENT``` environment variable.
 * Most machines only have one ```IFF_UP``` interface initially. See ```output_iface_ip()``` in ```agetty.c```
 * Choose the interface with the default route. This would require modifications to ```output_iface_ip()``` in ```agetty.c```

I don't think this can be perfect. But needs to be better than: "Sorry. Go figure out your DNS situation before you can use Cockpit."

> So in most cases this will only work from connecting locally anyway. Also, if the local host name is not resolvable, tools like sudo also croak loudly. 

Strange. It doesn't on my system. 

> So I'm in favor of assuming a normal system configuration and human-readable names to fit its purpose.
> We won't ever be able to give a perfect and succinct URL in this motd snippet anyway. As the best thing that we can do is a hint, let's use the one that humans can understand most, not a hodgepodge of random numbers.

The ```/etc/motd``` stuff can be a clickable link in a terminal. Why not print both?

**Comment by martinpitt** [comment]
> "Go figure out your DNS situation before you can use Cockpit."

Locally this is okay. nss-myhostname is being used on at least Fedora and RHEL now, so it really takes some effort to *not* make the local host name resolvable -- that's also the reason for your "Strange. It doesn't on my system" ☺. You can't uninstall systemd-libs, but of course you can remove it from /etc/nsswitch.conf - but there are lots of other ways to break stuff on your machine.

Of course accessing from remote locations is a different situation. Within the same LAN, host names usually work, and outside IP addresses often don't either. `$SSH_CLIENT` is a good hint indeed, thanks for pointing that out! So if that exists, we could use it (although it again shows an IPv6 address if you connect via IPv6, so it's totally unmemorable).

> Why not print both?

I'm ok with that, as long as it's just one address which is usually correct (like the heuristics mentioned above of taking the IP that matches the default route). I'm mostly arguing for *at least* showing the host name, as that's a much better mental model to get into people's heads. Showing that and an IPv4 address should still fit on one line, so that's fine for me.

So something like

    Web Console: https://myhostname:9090 or https://192.168.2.4:9090

where the IP address is `$SSH_CLIENT`, falling back to IP address of default route interface, or not shown at all if there is no default route. @stefwalter , @allisonkarlitskaya , @andreasn, WDYT?

**Comment by stefwalter** [comment]
Keep in mind ```$SSH_CLIENT``` would require a lookup in the routing tables before you can find the local interface in use. But that's the sorta effort we could go to to make this usable.

**Comment by allisonkarlitskaya** [comment]
We can't do anything based on (for example) $SSH_CLIENT because the motd.d support doesn't allow running arbitrary code.  For now, based on Martin's earlier advice, I'm just going to do hostname.  We can improve this in a later iteration.

**Comment by martinpitt** [comment]
How is that related to motd at all? The file is created by cockpit.socket's `ExecStartPost=` command, which *can* run arbitrary code. We can't just use static files anyway, as we can't put the actual hostname in there with our current simple approach either.

**Comment by allisonkarlitskaya** [comment]
I rather like this one-liner, fwiw:

    ip -o route get 255 | sed 's/.*src \([^ ]*\) .*/\1/'

**Comment by allisonkarlitskaya** [comment]
@martinpitt The motd sniplet is indeed created at the `ExecStartPost=` point, where we run a script.  We don't have `SSH_CLIENT` set at this point, though... Once the user is logging in to SSH, we already have (effectively) static content there.

**Comment by garkin** [comment]
Could you please add to the MOTD a way to how do i disable this "very useful" function.  🤢
You could even improve it's annoyance by making it like 15 lines and by adding some TUI tables and formatting.
Thank you.
