### ISSUE TITLE
Show a hint for username when joined to a domain

### ISSUE THREAD

**Issue by puiterwijk** [cockpit-project/cockpit#916]
Currently, it's not clear you'd need to use username@domain when you joined a domain and it's not set as the default domain.

**Comment by martinpitt** [comment]
While realmd [got fixed](https://bugzilla.redhat.com/show_bug.cgi?id=1575538) to not use fully qualified domains by default any more (and thus became consistent with freeipa-installer), it's still an option, and it should be displayed. This should be done as part of https://projects.engineering.redhat.com/browse/COCKPIT-325

**Comment by martinpitt** [comment]
This is fixed in 187, it shows more information about the domain. See https://cockpit-project.org/blog/cockpit-187.html
