### ISSUE TITLE
network manager not showing nics

### ISSUE THREAD

**Issue by warllo54** [cockpit-project/cockpit#9192]
My Network info isn't showing up under the networking module. Running Ubuntu 16.04.4 LTS on a proxmox vm.

Here is the log info from the network module in cockpit.

May 16, 2018
 15:03 <info> [1526501017.1310] manager: WWAN hardware radio set enabled NetworkManager
 15:03 <info> [1526501017.1309] manager: WiFi hardware radio set enabled NetworkManager
 15:03 <warn> [1526501007.5737] failed to enumerate oFono devices: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.ofono was not provided by any .service files NetworkManager
 15:03 <info> [1526501007.5731] ofono is now available NetworkManager
 15:03 <info> [1526501007.5711] urfkill disappeared from the bus NetworkManager
 15:03 <info> [1526501007.5647] manager: NetworkManager state is now CONNECTED_GLOBAL NetworkManager
 15:03 <info> [1526501007.5646] manager: startup complete NetworkManager
 15:03 <info> [1526501007.5622] manager: (lo): new Generic device (/org/freedesktop/NetworkManager/Devices/1) NetworkManager
 15:03 <info> [1526501007.5615] device (lo): link connected NetworkManager
 15:03 nm_device_get_device_type: assertion 'NM_IS_DEVICE (self)' failed NetworkManager

Any suggestions?

**Comment by kaysond** [comment]
@warllo54 any luck figuring this out?. where did you find the module log?

**Comment by KKoukiou** [comment]
This doesn't look like cockpit-network bug. More like this one https://bugs.launchpad.net/network-manager/+bug/1568560/

**Comment by warllo54** [comment]
@kaysond  I rebuilt the server and reinstalled cockpit and everything worked fine. I'm thinking I had bad install media.
