### ISSUE TITLE
Presence of subscription-manager on CentOS 7 disables packagekit updates

### ISSUE THREAD

**Issue by kai4785** [cockpit-project/cockpit#9193]
The cockpit-system package now "Requires: subscription-manager >= 1.13". This has two undesirable side-effects on CentOS systems.
1) cockpit-packagekit now disables updates because you are "unsubscribed", even though it shows you available updates.
1) yum loads the subscription-manager plugins by default, and yells at you every time you run yum.
```
# yum list cockpit
Loaded plugins: fastestmirror, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Determining fastest mirrors
```

These issues can be worked around in multiple ways. Here's two.
```
# rpm -e --nodeps subscription-manager*
```
Or
```
# sed -i 's/enabled=0/enabled=1/' /etc/yum/pluginconf.d/subscription-manager.conf /etc/yum/pluginconf.d/search-disabled-repos.conf /etc/yum/pluginconf.d/product-id.conf
# mv /etc/dbus-1/system.d/com.redhat.SubscriptionManager.conf{,.back}
```

I think reasonable solutions include:
1) separating out a cockpit-rh-subscription
2) a work around that doesn't require such a heavy hand. (Can I disable a dbus interface with policykit?)

This issue is raised in a comment in issue #9156 , but I don't think the two issues related in anyway except they were released with CentOS 7.5.

**Comment by martinpitt** [comment]
This is https://bugzilla.redhat.com/show_bug.cgi?id=1505955 . But from the upstream side what we can do is to stop requiring subscription-manager on non-RHEL systems.

**Comment by shawly** [comment]
I'm on CentOS Linux release 7.6.1810 (Core) but this issue still persists, I can't update packages via cockpit because it tells me that I need a subscription.

**Comment by StewAlexanderACC** [comment]
Issue still exists, and work around doesn't work

``` Centos Linux release 7.7.1908```
```cockpit-system-195.101.el7.centos.0.1.noarch```
