### ISSUE TITLE
maintaining compatability with sysvinit for Debian

### ISSUE THREAD

**Issue by zeigerpuppy** [cockpit-project/cockpit#9208]
Installing cockpit on Debian (without systemd) is possible with the current Debian package (thanks!).  It would be great to retain compatability with systems that choose not to use systemd, as this is still a permissible config with Debian.

I have installed and generally it works fine with a few tweaks, which would be nice to support officially.  Perhaps the installer could detect if systemd is not available and apply the following:

1. no sysvinit startup script (I have included one below)
2. certificate not created on install, fixed with:
    ```
    /usr/lib/cockpit/remotectl certificate --ensure --user=root --group=cockpit-ws 
    ```
3. checking for running daemons seems to rely on systemd, for instance if `libvirt` is running, this is not detected... looking at a fix
4. log file scanning seems broken without systemd

## SysVinit file:

```
#!/bin/sh
### BEGIN INIT INFO
# Provides:          cockpit
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: cockpit management webserver
# Description:       cockpit management webserver
### END INIT INFO

dir="/usr/lib/cockpit/"
cmd="/usr/lib/cockpit/cockpit-ws"
user="cockpit-ws"

name=`basename $0`
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"
        cd "$dir"
        if [ -z "$user" ]; then
            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
        else
            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
        fi
        echo $! > "$pid_file"
        if ! is_running; then
            echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in 1 2 3 4 5 6 7 8 9 10
        # for i in `seq 10`
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0

```

**Comment by martinpitt** [comment]
3 (systemd D-Bus API) and 4 (systemd journal) are built into cockpit pretty deeply. There won't ever be a parallel non-systemd implementation of these, as it's just too much effort for little gain, and nobody in the team tests or is interested in this.

1 and 2 are easier to handle indeed, and you can just keep a local script for the time being. Note that you can use /lib/init/init-d-script to greatly simplify this.

**Comment by larskarlitski** [comment]
As Martin said back in May, cockpit is deeply integrated with systemd's D-Bus APIs. There don't seem to be enough people that care about running cockpit on non-systemd systems to develop alternatives.
