### ISSUE TITLE
Cannot login to cockpit after deploying as pod in Azure AKS 1.8.7

### ISSUE THREAD

**Issue by razidare** [cockpit-project/cockpit#9209]
Hello,

I am trying to deploy cockpit as per  https://cockpit-project.org/guide/133/feature-kubernetes.html and I can see that the pod was succesfully deployed.

Also tried to get the cluster basic auth credentials in order to login to cockpit, so used `kubectl config view` but found no username and password, unfortunately.

Decided to create a set, so used 
kubectl config set-credentials cluster-admin --username=admin --password=xxxxxx
and now when using `kubectl config view`  i can see that the username and password is there.

Tried them but login still fails.
Proxied to the k8s api server and started using `curl -k -u admin:admin https://localhost:8081/api/` with all of the combinations of usernames and passwords I could think of, but to no avail.

Given that this is an Azure AKS, I cannot ssh into the control plane, or can I?
Any ideas?

**Comment by razidare** [comment]
Also, is there any way to check for sure to know if the cluster is basic authentication enabled?

**Comment by rajeshevuri** [comment]
@razidare  Actually I was having a same problem in Azure. Do you have any solution?

**Comment by razidare** [comment]
> @razidare Actually I was having a same problem in Azure. Do you have any solution?

Hi rajesh, I actually gave up on using Cockpit, as I couldn't get it working, sorry about that.

**Comment by rajeshevuri** [comment]
> > @razidare Actually I was having a same problem in Azure. Do you have any solution?
> 
> Hi rajesh, I actually gave up on using Cockpit, as I couldn't get it working, sorry about that.

Hi @razidare , Thanks for letting me know.
