### ISSUE TITLE
Need easier navigation between user accounts

### ISSUE THREAD

**Issue by pdonlon** [cockpit-project/cockpit#924]
Right now our Accounts page looks like this:

![](http://i.imgur.com/YQnSbI3.png)

After selecting an account the user is brought to this page:

![](http://i.imgur.com/8hCT1FX.png)

Right now to go back to looking at all the accounts the user needs to hit the accounts tab in the navigation bar:

![](http://i.imgur.com/xkRO9yI.png)

This makes it hard to quickly navigate through users to change/look at settings about each user. It would be a lot easier if the overview of all the accounts were on the same page as each specific account. 

I was thinking this could be accomplished by just putting the overview of all accounts to the left of the specific user's page since there is so much unused space:

![](http://i.imgur.com/uXfbZyH.png)

**Comment by andreasn** [comment]
The design changed a bit since then, but it should be fairly painless to navigate using the breadcrumb bar now. I think it's fine as it's in master now, so closing.
