### ISSUE TITLE
packagekit: row resizes when opened

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#9242]
The row jumps around as soon as I open it, making the experience quite jarring.
It seems it's because some of the packages end up on a second row as soon as I open the pane.

![cp-updates-row-resize](https://user-images.githubusercontent.com/209895/40553537-42e8a164-6043-11e8-9e7f-b424caf29516.gif)

**Comment by andreasn** [comment]
```
.listing-ct-item th {
white-space: nowrap;
}

```
seems to help some, but messes up by adding horizontal scrolling to the browser window :/

**Comment by garrett** [comment]
I think I fixed this in the big list overhaul (commit 0f1ceda71370d02e5b8b0f4f68ed6935bb3837d3) — please see if you can still reproduce this issue.

**Comment by KKoukiou** [comment]
Not reproducible any more.
