### ISSUE TITLE
machines: Add Disk: inform the user if the disk is attached to any other VM

### ISSUE THREAD

**Issue by mareklibra** [cockpit-project/cockpit#9246]
In `pkg/machines`, within the `Add Disk` feature, the user can select existing disk to be attached to a virtual machine.

The selected disk can be already attached to another virtual machine on the host.
It is a valid scenario to have single disk attached to multiple virtual machines but might lead to data loss if done unintentionally. 

The user should be informed, that particular disk is already attached to another VM.

Existing:
So far there's check if the disk is already attached to the same VM. Only unique disks can be added to a single VM. This feature should remain.

Limitations:
- detection if a disk is attached to another VM will be done via comparing values from dumpxml. So only disk files of the same name/path will be detected. For symlinks, the `readlink -f` can be used to improve.
- if the backing disk file is attached to a VM running on different host (i.e. using NFS) or in different user's Libvirt session, it will not be detected.

This is follow-up for https://github.com/cockpit-project/cockpit/pull/9166 or #9081, resp.

**Comment by mareklibra** [comment]
@garrett , considering #9166 dialog, how to denote that particular disk is already attached to another VM?
It would be even nice to show which one**s**.

**Comment by martinpitt** [comment]
I agree, trying to add the same disk to multiple domains should at least raise a big warning.

@KKoukiou , do we have an API to map a disk to its using domains? Or could it iterate over all domains to see if it's already being used?

**Comment by KKoukiou** [comment]
There is not an libvirt API for checking if a disk is used.
But for disks that are created through cockpit UI, and have the pool,volume attributes in the XML like this:
``` xml
  <disk type='volume' device='disk'>
    <driver name='qemu' type='raw'/>
    <source pool='blk-pool0' volume='blk-pool0-vol0'/>
    <target dev='hdk' bus='ide'/>
  </disk>
```
I am implementing the functionality to find if a volume is used here by a domain in this commit.
https://github.com/cockpit-project/cockpit/pull/10783/commits/de5dea300c83a4fea3ce0ff0458aec69e38c6136
I 'll have to repost on that PR, but it's doable.

**Comment by KKoukiou** [comment]
Already implemented;
![Screen Shot 2019-10-18 at 13 54 36](https://user-images.githubusercontent.com/14921356/67092181-dfa13b80-f1ae-11e9-96cf-cb39ab031ab5.png)
