### ISSUE TITLE
RFE: Consider support for tracepoint / probe hit counts

### ISSUE THREAD

**Issue by myllynen** [cockpit-project/cockpit#9247]
Linux kernel provides hundreds of tracepoints in various categories/subsystems that might give insight on what is happening on a system (for example, file system/network/power/syscall/thermal events). USDT/dtrace probes are built-in in some applications/libraries (e.g., OpenJDK JVM) to allow monitoring their internals (in case of JVM, starting a new thread, beginning of GC, etc). uprobes is a mechanism to trace user-space functions calls (e.g., calls to malloc).

https://jvns.ca/blog/2017/07/05/linux-tracing-systems/ provides a nice introduction in this area.

So far there have been various disjoint command line utilities from different projects to access this information (like perf(1) and several tools from the BCC project - see https://github.com/iovisor/bcc).

PCP (already used by Cockpit when installed) is introducing support for collecting metrics from tracepoint / uprobe / USDT/dtrace hit counts in PCP 4.1.0 (to be released in mid June) with a simple text file based configuration. (For configuration file examples, see the recent PCP commit https://github.com/performancecopilot/pcp/commit/889597b0ca48aacef17bc8bdd8b98a1c436a32bd).

It could be considered here whether this kind of information would be helpful for some Cockpit users and if deemed so, adding an interface to enable some of these metrics and providing visualization of the results would make this information available in an easily accessible and consumable manner.

In case deemed being out of scope, please feel free to close this ticket, then we at least have this aspect documented here.

Thanks.

**Comment by garrett** [comment]
There are two paths that can be taken with this feature in mind:

1. Figure out a use case that solves some issue in an elegant manner and get it integrated into Cockpit directly.
2. Create an add-on to Cockpit that provides this (and possibly some other advanced monitoring features). See [**Starter Kit** for details…](https://cockpit-project.org/blog/cockpit-starter-kit.html)

They're not mutually exclusive, either. (Both can be done. Example: If we do provide a feature in Cockpit that uses this functionality, it might be a simple version. Then a more advanced version could be provided as an optional add-on.)

Right now, I don't understand what problem this addresses, for the audience<sup>*</sup> of Cockpit. 

<sup>*</sup> _We have a working definition of Cockpit's audience at: https://github.com/cockpit-project/cockpit-project.github.io/issues/143 (it's a discussion & not finalized at the moment, but the list at the top is probably pretty close to what we're going with for a formalized version)._

I'll read over the links you included above and think about it, but meanwhile please feel free to provide a scenario why someone in our audience would want to use tracepoints / probe hit counts within Cockpit. You're _much_ more familiar with what usefulness this feature can provide people than I am. :wink: Thanks!

**Comment by myllynen** [comment]
Thanks for pointing the doc about target audience for Cockpit, we exchanged few words on IRC whether this would be in scope but I hadn't seen the doc before.

Given the above, I think if this would be considered then add-on might be a better starting point as except in a few clearer cases that come to mind at this stage (see below) this might often require quite deep understanding of the system and the relevance of probes/tracepoints available in there. With user-space probes most people know or can guess what c:malloc or libjvm.so:thread__start hit counts indicate but even then there's no generic rule to tell whether the results are expected or not as they are completely dependant on the workload and application profiles running on a system.

The somewhat more indicative cases might be hit counts for these kernel tracepoints:

* ras: Reliabillity and Serviceability tracepoints - these include ras:{aer,arm,mc}_event and, perhaps most notably, ras:memory_failure_event (and ras:non_standard_event). So you would expect to have memory failure events at zero, if you have unexplained issues and see memory failure events that might be an indication of the root cause.

* sock: socket related tracepoints - sock:sock_exceed_buf_limit and sock:sock_rcvqueue_full might indicate why/when packets are being dropped (sock:inet_sock_set_state is being used by `tcplife` to track TCP usage per pid)

* thermal: and power: tracepoints - power management is becoming more and more important topic, these tracepoints could indicate when processor clocks are throttled and thus decrease performance, or just seeing how often the CPU enters the idle state might be interesting information for some.

Hopefully this explains a bit more what could be possible on this front. Thanks.

**Comment by martinpitt** [comment]
This is a rather large project that our team won't be doing within cockpit itself. It's a totally fine idea as a standalone project though, they are nicely integrated now on the Applications page for easily discovering them.
