### ISSUE TITLE
Apt repository not up to date

### ISSUE THREAD

**Issue by ValkyrieUK** [cockpit-project/cockpit#9266]
Hi, just stumbled across this project.

I'm running Ubuntu 18.0.4
```
➜  ~ uname -a

Linux server 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

It seems the apt repo is stuck on 164-1

```
➜  ~ sudo apt-get upgrade cockpit
Reading package lists... Done
Building dependency tree
Reading state information... Done
cockpit is already the newest version (164-1).
Calculating upgrade... Done
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

**Comment by martinpitt** [comment]
Right, I'm aware of that. We couldn't do backports while 18.04 was being released and cosmic being opened. Last week, 168-1 landed again in cosmic, so the road is free for backporting again. Tomorrow's 169 release will land in bionic/xenial-backports again.

**Comment by martinpitt** [comment]
I just backported Cockpit 169 to bionic and xenial: https://launchpad.net/ubuntu/+source/cockpit

Will still take an hour or two to build and publish.

**Comment by danielvitek** [comment]
still version 164, but current is 184

**Comment by martinpitt** [comment]
No, both 18.04 and 18.10 backports have version 183 now.
```
❱❱❱ curl -s http://archive.ubuntu.com/ubuntu/dists/bionic-backports/universe/binary-amd64/Packages.xz | xzgrep  -A2 '^Package: cockpit$'
Package: cockpit
Architecture: all
Version: 183-1~ubuntu18.04.1
```

**Comment by danielvitek** [comment]
<img width="720" alt="screenshot 2018-12-11 20 32 47" src="https://user-images.githubusercontent.com/11147846/49826414-323beb00-fd87-11e8-9b4a-2c6a84ed1671.png">

Then, any idea what is wrong?

**Comment by martinpitt** [comment]
@danielvitek : Please copy&paste the output of `apt-cache policy cockpit`.

**Comment by danielvitek** [comment]
@martinpitt got it, the correct command for install was
`apt-get -t bionic-backports install cockpit`

thank you :)
