### ISSUE TITLE
software updates: layout issues in mobile view

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#9273]
![screenshot from 2018-05-30 14-09-56](https://user-images.githubusercontent.com/209895/40719222-3389ec5e-6413-11e8-9e8b-e6564663250a.png)

**Comment by andreasn** [comment]
* stacking items on top of each other makes each row very tall
 * it draws lines between the rows
 * might make sense to hide the changelog details at this low resolution in the header, since it's the least critical piece of information

**Comment by andreasn** [comment]
@garrett did this regress? What was the original layout plan?

**Comment by andreasn** [comment]
Mockup of a better layout:
![screen shot 2018-05-31 at 11 44 27](https://user-images.githubusercontent.com/209895/40783137-d4efeaca-64e1-11e8-8c0c-bcd2c4d7e377.png)

**Comment by garrett** [comment]
This is completely a regression.

I'll look into a fix. Thanks for the mockup!

**Comment by garrett** [comment]
Fixed in #9292. 

Related: While making changes to the list, I also adjusted the refresh bar and list leading. These changes are (currently) pending in #9294.
