### ISSUE TITLE
storage tab missing 

### ISSUE THREAD

**Issue by 851d229** [cockpit-project/cockpit#9279]
Hi,
I've just installed Cockpit on a Centos 7, and the Storage Tab is missing

![capture](https://user-images.githubusercontent.com/39810076/40805032-02c3632e-64eb-11e8-9d6e-1d5a02665dcd.JPG)

Is there a fix for that ?

**Comment by martinpitt** [comment]
You should be able to install cockpit-storaged?

**Comment by 851d229** [comment]
great !  it's working!

Perhaps this plugin was specified in the installation guide?  I didn't see it. If not, could be great to specify the available plugins which could be installed.

thank you.

**Comment by martinpitt** [comment]
Nice, thanks for reporting back.
