### ISSUE TITLE
No root permissions on remote ssh machine with key and different password

### ISSUE THREAD

**Issue by BlackHoleFox** [cockpit-project/cockpit#9281]
I have several separate machines added in my dashboard but whenever I try do to anything on them, change the host name or delete a user, I always get a "Permission Denied" error. Ive connected to them via SSH, adding the keys manually with the interface. Is something setup wrong?

**Comment by martinpitt** [comment]
This sounds like a current design limitation. If you log into a machine with password, then Cockpit remembers that password and also uses it for `sudo` (or `pkexec`) to run commands as root. But if you log in with an ssh key, and the remote user uses a different password than the local one that you used to log into Cockpit, then Cockpit does not have a password for running `sudo` on the remote machine. We also don't currently have a place to set that.

So the workarounds are: Use user/password to log into the remote machine, or log in as root, or configure sudo on the remote machine to not require a password, or use the same password on both machines.

**Comment by BlackHoleFox** [comment]
Thanks for the timely response. Are there any plans to add this option to cockpits dashboard config, even if a manaul edit is required? I can look into probably the no password for sudo option in the meantime.

**Comment by martinpitt** [comment]
We wouldn't want to store cleartext passwords in /etc/cockpit/machines.d/, so it wouldn't work to just do this once. What would be more realistic is to ask for the sudo password when you connect to the remote machine. This is still not trivial, and we don't have short-term plans/capacity for this, I'm afraid.

**Comment by BlackHoleFox** [comment]
Ah that does seem like a better idea. In regards to not having any plans, its fine. Ive switched to no password sudo access on some machines for testing. I do hope this eventually gets into the workflow. 

In regards to storage, would it work to store hashes of the passwords using your cockpit user password as the key to them? Then they wouldn't be plaintext.

**Comment by martinpitt** [comment]
There is no "cockpit user password", just the regular /etc/shadow one. Cockpit really shouldn't reinvent password stores, that's just a can of worms. It's bad enough to have to keep it in memory, but at least that's fungible over time.

**Comment by martinpitt** [comment]
This is now tracked in https://projects.engineering.redhat.com/browse/COCKPIT-520 (internal, sorry)

**Comment by martinpitt** [comment]
This was finally fixed with https://cockpit-project.org/blog/cockpit-219.html
