### ISSUE TITLE
Update Tab and other features

### ISSUE THREAD

**Issue by 851d229** [cockpit-project/cockpit#9287]
Hi everyone,

I want to administer all my CentOS 7 with Cockpit.  I would like to know if Cockpit have the ability to administer Updates ?  Is there a cockpit plugin which allows the administration of Centos System Updates?  I have seen that's possible to do this with Redhat systems and it's only for registered systems (redhat licence agreement).

thank you !

**Comment by martinpitt** [comment]
In principle yes, it's the cockpit-packagekit package. Unfortunately this triggers https://bugzilla.redhat.com/show_bug.cgi?id=1505955 which is a bit of a nuisance to work around (basically, you have to disable the rhsmd D-Bus service).

**Comment by 851d229** [comment]
If I understand well, if I disable the D-Bus service, my centos 7 will be able to get updates?  How can we disable the D-Bus service?  is there a know command line for this?

**Comment by martinpitt** [comment]
I can't check it right now, but there should be an /etc/dbus-1/system.d/*rhsmd*. If you delete that file, rhsmd should fail to start up and the update package should start working.

**Comment by 851d229** [comment]
here is my listing (please see attached image):
![capture](https://user-images.githubusercontent.com/39810076/40849875-26aed128-6591-11e8-927e-e8cf37c67d58.JPG)

I don't see any rsdmd but only RHSM1 ...

**Comment by martinpitt** [comment]
Yes, that looks right. I suggest renaming these to `'*.disabled`, or moving them to someplace else.

**Comment by 851d229** [comment]
this didn't helps unfortunetely.  I move the 2 files in another folder.  I even reboot the server but same thing.  The system keeps asking me to register to Redhat.

![capture1](https://user-images.githubusercontent.com/39810076/40850913-defd1206-6593-11e8-92b8-27684ff336e2.JPG)

![capture2](https://user-images.githubusercontent.com/39810076/40850918-e2a13e82-6593-11e8-9725-931b0e9b220b.JPG)

**Comment by 851d229** [comment]
I have read many posts on the internet about the software update tab for Centos, it seems that's doesn't work much with Centos ...  perhaps it will be a good idea to make a fix on this possibility?  To make Cockpit Software Update 100% usable by centos servers?
thank you for your support Martin !

**Comment by 851d229** [comment]
ok thank you !
