### ISSUE TITLE
please add node names to kube nodes utilisation graph boxes

### ISSUE THREAD

**Issue by ikke-t** [cockpit-project/cockpit#9291]
Hi,

I found the kubernetes cluster status graph useful while I was debugging new cluster. By one view I can see the "heatmap" of the cluster. Some of the nodes were red on memory consumption.

However, it would be nice to immediately see which node is in question. Can you please add node names to coloured squares. See sccreenshot of this page: https://localhost:9090/kubernetes#/nodes

<img width="818" alt="screen shot 2018-06-02 at 10 04 04" src="https://user-images.githubusercontent.com/1146409/40906410-5e086846-67e9-11e8-895d-d76b8956684a.png">

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
