### ISSUE TITLE
User manifest override.json for system packages

### ISSUE THREAD

**Issue by opoplawski** [cockpit-project/cockpit#9299]
I'd like to disable the terminal.  Possibly just for certain users, but even completely would be fine.  At the moment I have to edit /usr/share/cockpit/systemd/manifest.json to remove it.

**Comment by martinpitt** [comment]
You can create a [manifest override](https://cockpit-project.org/guide/latest/packages.html#package-replace) globally in /usr/share/cockpit/systemd/override.json or per-user in ~username/.local/share/cockpit/systemd/override.json.

**Comment by opoplawski** [comment]
Ah, thanks!  Sorry I didn't catch that...

**Comment by RobertDeRose** [comment]
@martinpitt Could you explain the 'per-user' version more?
I was able to get the `/use/share` one to work as expected, but when I attempt `~username` with the name of my user, in this case `rderose` and then log in with the rderose account, the override does not work.  Does this require a specific version of systemd to work? I'm currently trying with Debian 9 using systemd 232

**Comment by martinpitt** [comment]
@RobertDeRose : Right, sorry, right now you can't override a system manifest with a per-user one. So only the /usr/share/cockpit/systemd/override.conf will work.

**Comment by RobertDeRose** [comment]
@martinpitt Thank you for the clarification. Bummer, but thanks.

So I am trying to disable the terminal for certain users, and the override.json removes the buttons, but if they still know to navigate to `$URL/system/terminal` they can still access it. 

So even the manifest override isn't really a working solution.

Any other thoughts how to accomplish this? 

Thanks for your time!

**Comment by martinpitt** [comment]
@RobertDeRose : Disabling the Terminal is *not* a security measure, it's just some UI cleanup. As soon as you have a running cockpit session, you can run arbitrary commands in it (with your user's  permissions, and as root if the user is an admin) using the JavaScript console.

**Comment by stejoo** [comment]
I am also looking into this to try and hide certain packages/plugins for certain users. 
Has there been any change allowing overrides to work on a per user basis?
I'm trying to remove features for a certain user to minimize the possibility of confusing them. By simply allowing them access to just what they need.

Otherwise I might try disabling many of the regular packages/plugins system-wide and enable them again on a per user basis by installing working variants in their `~user/.local/share/cockpit/<package name>` paths.

**Comment by martinpitt** [comment]
@stejoo Disabling a page on a per-user basis in ~user/.local/share/cockpit/ has always worked.

**Comment by stejoo** [comment]
Thanks for your reply @martinpitt 

I'm glad to see this should be functional. So this should be down to user error than.

I had resorted to embedding after attempts at hiding parts of the interface did not work for me. I used https://cockpit-project.org/guide/latest/embedding.html and that did the trick. We have written a plugin for Cockpit to aid installers in setting up the machine in the field. That works well. And before the recent update that added "Restrict frame embedding to same origin" this method worked fine in restricting less experienced personnel within just that part.

We cannot keep running that version forever, hence I'm revisiting this method.

Thank you for the tip. I have tried disabling parts of the package manifest for particular user account already via that method (override file in the `~/.local/share/cockpit/`. That didn't go well for me. I would be very glad if you could provide me with some tips or point out documentation on how to hide elements of the Cockpit UI for a certain user.

I would be grateful for any help on the matter. And if I can help in any way I am all ears. Perhaps I could write some documentation for such a customization to aid others in the future?

**Comment by martinpitt** [comment]
Argh, indeed a ~/.local/share/cockpit/systemd/override.json does *not* apply to /usr/share/cockpit/systemd/manifest.json. You'd have to put it right next to the corresponding manifest.json, i.e. right now only /usr/share/cockpit/systemd/override.json works. But that's stupid indeed, as admins should really not write there.

Reopening due to this, and retitling accordingly.

**Comment by stejoo** [comment]
Thank you for verifying and confirming @martinpitt.

Writing to `/usr/share/cockpit` is indeed not the way. On Fedora IoT, which I am using, that location is immutable even.

**Comment by martinpitt** [comment]
I have a fix for that now. It's working fine, I just need to create some integration tests.

**Comment by stejoo** [comment]
Oh wow, that's fast. Thank for your work on this. If I can help out by testing I'd be happy to.

**Comment by martinpitt** [comment]
Being developed in #16884. We also auto-build COPR packages for all Fedoras and CentOS 8/9, if you want to take them for a spin. Follow the "rpm-build:*" test contexts.

**Comment by aweaver1fandm** [comment]
I see in the comments there are several directories where your fix is supposed to look for overrides.  However, the documentation found here: https://cockpit-project.org/guide/latest/packages.html#package-manifest-override  probably needs to also be updated.  Currently it says:

**Comment by martinpitt** [comment]
The documentation is correct. For your particular case, it should go into ~/.config/cockpit/systemd.override.json. ~/.config/cockpit/systemd/* is not looked at. Possibly the first sentence is a bit misleading, and we should replace the comma with ". Alternatively..."?

**Comment by aweaver1fandm** [comment]
Thanks that is helpful
