### ISSUE TITLE
machines: Improve File download dialog - external console

### ISSUE THREAD

**Issue by mareklibra** [cockpit-project/cockpit#9338]
In machines, data for an external remote desktop viewer application is provided via file download of a generated `.vv` file.

Recent Cockpit's CSP (content security policy) which is farther tailored in `pkg/machines/manifest.json.in` does not allow such action.

As a workaround, download via `iframe` is recently used, but causing ugly, non-standard, download dialog.

The CSP should be set properly to work on all supported browsers.
If successful, recent download-logic can be replaced by generic [file-saver](https://www.npmjs.com/package/file-saver).

As an alternative solution, the generated content can be stored on host filesystem and served by cockpit-ws as a regular file to by-pass the CSP setting. Multi-machine environment needs to be considered in this case.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

We are sorry, but we won't be able to address this in any time soon.
If you are interested in helping us with the implementation, please comment here.
