### ISSUE TITLE
Add support for setting up log forwarding to a remote server

### ISSUE THREAD

**Issue by sgallagher** [cockpit-project/cockpit#9376]
If the system has rsyslog installed, Cockpit would need only to ask for the IP/host of the remote log aggregator and set
```
action(type="omfwd" Target=192.168.122.201 Port="514" Protocol="udp")
```
in the rsyslog.conf to enable the local logs to be forwarded.

**Comment by martinpitt** [comment]
FTR, as Cockpit heavily depends on systemd/journal, this should probably integrate with systemd-journal-remote, not with rsyslog.

**Comment by sgallagher** [comment]
The problem with that is that all log aggregators support rsyslog format, but nearly none of them support systemd-journal-remote.

Since systemd-journald can export using rsyslog, it makes sense to use that protocol.

**Comment by martinpitt** [comment]
This is still "current" in the sense that the original description is still valid. However, in practice it will still be a "wont fix", I'm afraid. rsyslog really isn't a thing any more in Fedora, RHEL 8, Debian, Ubuntu, and other modern distributions. You can still install it of course, but it's not what these OSes use and support by default. So adding this to the Logs page would feel quite "bolted on", and not really integrated.

So I close this now to unclutter our bug tracker a bit. If you object, I'm fine with keeping this open, of course.
