### ISSUE TITLE
iSCSI & NFS UI Widgets Missing

### ISSUE THREAD

**Issue by BlamKiwi** [cockpit-project/cockpit#9379]
I have Cockpit 169 running on an Ubuntu 16.04 system. However when I navigate to the Storage tab I don't see any options to configure iSCSI or NFS. 

Is this because I haven't configured my system properly? I can't tell what's wrong because the UI doesn't give a lot of feedback.

**Comment by KKoukiou** [comment]
@BlamKiwi sorry for the late reply. Do you still have this issue? If yes can you please post a screenshot of your storage page and also js console logs.

**Comment by Ussat** [comment]
I dont think so, I have it working on Ubuntu just fine, and it works on Cent/RHEL fine as long as I connect to the local cockpit, but not if I attach the system to a remote cockpit.

**Comment by marusak** [comment]
Seems like fixed in https://github.com/cockpit-project/cockpit/pull/12484
