### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by wrinkledcheese** [cockpit-project/cockpit#9403]
I have an issue that I suspect I know how to fix it, but security alarms are going off.

I found what I think is my solution in this ticket:  https://github.com/cockpit-project/cockpit/issues/8334

Brad Pitt's cousin ( haha I actually forget his first name ) had posted something that I think is exactly the problem I'm having, although it was not the OPs issue.

He had said:

> In the latter case the PAM config will need some adjustment.

I'm running OpenSuSE Leap 15, which doesn't have an official package.  I've gotten as far as being able to connect and get the login from another system, but I have never had luck with PAM configuration.

I noticed there doesn't seem to be any cockpit files in and of the PAM directories I have and I can't seem to find any docs on PAM installation.  In the compiled source directory from git clone, there is a tools/cockpit.pam that looks like it is a pam module for various distros.  Should I just be able to install this PAM module without any security concerns ( copy pasta as is )?

[edit]

When I tried, instead of getting a "Wrong user name or password" error, I got a "Permission denied" error.

[edit]

I came across this: https://www.reddit.com/r/Fedora/comments/4y7p3v/cant_login_to_cockpit/
> Journalctl -xe
> Should highlight the failure specifically.

And it looks promising as a direction to head in.  Hopefully this post helps someone else.

[edit]

While promising, it was only one of my issues.  It appears as though SuSE linux has password-auth ( as I can find it's defaults using Google ) split unto multiple files.  I will try and approach modifying the default cockpit config using the files as they exist on SuSE linux.  If successful I will post my results.

[edit]

SUCCESS!  In commenting out the postlogin lines ( it appears this is for logging failed attempts ) and modifying the multiple password-auth lines, I was able to log in.

The files I used were common-*.  The word after the dash depended on the module interface portion of the config ( the foirst word ).
Eg,
`auth require password-auth`
I replaced with
`auth include common-auth`
`account require password-auth`
I replaced with
`account require common-account`

Hope this helps someone.

**Comment by wrinkledcheese** [comment]
> Closing as I've resolved my own issue.

**Comment by cloud-rocket** [comment]
* I am running into this issue on GCP (users are created automatically and available under `/etc/passwd`)
* Installed Ubuntu 18.04 minimal
* Install `cockpit` with `apt install cockpit`

`/var/log/auth.log` reports:

```
Feb 25 12:17:54 cockpit cockpit-session: pam_unix(cockpit:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=10.142.0.7  user=myuser

``` 

Any idea?
