### ISSUE TITLE
SuSE Linux requires root password while performing actions via cockpit.

### ISSUE THREAD

**Issue by wrinkledcheese** [cockpit-project/cockpit#9404]
Whenever I perform an action on cockpit, the system I'm remotely administering requires the root password.  This appears to be a PolKit issue after some brief research.  

I will hopefully document all of my findings while preventing a SuSE linux system running cockpit from requiring a root password whenever an action is performed via the cockpit interface( such as formatting drives and creating a RAID volume ).  I doubt I will get all of the required actions, but hopefully I will get some of them.  More importantly, I'm hoping to document the generic procedure which can be applied to all actions required by cockpit.

[edit]

So far it appears that when a permission is required.  The prompt on the remote system has a details button that has all the information that you require.  For example, deleting partitions and formatting drives gives the following information:

org.freedesktop.udisks2.modify-device-system
org.freedesktop.udisks2.modify-system-configuration

**Comment by martinpitt** [comment]
Can you please be more specific which cockpit version you are using? This seems a bit odd. Normally the root cockpit-bridge is started pretty much right after logging in, and from then on there should not be any auth requests -- either you have a root bridge and can run administrative commands, or not. This got cleaned up recently in [168](https://cockpit-project.org/blog/cockpit-168.html).

**Comment by martinpitt** [comment]
No response in half a year, and most probably be fixed in version 168.
