### ISSUE TITLE
Cockpit number of concurrent servers connections

### ISSUE THREAD

**Issue by 851d229** [cockpit-project/cockpit#9411]
Hi everyone,

I got the message "Connecting simultaneously to more than 20 machines is unsupported" after that I added my 21th server.  I don't have any problem to disconnect some other servers to allow connection of new ones.  How can we disconnect servers from the console? I didn't find a way to disconnect a server from the Dashboard.  Or can we instruct Cockpit to automatically disconnect servers after some time?

thank you !

**Comment by stefwalter** [comment]
This is an area where Cockpit needs work. 

 * We shouldn't need to connect to all systems simultaneously. 
 * We should be able to connect to an arbitrary system from the choose machine drop down.
 * And we should have a way to connect to additional systems without displaying their status on the dashboard.

CC @andreasn

**Comment by 851d229** [comment]
Would be  great for theses works!

Hope to get an answer on this one.  Is there a way to disconnect the servers on the Dashboard?

**Comment by 851d229** [comment]
Ok so actually we still can't disconnect machines to add new ones....  well, hope this feature will be developped soon, because right now my number of machine is going far from 20

**Comment by danielporto** [comment]
Any update on this? 
I've just hit the wall of 20 machines...

**Comment by martinpitt** [comment]
Sorry, we won't change this. Cockpit really isn't a tool to track many machines at once.
