### ISSUE TITLE
typing 'make' doesn't update dist/base1/cockpit.js

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#9424]
Step 1: edit src/base1/cockpit.js
Step 2: type 'make'
Step 3: run some tests, and notice that they're using the old cockpit.js

Basically, webpack doesn't copy updated cockpit.js into dist/

I've tried a few modifications to the webpack config (including adding a 'base1' package and listing it in the Makefile), but I can't figure out how to fix this properly.

**Comment by allisonkarlitskaya** [comment]
This broke with #8266.

**Comment by larskarlitski** [comment]
This was reverted with 5341eec7d, and subsequently fixed in a better way with 5341eec7d. In any case, `make` works correctly now.
