### ISSUE TITLE
update to new login pattern from patternfly?

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#9432]
[Patternfly 3.37.0](https://github.com/patternfly/patternfly/releases/tag/v3.37.0) changed the login page pattern.

[Design specification](https://www.patternfly.org/pattern-library/application-framework/login-page/#overview)
[Demo](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/login-basic.html)

**Comment by andreasn** [comment]
It has some slight regressions for us with regards to mobile compared to the custom classes we added for our current mobile layout. It does allow us to get rid of some code that we currently maintain though.
Not too many other products have migrated to the new screen yet, so not any insane hurry to fix this I think.

**Comment by andreasn** [comment]
@garrett

**Comment by marusak** [comment]
This has been done :)

**Comment by garrett** [comment]
Yep, we leapfrogged at least a design iteration or two. :wink: Thanks for closing this bug! :+1:
