### ISSUE TITLE
Login: Improved message for unsupported browsers

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#9438]
Currently, unsupported browsers get a message about WebSockets. It should be improved to suggest a list of various "known-good" browsers.

Of the top of my head, I'd suggest mentioning "a recent version" of:

- Firefox
- Chrome
- Edge
- Safari

...and omitting specific version numbers.

**Comment by garrett** [comment]
FontAwesome has browser brands. Provided the version of PatternFly we use has these icons, we can simply use FA icons and have links to the various browsers.

https://fontawesome.com/icons?d=gallery&q=browser

It should be pretty trivial, but the priority is not as high, due to upcoming deadlines.

**Comment by garrett** [comment]
A modern browser is needed for security and reliability.

Please upgrade to one of the following:

_(Highlight downloadable browsers, with graphics)_

- Firefox
- Brave
- Chrome

(Mention browsers that come bundled with the OS, also with graphics)

- Edge included in Windows 10
- Safari included in macOS
- Web included in GNOME

(Then have a list of mobile browsers, including some of the above, but only in text form.)

---

So I was thinking we want to highlight (with graphics) desktop browsers when viewed on a desktop and mobile browsers on a mobile device. 

The page would _most likely_ come up when someone is using IE. If they're using IE, they're _probably_ on Windows < 10 and need to download a browser (or upgrade an OS). The order prioritizes open source browsers for the downloads. The bundled browsers list prioritizes by general market share of OS.

**Comment by garrett** [comment]
Here's a mockup that preserves the style of the login screen's background and highlight area and uses the above logic:

![browser-warning](https://user-images.githubusercontent.com/10246/43137065-061c9010-8f4b-11e8-8a50-dd311fc9ffad.png)

**Comment by garrett** [comment]
FWIW: While FontAwesome is used within Cockpit, it isn't used for the login screen. I've worked on the logos and reduced them to their minimum filesize in hifi SVG, 64×64 PNG, and lofi SVG.

Hifi SVG: 36kb, 40kb inlined into CSS (using SVG text inlining instead of base64, which would be more costly)
Hifi PNG: 24kb
Lowfi SVG: 13kb
Lofi PNG: 13kb

Everything would probably have to be inlined into the CSS, adding 30 - 60 kb to the page load, depending on if we go with SVG or PNG and hifi or lowfi.

Considering this screen will almost only ever be displayed for IE, we could use SVG... or just go with inline'd 64×64 PNGs, as someone running IE is probably using an old version of Windows and therefore not really on a hidpi screen (which would render the logos a bit blurry).

**Comment by garrett** [comment]
(Not pictured in the mockup, but implied: we could have a footer that says "bla blaa blah blaaa are registered trademarks so on and so forth" for the respective logos.)

**Comment by andreasn** [comment]
Full color versions sounds tricky from a copyright standpoint, as the logos from the different vendors are non-free, and something I'm sure the different distros are not very keen on shipping.

So are these logos included in our copy of FontAwesome? If so, I guess it should be fine with the fontawesome provided icons.

**Comment by andreasn** [comment]
Saying Edge is on Windows 10 makes me think it would not be available on a future Windows 11 (or whatever they'll call the next version). Would force us to fix Cockpit in the future (and then backport that during RHEL's lifecycle?)

**Comment by garrett** [comment]
[Windows 10 is the last version of Windows](https://www.theverge.com/2015/5/7/8568473/windows-10-last-version-of-windows)

And here's a modified mockup with simple 1-color (and some alpha) icons, which also has "Windows 10+":

![browser-warning-simple](https://user-images.githubusercontent.com/10246/43143746-d29c802c-8f5b-11e8-9a5e-29248914c638.png)

FontAwesome is not shipped with the login screen. I could make a subset version which is just browser logos (and do a special one for Epiphany and possibly Safari, as seen here).

**Comment by garrett** [comment]
Here are the browser icons in FontAwesome:

https://fontawesome.com/icons?d=gallery&q=browser

Preview:

![screenshot_2018-07-24 font awesome 5 icons](https://user-images.githubusercontent.com/10246/43144019-6fb4a984-8f5c-11e8-8930-3cf3477f9182.png)

It's lacking Brave and Epiphany. I could merge them into the font subset (which would be inlined, like we do elsewhere) too or reference them as SVG.

**Comment by garrett** [comment]
After thinking about it and peeking into the code for the login screen, I think we should drop the idea of the logos, for two reasons:

1. It increases the transfer time for the files (although only like 40kb - 60kb, which isn't so much)
2. It gets a bit murky trademark-wise.

It's kind of sad, as it's prettier with the logos. But oh well. Realistically, the only people seeing this will hopefully be a very small subset who are using IE or some really old browser.

(Even obscure browsers are usually using WebKit or Blink these days. And old in this context is something like a rendering engine that's a decade old.)

**Comment by martinpitt** [comment]
It seems a bit sad indeed, but after pondering this a bit I agree to the textual variant. After all, this is an edge^Wcorner case, and even the people who *do* see it, see it only once. So there's not that much benefit in being pretty, and avoids issues with font maintenance and trademarks.

Plus, this should even work in w3m and links :-)

**Comment by garrett** [comment]
Well, the detection right now is based on JavaScript... so it wouldn't work properly in w3m and links.

Right now, it _looks_ like lynx works (but doesn't). Same for w3m. 

I'm wondering if we should use CSS's `@supports` to turn on/off blocks for a first-line feature detection then fall back to JS-based detection to turn on/off the same blocks of HTML.

**Comment by andreasn** [comment]
Not working on Lynx affects very, very few people. I wouldn't loose sleep over it.

**Comment by garrett** [comment]
People who care about terminal browsing probably use the terminal for managing systems already. The audience for managing systems in a modern graphical browser are probably already using a modern graphical browser. I don't think @martinpitt or I were being really serious about textmode browsers. :wink:

**Comment by garrett** [comment]
This part of the comment was actually serious though, and has nothing to do with textmode browsers:

> I'm wondering if we should use CSS's @supports to turn on/off blocks for a first-line feature detection then fall back to JS-based detection to turn on/off the same blocks of HTML.

**Comment by andreasn** [comment]
> I don't think @martinpitt or I were being really serious about textmode browsers.

Haha, ok!

**Comment by garrett** [comment]
Here's what I have for a WIP implementation, loosely based on the mockups:

![screenshot_2018-08-01 sunny](https://user-images.githubusercontent.com/10246/43536144-276afbe0-95bc-11e8-99bf-ead435795e0c.png)

I dropped Safari (as macOS folks are incredibly unlikely to see this error message) and Brave (to balance it out, and because if we're recommending browsers, let's recommend the ones we ourselves use).

I'll push this up as a PR tomorrow and look into removing the branding and moving the heading & error outside of the light box area.

**Comment by martinpitt** [comment]
This page looks so nice (plain elegance) that it's almost a pity that most people will never see it :)

**Comment by andreasn** [comment]
What's your definition of bundled?
GNOME Web is not installed by default in any distro that I am aware of, since most of them bundle Firefox. You need to install GNOME Web post-installation.

**Comment by garrett** [comment]
@andreasn: Oh. I guess I should switch it back to Safari / macOS then? Or just drop it down to Edge (which seems a little weird in this layout).
