### ISSUE TITLE
containers: can't see what containers depends on an image from the overview page

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#9470]
I was in the process of deleting some images, but a couple of them had containers depending on them.
I was unable to see this from expanding the images in the overview, but I could see the containers if I dived in and checked the image on it's own page.

![screenshot from 2018-06-22 09-52-50](https://user-images.githubusercontent.com/209895/41765699-22a9cfe0-7605-11e8-87ef-324a1122710b.png)

![screenshot from 2018-06-22 09-52-41](https://user-images.githubusercontent.com/209895/41765710-2ba7d830-7605-11e8-8808-01c8aa970760.png)

**Comment by andreasn** [comment]
The best solution would be to have a "Containers" or a "Used by Containers" tab in the containers pane in the overview.

**Comment by Gundersanne** [comment]
The "Used by Containers" on the image's details page isn't migrated to React yet. This might be a good opportunity to migrate that component first, and then use it in both `/docker#/image` and the `/docker` page.

**Comment by martinpitt** [comment]
Let's not do much work on the Docker page any more, but instead implement such things in cockpit-podman.
