### ISSUE TITLE
Needs an easier workflow for deleting images with containers depending on them

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#9474]
We could be more clever when trying to delete an image that has containers depending on it.

This is what we currently present:
![screenshot from 2018-06-22 11-13-54](https://user-images.githubusercontent.com/209895/41768727-5f28e8c2-760d-11e8-8cf9-d20df6971ff1.png)

We could potentially list all the images in the dialog that comes before that and allow to delete those together with the image itself.

**Comment by andreasn** [comment]
Here is a design proposal:

![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/2d3690941bf8811af41ef77b93cbc5c7faba2a26/containers/delete-image-warning.png)

**Comment by Gundersanne** [comment]
Also keep in mind there's already a confirmation dialog. So if we do force removal we'd need to merge those two. This is what I have now:

![screenshot from 2018-07-02 15-49-04](https://user-images.githubusercontent.com/11140201/42167827-7ea620fc-7e0f-11e8-9538-8800d4d7ef31.png)
