### ISSUE TITLE
Logs Entry UI Spacing

### ISSUE THREAD

**Issue by leomoty** [cockpit-project/cockpit#9481]
While looking up some logs today, I got a crash on a Dotnet App, when I selected the entry itself, the label and the message were glued together.

Running Cockpit Project 170 on Fedora Server 28.

A few screenshots:

![image](https://user-images.githubusercontent.com/1463740/41810863-b8011572-76db-11e8-882e-5f2f032fad1a.png)

![image](https://user-images.githubusercontent.com/1463740/41810867-c61c7188-76db-11e8-85f8-5f9e606e51f4.png)

![image](https://user-images.githubusercontent.com/1463740/41810872-ce2abdb2-76db-11e8-9293-8b2f2f8bd987.png)

**Comment by leomoty** [comment]
Took a better look at it, there is a rule for some padding-left and padding-top which is `.info-table-ct > tr > td` in system.css.

**Comment by stefwalter** [comment]
CC @andreasn What do you think?

**Comment by leomoty** [comment]
@stefwalter, seems like this was done on purpose in https://github.com/cockpit-project/cockpit/commit/0ca254dbf56dcd82437eade8c90055b4a4815adb.

**Comment by andreasn** [comment]
Yeah, looks like 0ca254d broke this layout.
@mvollmer what do you think?
