### ISSUE TITLE
org.freedesktop.Problems support

### ISSUE THREAD

**Issue by jfilak** [cockpit-project/cockpit#95]
org.freedesktop.Problems D-Bus interface [1] has been designed for management of application failures. Currently only ABRT implements this interface, however, it would be nice if cockpit could display the detected problems. The interface has not yet been standardized thus any changes needed will be immediately included and implemented in ABRT.

1: http://jfilak.fedorapeople.org/ProblemsAPI/re01.html

**Comment by stefwalter** [comment]
This has been sitting here a while and nobody has yet done anything about it. I've moved this to our ideas page:

https://github.com/cockpit-project/cockpit/wiki/Ideas
