### ISSUE TITLE
machines: grouping of controls needed

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#9523]
As a followup to PR #9166
The controls needs some spacing, otherwise it looks like "Target" belongs to "Name", because it's closer to that control than it is to "Pool"

This is how it currently looks:
![mockup](https://user-images.githubusercontent.com/17194943/40228013-63b88f20-5a90-11e8-94d0-eb021c1b9ac0.png)

Here is the wirefram of the correct spacing,
![mockup](https://user-images.githubusercontent.com/10246/40051668-e2128a1c-583b-11e8-9e73-81cc55950da0.png)

**Comment by martinpitt** [comment]
This got fixed by removing Target entirely in PR #10688.
