### ISSUE TITLE
Nigh impossible to install even from source

### ISSUE THREAD

**Issue by junebug12851** [cockpit-project/cockpit#9527]
This looks like a really promising project but I've spent the past few hours trying to get it installed, given up twice already, and may just give up all-together.

My system is Arch Linux, one of the unsupported platforms officially, it's no problem because there's AUR, however this is the problem with AUR

1. AUR wants to build with the default configuration and that includes PCP. 
2. PCP is within `systemtap` on AUR however `systemtap` is no longer maintained in AUR by a direct notice from the maintainer May 19th 2018, it's been unofficially updated since but the PGP signature is invalid so it won't install. 
3. There's `systemtap-git` but it also has seperate problems and won't install

That's no problem, Arch it's an unofficial platform and AUR can have issues like this so I can switch to good old fashioned source compile as a last resort

I wasn't able to find any source code repo for systemtap since I wasn't sure whether to trust the .tar archive in AUR especially since signatures weren't matching up however I found a handy little config that tells cockpit to not compile with PCP and boom all those problems are solved `--disable-pcp`

The next problem was cockpit goes rather out of it's way to ensure that you only install the friendly package either officially or unofficially, all documentation whatsoever points to this friendly page. Since I'm in a position where I can't install the friendly package I'm left with absolutely no documentation at all in any shred as to how to compile and run from source so I'm going to have to blindly guess at the defaults

Since I see an autogen.sh file I'm going to assume its

1. ./autogen.sh
2. configure with `--disable-pcp`
3. make
4. make install

So I do all that, it takes a while but completes all those steps

However I don't see it anywhere on my system, I figured maybe it all stays contained in this folder since some packages compile and install to a sub-folder rather than directly on the system but I don't see any subfolders that might house executables or something. Without any documentation I really don't have any idea the details of compiling this project from source and installing it then manually configuring and setting it up, all I have is rather good usage documentation after it's installed and initially setup by the system package

So I'm asking for help, maybe I'm missing the docs somewhere that tells how to compile, install, and setup from source or maybe I did everything right and I'm not looking in the right place, or maybe I need to adjust some build settings? Asking for help on this.

Furthermore I suggest making more obvious easier docs for compiling and installing from source, the way I got to this repo was by:

1. Going to the official site
2. Clicking edit this page link at the bottom
3. Clicking `cockpit-project` to be taken out of the website repo
4. Clicking `cockpit` to be taken into the correct source code repo

Therefore I also suggest just including a link to the github repo directly or a "Fork this project" link in the Upper Right-Hand corner ^_^ and overall making it more friendly with all Linux users by having easily accessible source code and install documentation so users can always compile and install if they want to or as a last resport

Any help is appreciated, thanks

**Comment by martinpitt** [comment]
You can easily build without PCP with `./configure --disable-pcp`. Please see `./configure --help` for similar options, in case other libraries are not available either. It seems you already found that option :-) A lot of autotools-based free software projects work like that.

If you build from a released tarball (which is heavily recommended), then don't run `./autogen.sh`.
If you build directly from a git checkout (not recommended unless you have a specific reason), you can do this with `./autogen.sh --disable-pcp` and skip the `./configure` step, that's already included.

> The next problem was cockpit goes rather out of it's way to ensure that you only install the friendly package either officially or unofficially

What is the "friendly package"?

Judging how much trouble you have, please give it a try to get the latest release from https://github.com/cockpit-project/cockpit/releases and configure/make/install that. This won't need webpack and `npm install` and all the extra stuff:
```
wget https://github.com/cockpit-project/cockpit/releases/download/171/cockpit-171.tar.xz
tar xf cockpit-171.tar.xz
cd cockpit-171/
./configure --sysconfdir=/etc
make -j4
sudo make install
```
Note that this still requires installing all of its build dependencies, `./configure` most likely will fail a couple of times and tell you what it needs. After that you also need to install a `/etc/pam.d/cockpit`  file that works for Arch Linux (we don't ship one upstream), have a look at tools/cockpit.pam or tools/cockpit.debian.pam as examples.

If all of that still intimidates you and you never built a package before, then maybe it would be better to let someone from the Arch community package Cockpit? :-)

**Comment by martinpitt** [comment]
Also, cockpit is reasonably current in https://aur.archlinux.org/packages/cockpit/, so it actually *is* already packaged. Why don't you just take this?

**Comment by RobotsAreCrazy** [comment]
on manjaro-arm

Hi Martin,  i got inquisitive and wanted to build and install the latest version.... i had to disable-doc and pcp to make progress

"install a /etc/pam.d/cockpit file that works for Arch Linux (we don't ship one upstream), have a look at tools/cockpit.pam or tools/cockpit.debian.pam as examples."

How do i do this please?

**Comment by RobotsAreCrazy** [comment]
Hi Martin,

This is the contents of .pam at the moment

#%PAM-1.0
# pam_selinux.so close should be the first session rule

session   required  pam_selinux.so close
session   required  pam_loginuid.so
auth      include   system-remote-login
account   include   system-remote-login
password  include   system-remote-login
session   include   system-remote-login

auth       required     pam_sepermit.so
auth       substack     password-auth
auth       include      postlogin
auth       optional     pam_ssh_add.so
account    required     pam_nologin.so
account    include      password-auth
password   include      password-auth

# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required     pam_selinux.so open env_params
session    optional     pam_keyinit.so force revoke
session    optional     pam_ssh_add.so
session    include      password-auth
session    include      postlogin


what stays and what can go?

Thanks

**Comment by martinpitt** [comment]
We actually do ship a PAM file for arch now: https://github.com/cockpit-project/cockpit/blob/main/tools/arch/cockpit.pam

**Comment by RobotsAreCrazy** [comment]
I did get it working in the end, i did the same with v2.63 and that had same entries of default setup on the pam and it wouldn't work it's a funny one, but 2.64 is working with arch cockpit pam
