### ISSUE TITLE
WIKI: Apache Proxy page is missing $1 in websocket config

### ISSUE THREAD

**Issue by mattheys** [cockpit-project/cockpit#9543]
https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-Apache-with-LetsEncrypt

I believe this should read as below with the $1 otherwise the request isn't forwarded to the correct url, it's sent to the root of the website, was the only way to get it working for me.

```
  # allow for upgrading to websockets
  RewriteEngine On
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule /(.*)           ws://127.0.0.1:9090/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket [NC]
  RewriteRule /(.*)           http://127.0.0.1:9090/$1 [P,L]
```

**Comment by Gundersanne** [comment]
Thank you for reporting! This has been fixed.
