### ISSUE TITLE
users: actions fail due to unlocking errors when clicking too fast

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9558]
The users page does not serialize or retry actions when doing lots of things in quick succession. This particularly affects our tests, `check-accounts` often [fails](https://fedorapeople.org/groups/cockpit/logs/pull-9552-20180702-064747-a6ac5a9f-verify-fedora-atomic/log.html#199) with various errors. The associated screen shots say why:

![screenshot](https://fedorapeople.org/groups/cockpit/logs/pull-9552-20180702-064747-a6ac5a9f-verify-fedora-atomic/TestAccounts-testBasic-fedora-atomic-127.0.0.2-2901-FAIL.png)

On other pages our approach is generally that we disable UI actions while an activity runs. This provides proper serialization and should work here as well.

**Comment by martinpitt** [comment]
@stefwalter : FYI, this is the issue we talked about last week. I'll see to talk someone into fixing this :)

**Comment by as-rawat** [comment]
I'd like to fix it! I don't even know where to start... It'll be great if you could provide some pointers 👶

**Comment by martinpitt** [comment]
@as-rawat : Nice! It shouldn't be too difficult actually. If you want to give it a stab, here are some notes which hopefully help. Also, if you want to work on this, I strongly recommend reading [Working on your local machine](https://github.com/cockpit-project/cockpit/blob/master/HACKING.md#working-on-your-local-machine) so that you can develop on Cockpit with fast iteration cycles.

For an old jquery/plain JavaScript page like users, disabling/enabling an element happens through the `disabled` property; the [users page code](https://github.com/cockpit-project/cockpit/blob/master/pkg/users/local.js#L911) already does that plenty of times, like this:

    $('#my_element_id').prop('disabled', true);

So the exercise is to change `change_role()`, `change_real_name()` and all other functions to disable all UI elements before the `cockpit.spawn` (which calls things like `passwd`) and re-enable them again after spawn finishes.

Of course this should not disable every button/link individually, that would be laborius, error prone, and hard to maintain. It should work to disable a parent element which includes them all. My first guess would be [#account-details](https://github.com/cockpit-project/cockpit/blob/master/pkg/users./index.html#L75).

It could also be that the tests need updating, to wait until elements become enabled again. (I'm happy to help with that).

**Comment by as-rawat** [comment]
Thanks for pointers! I think, I'm not getting a perfect picture of what's happening here... but I think...
The bug is:
-users is able to trigger activities even when an activity is already running which affects tests and fails.
What I have to do is:
-Install cockpit
-When a user starts an activity(cockpit.swamp) disable everything on the page(DOM or a parent element) till its completed and then re-enable it.

Please correct me! 😕

**Comment by martinpitt** [comment]
@as-rawat : You've got it right. :+1:

**Comment by as-rawat** [comment]
@martinpitt Sorry for not giving any details. I would like to work on it but wasn't able to cuz I was giving few interviews and searching for the jobs.
