### ISSUE TITLE
store performance data option ON issue

### ISSUE THREAD

**Issue by nirajvara** [cockpit-project/cockpit#9604]
I have installed  cockpit-154 in  Red Hat Enterprise Linux Server release 7.4. 

Its working fine but when I ON the  **store performance data**   option after few second its disable/Off again.

I am not able to identify the issue why it's not ON !! 

Please guide what could be the issue.

**Comment by mvollmer** [comment]
Sorry for letting this sit for so long.  If you are still experiencing this, please try
```
systemctl enable --now pmlogger pmcd
```
in a shell.  Does it produce any error messages?

What does
```
systemctl status pmlogger
```
show?

What is the content of `var/log/pcp/pmlogger/$(hostname)/pmlogger.log`?

**Comment by aleho** [comment]
I can confirm this issue. Same behavior on Debian/buster, version 185.

Web interface logs an error object:
```JS
"Enabling pmlogger failed",
{
  "problem": null,
  "name": "org.freedesktop.systemd1.UnitGenerated",
  "message": "Unit /run/systemd/generator.late/pmcd.service is transient or generated."
}
```

I suspects it's a detection error, as the services seem to run without issues?


```sh
$ systemctl status pmlogger
● pmlogger.service - LSB: Control pmlogger (the performance metrics logger for PCP)
   Loaded: loaded (/etc/init.d/pmlogger; generated)
   Active: active (exited) since Fri 2019-01-11 22:13:28 CET; 1 weeks 0 days ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 0 (limit: 4915)
   Memory: 0B
   CGroup: /system.slice/pmlogger.service
```

```sh
$ systemctl status pmcd.service
● pmcd.service - LSB: Control pmcd (the collection daemon for PCP)
   Loaded: loaded (/etc/init.d/pmcd; generated)
   Active: active (running) since Fri 2019-01-11 22:13:28 CET; 1 weeks 0 days ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 6 (limit: 4915)
   Memory: 12.1M
   CGroup: /system.slice/pmcd.service
           ├─1015 /usr/lib/pcp/bin/pmcd
           ├─1029 /var/lib/pcp/pmdas/root/pmdaroot
           ├─1066 /var/lib/pcp/pmdas/proc/pmdaproc -d 3
           ├─1087 /var/lib/pcp/pmdas/xfs/pmdaxfs -d 11
           ├─1096 /var/lib/pcp/pmdas/linux/pmdalinux
           └─1115 /var/lib/pcp/pmdas/kvm/pmdakvm -d 95

Jän 11 22:13:28 nas systemd[1]: Starting LSB: Control pmcd (the collection daemon for PCP)...
Jän 11 22:13:28 nas pmcd[513]: Starting pmcd ...
Jän 11 22:13:28 nas systemd[1]: Started LSB: Control pmcd (the collection daemon for PCP).
```

**Comment by JannikArndt** [comment]
I've had a similar issue (Version 185, fresh install on a Raspberry Pi). The warning only showed up in the Web-Inspector :-/ 

I looked into the `pmcd.service`, and indeed, it is generated (whatever that means):

```
$ sudo systemctl status pmcd.service   
● pmcd.service - LSB: Control pmcd (the collection daemon for PCP)
   Loaded: loaded (/etc/init.d/pmcd; generated; vendor preset: enabled)
   Active: active (running) since Tue 2019-02-12 18:16:49 GMT; 4min 44s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 18333 ExecStop=/etc/init.d/pmcd stop (code=exited, status=0/SUCCESS)
  Process: 18547 ExecStart=/etc/init.d/pmcd start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/pmcd.service
           ├─18627 /usr/lib/pcp/bin/pmcd
           ├─18630 /var/lib/pcp/pmdas/root/pmdaroot
           ├─18631 /var/lib/pcp/pmdas/proc/pmdaproc -d 3
           ├─18632 /var/lib/pcp/pmdas/xfs/pmdaxfs -d 11
           └─18633 /var/lib/pcp/pmdas/linux/pmdalinux

Feb 12 18:16:48 raspberrypi-23 systemd[1]: Starting LSB: Control pmcd (the collection daemon for PCP)...
Feb 12 18:16:49 raspberrypi-23 pmcd[18547]: Starting pmcd ...
Feb 12 18:16:49 raspberrypi-23 systemd[1]: Started LSB: Control pmcd (the collection daemon for PCP).
```

If you try to edit it with `sudo systemctl edit pmcd.service`, the file is empty. Only when using `--full` will you get a definition:

```
$ sudo systemctl edit --full pmcd.service
```

If you store that and 

```
$ sudo systemctl restart pmcd.service
```

you _then_ see 

```
$ sudo systemctl status pmcd.service        
● pmcd.service - LSB: Control pmcd (the collection daemon for PCP)
   Loaded: loaded (/etc/init.d/pmcd; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-02-12 18:33:38 GMT; 8min ago
     Docs: man:systemd-sysv-generator(8)
   CGroup: /system.slice/pmcd.service
           ├─20679 /usr/lib/pcp/bin/pmcd
           ├─20682 /var/lib/pcp/pmdas/root/pmdaroot
           ├─20683 /var/lib/pcp/pmdas/proc/pmdaproc -d 3
           ├─20684 /var/lib/pcp/pmdas/xfs/pmdaxfs -d 11
           └─20685 /var/lib/pcp/pmdas/linux/pmdalinux

Feb 12 18:33:38 raspberrypi-23 systemd[1]: Starting LSB: Control pmcd (the collection daemon for PCP)...
Feb 12 18:33:38 raspberrypi-23 pmcd[20599]: Starting pmcd ...
Feb 12 18:33:38 raspberrypi-23 systemd[1]: Started LSB: Control pmcd (the collection daemon for PCP).
```

Next, the web interface give the same warning for `pmlogger`, so you repeat the process and then finally the button switches to "ON" — until you reload the page, then it's off again 🙈

**Comment by JannikArndt** [comment]
Small correction: The line is actually

```
Loaded: loaded (/etc/init.d/pmlogger; static; vendor preset: enabled)
```

so `static` instead of `enabled`. 

If you try to `sudo systemctl enable pmlogger.service`, it says

```
Synchronizing state of pmlogger.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable pmlogger
The unit files have no installation config (WantedBy, RequiredBy, Also, Alias
settings in the [Install] section, and DefaultInstance for template units).
This means they are not meant to be enabled using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
4) In case of template units, the unit is meant to be enabled with some
   instance name specified.
```

If you `sudo systemctl edit --full pmlogger.service` and then add 

```
[Install]
WantedBy = multi-user.target
```

as proposed [here](https://unix.stackexchange.com/questions/354681/init-service-failing-to-enable-once-a-systemd-service-file-is-generated), _then_ you can 

```
$ sudo systemctl enable pmlogger.service     
Synchronizing state of pmlogger.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable pmlogger
Created symlink /etc/systemd/system/multi-user.target.wants/pmlogger.service → /etc/systemd/system/pmlogger.service.
```

and get the 

```
Loaded: loaded (/etc/init.d/pmlogger; enabled; vendor preset: enabled)
```

line. And then the button actually _stays on_! Only, it doesn't seem to have any effect, once you reload, the metrics will start new 😔

**Comment by Christian1998** [comment]
Any news on this? Experiencing the same on Debian 10.1 with latest Cockpit-Version :/

**Comment by lord-carlos** [comment]
I also have this issue on Debian stable.
Version: 188-1

**Comment by tobbsn** [comment]
This is still an issue for me. My affected machines are also on debian stable (10.2), with the latest cockpit version (188-1).

**Comment by arhimedoffs** [comment]
Same issue, Debian stable. Version: 188-1.
Web interface show `Off`. But metrics actually stored!

**Comment by atifhub** [comment]
Hi, i have got the same issue :-( Any update please ?

**Comment by lord-carlos** [comment]
I switched to Grafana for long term monitoring.

**Comment by atifhub** [comment]
> I switched to Grafana for long term monitoring.

Yes I understand. i'll switch to something serious than the cockpit project

**Comment by m1dnight** [comment]
Same issue here. Tried all the above suggestions and none of them work. Not going to be salty, but going to keep an eye out. Too unexperienced to help here, though.

**Comment by m1dnight** [comment]
> Same issue, Debian stable. Version: 188-1.
> Web interface show `Off`. But metrics actually stored!

Now that you mention it, the metrics on the front page and storage page are indeed stored!  If you look at the networking page they don't seem ot be (or my values are near 0 all the time). I will get back on this.

**Comment by m1dnight** [comment]
Not sure if this is helpful, but I noticed that after a reboot, I presume, it stopped logging metrics. I'm going to try and reproduce and report back.

**Comment by zoltanhomoki** [comment]
Same issue here. The previous workaround (manually starting the services) worked however now since the last reboot cockpit UI won't show the historical data.
It's also Debian 10 with cockpit version 188-1

**Comment by m1dnight** [comment]
> Same issue here. The previous workaround (manually starting the services) worked however now since the last reboot cockpit UI won't show the historical data.
> It's also Debian 10 with cockpit version 188-1

I too have the issue. But simply re-executing the following steps provided by @JannikArndt  fixed it again.


```

**Comment by zoltanhomoki** [comment]
Thanks for the advice. Tried it, the switch on the UI stays "ON" but still no history :(

> > Same issue here. The previous workaround (manually starting the services) worked however now since the last reboot cockpit UI won't show the historical data.
> > It's also Debian 10 with cockpit version 188-1
> 
> I too have the issue. But simply re-executing the following steps provided by @JannikArndt fixed it again.

**Comment by Kisamegr** [comment]
I also got the same issue on Raspbian Buster with version 217...

**Comment by guizmoau** [comment]
+1 bug

same here with two fresh stable debian 10 but it went ok with fresh new raspbian buster...
the workaround above did it but still the bug exist

**Comment by HairyStuntWaffle** [comment]
same issue Raspberry Pi OS Lite, 5.4 kernel, update 2011-1-11

**Comment by martinpitt** [comment]
As above, these were/are bugs in the pcp package (service crashing). The UI just follows the unit state.

**Comment by HairyStuntWaffle** [comment]
I can't seem to find the known issues log for PMCD/PCP. can you advise where these are please.

**Comment by HairyStuntWaffle** [comment]
> As above, these were/are bugs in the pcp package (service crashing). The UI just follows the unit state.

I can't seem to find the known issues log for PMCD/PCP. can you advise where these are please.

**Comment by martinpitt** [comment]
@HairyStuntWaffle : For Raspbian, probably https://bugs.debian.org/src:pcp . For upstream, https://github.com/performancecopilot/pcp/issues
