### ISSUE TITLE
Question: Contributing to Cockpit

### ISSUE THREAD

**Issue by leomoty** [cockpit-project/cockpit#9607]
I tried to get some help over IRC, but didn't get much of a response. I did a small PR the other day, and  mainly tested it by forcing the change on chrome (file override) while cockpit was running on my home server. That was fine, but it doesn't scale well.

I tried following HACKING.md, firstly by going with vagrant option, when I did `rsync` the changes, they never seemed to change anything.

Afterwards, I made a full blown virtual machine with Fedora Workstation, and tried the running local installation portion of the guide. 

A minor nitpick tho, installing `webpack` globally yields a way newer version than the one used in the project. Which was not able to successfully build the `dist` folder with. I used `npx webpack` instead.

My mapping is correct according to the guide, I just don't know why my changes are never reflected on UI. Also using the same user in both cockpit and terminal.

**Comment by KKoukiou** [comment]
Hey @leomoty,
I follow the following steps for development and it works like a charm.

* Install cockpit on my system with my package manager
* Create symlink `ln -snf $PATH_TO_YOUR_CHECKOUT/cockpit/dist/$YOUR_PACKAGE_NAME /usr/local/share/cockpit/$YOUR_PACKAGE_NAME`
* Run webpack (in watch mode to check for changes in your directory). Yeah, the version installed if you execute the command from [HACKING](https://github.com/cockpit-project/cockpit/blame/master/HACKING.md#L27) is very new, you can use the one installed from the development dependencies, like `./node_modules/.bin/webpack --progress --color --watch`
* Make your local changes and make sure your refresh your browser , ignoring cached content (`Control+Shift+R or Shift + F5`) 

I hope this helps, else feel free to step by on #cockpit channel for more help.

Note: `cockpit-bridge --packages` will show you the packages that are visible to cockpit and you can see for a specific package where the code resides.

**Comment by leomoty** [comment]
Hello @KKoukiou, thanks for your answer, i'll give it another try this weekend.

**Comment by leomoty** [comment]
Hey @KKoukiou, I had some progress, I've created yet another VM to test with Fedora (didn't create any new user) and ran the symbolic link command from HACKING.md, with the help of `cockpit-bridge --packages` I was able to see if anything had changed:

```
cockpit-bridge --packages | grep /root/
network: /root/.local/share/cockpit/networkmanager
```

No luck with the other packages tho, still maps to `/usr/share/cockpit/*`, as far as network is concerned, the changes I did to test worked just fine.

**Comment by martinpitt** [comment]
The instructions how to [work from your build tree](https://github.com/cockpit-project/cockpit/blob/master/HACKING.md#working-on-your-local-machine) are still current. However, directly calling `webpack` is not something which we support - there's too much stuff in the `Makefile`s which cannot be represented/done with webpack, so doing the usual `./configure` and `make` is a lot safer bet. You need to at least run configure and make once - after that, you might have some luck with directly running `webpack`.

**Comment by martinpitt** [comment]
I updated HACKING in PR #9974.
