### ISSUE TITLE
Image refresh for openshift-prerelease

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#9608]
Image refresh for openshift-prerelease
 * [ ] fix kubevirt on openshift images (PR #9638)
 * [ ] FAIL: image-refresh openshift-prerelease

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-4b8rt.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9608-20180707-000707/

**Comment by martinpitt** [comment]
@stefwalter: FYI, the bots will just try this again in vain -- this has been blocked/broken for months. In #9975 I at least fix the openshift image to be buildable again, but I have to sacrifice kubevirt. I wouldn't want to kick it out of openshift-prerelease as well, until it's clear what the fate of cockpit kubevirt support will be (there'll be a meeting soon).

**Comment by martinpitt** [comment]
kubevirt is gone now (PR #10085), so let's try this again.
