### ISSUE TITLE
Adding IPv6 machine

### ISSUE THREAD

**Issue by blubbsy** [cockpit-project/cockpit#9612]
Hi,

how do i add a machine that is only available through ipv6? i simply added the ip adress in backets in the json file in /etc/cockpit/machines.d/, but it isnt working. The machine from which iam trying to connect is able to connect through ssh ("ssh -6 [IP] -p PORT", also without the -6 option it works) to the machine, but cockpit is not able to do so. 

BR,
Blubbsy

**Comment by blubbsy** [comment]
So there is no way to connect through IPv6 to another cockpit instance? i  still couldnt figure out how this can work :(

**Comment by AdrianKoshka** [comment]
So...cockpit is just going to ignore IPv6? Thanks for being part of the problem.

**Comment by AdrianKoshka** [comment]
Seems hostnames work, thankfully, even if those hostnames can only be reached over IPv6.

**Comment by blubbsy** [comment]
i think it is a problem in parsing the IPv6 properly. the problem is, that the machine has no hostname, but i was already thinking to create a VPN connection to access the other machine through hostnames or ipv4. 

at the moment my idea was to simply open the specific IPv6 addresses and port in the firewall. at least for tests or temporarely.

**Comment by timway** [comment]
I've been looking into this - starting in pkg/lib/machines.js downwards into the dbus messaging it seems that "connection_string" is used and it's not updated for RFC 3986 / 6874 / 7320. This means an IPv6 address like "2001:db8::1" is interpreted as "2001:db8::" on port 1 instead of ssh://[2001:db8::1]:22. This is likely going to need some input from the core maintainers on how to proceed but it's possible some foundation updating will be required.

**Comment by blubbsy** [comment]
Thanks timway! that was a very helpful explanation :)

**Comment by timway** [comment]
No problem. I've brought it up in IRC a few times and everyone agrees it needs to get addressed. It's just a matter of free time in the pipeline. I'd like to take a crack at it as well but I've been suffering from the same issue lately.

**Comment by blubbsy** [comment]
Just for information: Yesterday i dedicated again some time to find a workaround and simply added the ipv6 to "hosts". Works ;) It is not the nicest way, but this way it is at least usable.

Thanks timway for you help

**Comment by martinpitt** [comment]
This is a cockpit-ssh/libssh bug. Using a hostname works. This is my server; I have ssh key auth there, so it does not need a password (actually doing a challenge is too hard on the command line):

(Note that you need to press Enter a couple of times to make progress)
```
❱❱❱ getent ahosts piware.de
fd42::1         STREAM piware.de

❱❱❱ ./cockpit-ssh piware.de
74

{"command":"authorize","challenge":"*","cookie":"session199681599547134"}
cockpit-ssh-Message: 08:38:55.000: couldn't read control message: Bad message
78

{"command":"authorize","challenge":"basic","cookie":"session199681599547135"}
cockpit-ssh-Message: 08:38:56.096: couldn't read control message: Bad message
410

{"command":"init","version":1,"checksum":"f91d121f711cbcaf9ee7051f3caf79809b1b8b595b1511a5eac1d13713711a71","packages":{"ssh":null,"base1":null,"domain":null,"shell":null,"users":null,"system":null,"performance":null},"os-release":{"NAME":"Debian GNU/Linux","VERSION":"10 (buster)","ID":"debian","VERSION_ID":"10","PRETTY_NAME":"Debian GNU/Linux 10 (buster)","VARIANT":null,"VARIANT_ID":null,"CPE_NAME":null}}
```

(it's a private IPv6, as this is going through a VPN). But when I specify an IPv6 address, either with or without [], it fails:

```
❱❱❱ ./cockpit-ssh '[fd42::1]'
cockpit-ssh-Message: 08:38:16.960: cockpit-ssh fd42::1: refusing to connect to unknown host: fd42::1
{"command":"init","problem":"unknown-host","error":"unknown-host","auth-method-results":{}}

❱❱❱ ./cockpit-ssh '[fd42::1]'
cockpit-ssh-Message: 08:38:25.032: ignoring invalid port in [fd42::1]
cockpit-ssh-Message: 08:38:26.328: cockpit-ssh [fd42::1]: refusing to connect to unknown host: [fd42::1]:22
{"command":"init","problem":"unknown-host","error":"unknown-host","auth-method-results":{}}

**Comment by martinpitt** [comment]
Fixedin PR #14615
