### ISSUE TITLE
Showing SR-IOV VFs in context of the PF

### ISSUE THREAD

**Issue by sghosh151** [cockpit-project/cockpit#9616]
The current networking tabs shows all interfaces on the system as equal. 
It would be more interesting/clear to show physical interfaces vs logical interfaces. In particular - for SR-IOV virtual functions since they show up with standard device names.

In "ip link" output, the PF devices shows all the related VF and mac addresses.

```
3: ens6f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:1b:21:63:5c:41 brd ff:ff:ff:ff:ff:ff
    vf 0 MAC 9a:e9:98:03:6a:49, spoof checking on, link-state auto, trust off
    vf 1 MAC 92:29:0c:e0:b3:ad, spoof checking on, link-state auto, trust off
    vf 2 MAC 22:89:24:b9:5c:04, spoof checking on, link-state auto, trust off
    vf 3 MAC fe:fc:6b:c6:04:d6, spoof checking on, link-state auto, trust off
    vf 4 MAC aa:c3:6d:1e:a4:b2, spoof checking on, link-state auto, trust off
    vf 5 MAC b6:9b:0e:2d:6e:3c, spoof checking on, link-state auto, trust off
    vf 6 MAC 36:6a:5f:42:d5:1a, spoof checking on, link-state auto, trust off
```

Note: virt-manager in F28 allows VirtualNetwork to be created with a selection of all the VFs belonging to a PF

**Comment by marusak** [comment]
This issue is closed due to inactivity.

We are sorry, but we won't be able to address this in any time soon.
If you are interested in helping us with the implementation, please comment here.
