### ISSUE TITLE
machines: escape arguments of virsh

### ISSUE THREAD

**Issue by mareklibra** [cockpit-project/cockpit#9623]
Escape shell script command arguments when calling `virsh` from `pkg/machines`.

VM names, storage pool names and others can consist of all characters as file-names do, means i.e. quotes, spaces, etc.

Related to `pkg/machines/libvirt.es6`.

Issue identified within #9166 .

**Comment by martinpitt** [comment]
This might be partially fixed with the move to libvirt-dbus, but there's still enough shell code to break this. I'd suggest to changing the existing test cases to sprinkle some spaces into the directories/file/storage poll names, which should point out where this fails.

**Comment by martinpitt** [comment]
I checked current pkg/machines/scripts/create_machine.sh and pkg/machines/scripts/install_machine.sh and most variables (in particular, `$VM_NAME`) are now properly quoted. But `$SOURCE`, `$STORAGE_POOL` etc. still are not, let's fix that.
