### ISSUE TITLE
Create docker image using Dockerfile

### ISSUE THREAD

**Issue by wiryonolau** [cockpit-project/cockpit#9661]
Hi is it possible to create docker image using Dockerfile in the UI?

**Comment by KKoukiou** [comment]
@wiryonolau hey, I am not the package developer but from just using it I see that there is not such option.
You can either pull some new image with the "Get new image" button, either you can of course build your image from Dockerfile locally and it will then appear in the images list.

@stefwalter  do you think this RFE would be useful to implement?

**Comment by martinpitt** [comment]
To be honest I don't like the idea much. Editing docker files and building containers involves good terminals and editors, and long textual outputs from `docker build`. For all of these a web UI is vastly inferior to a proper terminal. You could sink an infinite amount of effort into building a web UI for docker container *development*, but this isn't what Cockpit's goal is.

Also, indeed let's avoid new feature development in cockpit-docker, as this is going away.

For these reasons I close this, I hope you understand. Thanks!
