### ISSUE TITLE
machines: CPU type is null

### ISSUE THREAD

**Issue by qiyuann** [cockpit-project/cockpit#9679]
The vm's CPU Type is null:
![screenshot from 2018-07-18 15-07-05](https://user-images.githubusercontent.com/23047456/42865478-522dae52-8a9c-11e8-9980-cda4202ef299.png)

While in dumpxml, 
```  
 <cpu mode='custom' match='exact' check='full'>
    <model fallback='forbid'>Opteron_G3</model>
    <topology sockets='1' cores='1' threads='1'/>
    <feature policy='disable' name='monitor'/>
    <feature policy='require' name='x2apic'/>
    <feature policy='require' name='hypervisor'/>
    <feature policy='disable' name='rdtscp'/>
    <feature policy='disable' name='svm'/>
  </cpu>
```

Versions:
cockpit-machines-172-2.el7.x86_64
cockpit-system-154-3.el7.noarch
cockpit-154-3.el7.x86_64
cockpit-ws-154-3.el7.x86_64
cockpit-bridge-154-3.el7.x86_64
chrome-64.0.3282.119

**Comment by KKoukiou** [comment]
@yevmel Thanks for noticing this. I sent PR to fix this.

**Comment by qiyuann** [comment]
verified.
versions:
cockpit-machines-173-2.el7.x86_64
