### ISSUE TITLE
machines: Failed to create vm when not check "Immediately Start VM"

### ISSUE THREAD

**Issue by qiyuann** [cockpit-project/cockpit#9680]
Try to create a VM using the following configuration:

![screenshot from 2018-07-18 15-20-53](https://user-images.githubusercontent.com/23047456/42867553-8b4f6670-8aa2-11e8-8945-70e63063728e.png)

Do not check "Immediately Start VM", and click Install to start installation:

![screenshot from 2018-07-18 15-23-53](https://user-images.githubusercontent.com/23047456/42867718-fa3dbd16-8aa2-11e8-8576-eb0b5c9ce131.png)

There will pop up an error:

![screenshot from 2018-07-18 15-24-22](https://user-images.githubusercontent.com/23047456/42867936-89a1d262-8aa3-11e8-8ba6-a5e829803907.png)

Versions:
cockpit-machines-172-2.el7.x86_64
cockpit-system-154-3.el7.noarch
cockpit-154-3.el7.x86_64
cockpit-ws-154-3.el7.x86_64
cockpit-bridge-154-3.el7.x86_64
chrome-64.0.3282.119

**Comment by KKoukiou** [comment]
@qiyuann thanks for submitting the issue.
PR https://github.com/cockpit-project/cockpit/pull/9684 should fix this issue.

**Comment by qiyuann** [comment]
verified.
versions:
cockpit-machines-173-2.el7.x86_64
