### ISSUE TITLE
Generate trusted certificate on Fedora

### ISSUE THREAD

**Issue by abitrolly** [cockpit-project/cockpit#9705]
I feel not good entering my system credentials into the form on a non-protected web page. Is it possible to generate trusted certificate on installation for 127.0.0.1? At least on Fedora.

https://stackoverflow.com/questions/50788043/how-to-trust-self-signed-localhost-certificates-on-linux-chrome-and-firefox

**Comment by abitrolly** [comment]
Yes. Own protected certificate authority for local development, and `cockpit` as an example of good practice for that. Many websites require HTTPS to work correctly (loading resources etc.).

**Comment by jmalacho** [comment]
I do not understand your example.  In what world do you not trust the connection to 127.0.0.1

**Comment by abitrolly** [comment]
@jmalacho ignorance.

**Comment by martinpitt** [comment]
Note that if you have [sscg](https://github.com/sgallagher/sscg) installed (recommended by the Fedora cockpit package), it's at least not self-signed any more, but you can import the sscg CA into your browser or your system-wide trusted certificates.

If you already have your own trusted certificate, you can [tell cockpit-ws to use it](https://cockpit-project.org/guide/latest/https.html).

**Comment by martinpitt** [comment]
See the previous comment. sscg and using your own certificates are the two things that help with that; or joining a FreeIPA domain, in which case cockpit-ws will automatically use an IPA provided (trusted) SSL certificate.

Other than these three, nobody has had any good idea how to make this any easier. SSL certs are inherently hard :-/
