### ISSUE TITLE
RFE: storage - mdadm manage support

### ISSUE THREAD

**Issue by sghosh151** [cockpit-project/cockpit#9706]
Enhance to the current md raid management:
1 - remove faulty disk from raid set
2 - add new disk to raid set

quick ref for operations:
https://www.thomas-krenn.com/en/wiki/Mdadm_recovery_and_resync

**Comment by mvollmer** [comment]
Cockpit can do both 1 and 2 already, by executing `mdadm --remove` and `mdadm --add`.  Is that not enough?
