### ISSUE TITLE
test-httpstream fails with GnuTLS 3.6.3 (Rawhide, fedora-testing, rhel-x)

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9723]
This unit test started to fail on recent [Fedora rawhide builds](https://kojipkgs.fedoraproject.org//work/tasks/5040/28565040/build.log), it has also been observed in RHEL downstream:

```
./test-httpstream terminated with SIGABRT
FAIL: test-httpstream 7 /http-stream/tls/basic

FAIL: test-httpstream 12 /http-stream/tls/authority-good
cockpit-bridge-Message: 14:08:31.926: https://localhost:42005/test: couldn't read: Error performing TLS handshake: The operation was cancelled due to user error
**
cockpit-bridge:ERROR:src/bridge/test-httpstream.c:815:test_tls_authority_bad: Got unexpected message: https://localhost:42005/test: couldn't read: Error performing TLS handshake: The operation was cancelled due to user error instead of cockpit-bridge-Message: *Unacceptable TLS certificate:*untrusted-issuer*

FAIL: test-httpstream 13 /http-stream/tls/authority-bad
ERROR: test-httpstream process failed: 250
```

This is a GnuTLS 3.6.3 regression, filed as https://gitlab.com/gnutls/gnutls/issues/530

**Comment by martinpitt** [comment]
It's not a build issue. Building cockpit in a rawhide mock, running

    ./test-httpstream  -p /http-stream/tls/basic --verbose

in the mock fails with

    cockpit-bridge-Message: 22:31:35.046: https://localhost:41049/test: couldn't read: Error performing TLS handshake: The operation was cancelled due to user error

while it succeeds when I run that same binary on the  Fedora 28 host. `./test-httpstream` does not actually fork cockpit-bridge (according to strace), it apparently has the bridge code linked in.

glib-networking is the same in both environments (2.56.1-1), but F28 has gnutls 3.6.2-3 while Rawhide has 3.6.3-1. Testing that theory, on my host:

```
$ mkdir /tmp/lib
$ cp  `mock -r fedora-rawhide-x86_64 --print-root-path`/lib64/libgnutls* /tmp/lib
$ LD_LIBRARY_PATH=/tmp/lib ./test-httpstream  -p /http-stream/tls/basic --verbose
cockpit-bridge-Message: 22:41:11.526: https://localhost:44009/test: couldn't read: Error performing TLS handshake: The operation was cancelled due to user error
```

**Comment by martinpitt** [comment]
Running with `GNUTLS_DEBUG_LEVEL=10`, the log significantly starts to differ after this:
```
gnutls[4]: HSK[0x21a5130]: CERTIFICATE REQUEST (13) was received. Length 38[38], frag offset 0, frag length: 38, sequence: 0
gnutls[4]: EXT[0x21a5130]: rcvd signature algo (2.3) ECDSA-SHA1
```

With GnuTLS 3.6.3 (failing) I see
```
gnutls[3]: ASSERT: cert-cred.c[call_legacy_cert_cb1]:399
gnutls[3]: ASSERT: cert.c[call_get_cert_callback]:384
gnutls[3]: ASSERT: cert.c[_gnutls_proc_cert_cert_req]:886
gnutls[3]: ASSERT: handshake.c[handshake_client]:2889
(MSG: cockpit-bridge-MESSAGE: https://localhost:33935/test: couldn't read: Error performing TLS handshake: The operation was cancelled due to user error)
```
while on 3.6.2 I see
```
gnutls[3]: ASSERT: buffers.c[get_last_packet]:1157
gnutls[10]: READ: Got 5 bytes from 0xc9e1a0
gnutls[10]: READ: read 5 bytes from 0xc9e1a0
gnutls[10]: RB: Have 0 bytes into buffer. Adding 5 bytes.
gnutls[10]: RB: Requested 5 bytes
gnutls[5]: REC[0xca07e0]: SSL 3.3 Handshake packet received. Epoch 0, length: 4
[...]
gnutls[5]: REC[0xca07e0]: Decrypted Packet[4] Handshake(22) with length: 4
gnutls[4]: HSK[0xca07e0]: SERVER HELLO DONE (14) was received. Length 0[0], frag offset 0, frag length: 1, sequence: 0
gnutls[4]: HSK[0xca07e0]: CERTIFICATE was queued [7 bytes]
gnutls[4]: HSK[0xca07e0]: CLIENT KEY EXCHANGE was queued [37 bytes]
[...]
gnutls[5]: REC[0xca07e0]: Epoch #1 ready
gnutls[4]: HSK[0xca07e0]: Cipher Suite: GNUTLS_ECDHE_RSA_AES_256_GCM_SHA384
[...]
```

But I don't know how to interpret this. At this point I'd recommend:
 
 1. Run a git bisect of gnutls to find the relevant commit. The above provides a fully automatic test that can be done on a built tree, so this takes little human time. Maybe this will already tell us what's wrong.
 2. If that still doesn't work, create a minimal standalone reproducer and file a GnuTLS bug. We have good contacts to the authors, and they should be able to help us relatively fast.

**Comment by martinpitt** [comment]
3.6.3 changelog: https://lists.gnupg.org/pipermail/gnutls-devel/2018-July/008584.html

**Comment by martinpitt** [comment]
I manually tested the bridge with httpstream on my server (valid SSL cert) and the local cockpit port (self-signed, cannot validate), and it  works:
```
❱❱❱ ( printf '\n{ "command": "open", "channel": "c", "payload": "http-stream1", "method": "GET", "address": "piware.de", "port": 443, "path": "/tmp/firewall-usabilitytestsetup.txt",  "tls": {} }\n---\n\n{ "command": "done", "channel": "c" }\n---\n'; sleep 3 ) |  LD_LIBRARY_PATH=~/tmp ./cockpit-bridge --interact=---; 

c
{"status":200,"reason":"OK","headers":{"Last-Modified":"Wed, 14 Mar 2018 09:14:46 GMT","Content-Type":"text/plain","Server":"Apache/2.4.25 (Debian)","Vary":"Accept-Encoding","Accept-Ranges":"bytes","ETag":"\"1ce-5675bce6ff8fb\"","Date":"Wed, 25 Jul 2018 06:15:58 GMT"}}
---
c
#!/bin/bash
set -eux
dnf update -y
[... further content of https://piware.de/tmp/firewall-usabilitytestsetup.txt ]


❱❱❱ ( printf '\n{ "command": "open", "channel": "c", "payload": "http-stream1", "method": "GET", "port": 9090, "path": "/",  "tls": { "validate": true } }\n---\n'; sleep 3 ) |  LD_LIBRARY_PATH=~/tmp ./cockpit-bridge --interact=---; 

{"command":"ready","channel":"c"}
---
cockpit-bridge-Message: 08:18:16.548: https://localhost:9090/: Unacceptable TLS certificate: untrusted-issuer 
cockpit-bridge-Message: 08:18:16.548: https://localhost:9090/: couldn't read: Unacceptable TLS certificate

{"rejected-certificate":"-----BEGIN CERTIFICATE-----\nMIIEfDCCA[...]\n-----END CERTIFICATE-----\n","command":"close","channel":"c","problem":"unknown-hostkey"}
---
```

The bridge is really using the new library:
```
❱❱❱ grep tls /proc/`pgrep cockpit-bridge`/maps
7faed7641000-7faed7670000 r--p 00000000 00:38 86453845                   /home/martin/tmp/libgnutls.so.30
```

So GnuTLS 3.6.3 generally seems to work; we have that version on the rhel-x image and our integration tests succeed. So for now this just looks like a bug in our tests.

**Comment by martinpitt** [comment]
This can be reproduced easily by running a TLS server with our mock cert, and trying to read from it:

    gnutls-serv --x509keyfile src/bridge/mock-server.key --x509certfile src/bridge/mock-server.crt --port 9999

    ( printf '\n{ "command": "open", "channel": "c", "payload": "http-stream1", "method": "GET", "port": 9999, "path": "/",  "tls": {} }\n---\n\n{ "command": "done", "channel": "c" }\n---\n'; sleep 3 ) |  ./cockpit-bridge --interact=---

This works on Fedora 28, but when running this with `LD_LIBRARY_PATH=~/tmp` (where I put libgnutls from rawhide), it fails with the same error. Then the server says

    Error in handshake: Error in the pull function.

But

    LD_LIBRARY_PATH=~/tmp/ gnutls-cli --insecure --port 9999 localhost

against the same server works.

**Comment by martinpitt** [comment]
Some more observations:

 * Changing the certificate makes no difference.
 * If I let the server run with OpenSSL, it works!

        openssl s_server -cert src/bridge/mock-server.crt -key src/bridge/mock-server.key -port 9999

**Comment by martinpitt** [comment]
I wrote a standalone reproducer that uses glib-networking: https://piware.de/tmp/glib-networking-tls-9723.c

```
$ gnutls-serv --x509keyfile src/bridge/mock-server.key --x509certfile src/bridge/mock-server.crt --port 9999

$ gcc -g -O0 `pkg-config --cflags --libs gio-2.0` glib-networking-tls-9723.c && LD_LIBRARY_PATH=~/tmp ./a.out 
** Message: 09:02:49.110: successfully connected
**
ERROR:glib-networking-tls-9723.c:35:main: assertion failed (error == NULL): Error performing TLS handshake: The operation was cancelled due to user error (g-tls-error-quark, 1)
Aborted (core dumped)
```

If I run a.out against GnuTLS 3.6.2, i. e. drop the `LD_LIBRARY_PATH`, it works:
```
** Message: 09:06:42.858: successfully connected
HTTP/1.0 200 OK
Content-type: text/html


<HTML>[...]
```

**Comment by Gundersanne** [comment]
I ran a git bisect using test-httpstream and the following configure command:
```
./configure --enable-tls13-support --disable-static --disable-openssl-compatibility \
--disable-non-suiteb-curves --with-system-priority-file=/etc/crypto-policies/back-ends/gnutls.config \
--with-default-trust-store-pkcs11="pkcs11:" --with-trousers-lib=/lib64/libtspi.so.1 \
--enable-guile -with-unbound-root-key-file=/var/lib/unbound/root.key \
--enable-dane --disable-rpath --with-default-priority-string=@SYSTEM --disable-doc
```

It fails on 9829ef9a3ca06d60472599df7c74ebb9a53f1fe2

**Comment by Gundersanne** [comment]
gnutls's `6a7976` fixes the issue. @martinpitt what's the next step here?

**Comment by martinpitt** [comment]
@Gundersanne : I filed PR #9730 as a cowboy hack to do today's release. Otherwise we've done due diligence now: identified the regression and the fix, reported it upstream, and I also NACK'ed the [update to Fedora 28](https://bodhi.fedoraproject.org/updates/FEDORA-2018-26f3a541e6).

So next steps are to wait until the gnutls fix makes it into Fedora 28+rawhide+rhel-x, then revert #9730 again. That revert should then close this issue.

Thank you for your help!

**Comment by martinpitt** [comment]
rhel-x nightlies, rawhide, and fedora-testing should all have the fixed GnuTLS now, so we can refresh these two images and drop that hack. Or just wait until they auto-refresh.

**Comment by martinpitt** [comment]
rhel-x nightlies, rawhide, and fedora-testing should all have the fixed GnuTLS now, so we can refresh these two images and drop that hack. Or just wait until they auto-refresh.
