### ISSUE TITLE
Don't enable Add button without any disk being chosen

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#973]
When editing volume group, the Add button should be disabled if there is no disks chosen, also a warning should show up if there is no available disks.
![screenshot from 2014-08-05 14 31 51](https://cloud.githubusercontent.com/assets/3952545/3816516/580ae964-1ccf-11e4-87f5-9d3249c5b0e7.png)
![screenshot from 2014-08-05 14 29 55](https://cloud.githubusercontent.com/assets/3952545/3816523/5d2a9782-1ccf-11e4-94f9-ea463ee94d78.png)

**Comment by dperpeet** [comment]
This is done consistently with our design patterns now: The button is always enabled and an error with a hint is shown when the user tries to add without checking a disk first.

@andreasn Do we need a filler for when the list is empty?

**Comment by andreasn** [comment]
It would be a nice-to-have to make the button disabled until you select a checkbox, but it gives a warning now at least, and it didn't come up as a big issue in any of the usability testing we did on volume groups, so I'll go ahead and close this. We can open a new issue if it arises as a big issue in the future.

![screenshot from 2019-01-10 16-43-14](https://user-images.githubusercontent.com/209895/50979576-0ed79d80-14f7-11e9-956e-d419fe29265e.png)

**Comment by mvollmer** [comment]
> It would be a nice-to-have to make the button disabled until you select a checkbox

I think we consciously don't use this pattern in dialogs.  We decided to let the user freely fill out the dialog and only give feedback on invalid input when he/she clicks "Apply".

(Let's document this if it isn't already.)

**Comment by andreasn** [comment]
Ah, right!
