### ISSUE TITLE
Accounts: adding a user does not create home dir in Debian

### ISSUE THREAD

**Issue by blade1989** [cockpit-project/cockpit#9744]
The "Create a new Account" page should have an option to also create the user dir in /home/

Right now when I create an account I cant see the username in the /home/ directory, that is usually created from using the `adduser` command.

On top of that, could al of the options of `adduser` be implemented in the Accounts page?:

       --conf FILE
       --disabled-login
       --disabled-password
       --force-badname
       --gecos GECOS
       --gid ID
       --group
       --help Display brief instructions.
       --home DIR
       --shell SHELL
       --ingroup GROUP
       --no-create-home
       --quiet
       --debug
       --system
       --uid ID
       --firstuid ID
       --lastuid ID
       --add_extra_groups

- Ubuntu 18.04.1
- Cockpit version 164.

**Comment by blade1989** [comment]
Whats the status of this?

**Comment by martinpitt** [comment]
adduser (and hence Cockpit) *does* create home directories by default. Do you perhaps have some custom /etc/adduser.conf configuration which would disable this?

As for the options, these are already implemented in the UI: Disabled login / password, GECOS, and "admin or not" (so a limited --group).

Some of them like --debug don't make much sense. The others are rather rare - they could be implemented under a "More options" expander in the dialog, but that isn't currently planned. Contributions are appreciated, of course :)

**Comment by blade1989** [comment]
I added an "Account" via Cockpit called cdir, I see it in the Cockpit, and also in the passwd file, but the dir was not created in /home/?

I added another user with the 'adduser' command, and I see that `adduser` did create a dir in the /home/ directory...

Seems like this is a Cockpit thing??


This is my adduser.conf:

```
DSHELL=/bin/bash
DHOME=/home
GROUPHOMES=no
LETTERHOMES=no
SKEL=/etc/skel
FIRST_SYSTEM_UID=100
LAST_SYSTEM_UID=999
FIRST_SYSTEM_GID=100
LAST_SYSTEM_GID=999
FIRST_UID=1000
LAST_UID=59999
FIRST_GID=1000
LAST_GID=59999
USERGROUPS=yes
USERS_GID=100
DIR_MODE=0755
SETGID_HOME=no
QUOTAUSER=""
SKEL_IGNORE_REGEX="dpkg-(old|new|dist|save)"
```

**Comment by martinpitt** [comment]
Cockpit doesn't actually call `adduser` (which is a Debianism), but `useradd` (which is an LSB standard). On Fedora, `useradd -s /bin/bash -c 'Test' foo` does create the  home directory, but in Debian unstable it doesn't. I think we should add `--create-home` which works everywhere.

**Comment by RHuehne** [comment]
there is also still the issue that on debian systems the /etc/default/useradd file is ignored. So there is no possibility to provide custom defaults for users created by cockpit.

**Comment by gavD** [comment]
Hello, I'm using:
- Ubuntu 18.04
- Cockpit 164-1

I have tried:
- modifying /etc/useradd.conf and adding EXTRA_GROUPS
- modifying /etc/default/useradd and setting skel
    - /etc/skel has a bunch of files in it

Observed results:
1. Neither the groups nor the skel stuff got set in the

**Comment by martinpitt** [comment]
@gavD : This was fixed in version 185. I suggest to install cockpit from bionic-backports to get a more recent version.

**Comment by gavD** [comment]
This works! thank you @martinpitt  :-) 

(may be worth updating the install docs on the wiki to mention the availability of backports?)
