### ISSUE TITLE
Firewall: ERROR: COMMAND_FAILED

### ISSUE THREAD

**Issue by blade1989** [cockpit-project/cockpit#9765]
When adding a Service in the Cockpit firewall, I get a 'COMMAND_FAILED' error message.

I reviewed the `firewalld.log` and found the following:

```
WARNING: '/usr/sbin/iptables-restore --wait=2 -n' failed: iptables-restore: line 2 failed

ERROR: COMMAND_FAILED
```

 - CentOS Linux 7
 - Cockpit Version 169

**Comment by martinpitt** [comment]
This seems to be a [common problem](https://www.google.com/search?q=iptables-restore%3A+line+2+failed&ie=utf-8&oe=utf-8&client=firefox-b-ab). Please report it against firewalld in the CentOS bug tracker.

**Comment by blade1989** [comment]
Thanks! had a firewall tool installed from ages ago that I completely forgot about. Removed and now it works again.
