### ISSUE TITLE
machines-ovirt: [RFE] Should pop the waning while supending the HostedEngine VM.

### ISSUE THREAD

**Issue by kenzhaoyihui** [cockpit-project/cockpit#9778]
Description of problem:
Should pop the warning while supending the HostedEngine VM. Because the HostedEngine VM as the VM which install the engine on the host. So this VM is not managed by the engine. When supending the HostedEngine VM on the cockpit, there is no response, but from the console, it gives the error:
"""
HTTP POST failed: "{\n  \"async\" : \"false\",\n  \"fault\" : {\n    \"detail\" : \"[Cannot hibernate VM. This VM is not managed by the engine.]\",\n    \"reason\" : \"Operation Failed\"\n  },\n  \"status\" : \"failed\"\n}" /ovirt-engine/api/vms/f5455c3b-7a3b-41b9-8866-a92c2c669f70/suspend
ovirt.js:4518 handleOvirtError, error =  {
  "async" : "false",
  "fault" : {
    "detail" : "[Cannot hibernate VM. This VM is not managed by the engine.]",
    "reason" : "Operation Failed"
  },
  "status" : "failed"
} exception =  HttpError {status: 400, reason: "Bad Request", message: "Bad Request", problem: null, valueOf: ƒ, …}
"""

So, I think it is good idea to pop the warning on the cockpit while supending the HostedEngine VM

Version-Release number of selected component (if applicable):
RHEL-7.5-20180322.0
cockpit-machines-ovirt-172-2.el7.noarch

How reproducible:
100%

Steps to Reproduce:
The same as the description.

Expected results:

Additional info:

**Comment by KKoukiou** [comment]
@kenzhaoyihui unfortunately cockpit-machines-ovirt plugin is not being developed any more. See release notes from 187 release https://cockpit-project.org/blog/cockpit-187.html
I will close this issue since it's not relevant any more.
