### ISSUE TITLE
Long name of volume group out of dialog title area  

### ISSUE THREAD

**Issue by porscheyin** [cockpit-project/cockpit#979]
This is a legal name of volume group with maximum number of characters, but it is not showed properly, Should we talk about this ? @andreasn  @stefwalter 
![screenshot from 2014-08-06 12 17 44](https://cloud.githubusercontent.com/assets/3952545/3830306/eb30adb4-1d88-11e4-8ddf-dd4ca0dcbd4b.png)

**Comment by dperpeet** [comment]
similiar to #980 ?
