### ISSUE TITLE
Upgrade cockpit on Ubuntu

### ISSUE THREAD

**Issue by Discusal** [cockpit-project/cockpit#9795]
Hello,

I'm using Ubuntu 18.04 and installed cockpit from package but when i try to upgrade them, it says still are on version 164-1

¿How can i upgrade them to the last release?

**Comment by Discusal** [comment]
Ok i figure out by installing from backports: 

` sudo apt install cockpit/bionic-backports`

Version 172-1

**Comment by luixal** [comment]
Just got here trying to figure out why `apt-cache policy cockpit` was showing two versions available (198 and 164) but the older was being used. So, for anyone in my situation:

As far as I've read, Ubuntu Server (18.04 in my case) has backports enabled by default, but it keeps using other repos by default. If you want to use backports by default, you need to edit (create in my case) a file at `/etc/apt/preferences` with this content:

```
Package: *
Pin: release a=<release>-backports
Pin-Priority: 500  
```

[Original and Full info here](https://askubuntu.com/questions/25717/how-do-i-enable-the-backports-repository)

**Comment by FredericLatour** [comment]
For those trying to find a solution, have a look at this issue: #12668

**Comment by shahidkarimi** [comment]
Nothing works, it seems its not possible

**Comment by martinpitt** [comment]
@marvindanig : Seems you need to enable backports on your system: https://help.ubuntu.com/community/UbuntuBackports

(They are normally enabled by default)
