### ISSUE TITLE
Debian Timelines

### ISSUE THREAD

**Issue by Twiggled** [cockpit-project/cockpit#9797]
I know its hard to say and this is not exactly the correct place to post this but I have tried everywhere else.
Does anyone have a rough idea on cockpit 173-1 or 174-1 for debian stretch on the backport repository.
One of the key things we need is the vd0 ability on VMs.
Great job by the way only been using cockpit for a few weeks and it is far better than any of the other solutions I have used. Thanks for all the hard work and if there is anyway we can help please let us know.
Thanks
Paul

**Comment by mvollmer** [comment]
> One of the key things we need is the vd0 ability on VMs.

Do you have the rest of VDO already, such as the "vdo" command line
client?  Without those, Cockpit wont give you any VDO management,
unfortunately.

I don't think VDO is available on Debian, although there should be
nothing fundamental that would prevent someone from including it.

> Great job by the way only been using cockpit for a few weeks and it is
> far better than any of the other solutions I have used. Thanks for all
> the hard work and if there is anyway we can help please let us know.

Thanks!  Any kind of feedback is greatly appreciated!

**Comment by Twiggled** [comment]
We have everything setup in debian and I can create a VD0 Volume in the console using virsh to set them up.
But this will be difficult for some staff and I want to allow them to add and increase the volumes.

I know all this is working in the 173-1 release as I have it on a test system. Was just looking to see if anyone can give me an eta for the backport release.

Also we are having some issues with VM's If we do not start it immediately it will not start. Is this because the ISO we are using. The error seems to be incomplete.

Thanks
Paul

**Comment by martinpitt** [comment]
debian-backports currently has version 180 for stretch. I'll update it to 186 in two weeks, but this should be new enough for your requirements in the description.
