### ISSUE TITLE
Dialog bodies should scroll automatically without breaking dropdowns

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#9843]
We would like to CSS luke this

```
#cockpit_modal_dialog .modal-body {
    max-height: calc(75vh - 10rem);
    overflow: auto;
}
```

so that the footer of the dialog doesn't fall off the screen when the dialog gets too tall.

Unfortunately, this breaks dropdowns in the dialog.  If a dropdown would ordinarily extend past the dialog body, it will now be clipped and the body starts scrolling (even if there is enough space on the page to show the whole dropdown):

![dialog-scroll](https://user-images.githubusercontent.com/3228183/44192869-b368d580-a139-11e8-8c7f-e1b111650d87.png)

We should find a way to make this work naturally: dropdowns should be able to overflow the dialog body.

**Comment by martinpitt** [comment]
The dialogs were changed to ct-form-layout in the meantime, but supposedly that doesn't affect the scrolling issue. This calls  for some higher-order CSS magic, something for @garrett?

**Comment by garrett** [comment]
Yep, if I can finalize and implement native dropdowns that look like PF dropdowns, then it would fix this issue.

**Comment by garrett** [comment]
I've been playing around with styling native dropdowns; here's an experiment on what's possible: https://codepen.io/garrett/pen/jdEoxe

It's not pixel-perfect to PatternFly (except the dropdown icon), but somewhat close-ish.

**Comment by garrett** [comment]
Initial PR for native dropdowns is now @ #11155. Using native dropdowns would fix popping up outside a scrollable area and also happen to improve keyboard interaction and a11y in general.

(As of this writing, the CSS still needs to be added for them to look similar to our dropdowns. I'll adapt the CSS @ the codepen above and make it pixel-perfect, then include it in the PR.)

**Comment by KKoukiou** [comment]
We are already using native dropdowns almost everywhere.
Let's not keep this issue open anymore.
