### ISSUE TITLE
machines-ovirt: Add disk function doesn't work.

### ISSUE THREAD

**Issue by kenzhaoyihui** [cockpit-project/cockpit#9845]
Description of problem:
Add disk function doesn't work for cockpit-machines-ovirt.

![add_disk](https://user-images.githubusercontent.com/18360375/44198551-54748200-a174-11e8-8f4b-99aa1f8d5ad1.png)

Version-Release number of selected component (if applicable):
RHEL-7.6-20180814.0
cockpit-machines-ovirt-173-3.el7.noarch

How reproducible:
100%

Steps to Reproduce:
The same as the description.

Expected results:
Should work as this:
https://cockpit-project.org/blog/cockpit-173.html

Additional info:

**Comment by michalskrivanek** [comment]
@bond95 can you take a look why?

**Comment by mareklibra** [comment]
@kenzhaoyihui , thanks for reporting that.
From the screenshot: I don't see disk listing in the background. The "Add Disk" action should be available from there only. Looks like (just suspicion) the dialog appeared after "Create VM" action.

Can you please provide steps to reproduce?

Anyway - the "Add Disk feature" has not been implemented for oVirt  yet.
It should be either disabled (@bond95 , see provider specific components for disk listings) or implemented (should be easy).
