### ISSUE TITLE
rsa keys activation

### ISSUE THREAD

**Issue by gamblecrack** [cockpit-project/cockpit#9847]
At Cockpit, I can add rsa keys to log in to other servers. But I have to activate this manually. Is there a way to leave them activated?

**Comment by KKoukiou** [comment]
@gamblecrack sorry for late reply.
Here are the docs relevant to authentication, https://cockpit-project.org/guide/133/authentication.html
As written there the public key you wish to use must be present in ~/.ssh/authorized_keys in the target server. And you have to do that manually.
I am not sure what you mean by 'leave them activated' though.

**Comment by martinpitt** [comment]
@gamblecrack (CC @KKoukiou ): This is about the "Authentication" dialog in the  user menu, not the ssh config files.

Indeed you have to activate them every time you log into Cockpit. It's the equivalent of typing your password into the gnome keyring dialog after logging into your GNOME session - and this really can't persist, as we don't want to write the unencrypted SSH key anywhere on the disk.
