### ISSUE TITLE
Historical cockpit

### ISSUE THREAD

**Issue by guilhermetb** [cockpit-project/cockpit#9853]
good evening
When I access the cockpit it starts to monitor from that moment on
I wonder if there is any way to activate a history of 12 hours, so when access could see the status of the machines in the last 12 hours

**Comment by leomoty** [comment]
Hello @guilhermetb, you need to install `cockpit-pcp` package, which uses https://pcp.io/ to store data regarding your system. Since cockpit 172 (see the blog https://cockpit-project.org/blog/cockpit-172.html), it offers the installation on the system tab.

**Comment by guilhermetb** [comment]
Hi, thanks for the tip
I installed the pcp packages but the cockpit still does not store

dpkg -l | grep pcp
ii  libpcp-gui2                       4.1.1-1                        amd64        Performance Co-Pilot graphical client tools library
ii  libpcp-import1                    4.1.1-1                        amd64        Performance Co-Pilot data import library
ii  libpcp-mmv1                       4.1.1-1                        amd64        Performance Co-Pilot Memory Mapped Value client library
ii  libpcp-pmda-perl                  4.1.1-1                        amd64        Performance Co-Pilot Domain Agent Perl module
ii  libpcp-pmda3                      4.1.1-1                        amd64        Performance Co-Pilot Domain Agent library
ii  libpcp-trace2                     4.1.1-1                        amd64        Performance Co-Pilot application tracing library
ii  libpcp-web1                       4.1.1-1                        amd64        Performance Co-Pilot data import library
ii  libpcp3                           4.1.1-1                        amd64        Performance Co-Pilot library
ii  pcp                               4.1.1-1                        amd64        System level performance monitoring and performance management
ii  pcp-conf                          4.1.1-1                        amd64        Performance Co-Pilot runtime configuration
ii  python3-pcp                       4.1.1-1                        amd64        Performance Co-Pilot Python3 PMAPI module

**Comment by guilhermetb** [comment]
![image](https://user-images.githubusercontent.com/29417098/44303019-4bb6b400-a30c-11e8-9bc7-ffdcdc5d929b.png)

**Comment by guilhermetb** [comment]
dpkg -l | grep cockpit
ii  cockpit                           172-1~bpo9+1                   all          User interface for Linux servers
ii  cockpit-bridge                    172-1~bpo9+1                   amd64        Cockpit bridge server-side component
ii  cockpit-dashboard                 172-1~bpo9+1                   all          Cockpit remote servers and dashboard
ii  cockpit-networkmanager            172-1~bpo9+1                   all          Cockpit user interface for networking
ii  cockpit-storaged                  172-1~bpo9+1                   all          Cockpit user interface for storage
ii  cockpit-system                    172-1~bpo9+1                   all          Cockpit admin interface for a system
ii  cockpit-ws                        172-1~bpo9+1                   amd64        Cockpit Web Service

**Comment by guilhermetb** [comment]
I added the repository

/etc/apt/sources.list.d/backports.list
deb http://deb.debian.org/debian stretch-backports main

/etc/apt/sources.list
deb https://dl.bintray.com/pcp/stretch stretch main

Through apt-get the version 172-1~bpo9+1 is installed
This way the cockpit-pcp was not installed.

I downloaded the package cockpit-pcp_174-1_amd64.deb and it is now working properly.

**Comment by guilhermetb** [comment]
@leomoty Thanks for your help

**Comment by larskarlitski** [comment]
Closing, this seems to be resolved. Thanks @leomoty.
