### ISSUE TITLE
http-stream2's "connection" parameter is confusing

### ISSUE THREAD

**Issue by larskarlitski** [cockpit-project/cockpit#9862]
http-stream2 has a `connection` parameter. It is documented in [doc/protocol.md](https://github.com/cockpit-project/cockpit/blob/master/doc/protocol.md#L730) as a "stable connection identifier" and in [doc/guide/cockpit-http.xml](https://github.com/cockpit-project/cockpit/blob/master/doc/guide/cockpit-http.xml#L32) as "A connection identifier. Subsequent channel requests with the same identifier will try to use the same connection if it is still open".

However, this is only true when there's no pending request on that connection. If there is, Cockpit opens a second connection with the same identifier. The connection with the request that returns last is kept open, all others are closed.

This makes it hard to implement a client that never opens more than a specified number of connections to a server. Cockpit could help a lot if it queued requests on a named connection. Alternatively, it could return an error if a connection name is used when a request is still running on a connection with that name.

Cockpit could also handle connection pooling itself. `cockpit.http` feels high-level enough for such a feature.

At the least, we should document this parameter more clearly.

Noticed this in weldr-web, which opens a lot of connections on startup.

**Comment by martinpitt** [comment]
No progress on this in 5 years, and our new python bridge doesn't even implement connection sharing as nothing actually uses it. Not even cockpit-composer.
