### ISSUE TITLE
IP Port forwarding

### ISSUE THREAD

**Issue by Twiggled** [cockpit-project/cockpit#9879]
This may have been answered but I have looked. 
Cockpit 172-1 on Debian 9 with firewalld and KVM/Qemu installed.
Basically I have 5 IP addresses from my provider. I am trying to port forward specific IP addresses and ports to specific VM's I have setup. I can not seem to find a way to do this in Cockpit. Am I missing something or is this a feature that does not excist in Cockpit.
Any guidance really appreciated.

Thanks for all the help. And great work loving Cockpit.

**Comment by martinpitt** [comment]
Cockpit's Machines (or Networking) page currently only shows the configured network devices of the VM, there isn't functionality to add/remove them.

As for fowarding particular host IPs to VM network devices, this needs to be done with creating bridges on the host for the VMs, and setting up routing between the external IPs and the bridges (I think -- maybe libvirt has some functionality which sets that up). The Networking page can do some of this (like creating a bridge and adding members to it).

But not all of the required steps exist in  cockpit, so you didn't miss anything.

**Comment by Twiggled** [comment]
Thanks Martin for the answer. Found the documentation for KVM and Firewalld so lacking it has taken weeks to get anything close to working but I think this is the final key of the puzzle. I probably missed a step trying to do it all in cockpit. Hope all is going well and thanks for the reply.
