### ISSUE TITLE
Graph 1 half day generated

### ISSUE THREAD

**Issue by guilhermetb** [cockpit-project/cockpit#9881]
Good afternoon,
I configured the cockpit on my server and am using it together with PCP
The graphs are being generated correctly when I select period of 6 hours but when I choose period of 1 day the graph is generated only half.
I need help solving this problem.

root@vmi198825:/etc/mail# dpkg -l | grep cockpit
ii  cockpit                           172-1~bpo9+1                   all          User interface for Linux servers
ii  cockpit-bridge                    172-1~bpo9+1                   amd64        Cockpit bridge server-side component
ii  cockpit-dashboard                 172-1~bpo9+1                   all          Cockpit remote servers and dashboard
ii  cockpit-networkmanager            172-1~bpo9+1                   all          Cockpit user interface for networking
ii  cockpit-pcp                       174-1                          amd64        Cockpit PCP integration
ii  cockpit-storaged                  172-1~bpo9+1                   all          Cockpit user interface for storage
ii  cockpit-system                    172-1~bpo9+1                   all          Cockpit admin interface for a system
ii  cockpit-ws                        172-1~bpo9+1                   amd64        Cockpit Web Service
root@vmi198825:/etc/mail# dpkg -l | grep pcp
ii  cockpit-pcp                       174-1                          amd64        Cockpit PCP integration
ii  libpcp-gui2                       4.1.1-1                        amd64        Performance Co-Pilot graphical client tools library
ii  libpcp-import1                    4.1.1-1                        amd64        Performance Co-Pilot data import library
ii  libpcp-mmv1                       4.1.1-1                        amd64        Performance Co-Pilot Memory Mapped Value client library
ii  libpcp-pmda-perl                  4.1.1-1                        amd64        Performance Co-Pilot Domain Agent Perl module
ii  libpcp-pmda3                      4.1.1-1                        amd64        Performance Co-Pilot Domain Agent library
ii  libpcp-trace2                     4.1.1-1                        amd64        Performance Co-Pilot application tracing library
ii  libpcp-web1                       4.1.1-1                        amd64        Performance Co-Pilot data import library
ii  libpcp3                           4.1.1-1                        amd64        Performance Co-Pilot library
ii  pcp                               4.1.1-1                        amd64        System level performance monitoring and performance management
ii  pcp-conf                          4.1.1-1                        amd64        Performance Co-Pilot runtime configuration
ii  python3-pcp                       4.1.1-1                        amd64        Performance Co-Pilot Python3 PMAPI module

![image](https://user-images.githubusercontent.com/29417098/44416581-a426c500-a549-11e8-97dd-4afe19c79c9f.png)

**Comment by leomoty** [comment]
It is not exactly "half day", it seems to open the current pcp logging file (which is archived daily?), I tested on my system and I have the same behavior.

**Comment by guilhermetb** [comment]
When I choose time "1 day" it should show the history of a period of 24 hours in this case considering that today is day 21 the metric should be 20-08-2018 to 21-08-2018 but it shows at the beginning of the graph the time current and the rest of the blank graphic.

root@vmi198825:/var/log/pcp/pmlogger/vmi198825.contaboserver.net#  pcp -h localhost
Performance Co-Pilot configuration on vmi198825.contaboserver.net:
 platform: Linux vmi198825.contaboserver.net 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64
 hardware: 4 cpus, 1 disk, 1 node, 12019MB RAM
 timezone: -03+3
 services: pmcd pmproxy
     pmcd: Version 4.1.1-1, 8 agents, 4 clients
     pmda: root pmcd proc xfs linux mmv kvm jbd2
 pmlogger: primary logger: /var/log/pcp/pmlogger/vmi198825.contaboserver.net/20180821.15.27
     pmie: vmi198825.contaboserver.net: /var/log/pcp/pmie/vmi198825.contaboserver.net/pmie.log
root@vmi198825:/var/log/pcp/pmlogger/vmi198825.contaboserver.net# cat /var/log/pcp/pmie/vmi198825.contaboserver.net/pmie.log
Log for pmie on vmi198825.contaboserver.net started Tue Aug 21 15:27:10 2018

pmie: PID = 2033, via local:

root@vmi198825:/var/log/pcp/pmlogger/vmi198825.contaboserver.net# ls -lt
total 4924
-rw-r--r-- 1 pcp pcp 1821736 Aug 21 16:28 20180821.15.27.0
-rw-r--r-- 1 pcp pcp     652 Aug 21 16:27 20180821.15.27.index
-rw-r--r-- 1 pcp pcp  223276 Aug 21 16:27 20180821.15.27.meta
-rw-r--r-- 1 pcp pcp     241 Aug 21 15:27 Latest
-rw-r--r-- 1 pcp pcp   24291 Aug 21 15:27 pmlogger.log
-rw-r--r-- 1 pcp pcp    6192 Aug 21 15:26 20180821.00.10.index
-rw-r--r-- 1 pcp pcp   24366 Aug 21 15:26 pmlogger.log.prior
-rw-r--r-- 1 pcp pcp  578740 Aug 21 15:26 20180821.00.10.0.xz
-rw-r--r-- 1 pcp pcp   45068 Aug 21 15:25 20180821.00.10.meta.xz
-rw-r--r-- 1 pcp pcp  903316 Aug 21 00:10 20180820.0.xz
-rw-r--r-- 1 pcp pcp    9772 Aug 21 00:10 20180820.index
-rw-r--r-- 1 pcp pcp   50136 Aug 21 00:05 20180820.meta.xz
-rw-r--r-- 1 pcp pcp  909264 Aug 20 00:10 20180819.0.xz
-rw-r--r-- 1 pcp pcp    9672 Aug 20 00:10 20180819.index
-rw-r--r-- 1 pcp pcp   50656 Aug 20 00:05 20180819.meta.xz
-rw-r--r-- 1 pcp pcp  289616 Aug 19 00:10 20180818.0.xz
-rw-r--r-- 1 pcp pcp    3592 Aug 19 00:10 20180818.index
-rw-r--r-- 1 pcp pcp   49460 Aug 19 00:10 20180818.meta.xz
root@vmi198825:/var/log/pcp/pmlogger/vmi198825.contaboserver.net#

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
