### ISSUE TITLE
Cockpit 176 segfaults on fedora rawhide

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#9889]
`cockpit_ssh_relay_finalize` fails:

https://kojipkgs.fedoraproject.org//work/tasks/6764/29226764/build.log

**Comment by martinpitt** [comment]
Seems to work in Fedora 28: https://koji.fedoraproject.org/koji/taskinfo?taskID=29227796

So presumably some new libssh/glib/glibc change. Next step is to reproduce this in a rawhide mock, and bisect the package differences.

**Comment by Gundersanne** [comment]
Small update:

So what fails specifically is `explicit_bzero(kbd->answers[i], strlen(kbd->answers[i]));` in libssh `src/auth.c:1240`.

This only happens when doing interactive keyboard auth, one of the kbd->answers[i] ends up being null (a NULL check before doing `explicit_bzero` mitigates the crash).

**Comment by Gundersanne** [comment]
The error occurs when doing a multi-step interactive auth, whereby the second (or more) `ssh_userauth_kbdint_setanswer` isn't called. The tests that fail don't include the `x-conversation <id>` header, as a result `answer` in the following segment ends up being `NULL` and `ssh_userauth_kbdint_setanswer` never gets called:

```
static int
do_interactive_auth (CockpitSshData *data)
...
answer = prompt_with_authorize (data, prompt, msg, NULL, NULL, echo != '\0');
if (answer)
    status = ssh_userauth_kbdint_setanswer (data->session, i, answer);
else
     rc = SSH_AUTH_ERROR;
...
```

Because libssh allocates space for all the answers the first time `ssh_userauth_kbdint_setanswer` gets called, calling `ssh_free(session)` which later results in zeroing of the answers results in segfault when not having set all the answers: 

```
int ssh_userauth_kbdint_setanswer(ssh_session session, unsigned int i,
    const char *answer) {
...
if (session->kbdint->answers == NULL) {
    session->kbdint->answers = calloc(session->kbdint->nprompts, sizeof(char *));
...
```

Either calling `realloc` each time a new answer comes in and only zeroing the answers that have actually been answered works. Or more simply just introduce a null check before zeroing the answer to make sure the answer has actually been set.

**Comment by Gundersanne** [comment]
In conclusion I do think we should be calling `ssh_userauth_kbdint_setanswer` from within cockpit, as it's sort of implied from this line in the libssh doc that we can't really break off the whole "setanswering" process after we've started it.

> The server can send an empty question set (this is the default behavior on my system) after you have sent the answers to the first questions. You must still parse the answer, it might contain some message from the server saying hello or such things. Just call ssh_userauth_kbdint() until needed.

Another question is if the data retrieved from the user via prompt which cockpit-ssh receives and forwards to sshd should be `NULL` or just `""` when the `x-conversation <id>` header isn't present as in the failing test cases.

**Comment by Gundersanne** [comment]
Just to be sure made a ticket at libssh as well: https://bugs.libssh.org/T96

**Comment by martinpitt** [comment]
Closing this, as it was fixed on the libssh side.
