### ISSUE TITLE
Cockpit Storaged does not refresh after raid grow

### ISSUE THREAD

**Issue by emad-ramlawi** [cockpit-project/cockpit#9890]
![2018-08-22 18_53_19-storage - fedora docker](https://user-images.githubusercontent.com/42615994/44475033-b5043300-a63c-11e8-8fd0-c54bfe1d3f57.png)

This can be easily reproducted

I create RAID array with 3 disks for example RAID 0

then I grow it with an additional disk

mdadm --grow /dev/md/RAID_0 --add /dev/sdd --raid-devices=4 --level=0
![2018-08-22 18_54_32-storage - fedora docker](https://user-images.githubusercontent.com/42615994/44475085-d2390180-a63c-11e8-8188-a0b2572a3f0f.png)

It reflects the changes in terminal using
mdadm --detail /dev/md/RAID_0

but not cockpit

I tried restarting the service = systemctl restart cockpit
no luck
I trick incognito as well

I have to reboot the whole server for cockpit web to catch the latest correct sizes, can you check this ?

Also can you tell me how to restart cockpit effectively and delete it is cached values/folder if possible

**Comment by emad-ramlawi** [comment]
Also notice the newly added drive shows as recovering

**Comment by emad-ramlawi** [comment]
And thanks for your hard work and amazing project, truly this is what was missing from the Linux world, I know sometimes find useful services and ideas from cockpit applications.

**Comment by mvollmer** [comment]
> Also can you tell me how to restart cockpit effectively and delete it is cached values/folder if possible

In this case, you can try restarting the storage API daemon, udisks2: `systemctl restart udisks2`. You probably also need to reload the page.

**Comment by mvollmer** [comment]
I have filed https://github.com/storaged-project/udisks/issues/613 to track the root cause of this. I don't think we need any change in Cockpit itself.
