### ISSUE TITLE
machines-ovirt: Don't show the VMs from the cockpit while adding the host to engine with ip.

### ISSUE THREAD

**Issue by kenzhaoyihui** [cockpit-project/cockpit#9896]
Description of problem:
Don't show the VMs from the cockpit while adding the host to engine with ip.
When adding the host to engine with ip, cockpit cannot show the VMs. Some error pop from javascript console.
![cockpit-console](https://user-images.githubusercontent.com/18360375/44536397-f1b05700-a72e-11e8-8d58-dec2ef3cc129.png)

When ovirt use the TLS-enable libvirt connection URI, and the auto calculated libvirt URI is as follows: qemu+tls://${hostName}/systemand ,  add host to engine with ip, it cannot show VMs.

Version-Release number of selected component (if applicable):
RHEL-7.6-20180814.0
cockpit-machines-ovirt-173-3.el7.noarch(cockpit-machines-ovirt>=170)

How reproducible:
100%

Steps to Reproduce:
The same as the description.

Expected results:
Should show VMs from the cockpit

Additional info:
Workaround 
1. add the host to engine with hostname
2. change the host hostname to ip address, but it is not a correct method. So should be fixed on future build.

**Comment by marusak** [comment]
ovirt plugin is not maintained in upstream anymore. If this issue is still valid and you want to get it fixed, please open downstream (bugzilla) bug.
