### ISSUE TITLE
How to manage multiple machines through cockpit?

### ISSUE THREAD

**Issue by ping035627** [cockpit-project/cockpit#9922]
I want to access all the machines in the LAN through cockpit, how to manage multiple machines through cockpit?

**Comment by ping035627** [comment]
@sweise17, All the machines are in a local area network, only one machine can communicate with the outside network. I want to provide the function of Web terminal through this machine. Can this function be implemented through cockpit? Thanks.

**Comment by sweise17** [comment]
As I understand it, the server you want to manage must be accessible from where you call the web interface. I can try this with a virtual machine for you if it is as possible as you imagine. But it would be the same principle.

Server 1: SSH Port 22 Public Webinterface
Server 2: SSH Port 23 (Added to the Webinterface)
Server 3: SSH Port 24 (Added to the Webinterface)

I'll try it out at home later.

**Comment by martinpitt** [comment]
@ping035627 , yes, this is a common use case and supported by Cockpit. You pick one machine with the appropriate network access where you install the web service (cockpit-ws) and Dashboard (cockpit-dashboard), then you can add your other machines there. These will then get accessed from the first machine via ssh, and they don't need the web server installed. 

If you want to do this programmatically, https://cockpit-project.org/guide/latest/feature-machines.html describes where this configuration is stored.
