### ISSUE TITLE
fix avocado test on edge

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#9925]
Currently `test80ChangeTabTools` doesn't run completely on the `edge` tests. This was intended and merged in #9624 but should still be fixed.

**Comment by marusak** [comment]
`*ChangeTabTools` test does not exist. Is this still actual @Gundersanne ?

**Comment by Gundersanne** [comment]
@marusak I don't think it is, this is when the selenium test was a lot smaller. I'll close it.
