### ISSUE TITLE
packagekit: Hard to identify the security level on Software Updates page

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#9934]
It's hard to tell the exact security level of a security update, unless you either learn the icon by heart, or if you expand the column. Needs to be spelled out, either as a label or as a tooltip.

**Comment by andreasn** [comment]
See the middle image here:

[!](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/software-updates/software-updates-security-levels.png)

**Comment by martinpitt** [comment]
Is that actually a problem? If you are only interested in a cursory glance, like "do I have pending security updates?", then you won't (or shouldn't) make a decision based on guessees and icons. If you want to know the details, you need to open the expander anyway.

I'm a bit afraid of making the table even more crowded than it is already -- the columns already fight over space.

**Comment by andreasn** [comment]
So what I had in mind was only a tooltip.
