### ISSUE TITLE
images: fix cirros image or replace it with different one

### ISSUE THREAD

**Issue by Antique** [cockpit-project/cockpit#9935]
check-machines uses cirros image to boot a guest but it takes long time because that image is waiting to connect to some specific server which is not available and it takes several minutes to timeout.

Output of console from the guest:
```
cirros-ds 'net' up at 8.57
checking http://169.254.169.254/2009-04-04/instance-id
failed 1/20: up 8.77. request failed
failed 2/20: up 12.08. request failed
failed 3/20: up 15.20. request failed
failed 4/20: up 18.42. request failed
failed 5/20: up 23.63. request failed
failed 6/20: up 28.87. request failed
failed 7/20: up 34.00. request failed
failed 8/20: up 37.13. request failed
failed 9/20: up 42.24. request failed
failed 10/20: up 47.37. request failed
failed 11/20: up 52.51. request failed
failed 12/20: up 57.63. request failed
failed 13/20: up 62.74. request failed
failed 14/20: up 67.89. request failed
failed 15/20: up 73.01. request failed
failed 16/20: up 76.14. request failed
failed 17/20: up 81.39. request failed
failed 18/20: up 86.55. request failed
failed 19/20: up 91.71. request failed
failed 20/20: up 96.85. request failed
failed to read iid from metadata. tried 20
no results found for mode=net. up 101.99. searched: nocloud configdrive ec2
failed to get instance-id of datasource
Top of dropbear init script
Starting dropbear sshd: failed to get instance-id of datasource
```

One possible solution is to modify `/etc/cirros-init/config` from

```
# must set DATASOURCE_LIST
DATASOURCE_LIST="nocloud configdrive ec2"
```

to look like this:

```
# must set DATASOURCE_LIST
DATASOURCE_LIST="nocloud"
```

**Comment by martinpitt** [comment]
Right now the image is a straight download, so for that we should introduce a .bootstrap script to do the customization (`virt-customize`).

If that doesn't work for whatever reason, an alternative is to use https://alpinelinux.org/downloads/ instead. The image is slightly bigger (32 MB vs. 20 MB for CirrOS), but it boots in a second to the login prompt.

**Comment by KKoukiou** [comment]
Copying from IRC the hints from @martinpitt 

(10:38:17 AM) pitti: kkoukiou: basically, adding a cirros.bootstrap with a curl to download the original  image (right now, that's not recorded anywhere) and use virt-customize to twiddle the data sources list
(10:38:24 AM) pitti: then bots/image-create cirros should produce a working image

**Comment by martinpitt** [comment]
Let's do this next week at the sprint together.

**Comment by martinpitt** [comment]
@KKoukiou started with this cirros.bootstrap script:

```
#! /bin/bash
set -ex

OUTPUT="$1"
VM_NAME=cirros

curl -O $OUTPUT https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-i386-disk.img

virt-edit -a $OUTPUT -e 's/nocloud\ configdrive\ ec2/nocloud/' /etc/cirros-init/config
```

It doesn't work, as virt-{edit,customize,...} don't get along with cirros images, it always fails with "no operating system found".

We also looked at other options, like FreeDOS (doesn't work with libvirt, as it doesn't get along with its console), TinyCore OS or Alpine (only offer iso images, which we'd need to convert). So IMHO the simplest solution is to create a local user-data that does the config seddery, and boot the image once with that.
