### ISSUE TITLE
Running cockpit on Freebsd/pfsense

### ISSUE THREAD

**Issue by Esteidinger** [cockpit-project/cockpit#9944]
Has anyone gotten cockpit running on freebsd? I would like to monitor my pfsense server to at the very least get CPU/Mem/IO and network data out of it.

**Comment by martinpitt** [comment]
Right now, cockpit has a lot of explicit and implicit dependencies on systemd and quite probably other Linux specific APIs. It's possible in principle to change the project to be able to build at least a relevant subset of the functionality, and provide a SysV init script (that part is the simplest thing of all really), but nobody has done that work to my knowledge.

**Comment by martinpitt** [comment]
Similar to #1438.

This would be an immense amout of work; not only the build, but also lots of pages assume systemd. This would basically require founding a FreeBSD/RHEL6/SysV Cockpit development team, which is way too big to be tracked as an issue.

**Comment by Dunky13** [comment]
I understand the problem. It is a shame though, as I'd love to manage my opnsense system as well as other linux systems. I hope you can add this in the future

**Comment by unix4you2** [comment]
Which alternative do you recomend?

**Comment by dR3b** [comment]
Monitoring: prometheus_sysctl_exporter" (in base system)
DB: proemtheus (ports: net-mgmt/prometheus2)
WebGUI: Grafana (ports: www/grafana)
