### ISSUE TITLE
cockpit-machines: Adding disk UI dialog propagates sometimes wrong values to the the underlying actions

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#9945]
When using existing volume, to attach disk to VM, sometimes the volume choice is not propagated correctly to the action, and this leads to unexpected behavior.

For this reason the testAddDisk non deterministically fails on "failed to add disk",  like the following error from the CI:

```
# testAddDisk (check_machines_virsh.TestMachinesVirsh)
#
ls: cannot access '/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_NESTED': No such file or directory
[0830/175627.716096:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:10159/devtools/browser/851419b5-eead-4781-9ff3-58bdedd38e78
[0830/175627.840369:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 216993: Permission denied (13)
[0830/175628.086883:ERROR:zygote_host_impl_linux.cc(267)] Failed to adjust OOM score of renderer with pid 217019: Permission denied (13)
> info: index.es6: Setting Libvirt as virt provider.
> warning: error: Failed to attach disk
error: internal error: unable to execute QEMU command 'device_add': Failed to get "write" lock

> warning: Disk failed to be attached with following error: error: Failed to attach disk
error: internal error: unable to execute QEMU command 'device_add': Failed to get "write" lock
> warning: 
Wrote screenshot to TestMachinesVirsh-testAddDisk-debian-testing-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestMachinesVirsh-testAddDisk-debian-testing-127.0.0.2-2201-FAIL.html
Wrote JS log to TestMachinesVirsh-testAddDisk-debian-testing-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachinesVirsh-testAddDisk-debian-testing-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/verify/machineslib.py", line 609, in testAddDisk
    b.wait_not_present("#cockpit_modal_dialog")
  File "/build/cockpit/test/common/testlib.py", line 283, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 274, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 271, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#cockpit_modal_dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 194, 'columnNumber': 9, 'scriptId': '15', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 193, 'columnNumber': 8}, {'functionName': 'window.setTimeout', 'scriptId': '15', 'url': '', 'lineNumber': 205, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'PhWaitCondTimeout: condition did not become true\n    at window.setTimeout (<anonymous>:206:24)', 'objectId': '{"injectedScriptId":5,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1535651789120.26, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '217019.8'}
info: index.es6: Setting Libvirt as virt provider.
warning: error: Failed to attach disk
error: internal error: unable to execute QEMU command 'device_add': Failed to get "write" lock

warning: Disk failed to be attached with following error: error: Failed to attach disk
error: internal error: unable to execute QEMU command 'device_add': Failed to get "write" lock
warning: 

not ok 219 testAddDisk (check_machines_virsh.TestMachinesVirsh) # duration: 119s


# Flake probability: 0.136 (clustering)
```

In this case the diskFileName passed from the dialog looks to be undefined although the user clearly clicked on specific volume from dropdown.

![testmachinesvirsh-testadddisk-debian-testing-127 0 0 2-2201-fail](https://user-images.githubusercontent.com/14921356/44903730-a9d09780-ad0d-11e8-8a17-5457512d9ce7.png)

**Comment by KKoukiou** [comment]
Just for completeness the component used for the dialog is DialogPattern and we are showing it with show_modal_dialog.

**Comment by martinpitt** [comment]
I investigated this a bit in #9952, but copying here for convenience:

Some notes:
 - I (locally, not pushed yet) added the same `_temporary` suffix to `mydiskofpoolone`, for the same reason. This makes no difference.
 - I added a `sit()` right before the adding of `mydiskofpooltwo_temporary` to the VM (i. e. before the block that fails). Waiting for several minutes makes no difference, so this is not a race condition in that block.
 - The file is *not* busy. The UI, `virsh dumpxml`, and `# fuser /mnt/*/*`all agree that the three other disks are busy (by the running qemu), but `mydiskofpooltwo_temporary` is not.
 - The three files which are being used are owned by `qemu:qemu (0600 perms)`, while `mydiskofpooltwo_temporary` is owned by root:root (0600 perms). This might explain the "write lock" error, as qemu is running as user `qemu` and cannot write that file. However, chowning it to `qemu:qemu` makes no difference, and after the failing test  something changes `mydiskofpooltwo_permanent` to root:root. But I think the permissions are a red herring.

This really looks like libvirt gets confused. The [debian-stable](https://fedorapeople.org/groups/cockpit/logs/pull-9952-20180903-020808-d8aeab39-verify-debian-stable/log.html#218) failure shows this - even though the test adds `mydiskofpooltwo_temporary`, the screenshot shows that it really seems to be `mydiskofpooltwo_permanent` *again*:

![screenshot](https://fedorapeople.org/groups/cockpit/logs/pull-9952-20180903-020808-d8aeab39-verify-debian-stable/TestMachines-testAddDisk-debian-stable-127.0.0.2-2901-FAIL.png)

As a result, I disable this fourth test case for now i #9952.

**Comment by martinpitt** [comment]
FTR, I can perfectly reproduce this on my current Fedora 28 laptop
```
libvirt-4.1.0-5.fc28.x86_64
qemu-system-x86-2.11.2-2.fc28.x86_64
```

**Comment by KKoukiou** [comment]
I didn't see this issue long time now. I think it might have been fixed with the change from the old modal dialog to patternfly modal. With that we changed a lot on how we propagate dialog state changes, so it could be related.
Closing since it looks resolved.
