### ISSUE TITLE
Topology tab not displaying in Cockpit UI 

### ISSUE THREAD

**Issue by reselbob** [cockpit-project/cockpit#9964]
Just a did a fresh install of cockpit and cockpit-docker on Linux box.

Topology tab is not showing up on the left side panel. The Container tab is.

Here is a link to the screen shot: https://drive.google.com/file/d/1QXhYPvuxnGH8ADwKwP-SIfDW78NV7KIO/view?usp=sharing

I admit to being a newbie. I am hoping to use the Topology view to visualize my pods under MiniKube which is installed directly on the box, not in a VM. I must be doing something very wrong. 

Help?

**Comment by reselbob** [comment]
I think this explains it

https://www.youtube.com/watch?v=7LMrK1mbhjo

Need to install cockpit-kubernetes

True?

**Comment by reselbob** [comment]
Ah, so cockpit-kubernetes is not support for Ubuntu?

**Comment by martinpitt** [comment]
Correct, this isn't packaged for Debian/Ubuntu. This is a duplicate of issue #6687
