### ISSUE TITLE
storage: RAID creation throws an error when I put a name with space in  the name

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#9976]
Whenever I put a space in the name of a RAID array I get an error.
The RAID still gets created though.

![screenshot from 2018-09-04 11-36-34](https://user-images.githubusercontent.com/209895/45023459-ce42b180-b036-11e8-8309-edb2e5af9bfc.png)

**Comment by marusak** [comment]
Still happens, lets just validate the raid name. I'll implement something simple.
