### ISSUE TITLE
Image refresh for openshift-prerelease

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#9980]
Image refresh for openshift-prerelease
 * [ ] FAIL: image-refresh openshift-prerelease

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-h079n.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9980-20180904-142626/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9980-20180904-142626/

**Comment by martinpitt** [comment]
kubevirt is gone now (PR #10085), so let's try this again.
