### ISSUE TITLE
firewalld: Add support for zones

### ISSUE THREAD

**Issue by Twiggled** [cockpit-project/cockpit#9982]
So basically I have setup my QEMU/KVM Servers.

VM1
VM2
VM3
VM4
and so on.
When I start firewalld these can no longer get external access for apt update but can still ping addresses outside the network.

Also I wanted to setup firewalld to so different interfaces pointed to different VMS for specific ports.
I have Eth0 with 10.0.0.10 and Eth0:1 with 10.0.0.11 for example.

So for instance. 
VM1 Ext IP: 10.0.0.10 port 80 to Int IP: 192.168.122.10 port 80
VM2 Ext IP: 10.0.0.11 port 80 to Int IP: 192.168.122.11 port 80

And so on.

However I can configure this with different zones in console but in cockpit it only seems to allow you to edit one default zone and no way to assign an interface to the zone. Is this a feature request or something I have setup incorrectly.

**Comment by KKoukiou** [comment]
@Gundersanne is this addressed already?

**Comment by Gundersanne** [comment]
This should now be possible :) 

You can activate multiple zones, each applying to a different interface or set/range of source addresses.

I'm closing this, if you encounter any trouble using the new firewall interface, please reopen or create a new issue.
